### ISSUE TITLE
[CI] DataLifecycleServiceIT testAutomaticForceMerge failing

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#96084] opened 2023-05-15 01:28 UTC
It failed on my PR. But I see it has failed on main as well. It does not reproduce. But since it is a new test, maybe there is something that experts can take a closer look.

**Build scan:**
https://gradle-enterprise.elastic.co/s/hwqc6m4l3z5s2/tests/:modules:dlm:internalClusterTest/org.elasticsearch.dlm.DataLifecycleServiceIT/testAutomaticForceMerge

**Reproduction line:**
```
./gradlew ':modules:dlm:internalClusterTest' --tests "org.elasticsearch.dlm.DataLifecycleServiceIT.testAutomaticForceMerge" -Dtests.seed=73A7958A5BFF3FAF -Dtests.locale=es -Dtests.timezone=Africa/Bissau -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.dlm.DataLifecycleServiceIT&tests.test=testAutomaticForceMerge

**Failure excerpt:**
```
java.lang.AssertionError: The segments for .ds-metrics-foo-2023.05.15-000001 were not merged
Expected: a value less than <1>
     but: <1> was equal to <1>

  at __randomizedtesting.SeedInfo.seed([73A7958A5BFF3FAF:87D280C491CE4F45]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.elasticsearch.dlm.DataLifecycleServiceIT.lambda$testAutomaticForceMerge$6(DataLifecycleServiceIT.java:343)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1158)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1131)
  at org.elasticsearch.dlm.DataLifecycleServiceIT.testAutomaticForceMerge(DataLifecycleServiceIT.java:325)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

**Comment by kingherc** [comment] 2023-05-16 08:51
Also at https://gradle-enterprise.elastic.co/s/kfx7tvtpvewqk/tests/:modules:dlm:internalClusterTest/org.elasticsearch.dlm.DataLifecycleServiceIT/testAutomaticForceMerge?top-execution=1 

```
java.lang.AssertionError: The segments for .ds-metrics-foo-2023.05.15-000001 were not merged |  
-- | --
  | Expected: a value less than <4> |  
  | but: <4> was equal to <4> |  

...

REPRODUCE WITH: ./gradlew ':modules:dlm:internalClusterTest' --tests "org.elasticsearch.dlm.DataLifecycleServiceIT.testAutomaticForceMerge" -Dtests.seed=9E737181F8C2F7E1 -Dtests.locale=pl -Dtests.timezone=Africa/Bamako -Druntime.java=17
```

Will mute.

**Comment by masseyke** [comment] 2023-05-18 16:56
In these two cases for some reason the index that is to be forcemerged has already been forcemerged (for example in the one where it expected less than 4 segments, the original number of segments had been 28). Almost immediately before, we had asserted that the number of segments had not changed during the previous DLM run. That makes me wonder if a forcemerge had happened before the first time DLM even ran.
I can't reproduce this locally, but my theory (which is really just a guess) is that this is a timing problem. We write data to the index, then immediately change a setting on the index that will cause the next lucene merge call to actually merge segments. My guess is that the setting change happens closely enough to the writes that lucene is still working, so it merges the segments on its own before we even do the request to get the number of segments. So the very first number of segments we get for the about-to-be-rolled-over index is the post-merge number. The first check passes because that number remains the same through DLM. Then the second check fails because additional forcemerging does not happen on the next DLM run.
I've made one change that I hope will fix this, and a few changes that will give us more information if it still fails. The change that I think will fix it is that I have moved the setting change until after we fetch the pre-DLM number of segments. This will make it so that there is more time after the index writes so that the lucene thread won't be active when we change the setting. It will also mean that the first check (the one for the number of shards of the rollover index) will fail if we still have a problem (and if I'm right that the merge happens before the first DLM run ever happens). I've also added some logging to give us a little more information.

For my own reference in case this doesn't fix it, here's what we're seeing (the entries with `*` are my guess about the state that the logging will hopefully tell us more about).

| Step | Expected num segments after step | Actual num segments after step |
| :---         |     :---      |          :--- |
| insert docs   | 28     | 28    |
| update setting     | 28       | 4*      |
| run DLM (rollover)     | 28       | 4*      |
| insert docs in next index   | 28     | 4    |
| run DLM (forcemerge)     | 4       | 4      |

**Comment by astefan** [comment] 2023-05-25 10:02
Failure in `main` again today

```
REPRODUCE WITH: ./gradlew ':modules:dlm:internalClusterTest' --tests "org.elasticsearch.dlm.DataLifecycleServiceIT.testAutomaticForceMerge" -Dtests.seed=F019798BEA1D6C1A -Dtests.locale=es-PY -Dtests.timezone=America/New_York -Druntime.java=20

org.elasticsearch.dlm.DataLifecycleServiceIT > testAutomaticForceMerge FAILED
    java.lang.AssertionError: The segments for .ds-metrics-foo-2023.05.25-000001 were not merged
    Expected: a value less than <4>
         but: <4> was equal to <4>
        at __randomizedtesting.SeedInfo.seed([F019798BEA1D6C1A:46C6CC5202C1CF0]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.elasticsearch.dlm.DataLifecycleServiceIT.lambda$testAutomaticForceMerge$6(DataLifecycleServiceIT.java:347)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1171)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1144)
        at org.elasticsearch.dlm.DataLifecycleServiceIT.testAutomaticForceMerge(DataLifecycleServiceIT.java:329)
```

CI build https://gradle-enterprise.elastic.co/s/xn3gyywktmac4

**Comment by masseyke** [comment] 2023-05-26 18:47
The additional logging showed that segments were unexpectedly being merged before DLM ever even ran and before the `index.merge.policy.merge_factor` setting was modified (i.e. the things with `*` in https://github.com/elastic/elasticsearch/issues/96084#issuecomment-1553343454 are actually correct). Rather than trying to figure out why lucene is doing that every once in a while, I've modified the test to just check at the transport layer whether the ForceMergeAction has been called -- it's outside of the scope of this test to check that lucene is actually doing what we want.

**Closed** 2023-05-26 19:25 UTC
Labels: >test-failure, Team:Data Management, :Data Management/DLM
