### ISSUE TITLE
Scripted Similarity variable to access count of matched words or word count of query

### ISSUE THREAD

**Issue by kkendzia** [elastic/elasticsearch#39894] opened 2019-03-11 06:58 UTC
As discussed and suggested in [elastic forum ](https://discuss.elastic.co/t/match-phrase-score-calculation/171243) I open a feature request regarding this topic.

It would be nice to have the possibility to access the exact amount of words which have been matched. Or maybe to access the number of terms in a query to calculate this score by dividing it with doc.freq. The use case has been created by our project lead who wants to have a word count score.

**Comment by jpountz** [comment] 2019-03-11 17:21
The issue is that the scripted similarity scores phrase like boolean queries (the BM25 similarity does the same). It makes some sense for BM25 and IDF-based weighting in general, but it's true it's not great when ignoring term statistics entirely.

I'd be ok with adding a boolean flag to this similarity to configure whether phrases should be scored like boolean queries, or whether we should assume that the frequency of the phrase is the frequency of its' rarest term.

**Comment by javanna** [comment] 2024-06-24 18:41
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.

**Closed by javanna** 2024-06-24 18:41 UTC
Labels: >enhancement, :Search/Ranking, Team:Search
