### ISSUE TITLE
Server crashes when doing "histogram" aggregation on date field with small interval

### ISSUE THREAD

**Issue by yaronuliel** [elastic/elasticsearch#21968] opened 2016-12-05 09:31 UTC
**Elasticsearch version**:
5.0.2

**Plugins installed**: []

**JVM version**:
Version 8 Update 112 (build 1.8.0_112-b16)

**OS version**:
macOS sierra Version 10.12.1 (16B2555)

**Description of the problem including expected versus actual behavior**:
I ran a search on an index with (only) 22 records, the search included `histogram` aggregation on a field with date mapping using the default structure that Kibana generates for histogram aggregation

```
"histogram": {
    "field": "birthdate",
    "interval": 50
}
```

I expected it to either throw an error (using `histogram` instead of `date_histogram` on a field that was mapped as `date`) - or, return the values as I requested (if you regard this as a valid query)
Instead, I didn't get any result until the server crashed

**Steps to reproduce**:
 1. Create index with a field that has a date mapping
```
PUT /someindex/
{
   "mappings": {
      "sometype": {
         "properties": {
            "birthdate": {
               "type": "date",
               "format": "dateOptionalTime"
            }
         }
      }
   }
}
```

 2. Index some documents in the index (issue didn't happen with 0 or 1 records in the index)

 3. Run this query
```
GET /sports/_search
{
  "query":{
    "match_all": {}
  },
  "size":0,
  "aggs": {
    "dh": {
      "histogram": {
        "field": "birthdate",
        "interval": 50
      }
    }
  }
}
```
4. There is no response, and eventually the server crashes

**Logs:**
```
[2016-12-05T11:15:17,749][INFO ][o.e.m.j.JvmGcMonitorService] [DSSchuT] [gc][532] overhead, spent [317ms] collecting in the last [1.2s]
[2016-12-05T11:26:01,322][INFO ][o.e.c.m.MetaDataCreateIndexService] [DSSchuT] [sports] creating index, cause [api], templates [], shards [5]/[1], mappings [athlete]
[2016-12-05T11:26:51,655][WARN ][o.e.m.j.JvmGcMonitorService] [DSSchuT] [gc][1224] overhead, spent [511ms] collecting in the last [1s]
[2016-12-05T11:26:52,657][INFO ][o.e.m.j.JvmGcMonitorService] [DSSchuT] [gc][young][1225][5] duration [747ms], collections [1]/[1s], total [747ms]/[1.6s], memory [339.6mb]->[714mb]/[1.9gb], all_pools {[young] [2mb]->[138.3mb]/[266.2mb]}{[survivor] [33.2mb]->[33.2mb]/[33.2mb]}{[old] [304.3mb]->[542.4mb]/[1.6gb]}
[2016-12-05T11:26:52,657][WARN ][o.e.m.j.JvmGcMonitorService] [DSSchuT] [gc][1225] overhead, spent [747ms] collecting in the last [1s]
[2016-12-05T11:26:53,661][INFO ][o.e.m.j.JvmGcMonitorService] [DSSchuT] [gc][young][1226][6] duration [864ms], collections [1]/[1s], total [864ms]/[2.5s], memory [714mb]->[970.1mb]/[1.9gb], all_pools {[young] [138.3mb]->[162.9mb]/[266.2mb]}{[survivor] [33.2mb]->[33.2mb]/[33.2mb]}{[old] [542.4mb]->[773.8mb]/[1.6gb]}
[2016-12-05T11:26:53,661][WARN ][o.e.m.j.JvmGcMonitorService] [DSSchuT] [gc][1226] overhead, spent [864ms] collecting in the last [1s]
[2016-12-05T11:26:55,279][WARN ][o.e.m.j.JvmGcMonitorService] [DSSchuT] [gc][young][1227][7] duration [1.5s], collections [1]/[1.6s], total [1.5s]/[4s], memory [970.1mb]->[1gb]/[1.9gb], all_pools {[young] [162.9mb]->[4.4mb]/[266.2mb]}{[survivor] [33.2mb]->[33.2mb]/[33.2mb]}{[old] [773.8mb]->[1gb]/[1.6gb]}
[2016-12-05T11:26:55,280][WARN ][o.e.m.j.JvmGcMonitorService] [DSSchuT] [gc][1227] overhead, spent [1.5s] collecting in the last [1.6s]
[2016-12-05T11:26:56,430][WARN ][o.e.m.j.JvmGcMonitorService] [DSSchuT] [gc][young][1228][8] duration [1s], collections [1]/[1.1s], total [1s]/[5s], memory [1gb]->[1.3gb]/[1.9gb], all_pools {[young] [4.4mb]->[4.7mb]/[266.2mb]}{[survivor] [33.2mb]->[33.2mb]/[33.2mb]}{[old] [1gb]->[1.2gb]/[1.6gb]}
[2016-12-05T11:26:56,430][WARN ][o.e.m.j.JvmGcMonitorService] [DSSchuT] [gc][1228] overhead, spent [1s] collecting in the last [1.1s]
[2016-12-05T11:26:58,003][WARN ][o.e.m.j.JvmGcMonitorService] [DSSchuT] [gc][young][1229][9] duration [1s], collections [1]/[1.5s], total [1s]/[6s], memory [1.3gb]->[1.5gb]/[1.9gb], all_pools {[young] [4.7mb]->[4.9mb]/[266.2mb]}{[survivor] [33.2mb]->[33.2mb]/[33.2mb]}{[old] [1.2gb]->[1.5gb]/[1.6gb]}
[2016-12-05T11:26:58,004][WARN ][o.e.m.j.JvmGcMonitorService] [DSSchuT] [gc][1229] overhead, spent [1s] collecting in the last [1.5s]
[2016-12-05T11:27:02,508][WARN ][o.e.m.j.JvmGcMonitorService] [DSSchuT] [gc][1230] overhead, spent [4.3s] collecting in the last [4.5s]
[2016-12-05T11:27:06,409][WARN ][o.e.m.j.JvmGcMonitorService] [DSSchuT] [gc][1231] overhead, spent [3.7s] collecting in the last [3.9s]
[2016-12-05T11:27:11,770][WARN ][o.e.m.j.JvmGcMonitorService] [DSSchuT] [gc][1232] overhead, spent [4.5s] collecting in the last [5.3s]
[2016-12-05T11:27:15,295][WARN ][o.e.m.j.JvmGcMonitorService] [DSSchuT] [gc][1233] overhead, spent [3.5s] collecting in the last [3.5s]
[2016-12-05T11:27:51,842][WARN ][o.e.m.j.JvmGcMonitorService] [DSSchuT] [gc][1234] overhead, spent [4.4s] collecting in the last [4.4s]
java.lang.OutOfMemoryError: Java heap space
Dumping heap to java_pid58913.hprof ...
Heap dump file created [172966857 bytes in 37.036 secs]
[2016-12-05T11:29:11,594][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [] fatal error in thread [elasticsearch[DSSchuT][search][T#3]], exiting
java.lang.OutOfMemoryError: Java heap space
[2016-12-05T11:29:11,603][WARN ][o.e.m.j.JvmGcMonitorService] [DSSchuT] [gc][1235] overhead, spent [1.8m] collecting in the last [1.8m]
[2016-12-05T11:29:11,594][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [] fatal error in thread [elasticsearch[DSSchuT][management][T#2]], exiting
java.lang.OutOfMemoryError: Java heap space
	at java.util.HashMap$EntrySet.iterator(HashMap.java:1013) ~[?:1.8.0_112]
	at org.elasticsearch.common.settings.Settings.convertMapsToArrays(Settings.java:151) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.common.settings.Settings.convertMapsToArrays(Settings.java:166) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.common.settings.Settings.getAsStructuredMap(Settings.java:104) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.common.settings.Settings.toXContent(Settings.java:574) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.action.admin.cluster.node.info.NodesInfoResponse.toXContent(NodesInfoResponse.java:93) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.rest.action.RestActions.nodesResponse(RestActions.java:183) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.rest.action.RestActions$NodesResponseRestListener.buildResponse(RestActions.java:278) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.rest.action.RestActions$NodesResponseRestListener.buildResponse(RestActions.java:269) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.rest.action.RestBuilderListener.buildResponse(RestBuilderListener.java:38) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.rest.action.RestResponseListener.processResponse(RestResponseListener.java:37) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.rest.action.RestActionListener.onResponse(RestActionListener.java:47) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:91) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:87) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.action.support.TransportAction$ResponseFilterChain.proceed(TransportAction.java:224) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.action.ingest.IngestActionFilter.apply(IngestActionFilter.java:89) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.action.support.TransportAction$ResponseFilterChain.proceed(TransportAction.java:222) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.action.support.TransportAction$FilteredActionListener.onResponse(TransportAction.java:249) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.action.support.TransportAction$FilteredActionListener.onResponse(TransportAction.java:235) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.finishHim(TransportNodesAction.java:262) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.onOperation(TransportNodesAction.java:237) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.access$200(TransportNodesAction.java:160) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$1.handleResponse(TransportNodesAction.java:214) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$1.handleResponse(TransportNodesAction.java:206) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:951) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1028) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1012) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1002) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.transport.DelegatingTransportChannel.sendResponse(DelegatingTransportChannel.java:58) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.transport.RequestHandlerRegistry$TransportChannelWrapper.sendResponse(RequestHandlerRegistry.java:111) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:270) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:266) ~[elasticsearch-5.0.2.jar:5.0.2]
```

**Comment by dadoonet** [comment] 2016-12-05 09:34
Do you really intend to generate a bucket for every `50ms`?
Why not using BTW a `date_histogram` here?

**Comment by yaronuliel** [comment] 2016-12-05 09:36
No, I didn't - it was part of a training session, but still - I didn't expect it to crash
If, as you say, this isn't a reasonable query - it should be possible, especially when considering that `date_histogram` is available
(eventually I realized where my problem was - but still...)

**Comment by synhershko** [comment] 2016-12-05 09:38
@dadoonet I believe the issue here is that it crashed, not that it failed to generate the buckets :)

**Comment by dadoonet** [comment] 2016-12-05 09:41
Yeah I agree. I did not close the issue :)
I was just surprised by the request itself...

It crashes with OOM and we could expect probably to have a circuit breaker here...

@jpountz WDYT?

**Comment by jpountz** [comment] 2016-12-05 10:21
To me the problem here is not related to the circuit breakers but more to the fact that running aggs on such a small dataset (22 records) should allocate very little memory, yet this managed to trigger an OOME. We should dig...

**Comment by synhershko** [comment] 2016-12-05 11:03
@jpountz this is because the amount of buckets that's being generated is immense. You can reproduce this with date_histogram for example and 2 documents, one with a 2000 date and one with 2010 date. Then run with monthly interval. The threshold on number of buckets counts the ones with values, and ignores the empty ones.

**Comment by jpountz** [comment] 2016-12-05 11:28
Oh I see, thanks @synhershko. I was confused because I thought the OOME occurred when computing the buckets, in spite of the fact we use a sparse encoding. But the OOME actually occurs when generating the response, since we fill gaps with empty buckets.

Relates to #10904

**Comment by zjxlinux** [comment] 2017-12-27 06:10
Is it possible that the query cache(indices.breaker.request.limit which default to 40% of the heap space) plus the used segment memory already over 100% of the heap space,  that is why there is no circuit breaker here

**Comment by colings86** [comment] 2018-03-13 13:48
https://github.com/elastic/elasticsearch/pull/27581 has fixed this issue and the above recreation now (since 6.2.0) results in the following response to the client and no OOME on the server:
```
{
  "error": {
    "root_cause": [],
    "type": "search_phase_execution_exception",
    "reason": "",
    "phase": "fetch",
    "grouped": true,
    "failed_shards": [],
    "caused_by": {
      "type": "too_many_buckets_exception",
      "reason": "Trying to create too many buckets. Must be less than or equal to: [10000] but was [10001]. This limit can be set by changing the [search.max_buckets] cluster level setting.",
      "max_buckets": 10000
    }
  },
  "status": 503
}
```

**Closed by colings86** 2018-03-13 13:48 UTC
Labels: :Core/Circuit Breakers, :Search/Aggregations, discuss

**Comment by synhershko** [comment] 2018-03-13 14:11
@colings86 thanks! wouldn't it make sense to backport this to 5.x and 6.0/6.1?

**Comment by colings86** [comment] 2018-03-14 09:37
@synhershko 6.0 and 6.1 are not maintained as of the release of 6.2 and therefore do not receive bug fixes. 

The 5.6 branch is maintained but only to receive critical bug fixes. Although this enhancement is a big improvement the change for it was not straight-forward and back-porting this change to 5.6 would be tricky and high risk and we don't back port enhancements to bug fix releases as a rule. Additionally the enhancement is a breaking change which is not something we include in bug fix releases.
