### ISSUE TITLE
Factor GC overhead in circuit breakers

### ISSUE THREAD

**Issue by Bukhtawar** [elastic/elasticsearch#40115] opened 2019-03-15 19:23 UTC
### Problem Description
There are a bunch of circuit breakers that track for estimated bytes consumed for major memory contributors but there is still room for unaccounted memory #35564, #20837, #20250 etc. The newly introduced real circuit breaker #31767 isn't foolproof as large time gaps between reservation and actual allocation can cause few bulky concurrent request to cause OOM.

### Proposal
Since large GC overhead is an early sign of struggling GC and non-collectible heap which may keep on growing. The proposal is to factor in overhead in addition to actual heap consumption based on user configurable setting `gc_overhead_threshold` to detect symptoms early. If the node is already running a high GC overhead based on weighed average of past few GC runs we start to trip requests on the node.

**Comment by Bukhtawar** [comment] 2019-04-11 19:31
Summarizing the proposal
1. Compute EWMA of `avg_collection_time = collection_time / collections` (measure of GC effectiveness) and `overhead = 100 * current_gc_collection_time / time_elapsed`(measure of GC throughput) per GC and possibly expose this metrics via `/_node/stats` API. The computations are the same from `JVMGcMonitorService` which currently only serves for logging
2. The circuit breaker can start to trip request based on configurable thresholds(controlled probably through new settings) or leveraging `monitor.jvm.*` settings consuming the above stats.
3. Since we are tripping requests to avoid nodes from going OOM it could also so happen that the garbage is non-collectible(possible memory leaks) or stays longer(#35564) and the node takes a fairly longer time to go OOM(longer outages), the node should gracefully shutdown if even after tripping requests the node is unable to recover from slow/long GCs based on the stats from [1] and thresholds from [2]
4. The nodes can be re-started the same way as OOM scenarios(mostly externally)

@not-napoleon  Please share your thoughts on the same

**Comment by Bukhtawar** [comment] 2019-04-16 06:55
Hi @not-napoleon please let me know what you think on the proposal. I'll be more that happy to work on the PR

**Comment by not-napoleon** [comment] 2019-04-16 13:59
@jaymode Would you mind commenting on this?  I labeled it when it came in, but it's not really in my focus area and I don't have a good sense of what the right direction is.

**Comment by jaymode** [comment] 2019-04-16 14:05
Hi @Bukhtawar, thanks for opening the issue and providing an idea. We'll plan to discuss this as a team and summarize our thoughts after we've discussed. @danielmitterdorfer @dakrone you may be interested in this based on the work you've done on circuit breakers in the past.

**Comment by Bukhtawar** [comment] 2019-04-26 17:51
Hi @jaymode @danielmitterdorfer @dakrone, did we get a chance to review this. I'm awaiting a response on the proposal.

**Comment by jpountz** [comment] 2019-06-14 14:29
We discussed it in FixitFriday and made the following points:
 - the real-memory circuit breaker is expected to already helping with this since GC pressure typically correlates with high-memory usage
 - the problem is that circuit breakers don't intercept all memory allocations, some of the linked issues are about deserializing mappings for instance, which doesn't try to let circuit breakers know about memory allocations - this is a very hard problem to solve with complex graphs of tiny Java objects
 - we don't see a path forward that wouldn't also increase the risk that we prevent a request that would have run fine otherwise

As a consequence we decided not to move forward on this and close the issue. Thank you for bringing this up though @Bukhtawar!

**Closed by jpountz** 2019-06-14 14:29 UTC
Labels: :Core/Infra/Circuit Breakers, discuss
