### ISSUE TITLE
Can ZGC provide better performance improvement for es? Whether to consider some adjustments for ZGC in the optimization strategy

### ISSUE THREAD

**Issue by lsygxw** [elastic/elasticsearch#58989] opened 2020-07-03 02:57 UTC
Two months ago, I changed the GC of es to ZGC. After observation, I found that on high-performance machines, the management of heap memory is better than G1. Although it is no longer compatible with pointer compression, it can be improved on high-performance machines. The heap uses some memory-for-speed scenarios to adapt to frequent aggregation fields.

**Comment by gwbrown** [comment] 2020-07-06 22:56
We work hard to evaluate new garbage collection algorithms available in [our supported JVMs](https://www.elastic.co/support/matrix#matrix_jvm) and recommend them only when we have been able to test our systems thoroughly for negative interactions. At this time, we cannot recommend use of ZGC with Elasticsearch, because we have not evaluated and tested it thoroughly enough to make that recommendation. While Elasticsearch may run with ZGC, you may run into unexpected behavior, performance issues, or bugs that are specific to ZGC.

If and when we've determined that Elasticsearch is stable with ZGC, or any other new GC algorithm, we'll make a formal announcement of that fact. To prevent confusion, I'm going to close this issue.

If you want to discuss alternative GC strategies, there's an active community in the [forums](https://discuss.elastic.co/) that I highly recommend - it is frequented by many Elastic Stack power users and developers.

**Closed by gwbrown** 2020-07-06 22:56 UTC
Labels: :Core/Infra/Core, >enhancement

**Comment by souradeep07** [comment] 2026-07-15 18:56
Are there any plans to support zgc with elastic search? In the near future?
