### ISSUE TITLE
Add K-means clustering feature

### ISSUE THREAD

**Issue by geekpete** [elastic/elasticsearch#5512] opened 2014-03-24 11:26 UTC
Add k-means clustering to allow detection of clusters in data sets.
http://en.wikipedia.org/wiki/K-means_clustering

Would be useful for geo points but also other use cases too.

Thanks to https://github.com/koobs for suggesting this one in Sydney Elastic Training.

**Comment by yehosef** [comment] 2015-06-29 08:09
just found this - would be great. +1

**Comment by dsingley** [comment] 2015-10-09 15:20
+1

**Comment by redmouthch** [comment] 2015-10-12 19:02
search for this... this would be a very great feature. Also other Mining-algorithms.

**Comment by colings86** [comment] 2015-11-13 10:53
Implementing this as a pipeline aggregation should now be possible. In that case we would first collect values into buckets using other aggregations and then use the pipeline aggregation to create clusters from those buckets.

**Comment by lessless** [comment] 2015-12-20 14:35
that would be mad!

**Comment by lessless** [comment] 2015-12-30 09:54
@koobs is there a recording of this session somewhere out there?

**Comment by koobs** [comment] 2015-12-30 12:43
@lessless I hope not :)

**Comment by irony** [comment] 2016-01-27 17:57
This would really be awesome!

**Comment by audriusb** [comment] 2016-03-10 06:47
+1

**Comment by reinier-pv** [comment] 2016-03-10 13:02
:+1:

**Comment by trupin** [comment] 2016-04-09 10:43
+1

**Comment by chenryn** [comment] 2016-04-28 07:18
+1

**Comment by marfago** [comment] 2016-05-04 15:54
+1

**Comment by hkulekci** [comment] 2016-05-09 15:38
+1

**Comment by Amazium** [comment] 2016-06-23 10:40
+1

**Comment by s1monw** [comment] 2016-07-01 09:59
I am removing the discuss label and make it adopt me - there has been enough discussion on this.

**Comment by ryanrozich** [comment] 2016-07-04 03:55
+1 carrot2 is good for text clustering but does not use the aggregations framework, would be great to have a text clustering option that we can build sub-aggregations / child aggregations underneath.

**Comment by lessless** [comment] 2016-08-11 05:05
will we be able to use it for geopoints?

**Comment by SimoneTosato** [comment] 2016-10-07 11:05
+1

**Comment by ddavidebor** [comment] 2016-10-07 11:22
+1 This feature would be so helpful and powerful

**Comment by diugalde** [comment] 2016-10-14 07:46
What happened with this feature? Is there any work in progress? I think it would be really useful.

**Comment by tol** [comment] 2017-03-13 20:48
+1

**Comment by nknize** [comment] 2017-03-13 23:25
It's certainly gotten some attention. While a bit stalled at the moment, due to other priorities, @colings86 has a branch for geo_point k-means: https://github.com/colings86/elasticsearch/tree/feature/geokmeans

So a little more patience and this feature will be available soon.

**Comment by sebastianovide** [comment] 2017-06-28 15:58
+1

**Comment by mkarakucuk** [comment] 2017-07-28 11:15
+1

**Comment by A-Tokyo** [comment] 2017-11-24 11:10
+1

**Comment by vasily-kirichenko** [comment] 2017-12-18 20:51
+1

**Comment by ItshakEli** [comment] 2017-12-24 12:18
+1

**Comment by debb-hp-com** [comment] 2018-01-09 07:46
+1

**Comment by lessless** [comment] 2018-01-09 08:18
@nknize, @colings86 pushed last update to his branch in Jul '17. Is it ready or forced out by the higher-priority work?

**Comment by colings86** [comment] 2018-01-09 08:32
@lessless There has not yet been further work on this and its still a little way off. There are actually other cluster-like aggregations which are likely to be merged first as they are a bit simpler to implement (e.g. https://github.com/elastic/elasticsearch/pull/26659) as they are a bit easier to validate and test for a first implementation of aggregations which merge buckets at collection-time. Although we would like to make progress here, its not something that is being currently tackled as a main task due to other priorities

**Comment by geekpete** [comment] 2018-01-09 08:55
Could we collate potential future features on a special section of the roadmap perhaps?
This ticket could be closed and referenced to the "potential future features" area of the roadmap. This might help to clear a number of other github tickets that don't have major focus if priority is on other work at the moment.

**Comment by colings86** [comment] 2018-03-13 11:54
Stalled waiting on https://github.com/elastic/elasticsearch/pull/26659

/cc @elastic/es-search-aggs

**Comment by lessless** [comment] 2018-09-10 00:53
Still desired :)

**Comment by LaurentChardin** [comment] 2018-10-11 10:41
Indeed !! very desired !

**Comment by lessless** [comment] 2018-10-11 10:52
@colings86 should "stalled" label be removed now? #26659 was closed in favor of #28993 which is merged now

**Comment by colings86** [comment] 2018-10-12 09:33
It is true that because #28993 is merged the "stalled" label can be removed.

**Comment by Destroy666x** [comment] 2018-10-22 15:17
I also confirm it's very desired.

**Comment by abhilash1994** [comment] 2018-12-03 17:48
+1 for this

**Comment by ThomasSolti** [comment] 2019-01-22 11:10
+1

**Comment by barracuda317** [comment] 2019-02-22 15:45
Is the size parameter in https://www.elastic.co/guide/en/elasticsearch/reference/7.0/search-aggregations-bucket-geotilegrid-aggregation.html something like k-means-clustering for geo-search?

**Comment by polyfractal** [comment] 2019-02-22 16:16
@barracuda317 Not really, no.  GeoTile just overlays a fixed grid over the area and aggregates documents into those grid cells.  The grids are constructed irregardless of the data distribution (think of it more like a heatmap).

Clustering like k-means dynamically identifies regions of data that are "similar" and groups them together into a cluster.  Clustering can give you individual clusters that are different shapes, sizes, and densities.  For a practical example, a clustering algo might group all the values inside a city together, then cluster the rural countryside together as a different group (much larger but also more sparse)

**Comment by jamesdorfman** [comment] 2019-04-17 21:19
@colings86 is there a reason why this was never completed? If the issue is time commitment, I'm very interested in this feature and would like to try finishing the implementation.

**Comment by mayya-sharipova** [comment] 2019-04-18 08:30
@jamesdorfman  Can you please describe your use case. Are you interested to have k-means clustering of geo data (they can be up to 8 dims)?

**Comment by lessless** [comment] 2019-04-18 11:10
@mayya-sharipova +1 to exactly that use case

**Comment by jamesdorfman** [comment] 2019-04-19 04:16
@mayya-sharipova yes, I was specifically interested in implementing the geo data use case. This thread made it seem as though this specific feature is highly desired.

Furthermore, I'm not completely certain about how difficult this will be to implement, so I also think that the restricted use case of clustering only geo data is a good starting point.

**Comment by LaurentChardin** [comment] 2019-04-21 21:05
Another use case was to group ranges of prices of products within an index, and use k-cluster to propose cluster of prices to use with price selection.

**Comment by jamesdorfman** [comment] 2019-05-01 06:09
Upon further research and experimentation it seems that a more straightforward approach would be to implement an agglomerative hierarchical clustering algorithm, rather than k-means clustering.

K-means involves creating k buckets, and then reassigning data points at each iteration of the algorithm. On the other hand, in agglomerative hierarchical clustering each point is initially placed in its own cluster. Then, these clusters are merged together on subsequent iterations.
https://en.wikipedia.org/wiki/Hierarchical_clustering

I am currently working on implementing this clustering feature as a histogram bucket aggregation. The K-means approach would involve moving data between buckets at each iteration, However, the hierarchical method would simply entail creating a bucket for each point and then merging them until the desired number of buckets is reached. This functionality is very similar to the existing Auto Date Histogram Aggregation, where buckets are created and then merged. Since bucket merging functionality was already created for this algorithm, this approach is significantly easier to implement.

Furthermore, it seems that both methods can produce clusters of similar quality. https://www.cs.utah.edu/~piyush/teaching/4-10-print.pdf

Please let me know if this line of reasoning makes sense :)

**Comment by arshad171** [comment] 2019-09-04 11:33
@jamesdorfman Isn't Agglomerative Hierarchical Clustering expensive in terms time and space complexities compared to K-means?

Agglomerative clustering:
time complexity: O(n^3)
space complexity: O(n^2)

K-means:
time complexity: O(n * k * m)
space complexity: O((n + k)m)

And since K-means has implementations that support incremental learning, the space complexity can be further reduced to make it constant.

**Comment by sroui** [comment] 2021-01-01 19:16
+1

**Comment by geekpete** [comment] 2023-09-10 00:37
Do we think this issue is still relevant? I see it's now 10 years ago that I first opened it.

**Comment by ddavidebor** [comment] 2023-09-12 22:07
This brings back so many memories...

**Comment by wchaparro** [comment] 2024-01-05 14:57
Closing this as not planned in Aggregations. If we are going to develop this - it will go into ES|QL, where we are focusing future development.

**Closed by wchaparro** 2024-01-05 14:57 UTC
Labels: >feature, help wanted, :Analytics/Aggregations, Team:Analytics

**Comment by koobs** [comment] 2024-01-15 06:25
😢

**Comment by geekpete** [comment] 2024-07-29 01:34
hmm... https://github.com/apache/lucene/pull/13604
