### ISSUE TITLE
[CI] MixedClusterClientYamlTestSuiteIT test {p0=suggest/30_context/Multi contexts should work} failing

### ISSUE THREAD

**Issue by piergm** [elastic/elasticsearch#100692] opened 2023-10-11 14:56 UTC
**Build scan:**
https://gradle-enterprise.elastic.co/s/km3d3w5n4vfs2/tests/:qa:mixed-cluster:v7.17.15%23mixedClusterTest/org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT/test%20%7Bp0=suggest%2F30_context%2FMulti%20contexts%20should%20work%7D
**Reproduction line:**
```
./gradlew ':qa:mixed-cluster:v7.17.15#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=suggest/30_context/Multi contexts should work}" -Dtests.seed=26EC07F1DDEFAF7B -Dtests.bwc=true -Dtests.locale=no-NO -Dtests.timezone=Asia/Urumqi -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT&tests.test=test%20%7Bp0%3Dsuggest/30_context/Multi%20contexts%20should%20work%7D
**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([26EC07F1DDEFAF7B]:0)

```

**Comment by benwtrent** [comment] 2023-10-12 13:13
This is yet another mixed cluster timeout. I honestly don't think all these tests that suffer from 

> Test abandoned because suite timeout was reached.

Are the cause. The suite is just taking a long cumulative time and timing out.

[2023-10-11T19:47:42,973][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] [test] [p0=suggest/30_context/Multi contexts should work] before test
[2023-10-11T19:47:44,121][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] [test] [p0=suggest/30_context/Multi contexts should work] after test

This test individually didn't cause a timeout of 2400000ms (20 minutes). Closing this issue. 

We should collate all these Suite timeouts into a single thing that aims to either make all our tests faster or improve the infra.

**Closed by benwtrent** 2023-10-12 13:13 UTC
Labels: blocker, :Search/Suggesters, >test-failure, Team:Search
