### ISSUE TITLE
[Ml] CircuitBreakingException when deploying the ELSER model

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#99409] opened 2023-09-11 09:14 UTC
### Elasticsearch Version

8.9.1

### Java Version

_bundled_

### OS Version

any

### Problem Description

Deploying the ELSER model can cause a `CircuitBreakingException` if the cluster is being used heavily. Often the `CircuitBreakingException` is thrown because a request from Kibana or another client cannot be serviced with the available memory while loading the ELSER model which temporarily increases memory pressure in the JVM. In this scenario Kibana becomes unresponsive but in many cases the ELSER model deployment completes successfully but the UI takes a while to see that status change. 

```
Caused by: org.elasticsearch.common.breaker.CircuitBreakingException: [parent] Data too large, data for [indices:data/read/search[phase/query]] would be [1045092822/996.6mb], which is larger than the limit of [1020054732/972.7mb], real usage: [1045091992/996.6mb], new bytes reserved: [830/830b], usages [eql_sequence=0/0b, fielddata=1779/1.7kb, request=0/0b, inflight_requests=830/830b, model_inference=0/0b] at org.elasticsearch.indices.breaker.HierarchyCircuitBreakerService.checkParentLimit(HierarchyCircuitBreakerService.java:414)
```

### Steps to Reproduce

The problem occurs more commonly on smaller nodes with less JVM heap memory (e.g. 2GB JVM heap). Reproduce by repeatedly deploying and un-deploying the ELSER model.

**Comment by droberts195** [comment] 2023-09-11 09:35
Some ideas to fix this:

1. Index ELSER in smaller blocks. So change https://github.com/elastic/elasticsearch/blob/d0186e612f15e612ddf4b08c5cf538f892cbe26f/x-pack/plugin/ml-package-loader/src/main/java/org/elasticsearch/xpack/ml/packageloader/action/ModelImporter.java#L43 to 2MB instead of 4MB for example. We’ll need to do twice as many searches as before but each will (hopefully) use half the amount of memory.
2. Add a small delay in between the chunks. This will mean that the `PyTorchStateStreamer` will need a `ThreadPool` member. We’ll have to pass one in through its constructor, and the constructors of all the wrapping classes back to `MachineLearning`. Then it will be possible to use `scheduleWithFixedDelay` - see https://github.com/elastic/elasticsearch/blob/11b6db3dfe656deb8e868fe3b88d4a6ef35ae255/server/src/main/java/org/elasticsearch/threadpool/ThreadPool.java#L536 - to add a random delay of between 5 and 20 milliseconds between searches. Hopefully that slowdown will give the data node some time to garbage collect.
3. Finally, when the search response is a circuit breaker exception, can we retry it? Once we have delays between searches, it shouldn’t be that hard to increase the delay to a random number of seconds between 3 and 7, and retry the exact same search again instead of moving to the next one. We don’t want to do this forever, but up to 5 retries per model load would be reasonable if we think the cause of the problem is that the data node is under transient pressure.

**Comment by davidkyle** [comment] 2023-09-18 09:18
Related to #99592

**Closed** 2023-09-22 15:09 UTC
Labels: >bug, :ml, Team:ML
