### ISSUE TITLE
Multiple :docs:yamlRestTest failures on 8.5 CI

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#92448] opened 2022-12-19 13:52 UTC
### CI Link

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+8.5+periodic+release-tests/177/consoleFull

### Repro line

./gradlew ':docs:yamlRestTest' --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/ingest/line_986}" \   -Dtests.seed=2B9A522979DA8E8C \   -Dbuild.snapshot=false \   -Dtests.jvm.argline="-Dbuild.snapshot=false" \   -Dtests.locale=ar-SA \   -Dtests.timezone=Etc/UCT \   -Druntime.java=17

### Does it reproduce?

Didn't try

### Applicable branches

8.5

### Failure history

Started on Dec 17

### Failure excerpt

14:16:50 REPRODUCE WITH: ./gradlew ':docs:yamlRestTest' --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/ingest/line_986}" -Dtests.seed=2B9A522979DA8E8C -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dtests.locale=ar-SA -Dtests.timezone=Etc/UCT -Druntime.java=17
14:16:50 
14:16:50 org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT > test {yaml=reference/ingest/line_986} FAILED
14:16:50     java.lang.RuntimeException: Failure at [reference/ingest:892]: stashed value not found for key [body.sample_start]
14:16:50         at __randomizedtesting.SeedInfo.seed([2B9A522979DA8E8C:A3CE6DF3D726E374]:0)
14:16:50         at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:512)
14:16:50         at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:479)
14:16:50         at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
14:16:50         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:16:50         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
14:16:50         at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
14:16:50         at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
14:16:50         at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
14:16:50         at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
14:16:50         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
14:16:50         at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
14:16:50         at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
14:16:50         at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
14:16:50         at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
14:16:50         at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
14:16:50         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
14:16:50         at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
14:16:50         at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
14:16:50         at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
14:16:50         at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
14:16:50         at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
14:16:50         at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
14:16:50         at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
14:16:50         at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
14:16:50         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
14:16:50         at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
14:16:50         at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
14:16:50         at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
14:16:50         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
14:16:50         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
14:16:50         at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
14:16:50         at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
14:16:50         at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
14:16:50         at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
14:16:50         at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
14:16:50         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
14:16:50         at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
14:16:50         at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
14:16:50         at java.base/java.lang.Thread.run(Thread.java:833)
14:16:50 
14:16:50         Caused by:
14:16:50         java.lang.IllegalArgumentException: stashed value not found for key [body.sample_start]
14:16:50             at org.elasticsearch.test.rest.Stash.unstash(Stash.java:110)
14:16:50             at org.elasticsearch.test.rest.Stash.getValue(Stash.java:86)
14:16:50             at org.elasticsearch.test.rest.Stash.getValue(Stash.java:179)
14:16:50             at org.elasticsearch.test.rest.Stash.unstashObject(Stash.java:149)
14:16:50             at org.elasticsearch.test.rest.Stash.replaceStashedValues(Stash.java:121)
14:16:50             at org.elasticsearch.test.rest.yaml.section.Assertion.resolveExpectedValue(Assertion.java:42)
14:16:50             at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:65)
14:16:50             at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:499)
14:16:50             ... 38 more
14:16:51 
14:16:51 > Task :modules:lang-painless:jarHell
14:16:51 > Task :modules:lang-painless:licenseHeaders

**Comment by craigtaverner** [comment] 2022-12-20 14:21
Looks like duplicate of https://github.com/elastic/elasticsearch/issues/92415

**Comment by craigtaverner** [comment] 2022-12-20 14:25
There is a similar issue that has been worked on since the summer, with multiple fixes. A recent PR was merged to 8.6 and main, but not 8.5, which might account for why these recently failures appear on 8.5 only?

See https://github.com/elastic/elasticsearch/issues/87591

**Comment by mark-vieira** [comment] 2022-12-20 21:22
Is this a delivery issue? It's not clear what the root cause is here.

**Comment by mark-vieira** [comment] 2023-02-08 20:55
Since these are 8.5 specific and that branch is EOL I'm closing this issue.

**Closed by mark-vieira** 2023-02-08 20:55 UTC
Labels: :Delivery/Build, >test-failure, Team:Delivery
