### ISSUE TITLE
:qa:wildfly:startWildfly occasionally cannot determine port

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#49374] opened 2019-11-20 12:55 UTC
The following few builds failed with

```
Execution failed for task ':qa:wildfly:startWildfly'.
...
* What went wrong:
Execution failed for task ':qa:wildfly:startWildfly'.
> assert httpPort > 0
         |        |
         0        false
```

https://gradle-enterprise.elastic.co/s/blzf37ibrgq2u
https://gradle-enterprise.elastic.co/s/behxlgbe4kcy4
https://gradle-enterprise.elastic.co/s/ea4ogabcdcq7c

Perhaps WildFly failed to start up, or perhaps it has recently changed how it emits this port information. Extra logging looks to be needed to help us here.

**Comment by rjernst** [comment] 2019-12-05 23:00
I opened https://github.com/elastic/elasticsearch/pull/49892 to improve the logging here so we can find what is failing.

**Comment by rjernst** [comment] 2020-01-22 20:22
This hasn't reoccurred in the last month that I can find. Closing this for now.

**Comment by javanna** [comment] 2020-02-28 15:49
This happened again today on 7.6 branch: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.6+multijob-unix-compatibility/os=ubuntu-18.04&&immutable/88/console . Seems like wildfly does fail to start?

```
11:45:12 2020-02-28 10:45:00,030 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([("interface" => "management")]) - failure description: {"WFLYCTL0080: Failed services" => {"org.wildfly.network.interface.management" => "java.net.SocketException: No such device (getFlags() failed)
11:45:12     Caused by: java.net.SocketException: No such device (getFlags() failed)"}}
```

**Comment by jasontedor** [comment] 2020-02-28 20:51
I think this is happening because of Docker test fixtures running at the same time as this test. The issue is that those tests create Docker bridge devices which come and go as the tests setup and teardown. If other tests are running in parallel that try to loop over all devices, they will die when they hit one of these devices being removed at the same time. We've worked around this in other areas, but the failures here are in Wildfly, and not our code.

I think that we can solve this by making this into a Docker test fixture, and use the official Wildfly image. We can then let Wildfly bind to its default ports and we don't have to have the port scanning code that we have anymore:

https://github.com/elastic/elasticsearch/blob/401c75d8b5d8eec4275de9126ac1c0b6362d1c4a/qa/wildfly/build.gradle#L132-L164

This will massively simplify and clean up these tests, by modernizing them, as there is a lot of other code that we can remove there, such as the Ivy repository on top of the Wildfly download site, and the start and stop code.

@pugnascotia will be picking this up.

**Closed** 2020-03-04 22:03 UTC
Labels: :Core/Infra/Build, >test-failure
