### ISSUE TITLE
[CI] AutoFollowIT.testAutoFollowManyIndices test failure

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#36761] opened 2018-12-18 11:15 UTC
Could not reproduce this under Linux or osx. Link https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=oraclelinux/125/console

log snippet

```
  1> [2018-12-18T07:47:41,534][INFO ][o.e.x.c.AutoFollowIT     ] [testAutoFollowManyIndices] after test
FAILURE 15.9s J0 | AutoFollowIT.testAutoFollowManyIndices <<< FAILURES!
   > Throwable #1: java.lang.AssertionError:
   > Expected: <37>
   >      but: was <38>
   >    at __randomizedtesting.SeedInfo.seed([F02ACEB2EC9BD622:D818E1CF850A7355]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.xpack.ccr.AutoFollowIT.lambda$testAutoFollowManyIndices$6(AutoFollowIT.java:154)
   >    at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:848)
   >    at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:822)
   >    at org.elasticsearch.xpack.ccr.AutoFollowIT.testAutoFollowManyIndices(AutoFollowIT.java:151)
   >    at java.lang.Thread.run(Thread.java:748)
   >    Suppressed: java.lang.AssertionError:
   > Expected: <37>
   >      but: was <30>
   >            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >            at org.elasticsearch.xpack.ccr.AutoFollowIT.lambda$testAutoFollowManyIndices$6(AutoFollowIT.java:154)
   >            at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:836)
   >            ... 39 more
   >    Suppressed: java.lang.AssertionError:
   > Expected: <37>
   >      but: was <30>
   >            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >            at org.elasticsearch.xpack.ccr.AutoFollowIT.lambda$testAutoFollowManyIndices$6(AutoFollowIT.java:154)
   >            at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:836)
   >            ... 39 more
   >    Suppressed: java.lang.AssertionError:
   > Expected: <37>
   >      but: was <30>
   >            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >            at org.elasticsearch.xpack.ccr.AutoFollowIT.lambda$testAutoFollowManyIndices$6(AutoFollowIT.java:154)
   >            at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:836)
   >            ... 39 more
   >    Suppressed: java.lang.AssertionError:
```

reproduction

```
./gradlew :x-pack:plugin:ccr:internalClusterTest \
  -Dtests.seed=F02ACEB2EC9BD622 \
  -Dtests.class=org.elasticsearch.xpack.ccr.AutoFollowIT \
  -Dtests.method="testAutoFollowManyIndices" \
  -Dtests.security.manager=true \
  -Dtests.locale=id \
  -Dtests.timezone=Africa/Monrovia \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

Link to the plain text logfile is at https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=oraclelinux/125/consoleText

**Comment by martijnvg** [comment] 2019-01-11 16:38
I've pushed this test fix: e4391afd98c99e05ce1ca2163d1a096a0405d72b
I will close this issue if this test doen't fail in the coming days.

**Comment by gwbrown** [comment] 2019-01-11 23:42
This test failed again today in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.6+multijob-unix-compatibility/os=debian/47/console

**Comment by martijnvg** [comment] 2019-01-12 09:46
After taking a better look at the test and how the auto follow coordinator can work, I think that the underlying issue may be caused by a real issue in the auto follow coordinator. 

The `logs-does-not-count` index should not get auto followed, but it does get auto followed. In the test an auto follow pattern is added, a number of leader indices get created that should get auto followed, the auto follow pattern gets removed, the `logs-does-not-count` gets created (and should not get auto followed), then the auto follow patterns get re-added and finally a number of leader indices get created that should get auto followed.

When the auto follow coordinator removes the auto follower, the auto follower itself doen't know it is deleted yet and may do another auto follow round before it really stops. I will open a PR to fix this.

**Comment by martijnvg** [comment] 2019-01-16 10:48
Fix has been pushed. If it starts failing again then this issues can be re-opened.

**Comment by markharwood** [comment] 2019-02-20 15:36
Two other instances [recently](https://build-stats.elastic.co/app/kibana#/discover/5b56f0e0-3106-11e9-b7e7-170d507f4045?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-1y,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:e58bf320-7efd-11e8-bf69-63c8ef516157,key:project,negate:!f,params:(query:elasticsearch,type:phrase),type:phrase,value:elasticsearch),query:(match:(project:(query:elasticsearch,type:phrase))))),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'class:org.elasticsearch.xpack.ccr.AutoFollowIT%20AND%20test:%20testAutoFollowManyIndices%20AND%20stacktrace:%22java.lang.AssertionError:%22'),sort:!(time,desc)))

**Comment by benwtrent** [comment] 2019-02-21 16:58
Test failed builds again:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=java11,nodes=immutable&&linux&&docker/30/console

```
./gradlew :x-pack:plugin:ccr:internalClusterTest -Dtests.seed=FC1F17C78EA1673 -Dtests.class=org.elasticsearch.xpack.ccr.AutoFollowIT -Dtests.method="testAutoFollowManyIndices" -Dtests.security.manager=true -Dtests.locale=ig-NG -Dtests.timezone=Pacific/Guam -Dcompiler.java=12 -Druntime.java=11
```

**Comment by martijnvg** [comment] 2019-02-21 19:16
I think we should mute this test in master, 7.x, 7.0 and 6.7 branches. I will take a look at the recent failures tomorrow.

**Comment by martijnvg** [comment] 2019-02-27 09:28
I've unmuted this test on master and added more logging, so when it fails then there is more information to debug.

**Comment by martijnvg** [comment] 2019-03-08 11:46
This test [finally failed again](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=zulu11,nodes=immutable&&linux&&docker/285/console). Looks related to the fact an assertbusy(...) takes too long to complete. I've reduced the amount of leader indices that need to be auto followed and I will re-enable the test on all branches.

**Comment by danielmitterdorfer** [comment] 2019-03-11 08:08
It has failed again twice:

On 7.0 in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=zulu11,nodes=immutable&&linux&&docker/63/console ([CI build log](https://github.com/elastic/elasticsearch/files/2951193/7.0-build.log.zip)):

```
./gradlew :x-pack:plugin:ccr:internalClusterTest \
  -Dtests.seed=7E8FF37C0456B038 \
  -Dtests.class=org.elasticsearch.xpack.ccr.AutoFollowIT \
  -Dtests.method="testAutoFollowManyIndices" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-ER \
  -Dtests.timezone=America/Cuiaba \
  -Dcompiler.java=11 \
  -Druntime.java=11
```

It also failed on `7.x` in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=zulu11,nodes=immutable&&linux&&docker/66/console ([CI build log](https://github.com/elastic/elasticsearch/files/2951197/7.x-build.log.zip)):

```
./gradlew :x-pack:plugin:ccr:internalClusterTest \
  -Dtests.seed=62B0C83BEB2B0B6D \
  -Dtests.class=org.elasticsearch.xpack.ccr.AutoFollowIT \
  -Dtests.method="testAutoFollowManyIndices" \
  -Dtests.security.manager=true \
  -Dtests.locale=sn \
  -Dtests.timezone=America/Marigot \
  -Dcompiler.java=11 \
  -Druntime.java=11
```

**Comment by martijnvg** [comment] 2019-03-11 09:08
I've made additional changes to the this test to all branches (^). It looks like sometimes there isn't enough time to auto follow many indices, so I've further reduced the leader indices to be auto followed.  I've also added additional assertions in the test.

**Comment by danielmitterdorfer** [comment] 2019-03-11 15:18
To help with future analysis here is the build-stats link (only available for authenticated users) to see the details about build failures: https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(branch),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'class:%22org.elasticsearch.xpack.ccr.AutoFollowIT%22%20AND%20test:%22testAutoFollowManyIndices%22'),sort:!(time,desc))

**Comment by martijnvg** [comment] 2019-03-11 16:16
thanks @danielmitterdorfer, that is helpful.

**Comment by martijnvg** [comment] 2019-03-14 10:15
This test hasn't failed in the last 3 days after the above tweaks were pushed. I will close this issue for now, please re-open if this test fails again for similar reasons.

**Closed by martijnvg** 2019-03-14 10:15 UTC
Labels: :Distributed/CCR, >test-failure
