### ISSUE TITLE
[CI] DocsClientYamlTestSuiteIT test {yaml=reference/cluster/nodes-stats/line_2751} failing

### ISSUE THREAD

**Issue by salvatore-campagna** [elastic/elasticsearch#91081] opened 2022-10-24 12:31 UTC
### CI Link

https://gradle-enterprise.elastic.co/s/6jmgrmhtgnlwo

### Repro line

REPRODUCE WITH: ./gradlew ':docs:yamlRestTest' --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/cluster/nodes-stats/line_2751}" -Dtests.seed=7054FC29615BAD86 -Dtests.locale=es-CO -Dtests.timezone=Atlantic/Jan_Mayen -Druntime.java=17	

### Does it reproduce?

No

### Applicable branches

main, 8.5

### Failure history

https://gradle-enterprise.elastic.co/scans/tests?search.timeZoneId=Europe/Rome&tests.container=org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT&tests.test=test%20%7Byaml%3Dreference/cluster/nodes-stats/line_2751%7D

### Failure excerpt
```
Caused by: java.lang.AssertionError: Expected a map containing |  
| acknowledged: expected <true> but was <missing> |  
  | nodes: <unexpected> but was <{eZuJK4ryRA-IIh3hgWPqkQ={ingest={pipelines={attachment={count=1, time_in_millis=9, current=0, failed=0, processors=[{attachment={type=attachment, stats={count=1, time_in_millis=8, current=0, failed=0}}}]}, seats={count=11, time_in_millis=1, current=0, failed=0, processors=[{script={type=script, stats={count=11, time_in_millis=1, current=0, failed=0}}}]}, my-pipeline={count=2, time_in_millis=0, current=0, failed=0, processors=[{set={type=set, stats={count=0, time_in_millis=0, current=0, failed=0}}}]}, enrich-policy-reindex-7={count=1, time_in_millis=0, current=0, failed=0, processors=[{remove={type=remove, stats={count=1, time_in_millis=0, current=0, failed=0}}}]}, logs-my_app-default={count=0, time_in_millis=0, current=0, failed=0, processors=[{lowercase={type=lowercase, stats={count=0, time_in_millis=0, current=0, failed=0}}}]}, my-pipeline-id={count=0, time_in_millis=0, current=0, failed=0, processors=[{set={type=set, stats={count=0, time_in_millis=0, current=0, failed=0}}}]}, cbor-attachment={count=0, time_in_millis=0, current=0, failed=0, processors=[{attachment={type=attachment, stats={count=0, time_in_millis=0, current=0, failed=0}}}]}}}}}>

**Comment by salvatore-campagna** [comment] 2022-10-24 15:06
If I understand correctly this is a YAML test that runs after extracting the test from docs.

**Comment by ywangd** [comment] 2022-10-27 00:34
Also failed on 8.5 https://gradle-enterprise.elastic.co/s/jqbrxe4jfs43w/tests/:docs:yamlRestTest/org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT/test%20%7Byaml=reference%2Fcluster%2Fnodes-stats%2Fline_2747%7D?top-execution=1

Does _not_ reproduce locally.

The line numbers are slightly different (2751 vs 2747). But the error messages are the same
```
java.lang.AssertionError: Failure at [reference/cluster/nodes-stats:128]: Expected a map containing |  
-- | --
  | acknowledged: expected <true> but was <missing> |  
  | nodes: <unexpected> but was <{J-ylZHjmTp6qciKPgmdZMA={ingest={pipelines={attachment={count=3, time_in_millis=1000, current=0, failed=0, processors=[{attachment={type=attachment, stats={count=1, time_in_millis=3, current=0, failed=0}}}]}, seats={count=77, time_in_millis=47, current=0, failed=0, processors=[{script={type=script, stats={count=77, time_in_millis=45, current=0, failed=0}}}]}, geoip={count=1, time_in_millis=33, current=0, failed=0, processors=[{geoip={type=geoip, stats={count=1, time_in_millis=33, current=0, failed=0}}}]}, user_agent={count=1, time_in_millis=11, current=0, failed=0, processors=[{user_agent={type=user_agent, stats={count=1, time_in_millis=11, current=0, failed=0}}}]}, polygonize_circles={count=2, time_in_millis=5, current=0, failed=0, processors=[{circle={type=circle, stats={count=2, time_in_millis=5, current=0, failed=0}}}]}, pipelineB={count=1, time_in_millis=2, current=0, failed=0, processors=[{pipeline:pipelineA={type=pipeline, stats={count=1, time_in_millis=2, current=0, failed=0}}}, {set={type=set, stats={count=1, time_in_millis=0, current=0, failed=0}}}]}, set_os={count=1, time_in_millis=1, current=0, failed=0, processors=[{set={type=set, stats={count=1, time_in_millis=1, current=0, failed=0}}}]}, monthlyindex={count=1, time_in_millis=1, current=0, failed=0, processors=[{date_index_name={type=date_index_name, stats={count=1, time_in_millis=1, current=0, failed=0}}}]}, my-pipeline={count=5, time_in_millis=0, current=0, failed=0, processors=[{set={type=set, stats={count=0, time_in_millis=0, current=0, failed=0}}}]}, set-foo={count=5, time_in_millis=0, current=0, failed=0, processors=[{set={type=set, stats={count=5, time_in_millis=0, current=0, failed=0}}}]}, my-pipeline-id={count=2, time_in_millis=0, current=0, failed=0, processors=[{lowercase={type=lowercase, stats={count=0, time_in_millis=0, current=0, failed=0}}}]}, pipelineA={count=1, time_in_millis=0, current=0, failed=0, processors=[{set={type=set, stats={count=1, time_in_millis=0, current=0, failed=0}}}]}, set_bar={count=1, time_in_millis=0, current=0, failed=0, processors=[{set={type=set, stats={count=1, time_in_millis=0, current=0, failed=0}}}]}, enrich-policy-reindex-7={count=1, time_in_millis=0, current=0, failed=0, processors=[{remove={type=remove, stats={count=1, time_in_millis=0, current=0, failed=0}}}]}, logs-my_app-default={count=0, time_in_millis=0, current=0, failed=0, processors=[{lowercase={type=lowercase, stats={count=0, time_in_millis=0, current=0, failed=0}}}]}, add_timestamp_pipeline={count=0, time_in_millis=0, current=0, failed=0, processors=[{set={type=set, stats={count=0, time_in_millis=0, current=0, failed=0}}}]}}}}}>
```

**Comment by ywangd** [comment] 2022-10-27 05:19
8.4 as well 
https://gradle-enterprise.elastic.co/s/syfbvdpntqdya/tests/:docs:yamlRestTest/org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT/test%20%7Byaml=reference%2Fcluster%2Fnodes-stats%2Fline_2721%7D?top-execution=1

**Comment by benwtrent** [comment] 2022-10-31 17:14
Muting in 8.4: https://github.com/elastic/elasticsearch/pull/91211

**Comment by benwtrent** [comment] 2022-10-31 20:28
Same kind of failure, just a different doc line.

https://gradle-enterprise.elastic.co/s/5qnnxte64a3ra

```
org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT > test {yaml=reference/cluster/nodes-stats/line_2743} FAILED
    java.lang.AssertionError: Failure at [reference/cluster/nodes-stats:112]: Expected a map containing
    acknowledged: expected <true> but was <missing>
           nodes: <unexpected> but was <{kpE_PDcHT8SAe3pNOPOSzw={ingest={total={count=180, time_in_millis=876, current=0, failed=0}, pipelines={attachment={count=2, time_in_millis=793, current=0, failed=0, processors=[{attachment={type=attachment, stats={count=2, time_in_millis=793, current=0, failed=0}}}]}, seats={count=154, time_in_millis=17, current=0, failed=0, processors=[{script={type=script, stats={count=154, time_in_millis=15, current=0, failed=0}}}]}, user_agent={count=1, time_in_millis=8, current=0, failed=0, processors=[{user_agent={type=user_agent, stats={count=1, time_in_millis=8, current=0, failed=0}}}]}, geoip={count=1, time_in_millis=4, current=0, failed=0, processors=[{geoip={type=geoip, stats={count=1, time_in_millis=4, current=0, failed=0}}}]}, set_os={count=1, time_in_millis=1, current=0, failed=0, processors=[{set={type=set, stats={count=1, time_in_millis=1, current=0, failed=0}}}]}, set-foo={count=5, time_in_millis=0, current=0, failed=0, processors=[{set={type=set, stats={count=5, time_in_millis=0, current=0, failed=0}}}]}, monthlyindex={count=1, time_in_millis=0, current=0, failed=0, processors=[{date_index_name={type=date_index_name, stats={count=1, time_in_millis=0, current=0, failed=0}}}]}, set_bar={count=1, time_in_millis=0, current=0, failed=0, processors=[{set={type=set, stats={count=1, time_in_millis=0, current=0, failed=0}}}]}, cbor-attachment={count=0, time_in_millis=0, current=0, failed=0, processors=[{attachment={type=attachment, stats={count=0, time_in_millis=0, current=0, failed=0}}}]}, one-pipeline-to-rule-them-all={count=0, time_in_millis=0, current=0, failed=0, processors=[{pipeline:httpd_pipeline={type=conditional, stats={count=0, time_in_millis=0, current=0, failed=0}}}, {pipeline:syslog_pipeline={type=conditional, stats={count=0, time_in_millis=0, current=0, failed=0}}}, {fail={type=conditional, stats={count=0, time_in_millis=0, current=0, failed=0}}}]}, logs-my_app-default={count=0, time_in_millis=0, current=0, failed=0, processors=[{lowercase={type=lowercase, stats={count=0, time_in_millis=0, current=0, failed=0}}}]}, add_timestamp_pipeline={count=0, time_in_millis=0, current=0, failed=0, processors=[{set={type=set, stats={count=0, time_in_millis=0, current=0, failed=0}}}]}, my-pipeline-id={count=0, time_in_millis=0, current=0, failed=0, processors=[{set={type=set, stats={count=0, time_in_millis=0, current=0, failed=0}}}]}, my-pipeline={count=0, time_in_millis=0, current=0, failed=0, processors=[{lowercase={type=lowercase, stats={count=0, time_in_millis=0, current=0, failed=0}}}]}}}}}>
```

**Comment by fcofdez** [comment] 2022-11-02 11:27
Another failure: https://gradle-enterprise.elastic.co/s/3rbqxlcsw4ev6/tests/:docs:yamlRestTest/org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT/test%20%7Byaml=reference%2Fcluster%2Fnodes-stats%2Fline_2743%7D?top-execution=1

**Comment by kingherc** [comment] 2022-11-03 12:36
I looked at this since morning and still haven't figured out what's wrong. I cannot reproduce it locally.

So far I found that internally the doc tests are being converted to .yml for REST testing (under ./docs/build/rest/rest-api-spec/test/reference/cluster/nodes-stats.yml). E.g.,:

```
"line_2743":
  - skip:
      features:
        - default_shards
        - stash_in_key
        - stash_in_path
        - stash_path_replace
        - warnings
  - do:
      raw:
        method: GET
        path: "_nodes/stats"
        metric: "ingest"
        filter_path: "nodes.*.ingest"
  - is_false: _shards.failures
```

The test response in the build error looks correct. I do not see a match for `acknowledged` to true, so wondering where it comes from. Any help would be appreciated! I noticed as well relevant older tickets like [this one](https://github.com/elastic/elasticsearch/issues/80409#issuecomment-961885589) (cc @lcawl) but it did not help me much more.

**Comment by hendrikmuhs** [comment] 2022-11-07 08:46
another one: https://gradle-enterprise.elastic.co/s/js2opkn67veze

**Comment by kingherc** [comment] 2022-11-07 11:31
OK, thanks for the mute. Unfortunately since I cannot reproduce it, I am at my wits end about what is going on. I cannot understand where this "acknowledged: true" comes from. For this reason, I would recommend extending the logging to understand more about the test failure. Specifically I am thinking of the following: currently when there's a test failure, it prints the REST response. I would also like to print the test YAML file that has the test sections being executed. That way we can confirm when this happens that it is actually not an "acknowledged: true" section that this comes from (else, something might be tampering with the test files maybe).

**Comment by hendrikmuhs** [comment] 2022-11-07 12:40
once you have your enhancements ready, you can simple unmute the test. If it fails again during my shift I will let you know here.

**Comment by kingherc** [comment] 2022-11-08 09:47
One more failure [here](https://gradle-enterprise.elastic.co/s/r7ckne6ixm4v4/console-log?task=:docs:yamlRestTest) with `REPRODUCE WITH: ./gradlew ':docs:yamlRestTest' --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/cluster/nodes-stats/line_2735}" -Dtests.seed=8CCB1B3365E081FF -Dtests.locale=ar-AE -Dtests.timezone=Africa/Algiers -Druntime.java=17`. Will mute more.

**Comment by kingherc** [comment] 2022-11-08 10:37
Also appears in 8.5, see failure [here](https://gradle-enterprise.elastic.co/s/fgwpozl6i6xgq/console-log?task=:docs:yamlRestTest) with:

```
REPRODUCE WITH: ./gradlew ':docs:yamlRestTest' --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/cluster/nodes-stats/line_2739}" -Dtests.seed=DCFEFD7B1D951049 -Dtests.locale=en-CA -Dtests.timezone=US/Aleutian -Druntime.java=17 |  
-- | --
  |   |  
  | org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT > test {yaml=reference/cluster/nodes-stats/line_2739} FAILED |  
  | java.lang.AssertionError: Failure at [reference/cluster/nodes-stats:112]: Expected a map containing |  
  | acknowledged: expected <true> but was <missing> |  
  | nodes: <unexpected> but was <{JVJLx-FtStqACbvTRJYDFw={ingest={total={count=70, time_in_millis=116, current=0, failed=0}, pipelines={seats={count=66, time_in_millis=53, current=0, failed=0, processors=[{script={type=script, stats={count=66, time_in_millis=51, current=0, failed=0}}}]}, user_agent={count=1, time_in_millis=8, current=0, failed=0, processors=[{user_agent={type=user_agent, stats={count=1, time_in_millis=8, current=0, failed=0}}}]}, enrich-policy-reindex-7={count=1, time_in_millis=0, current=0, failed=0, processors=[{remove={type=remove, stats={count=1, time_in_millis=0, current=0, failed=0}}}]}, monthlyindex={count=1, time_in_millis=0, current=0, failed=0, processors=[{date_index_name={type=date_index_name, stats={count=1, time_in_millis=0, current=0, failed=0}}}]}, my-pipeline-id={count=0, time_in_millis=0, current=0, failed=0, processors=[{set={type=set, stats={count=0, time_in_millis=0, current=0, failed=0}}}]}, pipeline-one={count=0, time_in_millis=0, current=0, failed=0, processors=[]}, set_ingest_time={count=0, time_in_millis=0, current=0, failed=0, processors=[{set={type=set, stats={count=0, time_in_millis=0, current=0, failed=0}}}]}, my-pipeline={count=0, time_in_millis=0, current=0, failed=0, processors=[{set={type=set, stats={count=0, time_in_millis=0, current=0, failed=0}}}]}, logs-my_app-default={count=0, time_in_millis=0, current=0, failed=0, processors=[{lowercase={type=lowercase, stats={count=0, time_in_millis=0, current=0, failed=0}}}]}, add_timestamp_pipeline={count=0, time_in_millis=0, current=0, failed=0, processors=[{set={type=set, stats={count=0, time_in_millis=0, current=0, failed=0}}}]}}}}}> |  
  | at __randomizedtesting.SeedInfo.seed([DCFEFD7B1D951049:54AAC2A1B3697DB1]:0)
```

Will mute all these in 8.5 as well.

**Comment by kingherc** [comment] 2022-11-08 12:18
Another issue [here](https://gradle-enterprise.elastic.co/s/3ifrxoriruyyc). Will mute all tests in node-stats docs for main and 8.5.

**Comment by kingherc** [comment] 2022-11-09 16:36
Merged relevant PR that logs now YAML source code test file on failures. Left one case of node-stats.asciidoc that can cause issues. On next such issue, I hope the log will provide more insight into where the "acknowledge: true" comes from.

**Comment by dimitris-athanasiou** [comment] 2022-11-14 11:51
Got another failure in https://gradle-enterprise.elastic.co/s/xccq6v6p7jgsu/tests/:docs:yamlRestTest/org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT/test%20%7Byaml=reference%2Fcluster%2Fnodes-stats%2Fline_2747%7D?top-execution=1. Hopefully that provides the answer in the logs.

**Comment by davidkyle** [comment] 2022-11-16 14:44
The failures in #87591 looks to be related to this

**Comment by kingherc** [comment] 2022-11-16 17:35
Hi @davidkyle , indeed. I was also baffled as to where the "acknowledged: true" comes from, so I made a PR to log the test .yml on failure. My last comment strengthens my suspicion that something, somewhere, seems to be injecting a match for "acknowledged: true" in the .yml that is auto-generated from the docs. You can also confirm in your case whether the failure logs of your ticket now show the "acknowledged: true" part, and verify whether locally you cannot reproduce it (i.e., on your local machine, the auto-generated .yml does not contain that part). I have not yet had time to dig deeper where this "acknowledged: true" part gets injected. But if you do in the meantime, feel free to keep me updated.

**Comment by ywangd** [comment] 2022-11-17 02:23
I think this failure is the same (though exact line number is different) https://gradle-enterprise.elastic.co/s/qqok3cxti3vn2/tests/:docs:yamlRestTest/org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT/test%20%7Byaml=reference%2Fcluster%2Fnodes-stats%2Fline_2747%7D?top-execution=1

**Comment by davidkyle** [comment] 2022-11-17 09:32
@kingherc I don't think anyone has managed to reproduce these failures yet but it has been noted that they only occur on Ubuntu (I have not found an exception to that rule). Nice work logging the test yaml at failure 👍  

>  You can also confirm in your case whether the failure logs of your ticket (after my PR was merged) now show the "acknowledged: true" part

The test hasn't failed since your PR was merged but I will keep an eye out for it.

**Comment by kingherc** [comment] 2022-11-22 17:44
I have some hard time with this. I cannot reproduce it locally. It seems that the code responsible for converting the .asciidoc snippets to YAML test somehow add this unexpected `acknowledged: true` response match. I do see such test responses in some other .asciidoc files, so maybe the conversion code gets confused across files? The responsible code is `build-tools-internal/src/main/groovy/org/elasticsearch/gradle/internal/doc/SnippetsTask.groovy` and the couple other surrounding files in that folder. I did not fully understand these (yet), but since I see @nik9000 started these out, I wanted to ask you @nik9000 if you have any ideas (or tips where to start looking) for the reason why we sometimes see in CI an unexpected

```
   - match: 
       $body: 
         {
             "acknowledged": true
         }
```

added to the YAML file (while the original .asciidoc does not define any test reponse at all)?

**Comment by nik9000** [comment] 2022-11-22 19:06
> you @nik9000 if you have any ideas (or tips where to start looking) for the reason why we sometimes see in CI an unexpected

I think it's possible to stick a `console-result` as the first thing in a file. I'll put something together to check for that.

**Comment by nik9000** [comment] 2022-11-22 19:06
```
> reference/ml/trained-models/apis/put-trained-model-vocabulary.asciidoc[75:79](console-result): Result can't be first in file

```

**Closed** 2022-12-07 16:02 UTC
Labels: :Data Management/Stats, >test-failure, :Distributed/Distributed, Team:Data Management, Team:Distributed
