### ISSUE TITLE
Elasticsearch reports fielddata memory for doc_values only index

### ISSUE THREAD

**Issue by bobrik** [elastic/elasticsearch#17472] opened 2016-04-01 09:40 UTC
**Elasticsearch version**:

```
# elasticsearch --version
Version: 2.2.0, Build: 8ff36d1/2016-01-27T13:32:39Z, JVM: 1.8.0_72-internal
```

**JVM version**:

```
# java -version
openjdk version "1.8.0_72-internal"
OpenJDK Runtime Environment (build 1.8.0_72-internal-b15)
OpenJDK 64-Bit Server VM (build 25.72-b15, mixed mode)
```

**OS version**: Debian Jessie on kernel 4.1.3.

**Description of the problem including expected versus actual behavior**:

Elasticsearch reports fielddata memory for `doc_values` only index:

```
index                   fm   fcm    sm
raytracer-2016.03.31 6.5gb 2.5gb 4.6gb
```

Index mapping declares everything to be `doc_values` (and it should be default in 2.2 anyway):

``` json
{
  "template": "raytracer-*",
  "settings": {
    "number_of_shards": 50,
    "number_of_replicas": 1,
    "index.refresh_interval": "30s",
    "index.query.default_field": "id"
  },
  "mappings": {
    "_default_": {
      "_all": {
        "enabled": false
      },
      "dynamic_templates": [
        {
          "string_fields": {
            "match": "*",
            "match_mapping_type": "string",
            "mapping": {
              "type": "string",
              "index": "not_analyzed",
              "ignore_above": 256,
              "doc_values": true
            }
          }
        },
        {
          "long_fields": {
            "match": "*",
            "match_mapping_type": "long",
            "mapping": {
              "type": "long",
              "doc_values": true
            }
          }
        },
        {
          "double_fields": {
            "match": "*",
            "match_mapping_type": "double",
            "mapping": {
              "type": "double",
              "doc_values": true
            }
          }
        },
        {
          "date_fields": {
            "match": "*",
            "match_mapping_type": "date",
            "mapping": {
              "type": "date",
              "doc_values": true
            }
          }
        }
      ]
    }
  }
}
```

**Comment by jpountz** [comment] 2016-04-01 12:05
Do you perform terms aggregations on your string fields? If yes then this memory usage is due to global ordinals that elasticsearch builds on top of doc values.

**Comment by bobrik** [comment] 2016-04-01 12:11
Yes, I do. Is it documented somewhere?

**Comment by jpountz** [comment] 2016-04-01 14:24
It doesn't seem to be, at least not close to the docs of the stats APIs.

**Comment by ppf2** [comment] 2016-07-30 00:09
Let's document this since we will not be implementing separate reporting of ordinals' memory usage (https://github.com/elastic/elasticsearch/issues/9838) :)

**Comment by jimczi** [comment] 2019-05-06 16:39
Closing as duplicate of #37092 and https://github.com/elastic/elasticsearch/issues/37092#issuecomment-466875398

**Closed by jimczi** 2019-05-06 16:39 UTC
Labels: :Search/Search, >docs, help wanted
