### ISSUE TITLE
[DOCS] Provide guidance on removing data nodes

### ISSUE THREAD

**Issue by rwaight** [elastic/elasticsearch#46338] opened 2019-09-04 18:28 UTC
Starting with 7.0, we've added [this guide](https://www.elastic.co/guide/en/elasticsearch/reference/7.0/modules-discovery-adding-removing-nodes.html) for adding and removing _master eligible_ nodes.  We should also include guidance on the removal / decommissioning of data nodes beyond what is mentioned in [this discussion topic](https://discuss.elastic.co/t/remove-node-from-cluster/65257) (referencing [shard allocation filtering](https://www.elastic.co/guide/en/elasticsearch/reference/7.0/allocation-filtering.html))

I have some notes regarding a possible "decommission process" and can follow this up with a PR to start the process of documenting this issue.

**Comment by debadair** [comment] 2019-10-12 01:31
[docs issue triage]

**Comment by lockewritesdocs** [comment] 2022-04-28 15:01
This issue hasn't been updated for 3+ years so I'm closing it. If the issue is still valid, please reopen and provide guidance on how to proceed.

**Closed by lockewritesdocs** 2022-04-28 15:01 UTC
Labels: >docs, :Distributed/Allocation, Team:Distributed, Team:Docs
