### ISSUE TITLE
term suggest suggest_mode missing broken?

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch#17132] opened 2016-03-16 09:53 UTC
This was found during training using the core developer training dataset:

Getting all the term suggestions for framework

```json
GET stack/_suggest
{
  "mysuggest" : {
    "text" : "framework",
    "term" : {
      "field" : "title",
      "suggest_mode" : "always",
      "sort" : "score",
      "size" : 20
    }
  }
}
```

yields:

```json
[{
	"text": "frameworks",
	"score": 0.8888889,
	"freq": 16
}, {
	"text": "framework2",
	"score": 0.8888889,
	"freq": 1
}, {
	"text": "framwork",
	"score": 0.875,
	"freq": 5
}, {
	"text": "framewok",
	"score": 0.875,
	"freq": 2
}, {
	"text": "famework",
	"score": 0.875,
	"freq": 1
}, {
	"text": "framework's",
	"score": 0.7777778,
	"freq": 1
}, {
	"text": "freamwork",
	"score": 0.7777778,
	"freq": 1
}]
```

if we then pick any of the of these terms, except the most popular `frameworks` and feed it to the term suggester using the missing option:

```json
GET stack/_suggest
{
  "mysuggest" : {
    "text" : "framwork",
    "term" : {
      "field" : "title",
      "suggest_mode" : "missing",
      "sort" : "score",
      "size" : 20
    }
  }
}
```

We still get back suggestions:

```json
[{
	"text": "framework",
	"score": 0.875,
	"freq": 197
}, {
	"text": "frameworks",
	"score": 0.75,
	"freq": 9
}, {
	"text": "framewok",
	"score": 0.75,
	"freq": 1
}, {
	"text": "framework2",
	"score": 0.75,
	"freq": 1
}]
```

Only for the most `popular`  term do we get back no suggestions.

For full reference here is how `framwork` gets analyzed:

```GET stack/_analyze?field=title&text=framwork```

```json
{
  "tokens": [
    {
      "token": "framwork",
      "start_offset": 0,
      "end_offset": 8,
      "type": "<ALPHANUM>",
      "position": 0
    }
  ]
}
```

**Comment by clintongormley** [comment] 2016-03-16 10:33
This is an artefact of using multiple shards.  Try the following example with 1 shard vs 5 shards:

    PUT t
    {
      "settings": {
        "number_of_shards": 1
      }
    }
    
    POST t/t/_bulk
    {"index": {}}
    {  "text": "frameworks"}
    {"index": {}}
    {  "text": "frameworks"}
    {"index": {}}
    {  "text": "frameworks"}
    {"index": {}}
    {  "text": "frameworks"}
    {"index": {}}
    {  "text": "frameworks"}
    {"index": {}}
    {  "text": "frameworks"}
    {"index": {}}
    {  "text": "frameworks"}
    {"index": {}}
    {  "text": "frameworks"}
    {"index": {}}
    {  "text": "frameworks"}
    {"index": {}}
    {  "text": "frameworks"}
    {"index": {}}
    {  "text": "frameworks"}
    {"index": {}}
    {  "text": "frameworks"}
    {"index": {}}
    {  "text": "frameworks"}
    {"index": {}}
    {  "text": "frameworks"}
    {"index": {}}
    {  "text": "frameworks"}
    {"index": {}}
    {  "text": "frameworks"}
    {"index": {}}
    {  "text": "framework2"}
    {"index": {}}
    {  "text": "framwork"}
    {"index": {}}
    {  "text": "framwork"}
    {"index": {}}
    {  "text": "framwork"}
    {"index": {}}
    {  "text": "framwork"}
    {"index": {}}
    {  "text": "framwork"}
    {"index": {}}
    {  "text": "framwok"}
    {"index": {}}
    {  "text": "famwork"}
    {"index": {}}
    {  "text": "framwork's"}
    {"index": {}}
    {  "text": "freamwork"}
    
    GET t/_suggest
    {
      "mysuggest" : {
        "text" : "framwork",
        "term" : {
          "field" : "text",
          "suggest_mode" : "missing",
          "sort" : "score",
          "size" : 20
        }
      }
    }

Closing as duplicate of https://github.com/elastic/elasticsearch/issues/7472

**Closed by clintongormley** 2016-03-16 10:33 UTC
