### ISSUE TITLE
Explore Method Folding in Painless

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#49885] opened 2019-12-05 19:47 UTC
SQL uses special rules for `null` handling relative to operators such as addition or greater than. This creates a number of small method chains that requires numerous calls in Painless. As an example `a + b > c - d` becomes `gt(add(a,b),sub(c,d))`.  A possible performance improvement is to have painless recognize these methods should be inline. 

@costin Just want to double check this accurately describes the issue that we've discussed in the past.

**Comment by costin** [comment] 2019-12-10 12:05
Thanks @jdconrad - it does.
Note in practice the issue is amplified by the null checks on doc values which leads to a mandatory check per field.
So `a + b > c - d` becomes `gt(add(checkNull(a), checkNull(b), sub(checkNull(c), checknull(d)))`.

Note that all the methods above are whitelisted. I imagine for more complicated methods like `myDateTimeExtraction` things might be a tricky for most comparison and math operators it would really help to eliminate the excessive method invocations.

Maybe having some kind of macros API would help as a way to teach Painless about certain declarations.
For example if Painless would know that:
```
checkNull(docValues, a) = return docValues != null && docValues.contains(a) 
          ? docValues.get(a) : null
add(a,b) = a + b
```
then when it encounters `checkNull(docValues, a) + checkNull(docValues,b)` it would translate these to:
```
def checkNullA = docValues...
def checkNullB = docValues...
def result1 = checkNullA + checkNullB
```

**Comment by stu-elastic** [comment] 2020-02-20 19:14
This depends on AST split refactor #49869, these methods are too big to be inlined by hotspot.

@costin we'll have to work with you to get some tests to ensure the inlining will be useful when we pick this up.  It'd be useful to demonstrate that method overhead is substantial.

**Comment by rjernst** [comment] 2024-05-25 02:23
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.

**Closed by rjernst** 2024-05-25 02:23 UTC
Labels: >enhancement, :Core/Infra/Scripting, Team:Core/Infra
