### ISSUE TITLE
dfs_query_then_fetch does work sometimes

### ISSUE THREAD

**Issue by XGiton** [elastic/elasticsearch#20580] opened 2016-09-20 11:20 UTC
**Elasticsearch version**: Elasticsearch 5.0.0-alpha5

**Plugins installed**: [analyzer-ik]

**JVM version**: jdk1.8.0_101

**OS version**: Ubuntu 14.04

**Description of the problem including expected versus actual behavior**:
`dfs_query_then_fetch` does not work sometimes. When specifying `search_type=dfs_query_then_fetch`, Scores returned should are based on total information of all shard . Actually the scores returned are still based on local information in each shard.

This is my query:
```
curl -XPOST 'localhost:9200/test-index/enterprise/_search?search_type=dfs_query_then_fetch&explain=true&pretty' -d '
{
"query": {"match": {"content": "腾讯"}}
}'
```
I get result:
```

  "took" : 5,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 120,
    "max_score" : 118.87119,
    "hits" : [
      {
        "_shard" : "[test-index][2]",
        "_node" : "UTT6ATDATvW4r5cBzfnJJg",
        "_index" : "test-index",
        "_type" : "enterprise",
        "_id" : "腾讯个人有限公司",
        "_score" : 118.87119,
        "_source" : {
          "content" : "腾讯个人"
        },
        "_explanation" : {
          "value" : 120.98468,
          "description" : "sum of:",
          "details" : [
            {
              "value" : 120.98468,
              "description" : "weight(content:腾讯 in 74204) [PerFieldSimilarity], result of:",
              "details" : [
                {
                  "value" : 120.98468,
                  "description" : "score(doc=74204,freq=1.0 = termFreq=1.0\n), product of:",
                  "details" : [
                    {
                      "value" : 8.0,
                      "description" : "boost",
                      "details" : [ ]
                    },
                    {
                      "value" : 11.487666,
                      "description" : "idf(docFreq=21, docCount=2096372)",
                      "details" : [ ]
                    },
                    {
                      "value" : 1.3164628,
                      "description" : "tfNorm, computed from:",
                      "details" : [
                        {
                          "value" : 1.0,
                          "description" : "termFreq=1.0",
                          "details" : [ ]
                        },
                        {
                          "value" : 1.2,
                          "description" : "parameter k1",
                          "details" : [ ]
                        },
                        {
                          "value" : 0.75,
                          "description" : "parameter b",
                          "details" : [ ]
                        },
                        {
                          "value" : 9.699715,
                          "description" : "avgFieldLength",
                          "details" : [ ]
                        },
                        {
                          "value" : 4.0,
                          "description" : "fieldLength",
                          "details" : [ ]
                        }
                      ]
                    }
                  ]
                }
              ]
            },
            {
              "value" : 0.0,
              "description" : "match on required clause, product of:",
              "details" : [
                {
                  "value" : 0.0,
                  "description" : "# clause",
                  "details" : [ ]
                },
                {
                  "value" : 1.0,
                  "description" : "_type:enterprise, product of:",
                  "details" : [
                    {
                      "value" : 1.0,
                      "description" : "boost",
                      "details" : [ ]
                    },
                    {
                      "value" : 1.0,
                      "description" : "queryNorm",
                      "details" : [ ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      },
      {
        "_shard" : "[test-index][0]",
        "_node" : "UTT6ATDATvW4r5cBzfnJJg",
        "_index" : "test-index",
        "_type" : "enterprise",
        "_id" : "腾讯征信有限公司",
        "_score" : 111.30547,
        "_source" : {
          "content" : "腾讯征信"
        },
        "_explanation" : {
          "value" : 110.514534,
          "description" : "sum of:",
          "details" : [
            {
              "value" : 110.514534,
              "description" : "weight(content:腾讯 in 72811) [PerFieldSimilarity], result of:",
              "details" : [
                {
                  "value" : 110.514534,
                  "description" : "score(doc=72811,freq=1.0 = termFreq=1.0\n), product of:",
                  "details" : [
                    {
                      "value" : 8.0,
                      "description" : "boost",
                      "details" : [ ]
                    },
                    {
                      "value" : 11.206198,
                      "description" : "idf(docFreq=28, docCount=2097175)",
                      "details" : [ ]
                    },
                    {
                      "value" : 1.232739,
                      "description" : "tfNorm, computed from:",
                      "details" : [
                        {
                          "value" : 1.0,
                          "description" : "termFreq=1.0",
                          "details" : [ ]
                        },
                        {
                          "value" : 1.2,
                          "description" : "parameter k1",
                          "details" : [ ]
                        },
                        {
                          "value" : 0.75,
                          "description" : "parameter b",
                          "details" : [ ]
                        },
                        {
                          "value" : 9.702056,
                          "description" : "avgFieldLength",
                          "details" : [ ]
                        },
                        {
                          "value" : 5.2244897,
                          "description" : "fieldLength",
                          "details" : [ ]
                        }
                      ]
                    }
                  ]
                }
              ]
            },
            {
              "value" : 0.0,
              "description" : "match on required clause, product of:",
              "details" : [
                {
                  "value" : 0.0,
                  "description" : "# clause",
                  "details" : [ ]
                },
                {
                  "value" : 1.0,
                  "description" : "_type:enterprise, product of:",
                  "details" : [
                    {
                      "value" : 1.0,
                      "description" : "boost",
                      "details" : [ ]
                    },
                    {
                      "value" : 1.0,
                      "description" : "queryNorm",
                      "details" : [ ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      },
      ...
    ]
  }
}
```

**Comment by jimferenczi** [comment] 2016-09-20 12:14
Thank you for the report @XGiton 
The score of each hit is computed with the aggregated frequency but the explain output uses the local frequency. This has been fixed by https://github.com/elastic/elasticsearch/pull/19972

**Closed by jimferenczi** 2016-09-20 12:14 UTC

**Comment by XGiton** [comment] 2016-09-20 13:36
Thank you @jimferenczi 
These two contents shows in query result have same length, why they have different score?

**Comment by jimferenczi** [comment] 2016-09-22 10:02
@XGiton I am not able to reproduce your problem. I have the same score for hits that have the same content on different shards when using the dfs_query_then_fetch. Could you please share a recreation that reproduces the problem ?
