### ISSUE TITLE
wildcard query should throw a json_parse_exception with error code 400

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#117727] opened 2024-11-28 17:38 UTC
### Description

The `wildcard` query will throw a `json_parse_exception` with error code 500 when there is a syntax error in the value provided, while `term` query for example will throw the same exception wrapped in a `x_content_parse_exception` but with an error code 400, which I believe is the more correct approach.

Query to test:

```
{
    "query": {
        "wildcard": {
            "name": {
                "value": "*56\-1*"
            }
        }
    }
}
```

**Comment by martijnvg** [comment] 2024-11-29 08:45
@astefan Is this issue is a duplicate of #114142? Or is this one different?

**Comment by astefan** [comment] 2024-11-29 08:57
@martijnvg similar I guess, but that one lacks details, like reproduction steps and which query shows the bug

**Comment by drempapis** [comment] 2024-12-06 13:57
This has been fixed in this [pr](https://github.com/elastic/elasticsearch/pull/114445)

I also tried it locally for `main/8.x` branches

```
curl --location --request GET 'localhost:9200/order/_search' \
--header 'Content-Type: application/json' \
--data '{
    "query": {
        "wildcard": {
            "name": {
                "value": "*56\-1*"
            }
        }
    }
}'
```
```
{
    "error": {
        "root_cause": [
            {
                "type": "x_content_parse_exception",
                "reason": "[5:31] Unrecognized character escape '-' (code 45)\n at [Source: (byte[])\"{\n    \"query\": {\n        \"wildcard\": {\n            \"name\": {\n                \"value\": \"*56\\-1*\"\n            }\n        }\n    }\n}\"; line: 5, column: 31]"
            }
        ],
        "type": "x_content_parse_exception",
        "reason": "[5:31] Unrecognized character escape '-' (code 45)\n at [Source: (byte[])\"{\n    \"query\": {\n        \"wildcard\": {\n            \"name\": {\n                \"value\": \"*56\\-1*\"\n            }\n        }\n    }\n}\"; line: 5, column: 31]",
        "caused_by": {
            "type": "json_parse_exception",
            "reason": "Unrecognized character escape '-' (code 45)\n at [Source: (byte[])\"{\n    \"query\": {\n        \"wildcard\": {\n            \"name\": {\n                \"value\": \"*56\\-1*\"\n            }\n        }\n    }\n}\"; line: 5, column: 31]"
        }
    },
    "status": 400
}
```

**Closed by drempapis** 2024-12-06 13:57 UTC
Labels: >bug, Team:Search Foundations, :Search Foundations/Search
