### ISSUE TITLE
Consider upgrading to T-Digest 3.3

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#73928] opened 2021-06-08 20:00 UTC
The new version of t-digest promises improved [accuracy under most circumstances](https://tdunning.blogspot.com/2021/06/whats-new-in-t-digest-new-version-32.html). We should consider upgrading.

**Comment by kkrik-es** [comment] 2023-06-19 07:04
Duplicate of #95903

**Closed by kkrik-es** 2023-06-19 07:04 UTC
Labels: >enhancement, stalled, :Analytics/Aggregations, Team:Analytics

**Comment by martijnvg** [comment] 2023-06-19 08:01
Tdigest has been forked (#96086). This is no longer relevant.
