### ISSUE TITLE
tribe node fails to start with non default port settings

### ISSUE THREAD

**Issue by kt97679** [elastic/elasticsearch#16392] opened 2016-02-02 23:05 UTC
I'm trying to run tribe node using elasticsearch 2.2.0. I have cluster of 2 machines with the following config:

<pre>
network.host: 0.0.0.0
path.data: /var/lib/elasticsearch/
path.logs: /var/log/elasticsearch/
cluster.name: logstash-data
discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.unicast.hosts: ["10.16.1.32", "10.16.1.75"]
</pre>

On another machine I run 2 elasticsearch instances with following configs:

<pre>
transport.tcp.port: 9310
http.port: 9210
network.host: 0.0.0.0
path.data: /var/lib/elasticsearch/
path.logs: /var/log/elasticsearch/
cluster.name: logstash-kibana
</pre>

and

<pre>
#transport.tcp.port: 9301
#http.port: 9201
network.host: 0.0.0.0
path.data: /var/lib/elasticsearch/
path.logs: /var/log/elasticsearch/

tribe:
    data:
        cluster.name: logstash-data
        discovery.zen.ping.multicast.enabled: false
        discovery.zen.ping.unicast.hosts: ["10.16.1.32", "10.16.1.75"]
        network.host: 0.0.0.0
    kibana:
        cluster.name: logstash-kibana
        discovery.zen.ping.multicast.enabled: false
        discovery.zen.ping.unicast.hosts: ["127.0.0.1:9310"]
        network.host: 0.0.0.0
</pre>

This config works ok. But if I'll uncomment custom port settings I'm getting following exception:

<pre>
log4j:WARN No appenders could be found for logger (bootstrap).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" BindTransportException[Failed to bind to [9300-9400]]; nested: ChannelException[Failed to bind to: /0.0.0.0:9400]; nested: AccessControlException[access denied ("java.net.SocketPermission" "localhost:9400" "listen,resolve")];
Likely root cause: java.security.AccessControlException: access denied ("java.net.SocketPermission" "localhost:9400" "listen,resolve")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:457)
        at java.security.AccessController.checkPermission(AccessController.java:884)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
        at java.lang.SecurityManager.checkListen(SecurityManager.java:1131)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:221)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Refer to the log for complete error details.
</pre>

**Comment by rjernst** [comment] 2016-02-11 07:19
The problem here is the tribe nodes create an internal node for each cluster, and bind to the configured port for that client node. When you specify a custom ports for http and transport, security manager is configured with those ports, instead of the default ranges, which for transport are 9300-9400. But then the tribe client nodes continue to use the default ports, and fail when attempting to bind.

The only way I can see to fix this is to add knowledge about tribe settings to `Security.addBindPermissions`. /cc @rmuir

**Comment by CVTJNII** [comment] 2016-03-28 23:29
So the problem isn't that the values differ from the standard, it's that the values are pinned at all correct?  To mitigate this I attempted to pin back to the default ports of 9200 for http and 9300 for transport but still received the exception.  If the value is pinned the security manager and clients all try and use the pinned port, which fail, whereas if the value is unset the security manager uses the lowest free port, which is the default, and the clients use the subsequent ports in the ranges.  Is my understanding correct?

**Comment by chinmoydas1** [comment] 2016-05-12 09:22
Was there any solution to this issue? I am facing the same

**Comment by rjernst** [comment] 2016-05-15 03:05
@chinmoydas1 The only workaround at the moment is to use the default ports. I've marked this as adoptme.

**Comment by nellicus** [comment] 2016-08-10 09:25
+1

**Comment by sdmmemberx1** [comment] 2016-09-14 06:55
I am facing the same

**Comment by nellicus** [comment] 2016-09-14 07:57
my tribe config

```
abonuccelli@w530 /opt/elk/TEST/tribe_test/tribeNode $ egrep '^[^#]+' elasticsearch-2.3.5/config/elasticsearch.yml 
cluster.name: tribe
network.host: 192.168.1.105
http.port: 9220
transport.tcp.port: 9320
tribe:
  A: 
    cluster.name: clusterA
    discovery.zen.ping.unicast.hosts: ["192.168.1.105:9300"]
    network.publish_host: 192.168.1.105
    transport.tcp.port: 9340
  B: 
    cluster.name: clusterB
    discovery.zen.ping.unicast.hosts: ["192.168.1.105:9301"]
    network.publish_host: 192.168.1.105
    transport.tcp.port: 9341
  M:
    cluster.name: monitoring
    discovery.zen.ping.unicast.hosts: ["192.168.1.105:9310"]
    network.publish_host: 192.168.1.105
    transport.tcp.port: 9342
marvel.enabled: false

```

was getting

```
./elasticsearch-2.3.5/bin/elasticsearch
[2016-09-14 09:51:06,229][INFO ][node                     ] [Venom] version[2.3.5], pid[5567], build[90f439f/2016-07-27T10:36:52Z]
[2016-09-14 09:51:06,229][INFO ][node                     ] [Venom] initializing ...
[2016-09-14 09:51:06,740][INFO ][plugins                  ] [Venom] modules [reindex, lang-expression, lang-groovy], plugins [license, marvel-agent], sites []
[2016-09-14 09:51:08,052][INFO ][node                     ] [Venom/A] version[2.3.5], pid[5567], build[90f439f/2016-07-27T10:36:52Z]
[2016-09-14 09:51:08,052][INFO ][node                     ] [Venom/A] initializing ...
[2016-09-14 09:51:08,400][INFO ][plugins                  ] [Venom/A] modules [reindex, lang-expression, lang-groovy], plugins [license, marvel-agent], sites []
[2016-09-14 09:51:08,679][INFO ][node                     ] [Venom/A] initialized
[2016-09-14 09:51:08,680][INFO ][node                     ] [Venom/B] version[2.3.5], pid[5567], build[90f439f/2016-07-27T10:36:52Z]
[2016-09-14 09:51:08,680][INFO ][node                     ] [Venom/B] initializing ...
[2016-09-14 09:51:08,986][INFO ][plugins                  ] [Venom/B] modules [reindex, lang-expression, lang-groovy], plugins [license, marvel-agent], sites []
[2016-09-14 09:51:09,189][INFO ][node                     ] [Venom/B] initialized
[2016-09-14 09:51:09,190][INFO ][node                     ] [Venom/M] version[2.3.5], pid[5567], build[90f439f/2016-07-27T10:36:52Z]
[2016-09-14 09:51:09,190][INFO ][node                     ] [Venom/M] initializing ...
[2016-09-14 09:51:09,447][INFO ][plugins                  ] [Venom/M] modules [reindex, lang-expression, lang-groovy], plugins [license, marvel-agent], sites []
[2016-09-14 09:51:09,593][INFO ][node                     ] [Venom/M] initialized
[2016-09-14 09:51:09,598][INFO ][node                     ] [Venom] initialized
[2016-09-14 09:51:09,599][INFO ][node                     ] [Venom] starting ...
[2016-09-14 09:51:09,670][INFO ][transport                ] [Venom] publish_address {192.168.1.105:9320}, bound_addresses {192.168.1.105:9320}
[2016-09-14 09:51:09,673][INFO ][discovery                ] [Venom] tribe/lINF7OL1S0yiuYt5nV154w
[2016-09-14 09:51:09,674][WARN ][discovery                ] [Venom] waited for 0s and no initial state was set by the discovery
[2016-09-14 09:51:09,691][INFO ][http                     ] [Venom] publish_address {192.168.1.105:9220}, bound_addresses {192.168.1.105:9220}
[2016-09-14 09:51:09,691][INFO ][node                     ] [Venom/A] starting ...
[2016-09-14 09:51:09,743][INFO ][node                     ] [Venom/A] stopping ...
[2016-09-14 09:51:09,745][INFO ][node                     ] [Venom/A] stopped
[2016-09-14 09:51:09,745][INFO ][node                     ] [Venom/A] closing ...
[2016-09-14 09:51:09,749][INFO ][node                     ] [Venom/A] closed
[2016-09-14 09:51:09,750][INFO ][node                     ] [Venom/B] closing ...
[2016-09-14 09:51:09,752][INFO ][node                     ] [Venom/B] closed
[2016-09-14 09:51:09,752][INFO ][node                     ] [Venom/M] closing ...
[2016-09-14 09:51:09,754][INFO ][node                     ] [Venom/M] closed
Exception in thread "main" BindTransportException[Failed to bind to [9340]]; nested: ChannelException[Failed to bind to: /192.168.1.105:9340]; nested: AccessControlException[access denied ("java.net.SocketPermission" "localhost:9340" "listen,resolve")];
Likely root cause: java.security.AccessControlException: access denied ("java.net.SocketPermission" "localhost:9340" "listen,resolve")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:457)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at java.lang.SecurityManager.checkListen(SecurityManager.java:1131)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:221)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315)
	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Refer to the log for complete error details.
[2016-09-14 09:51:09,760][INFO ][node                     ] [Venom] stopping ...
[2016-09-14 09:51:09,772][INFO ][node                     ] [Venom] stopped
[2016-09-14 09:51:09,772][INFO ][node                     ] [Venom] closing ...
[2016-09-14 09:51:09,774][INFO ][node                     ] [Venom] closed
```

I was able to workaround adding a security exception (use this at your own risk)

```
abonuccelli@w530 /opt/elk/TEST/tribe_test $ cat tribeNode/elasticsearch-2.3.5/java.policy 
grant {
    permission java.net.SocketPermission "localhost:9340", "listen,resolve";
};
```

then

```
abonuccelli@w530 /opt/elk/TEST/tribe_test/tribeNode $ export ES_JAVA_OPTS=-Djava.security.policy=file:///opt/elk/TEST/tribe_test/tribeNode/elasticsearch-2.3.5/java.policy; ./elasticsearch-2.3.5/bin/elasticsearch
[2016-09-14 09:51:37,629][INFO ][node                     ] [Satannish] version[2.3.5], pid[5749], build[90f439f/2016-07-27T10:36:52Z]
[2016-09-14 09:51:37,630][INFO ][node                     ] [Satannish] initializing ...
[2016-09-14 09:51:38,162][INFO ][plugins                  ] [Satannish] modules [reindex, lang-expression, lang-groovy], plugins [license, marvel-agent], sites []
[2016-09-14 09:51:39,397][INFO ][node                     ] [Satannish/A] version[2.3.5], pid[5749], build[90f439f/2016-07-27T10:36:52Z]
[2016-09-14 09:51:39,398][INFO ][node                     ] [Satannish/A] initializing ...
[2016-09-14 09:51:39,656][INFO ][plugins                  ] [Satannish/A] modules [reindex, lang-expression, lang-groovy], plugins [license, marvel-agent], sites []
[2016-09-14 09:51:39,892][INFO ][node                     ] [Satannish/A] initialized
[2016-09-14 09:51:39,893][INFO ][node                     ] [Satannish/B] version[2.3.5], pid[5749], build[90f439f/2016-07-27T10:36:52Z]
[2016-09-14 09:51:39,893][INFO ][node                     ] [Satannish/B] initializing ...
[2016-09-14 09:51:40,178][INFO ][plugins                  ] [Satannish/B] modules [reindex, lang-expression, lang-groovy], plugins [license, marvel-agent], sites []
[2016-09-14 09:51:40,337][INFO ][node                     ] [Satannish/B] initialized
[2016-09-14 09:51:40,337][INFO ][node                     ] [Satannish/M] version[2.3.5], pid[5749], build[90f439f/2016-07-27T10:36:52Z]
[2016-09-14 09:51:40,337][INFO ][node                     ] [Satannish/M] initializing ...
[2016-09-14 09:51:40,599][INFO ][plugins                  ] [Satannish/M] modules [reindex, lang-expression, lang-groovy], plugins [license, marvel-agent], sites []
[2016-09-14 09:51:40,710][INFO ][node                     ] [Satannish/M] initialized
[2016-09-14 09:51:40,714][INFO ][node                     ] [Satannish] initialized
[2016-09-14 09:51:40,714][INFO ][node                     ] [Satannish] starting ...
[2016-09-14 09:51:40,778][INFO ][transport                ] [Satannish] publish_address {192.168.1.105:9320}, bound_addresses {192.168.1.105:9320}
[2016-09-14 09:51:40,780][INFO ][discovery                ] [Satannish] tribe/R-S-WQtmSvOLUInO-Cke7w
[2016-09-14 09:51:40,781][WARN ][discovery                ] [Satannish] waited for 0s and no initial state was set by the discovery
[2016-09-14 09:51:40,786][INFO ][http                     ] [Satannish] publish_address {192.168.1.105:9220}, bound_addresses {192.168.1.105:9220}
[2016-09-14 09:51:40,786][INFO ][node                     ] [Satannish/A] starting ...
[2016-09-14 09:51:40,794][INFO ][transport                ] [Satannish/A] publish_address {192.168.1.105:9340}, bound_addresses {192.168.1.105:9340}
[2016-09-14 09:51:40,797][INFO ][discovery                ] [Satannish/A] clusterA/RcPrSmbnRlmSh1jPShYQjA
^C[2016-09-14 09:51:45,560][INFO ][node                     ] [Satannish] stopping ...
[2016-09-14 09:51:45,584][INFO ][node                     ] [Satannish] stopped
[2016-09-14 09:51:45,584][INFO ][node                     ] [Satannish] closing ...
[2016-09-14 09:51:45,584][INFO ][node                     ] [Satannish/A] stopping ...
[2016-09-14 09:51:45,590][INFO ][node                     ] [Satannish/A] stopped
[2016-09-14 09:51:45,590][INFO ][node                     ] [Satannish/A] closing ...
[2016-09-14 09:51:45,595][INFO ][node                     ] [Satannish/A] closed
[2016-09-14 09:51:45,595][INFO ][node                     ] [Satannish/B] closing ...
[2016-09-14 09:51:45,598][INFO ][node                     ] [Satannish/B] closed
[2016-09-14 09:51:45,598][INFO ][node                     ] [Satannish/M] closing ...
[2016-09-14 09:51:45,601][INFO ][node                     ] [Satannish/M] closed
[2016-09-14 09:51:45,603][INFO ][node                     ] [Satannish] closed

```

**Comment by jasontedor** [comment] 2016-11-13 20:13
I'm removing the adoptme label as I have a fix for this and will open a PR soon.

**Comment by jasontedor** [comment] 2016-11-14 17:07
I opened #21546.

**Closed** 2016-11-14 20:09 UTC
Labels: :Tribe Node, bug
