### ISSUE TITLE
cgroups Support in JDK 16+33 Failing in Kubernetes with --cgroup-driver=systemd

### ISSUE THREAD

**Issue by daviddyball** [elastic/elasticsearch#75767] opened 2021-07-28 07:06 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 7.13.4

**Plugins installed**: []

**JVM version** (`java -version`): JDK 16+33

**OS version** (`uname -a` if on a Unix-like system): `Linux ip-10-229-49-73.eu-west-2.compute.internal 5.10.43-flatcar #1 SMP Tue Jun 15 19:46:57 -00 2021 x86_64 x86_64 x86_64 GNU/Linux`

**OS Distribution**: Flatcar Linux `2765.2.6

**Description of the problem including expected versus actual behavior**:

Expected:

ECK provisioned 7.x container instances should run without issue

Actual:

7.x containers fails to start when running in Kubernetes with `kubelet` `--cgroup-driver=systemd`

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. Provision a Kubernetes cluster with Flatcar Linux 2765.2.6 as the host
 2. Ensure `kubelet` is started with `--cgroup-driver=systemd`
 3. Attempt to provision an `Elasticsearch` 7.13.4 instance using ECK 

**Provide logs (if relevant)**:
Stacktrace
```
Exception in thread "main" java.lang.InternalError: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.platform.Metrics.systemMetrics(Metrics.java:65)
	at java.base/jdk.internal.platform.Container.metrics(Container.java:43)
	at jdk.management/com.sun.management.internal.OperatingSystemImpl.<init>(OperatingSystemImpl.java:48)
	at jdk.management/com.sun.management.internal.PlatformMBeanProviderImpl.getOperatingSystemMXBean(PlatformMBeanProviderImpl.java:279)
	at jdk.management/com.sun.management.internal.PlatformMBeanProviderImpl$3.nameToMBeanMap(PlatformMBeanProviderImpl.java:198)
	at java.management/java.lang.management.ManagementFactory.lambda$getPlatformMBeanServer$0(ManagementFactory.java:487)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1766)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.management/java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:488)
	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:140)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:558)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:263)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:207)
	at org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:220)
	at org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:197)
	at org.elasticsearch.common.logging.LogConfigurator.configureStatusLogger(LogConfigurator.java:248)
	at org.elasticsearch.common.logging.LogConfigurator.configureWithoutConfig(LogConfigurator.java:95)
	at org.elasticsearch.cli.CommandLoggingConfigurator.configureLoggingWithoutConfig(CommandLoggingConfigurator.java:29)
	at org.elasticsearch.cli.Command.main(Command.java:76)
	at org.elasticsearch.common.settings.KeyStoreCli.main(KeyStoreCli.java:32)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at java.base/jdk.internal.platform.Metrics.systemMetrics(Metrics.java:61)
	... 26 more
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.platform.CgroupSubsystemFactory.create(CgroupSubsystemFactory.java:107)
	at java.base/jdk.internal.platform.CgroupMetrics.getInstance(CgroupMetrics.java:167)
	... 31 more
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:260)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at java.base/jdk.internal.platform.CgroupUtil.lambda$readStringValue$1(CgroupUtil.java:66)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	at java.base/jdk.internal.platform.CgroupUtil.readStringValue(CgroupUtil.java:68)
	at java.base/jdk.internal.platform.CgroupSubsystemController.getStringValue(CgroupSubsystemController.java:65)
	at java.base/jdk.internal.platform.CgroupSubsystemController.getLongValue(CgroupSubsystemController.java:124)
	at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.getLongValue(CgroupV1Subsystem.java:272)
	at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.getHierarchical(CgroupV1Subsystem.java:218)
	at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.setPath(CgroupV1Subsystem.java:201)
	at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.setSubSystemControllerPath(CgroupV1Subsystem.java:173)
	at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.lambda$initSubSystem$5(CgroupV1Subsystem.java:113)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.initSubSystem(CgroupV1Subsystem.java:113)
	at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.<clinit>(CgroupV1Subsystem.java:47)
	... 33 more
Exception in thread "main" java.lang.InternalError: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.platform.Metrics.systemMetrics(Metrics.java:65)
	at java.base/jdk.internal.platform.Container.metrics(Container.java:43)
	at jdk.management/com.sun.management.internal.OperatingSystemImpl.<init>(OperatingSystemImpl.java:48)
	at jdk.management/com.sun.management.internal.PlatformMBeanProviderImpl.getOperatingSystemMXBean(PlatformMBeanProviderImpl.java:279)
	at jdk.management/com.sun.management.internal.PlatformMBeanProviderImpl$3.nameToMBeanMap(PlatformMBeanProviderImpl.java:198)
	at java.management/sun.management.spi.PlatformMBeanProvider$PlatformComponent.getMBeans(PlatformMBeanProvider.java:195)
	at java.management/java.lang.management.ManagementFactory.getPlatformMXBean(ManagementFactory.java:686)
	at java.management/java.lang.management.ManagementFactory.getOperatingSystemMXBean(ManagementFactory.java:388)
	at org.elasticsearch.tools.launchers.DefaultSystemMemoryInfo.<init>(DefaultSystemMemoryInfo.java:28)
	at org.elasticsearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:125)
	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:86)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at java.base/jdk.internal.platform.Metrics.systemMetrics(Metrics.java:61)
	... 10 more
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.platform.CgroupSubsystemFactory.create(CgroupSubsystemFactory.java:107)
	at java.base/jdk.internal.platform.CgroupMetrics.getInstance(CgroupMetrics.java:167)
	... 15 more
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:260)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at java.base/jdk.internal.platform.CgroupUtil.lambda$readStringValue$1(CgroupUtil.java:66)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	at java.base/jdk.internal.platform.CgroupUtil.readStringValue(CgroupUtil.java:68)
	at java.base/jdk.internal.platform.CgroupSubsystemController.getStringValue(CgroupSubsystemController.java:65)
	at java.base/jdk.internal.platform.CgroupSubsystemController.getLongValue(CgroupSubsystemController.java:124)
	at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.getLongValue(CgroupV1Subsystem.java:272)
	at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.getHierarchical(CgroupV1Subsystem.java:218)
	at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.setPath(CgroupV1Subsystem.java:201)
	at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.setSubSystemControllerPath(CgroupV1Subsystem.java:173)
	at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.lambda$initSubSystem$5(CgroupV1Subsystem.java:113)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.initSubSystem(CgroupV1Subsystem.java:113)
	at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.<clinit>(CgroupV1Subsystem.java:47)
	... 17 more
```

Relevant Slack discussions [here](https://elasticstack.slack.com/archives/CS9KR083S/p1627390198124800) and [here](https://elasticstack.slack.com/archives/CNTP6NLTZ/p1627388450101300)

Upstream issue also filed against Kubernetes https://github.com/kubernetes/kubernetes/issues/103944

**Comment by albertzaharovits** [comment] 2021-07-29 13:57
I don't think there's any action on the part of Elasticsearch, but can someone from @elastic/es-core-infra please take a look?

**Comment by daviddyball** [comment] 2021-08-02 08:04
Perhaps a drastic action, but lowering the JDK shipped with 7.x images would alleviate the problem for those suffering it. Granted it's not really ES's fault that this is happening, so maybe not :woman_shrugging:

**Comment by rjernst** [comment] 2021-08-03 00:38
I dug through the stack trace, but I need more info to understand what is happening.

The problem occurs during initialization of the cgroup v1 wrapper. It looks is trying to initialize info for the memory subsystem when looks for `memory.use_hierarchy`. However, in trying to formulate the path to find this setting, the jdk code encounters a null value for the root path of the cgroup controller. 

The [path initialization code](https://github.com/openjdk/jdk/blob/739769c8fc4b496f08a92225a12d07414537b6c0/src/java.base/linux/classes/jdk/internal/platform/cgroupv1/CgroupV1SubsystemController.java#L45) hasn't changed since 2019, so it doesn't appear this is at fault. However, there are 3 ways it might result in a null path. The first is if `root` or `cgroupPath` are null, but this does not seem possible given the [initialization code](https://github.com/openjdk/jdk/blob/8d9cf48e813dee9567340720978392e04f736e65/src/java.base/linux/classes/jdk/internal/platform/cgroupv1/CgroupV1Subsystem.java#L59) which parses `/proc/self/mountinfo` and `/proc/self/cgroup`. The second way it could be null is if `root` is not `/` and `cgroupPath` does not begin with `root`. Finally, the third way is if the previous condition is false, but `cgroupPath` is shorter than `root`.

Perhaps these possible null cases were existing bugs that are now being surfaced. But I could not find any commits in JDK 16 in the relevant v1 files that would have changed the arguments passed. It would help in debugging if someone who can reproduce the issue were to capture `/proc/self/mountinfo` and `/proc/self/cgroup` from within the container.

And a final note in regard to downgrading the JDK. We would likely not do this as that would mean releasing with an EOL JDK since JDK 15 became EOL as soon as JDK 16 was released.

**Comment by daviddyball** [comment] 2021-08-04 13:28
Sorry for the delay in responding. Here's the info you wanted @rjernst. Thanks for looking into this. Totally understand about the JDK versioning. For now we've just built our own images replacing the JDK which works fine.

This is the contents of those proc files on one of our Flatcar `2765.2.6` instances that has this problem:

**/proc/self/mountinfo**
```
4577 3100 0:450 / / rw,relatime master:1128 - overlay overlay rw,lowerdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/20675/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/20674/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/20673/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/20672/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/20671/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/20670/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/2029/fs,upperdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/20687/fs,workdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/20687/work
4578 4577 0:489 / /proc rw,nosuid,nodev,noexec,relatime - proc proc rw
4579 4577 0:490 / /dev rw,nosuid - tmpfs tmpfs rw,seclabel,size=65536k,mode=755
4580 4579 0:525 / /dev/pts rw,nosuid,noexec,relatime - devpts devpts rw,seclabel,gid=5,mode=620,ptmxmode=666
4581 4579 0:431 / /dev/mqueue rw,nosuid,nodev,noexec,relatime - mqueue mqueue rw,seclabel
4582 4577 0:446 / /sys ro,nosuid,nodev,noexec,relatime - sysfs sysfs ro,seclabel
4583 4582 0:526 / /sys/fs/cgroup rw,nosuid,nodev,noexec,relatime - tmpfs tmpfs rw,seclabel,mode=755
4584 4583 0:23 /system.slice/containerd.service/kubepods-burstable-podf65e797d_d5f9_4604_9773_94f4bb9946a0.slice:cri-containerd:86ac6260f9f8a9c1276748250f330ae9c2fcefe5ae809364ad1e45f3edf7e08a /sys/fs/cgroup/systemd ro,nosuid,nodev,noexec,relatime master:6 - cgroup cgroup rw,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd
4617 4583 0:26 /kubepods-burstable-podf65e797d_d5f9_4604_9773_94f4bb9946a0.slice:cri-containerd:86ac6260f9f8a9c1276748250f330ae9c2fcefe5ae809364ad1e45f3edf7e08a /sys/fs/cgroup/freezer ro,nosuid,nodev,noexec,relatime master:7 - cgroup cgroup rw,freezer
4620 4583 0:27 /kubepods-burstable-podf65e797d_d5f9_4604_9773_94f4bb9946a0.slice:cri-containerd:86ac6260f9f8a9c1276748250f330ae9c2fcefe5ae809364ad1e45f3edf7e08a /sys/fs/cgroup/net_cls,net_prio ro,nosuid,nodev,noexec,relatime master:8 - cgroup cgroup rw,net_cls,net_prio
4621 4583 0:28 /system.slice/containerd.service/kubepods-burstable-podf65e797d_d5f9_4604_9773_94f4bb9946a0.slice:cri-containerd:86ac6260f9f8a9c1276748250f330ae9c2fcefe5ae809364ad1e45f3edf7e08a /sys/fs/cgroup/pids ro,nosuid,nodev,noexec,relatime master:9 - cgroup cgroup rw,pids
4622 4583 0:29 /system.slice/containerd.service/kubepods-burstable-podf65e797d_d5f9_4604_9773_94f4bb9946a0.slice:cri-containerd:86ac6260f9f8a9c1276748250f330ae9c2fcefe5ae809364ad1e45f3edf7e08a /sys/fs/cgroup/blkio ro,nosuid,nodev,noexec,relatime master:10 - cgroup cgroup rw,blkio
4623 4583 0:30 /kubepods-burstable-podf65e797d_d5f9_4604_9773_94f4bb9946a0.slice:cri-containerd:86ac6260f9f8a9c1276748250f330ae9c2fcefe5ae809364ad1e45f3edf7e08a /sys/fs/cgroup/perf_event ro,nosuid,nodev,noexec,relatime master:11 - cgroup cgroup rw,perf_event
4624 4583 0:31 /system.slice/containerd.service/kubepods-burstable-podf65e797d_d5f9_4604_9773_94f4bb9946a0.slice:cri-containerd:86ac6260f9f8a9c1276748250f330ae9c2fcefe5ae809364ad1e45f3edf7e08a /sys/fs/cgroup/memory ro,nosuid,nodev,noexec,relatime master:12 - cgroup cgroup rw,memory
4625 4583 0:32 /system.slice/containerd.service/kubepods-burstable-podf65e797d_d5f9_4604_9773_94f4bb9946a0.slice:cri-containerd:86ac6260f9f8a9c1276748250f330ae9c2fcefe5ae809364ad1e45f3edf7e08a /sys/fs/cgroup/devices ro,nosuid,nodev,noexec,relatime master:13 - cgroup cgroup rw,devices
4626 4583 0:33 /system.slice/containerd.service/kubepods-burstable-podf65e797d_d5f9_4604_9773_94f4bb9946a0.slice:cri-containerd:86ac6260f9f8a9c1276748250f330ae9c2fcefe5ae809364ad1e45f3edf7e08a /sys/fs/cgroup/cpu,cpuacct ro,nosuid,nodev,noexec,relatime master:14 - cgroup cgroup rw,cpu,cpuacct
4627 4583 0:34 /kubepods-burstable-podf65e797d_d5f9_4604_9773_94f4bb9946a0.slice:cri-containerd:86ac6260f9f8a9c1276748250f330ae9c2fcefe5ae809364ad1e45f3edf7e08a /sys/fs/cgroup/hugetlb ro,nosuid,nodev,noexec,relatime master:15 - cgroup cgroup rw,hugetlb
4628 4583 0:35 /kubepods-burstable-podf65e797d_d5f9_4604_9773_94f4bb9946a0.slice:cri-containerd:86ac6260f9f8a9c1276748250f330ae9c2fcefe5ae809364ad1e45f3edf7e08a /sys/fs/cgroup/cpuset ro,nosuid,nodev,noexec,relatime master:16 - cgroup cgroup rw,cpuset
4629 4577 202:9 /var/lib/containerd/io.containerd.grpc.v1.cri/sandboxes/7e6f6132b4f3586e826f29e79681570c458df56e89e1062a8858ab8715ecf31e/resolv.conf /etc/resolv.conf rw,relatime - ext4 /dev/xvda9 rw,seclabel
4630 4577 202:9 /var/lib/containerd/io.containerd.grpc.v1.cri/sandboxes/7e6f6132b4f3586e826f29e79681570c458df56e89e1062a8858ab8715ecf31e/hostname /etc/hostname rw,relatime - ext4 /dev/xvda9 rw,seclabel
4631 4579 202:9 /var/lib/kubelet/pods/f65e797d-d5f9-4604-9773-94f4bb9946a0/containers/elasticsearch/6c8c0933 /dev/termination-log rw,relatime - ext4 /dev/xvda9 rw,seclabel
4632 4577 202:9 /var/lib/kubelet/pods/f65e797d-d5f9-4604-9773-94f4bb9946a0/etc-hosts /etc/hosts rw,relatime - ext4 /dev/xvda9 rw,seclabel
4633 4579 0:426 / /dev/shm rw,nosuid,nodev,noexec,relatime - tmpfs shm rw,seclabel,size=65536k
4634 4577 202:9 /var/lib/kubelet/pods/f65e797d-d5f9-4604-9773-94f4bb9946a0/volumes/kubernetes.io~configmap/elastic-internal-unicast-hosts /mnt/elastic-internal/unicast-hosts ro,relatime - ext4 /dev/xvda9 rw,seclabel
4635 4577 0:405 / /mnt/elastic-internal/elasticsearch-config ro,relatime - tmpfs tmpfs rw,seclabel
4636 4577 0:416 / /mnt/elastic-internal/probe-user ro,relatime - tmpfs tmpfs rw,seclabel
4637 4577 0:407 / /mnt/elastic-internal/xpack-file-realm ro,relatime - tmpfs tmpfs rw,seclabel
4638 4577 202:9 /var/lib/kubelet/pods/f65e797d-d5f9-4604-9773-94f4bb9946a0/volumes/kubernetes.io~configmap/elastic-internal-scripts /mnt/elastic-internal/scripts ro,relatime - ext4 /dev/xvda9 rw,seclabel
4639 4577 0:418 / /mnt/elastic-internal/downward-api ro,relatime - tmpfs tmpfs rw,seclabel
4662 4577 202:9 /var/lib/kubelet/pods/f65e797d-d5f9-4604-9773-94f4bb9946a0/volumes/kubernetes.io~empty-dir/elastic-internal-elasticsearch-bin-local /usr/share/elasticsearch/bin rw,relatime - ext4 /dev/xvda9 rw,seclabel
4663 4577 202:14848 / /usr/share/elasticsearch/data rw,relatime - ext4 /dev/xvdbg rw,seclabel
4664 4577 202:9 /var/lib/kubelet/pods/f65e797d-d5f9-4604-9773-94f4bb9946a0/volumes/kubernetes.io~empty-dir/elasticsearch-logs /usr/share/elasticsearch/logs rw,relatime - ext4 /dev/xvda9 rw,seclabel
4675 4577 202:9 /var/lib/kubelet/pods/f65e797d-d5f9-4604-9773-94f4bb9946a0/volumes/kubernetes.io~empty-dir/elastic-internal-elasticsearch-plugins-local /usr/share/elasticsearch/plugins rw,relatime - ext4 /dev/xvda9 rw,seclabel
4677 4577 202:9 /var/lib/kubelet/pods/f65e797d-d5f9-4604-9773-94f4bb9946a0/volumes/kubernetes.io~empty-dir/elastic-internal-elasticsearch-config-local /usr/share/elasticsearch/config rw,relatime - ext4 /dev/xvda9 rw,seclabel
4678 4677 0:415 / /usr/share/elasticsearch/config/http-certs ro,relatime - tmpfs tmpfs rw,seclabel
4679 4677 0:417 / /usr/share/elasticsearch/config/transport-remote-certs ro,relatime - tmpfs tmpfs rw,seclabel
4680 4677 0:404 / /usr/share/elasticsearch/config/transport-certs ro,relatime - tmpfs tmpfs rw,seclabel
3101 4579 0:525 /0 /dev/console rw,nosuid,noexec,relatime - devpts devpts rw,seclabel,gid=5,mode=620,ptmxmode=666
3102 4578 0:489 /bus /proc/bus ro,relatime - proc proc rw
3103 4578 0:489 /fs /proc/fs ro,relatime - proc proc rw
3135 4578 0:489 /irq /proc/irq ro,relatime - proc proc rw
3136 4578 0:489 /sys /proc/sys ro,relatime - proc proc rw
3137 4578 0:489 /sysrq-trigger /proc/sysrq-trigger ro,relatime - proc proc rw
3138 4578 0:527 / /proc/acpi ro,relatime - tmpfs tmpfs ro,seclabel
3139 4578 0:490 /null /proc/kcore rw,nosuid - tmpfs tmpfs rw,seclabel,size=65536k,mode=755
3168 4578 0:490 /null /proc/keys rw,nosuid - tmpfs tmpfs rw,seclabel,size=65536k,mode=755
3169 4578 0:490 /null /proc/latency_stats rw,nosuid - tmpfs tmpfs rw,seclabel,size=65536k,mode=755
3170 4578 0:490 /null /proc/timer_list rw,nosuid - tmpfs tmpfs rw,seclabel,size=65536k,mode=755
3171 4578 0:490 /null /proc/sched_debug rw,nosuid - tmpfs tmpfs rw,seclabel,size=65536k,mode=755
3172 4578 0:528 / /proc/scsi ro,relatime - tmpfs tmpfs ro,seclabel
3173 4582 0:545 / /sys/firmware ro,relatime - tmpfs tmpfs ro,seclabel
```

**/proc/self/cgroup**
```
11:cpuset:/kubepods-burstable-podf65e797d_d5f9_4604_9773_94f4bb9946a0.slice:cri-containerd:86ac6260f9f8a9c1276748250f330ae9c2fcefe5ae809364ad1e45f3edf7e08a
10:hugetlb:/kubepods-burstable-podf65e797d_d5f9_4604_9773_94f4bb9946a0.slice:cri-containerd:86ac6260f9f8a9c1276748250f330ae9c2fcefe5ae809364ad1e45f3edf7e08a
9:cpu,cpuacct:/system.slice/containerd.service/kubepods-burstable-podf65e797d_d5f9_4604_9773_94f4bb9946a0.slice:cri-containerd:86ac6260f9f8a9c1276748250f330ae9c2fcefe5ae809364ad1e45f3edf7e08a
8:devices:/system.slice/containerd.service/kubepods-burstable-podf65e797d_d5f9_4604_9773_94f4bb9946a0.slice:cri-containerd:86ac6260f9f8a9c1276748250f330ae9c2fcefe5ae809364ad1e45f3edf7e08a
7:memory:/system.slice/containerd.service/kubepods-burstable-podf65e797d_d5f9_4604_9773_94f4bb9946a0.slice:cri-containerd:86ac6260f9f8a9c1276748250f330ae9c2fcefe5ae809364ad1e45f3edf7e08a
6:perf_event:/kubepods-burstable-podf65e797d_d5f9_4604_9773_94f4bb9946a0.slice:cri-containerd:86ac6260f9f8a9c1276748250f330ae9c2fcefe5ae809364ad1e45f3edf7e08a
5:blkio:/system.slice/containerd.service/kubepods-burstable-podf65e797d_d5f9_4604_9773_94f4bb9946a0.slice:cri-containerd:86ac6260f9f8a9c1276748250f330ae9c2fcefe5ae809364ad1e45f3edf7e08a
4:pids:/system.slice/containerd.service/kubepods-burstable-podf65e797d_d5f9_4604_9773_94f4bb9946a0.slice:cri-containerd:86ac6260f9f8a9c1276748250f330ae9c2fcefe5ae809364ad1e45f3edf7e08a
3:net_cls,net_prio:/kubepods-burstable-podf65e797d_d5f9_4604_9773_94f4bb9946a0.slice:cri-containerd:86ac6260f9f8a9c1276748250f330ae9c2fcefe5ae809364ad1e45f3edf7e08a
2:freezer:/kubepods-burstable-podf65e797d_d5f9_4604_9773_94f4bb9946a0.slice:cri-containerd:86ac6260f9f8a9c1276748250f330ae9c2fcefe5ae809364ad1e45f3edf7e08a
1:name=systemd:/system.slice/containerd.service/kubepods-burstable-podf65e797d_d5f9_4604_9773_94f4bb9946a0.slice:cri-containerd:86ac6260f9f8a9c1276748250f330ae9c2fcefe5ae809364ad1e45f3edf7e08a
0::/
```

**Comment by rjernst** [comment] 2021-08-04 16:09
@daviddyball Thanks for the info. Can you please also do an `ls` of the path in `/proc/self/cgroup` listed for memory? In the above it is `/system.slice/containerd.service/kubepods-burstable-podf65e797d_d5f9_4604_9773_94f4bb9946a0.slice:cri-containerd:86ac6260f9f8a9c1276748250f330ae9c2fcefe5ae809364ad1e45f3edf7e08a` but I assume that may change if you already removed the pod.

**Comment by rjernst** [comment] 2021-08-04 17:04
Scratch that, it's not necessary. I've extracted the paths for memory and reproduced this using the setPath method from the jdk. The condition that fails, which allows path to fall through unset, is `cgroupPath.startsWith(root)`, so that is `/system.slice/containerd.service/kubepods-burstable-podf65e797d_d5f9_4604_9773_94f4bb9946a0.slice:cri-containerd:86ac6260f9f8a9c1276748250f330ae9c2fcefe5ae809364ad1e45f3edf7e08a` does not start with the root path `/system.slice/containerd.service/kubepods-burstable-podf65e797d_d5f9_4604_9773_94f4bb9946a0.slice`. Note that this is the wrong path!

The problem is the JDK's parsing of `/self/proc/cgroup` does not account for paths which could contain `:`. A split is done on colon of each line in that file, but without any limit, when in fact there should be 3 entries (2 splits). The extra `86ac6260f9f8a9c1276748250f330ae9c2fcefe5ae809364ad1e45f3edf7e08a` is silently thrown away.

I'll file a bug with OpenJDK. In the meantime, I'm not sure if it is possible to change your kubernetes configuration to not use colons as a separator? If not, using an older JDK seems like the next best workaround, though I'm surprised you say it works with JDK 15, as the bug appears to have existing as far back in history as I could find (which was only back to 2019 because of renames).

**Comment by rjernst** [comment] 2021-08-04 17:07
> I'm surprised you say it works with JDK 15

Ah, I looked back in the kubernetes issue and see it was actually JDK 12. I'm still not sure which change caused the bug, but that would be before 2019.

**Comment by daviddyball** [comment] 2021-08-05 12:46
Yeh, typo on my part... We switched to JDK 12 and it's working for now :+1:

**Comment by rjernst** [comment] 2021-08-10 14:10
The bug report was accepted by OpenJDK: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8272124

Given that this is an upstream issue, and there is no work to be done in ES it is fixed except upgrading the JDK, I hope you don't mind I close this issue. Note that I don't expect a fix anytime soon, it's been marked as P3, so pretty low priority.

**Closed by rjernst** 2021-08-10 14:10 UTC
Labels: >bug, :Core/Infra/Core, Team:Core/Infra

**Comment by daviddyball** [comment] 2021-08-11 08:29
Thanks for all the assistance @rjernst :+1:
