### ISSUE TITLE
[CI] "mlt/20_docs/Basic mlt query with docs" failure

### ISSUE THREAD

**Issue by kingherc** [elastic/elasticsearch#97419] opened 2023-07-06 11:29 UTC
### CI Link

https://gradle-enterprise.elastic.co/s/mkrx32ji64tua

### Repro line

```
./gradlew ':qa:mixed-cluster:v8.8.3#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=mlt/20_docs/Basic mlt query with docs}" -Dtests.seed=E0B4B36539AB6408 -Dtests.bwc=true -Dtests.locale=sv -Dtests.timezone=Europe/Bratislava -Druntime.java=20
```

### Does it reproduce?

Didn't try

### Applicable branches

main

### Failure excerpt

This issue had appeared in https://github.com/elastic/elasticsearch/issues/68908 but that was closed because it had not repeated in a long time. Now I saw it in the CI of https://github.com/elastic/elasticsearch/pull/97417, whose changes should have nothing to do with this test and thus I think this occurs in `main` as well.

Excerpt:

```
[2023-07-06T12:59:49,112][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] [test] [p0=mlt/20_docs/Basic mlt query with docs] before test
jul 06, 2023 12:59:49 EM org.elasticsearch.client.RestClient logResponse
WARNING: request [PUT http://[::1]:44091/_template/global] returned 2 warnings: [299 Elasticsearch-8.10.0-SNAPSHOT-7cac6d6fa6ed52d46b0c044525653fedce341ff1 "Legacy index templates are deprecated in favor of composable templates."],[299 Elasticsearch-8.8.3-SNAPSHOT-942648d64bb6a56f729f292c40ede12609206ca2 "legacy template [global] has index patterns [*] matching patterns from existing composable templates [.deprecation-indexing-template,.fleet-file-data,.fleet-fileds-fromhost-data,.fleet-fileds-fromhost-meta,.fleet-fileds-tohost-data,.fleet-fileds-tohost-meta,.fleet-files,.ml-anomalies-,.ml-notifications-000002,.ml-state,.ml-stats,.monitoring-beats-mb,.monitoring-ent-search-mb,.monitoring-es-mb,.monitoring-kibana-mb,.monitoring-logstash-mb,.slm-history,.watch-history-16,behavioral_analytics-events-default,ilm-history,logs,metrics,synthetics] with patterns (.deprecation-indexing-template => [.logs-deprecation.*],.fleet-file-data => [.fleet-file-data-*-*],.fleet-fileds-fromhost-data => [.fleet-fileds-fromhost-data-*],.fleet-fileds-fromhost-meta => [.fleet-fileds-fromhost-meta-*],.fleet-fileds-tohost-data => [.fleet-fileds-tohost-data-*],.fleet-fileds-tohost-meta => [.fleet-fileds-tohost-meta-*],.fleet-files => [.fleet-files-*-*],.ml-anomalies- => [.ml-anomalies-*],.ml-notifications-000002 => [.ml-notifications-000002],.ml-state => [.ml-state*],.ml-stats => [.ml-stats-*],.monitoring-beats-mb => [.monitoring-beats-8-*],.monitoring-ent-search-mb => [.monitoring-ent-search-8-*],.monitoring-es-mb => [.monitoring-es-8-*],.monitoring-kibana-mb => [.monitoring-kibana-8-*],.monitoring-logstash-mb => [.monitoring-logstash-8-*],.slm-history => [.slm-history-5*],.watch-history-16 => [.watcher-history-16*],behavioral_analytics-events-default => [behavioral_analytics-events-*],ilm-history => [ilm-history-5*],logs => [logs-*-*],metrics => [metrics-*-*],synthetics => [synthetics-*-*]); this template [global] may be ignored in favor of a composable template at index creation time"]
[2023-07-06T12:59:49,292][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] [test] Dump test yaml [/dev/shm/elastic+elasticsearch+pull-request+bwc/qa/mixed-cluster/build/restResources/yamlTests/rest-api-spec/test/mlt/20_docs.yml] on failure:
---
"Basic mlt query with docs":
  - do:
      indices.create:
        index: test_1

  - do:
      index:
          index:  test_1
          id:     "1"
          body:   { foo: bar }

  - do:
      index:
          index:  test_1
          id:     "2"
          body:   { foo: baz }

  - do:
      index:
          index:  test_1
          id:     "3"
          body:   { foo: foo }

  - do:
      indices.refresh: {}

  - do:
      search:
          rest_total_hits_as_int: true
          index:   test_1
          body:
            query:
              more_like_this:
                like:
                  -
                    _index: test_1
                    doc:
                      foo: bar
                  -
                    _index: test_1
                    _id: "2"
                  -
                    _id: "3"
                include: true
                min_doc_freq: 0
                min_term_freq: 0

  - match: { hits.total: 3 }

[2023-07-06T12:59:49,295][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] [test] Stash dump on test failure [{
  "stash" : {
    "body" : {
      "took" : 38,
      "timed_out" : false,
      "_shards" : {
        "total" : 2,
        "successful" : 2,
        "skipped" : 0,
        "failed" : 0
      },
      "hits" : {
        "total" : 2,
        "max_score" : 1.9616582,
        "hits" : [
          {
            "_index" : "test_1",
            "_id" : "1",
            "_score" : 1.9616582,
            "_source" : {
              "foo" : "bar"
            }
          },
          {
            "_index" : "test_1",
            "_id" : "2",
            "_score" : 1.9616582,
            "_source" : {
              "foo" : "baz"
            }
          }
        ]
      }
    }
  }
}]
[2023-07-06T12:59:49,488][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] [test] There are still tasks running after this test that might break subsequent tests [health-node[c]].
[2023-07-06T12:59:49,488][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] [test] [p0=mlt/20_docs/Basic mlt query with docs] after test
REPRODUCE WITH: ./gradlew ':qa:mixed-cluster:v8.8.3#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=mlt/20_docs/Basic mlt query with docs}" -Dtests.seed=E0B4B36539AB6408 -Dtests.bwc=true -Dtests.locale=sv -Dtests.timezone=Europe/Bratislava -Druntime.java=20
```

**Comment by pmpailis** [comment] 2023-10-13 11:12
Looking at the logs, we have 17 failures of the above test, were:
* 5 of them are related to the above AssertionError: `Expected: <3> but: was <2>`
* 12 of them are `resource_already_exists_exception`  (e.g. [here](https://gradle-enterprise.elastic.co/s/hd47ryhpg3jtg/tests/task/:qa:mixed-cluster:v7.3.0%23mixedClusterTest/details/org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT/test%20%7Bp0=mlt%2F20_docs%2FBasic%20mlt%20query%20with%20docs%7D?top-execution=1))

Could not reproduce locally with most of the gradle commands tested. Will take a look and update the issue accordingly.

**Comment by dakrone** [comment] 2023-11-02 18:35
Another failure: https://gradle-enterprise.elastic.co/s/mjlxmnwvge37q/tests/task/:qa:mixed-cluster:v7.17.15%23mixedClusterTest/details/org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT/test%20%7Bp0=mlt%2F20_docs%2FBasic%20mlt%20query%20with%20docs%7D?top-execution=1

**Comment by pmpailis** [comment] 2023-12-04 15:05
New failure: https://gradle-enterprise.elastic.co/s/wzrpr72kqpr3y/tests/task/:qa:mixed-cluster:v7.17.16%23mixedClusterTest/details/org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT/test%20%7Bp0=mlt%2F20_docs%2FBasic%20mlt%20query%20with%20docs%7D?top-execution=1

**Comment by pmpailis** [comment] 2024-02-13 11:05
The last reported error was on Dec. 6th, and we have only 3 such instances in the past 3 months.

<img width="1463" alt="Screenshot 2024-02-13 at 13 04 14" src="https://github.com/elastic/elasticsearch/assets/5754173/0b614775-02bb-490d-bd41-8e2d2a0c204f">


Closing this ticket. We can reopen if the error re-surfaces.

**Closed** 2024-02-13 11:05 UTC
Labels: :Search/Search, >test-failure, Team:Search, low-risk
