### ISSUE TITLE
ElasticSearch 7.8 date and time format issue: unable to store date in MMM-dd-yyyy HH:mm:ss format . Was woking in 6.7.1

### ISSUE THREAD

**Issue by nsharmacovs** [elastic/elasticsearch#61167] opened 2020-08-14 18:28 UTC
We are unable to store the date value as MMM-dd-yyyy HH:mm:ss. in elastic search 7.8.0 . This format was working in ELK 6.7.1. 

This is making the migration of data from the old index (6.7.1) to new index(7.8.0) impossible due to date format issues.

Appreciate your help and guidance.

Error :- 
[2020-08-10T14:30:58,866][WARN ][logstash.outputs.elasticsearch][main] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"metrics", :routing=>nil, :_type=>"_doc"}, #LogStash::Event:0x37d9caae], :response=>{"index"=>{"_index"=>"metrics-20200803", "_type"=>"_doc", "_id"=>"P5Sj2XMBruMyh45v0qce", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse field [metric_date] of type [date] in document with id 'P5Sj2XMBruMyh45v0qce'. Preview of field's value: 'AUG-10-2020 04:00:00'", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"failed to parse date field [AUG-10-2020 04:00:00] with format [MMM-dd-yyyy||MMM-dd-yyyy HH:mm:ss]", "caused_by"=>{"type"=>"date_time_parse_exception", "reason"=>"Failed to parse with all enclosed parsers"}}}}}}

index:- 
PUT metrics-20200403
{
"settings": {
"index": {
"number_of_shards": "3",
"number_of_replicas": "2"
}
},
"mappings": {
"doc": {
"properties": {
"metric_date": { "type": "date", "format": "MMM-dd-yyyy||MMM-dd-yyyy HH:mm:ss" }
}
}
}

**Comment by rjernst** [comment] 2020-08-14 20:26
I reproduced this easily. The problem appears to be Joda handled all dates in a case insensitive manner, while the Java 8 Time is case *sensitive*, at least by default. So the month part of the format is not matching because `AUG` is uppercased, but `Aug` works. Unfortunately there is no format specifier for case insensitive; it can only be turned on when building the formatter in code.

@pgomulka Can you please take a look at this? We should consider whether we need an additional flag somewhere, or make all our formatters case insensitive?

**Comment by pgomulka** [comment] 2020-08-17 12:51
I am also not aware of any format specifies to make the pattern case insensitive. The only way is to set this on a builder in java.
if we were to follow joda behaviour then making formats case insensitive by default would be a way to go.  This won't be exactly the same though. Joda only allows all upper, or all lower case for textual field. With case insensitive we would allow mix of upper/lower possible as well http://joda-interest.219941.n2.nabble.com/JodaTime-1-5-2-DateTimeFormatter-and-case-sensitivity-td364187.html

Adding an additional mapping flag strikes me as an overdo. Adding a cluster setting also sounds a bit too complex and low level.
Months, Day of weeks names are defined in java by locale. In some Locale months cannot start with an upper letter, when in others they can. Adding a custom "upper case" locale would be very tedious for a user. I think this can be worked around by simply preprocessing and skipping the textual month part (MMM) ?


If we want to fix this I would go for a case insensitive by default.

**Comment by pgomulka** [comment] 2020-08-31 07:48
we discussed this during core infra sync on 26th August.
The conclusion is that we will allow setting case insensitivity for date format per field with an additional mapping parameter. i.e. 
```
PUT my-index-000001
{
  "mappings": {
    "properties": {
      "date": {
        "type":   "date",
        "format": "MMM-dd-yyyy||MMM-dd-yyyy HH:mm:ss",
        "case_ignore" : true
      }
    }
  }
}
```
The flag will apply to both `MMM-dd-yyyy` and `MMM-dd-yyyy HH:mm:ss` and will enable `parseCaseInsensitive` on a `DateTimeFormatterBuilder` - meaning that all combinations Aug, AUG, aug, aUg will be allowed (this is more relaxed then joda)
Name flag to be discussed on the PR that will follow

@cjcenizal pinging as this probably affects ES UI for mapping editor

**Comment by cjcenizal** [comment] 2020-08-31 13:20
Thanks for the ping @pgomulka! Great call, this will affect the mappings editor. Would you mind pinging @elastic/es-ui on the subsequent PR, too?

**Comment by pgomulka** [comment] 2020-08-31 15:59
will do!

**Comment by rjernst** [comment] 2024-08-07 20:17
We never got around to this, and haven't seen anymore requests for the feature in several years. Given that the workaround of using an ingest processor to preprocess the data should be easy, I'm going to close this for now.

**Closed by rjernst** 2024-08-07 20:17 UTC
Labels: :Core/Infra/Core, Team:Core/Infra
