### ISSUE TITLE
Docker builds failing on downloading and extracting OpenJDK

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#48213] opened 2019-10-17 20:14 UTC
Seeing a [number of build failures](https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=non_verification&failures.failureMessage=*%0A%3E%20Exit-code%201%20when%20calling%20/usr/local/bin/docker-compose,%20stdout:%20Step%201/29*&list.offset=0&list.size=50&list.sortColumn=startTime&list.sortOrder=desc&search.buildToolType=gradle&search.buildToolType=maven&search.startTimeMax=1571343093220&search.startTimeMin=1568876400000&trends.section=overview&trends.timeResolution=day&viewer.tzOffset=-420) with the following error:

```
:distribution:docker:composeUp FAILED
--
/bin/sh: /tmp/_MEILJnGTU/libreadline.so.7: no version information available (required by /bin/sh)
Building elasticsearch-default
Service 'elasticsearch-default' failed to build: The command '/bin/sh -c curl -L --retry 8 -s https://github.com/AdoptOpenJDK/openjdk13-binaries/releases/download/jdk-13%2B33/OpenJDK13U-jdk_x64_linux_hotspot_13_33.tar.gz \| tar -C /opt -zxf -' returned a non-zero code: 2
```

We have a pretty aggressive retry configuration here (8 attempts), but it's not clear if we are even performing 8 retries since we're silencing output. Perhaps we should use `-S` instead so we at least get the root error cause in the output?

**Comment by mark-vieira** [comment] 2019-10-17 20:15
@atorok @rjernst @jasontedor thoughts?

**Comment by atorok** [comment] 2019-10-18 08:29
Duplicate of #48129

**Closed by atorok** 2019-10-18 08:29 UTC
Labels: :Core/Infra/Build
