### ISSUE TITLE
DIsk based allocator should take into account the amount of disk space which can be reused

### ISSUE THREAD

**Issue by maf23** [elastic/elasticsearch#10103] opened 2015-03-16 09:17 UTC
Assume we have a node where the disk usage is above the low watermark. If we restart this node then no shards will be allocated on it since the disk usage is above the low watermark.

It would be better if the disk based allocator could realize that it can throw away or at least reuse the space which is currently used for outdated shard copies on the node.

**Comment by clintongormley** [comment] 2015-04-05 20:07
@dakrone any thoughts about this?

**Comment by dakrone** [comment] 2015-05-08 16:15
@clintongormley hmm.. to implement this we would have to send a request for each shard to all nodes to see what files and checksums they have in common. This would be quite heavy, especially for an `AllocationDecider` (because it has to run in tight loops).

**Comment by clintongormley** [comment] 2015-05-08 17:31
@dakrone thanks for commenting, that sounds... heavy.  Perhaps once sequence IDs (https://github.com/elastic/elasticsearch/issues/10708) are in, it'll be more feasible.

Marking as stalled.

**Comment by clintongormley** [comment] 2015-12-05 20:29
@dakrone @bleskes I think this has been resolved already, no?

**Comment by dakrone** [comment] 2015-12-09 00:02
@clintongormley no, it hasn't be resolved still, I'm not sure if the seqids work is far enough along to work on this, maybe @bleskes knows?

**Comment by bleskes** [comment] 2015-12-09 08:27
I don't think we can expect this in the first iteration. The problem is very similar to the current file based copy - we don't know how much will be reused (or if seq no base recovery will succeed) until we start the work. The master needs to know this in advance somehow (as Lee already said).

**Comment by DaveCTurner** [comment] 2018-03-20 10:05
As I understand it, the situation described here is a transient problem around a node restart in the sense that the cluster sorts itself out eventually once it works out what data it no longer needs. As such, since its opening we have not seen enough feedback that it is something we should work on. We prefer to close this issue as a clear indication that we are not going to work on this at this time. We are always open to reconsidering this in the future based on compelling feedback; despite this issue being closed please feel free to leave feedback (including +1s).

**Closed by DaveCTurner** 2018-03-20 10:05 UTC
Labels: :Distributed/Allocation, stalled
