### ISSUE TITLE
Scripted metric aggregation docs

### ISSUE THREAD

**Issue by albertocsm** [elastic/elasticsearch#15834] opened 2016-01-07 16:04 UTC
it appears the docs on the scripted metric aggregation are obsolete/wrong
on ES 1.6 the init of a new prop on _agg, if done as documented(1), will throw with something like 
```
GroovyScriptExecutionException[MissingPropertyException[No such property: transactions for class: Script93]]
```

if the the prop is accessed directly and init (2), all works as expected

(1)
```
init_script" : "_agg['transactions'] = []"
```

(2)
```
init_script" : "_agg.transactions = []"
```

**Comment by clintongormley** [comment] 2016-01-10 10:10
@colings86 could you look at this please?

**Comment by colings86** [comment] 2016-01-11 11:24
I can reproduce this in 1.6.1, 1.7.3, and 2.1.1. I'm not sure what changed though as the init_script in (1) worked when the scripted_metric was created. Maybe @dakrone, @pickypg or @jdconrad knows what might have changed in the groovy scripting engine to cause this and whether it was intended or if this is a bug?

**Comment by clintongormley** [comment] 2016-03-01 11:28
This is a test bug :)

When pasting a curl statement into the console, the single quotes in `"_agg['transactions'] = []"` need to be escaped.

Running the same commands in Sense works just fine.  Closing

**Closed by clintongormley** 2016-03-01 11:28 UTC
Labels: docs
