### ISSUE TITLE
Percolator with groovy script filter fails on concurrent use

### ISSUE THREAD

**Issue by mvdz** [elastic/elasticsearch#8879] opened 2014-12-10 14:30 UTC
Tested on Elasticsearch 1.4.1.

Prepare the mapping and percolator:

```
curl -XPUT localhost:9200/test -d '{
  "mappings" : {
    "test" : {
      "properties" : {
        "name" : {
          "type" : "string"
        }
      }
    }
  }
}'
curl -XPUT localhost:9200/test/.percolator/1 -d '{
  "type": "test",
  "query": {
    "constant_score": {
      "filter": {
        "script": {
          "script": "doc[\"name\"].value == \"a\"",
          "lang": "groovy"
        }
      }
    }
  }
}'
```

This script tests for a match, it keeps looping silently as long as the expected result arrives. When an unexpected result arrives it's printed and the loop terminates:

```
while ! curl -s localhost:9200/test/test/_percolate -d '{ "doc": { "name": "a" } }' | grep -v '"failed":0},"total":1'; do :; done
```

This one tests a document that does not match, also keeps looping as long as the expected result arrives:

```
while ! curl -s localhost:9200/test/test/_percolate -d '{ "doc": { "name": "b" } }' | grep -v '"failed":0},"total":0'; do :; done
```

When running only one of them, it keeps running as expected.

When I run both at the same time, one of them terminates quickly with the wrong result.

Running the same one twice at the same time it takes a few seconds, but one of them terminates with a failed shard operation and this stack trace appears in the log:

```
[2014-12-10 15:14:34,652][DEBUG][action.percolate         ] [Crown] [test][2], node[3k5o4J4zTyeBQ1eAN2-Smw], [P], s[STARTED]: failed to execute [org.elasticsearch.action.percolate.PercolateRequest@290522d3]
org.elasticsearch.percolator.PercolateException: failed to percolate
    at org.elasticsearch.action.percolate.TransportPercolateAction.shardOperation(TransportPercolateAction.java:195)
    at org.elasticsearch.action.percolate.TransportPercolateAction.shardOperation(TransportPercolateAction.java:56)
    at org.elasticsearch.action.support.broadcast.TransportBroadcastOperationAction$AsyncBroadcastAction$1.run(TransportBroadcastOperationAction.java:171)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Caused by: org.elasticsearch.percolator.PercolateException: failed to execute
    at org.elasticsearch.percolator.PercolatorService$4.doPercolate(PercolatorService.java:561)
    at org.elasticsearch.percolator.PercolatorService.percolate(PercolatorService.java:239)
    at org.elasticsearch.action.percolate.TransportPercolateAction.shardOperation(TransportPercolateAction.java:192)
    ... 5 more
Caused by: org.elasticsearch.script.groovy.GroovyScriptExecutionException: ArrayIndexOutOfBoundsException[null]
    at org.elasticsearch.script.groovy.GroovyScriptEngineService$GroovyScript.run(GroovyScriptEngineService.java:253)
    at org.elasticsearch.index.query.ScriptFilterParser$ScriptFilter$ScriptDocSet.matchDoc(ScriptFilterParser.java:190)
    at org.elasticsearch.common.lucene.docset.MatchDocIdSet$NoAcceptDocsIterator.nextDoc(MatchDocIdSet.java:96)
    at org.apache.lucene.search.ConstantScoreQuery$ConstantScorer.nextDoc(ConstantScoreQuery.java:257)
    at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreAll(Weight.java:192)
    at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:163)
    at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:35)
    at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:621)
    at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:309)
    at org.elasticsearch.common.lucene.Lucene.countWithEarlyTermination(Lucene.java:201)
    at org.elasticsearch.common.lucene.Lucene.countWithEarlyTermination(Lucene.java:189)
    at org.elasticsearch.common.lucene.Lucene.exists(Lucene.java:180)
    at org.elasticsearch.percolator.PercolatorService$4.doPercolate(PercolatorService.java:557)
    ... 7 more
```

**Comment by tlrx** [comment] 2015-01-12 12:47
Just reproduced this bug in an integration test. 

What I suspect to be the source of this issue: when a shard is recovered (right after startup for example), the percolate queries of the shard are parsed then loaded in memory. While being parsed, the script filter instantiates a `GroovyScript` for the `script doc['name'].value == 'b'` with a `SearchLookup` that comes from the `QueryParsedContext` used for parsing.

When a doc is percolated, the cached query is re-used and executed against an in-memory index but the script filter still use the same `GroovyScript` instance with the same `SearchLookup` instance. When executed concurrently, the `SearchLookup` instance is used by several `Collector` at the same time and matching doc are mixed.

The only solution I see is to keep in memory the string representation of percolate queries and parse them for every doc to percolate... but this will drastically impact performance.

**Comment by clintongormley** [comment] 2015-01-13 21:07
@martijnvg any suggestions?

**Comment by martijnvg** [comment] 2015-01-19 09:30
@clintongormley no, @tlrx explanation makes sense and this issue needs to be fixed. (each percolator query for example should have its own SearchLookup then the bug doesn't occur)

**Comment by martijnvg** [comment] 2015-01-29 12:15
To get back to this: I tried to fix this in such a way that each `script_filter` execution has its own SearchLookup, but unfortunately this doesn't fix the bug. 

What I did was in ScriptFilterParser.ScriptFilter#getDocIdSet(...) create a new SearchScript and SearchLookup, just to be sure that in the percolator each percolate request is working on its own data structures. This isn't how should fix this issue, but should prevent bug, however this didn't help. Now I'm not sure what else can cause this issue with script_filter in the percolator.

**Comment by mvdz** [comment] 2015-03-03 13:07
Hello @martijnvg, I've taken another look at this and implemented a workaround that appears to be the same as what you describe. It does seem to work for me, could you take a look at it?

https://github.com/mvdz/elasticsearch/commit/04707f7fd25bc545aae00e34d7a0e443096b8456

I understand this isn't the real fix, but hopefully it can lead to something better. Also it only works for Groovy scripts, while the issue also exists for other script languages. It's based on the 1.4 branch.

**Comment by martijnvg** [comment] 2015-03-04 23:08
thanks for sharing this @mvdz! I'll take a look at it, maybe I did something wrong.

**Comment by robth** [comment] 2015-05-19 08:12
Hi guys, any progress on this issue?

**Comment by clintongormley** [comment] 2015-05-25 11:29
Hi @robth - no progress yet. /cc @martijnvg

**Comment by martijnvg** [comment] 2015-05-26 15:21
@clintongormley @robth Fixing the script issue has become easier because of the merge of queries and filters on the Lucene level. I think we can properly fix this for 2.0. In 1.x the only fix I can come up with isn't a clean one.

**Comment by robth** [comment] 2015-05-27 07:07
@clintongormley @martijnvg Thanks for the feedback!

**Comment by tlrx** [comment] 2015-11-26 09:14
I took some more time to look at this issue again and also talked to @martijnvg about a potential fix.

This issue was easy to reproduce on 1.x versions of Elasticsearch where a `GroovyScript` instance is initialized by the percolator at parsing time with a given `SearchLookup` instance before being cached, making the percolating query reuse the same search lookup instance again and again while percolating documents, resulting in collisions.

I think this issue disappeared in 2.0 thanks to #10389 where `SearchScript` has been split into `SearchScript` and `LeafSearchScript` and the `GroovyScriptEngineService` modified so that `GroovyScript` now use a dedicated `LeafSearchLookup` instance at search time and do not get mixed when percolating documents concurrently.

@martijnvg I do now think that the fix you suggested is not necessary anymore... what do you think?

**Comment by martijnvg** [comment] 2015-11-26 10:51
Cool, that fixes the `doc[fieldx]` lookup, but I think the `_source.fieldx` still can fail? Looking at the code the `SourceLookup` is still being reused. 

Maybe instead of adding a lazy script query (which gets accesses to the SearchLookup at a later stage) we could do the same trick to SearchLookup as is done with DocLookup and FieldsLookup? (getting a dedicatedLeadDocLookup / LeafFieldLookup instances at percolate time)

**Comment by tlrx** [comment] 2015-11-26 11:01
@martijnvg I didn't catch this one but I guess you're talking about [this line](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/search/lookup/SearchLookup.java#L47) right?

I'll try your solution, thanks for the suggestion

**Comment by martijnvg** [comment] 2015-11-26 12:04
@tlrx yes, that exact line.

**Comment by clintongormley** [comment] 2016-11-26 16:27
@martijnvg Just tried this on 5.0 and the doc[] case works fine, but when trying to use `_source`, I get no matches:

```
PUT /test
{
  "mappings" : {
    "test" : {
      "properties" : {
        "name" : {
          "type" : "keyword"
        },
        "query": {
          "type": "percolator"
        }
      }
    }
  }
}

PUT /test/test/1
{
  "type": "test",
  "query": {
    "constant_score": {
      "filter": {
        "script": {
          "script": {"inline": "_source.name == \"a\"",
          "lang": "groovy"
          }
        }
      }
    }
  }
}

GET /test/test/_percolate
{ "doc": { "name": "a" } }
```

Is `_source` not available in groovy scripts in the percolator?

**Comment by martijnvg** [comment] 2017-06-28 14:10
Closing this as this is no longer an issue. 

@clintongormley The memory index doesn't store `_source` and that is the reason why no matches are returned. I'll document this as a limitation.

**Closed by martijnvg** 2017-06-28 14:10 UTC
Labels: :Percolator, :Scripting, adoptme, bug
