### ISSUE TITLE
The way to backup the searchable snapshot

### ISSUE THREAD

**Issue by kunisen** [elastic/elasticsearch#93972] opened 2023-02-21 11:37 UTC
### Description

On ESS for the cold/frozen tier, searchable snapshot data is stored in i.e. s3 bucket, and the reliability is guaranteed by CSP. Almost no data loss risk of natural disasters, however, if there’s a human error, data can be removed easily, i.e. wrongly configured ILM, or users deleting the data by accident. They may think we have a backup like normal indices, but actually, there’s not. (Searchable snapshot is also not configurable and manageable by SLM, so if it's accidentally deleted, there's no way to find the data back.)

Logically thinking, it's a SPOF. 

It would be great to have a logic to take the backup of the searchable snapshots on the current ESS, i.e. thru mirroring the buckets.

cc @romain-chanu @psanz-estc as we discussed this

**Comment by DaveCTurner** [comment] 2023-02-21 11:52
The manual describes [how to back up a snapshot repository](https://www.elastic.co/guide/en/elasticsearch/reference/current/snapshots-register-repository.html#snapshots-repository-backup) which includes searchable snapshots. We recognise that there is room for improvement in this area, and https://github.com/elastic/elasticsearch/issues/54944 tracks that work. I am closing this as a duplicate of that issue.

**Closed by DaveCTurner** 2023-02-21 11:52 UTC
Labels: >enhancement, :Distributed/Store, :Distributed/Distributed, Team:Distributed
