### ISSUE TITLE
[CI] Missing files for configuration ':distribution:classpath'

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#36084] opened 2018-11-29 21:14 UTC
Stange build failures in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+bwc-tests/99/consoleFull:

```
21:19:08  [5.6.14] FAILURE: Build failed with an exception.
21:19:08  [5.6.14] 
21:19:08  [5.6.14] * What went wrong:
21:19:08  [5.6.14] A problem occurred configuring project ':distribution'.
21:19:08  [5.6.14] > Could not resolve all files for configuration ':distribution:classpath'.
21:19:08  [5.6.14]    > Could not resolve org.apache.ant:ant:1.9.3.
21:19:08  [5.6.14]      Required by:
21:19:08  [5.6.14]          project :distribution > com.netflix.nebula:gradle-ospackage-plugin:4.7.1 > org.redline-rpm:redline:1.2.6
21:19:08  [5.6.14]       > Skipped due to earlier error
21:19:08  [5.6.14]    > Could not resolve org.apache.commons:commons-compress:1.8.
21:19:08  [5.6.14]      Required by:
21:19:08  [5.6.14]          project :distribution > com.netflix.nebula:gradle-ospackage-plugin:4.7.1 > org.redline-rpm:redline:1.2.6
21:19:08  [5.6.14]       > Skipped due to earlier error
21:19:08  [5.6.14]    > Could not resolve org.bouncycastle:bcpg-jdk15on:1.51.
21:19:08  [5.6.14]      Required by:
21:19:08  [5.6.14]          project :distribution > com.netflix.nebula:gradle-ospackage-plugin:4.7.1 > org.redline-rpm:redline:1.2.6
21:19:08  [5.6.14]       > Skipped due to earlier error
21:19:08  [5.6.14]    > Could not resolve org.apache.commons:commons-compress:1.8.
21:19:08  [5.6.14]      Required by:
21:19:08  [5.6.14]          project :distribution > com.netflix.nebula:gradle-ospackage-plugin:4.7.1 > org.vafer:jdeb:1.4
21:19:08  [5.6.14]       > Skipped due to earlier error
21:19:08  [5.6.14]    > Could not resolve org.apache.ant:ant:1.9.3.
21:19:08  [5.6.14]      Required by:
21:19:08  [5.6.14]          project :distribution > com.netflix.nebula:gradle-ospackage-plugin:4.7.1 > org.vafer:jdeb:1.4
21:19:08  [5.6.14]       > Skipped due to earlier error
21:19:08  [5.6.14]    > Could not resolve org.bouncycastle:bcpg-jdk15on:1.51.
21:19:08  [5.6.14]      Required by:
21:19:08  [5.6.14]          project :distribution > com.netflix.nebula:gradle-ospackage-plugin:4.7.1 > org.vafer:jdeb:1.4
21:19:08  [5.6.14]       > Skipped due to earlier error
21:19:08  [5.6.14] 
```

This seems to be while building the 5.6 version for bwc tests. Whats interesting is that although the build complains e.g. `Could not resolve org.apache.ant:ant:1.9.3`, a later version of ant is downloaded earlier:
```
21:18:53  [5.6.14] Download https://plugins.gradle.org/m2/org/apache/ant/ant-launcher/1.9.4/ant-launcher-1.9.4.jar
```

Not sure where the requirements for 1.9.3 are coming from.

**Comment by danielmitterdorfer** [comment] 2019-01-25 13:18
I did *not* find this exact build failure in build-stats (for reference: this was build-id `20181129193021-E8159029`) but all other failures with that pattern where due to transient network errors. Also, `ant-launcher` is different from `ant`. As this seems to be caused by a transient error, I'm closing it.

**Closed by danielmitterdorfer** 2019-01-25 13:18 UTC
Labels: :Core/Infra/Build, >test-failure
