### ISSUE TITLE
Nondeterministic behavior of composite aggregation combined with nested aggregation(s)

### ISSUE THREAD

**Issue by elwerene** [elastic/elasticsearch#45006] opened 2019-07-30 14:17 UTC
**Elasticsearch version** (`bin/elasticsearch --version`):

6.2.4

**Plugins installed**:

None

**JVM version** (`java -version`): 

openjdk version "1.8.0_161"
OpenJDK Runtime Environment (build 1.8.0_161-b14)
OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):

Linux 97e45403b320 5.1.18-300.fc30.x86_64 #1 SMP Mon Jul 15 15:42:34 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

If I combine a composite aggregation with some nested aggregations, I get nondeterministic results.

I made an example request as small as possible to explain the problem. With a terms aggregation I get the desired results, with the composite aggregation I didn't in this run (On some instances I got a result, as I said, it is not deterministic. Wild guess: it has something to do with sharding and nested objects not being collected).

I removed some data and replaced it with the string `REMOVED`.

***Query with composite aggregation***
```
{
  "query": {
    "term": {
      "_id": "order:016449c2-76da-4410-8411-97819b09d565"
    }
  },
  "size": 1,
  "aggregations": {
    "report": {
      "composite": {
        "size": 10000,
        "sources": [
          {
            "created": {
              "date_histogram": {
                "field": "created",
                "interval": "week"
              }
            }
          }
        ]
      },
      "aggregations": {
        "report": {
          "nested": {
            "path": "commission"
          },
          "aggregations": {
            "report": {
              "terms": {
                "field": "commission.user",
                "order": {
                  "_term": "asc"
                },
                "size": 2147483647
              },
              "aggregations": {
                "commission.total": {
                  "sum": {
                    "field": "commission.total"
                  }
                },
                "commission.commission": {
                  "sum": {
                    "field": "commission.commission"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

****Response:****
```
{
  "took": 0,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 1,
    "hits": [
      {
        "_index": "test",
        "_type": "orders",
        "_id": "order:016449c2-76da-4410-8411-97819b09d565",
        "_score": 1,
        "_source": {
          "commission": [
            {
              "commission": 0.144,
              "total": 2.4,
              "user": "42"
            },
            {
              "commission": 0.336,
              "total": 2.4,
              "user": "42"
            }
          ],
          "created": 1564412914949
        }
      }
    ]
  },
  "aggregations": {
    "report": {
      "buckets": [
        {
          "key": {
            "created": 1564358400000
          },
          "doc_count": 1,
          "report": {
            "doc_count": 0,
            "report": {
              "doc_count_error_upper_bound": 0,
              "sum_other_doc_count": 0,
              "buckets": []
            }
          }
        }
      ]
    }
  }
}
```

***Request with terms aggregation***
```
{
  "query": {
    "term": {
      "_id": "order:016449c2-76da-4410-8411-97819b09d565"
    }
  },
  "size": 1,
  "aggregations": {
    "report": {
      "date_histogram": {
        "field": "created",
        "order": {
          "_key": "asc"
        },
        "interval": "week",
        "min_doc_count": 0
      },
      "aggregations": {
        "report": {
          "nested": {
            "path": "commission"
          },
          "aggregations": {
            "report": {
              "terms": {
                "field": "commission.user",
                "order": {
                  "_term": "asc"
                },
                "size": 2147483647
              },
              "aggregations": {
                "commission.total": {
                  "sum": {
                    "field": "commission.total"
                  }
                },
                "commission.commission": {
                  "sum": {
                    "field": "commission.commission"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

****Response****
```
{
  "took": 0,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 1,
    "hits": [
      {
        "_index": "test",
        "_type": "orders",
        "_id": "order:016449c2-76da-4410-8411-97819b09d565",
        "_score": 1,
        "_source": {
          "commission": [
            {
              "commission": 0.144,
              "total": 2.4,
              "user": "42"
            },
            {
              "commission": 0.336,
              "total": 2.4,
              "user": "42"
            }
          ],
          "created": 1564412914949
        }
      }
    ]
  },
  "aggregations": {
    "report": {
      "buckets": [
        {
          "key_as_string": "1564358400000",
          "key": 1564358400000,
          "doc_count": 1,
          "report": {
            "doc_count": 2,
            "report": {
              "doc_count_error_upper_bound": 0,
              "sum_other_doc_count": 0,
              "buckets": [
                {
                  "key": "42",
                  "doc_count": 2,
                  "commission.total": {
                    "value": 4.800000190734863
                  },
                  "commission.commission": {
                    "value": 0.47999998927116394
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
```

***Index Metadata***
```
{
  "state": "open",
  "settings": {
    "index": {
      "creation_date": "1564492722237",
      "number_of_shards": "5",
      "number_of_replicas": "1",
      "uuid": "REMOVED",
      "version": {
        "created": "6020499"
      },
      "provided_name": "test"
    }
  },
  "mappings": {
    "orders": {
      "dynamic": "strict",
      "properties": {
        "created": {
          "format": "epoch_millis",
          "type": "date"
        },
        "commission": {
          "type": "nested",
          "properties": {
            "total": {
              "type": "float"
            },
            "commission": {
              "type": "float"
            },
            "user": {
              "type": "keyword"
            }
          }
        }
      }
    }
  },
  "primary_terms": {
    "0": 1,
    "1": 1,
    "2": 1,
    "3": 1,
    "4": 1
  },
  "in_sync_allocations": {
    "0": [
      "REMOVED"
    ],
    "1": [
      "REMOVED"
    ],
    "2": [
      "REMOVED"
    ],
    "3": [
      "REMOVED"
    ],
    "4": [
      "REMOVED"
    ]
  }
}
```

**Comment by jimczi** [comment] 2019-07-30 20:50
I can not find the issue that caused this but I tried the same recreation with `6.8.1` and things work as expected. There was a lot of fixes and changes in the `composite` aggregation between `6.2` and `6.8` so you'll need to upgrade to a more recent version in order to get a fix for this bug. Since the issue is resolved in the latest versions I am going to close this issue, don't hesitate to reopen if you can reproduce on a more recent version.

**Closed by jimczi** 2019-07-30 20:50 UTC
Labels: :Analytics/Aggregations

**Comment by elwerene** [comment] 2019-07-31 09:19
I checked Elasticsearch 6.8.1, I can confirm it is fixed in this version. Thank you!
