### ISSUE TITLE
Low-level REST client status error

### ISSUE THREAD

**Issue by weizijun** [elastic/elasticsearch#42061] opened 2019-05-10 07:57 UTC
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):
6.6.1
**Plugins installed**: []

**JVM version** (`java -version`):
1.8

**OS version** (`uname -a` if on a Unix-like system):
3.10.0-514.16.1.es01.x86_64 #1 SMP Wed Oct 17 23:14:35 CST 2018 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
Low-level REST client accidentally casue exception:
```
java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
	at org.apache.http.util.Asserts.check(Asserts.java:46)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.ensureRunning(CloseableHttpAsyncClientBase.java:90)
	at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:123)
	at org.elasticsearch.client.RestClient.performRequestAsync(RestClient.java:524)
	at org.elasticsearch.client.RestClient.performRequestAsyncNoCatch(RestClient.java:501)
	at org.elasticsearch.client.RestClient.performRequestAsync(RestClient.java:232)
	at com.didichuxing.datachannel.arius.elasticsearch.client.ESClient.doExecute(ESClient.java:133)
```

after this excepiton appears, every request exception, because of the STOPPED status.
This case happens by chance. 
Can RestClient add a method to check if client is running? or reset  client internal

**Comment by javanna** [comment] 2019-05-10 09:49
This looks like a duplicate of #39946.

**Closed by javanna** 2019-05-10 09:49 UTC

**Comment by weizijun** [comment] 2019-05-10 14:49
> This looks like a duplicate of #39946.

yes, thanks! I will follow the #39946.
