### ISSUE TITLE
FieldValueFactorFunction should use 'missing' when field does't exist in mapping

### ISSUE THREAD

**Issue by edudar** [elastic/elasticsearch#16338] opened 2016-02-01 07:51 UTC
It's common case for continuous deployment to change elasticsearch's client and index independently. This leads to the case when `fieldValueFactorFunction` is added to the client but index is not rebuilt yet. I use `missing` property. Unfortunately [FieldValueFactorFunctionParser](https://github.com/elastic/elasticsearch/blob/528f6481eaadd2a0585dc6731a94d7a024b8ce29/src/main/java/org/elasticsearch/index/query/functionscore/fieldvaluefactor/FieldValueFactorFunctionParser.java#L89) demands to have a field in a mapping, it throws exception otherwise. This means we can't deploy an client before index is updated despite having `missing` property set. The suggestion here is to look as `missing` in case of field in the document or mapping are missing.

**Comment by clintongormley** [comment] 2016-02-02 14:03
Duplicate of #12016

**Closed by clintongormley** 2016-02-02 14:03 UTC
