### ISSUE TITLE
ESQL: Enrich performance degradation twice in last month

### ISSUE THREAD

**Issue by craigtaverner** [elastic/elasticsearch#102625] opened 2023-11-27 09:38 UTC
Twice in the last month the performance of `ENRICH` command has dropped dramatically:

* On the 15th November, single enrich dropped from 50ms to 85ms
* On the 24th November, it dropped further to 100ms

<img width="946" alt="Screenshot 2023-11-27 at 10 35 03" src="https://github.com/elastic/elasticsearch/assets/114451/4fa5e346-5d93-47d0-9c49-7857ad507f13">

See https://elasticsearch-benchmarks.elastic.co/#tracks/esql/nightly/default/30d

On the 15th the build run was `2128866bf1022046877ea255016dfa0feccb0c30`, and on the 24th it was `b12b38ca46fbc50a664d7389d6ff417e9485d8e7`.

**Comment by craigtaverner** [comment] 2023-11-27 09:55
I noticed this PR merged on the 15th shortly before the build that includes the first regression: https://github.com/elastic/elasticsearch/pull/102190

**Comment by dnhatn** [comment] 2023-11-29 16:27
Thanks @craigtaverner. I will take a look this week.

**Comment by dnhatn** [comment] 2023-12-01 07:00
I think I've identified the cause of this issue. The overhead of the circuit breaker is quite significant during the construction of a Block.Builder with many entries. We need to read/write several atomic longs when reserving memory from a breaker. I have a working solution that reserves an extra 4KB from the breaker, and gradually use that amount when adding more entries. Once we run out the reserved bytes, we reserve another extra 4KB. This solution has restored the previous performance levels we had before integrating with the BlockFactory in https://github.com/elastic/elasticsearch/pull/102190. I also think this approach not only reduces the latency of enrich queries but also improves the performance of most queries. I'm currently thinking how to integrate such breaker with minimal changes. /cc @nik9000 @ChrisHegarty

**Comment by ChrisHegarty** [comment] 2023-12-01 11:44
Good sleuthing @dnhatn! This is exactly what I feared with the addition of the breaker - more specifically the direct use of the request breaker. What you describe above is a per-driver / thread-local allocation breaker, right? Which we envisioned, e.g. https://github.com/elastic/elasticsearch/issues/99173 ?

**Comment by nik9000** [comment] 2023-12-01 15:25
Yeah, your solution sounds a lot like the per-request breaker we'd talked about. IIRC the trick was when you move the blocks out of the current thread we didn't know what to do. If you know then perfect!

**Comment by dnhatn** [comment] 2023-12-06 19:17
Fixed in https://github.com/elastic/elasticsearch/pull/102901 and https://github.com/elastic/elasticsearch/pull/102902

**Closed by dnhatn** 2023-12-06 19:17 UTC
Labels: >bug, Team:QL, :Query Languages/ES|QL
