### ISSUE TITLE
Mistake in documentaion regarding maximum level of QuadPrefixTree(29 not 50)

### ISSUE THREAD

**Issue by chintan-shah-25** [elastic/elasticsearch#21191] opened 2016-10-31 05:19 UTC
I was looking at [this](http://stackoverflow.com/questions/40303895/elasticsearch-2-3-geo-shape-type-mapping) stackoverflow question regarding geo shape mapping. (ES version 2.3)

[Documentation](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/geo-shape.html#prefix-trees) says 

> The maximum amount of levels for the quad trees in Elasticsearch is 50.

but according to [source code](https://github.com/elastic/elasticsearch/blob/3f77eacab14e70da2d7ee4720f55552f4f4242d9/core/src/main/java/org/elasticsearch/index/mapper/GeoShapeFieldMapper.java#L267) quadtree maps to lucene [PackedQuadPrefixTree](https://lucene.apache.org/core/6_2_1/spatial-extras/org/apache/lucene/spatial/prefix/tree/PackedQuadPrefixTree.html) which says max levels is 29 and not 50. The code below fails saying "maxLevels of 36 exceeds limit of 29"
```
PUT test_index

PUT test_index/_mapping/test_type
{
  "properties": {
    "text": {
      "type": "geo_shape",
      "tree": "quadtree",
      "precision": "1mm"
    }
  }
} 
```

Also there is no documentation regarding 'legacyquadtree' and if you give very high value of tree_levels like below, it throws OOM rather than saying max allowed level is 50

```
PUT test_index/_mapping/test_type
{
  "properties": {
    "text": {
      "type": "geo_shape",
      "tree": "legacyquadtree",
      "tree_levels": "54354552"
    }
  }
}
```

**Comment by nik9000** [comment] 2016-10-31 14:18
I've assigned this to @nknize because he knows this code well and can figure out what to do more quickly than I can.

**Comment by Sue-Gallagher** [comment] 2018-04-26 19:16
Upon further investigation, I've determined that this low hanging fruit isn't quite ripe. The table on https://www.elastic.co/guide/en/elasticsearch/reference/6.2/geo-shape.html is wrong. 
1. Precision is defined as a number plus a value, but the default column (far right) shows only a value, no number. I suspect that the true default is 50m. Please confirm.
2. tree-levels description clearly states that the default is the default for the chosen prefix tree, but the default column shows 50m. I suspect that the default should be "various"; please confirm.
and then...
3. We say that tree-level is the default of the particular prefix tree chosen, but in the descriptions of the prefix trees, we give the maximum value but not the default. If the default is some number below maximum, please provide.

**Comment by nknize** [comment] 2018-04-30 17:43
> 1. Precision is defined as a number plus a value, but the default column (far right) shows only a value, no number. I suspect that the true default is 50m. Please confirm.

Yes. The default is 50m



> 2. I suspect that the default should be "various"

Confirmed



> 3. If the default is some number below maximum, please provide.

GeoHashPrefixTree:  Default Level == 9
QuadPrefixTree:  Default Level == 21

**Closed** 2018-05-03 16:48 UTC
Labels: :Search/Geo, >docs, low hanging fruit
