### ISSUE TITLE
Nested geo_point object cannot be sorted by geo_distance (possible regression)

### ISSUE THREAD

**Issue by nikos** [elastic/elasticsearch#23442] opened 2017-03-01 21:53 UTC
**Elasticsearch version**: 5.2.1
**Plugins installed**: -
**JVM version**: 1.8.0_121
**OS version**: Mac OSX 10.11.6

**Description of the problem including expected versus actual behavior**:

When sorting with the help of _geo_distance the response should contain a float with the distance, but does list distances as "Infinity" for the case of nested objects. It works when the location is embedded as a simple inner object (without specifying place as type "nested").

**Steps to reproduce**:

```
PUT venues
{
  "mappings": {
    "sample": {
      "properties": {
        "body": {
          "type": "text"
        },
        "place": {
          "type": "nested",
          "properties": {
            "name": {
              "type": "text"
            },
            "location": {
              "type": "geo_point"
            }
          }
        }
      }
    }
  }
}


PUT venues/sample/1
{
  "name": "Venue #1",
  "place": {
    "name": "Irgendwo",
    "location": {
      "lat": 53.58121,
      "lon": 9.99121
    }
  }
}

PUT venues/sample/2
{
  "name": "Venue #2",
  "place": {
    "name": "Anders",
    "location": {
      "lat": 53.62171,
      "lon": 10.01231
    }
  }
}

GET venues/_search
{
  "query": {
    "match_all": {}
  },
  "sort": [{
		"_geo_distance": {
			"place.location": [53.551086, 9.993682]
		}
	}]
}
```

**Describe the feature**:

I would expect that the sorting behaves with the same sort criteria no matter if the sub-document is an inner object or a nested object.

This problem might be a regression as described in the thread [geo_distance sorting on geo_point in nested document](http://elasticsearch-users.115913.n3.nabble.com/geo-distance-sorting-on-geo-point-in-nested-document-td4035188.html) by Loren in May 2013 and his [fix](https://github.com/elasticsearch/elasticsearch/commit/db421742f71e40a0b132e20ac6508dfac5c8ab9c).

**Comment by nikos** [comment] 2017-03-01 22:07
After studying the related integration test cases, I was able to get the nested case working when specifying nested_path and sort order as follows:
```
  "sort": [{
		"_geo_distance": {
			"place.location": [53.551086, 9.993682],
			"nested_path": "place",
		  "order": "asc"
		}
	}]
```
Might be worth adding to the docs?

**Comment by martijnvg** [comment] 2017-03-02 07:43
Nested sorting is [documented](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/search-request-sort.html#nested-sorting), but I can understand the confusion when sorting and your result not being sorted. I think we should add validation here, so that it is clear that nested sorting is needed.

**Comment by wchaparro** [comment] 2023-04-19 13:54
Close as duplicate of #29991

**Closed** 2023-04-19 13:54 UTC
Labels: >enhancement, stalled, :Analytics/Geo, Team:Analytics
