### ISSUE TITLE
Mis-reported self-intersection

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#27832] opened 2017-12-15 08:36 UTC
**Elasticsearch version**
```
$ elasticsearch-6.1.0/bin/elasticsearch --version
Version: 6.1.0, Build: c0c1ba0/2017-12-12T12:32:54.550Z, JVM: 1.8.0_144
```

**Plugins installed**: []

**JVM version**
```
$ java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

**OS version**
```
$ uname -a
Darwin Davids-MacBook-Pro.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
```

The following sequence:

```
DELETE /geotest

PUT /geotest
{
  "mappings": {
    "geotest": {
      "properties": {
        "geometry": {
          "type": "geo_shape",
          "tree": "quadtree",
          "precision": "100m"
        }
      }
    }
  },
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 0
  }
}

POST /geotest/geotest
{
  "geometry": {
    "coordinates": [
      [
        [
          -29,
          -32
        ],
        [
          91,
          -45
        ],
        [
          -90,
          -45
        ],
        [
          -25,
          -31
        ],
        [
          -29,
          -32
        ]
      ]
    ],
    "type": "Polygon"
  }
}
```

Yields this error:

```
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "failed to parse [geometry]"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "failed to parse [geometry]",
    "caused_by": {
      "type": "invalid_shape_exception",
      "reason": "Self-intersection at or near point (-29.858846918489064, -32.046520874751494, NaN)"
    }
  },
  "status": 400
}
```

The shape in question apparently looks like this:

<img width="584" alt="screen shot 2017-12-15 at 08 35 00" src="https://user-images.githubusercontent.com/5058284/34033640-e5fc1002-e172-11e7-8fc0-2d91cb2339ef.png">

I have a suspicion this is something to do with the date-line, because changing the `91` to `90` does not yield this error.

**Comment by DaveCTurner** [comment] 2017-12-19 11:38
For future reference, I found this looking at https://github.com/dstl/baleen/issues/3 and https://github.com/elastic/elasticsearch/issues/17407 seems related.

**Comment by DaveCTurner** [comment] 2017-12-20 08:27
Ah, ok, I had my orientations mixed up after all, as @colings86 correctly guessed. This polygon's orientation is clockwise but it should be anticlockwise. We accept both for polygons that cross ≤180° of longitude but for wider polygons we assume that the incorrect orientation and excessive width is due to the date line:

https://github.com/elastic/elasticsearch/blob/e6da564eb15945289c1fd0d29d9cd04e3090d51b/core/src/main/java/org/elasticsearch/common/geo/builders/PolygonBuilder.java#L654-L660

We then try and "fix" it by putting the western hemisphere on the east of the eastern hemisphere:

https://github.com/elastic/elasticsearch/blob/e6da564eb15945289c1fd0d29d9cd04e3090d51b/core/src/main/java/org/elasticsearch/common/geo/builders/PolygonBuilder.java#L760-L766

The "fixed" shape does indeed self-intersect, and if I correctly orient the input shape then it is accepted.

@nknize, how would you feel about deprecating this leniency-by-default? The Antarctica outlines in the linked issues are clockwise too, and span > 180° of longitude, so I guess they get "fixed" in the same way. The resulting message about a self-intersection or a duplicated point is mysterious because it's talking about a geometry that's quite different from the one the user sees.

**Comment by DaveCTurner** [comment] 2017-12-20 09:22
Note that https://github.com/dstl/baleen/pull/39/files was a change that a user made to simplify an outline of Antarctica into one that ES accepts, but it still looks clockwise to me so I think the indexed shape is "fixed" as above, and therefore doesn't match the shape that they wanted to index.

**Comment by imotov** [comment] 2018-12-13 16:03
This looks like duplicate of #26286. Closing.

**Closed by imotov** 2018-12-13 16:03 UTC
Labels: :Analytics/Geo, >bug, v6.1.0
