### ISSUE TITLE
Percolator performance issue

### ISSUE THREAD

**Issue by kaliseo** [elastic/elasticsearch#9337] opened 2015-01-16 17:17 UTC
Hi !

I'm working on a large analytics data cluster, and user percolator query to compute customer profile. 

Since few days, i was experiencing issues with garbage collector consuming large CPU and crash requests. I made lot of tests, changing for oracle JVM, changing for G1GC, but nothing worked.

Si i begun to check the hot threads API and saw percolator were using large amount of CPU.

Just desactivated the percolator query (with 4 percolator query in index), and here is the result : 
![screenshot012](https://cloud.githubusercontent.com/assets/1506320/5780568/d95b1d60-9dab-11e4-9f9e-9b8efbe0a248.png)

Since i desactivated client.percolate in node.js code, CPU are low used.

Does anyone know why percolator query is killing GC performances ?

Thanks a lot for your help !

**Comment by kaliseo** [comment] 2015-01-18 18:26
Nobody ?

**Comment by kaliseo** [comment] 2015-01-18 18:45
Seems this part of documentation can explain the problem : 

When indexing a document that contains a query in an index and the .percolator type the query part of the documents gets parsed into a Lucene query and is kept in memory until that percolator document is removed or the index containing the .percolator type get removed. So all the active percolator queries are kept in memory.

But.. why does ES keep all queries in memory ? oO

**Comment by martijnvg** [comment] 2015-01-19 09:04
@kaliseo The reason is for speed. If for each percolator request the all the queries to be processed needed to be parsed it would take much longer to execute the percolate request.

So you're seeing performance issues and gc related issues with just 4 percolator queries in the entire cluster? How much heap space have you allocated to ES?

**Comment by clintongormley** [comment] 2015-01-19 19:37
@kaliseo Also:

* is swap disabled, or do you have `mlockall` enabled
* are you using heavy wildcard, fuzzy or regexp queries?

**Comment by kaliseo** [comment] 2015-01-24 10:04
Hi there,
Yes, 4 queries indexed in .percolator.

32GB heap size (machine is 64Gb RAM available)
mlockall is disabled

I'm not using widlcard or regexp. only term queries or script (type size()
of array).

On documentation, i saw all percolate queries are kept in memory. I think
it's the problem, cause i'm making percolate query with 1 or 2 million
documents per days.

Thierry @ Gmail

2015-01-19 20:38 GMT+01:00 Clinton Gormley <notifications@github.com>:

**Comment by martijnvg** [comment] 2015-01-25 14:23
If you just have 4 percolator queries indexed then the fact that the queries are kept in memory shouldn't be the issue. (unless those queries are very large)

What kind of documents are you indexing? Do you also percolate documents that are large? (lets say more than 100kb) Also have you changed the settings of the percolator threadpool?

**Comment by kaliseo** [comment] 2015-01-25 19:24
Hi,

I did not change percolator settings. Documents are much more less  than
100kb (mostly 200 / 300 bytes).

As i can see in documentation, percolator queries are kept in memory, but
document sent to percolate are kept in memory too (i don't realy understand
why) :
"*At percolate time the document specified in the request gets parsed into
a Lucene document and is stored in a in-memory Lucene index*. This
in-memory index can just hold this one document and it is optimized for
that. Then all the queries that are registered to the index that the
percolate request is targeted for are going to be executed on this single
document in-memory index. This happens on each shard the percolate request
need to execute."

It's why i think all documents sent to percolator are breaking down the
garbage collector performances.



Thierry @ Gmail

2015-01-25 15:23 GMT+01:00 Martijn van Groningen <notifications@github.com>:

**Comment by martijnvg** [comment] 2015-01-26 08:25
Yes, the document being percolated is indexed into an in-memory index,
otherwise we can't evaluate if the percolator queries match with the
document being percolated. The reason this is an in-memory index is because
the document being percolated between percolate requests is likely going to
be different all the time, also a single document is going to be percolated
and in that case the in-memory index is the best choice.

With what ES version are you running into these gc issues with the
percolator?

On 25 January 2015 at 20:24, kaliseo <notifications@github.com> wrote:

> Hi,
>
> I did not change percolator settings. Documents are much more less than
> 100kb (mostly 200 / 300 bytes).
>
> As i can see in documentation, percolator queries are kept in memory, but
> document sent to percolate are kept in memory too (i don't realy
> understand
> why) :
> "*At percolate time the document specified in the request gets parsed into
> a Lucene document and is stored in a in-memory Lucene index*. This
> in-memory index can just hold this one document and it is optimized for
> that. Then all the queries that are registered to the index that the
> percolate request is targeted for are going to be executed on this single
> document in-memory index. This happens on each shard the percolate request
> need to execute."
>
> It's why i think all documents sent to percolator are breaking down the
> garbage collector performances.
>
>
>
> Thierry @ Gmail
>
> 2015-01-25 15:23 GMT+01:00 Martijn van Groningen <notifications@github.com>:
>
>
> > If you just have 4 percolator queries indexed then the fact that the
> > queries are kept in memory shouldn't be the issue. (unless those queries
> > are very large)
> >
> > What kind of documents are you indexing? Do you also percolate documents
> > that are large? (lets say more than 100kb) Also have you changed the
> > settings of the percolator threadpool?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/elasticsearch/elasticsearch/issues/9337#issuecomment-71374912>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elasticsearch/elasticsearch/issues/9337#issuecomment-71387379>
> .
>



-- 
Met vriendelijke groet,

Martijn van Groningen

**Comment by kaliseo** [comment] 2015-01-27 09:20
I'm using :
Version: 1.4.2, Build: 927caff/2014-12-16T14:11:12Z, JVM: 1.8.0_31

Also tested with JVM 1.7.

Thierry @ Gmail

2015-01-26 9:26 GMT+01:00 Martijn van Groningen <notifications@github.com>:

> Yes, the document being percolated is indexed into an in-memory index,
> otherwise we can't evaluate if the percolator queries match with the
> document being percolated. The reason this is an in-memory index is
> because
> the document being percolated between percolate requests is likely going
> to
> be different all the time, also a single document is going to be
> percolated
> and in that case the in-memory index is the best choice.
>
> With what ES version are you running into these gc issues with the
> percolator?
>

**Comment by martijnvg** [comment] 2015-01-30 13:52
@kaliseo Are you percolating documents that have a nested mapping? Also is it possible to share a reproduction of the issues you're experiencing?

**Comment by kaliseo** [comment] 2015-01-31 08:07
Yes ! I'm using nested document to percolate.

What do you expect about sharing the reproduction ? Giving access to the
cluster ?

Thierry @ Gmail

2015-01-30 14:53 GMT+01:00 Martijn van Groningen <notifications@github.com>:

**Comment by martijnvg** [comment] 2015-01-31 09:39
Sharing the steps as curl commands or code snippets (native Java client or
a rest client) that lead up to the problem and sharing a jvm heap dump will
help too. It is best to share this privately by sending the download
details to my email adres.

On 31 January 2015 at 09:07, kaliseo <notifications@github.com> wrote:

> Yes ! I'm using nested document to percolate.
>
> What do you expect about sharing the reproduction ? Giving access to the
> cluster ?
>
> Thierry @ Gmail
>
> 2015-01-30 14:53 GMT+01:00 Martijn van Groningen <notifications@github.com>:
>
>
> > @kaliseo <https://github.com/kaliseo> Are you percolating documents
> that
> > have a nested mapping? Also is it possible to share a reproduction of
> the
> > issues you're experiencing?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/elasticsearch/elasticsearch/issues/9337#issuecomment-72203191>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elasticsearch/elasticsearch/issues/9337#issuecomment-72309060>
> .
>



-- 
Met vriendelijke groet,

Martijn van Groningen

**Comment by clintongormley** [comment] 2015-02-28 05:23
@kaliseo @martijnvg any progress on this ticket?

**Comment by kaliseo** [comment] 2015-02-28 09:59
Hi there,

No nothing. Did note made any other tests, i recoded programmaticaly my
system with nodejs

Thierry @ Gmail

2015-02-28 6:23 GMT+01:00 Clinton Gormley <notifications@github.com>:

**Comment by clintongormley** [comment] 2015-04-26 19:40
No more info here - closing

**Closed by clintongormley** 2015-04-26 19:40 UTC
Labels: feedback_needed
