### ISSUE TITLE
Error in per bucket doc_count_error_upper_bound for Term Aggregation ?

### ISSUE THREAD

**Issue by Nishikant-Dev** [elastic/elasticsearch#84787] opened 2022-03-09 07:06 UTC
I have raised this on [Elastic Forum](https://discuss.elastic.co/), and got the response from ES Team member that I should raise this as an issue, Link to question : [Original Question](https://discuss.elastic.co/t/error-in-per-bucket-doc-count-error-upper-bound-for-term-aggregation/294249)

ES Version 7.10.2

Below configuration for Elasticsearch:

```
1 Cluster
1 Node
1 Index
3 Shards (1 Replica shard for each primary, but in UNASSIGNED state as there is only 1 node).
```

I have indexed document and those are spread across 3 Shards(Shard-0, Shard-1,Shard-2).

Term Aggregation I am trying:

```
POST myIndex/_search
{
  "query": {"match_all": {}}, 
  "size":0,
  "aggs": {
    "products": {
      "terms": {
        "field": "BillToID",
        "size": 10,
        "shard_size": 11,
        "show_term_doc_count_error": true
      }
    }
  }
}
```

Response :-

```
"aggregations" : {
    "products" : {
      "doc_count_error_upper_bound" : 7,
      "sum_other_doc_count" : 12,
      "buckets" : [
        {
          "key" : "ProductA",
          "doc_count" : 100,
          "doc_count_error_upper_bound" : 6
        },
        {
          "key" : "ProductC",
          "doc_count" : 54,
          "doc_count_error_upper_bound" : 6
        },
        {
          "key" : "ProductZ",
          "doc_count" : 52,
          "doc_count_error_upper_bound" : 6
        },
        {
          "key" : "ProductG",
          "doc_count" : 47,
          "doc_count_error_upper_bound" : 6
        },
        {
          "key" : "ProductH",
          "doc_count" : 44,
          "doc_count_error_upper_bound" : 6
        },
        {
          "key" : "ProductB",
          "doc_count" : 43,
          "doc_count_error_upper_bound" : 6
        },
        {
          "key" : "ProductE",
          "doc_count" : 31,
          "doc_count_error_upper_bound" : 6
        },
        {
          "key" : "ProductF",
          "doc_count" : 19,
          "doc_count_error_upper_bound" : 6
        },
        {
          "key" : "ProductI",
          "doc_count" : 11,
          "doc_count_error_upper_bound" : 6
        },
        {
          "key" : "ProductJ",
          "doc_count" : 9,
          "doc_count_error_upper_bound" : 6
        }
      ]
    }
  }
```

From Definition in Docs Of Per Bucket doc_count_error_upper_bound:

> This is calculated by summing the document counts for the last term returned by all shards which did not return the term.

Problem : But When I checked I can see ProductA has been returned by each shard, so why does it shows "doc_count_error_upper_bound" : 6 for ProductA?

> Can you describe how you verified what was returned from each shard?

In total I indexed 422 documents into my Index.
then to check how much document of a particular unique term(ex:ProductA) does a shard hold, I used below query :--

```

POST /myIndex/_search?preference=_shards:0
{
  "query": {
    "match": {
      "BillToID": "ProductA"
    }
  }
}
```

If the values of totalHits > 0 , means shard-0 does hold document for ProductA, and how many documents it holds can be identified by totalHits.
I did this for every unique terms(like ProductA, ProductB as I know all of them beforehand) and on every shard.

> i.e ProductA count on -> Shard-0(35), Shard-1(33), Shard-2(32)

Now, As per doc,

> Each shard prepares a Priority Queue of Shard_Size with documents in descending order count.

As ProductA documets have highest documets count in each shard, so it must have been included in Priority Queue of every shard, when co-ordinator node finally prepared the global sorted list, ProductA will be on top of list as it has highest count.

Now for Per Bucket doc_count_error_upper_bound 

> This is calculated by summing the document counts for the last term returned by all shards which did not return the term.

But by above checks, it has been returned from all shards, then how come doc_count_error_upper_bound = 6 is showing for ProductA bucket?

**Comment by not-napoleon** [comment] 2024-01-05 18:04
So, as the field describes, that value is an error upper bound, not an exact measurement.  It is indeed possible, and even likely, for the actual error to be below that threshold. I'd need more of a reproduction example (i.e. the full data and queries) to explain exactly where that specific number is coming from in this case (and also, I'm not sure the heuristic hasn't changed since 7.10), but in general it is expected behavior that the error upper bound be higher than the actual error.

Closing as not an issue.

**Closed by not-napoleon** 2024-01-05 18:04 UTC
Labels: :Analytics/Aggregations, Team:Analytics
