### ISSUE TITLE
IllegalArgumentException: can not write type Enum in Java client for terms query

### ISSUE THREAD

**Issue by mraliagha** [elastic/elasticsearch#73547] opened 2021-05-31 06:57 UTC
**Elasticsearch version**: 7.12.1

**Description of the problem including expected versus actual behavior**:
Prior to Elasticsearch 7.12.0 using terms query with an enum value was working without any issues. After upgrading java Elasticsearch client from 7.10.0 to 7.12.1 the following exception has been thrown when terms query is used for an Enum value. The same code is tested for previous versions and it works without any issues.

```
BoolQueryBuilder query = QueryBuilders.boolQuery();
query.mustNot(QueryBuilders.termsQuery("foo", Thing.BAR));

public Enum Thing{
   FOO, BAR;

  @Override 
  @JsonValue
  public String toString() {
      return name().toLowerCase();
  }
}
```

**Exception:**
```
Caused by: java.lang.IllegalArgumentException: can not write type [class com.example.Thing]
	at org.elasticsearch.common.io.stream.StreamOutput.writeGenericValue(StreamOutput.java:845)
	at org.elasticsearch.common.io.stream.StreamOutput.lambda$static$12(StreamOutput.java:700)
	at org.elasticsearch.common.io.stream.StreamOutput.writeGenericValue(StreamOutput.java:843)
	at org.elasticsearch.index.query.TermsQueryBuilder$Values.serialize(TermsQueryBuilder.java:434)
	at org.elasticsearch.index.query.TermsQueryBuilder$BinaryValues.<init>(TermsQueryBuilder.java:493)
	at org.elasticsearch.index.query.TermsQueryBuilder$BinaryValues.<init>(TermsQueryBuilder.java:483)
	at org.elasticsearch.index.query.TermsQueryBuilder.<init>(TermsQueryBuilder.java:161)
	at org.elasticsearch.index.query.TermsQueryBuilder.<init>(TermsQueryBuilder.java:141)
	at org.elasticsearch.index.query.QueryBuilders.termsQuery(QueryBuilders.java:568)
```

Prior to 7.12.0, the same code snippet works without any issues. The workaround is to use .toString() wherever an Enum value has been used.

After exploring what could have gone wrong in the version 7.12.1 client, we realised that [this PR](https://github.com/elastic/elasticsearch/pull/67223) has created the mentioned side effect.  The issue seems to be related to line 168 of TermsQueryBuilder.java.

**Comment by cbuescher** [comment] 2021-05-31 08:10
I believe this is a duplicate of https://github.com/elastic/elasticsearch/issues/71388. The workaround is to use the string representation of the enum. There is an open issue to make the query constructor safer to use with general Object https://github.com/elastic/elasticsearch/issues/71972. Please let me know if the workaround works for you, in this case I would like to close this issue.

**Comment by mraliagha** [comment] 2021-05-31 08:43
> I believe this is a duplicate of #71388. The workaround is to use the string representation of the enum. There is an open issue to make the query constructor safer to use with general Object #71972. Please let me know if the workaround works for you, in this case, I would like to close this issue.

I had a look at the issue you mentioned and you are correct it seems this issue is a duplicate issue. However, what I am worried about is the other issue is closed and marked as "won't fix". May I ask why this issue won't be fixed? Certainly, the .toString() workaround works, but given there is already a `QueryBuilders.termsQuery(String, Object)` method that has been working until version 7.12.0 it's causing a lot of unnecessary overhead for all existing projects to stop using Enum and use `QueryBuilders.termsQuery(String, String)` instead. This issue has caused a lot of silent failures in different places for us and cannot easily be avoided given the method signature does not prevent it in the first place.

**Comment by cbuescher** [comment] 2021-05-31 11:58
> May I ask why this issue won't be fixed?

Sure, I understand the concern, but the fact that creating TermsQueryBuilder with Enums worked so far was mostly a lucky accident. We always already used the enums string representation when sending the request to the server. We should now have allowed using Enums directly in the constructor in the first place for the reason I mentioned on the original issue. I don't think we should revert to this potential buggy behaviour, especially when there is a correct way of using the enums string representation that should be used. The issue we have open centers around preventing the misuse in the first place.
I hope this ansers your question.

**Comment by mraliagha** [comment] 2021-05-31 13:11
>  I don't think we should revert to this potential buggy behaviour, especially when there is a correct way of using the enums string representation that should be used. The issue we have open centers around preventing the misuse in the first place.

Yes. It makes sense. I agree with you. However, if that was not by design it should have been prevented, so I hope this confusion will be removed by deprecating the `QueryBuilders.termsQuery(String, Object)` method. Is there any plan to remove that from other types of queries supported in the `QueryBuilders` class? They seem to work with Enum right now, but if that's also not by design I am afraid it may get removed soon and create additional side effects.

**Comment by cbuescher** [comment] 2021-05-31 13:33
> Is there any plan to remove that from other types of queries supported in the `QueryBuilders` class? They seem to work with Enum right now, but if that's also not by design I am afraid it may get removed soon and create additional side effects.
Good point, I will add this to the open issue.

**Closed by cbuescher** 2021-05-31 13:33 UTC
Labels: :Search/Search, >bug, Team:Search, v7.12.0, v7.13.0, v8.0.0
