### ISSUE TITLE
Documentation: HighLevelRestClient javadocs link to non existing pages

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#49716] opened 2019-11-29 12:09 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 7.4.2 up to master

**Description of the problem including expected versus actual behavior**: It seems, some javadocs are missing or under a wrong path

**Steps to reproduce**:

1. Go to https://www.elastic.co/guide/en/elasticsearch/client/java-rest/7.4/java-rest-high-javadoc.html or the master docs https://www.elastic.co/guide/en/elasticsearch/client/java-rest/master/java-rest-high-javadoc.html
2. Click on the `org.elasticsearch.client`  package
3. Click on 'RestHighLevelClient'
4. Click on `BulkResponse` (the first link in the MethodSummary paragraph)
5. See a 404 error

Original source of this was a forum post: https://discuss.elastic.co/t/broken-links-in-javadocs/209822

I have not tested further cases, but the user mentioned this happens on more links.

**Comment by selfishone** [comment] 2019-12-01 18:04
@cbuescher I am new to elasticsearch can i pick this up?

**Comment by cbuescher** [comment] 2019-12-02 09:48
@selfishone sure, unfortunately I'm not entirely sure where to start poking for this. I see the links are broken but I don't know if this is something in the javadocs themselves or in the way we build and deploy them, which might be more difficult to fix.

**Comment by jrodewig** [comment] 2020-07-31 19:44
This seems to have been fixed as I was not able to reproduce. Closing this issue.

**Closed by jrodewig** 2020-07-31 19:44 UTC
Labels: :Core/Features/Java High Level REST Client, >docs, Team:Core/Features, Team:Docs
