### ISSUE TITLE
Query performance degrade after 7.12 in big aggregation case

### ISSUE THREAD

**Issue by maosuhan** [elastic/elasticsearch#70800] opened 2021-03-24 09:58 UTC
We encounter query performance degrade after we upgrade to 7.12. The performance is almost 2 times slower than old version.
Below is the flame graph after in 7.12
![image](https://user-images.githubusercontent.com/1617828/112288804-ac7aaa00-8cc8-11eb-902f-c8d78951b379.png)

You can see `BytesReferenceStreamInput.maybeNextSlice` may be the performance bottleneck now and it is introduced in https://github.com/elastic/elasticsearch/pull/65921.

The query is 
```
{
  "query": {
    "bool": {
      "filter": [
        {
          "terms": {
            "xxxx_id": [
              xxxxx
              ]
          }
        },
        {
          "range": {
            "local_stat_time_hour": {
              "lt": "2020-12-30 00:00:00",
              "gte": "2020-10-01 00:00:00",
              "time_zone": "+00:00"
            }
          }
        }
      ]
    }
  },
  "aggs": {
    "stat_time_hour": {
      "date_histogram": {
        "min_doc_count": 1,
        "format": "yyyy-MM-dd HH:mm:ss",
        "interval": "hour",
        "extended_bounds": {
          "max": "2020-12-30 00:00:00",
          "min": "2020-10-01 00:00:00"
        },
        "field": "local_stat_time_hour"
      },
      "aggs": {
        "campaign_id": {
          "terms": {
            "field": "zzz_id",
            "size": 50000,
            "min_doc_count": 1
          },
          "aggs": {
            "yyyy": {
              "sum": {
                "field": "yyyy"
              }
            },
     ............... total 92 sum aggs
          }
        }
      }
    }
  },
  "size": 0
}
```

In 7.6.2, it takes 15 seconds to run the query but in 7.12, it takes 30 seconds. The response size is 600MB.
I guess if we can construct a query which produce large response size and many sum aggs, then we can reproduce the issue.

**Comment by nik9000** [comment] 2021-03-24 13:32
> The response size is 600MB.

Is that the resulting json?


A little bit of triage:
* this is in the coordinating node. The flame graph doesn't go "down" enough for me to see precisely where it is coming from, but it deserializing the agg for some reason.

**Comment by nik9000** [comment] 2021-03-24 18:23
I'll try and have a look at this in a day or so.

**Comment by nik9000** [comment] 2021-03-24 20:57
> In 7.6.2, it takes 15 seconds to run the query but in 7.12, it takes 30 seconds.

Did you come directly from 7.6.2 to 7.12.0?

**Comment by maosuhan** [comment] 2021-03-25 00:48
@nik9000 Thanks for your quick response.
Yes, 600MB is the result uncompressed json.
And we just directly upgrade from 7.6.2 to latest version to have a performance test.
Below is the detailed flame graph.
7.12
[flame graph.zip](https://github.com/elastic/elasticsearch/files/6201237/flame.graph.zip)
7.6.2
[flame graph 7.6.2.zip](https://github.com/elastic/elasticsearch/files/6201243/flame.graph.7.6.2.zip)

**Comment by nik9000** [comment] 2021-03-26 15:18
Thanks for the full flame graphs! Its super helpful. It does look like we switched from `ByteBufStreamInput` to `BytesReferenceStreamInput` which has the `maybeNextSlice` thing. I'll try and reproduce with a microbenchmark next. I probably won't get a chance to get something together until later next week though.

**Comment by original-brownbear** [comment] 2021-04-01 11:51
@nik9000 I think this makes perfect sense to fix (but may be hard to reproduce in isolation due to inlining). I have an easy fix for this, I'll open a PR

**Comment by original-brownbear** [comment] 2021-04-01 13:20
I opened #71181 that should get us back to comparable performance to what we had when we directly accessed `ByteBuf`.

**Closed** 2021-04-02 03:47 UTC
Labels: :Analytics/Aggregations, >bug, Team:Analytics
