### ISSUE TITLE
The index has entered RED status because the number of documents has reached 2,147,483,519

### ISSUE THREAD

**Issue by opencmit2** [elastic/elasticsearch#98651] opened 2023-08-21 02:43 UTC
### Elasticsearch Version

7.8.1

### Java Version

openjdk 14.0.1 

### OS Version

BigCloud Enterprise Linux release 7.6.1905 (Core)

### Problem Description

The index has entered RED status because the number of documents has reached 2,147,483,519. Can the index be restored to a normal status? 

### Steps to Reproduce

Create an index with an excessive number of documents，Put the index in the red state。

**Comment by DaveCTurner** [comment] 2023-08-21 07:44
Thanks very much for your interest in Elasticsearch.

Quoting the bug report form:

> Please also check your OS is [supported](https://www.elastic.co/support/matrix#show_os), and that the version of Elasticsearch has not passed [end-of-life](https://www.elastic.co/support/eol). If you are using an unsupported OS or an unsupported version then the issue is likely to be closed.

Your issue relates to Elasticsearch version 7.8.1 which has passed end-of-life, so I am closing this. I believe this issue does not occur in supported versions because of changes made since 7.8.1 was released. If you can reproduce this issue in a supported version then we will reopen it.

**Closed by DaveCTurner** 2023-08-21 07:44 UTC
Labels: >bug, needs:triage
