### ISSUE TITLE
Updating index analyzer allows inconsistent indexing

### ISSUE THREAD

**Issue by GlenRSmith** [elastic/elasticsearch#28111] opened 2018-01-05 21:04 UTC
As described in [indices-update-settings](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-update-settings.html#update-settings-analysis), it is possible to update analyzers while an index is closed. (The doc only shows adding an analyzer, but in fact it is possible to change an existing one.)

This leaves open the possibility to have documents indexed inconsistently before and after such a change. I think consideration should be given to disabling that capability.

cc: @s1monw

**Comment by s1monw** [comment] 2018-01-12 14:21
We discussed this in fixit-friday and this is a general / long standing (by design... I can already hear somebody say it's a feature) issue. We need to do a significant amount of work to fix this but first and foremost we need to find a good way to fix synonym filter. Synonyms should be updateable but only for search analyzers which is not the case. there are also issues with synonyms in general that we need to fix ie. files can be changed on disk and the index will be corrupted. 

We will look into fixing this issue hopefully soon.

**Comment by dakrone** [comment] 2024-05-08 21:49
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.

**Closed by dakrone** 2024-05-08 21:49 UTC
Labels: >enhancement, resiliency, PITA, :Data Management/Indices APIs, Team:Data Management
