### ISSUE TITLE
[CI] SmokeTestMultiNodeClientYamlTestSuiteIT fails at indices.stats/10_index

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#46129] opened 2019-08-29 13:36 UTC
Java.lang.AssertionError:
Failure at [indices.stats/10_index:3]:
expected [2xx] status code but api [indices.create]
returned [400 Bad Request] [{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [test1/h9cGvOpzRXCRIa40E8FSTA] already exists","index_uuid":"h9cGvOpzRXCRIa40E8FSTA","index":"test1"

**Comment by matriv** [comment] 2019-08-29 14:08
Build scan: https://gradle-enterprise.elastic.co/s/po3ylizqwwf6q
Reproduce with (didn't reproduce locally): 
```
./gradlew :qa:smoke-test-multinode:integTestRunner --tests "org.elasticsearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT" \
  -Dtests.method="test {yaml=indices.stats/10_index/Index - pattern}" \
  -Dtests.seed=47A708B23692C1D5 \
  -Dtests.security.manager=true \
  -Dtests.locale=is-IS \
  -Dtests.timezone=America/Barbados \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

**Comment by matriv** [comment] 2019-08-29 14:29
Another failure: Log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob+fast+part1/1024/console Build Scan: https://gradle-enterprise.elastic.co/s/6q3xz77vvfo7m

**Comment by atorok** [comment] 2019-09-02 08:26
this seems to be a duplicate of #46091

**Closed by atorok** 2019-09-02 08:26 UTC
Labels: :Core/Infra/Build, >test-failure, v8.0.0
