### ISSUE TITLE
Elasticsearch SQL (Exception on selecting array using queries)

### ISSUE THREAD

**Issue by TejasC-CS** [elastic/elasticsearch#34359] opened 2018-10-08 13:00 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): "6.4.2"

**Plugins installed**: No Plugins Installed

**JVM version** (`java -version`): "1.8.0_181"

**OS version** (`uname -a` if on a Unix-like system): "Windows 10 Pro"

**Description of the problem including expected versus actual behavior**: Elasticsearch throwing _sql_illegal_argument_exception_  when trying to select an array in a query.

**Steps to reproduce**:
Create an index and put some data in it as follows:
PUT index/type/1
{
  "body": "here",
  "arr" : ["c","d"]
}

PUT index/type/2
{
  "body": "there",
  "arr" : ["1","2"]
}

We can see that arr is an array.
When we try to select the field "body", we get the results as expected.
POST _xpack/sql
{
         "query":"SELECT body FROM index "
}
Results:
{
     "columns": [
           {
          "name": "body",
          "type": "text"
           }
      ],
    "rows": [
        [
           "here"
        ],
        [
          "there"
        ]
  ]
}

But, when we try to select field "arr" (which is of type array), we get results as follows:
POST _xpack/sql
{
         "query":"SELECT arr FROM index "
}

Results:
{
  "error": {
    "root_cause": [
      {
        "type": "sql_illegal_argument_exception",
        "reason": "Arrays (returned by [arr]) are not supported"
      }
    ],
    "type": "sql_illegal_argument_exception",
    "reason": "Arrays (returned by [arr]) are not supported"
  },
  "status": 500
}

I'm not really sure if it's a bug.
Is it a bug or this will be integrated later as a part of Elasticsearch roadmap?
Or there is no support for arrays at all?

**Comment by astefan** [comment] 2018-10-09 17:33
This is not a bug: arrays are not supported at the moment. A more thorough discussion about this you can find in [this issue](https://github.com/elastic/elasticsearch/issues/33204). I will close this issue now (as it is not a bug) and, if you'd like you can add more input to the [referenced previous issue](https://github.com/elastic/elasticsearch/issues/33204).

**Closed by astefan** 2018-10-09 17:33 UTC
Labels: :Search/SQL

**Comment by TejasC-CS** [comment] 2018-10-10 06:06
Thank you very much for your response.
I want to ask something.
When you sat "arrays are not supported at the moment", will elasticsearch SQL support arrays in near future ?

**Comment by astefan** [comment] 2018-10-10 09:38
It is possible we will implement it in the future. When and how, even if, still undecided. I can say that it's not on our list for the very near future though. As I mentioned in my previous comment, the referenced issue there has more details about the difficulties of implementing this feature, but I think it's not impossible.

**Comment by TejasC-CS** [comment] 2018-10-10 09:55
Okay, cool!
Thanks for looking into it
