### ISSUE TITLE
[CI] ClassificationIT.testDependentVariableIsAliasToNested failure

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#53270] opened 2020-03-09 09:40 UTC
log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=centos-8&&immutable/622/consoleFull
gradle: https://gradle-enterprise.elastic.co/s/6k53ohdaafsys

does not reproduce locally

failure:
```
08:05:12 org.elasticsearch.xpack.ml.integration.ClassificationIT > testDependentVariableIsAliasToNested FAILED
08:05:12     java.lang.AssertionError: 
08:05:12     Expected: <100>
08:05:12          but: was <84>
08:05:12         at __randomizedtesting.SeedInfo.seed([49F826DCA61815D3:3CB455B8FBF6D9AE]:0)
08:05:12         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
08:05:12         at org.junit.Assert.assertThat(Assert.java:956)
08:05:12         at org.junit.Assert.assertThat(Assert.java:923)
08:05:12         at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.assertProgress(MlNativeDataFrameAnalyticsIntegTestCase.java:206)
08:05:12         at org.elasticsearch.xpack.ml.integration.ClassificationIT.testDependentVariableIsAliasToNested(ClassificationIT.java:430)
08:05:12 REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.ClassificationIT.testDependentVariableIsAliasToNested" -Dtests.seed=49F826DCA61815D3 -Dtests.security.manager=true -Dtests.locale=fi -Dtests.timezone=Africa/Addis_Ababa -Dcompiler.java=13
08:05:12 
08:05:12 Suite: Test class org.elasticsearch.xpack.ml.integration.ClassificationIT
```

repro with:

```
./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.ClassificationIT.testDependentVariableIsAliasToNested" \
  -Dtests.seed=49F826DCA61815D3 \
  -Dtests.security.manager=true \
  -Dtests.locale=fi \
  -Dtests.timezone=Africa/Addis_Ababa \
  -Dcompiler.java=13
```

**Comment by droberts195** [comment] 2020-03-09 09:49
The error looks very similar to the one seen in #53222.  There is probably a whole set of tests that are affected by the same root cause problem.

**Comment by dimitris-athanasiou** [comment] 2020-03-09 10:29
This is indeed the same issue. Closing in favor of #53222

**Closed by dimitris-athanasiou** 2020-03-09 10:29 UTC
Labels: :ml, >test-failure
