### ISSUE TITLE
Wrong geo_distance filter behavior

### ISSUE THREAD

**Issue by ErickSkrauch** [elastic/elasticsearch#14185] opened 2015-10-19 08:24 UTC
I'm working on map search service. On Google Map defined some objects and i need to draw some areas, in whith they can bounds. ```geo_shape``` search work OK, but with ```geo_distance``` (e.g. circle search) i have trouble.

![](http://dl2.joxi.net/drive/0004/2001/325585/151016/4854042dd0.png)
If i move my circle above or below these strips, objects will be found. But if I move circle right or left objects, everything works as it should.

That is, if I change the latitude, but longitude affect the objects, ElasticSearch finds them.

Index looks like this:
```
'location' => [
    'type' => 'geo_shape',
],
'location_point' => [
    'type' => 'geo_point',
],
```

Data:
```
"location": {
    "type": "point",
    "coordinates": [
        25.76029,
        -80.19339
    ]
},
"location_point": [
    25.76029,
    -80.19339
],
```

Search query:
```
{
    "fields":[
        ...
    ],
    "query":{
        ...
    },
    "filter":{
        "and":[
            {
                "and":[
                    {
                        "or":[
                            {
                                "geo_distance":{
                                    "distance":"15294.54531m",
                                    "location_point":[
                                        26.57895,
                                        -80.19496
                                    ]
                                }
                            }
                        ]
                    }
                ]
            },
            {
                ...
            }
        ]
    }
}
```

P.S. the same behavior on ```geo_shape``` search with ```shape type = circle```.
P.S.S. If someone knows English better (e.g. anyone :D), please adjust my description.

**Comment by clintongormley** [comment] 2015-10-20 11:31
Hi @ErickSkrauch 

I'm afraid I don't understand what the problem is.  Could you provide a full recreation which demonstrates the data you have, the queries you are running, and what doesn't work as you expect?

**Comment by ErickSkrauch** [comment] 2015-10-20 13:53
I can show it to you using TeamViewer on my dev computer.
Can you add me to Skype or Telegram by nickname ErickSkrauch?

**Comment by clintongormley** [comment] 2015-10-20 14:02
No @ErickSkrauch we can't :)

**Comment by ErickSkrauch** [comment] 2015-10-20 14:19
Well, just that it would be the easiest way.

What exactly you not understand?
If I move the circle to the left or right (changing longitude), the objects will be filtered, but it does not affect the latitude.

![](http://dl2.joxi.net/drive/0004/2001/325585/151020/93d0c97e8b.png)
![](http://dl2.joxi.net/drive/0004/2001/325585/151020/65b16d8724.png)
![](http://dl2.joxi.net/drive/0004/2001/325585/151020/1ea3f80e77.png)
![](http://dl1.joxi.net/drive/0004/2001/325585/151020/b3377a1ab8.png)
![](http://dl1.joxi.net/drive/0004/2001/325585/151020/6a7b8043a1.png)

**Comment by clintongormley** [comment] 2015-10-20 14:20
I repeat: Could you provide a full recreation (ie show the curl requests that get sent to Elasticsearch, and the responses) which demonstrates the data you have, the queries you are running, and what doesn't work as you expect?

**Comment by ErickSkrauch** [comment] 2015-10-20 14:24
Ok, I will prepere full recreation.

**Comment by clintongormley** [comment] 2016-01-29 18:34
No more feedback. Closing

**Closed by clintongormley** 2016-01-29 18:34 UTC
Labels: :Geo, feedback_needed
