### ISSUE TITLE
JdbcResultSetIT testGettingBooleanValues failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#68018] opened 2021-01-26 18:28 UTC
I've seen 6 failures today.

**Build scan**:
https://gradle-enterprise.elastic.co/s/dpmvt2wywytia/tests/:x-pack:plugin:sql:qa:jdbc:single-node:v7.11.0%23bwcTest/org.elasticsearch.xpack.sql.qa.jdbc.single_node.JdbcResultSetIT/testGettingBooleanValues#1

**Repro line**:

`./gradlew ':x-pack:plugin:sql:qa:jdbc:single-node:v7.11.0#bwcTest' -Dtests.class="org.elasticsearch.xpack.sql.qa.jdbc.single_node.JdbcResultSetIT" -Dtests.method="testGettingBooleanValues" -Dtests.seed=59AC45162D7E3DF1 -Dtests.security.manager=true -Dtests.bwc=true -Dtests.locale=es-GT -Dtests.timezone=Africa/Maseru -Druntime.java=11`

**Reproduces locally?**:
Did not repro lcoally (although I got a random local failure once). I suspect a timing issue.

**Applicable branches**:
Only `master` so far.

**Failure history**:
https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=America/Los_Angeles&tests.container=org.elasticsearch.xpack.sql.qa.jdbc.single_node.JdbcResultSetIT&tests.disabledDistributions=WyJvdXRjb21lOnBhc3NlZCJd&tests.sortField=FAILED&tests.test=testGettingBooleanValues&tests.unstableOnly=true

**Failure excerpt**:
```
org.elasticsearch.xpack.sql.qa.jdbc.single_node.JdbcResultSetIT > testGettingBooleanValues FAILED
    org.junit.ComparisonFailure: expected:<...6-12-17T05:16:37.860[221568]+11:00] of type [DAT...> but was:<...6-12-17T05:16:37.860[]+11:00] of type [DAT...>
        at __randomizedtesting.SeedInfo.seed([59AC45162D7E3DF1:139A13CCAFD7344C]:0)
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.lambda$testGettingBooleanValues$111(ResultSetTestCase.java:930)
        at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.doWithQuery(ResultSetTestCase.java:1863)
        at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.doWithQuery(ResultSetTestCase.java:1851)
        at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.testGettingBooleanValues(ResultSetTestCase.java:917)
```

**Comment by palesz** [comment] 2021-01-26 21:16
These test failures seem to happen not on the current master, but only in builds that verify the following unmerged PR: https://github.com/elastic/elasticsearch/pull/67666/commits which is implement nano support. The comparison failure suggests that the same timestamp was returned, but the formatting changed (nanos vs millis only).

@matriv Can you please verify that these are already fixed with https://github.com/elastic/elasticsearch/pull/67666/commits/2c0909a59932c224406e098e144969386153601d ?

**Comment by mark-vieira** [comment] 2021-01-26 21:44
@palesz Yes, perhaps. I did run into this locally though, which is why I raised the issue. Perhaps what I encountered locally was a slightly different problem?

https://gradle-enterprise.elastic.co/s/zhidgux7yxdfy/tests/:x-pack:plugin:sql:qa:jdbc:single-node:integTest/org.elasticsearch.xpack.sql.qa.jdbc.single_node.JdbcResultSetIT/testGettingBooleanValues#1

**Comment by palesz** [comment] 2021-01-26 22:54
@mark-vieira Yes, your local run seems to be different. Instead of timestamp formatting issues (millis vs nanos) the timestamps are in different timezones. After a lots of trying I was able to reproduce the error with Oracle JDK 15.0.1 (with every other JDK it succeeds, this is the same version you are using). I'll take a look.

**Comment by matriv** [comment] 2021-01-27 09:53
To me this seems similar to this fix: https://github.com/elastic/elasticsearch/pull/51592
Tzdata keeps being update with newer java versions, so using fixed random offsets instead of random timezone ids is the way to go, to avoid those failures when the tests run with the server and the client (JDBC) on different JVMs.

**Closed** 2021-01-28 23:16 UTC
Labels: :Query Languages/SQL, >test-failure, Team:QL
