### ISSUE TITLE
request: float interval in histogram aggregations

### ISSUE THREAD

**Issue by razaba** [elastic/elasticsearch#10901] opened 2015-04-30 10:32 UTC
On my application we were trying to analyze floating data.
we tried to use histogram on a float field and we discovered that the "interval" field accepts only integer.
but sometimes we need to analyze floating number with more precision that the integer number cannot give us. For an example if you want to find the most frequently used radio frequency, just on FM range there is a more then 10 stations between 99 to 100 if you multiply it by 10.

I can resolve this problem by pre-indexing all my field with fixed factor, but its opposes a problem what if my client will want to change the factor dynamically?

And that why I came to the conclusion that we have to have a factor field (like in date histogram) or maybe to enable the  interval to be float number (both can be great)

thank you very much,
regards Raz Abadi

**Comment by jpountz** [comment] 2015-04-30 10:36
@razaba I'm closing this issue as a duplicate of https://github.com/elastic/elasticsearch/issues/4847. I agree decimal intervals can be useful...

**Closed by jpountz** 2015-04-30 10:36 UTC
