### ISSUE TITLE
[CI] XDocsClientYamlTestSuiteIT test {yaml=en/rest-api/watcher/stats/line_153} fails

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#33864] opened 2018-09-19 15:39 UTC
## Reproduction line 
(does not) reproduce locally
```
./gradlew :x-pack:docs:integTestRunner \
  -Dtests.seed=7088A82F5379EBE9 \
  -Dtests.class=org.elasticsearch.smoketest.XDocsClientYamlTestSuiteIT \
  -Dtests.method="test {yaml=en/rest-api/watcher/stats/line_153}" \
  -Dtests.security.manager=true \
  -Dtests.jvm.argline="-XX:-UseConcMarkSweepGC -XX:+UseG1GC" \
  -Dtests.locale=sr-Latn \
  -Dtests.timezone=Australia/Melbourne \
  -Dcompiler.java=10 \
  -Druntime.java=8
```

## Example relevant log:
```
19:47:10   1> [2018-09-19T05:46:57,699][ERROR][o.e.s.XDocsClientYamlTestSuiteIT] [test] This failing test was generated by documentation starting at en/rest-api/watcher/stats.asciidoc:line_153. It may include many snippets. See Elasticsearch's docs/README.asciidoc for an explanation of test generation.
19:47:10 ERROR   0.39s | XDocsClientYamlTestSuiteIT.test {yaml=en/rest-api/watcher/stats/line_153} <<< FAILURES!
19:47:10    > Throwable #1: org.elasticsearch.test.rest.yaml.ClientYamlTestResponseException: org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:40253], URI [/_xpack/security/user?error_trace=true], status line [HTTP/1.1 503 Service Unavailable]
19:47:10    > {"error":{"root_cause":[],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[],"stack_trace":"Failed to execute phase [query], all shards failed\n\tat org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:293)\n\tat org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:133)\n\tat org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:254)\n\tat org.elasticsearch.action.search.InitialSearchPhase.onShardFailure(InitialSearchPhase.java:106)\n\tat org.elasticsearch.action.search.InitialSearchPhase.access$200(InitialSearchPhase.java:50)\n\tat org.elasticsearch.action.search.InitialSearchPhase$2.onFailure(InitialSearchPhase.java:277)\n\tat org.elasticsearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:73)\n\tat org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:51)\n\tat org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:487)\n\tat org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1121)\n\tat org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1218)\n\tat org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1202)\n\tat org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:66)\n\tat org.elasticsearch.action.search.SearchTransportService$3.onFailure(SearchTransportService.java:364)\n\tat org.elasticsearch.search.SearchService$2.onFailure(SearchService.java:342)\n\tat org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:336)\n\tat org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:330)\n\tat org.elasticsearch.search.SearchService$3.doRun(SearchService.java:1021)\n\tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\n\tat org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat java.base/java.lang.Thread.run(Thread.java:844)\n"},"status":503}
```
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/13/consoleFull

## Frequency

Happens with low frequency, only one failure exactly like before, but a few others before. 
Since it's in docs I wanted to make sure it's recorded.

**Comment by jpountz** [comment] 2018-09-20 15:16
We looked into it and suspect that shards of the security index haven't finished allocating. As they are today, XPack tests preserve templates but not indices, while we should probably not delete and then reinstantiate the security index for every test. @nik9000 mentioned that this area in general needs love, so that for instance the same test runner could run regular and xpack doc tests.

**Comment by jpountz** [comment] 2018-09-20 15:17
For the record here is the line in the logs that I am referring to: `19:47:10    > Caused by: org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:40253], URI [/_xpack/security/user?error_trace=true], status line [HTTP/1.1 503 Service Unavailable]`

**Comment by romseygeek** [comment] 2018-09-21 12:57
Three more failures in the last 24 hours, all on master:
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=amazon/12/console
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java10,ES_RUNTIME_JAVA=java10,nodes=virtual&&linux/14/console
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/21/console

**Comment by droberts195** [comment] 2018-09-26 13:41
Same problem for a different Watcher docs test in 
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=amazon/24/console

```
13:28:48    > Caused by: org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:39715], URI [/_xpack/security/user?error_trace=true], status line [HTTP/1.1 503 Service Unavailable]
```

Also, #34013 is open for the same problem on Security docs tests.  Probably most intermittent X-Pack docs test failures are caused by this.

**Comment by nik9000** [comment] 2018-10-04 15:01
We believe this is caused because the tests clean out the security index after each test but don't wait for it to be recreated before the test. I've started working on cleaning up some of the other x-pack test cleanup code and eventually I'll get to security. And when I do, this issue is waiting for me.

**Comment by jkakavas** [comment] 2019-02-15 11:01
These haven't failed since late October last year : https://build-stats.elastic.co/goto/09ab121c9712bee12bbcb0a2bf58c3ea
It looks like https://github.com/elastic/elasticsearch/pull/35271 fixed them too - closing this for now

**Closed by jkakavas** 2019-02-15 11:01 UTC
Labels: :Core/Features/Watcher, >non-issue, >test-failure, v8.0.0
