### ISSUE TITLE
LongGCDisruptionTests.testNotBlockingUnsafeStackTraces failed

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#50047] opened 2019-12-10 18:08 UTC
Over the last month + there have been periodic failures of org.elasticsearch.test.disruption.LongGCDisruptionTests.testNotBlockingUnsafeStackTraces

A recent failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=adoptopenjdk11,nodes=general-purpose/379/console

Reproduce Line: 
```
./gradlew ':test:framework:test' --tests "org.elasticsearch.test.disruption.LongGCDisruptionTests.testNotBlockingUnsafeStackTraces" \
  -Dtests.seed=60FAC2799A7B2796 \
  -Dtests.security.manager=true \
  -Dtests.locale=hu-HU \
  -Dtests.timezone=US/Central \
  -Dcompiler.java=12
```

The internal stack trace:
```
11:07:35   2> java.lang.RuntimeException: suspending node threads took too long
11:07:35         at __randomizedtesting.SeedInfo.seed([60FAC2799A7B2796:62E98AC6BE559FFF]:0)
11:07:35         at org.elasticsearch.test.disruption.LongGCDisruption.startDisrupting(LongGCDisruption.java:124)
11:07:35         at org.elasticsearch.test.disruption.LongGCDisruptionTests.testNotBlockingUnsafeStackTraces(LongGCDisruptionTests.java:149)
```

The threadstacks:
```
11:07:35   1> [2019-12-10T10:07:32,452][WARN ][o.e.t.d.LongGCDisruptionTests$2] [testNotBlockingUnsafeStackTraces] failed to suspend node [test_node]'s threads within [30000] millis. Suspending thread stack trace:
11:07:35   1>  java.base@11.0.5/java.lang.Thread.suspend0(Native Method)
11:07:35   1> java.base@11.0.5/java.lang.Thread.suspend(Thread.java:1085)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruption.suspendThreads(LongGCDisruption.java:254)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruption$1.doRun(LongGCDisruption.java:87)
11:07:35   1> app//org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
11:07:35   1> java.base@11.0.5/java.lang.Thread.run(Thread.java:834)
11:07:35   1> Threads that weren't suspended:
11:07:35   1>  [test_node][0]
11:07:35   1> ----
11:07:35   1> java.base@11.0.5/java.lang.Thread.yield(Native Method)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests.lambda$testNotBlockingUnsafeStackTraces$2(LongGCDisruptionTests.java:131)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests$$Lambda$260/0x000000010033e840.run(Unknown Source)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests.lambda$testNotBlockingUnsafeStackTraces$3(LongGCDisruptionTests.java:141)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests$$Lambda$261/0x000000010033ec40.run(Unknown Source)
11:07:35   1> java.base@11.0.5/java.lang.Thread.run(Thread.java:834)
11:07:35   1> [test_node][4]
11:07:35   1> ----
11:07:35   1> java.base@11.0.5/jdk.internal.misc.Unsafe.park(Native Method)
11:07:35   1> java.base@11.0.5/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
11:07:35   1> java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
11:07:35   1> java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:917)
11:07:35   1> java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1240)
11:07:35   1> java.base@11.0.5/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:267)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests$LockedExecutor.executeLocked(LongGCDisruptionTests.java:45)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests.lambda$testNotBlockingUnsafeStackTraces$3(LongGCDisruptionTests.java:139)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests$$Lambda$261/0x000000010033ec40.run(Unknown Source)
11:07:35   1> java.base@11.0.5/java.lang.Thread.run(Thread.java:834)
11:07:35   1> [test_node][3]
11:07:35   1> ----
11:07:35   1> java.base@11.0.5/java.lang.Thread.yield(Native Method)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests.lambda$testNotBlockingUnsafeStackTraces$2(LongGCDisruptionTests.java:131)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests$$Lambda$260/0x000000010033e840.run(Unknown Source)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests.lambda$testNotBlockingUnsafeStackTraces$3(LongGCDisruptionTests.java:141)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests$$Lambda$261/0x000000010033ec40.run(Unknown Source)
11:07:35   1> java.base@11.0.5/java.lang.Thread.run(Thread.java:834)
11:07:35   1> [test_node][1]
11:07:35   1> ----
11:07:35   1> java.base@11.0.5/java.lang.Thread.yield(Native Method)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests.lambda$testNotBlockingUnsafeStackTraces$2(LongGCDisruptionTests.java:131)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests$$Lambda$260/0x000000010033e840.run(Unknown Source)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests.lambda$testNotBlockingUnsafeStackTraces$3(LongGCDisruptionTests.java:141)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests$$Lambda$261/0x000000010033ec40.run(Unknown Source)
11:07:35   1> java.base@11.0.5/java.lang.Thread.run(Thread.java:834)
11:07:35   1> [test_node][2]
11:07:35   1> ----
11:07:35   1> java.base@11.0.5/java.lang.Thread.yield(Native Method)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests.lambda$testNotBlockingUnsafeStackTraces$2(LongGCDisruptionTests.java:131)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests$$Lambda$260/0x000000010033e840.run(Unknown Source)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests.lambda$testNotBlockingUnsafeStackTraces$3(LongGCDisruptionTests.java:141)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests$$Lambda$261/0x000000010033ec40.run(Unknown Source)
11:07:35   1> java.base@11.0.5/java.lang.Thread.run(Thread.java:834)
```

**Comment by original-brownbear** [comment] 2019-12-10 18:50
I can reproduce this locally, running this test in a loop eventually gets the JVM into a state where it completely locks up (as in not even a thread-dump can be taken) and then the test eventually fails.

**Comment by original-brownbear** [comment] 2019-12-11 13:37
The problem here is that we are randomly running into safe points that take multiple seconds when calling `suspend` on the thread:

```
[136.264s][debug  ][vmoperation             ] begin VM_Operation (0x00007f4aeaa576c0): ThreadDump, mode: safepoint, requested by thread 0x00007f4abc0e3800
[136.264s][debug  ][vmoperation             ] end VM_Operation (0x00007f4aeaa576c0): ThreadDump, mode: safepoint, requested by thread 0x00007f4abc0e3800
[136.264s][debug  ][safepoint,stats         ]  136.264: ThreadDump                    [                18                 0             0 ][             0       0       0       0       0 ]               0 
[136.264s][info   ][safepoint               ] Leaving safepoint region
[136.264s][info   ][safepoint               ] Total time for which application threads were stopped: 0.0002377 seconds, Stopping threads took: 0.0000023 seconds
[136.264s][debug  ][thread,smr              ] tid=6164: SafeThreadsListPtr::acquire_stable_list: add nested list pointer to ThreadsList=0x00007f4abc004730
[136.264s][debug  ][thread,smr              ] tid=6164: SafeThreadsListPtr::release_stable_list: delete nested list pointer to ThreadsList=0x00007f4abc004730
[136.264s][debug  ][thread,smr              ] tid=6164: SafeThreadsListPtr::acquire_stable_list: add nested list pointer to ThreadsList=0x00007f4abc004730
[142.645s][debug  ][vmthread                ] Adding VM operation: ThreadSuspend
[142.645s][debug  ][vmthread                ] Evaluating safepoint VM operation: ThreadSuspend
[142.645s][debug  ][safepoint               ] Safepoint synchronization initiated. (18 threads)
[142.645s][info   ][safepoint               ] Application time: 6.3813087 seconds
[142.645s][info   ][safepoint               ] Entering safepoint region: ThreadSuspend
[142.645s][info   ][safepoint,cleanup       ] updating inline caches, 0.0000016 secs
[142.645s][info   ][safepoint,cleanup       ] compilation policy safepoint handler, 0.0000006 secs
[142.645s][info   ][safepoint,cleanup       ] deflating global idle monitors, 0.0000004 secs
[142.645s][info   ][safepoint,cleanup       ] purging class loader data graph, 0.0000001 secs
[142.645s][info   ][safepoint,cleanup       ] resizing system dictionaries, 0.0000008 secs
[142.645s][info   ][safepoint,cleanup       ] deflating per-thread idle monitors, 0.0000044 secs
[142.646s][info   ][safepoint,cleanup       ] safepoint cleanup tasks, 0.0002165 secs
[142.646s][debug  ][vmoperation             ] begin VM_Operation (0x00007f4aeaa57710): ThreadSuspend, mode: safepoint, requested by thread 0x00007f4abc0e3800
[142.646s][debug  ][vmoperation             ] end VM_Operation (0x00007f4aeaa57710): ThreadSuspend, mode: safepoint, requested by thread 0x00007f4abc0e3800
[142.646s][debug  ][safepoint,stats         ]  142.645: ThreadSuspend                 [                18                 0             0 ][             0       0       0       0       0 ]               0 
[142.646s][info   ][safepoint               ] Leaving safepoint region
```

This looks a lot like the following JVM bug. https://bugs.openjdk.java.net/browse/JDK-8212933 that is supposed to be fixed in JDK 12 b13, but I can still reproduce it in b33.

**Comment by davidkyle** [comment] 2020-01-06 16:04
Reopening... 

@original-brownbear the test fail on Java 8 (runtime, Java 13 build)


```
java.lang.RuntimeException: suspending node threads took too long
	at __randomizedtesting.SeedInfo.seed([59768ACBFC336E0F:5B65C274D81DD666]:0)
	at org.elasticsearch.test.disruption.LongGCDisruption.startDisrupting(LongGCDisruption.java:124)
	at org.elasticsearch.test.disruption.LongGCDisruptionTests.testNotBlockingUnsafeStackTraces(LongGCDisruptionTests.java:152)
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA=openjdk13,ES_RUNTIME_JAVA=java8,nodes=general-purpose/433/console
https://gradle-enterprise.elastic.co/s/mz54zhh4o5wfq

And a few more found on build stats: 
https://gradle-enterprise.elastic.co/s/zpncey4ukuwgk
https://gradle-enterprise.elastic.co/s/ag4cebu2jraju

**Comment by original-brownbear** [comment] 2020-01-06 16:42
Seems this is actually this issue https://bugs.openjdk.java.net/browse/JDK-8218446 for which the fix has been backed out again.
It's talking about the exact 6s waits I observed here as well in https://bugs.openjdk.java.net/browse/JDK-8218446?focusedCommentId=14251478&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14251478

**Comment by ywelsch** [comment] 2020-01-06 16:49
The above failure was on JDK8, not JDK13?

**Comment by pgomulka** [comment] 2020-01-07 11:26
failed again
https://gradle-enterprise.elastic.co/s/p2c4a73pwq3js
```
./gradlew ':test:framework:test' --tests "org.elasticsearch.test.disruption.LongGCDisruptionTests.testNotBlockingUnsafeStackTraces" \
  -Dtests.seed=E32A05972B9EA548 \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-KW \
  -Dtests.timezone=America/Argentina/Rio_Gallegos \
  -Dcompiler.java=13 \
  -Druntime.java=8
```
I wonder if the fix mentioned in comment https://github.com/elastic/elasticsearch/issues/50047#issuecomment-571212502 is aimed jdk13 only, we should try to disable the test for jdk8?
@original-brownbear what do you think?

**Comment by original-brownbear** [comment] 2020-01-08 10:20
@ywelsch 

right it's also happening on JDK-8 and 13 now ... 13 I'd expect because they backed out the fix for the linked issue but `8` is unexpected. 

I opened https://github.com/elastic/elasticsearch/pull/50731 to not fail the test if we run into blocked `Thread#suspend` but otherwise leave the test enabled as a suggested fix for this. If `8` fails for a different reason it should still fail and we can look into that then and we retain most of the coverage in general.

**Closed** 2020-01-14 13:38 UTC
Labels: :Distributed/Distributed, >test-failure

**Comment by craigtaverner** [comment] 2023-02-28 13:50
Happened for JDK20 once in the last week: https://gradle-enterprise.elastic.co/s/2cez7jjoafjy6/tests/:test:framework:test/org.elasticsearch.test.disruption.LongGCDisruptionTests/testNotBlockingUnsafeStackTraces?top-execution=1

**Comment by DaveCTurner** [comment] 2023-02-28 13:53
I suspect that's the same thing as https://github.com/elastic/elasticsearch/issues/93707

**Comment by craigtaverner** [comment] 2023-02-28 14:01
Happened also a month ago on the 2nd February: https://gradle-enterprise.elastic.co/s/azrns37543ppo/tests/:test:framework:test/org.elasticsearch.test.disruption.LongGCDisruptionTests/testNotBlockingUnsafeStackTraces?top-execution=1
