### ISSUE TITLE
Stored scripts API accepting malformed requests

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#27612] opened 2017-12-01 09:24 UTC
The stored scripts API today accepts malformed requests instead of throwing an exception.  For instance:

```
POST _scripts/foo
{
  "source": "return"
}

GET _scripts/foo
```

returns

```
{
  "_id": "foo",
  "found": true,
  "script": {
    "lang": "mustache",
    "source": """{"source":"return"}"""
  }
}
```

**Comment by rjernst** [comment] 2017-12-02 22:59
You need to tell it to compile against a script context.  Pass the `context` parameter (url) to the put stored script api with a context name, eg `template` if you are using a mustache script.

**Comment by clintongormley** [comment] 2017-12-05 11:25
The [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/modules-scripting-using.html#modules-scripting-stored-scripts) for this API doesn't mention contexts, so I can't figure out exactly how this is supposed to be used, but it seems like my original example above should throw an exception, no?

**Comment by rjernst** [comment] 2017-12-05 17:34
No, your example does not compile the script, it only stores it. We discussed making context required in previous issues before adding script contexts, but you thought that was too cumbersome for users. :) . It sounds like we just need to update the documentation.

**Comment by rjernst** [comment] 2017-12-05 17:46
My apologies, I misread the issue here. The problem is due to having support for old templates. This was where the entire template was passed. Essentially there is a heuristic that looks for "template", looks for "script", and if it doesn't find those, then it takes the entire body as the script source.

**Comment by topalavlad** [comment] 2017-12-12 13:26
Hi all, I'd like to start tinkering with the code and this seemed like a good issue to start with, but to me it seems this loose script definition might have been intended.

If "script" and "template" are not found, an object with the provided JSON contents is created in 
`StoredScriptSource#parse(BytesReference content, XContentType xContentType)` so I'm not sure what the desired fix is.

Do you think the object should be restricted to a more specific template?

**Comment by rjernst** [comment] 2017-12-12 20:48
@topalavlad The fix here is to deprecate/remove support for this leniency. It was my original intention to remove this for 6.0, but i did not get to deprecating it in time in 5.x. Additionally, "template" should also be deprecated/removed, but that is a separate issue (and possibly a bit more involved, I don't remember all the details from the last time I looked).

**Comment by topalavlad** [comment] 2017-12-13 00:22
Cool, I'll try to remove the part which accepts anything and see which tests will fail

**Comment by golankopi** [comment] 2018-02-01 14:57
Hi, any updates on that issue? 

In addition to much mentioned here,   **any** script created will be stored successfully:  

```
POST _scripts/foo
{
      "script": {
        "source": "fsafsfsfsfsafasf",
        "lang": "painless"
    }
}
```
will return:
```
{
  "acknowledged": true
}
```
and  `GET _scripts/foo`
will return: 
```
{
  "_id": "foo",
  "found": true,
  "script": {
    "lang": "painless",
    "source": "fsafsfsfsfsafasf"
  }
}
```

**Comment by jdconrad** [comment] 2018-03-12 17:58
We should probably discuss whether or not context should be required for stored scripts again now that they're completed.

**Comment by jdconrad** [comment] 2018-03-16 22:36
Discussion with @rjernst -- we may be able to compile against each existing context when a stored script is entered to ensure that at least one context will successfully compile.  As a follow up possibly even marking which contexts are good for use with the stored script.

**Comment by stu-elastic** [comment] 2020-04-02 19:00
This is one of the goals of https://github.com/elastic/elasticsearch/issues/53702 the issues in https://github.com/elastic/elasticsearch/issues/54677 need to be resolved first to move forward.

**Comment by rjernst** [comment] 2024-05-25 02:58
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.

**Closed by rjernst** 2024-05-25 02:58 UTC
Labels: >bug, :Core/Infra/Scripting, Team:Core/Infra
