### ISSUE TITLE
Flaky query results with TerminateAfter

### ISSUE THREAD

**Issue by albertteoh** [elastic/elasticsearch#67215] opened 2021-01-08 21:48 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 
Version: 7.9.1, Build: default/tar/083627f112ba94dffc1232e8b42b73492789ef91/2020-09-01T21:22:21.964974Z, JVM: 1.8.0_151

**Plugins installed**: []

**JVM version** (`java -version`):
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**:
_TL;DR_
Indeterministic behaviour from ES span query results leading to flaky span counts (and span sets) for traces. This appears to happen when `ES_MAX_DOC_COUNT * num_index_shards < num_spans_in_trace`. Has anybody seen this before and know if there is an easy fix for it, perhaps in ES configuration? @pavolloffay 

_Observations_
The following gif demonstrates the symptom resulting from the flakey ES span query results. "Find Traces" is clicked multiple times in quick succession on the same query and the first trace's span count jumps between the following numbers: `[500, 490, 499, 489, 435]`.

![jaeger-ui-demo-flaky-spancount-es7](https://user-images.githubusercontent.com/26584478/101739419-9a12a100-3b1b-11eb-9221-f1458fc08f7e.gif)

**Jaeger was ruled out as the cause of these flaky span counts** by reproducing the flaky query results locally in ES, as this next gif demonstrates (note the changing search result's `spanID` field):

![postman-demo-flaky-span-query-es7](https://user-images.githubusercontent.com/26584478/101885751-a3b90900-3bee-11eb-9eb0-3478b717c28f.gif)

_Note_:
- The same query is executed multiple times in quick succession.
- The query is on a single shard (out of 5 shards): `?preference=_shards:2`.
- The query requests for a single document via the `size: 1` and `terminate_after: 1` query attributes.
- The spanID, start time and duration fields returned from the query differ between executions of the same query.
- I believe the indeterministic start times cause the flaky span counts due to how jaeger-query scrolls through the documents returned by ES: https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/es/spanstore/reader.go#L388 
- This behaviour exists on both ES 6 and 7, and the gif above is from ES 7.

My suspicion is that [`TerminateAfter`](https://github.com/jaegertracing/jaeger/blob/6c2be456ca41cdb98ac4b81cb8d9a9a9044463cd/plugin/storage/es/spanstore/reader.go#L167) fetches the first `n` documents in-deterministically from each shard (before any sorting is applied), because removing `TerminateAfter` from the query resulted in correct span counts, though no longer limited.

**Steps to reproduce**:

Essentially, create multiple (> 1) unique documents that have a shared attribute, such as a common ID.
Then search on this common ID ensuring the `TerminateAfter` search attribute is set to 1 (something less than the number of documents containing the common ID). 

The following instructions are how I reproduced it with Jaeger's span documents, where the commonID is the `traceID`, but I believe any kind of document will do:

 1. `git clone git@github.com:jaegertracing/jaeger.git`
 2. `cd jaeger`
 3. `make build-collector`
 4. Run elasticsearch locally
 5. Start the Jaeger collector: `SPAN_STORAGE_TYPE=elasticsearch ./cmd/collector/collector-darwin-amd64`
 6. `make build-query`
 7. Start jaeger-query: `SPAN_STORAGE_TYPE=elasticsearch ./cmd/query/query-darwin-amd64`
 8. Clone and run the HotROD example to generate traces: https://github.com/jaegertracing/jaeger/tree/master/examples/hotrod
 9. Navigate to http://localhost:16686
 10. Find an example trace and click on it. Note the traceID from the URL bar and search for this in Elasticsearch like so:
 ```
{
    "query": {
        "bool": {
            "should": [
                {
                    "term": {
                        "traceID": {
                            "boost": 2,
                            "value": "<the trace ID>"
                        }
                    }
                },
                {
                    "term": {
                        "traceID": "<the trace ID>"
                    }
                }
            ]
        }
    },
    
    "sort": [
        {
            "startTime": {
                "order": "asc"
            }
        }
    ],
    "size": 1,
    "terminate_after": 1
}
```

**Comment by albertteoh** [comment] 2021-01-18 11:00
Thanks for the response @jimczi, yes my reproduction test is using replicas indeed. Specifically, there are 5 shards, with each shard having a primary and a replica.

Good to know that this is expected behaviour.

**Comment by albertteoh** [comment] 2021-01-18 11:07
Question: why would consecutive queries switch between primary and replica like that? Why is Elasticsearch not always fetching results directly from primary? I don't believe my local setup is under particularly high load nor had issues with the primary.

**Comment by jimczi** [comment] 2021-01-18 12:52
That's explained [here](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/search-search.html#search-preference).
What you see in your example is the round robin that we apply to select which replica should execute the request. We use adaptive replica selection to redirect the traffic to the fastest node but in your case it's just switching from one replica to another in order to spread the load on the cluster. 
Note that you can use a custom-string in the preference as explained in the documentation:
```
Any string that does not start with _. If the cluster state and selected shards do not change, searches using the same <custom-string> value are routed to the same shards in the same order.
```

**Comment by jimczi** [comment] 2021-01-18 19:39
I am closing this issue since the behavior is expected and not a bug as explained in the comments.

**Closed by jimczi** 2021-01-18 19:39 UTC
Labels: :Search/Search, >bug, Team:Search
