### ISSUE TITLE
Client node count not shown in stats api - ES 2.0.1

### ISSUE THREAD

**Issue by SKumarMN** [elastic/elasticsearch#17311] opened 2016-03-24 06:02 UTC
I have 3 nodes in my cluster and two are master cum data nodes and one node is client node. When I issues stats api(_cluster/stats), I still see the count of client as 0 even though its is up and working.

Below is the response of stats API

nodes: {
count: {
total: 3,
master_only: 0,
data_only: 0,
master_data: 2,
client: 0
},
versions: [
"2.0.1"
],

jvm: {
max_uptime_in_millis: 1181282,
versions: [
{
version: "1.8.0_73",
vm_name: "Java HotSpot(TM) 64-Bit Server VM",
vm_version: "25.73-b02",
vm_vendor: "Oracle Corporation",
count: 3
}
],

OS is 
name: "Linux",
arch: "amd64",
version: "2.6.18-308.4.1.0.1.el5",
available_processors: 32
:

**Comment by javanna** [comment] 2016-03-24 06:53
HI @SKumarMN how did you set up the nodes to be client nodes? Did you set `node.client` to `true` or `node.master` and `node.data` to `false`? I believe this may be related to #16565 .

**Comment by SKumarMN** [comment] 2016-03-24 08:57
Yes as per this doc [link
](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html
) , I gave node.master and node.data to false

**Comment by javanna** [comment] 2016-03-24 10:02
That's what I though, I am closing as duplicate of #16565, but thanks for reporting. This is being addressed as part of #16963 so that there is a single way to create a client node and that will be always taken into account in all the relevant apis, e.g. cluster stats

**Closed by javanna** 2016-03-24 10:02 UTC
Labels: :Cluster, feedback_needed
