### ISSUE TITLE
Lintian failure on Debian 10

### ISSUE THREAD

**Issue by pugnascotia** [elastic/elasticsearch#48573] opened 2019-10-28 10:59 UTC
We added Debian 10 to the packaging tests for #44657. Now those tests are failing, as below.

```
org.elasticsearch.packaging.test.DebMetadataTests > test05CheckLintian FAILED
--
java.lang.RuntimeException: Command was not successful: [bash -c lintian /var/lib/jenkins/workspace/elastic+elasticsearch+pull-request+multijob+packaging-tests-unix-gcp/os/debian-10-packaging/distribution/packages/deb/build/distributions/elasticsearch-8.0.0-SNAPSHOT-amd64.deb]
result: exitCode = [2] stdout = [N: 0 tags overridden; 17 unused overrides] stderr = [bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
LANGUAGE = (unset),
LC_ALL = "en_US.UTF-8",
LANG = (unset)
are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
warning: the authors of lintian do not recommend running it with root privileges!
Usage: Lintian::files::empty_package::_set_is_dummy(self, newvalue) at /usr/share/lintian/checks/files/empty-package.pm line 42.
internal error: cannot run files check on package binary:elasticsearch/8.0.0~SNAPSHOT/amd64
warning: skipping check of binary:elasticsearch/8.0.0~SNAPSHOT/amd64]
at __randomizedtesting.SeedInfo.seed([AF166E2BC43F9213:6FE8F2C77E4BF7A8]:0)
at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:116)
at org.elasticsearch.packaging.util.Shell.run(Shell.java:68)
at org.elasticsearch.packaging.test.DebMetadataTests.test05CheckLintian(DebMetadataTests.java:45)
```

**Comment by pugnascotia** [comment] 2019-10-28 10:59
cc @atorok

**Comment by ywelsch** [comment] 2019-10-28 13:04
Build failure: https://gradle-enterprise.elastic.co/s/izjgwzn5rolaq

**Comment by mark-vieira** [comment] 2019-10-28 21:25
We are getting all kinds of nasty errors and warning related to issues setting the default locale on Debian 10. I think I've tracked down the problem. I've opened https://github.com/elastic/infra/issues/15670 to have this addressed.

**Comment by atorok** [comment] 2019-10-29 06:46
I don't think the locale errors are causing this.
I'm getting this with `locales-all`  installed.
```
jenkins@alpar-ci-debian-10-1029-0746:~/elasticsearch$ lintian distribution/packages/oss-deb/build/distributions/elasticsearch-oss-8.0.0-SNAPSHOT-amd64.deb


Usage: Lintian::files::empty_package::_set_is_dummy(self, newvalue) at /usr/share/lintian/checks/files/empty-package.pm line 42.
internal error: cannot run files check on package binary:elasticsearch-oss/8.0.0~SNAPSHOT/amd64
warning: skipping check of binary:elasticsearch-oss/8.0.0~SNAPSHOT/amd64
N: 0 tags overridden; 16 unused overrides
```

**Comment by atorok** [comment] 2019-10-29 08:46
I think the root cause is 
```
Usage: Lintian::files::empty_package::_set_is_dummy(self, newvalue) at /usr/share/lintian/checks/files/empty-package.pm line 44.
```
which is indicative of a a bug in lintian. 

Also of note: 
```
jenkins@alpar-ci-debian-10-1029-0746:~/elasticsearch$ lintian --version
Lintian v2.30.0
```

According to https://packages.debian.org/search?keywords=lintian that's the version in testing, debian 10 should have `2.15.0` 

Running `sudo apt-get install lintian=2.15.0` to get the correct version works.

We have a miss configured source 
```
jenkins@alpar-ci-debian-10-1029-0746:~/elasticsearch$ cat /etc/apt/sources.list.d/deb_debian_org_debian.list 
deb http://deb.debian.org/debian unstable main
jenkins@alpar-ci-debian-10-1029-0746:~/elasticsearch$ apt-cache showpkg lintian
Package: lintian
Versions: 
2.30.0 (/var/lib/apt/lists/deb.debian.org_debian_dists_unstable_main_binary-amd64_Packages)

```

**Comment by atorok** [comment] 2019-10-29 12:13
The workaround was merged to stop the CI failures, will keep the issue open to track removing it once the image is fixed.

**Comment by atorok** [comment] 2019-11-13 15:33
Different Lintian versions check different things, that's why this was particular to Debian 10.

**Closed by atorok** 2019-11-13 15:33 UTC
Labels: :Core/Infra/Packaging, >test-failure
