### ISSUE TITLE
Lack of warning for parsing incorrect parameters in elasticsearch.yml 

### ISSUE THREAD

**Issue by mtbottle** [elastic/elasticsearch#10022] opened 2015-03-06 16:02 UTC
There is a lack of warning for incorrectly parsed configurations. In this case I set invalid values for the following configurations in elasticsearch.yml : 

```
# incorrect values because booleans have to be lowercase
node.master: True
node.data: True
discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.unicast.hosts: ["localhost"]
```
But elastic search starts and I am able to see the following cluster nodes:
```
curl localhost:9200/_nodes/http?pretty=true
{
  "cluster_name" : "elasticsearch",
  "nodes" : {
      ...
      "attributes" : {
        "master" : "True",
        "data" : "True"
      },
     ...
    },
```
The only indication when I get that there is a problem is when I try to run other commands to access the data in the cluster. This is the error that I get back when I try to add a mapping to my_index:
```
curl -X PUT localhost:9200/my_index -d @mapping.json'
{"error":"MasterNotDiscoveredException[waited for [30s]]","status":503}
```
In this case, it would be useful to fail server start if there is an incorrect parameter or issue some sort of warning or have it logged. I ran this on elasticsearch 1.3.4.

**Comment by clintongormley** [comment] 2015-04-04 12:38
Agreed - we're planning a big settings cleanup.  Closing as a duplicate of #6732

**Closed by clintongormley** 2015-04-04 12:38 UTC
