### ISSUE TITLE
Segment merges should try to avoid exhausting all free disk space

### ISSUE THREAD

**Issue by mikemccand** [elastic/elasticsearch#15481] opened 2015-12-16 15:13 UTC
When a Lucene segment merge runs, it needs sizable free temporary disk space to do its work.  If it runs out of disk space part way through, the OS rejects the `write` call, and we'll hit a "tragic" exception that will fail that shard.

This behavior is particularly evil because on filling up the disk, the merge will then go and remove all temp files, thus freeing up (sizable) disk space and provoking issues like #15420 where "at first it failed and now it succeeded" leads to corruption.

Instead, we should avoid kicking off the merge, up front, if there isn't enough space?  I think we need some simple "reservation" API where the merge can claim how much space it expects to use, and fail at that point if there isn't enough space.

Probably we could do this with a `Directory` wrapper that 1) uses Java's APIs to monitor free space periodically, and 2) adds this new reservation API.  This wrapper should then throw the "disk full" `IOException` long before the underlying disk actually fills up.  We would need to wrap `IndexOutput` as well, because the up front estimate could be off, and of course other things (merges from other shards, users copying files around, etc.) can concurrently fill up the disk.

I think much of this improvement could be done in Lucene, with ES customizing the "reserve" method to be aware of N shards that are all reserving space for their merges on one node?  Lucene's default `TieredMergePolicy` already estimates the size of the merged segment to enforce its `maxMergedSegmentMB`...

Or maybe there's a simpler approach?

**Comment by nik9000** [comment] 2015-12-16 15:55
> Instead, we should avoid kicking off the merge, up front, if there isn't enough space

This is a pretty good start, I think. Its also probably worth loudly complaining about how we can't start the merge because of free space. I don't know how to prevent spamming the logs with it, maybe eating more free space.

I don't know what we can do about not having enough space though.

> "reserve" method

Elasticsearch already does some reservation math when it copies shards from one node to another. I suspect having a common abstraction that we can plug in a few places would allow restores to play well with merges.

**Comment by jpountz** [comment] 2015-12-18 13:44
Do we need to do anything here? Regarding #15420 the bug was in the translog, not due to merges? And it's actually a good thing that this behaviour exposed #15420, otherwise we might have never caught the bug.

**Comment by mikemccand** [comment] 2015-12-21 19:37
It is indeed nice that merges will go and fill up disk space for us, provoking nasty disk-full bugs that otherwise wouldn't be found, but it would be best if our tests could properly simulate random disk full situations, using the mock filesystems from Lucene.

Maybe, we shouldn't fix this until we have better disk-full testing in place?

**Comment by rmuir** [comment] 2015-12-21 20:04
I am -1 to stopping merging because space runs out. Failing the merge is the right thing to do.

I do not think we should add "reserve space" in lucene unless we back it by a method in the JDK that actually reserves space (http://pubs.opengroup.org/onlinepubs/009695399/functions/posix_fallocate.html or similar), and lucene does not need this since we only rely on atomic rename always. The problem is not lucene corrupting anything here.

As far as testing, I still have a disk full branch if anyone wants to help: https://github.com/apache/lucene-solr/compare/trunk...rmuir:diskfull

Testing this well is easy with something like lucene that uses a very contained set of the java filesystem api and is only write-once, it needs lots of improvements to implement the other apis. For example, lucene does not even use FileChannel for write, just for locking. But this is more complex than an outputstream for testing this.

**Comment by rmuir** [comment] 2015-12-21 20:14
By the way, if we want a best effort check to fail earlier, lets put it somewhere in e.g. ElasticsearchMergePolicy to check estimated size against filestore.

To me this is very different from adding i/o methods to lucene's Directory API that do not work.

**Comment by mikemccand** [comment] 2015-12-22 00:32
> Failing the merge is the right thing to do.

+1: I think failing the shard (that's pointing to a data path that is too full to do the requested merge) is the right thing to do.  In Lucene, I think closing the `IndexWriter` with a tragic exception...

> I do not think we should add "reserve space" in lucene unless we back it by a method in the JDK that actually reserves space 

`RAF.setLength` doesn't `fallocate` right (it will create sparse files)?  Lucene used to call this API when building compound files I think :)

Is there any way to `fallocate` from Java now?

> lets put it somewhere in e.g. ElasticsearchMergePolicy to check estimated size against filestore.

OK, I'll explore doing this only in Elasticsearch: I agree it's the easy way out, but I don't think it's the correct approach.  I.e., other Lucene users also don't want large merges to use up all free disk space.

**Comment by rmuir** [comment] 2015-12-22 06:06
> RAF.setLength doesn't fallocate right (it will create sparse files)? Lucene used to call this API when building compound files I think :)
> 
> Is there any way to fallocate from Java now?

Nothing in java calls it.

> OK, I'll explore doing this only in Elasticsearch: I agree it's the easy way out, but I don't think it's the correct approach. I.e., other Lucene users also don't want large merges to use up all free disk space.

Why? because their code is broken on disk-full and they would rather hide from that? That's not lucene's job, its a search engine library. We should just deliver the exception!

**Comment by mikemccand** [comment] 2016-01-15 16:39
Both @jpountz and @rmuir seem against making any change to ES's or Lucene's behavior when disk full is approaching ... I'm going to close this as "won't fix" for now.

We can revisit it when we have better test coverage of disk full situations.

**Comment by jasontedor** [comment] 2018-03-14 02:22
Closing as won't fix per the discussion here. Note that we have made some additional changes in Elasticsearch to handle full-disk situations better: #25541

**Closed by jasontedor** 2018-03-14 02:22 UTC
Labels: :Core/Core, >bug, PITA
