### ISSUE TITLE
EndpointSuffix support in azure repository plugin

### ISSUE THREAD

**Issue by hanabi1224** [elastic/elasticsearch#26655] opened 2017-09-15 02:49 UTC
Azure storage has customized domain in certain regions, e,g.  EndpointSuffix=core.chinacloudapi.cn in Azure China. It will be great to support EndpointSuffix part from Azure storage connection string setting

Refer to: [doc](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.cloudstorageaccount.-ctor?redirectedfrom=MSDN&view=azurestorage-8.1.3#Microsoft_WindowsAzure_Storage_CloudStorageAccount__ctor_Microsoft_WindowsAzure_Storage_Auth_StorageCredentials_System_String_System_Boolean_) and [post](https://stackoverflow.com/questions/44676186/azure-cloud-storage-account-with-custom-endpoint-suffix)

**Comment by martijnvg** [comment] 2017-09-15 07:44
Duplicate of #26432

**Closed by martijnvg** 2017-09-15 07:44 UTC
