### ISSUE TITLE
can't run jstack command in elasticsearch docker container

### ISSUE THREAD

**Issue by huanqingdong** [elastic/elasticsearch#50727] opened 2020-01-08 07:00 UTC
**Elasticsearch version**:
7.1.0

**Plugins installed**: 
repository-hdfs ,elasticsearch-analysis-ik,dynamic-synonym

**JVM version** (`java -version`):
openjdk version "12.0.1" 2019-04-16
OpenJDK Runtime Environment (build 12.0.1+12)
OpenJDK 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)

**OS version** (`uname -a` if on a Unix-like system):
Linux SmartSearch-es01 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
I use the docker image elasticsearch:7.1.0 , I can not run jstack command in docker container and got the error beloow : 
1: Unable to open socket file /proc/1/root/tmp/.java_pid1: target process 1 doesn't respond within 10500ms or HotSpot VM not loaded

**Steps to reproduce**:
 1.  setp into docker container es01
```shell
docker exec -it es01 bash
```
 2. change user to elasticsearch 
```shell
[root@docker-221 elasticsearch]# su elasticsearch
[elasticsearch@docker-221 ~]$ 
```
 3. run jstack comman
```shell
[elasticsearch@docker-221 ~]$ /usr/share/elasticsearch/jdk/bin/jps
1 Elasticsearch
966 Jps
[elasticsearch@docker-221 ~]$ /usr/share/elasticsearch/jdk/bin/jstack 1
1: Unable to open socket file /proc/1/root/tmp/.java_pid1: target process 1 doesn't respond within 10500ms or HotSpot VM not loaded
```

**Provide logs (if relevant)**:

**Comment by dliappis** [comment] 2020-01-08 11:11
Thanks very much for your interest in Elasticsearch.

The issue is that the `elasticsearch` process runs as uid 1000 and gid 0, but when you `su elasticsearch` uid:gid `1000:1000`; instead you should try `docker exec -u 1000:0 -ti es01 /bin/bash` and run jstack from there without `su`'ing.

Having said that, this appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Closed by dliappis** 2020-01-08 11:11 UTC

**Comment by huanqingdong** [comment] 2020-01-09 00:40
@dliappis Thank you very much , It works

**Comment by xiaochengxuyuan** [comment] 2022-11-11 03:13
nice！

**Comment by xiaoshi2013** [comment] 2023-02-09 14:08
nice
