### ISSUE TITLE
Unable to execute batch script

### ISSUE THREAD

**Issue by johnjaylward** [elastic/elasticsearch#55131] opened 2020-04-13 20:02 UTC
I am unable to start Elastic on Windows 10 because my environment does not have batch "delayed expansion" enabled by default.

When I run the script `elasticsearch-env.bat` I get the following output:
```
C:\Program Files\Elastic\Elasticsearch\7.6.2>.\bin\elasticsearch-env.bat

C:\Program Files\Elastic\Elasticsearch\7.6.2>set SCRIPT=.\bin\elasticsearch-env.bat

C:\Program Files\Elastic\Elasticsearch\7.6.2>rem determine Elasticsearch home; to do this, we strip from the path until we

C:\Program Files\Elastic\Elasticsearch\7.6.2>rem find bin, and then strip bin (there is an assumption here that there is no

C:\Program Files\Elastic\Elasticsearch\7.6.2>rem nested directory under bin also named bin)

C:\Program Files\Elastic\Elasticsearch\7.6.2>for %I in (.\bin\elasticsearch-env.bat) do set ES_HOME=%~dpI

C:\Program Files\Elastic\Elasticsearch\7.6.2>set ES_HOME=C:\Program Files\Elastic\Elasticsearch\7.6.2\bin\

C:\Program Files\Elastic\Elasticsearch\7.6.2>for %I in (":\Program Files\Elastic\Elasticsearch\7.6.2\bin") do set DIRNAME=%~nxI

C:\Program Files\Elastic\Elasticsearch\7.6.2>set DIRNAME=bin

C:\Program Files\Elastic\Elasticsearch\7.6.2>if not "bin" == "bin" (
for %I in ("C:\Program Files\Elastic\Elasticsearch\7.6.2\bin\..") do set ES_HOME=%~dpfI
 goto es_home_loop
)

C:\Program Files\Elastic\Elasticsearch\7.6.2>for %I in ("C:\Program Files\Elastic\Elasticsearch\7.6.2\bin\..") do set ES_HOME=%~dpfI

C:\Program Files\Elastic\Elasticsearch\7.6.2>set ES_HOME=C:\Program Files\Elastic\Elasticsearch\7.6.2

C:\Program Files\Elastic\Elasticsearch\7.6.2>rem now set the classpath

C:\Program Files\Elastic\Elasticsearch\7.6.2>set ES_CLASSPATH=!ES_HOME!\lib\*

C:\Program Files\Elastic\Elasticsearch\7.6.2>set HOSTNAME=AYLWARDJ-P50

C:\Program Files\Elastic\Elasticsearch\7.6.2>if not defined ES_PATH_CONF (set ES_PATH_CONF=!ES_HOME!\config )

C:\Program Files\Elastic\Elasticsearch\7.6.2>rem now make ES_PATH_CONF absolute

C:\Program Files\Elastic\Elasticsearch\7.6.2>for %I in ("C:\ProgramData\Elastic\Elasticsearch\config..") do set ES_PATH_CONF=%~dpfI

C:\Program Files\Elastic\Elasticsearch\7.6.2>set ES_PATH_CONF=C:\ProgramData\Elastic\Elasticsearch\config

C:\Program Files\Elastic\Elasticsearch\7.6.2>set ES_DISTRIBUTION_FLAVOR=default

C:\Program Files\Elastic\Elasticsearch\7.6.2>set ES_DISTRIBUTION_TYPE=zip

C:\Program Files\Elastic\Elasticsearch\7.6.2>set ES_BUNDLED_JDK=true

C:\Program Files\Elastic\Elasticsearch\7.6.2>cd /d "C:\Program Files\Elastic\Elasticsearch\7.6.2"

C:\Program Files\Elastic\Elasticsearch\7.6.2>rem now set the path to java, pass "nojava" arg to skip setting JAVA_HOME and JAVA

C:\Program Files\Elastic\Elasticsearch\7.6.2>if "" == "nojava" (exit /b )

C:\Program Files\Elastic\Elasticsearch\7.6.2>if defined JAVA_HOME (
set JAVA="C:\Program Files\AdoptOpenJDK\jdk-8.0.242.08-hotspot\bin\java.exe"
 set JAVA_TYPE=JAVA_HOME
)  else (
set JAVA="C:\Program Files\Elastic\Elasticsearch\7.6.2\jdk\bin\java.exe"
 set JAVA_HOME="C:\Program Files\Elastic\Elasticsearch\7.6.2\jdk"
 set JAVA_TYPE=bundled jdk
)

C:\Program Files\Elastic\Elasticsearch\7.6.2>if not exist !JAVA! (
echo "could not find java in !JAVA_TYPE! at !JAVA!"  1>&2
 exit /b 1
)
"could not find java in !JAVA_TYPE! at !JAVA!"
```

As you can see, the output is not expanding the variables set for delayed expansion like `!JAVA_TYPE!` or `!JAVA!`.

By adding the following line to the top of the file, expansion appears to work properly:
```bat
SETLOCAL ENABLEDELAYEDEXPANSION
```

I believe setting this at the top of all the `.bat` files would help alleviate weird issues like this.

https://github.com/elastic/elasticsearch/blob/633790fa99f30d8de02ab7d6af07dfb22332a8d8/distribution/src/bin/elasticsearch-env.bat#L1

**Comment by johnjaylward** [comment] 2020-04-13 20:36
after playing around with it a bit more, it appears that adding `SETLOCAL ENABLEDELAYEDEXPANSION` to the top of the `env` file did not work when running the `cli` file.

Adding `SETLOCAL ENABLEDELAYEDEXPANSION` to the top of the `cli.bat` but not to the top of `env.bat` worked.

Example output of having the expansion set in the `env.bat` and running the `cli.bat`:
```
C:\Program Files\Elastic\Elasticsearch\7.6.2>set ES_JAVA_OPTS=-Xms4m -Xmx64m -XX:+UseSerialGC

C:\Program Files\Elastic\Elasticsearch\7.6.2>-Xms4m -Xmx64m -XX:+UseSerialGC  -Des.path.home="C:\Program Files\Elastic\Elasticsearch\7.6.2\" -Des.path.conf="C:\ProgramData\Elastic\Elasticsearch\config" -Des.distribution.flavor="" -Des.distribution.type="" -cp "" ""
'-Xms4m' is not recognized as an internal or external command,
operable program or batch file.
```

Example output of having the expansion NOT set in the `env.bat` and running the `cli.bat` with it set in line 1:
```
C:\Program Files\Elastic\Elasticsearch\7.6.2>set ES_JAVA_OPTS=-Xms4m -Xmx64m -XX:+UseSerialGC

C:\Program Files\Elastic\Elasticsearch\7.6.2>"C:\Program Files\AdoptOpenJDK\jdk-8.0.242.08-hotspot\bin\java.exe"   -Xms4m -Xmx64m -XX:+UseSerialGC    -Des.path.home="C:\Program Files\Elastic\Elasticsearch\7.6.2"   -Des.path.conf="C:\ProgramData\Elastic\Elasticsearch\config"   -Des.distribution.flavor="default"   -Des.distribution.type="zip"   -cp "C:\Program Files\Elastic\Elasticsearch\7.6.2\lib\*"   ""
Error: Could not find or load main class
```

**Comment by johnjaylward** [comment] 2020-04-14 14:30
So I had initially installed in Windows using the `MSI` installer. I couldn't get it to work, so I uninstalled the MSI version and reinstalled just using the zip file release. I did not see this issue at all with the zip `bat` files. I'm not sure what's different between the two that would cause one to fail and the other to succeed. The main difference in my installation was that the `msi` placed the application under `c:\program files\elasticsearch...` while the zip is just under `c:\elasticsearch\...`. It seems odd that the bat files would have different runtime options depending on where they are running though, so I'm not sure that's important.

**Comment by rjernst** [comment] 2020-04-15 18:42
@johnjaylward when installing via the MSI, the exe is the expected route to launch Elasticsearch (or the provided service). The elasticsearch-env.bat file is never meant to be executed directly, and as you noted, requires setting delayed expansion before invoking. We do have tests for all these scripts, but Windows has been particularly troublesome to maintain a green CI state for as the edge cases are numerous. However, we have pretty good coverage for basic usage of launching Elasticsearch in the most common ways.

While it is certainly possible there still exist bugs, this issue doesn't indicate what the actual error condition is, since one would never invoke the env script directly, or provide a reproduction. It seems this is likely a user specific environmental or setup issue and we like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. As such, I hope you don't mind that I close this.

**Closed by rjernst** 2020-04-15 18:42 UTC
Labels: :Core/Infra/Core
