### ISSUE TITLE
Indexing a json displaying floats in float or rounded to integer format fails 

### ISSUE THREAD

**Issue by dolanor** [elastic/elasticsearch#17295] opened 2016-03-23 19:34 UTC
Hi,

**Elasticsearch version**: 2.2.1 (from `docker pull elasticsearch`)

**JVM version**: OpenJDK 1.8.0_72-internal (from `docker pull elasticsearch`

**OS version**: Debian 8.3 (from `docker pull elasticsearch`

**Description of the problem including expected versus actual behavior**:

Indexing some data were float64 data could be written as integer (by luck) makes elasticsearch refuse to index them.
In a file were the first type indexed was a float type and then another in the collection could be written as integer will make the indexing fail.

I think it should accept an integer in a floating point type, even if doesn't have the floating point format.
On the other hand, I understand that it couldn't accept a floating point number in a integer type because it creates data loss.

**Steps to reproduce**:
 1. `curl -X PUT localhost:9200/speed/record/1 -d '{ "speed_rec": [ { "speed": 61.23 }, { "speed": 61 } ] }'` will fail:
`{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"failed to parse"}],"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"illegal_argument_exception","reason":"mapper [speed_rec.speed] of different type, current_type [double], merged_type [long]"}},"status":400}`
 2. `curl -X PUT localhost:9200/speed/record/1 -d '{ "speed_rec": [ { "speed": 61.23 }, { "speed": 61.0 } ] }'` will succeed `{"_index":"speed","_type":"record","_id":"1","_version":1,"_shards":{"total":2,"successful":1,"failed":0},"created":true}`

**Comment by clintongormley** [comment] 2016-03-24 17:13
Duplicate of https://github.com/elastic/elasticsearch/issues/15377

**Closed by clintongormley** 2016-03-24 17:13 UTC
