### ISSUE TITLE
search_after not working with dates that are undefinded

### ISSUE THREAD

**Issue by tahergalal** [elastic/elasticsearch#28806] opened 2018-02-23 18:05 UTC
**Describe the feature**:

**Elasticsearch version** (6.2.1):

**JVM version** (`java -version`):

**OS version** (windows):

**Description of the problem including expected versus actual behavior**:
Index with many documents some of which have a value for a date field deletedOn and others don't

query uses a sort : [{"deletedOn": "asc"}, {"_id" : "asc"}]

this sometimes returns a value in the sort:[9223372036854776000,"doc_id_1"] of the hit that when passed to the search if I provide this information to search_after I get an error because the value from thedate field is expected to be a max of an integer with an error No matching token for number_type [BIG_INTEGER]

**Steps to reproduce**:

1. create two documents with a date field and a text field
2. create a document that only has a text field
3. search for match all size 2 with sort by date field and _id
4. provide the value obtained to the search_after 

**Provide logs (if relevant)**:

**Comment by nik9000** [comment] 2018-02-23 19:30
Could someone with @elastic/es-search-aggs take a look, maybe @jimczi?

**Comment by jimczi** [comment] 2018-02-28 16:50
Elasticsearch will never return a value greater than Long.MAX_VALUE (`9223372036854775807`)  for a date field. We use this value by default when a document doesn't have a value for the field that is sort on. What library are you using to parse the json response ? It seems that this library is reading the number returned by es as doubles and not longs. This would explain why `9223372036854775807` is replaced by `9223372036854776000` since doubles cannot accurately represent all numbers.

**Comment by tahergalal** [comment] 2018-02-28 17:13
this is the value I am getting when using the javascript lib. Also when testing the query in kibana I get the same value of 9223372036854776000

**Comment by jimczi** [comment] 2018-02-28 19:51
Ok so this is an issue with javascript that handles number with 64bit floating point and can't represent large number accurately. I am going to close this issue because the problem is not in es. You can check this issue in Kibana: https://github.com/elastic/kibana/issues/1274 and ask there what's the status.

**Closed by jimczi** 2018-02-28 19:51 UTC
Labels: :Search/Search, feedback_needed
