### ISSUE TITLE
NullPointerException when a datastream gets created.

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch#84600] opened 2022-03-03 07:58 UTC
### Elasticsearch Version

8.2.0-SNAPSHOT

### Installed Plugins

Running on cloud

### Java Version

_bundled_

### OS Version

Running on cloud.

### Problem Description

```
[instance-0000000001] failed to serialize outbound message [Response{512401}{false}{false}{false}{class org.elasticsearch.action.admin.indices.create.CreateIndexResponse}]
java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
	at org.elasticsearch.common.io.stream.StreamOutput.writeString(StreamOutput.java:390) ~[elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at org.elasticsearch.action.admin.indices.create.CreateIndexResponse.writeTo(CreateIndexResponse.java:63) ~[elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at org.elasticsearch.transport.OutboundMessage.serialize(OutboundMessage.java:70) ~[elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at org.elasticsearch.transport.OutboundHandler.sendMessage(OutboundHandler.java:170) [elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at org.elasticsearch.transport.OutboundHandler.sendResponse(OutboundHandler.java:145) [elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at org.elasticsearch.transport.TcpTransportChannel.sendResponse(TcpTransportChannel.java:57) [elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:41) [elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:38) [elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:19) [elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:31) [elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$applyInternal$2(SecurityActionFilter.java:164) [x-pack-security-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at org.elasticsearch.action.ActionListener$DelegatingFailureActionListener.onResponse(ActionListener.java:219) [elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at org.elasticsearch.action.ActionListener$DelegatingActionListener.onResponse(ActionListener.java:186) [elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at org.elasticsearch.action.admin.indices.create.AutoCreateAction$TransportAction.lambda$masterOperation$1(AutoCreateAction.java:150) [elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at org.elasticsearch.action.support.ActiveShardsObserver.waitForActiveShards(ActiveShardsObserver.java:68) [elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at org.elasticsearch.action.admin.indices.create.AutoCreateAction$TransportAction.lambda$masterOperation$2(AutoCreateAction.java:146) [elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:136) [elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at org.elasticsearch.cluster.AckedClusterStateUpdateTask.onAllNodesAcked(AckedClusterStateUpdateTask.java:59) [elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.MasterService$ContextPreservingAckListener.onAllNodesAcked(MasterService.java:586) [elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:270) [elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:153) [elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:114) [elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:170) [elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:717) [elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:260) [elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:223) [elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

### Steps to Reproduce

This happens just after the datastream gets created initially as a result of a `/_bulk` operation.

```
[instance-0000000001] adding data stream [logs-apm.error-default] with write index [.ds-logs-apm.error-default-2022.03.03-000001], backing indices [], and aliases [] | instance-0000000001 | gi-9116927167290556149 | INFO
```

```
[instance-0000000001] [.ds-logs-apm.error-default-2022.03.03-000001] creating index, cause [initialize_data_stream], templates [logs-apm.error], shards [1]/[1]
```

The individual bulk operation also fails with:

```
{
  "status": 500,
  "error": {
    "type": "null_pointer_exception",
    "reason": "Cannot invoke \"String.length()\" because \"str\" is null"
  },
  "operation": {
    "create": {
      "_index": "logs-apm.error-default"
    }
  },
```

I can not reproduce this consistently and strongly suggests a timing issue. 
After these errors pop up the datastream appears to be healthy and inserting the same documents manually no longer fails too.

**Comment by dakrone** [comment] 2022-03-03 23:35
@martijnvg do you have any ideas for what could be causing this?

**Comment by martijnvg** [comment] 2022-03-04 14:31
@Mpdreamz Can you share the `build_hash` of the cluster that you're using? I tried to reproduce locally, but I couldn't reproduce from master branch (from commit 1fc1a2da2d01e6049e553c1742a7f335214e40cb). There have been some changes in the auto create index logic (batching of cluster state update when auto creating new indices), but maybe the issue was unintentionally fixed by other commits. 

I will open a change to not allow specifying null as index in CreateIndexResponse. That way if this fails again, an easier to debug stacktrace will be available.

**Comment by martijnvg** [comment] 2022-03-31 07:18
@Mpdreamz Did you see another NPE?

**Comment by Mpdreamz** [comment] 2022-05-09 09:17
Hey @martijnvg I haven't seen an NRE for quite a while now.

I'm happy to reopen if I see it again.

**Comment by martijnvg** [comment] 2022-05-09 12:16
👍

**Closed by martijnvg** 2022-05-09 12:16 UTC
Labels: >bug, :Data Management/Data streams, Team:Data Management
