### ISSUE TITLE
Negative score for Similarity

### ISSUE THREAD

**Issue by lionsoul2014** [elastic/elasticsearch#48671] opened 2019-10-30 06:18 UTC
**Elasticsearch version** : 7.4.0

**JVM version** (`java -version`): 1.8.0_172

I copied the source code of BM25Similarity from lucene 8.2.0 source tree and renamed it to MyBM25Similarity and make it a plugin for elasticsearch, here is code blocks for the main interfaces:
```java
    /** Implemented as <code>log(1 + (docCount - docFreq + 0.5)/(docFreq + 0.5))</code>. */
    protected float idf(long docFreq, long docCount) 
    {
        return (float) Math.log(1 + (docCount - docFreq + 0.5D)/(docFreq + 0.5D));
    }

    @Override
    public final long computeNorm(FieldInvertState state) 
    {
        final int numTerms;
        if (state.getIndexOptions() == IndexOptions.DOCS && state.getIndexCreatedVersionMajor() >= 8) {
            numTerms = state.getUniqueTermCount();
        } else if (discountOverlaps) {
            numTerms = state.getLength() - state.getNumOverlap();
        } else {
            numTerms = state.getLength();
        }
        
        // System.out.println(this.getClass() + ", " + state.getName() + ", terms:  " + numTerms);
        return SmallFloat.intToByte4(numTerms);
    }

    @Override
    public final SimScorer scorer(float boost, CollectionStatistics collectionStats, TermStatistics... termStats) 
    {
        Explanation idf = termStats.length == 1
        		? idfExplain(collectionStats, termStats[0]) : idfExplain(collectionStats, termStats);
        float avgdl = avgFieldLength(collectionStats);

        float[] cache = new float[256];
        for (int i = 0; i < cache.length; i++) {
            cache[i] = k1 * ((1 - b) + b * LENGTH_TABLE[i] / avgdl);
        }
        
        final float boostVal = boost * (k1 + 1);
        return new BM25Scorer(boostVal, k1, b, freqModifierName, freqModifier, idf, avgdl, cache);
    }
```

My mapping for search:
```json
{
	"my_repository": {
		"aliases": {},
		"mappings": {
			"dynamic": "strict",
			"properties": {
				"attr_set": {
					"type": "text",
					"analyzer": "jcseg_delimiter"
				},
				"description": {
					"type": "text",
					"index_options": "offsets",
					"similarity": "my_bm25",
					"analyzer": "analyzer_for_index",
					"search_analyzer": "analyzer_for_search"
				},
				"for_match": {
					"type": "text",
					"similarity": "my_bm25",
					"analyzer": "analyzer_for_index",
					"search_analyzer": "analyzer_for_search"
				},
				"for_weight": {
					"type": "text",
					"similarity": "my_bm25",
					"analyzer": "analyzer_for_index",
					"search_analyzer": "analyzer_for_search"
				},
				"forks_count": {
					"type": "integer"
				},
				"id": {
					"type": "long"
				},
				"lang": {
					"type": "keyword"
				},
				"name": {
					"type": "text",
					"index_options": "offsets",
					"similarity": "my_bm25",
					"analyzer": "analyzer_for_index",
					"search_analyzer": "analyzer_for_search"
				},
				"payload": {
					"type": "text",
					"index": false
				},
				"repo_score": {
					"type": "half_float",
					"index": false,
					"store": true
				},
				"stars_count": {
					"type": "integer"
				},
				"updated_at": {
					"type": "integer"
				},
				"updated_td": {
					"type": "short",
					"index": false,
					"store": true
				},
				"watches_count": {
					"type": "integer"
				}
			}
		},
		"settings": {
			"index": {
				"number_of_shards": "3",
				"provided_name": "my_repository",
				"similarity": {
					"my_bm25": {
						"discount_overlaps": "true",
						"const_freq": "1",
						"b": "0.21",
						"freq_modifier": "logp1",
						"type": "MyBM25",
						"k1": "1.26"
					}
				},
				"creation_date": "1572408902153",
				"analysis": {
					"analyzer": {
						"analyzer_for_search": {
							"jcseg_maxlen": "5",
							"jcseg_appendpinyin": "0",
							"jcseg_appendsyn": "0",
							"type": "jcseg_complex",
							"jcseg_pptmaxlen": "0"
						},
						"analyzer_for_index": {
							"jcseg_maxlen": "5",
							"jcseg_appendpinyin": "1",
							"jcseg_appendsyn": "1",
							"type": "jcseg_search",
							"jcseg_pptmaxlen": "0"
						}
					}
				},
				"number_of_replicas": "1",
				"uuid": "VqXvoQeOSPWi5OLQD31dtg",
				"version": {
					"created": "7040099"
				}
			}
		}
	}
}
```

When i try to search something not everything, i saw the following logs ahout exception report:
```
org.elasticsearch.ElasticsearchException$1: Similarities must not produce negative scores, but got:
-31.97649 = score(freq=3.4028235E38), product of:
  4.746 = boost
  -3.0145967 = idf, computed as log(1 + (N - n + 0.5) / (n + 0.5)) from:
    86822 = n, number of documents containing term
    4259 = N, total number of documents with field
  2.234981 = tf=89.72284, modifer=logp1, computed as freq * / (freq + k1 * (1 - b + b * dl / avgdl)) from:
    3.4028235E38 = term frequency
    1.26 = k1, term saturation parameter
    0.21 = b, length normalization parameter
    1.0 = dl, length of field
    29.475698 = avgdl, average length of field
```

the following is my DSL for query:
```json
{
	"explain": true,
	"query": {
		"bool": {
			"must": [{
				"multi_match": {
					"type": "cross_fields",
					"fields": [
						"name^2.12",
						"for_weight^2.1",
						"description^1.42",
						"for_match^1"
					],
					"query": "my query string",
					"tie_breaker": 0.24,
					"operator": "AND"
				}
			}],
			"filter": {
				"bool": {
					"must": [{
						"term": {
							"attr_set": "attr:1"
						}
					}, {
						"term": {
							"attr_set": "attr:2"
						}
					}]
				}
			}
		}
	},
	"sort": [{
		"_score": "desc"
	}],
	"from": 0,
	"size": 11
}
```

i think this is bug:
n should never be greater than N or it will produce a negative score thougth **log(1 + (N - n + 0.5) / (n + 0.5))**

In my similarity plugin, I could do nothing for the value in N and n since i could only get them through the collectionStats object like the default BM25Similarity did.

it this because of the empty value for the specified field cause error count for the total number of documents ?

**Comment by lionsoul2014** [comment] 2019-10-30 06:44
i've read the solution for the runtime negative score checking for the none-buildin silimarity implementations in an issue here, i think that why the default BM25 works find for this.

**Comment by jimczi** [comment] 2019-10-30 13:14
This is a duplicate of #44700, the cross fields mode can generate negative scores when not all fields have the same doc count. We have plans to introduce the new BM25FQuery in #41106 in order to replace the buggy BlendedTermQuery.

**Closed by jimczi** 2019-10-30 13:14 UTC
Labels: :Search/Ranking, >bug
