### ISSUE TITLE
Check all shard directory write permissions?

### ISSUE THREAD

**Issue by calm4wei** [elastic/elasticsearch#66449] opened 2020-12-16 15:29 UTC
**Elasticsearch version** (`bin/elasticsearch --version`):6.7.2

**Plugins installed**: []

**JVM version** (`java -version`):1.8

**OS version** (`uname -a` if on a Unix-like system):CentOS release 6.5 (Final)

**Description of the problem including expected versus actual behavior**:
Environment description： 
8 nodes
34821 indexes
90371 shards
About 11296 shards per node

Operation: restart a data node 

Expected outcome: the es node service port starts within 5 minutes

Actual results: Node service port started more than 30 minutes

**Provide logs (if relevant)**:

> Printed node startup process stack as below:

java.lang.Thread.State: RUNNABLE
        at java.io.UnixFileSystem.canonicalize0(Native Method)
        at java.io.UnixFileSystem.canonicalize(UnixFileSystem.java:172)
        at java.io.File.getCanonicalPath(File.java:618)
        at java.io.FilePermission$1.run(FilePermission.java:224)
        at java.io.FilePermission$1.run(FilePermission.java:212)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.io.FilePermission.init(FilePermission.java:212)
        at java.io.FilePermission.<init>(FilePermission.java:299)
        at java.lang.SecurityManager.checkWrite(SecurityManager.java:979)
        at sun.nio.fs.UnixChannelFactory.open(UnixChannelFactory.java:247)
        at sun.nio.fs.UnixChannelFactory.newFileChannel(UnixChannelFactory.java:136)
        at sun.nio.fs.UnixChannelFactory.newFileChannel(UnixChannelFactory.java:148)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:212)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.createFile(Files.java:632)
        at org.elasticsearch.env.NodeEnvironment.tryWriteTempFile(NodeEnvironment.java:1073)
        at org.elasticsearch.env.NodeEnvironment.assertCanWrite(NodeEnvironment.java:1059)
        at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:278)
        at org.elasticsearch.node.Node.<init>(Node.java:263)
        at org.elasticsearch.node.Node.<init>(Node.java:243)
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:232)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:232)
                at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:350)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
        at org.elasticsearch.cli.Command.main(Command.java:88)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84)

**Cause Analysis**:

> The shard directory is as follows:

/data/nodes/0/indices/${index_uuid}/
          -- ${shardNumber}/
                  -- index/
                  -- _state/
                  -- translog/
          -- _state/

When the node starts, check whether it is necessary to sub-directories of each shard, the directories include index/translog/_state?

When the number of node shards is large, the startup is slow due to the need to check the write permission of each subdirectory. With 10,000 shards, the startup time exceeds 30 minutes.

> code show as below, org.elasticsearch.env.NodeEnvironment.java ：

private void assertCanWrite() throws IOException {
    for (Path path : nodeDataPaths()) { // check node-paths are writable
        tryWriteTempFile(path);
    }
    for (String indexFolderName : this.availableIndexFolders()) {
        for (Path indexPath : this.resolveIndexFolder(indexFolderName)) { // check index paths are writable
            Path indexStatePath = indexPath.resolve(MetadataStateFormat.STATE_DIR_NAME);
            tryWriteTempFile(indexStatePath);
            tryWriteTempFile(indexPath);
            try (DirectoryStream<Path> stream = Files.newDirectoryStream(indexPath)) {
                for (Path shardPath : stream) {
                    String fileName = shardPath.getFileName().toString();
                    if (Files.isDirectory(shardPath) && fileName.chars().allMatch(Character::isDigit)) {
                        Path indexDir = shardPath.resolve(ShardPath.INDEX_FOLDER_NAME);
                        Path statePath = shardPath.resolve(MetadataStateFormat.STATE_DIR_NAME);
                        Path translogDir = shardPath.resolve(ShardPath.TRANSLOG_FOLDER_NAME);
                        tryWriteTempFile(indexDir);
                        tryWriteTempFile(translogDir);
                        tryWriteTempFile(statePath);
                        tryWriteTempFile(shardPath);
                    }
                }
            }
        }
    }
}

**Solution**:
Is it possible to check only the write permission of the data root directory, such as /data/nodes?
About 11296 shards per node, node service port starts within 5 minutes if using this way.

What I want to discuss is whether it is necessary to check each shard subdirectory?

**Comment by DaveCTurner** [comment] 2020-12-16 18:33
Closing this as a duplicate of https://github.com/elastic/elasticsearch/pull/66429.

This doesn't sound like a bug so much as one of the (many) bad consequences of ignoring [safety limits](https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-cluster.html#cluster-shard-limit). 11k shards on a single node not a reasonable configuration.

**Closed by DaveCTurner** 2020-12-16 18:33 UTC
Labels: >bug, needs:triage
