### ISSUE TITLE
"discovery.seed_hosts"Dynamic IP is not supported

### ISSUE THREAD

**Issue by xueyin220807** [elastic/elasticsearch#77288] opened 2021-09-05 12:11 UTC
![Y2FMGKV)OJ9ZSJ PU`M_`BO](https://user-images.githubusercontent.com/9277529/132126246-724c3689-0742-4d7e-8a64-d674986a3603.png)
If it's like this, it will report an error

**Comment by DaveCTurner** [comment] 2021-09-05 12:39
This is working as intended and not a bug: this field takes IP addresses or DNS hostnames, neither of which may contain a `*` (apart from some [exceptional configs](https://en.wikipedia.org/wiki/Wildcard_DNS_record) which aren't relevant to this case). 

Support for dynamic IP addresses is provided via other mechanisms, for example the [file-based hosts provider](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery-hosts-providers.html#file-based-hosts-provider), so I am closing this. If you have further questions, please ask them on the [discussion forum](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6) and not here.

**Closed by DaveCTurner** 2021-09-05 12:39 UTC
Labels: >bug, needs:triage
