### ISSUE TITLE
[CI] ClusterSettingsIT testUserMetadata failing

### ISSUE THREAD

**Issue by nielsbauman** [elastic/elasticsearch#108996] opened 2024-05-24 08:37 UTC
Assigning to Distributed team due to `"internal:cluster/coordination/commit_state"` pending task.

**Build scan:**
https://gradle-enterprise.elastic.co/s/4cpjhyiuzmbjm/tests/:server:internalClusterTest/org.elasticsearch.cluster.settings.ClusterSettingsIT/testUserMetadata

**Reproduction line:**
```
gradlew ':server:internalClusterTest' --tests "org.elasticsearch.cluster.settings.ClusterSettingsIT.testUserMetadata" -Dtests.seed=FC0849ED15EE831B -Dtests.locale=es-PE -Dtests.timezone=Africa/Juba -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.cluster.settings.ClusterSettingsIT#testUserMetadata`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testUserMetadata'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.cluster.settings.ClusterSettingsIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.AssertionError: All incoming requests on node [node_s3] should have finished. Expected 0 bytes for requests in-flight but got 196 bytes; pending tasks [[{
  "node" : "node_s3",
  "id" : 81,
  "type" : "transport",
  "action" : "internal:cluster/coordination/commit_state",
  "description" : "",
  "start_time" : "2024-05-23T20:41:05.376Z",
  "start_time_in_millis" : 1716496865376,
  "running_time" : "2.6m",
  "running_time_in_nanos" : 161646439500,
  "cancellable" : false,
  "headers" : { }
}]]

  at __randomizedtesting.SeedInfo.seed([FC0849ED15EE831B:53FBF34C8110D0C8]:0)
  at org.elasticsearch.test.InternalTestCluster.lambda$assertRequestsFinished$36(InternalTestCluster.java:2550)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1295)
  at org.elasticsearch.test.InternalTestCluster.assertRequestsFinished(InternalTestCluster.java:2541)
  at org.elasticsearch.test.InternalTestCluster.assertAfterTest(InternalTestCluster.java:2514)
  at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:594)
  at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2332)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1570)

```

**Comment by nielsbauman** [comment] 2024-05-24 08:39
There is an array of failures in that build: https://gradle-enterprise.elastic.co/s/4cpjhyiuzmbjm/tests/overview?outcome=FAILED

**Comment by pxsalehi** [comment] 2024-05-24 09:41
Unless, we're sure the mentioned pending task is the root cause, it might be better to start with the team owning the test (core/infra).

**Comment by mosche** [comment] 2024-06-28 10:13
Looks like very low risk. Also, I tried reproducing but couldn't.

**Comment by ldematte** [comment] 2024-08-06 15:42
This test only failed on that occasion apparently; no other failures in the last 90 days. 
As @nielsbauman pointed out, there are multiple tests failures on that build; it seems that something went wrong with the network in the test cluster; for example:
```
Could not load entry 2e7d55a34672c22173ac56c89e1af038 from remote build cache	
org.gradle.caching.BuildCacheException: Connect to gradle-enterprise.elastic.co:443 [gradle-enterprise.elastic.co/35.188.12.98] failed: Connection refused: no further information
```

I'm going to close it as a infrastructure issue

**Closed** 2024-08-06 15:42 UTC
Labels: :Core/Infra/Settings, >test-failure, Team:Core/Infra, low-risk
