### ISSUE TITLE
7.2.x REST client is not able to consume responses from 6.x

### ISSUE THREAD

**Issue by martin-g** [elastic/elasticsearch#44632] opened 2019-07-19 16:01 UTC
**Elasticsearch version**: 7.2.0

**Plugins installed**: [snapshot-s3]

**JVM version** (`java -version`): 1.8.0_212

**OS version** (`uname -a` if on a Unix-like system): Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

I have an application that reads some data from ES1 which is version 6.2.2, does some work with the data and stores another data in ES2 which I just (tried to) upgraded to 7.2.0.
I've updated my application to use `org.elasticsearch.client:elasticsearch-rest-high-level-client:7.2.0` thinking that it should be able to read responses from 6.x.

The problem is that the response from 6.2.2 does not have a `took` field and the 7.2.x client chokes with:

```
19-07-2019 18:45:29 [Thread-3] ERROR i.s.w.analysis.MasterQueryResolver / - An error occurred during multi search request
java.io.IOException: Unable to parse response body for Response{requestLine=POST /_msearch?typed_keys=true HTTP/1.1, host=http://ES1:9200, response=HTTP/1.1 200 OK}
    at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1467)
    at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1418)
    at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1388)
    at org.elasticsearch.client.RestHighLevelClient.msearch(RestHighLevelClient.java:978)
    ...
    at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.IllegalArgumentException: Required [took]
    at org.elasticsearch.common.xcontent.ConstructingObjectParser$Target.finish(ConstructingObjectParser.java:446)
    at org.elasticsearch.common.xcontent.ConstructingObjectParser$Target.access$000(ConstructingObjectParser.java:350)
    at org.elasticsearch.common.xcontent.ConstructingObjectParser.parse(ConstructingObjectParser.java:169)
    at org.elasticsearch.common.xcontent.ConstructingObjectParser.apply(ConstructingObjectParser.java:161)
    at org.elasticsearch.action.search.MultiSearchResponse.fromXContext(MultiSearchResponse.java:212)
```

Do I assume wrongly that this should be supported scenario ?

**Comment by cbuescher** [comment] 2019-07-19 17:27
Hi @martin-g,

sorry to hear you are having problems updating your application and the client. As our documentation on [client compatibility](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/master/java-rest-high-compatibility.html) states:

> The High Level Client is guaranteed to be able to communicate with any Elasticsearch node running on the same major version and greater or equal minor version. It doesn’t need to be in the same minor version as the Elasticsearch nodes it communicates with, as it is forward compatible meaning that it supports communicating with later versions of Elasticsearch than the one it was developed for. ... The client should always be updated last, once all of the nodes in the cluster have been upgraded to the new major version.

So yes, your scenario is not supported by design. Hope you find the explanation in the docs useful though and don't mind if I close this.

**Closed by cbuescher** 2019-07-19 17:27 UTC

**Comment by martin-g** [comment] 2019-07-19 19:59
It's a pity that this minor timing/debug property breaks my case.
Upgrading the source DB is not an option for us at the moment.
Using old client does not work because of the types removal.

Thanks anyway!

**Comment by martin-g** [comment] 2019-07-20 22:09
I was able to make it work!

Now I use REST client ver. 6.8.1 in the application. I've removed the type from the template mappings and I use `_doc` as a type in the Java APIs.
This way my app successfully reads data from ES1 v.6.2.2, processes it and stores it in ES2 v.7.2.0.
I guess this is not officially supported but I'll take my chances!
