### ISSUE TITLE
[CI] MatchPhraseQueryBuilderTests#testToQuery

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#31061] opened 2018-06-04 10:22 UTC
Seen in a PR build:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request/10979/console

This reproduced also on master:
```
REPRODUCE WITH: ./gradlew :server:test -Dtests.seed=89A368D2AE08BDD7 -Dtests.class=org.elasticsearch.index.query.MatchPhraseQueryBuilderTests -Dtests.method="testToQuery" -Dtests.security.manager=true -Dtests.locale=el -Dtests.timezone=Europe/Belgrade
```

```
ERROR   1.44s | MatchPhraseQueryBuilderTests.testToQuery <<< FAILURES!
   > Throwable #1: java.lang.IllegalArgumentException: Can only use phrase queries on text fields - not on [mapped_date] which is of type [date]
   >    at __randomizedtesting.SeedInfo.seed([89A368D2AE08BDD7:7E586AECDF8B783D]:0)
   >    at org.elasticsearch.index.mapper.MappedFieldType.phraseQuery(MappedFieldType.java:359)
   >    at org.elasticsearch.index.search.MatchQuery$MatchQueryBuilder.analyzePhrase(MatchQuery.java:362)
   >    at org.apache.lucene.util.QueryBuilder.createFieldQuery(QueryBuilder.java:330)
   >    at org.elasticsearch.index.search.MatchQuery$MatchQueryBuilder.createFieldQuery(MatchQuery.java:407)
   >    at org.apache.lucene.util.QueryBuilder.createPhraseQuery(QueryBuilder.java:123)
   >    at org.elasticsearch.index.search.MatchQuery.parse(MatchQuery.java:291)
   >    at org.elasticsearch.index.query.MatchPhraseQueryBuilder.doToQuery(MatchPhraseQueryBuilder.java:183)
   >    at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:98)
   >    at org.elasticsearch.test.AbstractQueryTestCase.testToQuery(AbstractQueryTestCase.java:416)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
   >    at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by cbuescher** [comment] 2018-06-04 10:22
@romseygeek could be related to a resent change of yours? Can you take a look?

**Comment by danielmitterdorfer** [comment] 2018-06-04 15:30
In https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1811/console, we have a failure that appear similar to me as well:

```
14:59:21    > Throwable #1: java.lang.IllegalArgumentException: Can only use phrase queries on text fields - not on [mapped_int] which is of type [integer]
14:59:21    > 	at __randomizedtesting.SeedInfo.seed([1CB5AD72C3F76E4:B52429EA54687064]:0)
14:59:21    > 	at org.elasticsearch.index.mapper.MappedFieldType.phraseQuery(MappedFieldType.java:388)
14:59:21    > 	at org.elasticsearch.index.search.MatchQuery$MatchQueryBuilder.analyzePhrase(MatchQuery.java:364)
14:59:21    > 	at org.apache.lucene.util.QueryBuilder.createFieldQuery(QueryBuilder.java:330)
14:59:21    > 	at org.elasticsearch.index.search.MatchQuery$MatchQueryBuilder.createFieldQuery(MatchQuery.java:409)
14:59:21    > 	at org.apache.lucene.util.QueryBuilder.createPhraseQuery(QueryBuilder.java:123)
14:59:21    > 	at org.elasticsearch.index.search.MatchQuery.parse(MatchQuery.java:293)
14:59:21    > 	at org.elasticsearch.index.search.MultiMatchQuery.parseAndApply(MultiMatchQuery.java:60)
14:59:21    > 	at org.elasticsearch.index.search.MultiMatchQuery.access$100(MultiMatchQuery.java:47)
14:59:21    > 	at org.elasticsearch.index.search.MultiMatchQuery$QueryBuilder.parseGroup(MultiMatchQuery.java:117)
14:59:21    > 	at org.elasticsearch.index.search.MultiMatchQuery$QueryBuilder.buildGroupedQueries(MultiMatchQuery.java:108)
14:59:21    > 	at org.elasticsearch.index.search.MultiMatchQuery.parse(MultiMatchQuery.java:89)
14:59:21    > 	at org.elasticsearch.index.query.MultiMatchQueryBuilder.doToQuery(MultiMatchQueryBuilder.java:825)
14:59:21    > 	at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:98)
14:59:21    > 	at org.elasticsearch.test.AbstractQueryTestCase.testMustRewrite(AbstractQueryTestCase.java:769)
14:59:21    > 	at java.lang.Thread.run(Thread.java:748)
```

Reproduction line:

```
./gradlew :server:test -Dtests.seed=1CB5AD72C3F76E4 -Dtests.class=org.elasticsearch.index.query.MultiMatchQueryBuilderTests -Dtests.method="testMustRewrite" -Dtests.security.manager=true -Dtests.locale=mt -Dtests.timezone=Asia/Oral
```

The test failure did not reproduce locally for me (hence I did not mute the test for now).

**Comment by romseygeek** [comment] 2018-06-04 15:56
It's part of the same issue, and will be fixed by #31060

**Closed** 2018-06-04 18:13 UTC
Labels: :Search/Search, >test-failure, v6.4.0, v7.0.0

**Comment by mayya-sharipova** [comment] 2018-06-05 20:23
@romseygeek  Alan, has the change been backported to 6.x? We have a recent failure of this test on 6.x multijob-windows-compatibility (although  it is NOT reproducible on my machine with 6.x):

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-windows-compatibility/1104/console

REPRODUCE WITH: gradlew :server:test \
  -Dtests.seed=27D2F223CA62DC0D \
  -Dtests.class=org.elasticsearch.index.query.MatchPhrasePrefixQueryBuilderTests \
  -Dtests.method="testMustRewrite" \
  -Dtests.security.manager=true \
  -Dtests.locale=nl-BE \
  -Dtests.timezone=Atlantic/Madeira

REPRODUCE WITH: gradlew :server:test \
  -Dtests.seed=27D2F223CA62DC0D \
  -Dtests.class=org.elasticsearch.index.query.MatchPhraseQueryBuilderTests \
  -Dtests.method="testMustRewrite" \
  -Dtests.security.manager=true \
  -Dtests.locale=is \
  -Dtests.timezone=Africa/Bujumbura

Throwable #1: ElasticsearchStatusException[Test likely fails due to insufficient disk space on test machine, please free up space.]; nested: ElasticsearchStatusException[Cannot run forecast: Forecast cannot be executed as models exceed internal memory limit and available disk space is insufficient];
   > 	at __randomizedtesting.SeedInfo.seed([9D4823F36C890ECA:D2989DA905F7077A]:0)
   > 	at org.elasticsearch.xpack.ml.integration.ForecastIT.testOverflowToDisk(ForecastIT.java:258)
   > 	at java.lang.Thread.run(Thread.java:748)

**Comment by romseygeek** [comment] 2018-06-06 08:17
@mayya-sharipova the backport is in #31072, still waiting for a green CI on that one
