### ISSUE TITLE
[ML] MachineLearningIT testDeleteTrainedModel failure

### ISSUE THREAD

**Issue by albertzaharovits** [elastic/elasticsearch#59788] opened 2020-07-17 14:42 UTC
https://gradle-enterprise.elastic.co/s/665eciimpzxny

This has only failed once : https://gradle-enterprise.elastic.co/scans/tests?list.size=50&list.sortColumn=startTime&list.sortOrder=desc&search.buildToolType=gradle&search.buildToolType=maven&search.relativeStartTime=P28D&search.tags=CI&search.tags=not:pull-request&search.timeZoneId=Europe/Bucharest&tests.container=org.elasticsearch.client.MachineLearningIT&tests.sortField=FAILED&tests.test=testDeleteTrainedModel&tests.unstableOnly=true

```
org.elasticsearch.client.MachineLearningIT > testDeleteTrainedModel FAILED |  
-- | --
  | org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=search_phase_execution_exception, reason=Partial shards failure (1 shards unavailable)] |  
  | at __randomizedtesting.SeedInfo.seed([64FD9D6AD3C85C13:1B1C1B6EAABAE19E]:0) |  
  | at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:187) |  
  | at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1892) |  
  | at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1869) |  
  | at org.elasticsearch.client.RestHighLevelClient$1.onFailure(RestHighLevelClient.java:1785) |  
  | at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:617) |  
  | at org.elasticsearch.client.RestClient$1.completed(RestClient.java:358) |  
  | at org.elasticsearch.client.RestClient$1.completed(RestClient.java:346) |  
  | at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:122) |  
  | at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:181) |  
  | at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:448) |  
  | at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:338) |  
  | at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265) |  
  | at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81) |  
  | at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39) |  
  | at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114) |  
  | at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) |  
  | at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) |  
  | at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) |  
  | at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) |  
  | at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) |  
  | at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) |  
  | at java.base/java.lang.Thread.run(Thread.java:834)
```
Possible cause:
```

ERROR][o.e.x.i.IndexLifecycleRunner] [asyncIntegTest-0] policy [my_policy] for index [my_index] failed on step [{"phase":"warm","action":"shrink","name":"shrink"}]. Moving to ERROR step |  
-- | --
  | »  java.lang.IllegalArgumentException: the number of target shards [3] must be less that the number of source shards [2] |  
  | »  	at org.elasticsearch.cluster.metadata.IndexMetadata.selectShrinkShards(IndexMetadata.java:1635) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.action.admin.indices.shrink.TransportResizeAction.prepareCreateIndexRequest(TransportResizeAction.java:149) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.action.admin.indices.shrink.TransportResizeAction.lambda$masterOperation$2(TransportResizeAction.java:109) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:113) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.client.node.NodeClient.lambda$executeLocally$0(NodeClient.java:91) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:175) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:169) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$AsyncAction.onCompletion(TransportBroadcastByNodeAction.java:380) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$AsyncAction.onNodeResponse(TransportBroadcastByNodeAction.java:349) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$AsyncAction$1.handleResponse(TransportBroadcastByNodeAction.java:321) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$AsyncAction$1.handleResponse(TransportBroadcastByNodeAction.java:313) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.transport.TransportService$6.handleResponse(TransportService.java:573) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1102) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1180) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1160) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:52) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$BroadcastByNodeTransportRequestHandler.messageReceived(TransportBroadcastByNodeAction.java:414) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$BroadcastByNodeTransportRequestHandler.messageReceived(TransportBroadcastByNodeAction.java:388) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(SecurityServerTransportInterceptor.java:228) [x-pack-security-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:178) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.lambda$messageReceived$0(SecurityServerTransportInterceptor.java:277) [x-pack-security-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$runRequestInterceptors$15(AuthorizationService.java:353) [x-pack-security-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.common.util.concurrent.ListenableFuture$1.doRun(ListenableFuture.java:112) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  

```

I'm not going to mute at this time.

**Comment by benwtrent** [comment] 2020-12-03 18:44
Digging into it. This test has [failed twice in the past 6 months](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-6M,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:e58bf320-7efd-11e8-bf69-63c8ef516157,key:branch,negate:!t,params:!(pull-request-1,pull-request-2,pull-request),type:phrases,value:'pull-request-1,%20pull-request-2,%20pull-request'),query:(bool:(minimum_should_match:1,should:!((match_phrase:(branch:pull-request-1)),(match_phrase:(branch:pull-request-2)),(match_phrase:(branch:pull-request))))))),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testDeleteTrainedModel),sort:!(time,desc)))

The stack trace in the latest failure shows that it failed on the DeleteByQuery call. Since the previous GET calls worked ok, I am thinking it was the `.ml-stats` index that was in the middle of initializing due to another test creating it (since this test doesn't touch that index).

We have no mechanism right now to determine if a search failure is due to a brand new index being created and still initializing or if there is really a shard failure.

**Comment by benwtrent** [comment] 2021-02-25 13:04
This test has not failed again since my previous comment.

Closing.

Per a version of Murphy's law, closing the issue is a good way to force the test to fail again. We shall see.

**Closed by benwtrent** 2021-02-25 13:04 UTC
Labels: :ml, >test-failure
