### ISSUE TITLE
ES|QL: subsequent count(*) are incorrectly pruned 

### ISSUE THREAD

**Issue by luigidellaquila** [elastic/elasticsearch#102425] opened 2023-11-21 17:05 UTC
```
from employees | stats  a = count(*) | stats  c = count(*)
```

```
       c       
---------------
100            
```

It should be `1`, because the first `stats` produces only one row (no `by` clause)

The problem is most likely due to a bug in `PruneColumns` optimization rule:

```
[2023-11-21T18:02:26,025][TRACE][o.e.x.e.o.LogicalPlanOptimizer] [runTask-0] Rule optimizer.LogicalPlanOptimizer$PruneColumns applied
Limit[500[INTEGER]]                                                                = Limit[500[INTEGER]]
\_Aggregate[[],[COUNT([2a][KEYWORD]) AS c]]                                        = \_Aggregate[[],[COUNT([2a][KEYWORD]) AS c]]
  \_Aggregate[[],[COUNT([2a][KEYWORD]) AS a]]                                      !   \_EsRelation[employees][avg_worked_seconds{f}#102, birth_date{f}#103, emp_n..]
    \_EsRelation[employees][avg_worked_seconds{f}#102, birth_date{f}#103, emp_n..] ! 
```

**Comment by gurudykim** [comment] 2023-11-28 07:54
Hello, I am a student who is practicing ES.
It's because I've reproduced this issue
Can you tell me how you set it up?
Also, if you tell me where you used that query statement
I'd really appreciate it.

**Comment by alex-spies** [comment] 2024-04-04 08:49
I just checked, this doesn't occur anymore with https://github.com/elastic/elasticsearch/pull/106673. I'll add a test to that PR.

**Comment by alex-spies** [comment] 2024-04-04 14:33
Fixed by https://github.com/elastic/elasticsearch/pull/106673

**Closed by alex-spies** 2024-04-04 14:33 UTC
Labels: >bug, Team:Analytics, :Analytics/ES|QL
