### ISSUE TITLE
elasticsearch rollup: how the rolled response and live response combine

### ISSUE THREAD

**Issue by benjam1n77** [elastic/elasticsearch#58638] opened 2020-06-28 10:15 UTC
When I use _rollup_search api, the searchRequest become into a multisearchRequest including an original SearchRequest and a rewritten SearchRequest, and I get a multisearchResponse including a live Response and a rolled Response. But I am a little confused of how the live Response and rolled Response combine. For example, 

the live response:
```
{
  "timeline": {
    "buckets": [
      {
        "key_as_string": "2018-01-23T20:00:00.000Z",
        "key": 1516737600000,
        "nodes": {
          "doc_count_error_upper_bound": 0,
          "sum_other_doc_count": 0,
          "buckets": [
            {
              "key": "a",
              "doc_count": 2,
              "max_temperature": {
                "value": 620.0
              },
              "avg_voltage": {
                "value": 6.349999904632568
              }
            }
          ]
        }
      }
    ]
   }
}
```

the rolled response：
```
{
  "timeline": {
    "buckets": [
      {
        "key_as_string": "2018-01-23T20:00:00.000Z",
        "key": 1516737600000,
        "nodes": {
          "doc_count_error_upper_bound": 0,
          "sum_other_doc_count": 0,
          "buckets": [
            {
              "key": "b",
              "doc_count": 1,
              "max_temperature": {
                "value": 410.0
              },
              "avg_voltage": {
                "value": 5.5
              }
            }
          ]
        }
      }
    ]
  }
}
```

what I expect  of  the combined result：
```
{
  "timeline": {
    "buckets": [
      {
        "key_as_string": "2018-01-23T20:00:00.000Z",
        "key": 1516737600000,
        "nodes": {
          "doc_count_error_upper_bound": 0,
          "sum_other_doc_count": 0,
          "buckets": [
            {
              "key": "a",
              "doc_count": 2,
              "max_temperature": {
                "value": 620.0
              },
              "avg_voltage": {
                "value": 6.349999904632568
              }
            },
            {
              "key": "b",
              "doc_count": 1,
              "max_temperature": {
                "value": 410.0
              },
              "avg_voltage": {
                "value": 5.5
              }
            }
          ]
        }
      }
    ]
  }
}
```

but the fact is :
```
{
  "timeline": {
    "buckets": [
      {
        "key_as_string": "2018-01-23T20:00:00.000Z",
        "key": 1516737600000,
        "nodes": {
          "doc_count_error_upper_bound": 0,
          "sum_other_doc_count": 0,
          "buckets": [
            {
              "key": "a",
              "doc_count": 2,
              "max_temperature": {
                "value": 620.0
              },
              "avg_voltage": {
                "value": 6.349999904632568
              }
            }
          ]
        }
      }
    ]
  }
}
```

The bucket in rolled response is overlapped by it in live response in a unresonable way : outer layer bucket is overlapped, not inner layer bucket. Will you reconsider the design of rollup in the next version?

**Comment by csoulios** [comment] 2020-07-01 15:48
Thanks for submitting this issue. 

Rollups is currently being refactored and the `_rollup_search` endpoint will be dropped when the new implementation is released. Therefore, the whole logic of collecting and merging buckets is going to change.

This ticket is a duplicate of https://github.com/elastic/elasticsearch/issues/48005

**Closed by csoulios** 2020-07-01 15:48 UTC
Labels: :Analytics/Rollup, >enhancement
