### ISSUE TITLE
:distribution:packages:buildOssDeb failed (No such file or directory)

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#69784] opened 2021-03-02 10:42 UTC
**Build scan**: https://gradle-enterprise.elastic.co/s/pqrwdjttdutv2

**Repro line**: None given, I tried `./gradlew :distribution:packages:buildOssDeb`

**Reproduces locally?**: No

**Applicable branches**: Only seen on 7.x

**Failure history**: First time in 90 days [according to Gradle Enterprise](https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=all_failures&failures.failureMessage=Execution%20failed%20for%20task%20%27:distribution:packages:buildOssDeb%27.%0A%3E%20Can%27t%20build%20debian%20package%20/dev/shm/elastic%2Belasticsearch%2B7.x%2Bpackaging-vagrant-matrix/OS/centos-6/nodes/metal/distribution/packages/oss-deb/build/distributions/elasticsearch-oss-7.13.0-SNAPSHOT-amd64.deb&search.relativeStartTime=P90D&search.timeZoneId=Europe/London)

**Failure excerpt**:

```
Can't build debian package /dev/shm/elastic+elasticsearch+7.x+packaging-vagrant-matrix/OS/centos-6/nodes/metal/distribution/packages/oss-deb/build/distributions/elasticsearch-oss-7.13.0-SNAPSHOT-amd64.deb
> Failed to create debian package /dev/shm/elastic+elasticsearch+7.x+packaging-vagrant-matrix/OS/centos-6/nodes/metal/distribution/packages/oss-deb/build/distributions/elasticsearch-oss-7.13.0-SNAPSHOT-amd64.deb
  > Could not create deb package
    > /dev/shm/elastic+elasticsearch+7.x+packaging-vagrant-matrix/OS/centos-6/nodes/metal/distribution/packages/build/packaging/oss-deb/copyright (No such file or directory)
```

**Comment by mark-vieira** [comment] 2021-03-02 23:59
Closing this as a duplicate of https://github.com/elastic/elasticsearch/issues/69504

**Closed by mark-vieira** 2021-03-02 23:59 UTC
Labels: :Delivery/Packaging, >test-failure, Team:Delivery
