### ISSUE TITLE
es 5.3.1 issue

### ISSUE THREAD

**Issue by ninadvps** [elastic/elasticsearch#25411] opened 2017-06-26 23:23 UTC
**Describe the feature**:

**5.3.1**:

**Plugins installed**: []

**JVM version** (`java -version`):
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux vps-cl-0 4.2.0-42-generic #49~14.04.1-Ubuntu SMP Wed Jun 29 20:22:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
Elastic search seems to have some corruption... and doesnt allow you to start the cluster again once it goes in this state.... we rebooted even the machines.

Caused by: org.apache.lucene.store.LockObtainFailedException: Lock held by this virtual machine: /data/nodes/0/indices/b245vxRiSk6wO_XMgEvf2A/1/index/write.lock

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.  create a 3 node cluster and push around 80GB of data

2. use this config elasticsearch.yml .... 

cluster.name: icecluster
node.name: icecluster-10.10.20.7
node.master: true
node.data: true
path.data: /data
http.port: 9200
network.bind_host: '0.0.0.0'
network.publish_host: 10.10.20.7
discovery.zen.ping.unicast.hosts: [10.10.20.7,10.10.20.8,10.10.20.9]
discovery.zen.minimum_master_nodes: 2
discovery.zen.no_master_block: write
thread_pool:
    bulk:
     queue_size: 1000000
    index:
     queue_size: 1000000```

 3. Jvm 4 gb xms and 4 gb xmx

**Provide logs (if relevant)**:

[2017-06-26T15:29:56,593][WARN ][o.e.g.GatewayAllocator$InternalReplicaShardAllocator] [icecluster-10.10.20.7] [mldata_06-25-2017][1]: failed to list shard for shard_store on node [7IPGCbvjR7KlE8uK9xcuqw]
org.elasticsearch.action.FailedNodeException: Failed node [7IPGCbvjR7KlE8uK9xcuqw]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.onFailure(TransportNodesAction.java:246) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.access$200(TransportNodesAction.java:160) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$1.handleException(TransportNodesAction.java:218) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1032) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1134) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1112) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.transport.TransportService$7.onFailure(TransportService.java:629) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:623) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39) ~[elasticsearch-5.3.1.jar:5.3.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: org.elasticsearch.transport.RemoteTransportException: [icecluster-10.10.20.7][10.10.20.7:9300][internal:cluster/nodes/indices/shard/store[n]]
Caused by: org.elasticsearch.ElasticsearchException: Failed to list store metadata for shard [[mldata_06-25-2017][1]]
        at org.elasticsearch.indices.store.TransportNodesListShardStoreMetaData.nodeOperation(TransportNodesListShardStoreMetaData.java:114) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.indices.store.TransportNodesListShardStoreMetaData.nodeOperation(TransportNodesListShardStoreMetaData.java:64) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.action.support.nodes.TransportNodesAction.nodeOperation(TransportNodesAction.java:145) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:269) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:265) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:618) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.3.1.jar:5.3.1]
        ... 3 more
Caused by: org.apache.lucene.store.LockObtainFailedException: Lock held by this virtual machine: /data/nodes/0/indices/b245vxRiSk6wO_XMgEvf2A/1/index/write.lock
        at org.apache.lucene.store.NativeFSLockFactory.obtainFSLock(NativeFSLockFactory.java:127) ~[lucene-core-6.4.2.jar:6.4.2 34a975ca3d4bd7fa121340e5bcbf165929e0542f - ishan - 2017-03-01 23:23:13]
        at org.apache.lucene.store.FSLockFactory.obtainLock(FSLockFactory.java:41) ~[lucene-core-6.4.2.jar:6.4.2 34a975ca3d4bd7fa121340e5bcbf165929e0542f - ishan - 2017-03-01 23:23:13]
        at org.apache.lucene.store.BaseDirectory.obtainLock(BaseDirectory.java:45) ~[lucene-core-6.4.2.jar:6.4.2 34a975ca3d4bd7fa121340e5bcbf165929e0542f - ishan - 2017-03-01 23:23:13]
        at org.apache.lucene.store.FilterDirectory.obtainLock(FilterDirectory.java:104) ~[lucene-core-6.4.2.jar:6.4.2 34a975ca3d4bd7fa121340e5bcbf165929e0542f - ishan - 2017-03-01 23:23:13]
        at org.apache.lucene.store.FilterDirectory.obtainLock(FilterDirectory.java:104) ~[lucene-core-6.4.2.jar:6.4.2 34a975ca3d4bd7fa121340e5bcbf165929e0542f - ishan - 2017-03-01 23:23:13]
        at org.elasticsearch.index.shard.IndexShard.snapshotStoreMetadata(IndexShard.java:869) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.indices.store.TransportNodesListShardStoreMetaData.listStoreMetaData(TransportNodesListShardStoreMetaData.java:128) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.indices.store.TransportNodesListShardStoreMetaData.nodeOperation(TransportNodesListShardStoreMetaData.java:112) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.indices.store.TransportNodesListShardStoreMetaData.nodeOperation(TransportNodesListShardStoreMetaData.java:64) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.action.support.nodes.TransportNodesAction.nodeOperation(TransportNodesAction.java:145) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:269) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:265) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:618) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.3.1.jar:5.3.1]
        ... 3 more
[2017-06-26T15:41:05,539][INFO ][o.e.n.Node               ] [icecluster-10.10.20.7] stopping ...
[2017-06-26T15:41:05,677][WARN ][o.e.i.c.IndicesClusterStateService] [icecluster-10.10.20.7] [[sensor_06-25-2017][0]] marking and sending shard failed due to [failed recovery]
org.elasticsearch.indices.recovery.RecoveryFailedException: [sensor_06-25-2017][0]: Recovery failed from {icecluster-10.10.20.8}{v1lXGgVpRYuNpLAwTJcWow}{_grarlZmRvaHgZg-xwO0Dw}{10.10.20.8}{10.10.20.8:9300} into {icecluster-10.10.20.7}{7IPGCbvjR7KlE8uK9xcuqw}{0CcdIIuXTnetmxCWxeq0wA}{10.10.20.7}{10.10.20.7:9300}
        at org.elasticsearch.indices.recovery.PeerRecoveryTargetService.doRecovery(PeerRecoveryTargetService.java:313) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.indices.recovery.PeerRecoveryTargetService.access$900(PeerRecoveryTargetService.java:73) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$RecoveryRunner.doRun(PeerRecoveryTargetService.java:555) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.3.1.jar:5.3.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: org.elasticsearch.transport.TransportException: transport stopped, action: internal:index/shard/recovery/start_recovery
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:245) ~[elasticsearch-5.3.1.jar:5.3.1]
        ... 5 more
[2017-06-26T15:41:05,688][WARN ][o.e.c.a.s.ShardStateAction] [icecluster-10.10.20.7] [sensor_06-25-2017][0] unexpected failure while sending request [internal:cluster/shard/failure] to [{icecluster-10.10.20.7}{7IPGCbvjR7KlE8uK9xcuqw}{0CcdIIuXTnetmxCWxeq0wA}{10.10.20.7}{10.10.20.7:9300}] for shard entry [shard id [[sensor_06-25-2017][0]], allocation id [uRcRYNU-SxitdhYEfbvJrw], primary term [0], message [failed recovery], failure [RecoveryFailedException[[sensor_06-25-2017][0]: Recovery failed from {icecluster-10.10.20.8}{v1lXGgVpRYuNpLAwTJcWow}{_grarlZmRvaHgZg-xwO0Dw}{10.10.20.8}{10.10.20.8:9300} into {icecluster-10.10.20.7}{7IPGCbvjR7KlE8uK9xcuqw}{0CcdIIuXTnetmxCWxeq0wA}{10.10.20.7}{10.10.20.7:9300}]; nested: TransportException[transport stopped, action: internal:index/shard/recovery/start_recovery]; ]]
org.elasticsearch.transport.SendRequestTransportException: [icecluster-10.10.20.7][10.10.20.7:9300][internal:cluster/shard/failure]
        at org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:572) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:495) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:470) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.cluster.action.shard.ShardStateAction.sendShardAction(ShardStateAction.java:104) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.cluster.action.shard.ShardStateAction.shardFailed(ShardStateAction.java:169) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.cluster.action.shard.ShardStateAction.localShardFailed(ShardStateAction.java:163) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.sendFailShard(IndicesClusterStateService.java:681) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.failAndRemoveShard(IndicesClusterStateService.java:671) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.handleRecoveryFailure(IndicesClusterStateService.java:648) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.access$800(IndicesClusterStateService.java:91) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.indices.cluster.IndicesClusterStateService$RecoveryListener.onRecoveryFailure(IndicesClusterStateService.java:642) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.indices.recovery.RecoveryTarget.notifyListener(RecoveryTarget.java:259) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.indices.recovery.RecoveryTarget.fail(RecoveryTarget.java:246) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.indices.recovery.RecoveriesCollection.failRecovery(RecoveriesCollection.java:183) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.indices.recovery.PeerRecoveryTargetService.doRecovery(PeerRecoveryTargetService.java:313) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.indices.recovery.PeerRecoveryTargetService.access$900(PeerRecoveryTargetService.java:73) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$RecoveryRunner.doRun(PeerRecoveryTargetService.java:555) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.3.1.jar:5.3.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: org.elasticsearch.transport.TransportException: TransportService is closed stopped can't send request
        at org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:556) ~[elasticsearch-5.3.1.jar:5.3.1]
        ... 21 more
[2017-06-26T15:41:05,779][INFO ][o.e.n.Node               ] [icecluster-10.10.20.7] stopped
[2017-06-26T15:41:05,779][INFO ][o.e.n.Node               ] [icecluster-10.10.20.7] closing ...
[2017-06-26T15:41:05,845][INFO ][o.e.n.Node               ] [icecluster-10.10.20.7] closed
[2017-06-26T15:41:39,043][INFO ][o.e.n.Node               ] [icecluster-10.10.20.7] initializing ...
[2017-06-26T15:41:39,186][INFO ][o.e.e.NodeEnvironment    ] [icecluster-10.10.20.7] using [1] data paths, mounts [[/data (/dev/sdb1)]], net usable_space [789.5gb], net total_space [916.7gb], spins? [possibly], types [ext4]
[2017-06-26T15:41:39,186][INFO ][o.e.e.NodeEnvironment    ] [icecluster-10.10.20.7] heap size [3.9gb], compressed ordinary object pointers [true]
[2017-06-26T15:41:39,732][INFO ][o.e.n.Node               ] [icecluster-10.10.20.7] node name [icecluster-10.10.20.7], node ID [7IPGCbvjR7KlE8uK9xcuqw]

**Comment by tvernum** [comment] 2017-06-26 23:49
Please ask this question on our [discuss forum](https://discuss.elastic.co/) where we can provide better support.

Elastic uses GitHub issues for confirmed bugs and feature requests which have been discussed on the forums. While it is possible that your data corruption is caused by a bug in Elasticsearch, it is more effective for us and for you if the diagnosis takes place on the forum, and then a GitHub issue is raised if and when we confirm the nature of the bug.

I'm going to close this issue for now, but we can reopen it at a later date if we find that there is a bug that needs to be fixed.

Thank you.

**Closed by tvernum** 2017-06-26 23:49 UTC
