### ISSUE TITLE
Cannot find empty fields ("") processed by stempel (polish analyser) using exists/missing query

### ISSUE THREAD

**Issue by rkoc** [elastic/elasticsearch#22645] opened 2017-01-16 20:24 UTC
**Elasticsearch version**: 2.3.4

Cannot find empty fields ("") processed by stempel (polish analyser) using exists/missing query. I have no problems with other 'standard' or 'not_anlyzed' types.

**Comment by clintongormley** [comment] 2017-01-17 11:23
Please provide a short but complete curl reproduction of the issue, including creating the index, specifying the mappings, indexing the docs, searching, and explain what you expected to see and what you actually see.  It will greatly help us to understand what the problem is.

**Comment by jsgandalf** [comment] 2017-03-28 23:02
I'm also having the same issues... I'm trying to find empty values, and have set my index mapping to keyword (which technically does not analyze so it should pick up on the "" values)

```
"query": {
      "term": { "MY_FIELD_TO_SEARCH": "" }
}
```

**Comment by colings86** [comment] 2017-03-31 14:42
@jsgandalf could you provide the information @clintongormley asked for above as it will greatly help in recreating (and therefore understanding and solving) this issue you are seeing

**Comment by jsgandalf** [comment] 2017-03-31 17:36
Actually, when I reindex my database and rerun the query. It worked =)

The problem was that my field was type: text and NOT a keyword. Changed the index to keyword and reindexed:

```
curl -X PUT https://username:password@host.io:9200/mycoolindex

curl -X PUT https://user:pass@host.io:9200/mycoolindex/_mapping/mycooltype -d '{
  "properties": {
			    "MY_FIELD_TO_SEARCH": {
						"type": "keyword"
					},
}'

curl -X PUT https://username:password@host.io:9200/_reindex -d '{
  "source": {
    "index": "oldindex"
  },
  "dest": {
    "index": "mycoolindex"
  }
}'
```

I hope this helps someone who was as stuck as I was getting rid of those empty values.

**Comment by javanna** [comment] 2017-04-18 13:09
thanks for getting back to us. Closing.

**Closed by javanna** 2017-04-18 13:09 UTC
Labels: :Plugin Analysis Stempel, feedback_needed
