### ISSUE TITLE
RegressionIT#testSingleNumericFeatureAndMixedTrainingAndNonTrainingRows fails because 100 training docs had no feature importance

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#60340] opened 2020-07-28 20:29 UTC
Seems to fail on a regular basis, although it did not reproduce for me locally.  Going to push a mute.

- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+EAR/126/console
- https://gradle-enterprise.elastic.co/s/rvoq6sc762wok

```
./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.RegressionIT.testSingleNumericFeatureAndMixedTrainingAndNonTrainingRows" \
  -Dtests.seed=1D62E4C4D315190 \
  -Dtests.security.manager=true \
  -Dtests.locale=es-PY \
  -Dtests.timezone=Europe/Andorra \
  -Druntime.java=11
```
```
java.lang.AssertionError: There were [100] training docs and [0] test docs with empty feature importance from 350 hits.
[{@timestamp=1595964421192, feature=2.0, ml__id_copy=gzjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421192, feature=2.0, ml__id_copy=pzjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421192, feature=2.0, ml__id_copy=rTjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421192, feature=2.0, ml__id_copy=vzjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=9TjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=-DjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=_jjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=ATjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=EDjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=FjjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=IjjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=OjjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=QDjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=QzjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421194, feature=2.0, ml__id_copy=cDjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421194, feature=2.0, ml__id_copy=nTjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421192, feature=2.0, ml__id_copy=hjjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421192, feature=2.0, ml__id_copy=kjjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421192, feature=2.0, ml__id_copy=vDjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421192, feature=2.0, ml__id_copy=zjjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=6TjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=DTjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=HDjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=VTjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=WDjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=YTjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421194, feature=2.0, ml__id_copy=jjjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421194, feature=2.0, ml__id_copy=kTjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421194, feature=2.0, ml__id_copy=pjjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421192, feature=2.0, ml__id_copy=tjjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421192, feature=2.0, ml__id_copy=3TjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=4DjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=CjjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=HzjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=KzjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=TDjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421194, feature=2.0, ml__id_copy=czjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421194, feature=2.0, ml__id_copy=fDjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421194, feature=2.0, ml__id_copy=iDjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421194, feature=2.0, ml__id_copy=izjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421194, feature=2.0, ml__id_copy=lzjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421194, feature=2.0, ml__id_copy=mjjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421192, feature=2.0, ml__id_copy=iTjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421192, feature=2.0, ml__id_copy=jDjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421192, feature=2.0, ml__id_copy=jzjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421192, feature=2.0, ml__id_copy=lTjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421192, feature=2.0, ml__id_copy=njjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421192, feature=2.0, ml__id_copy=oTjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421192, feature=2.0, ml__id_copy=qjjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421192, feature=2.0, ml__id_copy=uTjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421192, feature=2.0, ml__id_copy=xTjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421192, feature=2.0, ml__id_copy=yDjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421192, feature=2.0, ml__id_copy=yzjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421192, feature=2.0, ml__id_copy=0TjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421192, feature=2.0, ml__id_copy=1DjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421192, feature=2.0, ml__id_copy=1zjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421192, feature=2.0, ml__id_copy=2jjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=4zjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=8jjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=GTjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=JTjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=NzjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=TzjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=ZDjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421194, feature=2.0, ml__id_copy=bTjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421194, feature=2.0, ml__id_copy=eTjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421194, feature=2.0, ml__id_copy=fzjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421194, feature=2.0, ml__id_copy=gjjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421194, feature=2.0, ml__id_copy=hTjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421194, feature=2.0, ml__id_copy=lDjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421194, feature=2.0, ml__id_copy=ozjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421192, feature=2.0, ml__id_copy=gDjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421192, feature=2.0, ml__id_copy=mDjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421192, feature=2.0, ml__id_copy=szjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421192, feature=2.0, ml__id_copy=wjjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=7DjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=BDjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=BzjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=LjjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=MTjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=NDjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=PTjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=STjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=UjjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=ZzjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421194, feature=2.0, ml__id_copy=ajjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421192, feature=2.0, ml__id_copy=fTjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421192, feature=2.0, ml__id_copy=mzjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421192, feature=2.0, ml__id_copy=pDjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421192, feature=2.0, ml__id_copy=sDjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=5jjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=7zjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=-zjklnMBN2feomY2dCVL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=EzjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=KDjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=RjjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=WzjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421193, feature=2.0, ml__id_copy=XjjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421194, feature=2.0, ml__id_copy=djjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}, {@timestamp=1595964421194, feature=2.0, ml__id_copy=oDjklnMBN2feomY2dCZL, discrete-feature=20, variable=20.0, ml={variable_prediction=20.0, feature_importance=[], is_training=true}}]
Expected: <0>
     but: was <100>
	at __randomizedtesting.SeedInfo.seed([1D62E4C4D315190:15C28BC501C75D99]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.elasticsearch.xpack.ml.integration.RegressionIT.testSingleNumericFeatureAndMixedTrainingAndNonTrainingRows(RegressionIT.java:133)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by davidkyle** [comment] 2020-07-29 08:13
Closing as a duplicate of #59413

Thanks for raising this @polyfractal I was waiting for the failure as it has some extra logging in it.

**Closed by davidkyle** 2020-07-29 08:13 UTC
Labels: :ml, >test-failure

**Comment by polyfractal** [comment] 2020-07-29 12:57
Whoops, missed that one when looking!  :+1:
