### ISSUE TITLE
Delete by Query failed + Primary/Replica shards out of sync

### ISSUE THREAD

**Issue by aewhite** [elastic/elasticsearch#19692] opened 2016-07-29 19:56 UTC
Elasticsearch 2.3.2

Problem manifests when we run a pretty simple delete-by-query. Here is the response body

```
{
  "took": 1001,
  "timed_out": false,
  "_indices": {
    "_all": {
      "found": 57,
      "deleted": 0,
      "missing": 0,
      "failed": 57
    },
    "index-name": {
      "found": 57,
      "deleted": 0,
      "missing": 0,
      "failed": 57
    }
  },
  "failures": []
}
```

Nothing in the logs indicate a failure. Issuing a _search with the same query yields those 57 document *sometimes*. Ie, the documents are only found on the replica and never the primary. Checking the document delete count on the _cat endpoints yields a 57 document discrepancy too. 

So far, the only solution has been to cancel the allocation of the replicated shared via the _reroute API and let ES rebuild the replica. 

There is a possibility that this is unrelated to delete-by-query directly and it is only surfacing another issue. The general step we take before we realize there a problem is...

1. Switch an alias from pointing to index A to index B
2. Use the reindex API to move documents from A to B
3. Use delete-by-query to purge all moved documents from A

If (1) or (2) have an issue then maybe (3) just surfaces it. 

Some observations: 

* This has happened several times and it's pretty consistent. Probably about 25% of all big move operations
* It's always the replicas that have the extra documents
* We tag the index times on the documents and I never saw clustering on the left-behind documents
* Rebuilding the replica has always worked as a workaround
* When we delete in batch, we have tried both small and large sizes with the same results
* The number of out-of-sync documents is always small (<100)

**Comment by nik9000** [comment] 2016-07-29 21:13
I don't know what is up for sure. @tlrx might know more so I've pinged him.

I will say that step 3 of your process is generally a bad idea - it is much much much more efficient to delete the a whole index rather than to delete all of the documents from it. On the other hand if you are only removing parts of it, well, know that that isn't a particularly efficient operation. If you are ok with that then cool.

**Comment by aewhite** [comment] 2016-07-29 21:54
To be clear, we are not using delete-by-query to delete all documents in an index. The point of this process is to move related documents from a large index into a dedicated index.

**Comment by bleskes** [comment] 2016-07-31 10:51
@aewhite these things can be very difficult to trace down and depend on very small details. Can chance you can give us a concrete reproduction or at the very least the exact API calls you used?

**Comment by aewhite** [comment] 2016-07-31 11:54
I have not been able replicate it outside of our production environment but I suspect the volume in that environment plays a big role. We are ingesting thousands of documents per second (sometime up to 100k/s). And when we do these document migrations, the volume is in the millions. 

As to the exact delete-by-query, it is built using the following code:

```
        final DeleteByQueryRequestBuilder deleteByQueryRequestBuilder = DeleteByQueryAction.INSTANCE
                .newRequestBuilder(client.getRawClient())
                .setIndices(indexName)
                .setTypes("post", "analytic")
                .setQuery(QueryBuilders.boolQuery()
                                       .must(QueryBuilders.termQuery("internal.container_id", containerId)));

        deleteByQueryRequestBuilder.request().size(DELETE_BY_QUERY_BATCH_SIZE);

        final DeleteByQueryResponse deleteByQueryResponse = deleteByQueryRequestBuilder
                .execute()
                .actionGet();
```

The steps describe for (1) and (2) above are a bit more involved code-wise but the end calls to ES are very basic. Aliases are removed from one index and added to the other in a single command. The reindex calls are split up by types but are otherwise similar to the delete by query code above.

**Comment by tlrx** [comment] 2016-08-01 07:59
Unfortunately the Delete-By-Query plugin in version 2.x lacks of logging traces when a delete request failed but most of the time this is caused by a missing document, ie a document has been found during the search/scan/scroll phase but has been deleted or updated before the effective delete request is executed. Are you in such a case? 

Also, do you see any difference in docs count in shards before executing the delete-by-query request?

**Comment by aewhite** [comment] 2016-08-02 13:40
I have another update and I'll answer some Qs.

We ran into this issue again this morning. However, this time there is no difference in the number of documents (or even their _id field), but there is a difference in the versions of the documents. 

Quick background: we use external versioning based on a timestamping system to ensure that various system doesn't overwrite new data with outdated data. 

The version differences across the shards is tiny (<100ms on average) and it appears to be a toss-up as to which shard has the greatest _version.  It's not unusual for us to see rapid fire updates/inserts to the same document due to the nature of the data we collect and our processes. 

This makes me wonder if the problem is in step (1). Even though the alias switch is atomic, are they transactionally consistent for replication? Though, I can see how update-by-query might still be a candidate. 

@tlrx to answer your questions:

First, at the time we issue a delete-by-query on an set of documents, all aliases that would point to that data have been reassigned to a new index. We never issue a delete-by-query to a set of documents that could be updated (all writes go through aliases that are tightly controlled).

As to the state of the index before the query, sadly we don't have insights into this and I think it might be hard given the state I described above with equal doc counts but different versions. This is part of an automated process so I rarely get to see the system between steps (1) and (3) of my original description. And even even if I could look, I don't know how to find version difference across shards for millions of documents without exporting/sorting and comparing them.

**Comment by aewhite** [comment] 2016-08-02 14:37
Ok, more updates. I tracked down the exact versions that were in conflict and when they were inserted. Nearly all of the conflicts cluster around a time when the index was being hit heavily (100k inserts per second). All of the steps I described above happened hours later. Therefore, this appears to be related to write consistency under heavy volume. 

I checked the server logs (master and the shard primary and replica hosts) and nothing is reported out of the ordinary for that high-insert time.

**Comment by nik9000** [comment] 2016-08-02 15:53
> Therefore, this appears to be related to write consistency under heavy volume.

You **should** be able to make *sure* this isn't caused by delete-by-query/alias swapping by walking an index that you haven't used that against and doing gets, bouncing from replica to primary. You can do that with [_preference](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-preference.html).

Are you willing to give that a shot?

**Comment by bleskes** [comment] 2016-08-02 20:19
> This makes me wonder if the problem is in step (1). Even though the alias switch is atomic, are they transactionally consistent for replication? 

They should be resolved before the right is started on the primary, yes.

> The version differences across the shards is tiny (<100ms on average) and it appears to be a toss-up as to which shard has the greatest _version

It sounds like you found document mismatch before the delete by query has run? can you elaborate on what your exactly mean with "<100ms on average"? are these difference between primary and replica? Or they on index A or index B?

Also, can you share the reindexing commands and the normal indexing command you use?

**Comment by aewhite** [comment] 2016-08-02 21:18
@nik9000 I have started trying to find the problem for document sets that haven't been moved but these indexes are large (1B+ documents) and are actively being written to so it's hard to prove that a version mismatch from the time I read shard A to shard B isn't from normal processes. We're talking trying to find ~60 documents out of at least 7.5M documents in an index with 1B documents that has 1k inserts per second on the low end and 100k/s during peak processing time. 

@bleskes it does look like the problem exists before the delete-by-query ran but I just haven't found proof of that yet. 

>  can you elaborate on what your exactly mean with "<100ms on average"? are these difference between primary and replica? Or they on index A or index B?

Sure, so the differences were between the primary and the replicate. Basically my method was to query shard X primary and replica separately using the preference API, export their ids and versions, sort by id and compare them. What I saw was that documents on the primary and the replica had slightly different versions. Usually |version.primary - version.replica| < 100. As to which one had the greater version seemed random.

**Comment by bleskes** [comment] 2016-08-02 21:27
>  I saw was that documents on the primary and the replica had slightly different versions. 

OK. Thanks. This helps. Are these index A or B?

Can you share the API calls you use for indexing and reindexing?

**Comment by aewhite** [comment] 2016-08-02 21:41
The version difference were on index A, the source index. Ie, the delete-by-query would not delete those documents because I assume it detected version difference.

Reindex call:

```
    private ReindexRequestBuilder buildReindexRequest(final String container,
                                                      final String type, final String fromIndex, final String toIndex) {
        final ReindexRequestBuilder reindexRequestBuilder = ReindexAction.INSTANCE.newRequestBuilder(client.getRawClient())
                                                                   .source(fromIndex)
                                                                   .destination(toIndex)
                                                                   .abortOnVersionConflict(false)
                                                                   .filter(QueryBuilders.boolQuery()
                                                                                        .must(QueryBuilders.termQuery("internal.container_id", container))
                                                                                        .must(QueryBuilders.typeQuery(type)));

        reindexRequestBuilder.source().setSize(REINDEX_SCROLL_BATCH_SIZE);
        reindexRequestBuilder.destination().setVersionType(VersionType.EXTERNAL);
        reindexRequestBuilder.destination().setRouting("discard");
        return reindexRequestBuilder;
    }
```

Index call A (realtime updates):

```
final UpdateRequest updateRequest = new UpdateRequestBuilder(client, UpdateAction.INSTANCE)
                .setType("post")
                .setIndex(createContainerWriteAliasName(containerId))
                .setId(DOC_ID_GENERATOR.generateDocId(compositePostBuilder, containerId))
                .setDoc(jsonBytes)
                .setVersionType(VersionType.FORCE)
                .setVersion(compositePostBuilder.getCanonicalConversation().getVersion())
                .setDocAsUpsert(true)
                .request();
```

Index call B (batch updates):

```
        final IndexRequestBuilder indexRequestBuilder = transportClient.prepareIndex(writeAliasName, type)
                                                                       .setId(postIndexRequest.getDocumentId())
                                                                       .setVersionType(VersionType.EXTERNAL_GTE)
                                                                       .setVersion(postIndexRequest.getVersion())
                                                                       .setSource(postIndexRequest.getDocument().toByteArray());
```

The use of force in the realtime system is by design since that data represent the latest and greatest version of a document. Batch processes will take a realtime document and attempt to enrich it which may give it a higher version number but we never want it to overwrite the latest realtime data.

**Comment by nik9000** [comment] 2016-08-02 21:47
`FORCE`....

**Comment by nik9000** [comment] 2016-08-02 21:49
The trouble with force is that it does this. If any of your updates arrive out of order then the `FORCE` will squash them.

**Comment by aewhite** [comment] 2016-08-02 21:54
I want it to squish them... just consistently squish, not half squish.

**Comment by aewhite** [comment] 2016-08-02 22:06
I want to also be 100% clear that when I issue the delete-by-query that there is NO data being indexed that would cause a conflict, by that point the alias has already been updated. The delete by query leaves the index in this weird inconsistent state after being ran (and it was probably in this state before delete-by-query was ever ran).

**Comment by nik9000** [comment] 2016-08-02 22:10
> it was probably in this state before delete-by-query was ever ran)

I'm fairly certain this is caused by `FORCE`.

Say you have two requests to the same document at the same time, both with `FORCE`. The vast, vast majority of the time the first one will be executed first on the primary and then on the replicas and then the second one will be executed on the primary and then on the replicas. But, sometimes, just to make your life hard, executing that first request is delayed on the primary. Maybe there is a network burble, maybe there is some kind of recovery event. If that happens then the primary and replicas will be out of sync. And it'll look like what you described with the replicas having almost the same version but not quite. The javadocs actually [warn](https://github.com/elastic/elasticsearch/blob/2.4/core/src/main/java/org/elasticsearch/index/VersionType.java#L181) about it, but I think we should make it more prevalent.

As for your batch enrichment jobs.... hmm. I see why you have force, but it is causing trouble. I guess you could have the batch jobs only increment the version by 1, but that isn't all that reliable. `EXTERNAL_GTE` is also not really a good option because it has similar ordering issues.

**Comment by aewhite** [comment] 2016-08-02 22:14
So, I read that as "you may lose newer version of a document" and I am 100% ok with that. I did not read "this may make your index inconsistent" which is vastly different in my book.

**Comment by bleskes** [comment] 2016-08-03 07:39
@aewhite thank you very much for explaining the details. The way you use the versioning is not as intended (it assumes some external source of truth that is always correct and is always consistent). See [this blog post](https://www.elastic.co/blog/elasticsearch-versioning-support) for details.

I totally agree that we didn't document the dangers of `FORCE` strongly enough.  I leave this issue open as the right "fix" is documentation.

Also in hindsight I think this just a too dangerous feature. I opened #19769 to discuss its removal.

**Comment by aewhite** [comment] 2016-08-03 11:51
I'm not sure I agree here. We do have an external source that is the source of truth and it is always consistent (HBase). That is exactly why we use FORCE. 

What's strange to me most consistent replication systems use a monotonically increasing 0-gap id system for transactions and replicas *must* reply them in order or the whole system rolls back. If ES doesn't do this then even EXTERNAL_GTE isn't consistent since two updates with different versions could do non idempotent operations on a document.

Without FORCE, I'm not sure what our options will be for eventual consistency.

**Comment by nik9000** [comment] 2016-08-03 12:09
Es doesn't impose an ordering on the operations right now. You'll see
sequence numbers mentioned on GitHub every once in a while and the intent
is to have them do that sort of thing. For now the only ordering
elasticsearch has is per document, specified by version type. Force and
external_gte both have problems because they throw out the normal
constraints.

**Comment by bleskes** [comment] 2016-08-03 12:30
This all comes from the fact that ES uses versions to support out of order and concurrent indexing operations on the replicas. `FORCE` breaks those violations which is why it leaves your replicas in an inconsistent state and that's exactly why it's a super expert settings (which I think in hindsight should be removed - and I added it :)  ) 

`EXTERNAL_GTE` is only to be used for deletes where the external version doesn't see delete as an operation and increments it's version. If all other writes use external, it is safe to use (a concurrent write with a lower or equal version should be deleted, a newer write with a higher version will not be overwritten).

> I'm not sure I agree here. We do have an external source that is the source of truth and it is always consistent (HBase). That is exactly why we use FORCE.

In that case you should not use updates but rather do complete indexing with your version set to `EXTERNAL` all the time.  If your deletes are versioned as well (I do hope they are :)) , you should use `EXTERNAL` there as well. I don't see the need for a `FORCE` in this case?

**Comment by aewhite** [comment] 2016-08-03 16:29
The reason for `FORCE` is because we have the following work flow:

```
external source -> collection -> ES <-----------
                              -> HBase -> batch | 
                           
```

Batch can transform the document and thus give it a more up-to-date (ie larger) version. When we get an updated version of the document for collection we want to force any data in this document to override existing data (that is what I thought `FORCE` did). The kicker here is that the document coming from collection may have a lower version than the batch generated version and unless we precede all inserts with deletes, those new documents will not be indexed due to version conflicts. 

Our backend system takes all versions and changes to a document into consideration so it is eventually consistent, but it's also lagging behind realtime with the latest and greatest info. The reason for the update vs a fresh index is because realtime updates are usually small and don't invalidate enrichments. Blowing away expensive enrichments just because we have a newer source document would be a very bad user experience for us. 

The versioning system we settled on was carefully designed to be eventually consistent while allowing realtime updates to volatile fields. However, this design was built on the assumption that ES had strict ordering of CRUD operations between primaries and replicas.

**Comment by bleskes** [comment] 2016-08-04 21:35
I'm very sorry to hear you have built a system based on the premise that `FORCE` works differnlty. Sadly what it does is to disable the build in version support and allows you to dictate both on the primay and replica (when the request arrives there) what the version should be - no constraints what so ever. This is of course why it's dangerous and don't support concurrency. 

The only versioning-based solution that will work for your case is `EXTERNAL` which is designed to keep ES with an external system that resolves all conflicts and servers as the source of truth (see the blog post I mentioned). Now for you, this doesn't work as your external system takes too long to resolve.

We can consider is using update scripts for all indexing where you manually decide which fields to keep and which to throw away based on your custom business logic. It does come with an obvious (potentially acceptable!)  overhead. 

I don't see any other option right now, with the current feature set in ES.

**Comment by aewhite** [comment] 2016-08-04 22:10
Thanks, we are currently researching alternative versioning/update strategies and/or code changes to introduce strict ordering of replicated operations in the ES code base.

**Comment by clintongormley** [comment] 2016-08-11 12:17
Closing in favour of #19769

**Closed by clintongormley** 2016-08-11 12:17 UTC
Labels: :Plugin Delete By Query
