### ISSUE TITLE
Block / document against overlapping buckets per repositories

### ISSUE THREAD

**Issue by stefnestor** [elastic/elasticsearch#83383] opened 2022-02-01 16:41 UTC
### Elasticsearch Version

7.16.3

### Java Version

_bundled_

### OS Version

UNK

### Problem Description

Using Elastic's [ECE 2.12](https://www.elastic.co/guide/en/cloud-enterprise/2.12/index.html) which uses Elasticsearch Docker images (experienced 7.16.1 to 7.16.3), having multiple Snapshot Repositories for a single cluster pointing to the same (s3) bucket appears to corrupt `uuid`s upon upgrade. Docs currently only warn [against multiple clusters writing to single bucket](https://www.elastic.co/guide/en/cloud/current/ec_share_a_repository_across_clusters.html) but not a single cluster with multiple repositories to a single bucket. Alternatively expecting: multiple SLM policies set to update a single repository/bucket or upgrade to not dissolve `uuid`s.

### Steps to Reproduce

1. Cluster on 7.16.1
2. Setup two S3 repositories pointing to a singular `endpoint` and `bucket`, note their `uuid`s are distinct, redacted e.g.
    ```diff
    { "repository_1" : {
      "type" : "s3",
   +   "uuid" : "t04eQ4jxROqA0mlnMcCpAA",
      "settings" : {
        "bucket" : "just_one_bucket_path",
        "endpoint" : "just_one_endpoint_domain",
        "readonly" : "false",
        "region" : "us-south",
        "compress" : "true"
    }},
    "repository_2" : {
      "type" : "s3",
      "uuid" : "rb2YgZXoTW6qMdtLiyEsjw",
      "settings" : {
        "bucket" : "just_one_bucket_path",
        "endpoint" : "just_one_endpoint_domain",
        "readonly" : "false",
        "region" : "us-south",
        "compress" : "true"
    }}}
    ```
3. Upgrade to 7.16.3 (cluster was upgraded 7.16.1 > 7.16.2 > 7.16.3 but issue was not noticed until searchable snapshot erred below). Poll Repositories and now find `uuid:t04eQ4jxROqA0mlnMcCpAA` is missing and both repositories with unique names point to a single `uuid`:
    ```diff
    { "repository_1" : {
      "type" : "s3",
    -  "uuid" : "rb2YgZXoTW6qMdtLiyEsjw",
      "settings" : {
        "bucket" : "just_one_bucket_path",
        "endpoint" : "just_one_endpoint_domain",
        "readonly" : "false",
        "region" : "us-south",
        "compress" : "true"
    }},
    "repository_2" : {
      "type" : "s3",
      "uuid" : "rb2YgZXoTW6qMdtLiyEsjw",
      "settings" : {
        "bucket" : "just_one_bucket_path",
        "endpoint" : "just_one_endpoint_domain",
        "readonly" : "false",
        "region" : "us-south",
        "compress" : "true"
    }}}
    ```

### Logs (if relevant)

1. Upon this happening, the Searchable Snapshot indices start erring
    - ILM explains will start erring
        ```
        repository_exception: [repository_1] Could not read repository data because the contents of the repository do not match its expected state. This is likely the result of either concurrently modifying the contents of the repository by a process other than this cluster or an issue with the repository's underlying storage. The repository has been disabled to prevent corrupting its contents. To re-enable it and continue using it please remove the repository from the cluster and add it again to make the cluster recover the known state of the repository from its physical contents.
        ```
    - Allocation explain
        ```
        this index is backed by a searchable snapshot in a repository with UUID [t04eQ4jxROqA0mlnMcCpAA] but no such repository is registered with this cluster; the required repository was originally named [repository_1]
        ```
2. This [Discuss](https://discuss.elastic.co/t/restore-from-s3-repository-exception/268848/5) recommends removing and recreating the Repository, which attempt HTTP 500 errors
    ```
    trying to modify or unregister repository [repository_1] that is currently used (found {X} searchable snapshots indices that use the repository: [{first 5 of X indices}]
    ```
6. To resolve, you have to go down a rabbit hole of undoing the Searchable Snapshot Index, deleting its backing Snapshot, deleting its Repository, change its ILM Policy (or its backing Repository), reset its ILM Step. For posterity, TLDR steps:
    1. stop ILM
    2. restore the latest 7 SS indices's backing indices
    3. DELETE _snapshot/kyndryl-scmon-s3-repository
    4. Re-add _snapshot/kyndryl-scmon-s3-repository
    5. ILM move the indices to the beginning of the Frozen phase
    6. start ILM

**Comment by Leaf-Lin** [comment] 2022-02-16 23:51
Duplicate of https://github.com/elastic/elasticsearch/issues/78276?

**Comment by kunisen** [comment] 2022-07-27 07:54
This can also happen when restoring an entire cluster scenario
https://www.elastic.co/guide/en/elasticsearch/reference/current/snapshots-restore-snapshot.html#restore-entire-cluster

And in this scenario, it can happen w/o ILM explain error 

```
repository_exception: [repository_1] Could not read repository data because the contents of the repository do not match its expected state. This is likely the result of either concurrently modifying the contents of the repository by a process other than this cluster or an issue with the repository's underlying storage. The repository has been disabled to prevent corrupting its contents. To re-enable it and continue using it please remove the repository from the cluster and add it again to make the cluster recover the known state of the repository from its physical contents.
```

but just with the same cluster allocation error:

```
this index is backed by a searchable snapshot in a repository with UUID [aaa] but no such repository is registered with this cluster; the required repository was originally named [bbb]
```

We probably need to separate it into different scenarios. 
As in my scenario, there's no way to "restore the latest 7 SS indices's backing indices" because they are not existing in the destination cluster.
The only workaround I can think here, is to restore the backing indices in the source cluster, and then remote reindex to the destination cluster, then manually ILM move step to switch it to cold/frozen SS.
https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-move-to-step.html

**Comment by original-brownbear** [comment] 2022-08-03 12:28
Closing this as a duplicate of https://github.com/elastic/elasticsearch/issues/78276

**Closed by original-brownbear** 2022-08-03 12:28 UTC
Labels: >bug, :Distributed/Snapshot/Restore, Team:Distributed
