### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/elasticsearch/bootstrap/Elasticsearch

### ISSUE THREAD

**Issue by Mohamed70** [elastic/elasticsearch#10259] opened 2015-03-25 10:36 UTC
Hello, I downloaded elasticsearch 1.5.0, I tried to run it but I got this error:

    Exception in thread "main" java.lang.NoClassDefFoundError: org/elasticsearch/bootstrap/Elasticsearch
    Caused by: java.lang.ClassNotFoundException: org.elasticsearch.bootstrap.Elasticsearch
	   at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
	   at java.security.AccessController.doPrivileged(Native Method)
	   at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	   at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
	   at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
	   at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
    Could not find the main class: org.elasticsearch.bootstrap.Elasticsearch. Program will exit.

What's the problem?

**Comment by dadoonet** [comment] 2015-03-25 17:11
Which exact file did you download?
How did you install it?
On which OS?

**Comment by LambdaDriver** [comment] 2015-04-07 16:31
I have encountered the same error on Solaris 11 SPARC using the zip file downloaded from the main site (elasticsearch-1.5.0.zip). 

`SunOS logstash01.local 5.11 11.2 sun4v sparc sun4v`

I run using the following command
`elasticsearch-1.5.0/bin/elasticsearch --config /etc/elasticsearch/elasticsearch.yml -p elasticsearch.pid -d`

Pertinant environment info
```
JAVA_HOME=/export/home/logstash/jdk1.8.0_25
ES_HEAP_SIZE=8g
```


```
[2015-04-07 12:21:04,020][INFO ][node                     ] [zeus] version[1.5.0], pid[2147], build[5448160/2015-03-23T14:30:58Z]
[2015-04-07 12:21:04,021][INFO ][node                     ] [zeus] initializing ...
[2015-04-07 12:21:04,032][INFO ][plugins                  ] [zeus] loaded [marvel], sites [marvel]
[2015-04-07 12:21:04,966][ERROR][bootstrap                ] Exception
org.elasticsearch.common.util.concurrent.ExecutionError: org.elasticsearch.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: Lorg/elasticsearch/indices/InternalIndicesService;
        at org.elasticsearch.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
        at org.elasticsearch.common.cache.LocalCache.get(LocalCache.java:3937)
        at org.elasticsearch.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
        at org.elasticsearch.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
        at org.elasticsearch.common.inject.internal.FailableCache.get(FailableCache.java:51)
        at org.elasticsearch.common.inject.ConstructorInjectorStore.get(ConstructorInjectorStore.java:50)
        at org.elasticsearch.common.inject.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:50)
        at org.elasticsearch.common.inject.InjectorImpl.initializeBinding(InjectorImpl.java:372)
        at org.elasticsearch.common.inject.BindingProcessor$1$1.run(BindingProcessor.java:148)
        at org.elasticsearch.common.inject.BindingProcessor.initializeBindings(BindingProcessor.java:204)
        at org.elasticsearch.common.inject.InjectorBuilder.initializeStatically(InjectorBuilder.java:119)
        at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:102)
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:93)
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70)
        at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:59)
        at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:203)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:159)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:70)
        at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:213)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)
Caused by: org.elasticsearch.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: Lorg/elasticsearch/indices/InternalIndicesService;
        at org.elasticsearch.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
        at org.elasticsearch.common.cache.LocalCache.get(LocalCache.java:3937)
        at org.elasticsearch.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
        at org.elasticsearch.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
        at org.elasticsearch.common.inject.internal.FailableCache.get(FailableCache.java:51)
        at org.elasticsearch.common.inject.MembersInjectorStore.get(MembersInjectorStore.java:68)
        at org.elasticsearch.common.inject.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:67)
        at org.elasticsearch.common.inject.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:29)
        at org.elasticsearch.common.inject.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:37)
        at org.elasticsearch.common.inject.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:33)
        at org.elasticsearch.common.inject.internal.FailableCache$1.load(FailableCache.java:39)
        at org.elasticsearch.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
        at org.elasticsearch.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
        at org.elasticsearch.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
        at org.elasticsearch.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
        ... 19 more
Caused by: java.lang.NoClassDefFoundError: Lorg/elasticsearch/indices/InternalIndicesService;
        at java.lang.Class.getDeclaredFields0(Native Method)
        at java.lang.Class.privateGetDeclaredFields(Class.java:2575)
        at java.lang.Class.getDeclaredFields(Class.java:1908)
        at org.elasticsearch.common.inject.spi.InjectionPoint$Factory$1.getMembers(InjectionPoint.java:378)
        at org.elasticsearch.common.inject.spi.InjectionPoint$Factory$1.getMembers(InjectionPoint.java:376)
        at org.elasticsearch.common.inject.spi.InjectionPoint.addInjectorsForMembers(InjectionPoint.java:351)
        at org.elasticsearch.common.inject.spi.InjectionPoint.addInjectionPoints(InjectionPoint.java:345)
        at org.elasticsearch.common.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:287)
        at org.elasticsearch.common.inject.MembersInjectorStore.createWithListeners(MembersInjectorStore.java:80)
        at org.elasticsearch.common.inject.MembersInjectorStore.access$000(MembersInjectorStore.java:36)
        at org.elasticsearch.common.inject.MembersInjectorStore$1.create(MembersInjectorStore.java:45)
        at org.elasticsearch.common.inject.MembersInjectorStore$1.create(MembersInjectorStore.java:41)
        at org.elasticsearch.common.inject.internal.FailableCache$1.load(FailableCache.java:39)
        at org.elasticsearch.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
        at org.elasticsearch.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
        at org.elasticsearch.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
        at org.elasticsearch.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
        ... 33 more
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.indices.InternalIndicesService
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 50 more
```

**Comment by clintongormley** [comment] 2015-04-26 20:08
No more info provided. Closing

**Closed by clintongormley** 2015-04-26 20:08 UTC
Labels: feedback_needed

**Comment by Mohamed70** [comment] 2015-04-29 09:10
Sorry, I was busy that's why I didn't answer...
So, I tested ZIP and TAR, and it doesn't works, it only works with the DEB archive.
When I run with zip or tar I get this:

    root@debian:/home/user/elasticsearch-1.5.2# ./bin/elasticsearch
    Exception in thread "main" java.lang.NoClassDefFoundError:     org/elasticsearch/bootstrap/Elasticsearch
    Caused by: java.lang.ClassNotFoundException: org.elasticsearch.bootstrap.Elasticsearch
	at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
    Could not find the main class: org.elasticsearch.bootstrap.Elasticsearch. Program will exit.

And I want to test the Marvel plugin but I also get a similar error:

    root@debian:/home/user/elasticsearch-1.5.2# ./bin/plugin -i elasticsearch/marvel/latest
    Exception in thread "main" java.lang.UnsupportedClassVersionError:      org/elasticsearch/plugins/PluginManager : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
    Could not find the main class: org.elasticsearch.plugins.PluginManager. Program will exit.

**Comment by dadoonet** [comment] 2015-04-29 09:41
The second trace is different than the first one. But it shows something interesting which is that you are using an old JVM.

**Comment by dadoonet** [comment] 2015-04-29 09:43
Could you run also `ls -l lib` and paste the result here?

**Comment by Mohamed70** [comment] 2015-04-29 09:50
Ok.
I'm using a virtual machine with VMPlayer where Debian is installed.
The result of ls -l lib is:

    root@debian:/home/mohamed/Téléchargements/elasticsearch-1.5.2# ls -l lib
    total 28864
    -rw-rw-r-- 1 root root   167735 avril 27 09:36 antlr-runtime-3.5.jar
    -rw-rw-r-- 1 root root   448794 avril 27 11:04 apache-log4j-extras-1.2.17.jar
    -rw-rw-r-- 1 root root    47359 avril 27 09:36 asm-4.1.jar
    -rw-rw-r-- 1 root root    38090 avril 27 09:36 asm-commons-4.1.jar
    -rw-rw-r-- 1 root root 13774099 avril 27 11:22 elasticsearch-1.5.2.jar
    -rw-rw-r-- 1 root root  6919921 avril 27 11:04 groovy-all-2.4.0.jar
    -rw-rw-r-- 1 root root   914597 avril 27 09:36 jna-4.1.0.jar
    -rw-rw-r-- 1 root root   794991 avril 27 09:36 jts-1.13.jar
    -rw-rw-r-- 1 root root   489884 avril 27 09:36 log4j-1.2.17.jar
    -rw-rw-r-- 1 root root  1699875 avril 27 09:36 lucene-analyzers-common-4.10.4.jar
    -rw-rw-r-- 1 root root  2563490 avril 27 09:36 lucene-core-4.10.4.jar
    -rw-rw-r-- 1 root root    75491 avril 27 09:36 lucene-expressions-4.10.4.jar
    -rw-rw-r-- 1 root root   107784 avril 27 09:36 lucene-grouping-4.10.4.jar
    -rw-rw-r-- 1 root root   138282 avril 27 09:36 lucene-highlighter-4.10.4.jar
    -rw-rw-r-- 1 root root    64021 avril 27 09:36 lucene-join-4.10.4.jar
    -rw-rw-r-- 1 root root    36078 avril 27 09:36 lucene-memory-4.10.4.jar
    -rw-rw-r-- 1 root root    97173 avril 27 09:36 lucene-misc-4.10.4.jar
    -rw-rw-r-- 1 root root   213029 avril 27 09:36 lucene-queries-4.10.4.jar
    -rw-rw-r-- 1 root root   391515 avril 27 09:36 lucene-queryparser-4.10.4.jar
    -rw-rw-r-- 1 root root   119449 avril 27 09:36 lucene-sandbox-4.10.4.jar
    -rw-rw-r-- 1 root root   126794 avril 27 09:36 lucene-spatial-4.10.4.jar
    -rw-rw-r-- 1 root root   179011 avril 27 09:36 lucene-suggest-4.10.4.jar
    drwxr-xr-x 2 root root     4096 avril 29 11:00 sigar
    -rw-rw-r-- 1 root root   102177 avril 27 09:36 spatial4j-0.4.1.jar

**Comment by dadoonet** [comment] 2015-04-29 09:55
Wondering if something could be wrong with your path which contains french characters: `Téléchargements`. Could you try to move your elasticsearch installation in another dir like `/home/mohamed/work/`? Also it sounds like you have downloaded and extracted elasticsearch as `root`. Are you running your terminal as `root`?

If so, may be you should try to launch elasticsearch with `sudo`?

**Comment by Mohamed70** [comment] 2015-04-29 10:09
I tried to move elasticsearch to another dir and to extract it without root privilege but I also have the same problem.

**Comment by dadoonet** [comment] 2015-04-29 10:22
what gives `java -version`?

**Comment by Mohamed70** [comment] 2015-04-29 11:37
user@debian:~/Documents/elasticsearch-1.5.2$ java -version
java version "1.6.0_34"
OpenJDK Runtime Environment (IcedTea6 1.13.6) (6b34-1.13.6-1~deb7u1)
OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)

**Comment by dadoonet** [comment] 2015-04-29 11:38
Not sure it's your issue here but for sure elasticsearch 1.5 won't work with Java 6.
It requires at least Java7

**Comment by Mohamed70** [comment] 2015-04-29 12:50
Now I installed java 1.7 and it works!! Thanks.

**Comment by Mohamed70** [comment] 2015-04-29 15:39
I installed elasticsearch with deb package, then how I can install the marvel plugin?

**Comment by dadoonet** [comment] 2015-04-29 15:51
Please use the mailing list for your questions.

**Comment by Mohamed70** [comment] 2015-04-30 08:10
Which mailing list?

**Comment by dadoonet** [comment] 2015-04-30 08:11
https://groups.google.com/forum/?hl=fr&fromgroups#!forum/elasticsearch

**Comment by Mohamed70** [comment] 2015-04-30 09:06
Ok.

2015-04-30 10:12 GMT+02:00 David Pilato <notifications@github.com>:

**Comment by satwik19** [comment] 2017-08-09 07:44
Hello, my elasticsearch version is 5.2.2 and java version is 1.8, I tried to run a program but I got this error: 
Exception in thread "main" java.lang.NoClassDefFoundError: org/elasticsearch/plugins/ActionPlugin
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<clinit>(PreBuiltTransportClient.java:54)
	at line_count_spark.Main.main(Main.java:56)
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.plugins.ActionPlugin
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more

**Comment by satwik19** [comment] 2017-08-09 07:48
plzz tell me what i do? to solve this problem

**Comment by dadoonet** [comment] 2017-08-09 07:54
Explain your problem on discuss.elastic.co with all details.

**Comment by satwik19** [comment] 2017-08-09 09:55
i will check there.
Thanks
