### ISSUE TITLE
[CI] Unknown NamedWriteable [component_template] in rolling upgrade tests

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#68894] opened 2021-02-11 10:49 UTC
In a rolling upgrade test from v7.4.2 -> v7.12.snapshot these errors were logged multiple times when the cluster was in a mixed version state:

```
[2021-02-11T03:08:46,648][DEBUG][o.e.c.c.PublicationTransportHandler] [v7.4.2-0] failed to send cluster state to {v7.4.2-2}{n_PQfFTzSpeKCcso849JSw}{NEtcn8n5T_S6j7j1AY8dwQ}{127.0.0.1}{127.0.0.1:45169}{dilm}{testattr=test, ml.machine_memory=101203329024, ml.max_open_jobs=20, xpack.installed=true}
org.elasticsearch.transport.RemoteTransportException: [v7.4.2-2][127.0.0.1:45169][internal:cluster/coordination/publish_state]
Caused by: java.lang.IllegalArgumentException: Unknown NamedWriteable [org.elasticsearch.cluster.NamedDiff][component_template]
```

```
Caused by: java.lang.IllegalArgumentException: Unknown NamedWriteable [org.elasticsearch.cluster.NamedDiff][index_template]
``` 

On the node that has not been upgraded we see:
```
[2021-02-11T03:08:44,938][WARN ][o.e.c.c.PublicationTransportHandler] [v7.4.2-2] unexpected error while deserializing an incoming cluster state
java.lang.IllegalArgumentException: Unknown NamedWriteable [org.elasticsearch.cluster.NamedDiff][component_template]
``` 

And the cluster state diff is not applied. 

**Build scan**:
https://gradle-enterprise.elastic.co/s/rzgzr3qq42yeq

**Repro line**:
`./gradlew ':x-pack:qa:rolling-upgrade:v7.4.2#bwcTest`

**Reproduces locally?**:

**Applicable branches**:
7.x

**Failure history**:
Unknown as the error may not manifest as a failure

**Failure excerpt**:
`Caused by: java.lang.IllegalArgumentException: Unknown NamedWriteable [org.elasticsearch.cluster.NamedDiff][component_template]`

**Comment by martijnvg** [comment] 2021-02-22 13:43
Looking at this test failure; I think this is related to #66837. The `Caused by: java.lang.IllegalArgumentException: Unknown NamedWriteable [org.elasticsearch.cluster.NamedDiff][component_template]` error is also a side effect of installing component templates in a mixed cluster (with nodes that don't understand component templates) and the test logs are also filled with `No handler for action [cluster:admin/component_template/put]` errors, which is reported as well in #66837.

So I'm closing this issue in favour for #66837.

**Closed by martijnvg** 2021-02-22 13:43 UTC
Labels: :Core/Features/Data streams, >test-failure, Team:Core/Features
