### ISSUE TITLE
Ranges as sources for composite aggs

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#38650] opened 2019-02-08 20:50 UTC
Similar to their [histogram](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-composite-aggregation.html#_histogram) counter-part, composite aggs could be extended to support [ranges](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-range-aggregation.html) (numeric, date, ip) as a value source.

**Comment by consulthys** [comment] 2019-11-07 15:26
Can anyone provide a status on this?

**Comment by polyfractal** [comment] 2019-11-18 16:36
Hi @consulthys.  The issue is the source of truth, so we'll make a comment here (or link via a PR) if there is movement on the issue.

Barring any updates, you can safely assume there has been no progress on the issue.  So in this case, there is no news regarding adding range support to composite yet.  We'd like to support it (which is why the issue hasn't been closed), but no updates otherwise.  Sorry!

**Comment by consulthys** [comment] 2019-11-18 18:20
Thank you very much for the update @polyfractal !

**Comment by tveasey** [comment] 2021-03-23 13:40
We have a use case for this in ML: it's a useful primitive for diverse sampling for training on very large data sets.

**Comment by wchaparro** [comment] 2024-02-15 20:18
Closing as not planned.

**Closed by wchaparro** 2024-02-15 20:18 UTC
Labels: >enhancement, Team:Analytics, :Analytics/CompositeAggs
