### ISSUE TITLE
Invalid -Xlog option

### ISSUE THREAD

**Issue by jdoles** [elastic/elasticsearch#45673] opened 2019-08-16 19:49 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 7.3.0

**Plugins installed**: none

**JVM version** (`java -version`): packaged

**OS version** (`uname -a` if on a Unix-like system): Windows Server 2016

**Description of the problem including expected versus actual behavior**:
Starting via elasticsearch.bat produces the following error - 
Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
output:
[0.003s][error][logging] Error opening log file 'logs/gc.log': No such file or directory
[0.003s][error][logging] Initialization of output 'file=logs/gc.log' using options 'filecount=32,filesize=64m' failed.
error:
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Invalid -Xlog option '-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m', see error log for details.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
        at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:111)
        at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:79)
        at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:57)
        at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:89)

**Steps to reproduce**: 
Start elasticsearch via the elasticsearch.bat file

This is corrected by changing the following line in jvm.options from:
9-:-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m

to:

9-:-Xlog:gc*,gc+age=trace,safepoint:file=\"c:\elasticsearch\logs\gc.log\":utctime,pid,tags:filecount=32,filesize=64m

It looks like this has been around for a while in the Windows version.  I found it referenced at https://discuss.elastic.co/t/initial-attempt-at-installing-elasticsearch-not-going-well-windows-server-2016/164923/8 in January.

**Comment by hariseldon3141** [comment] 2020-04-10 01:47
Issue still exists in 7.6.1 64-bit on RHEL 7.8

**Comment by pgomulka** [comment] 2020-12-10 08:44
@hariseldon3141 @jdoles I was unable to reproduce this.
Can you please provided more details on how you think we can reproduce?

**Comment by hariseldon3141** [comment] 2020-12-10 14:58
@pgomulka As this happened 8 months ago, I cannot provide that information. Unfortunately I change workstations quite often. I cannot provide any further information, other than that Elasticsearch seemed unable to create its own logs folder, and my problem was fixed by simply creating the folder at the path that the error specified.

I also recall something weird where an error associated with some 1.9 version was getting printed even though I was using 1.8.

**Comment by pgomulka** [comment] 2020-12-14 09:03
as I was not able to reproduce this I will close this for the time being. Feel free to reach out, reopen if you find any problems related to this.
thank you

**Comment by mischabraam** [comment] 2021-07-08 11:22
This seems not to be resolved. I have this exact issue on Mac with elasticsearch 7.10.2. (latest version in Brew). When starting it logs the following

```
Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
output:
[0.003s][error][logging] Error opening log file 'logs/gc.log': No such file or directory
[0.003s][error][logging] Initialization of output 'file=logs/gc.log' using options 'filecount=32,filesize=64m' failed.
error:
Invalid -Xlog option '-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m', see error log for details.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
	at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:126)
	at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:88)
	at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:59)
	at org.elasticsearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:137)
	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:95)
```

**Comment by cypherrage** [comment] 2021-07-09 16:25
@mischabraam This happens when you dont have a logs directory already created. Creating the logs directory will solve this.

@pgomulka This issue is not common as most people have a logs directory independent of Elasticsearch. This can be reproduced by deleting your logs directory. Is there a reason that Elasticsearch can't simply create the logs directory if it doesn't already exist? Not sure if this is a permissions issue or what, but this would potentially be a very simple fix.

**Comment by mischabraam** [comment] 2021-07-23 12:47
Why not create the directory in code if it doesn't exist?

**Comment by mark-vieira** [comment] 2021-07-26 16:56
> Is there a reason that Elasticsearch can't simply create the logs directory if it doesn't already exist? Not sure if this is a permissions issue or what, but this would potentially be a very simple fix.

I have mixed feelings about this. Failing when the directory is missing serves as an indicator you might have misconfigured the system. I'm not sure just implicitly creating the directory is the best solution here. My preference is to fail and make folks explicitly create the directory.

**Comment by pgomulka** [comment] 2021-08-04 16:16
@mischabraam we discussed this and we decided that we will not allow for creating a directory when missing. For the reason mentioned in https://github.com/elastic/elasticsearch/issues/45673#issuecomment-886868021
we suspect that there might be a packaging problem though and we will investigate further

**Comment by Vasanthagokul** [comment] 2021-09-13 09:04
if there is a problem just create two folders within elastisearch and name it "logs" and "plugins"

**Comment by justinmchase** [comment] 2021-11-28 18:29
I'm encountering this issue also, I tried creating the missing directories but it didn't work. These options are pointing to a relative path directory with an invalid windows file paths `logs/gc.log` instead of `logs\\gc.log`, could that be the issue?

Also, since the path is relative its hard to know what its relative to, I did create them relative to the current working directory for the process but it didn't solve the issue.

**Comment by justinmchase** [comment] 2021-11-28 20:26
Changing the log file to `logs\gc.log` has no effect (with a back slash instead of forward slash).

I then changed the line in the options file to have a full hard coded path:
> 9-:-Xlog:gc*,gc+age=trace,safepoint:file=D:\code\example\.data\elasticsearch\logs\gc.log:utctime,pid,tags:filecount=32,filesize=64m

And then it started working. The CWD of the process is `D:\code\example\.data\elasticsearch` in this case, yet that relative path doesn't work.

I tried `.\logs\gc.log` and `${PWD}\logs\gc.log` and neither of those work either... So I know it can work I just have no idea where its expecting the `logs` folder to be.

>  Failing when the directory is missing serves as an indicator you might have misconfigured the system. I'm not sure just implicitly creating the directory is the best solution here. My preference is to fail and make folks explicitly create the directory.

I think this is fine but it would be super helpful if the error message included the expected full path and if indeed the user has a misconfigured system it may be super helpful here to add a explanation suggesting that there is a likely misconfiguration and what can be done about it. For example is there an environment variable that is dictating where that path is relative to that may be missing?

**Comment by mark-vieira** [comment] 2021-11-29 22:00
> I think this is fine but it would be super helpful if the error message included the expected full path and if indeed the user has a misconfigured system it may be super helpful here to add a explanation suggesting that there is a likely misconfiguration and what can be done about it. For example is there an environment variable that is dictating where that path is relative to that may be missing?

I'm not sure there's not a whole lot we can do here. This is a JVM flag so it's the JVM that's throwing the error on startup.

**Comment by justinmchase** [comment] 2021-11-30 15:00
> ... it's the JVM that's throwing the error on startup.

Ok, yeah then modifying the error message does seem out of scope here.

But here is the line we're talking about in this code base:
https://github.com/elastic/elasticsearch/blob/master/distribution/src/config/jvm.options#L86

And I'm just realizing that that line is different than what I'm seeing on my system, it looks like the log path is being replaced at build time here?

https://github.com/elastic/elasticsearch/blob/master/distribution/build.gradle#L521

Could it be fixed by altering that default path to be more like this one?

https://github.com/elastic/elasticsearch/blob/master/distribution/build.gradle#L494

from:
```
  'def': 'logs/gc.log'
```

to:
```
  'def': ''$ES_HOME"/logs/gc.log'
```

Otherwise, what would help me immensely is if someone here could explain where the logs directory is supposed to be created?

Or another super easy fix would be to just omit that line entirely by default. Something like this:

```
      'loggc': [
        'deb': "-Xlog:gc*,gc+age=trace,safepoint:file=${packagingLoggc}:utctime,pid,tags:filecount=32,filesize=64m",
        'rpm': "-Xlog:gc*,gc+age=trace,safepoint:file=${packagingLoggc}:utctime,pid,tags:filecount=32,filesize=64m",
        'def': ''
      ],
```

```
# jvm.options
## GC logging
@loggc@
```

**Comment by mark-vieira** [comment] 2021-11-30 22:34
Using an absolute path is an interesting idea. I suspect the reason we _don't_ is because our JVM options parsing logic likely doesn't support it but we could potentially improve that. Likely same reason using `${PWD}` in the path didn't work.

**Comment by rjernst** [comment] 2022-06-09 13:44
Given the recent consolidation of scripting logic into Java, I don't think this issue is possible anymore. My theory is that this could have occurred in the past when the jvm options parser was invoked before cd'ing to the ES_HOME dir in bin/elasticsearch-env. cd'ing to ES_HOME happens as soon as possible now, so there should always be a log dir (as we ship with an empty log dir in all distributions).

**Closed by rjernst** 2022-06-09 13:44 UTC
Labels: >bug, feedback_needed, :Core/Infra/Logging, team-discuss, Team:Core/Infra, needs:reproduction
