### ISSUE TITLE
Prioritize FetchPhase over QueryPhase Under High Search Workload

### ISSUE THREAD

**Issue by atris** [elastic/elasticsearch#39891] opened 2019-03-11 05:36 UTC
Currently, FetchPhase and QueryPhase will be scheduled on the same threadpool. This can cause issues when dealing with search heavy workloads since FetchPhase can stall behind a slew of QueryPhases. That is problematic since FetchPhase is heavier than QueryPhase (more open search handles for eg), and also means that we have completed the QueryPhase for the specific query, hence the major heavylifting for that query has already been done.

On coordinator nodes, we should complete FetchPhase faster to reduce the probability of throttling kicking in and killing the FetchPhase, hence wasting the resources expended for completing the QueryPhase for this query (https://github.com/elastic/elasticsearch/issues/38586). On data nodes, completing FetchPhase earlier should reduce query latencies and should also reduce pressure on memory (https://github.com/elastic/elasticsearch/issues/29366).

Another mechanism is to schedule QueryPhase and FetchPhase on different threadpools, but that is discouraged due to the fact that we already have a large number of threadpools today.

**Comment by javanna** [comment] 2022-11-16 22:08
Closing as duplicate of #29366 .

**Closed by javanna** 2022-11-16 22:08 UTC
Labels: :Search/Search, Team:Search
