### ISSUE TITLE
MachineLearningTests.testNoAttributes_givenSameAndMlEnabled fails due to trying to directly set node.attr.ml.enabled

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#30804] opened 2018-05-23 09:30 UTC
Example failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.3+intake/100/console

Reproduce command:
```
./gradlew :x-pack:plugin:ml:test -Dtests.seed=1FF9AADB15A8BF2A -Dtests.class=org.elasticsearch.xpack.ml.MachineLearningTests -Dtests.method="testNoAttributes_givenSameAndMlEnabled" -Dtests.security.manager=true -Dtests.locale=hu-HU -Dtests.timezone=Etc/GMT-0
```

It looks like this is as a result of the changes made in https://github.com/elastic/elasticsearch/commit/30b004f582fa44d630fe1a910089d0821e6fcc26. @droberts195 is working on a fix for this.

Failure stack trace:
```
09:10:34 ERROR   0.04s J2 | MachineLearningTests.testNoAttributes_givenSameAndMlEnabled <<< FAILURES!
09:10:34    > Throwable #1: java.lang.IllegalArgumentException: Directly setting [node.attr.ml.enabled] is not permitted - it is reserved for machine learning. If your intention was to customize machine learning, set the [xpack.ml.enabled] setting instead.
09:10:34    > 	at __randomizedtesting.SeedInfo.seed([1FF9AADB15A8BF2A:43DD702474BC0633]:0)
09:10:34   2> NOTE: leaving temporary files on disk at: /var/lib/jenkins/workspace/elastic+elasticsearch+6.3+intake/x-pack/plugin/ml/build/testrun/test/J2/temp/org.elasticsearch.xpack.ml.MachineLearningTests_1FF9AADB15A8BF2A-001
09:10:34   2> NOTE: test params are: codec=Asserting(Lucene70): {}, docValues:{}, maxPointsInLeafNode=1487, maxMBSortInHeap=7.5181168679555945, sim=RandomSimilarity(queryNorm=false): {}, locale=hu-HU, timezone=Etc/GMT-0
09:10:34    > 	at org.elasticsearch.xpack.ml.MachineLearning.reportClashingNodeAttribute(MachineLearning.java:342)
09:10:34   2> NOTE: Linux 4.4.0-1055-aws amd64/Oracle Corporation 1.8.0_162 (64-bit)/cpus=4,threads=1,free=421484672,total=514850816
09:10:34    > 	at org.elasticsearch.xpack.ml.MachineLearning.addMlNodeAttribute(MachineLearning.java:327)
09:10:34   2> NOTE: All tests run in this JVM: [CppLogMessageHandlerTests, NormalizerTests, NameResolverTests, DataLoadParamsTests, CsvParserTests, AuditorTests, JsonDataToProcessWriterTests, CategoryDefinitionTests, ModelPlotConfigWriterTests, TimeRangeTests, CountingInputStreamTests, TransportGetJobsStatsActionTests, FlushAcknowledgementTests, InfluenceTests, DatafeedNodeSelectorTests, NormalizerResultHandlerTests, ConnectiveTests, AutodetectCommunicatorTests, RuleConditionTypeTests, InfluencersQueryBuilderTests, MlDailyManagementServiceTests, TransportStartDatafeedActionTests, ChainTaskExecutorTests, ExpiredResultsRemoverTests, AggregationToJsonProcessorTests, NativeAutodetectProcessTests, DataExtractorFactoryTests, DateFormatDateTransformerTests, DetectorFunctionTests, SearchHitToJsonProcessorTests, BucketNormalizableTests, PartitionScoreTests, NativeControllerTests, MachineLearningFeatureSetTests, MachineLearningTests]
09:10:34    > 	at org.elasticsearch.xpack.ml.MachineLearning.additionalSettings(MachineLearning.java:311)
09:10:34    > 	at org.elasticsearch.xpack.ml.MachineLearningTests.testNoAttributes_givenSameAndMlEnabled(MachineLearningTests.java:49)
09:10:34    > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by colings86** [comment] 2018-05-23 09:42
Muted test on master, 6.x, and 6.3

**Comment by ywelsch** [comment] 2018-05-23 09:52
This was caused by https://github.com/elastic/elasticsearch/pull/30780, which luckily passed CI due to randomization.
I've pushed a fix and reenabled the tests on all branches.

**Closed by ywelsch** 2018-05-23 09:52 UTC
Labels: :ml, >test-failure, v6.3.0, v6.4.0, v7.0.0
