### ISSUE TITLE
Bug in aggregation result when using shards

### ISSUE THREAD

**Issue by physicalattraction** [elastic/elasticsearch#37425] opened 2019-01-14 15:01 UTC
We have found a reproducible issue that an aggregation gives not the correct results when using sharding.

Reproduction (The Python script below can be used for steps 1 and 2):
1) Create an index with 5 shards with the given the mappings from this JSON: https://s3.eu-central-1.amazonaws.com/nyon-shared-storage/sales-production-mappings.json
2) Add the following 1,500 documents to it: https://s3.eu-central-1.amazonaws.com/nyon-shared-storage/sales-production-anonymized.json
3) Run the following query: https://s3.eu-central-1.amazonaws.com/nyon-shared-storage/search_query.json
4) Write down the results somewhere, in particular the combination of key and total quantity.
5) Change the "size": 20 to "size" 200 in the search query and run it again
6) Compare the outputs.

The outputs depend a little bit on which data is stored on which shard, and hence can differ (which is the actual problem!) For me, the results were:

size = 20:
```
    [(1, 'MDS_FES_brand_supplier_1||article_113||34-46||120', 19.0),
     (2, 'MDS_FES_brand_supplier_1||article_115||34-46||120', 19.0),
     (3, 'MDS_FES_brand_supplier_1||article_113||XS-XXL||990', 14.0),
     (4, 'MDS_FES_brand_supplier_1||article_115||XS-XXL||990', 13.0),
     (5, 'MDS_FES_brand_supplier_1||article_113||603', 12.0),
     (6, 'MDS_FES_brand_supplier_1||article_113||34-46||990', 10.0),
     (7, 'MDS_FES_brand_supplier_1||article_115||34-46||491', 10.0),
     (8, 'MDS_FES_brand_supplier_1||article_113||990', 8.0),
     (9, 'MDS_FES_brand_supplier_1||article_115||XS-XXL||650', 7.0),
     (10, 'MDS_FES_brand_supplier_1||article_113||34-46||348', 6.0),
     (11, 'MDS_FES_brand_supplier_1||article_113||XS-XXL||120', 6.0),
     (12, 'MDS_FES_brand_supplier_1||article_113||XS-XXL||650', 6.0),
     (13, 'MDS_FES_brand_supplier_1||article_115||34-46||348', 6.0),
     (14, 'MDS_FES_brand_supplier_1||article_115||990', 6.0),
     (15, 'MDS_FES_brand_supplier_1||article_115||XS-XL||348', 6.0),
     (16, 'MDS_FES_brand_supplier_1||article_113||120', 5.0),
     (17, 'MDS_FES_brand_supplier_1||article_113||34-46||320', 5.0),
     (18, 'MDS_FES_brand_supplier_1||article_115||120', 5.0),
     (19, 'MDS_FES_brand_supplier_1||article_115||603', 5.0),
     (20, 'MDS_FES_brand_supplier_1||article_115||638', 5.0)]
```

size = 200:
```
     [(1, 'MDS_FES_brand_supplier_1||article_113||34-46||120', 19.0),
     (2, 'MDS_FES_brand_supplier_1||article_115||34-46||120', 19.0),
     (3, 'MDS_FES_brand_supplier_1||article_113||XS-XXL||990', 14.0),
     (4, 'MDS_FES_brand_supplier_1||article_115||XS-XXL||990', 13.0),
     (5, 'MDS_FES_brand_supplier_1||article_113||603', 12.0),
     (6, 'MDS_FES_brand_supplier_1||article_115||34-46||491', 10.0),
     (7, 'MDS_FES_brand_supplier_1||article_113||34-46||990', 9.0),
     (8, 'MDS_FES_brand_supplier_1||article_113||990', 8.0),
     (9, 'MDS_FES_brand_supplier_1||article_115||XS-XXL||650', 7.0),
     (10, 'MDS_FES_brand_supplier_1||article_113||34-46||348', 6.0),
     (11, 'MDS_FES_brand_supplier_1||article_113||XS-XXL||120', 6.0),
     (12, 'MDS_FES_brand_supplier_1||article_113||XS-XXL||650', 6.0),
     (13, 'MDS_FES_brand_supplier_1||article_115||990', 6.0),
     (14, 'MDS_FES_brand_supplier_1||article_115||XS-XL||348', 6.0),
     (15, 'MDS_FES_brand_supplier_1||article_115||XS-XXL||491', 6.0),
     (16, 'MDS_FES_brand_supplier_1||article_113||120', 5.0),
     (17, 'MDS_FES_brand_supplier_1||article_115||120', 5.0),
     (18, 'MDS_FES_brand_supplier_1||article_115||34-46||348', 5.0),
     (19, 'MDS_FES_brand_supplier_1||article_115||603', 5.0),
     (20, 'MDS_FES_brand_supplier_1||article_115||638', 5.0),
```

As one can see, the bucket with key `MDS_FES_brand_supplier_1||article_113||34-46||990` contains a total quantity of 10 in the first case and of 9 in the latter case. It turns out that in the first case, not all data was taken into account (one document with quantity = -1 is not taken into account). One can verify this by adding a query `{'term': {'catalogs.full_submodel_grouping': 'MDS_FES_brand_supplier_1||article_113||34-46||990'}}` to the search query. In both cases, the result is now 9.

I tested this on ElasticSearch 6.4.2 with two nodes. This problem disappears when executed on an index with only 1 shard.

Python script for reproduction:

```
def restore_snapshot():
    index = 'sales-reproduction'
    delete_index(index)
    with open('sales-production-mappings.json', 'r') as f:
        mappings = json.loads(f.read())
    create_index(index, settings={'number_of_shards': 5}, mappings=mappings)
    with open('sales-production-anonymized.json', 'r') as f:
        result = json.loads(f.read())
    for sale in result['hits']['hits']:
        source = sale['_source']
        post_to_index(index, source)
```

**Comment by polyfractal** [comment] 2019-01-14 19:36
I suspect what you're seeing is just the approximate nature of the `top-n` algorithm used by the terms aggregation.  Essentially, each shard sends back its best `n` results, and then all the shard's best `n` are merged.  But due to the sharded nature a term may not make the top `n` of a particular shard (even though globally it should).  This can lead to approximate doc_counts, and by extension, approximate ordering by sub-aggs (since you need all the documents present for a sub-agg to be accurate as well).

The docs cover this situation here: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#search-aggregations-bucket-terms-aggregation-approximate-counts

As you saw, increasing the size of the request usually "fixes" the issue, because the `top-n` expands and more results are pulled from each shard.

We have a [`shard_size` parameter](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_shard_size_3) which you can configure to achieve the same thing, without increasing the size of the final `top-n` result set.  E.g. you can set `shard_size: 200` to retrieve 200 results from each shard, but keep `size: 20` so that the final result set is still 20 long.

Would you mind configuring a `shard_size` and retrying your tests?  I believe that will fix the issue you are seeing, and make the results more deterministic.

**Comment by physicalattraction** [comment] 2019-01-15 08:35
@polyfractal: Thanks for your clear reply. Indeed increasing the `shard_size` parameter from 20 to 200 gives me a more accurate result. I was not aware of this limitation, it is present but a bit hidden in the documentation.

So it is not a bug after all, just for me unexpected behavior. I think it is more fair to future users if the limitations of ElasticSearch are clearly communicated in any feature page like the README of this repository. People need to make a decision which database to choose based on this kind of information. They do not, and in fact cannot read the entire documentation to make a well-informed decision.

**Comment by polyfractal** [comment] 2019-01-15 13:06
Great, glad that solved your issue @physicalattraction!  Gonna close this issue :)

 > So it is not a bug after all, just for me unexpected behavior. I think it is more fair to future users if the limitations of ElasticSearch are clearly communicated in any feature page like the README of this repository. People need to make a decision which database to choose based on this kind of information. They do not, and in fact cannot read the entire documentation to make a well-informed decision.

I understand this sentiment, but you have to think about it from the perspective of maintaining a large project.  We have a wide array of features, and due to the distributed nature of Elasticsearch, many of the features have specific implementation details and limitations.  That's just part of the territory for any kind of clustered software, certain tradeoffs have to be made (often it's "pick two of: `[fast, accurate, big]`").  

It would be impractical to list all the caveats and limitations in the project's README.  The list would be unwieldy and difficult for a user to navigate, and confusing since new users wouldn't understand what any of the features are... or how to interpret the limitations.

Instead, we try to extensively document the limitations on each feature.  The `terms` agg spends the first third of the documentation discussing the [approximate count issue](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#search-aggregations-bucket-terms-aggregation-approximate-counts).  Similarly, the [Cardinality agg](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-cardinality-aggregation.html#_counts_are_approximate) and [Percentiles agg](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-percentile-aggregation.html#search-aggregations-metrics-percentile-aggregation-approximation) have a lot written about their particular algorithms and the tradeoffs that are incurred.    This pattern is used across the APIs/features in ES docs.

The hope is that a user finds the feature they need, reads about how to use it in the documentation and then continues to read about the limitations.  We're not trying to hide anything (I think we're very open about limitations!), it's just that at the size of our API, it's the only practical way to organize the information.

Thanks for understanding!

**Closed by polyfractal** 2019-01-15 13:06 UTC
Labels: :Analytics/Aggregations, >bug, feedback_needed

**Comment by physicalattraction** [comment] 2019-01-15 13:20
Thanks for the clarification. :-)
