### ISSUE TITLE
Elasticsearch docker image no longer ships unzip from 7.2.0 -> need new doc for certificate generation

### ISSUE THREAD

**Issue by jguay** [elastic/elasticsearch#43696] opened 2019-06-27 13:53 UTC
**Elasticsearch version** (`bin/elasticsearch --version`):
7.2.0 docker (docker.elastic.co/elasticsearch/elasticsearch:7.2.0)

**Description of the problem including expected versus actual behavior**:

We document generating certificates using docker [here](https://www.elastic.co/guide/en/elasticsearch/reference/7.2/configuring-tls-docker.html) which makes use of [certutil](https://www.elastic.co/guide/en/elasticsearch/reference/7.2/certutil.html) outputing a zip file, which we then unzip

Previous to 7.2.0 elasticsearch image had unzip which was removed, but it's assumed it was wrong to include unzip in elasticsearch image and to use this.
```
$ docker run --rm -it docker.elastic.co/elasticsearch/elasticsearch:7.2.0 /bin/bash
[root@01e46fafd1e4 elasticsearch]# unzip
bash: unzip: command not found
```

We should probably use tar.gz instead since tar is still part of the image, but then [certutil](https://www.elastic.co/guide/en/elasticsearch/reference/current/certutil.html) "--out" option generates only zip file regardlesss if extension would be tar.gz

```
$ file bundle.tar.gz
bundle.tar.gz: Zip archive data, at least v2.0 to extract
```

**Steps to reproduce**:
https://www.elastic.co/guide/en/elasticsearch/reference/7.2/configuring-tls-docker.html

This will fail on unzip command

There may be several workarounds : 
1- Most simple, use elasticsearch 7.1.1 for the certificates generation
2- Dockerfile to install unzip for the container used to run same script as documented
3- Generate the zip file with that container, use another container for the unzipping of the certificates bundle.zip
4- More complicated run several commands without using those from the context help from certutil, losing the ability to utilize silent mode of certutil
```
If you specify any of the following options:
    * -pem (PEM formatted output)
    * -keep-ca-key (retain generated CA key)
    * -multiple (generate multiple certificates)
    * -in (generate certificates from an input file)
then the output will be be a zip file containing individual certificate/key files
```

**Comment by dliappis** [comment] 2019-06-28 13:40
This is a duplicate of #43695 so I will close this out and keep tracking progress in #43695 . I have raised #43748 to address it.

**Closed by dliappis** 2019-06-28 13:40 UTC
Labels: :Core/Infra/Packaging
