### ISSUE TITLE
Store synonym definition file in an index instead on the FS

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#16824] opened 2016-02-26 16:30 UTC
Today, you have two ways to define a list of synonyms:

* within the index settings (mapping) which could cause a very big index metadata (so big cluster state - imagine daily indices)
* on the file system itself but this is hard to maintain then

This feature request is about storing that document within an index and be able to retrieve it when the index is created/loaded.

See also discussion on https://discuss.elastic.co/t/recommendation-for-large-synonym-file/42740/5

**Comment by frankkoornstra** [comment] 2016-02-26 16:47
+!

**Comment by Timvd** [comment] 2016-02-26 16:47
+1

**Comment by andrestc** [comment] 2016-02-26 18:13
Definetly +1, we implemented something like this in our application and would be great to have this kind of feature natively.

**Comment by clintongormley** [comment] 2016-02-28 23:53
Closing as duplicate of https://github.com/elastic/elasticsearch/issues/5124

**Closed by clintongormley** 2016-02-28 23:53 UTC
Labels: :Analysis, discuss
