### ISSUE TITLE
ILM Enhancement - Adjust Shard allocation setting total_shards_per_node

### ISSUE THREAD

**Issue by steevo590** [elastic/elasticsearch#47697] opened 2019-10-07 19:39 UTC
Hi,
I would like request and enhancement to the ILM to be able to modify the total_shards_per_node setting as part of the ILM cycle, for most of my indices I have it set to 1 while it is on hot but need it modified when it goes to warm as I have more warm nodes than hot and some indexes have too many shards that there is no available warm node to move it to so a few shards sit on hot where I don't want them unless I use some separate mechanism to change this setting once it's not being actively written to.

thanks,

**Comment by dakrone** [comment] 2019-10-07 20:09
Hi @steevo590 this is a duplicate of an existing issue: https://github.com/elastic/elasticsearch/issues/44070. It's on the ILM roadmap and we're planning on adding it in the future. I'm going to close this in favor of the other issue.

**Closed by dakrone** 2019-10-07 20:09 UTC
Labels: :Core/Features/ILM+SLM

**Comment by steevo590** [comment] 2019-10-07 20:15
ok thanks, must have missed that when I looked through them initially
