### ISSUE TITLE
CI: SearchableSnapshotsIntegTests failures

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#66730] opened 2020-12-22 09:08 UTC
Two set of tests are failing - from the logs they _seem_ somewhat related.

org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests testSnapshotMountedIndexLeavesBlobsUntouched
org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotRecoveryStateIntegrationTests testRecoveryStateRecoveredBytesMatchPhysicalCacheState

**Build scan**:
https://gradle-enterprise.elastic.co/s/mespip5gogcmg
https://gradle-enterprise.elastic.co/s/p5uuwims7a7f2

**Repro line**:
```
Execution failed for task ':x-pack:plugin:searchable-snapshots:internalClusterTest'.

REPRODUCE WITH: gradlew ':x-pack:plugin:searchable-snapshots:internalClusterTest' --tests "org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests.testSnapshotMountedIndexLeavesBlobsUntouched" \
  -Dtests.seed=BB70024FC3F106BB \
  -Dtests.security.manager=true \
  -Dtests.locale=en-SG \
  -Dtests.timezone=America/St_Johns \
  -Druntime.java=11

REPRODUCE WITH: gradlew ':x-pack:plugin:searchable-snapshots:internalClusterTest' --tests "org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests.testSnapshotMountedIndexLeavesBlobsUntouched" \
  -Dtests.seed=BB70024FC3F106BB \
  -Dtests.security.manager=true \
  -Dtests.locale=en-SG \
  -Dtests.timezone=America/St_Johns \
  -Druntime.java=11
```

```
Execution failed for task ':x-pack:plugin:searchable-snapshots:internalClusterTest'.

REPRODUCE WITH: gradlew ':x-pack:plugin:searchable-snapshots:internalClusterTest' --tests "org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotRecoveryStateIntegrationTests.testRecoveryStateRecoveredBytesMatchPhysicalCacheState" \
  -Dtests.seed=D4540C05A4826074 \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-AE \
  -Dtests.timezone=Asia/Atyrau \
  -Druntime.java=8

REPRODUCE WITH: gradlew ':x-pack:plugin:searchable-snapshots:internalClusterTest' --tests "org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotRecoveryStateIntegrationTests.testRecoveryStateRecoveredBytesMatchPhysicalCacheState" \
  -Dtests.seed=D4540C05A4826074 \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-AE \
  -Dtests.timezone=Asia/Atyrau \
  -Druntime.java=8
```

**Applicable branches**:
7.11 and master

**Failure excerpt**:
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=380, name=elasticsearch[node_s0][generic][T#2], state=RUNNABLE, group=TGRP-SearchableSnapshotRecoveryStateIntegrationTests]
	at __randomizedtesting.SeedInfo.seed([D4540C05A4826074:9AB6D6941D759D7C]:0)
Caused by: java.lang.AssertionError: shard eviction should be successful: [snapshotUUID=xlTcRHS3TvKMZ0ThoYJJtg, snapshotIndexName=twpfmpmquh, shardId=[twpfmpmquh][0]]
	at __randomizedtesting.SeedInfo.seed([D4540C05A4826074]:0)
	at org.elasticsearch.xpack.searchablesnapshots.cache.CacheService.runIfShardMarkedAsEvictedInCache(CacheService.java:412)
	at org.elasticsearch.xpack.searchablesnapshots.cache.CacheService.access$100(CacheService.java:62)
	at org.elasticsearch.xpack.searchablesnapshots.cache.CacheService$1.doRun(CacheService.java:351)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:684)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=868, name=elasticsearch[node_s1][generic][T#6], state=RUNNABLE, group=TGRP-SearchableSnapshotsIntegTests]
	at __randomizedtesting.SeedInfo.seed([BB70024FC3F106BB:5D02DB6F37A22D01]:0)
Caused by: java.lang.AssertionError: shard eviction should be successful: [snapshotUUID=zjm5kXbKSHisEnXGh-76Lw, snapshotIndexName=oxejtlweoj, shardId=[oxejtlweoj][1]]
	at __randomizedtesting.SeedInfo.seed([BB70024FC3F106BB]:0)
	at org.elasticsearch.xpack.searchablesnapshots.cache.CacheService.runIfShardMarkedAsEvictedInCache(CacheService.java:412)
	at org.elasticsearch.xpack.searchablesnapshots.cache.CacheService$1.doRun(CacheService.java:351)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:680)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by costin** [comment] 2020-12-22 09:26
Another one here with the same assertion failure: https://gradle-enterprise.elastic.co/s/5aivsdkt65r2m

org.elasticsearch.blobstore.cache.SearchableSnapshotsBlobStoreCacheIntegTests#testBlobStoreCache
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=60, name=elasticsearch[node_s2][generic][T#2], state=RUNNABLE, group=TGRP-SearchableSnapshotsBlobStoreCacheIntegTests]
	at __randomizedtesting.SeedInfo.seed([BB88A94FB8F520BE:A3C594952E97D249]:0)
Caused by: java.lang.AssertionError: shard eviction should be successful: [snapshotUUID=9Uc6WrbVRPmAReLGpgDXiQ, snapshotIndexName=qsroabstvp, shardId=[qsroabstvp][5]]
	at __randomizedtesting.SeedInfo.seed([BB88A94FB8F520BE]:0)
	at org.elasticsearch.xpack.searchablesnapshots.cache.CacheService.runIfShardMarkedAsEvictedInCache(CacheService.java:412)
	at org.elasticsearch.xpack.searchablesnapshots.cache.CacheService$1.doRun(CacheService.java:351)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:680)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by original-brownbear** [comment] 2020-12-25 16:17
@tlrx I think you're working on this one anyway so assigning you here. I guess this one is kind of a duplicate of other open test failures (we got a few failing tests that are coming from this tripped assertion but I figured I'd leave it open so people have an easier time in test triage)

**Comment by dimitris-athanasiou** [comment] 2021-01-11 09:03
Another failure of this: https://gradle-enterprise.elastic.co/s/62xa4bm4czz44

org.elasticsearch.blobstore.cache.SearchableSnapshotsBlobStoreCacheIntegTests#testBlobStoreCache
```
com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
WARNING: Uncaught exception in thread: Thread[elasticsearch[node_s3][generic][T#4],5,TGRP-SearchableSnapshotsBlobStoreCacheIntegTests]
java.lang.AssertionError: shard eviction should be successful: [snapshotUUID=a3BM51jwSTuEE_b39EdXvA, snapshotIndexName=tqbgvnsvwp, shardId=[tqbgvnsvwp][3]]
	at __randomizedtesting.SeedInfo.seed([D60DDAE24C94ED57]:0)
	at org.elasticsearch.xpack.searchablesnapshots.cache.CacheService.runIfShardMarkedAsEvictedInCache(CacheService.java:412)
	at org.elasticsearch.xpack.searchablesnapshots.cache.CacheService.access$100(CacheService.java:62)
	at org.elasticsearch.xpack.searchablesnapshots.cache.CacheService$1.doRun(CacheService.java:351)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:684)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by dimitris-athanasiou** [comment] 2021-01-11 09:11
And another one in a different test: https://gradle-enterprise.elastic.co/s/yub77ikk5xicq

org.elasticsearch.xpack.searchablesnapshots.RetrySearchIntegTests testRetryPointInTime

```
com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
WARNING: Uncaught exception in thread: Thread[elasticsearch[node_s5][generic][T#1],5,TGRP-RetrySearchIntegTests]
java.lang.AssertionError: shard eviction should be successful: [snapshotUUID=hvZ0GJlFS0GFkdoiGl5Djw, snapshotIndexName=xtmpjwqbvm, shardId=[xtmpjwqbvm][0]]
	at __randomizedtesting.SeedInfo.seed([5CDCF8EDA7F4EB1C]:0)
	at org.elasticsearch.xpack.searchablesnapshots.cache.CacheService.runIfShardMarkedAsEvictedInCache(CacheService.java:412)
	at org.elasticsearch.xpack.searchablesnapshots.cache.CacheService$1.doRun(CacheService.java:351)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:680)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by iverase** [comment] 2021-01-12 14:43
Another failure today: https://gradle-enterprise.elastic.co/s/cgxjk3js5junk

One thing that seems clear is that errors seems to be happening only on windows.

**Comment by tlrx** [comment] 2021-01-15 09:03
The shard eviction mechanism has been improved in #67160 and the failing assertion removed in #67265. This should be fixed now so I'm closing this issue.

**Closed by tlrx** 2021-01-15 09:03 UTC
Labels: :Distributed/Snapshot/Restore, >test-failure, Team:Distributed
