### ISSUE TITLE
how to add dynamic mappings if and only if  it matches some template

### ISSUE THREAD

**Issue by neoxue** [elastic/elasticsearch#27170] opened 2017-10-30 14:47 UTC
-    on dynamic/dynamic template, as I understand that:
-    If I turn dynamic: true, it tries to match my dynamic templates and choose my defined mapping or not matched, then it choose default mapping;(long, text|keyword etc.)

-    I want a feature that, add dynamic mapping if and only if it matches my template.(which means if not matched, then go the way of dynamic false) Is there a method or could we add this feature?

**Comment by dnhatn** [comment] 2017-10-30 15:37
@neoxue, Please ask questions on https://discuss.elastic.co where we can give you a better support. We use Github for bug reports and feature requests. Thank you.

**Comment by jasontedor** [comment] 2017-10-30 15:47
@dnhatn This is a feature request, which is valid here.

**Comment by dnhatn** [comment] 2017-10-30 15:51
@jasontedor @neoxue, Sorry, I mistakenly thought it as a question.

**Comment by neoxue** [comment] 2017-10-31 06:36
@dnhatn  that's all right. I wrote an ambiguous title.

**Comment by colings86** [comment] 2017-11-27 16:34
We discussed this in the search and aggregation team and we said that we can see the use case for this and think we should support it but we want to fold it into other discussions we are having around dynamic  mappings, index templates and auto creation of indexes to make sure our decisions on those take this into account

**Comment by javanna** [comment] 2018-03-16 10:31
@elastic/es-search-aggs

**Comment by ernesto-jimenez** [comment] 2018-06-01 07:28
@colings86 has there been any discussion about this?

If so, where will be the best place to track it?

In case a use case is helpful for the discussion:

When creating our ELK indexes for our structured logs we want to pre-define some known fields for parsing (e.g: `event` or `duration`) and use dynamic templates for some conventions (e.g: top level `*_at`will be indexed as a `date`, top level `*_id` as `text` and so on). That would allow developers to have a great experience with logs by following conventions. However, we don't want to create fields for _anything_ since it could lead to [mapping explosion](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html#mapping-limit-settings).

**Comment by colings86** [comment] 2018-06-01 11:59
@ernesto-jimenez There has not yet been further discussion about this due to other priorities but it is something we would still like to address. Here is the best place to track this feature in particular. I'll make sure that any related discussion we have around "dynamic mappings, index templates and auto creation of indexes" which would affect or include this are linked here so you can be aware of those too and can track them as well.

**Comment by javanna** [comment] 2022-06-16 19:26
As far as I understand, the solution that was proposed [here](https://github.com/elastic/elasticsearch/issues/12358#issuecomment-372735502) would address this issue as you would be able to define your dynamic templates plus an extra dynamic template at the end with a directive to not map matching fields. Closing as a duplicate of #12358 .

**Closed by javanna** 2022-06-16 19:26 UTC
Labels: >enhancement, stalled, :Search/Mapping, Team:Search
