### ISSUE TITLE
[CI] :test:fixtures:s3-fixture:composeUp unable to remount

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#52313] opened 2020-02-13 12:34 UTC
looks differently to previous issues, therefore creating a new one.

Found: https://gradle-enterprise.elastic.co/s/lhodf6wwx6nlo

Relevant logs:
```
10:43:10 > Task :test:fixtures:s3-fixture:composeUp
10:43:10 /bin/sh: /tmp/_MEIUo0akS/libreadline.so.7: no version information available (required by /bin/sh)
10:43:10 Building s3-fixture
10:43:10 Building s3-fixture-with-session-token
10:43:10 Building s3-fixture-with-ec2
10:43:10 Building s3-fixture-with-ecs
10:43:11 /bin/sh: /tmp/_MEI257k26/libreadline.so.7: no version information available (required by /bin/sh)
10:43:11 Creating network "a0a8e30ec4a70b68abd8d4c03e0f240e_s3-fixture__default" with the default driver
10:43:11 Creating a0a8e30ec4a70b68abd8d4c03e0f240e_s3-fixture__s3-fixture-with-ecs_1 ... 
10:43:11 Creating a0a8e30ec4a70b68abd8d4c03e0f240e_s3-fixture__s3-fixture_1          ... 
10:43:11 Creating a0a8e30ec4a70b68abd8d4c03e0f240e_s3-fixture__s3-fixture-with-ec2_1 ... 
10:43:11 Creating a0a8e30ec4a70b68abd8d4c03e0f240e_s3-fixture__s3-fixture-with-session-token_1 ... 
10:43:12 Creating a0a8e30ec4a70b68abd8d4c03e0f240e_s3-fixture__s3-fixture_1                    ... error
10:43:13 
10:43:13 ERROR: for a0a8e30ec4a70b68abd8d4c03e0f240e_s3-fixture__s3-fixture_1  Cannot start service s3-fixture: unable to remount dir as readonly: mount tmpfs:/var/lib/docker/containers/31350c2929cd685fad880dc24f4c093aab60bdcbbc66e267261c776187945dbb/mounts/secrets, flags: 0x21, data: uid=0,gid=0: device or resource busy
10:43:13 Creating a0a8e30ec4a70b68abd8d4c03e0f240e_s3-fixture__s3-fixture-with-ecs_1           ... done
10:43:13 Creating a0a8e30ec4a70b68abd8d4c03e0f240e_s3-fixture__s3-fixture-with-ec2_1           ... done
10:43:13 Creating a0a8e30ec4a70b68abd8d4c03e0f240e_s3-fixture__s3-fixture-with-session-token_1 ... done
10:43:13 
10:43:13 ERROR: for s3-fixture  Cannot start service s3-fixture: unable to remount dir as readonly: mount tmpfs:/var/lib/docker/containers/31350c2929cd685fad880dc24f4c093aab60bdcbbc66e267261c776187945dbb/mounts/secrets, flags: 0x21, data: uid=0,gid=0: device or resource busy
10:43:13 Encountered errors while bringing up the project.
10:43:13 /bin/sh: /tmp/_MEId4lFDz/libreadline.so.7: no version information available (required by /bin/sh)
10:43:14 Stopping a0a8e30ec4a70b68abd8d4c03e0f240e_s3-fixture__s3-fixture-with-session-token_1 ... 
10:43:14 Stopping a0a8e30ec4a70b68abd8d4c03e0f240e_s3-fixture__s3-fixture-with-ec2_1           ... 
10:43:14 Stopping a0a8e30ec4a70b68abd8d4c03e0f240e_s3-fixture__s3-fixture-with-ecs_1           ... 
10:43:14 Stopping a0a8e30ec4a70b68abd8d4c03e0f240e_s3-fixture__s3-fixture-with-ecs_1           ... done
10:43:14 Stopping a0a8e30ec4a70b68abd8d4c03e0f240e_s3-fixture__s3-fixture-with-ec2_1           ... done
10:43:15 Stopping a0a8e30ec4a70b68abd8d4c03e0f240e_s3-fixture__s3-fixture-with-session-token_1 ... done
```

**Comment by mark-vieira** [comment] 2020-02-19 21:23
This is a duplicate of #48027.

**Closed by mark-vieira** 2020-02-19 21:23 UTC
Labels: :Core/Infra/Build, >test-failure
