### ISSUE TITLE
field collapsing very slow

### ISSUE THREAD

**Issue by zplzpl** [elastic/elasticsearch#24899] opened 2017-05-26 11:37 UTC
Only one field is used to collapsing . the field type is keyword.

hits.total = 1130 

The same request does not contain the collapsing that are only used for 13 milliseconds, using a collapsing using 130 milliseconds. (This time is CURL starttransfer time)

10x time.

Using the restful api.

**Comment by clintongormley** [comment] 2017-05-26 11:40
@zplzpl did you read the information that we asked for when you opened this issue? See https://github.com/elastic/elasticsearch/issues/new

**Comment by jimczi** [comment] 2017-05-28 19:08
Duplicate of #24900

**Closed by jimczi** 2017-05-28 19:08 UTC
Labels: :Search, feedback_needed
