### ISSUE TITLE
[CI] DocsClientYamlTestSuiteIT ILM tests failing on Windows

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#51899] opened 2020-02-05 00:10 UTC
We've been seeing a couple of YAML tests, specifically `test {yaml=reference\ilm\apis/get-lifecycle/line_49}` and `test {yaml=reference\ilm/update-lifecycle-policy/line_29}` failing regularly on Windows in CI. The errors are all very similar:

```
Failure at [reference\ilm\apis/get-lifecycle:42]: $body didn't match expected value:
                         $body: 
                       my_policy: 
                     modified_date: same [2020-02-04T22:57:46.144Z]
                            policy: 
                              phases: 
                                delete: 
                                 actions: 
                                    delete: same [empty map]
                                 min_age: same [30d]
                                  warm: 
                                 actions: 
                                forcemerge: 
                            max_num_segments: same [1]
                                 min_age: same [10d]
                           version: expected Integer [1] but was Integer [4]
```

Seem to be complaining about the policy version. Sounds like we are updating this policy multiple times or something isn't getting cleaned up. Not sure why this seems to be a Windows-only phenomenon.

https://gradle-enterprise.elastic.co/scans/tests?failures.failureClassification=non_verification&list.offset=0&list.size=50&list.sortColumn=startTime&list.sortOrder=desc&search.buildToolType=gradle&search.buildToolType=maven&search.startTimeMax=1580889599999&search.startTimeMin=1580544000000&search.tags=CI&search.tags=windows&tests.container=org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT&tests.sortField=FAILED&tests.unstableOnly&trends.section=overview&trends.timeResolution=day&viewer.tzOffset=-480

**Comment by probakowski** [comment] 2020-02-05 00:16
I think the same issue was tracked in #51605 and there was fix for that provided by @andreidan .
I wonder if these above are new instances or some leftovers from before the fix

**Comment by mark-vieira** [comment] 2020-02-05 00:20
I don't think that fix addressed these specifically. The link above has builds failing on `7.6`, `7.x` and `master` as recent as an hour ago.

**Comment by andreidan** [comment] 2020-02-05 09:24
I haven't backported the fix for #51605 to 7.6, and 7.x yet (doing that now). The recent failures in master, in the windows compatibility pipeline, are due to failures of `LoggingOutputStreamTests`

**Comment by andreidan** [comment] 2020-02-05 09:25
Duplicate of #51605

**Closed by andreidan** 2020-02-05 09:25 UTC
Labels: :Core/Features/ILM+SLM, >test-failure

**Comment by mark-vieira** [comment] 2020-02-05 15:21
Thanks @andreidan!
