### ISSUE TITLE
index.version.created contains bad version number: "8512000"

### ISSUE THREAD

**Issue by drallax** [elastic/elasticsearch#115796] opened 2024-10-28 17:08 UTC
### Elasticsearch Version

8.15.2, 8.15.3

### Installed Plugins

_bundled_

### Java Version

_bundled_

### OS Version

ubuntu 22.04

### Problem Description

index.version.created contains a bad version number: "8512000"

tested it on 
- a freshly downloaded and locally installed Elasticsearch,
- Elasticsearch docker container

both instances report index.version.created "8512000"
while the expected index.version.created would be "8150399" (for 8.15.3) or "8150299" (for 8.15.2)

### Steps to Reproduce

```
curl -CXPUT localhost:9200/testindex
curl -XGET localhost:9200/testindex
{"testindex":{"aliases":{},"mappings":{},"settings":{"index":{"routing":{"allocation":{
  "include":{"_tier_preference":"data_content"}}},
  "number_of_shards":"1","provided_name":"testindex","creation_date":"1730125116869","number_of_replicas":"1","uuid":"DQwhu-hvTPe8VAOrYvqlUA",
  "version":{"created":"8512000"}}}}
}
```

**Comment by jackchi** [comment] 2024-10-28 22:28
I am also experiencing this on `8.15.0`. 

After upgrading from `8.8.1` to `8.15.0` I noticed that on both my existing index and new index we are getting conflicting version numbers. 

This is concerning because the snapshots version also is different from ES version. 

# Index creation in ES 8.15.0
```bash
GET  es-end-point | jq .
{
  "name": "my-name",
  "cluster_name": "my-cluster",
  "version": {
    "number": "8.15.0",
    "build_flavor": "default",
    "build_type": "docker",
    "build_hash": "1a77947f34deddb41af25e6f0ddb8e830159c179",
    "build_date": "2024-08-05T10:05:34.233336849Z",
    "build_snapshot": false,
    "lucene_version": "9.11.1",
    "minimum_wire_compatibility_version": "7.17.0",
    "minimum_index_compatibility_version": "7.0.0"
  },
  "tagline": "You Know, for Search"
}
```

## Index creation

```
bash
green  open   jack-test-index sMlNoI5fRneobEJKcHJi_g   1   1          0            0       454b           227b         227b
```

## Wrong Index Settings Observed. 
```bash
curldp https://use1-c130-coordinator.prd-itbl.co/jack-test-index/_settings?pretty&human
{
  "jack-test-index" : {
    "settings" : {
      "index" : {
        "creation_date_string" : "2024-10-28T22:06:08.290Z",
        "routing" : {
          "allocation" : {
            "include" : {
              "_tier_preference" : "data_content"
            }
          }
        },
        "number_of_shards" : "1",
        "provided_name" : "jack-test-index",
        "creation_date" : "1730153168290",
        "number_of_replicas" : "1",
        "uuid" : "sMlNoI5fRneobEJKcHJi_g",
        "version" : {
          "created_string" : "8.14.4-snapshot[8512000]",
          "created" : "8512000"
        }
      }
    }
  }
}
```

## Snapshot Version Conflict

![Image](https://github.com/user-attachments/assets/38de5ef4-1690-4c14-b5bf-8a0cd24773ae)

We are running ECK and confirming that all nodes are restarted and cluster is GREEN. 
![Image](https://github.com/user-attachments/assets/d67f3bb2-d225-461b-a193-f32aef764d36)


Elasticsearch Slack thread for context https://elasticstack.slack.com/archives/CNTP6NLTZ/p1730152461400149

**Comment by rjernst** [comment] 2024-10-28 23:45
Index version created is an opaque integer representing when an index was created. In the past this has mapped to the internal id of Version.java. However, IndexVersion (and similarly TransportVersion) are now decoupled from Version. The id now no longer maps directly to version ids.

However, the string version should show up correctly as 8.15.0 in this case. The string version is determined via a reverse looking via a resource file mapping released version numbers to index version ids. The only way this can contain "snapshot" is if IndexVersion.CURRENT. It looks like there is a bug in how snapshot versions are handled that is overwriting the last known version. I was able to reproduce this issue by creating an index in 8.15.0 and seeing the same string version of `8.14.4-snapshot[8512000]`.

**Comment by rjernst** [comment] 2024-10-28 23:54
Ah, I think this was already addressed in 8.15.1, see https://github.com/elastic/elasticsearch/pull/112242

**Comment by rjernst** [comment] 2024-10-29 00:06
I can confirm this was fixed in 8.15.1. Running the same test there, I get:
```
"created_string" : "8.15.0-8.15.1"
```

And when running with 8.15.3 I get:
```
"created_string" : "8.15.0-8.15.3"
```

This is expected since the index version did not change for those versions.

Give the above, I hope you don't mind I close this issue, since the returned version is working as intended.

**Closed by rjernst** 2024-10-29 00:06 UTC
Labels: >bug, :Core/Infra/Core, Team:Core/Infra

**Comment by jackchi** [comment] 2024-10-29 21:27
hi @rjernst Ryan, just to confirm, the fix is in and I should try `8.15.3`?

**Comment by rjernst** [comment] 2024-10-30 00:28
Yes, the fix was released in 8.15.1.

**Comment by drallax** [comment] 2024-10-30 09:00
@rjernst Thanks for looking into this and clarifying the version number policy!

if can confirm that if I include `human` as a query parameter, ES will include an extra field `version.created_string` that contains the correct version number
```
curl -XGET http://localhost:9200/testindex?human | jq
{
  "testindex": {
    ...
    "settings": {
      "index": {
        ...
        "version": {
          "created_string": "8.15.0-8.15.3",
          "created": "8512000"
        }
      }
    }
  }
}
```

**Comment by thecoop** [comment] 2024-10-30 10:26
Yes, that string is included in human-readable settings
