### ISSUE TITLE
[CI] BuildPluginFuncTest applies checks failing

### ISSUE THREAD

**Issue by valeriy42** [elastic/elasticsearch#88246] opened 2022-07-04 10:26 UTC
The test seems to fail regularly in different Windows Environments. The failures started on June 28th 2022.

**Build scan:**
https://gradle-enterprise.elastic.co/s/bvkatzy4gixn2/tests/:integTest/org.elasticsearch.gradle.internal.BuildPluginFuncTest/applies%20checks

**Reproduction line:**
`null`

**Applicable branches:**
master

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.gradle.internal.BuildPluginFuncTest&tests.test=applies%20checks

**Failure excerpt:**
```
org.gradle.testkit.runner.UnexpectedBuildFailure: Unexpected build execution failure in C:\Users\jenkins\AppData\Local\Temp\junit17692165864845032350 with arguments [check, --configuration-cache, -Dtest.external=true]

Output:
Configuration cache is an incubating feature.
Calculating task graph as no configuration cache is available for tasks: check

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\jenkins\AppData\Local\Temp\junit17692165864845032350\build.gradle' line: 29

* What went wrong:
Could not compile build file 'C:\Users\jenkins\AppData\Local\Temp\junit17692165864845032350\build.gradle'.
> startup failed:
  build file 'C:\Users\jenkins\AppData\Local\Temp\junit17692165864845032350\build.gradle': 29: Unexpected character: '"' @ line 29, column 19.
                 url = "C:\Users\jenkins\AppData\Local\Temp\junit13185856896208040717\local-repo"
                       ^
  
  1 error


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Configuration cache entry stored.

  at org.gradle.testkit.runner.internal.DefaultGradleRunner.lambda$build$2(DefaultGradleRunner.java:264)
  at org.gradle.testkit.runner.internal.DefaultGradleRunner.run(DefaultGradleRunner.java:338)
  at org.gradle.testkit.runner.internal.DefaultGradleRunner.build(DefaultGradleRunner.java:262)
  at org.elasticsearch.gradle.internal.test.InternalAwareGradleRunner.build(InternalAwareGradleRunner.java:145)
  at org.elasticsearch.gradle.internal.test.ConfigurationCacheCompatibleAwareGradleRunner.build(ConfigurationCacheCompatibleAwareGradleRunner.java:153)
  at org.elasticsearch.gradle.internal.test.NormalizeOutputGradleRunner.build(NormalizeOutputGradleRunner.java:145)
  at org.elasticsearch.gradle.internal.BuildPluginFuncTest.applies checks(BuildPluginFuncTest.groovy:157)

```

**Comment by pugnascotia** [comment] 2022-07-04 11:55
@breskeby is this a dupe of #87913?

**Comment by breskeby** [comment] 2022-07-04 11:56
I think so. I'm about to merge a fix of above

**Comment by breskeby** [comment] 2022-07-04 17:12
Fixed in https://github.com/elastic/elasticsearch/pull/88240

**Closed by breskeby** 2022-07-04 17:12 UTC
Labels: :Delivery/Build, >test-failure, Team:Delivery
