### ISSUE TITLE
[CI] SearchableSnapshotActionIT.testSearchableSnapshotsInHotPhasePinnedToHotNodes

### ISSUE THREAD

**Issue by pugnascotia** [elastic/elasticsearch#82463] opened 2022-01-12 10:57 UTC
There seems to be some issue in the `ESRestTestCase` cleanup code that has triggered this failure.

**Build scan**:

https://gradle-enterprise.elastic.co/s/zytsjl7fdctfo

**Repro line**: 

```
./gradlew ':x-pack:plugin:ilm:qa:multi-node:javaRestTest' \
  --tests "org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT.testSearchableSnapshotsInHotPhasePinnedToHotNodes" \
  -Dtests.seed=28DC0BD4EBA705E7 -Dtests.locale=id -Dtests.timezone=America/Porto_Acre -Druntime.java=8
```

**Reproduces locally?**:

No.

**Applicable branches**:

7.17

**Failure history**:

This is the only failure right now.

**Failure excerpt**:

```
org.elasticsearch.client.ResponseException: method [DELETE], host [http://127.0.0.1:58828], URI [_snapshot/MtbXYNMJcvWU], status line [HTTP/1.1 500 Internal Server Error]
{"error":{"root_cause":[{"type":"illegal_state_exception","reason":"trying to modify or unregister repository [MtbXYNMJcvWU] that is currently used (found 1 searchable snapshots indices that use the repository: [restored-.ds-logs-trayhhvexq-2022.01.12-000002/1arsN9aSQ0mx-reYL1L2nA])"}],"type":"illegal_state_exception","reason":"trying to modify or unregister repository [MtbXYNMJcvWU] that is currently used (found 1 searchable snapshots indices that use the repository: [restored-.ds-logs-trayhhvexq-2022.01.12-000002/1arsN9aSQ0mx-reYL1L2nA])"},"status":500}
```

**Comment by arteam** [comment] 2022-01-19 13:57
Doesn't seem to reproduce anymore. I checked the test and it works for me locally in 7.17, 8.0 and master. It also hasn't failed on CI the last 7 days. I'm going to close the issue.

**Closed by arteam** 2022-01-19 13:57 UTC
Labels: :Distributed/Snapshot/Restore, >test-failure, Team:Distributed
