### ISSUE TITLE
Better changelog validation

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#98690] opened 2023-08-21 18:15 UTC
While there is some changelog validation that occurs in PRs, it seems to be separate from the changelog parsing that occurs as part of release notes generation. We should check each PR that parsing of the changelog works correctly.

See https://github.com/elastic/elasticsearch/pull/98689

**Comment by mark-vieira** [comment] 2023-10-04 21:16
I believe this is a duplicate of https://github.com/elastic/elasticsearch/issues/93840

**Closed by mark-vieira** 2023-10-04 21:16 UTC
Labels: >docs, :Delivery/Build, Team:Docs, Team:Delivery
