### ISSUE TITLE
For geo query distance returns farthest item first when it claims to boost closest

### ISSUE THREAD

**Issue by edwardcapriolo** [elastic/elasticsearch#80686] opened 2021-11-14 00:06 UTC
**Elasticsearch version** (`bin/elasticsearch --version`):
7.14

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):
Windowz 10

**Description of the problem including expected versus actual behavior**:

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-distance-feature-query.html

You can use the distance_feature query to find the nearest neighbors to a location. You can also use the query in a bool search’s should filter to add boosted relevance scores to the bool query’s scores.

When I use the feature the scores are highest for the "farthest" entities, and the scores are fractional and not very relevant. 

**Steps to reproduce**:

```
PUT /locations
{
  "mappings": {
    "properties": {
      "pin": {
        "properties": {
          "location": {
            "type": "geo_point"
          }
        }
      }
    }
  }
}

PUT /locations/_doc/1
{
  "attractionType": "monument",
  "name": "statue of liberty",
  "pin": {
    "location": {
      "lat": 40.6892,
      "lon": -74.044502
    }
  }
}

PUT /locations/_doc/2
{
  "attractionType": "theme park",
  "name": "Playland",
  "pin": {
    "location": {
      "lat": 40.981613,
      "lon": -73.691925
    }
  }
}

PUT /locations/_doc/3
{
  "attractionType": "monument",
  "name": "The Alamo",
  "pin": {
    "location": {
      "lat": 29.425171,
      "lon": -98.494614
    }
  }
}


GET /locations/_search
{
  "query": {
    "bool": {
      "must": {
        "match_all": {}
      },
      "should": {
        "distance_feature": {
          "field": "pin.location",
          "pivot": "100mi",
          "origin": [41.0340,  -73.7629],
          "boost": 2.0
        }
      },
      
      "filter": {
        "geo_distance": {
          
          "distance": "2000mi",
          "pin.location": {
            "lat": 41.0340,
            "lon": -73.7629
          }
        }
      }
    }
  }

}
```

Results in
```
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 3,
      "relation" : "eq"
    },
    "max_score" : 1.0218437,
    "hits" : [
      {
        "_index" : "locations",
        "_type" : "_doc",
        "_id" : "3",
        "_score" : 1.0218437,
        "_source" : {
          "attractionType" : "monument",
          "name" : "The Alamo",
          "pin" : {
            "location" : {
              "lat" : 29.425171,
              "lon" : -98.494614
            }
          }
        }
      },
      {
        "_index" : "locations",
        "_type" : "_doc",
        "_id" : "1",
        "_score" : 1.0211045,
        "_source" : {
          "attractionType" : "monument",
          "name" : "statue of liberty",
          "pin" : {
            "location" : {
              "lat" : 40.6892,
              "lon" : -74.044502
            }
          }
        }
      },
      {
        "_index" : "locations",
        "_type" : "_doc",
        "_id" : "2",
        "_score" : 1.0210775,
        "_source" : {
          "attractionType" : "theme park",
          "name" : "Playland",
          "pin" : {
            "location" : {
              "lat" : 40.981613,
              "lon" : -73.691925
            }
          }
        }
      }
    ]
  }
}
```

As you see the closest things have the lowest score. And the boosting is always small fractional numbers no matter how the pivot is tuned or how close are far things are.
**Provide logs (if relevant)**:

**Comment by imotov** [comment] 2021-11-19 23:23
I am going to close the issue since it seems to work as designed. 

@edwardcapriolo if you add sorting by geo distance, you will see that the point [41.034, -73.7629] is indeed closer to "The Alamo" (14574 km) than to the "Statue of Liberty" (15090 km). You can verify it yourself by running:

```
GET /locations/_search
{
  "query": {
    "bool": {
      "must": {
        "match_all": {}
      },
      "should": {
        "distance_feature": {
          "field": "pin.location",
          "pivot": "100mi",
          "origin": [
            41.034,
            -73.7629
          ],
          "boost": 2
        }
      },
      "filter": {
        "geo_distance": {
          "distance": "2000mi",
          "pin.location": {
            "lat": 41.034,
            "lon": -73.7629
          }
        }
      }
    }
  },
  "sort" : [
    {
      "_geo_distance" : {
          "pin.location" : [
            41.034,
            -73.7629
          ],
          "order" : "asc",
          "unit" : "km",
          "mode" : "min",
          "distance_type" : "arc",
          "ignore_unmapped": true
      }
    }
  ]
}
```

I think the issue is caused by the incorrect assumption that [41.034, -73.7629] is in White Plains, NY, while it is actually somewhere in [Antarctica](https://www.google.com/maps/place/73%C2%B045'46.4%22S+41%C2%B002'02.4%22E). Unfortunately, geopoints expressed as arrays [are using the `[lon, lat]` format](https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-point.html#CO45-4) and confuse a lot of new users. So, if you move your point back to White Plains, NY, you will get the expected results:

```
GET /locations/_search
{
  "query": {
    "bool": {
      "must": {
        "match_all": {}
      },
      "should": {
        "distance_feature": {
          "field": "pin.location",
          "pivot": "100mi",
          "origin": [
            -73.7629,
            41.034
          ],
          "boost": 2
        }
      },
      "filter": {
        "geo_distance": {
          "distance": "2000mi",
          "pin.location": {
            "lat": 41.034,
            "lon": -73.7629
          }
        }
      }
    }
  }
}
```

Alternatively, you can just stick with lat/lon notation:

```
GET /locations/_search
{
  "query": {
    "bool": {
      "must": {
        "match_all": {}
      },
      "should": {
        "distance_feature": {
          "field": "pin.location",
          "pivot": "100mi",
          "origin":  {
            "lat": 41.034,
            "lon": -73.7629
          },
          "boost": 2
        }
      },
      "filter": {
        "geo_distance": {
          "distance": "2000mi",
          "pin.location": {
            "lat": 41.034,
            "lon": -73.7629
          }
        }
      }
    }
  }
}
```

**Closed by imotov** 2021-11-19 23:23 UTC
Labels: >bug, :Analytics/Geo, team-discuss, Team:Analytics

**Comment by edwardcapriolo** [comment] 2021-11-20 14:25
@imotov Cool good find. I event tried plotting the point on the map in Kibana, but as you pointed out my query was transposed. Thanks for digging in.
