### ISSUE TITLE
Mount point not found on btrfs

### ISSUE THREAD

**Issue by TJC** [elastic/elasticsearch#23710] opened 2017-03-23 07:27 UTC
Essentially a duplicate of #14337 , but that was closed without insight two years ago, and I believe I have some more to add.

**Elasticsearch version**: 2.4.4

**Plugins installed**: []

**JVM version**: Oracle-sourced 1.8.0_111

**OS version**: Ubuntu 14.04

**Description of the problem including expected versus actual behavior**:

Ubuntu's standard btrfs filesystem setup is to have two subvolumes -- one for root, and one for /home.  
This server was configured as such.

Elasticsearch refused to start-up, throwing the following error about mount point not found.
```
Caused by: java.io.IOException: failed to obtain lock on /var/lib/elasticsearch/dc_sdlocal_net/nodes/49
        at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:186)
        ... 6 more
Caused by: java.io.IOException: Mount point not found
        at sun.nio.fs.LinuxFileStore.findMountEntry(LinuxFileStore.java:91)
```

**Steps to reproduce**:
 1. Install Ubuntu 14.04 (or 16.04 should work too) on a VM, selecting btrfs as the root filesystem type.
 2. Install elasticsearch.
 3. Attempt to start elasticsearch.

**Provide logs (if relevant)**:
```
[2017-03-23 17:38:42,660][INFO ][node                     ] [v04.dc.sdlocal.net] version[2.4.4], pid[8464], build[fcb
b46d/2017-01-03T11:33:16Z]
[2017-03-23 17:38:42,661][INFO ][node                     ] [v04.dc.sdlocal.net] initializing ...
[2017-03-23 17:38:43,055][INFO ][plugins                  ] [v04.dc.sdlocal.net] modules [reindex, lang-expression, l
ang-groovy], plugins [cloud-aws, hq], sites [hq]
[2017-03-23 17:38:43,080][ERROR][bootstrap                ] Exception
java.lang.IllegalStateException: Failed to obtain node lock, is the following location writable?: [/var/lib/elasticse
arch/dc_sdlocal_net]
        at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:199)
        at org.elasticsearch.node.Node.<init>(Node.java:165)
        at org.elasticsearch.node.Node.<init>(Node.java:140)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:194)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:286)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:45)
Caused by: java.io.IOException: failed to obtain lock on /var/lib/elasticsearch/dc_sdlocal_net/nodes/49
        at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:186)
        ... 6 more
Caused by: java.io.IOException: Mount point not found
        at sun.nio.fs.LinuxFileStore.findMountEntry(LinuxFileStore.java:91)
        at sun.nio.fs.UnixFileStore.<init>(UnixFileStore.java:65)
        at sun.nio.fs.LinuxFileStore.<init>(LinuxFileStore.java:44)
        at sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:51)
        at sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:39)
        at sun.nio.fs.UnixFileSystemProvider.getFileStore(UnixFileSystemProvider.java:368)
        at java.nio.file.Files.getFileStore(Files.java:1461)
        at org.elasticsearch.env.ESFileStore.getMatchingFileStore(ESFileStore.java:89)
        at org.elasticsearch.env.Environment.getFileStore(Environment.java:318)
        at org.elasticsearch.env.NodeEnvironment$NodePath.<init>(NodeEnvironment.java:93)
        at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:175)

.... logs continue but are not relevant
```

**Comment by TJC** [comment] 2017-03-23 07:31
I believe this is due to a bug in `sun.nio.fs.LinuxFileStore.findMountEntry` in regards to btrfs.

A work-around is to create *another* subvolume and mount that on /var/lib/elasticsearch.

ie. ```
mount /dev/sda1 /mnt/tmp
cd /mnt/tmp
ls
# shows @ and @home
btrfs subvol create @elasticsearch
cd /
umount /mnt/tmp
mount -o subvol=@elasticsearch /var/lib/elasticsearch
chown elasticsearch /var/lib/elasticsearch
```

elasticsearch now starts up fine.

**Comment by jasontedor** [comment] 2017-03-23 13:44
Closing as not an Elasticsearch issue.

**Closed by jasontedor** 2017-03-23 13:44 UTC

**Comment by nik9000** [comment] 2017-03-23 13:45
@TJC, do you want to file a bug with the jdk folks?

**Comment by jasontedor** [comment] 2017-03-23 14:23
There's a related JDK bug which already discusses btrfs: https://bugs.openjdk.java.net/browse/JDK-8165852

**Comment by jasontedor** [comment] 2017-03-23 14:24
See also this mail thread: http://mail.openjdk.java.net/pipermail/nio-dev/2016-October/003915.html

**Comment by jasontedor** [comment] 2017-03-23 14:25
Finally, I think this bug is the crux of the matter: https://bugs.openjdk.java.net/browse/JDK-8166162

I suspect that any newly opened bug reporting this issue would be closed as a duplicate of that one as that's the heart of the matter here for us.

**Comment by TJC** [comment] 2017-03-23 23:28
Why is ElasticSearch trying to find the mountpoint, anyway? Why does that matter?

**Comment by tvernum** [comment] 2017-03-23 23:44
Elasticsearch makes heavy use of the local filesystem to store indices. To do that safely and efficiently we need to monitor various properties of the filesystem (e.g. free disk space).

In Java the most effective way to do that is with a FileStore and the JRE requires the mount point in order to construct a FileStore.

**Comment by TJC** [comment] 2017-03-23 23:48
OK, that makes sense.

At the very least, could you improve the error message that is reported? The first sysadmin who hit this issue at my place was very confused, because he saw the top-level error saying "Cannot write.. is this directory writeable?" message, and went on a long diversion.

Whereas I investigated the "cannot find mountpoint" error that occurred further down the stacktrace in order to work this out.

**Comment by jasontedor** [comment] 2017-03-24 12:21
Here's the situation:

We are trying to lock the directory to ensure that no other instance of Elasticsearch could mutate the index files on disk at the same time, that would be a complete disaster. We failed to lock the directory. The vast majority of the time that locking the directory fails is because the directory is not writable (or, in 5.x, a user started multiple nodes without increasing the value of `node.max_local_storage_nodes`). Given these two facts:
1. We want to address the common problem, so the exception message indicates the most likely problem (and in 5.x we have modified it to say `maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes]`).
2. We also print actual cause of the problem.

What would you suggest that we do instead?

**Comment by TJC** [comment] 2017-03-27 07:07
I guess you have some kind of exception handler around the getFileStore call, right? (Looks like it from the stack trace).
In that handler, can you check to see if the error receives was "Mount point not found", and then re-iterate that error, rather than printing the "is directory writable" message?

**Comment by jasontedor** [comment] 2017-03-27 11:22
> In that handler, can you check to see if the error receives was "Mount point not found", and then re-iterate that error, rather than printing the "is directory writable" message?

I appreciate the suggestion, but I do not think it's worth parsing an exception message (something that in general we would like to avoid) for this very specific situation given that the full stack trace already shows the root cause of the problem.

**Comment by TJC** [comment] 2017-03-27 11:31
OK, no worries. Thanks for talking it over.
