### ISSUE TITLE
Bulk-update using Java Rest Client throws IOException

### ISSUE THREAD

**Issue by shobhanaquickride** [elastic/elasticsearch#28833] opened 2018-02-27 10:41 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 6.0.0

**Plugins installed**: [None]

**JVM version** (`java -version`): 1.8.0_45

**OS version** (`uname -a` if on a Unix-like system): Windows 10 64-bit OS

**Description of the problem including expected versus actual behavior**:
I am trying to bulk update one field in many documents using Java Rest Client. Here is how my code looks like :
```
String updateLastUsedTimeInBulkPath = "/_bulk"; // Tried with just "_bulk" also
StringEntity updateLastUsedTimeRequest = new StringEntity(jsonStringToUpdateLastUsedTimeInBulk);
updateLastUsedTimeRequest.setContentType("application/x-ndjson");
elasticServerRestClient.performRequest("POST", updateLastUsedTimeInBulkPath, Collections.<String, String>emptyMap(), updateLastUsedTimeRequest);
```
jsonStringToUpdateLastUsedTimeInBulk in the above code looks like the following :
```
{ "update" : {"_index" : "routematch", "_type" : "routematch", "_id" : "2686101,8264892"} }
{ "doc" : {"lastUsedTime" : "1519221900208"} }
{ "update" : {"_index" : "routematch", "_type" : "routematch", "_id" : "2686101,2686101"} }
{ "doc" : {"lastUsedTime" : "1519221900209"} }
```

Mapping is as follows :
```
PUT routematch
{
  "settings": {
    "number_of_shards": 5,
    "auto_expand_replicas": "0-all"
  },
  "mappings": {
    "routematch": {
      "properties": {
        ..............,
        "lastUsedTime": {"type": "long"}
      }
    }
  }
}
```

I tried to execute the same using Kibana and it worked fine and updated the field in all documents, but it always fails when executed using Java RestClient with following exception :
```
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.7.0_79]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[?:1.7.0_79]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.7.0_79]
	at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[?:1.7.0_79]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~[?:1.7.0_79]
	at org.apache.http.impl.nio.conn.LoggingIOSession$LoggingByteChannel.read(LoggingIOSession.java:204) ~[httpasyncclient-4.1.2.jar:4.1.2]
	at org.apache.http.impl.nio.reactor.SessionInputBufferImpl.fill(SessionInputBufferImpl.java:204) ~[httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.codecs.AbstractMessageParser.fillBuffer(AbstractMessageParser.java:136) ~[httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:241) ~[httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81) ~[httpasyncclient-4.1.2.jar:4.1.2]
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39) ~[httpasyncclient-4.1.2.jar:4.1.2]
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114) ~[httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) ~[httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) ~[httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) ~[httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) ~[httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588) ~[httpcore-nio-4.4.5.jar:4.4.5]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
```

Expected Result : Field value has to be updated in specified documents
Actual Result : IOException

**Steps to reproduce**:
 1. Create an index and a type
 2. Ingest data
 3. Use Java RestClient to bulk-update few fields in several documents

**Provide logs (if relevant)**:
Couldn't find any logs in elastic search during this time.

**Comment by tlrx** [comment] 2018-02-27 15:44
What is the error shown in Elasticsearch logs?

Also, note that you can use the Java REST High Level Client to execute Bulk requests: https://www.elastic.co/guide/en/elasticsearch/client/java-rest/6.0/java-rest-high-document-bulk.html

**Comment by shobhanaquickride** [comment] 2018-02-27 17:02
There were no errors/warn/info in Elasticsearch logs during this time!
I haven't used Java High Level REST Client; will check

**Comment by javanna** [comment] 2018-03-02 09:14
I am closing this given that you also asked the same question in our forums. This may very well be some usage issue. If it turns out to be a bug, we can always open another issue with a clear recreation.

**Closed by javanna** 2018-03-02 09:14 UTC
Labels: :Core/Java Low Level REST Client, feedback_needed

**Comment by shobhanaquickride** [comment] 2018-03-02 11:38
It has been 7 days since I first posted in the forum as well as on SO and I haven't heard anything there. I have followed the instructions given in Elastic search documents while coding and have rechecked the same several times. The same works fine when executed through Kibana but fails when run through Java rest client. Hence I strongly feel its a bug!

**Comment by javanna** [comment] 2018-03-02 13:34
@shobhanaquickride please let's continue this discussion in the forums until we know more. I will reply there. Not saying this cannot be a bug, just that I cannot reproduce it with the info I have, and it doesn't look like a bug.

**Comment by shobhanaquickride** [comment] 2018-03-02 17:45
Sure, no issues
