### ISSUE TITLE
mapper_parsing_exception when inserting document containing a key starting with 'geo'

### ISSUE THREAD

**Issue by etiennechabert** [elastic/elasticsearch#23081] opened 2017-02-09 16:42 UTC
**Version and so on** : "version": {
    "number": "2.4.4",
    "build_hash": "fcbb46dfd45562a9cf00c604b30849a6dec6b017",
    "build_timestamp": "2017-01-03T11:33:16Z",
    "build_snapshot": false,
    "lucene_version": "5.5.2"
  }

**How to reproduce** :  
Try to insert a document with the following json :
{
	"geoTest": "data"
}

**Response Error** :
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "failed to parse"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "failed to parse",
    "caused_by": {
      "type": "illegal_argument_exception",
      "reason": "illegal latitude value [268.59375] for geoTest"
    }
  },
  "status": 400
}

**Conclusion** :
Any key starting with the string "geo" produce this error

Best regards

**Comment by cbuescher** [comment] 2017-02-09 17:13
This doesn't reproduce. It looks like you have defined [dynamic templage](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-templates.html) somewhere that matches this key prefix. You should be able to see those in your mappings. Closing this for now, please use the [Discourse forum](https://discuss.elastic.co) or [IRC channels](https://www.elastic.co/community) if you cannot find the source of your problem.

**Closed by cbuescher** 2017-02-09 17:13 UTC
