### ISSUE TITLE
Gradle plugin for ES plugin development disables other language plugins

### ISSUE THREAD

**Issue by apatrida** [elastic/elasticsearch#28742] opened 2018-02-20 04:44 UTC
I am not sure of all the details yet, but starting this thread.

But somewhere between `5.6.4` and `5.6.7` of Elasticsearch and the `elasticsearch.esplugin`, or between `1.1.x` of Kotlin and `1.2.21` the two plugins no longer work together.  Something causes the Kotlin plugin to not function correctly.  The compiler runs, but it has no dependencies in its source sets.  Not sure which side this is on.

this is the failing branch of code:
https://github.com/kohesive/elasticsearch-lang-kotlin/tree/update-kotlin-1.2.21

Filed with Kotlin team as:
https://youtrack.jetbrains.com/issue/KT-22946

**Comment by apatrida** [comment] 2018-02-20 04:46
(yes, I know this is outdated ES version, but I have to get this version fixed before I can move forward to current versions)

**Comment by rjernst** [comment] 2018-02-20 05:58
Nothing was changed in 5.6 with the build. We noticed some changes in gradle behavior recently, but this was when updating to gradle 4.5 (see #28490 and https://discuss.gradle.org/t/test-task-has-empty-dependson-in-gradle-4-5/25704). But I do not think this is related to Elasticsearch, so I hope you don't mind that I close this issue. If you have reproduction instructions (and actual details for what "failing" means) then please reopen.

**Closed by rjernst** 2018-02-20 05:58 UTC

**Comment by apatrida** [comment] 2018-02-21 16:27
Well, the ES plugin plugin seems to now not let any library have tertiary dependencies, which appears to be a change yes?  Kotlin moved some things out of its embeddable compiler lib into separate tertiary dependencies and they now are not added, so this causes a clear issue.  So it appears I have to go dig up the full tree and manually include each level of dependency.  So it was caused by the ES plugin.

**Comment by apatrida** [comment] 2018-02-21 16:29
@rjernst "Nothing was changed in 5.6 with the build." other than not allowing tertiary dependencies in plugins, this probably broke quite a few of their builds.

**Comment by rjernst** [comment] 2018-02-21 16:50
@apatrida If by "tertiary dependencies" you mean transitive dependencies, the plugin has never allowed them. The gradle plugin is how we (Elastic) build our own plugins, and we want to know *exactly* which dependencies we are using, so we disable transitive dependencies within the entire build. But this has not changed; it has been that way since we switched to gradle in 5.0.

If you need help fixing your plugin, please open a [discuss thread](https://discuss.elastic.co/c/elasticsearch). Feel free to link it here and I will be happy to assist you there.

**Comment by apatrida** [comment] 2018-02-21 22:32
thanks, I'm all fixed, not sure why it was fine before and bad now. but all good today.
