### ISSUE TITLE
Force master reelection

### ISSUE THREAD

**Issue by mak-m** [elastic/elasticsearch#30812] opened 2018-05-23 12:51 UTC
For the sake of planned maintenance on master nodes it would be really good to have functionality to make the cluster leader to step down and transfer the leader role.

It might be invoked via an http API call. After the call is made the reelection happens with no downtime while there is an actual leader and after the reelection any other node takes over leadership.

**Comment by dliappis** [comment] 2018-05-23 13:49
Thanks for opening the issue.

Your feedback is very welcome and appreciated.

This was already discussed in https://github.com/elastic/elasticsearch/issues/17493 and https://discuss.elastic.co/t/transfer-the-master-role/36654/5

As mentioned by @DaveCTurner in [his comment](https://github.com/elastic/elasticsearch/issues/17493#issuecomment-365955243), "if you shut down Elasticsearch properly (and don’t just pull the plug) then a new master will be elected within a few seconds".

Therefore, I will be closing this as a duplicate of #17493.

**Closed by dliappis** 2018-05-23 13:49 UTC
Labels: :Distributed/ZenDiscovery
