### ISSUE TITLE
[CI] RcsCcsCommonYamlTestSuiteIT classMethod failing

### ISSUE THREAD

**Issue by fcofdez** [elastic/elasticsearch#93851] opened 2023-02-16 09:01 UTC
**Build scan:**
https://gradle-enterprise.elastic.co/s/aydspswsfic2g/tests/:qa:ccs-common-rest:yamlRestTest/org.elasticsearch.test.rest.yaml.RcsCcsCommonYamlTestSuiteIT

**Reproduction line:**
```
null
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.test.rest.yaml.RcsCcsCommonYamlTestSuiteIT&tests.test=classMethod

**Failure excerpt:**
```
java.lang.RuntimeException: An error occurred orchestrating test cluster.

  at __randomizedtesting.SeedInfo.seed([AA3796DB2EFF124C]:0)
  at org.elasticsearch.test.cluster.local.LocalClusterHandle.execute(LocalClusterHandle.java:236)
  at org.elasticsearch.test.cluster.local.LocalClusterHandle.writeUnicastHostsFile(LocalClusterHandle.java:217)
  at org.elasticsearch.test.cluster.local.LocalClusterHandle.waitUntilReady(LocalClusterHandle.java:160)
  at org.elasticsearch.test.cluster.local.LocalClusterHandle.start(LocalClusterHandle.java:70)
  at org.elasticsearch.test.cluster.local.LocalElasticsearchCluster$1.evaluate(LocalElasticsearchCluster.java:38)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

  Caused by: java.lang.RuntimeException: Elasticsearch process died while waiting for ports file. See console output for details.

    at org.elasticsearch.test.cluster.local.LocalClusterFactory$Node.lambda$waitUntilReady$0(LocalClusterFactory.java:210)
    at org.elasticsearch.test.cluster.util.Retry.lambda$retryUntilTrue$0(Retry.java:33)
    at org.elasticsearch.test.cluster.util.Retry.lambda$getValueWithTimeout$1(Retry.java:47)
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
    at java.lang.Thread.run(Thread.java:833)

```

**Comment by n1v0lg** [comment] 2023-02-16 09:36
I think this is possibly related also: https://gradle-enterprise.elastic.co/s/7mv554fpoyuyw

There is a slack thread discussing the above failure with ES-delivery as well: https://elastic.slack.com/archives/C01EMR8S1KN/p1676503911401289

I'll look a bit more into this but likely reassign to the delivery team.

**Comment by n1v0lg** [comment] 2023-02-16 09:38
This reproduces reliably with:

```
./gradlew ':qa:ccs-common-rest:yamlRestTest' --tests "org.elasticsearch.test.rest.yaml.RcsCcsCommonYamlTestSuiteIT" -Dtests.seed=AA3796DB2EFF124C -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dtests.locale=en-US -Dtests.timezone=Etc/UTC -Druntime.java=17 -Dlicense.key="x-pack/license-tools/src/test/resources/public.key"
```

**Comment by n1v0lg** [comment] 2023-02-16 09:53
Re-routing to delivery as this seems to be a more general build related issue. Including message from Slack here for context:

> I think there is probably a bug in how the new test cluster deals with release build. For example, this fails
./gradlew :x-pack:plugin:security:qa:service-account:javaRestTest --tests ServiceAccountIT -Dbuild.snapshot=false -Dlicense.key=x-pack/license-tools/src/test/resources/public.key
build scan [here](https://gradle-enterprise.elastic.co/s/7mv554fpoyuyw).
Looking at it briefly, I think it is because the system properties didn’t get propagated to the test cluster orchestration code. LocalDistributionResolver tries to resolve build.snapshot but it gets true instead of false.

The test class in the above message is different be the root cause appears to be the same.

**Comment by ywangd** [comment] 2023-02-17 05:13
There seem to be a genuine issue in plugin loading
https://github.com/elastic/elasticsearch/blob/ee3f3e1e6304c178131cb4302705f0beb3426b41/server/src/main/java/org/elasticsearch/plugins/PluginsService.java#L284-L294

The variable `loaded` is a HashMap and does not preserve the sorting order which leads to security being loaded before core.

**Comment by rjernst** [comment] 2023-02-17 14:50
I do not think there is an issue with plugin/module loading. The variable `loaded` isn't meant to ensure any ordering. Instead, the `sortedBundles` list is what determines the order to load plugins. That list is built by inspecting the inter-plugin dependencies in `PluginsUtils.sortBundles`. Unfortunately the actual order of loading is currently only shown at debug level (we should change that, I created https://github.com/elastic/elasticsearch/issues/93881, /cc @williamrandolph):
https://gist.github.com/rjernst/b176f58c4c41a0e90649ca1230ebf73f

You can see in that gist that x-pack-core was loaded first, then later security. The "loaded modules" lines are a name sorted list of those that were loaded (it used to be output as we were loading modules, that should be restored as part of https://github.com/elastic/elasticsearch/issues/93881).

However, there is a problem with the order of initialization. Once plugins are loaded, the Node constructor calls several methods on each plugin to initialize and collect various subsystems. The order of calling those methods for each plugin is currently not guaranteed. The original intention was that plugins should not have inter plugin ordering needs, but security is "special", and relies on several statics, like ssl context. I created https://github.com/elastic/elasticsearch/pull/93882 to guarantee the order, which for me fixes this test locally.

@mark-vieira I had to manually change RcsCcsCommonYamlTestSuitIT in order to enable debug logging for plugins. This used to be available via `-Dtests.es.xxxsetting=blah`. Perhaps that form needs to be added to the testclusters replacement?

**Comment by ywangd** [comment] 2023-02-20 03:07
> However, there is a problem with the order of initialization

Yeah I meant the order of initialization. Thanks for fixing it!

**Comment by davidkyle** [comment] 2023-02-20 10:32
There was a failure in the release tests today 

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+main+periodic+release-tests/672/consoleText

**Comment by gmarouli** [comment] 2023-02-21 08:39
Another failure: https://gradle-enterprise.elastic.co/s/kui76jmfbn67g/tests/:qa:ccs-common-rest:yamlRestTest/org.elasticsearch.test.rest.yaml.RcsCcsCommonYamlTestSuiteIT?top-execution=1

**Closed** 2023-02-21 14:25 UTC
Labels: :Core/Infra/Plugins, >test-failure, Team:Core/Infra

**Comment by mark-vieira** [comment] 2023-02-21 16:51
> @mark-vieira I had to manually change RcsCcsCommonYamlTestSuitIT in order to enable debug logging for plugins. This used to be available via `-Dtests.es.xxxsetting=blah`. Perhaps that form needs to be added to the testclusters replacement?

This is specific to the `:run` task. That was never the case for test clusters.
