### ISSUE TITLE
[CI] MixedClusterClientYamlTestSuiteIT test {p0=tsdb/90_unsupported_operations/sort by _id} failing

### ISSUE THREAD

**Issue by maxhniebergall** [elastic/elasticsearch#101536] opened 2023-10-30 16:31 UTC
This issue doesn't reproduce with the same error message as in build scan:

` ./gradlew ':qa:mixed-cluster:v7.17.15#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=tsdb/90_unsupported_operations/sort by _id}" -Dtests.seed=34938BC23C0EB8E9 -Dtests.bwc=true -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dtests.locale=ar-AE -Dtests.timezone=Indian/Mahe -Druntime.java=21` 

causes `FAILURE: Build failed with an exception.

* Where:
Build file '/Users/mh/workplace/elasticsearch/x-pack/plugin/core/build.gradle' line: 96

* What went wrong:
Could not determine the dependencies of task ':x-pack:plugin:analytics:compileJava'.
> Could not resolve all task dependencies for configuration ':x-pack:plugin:analytics:moduleCompileClasspath'.
   > Could not create task ':x-pack:plugin:core:processResources'.
      > Property license.key must be set for release build`

adding `-Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false"` results in 

`FAILURE: Build failed with an exception.

* Where:
Build file '/Users/mh/workplace/elasticsearch/x-pack/plugin/core/build.gradle' line: 96

* What went wrong:
Could not determine the dependencies of task ':x-pack:plugin:analytics:compileJava'.
> Could not resolve all task dependencies for configuration ':x-pack:plugin:analytics:moduleCompileClasspath'.
   > Could not create task ':x-pack:plugin:core:processResources'.
      > Property license.key must be set for release build`

adding `-Dlicense.key="$(pwd)/x-pack/license-tools/src/test/resources/public.key" -Dbuild.id=deadbeef` causes the build to succeed

**Build scan:**
https://gradle-enterprise.elastic.co/s/26yvbsn2aa42o/tests/:qa:mixed-cluster:v7.17.15%23mixedClusterTest/org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT/test%20%7Bp0=tsdb%2F90_unsupported_operations%2Fsort%20by%20_id%7D
**Reproduction line:**
```
./gradlew ':qa:mixed-cluster:v7.17.15#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=tsdb/90_unsupported_operations/sort by _id}" -Dtests.seed=34938BC23C0EB8E9 -Dtests.bwc=true -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dtests.locale=ar-AE -Dtests.timezone=Indian/Mahe -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT&tests.test=test%20%7Bp0%3Dtsdb/90_unsupported_operations/sort%20by%20_id%7D

**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([34938BC23C0EB8E9]:0)

```

**Comment by benwtrent** [comment] 2023-10-31 10:50
```
[2023-10-30T17:49:59,011][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] [test] [p0=tsdb/90_unsupported_operations/sort by _id] before test
....
[2023-10-30T17:49:59,456][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] [test] [p0=tsdb/90_unsupported_operations/sort by _id] after test
```

The individual test only ran for 300ms. The suite timed out and this test had little impact.

Closing as duplicate of: https://github.com/elastic/elasticsearch/issues/69973

**Closed by benwtrent** 2023-10-31 10:50 UTC
Labels: >bug, blocker, >test-failure, needs:triage
