### ISSUE TITLE
Test search/160_exists_query fails 

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#45581] opened 2019-08-14 20:53 UTC
Different tests in: search/160_exists_query failed 4 times within the last 3 days.
Doesn't reproduce for me.

One of the failures:
./gradlew :qa:smoke-test-multinode:integTestRunner --tests "org.elasticsearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT.test {yaml=search/160_exists_query/Test exists query on unmapped boolean field}" \
  -Dtests.seed=DBFD63CBEAAA3881 \
  -Dtests.security.manager=true \
  -Dtests.locale=bs-Cyrl \
  -Dtests.timezone=America/Edmonton \
  -Dcompiler.java=12 \
  -Druntime.java=11

Log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob+fast+part2/687/console
Build Scans: https://gradle-enterprise.elastic.co/s/szzo266jtkibm

Stack trace:
Caused by: java.lang.AssertionError: expected [2xx] status code but api [indices.create] returned [400 Bad Request] [{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [test/1U9nRH_AQUuf9dlIDGsWrQ] already exists"

I don't see any obvious  cause of this test failure. May be we need to simplify test setup. 
In test setup section we create and populate a lot of indexes not even needed for each test. May be should simplify  tests in`160_exists_query` and create indexes explicitly for each individual test.

---
Other failures:
REPRODUCE WITH: ./gradlew :qa:mixed-cluster:v8.0.0#mixedClusterTestRunner --tests "org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search/160_exists_query/Test exists query on unmapped long field}" \
  -Dtests.seed=20841EF407320797 \
  -Dtests.security.manager=true \
  -Dtests.locale=wo-SN \
  -Dtests.timezone=Etc/GMT+4 \
  -Dcompiler.java=12 \
  -Druntime.java=11

Log : https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=centos-6&&immutable/203/console
Build Scans: https://gradle-enterprise.elastic.co/s/cor3kexwy5wni

./gradlew :qa:smoke-test-multinode:integTestRunner --tests "org.elasticsearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT.test {yaml=search/160_exists_query/Test exists query on mapped byte field}" \
  -Dtests.seed=ABB917CFF8F733BB \
  -Dtests.security.manager=true \
  -Dtests.locale=fr-MR \
  -Dtests.timezone=America/Juneau \
  -Dcompiler.java=12 \
  -Druntime.java=11

Log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob+fast+part2/737/console
Build Scans: https://gradle-enterprise.elastic.co/s/uozrajje627bg

**Comment by mayya-sharipova** [comment] 2019-08-18 13:22
Looks like related to https://github.com/elastic/elasticsearch/issues/45605

**Comment by atorok** [comment] 2019-09-11 11:33
Closing as a duplicate of #46091,

**Closed by atorok** 2019-09-11 11:33 UTC
Labels: :Core/Infra/Build, :Search/Search, >test-failure
