### ISSUE TITLE
[CI] TasksIT testListTasksWaitForCompletion failing

### ISSUE THREAD

**Issue by pxsalehi** [elastic/elasticsearch#97923] opened 2023-07-25 10:39 UTC
**Build scan:**
https://gradle-enterprise.elastic.co/s/t3i5vfvymbgje/tests/:server:internalClusterTest/org.elasticsearch.action.admin.cluster.node.tasks.TasksIT/testListTasksWaitForCompletion

**Reproduction line:**
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.action.admin.cluster.node.tasks.TasksIT.testListTasksWaitForCompletion" -Dtests.seed=6739EE9186E7D99 -Dtests.locale=ar-AE -Dtests.timezone=SystemV/AST4 -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.action.admin.cluster.node.tasks.TasksIT&tests.test=testListTasksWaitForCompletion

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: a collection with size <1>
     but: collection size was <0>

  at __randomizedtesting.SeedInfo.seed([6739EE9186E7D99:702F563FA5C0E77A]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.action.admin.cluster.node.tasks.TasksIT.lambda$testListTasksWaitForCompletion$14(TasksIT.java:554)
  at org.elasticsearch.action.admin.cluster.node.tasks.TasksIT.waitForCompletionTestCase(TasksIT.java:640)
  at org.elasticsearch.action.admin.cluster.node.tasks.TasksIT.testListTasksWaitForCompletion(TasksIT.java:548)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

**Comment by volodk85** [comment] 2023-07-31 17:19
Fixed in https://github.com/elastic/elasticsearch/pull/98044

**Comment by mark-vieira** [comment] 2023-11-20 21:54
Here's another failure that should include the additional logging.

**Comment by DaveCTurner** [comment] 2023-11-23 13:13
I had a failure of this on my local machine. I'm suspicious about this bit being called too soon:

https://github.com/elastic/elasticsearch/blob/49f8446344311348f1d1602c0dd5b911137135a0/server/src/internalClusterTest/java/org/elasticsearch/action/admin/cluster/node/tasks/TasksIT.java#L602-L604

This finishes the wait if _any_ task is unregistered, but there's lots of tasks that shouldn't trigger that (e.g. fault detection).

**Comment by ywangd** [comment] 2023-12-13 06:03
Happend again https://gradle-enterprise.elastic.co/s/l442caargqi2s/tests/task/:server:internalClusterTest/details/org.elasticsearch.action.admin.cluster.node.tasks.TasksIT/testListTasksWaitForCompletion?top-execution=1

**Comment by idegtiarenko** [comment] 2024-01-09 14:03
>I had a failure of this on my local machine. I'm suspicious about this bit being called too soon

I think it is a correct guess. If task list is starting for a long time, something else could happen in a meanwhile. I was able to reproduce the failure with ~10% chance with:
```
Subject: [PATCH] format
---
Index: server/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/TransportListTasksAction.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/server/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/TransportListTasksAction.java b/server/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/TransportListTasksAction.java
--- a/server/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/TransportListTasksAction.java	(revision dcb019dc15165d73c9145d632ef1fb23231b09dc)
+++ b/server/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/TransportListTasksAction.java	(date 1704808639772)
@@ -94,6 +94,12 @@
     @Override
     protected void processTasks(CancellableTask nodeTask, ListTasksRequest request, ActionListener<List<Task>> nodeOperation) {
         if (request.getWaitForCompletion()) {
+            try {
+                Thread.sleep(500);
+            } catch (InterruptedException e) {
+                throw new RuntimeException(e);
+            }
+
             final ListenableActionFuture<List<Task>> future = new ListenableActionFuture<>();
             final List<Task> processedTasks = new ArrayList<>();
             final Set<Task> removedTasks = ConcurrentCollections.newConcurrentSet();
Index: server/src/internalClusterTest/java/org/elasticsearch/action/admin/cluster/node/tasks/TasksIT.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/server/src/internalClusterTest/java/org/elasticsearch/action/admin/cluster/node/tasks/TasksIT.java b/server/src/internalClusterTest/java/org/elasticsearch/action/admin/cluster/node/tasks/TasksIT.java
--- a/server/src/internalClusterTest/java/org/elasticsearch/action/admin/cluster/node/tasks/TasksIT.java	(revision dcb019dc15165d73c9145d632ef1fb23231b09dc)
+++ b/server/src/internalClusterTest/java/org/elasticsearch/action/admin/cluster/node/tasks/TasksIT.java	(date 1704808639752)
@@ -600,10 +600,12 @@
                     @Override
                     public void onTaskUnregistered(Task task) {
                         waitForWaitingToStart.countDown();
+                        logger.info("--> Unregistered task {}", task);
                     }
                 });
             }
 
+            logger.info("--> Starting wait task");
             // Spin up a request to wait for the test task to finish
             waitResponseFuture = wait.apply(taskId);
 
@@ -611,6 +613,7 @@
              * reference to the running task. Because we unblock immediately after this the task may no longer be running for us to wait
              * on which is fine. */
             waitForWaitingToStart.await();
+            logger.info("--> Unblocking test task");
         } finally {
             // Unblock the request so the wait for completion request can finish
             client().execute(UNBLOCK_TASK_ACTION, new TestTaskPlugin.UnblockTestTasksRequest()).get();
```
in my case it was always caused by `internal:coordination/fault_detection/leader_check`, `internal:coordination/fault_detection/follower_check` but other tasks are also present.

**Closed** 2024-02-05 13:11 UTC
Labels: >test-failure, :Distributed/Task Management, Team:Distributed, medium-risk
