### ISSUE TITLE
mixed-cluster test search_shards/10_basic/Search shards aliases with and without filters fails on 7.x

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#40838] opened 2019-04-04 10:59 UTC
## Example build failure

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+intake/898/
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+intake/897/
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+intake/896/

## Reproduction line 
does not reproduce locally
```
./gradlew ':qa:mixed-cluster:v6.7.1#mixedClusterTestRunner' -Dtests.seed=BE4EC91EA2995623 -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT -Dtests.method="test {p0=search_shards/10_basic/Search shards aliases with and without filters}" -Dtests.security.manager=true -Dtests.locale=el-CY -Dtests.timezone=Asia/Dushanbe -Dcompiler.java=12 -Druntime.java=8
```

## Example relevant log:
```
java.lang.AssertionError: Failure at [search_shards/10_basic:67]: indices.test_index.filter.bool.should.0.term.field.value didn't match expected value:
indices.test_index.filter.bool.should.0.term.field.value: expected [value1] but was [value2]

	at __randomizedtesting.SeedInfo.seed([BE4EC91EA2995623:361AF6C40C653BDB]:0)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:393)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:370)
	at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: indices.test_index.filter.bool.should.0.term.field.value didn't match expected value:
indices.test_index.filter.bool.should.0.term.field.value: expected [value1] but was [value2]

	at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:93)
	at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:76)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:386)
```

Wasn't sure how to label this one.

**Comment by hendrikmuhs** [comment] 2019-04-04 11:36
for 7.0: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+intake/627/consoleFull

**Comment by jpountz** [comment] 2019-04-04 11:41
Assigning to myself, likely related to the changes I pushed this morning.

**Comment by jpountz** [comment] 2019-04-04 12:08
OK I understand what happened now. My change changed the order in which filters are applied in aliases sometimes, and I had to accomodate one test for that. The problem is that the failing 7.1 and 7.0 jobs didn't have my change yet and tested against a 6.7 cluster that had the change already. I pushed at about the same time on 6.7, 7.0 and 7.x so I believe this only affected jobs that were waiting in the queue. I'll wait for at least one green build on each branch and then revert the commit that disables the test.

**Comment by jpountz** [comment] 2019-05-21 08:39
I had reverted in d6637eefb3b197d905e1d0024e2d77d3322e2dde and 7c27e5f243098d4251b865a7ac89636d874491f9 but then forgot to close this issue.

**Closed by jpountz** 2019-05-21 08:39 UTC
Labels: :Search/Search, >test-failure, v7.2.0
