### ISSUE TITLE
[CI] CreateIndexIT testNonNestedMappings failing

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#71919] opened 2021-04-20 11:40 UTC
**Build scan:**
https://gradle-enterprise.elastic.co/s/v3qnzl2twjlik/tests/:server:internalClusterTest/org.elasticsearch.action.admin.indices.create.CreateIndexIT/testNonNestedMappings

**Reproduction line:**
`./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.action.admin.indices.create.CreateIndexIT.testNonNestedMappings" -Dtests.seed=C94FFBDF3BA718EC -Dtests.security.manager=true -Dtests.locale=es-PA -Dtests.timezone=Etc/GMT+6 -Druntime.java=8`

**Applicable branches:**
7.x

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.action.admin.indices.create.CreateIndexIT&tests.test=testNonNestedMappings

**Failure excerpt:**
```
java.lang.IllegalStateException: Some shards are still open after the threadpool terminated. Something is leaking index readers or store references.

  at org.elasticsearch.node.Node.awaitClose(Node.java:1095)
  at org.elasticsearch.test.InternalTestCluster$NodeAndClient.close(InternalTestCluster.java:1085)
  at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:74)
  at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:116)
  at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:99)
  at org.elasticsearch.test.InternalTestCluster.close(InternalTestCluster.java:875)
  at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:74)
  at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:116)
  at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:99)
  at org.elasticsearch.test.ESIntegTestCase.clearClusters(ESIntegTestCase.java:536)
  at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:600)
  at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2255)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at java.lang.Thread.run(Thread.java:748)

```

**Comment by andreidan** [comment] 2021-04-20 15:14
I believe this might be a recovery issue 
```
Caused by: java.lang.RuntimeException: unclosed IndexInput: segments_2
	at org.apache.lucene.store.MockDirectoryWrapper.addFileHandle(MockDirectoryWrapper.java:735)
	at org.apache.lucene.store.MockDirectoryWrapper.openInput(MockDirectoryWrapper.java:778)
	at org.apache.lucene.store.FilterDirectory.openInput(FilterDirectory.java:100)
	at org.apache.lucene.store.FilterDirectory.openInput(FilterDirectory.java:100)
	at org.elasticsearch.indices.recovery.RecoverySourceHandler$2.onNewResource(RecoverySourceHandler.java:906)
	at org.elasticsearch.indices.recovery.RecoverySourceHandler$2.onNewResource(RecoverySourceHandler.java:896)
	at org.elasticsearch.indices.recovery.MultiChunkTransfer.getNextRequest(MultiChunkTransfer.java:145)
	at org.elasticsearch.indices.recovery.MultiChunkTransfer.handleItems(MultiChunkTransfer.java:102)
	at org.elasticsearch.indices.recovery.MultiChunkTransfer$1.write(MultiChunkTransfer.java:67)
	at org.elasticsearch.common.util.concurrent.AsyncIOProcessor.processList(AsyncIOProcessor.java:97)
	at org.elasticsearch.common.util.concurrent.AsyncIOProcessor.drainAndProcessAndRelease(AsyncIOProcessor.java:85)
	at org.elasticsearch.common.util.concurrent.AsyncIOProcessor.put(AsyncIOProcessor.java:73)
	at org.elasticsearch.indices.recovery.MultiChunkTransfer.addItem(MultiChunkTransfer.java:78)
	at org.elasticsearch.indices.recovery.MultiChunkTransfer.start(MultiChunkTransfer.java:74)
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.sendFiles(RecoverySourceHandler.java:951)
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.lambda$phase1$22(RecoverySourceHandler.java:526)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)

**Comment by andreidan** [comment] 2021-04-20 15:26
I believe this commit is the culprit 

https://github.com/elastic/elasticsearch/commit/74c20f1bc8b319faf60160cc5e77e3598dbd4554

**Comment by tlrx** [comment] 2021-04-21 13:17
I think that there is possibly a file leak in RecoverySourceHandler at  https://github.com/elastic/elasticsearch/blob/55eb4be172d33664a9beb152795b53c4a2b3e070/server/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java#L905-L906

where an `IndexInput` can be opened but never closed when the `MultiChunkTransfer` is closed.

**Comment by original-brownbear** [comment] 2021-04-21 13:21
@tlrx I think that's not it (though I suppose it could be an additional issue, should clean that up as well :)). I already reproduced the problem last night. The issue here is that we're somehow closing `IndexInput` instances after closing the associated `Store` when closing an index (I think it's coming from refreshes). Prior to https://github.com/elastic/elasticsearch/commit/74c20f1bc8b319faf60160cc5e77e3598dbd4554 this would go unnoticed since we just swallowed the exceptions from closing the store but not we trip the assert.

**Comment by jtibshirani** [comment] 2021-04-22 00:08
Another related failure: https://gradle-enterprise.elastic.co/s/dy62qabyvzl3e

Failure excerpt:
```
java.lang.RuntimeException: MockDirectoryWrapper: cannot close: there are still 1 open files: {segments_2=1} |  
-- | --
  | at org.apache.lucene.store.MockDirectoryWrapper.close(MockDirectoryWrapper.java:843) |  
  | at org.apache.lucene.store.FilterDirectory.close(FilterDirectory.java:110) |  
  | at org.apache.lucene.store.FilterDirectory.close(FilterDirectory.java:110) |  
  | at org.elasticsearch.index.store.Store$StoreDirectory.innerClose(Store.java:723) |  
  | at org.elasticsearch.index.store.Store$StoreDirectory.access$100(Store.java:693)
```

**Comment by original-brownbear** [comment] 2021-04-22 06:00
Seems Jay came to the same conclusion that I did here in https://github.com/elastic/elasticsearch/pull/72037

**Closed** 2021-04-23 12:22 UTC
Labels: :Distributed/Recovery, :Search/Mapping, >test-failure, Team:Distributed, Team:Search
