### ISSUE TITLE
s3-repository AWS S3 Outpost support

### ISSUE THREAD

**Issue by m00lecule** [elastic/elasticsearch#104280] opened 2024-01-11 18:02 UTC
### Elasticsearch Version

7.9.1

### Installed Plugins

s3-repository

### Java Version

_bundled_

### OS Version

6.2.0-39-generic

### Problem Description

Hello!

I am running Elasticsearch cluster on AWS EC2s on AWS Outpost (https://docs.aws.amazon.com/AmazonS3/latest/userguide/S3onOutposts.html). I am unable to register a snapshot repository using AWS Outpost S3 pointed by AWS Outpost S3 Access Point. What is weird that I am able to register snapshot repository on s3 through AccessPoint either by using AccessPoint ARN or alias when S3 is created in AWS Region, but for S3 on Outpost it is not possible. 

here are some examples how the AWS S3 Outpost client should look like: https://docs.aws.amazon.com/AmazonS3/latest/userguide/S3OutpostsGSCLIJava.html#S3OutpostsUploadObjects

I would kindly ask for a hint if this is even possible.

### Steps to Reproduce

Example PUT payloads:

1. AWS Outpost bucketname as bucket and AccessPoint full URL as endpoint
```
{
  "type": "s3",
  "settings": {
  "bucket": "es-snapshots-*******--op-s3",
  "region" : "us-west-2",
  "endpoint" : "es-snapshots-*******.op-*******.s3-outposts.us-west-2.amazonaws.com",
  "role_arn" : "arn:aws:iam::*******:role/elasticsearch-*******_role"
  }
}
```

Error response:
```
    sdk_client_exception: Unable to execute HTTP request: es-snapshots---op-s3.es-snapshots-.op-*******.s3-outposts.us-west-2.amazonaws.com
```

2. AWS Outpost bucketname as bucket and AccessPoint URL without bucketname as endpoint
```
{
  "type": "s3",
  "settings": {
  "bucket": "es-snapshots-*******--op-s3",
  "region" : "us-west-2",
  "endpoint" : "op-*******.s3-outposts.us-west-2.amazonaws.com",
  "role_arn" : "arn:aws:iam::*******:role/elasticsearch-*******_role"
  }
}
```
Error response:
```
    amazon_s3_exception: The authorization header is malformed; Incorrect service s3. This endpoint belongs to s3-outposts.
```

3. AWS Outpost bucketname as bucket and AccessPoint URL without bucketname and outpost ID as endpoint
```
{
  "type": "s3",
  "settings": {
  "bucket": "es-snapshots-*******--op-s3",
  "region" : "us-west-2",
  "endpoint" : "s3-outposts.us-west-2.amazonaws.com",
  "role_arn" : "arn:aws:iam::*******:role/elasticsearch-*******_role"
  }
}
```

Error response:
```
    sdk_client_exception: Unable to execute HTTP request: es-snapshots-*******--op-s3.s3-outposts.us-west-2.amazonaws.com
```

4. AWS Outpost bucket arn as bucket and AccessPoint full URL as endpoint
```
{
  "type": "s3",
  "settings": {
  "bucket": "arn:aws:s3-outposts:us-west-2:*******:outpost/op-*******/accesspoint/es-snapshots",
  "region" : "us-west-2",
  "endpoint" : "es-snapshots-*******.op-*******.s3-outposts.us-west-2.amazonaws.com",
  "role_arn" : "arn:aws:iam::*******:role/elasticsearch-*******_role"
  }
}
```

Error response:

```
    amazon_s3_exception: The authorization header is malformed; Incorrect service s3. This endpoint belongs to s3-outposts.
```
5. AWS S3 Bucket AccessPoint as bucketname on AWS Cloud region 
For example in AWS Cloud region it is possible to register s3 repository by using AccessPoint alias without any problems:
```
{
  "type": "s3",
  "settings": {
  "bucket": "elastic-*******-s3alias",
  "endpoint": "s3.us-west-2.amazonaws.com",
  "region" : "us-west-2",
  "role_arn" : "arn:aws:iam::*******:role/elasticsearch-*******_role"
  }
}
```

**Comment by DaveCTurner** [comment] 2024-01-11 18:11
Thank you very much for your interest in Elasticsearch. Unfortunately the issue you have reported relates to Elasticsearch version 7.9.1 which is very old and has passed [end-of-life](https://www.elastic.co/support/eol). We will not investigate issues related to unsupported versions here on Github, so I am closing this to indicate that no action is needed from the Elasticsearch development team. It's possible that you will find a volunteer to help you with this issue on the [community forums](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6), but our strong recommendation would be to upgrade to a supported version of Elasticsearch as a matter of some urgency. If you can reproduce your issue on a supported version then please open a fresh bug report.

Quoting the bug report form:

> Please also check your OS is [supported](https://www.elastic.co/support/matrix#show_os), and that the version of Elasticsearch has not passed [end-of-life](https://www.elastic.co/support/eol). If you are using an unsupported OS or an unsupported version then the issue is likely to be closed.

**Closed by DaveCTurner** 2024-01-11 18:11 UTC
Labels: >bug, needs:triage

**Comment by m00lecule** [comment] 2024-01-11 18:25
You are right @DaveCTurner, I will try to reproduce the latest elasticsearch version. But in general is AWS S3 Outpost supported by repository-s3 module?

**Comment by alkur-gh** [comment] 2024-06-07 10:49
Hi, had the same problem. Couldn't find any helpful material on this topic, but figured it out after some time. Maybe it can still be useful to someone.
From my understanding elasticsearch version must be at least [v7.17.18](https://github.com/elastic/elasticsearch/blame/8682172c2130b9a411b1bd5ff37c9792367de6b0/plugins/repository-s3/build.gradle#L26), because it's the first version which started to use aws-java-sdk with support for s3-outposts. Though i tested only v7.17.21. Not sure if the same settings will work for v8.x.x.
```
curl -X PUT "http://localhost:9200/_snapshot/my-s3-repo" -H "Content-Type: application/json" -d '
{
	"type": "s3",
	"settings": {
                // bucket is defined as arn because new aws-java-sdk parses some settings from it
                // such as service endpoint (s3 vs s3-outposts) which later used to sign http requests to s3
                // here i used access point arn, but maybe bucket arn may work too, didn't check though
		"bucket": "arn:aws:s3-outposts:{{ region }}:{{ account_id }}:outpost/{{ outpost_id }}/accesspoint/{{ accesspoint_name }}",

                // required
		"endpoint": "s3-outposts.{{ region }}.amazonaws.com",
		
                // required because x-amz-acl is not supported by outposts, and s3 api doesn't return an error only if this value is sent
                // https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html#API_PutObject_RequestSyntax
		"canned_acl": "bucket-owner-full-control",

                // required, same as above
		"storage_class": "OUTPOSTS"
	}
}
'
```
