### ISSUE TITLE
Highlight fails when using edge_ngram filter

### ISSUE THREAD

**Issue by ralgond** [elastic/elasticsearch#67820] opened 2021-01-21 12:26 UTC
The version of es is 7.10.1

I am using the edge_ngram filter in my analyzer, e.g. I index a word "EVA京", it will be mapped to an array [E, EV, EVA, 京]. And then I search "EV", of cause "EVA京" can be recalled. But the highlight works wrong! The result of highlight is "&lt;em&gt;EVA&lt;/em&gt;京", but not "&lt;em&gt;EV&lt;/em&gt;A京".

Can someone give me a hint how to correct the highlight result?

**Comment by mayya-sharipova** [comment] 2021-01-21 20:27
@ralgond  Thanks for submitting your issue. But this is not a bug, but an expected behaviour.

the edge_ngram filters doesn’t update the offsets of the terms so you would need to  switch to an edge_ngram tokenizer if you want to highlight partial words.

You can check how your terms get indexed by using `_termvectors` API.
```
GET <INDEX_NAME>/_termvectors/<DOC_ID>?fields=<FIElD_NAME>
```


For this reason,  I will be closing this issue.

**Closed by mayya-sharipova** 2021-01-21 20:27 UTC
Labels: :Search/Highlighting, >bug, Team:Search

**Comment by ralgond** [comment] 2021-01-24 07:47
@mayya-sharipova Thanks for your hint.  I have solved this problem by writing an analysis plugin. the github address of plugin is 
 https://github.com/ralgond/elasticsearch-analysis-edgengram
