### ISSUE TITLE
OpenID Connect APIs are missing API specification documents

### ISSUE THREAD

**Issue by sethmlarson** [elastic/elasticsearch#83559] opened 2022-02-04 22:39 UTC
The following OpenID APIs added in https://github.com/elastic/elasticsearch/pull/40674 don't have corresponding API spec documents:

- `POST /_security/oidc/authenticate`
- `POST /_security/oidc/prepare`
- `POST /_security/oidc/logout`

I'm proposing the following names if we decide to add API specs for these APIs:

- `security.oidc_authenticate`
- `security.oidc_prepare`
- `security.oidc_logout`

**Comment by rdnm** [comment] 2022-02-09 13:47
Hey @sethmlarson I'm closing this one as a duplicate of https://github.com/elastic/elasticsearch/issues/67189

**Closed by rdnm** 2022-02-09 13:47 UTC
Labels: :Core/Infra/REST API, Team:Core/Infra, Team:Clients
