### ISSUE TITLE
Too verbose logging creating significant garbage on master 

### ISSUE THREAD

**Issue by Bukhtawar** [elastic/elasticsearch#50900] opened 2020-01-13 10:00 UTC
## Problem
When a node goes bad due to hardware failure(checksum errors) or network disconnections, the async shard fetch does too verbose logging at a per shard listing basis generating too much garbage as seen below from one of the traces. This occurred on a ES 6.8 cluster, but my assumption is it would happen on later versions too. Please correct me if my understanding is wrong.

**Stack trace from JVM allocation profiler** 

`
[ 0] char[]
  [ 1] java.util.Arrays.copyOf
  [ 2] java.lang.AbstractStringBuilder.ensureCapacityInternal
  [ 3] java.lang.AbstractStringBuilder.append
  [ 4] java.lang.StringBuilder.append
  [ 2] java.lang.AbstractStringBuilder.ensureCapacityInternal
  [ 3] java.lang.AbstractStringBuilder.append
  [ 4] java.lang.StringBuilder.append
  [ 4] java.lang.StringBuilder.append
  [ 5] org.apache.logging.log4j.core.pattern.PlainTextRenderer.render
  [ 6] org.apache.logging.log4j.core.impl.ExtendedStackTraceElement.render
  [ 7] org.apache.logging.log4j.core.impl.ExtendedStackTraceElement.renderOn
  [ 8] org.apache.logging.log4j.core.impl.ThrowableProxy.formatEntry
  [ 9] org.apache.logging.log4j.core.impl.ThrowableProxy.formatElements
  [10] org.apache.logging.log4j.core.impl.ThrowableProxy.getExtendedStackTraceAsString
  [11] org.apache.logging.log4j.core.pattern.ExtendedThrowablePatternConverter.format
  [12] org.apache.logging.log4j.core.pattern.PatternFormatter.format
  [13] org.apache.logging.log4j.core.layout.PatternLayout$PatternSerializer.toSerializable
  [14] org.apache.logging.log4j.core.layout.PatternLayout.toText
  [15] org.apache.logging.log4j.core.layout.PatternLayout.encode
  [16] org.apache.logging.log4j.core.layout.PatternLayout.encode
  [17] org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent
  [18] org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend
  [19] org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append
  [20] org.apache.logging.log4j.core.appender.RollingFileAppender.append
  [21] org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender
  [22] org.apache.logging.log4j.core.config.AppenderControl.callAppender0
  [23] org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion
  [24] org.apache.logging.log4j.core.config.AppenderControl.callAppender
  [25] org.apache.logging.log4j.core.config.LoggerConfig.callAppenders
  [26] org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent
  [27] org.apache.logging.log4j.core.config.LoggerConfig.log
  [28] org.apache.logging.log4j.core.config.LoggerConfig.log
  [29] org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log
  [30] org.apache.logging.log4j.core.Logger.logMessage
  [31] org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage
  [32] org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion
  [33] org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely
  [34] org.apache.logging.log4j.spi.AbstractLogger.logMessage
  [35] org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled
  [36] org.apache.logging.log4j.spi.AbstractLogger.warn
  [37] org.elasticsearch.gateway.AsyncShardFetch.processAsyncFetch
  [38] org.elasticsearch.gateway.AsyncShardFetch$1.onResponse
  [39] org.elasticsearch.gateway.AsyncShardFetch$1.onResponse
  [40] org.elasticsearch.action.support.TransportAction$1.onResponse
  [41] org.elasticsearch.action.support.TransportAction$1.onResponse
  [42] org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.finishHim
  [43] org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.onFailure
  [44] org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.access$200
  [45] org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$1.handleException
  [46] org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException
  [47] org.elasticsearch.transport.TcpTransport.lambda$handleException$24
  [48] org.elasticsearch.transport.TcpTransport$$Lambda$2567.728518351.run
  [49] org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute
  [50] org.elasticsearch.transport.TcpTransport.handleException
  [51] org.elasticsearch.transport.TcpTransport.handlerResponseError
  [52] org.elasticsearch.transport.TcpTransport.messageReceived
  [53] org.elasticsearch.transport.TcpTransport.inboundMessage
  [25] org.apache.logging.log4j.core.config.LoggerConfig.callAppenders
  [26] org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent
  [27] org.apache.logging.log4j.core.config.LoggerConfig.log
  [28] org.apache.logging.log4j.core.config.LoggerConfig.log
  [29] org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log
  [30] org.apache.logging.log4j.core.Logger.logMessage
  [31] org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage
  [32] org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion
  [33] org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely
  [34] org.apache.logging.log4j.spi.AbstractLogger.logMessage
  [35] org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled
  [36] org.apache.logging.log4j.spi.AbstractLogger.warn
  [37] org.elasticsearch.gateway.AsyncShardFetch.processAsyncFetch
  [38] org.elasticsearch.gateway.AsyncShardFetch$1.onResponse
  [39] org.elasticsearch.gateway.AsyncShardFetch$1.onResponse
  [40] org.elasticsearch.action.support.TransportAction$1.onResponse
  [41] org.elasticsearch.action.support.TransportAction$1.onResponse
  [42] org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.finishHim
  [43] org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.onFailure
`

**Below is a sample exception on a hardware failure** 

`
Caused by: org.elasticsearch.transport.RemoteTransportException: [xxxxxx][10.xxx.xxx.xx:9300][internal:cluster/nodes/indices/shard/store[n]]
Caused by: org.elasticsearch.ElasticsearchException: Failed to list store metadata for shard [[test-2019.12.27-000225][109]]
	at org.elasticsearch.indices.store.TransportNodesListShardStoreMetaData.nodeOperation(TransportNodesListShardStoreMetaData.java:115) ~[elasticsearch-6.8.0.jar:6.8.0]
	at org.elasticsearch.indices.store.TransportNodesListShardStoreMetaData.nodeOperation(TransportNodesListShardStoreMetaData.java:61) ~[elasticsearch-6.8.0.jar:6.8.0]
	at org.elasticsearch.action.support.nodes.TransportNodesAction.nodeOperation(TransportNodesAction.java:138) ~[elasticsearch-6.8.0.jar:6.8.0]
	at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:259) ~[elasticsearch-6.8.0.jar:6.8.0]
...
Caused by: org.apache.lucene.index.CorruptIndexException: failed engine (reason: [recovery]) (resource=preexisting_corruption)
	at org.elasticsearch.index.store.Store.failIfCorrupted(Store.java:599) ~[elasticsearch-6.8.0.jar:6.8.0]
	at org.elasticsearch.index.store.Store.readMetadataSnapshot(Store.java:442) ~[elasticsearch-6.8.0.jar:6.8.0]
	at org.elasticsearch.indices.store.TransportNodesListShardStoreMetaData.listStoreMetaData(TransportNodesListShardStoreMetaData.java:155) ~[elasticsearch-6.8.0.jar:6.8.0]
	at org.elasticsearch.indices.store.TransportNodesListShardStoreMetaData.nodeOperation(TransportNodesListShardStoreMetaData.java:113) ~[elasticsearch-6.8.0.jar:6.8.0]
	at org.elasticsearch.indices.store.TransportNodesListShardStoreMetaData.nodeOperation(TransportNodesListShardStoreMetaData.java:61) ~[elasticsearch-6.8.0.jar:6.8.0]
	at org.elasticsearch.action.support.nodes.TransportNodesAction.nodeOperation(TransportNodesAction.java:138) ~[elasticsearch-6.8.0.jar:6.8.0]
	at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:259) ~[elasticsearch-6.8.0.jar:6.8.0]
	at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:255) ~[elasticsearch-6.8.0.jar:6.8.0]
`

**Comment by DaveCTurner** [comment] 2020-01-13 11:28
I don't think this is the case in more recent versions, but there's not enough detail in this issue to be sure. You've not even shared the whole stack trace, let alone any instructions for reproducing it, and my attempts to reproduce this in a more recent version have all failed. I am closing this. If you can demonstrate that this is still an issue in a more up-to-date version and can provide instructions to help us see the problem too then we can reopen it.

**Closed by DaveCTurner** 2020-01-13 11:28 UTC

**Comment by mohit0193** [comment] 2020-06-08 07:44
Problem: Too much logging of long exception stack traces results in log files getting rotated every few mins

We would like to know your early thoughts to fix it.

Printing same stack-trace for each shards doesn't seems to be beneficial so are thinking of using sampling based logging. And on other thought since, this stack-trace is not much useful for debugging so we can trim it also

**Comment by DaveCTurner** [comment] 2020-06-08 09:05
@mohit0193 I agree that a stack trace on a `NodeDisconnectedException` is not helpful here. Since this looks unrelated to the original issue (`NodeDisconnectedException` vs `CorruptIndexException`) would you open a new issue instead?

**Comment by Bukhtawar** [comment] 2020-06-08 09:15
>When a node goes bad due to hardware failure(checksum errors) or network disconnections

Thanks @DaveCTurner if you read the first line its related. I'm fine with a new issue as well

**Comment by DaveCTurner** [comment] 2020-06-08 10:52
Yeah the outer exception is the same, but the root cause is a `CorruptIndexException` which we don't see happening often enough to cause problems with log volume. `NodeDisconnectedException` is another matter.

**Comment by Bukhtawar** [comment] 2020-06-08 11:02
I had seen the same problem on both the cases node disconnections and otherwise but had only the `CorruptIndexException ` at that point in time so couldn't come back. Glad you replied.

**Comment by mohit0193** [comment] 2020-06-08 11:06
Thanks @DaveCTurner I have already started working on this. I would be interested in picking this up and open PR. I will create a new Github issue.

**Comment by mohit0193** [comment] 2020-06-08 11:17
created new Github issue: https://github.com/elastic/elasticsearch/issues/57804
