### ISSUE TITLE
[CI] Failure in BasicDistributedJobsIT.testFailOverBasics_withDataFeeder

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#40441] opened 2019-03-26 06:45 UTC
Failed on 6.7, doesn't reproduce.
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.7+internalClusterTest/3253/

[3253-console.txt.gz](https://github.com/elastic/elasticsearch/files/3006802/3253-console.txt.gz)

```
 1> [2019-03-26T13:20:17,422][INFO ][o.e.x.m.i.BasicDistributedJobsIT] [testFailOverBasics_withDataFeeder] [BasicDistributedJobsIT#testFailOverBasics_withDataFeeder]: cleaned up after test
  1> [2019-03-26T13:20:17,422][INFO ][o.e.x.m.i.BasicDistributedJobsIT] [testFailOverBasics_withDataFeeder] after test
ERROR   14.2s J2 | BasicDistributedJobsIT.testFailOverBasics_withDataFeeder <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 2
   > 	at org.elasticsearch.indices.IndicesQueryCache.close(IndicesQueryCache.java:189)
   > 	at org.elasticsearch.core.internal.io.IOUtils.closeWhileHandlingException(IOUtils.java:145)
   > 	at org.elasticsearch.core.internal.io.IOUtils.closeWhileHandlingException(IOUtils.java:130)
   > 	at org.elasticsearch.indices.IndicesService.doClose(IndicesService.java:298)
   > 	at org.elasticsearch.common.component.AbstractLifecycleComponent.close(AbstractLifecycleComponent.java:112)
   > 	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:103)
   > 	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:61)
   > 	at org.elasticsearch.node.NodeService.close(NodeService.java:135)
   > 	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:103)
   > 	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:85)
   > 	at org.elasticsearch.node.Node.close(Node.java:946)
   > 	at org.elasticsearch.test.InternalTestCluster$NodeAndClient.close(InternalTestCluster.java:1011)
   > 	at org.elasticsearch.test.InternalTestCluster.stopNodesAndClients(InternalTestCluster.java:1670)
   > 	at org.elasticsearch.test.InternalTestCluster.stopNodesAndClient(InternalTestCluster.java:1656)
   > 	at org.elasticsearch.test.InternalTestCluster.stopRandomDataNode(InternalTestCluster.java:1550)
   > 	at org.elasticsearch.xpack.ml.integration.BasicDistributedJobsIT.testFailOverBasics_withDataFeeder(BasicDistributedJobsIT.java:122)
   > 	at java.lang.Thread.run(Thread.java:748)Throwable #2: java.lang.RuntimeException: Had to resort to force-stopping datafeed, something went wrong?
   > 	at org.elasticsearch.xpack.ml.support.BaseMlIntegTestCase.deleteAllDatafeeds(BaseMlIntegTestCase.java:295)
   > 	at org.elasticsearch.xpack.ml.support.BaseMlIntegTestCase.cleanupWorkaround(BaseMlIntegTestCase.java:208)
   > 	at java.lang.Thread.run(Thread.java:748)
   > Caused by: java.util.concurrent.ExecutionException: MasterNotDiscoveredException[no known master node]
   > 	at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.getValue(BaseFuture.java:265)
   > 	at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:252)
   > 	at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:94)
   > 	at org.elasticsearch.xpack.ml.support.BaseMlIntegTestCase.deleteAllDatafeeds(BaseMlIntegTestCase.java:283)
   > 	... 36 more
   > Caused by: MasterNotDiscoveredException[no known master node]
   > 	at org.elasticsearch.xpack.ml.action.TransportStopDatafeedAction.doExecute(TransportStopDatafeedAction.java:113)
   > 	at org.elasticsearch.xpack.ml.action.TransportStopDatafeedAction.doExecute(TransportStopDatafeedAction.java:48)
   > 	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:167)
   > 	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:139)
   > 	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:81)
   > 	at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:87)
   > 	at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:76)
   > 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:403)
   > 	at org.elasticsearch.client.FilterClient.doExecute(FilterClient.java:68)
   > 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:403)
   > 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:391)
   > 	at org.elasticsearch.xpack.ml.support.BaseMlIntegTestCase.deleteAllDatafeeds(BaseMlIntegTestCase.java:282)
   > 	... 36 more
```

**Comment by droberts195** [comment] 2019-03-26 09:38
This is the same as https://github.com/elastic/elasticsearch/issues/37117#issuecomment-466949747, which seems to have been fixed in 7.1 and above by #39099 - see https://github.com/elastic/elasticsearch/issues/37117#issuecomment-476114159.

@jpountz how risky would it be to backport #39099 to the 6.7 branch?  CI will be running on 6.7 for another 18 months or so, so this failure will continue to plague us for a long time if the problem is left unfixed on the 6.7 branch.

**Comment by jpountz** [comment] 2019-03-26 10:04
@droberts195 It looks ok risk-wise. I will give it a try now.

**Comment by jpountz** [comment] 2019-03-26 13:47
@droberts195 I just backported to 7.0. On 6.7 I only backported the part that makes the map synchronized as the other changes relate to the introduction of ref-counting on open shards, which I think is unsafe for 6.7. Let's see whether this is enough to make things better.

**Comment by droberts195** [comment] 2019-03-26 13:56
Great, thanks for doing that so quickly @jpountz.  In a few weeks' time I will check the [build-stats](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-1y,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'stacktrace:%22org.elasticsearch.indices.IndicesQueryCache.close%22'),sort:!(time,desc))) link that tracks failures with `org.elasticsearch.indices.IndicesQueryCache.close` in a stack trace and see what the pattern looks like.

**Comment by droberts195** [comment] 2019-04-23 13:53
No test failure with `org.elasticsearch.indices.IndicesQueryCache.close` in its stack trace has been observed since 25th March, which is the day before the fix was backported to 6.7.

**Comment by davidkyle** [comment] 2019-04-30 10:47
Bah a new failure on the 6.7 branch. This is the only failure I can find since the fix went in. 

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.7+multijob-unix-compatibility/os=centos-7&&immutable/138/console

```
java.lang.AssertionError: 2
	at __randomizedtesting.SeedInfo.seed([70F57926E973817:E8BA0B69A990269A]:0)
	at org.elasticsearch.indices.IndicesQueryCache.close(IndicesQueryCache.java:190)
	at org.elasticsearch.core.internal.io.IOUtils.closeWhileHandlingException(IOUtils.java:145)
	at org.elasticsearch.core.internal.io.IOUtils.closeWhileHandlingException(IOUtils.java:130)
	at org.elasticsearch.indices.IndicesService.doClose(IndicesService.java:298)
	at org.elasticsearch.common.component.AbstractLifecycleComponent.close(AbstractLifecycleComponent.java:112)
	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:103)
	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:61)
	at org.elasticsearch.node.NodeService.close(NodeService.java:135)
	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:103)
	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:85)
	at org.elasticsearch.node.Node.close(Node.java:946)
	at org.elasticsearch.test.InternalTestCluster$NodeAndClient.close(InternalTestCluster.java:1011)
	at org.elasticsearch.test.InternalTestCluster.stopNodesAndClients(InternalTestCluster.java:1670)
	at org.elasticsearch.test.InternalTestCluster.stopNodesAndClient(InternalTestCluster.java:1656)
	at org.elasticsearch.test.InternalTestCluster.stopRandomDataNode(InternalTestCluster.java:1550)
	at org.elasticsearch.xpack.ml.integration.BasicDistributedJobsIT.testFailOverBasics_withDataFeeder(BasicDistributedJobsIT.java:122)
``` 

Looks like the partial fix described in https://github.com/elastic/elasticsearch/issues/40441#issuecomment-476646622 was not sufficient, reopening.

**Comment by droberts195** [comment] 2020-07-07 10:28
We haven't seen this problem recently, and given that the only failure was on the 6.7 branch and 6.7 is no longer being maintained I will close it.

**Closed by droberts195** 2020-07-07 10:28 UTC
Labels: :ml, >test-failure
