### ISSUE TITLE
Java 9: requiring elasticsearch from module-info.java fails with "module not found"

### ISSUE THREAD

**Issue by reda-alaoui** [elastic/elasticsearch#28984] opened 2018-03-12 01:49 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 6.2.2

**JVM version** (`java -version`): 9.0.4

**OS version** (`uname -a` if on a Unix-like system): Ubuntu 17.10

**Description of the problem including expected versus actual behavior**:

We are migrating our Maven project to Java 9.
In each module of our project, we add a `module-info.java`.
Everything works fine for every dependencies except elasticsearch.

Requiring it from module-info fails with:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project foo: Compilation failure
[ERROR] /foo/src/main/java/module-info.java:[10,12] module not found: elasticsearch
```

**Steps to reproduce**:

 1. Create basic maven project targeting JDK 9
 2. Add elasticsearch as a dependency
 3. Add a module-info.java with "requires elasticsearch;"
 4. Try to build the project

**Analysis**:

I debugged `maven-compiler-plugin` and that lead me to `jdk.internal.module.ModulePath`.
It fails in `jdk.internal.module.ModulePath` at line 557:
```java
// parse each service configuration file
        for (String sn : serviceNames) {
            JarEntry entry = jf.getJarEntry(SERVICES_PREFIX + sn);
            List<String> providerClasses = new ArrayList<>();
            try (InputStream in = jf.getInputStream(entry)) {
                BufferedReader reader
                    = new BufferedReader(new InputStreamReader(in, "UTF-8"));
                String cn;
                while ((cn = nextLine(reader)) != null) {
                    if (cn.length() > 0) {
                        String pn = packageName(cn);
                        if (!packages.contains(pn)) {
                            String msg = "Provider class " + cn + " not in module";
                            throw new InvalidModuleDescriptorException(msg); // <-- FAILING HERE
                        }
                        providerClasses.add(cn);
                    }
                }
            }
            if (!providerClasses.isEmpty())
                builder.provides(sn, providerClasses);
        }
```

The issue comes from the fact that no elasticsearch packages match the following declared Java services:
- server/src/main/resources/META-INF/services/org.apache.lucene.codecs.Codec
- server/src/main/resources/META-INF/services/org.apache.lucene.codecs.PostingsFormat
- server/src/main/resources/META-INF/services/org.apache.lucene.codecs.DocValuesFormat

Those service declarations either need to be moved to another project, or a fake class should be added to `org.apache.lucene.codecs`.

**Comment by reda-alaoui** [comment] 2018-03-13 18:10
After adding a fake class to the package, I discovered that I have now the exact same issue with dependency `groovy-all`.

**Comment by rjernst** [comment] 2018-03-13 22:25
> no elasticsearch packages match the following declared Java services

Can you elaborate on this? I think Codec and DocValuesFormat are leftover from long ago when we had custom versions of these in ES. PostingsFormat contains Completion50PostingsFormat which is still used. Is the issue just that Codec and DocValuesFormat are empty (we can remove them)?

**Comment by reda-alaoui** [comment] 2018-03-13 23:07
I added a Gradle test module in the PR, but I couldn't reproduce my maven project behaviour.
Maybe it is just a Maven issue.

@rjernst,
I didn't see that both of them were empty.
Still, the issue is also caused by org.apache.lucene.codecs.PostingsFormat for which I had to add 2 fake classes:
- https://github.com/Cosium/elasticsearch/blob/e4cac84d72413d1abfaa0b975d8f0b6959310db5/server/src/main/java/org/apache/lucene/search/suggest/document/JigsawMarker.java
- https://github.com/Cosium/elasticsearch/blob/e4cac84d72413d1abfaa0b975d8f0b6959310db5/server/src/main/java/org/apache/lucene/codecs/JigsawMarker.java

This is really weird.
I am creating a git repository with a Maven project reproducing the issue.

**Comment by reda-alaoui** [comment] 2018-03-13 23:44
I created https://github.com/Cosium/jigsaw-elasticsearch which allows to reproduce the issue.

**Comment by reda-alaoui** [comment] 2018-03-14 00:03
And a ticket in Maven compiler tracker https://issues.apache.org/jira/browse/MCOMPILER-328

**Comment by reda-alaoui** [comment] 2018-03-14 10:59
https://issues.apache.org/jira/browse/MCOMPILER-328?focusedCommentId=16398365&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16398365 confirms that Maven get the automodule name directly from the JDK.

That would mean that Gradle computes the module name itself, which is more brittle.

**Comment by reda-alaoui** [comment] 2018-03-14 11:12
I created a Gradle equivalent:
https://github.com/Cosium/jigsaw-elasticsearch-gradle
I reproduce the same issue as Maven.

Therefore:
- this issue still stands
- the Gradle consumer module that I added in the PR has another issue

**Comment by reda-alaoui** [comment] 2018-03-15 09:59
After much debugging !

# Classpath vs Modulepath in Java 9

The modulepath should contain all modular jars. That includes jars containing well defined `module-info.java` and jar *eligible* to automodule.
Elasticsearch is not currently eligible to automodule because it violates some Jigsaw encapsulation about Java services.

The classpath contain all the remaining jars.

A jar in the module path can't access to the classpath.

# Maven behaviour

For each jar:
- Maven provides the jar to JDK ModuleFinder
- If the ModuleFinder considers the Jar as a module, Maven adds the Jar to --module-path
- If the ModuleFinder does not consider the Jar as a module (i.e. elasticsearch), Maven adds it to -classpath

With elasticsearch as unique dependency:
```
[DEBUG] Command line options:
[DEBUG] -d /srv/git/cosium/jigsaw-elasticsearch/target/classes -classpath /srv/git/cosium/jigsaw-elasticsearch/target/classes:/home/rhousni/.m2/repository/org/elasticsearch/elasticsearch/6.2.2/elasticsearch-6.2.2.jar: -sourcepath /srv/git/cosium/jigsaw-elasticsearch/src/main/java:/srv/git/cosium/jigsaw-elasticsearch/target/generated-sources/annotations: -s /srv/git/cosium/jigsaw-elasticsearch/target/generated-sources/annotations -g -verbose -nowarn -target 9 -source 9
```

With commons-io as unique dependency:
```
[DEBUG] Command line options:
[DEBUG] -d /srv/git/cosium/jigsaw-elasticsearch/target/classes -classpath /srv/git/cosium/jigsaw-elasticsearch/target/classes: --module-path /home/rhousni/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar: -sourcepath /srv/git/cosium/jigsaw-elasticsearch/src/main/java:/srv/git/cosium/jigsaw-elasticsearch/target/generated-sources/annotations: -s /srv/git/cosium/jigsaw-elasticsearch/target/generated-sources/annotations -g -verbose -nowarn -target 9 -source 9
```

# Gradle behaviour

Gradle doesn't make any kind of jigsaw module autodetection.
By default, even in Java 9, Gradle will put all dependencies into the `classpath`.
This is confirmed by the [tutorial](https://guides.gradle.org/building-java-9-modules/#modify_the_code_compilejava_code_task_to_produce_a_module) that expects us to populate the `--module-path` and override `-classpath` manually.

It expects the user to provide manually the list of modules that should be put added to `--module-path`.

# Conclusion

The jar built by my project being defined by a `module-info.java`, it must resides in `--module-path`. Since elasticsearch fails the JDK automodule selection phase during Maven build, elasticsearch ends in `-classpath`, making it unreachable by my jar.

IMO, there is no point in trying to reproduce the current issue with a dedicated Gradle module, since it entirely depends on the way the end user will configure Gradle. Besides, it is unlikely that Gradle user is aware of the current issue since he will probably never use the JDK api allowing to select automodules.

So the fix seems to be the good one to me. 
The question seems to be what kind of automatic test could detect this kind of defect.

I think it would be easier to have a Maven module, since Maven has the correct behaviour. 
What do you think?

**Comment by reda-alaoui** [comment] 2018-03-28 08:05
Ping @rjernst , @jasontedor

**Comment by reda-alaoui** [comment] 2018-04-22 17:08
Ping @rjernst, @jasontedor

**Comment by nicolaiparlog** [comment] 2018-06-26 05:18
I don't understand how this is a `>non-issue`. On the contrary, this is a serious issue for anyone who wants to use the module system and I think it should be investigated.

**Comment by jasontedor** [comment] 2018-06-26 07:28
@nicolaiparlog The label was a mislabeling and I have removed it.

**Comment by reda-alaoui** [comment] 2018-07-11 08:40
@jasontedor the label is still on the linked PR

**Comment by tomdw** [comment] 2018-08-10 07:46
@jasontedor any idea on when this will be fixed/included in a release? thx!

**Comment by uschindler** [comment] 2018-09-04 22:27
You can only fix this by making Elasticsearch a real module. Automodules don't work for Elasticsearch. There are several problems: Elasticsearch contains classes from a package it does not own (org.apache.lucene) and also defines SPIs for them. This needs to be exposed via module-info.java. But this won't still not work, as Lucene is not module conformant (for the same reasons).

**Comment by tomdw** [comment] 2018-09-05 05:39
@uschindler as the discussion in this issue shows, there is a fix available, it only has to be merged and released. So converting to an explicit module is not needed yet. Putting an automatic module name in the manifest does no harm, on the contrary, it makes sure that elasticsearch reserves its module name.

**Comment by uschindler** [comment] 2018-09-05 06:14
The problem is that it won't still not work at runtime, because the SPI won't load. The good thing is that Elasticsearch does no longer implement SPIs (Codecs). And if you just use the Elasticsearch client, you won't run into trouble, because Lucene is just a dependency, but it's actually not used (only for classloading).

**Comment by tomdw** [comment] 2018-09-06 14:02
@uschindler thx for the clarification. I do think that if this gets fixed for elasticsearch it can be deployed as automatic module and we can keep lucene on the classpath for now. (automatic modules can read from the classpath) That way at least explicit modules can use the elasticsearch automatic module, and lucene remains on the classpath until a redesign has been done.

**Comment by reda-alaoui** [comment] 2019-02-01 13:38
> I was not able to replicate the issues with the empty service files just by requiring elasticsearch from a modules-info

As mentionned in the linked issue, if you did that with Gradle it's normal.
Try with Maven.

**Comment by atorok** [comment] 2019-02-04 08:20
Closing in favor of #38299

**Closed by atorok** 2019-02-04 08:20 UTC
Labels: :Core/Infra/Build, jdk9, team-discuss
