### ISSUE TITLE
integ-test-zip:integTestRunner is unable to run individual/suites of yaml tests

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#41380] opened 2019-04-19 15:51 UTC
It seems `:distribution:archives:integ-test-zip:integTestRunner` is unable execute specific YAML tests or "suites" of yaml tests when using the `--tests` syntax.  E.g. trying to run this command (from a failure repro line) or the entire `search.aggregations` suite:

```
./gradlew :distribution:archives:integ-test-zip:integTestRunner --tests "org.elasticsearch.test.rest.IntegTestZipClientYamlTestSuiteIT.test {p0=search.aggregation/Simple Composite aggregation}" -Dtests.seed=87CCC23B63F5ABF7 -Dtests.security.manager=true -Dtests.locale=saq -Dtests.timezone=Pacific/Chatham -Dcompiler.java=12 -Druntime.java=11
```
```
./gradlew :distribution:archives:integ-test-zip:integTestRunner --tests "org.elasticsearch.test.rest.IntegTestZipClientYamlTestSuiteIT.test {p0=search.aggregation/*}" -Dtests.seed=87CCC23B63F5ABF7 -Dtests.security.manager=true -Dtests.locale=saq -Dtests.timezone=Pacific/Chatham -Dcompiler.java=12 -Druntime.java=11
```
Both fail with an exception:

```
Execution failed for task ':distribution:archives:integ-test-zip:integTestRunner'.
> No tests found for given includes: [**/*IT.class](include rules) [**/*$*.class](exclude rules) [org.elasticsearch.test.rest.IntegTestZipClientYamlTestSuiteIT.test {p0=search.aggregation/*}](--tests filter)
```

This appears to be at least partially isolated to the `:distribution:archives:integ-test-zip:integTestRunner` tests, since a similar test run with `:x-pack:plugin:integTestRunner` works fine:

```
./gradlew :x-pack:plugin:integTestRunner --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=rollup/*}" -Dtests.seed=CE14E0490F1C442F -Dtests.security.manager=true -Dtests.locale=af-ZA -Dtests.timezone=Europe/Zurich -Dcompiler.java=12 -Druntime.java=11 -Dtests.rest.blacklist=getting_started/10_monitor_cluster_health/*
```

This is all on master, btw.

**Comment by atorok** [comment] 2019-09-05 12:15
The dot in the name of the YML tests confuses Gradle when parsing `--tests`. 
@mark-vieira do we have ideas on how to address this ? 
Maybe replace the dots in the test runner ? Or ban them and update all the tests to use something else ?

**Comment by mark-vieira** [comment] 2019-09-05 18:38
The solution here is to use the legacy `-Dtests.` sysprops. In fact, we've already fixed the reproduction lines in these scenarios to do exactly that via https://github.com/elastic/elasticsearch/pull/43255.

For ad-hoc requests to run one of these folks would have to know to use `-D` method when the test name includes a period. We _could_ document this but it'd still be confusing.

**Comment by atorok** [comment] 2019-09-06 07:30
That feels more like a workaround than a solution to me. It would be better to have a single way to do this.  I'm leaning towards changing the test name e.x. `s/[.]/_/` and adding a check that would not allow a dot in the test names going forward.

**Comment by mark-vieira** [comment] 2019-09-06 14:51
I'm not against that. Not sure how disruptive that would be but we can certainly do this.

**Comment by rjernst** [comment] 2019-09-11 18:40
I wonder if we need the test method run to be part of --tests long term. IMO the rest test runner should be essentially running a fixed test method, and the particular "test" that is run should be a separate system property, so we don't have to deal with the weird encoding of test names with special characters that aren't really test methods. Alternatively, if we continue using parameterized tests for running rest tests, we could have the test name be artificial. If we are going to modify, then let's just munge the test name for repro but not force any change on the actual test name in yaml.

**Comment by mark-vieira** [comment] 2019-09-11 18:54
> I wonder if we need the test method run to be part of --tests long term. IMO the rest test runner should be essentially running a fixed test method, and the particular "test" that is run should be a separate system property, so we don't have to deal with the weird encoding of test names with special characters that aren't really test methods.

I think this would result in a poor experience in terms of Junit test reporting though. In JUnit a "test" is a test method. If we had a single test case that ran one or more individual YAML tests then in things like build-stats and build scans all test results would be aggregated into a single test case. This would make it really hard to get any kind of useful metrics on individual test cases.

**Comment by atorok** [comment] 2019-10-09 13:25
Closing in favor of #47793

**Comment by mark-vieira** [comment] 2019-12-11 22:19
Going to close this since a workaround exists for test method names with a `.` which is to use `-Dtests.method`. Also, our reproduction line logic is aware of this and will use the system property mechanism instead of `--tests` when it finds a period in the test method name.

**Closed by mark-vieira** 2019-12-11 22:19 UTC
Labels: :Core/Infra/Build, >bug
