### ISSUE TITLE
Master should not stop the reallocation of the primary shards that have completed fetching shard data when a node restarts and a primary shard is still fetching shard data

### ISSUE THREAD

**Issue by kkewwei** [elastic/elasticsearch#87405] opened 2022-06-05 12:35 UTC
After a data nodes restarted and rejoined the cluster, the primary shards originally allocated on the node cannot be reallocated. To find the reason, I set the logger level of GatewayAllocator to be `debug`, and find that master loop print the following logs:
```
[2022-06-03T11:21:09,341][DEBUG][o.e.g.G.InternalPrimaryShardAllocator] [master1] [[index1/jnpkzL6nTvOAdDRfaRfvKA]][89]: found 1 allocation candidates of [index1][89], node[null], [P], recovery_source[existing store recovery; bootstrap_history_uuid=false], s[UNASSIGNED], unassigned_info[[reason=NODE_LEFT], at[2022-06-01T16:16:23.310Z], delayed=false, details[node_left [f38mcMSBRMW6n4k4ycLF0Q]], allocation_status[fetching_shard_data]] based on allocation ids: [[_22ekQc0RSKsZmZNobSONg]]
[2022-06-03T11:21:09,342][DEBUG][o.e.g.G.InternalPrimaryShardAllocator] [master1] [[index1/jnpkzL6nTvOAdDRfaRfvKA]][89]: allocating [[index1][89], node[null], [P], recovery_source[existing store recovery; bootstrap_history_uuid=false], s[UNASSIGNED], unassigned_info[[reason=NODE_LEFT], at[2022-06-01T16:16:23.310Z], delayed=false, details[node_left [f38mcMSBRMW6n4k4ycLF0Q]], allocation_status[fetching_shard_data]]] to [{gh-data-rt0257}{f38mcMSBRMW6n4k4ycLF0Q}{48F3nfaDS-2-XBnEY_PHiQ}{10.22.129.3}{10.22.129.3:9300}{dilrt}{ml.machine_memory=135202697216, rack=gha, ml.max_open_jobs=20, xpack.installed=true, transform.node=true}] on primary allocation
[2022-06-03T11:21:09,342][DEBUG][o.e.g.G.InternalPrimaryShardAllocator] [master1] [[index1/jnpkzL6nTvOAdDRfaRfvKA]][14]: found 1 allocation candidates of [index1][14], node[null], [P], recovery_source[existing store recovery; bootstrap_history_uuid=false], s[UNASSIGNED], unassigned_info[[reason=NODE_LEFT], at[2022-06-01T16:16:23.310Z], delayed=false, details[node_left [f38mcMSBRMW6n4k4ycLF0Q]], allocation_status[fetching_shard_data]] based on allocation ids: [[3dkPH5qZQkGjzzRextPLRw]]
[2022-06-03T11:21:09,342][DEBUG][o.e.g.G.InternalPrimaryShardAllocator] [master1] [[index1/jnpkzL6nTvOAdDRfaRfvKA]][14]: allocating [[index1][14], node[null], [P], recovery_source[existing store recovery; bootstrap_history_uuid=false], s[UNASSIGNED], unassigned_info[[reason=NODE_LEFT], at[2022-06-01T16:16:23.310Z], delayed=false, details[node_left [f38mcMSBRMW6n4k4ycLF0Q]], allocation_status[fetching_shard_data]]] to [{gh-data-rt0257}{f38mcMSBRMW6n4k4ycLF0Q}{48F3nfaDS-2-XBnEY_PHiQ}{10.22.129.3}{10.22.129.3:9300}{dilrt}{ml.machine_memory=135202697216, rack=gha, ml.max_open_jobs=20, xpack.installed=true, transform.node=true}] on primary allocation
[2022-06-03T11:21:09,342][DEBUG][o.e.g.G.InternalPrimaryShardAllocator] [master1] [[index1/jnpkzL6nTvOAdDRfaRfvKA]][164]: found 1 allocation candidates of [index1][164], node[null], [P], recovery_source[existing store recovery; bootstrap_history_uuid=false], s[UNASSIGNED], unassigned_info[[reason=NODE_LEFT], at[2022-06-01T16:16:23.310Z], delayed=false, details[node_left [f38mcMSBRMW6n4k4ycLF0Q]], allocation_status[fetching_shard_data]] based on allocation ids: [[-6LyyUkUS9y6yDQvCb8jRw]]
[2022-06-03T11:21:09,342][DEBUG][o.e.g.G.InternalPrimaryShardAllocator] [master1] [[index1/jnpkzL6nTvOAdDRfaRfvKA]][164]: allocating [[index1][164], node[null], [P], recovery_source[existing store recovery; bootstrap_history_uuid=false], s[UNASSIGNED], unassigned_info[[reason=NODE_LEFT], at[2022-06-01T16:16:23.310Z], delayed=false, details[node_left [f38mcMSBRMW6n4k4ycLF0Q]], allocation_status[fetching_shard_data]]] to [{gh-data-rt0257}{f38mcMSBRMW6n4k4ycLF0Q}{48F3nfaDS-2-XBnEY_PHiQ}{10.22.129.3}{10.22.129.3:9300}{dilrt}{ml.machine_memory=135202697216, rack=gha, ml.max_open_jobs=20, xpack.installed=true, transform.node=true}] on primary allocation
[2022-06-03T11:21:09,342][DEBUG][o.e.g.G.InternalPrimaryShardAllocator] [master1] [[index20/bAR8LaArQyCnK-eAnxPvXg]][62]: found 1 allocation candidates of [index20][62], node[null], [P], recovery_source[existing store recovery; bootstrap_history_uuid=false], s[UNASSIGNED], unassigned_info[[reason=NODE_LEFT], at[2022-06-01T16:16:23.306Z], delayed=false, details[node_left [f38mcMSBRMW6n4k4ycLF0Q]], allocation_status[fetching_shard_data]] based on allocation ids: [[qfzTDRikSpq-RwmjcTztXg]]
[2022-06-03T11:21:09,342][DEBUG][o.e.g.G.InternalPrimaryShardAllocator] [master1] [[index20/bAR8LaArQyCnK-eAnxPvXg]][62]: allocating [[index20][62], node[null], [P], recovery_source[existing store recovery; bootstrap_history_uuid=false], s[UNASSIGNED], unassigned_info[[reason=NODE_LEFT], at[2022-06-01T16:16:23.306Z], delayed=false, details[node_left [f38mcMSBRMW6n4k4ycLF0Q]], allocation_status[fetching_shard_data]]] to [{gh-data-rt0257}{f38mcMSBRMW6n4k4ycLF0Q}{48F3nfaDS-2-XBnEY_PHiQ}{10.22.129.3}{10.22.129.3:9300}{dilrt}{ml.machine_memory=135202697216, rack=gha, ml.max_open_jobs=20, xpack.installed=true, transform.node=true}] on primary allocation
[2022-06-03T11:21:09,342][DEBUG][o.e.g.G.InternalPrimaryShardAllocator] [master1] [[index20/bAR8LaArQyCnK-eAnxPvXg]][212]: found 1 allocation candidates of [index20][212], node[null], [P], recovery_source[existing store recovery; bootstrap_history_uuid=false], s[UNASSIGNED], unassigned_info[[reason=NODE_LEFT], at[2022-06-01T16:16:23.306Z], delayed=false, details[node_left [f38mcMSBRMW6n4k4ycLF0Q]], allocation_status[fetching_shard_data]] based on allocation ids: [[F6tAReDDQnC6Bg9iD2oQ6Q]]
```
The primary shards can't be reallocated the the node, we can see that the shard has completed fetching shard data, and find 1 allocation candidate, but it can't be really reallocated. It lasted several hours until the data is again restarted by some reason, all the shards are allocated successfully.

I guess that some of shards are fetching shard data, and don't receive the response, which result to the case. But I can't confirm that some shards are fetching shard data.

We can see that if one shard is fetching shard data, the other primary shards that have completed fetching shard data will be 
made the decision of FETCHING_SHARD_DATA by the master, and will be delayed to allocate, It doesn't seem reasonable.
https://github.com/elastic/elasticsearch/blob/f4b720e1dfd071156eace73a89d254ab23dd102c/server/src/main/java/org/elasticsearch/gateway/PrimaryShardAllocator.java#L222

If we remove the condition, the other primary shards that have completed fetching shard data will reallocated successfully.

**Comment by DaveCTurner** [comment] 2022-06-06 07:33
I don't think there's enough information given here to reproduce or even understand the issue you encountered. I appreciate that we could allocate some primaries even while fetching info about other primaries, but typically this process happens fairly quickly so this extra complexity would come with limited benefits in practice. Indeed as you say the shards all allocated properly after another restart which shows that the fundamental problem wasn't due to the `allocation.hasPendingAsyncFetch()` check you link. It sounds like something was stuck or running slowly somewhere, but we can't fix that without understanding what exactly was stuck or running slowly.

**Comment by kkewwei** [comment] 2022-06-08 02:48
The case doesn't happen again, sorry, I can't find the reason why it was stuck.

**Comment by DaveCTurner** [comment] 2022-06-08 07:36
Ok thanks for checking @kkewwei. I'll close this for now but if you get further details then we can reopen it again.

**Closed by DaveCTurner** 2022-06-08 07:36 UTC
Labels: feedback_needed, :Distributed/Allocation, Team:Distributed
