### ISSUE TITLE
Installing Elasticsearch 5.0.0-alpha1 rpm segfaults SLES11SP4

### ISSUE THREAD

**Issue by dliappis** [elastic/elasticsearch#17470] opened 2016-04-01 08:34 UTC
**Elasticsearch version**: 5.0.0-alpha1

**JVM version**: Oracle JDK 1.8.0_77-b03

**OS version**: SLES 11SP4

**Description of the problem including expected versus actual behavior**:

`elasticsearch 5.0.0-alpha1` rpm package is not installable on SLES11SP4. `rpm -i` fails complaining about the header and exits with a segmentation fault.
Tangentially to this, `gradle checkSles11` fails trying to install the created elasticsearch package.
Note that `elasticsearch-2.0.0.0.rpm` installs without problems.

Expected behavior is that `elasticsearch-5.0.0*.rpm` should be installable on SLES 11SP4 via `rpm` or `zypper`

**Steps to reproduce**:

1. clone [my forked branch](https://github.com/dliappis/elasticsearch/tree/add_sles11_support) containing the sles-11 vagrant additions
2. `gradle prepareTestRoot`
3. `vagrant up sles-11 && vagrant ssh sles-11`
4. `cd $TESTROOT`
5. `sudo bats $BATS/*_rpm_*.bats`

**Provide logs (if relevant)**:

1. Download and install elasticsearch-5.0.0-alpha1.rpm

  ```
sles-11:~$ sudo su -
sles-11:~$ pwd
/root
sles-11:~$ rpm -qa | grep -i elastic
sles-11:~$ wget http://download.elastic.co/elasticsearch/staging/5.0.0-alpha1-f27399d/org/elasticsearch/distribution/rpm/elasticsearch/5.0.0-alpha1/elasticsearch-5.0.0-alpha1.rpm
--2016-04-01 08:15:11--  http://download.elastic.co/elasticsearch/staging/5.0.0-alpha1-f27399d/org/elasticsearch/distribution/rpm/elasticsearch/5.0.0-alpha1/elasticsearch-5.0.0-alpha1.rpm
Resolving download.elastic.co... 184.72.244.137, 184.73.171.50, 184.73.186.87, ...
Connecting to download.elastic.co|184.72.244.137|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 26878246 (26M) [application/x-rpm]
Saving to: `elasticsearch-5.0.0-alpha1.rpm'

100%[=============================================================================>] 26,878,246  1.80M/s   in 19s     

2016-04-01 08:15:31 (1.37 MB/s) - `elasticsearch-5.0.0-alpha1.rpm' saved [26878246/26878246]

sles-11:~$ rpm -ivh ./elasticsearch-5.0.0-alpha1.rpm 
error: ./elasticsearch-5.0.0-alpha1.rpm: headerRead failed: Header sanity check: OK
Segmentation fault
```
  
2. Trying to install 5.0.0-alpha1 with zypper

  ```shell
sles-11:~$ sudo zypper ar -f -t rpm-md https://download.elastic.co/elasticsearch/staging/5.0.0-alpha1-f27399d/repos/5.x/centos elasticsearch
Adding repository 'elasticsearch' [done]
Repository named 'elasticsearch' already exists. Please use another alias.
sles-11:~$     sudo zypper install elasticsearch
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following NEW package is going to be installed:
  elasticsearch 

The following package is not supported by its vendor:
  elasticsearch 

1 new package to install.
Overall download size: 25.6 MiB. After the operation, additional 28.6 MiB will be used.
Continue? [y/n/? shows all options] (y): y
Installing: elasticsearch-5.0.0-alpha1 [error]
Installation of elasticsearch-5.0.0-alpha1 failed:
(with --nodeps --force) Error: Subprocess failed. Error: RPM failed: error: /var/cache/zypp/packages/elasticsearch/elasticsearch-5.0.0-alpha1.rpm: headerRead failed: Header sanity check: OK
```

**Comment by clintongormley** [comment] 2016-04-01 09:57
This looks like a bug in the gradle-ospackage-plugin.  We're not alone: https://github.com/nebula-plugins/gradle-ospackage-plugin/issues/162

**Comment by clintongormley** [comment] 2016-04-01 13:07
OK I've got SLES11 working, but the RPM has to be rebuilt with http://rpmrebuild.sourceforge.net/ which looks like it is available on at least opensuse and ubuntu.  Looks like redline (used by gradle's ospackage plugin) doesn't like rpm 4.4 - see https://github.com/craigwblake/redline/issues/97

rpmrebuild pointed out that we were missing some metadata eg License, which I'll open a PR to fix.

The init.d script required PR https://github.com/elastic/elasticsearch/pull/12555 in order to start.

**Comment by clintongormley** [comment] 2016-04-01 13:15
@rjernst see https://github.com/elastic/elasticsearch/issues/17470#issuecomment-204391452

**Comment by rjernst** [comment] 2016-04-05 23:26
I investigated this and commented on the redline issue. It looks like the problem is 4.4 only knew about md5 checksums, but redline writes md5 and sha1.  Using `rpmrebuild` works because it has special logic just for this case, where it writes the rpm file back out with only md5 digests.

**Comment by nik9000** [comment] 2016-04-08 13:58
@rjernst is this a thing you are actively working on? We've got SLES builds that constantly fail in Jenkins. Either we should fix them or disable them.

**Comment by nik9000** [comment] 2016-04-08 13:58
Example: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-os-compatibility/os=sles/221/console

**Comment by clintongormley** [comment] 2016-04-22 12:58
We can't support RPM installation on SLES11-SP4 (old version of RPM) so I'm going to close this.

**Closed by clintongormley** 2016-04-22 12:58 UTC
Labels: :Packaging, bug, v5.0.0
