### ISSUE TITLE
function_score ignores functions if inner query is filter-only

### ISSUE THREAD

**Issue by micpalmia** [elastic/elasticsearch#15921] opened 2016-01-12 08:53 UTC
Working on *Elasticsearch 2.1.1* - sorry in advance for the probably inaccurate terminology.

When the `query` section of a `function_score` query would not normally rank results (e.g., a `bool` query only containing `filter` and `must_not` clauses), the function score query ranks `0` all elements regardless of the listed `functions`.

Moving the filtering to an outside query works as expected.
In Elasticsearch 1.x, a `filtered` query only containing the `filter` section gets scored normally.

``` bash
curl -XPUT localhost:9200/test/test/1 -d '
{"rank": 1}'
curl -XPUT localhost:9200/test/test/2 -d '
{"rank": 2}'
curl -XPUT localhost:9200/test/test/3 -d '
{"rank": 3}'

# scores everything 0
curl -XPOST localhost:9200/test/test/_search -d '
{
   "query": {
      "function_score": {
         "query": {
            "bool": {
               "filter": {
                  "range": {
                     "rank": {
                        "gte": 2
                     }
                  }
               }
            }
         },
         "functions": [
            {
               "field_value_factor": {
                  "field": "rank"
               }
            }
         ]
      }
   }
}'

# scores appropriately
curl -XPOST localhost:9200/test/test/_search -d '
{
   "query": {
      "bool": {
         "filter": {
            "range": {
               "rank": {
                  "gte": 2
               }
            }
         },
         "must": {
            "function_score": {
               "functions": [
                  {
                     "field_value_factor": {
                        "field": "rank"
                     }
                  }
               ]
            }
         }
      }
   }
}'
```

**Comment by clintongormley** [comment] 2016-01-12 13:25
It appears the filter returns the score as `0` instead of `1`, which doesn't seem right.  @jpountz ?

**Comment by jpountz** [comment] 2016-01-12 14:58
The first query gives a score of 0 to all docs because there are no scoring clauses. In order to get a score of 1 you would need to add a `must` clause with a `match_all` query, or more simply since there is a single filter, wrap it under a `constant_score` query:

```
curl -XPOST localhost:9200/test/test/_search -d '
{
   "query": {
      "function_score": {
         "query": {
            "constant_score": {
               "range": {
                  "rank": {
                     "gte": 2
                  }
               }
            }
         },
         "functions": [
            {
               "field_value_factor": {
                  "field": "rank"
               }
            }
         ]
      }
   }
}'
```

**Comment by clintongormley** [comment] 2016-01-12 15:01
@jpountz this is surprising... filtered docs in 1.x were all given a score of 1.0.  Is this not possible with `bool.filter`?  If not, then this should be documented.

**Comment by jpountz** [comment] 2016-01-12 16:01
We could automatically add a match_all MUST clause if there are no positive clauses in order to get a score of one. But isn't it more natural to get null scores if there are no scoring clauses?

**Comment by micpalmia** [comment] 2016-01-12 16:09
Regardless of whether it's more natural to get a score of 1 or 0 in case there are no scoring clauses, a `match_all` clause is the default if the `query` clause inside the `function_score` query is not provided. It's thus surprising, when implementing a query with function scoring, that adding a few filtering query *removes* it.

**Comment by jpountz** [comment] 2016-01-12 17:27
But you did not just add filters, you overrode the default `match_all` query with another query that returns scores that are equal to 0.

Maybe what really needs to be done is further documenting the 2.0 upgrade notes about the `filtered` query. They already state that 
```
GET _search
{
  "query": {
    "filtered": {
      "query": {
        "match": {
          "text": "quick brown fox"
        }
      },
      "filter": {
        "term": {
          "status": "published"
        }
      }
    }
  }
}
```
needs to become
```
GET _search
{
  "query": {
    "bool": {
      "must": {
        "match": {
          "text": "quick brown fox"
        }
      },
      "filter": {
        "term": {
          "status": "published"
        }
      }
    }
  }
}
```
Maybe they should also document that
```
GET _search
{
  "filtered": {
    "filter": {
      "term": {
        "status": "published"
      }
    }
  }
}
```
needs to become
```
GET _search
{
  "query": {
    "constant_score": {
      "filter": {
        "term": {
          "status": "published"
        }
      }
    }
  }
}
```

**Comment by micpalmia** [comment] 2016-01-12 21:03
I think transforming an unscored 1.x query into a 2.x `constant_score` query is very much unnecessary most of the time. I happily transformed all the production queries that were filter-only into boolean filters without issues, because the output score was irrelevant.

The thing that I was personally missing (and that I think is not clear at all from the docs) is that unscored queries stopped returning a score of 1 for all documents and now return a score of 0. And this obviously has important consequences in a context in which scores get multiplied by each other, like in the `function_score` query.

**Comment by clintongormley** [comment] 2016-01-13 10:58
I've added the documentation here: https://github.com/elastic/elasticsearch/commit/33e7bb6fba5bf0a28d3fb5462cff931be579c366

Just wondering if the function score query should always have an implicit `match_all`, to make it function the way it did before.

**Comment by clintongormley** [comment] 2016-01-13 16:27
> Just wondering if the function score query should always have an implicit match_all, to make it function the way it did before.

To put this remark into context, I was thinking of having an implicit `match_all` if the user specified the `filter` parameter in the `function_score` query, but that parameter no longer exists in 2.0, so my remark doesn't make much sense. 

Given that the docs have been added, I think we can close this.

**Closed by clintongormley** 2016-01-13 16:27 UTC
Labels: :Search, adoptme, bug

**Comment by ZhangDi-d** [comment] 2021-07-29 03:52
> Working on _Elasticsearch 2.1.1_ - sorry in advance for the probably inaccurate terminology.
> 
> When the `query` section of a `function_score` query would not normally rank results (e.g., a `bool` query only containing `filter` and `must_not` clauses), the function score query ranks `0` all elements regardless of the listed `functions`.
> 
> Moving the filtering to an outside query works as expected.
> In Elasticsearch 1.x, a `filtered` query only containing the `filter` section gets scored normally.
> 
> ```shell
> curl -XPUT localhost:9200/test/test/1 -d '
> {"rank": 1}'
> curl -XPUT localhost:9200/test/test/2 -d '
> {"rank": 2}'
> curl -XPUT localhost:9200/test/test/3 -d '
> {"rank": 3}'
> 
> # scores everything 0
> curl -XPOST localhost:9200/test/test/_search -d '
> {
>    "query": {
>       "function_score": {
>          "query": {
>             "bool": {
>                "filter": {
>                   "range": {
>                      "rank": {
>                         "gte": 2
>                      }
>                   }
>                }
>             }
>          },
>          "functions": [
>             {
>                "field_value_factor": {
>                   "field": "rank"
>                }
>             }
>          ]
>       }
>    }
> }'
> 
> # scores appropriately
> curl -XPOST localhost:9200/test/test/_search -d '
> {
>    "query": {
>       "bool": {
>          "filter": {
>             "range": {
>                "rank": {
>                   "gte": 2
>                }
>             }
>          },
>          "must": {
>             "function_score": {
>                "functions": [
>                   {
>                      "field_value_factor": {
>                         "field": "rank"
>                      }
>                   }
>                ]
>             }
>          }
>       }
>    }
> }'
> ```

excuse me, I have a small question. If you don’t care about the function failure caused by the filter, will query 2 here have better performance than query 1（because it filters some results first）？

**Comment by jpountz** [comment] 2021-07-29 15:27
These queries should have about the same performance. In both cases results would be filtered before scores are computed.

**Comment by ZhangDi-d** [comment] 2021-07-30 01:55
> These queries should have about the same performance. In both cases results would be filtered before scores are computed.

dear jpountz，Thank you very much for your reply, I know I should go to the community or stackoverflow to ask questions, but please allow me to go deeper on the above question。Imagine we have some aggregations. What is the difference between query1 and query2 in performance?  Looking forward to your reply

```
curl -XPOST localhost:9200/test/test/_search -d '
{
   "query": {
      "function_score": {
         "query": {
            "bool": {
               "filter": {
                  "range": {
                     "rank": {
                        "gte": 2
                     }
                  }
               }
            }
         },
         "functions": [
            {
               "field_value_factor": {
                  "field": "rank"
               }
            }
         ]
      }
   },
   "aggs": {
     "some_agg": {
       "terms": {
         "field": "some_filed",
         "size": 10
       }
     }
   }
}'
```
```
curl -XPOST localhost:9200/test/test/_search -d '
{
   "query": {
      "bool": {
         "filter": {
            "range": {
               "rank": {
                  "gte": 2
               }
            }
         },
         "must": {
            "function_score": {
               "functions": [
                  {
                     "field_value_factor": {
                        "field": "rank"
                     }
                  }
               ]
            }
         }
      }
   },
   "aggs": {
     "some_agg": {
       "terms": {
         "field": "some_filed",
         "size": 10
       }
     }
   }
}'

```

**Comment by ZhangDi-d** [comment] 2021-07-30 06:37
I read some content, but I am not sure of the answer to the question...

https://stackoverflow.com/questions/53374292/when-using-function-score-in-elasticsearch-does-it-matter-if-filters-are-inside
https://www.elastic.co/cn/blog/elasticsearch-query-execution-order

**Comment by jpountz** [comment] 2021-07-30 06:51
Adding aggregations wouldn't change anything, these two queries would still be roughly equivalent.

**Comment by ZhangDi-d** [comment] 2021-07-30 06:59
Thank you very much for your reply, I have gained a lot. :)
