### ISSUE TITLE
Release 6.x wrongly marked as "latest" in GitHub releases

### ISSUE THREAD

**Issue by antoineco** [elastic/elasticsearch#75436] opened 2021-07-18 09:19 UTC
The latest Elasticsearch release (at the time of writing) included two new versions:
- `6.8.17` for the 6.x series
- `7.13.3` for the 7.x series

Instead of `7.13.3`, it's the `6.8.17` that was marked as "latest" on GitHub (see screenshot below).

This can yield unexpected results in CI pipelines. For example, the official [`octokit/request-action@v2.x`](https://github.com/octokit/request-action) GitHub Action can expose this "latest" release to subsequent workflow steps (with `GET /repos/:repository/releases/latest`) but, at the time of writing, the returned version of Elasticsearch is not the actual latest.

One example of unexpected result is a downgrade from 7.x to 6.x: https://github.com/deviantony/docker-elk/pull/602. (Of course it would be possible to improve the version comparison to avoid this, but the original issue would remain because `7.13.3` would never be seen as the "latest" release).

---

![image](https://user-images.githubusercontent.com/3299086/126061768-9633ad5e-da6d-45f8-91c2-fd79807655c8.png)

**Comment by DaveCTurner** [comment] 2021-07-19 06:47
Closing this as a duplicate of #75101. Github's `latest` tag doesn't work for projects like this one that maintain multiple release series at the same time, since it always links to the chronologically-latest release.

**Closed by DaveCTurner** 2021-07-19 06:47 UTC

**Comment by antoineco** [comment] 2021-07-19 07:36
> always links to the chronologically-latest release.

That is untrue. The "latest" version is user-defined on GitHub.

**Comment by DaveCTurner** [comment] 2021-07-19 07:46
Sorry if I'm just missing something obvious but I don't see the UI that lets the user change this. Could you guide me through what you mean?

I also don't see a way to do this in the API, and moreover the [API docs](https://docs.github.com/en/rest/reference/repos#get-the-latest-release) indicate that the latest release is based purely on the chronological order of commits:

> The latest release is the most recent non-prerelease, non-draft release, sorted by the created_at attribute. The created_at attribute is the date of the commit used for the release, and not the date when the release was drafted or published.

**Comment by antoineco** [comment] 2021-07-19 21:49
@DaveCTurner my apologies, I spoke too fast. The button I had in mind was "pre-release" when you [edit/create a release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository#editing-a-release) using the UI, but that is not the case of the 7.13.3 release. There is indeed no way to explicitly set this flag, spot on.

As an alternative, simply editing the release and saving (without actual changes) via the UI should force the latest semver to be flagged as the latest release. I thought this was the API's default behavior, but apparently not.

**Comment by DaveCTurner** [comment] 2021-07-20 08:16
> As an alternative, simply editing the release and saving (without actual changes) via the UI should force the latest semver to be flagged as the latest release.

This also isn't the case I think, the docs I quoted in my previous message indicate that "latest" is determined by the date of the commit. Anticipating your next suggestion, no, we won't be implementing any kind of history-rewriting mechanism to adjust the date of the released commit to work around this behaviour. Our release process involves choosing a candidate commit from the branch well before the release actually occurs, but may change our minds during the process, and may continue to push more changes to the branch at all times. Rewriting history to fix this would introduce so many other issues elsewhere.

TBC I absolutely do see how useful it would be to be able to do what you want, but the feature as implemented by Github today doesn't do that. I think this is something to raise with Github themselves.

**Comment by antoineco** [comment] 2021-07-20 08:18
@DaveCTurner I appreciate the effort anyway, thanks for your replies!
