### ISSUE TITLE
elasticsearch-5.6.1 is giving me such error 'Exception in thread "main" java.nio.file.AccessDeniedException:' when i'm trying to install any plugin on ubuntu machine

### ISSUE THREAD

**Issue by YashMangla** [elastic/elasticsearch#26786] opened 2017-09-25 21:21 UTC
-> Downloading ingest-geoip from elastic
[=================================================] 100%  
Exception in thread "main" java.nio.file.AccessDeniedException: /usr/share/elasticsearch/plugins/.installing-8466668133179145445
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
        at java.nio.file.Files.createDirectory(Files.java:674)
        at java.nio.file.TempFileHelper.create(TempFileHelper.java:136)
        at java.nio.file.TempFileHelper.createTempDirectory(TempFileHelper.java:173)
        at java.nio.file.Files.createTempDirectory(Files.java:950)
        at org.elasticsearch.plugins.InstallPluginCommand.stagingDirectory(InstallPluginCommand.java:448)
        at org.elasticsearch.plugins.InstallPluginCommand.unzip(InstallPluginCommand.java:396)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:216)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:201)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)

**Comment by jasontedor** [comment] 2017-09-25 21:30
You do not have permissions to create the file, probably because you did not run as `sudo`. This is not a bug. Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Closed by jasontedor** 2017-09-25 21:30 UTC

**Comment by EbolaWare** [comment] 2018-02-07 02:51
they do not mention running the install as root...

**Comment by HansaTheDeveloper** [comment] 2018-05-23 11:21
Exception in thread "main" java.nio.file.AccessDeniedException: /usr/share/elasticsearch/plugins/.installing-8466668133179145445

This means just give the permission of ' /usr/share/elasticsearch' folder. Error will resolve automatically. Thank you.

**Comment by YashMangla** [comment] 2018-05-24 06:20
I resolved this issue basically  in listed error our script doesn't have all permission as root user have so we can't able to create a files and folder which scripts needs to create to store meta info. So, there is 2 type of solution which you can perform.
1. you can run this command as a root user privilledges
or
2. you can allow this script permission like read/write/execute to all necessary files and folders. and sometimes you have to go that particular folder and allow all necessary permissions.

Thanks

**Comment by kelvin5349** [comment] 2019-05-03 08:23
I have the solution, even running as root it throws the same error as AccessDeniedException please do the following:

chmod 777 plugins/

this will give read, write, execute permission to the plugins folder since that is the folder the plugins will be installed. after doing so re-run the command again.

![1](https://user-images.githubusercontent.com/50230152/57126480-af600f00-6dbf-11e9-86b3-06badfffcd4b.JPG)
![2](https://user-images.githubusercontent.com/50230152/57126483-b2f39600-6dbf-11e9-9ccb-cd6d02296289.JPG)

**Comment by vamuzumd** [comment] 2020-10-30 18:51
I am facing the same error intermittently whiile installing multiple custom plugins in a for loop on Windows OS. More details on this [ES community thread](https://discuss.elastic.co/t/multiple-plugin-installations-on-windows-intermittently-fail-with-java-nio-accessdeniedexception/253630).
