### ISSUE TITLE
[PIT] ID string can become arbitrarily large.

### ISSUE THREAD

**Issue by tsullivan** [elastic/elasticsearch#98460] opened 2023-08-14 20:07 UTC
Kibana CSV reporting uses the PIT API to page through all the data requested for export by the user. This can create a slight problem in that a form of debug logging in Kibana captures request URLs and POST payloads sent to Elasticsearch. This can cause the entire PIT to be logged, which can create problems that make troubleshooting difficult. This can also make manually executing the search in Kibana's Dev Tools more tedious and challenging for humans, or just very slow.

Related: https://github.com/elastic/kibana/pull/163505#discussion_r1293843414

**Comment by javanna** [comment] 2024-07-17 12:45
Duplicate of #80187

**Closed by javanna** 2024-07-17 12:45 UTC
Labels: >bug, Team:Search Foundations, :Search Foundations/Search
