### ISSUE TITLE
NullPointerException on empty two node cluster

### ISSUE THREAD

**Issue by francoisprunier** [elastic/elasticsearch#25934] opened 2017-07-27 14:04 UTC
**Elasticsearch version**: 5.4.3

**Plugins installed**: [none]

**JVM version** (`java -version`): openjdk version "1.8.0_141"

**OS version** (`uname -a` if on a Unix-like system): 3.10.0-514.26.2.el7.x86_64 (centos)

**Description of the problem including expected versus actual behavior**:

We installed a two node cluster for our customer, left if alone and empty for a few days, and one night one of the node was down due to a null pointer exception. From the exception, it looks like something was trying to run a bucket script aggregation with an empty lucene expression script and failed. But based on the time it happened (4AM), it doesn't look like it was the customer running it. 

The cluster is empty except for a .kibana index.

**Steps to reproduce**:

I tried to reproduce it by running various bucket script aggregation but i couldn't.

**Provide logs (if relevant)**:
```
[2017-07-26T04:46:19,934][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [datalake3] fatal error in thread [elasticsearch[datalake3][search][T#6]], exiting
java.lang.ExceptionInInitializerError: null
        at org.elasticsearch.script.expression.ExpressionScriptEngineService$1.run(ExpressionScriptEngineService.java:106) ~[?:?]
        at org.elasticsearch.script.expression.ExpressionScriptEngineService$1.run(ExpressionScriptEngineService.java:85) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at org.elasticsearch.script.expression.ExpressionScriptEngineService.compile(ExpressionScriptEngineService.java:85) ~[?:?]
        at org.elasticsearch.script.ScriptService.compile(ScriptService.java:305) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.search.aggregations.pipeline.bucketscript.BucketScriptPipelineAggregator.reduce(BucketScriptPipelineAggregator.java:94) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.search.aggregations.InternalAggregation.reduce(InternalAggregation.java:122) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.search.aggregations.InternalAggregations.reduce(InternalAggregations.java:139) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.search.aggregations.bucket.filters.InternalFilters$InternalBucket.reduce(InternalFilters.java:100) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.search.aggregations.bucket.filters.InternalFilters.doReduce(InternalFilters.java:205) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.search.aggregations.InternalAggregation.reduce(InternalAggregation.java:119) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.search.aggregations.InternalAggregations.reduce(InternalAggregations.java:139) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.action.search.SearchPhaseController.reduceAggs(SearchPhaseController.java:513) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.action.search.SearchPhaseController.reducedQueryPhase(SearchPhaseController.java:490) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.action.search.SearchPhaseController.reducedQueryPhase(SearchPhaseController.java:408) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.action.search.SearchPhaseController$1.reduce(SearchPhaseController.java:725) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:102) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.action.search.FetchSearchPhase.access$000(FetchSearchPhase.java:45) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:87) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.4.3.jar:5.4.3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78) ~[?:?]
        at java.io.InputStreamReader.<init>(InputStreamReader.java:129) ~[?:?]
        at org.apache.lucene.util.IOUtils.getDecodingReader(IOUtils.java:155) ~[lucene-core-6.5.1.jar:6.5.1 cd1f23c63abe03ae650c75ec8ccb37762806cc75 - jimczi - 2017-04-21 12:17:15]
        at org.apache.lucene.util.IOUtils.getDecodingReader(IOUtils.java:178) ~[lucene-core-6.5.1.jar:6.5.1 cd1f23c63abe03ae650c75ec8ccb37762806cc75 - jimczi - 2017-04-21 12:17:15]
        at org.apache.lucene.expressions.js.JavascriptCompiler.<clinit>(JavascriptCompiler.java:695) ~[?:?]
        ... 24 more
```

**Comment by danielmitterdorfer** [comment] 2017-07-27 15:37
I spent quite a bit of time now trying to reproduce what you describe.

At the point the exception is thrown, Lucene tries to read the file `JavascriptCompiler.properties` via `java.lang.Class#getResourceAsStream()` which is bundled with Lucene. This suggests that there might be issues with the classpath. I assume that you are running Elasticsearch standalone and not embedded in some other application. I'd also do a review of the defined environment variables (`env`) for the user that is executing the elasticsearch process and check the contents of `$JAVA_HOME/jre/lib/ext`.

You could also either raise the log level of the root logger to `DEBUG` by changing the line with root logger in `config/elasticsearch.yml` to `rootLogger.level = debug`. It's less impact to start with setting the [slow log](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-slowlog.html) threshold to zero by [setting the following index-level setting](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-update-settings.html):

```
index.search.slowlog.threshold.query.info: 0s
```

By doing the latter you will get a list of all queries that are run but you need to this per index.

However, I also doubt that this is related to the query (I tried to reproduce it on 5.4.3 with JDK 1.8.0_141 with our [scripted metric aggregation example](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-scripted-metric-aggregation.html)) but maybe it's revealing something.

As the problem is not reproducible (neither by me nor by you) I am closing this for now. I hope that I've given you enough pointers to help you to narrow it down. If you found a way to reproduce this issue with the pointers I've given here, please feel free to reopen.

**Closed by danielmitterdorfer** 2017-07-27 15:37 UTC
