### ISSUE TITLE
index.mapper.dynamic is not honored during auto-creation of an index from template

### ISSUE THREAD

**Issue by tom-mi** [elastic/elasticsearch#17592] opened 2016-04-07 11:32 UTC
**Elasticsearch version**:  2.3.1

**JVM version**: 1.8.0_66

**OS version**: CentOS 7

**Description of the problem including expected versus actual behavior**:
When a new index is auto-created (by indexing a document) using an index template, the setting `index.mapper.dynamic` is not honored: If the document has an unmapped type, it gets indexed nevertheless and the additional type is added to the index.

*Expected result:* The indexing operation should be rejected as dynamic mapping is disabled for the index created from the template.

**Steps to reproduce**:

Create template:

    curl -XPUT localhost:9200/_template/test?pretty -d'
    {
      "template": "test_*",
      "settings": {
        "number_of_shards": 1,
        "index.mapper.dynamic": false
      },
      "mappings": {
        "foo": {
          "properties": {
            "name": {
              "type": "string"
            }
          }
        }
      }
    }'

Index data that does not match the mapping:

    curl -XPOST localhost:9200/test_1/bar?pretty -d'
    {
        "abc": "def"
    }'

Now, an index with an additional type "bar" has been created from the template, although dynamic mapping is set to false.

    curl -XGET localhost:9200/test_1?pretty
    {
      "test_1" : {
        "aliases" : { },
        "mappings" : {
          "foo" : {
            "properties" : {
              "name" : {
                "type" : "string"
              }
            }
          },
          "bar" : {
            "properties" : {
              "abc" : {
                "type" : "string"
              }
            }
          }
        },
        "settings" : {
          "index" : {
            "mapper" : {
              "dynamic" : "false"
            },
            "creation_date" : "1460026755596",
            "number_of_shards" : "1",
            "number_of_replicas" : "1",
            "uuid" : "EGWEI-iARECmY__EEa9jHg",
            "version" : {
              "created" : "2030199"
            }
          }
        },
        "warmers" : { }
      }
    }

**Comment by clintongormley** [comment] 2016-04-07 16:06
Related to https://github.com/elastic/elasticsearch/issues/17561

The difference is that, in this example, `index.mapper.dynamic` is set at the index level rather than in the config file in #17561.

**Comment by clintongormley** [comment] 2016-04-07 16:34
Probably caused by https://github.com/elastic/elasticsearch/pull/15424

**Comment by clintongormley** [comment] 2016-05-05 08:03
Actually investigating this further, this setting in the config file never worked correctly.  For instance, the following:

    PUT _template/test
    {
      "order": 0,
      "template": "persons*",
      "settings": {
        "index": {
          "number_of_shards": "1",
          "number_of_replicas": "0"
        }
      },
      "mappings": {
        "person": {
          "dynamic": "strict",
          "_all": {
            "enabled": false
          },
          "properties": {
            "name": {
              "index": "not_analyzed",
              "type": "string"
            }
          }
        }
      }
    }
    
Now put a document with type `personx`, which should have been prevented:

    PUT persons_1970/personx/1
    {
        "name" : "Henk"
    }

The `personx` type is added.  If the index already existed at the time we tried to add `personx`, then this would fail.  Setting `index.*` settings in the config file is no longer supported in 5.0 so I'm going to close this issue.

**Comment by clintongormley** [comment] 2016-05-05 08:08
Turns out this has always worked this way, it isn't a regression but it is a bug and could be improved.

**Closed** 2016-07-19 07:03 UTC
Labels: :Mapping, adoptme, bug, v5.0.0
