### ISSUE TITLE
[CI] TransformIT.testCreateDeleteWithDefer failed

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#51549] opened 2020-01-28 16:55 UTC
`TransformIT.testCreateDeleteWithDefer` failed in https://gradle-enterprise.elastic.co/s/6zifwxutcyys4

The error was:

```
org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=resource_not_found_exception, reason=Transform with id [test-with-defer] could not be found]
at __randomizedtesting.SeedInfo.seed([4AD13473B45DD1FF:8D1B8D1C19ADCBEE]:0)
at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177)
at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1823)
at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1800)
at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1557)
at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1529)
at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1496)
at org.elasticsearch.client.TransformClient.deleteTransform(TransformClient.java:194)
at org.elasticsearch.client.ESRestHighLevelClientTestCase.execute(ESRestHighLevelClientTestCase.java:101)
at org.elasticsearch.client.ESRestHighLevelClientTestCase.execute(ESRestHighLevelClientTestCase.java:92)
at org.elasticsearch.client.TransformIT.testCreateDeleteWithDefer(TransformIT.java:223)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:564)
at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
at java.lang.Thread.run(Thread.java:832)
```

This did not reproduce locally for me using:

```
./gradlew ':client:rest-high-level:integTestRunner' --tests "org.elasticsearch.client.TransformIT.testCreateDeleteWithDefer" \
  -Dtests.seed=4AD13473B45DD1FF \
  -Dtests.security.manager=true \
  -Dtests.locale=es-AR \
  -Dtests.timezone=Pacific/Galapagos \
  -Dcompiler.java=13
```

**Comment by hendrikmuhs** [comment] 2020-01-29 16:18
Another failure: https://gradle-enterprise.elastic.co/s/fq7byrn5izuow

I have not been able to find the root cause yet, neither locally nor by inspecting the logs, timing seems to be key. 

#51627 adds extra instrumentation to find the problem next time it happens.

**Comment by hendrikmuhs** [comment] 2020-02-14 11:43
status update: the failure did not happen in the last 16 days

**Comment by hendrikmuhs** [comment] 2020-03-03 09:44
this error has not been seen again, since the initial report. Therefore closing it.

**Closed by hendrikmuhs** 2020-03-03 09:44 UTC
Labels: :ml/Transform, >test-failure
