### ISSUE TITLE
Elasticsearch 5.6 on Suse linux 11.4 not able to change bind address in elasticsearch.yml

### ISSUE THREAD

**Issue by shahanepratap18** [elastic/elasticsearch#37417] opened 2019-01-14 12:26 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 5.6

**Plugins installed**: []

**JVM version** (`java -version`): OpenJDK 1.8

**OS version** (`uname -a` if on a Unix-like system): SLES 11.4

**Description of the problem including expected versus actual behavior**: Want to bind the elasticsearch host to IP other than 127.0.0.1. 
As per the installation documentation RPM package is not available for ES on Suse Linux 11. So we downloaded the source and ran the .sh in the folder. Now we changed the bind-address in elasticsearch.yml, after doing so Elasticsearch would not start again. Commented the bind-address back to its original state and it worked fine. 

**Steps to reproduce**:

 1. Download and Install Elasticsearch 5.4 on OpenSuse 11.4
 2. Start Elasticsearch using the .sh script file
 3. Change the bind-address in elasticsearch.yml, and try to start Elasticsearch again, it will not start.
 4. Revert the changes in elasticsearch.yml back, and start Elasticsearch. This would work fine.

**Comment by colings86** [comment] 2019-01-14 14:31
> Change the bind-address in elasticsearch.yml, and try to start Elasticsearch again, it will not start.

Could you show what the elasticsearch.yml file looks like after your changes when Elasticsearch wil not start?

Could you also have a look at the logs and paste the full stack trace of the error printed there?

**Comment by tvernum** [comment] 2019-01-15 05:53
@shahanepratap18 - I edited your comment to wrap the ES config in a code block (```)

**Comment by tvernum** [comment] 2019-01-15 05:59
@shahanepratap18 

The logs explain why Elasticsearch did not start:
```
[2] bootstrap checks failed
[1]: max file descriptors [8192] for elasticsearch process is too low, increase to at least [65536]
[2]: max size virtual memory [55651205120] for user [mitcon] is too low, increase to [unlimited]
```

When you modified the `network.host` value, you enabled _production mode_ which enforces the [bootstrap checks](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/bootstrap-checks.html).
You need to fix the 2 issues that are being reported in the logs:
1. [File Descriptors](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/_file_descriptor_check.html)
2. [Max size virtual memory](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/max-size-virtual-memory-check.html)

If you need further help with this, please ask on our [forums](https://discuss.elastic.co/c/elasticsearch). This allows us to use GitHub for verified bug reports, feature requests, and pull requests. The discussion forums are beter suited to walking through these kinds of configuration issues.

Since Elasticsearch is working as intended, I hope you don't mind that I close this issue, but please visit the [forums](https://discuss.elastic.co/c/elasticsearch) if you have more questions.

Thank you.

**Closed by tvernum** 2019-01-15 05:59 UTC
Labels: :Core/Infra/Core, feedback_needed

**Comment by shahanepratap18** [comment] 2019-01-15 06:38
Hello tvernum,
Thanks for valuable support after your instruction I had done changes in my system but the issue was not resolved, after that, I'll just add transport.host: localhost in elasticsearch.yml file after that issue was resolved.
Thanks for valuable support
