### ISSUE TITLE
Fuzziness not working with custom analyzer in "multi_match"

### ISSUE THREAD

**Issue by rishabh-traveloka** [elastic/elasticsearch#33084] opened 2018-08-23 09:36 UTC
**Describe the feature**: Fuzziness

**Elasticsearch version** (`bin/elasticsearch --version`):6.0

**Plugins installed**: []None

**JVM version** (`java -version`):1.8

**OS version** (`uname -a` if on a Unix-like system): EC2

**Description of the problem including expected versus actual behavior**:

When my custom analyzer generates two or more tokens , fuzziness is not applied and results are not obtained for the same.

**Steps to reproduce**:

1. Create Custom analyzer which generates two or more tokens for words like "chinese","tickets"=>"ticket" "tickets"

2. Make a multi match query with your custom analyzer and fuzziness applied , you wont get result as expected with fuzziness.

**QUERY**
```
"query": {
                    "bool": {
                      "should": [{
                        "multi_match": {
                        	"analyzer":"<custom analyzer>",
                          "fuzziness": "1",
                          "query": "chinepe",
                          "prefix_length": 3,
                          "fields": ["<filedName>"]
                        }
                      }]
                    } 

```

**Provide logs (if relevant)**:

**Comment by jpountz** [comment] 2018-08-23 12:58
Thanks for reporting this bug. Can you provide example mappings and documents that fail to match with this query?

**Comment by rishabh-traveloka** [comment] 2018-08-24 04:38
@jpountz ,
**Mapping** - Any Mapping with analyzer containing stemmer (generated two tokens for chinepe => chinep/chinese)

**Documents Not Matching:** Document containing "chinese" 

I cannot provide exact documents/mapping. Thanks for understanding.

**Comment by rishabhdugar** [comment] 2018-09-05 02:02
@jimczi  , @jpountz , any thoughts or comments on this?

**Comment by jpountz** [comment] 2018-09-07 12:43
@rishabh-traveloka If you could provide concrete mappings and queries that reproduce the problem, that would still be useful. It doesn't need to be exactly the ones that you use in production, just something minimal that helps reproduce the problem.

**Comment by javanna** [comment] 2018-10-02 11:52
@rishabh-traveloka @rishabhdugar could you kindly provide the requested info above?

**Comment by andyb-elastic** [comment] 2018-10-18 18:53
I couldn't reproduce this on 6.0.0 as described using a synonym token filter and fuzziness 1

Since we haven't gotten feedback I'm going to close the issue. @rishabh-traveloka if you're still seeing this issue and can provide a minimal mapping and query (it does not have to be what you're using in production) please comment and we'll re-open this issue

**Closed by andyb-elastic** 2018-10-18 18:53 UTC
Labels: :Search/Search, >bug, feedback_needed
