### ISSUE TITLE
GClient and GNode not exists in 1.5 any more but the documentation is very misleading

### ISSUE THREAD

**Issue by JamesLuoau** [elastic/elasticsearch#10944] opened 2015-05-04 06:04 UTC
http://www.elastic.co/guide/en/elasticsearch/client/groovy-api/current/client.html

Moved to Groovy extensions, so that this documentation should update

**Comment by clintongormley** [comment] 2015-05-04 13:22
Closing as duplicate of https://github.com/elastic/elasticsearch-groovy/issues/24

**Closed by clintongormley** 2015-05-04 13:22 UTC
