### ISSUE TITLE
CI: org.elasticsearch.client.MachineLearningIT » testEstimateMemoryUsage 

### ISSUE THREAD

**Issue by pugnascotia** [elastic/elasticsearch#46071] opened 2019-08-28 11:30 UTC
## Example build failure
https://gradle-enterprise.elastic.co/s/m4kgtux5zkwyo/tests/43nmsh6ur4gh6-lvl6vkkdfsfgs?openStackTraces=WzBd

## Reproduction line

Reproduces for me reliably on 7.x if I change `runtime.java` to 12 (I'm struggling to get it to run with a vaue of 8, even with a 1.8 JDK installed):

```
./gradlew :client:rest-high-level:integTestRunner --tests "org.elasticsearch.client.MachineLearningIT.testEstimateMemoryUsage" -Dtests.seed=B682ECA58AF6DA1F -Dtests.security.manager=true -Dtests.locale=fi-FI -Dtests.timezone=America/Sao_Paulo -Dcompiler.java=12 -Druntime.java=12
```

## Example relevant log
```
java.lang.AssertionError: 

Expected: (a value greater than <1kb> and a value less than <1gb>)
     but: a value greater than <1kb> was null
Close stacktrace
at __randomizedtesting.SeedInfo.seed([B682ECA58AF6DA1F:2E984A2E94660B24]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at org.elasticsearch.client.MachineLearningIT.testEstimateMemoryUsage(MachineLearningIT.java:1749)
```

**Comment by droberts195** [comment] 2019-08-28 11:38
This is probably the same underlying problem that was identified in https://github.com/elastic/elasticsearch/issues/45787#issuecomment-525705020

/cc @przemekwitek

**Comment by przemekwitek** [comment] 2019-08-28 11:44
Yes, this is most likely a duplicate, marking it as such.
BTW, I've identified the root cause of the issue you referenced and I'm thinking about the fix.

Duplicate of https://github.com/elastic/elasticsearch/issues/45787

**Closed by przemekwitek** 2019-08-28 11:44 UTC
Labels: :ml, :ml/Data Frame, >test-failure, v7.4.0, v8.0.0
