### ISSUE TITLE
Cannot run Elasticsearch image with discovery-ec2 on ARM machines

### ISSUE THREAD

**Issue by bugb** [elastic/elasticsearch#97215] opened 2023-06-29 06:08 UTC
### Elasticsearch Version

7.13.0

### Installed Plugins

discovery-ec2

### Java Version

_bundled_

### OS Version

Amazon Linux 2/Graviton (EC2 ARM)

### Problem Description

I build an Elasticsearch Docker image with discovery-ec2 plugin but get the following error when running the Docker image:
```
BindTransportException[Failed to resolve publish address]; nested: IOException[IOException caught when fetching InetAddress from [http://169.254.169.254/latest/meta-data/local-ipv4]]; nested: IOException[Server returned HTTP response code: 401 for URL: http://169.254.169.254/latest/meta-data/local-ipv4];
Likely root cause: java.io.IOException: Server returned HTTP response code: 401 for URL: http://169.254.169.254/latest/meta-data/local-ipv4
```

### Steps to Reproduce

1. SSH to my machine (currently I am using an EC2 with m7g instance type, arch: arm64)
2. Build my custom Elasticsearch image:
```
# My Dockerfile
FROM arm64v8/elasticsearch:7.13.0

USER root

ARG CACHEBUST=1

# EC2 Discovery
RUN eval ${ES_JAVA_OPTS:-} elasticsearch-plugin install --batch discovery-ec2
```
3. Run the Docker image:
```
 docker run  -p 9200:9200 -d my_custom_es_image
```
4. Get the error:
```
{"type": "server", "timestamp": "2023-06-29T06:06:05,714Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "_ec2_", "message": "loaded plugin [discovery-ec2]" }
{"type": "server", "timestamp": "2023-06-29T06:06:05,753Z", "level": "INFO", "component": "o.e.e.NodeEnvironment", "cluster.name": "elasticsearch", "node.name": "_ec2_", "message": "using [1] data paths, mounts [[/ (overlay)]], net usable_space [34.2gb], net total_space [39.9gb], types [overlay]" }
{"type": "server", "timestamp": "2023-06-29T06:06:05,753Z", "level": "INFO", "component": "o.e.e.NodeEnvironment", "cluster.name": "elasticsearch", "node.name": "_ec2_", "message": "heap size [3.7gb], compressed ordinary object pointers [true]" }
{"type": "server", "timestamp": "2023-06-29T06:06:05,776Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "elasticsearch", "node.name": "_ec2_", "message": "node name [_ec2_], node ID [8m1l_vWqTceol3H6L7_8dA], cluster name [elasticsearch], roles [transform, data_frozen, master, remote_cluster_client, data, ml, data_content, data_hot, data_warm, data_cold, ingest]" }
{"type": "deprecation.elasticsearch", "timestamp": "2023-06-29T06:06:05,793Z", "level": "DEPRECATION", "component": "o.e.d.c.s.Settings", "cluster.name": "elasticsearch", "node.name": "_ec2_", "message": "[thread_pool.search.max_queue_size] setting was deprecated in Elasticsearch and will be removed in a future release! See the breaking changes documentation for the next major version." }
{"type": "deprecation.elasticsearch", "timestamp": "2023-06-29T06:06:05,793Z", "level": "DEPRECATION", "component": "o.e.d.c.s.Settings", "cluster.name": "elasticsearch", "node.name": "_ec2_", "message": "[thread_pool.search.min_queue_size] setting was deprecated in Elasticsearch and will be removed in a future release! See the breaking changes documentation for the next major version." }
{"type": "deprecation.elasticsearch", "timestamp": "2023-06-29T06:06:07,641Z", "level": "DEPRECATION", "component": "o.e.d.c.s.Settings", "cluster.name": "elasticsearch", "node.name": "_ec2_", "message": "[discovery.zen.minimum_master_nodes] setting was deprecated in Elasticsearch and will be removed in a future release! See the breaking changes documentation for the next major version." }
{"type": "deprecation.elasticsearch", "timestamp": "2023-06-29T06:06:07,643Z", "level": "DEPRECATION", "component": "o.e.d.c.s.Settings", "cluster.name": "elasticsearch", "node.name": "_ec2_", "message": "[discovery.zen.hosts_provider] setting was deprecated in Elasticsearch and will be removed in a future release! See the breaking changes documentation for the next major version." }
{"type": "server", "timestamp": "2023-06-29T06:06:09,259Z", "level": "INFO", "component": "o.e.x.m.p.l.CppLogMessageHandler", "cluster.name": "elasticsearch", "node.name": "_ec2_", "message": "[controller/210] [Main.cc@117] controller (64 bit): Version 7.13.0 (Build a62594307178cf) Copyright (c) 2021 Elasticsearch BV" }
{"type": "server", "timestamp": "2023-06-29T06:06:09,516Z", "level": "INFO", "component": "o.e.i.g.LocalDatabases", "cluster.name": "elasticsearch", "node.name": "_ec2_", "message": "initialized default databases [[GeoLite2-Country.mmdb, GeoLite2-City.mmdb, GeoLite2-ASN.mmdb]], config databases [[]] and watching [/usr/share/elasticsearch/config/ingest-geoip] for changes" }
{"type": "server", "timestamp": "2023-06-29T06:06:09,518Z", "level": "INFO", "component": "o.e.i.g.DatabaseRegistry", "cluster.name": "elasticsearch", "node.name": "_ec2_", "message": "initialized database registry, using geoip-databases directory [/tmp/elasticsearch-11661059296051893862/geoip-databases/8m1l_vWqTceol3H6L7_8dA]" }
{"type": "server", "timestamp": "2023-06-29T06:06:09,960Z", "level": "INFO", "component": "o.e.t.NettyAllocator", "cluster.name": "elasticsearch", "node.name": "_ec2_", "message": "creating NettyAllocator with the following configs: [name=elasticsearch_configured, chunk_size=1mb, suggested_max_allocation_size=1mb, factors={es.unsafe.use_netty_default_chunk_and_page_size=false, g1gc_enabled=true, g1gc_region_size=4mb}]" }
{"type": "server", "timestamp": "2023-06-29T06:06:10,016Z", "level": "INFO", "component": "o.e.d.DiscoveryModule", "cluster.name": "elasticsearch", "node.name": "_ec2_", "message": "using discovery type [zen] and seed hosts providers [settings, ec2]" }
{"type": "server", "timestamp": "2023-06-29T06:06:10,423Z", "level": "INFO", "component": "o.e.g.DanglingIndicesState", "cluster.name": "elasticsearch", "node.name": "_ec2_", "message": "gateway.auto_import_dangling_indices is disabled, dangling indices will not be automatically detected or imported and must be managed manually" }
{"type": "server", "timestamp": "2023-06-29T06:06:10,752Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "elasticsearch", "node.name": "_ec2_", "message": "initialized" }
{"type": "server", "timestamp": "2023-06-29T06:06:10,752Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "elasticsearch", "node.name": "_ec2_", "message": "starting ..." }
{"type": "server", "timestamp": "2023-06-29T06:06:10,764Z", "level": "INFO", "component": "o.e.x.s.c.f.PersistentCache", "cluster.name": "elasticsearch", "node.name": "_ec2_", "message": "persistent cache index loaded" }
{"type": "server", "timestamp": "2023-06-29T06:06:10,858Z", "level": "ERROR", "component": "o.e.b.ElasticsearchUncaughtExceptionHandler", "cluster.name": "elasticsearch", "node.name": "_ec2_", "message": "uncaught exception in thread [main]", 
"stacktrace": ["org.elasticsearch.bootstrap.StartupException: BindTransportException[Failed to resolve publish address]; nested: IOException[IOException caught when fetching InetAddress from [http://169.254.169.254/latest/meta-data/local-ipv4]]; nested: IOException[Server returned HTTP response code: 401 for URL: http://169.254.169.254/latest/meta-data/local-ipv4];",
"at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-7.13.0.jar:7.13.0]",
"at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-7.13.0.jar:7.13.0]",
"at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75) ~[elasticsearch-7.13.0.jar:7.13.0]",
"at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116) ~[elasticsearch-cli-7.13.0.jar:7.13.0]",
"at org.elasticsearch.cli.Command.main(Command.java:79) ~[elasticsearch-cli-7.13.0.jar:7.13.0]",
"at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) ~[elasticsearch-7.13.0.jar:7.13.0]",
"at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:81) ~[elasticsearch-7.13.0.jar:7.13.0]",
"Caused by: org.elasticsearch.transport.BindTransportException: Failed to resolve publish address",
"at org.elasticsearch.transport.TcpTransport.createBoundTransportAddress(TcpTransport.java:441) ~[elasticsearch-7.13.0.jar:7.13.0]",
"at org.elasticsearch.transport.TcpTransport.bindServer(TcpTransport.java:373) ~[elasticsearch-7.13.0.jar:7.13.0]",
"at org.elasticsearch.transport.netty4.Netty4Transport.doStart(Netty4Transport.java:120) ~[?:?]",
"at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:48) ~[elasticsearch-7.13.0.jar:7.13.0]",
"at org.elasticsearch.transport.TransportService.doStart(TransportService.java:263) ~[elasticsearch-7.13.0.jar:7.13.0]",
"at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:48) ~[elasticsearch-7.13.0.jar:7.13.0]",
"at org.elasticsearch.node.Node.start(Node.java:865) ~[elasticsearch-7.13.0.jar:7.13.0]",
"at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:311) ~[elasticsearch-7.13.0.jar:7.13.0]",
"at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:406) ~[elasticsearch-7.13.0.jar:7.13.0]",
"at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.13.0.jar:7.13.0]",
"... 6 more",
"Caused by: java.io.IOException: IOException caught when fetching InetAddress from [http://169.254.169.254/latest/meta-data/local-ipv4]",
"at org.elasticsearch.discovery.ec2.Ec2NameResolver.resolve(Ec2NameResolver.java:99) ~[?:?]",
"at org.elasticsearch.discovery.ec2.Ec2NameResolver.resolveIfPossible(Ec2NameResolver.java:115) ~[?:?]",
"at org.elasticsearch.common.network.NetworkService.resolveInternal(NetworkService.java:199) ~[elasticsearch-7.13.0.jar:7.13.0]",
"at org.elasticsearch.common.network.NetworkService.resolveInetAddresses(NetworkService.java:187) ~[elasticsearch-7.13.0.jar:7.13.0]",
"at org.elasticsearch.common.network.NetworkService.resolvePublishHostAddresses(NetworkService.java:143) ~[elasticsearch-7.13.0.jar:7.13.0]",
"at org.elasticsearch.transport.TcpTransport.createBoundTransportAddress(TcpTransport.java:439) ~[elasticsearch-7.13.0.jar:7.13.0]",
"at org.elasticsearch.transport.TcpTransport.bindServer(TcpTransport.java:373) ~[elasticsearch-7.13.0.jar:7.13.0]",
"at org.elasticsearch.transport.netty4.Netty4Transport.doStart(Netty4Transport.java:120) ~[?:?]",
"at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:48) ~[elasticsearch-7.13.0.jar:7.13.0]",
"at org.elasticsearch.transport.TransportService.doStart(TransportService.java:263) ~[elasticsearch-7.13.0.jar:7.13.0]",
"at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:48) ~[elasticsearch-7.13.0.jar:7.13.0]",
"at org.elasticsearch.node.Node.start(Node.java:865) ~[elasticsearch-7.13.0.jar:7.13.0]",
"at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:311) ~[elasticsearch-7.13.0.jar:7.13.0]",
"at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:406) ~[elasticsearch-7.13.0.jar:7.13.0]",
"at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.13.0.jar:7.13.0]",
"... 6 more",
"Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: http://169.254.169.254/latest/meta-data/local-ipv4",
"at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1985) ~[?:?]",
"at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577) ~[?:?]",
"at java.security.AccessController.doPrivileged(AccessController.java:554) ~[?:?]",
"at org.elasticsearch.discovery.ec2.SocketAccess.doPrivilegedIOException(SocketAccess.java:37) ~[?:?]",
"at org.elasticsearch.discovery.ec2.Ec2NameResolver.resolve(Ec2NameResolver.java:89) ~[?:?]",
"at org.elasticsearch.discovery.ec2.Ec2NameResolver.resolveIfPossible(Ec2NameResolver.java:115) ~[?:?]",
"at org.elasticsearch.common.network.NetworkService.resolveInternal(NetworkService.java:199) ~[elasticsearch-7.13.0.jar:7.13.0]",
"at org.elasticsearch.common.network.NetworkService.resolveInetAddresses(NetworkService.java:187) ~[elasticsearch-7.13.0.jar:7.13.0]",
"at org.elasticsearch.common.network.NetworkService.resolvePublishHostAddresses(NetworkService.java:143) ~[elasticsearch-7.13.0.jar:7.13.0]",
"at org.elasticsearch.transport.TcpTransport.createBoundTransportAddress(TcpTransport.java:439) ~[elasticsearch-7.13.0.jar:7.13.0]",
"at org.elasticsearch.transport.TcpTransport.bindServer(TcpTransport.java:373) ~[elasticsearch-7.13.0.jar:7.13.0]",
"at org.elasticsearch.transport.netty4.Netty4Transport.doStart(Netty4Transport.java:120) ~[?:?]",
"at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:48) ~[elasticsearch-7.13.0.jar:7.13.0]",
"at org.elasticsearch.transport.TransportService.doStart(TransportService.java:263) ~[elasticsearch-7.13.0.jar:7.13.0]",
"at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:48) ~[elasticsearch-7.13.0.jar:7.13.0]",
"at org.elasticsearch.node.Node.start(Node.java:865) ~[elasticsearch-7.13.0.jar:7.13.0]",
"at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:311) ~[elasticsearch-7.13.0.jar:7.13.0]",
"at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:406) ~[elasticsearch-7.13.0.jar:7.13.0]",
"at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.13.0.jar:7.13.0]",
"... 6 more"] }
uncaught exception in thread [main]
BindTransportException[Failed to resolve publish address]; nested: IOException[IOException caught when fetching InetAddress from [http://169.254.169.254/latest/meta-data/local-ipv4]]; nested: IOException[Server returned HTTP response code: 401 for URL: http://169.254.169.254/latest/meta-data/local-ipv4];
Likely root cause: java.io.IOException: Server returned HTTP response code: 401 for URL: http://169.254.169.254/latest/meta-data/local-ipv4
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1985)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
        at org.elasticsearch.discovery.ec2.SocketAccess.doPrivilegedIOException(SocketAccess.java:37)
        at org.elasticsearch.discovery.ec2.Ec2NameResolver.resolve(Ec2NameResolver.java:89)
        at org.elasticsearch.discovery.ec2.Ec2NameResolver.resolveIfPossible(Ec2NameResolver.java:115)
        at org.elasticsearch.common.network.NetworkService.resolveInternal(NetworkService.java:199)
        at org.elasticsearch.common.network.NetworkService.resolveInetAddresses(NetworkService.java:187)
        at org.elasticsearch.common.network.NetworkService.resolvePublishHostAddresses(NetworkService.java:143)
        at org.elasticsearch.transport.TcpTransport.createBoundTransportAddress(TcpTransport.java:439)
        at org.elasticsearch.transport.TcpTransport.bindServer(TcpTransport.java:373)
        at org.elasticsearch.transport.netty4.Netty4Transport.doStart(Netty4Transport.java:120)
        at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:48)
        at org.elasticsearch.transport.TransportService.doStart(TransportService.java:263)
        at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:48)
        at org.elasticsearch.node.Node.start(Node.java:865)
        at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:311)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:406)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116)
        at org.elasticsearch.cli.Command.main(Command.java:79)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:81)
For complete error details, refer to the log at /usr/share/elasticsearch/logs/elasticsearch.log
{"type": "server", "timestamp": "2023-06-29T06:06:11,778Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "elasticsearch", "node.name": "_ec2_", "message": "stopping ..." }
{"type": "server", "timestamp": "2023-06-29T06:06:11,784Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "elasticsearch", "node.name": "_ec2_", "message": "stopped" }
{"type": "server", "timestamp": "2023-06-29T06:06:11,784Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "elasticsearch", "node.name": "_ec2_", "message": "closing ..." }
{"type": "server", "timestamp": "2023-06-29T06:06:11,792Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "elasticsearch", "node.name": "_ec2_", "message": "closed" }
{"type": "server", "timestamp": "2023-06-29T06:06:11,793Z", "level": "INFO", "component": "o.e.x.m.p.NativeController", "cluster.name": "elasticsearch", "node.name": "_ec2_", "message": "Native controller process has stopped - no new native processes can be started" }
```

Note: when I do not install discovery-ec2 plugin, it works fine!

**Comment by DaveCTurner** [comment] 2023-06-29 08:08
Thanks very much for your interest in Elasticsearch.

Quoting the bug report form:

> Please also check your OS is [supported](https://www.elastic.co/support/matrix#show_os), and that the version of Elasticsearch has not passed [end-of-life](https://www.elastic.co/support/eol). If you are using an unsupported OS or an unsupported version then the issue is likely to be closed.

Your issue relates to Elasticsearch version 7.13.0 which has passed end-of-life, so I am closing this. Moreover I believe this  issue is a duplicate of https://github.com/elastic/elasticsearch/issues/91585.

**Closed by DaveCTurner** 2023-06-29 08:08 UTC
Labels: >bug, needs:triage
