### ISSUE TITLE
[CI] Failures on 6.x for 60_ml_config_migration/Test old cluster jobs and datafeeds and delete them

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#36810] opened 2018-12-19 02:14 UTC
This has failed at least twice since #36698 was merged to 6.x

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/693/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java11,nodes=virtual&&linux/127/console

```
./gradlew :x-pack:qa:rolling-upgrade:with-system-key:v5.6.15#upgradedClusterTestRunner -Dtests.seed=7721FEBE7CCB10B7 -Dtests.class=org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT -Dtests.method="test {p0=upgraded_cluster/60_ml_config_migration/Test old cluster jobs and datafeeds and delete them}" -Dtests.security.manager=true -Dtests.locale=ar-AE -Dtests.timezone=Etc/GMT-10 -Dcompiler.java=11 -Druntime.java=8 -Dtests.rest.suite=upgraded_cluster -Dtests.rest.blacklist="/30_ml_jobs_crud/Test model memory limit is updated"
```

```
00:50:45    > Throwable #1: java.lang.AssertionError: Failure at [upgraded_cluster/60_ml_config_migration:43]: datafeeds.0.state didn't match expected value:
00:50:45    >              datafeeds.0.state: expected [started] but was [stopped]
00:50:45    > 	at __randomizedtesting.SeedInfo.seed([7721FEBE7CCB10B7:FF75C164D2377D4F]:0)
00:50:45    > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:406)
00:50:45    > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:383)
00:50:45    > 	at java.lang.Thread.run(Thread.java:748)
00:50:45    > Caused by: java.lang.AssertionError: datafeeds.0.state didn't match expected value:
00:50:45    >              datafeeds.0.state: expected [started] but was [stopped]
00:50:45    > 	at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:87)
00:50:45    > 	at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:76)
00:50:45    > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:399)
00:50:45    > 	... 38 more
```

I get failures locally as well but they have a different assertion failure.

I'm going to mute this on 6.x

**Comment by tvernum** [comment] 2018-12-19 02:15
@davidkyle I assigned this to you since it seems to have come from #36698.
Please reassign if I got that wrong.

**Comment by droberts195** [comment] 2019-01-07 14:32
I think this is a case of an old bug, but made far more likely to happen due to the timing changes of having to do a search for job configuration rather than getting it from the cluster state.

This goes back to the age-old inconsistency that when jobs open for the first time they're in the `opening` state until they are ready to accept data.  But when relocating to a new node jobs stay in the `opened` state, yet cannot accept data until the corresponding C++ process is running on the new node.

We have a check that datafeed persistent tasks cannot be assigned to a node until the associated job is assigned to a node.  We also have a check that an assigned datafeed cannot be run until the associated job is in the `opened` state.  If a datafeed's associated job is in the `opening` state then it waits for a subsequent cluster state update where the job state is `opened`, but this check assumes that relocating jobs would have a state of `opening`, which they do not.

Two possible solutions are:

1. Set the job state to `opening` when it is `opened` but the assignment is stale
2. Change the test in `DatafeedManager` to check whether a C++ process is running for the associated job, and not rely on an `opened` state implying this

**Comment by droberts195** [comment] 2019-01-07 14:42
The piece of code I referred to in `DatafeedManager` is https://github.com/elastic/elasticsearch/blob/0000e7c8b524556d7a1bbec94e6c0114fc225bab/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/datafeed/DatafeedManager.java#L488-L491

**Comment by droberts195** [comment] 2019-01-07 17:06
Although option 1 (setting the job state to `opening` when it is `opened` but the assignment is stale) seems logically nicer, there is no way to achieve this without making a change to the persistent tasks framework.  There is no way to change a task's status on reassignment.  Task status can only be set by a separate action, and using that mechanism would leave a period when the same problem that exists now would still exist (just much harder to debug since it would exist for a shorter and less predictable amount of time).

**Comment by droberts195** [comment] 2019-01-08 15:06
> Although option 1 (setting the job state to opening when it is opened but the assignment is stale) seems logically nicer, there is no way to achieve this without making a change to the persistent tasks framework.

This problem has been dealt with elsewhere via the concept of "stale" task status.  The task status of a job task stores an allocation ID as well as the task itself, and if these differ then we know the task has relocated.  Then we can interpret the reported status value differently.  This tactic has already been used elsewhere.  I extended use of it to the datafeed manager in #37227.

#37227 should stop the problem occurring in the fully upgraded cluster.  In the mixed cluster it may still happen if a job gets relocated to a node on the old version that doesn't have the fix.  I'll think more carefully about this before unmuting the test.

**Comment by droberts195** [comment] 2019-01-09 10:34
> I'll think more carefully about this before unmuting the test.

The test that is muted _only_ runs in the fully upgraded cluster, so can definitely be unmuted when #37227 is merged.

The same underlying problem does sometimes happen in the mixed cluster, for example it happened in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.6+bwc-tests/49/console.  However, the test that fails in this case is not currently muted.  I'll monitor similar failures once #37227 is merged to see if the mixed cluster failures completely go away.  If not then I'll adjust what tests are run in the mixed cluster.

**Comment by droberts195** [comment] 2019-01-10 09:41
The same test is now failing in CI in a slightly different way:

* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+release-tests/325/console
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.6+multijob-unix-compatibility/os=amazon/43/console
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.6+bwc-tests/64/console

**Comment by droberts195** [comment] 2019-01-10 17:41
I found out what is happening.  Whether a persistent task goes stale when a node leaves and rejoins the cluster depends on whether there is a cluster state update while the cluster has a master node and the node is out of the cluster.  If a node leaves and rejoins the cluster while the cluster has no master node then a persistent task running on it will _not_ go stale.  Maybe this was intentional, but it's annoying for ML in the case of a node running ML jobs being restarted.

In the rolling upgrade tests all 3 nodes are master eligible and minimum master nodes is 3, so while any node is restarted the cluster has no master.  When the upgraded node rejoins the cluster it has a master again.  At this point a flurry of cluster state updates occur.  Sometimes the ML persistent tasks that were running on the restarted node are reallocated to a different node and sometimes they stay on the restarted node.  If they stay on the restarted node they're not considered stale.

This wouldn't happen in a cluster with minimum master nodes less than the number of nodes in the cluster.  Then if a single ML node was restarted the remaining nodes would still be able to form a cluster with a master and the ML persistent tasks would either get allocated to other nodes or become unallocated while the node being restarted was out of the cluster.  This would guarantee that they were stale.

The problem can be fixed by checking explicitly whether an autodetect process is running for a datafeed's job before the datafeed does any work.  The extent to which this is a test fix or a production fix depends on whether anyone runs in production with minimum master nodes set to the number of nodes in the cluster.  It seems a bit crazy because then a single node failure cripples the cluster.

**Comment by gwbrown** [comment] 2019-01-11 23:36
This failed again in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.6+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=zulu8,nodes=virtual&&linux/47/console, which includes https://github.com/elastic/elasticsearch/commit/f141f3a81f43453d338f24b84e42d95736cad6db, which I believe was intended to fix it.  It appears to be happening much less now, so I'm not going to re-mute the test, but I'm not sure the problem is fully fixed.

**Comment by droberts195** [comment] 2019-01-14 09:15
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.6+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=zulu8,nodes=virtual&&linux/47/console says:

```
runbld>>> Using last successful commit 1180687 from the job elastic+elasticsearch+6.6+intake with the build id 20190111103841-CB1867D2 that was started at 2019-01-11T10:38:42.324Z and finished 5h 47m 47s ago
```

1180687 is the commit before f141f3a, so the failing build did not contain the fix.  (At the time the build ran f141f3a was committed but had not got past an intake build so was not being used in the non-intake builds.)

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+bwc-tests/281/consoleText is another build that failed over the weekend due to this problem but again it used a "last successful commit" from before the fix.

The only other build over the weekend where this test failed was https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/972/consoleText, but a whole load of other tests also failed in that build and the root cause looks like a problem setting up security that meant the test harness couldn't connect to the test clsuter.  Therefore I'll close this issue again.

**Closed by droberts195** 2019-01-14 09:15 UTC
Labels: :ml, >test-failure
