### ISSUE TITLE
batsPackagingTest occasionally fails in 'test runtime directory'

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#31634] opened 2018-06-27 21:39 UTC
In the packaging tests for Centos 7, it seems 'test runtime directory' can fail when attempting to start up elasticsearch. This line in particular looked interesting: `Failed to start elasticsearch.service: Unit not found.`

---

Link to build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+packaging-tests/979/console

Command to reproduce:
```
./gradlew :qa:vagrant:vagrantCentos7#batsPackagingTest \
  -Dtests.seed=3EE613214D49E09D 
```

Excerpt from the logs:
```
not ok 211 [SYSTEMD] test runtime directory
not ok 211 [SYSTEMD] test runtime directory
# (in test file /project/build/packaging/bats/tests/60_systemd.bats, line 244)
# (in test file /project/build/packaging/bats/tests/60_systemd.bats, line 244)
#   `systemctl start elasticsearch.service' failed with status 5
#   `systemctl start elasticsearch.service' failed with status 5
# Creating elasticsearch group... OK
# Creating elasticsearch user... OK
# Creating elasticsearch group... OK
# Creating elasticsearch user... OK
# ### NOT starting on installation, please execute the following statements to configure elasticsearch service to start automatically using systemd
#  sudo systemctl daemon-reload
#  sudo systemctl enable elasticsearch.service
# ### You can start elasticsearch service by executing
#  sudo systemctl start elasticsearch.service
# Created elasticsearch keystore in /etc/elasticsearch
# Failed to start elasticsearch.service: Unit not found.
# ### NOT starting on installation, please execute the following statements to configure elasticsearch service to start automatically using systemd
#  sudo systemctl daemon-reload
#  sudo systemctl enable elasticsearch.service
# ### You can start elasticsearch service by executing
#  sudo systemctl start elasticsearch.service
# Created elasticsearch keystore in /etc/elasticsearch
# Failed to start elasticsearch.service: Unit not found.
```

Full log: [bats_packaging_log.txt](https://github.com/elastic/elasticsearch/files/2143018/bats_packaging_log.txt)

**Comment by jdconrad** [comment] 2018-07-26 23:02
I believe this one is similar (https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.3+packaging-tests/279/console)
with
```
22:46:38 not ok 70 [TAR PLUGINS] start elasticsearch with all plugins removed
22:46:38 not ok 70 [TAR PLUGINS] start elasticsearch with all plugins removed
22:46:38 # (from function `wait_for_elasticsearch_status' in file /project/build/packaging/bats/utils/utils.bash, line 432,
22:46:38 # (from function `wait_for_elasticsearch_status' in file /project/build/packaging/bats/utils/utils.bash, line 432,
22:46:38 #  from function `start_elasticsearch_service' in file /project/build/packaging/bats/utils/utils.bash, line 316,
22:46:38 #  from function `start_elasticsearch_service' in file /project/build/packaging/bats/utils/utils.bash, line 316,
22:46:38 #  in test file /project/build/packaging/bats/tests/25_tar_plugins.bats, line 392)
22:46:38 #  in test file /project/build/packaging/bats/tests/25_tar_plugins.bats, line 392)
22:46:38 #   `start_elasticsearch_service' failed
22:46:38 #   `start_elasticsearch_service' failed
```

**Comment by andyb-elastic** [comment] 2019-02-05 21:53
I think the failures in [this comment](https://github.com/elastic/elasticsearch/issues/31634#issuecomment-408261145) and [this comment](https://github.com/elastic/elasticsearch/issues/31634#issuecomment-456296144) are something different - the former is in tests for the tar distribution, and the latter is on centos 6 which doesn't use systemd

My best guess is the package installation failed [here](https://github.com/elastic/elasticsearch/blob/75a8e0b2ba01cefd32cf714cadd9707a691ce085/qa/vagrant/src/test/resources/packaging/tests/60_systemd.bats#L242), which would mean that the rpm installation returned a 0 exit code in spite of something being wrong (whether an error in rpm, or an issue with the package)

**Comment by henningandersen** [comment] 2019-04-16 12:26
Had a failure on https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+packaging-tests-sample/13071/console that looks somewhat similar though without the mentioned "failed to start" lines in it. Unable to reproduce using the reproduce with line:

./gradlew ":x-pack:qa:vagrant:vagrantCentos7#batsPackagingTest" -Dtests.seed=6F730C40F2BC9F67 

[bats_packaging_log_pr_13071.txt](https://github.com/elastic/elasticsearch/files/3084851/bats_packaging_log_pr_13071.txt)

**Comment by rjernst** [comment] 2019-05-07 18:44
In general issues like this need more investigation to find the actual elasticsearch log in order to understand why ES failed to start. As is, this issue isn't actionable, thus I'm closing. Hopefully as we continue to migrate to java based packaging tests these will become easier to investigate, as we can dump the elasticsearch log from the java tests on failure.

**Closed by rjernst** 2019-05-07 18:44 UTC
Labels: :Core/Infra/Packaging, >test-failure
