### ISSUE TITLE
Range bucket in pipeline aggregations

### ISSUE THREAD

**Issue by davmrtl** [elastic/elasticsearch#14486] opened 2015-11-03 17:01 UTC
Hi,

Should be great to be able to perform a grouping of computed values using the pipeline aggregation range bucket.

Thanks,

David

**Comment by polyfractal** [comment] 2015-11-05 15:42
What would you like to do with the values in the range buckets?  Do you mainly want to do group metrics like `min`/`max`/`avg`, etc?  Or also "sequential" operations like `moving_avg`?

I ask because the first set would be relatively simple, whereas the second is much more complicated.  Operations like a moving average rely on the previous data to be evenly spaced and contiguous.  We currently have a "gap policy" that helps fill in gaps in a series of data...but I'm not sure how that would work with ranges that can be unequally sized and spaced.

/cc @colings86

**Comment by nishasingla1224** [comment] 2016-01-30 07:40
Hi 
I want to group the computed data using pipeline aggregations.Would be great to have a support of this feature.

**Comment by clintongormley** [comment] 2016-02-14 15:21
@davmrtl @nishasingla1224 I still don't understand what you mean by "grouping" here.  Could you provide a concrete example?

**Comment by clintongormley** [comment] 2016-05-24 10:31
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Closed by clintongormley** 2016-05-24 10:31 UTC
Labels: :Aggregations, feedback_needed

**Comment by phoenixgao** [comment] 2016-08-17 08:38
Imaging I have indexed events into elasticsearch, each event is like:
{"timestamp" : @timestamp, "event_name": "hit a button", "user_id": 123}

So I'd like to have a first buckets aggregation to count the times a user hit the button group by user_id, then I want to know the range of these counts

Is it possible to do this without a pipeline range aggregation? @clintongormley @polyfractal

**Comment by polyfractal** [comment] 2016-08-17 13:26
@phoenixgao: you can do something like this:

```json
{
   "query": {
      "constant_score": {
         "filter": {
            "term": {
               "event_name": "hit a button"
            }
         }
      }
   },
   "aggs": {
      "users": {
         "terms": {
            "field": "user_id"
         }
      },
      "click_stats": {
         "stats_bucket": {
            "buckets_path": "users._count"
         }
      }
   }
}
```

The query limits the docs to those that were "button click" events, the `terms` agg groups by user_id, and the `stats_bucket` will show you the min/max/avg, etc of the user click counts.

@phoenixgao If you have any more questions, please [make a thread at the discussion forums](https://discuss.elastic.co/).  Github tickets are more for bug reports and feature requests, general questions are better suited for the forums :)

**Comment by phoenixgao** [comment] 2016-08-17 14:13
@polyfractal Thanks!!
what I was asking might be a duplicate of https://github.com/elastic/elasticsearch/issues/17590 though
