### ISSUE TITLE
[CI] Must specify license and notice file for project :benchmarks for Zulu builds

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#36537] opened 2018-12-12 11:44 UTC
First time reported [here](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=zulu11,nodes=virtual&&linux/112/console).

```
18:01:21 
18:01:21 > Configure project :
18:01:21 Evaluating root project 'virtual&&linux' using build file '/var/lib/jenkins/workspace/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA/java11/ES_RUNTIME_JAVA/zulu11/nodes/virtual&&linux/build.gradle'.
18:01:21 Compiling build file '/var/lib/jenkins/workspace/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA/java11/ES_RUNTIME_JAVA/zulu11/nodes/virtual&&linux/build.gradle' using SubsetScriptTransformer.
18:01:21 Compiling build file '/var/lib/jenkins/workspace/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA/java11/ES_RUNTIME_JAVA/zulu11/nodes/virtual&&linux/build.gradle' using BuildScriptTransformer.
18:01:23 
18:01:23 Project evaluation failed including an error in afterEvaluate {}.
18:01:23 > Configure project :benchmarks
18:01:23 Evaluating project ':benchmarks' using build file '/var/lib/jenkins/workspace/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA/java11/ES_RUNTIME_JAVA/zulu11/nodes/virtual&&linux/benchmarks/build.gradle'.
18:01:23 Compiling build file '/var/lib/jenkins/workspace/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA/java11/ES_RUNTIME_JAVA/zulu11/nodes/virtual&&linux/benchmarks/build.gradle' using SubsetScriptTransformer.
18:01:23 Compiling build file '/var/lib/jenkins/workspace/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA/java11/ES_RUNTIME_JAVA/zulu11/nodes/virtual&&linux/benchmarks/build.gradle' using BuildScriptTransformer.
18:01:23 Starting process 'command '/var/lib/jenkins/.java/zulu11/bin/jrunscript''. Working directory: /var/lib/jenkins/workspace/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA/java11/ES_RUNTIME_JAVA/zulu11/nodes/virtual&&linux/benchmarks Command: /var/lib/jenkins/.java/zulu11/bin/jrunscript -e print(java.lang.System.getProperty("java.vendor") + " " + java.lang.System.getProperty("java.version") + " [" + java.lang.System.getProperty("java.vm.name") + " " + java.lang.System.getProperty("java.vm.version") + "]");
18:01:23 org.gradle.api.GradleException: Must specify license and notice file for project :benchmarks
18:01:23 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
18:01:23 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
18:01:23 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
18:01:23 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
18:01:23 	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
18:01:23 	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
18:01:23 	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
18:01:23 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
18:01:23 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:237)
18:01:23 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:249)
18:01:23 	at org.elasticsearch.gradle.BuildPlugin$_configureJars_closure21$_closure53.doCall(BuildPlugin.groovy:820)
18:01:23 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:01:23 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18:01:23 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:01:23 
18:01:23 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
18:01:23 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
```

**Comment by atorok** [comment] 2018-12-12 12:18
This seems to be caused by
```
18:01:23 Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [id 'elasticsearch.build']
18:01:23 	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:160)
18:01:23 	at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:130)
18:01:23 	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:120)
18:01:23 	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:38)
18:01:23 	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:86)
18:01:23 	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:143)
18:01:23 	at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:46)
18:01:23 	at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.java:34)
18:01:23 	at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
18:01:23 	at build_aunv29xcmjueb6zr57l9dszze.run(/var/lib/jenkins/workspace/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA/java11/ES_RUNTIME_JAVA/zulu11/nodes/virtual&&linux/benchmarks/build.gradle:20)
18:01:23 	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
18:01:23 	... 115 more
18:01:23 Caused by: org.gradle.process.internal.ExecException: A problem occurred starting process 'command '/var/lib/jenkins/.java/zulu11/bin/jrunscript''
18:01:23 	at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:232)
18:01:23 	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:209)
18:01:23 	at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:356)
18:01:23 	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:86)
18:01:23 	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
18:01:23 	... 3 more
18:01:23 Caused by: net.rubygrapefruit.platform.NativeException: Could not start '/var/lib/jenkins/.java/zulu11/bin/jrunscript'
18:01:23 	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
18:01:23 	at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
18:01:23 	at org.gradle.process.internal.ExecHandleRunner.startProcess(ExecHandleRunner.java:97)
18:01:23 	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:70)
18:01:23 	... 4 more
18:01:23 Caused by: java.io.IOException: Cannot run program "/var/lib/jenkins/.java/zulu11/bin/jrunscript" (in directory "/var/lib/jenkins/workspace/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA/java11/ES_RUNTIME_JAVA/zulu11/nodes/virtual&&linux/benchmarks"): error=2, No such file or directory
18:01:23 	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
18:01:23 	... 7 more
18:01:23 Caused by: java.io.IOException: error=2, No such file or directory
18:01:23 	... 8 more
```
The zulu distribution on the CI worker is either missing `jrunscript` or the zulu distribution is missing entirely.

**Comment by atorok** [comment] 2018-12-12 13:14
Confirmed that the zulu sdk is missing in CI. Closing as this is a CI issue.

**Closed by atorok** 2018-12-12 13:14 UTC
Labels: :Core/Infra/Build
