### ISSUE TITLE
[CI] DocsClientYamlTestSuiteIT reference/text-structure/apis/find-structure:285 failed

### ISSUE THREAD

**Issue by probakowski** [elastic/elasticsearch#80409] opened 2021-11-05 12:49 UTC
**Build scan**:
https://gradle-enterprise.elastic.co/s/jyvigqhvk2dg6
**Repro line**:

**Reproduces locally?**:
Didn't try

**Applicable branches**:
master, 8.0
**Failure history**:
Looks like it started to fail today around 9AM CET (2 failures so far)
**Failure excerpt**:

```
Caused by: java.lang.AssertionError: Expected a map containing |  
  | acknowledged: expected <true> but was <missing> |  
  | num_lines_analyzed: <unexpected> but was <24> |  
  | num_messages_analyzed: <unexpected> but was <24> |  
  | sample_start: <unexpected> but was "{\"release_date\":\"2011-06-02\",\"author\":\"James S.A. Corey\",\"name\":\"Leviathan Wakes\",\"page_count\":561}\n{\"release_date\":\"1989-05-26\",\"author\":\"Dan Simmons\",\"name\":\"Hyperion\",\"page_count\":482}\n" |  
  | charset: <unexpected> but was "UTF-8" |  
  | has_byte_order_marker: <unexpected> but was <false> |  
  | format: <unexpected> but was "ndjson" |  
  | timestamp_field: <unexpected> but was "release_date" |  
  | joda_timestamp_formats: <unexpected> but was <[ISO8601]> |  
  | java_timestamp_formats: <unexpected> but was <[ISO8601]> |  
  | need_client_timezone: <unexpected> but was <true> |  
  | mappings: <unexpected> but was <{properties={@timestamp={type=date}, author={type=keyword}, name={type=keyword}, page_count={type=long}, release_date={type=date, format=iso8601}}}> |  
  | ingest_pipeline: <unexpected> but was <{description=Ingest pipeline created by text structure finder, processors=[{date={field=release_date, timezone={{ event.timezone }}, formats=[ISO8601]}}]}> |  
  | field_stats: <unexpected> but was <{author={count=24, cardinality=20, top_hits=[{value=Frank Herbert, count=4}, {value=Robert A. Heinlein, count=2}, {value=Alastair Reynolds, count=1}, {value=Aldous Huxley, count=1}, {value=Dan Simmons, count=1}, {value=Douglas Adams, count=1}, {value=George Orwell, count=1}, {value=Iain M. Banks, count=1}, {value=Isaac Asimov, count=1}, {value=James S.A. Corey, count=1}]}, name={count=24, cardinality=24, top_hits=[{value=1984, count=1}, {value=A Fire Upon the Deep, count=1}, {value=Brave New World, count=1}, {value=Children of Dune, count=1}, {value=Consider Phlebas, count=1}, {value=Dune, count=1}, {value=Dune Messiah, count=1}, {value=Ender's Game, count=1}, {value=Fahrenheit 451, count=1}, {value=Foundation, count=1}]}, page_count={count=24, cardinality=24, min_value=180, max_value=768, mean_value=387.0833333333333, median_value=329.5, top_hits=[{value=180, count=1}, {value=208, count=1}, {value=224, count=1}, {value=227, count=1}, {value=268, count=1}, {value=271, count=1}, {value=275, count=1}, {value=288, count=1}, {value=304, count=1}, {value=311, count=1}]}, release_date={count=24, cardinality=20, earliest=1932-06-01, latest=2011-06-02, top_hits=[{value=1985-06-01, count=3}, {value=1969-06-01, count=2}, {value=1992-06-01, count=2}, {value=1932-06-01, count=1}, {value=1951-06-01, count=1}, {value=1953-10-15, count=1}, {value=1959-12-01, count=1}, {value=1965-06-01, count=1}, {value=1966-04-01, count=1}, {value=1969-10-15, count=1}]}}> |  
```

**Comment by droberts195** [comment] 2021-11-05 13:14
This is a weird one.  The failure message seems to think it was wanting an `AcknowledgedResponse`.  Instead it got the exact response that's specified as the expected response:

https://github.com/elastic/elasticsearch/blob/b4d671a6b710eb6ccde398ed64b764ea73fd3e89/docs/reference/text-structure/apis/find-structure.asciidoc#L281-L525

I cannot understand why the test thought that the expected response should be an `AcknowledgedResponse`.

**Comment by lcawl** [comment] 2021-11-05 17:38
i haven't been able to make this occur locally by running `./gradlew ':docs:integTest' --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/text-structure/apis/find-structure/line_250}" -Dtests.seed=1CB3E881F39A0FE4 -Dtests.locale=en-MT -Dtests.timezone=Australia/LHI -Druntime.java=17	`

but am spinning up a master cluster to see if the response has changed somehow.

**Comment by lcawl** [comment] 2021-11-05 18:31
I am not sure if it's the cause of this problem or not, but when I run the example on a master or 7.16 cluster in Dev Tools, I get the following result:

> {
  "num_lines_analyzed" : 24,
  "num_messages_analyzed" : 24,
  "sample_start" : """{"name": "Leviathan Wakes", "author": "James S.A. Corey", "release_date": "2011-06-02", "page_count": 561}
{"name": "Hyperion", "author": "Dan Simmons", "release_date": "1989-05-26", "page_count": 482}
""",
  "charset" : "UTF-8",
  ...

NOTE the three quotation marks instead of a single quotation mark. Perhaps this affects the code check?

**Comment by benwtrent** [comment] 2021-11-05 20:33
In lisa's comment, for some reason a text-block from java is being serialized instead of escaping the inner quotes. This is not good. I am guessing this has to do with some internal XContent change or just the change to Java17?

**Comment by droberts195** [comment] 2021-11-08 15:32
Strangely this hasn't failed today even though the test isn't muted.  Maybe it's been fixed by some other change that's happened recently...

**Comment by lockewritesdocs** [comment] 2022-04-28 21:03
This seems to be a transient CI issue, so I'm marking this issue as closed.

**Closed by lockewritesdocs** 2022-04-28 21:03 UTC
Labels: >docs, >test-failure, :ml, Team:Docs, Team:ML
