### ISSUE TITLE
aggregation filter does not work for child aggregation

### ISSUE THREAD

**Issue by xuralf** [elastic/elasticsearch#15005] opened 2015-11-25 09:53 UTC
Hi, 
   I have a parent-child structure index, where I want to do filtering on child type documents while doing child-aggregation. 
   For example, the child type has a field of date, and I want to set the range of the date field in the child aggregation.
   Is that possible even in the latest version (2.0)?
   Thank you guies very much.

**Comment by jpountz** [comment] 2015-11-25 09:56
Can you post a recreation of what you are doing today and that doesn't work?

**Comment by saai** [comment] 2015-11-25 10:05
hi jpountz,  I am xuralf's colleague, and here is the problem.

the querying json is as followed:

{
  "query" : {
    "filtered" : {
      "query" : {
        "bool" : {
          "must" : {
            "has_child" : {
              "query" : {
                "bool" : { }
              },
              "child_type" : "hotel-level-lose-stat"
            }
          }
        }
      },
      "filter" : {
        "bool" : {
          "must" : {
            "has_child" : {
              "filter" : {
                "bool" : {
                  "must" : {
                    "range" : {
                      "report_date" : {
                        "from" : "2015-11-01",
                        "to" : "2015-11-03",
                        "include_lower" : true,
                        "include_upper" : true
                      }
                    }
                  }
                }
              },
              "child_type" : "hotel-level-lose-stat"
            }
          }
        }
      }
    }
  },
  "aggregations" : {
    "sales_center" : {
      "terms" : {
        "field" : "sales_center",
        "size" : 0
      },
      "aggregations" : {
        "region" : {
          "terms" : {
            "field" : "region",
            "size" : 0
          },
          "aggregations" : {
            "sales_area" : {
              "terms" : {
                "field" : "sales_area",
                "size" : 0
              },
              "aggregations" : {
                "secondary_area" : {
                  "terms" : {
                    "field" : "secondary_area",
                    "size" : 0
                  },
                  "aggregations" : {
                    "city_name.raw" : {
                      "terms" : {
                        "field" : "city_name.raw",
                        "size" : 0
                      },
                      "aggregations" : {
                        "manager_name.raw" : {
                          "terms" : {
                            "field" : "manager_name.raw",
                            "size" : 0
                          },
                          "aggregations" : {
                            "trading_area.raw" : {
                              "terms" : {
                                "field" : "trading_area.raw",
                                "size" : 0
                              },
                              "aggregations" : {
                                "competitor_price" : {
                                  "children" : {
                                    "type" : "hotel-level-lose-stat"
                                  },
                                  "aggregations" : {
                                    "competitor_price" : {
                                      "date_histogram" : {
                                        "field" : "report_date",
                                        "interval" : "1d",
                                        "min_doc_count" : 0,
                                        "format" : "yyyy-MM-dd",
                                        "extended_bounds" : {
                                          "min" : "2015-11-01",
                                          "max" : "2015-11-03"
                                        }
                                      },
                                      "aggregations" : {
                                        "competitor_price" : {
                                          "filter" : {
                                            "exists" : {
                                              "field" : "competitor_price"
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                },
                                "lose_result" : {
                                  "children" : {
                                    "type" : "hotel-level-lose-stat"
                                  },
                                  "aggregations" : {
                                    "lose_result" : {
                                      "date_histogram" : {
                                        "field" : "report_date",
                                        "interval" : "1d",
                                        "min_doc_count" : 0,
                                        "format" : "yyyy-MM-dd",
                                        "extended_bounds" : {
                                          "min" : "2015-11-01",
                                          "max" : "2015-11-03"
                                        }
                                      },
                                      "aggregations" : {
                                        "lose_result" : {
                                          "filter" : {
                                            "bool" : {
                                              "must" : {
                                                "range" : {
                                                  "report_date" : {
                                                    "from" : "2015-11-01",
                                                    "to" : "2015-11-03",
                                                    "include_lower" : true,
                                                    "include_upper" : true
                                                  }
                                                }
                                              }
                                            }
                                          },
                                          "aggregations" : {
                                            "lose_result" : {
                                              "terms" : {
                                                "field" : "lose_result"
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}


and the returning json is 

{
  "took" : 300,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 0.0,
    "hits" : [ ]
  },
  "aggregations" : {
    "sales_center" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 0,
      "buckets" : [ {
        "key" : "高星酒店",
        "doc_count" : 1,
        "region" : {
          "doc_count_error_upper_bound" : 0,
          "sum_other_doc_count" : 0,
          "buckets" : [ {
            "key" : "高星酒店",
            "doc_count" : 1,
            "sales_area" : {
              "doc_count_error_upper_bound" : 0,
              "sum_other_doc_count" : 0,
              "buckets" : [ {
                "key" : "西南区域",
                "doc_count" : 1,
                "secondary_area" : {
                  "doc_count_error_upper_bound" : 0,
                  "sum_other_doc_count" : 0,
                  "buckets" : [ {
                    "key" : "四川",
                    "doc_count" : 1,
                    "city_name.raw" : {
                      "doc_count_error_upper_bound" : 0,
                      "sum_other_doc_count" : 0,
                      "buckets" : [ {
                        "key" : "阿坝",
                        "doc_count" : 1,
                        "manager_name.raw" : {
                          "doc_count_error_upper_bound" : 0,
                          "sum_other_doc_count" : 0,
                          "buckets" : [ {
                            "key" : "彭洁",
                            "doc_count" : 1,
                            "trading_area.raw" : {
                              "doc_count_error_upper_bound" : 0,
                              "sum_other_doc_count" : 0,
                              "buckets" : [ {
                                "key" : "未确定",
                                "doc_count" : 1,
                                "lose_result" : {
                                  "doc_count" : 2,
                                  "lose_result" : {
                                    "buckets" : [ {
                                      "key_as_string" : "2015-11-01",
                                      "key" : 1446336000000,
                                      "doc_count" : 0,
                                      "lose_result" : {
                                        "doc_count" : 0,
                                        "lose_result" : {
                                          "doc_count_error_upper_bound" : 0,
                                          "sum_other_doc_count" : 0,
                                          "buckets" : [ ]
                                        }
                                      }
                                    }, {
                                      "key_as_string" : "2015-11-02",
                                      "key" : 1446422400000,
                                      "doc_count" : 1,
                                      "lose_result" : {
                                        "doc_count" : 0,
                                        "lose_result" : {
                                          "doc_count_error_upper_bound" : 0,
                                          "sum_other_doc_count" : 0,
                                          "buckets" : [ ]
                                        }
                                      }
                                    }, {
                                      "key_as_string" : "2015-11-03",
                                      "key" : 1446508800000,
                                      "doc_count" : 0,
                                      "lose_result" : {
                                        "doc_count" : 0,
                                        "lose_result" : {
                                          "doc_count_error_upper_bound" : 0,
                                          "sum_other_doc_count" : 0,
                                          "buckets" : [ ]
                                        }
                                      }
                                    }, {
                                      "key_as_string" : "2015-11-04",
                                      "key" : 1446595200000,
                                      "doc_count" : 0,
                                      "lose_result" : {
                                        "doc_count" : 0,
                                        "lose_result" : {
                                          "doc_count_error_upper_bound" : 0,
                                          "sum_other_doc_count" : 0,
                                          "buckets" : [ ]
                                        }
                                      }
                                    }, {
                                      "key_as_string" : "2015-11-05",
                                      "key" : 1446681600000,
                                      "doc_count" : 0,
                                      "lose_result" : {
                                        "doc_count" : 0,
                                        "lose_result" : {
                                          "doc_count_error_upper_bound" : 0,
                                          "sum_other_doc_count" : 0,
                                          "buckets" : [ ]
                                        }
                                      }
                                    }, {
                                      "key_as_string" : "2015-11-06",
                                      "key" : 1446768000000,
                                      "doc_count" : 0,
                                      "lose_result" : {
                                        "doc_count" : 0,
                                        "lose_result" : {
                                          "doc_count_error_upper_bound" : 0,
                                          "sum_other_doc_count" : 0,
                                          "buckets" : [ ]
                                        }
                                      }
                                    }, {
                                      "key_as_string" : "2015-11-07",
                                      "key" : 1446854400000,
                                      "doc_count" : 0,
                                      "lose_result" : {
                                        "doc_count" : 0,
                                        "lose_result" : {
                                          "doc_count_error_upper_bound" : 0,
                                          "sum_other_doc_count" : 0,
                                          "buckets" : [ ]
                                        }
                                      }
                                    }, {
                                      "key_as_string" : "2015-11-08",
                                      "key" : 1446940800000,
                                      "doc_count" : 0,
                                      "lose_result" : {
                                        "doc_count" : 0,
                                        "lose_result" : {
                                          "doc_count_error_upper_bound" : 0,
                                          "sum_other_doc_count" : 0,
                                          "buckets" : [ ]
                                        }
                                      }
                                    }, {
                                      "key_as_string" : "2015-11-09",
                                      "key" : 1447027200000,
                                      "doc_count" : 0,
                                      "lose_result" : {
                                        "doc_count" : 0,
                                        "lose_result" : {
                                          "doc_count_error_upper_bound" : 0,
                                          "sum_other_doc_count" : 0,
                                          "buckets" : [ ]
                                        }
                                      }
                                    }, {
                                      "key_as_string" : "2015-11-10",
                                      "key" : 1447113600000,
                                      "doc_count" : 0,
                                      "lose_result" : {
                                        "doc_count" : 0,
                                        "lose_result" : {
                                          "doc_count_error_upper_bound" : 0,
                                          "sum_other_doc_count" : 0,
                                          "buckets" : [ ]
                                        }
                                      }
                                    }, {
                                      "key_as_string" : "2015-11-11",
                                      "key" : 1447200000000,
                                      "doc_count" : 0,
                                      "lose_result" : {
                                        "doc_count" : 0,
                                        "lose_result" : {
                                          "doc_count_error_upper_bound" : 0,
                                          "sum_other_doc_count" : 0,
                                          "buckets" : [ ]
                                        }
                                      }
                                    }, {
                                      "key_as_string" : "2015-11-12",
                                      "key" : 1447286400000,
                                      "doc_count" : 1,
                                      "lose_result" : {
                                        "doc_count" : 0,
                                        "lose_result" : {
                                          "doc_count_error_upper_bound" : 0,
                                          "sum_other_doc_count" : 0,
                                          "buckets" : [ ]
                                        }
                                      }
                                    } ]
                                  }
                                },
                                "competitor_price" : {
                                  "doc_count" : 2,
                                  "competitor_price" : {
                                    "buckets" : [ {
                                      "key_as_string" : "2015-11-01",
                                      "key" : 1446336000000,
                                      "doc_count" : 0,
                                      "competitor_price" : {
                                        "doc_count" : 0
                                      }
                                    }, {
                                      "key_as_string" : "2015-11-02",
                                      "key" : 1446422400000,
                                      "doc_count" : 1,
                                      "competitor_price" : {
                                        "doc_count" : 1
                                      }
                                    }, {
                                      "key_as_string" : "2015-11-03",
                                      "key" : 1446508800000,
                                      "doc_count" : 0,
                                      "competitor_price" : {
                                        "doc_count" : 0
                                      }
                                    }, {
                                      "key_as_string" : "2015-11-04",
                                      "key" : 1446595200000,
                                      "doc_count" : 0,
                                      "competitor_price" : {
                                        "doc_count" : 0
                                      }
                                    }, {
                                      "key_as_string" : "2015-11-05",
                                      "key" : 1446681600000,
                                      "doc_count" : 0,
                                      "competitor_price" : {
                                        "doc_count" : 0
                                      }
                                    }, {
                                      "key_as_string" : "2015-11-06",
                                      "key" : 1446768000000,
                                      "doc_count" : 0,
                                      "competitor_price" : {
                                        "doc_count" : 0
                                      }
                                    }, {
                                      "key_as_string" : "2015-11-07",
                                      "key" : 1446854400000,
                                      "doc_count" : 0,
                                      "competitor_price" : {
                                        "doc_count" : 0
                                      }
                                    }, {
                                      "key_as_string" : "2015-11-08",
                                      "key" : 1446940800000,
                                      "doc_count" : 0,
                                      "competitor_price" : {
                                        "doc_count" : 0
                                      }
                                    }, {
                                      "key_as_string" : "2015-11-09",
                                      "key" : 1447027200000,
                                      "doc_count" : 0,
                                      "competitor_price" : {
                                        "doc_count" : 0
                                      }
                                    }, {
                                      "key_as_string" : "2015-11-10",
                                      "key" : 1447113600000,
                                      "doc_count" : 0,
                                      "competitor_price" : {
                                        "doc_count" : 0
                                      }
                                    }, {
                                      "key_as_string" : "2015-11-11",
                                      "key" : 1447200000000,
                                      "doc_count" : 0,
                                      "competitor_price" : {
                                        "doc_count" : 0
                                      }
                                    }, {
                                      "key_as_string" : "2015-11-12",
                                      "key" : 1447286400000,
                                      "doc_count" : 1,
                                      "competitor_price" : {
                                        "doc_count" : 1
                                      }
                                    } ]
                                  }
                                }
                              } ]
                            }
                          } ]
                        }
                      } ]
                    }
                  } ]
                }
              } ]
            }
          } ]
        }
      } ]
    }
  }
}

the returning date is out of [2015-11-01,2015-11-03] , we can see the data of 2015-11-04 etc,

 it seems that the aggregation filter doesn't work, please help me !!

**Comment by saai** [comment] 2015-11-25 10:26
the returned report_date value is exceeding the range filter , which is from 2015-11-01 to 2015-11-03, 

is the child aggregation filter doesn't work ? or did I wrongly set the filter?

**Comment by saai** [comment] 2015-11-25 11:42
I did another test, the json is much easier,

the query json 
{
  "aggregations" : {
    "sales_center" : {
      "terms" : {
        "field" : "sales_center"
      },
      "aggregations" : {
        "region" : {
          "terms" : {
            "field" : "region"
          },
          "aggregations" : {
            "sales_area" : {
              "terms" : {
                "field" : "sales_area"
              },
              "aggregations" : {
                "secondary_area" : {
                  "terms" : {
                    "field" : "secondary_area"
                  },
                  "aggregations" : {
                    "city_name.raw" : {
                      "terms" : {
                        "field" : "city_name.raw"
                      },
                      "aggregations" : {
                        "manager_name.raw" : {
                          "terms" : {
                            "field" : "manager_name.raw"
                          },
                          "aggregations" : {
                            "lose_stat" : {
                              "children" : {
                                "type" : "hotel-level-lose-stat"
                              },
                              "aggregations" : {
                                "qunar_scope_filter" : {
                                  "filter" : {
                                    "terms" : {
                                      "quanr_scope" : [ "ZHI_XIAO" ]
                                    }
                                  }
                                },
                                "qunar_scope" : {
                                  "terms" : {
                                    "field" : "qunar_scope"
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}


the returned results
{
  "took" : 190,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "hits" : {
    "total" : 3,
    "max_score" : 0.0,
    "hits" : [ ]
  },
  "aggregations" : {
    "sales_center" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 0,
      "buckets" : [ {
        "key" : "高星酒店",
        "doc_count" : 2,
        "region" : {
          "doc_count_error_upper_bound" : 0,
          "sum_other_doc_count" : 0,
          "buckets" : [ {
            "key" : "高星酒店",
            "doc_count" : 2,
            "sales_area" : {
              "doc_count_error_upper_bound" : 0,
              "sum_other_doc_count" : 0,
              "buckets" : [ {
                "key" : "西南区域",
                "doc_count" : 2,
                "secondary_area" : {
                  "doc_count_error_upper_bound" : 0,
                  "sum_other_doc_count" : 0,
                  "buckets" : [ {
                    "key" : "四川",
                    "doc_count" : 2,
                    "city_name.raw" : {
                      "doc_count_error_upper_bound" : 0,
                      "sum_other_doc_count" : 0,
                      "buckets" : [ {
                        "key" : "阿坝",
                        "doc_count" : 2,
                        "manager_name.raw" : {
                          "doc_count_error_upper_bound" : 0,
                          "sum_other_doc_count" : 0,
                          "buckets" : [ {
                            "key" : "向璐",
                            "doc_count" : 1,
                            "lose_stat" : {
                              "doc_count" : 1,
                              "qunar_scope_filter" : {
                                "doc_count" : 0
                              },
                              "qunar_scope" : {
                                "doc_count_error_upper_bound" : 0,
                                "sum_other_doc_count" : 0,
                                "buckets" : [ {
                                  "key" : "ZHI_XIAO_AND_AGENTS",
                                  "doc_count" : 1
                                } ]
                              }
                            }
                          }, {
                            "key" : "彭洁",
                            "doc_count" : 1,
                            "lose_stat" : {
                              "doc_count" : 2,
                              "qunar_scope_filter" : {
                                "doc_count" : 0
                              },
                              "qunar_scope" : {
                                "doc_count_error_upper_bound" : 0,
                                "sum_other_doc_count" : 0,
                                "buckets" : [ {
                                  "key" : "ZHI_XIAO",
                                  "doc_count" : 2
                                } ]
                              }
                            }
                          } ]
                        }
                      } ]
                    }
                  } ]
                }
              } ]
            }
          } ]
        }
      }, {
        "key" : "单体直销中心",
        "doc_count" : 1,
        "region" : {
          "doc_count_error_upper_bound" : 0,
          "sum_other_doc_count" : 0,
          "buckets" : [ {
            "key" : "华中大区",
            "doc_count" : 1,
            "sales_area" : {
              "doc_count_error_upper_bound" : 0,
              "sum_other_doc_count" : 0,
              "buckets" : [ {
                "key" : "华西南",
                "doc_count" : 1,
                "secondary_area" : {
                  "doc_count_error_upper_bound" : 0,
                  "sum_other_doc_count" : 0,
                  "buckets" : [ {
                    "key" : "川贵",
                    "doc_count" : 1,
                    "city_name.raw" : {
                      "doc_count_error_upper_bound" : 0,
                      "sum_other_doc_count" : 0,
                      "buckets" : [ {
                        "key" : "阿坝",
                        "doc_count" : 1,
                        "manager_name.raw" : {
                          "doc_count_error_upper_bound" : 0,
                          "sum_other_doc_count" : 0,
                          "buckets" : [ {
                            "key" : "黄晓静",
                            "doc_count" : 1,
                            "lose_stat" : {
                              "doc_count" : 0,
                              "qunar_scope_filter" : {
                                "doc_count" : 0
                              },
                              "qunar_scope" : {
                                "doc_count_error_upper_bound" : 0,
                                "sum_other_doc_count" : 0,
                                "buckets" : [ ]
                              }
                            }
                          } ]
                        }
                      } ]
                    }
                  } ]
                }
              } ]
            }
          } ]
        }
      } ]
    }
  }
}

we can see that the "qunar_scope_filter" aggregation  DID NOT  hit any doc which equals "ZHI_XIAO" , while qunar_scope aggregation has hits 2 documents of "ZHI_XIAO", they are both the sub aggregation of child type, so the filtered aggregation inside child aggregation does not work properly.

**Comment by jpountz** [comment] 2015-11-25 18:01
You seem to have a typo in your example:

```
                                    "terms" : {
                                      "quanr_scope" : [ "ZHI_XIAO" ]
                                    }
```

Should it be "qunar_scope" rather than "quanr_scope"? Could it be the cause of your problem?

**Comment by saai** [comment] 2015-11-26 02:49
@jpountz  Yes you are right , I passed the wrong field name for qunar_scope. But , here is another strange thing, when I pass the date type field "report_date" for filter, I got wrong result , the json is as followed.

the query json:
{
  "aggregations" : {
    "sales_center" : {
      "terms" : {
        "field" : "sales_center"
      },
      "aggregations" : {
        "lose_stat" : {
          "children" : {
            "type" : "hotel-level-lose-stat"
          },
          "aggregations" : {
            "qunar_scope" : {
              "terms" : {
                "field" : "qunar_scope"
              }
            },
            "qunar_scope_filter" : {
              "filter" : {
                "terms" : {
                  "qunar_scope" : [ "ZHI_XIAO" ]
                }
              },
              "aggregations" : {
                "lose_result" : {
                  "terms" : {
                    "field" : "lose_result"
                  }
                }
              }
            },
            "report_date_filter" : {
              "filter" : {
                "range" : {
                  "report_date" : {
                    "from" : "2015-11-01",
                    "to" : "2015-11-03",
                    "include_lower" : true,
                    "include_upper" : true
                  },
                  "_name" : "report_date"
                }
              },
              "aggregations" : {
                "lose_result" : {
                  "terms" : {
                    "field" : "lose_result"
                  }
                }
              }
            },
            "report_date" : {
              "terms" : {
                "field" : "report_date"
              }
            },
            "lose_result" : {
              "terms" : {
                "field" : "lose_result"
              }
            }
          }
        }
      }
    }
  }
}

the result json:
{
  "took" : 267,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "hits" : {
    "total" : 3,
    "max_score" : 0.0,
    "hits" : [ ]
  },
  "aggregations" : {
    "sales_center" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 0,
      "buckets" : [ {
        "key" : "高星酒店",
        "doc_count" : 2,
        "lose_stat" : {
          "doc_count" : 3,
          "report_date" : {
            "doc_count_error_upper_bound" : 0,
            "sum_other_doc_count" : 0,
            "buckets" : [ {
              "key" : 1446422400000,
              "key_as_string" : "2015-11-02",
              "doc_count" : 1
            }, {
              "key" : 1447286400000,
              "key_as_string" : "2015-11-12",
              "doc_count" : 1
            }, {
              "key" : 1448236800000,
              "key_as_string" : "2015-11-23",
              "doc_count" : 1
            } ]
          },
          "qunar_scope_filter" : {
            "doc_count" : 2,
            "lose_result" : {
              "doc_count_error_upper_bound" : 0,
              "sum_other_doc_count" : 0,
              "buckets" : [ {
                "key" : "PRICE_LOSE",
                "doc_count" : 2
              } ]
            }
          },
          "qunar_scope" : {
            "doc_count_error_upper_bound" : 0,
            "sum_other_doc_count" : 0,
            "buckets" : [ {
              "key" : "ZHI_XIAO",
              "doc_count" : 2
            }, {
              "key" : "ZHI_XIAO_AND_AGENTS",
              "doc_count" : 1
            } ]
          },
          "lose_result" : {
            "doc_count_error_upper_bound" : 0,
            "sum_other_doc_count" : 0,
            "buckets" : [ {
              "key" : "PRICE_LOSE",
              "doc_count" : 3
            } ]
          },
          "report_date_filter" : {
            "doc_count" : 0,
            "lose_result" : {
              "doc_count_error_upper_bound" : 0,
              "sum_other_doc_count" : 0,
              "buckets" : [ ]
            }
          }
        }
      }, {
        "key" : "单体直销中心",
        "doc_count" : 1,
        "lose_stat" : {
          "doc_count" : 0,
          "report_date" : {
            "doc_count_error_upper_bound" : 0,
            "sum_other_doc_count" : 0,
            "buckets" : [ ]
          },
          "qunar_scope_filter" : {
            "doc_count" : 0,
            "lose_result" : {
              "doc_count_error_upper_bound" : 0,
              "sum_other_doc_count" : 0,
              "buckets" : [ ]
            }
          },
          "qunar_scope" : {
            "doc_count_error_upper_bound" : 0,
            "sum_other_doc_count" : 0,
            "buckets" : [ ]
          },
          "lose_result" : {
            "doc_count_error_upper_bound" : 0,
            "sum_other_doc_count" : 0,
            "buckets" : [ ]
          },
          "report_date_filter" : {
            "doc_count" : 0,
            "lose_result" : {
              "doc_count_error_upper_bound" : 0,
              "sum_other_doc_count" : 0,
              "buckets" : [ ]
            }
          }
        }
      } ]
    }
  }
}


the report_date_filter did not hit any doc, since the range is [2015-11-01, 2015-11-03],  the doc 2015-11-02 should be hit, did I wrongly set  the date filter ? Thanks in advance!!

**Comment by clintongormley** [comment] 2015-11-27 13:07
Hi @saai 

As @jpountz said before, please could you upload a full (minimal) recreation, ie show how you create the index, index the docs, then run the query.  Otherwise we're just guessing.

**Comment by saai** [comment] 2015-12-09 02:57
Hello @jpountz and @clintongormley , Here I am again... 
I have made a simple example to show the issue more explicitly.
An index, which has two types , hotel which is the parent , and order which is the child. 
hotel has 3 fields: hotel_seq (id), hotel_name, hotel_level ,
order has 4 fields: report_date (date type), hotel_seq, selling_type (indicates whether the order is from the website or mobile apps), price (the price of the order).
I use java to create the index, and here are the XContentBuilder of hotel and order:
<pre><code>

XContentBuilder parentJson = XContentFactory.jsonBuilder()
                .startObject()
                .startObject("properties")
                .startObject("hotel_seq").field("type", "string").field("index", "not_analyzed").field("doc_values", true).endObject()
                .startObject("hotel_name").field("type", "string").field("analyzer", "cjk").startObject("fields").startObject("raw").field("type", "string").field("index", "not_analyzed").field("doc_values", true).endObject().endObject().endObject()
                .startObject("hotel_level").field("type", "string").field("index", "not_analyzed").field("doc_values", true).endObject()
                .endObject()
                .endObject()
                ;
XContentBuilder childJson = XContentFactory.jsonBuilder()
                .startObject()
                .startObject("_parent").field("type", parentType).endObject()
                .startObject("properties")
                .startObject("report_date").field("type", "date").field("format", "yyyy-MM-dd").endObject()
                .startObject("hotel_seq").field("type", "string").field("index", "not_analyzed").field("doc_values", true).endObject()
                .startObject("selling_type").field("type", "string").field("index", "not_analyzed").field("doc_values", true).endObject()
                .startObject("price").field("type", "double").field("index", "not_analyzed").field("doc_values", true).endObject()
                .endObject()
                .endObject()
                ; 
</code></pre>

then , I put 2 hotels and 3 orders data into the index, here are the json of the data

<pre><code>
XContentBuilder hotel1 = XContentFactory.jsonBuilder()
                .startObject()
                .field("hotel_seq", "aba_201")
                .field("hotel_name","holidays inn")
                .field("hotel_level", "B")
                .endObject();
        XContentBuilder hotel2 = XContentFactory.jsonBuilder()
                .startObject()
                .field("hotel_seq", "aba_202")
                .field("hotel_name", "four seasons")
                .field("hotel_level", "A")
                .endObject();
        XContentBuilder order1 = XContentFactory.jsonBuilder()
                .startObject()
                .field("report_date", "2015-11-01")
                .field("hotel_seq", "aba_201")
                .field("selling_type", "WEBSITE")
                .field("price", 766.0)
                .endObject();
        XContentBuilder order2 = XContentFactory.jsonBuilder()
                .startObject()
                .field("report_date", "2015-11-03")
                .field("hotel_seq", "aba_201")
                .field("selling_type", "APP")
                .field("price", 766.0)
                .endObject();
        XContentBuilder order3 = XContentFactory.jsonBuilder()
                .startObject()
                .field("report_date","2015-11-02")
                .field("hotel_seq", "aba_202")
                .field("selling_type", "WEBSITE")
                .field("price", 1666.0)
                .endObject();
</code></pre>

Then I try to query the incomes of selling_type "WEBSITE" and the incomes from report_date 2015-11-01 to 2015-11-03, aggregated by hotel_level in parent fields . In order to compare, I also added two child aggregation of report_date terms and selling_type terms.

the request json is as followed:
<pre><code>
{
  "aggregations" : {
    "hotel_level" : {
      "terms" : {
        "field" : "hotel_level"
      },
      "aggregations" : {
        "order" : {
          "children" : {
            "type" : "child-order"
          },
          "aggregations" : {
            "selling_type_terms" : {
              "terms" : {
                "field" : "selling_type"
              }
            },
            "report_date_terms" : {
              "terms" : {
                "field" : "report_date"
              }
            },
            "selling_type_WEBSITE" : {
              "filter" : {
                "terms" : {
                  "selling_type" : [ "WEBSITE" ]
                }
              },
              "aggregations" : {
                "income" : {
                  "sum" : {
                    "field" : "price"
                  }
                }
              }
            },
            "report_date_20151101_20151103" : {
              "filter" : {
                "range" : {
                  "report_date" : {
                    "from" : "2015-11-01",
                    "to" : "2015-11-03",
                    "include_lower" : true,
                    "include_upper" : true
                  }
                }
              },
              "aggregations" : {
                "income" : {
                  "sum" : {
                    "field" : "price"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
</pre></code>

and the result is 

<pre><code>
{
  "took" : 1373,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : 0.0,
    "hits" : [ ]
  },
  "aggregations" : {
    "hotel_level" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 0,
      "buckets" : [ {
        "key" : "A",
        "doc_count" : 1,
        "order" : {
          "doc_count" : 1,
          "report_date_20151101_20151103" : {
            "doc_count" : 0,
            "income" : {
              "value" : 0.0
            }
          },
          "selling_type_WEBSITE" : {
            "doc_count" : 1,
            "income" : {
              "value" : 1666.0
            }
          },
          "selling_type_terms" : {
            "doc_count_error_upper_bound" : 0,
            "sum_other_doc_count" : 0,
            "buckets" : [ {
              "key" : "WEBSITE",
              "doc_count" : 1
            } ]
          },
          "report_date_terms" : {
            "doc_count_error_upper_bound" : 0,
            "sum_other_doc_count" : 0,
            "buckets" : [ {
              "key" : 1446422400000,
              "key_as_string" : "2015-11-02",
              "doc_count" : 1
            } ]
          }
        }
      }, {
        "key" : "B",
        "doc_count" : 1,
        "order" : {
          "doc_count" : 2,
          "report_date_20151101_20151103" : {
            "doc_count" : 0,
            "income" : {
              "value" : 0.0
            }
          },
          "selling_type_WEBSITE" : {
            "doc_count" : 1,
            "income" : {
              "value" : 766.0
            }
          },
          "selling_type_terms" : {
            "doc_count_error_upper_bound" : 0,
            "sum_other_doc_count" : 0,
            "buckets" : [ {
              "key" : "APP",
              "doc_count" : 1
            }, {
              "key" : "WEBSITE",
              "doc_count" : 1
            } ]
          },
          "report_date_terms" : {
            "doc_count_error_upper_bound" : 0,
            "sum_other_doc_count" : 0,
            "buckets" : [ {
              "key" : 1446336000000,
              "key_as_string" : "2015-11-01",
              "doc_count" : 1
            }, {
              "key" : 1446508800000,
              "key_as_string" : "2015-11-03",
              "doc_count" : 1
            } ]
          }
        }
      } ]
    }
  }
}
</pre></code>

In hotel_level bucket "A", I got 1666.0 for the total incomes of WEBSITE ,which is right,  but 0 for total incomes from 20151101 to 20151103, which should be 1666.0,  so I guess that the date range filter is not working in child aggregations.

**Comment by clintongormley** [comment] 2015-12-14 20:31
@martijnvg Please could you have a look at this?

**Comment by clintongormley** [comment] 2015-12-14 20:32
Related to https://github.com/elastic/elasticsearch/issues/15413 ?

**Comment by martijnvg** [comment] 2015-12-15 20:59
@saai I tried to make a reproduction based on what you have shared in your latest comment:

Mappings and documents:

```
DELETE /_all

PUT /test
{
  "mappings": {
    "parentType" : {
      "properties": {
        "hotel_name": {"type": "string"},
        "hotel_level" : {"type": "string", "index": "not_analyzed"}
      }
    },
    "childType": {
      "_parent": {
        "type": "parentType"
      },
      "properties": {
        "selling_type" : {"type": "string", "index": "not_analyzed"},
        "price" : {"type": "double", "index": "not_analyzed"},
        "report_date": {"type": "date", "format": "yyyy-MM-dd"}
      }
    }
  }
}

PUT /test/parentType/1
{
  "hotel_name":"holidays inn",
  "hotel_level": "B"
}

PUT /test/parentType/2
{
  "hotel_name": "four seasons",
  "hotel_level": "A"
}

PUT /test/childType/order1?parent=1
{
  "report_date": "2015-11-01",
  "selling_type": "WEBSITE",
  "price": 766.0
}

PUT /test/childType/order2?parent=1
{
  "report_date": "2015-11-03",
  "selling_type": "APP",
  "price": 766.0  
}

PUT /test/childType/order3?parent=2
{
  "report_date": "2015-11-02",
  "selling_type": "WEBSITE",
  "price": 1666.0
}
```

Search request:

```
GET /test/_search
{
  "size": 0, 
  "aggregations" : {
    "hotel_level" : {
      "terms" : {
        "field" : "hotel_level"
      },
      "aggregations" : {
        "order" : {
          "children" : {
            "type" : "childType"
          },
          "aggregations" : {
            "selling_type_terms" : {
              "terms" : {
                "field" : "selling_type"
              }
            },
            "report_date_terms" : {
              "terms" : {
                "field" : "report_date"
              }
            },
            "selling_type_WEBSITE" : {
              "filter" : {
                "terms" : {
                  "selling_type" : [ "WEBSITE" ]
                }
              },
              "aggregations" : {
                "income" : {
                  "sum" : {
                    "field" : "price"
                  }
                }
              }
            },
            "report_date_20151101_20151103" : {
              "filter" : {
                "range" : {
                  "report_date" : {
                    "from" : "2015-11-01",
                    "to" : "2015-11-03",
                    "include_lower" : true,
                    "include_upper" : true
                  }
                }
              },
              "aggregations" : {
                "income" : {
                  "sum" : {
                    "field" : "price"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

When running this I do get results for the `report_date_20151101_20151103`(income is 1666). So this looks good here, but maybe my reproduction isn't exactly the same? (something got lost between translating the java snippets to curl requests)

Some questions:
* Can you try and run the reproduction I have shared here? 
* What ES version are you using exactly? 
* Did you run your reproduction on already existing index?

**Comment by saai** [comment] 2016-01-04 04:17
@martijnvg Thanks for the reply, your reproduction is working fine. Since I am using the version 1.7.1, I guess this is an old bug for "date" type,  it will take some time for my project to update to the version 2.0 +, I will let you know if I found the same issue after the update...

Again thanks very much for your conscientious reply !!!

**Comment by clintongormley** [comment] 2016-02-14 17:57
thanks @saai - closing

**Closed by clintongormley** 2016-02-14 17:57 UTC
Labels: :Aggregations, :Parent/Child, bug, feedback_needed
