### ISSUE TITLE
rolling upgrade tests (80_data_frame_jobs_crud) are failing

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#48336] opened 2019-10-22 10:26 UTC
Two failures today:

Build | 20191022094655-F9FE3750
Log | https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+bwc/BWC_VERSION=7.2.0,nodes=centos-7&&immutable/233/console
Build Scans | https://gradle-enterprise.elastic.co/s/tsrfkk4svewle

Build | 20191022094654-1329FC63
Log | https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+bwc/BWC_VERSION=7.2.1,nodes=centos-7&&immutable/233/console
Build Scans | https://gradle-enterprise.elastic.co/s/hg4o5qjzu7kgm

Is it somehow related to this commit? https://github.com/elastic/elasticsearch/commit/8003677bfc6e582189fbb291e2f56daeddfb28e1

**Comment by hendrikmuhs** [comment] 2019-10-22 10:57
@przemekwitek Thanks!

It's probably caused by this #48302, fortunately not backported to 7.4 yet. I am looking into it.

**Comment by przemekwitek** [comment] 2019-10-22 11:11
Another instance:


Build | 20191022105833-1A0A06B3
Log | https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+default-distro+bwc/BWC_VERSION=7.2.0,nodes=centos-7&&immutable/229/console
Build Scans | https://gradle-enterprise.elastic.co/s/nm7af4pesba6s

**Comment by hendrikmuhs** [comment] 2019-10-23 07:30
fixed with #48344

**Closed by hendrikmuhs** 2019-10-23 07:30 UTC
Labels: :ml/Transform
