### ISSUE TITLE
[Fielddata] Terms aggregation on keyword field with doc values consume huge fielddata cache, may cause OOM

### ISSUE THREAD

**Issue by viewsite** [elastic/elasticsearch#32761] opened 2018-08-10 03:04 UTC
**Description of the problem including expected versus actual behavior**:

From issue #12394 we know that in-memory field data for field-types that support doc-values are removed. But, every time after running a big terms aggregation query on a keyword field enabled with doc_values,  which has one hundred million buckets,  my field data cache is being consumed up to 7.1gb and triggered parent breaker,  cause normal requests to the cluster to be rejected continuously.  The parent-level breaker is configured with 30% of 20gb JVM heap,  the field data circuit breaker is configured with 3% of JVM heap and I expect them to protect cluster. When can keyword field with doc values enabled consume field data cache and cause a lot of memory?

**Elasticsearch version** (`bin/elasticsearch --version`):  5.6.4 

**Plugins installed**: none

**JVM version** (`java -version`):  1.8.0_91-b14

**Elasticsearch.yml** :  

> 
indices.queries.cache.count: 500
processors: 2
cluster.routing.allocation.disk.watermark.high: 95%
cluster.routing.allocation.disk.watermark.low: 90%
network.publish_host: 1.1.1.1
indices.queries.cache.size: 5%
node.data: true
discovery.zen.minimum_master_nodes: 1
cluster.name: pe5qmzs4
node.master: true
node.attr.ip: 1.1.1.1
node.ingest: true
transport.tcp.port: 9300
indices.memory.index_buffer_size: 15%
thread_pool.bulk.queue_size: 1024
http.port: 9200
network.host: 0.0.0.0
indices.breaker.request.limit: 6%
indices.breaker.fielddata.limit: 3%
indices.breaker.total.limit: 30%

**JVM**:
-Xms20000m
-Xmx20000m

**Steps to reproduce**:

 1.   Prepare a cluster with 150gb data that contains a keyword field with one hundred million distinct value
 2.  Run the query below
> GET index/_search?
{
    "size": 0,
   "aggregations": {  
        "agg_trace_id": {  
            "terms": {  
                "field": "keyword_field"
            }
        }
    }  
}

**Fielddata**:
Sending _stats/fielddata?fields=keyword_field&human=true 
Result: 
> {
  "_shards" : {
    "total" : 231,
    "successful" : 157,
    "failed" : 73,
    "failures" : [
      { 
        "shard" : 2,
        "index" : "index",
        "status" : "INTERNAL_SERVER_ERROR",
        "reason" : {
          "type" : "failed_node_exception",
          "reason" : "Failed node [lg8-CJLRS_KUlb2tkAWnZw]",
          "caused_by" : {
            "type" : "circuit_breaking_exception",
            "reason" : "[parent] Data too large, data for [<transport_request>] would be [7647861567/7.1gb], which is larger than the limit of [6192011673/5.7gb]",
            "bytes_wanted" : 7647861567,
            "bytes_limit" : 6192011673
          }
        }
      }
    ]
  },
  "_all" : {
    "primaries" : {
      "fielddata" : {
        "memory_size" : "3.1gb",
        "memory_size_in_bytes" : 3432930008,
        "evictions" : 0,
        "fields" : {
          "keyword_field" : {
            "memory_size" : "3.1gb",
            "memory_size_in_bytes" : 3432930008
          }
        }
      }
    }
........................

By adding execution_hint: map to my aggregation,  it takes effects and the aggregation does not consume field data cache anymore. But I think keyword field with doc values should not consume field data cache and cause huge memory, and the field data breaker should have worked. I think it is a bug.  Eager for any help.

**Comment by viewsite** [comment] 2018-08-10 03:13
@clintongormley  @elasticmachine

**Comment by viewsite** [comment] 2018-08-10 03:14
Thanks for any help

**Comment by markharwood** [comment] 2018-08-10 09:30
The `fielddata` settings you might pick for a field are only one of several potential contributors to the overall internal fielddata accounting that is reported. 

Even if you don't select to use fielddata in your mapping certain actions may cause other field-related structures to be loaded into memory e.g. your `terms` aggregation may have triggered the use of a global ordinals map under the covers to service the request. These costs fall under the umbrella of fielddata-related stats and the 3% setting you have is probably low for the aggregations you're doing.

It's also worth noting that the fielddata circuit breaker is not the one tripping here anyway - it's the request circuit breaker and its doing the right thing as you're trying to run a very memory heavy aggregation and the circuit breaker is stopping it based on the defined limits for a request.

Closing as "not a bug" with fielddata.

**Closed by markharwood** 2018-08-10 09:30 UTC
Labels: :Search/Aggregations

**Comment by viewsite** [comment] 2018-08-10 09:41
@markharwood  it's the parent circuit breaker takes effects, not request circuit breaker, is that reasonable？ And the memory used by field data cache has not been released for a long time even after the aggregation is done, which continuously triggers parent circuit breaker

**Comment by markharwood** [comment] 2018-08-10 09:54
>the memory used by field data cache has not been released for a long time

The global ordinals map is a `term -> unique number` map that can be reused across requests so it's going to be heavy.

**Comment by markharwood** [comment] 2018-11-21 09:47
> please do note the docs here 

My bad. Believe the docs not me :)
So it's a `segment term ordinal -> global term ordinal` map.

>in our experience that global ordinals are not light on memory (and also can take a while to load,

We have logic that tries to automatically guess the best execution strategy but when I run selective queries I find setting `execution_hint` to `map` is often a useful guiding hand.

**Comment by synhershko** [comment] 2018-11-21 10:07
> Believe the docs not me :)

You were wrong about the mapping, not about the timings which is what I referred to... Like I said our tests show exactly what you described for high cardinality fields. I'm not aware of any monitoring / APIs which reflect on the size of that thing, and it seems to take us ~15m to load global ordinals and ~5GB on-heap for a single field from single index which is bad.

What's more curious is that some other datatypes seem to load slower (terms agg on ip datatype is ~20% slower than keyword datatype, for some reason).

I'm going to create a discussion on the forums about this soon, as this is rather unexpected and throws me back to pre-2.x days :( , but any help appreciated

> We have logic that tries to automatically guess the best execution strategy but when I run selective queries I find setting execution_hint to map is often a useful guiding hand.

Yup, this was my fallback as well. The following disclaimer in the docs worries me, though:

> Please note that Elasticsearch will ignore this execution hint if it is not applicable and that there is no backward compatibility guarantee on these hints.

**Comment by synhershko** [comment] 2018-11-27 10:49
@markharwood moved the discussion to the forums (https://discuss.elastic.co/t/global-ordinals-performance-and-size-on-heap/158320) , will greatly appreciate your input!
