### ISSUE TITLE
Elasticsearch 5.4.x - extensive CPU (100%) and memory usage for array of range queries

### ISSUE THREAD

**Issue by nenadvicentic** [elastic/elasticsearch#25102] opened 2017-06-07 12:57 UTC
**Elasticsearch version**: 5.4.0 and 5.4.1

**Plugins installed**: []

**JVM version** (`java -version`): jre 1.8.0.131 (x64)

**OS version** (`uname -a` if on a Unix-like system): **any** (tested on Windows 10, Debian)

**Description of the problem including expected versus actual behavior**:
_Actual:_

When having search query which combines multiple "range" queries in "should" query performance of Elasticsearch 5.4.x is ~20 times slower (**100 secs**, compared to **5 secs** on Elasticsearch 5.3.2), CPU usage **100%**, compared to **28%** on 5.3.2, memory usage ~50% higher (**2.3 GB** vs **1.4 GB**).

_Expected:_
roughly similar performance (cpu, memory, time) as 5.3.x

Happens on both cluster configuration and single node.

**Steps to reproduce**:
It's not possible to reproduce the problem without having few million records, but it's around these lines:

 1. Mapping (real type additional data, but property we are querying is only `id` of type `integer`)
```
PUT perf_problem_index
{
  "mappings": {
    "my_type": {
      "properties": {
        "id": {
          "type": "integer"
        }
      }
    }
  }
}
```
 2. Items (**~10 million** items)

```
PUT perf_problem_index/my_type/1
{
  "id" : 1
}

PUT perf_problem_index/my_type/2
{
  "id" : 2
}

PUT perf_problem_index/my_type/3
{
  "id" : 3
}
```

 3. And a query similar to bellow, just with **400+** range entries:

```
POST perf_problem_index/my_type/_search
{
    "query": {
        "bool": {
            "must": [
                {
                    "bool": {
                        "should": [
                            {
                                "term": {
                                    "id": {
                                        "value": 1002
                                    }
                                }
                            },
                            {
                                "range": {
                                    "id": {
                                        "gte": 1004.0,
                                        "lte": 1006.0
                                    }
                                }
                            },
                            {
                                "range": {
                                    "id": {
                                        "gte": 1008.0,
                                        "lte": 1011.0
                                    }
                                }
                            }
                        ]
                    }
                }
            ]
        }
    }
}
```

**Comment by markharwood** [comment] 2017-06-07 13:15
@jpountz Would you have an explanation for this performance regression between 5.3 and 5.4? Looks like a heavy query.

**Comment by markharwood** [comment] 2017-06-07 13:41
[This change in Lucene](https://issues.apache.org/jira/browse/LUCENE-7641) happened between these versions and relates to range queries. It added extra testing logic to range queries to test if it was more efficient to compute documents that do not match the range on single-valued fields when more than half the documents in the index would match.

While this sped up the more common case of a small number of range queries it may not pay off so well in a compound query like yours with very many small ranges (at least that's my working assumption).

**Comment by jpountz** [comment] 2017-06-07 13:59
I think https://github.com/elastic/elasticsearch/pull/23119 is more likely to trigger changes in performance of range queries, even though it is still unclear to me why it would cause a slowdown in that case.

@nenadvicentic Would you mind sharing:
 - your actual query,
 - the [profile](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-profile.html) output
 - the output of the [hot threads](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-hot-threads.html) API **while the query is running** . Taking it a couple times might help.

Thanks!

**Comment by nenadvicentic** [comment] 2017-06-07 14:59
Hi @jpountz ,

I collected performance data.

This is the actual query:
[Elasticsearch-slow-query.txt](https://github.com/elastic/elasticsearch/files/1058390/Elasticsearch-slow-query.txt)

Profiling data from 3 versions of Elasticsearch: **5.3.2, 5.4.0 and 5.4.1**, running the above query (same query, same data). I only removed data from `hits` array. Rest of it is there.

[Elasticsearch-slow-query-example-profiling-info_v5.3.2.txt](https://github.com/elastic/elasticsearch/files/1058394/Elasticsearch-slow-query-example-profiling-info_v5.3.2.txt)
[Elasticsearch-slow-query-example-profiling-info_v5.4.0.txt](https://github.com/elastic/elasticsearch/files/1058395/Elasticsearch-slow-query-example-profiling-info_v5.4.0.txt)
[Elasticsearch-slow-query-example-profiling-info_v5.4.1.txt](https://github.com/elastic/elasticsearch/files/1058396/Elasticsearch-slow-query-example-profiling-info_v5.4.1.txt)

And here are 3 checks for hot_threads. All three are only for version **5.4.1**:

[Elasticsearch-slow-query-hot_threads_take1_v5.4.1.txt](https://github.com/elastic/elasticsearch/files/1058415/Elasticsearch-slow-query-hot_threads_take1_v5.4.1.txt)
[Elasticsearch-slow-query-hot_threads_take2_v5.4.1.txt](https://github.com/elastic/elasticsearch/files/1058417/Elasticsearch-slow-query-hot_threads_take2_v5.4.1.txt)
[Elasticsearch-slow-query-hot_threads_take3_v5.4.1.txt](https://github.com/elastic/elasticsearch/files/1058419/Elasticsearch-slow-query-hot_threads_take3_v5.4.1.txt)

**Comment by jpountz** [comment] 2017-06-07 16:51
I think I understand what is happening. We have heuristics in place in order to estimate how many documents each leaf of the query tree matches so that we can pick the optimal execution order. However this heuristic is not very accurate, it can easily be off by about 1024, and the fact that there are many tiny ranges makes the error add up and Elasticsearch ends up assuming that it is better to iterate over all docs of the `plot` type and check whether they match the `bool` query rather than iterate documents that match the `bool` query and check whether they are in the `plot` type. In addition to being a linear scan, this is slow due to our best efforts to optimize for execution order, so on each document, we sort ranges by cost before trying to match them, which is the bottleneck according to the hot threads.

I quickly checked, and none of the ranges seems to match more than 100 elements, so I think it would be worth rewriting this `bool` query of ranges into a giant `terms` query for all possible values. If you happen to have ranges that are not tiny sometimes, then I would suggest to have a `bool` query that has one `range` clause for each large range (say more than 100 elements as a start, should be tuned afterwards), and to merge all small ranges and `term` queries into a single `terms` clause.

**Comment by nenadvicentic** [comment] 2017-06-08 09:31
I have tried to rewrite the query, but without success.

Initially, I have tried to convert all ranges with less then 100 elements to single `TermsQuery`, but I hit the limit for total query length, or `TermsQuery` length (I had ~7000 values in terms query). In the end, I converted only ranges with less then 10 elements to the single terms query, to keep the size of query text within allowed range.

However, once working, query took around **30 sec** (compared to **2-6 sec** in **v5.3.2**). More, when I tried to profile request, I've got `TimeParsingException`, so I could not proceed. I reported issue here: elastic/elasticsearch-net#2778

Regarding new query execution heuristics, could this be something worth fixing? Parent/child part of query limits amount of children to less then 100 plots. Also, **400 ranges**, each with additional **+1024** estimation, it's still only **409600** items extra of **10 million** items, which is **4%** error in worst possible case. It seems to be too small number to switch to full scan of items.

Is there a way to opt-out from new heuristics logic, in order to keep performance level similar to **v5.3.2** for problematic queries?

**Comment by jpountz** [comment] 2017-06-08 10:24
> Is there a way to opt-out from new heuristics logic

There is no way to work-around it, but on 5.4 you could take advantage of the fact that the [`dis_max` query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-dis-max-query.html) does not yet implement the optimization. So if you replace your `bool` query with a `dis_max`, that should get you back to similar performance as before.

> Also, 400 ranges, each with additional +1024 estimation, it's still only 409600 items extra of 10 million items, which is 4% error

Could you share how many documents match your `bool` query that contains 400 ranges (in the entire index, no type filter), how many documents you have in the `plot` type, and how many documents have a value for the `id1` field (can be done with an `exists` query).

**Comment by nenadvicentic** [comment] 2017-06-09 07:17
Here is information about the data in the Elasticsearch index:

It is single parent-child relationship: parent `registrygroup` having 1 or more `plot` children (1 to 50).

Total parent items: 3224996
Total child items: 10238610 - all child items are of `plot` type, each `plot` has `id1`  (more accurate name would be `groupId`)

Range sub-queries are acting like access list, so in my example fits all items. In average case it will be 10-60% of items.

What I think can be improved: example query I gave fetches single parent item **by id**. Result is 1 parent with 1 child item. So heuristics should figure that querying by `id` has highest selectivity and then `parent-child` relation. This seemed to work fine until version **5.4**.

Bellow is output of the query from **v5.3.2** (with _source data removed):

```
{
   "took": 2453,
   "timed_out": false,
   "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
   },
   "hits": {
      "total": 1,
      "max_score": 3,
      "hits": [
         {
            "_index": "my_index",
            "_type": "registrygroup",
            "_id": "75016e435",
            "_score": 3,
            "_source": {
               ...
            },
            "inner_hits": {
               "plot": {
                  "hits": {
                     "total": 1,
                     "max_score": 1,
                     "hits": [
                        ...
                     ]
                  }
               }
            }
         }
      ]
   }
}
```

**Comment by jpountz** [comment] 2017-06-14 09:15
> It is single parent-child relationship: parent registrygroup having 1 or more plot children (1 to 50).

Do you mean that parents have at most 50 children? This probably means you would get much better performance by modeling your join with a `nested` object. Usually the only reason to prefer parent-child over nested is to avoid the indexing overhead of having to reindex all children when a single one needs to be added/removed/updated. But with at most 50 children I believe this would not be an issue.

> So heuristics should figure that querying by id has highest selectivity and then parent-child relation. This seemed to work fine until version 5.4.

This is not the way it worked before 5.4 but you are right that we should try to do a better job with this kind of queries when filters on the parent are more selective than the join. The one thing that makes it tricky is that Lucene's query execution model requires that doc ids are visited in order, yet there is no relationship between the doc IDs of children documents and their parent, they can even be in different segments. The good news if you manage to migrate to nested docs rather than parent/child is that `nested` maintain order, ie. if `parentDocId1 < parentDocId2` then every child of `parentDocId1` has a doc ID that is less than every child of `parentDocId2`, which allows us to make much better decisions about how to run the query.

**Comment by nenadvicentic** [comment] 2017-06-26 13:33
Problem is, `child` objects are actually pins on the map and in map cases they are completely independent from parent items. If I would recreate index turning child objects into nested objects, any child matching my x-y-z tile on the map would return complete parent item with all children, regardless if children belong to x-y-z or not. Same goes for the `id` ranges I'm filtering for. One match would return everything. Additionally, this approach would require making projections of nested items.

I think looking at object modeling just distracts from the core problem here. Same query dropping from 5 seconds to 100 seconds between 2 minor versions of Elasticsearch should be clear sign that there is an issue to look for.

**Comment by jpountz** [comment] 2017-07-04 08:31
I am looking into that issue, however I disagree that object modeling is a distraction. Regardless of that issue, if you care about search performance, then you should not use parent-child relations as this is our only query that needs to perform linear scans.

**Comment by nenadvicentic** [comment] 2017-07-05 07:32
@jpountz I attached additional test-query and it's profiling results in 5.3.2 and 5.4.2. Maybe this gives additional insight where the problem might be.

If I run my child range-query without parent part (it's attached at the bottom) over all `plot` objects it finishes in **2.03 secs on 5.3.2** and in **4.1 secs on 5.4.2**. This range-query is basically child query from my original example, but extracted and run separately. This is **2 secs slowdown** and for me it fits the with explanation that range query implementation is now different.

However, this 2 secs slowdown does not explain 20x performance drop on original parent-child query (**5 secs to 100 secs**). That is the reason why I think there is a bug. My blind guess is that range-query in 5.4.2 is unnecessarily re-run multiply times, instead of once.


[elasticsearch-my-request.txt](https://github.com/elastic/elasticsearch/files/1123805/elasticsearch-my-request.txt)
[elasticsearch-response-profile-v5.3.2.txt](https://github.com/elastic/elasticsearch/files/1123807/elasticsearch-response-profile-v5.3.2.txt)
[elasticsearch-response-profile-v5.4.2.txt](https://github.com/elastic/elasticsearch/files/1123808/elasticsearch-response-profile-v5.4.2.txt)

**Comment by jpountz** [comment] 2017-08-02 10:03
The situation should get better when/if https://issues.apache.org/jira/browse/LUCENE-7897 gets merged.

**Comment by jpountz** [comment] 2017-08-17 08:22
LUCENE-7897 has been merged. Closing.

**Closed by jpountz** 2017-08-17 08:22 UTC
Labels: :Benchmark, :Search
