### ISSUE TITLE
Defining a template for geo_points messes up the full_name of other fields in the mapping

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#11055] opened 2015-05-08 11:42 UTC
For a template like this one

```
PUT _template/test 
{
  "template": "test-*",
  "mappings": {
    "document": {
      "dynamic_templates": [
        {
          "geoFields": {
            "match": "geo*",
            "mapping": {
              "type": "geo_point"
            }
          }
        }
      ]
    }
  }
}
```

Using this document

```
PUT test-1/document/1
{
  "geo":[
    {
      "lon": 12,
      "lat": 34
    },
    {
      "lon": 13,
      "lat": 33
    }],
  "foo": "foo1"
}
```

Will generate a weird `full_name` for field `foo` (`GET test-1/document/_mapping/field/foo,geo`):

```
{
   "test-1": {
      "mappings": {
         "document": {
            "geo": {
               "full_name": "geo",
               "mapping": {
                  "geo": {
                     "type": "geo_point"
                  }
               }
            },
            "foo": {
               "full_name": "geo.foo",
               "mapping": {
                  "foo": {
                     "type": "string"
                  }
               }
            }
         }
      }
   }
}
```

The same **doesn't** happen when the document used to create the index is not using an array of `geo_point`s:

```
PUT test-1/document/1
{
  "geo": {
    "lon": 12,
    "lat": 34
  },
  "foo": "foo1"
}
```

the resulting mapping being:

```
{
   "test-1": {
      "mappings": {
         "document": {
            "geo": {
               "full_name": "geo",
               "mapping": {
                  "geo": {
                     "type": "geo_point"
                  }
               }
            },
            "foo": {
               "full_name": "foo",
               "mapping": {
                  "foo": {
                     "type": "string"
                  }
               }
            }
         }
      }
   }
}
```

**Comment by astefan** [comment] 2015-05-08 11:42
Tested with ES 1.5.2 and 1.4.4.

**Comment by rjernst** [comment] 2015-05-15 00:27
I was able to reproduce this, but only on 1.x.  I believe it was fixed by one of the many mapping refactorings there. I'm going to close this because I don't think it is worth the effort to track down which mapping refactoring fixed the issue and try to backport (as these refactorings have been complicated and rely on each other).

**Closed by rjernst** 2015-05-15 00:27 UTC
Labels: :Mapping, adoptme, bug
