### ISSUE TITLE
IndexShardIT#testStressMaybeFlushOrRollTranslogGeneration occasionally fails with an assertion error.

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#31629] opened 2018-06-27 20:14 UTC
In a `6.3` build, `IndexShardIT#testStressMaybeFlushOrRollTranslogGeneration` failed with an assertion error around the total number of flushes. This looks similar to #25773, which was already addressed, but is likely different because of the details of the assertion failure: this build failed comparing 1 to 2 flushes, while the previous failure compared 1 with a very large number like 775331. I unfortunately wasn't able to reproduce this locally.

---

Link to the build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.3+multijob-unix-compatibility/os=amazon/149/console

Command to reproduce: 
```
./gradlew :server:integTest \
  -Dtests.seed=32E55CC3C4A38C89 \
  -Dtests.class=org.elasticsearch.index.shard.IndexShardIT \
  -Dtests.method="testStressMaybeFlushOrRollTranslogGeneration" \
  -Dtests.security.manager=true \
  -Dtests.locale=he \
  -Dtests.timezone=Pacific/Johnston
```

Relevant excerpt from the logs:
```
FAILURE 0.15s J3 | IndexShardIT.testStressMaybeFlushOrRollTranslogGeneration <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <1L>
   >      but: was <2L>
   > 	at __randomizedtesting.SeedInfo.seed([32E55CC3C4A38C89:DFE968D623B47EAF]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.index.shard.IndexShardIT.lambda$testStressMaybeFlushOrRollTranslogGeneration$6(IndexShardIT.java:448)
   > 	at org.elasticsearch.index.shard.IndexShardIT.testStressMaybeFlushOrRollTranslogGeneration(IndexShardIT.java:463)
   > 	at java.lang.Thread.run(Thread.java:748)
```

Full log: [index_shard_log.txt](https://github.com/elastic/elasticsearch/files/2142761/index_shard_log.txt)

**Comment by bleskes** [comment] 2018-07-06 09:32
@dnhatn any news on this one?

**Comment by dnhatn** [comment] 2018-07-10 22:45
I looked at this. However, we have no clue here; I enabled debug log for the test.

**Comment by hub-cap** [comment] 2018-07-18 15:53
Another test failure, hopefully with more logging this time!

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.3+multijob-unix-compatibility/os=amazon/192/console

**Comment by DaveCTurner** [comment] 2018-08-06 07:11
Unfortunately not, the log levels were only increased in 6.4-and-later.

**Comment by dnhatn** [comment] 2018-09-13 15:46
Discussed this with the team, we prefer to reduce the logging level of the test then close it since this test has not failed for a month.

**Comment by dnhatn** [comment] 2019-02-13 23:46
Failed again https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/8188/consoleText. I am able to reproduce it now.

**Comment by droberts195** [comment] 2019-02-14 13:10
This failed again with the same error in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.6+intake/221/console

```
12:39:54 FAILURE 10.3s J1 | IndexShardIT.testStressMaybeFlushOrRollTranslogGeneration <<< FAILURES!
12:39:54    > Throwable #1: java.lang.AssertionError: flush stats: total=[0 vs 2], periodic=[0 vs 2]
12:39:54    > Expected: <1L>
12:39:54    >      but: was <2L>
12:39:54    > 	at __randomizedtesting.SeedInfo.seed([BF7D8085A35D96E6:5271B490444A64C0]:0)
12:39:54    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
12:39:54    > 	at org.elasticsearch.index.shard.IndexShardIT.lambda$testStressMaybeFlushOrRollTranslogGeneration$6(IndexShardIT.java:467)
12:39:54    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:848)
12:39:54    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:822)
12:39:54    > 	at org.elasticsearch.index.shard.IndexShardIT.testStressMaybeFlushOrRollTranslogGeneration(IndexShardIT.java:477)
12:39:54    > 	at java.lang.Thread.run(Thread.java:748)
```

The repro command was:

```
./gradlew :server:integTest \
  -Dtests.seed=BF7D8085A35D96E6 \
  -Dtests.class=org.elasticsearch.index.shard.IndexShardIT \
  -Dtests.security.manager=true \
  -Dtests.locale=en-US \
  -Dtests.timezone=Etc/UTC \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

This didn't reproduce locally for me.

**Closed** 2019-02-15 17:48 UTC
Labels: :Distributed/Engine, >test-failure
