### ISSUE TITLE
Plugins Show in Container but not outside container

### ISSUE THREAD

**Issue by SarpongAbasimi** [elastic/elasticsearch#89679] opened 2022-08-28 11:30 UTC
### Elasticsearch Version

7.9.3

### Installed Plugins

repository-s3 7.9.3

### Java Version

_bundled_

### OS Version

Darwin

### Problem Description

I am trying to create a snapshot of my elasticsearch cluster and store it in s3. The problem is that when I install the `repository-s3 7.9.3` inside the container and make a curl request inside of the container

`curl -XGET 'http://localhost:9200/_cat/plugins?pretty'` I see the plugin

But when I exit outside of the container and make the same curl request, I do not see the plugin

<img width="1787" alt="Screenshot 2022-08-28 at 12 15 57" src="https://user-images.githubusercontent.com/37377831/187071589-6d5fd4a7-0f43-4d37-90cd-64a7d82edbe3.png">

### Steps to Reproduce

Create a `docker.compose.yml` file

```docker.compose
version: "3.9"

services:
  all_healthy:
    image: alpine

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    # network_mode: bridge
    environment:
      - cluster.name=elasticsearch_intenthq
      - discovery.type=single-node
      - network.publish_host=_local_
    ports:
      - 9200:9200
    deploy:
      resources:
        limits:
          memory: 1024M
    healthcheck:
      test: [ "CMD-SHELL", "curl -sf --connect-timeout 1 localhost:9200" ]
      interval: 1s
      timeout: 1s
      retries: 60

  localstack:
    image: localstack/localstack
    # network_mode: bridge
    ports:
      - 4566:4566
      - 4571:4571
    environment:
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=xyz
      - AWS_SECRET_ACCESS_KEY=aaa
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

```

- Then  `docker compose up`
- Exec into the container then run `bin/elasticsearch-plugin install --batch repository-s3`
- Once done, run `docker restart <containerId>`
- Exec into the container again and run this `curl -XGET 'http://localhost:9200/_cat/plugins?pretty'` 
- You will see the plugin `repository-s3`
- Then get outside of the container then make the same request  ``curl -XGET 'http://localhost:9200/_cat/plugins?pretty'` 
- You won't see the plugin

**Comment by SarpongAbasimi** [comment] 2022-08-30 16:13
@ncdc @AndrewO

**Comment by SarpongAbasimi** [comment] 2022-08-30 16:18
@idegtiarenko please any input into this?

**Comment by SarpongAbasimi** [comment] 2022-08-30 16:19
Basically the nodes in the container have the plugin but outside the container, the nodes to not have the plugin.
I am not sure if this is a bug or not for Elasticsearch

**Comment by DJRickyB** [comment] 2022-08-31 17:17
Hello! It's not clear to me how an Elasticsearch bug could cause this, so I'm going to close the issue.

However, you had me curious so I followed your reproduction, and was not able to reproduce:
```
<all the setup stuff>
rick.boyd@Ricks-MBP ~ % docker restart es-issue_elasticsearch_1
es-issue_elasticsearch_1
rick.boyd@Ricks-MBP ~ % docker exec -it es-issue_elasticsearch_1 bash
[root@a367f1d868b1 elasticsearch]# curl -X GET localhost:9200/_cat/plugins
a367f1d868b1 repository-s3 7.9.3
[root@a367f1d868b1 elasticsearch]# exit
exit
rick.boyd@Ricks-MBP ~ % curl -X GET localhost:9200/_cat/plugins
a367f1d868b1 repository-s3 7.9.3
```

(`Ricks-MBP` being my workstation host). 

This leads me to believe that you have an instance running that is bound to `localhost:9200` (on your host machine) that is getting conflated with your docker container which is bound to `0.0.0.0:9200` on your host machine. If I do that, then indeed I get

```
rick.boyd@Ricks-MBP ~ % curl -X GET localhost:9200/_cat
/plugins
rick.boyd@Ricks-MBP ~ %
```

Hopefully that hint is enough to push you forward. You might try binding to a different port on your host to separate instances. If you need any other product help, please ask over in https://discuss.elastic.co

**Closed by DJRickyB** 2022-08-31 17:17 UTC
Labels: >bug, needs:triage
