### ISSUE TITLE
[painless] NullPointerExceptions when accessing params HashMap members

### ISSUE THREAD

**Issue by jzzfs** [elastic/elasticsearch#35630] opened 2018-11-16 11:13 UTC
**Elasticsearch version**
Version: 6.3.1, Build: default/zip/eb782d0/2018-06-29T21:59:26.107521Z, JVM: 1.8.0_121

**Plugins installed**: []

**JVM version**:
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

**OS version**:
Mac OS Darwin xyz.local 17.6.0 Darwin Kernel Version 17.6.0
root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**:
When accessing `doc` within the map_script of a scripted aggregation, I keep getting a null pointer exception.

**Steps to reproduce**:

Executing

    {
        "init_script":{
            "source":"params._agg['transactions'] = [];"
        },
        "map_script":{
            "source":"Debug.explain(params)"        <----------------
        },
        ...
    }

with no affecting queries or agg filters I get

    {
        ...,
        "painless_class":"java.util.HashMap",
        "to_string":"{doc=org.elasticsearch.search.lookup.LeafDocLookup@133b9d24, _source=org.elasticsearch.search.lookup.SourceLookup@7b812d13, _doc=org.elasticsearch.search.lookup.LeafDocLookup@133b9d24, _fields=org.elasticsearch.search.lookup.LeafFieldsLookup@6149f5f3, _agg={transactions=[]}}",
        "java_class":"java.util.HashMap",
        ...
    }
    
In here, `Debug.explain(params._agg)` is accessible w/o problems, as is `Debug.explain(params.containsKey('doc'))`, which returns

    {
        ...,
        "painless_class":"java.lang.Boolean",
        "to_string":"true",
        "java_class":"java.lang.Boolean",
        ...
    }

If, however, I access 

 - `params.doc`
 - `params['_doc']`
 - `doc`
 - `_doc`
 - or any variant of those
 

I keep getting 

    {
        ...,
        "caused_by":{
            "type":"null_pointer_exception",
            "reason":null,
            "caused_by":{
                "type":"null_pointer_exception",
                "reason":null
            }
        },
        ...
    }

What's happening? And why am I seeing `LeafDocLookup` instances which cannot be accessed and appear not stringified / toString()-ed?

----------

**Kibana stacktrace**:

    {
        "error":{
            "root_cause":[
                {
                    "type":"null_pointer_exception",
                    "reason":null
                }
            ],
            "type":"search_phase_execution_exception",
            "reason":"all shards failed",
            "phase":"query",
            "grouped":true,
            "failed_shards":[
                {
                    "shard":0,
                    "index":"abcdefgh",
                    "node":"C2dBtzqBQOOiH5G5IGQPkQ",
                    "reason":{
                        "type":"null_pointer_exception",
                        "reason":null
                    }
                }
            ],
            "caused_by":{
                "type":"null_pointer_exception",
                "reason":null,
                "caused_by":{
                    "type":"null_pointer_exception",
                    "reason":null
                }
            }
        },
        "status":500
    }

----------

**ES stacktrace**:

```
org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:288) ~[elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:128) ~[elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:249) ~[elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.action.search.InitialSearchPhase.onShardFailure(InitialSearchPhase.java:101) ~[elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.action.search.InitialSearchPhase.access$100(InitialSearchPhase.java:48) ~[elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.action.search.InitialSearchPhase$2.lambda$onFailure$1(InitialSearchPhase.java:222) ~[elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.action.search.InitialSearchPhase.maybeFork(InitialSearchPhase.java:176) [elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.action.search.InitialSearchPhase.access$000(InitialSearchPhase.java:48) [elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.action.search.InitialSearchPhase$2.onFailure(InitialSearchPhase.java:222) [elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:73) [elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:51) [elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:527) [elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1103) [elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1196) [elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1180) [elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:66) [elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.action.search.SearchTransportService$6$1.onFailure(SearchTransportService.java:385) [elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.search.SearchService$2.onFailure(SearchService.java:341) [elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:335) [elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:329) [elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.search.SearchService$3.doRun(SearchService.java:1019) [elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:725) [elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) [elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.3.1.jar:6.3.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: org.elasticsearch.ElasticsearchException$1
	at org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:658) ~[elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:126) ~[elasticsearch-6.3.1.jar:6.3.1]
	... 26 more
Caused by: java.lang.NullPointerException
	at org.elasticsearch.painless.Definition.getTypeInternal(Definition.java:1364) ~[?:?]
	at org.elasticsearch.painless.Definition.getType(Definition.java:447) ~[?:?]
	at org.elasticsearch.painless.Definition.ClassToType(Definition.java:615) ~[?:?]
	at org.elasticsearch.painless.PainlessExplainError.getHeaders(PainlessExplainError.java:57) ~[?:?]
	at org.elasticsearch.painless.PainlessScript$Script.execute(Debug.explain(params['doc']):21) ~[?:?]
	at org.elasticsearch.painless.ScriptImpl.run(ScriptImpl.java:105) ~[?:?]
	at org.elasticsearch.search.aggregations.metrics.scripted.ScriptedMetricAggregator$1.collect(ScriptedMetricAggregator.java:71) ~[elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.search.aggregations.LeafBucketCollector$2.collect(LeafBucketCollector.java:67) ~[elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.search.aggregations.LeafBucketCollector.collect(LeafBucketCollector.java:82) ~[elasticsearch-6.3.1.jar:6.3.1]
	at org.apache.lucene.search.MultiCollector$MultiLeafCollector.collect(MultiCollector.java:174) ~[lucene-core-7.3.1.jar:7.3.1 ae0705edb59eaa567fe13ed3a222fdadc7153680 - caomanhdat - 2018-05-09 09:27:24]
	at org.apache.lucene.search.FilterLeafCollector.collect(FilterLeafCollector.java:43) ~[lucene-core-7.3.1.jar:7.3.1 ae0705edb59eaa567fe13ed3a222fdadc7153680 - caomanhdat - 2018-05-09 09:27:24]
	at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreAll(Weight.java:233) ~[lucene-core-7.3.1.jar:7.3.1 ae0705edb59eaa567fe13ed3a222fdadc7153680 - caomanhdat - 2018-05-09 09:27:24]
	at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:184) ~[lucene-core-7.3.1.jar:7.3.1 ae0705edb59eaa567fe13ed3a222fdadc7153680 - caomanhdat - 2018-05-09 09:27:24]
	at org.apache.lucene.search.ConstantScoreQuery$ConstantBulkScorer.score(ConstantScoreQuery.java:84) ~[lucene-core-7.3.1.jar:7.3.1 ae0705edb59eaa567fe13ed3a222fdadc7153680 - caomanhdat - 2018-05-09 09:27:24]
	at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:39) ~[lucene-core-7.3.1.jar:7.3.1 ae0705edb59eaa567fe13ed3a222fdadc7153680 - caomanhdat - 2018-05-09 09:27:24]
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:660) ~[lucene-core-7.3.1.jar:7.3.1 ae0705edb59eaa567fe13ed3a222fdadc7153680 - caomanhdat - 2018-05-09 09:27:24]
	at org.elasticsearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:191) ~[elasticsearch-6.3.1.jar:6.3.1]
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:462) ~[lucene-core-7.3.1.jar:7.3.1 ae0705edb59eaa567fe13ed3a222fdadc7153680 - caomanhdat - 2018-05-09 09:27:24]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:266) ~[elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:107) ~[elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:324) ~[elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:357) ~[elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:333) ~[elasticsearch-6.3.1.jar:6.3.1]
```

cc @LucaWintergerst

**Comment by rjernst** [comment] 2018-11-19 23:49
Can you please provide the actual script your are using with `doc`? While the error message is confusing, this basically just means you are trying to dereference `null` (where the returned type is `def` in painless). This usually happens when trying to access a field that is not mapped, for example `doc['doesnotexist'].value`.

**Comment by jzzfs** [comment] 2018-11-20 09:41
```
GET dev__oct_2018/_search
{
  "size": 0,
  "query": {
    "bool": {
      "must": [],
      "should": [],
      "must_not": [],
      "filter": []
    }
  },
  "aggs": {
    "the hard way": {
      "scripted_metric": {
        "init_script": {
          "source": "params._agg['commits'] = [];"
        },
        "map_script": {
          "source": "Debug.explain(doc)"
        },
        "combine_script": {
          "source": "return 0.0"
        },
        "reduce_script": {
          "source": "return 0.0"
        }
      }
    }
  }
}
```
returns
```
{
  "error": {
    "root_cause": [
      {
        "type": "null_pointer_exception",
        "reason": null
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "dev__oct_2018",
        "node": "C2dBtzqBQOOiH5G5IGQPkQ",
        "reason": {
          "type": "null_pointer_exception",
          "reason": null
        }
      }
    ],
    "caused_by": {
      "type": "null_pointer_exception",
      "reason": null,
      "caused_by": {
        "type": "null_pointer_exception",
        "reason": null
      }
    }
  },
  "status": 500
}
```

Here's the ES footprint:
```
{
  "name": "C2dBtzq",
  "cluster_name": "elasticsearch",
  "cluster_uuid": "tNRb2YK5Rzi0bm06kF05rQ",
  "version": {
    "number": "6.3.1",
    "build_flavor": "default",
    "build_type": "zip",
    "build_hash": "eb782d0",
    "build_date": "2018-06-29T21:59:26.107521Z",
    "build_snapshot": false,
    "lucene_version": "7.3.1",
    "minimum_wire_compatibility_version": "5.6.0",
    "minimum_index_compatibility_version": "5.0.0"
  },
  "tagline": "You Know, for Search"
}
```

### Note 1
I unfortunately cannot share the mapping b/c of NDA but, in essence, all my other percentile, nested, stats etc aggs are working just fine. This scripted metric agg is the only one causing trouble.

### Note 2
The above issue pertains to localhost and the abovementioned build.
I tried this agg on my live server which has the following footprint:
```
{
  "name": "wQnVrAN",
  "cluster_name": "elasticsearch",
  "cluster_uuid": "cobqE0w3SPu0LVLwv9MhxA",
  "version": {
    "number": "6.4.3",
    "build_flavor": "oss",
    "build_type": "tar",
    "build_hash": "fe40335",
    "build_date": "2018-10-30T23:17:19.084789Z",
    "build_snapshot": false,
    "lucene_version": "7.4.0",
    "minimum_wire_compatibility_version": "5.6.0",
    "minimum_index_compatibility_version": "5.0.0"
  },
  "tagline": "You Know, for Search"
}
```
and the response is
```
{
  "error": {
    "root_cause": [
      {
        "type": "script_exception",
        "reason": "runtime error",
        "painless_class": "org.elasticsearch.index.fielddata.ScriptDocValues.Doubles",
        "to_string": "[112043.0]",
        "java_class": "org.elasticsearch.index.fielddata.ScriptDocValues$Doubles",
        "script_stack": [
          "Debug.explain(doc.id)",
          "                 ^---- HERE"
        ],
        "script": "Debug.explain(doc.id)",
        "lang": "painless"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "dev__oct_2018",
        "node": "wQnVrAN8QwabKDmXd5ADeg",
        "reason": {
          "type": "script_exception",
          "reason": "runtime error",
          "painless_class": "org.elasticsearch.index.fielddata.ScriptDocValues.Doubles",
          "to_string": "[112043.0]",
          "java_class": "org.elasticsearch.index.fielddata.ScriptDocValues$Doubles",
          "script_stack": [
            "Debug.explain(doc.id)",
            "                 ^---- HERE"
          ],
          "script": "Debug.explain(doc.id)",
          "lang": "painless",
          "caused_by": {
            "type": "painless_explain_error",
            "reason": null
          }
        }
      }
    ]
  },
  "status": 500
}
```

which is what I would expect! The thing is, the live data passed through the same sync pipeline as my localhost index. So I suppose the newer, live build takes care of these null pointers.

**Comment by rjernst** [comment] 2018-11-20 17:53
I'm not able to reproduce this. I created an index with a single doc, then ran:

```
GET _search
{
  "size": 0,
  "query": {
    "match_all": {}
  },
  "aggs": {
    "myagg": {
      "scripted_metric": {
        "map_script": {
          "source": "Debug.explain(doc)"
        },
        "combine_script": {
          "source": "return 0.0"
        },
        "reduce_script": {
          "source": "return 0.0"
        }
      }
    }
  }
}
```

And I get the expected explain response:
```
{"error":{"root_cause":[{"type":"script_exception","reason":"runtime error","to_string":"org.elasticsearch.search.lookup.LeafDocLookup@21023a5b","java_class":"org.elasticsearch.search.lookup.LeafDocLookup","script_stack":["Debug.explain(doc)","              ^---- HERE"],"script":"Debug.explain(doc)","lang":"painless"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"index","node":"XzGHrcTcQJytGhRENO2WLw","reason":{"type":"script_exception","reason":"runtime error","to_string":"org.elasticsearch.search.lookup.LeafDocLookup@21023a5b","java_class":"org.elasticsearch.search.lookup.LeafDocLookup","script_stack":["Debug.explain(doc)","              ^---- HERE"],"script":"Debug.explain(doc)","lang":"painless","caused_by":{"type":"painless_explain_error","reason":null}}}]},"status":400}
```

The example you gave that "works" is also not the same as what you first pasted. The latter looks for an `id` field in doc, while the former just tries to explain `doc` (which is what I ran). And this also does not match the title of this issue (which implies the error is when accessing params). Since you can't share your actual data/query, could you please try to provide a minimal recreation? Something like "index these docs, run this query, see failure"

**Comment by jzzfs** [comment] 2018-11-22 11:04
I'm not able to reproduce it with dummy data:

#### PUT script_test_index
---
#### POST script_test_index/record
```
{
  "index": 0,
  "guid": "dc3cbef6-d46d-4ee6-b8ff-0f84343c9593",
  "isActive": false,
  "balance": "$3,032.44",
  "picture": "http://placehold.it/32x32",
  "age": 23,
  "eyeColor": "green",
  "name": "Caroline Wooten",
  "gender": "female",
  "company": "EWAVES",
  "email": "carolinewooten@ewaves.com",
  "phone": "+1 (921) 448-2839",
  "address": "324 Pilling Street, Vaughn, Illinois, 9521",
  "about": """
Ad culpa non eu mollit eiusmod voluptate. Lorem cillum consectetur aliquip pariatur cillum deserunt tempor reprehenderit in irure voluptate. Nostrud enim officia commodo aliquip amet laborum ea excepteur. Nulla do ipsum exercitation irure minim reprehenderit tempor deserunt adipisicing dolore. Est minim consectetur nulla dolor minim sint dolor magna laborum. Aliqua dolore in do nulla laborum voluptate voluptate voluptate consequat.
""",
  "registered": "2015-10-24T01:53:17 -02:00",
  "latitude": -25.320813,
  "longitude": -164.551767,
  "tags": [
    "occaecat",
    "sit",
    "fugiat",
    "nulla",
    "excepteur",
    "consequat",
    "velit"
  ],
  "friends": [
    {
      "id": 0,
      "name": "Noemi Kemp"
    },
    {
      "id": 1,
      "name": "June Hogan"
    },
    {
      "id": 2,
      "name": "Sasha Massey"
    }
  ],
  "greeting": "Hello, Caroline Wooten! You have 3 unread messages.",
  "favoriteFruit": "strawberry"
}
```
---
#### GET script_test_index/_search
```
{
  "size": 0,
  "query": {
    "bool": {
      "must": [],
      "should": [],
      "must_not": [],
      "filter": []
    }
  },
  "aggs": {
    "the hard way": {
      "scripted_metric": {
        "init_script": {
          "source": "params._agg['tmp'] = [];"
        },
        "map_script": {
          "source": "Debug.explain(doc)"
        },
        "combine_script": {
          "source": "return 0.0"
        },
        "reduce_script": {
          "source": "return 0.0"
        }
      }
    }
  }
}
```
---
This time I'm not getting any 500s but there is a shard failure.

#### Response of the last operation
```
{
  "took": 87,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 4,
    "skipped": 0,
    "failed": 1,
    "failures": [
      {
        "shard": 2,
        "index": "script_test_index",
        "node": "C2dBtzqBQOOiH5G5IGQPkQ",
        "reason": {
          "type": "null_pointer_exception",
          "reason": null
        }
      }
    ]
  },
  "hits": {
    "total": 0,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "the hard way": {
      "value": 0
    }
  }
}
```

**Comment by rjernst** [comment] 2018-11-28 00:55
Given that this is not reproducible, I hope you don't mind that I close this issue. If you come up with a reproduction in the future, please don't hesitate to comment here and we can reopen.

**Closed by rjernst** 2018-11-28 00:55 UTC
Labels: :Core/Infra/Scripting, >bug, v6.6.0, v7.0.0

**Comment by qballer** [comment] 2019-01-07 14:48
I'm having a similar issue:  
https://stackoverflow.com/questions/54075711/trying-to-pass-params-to-elasticsearch-getting-null-pointer-exception
if anyone can help me.
