### ISSUE TITLE
Elasticsearch snapshot,want to snapshot a specific index,but snapshot all indices.Is it a bug？

### ISSUE THREAD

**Issue by Judyccb** [elastic/elasticsearch#11557] opened 2015-06-09 15:25 UTC
I use the API as follow,

curl -XPUT XXXX/_snapshot/indexBackup/tranpmindex_v1ccbs-2015-05-09?wait_for_completion=true -d '{"indices":"tranpmindex_v1ccb-2015-05-09","include_global_state":"false"}'

The index of tranpmindex_v1ccb-2015-05-09 is only about 90M. However, after 15minutes the API executed, the directory of indexBackup increase to 250G.There are a lot of other indices under this dir.

Why?is it a bug? the version of ES is 1.4.4

Thanks!

**Comment by imotov** [comment] 2015-06-10 13:17
@Judyccb That's strange. I just tried reproducing it with 1.4.4 and everything seems to work as expected - only one index is copied to the repository. What do you get back as a response to this operation?

**Comment by Judyccb** [comment] 2015-06-10 15:59
After I input the command and clicked enter, there is no output.I waited for just 5 minutes, then got the warn message that the NFS was full.I had to kill the snapshot process.In the ES log,there is only "no disk free,snapshot failed".The log level is INFO.This is our production environment.I tested snapshot in our test environment,there is no problem. But our production environment and test environment is different. Is it possible because of the environment? what circumstances the snapshot did not consider the index name?

**Comment by imotov** [comment] 2015-06-10 16:01
@Judyccb as long as the body of the request is correctly supplied, the list of indices is always considered.

**Comment by Judyccb** [comment] 2015-06-10 16:07
Hi  Motov,
Is there the body any problem as follow?
 curl -XPUT XXXX/_snapshot/indexBackup/tranpmindex_v1ccbs-2015-05-09?wait_for_completion=true -d '{"indices":"tranpmindex_v1ccb-2015-05-09","include_global_state":"false"}'
This index of tranpmindex_v1ccb-2015-05-09 was reindexed by Python

**Comment by imotov** [comment] 2015-06-10 16:11
@Judyccb I don't see any issues with your request. I created and an index with the same name and I wasn't able to reproduce the issue with your command - everything worked fine for me. Do you have any filters or proxy setup between your machine and the elasticsearch server? Is it possible that this proxy somehow cuts off the body or something like this?

**Comment by Judyccb** [comment] 2015-06-10 16:26
Hi Motov,
The machine I executed the command is one node of our ES cluster.Our ES cluster has 43 nodes. We have a team working on this cluster.I am not sure whether there is any filters or proxy on this machine.How to check it? Could you give any suggestion?

**Comment by imotov** [comment] 2015-06-10 17:24
I think the best way would be to ask the team working on this cluster. You can try specifying some bogus parameters in the body to see if they will generate a parse error (the error means the body was indeed sent and parsed by elasticsearch). However, if body will not reach elasticsearch you will end up creating a complete snapshot again.

**Comment by Judyccb** [comment] 2015-06-11 05:19
Hi Motov,

I think the body was indeed sent and parsed by elasticsearch. The es log  is as follow,
[2015-06-09 16:14:39,007][WARN ][snapshots                ] [by10esapap1009_0] [[patrol_v1-2015-01-16][2]] [indexBackup:tranpmindex_v1ccbs-2015-05-09] failed to create snapshot
org.elasticsearch.index.snapshots.IndexShardSnapshotFailedException: [patrol_v1-2015-01-16][2] Failed to perform snapshot (index files)
        at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository$SnapshotContext.snapshot(BlobStoreIndexShardRepository.java:503)
        at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository.snapshot(BlobStoreIndexShardRepository.java:139)
        at org.elasticsearch.index.snapshots.IndexShardSnapshotAndRestoreService.snapshot(IndexShardSnapshotAndRestoreService.java:86)
        at org.elasticsearch.snapshots.SnapshotsService$5.run(SnapshotsService.java:818)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: No space left on device
        at java.io.FileOutputStream.close0(Native Method)
        at java.io.FileOutputStream.close(FileOutputStream.java:393)
        at java.io.FilterOutputStream.close(FilterOutputStream.java:160)
        at org.elasticsearch.common.blobstore.fs.FsBlobContainer$1.close(FsBlobContainer.java:92)
        at java.io.FilterOutputStream.close(FilterOutputStream.java:160)
        at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository$SnapshotContext.snapshotFile(BlobStoreIndexShardRepository.java:560)
        at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository$SnapshotContext.snapshot(BlobStoreIndexShardRepository.java:501)
        ... 6 more
[2015-06-09 16:14:39,007][WARN ][snapshots                ] [by10esapap1009_0] [[patrol_v1-2015-03-01][3]] [indexBackup:tranpmindex_v1ccbs-2015-05-09] failed to create snapshot
org.elasticsearch.index.snapshots.IndexShardSnapshotFailedException: [patrol_v1-2015-03-01][3] Failed to perform snapshot (index files)
        at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository$SnapshotContext.snapshot(BlobStoreIndexShardRepository.java:503)
/patrol-2015-03-29
org.elasticsearch.index.snapshots.IndexShardSnapshotFailedException: [patrol_v1-2015-02-23][3] Failed to perform snapshot (index files)
        at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository$SnapshotContext.snapshot(BlobStoreIndexShardRepository.java:503)
        at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository.snapshot(BlobStoreIndexShardRepository.java:139)
        at org.elasticsearch.index.snapshots.IndexShardSnapshotAndRestoreService.snapshot(IndexShardSnapshotAndRestoreService.java:86)
        at org.elasticsearch.snapshots.SnapshotsService$5.run(SnapshotsService.java:818)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: /home/ap/appmon/esdata/snapshot/indices/patrol_v1-2015-02-23/3/__0 (No such file or directory)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
        at org.elasticsearch.common.blobstore.fs.FsBlobContainer.createOutput(FsBlobContainer.java:85)
        at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository$SnapshotContext.snapshotFile(BlobStoreIndexShardRepository.java:555)
        at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository$SnapshotContext.snapshot(BlobStoreIndexShardRepository.java:501)
        ... 6 more
[2015-06-09 16:14:44,505][WARN ][snapshots                ] [by10esapap1009_0] [[patrol-2015-03-29][2]] [indexBackup:tranpmindex_v1ccbs-2015-05-09] failed to create snapshot
org.elasticsearch.index.snapshots.IndexShardSnapshotFailedException: [patrol-2015-03-29][2] Failed to perform snapshot (index files)
        at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository$SnapshotContext.snapshot(BlobStoreIndexShardRepository.java:503)
        at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository.snapshot(BlobStoreIndexShardRepository.java:139)
        at org.elasticsearch.index.snapshots.IndexShardSnapshotAndRestoreService.snapshot(IndexShardSnapshotAndRestoreService.java:86)
        at org.elasticsearch.snapshots.SnapshotsService$5.run(SnapshotsService.java:818)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: /home/ap/appmon/esdata/snapshot/indices/patrol-2015-03-29/2/__0 (No such file or directory)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:171)

----------------------------------------------------
every record includes "tranpmindex_v1ccbs-2015-05-09"which is the index I want to snapshot,but include the index I do not want to snapshot too,eg, patrol_v1-2015-01-16.How the index I do not want to snapshot parsed by elasticseach?

**Comment by imotov** [comment] 2015-06-11 15:41
@Judyccb these are just the errors that indicate that you ran out of disk space while trying to snapshot every index in your cluster. This is the default behavior when the elasticsearch server doesn't receive a list of indices specified in the request and therefore creates a snapshot of all available indices.

**Comment by Judyccb** [comment] 2015-06-11 16:13
Hi Motov,
I ran the snapshot command at 15:57. ES snapshot all available indices from 15:57 to 16:09,then no disk and error message as above. ‘tranpmindex_v1ccbs-2015-05-09’ in each error message is the index I want to snapshot,which proved the ES has received the index name from request but not parsed correctly. Do you agree?
----------------------------------------------------------------------------------------------- 
 [2015-06-09 16:14:39,007][WARN ][snapshots ] [by10esapap1009_0] [[patrol_v1-2015-01-16][2]] [indexBackup:tranpmindex_v1ccbs-2015-05-09] failed to create snapshot
-----------------------------------------------------------------------------------------------
curl -XPUT XXXX/_snapshot/indexBackup/tranpmindex_v1ccbs-2015-05-09?wait_for_completion=true -d '{"indices":"tranpmindex_v1ccb-2015-05-09","include_global_state":"false"}'

**Comment by imotov** [comment] 2015-06-11 16:19
The **tranpmindex_v1ccbs-2015-05-09** in each error message is the name of the snapshot: 

curl -XPUT XXXX/_snapshot/indexBackup/**tranpmindex_v1ccbs-2015-05-09**?wait_for_completion=true

which happens to be the same as the name of the index that you intended to snapshot in your case.

**Comment by Judyccb** [comment] 2015-06-12 05:35
Hi Motov,
I reproduced the problem in our test environment.If I input the command as follow,
curl -XPUT XXXX/_snapshot/indexBackup/tranpmindex_v1ccbs-2015-05-09wait_for_completion=true
- d '{"indices":"tranpmindex_v1ccb-2015-05-09","include_global_state":"false"}'
In SecureCRT, when "- d '{"indices":"tranpmindex_v1ccb-2015-05-09","include_global_state":"false"}'"  appears on the second line, then all indices will be snapshot.if "-d"  is on the same line of "curl -XPUT XXXX/_snapshot/indexBackup/tranpmindex_v1ccbs-2015-05-09wait_for_completion=true",the result will be OK.
I  pasted all the command to the ultraedit,there is no special charactor.Besides that, I use the history|grep snapshot command,the result appeared complete command.
It's so strange! And I execute other OS command like this ,it's OK. I am not sure whether it's the problem about Restful API. And I think it's a high risk to user because  the snapshot command snapshots all indices without special tag or hint. It's not enough to distinguish snapshot all or a just by '-dXXX '.

**Comment by imotov** [comment] 2015-06-12 15:56
@Judyccb I think the main use case is making a backup of the entire cluster with all indices at the same time. We are trying to make this use case as simple as possible hence the default behavior. This is also consistent with other APIs in elasticsearch - for example if you don't specify any search request, it will perform search of all indices.

**Comment by Judyccb** [comment] 2015-06-12 16:20
Hi Motov,
I tested the command using SecureCRT and XShell, the problem appeared all.I doubt the CURL command a little.What do you think? How to avoid this?
Besides that, I open a new issue about restore,#11633,expected your response.
Thanks!!

**Comment by imotov** [comment] 2015-06-12 16:28
@Judyccb we trying to use github for bug reports and enhancement requests. I think a much better place to ask for help with using the curl command would be our discussion forum https://discuss.elastic.co/. Since what you are describing doesn't seem to be an elasticsearch bug, I am going to close this issue. Let's continue on our discussion forum.

**Closed by imotov** 2015-06-12 16:28 UTC
Labels: feedback_needed
