### ISSUE TITLE
Highlighter tags extraneous terms from an array when used with match_phrase query

### ISSUE THREAD

**Issue by daniellandau** [elastic/elasticsearch#18035] opened 2016-04-28 10:12 UTC
**Elasticsearch version**:
2.3.1

**Description of the problem including expected versus actual behavior**:
This is similar to https://github.com/elastic/elasticsearch/issues/15291 but still happens with version 2.3.1 on slightly different circumstances. In the previous issue the field was a string, now it's an array.

```
POST /test_index
{
   "settings": {
      "number_of_shards": 1,
      "number_of_replicas": 0
   },
       "mappings" : {
        "file" : { }
        }
    }
}

POST /test_index/file
{
   "texts": [
      "quick brown fox here.",
      "just a fox"
   ]
}

POST /test_index/file/_search
{
   "query": {
      "match_phrase": {
         "text": "quick brown fox"
      }
   },
   "highlight": {
      "fields": {
         "text": {
            "number_of_fragments": 0
         }
      }
   }
}
```

I expect to get a single highlighted fragment from the first string in the array, but instead I get

```
   "hits" : [ {                                                                                 
     "_index" : "test_index",                                                                   
     "_type" : "file",                                                                          
     "_id" : "AVRcVPVIk4eDYtUZXTb8",                                                            
     "_score" : 0.34520942,                                                                     
     "_source" : {                                                                              
       "texts" : [ "quick brown fox here.", "just a fox" ]                                      
     },                                                                                         
     "highlight" : {                                                                            
       "texts" : [ "<em>quick</em> <em>brown</em> <em>fox</em> here.", "just a <em>fox</em>" ]  
     }                                                                                          
   } ]                                                                                          
```

The separate fox is also highlighted even though it doesn't actually match.

**Comment by clintongormley** [comment] 2016-04-29 09:00
Duplicate of https://github.com/elastic/elasticsearch/issues/17848

**Closed by clintongormley** 2016-04-29 09:00 UTC

**Comment by ashitpupu** [comment] 2017-03-17 16:40
@clintongormley I am seeing the same issue in ES 2.3.3. How to fix this issue ???
