### ISSUE TITLE
docker.elastic.co authentication required when pulling elastic search

### ISSUE THREAD

**Issue by lpd-gogo** [elastic/elasticsearch#68434] opened 2021-02-03 10:30 UTC
**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

01:09:29 bb378fdbe6ca: Retrying in 3 seconds
01:09:29 bb378fdbe6ca: Retrying in 2 seconds
01:09:29 bb378fdbe6ca: Retrying in 1 second
01:09:41 bb378fdbe6ca: Retrying in 15 seconds
01:09:42 bb378fdbe6ca: Retrying in 14 seconds
01:09:43 bb378fdbe6ca: Retrying in 13 seconds
01:09:43 bb378fdbe6ca: Retrying in 12 seconds
01:09:45 bb378fdbe6ca: Retrying in 11 seconds
01:09:46 bb378fdbe6ca: Retrying in 10 seconds
01:09:47 bb378fdbe6ca: Retrying in 9 seconds
01:09:47 bb378fdbe6ca: Retrying in 8 seconds
01:09:48 bb378fdbe6ca: Retrying in 7 seconds
01:09:50 bb378fdbe6ca: Retrying in 6 seconds
01:09:51 bb378fdbe6ca: Retrying in 5 seconds
01:09:51 bb378fdbe6ca: Retrying in 4 seconds
01:09:52 bb378fdbe6ca: Retrying in 3 seconds
01:09:54 bb378fdbe6ca: Retrying in 2 seconds
01:09:55 bb378fdbe6ca: Retrying in 1 second
01:10:00 bb378fdbe6ca: Verifying Checksum
01:10:00 bb378fdbe6ca: Download complete
01:10:00 docker: unauthorized: authentication required.
01:10:00 See 'docker run --help'.
[Pipeline] sh
01:10:03 + docker inspect -f {{.State.Running}} b03da92744ff6b44741ecfe793ab09ac67f043937f154763b422827439358b3d

**Comment by tillepille** [comment] 2021-02-04 09:23
@lpd-gogo  
Which image did you try to pull?  
Which command did you use to pull?

**Comment by lpd-gogo** [comment] 2021-02-04 10:51
Tried pulling elasticsearch 2.3.4

**Comment by tillepille** [comment] 2021-02-04 10:57
On [Elastic Docker Registry](https://www.docker.elastic.co/r/elasticsearch?limit=50&offset=250&show_snapshots=false) there are only images from `5.0.0` and above, from dockerhub I could pull the image w/o problems.

Dockerhub

```shell
$ docker pull elasticsearch:2.3.4
2.3.4: Pulling from library/elasticsearch
Digest: sha256:7a09f0b9204b0e331eb7031bf30e12c8138c53c61938d59bb07b9a1c6de93483
Status: Image is up to date for elasticsearch:2.3.4
docker.io/library/elasticsearch:2.3.4
```

Elastic Registry
```shell
$ docker pull docker.elastic.co/elasticsearch/elasticsearch:2.3.4
Error response from daemon: manifest for docker.elastic.co/elasticsearch/elasticsearch:2.3.4 not found: manifest unknown: manifest unknown
```

**Comment by DaveCTurner** [comment] 2021-02-04 13:50
As this issue pertains to a version of Elasticsearch that is long past [end-of-life](https://www.elastic.co/support/eol) we wouldn't consider it a bug. You may be able to get further assistance on the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

If you can reproduce this with a supported version, and can demonstrate that the problem is not related to your environment, then we can re-open this to investigate further.

**Closed by DaveCTurner** 2021-02-04 13:50 UTC
Labels: >bug, needs:triage
