### ISSUE TITLE
Contrary to the javadoc, cluster health check fails with null indices

### ISSUE THREAD

**Issue by wilkinsona** [elastic/elasticsearch#10574] opened 2015-04-13 15:34 UTC
In 1.4.4, the javadoc for `Requests.clusterHealthRequest` states that the `indices` parameter can "use `null` or `_all` to execute against all indices. However, passing `null` causes the health request to throw an exception that's caused by an NPE:

```
java.lang.NullPointerException
	at org.elasticsearch.action.admin.cluster.health.TransportClusterHealthAction.masterOperation(TransportClusterHealthAction.java:133)
	at org.elasticsearch.action.admin.cluster.health.TransportClusterHealthAction.masterOperation(TransportClusterHealthAction.java:46)
	at org.elasticsearch.action.support.master.TransportMasterNodeOperationAction$3.run(TransportMasterNodeOperationAction.java:134)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
```

**Comment by clintongormley** [comment] 2015-04-13 15:48
@luca what do we normally do here? Require `_all` or accept null?

**Comment by javanna** [comment] 2015-04-16 08:28
This is a bug, `null` becomes an empty array when the request goes through the wire, but if the request gets executed immediately on the node where it's created it causes NPE. In the context of cluster health empty indices means no indices (only the global cluster health is returned), it is probably appropriate to check for null in TransportClusterHealthAction where the NPE gets thrown.

**Comment by andrestc** [comment] 2015-08-22 20:11
I think I will take a shot on this one. Should we treat null as "_all"?

**Comment by andrestc** [comment] 2015-09-16 23:27
I decided to give this a try but im not able to reproduce this on master.
I added the following test case:

```java
@Test //issue #10574
    public void testLocalHealthWithNullIndicesActLikeAll() {
        createIndex("test");
        ensureGreen();

        for (String node : internalCluster().getNodeNames()) {
            logger.info("--> running cluster local health with null indices");
            ClusterHealthResponse health = client(node).admin().cluster().prepareHealth(null).setLocal(true).setWaitForEvents(Priority.LANGUID).setTimeout("30s").get("10s");
            assertThat(health.getStatus(), equalTo(ClusterHealthStatus.GREEN));
            assertThat(health.isTimedOut(), equalTo(false));
            assertThat(health.getIndices().get("test").getStatus(), equalTo(ClusterHealthStatus.GREEN));
        }
    }
```

And it passes. I belive this bug is fixed in master, because we handle this case in [IndexNameExpressionResolver](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java#L116).

@clintongormley @javanna do we need this fixed in 1.x?
If this is indeed fixed in master, do you want me to PR the test case?

Thanks.

**Comment by clintongormley** [comment] 2015-09-18 15:59
@andrestc this is a minor bug with an easy workaround - i wouldn't fix it for 1.x.  It sounds like it is already fixed in master? If so, then I'd just close this issue.

**Comment by andrestc** [comment] 2015-09-18 16:02
@clintongormley Cool. Yea, It looks fixed.

**Closed** 2015-09-18 17:18 UTC
Labels: :Java API, adoptme, bug, low hanging fruit
