### ISSUE TITLE
[CI] Darwin IntegTestZip 6.8 ClientYaml Timeout

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#51206] opened 2020-01-20 05:28 UTC
https://gradle-enterprise.elastic.co/s/fyxp3hmz7hsio/console-log?anchor=3009&task=:distribution:archives:integ-test-zip:integTestRunner
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.8+multijob-darwin-compatibility/461/console

```
05:02:18 ERROR   0.00s | IntegTestZipClientYamlTestSuiteIT (suite) <<< FAILURES!
05:02:18    > Throwable #1: java.lang.Exception: Suite timeout exceeded (>= 1200000 msec).
05:02:18    > 	at __randomizedtesting.SeedInfo.seed([746D33B9ACBB36BC]:0)
05:02:18 Completed [4/7] in 1208.14s, 275 tests, 2 errors, 16 skipped <<< FAILURES!
05:02:18 
05:02:38 
05:02:38 [ant:junit4] JVM J0: stderr was not empty, see: /private/var/lib/jenkins/workspace/elastic+elasticsearch+6.8+multijob-darwin-compatibility/distribution/archives/integ-test-zip/build/testrun/integTestRunner/temp/junit4-J0-20200119_204030_5071350965856166024916.syserr
05:02:39 
05:02:39 > Task :distribution:archives:integ-test-zip:integTestRunner
05:02:39 Tests with failures:
05:02:39   - org.elasticsearch.test.rest.IntegTestZipClientYamlTestSuiteIT.test {p0=indices.open/20_multiple_indices/All indices}
05:02:39   - org.elasticsearch.test.rest.IntegTestZipClientYamlTestSuiteIT (suite)
05:02:39 
05:02:39 Slow Tests Summary:
05:02:39 1208.14s | org.elasticsearch.test.rest.IntegTestZipClientYamlTestSuiteIT
05:02:39  17.52s | org.elasticsearch.test.rest.CreatedLocationHeaderIT
05:02:39  16.52s | org.elasticsearch.test.rest.NodeRestUsageIT
05:02:39  13.86s | org.elasticsearch.test.rest.WaitForRefreshAndCloseIT
05:02:39   4.85s | org.elasticsearch.test.rest.DefaultShardsIT
```

**Comment by williamrandolph** [comment] 2020-04-02 17:29
There have been three of these in a row on the 6.8 Darwin compatibility job:

Latest one - [Jenkins](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.8+multijob-darwin-compatibility/608/), [Gradle Enterprise](https://gradle-enterprise.elastic.co/s/365v43rmzikkw)

**Comment by mark-vieira** [comment] 2020-04-07 18:02
Not sure what was happening but the last two darwin builds have passed so I'm going to close this for now. We can reopen if these start timing out again.

**Comment by astefan** [comment] 2020-10-01 08:15
This one failed today, and in the last 30 days there was a [total of 6 failures](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'class:%22org.elasticsearch.test.rest.IntegTestZipClientYamlTestSuiteIT%22%20AND%20branch:%226.8%22%20AND%20stacktrace:%22timeout%20was%20reached%22'),sort:!(time,desc))).

Today's failure: 
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.8+multijob-darwin-compatibility/255/console
https://gradle-enterprise.elastic.co/s/c6oksuujd7od4

**Comment by mark-vieira** [comment] 2020-10-01 16:20
I'm closing this is a duplicate of #58286 since it's all the same fundamental issue, which is that Darwin CI worker performance is ridiculously poor.

**Closed by mark-vieira** 2020-10-01 16:20 UTC
Labels: :Core/Infra/Packaging, >test-failure, v6.8.9
