### ISSUE TITLE
Index lifecycle management issue with policies being replaced

### ISSUE THREAD

**Issue by bmcconaghy** [elastic/elasticsearch#35516] opened 2018-11-13 19:24 UTC
I created a policy named 
`default_policy`
and saved it.  I then created a new policy named
`-default_policy`
and saved it and  it _replaced_ `default_policy`,  There seems to be something amiss with how policies are saved and matching them up with existing policies.

**Comment by colings86** [comment] 2018-11-14 09:12
I could not reproduce this bug locally. I tried the following:
```
PUT _ilm/policy/my_lifecycle1
{
  "policy": {
    "phases": {
      "hot": {
        "actions": {
          "rollover": {
            "max_docs": 200
          }
        }
      },
      "delete": {
        "min_age": "2m",
        "actions": {
          "delete": {}
        }
      }
    }
  }
}

PUT _ilm/policy/-my_lifecycle1
{
  "policy": {
    "phases": {
      "hot": {
        "actions": {
          "rollover": {
            "max_docs": 100
          }
        }
      },
      "delete": {
        "min_age": "2m",
        "actions": {
          "delete": {}
        }
      }
    }
  }
}

GET _ilm/policy
```

and the response I got had the two separate policies:
```
{
  "-my_lifecycle1" : {
    "version" : 1,
    "modified_date" : "2018-11-14T09:10:43.990Z",
    "policy" : {
      "phases" : {
        "hot" : {
          "min_age" : "0ms",
          "actions" : {
            "rollover" : {
              "max_docs" : 100
            }
          }
        },
        "delete" : {
          "min_age" : "2m",
          "actions" : {
            "delete" : { }
          }
        }
      }
    }
  },
  "my_lifecycle1" : {
    "version" : 1,
    "modified_date" : "2018-11-14T09:10:41.709Z",
    "policy" : {
      "phases" : {
        "hot" : {
          "min_age" : "0ms",
          "actions" : {
            "rollover" : {
              "max_docs" : 200
            }
          }
        },
        "delete" : {
          "min_age" : "2m",
          "actions" : {
            "delete" : { }
          }
        }
      }
    }
  }
}
```

@bmcconaghy could you share a console recreation script for this as there is presumably something different between what you are doing and what I am doing?

**Comment by gwbrown** [comment] 2018-12-07 17:14
We haven't seen this or been able to reproduce it since, so I'm closing this.

**Closed by gwbrown** 2018-12-07 17:14 UTC
Labels: :Core/Features/ILM, >bug
