### ISSUE TITLE
`search/380_sort_segments_on_timestamp` test from `RcsCcsCommonYamlTestSuiteIT ` fails on `main`

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#94538] opened 2023-03-20 09:32 UTC
### CI Link

https://gradle-enterprise.elastic.co/s/qiwxbw5bm67tg

### Repro line

```
REPRODUCE WITH: ./gradlew ':qa:ccs-common-rest:yamlRestTest' --tests "org.elasticsearch.test.rest.yaml.RcsCcsCommonYamlTestSuiteIT.test {p0=search/380_sort_segments_on_timestamp/Test that index segments are sorted on timestamp field if @timestamp field is defined in mapping}" \   -Dtests.seed=86C57DA037724F15 \   -Dtests.locale=en-CA \   -Dtests.timezone=Asia/Macau \   -Druntime.java=19  
REPRODUCE WITH: ./gradlew ':qa:ccs-common-rest:yamlRestTest' --tests "org.elasticsearch.test.rest.yaml.RcsCcsCommonYamlTestSuiteIT.test {p0=search/380_sort_segments_on_timestamp/Test that index segments are sorted on timestamp field if @timestamp field is defined in mapping}" \   -Dtests.seed=86C57DA037724F15 \   -Dtests.locale=en-CA \   -Dtests.timezone=Asia/Macau \   -Druntime.java=19
```

### Does it reproduce?

Yes

### Applicable branches

main

### Failure excerpt

```
09:22:48 REPRODUCE WITH: ./gradlew ':qa:ccs-common-rest:yamlRestTest' --tests "org.elasticsearch.test.rest.yaml.RcsCcsCommonYamlTestSuiteIT.test {p0=search/380_sort_segments_on_timestamp/Test that index segments are sorted on timestamp field if @timestamp field is defined in mapping}" -Dtests.seed=86C57DA037724F15 -Dtests.locale=en-CA -Dtests.timezone=Asia/Macau -Druntime.java=19
09:22:48 
09:22:48 org.elasticsearch.test.rest.yaml.RcsCcsCommonYamlTestSuiteIT > test {p0=search/380_sort_segments_on_timestamp/Test that index segments are sorted on timestamp field if @timestamp field is defined in mapping} FAILED
09:22:48     java.lang.AssertionError: Failure at [search/380_sort_segments_on_timestamp:46]: Expected a list containing
09:22:48     0: expected "2021-08-02" but was "2021-08-01"
09:22:48         at __randomizedtesting.SeedInfo.seed([86C57DA037724F15:E91427A998E22ED]:0)
09:22:48         at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:547)
09:22:48         at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:499)
09:22:48         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
09:22:48         at java.base/java.lang.reflect.Method.invoke(Method.java:578)
09:22:48         at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
09:22:48         at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
09:22:48         at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
09:22:48         at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
09:22:48         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
09:22:48         at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
09:22:48         at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
09:22:48         at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
09:22:48         at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
09:22:48         at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
09:22:48         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
09:22:48         at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
09:22:48         at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
09:22:48         at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
09:22:48         at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
09:22:48         at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
09:22:48         at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
09:22:48         at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
09:22:48         at org.elasticsearch.test.cluster.local.LocalElasticsearchCluster$1.evaluate(LocalElasticsearchCluster.java:39)
09:22:48         at org.elasticsearch.test.cluster.local.LocalElasticsearchCluster$1.evaluate(LocalElasticsearchCluster.java:39)
09:22:48         at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
09:22:48         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
09:22:48         at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
09:22:48         at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
09:22:48         at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
09:22:48         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
09:22:48         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
09:22:48         at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
09:22:48         at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
09:22:48         at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
09:22:48         at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
09:22:48         at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
09:22:48         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
09:22:48         at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
09:22:48         at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
09:22:48         at java.base/java.lang.Thread.run(Thread.java:1589)
09:22:48 
09:22:48         Caused by:
09:22:48         java.lang.AssertionError: Expected a list containing
09:22:48         0: expected "2021-08-02" but was "2021-08-01"
09:22:48             at org.elasticsearch.test.MapMatcher.assertMap(MapMatcher.java:82)
09:22:48             at org.elasticsearch.test.MapMatcher.assertMap(MapMatcher.java:65)
09:22:48             at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:97)
09:22:48             at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:65)
09:22:48             at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:527)
09:22:48             ... 39 more
09:22:49 
```

**Comment by cbuescher** [comment] 2023-03-20 10:09
Closing as duplicate of https://github.com/elastic/elasticsearch/issues/94357

**Closed by cbuescher** 2023-03-20 10:09 UTC
Labels: :Search/Search, >test-failure, Team:Search
