### ISSUE TITLE
Cardinality on a keyword field inside a composite aggregation doesn't work

### ISSUE THREAD

**Issue by ohadravid** [elastic/elasticsearch#30647] opened 2018-05-16 10:30 UTC
**Elasticsearch version** (`bin/elasticsearch --version`):  6.2.4

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_161

**OS version** (`uname -a` if on a Unix-like system): Linux 9220caee2267 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

When using a `cardinality` aggregation on a `keyword` type field inside a  composite aggregation,
0 is returned instead of the actual cardinality.

**Steps to reproduce**:

1. Using the latest docker `docker.elastic.co/elasticsearch/elasticsearch:6.2.4`, create the following document & mapping.

```python
#/usr/bin/python
es = elasticsearch.Elasticsearch('localhost')

es.indices.put_mapping('sample', {
    'properties': {
        'user_name': {
            'type': 'keyword'   
        }
    }
}, index='sample')

es.index('sample', 'sample', {
    'port': 80,
    'user_name': 'some_user',
    'session_id': 12
})
```

2. Run the query:
```json
GET sample/_search
{
  "query": {
    "match_all": {}
  },
  "aggs": {
    "my_buckets": {
      "composite": {
        "size": 10,
        "sources": [
          {
            "port_agg": {
              "terms": {
                "field": "port"
              }
            }
          }
        ]
      },
      "aggs": {
        "dc_username": {
          "cardinality": {
            "field": "user_name"
          }
        }
      }
    }
  },
  "size": 0
}
```

The result is:
```json
{
  "took": 2,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 1,
    "hits": []
  },
  "aggregations": {
    "my_buckets": {
      "buckets": [
        {
          "key": {
            "port_agg": 80
          },
          "doc_count": 1,
          "dc_username": {
            "value": 0
          }
        }
      ]
    }
  }
}
```

Where `dc_username` is 0, instead of 1.

Using `terms` instead will return the correct result:
```json
GET sample/_search
{
  "query": {
    "match_all": {}
  },
  "aggs": {
    "my_buckets": {
      "terms": {
        "size": 10,
        "field": "port"
      },
      "aggs": {
        "dc_username": {
          "cardinality": {
            "field": "user_name"
          }
        }
      }
    }
  },
  "size": 0
}
```

```json
{
  "took": 23,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "my_buckets": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 0,
      "buckets": [
        {
          "key": 80,
          "doc_count": 1,
          "dc_username": {
            "value": 1
          }
        }
      ]
    }
  }
}
```

**Provide logs (if relevant)**:

**Comment by jimczi** [comment] 2018-05-16 10:39
Thanks for reporting @ohadravid 
This is a duplicate of https://github.com/elastic/elasticsearch/issues/28688 and the fix is already committed for the next minor version (6.3.0).

**Closed by jimczi** 2018-05-16 10:39 UTC
