### ISSUE TITLE
[CI] RejectionActionIT.testSimulatedSearchRejectionLoad fails on CI

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#54208] opened 2020-03-25 16:47 UTC
The test `RejectionActionIT.testSimulatedSearchRejectionLoad` faild today on CI:

```
org.elasticsearch.action.RejectionActionIT > testSimulatedSearchRejectionLoad FAILED
    java.lang.AssertionError: There are still [2] in-flight contexts. The first one's creation site is listed as the cause of this exception.
        at org.elasticsearch.search.MockSearchService.assertNoInFlightContext(MockSearchService.java:52)
        at org.elasticsearch.test.ESTestCase.lambda$ensureAllSearchContextsReleased$7(ESTestCase.java:507)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:892)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:865)
        at org.elasticsearch.test.ESTestCase.ensureAllSearchContextsReleased(ESTestCase.java:507)
        at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2027)
```

It does not reproduce locally using:

```
./gradlew ':server:integTest' --tests "org.elasticsearch.action.RejectionActionIT.testSimulatedSearchRejectionLoad" \
  -Dtests.seed=895157B0CB297B78 \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-BA \
  -Dtests.timezone=US/Indiana-Starke \
  -Dcompiler.java=13
```

Build scan: https://gradle-enterprise.elastic.co/s/cpuizavuiommc

This failure looks different from older one (#26745) and I must admit that I'm not sure what is going on with this test.

**Comment by jimczi** [comment] 2020-09-21 18:38
Last failure was on April in 6.8 so I am going to close the issue since it doesn't seem to reproduce. We'll reopen if that's not the case.

**Closed by jimczi** 2020-09-21 18:38 UTC
Labels: :Search/Search, >test-failure, Team:Search
