### ISSUE TITLE
[CI] Task :distribution:docker:buildDockerImage failing in 7.4

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#46916] opened 2019-09-20 11:41 UTC
Logs: https://gradle-enterprise.elastic.co/s/iopz4epyq3qvm/console-log?task=:distribution:docker:buildDockerImage

Stacktrace:
```
Running transaction
--
Updating   : 2:shadow-utils-4.6-5.el7.x86_64                              1/2[91mError unpacking rpm package 2:shadow-utils-4.6-5.el7.x86_64
[0m
error: unpacking of archive failed on file /usr/bin/newgidmap;5d848de7: cpio: cap_set_file
Verifying  : 2:shadow-utils-4.6-5.el7.x86_64                              1/2[91m2:shadow-utils-4.1.5.1-25.el7_6.1.x86_64 was supposed to be removed but is not!
[0m
Verifying  : 2:shadow-utils-4.1.5.1-25.el7_6.1.x86_64                     2/2
 
Failed:
shadow-utils.x86_64 2:4.1.5.1-25.el7_6.1    shadow-utils.x86_64 2:4.6-5.el7
```

Seems to require `cap_set_file` to install the shadow-utils.

**Comment by jasontedor** [comment] 2019-09-20 17:39
This appears to be a transient issue from, say, a broken download.

**Comment by droberts195** [comment] 2019-10-02 12:35
The original failure was on Debian 8.  The exact same package, `shadow-utils-4.6-5.el7.x86_64`, failed again in a CentOS 7 Docker image on a Debian 8 CI worker in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=debian-8&&immutable/299/console

```
11:54:25 Error unpacking rpm package 2:shadow-utils-4.6-5.el7.x86_64
11:54:25   Updating   : 2:shadow-utils-4.6-5.el7.x86_64                              1/2 
11:54:25 error: unpacking of archive failed on file /usr/bin/newgidmap;5d948f8a: cpio: cap_set_file
```

https://bugzilla.redhat.com/show_bug.cgi?id=1738233 gave me a hint that the problem might be that the kernel of the Debian 8 host does not support the `cap_set_file` syscall that the CentOS 7 Docker image is trying to use.  But that would be quite weird because CentOS 7 uses a 3.10 kernel whereas Debian 8 has a 3.16 kernel, so you would think that the newer host kernel would support all the syscalls that the older container userland wanted to use.

Then I found https://github.com/moby/moby/issues/6980 which sounds like the same problem on a different package.  There is an idea to fix it in https://github.com/docker/hub-feedback/issues/461#issuecomment-318786850.  Maybe that will help in our case.

**Comment by atorok** [comment] 2019-10-03 12:03
Duplicate of #47097

**Closed by atorok** 2019-10-03 12:03 UTC
Labels: :Core/Infra/Packaging, >test-failure
