### ISSUE TITLE
ScriptFieldIT#testNativeScript failure

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#23934] opened 2017-04-06 08:11 UTC
```
REPRODUCE WITH: gradle :core:integTest -Dtests.seed=2BCD6888C069F459 -Dtests.class=org.elasticsearch.script.ScriptFieldIT -Dtests.method="testNativeScript" -Dtests.security.manager=true -Dtests.locale=es-NI -Dtests.timezone=Israel
ERROR   20.6s J0 | ScriptFieldIT.testNativeScript <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <6>
   >      but: was <5>
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.script.ScriptFieldIT.testNativeScript(ScriptFieldIT.java:68)
   > 	at java.lang.Thread.run(Thread.java:745)Throwable #2: java.lang.AssertionError: Request breaker not reset to 0 on node: node_s0
   > Expected: <0L>
   >      but: was <16440L>
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.test.InternalTestCluster$3.run(InternalTestCluster.java:2023)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:715)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:689)
   > 	at org.elasticsearch.test.InternalTestCluster.ensureEstimatedStats(InternalTestCluster.java:2019)
   > 	at org.elasticsearch.test.TestCluster.assertAfterTest(TestCluster.java:92)
   > 	at org.elasticsearch.test.InternalTestCluster.assertAfterTest(InternalTestCluster.java:2042)
   > 	at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:579)
   > 	at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2036)
   > 	at java.lang.Thread.run(Thread.java:745)
   > 	Suppressed: java.lang.AssertionError: Request breaker not reset to 0 on node: node_s0
   > Expected: <0L>
   >      but: was <16440L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.test.InternalTestCluster$3.run(InternalTestCluster.java:2023)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:703)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: Request breaker not reset to 0 on node: node_s0
   > Expected: <0L>
   >      but: was <16440L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.test.InternalTestCluster$3.run(InternalTestCluster.java:2023)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:703)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: Request breaker not reset to 0 on node: node_s0
   > Expected: <0L>
   >      but: was <16440L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.test.InternalTestCluster$3.run(InternalTestCluster.java:2023)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:703)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: Request breaker not reset to 0 on node: node_s0
   > Expected: <0L>
   >      but: was <16440L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.test.InternalTestCluster$3.run(InternalTestCluster.java:2023)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:703)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: Request breaker not reset to 0 on node: node_s0
   > Expected: <0L>
   >      but: was <16440L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.test.InternalTestCluster$3.run(InternalTestCluster.java:2023)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:703)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: Request breaker not reset to 0 on node: node_s0
   > Expected: <0L>
   >      but: was <16440L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.test.InternalTestCluster$3.run(InternalTestCluster.java:2023)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:703)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: Request breaker not reset to 0 on node: node_s0
   > Expected: <0L>
   >      but: was <16440L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.test.InternalTestCluster$3.run(InternalTestCluster.java:2023)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:703)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: Request breaker not reset to 0 on node: node_s0
   > Expected: <0L>
   >      but: was <16440L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.test.InternalTestCluster$3.run(InternalTestCluster.java:2023)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:703)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: Request breaker not reset to 0 on node: node_s0
   > Expected: <0L>
   >      but: was <16440L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.test.InternalTestCluster$3.run(InternalTestCluster.java:2023)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:703)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: Request breaker not reset to 0 on node: node_s0
   > Expected: <0L>
   >      but: was <16440L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.test.InternalTestCluster$3.run(InternalTestCluster.java:2023)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:703)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: Request breaker not reset to 0 on node: node_s0
   > Expected: <0L>
   >      but: was <16440L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.test.InternalTestCluster$3.run(InternalTestCluster.java:2023)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:703)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: Request breaker not reset to 0 on node: node_s0
   > Expected: <0L>
   >      but: was <16440L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.test.InternalTestCluster$3.run(InternalTestCluster.java:2023)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:703)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: Request breaker not reset to 0 on node: node_s0
   > Expected: <0L>
   >      but: was <16440L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.test.InternalTestCluster$3.run(InternalTestCluster.java:2023)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:703)
   > 		... 40 moreThrowable #3: java.lang.RuntimeException: 1 pages have not been released
   > 	at org.elasticsearch.common.util.MockPageCacheRecycler.ensureAllPagesAreReleased(MockPageCacheRecycler.java:52)
   > 	at org.elasticsearch.test.ESTestCase.checkStaticState(ESTestCase.java:388)
   > 	at org.elasticsearch.test.ESTestCase.after(ESTestCase.java:282)
   > 	at java.lang.Thread.run(Thread.java:745)
   > Caused by: java.lang.Throwable
   > 	at org.elasticsearch.common.util.MockPageCacheRecycler.wrap(MockPageCacheRecycler.java:69)
   > 	at org.elasticsearch.common.util.MockPageCacheRecycler.bytePage(MockPageCacheRecycler.java:118)
   > 	at org.elasticsearch.common.util.BigArrays.newByteArray(BigArrays.java:466)
   > 	at org.elasticsearch.common.util.MockBigArrays.newByteArray(MockBigArrays.java:100)
   > 	at org.elasticsearch.common.util.BigArrays.newByteArray(BigArrays.java:479)
   > 	at org.elasticsearch.common.io.stream.BytesStreamOutput.<init>(BytesStreamOutput.java:62)
   > 	at org.elasticsearch.common.io.stream.ReleasableBytesStreamOutput.<init>(ReleasableBytesStreamOutput.java:36)
   > 	at org.elasticsearch.transport.TcpTransport.sendResponse(TcpTransport.java:1116)
   > 	at org.elasticsearch.transport.TcpTransport.sendResponse(TcpTransport.java:1107)
   > 	at org.elasticsearch.transport.TcpTransportChannel.sendResponse(TcpTransportChannel.java:67)
   > 	at org.elasticsearch.transport.TcpTransportChannel.sendResponse(TcpTransportChannel.java:61)
   > 	at org.elasticsearch.transport.DelegatingTransportChannel.sendResponse(DelegatingTransportChannel.java:60)
   > 	at org.elasticsearch.transport.RequestHandlerRegistry$TransportChannelWrapper.sendResponse(RequestHandlerRegistry.java:108)
   > 	at org.elasticsearch.action.search.SearchTransportService$12.messageReceived(SearchTransportService.java:395)
   > 	at org.elasticsearch.action.search.SearchTransportService$12.messageReceived(SearchTransportService.java:391)
   > 	at org.elasticsearch.transport.AssertingTransportInterceptor$1.messageReceived(AssertingTransportInterceptor.java:76)
   > 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66)
   > 	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1482)
   > 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638)
   > 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
   > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
   > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
   > 	... 1 more
```

Failure does not reproduce.

build url: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=fedora/79

**Comment by jdconrad** [comment] 2017-04-11 15:29
@imotov I'm not very familiar with native scripts, is this something you would be comfortable looking at?

**Comment by imotov** [comment] 2017-04-11 15:39
@jdconrad I don't think the problem is with native scripts here (which are trivial in this case). It looks like a request breaker issue and @dakrone is probably the best person to take a look at it.

**Comment by dakrone** [comment] 2017-05-26 18:47
Going to close this as native scripts (and thus ScriptFieldIT) are gone

**Closed by dakrone** 2017-05-26 18:47 UTC
Labels: :Scripting, test
