### ISSUE TITLE
Release analysis plugins to maven

### ISSUE THREAD

**Issue by synhershko** [elastic/elasticsearch#22529] opened 2017-01-10 15:27 UTC
Latest analysis plugin versions on maven are 5.0 alpha (e.g. http://mvnrepository.com/artifact/org.elasticsearch.plugin/analysis-smartcn , http://mvnrepository.com/artifact/org.elasticsearch.plugin/analysis-kuromoji). Since they require installation, essentially they aren't internalized fully, and as such they should be released to maven so users can run integration tests etc by loading them into clusters by maven ref.

**Comment by clintongormley** [comment] 2017-01-10 15:57
Duplicate of https://github.com/elastic/elasticsearch/issues/21615

**Closed by clintongormley** 2017-01-10 15:57 UTC
