### ISSUE TITLE
ES_7.3.0 JDBC driver does not work properly in the JDK 8 version.

### ISSUE THREAD

**Issue by lendo** [elastic/elasticsearch#45316] opened 2019-08-08 06:09 UTC
JDK version: 1.8.0_211
when i used xpack 7.3.0 jdbc driver to access my data in es cluster.
I got a stack error:
`java.lang.IllegalStateException: Unsupported Content-Type: text/plain; charset=UTF-8
	at org.elasticsearch.xpack.sql.client.HttpClient.readFrom(HttpClient.java:161)
	at org.elasticsearch.xpack.sql.client.JreHttpUrlConnection.request(JreHttpUrlConnection.java:155)
	at org.elasticsearch.xpack.sql.client.HttpClient.lambda$get$4(HttpClient.java:131)
	at org.elasticsearch.xpack.sql.client.JreHttpUrlConnection.http(JreHttpUrlConnection.java:65)
	at org.elasticsearch.xpack.sql.client.HttpClient.lambda$get$5(HttpClient.java:130)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.elasticsearch.xpack.sql.client.HttpClient.get(HttpClient.java:129)
	at org.elasticsearch.xpack.sql.client.HttpClient.serverInfo(HttpClient.java:60)
	at org.elasticsearch.xpack.sql.jdbc.JdbcHttpClient.fetchServerInfo(JdbcHttpClient.java:95)
	at org.elasticsearch.xpack.sql.jdbc.JdbcHttpClient.<init>(JdbcHttpClient.java:47)
	at org.elasticsearch.xpack.sql.jdbc.JdbcConnection.<init>(JdbcConnection.java:53)
	at org.elasticsearch.xpack.sql.jdbc.JdbcConnection.<init>(JdbcConnection.java:48)
	at org.elasticsearch.xpack.sql.jdbc.EsDriver.connect(EsDriver.java:76)`

I debug my code and get a snapshot:
<img width="979" alt="1" src="https://user-images.githubusercontent.com/82283/62678968-89ad5c00-b9e5-11e9-8c33-129d4b0953a6.png">
the header "Content-Type" is missing. finally i found a problem in xpack 7.3.0 jdbc driver.

es 7.3.0 jdbc driver use java.net.HttpURLConnection to perform requests，The following two figures show the difference between jdk8 and jdk7 in sun/net/www/protocol/http/HttpURLConnection.java:
jdk8:
<img width="386" alt="7CB86FA6-2522-4770-BBB7-218D777F6FC9" src="https://user-images.githubusercontent.com/82283/62678702-c7f64b80-b9e4-11e9-849d-da1232a9b076.png">
jdk7:
<img width="415" alt="BC6A31A6-5D96-4c9b-84B6-39062867FCDB" src="https://user-images.githubusercontent.com/82283/62678713-cdec2c80-b9e4-11e9-9947-755d33eb1ad0.png">

Propose: use **Apache HttpClient** instead of java.net.HttpURLConnection in org.elasticsearch.xpack.sql.client.JreHttpUrlConnection.java

**Comment by astefan** [comment] 2019-08-09 08:55
@lendo I don't see how you use the driver and I cannot reproduce this behavior. You only provide the conclusion of an investigation to an issue that is not explained or detailed enough.
Can you provide more info about how you actually test this, in what environment, and the full stacktrace?

**Comment by matriv** [comment] 2020-05-19 18:53
Closing this as there hasn't been any feedback for long time.

**Closed by matriv** 2020-05-19 18:53 UTC
Labels: :Query Languages/SQL, Team:QL, feedback_needed
