### ISSUE TITLE
`array_index_out_of_bounds_exception` shard exception in a search query

### ISSUE THREAD

**Issue by arthurdarcet** [elastic/elasticsearch#38170] opened 2019-02-01 10:21 UTC
**Elasticsearch version:**
6.6.0

**Original install method (e.g. download page, yum, from source, etc.):**
Empty cluster, started with `docker run --rm -p9200:9200 docker.elastic.co/elasticsearch/elasticsearch:6.6.0`

**Describe the bug:**

I'm getting an `array_index_out_of_bounds_exception` shard exception when doing some very specific search request with simple_query_string, a term query and highlighting.

The search query is run against an index with a single document, bellow is a script reproducing the issue. I'm running against a completely empty/new single node cluster

```sh
#!/bin/sh

ES="http://127.0.0.1:9200/test-idx"

echo "Drop idx: "
curl -XDELETE "$ES"

echo "\nInsert obj: "
curl \
	-XPUT "$ES/_doc/0?refresh=wait_for" \
	-H'content-type:application/json' \
	-d'{"key1": "word", "key2": "other"}'

echo "\nSearch: "
curl \
	"$ES/_doc/_search?pretty=true" \
	-H'content-type:application/json' \
	-d '{
	"query": {
		"bool": {
			"should": {
				"term": {
				"_id": "rrrrrrrrrrrrrrrrrrrrrrfr"
				}
			},
			"must": {
				"function_score": {
					"query": {
						"simple_query_string": {
							"query": "word*"
						}
					}
				}
			}
		}
	},
	"highlight": {
		"require_field_match": false,
		"fields": {
			"key2": {}
		}
	}
}'
```

Exact error:
```json
"reason" : {
  "type" : "array_index_out_of_bounds_exception",
  "reason" : "Index 18 out of bounds for length 18"
}
```

Here are some of the changes in the query that make it *work*:
 - Switching from `word*` to `word` works
 - `require_field_match: true`
 - `term._id` query that does have the `f` at that position
 - `term._id` with one more or one less `r`

I have not found any logs with a stacktrace for the issue, and I have no idea what I can try next… Is there anything I could do to get a more precise error? (`error_trace=true` does not add anything to the logs or response)
The issue is also present in our production cluster, running 6.3.1

**Comment by jimczi** [comment] 2019-02-01 11:37
This is a duplicate of https://github.com/elastic/elasticsearch/issues/37525. The `_id` field does not use utf-8 encoding internally which breaks the unified highlighter. We'll remove the `_id` field when `required_field_match` is false in order to avoid this issue. I hope you don't mind if I close this issue,  we'll update #37525 when a fix is ready.

**Closed by jimczi** 2019-02-01 11:37 UTC
Labels: :Search/Highlighting, >bug

**Comment by arthurdarcet** [comment] 2019-02-01 12:36
ok. We should be able to remove `require_field_match` so we should be fine.
Thanks!
