### ISSUE TITLE
[CI] JdbcResultSetIT testGettingValidNumbersWithCastingFromUnsignedLong failing

### ISSUE THREAD

**Issue by idegtiarenko** [elastic/elasticsearch#97358] opened 2023-07-04 11:55 UTC
**Build scan:**
https://gradle-enterprise.elastic.co/s/lsw4zncy6twui/tests/:x-pack:plugin:sql:qa:jdbc:single-node:v8.8.3%23bwcTest/org.elasticsearch.xpack.sql.qa.jdbc.single_node.JdbcResultSetIT/testGettingValidNumbersWithCastingFromUnsignedLong

**Reproduction line:**
```
./gradlew ':x-pack:plugin:sql:qa:jdbc:single-node:v8.8.3#bwcTest' -Dtests.class="org.elasticsearch.xpack.sql.qa.jdbc.single_node.JdbcResultSetIT" -Dtests.method="testGettingValidNumbersWithCastingFromUnsignedLong" -Dtests.seed=B9E4EF0CF07C2C7A -Dtests.bwc=true -Dtests.locale=es-VE -Dtests.timezone=America/Lower_Princes -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.sql.qa.jdbc.single_node.JdbcResultSetIT&tests.test=testGettingValidNumbersWithCastingFromUnsignedLong

**Failure excerpt:**
```
org.elasticsearch.client.ResponseException: method [PUT], host [http://127.0.0.1:35161], URI [/test/_doc/2?refresh=true], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"document_parsing_exception","reason":"[1:23] failed to parse field [test_unsigned_long] of type [unsigned_long] in document with id '2'. Preview of field's value: '-1'"}],"type":"document_parsing_exception","reason":"[1:23] failed to parse field [test_unsigned_long] of type [unsigned_long] in document with id '2'. Preview of field's value: '-1'","caused_by":{"type":"illegal_argument_exception","reason":"Value [-1] is out of range for unsigned long."}},"status":400}

  at __randomizedtesting.SeedInfo.seed([B9E4EF0CF07C2C7A:7667C1D31414B1A5]:0)
  at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:347)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:313)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
  at org.elasticsearch.xpack.sql.qa.jdbc.JdbcIntegrationTestCase.index(JdbcIntegrationTestCase.java:115)
  at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.indexTestFieldsDoc(ResultSetTestCase.java:2473)
  at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.testGettingValidNumbersWithCastingFromUnsignedLong(ResultSetTestCase.java:825)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

**Comment by alex-spies** [comment] 2024-09-06 11:57
Duplicate of https://github.com/elastic/elasticsearch/issues/99861.

This doesn't reproduce anymore and was fixed in https://github.com/elastic/elasticsearch/pull/99862.

**Closed by alex-spies** 2024-09-06 11:57 UTC
Labels: >test-failure, :Analytics/SQL, Team:Analytics, low-risk
