### ISSUE TITLE
Monitoring Snapshot Restore As Task

### ISSUE THREAD

**Issue by Alsheh** [elastic/elasticsearch#66072] opened 2020-12-09 02:51 UTC
Currently, restoring a snapshot without waiting for completing just acknowledges the request:

Request:
`POST /_snapshot/my_backup/snapshot_1/_restore?wait_for_completion=false`

Response:
```
{
  "accepted" : true
}
```

Ideally, I'd like to get a task id to monitor the restore request progress as well as seeing any errors that may occur when retrieving the task status via the tasks API `GET _tasks/<task-id>`.

**Comment by DaveCTurner** [comment] 2021-09-13 12:59
Better visibility into restore progress is a good idea, but I think it would be tricky to solve it with the tasks API. The status info that tasks report must be kept in memory on the node that runs the task, but we wouldn't want to centralise the status of ongoing restores like that, and splitting the task up across nodes would be hard to understand. Instead we'd want to have an API that gets the up-to-date status from all the nodes as described in #59233, so I'm closing this as a duplicate of that.

**Closed by DaveCTurner** 2021-09-13 12:59 UTC
Labels: >enhancement, :Distributed/Snapshot/Restore, Team:Distributed
