### ISSUE TITLE
SearchContext to be accessible from ScoreFunctions

### ISSUE THREAD

**Issue by ethteck** [elastic/elasticsearch#26105] opened 2017-08-08 20:54 UTC
I work on an ES plugin in which we would like our ScoreFunction to be able to view the TopDocs returned so far. We used to get at this from the SearchContext, which we can no longer do as of 5.1.1.

Is it possible for SearchContext to be accessible from LeafScoreFunction / ScoreFunction ?

**Comment by dadoonet** [comment] 2017-08-08 20:56
For the record, same thread as https://discuss.elastic.co/t/accessing-topdocs-from-a-leafscorefunction/96336

**Comment by jimczi** [comment] 2017-08-09 10:04
The solution described in the forum should suit your needs so I am going to close this issue. Accessing the score of the query directly through `subQueryScore` is much cleaner than `SearchContext.current` so there is no regression here.

**Closed by jimczi** 2017-08-09 10:04 UTC

**Comment by ethteck** [comment] 2017-08-09 17:36
I'm requesting that this be re-opened due to @rjernst's reply in the discussion linked earlier. The functionality of `subQueryScore` unfortunately does not satisfy what we are looking for.

In essence, we would like some way to get at the `SearchContext` now that the ability to get the "current" `SearchContext` is gone. Other things we prefer to be able to see that we used to get from the `SearchContext`: `numberOfShards()`, `rescore()`, `size()`

I'm not sure if this makes sense from a design standpoint, but would it be possible for the `SearchContext` to be accessible via some other context, such as `QueryShardContext`?

**Comment by jimczi** [comment] 2017-08-10 13:53
IMO the SearchContext is an internal thing that the function score should not be aware of. The fact that it was accessible before was I think not intentional (at least inside the implementation of a custom query).
If your function score depends on other factors (size or rescore) maybe you could simply copy them directly in your custom function score definition ? This would require some additional arguments and parsing on your plugin but it would make your function score more robust to internal changes in es ?

**Comment by ethteck** [comment] 2017-08-10 14:51
>  simply copy them directly in your custom function score definition

Could you expand upon this? If there's any other way I can get at these things (TopDocs, size, rescore), that's really all we're looking to do.

**Comment by jimczi** [comment] 2017-08-10 15:02
I am just saying that you could copy the size and the rescore definition in the function score and parse them in your custom function score. Regarding the TopDocs I don't understand how you could access them during the query since they are filled only at the end.

**Comment by ethteck** [comment] 2017-08-10 15:19
Wouldn't this require users to enter these values twice, both in the query and again in the rescore function?

```
{
"explain": true,
"query": {
    "match": {
        "primary_name": "Abdallah Ghmori"
    }
},
"rescore": {
    "window_size": 200,
    "query": {
        "rescore_query": {
            "function_score": {
                "name_score": {
                    "window_size": 200,
                    "size": 100,
                    "field": "primary_name",
                    "query_name": "Abdallah Ghmori"
                }
            }
        },
        "query_weight": 0.0
    }
},
"size": 100
}
```

Or are you saying there's some way to access these already-parsed values from the ScoreFunctionParser?

The TopDocs have always been present for us in the past at rescore time, via the SearchContext. Haven't they already all been collected in a prior phase?

**Comment by jimczi** [comment] 2017-08-10 15:28
> Wouldn't this require users to enter these values twice, both in the query and again in the rescore function?

Yes the idea is to copy these values in the function score definition like in your example.

> The TopDocs have always been present for us in the past at rescore time, via the SearchContext. Haven't they already all been collected in a prior phase?

I didn't understand that you were on the rescore side. So yep they are available in the context when doing the rescore but it seems weird to allow a rescore query to access them all at once since they will be pass to your function_score one by one for rescoring. What kind of informations are you extracting from the top_docs ?

**Comment by ethteck** [comment] 2017-08-10 16:19
Okay. While this is definitely a possibility, I'd say it's pretty inconvenient for the user and relies on them to remember to put the same things in multiple places in the query.

We look at the TopDocs.scoreDocs to get the original query scores, and we have a function that compute a minimum score threshold based off of these scores. We use this threshold to decide whether we should perform our expensive rescore on a doc or not. Our function needs to be able to iterate over these scores, which we used to get from `SearchContext.current().queryResult().topDocs().scoreDocs`.

**Comment by ethteck** [comment] 2017-08-10 16:37
> seems weird to allow a rescore query to access them all at once since they will be pass to your function_score one by one for rescoring

Also, unfortunately, this isn't quite working either. I assume you're talking about the `subQueryScore` field in `LeafScoreFunction.score`. I [discussed this](https://discuss.elastic.co/t/accessing-topdocs-from-a-leafscorefunction/96336/4?u=ethanroseman) with @rjernst and he deemed that it's not giving us the score we actually want.

**Comment by jimczi** [comment] 2017-08-10 17:53
Sorry I missed the discussion in the forum. Yes the `subQueryScore` is the score of the rescore query so in your case a `match_all` query.  I still don't think that accessing the information you want through the SearchContext is not the good solution. I am sure we can find something less hacky so let's continue the discussion here https://discuss.elastic.co/t/accessing-topdocs-from-a-leafscorefunction/96336 (thanks for opening this).
