### ISSUE TITLE
Transport client is broken for released versions from 5.0.0-alpha5 RC1

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#19625] opened 2016-07-27 14:45 UTC
The transport client has now been moved into its own project (using project here to distinguish a gradle module/project from and Elasticsearch plugin module) `:client:transport`. This module has the following compile dependencies:

```
<dependency>
      <groupId>org.elasticsearch.plugin</groupId>
      <artifactId>reindex</artifactId>
      <version>5.0.0-alpha5</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.elasticsearch.plugin</groupId>
      <artifactId>lang-mustache</artifactId>
      <version>5.0.0-alpha5</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.elasticsearch.plugin</groupId>
      <artifactId>transport-netty4</artifactId>
      <version>5.0.0-alpha5</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.elasticsearch</groupId>
      <artifactId>elasticsearch</artifactId>
      <version>5.0.0-alpha5</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.elasticsearch.plugin</groupId>
      <artifactId>transport-netty3</artifactId>
      <version>5.0.0-alpha5</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.elasticsearch.plugin</groupId>
      <artifactId>percolator</artifactId>
      <version>5.0.0-alpha5</version>
      <scope>compile</scope>
    </dependency>
```

The problem is that the `org.elasticsearch.plugin` artifacts don't seem to be published to the maven repository as part of the release build and therefore a project that tries to import the transport client using:

```
    <dependency>
        <groupId>org.elasticsearch.client</groupId>
        <artifactId>transport</artifactId>
        <version>5.0.0-alpha5</version>
    </dependency>
```

cannot resolve the dependencies rendering the transport client broken. The above dependencies are required dues to https://github.com/elastic/elasticsearch/blob/master/client/transport/src/main/java/org/elasticsearch/transport/client/PreBuiltTransportClient.java#L52-59.

In order to get the transport client to be usable for 5.0.0-alpha5 onwards it looks like we need to start publishing the artifacts for the modules in the maven repository.

**Comment by dadoonet** [comment] 2016-07-27 14:49
Similar to #18131. I agree we should publish at the very least jars that can be used by the transport client.
Won't be an issue anymore I guess once we will definitely switch to REST Client only.

**Comment by nik9000** [comment] 2016-08-01 11:38
I believe this is closed by https://github.com/elastic/elasticsearch/pull/19667.

**Comment by costin** [comment] 2016-08-01 14:08
The issue still persists and currently I can't test the upcoming ES 5.0.0-alpha5.

First off, the snapshot in the Maven OSS repository is incomplete as neither netty3 or netty4 artifacts are present:
https://oss.sonatype.org/content/repositories/snapshots/org/elasticsearch/plugin/

Now using the staging repo I can find netty3 deployed however its pom is invalid and cannot be used inside Gradle:

```
   > Could not resolve org.elasticsearch.plugin:transport-netty3-client:5.0.0-alpha5.
     Required by:
         elasticsearch-hadoop:elasticsearch-hadoop-mr:5.0.0.BUILD-SNAPSHOT
      > Could not resolve org.elasticsearch.plugin:transport-netty3-client:5.0.0-alpha5.
         > inconsistent module metadata found. Descriptor: org.elasticsearch.plugin:transport-netty3:5.0.0-alpha5 Errors: bad module name: expected='transport-netty3-client' found='transport-netty3'
```

The pom definition does look invalid:

```
  <groupId>org.elasticsearch.plugin</groupId>
  <artifactId>transport-netty3</artifactId>
  <version>5.0.0-alpha5</version>
```

am I missing something?

**Comment by nik9000** [comment] 2016-08-01 14:13
Maybe we just need to cut another build?

**Comment by costin** [comment] 2016-08-01 16:02
@clintongormley fixed the staging repo live and things build locally; the CI should soon (~1h total) confirm that. However I'm still confused why the netty3/4 artifacts don't show up in the OSS Sonatype repo. The latest deployment is from [today](https://oss.sonatype.org/content/repositories/snapshots/org/elasticsearch/elasticsearch/5.0.0-alpha5-SNAPSHOT/) but the modules are not there.
@rjernst any ideas?

**Comment by rjernst** [comment] 2016-08-01 16:05
Note that the reason Clint had to fix it up locally was because the "old" way (prior to unified release) that stuff gets created does not know about the hack I added for client jars of modules/plugins.

> However I'm still confused why the netty3/4 artifacts don't show up in the OSS Sonatype repo

CI is caught in a weird world between old publishing, and the unified release snapshots. I just found the unified builds have been (silently) failing in CI unknowingly forever.  I'm working with infra to get that fixed, and then when we have clean runs, I will ask them to remove the old job (I did not even realize it was still running).

**Comment by costin** [comment] 2016-08-01 16:12
@rjernst Thanks. Fwiw, after upgrading to ES alpha5, Gradle was reporting a build as successful despite clearly failing in the logs. It was the execution time that gave it away.

**Comment by rjernst** [comment] 2016-08-01 16:17
> Gradle was reporting a build as successful despite clearly failing in the logs

Can you expand on this or open a new issue with details?

**Comment by costin** [comment] 2016-08-01 16:38
Still exploring - it _might_ be something inside our build script.

**Comment by clintongormley** [comment] 2016-08-11 11:16
@costin any further info?

**Comment by costin** [comment] 2016-08-11 14:44
The transport plugin seem to be in maven so we're good.
As for the Gradle misbehaviour, I couldn't reproduce it but I'll keep on trying. However this is separate and has nothing to do with the issue itself which can be closed.

**Closed** 2016-08-11 14:55 UTC
Labels: blocker, bug, build, v5.0.0
