### ISSUE TITLE
Embedded JDK 18 on docker-compose keeps failing

### ISSUE THREAD

**Issue by luccas-freitas** [elastic/elasticsearch#87173] opened 2022-05-26 14:41 UTC
### Elasticsearch Version

8.2.1

### Java Version

_bundled_

### OS Version

5.15.0-33-generic #34-Ubuntu SMP Wed May 18 13:34:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

I'm following [this tutorial](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html) and when I run _docker compose up_ shows the error below:

A fatal error has been detected by the Java Runtime Environment:

  Internal Error (codeBuffer.cpp:962), pid=104, tid=105
  guarantee(sect->end() <= tend) failed: sanity

 JRE version:  (18.0.1.1+2) (build )
 Java VM: OpenJDK 64-Bit Server VM (18.0.1.1+2-6, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
 Problematic frame:
 V  [libjvm.so+0x582c9c]  CodeBuffer::verify_section_allocation()+0x36c

 Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /usr/share/elasticsearch/core.104)

 An error report file with more information is saved as:
 /usr/share/elasticsearch/hs_err_pid104.log

in/elasticsearch-env: line 84:   104 Aborted                 (core dumped) "$JAVA" "$XSHARE" -cp "$LAUNCHERS_CLASSPATH" org.elasticsearch.tools.java_version_checker.JavaVersionChecker

### Steps to Reproduce

docker compose up

**Comment by mark-vieira** [comment] 2022-05-31 21:35
@ChrisHegarty this seems vaguely similar to a similar report I think we've gotten recently related to JRE 18. Anything stand out to you? Would we need to see the core dump?

**Comment by ChrisHegarty** [comment] 2022-06-01 11:13
@[luccas-freitas](https://github.com/luccas-freitas) Can you please include the stacktrace from the hs_err_pid log file.

**Comment by luccas-freitas** [comment] 2022-06-01 14:27
Attached: [hs_err_pid19.log](https://github.com/elastic/elasticsearch/files/8815066/hs_err_pid19.log)

**Comment by ChrisHegarty** [comment] 2022-06-01 15:19
Likely a JDK bug, see https://bugs.openjdk.java.net/browse/JDK-8284883

**Comment by dean-long** [comment] 2022-06-02 08:21
It looks different from JDK-8284883 to me.  The backtrace from the hs_err file shows it happening while generating stubs during startup.  If it was JDK-8284883, it would happen in a C2 compiler thread while compiling a method.

**Comment by dean-long** [comment] 2022-06-02 23:08
> You wanna open a new issue for this in the OpenJDK JIRA, or will I?

@ChrisHegarty, please go ahead and create one.  Thanks.

**Comment by ChrisHegarty** [comment] 2022-06-03 08:02
The following issue has been filed in the OpenJDK JIRA to track this - https://bugs.openjdk.java.net/browse/JDK-8287772

**Comment by peppy** [comment] 2022-06-09 17:40
This also applies to ubuntu apt packages (7.17.x). Using 7.16.3 is a temporary workaround.

**Comment by mark-vieira** [comment] 2022-07-12 18:32
@ChrisHegarty the linked JDK bug report was closed as "cannot reproduce". Do we still think this is a legitimate problem?

**Comment by peppy** [comment] 2022-07-14 17:23
This also applies to debian 11 apt packages.

**Comment by yjwong** [comment] 2022-07-17 12:59
Also ran into this issue. Interestingly, it might have to do with the specific CPU (or type) being used. Previously, we were using DigitalOcean Basic nodes running Intel(R) Xeon(R) CPU E5-2697 v3 @ 2.60GHz.

After switching to a new node type - DigitalOcean CPU-Optimized nodes running Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz, we started seeing these crashes on startup.

**Comment by ChrisHegarty** [comment] 2022-07-18 13:15
Without doubt the problem being encountered here is a bug in the JDK - not Elasticsearch. To date, we've been unsuccessful in convincing the JDK maintainers that this issue is worth fixing (without a reproducible testcase independent of Elasticsearch). 

@yjwong @peppy is is possible to reproduce the JVM crash with a simple java program, on the machine configurations that you mentioned.

**Comment by peppy** [comment] 2022-07-19 06:03
Are you thinking just a "hello world" level simple app? I can look to test that out, or I can provide a digitalocean droplet on the configuration required for you to reproduce the issue.

**Comment by leonkoens** [comment] 2022-07-23 10:04
> Also ran into this issue. Interestingly, it might have to do with the specific CPU (or type) being used. Previously, we were using DigitalOcean Basic nodes running Intel(R) Xeon(R) CPU E5-2697 v3 @ 2.60GHz.
> 
> After switching to a new node type - DigitalOcean CPU-Optimized nodes running Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz, we started seeing these crashes on startup.

This happened for us as well. After upgrading to CPU optimized Elasticsearch is crashing. 

Running a simple Hello World app with the build in Java failed about 50% of the time. 

```java
class HelloWorld
{
    public static void main(String args[])
    {
        System.out.println("Hello, World");
    }
}
```

```bash
elasticsearch@hostname:/tmp$ /usr/share/elasticsearch/jdk/bin/java /tmp/hello.java
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (codeBuffer.cpp:962), pid=11540, tid=11541
#  guarantee(sect->end() <= tend) failed: sanity
#
# JRE version:  (18.0.1.1+2) (build )
# Java VM: OpenJDK 64-Bit Server VM (18.0.1.1+2-6, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x582c9c]  CodeBuffer::verify_section_allocation()+0x36c
#
# Core dump will be written. Default location: /usr/share/elasticsearch/jdk/bin/core
#
# An error report file with more information is saved as:
# /tmp/hs_err_pid11540.log
#
#
Aborted
elasticsearch@hostname:/tmp$ /usr/share/elasticsearch/jdk/bin/java /tmp/hello.java
Hello, World
```

[hs_err_pid11540.log](https://github.com/elastic/elasticsearch/files/9173515/hs_err_pid11540.log)

**Comment by rgroten** [comment] 2022-08-04 16:04
Same issue for me trying to update from ES 8.1.0 to ES 8.3.3.  I also get the same result with the helloworld test @leonkoens posted.

**Comment by markandrewj** [comment] 2022-08-04 18:01
I went ahead and pulled down version 19 of OpenJDK from [https://jdk.java.net/19/](https://jdk.java.net/19/) and ran the hello world program with it. I did not encounter the same issue when running the hello world program with Java 19. I tested with Java 19, after speaking with @rgroten, and testing the Java packaged with Elastic in the same environment. Using the packaged Java resulted in the same core dump as above to happen sporadically. 

Java 19 is not GA, so it seems the patch that fixes this should be back-ported to Java 18. I wanted to provide this information because I noticed in the OpenJDK issue tracker there were people reporting this issue, but the developers were not able to reproduce the issue, and as a result it was being treated as an issue with Elastic.

**Comment by mark-vieira** [comment] 2022-08-04 19:42
Thanks for the investigation @markandrewj. As is our normal process, our intention is to upgrade the bundled JDK to Java when it goes GA which is scheduled for 20 September. In the meantime, using Java 17 is also an option. As I understand it this issue seems to be specific to Java 18.

**Comment by rgroten** [comment] 2022-10-12 15:41
> Thanks for the investigation @markandrewj. As is our normal process, our intention is to upgrade the bundled JDK to Java 19 when it goes GA which is scheduled for 20 September. In the meantime, using Java 17 is also an option. As I understand it this issue seems to be specific to Java 18.

Hi @mark-vieira , I just tried elastic 8.4.3 and this problem with Java 18 still exists.  Any idea when Java 19 will be bundled in?  Thanks!

**Comment by mark-vieira** [comment] 2022-10-12 22:07
I've just merged the [upgrade](https://github.com/elastic/elasticsearch/pull/90571) so it should be available in the next upcoming release.

**Comment by rgroten** [comment] 2022-10-12 22:57
Oh that's great news thank you!

**Comment by markandrewj** [comment] 2023-01-09 21:11
We have been able to upgrade to Elastic 8.5. Unless there is more to do at this point, it looks like this issue is resolved and be closed. Thank you to everyone for the help.

**Comment by mark-vieira** [comment] 2024-01-09 23:59
Bundled JDK has been updated to Java 21. Closing this issue.

**Closed by mark-vieira** 2024-01-09 23:59 UTC
Labels: >bug, :Delivery/Packaging, Team:Delivery
