### ISSUE TITLE
[CI] RunDataFrameAnalyticsIT testOutlierDetectionStopAndRestart failure

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#52654] opened 2020-02-21 17:16 UTC
I was unable to reproduce this failure locally.

https://gradle-enterprise.elastic.co/s/3tpftagug7eea/tests/zcquf3hc3eoda-q3ovxh6ju37ic

```:x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner » org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT » testOutlierDetectionStopAndRestart (36.539s)

Expected: is null
     but: was "[integTest-1][127.0.0.1:32893][indices:admin/create]"
java.lang.AssertionError
: 

Expected: is null
     but: was "[integTest-1][127.0.0.1:32893][indices:admin/create]"
Open stacktrace
[2020-02-20T21:50:10,836][INFO ][o.e.x.m.i.RunDataFrameAnalyticsIT] [testOutlierDetectionStopAndRestart] before test
[2020-02-20T21:50:10,838][INFO ][o.e.x.m.i.RunDataFrameAnalyticsIT] [testOutlierDetectionStopAndRestart] [RunDataFrameAnalyticsIT#testOutlierDetectionStopAndRestart]: setting up test
[2020-02-20T21:50:10,840][INFO ][o.e.p.PluginsService     ] [testOutlierDetectionStopAndRestart] no modules loaded
[2020-02-20T21:50:10,840][INFO ][o.e.p.PluginsService     ] [testOutlierDetectionStopAndRestart] loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
[2020-02-20T21:50:10,840][INFO ][o.e.p.PluginsService     ] [testOutlierDetectionStopAndRestart] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
[2020-02-20T21:50:10,840][INFO ][o.e.p.PluginsService     ] [testOutlierDetectionStopAndRestart] loaded plugin [org.elasticsearch.xpack.core.XPackClientPlugin]
[2020-02-20T21:50:10,938][INFO ][o.e.t.ExternalTestCluster] [testOutlierDetectionStopAndRestart] Setup ExternalTestCluster [integTest] made of [3] nodes
[2020-02-20T21:50:11,328][INFO ][o.e.x.m.i.RunDataFrameAnalyticsIT] [testOutlierDetectionStopAndRestart] [RunDataFrameAnalyticsIT#testOutlierDetectionStopAndRestart]: all set up test
[2020-02-20T21:50:46,707][ERROR][o.e.x.m.i.RunDataFrameAnalyticsIT] [testOutlierDetectionStopAndRestart] Failed to stop data frame analytics jobs; trying force
org.elasticsearch.ElasticsearchStatusException: cannot close data frame analytics [test_outlier_detection_stop_and_restart] because it failed, use force stop instead
	at org.elasticsearch.xpack.core.ml.utils.ExceptionsHelper.conflictStatusException(ExceptionsHelper.java:67) ~[x-pack-core-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
	at org.elasticsearch.xpack.ml.action.TransportStopDataFrameAnalyticsAction.findAnalyticsToStop(TransportStopDataFrameAnalyticsAction.java:127) ~[x-pack-ml-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
	at org.elasticsearch.xpack.ml.action.TransportStopDataFrameAnalyticsAction.lambda$doExecute$1(TransportStopDataFrameAnalyticsAction.java:102) ~[x-pack-ml-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) ~[elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
	at org.elasticsearch.xpack.ml.action.TransportStopDataFrameAnalyticsAction.lambda$expandIds$4(TransportStopDataFrameAnalyticsAction.java:174) ~[x-pack-ml-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) ~[elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
	at org.elasticsearch.xpack.ml.dataframe.persistence.DataFrameAnalyticsConfigProvider.lambda$getMultiple$3(DataFrameAnalyticsConfigProvider.java:133) ~[x-pack-ml-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) ~[elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43) ~[elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:70) ~[elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:64) ~[elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43) ~[elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
	at org.elasticsearch.xpack.ml.action.TransportGetDataFrameAnalyticsAction.lambda$doExecute$0(TransportGetDataFrameAnalyticsAction.java:63) ~[x-pack-ml-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) ~[elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
	at org.elasticsearch.xpack.core.action.AbstractTransportGetResourcesAction$1.onResponse(AbstractTransportGetResourcesAction.java:124) ~[x-pack-core-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
	at org.elasticsearch.xpack.core.action.AbstractTransportGetResourcesAction$1.onResponse(AbstractTransportGetResourcesAction.java:97) ~[x-pack-core-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43) ~[elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:70) ~[elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:64) ~[elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43) ~[elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.sendSearchResponse(AbstractSearchAsyncAction.java:542) ~[elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
	at org.elasticsearch.action.search.ExpandSearchPhase.run(ExpandSearchPhase.java:117) ~[elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:349) ~[elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:343) ~[elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
	at org.elasticsearch.action.search.FetchSearchPhase.moveToNextPhase(FetchSearchPhase.java:216) ~[elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
	at org.elasticsearch.action.search.FetchSearchPhase.lambda$innerRun$1(FetchSearchPhase.java:105) ~[elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
	at org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:111) ~[elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
	at org.elasticsearch.action.search.FetchSearchPhase.access$000(FetchSearchPhase.java:44) ~[elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
	at org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:87) ~[elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44) ~[elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:692) ~[elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_241]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
[2020-02-20T21:50:46,797][INFO ][o.e.x.m.i.RunDataFrameAnalyticsIT] [testOutlierDetectionStopAndRestart] [RunDataFrameAnalyticsIT#testOutlierDetectionStopAndRestart]: cleaning up after test
[2020-02-20T21:50:47,293][INFO ][o.e.x.m.i.RunDataFrameAnalyticsIT] [testOutlierDetectionStopAndRestart] [RunDataFrameAnalyticsIT#testOutlierDetectionStopAndRestart]: cleaned up after test
[2020-02-20T21:50:47,293][INFO ][o.e.x.m.i.RunDataFrameAnalyticsIT] [testOutlierDetectionStopAndRestart] after test
REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT.testOutlierDetectionStopAndRestart" -Dtests.seed=2DE2C601564EDB34 -Dtests.security.manager=true -Dtests.locale=sl-SI -Dtests.timezone=Etc/GMT+12 -Dcompiler.java=13
REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT.testOutlierDetectionStopAndRestart" -Dtests.seed=2DE2C601564EDB34 -Dtests.security.manager=true -Dtests.locale=sl-SI -Dtests.timezone=Etc/GMT+12 -Dcompiler.java=13```

**Comment by jdconrad** [comment] 2020-02-21 17:17
Another failure in the test suite: https://github.com/elastic/elasticsearch/issues/49305

**Comment by jdconrad** [comment] 2020-02-21 17:36
Muted in 7.6 and 7.7.

**Comment by davidkyle** [comment] 2020-02-21 18:16
The task failed for some mysterious reason 
```
Successfully update task state to [failed]
```
yay successfully 

Here are the [logs.zip](https://github.com/elastic/elasticsearch/files/4237427/logs.zip) the only lines I see referencing the job are

```
[2020-02-21T09:50:13,033][INFO ][o.e.x.m.a.TransportStartDataFrameAnalyticsAction] [integTest-0] [test_outlier_detection_stop_and_restart] Starting data frame analytics
[2020-02-21T09:50:13,172][INFO ][o.e.x.m.d.DataFrameAnalyticsManager] [integTest-0] [test_outlier_detection_stop_and_restart] Creating destination index [test-outlier-detection-stop-and-restart-results]
[2020-02-21T09:50:13,258][INFO ][o.e.x.m.a.TransportStopDataFrameAnalyticsAction] [integTest-0] [test_outlier_detection_stop_and_restart] Stopping task with force [false]
[2020-02-21T09:50:13,778][INFO ][o.e.x.m.a.TransportStartDataFrameAnalyticsAction] [integTest-0] [test_outlier_detection_stop_and_restart] Starting data frame analytics
[2020-02-21T09:50:13,877][INFO ][o.e.x.m.d.DataFrameAnalyticsManager] [integTest-0] [test_outlier_detection_stop_and_restart] Creating destination index [test-outlier-detection-stop-and-restart-results]
[2020-02-21T09:50:13,947][INFO ][o.e.x.m.d.DataFrameAnalyticsTask] [integTest-0] [test_outlier_detection_stop_and_restart] Successfully update task state to [failed]
[2020-02-21T09:50:46,746][INFO ][o.e.x.m.a.TransportStopDataFrameAnalyticsAction] [integTest-0] [test_outlier_detection_stop_and_restart] Stopping task with force [true]
```

Odd that it tries to create the destination index again when it restarts.

**Comment by davidkyle** [comment] 2020-02-24 15:25
I've reverted the muting of this test on the 7.x branch in de3d674bb7949fe44ee1a2592a48d4317fbd1481. The extra logging added in #52659 should shine a light on what went wrong. When it fails again please ping the ml team.

**Comment by dnhatn** [comment] 2020-02-26 13:55
@davidkyle This test failed again on 7.x: https://gradle-enterprise.elastic.co/s/gk43p25mbnfia/tests/zcquf3hc3eoda-q3ovxh6ju37ic.

**Comment by davidkyle** [comment] 2020-02-26 14:41
Thanks @dnhatn 

I've muted the test again in ad3a3b1af984bc051e7af01b50d1f4c78120e44d and here are the 
[logs](https://github.com/elastic/elasticsearch/files/4256286/logs.zip)

**Comment by davidkyle** [comment] 2020-02-26 18:05
The error is 
```
Updated analytics task state to [failed] with reason [[integTest-0][127.0.0.1:37781][indices:admin/create]]
```
 where the `[integTest-0][127.0.0.1:37781][indices:admin/create]` part comes from an [ActionTransportException](https://github.com/elastic/elasticsearch/blob/99f88f15c5febbca2d13b5b5fda27b844153bf1a/server/src/main/java/org/elasticsearch/transport/ActionTransportException.java#L78) 

We know the create index is failing but why? Well the cause is not in `Exception.getMessage()` better unwrap that exception, another round of logging changes and unmuting coming up. 

The test starts then stops a DFA. On restart the the DFA will delete and recreate the destination index if the DFA was only partially complete from the last run. The deleting is fine but the recreation is erring. On a different node there is the log message 
```
[test-outlier-detection-stop-and-restart-results] creating index, cause [auto(bulk api)], templates [random_index_template], shards [3]/[1], mappings []
```
Note the cause **auto(bulk api)** not **api** which it would be if create index was called. It looks like something in the DFA is doing a bulk write before the index is created

**Comment by davidkyle** [comment] 2020-02-27 12:41
Unmuted again in d8bdf31110521733e5cfc3e7a2da2fa3450db2f3.

If you are triaging this failure please ping `@elastic/ml-core`

**Comment by dimitris-athanasiou** [comment] 2020-04-03 14:37
No failures of this appeared for over a month now. Closing for now.

**Closed by dimitris-athanasiou** 2020-04-03 14:37 UTC
Labels: :ml, >test-failure, v7.8.0
