### ISSUE TITLE
update doc but can't search

### ISSUE THREAD

**Issue by NigelZHANG** [elastic/elasticsearch#49790] opened 2019-12-03 09:57 UTC
I use **elasticsearch: 6.8**
I delete the index, it will not delete all doc Immediately, when I create the new doc with same name index, it return 200 that show the doc has been updated, but can't search in the index.
Hope to get your help.
`elastic.BulkResponseItem{Index:\"n10219288_bngdnruleenesf2ter10\", Type:\"n10219288_bngdnruleenesf2ter10_type\", Id:\"11\", Version:11, Result:\"updated\", Shards:(*elastic.shardsInfo)(0xc000f28b80), SeqNo:39, PrimaryTerm:1, Status:200, ForcedRefresh:false, Error:(*elastic.ErrorDetails)(nil)}, shards is: &elastic.shardsInfo{Total:2, Successful:2, Failed:0}`

**Comment by gaobinlong** [comment] 2019-12-03 10:25
The Version in the response is 11, it means the doc exists in the index, so I think the index has not been deleted. And check your query dsl if the doc can't be searched. You can ask question in  the forum: https://discuss.elastic.co.

**Comment by henningandersen** [comment] 2019-12-03 11:19
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.

**Closed by henningandersen** 2019-12-03 11:19 UTC

**Comment by NigelZHANG** [comment] 2019-12-04 08:49
I am sorry to description the question blurred, @gaobinlong @henningandersen 
I delete the doc and force merge the index, It show the result is updated when I put the doc again, but the doc can't search. I check the es doc that tell me the doc will not delete immediately, but why I can't search it in spite of putting it again. Hope to get your help
Below is my steps:
1. delete all docs
2. check the index doc
`green open n10219288_bngdnruleenesf2ter10 iREbA-D1S9GTiz-vsFVjMg 5 1 0 0  2.2kb  1.1kb`
3. force merge index to confirm the doc is empty
`{"_shards":{"total":10,"successful":10,"failed":0}}`
4. get the shards info
`[{"index":"n10219288_bngdnruleenesf2ter10","shard":"2","prirep":"p","state":"STARTED","docs":"0","store":"228b","ip":"x.x.x.x","node":"Jr-kmy5"},{"index":"n10219288_bngdnruleenesf2ter10","shard":"2","prirep":"r","state":"STARTED","docs":"0","store":"228b","ip":"x.x.x.x","node":"dApGvYg"},{"index":"n10219288_bngdnruleenesf2ter10","shard":"1","prirep":"r","state":"STARTED","docs":"0","store":"228b","ip":"x.x.x.x","node":"Jr-kmy5"},{"index":"n10219288_bngdnruleenesf2ter10","shard":"1","prirep":"p","state":"STARTED","docs":"0","store":"228b","ip":"x.x.x.x","node":"dApGvYg"},{"index":"n10219288_bngdnruleenesf2ter10","shard":"3","prirep":"r","state":"STARTED","docs":"0","store":"228b","ip":"x.x.x.x","node":"Jr-kmy5"},{"index":"n10219288_bngdnruleenesf2ter10","shard":"3","prirep":"p","state":"STARTED","docs":"0","store":"228b","ip":"x.x.x.x","node":"dApGvYg"},{"index":"n10219288_bngdnruleenesf2ter10","shard":"4","prirep":"p","state":"STARTED","docs":"0","store":"228b","ip":"x.x.x.x","node":"Jr-kmy5"},{"index":"n10219288_bngdnruleenesf2ter10","shard":"4","prirep":"r","state":"STARTED","docs":"0","store":"228b","ip":"x.x.x.x","node":"dApGvYg"},{"index":"n10219288_bngdnruleenesf2ter10","shard":"0","prirep":"p","state":"STARTED","docs":"0","store":"228b","ip":"x.x.x.x","node":"Jr-kmy5"},{"index":"n10219288_bngdnruleenesf2ter10","shard":"0","prirep":"r","state":"STARTED","docs":"0","store":"228b","ip":"x.x.x.x","node":"dApGvYg"}]`
5. put doc again
`{Index:\"n10219288_bngdnruleenesf2ter10\", Type:\"n10219288_bngdnruleenesf2ter10_type\", Id:\"1\", Version:16, Result:\"updated\", Shards:(*elastic.shardsInfo)(0xc00059cba0), SeqNo:78, PrimaryTerm:1, Status:200, ForcedRefresh:false, Error:(*elastic.ErrorDetails)(nil)}`
6. search the doc:
`curl endpoint/n10219288_bngdnruleenesf2ter10/n10219288_bngdnruleenesf2ter10_type/1`
result:
`{"_index":"n10219288_bngdnruleenesf2ter10","_type":"n10219288_bngdnruleenesf2ter10_type","_id":"1","found":false}`

**Comment by henningandersen** [comment] 2019-12-04 13:42
@NigelZHANG as noted, this is a user question and should be asked in the forums.

My best guess is that you are missing to refresh the index after the writes, but a more comprehensive either kibana style or curl style reproduction would be nice in order to help out. And that conversation should be on our discuss forum, not here, since we want to preserve github for confirmed bugs, feature requests and pull requests.

Please go to https://discuss.elastic.co/ and ask your question there, including as much detail as possible.
