### ISSUE TITLE
Will range aggregation support 'lte/lt/gt/gte'?

### ISSUE THREAD

**Issue by thihy** [elastic/elasticsearch#12153] opened 2015-07-09 12:33 UTC
The range query support  'lte/lt/gt/gte', will the range aggregation support too? 
For price of goods, I want to use range [0,50], [50,100], ...

**Comment by jpountz** [comment] 2015-07-09 13:10
Duplicate of https://github.com/elastic/elasticsearch/issues/5249

**Closed by jpountz** 2015-07-09 13:10 UTC
