### ISSUE TITLE
[CI] TransportServiceHandshakeTests testAcceptsMismatchedBuildHashFromDifferentVersion failing

### ISSUE THREAD

**Issue by arteam** [elastic/elasticsearch#99765] opened 2023-09-21 15:06 UTC
**Build scan:**
https://gradle-enterprise.elastic.co/s/xrl53o33btyf4/tests/:server:test/org.elasticsearch.transport.TransportServiceHandshakeTests/testAcceptsMismatchedBuildHashFromDifferentVersion

**Reproduction line:**
```
./gradlew ':server:test' --tests "org.elasticsearch.transport.TransportServiceHandshakeTests.testAcceptsMismatchedBuildHashFromDifferentVersion" -Dtests.seed=F7A459ED97A7C11F -Dtests.locale=ga-IE -Dtests.timezone=Asia/Khandyga -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.transport.TransportServiceHandshakeTests&tests.test=testAcceptsMismatchedBuildHashFromDifferentVersion

**Failure excerpt:**
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=5860, name=Thread-221, state=RUNNABLE, group=TGRP-TransportServiceHandshakeTests]

  at __randomizedtesting.SeedInfo.seed([F7A459ED97A7C11F:6B8492AF6057E387]:0)

  Caused by: java.lang.AssertionError: cluster:monitor/state

    at __randomizedtesting.SeedInfo.seed([F7A459ED97A7C11F]:0)
    at org.elasticsearch.transport.InboundAggregator.lambda$new$0(InboundAggregator.java:46)
    at org.elasticsearch.transport.InboundAggregator.initializeRequestState(InboundAggregator.java:197)
    at org.elasticsearch.transport.InboundAggregator.headerReceived(InboundAggregator.java:66)
    at org.elasticsearch.transport.InboundPipeline.headerReceived(InboundPipeline.java:138)
    at org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:112)
    at org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:96)
    at org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:61)
    at org.elasticsearch.transport.netty4.Netty4MessageInboundHandler.channelRead(Netty4MessageInboundHandler.java:48)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.lang.Thread.run(Thread.java:1623)

```

**Comment by stu-elastic** [comment] 2023-10-03 15:44
This seems to be a rare concurrency issue (one failure in the last 90 days) due to the handler not existing for `ClusterStateAction`.  Upon reviewing the registration code, registration creates a [new `Map`](https://github.com/elastic/elasticsearch/blob/164e97e2ca1203dbacb3b3bebb1cdb5129a2083c/server/src/main/java/org/elasticsearch/transport/Transport.java#L289) and flips a `volatile` reference.

Unfortunately, registration occurs late in Node creation so we need some sort of lazy loading mechanism.  That means fixing this issue (which I've been unable to reproduce after a large number of iterations) may be quite invasive and we'll be unable to validate the fix.

With that said, I'm going to close this issue and if it reoccurs we'll reevaluate.

**Closed by stu-elastic** 2023-10-03 15:44 UTC
Labels: :Core/Infra/Core, >test-failure, Team:Core/Infra
