### ISSUE TITLE
[CI] DocValueFormatTests testParseEpochSecondsTimezone failing

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#75594] opened 2021-07-21 15:04 UTC
**Build scan:**
https://gradle-enterprise.elastic.co/s/k7awyx6u5f3pg/tests/:server:test/org.elasticsearch.search.DocValueFormatTests/testParseEpochSecondsTimezone

**Reproduction line:**
`./gradlew ':server:test' --tests "org.elasticsearch.search.DocValueFormatTests.testParseEpochSecondsTimezone" -Dtests.seed=86D4AE56ED1AB2CA -Dtests.locale=sl-SI -Dtests.timezone=Africa/Cairo -Druntime.java=8`

**Applicable branches:**
7.x

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.search.DocValueFormatTests&tests.test=testParseEpochSecondsTimezone

**Failure excerpt:**
```
java.lang.AssertionError: failed formatting for tz Antarctica/Macquarie expected:<5088138463325883000> but was:<5088138463322283000>

  at __randomizedtesting.SeedInfo.seed([86D4AE56ED1AB2CA:18B7F30EC0A72106]:0)
  at org.junit.Assert.fail(Assert.java:88)
  at org.junit.Assert.failNotEquals(Assert.java:834)
  at org.junit.Assert.assertEquals(Assert.java:645)
  at org.elasticsearch.search.DocValueFormatTests.testParseEpochSecondsTimezone(DocValueFormatTests.java:273)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at java.lang.Thread.run(Thread.java:748)

```

**Comment by not-napoleon** [comment] 2021-07-21 19:16
the behavior of this test seems to depend on the JVM running it.  It looks like [the 2020b time zone update](https://mm.icann.org/pipermail/tz-announce/2020-October/000059.html) changed timestamps in Antarctica/Macquarie.  I suspect this is the root cause of the issue here, although I have no idea why or what to do about it.

**Comment by pgomulka** [comment] 2021-07-21 19:45
this could be related to DST change I guess.
actual
```
resolution.toInstant(5088138463322283000L).atZone(timeZone)
result = {ZonedDateTime@4472} "+161238659-04-03T02:18:03+11:00[Antarctica/Macquarie]"
 dateTime = {LocalDateTime@4474} "+161238659-04-03T02:18:03"
 offset = {ZoneOffset@4475} "+11:00"
 zone = {ZoneRegion@3440} "Antarctica/Macquarie"
```
expected
```
resolution.toInstant(5088138463325883000L).atZone(timeZone)
result = {ZonedDateTime@4464} "+161238659-04-03T02:18:03+10:00[Antarctica/Macquarie]"
 dateTime = {LocalDateTime@4466} "+161238659-04-03T02:18:03"
 offset = {ZoneOffset@4460} "+10:00"
 zone = {ZoneRegion@3440} "Antarctica/Macquarie"
```

**Comment by not-napoleon** [comment] 2021-07-21 20:24
yeah, that's what we're thinking too.  I'll dig into it.  Thanks for the examples.

**Comment by not-napoleon** [comment] 2021-07-21 20:59
Okay, I reproed it for a DST transition in `America/New_York`, so it's definitely not related to the timezone getting updated.  My guess is the weird JVM behavior I observed happens because the old configuration for that time zone didn't use DST and the new one (which is the same as Tasmania) does.  I'm not sure why this test fails on DST transitions though.  I'm going to dig through the formatting code and see if I can find it.

Also, what tool are you using that gives that handy DST warning?  that seems useful, and I would adopt it on aggs date tests if possible.

**Comment by pgomulka** [comment] 2021-07-22 06:32
I used https://www.epochconverter.com/

**Comment by dimitris-athanasiou** [comment] 2021-08-09 13:06
Another failure in https://gradle-enterprise.elastic.co/s/icocclpojmfys 

```
failed formatting for tz America/Shiprock expected:<4251220723700410327> but was:<4251220723696810327>
```

**Comment by not-napoleon** [comment] 2021-08-17 16:26
After a considerable amount of digging into this, I've traced it to a bug in the JDK's time formatting library.  They [opened this ticket](https://bugs.openjdk.java.net/browse/JDK-8272473) based on my report.  I'm waiting to see how that resolves before taking any further action on our side.

**Comment by davidkyle** [comment] 2021-08-23 12:41
Another on 7.14 with Java 8

`java.lang.AssertionError: failed formatting for tz Europe/Zurich expected:<1982775388871164000> but was <1982775388867564000>`

https://gradle-enterprise.elastic.co/s/ieh5ueehuly3k/tests/:server:test/org.elasticsearch.search.DocValueFormatTests/testParseEpochSecondsTimezone?top-execution=1

**Comment by not-napoleon** [comment] 2022-10-14 14:46
This is fixed in the core java library, and hasn't failed recently.  I think we can safely close this issue now.

**Closed by not-napoleon** 2022-10-14 14:46 UTC
Labels: :Analytics/Aggregations, >test-failure, Team:Analytics
