### ISSUE TITLE
[CI] MetaDataWriteDataNodesIT.testMetaIsRemovedIfAllShardsFromIndexRemoved failure

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#13758] opened 2015-09-24 07:33 UTC
Fails with the following generic message (for this test, as this is what it tests):

expected index to not be in meta state of node node_t1

see http://build-us-00.elastic.co/job/es_core_2x_centos/334/testReport/junit/org.elasticsearch.gateway/MetaDataWriteDataNodesIT/testMetaIsRemovedIfAllShardsFromIndexRemoved/

More detailed to be filled in as they are found.

**Comment by brwe** [comment] 2015-10-13 13:20
This failed four times within five days (19-24 Sep) but not before or after. I was unable to reproduce it too.
It seems like whatever caused this failure is fixed now. It is unsatisfying to not know what was going on but don't think it makes much sense to spend time on an analysis so I will just close this issue. Feel free to reopen if you disagree.

**Comment by javanna** [comment] 2015-10-13 13:26
funny timing, I was looking into this as it just failed on the 2.1 branch...reopening :)

http://build-us-00.elastic.co/job/es_core_21_centos/76/

**Comment by brwe** [comment] 2015-10-13 15:13
chatted with @s1monw and we found the problem: in the test we use the WindowsFS mock file system to simulate that windows does not delete files if they are opened by some other process and instead gives you `java.io.IOException: access denied`. In the test we also check if the shard was deleted while it is being deleted. This check might hold on to a file while the node is trying to delete it and deletion will fail then. I am trying to figure out if this is a bug. We might end up having shards lying around forever if for example a virus scanner is opening files while shards are relocated away from a node on windows.

**Closed** 2015-10-19 12:25 UTC
Labels: jenkins, test
