### ISSUE TITLE
ES not able to start

### ISSUE THREAD

**Issue by hello4usharath** [elastic/elasticsearch#27031] opened 2017-10-17 08:14 UTC
```
][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [********] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.NullPointerException
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-5.6.3.jar:5.6.3]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) ~[elasticsearch-5.6.3.jar:5.6.3]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70) ~[elasticsearch-5.6.3.jar:5.6.3]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) ~[elasticsearch-5.6.3.jar:5.6.3]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-5.6.3.jar:5.6.3]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.6.3.jar:5.6.3]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.6.3.jar:5.6.3]
Caused by: java.lang.NullPointerException
        at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:273) ~[?:?]
        at org.elasticsearch.common.io.PathUtils.get(PathUtils.java:60) ~[elasticsearch-5.6.3.jar:5.6.3]
        at org.elasticsearch.monitor.os.OsProbe.readSysFsCgroupCpuAcctCpuAcctUsage(OsProbe.java:274) ~[elasticsearch-5.6.3.jar:5.6.3]
        at org.elasticsearch.monitor.os.OsProbe.getCgroupCpuAcctUsageNanos(OsProbe.java:261) ~[elasticsearch-5.6.3.jar:5.6.3]
        at org.elasticsearch.monitor.os.OsProbe.getCgroup(OsProbe.java:419) ~[elasticsearch-5.6.3.jar:5.6.3]
        at org.elasticsearch.monitor.os.OsProbe.osStats(OsProbe.java:464) ~[elasticsearch-5.6.3.jar:5.6.3]
        at org.elasticsearch.monitor.os.OsService.<init>(OsService.java:45) ~[elasticsearch-5.6.3.jar:5.6.3]
        at org.elasticsearch.monitor.MonitorService.<init>(MonitorService.java:45) ~[elasticsearch-5.6.3.jar:5.6.3]
        at org.elasticsearch.node.Node.<init>(Node.java:362) ~[elasticsearch-5.6.3.jar:5.6.3]
        at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.3.jar:5.6.3]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.3.jar:5.6.3]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.3.jar:5.6.3]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.3.jar:5.6.3]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.3.jar:5.6.3]
```

**Comment by hello4usharath** [comment] 2017-10-17 08:15
Java version
openjdk version "1.8.0_144"
OpenJDK Runtime Environment (build 1.8.0_144-b01)
OpenJDK 64-Bit Server VM (build 25.144-b01, mixed mode)

**Comment by dadoonet** [comment] 2017-10-17 09:04
Did you change any settings? What are they? How are you launching elasticsearch? How did you install it?

**Comment by jasontedor** [comment] 2017-10-17 09:13
I’ll take this one @dadoonet, it’s a problem with the cgroups on the system for this user.

**Comment by hello4usharath** [comment] 2017-10-17 10:25
What exactly cgroup means?

**Comment by hello4usharath** [comment] 2017-10-17 10:49
Is this Linux parameters?

**Comment by hello4usharath** [comment] 2017-10-17 10:56
How can we fix cgroup issue?

**Comment by rkatwal** [comment] 2017-10-27 01:06
There seems to be an issue while accessing a path on file system which seems to be getting returned as NULL. Did you check to make sure all paths used are accessible?

Caused by: java.lang.NullPointerException
        at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:273) ~[?:?]
        at org.elasticsearch.common.io.PathUtils.get(PathUtils.java:60)

**Comment by K0NZ1** [comment] 2017-11-10 09:00
@hello4usharath 
Did you find a solution? I have currently the same problem.

**Comment by K0NZ1** [comment] 2017-11-10 09:09
Ok, find a solution (https://discuss.elastic.co/t/why-elasticsearch-5-2-0-throw-nullpointerexception-when-start/74739/12).
sudo mount -t cgroup -o rw,nosuid,nodev,noexec,relatime,cpu,cpuacct cgroup /sys/fs/cgroup/cpu,cpuacct
Thanks  to @jasontedor

**Comment by jasontedor** [comment] 2018-03-14 02:17
Closing as this is due to a cgroup configuration issue.

**Closed by jasontedor** 2018-03-14 02:17 UTC
Labels: :Core/Core
