### ISSUE TITLE
Bitwise operator 4&7 !=0 returns 0 but must be 1.

### ISSUE THREAD

**Issue by gr3ysky** [elastic/elasticsearch#26272] opened 2017-08-18 07:37 UTC
Elasticsearch version: 5.0.2
OS version:Linux
I have a document containing a field productId with value 7
Here is the doc
```
{
    "took": 1,
    "timed_out": false,
    "_shards": {
        "total": 5,
        "successful": 5,
        "failed": 0
    },
    "hits": {
        "total": 1,
        "max_score": 1,
        "hits": [
            {
                "_index": "smartex",
                "_type": "product_trend_report_data",
                "_id": "5d32ccc9-e085-49ee-b6bd-5eb1c2b9da69",
                "_score": 1,
                "_source": {
                    "reportType": 3,
                    "shiftId": 1,
                    "tenantId": 2,
                    "locationId": 267,
                    "expressionId": 1,
                    "variableId": 1,
                    "variableType": 3,
                    "reportPeriod": 5,
                    "creationTime": "2017-08-12T00:00:00",
                    "reportValue": "80",
                    "persistTime": "2017-08-18T07:19:10.3192712Z",
                    "id": "5d32ccc9-e085-49ee-b6bd-5eb1c2b9da69",
                    **"productId": 7,**
                    "serialNo": ""
                }
            }
        ]
    }
}
```

For the query 
```
{
	"script_fields" : {
        "test" : {
            "script" : {
                "lang": "expression",
                "inline": "pids & doc['productId'].value", 
                "params": {
                	"pids": 4
              }
            }
        }
    }
}
```
I get 
```
{
    "took": 3,
    "timed_out": false,
    "_shards": {
        "total": 5,
        "successful": 5,
        "failed": 0
    },
    "hits": {
        "total": 1,
        "max_score": 1,
        "hits": [
            {
                "_index": "smartex",
                "_type": "product_trend_report_data",
                "_id": "5d32ccc9-e085-49ee-b6bd-5eb1c2b9da69",
                "_score": 1,
                "fields": {
                    "test": [
                        **4**
                    ]
                }
            }
        ]
    }
}
```
which is correct.
But when I use !=0 operator 
```
{
	"script_fields" : {
        "test" : {
            "script" : {
                "lang": "expression",
                "inline": "**pids & doc['productId'].value!=0**", 
                "params": {
                	"pids": 4
              }
            }
        }
    }
}
```
I get 

```
{
    "took": 3,
    "timed_out": false,
    "_shards": {
        "total": 5,
        "successful": 5,
        "failed": 0
    },
    "hits": {
        "total": 1,
        "max_score": 1,
        "hits": [
            {
                "_index": "smartex",
                "_type": "product_trend_report_data",
                "_id": "5d32ccc9-e085-49ee-b6bd-5eb1c2b9da69",
                "_score": 1,
                "fields": {
                    **"test": [
                        0
                    ]**
                }
            }
        ]
    }
}
```
0 on the test field but it must be 1

Can u patch this please. Thanks

**Comment by shaheda** [comment] 2017-08-18 08:59
0 is correct. != has higher precedence over &. 7!=0 is 1, so 4&1 is 0.

**Comment by nik9000** [comment] 2017-08-18 13:44
I'm labeling this painless so @jdconrad can have a look. I'm not sure if this is an actual bug or a documentation bug but @jdconrad will know.

**Comment by jdconrad** [comment] 2017-08-18 14:31
@shanayl is correct.  The order of precedence for operators in Painless can be found in the documentation (https://www.elastic.co/guide/en/elasticsearch/painless/master/_operators.html).  I'm going to go ahead and close this as this is not a bug.  @gr3ysky Please feel free to re-open or file another issue if the solution presented isn't working as expected.

**Closed by jdconrad** 2017-08-18 14:31 UTC
Labels: :Plugin Lang Painless
