### ISSUE TITLE
Highlighting broken with has_child query

### ISSUE THREAD

**Issue by HonzaKral** [elastic/elasticsearch#16687] opened 2016-02-16 03:13 UTC
if you have a parent/child relationship doing a query that contains a `has_child` will result in error:

```
curl localhost:9200/_search -d '{
    "highlight": {"fields": {"title": {}}},
    "query": {
        "has_child": {
            "query": {"match": {"body": "drip"}},
            "type": "answer"
        }
    }
}'
```

Error returned:
```
{
    "type":"illegal_state_exception",
    "reason":"can't load global ordinals for reader of type: class org.apache.lucene.search.highlight.WeightedSpanTermExtractor$DelegatingLeafReader must be a DirectoryReader"
}
```

Works fine on 2.0.0, fails on 2.1.0 and later.

**Comment by martijnvg** [comment] 2016-02-16 05:43
Duplicate of #14999. We should just as before ignore the `has_child` during highlighting.

**Closed by martijnvg** 2016-02-16 05:43 UTC
