### ISSUE TITLE
Different search result between adding AND between words and using default_operator

### ISSUE THREAD

**Issue by huangenyan** [elastic/elasticsearch#28385] opened 2018-01-26 04:41 UTC
**Elasticsearch version** : 
```
Version: 6.1.1, Build: bd92e7f/2017-12-17T20:23:25.338Z, JVM: 1.8.0_25
```

**Plugins installed**: None

**JVM version**:
```
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
```

**OS version**: Both on my own laptop (macOS) and the server (Ubuntu)

**Description of the problem including expected versus actual behavior**:
Suppose I have the following 2 docs:
```
PUT /twitter/doc/evan-smith 
{
  "name": "Evan Smith",
  "content": "Doe is green tech",
  "categories": [
        "green tech",
        "website development"
    ]
}
```
and
```
PUT /twitter/doc/john-doe
{
  "name": "John Doe",
    "categories": [
        "green tech",
        "website development"
    ]
}
```
When I search using `/twitter/_search?&q=doe AND green AND tech`, both documents are returned. However, when I search using `/twitter/_search?q=doe green tech&default_operator=and` Only the first document (`evan-smith`) is returned. According to the documentation:

> The default operator used if no explicit operator is specified. For example, with a default operator of OR, the query capital of Hungary is translated to capital OR of OR Hungary, and with default operator of AND, the same query is translated to capital AND of AND Hungary. The default value is OR.

The two queries are expected to have the same effect, but the fact is that they behaves differently when the words are in different fields of the doc, `AND` will search words across different fields but `default_operator=AND` requires all words occur in the same field.

Why? Can I search across multiple fields without manually adding `AND` between each word?

**Comment by polyfractal** [comment] 2018-02-07 19:42
Urgh, this is indeed confusing.  I'm not sure if there's a reason for this behavior, perhaps it just needs better documentation. @jimczi or @dakrone may know more.

The difference is caused by the interaction of Lucene's query parser and Elasticsearch's field expansion mechanism... and the order the ANDs are applied in.  I've rewritten your searches into query_strings for better readability and ran them through the Validate API so we can see how they translate into lucene queries.

First, if we look at the query against a single field, they yield the same thing:

```js
GET /twitter/_validate/query?explain
{
  "query": {
    "query_string": {
      "default_field": "content", 
      "query": "doe AND green AND tech"
    }
  }
}

GET /twitter/_validate/query?explain
{
  "query": {
    "query_string": {
      "default_field": "content", 
      "default_operator": "AND", 
      "query": "doe green tech"
    }
  }
}
```
```
+content:doe +content:green +content:tech
```

The issue arises when we need to start search across multiple fields.  Query string attempts to expand the query to all matching fields if there isn't a default field, but this expansion causes slightly different behavior depending on how you structure the query.

First, if we try with ANDs directly in the query:
```js
GET /twitter/_validate/query?explain
{
  "query": {
    "query_string": {
      "query": "doe AND green AND tech"
    }
  }
}
```
```
+(content.keyword:doe | name:doe | name.keyword:doe | categories:doe | content:doe | categories.keyword:doe) 
+(content.keyword:green | name:green | name.keyword:green | categories:green | content:green | categories.keyword:green) 
+(content.keyword:tech | name:tech | name.keyword:tech | categories:tech | content:tech | categories.keyword:tech)
```
Which translates into three mandatory clauses, where each clause is looking for the term in any of the fields.  Essentially, the query is parsed, finds three mandatory terms, then expands to all the fields.  E.g. we must have a document where `doe` is in any field, `green` is in any field and `tech` is in any field.

In contrast, when we use the `default_operator`:
```js
GET /twitter/_validate/query?explain
{
  "query": {
    "query_string": {
      "default_operator": "AND", 
      "query": "doe green tech"
    }
  }
}
```
```
(content.keyword:doe green tech | (+name:doe +name:green +name:tech) | name.keyword:doe green tech 
| (+categories:doe +categories:green +categories:tech) 
| (+content:doe +content:green +content:tech) | categories.keyword:doe green tech)
```
This query also has three optional clauses filled with mandatory terms.  It says we must find a document that has the terms `doe, green, tech` in one of `name`, `categories`, `content`.  The query is parsed, finds three optional terms, expands to all fields, THEN make it so at least one of the sets matches.  Which is why you end up with needing to match all in one field

All that said, if you are searching multiple fields I would just use the [Multi-Match Query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html) directly, since it gives much better control with less surprising semantics.

**Comment by mayya-sharipova** [comment] 2018-03-21 20:40
cc @elastic/es-search-aggs

Do we think that this query is  **INCORRECTLY** rewritten:

```HTTP
GET /twitter/_validate/query?explain
{
  "query": {
    "query_string": {
      "query": "doe AND green AND tech"
    }
  }
}
```
into 
```
+(content.keyword:doe | name:doe | name.keyword:doe | categories:doe | content:doe | categories.keyword:doe) 
+(content.keyword:green | name:green | name.keyword:green | categories:green | content:green | categories.keyword:green) 
+(content.keyword:tech | name:tech | name.keyword:tech | categories:tech | content:tech | categories.keyword:tech)
```

This query instead of translating to find me a document where:
 `doe` is in any field AND `green` is in any field AND  `tech` is in any field, 

should be translated into find me a document where:
`doe` AND `green` and `tech` occur together in a single field, which could be any field of the document.

**Comment by jimczi** [comment] 2018-03-21 21:08
@mayya-sharipova this is the expected in any version of es. The `query_string` parses the input around operators and analyze each piece of text independently so `doe`, `green` and `tech`are parsed separately and produce one query each which is a max disjunction over the fields that the query targets (in this case all fields since `fields` is empty). What changed in 6.x is that if you omit the operator and do `do green tech` then we will build the query for each field using this single piece of text so you'll end up with a query that requires all terms to match in a single field. This change was made to allow analyzers to see more than one term in a single analysis, previously spaces were considered operators and that breaks any multi term analysis (shingles, multi-words synonyms, ...). 
So in 6.x if you search in a `query_string` for `(new york) AND paris`, `new york` can be pass entirely to each analyzer targeted by the query. This also means that a `multi_match` query produces the same query than a `query_string` query without operator. For each piece of text (around operators) you can also choose whether you want the `cross_fields`, `best_fields` or `most_fields` mode like you would do for the entire query in a `multi_match`. 
I am going to close this issue because the behavior is expected and we changed the documentation of the `query_string` to emphasize this difference in 6.x:
https://www.elastic.co/guide/en/elasticsearch/reference/6.x/query-dsl-query-string-query.html

**Closed by jimczi** 2018-03-21 21:08 UTC
Labels: :Search/Search

**Comment by mayya-sharipova** [comment] 2018-03-21 21:30
@jimczi thanks so much for elaborating on this

**Comment by hitendrapratap** [comment] 2020-04-22 19:36
@jimczi As you suggested to use ```multi_match``` but it doesn't support advanced search like wildcard, parentheses and quotes. But these are supported by ```query_string```. Could you recommend what we could use as one stop query?
