### ISSUE TITLE
Unassigned shards during cluster start since upgrading to 1.7.1

### ISSUE THREAD

**Issue by davidvgalbraith** [elastic/elasticsearch#14149] opened 2015-10-15 23:45 UTC
Hey! I have a two-node Elasticsearch cluster that I upgraded to version 1.7.1 from 1.5.2. All my indexes have 2 shards and no replicas. Whenever I start Elasticsearch now, I get red cluster health with unassigned shards:
```
{
  "cluster_name" : "campfire.production.local",
  "status" : "red",
  "timed_out" : false,
  "number_of_nodes" : 2,
  "number_of_data_nodes" : 2,
  "active_primary_shards" : 214,
  "active_shards" : 214,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 18,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0
}
```
I tried to use the reroute API to assign them or figure out what's wrong, and this happened:
```
curl -XPOST -d '{ "commands" : [ { "allocate" : { "index" : "metadata-jut_internal@16653", "shard" : 1, "node" : "FYEkARYjQm2Bp41qVoxSUg" } } ] }' http://localhost:9200/_cluster/reroute?pretty
{
  "error" : "ElasticsearchIllegalArgumentException[[allocate] trying to allocate a primary shard [metadata-jut_internal@16653][1], which is disabled]",
  "status" : 400
}
```
I tried adding `"allow_primary": true` to the reassign command, and it assigned the shard, but when I tried to query the data from that shard I found that it had been deleted. That wasn't good. After reading https://github.com/elastic/elasticsearch/issues/14001, I reran the command without `allow_primary` but with `explain`, and here's a portion of the response for one of my indexes whose shards are unassigned:
```
        "events-jut_internal@2015.07.31" : {
          "shards" : {
            "0" : [ {
              "state" : "UNASSIGNED",
              "primary" : true,
              "node" : null,
              "relocating_node" : null,
              "shard" : 0,
              "index" : "events-jut_internal@2015.07.31",
              "unassigned_info" : {
                "reason" : "CLUSTER_RECOVERED",
                "at" : "2015-10-15T23:07:55.600Z"
              }
            } ],
            "1" : [ {
              "state" : "UNASSIGNED",
              "primary" : true,
              "node" : null,
              "relocating_node" : null,
              "shard" : 1,
              "index" : "events-jut_internal@2015.07.31",
              "unassigned_info" : {
                "reason" : "CLUSTER_RECOVERED",
                "at" : "2015-10-15T23:07:55.600Z"
              }
            } ]
```
How am I to interpret that `CLUSTER_RECOVERED` reason? How can I get my cluster back to green, preferably without losing any more data? Thanks!

**Comment by clintongormley** [comment] 2015-10-16 08:57
`CLUSTER_RECOVERED` means that the shard was marked as unassigned when you started your cluster.  All shards start off like this.

You can use the `explain` parameter to a reroute command to get explanations of why your shards are unassigned.  In this case, you have disabled allocation.

Check your cluster settings.  You need to reenable allocation.

**Closed by clintongormley** 2015-10-16 08:57 UTC

**Comment by davidvgalbraith** [comment] 2015-10-16 18:37
That's a brave little theory, but it doesn't seem to be accurate. I did
```
root@staging-llnw-de0:~$ curl -XPUT 'localhost:9200/_cluster/settings' -d '{
  "persistent": {
    "cluster.routing.allocation.enable": "all"
  }
}'
root@staging-llnw-de0:~$ curl localhost:9200/_cluster/settings
{"persistent":{"cluster":{"routing":{"allocation":{"enable":"all"}}}},"transient":{}}
root@staging-llnw-de0:/opt/jut# curl localhost:9200/_cluster/health?pretty
{
  "cluster_name" : "campfire.production.local",
  "status" : "red",
  "timed_out" : false,
  "number_of_nodes" : 2,
  "number_of_data_nodes" : 2,
  "active_primary_shards" : 214,
  "active_shards" : 214,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 18,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0
}
```
I then restarted Elasticsearch on both nodes, and the health stayed the same. Did I run the wrong command to enable allocation? Is there another possible cause of these unassigned shards?

**Comment by s1monw** [comment] 2015-10-16 18:51
can you run `GET /_cluster/reroute?explain=true` and paste the output? Can you actually tell if the shards that are not allocated exist on disk? like you have 2 nodes, do the nodes have a copy of that shard in their data dir? Can you also for the time being set logging level for `gateway` to `trace`?

**Comment by davidvgalbraith** [comment] 2015-10-16 18:57
```
root@staging-llnw-de0:/opt/jut# curl localhost:9200/_cluster/reroute?explain=true
{"error":"ElasticsearchIllegalArgumentException[No feature for name [reroute]]","status":400}
```
Doesn't seem like GET on _cluster/reroute is a real API, I did a POST there in OP and pasted a relevant section of the 2.5 MB of output I got.

**Comment by davidvgalbraith** [comment] 2015-10-16 19:17
The shards are in fact missing from my data dir! What happened to my data?

**Comment by s1monw** [comment] 2015-10-16 19:19
ok so lemme ask you some more questions? Did you delete those indices by any chance and some shards didn't get deleted so we "re-imported" it on the restart? do you use multiple data paths by any chance? can you see some mentions of dangling indices in the logs?

**Comment by davidvgalbraith** [comment] 2015-10-16 19:26
Ok so I have an index per day and a retention policy to keep the last 90 days, so the only time I delete indices is after their 90 days are up. Accordingly my indices go back to July 18, and I have the shards from July 18-30, then from July 31 to August 6 I'm missing shards, and from August 7 to today I have the shards again. There's no scenario in my application where I'd delete intermediate indices without deleting all the older indices too. What do you mean by multiple data paths? What would dangling indices look like in the logs? `grep -i dangl elasticsearch.log` returned no lines.

**Comment by s1monw** [comment] 2015-10-16 19:37
very hard to tell what's going on here.. do you have anything else in the logs that can help me to figure this out?

**Comment by davidvgalbraith** [comment] 2015-10-16 20:14
I turned on TRACE level logging for gateway and shard recovery. Here's what I find when I search for an index name whose shards got assigned successfully:
```
root@staging-llnw-de0:/opt/jut# cat data/logs/elasticsearch-kid-e0c6f82d-5da6-4815-a6ed-0de785125481/elasticsearch.log | grep events-jut_internal@2015.08.07
[2015-09-29 19:42:45,275][DEBUG][action.admin.indices.stats] [node-e0c6f82d-5da6-4815-a6ed-0de785125481] [events-jut_internal@2015.08.07][1], node[j0qBnp6BSWmi8sEh9NCP4A], [P], s[STARTED]: failed to execute [org.elasticsearch.action.admin.indices.stats.IndicesStatsRequest@291f2e34]
[2015-10-16 20:08:29,538][DEBUG][index.gateway            ] [node-e0c6f82d-5da6-4815-a6ed-0de785125481] [events-jut_internal@2015.08.07][0] starting recovery from local ...
[2015-10-16 20:08:29,539][TRACE][index.gateway.local      ] [node-e0c6f82d-5da6-4815-a6ed-0de785125481] [events-jut_internal@2015.08.07][0] using existing shard data, translog id [1439439522375]
[2015-10-16 20:08:29,539][TRACE][index.gateway.local      ] [node-e0c6f82d-5da6-4815-a6ed-0de785125481] [events-jut_internal@2015.08.07][0] try recover from translog file translog-1439439522375 locations: [/mnt/elasticsearch/campfire.production.local/nodes/0/indices/events-jut_internal@2015.08.07/0/translog]
[2015-10-16 20:08:29,539][TRACE][index.gateway.local      ] [node-e0c6f82d-5da6-4815-a6ed-0de785125481] [events-jut_internal@2015.08.07][0] Translog file found in /mnt/elasticsearch/campfire.production.local/nodes/0/indices/events-jut_internal@2015.08.07/0/translog - renaming
[2015-10-16 20:08:29,539][TRACE][index.gateway.local      ] [node-e0c6f82d-5da6-4815-a6ed-0de785125481] [events-jut_internal@2015.08.07][0] Renamed translog from translog-1439439522375 to translog-1439439522375.recovering
[2015-10-16 20:08:29,549][TRACE][index.gateway.local      ] [node-e0c6f82d-5da6-4815-a6ed-0de785125481] [events-jut_internal@2015.08.07][0] recovering translog file: /mnt/elasticsearch/campfire.production.local/nodes/0/indices/events-jut_internal@2015.08.07/0/translog/translog-1439439522375.recovering length: 17
[2015-10-16 20:08:29,550][TRACE][index.gateway.local      ] [node-e0c6f82d-5da6-4815-a6ed-0de785125481] [events-jut_internal@2015.08.07][0] ignoring translog EOF exception, the last operation was not properly written
[2015-10-16 20:08:29,552][TRACE][index.gateway            ] [node-e0c6f82d-5da6-4815-a6ed-0de785125481] [events-jut_internal@2015.08.07][0] recovery completed from local, took [13ms]
```
And here's what I find when I search for one whose shards did not get assigned:
```
root@staging-llnw-de0:/opt/jut# cat data/logs/elasticsearch-kid-e0c6f82d-5da6-4815-a6ed-0de785125481/elasticsearch.log | grep events-jut_internal@2015.08.06
root@staging-llnw-de0:/opt/jut#
```
i.e. nothing! So the gateway recovery never even thinks about my index whose shards didn't get assigned. Maybe that's something to go on?

**Comment by s1monw** [comment] 2015-10-16 20:17
man I don't know where your indices went.. I will talk to others if they can think of a bug that could have caused that...

**Comment by virHappy** [comment] 2016-01-28 07:39
so what is going on?

**Comment by davidvgalbraith** [comment] 2016-01-28 07:53
Hey @virHappy! We never found out what happened here. I hope you haven't lost data too.

**Comment by ksou1** [comment] 2016-01-29 22:57
Hi @davidvgalbraith. I'm experiencing the same issue as we speak. Have a 3 node cluster (1 dedicated master, 2 master/data nodes, set for a primary and 1 replica shard). Set "cluster.routing.allocation.enable" to "none", restarted my nodes (dedicated master 1st). All 3 nodes joined cluster properly (status yellow), so I set "cluster.routing.allocation.enable" to "all".  However, I'm sitting here 1 hour later and all of my "replica" shards are still unassigned. And.. all of my primary shards are assigned to the master/data node that happened to join the cluster first. Reroute?explain shows "CLUSTER RECOVERED" as reason, just as in your case. Will give it a while but I think next time I'll leave routing enabled and live with the thrashing that happens upon cluster start. While I really like ES and what it can do, its difficult to really rely on it with all of the "glitches".

**Comment by bleskes** [comment] 2016-01-31 20:26
@ksou1 which ES version are you using?  Also, I'm a bit confused the "CLUSTER RECOVERED" output of reroute. Can you gist the exact output?

**Comment by bleskes** [comment] 2016-01-31 20:28
scratch the last comment about `Cluster recovered`, re reading the ticket I get what you refer to (the unassigned_info part). Based on your ES version we'll see how to proceed.

**Comment by ksou1** [comment] 2016-02-01 14:06
Hi @bleskes . ES version is 1.7.2. Replicated shards finally started to allocate about 8 hours after the cluster restart. I have an index deletion script that runs at 1am every morn (to delete indexes 31 days old) and it prints a view of all indexes after the deletions. I noticed in the output that only 7 of the 218 indexes had gone to "green" status even at that point. The rest were in "yellow" status. So... after restarting the cluster at 5pm, only 7 indexes had their replica shards allocated by 1am (8 hours). By 9am the next morning, all replica's were allocated. We will be upgrading to ES 2.1.1 in the next few weeks. Keeping my fingers crossed that we dont see this delay again.

**Comment by bleskes** [comment] 2016-02-02 12:53
@ksou1 thanks. During the period the cluster was yellow - do you know the replicas were initializing (i.e., recovering) or were they unassigned?

**Comment by ksou1** [comment] 2016-02-02 14:52
Up until the time the replicas started to allocate to the second data node, they were unassigned. There were 1086 active_primary_shards, and 1086 unassigned_shards (the replicas). There were 0 initializing_shards and, strangely, 0 delayed_unassigned_shards. Cluster health also showed 0 pending_tasks and 0 in_flight_fetch.

**Comment by bleskes** [comment] 2016-02-02 15:23
I see. Do you happen to have a cluster health response ? I'm curious to see what the `number_of_in_flight_fetch` field had to say...

**Comment by bleskes** [comment] 2016-02-02 17:24
@ksou1 not sure whether you edited your comment or I just totally missed the fact that there are 0 in_flght_fetch. I this case my best guess is that you've hit https://github.com/elastic/elasticsearch/pull/14494  and something happened later on triggering another reroute..

**Comment by jessabe** [comment] 2016-03-29 14:39
@davidvgalbraith having a similar issue here as well. I'm guessing this has resulted in lost data and you've moved on, or?

**Comment by davidvgalbraith** [comment] 2016-03-29 16:06
That's right, @jessabe! Never figured out what exactly happened or what we should have done differently =\

**Comment by bleskes** [comment] 2016-03-29 19:15
@jessabe you may have the same issue (whatever it is) but it may also be different . If you give us more details we can evaluate - these are important matters.

**Comment by maziyarpanahi** [comment] 2016-03-29 22:30
Hello,

Mine is the latest ES 2.2.1 and I did my upgrade while back when it came out so I am certain it has nothing to do with my upgrade. All the members are the same config and the same version and being restarted multiple times after upgrade. 
This time I did restart each as a rollback cause I updated my elasticsearch.yml (adding repo.path which now is too late!) and 3 indexes has one unassigned shard (all the primary shards) each.
```
"details": "engine failure, reason [corrupt file (source: [flush])], failure FlushFailedEngineException[Flush failed]; nested: CorruptIndexException[verification failed : calculated=p4rbbd stored=1yztcit (resource=VerifyingIndexInput(NIOFSIndexInput(path=\"/data/iscpif-es/nodes/0/indices/scientific/3/index/_f75.cfs\")))];
```
These machines are KVM VM. I am not sure whether this is ext4 corruption and I should do fsck or a bug some where in Lucene/ES.

**Comment by nathan-zhu** [comment] 2016-07-08 07:11
@davidvgalbraith i got same problem on ES 2.3 in docker, the issue is here #19323 it said i don't have enough disk space for allocation to reroute, not sure this will help something.

**Comment by emanzaman** [comment] 2018-09-04 05:09
Hi, I am facing the same issue:
1. Restarted my elastic search cluster from one node to three nodes. But the cluster status is now red as shown below:
`$> curl "localhost:9200/_cat/health"
1536037434 06:03:54 graylog-uat red 3 2 13 12 0 0 1 0 - 92.9%
`
2. After some investigation, I landed upon the cluster allocation API and here is the output:
`$> curl -X GET "localhost:9200/_cluster/allocation/explain?pretty=true"
{
  "index" : "graylog_0",
  "shard" : 0,
  "primary" : true,
  "current_state" : "unassigned",
  "unassigned_info" : {
    "reason" : "CLUSTER_RECOVERED",
    "at" : "2018-09-03T12:15:27.463Z",
    "last_allocation_status" : "no_valid_shard_copy"
  },
  "can_allocate" : "no_valid_shard_copy",
  "allocate_explanation" : "cannot allocate because a previous copy of the primary shard existed but can no longer be found on the nodes in the cluster",
  "node_allocation_decisions" : [
    {
      "node_id" : "8W_0X_3UTY6twG7ZssfdTg",
      "node_name" : "nodeB",
      "transport_address" : "11.193.165.94:9301",
      "node_decision" : "no",
      "store" : {
        "found" : false
      }
    },
    {
      "node_id" : "c_K4VUSCQk-QV1mlquurhA",
      "node_name" : "nodeA",
      "transport_address" : "11.195.33.52:9301",
      "node_decision" : "no",
      "store" : {
        "found" : false
      }
    }
  ]
}
3. I can also see, in the log below, the index 'graylog_0' getting deleted. If such is the case why is ES even searching for the said index.   
`
`$> zgrep "graylog_0" *
elasticsearch-2018-08-30.log.gz:2018-08-30 08:19:45,493 | INFO  | o.e.c.r.a.AllocationService | Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[graylog_0][0]] ...]).
elasticsearch-2018-08-30.log.gz:2018-08-30 13:25:11,234 | INFO  | o.e.c.m.MetaDataDeleteIndexService | [graylog_0/HO0jj6QwTUmVaJn3OZQyZQ] deleting index
`
Elasticsearch version: 5.6.8
