### ISSUE TITLE
List primary copy of each shard first in output of routing table

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#14123] opened 2015-10-14 21:28 UTC
The routing table returned from our apis (like _status) seem to list the copies of a single shard sorted by the node_id.  So the primary copy can appear anywhere in the list, sometimes as the first copy in the list, sometimes as the last copy in the list.  This causes some issues in monitoring scripts I have seen out there where they are expecting the first copy of the shard listed to be the primary copy.  While it is an easy fix in the monitoring script, it may actually be nice if we consistently present the primary copy as the first item in the list of copies.

Example of a shard that has 3 copies (2 replicas):
```
"1" : [ {
          "routing" : {
            "state" : "STARTED",
            "primary" : false,
            "node" : "CUWZHwwjREGElE9zu_PNIg",
            "relocating_node" : null,
            "shard" : 1,
            "index" : "awareness"
          }
        }, {
          "routing" : {
            "state" : "STARTED",
            "primary" : false,
            "node" : "lzBXmSxyScyit_BOMaH4yw",
            "relocating_node" : null,
            "shard" : 1,
            "index" : "awareness"
          }        }, {
          "routing" : {
            "state" : "STARTED",
            "primary" : true,
            "node" : "TFxkZt-lSz-hs-tqGCcdkg",
            "relocating_node" : null,
            "shard" : 1,
            "index" : "awareness"
          }
        } ],
```

**Comment by clintongormley** [comment] 2015-10-15 13:14
Seems reasonable - I assume this wouldn't be too expensive?

**Comment by jasontedor** [comment] 2015-10-15 13:36
I would think for monitoring it would be better to be using `_cat/shards` which is much more amenable to sorting. For example:

    curl -sS -XGET localhost:9200/_cat/shards?h=index,shard,prirep,state,id | sort -k3

The problem is that the routing table is backed by a specialized hash map where iteration isn't amenable to sorting.

**Comment by ppf2** [comment] 2015-10-15 17:18
Thanks @jasontedor .  In this case, the user is on Windows and using powershell's convert-to-json functionality which makes it easy to iterate the json output and has a pretty complete set of monitoring scripts based on the non-cat apis.  It's certainly easy to update those scripts to workaround this behavior though.  So this is just to gauge the level of effort for us to display the primary copy first which may benefit other folks who use the non-cat apis. Certainly not a high priority item to address, just something nice to have if we have spare time :)

**Comment by bleskes** [comment] 2015-10-15 17:56
@jasontedor I quickly glanced at things - so I might be missing something but isn't this a question of sorting the shard list in the IndexShardRoutingTable constructor/builder: https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/cluster/routing/IndexShardRoutingTable.java#L77

This list is super short, so the overhead should be negligible....

**Comment by jasontedor** [comment] 2015-10-16 09:12
We discussed this during fix-it-Friday and have come to the conclusion to not favor any one particular sort order over any other. Since it is not difficult to sort externally (especially with the `_cat/shards` API), we will close this issue as won't-fix.

**Closed by jasontedor** 2015-10-16 09:12 UTC
Labels: :Stats, discuss, enhancement
