### ISSUE TITLE
SQL: order by Multiple columns expression error when aggregation 

### ISSUE THREAD

**Issue by chen-ABC** [elastic/elasticsearch#73361] opened 2021-05-25 11:57 UTC
success example
```
SELECT supplier_name AS supplier_name,
       SUM(fee_of_purchase) AS "total"
FROM "default".supplier_store_product_income_log_m_202105
GROUP BY supplier_name
ORDER BY "total" DESC
LIMIT 50;
```

error example
```
SELECT supplier_name AS supplier_name,
       SUM(income_of_sales_real_regular)+SUM(income_of_sales_real_store_clearance)AS "total"
FROM "default".supplier_store_product_income_log_m_202105
GROUP BY supplier_name
ORDER BY "total" DESC
LIMIT 50;

elasticsearch error: Error (verification_exception): Found 1 problem(s) line 9:10: Cannot order by non-grouped column [total], expected [supplier_name] or an aggregate function
```

elasticsearch version: 6.7.1

**Comment by matriv** [comment] 2021-05-26 11:22
Reproduced on master, we currently not allow to order by on scalar functions (in this example: `+` operator) applied on top aggregate functions (in this example: `SUM`).

**Comment by matriv** [comment] 2021-05-26 11:24
Closing though, as a duplicate of: #52206

**Comment by matriv** [comment] 2021-05-26 11:25
Closing though, as a duplicate of: #52206

**Closed by matriv** 2021-05-26 11:25 UTC
Labels: :Query Languages/SQL, >bug, Team:QL
