### ISSUE TITLE
[CI] PasswordToolsTests test20GeneratePasswords failing

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#74063] opened 2021-06-14 12:10 UTC
Password generation test failed due to RED cluster.

**Build scan:**
https://gradle-enterprise.elastic.co/s/2hcjgskisrgfa/tests/:qa:os:destructiveDistroTest.default-deb/org.elasticsearch.packaging.test.PasswordToolsTests/test20GeneratePasswords

**Reproduction line:**
`null`

**Applicable branches:**
7.13

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.packaging.test.PasswordToolsTests&tests.test=test20GeneratePasswords

**Failure excerpt:**
```
java.lang.RuntimeException: Command was not successful: [bash -c "/usr/share/elasticsearch/bin/elasticsearch-setup-passwords" auto --batch]
   result: exitCode = [75] stdout = [] stderr = [Your cluster health is currently RED.
This means that some cluster data is unavailable and your cluster is not fully functional.

It is recommended that you resolve the issues with your cluster before running elasticsearch-setup-passwords.
It is very likely that the password changes will fail when run against an unhealthy cluster.


Unexpected response code [503] from calling PUT http://127.0.0.1:9200/_security/user/apm_system/_password?pretty
Cause: Cluster state has not been recovered yet, cannot write to the [null] index

Possible next steps:
* Try running this tool again.
* Try running with the --verbose parameter for additional messages.
* Check the elasticsearch logs for additional error details.
* Use the change password API manually. 

ERROR: Failed to set password for user [apm_system].]

  at __randomizedtesting.SeedInfo.seed([1A7E9CD900E3073B:F873AC21EBC82A08]:0)
  at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:147)
  at org.elasticsearch.packaging.util.Shell.run(Shell.java:73)
  at org.elasticsearch.packaging.util.Installation$Executable.run(Installation.java:174)
  at org.elasticsearch.packaging.test.PasswordToolsTests.lambda$test20GeneratePasswords$0(PasswordToolsTests.java:55)
  at org.elasticsearch.packaging.test.PackagingTestCase.assertWhileRunning(PackagingTestCase.java:270)
  at org.elasticsearch.packaging.test.PasswordToolsTests.test20GeneratePasswords(PasswordToolsTests.java:54)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at java.lang.Thread.run(Thread.java:748)

```

**Comment by mark-vieira** [comment] 2021-06-14 20:31
Strange, since the root cause here was just the cluster not coming up properly and there's only been a single instance of this failure I'm apt to chaulk this up to solar flares. Let's keep it open for a few days in any case though.

**Comment by davidkyle** [comment] 2021-06-21 15:53
Another instance this time on master: https://gradle-enterprise.elastic.co/s/qkj5fl7afm4ma

Must be those solar flares again or maybe the test just doesn't like Mondays

**Comment by mark-vieira** [comment] 2021-06-21 16:09
Anyone from @elastic/es-security able to provide some insight here? Any idea what would cause such an error?

```
org.elasticsearch.ElasticsearchStatusException: Cluster state has not been recovered yet, cannot write to the [null] index
	at org.elasticsearch.xpack.security.support.SecurityIndexManager.prepareIndexIfNeededThenExecute(SecurityIndexManager.java:328) [x-pack-security-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.xpack.security.authc.esnative.NativeUsersStore.changePassword(NativeUsersStore.java:237) [x-pack-security-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.xpack.security.action.user.TransportChangePasswordAction.doExecute(TransportChangePasswordAction.java:55) [x-pack-security-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.xpack.security.action.user.TransportChangePasswordAction.doExecute(TransportChangePasswordAction.java:25) [x-pack-security-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:77) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.action.support.ActionFilter$Simple.apply(ActionFilter.java:42) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:75) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$applyInternal$3(SecurityActionFilter.java:160) [x-pack-security-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
```

**Comment by ywangd** [comment] 2021-06-22 01:04
I don't think there is anything specific to security code. The error message shows that the security index name is still `null`. This means the node has never recieved any `ClusterChangedEvent`, i.e. it never had the chance to join a cluster. It is either a setup issue or transient solar flare ...

**Comment by tvernum** [comment] 2021-06-22 01:18
The message generation has a bug (that we really should have fixed by now, but it always comes up during investigations of a different root issue so it gets pushed to the side).

Security operates on an alias that points to the true underlying index. Normally, we throw an exception we attempt to include the concrete index name - it is more useful to get a message saying that a real index is unavailable than an alias (which the admin then needs to manually resolve to find out which index is missing).
However, if the cluster state is not yet available we generally won't know what the alias points to (because that's stored in cluster state), so the message building writes a `null`. We shouldn't do that - I think we should just use the alias if the index name isn't yet known.

Ignoring that `null`, the root cause here is pretty much what it says.  
The `SecurityIndexManager` listens to cluster events and tracks the state of the security index (*). The initial state for the tracking is `UNRECOVERED_STATE` which indicates that this class (on this node) has not yet received a cluster event that provides index metadata. This error indicates that we (`NativeUsersStore` in response to a change password request) tried to write to the index while it was still in that unrecovered state.

* (*) Or, in some cases, the security-tokens index. Security uses 2 system indices, and there is an instance of the `SecurityIndexManager` for each one. However, the `NativeUsersStore` only interacts with the `.security` index, so we know  that this error must be due to the main security index.

That's more or less expected. Some security classes look at the index state directly and respond in specific ways when the index is not available, but typically there's nothing we can do except fail, so most code paths just end up in this check that will throw this exception.  

It doesn't look like the cluster itself had any problems forming:
```
[2021-06-21T11:12:33,019][INFO ][o.e.c.c.Coordinator      ] [elasticsearch-ci-immutable-debian-9-pkg-1624273535255629315] setting initial configuration to VotingConfiguration{PN-HNzLfRrCR_LBWHVzGLg}	
[2021-06-21T11:12:33,180][INFO ][o.e.c.s.MasterService    ] [elasticsearch-ci-immutable-debian-9-pkg-1624273535255629315] elected-as-master ([1] nodes joined)[{elasticsearch-ci-immutable-debian-9-pkg-1624273535255629315}{PN-HNzLfRrCR_LBWHVzGLg}{LnXhiru_RDqvqeB75deBKA}{127.0.0.1}{127.0.0.1:9300}{cdfhilmrstw} elect leader, _BECOME_MASTER_TASK_, _FINISH_ELECTION_], term: 1, version: 1, delta: master node changed {previous [], current [{elasticsearch-ci-immutable-debian-9-pkg-1624273535255629315}{PN-HNzLfRrCR_LBWHVzGLg}{LnXhiru_RDqvqeB75deBKA}{127.0.0.1}{127.0.0.1:9300}{cdfhilmrstw}]}	
[2021-06-21T11:12:33,230][INFO ][o.e.c.c.CoordinationState] [elasticsearch-ci-immutable-debian-9-pkg-1624273535255629315] cluster UUID set to [HkhxxqlBTr2DeKqfcu2ICQ]	
[2021-06-21T11:12:33,259][INFO ][o.e.c.s.ClusterApplierService] [elasticsearch-ci-immutable-debian-9-pkg-1624273535255629315] master node changed {previous [], current [{elasticsearch-ci-immutable-debian-9-pkg-1624273535255629315}{PN-HNzLfRrCR_LBWHVzGLg}{LnXhiru_RDqvqeB75deBKA}{127.0.0.1}{127.0.0.1:9300}{cdfhilmrstw}]}, term: 1, version: 1, reason: Publication{term=1, version=1}	
```
So I suspect this is just a timing issue. The cluster had just formed, but the relevant cluster events had not been published to the `SecurityIndexManager` yet.

It's possible that there's a bug somewhere that is causing the events to get lost, but the tool itself reports `Your cluster health is currently RED.` and that comes from looking at the [cluster health API](https://github.com/elastic/elasticsearch/blob/68817d7ca29c264b3ea3f766737d81e2ebb4028c/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/esnative/tool/SetupPasswordTool.java#L408-L437), I think the most likely explanation is that we aren't waiting long enough (or checking the right things) before we try and run this packaging test.

`elasticsearch-setup-passwords` shouldn't be run against a red cluster. It will almost certainly fail (hence the health check). So, I think the problem here is that the test relies on `PackagingTestCase.awaitElasticsearchStartup` but that only waits for a pid file which doesn't guarantee that the cluster has actually formed.  
So, we could either change the packaging test to wait for a healthy cluster, or change the test to not care whether the password change works or not.
The latter is a fair option in this case because this is a packaging test - its purpose it to ensure that the CLI tool is installed correctly and the controlling shell scripts don't have errors, etc. Testing the core functionality of the tool is handled elsewhere. From a packaging point of view, as long as it connected to ES correctly (and authenticating with the bootstrap password worked), the actual password change is irrelevant.

**Comment by mark-vieira** [comment] 2021-06-22 18:07
> The latter is a fair option in this case because this is a packaging test - its purpose it to ensure that the CLI tool is installed correctly and the controlling shell scripts don't have errors, etc.

Yeah, this gets to be tricky because really we're just looking for a non-zero exit code here and that gets hard to differentiate between "the server returned an error" or "the tool is busted".

I think hardening this test to wait for a green cluster is the better option here. We'll look into this.

**Closed** 2021-07-21 08:42 UTC
Labels: :Delivery/Packaging, >test-failure, Team:Delivery
