### ISSUE TITLE
Limitation of nested aggregations - Need ability to access owner fields from nested aggregations

### ISSUE THREAD

**Issue by roytmana** [elastic/elasticsearch#16642] opened 2016-02-12 16:33 UTC
Currently it is impossible to access owner's fields from a nested aggregation. So it is not possible to do following:

* Bucket aggregations on them (a very common use case) as a sub aggregation of  the nested one. For example If multiple lawyers are assigned to cases of different types and each assignment captures his/her hours spent and report needs to be total hours by lawyer by case type. It is impossible to do so. Using reverse_nested and back will not produce desired results 
* Filter on owner's fields within aggregations. 
* Metrics aggregations on owner's fields are a little less useful as there will be double-counting but often are necessary as well

**Comment by clintongormley** [comment] 2016-02-13 11:50
@roytmana could you please provide examples of what you are trying to achieve (and what can't be achieved by simply including the required parent field in the nested doc itself)?

I'm sure that you are aware that nested docs are separate docs from the parent, so accessing the parent from the nested doc would be prohibitively expensive.

**Comment by roytmana** [comment] 2016-02-14 16:08
Hello @clintongormley 

The example below is just a small example to demonstrate the issue. In real life I have a number of nested (sometimes twice) of fields in the main object and the main object has hundreds of properties. I cannot embed all the parent object's properties into nested child objects because it is an entirely dynamic system and users can craft any kind of query or aggregation on any combination of properties. It would be impractical to repeat all parent (owner) properties in the nested child not to mention that the JSON is not for searching and aggregation only it is heavily used by other systems and other reports.

Of course I understand that nested is a separate document and price of accessing parent may not be trivial but it is lot less expensive than in parent/child and in context of aggregation it could be optimized nicely if parent aggregation is on the owner object so it is already loaded and available within child aggregations. Also if trying to work around it with reverse nested aggregation incurs cost of fetching owner objects anyway (and does not work as you can see in example below).

I think allowing access to parent fields using something like ../parentProperty would be terrific feature in supporting cases that otherwise required messy, inefficient and often very much unwanted denormalization 

All the issues could be in some form worked around if you are hand-crafting a specific query and can modify your json on a dime (by bringing in needed parent properties into a nested field) just to satisfy your query. But in dynamic systems where queries are not known upfront and where JSON structure needs to be kept stable or versioned carefully it is just not possible 

Imagine having Teams that handle Requests of certain Priority. Each request may have multiple teams assigned to it and each team request assignment has number of hours allocated for this team on a request:
 
```javascript
request:{
  priority:1,
  teams:[
    {name:'team1', hours:10},
    {name:'team2', hours:20},
  ]
}
```

Let's try to produce a report that gives number of hours by team by priority. Doing nested aggregation on **teams.name** and then reverse nested to group on **priority** and then nested to sum **teams.hours** double-counts hours because second nesting on teams knows nothing about  upstream nesting as it is executed in context of request and as result it will lump hours for each team on request under the top level team aggregation 

If i could access "../priority" from teams nested document context I would not have to use reverse nested and lose my aggregation context and everything would have worked like a charm

Similar case with filter aggregation - it is not possible to add any filtering logic on parent fields to it. While it is possible to put that logic into parent agg on the owner document it will only work with simple single purpose queries. Complex queries with multiple filters as sub aggs often have conflicting criteria in the filters (ex. each filter agg segments out a portion of docs based on parent's properties) forcing the aggregation to be split onto multiple queries and then re-aggregated  on the client. It could be non trivial if it is happening within some multi-bucket aggs

Thank you,
Alex

**Comment by clintongormley** [comment] 2016-02-15 12:26
This issue is pretty much a duplicate of #16642, so I'll close this one in favour of the other

**Closed by clintongormley** 2016-02-15 12:26 UTC
Labels: :Aggregations, discuss, feedback_needed

**Comment by roytmana** [comment] 2016-02-15 16:16
@clintongormley you are sating "This issue is pretty much a duplicate of #16642, so I'll close this one in favour of the other" but this is the #16642 I think you have already closed the other one

**Comment by clintongormley** [comment] 2016-02-15 16:18
Sorry, I meant #16380

**Comment by Pendu** [comment] 2020-05-23 21:38
This problem is not solved. The two tickets are referring to each other...

#16380 and #16642

> Sorry, I meant #16380
