### ISSUE TITLE
SQL: Consider using stored_fields for "store: true, index: false" mapped fields

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#30259] opened 2018-04-30 13:12 UTC
Currently a stored, not indexed field is not returned at all:

```
DELETE library
PUT library
{
  "mappings": {
    "book": {
      "properties": {
        "author": {
          "type": "text"
        },
        "name": {
          "type": "text",
          "fields": {
            "not_indexed": {
              "type": "text",
              "index": false,
              "store": true
            }
          }
        }
      }
    }
  }
}

POST /_xpack/sql?format=json
{
  "query":"select name.not_indexed as name_not_indexed from library where match(name,'hyperion')"
}

{
  "columns": [
    {
      "name": "name_not_indexed",
      "type": "text"
    }
  ],
  "rows": [
    [
      null
    ]
  ]
}
```

But, Elasticsearch does offer a way to return those not indexed, stored fields using [`stored_fields`](https://www.elastic.co/guide/en/elasticsearch/reference/6.x/mapping-store.html#mapping-store):

```
GET /library/_search
{
  "query": {
    "match_all": {}
  },
  "_source": {
    "includes": ""
  },
  "stored_fields": ["name.not_indexed"]
}
```

**Comment by costin** [comment] 2018-05-25 17:52
The decision in this case was to always use the stored field (as oppose to the source) if stored has appeared in the mapping.

**Comment by bpintea** [comment] 2020-10-12 11:20
This seems to no longer (@7.9.0) reproduce. (Assuming the `book` field in the example as unintended).

**Comment by bpintea** [comment] 2020-10-15 10:38
Closing as no longer applicable, please reopen on reoccurrence.

**Closed by bpintea** 2020-10-15 10:38 UTC
Labels: :Query Languages/SQL, >enhancement, Team:QL
