### ISSUE TITLE
/_cat /_all /_cluster APIs not working after upgrade.

### ISSUE THREAD

**Issue by ignaciovazquez** [elastic/elasticsearch#9713] opened 2015-02-17 01:16 UTC
I've just finished upgrading ES from version 1.3.2 to 1.4.3.

After restarting the node 
The /_cat/, /_all/, /_cluster/ APIs have stopped working. 
Any request sent to those endpoints just hangs there.

/_status works fine and the indices look like they are working properly. 

This is the only ES instance in the cluster.

Any ideas?

```
[2015-02-16 16:57:52,298][INFO ][node                     ] [Hawkeye II] version[1.4.3], pid[29600], build[36a29a7/2015-02-11T14:23:15Z]
[2015-02-16 16:57:52,299][INFO ][node                     ] [Hawkeye II] initializing ...
[2015-02-16 16:57:52,312][INFO ][plugins                  ] [Hawkeye II] loaded [river-rss], sites []
[2015-02-16 16:57:55,435][INFO ][node                     ] [Hawkeye II] initialized
[2015-02-16 16:57:55,436][INFO ][node                     ] [Hawkeye II] starting ...
[2015-02-16 16:57:55,588][INFO ][transport                ] [Hawkeye II] bound_address {inet[/0.0.0.0:9300]}, publish_address {inet[/192.168.141.202:9300]}
[2015-02-16 16:57:55,599][INFO ][discovery                ] [Hawkeye II] egocluster/C7eUOp2CSf6HbTJPQCXcHA
[2015-02-16 16:57:58,622][INFO ][cluster.service          ] [Hawkeye II] new_master [Hawkeye II][C7eUOp2CSf6HbTJPQCXcHA][li509-129][inet[/192.168.141.202:9300]], reason: zen-disco-join (elected_as_master)
[2015-02-16 16:57:58,740][INFO ][http                     ] [Hawkeye II] bound_address {inet[/0.0.0.0:9200]}, publish_address {inet[/192.168.141.202:9200]}
[2015-02-16 16:57:58,740][INFO ][node                     ] [Hawkeye II] started
```

**Comment by ignaciovazquez** [comment] 2015-02-17 01:26
It looks like /_cat/count and /_cat/recovery are working fine, though.

Here's elasticsearch.yml:

```
bootstrap.mlockall: true
cluster.name: egocluster
discovery.zen.ping.multicast.enabled: false
indices.recovery.max_bytes_per_sec: 500mb
network.host: 127.0.0.1
```

**Comment by dadoonet** [comment] 2015-02-17 01:46
I think that it's caused by the plugin you are using.
Could you open an issue in RSS river project ?

**Comment by ignaciovazquez** [comment] 2015-02-17 02:00
You are right, it was the RSS river plugin.

Thanks,

**Comment by dadoonet** [comment] 2015-02-17 07:49
Actually it happens since 1.4 with every river but it's hard to reproduce locally.
For now, I'm trying to fix that in all Rivers but it might be something we could/should fix in es core itself.

I hope I could reproduce it locally with RSS River. :)

**Comment by ignaciovazquez** [comment] 2015-02-17 13:53
Thanks!

Is there any way I can help you reproduce / debug the problem?

Ignacio

**Comment by ignaciovazquez** [comment] 2015-03-03 21:20
Hi,

Is this something you are able to fix or shall we look into RSS River alternatives?

Thanks!

**Comment by dadoonet** [comment] 2015-03-03 21:30
You should consider logstash rss input plugin. RSS river is on my TODO list but TBH I don't have enough time to fix and release those days.

**Comment by dadoonet** [comment] 2015-06-03 15:21
I'm going to close this one as it was most likely caused by the RSS river.
Note that rivers have been deprecated now and will disappear in the future.

**Closed by dadoonet** 2015-06-03 15:21 UTC
