### ISSUE TITLE
Setting the slowlog log level has no effect with 1.4.2

### ISSUE THREAD

**Issue by cmeury** [elastic/elasticsearch#10338] opened 2015-03-31 09:58 UTC
On a ES 1.4.2 cluster, I am trying to transiently set the log level of search slowlogs via the API:

````bash
curl -s -XPUT 'http://localhost:9200/_cluster/settings' -d '
{
    "transient" : {
        "logger.index.search.slowlog.query" : "INFO"
    }
}'
````

I confirmed that the transient setting is stored in the cluster with a GET on the same path.

However I still have many DEBUG log events in my slowlogs. What am I doing wrong? Is this a known issue?

**Comment by clintongormley** [comment] 2015-04-05 13:25
@cmeury I wonder if the debug events are really fetch events?

Try setting `logger.index.search.slowlog` instead?

**Comment by cmeury** [comment] 2015-04-07 14:18
No, the log entries are shown with ".query". I configured like this:


```bash
curl -s -XPUT 'http://localhost:9200/_cluster/settings' -d '
{
    "transient" : {
        "logger.index.search.slowlog.query" : "INFO"
    }
}'
````

It was acknowledged and showed up when GETting the settings, but I still have entries like this in the slowlog file:

```
[2015-04-07 13:45:39,948][DEBUG][index.search.slowlog.query] [hostname] [posts][1] took[762.7ms], took_millis[762], types[post], ...
````

I tried setting `logger.index.search.slowlog` to `INFO` as well, did not change anything. Isn't it hierarchical anyway?

**Comment by clintongormley** [comment] 2016-01-14 14:11
Duplicate of #7461

**Closed by clintongormley** 2016-01-14 14:11 UTC
Labels: :Logging, adoptme, bug
