### ISSUE TITLE
Monitoring: Transform script in elasticsearch_cluster_status.json results in ArrayOutOfBoundsException

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#33649] opened 2018-09-12 20:30 UTC
With monitoring enabled, when a cluster becomes yellow/red there is the possibility of the transform script in the monitoring watch elasticsearch_cluster_status.json resulting in an ArrayOutOfBoundsException.  Two indices are searched against .monitoring-es-* and .monitoring-alerts-6 for information required to use watcher to send an appropriate email related to changes in cluster status.  The condition script ensures that the searches contain results prior to being accessed, but the transform script does not.  Guards should be added to ensure the exception does not occur in the transform script.  However, this is not necessarily simple because without information from the es index it's not possible to know whether the cluster is red/yellow.

This is being seen in production for a number of customers.  But it should be noted that if a cluster is yellow/red this is only a symptom and not the actual problem the cluster may be experiencing.

**Comment by nerophon** [comment] 2018-11-29 12:21
I've experienced this bug in a production deployment recently; so it is still current as of 6.5.1.

**Comment by jakelandis** [comment] 2019-10-06 21:17
This is a duplicate of https://github.com/elastic/elasticsearch/issues/43184 . Closing this one in favor of the other.

**Closed by jakelandis** 2019-10-06 21:17 UTC
Labels: :Core/Features/Watcher, >bug
