### ISSUE TITLE
[CI] TestClustersPluginIT.testMultiNode failure

### ISSUE THREAD

**Issue by henningandersen** [elastic/elasticsearch#41256] opened 2019-04-16 13:38 UTC
This test failed on my master[ PR build](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/12124/testReport/). I have not been able to reproduce it locally. Unsure if it relates to #37889.

This seems to be the primary problem:
```
[2019-04-16T09:36:36,076][WARN ][o.e.c.NodeConnectionsService] [multiNode-3] failed to connect to {multiNode-1}{76UnrzNcSQCGO2byg8l0-g}{pWe_gZtjS_22EyAtKnzMDA}{127.0.0.1}{127.0.0.1:33513}{testattr=test, ml.machine_memory=63323983872, ml.max_open_jobs=20, xpack.installed=true} (tried [1] times)
  org.elasticsearch.transport.ConnectTransportException: [multiNode-1][127.0.0.1:33513] connect_exception
  	at org.elasticsearch.transport.TcpTransport$ChannelsConnectedListener.onFailure(TcpTransport.java:956) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  	at org.elasticsearch.action.ActionListener.lambda$toBiConsumer$3(ActionListener.java:161) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  ```
leading to:
```
`cluster{::multiNode}` failed to wait for cluster health yellow after 40 SECONDS
```

[testMultiNode.zip](https://github.com/elastic/elasticsearch/files/3085093/testMultiNode.zip)

**Comment by atorok** [comment] 2019-04-18 05:48
I tried to reproduce this both locally and on an identical worker but it won't reproduce. 
There's not much to go by  from the logs., I don't see why the nodes wouldn't be able to talk to each-other. Will try some more to reproduce with the entire suite.

**Comment by henningandersen** [comment] 2019-04-24 12:24
This test failed again on my PR build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/12570/testReport/org.elasticsearch.gradle.testclusters/TestClustersPluginIT/testMultiProject/

Looks like a similar but not identical error:
```
> `cluster{:bravo:myTestCluster}` failed to wait for cluster health yellow after 40 SECONDS
```

Will leave test unmuted for now and retry PR.

**Comment by henningandersen** [comment] 2019-04-25 12:57
Once more, seems it fails on every PR I do:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/12727/testReport/

**Comment by henningandersen** [comment] 2019-04-29 15:17
Once again here: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/12965/testReport/

**Comment by henningandersen** [comment] 2019-04-29 18:04
Turns out the last failures were for `testMultiProject`. `testMultiNode` is still muted.

Muted `testMultiProject` in 40216b4eca96121d85e76c7a0a263bd5e747a170

**Comment by droberts195** [comment] 2019-05-08 11:22
Both the affected tests are failing again:

* `testMultiNode` in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/13551/testReport/
* `testMultiProject` in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/13545/testReport/

**Comment by atorok** [comment] 2019-05-08 14:24
@droberts195  can you merge master in and try again please ? I added additional logging to see what the issue is.

**Comment by droberts195** [comment] 2019-05-08 15:38
My PR is merged now, as I managed to get a green build after rerunning the tests - they got assigned to an Ubuntu worker on the run that succeeded.  I see that both the workers that had problems for my PR have been replaced in Jenkins.  So maybe there was something dodgy about those Debian workers.

**Comment by droberts195** [comment] 2019-05-09 11:33
@atorok was fa98c5ec60f4ea38785f1b598d3bcddb5c6085be the commit with the extra logging?  If so a failure of `TestClustersPluginIT.testMultiNode` containing that is https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/13576/testReport/

That build also ran on a Debian worker...

**Comment by atorok** [comment] 2019-05-09 13:15
That's the right commit, but I'm not seeing the additional logs I was expecting

**Comment by atorok** [comment] 2019-05-09 14:31
muted in 54f7113b2e8

**Comment by henningandersen** [comment] 2019-06-10 10:08
Backported muting of testMultiProject to 7.1.

**Closed** 2019-09-30 07:23 UTC
Labels: :Core/Infra/Build, >test-failure
