### ISSUE TITLE
Unable to run Elasticsearch (2.2.0) windows service

### ISSUE THREAD

**Issue by habibcs** [elastic/elasticsearch#16528] opened 2016-02-09 09:34 UTC
Hi,

Installed the service from zip (windows 8.1 professional - developer machine) with all default options.
JVM is present and all settings seems to be alright.

**- service install -> installs perfectly**
**- service manager (then start - argument: start) -> service starts and then stops (logging mode set to Debug)**

**elasticsearch-service-x64-stderr.2016-02-09.log** =>
2016-02-09 10:00:32 Commons Daemon procrun stderr initialized
Java HotSpot(TM) 64-Bit Server VM warning: Using the ParNew young collector with the Serial old collector is deprecated and will likely be removed in a future release
Exception in thread "main" tstrap.Bootstrap.init(Bootstrap.java:248)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details

**elasticsearch-service-x64.2016-02-09.log** =>
[2016-02-09 10:00:32] [debug] ( prunsrv.c:1679) [ 8288] Commons Daemon procrun log initialized
[2016-02-09 10:00:32] [info]  ( prunsrv.c:1683) [ 8288] Commons Daemon procrun (1.0.15.0 64-bit) started
[2016-02-09 10:00:32] [info]  ( prunsrv.c:1596) [ 8288] Running 'elasticsearch-service-x64' Service...
[2016-02-09 10:00:32] [debug] ( prunsrv.c:1374) [ 5200] Inside ServiceMain...
[2016-02-09 10:00:32] [debug] ( prunsrv.c:844 ) [ 5200] reportServiceStatusE: 2, 0, 3000, 0
[2016-02-09 10:00:32] [info]  ( prunsrv.c:1127) [ 5200] Starting service...
[2016-02-09 10:00:32] [debug] ( javajni.c:233 ) [ 5200] loading jvm 'C:\Program Files\Java\jdk1.8.0_11\jre\bin\server\jvm.dll'
[2016-02-09 10:00:32] [debug] ( javajni.c:704 ) [ 8444] Jvm Option[0] -XX:+UseParNewGC
[2016-02-09 10:00:32] [debug] ( javajni.c:704 ) [ 8444] Jvm Option[1] -Xms256m
[2016-02-09 10:00:32] [debug] ( javajni.c:704 ) [ 8444] Jvm Option[2] -Xmx1g
[2016-02-09 10:00:32] [debug] ( javajni.c:704 ) [ 8444] Jvm Option[3] -Djava.awt.headless=true
[2016-02-09 10:00:32] [debug] ( javajni.c:704 ) [ 8444] Jvm Option[4] -XX:+UseCMSInitiatingOccupancyOnly
[2016-02-09 10:00:32] [debug] ( javajni.c:704 ) [ 8444] Jvm Option[5] -XX:+HeapDumpOnOutOfMemoryError
[2016-02-09 10:00:32] [debug] ( javajni.c:704 ) [ 8444] Jvm Option[6] -XX:+DisableExplicitGC
[2016-02-09 10:00:32] [debug] ( javajni.c:704 ) [ 8444] Jvm Option[7] -Dfile.encoding=UTF-8
[2016-02-09 10:00:32] [debug] ( javajni.c:704 ) [ 8444] Jvm Option[8] -Djna.nosys=true
[2016-02-09 10:00:32] [debug] ( javajni.c:704 ) [ 8444] Jvm Option[9] -Delasticsearch
[2016-02-09 10:00:32] [debug] ( javajni.c:704 ) [ 8444] Jvm Option[10] -Des.path.home=C:\LogAggregator\elasticsearch
[2016-02-09 10:00:32] [debug] ( javajni.c:704 ) [ 8444] Jvm Option[11] -Des.default.path.home=C:\LogAggregator\elasticsearch
[2016-02-09 10:00:32] [debug] ( javajni.c:704 ) [ 8444] Jvm Option[12] -Des.default.path.logs=C:\LogAggregator\elasticsearch\logs
[2016-02-09 10:00:32] [debug] ( javajni.c:704 ) [ 8444] Jvm Option[13] -Des.default.path.data=C:\LogAggregator\elasticsearch\data
[2016-02-09 10:00:32] [debug] ( javajni.c:704 ) [ 8444] Jvm Option[14] -Des.default.path.conf=C:\LogAggregator\elasticsearch\config
[2016-02-09 10:00:32] [debug] ( javajni.c:704 ) [ 8444] Jvm Option[15] -Djava.class.path=C:\LogAggregator\elasticsearch/lib/elasticsearch-2.2.0.jar;C:\LogAggregator\elasticsearch/lib/antlr-runtime-3.5.jar;C:\LogAggregator\elasticsearch/lib/apache-log4j-extras-1.2.17.jar;C:\LogAggregator\elasticsearch/lib/asm-4.1.jar;C:\LogAggregator\elasticsearch/lib/asm-commons-4.1.jar;C:\LogAggregator\elasticsearch/lib/commons-cli-1.3.1.jar;C:\LogAggregator\elasticsearch/lib/compiler-0.8.13.jar;C:\LogAggregator\elasticsearch/lib/compress-lzf-1.0.2.jar;C:\LogAggregator\elasticsearch/lib/elasticsearch-2.1.1.jar;C:\LogAggregator\elasticsearch/lib/elasticsearch-2.2.0.jar;C:\LogAggregator\elasticsearch/lib/groovy-all-2.4.4-indy.jar;C:\LogAggregator\elasticsearch/lib/guava-18.0.jar;C:\LogAggregator\elasticsearch/lib/HdrHistogram-2.1.6.jar;C:\LogAggregator\elasticsearch/lib/hppc-0.7.1.jar;C:\LogAggregator\elasticsearch/lib/jackson-core-2.6.2.jar;C:\LogAggregator\elasticsearch/lib/jackson-dataformat-cbor-2.6.2.jar;C:\LogAggregator\elasticsearch/lib/jackson-dataformat-smile-2.6.2.jar;C:\
[2016-02-09 10:00:32] [debug] ( javajni.c:704 ) [ 8444] Jvm Option[16] exit
[2016-02-09 10:00:32] [debug] ( javajni.c:704 ) [ 8444] Jvm Option[17] -Xms256m
[2016-02-09 10:00:32] [debug] ( javajni.c:704 ) [ 8444] Jvm Option[18] -Xmx1024m
[2016-02-09 10:00:32] [debug] ( javajni.c:704 ) [ 8444] Jvm Option[19] -Xss256k
[2016-02-09 10:00:32] [debug] ( javajni.c:888 ) [ 8444] argv[0] = start
[2016-02-09 10:00:32] [debug] ( javajni.c:941 ) [ 8444] Java Worker thread started org/elasticsearch/bootstrap/Elasticsearch:main
[2016-02-09 10:00:32] [debug] ( javajni.c:952 ) [ 8444] Exception has been thrown
[2016-02-09 10:00:32] [debug] ( javajni.c:964 ) [ 8444] Java Worker thread finished org/elasticsearch/bootstrap/Elasticsearch:main with status=6
[2016-02-09 10:00:33] [debug] ( prunsrv.c:1186) [ 5200] Java started org/elasticsearch/bootstrap/Elasticsearch
[2016-02-09 10:00:33] [info]  ( prunsrv.c:1284) [ 5200] Service started in 1095 ms.
[2016-02-09 10:00:33] [debug] ( prunsrv.c:844 ) [ 5200] reportServiceStatusE: 4, 0, 0, 0
[2016-02-09 10:00:33] [debug] ( prunsrv.c:1528) [ 5200] Waiting for worker to finish...
[2016-02-09 10:00:33] [debug] ( prunsrv.c:1533) [ 5200] Worker finished.
[2016-02-09 10:00:33] [debug] ( prunsrv.c:1559) [ 5200] Waiting for all threads to exit
[2016-02-09 10:00:33] [debug] ( prunsrv.c:844 ) [ 5200] reportServiceStatusE: 3, 0, 0, 0
[2016-02-09 10:00:33] [debug] ( prunsrv.c:1563) [ 5200] JVM destroyed.
[2016-02-09 10:00:33] [debug] ( prunsrv.c:844 ) [ 5200] reportServiceStatusE: 1, 1066, 0, 1
[2016-02-09 10:00:33] [info]  ( prunsrv.c:1598) [ 8288] Run service finished.
[2016-02-09 10:00:33] [info]  ( prunsrv.c:1764) [ 8288] Commons Daemon procrun finished

What is missing?
Just to enable ELS service to run on a windows machine (single default node)

**Comment by gmarz** [comment] 2016-02-09 22:16
@habibcs can you also share your `elasticsearch.log` file?

**Comment by habibcs** [comment] 2016-02-10 08:16
[logs.zip](https://github.com/elastic/elasticsearch/files/124367/logs.zip)
Hi in the log folder (subfolder inside elasticsearch folder) - these are the only log files - same as what I pasted above.

**Comment by fenneh** [comment] 2016-02-12 17:38
Having the exact same issue. Server 2012 R2 machine using

    C:\Elasticsearch\bin>java -version
    java version "1.8.0_66"
    Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
    Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

**Comment by robedhbw** [comment] 2016-04-14 08:25
Hello,
I ve got the same error trying to install the jdbc river. Also on the Server 2012 R2..

**Comment by fenneh** [comment] 2016-04-14 15:24
I'm actually using ES 2.3.1 now with no issues on the same config as previously posted.

**Comment by clintongormley** [comment] 2016-04-14 17:13
@habibcs could you try 2.3.1 as well please?

**Comment by gmarz** [comment] 2016-04-14 18:56
@habibcs I noticed you have two elasticsearch jars in your class path:

[2016-02-09 10:00:32] debug [ 8444] Jvm Option[15] -Djava.class.path=C:\LogAggregator\elasticsearch/lib/elasticsearch-2.2.0.jar;C:\LogAggregator\elasticsearch/lib/antlr-runtime-3.5.jar;C:\LogAggregator\elasticsearch/lib/apache-log4j-extras-1.2.17.jar;C:\LogAggregator\elasticsearch/lib/asm-4.1.jar;C:\LogAggregator\elasticsearch/lib/asm-commons-4.1.jar;C:\LogAggregator\elasticsearch/lib/commons-cli-1.3.1.jar;C:\LogAggregator\elasticsearch/lib/compiler-0.8.13.jar;C:\LogAggregator\elasticsearch/lib/compress-lzf-1.0.2.jar;**C:\LogAggregator\elasticsearch/lib/elasticsearch-2.1.1.jar;C:\LogAggregator\elasticsearch/lib/elasticsearch-2.2.0.jar;**C:\LogAggregator\elasticsearch/lib/groovy-all-2.4.4-indy.jar;C:\LogAggregator\elasticsearch/lib/guava-18.0.jar;C:\LogAggregator\elasticsearch/lib/HdrHistogram-2.1.6.jar;C:\LogAggregator\elasticsearch/lib/hppc-0.7.1.jar;C:\LogAggregator\elasticsearch/lib/jackson-core-2.6.2.jar;C:\LogAggregator\elasticsearch/lib/jackson-dataformat-cbor-2.6.2.jar;C:\LogAggregator\elasticsearch/lib/jackson-dataformat-smile-2.6.2.jar;C:\

I am willing to bet that's your problem.  Was there already an existing elasticsearch installation in `C:\LogAggregator`?  If so, you should completely delete the existing `bin` and `lib` folders before extracting the new version.

**Comment by habibcs** [comment] 2016-04-15 07:21
Thanks for replying, I cannot test anymore (at least not now).
Got reply above (suggesting new version or now it would work) almost after two months; it wasn't a hobby project but was evaluating for client; and ultimately client decided other products.
Other ppl having the same issue, please recheck with the newer version and confirm if it is working, perhaps that can be useful specially @robedhbw

**Comment by clintongormley** [comment] 2016-04-15 08:16
> I am willing to bet that's your problem. Was there already an existing elasticsearch installation in C:\LogAggregator? If so, you should completely delete the existing bin and lib folders before extracting the new version.

@gmarz weird we didn't get a jarhell exception here?

**Comment by gmarz** [comment] 2016-04-15 14:03
@clintongormley I actually do get a jarhell exception

```
Exception in thread "main" anifest(JarHell.java:224)
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:177)
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:87)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:164)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.
The data area passed to a system call is too small.

Failed to start service
```

It's indeed strange that the logs @habibcs posted do not show the same exception.  But the double jar files in the class path indicate that something is probably funky with the installation- so it could be something else, but I'm not able to reproduce this otherwise.

@robedhbw I don't think you're running into the same issue. [Rivers have been removed in 2.0](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_removed_features.html#_rivers_have_been_removed), so if you're trying to install the JDBC river with ES 2.2, it won't work :).

**Comment by robedhbw** [comment] 2016-04-15 15:05
@gmarz Ou thanks. Is there any other useful plugin to import Ms Sql databases`? Thanks.

**Comment by clintongormley** [comment] 2016-04-18 10:14
i think we can close this issue then

**Closed by clintongormley** 2016-04-18 10:14 UTC
Labels: :Packaging, discuss
