### ISSUE TITLE
Elasticsearch plugin is red

### ISSUE THREAD

**Issue by keithjohnhowe** [elastic/elasticsearch#27586] opened 2017-11-29 14:52 UTC
I have installed Elasticsearch 5.51 and Kibana 5.51 and I am now getting an Elasticsearch plugin is red error message 

![screenshot from 2017-11-29 14-37-18](https://user-images.githubusercontent.com/25707671/33380468-16faf0a4-d513-11e7-9e59-76bd183541cc.png)

The elastic search logs mention - not enough master nodes discovered, I have 4 nodes and one master -- 

	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
[2017-11-29T14:23:41,899][WARN ][o.e.d.z.ZenDiscovery     ] [elasticsearch-logging-0] not enough master nodes discovered during pinging (found [[Candidate{node={elasticsearch-logging-0}{2vy6rZTLR7CZIi6wbRZj0Q}{tUNcsm31SVyMKVoZJc7BTA}{100.96.4.6}{100.96.4.6:9300}{ml.enabled=true}, clusterStateVersion=-1}]], but needed [2]), pinging again
[2017-11-29T14:23:43,417][WARN ][r.suppressed             ] path: /.reporting-*/esqueue/_search, params: {index=.reporting-*, type=esqueue, version=true}
org.elasticsearch.cluster.block.ClusterBlockException: blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];
	at org.elasticsearch.cluster.block.ClusterBlocks.globalBlockedException(ClusterBlocks.java:165) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.cluster.block.ClusterBlocks.globalBlockedRaiseException(ClusterBlocks.java:151) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.action.search.TransportSearchAction.executeSearch(TransportSearchAction.java:255) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:186) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:65) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:170) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:142) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:84) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:83) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:72) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.client.support.AbstractClient.search(AbstractClient.java:535) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.rest.action.search.RestSearchAction.lambda$prepareRequest$1(RestSearchAction.java:78) ~[elasticsearch-5.5.1.jar:5.5.1]

**Comment by jasontedor** [comment] 2017-11-29 14:59
This looks like a configuration issue, not a bug. Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this. We can reopen this if after discussion we see there is a bug.

**Closed by jasontedor** 2017-11-29 14:59 UTC
