### ISSUE TITLE
New machine cant start up by following steps of  Install Elasticsearch from archive on Linux or MacOS

### ISSUE THREAD

**Issue by yaolc** [elastic/elasticsearch#91733] opened 2022-11-19 23:43 UTC
### Elasticsearch Version

8.5.1

### Java Version

19.0.1

### OS Version

ubuntu 18.04

### Problem Description

My OS was installed new. I Install ElasticSearch By [Install Elasticsearch from archive on Linux or MacOS](https://www.elastic.co/guide/en/elasticsearch/reference/8.5/targz.html) .But Some Problem Happened.

[2022-11-19T23:38:27,384][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [8wahyuvj8ybdax7x] uncaught exception in thread [process reaper (pid 19995)]java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "modifyThread")
        at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:485)
        at java.base/java.security.AccessController.checkPermission(AccessController.java:1068)
        at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:411)
        at org.elasticsearch.securesm@8.5.1/org.elasticsearch.secure_sm.SecureSM.checkThreadAccess(SecureSM.java:166)
        at org.elasticsearch.securesm@8.5.1/org.elasticsearch.secure_sm.SecureSM.checkAccess(SecureSM.java:120)

### Steps to Reproduce

empty

### Logs (if relevant)

[2022-11-19T23:38:27,387][WARN ][stderr                   ] [8wahyuvj8ybdax7x] The system environment variables are not available to Log4j due to security restrictions: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getenv.*")The system environment variables are not available to Log4j due to security restrictions: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getenv.*")The system environment variables are not available to Log4j due to security restrictions: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getenv.*")The system environment variables are not available to Log4j due to security restrictions: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getenv.*")The system environment variables are not available to Log4j due to security restrictions: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getenv.*")
[2022-11-19T23:38:27,388][WARN ][stderr                   ] [8wahyuvj8ybdax7x] java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getenv.*")
[2022-11-19T23:38:27,388][WARN ][stderr                   ] [8wahyuvj8ybdax7x] 	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:485)
[2022-11-19T23:38:27,389][WARN ][stderr                   ] [8wahyuvj8ybdax7x] 	at java.base/java.security.AccessController.checkPermission(AccessController.java:1068)
[2022-11-19T23:38:27,389][WARN ][stderr                   ] [8wahyuvj8ybdax7x] 	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:411)
[2022-11-19T23:38:27,389][WARN ][stderr                   ] [8wahyuvj8ybdax7x] 	at java.base/java.lang.System.getenv(System.java:1198)
[2022-11-19T23:38:27,389][WARN ][stderr                   ] [8wahyuvj8ybdax7x] 	at org.apache.logging.log4j@2.18.0/org.apache.logging.log4j.util.EnvironmentPropertySource.containsProperty(EnvironmentPropertySource.java:99)
[2022-11-19T23:38:27,389][WARN ][stderr                   ] [8wahyuvj8ybdax7x] 	at org.apache.logging.log4j@2.18.0/org.apache.logging.log4j.util.PropertiesUtil$Environment.get(PropertiesUtil.java:513)
[2022-11-19T23:38:27,389][WARN ][stderr                   ] [8wahyuvj8ybdax7x] 	at org.apache.logging.log4j@2.18.0/org.apache.logging.log4j.util.PropertiesUtil$Environment.access$200(PropertiesUtil.java:434)
[2022-11-19T23:38:27,389][WARN ][stderr                   ] [8wahyuvj8ybdax7x] 	at org.apache.logging.log4j@2.18.0/org.apache.logging.log4j.util.PropertiesUtil.getStringProperty(PropertiesUtil.java:382)
[2022-11-19T23:38:27,389][WARN ][stderr                   ] [8wahyuvj8ybdax7x] 	at org.apache.logging.log4j@2.18.0/org.apache.logging.log4j.util.PropertiesUtil.getBooleanProperty(PropertiesUtil.java:169)
[2022-11-19T23:38:27,390][WARN ][stderr                   ] [8wahyuvj8ybdax7x] 	at org.apache.logging.log4j@2.18.0/org.apache.logging.log4j.status.StatusLogger.isDebugPropertyEnabled(StatusLogger.java:143)
[2022-11-19T23:38:27,390][WARN ][stderr                   ] [8wahyuvj8ybdax7x] 	at org.apache.logging.log4j@2.18.0/org.apache.logging.log4j.status.StatusLogger.isEnabled(StatusLogger.java:426)
[2022-11-19T23:38:27,390][WARN ][stderr                   ] [8wahyuvj8ybdax7x] 	at org.apache.logging.log4j@2.18.0/org.apache.logging.log4j.status.StatusLogger.isEnabled(StatusLogger.java:327)
[2022-11-19T23:38:27,390][WARN ][stderr                   ] [8wahyuvj8ybdax7x] 	at org.apache.logging.log4j@2.18.0/org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1982)
[2022-11-19T23:38:27,390][WARN ][stderr                   ] [8wahyuvj8ybdax7x] 	at org.apache.logging.log4j@2.18.0/org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:740)
[2022-11-19T23:38:27,390][WARN ][stderr                   ] [8wahyuvj8ybdax7x] 	at org.apache.logging.log4j.core@8.5.1/org.apache.logging.log4j.core.appender.DefaultErrorHandler.error(DefaultErrorHandler.java:61)
[2022-11-19T23:38:27,390][WARN ][stderr                   ] [8wahyuvj8ybdax7x] 	at org.apache.logging.log4j.core@8.5.1/org.apache.logging.log4j.core.config.AppenderControl.appenderErrorHandlerMessage(AppenderControl.java:118)
[2022-11-19T23:38:27,390][WARN ][stderr                   ] [8wahyuvj8ybdax7x] 	at org.apache.logging.log4j.core@8.5.1/org.apache.logging.log4j.core.config.AppenderControl.isRecursiveCall(AppenderControl.java:110)
[2022-11-19T23:38:27,391][WARN ][stderr                   ] [8wahyuvj8ybdax7x] 	at org.apache.logging.log4j.core@8.5.1/org.apache.logging.log4j.core.config.AppenderControl.shouldSkip(AppenderControl.java:93)
[2022-11-19T23:38:27,391][WARN ][stderr                   ] [8wahyuvj8ybdax7x] 	at org.apache.logging.log4j.core@8.5.1/org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:86)
[2022-11-19T23:38:27,391][WARN ][stderr                   ] [8wahyuvj8ybdax7x] 	at org.apache.logging.log4j.core@8.5.1/org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:675)
[2022-11-19T23:38:27,391][WARN ][stderr                   ] [8wahyuvj8ybdax7x] 	at org.apache.logging.log4j.core@8.5.1/org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:633)
[2022-11-19T23:38:27,391][WARN ][stderr                   ] [8wahyuvj8ybdax7x] 	at org.apache.logging.log4j.core@8.5.1/org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:616)
[2022-11-19T23:38:27,391][WARN ][stderr                   ] [8wahyuvj8ybdax7x] 	at org.apache.logging.log4j.core@8.5.1/org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:552)
[2022-11-19T23:38:27,391][WARN ][stderr                   ] [8wahyuvj8ybdax7x] 	at org.apache.logging.log4j.core@8.5.1/org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
[2022-11-19T23:38:27,391][WARN ][stderr                   ] [8wahyuvj8ybdax7x] 	at org.apache.logging.log4j.core@8.5.1/org.apache.logging.log4j.core.Logger.log(Logger.java:161)
[2022-11-19T23:38:27,391][WARN ][stderr                   ] [8wahyuvj8ybdax7x] 	at org.apache.logging.log4j@2.18.0/org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
[2022-11-19T23:38:27,392][WARN ][stderr                   ] [8wahyuvj8ybdax7x] 	at org.apache.logging.log4j@2.18.0/org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
[2022-11-19T23:38:27,392][WARN ][stderr                   ] [8wahyuvj8ybdax7x] 	at org.apache.logging.log4j@2.18.0/org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
[2022-11-19T23:38:27,387][WARN ][stderr                   ] [8wahyuvj8ybdax7x] The system environment variables are not available to Log4j due to security restrictions: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getenv.*")The system environment variables are not available to Log4j due to security restrictions: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getenv.*")The system environment variables are not available to Log4j due to security restrictions: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getenv.*")The system environment variables are not available to Log4j due to security restrictions: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getenv.*")
[2022-11-19T23:38:27,387][WARN ][stderr                   ] [8wahyuvj8ybdax7x] The system environment variables are not available to Log4j due to security restrictions: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getenv.*")The system environment variables are not available to Log4j due to security restrictions: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getenv.*")The system environment variables are not available to Log4j due to security restrictions: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getenv.*")
[2022-11-19T23:38:27,387][WARN ][stderr                   ] [8wahyuvj8ybdax7x] The system environment variables are not available to Log4j due to security restrictions: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getenv.*")The system environment variables are not available to Log4j due to security restrictions: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getenv.*")
[2022-11-19T23:38:27,386][WARN ][stderr                   ] [8wahyuvj8ybdax7x] The system environment variables are not available to Log4j due to security restrictions: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getenv.*")
[2022-11-19T23:38:27,384][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [8wahyuvj8ybdax7x] uncaught exception in thread [process reaper (pid 19995)]
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "modifyThread")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:485) ~[?:?]
	at java.security.AccessController.checkPermission(AccessController.java:1068) ~[?:?]
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:411) ~[?:?]
	at org.elasticsearch.secure_sm.SecureSM.checkThreadAccess(SecureSM.java:166) ~[?:?]
	at org.elasticsearch.secure_sm.SecureSM.checkAccess(SecureSM.java:120) ~[?:?]
	at java.lang.Thread.checkAccess(Thread.java:2360) ~[?:?]
	at java.lang.Thread.setDaemon(Thread.java:2308) ~[?:?]
	at java.lang.ProcessHandleImpl.lambda$static$0(ProcessHandleImpl.java:103) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:637) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:928) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1021) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1158) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
	at jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186) ~[?:?]

**Comment by rjernst** [comment] 2022-11-21 18:30
This is a duplicate of https://github.com/elastic/elasticsearch/issues/91650

**Closed by rjernst** 2022-11-21 18:30 UTC
Labels: >bug, :Core/Infra/Core, Team:Core/Infra
