### ISSUE TITLE
DateRangeIT fails with ZoneRulesException[Unknown time-zone ID: America/Nuuk]

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#87833] opened 2022-06-20 09:13 UTC
### CI Link

https://gradle-enterprise.elastic.co/s/b7ghqan6yijvw

### Repro line

gradlew ':server:integTest' -Dtests.seed=6168B8B64345658D -Dtests.class=org.elasticsearch.search.aggregations.bucket.DateRangeIT -Dtests.method="testSingleValueFieldWithDateMath" -Dtests.security.manager=true -Dtests.locale=bs-Latn-BA -Dtests.timezone=Asia/Seoul -Dcompiler.java=11 -Druntime.java=12

### Does it reproduce?

Didn't try

### Applicable branches

6.8

### Failure excerpt

Throwable #1: Failed to execute phase [query], all shards failed; shardFailures {[JW-5yCcLQxCGcRC9_OWkFQ][idx][0]: RemoteTransportException[[node_s0][127.0.0.1:45281][indices:data/read/search[phase/query]]]; nested: ZoneRulesException[Unknown time-zone ID: America/Nuuk]; }{[JW-5yCcLQxCGcRC9_OWkFQ][idx][1]: RemoteTransportException[[node_s0][127.0.0.1:45281][indices:data/read/search[phase/query]]]; nested: ZoneRulesException[Unknown time-zone ID: America/Nuuk]; }{[JW-5yCcLQxCGcRC9_OWkFQ][idx][2]: RemoteTransportException[[node_s0][127.0.0.1:45281][indices:data/read/search[phase/query]]]; nested: ZoneRulesException[Unknown time-zone ID: America/Nuuk]; }{[JW-5yCcLQxCGcRC9_OWkFQ][idx][3]: RemoteTransportException[[node_s0][127.0.0.1:45281][indices:data/read/search[phase/query]]]; nested: ZoneRulesException[Unknown time-zone ID: America/Nuuk]; }{[JW-5yCcLQxCGcRC9_OWkFQ][idx][4]: RemoteTransportException[[node_s0][127.0.0.1:45281][indices:data/read/search[phase/query]]]; nested: ZoneRulesException[Unknown time-zone ID: America/Nuuk]; }
09:47:12    > 	at __randomizedtesting.SeedInfo.seed([6168B8B64345658D:3F4EC312A8B6D406]:0)

**Comment by not-napoleon** [comment] 2022-10-14 14:58
I'm closing this - I couldn't reproduce the failure, it doesn't appear to have failed at all recently, and the version this failure is reported on is no longer supported.

**Closed by not-napoleon** 2022-10-14 14:58 UTC
Labels: :Analytics/Aggregations, >test-failure, Team:Analytics, v6.8.24
