### ISSUE TITLE
[CI] ActiveDirectorySessionFactoryTests classMethod failing

### ISSUE THREAD

**Issue by edsavage** [elastic/elasticsearch#105401] opened 2024-02-12 14:30 UTC
Seems docker related

**Build scan:**
https://gradle-enterprise.elastic.co/s/gkulbnzrdipfg/tests/:x-pack:qa:third-party:active-directory:test/org.elasticsearch.xpack.security.authc.ldap.ActiveDirectorySessionFactoryTests

**Reproduction line:**
```
null
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.xpack.security.authc.ldap.ActiveDirectorySessionFactoryTests#classMethod`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('classMethod'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.security.authc.ldap.ActiveDirectorySessionFactoryTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=<resolving>, imagePullPolicy=DefaultPullPolicy(), imageNameSubstitutor=org.testcontainers.utility.ImageNameSubstitutor$LogWrappedImageNameSubstitutor@27332164)

  at __randomizedtesting.SeedInfo.seed([7FA184586C7298D8]:0)
  at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1367)
  at org.testcontainers.containers.GenericContainer.logger(GenericContainer.java:674)
  at org.elasticsearch.test.fixtures.testcontainers.DockerEnvironmentAwareTestContainer.start(DockerEnvironmentAwareTestContainer.java:67)
  at org.testcontainers.containers.GenericContainer.starting(GenericContainer.java:1085)
  at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:28)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

  Caused by: com.github.dockerjava.api.exception.DockerClientException: Could not build image: failed to get digest sha256:cc95a733c5d8e97e125081874caaaf90cc1e1bb5d68b2af165a989cc7673b7aa: open /var/lib/docker/image/overlay2/imagedb/content/sha256/cc95a733c5d8e97e125081874caaaf90cc1e1bb5d68b2af165a989cc7673b7aa: no such file or directory

    at com.github.dockerjava.api.command.BuildImageResultCallback.getImageId(BuildImageResultCallback.java:78)
    at com.github.dockerjava.api.command.BuildImageResultCallback.awaitImageId(BuildImageResultCallback.java:50)
    at org.testcontainers.images.builder.ImageFromDockerfile.resolve(ImageFromDockerfile.java:159)
    at org.testcontainers.images.builder.ImageFromDockerfile.resolve(ImageFromDockerfile.java:40)
    at org.testcontainers.utility.LazyFuture.getResolvedValue(LazyFuture.java:20)
    at org.testcontainers.utility.LazyFuture.get(LazyFuture.java:41)
    at org.testcontainers.shaded.com.google.common.util.concurrent.Futures$1.get(Futures.java:536)
    at org.testcontainers.images.RemoteDockerImage.getImageName(RemoteDockerImage.java:130)
    at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:67)
    at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:28)
    at org.testcontainers.utility.LazyFuture.getResolvedValue(LazyFuture.java:20)
    at org.testcontainers.utility.LazyFuture.get(LazyFuture.java:41)
    at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1365)
    at org.testcontainers.containers.GenericContainer.logger(GenericContainer.java:674)
    at org.elasticsearch.test.fixtures.testcontainers.DockerEnvironmentAwareTestContainer.start(DockerEnvironmentAwareTestContainer.java:67)
    at org.testcontainers.containers.GenericContainer.starting(GenericContainer.java:1085)
    at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:28)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
    at java.lang.Thread.run(Thread.java:1583)

```

**Comment by benwtrent** [comment] 2024-02-12 14:47
Not sure why this was tagged as `:search/search`

The failure was due to a docker image failing to download and if it wasn't due to that, it the test is located within the security plugin.

Tagging delivery & security.

**Comment by mark-vieira** [comment] 2024-02-13 18:52
So far only a single occurrence. We'll keep an eye on this.

**Comment by benwtrent** [comment] 2024-03-06 14:36
eerily similar failure here: https://gradle-enterprise.elastic.co/s/zlqmdntkflpbs

active-directory test failure due to docker failure.

**Comment by slobodanadamovic** [comment] 2024-04-23 07:35
There have been only 2 failures in the past 2 months and in the past 1 month 0 failure. Hence I marked this issue as `low-risk`, since this feels like a temporary issue.

**Comment by mark-vieira** [comment] 2024-04-23 16:37
Closing since there have been no failures in the last month.

**Comment by slobodanadamovic** [comment] 2024-05-02 14:32
Just found two recent failures with the same issue but for different tests:

- [GroupMappingIT](https://gradle-enterprise.elastic.co/s/4s4vjmjdmrzzy/tests/task/:x-pack:qa:third-party:active-directory:test/details/org.elasticsearch.xpack.security.authc.ldap.GroupMappingIT?top-execution=1)

- [ActiveDirectoryRunAsIT](https://gradle-enterprise.elastic.co/s/s3lxd7fc4yqqk/tests/task/:x-pack:qa:third-party:active-directory:test/details/org.elasticsearch.xpack.security.authc.ldap.ActiveDirectoryRunAsIT?top-execution=1)

**Comment by slobodanadamovic** [comment] 2024-10-15 14:04
We still see occasional failures for `GroupMappingIT` and `ActiveDirectoryRunAsIT` integration test:
 
- https://github.com/elastic/elasticsearch/issues/114022
- https://github.com/elastic/elasticsearch/issues/114076

This still looks like a transient error, but it might as well be a race condition!? 
```
GroupMappingIT > classMethod FAILED
    org.testcontainers.containers.ContainerLaunchException: Container startup failed for image es-smb-fixture:latest
        at __randomizedtesting.SeedInfo.seed([ABF161D102ABA71E]:0)
        at app//org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:362)
        at app//org.testcontainers.containers.GenericContainer.start(GenericContainer.java:333)
        at app//org.elasticsearch.test.fixtures.testcontainers.DockerEnvironmentAwareTestContainer.start(DockerEnvironmentAwareTestContainer.java:68)
        at app//org.testcontainers.containers.GenericContainer.starting(GenericContainer.java:1085)
        at app//org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:28)
        at app//org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at app//org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
        at app//com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at app//com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at app//org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at app//org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at app//org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at app//org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at app//org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
        at app//org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at app//com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
        at app//com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
        at java.base@22.0.1/java.lang.Thread.run(Thread.java:1570)

        Caused by:
        org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=<resolving>, imagePullPolicy=DefaultPullPolicy(), imageNameSubstitutor=org.testcontainers.utility.ImageNameSubstitutor$LogWrappedImageNameSubstitutor@1c350e95)
            at app//org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1367)
            at app//org.testcontainers.containers.GenericContainer.logger(GenericContainer.java:674)
            at app//org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:344)
            ... 21 more

            Caused by:
            com.github.dockerjava.api.exception.DockerClientException: Could not build image: failed to get digest sha256:a543b761e853ed2141667038347abfe5b0683c620183d5ed320595cc83b254ed: open /var/lib/docker/image/overlay2/imagedb/content/sha256/a543b761e853ed2141667038347abfe5b0683c620183d5ed320595cc83b254ed: no such file or directory
                at app//com.github.dockerjava.api.command.BuildImageResultCallback.getImageId(BuildImageResultCallback.java:78)
                at app//com.github.dockerjava.api.command.BuildImageResultCallback.awaitImageId(BuildImageResultCallback.java:50)
                at app//org.testcontainers.images.builder.ImageFromDockerfile.resolve(ImageFromDockerfile.java:159)
                at app//org.testcontainers.images.builder.ImageFromDockerfile.resolve(ImageFromDockerfile.java:40)
                at app//org.testcontainers.utility.LazyFuture.getResolvedValue(LazyFuture.java:20)
                at app//org.testcontainers.utility.LazyFuture.get(LazyFuture.java:41)
                at app//org.testcontainers.shaded.com.google.common.util.concurrent.Futures$1.get(Futures.java:536)
                at app//org.testcontainers.images.RemoteDockerImage.getImageName(RemoteDockerImage.java:130)
                at app//org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:67)
                at app//org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:28)
                at app//org.testcontainers.utility.LazyFuture.getResolvedValue(LazyFuture.java:20)
                at app//org.testcontainers.utility.LazyFuture.get(LazyFuture.java:41)
                at app//org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1365)
                ... 23 more
```

**Comment by mark-vieira** [comment] 2024-12-27 16:28
Duplicate of https://github.com/elastic/elasticsearch/issues/117415

**Closed by mark-vieira** 2024-12-27 16:28 UTC
Labels: :Delivery/Build, >test-failure, Team:Delivery, low-risk
