### ISSUE TITLE
moving average prediction bug

### ISSUE THREAD

**Issue by liorg2** [elastic/elasticsearch#24327] opened 2017-04-26 08:39 UTC
**Elasticsearch version:**
5.2
**Plugins installed:**
[x-pack]

**JVM version**:
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

**OS version:**
CentOS Linux release 7.2.1511

**Description of the problem including expected versus actual behavior:**
when trying to predict 2 different aggregation buckets - when the first is null,(not sure why), no prediction is provided for the other one as well.

**Steps to reproduce:**

this will return prediction for "plt" field:

[query1.txt](https://github.com/elastic/elasticsearch/files/957702/query1.txt)

_response:_

[response1.txt](https://github.com/elastic/elasticsearch/files/957703/response1.txt)

while this will not return "plt" field prediction:
[query2.txt](https://github.com/elastic/elasticsearch/files/957705/query2.txt)

_response:_
[response2.txt](https://github.com/elastic/elasticsearch/files/957706/response2.txt)

the only difference in the aggregations order, which should not matter in json documents

**Comment by colings86** [comment] 2017-04-26 09:58
Something is definitely weird here because in botht hte responses the last non-prediction bucket is:
```
              {
                "key_as_string": "2017-02-26T00:00:00.000Z",
                "key": 1488067200000,
                "doc_count": 0,
                "avg__plt": {
                  "value": 14243.0556640625
                },
                "avg__connection_time": {
                  "value": null
                },
                "movavg__plt": {
                  "value": 13210.367580574217
                },
                "movavg__connection_time": {
                  "value": 359.128475
                }
              }
```
That bucket has a `doc_count` of 0 which is weird because 1) you have no extended_bounds on your histogram so it should not be returning empty buckets and 2) if the bucket is empty then the `avg__plt` agg should be returning `null` like the `avg__connection_time` agg is because there was no date for the bucket to compute the average for.

@polyfractal any ideas here?

**Comment by colings86** [comment] 2017-04-26 10:00
@liorg2 are you able to try to come up with a recreation script that should this same behaviour on a fresh index? If so could you provide it here? (it would be good if your recreation script includes creating the index and indexing documents so we can fully reproduce what you are seeing)

**Comment by colings86** [comment] 2017-04-26 10:02
@liorg2 also, could you do a query for `"key":"75610c7ee12bc268af33ddb31828a4b8"` and `"create_date": [1488067200000 TO 1488153600000]` to see if it matches any documents? (from those above responses it suggests you should get 0 hits

**Comment by liorg2** [comment] 2017-04-26 11:33
thanks @colings86 

there is one doc by this condition:

```
GET .../_search?ignore_unavailable
{
  "size": 10,
  "query": {
    "bool": {
      "filter": [
        {
          "range": {
            "create_date": {
              "gte": "2017-02-26T00:00:00",
              "lt": "2017-02-27T00:00:00"
            }
          }
        },
        {
          "terms": {
            "key": [
              "75610c7ee12bc268af33ddb31828a4b8"
            ]
          }
        }
      ]
    }
  }
}

```

it doesn't have this field though: "connection_time__stats"

is there a quick way to generate such a create/index script you mentioned?

**Comment by polyfractal** [comment] 2017-04-26 21:14
Urgh, yeah, I have no idea what's going on here either.  All the values are identical up until the missing prediction bucket.

I'm wondering if that second-to-last bucket with a count of zero is somehow getting overwritten/merged with a prediction bucket?  E.g. [here](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/search/aggregations/pipeline/movavg/MovAvgPipelineAggregator.java#L164) we create a new bucket for the prediction -- using any existing buckets -- but set the doc count to zero. 

If the two series are not "lined up" then one of the aggs would overwrite a valid bucket with it's prediction, which may be the case here... I think.

I'm still not sure why the order matters and why the last bucket shows/doesn't show, but it may be related.  I'll start debugging.

**Comment by polyfractal** [comment] 2017-04-28 13:01
BTW @liorg2 , if there's any way you can create a small test case that demonstrates this behavior, it would be very appreciated!  Still a bit stumped what's going on here :/

**Comment by liorg2** [comment] 2017-04-28 15:34
No prob. Will do it on Monday

**Comment by liorg2** [comment] 2017-05-10 15:39
I'm very sorry, but I don't have access to this data anymore. I really hope that you succeeded to reproduce this issue.....
anyway I think is that the missing field cause this issue

Lior

**Comment by polyfractal** [comment] 2017-05-17 18:22
No luck reproducing, but after looking a bit closer there's definitely a bug with predictions overwriting doc counts on buckets.  Perhaps that's the root cause, not sure.  I'll work up a PR to fix that and hopefully it'll fix your problem :)

**Comment by liorg2** [comment] 2017-05-18 08:10
Sorry, but the admin here deleted all "QA indices" from time to time. I will try to replicate it when I have more time

**Comment by polyfractal** [comment] 2017-06-13 15:47
Gonna close this, feel free to re-open if you can provide some more information about the issue you were having.  #24892 fixed the doc_count issue, so perhaps try to upgrade to a version with that bugfix (5.5, 6.0) if you get a chance.

> BTW, it will be very nice of you guys to add also upper/lower fences, as few other libraries do.
also, can I ask, if you are using open source lib for the models/prediction calc ?

We can look into adding fences, although I'm not quite sure how that applies to moving average?  I've only seen fences in reference to box-plots.

No open source lib for models/prediction, just our own code.  We only support pretty simple moving averages and extrapolation, so it wasn't a burden to write it ourself. :)

**Closed by polyfractal** 2017-06-13 15:47 UTC
Labels: :Aggregations, feedback_needed
