### ISSUE TITLE
Soft Limit for Max number of shards per node

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/elasticsearch#24253] opened 2017-04-21 18:43 UTC
Nowadays one can create as many shards as you want in a node. Elasticsearch will try to allocate the shards in the nodes, and if you have too many shards you can hit different type of issues:

1. Too many open files (File Descriptor Issues).
2. High memory usage.
3. Large cluster states

I think that if we add a Soft Limit for the number of shards per node, we could be at least preventing [1] and [2] , and [3] shouldn't be too problematic and can be easily fixed in an existing cluster.

CC @clintongormley

**Comment by clintongormley** [comment] 2017-04-24 10:13
Duplicate of https://github.com/elastic/elasticsearch/issues/20705

**Closed by clintongormley** 2017-04-24 10:13 UTC
Labels: discuss, enhancement
