### ISSUE TITLE
[CI] CreateIndexIT trips assertion in ReleasableBytesReference

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#74253] opened 2021-06-17 15:40 UTC
This caused the test to timeout but I'm not sure it's specific to CreateIndexIT itself, it seems that there may be a missing incRef() somewhere in recovery?

**Build scan:**
https://gradle-enterprise.elastic.co/s/tt2vkhr34d3oe/tests/:server:internalClusterTest/org.elasticsearch.action.admin.indices.create.CreateIndexIT/classMethod

**Reproduction line:**
`null`

**Applicable branches:**
7.13

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.action.admin.indices.create.CreateIndexIT&tests.test=classMethod

**Failure excerpt:**
```
java.lang.Exception: Suite timeout exceeded (>= 1200000 msec).

  at __randomizedtesting.SeedInfo.seed([1DB9635AB22FB757]:0)

```

**Comment by romseygeek** [comment] 2021-06-17 15:41
The actual useful part of the output is this:
```

Caused by: | &nbsp;
-- | --
&nbsp; | java.lang.AssertionError | &nbsp;
&nbsp; | at __randomizedtesting.SeedInfo.seed([1DB9635AB22FB757]:0) | &nbsp;
&nbsp; | at org.elasticsearch.common.bytes.ReleasableBytesReference.writeTo(ReleasableBytesReference.java:145) | &nbsp;
&nbsp; | at org.elasticsearch.common.io.stream.StreamOutput.writeBytesReference(StreamOutput.java:189) | &nbsp;
&nbsp; | at org.elasticsearch.indices.recovery.RecoveryFileChunkRequest.writeTo(RecoveryFileChunkRequest.java:105) | &nbsp;
&nbsp; | at org.elasticsearch.transport.OutboundMessage.writeMessage(OutboundMessage.java:76) | &nbsp;
&nbsp; | at org.elasticsearch.transport.OutboundMessage.serialize(OutboundMessage.java:53) | &nbsp;
&nbsp; | at org.elasticsearch.transport.OutboundHandler$MessageSerializer.get(OutboundHandler.java:161) | &nbsp;
&nbsp; | at org.elasticsearch.transport.OutboundHandler$MessageSerializer.get(OutboundHandler.java:147) | &nbsp;
&nbsp; | at org.elasticsearch.transport.OutboundHandler$SendContext.get(OutboundHandler.java:200) | &nbsp;
&nbsp; | at org.elasticsearch.transport.OutboundHandler.internalSend(OutboundHandler.java:127) | &nbsp;
&nbsp; | at org.elasticsearch.transport.OutboundHandler.sendMessage(OutboundHandler.java:122) | &nbsp;
&nbsp; | at org.elasticsearch.transport.OutboundHandler.sendRequest(OutboundHandler.java:86) | &nbsp;
&nbsp; | at org.elasticsearch.transport.TcpTransport$NodeChannels.sendRequest(TcpTransport.java:260) | &nbsp;
&nbsp; | at org.elasticsearch.test.transport.StubbableTransport$WrappedConnection.sendRequest(StubbableTransport.java:221) | &nbsp;
&nbsp; | at org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:845) | &nbsp;
&nbsp; | at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:759) | &nbsp;
&nbsp; | at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:685) | &nbsp;
&nbsp; | at org.elasticsearch.indices.recovery.RemoteRecoveryTargetHandler$1.tryAction(RemoteRecoveryTargetHandler.java:240) | &nbsp;
&nbsp; | at org.elasticsearch.action.support.RetryableAction$1.doRun(RetryableAction.java:88) | &nbsp;
&nbsp; | at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) | &nbsp;
&nbsp; | at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:215) | &nbsp;
&nbsp; | at org.elasticsearch.action.support.RetryableAction.run(RetryableAction.java:66) | &nbsp;
&nbsp; | at org.elasticsearch.indices.recovery.RemoteRecoveryTargetHandler.executeRetryableAction(RemoteRecoveryTargetHandler.java:250) | &nbsp;
&nbsp; | at org.elasticsearch.indices.recovery.RemoteRecoveryTargetHandler.writeFileChunk(RemoteRecoveryTargetHandler.java:205) | &nbsp;
&nbsp; | at org.elasticsearch.indices.recovery.RecoverySourceHandler$2.executeChunkRequest(RecoverySourceHandler.java:955) | &nbsp;
&nbsp; | at org.elasticsearch.indices.recovery.RecoverySourceHandler$2.executeChunkRequest(RecoverySourceHandler.java:903) | &nbsp;
&nbsp; | at org.elasticsearch.indices.recovery.MultiChunkTransfer.handleItems(MultiChunkTransfer.java:112) | &nbsp;
&nbsp; | at org.elasticsearch.indices.recovery.MultiChunkTransfer.access$000(MultiChunkTransfer.java:48) | &nbsp;
&nbsp; | at org.elasticsearch.indices.recovery.MultiChunkTransfer$1.write(MultiChunkTransfer.java:67) | &nbsp;
&nbsp; | at org.elasticsearch.common.util.concurrent.AsyncIOProcessor.processList(AsyncIOProcessor.java:97) | &nbsp;
&nbsp; | at org.elasticsearch.common.util.concurrent.AsyncIOProcessor.drainAndProcessAndRelease(AsyncIOProcessor.java:85) | &nbsp;
&nbsp; | at org.elasticsearch.common.util.concurrent.AsyncIOProcessor.put(AsyncIOProcessor.java:73) | &nbsp;
&nbsp; | at org.elasticsearch.indices.recovery.MultiChunkTransfer.addItem(MultiChunkTransfer.java:78) | &nbsp;
&nbsp; | at org.elasticsearch.indices.recovery.MultiChunkTransfer.start(MultiChunkTransfer.java:74) | &nbsp;
&nbsp; | at org.elasticsearch.indices.recovery.RecoverySourceHandler.sendFiles(RecoverySourceHandler.java:978) | &nbsp;
&nbsp; | at org.elasticsearch.indices.recovery.RecoverySourceHandler.lambda$phase1$22(RecoverySourceHandler.java:531) | &nbsp;
&nbsp; | at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134) | &nbsp;
&nbsp; | at org.elasticsearch.common.util.concurrent.ListenableFuture$1.doRun(ListenableFuture.java:101) | &nbsp;
&nbsp; | at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) | &nbsp;
&nbsp; | at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:215) | &nbsp;
&nbsp; | at org.elasticsearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:95) | &nbsp;
&nbsp; | at org.elasticsearch.common.util.concurrent.ListenableFuture.lambda$done$0(ListenableFuture.java:87) | &nbsp;
&nbsp; | at java.util.ArrayList.forEach(ArrayList.java:1259) | &nbsp;
&nbsp; | at org.elasticsearch.common.util.concurrent.ListenableFuture.done(ListenableFuture.java:87) | &nbsp;
&nbsp; | at org.elasticsearch.common.util.concurrent.BaseFuture.set(BaseFuture.java:133) | &nbsp;
&nbsp; | at org.elasticsearch.common.util.concurrent.ListenableFuture.onResponse(ListenableFuture.java:116) | &nbsp;
&nbsp; | at org.elasticsearch.action.StepListener.innerOnResponse(StepListener.java:53) | &nbsp;
&nbsp; | at org.elasticsearch.action.NotifyOnceListener.onResponse(NotifyOnceListener.java:29) | &nbsp;
&nbsp; | at org.elasticsearch.action.ActionListener$MappedActionListener.onResponse(ActionListener.java:101) | &nbsp;
&nbsp; | at org.elasticsearch.action.ActionListener$RunBeforeActionListener.onResponse(ActionListener.java:387) | &nbsp;
&nbsp; | at org.elasticsearch.action.support.RetryableAction$RetryingListener.onResponse(RetryableAction.java:133) | &nbsp;
&nbsp; | at org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:43) | &nbsp;
&nbsp; | at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1273) | &nbsp;
&nbsp; | at org.elasticsearch.transport.InboundHandler.doHandleResponse(InboundHandler.java:291) | &nbsp;
&nbsp; | at org.elasticsearch.transport.InboundHandler.lambda$handleResponse$1(InboundHandler.java:279) | &nbsp;
&nbsp; | at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:673) | &nbsp;
&nbsp; | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) | &nbsp;
&nbsp; | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) | &nbsp;
&nbsp; | at java.lang.Thread.run(Thread.java:748)
```

**Comment by DaveCTurner** [comment] 2021-06-17 15:43
Hmm I wonder if this relates https://github.com/elastic/elasticsearch/pull/74117 which added a missing `decRef()` around here.

**Comment by original-brownbear** [comment] 2021-06-17 16:12
@DaveCTurner I think the problem is that if a recovery is cancelled while the request is about to be sent, we will decrement the request and still try to send it. I think I have a reasonable fix for this :)

**Comment by DaveCTurner** [comment] 2021-06-17 16:19
Ah yeah good catch, we should try and acquire another ref just for the sending too I guess.

**Closed** 2021-06-17 20:46 UTC
Labels: :Distributed/Recovery, >test-failure, Team:Distributed
