### ISSUE TITLE
[feature request] close inactive index and when it is visited first time, open it

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#18990] opened 2016-06-21 03:32 UTC
**Describe the feature**:
close inactive index(without read or write) for configable time.
when it is visited first time, open it.

**Comment by jpountz** [comment] 2016-06-21 06:25
What is the reason that makes you want this feature?

**Comment by makeyang** [comment] 2016-06-21 06:32
some users take ES as the main storage system and keep like years data, which is structed as daily rolling data, in ES as the archieve data.
some old data are seldom used but they will be used one day. 
in order to reduce the cluster's memory presure, I'd like this feature.

**Comment by clintongormley** [comment] 2016-06-21 09:55
Duplicate of https://github.com/elastic/elasticsearch/issues/10869

**Closed by clintongormley** 2016-06-21 09:55 UTC
