### ISSUE TITLE
SQL: add support for scripted metrics aggregations

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#37271] opened 2019-01-09 16:20 UTC
`SELECT MAX(IF(<condition>,<value1>,<value2>)) FROM test` is not currently supported in ES-SQL, but such a query is possible in Elasticsearch through the use of scripts.
For example:

```
{
	"size":0,
    "aggs" : {
        "prices" : {
            "sum" : {
                "script" : {
                    "source": "if (doc['price'].size()>0) {if (doc.decider.value>0) return doc.price.value; else return 0;} else return 0;"
                }
            }
        }
    }
}
```

**Comment by costin** [comment] 2019-01-10 07:05
`IF` is not standard SQL and can be mimicked through `CASE/THEN/END` - more verbose but also more powerful. I would use that instead on the SQL side - the implementation in ES will likely be the same.

**Comment by joaquinfernandez131** [comment] 2019-01-29 14:47
> `IF` is not standard SQL and can be mimicked through `CASE/THEN/END` - more verbose but also more powerful. I would use that instead on the SQL side - the implementation in ES will likely be the same.

Is there an issue raised by the CASE (WHEN) (#36200), do you know when they will incorporate it?

**Comment by astefan** [comment] 2019-02-07 06:56
@joaquinfernandez131 we don't have a definitive plan for it, but it's likely to be implemented sometime in the future, if no technical reasons against it will arise.

**Comment by monfera** [comment] 2019-12-02 13:15
I'd also favor `CASE` / `WHEN` as the standard defines it, and the compatibility matrix is pretty uniform (see Compatibility 2/3rds of the way down [here](https://modern-sql.com/feature/case)) so people can just use it. Not sure if it fits right away, but there are some finer points, eg. 

- possibility for an `ELSE` branch, 
- simple form, when the compared value is hoisted, and the `WHEN`s contain values for `=` checking rather than containing full predicates, so `CASE a WHEN 100... WHEN 200...` as an alternative to the baseline `CASE WHEN a = 100... WHEN a = 200...` 
- `COALESCE`, `NULLIF`

**Comment by mage694** [comment] 2019-12-05 08:40
Any update on this issue?

**Comment by obi134** [comment] 2020-01-28 12:39
I would also appreciate a fix of this to resolve an issue like this: https://stackoverflow.com/questions/28149366/how-to-make-a-2d-count-table-in-sql

It would be great if ES SQL would support COUNT( CASE WHEN expression THEN 1 ELSE 0 END)

**Comment by matriv** [comment] 2020-04-09 14:44
UPDATE: We have started working on this.

**Comment by matriv** [comment] 2020-04-09 14:47
Closing this as it's actually a duplicate of #29980.
Please follow the updates there.

**Closed by matriv** 2020-04-09 14:47 UTC
Labels: :Query Languages/SQL, >feature

**Comment by matriv** [comment] 2020-04-17 10:41
`master` : 506d1beea7abb2b45de793bba2e349090a78f2f9
`7.x` : f958e9abdc492f648e305c9de618bf7273e5559b
