### ISSUE TITLE
zen.ping_timeout in docs, zen.ping.timeout in elasticsearch.yml

### ISSUE THREAD

**Issue by Chromana** [elastic/elasticsearch#9581] opened 2015-02-05 11:22 UTC
In the docs (http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/modules-discovery-zen.html#master-election) it says the variable is `discovery.zen.ping_timeout`. In the default elasticsearch.yml which ships with ES 1.4.2 it is stated (on about line 310) as `discovery.zen.ping.timeout`. Which is it? A correction should be made somewhere and the rest of the offending document should probably be checked for other similar inaccuracies.

**Comment by clintongormley** [comment] 2015-02-09 11:32
Meh - both of them work, for bwc sake :(

The problem is that we don't yet have a decent way to deprecate old settings. This should be solved by https://github.com/elasticsearch/elasticsearch/issues/6732

**Comment by jasontedor** [comment] 2015-09-23 17:19
Closed by d8b29f7beb37993c77bfb3298a77513651ef81d4.

**Closed** 2015-09-23 17:18 UTC
Labels: :Settings, adoptme
