### ISSUE TITLE
highlight regression between ES version 8.1 and 8.2

### ISSUE THREAD

**Issue by acarrio** [elastic/elasticsearch#86455] opened 2022-05-05 08:31 UTC
### Elasticsearch Version

8.2.0

### Installed Plugins

default installation

### Java Version

_bundled_

### OS Version

windows 10

### Problem Description

Hello,

In version 8.2 I found a regression in highlight regarding th use of wildcard query using a rewrite parameter different from the default one. In that case I get only one snippet from the the wildcard field and if I change the rewrite to  "constant_score" I get two snippets one from each field that match.

Thanks for your help.

### Steps to Reproduce

curl -XDELETE localhost:9222/test

curl -XPUT localhost:9222/test

curl -XPUT -H "Content-Type: application/json" localhost:9222/test/_doc/1 -d '{
 "title": "Method for preventing electrode deterioration in etching apparatus",
 "code": "usb1"
}'

curl -XPOST "http://localhost:9222/test/_search" -H 'Content-Type: application/json' -d'
{
  "size": 1,
  "_source": false, 
  "query": {
    "bool": {
      "must": [
        {
          "bool": {
            "should": [
              {
                "term": {
                  "title": {
                    "value": "electrode",
                    "boost": 5.3159513
                  }
                }
              }
            ],
            "adjust_pure_negative": true,
            "boost": 1
          }
        },
        {
          "bool": {
            "should": [
              {
                "term": {
                  "title": {
                    "value": "deterioration",
                    "boost": 5.3159513
                  }
                }
              }
            ],
            "adjust_pure_negative": true,
            "boost": 1
          }
        },
        {
          "wildcard": {
            "code": {
              "wildcard": "usb?",
              "rewrite": "constant_score_boolean"
            }
          }
        }
      ],
      "adjust_pure_negative": true,
      "boost": 1
    }
  },
  "highlight": {
    "pre_tags": [
      "<mark>"
    ],
    "post_tags": [
      "</mark>"
    ],
    "type": "unified",
    "force_source": false,
    "require_field_match": true,
    "fields": {
      "title": {
        "fragment_size": 50000,
        "number_of_fragments": 10000
      },
      "code": {
        "fragment_size": 1000,
        "number_of_fragments": 10000
      }
    }
  }
}'

Produce higlight : 
        "highlight" : {
          "code" : [
            "<mark>usb1</mark>"
          ]
        }

curl -XPOST "http://localhost:9222/test/_search" -H 'Content-Type: application/json' -d'
{
  "size": 1,
  "_source": false, 
  "query": {
    "bool": {
      "must": [
        {
          "bool": {
            "should": [
              {
                "term": {
                  "title": {
                    "value": "electrode",
                    "boost": 5.3159513
                  }
                }
              }
            ],
            "adjust_pure_negative": true,
            "boost": 1
          }
        },
        {
          "bool": {
            "should": [
              {
                "term": {
                  "title": {
                    "value": "deterioration",
                    "boost": 5.3159513
                  }
                }
              }
            ],
            "adjust_pure_negative": true,
            "boost": 1
          }
        },
        {
          "wildcard": {
            "code": {
              "wildcard": "usb?",
              "rewrite": "constant_score"
            }
          }
        }
      ],
      "adjust_pure_negative": true,
      "boost": 1
    }
  },
  "highlight": {
    "pre_tags": [
      "<mark>"
    ],
    "post_tags": [
      "</mark>"
    ],
    "type": "unified",
    "force_source": false,
    "require_field_match": true,
    "fields": {
      "title": {
        "fragment_size": 50000,
        "number_of_fragments": 10000
      },
      "code": {
        "fragment_size": 1000,
        "number_of_fragments": 10000
      }
    }
  }
}'
Produce higlight : 
        "highlight" : {
          "code" : [
            "<mark>usb1</mark>"
          ],
          "title" : [
            "Method for preventing <mark>electrode</mark> <mark>deterioration</mark> in etching apparatus"
          ]
        }

**Comment by asabourin** [comment] 2022-05-27 06:08
Possibly related to this, we've noticed that a query with a `query_string` and a `more_like_this` terms which returned highlights in 8.1.x and older doesn't return them anymore in 8.2.0. Removing the `more_like_this` term does bring back the highlights in the response.

**Comment by asabourin** [comment] 2022-07-20 02:11
Digging further, using the `plain` highlighter instead of the `unified` one does solve the issue (as well as a new different occurrence of missing highlight result we've seen in 8.3 with a seemingly basic `query_string`)

**Comment by romseygeek** [comment] 2022-09-23 12:24
This is caused by https://github.com/apache/lucene/issues/11490 and will be fixed by https://github.com/apache/lucene/pull/11807, which will hopefully be included in an apache lucene release fairly soon and in a new elasticsearch version shortly afterwards.

**Comment by javanna** [comment] 2023-05-03 21:20
This should be fixed with Elasticsearch 8.7 which is based on Lucene 9.5 and contains the fix you mentioned above. Can we close?

**Comment by romseygeek** [comment] 2023-05-04 09:41
Yes, we can close this now.

**Closed by romseygeek** 2023-05-04 09:41 UTC
Labels: >bug, :Search/Highlighting, Team:Search
