### ISSUE TITLE
There should be common interfaces for the same name methods in java client library

### ISSUE THREAD

**Issue by xzer** [elastic/elasticsearch#5361] opened 2014-03-07 07:02 UTC
AFAIK, it would be great if two types of interfaces are defined, which would help developers to do better source reusing. And also that there maybe other things in same situation, I hope somebody else can commit them here too.

At first, for the request builders, there are SearchRequestBuilder, CountRequestBuilder and DeleteByQueryRequestBuilder which are sharing a group of methods with same name due to the completely same functions. Thus, currently, I have to define 3 methods for the separated 3 types if I want to add some common search define on the request(especially for adding routing by common logic).

Secondly, for the QueryBuilders and FilterBuilders, they are in 99% similarity logically and they are in 99% similarity in the real source but there are only separated interfaces for each other of query and filter. Hence, I have to define 2 methods for the separated 2 types if I want to create a common query define for some common business data structure.

I believe both of the above situations can be addressed by defining higher level interfaces.

**Comment by dakrone** [comment] 2015-04-10 16:58
This can be visited as part of #10217

**Comment by clintongormley** [comment] 2015-04-13 10:14
Agreed - closing as a duplicate of #10217 and https://github.com/elastic/elasticsearch/pull/10531

**Closed by clintongormley** 2015-04-13 10:14 UTC
Labels: :Java API
