### ISSUE TITLE
suggest_mode in term suggester not working correctly

### ISSUE THREAD

**Issue by kabike** [elastic/elasticsearch#29181] opened 2018-03-21 05:47 UTC
**Elasticsearch version** :Version: 6.1.1, Build: bd92e7f/2017-12-17T20:23:25.338Z

**Plugins installed**: []

**JVM version** :java version "1.8.0_151"

**OS version** :Linux dev24.mr 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
Suggest_mode in term suggester not working correctly.It should work as doccument

**Steps to reproduce**:
 1.
```
POST bar/foo/1
{
  "title": "that is human"
}

POST bar/foo/2
{
  "title": "that is human"
}

POST bar/foo/3
{
  "title": "that is humane"
}
```
 2.
```
POST bar/_search
{
  "suggest": {
    "suggestion": {
      "text": "humane",
      "term": {
        "field": "title"
      }
    }
  }
}
```
 3.
the result is
```
  "suggest": {
    "suggestion": [
      {
        "text": "humane",
        "offset": 0,
        "length": 6,
        "options": [
          {
            "text": "human",
            "score": 0.8,
            "freq": 2
          }
        ]
      }
    ]
  }
```
suggest_mode defaults to "missing",so there should not be options for "humane" since it is also in index

**Comment by jimczi** [comment] 2018-03-21 08:59
The `missing` option is applied per shard, in your example you create an index with 5 shards and only one document contains `humane` so the 4 other shards can return a suggestion for this term.
Currently there is no way to discard a suggestion if the input exists in at least one shard. 
Closing as duplicate of #7472

**Closed by jimczi** 2018-03-21 08:59 UTC

**Comment by kabike** [comment] 2018-03-21 10:06
thanks
