### ISSUE TITLE
DeleteByQueryConcurrentTests.testConcurrentDeleteByQueriesOnDifferentDocs fails reproducibly 

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#62894] opened 2020-09-24 16:47 UTC
**Build scan**:
https://gradle-enterprise.elastic.co/s/p5tyls66tnmwk

**Repro line**:
./gradlew ':modules:reindex:test' --tests "org.elasticsearch.index.reindex.DeleteByQueryConcurrentTests.testConcurrentDeleteByQueriesOnDifferentDocs" -Dtests.seed=9E9F2FA9C4BE676F -Dtests.security.manager=true -Dtests.locale=bg-BG -Dtests.timezone=Pacific/Guam -Druntime.java=11

**Reproduces locally?**:
yes
**Applicable branches**:
master (did not check other)
**Failure history**:

**Failure excerpt**:
```
   Expected: updated matches <0L> and created matches <0L> and deleted matches <30L> and versionConflicts matches <0L> and failures size matches <0> and reason cancelled matches null and slices matches an empty collection
             but: was <BulkByScrollResponse[took=344ms,timed_out=false,sliceId=null,updated=0,created=0,deleted=30,batches=1,versionConflicts=2,noops=0,retries=0,throttledUntil=0s,bulk_failures=[{"index":"test","id":"Z8z-wHQB_tzBedAeplcO","cause":{"type":"version_conflict_engine_exception","reason":"[Z8z-wHQB_tzBedAeplcO]: version conflict, required seqNo [4], primary term [1]. but no document was found","index_uuid":"ABeYZSUDS5C5R7GnY53S1A","shard":"1","index":"test"},"status":409}, {"index":"test","id":"dMz-wHQB_tzBedAeplcY","cause":{"type":"version_conflict_engine_exception","reason":"[dMz-wHQB_tzBedAeplcY]: version conflict, required seqNo [13], primary term [1]. but no document was found","index_uuid":"ABeYZSUDS5C5R7GnY53S1A","shard":"3","index":"test"},"status":409}],search_failures=[]]>
            at __randomizedtesting.SeedInfo.seed([9E9F2FA9C4BE676F]:0)
            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
            at org.junit.Assert.assertThat(Assert.java:956)
            at org.junit.Assert.assertThat(Assert.java:923)
            at org.elasticsearch.index.reindex.DeleteByQueryConcurrentTests.lambda$testConcurrentDeleteByQueriesOnDifferentDocs$0(DeleteByQueryConcurrentTests.java:59)

```

**Comment by jimczi** [comment] 2020-09-24 19:27
Duplicate of #62609, the test is already muted on master and 7x, hence closing

**Closed by jimczi** 2020-09-24 19:27 UTC
Labels: :Core/Features/Features, >test-failure, Team:Core/Features
