### ISSUE TITLE
[CI] CcrRollingUpgradeIT » testUniDirectionalIndexFollowing

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#59627] opened 2020-07-15 14:52 UTC
**Build scan**:
https://gradle-enterprise.elastic.co/s/uxnrmjs7mcwve

**Repro line**:
`REPRODUCE WITH: ./gradlew ':x-pack:qa:rolling-upgrade-multi-cluster:v6.8.11#leader#upgradedClusterTest' --tests "org.elasticsearch.upgrades.CcrRollingUpgradeIT.testUniDirectionalIndexFollowing" -Dtests.seed=FBED9F657A3AE974 -Dtests.security.manager=true -Dtests.locale=th -Dtests.timezone=Europe/Riga -Druntime.java=8`

**Reproduces locally?**:
No

**Applicable branches**:
7.x

**Failure history**:
https://gradle-enterprise.elastic.co/s/uza2ofj3d32fe

**Failure excerpt**:

```
org.elasticsearch.client.ResponseException: method [PUT], host [http://127.0.0.1:35463], URI [/follower_index4/_ccr/follow?wait_for_active_shards=1], status line [HTTP/1.1 400 Bad Request] 
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Not all copies of follow shard are started"}],"type":"illegal_argument_exception","reason":"Not all copies of follow shard are started"},"status":400}
```
https://gradle-enterprise.elastic.co/s/uxnrmjs7mcwve/tests/:x-pack:qa:rolling-upgrade-multi-cluster:v6.8.11%23leader%23upgradedClusterTest/org.elasticsearch.upgrades.CcrRollingUpgradeIT/testUniDirectionalIndexFollowing?anchor=e30&focused-exception-line=0-0

**Comment by tlrx** [comment] 2020-07-15 14:55
Duplicate of #59625

**Closed by tlrx** 2020-07-15 14:55 UTC
Labels: :Distributed/CCR, >test-failure, Team:Distributed
