### ISSUE TITLE
The maven central elasticsearch-6.2.3.jar is missing several logging class files 

### ISSUE THREAD

**Issue by pavocristatus** [elastic/elasticsearch#29303] opened 2018-03-29 22:03 UTC
We use the following sbt dependencies to make a scala build for our application

                      "org.elasticsearch" % "elasticsearch" % "6.2.3",
                         "org.elasticsearch.client" % "transport" % "6.2.3",
                         "org.apache.logging.log4j" % "log4j-api" % "2.9.1",
                         "org.apache.logging.log4j" % "log4j-core" % "2.9.1"

When executing our application we see an error when it talks to Elasticsearch (creates a new client connection with the following piece of code:

`lazy private val settings = Settings.builder()`
`                                         .put("cluster.name", ESClusterName)`
`                                         .put("client.transport.sniff", true)`
`                                         .put("client.transport.ping_timeout", DefaultTimeout) //The time to wait for a ping response from a node. Defaults to 5s`
`                                                           .build()`
`
`
`  val client: TransportClient = new PreBuiltTransportClient(settings)`
`  .addTransportAddress(new TransportAddress(InetAddress.getByName(NodeName), port))
`

with the following error:

`Exception in thread "main" java.lang.NoClassDefFoundError: org/elasticsearch/common/logging/Loggers`
`	at org.elasticsearch.common.unit.ByteSizeValue.<clinit>(ByteSizeValue.java:36)`
`	at org.elasticsearch.common.network.NetworkService.<clinit>(NetworkService.java:56)`
	`at org.elasticsearch.transport.TcpTransport.<clinit>(TcpTransport.java:151)`
	`at org.elasticsearch.client.transport.TransportClient.newPluginService(TransportClient.java:100)`
	`at org.elasticsearch.client.transport.TransportClient.buildTemplate(TransportClient.java:130)`
	`at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:273)`
	`at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:128)`
	`at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:114)`
	`at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:104) `
 .....
......
......

Extracting the contents of the elasticsearch-6.2.3.jar file reveals that the Loggers.class is not available under the "package org.elasticsearch.common.logging;" as expected. Can you please look into it and provide a jar that resolves the issue?

Thanks in advance.

**Comment by jasontedor** [comment] 2018-03-29 22:28
It looks like you are not pulling in all transitive dependencies. In particular, the `org.elasticsearch:elasticsearch` artifact is dependent on (amongst others) `org.elasticsearch:elasticsearch-core`. Looking at this JAR:

```
18:27:04 [jason:~] $ mvn org.apache.maven.plugins:maven-dependency-plugin:2.1:get -DrepoUrl=https://repo.maven.apache.org/maven2 -Dartifact=org.elasticsearch:elasticsearch-core:6.2.3
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.1:get (default-cli) @ standalone-pom ---
Downloading from central: https://repo.maven.apache.org/maven2/org/elasticsearch/elasticsearch-core/6.2.3/elasticsearch-core-6.2.3.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/elasticsearch/elasticsearch-core/6.2.3/elasticsearch-core-6.2.3.jar (19 kB at 49 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.188 s
[INFO] Finished at: 2018-03-29T18:27:10-04:00
[INFO] ------------------------------------------------------------------------
18:27:10 [jason:~] $ jar tf ~/.m2/repository/org/elasticsearch/elasticsearch-core/6.2.3/elasticsearch-core-6.2.3.jar | grep Loggers
org/elasticsearch/common/logging/Loggers.class
```

shows that it contains exactly the dependency that is missing for you. I am closing this as not a bug. If you need additional help, please use the [forum](https://discuss.elastic.co). Of course, feel free to link from here to there for visibility.

**Closed by jasontedor** 2018-03-29 22:28 UTC
