### ISSUE TITLE
Korean tokenizer (Nori) add a weird digit to a token

### ISSUE THREAD

**Issue by drake-jin** [elastic/elasticsearch#50726] opened 2020-01-08 03:56 UTC
@jimczi 

# Summary
It results is so weird, 
'정진해온' '정진'(Verb) It's a wrong morpheme.
but.. 'nori tokenizer' spit out a weird result like this
> '정진해온' => '정진7' '하' '아' '온'
How should I resolve this issue about 정진`7`?

### test env.
- elasticsearch version: 6.7.2
- plugins: only nori
- java: open jdk 1.8
- os: ubuntu 17.04

### input
```
GET /test/_analyze
{
  "text": """
정진해온
  """,
  "explain": true, 
  "char_filter": [], 
  "tokenizer": "nori_tokenizer"
}
```

### output

```
{
  "detail" : {
    "custom_analyzer" : true,
    "tokenizer" : {
      "name" : "nori_tokenizer",
      "tokens" : [
        {
          "token" : "정진7",
          "start_offset" : 0,
          "end_offset" : 3,
          "type" : "word",
          "position" : 0,
          "bytes" : "[ec a0 95 ec a7 84 37]",
          "leftPOS" : "NNG(General Noun)",
          "morphemes" : null,
          "posType" : "MORPHEME",
          "positionLength" : 1,
          "reading" : null,
          "rightPOS" : "NNG(General Noun)",
          "termFrequency" : 1
        },
        {
          "token" : "하",
          "start_offset" : 0,
          "end_offset" : 3,
          "type" : "word",
          "position" : 1,
          "bytes" : "[ed 95 98]",
          "leftPOS" : "XSV(Verb Suffix)",
          "morphemes" : null,
          "posType" : "MORPHEME",
          "positionLength" : 1,
          "reading" : null,
          "rightPOS" : "XSV(Verb Suffix)",
          "termFrequency" : 1
        },
        {
          "token" : "아",
          "start_offset" : 0,
          "end_offset" : 3,
          "type" : "word",
          "position" : 2,
          "bytes" : "[ec 95 84]",
          "leftPOS" : "E(Verbal endings)",
          "morphemes" : null,
          "posType" : "MORPHEME",
          "positionLength" : 1,
          "reading" : null,
          "rightPOS" : "E(Verbal endings)",
          "termFrequency" : 1
        },
        {
          "token" : "오",
          "start_offset" : 3,
          "end_offset" : 4,
          "type" : "word",
          "position" : 3,
          "bytes" : "[ec 98 a4]",
          "leftPOS" : "VX(Auxiliary Verb or Adjective)",
          "morphemes" : null,
          "posType" : "MORPHEME",
          "positionLength" : 1,
          "reading" : null,
          "rightPOS" : "VX(Auxiliary Verb or Adjective)",
          "termFrequency" : 1
        },
        {
          "token" : "ᆫ",
          "start_offset" : 3,
          "end_offset" : 4,
          "type" : "word",
          "position" : 4,
          "bytes" : "[e1 86 ab]",
          "leftPOS" : "E(Verbal endings)",
          "morphemes" : null,
          "posType" : "MORPHEME",
          "positionLength" : 1,
          "reading" : null,
          "rightPOS" : "E(Verbal endings)",
          "termFrequency" : 1
        }
      ]
    }
  }
}

```

**Comment by drake-jin** [comment] 2020-01-08 05:20
# Test on mecab
mecab doing like this..  It's same Nori result. Oh.. god...

![image](https://user-images.githubusercontent.com/10516961/71952386-d958b380-3221-11ea-9f0f-2713b3b2b2b3.png)

**Comment by drake-jin** [comment] 2020-01-08 08:30
I report this to mecab-ko team.
If has any answer about this link, I'll notice to you. thanks. 

https://groups.google.com/forum/?hl=ko#!topic/eunjeon/eClaa6E47g0

**Comment by jimczi** [comment] 2020-01-08 09:09
Thanks for reporting @drake-jin . If there is no answer in the forum you can try to open an issue directly in https://bitbucket.org/eunjeon/mecab-ko-dic since you identified the [root cause](https://bitbucket.org/eunjeon/mecab-ko-dic/src/df15a487444d88565ea18f8250330276497cc9b9/seed/Inflect.csv#lines-35061). 
In the meantime you can use the [user dictionary](https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-nori-tokenizer.html) to override this rule and preserve the original form. I hope you don't mind if I close this issue but any update to the mecab-ko-dic must be applied to Lucene first so when/if a new version of the dictionary is available we should track it there.

**Closed by jimczi** 2020-01-08 09:09 UTC

**Comment by drake-jin** [comment] 2020-01-08 09:13
:) Thanks. I'll report this link(https://bitbucket.org/eunjeon/mecab-ko-dic). too.
If have any notice, I'll notice to you.

PS.
> `.... you can use the user dictionary to override this rule and preserve the original form. ...`

=> Sadly, It didn't work...

**Comment by jimczi** [comment] 2020-01-08 09:18
> Sadly, It didn't work...

Can you be more specific ? What did you try ?

**Comment by drake-jin** [comment] 2020-01-08 09:31
Oops. It's my mistake.
 
![image](https://user-images.githubusercontent.com/10516961/71966477-066a8d80-3245-11ea-98b8-98790e0fa677.png)
