### ISSUE TITLE
Index Lifecycle Policies effecting system indices in version 7.7

### ISSUE THREAD

**Issue by rgarcia89** [elastic/elasticsearch#56890] opened 2020-05-18 09:59 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 7.7

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:
In elasticsearch version 7.7 system indicies are also being affected by Index Lifecycle Policies. This causes some serious issues when it comes to freezing, changing to read-only or even deleting indicies using policies.

**Steps to reproduce**:
Update to version 7.7 and list the managed vs unmanaged indicies

Screenshots version 7.6.2 vs 7.7.0
![image](https://user-images.githubusercontent.com/4134730/82200129-ec317200-98fe-11ea-81c1-bd929267ddfa.png)
![image](https://user-images.githubusercontent.com/4134730/82200145-f3f11680-98fe-11ea-9b31-00e1d4d6a08f.png)
![image](https://user-images.githubusercontent.com/4134730/82200164-fb182480-98fe-11ea-903b-be403871e068.png)

**Comment by joegallo** [comment] 2020-12-10 15:31
@rgarcia89 would it be possible for you to share the relevant parts of the details for `denic-index-policy`? I'm curious about the exact scenario by which, for example, your `.kibana_1` index ended up being managed by ILM.

**Comment by rgarcia89** [comment] 2020-12-10 15:54
@joegallo sure please fine them below:
If I create a template as shown below, hidden indicies will also get assigned the policy.
```
PUT _template/denic-index-template?include_type_name
{
  "order": 100,
  "index_patterns": [
    "*"
  ],
  "settings": {
    "index": {
      "format": "1",
      "lifecycle": {
        "name": "denic-index-policy"
      },
...
}
```
In order to not run into this issue anymore, I had to use a pretty ugly workaround, which at least works:
```
PUT _template/denic-index-template?include_type_name
{
  "order": 100,
  "index_patterns": [
    "a*",
    "b*",
    "c*",
    "d*",
    "e*",
...
```

**Comment by dakrone** [comment] 2020-12-10 18:10
@joegallo `*` templates should be ignored for hidden indices, as per:

https://github.com/elastic/elasticsearch/blob/81a1e9eda8e6183f5237786246f6dced26a10eaf/server/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexTemplateService.java#L347-L353

So either the `.kibana_1` index isn't appropriately marked as hidden, or else there is a bug elsewhere.

**Comment by rgarcia89** [comment] 2020-12-10 20:14
@dakrone in that case there must be a bug, because I can 100% confirm that they are not ignored

**Comment by joegallo** [comment] 2020-12-10 23:09
I've spun up a 7.6.2 and a 7.7.0 cluster, and created a `test-template` on both. It looks like this:

```
GET _template/test-template
{
  "test-template": {
    "index_patterns": [
      "*"
    ],
    "mappings": {
      "properties": {},
      "_meta": {},
      "_source": {}
    },
    "aliases": {},
    "order": 0,
    "settings": {
      "index": {
        "number_of_replicas": "3"
      }
    }
  }
}
```

Then I created a dot-prefixed index on both versions using `PUT .myowndotindex` and then fetched the settings:

```
GET .myowndotindex/_settings
{
  ".myowndotindex": {
    "settings": {
      "index": {
        "provided_name": ".myowndotindex",
        "number_of_replicas": "3", # <---<<<
        "uuid": "5WrPU2erSJSIBJRGn4z5-Q",
        "number_of_shards": "1",
        "creation_date": "1607641206788",
        "version": {
          "created": "7070099"
        }
      }
    }
  }
}
```

Crucially, both versions ended up with the `number_of_replicas` that I'd have expected if they were created via the template. And that makes some amount of sense to me, in that I don't see any special code around ignoring dot-prefixed indices when looking up templates (i.e. AFAICT `"*"` has always meant "all indices", at least w.r.t. dot-prefixes).

@rgarcia89 are you perhaps seeing an order of operations artifact? If you have a cluster with a `.kibana_1` and other system indices already in existence, and you add a `"*"` template to it, it doesn't retroactively apply that template to the already created indices, BUT OTOH if you created the `"*"` template before those indices were created, then it would.

**Comment by rgarcia89** [comment] 2020-12-13 13:41
@joegallo thats correct, templates are not being applied retroactively, which is totally fine for me. However, of course I created the template before the next hidden index has been created. The `"*"` template is being used as kind of catch all for indicies that do not match any other template.

From my perspective the documentations says that hidden indicies will not be addressed by the `"*"` so I don't understand why it is acting differently. Thinking about the fact, that these indicies are necessary for running kibana I would expect some kind protection that ensures that hidden or at least system related indicies cannot be touched by an lifecycle policy

**Comment by rgarcia89** [comment] 2021-01-06 17:56
@joegallo any update on the request?

**Comment by joegallo** [comment] 2021-01-06 18:52
> From my perspective the documentations says that hidden indicies will not be addressed by the `"*"`

Can you link me to where the docs indicate this? I'm guessing there's a difference between the docs and the behavior, or perhaps the expected behavior, and I'd like to narrow in on that.

**Comment by rgarcia89** [comment] 2021-01-06 18:58
> Can you link me to where the docs indicate this? I'm guessing there's a difference between the docs and the behavior, or perhaps the expected behavior, and I'd like to narrow in on that.

This is what I understand from here: https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-index.html#hidden-indices

**Comment by stefnestor** [comment] 2022-02-24 23:21
Finding this way later. IIUC if you want to set a "global but system indices" ILM policy, you need to set `index_patterns:*,-.*` (maybe works w/Datastreams?). If you only set `index_patterns:*` will you encounter system index access errors starting 8.0 or will they be auto-filtered out? (Thinking of docs here but not sure how to self-serve, sorry: https://github.com/elastic/elasticsearch/pull/84377)

**Closed** 2022-09-06 08:59 UTC
Labels: >bug, :Data Management/ILM+SLM, Team:Data Management
