### ISSUE TITLE
 Maybe memory leak still in IndicesQueryCache$ElasticsearchLRUQueryCache (6.5.3)

### ISSUE THREAD

**Issue by wuyunfeng** [elastic/elasticsearch#57400] opened 2020-06-01 07:22 UTC
**Elasticsearch version** (`bin/elasticsearch --version`):
6.5.3
**Plugins installed**: 
[ respository-hdfs, analysis-ik]

**JVM version** (`java -version`):
1.8
**OS version** (`uname -a` if on a Unix-like system):
Centos 7.x
**Description of the problem including expected versus actual behavior**:
Our cluster have 13 nodes (master/data),  about 20 index with 108 shards,  400GB disk-usage total,  number_of_replicas: 1.

```
GET _nodes/stats/indices/segments
```

```
"indices": {
            "segments": {
               "count": 309,
               "memory_in_bytes": 252406692,
               "terms_memory_in_bytes": 220566093,
               "stored_fields_memory_in_bytes": 24673184,
               "term_vectors_memory_in_bytes": 4013664,
               "norms_memory_in_bytes": 50176,
               "points_memory_in_bytes": 2801227,
               "doc_values_memory_in_bytes": 302348,
               "index_writer_memory_in_bytes": 2476343,
               "version_map_memory_in_bytes": 26305,
               "fixed_bit_set_memory_in_bytes": 11819960,
               "max_unsafe_auto_id_timestamp": -1,
               "file_sizes": {}
            }
         }
      }
```

```
GET _nodes/stats/indices/query_cache
```

```
         "indices": {
            "query_cache": {
               "memory_size_in_bytes": 460797529,
               "total_count": 281194614,
               "hit_count": 8502228,
               "miss_count": 272692386,
               "cache_size": 17142,
               "cache_count": 17142,
               "evictions": 0
            }
         }
```

Continuously growing memory usage eventually leading to periodically FullGC result in Cluster not available. All nodes have 128G  physical  memory，31G JVM Heap, 26cores.

I just dump the heap and analysis the heap with `MAT`, found ElasticsearchLRUQueryCache retained about 21,613,314,000 heap size.

OverView:

![image](https://user-images.githubusercontent.com/5183061/83385777-66dcb000-a41c-11ea-9eae-83b85605349b.png)

Problem Suspect  1 `org.elasticsearch.indices.IndicesQueryCache$ElasticsearchLRUQueryCache`: 

Shortest Paths To the Accumulation Point
![image](https://user-images.githubusercontent.com/5183061/83384368-b66dac80-a419-11ea-8ccb-3385d5529d3b.png)

Accumulated Objects in Dominator Tree
![image](https://user-images.githubusercontent.com/5183061/83384398-c4bbc880-a419-11ea-9f67-b89b1f0225dc.png)

Accumulated Objects by Class in Dominator Tree
![image](https://user-images.githubusercontent.com/5183061/83384447-e1580080-a419-11ea-9129-0ddb8696716e.png)

All Accumulated Objects by Class 
![image](https://user-images.githubusercontent.com/5183061/83384474-eb79ff00-a419-11ea-915e-38a42f64ac7c.png)
![image](https://user-images.githubusercontent.com/5183061/83384493-f16fe000-a419-11ea-8c45-a1e07202e39b.png)

I notice some user which  use older version(2.4.2) encountered similar problem which was resolved by @jpountz ：

https://github.com/elastic/elasticsearch/issues/22742
https://issues.apache.org/jira/browse/LUCENE-7652

but periodically FullGC on all node of the cluster about one-week  recently. It seems some query maybe reference the `SegmentReader` indirectly， and I puzzled with the `17,830,353,512`  retained heap size by `org.apache.lucene.index.SegmentReader`  seems the old `segment reader` which were closed but still has some reference? 

From `All Accumulated Objects by Class`, I noticed `20,886,047,792 ` Shallow Heap by `long[]` about 1,379,835 Objects.  this long[] is the  `bit set` cached by LRUQueryCache and some meta data of the `reader` such as `StoredFieldsReader` 、`doc value producer` etc?

Class_Histogram

![image](https://user-images.githubusercontent.com/5183061/83390294-2b45e400-a424-11ea-94fc-0a5e46b06f81.png)

`FixedBits` have 40,096  objects and retained heap >= 23,494,510,832, which just `long[] bits`

 `FixedBits` was used for  `SegmentReader#liveDocs or hardLiveDocs` and `LRUQueryCache`.

**Comment by wuyunfeng** [comment] 2020-06-01 07:25
@jpountz

**Comment by wuyunfeng** [comment] 2020-06-01 10:51
It seems related with this issue?:
https://issues.apache.org/jira/browse/LUCENE-8017

![image](https://user-images.githubusercontent.com/5183061/83402235-ed06ef80-a438-11ea-8ffa-9e3320b947ec.png)

**Comment by wuyunfeng** [comment] 2020-06-01 12:20
In those top class, the FunctionScoreQuery or ScriptQuery would reference the `LeafReaderContext`

**Comment by Bukhtawar** [comment] 2020-06-25 17:29
I have noticed a similar issue in 7.4 as well. I believe this issue is still not fixed. @romseygeek can you please confirm


<img width="1272" alt="Screenshot 2020-06-25 at 12 53 18 PM" src="https://user-images.githubusercontent.com/12809319/85769056-44963380-b737-11ea-8179-50d3facc06d4.png">


<img width="1276" alt="Screenshot 2020-06-25 at 12 59 25 PM" src="https://user-images.githubusercontent.com/12809319/85769076-49f37e00-b737-11ea-92cc-8ed208c70678.png">

**Comment by jpountz** [comment] 2020-07-20 07:56
@Bukhtawar This particular issue is fixed in Lucene 8.3/Elasticsearch 7.5.

@wuyunfeng Sorry for the late response. Your boolean queries are large, they must be indirectly referencing queries that either reference readers or large objects. It might be due to GlobalOrdinalsWithScoreQuery like @Bukhtawar but it might be something else as well. If/when this reproduces, could you look at the queries that your boolean queries are referencing? Upgrading to a more recent version might help too as we fixed a couple bugs that could explain this since 6.5.3 was released.

**Comment by Bukhtawar** [comment] 2020-07-20 08:01
Thanks @jpountz for confirming

**Comment by wuyunfeng** [comment] 2020-07-20 10:45
@jpountz  We have a lot of `match` or `match_phrase` query in our `boolean` query, and a `script_score ` for custom scoring, and `aggs` for some field which like below:

```

{
    "query":{
        "function_score":{
            "query":{
                "bool":{
                    "must":[
                        {
                            "bool":{
                                "should":[
                                    {
                                        "match_phrase":{
                                            "fieldEnt.py":{
                                                "query":"Some Value",
                                                "boost":1
                                            }
                                        }
                                    },
                                    {
                                        "match":{
                                            "fieldEnt.content":{
                                                "query":"Some Value",
                                                "boost":9,
                                                "operator":"and",
                                                "analyzer":"ik_max_word"
                                            }
                                        }
                                    },
                                    {
                                        "match":{
                                            "fieldRN":{
                                                "query":"Some Value",
                                                "boost":1,
                                                "operator":"and"
                                            }
                                        }
                                    },
                                    {
                                        "match":{
                                            "scope":{
                                                "query":"Some Value",
                                                "boost":1,
                                                "operator":"and"
                                            }
                                        }
                                    },
                                    {
                                        "match":{
                                            "addr":{
                                                "query":"Some Value",
                                                "boost":1,
                                                "operator":"and"
                                            }
                                        }
                                    },
                                    {
                                        "match":{
                                            "fieldP":{
                                                "query":"Some Value",
                                                "boost":30,
                                                "operator":"and"
                                            }
                                        }
                                    },
                                    {
                                        "match":{
                                            "shareholders":{
                                                "query":"Some Value",
                                                "boost":10,
                                                "operator":"and"
                                            }
                                        }
                                    },
                                    {
                                        "match":{
                                            "directors":{
                                                "query":"Some Value",
                                                "boost":20,
                                                "operator":"and"
                                            }
                                        }
                                    },
                                    {
                                        "match":{
                                            "coreNames":{
                                                "query":"Some Value",
                                                "boost":30,
                                                "operator":"and",
                                                "analyzer":"ik_max_word"
                                            }
                                        }
                                    },
                                    {
                                        "match":{
                                            "keyNames":{
                                                "query":"Some Value",
                                                "boost":1000,
                                                "operator":"and"
                                            }
                                        }
                                    },
                                    {
                                        "match_phrase":{
                                            "markName":{
                                                "query":"Some Value",
                                                "boost":10
                                            }
                                        }
                                    },
                                    {
                                        "match":{
                                            "formerNames":{
                                                "query":"Some Value",
                                                "boost":30,
                                                "operator":"and"
                                            }
                                        }
                                    },
                                    {
                                        "match":{
                                            "projectBrandName":{
                                                "query":"Some Value",
                                                "boost":50,
                                                "operator":"and"
                                            }
                                        }
                                    },
                                    {
                                        "match":{
                                            "abbrNames":{
                                                "query":"Some Value",
                                                "boost":200,
                                                "operator":"and"
                                            }
                                        }
                                    },
                                    {
                                        "match_phrase":{
                                            "siteName":{
                                                "query":"Some Value",
                                                "boost":5
                                            }
                                        }
                                    },
                                    {
                                        "match_phrase":{
                                            "siteUrl":{
                                                "query":"Some Value",
                                                "boost":5
                                            }
                                        }
                                    },
                                    {
                                        "match_phrase":{
                                            "icpNo":{
                                                "query":"Some Value",
                                                "boost":5
                                            }
                                        }
                                    }
                                ]
                            }
                        }
                    ]
                }
            },
            "script_score":{
                "script":{
                    "inline":"int entweight=10000;if(doc[\"weight\"].value==1) {entweight=10000;if(doc[\"entType\"].value==\"Some Value\") {entweight = entweight - 100;}if(doc[\"entType\"].value==\"Some Value\" || doc[\"entType\"].value==null) {entweight=500;if(doc[\"openStatus\"].value==\"注销\" || doc[\"openStatus\"].value==\"Some Value\") {entweight=5;}} else if(doc[\"openStatus\"].value==\"Some Value\" || doc[\"openStatus\"].value==\"Some Value\") {entweight=1000;}if(doc[\"weight\"].value==4) {entweight=0;}}return  Math.sqrt(doc[\"zxScore\"].value)*10*8.5 + _score+entweight;"
                }
            }
        }
    },
    "from":0,
    "size":50,
    "aggs":{
        "provinceCode":{
            "terms":{
                "field":"provinceCode",
                "size":300
            }
        },
        "regCapLevel":{
            "terms":{
                "field":"regCapLevel",
                "size":300
            }
        },
        "entType":{
            "terms":{
                "field":"entType",
                "size":300
            }
        },
        "openStatus":{
            "terms":{
                "field":"openStatus",
                "size":300
            }
        },
        "startYear":{
            "terms":{
                "field":"startYear",
                "size":300
            }
        },
        "discredited":{
            "terms":{
                "field":"discredited",
                "size":300
            }
        }
    },
    "highlight":{
        "fields":[
            {
                "fieldEnt.content":{
                    "type":"unified"
                }
            },
            {
                "fieldRN":{
                    "type":"unified"
                }
            },
            {
                "fieldP":{
                    "type":"unified"
                }
            },
            {
                "directors":{
                    "type":"unified"
                }
            },
            {
                "addr":{
                    "type":"unified"
                }
            },
            {
                "scope":{
                    "type":"unified"
                }
            },
            {
                "markName":{
                    "type":"unified"
                }
            },
            {
                "shareholders":{
                    "type":"unified"
                }
            },
            {
                "formerNames":{
                    "type":"unified"
                }
            },
            {
                "projectBrandName":{
                    "type":"unified"
                }
            },
            {
                "siteUrl":{
                    "type":"unified"
                }
            },
            {
                "siteName":{
                    "type":"unified"
                }
            },
            {
                "icpNo":{
                    "type":"unified"
                }
            },
            {
                "keyNames":{
                    "type":"unified"
                }
            },
            {
                "coreNames":{
                    "type":"unified"
                }
            },
            {
                "abbrNames":{
                    "type":"unified"
                }
            }
        ]
    }
}'
```

**Comment by wuyunfeng** [comment] 2020-07-20 10:47
In my `MAT` analysis result, I cannot see the `the queries that your boolean queries are referencing`, but I can provide the origin query, does it ok?

**Comment by jpountz** [comment] 2020-07-20 14:48
I don't think that the query you shared is responsible for the memory we're seeing retained by the cache. Even though your queries have many clauses, MAT reports that your boolean queries consume 25MB of heap, which is a lot for a query. So I'd be curious to see what type of queries are used as clauses of these boolean queries. Are some of your indices using parent/child relationships? You might be affected by the same bug as @Bukhtawar.

**Comment by wuyunfeng** [comment] 2020-07-20 14:57
@jpountz I would confirm that tomorrow, and now  I just know our user maybe using nested-object. After we add more nodes to our ES Cluster, this fullgc have not appear again.

**Comment by wuyunfeng** [comment] 2020-07-20 15:02
`consume 25MB of heap ` you means some - the cached `BitSetProducer`?

**Comment by jpountz** [comment] 2020-07-20 15:27
No, I was looking at the "Accumulated Objects in Dominator Tree" table that you shared a screenshot of.

**Comment by wuyunfeng** [comment] 2020-07-21 04:58
@jpountz  Our user have nested query likes below:

```
{
   "query": {
      "function_score": {
         "query": {
            "bool": {
               "must": [
                  {
                     "nested": {
                        "path": "eid",
                        "query": {
                           "bool": {
                              "must": [
                                 {
                                    "match": {
                                       "eid.bdCode": {
                                          "query": "value",
                                          "boost": 1,
                                          "operator": "and"
                                       }
                                    }
                                 }
                              ]
                           }
                        }
                     }
                  }
               ]
            }
         },
         "script_score": {
            "script": {
               "inline": "_score"
            }
         }
      }
   },
   "from": 0,
   "size": 10,
   "aggs": {
      "ops": {
         "terms": {
            "field": "opsField",
            "size": 300
         }
      }
   }
}
```
This query would use `ESToParentBlockJoinQuery(ES)/ToParentBlockJoinQuery(Lucene)`

**Comment by wuyunfeng** [comment] 2020-07-21 05:13
I noticed this Lucene PR: https://github.com/apache/lucene-solr/pull/963/ ,  some comments add by @jimczi 

```
     // disable caching because this query relies on a top reader context
      // and holds a bitset of matching ordinals that cannot be accounted in
      // the memory used by the cache
```
ToParentBlockJoinQuery holds a `BitSetProducer` which cached by ES's `BitsetFilterCache`, is this the reason for our ES cluster `fullgc` periodically?

**Comment by jpountz** [comment] 2020-07-21 08:50
@wuyunfeng This looks like a likely cause of the problem you are seeing to me.

**Comment by wuyunfeng** [comment] 2020-07-21 08:57
@jpountz  the reason is what I mentioned? 

> ToParentBlockJoinQuery holds a `BitSetProducer` which cached by ES's `BitsetFilterCache`, `BitsetFilterCache` and `BitSetProducer` would  reference the `readers ` ,is this the reason for our ES cluster `fullgc` periodically?

**Comment by jpountz** [comment] 2020-07-21 09:01
Yes this is correct. I can't be 100% sure but this looks plausible given the symptoms and the query you shared.

**Comment by wuyunfeng** [comment] 2020-07-21 09:29
@jpountz Can we add the same cache policy for `ToParentBlockJoinQuery` like this PR : https://github.com/apache/lucene-solr/pull/963

I will continue to pay attention all query sent to ES today.

**Comment by jpountz** [comment] 2020-07-21 09:45
@wuyunfeng Sorry I got confused and mixed up issues. I don't think that `ToParentBlockJoinQuery` has a problem. It doesn't directly reference a bitset like `GlobalOrdinals(WithScore)Query`, and the reader keys do not reference the readers (it used to be the case long ago, but this has been fixed in Lucene 7.0/Elasticsearch 6.0).

**Comment by jpountz** [comment] 2020-07-21 10:14
> I will continue to pay attention all query sent to ES today.

IMO the most efficient strategy would be to further analyze the heap dump next time you get one.

**Comment by wuyunfeng** [comment] 2020-07-21 10:43
@jpountz 

>  I don't think that ToParentBlockJoinQuery has a problem. It doesn't directly reference a bitset like GlobalOrdinals(WithScore)Query

`ToParentBlockJoinQuery` reference the `parentBits` by `BitsetFilterCache` which cached in `Cache<IndexReader.CacheKey, Cache<Query, Value>> loadedFilters` 

> IMO the most efficient strategy would be to further analyze the heap dump next time you get one.

OK. I would close this issue .  Do you mind reopening this issue when I get the heap dump next time ?

**Comment by wuyunfeng** [comment] 2020-07-21 10:46
> but this has been fixed in Lucene 7.0/Elasticsearch 6.0

Can you share the PR or issue for this bug-fix?

**Comment by wuyunfeng** [comment] 2020-07-21 11:02
![image](https://user-images.githubusercontent.com/5183061/88047632-81ade400-cb84-11ea-9e82-013bebd58dbc.png)

BTW, the long[]  consume almost 20G+ JVM memory, does it is the `bitset`?

![image](https://user-images.githubusercontent.com/5183061/88047684-94c0b400-cb84-11ea-89a0-35d15b3eeec6.png)

SegmentReader consume almost 17G+.

I just confused with this two object `SegmentReader` and `long[]`

**Comment by jpountz** [comment] 2020-07-21 11:43
Hard to tell, these long[] could be bitsets, but Lucene and Elasticsearch also use large long[] arrays elsewhere so I wouldn't jump to conclusions.

My suspicion is that you're seeing so much RAM usage for SegmentReader because it indirectly points to many of the long[] arrays that are in your heap. This typically happens because caches register listeners on to readers, which makes the readers references all caches.

**Closed** 2020-07-27 04:56 UTC
Labels: :Search/Search, >bug, Team:Search, feedback_needed

**Comment by arielzach** [comment] 2020-10-21 23:40
I don't know what state this issue is in but I'm having a similar problem with ES7.8, I'm using the docker version:

docker.elastic.co/elasticsearch/elasticsearch:7.8.0

![image](https://user-images.githubusercontent.com/64101789/96801000-0820ce80-13dd-11eb-81b0-ea10ea1b8e72.png)
![image](https://user-images.githubusercontent.com/64101789/96801050-238bd980-13dd-11eb-8427-d03b09cd71ca.png)
![image](https://user-images.githubusercontent.com/64101789/96801070-2dadd800-13dd-11eb-9688-10170bb431f0.png)
![image](https://user-images.githubusercontent.com/64101789/96801083-37cfd680-13dd-11eb-8568-b90870820407.png)
![image](https://user-images.githubusercontent.com/64101789/96801176-677ede80-13dd-11eb-9e90-fea925d0560d.png)

@wuyunfeng could you solve this problem?
