### ISSUE TITLE
Elasticsearch crashed with same error

### ISSUE THREAD

**Issue by amitdaniel86** [elastic/elasticsearch#10052] opened 2015-03-10 15:33 UTC
Hey , 

First of all this is the error : 

[2015-03-10 14:59:24,165][WARN ][indices.breaker          ] [log1-01] [FIELDDATA] New used memory 64378163272 [59.9gb] from field [@timestamp] would be larger than configured breaker: 64356483072 [59.9gb], breaking
[2015-03-10 14:59:24,166][DEBUG][action.search.type       ] [log1-01] [logstash-2015.03.09][0], node[Tm4cqA_iQHOrY-rMhPR7Dg], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@7533f62d]
org.elasticsearch.search.query.QueryPhaseExecutionException: [logstash-2015.03.09][0]: query[ConstantScore(*:*)],from[0],size[0]: Query Failed [Failed to execute global facets]
	at org.elasticsearch.search.facet.FacetPhase.execute(FacetPhase.java:193)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:171)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:275)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: org.elasticsearch.ElasticsearchException: org.elasticsearch.common.breaker.CircuitBreakingException: [FIELDDATA] Data too large, data for [@timestamp] would be larger than limit of [64356483072/59.9gb]
	at org.elasticsearch.index.fielddata.plain.AbstractIndexFieldData.load(AbstractIndexFieldData.java:80)
	at org.elasticsearch.search.facet.datehistogram.ValueDateHistogramFacetExecutor$Collector.setNextReader(ValueDateHistogramFacetExecutor.java:91)
	at org.elasticsearch.common.lucene.search.FilteredCollector.setNextReader(FilteredCollector.java:67)
	at org.apache.lucene.search.MultiCollector.setNextReader(MultiCollector.java:113)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:612)
	at org.elasticsearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:191)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:309)
	at org.elasticsearch.search.facet.FacetPhase.execute(FacetPhase.java:186)
	... 8 more
Caused by: org.elasticsearch.common.util.concurrent.UncheckedExecutionException: org.elasticsearch.common.breaker.CircuitBreakingException: [FIELDDATA] Data too large, data for [@timestamp] would be larger than limit of [64356483072/59.9gb]
	at org.elasticsearch.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
	at org.elasticsearch.common.cache.LocalCache.get(LocalCache.java:3937)
	at org.elasticsearch.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4739)
	at org.elasticsearch.indices.fielddata.cache.IndicesFieldDataCache$IndexFieldCache.load(IndicesFieldDataCache.java:174)
	at org.elasticsearch.index.fielddata.plain.AbstractIndexFieldData.load(AbstractIndexFieldData.java:74)
	... 15 more
Caused by: org.elasticsearch.common.breaker.CircuitBreakingException: [FIELDDATA] Data too large, data for [@timestamp] would be larger than limit of [64356483072/59.9gb]
	at org.elasticsearch.common.breaker.ChildMemoryCircuitBreaker.circuitBreak(ChildMemoryCircuitBreaker.java:97)
	at org.elasticsearch.common.breaker.ChildMemoryCircuitBreaker.addEstimateBytesAndMaybeBreak(ChildMemoryCircuitBreaker.java:148)
	at org.elasticsearch.index.fielddata.RamAccountingTermsEnum.flush(RamAccountingTermsEnum.java:71)
	at org.elasticsearch.index.fielddata.RamAccountingTermsEnum.next(RamAccountingTermsEnum.java:85)
	at org.elasticsearch.index.fielddata.ordinals.OrdinalsBuilder$3.next(OrdinalsBuilder.java:472)
	at org.elasticsearch.index.fielddata.plain.PackedArrayIndexFieldData.loadDirect(PackedArrayIndexFieldData.java:109)
	at org.elasticsearch.index.fielddata.plain.PackedArrayIndexFieldData.loadDirect(PackedArrayIndexFieldData.java:49)
	at org.elasticsearch.indices.fielddata.cache.IndicesFieldDataCache$IndexFieldCache$1.call(IndicesFieldDataCache.java:187)
	at org.elasticsearch.indices.fielddata.cache.IndicesFieldDataCache$IndexFieldCache$1.call(IndicesFieldDataCache.java:174)
	at org.elasticsearch.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4742)
	at org.elasticsearch.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at org.elasticsearch.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at org.elasticsearch.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at org.elasticsearch.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 19 more

Server details : 

Memory : 125GB ( Used - 54 GB , Free - 71 GB ) 
CPU :  16 

Can you please advice to me what is the issue ? what should i do ?

Thanks , 
Amit Daniel

**Comment by dakrone** [comment] 2015-03-10 17:17
@amitdaniel86 this exception is not crashing Elasticsearch, this exception means that Elasticsearch prevented you from loading too much data into memory and causing your server to go out of memory, you can see from this line:

Caused by: org.elasticsearch.ElasticsearchException: org.elasticsearch.common.breaker.CircuitBreakingException: [FIELDDATA] Data too large, data for [@timestamp] would be larger than limit of [64356483072/59.9gb]

This means that the `@timestamp` field is trying to load more than 60gb of memory. You will need to either limit the fielddata size (see: https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-fielddata.html#index-modules-fielddata) or you will need to switch to doc_values for the timestamp field: https://www.elastic.co/guide/en/elasticsearch/guide/current/doc-values.html#doc-values

**Comment by amitdaniel86** [comment] 2015-03-11 09:13
Can you help me to understand why the @timestamp field trying to load more than 60GB of data ? 
Maybe i have another issue to solve.

Thanks for your help !!! @dakrone

**Comment by dakrone** [comment] 2015-03-11 16:33
@amitdaniel86 field data is loaded for a field when that field is used for facets, aggregations, or when sorting on the field, so it could be any (or all) of those three.

**Comment by clintongormley** [comment] 2015-07-22 09:44
Looks like there is nothing to do here. Closing

**Closed by clintongormley** 2015-07-22 09:44 UTC

**Comment by bolee** [comment] 2015-07-31 08:29
How to switch doc_values,for every filed?

**Comment by majormashup** [comment] 2015-09-08 10:47
Switching to doc_values for every field is probably a bad idea. Looking at the documentation linked above I can see that doc_values will remove some load from the JVM heap however will increase disk I/O. I think the wise choice here is to find a good balance between field data and doc value.

**Comment by clintongormley** [comment] 2015-09-08 11:22
@majormashup sure doc values will take more I/O, but that is much better than stressing the heap.  doc values on all fields (except analyzed string fields) is the default in 2.0. This is to provide the best experience out of the box.

Of course, if you have fields that you never plan on using for sorting, aggs, or in scripts, then you can disable doc values for them and save I/O and disk space.

**Comment by majormashup** [comment] 2015-09-08 12:02
@clintongormley - thanks very much.
