### ISSUE TITLE
Score and Score in Explanation are Different when search type is dfs-query-then-fetch

### ISSUE THREAD

**Issue by nbqyqx** [elastic/elasticsearch#24335] opened 2017-04-26 13:55 UTC
**Elasticsearch version**:
2.3.3 BM25 Similarity
**Plugins installed**: []

**JVM version**:
open jdk 1.8
**OS version**:
mac os
**Description of the problem including expected versus actual behavior**:
Score and Score in Explanation are Different when search type is dfs-query-then-fetch

**Steps to reproduce**:
 1.Query==>/building-house-type/_search?pretty=true&search_type=dfs_query_then_fetch&explain
 {"term" : { "building_house_type_building_status" : "24" }}
 2.
 3.

**Provide logs (if relevant)**:
```json
  {
"_shard": 0,
"_node": "HqejV1BMTUWDQ0ghJIW6XQ",
"_index": "topsale-dev",
"_type": "building-house-type",
"_id": "18048",
"_score": 1.9397722,
"_source": {...},
"_explanation": {
"value": 1.8965808,
"description": "sum of:",
"details": [
  {
"value": 1.8965808,
"description": "weight(building_house_type_building_status:` in 0) [PerFieldSimilarity], result of:",
"details": [
  {
"value": 1.8965808,
"description": "score(doc=0,freq=1.0 = termFreq=1.0 ), product of:",
"details": [
  {
"value": 1.8965808,
"description": "idf(docFreq=556, maxDocs=3707)",
"details": [],
},
  {
"value": 1,
"description": "tfNorm, computed from:",
"details": [
  {
"value": 1,
"description": "termFreq=1.0",
"details": [],
},
  {
"value": 1.2,
"description": "parameter k1",
"details": [],
},
  {
"value": 0,
"description": "parameter b (norms omitted for field)",
"details": [],
}
],
}
],
}
],
},
```

**Describe the feature**:

Neal

**Comment by colings86** [comment] 2017-04-26 14:24
Could you explain what differences you are seeing that you don't expect? If I run the following script I get the same output for explain in both searches with only the score values being different (which is expected since the term statistics are taken from every shard rather than just the local shard:
```
PUT test

POST test/doc/1
{
  "foo":"bar"
}

POST test/doc/2
{
  "foo":"baz"
}

GET test/_search?pretty=true&search_type=dfs_query_then_fetch
{
  "explain": true, 
  "query": {
    "term": {
      "foo": "bar"
    }
  }
}

GET test/_search?pretty=true
{
  "explain": true, 
  "query": {
    "term": {
      "foo": "bar"
    }
  }
}
```

**Comment by jimczi** [comment] 2017-04-26 14:31
That's just a duplicate of https://github.com/elastic/elasticsearch/issues/15369 which is fixed in 5.0 by https://github.com/elastic/elasticsearch/issues/15369

**Closed by jimczi** 2017-04-26 14:31 UTC
Labels: :Search, :Similarities, feedback_needed

**Comment by nbqyqx** [comment] 2017-04-26 15:19
Any plan to fix in 2.3.x?

Neal Hu
nealhu@apache.org

**Comment by jimczi** [comment] 2017-04-26 15:37
@nbqyqx it would be 2.4.x but this is a minor bug really so might be better to just upgrade to 5.x instead ?

**Comment by nbqyqx** [comment] 2017-04-27 01:20
@jimczi yes, we are wanting for es jdbc importer to support 5.x, then we will upgrade to 5.x
