### ISSUE TITLE
Terms Aggregation inside a nested document and a filter in the main query returns or-linked counts

### ISSUE THREAD

**Issue by SimonJonasGubler** [elastic/elasticsearch#28262] opened 2018-01-17 12:36 UTC
**Elasticsearch version** : 5.6.5, 6.1.1

**Plugins installed**: []

**JVM version**: 1.8.0_141

**OS version** : Windows 10 Enterprise Version 1703

**Description of the problem including expected versus actual behavior**:
**Precondition:**
There is a nested type with an array of filteroptions in the inner object
One nested object with two inner objects is inserted. One with “opt1” in the filteroptions, one with “opt2”
A query filters by “opt1” and has an aggregation with a terms aggregation on the filteroptions. 

**Expected behavior:**
The aggregation result for “opt2” should return 0

**Actual behavior**:
The aggregation result for “opt2” returns 1

**Steps to reproduce**:

 1. Execute script to create an index, insert an entry and execute a query 
[ScriptForElastic5.6.txt](https://github.com/elastic/elasticsearch/files/1638844/ScriptForElastic5.6.txt)
or for elastic 6
[ScriptForElastic6.txt](https://github.com/elastic/elasticsearch/files/1638845/ScriptForElastic6.txt)

 2. Investigate the result
[Elastic5.6Result.txt](https://github.com/elastic/elasticsearch/files/1638842/Elastic5.6Result.txt)
[Elastic6Result.txt](https://github.com/elastic/elasticsearch/files/1638843/Elastic6Result.txt)

The aggregation "CountsOfAllFilterOptions" contains a terms aggregation and a reverse_nested aggregation. The doc_count-results of both the "opt1" and "opt2" buckets as well as the reverse_nested aggregation are 1 but in our understanding the result of bucket "opt1" should be the count of documents with 
"op1" **and** "opt2" as filteroptions. 
Instead the result seems to be the count of documents with 
"opt1" **or** "opt2".

**Comment by DaveCTurner** [comment] 2018-01-17 13:14
Thanks for the detailed steps-to-reproduce, @SimonJonasGubler. In 6.1.1 I see the following:

```
DELETE test_aggregation_with_inner_mapping

PUT test_aggregation_with_inner_mapping
{"mappings":{"ContainerType":{"properties":{"outerId":{"type":"long"},"innerModels":{"type":"nested","properties":{"innerId":{"type":"long"},"filterOptions":{"type":"keyword"}}}}}}}

POST test_aggregation_with_inner_mapping/ContainerType/_bulk
{"index":{}}
{"outerId":"10","innerModels":[{"innerId":"11","filterOptions":["opt1"]},{"innerId":"12","filterOptions":["opt2"]}]}
{"index":{}}
{"outerId":"20","innerModels":[{"innerId":"21","filterOptions":["opt1"]}]}
{"index":{}}
{"outerId":"30","innerModels":[{"innerId":"32","filterOptions":["opt2"]}]}

GET test_aggregation_with_inner_mapping/ContainerType/_search
{
  "query": {
    "bool": {
      "filter": [
        {
          "nested": {
            "query": {
              "bool": {
                "filter": [
                  {
                    "match": {
                      "innerModels.filterOptions": {
                        "query": "opt1"
                      }
                    }
                  }
                ]
              }
            },
            "path": "innerModels"
          }
        }
      ]
    }
  },
  "aggs": {
    "CountsOfAllFilterOptions": {
      "nested": {
        "path": "innerModels"
      },
      "aggs": {
        "filterOptions": {
          "terms": {
            "field": "innerModels.filterOptions"
          },
          "aggs": {
            "filterOptions": {
              "reverse_nested": {}
            }
          }
        }
      }
    }
  }
}
```

yields

```
  "aggregations": {
    "CountsOfAllFilterOptions": {
      "doc_count": 3,
      "filterOptions": {
        "doc_count_error_upper_bound": 0,
        "sum_other_doc_count": 0,
        "buckets": [
          {
            "key": "opt1",
            "doc_count": 2,
            "filterOptions": {
              "doc_count": 2
            }
          },
          {
            "key": "opt2",
            "doc_count": 1,
            "filterOptions": {
              "doc_count": 1
            }
          }
        ]
      }
    }
```

If I understand correctly, you expect the inner document `{"innerId":"12","filterOptions":["opt2"]}` to be ignored in the aggregation, so that the `{"key":"opt2","doc_count":1,"filterOptions":{"doc_count":1}}` bucket isn't returned?

The issue is, I think, that the filter is finding all outer docs that have a matching inner doc, and the aggregation then runs over all the outer docs that are returned. In the example above I index a couple more documents to show that this is what's happening instead of this:

> the result seems to be the count of documents with "opt1" **or** "opt2".

This is by design, but perhaps someone like @colings86 would know how to achieve what you're wanting?

**Comment by SimonJonasGubler** [comment] 2018-01-17 14:02
Thanks for the quick and helpful answer. I would like to get the "opt2" bucket returned but I expected it to have doc_count 1 in your example. The reason for that is I expected the aggregation to include the filter in the main-query. But this seems not to be the case.

Do you know how the terms-aggregation could be enhanced to include certain field-values? Then we could use that and include "opt1" in  our example. The aggregation would then return doc_count 1 for the bucket "opt2" because there is only one document with both "opt1" and "opt2".

**Comment by colings86** [comment] 2018-01-18 12:25
@SimonJonasGubler I'm not following completely on what you expect vs. what is returned in @DaveCTurner's example above. You said in your reply:
> I would like to get the "opt2" bucket returned but I expected it to have doc_count 1 in your example

However in the example the `opt2` bucket does have a doc count of 1:
>```
>          {
>            "key": "opt2",
>            "doc_count": 1,
>            "filterOptions": {
>              "doc_count": 1
>            }
>          }
>```

Could you maybe modify the response in @DaveCTurner's example so it shows what you expect to see?

To clarify a bit how the search request is being interpreted, the following describes what the search request in @DaveCTurner's example will do in Elasticsearch:

The `query` asks Elasticsearch to match any root (top-level) document that contains an `innerModels` nested document with a value of `opt1` in the `innerModels.filterOptions` field. This query will return the root document and that root document may also contain `innerModels` nested documents which do not match `opt1` in the `innerModels.filterOptions` field.

All matching root documents are passed to the Aggregations. The `CountsOfAllFilterOptions` nested aggregation is asking Elasticsearch to take each of the `innerModels` nested documents in each root document and pass each nested document to the sub-aggregations (rather than passing the root document to the sub aggregations). Note that this aggregation does not differentiate between nested documents containing `opt1` and those that don't, all nested documents for root documents matching the query are passed to the sub aggregations.

The `filterOptions` terms aggregation will take each document it is passed (in this case each innerModels nested document from the `CountsOfAllFilterOptions`), inspect the `innerModels.filterOptions` field of the document and pass it to a bucket for that value (in the example above it creates two buckets, one for `opt1` and one for `opt2`). For each bucket the documents in the bucket are passed the sub-aggregations.

the `filterOptions` reverse_nested aggregation will take each nested document passed to it and resolve the root document that contains it.

So in effect you are asking Elasticsearch: "Find me all root documents that contain at least one inner document with the value `opt1` in the `innerModels.filterOptions` field. Then for each of those root documents consider each `innerModels` nested document individually and create buckets based on the value of `innerModels.filterOptions` of those nested documents, then in each of those buckets resolve the root documents from those nested documents and tell me how many root documents there are in each bucket.

**Comment by SimonJonasGubler** [comment] 2018-01-18 15:14
@colings86 Sorry for the missunderstanding. I see now how the terms aggregation works. In a highlevel-view what I would like to achieve is to get a result like this:

- All outer documents which contain an inner document with "opt1" in the filterOptions
- An aggregation with the following counts
-- All outer documents which contain an inner document with "opt1" in the filterOptions
-- All outer documents which contain an inner document with "opt1" **and** "opt2" in the filterOptions

Basically I would like the aggregation to tell me how many documents would be returned in the main query if another filterOption is filtered additionally. So if there would be three filteroptions "opt1", "opt2", "opt3" I would like to get the following result:

- All outer documents which contain an inner document with "opt1" in the filterOptions
- An aggregation with the following counts
-- All outer documents which contain an inner document with "opt1" in the filterOptions
-- All outer documents which contain an inner document with "opt1" **and** "opt2" in the filterOptions
-- All outer documents which contain an inner document with "opt1" **and** "opt3" in the filterOptions

In @DaveCTurner 's example the count in the result was as expected. For bucket "opt1" it returned 2 and for bucket "opt2" it returned 1. But in my initial example there is only one outer document with two inner documents with "opt1" respectively "opt2". The query returned then 1 for both filterOptions which is not what I expected.

Do you have an idea how to implement a query to get the described result?

**Comment by colings86** [comment] 2018-01-18 15:39
@SimonJonasGubler Thanks for the clarification, I think I understand what you are wanting to do now.

I have a couple more questions though if thats ok:
1. Are the number of possible values for `filterOptions` small?
2. Are the possible values for `filterOptions` known (as in do you know all the values there could be upfront)?
3. Do you use the fact that `innerModel` is nested in other queries?
4. If yes to 3, in those other queries are you searching across multiple fields in the `innerModel` nested documents?

**Comment by SimonJonasGubler** [comment] 2018-01-18 16:31
1. Unfortunately no. In our first implementation we tried to implement it with a global aggregation for each option with a complete filter. But for some cases there were many options so the query was very slow. That's why we tried the filters-Aggregation
2. The possible values are known.
3. Do you mean other queries than the one I described? No, we use the index only for this query. However there are other fields in our outer- and inner-document which can also be selected
5. Yes we can change the mappings and reindex or create an index completely if required

**Comment by colings86** [comment] 2018-01-23 13:12
@SimonJonasGubler Sorry for the late response on this. I think I have a solution for your use case given your comment above. I think the following example script will work:
```
DELETE test_aggregation_with_inner_mapping

PUT test_aggregation_with_inner_mapping
{
  "mappings": {
    "ContainerType": {
      "properties": {
        "outerId": {
          "type": "long"
        },
        "innerModels": {
          "type": "nested",
          "properties": {
            "innerId": {
              "type": "long"
            },
            "filterOptions": {
              "type": "keyword"
            }
          }
        }
      }
    }
  }
}

POST test_aggregation_with_inner_mapping/ContainerType/_bulk
{"index":{}}
{"outerId":"10","innerModels":[{"innerId":"11","filterOptions":["opt1", "opt2"]},{"innerId":"12","filterOptions":["opt3"]}]}
{"index":{}}
{"outerId":"20","innerModels":[{"innerId":"21","filterOptions":["opt1"]}]}
{"index":{}}
{"outerId":"30","innerModels":[{"innerId":"32","filterOptions":["opt2"]}]}
{"index":{}}
{"outerId":"10","innerModels":[{"innerId":"11","filterOptions":["opt1"]},{"innerId":"12","filterOptions":["opt1", "opt3"]}]}

GET test_aggregation_with_inner_mapping/ContainerType/_search
{
  "query": {
    "bool": {
      "filter": [
        {
          "nested": {
            "query": {
              "bool": {
                "filter": [
                  {
                    "match": {
                      "innerModels.filterOptions": {
                        "query": "opt1"
                      }
                    }
                  }
                ]
              }
            },
            "path": "innerModels"
          }
        }
      ]
    }
  },
  "aggs": {
    "CountsOfAllFilterOptions": {
      "nested": {
        "path": "innerModels"
      },
      "aggs": {
        "opt1Filter": {
          "filter": {
            "match": {
              "innerModels.filterOptions": {
                "query": "opt1"
              }
            }
          },
          "aggs": {
            "filterOptions": {
              "terms": {
                "field": "innerModels.filterOptions"
              },
              "aggs": {
                "filterOptions": {
                  "reverse_nested": {}
                }
              }
            }
          }
        }
      }
    }
  }
}
```

Note that the input documents are slightly different to the previous example. The key difference in the search request is adding a `filter` aggregation around the terms aggregation. This will only allow inner documents which contain "opt1" to be passed to the sub-aggregations. The following is the response form the search in this example:
```
{
  ...
  "aggregations": {
    "CountsOfAllFilterOptions": {
      "doc_count": 5,
      "opt1Filter": {
        "doc_count": 4,
        "filterOptions": {
          "doc_count_error_upper_bound": 0,
          "sum_other_doc_count": 0,
          "buckets": [
            {
              "key": "opt1",
              "doc_count": 4,
              "filterOptions": {
                "doc_count": 3
              }
            },
            {
              "key": "opt2",
              "doc_count": 1,
              "filterOptions": {
                "doc_count": 1
              }
            },
            {
              "key": "opt3",
              "doc_count": 1,
              "filterOptions": {
                "doc_count": 1
              }
            }
          ]
        }
      }
    }
  }
}
```

The count to look for is the one within the inner `filterOptions` object for each terms bucket. This says that there are 3 outer documents which contain "opt1" in an inner document (note that the third input document does not contain "opt1"), there is one outer document containing both "opt1" and "opt2" (the first document) and one outer document containing both "opt1" and "opt3".

Does that fit your use case and solve your issue?

**Comment by SimonJonasGubler** [comment] 2018-01-29 09:53
Hi @colings86 

Thank you very much, the query works also with the example from the first post. Conceptionally we need to add the filter from the main-query to the aggregation so that the nested documents are filtered before being aggregated. Is that correct? With this insight we can find a solution to our problem.

Kind regards

Simon

**Comment by colings86** [comment] 2018-01-29 12:29
Yes thats correct, I'm glad you have a solution now. I'm going to close this issue since we have confirmed there is no bug here. If you have further question please ask on the forum at https://discuss.elastic.co

**Closed by colings86** 2018-01-29 12:29 UTC
Labels: :Aggregations, feedback_needed
