### ISSUE TITLE
unknown reason for ElasticsearchException Missing value for field

### ISSUE THREAD

**Issue by dblado** [elastic/elasticsearch#14012] opened 2015-10-08 01:14 UTC
I added a geo_distance filter to a query received an error:

ElasticsearchException[Missing value for field [reviews_length]]

I really thought all of my documents had the reviews_length field so I checked, and:
```
curl -XGET http://localhost:9200/vendop/vendor/_search -d '{
  "query": {
    "filtered": {
      "filter": {
        "missing": {
          "field": "reviews_length"
        }
      }
    }
  }
}'
```
produces:
```
{
"took": 1,
"timed_out": false,
"_shards": {
"total": 5,
"successful": 5,
"failed": 0
},
"hits": {
"total": 0,
"max_score": null,
"hits": [ ]
}
}
```

The complete query is:
```
{
  "query": {
    "filtered": {
      "filter": {
        "bool": {
          "must": [
            {
              "geo_distance": {
                "distance": "50mi",
                "location2.coordinates": [
                  -122.4194155,
                  37.7749295
                ]
              }
            }
          ]
        }
      },
      "query": {
        "bool": {
          "minimum_should_match": "60%",
          "should": [
            {
              "function_score": {
                "query": {
                  "match": {
                    "name.lower_raw": "molding"
                  }
                },
                "functions": [
                  {
                    "boost_factor": 20
                  }
                ]
              }
            },
            {
              "function_score": {
                "query": {
                  "match": {
                    "name": {
                      "query": "molding",
                      "fuzziness": "auto"
                    }
                  }
                },
                "functions": [
                  {
                    "boost_factor": 10
                  }
                ]
              }
            },
            {
              "multi_match": {
                "query": "molding",
                "fields": [
                  "_all"
                ]
              }
            },
            {
              "function_score": {
                "functions": [
                  {
                    "field_value_factor": {
                      "field": "reviews_length",
                      "factor": 0.01
                    }
                  }
                ]
              }
            },
            {
              "function_score": {
                "query": {
                  "terms": {
                    "services": [
                      "523e900941233f628f8eee71",
                      "523e900941233f628f8eee72",
                      "54359cfeae304c2f77d6adb6",
                      "523e900941233f628f8eee70",
                      "53dfabeb2a2dfa23de430fcf",
                      "53dfabde2a2dfa23de430fce"
                    ]
                  }
                },
                "functions": [
                  {
                    "boost_factor": 25
                  }
                ]
              }
            }
          ]
        }
      }
    }
  },
  "size": 20
}
```

If I add this range filter to query.filtered.filter.bool.must, I still get the error but only on one of the shards (so there are search results).
```
            {
              "range": {
                "reviews_length": {
                  "gte": 0
                }
              }
            }
```

the field is defined in the mapping as:
```
        "reviews_length": {
          "type": "long"
        }
```

I tried putting together a full test case but I couldn't reproduce the problem with a very abbreviated data set. I have tried rebuilding my index but still run into this issue. What is interesting is that if I remove the minimum_should_match from the query (or change it to <40% the problem goes away.

I'm sure there is just something I'm missing in the docs. I'm using 1.4.2 in prod so I can't use the 'missing' parameter to 'field_value_factor' yet -- and shouldn't have to since none of my documents have the reviews_length field missing.

If it helps, here is the debug log from ES:
```
[2015-10-07 18:11:26,126][DEBUG][action.search.type       ] [White Rabbit] All shards failed for phase: [query]
org.elasticsearch.search.query.QueryPhaseExecutionException: [vendop_v1][0]: query[filtered(filtered((function score (name.lower_raw:molding,function=boost[20.0]) function score (name:molding~2,function=boost[10.0]) function score (child_filter[review/vendor](filtered(_all:molding)->cache(_type:review)),function=boost[4.0]) _all:molding function score (ConstantScore(*:*),function=org.elasticsearch.common.lucene.search.function.FieldValueFactorFunction@6e1aca5f) function score (services:523e900941233f628f8eee71 services:523e900941233f628f8eee72 services:54359cfeae304c2f77d6adb6 services:523e900941233f628f8eee70 services:53dfabeb2a2dfa23de430fcf services:547ba915ae304c5e979f40f0 services:5227a9b0c64c8c1739698315 services:5328a646c61e3610d056ca90 services:52450165a4283d7aaa000000 services:533afb1fc61e3662d1cecdc2 services:523e900941233f628f8eee6f services:53dfabcd2a2dfa23de430fcd services:523e900941233f628f8eee74 services:547a7a6d2a2dfa2aaac69fb3 services:523e900941233f628f8eee75 services:53f39ac2ae304c77eaa2289e services:53dfabde2a2dfa23de430fce,function=boost[25.0]))~3)->BooleanFilter(+GeoDistanceFilter(location2.coordinates, SLOPPY_ARC, 80467.2, 37.7749295, -122.4194155)))->cache(+_type:vendor +org.elasticsearch.index.search.nested.NonNestedDocsFilter@8b805655)],from[0],size[20]: Query Failed [Failed to execute main query]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:163)
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:289)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:300)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.ElasticsearchException: Missing value for field [reviews_length]
	at org.elasticsearch.common.lucene.search.function.FieldValueFactorFunction.score(FieldValueFactorFunction.java:71)
	at org.elasticsearch.common.lucene.search.function.FunctionScoreQuery$FunctionFactorScorer.innerScore(FunctionScoreQuery.java:170)
	at org.elasticsearch.common.lucene.search.function.CustomBoostFactorScorer$AnyNextDoc.score(CustomBoostFactorScorer.java:133)
	at org.elasticsearch.common.lucene.search.function.CustomBoostFactorScorer.score(CustomBoostFactorScorer.java:71)
	at org.apache.lucene.search.MinShouldMatchSumScorer.evaluateSmallestDocInHeap(MinShouldMatchSumScorer.java:170)
	at org.apache.lucene.search.MinShouldMatchSumScorer.nextDoc(MinShouldMatchSumScorer.java:142)
	at org.apache.lucene.search.FilteredQuery$QueryFirstScorer.nextDoc(FilteredQuery.java:176)
	at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreAll(Weight.java:192)
	at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:163)
	at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:35)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:621)
	at org.elasticsearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:191)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:491)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:448)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:281)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:269)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:157)
	... 8 more
```

**Comment by clintongormley** [comment] 2015-10-08 13:16
Hi @dblado 

So much has changed since then.  Would it be possible to copy the index into a node with 1.7.2 and try the query there, to see if the problem still exists?

**Comment by dblado** [comment] 2015-10-08 19:02
@clintongormley sure thing. I am using 1.6.0 locally just haven't needed to upgrade prod yet.

Loading my full dataset (~5.5mln documents) into 1.7.2 and running the same query shows 4/5 shards failing.

response error:
```
"failures": [
{
"index": "vendop_v1",
"shard": 0,
"status": 500,
"reason": "QueryPhaseExecutionException[[vendop_v1][0]: query[filtered(filtered((function score (name.lower_raw:molding,function=boost[20.0]) function score (name:molding~2,function=boost[10.0]) _all:molding function score (ConstantScore(*:*),function=org.elasticsearch.common.lucene.search.function.FieldValueFactorFunction@6267d318) function score (services:523e900941233f628f8eee71 services:523e900941233f628f8eee72 services:54359cfeae304c2f77d6adb6 services:523e900941233f628f8eee70 services:53dfabeb2a2dfa23de430fcf services:547ba915ae304c5e979f40f0 services:5227a9b0c64c8c1739698315 services:5328a646c61e3610d056ca90 services:52450165a4283d7aaa000000 services:533afb1fc61e3662d1cecdc2 services:523e900941233f628f8eee6f services:53dfabcd2a2dfa23de430fcd services:523e900941233f628f8eee74 services:547a7a6d2a2dfa2aaac69fb3 services:523e900941233f628f8eee75 services:53f39ac2ae304c77eaa2289e services:53dfabde2a2dfa23de430fce,function=boost[25.0]))~3)->BooleanFilter(+GeoDistanceFilter(location2.coordinates, SLOPPY_ARC, 80467.2, 37.7749295, -122.4194155)))->cache(+_type:vendor +org.elasticsearch.index.search.nested.NonNestedDocsFilter@20b3a141)],from[0],size[20]: Query Failed [Failed to execute main query]]; nested: ElasticsearchException[Missing value for field [reviews_length]]; "
}
```

log error:
```
[2015-10-08 11:59:40,681][DEBUG][action.search.type       ] [Battletide] [vendop_v1][0], node[6e1xCs4yTU-uzvFvZeWp_A], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@67a2443a] lastShard [true]
org.elasticsearch.search.query.QueryPhaseExecutionException: [vendop_v1][0]: query[filtered(filtered((function score (name.lower_raw:molding,function=boost[20.0]) function score (name:molding~2,function=boost[10.0]) _all:molding function score (ConstantScore(*:*),function=org.elasticsearch.common.lucene.search.function.FieldValueFactorFunction@6267d318) function score (services:523e900941233f628f8eee71 services:523e900941233f628f8eee72 services:54359cfeae304c2f77d6adb6 services:523e900941233f628f8eee70 services:53dfabeb2a2dfa23de430fcf services:547ba915ae304c5e979f40f0 services:5227a9b0c64c8c1739698315 services:5328a646c61e3610d056ca90 services:52450165a4283d7aaa000000 services:533afb1fc61e3662d1cecdc2 services:523e900941233f628f8eee6f services:53dfabcd2a2dfa23de430fcd services:523e900941233f628f8eee74 services:547a7a6d2a2dfa2aaac69fb3 services:523e900941233f628f8eee75 services:53f39ac2ae304c77eaa2289e services:53dfabde2a2dfa23de430fce,function=boost[25.0]))~3)->BooleanFilter(+GeoDistanceFilter(location2.coordinates, SLOPPY_ARC, 80467.2, 37.7749295, -122.4194155)))->cache(+_type:vendor +org.elasticsearch.index.search.nested.NonNestedDocsFilter@20b3a141)],from[0],size[20]: Query Failed [Failed to execute main query]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:163)
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:301)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:312)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.ElasticsearchException: Missing value for field [reviews_length]
	at org.elasticsearch.common.lucene.search.function.FieldValueFactorFunction.score(FieldValueFactorFunction.java:71)
	at org.elasticsearch.common.lucene.search.function.FunctionScoreQuery$FunctionFactorScorer.innerScore(FunctionScoreQuery.java:170)
	at org.elasticsearch.common.lucene.search.function.CustomBoostFactorScorer$AnyNextDoc.score(CustomBoostFactorScorer.java:133)
	at org.elasticsearch.common.lucene.search.function.CustomBoostFactorScorer.score(CustomBoostFactorScorer.java:71)
	at org.apache.lucene.search.MinShouldMatchSumScorer.evaluateSmallestDocInHeap(MinShouldMatchSumScorer.java:170)
	at org.apache.lucene.search.MinShouldMatchSumScorer.nextDoc(MinShouldMatchSumScorer.java:142)
	at org.apache.lucene.search.FilteredQuery$QueryFirstScorer.nextDoc(FilteredQuery.java:176)
	at org.apache.lucene.search.FilteredQuery$QueryFirstScorer.advance(FilteredQuery.java:187)
	at org.apache.lucene.search.FilteredQuery$LeapFrogScorer.advanceToNextCommonDoc(FilteredQuery.java:274)
	at org.apache.lucene.search.FilteredQuery$LeapFrogScorer.nextDoc(FilteredQuery.java:286)
	at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreAll(Weight.java:192)
	at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:163)
	at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:35)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:621)
	at org.elasticsearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:191)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:491)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:448)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:281)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:269)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:157)
	... 8 more
```

**Comment by dblado** [comment] 2015-10-08 19:22
@clintongormley FYI, on 1.7.2, If I add the range filter, there are no errors and hits.total = 33 (expected):

```
            {
              "range": {
                "reviews_length": {
                  "gte": 0
                }
              }
            }
```

On 1.6.0, adding the range filter shows an error on one shard and hits.total = 26

**Comment by jimmytheleaf** [comment] 2015-10-08 22:50
On 1.7.1, I have a similar error with a query involving function scores and a `geo_bounding_box` filter. I have the same behavior where I get an error that says the field was missing, even though I confirm with a query + "missing" filter that no documents in this doctype have this field missing. (I have documents across other doctypes with this field not present.)

What is strange, is if I removed the `geo_bounding_box` filter, I get results back fine and no longer see the error. Behavior persists after I cleared the cache.

Error root cause was a similar: `Query Failed [Failed to execute main query]]; nested: ElasticsearchException[Missing value for field [a4]];`

@dblado -- kind of curious, if you don't have that range filter, and you remove the `geo_distance` filter, do you still get the error?

**Comment by dblado** [comment] 2015-10-08 23:07
Hi @jimmytheleaf I do still get the error but not on all shards. I didn't notice the error because some shards succeeded and returned results.

**Comment by jimmytheleaf** [comment] 2015-10-09 18:13
Another datapoint, and suggestion for me that there is something odd going on with the way filters are being applied -- I'm doing a query that involves a `geo_bounding_box` filter and a set of `field_value_factor` functions on an index + doctype. I.E. `POST /<index-name>/<doctype>/_search`.

If I add a term filter for the doctype, i.e.:

```javascript
{ "term" : { "_type": <doctype>}}
```

I no longer get the spurious `ElasticsearchException[Missing value for field [<fieldname>]];` Issue.

Kinda suggests for me that something about the geo filter is causing my query to funnel documents from other doctypes (where that field is missing) into the function scoring, and causing it to barf when the field I'm scoring on doesn't exist?


My query that triggers the error looks like:

````javascript
// POST /index-name/doc-type/_search
{
   "query": {
      "filtered": {
         "filter": {
            "bool": {
               "must": [
                  {
                     "nested": {
                        "filter": {
                           "geo_bounding_box": {
                              "_cache": false,
                              "type": "indexed",
                              "point": {
                                 "bottom_right": {
                                    "lat": 36.00621805925558,
                                    "lon": -120.33803214814795
                                 },
                                 "top_left": {
                                    "lat": 38.90084254074442,
                                    "lon": -124.98458605185203
                                 }
                              }
                           }
                        },
                        "path": "foo"
                     }
                  }
               ]
            }
         },
         "query": {
            "nested": {
               "path": "bar",
               "score_mode": "max",
               "inner_hits": {
                  "size": 1
               },
               "query": {
                  "function_score": {
                     "query": {
                        "filtered": {}
                     },
                     "functions": [
                        {
                           "field_value_factor": {
                              "field": "a1",
                              "factor": 0.004342221095126581
                           }
                        },
                        {
                           "field_value_factor": {
                              "field": "a2",
                              "factor": 0.2212504591677979
                           }
                        },
                        {
                           "field_value_factor": {
                              "field": "a3",
                              "factor": 0.723225250366149
                           }
                        },
                        {
                           "field_value_factor": {
                              "field": "a4",
                              "factor": 0.051182069370926446
                           }
                        }
                     ],
                     "score_mode": "sum"
                  }
               }
            }
         }
      }
   }
}
```


Error disappears with either:

````javascript
// POST /index-name/doc-type/_search
{
   "query": {
      "filtered": {
         "filter": {
            "bool": {
               "must": []
            }
         },
         "query": {
            "nested": {
               "path": "bar",
               "score_mode": "max",
               "inner_hits": {
                  "size": 1
               },
               "query": {
                  "function_score": {
                     "query": {
                        "filtered": {}
                     },
                     "functions": [
                        {
                           "field_value_factor": {
                              "field": "a1",
                              "factor": 0.004342221095126581
                           }
                        },
                        {
                           "field_value_factor": {
                              "field": "a2",
                              "factor": 0.2212504591677979
                           }
                        },
                        {
                           "field_value_factor": {
                              "field": "a3",
                              "factor": 0.723225250366149
                           }
                        },
                        {
                           "field_value_factor": {
                              "field": "a4",
                              "factor": 0.051182069370926446
                           }
                        }
                     ],
                     "score_mode": "sum"
                  }
               }
            }
         }
      }
   }
}
```

or:

```javascript
// POST /index-name/doc-type/_search
{
   "query": {
      "filtered": {
         "filter": {
            "bool": {
               "must": [
                  { "term": {"_type": "doc-type"} },
                  {
                     "nested": {
                        "filter": {
                           "geo_bounding_box": {
                              "_cache": false,
                              "type": "indexed",
                              "point": {
                                 "bottom_right": {
                                    "lat": 36.00621805925558,
                                    "lon": -120.33803214814795
                                 },
                                 "top_left": {
                                    "lat": 38.90084254074442,
                                    "lon": -124.98458605185203
                                 }
                              }
                           }
                        },
                        "path": "foo"
                     }
                  }
               ]
            }
         },
         "query": {
            "nested": {
               "path": "bar",
               "score_mode": "max",
               "inner_hits": {
                  "size": 1
               },
               "query": {
                  "function_score": {
                     "query": {
                        "filtered": {}
                     },
                     "functions": [
                        {
                           "field_value_factor": {
                              "field": "a1",
                              "factor": 0.004342221095126581
                           }
                        },
                        {
                           "field_value_factor": {
                              "field": "a2",
                              "factor": 0.2212504591677979
                           }
                        },
                        {
                           "field_value_factor": {
                              "field": "a3",
                              "factor": 0.723225250366149
                           }
                        },
                        {
                           "field_value_factor": {
                              "field": "a4",
                              "factor": 0.051182069370926446
                           }
                        }
                     ],
                     "score_mode": "sum"
                  }
               }
            }
         }
      }
   }
}
```

**Comment by dblado** [comment] 2015-10-09 21:03
interesting -- if I update my failed query to include:
```
          "must": [
            {
              "term": {
                "_type": "vendor"
              }
            },
            {
              "geo_distance": {
                "distance": "50mi",
                "location2.coordinates": [
                  -122.4194155,
                  37.7749295
                ]
              }
            }
          ]
```

I still get an error but only on 1 shard instead of all 5.

**Comment by dblado** [comment] 2015-10-10 00:43
Some more experimenting...

I changed my mapping and rebuilt the index. My reviews_length field is now:

```
        "reviews_length": {
          "type": "short",
        }
```
as long as I add reviews_length range filter:
```
            {
              "range": {
                "reviews_length": {
                  "gte": 0
                }
              }
            }
```
all 5 shards succeed! Without the range filter, 4/5 shards fail with missing value for field.


I built a second index w/ the mapping set as:
```
        "reviews_length": {
          "type": "short",
          "null_value": 0
        }
```

Again, as long as I have the reviews_length range filter, the query succeeds.  Interesting that without the range filter on reviews_length, all shards fail w/ null_value set in the mapping. I find this odd since the field should always exist since there is a null_value specified in the mapping. Did I misunderstand the null_value setting?

**Comment by jpountz** [comment] 2015-10-13 09:37
These errors are due to the fact that `MinShouldMatchScorer` sometimes evaluates the score on sub scorers even if there might not be enough matching clauses for the boolean query (which has min_should_match set) to match. This scorer was changed in Lucene 5.1 to compute scores lazily (https://issues.apache.org/jira/browse/LUCENE-6201) so it should be fixed in Elasticsearch 2.0, which will be based on Lucene 5.2.1. The only work-around that I can think of for 1.x would be to filter the query wrapped by the `function_score` query that has the `field_value_factor` function so that it cannot match a document that doesn't have a value for `reviews_length`.

Having reindexed with the `null_value` set on the `reviews_length` field should have worked. If it didn't, I guess it is because you have other types on the same index that either don't have the `reviews_length` field or have it but don't have a `null_value` configured.

**Closed by jpountz** 2015-10-13 09:37 UTC
Labels: :Search, bug, feedback_needed

**Comment by dblado** [comment] 2015-10-13 23:51
@jpountz thanks for the feedback. I find it odd that the same query works when the reviews_length field is set to a different data type (short vs long).

I do have other types in the same index, but the search is to /index/type/_search...doesn't that mean it shouldn't matter if other types don't have that field defined?

**Comment by clintongormley** [comment] 2015-10-14 08:28
> I do have other types in the same index, but the search is to /index/type/_search...doesn't that mean it shouldn't matter if other types don't have that field defined?

it's a whole lot more complex than that.  lucene has no concept of types, it just sees a list of fields (which may or may not be in your type).  queries and filters do not necessarily operate on just the subset of documents that other query/filter clauses have included, but may well hit unrelated documents.

This all gets a whole lot neater and cleaner in 2.0

**Comment by EmilAlipiev** [comment] 2016-04-11 12:59
I am using 2.0.2 version and I have exactly similar query and same error. I went to through my integer field which OrderCount as below. and all have value 0 or greater than 0. How can I solve this problem?

{
   "query": {
      "function_score": {
         "query": {
            "bool": {
               "should": [
                  {
                     "multi_match": {
                        "type": "best_fields",
                        "query": "tinte",
                        "fields": [                          
                           "Name^7",
                           "ShortDescription^6"
                        ]
                     }
                  }
               ]
            }
         },
         "field_value_factor": {
            "field": "OrderCount"
         }
      }
   }
}
