### ISSUE TITLE
[CI] SnapshotBasedRecoveryIT testSnapshotBasedRecovery failing

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#81661] opened 2021-12-13 15:17 UTC
**Build scan**: https://gradle-enterprise.elastic.co/s/ji3jtqdsaporc

**Repro line**: 

```
./gradlew ':qa:rolling-upgrade:v8.0.0#oneThirdUpgradedTest' -Dtests.class="org.elasticsearch.upgrades.SnapshotBasedRecoveryIT" -Dtests.method="testSnapshotBasedRecovery" -Dtests.seed=DFBB69B284242E99 -Dtests.bwc=true -Dtests.locale=sr-CS -Dtests.timezone=Canada/Atlantic -Druntime.java=17
```

**Reproduces locally?**: No

**Applicable branches**: master

**Failure history**: 
https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=Europe/Athens&tests.container=org.elasticsearch.upgrades.SnapshotBasedRecoveryIT&tests.sortField=FAILED&tests.test=testSnapshotBasedRecovery&tests.unstableOnly=true

**Failure excerpt**: Too large to paste here, please see build scan.

**Comment by fcofdez** [comment] 2021-12-13 16:00
Closing as a duplicate of https://github.com/elastic/elasticsearch/issues/80939

**Closed by fcofdez** 2021-12-13 16:00 UTC
Labels: >test-failure, :Distributed/Recovery, Team:Distributed

**Comment by dimitris-athanasiou** [comment] 2021-12-13 16:04
Thanks for closing this @fcofdez and sorry for the noise. Apparently looking up "SnapshotBase" in GitHub doesn't work as I expected and one needs to search for the whole word "SnapshotBasedRecoveryIT"!
