### ISSUE TITLE
Graph Java API not working 

### ISSUE THREAD

**Issue by ahr12** [elastic/elasticsearch#22951] opened 2017-02-03 06:39 UTC
I use graph Java API. but I am getting the NullPointerException Errors.

import java.net.InetAddress;
import java.util.Collection;
 
import org.elasticsearch.client.transport.TransportClient;
import org.elasticsearch.common.settings.Settings;
import org.elasticsearch.common.transport.InetSocketTransportAddress;
import org.elasticsearch.graph.action.GraphExploreAction;
import org.elasticsearch.graph.action.GraphExploreRequestBuilder;
import org.elasticsearch.graph.action.GraphExploreResponse;
import org.elasticsearch.graph.action.Hop;
import org.elasticsearch.graph.action.Vertex;
import org.elasticsearch.index.query.QueryBuilders;
import org.elasticsearch.transport.client.PreBuiltTransportClient;

/**
 * Demo graph client - find elastic meetup attendees and what other meetup groups they frequent
 */
public class EsGraph {

	public static void main(String[] args) throws Exception {
	
		 
	
		int requiredNumberOfSightings=1;
		Settings settings = Settings.builder()
		        .put("cluster.name", "elasticsearch").build();
		TransportClient client1 = new PreBuiltTransportClient(settings)
        .addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName("localhost"), 9300));

		
		
	
		GraphExploreRequestBuilder grb = new GraphExploreRequestBuilder( client1, GraphExploreAction.INSTANCE).setIndices("datagraph");
		Hop hop1 = grb.createNextHop(QueryBuilders.termQuery("_all", "elasticsearch"));
		// elasticsearch meetup attendees
		hop1.addVertexRequest("member_id").size(10).minDocCount(requiredNumberOfSightings); 
		// groups attended by elastic attendees
		grb.createNextHop(null).addVertexRequest("group_id").size(10).minDocCount(requiredNumberOfSightings); 
	
		GraphExploreResponse response = grb.get();
		Collection<Vertex> vertices = response.getVertices();
	
		System.out.println("==Members===");
		for (Vertex vertex : vertices) {
			if(vertex.getField().equals("member_id")){
				System.out.println(vertex.getTerm());        		
			}
		}
	
		System.out.println("==Groups===");
		for (Vertex vertex : vertices) {
			if(vertex.getField().equals("group_id")){
				System.out.println(vertex.getTerm());        		
			}
		}        

		 
		client1.close();

	}

}

I am getting following error -:

Exception in thread "main" java.lang.NullPointerException
at org.elasticsearch.client.transport.TransportProxyClient.lambda$execute$0(TransportProxyClient.java:59)
at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:231)
at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:345)
at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:403)
at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54)
at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:62)
at org.formcept.orient.EsGraph.main(EsGraph.java:42)

**Comment by clintongormley** [comment] 2017-02-03 08:18
@markharwood could you take a look please?

**Comment by markharwood** [comment] 2017-02-03 11:14
I've tried this on the latest 5.2 download and tried providing missing index names and field names in the test client and was unable to reproduce the same failure you see here.

[This gist](https://gist.github.com/markharwood/f9e955f52908129ef364446cfec0a65e) provides a demo of the data setup and a REST and Java client query for the given example that works OK here.

Can you confirm if you can run this in your environment? This might help draw out any issues relating to your environment.

**Comment by ahr12** [comment] 2017-02-03 12:17
Hello Sir,
I use ElasticSearch 5.1.2 add I already install the x-pack. I use following maven dependencies-
<dependency>
		<groupId>org.elasticsearch</groupId>
		<artifactId>elasticsearch</artifactId>
		<version>5.1.2</version>
	</dependency>
  	<dependency>
    <groupId>org.elasticsearch.client</groupId>
    <artifactId>transport</artifactId>
    <version>5.1.2</version>
</dependency>
<dependency>
    <groupId>org.elasticsearch.plugin</groupId>
    <artifactId>graph</artifactId>
    <version>2.3.0</version>
</dependency>
 <dependency>
    <groupId>org.elasticsearch.plugin</groupId>
    <artifactId>x-pack</artifactId>
    <version>5.0.0-alpha5</version>
</dependency>

but I am not able to use x-pack library which you use in your java program

**Comment by markharwood** [comment] 2017-02-03 12:59
That looks like an unusual mix of dependencies.
I have only this in my pom.xml:

	<dependencies>
	 
	  <dependency>
		 <groupId>org.elasticsearch.client</groupId>
		 <artifactId>x-pack-transport</artifactId>
		 <version>5.2.0</version>
	  </dependency>  
	</dependencies>

**Comment by markharwood** [comment] 2017-02-03 14:15
Closing this issue due to invalid classpath settings.

For the record, to run the example Java client code above you also need classes for a logging framework. That whole area can get into complex configuration but here are my minimal dependencies for running that example Java class:

	<dependencies>
		 
		<dependency>
		   <groupId>org.elasticsearch.client</groupId>
		   <artifactId>x-pack-transport</artifactId>
		   <version>5.2.0</version>
		</dependency>  
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-api</artifactId>
			<version>2.7</version>
		</dependency>    
	</dependencies>

**Closed by markharwood** 2017-02-03 14:15 UTC
Labels: :Java API, feedback_needed

**Comment by ahr12** [comment] 2017-02-05 12:39
My eclipse didn't find the x-pack-transport maven dependency which you provide.Can you check it again

**Comment by dadoonet** [comment] 2017-02-06 05:42
You need to follow this guide: https://www.elastic.co/guide/en/x-pack/current/java-clients.html

Don't forget the repository

**Comment by markharwood** [comment] 2017-02-06 09:24
My [original gist](https://gist.github.com/markharwood/f9e955f52908129ef364446cfec0a65e) includes the full pom.xml

**Comment by ahr12** [comment] 2017-02-06 10:57
I am getting the following errors when I run this program 

Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: org/elasticsearch/cluster/AbstractNamedDiffable
	at org.elasticsearch.xpack.watcher.Watcher.getNamedWriteables(Watcher.java:165)
	at org.elasticsearch.xpack.XPackPlugin.getNamedWriteables(XPackPlugin.java:429)
	at org.elasticsearch.client.transport.TransportClient.lambda$buildTemplate$1(TransportClient.java:140)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.elasticsearch.client.transport.TransportClient.buildTemplate(TransportClient.java:141)
	at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:247)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:125)
	at org.elasticsearch.xpack.client.PreBuiltXPackTransportClient.<init>(PreBuiltXPackTransportClient.java:55)
	at org.elasticsearch.xpack.client.PreBuiltXPackTransportClient.<init>(PreBuiltXPackTransportClient.java:50)
	at org.elasticsearch.xpack.client.PreBuiltXPackTransportClient.<init>(PreBuiltXPackTransportClient.java:46)
	at org.formcept.orient.EsGraph.main(EsGraph.java:24)
Caused by: java.lang.NoClassDefFoundError: org/elasticsearch/cluster/AbstractNamedDiffable
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 17 more
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.cluster.AbstractNamedDiffable
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 29 more

**Comment by ahr12** [comment] 2017-02-07 05:34
I resolve that errors.Now it's working fine.
Thanks a lot.
