### ISSUE TITLE
[CI] Rolling upgrade tests (twoThirdsUpgradedTestRunner) fails to form cluster

### ISSUE THREAD

**Issue by dliappis** [elastic/elasticsearch#36928] opened 2018-12-21 08:30 UTC
Build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.6+intake/24/console

Similar to the closed https://github.com/elastic/elasticsearch/issues/35456, but for the twoThirdsUpgradedTestRunner:

```
04:31:44 > Task :x-pack:qa:rolling-upgrade:with-system-key:v5.6.15#twoThirdsUpgradedTestRunner FAILED
04:31:44 :x-pack:qa:rolling-upgrade:with-system-key:v5.6.15#twoThirdsUpgradedTestRunner (Thread[Execution worker for ':',5,main]) completed. Took 2 mins 49.999 secs.
04:31:44 :x-pack:qa:rolling-upgrade:with-system-key:v5.6.15#oldClusterTestCluster#node2.stop (Thread[Execution worker for ':',5,main]) started.
04:31:44 
```

I can reproduce this locally on my workstation using:

```
./gradlew :x-pack:qa:rolling-upgrade:with-system-key:v5.6.15#twoThirdsUpgradedTestRunner -Dtests.seed=679945B82D7ABBD4 -Dtests.class=org.elasticsearch.upgrades.MlMigrationIT -Dtests.method="testConfigMigration" -Dtests.security.manager=true -Dtests.locale=it -Dtests.timezone=Pacific/Ponape -Dcompiler.java=11 -Druntime.java=8
```

but in my reproduction the exact failure is:

```
Task :x-pack:qa:rolling-upgrade:with-system-key:v5.6.15#twoThirdsUpgradedTestCluster#wait FAILED
```

The task appears to fail because a cluster doesn't form and the logs (e.g. on my workstation) show:

```
|    [2018-12-21T10:00:16,272][WARN ][o.e.d.z.FileBasedUnicastHostsProvider] [upgraded-node-1] expected, but did not find, a dynamic hosts list at [/home/dl/source/elastic/elasticsearch/x-pack/qa/rolling-upgrade/with-system-key/build/cluster/v5.6.15#twoThirdsUpgradedTestCluster node0/elasticsearch-6.6.0-SNAPSHOT/config/unicast_hosts.txt]
...
[2018-12-21T10:00:16,665][DEBUG][o.e.a.a.c.h.TransportClusterHealthAction] [upgraded-node-1] no known master node, scheduling a retry
```

The particular file those exists and has the correct list of IPv6 addresses (even though there's no newline at the last line):

```
cat /home/dl/source/elastic/elasticsearch/x-pack/qa/rolling-upgrade/with-system-key/build/cluster/v5.6.15#twoThirdsUpgradedTestCluster\ node0/elasticsearch-6.6.0-SNAPSHOT/config/unicast_hosts.txt
[::1]:36463
[::1]:44889
[::1]:45733
```

This has been failing occasionally in the past: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.5+intake/216/console

**Comment by DaveCTurner** [comment] 2018-12-21 13:09
The issue that CI found is a test failure, unrelated to cluster formation, for which I opened #36935. However, the failure you get when trying to reproduce this looks to be a Gradle issue: running with `--dry-run` shows that `upgraded-node-0` is stopped before `upgraded-node-1` is started, so the cluster cannot form:

```
...
:x-pack:qa:rolling-upgrade:with-system-key:v5.6.15#oneThirdUpgradedTestCluster#wait SKIPPED
:x-pack:qa:rolling-upgrade:with-system-key:v5.6.15#oneThirdUpgradedTestRunner SKIPPED
:x-pack:qa:rolling-upgrade:with-system-key:v5.6.15#oneThirdUpgradedTestCluster#stop SKIPPED
...
```

**Comment by original-brownbear** [comment] 2018-12-21 15:40
So this is kind of funny :) The problem here isn't necessarily with Gradle, it's this:

if you run this reproducer:

```
./gradlew :x-pack:qa:rolling-upgrade:with-system-key:v5.6.15#twoThirdsUpgradedTestRunner -Dtests.seed=679945B82D7ABBD4 -Dtests.class=org.elasticsearch.upgrades.MlMigrationIT -Dtests.method="testConfigMigration" -Dtests.security.manager=true -Dtests.locale=it -Dtests.timezone=Pacific/Ponape -Dcompiler.java=11 -Druntime.java=8
```

then you will not run the fully upgraded cluster, i.e. the `5.6.15#upgradedClusterTestCluster` tasks.
We do configure that task to be finalized by `#oneThirdUpgradedTestCluster#stop"` and `#twoThirdsUpgradedTestCluster#stop`. So running any of the `twoThirdsUpgradedTestRunner` tasks directly spells trouble. I don't think this is the reason for the test failure on CI itself though, the ordering is fine if you run all the full BWC test.
Is this even something we care about fixing? (NOTE: it seems like this wouldn't be an entirely trivial fix because of the way we lazily create the `#stop` tasks)

**Comment by DaveCTurner** [comment] 2018-12-21 16:13
I think we should do _something_ because otherwise this confusion will just repeat every time there's a BWC test failure that someone tries to reproduce. Maybe we can fix the `REPRODUCE WITH` line to say to run the same test on the fully-upgraded cluster?

**Comment by original-brownbear** [comment] 2018-12-21 16:16
@DaveCTurner 

> Maybe we can fix the REPRODUCE WITH line to say to run the same test on the fully-upgraded cluster?

Yea that would be a good approach imo.

@atorok you're currently refactoring this logic anyway, wdyt?

**Comment by atorok** [comment] 2018-12-21 18:05
Testclusters will be less affected by this. As it won't implement the cluster management with tasks, so the repro line will work from the perspective of the upgrades, but I'm not sure it will be 100% correct,  as the `test.class` and `test.method` will be applicable to all test runners. I don't think we guarantee these to be side effect free, so one might still have to run say all tests in `oneThirdUpgradedTest` to reproduce a failure in `twoThirdsUpgradedTest`  so it might be better to create a custom repro line printer for these which just replaces the task  with would print something like 
```
./gradlew -p x-pack/qa/rolling-upgrade/with-system-key -Dtests.seed=679945B82D7ABBD4  -Dtests.security.manager=true -Dtests.locale=it -Dtests.timezone=Pacific/Ponape -Dcompiler.java=11 -Druntime.java=8
```

**Comment by DaveCTurner** [comment] 2018-12-21 18:18
I think I'd rather accept the risk of side-effects and keep the `test.class` and `test.method` arguments in the output. There will be many situations where the reproduction continues to work even if we haven't run the whole suite first, and it's a lot quicker to try the more focussed single-test run first and only expand it to run everything if you suspect side-effects. It's a lot easier to take those arguments out than to put them in, and taking them out is something I would naturally try when struggling to reproduce a failure.

**Comment by original-brownbear** [comment] 2018-12-24 10:39
@atorok assigned this to you then, hope it's ok :)

**Comment by atorok** [comment] 2019-02-18 12:35
I would rather not teach the reproduction printer about  the different tasks we use to have them substituted by `check`. We should make sure that the tasks themselves have the proper inner dependencies. Like this was said before, this is a non trivial fix for something we are replacing with testclusters, so I am going to close this.

**Closed by atorok** 2019-02-18 12:35 UTC
Labels: :Distributed/Discovery-Plugins, >test-failure
