### ISSUE TITLE
[CI] RunDataFrameAnalyticsIT testOutlierDetectionWithEnoughDocumentsToScroll

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#45930] opened 2019-08-23 20:09 UTC
Failed today on master.

Log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=openjdk12,nodes=general-purpose/161/console
Build Scans: https://gradle-enterprise.elastic.co/s/qdnqr665edzeu

/gradlew :x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner --tests "org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT.testOutlierDetectionWithEnoughDocumentsToScroll" \
  -Dtests.seed=BCACEDEBD847C287 \
  -Dtests.security.manager=true \
  -Dtests.locale=tk \
  -Dtests.timezone=America/Rosario \
  -Dcompiler.java=12 \
  -Druntime.java=12

Relevant stack trace:
```
org.elasticsearch.ElasticsearchException: [memory_usage_estimation_3820] Error while starting process: Close stacktrace
at __randomizedtesting.SeedInfo.seed([BCACEDEBD847C287:A07880B4C3BBBEFF]:0)
at org.elasticsearch.xpack.core.ml.utils.ExceptionsHelper.serverError(ExceptionsHelper.java:47)
at org.elasticsearch.xpack.ml.dataframe.process.MemoryUsageEstimationProcessManager.runJob(MemoryUsageEstimationProcessManager.java:88)
at org.elasticsearch.xpack.ml.dataframe.process.MemoryUsageEstimationProcessManager.lambda$runJobAsync$0(MemoryUsageEstimationProcessManager.java:49)
at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:699)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.lang.Thread.run(Thread.java:835)
```

**Comment by dimitris-athanasiou** [comment] 2019-08-24 12:15
@przemekwitek This is another instance of the memory estimation process failing to start. I wonder if it's best to raise an issue that describes this problem explicitly so we can link to it when integ tests fail.

**Comment by przemekwitek** [comment] 2019-08-26 14:55
> @przemekwitek This is another instance of the memory estimation process failing to start. I wonder if it's best to raise an issue that describes this problem explicitly so we can link to it when integ tests fail.

I already have a ">test-failure" issue with some investigation already done. Marking this one as its duplicate.

Duplicate of https://github.com/elastic/elasticsearch/issues/45787

**Closed** 2019-08-26 14:55 UTC
Labels: :ml/Data Frame, >test-failure
