### ISSUE TITLE
Rollup average not working

### ISSUE THREAD

**Issue by it-quod** [elastic/elasticsearch#45187] opened 2019-08-05 08:44 UTC
We have been trying to use rollup for few months.
Through version the main feature does not seem to work.
Aggregating value into an average does not return an average but a always sum .

```
{
  "VenueTimeStamp.date_histogram.interval":"10m",
  "VenueTimeStamp.date_histogram.timestamp":1564623000000,
  "Side.keyword.terms.value":"Bid",
  "Symbol.keyword.terms._count":567,
  "Price.sum.value":590.585381269455,
  "VenueTimeStamp.date_histogram.time_zone":"UTC",
  "Price.avg._count":567,
  "Price.avg.value":590.585381269455,
  "Price.histogram.value":0,
  "Price.histogram._count":567,
  "Venue.keyword.terms._count":567,
  "Price.histogram.interval":10,
  "_rollup.version":2,
  "Price.min.value":1.0387799739837646,
  "Venue.keyword.terms.value":"HOTSPOT",
  "Side.keyword.terms._count":567,
  "Symbol.keyword.terms.value":"AUD/NZD",
  "Price.max.value":1.0448600053787231,
  "VenueTimeStamp.date_histogram._count":567,
  "_rollup.id":"aggdepth_test2"
}
```

**Comment by polyfractal** [comment] 2019-08-06 15:20
Can you provide a bit more details?  What query are you using which is returning the incorrect average?  Can you paste it here?

**Comment by it-quod** [comment] 2019-08-07 06:03
Creating a simple Rollup Job on Kibana UI 

Below the json: `{
  "config": {
    "id": "aggdepth_test2",
    "index_pattern": "aggdepthentries",
    "rollup_index": "aggdepth_test2",
    "cron": "*/10 * * * * ?",
    "groups": {
      "date_histogram": {
        "fixed_interval": "10m",
        "field": "VenueTimeStamp",
        "delay": "20m",
        "time_zone": "UTC"
      },
      "histogram": {
        "interval": 10,
        "fields": [
          "Price"
        ]
      },
      "terms": {
        "fields": [
          "Side.keyword",
          "Symbol.keyword",
          "Venue.keyword"
        ]
      }
    },
    "metrics": [
      {
        "field": "Price",
        "metrics": [
          "avg",
          "max",
          "min",
          "sum"
        ]
      }
    ],
    "timeout": "20s",
    "page_size": 1000
  },
  "status": {
    "job_state": "started",
    "current_position": {
      "Price.histogram": 1480,
      "Side.keyword.terms": "Offer",
      "Symbol.keyword.terms": "XAU/USD",
      "Venue.keyword.terms": "DB",
      "VenueTimeStamp.date_histogram": 1565155800000
    },
    "upgraded_doc_id": true
  },
  "stats": {
    "pages_processed": 16586,
    "documents_processed": 42086687,
    "rollups_indexed": 41748,
    "trigger_count": 16398,
    "index_time_in_ms": 11679,
    "index_total": 188,
    "index_failures": 0,
    "search_time_in_ms": 3718959,
    "search_total": 16586,
    "search_failures": 0
  }
}`

**Comment by ajoliveira** [comment] 2019-11-30 03:01
I've been able to reproduce this in 7.4.0 ... the underlying query is being constructed incorrectly and using `sum` even though `avg` is being specified:
```
PUT _rollup/job/roll
{
  "index_pattern": "roll_test",
  "rollup_index": "roll",
  "cron": "0 * * * * ?",
  "page_size": 1000,
  "timeout": "20s",
  "groups": {
    "date_histogram": {
      "calendar_interval": "1m",
      "field": "@timestamp",
      "delay": "1h",
      "time_zone": "UTC"
    },
    "terms": {
      "fields": [
        "category.keyword"
      ]
    }
  },
  "metrics": [
    {
      "field": "my_count",
      "metrics": [
        "sum",
        "max",
        "min",
        "avg"
      ]
    }
  ]
}
```

My `avg` values were always the same as `sum`, so I enabled slowlogs and captured the following aggregation being submitted showing both fields being set to `sum` for `my_count.avg.value` and `my_count.sum.value`:

```
{
  "size": 0,
  "query": {
    "range": {
      "@timestamp": {
        "from": null,
        "to": null,
        "include_lower": true,
        "include_upper": true,
        "boost": 1
      }
    }
  },
  "track_total_hits": -1,
  "aggregations": {
    "rollup": {
      "meta": {
        "_rollup.interval": "1m"
      },
      "composite": {
        "size": 1000,
        "sources": [
          {
            "@timestamp.date_histogram": {
              "date_histogram": {
                "field": "@timestamp",
                "missing_bucket": false,
                "value_type": "date",
                "order": "asc",
                "calendar_interval": "1m",
                "time_zone": "UTC"
              }
            }
          },
          {
            "category.keyword.terms": {
              "terms": {
                "field": "category.keyword",
                "missing_bucket": true,
                "order": "asc"
              }
            }
          }
        ]
      },
      "aggregations": {
        "my_count.sum.value": {
          "sum": {
            "field": "my_count"
          }
        },
        "my_count.max.value": {
          "max": {
            "field": "my_count"
          }
        },
        "my_count.min.value": {
          "min": {
            "field": "my_count"
          }
        },
        "my_count.avg._count": {
          "value_count": {
            "field": "my_count"
          }
        },
        "my_count.avg.value": {
          "sum": {
            "field": "my_count"
          }
        }
      }
    }
  }
}
```

**Comment by polyfractal** [comment] 2019-12-04 14:33
This is actually intentional :)

An `avg` aggregation is internally constructed from two aggregations: `sum` on the count, and `sum` of the value.  These two sums are collected from across all the shards and then averaged together.  There are [java docs here](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/RollupRequestTranslator.java#L398-L421) describing the behavior.  This is why ES' rollup functionality can be used across multiple time scales.  

We don't save individual averages, and we can't use the `avg` aggregator directly because an average of an averages does not equal the average of all values.  Instead we save counts and values and recompute the average at the correct interval.

Generally, the queries being generated internally are considered "implementation details" since we have to jump through various hoops to rewrite a normal aggregation into something that matches the rollup conventions.

The real question is if the response is correct or not... if the avg is incorrect then that's a bug.

**Comment by it-quod** [comment] 2019-12-04 14:48
That is what we understood indeed .

We have started building the average with a scripted field
Using the avg._count and avg.value

if(!doc['Price.avg.value'].empty && !doc['Price.avg._count'].empty ) { doc['Price.avg.value'].value / doc['Price.avg._count'].value } else return 0

I am not sure that is the correct way to compute average, when you say "recompute the average"

This above solutions only works when creating "Standard Index Pattern"
Scripted field do not work when creating "Rollup index pattern"

Also that being said, what is then the point of avg , the value are duplicate from the already existing value_count and sum


**Price.avg._count
Price.avg.value**
Price.max.value
Price.min.value
**Price.sum.value
Price.value_count.value**

**Comment by ajoliveira** [comment] 2019-12-04 17:41
@it-quod To @polyfractal 's point, it appears to be easy to overlook (I did it myself), is that after the data is rolled up, to generate a valid 'avg' value or view the data as expected, you have to use the `_rollup_search` API - [docs](https://www.elastic.co/guide/en/elasticsearch/reference/7.4/rollup-search.html).

In my example, I was expecting a value of 7.5 ... but getting 15
```
    "hits" : [
      {
        "_index" : "roll",
        "_type" : "_doc",
        "_id" : "roll$T1JyrZl6IDvH3AbUJvff9A",
        "_score" : 1.0,
        "_source" : {
          "@timestamp.date_histogram._count" : 2,
          "@timestamp.date_histogram.interval" : "1m",
          "@timestamp.date_histogram.time_zone" : "UTC",
          "@timestamp.date_histogram.timestamp" : 1575018000000,
          "_rollup.id" : "roll",
          "_rollup.version" : 2,
          "category.keyword.terms._count" : 2,
          "category.keyword.terms.value" : "cat",
          "my_count.avg._count" : 2.0,
          "my_count.avg.value" : 15.0,
          "my_count.max.value" : 10.0,
          "my_count.min.value" : 5.0,
          "my_count.sum.value" : 15.0
        }
      }
    ]
```
However, requesting it via the `_rollup_search` API, did get me the expected result:
```
GET roll/_rollup_search
{
  "size": 0,
  "aggregations": {
    "final_avg": {
      "avg": {
        "field": "my_count"
      }
    }
  }
}

# OUTPUT
...
  "aggregations" : {
    "final_avg" : {
      "value" : 7.5
    }
  }

```
Also linking https://github.com/elastic/elasticsearch/issues/48005 here, as hopefully having this in the `_search` endpoint would avoid this confusion as well.

**Comment by polyfractal** [comment] 2019-12-05 14:48
++ to what @ajoliveira said.  The rollup indices can only be used with the dedicated `_rollup_search` endpoint, which knows how to translate and work with the internal rollup naming conventions.

If you use the regular `_search` endpoint, the documents are just regular documents with a strange naming convention, and none of the rollup searching functionality works.

> This above solutions only works when creating "Standard Index Pattern"
> Scripted field do not work when creating "Rollup index pattern"

It shouldn't be necessary for simple things like averages (e.g. we take care of that for you), but just an fyi: scripting does not currently work with Rollup indices, because of the field renaming issue.  The `_rollup_search` endpoint rewrites queries and aggregation field names to match the internal naming convention, but we can't rewrite scripts.  So that means a user would have to know how to convert field names according to our convention which is a poor experience.  So scripting is not currently supported.

> Also that being said, what is then the point of avg , the value are duplicate from the already existing value_count and sum
>
> Price.avg._count
> Price.avg.value
> Price.max.value
> Price.min.value
> Price.sum.value
> Price.value_count.value

These are the metrics Rollup are saving for the particular tuple at that point in time.  min/max/value_count are used by min/max/value_count aggregations.  `_count` and `sum` are used by the average aggregation.

The values might look like duplicates, but they are not always... it depends on the data.  E.g. the _count and value_count can be different if you have multi-valued fields.  Min/max/sum are obviously different quantities which can change depending on the interval of data.

There is some duplication (e.g. `sum.value` and `avg.value`) which we could improve.  Today Rollup saves all the metrics "in isolation" without seeing if a different metric provides the same value.  There's an issue for that here: https://github.com/elastic/elasticsearch/issues/47876

**Comment by vchan2002** [comment] 2020-04-11 04:29
I'm very glad that I stumbled up on this while trying to figure out how to use rollups, and the workaround of using a scripted field to get the "real" average out.  In my use case, my team is trying to use Kibana to build out metric visualizations based on data shipped from metricbeat.  With the day the dashboards were built and the requirements set, the amount of data being queried and aggregated against the raw metricbeat indexes would not have resulted in a good user experience.

**Comment by rokcarl** [comment] 2020-10-23 05:39
So, to recap, there's no bug demonstrated yet, correct? You just have to use `_rollup_search`.

**Comment by wchaparro** [comment] 2023-06-23 19:04
With the 8.7 release of Elasticsearch, we have made a [new downsampling capability](https://www.elastic.co/guide/en/elasticsearch/reference/current/downsampling.html) associated with the new [time series datastreams](https://www.elastic.co/guide/en/elasticsearch/reference/current/tsds.html) functionality generally available (GA). This capability was in tech preview in ILM since 8.5.  Downsampling provides a method to reduce the footprint of your time series data by storing it at reduced granularity. The downsampling process rolls up documents within a fixed time interval into a single summary document. Each summary document includes statistical representations of the original data: the min, max, sum, value_count, and average for each metric. Data stream time series dimensions are stored unchanged. 

Downsampling is superior to rollup because:

- Downsampled indices are searched through the _search API
- It is possible to query multiple downsampled indices together with raw data indices
- The pre-aggregation is based on the metrics and time series definitions in the index mapping so very little configuration is required (i.e. much easier to add new time serieses)
- Downsampling is managed as an action in ILM
- It is possible to downsample a downsampled index, and reduce granularity as the index ages
- The performance of the pre-aggregation process is superior in downsampling, as it builds on the time_series index mode infrastructure

Because of the introduction of this new capability, we are deprecating the rollups functionality, which never left the Tech Preview/Experimental status, in favor of downsampling and thus we are closing this issue. We encourage you to migrate your solution to downsampling and take advantage of the new TSDB functionality.

**Closed by wchaparro** 2023-06-23 19:04 UTC
Labels: :Analytics/Rollup, v7.4.0, Team:Analytics
