### ISSUE TITLE
[CI] SearchPhaseControllerTests.testSort fails on 5.0 branch

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#21442] opened 2016-11-09 21:12 UTC
CI Failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.0+multijob-unix-compatibility/os=oraclelinux/175/console

```
FAILURE 0.14s | SearchPhaseControllerTests.testSort <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <28>
   >      but: was <32>
   > 	at __randomizedtesting.SeedInfo.seed([90A4A80B117E3E9:58EF62A97A5AF9F9]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.action.search.SearchPhaseControllerTests.testSort(SearchPhaseControllerTests.java:77)
   > 	at java.lang.Thread.run(Thread.java:745)
```

This reproduces locally for me with:

```
gradle :core:test -Dtests.seed=90A4A80B117E3E9 -Dtests.class=org.elasticsearch.action.search.SearchPhaseControllerTests -Dtests.method="testSort" -Dtests.security.manager=true -Dtests.locale=ar-LB -Dtests.timezone=Asia/Baghdad
```

**Comment by dakrone** [comment] 2016-11-10 18:37
@areek the `SearchPhaseControllerTests` has your name all over it, can you take a look at this failure?

**Comment by colings86** [comment] 2017-04-26 09:43
Closing since I can no longer reproduce this on master, 5.x, 5.4 or 5.3 branches. If this failure reproduces please reopen

**Closed by colings86** 2017-04-26 09:43 UTC
Labels: :Search, test
