### ISSUE TITLE
[CI] SnapshotDisruptionIT. testDisruptionOnSnapshotInitialization fails unreproducibly

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#36779] opened 2018-12-18 15:25 UTC
See https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/837/console

Ran this with hundred iterations on Linux and once on osx, does not reproduce. Reproduction line is

```
 ./gradlew :server:integTest \
  -Dtests.seed=642A19B3B0D37154 \
  -Dtests.class=org.elasticsearch.discovery.SnapshotDisruptionIT \
  -Dtests.method="testDisruptionOnSnapshotInitialization" \
  -Dtests.security.manager=true \
  -Dtests.locale=hr-HR \
  -Dtests.timezone=Europe/Tirane \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

I saw another test failure in the last days. Log excerpt

```
  1> [2018-12-18T14:58:52,986][INFO ][o.e.d.SnapshotDisruptionIT] [testDisruptionOnSnapshotInitialization] after test
FAILURE 4.73s J1 | SnapshotDisruptionIT.testDisruptionOnSnapshotInitialization <<< FAILURES!
   > Throwable #1: java.lang.AssertionError:
   > Expected: an instance of org.elasticsearch.discovery.MasterNotDiscoveredException
   >      but: <RemoteTransportException[[node_tm1][127.0.0.1:41899][cluster:admin/snapshot/create]]; nested: ConcurrentSnaps
hotExecutionException[[test-repo:test-snap-2] cannot snapshot while a snapshot deletion is in-progress];> is a org.elasticsea
rch.transport.RemoteTransportException
   >    at __randomizedtesting.SeedInfo.seed([642A19B3B0D37154:4EF53F6396CB828B]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.discovery.SnapshotDisruptionIT.testDisruptionOnSnapshotInitialization(SnapshotDisruptionIT.java:
164)
   >    at java.lang.Thread.run(Thread.java:748)

```

Direct log https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/837/consoleText

**Comment by original-brownbear** [comment] 2018-12-18 22:22
Fixed incoming in  #36801 I think :)

**Comment by javanna** [comment] 2018-12-28 09:16
Another occurrence: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=java8fips,nodes=virtual&&linux/145/console

**Comment by javanna** [comment] 2018-12-28 12:00
and one more: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/218/console

**Comment by original-brownbear** [comment] 2018-12-28 13:37
Reproduced this again by putting a 5s sleep into the task in `org.elasticsearch.snapshots.SnapshotsService#deleteSnapshotFromRepository`. The same reproducer was fixed before ... seems something changed meanwhile. Looking into it.

**Comment by romseygeek** [comment] 2019-01-03 13:53
Another failure today:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+release-tests/288/console

Here it looks as though the cluster state reports that the snapshot has been aborted, but the SnapshotsService sees a success; this leads to a NoSuchFileException further down the line when the SnapshotsService tries to read metadata for a snapshot that does not in fact exist.

**Comment by romseygeek** [comment] 2019-01-03 13:55
Actually I think this failure was from a build that didn't have #37100 included so it can probably be ignored.

**Comment by atorok** [comment] 2019-01-09 14:52
It seems that this failure was after the commit: 
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java8fips,nodes=virtual&&linux/169/console

```
06:27:06   1> [2019-01-09T02:27:06,586][INFO ][o.e.d.SnapshotDisruptionIT] [testDisruptionOnSnapshotInitialization] after test
06:27:06 ERROR   5.02s J1 | SnapshotDisruptionIT.testDisruptionOnSnapshotInitialization <<< FAILURES!
06:27:06    > Throwable #1: SnapshotMissingException[[test-repo:test-snap-2] is missing]
06:27:06    > 	at __randomizedtesting.SeedInfo.seed([287964528C5DC44:2858B0950EDD2F9B]:0)
06:27:06    > 	at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:115)
06:27:06    > 	at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:54)
06:27:06    > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:127)
06:27:06    > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.doRun(TransportMasterNodeAction.java:208)
06:27:06    > 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:759)
06:27:06    > 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
06:27:06    > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
06:27:06    > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
06:27:06    > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by original-brownbear** [comment] 2019-01-09 15:16
Ah yikes that makes sense, that's another possible failure mode here ... sorry about that will fix very soon :)

**Comment by atorok** [comment] 2019-01-09 15:40
Muted test in ae086ebcc44

**Comment by tbrooks8** [comment] 2019-01-10 18:53
Failure in this build https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1189/console

```
Publication{term=2, version=38}
  1> [2019-01-10T13:22:04,999][INFO ][o.e.d.SnapshotDisruptionIT] [testDisruptionOnSnapshotInitialization] --> done
  1> [2019-01-10T13:22:05,007][WARN ][o.e.s.SnapshotsService   ] [node_tm0] [test-repo][test-snap-2] failed to create snapshot
  1> org.elasticsearch.snapshots.ConcurrentSnapshotExecutionException: [test-repo:test-snap-2] cannot snapshot while a snapshot deletion is in-progress
  1> 	at org.elasticsearch.snapshots.SnapshotsService$1.execute(SnapshotsService.java:255) ~[main/:?]
  1> 	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47) ~[main/:?]
  1> 	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:686) ~[main/:?]
  1> 	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:311) ~[main/:?]
  1> 	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:211) [main/:?]
  1> 	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:143) [main/:?]
  1> 	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [main/:?]
  1> 	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:660) [main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244) [main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207) [main/:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
  1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
```

```
FAILURE 71.0s J1 | SnapshotDisruptionIT.testDisruptionOnSnapshotInitialization <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: SnapshotMissingException[[test-repo:test-snap-2] is missing]
   > 	at __randomizedtesting.SeedInfo.seed([DD7787B0D526D4B7:F7A8A160F33E2768]:0)
   > 	at org.elasticsearch.discovery.SnapshotDisruptionIT.lambda$testDisruptionOnSnapshotInitialization$2(SnapshotDisruptionIT.java:185)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:847)
   > 	at org.elasticsearch.discovery.SnapshotDisruptionIT.testDisruptionOnSnapshotInitialization(SnapshotDisruptionIT.java:181)
   > 	at java.lang.Thread.run(Thread.java:748)
   > 	Suppressed: java.lang.AssertionError: SnapshotMissingException[[test-repo:test-snap-2] is missing]
   > 		at org.elasticsearch.discovery.SnapshotDisruptionIT.lambda$testDisruptionOnSnapshotInitialization$2(SnapshotDisruptionIT.java:185)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
   > 		... 38 more
   > 	Caused by: SnapshotMissingException[[test-repo:test-snap-2] is missing]
   > 		at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:115)
   > 		at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:54)
   > 		at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:127)
   > 		at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.doRun(TransportMasterNodeAction.java:208)
   > 		at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:759)
   > 		at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
   > 		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   > 		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   > 		... 1 more
   > 	Suppressed: java.lang.AssertionError: SnapshotMissingException[[test-repo:test-snap-2] is missing]
   > 		at org.elasticsearch.discovery.SnapshotDisruptionIT.lambda$testDisruptionOnSnapshotInitialization$2(SnapshotDisruptionIT.java:185)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
   > 		... 38 more
   > 	Caused by: SnapshotMissingException[[test-repo:test-snap-2] is missing]
```

**Comment by original-brownbear** [comment] 2019-01-10 19:34
@ywelsch I know we talked about this before so I'm 99% sure we decided not to worry about this, but just to make sure:

We run into the race between the snapshot being deleted here and the retry running again. Now that we have https://github.com/elastic/elasticsearch/pull/37289 it becomes visible that the retries don't work out in all cases.
Is this something we want to fix, no right? We're good with relaxing the test further to simply pass here so long as we don't have a stuck snapshot in the cluster-state as a result of the race from the retries?

**Comment by original-brownbear** [comment] 2019-01-11 11:44
Done in https://github.com/elastic/elasticsearch/pull/37358

**Comment by tlrx** [comment] 2019-02-27 09:16
The failure happens regularly on 6.7, like today:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.7+intake/250/
<details>
08:40:11   1> [2019-02-27T00:40:10,836][INFO ][o.e.d.SnapshotDisruptionIT] [testDisruptionOnSnapshotInitialization] after test
08:40:11 ERROR   40.3s J2 | SnapshotDisruptionIT.testDisruptionOnSnapshotInitialization <<< FAILURES!
08:40:11    > Throwable #1: SnapshotException[[test-repo:test-snap-2/WqkVybAjQC-VI4quafSYJg] Snapshot could not be read]; nested: SnapshotMissingException[[test-repo:test-snap-2/WqkVybAjQC-VI4quafSYJg] is missing]; nested: NoSuchFileException[/var/lib/jenkins/workspace/elastic+elasticsearch+6.7+intake/server/build/testrun/integTest/J2/temp/org.elasticsearch.discovery.SnapshotDisruptionIT_2F4E8816784D4C6C-001/tempDir-002/repos/KSdYkZwoLt/snap-WqkVybAjQC-VI4quafSYJg.dat];
08:40:11    > 	at __randomizedtesting.SeedInfo.seed([2F4E8816784D4C6C:591AEC65E55BFB3]:0)
08:40:11    > 	at org.elasticsearch.snapshots.SnapshotsService.snapshots(SnapshotsService.java:204)
08:40:11    > 	at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:136)
08:40:11    > 	at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:55)
08:40:11    > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:124)
08:40:11    > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.doRun(TransportMasterNodeAction.java:211)
08:40:11    > 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:751)
08:40:11    > 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
08:40:11    > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
08:40:11    > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
08:40:11    > 	at java.lang.Thread.run(Thread.java:748)
08:40:11    > Caused by: SnapshotMissingException[[test-repo:test-snap-2/WqkVybAjQC-VI4quafSYJg] is missing]; nested: NoSuchFileException[/var/lib/jenkins/workspace/elastic+elasticsearch+6.7+intake/server/build/testrun/integTest/J2/temp/org.elasticsearch.discovery.SnapshotDisruptionIT_2F4E8816784D4C6C-001/tempDir-002/repos/KSdYkZwoLt/snap-WqkVybAjQC-VI4quafSYJg.dat];
08:40:11    > 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getSnapshotInfo(BlobStoreRepository.java:557)
08:40:11    > 	at org.elasticsearch.snapshots.SnapshotsService.snapshots(SnapshotsService.java:198)
08:40:11    > 	... 9 more
08:40:11    > Caused by: java.nio.file.NoSuchFileException: /var/lib/jenkins/workspace/elastic+elasticsearch+6.7+intake/server/build/testrun/integTest/J2/temp/org.elasticsearch.discovery.SnapshotDisruptionIT_2F4E8816784D4C6C-001/tempDir-002/repos/KSdYkZwoLt/snap-WqkVybAjQC-VI4quafSYJg.dat
08:40:11    > 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
08:40:11    > 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
08:40:11    > 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
08:40:11    > 	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
08:40:11    > 	at java.nio.file.Files.newByteChannel(Files.java:361)
08:40:11    > 	at java.nio.file.Files.newByteChannel(Files.java:407)
08:40:11    > 	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
08:40:11    > 	at org.apache.lucene.mockfile.FilterFileSystemProvider.newInputStream(FilterFileSystemProvider.java:192)
08:40:11    > 	at org.apache.lucene.mockfile.FilterFileSystemProvider.newInputStream(FilterFileSystemProvider.java:192)
08:40:11    > 	at org.apache.lucene.mockfile.FilterFileSystemProvider.newInputStream(FilterFileSystemProvider.java:192)
08:40:11    > 	at org.apache.lucene.mockfile.HandleTrackingFS.newInputStream(HandleTrackingFS.java:92)
08:40:11    > 	at org.apache.lucene.mockfile.FilterFileSystemProvider.newInputStream(FilterFileSystemProvider.java:192)
08:40:11    > 	at org.apache.lucene.mockfile.HandleTrackingFS.newInputStream(HandleTrackingFS.java:92)
08:40:11    > 	at org.apache.lucene.mockfile.FilterFileSystemProvider.newInputStream(FilterFileSystemProvider.java:192)
08:40:11    > 	at org.apache.lucene.mockfile.HandleTrackingFS.newInputStream(HandleTrackingFS.java:92)
08:40:11    > 	at java.nio.file.Files.newInputStream(Files.java:152)
08:40:11    > 	at org.elasticsearch.common.blobstore.fs.FsBlobContainer.readBlob(FsBlobContainer.java:120)
08:40:11    > 	at org.elasticsearch.repositories.blobstore.ChecksumBlobStoreFormat.readBlob(ChecksumBlobStoreFormat.java:101)
08:40:11    > 	at org.elasticsearch.repositories.blobstore.BlobStoreFormat.read(BlobStoreFormat.java:90)
08:40:11    > 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getSnapshotInfo(BlobStoreRepository.java:555)
08:40:11    > 	... 10 more
08:40:11 Completed [163/334] on J2 in 40.34s, 1 test, 1 error <<< FAILURES!
</details>

I'm reopening this issue to raise your attention @original-brownbear. Test was muted on 6.7 in e2b79f07fb97f075544f3e2718c2809473f7cbde

**Comment by original-brownbear** [comment] 2019-05-21 10:50
wops forgot all about this one, backported to `6.8` now in #37358 => closing here since all newer branches have the fix for this already.

**Closed by original-brownbear** 2019-05-21 10:50 UTC
Labels: :Distributed/Snapshot/Restore, >test-failure, v7.2.0
