### ISSUE TITLE
ingest: Default index pipeline not being applied to docs during bulk indexing

### ISSUE THREAD

**Issue by rfraposa** [elastic/elasticsearch#36144] opened 2018-12-02 22:09 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 6.5.1

**Description of the problem including expected versus actual behavior**: I am indexing a Google spreadsheet (using the add-on: https://github.com/elastic/google-sheets-add-on) into a 6.5.1 cluster. The index has a default pipeline defined, which works as expected if I use `_bulk` from within Console. But the pipeline is not being applied to docs indexed using a `_bulk` insert from the JavaScript code.

**Comment by jakelandis** [comment] 2018-12-02 23:17
@rfraposa - could this be a due to https://github.com/elastic/elasticsearch/issues/35817 ?  (Console doesn't do anything special with the request)

If so, can we close as a duplicate ?

**Comment by rfraposa** [comment] 2018-12-02 23:50
I don't know if it is the same issue, but it might be. The JavaScript code is not using any aliases - the `_bulk` command uses the actual index name.

**Comment by jakelandis** [comment] 2018-12-03 16:22
Is it possible to grab the http requests that are being sent from JavaScript ?

Or can you provide a reproduction scenario ?

**Comment by rfraposa** [comment] 2018-12-03 18:21
I don't seem to be able to see the requests - not sure why. I'll PM you a link to a google doc with everyone configured and ready for testing.

**Comment by rfraposa** [comment] 2018-12-03 23:20
Sorry @jakelandis - I don't know the Add-On works, but it appears to use a callback mechanism. The data is not posted from my browser, so I can't see the `_bulk` command. 

At any rate, my guess is that this is a duplicate of #35817 - it's the only thing that makes sense.

**Comment by jakelandis** [comment] 2018-12-03 23:45
closing and will take a closer look outside of this issue.

**Closed by jakelandis** 2018-12-03 23:45 UTC
Labels: :Core/Features/Ingest

**Comment by jakelandis** [comment] 2018-12-04 16:00
I believe the root cause of this issue is https://github.com/elastic/elasticsearch/issues/36219 (which was uncovered by investigating this issue) thanks for report @rfraposa !
