### ISSUE TITLE
[ES|QL] Valid query with list is returning null

### ISSUE THREAD

**Issue by dej611** [elastic/elasticsearch#99663] opened 2023-09-19 13:23 UTC
### Description

While testing on Kibana I've noticed that this is a valid query:

```
row a =1 | eval b = 1 + [1, 2, 3]
```

but the result is `b is -` (which I assume is `null`). At least is not returning weird numbers.

Few questions here:
* is that supposed to work/be valid?
* what should it be the correct result?

**Comment by alex-spies** [comment] 2023-09-19 14:02
Hi @dej611 !

Thanks for the find! Currently, I don't think this is supposed to be valid and should at least place a warning in the header of the response. I can confirm that your query *does not even create a warning*.

There's a related issue, where `+` signs in front of multivalue literals are permitted, but `-` signs aren't: #98401

Enabling expressions like this could make sense in the future, since it would be intuitive to expect that `1 * [1, 2, 3] == [1*1, 1*2, 1*3]` (not sure about `+/-`, though).

**Comment by dej611** [comment] 2023-09-19 14:14
From a quick check also performing a math operation between two multi-valued field result in `null`:
```
row a =1 | eval b = [2, 3, 4] + [1, 2, 3]
```

`b` is still `null`.

**Comment by bpintea** [comment] 2023-09-19 15:08
> @bpintea is working on miking this emit a warning.

This is tracked here: https://github.com/elastic/elasticsearch/issues/98743

> From a quick check also performing a math operation between two multi-valued field result in null

The behaviour of functions with multivalues has been discussed and we started with a simple approach of returning `null`, with some exceptions, for unary functions. We can push the limit here (I've opened [an issue](https://github.com/elastic/elasticsearch/issues/99672) for that), but the problem of n-ary functions with multivalues doesn't have both a "standard" (arithmetic) and intuitive behaviour so I guess that might take a bit longer.

> [2, 3, 4] + [1, 2, 3]

Your example has two operands with same cardinality, but should `[2, 3] + [1, 2, 3]` return a cartesian product? Is this useful / expected? Noteworthy, the existing `mv_xxx()` functions are available to "ease" working with MVs.

**Comment by nik9000** [comment] 2023-09-19 15:50
> From a quick check also performing a math operation between two multi-valued field result in `null`:
> 
> ```
> row a =1 | eval b = [2, 3, 4] + [1, 2, 3]
> ```
> 
> `b` is still `null`.

Yeah. Touching any multi-valued field with most operations will result in `null`. Like @bpintea says, you could, for example, do `| eval b = mv_min([2, 3, 4]) + mv_max([1, 2, 3])` and get `5`. But that's probably not what you are looking for.

We know at some point we'll need to process multivalued fields and produce multivalue fields. Something like:

|       name        |  lhs  |  rhs  |    answer |
|-------------------|-------|-------|-----------|
|  how it works now |     1 |     2 |         3 |
|     apply to each | [1,2] |     2 |     [3,4] |
| cartesian product | [1,2] | [1,2] | [1,2,3,4] |
|          pairwise | [1,2] | [1,2] |     [2,4] |

I the trick is - what syntax should *do* these things? At this point, I dunno. For a long time I was for no special syntax to get at least line 2. But it feels like we *do* want special syntax for cartesian products and pairwise application. But, at least for now, most functions return `null` if the see a multivalued field. The exception is `to_xx` which applies to each value.

**Comment by bpintea** [comment] 2023-09-20 12:22
The current behaviour is also [documented](https://www.elastic.co/guide/en/elasticsearch/reference/master/esql-multivalued-fields.html#esql-multivalued-fields-functions).

Will close this issue for now, as it works as intended, but feel free to reopen if some aspects have been missed. 🙏

**Closed by bpintea** 2023-09-20 12:22 UTC
Labels: >enhancement, Team:QL, :Query Languages/ES|QL
