### ISSUE TITLE
Exists filters have bad performance

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/elasticsearch#22657] opened 2017-01-17 14:07 UTC
**Elasticsearch version**: Elasticsearch 5.1

**Plugins installed**: -]

**JVM version**: Any

**OS version**: Any

**Description of the problem including expected versus actual behavior**:

In 2.x the the missing query has been deprecated, and one should use and _exists query_ inside a _must_not_ clause. In 5.1 the only option is to use the exists query in a must not.

Doing some tests, i noticed that the execution of the bool with a must not is not performing as good as one expects. 

The test is the following:

1. Multiple types included
2. More than 10 million documents
3. And the following query:

```
{
  "query": {
    "bool": {
      "filter": [
        {
          "term": {
            "BOOL_FIELD1": false
          }
        },
        {
          "range": {
            "DATE_FIELD2": {
              "lte": "2017-01-01"
            }
          }
        }
      ],
      "should": [
        {
          "bool": {
            "must_not": {
              "exists": {
                "field": "DATE_FIELD1"
              }
            }
          }
        },
        {
          "range": {
            "DATE_FIELD1": {
              "gt": "2017-01-01"
            }
          }
        }
      ]
    }
  }
}
```

The profiler shows that at some point inside the `bool>must_not` we are doing an expensive match_all clause:

```
"query": [
    {
        "type": "BooleanQuery",
        "description": "+((-ConstantScore(_field_names:DATE_FIELD1) +*:*) DATE_FIELD1:[1483315200000 TO 9223372036854775807] #BOOL_FIELD1:F #DATE_FIELD2:[-9223372036854775808 TO 1483315199999]) #(ConstantScore(_type:TYPE_1))^0.0",
        "time": "3951.448731ms",
        "breakdown": {
            "score": 2310059550,
            "build_scorer_count": 27,
            "match_count": 0,
            "create_weight": 587195,
            "next_doc": 1629358099,
            "match": 0,
            "create_weight_count": 1,
            "next_doc_count": 3489324,
            "score_count": 3489319,
            "build_scorer": 4465216,
            "advance": 0,
            "advance_count": 0
        },
        "children": [
            {
                "type": "BooleanQuery",
                "description": "(-ConstantScore(_field_names:DATE_FIELD1) +*:*) DATE_FIELD1:[1483315200000 TO 9223372036854775807] #BOOL_FIELD1:F #DATE_FIELD2:[-9223372036854775808 TO 1483315199999]",
                "time": "2716.687540ms",
                "breakdown": {
                    "score": 1977436672,
                    "build_scorer_count": 27,
                    "match_count": 0,
                    "create_weight": 513144,
                    "next_doc": 0,
                    "match": 0,
                    "create_weight_count": 1,
                    "next_doc_count": 0,
                    "score_count": 3489319,
                    "build_scorer": 4299218,
                    "advance": 727459835,
                    "advance_count": 3489324
                },
                "children": [
                    {
                        "type": "BooleanQuery",
                        "description": "-ConstantScore(_field_names:DATE_FIELD1) +*:*",
                        "time": "1121.160176ms",
                        "breakdown": {
                            "score": 384220941,
                            "build_scorer_count": 27,
                            "match_count": 3493583,
                            "create_weight": 484754,
                            "next_doc": 44583944,
                            "match": 294190414,
                            "create_weight_count": 1,
                            "next_doc_count": 362672,
                            "score_count": 3126806,
                            "build_scorer": 1680096,
                            "advance": 385886027,
                            "advance_count": 3130911
                        },
                        "children": [
                            {
                                "type": "ConstantScoreQuery", <---------- This is the missing clause
                                "description": "ConstantScore(_field_names:DATE_FIELD1)", 
                                "time": "45.20257600ms",
                                "breakdown": {
                                    "score": 0,
                                    "build_scorer_count": 27,
                                    "match_count": 0,
                                    "create_weight": 462958,
                                    "next_doc": 0,
                                    "match": 0,
                                    "create_weight_count": 1,
                                    "next_doc_count": 0,
                                    "score_count": 0,
                                    "build_scorer": 1214111,
                                    "advance": 43162585,
                                    "advance_count": 362894
                                },
                                "children": [
                                    {
                                        "type": "TermQuery",
                                        "description": "_field_names:DATE_FIELD1",
                                        "time": "17.49171500ms",
                                        "breakdown": {
                                            "score": 0,
                                            "build_scorer_count": 27,
                                            "match_count": 0,
                                            "create_weight": 21463,
                                            "next_doc": 0,
                                            "match": 0,
                                            "create_weight_count": 1,
                                            "next_doc_count": 0,
                                            "score_count": 0,
                                            "build_scorer": 399236,
                                            "advance": 16708094,
                                            "advance_count": 362894
                                        }
                                    }
                                ]
                            },
                            {
                                "type": "MatchAllDocsQuery",    <---------- HERE , matching all documents.
                                "description": "*:*",
                                "time": "301.1009210ms",
                                "breakdown": {
                                    "score": 115027006,
                                    "build_scorer_count": 27,
                                    "match_count": 0,
                                    "create_weight": 1391,
                                    "next_doc": 18151692,
                                    "match": 0,
                                    "create_weight_count": 1,
                                    "next_doc_count": 362672,
                                    "score_count": 3126806,
                                    "build_scorer": 18448,
                                    "advance": 161281967,
                                    "advance_count": 3130911
                                }
                            }
                        ]
                    },
                    {
                        "type": "",
                        "description": "DATE_FIELD1:[1483315200000 TO 9223372036854775807]",
                        "time": "0.9628580000ms",
                        "breakdown": {
                            "score": 1856,
                            "build_scorer_count": 27,
                            "match_count": 0,
                            "create_weight": 2788,
                            "next_doc": 0,
                            "match": 0,
                            "create_weight_count": 1,
                            "next_doc_count": 0,
                            "score_count": 6,
                            "build_scorer": 899073,
                            "advance": 59093,
                            "advance_count": 14
                        }
                    },
                    {
                        "type": "TermQuery",
                        "description": "BOOL_FIELD1:F",
                        "time": "146.7007190ms",
                        "breakdown": {
                            "score": 0,
                            "build_scorer_count": 27,
                            "match_count": 0,
                            "create_weight": 2866,
                            "next_doc": 0,
                            "match": 0,
                            "create_weight_count": 1,
                            "next_doc_count": 0,
                            "score_count": 0,
                            "build_scorer": 181639,
                            "advance": 143026853,
                            "advance_count": 3489333
                        }
                    },
                    {
                        "type": "",
                        "description": "DATE_FIELD2:[-9223372036854775808 TO 1483315199999]",
                        "time": "139.4384300ms",
                        "breakdown": {
                            "score": 0,
                            "build_scorer_count": 26,
                            "match_count": 0,
                            "create_weight": 1177,
                            "next_doc": 0,
                            "match": 0,
                            "create_weight_count": 1,
                            "next_doc_count": 0,
                            "score_count": 0,
                            "build_scorer": 654853,
                            "advance": 135293049,
                            "advance_count": 3489324
                        }
                    }
                ]
            },
            {
                "type": "BoostQuery",
                "description": "(ConstantScore(_type:TYPE_1))^0.0",
                "time": "442.0722720ms",
                "breakdown": {
                    "score": 0,
                    "build_scorer_count": 26,
                    "match_count": 0,
                    "create_weight": 9132,
                    "next_doc": 436935469,
                    "match": 0,
                    "create_weight_count": 1,
                    "next_doc_count": 3489324,
                    "score_count": 0,
                    "build_scorer": 56264,
                    "advance": 1572452,
                    "advance_count": 9604
                },
                "children": [
                    {
                        "type": "TermQuery",
                        "description": "_type:TYPE_1",
                        "time": "189.9574780ms",
                        "breakdown": {
                            "score": 0,
                            "build_scorer_count": 26,
                            "match_count": 0,
                            "create_weight": 2575,
                            "next_doc": 185530777,
                            "match": 0,
                            "create_weight_count": 1,
                            "next_doc_count": 3489324,
                            "score_count": 0,
                            "build_scorer": 40296,
                            "advance": 884875,
                            "advance_count": 9604
                        }
                    }
                ]
            }
        ]
    }
],
```

So it looks like either we are doing not-necessary steps when using the Exists inside a bool, or we should bring back a "missing" that knows that it should do a Match all. Filtering by type is taking a similar time than doing a `must_not>exists`.

Opening this to discuss whether: 

1. Do we need to bring back the Missing filter/query?
2. Is there something that we should do/recommend apart from doing `must_not>exists`?

**Comment by gmoskovicz** [comment] 2017-01-17 15:10
Performed another similar test.

[1] Normal `bool>must_not`

```
GET logstash-2017.01.17/_search
{
  "query": {
    "bool": {
      "must_not": {
        "exists": {
          "field": "field1"
        }
      }
    }
  }
}
```

Results: from 40ms to 45ms

[2] Constant score query

```
GET logstash-2017.01.17/_search
{
  "query": {
    "constant_score": {
      "filter": {
        "bool": {
          "must_not": {
            "exists": {
              "field": "field1"
            }
          }
        }
      }
    }
  }
}
```

Results: from 28ms to 41ms

[2] Filter>bool>must_not

```
GET logstash-2017.01.17/_search
{
  "query": {
    "bool": {
      "filter": {
        "bool": {
          "must_not": {
            "exists": {
              "field": "field1"
            }
          }
        }
      }
    }
  }
}
```

Results: from 28ms to 39ms


The test was performed in an index with the following configuration in 1 node only:

```
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 12215398,
    "max_score": 0,
    "hits": []
  }
}
```

```
logstash-2017.01.17                   2 p STARTED    2443397 182.1mb 127.0.0.1 PZyNogU
logstash-2017.01.17                   2 r UNASSIGNED                           
logstash-2017.01.17                   1 p STARTED    2441482 181.3mb 127.0.0.1 PZyNogU
logstash-2017.01.17                   1 r UNASSIGNED                           
logstash-2017.01.17                   3 p STARTED    2443738 201.9mb 127.0.0.1 PZyNogU
logstash-2017.01.17                   3 r UNASSIGNED                           
logstash-2017.01.17                   4 p STARTED    2444459 182.3mb 127.0.0.1 PZyNogU
logstash-2017.01.17                   4 r UNASSIGNED                           
logstash-2017.01.17                   0 p STARTED    2442322 236.5mb 127.0.0.1 PZyNogU
logstash-2017.01.17                   0 r UNASSIGNED   
```

**Comment by clintongormley** [comment] 2017-01-17 15:59
@jpountz it looks like the implicit `match_all` is scoring docs, which is taking the majority of the time.  Could this be improved by disabling scoring?

I assume that most of the cost is building the bitset for all docs minus those which have the field.

**Comment by jpountz** [comment] 2017-01-17 17:16
> it looks like the implicit match_all is scoring docs, which is taking the majority of the time. Could this be improved by disabling scoring?

The long timing for scoring on the `match_all` query is not the cause of the problem but rather a side-effect: this query is mostly slow because it matches lots of documents. The reason is that we have to visit all matching documents in order to compute the total hit count and the top hits. We do indeed score, but if you look at the timings, it is not the bottleneck: we spend a similar amount of time in `advance` and `matches`. Disabling scoring might speed things up a bit, but not significantly.

I don't think there is much we can do here.

**Comment by gmoskovicz** [comment] 2017-01-17 17:21
@jpountz @clintongormley 

I opened this issue not only to see if we can do something to speed up this, but also to maybe think about a documentation change to make sure that everyone does an `exists` wrapped by a `constant_score`. That is what it gives the best results.

Also, visiting all the documents doesn't make any sense as when using `exists` we usually don't want the top documents, but just to filter those documents as soon as the field exists or not.

Should we change the recommendation from `bool>must_not>exists` to `constant_score>filter>bool>must_not>exists`?

**Comment by jpountz** [comment] 2017-01-17 18:25
Docs already mention that filters are preferable to queries when scores do not matter, so I think we are good from that perspective? The `exists` query is not different from other queries.

Additionally I'm wondering that the speedup that you saw with `constant_score` wrapping might be due to the fact the query gets cached rather than because scores are not computed?

> Also, visiting all the documents doesn't make any sense as when using exists we usually don't want the top documents, but just to filter those documents as soon as the field exists or not.

True, but even in that case we still need to count the number of documents that match.

**Comment by colings86** [comment] 2017-03-31 09:52
@jpountz is there anything to be done here?

**Comment by jpountz** [comment] 2017-03-31 11:59
Agreed there is nothing left to be done. Closing.

**Closed by jpountz** 2017-03-31 11:59 UTC
Labels: :Search, enhancement
