### ISSUE TITLE
Elasticsearch does not refresh AWS Web ID Token

### ISSUE THREAD

**Issue by ahmetdd** [elastic/elasticsearch#118678] opened 2024-12-13 15:05 UTC
### Elasticsearch Version

8.16.1

### Java Version

_bundled_

### OS Version

Kubernetes

### Problem Description

S3 repository setups rely on AWS IAM roles (IRSA) for service accounts become inaccessible after a while. when we restart the pods, access is provided but after a while it comes back to the same situation and cannot access.

### Steps to Reproduce

https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-snapshots.html#k8s-iam-service-accounts

I'm creating Aws s3 setup for snapshot. 
When I first run it, it successfully accesses s3 but after a while it becomes inaccessible.

### Logs (if relevant)

{
  "error": {
    "root_cause": [
      {
        "type": "repository_verification_exception",
        "reason": "[repo] path  is not accessible on master node"
      }
    ],
    "type": "repository_verification_exception",
    "reason": "[Repo] path  is not accessible on master node",
    "caused_by": {
      "type": "i_o_exception",
      "reason": "Unable to upload object [tests-u7JQMsD-QrERESFFDfdfdA/master.dat] using a single upload",
      "caused_by": {
        "type": "amazon_client_exception",
        "reason": "amazon_client_exception: java.lang.IllegalStateException: Connection pool shut down",
        }
      }
    }
  },
  "status": 500
}

**Comment by pxsalehi** [comment] 2024-12-13 15:37
Duplicate of https://github.com/elastic/elasticsearch/issues/115186 it seems. I'll close this. Feel free to reopen if it is not a duplicate.

**Closed by pxsalehi** 2024-12-13 15:37 UTC
Labels: >bug, needs:triage
