### ISSUE TITLE
[CI] MlTrainedModelsUpgradeIT testTrainedModelInference failing

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#81932] opened 2021-12-20 14:42 UTC
**Build scan:**
https://gradle-enterprise.elastic.co/s/lhnje5oufbvgq/tests/:x-pack:qa:rolling-upgrade:v7.16.2%23oldClusterTest/org.elasticsearch.upgrades.MlTrainedModelsUpgradeIT/testTrainedModelInference

**Reproduction line:**
`./gradlew ':x-pack:qa:rolling-upgrade:v7.16.2#oldClusterTest' -Dtests.class="org.elasticsearch.upgrades.MlTrainedModelsUpgradeIT" -Dtests.method="testTrainedModelInference" -Dtests.seed=9308E9DA28C975CE -Dtests.bwc=true -Dtests.locale=sq -Dtests.timezone=Australia/Eucla -Druntime.java=8`

**Applicable branches:**
7.17

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.upgrades.MlTrainedModelsUpgradeIT&tests.test=testTrainedModelInference

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: "stopped"
     but: was "failed"

  at __randomizedtesting.SeedInfo.seed([9308E9DA28C975CE:C84A77CF940160D]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.upgrades.MlTrainedModelsUpgradeIT.lambda$putAndStartDFAAndWaitForFinish$3(MlTrainedModelsUpgradeIT.java:216)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1123)
  at org.elasticsearch.upgrades.MlTrainedModelsUpgradeIT.putAndStartDFAAndWaitForFinish(MlTrainedModelsUpgradeIT.java:212)
  at org.elasticsearch.upgrades.MlTrainedModelsUpgradeIT.createAndRunClassificationJob(MlTrainedModelsUpgradeIT.java:203)
  at org.elasticsearch.upgrades.MlTrainedModelsUpgradeIT.testTrainedModelInference(MlTrainedModelsUpgradeIT.java:58)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at java.lang.Thread.run(Thread.java:748)

```

**Comment by pgomulka** [comment] 2021-12-22 13:48
another one - did not reproduce locally.
https://gradle-enterprise.elastic.co/s/s32wnl73b7mpm/tests/:x-pack:qa:rolling-upgrade:v7.16.3%23oldClusterTest/org.elasticsearch.upgrades.MlTrainedModelsUpgradeIT/testTrainedModelInference?expanded-stacktrace=WyIwIl0&top-execution=1

what surprised me a little bit was that the assertion waits for 1minute. Is this really necessary to wait that long?

**Comment by davidkyle** [comment] 2021-12-23 10:49
The logs reveal the root cause to be an error in the Painless script engine.

```
org.elasticsearch.script.ScriptException: compile error
	at org.elasticsearch.painless.PainlessScriptEngine.convertToScriptException(PainlessScriptEngine.java:495) ~[?:?]
	at org.elasticsearch.painless.PainlessScriptEngine.compile(PainlessScriptEngine.java:406) ~[?:?]
	at org.elasticsearch.painless.PainlessScriptEngine.compile(PainlessScriptEngine.java:129) ~[?:?]
	at org.elasticsearch.script.ScriptCache.lambda$compile$0(ScriptCache.java:101) ~[elasticsearch-7.16.3-SNAPSHOT.jar:7.16.3-SNAPSHOT]
	at org.elasticsearch.common.cache.Cache.computeIfAbsent(Cache.java:419) ~[elasticsearch-7.16.3-SNAPSHOT.jar:7.16.3-SNAPSHOT]
	at org.elasticsearch.script.ScriptCache.compile(ScriptCache.java:83) ~[elasticsearch-7.16.3-SNAPSHOT.jar:7.16.3-SNAPSHOT]
	at org.elasticsearch.script.ScriptService.compile(ScriptService.java:612) ~[elasticsearch-7.16.3-SNAPSHOT.jar:7.16.3-SNAPSHOT]
	at org.elasticsearch.reindex.AbstractAsyncBulkByScrollAction$ScriptApplier.apply(AbstractAsyncBulkByScrollAction.java:851) ~[?:?]
	at org.elasticsearch.reindex.AbstractAsyncBulkByScrollAction$ScriptApplier.apply(AbstractAsyncBulkByScrollAction.java:812) ~[?:?]
	at org.elasticsearch.reindex.AbstractAsyncBulkByScrollAction.buildBulk(AbstractAsyncBulkByScrollAction.java:250) ~[?:?]
	at org.elasticsearch.reindex.AbstractAsyncBulkByScrollAction.prepareBulkRequest(AbstractAsyncBulkByScrollAction.java:386) ~[?:?]
	at org.elasticsearch.reindex.AbstractAsyncBulkByScrollAction$1.doRun(AbstractAsyncBulkByScrollAction.java:345) ~[?:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:777) ~[elasticsearch-7.16.3-SNAPSHOT.jar:7.16.3-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-7.16.3-SNAPSHOT.jar:7.16.3-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.RunOnce.run(RunOnce.java:29) ~[elasticsearch-7.16.3-SNAPSHOT.jar:7.16.3-SNAPSHOT]
	at org.elasticsearch.index.reindex.WorkerBulkByScrollTaskState$DelayedPrepareBulkRequest.lambda$new$0(WorkerBulkByScrollTaskState.java:254) ~[elasticsearch-7.16.3-SNAPSHOT.jar:7.16.3-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:718) ~[elasticsearch-7.16.3-SNAPSHOT.jar:7.16.3-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalAccessError: failed to access class org.objectweb.asm.Edge from class org.objectweb.asm.MethodWriter (org.objectweb.asm.Edge is in unnamed module of loader 'app'; org.objectweb.asm.MethodWriter is in unnamed module of loader java.net.FactoryURLClassLoader @27068a50)
	at org.objectweb.asm.MethodWriter.addSuccessorToCurrentBasicBlock(MethodWriter.java:1782) ~[Log4jHotPatchFat.jar:?]
	at org.objectweb.asm.MethodWriter.visitLabel(MethodWriter.java:1224) ~[Log4jHotPatchFat.jar:?]
	at org.objectweb.asm.commons.GeneratorAdapter.mark(GeneratorAdapter.java:904) ~[?:?]
	at org.elasticsearch.painless.phase.DefaultIRTreeToASMBytesPhase.visitTry(DefaultIRTreeToASMBytesPhase.java:670) ~[?:?]
	at org.elasticsearch.painless.phase.DefaultIRTreeToASMBytesPhase.visitTry(DefaultIRTreeToASMBytesPhase.java:178) ~[?:?]
	at org.elasticsearch.painless.ir.TryNode.visit(TryNode.java:44) ~[?:?]
	at org.elasticsearch.painless.phase.DefaultIRTreeToASMBytesPhase.visit(DefaultIRTreeToASMBytesPhase.java:181) ~[?:?]
	at org.elasticsearch.painless.phase.DefaultIRTreeToASMBytesPhase.visitBlock(DefaultIRTreeToASMBytesPhase.java:337) ~[?:?]
	at org.elasticsearch.painless.phase.DefaultIRTreeToASMBytesPhase.visitBlock(DefaultIRTreeToASMBytesPhase.java:178) ~[?:?]
	at org.elasticsearch.painless.ir.BlockNode.visit(BlockNode.java:35) ~[?:?]
	at org.elasticsearch.painless.phase.DefaultIRTreeToASMBytesPhase.visit(DefaultIRTreeToASMBytesPhase.java:181) ~[?:?]
	at org.elasticsearch.painless.phase.DefaultIRTreeToASMBytesPhase.visitFunction(DefaultIRTreeToASMBytesPhase.java:319) ~[?:?]
	at org.elasticsearch.painless.phase.DefaultIRTreeToASMBytesPhase.visitFunction(DefaultIRTreeToASMBytesPhase.java:178) ~[?:?]
	at org.elasticsearch.painless.ir.FunctionNode.visit(FunctionNode.java:32) ~[?:?]
	at org.elasticsearch.painless.phase.DefaultIRTreeToASMBytesPhase.visit(DefaultIRTreeToASMBytesPhase.java:181) ~[?:?]
	at org.elasticsearch.painless.phase.DefaultIRTreeToASMBytesPhase.visitClass(DefaultIRTreeToASMBytesPhase.java:259) ~[?:?]
	at org.elasticsearch.painless.phase.DefaultIRTreeToASMBytesPhase.visitScript(DefaultIRTreeToASMBytesPhase.java:186) ~[?:?]
	at org.elasticsearch.painless.Compiler.compile(Compiler.java:221) ~[?:?]
	at org.elasticsearch.painless.PainlessScriptEngine$2.run(PainlessScriptEngine.java:401) ~[?:?]
	at org.elasticsearch.painless.PainlessScriptEngine$2.run(PainlessScriptEngine.java:397) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
	at org.elasticsearch.painless.PainlessScriptEngine.compile(PainlessScriptEngine.java:397) ~[?:?]
	... 18 more
```

**Comment by davidkyle** [comment] 2021-12-23 10:50
Closing in favour of #81915

**Closed by davidkyle** 2021-12-23 10:50 UTC
Labels: >test-failure, :ml, Team:ML

**Comment by davidkyle** [comment] 2021-12-23 10:54
> what surprised me a little bit was that the assertion waits for 1minute. Is this really necessary to wait that long?

Yes, the test is performing some complicated analysis through many processing stages. On a busy CI machine it could take a long time. It is best to avoid false negative test failures on a slow machine by setting the timeout to a high value
