### ISSUE TITLE
Decimal histograms

### ISSUE THREAD

**Issue by njss** [elastic/elasticsearch#16474] opened 2016-02-05 13:07 UTC
I am not finding any good reference about how to set up a range histogram using decimal bins.
I could find a plugin that implements this (until version 1.XX) but I am worried with the sustainability of this fix.
Any new plans?

**Comment by jpountz** [comment] 2016-02-08 09:11
Duplicate of #4847.

Nothing new unfortunately. Aggregations are currently undergoing a significant refactoring that aims at making them parsed on the coordinating node instead of only on the shards. Once it is finished, I think we should look into this feature again.

**Closed by jpountz** 2016-02-08 09:11 UTC

**Comment by njss** [comment] 2016-02-08 11:19
Ok, thank you for the answer.
This is considered a very important feature, right!?
