### ISSUE TITLE
[CI] RecoveryFromGatewayIT testMessyElectionsStillMakeClusterGoGreen failing

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#91975] opened 2022-11-28 16:29 UTC
**Build scan:**
https://gradle-enterprise.elastic.co/s/e5iycrl42ofjm/tests/:server:internalClusterTest/org.elasticsearch.gateway.RecoveryFromGatewayIT/testMessyElectionsStillMakeClusterGoGreen

**Reproduction line:**
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.gateway.RecoveryFromGatewayIT.testMessyElectionsStillMakeClusterGoGreen" -Dtests.seed=BA02796B06E5F0E9 -Dtests.locale=hi -Dtests.timezone=America/Phoenix -Druntime.java=17
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.gateway.RecoveryFromGatewayIT&tests.test=testMessyElectionsStillMakeClusterGoGreen

**Failure excerpt:**
```
java.lang.AssertionError: (No message provided)

  at org.junit.Assert.fail(Assert.java:86)
  at org.junit.Assert.assertTrue(Assert.java:41)
  at org.junit.Assert.assertFalse(Assert.java:64)
  at org.junit.Assert.assertFalse(Assert.java:74)
  at org.elasticsearch.test.InternalTestCluster.validateClusterFormed(InternalTestCluster.java:1215)
  at org.elasticsearch.test.InternalTestCluster.startAndPublishNodesAndClients(InternalTestCluster.java:1746)
  at org.elasticsearch.test.InternalTestCluster.fullRestart(InternalTestCluster.java:1956)
  at org.elasticsearch.test.InternalTestCluster.fullRestart(InternalTestCluster.java:1840)
  at org.elasticsearch.gateway.RecoveryFromGatewayIT.testMessyElectionsStillMakeClusterGoGreen(RecoveryFromGatewayIT.java:710)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by kingherc** [comment] 2023-01-13 14:04
By reviewing the complete logs, I notice that this assertion is before:

```
WARNING: Uncaught exception in thread: Thread[elasticsearch[node_t2][clusterApplierService#updateTask][T#1],5,TGRP-RecoveryFromGatewayIT]
java.lang.AssertionError: liveNodes = [{node_t0}{mGJa4e-LRF-6t6B0q8-V7A}{x4TNRVQkSQm141ajKIenWA}{node_t0}{127.0.0.1}{127.0.0.1:21763}{cdfhilmrstw}, {node_t1}{jEx9BOVOTNuM8xrO8Sa7Qg}{iAncle1JRDehN7QhPUe7lw}{node_t1}{127.0.0.1}{127.0.0.1:21762}{cdfhilmrstw}] master = {node_t2}{0nLB5i_oQa2aUBkWUkBcNg}{qKYfVCiEQduqqEFRX3geMA}{node_t2}{127.0.0.1}{127.0.0.1:21761}{cdfhilmrstw}
	at __randomizedtesting.SeedInfo.seed([BA02796B06E5F0E9]:0)
	at org.elasticsearch.cluster.coordination.Reconfigurator.reconfigure(Reconfigurator.java:91)
	at org.elasticsearch.cluster.coordination.Coordinator.improveConfiguration(Coordinator.java:1243)
	at org.elasticsearch.cluster.coordination.Coordinator.scheduleReconfigurationIfNeeded(Coordinator.java:1296)
	at org.elasticsearch.cluster.coordination.Coordinator$CoordinatorPublication$4$1.onResponse(Coordinator.java:1857)
	at org.elasticsearch.cluster.coordination.Coordinator$CoordinatorPublication$4$1.onResponse(Coordinator.java:1797)
	at org.elasticsearch.cluster.service.ClusterApplierService$ClusterApplyActionListener.onResponse(ClusterApplierService.java:595)
	at org.elasticsearch.cluster.service.ClusterApplierService$ClusterApplyActionListener.onResponse(ClusterApplierService.java:566)
	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:438)
	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:154)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:850)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:257)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:223)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

So this is a duplicate of https://github.com/elastic/elasticsearch/issues/90591 which is already fixed.

**Closed by kingherc** 2023-01-13 14:04 UTC
Labels: >test-failure, :Distributed/Cluster Coordination, Team:Distributed
