### ISSUE TITLE
MlDistributedFailureIT.testStopAndForceStopDatafeed failed on 7.x

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#53425] opened 2020-03-11 18:04 UTC
A single failure for the last 3 months.

Log : https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_RUNTIME_JAVA=zulu11,nodes=general-purpose/564/console
Build Scans: https://gradle-enterprise.elastic.co/s/sxg6prs53mkak

REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:internalClusterTest' --tests "org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.testStopAndForceStopDatafeed" \
  -Dtests.seed=C4F2876331FA3081 \
  -Dtests.security.manager=true \
  -Dtests.locale=de-AT \
  -Dtests.timezone=JST \
  -Dcompiler.java=13

Doesn't reproduce for me

```
expected:<opened> but was:<opening>
java.lang.AssertionError: expected:<opened> but was:<opening>
at __randomizedtesting.SeedInfo.seed([C4F2876331FA3081:9AEC2EB660A09E50]:0)
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:118)
at org.junit.Assert.assertEquals(Assert.java:144)
at org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.lambda$setupJobAndDatafeed$14(MlDistributedFailureIT.java:439)
```

**Comment by benwtrent** [comment] 2020-12-02 21:01
Looking at the suppressed errors 
```
java.lang.AssertionError: expected:<opened> but was:<opening>
	at __randomizedtesting.SeedInfo.seed([C4F2876331FA3081:9AEC2EB660A09E50]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.lambda$setupJobAndDatafeed$14(MlDistributedFailureIT.java:439)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:906)
	at org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.setupJobAndDatafeed(MlDistributedFailureIT.java:436)
	at org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.testStopAndForceStopDatafeed(MlDistributedFailureIT.java:327)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: java.lang.AssertionError: expected:<opened> but was:<closed>
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.failNotEquals(Assert.java:834)
		at org.junit.Assert.assertEquals(Assert.java:118)
		at org.junit.Assert.assertEquals(Assert.java:144)
		at org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.lambda$setupJobAndDatafeed$14(MlDistributedFailureIT.java:439)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:894)
		... 38 more
	Suppressed: java.lang.AssertionError: expected:<opened> but was:<closed>
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.failNotEquals(Assert.java:834)
		at org.junit.Assert.assertEquals(Assert.java:118)
		at org.junit.Assert.assertEquals(Assert.java:144)
		at org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.lambda$setupJobAndDatafeed$14(MlDistributedFailureIT.java:439)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:894)
		... 38 more
	Suppressed: java.lang.AssertionError: expected:<opened> but was:<closed>
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.failNotEquals(Assert.java:834)
		at org.junit.Assert.assertEquals(Assert.java:118)
		at org.junit.Assert.assertEquals(Assert.java:144)
		at org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.lambda$setupJobAndDatafeed$14(MlDistributedFailureIT.java:439)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:894)
		... 38 more
	Suppressed: java.lang.AssertionError: expected:<opened> but was:<closed>
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.failNotEquals(Assert.java:834)
		at org.junit.Assert.assertEquals(Assert.java:118)
		at org.junit.Assert.assertEquals(Assert.java:144)
		at org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.lambda$setupJobAndDatafeed$14(MlDistributedFailureIT.java:439)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:894)
		... 38 more
	Suppressed: java.lang.AssertionError: expected:<opened> but was:<closed>
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.failNotEquals(Assert.java:834)
		at org.junit.Assert.assertEquals(Assert.java:118)
		at org.junit.Assert.assertEquals(Assert.java:144)
		at org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.lambda$setupJobAndDatafeed$14(MlDistributedFailureIT.java:439)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:894)
		... 38 more
	Suppressed: java.lang.AssertionError: expected:<opened> but was:<closed>
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.failNotEquals(Assert.java:834)
		at org.junit.Assert.assertEquals(Assert.java:118)
		at org.junit.Assert.assertEquals(Assert.java:144)
		at org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.lambda$setupJobAndDatafeed$14(MlDistributedFailureIT.java:439)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:894)
		... 38 more
	Suppressed: java.lang.AssertionError: expected:<opened> but was:<closed>
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.failNotEquals(Assert.java:834)
		at org.junit.Assert.assertEquals(Assert.java:118)
		at org.junit.Assert.assertEquals(Assert.java:144)
		at org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.lambda$setupJobAndDatafeed$14(MlDistributedFailureIT.java:439)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:894)
		... 38 more
	Suppressed: java.lang.AssertionError: expected:<opened> but was:<closed>
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.failNotEquals(Assert.java:834)
		at org.junit.Assert.assertEquals(Assert.java:118)
		at org.junit.Assert.assertEquals(Assert.java:144)
		at org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.lambda$setupJobAndDatafeed$14(MlDistributedFailureIT.java:439)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:894)
		... 38 more
	Suppressed: java.lang.AssertionError: expected:<opened> but was:<closed>
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.failNotEquals(Assert.java:834)
		at org.junit.Assert.assertEquals(Assert.java:118)
		at org.junit.Assert.assertEquals(Assert.java:144)
		at org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.lambda$setupJobAndDatafeed$14(MlDistributedFailureIT.java:439)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:894)
		... 38 more
	Suppressed: java.lang.AssertionError: expected:<opened> but was:<closed>
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.failNotEquals(Assert.java:834)
		at org.junit.Assert.assertEquals(Assert.java:118)
		at org.junit.Assert.assertEquals(Assert.java:144)
		at org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.lambda$setupJobAndDatafeed$14(MlDistributedFailureIT.java:439)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:894)
		... 38 more
	Suppressed: java.lang.AssertionError: expected:<opened> but was:<closed>
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.failNotEquals(Assert.java:834)
		at org.junit.Assert.assertEquals(Assert.java:118)
		at org.junit.Assert.assertEquals(Assert.java:144)
		at org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.lambda$setupJobAndDatafeed$14(MlDistributedFailureIT.java:439)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:894)
		... 38 more
	Suppressed: java.lang.AssertionError: expected:<opened> but was:<closed>
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.failNotEquals(Assert.java:834)
		at org.junit.Assert.assertEquals(Assert.java:118)
		at org.junit.Assert.assertEquals(Assert.java:144)
		at org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.lambda$setupJobAndDatafeed$14(MlDistributedFailureIT.java:439)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:894)
		... 38 more
	Suppressed: java.lang.AssertionError: expected:<opened> but was:<closed>
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.failNotEquals(Assert.java:834)
		at org.junit.Assert.assertEquals(Assert.java:118)
		at org.junit.Assert.assertEquals(Assert.java:144)
		at org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.lambda$setupJobAndDatafeed$14(MlDistributedFailureIT.java:439)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:894)
		... 38 more
	Suppressed: java.lang.AssertionError: expected:<opened> but was:<opening>
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.failNotEquals(Assert.java:834)
		at org.junit.Assert.assertEquals(Assert.java:118)
		at org.junit.Assert.assertEquals(Assert.java:144)
		at org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.lambda$setupJobAndDatafeed$14(MlDistributedFailureIT.java:439)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:894)
		... 38 more
```

It seems that these two failures 8 months ago were caused by CI slowness. The job was indeed opening (successfully went from closed to opening). 

Closing this issue. If these tests continue to fail in this manner again, we can attempt to up the timeout.

**Closed by benwtrent** 2020-12-02 21:01 UTC
Labels: :ml, >test-failure
