### ISSUE TITLE
mapper-attachments - copy_to doesn't work

### ISSUE THREAD

**Issue by chindhuhari** [elastic/elasticsearch#20774] opened 2016-10-06 08:55 UTC
**Elasticsearch version**: 2.3.2

**Plugins installed**: [mapper-attachments]

**JVM version**: 1.8

**OS version**: Windows

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
Similar to https://github.com/elastic/elasticsearch-mapper-attachments/issues/216 and https://github.com/elastic/elasticsearch/issues/14946
We couldn't find as to in which version this was fixed.
If there is a document or references available, please do help us with the links leading to it

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by SKumarMN** [comment] 2016-10-06 08:58
I am facing the same issue too. Can you please let know if there is a fix if so in which version or this feature(copy_to in subfields) is not supported at all

**Comment by dadoonet** [comment] 2016-10-06 09:45
Duplicate of #18361.

**Closed by dadoonet** 2016-10-06 09:45 UTC
