### ISSUE TITLE
Maybe memory leak in search.SearchService

### ISSUE THREAD

**Issue by arielzach** [elastic/elasticsearch#64427] opened 2020-10-30 16:43 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 7.8 and 7.9.2

**Plugins installed**: []

**JVM version** (`java -version`): 14.0.1

**OS version** (`uname -a` if on a Unix-like system): 4.14.186-110.268.amzn1.x86_64 #1 SMP Tue Jul 14 02:57:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux (docker.elastic.co/elasticsearch/elasticsearch:7.8.0)

**Description of the problem including expected versus actual behavior**:
I return to this problem that we are having, in this [issue](https://github.com/elastic/elasticsearch/issues/64028) that I opened a few days ago I detailed the same problem that we are having now, in that issue you recommended us to close the contexts that we left open, we made those changes but the problem persists. 

It should be clarified that the same code (closing or not the contexts) works perfectly in ES 6.8.

Continuously growing memory usage eventually leading to periodically FullGC result in Cluster not available. All nodes have 64G physical memory，32G JVM Heap, 8 cores, 1 index, 32 shards, 2 replicas.

The problem is similar to the one presented here: https://github.com/elastic/elasticsearch/issues/57400

Previously we had a 6.8 cluster with exactly the same configuration (hardware and ES config) and we did not have this problem.

I just dump the heap and analysis the heap with MAT

![image](https://user-images.githubusercontent.com/64101789/96801000-0820ce80-13dd-11eb-81b0-ea10ea1b8e72.png)
![image](https://user-images.githubusercontent.com/64101789/96801050-238bd980-13dd-11eb-8427-d03b09cd71ca.png)
![image](https://user-images.githubusercontent.com/64101789/96801070-2dadd800-13dd-11eb-9688-10170bb431f0.png)
![image](https://user-images.githubusercontent.com/64101789/96801083-37cfd680-13dd-11eb-8568-b90870820407.png)
![image](https://user-images.githubusercontent.com/64101789/96801176-677ede80-13dd-11eb-9e90-fea925d0560d.png)

**Comment by arielzach** [comment] 2020-11-06 14:47
We set search.max_open_scroll_context to 150 and so far it's working fine. Is it correct that we have to adjust the number of contexts to prevent nodes from failing?

**Comment by arielzach** [comment] 2020-11-09 18:18
After a few days working well, the cluster fell again, at the time of the fall, it did not reach the 140 open contexts.

**Comment by jimczi** [comment] 2020-11-09 20:02
Can you clarify what you mean by "fell again" ? You mentioned Full GC but no OutOfMemoryException so can you share the memory usage of the node before and after the full GC ?  Are you overriding any Java options in your configuration ? 
What version of Java are you using to run Elasticsearch `6.8` ?  Java 14 defaults to G1 GC so if you switched to this version in `7.x` the behavior may have changed.

**Comment by arielzach** [comment] 2020-11-09 20:54
"fell again" = We have ES running in docker, sometimes the containers stop and are restarted but other times they just disappear from the cluster for a few minutes.

Are you overriding any Java options in your configuration?: No
What version of Java are you using to run Elasticsearch 6.8?: 13 (docker.elastic.co/elasticsearch/elasticsearch:6.8.4) 

As seen in the graph, there is a peak in the heap at 0 o'clock:
![image](https://user-images.githubusercontent.com/64101789/98592698-dbabf400-22b0-11eb-9ada-ea25a906a61b.png)

GC graphics:
![image](https://user-images.githubusercontent.com/64101789/98593106-71e01a00-22b1-11eb-8d56-8fad2eeadd40.png)
![image](https://user-images.githubusercontent.com/64101789/98593133-7a385500-22b1-11eb-9d6b-a19574078c5d.png)
![image](https://user-images.githubusercontent.com/64101789/98593156-83c1bd00-22b1-11eb-8234-391f1e692d96.png)
![image](https://user-images.githubusercontent.com/64101789/98593182-8d4b2500-22b1-11eb-8313-ece8abf1e8d9.png)

**Comment by arielzach** [comment] 2020-11-20 20:03
The same problem just happened to us with ES 6.8:

![image](https://user-images.githubusercontent.com/64101789/99844573-0cfaae80-2b52-11eb-8f28-bf99960644c1.png)
![image](https://user-images.githubusercontent.com/64101789/99844598-15eb8000-2b52-11eb-8697-885cf2889007.png)

**Comment by arielzach** [comment] 2020-12-01 22:57
What can be the cause of this?

![image](https://user-images.githubusercontent.com/64101789/100806476-49aa8d80-340f-11eb-910e-3be299719540.png)

![image](https://user-images.githubusercontent.com/64101789/100806561-6e066a00-340f-11eb-92d4-3c605ddd817c.png)

**Comment by jimczi** [comment] 2020-12-01 23:26
What can be the cause of this?

Very large shards that are scrolled or queried concurrently while updates/deletes are applied on the index.
Do you know where all these contexts are coming from ? Is it from concurrent scroll requests hitting  the same index ? 
The memory needed for an active context depends on the refresh interval of the index. So if you refresh too often (every second by default), any new scroll will work on a different reader.

**Comment by arielzach** [comment] 2020-12-04 14:18
Hi @jimczi , we increased the refresh_interval to 4s and the problem still persists.

**Comment by jimczi** [comment] 2020-12-18 11:38
Github is not the best place for investigating a problem in Elasticsearch. We reserve it for verified bugs and feature requests so I hope you don't mind if I close this issue. I'll be glad to continue the investigation in the [discuss forum](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6) and we can reopen this issue if we find a real bug in the meantime. So please provide the informations asked in https://github.com/elastic/elasticsearch/issues/64427#issuecomment-736885788 in a new post on the forum.

**Closed by jimczi** 2020-12-18 11:38 UTC
Labels: :Search/Search, >bug, Team:Search
