### ISSUE TITLE
SearchWithRandomIOExceptionsIT.testRandomDirectoryIOExceptions failure on 7.x

### ISSUE THREAD

**Issue by gwbrown** [elastic/elasticsearch#39591] opened 2019-03-01 21:53 UTC
CI link: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+intake/378/console

Reproduce line, does not reproduce locally:
```
./gradlew :server:integTest \
  -Dtests.seed=48F6B3A3D86AF908 \
  -Dtests.class=org.elasticsearch.search.basic.SearchWithRandomIOExceptionsIT \
  -Dtests.method="testRandomDirectoryIOExceptions" \
  -Dtests.security.manager=true \
  -Dtests.locale=sl-SI \
  -Dtests.timezone=America/Asuncion \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

Stack trace:
```
java.lang.AssertionError: search result contains [0] results. expected [1]
	at __randomizedtesting.SeedInfo.seed([48F6B3A3D86AF908:10ADF8BC62C12A9]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.elasticsearch.test.ESIntegTestCase.assertResultsAndLogOnFailure(ESIntegTestCase.java:891)
	at org.elasticsearch.search.basic.SearchWithRandomIOExceptionsIT.testRandomDirectoryIOExceptions(SearchWithRandomIOExceptionsIT.java:174)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
```

Build logs: 
[consoleText.txt](https://github.com/elastic/elasticsearch/files/2921151/consoleText.txt)

Not muting this yet, as it's only failed once with this error and isn't reproducible.

**Comment by davidkyle** [comment] 2019-08-21 15:53
Another on 7.x. There has been a handful of failures since this issue was opened. 

```
java.lang.AssertionError: search result contains [1] results. expected [0]
	at __randomizedtesting.SeedInfo.seed([E95A6A4FD1B3C2F6:A0A60667CFF52957]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.elasticsearch.test.ESIntegTestCase.assertResultsAndLogOnFailure(ESIntegTestCase.java:837)
	at org.elasticsearch.search.basic.SearchWithRandomIOExceptionsIT.testRandomDirectoryIOExceptions(SearchWithRandomIOExceptionsIT.java:174)
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=oraclelinux-7&&immutable/215/console
https://gradle-enterprise.elastic.co/s/dznp7p5rpnck4

**Comment by droberts195** [comment] 2020-03-23 17:20
This one popped up again today on 7.x with the exact same error.

```
search result contains [1] results. expected [0]
java.lang.AssertionError: search result contains [1] results. expected [0]
	at __randomizedtesting.SeedInfo.seed([D77E6A1B6E73DB37:9E82063370353096]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.elasticsearch.test.ESIntegTestCase.assertResultsAndLogOnFailure(ESIntegTestCase.java:846)
	at org.elasticsearch.search.basic.SearchWithRandomIOExceptionsIT.testRandomDirectoryIOExceptions(SearchWithRandomIOExceptionsIT.java:174)
```

The Gradle scan is https://gradle-enterprise.elastic.co/s/7acoafg32bxvu

**Comment by dimitris-athanasiou** [comment] 2020-06-29 11:29
We also hit another.

Build scan: https://gradle-enterprise.elastic.co/s/csil3c4dll3ze

Log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob+fast+part1/565/console

This one hit a different assertion in that test. It seems something went wrong while trying to delete indices during cleanup:

```
java.lang.AssertionError: AcknowledgedResponse failed - not acked	
Expected: <true>	
     but: was <false>	
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)	
at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked(ElasticsearchAssertions.java:115)	
at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked(ElasticsearchAssertions.java:119)	
at org.elasticsearch.test.TestCluster.wipeIndices(TestCluster.java:160)	
at org.elasticsearch.test.TestCluster.wipe(TestCluster.java:84)	
at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:594)	
at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2214)
```

An exception can be seen:

```

jun 29, 2020 10:22:10 AM com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException |  
-- | --
  | ADVERTENCIA: Uncaught exception in thread: Thread[elasticsearch[node_s1][clusterApplierService#updateTask][T#1],5,TGRP-SearchWithRandomIOExceptionsIT] |  
  | java.lang.AssertionError: Index commit [CommitPoint{segment[segments_2], userData[{history_uuid=PpWWUbxPScmbVSUaGCBbrg, local_checkpoint=-1, max_seq_no=-1, max_unsafe_auto_id_timestamp=-1, translog_uuid=bFKKxodIRNWucAzOPh75GQ}]}] is deleted twice |  
  | at __randomizedtesting.SeedInfo.seed([D6E404A5E09FA15C]:0) |  
  | at org.elasticsearch.index.engine.CombinedDeletionPolicy.deleteCommit(CombinedDeletionPolicy.java:114) |  
  | at org.elasticsearch.index.engine.CombinedDeletionPolicy.onCommit(CombinedDeletionPolicy.java:89) |  
  | at org.apache.lucene.index.IndexFileDeleter.checkpoint(IndexFileDeleter.java:524) |  
  | at org.apache.lucene.index.IndexWriter.finishCommit(IndexWriter.java:3509) |  
  | at org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:3465) |  
  | at org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:3415) |  
  | at org.elasticsearch.index.engine.InternalEngine.commitIndexWriter(InternalEngine.java:2449) |  
  | at org.elasticsearch.index.engine.InternalEngine.flush(InternalEngine.java:1784) |  
  | at org.elasticsearch.index.engine.Engine.flush(Engine.java:1054) |  
  | at org.elasticsearch.index.engine.Engine.flushAndClose(Engine.java:1683) |  
  | at org.elasticsearch.test.engine.MockInternalEngine.flushAndCloseInternal(MockInternalEngine.java:73) |  
  | at org.elasticsearch.test.engine.MockInternalEngine.close(MockInternalEngine.java:51) |  
  | at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:106) |  
  | at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:64) |  
  | at org.elasticsearch.index.shard.IndexShard.close(IndexShard.java:1357) |  
  | at org.elasticsearch.index.IndexService.closeShard(IndexService.java:524) |  
  | at org.elasticsearch.index.IndexService.removeShard(IndexService.java:507) |  
  | at org.elasticsearch.index.IndexService.close(IndexService.java:322) |  
  | at org.elasticsearch.indices.IndicesService.removeIndex(IndicesService.java:797) |  
  | at org.elasticsearch.indices.cluster.IndicesClusterStateService.deleteIndices(IndicesClusterStateService.java:302) |  
  | at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:236) |  
  | at org.elasticsearch.cluster.service.ClusterApplierService.lambda$callClusterStateAppliers$5(ClusterApplierService.java:522) |  
  | at java.lang.Iterable.forEach(Iterable.java:75) |  
  | at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:519) |  
  | at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:490) |  
  | at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:437) |  
  | at org.elasticsearch.cluster.service.ClusterApplierService.access$100(ClusterApplierService.java:74) |  
  | at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:177) |  
  | at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:651) |  
  | at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) |  
  | at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) |  
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) |  
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) |  
  | at java.lang.Thread.run(Thread.java:748)


```

**Comment by danielmitterdorfer** [comment] 2020-07-09 06:03
We hit the same issue as the one identified by @dimitris-athanasiou again:

* [build scan](https://gradle-enterprise.elastic.co/s/todaxth2do53o)
* [build](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_RUNTIME_JAVA=zulu11,nodes=general-purpose/87/console)

```
java.lang.AssertionError: AcknowledgedResponse failed - not acked
Expected: <true>
     but: was <false>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked(ElasticsearchAssertions.java:115)
	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked(ElasticsearchAssertions.java:119)
	at org.elasticsearch.test.TestCluster.wipeIndices(TestCluster.java:160)
	at org.elasticsearch.test.TestCluster.wipe(TestCluster.java:84)
	at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:594)
	at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2233)
```

```
java.lang.AssertionError: Index commit [CommitPoint{segment[segments_3], userData[{history_uuid=jCov8UF5TcuK9Wp0jDVvNw, local_checkpoint=-1, max_seq_no=-1, max_unsafe_auto_id_timestamp=-1, translog_uuid=daCIdKSyQ36eplN_M_MZrw}]}] is deleted twice
	at __randomizedtesting.SeedInfo.seed([8C881BBCF21FE4E8]:0)
	at org.elasticsearch.index.engine.CombinedDeletionPolicy.deleteCommit(CombinedDeletionPolicy.java:114)
	at org.elasticsearch.index.engine.CombinedDeletionPolicy.onCommit(CombinedDeletionPolicy.java:89)
	at org.apache.lucene.index.IndexFileDeleter.checkpoint(IndexFileDeleter.java:524)
	at org.apache.lucene.index.IndexWriter.finishCommit(IndexWriter.java:3649)
	at org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:3605)
	at org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:3555)
	at org.elasticsearch.index.engine.InternalEngine.commitIndexWriter(InternalEngine.java:2449)
	at org.elasticsearch.index.engine.InternalEngine.flush(InternalEngine.java:1784)
	at org.elasticsearch.index.engine.Engine.flush(Engine.java:1054)
	at org.elasticsearch.index.engine.Engine.flushAndClose(Engine.java:1683)
	at org.elasticsearch.test.engine.MockInternalEngine.flushAndCloseInternal(MockInternalEngine.java:73)
	at org.elasticsearch.test.engine.MockInternalEngine.close(MockInternalEngine.java:51)
	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:106)
	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:64)
	at org.elasticsearch.index.shard.IndexShard.close(IndexShard.java:1359)
	at org.elasticsearch.index.IndexService.closeShard(IndexService.java:524)
	at org.elasticsearch.index.IndexService.removeShard(IndexService.java:507)
	at org.elasticsearch.index.IndexService.close(IndexService.java:322)
	at org.elasticsearch.indices.IndicesService.removeIndex(IndicesService.java:797)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.deleteIndices(IndicesClusterStateService.java:302)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:236)
	at org.elasticsearch.cluster.service.ClusterApplierService.lambda$callClusterStateAppliers$5(ClusterApplierService.java:522)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:519)
	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:490)
	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:437)
	at org.elasticsearch.cluster.service.ClusterApplierService.access$100(ClusterApplierService.java:74)
	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:177)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:651)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

To me this seems like a different issue though as it is about an error that happens while the index is being deleted.

**Comment by original-brownbear** [comment] 2021-02-01 15:00
This happened to me today in https://gradle-enterprise.elastic.co/s/7qhdsy72qgcni

It's actually fairly easy to reproduce via `./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.search.basic.SearchWithRandomIOExceptionsIT.testRandomDirectoryIOExceptions" -Dtests.seed=5F14A87714CB0D2C -Dtests.security.manager=true -Dtests.locale=de-LU -Dtests.timezone=America/Argentina/ComodRivadavia -Druntime.java=11` on current master. Most of the runs are just absurdly slow but after a few tens of iterations the above failure shows up reliably for me locally.

**Comment by dnhatn** [comment] 2021-05-31 17:50
Fixed in LUCENE-9980.

**Closed** 2021-05-31 17:49 UTC
Labels: :Search/Search, >test-failure, Team:Search
