### ISSUE TITLE
Failed to derive xcontent from org.elasticsearch.common.bytes.ChannelBufferBytesReference

### ISSUE THREAD

**Issue by jlecour** [elastic/elasticsearch#8595] opened 2014-11-21 17:08 UTC
Hi,

I've recently upgraded to `1.4.0` and I have some transient errors, like this one : 

```
ElasticsearchParseException[Failed to derive xcontent from org.elasticsearch.common.bytes.ChannelBufferBytesReference@143d90f]
```

It's very strange since it happens on various indices. Some of them are very stable (a handful of update each day), some of them are very volatile (thousands of concurrent read/writes during the day, then left alone).

I can't reproduce those errors. I can't pinpoint any specific query.
I've been logging a lot and each time a query raise this error, I re-execute it and it runs well.

I've not tried to downgrade to `1.3.x` yet. Maybe I will.

I've been raking my brain for many days, with quite some frustration hence this evasive bug report.

If anyone has the beginning of an idea, I'd be happy to try and give as much information as I can.

**Comment by epackorigan** [comment] 2015-01-14 06:21
i was seeing this earlier today with a slightly malformed JSON block (trying to setup some transient settings). In my case, i had extra spaces at the beginning, before the opening bracket.

this worked:
curl -XPUT localhost:9200/_cluster/settings -d '{
    "transient" : {
        "cluster.routing.allocation.disk.threshold_enabled" : false
    }
}'

this didn't (note the extra space on the beginning of the line containing "transient")
curl -XPUT localhost:9200/_cluster/settings -d '
 { "transient" : {
        "cluster.routing.allocation.disk.threshold_enabled" : false
    }
}'

**Comment by clintongormley** [comment] 2015-01-15 20:03
@epackorigan Can you recreate this?

i tried setting up two nodes and running your malfunctionting request, and all worked as expected.

**Comment by epackorigan** [comment] 2015-01-17 06:27
I will try to reproduce on Monday and reconfirm.

**Comment by epackorigan** [comment] 2015-01-22 00:19
not quite monday, but here is what i have:

I was trying to migrate data off one node, so i can service it (add ram to it).
i tried the following:
'''
curl --silent -XPUT localhost:9200/_cluster/settings -s '{
  "transient" : {
    "cluster.routing.allocation.exclude._ip" : "10.0.0.1"
  }
}'
'''
note: there are two spaces in front of transient, and 4 in front of cluster. i received the following error:
  "error" : "ElasticsearchParseException[Failed to derive xcontent from org.elasticsearch.common.bytes.BytesArray@1]",

more variations on the spacing, or formatting of the submitted data, pretty much always yielded that same error:
'''
curl --silent -XPUT localhost:9200/_cluster/settings?pretty -s '{ "transient" : { "cluster.routing.allocation.exclude._ip" : "10.0.0.1" } }'
{
  "error" : "ElasticsearchParseException[Failed to derive xcontent from org.elasticsearch.common.bytes.BytesArray@1]",
  "status" : 400
}
'''
until i had exactly 4/8 spaces:
'''
curl -XPUT localhost:9200/_cluster/settings -d '{
    "transient" : {
        "cluster.routing.allocation.exclude._ip" : "10.0.0.1"
    }
}'
{"acknowledged":true,"persistent":{},"transient":{"cluster":{"routing":{"allocation":{"exclude":{"_ip":"10.0.0.1"}}}}}}
'''

it could be that the parser there is very picky about the format of the JSON data (i'm not even sure if that's valid JSON or not).

Note: I'm running on Debian Wheezy, with OpenJDK-1.7, ES 1.4.2 (all installed from packages)

**Comment by clintongormley** [comment] 2015-01-22 13:57
@epackorigan The formatting of your JSON is just fine.  It's your use of parameters which is flakey ;)

Your version which doesn't work:

    curl -XPUT localhost:9200/_cluster/settings -s '{

Your version which **does** work:

    curl -XPUT localhost:9200/_cluster/settings -d '{

With the first version, you're not passing a body at all, which is why it is failing with Failed to derive xcontent from org.elasticsearch.common.bytes.BytesArray@1

**Comment by epackorigan** [comment] 2015-01-22 17:26
<facepalm>Doh! sorry for the noise!</facepalm>

**Comment by mausch** [comment] 2015-02-24 17:45
I just got this error from copying and pasting a request from somewhere into Marvel/Sense, which left me with a space after the request path. I googled the error and this was the first result, which was a good thing because I could fix it right away, but perhaps a "less scary" error might help other users (I imagine this must be a quite common mistake).

**Comment by bleskes** [comment] 2015-02-24 17:51
@mausch that's annoying. FYI We have this noted for Sense and we'll fix it to trim the request properly (putting aside the question of a better error message

**Comment by bleskes** [comment] 2015-03-05 20:46
@mausch FYI - the trailing space issue is fixed in marvel 1.3.1 , released today.

**Comment by clintongormley** [comment] 2015-04-26 19:44
No more info on this ticket. Closing. Feel free to reopen if you're still seeing this

**Closed by clintongormley** 2015-04-26 19:44 UTC
Labels: bug, feedback_needed

**Comment by GamingCoder** [comment] 2015-07-29 15:47
I saw this error in the ES JavaSCript client and documented the problem at https://github.com/elastic/elasticsearch-js/issues/245

**Comment by bamarni** [comment] 2016-01-27 10:24
I'm getting the same error with version `1.7.4` and the official php client.

It is with the bulk api too, even though I get this error it looks like everything worked normally, very similar to what @jlecour reported.

**Comment by ulkas** [comment] 2016-03-08 09:37
@bamarni 
the same at me, also en empty body in the batch json

**Comment by serg3ant** [comment] 2017-04-25 10:18
It seem to happen when bulk is empty

**Comment by gdubicki** [comment] 2017-09-22 08:52
Can you please reopen and change the error message?

Passing empty data to ES API seems to be a pretty common mistake...

(especially as `curl` makes is it easy to make this mistake - btw: I am switching to https://github.com/jakubroztocil/httpie to hitting such issues in the future)

**Comment by javanna** [comment] 2017-09-25 15:58
@gdubicki the error messages were improved for all the relevant APIs with #23497 (went out with 5.5).
