### ISSUE TITLE
No highlighting for phrases with stop words when term vector with positions offsets is enabled

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#2157] opened 2012-08-09 14:50 UTC
If a record contains a phrase with stop words in the middle  (`foo and bar`, for example) and the search expression contains a matching phrase, highlighter produces different results that depend on how the field was indexed. 
- If the field was indexed with `"term_vector": "with_positions_offsets"` elasticsearch doesn't highlight anything
- if the field was indexed with `"term_vector": "with_positions_offsets"` and the field's analyzer has `"enable_position_increments": false`, elasticsearch highlights the entire phrase: `foo and bar`. 
- if the field was indexed without "term_vector" enabled elasticsearch highlights words `foo` and `bar` separately.

Full repro can be found here: https://gist.github.com/3280061

Solr seems to be behaving the same way: see https://gist.github.com/3279879#file_response_fvh.txt  and [SOLR-3724](https://issues.apache.org/jira/browse/SOLR-3724)

A possible workaround for us would be to add a flag on the highlighter query and globally that would disable fast vector highlighter. FVH is relatively new portion of lucene and this is already the second time when I wish I had a way to temporarily disable it without reindexing my data. (The first time was [LUCENE-3719](https://issues.apache.org/jira/browse/LUCENE-3719).) I could submit a pull request if you think that would be a useful feature.

**Comment by ajhalani** [comment] 2015-09-02 21:31
Any chance there has been any update on this?? The default "english" analyzer exposed this issue so easily.

**Comment by aih** [comment] 2015-09-13 07:30
+1 I need to use the fvh filter to combine the highlights from searching two fields (one using the English analyzer and one using whitespace, to capture exact matches). However, highlighting fails for phrases with stopwords.

**Comment by nik9000** [comment] 2015-09-13 11:36
Give the [experimental highlighter](https://github.com/wikimedia/search-highlighter) a shot. It works reasonably well as a replacement for the fvh and _should_ support this though I don't remember testing it explicitly. It [looks](https://en.wikipedia.org/w/index.php?search=to+be+or+not+to+be&title=Special%3ASearch&go=Go&fulltext=1) like this works, though it might be working because of the more whitespace like analyzer in use over there in addition to the english one.

I believe I'll be working a ton more on highlighters in the coming months and I'll make sure this is on the list of things we fix.

**Comment by aih** [comment] 2015-09-14 06:25
Thank you, @nik9000! I tried the experimental highlighter and it had the same behavior as fvh (ignoring stopwords in phrase searches, and therefore missing matches where the stopword is in the middle-- e.g. "motion to adjourn"). I also noticed that the experimental highlighter doesn't support whole-field fragments (number_of_fragments = 0).
**However**, your comment solved my problem. Indeed, it looks like the Wikipedia search matches phrases because it uses a whitespace-like analyzer. So, I took out the stopwords from my English analyzer, reindexed, and now I've got phrase highlighting with stopwords. Would still be nice to have the option to match stopwords with the highlighter only, but this works for now.

**Comment by clintongormley** [comment] 2016-11-06 09:22
Updated for 5.0.  FVH still doesn't handle phrase queries with stop words unless slop is included:

```
PUT /test-idx
{
  "settings": {
    "index": {
      "analysis": {
        "analyzer": {
          "standard_stop": {
            "type": "standard",
            "stopwords": "_english_"
          }
        }
      }
    }
  },
  "mappings": {
    "rec": {
      "properties": {
        "message": {
          "type": "text",
          "analyzer": "standard",
          "term_vector": "with_positions_offsets",
          "fields": {
            "stop": {
              "type": "text",
              "analyzer": "standard_stop",
              "term_vector": "with_positions_offsets"
            }
          }
        }
      }
    }
  }
}

PUT /test-idx/rec/1
{
  "message": "foo and bar and something else"
}

GET /test-idx/_search
{
  "highlight": {
    "fields": {
      "message": {},
      "message.stop": {}
    }
  },
  "query": {
    "query_string": {
      "fields": ["message","message.stop"],
      "query": "\"foo and bar\""
    }
  }
}

```

FVH works when slop is enabled:

```
GET /test-idx/_search
{
  "highlight": {
    "fields": {
      "message": {},
      "message.stop": {}
    }
  },
  "query": {
    "query_string": {
      "fields": ["message","message.stop"],
      "query": "\"foo and bar\"~4"
    }
  }
}
```

**Comment by yoav2** [comment] 2016-11-10 13:12
Is there any solution for this?. highlighting is not working when I index with English Analyzer, and search for a phrase with stop words.

**Comment by clintongormley** [comment] 2016-11-10 13:45
@jimczi The FVH doesn't handle phrase matches when slop is involved - is this a bug in our implementation or in Lucene?

**Comment by yoav2** [comment] 2016-11-10 14:15
How can I make the stop words highlighted? (using English Analyzer and With_Positions_Offsets) in phrase matches query?

**Comment by jimczi** [comment] 2016-11-10 16:33
The problem is in Lucene:
https://issues.apache.org/jira/browse/LUCENE-7552 
The FVH does not handle gaps in phrase query. I'll work on this.

**Comment by dadoonet** [comment] 2016-11-10 18:07
@jimczi apparently you opened the JIRA issue twice :)
Do you think this is related to https://issues.apache.org/jira/browse/LUCENE-7541 as well?

**Comment by jimczi** [comment] 2016-11-10 20:32
Thanks @dadoonet, this is not related. This one is about gaps in phrase query and the other one is about repeated tokens in the query. The multi tagging system of the FVH is at the token level and it will not be easy to fix that.

**Comment by clintongormley** [comment] 2016-11-24 18:13
Closing in favour of #21621

**Closed by clintongormley** 2016-11-24 18:13 UTC
Labels: :Highlighting, bug
