### ISSUE TITLE
Allow more than 1024 dimensions for indexed dense_vector fields

### ISSUE THREAD

**Issue by phillipb** [elastic/elasticsearch#92593] opened 2022-12-28 23:45 UTC
### Description

I'd like to be able to configure the max number of dimensions that are allowed for indexed dense_vectors. I'm using OpenAi's embeddings (which I'm assuming will be a popular use case) and they have 1536 dimensions, but dense_vectors only support 1024. Ideally, I'd like to not lose any semantic meaning by truncating my vectors.

**Comment by benwtrent** [comment] 2023-01-03 12:57
Closing as duplicate of: https://github.com/elastic/elasticsearch/issues/92458

We don't want to accidentally spread the conversation around to multiple places.

**Closed by benwtrent** 2023-01-03 12:57 UTC
Labels: >enhancement, :Search/Search, Team:Search
