### ISSUE TITLE
Term aggregation query without filter does not provide all the records.

### ISSUE THREAD

**Issue by DeeJ29** [elastic/elasticsearch#85783] opened 2022-04-11 13:37 UTC
### Elasticsearch Version

6.8.3

### Java Version

_bundled_

### OS Version

CentOS Linux 7

### Problem Description

Term aggregation with and without filter is giving different results.
If we run term aggregation without filter, then the result has fewer records. With filter, for the same query, the results has more (correct) number of records.
However the composite aggregation query for the same query with and without filter gives same and correct number of records.

Term aggregation query:
curl -i -XGET -k 'https://elasticsearch-lb.elasticsearch.svc:9200/resourcesdb-2022.04.05/_search?pretty&size=0' -H "Content-Type:application/json" -d '{
   "query": {
      "bool": {
         "filter": [{
            "range": {
               "ts": {
                  "gte": "2022-04-06T13:35:49.000Z",
                  "lte": "2022-04-06T15:45:49.000Z",
                  "format": "date_optional_time"
               }
            }
         }],
         "must": [{
            "terms": {
               "fabricName": ["fabric1"],
               "boost": 1
            }
         },
         { "terms": {
               "nodeName": ["node64"]
            }
         },
         {
            "terms": {
               "resourceName": ["utilization:CPU"]
            }
         }]
      }
   },
   "size": 0,
   "aggs": {
      "l1_top_resources": {
         "terms": {
            "field": "nodeName",
            "size": 10
         },
         "aggs": {
            "l1_timeseries": {
               "date_histogram": {
                  "field": "ts",
                  "interval": "5m",
                  "min_doc_count": 1
               },
               "aggs": {
                  "l1_timeseries_agg": {
                     "top_hits": {
                        "size": 1,
                        "sort": [{
                           "ts": {
                              "order": "desc"
                          }
                        }],
                        "_source": {
                           "includes": ["currVal", "maxVal", "ts", "rawAnomalyScore","nodeName"]
                        }
                     }
                  }
               }
            }
         }
      }
   }
}'

with nodename filter : 25 buckets for node64
w/o nodename filter : 10 nodes are displayed and node64 has only 8 buckets

Composite aggregation query:

curl -i -XGET -k 'https://elasticsearch-lb.elasticsearch.svc:9200/resourcesdb-2022.04.05/_search?pretty&size=0' -H "Content-Type:application/json" -d '{
   "query": {
      "bool": {
         "filter": [{
            "range": {
               "ts": {
                  "gte": "2022-04-06T13:35:49.000Z",
                  "lte": "2022-04-06T15:45:49.000Z",
                  "format": "date_optional_time"
               }
            }
         }],
         "must": [{
            "terms": {
               "fabricName": ["fabric1"],
               "boost": 1
            }
         },
         { "terms": {
               "nodeName": ["node64"]
            }
         },
         {
            "terms": {
               "resourceName": ["utilization:CPU"]
            }
         }]
      }
   },
   "size": 0,
   "aggs": {
      "sourceName": {
            "composite": {
                "size": 10000,
                "sources" : [
                    {
                        "sourceName": { "terms": { "field": "nodeName" } }
                    },
                    {
                        "timeseries": { "date_histogram": { "field": "ts", "interval": "5m", "order": "asc" } }
                    }
                ]
            },
               "aggs": {
                  "l1_timeseries_agg": {
                     "top_hits": {
                        "size": 1,
                        "sort": [{
                           "ts": {
                              "order": "desc"
                          }
                        }],
                        "_source": {
                           "includes": ["currVal", "maxVal", "ts", "rawAnomalyScore","nodeName"]
                        }
                     }
                  }
               }
            }
         }
      }
   }
}'
o/p location :  /tmp/c1   /tmp/c2
 
with nodename filter for node64 : 25 buckets
w/o nodename filter : 10 nodes are displayed and node64 has 25 buckets

### Steps to Reproduce

Run the query as mentioned in problem description

**Comment by gmarouli** [comment] 2022-04-11 14:48
Hi @DeeJ29 , could you provide some sample data to run the queries against so we can reproduce it?

**Comment by DeeJ29** [comment] 2022-04-12 10:49
Hi Mary,

The issue is seen only in high scale data. You can prepare a db with more
than 20 million records and run the query.
I do not have sample data to share.

Thanks,
Divya

**Comment by gmarouli** [comment] 2022-04-13 09:02
No problem, I double checked with others and with the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-aggregations-bucket-terms-aggregation.html#search-aggregations-bucket-terms-aggregation-size) and this is expected behavior.

> the node coordinating the search process will request each shard to provide its own top size term buckets and once all shards respond, it will reduce the results to the final list that will then be returned to the client. This means that if the number of unique terms is greater than size, the returned list is slightly off and not accurate (it could be that the term counts are slightly off and it could even be that a term that should have been in the top size buckets was not returned).

Therefore when you look for the `node64` you see the following two cases:
- When there is no query, it might happen that bucket `node64` does not make it to the top 10 buckets in most of the shards and therefore it reports an underestimated document count. 
- When adding the filter, bucket `node64` makes it to most of the top 10 buckets and therefore provides a more accurate count,  higher than the one without filter.

I hope this was helpful. Let me know if you have any further questions, if not, will proceed with closing the issue.

**Comment by gmarouli** [comment] 2022-06-13 09:01
Since there hasn't been any reaction to this issue, I will close the issue.

**Closed by gmarouli** 2022-06-13 09:01 UTC
Labels: >non-issue, :Analytics/Aggregations, Team:Analytics
