### ISSUE TITLE
Unable to view segment file sizes stats

### ISSUE THREAD

**Issue by spiegela** [elastic/elasticsearch#21878] opened 2016-11-30 03:57 UTC
I'm unable to pull the segment file sizes using the `/_stats` endpoint as documented [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html). Here's an example of the failing API call:

```
$ curl -v "http://127.0.0.1:9200/_stats/segments?include_segment_file_sizes&pretty=true"
* About to connect() to 127.0.0.1 port 9200 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 9200 (#0)
> GET /_stats/segments?include_segment_file_sizes&pretty=true HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:9200
> Accept: */*
> 
< HTTP/1.1 400 Bad Request
< content-type: application/json; charset=UTF-8
< content-length: 390
<
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "request [/_stats/segments] contains unrecognized parameter: [include_segment_file_sizes]"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "request [/_stats/segments] contains unrecognized parameter: [include_segment_file_sizes]"
  },
  "status" : 400
}
* Connection #0 to host 127.0.0.1 left intact
```

I've found the issue in the REST API handler, and will be submitting a PR to resolve shortly.

**Comment by martijnvg** [comment] 2018-03-21 08:30
@spiegela Apologies for leaving this bug report unattended. Currently the request that you were making is working as expected. I will close this issue, since it has been reported a long time and many things have changed in the meantime. Feel free to open another issue if you still manage to reproduce this error on a recent ES version.

**Closed by martijnvg** 2018-03-21 08:30 UTC
Labels: :Core/Stats, >bug

**Comment by spiegela** [comment] 2018-04-05 14:40
@martijnvg no worries. PR #21879 was merged, and resolved this bug. I think this was only outstanding as a housekeeping issue. I just checked against `6.5` and it still appears to be working 😄
