### ISSUE TITLE
Marvel is trying to query closed indices

### ISSUE THREAD

**Issue by bradvido** [elastic/elasticsearch#11092] opened 2015-05-11 14:26 UTC
I'm using Marvel 1.3.1 running on an ES 1.5.2 cluster.

My ES logs are seeing this every 30 seconds or so:

```
[2015-05-11 09:16:52,990][ERROR][marvel.agent             ] [dev-es1] error while collecting indices stats
org.elasticsearch.indices.IndexClosedException: [logstash-2015.03.27] closed
	at org.elasticsearch.cluster.metadata.MetaData.concreteIndices(MetaData.java:790)
	at org.elasticsearch.cluster.metadata.MetaData.concreteIndices(MetaData.java:723)
	at org.elasticsearch.action.support.broadcast.TransportBroadcastOperationAction$AsyncBroadcastAction.<init>(TransportBroadcastOperationAction.java:120)
	at org.elasticsearch.action.support.broadcast.TransportBroadcastOperationAction.doExecute(TransportBroadcastOperationAction.java:71)
	at org.elasticsearch.action.support.broadcast.TransportBroadcastOperationAction.doExecute(TransportBroadcastOperationAction.java:47)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:75)
	at org.elasticsearch.client.node.NodeIndicesAdminClient.execute(NodeIndicesAdminClient.java:77)
	at org.elasticsearch.client.support.AbstractIndicesAdminClient.stats(AbstractIndicesAdminClient.java:524)
	at org.elasticsearch.action.admin.indices.stats.IndicesStatsRequestBuilder.doExecute(IndicesStatsRequestBuilder.java:178)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:91)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:65)
	at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:80)
	at org.elasticsearch.marvel.agent.AgentService$ExportingWorker.exportIndicesStats(AgentService.java:293)
	at org.elasticsearch.marvel.agent.AgentService$ExportingWorker.run(AgentService.java:260)
	at java.lang.Thread.run(Thread.java:745)
```

It is true that the index is closed, but shouldn't marvel skip closed indices instead of throwing an error when it tries to process them?

**Comment by clintongormley** [comment] 2015-05-15 15:58
Makes sense @bradvido

**Comment by bleskes** [comment] 2015-05-20 12:21
@bradvido do you have a custom `marvel.agent.indices` ? the default (empty) one shouldn't expand to closed indices...

**Comment by bradvido** [comment] 2015-06-02 15:52
Yes, I do have custom for all:
`marvel.agent.indices: "*"`

Still, I'd expect closed indices to be skipped.

**Comment by bleskes** [comment] 2015-06-08 12:57
@bradvido thx. This is equivalent to the default and it works for me, so something else is in place. Any chance you can create a small reproduction?

**Comment by jpountz** [comment] 2015-08-26 19:50
Closing due to lack of feedback

**Closed by jpountz** 2015-08-26 19:50 UTC
Labels: enhancement, feedback_needed
