### ISSUE TITLE
user_agent processor produces versions formatted as `128.0.`

### ISSUE THREAD

**Issue by lahsivjar** [elastic/elasticsearch#116950] opened 2024-11-18 14:50 UTC
### Elasticsearch Version

8.x, main

### Java Version

_bundled_

### OS Version

all

### Problem Description

[user-agent processor](https://www.elastic.co/guide/en/elasticsearch/reference/current/user-agent-processor.html) with a user-agent as `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0` produces versions with trailing `.`. The issue is made worse due to https://github.com/elastic/elasticsearch/issues/116946 which causes the produced value to be mapped as a `date` if date detection and dynamic mapping are enabled.

### Steps to Reproduce

```
PUT _ingest/pipeline/user_agent
{
  "description" : "Add user agent information",
  "processors" : [
    {
      "user_agent" : {
        "field" : "agent"
      }
    }
  ]
}
PUT testagentbug/_doc/my_id?pipeline=user_agent
{
  "agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0"
}
GET testagentbug/_doc/my_id // The `user_agent.version` field has the value of `128.0.`
```

Expectation is for the `user_agent.version` to be correctly detected (without the trailing `.`)

**Comment by AI-IshanBhatt** [comment] 2024-11-20 10:08
It should be fixed by #116953

**Comment by AI-IshanBhatt** [comment] 2024-11-20 10:09
Duplicate of #116946

**Comment by lahsivjar** [comment] 2024-11-20 10:22
> Duplicate of https://github.com/elastic/elasticsearch/issues/116946

I don't think this is a duplicate of Duplicate of https://github.com/elastic/elasticsearch/issues/116946 as that one is about the date detection detecting `128.0.` strings as date whereas this one is about the user_agent processor which is producing the `version` field as `128.0.` when given an input `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0`

**Comment by smalyshev** [comment] 2024-11-20 22:55
This is not a duplicate and it happens because regex parser for this string produces patch version as empty string, and `UserAgentProcessor.java` does not handle empty strings properly when recomposing the version string.

**Closed** 2024-12-04 00:32 UTC
Labels: >bug, Team:Search Foundations, :Search Foundations/Search
