### ISSUE TITLE
ReindexFromRemote#testEs2WithFunnyThrottle fails on 5.5

### ISSUE THREAD

**Issue by jaymode** [elastic/elasticsearch#25453] opened 2017-06-28 18:39 UTC
In CI, the ReindexFromRemote#testEs2WithFunnyThrottle test fails due to a index not found exception when trying to delete the `test` index:

```
org.elasticsearch.client.ResponseException: DELETE http://127.0.0.1:42507/test: HTTP/1.1 404 Not Found
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"test","index":"test"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"test","index":"test"},"status":404}
	at __randomizedtesting.SeedInfo.seed([EEBCB9A46F195C13:BA1AFFC5C1CB88B5]:0)
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:354)
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:343)
	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	at java.lang.Thread.run(Thread.java:748)
```

I was not able to reproduce but this is the reproduce line:

```
gradle :qa:reindex-from-old:integTestRunner -Dtests.seed=EEBCB9A46F195C13 -Dtests.class=org.elasticsearch.smoketest.ReindexFromOldRemoteIT -Dtests.method="testEs2WithFunnyThrottle" -Dtests.security.manager=true -Dtests.locale=en-US -Dtests.timezone=Etc/GMT-3
```

Build url: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.5+multijob-unix-compatibility/os=oraclelinux/48/console

**Comment by droberts195** [comment] 2017-12-08 14:26
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=oraclelinux/1772/console failed on a different test in the same suite, but in the same way: it got a 404 when trying to delete the `test` index in the `finally` block.

The exception thrown from the `finally` block could well be masking an earlier exception which would have been more useful.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/1772/os=oraclelinux/artifact/qa/reindex-from-old/build/cluster/integTestCluster%20node0/elasticsearch-7.0.0-alpha1-SNAPSHOT/logs/qa_reindex-from-old_integTestCluster.log contains this error:

```
[2017-12-08T14:03:49,672][WARN ][o.e.i.r.TransportReindexAction] [node-0] Failed to clear scroll [c2NhbjswOzE7dG90YWxfaGl0czo1Ow==]
org.elasticsearch.client.ResponseException: method [DELETE], host [http://127.0.0.1:33317], URI [/_search/scroll], status line [HTTP/1.1 500 Internal Server Error]
{"error":"ActionRequestValidationException[Validation Failed: 1: no scroll ids specified;]","status":500}
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:357) [elasticsearch-rest-client-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:346) [elasticsearch-rest-client-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119) [httpcore-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177) [httpasyncclient-4.1.2.jar:4.1.2]
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436) [httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326) [httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265) [httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81) [httpasyncclient-4.1.2.jar:4.1.2]
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39) [httpasyncclient-4.1.2.jar:4.1.2]
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114) [httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) [httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) [httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) [httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) [httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) [httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588) [httpcore-nio-4.4.5.jar:4.4.5]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

Also, https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/1772/os=oraclelinux/artifact/qa/reindex-from-old/build/tmp/unzipEs090/elasticsearch-0.90.13/logs/elasticsearch.log contains this:

```
[2017-12-08 14:03:28,955][WARN ][discovery.zen.ping.multicast] [Atlas] failed to read requesting data from /127.0.0.1:54328
java.io.IOException: Expected handle header, got [13]
	at org.elasticsearch.common.io.stream.HandlesStreamInput.readString(HandlesStreamInput.java:65)
	at org.elasticsearch.cluster.ClusterName.readFrom(ClusterName.java:64)
	at org.elasticsearch.cluster.ClusterName.readClusterName(ClusterName.java:58)
	at org.elasticsearch.discovery.zen.ping.multicast.MulticastZenPing$Receiver.run(MulticastZenPing.java:409)
	at java.lang.Thread.run(Thread.java:748)
[2017-12-08 14:03:30,460][WARN ][discovery.zen.ping.multicast] [Atlas] failed to read requesting data from /127.0.0.1:54328
java.io.IOException: Expected handle header, got [13]
	at org.elasticsearch.common.io.stream.HandlesStreamInput.readString(HandlesStreamInput.java:65)
	at org.elasticsearch.cluster.ClusterName.readFrom(ClusterName.java:64)
	at org.elasticsearch.cluster.ClusterName.readClusterName(ClusterName.java:58)
	at org.elasticsearch.discovery.zen.ping.multicast.MulticastZenPing$Receiver.run(MulticastZenPing.java:409)
	at java.lang.Thread.run(Thread.java:748)
[2017-12-08 14:03:31,962][WARN ][discovery.zen.ping.multicast] [Atlas] failed to read requesting data from /127.0.0.1:54328
java.io.IOException: Expected handle header, got [13]
	at org.elasticsearch.common.io.stream.HandlesStreamInput.readString(HandlesStreamInput.java:65)
	at org.elasticsearch.cluster.ClusterName.readFrom(ClusterName.java:64)
	at org.elasticsearch.cluster.ClusterName.readClusterName(ClusterName.java:58)
	at org.elasticsearch.discovery.zen.ping.multicast.MulticastZenPing$Receiver.run(MulticastZenPing.java:409)
	at java.lang.Thread.run(Thread.java:748)
```

However, I could not reproduce the problem locally yet my local equivalents of those two log files for the successful test contain the same errors.  The REPRO command was:

```
gradle :qa:reindex-from-old:integTestRunner \
  -Dtests.seed=22F500316A81743F \
  -Dtests.class=org.elasticsearch.smoketest.ReindexFromOldRemoteIT \
  -Dtests.method="testEs090" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-OM \
  -Dtests.timezone=Africa/Lagos
```

**Comment by nik9000** [comment] 2018-01-26 15:42
I'll take a look at this now.

**Comment by nik9000** [comment] 2018-01-26 16:32
I've pushed a patch that ought not to hide the real failure the next time it happens.

**Comment by dakrone** [comment] 2018-03-20 14:54
Haven't seen this fail in a long time, so closing this.

**Closed by dakrone** 2018-03-20 14:54 UTC
Labels: :Distributed/CRUD, >test, jenkins
