### ISSUE TITLE
{i.n.channel.AbstractChannel:146} Force-closing a channel whose registration task was not accepted by an event loop: [id: 0x542c835b]  java.lang.OutOfMemoryError: unable to create new native thread

### ISSUE THREAD

**Issue by yinweitao** [elastic/elasticsearch#35681] opened 2018-11-19 04:11 UTC
2018-11-19 11:58:43,976 [WARN] {i.n.channel.AbstractChannel:146} Force-closing a channel whose registration task was not accepted by an event loop: [id: 0x542c835b]

java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at io.netty.util.concurrent.ThreadPerTaskExecutor.execute(ThreadPerTaskExecutor.java:33)
	at io.netty.util.concurrent.SingleThreadEventExecutor.doStartThread(SingleThreadEventExecutor.java:862)
	at io.netty.util.concurrent.SingleThreadEventExecutor.startThread(SingleThreadEventExecutor.java:855)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:760)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:475)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74)
	at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:85)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:330)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:163)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:145)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:126)
	at com.voxlearning.alps.remote.hydra.client.channel.ClientChannel.lambda$new$0(ClientChannel.java:70)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-11-19 11:58:43,977 [WARN] {i.n.channel.AbstractChannel:146} Force-closing a channel whose registration task was not accepted by an event loop: [id: 0xc8677bc3]

java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at io.netty.util.concurrent.ThreadPerTaskExecutor.execute(ThreadPerTaskExecutor.java:33)
	at io.netty.util.concurrent.SingleThreadEventExecutor.doStartThread(SingleThreadEventExecutor.java:862)
	at io.netty.util.concurrent.SingleThreadEventExecutor.startThread(SingleThreadEventExecutor.java:855)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:760)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:475)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74)
	at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:85)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:330)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:163)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:145)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:126)
	at com.voxlearning.alps.remote.hydra.client.channel.ClientChannel.lambda$new$0(ClientChannel.java:70)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-11-19 11:58:44,252 [ERROR] {i.n.u.c.D.rejectedExecution:181} Failed to submit a listener notification task. Event loop shut down?

java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at io.netty.util.concurrent.GlobalEventExecutor.startThread(GlobalEventExecutor.java:222)
	at io.netty.util.concurrent.GlobalEventExecutor.execute(GlobalEventExecutor.java:211)
	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:767)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:435)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:102)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:912)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)
2018

**Comment by jasontedor** [comment] 2018-11-19 04:44
I am sorry that you’re having trouble.

This is not a good issue report. You’ve ignored our template, not given any steps to reproduce, and dropped a stack trace in our laps without any context. Please help us help you.

Unable to create new native thread is almost always an indication that you’ve hit a resource limit. For example a memory limit or an rlimit (e.g., max processes). This is rarely indicative of our a problem on our side, usually it’s one on yours. 

And anyway, this in the stacktrace is completely out of place:

```
com.voxlearning.alps.remote.hydra.client.channel.ClientChannel.lambda$new$0(ClientChannel.java:70)
```

Do you see how `elasticsearch` never appears in the stacktrace anywhere?  Is this purely client side then? That is unlikely to be us, instead you. Check your rlimit as a start.

I am treating this as not a bug report, instead as a user question.  There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Closed by jasontedor** 2018-11-19 04:44 UTC
