### ISSUE TITLE
num_freed field in clear all scrolls response is incorrect

### ISSUE THREAD

**Issue by stav29** [elastic/elasticsearch#63171] opened 2020-10-02 10:52 UTC
**Elasticsearch version** (`bin/elasticsearch --7.8.1`):

**Plugins installed**: []

**JVM version** (`java -11.0.6`):

**OS version** (windows):

**Description of the problem**:
When I try to delete all scrolls using DELETE server:port/_search/scroll/_all
I get the number of nodes in the cluster in the num_freed field instead of the number of scrolls actually being deleted

**Comment by stav29** [comment] 2020-10-02 10:55
If it's fairly easy I would like to try and fix this bug

**Comment by matriv** [comment] 2020-10-05 15:24
@stav29 Do you have an example to reproduce this ?

**Comment by stav29** [comment] 2020-10-05 21:20
@matriv in order to reproduce this you will - need to run DELETE /_search/scroll/_all  (instead of passing a specific scroll id or some scroll id's in an array). It wouldn't matter how many active scrolls you have (even without active scrolls) you will get the number of nodes in your cluster in the num_freed field in the response.

**Comment by matriv** [comment] 2020-10-06 08:25
@stav29 Thx for the clarification, the current behaviour is the intended one, but it's not documented (regarding the `_all`).
Feel free to work on the improvement you propose, which can be a bit trickier when there are failures on nodes involved.

**Comment by javanna** [comment] 2024-06-24 18:52
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.

**Closed by javanna** 2024-06-24 18:52 UTC
Labels: >enhancement, :Search/Search, Team:Search
