### ISSUE TITLE
[CI] RejectionActionIT#testSimulatedSearchRejectionLoad failure

### ISSUE THREAD

**Issue by jaymode** [elastic/elasticsearch#26745] opened 2017-09-21 20:30 UTC
The RejectionActionIT#testSimulatedSearchRejectionLoad failed in CI on the 5.6 branch. Looking back this test seems to have failed intermittently but has different failures. The latest is caused by an uncaught exception from an assertion.

Build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+java9-periodic/694/console

```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=349, name=elasticsearch[node_s0][local_transport][T#3], state=RUNNABLE, group=TGRP-RejectionActionIT]
	at __randomizedtesting.SeedInfo.seed([1646A71AAEE0DE84:8C76F0189600A0B4]:0)
Caused by: java.lang.AssertionError: unexpected higher total ops [10] compared to expected [9]
	at __randomizedtesting.SeedInfo.seed([1646A71AAEE0DE84]:0)
	at org.elasticsearch.action.search.InitialSearchPhase.successfulShardExecution(InitialSearchPhase.java:204)
	at org.elasticsearch.action.search.InitialSearchPhase.onShardResult(InitialSearchPhase.java:190)
	at org.elasticsearch.action.search.InitialSearchPhase.access$000(InitialSearchPhase.java:46)
	at org.elasticsearch.action.search.InitialSearchPhase$1.innerOnResponse(InitialSearchPhase.java:164)
	at org.elasticsearch.action.search.SearchActionListener.onResponse(SearchActionListener.java:44)
	at org.elasticsearch.action.search.SearchActionListener.onResponse(SearchActionListener.java:29)
	at org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:46)
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1060)
	at org.elasticsearch.transport.local.LocalTransport.lambda$handleParsedResponse$4(LocalTransport.java:444)
	at org.elasticsearch.common.util.concurrent.EsExecutors$1.execute(EsExecutors.java:110)
	at org.elasticsearch.transport.local.LocalTransport.handleParsedResponse(LocalTransport.java:442)
	at org.elasticsearch.test.transport.AssertingLocalTransport.handleParsedResponse(AssertingLocalTransport.java:100)
	at org.elasticsearch.transport.local.LocalTransport.handleResponse(LocalTransport.java:438)
	at org.elasticsearch.transport.local.LocalTransport.processReceivedMessage(LocalTransport.java:340)
	at org.elasticsearch.transport.local.LocalTransport.lambda$receiveMessage$0(LocalTransport.java:300)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

Reproduce line (did not reproduce):

```
gradle :core:integTest \
  -Dtests.seed=1646A71AAEE0DE84 \
  -Dtests.class=org.elasticsearch.action.RejectionActionIT \
  -Dtests.method="testSimulatedSearchRejectionLoad" \
  -Dtests.security.manager=true \
  -Dtests.jvm.argline="--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.nio.file=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.locks=ALL-UNNAMED --add-opens=java.base/java.util.regex=ALL-UNNAMED" \
  -Dtests.locale=eo \
  -Dtests.timezone=Africa/Libreville
```

@s1monw assigning to you based on git history.

**Comment by s1monw** [comment] 2017-11-23 16:57
can not reproduce

**Comment by colings86** [comment] 2018-02-12 09:19
This failed again in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+openjdk-java8-periodic/79/console

It seems that this has failed 6 times since July 2017 and only ever on the 5.6 branch. I'm going to try to see what is different between the 5.6 and 6.x branch in this area to see if there is anything that could be causing this on 5.6

**Comment by colings86** [comment] 2018-02-12 15:15
I spoke to @jpountz and @bleskes about this (thanks both for the help and discussion) and have pushed https://github.com/elastic/elasticsearch/commit/24c10adbef334f241c18226fcc74ac10b3f6d7cd to add some more information to the assertion error. If this does not produce enough information to see whats going on we might add logging to onSuccessfulShard() and onShardFailure() to show exactly which shards are being run and if there is any double execution happening but there was concern that doing this might also change the timing around this and cause it to occur even more rarely.

**Comment by colings86** [comment] 2018-05-11 09:07
This hasn't failed since 12 Feb so I'm going to close it now and it can be reopened if we see it again

**Comment by vladimirdolzhenko** [comment] 2018-07-05 09:55
It happened again

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+multijob-unix-compatibility/os=ubuntu&&virtual/1188/console

reproduce command (doesn't reproduce locally)
```
./gradlew :core:integTest -Dtests.seed=E4624DBD70EDA483 -Dtests.class=org.elasticsearch.action.RejectionActionIT -Dtests.method="testSimulatedSearchRejectionLoad" -Dtests.security.manager=true -Dtests.locale=sr-Latn -Dtests.timezone=Asia/Oral
```

there are lots of leaked threads:
```
 2> jul 04, 2018 12:20:10 PM com.carrotsearch.randomizedtesting.ThreadLeakControl checkThreadLeaks
  2> WARNING: Will linger awaiting termination of 96 leaked thread(s).
  2> jul 04, 2018 12:20:15 PM com.carrotsearch.randomizedtesting.ThreadLeakControl checkThreadLeaks
  2> SEVERE: 96 threads leaked from SUITE scope at org.elasticsearch.action.RejectionActionIT

2>    1) Thread[id=982, name=elasticsearch[transport_client_node_s0][local_transport][T#5], state=WAITING, group=TGRP-RejectionActionIT]
  2>    2) Thread[id=956, name=elasticsearch[transport_client_node_s1][scheduler][T#1], state=TIMED_WAITING, group=TGRP-RejectionActionIT]
  2>    3) Thread[id=1007, name=elasticsearch[transport_client_node_s0][local_transport][T#14], state=WAITING, group=TGRP-RejectionActionIT]
  2>    4) Thread[id=934, name=elasticsearch[node_s1][clusterService#updateTask][T#1], state=WAITING, group=TGRP-RejectionActionIT]
  2>    5) Thread[id=965, name=elasticsearch[transport_client_node_s0][scheduler][T#1], state=TIMED_WAITING, group=TGRP-RejectionActionIT]
  2>    6) Thread[id=1018, name=elasticsearch[transport_client_node_s0][generic][T#4], state=WAITING, group=TGRP-RejectionActionIT]
  2>    7) Thread[id=1017, name=elasticsearch[transport_client_node_s1][generic][T#3], state=WAITING, group=TGRP-RejectionActionIT]
  2>    8) Thread[id=1012, name=elasticsearch[node_s0][refresh][T#1], state=WAITING, group=TGRP-RejectionActionIT]
  2>    9) Thread[id=986, name=elasticsearch[transport_client_node_s1][local_transport][T#9], state=WAITING, group=TGRP-RejectionActionIT]
  2>   10) Thread[id=930, name=elasticsearch[node_s1][[ttl_expire]], state=TIMED_WAITING, group=TGRP-RejectionActionIT]
  2>   11) Thread[id=981, name=elasticsearch[transport_client_node_s1][listener][T#4], state=WAITING, group=TGRP-RejectionActionIT]
  2>   12) Thread[id=935, name=elasticsearch[node_s0][generic][T#1], state=TIMED_WAITING, group=TGRP-RejectionActionIT]
  2>   13) Thread[id=985, name=elasticsearch[transport_client_node_s1][listener][T#5], state=WAITING, group=TGRP-RejectionActionIT]
  2>   14) Thread[id=1020, name=elasticsearch[node_s1][management][T#3], state=TIMED_WAITING, group=TGRP-RejectionActionIT]
  2>   15) Thread[id=988, name=elasticsearch[transport_client_node_s0][local_transport][T#6], state=WAITING, group=TGRP-RejectionActionIT]
  2>   16) Thread[id=996, name=elasticsearch[transport_client_node_s0][listener][T#5], state=WAITING, group=TGRP-RejectionActionIT]
  2>   17) Thread[id=971, name=elasticsearch[transport_client_node_s0][listener][T#1], state=WAITING, group=TGRP-RejectionActionIT]
  2>   18) Thread[id=949, name=elasticsearch[node_s1][generic][T#5], state=WAITING, group=TGRP-RejectionActionIT]
  2>   19) Thread[id=1016, name=elasticsearch[transport_client_node_s0][generic][T#3], state=WAITING, group=TGRP-RejectionActionIT]
  2>   20) Thread[id=942, name=elasticsearch[node_s0][generic][T#3], state=TIMED_WAITING, group=TGRP-RejectionActionIT]
  2>   21) Thread[id=1011, name=elasticsearch[transport_client_node_s0][local_transport][T#15], state=WAITING, group=TGRP-RejectionActionIT]
  2>   22) Thread[id=1015, name=elasticsearch[transport_client_node_s0][generic][T#2], state=WAITING, group=TGRP-RejectionActionIT]
  2>   23) Thread[id=940, name=elasticsearch[node_s1][generic][T#3], state=WAITING, group=TGRP-RejectionActionIT]
  2>   24) Thread[id=962, name=elasticsearch[node_s1][search][T#1], state=WAITING, group=TGRP-RejectionActionIT]
  2>   25) Thread[id=1009, name=elasticsearch[transport_client_node_s1][local_transport][T#16], state=WAITING, group=TGRP-RejectionActionIT]
  2>   26) Thread[id=950, name=elasticsearch[node_s1][generic][T#6], state=WAITING, group=TGRP-RejectionActionIT]
  2>   27) Thread[id=1005, name=elasticsearch[transport_client_node_s1][local_transport][T#13], state=WAITING, group=TGRP-RejectionActionIT]
  2>   28) Thread[id=970, name=elasticsearch[transport_client_node_s0][local_transport][T#2], state=WAITING, group=TGRP-RejectionActionIT]
  2>   29) Thread[id=1002, name=elasticsearch[transport_client_node_s0][listener][T#8], state=WAITING, group=TGRP-RejectionActionIT]
  2>   30) Thread[id=997, name=elasticsearch[transport_client_node_s0][local_transport][T#9], state=WAITING, group=TGRP-RejectionActionIT]
  2>   31) Thread[id=933, name=elasticsearch[node_s0][clusterService#updateTask][T#1], state=WAITING, group=TGRP-RejectionActionIT]
  2>   32) Thread[id=1013, name=elasticsearch[node_s1][refresh][T#1], state=WAITING, group=TGRP-RejectionActionIT]
  2>   33) Thread[id=972, name=elasticsearch[transport_client_node_s1][local_transport][T#5], state=WAITING, group=TGRP-RejectionActionIT]
  2>   34) Thread[id=925, name=elasticsearch[node_s0][[timer]], state=TIMED_WAITING, group=TGRP-RejectionActionIT]
  2>   35) Thread[id=966, name=elasticsearch[transport_client_node_s0][local_transport][T#1], state=WAITING, group=TGRP-RejectionActionIT]
  2>   36) Thread[id=944, name=elasticsearch[node_s1][generic][T#4], state=WAITING, group=TGRP-RejectionActionIT]
  2>   37) Thread[id=1001, name=elasticsearch[transport_client_node_s0][local_transport][T#11], state=WAITING, group=TGRP-RejectionActionIT]
  2>   38) Thread[id=958, name=elasticsearch[transport_client_node_s1][generic][T#1], state=WAITING, group=TGRP-RejectionActionIT]
  2>   39) Thread[id=967, name=elasticsearch[transport_client_node_s0][generic][T#1], state=WAITING, group=TGRP-RejectionActionIT]
  2>   40) Thread[id=960, name=elasticsearch[transport_client_node_s1][local_transport][T#2], state=WAITING, group=TGRP-RejectionActionIT]
  2>   41) Thread[id=978, name=elasticsearch[transport_client_node_s0][local_transport][T#4], state=WAITING, group=TGRP-RejectionActionIT]
  2>   42) Thread[id=989, name=elasticsearch[transport_client_node_s0][local_transport][T#7], state=WAITING, group=TGRP-RejectionActionIT]
  2>   43) Thread[id=975, name=elasticsearch[transport_client_node_s1][listener][T#3], state=WAITING, group=TGRP-RejectionActionIT]
  2>   44) Thread[id=926, name=elasticsearch[node_s0][scheduler][T#1], state=TIMED_WAITING, group=TGRP-RejectionActionIT]
  2>   45) Thread[id=1019, name=elasticsearch[transport_client_node_s1][generic][T#4], state=WAITING, group=TGRP-RejectionActionIT]
  2>   46) Thread[id=948, name=elasticsearch[node_s0][management][T#1], state=TIMED_WAITING, group=TGRP-RejectionActionIT]
  2>   47) Thread[id=992, name=elasticsearch[transport_client_node_s0][local_transport][T#8], state=WAITING, group=TGRP-RejectionActionIT]
  2>   48) Thread[id=1004, name=elasticsearch[transport_client_node_s0][local_transport][T#13], state=WAITING, group=TGRP-RejectionActionIT]
  2>   49) Thread[id=1014, name=elasticsearch[transport_client_node_s1][generic][T#2], state=WAITING, group=TGRP-RejectionActionIT]
  2>   50) Thread[id=1008, name=elasticsearch[transport_client_node_s1][local_transport][T#15], state=WAITING, group=TGRP-RejectionActionIT]
  2>   51) Thread[id=1023, name=elasticsearch[node_s0][flush][T#1], state=WAITING, group=TGRP-RejectionActionIT]
  2>   52) Thread[id=987, name=elasticsearch[transport_client_node_s1][listener][T#6], state=WAITING, group=TGRP-RejectionActionIT]
  2>   53) Thread[id=977, name=elasticsearch[transport_client_node_s0][listener][T#2], state=WAITING, group=TGRP-RejectionActionIT]
  2>   54) Thread[id=954, name=elasticsearch[node_s0][bulk][T#1], state=WAITING, group=TGRP-RejectionActionIT]
  2>   55) Thread[id=951, name=elasticsearch[node_s1][bulk][T#1], state=WAITING, group=TGRP-RejectionActionIT]
  2>   56) Thread[id=983, name=elasticsearch[transport_client_node_s0][listener][T#4], state=WAITING, group=TGRP-RejectionActionIT]
  2>   57) Thread[id=976, name=elasticsearch[transport_client_node_s0][local_transport][T#3], state=WAITING, group=TGRP-RejectionActionIT]
  2>   58) Thread[id=995, name=elasticsearch[transport_client_node_s0][listener][T#6], state=WAITING, group=TGRP-RejectionActionIT]
  2>   59) Thread[id=993, name=elasticsearch[transport_client_node_s1][local_transport][T#12], state=WAITING, group=TGRP-RejectionActionIT]
  2>   60) Thread[id=1000, name=elasticsearch[transport_client_node_s0][listener][T#7], state=WAITING, group=TGRP-RejectionActionIT]
  2>   61) Thread[id=1003, name=elasticsearch[transport_client_node_s0][local_transport][T#12], state=WAITING, group=TGRP-RejectionActionIT]
  2>   62) Thread[id=959, name=elasticsearch[node_s0][bulk][T#2], state=WAITING, group=TGRP-RejectionActionIT]
  2>   63) Thread[id=953, name=elasticsearch[node_s0][generic][T#6], state=TIMED_WAITING, group=TGRP-RejectionActionIT]
  2>   64) Thread[id=941, name=elasticsearch[node_s0][local_transport][T#1], state=WAITING, group=TGRP-RejectionActionIT]
  2>   65) Thread[id=938, name=elasticsearch[node_s1][local_transport][T#1], state=WAITING, group=TGRP-RejectionActionIT]
  2>   66) Thread[id=947, name=elasticsearch[node_s0][generic][T#4], state=TIMED_WAITING, group=TGRP-RejectionActionIT]
  2>   67) Thread[id=973, name=elasticsearch[transport_client_node_s1][listener][T#2], state=WAITING, group=TGRP-RejectionActionIT]
  2>   68) Thread[id=927, name=elasticsearch[node_s0][[ttl_expire]], state=TIMED_WAITING, group=TGRP-RejectionActionIT]
  2>   69) Thread[id=994, name=elasticsearch[transport_client_node_s1][listener][T#8], state=WAITING, group=TGRP-RejectionActionIT]
  2>   70) Thread[id=943, name=elasticsearch[node_s0][local_transport][T#2], state=WAITING, group=TGRP-RejectionActionIT]
  2>   71) Thread[id=945, name=elasticsearch[node_s1][management][T#1], state=TIMED_WAITING, group=TGRP-RejectionActionIT]
  2>   72) Thread[id=946, name=elasticsearch[node_s1][management][T#2], state=TIMED_WAITING, group=TGRP-RejectionActionIT]
  2>   73) Thread[id=955, name=elasticsearch[transport_client_node_s1][[timer]], state=TIMED_WAITING, group=TGRP-RejectionActionIT]
  2>   74) Thread[id=974, name=elasticsearch[transport_client_node_s1][local_transport][T#6], state=WAITING, group=TGRP-RejectionActionIT]
  2>   75) Thread[id=991, name=elasticsearch[transport_client_node_s1][listener][T#7], state=WAITING, group=TGRP-RejectionActionIT]
  2>   76) Thread[id=961, name=elasticsearch[transport_client_node_s1][local_transport][T#3], state=WAITING, group=TGRP-RejectionActionIT]
  2>   77) Thread[id=952, name=elasticsearch[node_s0][generic][T#5], state=TIMED_WAITING, group=TGRP-RejectionActionIT]
  2>   78) Thread[id=1006, name=elasticsearch[transport_client_node_s1][local_transport][T#14], state=WAITING, group=TGRP-RejectionActionIT]
  2>   79) Thread[id=969, name=elasticsearch[transport_client_node_s1][listener][T#1], state=WAITING, group=TGRP-RejectionActionIT]
  2>   80) Thread[id=1021, name=elasticsearch[node_s0][management][T#2], state=TIMED_WAITING, group=TGRP-RejectionActionIT]
  2>   81) Thread[id=924, name=TEST-RejectionActionIT.testSimulatedSearchRejectionLoad-seed#[E4624DBD70EDA483], state=WAITING, group=TGRP-RejectionActionIT]
  2>   82) Thread[id=957, name=elasticsearch[transport_client_node_s1][local_transport][T#1], state=WAITING, group=TGRP-RejectionActionIT]
  2>   83) Thread[id=968, name=elasticsearch[transport_client_node_s1][local_transport][T#4], state=WAITING, group=TGRP-RejectionActionIT]
  2>   84) Thread[id=929, name=elasticsearch[node_s1][scheduler][T#1], state=TIMED_WAITING, group=TGRP-RejectionActionIT]
  2>   85) Thread[id=928, name=elasticsearch[node_s1][[timer]], state=TIMED_WAITING, group=TGRP-RejectionActionIT]
  2>   86) Thread[id=998, name=elasticsearch[transport_client_node_s1][local_transport][T#11], state=WAITING, group=TGRP-RejectionActionIT]
  2>   87) Thread[id=990, name=elasticsearch[transport_client_node_s1][local_transport][T#10], state=WAITING, group=TGRP-RejectionActionIT]
  2>   88) Thread[id=937, name=elasticsearch[node_s0][generic][T#2], state=TIMED_WAITING, group=TGRP-RejectionActionIT]
  2>   89) Thread[id=980, name=elasticsearch[transport_client_node_s0][listener][T#3], state=WAITING, group=TGRP-RejectionActionIT]
  2>   90) Thread[id=984, name=elasticsearch[transport_client_node_s1][local_transport][T#8], state=WAITING, group=TGRP-RejectionActionIT]
  2>   91) Thread[id=964, name=elasticsearch[transport_client_node_s0][[timer]], state=TIMED_WAITING, group=TGRP-RejectionActionIT]
  2>   92) Thread[id=979, name=elasticsearch[transport_client_node_s1][local_transport][T#7], state=WAITING, group=TGRP-RejectionActionIT]
  2>   93) Thread[id=963, name=elasticsearch[node_s0][search][T#1], state=WAITING, group=TGRP-RejectionActionIT]
  2>   94) Thread[id=999, name=elasticsearch[transport_client_node_s0][local_transport][T#10], state=WAITING, group=TGRP-RejectionActionIT]
  2>   95) Thread[id=1022, name=elasticsearch[node_s1][flush][T#1], state=WAITING, group=TGRP-RejectionActionIT]
  2>   96) Thread[id=1010, name=elasticsearch[transport_client_node_s0][local_transport][T#16], state=WAITING, group=TGRP-RejectionActionIT]
  2> NOTE: leaving temporary files on disk at: /var/lib/jenkins/workspace/elastic+elasticsearch+5.6+multijob-unix-compatibility/os/ubuntu&&virtual/core/build/testrun/integTest/J2/temp/org.elasticsearch.action.RejectionActionIT_E4624DBD70EDA483-001
```

**Comment by vladimirdolzhenko** [comment] 2018-07-05 09:55
Pinging @elastic/es-search-aggs

**Comment by colings86** [comment] 2018-08-03 08:37
Looking at the logs for this last one it looks like this was a transient failure with the CI infrastructure. It looks like a worker process died and that caused a suite timeout which in turn leads to the leaked threads:
```
07:19:11 HEARTBEAT J2 PID(59920@worker-0929ae9b7d6f48436.build.us-west-2a.elasticnet.co): 2018-07-04T07:19:11, stalled for 1141s at: RejectionActionIT.testSimulatedSearchRejectionLoad
07:19:21 HEARTBEAT J2 PID(59920@worker-0929ae9b7d6f48436.build.us-west-2a.elasticnet.co): 2018-07-04T07:19:21, stalled for 1151s at: RejectionActionIT.testSimulatedSearchRejectionLoad
07:19:31 HEARTBEAT J2 PID(59920@worker-0929ae9b7d6f48436.build.us-west-2a.elasticnet.co): 2018-07-04T07:19:31, stalled for 1161s at: RejectionActionIT.testSimulatedSearchRejectionLoad
07:19:41 HEARTBEAT J2 PID(59920@worker-0929ae9b7d6f48436.build.us-west-2a.elasticnet.co): 2018-07-04T07:19:41, stalled for 1171s at: RejectionActionIT.testSimulatedSearchRejectionLoad
07:19:51 HEARTBEAT J2 PID(59920@worker-0929ae9b7d6f48436.build.us-west-2a.elasticnet.co): 2018-07-04T07:19:51, stalled for 1181s at: RejectionActionIT.testSimulatedSearchRejectionLoad
07:20:01 HEARTBEAT J2 PID(59920@worker-0929ae9b7d6f48436.build.us-west-2a.elasticnet.co): 2018-07-04T07:20:01, stalled for 1191s at: RejectionActionIT.testSimulatedSearchRejectionLoad
```

and
 
```
07:20:15   2> WARNING: Suite execution timed out: org.elasticsearch.action.RejectionActionIT
```

I'm going to close this again since this appears to have been a transient failure and is definitely different to the original issue. If the thread leak appears again (i.e. its not a transient issue) we should open a new issue for it and investigate from there.

**Closed by colings86** 2018-08-03 08:37 UTC
Labels: :Search/Search, >test-failure
