### ISSUE TITLE
Windows Checkstyle failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#80118] opened 2021-11-01 09:17 UTC
**Build scan**:
https://gradle-enterprise.elastic.co/s/zb6juz2ohrhec
https://gradle-enterprise.elastic.co/s/rlz2usradpppe
https://gradle-enterprise.elastic.co/s/m3dr4x2yj4afw
+ many more

**Repro line**:
`gradlew :x-pack:docs:checkstyleTest`

**Reproduces locally?**:
Not on macOS

**Applicable branches**:
8.0

**Failure history**:
https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=all_failures&failures.failureMessage=Execution%20failed%20for%20task%20*%0A%3E%20Checkstyle%20rule%20violations%20were%20found.%20See%20the%20report%20at:%20file:///*/*/*/*/build/reports/checkstyle/*%0A%20%20Checkstyle%20files%20with%20violations:%20*%0A%20%20Checkstyle%20violations%20by%20severity:%20*&search.relativeStartTime=P7D&search.timeZoneId=Europe/London

**Failure excerpt**:
```
[ant:checkstyle] [ERROR] C:\Users\jenkins\workspace\platform-support\10\x-pack\docs\src\test\java\org\elasticsearch\smoketest\XDocsClientYamlTestSuiteIT.java:1: Duplicate header javadocs are forbidden [MultipleHeaderJavadoc]
```

**Comment by arteam** [comment] 2021-11-01 10:06
I'm wondering if #80121 would fix that. I also can't test locally, because I'm on Linux.

**Comment by williamrandolph** [comment] 2021-11-17 21:44
I think we can close this as a duplicate of https://github.com/elastic/elasticsearch/issues/80182, fixed by https://github.com/elastic/elasticsearch/pull/80201 . The tests are no longer failing in CI, and I can no longer reproduce on Windows.

**Closed by williamrandolph** 2021-11-17 21:44 UTC
Labels: :Core/Infra/Core, >test-failure, Team:Core/Infra
