### ISSUE TITLE
Cancel a search request in ES

### ISSUE THREAD

**Issue by ESamir** [elastic/elasticsearch#19244] opened 2016-07-04 08:34 UTC
Add possibility to cancel a search request in ES.

When  a request is sent  from a web site and the end-user decide to go to another page, we will like to have the possibility  to stop the current search .

**Comment by dadoonet** [comment] 2016-07-04 09:01
I wonder if you have very loooong running requests.

Otherwise, I don't understand the need for such a feature as most of the time I'd expect search requests running in less than a second.
Can you elaborate a bit more?

**Comment by clintongormley** [comment] 2016-07-04 14:55
Duplicate of #12187

**Closed by clintongormley** 2016-07-04 14:55 UTC
Labels: :Search, discuss, enhancement

**Comment by ebuildy** [comment] 2018-07-06 09:05
it's a good idea, I know Nginx has this kind of feature: http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_ignore_client_abort

> Determines whether the connection with a proxied server should be closed when a client closes the connection without waiting for a response.

elasticsearch should stop the query if the main HTTP query connection is closed by the client.
