### ISSUE TITLE
There is a bug in date math

### ISSUE THREAD

**Issue by yjj0227** [elastic/elasticsearch#95006] opened 2023-04-04 09:15 UTC
### Elasticsearch Version

7.17

### Java Version

_bundled_1.8

### OS Version

5.4.0-128-generic

### Problem Description

I think it's calculated incorrectly only for specific months.
my date math: {now/M-2M{YYYY.MM} (I ran it on 2023.03.02 )
expected result: 2023.01
but real result: 2022.01
it's calculated correctly for other moths

### Steps to Reproduce

if you run it on 2023.04,
please put {now/M-3M{YYYY.MM} on it.
just make the expected result '2023.01'.

### Logs (if relevant)

2023-04-04 16:16:05,760 INFO      "<my-log-{now/M-3M{YYYY.MM}}>" is using Elasticsearch date math.
2023-04-04 16:16:05,763 INFO      DRY-RUN MODE.  No changes will be made.
2023-04-04 16:16:05,763 INFO      DRY-RUN: snapshot: my-log-2022.01

**Comment by thecoop** [comment] 2023-04-04 10:12
@yjj0227 Thanks for the report, I'm afraid there isn't enough information here to diagnose the issue. Could you please add some full reproduction steps, including:
- What's your current timezone?
- What commands are you running to set up your indices & data?
- What commands are you running to query the index, what results are you getting back, and what are you expecting the results to be?

**Comment by DaveCTurner** [comment] 2023-04-04 10:34
I think this duplicates https://github.com/elastic/elasticsearch/issues/67014: if you want calendar years, you should say `yyyy` and not `YYYY`. See https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html for more information.

**Comment by rjernst** [comment] 2023-04-04 14:49
https://github.com/elastic/elasticsearch/issues/67014 is related, but I don't think it duplicates this issue. Rather, this exemplifies why `YYYY` is trappy, since most users do not realize it is for week-based-year.

As @DaveCTurner says, `yyyy` should be used for the year. Since date math is working as intended, I hope you don't mind I close this issue.

**Closed by rjernst** 2023-04-04 14:49 UTC
Labels: >bug, :Core/Infra/Core, Team:Core/Infra
