### ISSUE TITLE
[CI] Failure in reference/aggregations/pipeline/movfn-aggregation/line_42

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#46976] opened 2019-09-23 14:47 UTC
See https://gradle-enterprise.elastic.co/s/yimfrnarnr3q6/tests/jbm2x6tnwtxku-frqyhfwzks75g

```
./gradlew ':docs:integTestRunner' --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/aggregations/pipeline/movfn-aggregation/line_42}" -Dtests.seed=DF4B6341AD614DC6 -Dtests.security.manager=true -Dtests.locale=ar-MA -Dtests.timezone=America/Port-au-Prince -Dcompiler.java=12 -Druntime.java=8
```

failed with:

```
Caused by: java.lang.AssertionError: 
$body didn't match expected value:
                         $body: 
                         _shards: 
                            failed: same [0]
                           skipped: same [0]
                        successful: same [3]
                             total: same [3]
                    aggregations: 
                     my_date_histo: 
                             buckets: 
                                     0: 
                               doc_count: same [3]
                                     key: same [1420070400000]
                           key_as_string: expected String [2015/01/01 00:00:00] but was String [2015-01-01T00:00:00.000Z]
                               the_movfn: 
                                     value: expected [null] but not found
                                 the_sum: 
                                     value: same [550.0]
                                     1: 
                               doc_count: same [2]
                                     key: same [1422748800000]
                           key_as_string: expected String [2015/02/01 00:00:00] but was String [2015-02-01T00:00:00.000Z]
                               the_movfn: 
                                     value: same [550.0]
                                 the_sum: 
                                     value: same [60.0]
                                     2: 
                               doc_count: same [2]
                                     key: same [1425168000000]
                           key_as_string: expected String [2015/03/01 00:00:00] but was String [2015-03-01T00:00:00.000Z]
                               the_movfn: 
                                     value: same [305.0]
                                 the_sum: 
                                     value: same [375.0]
                            hits: 
                              hits: same [empty list]
                         max_score: expected [null] but not found
                             total: 
                            relation: same [eq]
                               value: same [7]
                       timed_out: same [false]
                            took: same [4]
```

**Comment by polyfractal** [comment] 2019-09-23 16:21
Super weird, I have no idea what went wrong.  Looks like the parser might have broken mid parsing or something?  E.g. two incorrect matches were:

- `max_score: expected [null] but not found`
- `the_movfn: value: expected [null] but not found`

But both of those match the response output that was dumped into the log:

```js
{
  "stash" : {
    "body" : {
      "took" : 4,
      "timed_out" : false,
      "_shards" : {
        "total" : 3,
        "successful" : 3,
        "skipped" : 0,
        "failed" : 0
      },
      "hits" : {
        "total" : {
          "value" : 7,
          "relation" : "eq"
        },
        "max_score" : null,  // <-- here
        "hits" : [ ]
      },
      "aggregations" : {
        "my_date_histo" : {
          "buckets" : [
            {
              "key_as_string" : "2015-01-01T00:00:00.000Z",
              "key" : 1420070400000,
              "doc_count" : 3,
              "the_sum" : {
                "value" : 550.0
              },
              "the_movfn" : {
                "value" : null  // <-- here
              }
            },
            {
              "key_as_string" : "2015-02-01T00:00:00.000Z",
              "key" : 1422748800000,
              "doc_count" : 2,
              "the_sum" : {
                "value" : 60.0
              },
              "the_movfn" : {
                "value" : 550.0
              }
            },
            {
              "key_as_string" : "2015-03-01T00:00:00.000Z",
              "key" : 1425168000000,
              "doc_count" : 2,
              "the_sum" : {
                "value" : 375.0
              },
              "the_movfn" : {
                "value" : 305.0
              }
            }
          ]
        }
      }
    }
  }
}
```

The date formats are strange though:

`key_as_string: expected String [2015/01/01 00:00:00] but was String [2015-01-01T00:00:00.000Z]`

The test is definitely looking for `2015/01/01 00:00:00`.

It doesn't reproduce for me though which is odd.  There's no randomization here, just a doc test.  Should fail consistently... I have no idea what's going on :(

**Comment by imotov** [comment] 2019-11-12 19:00
It's strange, unexplainable, unreproducible, it happened once and it never happened again since September. I think we can just blame it on cosmic rays at this point and close.

**Comment by polyfractal** [comment] 2019-11-12 19:11
:+1: for it, gamma ray seems as likely as any other explanation I can come up with.  Closing!

**Closed by polyfractal** 2019-11-12 19:11 UTC
Labels: :Analytics/Aggregations, >test-failure
