### ISSUE TITLE
No easy way of creating index only if not exists

### ISSUE THREAD

**Issue by mouadino** [elastic/elasticsearch#19862] opened 2016-08-08 12:17 UTC
**Describe the feature**:

While trying to find a workaround for previously create [bug](https://github.com/elastic/elasticsearch/issues/19857), one of the work around is to create an index before calling update, but to be more resilient I only want to create the index if it's not already created, sadly the only way of doing that that I could find is to do a "compare and set" which is ofc not atomic and open to race conditions.

What I tried is to create the index and in case an error is returned check if it's of type already exists, which I hopped it's coming with status code 409, sadly it was not the case, and instead I got back 400 which is too generic to just catch index already exists.

I wish for an API that enable to create index only if this later doesn't exist (like SQL `create table if not exists ..`).

**Comment by nik9000** [comment] 2016-08-08 14:31
I've been thinking about a thing for this myself lately so I'm assigning it to myself for now.

If you really need an index to exist before you do a thing you should probably just create it and catch the failure Elasticsearch returns and check if it is `IndexAlreadyExistsException`.

**Comment by dadoonet** [comment] 2016-08-08 14:55
IMO that's the responsability of a client. For example, when I'm integrating an elasticsearch client, I'm basically writing:

```java
    public void createIndex(String index, boolean ignoreErrors) throws IOException {
        logger.debug("create index [{}]", index);
        try {
            client.performRequest("PUT", "/" + index);
        } catch (ResponseException e) {
            if (e.getResponse().getStatusLine().getStatusCode() == 400 &&
                    (e.getMessage().contains("index_already_exists_exception") || e.getMessage().contains("IndexAlreadyExistsException") )) {
                if (!ignoreErrors) {
                    throw new RuntimeException("index already exists");
                }
                logger.trace("index already exists. Ignoring error...");
                return;
            }
            throw e;
        }
    }
```

**Comment by mouadino** [comment] 2016-08-08 15:47
@dadoonet That's what I end up doing, but I will prefer to not depend on string comparison to identify error types, b/c it can easily go wrong when you take in consideration i18n ... .

FYI I am using golang client here https://github.com/olivere/elastic, so for me the code looks more like:

```
func IsAlreadyExists(err interface{}) bool {
	if e, ok := err.(*elastic.Error); ok {
		return e.Status == http.StatusBadRequest && e.Details.Type == "index_already_exists_exception"
	}
	return false
}
```

**Comment by nik9000** [comment] 2016-08-08 15:58
> when you take in consideration i18n

For what it is worth, the type of the error isn't going to be internationalized. It might change but we'd consider that a backward breaking change and only do it is a major release and we *should* be marking it in the migration notes.

**Comment by rochdev** [comment] 2017-07-21 12:01
Has there been any progress on this? I am facing the same issue.

**Comment by hub-cap** [comment] 2018-03-21 12:43
This feature request is an interesting idea but since its opening we have not seen enough feedback that it is a feature we should pursue. We prefer to close this issue as a clear indication that we are not going to work on this at this time. We are always open to reconsidering this in the future based on compelling feedback; despite this issue being closed please feel free to leave feedback on the proposal (including +1s).

**Comment by mario-paniccia** [comment] 2018-06-27 14:28
this feature would be cool 👍

**Comment by boralprophecy** [comment] 2018-09-12 10:40
This is a very useful and important feature. Please implement it.

**Comment by elmehalawi** [comment] 2019-05-15 18:28
This feature would definitely make our lives easier.

**Comment by jossef** [comment] 2019-07-24 05:29
reopen this issue. seems like a reasonable development experience.

**Comment by gwbrown** [comment] 2019-07-26 14:00
We discussed this is FixItFriday given that there's been some feedback on this issue that this is something that people would like to see.

There are two changes we could make based on the feedback in this issue:
1) When attempting to create an index that already exists, the response should be easier to identify. Returning an HTTP 409 Conflict status code would make this simpler.
2) Add a `CREATE IF NOT EXISTS` equivalent.

We've decided to address the first issue and ensure that attempting to create an index that already exists returns an easily identifiable response code. Because that's a breaking change, it will have to wait until the next major version.

We don't have a strong opposition to adding a create-if-not-exists flag/API, but we would like to know if there are use cases that this would enable, or if it would just be more convenient. Once the HTTP status code has been changed for this case, the existing API would effectively work as a create-if-not-exists if the client application considers an HTTP 409 response a success.

**Comment by jossef** [comment] 2019-07-27 18:06
@gwbrown 

my usecase is doing lazy initialization on app start after deleting an index. happens a lot when I'm modeling my data and running on different test/dev environments. 

please add both 1 and 2. 

the `CREATE IF NOT EXISTS` flag will provide a good experience. e.g.

```js
        await elasticsearchClient.indices.create({
            index: 'my-index',
            createIfNotExists: true,
            body: {
                "mappings": {
                    "properties": {...}
                }
            }
        });
```

**Comment by jasontedor** [comment] 2019-08-02 01:58
> my usecase is doing lazy initialization on app start after deleting an index.

If this is lazy initialization on startup, then race conditions aren't a concern and you can do an index exists check and create the index if it doesn't exist otherwise continue. Or, try to create the index and swallow and index exists exception.

We aim to keep the surface area of our API small. We haven't heard a compelling use case that we need to add an additional endpoint here.

**Comment by imjuni** [comment] 2019-12-17 04:15
I want to migrate data from database. So I have to create index so many. And I want set mapping and some configuration, for example analysis setting etc. But indices.exists API not suitable this work. Because That don't reply missing index name. Only return exists or not. 3 index already exists and 2 index not exists, exists API return 404 But not reply not exists index name. Any one help this problem?

```ts
const prefix = 'exists_test';
const checkouts = [
  DateTime.fromFormat('2019-11-10', 'yyyy-LL-dd'),  // exists index
  DateTime.fromFormat('2019-11-09', 'yyyy-LL-dd'),  // not exists index
  DateTime.fromFormat('2019-11-05', 'yyyy-LL-dd'),  // exists index
  DateTime.fromFormat('2019-11-04', 'yyyy-LL-dd'),  // not exists index
  DateTime.fromFormat('2019-11-02', 'yyyy-LL-dd'),  // exists index
];

const res = await ElasticSearch.client.indices.exists({
  index: checkouts.map((checkout) => (`${prefix}_${checkout.toFormat('yyyy_LL_dd')}`)),
});

// I cannot took not name of exists index from response
console.log(res);
```

**Comment by robertbcalhoun** [comment] 2020-02-10 21:11
Hi. I just encountered this issue again while upgrading my client library for ES7. 

I have about 500 agents pushing data to our ElasticSearch cluster, and it's not possible to avoid a potential race condition on index creation as they are all peers. (Even if you check first, some other agent may have created the index between the `cat indices` and `create index` calls.)

[The recommendation on this thread](https://github.com/elastic/elasticsearch/issues/19862#issuecomment-238255983) is to catch HTTP response 400, search the error for `{"type":"index_already_exists_exception"}`, and clear the error if found. This fails on ES7 because ElasticSearch now returns `{"type":"resource_already_exists_exception"}`. This demonstrates the pitfalls of scraping error message text.

In discussing options going forward, @gwbrown said:
> There are two changes we could make based on the feedback in this issue:
> 
> 1. When attempting to create an index that already exists, the response should be easier to identify. Returning an HTTP 409 Conflict status code would make this simpler.
> 2. Add a `CREATE IF NOT EXISTS` equivalent.
> 
> We've decided to address the first issue and ensure that attempting to create an index that already exists returns an easily identifiable response code. Because that's a breaking change, it will have to wait until the next major version.
> 
> We don't have a strong opposition to adding a create-if-not-exists flag/API, but we would like to know if there are use cases that this would enable, or if it would just be more convenient before adding yet more surface area to this API. Once the HTTP status code has been changed for this case, the existing API would effectively work as a create-if-not-exists if the client application considers an HTTP 409 response a success.

I have a modest preference for create-if-not-exists that behaves like linux `mkdir -p` (vs the atomic [`mkdir()`](https://linux.die.net/man/2/mkdir) syscall, or default `mkdir` behavior ) but returning HTTP response code 409 is fine if that seems cleaner / more correct to you. But I do want to encourage you to implement *something* we can code against, as the current behavior (generic error plus an apparently mutable enum string) is not good. 

My plan for now: trap all of the above e.g. 
```
(HTTP_response == 409) || 
(HTTP_response == 400 && type==index_already_exists_exception) || 
(HTTP_response == 400 && type==resource_already_exists_exception)
```

Thank you!
-Rob

I am using:
```
  "version" : {
    "number" : "6.8.0",
    "build_flavor" : "oss",
    "build_type" : "tar",
    "build_hash" : "40905a0",
    "build_date" : "2019-12-13T07:20:39.325941Z",
    "build_snapshot" : false,
    "lucene_version" : "7.7.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },

```

**Comment by ptahchiev** [comment] 2020-07-28 06:27
I have several jobs that export data from db to elasticsearch. Unfortunately some of the jobs start simultaneously and seems like a race condition happens so each one of them is first checking if there's an index present and if not, try to create it. So at some point I start seeing tons of errors in the log saying that the index already exist. I would really appreciate some `RequestOptions` to specify `createIfNotExists`.

**Comment by maxnilz** [comment] 2020-11-25 14:03
+1

**Comment by outsideMyBox** [comment] 2020-12-14 09:00
I also have a use case where "create if no exists" would be useful:
I need to index documents in different indexes depending on some of the document's properties.
The number of indexes can grow over time and specific mappings and settings may need to be applied during each creation (again depending on document's properties). 
This is all good and can be achieved programmatically. The issue is that my client runs on several instances on a Kubernetes cluster, I will for sure hit the case where several ones try to create a new index at the same time.

**Comment by hnwyllmm** [comment] 2021-01-19 01:47
+1

**Comment by hosseinkalbasi** [comment] 2021-05-06 19:35
```
from elasticsearch import Elasticsearch
es = Elasticsearch()

# ignore 400 cause by IndexAlreadyExistsException when creating an index
es.indices.create(index='test-index', ignore=400)
```
Is the `ignore=400` the current solution here? The code above will create index if it doesn't exist, and won't raise an error if it is already there.

**Comment by gwbrown** [comment] 2021-05-06 19:47
@hosseinkalbasi That appears to be an example from the Python client, where the `ignore` parameter (and the 400 error) is handled by the Python client, not Elasticsearch itself. This issue is discussing a way to specify something in the Elasticsearch HTTP API, so that the 400 error would not be returned in the first place.

The fact that it's so easy to handle this case in the Python client may be an argument against adding this feature to Elasticsearch itself, if the error can be handled quickly and easily in our official clients.

**Comment by robertbcalhoun** [comment] 2021-05-06 21:57
@gwbrown, the code fragment posted by @hosseinkalbasi from python client "Example Use" page ignores *any* 400 error raised by the server in response to a create index request, see [perform_request in http_aiohttp.py](https://github.com/elastic/elasticsearch-py/blob/415a427db8dbe4ef31b6731eb55da39522ad753b/elasticsearch/_async/http_aiohttp.py#L328).  I would argue that the issue is easily handled in the example, only because the example is a bit sloppy. Trying to create an index called `-myillegalindex` also throws response code 400 (with body `{"type" : "invalid_index_name_exception"}`) in ES 6.8, so ignoring all 400 responses is not correct.

Most of the sample code in this ticket tests for response code 400 AND response body contains a specific exception string. This makes client code less likely to ignore a real client error, but it is also fragile code that breaks if the response body changes (as it has.)

Since this ticket has been open for 4+ years, it would appear the Elasticsearch team doesn't want to change the behavior. That is ok; API stability is worth a lot :-). It would be helpful if the team updated the [create index documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-create-index.html) with a description of how the server will respond to a request to create an index that already exists, e.g. "If the index already exists, the server will respond with HTTP response code=400 and HTTP response body containing  `{"type":"resource_already_exists_exception"}`". Then stick to it. We'll code our clients accordingly. Thank you!

**Comment by panosprotopapas** [comment] 2021-05-27 13:24
To use a more specific error-handling in Python, and avoid silencing unrelated 400 errors, one could use the following that is along the lines of what was proposed for Java/Go above.

```
from elasticsearch import Elasticsearch, TransportError

es = Elasticsearch(...)

try:
    es.indices.create(index=...)

except TransportError as e:
    if e.error != "resource_already_exists_exception" or e.status_code != 400:
        raise
```

**Comment by tiefenb** [comment] 2021-10-02 19:49
+1

**Comment by dakrone** [comment] 2024-05-08 20:45
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.

**Closed by dakrone** 2024-05-08 20:45 UTC
Labels: :Data Management/Indices APIs, Team:Data Management

**Comment by mitar** [comment] 2024-05-09 06:50
53 upvotes is not a lot of interest?

**Comment by dadoonet** [comment] 2024-05-09 08:06
With the [new Java client](https://www.elastic.co/blog/switching-from-the-java-high-level-rest-client-to-the-new-java-api-client), you can now run:

```Java
try {
    client.indices().delete(dir -> dir.index("search-data"));
} catch (ElasticsearchException ignored) { }
```

The workaround is easy so I guess that's one of the reason the team did not prioritize this over the last 8 years. 🤷🏻
