### ISSUE TITLE
[CI] Failure in org.elasticsearch.search.nested.SimpleNestedIT > testNestedSortingWithNestedFilterAsFilter

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#44486] opened 2019-07-17 10:50 UTC
This just failed in https://scans.gradle.com/s/lw7dlzisht5c4/console-log#L1144:

```
org.elasticsearch.search.nested.SimpleNestedIT > testNestedSortingWithNestedFilterAsFilter FAILED
java.lang.AssertionError: Count is 1 hits but 2 was expected.  Total shards: 6 Successful shards: 6 & 0 shard failures:
at __randomizedtesting.SeedInfo.seed([FBD52EABAFDD414B:3F6AF143B17D618A]:0)
at org.junit.Assert.fail(Assert.java:88)
at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertHitCount(ElasticsearchAssertions.java:254)
at org.elasticsearch.search.nested.SimpleNestedIT.testNestedSortingWithNestedFilterAsFilter(SimpleNestedIT.java:1329)
REPRODUCE WITH: ./gradlew :server:integTest --tests "org.elasticsearch.search.nested.SimpleNestedIT.testNestedSortingWithNestedFilterAsFilter" -Dtests.seed=FBD52EABAFDD414B -Dtests.security.manager=true -Dtests.locale=mgo-CM -Dtests.timezone=Asia/Chita -Dcompiler.java=12 -Druntime.java=11
```

Does not reproduce locally and it's the first time I'm seeing this so not muting.

**Comment by mayya-sharipova** [comment] 2019-07-24 14:07
I am puzzled about what caused this test failure. This seems to be not related to the test, but rather a problem of indexing/searching. 
2 docs were supposed to be indexed, and these 2 docs were supposed to be found during search, but only 1 was found 

[2019-07-17T19:37:18,499][INFO ][o.e.c.m.MetaDataCreateIndexService] [node_s2] [test] creating index, cause [api], templates [random_index_template], shards [6]/[1], mappings [type]
[2019-07-17T19:37:19,030][INFO ][o.e.c.r.a.AllocationService] [node_s2] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[test][4]]]). 

I have added a PR: https://github.com/elastic/elasticsearch/pull/44815 to assure that indexing was successful

**Comment by markharwood** [comment] 2019-09-11 10:47
I took another look at this too. 
Did not reproduce after many iterations and I also cannot see why indexing would have failed previously (a little worrying).
Maybe this can close now that we have the additional assertion in place to check for indexing failures in the test?

**Comment by mayya-sharipova** [comment] 2019-10-22 20:17
I agree with Mark. There were not failures of this test anymore,  I could not reproduce it locally running multiple times, and with additional assertion, we are confident enough to close this issue.

**Closed by mayya-sharipova** 2019-10-22 20:17 UTC
Labels: :Search/Search, >test-failure
