### ISSUE TITLE
ECK - Failed to deserialize response from handle when upgrade from 7.10 to 7.11

### ISSUE THREAD

**Issue by hungnguyen-elastic** [elastic/elasticsearch#66625] opened 2020-12-18 18:43 UTC
**Elasticsearch version** (`bin/elasticsearch --version`):
7.10.0-c650b297 -->  7.11.0-710164a0
**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):
ECK
**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. Run cluster with BC version - 7.10.0-c650b297
 2. Upgrade to BC version - 7.11.0-710164a0
 3. manifest file
 
 ```---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: hungnguyen
spec:
  secureSettings:
  - secretName: "gcs-credentials"
  version: 7.11.0
  nodeSets:
  - name: master
    count: 3
    podTemplate:
      spec:
        imagePullSecrets:
          - name: regcred
        containers:
        - name: elasticsearch
          image: docker.elastic.co/staging/elasticsearch:7.11.0-710164a0
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        - name: install-plugins
          command:
          - sh
          - -c
          - |
            ES_JAVA_OPTS="-Des.plugins.staging=710164a0" bin/elasticsearch-plugin install --batch repository-gcs
          env:
            - name: ES_JAVA_OPTS
              value: -Xms4g -Xmx4g
    config:
      node.master: true
      node.data: false
      node.ingest: false
      node.ml: false
  - name: data
    count: 3
    podTemplate:
      spec:
        imagePullSecrets:
          - name: regcred
        containers:
        - name: elasticsearch
          image: docker.elastic.co/staging/elasticsearch:7.11.0-710164a0
          env:
          - name: ES_JAVA_OPTS
            value: -Xms10g -Xmx10g
          resources:
            requests:
              memory: 20Gi
              cpu: 0.5
            limits:
              memory: 20Gi
              cpu: 2
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        - name: install-plugins
          command:
          - sh
          - -c
          - |
            ES_JAVA_OPTS="-Des.plugins.staging=710164a0" bin/elasticsearch-plugin install --batch repository-gcs
    config:
      node.master: false
      node.data: true
      node.ingest: true
      node.ml: true
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: standard
```

**Provide logs (if relevant)**:
{"type": "server", "timestamp": "2020-12-18T18:43:14,365Z", "level": "WARN", "component": "o.e.d.HandshakingTransportAddressConnector", "cluster.name": "hungnguyen", "node.name": "hungnguyen-es-data-2", "message": "handshake failed for [connectToRemoteMasterNode[10.192.7.6:9300]]",
"stacktrace": ["org.elasticsearch.transport.RemoteTransportException: [Failed to deserialize response from handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.action.ActionListenerResponseHandler@3ec6cc98/org.elasticsearch.transport.TransportService$5@735c54e5]]",
"Caused by: org.elasticsearch.transport.TransportSerializationException: Failed to deserialize response from handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.action.ActionListenerResponseHandler@3ec6cc98/org.elasticsearch.transport.TransportService$5@735c54e5]",
"at org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:237) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:133) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:89) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:700) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:142) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:117) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:82) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74) ~[?:?]",
"at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]",
"at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]",
"at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]",
"at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271) ~[?:?]",
"at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]",
"at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]",
"at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]",
"at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1518) ~[?:?]",
"at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1267) ~[?:?]",
"at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1314) ~[?:?]",
"at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) ~[?:?]",
"at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440) ~[?:?]",
"at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[?:?]",
"at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]",
"at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]",
"at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]",
"at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[?:?]",
"at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]",
"at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]",
"at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[?:?]",
"at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[?:?]",
"at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[?:?]",
"at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615) ~[?:?]",
"at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578) ~[?:?]",
"at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[?:?]",
"at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[?:?]",
"at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]",
"at java.lang.Thread.run(Thread.java:832) [?:?]",
"Caused by: java.lang.IllegalStateException: unexpected byte [0x15]",
"at org.elasticsearch.common.io.stream.StreamInput.readBoolean(StreamInput.java:578) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at org.elasticsearch.common.io.stream.StreamInput.readBoolean(StreamInput.java:568) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at org.elasticsearch.cluster.node.DiscoveryNode.<init>(DiscoveryNode.java:273) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at org.elasticsearch.common.io.stream.StreamInput.readOptionalWriteable(StreamInput.java:1013) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at org.elasticsearch.transport.TransportService$HandshakeResponse.<init>(TransportService.java:599) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at org.elasticsearch.transport.TransportService.lambda$handshake$8(TransportService.java:521) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at org.elasticsearch.action.ActionListenerResponseHandler.read(ActionListenerResponseHandler.java:69) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at org.elasticsearch.action.ActionListenerResponseHandler.read(ActionListenerResponseHandler.java:36) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1280) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1267) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1280) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1267) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:234) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:133) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:89) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:700) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:142) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:117) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:82) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74) ~[?:?]",
"at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]",
"at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]",
"at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]",
"at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271) ~[?:?]",
"at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]",
"at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]",
"at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]",
"at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1518) ~[?:?]",
"at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1267) ~[?:?]",
"at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1314) ~[?:?]",
"at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) ~[?:?]",
"at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440) ~[?:?]",
"at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[?:?]",
"at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]",
"at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]",
"at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]",
"at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[?:?]",
"at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]",
"at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]",
"at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[?:?]",
"at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[?:?]",
"at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[?:?]",
"at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615) ~[?:?]",
"at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578) ~[?:?]",
"at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[?:?]",
"at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[?:?]",
"at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]",
"at java.lang.Thread.run(Thread.java:832) ~[?:?]"] }

**Comment by jtibshirani** [comment] 2020-12-18 19:56
I tagged the core infra team because the failing line seems related to this PR: #64324. 

> 1. Run cluster with BC version - 7.10.0-c650b297
> 2. Upgrade to BC version - 7.11.0-710164a0

To double-check: are you upgrading from an officially released version, or a build candidate? It'd be good to rule out issues caused by upgrading from a build candidate, which we don't support.

**Comment by hungnguyen-elastic** [comment] 2020-12-18 19:59
I upgraded from a build candidate.

**Comment by jtibshirani** [comment] 2020-12-18 20:01
Got it, could you try the same reproduction steps but using the released version of 7.10.0? If it doesn't reproduce then we can close out this issue.

**Comment by hungnguyen-elastic** [comment] 2020-12-18 20:35
Gotcha, I have been trying to get it to the official release version of 7.10.0 but the change cannot be deployed to all of the cluster as this one pod is getting stuck with the config of the 7.11.0 upgrade. Since this one pod is stuck, ECK won't deploy any changes to the rest of the cluster. DO you know how I can get out of this? I have tried to delete the pod but that didn't help

**Comment by hungnguyen-elastic** [comment] 2020-12-18 21:15
I got it working by deleting the volume on the volume of the corrupted node and the whole cluster is now in version 7.11.0

**Comment by jtibshirani** [comment] 2020-12-18 21:18
Thanks @hungnguyen-elastic, I'll close this out as it seems like the upgrade worked.

**Comment by hungnguyen-elastic** [comment] 2020-12-18 21:18
Thank you Julie

**Closed by jtibshirani** 2020-12-18 21:18 UTC
Labels: :Core/Infra/Core, >bug, Team:Core/Infra
