### ISSUE TITLE
Cannot start Elasticsearch 5.4.0 on Windows when path contains parentheses

### ISSUE THREAD

**Issue by faraazaamir** [elastic/elasticsearch#24712] opened 2017-05-16 12:34 UTC
**Elasticsearch version**: 5.4.0

**Plugins installed**: []

**JVM version** (`java -version`): jre1.8.0_131

**OS version** (`uname -a` if on a Unix-like system): Windows 7 Enterprise

**Description of the problem including expected versus actual behavior**:
I have followed the steps outlined for installing elasticsearch on my machine. On clicking on elasticsearch.bat, a black command screen appears for a fraction of a second and disappears. I navigate to http://localhost:9200 and there's nothing. 
I am just starting to evaluate elasticsearch and its frustrating to not even get past the install.

My JAVA_HOME is C:\Program Files (x86)\Java\jre1.8.0_131

Please advise. 

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by danielmitterdorfer** [comment] 2017-05-16 13:00
Hi @faraazaamir, we reserve Github for bug reports and feature requests only. Please ask questions like these in the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch) instead. Thank you!

As a hint: I guess Elasticsearch is terminating due to some problem that is specific to your machine. You should not double-click on the `.bat` file but instead open a terminal (`cmd.exe`) and start the `elasticsearch.bat` file from there. By doing it this way you should be able to see the error. Alternatively, you can also inspect the log files in the `logs` directory of Elasticsearch.

**Comment by faraazaamir** [comment] 2017-05-16 13:42
Thanks for the suggestion.
I also had to follow the steps mentioned in the below to get it working:
http://stackoverflow.com/questions/40973584/installing-elasticsearch-5-0-2-on-windows-8-config-jvm-options-was-unexpecte

**Comment by danielmitterdorfer** [comment] 2017-05-16 13:50
If I read that correctly, the "fix" was to modify the batch file (bad idea). The problem is that this user (and probably also you) started Elasticsearch from the `bin` directory. However, Elasticsearch should always be started from its home directory. So instead of invoking `elasticsearch.bat` in `bin`, you should just go the home directory and invoke `.\bin\elasticsearch.bat` (as mentioned in the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/windows.html#windows-running)).

**Comment by faraazaamir** [comment] 2017-05-17 06:43
I reverted the change and tried per your suggestion:
C:\Program Files (x86)\ElasticSearch\elasticsearch-5.4.0>.\bin\elasticsearch.bat

Got the same error:
\ElasticSearch\elasticsearch-5.4.0\bin\\..\config\jvm.options was unexpected at
this time.

So the workaround mentioned in the stackoverflow link is needed unless you have any other suggestions on what I might have done wrong.

**Comment by danielmitterdorfer** [comment] 2017-05-17 09:04
@faraazaamir The problem is that you have spaces in your path. This will be fixed with https://github.com/elastic/elasticsearch/pull/24731 (will probably be included in Elasticsearch 5.4.2).

**Comment by jasontedor** [comment] 2017-05-17 10:22
> The problem is that you have spaces in your path.

To be very clear, the problem is multiple spaces, not a single space (we test all of our builds with paths that include a space).

@faraazaamir You can immediately workaround this issue by installing a 64-bit JDK in a path with a single space (you have two spaces in `Program Files (x86)`.

**Comment by jasontedor** [comment] 2017-05-17 10:43
> Have we tried to reproduce this?

After discussion with @russcam, the issue is *parentheses* in the path, not the spaces. You can workaround this right now by removing the parentheses from your install path for Elasticsearch.

**Closed** 2017-05-17 11:22 UTC
Labels: :Packaging, bug

**Comment by jasontedor** [comment] 2017-05-17 11:23
This will be fixed in 5.4.1.

**Comment by faraazaamir** [comment] 2017-05-18 10:00
Hi,

I was able to run the bat file without changes once I changed my directory structure to not have any spaces.

Thanks all for your help.
