### ISSUE TITLE
[CI] JdbcPreparedStatementTests.testSettingSqlDateValues failed

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#49287] opened 2019-11-19 10:08 UTC
The test JdbcPreparedStatementTests.testSettingSqlDateValues failed today on CI:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/os=windows-2019/271/console
https://gradle-enterprise.elastic.co/s/dmoo2wymftgek

It reproduces with:
```
gradlew ':x-pack:plugin:sql:jdbc:test' --tests "org.elasticsearch.xpack.sql.jdbc.JdbcPreparedStatementTests.testSettingSqlDateValues" \
  -Dtests.seed=F472B1A0476B4075 \
  -Dtests.security.manager=true \
  -Dtests.locale=ar \
  -Dtests.timezone=Asia/Dacca \
  -Dcompiler.java=12
```

**Comment by matriv** [comment] 2020-02-04 18:19
I'm closing this since it cannot be reproduced since master has moved to Java 13.
It cannot also be reproduced in branches 7.x, 7.6, 7.5 and 6.8 with various combinations 
of java compiler vs runtime configs.
Probably it had to do with some older jvm 12 with out-of-date tz data for the involved timezones:
apart from the system timezome `Asia/Dacca` the `America/Santiago` is used in the test (randomCalendar()). Also check discussion in #50035 where something relevant was discovered.

**Closed by matriv** 2020-02-04 18:19 UTC
Labels: :Search/SQL, >test-failure, v8.0.0
