### ISSUE TITLE
ESQL: Improve performance for queries with small limit across large clusters

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#103369] opened 2023-12-13 02:40 UTC
### Description

`from x | limit 100` should be fast regardless of how big or small the underlying cluster is.
Currently, that is not the case for big clusters since we end up performing a topN despite throwing away N-1 results.
As there's no sorting, we should optimize the query to be blazing fast.

We've identified two main areas to explore:
- [ ] improve the usage of field_caps (both for requests and response)
- [ ] significantly limit the amount of broadcasting from all shards to just a small handful.

**Comment by nik9000** [comment] 2024-01-31 19:07
So I spun up a 5 node cluster - 4 data, 1 master - and ran our [`elastic/logs`](https://github.com/elastic/rally-tracks/tree/master/elastic/logs) track against it with a [configuration](https://gist.github.com/nik9000/d9be9a22e9075d4223c9284012214678) so it'd make 5,000 tiny indices and some real ones. Then I ran `FROM *` in a `while true` loop. It clocked in around 0.6 seconds pretty consistently. That's not nearly as scientific as extending the rally track but it's easier.

When I ran the async profiler on the coordinating node I got this:

![many_small_indices](https://github.com/elastic/elasticsearch/assets/215970/d4111f61-f3d8-4483-84f2-08e27ae583e3)

I annotated that in gimp because I don't know how computers work. ES|QL proper is about 23% of the request an field caps is about 55%. The rest seems like netty doing things - probably rendering ES|QL - and us getting search shards. I presume for ES|QL. But, either way, I know the big slow thing here is field caps. And that just gets worse and worse and worse with a larger number of indices.

I'm going to run another test, this time with 50,000 indices and see where we fall, but I think it might be time for us to do something about field caps.

I know this issue was initially to do fancier optimizations when you are just doing simple queries, but those optimizations are attacking the 25% or 30% of the runtime. Not the 55%.

**Comment by abatsakis** [comment] 2024-01-31 19:24
yeah this is crazy expensive. I thought we made some improvements there. Is this after the improvements?

**Comment by nik9000** [comment] 2024-01-31 19:40
This is based on the master branch. I'm looking at what we can. More improvements? Something else. Not sure yet.

**Comment by dnhatn** [comment] 2024-01-31 19:55
We optimized by sending fewer fields and here we are requesting all fields unfortunately.

**Comment by nik9000** [comment] 2024-01-31 21:53
Small update - I can't reproduce my graph locally. It looks to me like that was a bit of a fluke around distributed execution. That isn't to say it's wrong - just that in other scenarios it'll look different. I'm still mapping.

**Comment by nik9000** [comment] 2024-02-01 15:48
I double checked my results this morning on a 50,000 index cluster. this time I got a load average and flamegraph for every node. And I was indeed right the first time - the field caps request is super slow. It turns out that we might be able to dodge most of the work. See, field_caps tries to group by field, and then ESQL then re-groups by index. If we reach into the "raw" results from field caps we can group by index ourselves. That's something I could do without any backwards compatibility problems and *should* replace that big blob with something much smaller. how much smaller I don't know, but I'll update in a bit.

**Comment by nik9000** [comment] 2024-02-02 21:01
I opened #105067 which zaps pretty much all of the field caps time and #105088 which speeds up serialization of results - that's the orange tower on the right. That should drop 5,000 indices well under 100ms and 50,000 indices well under 500ms. There's more to do to make all these more efficient though. I expect we can change the cost of field caps from being per-index to being per-unique mapping.

**Comment by nik9000** [comment] 2024-02-02 21:13
> and 50,000 indices well under 500ms

More like under 700ms. Still much better than before, but nowhere near ok. This is, after all, pure overhead, no matter how complex the query is. We really need to squeeze this down to almost nothing, especially for simple cases like this.

**Comment by dnhatn** [comment] 2024-03-04 17:26
Do the target indices have different mappings, or are they almost identical? Field-caps leverage mapping hash to reduce the workload for indices with identical mappings.

**Comment by nik9000** [comment] 2024-03-04 21:43
> Do the target indices have different mappings, or are they almost identical? Field-caps leverage mapping hash to reduce the workload for indices with identical mappings.

Yeah! Field caps uses a hash for identical mappings and we use it in our code for the merges. What I saw when I last looked was the field caps dispatch and security mechanism is hitting us here. I was thinking we *could* dispatch to one index per mapping hash instead of all matching indexes. The trick is that we have to make sure not to leak any extra information that security would not permit. That's a bit more integration with security than most of our stuff does.

**Comment by dnhatn** [comment] 2024-03-04 22:55
> Yeah! Field caps uses a hash for identical mappings and we use it in our code for the merges. What I saw when I last looked was the field caps dispatch and security mechanism is hitting us here. I was thinking we could dispatch to one index per mapping hash instead of all matching indexes. The trick is that we have to make sure not to leak any extra information that security would not permit. That's a bit more integration with security than most of our stuff does.

We've considered this before, but never implemented it. In terms of security, I think it should be okay since we've already checked it in the parent field-caps transport action.

**Comment by nik9000** [comment] 2024-03-05 16:36
I was thinking we'd avoid the top level filtering from security by having ESQL do the filtering down to a single index per hash. Or something.

**Comment by dnhatn** [comment] 2024-03-06 19:10
I haven't tested it, but we might have issues with field-level security if we're sending only one index per mapping hash. This could also be a problem with the existing code, where we retrieve fields one index per mapping hash.

**Comment by nik9000** [comment] 2024-04-10 18:58
We're pretty ok with where we are for 8.14 so I'm going to close this. But we'll pick it up again before long.

**Closed by nik9000** 2024-04-10 18:58 UTC
Labels: >enhancement, Team:Analytics, :Analytics/ES|QL
