### ISSUE TITLE
[CI] QueryStringWithAnalyzersIT.testCustomWordDelimiterQueryString MasterNotDiscoveredException

### ISSUE THREAD

**Issue by kingherc** [elastic/elasticsearch#93626] opened 2023-02-09 09:21 UTC
### CI Link

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.17+multijob+platform-support-unix/os=amazon-2&&immutable/840/consoleFull

### Repro line

./gradlew ':modules:analysis-common:internalClusterTest' --tests "org.elasticsearch.analysis.common.QueryStringWithAnalyzersIT.testCustomWordDelimiterQueryString" -Dtests.seed=89B7B641553FEE75 -Dtests.locale=es-CR -Dtests.timezone=Asia/Makassar -Druntime.java=8

### Does it reproduce?

Didn't try

### Applicable branches

7.17

### Failure excerpt

```
10:58:09 > Task :modules:analysis-common:internalClusterTest
10:58:09 
10:58:09 
10:58:09 org.elasticsearch.analysis.common.QueryStringWithAnalyzersIT > testCustomWordDelimiterQueryString FAILED
10:58:09     MasterNotDiscoveredException[null]
10:58:09         at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.onTimeout(TransportMasterNodeAction.java:297)
10:58:09         at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:345)
10:58:09         at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:263)
10:58:09         at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:660)
10:58:09         at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:718)
10:58:09         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
10:58:09         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
10:58:09         at java.lang.Thread.run(Thread.java:748)
10:58:09 
10:58:09     MasterNotDiscoveredException[null]
10:58:09         at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.onTimeout(TransportMasterNodeAction.java:297)
10:58:09         at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:345)
10:58:09         at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:263)
10:58:09         at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:660)
10:58:09         at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:718)
10:58:09         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
10:58:09         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
10:58:09         at java.lang.Thread.run(Thread.java:748)
10:58:09 REPRODUCE WITH: ./gradlew ':modules:analysis-common:internalClusterTest' --tests "org.elasticsearch.analysis.common.QueryStringWithAnalyzersIT.testCustomWordDelimiterQueryString" -Dtests.seed=89B7B641553FEE75 -Dtests.locale=es-CR -Dtests.timezone=Asia/Makassar -Druntime.java=8
10:58:09 
```

Assigned to Search based on PR https://github.com/elastic/elasticsearch/pull/23614/files that introduced the test.

**Comment by romseygeek** [comment] 2023-04-21 10:25
Unfortunately the build scan for this failure is long gone so we can't get any more details.  The test isn't doing anything particularly funky with cluster set up (it's just a simple ESIntegTestCase) so I suspect this was caused by something elsewhere.  It wasn't muted and hasn't failed since, so I think we can close this for now and reopen if it happens again.

**Closed by romseygeek** 2023-04-21 10:25 UTC
Labels: :Search/Analysis, >test-failure, Team:Search
