### ISSUE TITLE
Delete snapshot not able to interrupt shard level operation due to Azure client call hanging

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#12567] opened 2015-07-30 19:29 UTC
Have a scenario where a delete snapshot is not able to interrupt the shard level request. The snapshot state shows aborted, with 1 shard still in started status:

```
{
  "snapshots" : [ {
    "snapshot" : "20150728t111647z",
    "repository" : "snapshot",
    "state" : "ABORTED",
    "shards_stats" : {
      "initializing" : 0,
      "started" : 1,
      "finalizing" : 0,
      "done" : 129,
      "failed" : 0,
      "total" : 130
    },
```
Shard in started status except that processed_size_in_bytes hasn't moved in >1 day.

```
        "shards" : {
          "0" : {
            "stage" : "STARTED",
            "stats" : {
              "number_of_files" : 110,
              "processed_files" : 87,
              "total_size_in_bytes" : 2486849879,
              "processed_size_in_bytes" : 1493448551,
              "start_time_in_millis" : 1438082207888,
              "time_in_millis" : 0
            },
```

The hot threads is showing the snapshot thread stuck due to an Azure client call:

```
   0.0% (0s out of 500ms) cpu usage by thread 'elasticsearch[ESNode-ElasticSearchData_IN_2][snapshot][T#196]'
     10/10 snapshots sharing following 25 elements
       java.net.SocketInputStream.socketRead0(Native Method)
       java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
       java.net.SocketInputStream.read(SocketInputStream.java:170)
       java.net.SocketInputStream.read(SocketInputStream.java:141)
       java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
       java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
       java.io.BufferedInputStream.read(BufferedInputStream.java:345)
       sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:704)
       sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
       sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1535)
       sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
       java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
       com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:124)
       com.microsoft.azure.storage.blob.CloudBlockBlob.commitBlockList(CloudBlockBlob.java:244)
       com.microsoft.azure.storage.blob.BlobOutputStream.commit(BlobOutputStream.java:321)
       com.microsoft.azure.storage.blob.BlobOutputStream.close(BlobOutputStream.java:285)
       org.elasticsearch.cloud.azure.blobstore.AzureOutputStream.close(AzureOutputStream.java:41)
       org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository$SnapshotContext.snapshotFile(BlobStoreIndexShardRepository.java:559)
       org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository$SnapshotContext.snapshot(BlobStoreIndexShardRepository.java:500)
       org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository.snapshot(BlobStoreIndexShardRepository.java:140)
       org.elasticsearch.index.snapshots.IndexShardSnapshotAndRestoreService.snapshot(IndexShardSnapshotAndRestoreService.java:85)
       org.elasticsearch.snapshots.SnapshotsService$5.run(SnapshotsService.java:852)
       java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       java.lang.Thread.run(Thread.java:745)
```

Is there a way to handle this situation better when the Azure call hangs so that the delete snapshot can successfully interrupt the outstanding (but stuck) shard request?

**Comment by clintongormley** [comment] 2015-08-05 10:35
This is a problem in the Azure client itself.  Threads do not timeout by default and so the only way to interrupt the thread is to restart the node.  There are two timeouts available:

`setMaximumExecutionTimeInMs`

The maximum execution time interval begins at the time that the client begins building the request. The default maximum execution is set in the client and is by default null, indicating no maximum time.

`setTimeoutIntervalInMs`

Sets the timeout to use when making this request. The default server timeout is set in the client and is by default null, indicating no server timeout.

See http://dl.windowsazure.com/storage/javadoc/com/microsoft/azure/storage/RequestOptions.html for full description.

We should probably do the following:

* expose the timeout settings
* check how they are *really* used by the Azure client depending of the type of request (max. operation time seems to be checked in between 2 request retries but I'm not sure)
* check that delete command leaves the snapshot in a coherent state if a timeout happen
* add some docs about it

**Comment by dadoonet** [comment] 2016-01-14 08:20
> `setTimeoutIntervalInMs`
>
> Sets the timeout to use when making this request. The default server timeout is set in the client and is by default null, indicating no server timeout.

`setTimeoutIntervalInMs` has been implemented in #15080. 

> We should probably do the following:
> 
> * expose the timeout settings

Done. See https://github.com/elastic/elasticsearch/pull/15080/files#diff-e1e28473441a5cb9762b0176ddc4d22bR126

> * check how they are *really* used by the Azure client depending of the type of request (max. operation time seems to be checked in between 2 request retries but I'm not sure)

That seems to still be an issue. According to recent reports with the support team, it looks like that even after 5 minutes, Azure client does not stop and raise an exception...

> * check that delete command leaves the snapshot in a coherent state if a timeout happen

@imotov could comment on what would happen if the azure client raises an exception.

> * add some docs about it

Done in #15080. https://www.elastic.co/guide/en/elasticsearch/plugins/master/repository-azure-usage.html

I wonder if we should implement `setMaximumExecutionTimeInMs ` instead? @craigwi WDYT? Should we use this instead of `setTimeoutIntervalInMs`? Or may be there is an issue in the azure client?

**Comment by craigwi** [comment] 2016-01-14 21:02
Hi @dadoonet, this service request came from us and I just now looked at the details.  As far as I can tell, the problem is that I did not pass the BlobRequestOptions to the calls to openInputStream() and openOutputStream() (in AzureStorageServiceImpl.java).

I had assumed that the options on the CloudBlobClient would be inherited by all containers and blobs referenced by it, but the evidence here is that the timeout option, at least, does not get passed through.

I am going to change my fork of the plugin and make the two calls looks like:

        return client.getContainerReference(container).getBlockBlobReference(blob).openInputStream(null, client.getDefaultRequestOptions(), null);

and 

        return client.getContainerReference(container).getBlockBlobReference(blob).openOutputStream(null, client.getDefaultRequestOptions(), null);

The middle parameter is the key addition, of course.

I'll verify and let you know.

Craig.

**Comment by dadoonet** [comment] 2016-01-14 21:07
Fantastic !

**Comment by dadoonet** [comment] 2016-01-15 10:32
@craigwi I looked at the azure client code and found that when you call `openOutputStream()`, it calls `openOutputStream(null, null /* options */, null)`.

Options are then populated by calling `options = BlobRequestOptions.applyDefaults(options, BlobType.BLOCK_BLOB, this.blobServiceClient, false)` which does:

```java
    protected static final BlobRequestOptions applyDefaults(final BlobRequestOptions options, final BlobType blobType,
            final CloudBlobClient client, final boolean setStartTime) {
        BlobRequestOptions modifiedOptions = new BlobRequestOptions(options);
        BlobRequestOptions.populateRequestOptions(modifiedOptions, client.getDefaultRequestOptions(), setStartTime);
        return BlobRequestOptions.applyDefaultsInternal(modifiedOptions, blobType, client, setStartTime);
    }
```

`BlobRequestOptions.populateRequestOptions` then calls `RequestOptions.populateRequestOptions` which does:

```java
    protected static final RequestOptions populateRequestOptions(RequestOptions modifiedOptions,
            final RequestOptions clientOptions, final boolean setStartTime) {
        // ...
        if (modifiedOptions.getTimeoutIntervalInMs() == null) {
            modifiedOptions.setTimeoutIntervalInMs(clientOptions.getTimeoutIntervalInMs());
        }

        if (modifiedOptions.getMaximumExecutionTimeInMs() == null) {
            modifiedOptions.setMaximumExecutionTimeInMs(clientOptions.getMaximumExecutionTimeInMs());
        }

        if (modifiedOptions.getMaximumExecutionTimeInMs() != null
                && modifiedOptions.getOperationExpiryTimeInMs() == null && setStartTime) {
            modifiedOptions.setOperationExpiryTimeInMs(new Date().getTime()
                    + modifiedOptions.getMaximumExecutionTimeInMs());
        }

        return modifiedOptions;
    }
```


So to me your initial assumption is correct. The default client options are applied here.
I don't think that passing `client.getDefaultRequestOptions()` will change anything here unless I'm missing something.

May be it's a bug elsewhere?

**Comment by dadoonet** [comment] 2016-01-15 11:00
@craigwi so I created a simple test case and looked in debug mode at what is happening on the azure client:

```java
public void testDumb() throws URISyntaxException, StorageException {
    CloudStorageAccount storageAccount = CloudStorageAccount.getDevelopmentStorageAccount();
    CloudBlobClient client = storageAccount.createCloudBlobClient();
    client.getDefaultRequestOptions().setTimeoutIntervalInMs(10000);
    client.getContainerReference("dumb").getBlockBlobReference("blob").openOutputStream();
}
```

Options are correctly updated.

<img width="607" alt="blobrequestoptions java - elasticsearch - -documents-elasticsearch-dev-es-gradle-elasticsearch intellij idea aujourd hui at 11 44 32" src="https://cloud.githubusercontent.com/assets/274222/12351644/6795ecee-bb7f-11e5-8371-a7a92f69b6ae.png">

I looked at the `BlobOutputStream` and the root problem is that actually the azure client does not use at all this time out setting.
This setting is only used by `BlobRequest` which we are not using.

<img width="1084" alt="intellij idea intellij idea aujourd hui at 11 50 50" src="https://cloud.githubusercontent.com/assets/274222/12351651/73fb24a4-bb7f-11e5-8ff1-1349e2199299.png">

So I believe that the change we have to do is bigger than what we did until now. I think it's time to implement #12448 which would use not Azure Input/Output Streams but `StorageRequest` or `BlobRequest`. I'll look at the Azure storage client examples unless you find another idea in the meantime.

**Comment by dadoonet** [comment] 2016-01-15 13:29
I looked at the other parts of the Azure client code and I found only one case where the `RequestOptions` is used:

In `CloudBlockBlob.upload`:

```java
        // If the stream is rewindable, and the length is known and less than
        // threshold the upload in a single put, otherwise use a stream.
        if (sourceStream.markSupported() && descriptor.getLength() != -1
                && descriptor.getLength() < options.getSingleBlobPutThresholdInBytes() + 1) {
            this.uploadFullBlob(sourceStream, descriptor.getLength(), accessCondition, options, opContext);
        }
```

But when you use directly a stream, `RequestOptions` are not used.. 

So the only short-term workaround I can see is by using the `upload` method and make sure we enter that code bloc.

I opened https://github.com/Azure/azure-storage-java/issues/71.

**Comment by imotov** [comment] 2016-01-15 16:10
>> check that delete command leaves the snapshot in a coherent state if a timeout happen

> @imotov could comment on what would happen if the azure client raises an exception.

The problem here is not in a timeout during a delete command. The problem is in absence of a timeout while writing a file to azure. The delete operation first makes sure that a snapshot that a user is trying to delete is not currently running, and if the snapshot is running the delete operation tries to cancel it. The cancellation process sends an abort message to all shards involved in the snapshot and waits for all shards to stop writing. The source of the problem is that one of the shards cannot stop writing because it's forever stuck in the write operation. If we will add the write operation timeout, it will resolve the core issue - the abort operation will not get stuck for more then the timeout interval and therefore will be easily cancellable. Moreover, it will help to eliminate the need to delete a stuck snapshot to start with, since the snapshot will not get stuck waiting for a write to finish in the first place. Instead it will just fail the snapshot for the shard that got stuck and move on.

**Comment by craigwi** [comment] 2016-01-17 20:05
guys, per the post I made on azure-storage-java (https://github.com/Azure/azure-storage-java/issues/71), the primary issue (lack of timeout) is due to a bug in an old version of com.microsoft.azure.storage.  We need to use version 3.0.0 or newer.

**Comment by craigwi** [comment] 2016-01-19 04:28
I updated my version of the cloud azure plugin to use azure-storage-java v3.1: https://github.com/craigwi/elasticsearch-cloud-azure/releases/tag/v2.8.4-craigwi.  I picked v3.1 because v4.0.0 looked to have a larger scope of changes and more risk.  So far, my tests, including frequent snapshots and restores, appear to be successful.

Craig.

**Comment by dadoonet** [comment] 2016-01-19 12:46
@craigwi It sounds like we should set `client.getDefaultRequestOptions().setMaximumExecutionTimeInMs(timeout);` 
In that case, we will have a better control from elasticsearch when something goes wrong and takes too much time.

WDYT?

I wonder if we should set both timeouts or only `setMaximumExecutionTimeInMs`?
I guess that `setMaximumExecutionTimeInMs` would be enough.

**Closed** 2016-01-19 17:03 UTC
Labels: :Plugin Cloud Azure, :Snapshot/Restore
