### ISSUE TITLE
Build failing with "Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0"

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#94152] opened 2023-02-27 13:20 UTC
### CI Link

https://gradle-enterprise.elastic.co/s/my6rc7uh3xfji

### Repro line

none

### Does it reproduce?

No

### Applicable branches

8.7

### Failure excerpt

Not sure where to look for more details in the log but this might be relevant https://gradle-enterprise.elastic.co/s/my6rc7uh3xfji/deprecations?expanded=WyI0Il0

**Comment by pgomulka** [comment] 2023-03-22 12:46
https://gradle-enterprise.elastic.co/s/xhjojj73a6xcs/failure?expanded-stacktrace=WyIwIl0#1

```

Cannot access input property 'clusters.v7.17.10-old$0.nodes.$0.distributionFiles' of task ':qa:repository-multi-version:v7.17.10#Step3OldClusterTest' (see --info log for details). Accessing unreadable inputs or outputs has been deprecated.
```

**Comment by pgomulka** [comment] 2023-03-22 13:29
ElasticsearchNode.getDistributedFiles is annotated with InputFiles and it will contain jar files.
perhaps this is what gradle considers unreadable? 
https://docs.gradle.org/current/userguide/upgrading_version_7.html#declare_unreadable_input_output

**Comment by breskeby** [comment] 2023-03-23 07:22
usually these kind of errors are IO glitches in the ci environment. I wasn't able to reproduce that in the past. Not sure we can do much about it

**Comment by n1v0lg** [comment] 2023-04-19 10:09
Whereas before it was deprecated, it looks like now it's not supported anymore:

https://gradle-enterprise.elastic.co/s/7ivmbp45cfca4

`qa:rolling-upgrade:v8.7.1#oneThirdUpgradedTest` failed with:

```
Cannot access input property 'clusters.v8.7.1$0.nodes.$1.distributionFiles' of task ':qa:rolling-upgrade:v8.7.1#oneThirdUpgradedTest'. Accessing unreadable inputs or outputs is not supported. Declare the task as untracked by using Task.doNotTrackState(). See https://docs.gradle.org/8.1/userguide/incremental_build.html#disable-state-tracking for more details.
> java.nio.file.NoSuchFileException: /var/lib/jenkins/workspace/elastic+elasticsearch+main+multijob+platform-support-unix/distribution/bwc/bugfix/build/bwc/checkout-8.7/distribution/archives/linux-tar/build/install/elasticsearch-8.7.1-SNAPSHOT/.attach_pid299594
  > /var/lib/jenkins/workspace/elastic+elasticsearch+main+multijob+platform-support-unix/distribution/bwc/bugfix/build/bwc/checkout-8.7/distribution/archives/linux-tar/build/install/elasticsearch-8.7.1-SNAPSHOT/.attach_pid299594
```

**Comment by mark-vieira** [comment] 2023-04-21 16:21
Hmm, this actually might be an issue with used a shared distribution and tracking the distribution directory as an input. A lot of these weird errors are side effects of that fact that Elasticsearch always uses the distribution directory as the working directory depsite what you tell it. Understandibly, we didn't design distributions to be "shared" by multiple running instances but we do in testing as an optimization. Perhaps when we register the filecollection as a task input we can filter out that file?

**Comment by mark-vieira** [comment] 2023-10-04 22:01
I haven't seen an instance of this failure in the past month so I'm closing this for now.

**Closed by mark-vieira** 2023-10-04 22:01 UTC
Labels: :Delivery/Build, >test-failure, Team:Delivery
