### ISSUE TITLE
[CI] AsyncSearchActionIT.testMaxMinAggregation

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#61796] opened 2020-09-01 15:32 UTC
**Build scan**:
```
https://gradle-enterprise.elastic.co/s/5p53iiai3gvyw
```

**Repro line**:
```
./gradlew ':x-pack:plugin:async-search:internalClusterTest' --tests "org.elasticsearch.xpack.search.AsyncSearchActionIT.testMaxMinAggregation" -Dtests.seed=221ED05A04A55CEC -Dtests.security.manager=true -Dtests.locale=uk -Dtests.timezone=Africa/Lusaka -Druntime.java=11
```

**Reproduces locally?**: No

**Applicable branches**: master

**Failure history**:
https://gradle-enterprise.elastic.co/scans/tests?search.buildToolTypes=gradle&search.buildToolTypes=maven&search.relativeStartTime=P7D&search.timeZoneId=Europe/London&tests.container=org.elasticsearch.xpack.search.AsyncSearchActionIT&tests.sortField=FAILED&tests.test=testMaxMinAggregation&tests.unstableOnly=true

**Failure excerpt**:

```
java.lang.AssertionError: 
Expected: <INTERNAL_SERVER_ERROR>
     but: was <NOT_FOUND>
	at __randomizedtesting.SeedInfo.seed([E48F8EE8EC3D08E2:7D4F68AB942469D2]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.search.AsyncSearchIntegTestCase$2.doNext(AsyncSearchIntegTestCase.java:280)
	at org.elasticsearch.xpack.search.AsyncSearchIntegTestCase$2.next(AsyncSearchIntegTestCase.java:256)
	at org.elasticsearch.xpack.search.AsyncSearchIntegTestCase$2.next(AsyncSearchIntegTestCase.java:243)
	at org.elasticsearch.xpack.search.AsyncSearchActionIT.testMaxMinAggregation(AsyncSearchActionIT.java:102)
```

**Comment by andreidan** [comment] 2020-09-01 15:34
Some failure scenarios were already fixed with https://github.com/elastic/elasticsearch/pull/56026 but this test started sporadically failing again in late August

**Comment by jimczi** [comment] 2020-09-01 16:00
Duplicate of #61790, hence closing

**Closed by jimczi** 2020-09-01 16:00 UTC
Labels: :Search/Search, >test-failure, Team:Search
