### ISSUE TITLE
Log query when circuit breaker trips

### ISSUE THREAD

**Issue by jjfalling** [elastic/elasticsearch#11145] opened 2015-05-13 12:21 UTC
If a query caused a circuit breaker to trip, it would be useful to log the full query for troubleshooting purposes.

**Comment by dakrone** [comment] 2015-05-13 15:42
@jjfalling this is a great idea, it might be tricky to figure out what level we can log it at, but hopefully it is doable.

**Comment by colings86** [comment] 2015-07-28 10:13
So it looks like we can add this in to the onFailure methods of TransportSearchQueryThenFetchAction (and the equivalent for other search types) however logging the request would mean we would need to make SearchRequest and all the objects it contains (queries, aggregations, highlighters, suggesters etc.) implement ToXContent so we can re-serialise the request to JSON to include it in the response (I propose adding a setRequestSource() method to CircuitBreakingException which will add the content to the JSON response in toXContent). adding toXcontent to all these object would be a lot of work and should probably be done as part of the query re-factoring if we wanted to do it.

Alternatively, we could just support this in the REST layer, and add logic to RestSearchAction's onFailure() method to add the request JSON to the response if the caught exception is a CircuitBreakingException. Thought?

**Comment by clintongormley** [comment] 2015-07-30 10:29
What about adding this exception to the query slowlog?

**Comment by colings86** [comment] 2015-07-30 11:41
The problem isn't sending the exception somewhere, the circuitBreakerException is already sent back to the client at the moment. The problem is how to render the query in the exception because at the moment we can't convert from the SearchRequest back to the JSON. We would need to do this wherever we end up sending the exception (to the logs or to the response).

The question is whether we need to do this for the Java API? If we do, we will need the SearchRequest to be serialised to JSON which will be a lot of work as there are a lot of classes that it depends on (all queries and aggs for a start).

Another option is for the SearchRequest to keep the original JSON string around. This seems inefficient as the search request would essentially be duplicating its content (once as the JSON string and once as the requests internal state). 

The last option is to only support this in the REST layer only and have the logic in the RestSearchAction instead of the TransportSearchActions.

**Comment by dakrone** [comment] 2015-10-28 20:02
@colings86 I'm curious if this has changed any with the new query refactoring work? Is is still something that could only happen in the `RestSearchAction`?

**Comment by colings86** [comment] 2015-11-02 11:45
@dakrone yes, we should now be able to do this since with the refactoring work we have ended up implementing ToXContent on the SearchRequest object (and all its attributes).

**Comment by vineet01** [comment] 2016-06-29 13:40
No updates on it for 2.3.3?

**Comment by majormoses** [comment] 2018-03-13 21:26
bump

**Comment by rjernst** [comment] 2020-12-09 22:12
There hasn't been a huge demand for this feature in the years since it was proposed, and thus we have not prioritized it. We are not particularly opposed to it. However, I also think this is mislabeled, as it is about how the search request utilizes the circuit breakers, not any fundamental feature of circuit breakers themselves. So, instead of closing, I am relabeling this for the search team, and adding `help wanted`. I will let them decide whether this is worth keeping open.

**Comment by sbocahu** [comment] 2023-12-26 13:21
👍 would be helpful to understand where errors seen in ES-backed-app logs come from without having to reshape the whole app logging

**Comment by javanna** [comment] 2024-07-16 15:34
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.

**Closed by javanna** 2024-07-16 15:34 UTC
Labels: >enhancement, help wanted, :Search Foundations/Search
