### ISSUE TITLE
ElasticsearchException getRootCause can result in infinite loop

### ISSUE THREAD

**Issue by bdelbosc** [elastic/elasticsearch#33930] opened 2018-09-21 06:55 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): master

**Plugins installed**: []

**JVM version** (`java -version`): openjdk version "10.0.2"

**OS version** (`uname -a` if on a Unix-like system): Linux 4.15.0-33-generic

**Description of the problem including expected versus actual behavior**:

The [ElasticsearchException#getRootCause](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/ElasticsearchException.java#L264) can result in an infinite loop if there is cycle in the causes.
We run into such case because the ElasticsearchException was serialized at some point in our code.

**Steps to reproduce**:
I will create a PR
**Provide logs (if relevant)**:

**Comment by jasontedor** [comment] 2018-09-21 22:28
Would you please provide a reproduction of a case where cyclic causes can occur? We go have guards elsewhere in our code for cyclic causes, although this is a precautionary measure and I have never actually seen it in practice: https://github.com/elastic/elasticsearch/blob/67bfb765ee8b7958a4d7a26b17f653ae8955878d/server/src/main/java/org/elasticsearch/ExceptionsHelper.java#L229

**Comment by danielmitterdorfer** [comment] 2018-12-12 15:47
As I've indicated on the related PR #33932 this turns out to be a client-side topic and hence I hope you don't mind if I close this. Should there be any new information regarding this, please feel free to comment / reopen. Thank you! :)

**Closed by danielmitterdorfer** 2018-12-12 15:47 UTC
Labels: :Core/Infra/Core, feedback_needed
