### ISSUE TITLE
Failed to start es when the following warning appears

### ISSUE THREAD

**Issue by lcsin** [elastic/elasticsearch#88227] opened 2022-07-01 08:30 UTC
![image](https://user-images.githubusercontent.com/49903755/176856840-f69fb847-ff3c-4103-9166-afab1eab8102.png)

es version: 7.17.5

**Comment by DaveCTurner** [comment] 2022-07-01 12:50
Closing as a duplicate of https://github.com/elastic/elasticsearch/issues/87844

**Closed by DaveCTurner** 2022-07-01 12:50 UTC
