### ISSUE TITLE
ES not starting (possibly because of cgroup issue)

### ISSUE THREAD

**Issue by UndisputedBasement33** [elastic/elasticsearch#36989] opened 2018-12-26 11:03 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 6.5.4

**Plugins installed**: [ingest-attachment]

**JVM version** (`java -version`): 1.8.0_191

**OS version** (`uname -a` if on a Unix-like system): 4.15.0-43-generic

**Description of the problem including expected versus actual behavior**: Elasticsearch service can't be started. Probably related to [#23486](https://github.com/elastic/elasticsearch/issues/23486) and [#23218](https://github.com/elastic/elasticsearch/issues/23218)

**Steps to reproduce**: systemctl start elasticsearch 

`cat /proc/self/croup`:
```12:rdma:/
11:freezer:/
10:memory:/
9:net_cls,net_prio:/
8:blkio:/
7:perf_event:/
6:cpu,cpuacct:/
5:pids:/user.slice/user-1000.slice/session-7.scope
4:cpuset:/
3:devices:/user.slice
2:hugetlb:/
1:name=systemd:/user.slice/user-1000.slice/session-7.scope
0::/user.slice/user-1000.slice/session-7.scope
```

`cat /proc/cgroups`:
```#subsys_name	hierarchy	num_cgroups	enabled
cpuset	4	1	1
cpu	6	1	1
cpuacct	6	1	1
blkio	8	1	1
memory	10	1	1
devices	3	112	1
freezer	11	2	1
net_cls	9	1	1
perf_event	7	1	1
net_prio	9	1	1
hugetlb	2	1	1
pids	5	124	1
rdma	12	1	1
```

`mount | grep cgroup`:
```tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/rdma type cgroup (rw,nosuid,nodev,noexec,relatime,rdma)
```

Log:
```[2018-12-26T10:38:39,336][INFO ][o.e.p.PluginsService     ] [U-Ii--b] loaded plugin [ingest-attachment]
[2018-12-26T10:38:39,347][ERROR][o.e.b.Bootstrap          ] [U-Ii--b] Exception
java.lang.NullPointerException: null
	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:273) ~[?:?]
	at org.elasticsearch.common.io.PathUtils.get(PathUtils.java:60) ~[elasticsearch-core-6.5.4.jar:6.5.4]
	at org.elasticsearch.monitor.os.OsProbe.readSysFsCgroupMemoryLimitInBytes(OsProbe.java:408) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.monitor.os.OsProbe.getCgroupMemoryLimitInBytes(OsProbe.java:395) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.monitor.os.OsProbe.getCgroup(OsProbe.java:488) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.monitor.os.OsProbe.osStats(OsProbe.java:531) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.xpack.ml.MachineLearning.additionalSettings(MachineLearning.java:327) ~[?:?]
	at org.elasticsearch.plugins.PluginsService.updatedSettings(PluginsService.java:203) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.node.Node.<init>(Node.java:339) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) [elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) [elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) [elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) [elasticsearch-cli-6.5.4.jar:6.5.4]
	at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-6.5.4.jar:6.5.4]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) [elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86) [elasticsearch-6.5.4.jar:6.5.4]
[2018-12-26T10:38:39,356][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [U-Ii--b] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.NullPointerException
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:140) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.5.4.jar:6.5.4]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.5.4.jar:6.5.4]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86) ~[elasticsearch-6.5.4.jar:6.5.4]
Caused by: java.lang.NullPointerException
	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:273) ~[?:?]
	at org.elasticsearch.common.io.PathUtils.get(PathUtils.java:60) ~[elasticsearch-core-6.5.4.jar:6.5.4]
	at org.elasticsearch.monitor.os.OsProbe.readSysFsCgroupMemoryLimitInBytes(OsProbe.java:408) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.monitor.os.OsProbe.getCgroupMemoryLimitInBytes(OsProbe.java:395) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.monitor.os.OsProbe.getCgroup(OsProbe.java:488) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.monitor.os.OsProbe.osStats(OsProbe.java:531) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.xpack.ml.MachineLearning.additionalSettings(MachineLearning.java:327) ~[?:?]
	at org.elasticsearch.plugins.PluginsService.updatedSettings(PluginsService.java:203) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.node.Node.<init>(Node.java:339) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-6.5.4.jar:6.5.4]
	... 6 more
```

**Comment by atorok** [comment] 2018-12-26 15:48
@UndisputedBasement33 what Linux distribution are you using ? Any configuration specific to it that would help reproduce the problem on our end ?

**Comment by UndisputedBasement33** [comment] 2018-12-27 00:40
I'm using Ubuntu 18.04 LTS. As far as I know there is nothing specific. I'm using the standard version of Ubuntu installed with the minimal configuration running as VM in VMWare ESXi.

**Comment by danielmitterdorfer** [comment] 2019-01-09 10:53
I tried reproducing your issue by installing Elasticsearch 6.5.4 from the Debian package in an [Ubuntu 18.04 Vagrant box](https://app.vagrantup.com/elastic/boxes/ubuntu-18.04-x86_64) but the service started up successfully.

Based on the stack trace you provide it seems that some part of the path is `null` but it's hard to tell. Can you please enable assertions temporarily and attempt to restart? This should raise an assertion error at the time the problem actually occurs.

To enable assertions, you need to add the following line to `/etc/elasticsearch/jvm.options`:

```
-ea
```

Can you then please start Elasticsearch again and provide the error trace?

**Comment by UndisputedBasement33** [comment] 2019-01-09 11:46
Hi and thanks for your efforts. In the last days I was trying to solve the problem and I was able to get elasticsearch running. I uninstalled Java and installed it again and from that point on it was working. Not sure what the problem was since the java -version was the same before but at least this fixed the problem.

**Comment by danielmitterdorfer** [comment] 2019-01-11 16:17
Thank you for your feedback @UndisputedBasement33! As we were both not able to reproduce it and it works for you now I'm gonna close the issue.

**Closed by danielmitterdorfer** 2019-01-11 16:17 UTC
Labels: :Core/Infra/Core, feedback_needed
