### ISSUE TITLE
Self-adjusting shard count and rollover size in ILM policies to cluster size

### ISSUE THREAD

**Issue by chingis-elastic** [elastic/elasticsearch#63872] opened 2020-10-19 10:47 UTC
We are managing hundreds of 7.8 ES clusters of different sizes (from 3 to 90 data nodes) for various purposes. To simplify configuration management, we store all configuration in one place and apply it to all clusters. This creates dis-balance for certain parameters which require absolute values, like `index.settings.number_of_shards` or `policy.phases.hot.actions.rollover.max_size`. We ended up with a script which would regularly adjust such values to cluster size (~number of data nodes). 

It would be great if ES cluster, once configured, would have some sort of default policy of adjusting those parameters in runtime, with certain regularity. It would be also great if user could specify own values with help of placeholders like
```
{
  "index.settings.number_of_shards": "some_constant * {number_of_data_nodes}"
}

{
  "policy.phases.hot.actions.rollover.max_size": "some_another_constant * {number_of_data_nodes}"
}
```
to tailor those settings for current setup / load pattern (e.g. `some_constant` and `some_another_constant` are picked empirically).

It was mentioned by @jakelandis that this might interfere with autoscaling effort currently going on in ES

**Comment by mcpate** [comment] 2020-10-20 15:32
> It was mentioned by @jakelandis that this might interfere with autoscaling effort currently going on in ES

I would be very curious to hear from the ES team on whether this request is realistic and if so what the timeline might look like.

**Comment by jakelandis** [comment] 2020-10-22 20:48
There are two independent concepts here

>  "policy.phases.hot.actions.rollover.max_size": "some_another_constant * {number_of_data_nodes}"

Currently the max size is determined by the total of the primary shards. When you set that to say 50GB and spread across 10 primary shards, after it rolls over, your ILM policy can implement a [shrink](https://www.elastic.co/guide/en/elasticsearch/reference/master/ilm-shrink.html) in the warm phase and then after that you have an optimally sized single shard. We have discussed possibly introducing a different ways to calculate when to roll over and open to the idea if there are compelling reasons why the max total, then shrink may not be ideal. I will add the caveat that using number of nodes might be problematic since the number of nodes in a cluster can and will change, and reduces some deterministic behaviour we prefer.


> "index.settings.number_of_shards": "some_constant * {number_of_data_nodes}"

This is interesting...kinda like auto_expand replica, but for primary shards. This is the part that may overlap with auto scaling and the data_hot tier, however I am not familiar enough to speak to this. cc @jasontedor - are there any plans to associated with autoscaling that would give an auto_expand like behaviour but for primary shards ?

Outside of auto scaling, I would be curious for the highest volume index patterns you could find a lowest common denominator of shards/hosts needed across the various cluster sizes. For example, if you have a "logs-lotsostuff-*" pattern that is the heaviest write pattern (as defined by template that determines shards) if 3 primary (the fewest number of nodes across all clusters) shards are enough to handle the load for a single index/data-stream with in that pattern in the highest volume cluster. If yes, then you set to 3 primaries on all the clusters and let shrink shrink them down to a reasonable size. You might end a bit over sharded on the small cluster, but probably not so much to cause problems.

**Comment by matschaffer** [comment] 2020-10-26 02:40
> If yes, then you set to 3 primaries on all the clusters and let shrink shrink them down to a reasonable size. You might end a bit over sharded on the small cluster, but probably not so much to cause problems.

That's pretty much how we've been operating until the 7.x upgrade. Then we hit the shard limit, bumped it up, then implemented dynamic shard calculation to our index template tooling. Which is what led to this issue.

It does kinda-sorta work, but not very well. 

The issue is compounded by the scale as well. Many regions would be fine on 3 shards of primary ingest, but our largest regions need more like 50. We're also not yet doing ILM & shrink for our largest indices, so we get `50*days retention` which really overshards smaller clusters.

**Comment by chingis-elastic** [comment] 2020-10-27 11:11
> Currently the max size is determined by the total of the primary shards.

That's interesting - how exactly its determined? Does node size influence here?

**Comment by joegallo** [comment] 2020-10-30 16:34
Somewhat related to https://github.com/elastic/elasticsearch/issues/63026

**Comment by jakelandis** [comment] 2022-02-09 22:12
Closing this issue as the two independent concerns are addressed (or will be) but in a slightly different way. 

> "policy.phases.hot.actions.rollover.max_size": "some_another_constant * {number_of_data_nodes}"

This can be handled by using `max_primary_shard_size` for the [rollover](https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-rollover.html) so the number of data nodes is not required. A similar `max_primary_shard_size` is also now available in the [shrink action](https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-shrink.html) that can also be used to dynamically shrink to a specified size independent of the number of data nodes. 


> "index.settings.number_of_shards": "some_constant * {number_of_data_nodes}"

Some efforts are underway to address this via auto scaling. It is still early, but that is the preferred approach since requiring codifying the number of data nodes is a bit too brittle.

**Closed by jakelandis** 2022-02-09 22:12 UTC
Labels: >enhancement, :Data Management/Indices APIs, :Data Management/ILM+SLM, team-discuss, Team:Data Management

**Comment by matschaffer** [comment] 2022-02-10 00:53
cc @lucasmoore and @nikulinivan for cloud-o11y consideration

> This can be handled by using max_primary_shard_size...

`max_primary_shard_size` sounds like a nice way to handle the shards-too-big problem.

> Some efforts are underway to address this via auto scaling. 

Is there an issue to follow?

If I recall correctly, the main driver for `number_of_shards` adjustment is spreading ingest load appropriately in high-scale regions, we need more nodes to take part in the write workload. If the index has too few shards, it's handled by only a few nodes and the pipeline backs up despite having plenty of spare capacity in the ES cluster.

**Comment by repantis** [comment] 2022-02-10 18:58
Hi @matschaffer, thank you for raising this. I will follow up with you to share more details on autoscaling.
