### ISSUE TITLE
Searching iWork files

### ISSUE THREAD

**Issue by marbetschar** [elastic/elasticsearch#19965] opened 2016-08-11 21:06 UTC
Ran into the same issue like @kirka121 over here: https://github.com/elastic/elasticsearch-mapper-attachments/issues/210

Indexing iWorks as part of a future release would be highly appreciated.

**Comment by rmuir** [comment] 2016-08-12 14:27
I don't think there is anything we can do here: tika needs to support the format first. We enable the `IWorkPackageParser` today already.

Newer Tika has a `IWork13PackageParser`, with the idea to handle newer IWork formats, but it doesn't appear to actually be capable of parsing anything yet: https://github.com/apache/tika/blob/master/tika-parsers/src/main/java/org/apache/tika/parser/iwork/iwana/IWork13PackageParser.java

It seems at the moment, its a WIP, only capable of detecting the format, and the issue is still open (see https://issues.apache.org/jira/browse/TIKA-1358)

**Comment by marbetschar** [comment] 2016-08-12 14:47
Sad to hear that, but thanks for the feedback anyways!

**Comment by rmuir** [comment] 2016-08-12 14:54
Well, if you look at the TIKA issue, it seems people are working on it, its just not ready yet.

**Comment by clintongormley** [comment] 2016-08-12 16:46
Not much we can do here, so closing this issue

**Closed by clintongormley** 2016-08-12 16:46 UTC
Labels: :Plugin Ingest Attachment, discuss
