### ISSUE TITLE
SQL: improve aggregations' handling of more complex formulas

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#36865] opened 2018-12-19 22:10 UTC
At the moment, aggregations/groupings like MAX, AVG, MIN are able to deal with one field as parameter, but things like `AVG((salary + 10)/experience)` are also possible in an AVG aggregation in Elasticsearch through the use of a script.

If one tries to use `AVG` with something more than a simple field as parameter, the following is being returned back:

```
sql> select AVG(salary + 1) from test_emp;                                                                                                                                
Server error [Server encountered an error [Does not know how to convert argument Add[] for function Avg[]]. [SqlIllegalArgumentException[Does not know how to convert argu
ment Add[] for function Avg[]]                                                                                                                                            
        at org.elasticsearch.xpack.sql.planner.QueryTranslator.field(QueryTranslator.java:438)                                                                            
        at org.elasticsearch.xpack.sql.planner.QueryTranslator$Avgs.toAgg(QueryTranslator.java:799)                                                                       
        at org.elasticsearch.xpack.sql.planner.QueryTranslator$Avgs.toAgg(QueryTranslator.java:795)                                                                       
        at org.elasticsearch.xpack.sql.planner.QueryTranslator$SingleValueAggTranslator.asAgg(QueryTranslator.java:883)                                                   
```

In general aggregations cannot be applied on top of any scalar function, another example:
```
SELECT gender AS g, SUM(ABS(emp_no)) AS "sum"
FROM test_emp
GROUP BY 1;
```

This was reported via our forum [here](https://discuss.elastic.co/t/please-help-with-elasticsearch-sql-error-does-not-know-how-to-convert-argument-div-for-function-max/161308).

**Comment by s-chizhik** [comment] 2020-01-07 15:12
I've also faced this issue.
Following query:
```SQL
SELECT
   SUM(duration / 60 / coefficient) as cnt
FROM
    ...
WHERE
    ...
```

leads to an error:
```JSON
{
  "error": {
    "root_cause": [
      {
        "type": "sql_illegal_argument_exception",
        "reason": "Does not know how to convert argument Div[] for function Sum[]"
      }
    ],
    "type": "sql_illegal_argument_exception",
    "reason": "Does not know how to convert argument Div[] for function Sum[]"
  },
  "status": 500
}
```

Would you be so kind as to tell me, is there any information about solving this problem?

**Comment by costin** [comment] 2020-01-07 15:41
Related to https://github.com/elastic/elasticsearch/issues/29980

**Comment by costin** [comment] 2020-01-07 15:44
@s-chizhik There only workaround I can suggest is trying to find an approximation of the result by moving the formula outside the aggregation - `SUM(duration) / 60 / coefficient` - if `coefficient` is also another field then only workaround would be to precompute that (which means reindexing the data which is far from ideal).

Lastly, this is a tracker for bugs for missing features, like that you encountered - for questions and help, please use the forums.
Thanks.

**Comment by matriv** [comment] 2020-04-09 14:46
Closing this as it's actually a duplicate of #29980.
Please follow the updates there.

**Closed by matriv** 2020-04-09 14:46 UTC
Labels: :Query Languages/SQL, >enhancement

**Comment by matriv** [comment] 2020-04-17 10:41
`master` : 506d1beea7abb2b45de793bba2e349090a78f2f9
`7.x` : f958e9abdc492f648e305c9de618bf7273e5559b
