### ISSUE TITLE
[CI] ConfigurationTests test20HostnameSubstitution failing

### ISSUE THREAD

**Issue by piergm** [elastic/elasticsearch#109660] opened 2024-06-13 07:49 UTC
**Build scan:**
https://gradle-enterprise.elastic.co/s/rszk57krw5vti/tests/:qa:packaging:destructiveDistroTest.default-linux-archive/org.elasticsearch.packaging.test.ConfigurationTests/test20HostnameSubstitution

**Reproduction line:**
```
null
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.packaging.test.ConfigurationTests#test20HostnameSubstitution`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('test20HostnameSubstitution'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.packaging.test.ConfigurationTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.RuntimeException: Request failed:
HTTP/1.1 503 Service Unavailable
{"error":{"root_cause":[{"type":"cluster_block_exception","reason":"blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];"}],"type":"cluster_block_exception","reason":"blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];"},"status":503}

  at __randomizedtesting.SeedInfo.seed([14018179B976132C:BC50ABF8CCA0EA90]:0)
  at org.elasticsearch.packaging.util.ServerUtils.makeRequest(ServerUtils.java:366)
  at org.elasticsearch.packaging.test.ConfigurationTests.lambda$test20HostnameSubstitution$1(ConfigurationTests.java:53)
  at org.elasticsearch.packaging.test.PackagingTestCase.assertWhileRunning(PackagingTestCase.java:298)
  at org.elasticsearch.packaging.test.ConfigurationTests.lambda$test20HostnameSubstitution$3(ConfigurationTests.java:52)
  at org.elasticsearch.packaging.test.PackagingTestCase.withCustomConfig(PackagingTestCase.java:537)
  at org.elasticsearch.packaging.test.ConfigurationTests.test20HostnameSubstitution(ConfigurationTests.java:41)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1570)

```

**Comment by mark-vieira** [comment] 2024-06-17 20:27
This looks more like a timeout as the node simply wasn't up yet. This has failed only one time in the last 30 days and hasn't reproduced since. I'm just going to close this for now. We can reopen if this continues to fail.

**Comment by mark-vieira** [comment] 2024-06-18 19:05
I hit this again. Reopening.

https://gradle-enterprise.elastic.co/s/6wi4lbyqjbd2o

**Comment by mark-vieira** [comment] 2024-07-23 22:39
I believe issue here is simply that the node is not yet ready to server responses. It seems that when security is enabled on a test node, we use a considerably less reliable heuristic for determining if the node is "up". In [`ServerUtils`](https://github.com/elastic/elasticsearch/blob/a4588c0e3f61a8d242e0f657bb4eea91e8188ece/qa/packaging/src/test/java/org/elasticsearch/packaging/util/ServerUtils.java#L89) we are simply looking for a listening socket on port 9200 but I don't think that's sufficient. The reason we don't use the health endpoint for this is because the node might be setup with security auto configuration and we don't know the credentials.

For now I've opened https://github.com/elastic/elasticsearch/pull/111216 to simply wrap the assertion in an `assertBusy` but there could be a better solution here as this only fixes this problem for this single test case. @rjernst would using the readiness endpoint be better here? Is that only available in the Docker distribution?

**Closed** 2024-07-23 23:27 UTC
Labels: :Delivery/Packaging, >test-failure, Team:Delivery, low-risk

**Comment by rjernst** [comment] 2024-07-24 00:03
> would using the readiness endpoint be better here?

Yes, I think so. However, we don't run the readiness service except in cloud environments. Ultimately the node itself should wait on the readiness service (see https://github.com/elastic/elasticsearch/pull/102325). Until that work is finished, I think using an assertBusy is an ok workaround.
