### ISSUE TITLE
In elasticsearch 5.4.3 can’t go to green the x-pack monitoring Shard Activity error Phase[1] phase1 failed

### ISSUE THREAD

**Issue by zqc0512** [elastic/elasticsearch#26475] opened 2017-09-01 15:48 UTC
in elasticsearch 5.4.3 the x-pack monitoring Shard Activity error,
the Files and Bytes zero, Translog is n/a
as so, the elasticsearch is yellow,and much time can’t go to green. the recovery is very slow,about two hours can’t go to green.
how i can do?
elasticsearch 5.4.3 
oracle java 1.8_121
```
java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```
os: CentOS Linux release 7.3.1611 (Core)     3.10.0-514.el7.x86_64 
![image](https://user-images.githubusercontent.com/25192261/29977415-d742592c-8f6f-11e7-82cf-4d1103a1a09d.png)

log

```
Caused by: org.elasticsearch.transport.RemoteTransportException: [xxx.xxx][xxx.xxxx:9302][internal:index/shard/recovery/start_recovery]
Caused by: org.elasticsearch.index.engine.RecoveryEngineException: Phase[1] phase1 failed
        at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:140) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.indices.recovery.PeerRecoverySourceService.recover(PeerRecoverySourceService.java:132) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.indices.recovery.PeerRecoverySourceService.access$100(PeerRecoverySourceService.java:54) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.indices.recovery.PeerRecoverySourceService$StartRecoveryTransportRequestHandler.messageReceived(PeerRecoverySourceService.java:141) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.indices.recovery.PeerRecoverySourceService$StartRecoveryTransportRequestHandler.messageReceived(PeerRecoverySourceService.java:138) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1555) ~[elasticsearch-5.4.3.jar:5.4.3]
        ... 5 more
Caused by: org.elasticsearch.indices.recovery.RecoverFilesRecoveryException: Failed to transfer [1] files with total size of [1.2gb]
        at org.elasticsearch.indices.recovery.RecoverySourceHandler.phase1(RecoverySourceHandler.java:337) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:138) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.indices.recovery.PeerRecoverySourceService.recover(PeerRecoverySourceService.java:132) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.indices.recovery.PeerRecoverySourceService.access$100(PeerRecoverySourceService.java:54) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.indices.recovery.PeerRecoverySourceService$StartRecoveryTransportRequestHandler.messageReceived(PeerRecoverySourceService.java:141) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.indices.recovery.PeerRecoverySourceService$StartRecoveryTransportRequestHandler.messageReceived(PeerRecoverySourceService.java:138) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1555) ~[elasticsearch-5.4.3.jar:5.4.3]
        ... 5 more
Caused by: org.elasticsearch.transport.ReceiveTimeoutTransportException: [datanode][dataip:9303][internal:index/shard/recovery/filesInfo] request_id [118881] timed out after [900000ms]
        at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:934) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) ~[elasticsearch-5.4.3.jar:5.4.3]
```

**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by jasontedor** [comment] 2017-09-01 15:50
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Closed by jasontedor** 2017-09-01 15:50 UTC

**Comment by zqc0512** [comment] 2017-09-01 15:58
i think it a bug, a large env(20T + data 50000+shards) output the error,in other env (100G+ data) not output the error.
sorry
@jasontedor

**Comment by jasontedor** [comment] 2017-09-02 01:20
It is possible that you're running into a related issue: #26293. We do not know the cause of this issue yet, all I can tell you is that we are taking it seriously.
