### ISSUE TITLE
On updating _root logger level through _cluster/settings log level of child loggers is not considered

### ISSUE THREAD

**Issue by nikhil-bhat** [elastic/elasticsearch#53061] opened 2020-03-03 16:12 UTC
**Elasticsearch version** Version: 6.8.2, Build: default/tar/b506955/2019-07-24T15:24:41.545295Z, JVM: 1.8.0_231:

**Plugins installed**: []

**JVM version** 1.8.0_231:

**OS version** (Linux 4.15):

**On updating _root logger level through _cluster/settings log level of child logger is not considered while logging**

**Steps to reproduce**:

 1. add debug log level for a particular logging heirarchy

 ```
curl -X PUT \
  http://localhost:9200/_cluster/settings \
  -H 'Content-Type: application/json' \
  -d '{
  "transient": {
    "logger.org.elasticsearch.action.bulk.TransportShardBulkAction": "debug"
  }
}
'
``
`
Make an indexing request which trigger mapper_parsing_exception 
I am able to see logs
 [2020-03-03T21:28:08,365][DEBUG][o.e.a.b.TransportShardBulkAction]


 2. Add log level info for root logger 
curl -X PUT \
  http://localhost:9200/_cluster/settings \
  -H 'Content-Type: application/json' \
  -d '{
  "transient": {
    "logger._root": "info"
  }
}
'
Make an indexing request which trigger mapper_parsing_exception 
 Now logs with o.e.a.b.TransportShardBulkAction are not appearing .

3.) In ideal scenario changing log level of root logger should not effect child loggers .

**Comment by pgomulka** [comment] 2020-03-10 14:14
@nikhil-bhat thanks for reaching out. 
Is `   "logger._root": "info"` intentional?
I suspect you wanted this to be `debug`?

**Comment by rjernst** [comment] 2020-03-12 21:30
@nikhil-bhat This is by design. When updating a logger level, children loggers are descended and updated as well. The root logger is the parent of all loggers, so updating it means changing all loggers to that level.

**Comment by rjernst** [comment] 2020-03-18 18:09
Given this is working as designed, I hope you don't mind I close this issue.

**Closed by rjernst** 2020-03-18 18:09 UTC
Labels: :Core/Infra/Logging
