### ISSUE TITLE
Installing repository-gcs kills elasticsearch

### ISSUE THREAD

**Issue by cafuego** [elastic/elasticsearch#37643] opened 2019-01-21 05:16 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 6.5.4

**Plugins installed**: [ingest-geoip, ingest-user-agent]

**JVM version** (`java -version`):  As shipped in the container.

```
sh-4.2# /opt/jdk-11.0.1/bin/java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system):

Docker 18.09.1 on both MacOS and on CentOS 7.

**Description of the problem including expected versus actual behavior**:

I'm trying up update our docker based ELK 5.6.7 setup to 6.5.4. The upgrade assistant in Kibana reports no errors (though there are warnings). I kept getting silent fails (no logs, no console output, just ES and container exit)

Since I got no logs, I set up a local copy (minus the data) to see if I could replicate the issue. I can spin up an ES instance when I use all the default sample settings from the ES docker guide, but the instance exits (without any explanatory logs) the moment I install the gcs-archive plugin.

I am able to restart the local ES instance and ask it about installed plugins, the response I get is:

```
sh-4.2# ./bin/elasticsearch-plugin list
.installing-17043088347915376259
ingest-geoip
ingest-user-agent
```

So something is going wrong somewhere along the way. 

**Steps to reproduce**:

 1. Create a docker based ES instance using the sample docker config from https://www.elastic.co/guide/en/elasticsearch/reference/6.5/docker.html
 2. Open a shell in the elasticsearch container and run `elasticsearch-plugin install --batch repository-gcs`
 3. Oops

**Provide logs (if relevant)**:

The final output from `docker-compose up elasticsearch`:

```
elk-elasticsearch | [2019-01-21T05:07:31,811][INFO ][o.e.l.LicenseService     ] [YGTwYNK] license [7619b178-262b-4760-bae6-0ab354ed7b19] mode [basic] - valid
elk-elasticsearch | [2019-01-21T05:07:31,857][INFO ][o.e.g.GatewayService     ] [YGTwYNK] recovered [1] indices into cluster_state
elk-elasticsearch | [2019-01-21T05:07:32,652][INFO ][o.e.c.r.a.AllocationService] [YGTwYNK] Cluster health status changed from [RED] to [GREEN] (reason: [shards started [[.kibana_1][0]] ...]).
elk-elasticsearch | [2019-01-21T05:08:00,075][INFO ][o.e.c.r.a.DiskThresholdMonitor] [YGTwYNK] low disk watermark [85%] exceeded on [YGTwYNKlQ6GH90riIRkshA][YGTwYNK]
[snip a few repeats]
elk-elasticsearch | [2019-01-21T05:09:30,071][INFO ][o.e.c.r.a.DiskThresholdMonitor] [YGTwYNK] low disk watermark [85%] exceeded on [YGTwYNKlQ6GH90riIRkshA][YGTwYNK][/usr/share/elasticsearch/data/nodes/0] free: 54.3gb[11.6%], replicas will not be assigned to this node
elk-elasticsearch | [2019-01-21T05:09:32,560][INFO ][o.e.x.m.j.p.NativeController] [YGTwYNK] Native controller process has stopped - no new native processes can be started
elk-elasticsearch exited with code 137
```

**Comment by dliappis** [comment] 2019-01-21 14:15
Thanks very much for your interest in Elasticsearch.

In your reproduction step 2 you mention:

> Open a shell in the elasticsearch container and run `elasticsearch-plugin install --batch repository-gcs`

Opening a shell with something like `docker exec --user 1000:1000 -ti <es_container_name> /bin/bash` implies that Elasticsearch is running.

However, as per [ES plugins docs](https://www.elastic.co/guide/en/elasticsearch/plugins/current/intro.html):

  > Plugins contain JAR files, but may also contain scripts and config files, and must be installed on every node in the cluster. After installation, each node must be restarted before the plugin becomes visible.

So you'll still need to restart your container after that, but, unless you have bind mounted `/usr/share/elasticsearch/plugins/repository-gcs`, after restart the new plugin won't be present.

The right approach to install the needed plugin is to create a customized image as described [here](https://www.elastic.co/guide/en/elasticsearch/reference/6.5/docker.html#_c_customized_image). A simple `Dockerfile` like:

```
FROM docker.elastic.co/elasticsearch/elasticsearch:6.5.4
RUN elasticsearch-plugin install --batch repository-gcs
```

will suffice. You can then build your custom image with something like:

```
docker build --tag=elasticsearch-custom .
```

and then starting the new image will confirm the needed plugin is present:

```
$ docker run --rm elasticsearch-custom
...
[2019-01-21T14:11:09,866][INFO ][o.e.p.PluginsService     ] [6xQb-Zz] loaded plugin [ingest-geoip]
[2019-01-21T14:11:09,866][INFO ][o.e.p.PluginsService     ] [6xQb-Zz] loaded plugin [ingest-user-agent]
[2019-01-21T14:11:09,867][INFO ][o.e.p.PluginsService     ] [6xQb-Zz] loaded plugin [repository-gcs]
```

For your benefit I'd like to add we reserve GitHub for verified bug reports, features and pull requests, so in the future if you are uncertain whether the issue is a real bug, we'd like to direct these kinds 
of things to the [forums](https://discuss.elastic.co/). If you can stop 
by there, we'd appreciate it.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your questions. As such, I hope you don't mind that I close this.

**Closed by dliappis** 2019-01-21 14:15 UTC
Labels: :Core/Infra/Packaging, >non-issue
