### ISSUE TITLE
Error while Bulk Index Operations !!!

### ISSUE THREAD

**Issue by adhamelia** [elastic/elasticsearch#17565] opened 2016-04-06 16:01 UTC
Hi ES Team,

we are using ES 2.2 build (2.2.0) for document storage. 

while executing bulk index request having a few docs around 10-50  docs at every 5 sec interval, getting a weird error in afterbulk callback of bulk processor.
**
RemoteTransportException[[Hairbag][127.0.0.1:9300][indices:data/write/bulk]]; nested: NullPointerException[id must not be null];**

in result of, lots of documents are not being indexed and most of our bulk request got failed !!!

we are clueless what's going underneath ??? can you guys throw some lights on it ???

**Comment by clintongormley** [comment] 2016-04-06 16:05
Please provide a short but complete reproduction of the issue, including creating the index, specifying the mappings, indexing the docs, and provide the full exception with stack trace.  It will greatly help us to understand what the problem is.

**Comment by clintongormley** [comment] 2016-05-24 10:34
No further feedback. Closing

**Closed by clintongormley** 2016-05-24 10:34 UTC
Labels: :Bulk, feedback_needed
