### ISSUE TITLE
get _cat/shards respon index_closed_exception

### ISSUE THREAD

**Issue by test987654123** [elastic/elasticsearch#36986] opened 2018-12-26 03:37 UTC
https://discuss.elastic.co/t/request-cat-shards-display-index-closed-exception/161992

elasticsearch version: 6.4.2 

![image](https://user-images.githubusercontent.com/14846522/50431022-953e8d80-0902-11e9-8fc5-bd6836b61fa6.png)

**Comment by javanna** [comment] 2018-12-27 19:46
hi @test987654123 do you have any plugin installed? Are you using the security plugin by any chance?

**Comment by test987654123** [comment] 2018-12-28 02:57
Hi, Because it is in the test environment, there is any plugin。 
## cluster xpack security setting ##
# display 
xpack.security.enabled: true
xpack.ssl.key: certs/*.key
xpack.ssl.certificate: certs/*.crt
xpack.ssl.certificate_authorities: certs/ca.crt
xpack.security.transport.ssl.enabled: true
xpack.security.http.ssl.enabled: true

# remote cross search 
search.remote.connections_per_cluster: 2   
search.remote.initial_connect_timeout: 40s 
search.remote.elastic_ali.seeds: *
search.remote.elastic_ali.skip_unavailable: true

## plugins info ##
[ ~ /data/app/elastic_coord ]# tree plugins
plugins

0 directories, 0 files

**Comment by javanna** [comment] 2018-12-28 09:32
Ok thanks for your feedback, see #32238 for an explanation on this issue. It's a known problem when xpack security is used, and an alias that points to both closed and open indices is accessed. Closing as a duplicate of #32238.

**Closed by javanna** 2018-12-28 09:32 UTC
Labels: :Core/Features/Index APIs, feedback_needed
