### ISSUE TITLE
Transforms mixed cluster "GET/start/stop old [cluster/batch] transforms" tests fail reproducibly

### ISSUE THREAD

**Issue by gwbrown** [elastic/elasticsearch#67945] opened 2021-01-25 19:08 UTC
**Build scan**: https://gradle-enterprise.elastic.co/s/apxwwc63asjom

**Repro line**: `./gradlew clean ':x-pack:qa:rolling-upgrade:v7.12.0#oneThirdUpgradedTest' -Dtests.class="org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=mixed_cluster/80_transform_jobs_crud/Test GET, start, and stop old cluster batch transforms}" -Dtests.seed=562A6BADAD918E4D -Dtests.security.manager=true -Dtests.bwc=true -Dtests.locale=es-MX -Dtests.timezone=W-SU -Druntime.java=11 -Dtests.rest.suite=mixed_cluster`

**Reproduces locally?**: Yes

**Applicable branches**: Observed on `master`-based PR branches, typically (always?) during BWC tests against 7.x (7.12.0 at time of writing).

**Failure history**: [build-stats](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-60d,mode:quick,to:now))&_a=(columns:!(message,branch),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'test:%22test%20%7Bp0%3Dmixed_cluster%2F80_transform_jobs_crud%2FTest%20GET,%20start,%20and%20stop%20old%20cluster%20batch%20transforms%7D%22'),sort:!(time,desc))), these failures appear to have started on either Jan. 18 or Jan. 21, there are some similar-but-not-quite-the-same failures on the 18th, the exact error message first appears on the 21st.

There appear to be some similar failures for the `continuous transforms` version of this test as well, see [this build scan](https://gradle-enterprise.elastic.co/s/qlxr224r7wnua/tests/:x-pack:qa:rolling-upgrade:v7.12.0%23oneThirdUpgradedTest/org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT/test%20%7Bp0=mixed_cluster%2F80_transform_jobs_crud%2FTest%20GET,%20stop,%20start,%20old%20continuous%20transforms%7D#1). I haven't put much time into investigating that failure as my guess is that the root cause is the same.

**Failure excerpt**:
```
java.lang.AssertionError: Failure at [mixed_cluster/80_transform_jobs_crud:316]: expected [2xx] status code but api [data_frame_transform_deprecated.update_transform] returned [500 Internal Server Error] [---	
error:	
  root_cause:	
  - type: "transport_serialization_exception"	
    reason: "Failed to deserialize response from handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.action.ActionListenerResponseHandler@77561550/org.elasticsearch.action.ActionListener$3@467557db]"	
    stack_trace: "org.elasticsearch.transport.TransportSerializationException: Failed\	
      \ to deserialize response from handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.action.ActionListenerResponseHandler@77561550/org.elasticsearch.action.ActionListener$3@467557db]\n\	
      \tat org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:278)\n\	
      \tat org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:139)\n\	
      \tat org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:95)\n\	
      \tat org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:686)\n\	
      \tat org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:142)\n\	
      \tat org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:117)\n\	
      \tat org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:82)\n\	
      \tat org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74)\n\	
      \tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\	
      \tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\	
      \tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\	
      \tat io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271)\n\	
      \tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\	
      \tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\	
      \tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\	
      \tat io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1518)\n\tat io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1267)\n\	
      \tat io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1314)\n\tat io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)\n\	
      \tat io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)\n\	
      \tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)\n\	
      \tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\	
      \tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\	
      \tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\	
      \tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)\n\	
      \tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\	
      \tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\	
      \tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)\n\	
      \tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)\n\	
      \tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)\n\	
      \tat io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615)\n\	
      \tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578)\n\	
      \tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)\n\	
      \tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\	
      \tat java.base/java.lang.Thread.run(Thread.java:834)\nCaused by: java.lang.IllegalStateException:\	
      \ unexpected byte [0x6c]\n\tat org.elasticsearch.common.io.stream.StreamInput.readBoolean(StreamInput.java:588)\n\	
      \tat org.elasticsearch.common.io.stream.StreamInput.readBoolean(StreamInput.java:578)\n\	
      \tat org.elasticsearch.common.io.stream.StreamInput.readOptionalString(StreamInput.java:368)\n\	
      \tat org.elasticsearch.xpack.core.transform.transforms.DestConfig.<init>(DestConfig.java:54)\n\	
      \tat org.elasticsearch.xpack.core.transform.transforms.TransformConfig.<init>(TransformConfig.java:203)\n\	
      \tat org.elasticsearch.xpack.core.transform.action.UpdateTransformAction$Response.<init>(UpdateTransformAction.java:185)\n\	
      \tat org.elasticsearch.xpack.core.transform.action.UpdateTransformAction$Response.fromStreamWithBWC(UpdateTransformAction.java:190)\n\	
      \tat org.elasticsearch.action.ActionListenerResponseHandler.read(ActionListenerResponseHandler.java:69)\n\	
      \tat org.elasticsearch.action.ActionListenerResponseHandler.read(ActionListenerResponseHandler.java:36)\n\	
      \tat org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1167)\n\	
      \tat org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1154)\n\	
      \tat org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1167)\n\	
      \tat org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1154)\n\	
      \tat org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:275)\n\	
      \t... 35 more\n"	
  type: "transport_serialization_exception"	
  reason: "Failed to deserialize response from handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.action.ActionListenerResponseHandler@77561550/org.elasticsearch.action.ActionListener$3@467557db]"	
  caused_by:	
    type: "illegal_state_exception"	
    reason: "unexpected byte [0x6c]"	
    stack_trace: "java.lang.IllegalStateException: unexpected byte [0x6c]\n\tat org.elasticsearch.common.io.stream.StreamInput.readBoolean(StreamInput.java:588)\n\	
      \tat org.elasticsearch.common.io.stream.StreamInput.readBoolean(StreamInput.java:578)\n\	
      \tat org.elasticsearch.common.io.stream.StreamInput.readOptionalString(StreamInput.java:368)\n\	
      \tat org.elasticsearch.xpack.core.transform.transforms.DestConfig.<init>(DestConfig.java:54)\n\	
      \tat org.elasticsearch.xpack.core.transform.transforms.TransformConfig.<init>(TransformConfig.java:203)\n\	
      \tat org.elasticsearch.xpack.core.transform.action.UpdateTransformAction$Response.<init>(UpdateTransformAction.java:185)\n\	
      \tat org.elasticsearch.xpack.core.transform.action.UpdateTransformAction$Response.fromStreamWithBWC(UpdateTransformAction.java:190)\n\	
      \tat org.elasticsearch.action.ActionListenerResponseHandler.read(ActionListenerResponseHandler.java:69)\n\	
      \tat org.elasticsearch.action.ActionListenerResponseHandler.read(ActionListenerResponseHandler.java:36)\n\	
      \tat org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1167)\n\	
      \tat org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1154)\n\	
      \tat org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1167)\n\	
      \tat org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1154)\n\	
      \tat org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:275)\n\	
      \tat org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:139)\n\	
      \tat org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:95)\n\	
      \tat org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:686)\n\	
      \tat org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:142)\n\	
      \tat org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:117)\n\	
      \tat org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:82)\n\	
      \tat org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74)\n\	
      \tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\	
      \tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\	
      \tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\	
      \tat io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271)\n\	
      \tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\	
      \tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\	
      \tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\	
      \tat io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1518)\n\tat io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1267)\n\	
      \tat io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1314)\n\tat io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)\n\	
      \tat io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)\n\	
      \tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)\n\	
      \tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\	
      \tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\	
      \tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\	
      \tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)\n\	
      \tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\	
      \tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\	
      \tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)\n\	
      \tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)\n\	
      \tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)\n\	
      \tat io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615)\n\	
      \tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578)\n\	
      \tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)\n\	
      \tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\	
      \tat java.base/java.lang.Thread.run(Thread.java:834)\n"	
  stack_trace: "org.elasticsearch.transport.TransportSerializationException: Failed\	
    \ to deserialize response from handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.action.ActionListenerResponseHandler@77561550/org.elasticsearch.action.ActionListener$3@467557db]\n\	
    \tat org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:278)\n\	
    \tat org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:139)\n\	
    \tat org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:95)\n\	
    \tat org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:686)\n\	
    \tat org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:142)\n\	
    \tat org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:117)\n\	
    \tat org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:82)\n\	
    \tat org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74)\n\	
    \tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\	
    \tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\	
    \tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\	
    \tat io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271)\n\	
    \tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\	
    \tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\	
    \tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\	
    \tat io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1518)\n\tat io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1267)\n\	
    \tat io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1314)\n\tat io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)\n\	
    \tat io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)\n\	
    \tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)\n\	
    \tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\	
    \tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\	
    \tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\	
    \tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)\n\	
    \tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\	
    \tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\	
    \tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)\n\	
    \tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)\n\	
    \tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)\n\	
    \tat io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615)\n\	
    \tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578)\n\	
    \tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)\n\	
    \tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\	
    \tat java.base/java.lang.Thread.run(Thread.java:834)\nCaused by: java.lang.IllegalStateException:\	
    \ unexpected byte [0x6c]\n\tat org.elasticsearch.common.io.stream.StreamInput.readBoolean(StreamInput.java:588)\n\	
    \tat org.elasticsearch.common.io.stream.StreamInput.readBoolean(StreamInput.java:578)\n\	
    \tat org.elasticsearch.common.io.stream.StreamInput.readOptionalString(StreamInput.java:368)\n\	
    \tat org.elasticsearch.xpack.core.transform.transforms.DestConfig.<init>(DestConfig.java:54)\n\	
    \tat org.elasticsearch.xpack.core.transform.transforms.TransformConfig.<init>(TransformConfig.java:203)\n\	
    \tat org.elasticsearch.xpack.core.transform.action.UpdateTransformAction$Response.<init>(UpdateTransformAction.java:185)\n\	
    \tat org.elasticsearch.xpack.core.transform.action.UpdateTransformAction$Response.fromStreamWithBWC(UpdateTransformAction.java:190)\n\	
    \tat org.elasticsearch.action.ActionListenerResponseHandler.read(ActionListenerResponseHandler.java:69)\n\	
    \tat org.elasticsearch.action.ActionListenerResponseHandler.read(ActionListenerResponseHandler.java:36)\n\	
    \tat org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1167)\n\	
    \tat org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1154)\n\	
    \tat org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1167)\n\	
    \tat org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1154)\n\	
    \tat org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:275)\n\	
    \t... 35 more\n"
```

**Comment by przemekwitek** [comment] 2021-01-26 14:09
This bug only occurs on `pull-request-bwc` branch which makes me wonder whether:
1. CI does not run this test for some reason
2. The issue is more related to the changes in the PR itself rather than the test which fails (it is known that serialization does not always fail at the place where the bug is)
3. Maybe the PR was synced in the middle of latest transform-related changes in master/7.x (full sequence is: https://github.com/elastic/elasticsearch/pull/67643, https://github.com/elastic/elasticsearch/pull/67821, https://github.com/elastic/elasticsearch/pull/67822, https://github.com/elastic/elasticsearch/pull/67826)
?

@gwbrown: Do you think one of the above could take place here?

**Comment by gwbrown** [comment] 2021-01-26 16:38
1 or 3 are possible, though I did also check on latest `master` (and again just before I write this), and the repro line fails against that, though [with a different error](https://gradle-enterprise.elastic.co/s/tj63vllt523s4/tests/:x-pack:qa:rolling-upgrade:v7.12.0%23oneThirdUpgradedTest/org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT/test%20%7Bp0=mixed_cluster%2F80_transform_jobs_crud%2FTest%20GET,%20start,%20and%20stop%20old%20cluster%20batch%20transforms%7D#1). Additionally, if I run the whole `transforms_jobs_crud` suite with the same seed, the [same two tests fail](https://gradle-enterprise.elastic.co/s/fywmmtajdvz2q).

I don't think it's 2, because just checking 3 PRs this has hit, there's one that adjusts some searchable snapshots test code (https://github.com/elastic/elasticsearch/pull/67917), one that adjusts how timestamps are printed (https://github.com/elastic/elasticsearch/pull/67893), and one that makes changes to snapshots (https://github.com/elastic/elasticsearch/pull/63513), none of which should impact serialization of Transforms.

If you believe this has been addressed and this repro line produces local failures for some reason which has already been addressed, feel free to close this issue and we can reopen it if/when it happens again.

**Comment by przemekwitek** [comment] 2021-01-27 12:39
> If you believe this has been addressed and this repro line produces local failures for some reason which has already been addressed, feel free to close this issue and we can reopen it if/when it happens again.

The last occurrence of this issue is from 2 days ago. I'll wait a day or two, look at build-stats and then close this issue if no new occurrences show up.

**Comment by przemekwitek** [comment] 2021-02-01 12:39
> The last occurrence of this issue is from 2 days ago. I'll wait a day or two, look at build-stats and then close this issue if no new occurrences show up.

I confirm that there were no new occurrences in the last days.
Closing the issue.

**Closed by przemekwitek** 2021-02-01 12:39 UTC
Labels: :ml/Transform, >test-failure
