### ISSUE TITLE
[CI] FlushIT testFlushOnInactive failing

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#97154] opened 2023-06-27 15:59 UTC
Looks similar to #87888 fixed a year ago. 

The test failed today https://gradle-enterprise.elastic.co/s/bcbi54ntydxas and a month ago https://gradle-enterprise.elastic.co/s/22czbdpytknvi

**Build scan:**
https://gradle-enterprise.elastic.co/s/bcbi54ntydxas/tests/:server:internalClusterTest/org.elasticsearch.indices.flush.FlushIT/testFlushOnInactive

**Reproduction line:**
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.indices.flush.FlushIT.testFlushOnInactive" -Dtests.seed=58067D81DCE0CA07 -Dtests.locale=es-CU -Dtests.timezone=America/Bahia -Druntime.java=20
```

**Applicable branches:**
8.9, main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.indices.flush.FlushIT&tests.test=testFlushOnInactive

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: <0>
     but: was <4>

  at __randomizedtesting.SeedInfo.seed([58067D81DCE0CA07:BF63E3C83F4FC9CB]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.indices.flush.FlushIT.lambda$testFlushOnInactive$1(FlushIT.java:136)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1172)
  at org.elasticsearch.indices.flush.FlushIT.testFlushOnInactive(FlushIT.java:134)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

**Comment by kingherc** [comment] 2023-06-29 11:51
This is reaaaally hard to reproduce. I had one local reproduction in I do not know how many hours of running, with no meaningful logs however to understand what's going on :/ I then turned on trace logging, and have never replicated it again.

I went back in time since Aug 22 (when https://github.com/elastic/elasticsearch/issues/87888 was fixed) in gradle history to find failures and found the following:

- Aug 28 for v8.4: https://gradle-enterprise.elastic.co/s/ugpdfjqrhtt4e but we should probably ignore this since the fix was merged in 8.5
- Sep 20 for v7.17: https://gradle-enterprise.elastic.co/s/3yf2fkacss75s but we should probably ignore this since the fix was not backported to 7.17 (wondering if we should?).
- Mar 8 for v8.7: https://gradle-enterprise.elastic.co/s/kr46jvxd2fq26
- Apr 3 for v8.8: https://gradle-enterprise.elastic.co/s/22czbdpytknvi
- Jun 27 for v8.9: https://gradle-enterprise.elastic.co/s/bcbi54ntydxas

So my impression is that the fix appeased the error'ing behavior a lot, but did not fix all edge cases.

**Comment by volodk85** [comment] 2024-02-08 23:18
Unfortunately it's failing again :(

https://gradle-enterprise.elastic.co/s/kandwegr56fsy/console-log

```
REPRODUCE WITH: gradlew ':server:internalClusterTest' --tests "org.elasticsearch.indices.flush.FlushIT.testFlushOnInactive" -Dtests.seed=4441F78B2F9D464C -Dtests.locale=en-ZA -Dtests.timezone=Europe/Sofia -Druntime.java=21

org.elasticsearch.indices.flush.FlushIT > testFlushOnInactive FAILED
    java.lang.AssertionError: 
    Expected: <0>
         but: was <4>
        at __randomizedtesting.SeedInfo.seed([4441F78B2F9D464C:A32469C2CC324580]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:964)
        at org.junit.Assert.assertThat(Assert.java:930)
        at org.elasticsearch.indices.flush.FlushIT.lambda$testFlushOnInactive$7(FlushIT.java:491)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1143)
        at org.elasticsearch.indices.flush.FlushIT.testFlushOnInactive(FlushIT.java:489)

```

**Comment by arteam** [comment] 2024-07-01 18:06
I believe that failure from is from 7.17 where we didn't backport Iraklis' fix. In the meantime, the test hasn't failed in over 90 days, so I'm going to close the issue. If it reproduces again, we can mute the test in 7.17 or try to backport #97332.

**Closed by arteam** 2024-07-01 18:06 UTC
Labels: >test-failure, :Distributed/Engine, Team:Distributed, low-risk
