### ISSUE TITLE
[1.5.2] Launcher script doesn't like unicode characters

### ISSUE THREAD

**Issue by gribouille** [elastic/elasticsearch#10937] opened 2015-05-02 21:51 UTC
The script ./bin/elasticsearch does not work when there are unicode characters in the path:
```
/tmp » pwd
/tmp
------------------------------------------------------------
/tmp » tar zxvf elasticsearch-1.5.2.tar.gz                                                                                 
elasticsearch-1.5.2/config/logging.yml
[...]
elasticsearch-1.5.2/NOTICE.txt
------------------------------------------------------------
/tmp » mkdir dir_with_french_char_é                                                                                        
------------------------------------------------------------
/tmp » mv elasticsearch-1.5.2 dir_with_french_char_é                                                                       
------------------------------------------------------------
/tmp » ./dir_with_french_char_é/elasticsearch-1.5.2/bin/elasticsearch
Error: Could not find or load main class org.elasticsearch.bootstrap.Elasticsearch
------------------------------------------------------------
/tmp » mv dir_with_french_char_é dir_with_french_char_e
------------------------------------------------------------
/tmp » ./dir_with_french_char_e/elasticsearch-1.5.2/bin/elasticsearch
[2015-05-02 23:43:59,233][INFO ][node                     ] [Prometheus] version[1.5.2], pid[15437], build[62ff986/2015-04-27T09:21:06Z]
[2015-05-02 23:43:59,234][INFO ][node                     ] [Prometheus] initializing ...
[2015-05-02 23:43:59,237][INFO ][plugins                  ] [Prometheus] loaded [], sites []
[2015-05-02 23:44:01,153][INFO ][node                     ] [Prometheus] initialized
[2015-05-02 23:44:01,153][INFO ][node                     ] [Prometheus] starting ...
[2015-05-02 23:44:01,224][INFO ][transport                ] [Prometheus] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/192.168.0.12:9300]}
[2015-05-02 23:44:01,234][INFO ][discovery                ] [Prometheus] elasticsearch/cVO5bJgySh-kySL-8sKoKA
```

**Comment by rmuir** [comment] 2015-05-03 07:45
Works fine for me, also with master. Can you show the results of 'env' or at least 'locale' (prints only the locale related ones)? It may be related. I strongly recommend using unicode (e.g. fr_FR.UTF-8) 
```
rmuir@beast:/data/t$ ./dir_with_french_char_é/elasticsearch-1.5.2/bin/elasticsearch
[2015-05-03 03:40:14,127][INFO ][node                     ] [Defensor] version[1.5.2], pid[11114], build[62ff986/2015-04-27T09:21:06Z]
[2015-05-03 03:40:14,127][INFO ][node                     ] [Defensor] initializing ...
[2015-05-03 03:40:14,130][INFO ][plugins                  ] [Defensor] loaded [], sites []
```

**Comment by gribouille** [comment] 2015-05-03 18:25
My locales is configured for UTF-8:
```
~ » locale                                                                                                         hakim@aeon
LANG=fr_FR.UTF-8
LANGUAGE=
LC_CTYPE=fr_FR.UTF-8
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=
```

**Comment by gribouille** [comment] 2015-05-03 18:31
I have forgotten to say that to run elasticearch with the starter command works:
```
/tmp » /usr/bin/java -Xms256m -Xmx1g -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -Dfile.encoding=UTF-8 -Delasticsearch -Des.foreground=yes -Des.path.home=/tmp/é/elasticsearch-1.5.2 -cp ":/tmp/é/elasticsearch-1.5.2/lib/elasticsearch-1.5.2.jar:/tmp/é/elasticsearch-1.5.2/lib/*:/tmp/é/elasticsearch-1.5.2/lib/sigar/*" org.elasticsearch.bootstrap.Elasticsearch
[2015-05-03 20:27:40,761][INFO ][node                     ] [Asteroth] version[1.5.2], pid[4301], build[62ff986/2015-04-27T09:21:06Z]
[2015-05-03 20:27:40,761][INFO ][node                     ] [Asteroth] initializing ...
[2015-05-03 20:27:40,764][INFO ][plugins                  ] [Asteroth] loaded [], sites []
[2015-05-03 20:27:42,736][INFO ][node                     ] [Asteroth] initialized
[2015-05-03 20:27:42,737][INFO ][node                     ] [Asteroth] starting ...
```

**Comment by clintongormley** [comment] 2015-05-04 13:10
When I try this on OSX, it works out of the box, with these locale settings:

    LANG=
    LC_COLLATE="C"
    LC_CTYPE="UTF-8"
    LC_MESSAGES="C"
    LC_MONETARY="C"
    LC_NUMERIC="C"
    LC_TIME="C"
    LC_ALL=

If I change `LC_CTYPE` to `C`, then I get the same error message: 

    LC_CTYPE="C" ./fã/elasticsearch-1.5.2/bin/elasticsearch 
    Error: Could not find or load main class org.elasticsearch.bootstrap.Elasticsearch

Does seem like a local locale problem...

**Comment by clintongormley** [comment] 2015-05-04 13:15
What OS are you running on?  Could you check this again, running `env` in the same shell where you see the failed start?

**Comment by gribouille** [comment] 2015-05-04 18:33
My config:
```
~ » env
LANG=fr_FR.UTF-8
TERM=xterm
SHELL=/bin/zsh
PAGER=less
LESS=-R
LC_CTYPE=fr_FR.UTF-8
LSCOLORS=Gxfxcxdxbxegedabagacad
_=/usr/bin/env
[...]
~ » uname -a
Linux aeon 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt7-1~bpo70+1 (2015-04-07) x86_64 GNU/Linux
~ » cat /etc/debian_version
7.8
```
This command works with zsh or dash:
```
/tmp » /usr/bin/java -Xms256m -Xmx1g -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -Dfile.encoding=UTF-8 -Delasticsearch -Des.foreground=yes -Des.path.home=/tmp/é/elasticsearch-1.5.2 -cp ":/tmp/é/elasticsearch-1.5.2/lib/elasticsearch-1.5.2.jar:/tmp/é/elasticsearch-1.5.2/lib/*:/tmp/é/elasticsearch-1.5.2/lib/sigar/*" org.elasticsearch.bootstrap.Elasticsearch
[2015-05-03 20:27:40,761][INFO ][node                     ] [Asteroth] version[1.5.2], pid[4301], build[62ff986/2015-04-27T09:21:06Z]
[2015-05-03 20:27:40,761][INFO ][node                     ] [Asteroth] initializing ...
[2015-05-03 20:27:40,764][INFO ][plugins                  ] [Asteroth] loaded [], sites []
[2015-05-03 20:27:42,736][INFO ][node                     ] [Asteroth] initialized
[2015-05-03 20:27:42,737][INFO ][node                     ] [Asteroth] starting ...
```

**Comment by clintongormley** [comment] 2015-05-05 07:33
@tlrx could you take a look at this when you have a moment?

**Comment by clintongormley** [comment] 2016-01-18 14:34
A lot has changed since 1.5, and this is not reproducible in master - closing for now, please reopen if there is still an issue in 2.1 or above.

**Closed by clintongormley** 2016-01-18 14:34 UTC
Labels: :Packaging, discuss
