### ISSUE TITLE
Watcher should not try to compile .swp (or other .*) files

### ISSUE THREAD

**Issue by jsnod** [elastic/elasticsearch#10289] opened 2015-03-26 23:48 UTC
I was editing a file in `config/scripts` when this showed up in my logs:

```
[2015-03-26 23:42:25,022][WARN ][script] [Madcap] no script engine found for [swp]
[2015-03-26 23:42:50,023][INFO ][script] [Madcap] removing script file [/etc/elasticsearch/scripts/.myScript.groovy.swp]
[2015-03-26 23:42:50,023][INFO ][script] [Madcap] compiling script file [/etc/elasticsearch/scripts/myScript.groovy]
```

I'm thinking the watcher should ignore `.swp` files.  Better yet, it should ignore `.*`

**Comment by jpountz** [comment] 2015-04-06 18:30
I think logging a warning is the right thing to do here? What if someone creates a plugin to add a scripting engine called `swp`? I also like the simplicity of the way it works now, if we start adding complex exclusion patterns I'm afraid it would become harder to reason about what gets compiled and what not.

**Comment by clintongormley** [comment] 2015-04-06 19:01
@jpountz how about only trying to compile recognised extensions? Makes more sense to me than compiling anything in the folder.

**Comment by dadoonet** [comment] 2015-04-06 19:08
+1 we should only compile expected extensions. My 0.05 cents.

**Comment by rmuir** [comment] 2015-04-06 19:46
I see other places in the code that ignore hidden files here (using isHidden). I think we should be consistent about this stuff, if we are going to look for only certain extensions here, then we should nuke the isHidden checks in the other places.

**Comment by jpountz** [comment] 2015-04-06 19:47
@clintongormley @dadoonet  What if you install elasticsearch on a new machine, move your scripts to `config/scripts` but forget to install the scripting plugin. You would get errors that the scripts could not be found while they are in the expected folder. I think I could easily get confused while the warning that we have in the logs today would clearly explain what the issue is?

**Comment by afx114** [comment] 2015-04-06 21:55
Sorry my request wasn't clear -- it's not the extension that is the issue, but the fact that it is a hidden file prefixed with the `.` character.  If your scripting engine was called `swp`, I think it would be fine to load `myScript.swp`.  But I think it is problematic to load `.myScript.swp` (notice the dot in the front).  Watcher shouldn't attempt to load dot-files files regardless of their extension.

**Comment by afx114** [comment] 2015-04-06 21:59
Although, now thinking about it some more, I could see an situation where someone copies an existing script to `myScript.groovy.bak` or `myScript.groovy.20150406` and then creates a new version of `myScript.groovy`.  Does that mean watcher will compile both files?  What if we have 50 backups in the directory, will watcher compile them all?  Perhaps that is an argument for compiling only expected extensions.

**Comment by clintongormley** [comment] 2015-04-07 12:13
> @clintongormley @dadoonet What if you install elasticsearch on a new machine, move your scripts to config/scripts but forget to install the scripting plugin. You would get errors that the scripts could not be found while they are in the expected folder. I think I could easily get confused while the warning that we have in the logs today would clearly explain what the issue is?

Surely the error would be "unsupported language XXX" instead?

> Although, now thinking about it some more, I could see an situation where someone copies an existing script to myScript.groovy.bak or myScript.groovy.20150406 and then creates a new version of myScript.groovy. Does that mean watcher will compile both files?

I think so.  We have had similar issues with config files, eg https://github.com/elastic/elasticsearch/issues/8040

**Comment by Tarotato** [comment] 2017-03-13 20:55
Hi, I'm new to this project and wondering if this was still available to fix?

**Comment by rjernst** [comment] 2017-05-28 05:40
File scripts have been removed for 6.0 so I am closing this.

**Closed by rjernst** 2017-05-28 05:40 UTC
Labels: :Scripting, adoptme, enhancement, low hanging fruit
