### ISSUE TITLE
[CI] NodeConnectionsServiceTests testOnlyBlocksOnConnectionsToNewNodes failing

### ISSUE THREAD

**Issue by thecoop** [elastic/elasticsearch#105556] opened 2024-02-15 13:46 UTC
**Build scan:**
https://gradle-enterprise.elastic.co/s/m4vy4ftjv7cya/tests/:server:test/org.elasticsearch.cluster.NodeConnectionsServiceTests/testOnlyBlocksOnConnectionsToNewNodes

**Reproduction line:**
```
./gradlew ':server:test' --tests "org.elasticsearch.cluster.NodeConnectionsServiceTests.testOnlyBlocksOnConnectionsToNewNodes" -Dtests.seed=2FFE3EE707EDD8D1 -Dtests.locale=nb -Dtests.timezone=Pacific/Tahiti -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
[Failure dashboard for `org.elasticsearch.cluster.NodeConnectionsServiceTests#testOnlyBlocksOnConnectionsToNewNodes`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testOnlyBlocksOnConnectionsToNewNodes'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.cluster.NodeConnectionsServiceTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([2FFE3EE707EDD8D1]:0)

```

**Comment by DaveCTurner** [comment] 2024-02-22 12:00
> **Reproduces locally?:**
> No

FWIW this reproduced for me locally after ~350k iterations (~12h). I think that's a record.

**Comment by arteam** [comment] 2024-03-25 17:38
I've ran this test around 25K without failures until I my machine ran out of TCP ports. This test doesn't reproduce for me and failed only once over 11K runs on CI. I'm going to close the issue, feel free to re-open if this issue reproduces again on CI.

**Comment by nielsbauman** [comment] 2024-05-24 09:11
@arteam found another one: https://gradle-enterprise.elastic.co/s/6jgmbgitrxihq/tests/:server:test/org.elasticsearch.cluster.NodeConnectionsServiceTests/testOnlyBlocksOnConnectionsToNewNodes

**Comment by nicktindall** [comment] 2024-07-17 07:23
I merged some changes to hopefully shed some more light on this failure https://github.com/elastic/elasticsearch/pull/110956

**Comment by nicktindall** [comment] 2024-07-29 06:21
I'm going to close this for now, it doesn't appear to have occurred since I merged the behavioural changes, if/when it does appear I hope that it'll look a bit different.

**Closed by nicktindall** 2024-07-29 06:21 UTC
Labels: :Distributed/Network, >test-failure, Team:Distributed, low-risk
