### ISSUE TITLE
Issue after upgrading ES from 1.x to 2.x 

### ISSUE THREAD

**Issue by dobariya** [elastic/elasticsearch#17580] opened 2016-04-07 05:28 UTC
After upgrading ES version from 1.7 to 2.2.0 we have start receiving errors.Please see below log for the same.

`we use virtual environment with EMC storage`

We have three nodes all as master=true and data=true.

Here is our configuration

    cluster.name: cluster1
    node.name: "node01
    node.master: true
    node.data: true
    index.query.bool.max_clause_count: 50100
    indices.fielddata.cache.size: 40%
    action.disable_delete_all_indices: true
    indices.cluster.send_refresh_mapping: false
    index.cache.field.type: soft
    indices.breaker.fielddata.limit: 60%
    path.data: E:/Share/Elastic_Search/data
    path.logs: \\PC1\Elasticsearch\Logs\node01
    bootstrap.mlockall: true
    network.host: node01
    indices.recovery.max_bytes_per_sec: 100mb
    indices.recovery.concurrent_streams: 5
    discovery.zen.ping.multicast.enabled: false
    discovery.zen.ping.unicast.hosts: [node01,node02,node03]

And log messages

    [2016-04-06 12:01:52,496][DEBUG][action.admin.indices.stats] [node01] [indices:monitor/stats] failed to execute operation for shard [[Products][3], node[L_mbnAHGRHiwIyi3of0GKw], [P], v[209], s[STARTED], a[id=FOWy8JKfRWeiFLmhvX05bQ]]
    ElasticsearchException[failed to refresh store stats]; nested: AccessDeniedException[E:\Share\Elastic_Search\data\cluster1\nodes\0\indices\Products\3\index\_9zmi_Lucene54_0.dvd];
      at org.elasticsearch.index.store.Store$StoreStatsCache.refresh(Store.java:1534)
      at org.elasticsearch.index.store.Store$StoreStatsCache.refresh(Store.java:1519)
      at org.elasticsearch.common.util.SingleObjectCache.getOrRefresh(SingleObjectCache.java:55)
      at org.elasticsearch.index.store.Store.stats(Store.java:293)
      at org.elasticsearch.index.shard.IndexShard.storeStats(IndexShard.java:665)
      at org.elasticsearch.action.admin.indices.stats.CommonStats.<init>(CommonStats.java:134)
      at org.elasticsearch.action.admin.indices.stats.TransportIndicesStatsAction.shardOperation(TransportIndicesStatsAction.java:165)
      at org.elasticsearch.action.admin.indices.stats.TransportIndicesStatsAction.shardOperation(TransportIndicesStatsAction.java:47)
      at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$BroadcastByNodeTransportRequestHandler.onShardOperation(TransportBroadcastByNodeAction.java:409)
      at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$BroadcastByNodeTransportRequestHandler.messageReceived(TransportBroadcastByNodeAction.java:388)
      at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$BroadcastByNodeTransportRequestHandler.messageReceived(TransportBroadcastByNodeAction.java:375)
      at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
      at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
      at java.lang.Thread.run(Unknown Source)
    Caused by: java.nio.file.AccessDeniedException: E:\Share\Elastic_Search\data\cluster1\nodes\0\indices\Products\3\index\_9zmi_Lucene54_0.dvd
      at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
      at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
      at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
      at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
      at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
      at sun.nio.fs.WindowsFileSystemProvider.readAttributes(Unknown Source)
      at java.nio.file.Files.readAttributes(Unknown Source)
      at java.nio.file.Files.size(Unknown Source)
      at org.apache.lucene.store.FSDirectory.fileLength(FSDirectory.java:209)
      at org.apache.lucene.store.FilterDirectory.fileLength(FilterDirectory.java:67)
      at org.apache.lucene.store.FilterDirectory.fileLength(FilterDirectory.java:67)
      at org.elasticsearch.index.store.Store$StoreStatsCache.estimateSize(Store.java:1543)
      at org.elasticsearch.index.store.Store$StoreStatsCache.refresh(Store.java:1532)
      ... 15 more
    [2016-04-06 12:30:41,867][DEBUG][action.admin.cluster.node.stats] [node01] failed to execute on node [L_mbnAHGRHiwIyi3of0GKw]
    RemoteTransportException[[node01][node01/10.250.200.104:9300][cluster:monitor/nodes/stats[n]]]; nested: ElasticsearchException[failed to refresh store stats]; nested: AccessDeniedException[E:\Share\Elastic_Search\data\cluster1\nodes\0\indices\Products\1\index\_a0it.nvd];
    Caused by: ElasticsearchException[failed to refresh store stats]; nested: AccessDeniedException[E:\Share\Elastic_Search\data\cluster1\nodes\0\indices\Products\1\index\_a0it.nvd];
      at org.elasticsearch.index.store.Store$StoreStatsCache.refresh(Store.java:1534)
      at org.elasticsearch.index.store.Store$StoreStatsCache.refresh(Store.java:1519)
      at org.elasticsearch.common.util.SingleObjectCache.getOrRefresh(SingleObjectCache.java:55)
      at org.elasticsearch.index.store.Store.stats(Store.java:293)
      at org.elasticsearch.index.shard.IndexShard.storeStats(IndexShard.java:665)
      at org.elasticsearch.action.admin.indices.stats.CommonStats.<init>(CommonStats.java:134)
      at org.elasticsearch.indices.IndicesService.stats(IndicesService.java:253)
      at org.elasticsearch.node.service.NodeService.stats(NodeService.java:157)
      at org.elasticsearch.action.admin.cluster.node.stats.TransportNodesStatsAction.nodeOperation(TransportNodesStatsAction.java:82)
      at org.elasticsearch.action.admin.cluster.node.stats.TransportNodesStatsAction.nodeOperation(TransportNodesStatsAction.java:44)
      at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:211)
      at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:207)
      at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
      at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
      at java.lang.Thread.run(Unknown Source)
    Caused by: java.nio.file.AccessDeniedException: E:\Share\Elastic_Search\data\cluster1\nodes\0\indices\Products\1\index\_a0it.nvd
      at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
      at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
      at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
      at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
      at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
      at sun.nio.fs.WindowsFileSystemProvider.readAttributes(Unknown Source)
      at java.nio.file.Files.readAttributes(Unknown Source)
      at java.nio.file.Files.size(Unknown Source)
      at org.apache.lucene.store.FSDirectory.fileLength(FSDirectory.java:209)
      at org.apache.lucene.store.FilterDirectory.fileLength(FilterDirectory.java:67)
      at org.apache.lucene.store.FilterDirectory.fileLength(FilterDirectory.java:67)
      at org.elasticsearch.index.store.Store$StoreStatsCache.estimateSize(Store.java:1543)
      at org.elasticsearch.index.store.Store$StoreStatsCache.refresh(Store.java:1532)
      ... 16 more
    [2016-04-06 13:27:45,837][DEBUG][action.admin.cluster.node.stats] [node01] failed to execute on node [L_mbnAHGRHiwIyi3of0GKw]
    RemoteTransportException[[node01][node01/10.250.200.104:9300][cluster:monitor/nodes/stats[n]]]; nested: ElasticsearchException[failed to refresh store stats]; nested: AccessDeniedException[E:\Share\Elastic_Search\data\cluster1\nodes\0\indices\anthem_review\0\index\_t7.fnm];
    Caused by: ElasticsearchException[failed to refresh store stats]; nested: AccessDeniedException[E:\Share\Elastic_Search\data\cluster1\nodes\0\indices\anthem_review\0\index\_t7.fnm];
      at org.elasticsearch.index.store.Store$StoreStatsCache.refresh(Store.java:1534)
      at org.elasticsearch.index.store.Store$StoreStatsCache.refresh(Store.java:1519)
      at org.elasticsearch.common.util.SingleObjectCache.getOrRefresh(SingleObjectCache.java:55)
      at org.elasticsearch.index.store.Store.stats(Store.java:293)
      at org.elasticsearch.index.shard.IndexShard.storeStats(IndexShard.java:665)
      at org.elasticsearch.action.admin.indices.stats.CommonStats.<init>(CommonStats.java:134)
      at org.elasticsearch.indices.IndicesService.stats(IndicesService.java:253)
      at org.elasticsearch.node.service.NodeService.stats(NodeService.java:157)
      at org.elasticsearch.action.admin.cluster.node.stats.TransportNodesStatsAction.nodeOperation(TransportNodesStatsAction.java:82)
      at org.elasticsearch.action.admin.cluster.node.stats.TransportNodesStatsAction.nodeOperation(TransportNodesStatsAction.java:44)
      at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:211)
      at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:207)
      at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
      at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
      at java.lang.Thread.run(Unknown Source)
    Caused by: java.nio.file.AccessDeniedException: E:\Share\Elastic_Search\data\cluster1\nodes\0\indices\anthem_review\0\index\_t7.fnm
      at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
      at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
      at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
      at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
      at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
      at sun.nio.fs.WindowsFileSystemProvider.readAttributes(Unknown Source)
      at java.nio.file.Files.readAttributes(Unknown Source)
      at java.nio.file.Files.size(Unknown Source)
      at org.apache.lucene.store.FSDirectory.fileLength(FSDirectory.java:209)
      at org.apache.lucene.store.FilterDirectory.fileLength(FilterDirectory.java:67)
      at org.apache.lucene.store.FilterDirectory.fileLength(FilterDirectory.java:67)
      at org.elasticsearch.index.store.Store$StoreStatsCache.estimateSize(Store.java:1543)
      at org.elasticsearch.index.store.Store$StoreStatsCache.refresh(Store.java:1532)
      ... 16 more
    [2016-04-06 18:26:11,254][DEBUG][action.admin.cluster.node.stats] [node01] failed to execute on node [BR9PT4QVRuy7VqE5iTlJLQ]
    RemoteTransportException[[LDESMETA03][10.250.200.29:9300][cluster:monitor/nodes/stats[n]]]; nested: ElasticsearchException[failed to refresh store stats]; nested: NotSerializableExceptionWrapper[E:\Share\Elastic_Search\data\cluster1\nodes\0\indices\mma_review\0\index\_rbj.cfe];
    Caused by: ElasticsearchException[failed to refresh store stats]; nested: NotSerializableExceptionWrapper[E:\Share\Elastic_Search\data\cluster1\nodes\0\indices\mma_review\0\index\_rbj.cfe];
      at org.elasticsearch.index.store.Store$StoreStatsCache.refresh(Store.java:1534)
      at org.elasticsearch.index.store.Store$StoreStatsCache.refresh(Store.java:1519)
      at org.elasticsearch.common.util.SingleObjectCache.getOrRefresh(SingleObjectCache.java:55)
      at org.elasticsearch.index.store.Store.stats(Store.java:293)
      at org.elasticsearch.index.shard.IndexShard.storeStats(IndexShard.java:665)
      at org.elasticsearch.action.admin.indices.stats.CommonStats.<init>(CommonStats.java:134)
      at org.elasticsearch.indices.IndicesService.stats(IndicesService.java:253)
      at org.elasticsearch.node.service.NodeService.stats(NodeService.java:157)
      at org.elasticsearch.action.admin.cluster.node.stats.TransportNodesStatsAction.nodeOperation(TransportNodesStatsAction.java:82)
      at org.elasticsearch.action.admin.cluster.node.stats.TransportNodesStatsAction.nodeOperation(TransportNodesStatsAction.java:44)
      at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:211)
      at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:207)
      at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:299)
      at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
      at java.lang.Thread.run(Unknown Source)
    Caused by: NotSerializableExceptionWrapper[E:\Share\Elastic_Search\data\cluster1\nodes\0\indices\mma_review\0\index\_rbj.cfe]
      at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
      at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
      at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
      at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
      at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
      at sun.nio.fs.WindowsFileSystemProvider.readAttributes(Unknown Source)
      at java.nio.file.Files.readAttributes(Unknown Source)
      at java.nio.file.Files.size(Unknown Source)
      at org.apache.lucene.store.FSDirectory.fileLength(FSDirectory.java:209)
      at org.apache.lucene.store.FilterDirectory.fileLength(FilterDirectory.java:67)
      at org.apache.lucene.store.FilterDirectory.fileLength(FilterDirectory.java:67)
      at org.elasticsearch.index.store.Store$StoreStatsCache.estimateSize(Store.java:1543)
      at org.elasticsearch.index.store.Store$StoreStatsCache.refresh(Store.java:1532)
      ... 16 more

**Comment by clintongormley** [comment] 2016-04-07 10:07
Try changing your `path.data` to:

    path.data: E:\Share\Elastic_Search\data

**Comment by dobariya** [comment] 2016-04-07 10:21
yes before i had the same but after reading some same issues online, found to change the path from backward slash to forward slash.But still its not working.

**Comment by clintongormley** [comment] 2016-04-07 10:29
Are you sure that path is accessible by the user running Elasticsearch, and that the file mentioned actually exists and has a non-zero size?

**Comment by dobariya** [comment] 2016-04-07 10:33
yes its accessible and on that path we have almost 500 indices so it is non-zero

**Comment by clintongormley** [comment] 2016-04-07 10:45
@Mpdreamz do you have any ideas?

**Comment by Mpdreamz** [comment] 2016-04-07 11:47
I don't think its a `path.data` configuration issue, permissions of  that are checked on startup and should prevent the node from starting. 

It might miss a specific extended attributes permission file trying to get the `size()` of that file or the attached EMC drive might not like that. Is `E:\Share` a network share? Does EMC use SMB(2) or CIFS?

Whats the output of calling `icacls E:\Share\Elastic_Search\data\cluster1\nodes\0\indices\mma_review\0\index\_rbj.cfe]` look like?

Are you running Elasticsearch as a service and if so under what account?

**Comment by dobariya** [comment] 2016-04-07 12:18
we are using virtual machine so `E:\Share` is a local drive of that machine.
`EMC use SMB(2)`
There is no file available  like `E:\Share\Elastic_Search\data\cluster1\nodes\0\indices\mma_review\0\index\_rbj.cfe`.

**Comment by Mpdreamz** [comment] 2016-04-07 13:04
This is a wild guess but you could be hit by https://support.microsoft.com/en-us/kb/3035936 possibly?

can you give me the icacls output of any of the parent folders that does exist?

**Comment by dobariya** [comment] 2016-04-07 13:17
E:\Share\Elastic_Search\data\cluster1\nodes\0\indices\mma_review

` BUILTIN\Administrators:(F)
 BUILTIN\Administrators:(I)(OI)(CI)(F)
 NT AUTHORITY\SYSTEM:(I)(OI)(CI)(F)
 CREATOR OWNER:(I)(OI)(CI)(IO)(F)
 BUILTIN\Users:(I)(OI)(CI)(RX)
 BUILTIN\Users:(I)(CI)(AD)
 BUILTIN\Users:(I)(CI)(WD)`

Successfully processed 1 files; Failed processing 0 files

**Comment by dobariya** [comment] 2016-04-08 03:25
FYI,
First we were using EMC storage but after installing elastic hq we found some slow IO errors in HQ so we moved ES to [pure storage](https://www.purestorage.com/) which is blazing fast.Even after moving to pure storage we are receiving these errors..

**Comment by TinLe** [comment] 2016-04-08 03:37
FYI.  I am testing pure storage, but using iSCSI, and I do not see these errors.   The difference is that I am using Linux RHEL 6.6.   So this look like a Windows specific bug.

**Comment by dobariya** [comment] 2016-04-08 04:38
So do we have to try this [https://support.microsoft.com/en-us/kb/3035936] for pure storage as well?

**Comment by dobariya** [comment] 2016-04-16 08:44
We even tried doing above but still same AccessDeniedException

**Comment by dobariya** [comment] 2016-04-19 03:58
We even tried above Microsoft solution but still it says AccessDeniedException on store refresh.
Please look into this.

**Comment by dobariya** [comment] 2016-04-27 10:48
Please provide me updates on this

**Comment by daveslee** [comment] 2016-09-25 20:42
Was this ever resolved? We're seeing a similar issue after upgrading from 1.x to 2.x with ES running on Windows.

**Comment by Mpdreamz** [comment] 2016-09-26 06:08
@daveslee it was not, can you provide some more details about what kind of disks and filesystem you are using? Shared not shared? And if so over what protocol. Also the output of the afformentioned `icacls` would be useful. 

Cc @elastic/microsoft

**Comment by sergfed** [comment] 2016-09-29 07:20
have the same issue.
Elastic 2.3.3 on Windows Server 2012 R2. java 1.8.0_91. 3 master nodes (2 of  them with data). ssd hdd. 
there are several errors per day:

ElasticsearchException[failed to refresh store stats]; nested: AccessDeniedException[E:\_db\elasticsearch-shorteners\nodes\0\indices\shtype-s-160928\1\index\_k98.cfe];
	at org.elasticsearch.index.store.Store$StoreStatsCache.refresh(Store.java:1532)
	at org.elasticsearch.index.store.Store$StoreStatsCache.refresh(Store.java:1517)
	at org.elasticsearch.common.util.SingleObjectCache.getOrRefresh(SingleObjectCache.java:55)
	at org.elasticsearch.index.store.Store.stats(Store.java:293)
	at org.elasticsearch.index.shard.IndexShard.storeStats(IndexShard.java:702)
	at org.elasticsearch.action.admin.indices.stats.CommonStats.<init>(CommonStats.java:134)
	at org.elasticsearch.action.admin.indices.stats.TransportIndicesStatsAction.shardOperation(TransportIndicesStatsAction.java:165)
	at org.elasticsearch.action.admin.indices.stats.TransportIndicesStatsAction.shardOperation(TransportIndicesStatsAction.java:47)
	at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$BroadcastByNodeTransportRequestHandler.onShardOperation(TransportBroadcastByNodeAction.java:420)
	at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$BroadcastByNodeTransportRequestHandler.messageReceived(TransportBroadcastByNodeAction.java:399)
	at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$BroadcastByNodeTransportRequestHandler.messageReceived(TransportBroadcastByNodeAction.java:386)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
	at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:300)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.nio.file.AccessDeniedException: E:\_db\elasticsearch-shorteners\nodes\0\indices\shtype-s-160928\1\index\_k98.cfe
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.readAttributes(Unknown Source)
	at java.nio.file.Files.readAttributes(Unknown Source)
	at java.nio.file.Files.size(Unknown Source)
	at org.apache.lucene.store.FSDirectory.fileLength(FSDirectory.java:210)
	at org.apache.lucene.store.FilterDirectory.fileLength(FilterDirectory.java:67)
	at org.apache.lucene.store.FilterDirectory.fileLength(FilterDirectory.java:67)
	at org.elasticsearch.index.store.Store$StoreStatsCache.estimateSize(Store.java:1541)
	at org.elasticsearch.index.store.Store$StoreStatsCache.refresh(Store.java:1530)
	... 17 more

**Comment by s1monw** [comment] 2016-09-29 07:29
I don't see how this is an Elasticsearch problem. `java.nio.file.AccessDeniedException` is not coming form anything we do. It's NOT an security manager exception. The filesystem doesn't allow to access this file. Somebody or something must be changing permissions on that file while ES is running. I don't think we can do anything about this? @clintongormley @Mpdreamz can we close this?

**Comment by dobariya** [comment] 2016-09-29 07:35
@s1monw : I disagree with you because there was no issue in ES1.x and it started on ES2.x.

**Comment by sergfed** [comment] 2016-09-29 07:47
> "Somebody or something must be changing permissions on that file while ES is running"
then return it back?
I understand your opinion, but it's strange, that we have sporadic errors. Before them and after there are no errors with these files. cluster is ok, node is ok, data is consistent.
It looks like something locks the file for a moment.

**Closed** 2016-10-07 09:24 UTC
Labels: :Packaging, feedback_needed

**Comment by ashitpupu** [comment] 2017-03-07 00:01
Is there any solution to this issue ?? I am encountering the same issue don't know how to proceed.
If any solution please suggest . Using ES 2.3.3 , error started to happen once I have updated my tokenizer to Ngram tokenizer. 
Please let me know if any solution available.

**Comment by sss13579** [comment] 2017-03-07 06:26
It has been fixed in version 2.4.2
