### ISSUE TITLE
Cannot highlight_query using parent document filters

### ISSUE THREAD

**Issue by tomas-fp** [elastic/elasticsearch#20974] opened 2016-10-17 11:38 UTC
**Elasticsearch version**: 2.3.5

**Plugins installed**: None

**JVM version**: 8

**OS version**: Darwin 15.5.0 
#### Issue

**Having the following parent-child document relations in a forums data context**:

thread documet (parent) -> post documet (child)

I wanna highlight the matched fields of first-level, nested and/or parent document fields.

So I'm running the following query:

``` json
{
    "sort": [
        "_score"
    ],
    "highlight": {
        "fields": {
            "*": {
                "fragment_size": 256,
                "number_of_fragments": 0,
                "no_match_size": 0,
                "required_field_match": false,
                "highlight_query": {
                    "bool": {
                        "should": [
                            {
                                "has_parent": {
                                    "parent_type": "thread",
                                    "query": {
                                        "nested": {
                                            "path": "forum",
                                            "query": {
                                                "simple_query_string": {
                                                    "default_operator": "AND",
                                                    "fields": [
                                                        "forum.name"
                                                    ],
                                                    "flags": "OR|AND|NOT",
                                                    "query": "foo"
                                                }
                                            }
                                        }
                                    }
                                }
                            },
                            {
                                "simple_query_string": {
                                    "default_operator": "AND",
                                    "fields": [
                                        "body"
                                    ],
                                    "flags": "OR|AND|NOT",
                                    "query": "foo"
                                }
                            }
                        ]
                    }
                }
            }
        }
    },
    "from": 0,
    "size": 1,
    "query": {
        "bool": {
            "must": [
                {
                    "has_parent": {
                        "query": {
                            "nested": {
                                "path": "forum",
                                "query": {
                                    "simple_query_string": {
                                        "query": "foo",
                                        "fields": [
                                            "forum.name"
                                        ],
                                        "flags": "OR|AND|NOT",
                                        "default_operator": "AND"
                                    }
                                }
                            }
                        },
                        "parent_type": "thread"
                    }
                },
                {
                    "simple_query_string": {
                        "query": "foo",
                        "fields": [
                            "body"
                        ],
                        "flags": "OR|AND|NOT",
                        "default_operator": "AND"
                    }
                },
                {
                    "has_parent": {
                        "inner_hits": {
                            "size": 1
                        },
                        "type": "thread",
                        "query": {
                            "match_all": {}
                        }
                    }
                }
            ]
        }
    }
}
```

And getting the following error:

```
search_phase_execution_exception'
can't load global ordinals for reader of type: class org.apache.lucene.search.highlight.WeightedSpanTermExtractor$DelegatingLeafReader must be a DirectoryReader
```

Not sure if this is an existent limitation or bug in ElasticSearch, since I saw similar issues related to `highlight_query` filters being reported and not solved yet.

**Comment by tomas-fp** [comment] 2017-02-07 15:10
Any update regarding this issue? The server is also replying with a `200 OK` status code when this error occurs.

Is there any workaround idea? I'm considering using `inner_hits` + `highlight` for parent documents highlighting.

**Comment by clintongormley** [comment] 2017-02-09 21:08
@tomas-fp it would be very helpful if you could provide a complete curl recreation - something we can copy and paste to test.  Also worth checking if anything has changed in 5.2

**Comment by colings86** [comment] 2018-03-26 14:45
@elastic/es-search-aggs

**Comment by cbuescher** [comment] 2021-06-14 09:39
I'm closing this issue because it is lacking a complete reproduction and the reported version is no longer maintained. The current parent/child logic also has changed, so please re-open this as a new issue if this still happens for you on 6.x/7.x versions.

**Closed by cbuescher** 2021-06-14 09:39 UTC
Labels: :Search/Highlighting, >bug, Team:Search, help wanted
