### ISSUE TITLE
[CI] IntegTestZipClientYamlTestSuiteIT#{p0=search.aggregation/190_percentiles_hdr_metric/Non-keyed test} test failure

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#26693] opened 2017-09-18 14:27 UTC
Build url: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+aggressive-opts/273/consoleText

Does not reproduce.

```
1> [2017-09-18T05:39:11,591][INFO ][o.e.t.r.IntegTestZipClientYamlTestSuiteIT] Stash dump on failure [{
  1>   "stash" : {
  1>     "body" : {
  1>       "took" : 34,
  1>       "timed_out" : false,
  1>       "_shards" : {
  1>         "total" : 5,
  1>         "successful" : 5,
  1>         "skipped" : 0,
  1>         "failed" : 0
  1>       },
  1>       "hits" : {
  1>         "total" : 3,
  1>         "max_score" : 1.0,
  1>         "hits" : [
  1>           {
  1>             "_index" : "test_1",
  1>             "_type" : "doc",
  1>             "_id" : "4",
  1>             "_score" : 1.0,
  1>             "_source" : {
  1>               "int_field" : 151,
  1>               "double_field" : 151.0,
  1>               "string_field" : "foo"
  1>             }
  1>           },
  1>           {
  1>             "_index" : "test_1",
  1>             "_type" : "doc",
  1>             "_id" : "1",
  1>             "_score" : 1.0,
  1>             "_source" : {
  1>               "int_field" : 1,
  1>               "double_field" : 1.0,
  1>               "string_field" : "foo"
  1>             }
  1>           },
  1>           {
  1>             "_index" : "test_1",
  1>             "_type" : "doc",
  1>             "_id" : "3",
  1>             "_score" : 1.0,
  1>             "_source" : {
  1>               "int_field" : 101,
  1>               "double_field" : 101.0,
  1>               "string_field" : "foo"
  1>             }
  1>           }
  1>         ]
  1>       },
  1>       "aggregations" : {
  1>         "percentiles_int" : {
  1>           "values" : [
  1>             {
  1>               "key" : 5.0,
  1>               "value" : 1.0
  1>             },
  1>             {
  1>               "key" : 25.0,
  1>               "value" : 1.0
  1>             },
  1>             {
  1>               "key" : 50.0,
  2> REPRODUCE WITH: gradle :distribution:integ-test-zip:integTestRunner -Dtests.seed=EA3E1BF5140E4CE6 -Dtests.class=org.elasticsearch.test.rest.IntegTestZipClientYamlTestSuiteIT -Dtests.method="test {p0=search.aggregation/190_percentiles_hdr_metric/Non-keyed test}" -Dtests.security.manager=true -Dtests.jvm.argline="-XX:+AggressiveOpts" -Dtests.locale=en-AU -Dtests.timezone=Etc/GMT+6
  1>               "value" : 101.0615234375
  1>             }
  1>           ]
  1>         }
  1>       }
  1>     }
  1>   }
  1> }]
FAILURE 0.27s | IntegTestZipClientYamlTestSuiteIT.test {p0=search.aggregation/190_percentiles_hdr_metric/Non-keyed test} <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Failure at [search.aggregation/190_percentiles_hdr_metric:407]: hits.total didn't match expected value:
   >                     hits.total: expected [4] but was [3]
   > 	at __randomizedtesting.SeedInfo.seed([EA3E1BF5140E4CE6:626A242FBAF2211E]:0)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:349)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:329)
   > 	at java.lang.Thread.run(Thread.java:745)
   > Caused by: java.lang.AssertionError: hits.total didn't match expected value:
   >                     hits.total: expected [4] but was [3]
   > 	at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:87)
   > 	at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:76)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:345)
   > 	... 38 more
```

**Comment by colings86** [comment] 2017-09-18 14:48
@polyfractal Could you look at this since I think you have been adding the YAML tests for aggregations recently?

**Comment by polyfractal** [comment] 2017-09-18 15:06
:+1: on it!

**Comment by polyfractal** [comment] 2017-10-26 14:28
I also cannot reproduce this, and it's really bizarre.  Doc 3 wasn't returned in the search hits, so either it wasn't available for search at the time or it didn't get indexed, unclear which.  The bulk has `refresh: true` so it should be search-able immediately.  

So the doc failing to index seems most likely, but impossible to know since we don't have the bulk response from the setup.  Maybe the index wasn't fully initialized despite the create index API succeeding?  Dunno.

Closing since I don't think there's anything we can do here.

**Closed by polyfractal** 2017-10-26 14:28 UTC
Labels: test
