### ISSUE TITLE
Index creation with dynamic mapping is order sensistive

### ISSUE THREAD

**Issue by judewood** [elastic/elasticsearch#20446] opened 2016-09-13 12:11 UTC
**Elasticsearch version**: 1.7.1

**Plugins installed**: []

**JVM version**:

**OS version**:

**Description of the problem including expected versus actual behavior**:
Creating an index appears to be sensitive to the order that settings and mappings are specified in.

**Steps to reproduce**:
 1. Create an index with the following body

```json
{
    "settings":{
          "analysis":{
             "analyzer":{
                "keylower":{
                   "tokenizer":"keyword",
                   "filter":"lowercase"
                }
             }
          }
       }
    },
    "mappings":{
        "siteprofile":{
            "dynamic_templates":[
            {
                "match_siteData_strings":{
                    "match_mapping_type":"string",
                    "path_match":"siteData.*",
                    "mapping":{
                        "type":"string",
                        "analyzer":"keylower"
                    }
                }
            },
            {
                "match_siteData_integers":{
                    "match_mapping_type":"integer",
                    "path_match":"siteData.*",
                    "mapping":{
                        "type":"string",
                        "index":"not_analyzed"
                    }
                }
            }
            ]
        }
    }
}
```

 then get its mappings Response is 

```json
{
  "myindex": {
    "mappings": {}
  }
}
```

 2.If the order of settings and mappings in the body are swapped then the index mappings are created correctly.

**Comment by dadoonet** [comment] 2016-09-13 12:14
I sent your JSON document to https://jsonformatter.curiousconcept.com/ and I can't parse it.
Are you sure it's what you put here?

**Comment by dadoonet** [comment] 2016-09-13 12:15
I believe you wanted to use:

```json
{
   "settings":{
      "analysis":{
         "analyzer":{
            "keylower":{
               "tokenizer":"keyword",
               "filter":"lowercase"
            }
         }
      }
   },
   "mappings":{
      "siteprofile":{
         "dynamic_templates":[
            {
               "match_siteData_strings":{
                  "match_mapping_type":"string",
                  "path_match":"siteData.",
                  "mapping":{
                     "type":"string",
                     "analyzer":"keylower"
                  }
               }
            },
            {
               "match_siteData_integers":{
                  "match_mapping_type":"integer",
                  "path_match":"siteData.",
                  "mapping":{
                     "type":"string",
                     "index":"not_analyzed"
                  }
               }
            }
         ]
      }
   }
}
```

**Comment by dadoonet** [comment] 2016-09-13 12:17
With the right JSON document, I can't reproduce your problem.
Closing.

Please ask on discuss.elastic.co next time you have a doubt.

**Closed by dadoonet** 2016-09-13 12:17 UTC

**Comment by judewood** [comment] 2016-09-13 12:54
Thank you.  You are correct I had an extra } in the body.
