### ISSUE TITLE
synonym search in dictionary elasticsearch not result

### ISSUE THREAD

**Issue by zonorion** [elastic/elasticsearch#24556] opened 2017-05-09 04:30 UTC
Hi all,
I want use synonym filter for search, my config 

`analysis: {
filter: {
synonym_filter: {
type: "synonym",
synonyms: [
"tp, saigon, sai gon, hcm, tphcm, sài gòn, sàigòn => Thành phố Hồ Chí Minh",
"tp, hn, ha noi, noi ha => Hà Nội"
]
}
},
analyzer: {
synonym_analyzer: {
filter: [
"standard",
"synonym_filter",
"lowercase",
"asciifolding"
],
type: "custom",
tokenizer: "whitespace"
}
}
}`

But when i search: 
`{
  "query": {
    "multi_match": {
      "query": "tp",
      "type": "best_fields",
      "fields": [
        "name"
      ],
      "operator": "and"
    }
  }
}`

Elastic only result one doc "Thành phố Hồ Chí Minh". Could u tell me why and how to fix it.
Thanks all.

**Comment by johtani** [comment] 2017-05-09 04:47
@zonorion  Please ask this question on our [discuss forum](https://discuss.elastic.co/c/elasticsearch) where we can provide better support for your question.

Elastic uses GitHub issues for confirmed bugs and feature requests only. Since this does not appear to be a bug in Elasticsearch, I'm going to close this ticket.

**Closed by johtani** 2017-05-09 04:47 UTC
