### ISSUE TITLE
Support highlight encoders provided via plugins

### ISSUE THREAD

**Issue by synhershko** [elastic/elasticsearch#3588] opened 2013-08-28 08:32 UTC
Instead of having them hardcoded like this:

```
    Encoder encoder = field.encoder().equals("html") ? Encoders.HTML : Encoders.DEFAULT;
```

(taken from FVH)

Will be much easier to fix issues like #3587 ad-hoc

**Comment by synhershko** [comment] 2017-07-07 09:54
I believe this can be closed now :)

**Comment by javanna** [comment] 2017-07-12 21:00
hi @synhershko it can be closed because we fixed it or because you are tired of waiting for us to fix it? :)

Besides jokes, I see the same problem in the unified highlighter. What am I missing?

**Comment by jimczi** [comment] 2018-03-14 09:31
The bug mentioned in the issue is fixed in Lucene:
https://issues.apache.org/jira/browse/LUCENE-5191
I am also closing this issue because I don't think we should provide a way to define custom encoders.
We have a simple `html` encoder that should be enough for most of the cases and if more complex encoding is required the solution is to rewrite the raw snippets (created by the `default` encoder)
in the response client side.

**Closed by jimczi** 2018-03-14 09:31 UTC
Labels: :Search/Highlighting, >enhancement, adoptme, low hanging fruit
