### ISSUE TITLE
Date histogram aggregation Milliseconds problem using minutes in date_range

### ISSUE THREAD

**Issue by deniseoboschetti** [elastic/elasticsearch#8200] opened 2014-10-22 20:13 UTC
When using minutes in the date range the returned keys are wrong (minutes and milliseconds).

Using the query according to:
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-aggregations-bucket-daterange-aggregation.html

I'm using ElasticSearch Version 1.3.2.

Example query:
"date_range":{
"field":"doc_published","
format":"dateOptionalTime",
"ranges":[
{"from":"20140101T00:10:00","to":"20140101T00:15:00"},{"from":"20140101T00:15:00","to":"20140101T00:20:00"}]
}

Example response:
{"key":"20140101-01-01T00:10:00.064Z-20140101-01-01T00:14:59.968Z",
"from":6.3549803335740006E17,
"from_as_string":"20140101-01-01T00:10:00.064Z",
"to":6.3549803335769997E17,
"to_as_string":"20140101-01-01T00:14:59.968Z"},

{"key":"20140101-01-01T00:14:59.968Z-20140101-01-01T00:20:00.000Z",
"from":6.3549803335769997E17,
"from_as_string":"20140101-01-01T00:14:59.968Z",
"to":6.35498033358E17,
"to_as_string":"20140101-01-01T00:20:00.000Z"}

The returning keys are invalid:
RECEIVED: 20140101-01-01T00:10:00.064Z-20140101-01-01T00:14:59.968Z
Should be: 
20140101-01-01T00:10:00.000Z-20140101-01-01T00:14:59.968Z 

RECEIVED: 20140101-01-01T00:14:59.968Z-20140101-01-01T00:20:00.000Z
Should be: 
20140101-01-01T00:15:00.000Z-20140101-01-01T00:20:00.000Z

**Comment by clintongormley** [comment] 2015-11-21 20:06
I'm unable to reproduce this in 2.1.0 or in 1.3.2.  I'm going to close this, but please feel free to reopen if you can replicate.

**Closed by clintongormley** 2015-11-21 20:06 UTC
