### ISSUE TITLE
[CI] RegressionIT.testStopAndRestart failure

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#67581] opened 2021-01-15 15:01 UTC
**Build scan**: https://gradle-enterprise.elastic.co/s/6vlpz4tjjwwus

**Repro line**: `gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.ml.integration.RegressionIT.testStopAndRestart" -Dtests.seed=CB002B982AFC9FE0 -Dtests.security.manager=true -Dtests.locale=bg-BG -Dtests.timezone=America/Montreal -Druntime.java=11`

**Reproduces locally?**: No

**Applicable branches**: `master`, `7.x`

**Failure excerpt**: 

```
org.elasticsearch.xpack.ml.integration.RegressionIT > testStopAndRestart FAILED
    java.lang.AssertionError: Stats were: {"id":"regression_stop_and_restart","state":"started","progress":[{"phase":"reindexing","progress_percent":100},{"phase":"loading_data","progress_percent":100},{"phase":"feature_selection","progress_percent":0},{"phase":"coarse_parameter_search","progress_percent":0},{"phase":"fine_tuning_parameters","progress_percent":0},{"phase":"final_training","progress_percent":0},{"phase":"writing_results","progress_percent":0},{"phase":"inference","progress_percent":0}],"data_counts":{"training_docs_count":350,"test_docs_count":0,"skipped_docs_count":0},"memory_usage":{"timestamp":1610702364954,"peak_usage_bytes":12916,"status":"ok"},"node":{"id":"ZBQn4V3tQ7unCXAoAcsMzw","name":"javaRestTest-0","ephemeral_id":"Ocv37ZNXQBWCrMdnfHVdLw","transport_address":"127.0.0.1:59082","attributes":{"testattr":"test","ml.machine_memory":"103077928960","ml.max_open_jobs":"20","xpack.installed":"true","ml.max_jvm_size":"518979584","transform.node":"true"}},"assignment_explanation":""}
    Expected: <stopped>
         but: was <started>
        at __randomizedtesting.SeedInfo.seed([CB002B982AFC9FE0:BC48A9663E169940]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.assertIsStopped(MlNativeDataFrameAnalyticsIntegTestCase.java:210)
        at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.lambda$waitUntilAnalyticsIsStopped$0(MlNativeDataFrameAnalyticsIntegTestCase.java:156)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:955)
        at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.waitUntilAnalyticsIsStopped(MlNativeDataFrameAnalyticsIntegTestCase.java:156)
        at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.waitUntilAnalyticsIsStopped(MlNativeDataFrameAnalyticsIntegTestCase.java:152)
        at org.elasticsearch.xpack.ml.integration.RegressionIT.testStopAndRestart(RegressionIT.java:326)
REPRODUCE WITH: gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.ml.integration.RegressionIT.testStopAndRestart" -Dtests.seed=CB002B982AFC9FE0 -Dtests.security.manager=true -Dtests.locale=bg-BG -Dtests.timezone=America/Montreal -Druntime.java=11
```

**Comment by dimitris-athanasiou** [comment] 2021-01-15 15:48
Looking into the logs, these are the relevant bits:

```
[2021-01-15T09:19:22,664][INFO ][o.e.x.m.a.TransportStartDataFrameAnalyticsAction] [javaRestTest-0] [regression_stop_and_restart] Starting data frame analytics from state [stopped]
[2021-01-15T09:19:22,731][INFO ][o.e.x.c.m.u.MlIndexAndAlias] [javaRestTest-0] About to create first concrete index [.ml-state-000001] with alias [.ml-state-write]
[2021-01-15T09:19:22,913][INFO ][o.e.x.c.m.u.MlIndexAndAlias] [javaRestTest-0] About to create first concrete index [.ml-stats-000001] with alias [.ml-stats-write]
[2021-01-15T09:19:23,103][INFO ][o.e.x.m.d.s.ReindexingStep] [javaRestTest-0] [regression_stop_and_restart] Creating destination index [regression_stop_and_restart_source_index_results]
[2021-01-15T09:19:23,308][INFO ][o.e.x.m.d.s.ReindexingStep] [javaRestTest-0] [regression_stop_and_restart] Started reindexing
[2021-01-15T09:19:23,719][INFO ][o.e.x.m.d.p.AnalyticsProcessManager] [javaRestTest-0] [regression_stop_and_restart] Started loading data
[2021-01-15T09:19:23,869][INFO ][o.e.x.m.a.TransportStopDataFrameAnalyticsAction] [javaRestTest-0] [regression_stop_and_restart] Stopping task with force [false]
[2021-01-15T09:19:23,870][INFO ][o.e.x.m.d.p.AnalyticsProcessManager] [javaRestTest-0] [regression_stop_and_restart] Closing process
[2021-01-15T09:19:23,885][INFO ][o.e.x.m.d.p.AnalyticsProcessManager] [javaRestTest-0] [regression_stop_and_restart] Closed process
[2021-01-15T09:19:23,886][INFO ][o.e.x.m.d.DataFrameAnalyticsManager] [javaRestTest-0] [regression_stop_and_restart] Marking task completed
[2021-01-15T09:19:24,304][INFO ][o.e.x.m.a.TransportStartDataFrameAnalyticsAction] [javaRestTest-0] [regression_stop_and_restart] Starting data frame analytics from state [stopped]
[2021-01-15T09:19:24,850][INFO ][o.e.x.m.d.p.AnalyticsProcessManager] [javaRestTest-0] [regression_stop_and_restart] Started loading data
[2021-01-15T09:20:30,042][INFO ][o.e.x.m.a.TransportStopDataFrameAnalyticsAction] [javaRestTest-0] [regression_stop_and_restart] Stopping task with force [false]
[2021-01-15T09:20:30,043][INFO ][o.e.x.m.d.p.AnalyticsProcessManager] [javaRestTest-0] [regression_stop_and_restart] Closing process
[2021-01-15T09:20:30,044][INFO ][o.e.x.m.d.p.AnalyticsProcessManager] [javaRestTest-0] [regression_stop_and_restart] Closed process
[2021-01-15T09:20:30,045][INFO ][o.e.x.m.d.DataFrameAnalyticsManager] [javaRestTest-0] [regression_stop_and_restart] Marking task completed
```

Nothing seems wrong except it took over a minute just to finish loading data after we restarted the job. This is insanely long for what the job's supposed to do so I can only imagine the CI worker happened to be incredibly busy.

I'll leave the issue open for now to see if it fails again or was just a really bad moment for our CI worker.

**Comment by hendrikmuhs** [comment] 2021-01-18 11:07
new failure: https://gradle-enterprise.elastic.co/s/gz76vkhfzexoe

**Comment by martijnvg** [comment] 2021-01-19 08:21
Two more instances:
* https://gradle-enterprise.elastic.co/s/vbonfw4c6swwk
* https://gradle-enterprise.elastic.co/s/ytxl4l42p2feo

**Comment by dimitris-athanasiou** [comment] 2021-01-19 09:48
OK, those look slightly different. I'm going to add some logging to figure this out.

**Comment by martijnvg** [comment] 2021-01-19 09:49
I'm seeing more of t[heses failures in the past and today](https://build-stats.elastic.co/app/kibana#/discover/0d588210-3843-11ea-a7eb-15e193b310ea?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:e58bf320-7efd-11e8-bf69-63c8ef516157,key:project,negate:!f,params:(query:elasticsearch,type:phrase),type:phrase,value:elasticsearch),query:(match:(project:(query:elasticsearch,type:phrase))))),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'project:elasticsearch%20AND%20(branch:%227.x%22%20OR%20branch:%22master%22%20OR%20branch:%227.11%22%20OR%20branch:%226.8%22)%20AND%20test:%22testStopAndRestart%22%20AND%20class%3Dorg.elasticsearch.xpack.ml.integration.RegressionIT'),sort:!(time,desc))).

Also it looks like `ClassificationIT#testStopAndRestart` fails for the same reason. Are [these failures ](https://build-stats.elastic.co/app/kibana#/discover/0d588210-3843-11ea-a7eb-15e193b310ea?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:e58bf320-7efd-11e8-bf69-63c8ef516157,key:project,negate:!f,params:(query:elasticsearch,type:phrase),type:phrase,value:elasticsearch),query:(match:(project:(query:elasticsearch,type:phrase))))),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'project:elasticsearch%20AND%20(branch:%227.x%22%20OR%20branch:%22master%22%20OR%20branch:%227.11%22%20OR%20branch:%226.8%22)%20AND%20test:%22testStopAndRestart%22%20AND%20class%3Dorg.elasticsearch.xpack.ml.integration.ClassificationIT'),sort:!(time,desc)))related to this failure?

Maybe we should mute these tests?

**Comment by dimitris-athanasiou** [comment] 2021-01-19 09:50
Yes, they're related. Please mute for now.

**Comment by dimitris-athanasiou** [comment] 2021-01-21 14:07
I have found the most likely reason for this failure. I will raise the fix PR shortly.

**Comment by valeriy42** [comment] 2021-01-25 09:52
The issue seems to persist https://gradle-enterprise.elastic.co/s/okm742yltgzgi . It happens mostly on Windows but I also [noticed](https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=Europe/Berlin&tests.container=org.elasticsearch.xpack.ml.integration.RegressionIT&tests.sortField=FAILED&tests.test=testStopAndRestart&tests.unstableOnly=true) some linux failures https://gradle-enterprise.elastic.co/s/b7wmuh4a3xh2o .

**Comment by dnhatn** [comment] 2021-03-30 16:17
This test failed again on Windows: https://gradle-enterprise.elastic.co/s/ydvmuwliqbu72

```
  2> REPRODUCE WITH: gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.ml.integration.ClassificationIT.testStopAndRestart" -Dtests.seed=5D140C9A5AB1BF87 -Dtests.security.manager=true -Dtests.locale=sr-BA -Dtests.timezone=Asia/Kuala_Lumpur -Druntime.java=8  
```

```
  2> java.lang.AssertionError: Stats were: {"id":"classification_stop_and_restart","state":"started","progress":[{"phase":"reindexing","progress_percent":100},{"phase":"loading_data","progress_percent":100},{"phase":"feature_selection","progress_percent":0},{"phase":"coarse_parameter_search","progress_percent":0},{"phase":"fine_tuning_parameters","progress_percent":0},{"phase":"final_training","progress_percent":0},{"phase":"writing_results","progress_percent":0},{"phase":"inference","progress_percent":0}],"data_counts":{"training_docs_count":350,"test_docs_count":0,"skipped_docs_count":0},"memory_usage":{"timestamp":1617117390593,"peak_usage_bytes":28590,"status":"ok"},"node":{"id":"n1NjGT2XSRG0cHcVU_352Q","name":"javaRestTest-1","ephemeral_id":"kUNF55z-Sxuc_DHRr4pm8w","transport_address":"127.0.0.1:58711","attributes":{"testattr":"test","ml.machine_memory":"103077900288","ml.max_open_jobs":"20","xpack.installed":"true","ml.max_jvm_size":"518979584","transform.node":"true"}},"assignment_explanation":""}
    Expected: <stopped>
         but: was <started>
        at __randomizedtesting.SeedInfo.seed([5D140C9A5AB1BF87:2A5C8E644E5BB927]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.assertIsStopped(MlNativeDataFrameAnalyticsIntegTestCase.java:224)
        at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.lambda$waitUntilAnalyticsIsStopped$0(MlNativeDataFrameAnalyticsIntegTestCase.java:160)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1017)
        at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.waitUntilAnalyticsIsStopped(MlNativeDataFrameAnalyticsIntegTestCase.java:160)
        at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.waitUntilAnalyticsIsStopped(MlNativeDataFrameAnalyticsIntegTestCase.java:156)
        at org.elasticsearch.xpack.ml.integration.ClassificationIT.testStopAndRestart(ClassificationIT.java:509)
```

**Comment by dnhatn** [comment] 2021-03-30 22:19
Closing this in favor #70698.

**Closed by dnhatn** 2021-03-30 22:19 UTC
Labels: :ml, >test-failure, Team:ML
