### ISSUE TITLE
.prepareSearch("index").setTypes("mytype") does not set types

### ISSUE THREAD

**Issue by rookie7799** [elastic/elasticsearch#11429] opened 2015-05-29 18:03 UTC
Hi,
When I print SearchRequestBuilder to see json the "types" : [ ]
Is this normal ?

**Comment by clintongormley** [comment] 2015-05-29 18:48
Hi @rookie7799 

Please can you ask questions like this on the forum instead https://discuss.elastic.co/c/elasticsearch

thanks

**Comment by dadoonet** [comment] 2015-05-29 20:32
@clintongormley Actually, it looks like a bug to me. 

```java
SearchRequestBuilder builder = client().prepareSearch("index").setTypes("type");
System.out.println("builder = " + builder);
```

Gives

```
builder = { }
```

I think this change did that: https://github.com/elastic/elasticsearch/pull/9944/files#diff-8e501ed49a549876267b54efd2347077R170

I pinged @javanna about it. Let's see what he thinks about it but we might need to reopen this issue although it might be a duplicate of #9962.

**Comment by clintongormley** [comment] 2015-05-29 20:37
thanks for spotting @dadoonet - reopening

**Comment by javanna** [comment] 2015-05-30 06:49
The types do get set, but you don't see them as the output of the `toString`, simply because the toString only prints out the content of what would be the request body, the actual search request and not what would be in the url, like types, index etc. it is something that we'll have to get back to at some point, but kinda expected for now.

**Comment by dadoonet** [comment] 2015-05-30 07:22
Thanks @javanna. Should we close this issue? Is this going to be fixed with  https://github.com/elastic/elasticsearch/issues/9962?

**Comment by javanna** [comment] 2015-06-02 08:44
yes I'd close in favour of #9962, where we have to discuss what `toString` should do in general and follow the same convention everywhere.

**Closed by javanna** 2015-06-02 08:44 UTC
Labels: :Java API, bug
