### ISSUE TITLE
Tribe enabled with a cluster with unknown host returned for DNS exits even if some clusters are accessible 

### ISSUE THREAD

**Issue by rzenker** [elastic/elasticsearch#20110] opened 2016-08-22 23:17 UTC
**Elasticsearch version**: 2.3.5 (using https://hub.docker.com/_/elasticsearch/)

**Plugins installed**: head, license, cloud-aws, marvel-agent (marvel is disabled on tribe and master-only nodes)

**JVM version**: https://hub.docker.com/_/elasticsearch/

**OS version**: https://hub.docker.com/_/elasticsearch/

**Description of the problem including expected versus actual behavior**:
Configure tribe for all possible remote clusters, but only some may be available at a single time.  This configuration uses service discovery and DNS because the IPs will be dynamic. If a cluster is not yet up or DNS fails to resolve a remote entry, elasticsearch exits.  If i configure only the DNS cluster entries that are up at the time of startup, then it appears to work as intended.

My assumption is that it would continue retrying at a backoff interval and serving requests for the clusters it can successfully connect to.  I'm not sure if this behavior would also affect an extended WAN outage, but would prefer a similar robust behavior.

**Steps to reproduce**:
 1.  Configure tribe nodes with DNS with at least one being unknown host at startup:
```     "-Des.node.data=false",
     "-Des.node.master=false",
     "-Des.marvel.enabled=false",
     "-Des.tribe.dc1.cluster.name=dc1-elasticsearch",
     "-Des.tribe.dc1.discovery.zen.ping.unicast.hosts=master-elasticsearch-dc1",
     "-Des.tribe.dc2.cluster.name=dc2-elasticsearch",
     "-Des.tribe.dc2.discovery.zen.ping.unicast.hosts=master-elasticsearch-dc2",
```
 2.  elasticsearch will exit with exception below.

**Provide logs (if relevant)**:
Exception in thread "main" java.lang.IllegalArgumentException: Failed to resolve address for [master-elasticsearch-dc2]
Likely root cause: java.net.UnknownHostException: master-elasticsearch-dc2: unknown error
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
        at java.net.InetAddress.getAllByName(InetAddress.java:1192)
        at java.net.InetAddress.getAllByName(InetAddress.java:1126)
        at org.elasticsearch.transport.netty.NettyTransport.parse(NettyTransport.java:733)
        at org.elasticsearch.transport.netty.NettyTransport.addressesFromString(NettyTransport.java:685)
        at org.elasticsearch.transport.TransportService.addressesFromString(TransportService.java:424)
        at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing.<init>(UnicastZenPing.java:160)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at <<<guice>>>
        at org.elasticsearch.node.Node.<init>(Node.java:213)
        at org.elasticsearch.tribe.TribeClientNode.<init>(TribeClientNode.java:35)
        at org.elasticsearch.tribe.TribeService.<init>(TribeService.java:146)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at <<<guice>>>
        at org.elasticsearch.node.Node.<init>(Node.java:213)
        at org.elasticsearch.node.Node.<init>(Node.java:140)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)

**Comment by clintongormley** [comment] 2016-08-23 12:52
Hi @rzenker 

This is indeed how it works today.  DNS resolution only happens at startup.  Closing as duplicate of https://github.com/elastic/elasticsearch/issues/14441

**Closed by clintongormley** 2016-08-23 12:52 UTC
