### ISSUE TITLE
[CI] ThirdPartyAuditTaskFuncTest reports violations and ignores compile only failing

### ISSUE THREAD

**Issue by fcofdez** [elastic/elasticsearch#96074] opened 2023-05-12 15:28 UTC
**Build scan:**
https://gradle-enterprise.elastic.co/s/57ctn5tfrizdk/tests/:integTest/org.elasticsearch.gradle.internal.precommit.ThirdPartyAuditTaskFuncTest/reports%20violations%20and%20ignores%20compile%20only

**Reproduction line:**
```
null
```

**Applicable branches:**
8.8

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.gradle.internal.precommit.ThirdPartyAuditTaskFuncTest&tests.test=reports%20violations%20and%20ignores%20compile%20only

**Failure excerpt:**
```
org.spockframework.runtime.ConditionNotSatisfiedError: Condition not satisfied:

normalized(givenOutput).contains(normalized(expected))
|          |            |        |          |
|          |            false    |          Forbidden APIs output:
|          |                     |          DEBUG: Classpath: [file:./build/precommit/thirdPartyAudit/thirdPartyAudit/]
|          |                     |          DEBUG: Detected Java 9 or later with module system.
|          |                     |          ERROR: Forbidden class/interface use: java.io.File [non-public internal runtime class]
|          |                     |          ERROR:   in org.acme.TestingIO (method declaration of 'getFile()')
|          |                     |          ERROR: Scanned 1 class file(s) for forbidden API invocations (in 0.00s), 1 error(s).
|          |                     |          ERROR: Check for forbidden API calls failed, see log.
|          |                     |          ==end of forbidden APIs==
|          |                     |          Classes with violations:
|          |                     |            * org.acme.TestingIO
|          |                     Forbidden APIs output:
|          |                     DEBUG: Classpath: [file:./build/precommit/thirdPartyAudit/thirdPartyAudit/]
|          |                     DEBUG: Detected Java 9 or later with module system.
|          |                     ERROR: Forbidden class/interface use: java.io.File [non-public internal runtime class]
|          |                     ERROR:   in org.acme.TestingIO (method declaration of 'getFile()')
|          |                     ERROR: Scanned 1 class file(s) for forbidden API invocations (in 0.00s), 1 error(s).
|          |                     ERROR: Check for forbidden API calls failed, see log.
|          |                     ==end of forbidden APIs==
|          |                     Classes with violations:
|          |                       * org.acme.TestingIO
|          Encryption of the configuration cache is enabled.
|          Calculating task graph as no configuration cache is available for tasks: :thirdPartyAudit
|          =======================================
|          Elasticsearch Build Hamster says Hello!
|            Gradle Version        : 8.1.1
|            OS Info               : Windows Server 2012 R2 6.3 (amd64)
|            JDK Version           : 17.0.2+8-86 (Oracle)
|            JAVA_HOME             : C:/Users/jenkins/.java/openjdk17
|            Random Testing Seed   : 66E3032C7B887E33
|            In FIPS 140 mode      : false
|          =======================================
|          > Task :thirdPartyAuditResources
|           
|          > Task :thirdPartyAudit FAILED
|          Forbidden APIs output:
|          DEBUG: Classpath: [file:/./build/precommit/thirdPartyAudit/thirdPartyAudit/]
|          DEBUG: Detected Java 9 or later with module system.
|          ERROR: Forbidden class/interface use: java.io.File [non-public internal runtime class]
|          ERROR:   in org.acme.TestingIO (method declaration of 'getFile()')
|          ERROR: Scanned 1 class file(s) for forbidden API invocations (in 0.00s), 1 error(s).
|          ERROR: Check for forbidden API calls failed, see log.
|          ==end of forbidden APIs==
|          Classes with violations:
|            * org.acme.TestingIO
|           
|          0 problems were found storing the configuration cache.
|           
|          See the complete report at file:///./build/reports/configuration-cache/cddqacafjoi648vpdvuchz930/1d8zxjua6a25p7moresmixwz2/configuration-cache-report.html
|           
|          FAILURE: Build failed with an exception.
|           
|          * What went wrong:
|          Execution failed for task ':thirdPartyAudit'.
|          > Audit of third party dependencies failed
|           
|          * Try:
|          > Run with --stacktrace option to get the stack trace.
|          > Run with --info or --debug option to get more log output.
|          > Run with --scan to get full insights.
|           
|          * Get more help at https://help.gradle.org
|           
|          BUILD FAILED in 5s
|          2 actionable tasks: 2 executed
|          Configuration cache entry stored.
Encryption of the configuration cache is enabled.
Calculating task graph as no configuration cache is available for tasks: :thirdPartyAudit
=======================================
Elasticsearch Build Hamster says Hello!
  Gradle Version        : 8.1.1
  OS Info               : Windows Server 2012 R2 6.3 (amd64)
  JDK Version           : 17.0.2+8-86 (Oracle)
  JAVA_HOME             : C:/Users/jenkins/.java/openjdk17
  Random Testing Seed   : 66E3032C7B887E33
  In FIPS 140 mode      : false
=======================================
> Task :thirdPartyAuditResources
 
> Task :thirdPartyAudit FAILED
Forbidden APIs output:
DEBUG: Classpath: [file:/./build/precommit/thirdPartyAudit/thirdPartyAudit/]
DEBUG: Detected Java 9 or later with module system.
ERROR: Forbidden class/interface use: java.io.File [non-public internal runtime class]
ERROR:   in org.acme.TestingIO (method declaration of 'getFile()')
ERROR: Scanned 1 class file(s) for forbidden API invocations (in 0.00s), 1 error(s).
ERROR: Check for forbidden API calls failed, see log.
==end of forbidden APIs==
Classes with violations:
  * org.acme.TestingIO
 
0 problems were found storing the configuration cache.
 
See the complete report at file:///./build/reports/configuration-cache/cddqacafjoi648vpdvuchz930/1d8zxjua6a25p7moresmixwz2/configuration-cache-report.html
 
FAILURE: Build failed with an exception.
 
* What went wrong:
Execution failed for task ':thirdPartyAudit'.
> Audit of third party dependencies failed
 
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
 
* Get more help at https://help.gradle.org
 
BUILD FAILED in 5s
2 actionable tasks: 2 executed
Configuration cache entry stored.

  at org.elasticsearch.gradle.fixtures.AbstractGradleFuncTest.assertOutputContains(AbstractGradleFuncTest.groovy:96)
  at org.elasticsearch.gradle.internal.precommit.ThirdPartyAuditTaskFuncTest.reports violations and ignores compile only(ThirdPartyAuditTaskFuncTest.groovy:109)

```

**Comment by fcofdez** [comment] 2023-05-12 15:29
`reports missing classes for analysis` is failing too

**Comment by valeriy42** [comment] 2023-05-15 12:47
Closing this issue because it's the duplicate of #96079

**Closed by valeriy42** 2023-05-15 12:47 UTC
Labels: :Delivery/Build, >test-failure, Team:Delivery

**Comment by valeriy42** [comment] 2023-05-15 12:49
Other instances of this failure today
- https://gradle-enterprise.elastic.co/s/5fujhpxuty3my
- https://gradle-enterprise.elastic.co/s/ybnrltoa3vodq

Only windows nodes are affected.
