### ISSUE TITLE
Java heap space Error on document indexing with spatial field

### ISSUE THREAD

**Issue by matthesrieke** [elastic/elasticsearch#16444] opened 2016-02-04 09:25 UTC
Hi Elasticsearch team,

I have recently migrated from ES 1.7.x to ES 2.x. I came across a bug that seem to be related to the storage of spatial mappings. I have seen this behaviour on  ES 2.0.x and the latest 2.2.0. In 1.7.x this worked without any issues. I am running Ubuntu 15.10 64bit with ES 2.2.0 installed from the elastic PPA. This also occured on a Ubuntu 14.04 64bit installation.

I have attached the json files to recreate the issue. Here are the curl requests using the json files as the payload content.

`curl -XDELETE localhost:9200/test`

`curl -vX PUT localhost:9200/test -d @create-index_broken.json --header "Content-Type: application/json"`

`curl -vX PUT localhost:9200/test/entry/124 -d @put-record_working.json --header "Content-Type: application/json"`
(this takes about 6 seconds on my machine)

`curl -vX PUT localhost:9200/test/entry/123 -d @put-record_broken.json --header "Content-Type: application/json"`

The spatial extent is bigger than in the previous request. This takes some time, and eventually I get the following error:

``` json
{
    "error": {
        "root_cause": [
            {
                "type": "index_failed_engine_exception",
                "reason": "Index failed for [entry#123]",
                "shard": "0",
                "index": "test"
            }
        ],
        "type": "index_failed_engine_exception",
        "reason": "Index failed for [entry#123]",
        "shard": "0",
        "index": "test",
        "caused_by": {
            "type": "out_of_memory_error",
            "reason": "Java heap space"
        }
    },
    "status": 500
}
```

When I create the index with a larger precision (1000m), both records are inserted in acceptable time:

`curl -vX PUT localhost:9200/test -d @create-index_working.json --header "Content-Type: application/json"`

The json files are attached as a zip:
[spatial-index-bug.zip](https://github.com/elastic/elasticsearch/files/117142/spatial-index-bug.zip)

**Comment by matthesrieke** [comment] 2016-02-04 09:29
`/var/log/elasticsearch/elasticsearch.log` does not provide too much information, still here are the entries starting with index creation:

[spatial-index-bug_log.txt](https://github.com/elastic/elasticsearch/files/117148/spatial-index-bug_log.txt)

**Comment by dakrone** [comment] 2016-02-04 22:41
@nknize maybe you could take a look at this?

**Comment by nknize** [comment] 2016-02-05 18:03
Hi @matthesrieke 

I'll try to reproduce the issue myself in a bit. In the meantime, if you have a chance try explicitly setting ```distance_error_pct : 0.025```.

**Comment by matthesrieke** [comment] 2016-02-09 08:19
hi @nknize 
thanks for investigating. indeed, setting `distance_error_pct` (even to a very small double, e.g. 0.0001) seems to resolve the memory error and improve performance!

**Comment by polyfractal** [comment] 2018-12-10 17:34
Confirming this is still an issue in 6.x and master.

I understand the rationale that by setting a `precision`, the user is signaling to us that they expect a certain level of accuracy, which is why we set `distance_error_pct` to zero internally.  But it feels trappy that a user can OOM their node on accident by ignoring that warning in the docs.  Worse, their system may work fine for a long time until a sufficiently antagonistic doc shows up and OOMs the node.

Is there a way we can add a circuit-breaker style runtime check to abort indexing a doc if it starts to use too much memory while indexing?  

Alternatively, perhaps we need to change the default so that it doesn't default to `distance_error_pct: 0`?  Or some heuristic that scales the `distance_error_pct` based on `precision`?


/cc @elastic/es-analytics-geo


Updated settings/docs for replicating on newer versions of ES:

```
DELETE test
PUT test
{"mappings":{"entry":{"dynamic":"false","properties":{"abstract":{"type":"text","boost":4},"access_constraint":{"type":"keyword"},"alternateTitle":{"type":"text","boost":5},"availability":{"type":"text"},"availableFormats":{"type":"keyword"},"availableFormatsVersion":{"type":"keyword"},"average_file_size":{"type":"keyword"},"conditions":{"type":"keyword"},"coverage":{"type":"keyword"},"creation_date":{"type":"date","ignore_malformed":true,"format":"strict_date_optional_time||epoch_millis"},"datasetCharacterSet":{"type":"keyword"},"datasetLanguage":{"type":"keyword"},"datasetTitle":{"type":"text","boost":5},"dateStamp":{"type":"date","ignore_malformed":true,"format":"strict_date_optional_time||epoch_millis"},"fulltext":{"type":"text"},"ident_identifier":{"type":"text","boost":10},"location":{"type":"geo_shape","precision":"52.0m"},"xmldoc":{"type":"text"}}}}}

PUT /test/entry/123
{"abstract":"test","access_constraint":"copyright","alternateTitle":["test1","test2"],"availability":"on demand","availableFormats":"tst","availableFormatsVersion":"-","average_file_size":"5.23 MB","conditions":["fee"],"coverage":"world","creation_date":"2016-01-23","datasetCharacterSet":"utf8","datasetLanguage":"eng","datasetTitle":"Test Dataset","dateStamp":"2015-10-25","frequency":"24 (per day)","fulltext":"test fulltext content","ident_identifier":"test:id:123451","location":{"type":"envelope","coordinates":[[-65,65],[65,-65]]},"xmldoc":"<?xml version=\"1.0\" encoding=\"UTF-8\"?><gmi:MI_Metadata xmlns:gmi=\"http://www.isotc211.org/2005/gmi\"></gmi:MI_Metadata>"}
```

And the OOM:

```
[elasticsearch] [2018-12-10T12:12:50,700][ERROR][o.e.i.e.Engine           ] [node-0] [test][0] already closed by tragic event on the index writer
[elasticsearch] java.lang.OutOfMemoryError: Java heap space
[elasticsearch]         at org.apache.lucene.index.FreqProxTermsWriterPerField$FreqProxPostingsArray.<init>(FreqProxTermsWriterPerField.java:224) ~[lucene-core-8.0.0-snapshot-c78429a554.jar:8.0.0-snapshot-c78429a554 c78429a554d28611dacd90c388e6c34039b228d1 - romseygeek - 2018-12-04 10:17:44]
[elasticsearch]         at org.apache.lucene.index.FreqProxTermsWriterPerField$FreqProxPostingsArray.newInstance(FreqProxTermsWriterPerField.java:245) ~[lucene-core-8.0.0-snapshot-c78429a554.jar:8.0.0-snapshot-c78429a554 c78429a554d28611dacd90c388e6c34039b228d1 - romseygeek - 2018-12-04 10:17:44]
[elasticsearch]         at org.apache.lucene.index.ParallelPostingsArray.grow(ParallelPostingsArray.java:46) ~[lucene-core-8.0.0-snapshot-c78429a554.jar:8.0.0-snapshot-c78429a554 c78429a554d28611dacd90c388e6c34039b228d1 - romseygeek - 2018-12-04 10:17:44]
[elasticsearch]         at org.apache.lucene.index.TermsHashPerField$PostingsBytesStartArray.grow(TermsHashPerField.java:252) ~[lucene-core-8.0.0-snapshot-c78429a554.jar:8.0.0-snapshot-c78429a554 c78429a554d28611dacd90c388e6c34039b228d1 - romseygeek - 2018-12-04 10:17:44]
[elasticsearch]         at org.apache.lucene.util.BytesRefHash.add(BytesRefHash.java:273) ~[lucene-core-8.0.0-snapshot-c78429a554.jar:8.0.0-snapshot-c78429a554 c78429a554d28611dacd90c388e6c34039b228d1 - romseygeek - 2018-12-04 10:17:44]
[elasticsearch]         at org.apache.lucene.index.TermsHashPerField.add(TermsHashPerField.java:151) ~[lucene-core-8.0.0-snapshot-c78429a554.jar:8.0.0-snapshot-c78429a554 c78429a554d28611dacd90c388e6c34039b228d1 - romseygeek - 2018-12-04 10:17:44]
[elasticsearch]         at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:856) ~[lucene-core-8.0.0-snapshot-c78429a554.jar:8.0.0-snapshot-c78429a554 c78429a554d28611dacd90c388e6c34039b228d1 - romseygeek - 2018-12-04 10:17:44]
[elasticsearch]         at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:441) ~[lucene-core-8.0.0-snapshot-c78429a554.jar:8.0.0-snapshot-c78429a554 c78429a554d28611dacd90c388e6c34039b228d1 - romseygeek - 2018-12-04 10:17:44]
[elasticsearch]         at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:405) ~[lucene-core-8.0.0-snapshot-c78429a554.jar:8.0.0-snapshot-c78429a554 c78429a554d28611dacd90c388e6c34039b228d1 - romseygeek - 2018-12-04 10:17:44]
[elasticsearch]         at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:251) ~[lucene-core-8.0.0-snapshot-c78429a554.jar:8.0.0-snapshot-c78429a554 c78429a554d28611dacd90c388e6c34039b228d1 - romseygeek - 2018-12-04 10:17:44]
[elasticsearch]         at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:494) ~[lucene-core-8.0.0-snapshot-c78429a554.jar:8.0.0-snapshot-c78429a554 c78429a554d28611dacd90c388e6c34039b228d1 - romseygeek - 2018-12-04 10:17:44]
[elasticsearch]         at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1618) ~[lucene-core-8.0.0-snapshot-c78429a554.jar:8.0.0-snapshot-c78429a554 c78429a554d28611dacd90c388e6c34039b228d1 - romseygeek - 2018-12-04 10:17:44]
[elasticsearch]         at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1237) ~[lucene-core-8.0.0-snapshot-c78429a554.jar:8.0.0-snapshot-c78429a554 c78429a554d28611dacd90c388e6c34039b228d1 - romseygeek - 2018-12-04 10:17:44]
[elasticsearch]         at org.elasticsearch.index.engine.InternalEngine.addDocs(InternalEngine.java:1067) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.index.engine.InternalEngine.indexIntoLucene(InternalEngine.java:1012) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:851) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:748) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.index.shard.IndexShard.applyIndexOperation(IndexShard.java:724) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.index.shard.IndexShard.applyIndexOperationOnPrimary(IndexShard.java:689) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.action.bulk.TransportShardBulkAction.lambda$executeIndexRequestOnPrimary$3(TransportShardBulkAction.java:462) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.action.bulk.TransportShardBulkAction$$Lambda$3478/0x0000000100c6b040.get(Unknown Source) ~[?:?]
[elasticsearch]         at org.elasticsearch.action.bulk.TransportShardBulkAction.executeOnPrimaryWhileHandlingMappingUpdates(TransportShardBulkAction.java:484) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequestOnPrimary(TransportShardBulkAction.java:460) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:218) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:161) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:153) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:141) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:79) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:1032) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:1010) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:102) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.runWithPrimaryShardReference(TransportReplicationAction.java:412) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
```

**Comment by imotov** [comment] 2018-12-10 20:05
> Is there a way we can add a circuit-breaker style runtime check to abort indexing a doc if it starts to use too much memory while indexing?

That sounds very reasonable to me.

**Comment by iverase** [comment] 2019-02-04 16:22
We discuss in the team and we agreed it would be nice to (roughly) estimate before hand the number of cells a polygon might create and abort the indexing of that shape if it is above a threshold.

The estimate can be done by using the length of the diagonal of the bounding box of the polygon.

**Comment by djptek** [comment] 2019-02-22 17:31
working on this

**Comment by djptek** [comment] 2019-04-30 17:26
Hi @iverase I am looking at suitable test cases for limiting using an estimate based on the diagonal as suggested.

As a limiting case, I am using `precision` of 100m

`curl -X PUT -H "Content-Type: application/json" server1:9200/test_16444 -d '{"mappings":{"dynamic":"false","properties":{"location":{"type":"geo_shape","precision":"100.0m"}}}}'`

and a BB which can contain the approximate borders of the country with the largest extension 

`curl -X PUT -H "Content-Type: application/json" server1:9200/test_16444/_doc/123 -d '{"location":{"type":"envelope","coordinates":[[-169.0,68.5],[80.5,41.2]]}}'`

Note: I chose that precision simply because those borders provoke the `out_of_memory_error` running Elasticsearch with default configuration at the `52.0m` precision. From a limited test they appear to work at `100.0m`

Does this scenario seem reasonable?

**Comment by polyfractal** [comment] 2020-06-18 14:32
I think we can probably close this now, since prefix trees are deprecated and we plan to remove them relatively shortly?

**Closed** 2020-08-11 14:03 UTC
Labels: :Analytics/Geo, >enhancement, Team:Analytics, feedback_needed, good first issue
