### ISSUE TITLE
DerivativeIT sometimes fails

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#21064] opened 2016-10-21 13:34 UTC
The following tests failed on 5.0 because the number of documents in a bucket is wrong:
- org.elasticsearch.search.aggregations.pipeline.DerivativeIT.testDocCountDerivative
- org.elasticsearch.search.aggregations.pipeline.DerivativeIT.testPartiallyUnmapped

Sadly it does not reproduce easily:
`gradle :core:integTest -Dtests.seed=22BBF080683DC006 -Dtests.class=org.elasticsearch.search.aggregations.pipeline.DerivativeIT -Dtests.method="testDocCountDerivative" -Dtests.security.manager=true -Dtests.locale=nl-BE -Dtests.timezone=Antarctica/McMurdo`

See     https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.0+dockeralpine-periodic/241/console
<details>

> Suite: org.elasticsearch.search.aggregations.pipeline.DerivativeIT
>   1> [2016-10-21T22:23:38,477][INFO ][o.e.s.a.p.DerivativeIT   ] [DerivativeIT]: setup suite
>   1> [2016-10-21T22:23:38,489][INFO ][o.e.t.InternalTestCluster] Setup InternalTestCluster [SUITE-CHILD_VM=[0]-CLUSTER_SEED=[-7378481417702118889]-HASH=[173C01400D2C67]-cluster] with seed [999A5E3E540B6A17] using [0] dedicated masters, [3](data) nodes and [0] coord only nodes
>   1> [2016-10-21T22:23:38,491][INFO ][o.e.n.Node               ] [node_s0] initializing ...
>   1> [2016-10-21T22:23:38,494][INFO ][o.e.e.NodeEnvironment    ] [node_s0] using [1] data paths, mounts [[/usr/share/elasticsearch/escheckout (/dev/xvda1)]], net usable_space [136.7gb], net total_space [196.7gb], spins? [unknown], types [ext4]
>   1> [2016-10-21T22:23:38,494][INFO ][o.e.e.NodeEnvironment    ] [node_s0] heap size [491mb], compressed ordinary object pointers [true]
>   1> [2016-10-21T22:23:38,498][INFO ][o.e.n.Node               ] [node_s0] version[5.0.0-SNAPSHOT], pid[11559], build[Unknown/Unknown], OS[Linux/4.4.0-31-generic/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_92-internal/25.92-b14]
>   1> [2016-10-21T22:23:38,498][WARN ][o.e.n.Node               ] [node_s0] version [5.0.0-SNAPSHOT] is a pre-release version of Elasticsearch and is not suitable for production
>   1> [2016-10-21T22:23:38,499][INFO ][o.e.p.PluginsService     ] [node_s0] no modules loaded
>   1> [2016-10-21T22:23:38,499][INFO ][o.e.p.PluginsService     ] [node_s0] loaded plugin [org.elasticsearch.test.ESIntegTestCase$TestSeedPlugin]
>   1> [2016-10-21T22:23:38,499][INFO ][o.e.p.PluginsService     ] [node_s0] loaded plugin [org.elasticsearch.test.transport.AssertingLocalTransport$TestPlugin]
>   1> [2016-10-21T22:23:38,499][INFO ][o.e.p.PluginsService     ] [node_s0] loaded plugin [org.elasticsearch.transport.MockTcpTransportPlugin]
>   1> [2016-10-21T22:23:38,662][INFO ][o.e.n.Node               ] [node_s0] initialized
>   1> [2016-10-21T22:23:38,663][INFO ][o.e.n.Node               ] [node_s0] starting ...
>   1> [2016-10-21T22:23:38,663][INFO ][o.e.t.TransportService   ] [node_s0] publish_address {local[80]}, bound_addresses {local[80]}
>   1> [2016-10-21T22:23:38,664][INFO ][o.e.c.s.ClusterService   ] [node_s0] new_master {node_s0}{VsbVBGb-SHOW7dcGqaGusw}{NR1bK2OGQqGrbBBAAX48EA}{local}{local[80]}, reason: local-disco-initial_connect(master)
>   1> [2016-10-21T22:23:38,664][INFO ][o.e.n.Node               ] [node_s0] started
>   1> [2016-10-21T22:23:38,666][INFO ][o.e.n.Node               ] [node_s1] initializing ...
>   1> [2016-10-21T22:23:38,669][INFO ][o.e.e.NodeEnvironment    ] [node_s1] using [1] data paths, mounts [[/usr/share/elasticsearch/escheckout (/dev/xvda1)]], net usable_space [136.7gb], net total_space [196.7gb], spins? [unknown], types [ext4]
>   1> [2016-10-21T22:23:38,669][INFO ][o.e.e.NodeEnvironment    ] [node_s1] heap size [491mb], compressed ordinary object pointers [true]
>   1> [2016-10-21T22:23:38,669][INFO ][o.e.n.Node               ] [node_s1] version[5.0.0-SNAPSHOT], pid[11559], build[Unknown/Unknown], OS[Linux/4.4.0-31-generic/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_92-internal/25.92-b14]
>   1> [2016-10-21T22:23:38,669][WARN ][o.e.n.Node               ] [node_s1] version [5.0.0-SNAPSHOT] is a pre-release version of Elasticsearch and is not suitable for production
>   1> [2016-10-21T22:23:38,670][INFO ][o.e.p.PluginsService     ] [node_s1] no modules loaded
>   1> [2016-10-21T22:23:38,670][INFO ][o.e.p.PluginsService     ] [node_s1] loaded plugin [org.elasticsearch.test.ESIntegTestCase$TestSeedPlugin]
>   1> [2016-10-21T22:23:38,670][INFO ][o.e.p.PluginsService     ] [node_s1] loaded plugin [org.elasticsearch.test.transport.AssertingLocalTransport$TestPlugin]
>   1> [2016-10-21T22:23:38,670][INFO ][o.e.p.PluginsService     ] [node_s1] loaded plugin [org.elasticsearch.transport.MockTcpTransportPlugin]
>   1> [2016-10-21T22:23:38,741][INFO ][o.e.g.GatewayService     ] [node_s0] recovered [0] indices into cluster_state
>   1> [2016-10-21T22:23:38,863][INFO ][o.e.n.Node               ] [node_s1] initialized
>   1> [2016-10-21T22:23:38,863][INFO ][o.e.n.Node               ] [node_s1] starting ...
>   1> [2016-10-21T22:23:38,865][INFO ][o.e.t.TransportService   ] [node_s1] publish_address {local[81]}, bound_addresses {local[81]}
>   1> [2016-10-21T22:23:38,869][INFO ][o.e.c.s.ClusterService   ] [node_s0] added {{node_s1}{OUnnW8dGTXmDkd1TLYKG_w}{SUFlVgSnRraZEoxLXPmgLg}{local}{local[81]},}, reason: local-disco-receive(from node[{node_s1}{OUnnW8dGTXmDkd1TLYKG_w}{SUFlVgSnRraZEoxLXPmgLg}{local}{local[81]}])
>   1> [2016-10-21T22:23:38,877][INFO ][o.e.c.s.ClusterService   ] [node_s1] detected_master {node_s0}{VsbVBGb-SHOW7dcGqaGusw}{NR1bK2OGQqGrbBBAAX48EA}{local}{local[80]}, added {{node_s0}{VsbVBGb-SHOW7dcGqaGusw}{NR1bK2OGQqGrbBBAAX48EA}{local}{local[80]},}, reason: local-disco-receive(from master)
>   1> [2016-10-21T22:23:38,880][INFO ][o.e.n.Node               ] [node_s1] started
>   1> [2016-10-21T22:23:38,881][INFO ][o.e.n.Node               ] [node_s2] initializing ...
>   1> [2016-10-21T22:23:38,884][INFO ][o.e.e.NodeEnvironment    ] [node_s2] using [1] data paths, mounts [[/usr/share/elasticsearch/escheckout (/dev/xvda1)]], net usable_space [136.7gb], net total_space [196.7gb], spins? [unknown], types [ext4]
>   1> [2016-10-21T22:23:38,884][INFO ][o.e.e.NodeEnvironment    ] [node_s2] heap size [491mb], compressed ordinary object pointers [true]
>   1> [2016-10-21T22:23:38,885][INFO ][o.e.n.Node               ] [node_s2] version[5.0.0-SNAPSHOT], pid[11559], build[Unknown/Unknown], OS[Linux/4.4.0-31-generic/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_92-internal/25.92-b14]
>   1> [2016-10-21T22:23:38,885][WARN ][o.e.n.Node               ] [node_s2] version [5.0.0-SNAPSHOT] is a pre-release version of Elasticsearch and is not suitable for production
>   1> [2016-10-21T22:23:38,886][INFO ][o.e.p.PluginsService     ] [node_s2] no modules loaded
>   1> [2016-10-21T22:23:38,886][INFO ][o.e.p.PluginsService     ] [node_s2] loaded plugin [org.elasticsearch.test.ESIntegTestCase$TestSeedPlugin]
>   1> [2016-10-21T22:23:38,886][INFO ][o.e.p.PluginsService     ] [node_s2] loaded plugin [org.elasticsearch.test.transport.AssertingLocalTransport$TestPlugin]
>   1> [2016-10-21T22:23:38,886][INFO ][o.e.p.PluginsService     ] [node_s2] loaded plugin [org.elasticsearch.transport.MockTcpTransportPlugin]
>   1> [2016-10-21T22:23:39,011][INFO ][o.e.n.Node               ] [node_s2] initialized
>   1> [2016-10-21T22:23:39,011][INFO ][o.e.n.Node               ] [node_s2] starting ...
>   1> [2016-10-21T22:23:39,011][INFO ][o.e.t.TransportService   ] [node_s2] publish_address {local[82]}, bound_addresses {local[82]}
>   1> [2016-10-21T22:23:39,012][INFO ][o.e.c.s.ClusterService   ] [node_s0] added {{node_s2}{AsePBHmiQROSvsP3EL8msw}{XUmUMt0jTLKW6lQEgHmvWg}{local}{local[82]},}, reason: local-disco-receive(from node[{node_s2}{AsePBHmiQROSvsP3EL8msw}{XUmUMt0jTLKW6lQEgHmvWg}{local}{local[82]}])
>   1> [2016-10-21T22:23:39,014][INFO ][o.e.c.s.ClusterService   ] [node_s1] added {{node_s2}{AsePBHmiQROSvsP3EL8msw}{XUmUMt0jTLKW6lQEgHmvWg}{local}{local[82]},}, reason: local-disco-receive(from master)
>   1> [2016-10-21T22:23:39,014][INFO ][o.e.c.s.ClusterService   ] [node_s2] detected_master {node_s0}{VsbVBGb-SHOW7dcGqaGusw}{NR1bK2OGQqGrbBBAAX48EA}{local}{local[80]}, added {{node_s0}{VsbVBGb-SHOW7dcGqaGusw}{NR1bK2OGQqGrbBBAAX48EA}{local}{local[80]},{node_s1}{OUnnW8dGTXmDkd1TLYKG_w}{SUFlVgSnRraZEoxLXPmgLg}{local}{local[81]},}, reason: local-disco-receive(from master)
>   1> [2016-10-21T22:23:39,034][INFO ][o.e.n.Node               ] [node_s2] started
>   1> [2016-10-21T22:23:39,035][INFO ][o.e.p.PluginsService     ] [transport_client_node_s0] no modules loaded
>   1> [2016-10-21T22:23:39,035][INFO ][o.e.p.PluginsService     ] [transport_client_node_s0] loaded plugin [org.elasticsearch.test.transport.AssertingLocalTransport$TestPlugin]
>   1> [2016-10-21T22:23:39,104][INFO ][o.e.t.TransportService   ] [transport_client_node_s0] publish_address {local[83]}, bound_addresses {local[83]}
>   1> [2016-10-21T22:23:39,126][INFO ][o.e.p.PluginsService     ] [transport_client_node_s2] no modules loaded
>   1> [2016-10-21T22:23:39,126][INFO ][o.e.p.PluginsService     ] [transport_client_node_s2] loaded plugin [org.elasticsearch.test.transport.AssertingLocalTransport$TestPlugin]
>   1> [2016-10-21T22:23:39,177][INFO ][o.e.t.TransportService   ] [transport_client_node_s2] publish_address {local[84]}, bound_addresses {local[84]}
>   1> [2016-10-21T22:23:39,180][INFO ][o.e.p.PluginsService     ] [transport_client_node_s1] no modules loaded
>   1> [2016-10-21T22:23:39,180][INFO ][o.e.p.PluginsService     ] [transport_client_node_s1] loaded plugin [org.elasticsearch.test.transport.AssertingLocalTransport$TestPlugin]
>   1> [2016-10-21T22:23:39,217][INFO ][o.e.t.TransportService   ] [transport_client_node_s1] publish_address {local[85]}, bound_addresses {local[85]}
>   1> [2016-10-21T22:23:39,234][INFO ][o.e.s.a.p.DerivativeIT   ] test using _default_ mappings: [{"_default_":{}}]
>   1> [2016-10-21T22:23:39,266][INFO ][o.e.s.a.p.DerivativeIT   ] using custom data_path for index: [ResDjeDWNT]
>   1> [2016-10-21T22:23:39,281][INFO ][o.e.c.m.MetaDataCreateIndexService] [node_s0] [idx] creating index, cause [api], templates [random_index_template], shards [9]/[1], mappings [_default_]
>   1> [2016-10-21T22:23:39,788][INFO ][o.e.c.r.a.AllocationService] [node_s0] Cluster health status changed from [YELLOW] to [GREEN](reason: [shards started [[idx][6]] ...]).
>   1> [2016-10-21T22:23:39,815][INFO ][o.e.s.a.p.DerivativeIT   ] using custom data_path for index: [zqFCVVIcvG]
>   1> [2016-10-21T22:23:39,822][INFO ][o.e.c.m.MetaDataCreateIndexService] [node_s0] [idx_unmapped] creating index, cause [api], templates [random_index_template], shards [4]/[1], mappings [_default_]
>   1> [2016-10-21T22:23:40,051][INFO ][o.e.c.r.a.AllocationService] [node_s0] Cluster health status changed from [YELLOW] to [GREEN](reason: [shards started [[idx_unmapped][0], [idx_unmapped][2]] ...]).
>   1> [2016-10-21T22:23:40,565][INFO ][o.e.s.a.p.DerivativeIT   ] using custom data_path for index: [WSUGbGXsOr]
>   1> [2016-10-21T22:23:40,582][INFO ][o.e.c.m.MetaDataCreateIndexService] [node_s0] [empty_bucket_idx] creating index, cause [api], templates [random_index_template], shards [7]/[0], mappings [_default_, type]
>   1> [2016-10-21T22:23:40,734][INFO ][o.e.c.r.a.AllocationService] [node_s0] Cluster health status changed from [YELLOW] to [GREEN](reason: [shards started [[empty_bucket_idx][2], [empty_bucket_idx][3], [empty_bucket_idx][5], [empty_bucket_idx][6], [empty_bucket_idx][0], [empty_bucket_idx][4], [empty_bucket_idx][1]] ...]).
>   1> [2016-10-21T22:23:40,771][INFO ][o.e.c.m.MetaDataCreateIndexService] [node_s0] [empty_bucket_idx_rnd] creating index, cause [api], templates [random_index_template], shards [3]/[1], mappings [_default_, type]
>   1> [2016-10-21T22:23:40,962][INFO ][o.e.c.r.a.AllocationService] [node_s0] Cluster health status changed from [YELLOW] to [GREEN](reason: [shards started [[empty_bucket_idx_rnd][0]] ...]).
>   1> [2016-10-21T22:23:41,212][INFO ][o.e.s.a.p.DerivativeIT   ] Index [992] docs async: [false] bulk: [true] partitions [44]
>   1> [2016-10-21T22:23:41,271][INFO ][o.e.c.m.MetaDataMappingService] [node_s0] [idx/1clk3G0bTQW9DfWEeEYhmw] create_mapping [type]
>   1> [2016-10-21T22:23:41,297][INFO ][o.e.c.m.MetaDataMappingService] [node_s0] [empty_bucket_idx/h2st7K81TTS9mjp1j_U8iQ] create_mapping [RANDOM_BOGUS_TYPE______]
>   1> [2016-10-21T22:23:41,317][INFO ][o.e.c.m.MetaDataMappingService] [node_s0] [empty_bucket_idx_rnd/moxZtb2gQry14AWJq8PuaA] create_mapping [RANDOM_BOGUS_TYPE______]
>   1> [2016-10-21T22:23:41,375][INFO ][o.e.c.m.MetaDataMappingService] [node_s0] [idx/1clk3G0bTQW9DfWEeEYhmw] create_mapping [RANDOM_BOGUS_TYPE______]
>   1> [2016-10-21T22:23:43,279][INFO ][o.e.s.a.p.DerivativeIT   ] [DerivativeIT#testSingleValuedField_normalised]: starting test
>   1> [2016-10-21T22:23:43,391][INFO ][o.e.s.a.p.DerivativeIT   ] [DerivativeIT#testSingleValuedField_normalised]: finished test
>   1> [2016-10-21T22:23:43,499][INFO ][o.e.s.a.p.DerivativeIT   ] [DerivativeIT#testSingleValueAggDerivativeWithGaps]: starting test
>   1> [2016-10-21T22:23:43,550][INFO ][o.e.s.a.p.DerivativeIT   ] [DerivativeIT#testSingleValueAggDerivativeWithGaps]: finished test
>   1> [2016-10-21T22:23:43,675][INFO ][o.e.s.a.p.DerivativeIT   ] [DerivativeIT#testDocCountDerivative]: starting test
>   1> [2016-10-21T22:23:43,698][INFO ][o.e.s.a.p.DerivativeIT   ] [DerivativeIT#testDocCountDerivative]: finished test
>   2> REPRODUCE WITH: gradle :core:integTest -Dtests.seed=22BBF080683DC006 -Dtests.class=org.elasticsearch.search.aggregations.pipeline.DerivativeIT -Dtests.method="testDocCountDerivative" -Dtests.security.manager=true -Dtests.locale=nl-BE -Dtests.timezone=Antarctica/McMurdo
>   1> [2016-10-21T22:23:44,248][INFO ][o.e.m.j.JvmGcMonitorService] [node_s2] [gc][5] overhead, spent [528ms] collecting in the last [1.2s]
>   1> [2016-10-21T22:23:44,249][INFO ][o.e.m.j.JvmGcMonitorService] [node_s1] [gc][5] overhead, spent [528ms] collecting in the last [1.3s]
> FAILURE 0.71s J0 | DerivativeIT.testDocCountDerivative <<< FAILURES!
> Throwable #1: java.lang.AssertionError: InternalBucket 34 docCount
> Expected: <19L>
>      but: was <20L>
>    at __randomizedtesting.SeedInfo.seed([22BBF080683DC006:27754CEEC71E28C9]:0)
>    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
>    at org.elasticsearch.search.aggregations.pipeline.DerivativeIT.checkBucketKeyAndDocCount(DerivativeIT.java:652)
>    at org.elasticsearch.search.aggregations.pipeline.DerivativeIT.testDocCountDerivative(DerivativeIT.java:189)
>    at java.lang.Thread.run(Thread.java:745)
>   1> [2016-10-21T22:23:44,340][INFO ][o.e.s.a.p.DerivativeIT   ] [DerivativeIT#testSingleValueAggDerivative_invalidPath]: starting test
>   1> [2016-10-21T22:23:44,375][INFO ][o.e.s.a.p.DerivativeIT   ] [DerivativeIT#testSingleValueAggDerivative_invalidPath]: finished test
>   1> [2016-10-21T22:23:44,465][INFO ][o.e.s.a.p.DerivativeIT   ] [DerivativeIT#testDocCountDerivativeWithGaps_random]: starting test
>   2> REPRODUCE WITH: gradle :core:integTest -Dtests.seed=22BBF080683DC006 -Dtests.class=org.elasticsearch.search.aggregations.pipeline.DerivativeIT -Dtests.method="testPartiallyUnmapped" -Dtests.security.manager=true -Dtests.locale=nl-BE -Dtests.timezone=Antarctica/McMurdo
>   1> [2016-10-21T22:23:44,486][INFO ][o.e.s.a.p.DerivativeIT   ] [DerivativeIT#testDocCountDerivativeWithGaps_random]: finished test
>   1> [2016-10-21T22:23:44,561][INFO ][o.e.s.a.p.DerivativeIT   ] [DerivativeIT#testPartiallyUnmapped]: starting test
>   1> [2016-10-21T22:23:44,576][INFO ][o.e.s.a.p.DerivativeIT   ] [DerivativeIT#testPartiallyUnmapped]: finished test
> FAILURE 0.09s J0 | DerivativeIT.testPartiallyUnmapped <<< FAILURES!
> Throwable #1: java.lang.AssertionError: InternalBucket 34 docCount
> Expected: <19L>
>      but: was <20L>
>    at __randomizedtesting.SeedInfo.seed([22BBF080683DC006:8BF9408B9C98B80C]:0)
>    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
>    at org.elasticsearch.search.aggregations.pipeline.DerivativeIT.checkBucketKeyAndDocCount(DerivativeIT.java:652)
>    at org.elasticsearch.search.aggregations.pipeline.DerivativeIT.testPartiallyUnmapped(DerivativeIT.java:370)
>    at java.lang.Thread.run(Thread.java:745)
>   1> [2016-10-21T22:23:44,679][WARN ][o.e.m.j.JvmGcMonitorService] [node_s0] [gc][6] overhead, spent [528ms] collecting in the last [1s]
>   1> [2016-10-21T22:23:44,690][INFO ][o.e.s.a.p.DerivativeIT   ] [DerivativeIT#testDocCountDerivativeWithGaps]: starting test
>   1> [2016-10-21T22:23:44,698][INFO ][o.e.s.a.p.DerivativeIT   ] [DerivativeIT#testDocCountDerivativeWithGaps]: finished test
>   1> [2016-10-21T22:23:44,805][INFO ][o.e.s.a.p.DerivativeIT   ] [DerivativeIT#testSingleValueAggDerivativeWithGaps_insertZeros]: starting test
>   1> [2016-10-21T22:23:44,817][INFO ][o.e.s.a.p.DerivativeIT   ] [DerivativeIT#testSingleValueAggDerivativeWithGaps_insertZeros]: finished test
>   1> [2016-10-21T22:23:44,900][INFO ][o.e.s.a.p.DerivativeIT   ] [DerivativeIT#testSingleValueAggDerivativeWithGaps_random]: starting test
>   2> NOTE: leaving temporary files on disk at: /usr/share/elasticsearch/escheckout/core/build/testrun/integTest/J0/temp/org.elasticsearch.search.aggregations.pipeline.DerivativeIT_22BBF080683DC006-001
>   1> [2016-10-21T22:23:44,911][INFO ][o.e.s.a.p.DerivativeIT   ] [DerivativeIT#testSingleValueAggDerivativeWithGaps_random]: finished test
>   1> [2016-10-21T22:23:45,041][INFO ][o.e.s.a.p.DerivativeIT   ] [DerivativeIT#testMultiValueAggDerivative]: starting test
>   1> [2016-10-21T22:23:45,070][INFO ][o.e.s.a.p.DerivativeIT   ] [DerivativeIT#testMultiValueAggDerivative]: finished test
>   1> [2016-10-21T22:23:45,206][INFO ][o.e.s.a.p.DerivativeIT   ] [DerivativeIT#testUnmapped]: starting test
>   1> [2016-10-21T22:23:45,213][INFO ][o.e.s.a.p.DerivativeIT   ] [DerivativeIT#testUnmapped]: finished test
>   1> [2016-10-21T22:23:45,290][INFO ][o.e.s.a.p.DerivativeIT   ] [DerivativeIT#testSingleValueAggDerivative]: starting test
>   1> [2016-10-21T22:23:45,318][INFO ][o.e.s.a.p.DerivativeIT   ] [DerivativeIT#testSingleValueAggDerivative]: finished test
>   1> [2016-10-21T22:23:45,440][INFO ][o.e.s.a.p.DerivativeIT   ] [DerivativeIT#testDocCountDerivativeWithGaps_insertZeros]: starting test
>   1> [2016-10-21T22:23:45,445][INFO ][o.e.s.a.p.DerivativeIT   ] [DerivativeIT#testDocCountDerivativeWithGaps_insertZeros]: finished test
>   1> [2016-10-21T22:23:45,615][INFO ][o.e.s.a.p.DerivativeIT   ] [DerivativeIT#testAvgMovavgDerivNPE]: starting test
>   1> [2016-10-21T22:23:45,642][INFO ][o.e.c.m.MetaDataCreateIndexService] [node_s0] [movavg_npe] creating index, cause [api], templates [random_index_template], shards [6]/[0], mappings [_default_]
>   1> [2016-10-21T22:23:45,745][INFO ][o.e.c.r.a.AllocationService] [node_s0] Cluster health status changed from [YELLOW] to [GREEN](reason: [shards started [[movavg_npe][1], [movavg_npe][2], [movavg_npe][4], [movavg_npe][5], [movavg_npe][3], [movavg_npe][0]] ...]).
>   1> [2016-10-21T22:23:45,791][INFO ][o.e.c.m.MetaDataMappingService] [node_s0] [movavg_npe/DWkJndHlTdK3zMTuLJUoew] create_mapping [type]
>   1> [2016-10-21T22:23:45,919][INFO ][o.e.s.a.p.DerivativeIT   ] [DerivativeIT#testAvgMovavgDerivNPE]: finished test
>   1> [2016-10-21T22:23:45,919][INFO ][o.e.s.a.p.DerivativeIT   ] [DerivativeIT]: cleaning up after suite
>   2> NOTE: test params are: codec=Lucene62, sim=ClassicSimilarity, locale=nl-BE, timezone=Antarctica/McMurdo
>   2> NOTE: Linux 4.4.0-31-generic amd64/Oracle Corporation 1.8.0_92-internal (64-bit)/cpus=4,threads=1,free=416386560,total=514326528
>   2> NOTE: All tests run in this JVM: [IpFieldBwCompatIT, FieldDataLoadingIT, EnableAllocationDeciderIT, CombiIT, AvgIT, StringTermsIT, IndexLifecycleActionIT, WaitActiveShardCountIT, MinBucketIT, CorruptedFileIT, DerivativeIT]
>   1> [2016-10-21T22:23:46,392][INFO ][o.e.n.Node               ] [node_s0] stopping ...
>   1> [2016-10-21T22:23:46,392][INFO ][o.e.c.s.ClusterService   ] [node_s1] master {new {node_s1}{OUnnW8dGTXmDkd1TLYKG_w}{SUFlVgSnRraZEoxLXPmgLg}{local}{local[81]}, previous {node_s0}{VsbVBGb-SHOW7dcGqaGusw}{NR1bK2OGQqGrbBBAAX48EA}{local}{local[80]}}, removed {{node_s0}{VsbVBGb-SHOW7dcGqaGusw}{NR1bK2OGQqGrbBBAAX48EA}{local}{local[80]},}, reason: local-disco-update
>   1> [2016-10-21T22:23:46,393][INFO ][o.e.c.s.ClusterService   ] [node_s2] master {new {node_s1}{OUnnW8dGTXmDkd1TLYKG_w}{SUFlVgSnRraZEoxLXPmgLg}{local}{local[81]}, previous {node_s0}{VsbVBGb-SHOW7dcGqaGusw}{NR1bK2OGQqGrbBBAAX48EA}{local}{local[80]}}, removed {{node_s0}{VsbVBGb-SHOW7dcGqaGusw}{NR1bK2OGQqGrbBBAAX48EA}{local}{local[80]},}, reason: local-disco-receive(from master)
>   1> [2016-10-21T22:23:46,394][INFO ][o.e.n.Node               ] [node_s0] stopped
>   1> [2016-10-21T22:23:46,394][INFO ][o.e.n.Node               ] [node_s0] closing ...
>   1> [2016-10-21T22:23:46,410][INFO ][o.e.n.Node               ] [node_s0] closed
>   1> [2016-10-21T22:23:46,412][INFO ][o.e.n.Node               ] [node_s1] stopping ...
>   1> [2016-10-21T22:23:46,413][INFO ][o.e.c.s.ClusterService   ] [node_s2] master {new {node_s2}{AsePBHmiQROSvsP3EL8msw}{XUmUMt0jTLKW6lQEgHmvWg}{local}{local[82]}, previous {node_s1}{OUnnW8dGTXmDkd1TLYKG_w}{SUFlVgSnRraZEoxLXPmgLg}{local}{local[81]}}, removed {{node_s1}{OUnnW8dGTXmDkd1TLYKG_w}{SUFlVgSnRraZEoxLXPmgLg}{local}{local[81]},}, reason: local-disco-update
>   1> [2016-10-21T22:23:46,418][INFO ][o.e.n.Node               ] [node_s1] stopped
>   1> [2016-10-21T22:23:46,418][INFO ][o.e.n.Node               ] [node_s1] closing ...
>   1> [2016-10-21T22:23:56,424][INFO ][o.e.n.Node               ] [node_s1] closed
>   1> [2016-10-21T22:23:56,424][WARN ][o.e.c.InternalClusterInfoService] [node_s1] Failed to update node information for ClusterInfoUpdateJob within 15s timeout
>   1> [2016-10-21T22:23:56,424][WARN ][o.e.c.InternalClusterInfoService] [node_s1] Failed to update shard information for ClusterInfoUpdateJob within 15s timeout
>   1> [2016-10-21T22:23:56,428][INFO ][o.e.n.Node               ] [node_s2] stopping ...
>   1> [2016-10-21T22:23:56,429][INFO ][o.e.n.Node               ] [node_s2] stopped
>   1> [2016-10-21T22:23:56,429][INFO ][o.e.n.Node               ] [node_s2] closing ...
>   1> [2016-10-21T22:23:56,432][INFO ][o.e.n.Node               ] [node_s2] closed
> Completed [38/308] on J0 in 18.04s, 14 tests, 2 failures <<< FAILURES!
> </details>

**Comment by tlrx** [comment] 2016-10-21 14:09
@cbuescher I'm assigning this issue to you since you worked on its randomization. Please feel free to reassign if needed.

**Comment by cbuescher** [comment] 2016-10-25 16:02
My attempts to reproduce this also failed so far. I will dig a bit more and see if adding logging somewhere might help.

**Comment by cbuescher** [comment] 2017-03-01 21:25
Closing this since we haven't seen any similar failure since 21/10/2016

**Closed by cbuescher** 2017-03-01 21:25 UTC
Labels: :Aggregations, jenkins, test, v5.0.0
