### ISSUE TITLE
Race conditions in Index Deletion

### ISSUE THREAD

**Issue by abeyad** [elastic/elasticsearch#17767] opened 2016-04-14 21:34 UTC
Some race conditions were found in shadow replica deletion, see #17695.  However, the following tests produce sporadic failures that indicate there are other race conditions when trying to delete the index contents of a deleted index (regular indices and shadow replicas).  

1. `IndexServiceTests#testBaseAsyncTask` (http://build-us-00.elastic.co/job/es_g1gc_master_metal/35910/testReport/junit/org.elasticsearch.index/IndexServiceTests/testBaseAsyncTask/)
2. `IndexShardTests#testSearcherWrapperWorksWithGlobaOrdinals` (https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-os-compatibility/os=ubuntu/239/console)
3. `IndexServiceTests#testRefreshTaskIsUpdated` (https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/20/console)

The stack traces look like:
```
java.io.IOException: Could not remove the following files (in the order of attempts):
   /home/jenkins/workspace/es_g1gc_master_metal/core/build/testrun/test/J1/temp/org.elasticsearch.index.IndexServiceTests_56B8EE9D1A7C1203-001/tempDir-001/data/single-node-cluster-CHILD_VM=[1]-CLUSTER_SEED=[6042546882828568297]-HASH=[15836EE647DB17]/nodes/0/indices/FRdrjAUiSb29Q33U4vlkXA/_state/state-1.st: java.io.IOException: access denied: /home/jenkins/workspace/es_g1gc_master_metal/core/build/testrun/test/J1/temp/org.elasticsearch.index.IndexServiceTests_56B8EE9D1A7C1203-001/tempDir-001/data/single-node-cluster-CHILD_VM=[1]-CLUSTER_SEED=[6042546882828568297]-HASH=[15836EE647DB17]/nodes/0/indices/FRdrjAUiSb29Q33U4vlkXA/_state/state-1.st
   /home/jenkins/workspace/es_g1gc_master_metal/core/build/testrun/test/J1/temp/org.elasticsearch.index.IndexServiceTests_56B8EE9D1A7C1203-001/tempDir-001/data/single-node-cluster-CHILD_VM=[1]-CLUSTER_SEED=[6042546882828568297]-HASH=[15836EE647DB17]/nodes/0/indices/FRdrjAUiSb29Q33U4vlkXA/_state: java.nio.file.DirectoryNotEmptyException: /home/jenkins/workspace/es_g1gc_master_metal/core/build/testrun/test/J1/temp/org.elasticsearch.index.IndexServiceTests_56B8EE9D1A7C1203-001/tempDir-001/data/single-node-cluster-CHILD_VM=[1]-CLUSTER_SEED=[6042546882828568297]-HASH=[15836EE647DB17]/nodes/0/indices/FRdrjAUiSb29Q33U4vlkXA/_state

	at org.apache.lucene.util.IOUtils.rm(IOUtils.java:323)
	at org.elasticsearch.gateway.MetaDataStateFormat.deleteMetaState(MetaDataStateFormat.java:378)
	at org.elasticsearch.indices.IndicesService.deleteIndexStore(IndicesService.java:579)
	at org.elasticsearch.indices.IndicesService.deleteIndexStore(IndicesService.java:554)
	at org.elasticsearch.indices.IndicesService.deleteClosedIndex(IndicesService.java:526)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyDeletedIndices(IndicesClusterStateService.java:239)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:182)
	at org.elasticsearch.cluster.service.ClusterService.runTasksForExecutor(ClusterService.java:652)
	at org.elasticsearch.cluster.service.ClusterService$UpdateTask.run(ClusterService.java:814)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:408)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:237)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:200)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

It is critical that the `_state` directory in the index dir gets deleted, so the index does not get re-imported as a dangling index.  

It is worth also keeping an eye out for these tests and seeing if #17265 solves the problem.  If the problem persists even after index tombstones are in, then an AwaitsFix should be added to the tests until the problem is resolved.

**Comment by bleskes** [comment] 2016-05-12 10:02
@abeyad was there any discussion on this? re reading the ticket I'm not 100% clear on what the issue is.

**Comment by abeyad** [comment] 2016-05-12 13:18
@bleskes During test triage, I found that some of the tests sporadically failed throwing exceptions like the one shown above, indicating a delete was not completely successful in that files remained on the file system after the delete operation.  This was more to keep track of this issue and see if it continues to come up.  It may not be race conditions that are the problem, though that was my initial guess.  It would also be interesting to see if tombstones fixes this problem.  None of these tests have failed since I first opened this issue nearly a month ago.

**Comment by abeyad** [comment] 2016-05-16 13:23
Just to update the ticket, @bleskes and I had a discussion about this.  These are very sporadic failures occurring on the test infrastructure and haven't occurred since the issue was reported.  They seem to do with file system permissions, but because its difficult to reproduce, haven't gotten to the bottom of it yet.  Will continue to keep an eye on it and try to reproduce it with extra logging.

**Comment by clintongormley** [comment] 2016-09-09 09:12
@abeyad any further news on this?

**Comment by abeyad** [comment] 2016-09-09 20:01
@clintongormley None of these tests have failed since this issue was reported on April 14.  I propose we close this unless something else manifests.

**Comment by clintongormley** [comment] 2016-09-13 11:12
sounds good, closing

**Closed by clintongormley** 2016-09-13 11:12 UTC
Labels: :Cluster, blocker, bug
