### ISSUE TITLE
5.x indexing document with version 0 or 1 (internal versioning) causes failure.

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch#20702] opened 2016-09-29 20:06 UTC
We are in the process of upgrading from 1.x to 5.x and have hundreds of tests verifying the behavior of 1.x. One thing that instantly failed was versioning on 5.0.0-beta1.

We were inserting a document with version 0 (the model default), which previously worked.
`Validation Failed: 1: illegal version value [0] for version type [INTERNAL];`

I was talking with @gmarz and he said the default had to be 1. So I updated my code to insert a new document into a new index with the version: 1.

`(409) Type: version_conflict_engine_exception Reason: "[employee][57ed6ffcf8a1032a485c05e6]: version conflict, current version [-1] is different than the one provided [1]`

According to the docs (https://www.elastic.co/guide/en/elasticsearch/reference/master/docs-index_.html) 1 should work... What's going on here?

**Comment by niemyjski** [comment] 2016-09-29 20:08
I guess the docs should be updated to say don't specify version in insert, and is there a breaking change noted someplace about this as this is working on 1.7.5

**Comment by niemyjski** [comment] 2016-09-29 20:09
I think it could be a bug, that if I specify a version of 1 on insert and it matches the internal implementation it shouldn't throw an error.

**Comment by bleskes** [comment] 2016-09-30 15:44
@niemyjski can you give an example of the concrete indexing requests you use? NEST , Sense or just curl style are all fine.

**Comment by niemyjski** [comment] 2016-09-30 17:59
```
PUT http://127.0.0.1:9200/employees 
{"mappings":{"employee":{"dynamic":false,"properties":{"id":{"type":"keyword"},"isDeleted":{"type":"boolean"},"createdUtc":{"type":"date"},"updatedUtc":{"type":"date"},"companyId":{"type":"keyword"},"companyName":{"type":"keyword"},"name":{"type":"text"},"age":{"type":"float"}}}}}
```

Version 0 previously worked in 1.x
```
PUT http://127.0.0.1:9200/employees/employee/57eea70cf8a1031bb0f54895?version=0 
{"createdUtc":"2016-09-30T17:55:24.2736658Z","id":"57eea70cf8a1031bb0f54895","companyId":"57eea70cf8a1031bb0f54894","age":20,"yearsEmployed":0,"updatedUtc":"2016-09-30T17:55:24.2736658Z","isDeleted":false}
```

this returns

```
HTTP/1.1 400 Bad Request

{"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: illegal version value [0] for version type [INTERNAL];"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: illegal version value [0] for version type [INTERNAL];"},"status":400}
```

Version 1 (same as the default for internal versioning):
```
PUT http://127.0.0.1:9200/employees/employee/57eea70cf8a1031bb0f54895?version=1 
{"createdUtc":"2016-09-30T17:55:24.2736658Z","id":"57eea70cf8a1031bb0f54895","companyId":"57eea70cf8a1031bb0f54894","age":20,"yearsEmployed":0,"updatedUtc":"2016-09-30T17:55:24.2736658Z","isDeleted":false}
```

returns 

```
HTTP/1.1 409 Conflict
{"error":{"root_cause":[{"type":"version_conflict_engine_exception","reason":"[employee][57eea70cf8a1031bb0f54895]: version conflict, current version [-1] is different than the one provided [1]","index_uuid":"sjlQ4NwrT1-sBrc0_sIkGA","shard":"0","index":"employees"}],"type":"version_conflict_engine_exception","reason":"[employee][57eea70cf8a1031bb0f54895]: version conflict, current version [-1] is different than the one provided [1]","index_uuid":"sjlQ4NwrT1-sBrc0_sIkGA","shard":"0","index":"employees"},"status":409}
```

**Comment by bleskes** [comment] 2016-10-03 09:39
@niemyjski thx.  Somewhat in reverse order:

> Version 1 (same as the default for internal versioning):

The use of default here is not really right. Adding a version to the index API means - "only index it if the documents *current* version is set to this". In your call it means it has been indexed before and never changed. If the document doesn't exist, the version checks throw a conflict, which is good.

> Version 0 previously worked in 1.x

A version value of 0 is invalid indeed. I think it's good we signal that now?

Going back to the original comment:

> We were inserting a document with version 0 (the model default),

It seems like you are trying to model a document and you want it have the 0 version when first created. Instead of using the index API in the case, you should use the `_create` one. This will give you the guarantees you are looking for. I'm going to close this now as it seems like everything works as intended.

**Closed by bleskes** 2016-10-03 09:39 UTC

**Comment by niemyjski** [comment] 2016-10-03 14:19
Can you link me to the docs for `_create`. I still think this is a bug. I have a generic library for indexing elasticsearch and I don't know if it was called from Add or Save method. I just pass along the index version on the document which worked before. If the default value after add is 1 and I pass in 1, that shouldn't throw an error (as it didn't previously). I do see why you made the change, but when it comes to concurrency, any update will change the version, so specifying the initial default value can only happen once...

**Comment by bleskes** [comment] 2016-10-03 14:36
@niemyjski I suggest you read up on the versioning scheme - it's not specified the version of the written doc but rather that on the previous one. Also, here are the _create docs, straight out of google - https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#operation-type

**Comment by niemyjski** [comment] 2016-10-03 14:44
Yes, I get that 100% but there isn't a previous version when the doc is first written! My unit test wipes out the cluster and creates the mappings and writes a single doc with a version and it fails... The version I'm specifying is the same version that elasticsearch returns after the doc is created (without specifying the version). I logged this as it was working before and I don't think indexing should fail if the internal version number will be the EXACT same as the version specified for creation.

**Comment by niemyjski** [comment] 2016-10-03 14:44
That link sends me to a 404

**Comment by bleskes** [comment] 2016-10-03 14:53
> That link sends me to a 404

Github mangles it up - here is a workable version [https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#operation-type](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#operation-type)

> it was working before

That doesn't mean it should keep working. I tried to explain, but I think something is still not clear - as I said before - I strongly suggest you read up on versioning. Docs are [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#index-versioning) and a blog post is [here](https://www.elastic.co/blog/elasticsearch-versioning-support). I also request you try out my suggestion before further discussing.

**Comment by niemyjski** [comment] 2016-10-03 17:33
I reread all the documents to ensure I wasn't missing anything... I'm not saying that something should never change due to backwards compatibility. I just think the docs here and announcements don't correlate to the actual behavior that occurs now nor the fact it was a breaking change (which is okay as long as it's stated someplace).

> By default, internal versioning is used that starts at 1 and increments with each update, deletes included. Optionally, the version number can be supplemented with an external value (for example, if maintained in a database). To enable this functionality, version_type should be set to external. The value provided must be a numeric, long value greater or equal to 0, and less than around 9.2e+18. 

> When you index a document for the very first time, it gets the version 1 and you can see that in the response Elasticsearch returns. 

> Consider the indexing command above. With internal versioning, it means "only index this document update if its current version is equal to 526". If the version matches, Elasticsearch will increase it by one and store the document. However, with an external versioning system this will be a requirement we can't enforce. Maybe that versioning system doesn't increment by one every time.

No where does it say you shouldn't specify a version on create. It also doesn't make sense that I can't specify `1` the default value of a newly inserted doc, this simplifies the index statement on the client without having extra rules (generic code).

**Comment by russcam** [comment] 2016-10-04 12:46
@niemyjski, specifying a version on a create call makes no sense though; because there is no current  version of the document when performing a create, there is no version that can be specified on the create call. To allow optimistic concurrency control when creating a document, you can use `.OpType(OpType.Create)` on an index call in NEST.

[I wrote a blog post about using Optimistic Concurrency Control with NEST and Elasticsearch](http://forloop.co.uk/blog/optimistic-concurrency-with-elasticsearch-and-nest); hope it helps.

**Comment by niemyjski** [comment] 2016-10-04 13:37
I'm not calling the create api, just bulk index generically for both create and save.

**Comment by garakelian** [comment] 2017-01-07 18:37
@russcam Following up @niemyjski comment.  Either there is a bug, or the document is wrong.

Using a new index, I make the following bulk API request (using curl):
```
{"index":{"_index":"test","_type":"default","_id":"100","_version":1483813028207}}
{"id":"100","firstName":"John","lastName":"Doe"}
```

Note that I'm using the "index" operation, NOT "create".  Per the docs [Bulk API docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html) "index and create expect a source on the next line, and have the same semantics as the op_type parameter to the standard index API (i.e. create will fail if a document with the same index and type exists already, **whereas index will add or replace a document as necessary**).

Yet, I get back an error like this:
```
      "index" : {
        "_index" : "test",
        "_type" : "default",
        "_id" : "100",
        "status" : 409,
        "error" : {
          "type" : "version_conflict_engine_exception",
          "reason" : "[default][100]: version conflict, current version [-1] is different than the one provided [1483813028207]",
  ....
        }
      }
```

**Comment by garakelian** [comment] 2017-01-07 22:22
@russcam Disregard my last message. Realized that I needed to pass "version_type":"external". Everything worked fine then.

**Comment by erdalceylan** [comment] 2018-05-03 12:47
https://www.elastic.co/blog/elasticsearch-versioning-support

['retry_on_conflict'] = (number) Specify how many times should the operation be retried when a conflict

works for me

**Comment by ywelsch** [comment] 2018-10-08 08:45
@Ad4mJ this seems unrelated to the discussion above (which was about internal versioning). Can you open a topic on `discuss.elastic.co` so that we can better understand your case before we escalate this to a Github issue? Thank you.
