### ISSUE TITLE
[CI] UpgradeClusterClientYamlTestSuiteIT test {p0=mixed_cluster/10_basic/Start scroll in mixed cluster on upgraded node that we will continue after upgrade} failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#100379] opened 2023-10-06 01:40 UTC
This test seems to be hanging often and causing this suite to time out.

**Build scan:**
https://gradle-enterprise.elastic.co/s/mchebbxsxkz7c/tests/:x-pack:qa:rolling-upgrade:v8.0.0%23twoThirdsUpgradedTest/org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT/test%20%7Bp0=mixed_cluster%2F10_basic%2FStart%20scroll%20in%20mixed%20cluster%20on%20upgraded%20node%20that%20we%20will%20continue%20after%20upgrade%7D
**Reproduction line:**
```
./gradlew ':x-pack:qa:rolling-upgrade:v8.0.0#twoThirdsUpgradedTest' -Dtests.class="org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=mixed_cluster/10_basic/Start scroll in mixed cluster on upgraded node that we will continue after upgrade}" -Dtests.seed=171E8571CDFE5A17 -Dtests.bwc=true -Dtests.locale=ar-AE -Dtests.timezone=America/Blanc-Sablon -Druntime.java=21
```

**Applicable branches:**
main, 8.11

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT&tests.test=test%20%7Bp0%3Dmixed_cluster/10_basic/Start%20scroll%20in%20mixed%20cluster%20on%20upgraded%20node%20that%20we%20will%20continue%20after%20upgrade%7D
**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([171E8571CDFE5A17]:0)

```

**Comment by mark-vieira** [comment] 2023-10-06 01:45
A related test has been muted for quite some time as well: https://github.com/elastic/elasticsearch/issues/100379

**Comment by masseyke** [comment] 2023-10-11 17:33
@mark-vieira you don't happen to remember which test you were referencing in the comment right before this one do you? The link points back to this ticket. I notice that this is in the first failure in the log (before this test runs), and everything seems to fail after that because the cluster isn't green, including #100371. I'm not sure exactly why that would be. But I wonder if fixing the `trained_model_assignment` serialization bug would fix all of these.
```
    {"error":{"root_cause":[{"type":"transport_serialization_exception","reason":"Failed to deserialize response from handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.transport.TransportService$4/[cluster:monitor/state]:org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$1@436988b7/org.elasticsearch.action.ActionListener$DelegatingFailureActionListener/org.elasticsearch.action.support.ContextPreservingActionListener/org.elasticsearch.tasks.TaskManager$1@27dd8740/org.elasticsearch.xpack.security.action.filter.SecurityActionFilter$$Lambda$5939/0x0000000801acfbe0@532957ea]"}],"type":"transport_serialization_exception","reason":"Failed to deserialize response from handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.transport.TransportService$4/[cluster:monitor/state]:org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$1@436988b7/org.elasticsearch.action.ActionListener$DelegatingFailureActionListener/org.elasticsearch.action.support.ContextPreservingActionListener/org.elasticsearch.tasks.TaskManager$1@27dd8740/org.elasticsearch.xpack.security.action.filter.SecurityActionFilter$$Lambda$5939/0x0000000801acfbe0@532957ea]","caused_by":{"type":"illegal_argument_exception","reason":"Unknown NamedWriteable [org.elasticsearch.cluster.metadata.Metadata$Custom][trained_model_assignment]"}},"status":500}
```
Since that doesn't format well, the important part is:
```
{"type":"illegal_argument_exception","reason":"Unknown NamedWriteable [org.elasticsearch.cluster.metadata.Metadata$Custom][trained_model_assignment]"}},"status":500}
```

**Comment by mark-vieira** [comment] 2023-10-11 17:44
Found it: https://github.com/elastic/elasticsearch/issues/91637

And funny enough it was just reenabled.

**Comment by droberts195** [comment] 2023-10-11 18:01
> But I wonder if fixing the `trained_model_assignment` serialization bug would fix all of these.

It should do. If this hasn't failed since #100388 was merged then it can be closed.

**Comment by mark-vieira** [comment] 2023-10-11 18:34
Interestingly I can consistently get this to fail in my branch where I've refactored this test to us the new test clusters framework. The main difference here is that we're running these YAML tests in isolation so perhaps there's some kind of race condition where some post-upgrade async task is not completing. I've also verified that it is getting hung on the `indicies.create` step here: https://github.com/elastic/elasticsearch/blob/5689455b129ce15c6206cf25b048e0c21b2949a1/x-pack/qa/rolling-upgrade/src/yamlRestTest/resources/rest-api-spec/test/mixed_cluster/10_basic.yml#L4

https://gradle-enterprise.elastic.co/s/aaubsywpkjnbw/tests/task/:x-pack:qa:rolling-upgrade:v8.10.0%23yamlRestTest/details/org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT/test%20%7BupgradedNodes=2%20test=mixed_cluster%2F10_basic%2FStart%20scroll%20in%20mixed%20cluster%20on%20upgraded%20node%20that%20we%20will%20continue%20after%20upgrade%7D?top-execution=1

**Comment by mark-vieira** [comment] 2023-10-11 18:40
In the logs you can see that the cluster goes RED immediately after we create the index. I have no idea what "reconcile-desired-balance" means though:

```[2023-10-12T00:38:57,925][INFO ][o.e.c.m.MetadataCreateIndexService] [test-cluster-2] [upgraded_scroll] creating index, cause [api], templates [], shards [1]/[0]
[2023-10-12T00:38:58,067][INFO ][o.e.c.r.a.AllocationService] [test-cluster-2] current.health="RED" message="Cluster health status changed from [YELLOW] to [RED] (reason: [reconcile-desired-balance])." previous.health="YELLOW" reason="reconcile-desired-balance"
```

**Comment by masseyke** [comment] 2023-10-11 19:08
Oh interesting -- are the index settings in that test incompatible with the new desired balance allocator (@DaveCTurner maybe)?
```
  - do:
      indices.create:
        index: upgraded_scroll
        wait_for_active_shards: all
        body:
          settings:
# we make sure we don't have shards relocating. Relocating a shard with a scroll on it prevents shards from moving back into a where
# a scroll is running (it holds the shard lock), see https://github.com/elastic/elasticsearch/issues/31827
            index.routing.rebalance.enable: none
            index.number_of_replicas: 0
            index.routing.allocation.include.upgraded: true
```

**Comment by droberts195** [comment] 2023-10-11 19:20
When this issue was first opened I think the `trained_model_assignment` bug was the cause of the first failure. This is visible in the server-side logs from the original issue description. Looking in the most recent Gradle scan there's no mention of `trained_model_assignment` in the server-side node logs. So I think there must have been **two** causes of this test failing originally, with the ML one masking the other one. I'm pretty certain the ML one was fixed by #100388, leaving the other problem as the visible cause of failure now.

**Comment by mark-vieira** [comment] 2023-10-11 19:21
> So I think there must have been **two** causes of this test failing originally, with the ML one masking the other one. I'm pretty certain the ML one was fixed by #100388, leaving the other problem as the visible cause of failure now.

That's quite possible. And I'm not sure what it is about this new setup that triggering this error so consistently. For reference, here is the PR if anyone wants to check it out and repro locally: https://github.com/elastic/elasticsearch/pull/100380

**Comment by masseyke** [comment] 2023-10-11 20:18
> For reference, here is the PR if anyone wants to check it out and repro locally: https://github.com/elastic/elasticsearch/pull/100380

How are you running this in that branch? The task seems to be gone:
```
* What went wrong:
Cannot locate tasks that match ':x-pack:qa:rolling-upgrade:v8.0.0#twoThirdsUpgradedTest' as task 'v8.0.0#twoThirdsUpgradedTest' not found in project ':x-pack:qa:rolling-upgrade'.
```

**Comment by mark-vieira** [comment] 2023-10-11 20:43
Just run `./gradlew :x-pack:qa:rolling-upgrade:v8.0.0#yamlRestTest`.

**Comment by cbuescher** [comment] 2023-10-12 13:51
Since I was the one unmuting #91637 to do the risk-assessment for our test failures I'm wondering if I should mute it again or not. Speed-reading the conversation here it seems to me that the problem isn't really search-related and the investigation here is more up-to date than on that ticket.
Should I close the older issue and the mute the test again? Or close but not mute? I would currently put this as a medium-risk since its unclear to me if this is a test framework problem or one that could also happen in production.

**Comment by masseyke** [comment] 2023-10-12 18:15
I can reproduce a failure on Mark's PR branch, but it's slightly different. I get
```
[2023-10-12T18:30:53,249][INFO ][o.e.c.r.a.AllocationService] [test-cluster-2] current.health="RED" message="Cluster health status changed from [YELLOW] to [RED] (reason: [index [upgraded_scroll] created])." previous.health="YELLOW" reason="index [upgraded_scroll] created"
```
And the stack trace is:
```
[2023-10-12T18:32:23,749][INFO ][o.e.a.b.TransportShardBulkAction] [test-cluster-1] operation failed. action [indices:data/write/bulk[s]], request [BulkShardRequest [[upgraded_scroll][0]] containing [index {[upgraded_scroll][42], source[{"foo":1}]}]] org.elasticsearch.action.UnavailableShardsException: [upgraded_scroll][0] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[upgraded_scroll][0]] containing [index {[upgraded_scroll][42], source[{"foo":1}]}]]
	at org.elasticsearch.server@8.12.0-SNAPSHOT/org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.retryBecauseUnavailable(TransportReplicationAction.java:1066)
	at org.elasticsearch.server@8.12.0-SNAPSHOT/org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.doRun(TransportReplicationAction.java:861)
	at org.elasticsearch.server@8.12.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at org.elasticsearch.server@8.12.0-SNAPSHOT/org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase$2.onTimeout(TransportReplicationAction.java:1025)
	at org.elasticsearch.server@8.12.0-SNAPSHOT/org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:355)
	at org.elasticsearch.server@8.12.0-SNAPSHOT/org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:293)
	at org.elasticsearch.server@8.12.0-SNAPSHOT/org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:645)
	at org.elasticsearch.server@8.12.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:916)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```
So oddly, it's creating the index and returning even though we have `wait_for_active_shards: all`. But then failing to do the bulk load because the shard isn't active. I experimented with changing the settings on that index, and it fails in this way if either `index.routing.rebalance.enable: none` or `index.number_of_replicas: 0` are set. I think we'll probably have to turn this over to @elastic/es-distributed.
With all that said, I'm still wondering if the failure reported here is due to something else (like the ML serialization thing that has been fixed), since the logs don't show anything like what Mark or I are seeing. @cbuescher for that reason I'd kind of like to leave this unmuted to see if it comes back again before Mark's PR goes in.

**Closed** 2024-11-05 21:54 UTC
Labels: >test-failure, :Data Management/Indices APIs, Team:Data Management, medium-risk
