### ISSUE TITLE
Add field validation for range aggregation field option

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#20773] opened 2016-10-06 05:09 UTC
**Elasticsearch version**: 1.7, 2.3

Consider the following example, if field is set to a field that does not exist, no errors are thrown and instead only the range aggregation is returned and the max value is not returned.

```
PUT rangeagg
{
  "mappings": {
    "type":{
      "properties": {
        "intField1":{
          "type": "integer"
        },
        "intField2":{
          "type": "integer"
        }
      }
    }
  }
}

POST rangeagg/type/1
{
  "intField1": 4,
  "intField2": 3
}

GET /rangeagg/_search
{
  "aggs": {
    "test": {
      "range": {
        "field": "whatever", 
        "script" : "doc['intField1'].value - doc['intField2'].value",
        "ranges": [
          {
            "from": 0,
            "to": 2
          }
        ]
      },
      "aggs": {
        "max": {
          "max": {
            "field": "intField1"
          }
        }
      }
    }
  }
} 

Returns:

"aggregations": {
      "test": {
         "buckets": [
            {
               "key": "0.0-2.0",
               "from": 0,
               "from_as_string": "0.0",
               "to": 2,
               "to_as_string": "2.0",
               "doc_count": 0
            }
         ]
      }
   }
```

**Comment by jpountz** [comment] 2016-10-10 17:23
The problem is that if we fail search requests on missing fields, then cross-index search requests will report failed shards as soon as any of the indices does not contain all fields that are used in aggregations. I am pretty sure many users rely on this behaviour.

And I'd like to avoid adding a setting.

**Comment by colings86** [comment] 2016-10-14 10:00
Discussed in FixItFriday. We agreed with @jpountz that we don't want to fail on missing fields because of the cross-index search request use case which is heavily used. Adding a specific setting for this is also not desirable but we thought in the case where you are wanting to specify a script to work on each value of a field rathe ran once on each document we should specify the script using `value_script` instead of `script`. 

This would allow us to add validation to error if you specify `script` and `field` since this would then be invalid.

To give an upgrade path for this change we should do the following:

In 5.x: 
* Add the `value_script` parameter to specify a script to execute on each value
* Specifying `script` and `field` will still work for BWC but will log to the deprecation logger
* Deprecate the use of `script` and `field` together in the documentation in favour of using `value_script` and `field`

In 6.0:
* Throw a error during parsing if `script` is used with `value_script`

/cc @clintongormley

**Comment by markharwood** [comment] 2018-03-16 17:10
cc @elastic/es-search-aggs

**Comment by wchaparro** [comment] 2023-04-19 14:21
Closing as not planned

**Closed by wchaparro** 2023-04-19 14:21 UTC
Labels: >enhancement, help wanted, :Analytics/Aggregations, Team:Analytics
