### ISSUE TITLE
manage_pipeline is not granular enough

### ISSUE THREAD

**Issue by tdmalone** [elastic/elasticsearch#57328] opened 2020-05-29 03:30 UTC
We'd like to have a user with access to read pipelines, but not necessarily to be able to write them.

Like #53110, but for pipelines. Also similar to #29999.

**Comment by tvernum** [comment] 2020-05-29 03:46
Duplicate of https://github.com/elastic/elasticsearch/issues/48028

**Closed by tvernum** 2020-05-29 03:46 UTC
Labels: >enhancement, needs:triage
