### ISSUE TITLE
dynamic_templates are not always applied in order

### ISSUE THREAD

**Issue by champtar** [elastic/elasticsearch#26650] opened 2017-09-14 18:03 UTC
**Elasticsearch version** (`bin/elasticsearch --version`):
5.6.0

**Plugins installed**: []
None

**JVM version** (`java -version`):
```
openjdk version "1.8.0_144"
OpenJDK Runtime Environment (build 1.8.0_144-b01)
OpenJDK 64-Bit Server VM (build 25.144-b01, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system):
```
Centos 7.4
Linux analytics1 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Description of the problem including expected versus actual behavior**:
```dynamic_templates``` are not always applied in order contrary to what says the documentation
https://www.elastic.co/guide/en/elasticsearch/reference/5.6/dynamic-templates.html

**Steps to reproduce**:

Here my dynamic_templates
```
        "dynamic_templates": [
          {
            "long_fields": {
              "match": "*",
              "match_mapping_type": "long",
              "mapping": {
                "type": "long"
              }
            }
          },
          {
            "string_fields": {
              "match": "hll_*",
              "mapping": {
                "type": "binary"
              }
            }
          },
          {
            "string_fields": {
              "match": "*",
              "match_mapping_type": "string",
              "mapping": {
                "type": "keyword"
              }
            }
          }
        ]
```

In one of my index got this mapping
```
          "hll_assets": {
            "type": "binary"
          },
          "hll_ip": {
            "type": "binary"
          },
```
And another one got
```
          "hll_assets": {
            "type": "keyword"
          },
          "hll_ip": {
            "type": "binary"
          },
```
hll_assets is not present in all documents, so maybe there is a difference in behavior when you create the mapping from the template vs when you update the mapping?
My 2 dynamic_templates are named "string_fields", If that's the problem ES should send an error and refuse the template creation

**Provide logs (if relevant)**:

**Comment by danielmitterdorfer** [comment] 2017-09-18 07:57
I tried to reproduce the issue with the following statements:

```
DELETE /my-index-*
DELETE /_template/26650

PUT _template/26650
{
  "template": "my-index-*",
  "mappings": {
    "my_type": {
        "dynamic_templates": [
          {
            "long_fields": {
              "match": "*",
              "match_mapping_type": "long",
              "mapping": {
                "type": "long"
              }
            }
          },
          {
            "string_fields": {
              "match": "hll_*",
              "mapping": {
                "type": "binary"
              }
            }
          },
          {
            "string_fields": {
              "match": "*",
              "match_mapping_type": "string",
              "mapping": {
                "type": "keyword"
              }
            }
          }
        ]
    }
  }
}

POST /my-index-1/my_type
{
    "app_id": 3,
	"description": "some text"
}

POST /my-index-1/my_type
{
    "app_id": 4,
	"hll_assets": "an asset"
}

POST /my-index-2/my_type
{
    "app_id": 3,
	"hll_assets": "an asset"
}

POST /my-index-2/my_type
{
    "app_id": 4,
	"description": "some other text"
}

GET /my-index-*/_mapping
```

For both indices I get:

```json
"properties": {
  "app_id": {
    "type": "long"
  },
  "description": {
    "type": "keyword"
  },
  "hll_assets": {
    "type": "binary"
  }
}
```

So I think there is something missing in your original description.

What do you mean by the following question?

> maybe there is a difference in behavior when you create the mapping from the template vs when you update the mapping?

If you update the mapping of an index by e.g. adding a new field then dynamic templates will not apply to that field (because it already exists then). So there are certainly differences but I am not sure what you are after.

> My 2 dynamic_templates are named "string_fields", If that's the problem ES should send an error and refuse the template creation

This is not a problem because dynamic templates are stored in a list internally and their order is preserved. The name does not matter although I think we should really enforce unique names here to avoid confusion.

Can you please try to refine your reproduction scenario as I could not reproduce the behavior you are describing? Are there mappings or dynamic templates updated in between?

**Comment by champtar** [comment] 2017-09-18 15:51
Hi @danielmitterdorfer 

I'm not able to reproduce it, but it did happen ...

My question was maybe there is a difference if first document is
```
POST /my-index-1/my_type
{
  "k": "aaa",
  "hll_ip": "ZXMgcm9ja3M="
}
```
rather than
```
POST /my-index-1/my_type
{
  "k": "aaa",
  "hll_ip": "ZXMgcm9ja3M=",
  "hll_assets": "ZXMgcm9ja3M="
}
```
ie if we update the properties list (new field in second document) instead of having the full list at index creation (in the first document)
If this change anything, my hll_* fields are big  (~12k)

**Comment by danielmitterdorfer** [comment] 2017-09-19 07:52
> I'm not able to reproduce it, but it did happen ...

Oh, I am not questioning at all that it did happen. It's just that I could not come up with a scenario to reproduce it. I could see this happen with an explicit mapping update right after creating an index, i.e.:

1. Create an index including the dynamic template definition (as the [examples in the docs](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/dynamic-templates.html) show)
2. Index a document without a `hll_assets` field
3. Define an explicit mapping for `hll_assets` to `keyword` via the PUT mapping API
4. Index a document with `hll_assets`. As the mapping was defined explicitly already in step 3, the dynamic template does not apply (because a mapping for the field `hll_assets` already exists)

But I could not read anything like that from your description so I don't think that you are doing such things.

The scenario that you are describing in your previous comment is perfectly fine (i.e. there is no need that `hll_assets` is contained in every document). Also the length of the field contents does not play a role here.

One other possibility that I could imagine is that you first create an index, add documents and then add the dynamic templates later with the PUT mapping API. If a field is already present when you add the dynamic template is added, it's too late (similar to the scenario that I've described above).

I'd close this issue for now as we both cannot reproduce the behavior at the moment. However, please comment on this ticket again if you find a scenario that reproduces it. Thank you for your help!

**Closed by danielmitterdorfer** 2017-09-19 07:52 UTC
Labels: :Mapping, feedback_needed
