### ISSUE TITLE
[CI] WindowsServiceTests test10InstallArchive failing

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#96247] opened 2023-05-22 11:56 UTC
**Build scan:**
https://gradle-enterprise.elastic.co/s/q7rawwrku7dpi/tests/:qa:os:destructiveDistroTest.default-windows-archive/org.elasticsearch.packaging.test.WindowsServiceTests/test10InstallArchive

**Reproduction line:**
```
null
```

**Applicable branches:**
7.17

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.packaging.test.WindowsServiceTests&tests.test=test10InstallArchive

**Failure excerpt:**
```
java.lang.RuntimeException: java.nio.file.AccessDeniedException: C:\tmp\elasticsearch-7.17.11-SNAPSHOT -> C:\tmp\elasticsearch

  at __randomizedtesting.SeedInfo.seed([7CFDD97899548A5C:9ED595CF4A8D04AF]:0)
  at org.elasticsearch.packaging.util.FileUtils.mv(FileUtils.java:136)
  at org.elasticsearch.packaging.util.Archives.installArchive(Archives.java:99)
  at org.elasticsearch.packaging.util.Archives.installArchive(Archives.java:62)
  at org.elasticsearch.packaging.test.WindowsServiceTests.test10InstallArchive(WindowsServiceTests.java:105)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

  Caused by: java.nio.file.AccessDeniedException: C:\tmp\elasticsearch-7.17.11-SNAPSHOT -> C:\tmp\elasticsearch

    at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
    at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
    at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:414)
    at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:291)
    at java.nio.file.Files.move(Files.java:1429)
    at org.elasticsearch.packaging.util.FileUtils.mv(FileUtils.java:134)
    at org.elasticsearch.packaging.util.Archives.installArchive(Archives.java:99)
    at org.elasticsearch.packaging.util.Archives.installArchive(Archives.java:62)
    at org.elasticsearch.packaging.test.WindowsServiceTests.test10InstallArchive(WindowsServiceTests.java:105)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke(Method.java:578)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
    at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
    at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
    at java.lang.Thread.run(Thread.java:1623)

```

**Comment by mark-vieira** [comment] 2023-05-24 23:23
Closing this as a duplicate of https://github.com/elastic/elasticsearch/issues/96026 since we believe it's the same root issue.

**Closed by mark-vieira** 2023-05-24 23:23 UTC
Labels: :Delivery/Packaging, >test-failure, Team:Delivery
