### ISSUE TITLE
[CI] org.elasticsearch.xpack.ilm.CCRIndexLifecycleIT.testCCRUnfollowDuringSnapshot fails sporadically

### ISSUE THREAD

**Issue by dliappis** [elastic/elasticsearch#48461] opened 2019-10-24 12:28 UTC
## Example build failure

https://gradle-enterprise.elastic.co/s/s7pg5vmuahasi

## Reproduction line

Does **not** reproduce locally

```
./gradlew ':x-pack:plugin:ilm:qa:multi-cluster:follow-clusterRunner' --tests "org.elasticsearch.xpack.ilm.CCRIndexLifecycleIT.testCCRUnfollowDuringSnapshot" \
  -Dtests.seed=15F5BEF4F0C61ABF \
  -Dtests.security.manager=true \
  -Dtests.locale=de-AT \
  -Dtests.timezone=PST \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

## Example relevant log:
```
 1> [2019-10-24T03:33:26,008][INFO ][o.e.x.i.CCRIndexLifecycleIT] [testCCRUnfollowDuringSnapshot] initializing REST clients against [http://[::1]:35835, http://127.0.0.1:33321]
13:33:58   1> [2019-10-24T03:33:30,691][INFO ][o.e.x.i.CCRIndexLifecycleIT] [testCCRUnfollowDuringSnapshot] --> starting unfollow
13:33:58   1> [2019-10-24T03:33:32,465][INFO ][o.e.x.i.CCRIndexLifecycleIT] [testCCRUnfollowDuringSnapshot] after test
13:33:58   2> REPRODUCE WITH: ./gradlew ':x-pack:plugin:ilm:qa:multi-cluster:follow-clusterRunner' --tests "org.elasticsearch.xpack.ilm.CCRIndexLifecycleIT.testCCRUnfollowDuringSnapshot" -Dtests.seed=15F5BEF4F0C61ABF -Dtests.security.manager=true -Dtests.locale=de-AT -Dtests.timezone=PST -Dcompiler.java=12 -Druntime.java=8
13:33:58   2> org.elasticsearch.client.ResponseException: method [HEAD], host [http://127.0.0.1:33321], URI [/unfollow-test-index/_doc/1], status line [HTTP/1.1 503 Service Unavailable]
13:33:58         at __randomizedtesting.SeedInfo.seed([15F5BEF4F0C61ABF:DFD8AE805887E1C]:0)
13:33:58         at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:283)
13:33:58         at org.elasticsearch.client.RestClient.performRequest(RestClient.java:261)
13:33:58         at org.elasticsearch.client.RestClient.performRequest(RestClient.java:267)
13:33:58         at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235)
13:33:58         at org.elasticsearch.xpack.ilm.CCRIndexLifecycleIT.assertDocumentExists(CCRIndexLifecycleIT.java:753)
13:33:58         at org.elasticsearch.xpack.ilm.CCRIndexLifecycleIT.lambda$testCCRUnfollowDuringSnapshot$3(CCRIndexLifecycleIT.java:166)
13:33:58         at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:881)
13:33:58         at org.elasticsearch.xpack.ilm.CCRIndexLifecycleIT.testCCRUnfollowDuringSnapshot(CCRIndexLifecycleIT.java:158)
13:33:58   1> [2019-10-24T03:33:32,611][INFO ][o.e.x.i.CCRIndexLifecycleIT] [testAliasReplicatedOnShrink] before test```

## Frequency

Happened [9 times so far](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-1y,mode:quick,to:now))&_a=(columns:!(branch,message),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'class:%20%22org.elasticsearch.xpack.ilm.CCRIndexLifecycleIT%22%20AND%20test:%20%22testCCRUnfollowDuringSnapshot%22'),sort:!(time,desc))) in `master` and `7.x` since September 17th 2019

**Comment by ywelsch** [comment] 2019-10-24 15:29
I've tagged this as Core/Features/ILM+SLM as I would like that area team to have a look first (whether it has something to do with the ILM integration or whether it's a core CCR concern). Please reassign if necessary

**Comment by gwbrown** [comment] 2019-10-24 19:52
I think this is just an issue with the test not properly converting a `ResponseException` to an `assertionError` so that it can be retried by an `assertBusy`.  I've opened https://github.com/elastic/elasticsearch/pull/48489 to address. Even if that's not the root cause, that PR includes some extra logging that should make this easier to troubleshoot.

**Closed** 2019-10-26 00:08 UTC
Labels: :Core/Features/ILM+SLM, >test-failure
