### ISSUE TITLE
[2.4 code issue]org.elasticsearch.transport.netty.NettyTransport:createServerBootstrap

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#20225] opened 2016-08-30 05:49 UTC
method: createServerBootstrap
the serverBootstrap created in this method is bounded to tcp port, so actually it is a tcp server.
while use HTTP_SERVER_BOSS_THREAD_NAME_PREFIX to create bossFactory and workerFactory, which is not properly

**Comment by jasontedor** [comment] 2016-08-30 09:40
This has already been addressed in master by #20207, but will not be backported to 2.4 (it's not a bug, it's not a new feature, just an annoyance when you're looking at thread names).

**Closed by jasontedor** 2016-08-30 09:40 UTC
