### ISSUE TITLE
Missing documents when bulk indexing

### ISSUE THREAD

**Issue by marghidanu** [elastic/elasticsearch#55098] opened 2020-04-12 00:35 UTC
**Elasticsearch version**: 7.6.2

**Plugins installed**: []

**JVM version**: openjdk version "1.8.0_242"

**OS version**: Linux 4.15.0-66-generic #75-Ubuntu

**Description of the problem including expected versus actual behavior**:

I'm using Logstash to import data from Kafka into ElasticSearch. I’m currently using a data generator to provide an expected result in ElasticSearch, I should be getting a record every minute in ElasticSearch, but sometimes the documents don't get indexed at all. I've excluded the possibility that this might be caused by Logstash since I briefly replaced it with Kafka Connect and behaved the same way. Kafka is returning the event since I can consume it with a different process. Logstash has no filtering whatsoever and it should just send data to ES. 

I've increased the `thread_pool.writes.queue_size` and the behavior still persists. The logs are not showing anything.

**Comment by nik9000** [comment] 2020-04-13 17:20
My instinct is that the problem is between Logstash and Elasticsearch *somewhere*. You should be able to see what Elasticsearch is getting in [_cat/thread_pool](https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-thread-pool.html) APIs or by cranking the logs up to trace, specifically `org.elasticsearch.task`. I'm sure there are logstash resources to look at that I don't know as well.

At this point this doesn't *look* like a bug in Elasticsearch so I'm going to close this. https://discuss.elastic.co is probably the right place to get help with something like this. Likely in the logstash section.

**Closed by nik9000** 2020-04-13 17:20 UTC
