### ISSUE TITLE
[CI] SmokeTestMultiNodeClientYamlTestSuiteIT test {yaml=cat.nodeattrs/10_basic/Test cat nodes attrs output} failing

### ISSUE THREAD

**Issue by masseyke** [elastic/elasticsearch#78561] opened 2021-10-01 15:17 UTC
The test has not changed in years, and I can't reproduce this locally. But it just failed twice, which seems suspicious.

**Build scan:**
https://gradle-enterprise.elastic.co/s/mkllp7hj2slee/tests/:qa:smoke-test-multinode:integTest/org.elasticsearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT/test%20%7Byaml=cat.nodeattrs%2F10_basic%2FTest%20cat%20nodes%20attrs%20output%7D

**Reproduction line:**
`./gradlew ':qa:smoke-test-multinode:integTest' --tests "org.elasticsearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT" -Dtests.method="test {yaml=cat.nodeattrs/10_basic/Test cat nodes attrs output}" -Dtests.seed=1AE2F352D3EA9FCD -Dtests.locale=el-CY -Dtests.timezone=Europe/Kiev -Druntime.java=8`

**Applicable branches:**
7.x

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT&tests.test=test%20%7Byaml%3Dcat.nodeattrs/10_basic/Test%20cat%20nodes%20attrs%20output%7D

**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([1AE2F352D3EA9FCD]:0)

```

**Comment by mark-vieira** [comment] 2021-10-01 16:39
Closing this as a duplicate of https://github.com/elastic/elasticsearch/issues/77025.

**Closed by mark-vieira** 2021-10-01 16:39 UTC
Labels: >test-failure, :Data Management/CAT APIs, Team:Data Management
