### ISSUE TITLE
[CI] LangPainlessClientYamlTestSuiteIT misses deprecation warnings

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#28600] opened 2018-02-09 10:03 UTC
Error in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1157/console

An expected warning message failed to appear:

>did not get expected warning header [ getDate is no longer necessary on date fields as the value is now a date.

I took a look but it did not reproduce for me:

    ./gradlew :modules:lang-painless:integTestRunner -Dtests.seed=8E78B1E6509C9509 -Dtests.class=org.elasticsearch.painless.LangPainlessClientYamlTestSuiteIT -Dtests.method="test {yaml=painless/50_script_doc_values/date}"  -Dtests.security.manager=true -Dtests.locale=es-CR -Dtests.timezone=Europe/Kirov

Console output: https://gist.github.com/markharwood/40c99146e8e5ae2cf4361cdd1197c031

@nik9000 commented on the email:

>Seems related to something that I did but happens infrequently. I'll dig when I'm done with what I'm working on now.

**Comment by nik9000** [comment] 2018-02-09 17:31
It looks like this has only happened one other time:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=fedora/647/console


Hunting!

**Comment by nik9000** [comment] 2018-02-09 20:03
I can't reproduce and don't have any hints on how this happened. I'm going to set it down until it happens again.

**Comment by markharwood** [comment] 2018-02-13 15:43
I thought one explanation might be the date warning wasn't actually missing but was misinterpreted by the test framework's result-parsing logic if there happened to be an additional warning.

To test that theory I tried changing the script to produce 2 deprecation warnings, one for a date and one for an integer :

    source: "doc['date'].date +' '+ doc['integer'].date"

Sadly this didn't recreate the issue - the test reported both of the deprecation warnings as "unexpected" responses rather than reporting the date warning as "missing" as we saw in the original Jenkins failure.

**Comment by markharwood** [comment] 2018-02-14 11:40
>It looks like this has only happened one other time:

I found another from Feb 10th: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+openjdk-java9-periodic/74 but this was a missing warning for calling getDate on a long.

Did not reproduce:

    ./gradlew :modules:lang-painless:integTestRunner -Dtests.seed=370B6DEF0A627F3 -Dtests.class=org.elasticsearch.painless.LangPainlessClientYamlTestSuiteIT -Dtests.method="test {yaml=painless/50_script_doc_values/long}" -Dtests.security.manager=true -Dtests.locale=hu-HU -Dtests.timezone=Australia/LHI

**Comment by ywelsch** [comment] 2018-03-14 12:34
more failures here: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+oracle-java10-periodic/171/console

**Comment by nik9000** [comment] 2018-03-14 16:07
I shelled into the node that ran https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+oracle-java10-periodic/171/console and it *did* log the deprecation warning that the test claimed wasn't returned:

```
[2018-03-14T11:50:38,780][WARN ][o.e.d.i.f.ScriptDocValues$Dates] getDates is no longer necessary on date fields as the values are now dates.
```

So the error is somewhere between the deprecation logging and returning the deprecations. Weird!

**Comment by DaveCTurner** [comment] 2018-03-26 10:36
Looking at the build-stats database I see the following failures that look like this (but none that pre-date 2018-02-07):

```
February  7th 2018, 21:44:13.596    https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=fedora/647/
February  8th 2018, 14:54:48.391    https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1157/
February 10th 2018, 03:38:16.357    https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+openjdk-java9-periodic/74/
February 22nd 2018, 11:37:36.089    https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1252/
February 23rd 2018, 10:17:20.589    https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=debian/709/
February 28th 2018, 05:59:58.777    https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=ubuntu/728/
March    14th 2018, 06:57:01.453    https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=amazon/799/
March    14th 2018, 10:59:36.438    https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+oracle-java10-periodic/171/
March    14th 2018, 13:05:25.079    https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=fedora/800/
March    17th 2018, 15:57:33.428    https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-java-periodic/ESJAVA=java10,ESRUNTIME=java9,nodes=linux/6/
March    21st 2018, 20:12:47.330    https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+ccr-6.x+feature-branch-periodic/497/
March    21st 2018, 23:17:20.803    https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=sles/829/
March    23rd 2018, 17:47:46.224    https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1420/
March    24th 2018, 18:53:30.134    https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=oraclelinux/840/
March    26th 2018, 01:35:40.970    https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-windows-compatibility/845/
```

**Comment by davidkyle** [comment] 2018-04-05 15:42
Another occurrence: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=fedora/887/console

**Comment by nik9000** [comment] 2018-04-10 15:33
I'm really not sure what to do about this. I'll add it to my list to look at some more soon but I have no idea why this happens.

**Comment by albertzaharovits** [comment] 2018-04-11 14:56
Another data point:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+periodic/1801/console

**Comment by romseygeek** [comment] 2018-04-19 13:33
Another instance:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=fedora/962/console

**Comment by nik9000** [comment] 2018-04-19 13:51
I think I have a hint for this one and plan to fight with it soon.

**Comment by nik9000** [comment] 2018-04-20 16:53
So I've been able to reproduce this locally but not without changing the test in weird ways. It is similar enough for me to decide that the cause is something like #19222.

**Comment by nik9000** [comment] 2018-04-20 19:45
Another trick might be to set the number of shards in the test index to 1 and see if the issue goes away.

**Comment by jkakavas** [comment] 2018-04-24 14:49
Another instance in 
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+release-tests/683/console

**Comment by jdconrad** [comment] 2018-04-27 15:51
@nik9000 Seems like you have a good handle on this issue, would it be all right if I assigned it over to you?

**Comment by markharwood** [comment] 2018-04-27 16:34
Another example in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.3+intake/15/console

**Comment by nik9000** [comment] 2018-04-27 17:59
Done.

Painless is not at fault here. It is just that it is the only place where we have an integration test that logs warnings during the fan-out portions of a search.

I spent most of last Friday poking at this one and was able to reproduce a *similar* issue but not this issue. I *could* fix that issue and hope that this one vanishes but I'm worried I'd hide something.

I *can* push something that *might* silence the failures. And if it does then it'll give us more information. I'll see about doing that this afternoon.

**Comment by nik9000** [comment] 2018-04-27 20:05
I've pushed 8401eac425d0440c0e860fb14cd112be2f8c01df (and backports) and left myself a note to see if that fixes the problem. If it does we have another bug to fix, but the test won't be failing so that is a plus.

**Comment by jasontedor** [comment] 2018-05-04 12:09
> If it does we have another bug to fix, but the test won't be failing so that is a plus.

This has not failed since changing to one shard. 😐

**Comment by nik9000** [comment] 2018-05-07 20:06
> This has not failed since changing to one shard. neutral_face

I had it on my list to check that today. Do you want to close this because it is *technically* gone but we've not really figured out the mechanism of action? I'm not 100% comfortable with that but I understand that I can't figure out all the mysteries.

**Closed** 2018-08-09 19:42 UTC
Labels: :Core/Scripting, >test-failure, v6.4.0
