### ISSUE TITLE
Fields no longer searchable or aggregatable after upgrading to 5.1

### ISSUE THREAD

**Issue by tedivm** [elastic/elasticsearch#22216] opened 2016-12-16 07:46 UTC
**Elasticsearch version**: 5.1.1

**Plugins installed**: []

**JVM version**: 1.8.0_92

**OS version**: Ubuntu 16.04

**Description of the problem including expected versus actual behavior**: When upgrading to 5.1 from the latest 2.x some fields were switched to no longer being searchable or aggregatable. 

**Steps to reproduce**:
 1. Upgrade to 5.1

**Provide logs (if relevant)**:

I am not the only person this has happened to-

https://discuss.elastic.co/t/upgraded-to-elk-5-0-can-no-longer-create-visualizations-with-aggregations/64725

**Comment by s1monw** [comment] 2016-12-16 08:00
@tedivm can you provide a reproduction or an example of what doesn't work. It's nearly impossible to do anything here with a "X doesn't work anymore after upgrade" description. :(

**Comment by tedivm** [comment] 2016-12-16 08:18
What exactly do you want? I'm restoring a backup now (it's easier than reindexing) so I can pull data from both the backup and the upgraded node pretty trivially once that's done. This is also data for a video game so there's literally nothing sensitive in it.

**Comment by tedivm** [comment] 2016-12-16 08:20
Also, this is a bit more than "x doesn't work anymore". A field that was previously indexed no longer is. It used to be usable for kibana visualizations, but now it is not and causes errors for things that previously worked just fine.

**Comment by s1monw** [comment] 2016-12-16 08:24
for instance, is the index you are trying to search created with 2.x or 5.x. What is the field mapping in 2.x vs. 5.x. An example query that worked in 2.x but doesn't in 5.x, a sample of your data that you are indexing, are you using dynamic mapping or you do you predefine mappings. I am really working on my yedi skills but it seems like the force is not with me today ;)

**Comment by tedivm** [comment] 2016-12-16 08:40
Index was created with 2.x. using dynamic mapping. The field in question is the `price` field, which is no longer aggregatable. Any query that tries to aggregate off of it fails, and the kibana index page (on the version 5 server) says the field is not aggregatable or searchable.

Data-

```json
{
  "_index": "screeps-orders-2016_12",
  "_type": "orders",
  "_id": "AVkGxCpiFgRTfYeuvk60",
  "_score": null,
  "_source": {
    "type": "sell",
    "amount": 5000,
    "remainingAmount": 5000,
    "price": 1.8,
    "roomName": "E58N38",
    "date": "2016-12-16T08:33:43.000Z",
    "resourceType": "Z",
    "tick": 16049217,
    "orderId": "58102d265ec178d32e7a37d9",
    "npc": false,
    "username": "Bogden",
    "room_x_dir": "E",
    "room_x": 58,
    "room_y_dir": "N",
    "room_y": 38
  },
  "fields": {
    "date": [
      1481877223000
    ]
  },
  "sort": [
    1481877223000
  ]
}
```


Mapping from 2.x

```json
{
  "screeps-orders-2016_12" : {
    "mappings" : {
      "orders" : {
        "properties" : {
          "alliance" : {
            "type" : "string"
          },
          "amount" : {
            "type" : "long"
          },
          "date" : {
            "type" : "date",
            "format" : "strict_date_optional_time||epoch_millis"
          },
          "npc" : {
            "type" : "boolean"
          },
          "orderId" : {
            "type" : "string"
          },
          "price" : {
            "type" : "double"
          },
          "remainingAmount" : {
            "type" : "long"
          },
          "resourceType" : {
            "type" : "string"
          },
          "roomName" : {
            "type" : "string"
          },
          "room_x" : {
            "type" : "long"
          },
          "room_x_dir" : {
            "type" : "string"
          },
          "room_y" : {
            "type" : "long"
          },
          "room_y_dir" : {
            "type" : "string"
          },
          "tick" : {
            "type" : "long"
          },
          "type" : {
            "type" : "string"
          },
          "username" : {
            "type" : "string"
          }
        }
      }
    }
  }
}
```

Mapping from 5.1-

```json
{
  "screeps-orders-2016_12": {
    "mappings": {
      "orders": {
        "properties": {
          "alliance": {
            "type": "string"
          },
          "amount": {
            "type": "long"
          },
          "date": {
            "type": "date",
            "format": "strict_date_optional_time||epoch_millis"
          },
          "npc": {
            "type": "boolean"
          },
          "orderId": {
            "type": "string"
          },
          "price": {
            "type": "double"
          },
          "remainingAmount": {
            "type": "long"
          },
          "resourceType": {
            "type": "string"
          },
          "roomName": {
            "type": "string"
          },
          "room_x": {
            "type": "long"
          },
          "room_x_dir": {
            "type": "string"
          },
          "room_y": {
            "type": "long"
          },
          "room_y_dir": {
            "type": "string"
          },
          "tick": {
            "type": "long"
          },
          "type": {
            "type": "string"
          },
          "username": {
            "type": "string"
          }
        }
      }
    }
  }
}
```

**Comment by s1monw** [comment] 2016-12-16 08:44
> Any query that tries to aggregate off of it fails, and the kibana index page (on the version 5 server) says the field is not aggregatable or searchable.

can you provide the query json and the rest response of the failure please.

**Comment by jimczi** [comment] 2016-12-16 08:45
Can you also share the mappings of all your indices that match your index pattern in Kibana ? 
Are you using `screeps-orders-2016_12` only or do you have an index pattern like `screeps-orders-*` ? I am saying this because fields with conflicting mapping will no longer appear as searchable/aggregatable in Kibana. So for instance if the field `price` is defined as a `double` in one index and as a `long` in another one then it won't work with Kibana 5 if they are part of the same index pattern.

**Comment by tedivm** [comment] 2016-12-16 08:59
@jimczi is the winner- it looks like in some places it was `long` and in other places it was `double`.

**Comment by jimczi** [comment] 2016-12-16 09:09
This check has been added in Kibana to avoid problems when running aggregations or search on this conflicting field. I also understand how it can be confusing when upgrading from 2.4.
You'll need to fix your mapping to make it work so I am closing the ticket. 
Thank you for reporting @tedivm

**Closed by jimczi** 2016-12-16 09:09 UTC
