### ISSUE TITLE
Elasticsearch no longer writing data after upgrading from 7.6 to 7.7

### ISSUE THREAD

**Issue by danfinn** [elastic/elasticsearch#58064] opened 2020-06-12 17:01 UTC
Ubuntu 16.04
Version: 7.7.1, Build: default/deb/ad56dce891c901a492bb1ee393f12dfff473a423/2020-05-28T16:30:01.040088Z, JVM: 1.8.0_201

java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

Recently we upgraded (via apt and default Ubuntu repos) from 7.6 to 7.7.

Our ELK pipeline looks like so:

filebeat shipping logs on all our nodes -> ELK on a single server

After upgrading to 7.7 as far as I can tell elasticsearch is no longer writing data to any of our indexes.  I enabled ruby debug logging in logstash and everything looks fine there, logs are flowing in and look normal, no errors.  I enabled debug logging in elasticsearch and I can see the connections from logstash sending logs to elasticsearch, no errors there.

```
[2020-06-11T18:30:20,989][TRACE][o.e.t.T.tracer           ] [ps-dev-elk] [841][indices:data/write/bulk[s][p]] received response from [{ps-dev-elk}{qmfFc9wtTn20jWjM6mCQMw}{iExEVJUJSJa36HZgIL-gOw}{127.0.0.1}{127.0.0.1:9300}{dilmrt}{ml.machine_memory=16808701952, xpack.installed=true, transform.node=true, ml.max_open_jobs=20}]
[2020-06-11T18:30:20,990][TRACE][o.e.t.T.tracer           ] [ps-dev-elk] [843][indices:admin/seq_no/global_checkpoint_sync[p]] sent to [{ps-dev-elk}{qmfFc9wtTn20jWjM6mCQMw}{iExEVJUJSJa36HZgIL-gOw}{127.0.0.1}{127.0.0.1:9300}{dilmrt}{ml.machine_memory=16808701952, xpack.installed=true, transform.node=true, ml.max_open_jobs=20}] (timeout: [null])
[2020-06-11T18:30:20,991][TRACE][o.e.t.T.tracer           ] [ps-dev-elk] [843][indices:admin/seq_no/global_checkpoint_sync[p]] received request
[2020-06-11T18:30:20,991][TRACE][o.e.t.T.tracer           ] [ps-dev-elk] [842][indices:data/write/bulk[s][p]] sent response
[2020-06-11T18:30:20,991][TRACE][o.e.t.T.tracer           ] [ps-dev-elk] [842][indices:data/write/bulk[s][p]] received response from [{ps-dev-elk}{qmfFc9wtTn20jWjM6mCQMw}{iExEVJUJSJa36HZgIL-gOw}{127.0.0.1}{127.0.0.1:9300}{dilmrt}{ml.machine_memory=16808701952, xpack.installed=true, transform.node=true, ml.max_open_jobs=20}]
[2020-06-11T18:30:20,991][TRACE][o.e.t.T.tracer           ] [ps-dev-elk] [843][indices:admin/seq_no/global_checkpoint_sync[p]] sent response
[2020-06-11T18:30:20,991][TRACE][o.e.t.T.tracer           ] [ps-dev-elk] [843][indices:admin/seq_no/global_checkpoint_sync[p]] received response from [{ps-dev-elk}{qmfFc9wtTn20jWjM6mCQMw}{iExEVJUJSJa36HZgIL-gOw}{127.0.0.1}{127.0.0.1:9300}{dilmrt}{ml.machine_memory=16808701952, xpack.installed=true, transform.node=true, ml.max_open_jobs=20}]
```

We use daily indexes and the logstash-* index pattern.  Yesterday I removed the index for that specific day.  Normally this would result in the index quickly being recreated.  That never happened.  This morning I checked and there has not been an index created for today.

As best as I can tell, logs are flowing into elasticsearch but are not being written anywhere.  Looking at the output for shards I don't see any document counts increasing on any of the shards.

```
root@ps-dev-elk:/var/log/logstash# curl -XGET localhost:9200/_cat/shards?v
index                    shard prirep state          docs   store ip        node
.kibana_8                0     p      STARTED          91 126.6kb 127.0.0.1 ps-dev-elk
.kibana_task_manager_1   0     p      STARTED           2   7.2kb 127.0.0.1 ps-dev-elk
logstash-2020.06.03      0     p      STARTED    14712122   7.3gb 127.0.0.1 ps-dev-elk
logstash-2020.06.03      0     r      UNASSIGNED
logstash-2020.06.02      0     p      STARTED    14813812   7.3gb 127.0.0.1 ps-dev-elk
logstash-2020.06.02      0     r      UNASSIGNED
logstash-2020.06.10      0     p      STARTED    12666539   5.7gb 127.0.0.1 ps-dev-elk
logstash-2020.06.10      0     r      UNASSIGNED
logstash                 0     p      STARTED     3057574   1.8gb 127.0.0.1 ps-dev-elk
logstash                 0     r      UNASSIGNED
.kibana_task_manager_3   0     p      STARTED           6    21kb 127.0.0.1 ps-dev-elk
.apm-custom-link         0     p      STARTED           0    230b 127.0.0.1 ps-dev-elk
.apm-agent-configuration 0     p      STARTED           0    283b 127.0.0.1 ps-dev-elk
logstash-2020.06.08      0     p      STARTED    12663722   5.7gb 127.0.0.1 ps-dev-elk
logstash-2020.06.08      0     r      UNASSIGNED
.kibana_task_manager_2   0     p      STARTED           3  25.9kb 127.0.0.1 ps-dev-elk
.kibana_10               0     p      STARTED         241   169kb 127.0.0.1 ps-dev-elk
logstash-2020.06.04      0     p      STARTED    14423582   7.1gb 127.0.0.1 ps-dev-elk
logstash-2020.06.04      0     r      UNASSIGNED
.async-search            0     p      STARTED           2 685.9kb 127.0.0.1 ps-dev-elk
.kibana_9                0     p      STARTED         227 220.2kb 127.0.0.1 ps-dev-elk
logstash-2020.06.06      0     p      STARTED    12435442   5.5gb 127.0.0.1 ps-dev-elk
logstash-2020.06.06      0     r      UNASSIGNED
logstash-2020.06.07      0     p      STARTED    12436608   5.5gb 127.0.0.1 ps-dev-elk
logstash-2020.06.07      0     r      UNASSIGNED
.kibana-6                0     p      STARTED          75  78.3kb 127.0.0.1 ps-dev-elk
.kibana-6                0     r      UNASSIGNED
logstash-2020.06.05      0     p      STARTED    12650352   5.7gb 127.0.0.1 ps-dev-elk
logstash-2020.06.05      0     r      UNASSIGNED
.tasks                   0     p      STARTED           1   6.6kb 127.0.0.1 ps-dev-elk
logstash-2020.06.09      0     p      STARTED    12686744   5.8gb 127.0.0.1 ps-dev-elk
logstash-2020.06.09      0     r      UNASSIGNED
.kibana_7                0     p      STARTED          86  87.2kb 127.0.0.1 ps-dev-elk
```

I am not seeing any errors in the logstash logs or the elasticsearch logs and am not sure what else might be causing this.

**Comment by cbuescher** [comment] 2020-06-15 08:18
@danfinn sorry to hear you are having trouble with Elasticsearch. However, your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a specific problem with your setup more than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.

**Closed by cbuescher** 2020-06-15 08:18 UTC
Labels: >bug, needs:triage

**Comment by danfinn** [comment] 2020-06-16 14:51
@cbuescher I have posted on the support forum.  I posted 5 days ago and have not gotten a response.  I have also been asking on #elasticsearch on irc and have not gotten any responses there.

I agree that this may be a config issue on our end but you closed it assuming its not a bug and I am not sure you know that to be the case for sure.  All we did was upgraded from 7.6 to 7.7 and we now are getting nothing written to indexes by elasticsearch and no errors at all either.  I am not sure what config option we would have enabled that would cause this?

**Comment by cbuescher** [comment] 2020-06-16 16:27
> I have posted on the support forum. I posted 5 days ago and have not gotten a response.

I'm sorry you didn't get response in the forums yet. Unfortunately, since there's no concrete indication of an error here (like an error or log message) that wasn't there before, I still think the forum is the right way to narrow this down. With the information currently available here I don't see how we can reproduce or investigate as a bug.
