### ISSUE TITLE
[feature request]iteration term aggregration

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#18261] opened 2016-05-11 03:55 UTC
**Describe the feature**:
currently term aggregation execute below: the node coordinating the search process will request each shard to provide its own top size term buckets and once all shards respond, it will reduce the results to the final list that will then be returned to the client.
if try to get all terms agg, it will cause memory issue.
this request is below:
not based on top size term but top term on each shard's term dictionary and return the agg. maintain a context for iteration to traverse all terms and get exact results.

**Comment by jpountz** [comment] 2016-05-11 06:25
Closing as duplicate of #4915

**Closed by jpountz** 2016-05-11 06:25 UTC
