### ISSUE TITLE
Defining analyzer on index doesn't complain about unknown parameters

### ISSUE THREAD

**Issue by fsoikin** [elastic/elasticsearch#16451] opened 2016-02-04 14:32 UTC
The following snippet does not produce an error:

```
post analyzertest1
  {
    "settings": {
        "analysis": {
            "analyzer": {
                "my_analyzer": {
                    "tokenizer": "standard",
                    "abracadabra": "foo"
                }
            }
        }
    }
  }
```

**Comment by javanna** [comment] 2016-02-11 17:24
We have recently introduced settings validation in master, meaning that unknown settings are now rejected. It doesn't help this case though as validation doesn't go that deep. For the analysis section we define settings groups, like `index.analysis.filter`, `index.analysis.tokenizer` etc. and only known groups can be used. But within each group, we don't have validation. That would need to be implemented by each analyzer, tokenizer, token filter etc. and we have a lot of them. Maybe an alternative would be, given that all the settings are loaded in memory, that while reading settings each component removes what was read and if anything was left at the end those are unsupported settings and we should throw error. Not sure how feasible this is though. Marking for discussion.

**Comment by javanna** [comment] 2016-02-12 11:19
We discussed this as part of FixItFriday. Everybody agrees that we should fix this. The check should be made on the node that receives the request though (or on the master node), rather than failing on each shard while trying to create the index. That makes it a high hanging fruit, along with having to find a smart way to fail without requiring explicit validation on each single tokenizer, token filter etc.

**Comment by jimczi** [comment] 2020-11-26 08:19
Closing as duplicate of #41299

**Closed by jimczi** 2020-11-26 08:19 UTC
Labels: :Search/Analysis, >enhancement, Team:Search, help wanted, high hanging fruit
