### ISSUE TITLE
Allow "safe" custom analyzers for keyword fields

### ISSUE THREAD

**Issue by mattweber** [elastic/elasticsearch#21137] opened 2016-10-26 17:43 UTC
Please allow setting custom analyzers that use the `keyword` tokenizer and [safe token filters](https://github.com/elastic/elasticsearch/issues/12394#issuecomment-128102606) on keyword fields.  This would be great so we can use `doc_values` for things like case-insensitive sorting and icu collation without needing to create pipelines.

This was originally discussed in #12394 and the last comment from @jpountz said this can be done in a future `5.x` release.  This issue is to keep track of this potential enhancement.

**Comment by dakrone** [comment] 2016-10-26 17:54
@mattweber I believe @jpountz is currently working on this!

**Comment by s1monw** [comment] 2016-10-26 19:04
this is a duplicate of https://github.com/elastic/elasticsearch/issues/18064 and we are waiting to upgrade to lucene 6.2 see https://issues.apache.org/jira/browse/LUCENE-7355
closing this for now @mattweber please see the other issue

**Closed by s1monw** 2016-10-26 19:04 UTC

**Comment by mattweber** [comment] 2016-10-26 19:12
Thanks @s1monw, did not see that.

**Comment by Omega359** [comment] 2016-10-26 19:59
If @jpountz  is working on #18064 can we have that issue updated to be assigned without the adoptme label? This feature would be a huge, huge deal for me to help reduce memory usage in my cluster.

**Comment by jpountz** [comment] 2016-10-27 19:55
Done.
