### ISSUE TITLE
addr is of illegal length

### ISSUE THREAD

**Issue by kender1314** [elastic/elasticsearch#65716] opened 2020-12-02 07:59 UTC
**elasticsearch version**: 7.9.1
**elasticsearch command**:
```
POST /_search?rest_total_hits_as_int=true
{
	"index": [
		"ip_mac_merge_*"
	],
	"ignore_unavailable": true
}
{
	"size": 0,
	"query": {
		"bool": {
			"must_not": [],
			"must": [
				{
					"query_string": {
						"query": "*",
						"analyze_wildcard": true
					}
				},
				{
					"range": {
						"date": {
							"gte": "2020-11-03 00:00:00",
							"lte": "2020-12-02 23:59:59"
						}
					}
				}
			]
		}
	},
	"fielddata_fields": [
		"e_date",
		"s_date",
		"create_date",
		"date"
	],
	"from": 0,
	"_source": {
		"excludes": [
			"@timestamp",
			"link_id"
		]
	},
	"fields": [
		"*",
		"_source"
	],
	"aggs": {
		"ip2": {
			"terms": {
				"field": "ip2",
				"size": 10
			}
		},
		"ip1": {
			"terms": {
				"field": "ip2",
				"size": 10
			}
		}
	}
}
```

**error repose**:
```
{
	"error": {
		"root_cause": [
			{
				"type": "illegal_argument_exception",
				"reason": "encoded bytes are of incorrect length"
			}
		],
		"type": "illegal_argument_exception",
		"reason": "encoded bytes are of incorrect length",
		"caused_by": {
			"type": "illegal_argument_exception",
			"reason": "addr is of illegal length"
		}
	},
	"status": 400
}
```
The field type of ip1 and ip2 is ip type.

I conducted some tests. When I shorten the time range to query, the query results can be returned normally, but the ipv6 values in the ip1 and ip2 fields are garbled. 
This is part of the result
```
"ip2": {
  "doc_count error_upper bound": 12442,
  "sum_other_doc_count": 1870188，
  "buckets":[ 
     {
        "key": \u0000\u0000\u0000\u0000 \u0000\u0000\u0000\u0000\u0000\u0000??\tR",
        "doc_count": 29738
    }
    {
        "key": "192.168.9.237",
        "doc_count": 29362
    }
  ]
}
```

Our last version used 7.6.2, and there is no problem with this msearch query itself.

I suspect that there is a bug in elasticsearch 7.9.1, but I am not sure if this error is due to ipv6.

How should this problem be solved? thank you very much.

**Comment by cbuescher** [comment] 2020-12-04 11:29
Closing as duplicate of https://github.com/elastic/elasticsearch/issues/65865

**Closed by cbuescher** 2020-12-04 11:29 UTC
Labels: >bug, needs:triage
