### ISSUE TITLE
[DOCS] Incorrect info in TESTING.asciidoc

### ISSUE THREAD

**Issue by nilanshu96** [elastic/elasticsearch#78631] opened 2021-10-04 16:57 UTC
The following command provided in doc to run a specific YAML REST test case for rest-api-spec doesn't work 

````
./gradlew ':rest-api-spec:yamlRestTest' \
  --tests "org.elasticsearch.test.rest.ClientYamlTestSuiteIT" \
  -Dtests.method="test {p0=cat.segments/10_basic/Help}"
````

The above command produces the following error

````
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':rest-api-spec:yamlRestTest'.
> No tests found for given includes: [**/*IT.class](include rules) [**/*$*.class](exclude rules) [org.elasticsearch.test.rest.ClientYamlTestSuiteIT](--tests filter)
````

Changing `p0` to `yaml` as ClientYamlTestSuiteIT uses a name annotation of `yaml` runs the test without any error.

Other than rest-api-spec, using p0 works for running yaml tests in other packages where a named annotation isn't used. For example the following command runs without any error
````
./gradlew ':x-pack:plugin:yamlRestTest' --tests "org.elasticsearch.xpack.test.rest.XPackRestIT" -Dtests.method="test {p0=analytics/top_metrics/fetch keyword}"
````

I was thinking of working on one of the open issues as part of hacktoberfest and this small error caused me confusion for hours. 
Please can someone confirm if there aren't any open PRs which fixes this documentation error? Else I'll raise a PR to fix this issue.

**Comment by jrodewig** [comment] 2021-10-05 13:10
Thanks for raising this, @nilanshu96. I was able to reproduce your error. It looks like we recently added the annotation with https://github.com/elastic/elasticsearch/pull/69462:

https://github.com/elastic/elasticsearch/blob/f3aac00f5d568f2103de83027daddce5b6201ad8/rest-api-spec/src/yamlRestTest/java/org/elasticsearch/test/rest/ClientYamlTestSuiteIT.java#L24

> Please can someone confirm if there aren't any open PRs which fixes this documentation error? Else I'll raise a PR to fix this issue.

A PR would be welcome! I'm not aware of any other open PRs to address this.

**Comment by nilanshu96** [comment] 2021-10-05 14:41
Hi @jrodewig, thanks for addressing my query. But before raising a PR I wanted to discuss whether changing p0 to yaml would be enough. As I've mentioned previously, using p0 does work for other projects like x-pack:plugin. It seems only rest-api-spec is using the yaml name annotation.  Which is why I believe commands using both yaml and p0 should be added to the doc to avoid any confusion. So should I add both the commands in the doc?

**Comment by jrodewig** [comment] 2021-10-05 17:30
Thanks for following up and seeking clarification. Tagging @elastic/es-delivery to keep me honest.

> As I've mentioned previously, using p0 does work for other projects like x-pack:plugin. It seems only rest-api-spec is using the yaml name annotation.

After taking a look, it seems like *most* other gradle projects use the yaml name annotation for their REST YAML test suites.
It seems like the `:x-pack:plugin:yamlRestTest` task may just be an exception.

While documenting `p0` is an option, it'll be easier to add the name annotation to `XPackRestIT` so it's consistent and update the docs to only use `yaml=`. That would mean this would no longer be a docs-only issue, however.

**Comment by jrodewig** [comment] 2021-10-05 17:35
Assigning this to myself for tracking purposes. A PR is still welcome @nilanshu96!

**Comment by nilanshu96** [comment] 2021-10-05 18:29
@jrodewig  I've added a PR. But it is saying I haven't signed the contributor agreement but I did sign it. What should I do?
Also I've only made a minor change of changing `p0` to `yaml`. There's also the following command in the doc that has `p0`. I don't know if I should change there as well
````
./gradlew :x-pack:qa:rolling-upgrade:v7.7.0#bwcTest \
 -Dtests.class=org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT \
 -Dtests.method="test {p0=*/40_ml_datafeed_crud/*}"
````

**Comment by jrodewig** [comment] 2021-10-05 19:03
Thanks @nilanshu96. I responded about the contributor agreement in the PR: https://github.com/elastic/elasticsearch/pull/78716#issuecomment-934685717


> There's also the following command in the doc that has p0. I don't know if I should change there as well

That's just an outdated BWC test reference. The test will run if you replace `7.7.0` with a more recent version. On the `master` branch, that would be:

```
./gradlew :x-pack:qa:rolling-upgrade:v7.16.0#bwcTest \
 -Dtests.class=org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT \
 -Dtests.method="test {p0=*/40_ml_datafeed_crud/*}"
```

We can maybe add a comment to that effect to the docs. However, I'm not sure it's worth it to keep these version numbers synced. They'll change pretty frequently.

**Comment by nilanshu96** [comment] 2021-10-05 19:56
I'm completely new to this repo so I cannot comment any further on what you mentioned as I lack the knowledge. I was just trying to resolve an open issue in x-pack:plugin when I encountered the minor error in the docs. I believe that it would be great to update the TESTING docs as newbies like me would often run the tests to see how things work in the repo. Anyway I hope I was of some help today.

**Comment by jrodewig** [comment] 2021-10-05 20:02
You were very helpful. Thanks for raising this, @nilanshu96. We appreciate your contribution!

**Closed** 2021-10-07 00:55 UTC
Labels: >docs, :Delivery/Build, v8.0.0, Team:Docs, Team:Delivery
