### ISSUE TITLE
IndexMetaData class shows two different value for important number of shards setting

### ISSUE THREAD

**Issue by amitmbm** [elastic/elasticsearch#87014] opened 2022-05-21 07:23 UTC
### Elasticsearch Version

8.2

### Installed Plugins

None

### Java Version

_bundled_

### OS Version

MacOS

### Problem Description

[Index MetaData](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/cluster/metadata/IndexMetadata.java) class, which is responsible for all the index settings, shows the two different value for very important setting `index.number_of_shards` .

Method `buildNumberOfShardsSetting()` has below code 

```
static Setting<Integer> buildNumberOfShardsSetting() {
        /* This is a safety limit that should only be exceeded in very rare and special cases. The assumption is that
         * 99% of the users have less than 1024 shards per index. We also make it a hard check that requires restart of nodes
         * if a cluster should allow to create more than 1024 shards per index. NOTE: this does not limit the number of shards
         * per cluster. this also prevents creating stuff like a new index with millions of shards by accident which essentially
         * kills the entire cluster with OOM on the spot.*/
        final int maxNumShards = Integer.parseInt(System.getProperty("es.index.max_number_of_shards", "1024"));
        if (maxNumShards < 1) {
            throw new IllegalArgumentException("es.index.max_number_of_shards must be > 0");
        }
        return Setting.intSetting(SETTING_NUMBER_OF_SHARDS, 1, 1, maxNumShards, Property.IndexScope, Property.Final);
    }

```

here default value for the setting is `1` but in the getter of same setting both JavaDoc and code has default value set to `-1` as shown below.

```
 /**
         * Returns the number of shards.
         *
         * @return the provided value or -1 if it has not been set.
         */
        public int numberOfShards() {
            return settings.getAsInt(SETTING_NUMBER_OF_SHARDS, -1);
        }
```

This is creating confusion for a very important setting and should be changed to `1` which is the correct default value.

### Steps to Reproduce

Code mistake explained in the issue itself.

### Logs (if relevant)

NA

**Comment by amitmbm** [comment] 2022-05-21 07:24
I would like to work on the fix and will link PR to issue soon.

**Comment by DaveCTurner** [comment] 2022-05-21 15:36
This method is only really for internal use and works as intended today (see my comment on #87015). Therefore I'm closing this.

**Closed by DaveCTurner** 2022-05-21 15:36 UTC
Labels: >bug, needs:triage
