### ISSUE TITLE
windows server2012 R2 elasticsearch start failed

### ISSUE THREAD

**Issue by kyunggyuyeol** [elastic/elasticsearch#41733] opened 2019-05-02 08:12 UTC
**Describe the feature**:

[2019-05-02T17:08:33,033][INFO ][o.e.e.NodeEnvironment    ] [node-1] using [1] data paths, mounts [[Data (D:)]], net usable_space [663.1gb], net total_space [681.4gb], types [NTFS]
[2019-05-02T17:08:33,041][INFO ][o.e.e.NodeEnvironment    ] [node-1] heap size [989.8mb], compressed ordinary object pointers [true]
[2019-05-02T17:08:33,047][INFO ][o.e.n.Node               ] [node-1] node name [node-1], node ID [K8xi-WbGTVqp66atdtHKcA]
[2019-05-02T17:08:33,048][INFO ][o.e.n.Node               ] [node-1] version[7.0.0], pid[4248], build[default/zip/b7e28a7/2019-04-05T22:55:32.697037Z], OS[Windows Server 2012 R2/6.3/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_211/25.211-b12]
[2019-05-02T17:08:33,050][INFO ][o.e.n.Node               ] [node-1] JVM home [C:\Program Files\Java\jdk1.8.0_211\jre]
[2019-05-02T17:08:33,052][INFO ][o.e.n.Node               ] [node-1] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=C:\Users\ADMINI~1\AppData\Local\Temp\2\elasticsearch, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -XX:+PrintGCDetails, -XX:+PrintGCDateStamps, -XX:+PrintTenuringDistribution, -XX:+PrintGCApplicationStoppedTime, -Xloggc:logs/gc.log, -XX:+UseGCLogFileRotation, -XX:NumberOfGCLogFiles=32, -XX:GCLogFileSize=64m, -Dio.netty.allocator.type=unpooled, -Delasticsearch, -Des.path.home=D:\ELKService\elasticsearch-7.0.0, -Des.path.conf=D:\ELKService\elasticsearch-7.0.0\config, -Des.distribution.flavor=default, -Des.distribution.type=zip, -Des.bundled_jd=true]
[2019-05-02T17:08:36,478][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [aggs-matrix-stats]
[2019-05-02T17:08:36,480][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [analysis-common]
[2019-05-02T17:08:36,481][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [ingest-common]
[2019-05-02T17:08:36,482][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [ingest-geoip]
[2019-05-02T17:08:36,484][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [ingest-user-agent]
[2019-05-02T17:08:36,485][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [lang-expression]
[2019-05-02T17:08:36,486][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [lang-mustache]
[2019-05-02T17:08:36,487][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [lang-painless]
[2019-05-02T17:08:36,488][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [mapper-extras]
[2019-05-02T17:08:36,489][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [parent-join]
[2019-05-02T17:08:36,490][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [percolator]
[2019-05-02T17:08:36,491][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [rank-eval]
[2019-05-02T17:08:36,492][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [reindex]
[2019-05-02T17:08:36,494][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [repository-url]
[2019-05-02T17:08:36,495][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [transport-netty4]
[2019-05-02T17:08:36,496][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [x-pack-ccr]
[2019-05-02T17:08:36,497][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [x-pack-core]
[2019-05-02T17:08:36,498][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [x-pack-deprecation]
[2019-05-02T17:08:36,499][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [x-pack-graph]
[2019-05-02T17:08:36,500][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [x-pack-ilm]
[2019-05-02T17:08:36,501][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [x-pack-logstash]
[2019-05-02T17:08:36,502][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [x-pack-ml]
[2019-05-02T17:08:36,504][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [x-pack-monitoring]
[2019-05-02T17:08:36,505][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [x-pack-rollup]
[2019-05-02T17:08:36,506][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [x-pack-security]
[2019-05-02T17:08:36,507][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [x-pack-sql]
[2019-05-02T17:08:36,508][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [x-pack-watcher]
[2019-05-02T17:08:36,510][INFO ][o.e.p.PluginsService     ] [node-1] no plugins loaded
[2019-05-02T17:08:44,215][INFO ][o.e.x.s.a.s.FileRolesStore] [node-1] parsed [0] roles from file [D:\ELKService\elasticsearch-7.0.0\config\roles.yml]
[2019-05-02T17:08:55,345][ERROR][o.e.b.Bootstrap          ] [node-1] Exception
org.elasticsearch.ElasticsearchException: Failed to create native process factories for Machine Learning
	at org.elasticsearch.xpack.ml.MachineLearning.createComponents(MachineLearning.java:427) ~[?:?]
	at org.elasticsearch.node.Node.lambda$new$9(Node.java:438) ~[elasticsearch-7.0.0.jar:7.0.0]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267) ~[?:1.8.0_211]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_211]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_211]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_211]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_211]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_211]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_211]
	at org.elasticsearch.node.Node.<init>(Node.java:441) ~[elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.node.Node.<init>(Node.java:251) ~[elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:211) ~[elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:211) ~[elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:325) [elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) [elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) [elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) [elasticsearch-cli-7.0.0.jar:7.0.0]
	at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-7.0.0.jar:7.0.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) [elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) [elasticsearch-7.0.0.jar:7.0.0]
Caused by: java.io.FileNotFoundException: \\.\pipe\controller_log_4248 (지정된 파일을 찾을 수 없습니다)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_211]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_211]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_211]
	at java.io.FileInputStream.<init>(FileInputStream.java:93) ~[?:1.8.0_211]
	at org.elasticsearch.xpack.ml.utils.NamedPipeHelper$PrivilegedInputPipeOpener.run(NamedPipeHelper.java:288) ~[?:?]
	at org.elasticsearch.xpack.ml.utils.NamedPipeHelper$PrivilegedInputPipeOpener.run(NamedPipeHelper.java:277) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_211]
	at org.elasticsearch.xpack.ml.utils.NamedPipeHelper.openNamedPipeInputStream(NamedPipeHelper.java:130) ~[?:?]
	at org.elasticsearch.xpack.ml.utils.NamedPipeHelper.openNamedPipeInputStream(NamedPipeHelper.java:97) ~[?:?]
	at org.elasticsearch.xpack.ml.process.ProcessPipes.connectStreams(ProcessPipes.java:131) ~[?:?]
	at org.elasticsearch.xpack.ml.process.NativeController.<init>(NativeController.java:61) ~[?:?]
	at org.elasticsearch.xpack.ml.process.NativeControllerHolder.getNativeController(NativeControllerHolder.java:40) ~[?:?]
	at org.elasticsearch.xpack.ml.MachineLearning.createComponents(MachineLearning.java:412) ~[?:?]
	... 20 more
[2019-05-02T17:08:55,364][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [node-1] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: ElasticsearchException[Failed to create native process factories for Machine Learning]; nested: FileNotFoundException[\\.\pipe\controller_log_4248 (지정된 파일을 찾을 수 없습니다)];
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-7.0.0.jar:7.0.0]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.0.0.jar:7.0.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) ~[elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.0.0.jar:7.0.0]
Caused by: org.elasticsearch.ElasticsearchException: Failed to create native process factories for Machine Learning
	at org.elasticsearch.xpack.ml.MachineLearning.createComponents(MachineLearning.java:427) ~[?:?]
	at org.elasticsearch.node.Node.lambda$new$9(Node.java:438) ~[elasticsearch-7.0.0.jar:7.0.0]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267) ~[?:1.8.0_211]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_211]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_211]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_211]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_211]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_211]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_211]
	at org.elasticsearch.node.Node.<init>(Node.java:441) ~[elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.node.Node.<init>(Node.java:251) ~[elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:211) ~[elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:211) ~[elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:325) ~[elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.0.0.jar:7.0.0]
	... 6 more
Caused by: java.io.FileNotFoundException: \\.\pipe\controller_log_4248 (지정된 파일을 찾을 수 없습니다)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_211]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_211]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_211]
	at java.io.FileInputStream.<init>(FileInputStream.java:93) ~[?:1.8.0_211]
	at org.elasticsearch.xpack.ml.utils.NamedPipeHelper$PrivilegedInputPipeOpener.run(NamedPipeHelper.java:288) ~[?:?]
	at org.elasticsearch.xpack.ml.utils.NamedPipeHelper$PrivilegedInputPipeOpener.run(NamedPipeHelper.java:277) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_211]
	at org.elasticsearch.xpack.ml.utils.NamedPipeHelper.openNamedPipeInputStream(NamedPipeHelper.java:130) ~[?:?]
	at org.elasticsearch.xpack.ml.utils.NamedPipeHelper.openNamedPipeInputStream(NamedPipeHelper.java:97) ~[?:?]
	at org.elasticsearch.xpack.ml.process.ProcessPipes.connectStreams(ProcessPipes.java:131) ~[?:?]
	at org.elasticsearch.xpack.ml.process.NativeController.<init>(NativeController.java:61) ~[?:?]
	at org.elasticsearch.xpack.ml.process.NativeControllerHolder.getNativeController(NativeControllerHolder.java:40) ~[?:?]
	at org.elasticsearch.xpack.ml.MachineLearning.createComponents(MachineLearning.java:412) ~[?:?]
	at org.elasticsearch.node.Node.lambda$new$9(Node.java:438) ~[elasticsearch-7.0.0.jar:7.0.0]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267) ~[?:1.8.0_211]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_211]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_211]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_211]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_211]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_211]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_211]
	at org.elasticsearch.node.Node.<init>(Node.java:441) ~[elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.node.Node.<init>(Node.java:251) ~[elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:211) ~[elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:211) ~[elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:325) ~[elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.0.0.jar:7.0.0]
	... 6 more

**Elasticsearch version** (`bin/elasticsearch --version`):

7.0.0
 
**Plugins installed**: []

**JVM version** (`java -version`):

1.8.0_211

**OS version** (`uname -a` if on a Unix-like system):

windows server 2012 R2

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

Windows 10 and Windows Server 2012 R2 are being tested. I do not know why I can not run only the server operating system.

**Comment by droberts195** [comment] 2019-05-07 11:24
Hi @kyunggyuyeol! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for confirmed bug reports and feature requests, and since this works on one machine it's possible it's an environmental problem rather than a bug. I'm closing this as an issue here, but encourage you to ask this question in the forum instead so that others can benefit from searching for the problem in the future. Please add the "machine learning" tag to the forum post, as this looks like the problem affects the machine learning functionality.

**Closed by droberts195** 2019-05-07 11:24 UTC
Labels: :Core/Infra/Core
