### ISSUE TITLE
yum command failing in buildDockerImage on Debian

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#47079] opened 2019-09-25 07:37 UTC
There are multiple builds failing across multiple branches, looking to be all on Debian:

https://gradle-enterprise.elastic.co/s/da2nqzn2l2c5c/console-log/raw

```
yum error: retry 10 in 10s
The command '/bin/sh -c for iter in {1..10}; do yum update -y &&     yum install -y nc &&     yum clean all && exit_code=0 && break || exit_code=$? && echo "yum error: retry $iter in 10s" && sleep 10; done;     (exit $exit_code)' returned a non-zero code: 1
```

Note that this has been failing for over a week, see https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=debian-8&&immutable/

**Comment by atorok** [comment] 2019-09-26 07:38
Duplicate of #47097

**Closed by atorok** 2019-09-26 07:38 UTC
Labels: :Core/Infra/Packaging, >test-failure
