### ISSUE TITLE
Inconsistency naming between mapping's "analysis" and _analyze API

### ISSUE THREAD

**Issue by masaruh** [elastic/elasticsearch#15258] opened 2015-12-05 06:55 UTC
_analyze API uses `filters`/`token_filters` while mapping's "analysis" uses `filter` and `char_filter`.
I feel it's better if both use the same parameter.

**Comment by clintongormley** [comment] 2015-12-05 13:00
Duplicate of #15189

**Closed by clintongormley** 2015-12-05 13:00 UTC
Labels: :Analysis
