### ISSUE TITLE
ForecastIT » testOverflowToDisk failed to create temporary directory on windows

### ISSUE THREAD

**Issue by alpar-t** [elastic/elasticsearch#44609] opened 2019-07-19 06:48 UTC
https://scans.gradle.com/s/vl3yktrv4xey4/tests/zcquf3hc3eoda-p36ippgnsdeic?openStackTraces=WzBd

```
org.elasticsearch.ElasticsearchStatusException: Cannot run forecast: Forecast internal error, failed to create temporary folder C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2012-r2\x-pack\plugin\ml\qa\native-multi-node-tests\build\testclusters\integTest-2\data\ml-local-data\tmp\job-forecast-it-test-overflow-to-disk\q5SsBWwBsH0xvxESbkgg error: The system cannot find the path specifiedClose stacktrace
at __randomizedtesting.SeedInfo.seed([DE1704EC3D6BE8E2:91C7BAB65415E152]:0)
at org.elasticsearch.xpack.core.ml.utils.ExceptionsHelper.badRequestException(ExceptionsHelper.java:67)
at org.elasticsearch.xpack.ml.action.TransportForecastJobAction.lambda$getForecastRequestStats$2(TransportForecastJobAction.java:111)
at org.elasticsearch.xpack.ml.job.persistence.JobResultsProvider.lambda$getForecastRequestStats$39(JobResultsProvider.java:1253)
at org.elasticsearch.xpack.ml.job.persistence.JobResultsProvider.lambda$searchSingleResult$33(JobResultsProvider.java:1093)
at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62)
at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)
at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:68)
at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:64)
at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)
at org.elasticsearch.action.search.AbstractSearchAsyncAction.sendSearchResponse(AbstractSearchAsyncAction.java:300)
at org.elasticsearch.action.search.FetchSearchPhase$3.run(FetchSearchPhase.java:213)
at org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:171)
at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:165)
at org.elasticsearch.action.search.ExpandSearchPhase.run(ExpandSearchPhase.java:119)
at org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:171)
at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:165)
at org.elasticsearch.action.search.FetchSearchPhase.moveToNextPhase(FetchSearchPhase.java:206)
at org.elasticsearch.action.search.FetchSearchPhase.lambda$innerRun$2(FetchSearchPhase.java:104)
at org.elasticsearch.action.search.CountedCollector.countDown(CountedCollector.java:53)
at org.elasticsearch.action.search.CountedCollector.onResult(CountedCollector.java:64)
at org.elasticsearch.action.search.FetchSearchPhase$2.innerOnResponse(FetchSearchPhase.java:166)
at org.elasticsearch.action.search.FetchSearchPhase$2.innerOnResponse(FetchSearchPhase.java:163)
at org.elasticsearch.action.search.SearchActionListener.onResponse(SearchActionListener.java:45)
at org.elasticsearch.action.search.SearchActionListener.onResponse(SearchActionListener.java:29)
at org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:54)
at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleResponse(SearchTransportService.java:431)
at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1137)
at org.elasticsearch.transport.InboundHandler$1.doRun(InboundHandler.java:224)
at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:193)
at org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:216)
at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:141)
at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:105)
at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:661)
at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:62)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1478)
at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1227)
at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1274)
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:582)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:536)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at java.lang.Thread.run(Thread.java:834)
[2019-07-18T04:21:07,728][INFO ][o.e.x.m.i.ForecastIT     ] [testOverflowToDisk] before test
[2019-07-18T04:21:07,728][INFO ][o.e.x.m.i.ForecastIT     ] [testOverflowToDisk] [ForecastIT#testOverflowToDisk]: setting up test
[2019-07-18T04:21:08,394][INFO ][o.e.x.m.i.ForecastIT     ] [testOverflowToDisk] [ForecastIT#testOverflowToDisk]: all set up test
[2019-07-18T04:21:37,903][INFO ][o.e.x.m.i.ForecastIT     ] [testOverflowToDisk] [ForecastIT#testOverflowToDisk]: cleaning up after test
[2019-07-18T04:21:39,603][INFO ][o.e.x.m.i.ForecastIT     ] [testOverflowToDisk] [ForecastIT#testOverflowToDisk]: cleaned up after test
[2019-07-18T04:21:39,603][INFO ][o.e.x.m.i.ForecastIT     ] [testOverflowToDisk] after test
REPRODUCE WITH: gradlew :x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner --tests "org.elasticsearch.xpack.ml.integration.ForecastIT.testOverflowToDisk" -Dtests.seed=DE1704EC3D6BE8E2 -Dtests.security.manager=true -Dtests.locale=en-SL -Dtests.timezone=Etc/GMT+11 -Dcompiler.java=12 -Druntime.java=11
```

**Comment by droberts195** [comment] 2019-09-17 13:04
`C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2012-r2\x-pack\plugin\ml\qa\native-multi-node-tests\build\testclusters\integTest-2\data\ml-local-data\tmp\job-forecast-it-test-overflow-to-disk\q5SsBWwBsH0xvxESbkgg` has 263 characters.  I think the maximum is 260.

If this theory is correct then renaming the job from `job-forecast-it-test-overflow-to-disk` to `job-forecast-test-disk-overflow` would solve it.  When I get a spare moment I'll test this on a local Windows machine.

**Comment by atorok** [comment] 2019-09-18 07:26
@droberts195 isn't this a problem users could run into if the data dir is far enough in a path , so not just a test issue.
I found some information here : https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#maximum-path-length-limitation

**Comment by droberts195** [comment] 2019-09-18 08:40
> isn't this a problem users could run into if the data dir is far enough in a path , so not just a test issue

In theory yes, but in practice nobody installs software in such deep paths except in CI systems.  The effort to solve this is enormous and will prevent changes that are more useful to real users from being implemented.  The problem is that Microsoft only implements their workarounds for path length in the wide character versions of their API functions.  The ML C++ uses UTF-8 internally.  This matches what people usually use on Mac/Linux.  A pure Windows C++ program would usually use UTF-16 internally, and naturally use the wide character versions of the API functions.  But for us to do this would mean either we are using UTF-16 as our character set on Mac/Linux, or else our C++ is using a different character size on different platforms which would create more bugs than it fixes.

Since it's only 3 characters over I think it is best to implement a workaround to get the test to work.  Or if that becomes unviable because the Jenkins paths are made even longer then we just mute the test on Windows again.  (But it would be nice to get this running even if only for a while as it may find further bugs like trying to delete open files and those would be worse because they could affect customers even with realistic path lengths.)

**Comment by atorok** [comment] 2019-09-18 08:53
Would it make sense to add a bootstrap check on windows on something to that effect to enforce that the data dir is  below some reasonable length ? 
Even if this happens in CI, and non production use-cases it seems a bit difficult to realize what's going on.  
Users might still spin up ES in those environments as do we, it seems like something relatively easy to do that would avoid most of the pain.

**Comment by droberts195** [comment] 2020-09-30 10:27
Hopefully the move from Jenkins to Team City will allow this test to be unmuted, as I understand the paths will be shorter.

**Comment by valeriy42** [comment] 2024-10-15 09:43
There has not been another test failure in the past 5 years. Switching from Jenkins to Buildkite probably mitigated the CI issues. So, I'm closing it.

**Closed** 2024-11-06 18:02 UTC
Labels: >test-failure, :ml, v7.2.2, v7.3.3, Team:ML, v6.8.15, low-risk, v9.0.0
