### ISSUE TITLE
Setting ES_HEAP_SIZE in windows

### ISSUE THREAD

**Issue by PandiyanCool** [elastic/elasticsearch#13648] opened 2015-09-18 05:04 UTC
I'm using Windows 2012 R2 machine.

I have set my Heap Size in Environment variable as follows
ES_HEAP_SIZE
4g

After setting the heap size, i have installed Elasticsearch as windows service using command

> service.bat install

When i started the service, Elasticsearch services has taken 4GB properly (Checked in Taskmanger.exe)

After some time, the memory used by elasticsearch service is came down to 1 GB.

Is this expected?

Helps much appreciated :)

**Comment by clintongormley** [comment] 2015-09-18 15:18
@PandiyanCool Are you setting `bootstrap.mlockall` to true in the config file?  Also, what version of ES are you using?

**Comment by PandiyanCool** [comment] 2015-09-19 03:45
Yup, I've set it. I'm using version 1.7.1

**Comment by clintongormley** [comment] 2015-09-19 13:22
@gmarz any ideas about this?

**Comment by gmarz** [comment] 2015-09-21 21:14
Hey @PandiyanCool how much RAM does the machine have?  What's the % of total memory used after elasticsearch starts up (and the 4gb is allocated)?

**Comment by PandiyanCool** [comment] 2015-09-22 01:55
@gmarz 
Total RAM memory is 8 GB
After installing & starting the Elasticsearch service, 4 GB is used by Elasticsearch service (checked in task manager - details tab)

After some time, Elasticsearch services is using ~less than 1 GB (as per task manger details).

But when i checked in nodes/stats in API request, the jvm committed heap size is showing 4 GB properly.

Am i missing something?

**Comment by gmarz** [comment] 2015-09-22 21:53
So I've been looking into this have been able to reproduce the same behavior, and I don't think this is expected.

The 4gb committed heap size that you see in the node stats API is the amount of virtual memory that's *reserved* by setting ES_HEAP_SIZE (`Xms`), which is expected, even with `bootstrap.mlockall` disabled.

By enabling `bootstrap.mlockall`, we expect the call to `VirtualLock()` to lock the working set into physical memory, which happens initially (this is the memory you see in task manager), but eventually drops off.

I don't have a solid explanation for this yet, but I have observed that the more memory pressure the system is under (i.e. less free space available), the quicker the "drop off" occurs.  It's as though Windows doesn't respect the fact that the pages in the working set are locked, and will release them when resources become low.

There's a lot of info out there that seems to indicate that `VirtualLock` doesn't guarantee pages won't be swapped, only reduces the odds, however the documentation says nothing about this.

I'll continue to look into a possible fix/explanation for this...

**Comment by PandiyanCool** [comment] 2015-09-23 04:06
Sure @gmarz  :)

**Comment by gmarz** [comment] 2015-09-23 17:02
From https://msdn.microsoft.com/en-us/library/windows/desktop/ms686237(v=vs.85).aspx:

> When an application is idle, or a low-memory situation causes a demand for memory, the operating system can reduce the application's working set below its minimum working set limit. If memory is abundant, the system might allow an application to exceed its maximum working set limit. The QUOTA_LIMITS_HARDWS_MIN_ENABLE and QUOTA_LIMITS_HARDWS_MAX_ENABLE flags enable you to ensure that limits are enforced.

Sounds like this could be the issue.  Currently, we call [SetProcessWorkingSetSize](https://msdn.microsoft.com/en-us/library/windows/desktop/ms686234(v=vs.85).aspx) which doesn't accept any flags for controlling the working set size limits.

I'm going to try replacing this with `SetProcessWorkingSetSizeEx()` with the QUOTA_LIMITS_HARDWS_MIN_ENABLE flag.

**Comment by PandiyanCool** [comment] 2015-09-24 04:35
thanks for information @gmarz :) Happy to receive more details about this, Interesting.

**Comment by PandiyanCool** [comment] 2015-10-01 09:52
Hi @gmarz ,

Is there any updates on this?

**Comment by PandiyanCool** [comment] 2015-12-08 05:50
hi @gmarz 

Is there any updates on this?

**Comment by gmarz** [comment] 2015-12-08 14:33
Hey @PandiyanCool, sorry for the delay here.  Had to put this on the back burner as I've been bogged down with other commitments.  That said, haven't forgotten about this and will look into it in the coming days.

**Comment by PandiyanCool** [comment] 2015-12-10 06:32
thanks @gmarz  :)

**Comment by blkbltjns** [comment] 2017-01-17 20:23
Any word on this issue?

**Comment by PandiyanCool** [comment] 2017-02-13 13:18
No @blkbltjns

**Comment by gmarz** [comment] 2017-02-13 15:33
Hey @PandiyanCool @blkbltjns I apologize for the really slow reply on this one.

I did try swapping out `SetProcessWorkingSetSize` with `SetProcessWorkingSetSizeEx(QUOTA_LIMITS_HARDWAS_MIN_ENABLE)` a while back as explained above, but unfortunately it didn't have any effect.

> There's a lot of info out there that seems to indicate that VirtualLock doesn't guarantee pages won't be swapped, only reduces the odds, however the documentation says nothing about this.

This seems to be true, and VirtualLock is just a hint, or a best effort- and doesn't guarantee to keep pages in physical memory.  If the process has no running threads, or the system is low on resources, the OS is free to swap out the process.  We will update our docs to mention this.

Still, it's worth enabling it as it's better than nothing.  However, if you want to guarantee that ES is never swapped then you can reduce the size of the page file, or disable it entirely (however this has other consequences like losing memory dumps, and running out of memory can cause the entire OS to crash).

Closing this one for now as there isn't anything actionable.  But please feel free to continue discussion.

**Closed by gmarz** 2017-02-13 15:33 UTC
Labels: :Core, discuss
