### ISSUE TITLE
Replace AntFixture usage with TestFixturesPlugin

### ISSUE THREAD

**Issue by breskeby** [elastic/elasticsearch#66991] opened 2021-01-05 10:55 UTC
- allows us to have a common structure for running fixture code
- allows us to ditch groovy completely for build logic code and move to 100% java for our production code (tests will stay java / groovy)

**Comment by mark-vieira** [comment] 2023-10-04 22:27
Duplicate of https://github.com/elastic/elasticsearch/issues/88774

**Closed by mark-vieira** 2023-10-04 22:27 UTC
Labels: >enhancement, :Delivery/Build, Team:Delivery
