### ISSUE TITLE
[RestHighLevelClient] Reindex method do not use slices param from ReindexRequest

### ISSUE THREAD

**Issue by RackovychV** [elastic/elasticsearch#45895] opened 2019-08-23 09:36 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 6.6.0

**JVM version** (`java -version`): 11.0.1 using Kotlin

**OS version** (`uname -a` if on a Unix-like system): MacOsX 10.14.6

**Description of the problem including expected versus actual behavior**:
ReindexRequest().slices(3) - slices parameter ignored when reindex method executed. So after execution elasticsearch created only one task without children.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Create index src_index, dst_index. Put some data to src_index.
 2. Call reindex method like
elasticClient.reindex(
        ReindexRequest()
            .setSourceIndices("src_index")
            .setDestIndex("dst_index")
            .setSlices(3),
        RequestOptions.DEFAULT
)
 3. Check that elasticsearch created only one task instead of 4(one parent and three child)

**Comment by hub-cap** [comment] 2019-08-23 18:19
Oh ive got some good news for you!!! This is a dupe of #44045 and will be released whenever 7.4 is released :)

https://github.com/elastic/elasticsearch/commit/fad06ff8e9fadc553d6ae824922b78f6bb19715b

**Closed by hub-cap** 2019-08-23 18:19 UTC
Labels: :Core/Features/Java High Level REST Client
