### ISSUE TITLE
elasticsearch depends on spatial test jar

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#14328] opened 2015-10-28 03:34 UTC
```
[INFO] +- org.apache.lucene:lucene-spatial:jar:5.4.0-snapshot-1708254:compile
[INFO] |  +- org.apache.lucene:lucene-spatial3d:jar:5.4.0-snapshot-1708254:compile
[INFO] |  \- com.spatial4j:spatial4j:jar:tests:0.5:compile
```

and make a .zip distribution and you see this tests jar in lib/

it should not be there...

**Comment by s1monw** [comment] 2015-10-28 08:48
I think this is a lucene issue see the difference between 5.x and 5.3
`http://svn.apache.org/repos/asf/lucene/dev/branches/branch_5x/lucene/spatial/ivy.xml` vs. `http://svn.apache.org/repos/asf/lucene/dev/branches/lucene_solr_5_3/lucene/spatial/ivy.xml` I will open a lucene issue I think it's caused by this revision: http://svn.apache.org/viewvc?view=revision&revision=1704760 / https://issues.apache.org/jira/browse/LUCENE-6810

**Comment by s1monw** [comment] 2015-10-28 08:51
I opened this https://issues.apache.org/jira/browse/LUCENE-6860

**Comment by clintongormley** [comment] 2016-01-29 20:18
Fixed in Lucene 5.4

**Closed by clintongormley** 2016-01-29 20:18 UTC
Labels: bug, build
