### ISSUE TITLE
[CI] PrevalidateShardPathIT testCheckShards failing

### ISSUE THREAD

**Issue by alex-spies** [elastic/elasticsearch#104807] opened 2024-01-26 13:11 UTC
**Build scan:**
https://gradle-enterprise.elastic.co/s/cqthpgkneqdvo/tests/:server:internalClusterTest/org.elasticsearch.cluster.PrevalidateShardPathIT/testCheckShards

**Reproduction line:**
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.cluster.PrevalidateShardPathIT.testCheckShards" -Dtests.seed=4D7C3C7CEAC38430 -Dtests.locale=sv -Dtests.timezone=America/Catamarca -Druntime.java=18
```

**Applicable branches:**
8.12

**Reproduces locally?:**
No

**Failure history:**
[Failure dashboard for `org.elasticsearch.cluster.PrevalidateShardPathIT#testCheckShards`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testCheckShards'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.cluster.PrevalidateShardPathIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.AssertionError: The relocation source node should have removed the shard(s)

  at __randomizedtesting.SeedInfo.seed([4D7C3C7CEAC38430:FC641ADAEFC68041]:0)
  at org.junit.Assert.fail(Assert.java:88)
  at org.junit.Assert.assertTrue(Assert.java:41)
  at org.elasticsearch.cluster.PrevalidateShardPathIT.lambda$testCheckShards$1(PrevalidateShardPathIT.java:80)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1278)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1251)
  at org.elasticsearch.cluster.PrevalidateShardPathIT.testCheckShards(PrevalidateShardPathIT.java:72)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:577)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by arteam** [comment] 2024-02-02 10:20
Lowering the risk since the issue can't be reliably reproduced.

**Comment by arteam** [comment] 2024-02-06 10:24
I believe this issue was supposed to fixed by #92112, this seems to isolated and happened only once over the last month on JDK 18. I'm going to close it since I can't reproduce the test failure on my machine. Feel free to-reopen it again if the issue persists.

**Comment by pxsalehi** [comment] 2024-02-06 10:53
@arteam but that fix is more than a year old and I am not sure if the error is the same. Also there seems to be a newer failure too according to the dashboard (one is on `main`):
<img width="374" alt="image" src="https://github.com/elastic/elasticsearch/assets/3340727/4be43f25-dc83-4bf0-a2a6-1cccceba8b4a">
I suggest keeping this open and investigating it since only in Jan this started failing and has seen two failures in one month.

**Comment by arteam** [comment] 2024-02-06 13:37
@pxsalehi For some reason I didn't see the Jan, 14 failure in the dashboard. I will re-open the issue!

It's the same issue as the fix from #92112 was fixing. The check for the moved shard from the source node `resp2.getNodes().get(0).getShardIds().isEmpty()` fails.

**Comment by DaveCTurner** [comment] 2024-02-29 08:00
I don't think #105747 resolved this, let's keep it open.

**Comment by arteam** [comment] 2024-04-12 13:44
This test hasn't had any failures over the last month, so I'm going to closed it. Feel free to reopen the issue if it starts failing again.

**Comment by ywangd** [comment] 2024-05-07 06:25
Failed again
https://gradle-enterprise.elastic.co/s/4ahgkmv4aevfe/tests/task/:server:internalClusterTest/details/org.elasticsearch.cluster.PrevalidateShardPathIT/testCheckShards?top-execution=1

**Comment by gmarouli** [comment] 2024-05-20 11:52
I got one more: https://gradle-enterprise.elastic.co/s/jr3zrf56bq7mw/tests/task/:server:internalClusterTest/details/org.elasticsearch.cluster.PrevalidateShardPathIT/testCheckShards

**Comment by alex-spies** [comment] 2024-07-01 08:43
And another one: https://gradle-enterprise.elastic.co/s/mdpq7liiqstao/tests/task/:server:internalClusterTest/details/org.elasticsearch.cluster.PrevalidateShardPathIT/testCheckShards?top-execution=1

**Comment by arteam** [comment] 2024-07-09 09:00
The latest change with the increased timeout seems to have improved the test, it hasn't been failing over the the last 4000 executions on CI. I'm going to close the issue, feel free to re-open if it comes back.

**Closed by arteam** 2024-07-09 09:00 UTC
Labels: >test-failure, :Distributed/Allocation, Team:Distributed, low-risk

**Comment by pxsalehi** [comment] 2024-07-17 08:54
@arteam should the extra loggings be removed from the test since this issue is closed?
