### ISSUE TITLE
[CI] debian-10 / packaging-tests-unix failing

### ISSUE THREAD

**Issue by ldematte** [elastic/elasticsearch#107808] opened 2024-04-24 07:41 UTC
### CI Link

https://buildkite.com/elastic/elasticsearch-periodic-packaging/builds/2160

### Repro line

N/A

### Does it reproduce?

Didn't try

### Applicable branches

main, 8.14, 8.13, 7.17

### Failure excerpt

Seems like there is something wrong/no longer supported with debian 10 repositories:
`The repository 'https://deb.debian.org/debian buster-backports Release' no longer has a Release file.`
This is failing consistently and across all branches

**Comment by ldematte** [comment] 2024-04-24 07:42
Failures on other branches:
- https://buildkite.com/elastic/elasticsearch-periodic-packaging/builds/2161
- https://buildkite.com/elastic/elasticsearch-periodic-packaging/builds/2166

**Comment by mark-vieira** [comment] 2024-04-24 17:48
Closing as duplicate of https://github.com/elastic/elasticsearch/issues/107725 this should be fixed soon when our images are rebuilt.

**Closed by mark-vieira** 2024-04-24 17:48 UTC
Labels: blocker, :Delivery/Packaging, >test-failure, Team:Delivery
