### ISSUE TITLE
_update some time i get DocumentAlreadyExistsException

### ISSUE THREAD

**Issue by vedil** [elastic/elasticsearch#11506] opened 2015-06-04 21:51 UTC
I am doing _update on some doc using the url like
http://10.0.0.91:9200/alias_SOME_INDEX/SOME_TYPE/SOME_ID/_update
and my payload is like

{ 
"doc":{"baseName":"Microsoft Office"}, 
"upsert":{"baseName":"Microsoft Office"}
}

on some other thread i am doing PUT for the same document with same id.

i get document already exists]","status":409 
some time it works some time i get this error

so i suspect some thing to do with 2 threads doing similar thing causing this, but an "_update" call giving already exists kind of exception looks strange

**Comment by clintongormley** [comment] 2015-06-05 08:53
I haven't tried to replicate this, but it sounds like it is trying to do an upsert, and not handling the conflict exception correctly.

**Comment by vedil** [comment] 2015-06-12 14:43
i have made a pull request for fixing this, do i have to do any thing more? is the pull request fine?

**Comment by clintongormley** [comment] 2015-06-12 17:13
thanks for the pr @vedil - i've marked it for review. somebody should get to it shortly

**Comment by vedil** [comment] 2015-07-09 01:11
messed up previous pull request, so created another one https://github.com/elastic/elasticsearch/pull/12137

**Comment by jasontedor** [comment] 2015-07-10 02:13
Can you provide a test case that replicates the `DocumentAlreadyExistsException`?

I agree that there is clearly potential for a race condition here and think that it's important that we get to the bottom of it. A test case that reproduces the exception would be helpful.

**Comment by vedil** [comment] 2015-07-14 18:28
tried creating a test case after removing my changes, and modifying my test a bit
 @Test
    public void testIndexNUpdateUpsert() {
            //update action goes to the primary, index op gets executed locally, then replicated
            String[] updateShardActions = new String[]{UpdateAction.NAME, IndexAction.NAME + "[r]"};
            interceptTransportActions(updateShardActions);

            String indexOrAlias = randomIndexOrAlias();
            
            String[] indexShardActions = new String[]{IndexAction.NAME, IndexAction.NAME + "[r]"};
            interceptTransportActions(indexShardActions);
            
            IndexRequest indexRequest = new IndexRequest(randomIndexOrAlias(), "type", "id").source("field", "value");
            IndexResponse indexResponse = internalCluster().clientNodeClient().index(indexRequest).actionGet();
            clearInterceptedActions();
            assertSameIndices(indexRequest, indexShardActions);
            assertThat(1L, equalTo(indexResponse.getVersion()));
            
            indexRequest = new IndexRequest(randomIndexOrAlias(), "type", "id").source("field", "value");
            indexResponse = internalCluster().clientNodeClient().index(indexRequest).actionGet();
            clearInterceptedActions();
            //assertSameIndices(indexRequest, indexShardActions);
            assertThat(2L, equalTo(indexResponse.getVersion()));
            
            UpdateRequest updateRequest = new UpdateRequest(indexOrAlias, "type", "id").upsert("field2", "value2").doc("field1", "value1");
            UpdateResponse updateResponse = internalCluster().clientNodeClient().update(updateRequest).actionGet();
            assertThat( updateResponse.getVersion(), greaterThan(indexResponse.getVersion()));

            clearInterceptedActions();
            System.out.println("updateRequest "+updateRequest +" updateShardActions = "+updateShardActions );
            assertSameIndicesOptionalRequests(updateRequest, updateShardActions);
    }

now this is failing always by saying 1 is < 2, is my assert supposed to succeed?
i am doing index, index, update and expecting a version > 2

**Comment by vedil** [comment] 2015-07-14 18:29
i am running test case using these vm arguments in eclipse
-ea -Dtests.seed=806B4E52F9B20C5B -Dtests.assertion.disabled=false -Dtests.heap.size=512m -Dtests.locale=no_NO_NY -Dtests.timezone=America/Miquelon -Des.logger.level=DEBUG

**Comment by vedil** [comment] 2015-07-24 16:56
@Test
    	public void testIndexNUpdateUpsert() {
            //update action goes to the primary, index op gets executed locally, then replicated
            //String[] updateShardActions = new String[]{UpdateAction.NAME, IndexAction.NAME + "[r]"};
            //interceptTransportActions(updateShardActions);

            final  String indexOrAlias = randomIndexOrAlias();
            final int NUMBER_OF_THREADS = 10;
            final int UPDATE_EVERY = 2;
            final CountDownLatch latch = new CountDownLatch(NUMBER_OF_THREADS);
            Thread[] threads = new Thread[NUMBER_OF_THREADS];
            for (int i = 0; i < threads.length; i++) {
                threads[i] = new Thread() {
                    @Override
                    public void run() {
                        try {
                            for (long i = 0; i < NUMBER_OF_THREADS; i++) {
                                if ((i % UPDATE_EVERY) == 0) {
                                    UpdateRequest updateRequest = new UpdateRequest(indexOrAlias, "type", "id").upsert("field2", "value2").doc("field1", "value1");
                                    UpdateResponse updateResponse = internalCluster().clientNodeClient().update(updateRequest).actionGet();
                                    System.out.println("update response = "+updateResponse);
                                } else {
                                    IndexRequest indexRequest = new IndexRequest(indexOrAlias, "type", "id").source("field", "value");
                                    IndexResponse indexResponse =  internalCluster().clientNodeClient().index(indexRequest).actionGet();
                                    System.out.println("index response = "+indexResponse);
                                }
                            }
                        } finally {
                            latch.countDown();
                        }
                    }
                };
            }

            for (Thread thread : threads) {
                thread.start();
            }
           
            try {
                latch.await();
            } catch (InterruptedException e) {
                e.printStackTrace();
                throw new RuntimeException();
            }
	}

using this test i am able to reproduce the "document already exists" also i see some exceptions whose message is like "version conflict, current [3], provided [1]" also

**Comment by brwe** [comment] 2015-07-28 13:21
I do not think this is an actual bug.

@vedil  I believe the unit test you put [here](https://github.com/elastic/elasticsearch/issues/11506#issuecomment-121331165) fails because you use a new `randomIndexOrAlias()` for each request and so the requests might not all got to the same index. I you use the same index each time the test will pass.

I agree that the `DocumentAlreadyExistsException` seems weird for the integration test but this is also expected I think. An update first retrieves the document via `get` and then issues an `index` request with the updated source. If a write sneaked in between `get` and issuing the `index` request we throw a `VersionConflictException` in case the document already existed before the update. However, in case the document did not exist when the `get` was executed we check that the document does still not exist when the `index` request is sent. If it does, we throw a `DocumentAlreadyExistsException`.
To circumvent this, you need to set the [retry on conflict parameter](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html#_parameters_3) to a higher value.
Let me know if my explanation makes sense.

We could potentially throw a `VersionConfictException` instead of a `DocumentAlreadyExistsException` to have consistent exceptions for updates or have a dedicated `UpdateFailedException` that explains what happened  or just document this better.

**Comment by vedil** [comment] 2015-07-28 14:13
regarding randomIndexOrAlias, i am calling it once and using it in all requests. so within a test it will use same index.
your other explanation makes sense, i feel VersionConfictException makes more sense.

**Comment by brwe** [comment] 2015-10-06 19:18
After https://github.com/elastic/elasticsearch/pull/13955 is in we will get `VersionConfictException`.

**Comment by brwe** [comment] 2015-10-07 15:16
#13955 was merged, closing

**Closed by brwe** 2015-10-07 15:16 UTC
Labels: :CRUD, adoptme, bug

**Comment by xing00lian** [comment] 2018-03-21 12:42
赞
