### ISSUE TITLE
Ingest parses index requests twice when there is a final pipeline

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#81244] opened 2021-12-02 09:20 UTC
I was looking at a flame graph of an ingestion workload with @dliappis, and it looks like we parse the JSON representation of the index request twice when a document has both a pipeline and a final pipeline.

It's hard to know how much we would save on this benchmark since not all data streams in this benchmark had both a pipeline and a final pipeline, but the cost of parsing index request into maps of maps via IngestService represented 4.06% of overall CPU time according to the flame graph, so this might not be negligible.

**Comment by masseyke** [comment] 2022-04-26 22:22
I assume you're talking about the call to IndexRequest::sourceAsMap happening once per pipeline? I've got a quick change in a branch where I cache that (https://github.com/elastic/elasticsearch/compare/master...masseyke:fix/not-parsing-index-request-twice?expand=1), but I haven't set up a performance test to prove that that does any good yet. I'll try to do that at some point soon.

**Comment by DJRickyB** [comment] 2022-05-03 14:15
In #85926 I attempted and failed to run the self-reference check once per document instead of once per pipeline. That enhancement should be coupled with this one in case it gets implemented.

*Also* as far as I can tell, the reason for moving back to the IndexRequest from the IngestDocument seems to be to possibly pivot to other pipelines in case the target index changes. Any change for this issue should ensure we have sufficient coverage for the changing-target-index case

**Comment by joegallo** [comment] 2022-11-18 15:27
![Screen Shot 2022-11-18 at 10 19 51 AM](https://user-images.githubusercontent.com/187034/202740062-8b5668a4-f28e-4f64-aba5-323c8aea2a25.png)

Confirmed for sure that the original description is correct, and that this is a significant time sink in terms of the total work we're doing during ingest pipeline processing. Without a big change, I can't imagine how we could get rid of the initial parse and final generate, but it does seem suboptimal to have the inner generate followed almost immediately by a subsequent parse.

**Comment by joegallo** [comment] 2022-11-18 22:28
Actually, there's another small cost that's repeated -- we build an IngestDocument from the parsed bytes twice and a very good fix for this ticket would remove that, too. (You can see a little repeated pattern just to the right of the two 'parse' rectangles, I'm thinking it would drop out along with the center generate/parse anti-pair.)

**Comment by joegallo** [comment] 2023-01-25 20:37
<img width="1792" alt="Screen Shot 2023-01-25 at 3 29 39 PM" src="https://user-images.githubusercontent.com/187034/214683083-9537b47a-971a-4a2a-afec-1e351ab6c003.png">

Here's an updated flamegraph, fundamentally we're still in the same situation (note: PR coming, we soon won't be). As before, the inefficiency here is that the center two highlighted operations are a very expensive generate/parse pair that can be optimized out.

#92995 and #93213 changed the overall shape of the flamegraph that we're getting here, so I thought an updated flamegraph was called for.

**Closed** 2023-01-30 16:48 UTC
Labels: >bug, :Data Management/Ingest Node, :Performance, Team:Data Management, Team:Performance

**Comment by joegallo** [comment] 2023-01-30 16:49
Here's an updated flame graph from https://github.com/elastic/elasticsearch/pull/93329, where there's now a single parse/generate cycle for all the pipelines, rather than for each pipeline:

![](https://user-images.githubusercontent.com/187034/215160676-61133594-04b9-4570-b2cc-3e9025436797.png)
