### ISSUE TITLE
TTL recalculated on upsert

### ISSUE THREAD

**Issue by ronlepper** [elastic/elasticsearch#11882] opened 2015-06-25 21:21 UTC
We are currently running into an issue with ttl and upserts (using doc_as_upsert).  It looks like the ttl is being recalulated when we perform an upsert that does not update _ttl or _timestamp.

Here is the command to create the mapping we are using to test this:

    curl -XPUT localhost:9200/timetolive -d'{
	"mappings": {
		"test": {
			"_ttl": {
				"enabled" : true
			},
			"_timestamp": {
				"enabled" : true, 
				"format":"basic_date_time",
				"path":"post_date"
			},
			
			"properties": {
				"post_date": {
					"type": "date", 
					"format":"basic_date_time"
				},
				"text": {
					"type": "string"
				}
			}
		}
	}
    }'

Then insert a document with a ttl and a timestamp:

    curl -XPUT localhost:9200/timetolive/test/1 -d'{
        "text" : "Initial test", 
        "post_date" : "20150625T130000.000000-0700", 
        "_ttl": "20s"
    }'

Next, update only the text field on the document: 

    curl -XPOST localhost:9200/timetolive/test/1/_update -d'{
        "doc" : {
            "text" : "Upsert text"
	    },
        "doc_as_upsert" : true 
    }'

After the upsert, the ttl has now been extended.  It looks like is taking the calculated time to live (_ttl + timestamp - now) from the initial request and adding it to the stored timestamp when the upsert comes in. 

We are running ElasticSearch version 1.5.2.

**Comment by pickypg** [comment] 2015-06-27 21:14
The problem is that the partial update will fetch the current document, which contains `"_ttl" : "20s"`, and update just the `text` field. Once done, it will reindex the _whole_ document and the `"_ttl" : "20s"` ends up being reset as a result.

This is why the TTL ends up restarting and, without special-casing TTL in the partial update process, which may be possible, there is not a very good solution to it.

Regardless, I would encourage you to look at using time-based indices rather than TTL-based documents. It's _much_ easier to delete an entire index than it is to have the automatic background query deleting documents, which itself creates load on your index/node/cluster. Naturally this isn't really doable with a `20s` TTL, but hopefully that was just an example value for the demonstration of the issue.

**Comment by ronlepper** [comment] 2015-07-06 19:22
Unfortunately, the time-based indices won't work for our use case.  The expiration date for each document has the potential to change so we'd need to delete from one index and insert into another index.  Since the documents being indexed are coming in through logstash, we'd rather use the update api and update the expiration date for the document based off the id.

It seems like most of our use cases can be handled with an update script to set the ttl properly, except when we want to set a ttl with an expiration to having no expiration.  If we set the ttl value to null, it will always use the existing calculated expiration time.  From the org.elasticsearch.action.update.UpdateHelper.java class, it looks like whenever ttl is null, it will attempt to pull the existing ttl expiration. Ideally, I would need some constant that could be used to reset a document to an infinite expiration.  

    if (ttl == null) {
        ttl = getResult.getFields().containsKey(TTLFieldMapper.NAME) ?    (Long)getResult.field(TTLFieldMapper.NAME).getValue() : null;
        if (ttl != null) {
                ttl = ttl - TimeValue.nsecToMSec(System.nanoTime() - getDateNS); // It is an approximation of exact TTL value, could be improved
         }
    }

**Comment by pickypg** [comment] 2015-07-06 20:48
Hi @ronlepper, that's fine and often times unavoidable. However, I'm not convinced that the approach that you're suggesting is superior to the default reset option given the possibility (or likelihood?) of update-after-dead actions, which is particularly expensive alongside TTL functionality.

Ignoring that behavior you _can_ use a Groovy script to imitate the functionality that you are looking for as part of an update (don't use dynamic scripting, but this is the example script to maintain it):

```json
{
  "script" : "ctx._source.text = text; ctx._source._ttl = ctx._ttl",
  "params" : {
    "text" : "Upsert text"
  },
  "upsert" : {
    "text" : "Upsert text",
    "_ttl" : "20s"
  }
}
```

This uses the "live" TTL value and sets it over the current source value's, which means that it maintains the current TTL rather than resetting it. Note: If you use a script, then [you cannot use the `doc` (use script `params`)](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html#_updates_with_a_partial_document).

I do wonder if another flag should be added for updates that allow automatic continuation of the document's TTL (effectively doing the `ctx._source._ttl = ctx._ttl` step of the above script), but I definitely don't think that it should be default.

**Comment by ronlepper** [comment] 2015-07-06 21:21
Hi @pickypg, thanks for the feedback.  I've implemented a similar script to the one you mention above and had some luck with it for most of my cases. The one case that I can't seem to get working though is removing the expiration.  For example, if I had a document that has a ttl value set and  I want to update the document to have no ttl based expiration.  Setting ctx._ttl to null or ctx._source._ttl to null in the script will just result in the UpdateHelper.java class pulling the current calulated ttl value.  Any suggestions for that case?

**Comment by pickypg** [comment] 2015-07-06 23:32
@ronlepper The only way to "unset" the `_ttl` is to reset or to completely replace (reindex) the document. You _can_ set it to `null`, but we're not checking for it, which I do consider to be a bug.

```json
{
  "script" : "ctx_source._ttl = null"
}
```

This does change the `_ttl` to `null`, but the code that you spotted assumes that `null` means that it's not set rather than that it's being _unset_. We need to check for the key if it's `null`, then remove it in that case.

**Comment by nside** [comment] 2016-04-29 21:38
I'm hitting a similar bug. Basically the _ttl doesn't get reset in the bulk update but does in the atomic one.
Here's a script to reproduce

```
import requests, time

def assert_success(r):
  assert r.json()['acknowledged']

INDEX = 'http://localhost:9200/test_ttl'
print 'delete index'
requests.delete(INDEX)
print 'create index'
r = requests.put(INDEX, data="""{
  "mappings": {
    "my_type": {
      "_ttl": {
        "enabled": true,
        "default": "5m"
      }
    }
  }
}""")

assert_success(r)

print 'read index'
assert requests.get(INDEX).json()['test_ttl']['mappings']['my_type']['_ttl']['default'] == 300000

print 'insert record'
r = requests.put(INDEX + '/my_type/1', data='{"hello": 1}')

print 'read record'
ttl1 = requests.get(INDEX + '/my_type/1').json()['_ttl']

time.sleep(1)
print 'read record'
ttl2 = requests.get(INDEX + '/my_type/1').json()['_ttl']

assert ttl2 < ttl1

print 'update record by id'
r = requests.put(INDEX + '/my_type/1', data='{"hello": 2}')

ttl3 = requests.get(INDEX + '/my_type/1').json()['_ttl']

assert ttl3 > ttl2, "TTL wasn't reset"

print 'update record bulk'
r = requests.put(INDEX + '/my_type/1/_bulk', data="""{ "update" : {"_id" : "1"}}
{"doc": {"hello" : 3} } }""")
print r.content

ttl4 = requests.get(INDEX + '/my_type/1').json()['_ttl']
assert ttl4 > ttl3, "TTL wasn't reset %f %f" % (ttl4, ttl3)
```

**Comment by clintongormley** [comment] 2016-05-12 12:55
Closing in favour of #18280

**Closed by clintongormley** 2016-05-12 12:55 UTC
Labels: :Mapping, bug, discuss
