### ISSUE TITLE
Test failure: org.elasticsearch.grok.GrokTests.testExponentialExpressions

### ISSUE THREAD

**Issue by jakelandis** [elastic/elasticsearch#58946] opened 2020-07-02 17:35 UTC
Given the rarity of this failure I am not muting. However, if this increases in occurrences this test should be muted. 

**Build scan**:

https://gradle-enterprise.elastic.co/s/iak3abjnc4huu

**Repro line**:
```
REPRODUCE WITH: ./gradlew ':libs:elasticsearch-grok:test' --tests "org.elasticsearch.grok.GrokTests.testExponentialExpressions" \
  -Dtests.seed=2012EF738111106E \
  -Dtests.security.manager=true \
  -Dtests.locale=es-VE \
  -Dtests.timezone=Africa/Niamey \
  -Druntime.java=11
```
**Reproduces locally?**:
No. Ran a few thousand iterations (without the extra -D arguments ) and they all passed.

**Applicable branches**:

This failure is on master, but history shows it is not specific to master. 

**Failure history**:
https://gradle-enterprise.elastic.co/scans/tests?list.size=50&list.sortColumn=startTime&list.sortOrder=desc&search.buildToolType=gradle&search.buildToolType=maven&search.relativeStartTime=P28D&search.timeZoneId=America/Chicago&tests.container=org.elasticsearch.grok.GrokTests&tests.sortField=FAILED&tests.test=testExponentialExpressions&tests.unstableOnly=true

This is the only one in past 28 day.

However, searching my email archives i see ~ 15 failures in the past 1.5 years across all branches. So this is pretty rare, but not also not likely caused by cosmic rays. I suspect that there is a subtle race condition in the test itself. 

**Failure excerpt**:

```
org.elasticsearch.grok.GrokTests > classMethod FAILED	
    java.lang.Exception: Suite timeout exceeded (>= 1200000 msec).	
        at __randomizedtesting.SeedInfo.seed([2012EF738111106E]:0)	
```

and
```
2> WARNING: Suite execution timed out: org.elasticsearch.grok.GrokTests 
```

I believe that for this particular test, it can occur if the Watch dog thread does not kill the Grok match as it should.

**Comment by dakrone** [comment] 2021-03-03 22:51
Seeing as how we haven't had more occurrences of this since last July, I'm going to close this for now, we can reopen if needed.

**Comment by DaveCTurner** [comment] 2021-09-07 11:51
I had a failure of this in a PR build: https://gradle-enterprise.elastic.co/s/ff62t5dy33ux2/console-log?task=:libs:elasticsearch-grok:test

**Comment by fcofdez** [comment] 2023-05-12 15:07
Looks like this is happening again https://gradle-enterprise.elastic.co/s/biozovvlmi3dk

**Comment by joegallo** [comment] 2023-05-18 18:54
```
"Thread-11715" ID=11760 TIMED_WAITING
	at java.base@20.0.1/java.lang.Thread.sleep0(Native Method)
	at java.base@20.0.1/java.lang.Thread.sleep(Thread.java:484)
	at app//org.elasticsearch.grok.GrokTests.lambda$testExponentialExpressions$2(GrokTests.java:776)
	at app//org.elasticsearch.grok.GrokTests$$Lambda$523/0x000000080132fd40.accept(Unknown Source)
	at app//org.elasticsearch.grok.MatcherWatchdog$Default.interruptLongRunningExecutions(MatcherWatchdog.java:142)
	at app//org.elasticsearch.grok.MatcherWatchdog$Default$$Lambda$528/0x000000080133f618.run(Unknown Source)
	at app//org.elasticsearch.grok.GrokTests.lambda$testExponentialExpressions$1(GrokTests.java:783)
	at app//org.elasticsearch.grok.GrokTests$$Lambda$527/0x000000080133f400.run(Unknown Source)
	at java.base@20.0.1/java.lang.Thread.runWith(Thread.java:1636)
	at java.base@20.0.1/java.lang.Thread.run(Thread.java:1623)
```

It's interesting to me that in the failure I don't see a thread like the above (in the output of the threads that are running when the timeout is reached). That makes me think that for some reason the watchdog didn't execute at all.

**Comment by joegallo** [comment] 2023-11-02 01:00
Still hoping for a new reproduction now that https://github.com/elastic/elasticsearch/pull/96230 has been merged. No luck yet.

**Comment by mark-vieira** [comment] 2023-11-18 17:41
@joegallo got another one for you: https://gradle-enterprise.elastic.co/s/w6ne6rvsehkpe/tests/:libs:elasticsearch-grok:test/org.elasticsearch.grok.GrokTests/testExponentialExpressions

**Comment by joegallo** [comment] 2023-11-20 18:48
Ahhhh! How exciting! Thanks, @mark-vieira!

**Closed** 2024-11-05 21:57 UTC
Labels: >test-failure, :Data Management/Ingest Node, Team:Data Management, low-risk
