### ISSUE TITLE
SQL: GROUPing BY PI() arithmetic operation results in exception

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#41244] opened 2019-04-16 08:37 UTC
```
sql> SELECT PI() + num0 AS x FROM "calcs" GROUP BY 1;
Server error [Server sent bad type [folding_exception]. Original type was [line 1:8: Cannot find grouping for 'PI() + num0']. [FoldingException[line 1:8: Cannot find grouping for 'PI() + num0']
        at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldAggregate.rule(QueryFolder.java:319)
        at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldAggregate.rule(QueryFolder.java:203)
        at org.elasticsearch.xpack.sql.tree.Node.lambda$transformUp$11(Node.java:196)
        at org.elasticsearch.xpack.sql.tree.Node.transformUp(Node.java:190)
        at org.elasticsearch.xpack.sql.tree.Node.transformUp(Node.java:196)
        at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldingRule.apply(QueryFolder.java:586)
        at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldingRule.apply(QueryFolder.java:582)
```

**Comment by matriv** [comment] 2019-05-08 15:02
This is another bug related to the ExpressionIds similar to #33361 and #40240

The plan looks like:
```
AggregateExec[[Add[PI()=3.141592653589793,emp_no{f}#16]#30],[Add[PI()=3.141592653589793,emp_no{f}#16]#32 AS x#4]]
```

so one id is `30` and the other is `32` so it's not found in the map of the `groupingContext`.

**Comment by matriv** [comment] 2019-05-09 15:30
Closing as a duplicate of #36074

**Closed by matriv** 2019-05-09 15:30 UTC
Labels: :Search/SQL, >bug
