### ISSUE TITLE
NodeDisconnectedException in CCR stats doc tests

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#35593] opened 2018-11-15 14:20 UTC
The following run failed:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=opensuse/60/console

The failure was that `number_of_failed_remote_cluster_state_requests` yielded 1 but was expected to yield 0:

```
  1> [2018-11-15T05:48:22,692][INFO ][o.e.s.DocsClientYamlTestSuiteIT] [test] Stash dump on test failure [{
  1>   "stash" : {
  1>     "body" : {
  1>       "auto_follow_stats" : {
  1>         "number_of_failed_follow_indices" : 0,
  1>         "number_of_failed_remote_cluster_state_requests" : 1,
  1>         "number_of_successful_follow_indices" : 0,
  1>         "recent_auto_follow_errors" : [
  1>           {
  1>             "leader_index" : "my_auto_follow_pattern",
  1>             "auto_follow_exception" : {
  1>               "type" : "exception",
  1>               "reason" : "ElasticsearchStatusException[can not fetch remote cluster state as the license state of the remote cluster [remote_cluster] could not be determined]; nested: ElasticsearchException[could not determine the license type for cluster [remote_cluster]]; nested: NodeDisconnectedException[[node-0][127.0.0.1:43215][cluster:monitor/xpack/info] disconnected];",
  1>               "caused_by" : {
  1>                 "type" : "status_exception",
  1>                 "reason" : "can not fetch remote cluster state as the license state of the remote cluster [remote_cluster] could not be determined",
  1>                 "caused_by" : {
  1>                   "type" : "exception",
  1>                   "reason" : "could not determine the license type for cluster [remote_cluster]",
  1>                   "caused_by" : {
  1>                     "type" : "node_disconnected_exception",
  1>                     "reason" : "[node-0][127.0.0.1:43215][cluster:monitor/xpack/info] disconnected"
  1>                   }
  1>                 }
  1>               }
  1>             }
  1>           }
  1>         ]
  1>       },
  1>       "follow_stats" : {
  1>         "indices" : [
  1>           {
  1>             "index" : "follower_index",
  1>             "shards" : [
  1>               {
  1>                 "remote_cluster" : "remote_cluster",
  1>                 "leader_index" : "leader_index",
  1>                 "follower_index" : "follower_index",
  1>                 "shard_id" : 0,
  1>                 "leader_global_checkpoint" : 0,
  1>                 "leader_max_seq_no" : 0,
  1>                 "follower_global_checkpoint" : 0,
  1>                 "follower_max_seq_no" : 0,
  1>                 "last_requested_seq_no" : 0,
  1>                 "outstanding_read_requests" : 0,
  1>                 "outstanding_write_requests" : 0,
  1>                 "write_buffer_operation_count" : 0,
  1>                 "write_buffer_size_in_bytes" : 0,
  1>                 "follower_mapping_version" : 0,
  1>                 "follower_settings_version" : 0,
  1>                 "total_read_time_millis" : 0,
  1>                 "total_read_remote_exec_time_millis" : 0,
  1>                 "successful_read_requests" : 0,
  1>                 "failed_read_requests" : 0,
  1>                 "operations_read" : 0,
  1>                 "bytes_read" : 0,
  1>                 "total_write_time_millis" : 0,
  1>                 "successful_write_requests" : 0,
  1>                 "failed_write_requests" : 0,
  1>                 "operations_written" : 0,
  1>                 "read_exceptions" : [ ],
  1>                 "time_since_last_read_millis" : -1
  1>               }
  1>             ]
  1>           }
  1>         ]
  1>       }
  1>     }
  1>   }
  1> }]
```

```
  2> REPRODUCE WITH: ./gradlew :docs:integTestRunner -Dtests.seed=EC91D2DAA4CFDBD5 -Dtests.class=org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT -Dtests.method="test {yaml=reference/ccr/apis/get-ccr-stats/line_88}" -Dtests.security.manager=true -Dtests.locale=en-IE -Dtests.timezone=CST6CDT -Dcompiler.java=11 -Druntime.java=8
```

What puzzles me is that `127.0.0.1:43215` seems to be the local node, and we're running CCR within a single cluster:

```
[2018-11-15T11:34:40,065][INFO ][o.e.t.TransportService   ] [node-0] publish_address {127.0.0.1:43215}, bound_addresses {[::1]:33485}, {127.0.0.1:43215}
...
[2018-11-15T11:47:47,110][WARN ][o.e.x.c.a.AutoFollowCoordinator] [node-0] failure occurred while fetching cluster state for auto follow pattern [my_auto_follow_pattern]
org.elasticsearch.ElasticsearchStatusException: can not fetch remote cluster state as the license state of the remote cluster [remote_cluster] could not be determined
	at org.elasticsearch.xpack.ccr.CcrLicenseChecker.clusterStateUnknownRemoteLicense(CcrLicenseChecker.java:425) ~[x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
	at org.elasticsearch.xpack.ccr.CcrLicenseChecker.lambda$checkRemoteClusterLicenseAndFetchClusterState$5(CcrLicenseChecker.java:171) ~[x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
	at org.elasticsearch.xpack.ccr.CcrLicenseChecker$1.onFailure(CcrLicenseChecker.java:217) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
	at org.elasticsearch.license.RemoteClusterLicenseChecker$1.onFailure(RemoteClusterLicenseChecker.java:180) [x-pack-core-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
	at org.elasticsearch.action.support.ContextPreservingActionListener.onFailure(ContextPreservingActionListener.java:50) [elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:53) [elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1127) [elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
	at org.elasticsearch.transport.TransportService.lambda$onConnectionClosed$8(TransportService.java:982) [elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:627) [elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.elasticsearch.ElasticsearchException: could not determine the license type for cluster [remote_cluster]
	... 9 more
Caused by: org.elasticsearch.transport.NodeDisconnectedException: [node-0][127.0.0.1:43215][cluster:monitor/xpack/info] disconnected
```

Not sure how we get a `NodeDisconnctedException` in this situation.

**Comment by martijnvg** [comment] 2018-11-15 15:23
Duplicate of #35496

**Closed by martijnvg** 2018-11-15 15:23 UTC
Labels: :Distributed/CCR, >test-failure
