### ISSUE TITLE
Completion Suggester does not allow source filtering

### ISSUE THREAD

**Issue by bharvidixit** [elastic/elasticsearch#20816] opened 2016-10-08 15:58 UTC
**Elasticsearch version**: 5.0.0-beta1

**Plugins installed**: []

**JVM version**: 1.8.0_72

**OS version**: Ubuntu 15

**Description of the problem including expected versus actual behavior**:
As described here https://www.elastic.co/guide/en/elasticsearch/reference/5.0/search-suggesters-completion.html#querying  one can use source filtering while returning suggestions under _suggest endpoint. However, using the source filtering returns following error to me.
![image](https://cloud.githubusercontent.com/assets/10341430/19214302/2c4a8924-8d9d-11e6-88af-ba838a879c97.png)

**Steps to reproduce**:
1. Follow examples mentioned on the above mentioned url for creating index with mapping and indexing document.
2. Use following query for the suggestion
curl -XPOST "http://localhost:9200/music/_suggest" -d'
{
    "_source": "completion.*",
    "song-suggest" : {
        "prefix" : "nir",
        "completion" : {
            "field" : "suggest"
        }
    }
}'

**Looking at the documentation, i also wonder why to use completion.\* as my source filtered field. Shouldn't it be the name of the field which exist in the document??**

_Surprisingly there is no exception thrown in Elasticsearch log file._

**Comment by areek** [comment] 2016-10-21 21:02
@bharvidixit please use `suggest` from the `_search` endpoint instead of `_suggest` endpoint. The `_suggest` endpoint doesn't support source filtering atm. I will open up a PR to document this or deprecate the `_suggest` endpoint in favour of using suggest via the `_search` endpoint

**Comment by clintongormley** [comment] 2016-11-05 17:08
Closing as duplicate of https://github.com/elastic/elasticsearch/issues/20482

**Closed by clintongormley** 2016-11-05 17:08 UTC
Labels: :Suggesters, bug, Pioneer Program
