### ISSUE TITLE
ElasticSearch discover all cores in a kubernetes pod instead the cores given in a statefulset

### ISSUE THREAD

**Issue by Dlorite** [elastic/elasticsearch#33055] opened 2018-08-22 10:54 UTC
Hi, we have a cluster of elasticsearch v.5.2.2. in kubernetes with 20 workers and 3 electable masters dedicated. This cluster have machines with 8 cores but in our statefullset we have set the workers with only 2 cpu core in guarantee mode. The problem comes when the workers think they have 8 cores and the bulk thread pool has a size of 8 too. Then all workers are working more than they can ingest and suddenly they one of them start to reject all petitions and the cluster stop of index more documents, this problem is solved restarting the pods, but eventually the problem comes again. We can escalate the cluster with more workers and then the problem seems is solved until the number of documents is increased.
I think that will be solved if elasticearch would discover the cores available correctly in a pod in kubernetes.

**Comment by gwbrown** [comment] 2020-12-14 23:53
I'm tagging this as `needs:reproduction` as we have made some changes since 5.2.2 to how Elasticsearch detects the number of cores in the context of containers that may have fixed this issue, but I don't have a Kubernetes cluster handy to test.

**Comment by mosche** [comment] 2024-11-08 14:32
I'm going to close this issue for now as it is very likely outdated and fixed in current versions of Elasticsearch. Feel free to reopen if you 
are still experiencing the issue after moving to a more recent version of Elasticsearch.

**Closed by mosche** 2024-11-08 14:32 UTC
Labels: :Core/Infra/Core, Team:Core/Infra, needs:reproduction
