### ISSUE TITLE
Performance of Unified Highlighter is ~5 times worse than Postings highlighter in Elasticsearch 5.5.0

### ISSUE THREAD

**Issue by ShilpiRachna** [elastic/elasticsearch#25786] opened 2017-07-19 08:28 UTC
Elasticsearch version: 5.5.0 
JVM version: 1.8.0_72 
OS version: Windows 10

Description of the problem including expected versus actual behavior:
--
We indexed around 1 million documents in a single shard, zero replica index with _source enabled. Each document has around 40 to 50 fields. There is only one mapping used for all documents and it has around 500 fields. We highlight only 12 fields.

I had filed an issue https://github.com/elastic/elasticsearch/issues/25699 for the performance of unified highlighter as compared to postings highlighter for multi match queries.

Commit https://github.com/elastic/elasticsearch/commit/41ea8fdcec064b5920a1ae392974fa6c51e9aef6 was done as part of the fix. I applied the commit on v5.5.0 branch (manually) and tried our scenario. The performance has improved significantly but it is still 5-6 times slower than postings highlighter for majority of the queries.

Comparison of performance for Multi-match query (in ms):
--
50th Percentile for our queries:
Postings: 20
Unified: 115

80th percentile for our queries:
Postings: 104
Unified: 310

Have attached the mapping and sample document:
https://github.com/elastic/elasticsearch/files/1147583/SampleDocument.txt
https://github.com/elastic/elasticsearch/files/1147584/Mapping.txt

Thanks!

**Comment by jimczi** [comment] 2017-07-20 11:01
Are you using `type:phrase` or `type:phrase_prefix` in your `multi_match`query ? Can you share some queries and give some insights regarding your performance tests (number of queries, methodology, ...).

**Comment by ShilpiRachna** [comment] 2017-07-21 06:48
Yes, we are using type:phrase in our query (but not type:phrase_prefix).

Here's a sample query:
[SampleQuery.txt](https://github.com/elastic/elasticsearch/files/1164676/SampleQuery.txt)

Performance tests were done with ~1500 different queries after indexing 1 million documents in single shard, zero replica index. We logged query performance for each query and compared the 50th, 80, 95th percentile numbers for ES 5.5 against ES 2.4.1

Thanks!

**Comment by jimczi** [comment] 2017-07-24 18:17
Unlike the `unified` highlighter, the `postings` highlighter ignores phrase query and only extract the terms regardless of their position.
That could explain the performance hit when you use the `unified` highlighter. There are options in the `unified` to disable phrase query highlighting but there are not settable in es. Though you can still disable phrase query by using a different `highlight_query`.
Regarding the performance tests, you should use the same version to compare highlighting perf otherwise you're just comparing two major versions with a lot more differences than just highlighting.
I hope you don't mind but I'll close this issue as it is not a bug. I really appreciate that you test the new `unified` highlighter but we should continue this discussion in the forum instead (https://discuss.elastic.co/c/elasticsearch) and if your perf tests find real bugs or regressions we can create verified issues here.

**Closed by jimczi** 2017-07-24 18:17 UTC
Labels: :Highlighting

**Comment by DivyaMalini** [comment] 2018-03-20 10:02
@jimczi , as per our discussion at ElasticOn18, I am using this thread to continue investigation on why move to unified highlighter, is contributing to _perf issues at high scale_ that we are dealing with. 

The thread already has info on the mapping etc. Do let us know if you need any other data to help us understand the degradation in perf.

**Comment by jimczi** [comment] 2018-03-22 21:56
@DivyaMalini I am not surprised that the `unified` is slower than the `postings` on a `match_phrase` query. This is expected since the `postings` highlighter ignores phrase queries,  this highlighter as meant to perform simple query terms highlighting, regardless of their positions. Did you try to override the `highlight_query` to change the `match_phrase` into a simple `match` query ?
That's what the `postings` highlighter does under the hood so the comparison would have more sense and you should be able to compare the results more easily (they should highlight the same things).
A phrase query is more costly than a disjunction of terms so I'd expect more similar performance if you change the `highlight_query` in the `unified` highlighter tests.

**Comment by DivyaMalini** [comment] 2018-03-29 15:00
Thanks @jimczi . We will try to focus on using  _match_ to get better comparisons of perf state.

**Comment by ShilpiRachna** [comment] 2018-06-19 11:05
As suggested by you, we tried highlight_query with _match_ for all fields that are included for highlighting . **The query performance is much better even for single term queries.**

Would like to understand why is highlight_query so much faster that search query. Our search query has 3 times the number of fields as compared to highlighted fields. Does that contribute to performance degradation with highlighting? 

Also, are there any recommendations regarding the usage of  _highlight_query_ .

Thanks!
Shilpi
