### ISSUE TITLE
Nodes stats API CPU usage value is -1

### ISSUE THREAD

**Issue by yskim8830** [elastic/elasticsearch#91940] opened 2022-11-25 04:16 UTC
### Elasticsearch Version

7.10.2-oss

### Java Version

15.0.1

### OS Version

Ubuntu 22.04.1 LTS

### Problem Description

Hello, I have a question.
I have installed elasticsearch on azure. OS is Ubuntu.
And look up the cpu usage.
I ran '_cat/nodes?format=json' , and the cpu value is -1.
can not understand.
I browsed the documentation (https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html)
## (integer) Recent CPU usage for the whole system, or -1 if not supported.

In what cases is this not supported?

### Steps to Reproduce

GET _cat/nodes?format=json

**Comment by DaveCTurner** [comment] 2022-11-25 09:50
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. Moreover your question relates to a version that is [no longer supported](https://www.elastic.co/support/eol).

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by BBQigniter** [comment] 2022-12-07 08:39
I think this issue can be reopened @DaveCTurner 

We currently see the same issue on our ECK-managed ELK-cluster version 8.4.1 (on our test-system which is setup similarly it's not happening)

All our Elasticsearch instances show `cpu -1` if I call for example `GET _cat/nodes?v` in Kibana.

The problem suddenly seems to have started at about midnight yesterday 06.12.2022

A node/pod restart didn't help and I'll check if I can find some hint why this suddenly happens

**Comment by BBQigniter** [comment] 2022-12-07 09:02
hmm, I wasn't able to find anything obvious on the nodes or in the Elasticsearch node/pod logs. 

could it be that this bug has something to with https://github.com/elastic/elasticsearch/pull/90319 even though I was not able to find some similar log-message?

**Comment by DaveCTurner** [comment] 2022-12-07 09:12
The CPU value comes pretty much directly from the JDK's `OperatingSystemMXBean#getCpuLoad()` method which AIUI ultimately reads information from `/proc/stat` (or the containers equivalent) and returns `-1` on a failure. Unfortunately the JDK doesn't give us any information about the nature of the failure. However, given that nothing in Elasticsearch changed at this time, and restarting Elasticsearch doesn't help, it sounds like something has changed in your environment instead.

Does the problem persist if you restart the whole host rather than just the affected pods?

**Comment by DaveCTurner** [comment] 2022-12-07 12:02
I think it uses `/proc/stat`, not `/proc/[pid]/stat`. Can you share this file from a bad node?

**Comment by BBQigniter** [comment] 2022-12-07 12:36
sorry, not possible anymore :( as I already have rebooted all affected nodes.

**Comment by rjernst** [comment] 2022-12-07 22:10
Given that further information is not possible, and the problem is outside of the control of Elasticsearch, I'm going to close this issue. If it occurs again in the future, please let us know the contents of `/proc/stat` on the troublesome node.

**Closed by rjernst** 2022-12-07 22:10 UTC
Labels: >bug, :Core/Infra/Core, Team:Core/Infra

**Comment by grcevski** [comment] 2022-12-08 15:02
Hi @yskim8830, as far as I understand the Microsoft build of OpenJDK should be identical to AdoptOpenJDK, except that they might have fixes that haven't been merged into OpenJDK yet. I wonder if it was Java version issue, perhaps a bug that had been fixed in a newer release?

Do you mind sharing a full version String from the two builds? E.g. java -version on the MDOpenJDK and AdoptOpenJDK.

Thanks.

**Comment by yskim8830** [comment] 2022-12-09 01:11
Hi @grcevski,
AdoptOpenJDK version was tested with 15.0.1+9. and
MS OpenJDK version 11.0.17 was tested.
Since there was no supported version of MS OpenJDK 15, we used version 11, which can support elasticsearch 7.10.x.
(Only versions 11, 16, and 17 were released.)
