### ISSUE TITLE
Input Json is not properly validated while indexing

### ISSUE THREAD

**Issue by mehrdad-hassanabadi** [elastic/elasticsearch#11012] opened 2015-05-06 12:51 UTC
Elasticsearch does not seem to consistently validate the syntaxt of the input json.

For instance the following (lacking a closing '}' ) returns 400:
> curl -v -XPUT 'http://localhost:9200/a/data/1' -d '{"t" : {"a" : "b"}'

But the following (same thing but with a bunch of extra '}' ) goes through, and it is even able to fetch it back:

curl -v -XPUT 'http://localhost:9200/a/data/1' -d '{"t" : {"a" : "b"}}}}}}}}}}}}}}'

I tried this on 1.4.3 and 1.5.2. Both show the same behavior.

**Comment by clintongormley** [comment] 2015-05-06 12:52
Closing as duplicate of #2315

**Closed by clintongormley** 2015-05-06 12:52 UTC
