### ISSUE TITLE
"supersetFreq > supersetSize" exception while running the significant terms aggregation, when sizes are equal

### ISSUE THREAD

**Issue by radu-gheorghe** [elastic/elasticsearch#9578] opened 2015-02-05 10:01 UTC
I can't quite understand why this is happening, but on occasions I'm getting errors like these while using background_filter, even though the query itself contains all the filters from the background filter:

```
ElasticsearchIllegalArgumentException[supersetFreq > supersetSize, in JLHScore.score(..)]
```

or

```
ElasticsearchIllegalArgumentException[subsetSize > supersetSize, does your background filter not include all documents in the bucket? If so and it is intentional, set "background_is_superset": false]
```

I can reproduce the first one everytime by using the match_all filter: https://gist.github.com/radu-gheorghe/0f9e1a04b11dc4e1f32b

It looks like this is happening only when the foreground and background set happen to be identical on a shard, but I'm not able to confirm if this is actually true yet. Another thing that's unclear is whether this affects other aggregations (e.g. if I'm nesting this significant terms aggregation under a terms aggregation, or just there's a different aggregation running on the same shard). I tend to think that they're affected, because the response says N shards failed (so I assume they fail completely?).

I'll try to dig deeper, right now things are quite fuzzy. Please tell me if you have any insights and/or workarounds. So far it looks like "background_is_superset": false helps, but that skews results.

**Comment by markharwood** [comment] 2015-02-05 11:31
I couldn't reproduce the error in your example gist. What version are you running?

I know your example with "match_all" may be contrived but there does need to be a difference between the subset/superset samples provided in order for the significance algorithms to do their thing.

**Comment by radu-gheorghe** [comment] 2015-02-06 06:58
Hello and thanks for your fast reply, Mark!

It's interesting because it always reproduces for me on ES 1.4.2. Clean install - always get the exception. Maybe you run it against master and something was fixed?

And yes, I'm aware that I can't expect significant results if subset=superset. In my use-case, the significant terms agg is nested under a terms agg. So it maybe be that subset=superset for some shard (I'm hitting hundreds of shards) or something like that. I got to the match_all example by trying to simplify things.

Thanks for looking into this!

**Comment by markharwood** [comment] 2015-02-06 09:57
OK, reproduced on 1.4.2 but looks OK on master.
I noticed that on 1.4.2 this works OK:

	GET /test/_search
	{
	   "aggregations": {
		  "test": {
			 "significant_terms": {
				"field": "a",
				"background_filter": {
				   "terms": {
					  "a": [
						 "foo",
						 "foo2"
					  ]
				   }
				}
			 }
		  }
	   }
	}

..which logically matches the same set of docs as match_all in your example. My guess is that there was an issue with the use of "match_all" filter but given this looks to be fixed in master and is a non-sensical thing to do (the default background without a background_filter is "all docs") then I am tempted to close this issue unless you can provide an example that doesn't use match_all as a background?

**Comment by radu-gheorghe** [comment] 2015-02-09 20:13
Thanks again for the quick follow-up. The trouble is, I can't provide a curl recreation of the issue with something else than match_all.

The original problem, however, is quite a lot different, I was using match_all because that was the only way I could provide a curl recreation: our significant terms aggregation is nested under a terms aggregation. So even though the filtered query (from the root object of the request) and the background_filter (of the significant terms agg) are identical (none of them match_all), in most situations the foreground set is just the bucket of one of the top N terms.

The interesting part is that the problem doesn't reproduce everywhere. Only some shards fail on some queries. Reindexing the same data gave us different number of failing shards for the same query. My suspicion is that failing shards have the subset equal to the superset, and that's where I'm getting the (wrong) error that "supersetFreq - subsetFreq > supersetSize - subsetSize". Do you know if there's a way to confirm that?

In the meantime, I would try to see if I can reproduce the issue on master. On 1.4.2, though, it's pretty clear to me that it's a bug somewhere in calculating those frequencies. Or maybe we shouldn't nest the significant terms under the terms aggregation?

**Comment by clintongormley** [comment] 2015-04-05 20:20
@radu-gheorghe @markharwood any follow up on this issue?

**Comment by radu-gheorghe** [comment] 2015-04-06 04:13
Nothing from me, I couldn't get a setup with master ES and the production data that was producing the issue in the first place :(

**Comment by clintongormley** [comment] 2015-04-26 20:07
OK thanks - going to assume fixed then. Feel free to reopen if you see it again

**Closed by clintongormley** 2015-04-26 20:07 UTC
Labels: feedback_needed

**Comment by maxcom** [comment] 2016-03-11 17:22
I see the same problem on Elasticsearch 1.7.5, significant terms with GND score. Background set has exaclty the same filters as main query. Significant terms aggegation is inside of terms aggregation.

**Comment by markharwood** [comment] 2016-03-11 17:34
Can you share the query JSON? (Ideally also with a minimal set of indexing commands that reproduce the problem but I know that might be expecting a lot...)

**Comment by maxcom** [comment] 2016-03-11 17:39
Query is autogenerated and may look strange

```
{
	"query": {
		"filtered": {
			"query": {
				"match_all": {}
			},
			"filter": {
				"bool": {
					"must": [{
						"range": {
							"date": {
								"from": "now/w",
								"to": null,
								"include_lower": true,
								"include_upper": true
							}
						}
					}, {
						"match_all": {}
					}]
				}
			}
		}
	},
	"aggregations": {
		"persons": {
			"significant_terms": {
				"field": "combined_persons",
				"size": 100,
				"min_doc_count": 1,
				"background_filter": {
					"range": {
						"date": {
							"from": "now/w",
							"to": null,
							"include_lower": true,
							"include_upper": true
						}
					}
				},
				"gnd": {
					"background_is_superset": true
				}
			}
		},
		"count": {
			"cardinality": {
				"field": "combined_persons"
			}
		}
	}
}
```

**Comment by maxcom** [comment] 2016-03-11 17:46
I need some time to remove extra fields and other non-relevant data from dataset, I hope I'll do in on Monday.

**Comment by markharwood** [comment] 2016-03-11 17:47
Many thanks. Do you have a stack trace too?

>  and may look strange

It does. The aggregation looks to be being asked to report on the significant differences between 2 identical sets? The foreground and background are the same in this case, no? Also - how many shards do you have out of interest?

**Comment by maxcom** [comment] 2016-03-11 17:58
> The aggregation looks to be being asked to report on the significant differences between 2 identical sets? The foreground and background are the same in this case, no?

Yes, that is right, but this is a corner case. Usually we have more filters in main query, and we only copy the date filter in a background set. If this is a problem, we can detect case when there sets are identical and replace sigterms with terms.

> Do you have a stack trace too?

```
2016-03-11 20:09:54.205346500 [DEBUG][action.search.type       ] [main] [msg-2016-10][2], node[XLipOAukTBCsvwZ-7b2png], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@4abe5b9d]
2016-03-11 20:09:54.205349500 org.elasticsearch.ElasticsearchIllegalArgumentException: subsetSize > supersetSize, does your background filter not include all documents in the bucket? If so and it is intentional, set "background_is_superset": false
2016-03-11 20:09:54.205351500   at org.elasticsearch.search.aggregations.bucket.significant.heuristics.NXYSignificanceHeuristic.checkFrequencies(NXYSignificanceHeuristic.java:130)
2016-03-11 20:09:54.205406500   at org.elasticsearch.search.aggregations.bucket.significant.heuristics.NXYSignificanceHeuristic.computeNxys(NXYSignificanceHeuristic.java:79)
2016-03-11 20:09:54.205408500   at org.elasticsearch.search.aggregations.bucket.significant.heuristics.GND.getScore(GND.java:77)
2016-03-11 20:09:54.205409500   at org.elasticsearch.search.aggregations.bucket.significant.InternalSignificantTerms$Bucket.updateScore(InternalSignificantTerms.java:79)
2016-03-11 20:09:54.205416500   at org.elasticsearch.search.aggregations.bucket.significant.GlobalOrdinalsSignificantTermsAggregator.buildAggregation(GlobalOrdinalsSignificantTermsAggregator.java:101)
2016-03-11 20:09:54.205424500   at org.elasticsearch.search.aggregations.bucket.significant.GlobalOrdinalsSignificantTermsAggregator.buildAggregation(GlobalOrdinalsSignificantTermsAggregator.java:40)
2016-03-11 20:09:54.205425500   at org.elasticsearch.search.aggregations.AggregationPhase.execute(AggregationPhase.java:134)
2016-03-11 20:09:54.205427500   at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:172)
2016-03-11 20:09:54.205433500   at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:301)
2016-03-11 20:09:54.205434500   at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:312)
2016-03-11 20:09:54.205435500   at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
2016-03-11 20:09:54.205436500   at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
2016-03-11 20:09:54.205441500   at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
2016-03-11 20:09:54.205442500   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2016-03-11 20:09:54.205443500   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2016-03-11 20:09:54.205450500   at java.lang.Thread.run(Thread.java:745)
```

> Also - how many shards do you have out of interest?

This query runs on one index with 6 shards.
