### ISSUE TITLE
Clone index does not keep "number_of_replicas" setting, nor it respects index templates

### ISSUE THREAD

**Issue by pmishev** [elastic/elasticsearch#74135] opened 2021-06-15 15:01 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 7.12.1

**Description of the problem including expected versus actual behavior**:

There could as well be 2 unrelated problems:

1. When cloning an index, `number_of_replicas` of the target index is not kept the same as the source index.

2. If there is an index template that sets the `number_of_replicas` to 0, this is being ignored as well, although the target index name matches the template pattern

**Steps to reproduce**:
```
PUT _index_template/template_1
{
  "index_patterns": ["mytest*"],
  "template": {
    "settings": {
      "number_of_replicas" : 0
    }
  }
}
PUT mytest1
GET mytest1
```
Observe that number_of_replicas = 0, as expected.

```
PUT /mytest1/_settings
{
  "settings": {
    "index.blocks.write": true
  }
}
POST /mytest1/_clone/mytest2
GET mytest2
```
Observe that number_of_replicas = 1, so the value was neither copied over from the source index, nor the index template was respected.

**Comment by DaveCTurner** [comment] 2021-06-15 15:58
This behaviour is by design, and the note in the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-clone-index.html) that says "Cloning doesn’t copy index metadata..." is intended to describe it, but I agree it could be clearer. Especially we should note that index templates have no impact on cloning. Marking this as a docs bug.

**Comment by pmishev** [comment] 2021-06-16 09:19
In the PR you did you added `Notes the clone API doesn't copy index settings.`, but I don't think that's the case. All other index settings I had in my index were copied over (e.g analysis, max_ngram_diff, blocks, etc.).

At the moment I'm handling copying the number_of_replicas manually app-side, but I can't be sure if there aren't any other settings that are not being copied over as well. Perhaps you should make it more explicit exactly what is copied and what is not.

**Comment by DaveCTurner** [comment] 2021-06-16 10:24
Sorry, it seems I've misread the code, I have just discovered a whole load of complications and it seems to vary by version. Let me investigate further what it's supposed to be doing.

**Comment by DaveCTurner** [comment] 2021-06-16 10:49
Ok sorry for the confusion, as per https://github.com/elastic/elasticsearch/issues/28347 these days we apparently _do_ copy most of the settings over. The only ones that look to be overridden are `index.number_of_replicas` and `index.auto_expand_replicas`:

https://github.com/elastic/elasticsearch/blob/393ab2d813b1fed8e6d69b3b4c4704fc3d93c422/server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateIndexService.java#L794-L799

There's a bunch of other private settings that are also not being copied, but that's deliberate and they don't matter to end-users anyway.

I'll correct the docs PR that James made.

**Comment by jrodewig** [comment] 2021-06-22 16:16
@DaveCTurner closed this with https://github.com/elastic/elasticsearch/pull/74175. Thanks again!

**Closed by jrodewig** 2021-06-22 16:16 UTC
Labels: :Core/Features/Indices APIs, >bug, >docs, Team:Core/Features, Team:Docs

**Comment by DaveCTurner** [comment] 2021-06-28 11:07
I am not sure it's deliberate that clones always have exactly one replica by default, at least I find that a bit surprising given that other settings are copied over, and I think we might want to consider this a bug. I opened https://github.com/elastic/elasticsearch/issues/74615 to discuss whether we want to do anything further on this front. I didn't reopen this thread since I didn't want the discussion to dwell on the point about index templates raised here.
