### ISSUE TITLE
Composite aggregation takes a long time when there are no matching docs

### ISSUE THREAD

**Issue by not-napoleon** [elastic/elasticsearch#85567] opened 2022-03-31 16:39 UTC
### Elasticsearch Version

8.1.0

### Java Version

_bundled_

### OS Version

-

### Problem Description

While profiling a query, we (@jpountz and @not-napoleon) observed that the Composite aggregation was spending a lot of time building a leaf collector with a top level `MatchNoDocsQuery`.  

### Steps to Reproduce

Excerpt from profile output:

```
"profile" : {
    "shards" : [
      {
        "id" : "[REDACTED]",
        "searches" : [
          {
            "query" : [
              {
                "type" : "MatchNoDocsQuery",
                "description" : """MatchNoDocsQuery("User requested "match_none" query.")""",
                "time_in_nanos" : 3322,
                "breakdown" : {
                  "set_min_competitive_score_count" : 0,
                  "match_count" : 0,
                  "shallow_advance_count" : 0,
                  "set_min_competitive_score" : 0,
                  "next_doc" : 0,
                  "match" : 0,
                  "next_doc_count" : 0,
                  "score_count" : 0,
                  "compute_max_score_count" : 0,
                  "compute_max_score" : 0,
                  "advance" : 0,
                  "advance_count" : 0,
                  "score" : 0,
                  "build_scorer_count" : 24,
                  "create_weight" : 745,
                  "shallow_advance" : 0,
                  "create_weight_count" : 1,
                  "build_scorer" : 2577
                }
              }
            ],
            "rewrite_time" : 3452,
            "collector" : [
              {
                "name" : "MultiCollector",
                "reason" : "search_multi",
                "time_in_nanos" : 1451246478,
                "children" : [
                  {
                    "name" : "EarlyTerminatingCollector",
                    "reason" : "search_count",
                    "time_in_nanos" : 13458
                  },
                  {
                    "name" : "MultiBucketCollector: [[group_by, total_count]]",
                    "reason" : "aggregation",
                    "time_in_nanos" : 1451207888
                  }
                ]
              }
            ]
          }
        ],
        "aggregations" : [
          {
            "type" : "CompositeAggregator",
            "description" : "group_by",
            "time_in_nanos" : 1451208986,
            "breakdown" : {
              "reduce" : 0,
              "post_collection_count" : 1,
              "build_leaf_collector" : 1451137341,
              "build_aggregation" : 59624,
              "build_aggregation_count" : 1,
              "build_leaf_collector_count" : 24,
              "post_collection" : 2985,
              "initialize" : 9036,
              "initialize_count" : 1,
              "reduce_count" : 0,
              "collect" : 0,
              "collect_count" : 0
            },
            "debug" : {
              "built_buckets" : 1
            }
          },
          {
            "type" : "SumAggregator",
            "description" : "total_count",
            "time_in_nanos" : 40078,
            "breakdown" : {
              "reduce" : 0,
              "post_collection_count" : 1,
              "build_leaf_collector" : 38570,
              "build_aggregation" : 561,
              "build_aggregation_count" : 1,
              "build_leaf_collector_count" : 24,
              "post_collection" : 89,
              "initialize" : 858,
              "initialize_count" : 1,
              "reduce_count" : 0,
              "collect" : 0,
              "collect_count" : 0
            },
            "debug" : {
              "built_buckets" : 1
            }
          },
          {
            "type" : "SumAggregator",
            "description" : "sum_count",
            "time_in_nanos" : 5705,
            "breakdown" : {
              "reduce" : 0,
              "post_collection_count" : 1,
              "build_leaf_collector" : 0,
              "build_aggregation" : 833,
              "build_aggregation_count" : 1,
              "build_leaf_collector_count" : 0,
              "post_collection" : 725,
              "initialize" : 4147,
              "initialize_count" : 1,
              "reduce_count" : 0,
              "collect" : 0,
              "collect_count" : 0
            },
            "debug" : {
              "built_buckets" : 0
            }
          }
        ]
      },
```

**Comment by jpountz** [comment] 2022-04-07 11:19
For reference, one suspect I have for this is the loading of global ordinals.

**Comment by 111andre111** [comment] 2022-04-12 14:00
I am not sure, but can this one here be a side effect?
Just asking: https://github.com/elastic/elasticsearch/issues/84721

**Comment by salvatore-campagna** [comment] 2022-05-02 11:15
It looks like this SDH (https://github.com/elastic/sdh-elasticsearch/issues/5794) is hitting a similar ptobelm when building the leaf collector for FilterAggregator.

**Comment by salvatore-campagna** [comment] 2022-06-06 10:19
Wouldn't it be useful to look at a flame graph?

**Comment by jpountz** [comment] 2022-06-07 13:34
@111andre111 It's related in that global ordinals are involved in both cases, but I'm seeing these issues as not directly related. This issue is about not loading global ordinals when no documents match the query while the other issue is about the performance of computing global ordinals.

@salvatore-campagna 
1. Getting a flame chart was not something we could easily do at the time.
2. It needs to be a composite aggregation on a `keyword` or `ip` field (whose implementation uses ordinals under the hood) that has a high cardinality (otherwise building global ordinals is cheap)
3. Any dataset that has several millions of unique values mapped as `keyword` or `ip` should work. Note that global ordinals are cached, so you will need to invalidate or clear the cache between requests to be able to reproduce this issue. E.g. our Rally tracks would typically not incur the cost of building global ordinals since they tend to run queries against read-only datasets.
4. It doesn't depend directly on the number of documents but on the number of unique values on the field that is being aggregated.

**Comment by wchaparro** [comment] 2024-02-15 20:36
Closing as not planned.

**Closed by wchaparro** 2024-02-15 20:36 UTC
Labels: >bug, Team:Analytics, :Analytics/CompositeAggs
