### ISSUE TITLE
Failures in RollupActionIT.testRollupIndexAndSetNewRollupPolicy

### ISSUE THREAD

**Issue by danhermann** [elastic/elasticsearch#69934] opened 2021-03-03 22:52 UTC
**Build scan**: https://gradle-enterprise.elastic.co/s/4et32nzkiu5sc

**Repro line**: `./gradlew ':x-pack:plugin:ilm:qa:multi-node:javaRestTest' --tests "org.elasticsearch.xpack.ilm.actions.RollupActionIT.testRollupIndexAndSetNewRollupPolicy" -Dtests.seed=625E2AA249E4FA -Dtests.security.manager=true -Dtests.locale=nb-NO -Dtests.timezone=Australia/Hobart -Druntime.java=11`

**Reproduces locally?**: No 

**Applicable branches**: master, 7.x, 7.12

**Failure history**: ~9 failures in the last month. See [build stats](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-6M,mode:quick,to:now))&_a=(columns:!(project,branch),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:e58bf320-7efd-11e8-bf69-63c8ef516157,key:project,negate:!f,params:(query:elasticsearch,type:phrase),type:phrase,value:elasticsearch),query:(match:(project:(query:elasticsearch,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:e58bf320-7efd-11e8-bf69-63c8ef516157,key:test,negate:!f,params:(query:testRollupIndexAndSetNewRollupPolicy,type:phrase),type:phrase,value:testRollupIndexAndSetNewRollupPolicy),query:(match:(test:(query:testRollupIndexAndSetNewRollupPolicy,type:phrase))))),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'message:%20%22failed%20to%20delete%20policy%22'),sort:!(time,desc))).

**Failure excerpt**:
```
java.lang.RuntimeException: failed to delete policy: policy-HLide

Caused by: org.elasticsearch.client.ResponseException: method [DELETE], host [http://[::1]:64566], URI [/_ilm/policy/policy-HLide], status line [HTTP/1.1 400 Bad Request] |  
  | {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Cannot delete policy [policy-HLide]. It is in use by one or more indices: [index-ylgpfvwlhu, rollup-index-ylgpfvwlhu-tv9-58ajth-vurjsnb1o8a]"}],"type":"illegal_argument_exception","reason":"Cannot delete policy [policy-HLide]. It is in use by one or more indices: [index-ylgpfvwlhu, rollup-index-ylgpfvwlhu-tv9-58ajth-vurjsnb1o8a]"},"status":400}

```

**Comment by andreidan** [comment] 2021-03-04 09:59
Closing this as a duplicate of https://github.com/elastic/elasticsearch/issues/68609 (@talevy is already looking into the failure)

**Closed by andreidan** 2021-03-04 09:59 UTC
Labels: :Core/Features/ILM+SLM, >test-failure, Team:Core/Features

**Comment by danhermann** [comment] 2021-03-04 13:53
Thanks for updating this, @andreidan. I missed the existing issue while triaging it.
