### ISSUE TITLE
[CI] NodeTests.testLoadPluginBootstrapChecks failure

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#41903] opened 2019-05-07 15:25 UTC
Failed for 7.x: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+corretto-periodic/ES_BUILD_JAVA=openjdk12,label=amazon/lastCompletedBuild/consoleFull

## Reproduction line
(does not) reproduce locally
```
./gradlew :server:test --tests "org.elasticsearch.node.NodeTests.testLoadPluginBootstrapChecks" \
  -Dtests.seed=8D55FC72EC3AA41B \
  -Dtests.security.manager=true \
  -Dtests.locale=no-NO \
  -Dtests.timezone=Europe/Sofia \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

## Example relevant log:
```
org.elasticsearch.node.NodeTests > testLoadPluginBootstrapChecks FAILED
    com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=899, name=elasticsearch[mock_ node][search][T#1], state=RUNNABLE, group=TGRP-NodeTests]

        Caused by:
        java.lang.AssertionError: expected task to always take longer than 0 nanoseconds, got: -1
REPRODUCE WITH: ./gradlew :server:test --tests "org.elasticsearch.node.NodeTests.testLoadPluginBootstrapChecks" -Dtests.seed=8D55FC72EC3AA41B -Dtests.security.manager=true -Dtests.locale=no-NO -Dtests.timezone=Europe/Sofia -Dcompiler.java=12 -Druntime.java=8
```

## Frequency
1st occurence

**Comment by jasontedor** [comment] 2019-05-07 22:21
I think that this is a duplicate of #41448 and fixed by #41810. Please feel free to reopen if you disagree.

**Closed by jasontedor** 2019-05-07 22:21 UTC
Labels: :Core/Infra/Plugins, >test-failure
