### ISSUE TITLE
Builds failing with OOM

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#34458] opened 2018-10-15 13:22 UTC
Since October 7 there's been approximately one build per day that's failed with an OOM:

- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+periodic/2704/console
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.4+multijob-unix-compatibility/os=oraclelinux/56/console
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=oraclelinux/55/console
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.4+multijob-unix-compatibility/os=oraclelinux/54/console
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=oraclelinux/52/console
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=oraclelinux/50/console
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.4+matrix-java-periodic/ES_BUILD_JAVA=java10,ES_RUNTIME_JAVA=java8fips,nodes=virtual&&linux/47/console

This was much less prevalent before October 7.

**Comment by atorok** [comment] 2018-10-17 13:43
Those logs are unfortunately gone. 
I did run into this locally while running with the Gradle daemon, 
and then subsequently looked at the  heap put nothing stood out. 
I'm not aware of any changes to the  build that could have caused this around Oct. 7.    
We allow Gradle to use 2G, I am tempted to increase that to see if we still get OOMs and as an interim solution before I get a chance to look more into it.

**Comment by ywelsch** [comment] 2018-10-18 13:15
another one: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=oraclelinux/4/console

**Comment by atorok** [comment] 2018-10-18 13:59
@ywelsch the one you link to has:
```
15:18:02 > Task :server:integTest FAILED
15:18:02 Tests with failures:
15:18:02   - org.elasticsearch.action.admin.indices.create.CreateIndexIT.testCreateAndDeleteIndexConcurrently
15:18:02 
```

@DaveCTurner  where was the OOM ? I assumed Gradle, but it could have been the tests, or the tests clusters too.

**Comment by DaveCTurner** [comment] 2018-10-18 14:18
They looked like the one that Yannick just linked:

```
  2> Oct 18, 2018 3:14:40 PM com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
  2> WARNING: Uncaught exception in thread: Thread[elasticsearch[node_td3][__mock_network_thread][T#11],5,TGRP-CreateIndexIT]
  2> java.lang.OutOfMemoryError: Java heap space
  2> 	at __randomizedtesting.SeedInfo.seed([8896DE14CA3FC96D]:0)
  2> 	at org.elasticsearch.transport.MockTcpTransport.readMessage(MockTcpTransport.java:155)
  2> 	at org.elasticsearch.transport.MockTcpTransport.access$800(MockTcpTransport.java:69)
  2> 	at org.elasticsearch.transport.MockTcpTransport$MockChannel$2.lambda$doRun$0(MockTcpTransport.java:335)
  2> 	at org.elasticsearch.transport.MockTcpTransport$MockChannel$2$$Lambda$2318/1903598586.run(Unknown Source)
  2> 	at org.elasticsearch.common.util.CancellableThreads.executeIO(CancellableThreads.java:105)
  2> 	at org.elasticsearch.transport.MockTcpTransport$MockChannel$2.doRun(MockTcpTransport.java:335)
  2> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
  2> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  2> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  1> [2018-10-18T15:14:35,036][WARN ][o.e.t.d.TestZenDiscovery ] [node_tm2] not enough master nodes discovered during pinging (found [[Candidate{node={node_tm2}{yE_r74WFSE2wsscOhN9fNw}{a7UCF_URSVGq9hfHOgz40A}{127.0.0.1}{127.0.0.1:40624}, clusterStateVersion=-1}]], but needed [2]), pinging again
  1> [2018-10-18T15:14:35,036][INFO ][o.e.t.d.MockZenPing      ] [node_tm2] pinging using mock zen ping
  2> 	at java.lang.Thread.run(Thread.java:748)
  2> Oct 18, 2018 3:14:40 PM com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
  2> WARNING: Uncaught exception in thread: Thread[elasticsearch[node_td3][__mock_network_thread][T#14],5,TGRP-CreateIndexIT]
  2> java.lang.OutOfMemoryError: Java heap space
  2> 	at __randomizedtesting.SeedInfo.seed([8896DE14CA3FC96D]:0)
  2> 	at org.elasticsearch.transport.MockTcpTransport.readMessage(MockTcpTransport.java:155)
  2> 	at org.elasticsearch.transport.MockTcpTransport.access$800(MockTcpTransport.java:69)
  1> [2018-10-18T15:14:35,036][INFO ][o.e.t.d.MockZenPing      ] [node_td3] pinging using mock zen ping
  2> 	at org.elasticsearch.transport.MockTcpTransport$MockChannel$2.lambda$doRun$0(MockTcpTransport.java:335)
  2> 	at org.elasticsearch.transport.MockTcpTransport$MockChannel$2$$Lambda$2318/1903598586.run(Unknown Source)
  1> [2018-10-18T15:14:35,036][WARN ][o.e.t.d.TestZenDiscovery ] [node_td3] not enough master nodes discovered during pinging (found [[Candidate{node={node_tm2}{yE_r74WFSE2wsscOhN9fNw}{a7UCF_URSVGq9hfHOgz40A}{127.0.0.1}{127.0.0.1:40624}, clusterStateVersion=-1}]], but needed [2]), pinging again
  2> 	at org.elasticsearch.common.util.CancellableThreads.executeIO(CancellableThreads.java:105)
  2> 	at org.elasticsearch.transport.MockTcpTransport$MockChannel$2.doRun(MockTcpTransport.java:335)
  1> [2018-10-18T15:14:35,036][INFO ][o.e.t.d.MockZenPing      ] [node_td3] pinging using mock zen ping
  2> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
  2> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

```

**Comment by colings86** [comment] 2018-10-29 09:02
https://github.com/elastic/infra/issues/7430 has now been merged so any heapdumps are uploaded to GCP if CI fails. 

If you come across a build which has OOME'd, please check the uploaded heapdump to see whats dominating the heap

**Comment by tvernum** [comment] 2018-11-09 00:48
We had a failure in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=fedora/47/

I did a quick analysis of the [heap dump](https://storage.cloud.google.com/elasticsearch-ci-artifacts/jobs/elastic+elasticsearch+master+multijob-unix-compatibility/os=fedora/47/server/build/heapdump/java_pid3241.hprof).

The usage is clearly in 8 very large (50 million bytes) `byte[]` created by `MockTcpTransport.readMessage`.
e.g.
> The thread java.lang.Thread @ 0xf05dd0b0 elasticsearch[node_sd1][__mock_network_thread][T#8] keeps local variables with total size 50,399,752 (11.75%) bytes.
>
> The memory is accumulated in one instance of "byte[]" loaded by "<system class loader>".
```

elasticsearch[node_sd1][__mock_network_thread][T#8]
  at java.net.SocketInputStream.socketRead0(Ljava/io/FileDescriptor;[BIII)I (Native Method)
  at java.net.SocketInputStream.socketRead(Ljava/io/FileDescriptor;[BIII)I (SocketInputStream.java:116)
  at java.net.SocketInputStream.read([BIII)I (SocketInputStream.java:171)
  at java.net.SocketInputStream.read([BII)I (SocketInputStream.java:141)
  at java.io.BufferedInputStream.read1([BII)I (BufferedInputStream.java:284)
  at java.io.BufferedInputStream.read([BII)I (BufferedInputStream.java:345)
  at org.elasticsearch.common.io.Streams.readFully(Ljava/io/InputStream;[BII)I (Streams.java:214)
  at org.elasticsearch.common.io.stream.InputStreamStreamInput.readBytes([BII)V (InputStreamStreamInput.java:67)
  at org.elasticsearch.common.io.stream.StreamInput.readFully([B)V (StreamInput.java:192)
  at org.elasticsearch.transport.MockTcpTransport.readMessage(Lorg/elasticsearch/transport/MockTcpTransport$MockChannel;Lorg/elasticsearch/common/io/stream/StreamInput;)V (MockTcpTransport.java:155)
  at org.elasticsearch.transport.MockTcpTransport.access$800(Lorg/elasticsearch/transport/MockTcpTransport;Lorg/elasticsearch/transport/MockTcpTransport$MockChannel;Lorg/elasticsearch/common/io/stream/StreamInput;)V (MockTcpTransport.java:69)
  at org.elasticsearch.transport.MockTcpTransport$MockChannel$2.lambda$doRun$0(Lorg/elasticsearch/common/io/stream/StreamInput;)V (MockTcpTransport.java:334)
  at org.elasticsearch.transport.MockTcpTransport$MockChannel$2$$Lambda$1476.run()V (Unknown Source)
  at org.elasticsearch.common.util.CancellableThreads.executeIO(Lorg/elasticsearch/common/util/CancellableThreads$IOInterruptable;)V (CancellableThreads.java:106)
  at org.elasticsearch.transport.MockTcpTransport$MockChannel$2.doRun()V (MockTcpTransport.java:334)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run()V (AbstractRunnable.java:37)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V (ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run()V (ThreadPoolExecutor.java:624)
  at java.lang.Thread.run()V (Thread.java:748)
```

**[Histogram](https://github.com/elastic/elasticsearch/files/2564153/histogram.csv.txt)**
```
Class Name,Objects,Shallow Heap,Retained Heap,
byte[],2453,410076168,410076168,
java.lang.Thread,124,14880,403746688,
java.lang.Class,14387,112208,13161896,
char[],55506,7408016,7408016,
java.lang.String,49448,1186752,5845880,
com.carrotsearch.ant.tasks.junit4.slave.SlaveMain,1,32,5244176,
java.lang.Object[],9987,735976,4984312,
java.util.HashMap,6053,290544,3235016,
java.util.HashMap$Node[],2447,283248,3027384,
java.util.HashMap$Node,15713,502816,2635448,
sun.misc.Launcher$AppClassLoader,1,88,2593176,
org.apache.lucene.analysis.standard.StandardTokenizerImpl,7,504,2241752,
java.util.concurrent.ConcurrentHashMap,535,34240,2053952,
java.util.concurrent.ConcurrentHashMap$Node[],332,243016,2029616,
java.util.Vector,310,9920,1931568,
java.util.Collections$UnmodifiableMap,885,28320,1895464,
java.util.concurrent.ConcurrentHashMap$Node,27920,893440,1766048,
org.elasticsearch.index.shard.IndexShard,7,1624,1331408,
org.elasticsearch.index.IndexService,1,152,1310760,
org.elasticsearch.index.engine.InternalEngine,7,1456,1195880,
java.lang.invoke.MethodType,4248,169920,1192536,
org.elasticsearch.common.cache.Cache,10,800,1039776,
org.elasticsearch.common.cache.Cache$CacheSegment[],10,10400,1035200,
org.elasticsearch.common.cache.Cache$CacheSegment,2560,81920,1024848,
org.apache.lucene.index.DefaultIndexingChain,4,256,976120,
org.elasticsearch.test.InternalTestCluster$NodeAndClient,3,120,895640,
org.elasticsearch.common.inject.InjectorImpl,6,288,876080,
org.elasticsearch.index.engine.InternalEngine$AssertingIndexWriter,7,1456,841320,
org.elasticsearch.node.MockNode,3,192,787992,
```

**Byte Arrays**
```
Class Name                                                                                                 | Shallow Heap | Retained Heap
-----------------------------------------------------------------------------------------------------------------------------------------
                                                                                                           |              |              
byte[50390785] @ 0xf85989e8                                                                                |   50,390,808 |    50,390,808
'- <Java Local> java.lang.Thread @ 0xf55814f8  elasticsearch[node_sd1][__mock_network_thread][T#15] Thread |          120 |    50,399,584
byte[50390785] @ 0xf5583a08                                                                                |   50,390,808 |    50,390,808
'- <Java Local> java.lang.Thread @ 0xf3b9ada0  elasticsearch[node_sd1][__mock_network_thread][T#14] Thread |          120 |    50,399,584
byte[50390785] @ 0xf0b7be68                                                                                |   50,390,808 |    50,390,808
'- <Java Local> java.lang.Thread @ 0xf0587e10  elasticsearch[node_sd1][__mock_network_thread][T#13] Thread |          120 |    50,399,584
byte[50390785] @ 0xed54c698                                                                                |   50,390,808 |    50,390,808
'- <Java Local> java.lang.Thread @ 0xf0589038  elasticsearch[node_sd1][__mock_network_thread][T#11] Thread |          120 |    50,399,584
byte[50390785] @ 0xea53df80                                                                                |   50,390,808 |    50,390,808
'- <Java Local> java.lang.Thread @ 0xf05dd3c0  elasticsearch[node_sd1][__mock_network_thread][T#12] Thread |          120 |    50,399,584
byte[50390785] @ 0xe75257d0                                                                                |   50,390,808 |    50,390,808
'- <Java Local> java.lang.Thread @ 0xf05887d0  elasticsearch[node_sd1][__mock_network_thread][T#9] Thread  |          120 |    50,399,584
byte[50390785] @ 0xe45170b8                                                                                |   50,390,808 |    50,390,808
'- <Java Local> java.lang.Thread @ 0xf0588228  elasticsearch[node_sd1][__mock_network_thread][T#10] Thread |          120 |    50,399,584
byte[50390785] @ 0xe14feb60                                                                                |   50,390,808 |    50,390,808
'- <Java Local> java.lang.Thread @ 0xf05dd0b0  elasticsearch[node_sd1][__mock_network_thread][T#8] Thread  |          120 |    50,399,752
byte[5242880] @ 0xe03963c0                                                                                 |    5,242,896 |     5,242,896
byte[32768] @ 0xf0a95068                                                                                   |       32,784 |        32,784
byte[32768] @ 0xf0a77c58                                                                                   |       32,784 |        32,784
byte[32768] @ 0xf0a50958                                                                                   |       32,784 |        32,784
byte[32768] @ 0xf0a01f98                                                                                   |       32,784 |        32,784
byte[32768] @ 0xf09dcba8                                                                                   |       32,784 |        32,784
byte[32768] @ 0xf09afb30                                                                                   |       32,784 |        32,784
byte[32768] @ 0xf0979430                                                                                   |       32,784 |        32,784
byte[32768] @ 0xf094bf38                                                                                   |       32,784 |        32,784
byte[32768] @ 0xf092cc20                                                                                   |       32,784 |        32,784
byte[32768] @ 0xf08d5f00                                                                                   |       32,784 |        32,784
byte[32768] @ 0xf08b8298                                                                                   |       32,784 |        32,784
byte[32768] @ 0xf088bc80                                                                                   |       32,784 |        32,784
byte[18432] @ 0xf0a6a9b8                                                                                   |       18,448 |        18,448
byte[18432] @ 0xf09cf910                                                                                   |       18,448 |        18,448
byte[18432] @ 0xf0946c78                                                                                   |       18,448 |        18,448
byte[18432] @ 0xf08abab0                                                                                   |       18,448 |        18,448
byte[16384] @ 0xf071e5c0                                                                                   |       16,400 |        16,400
byte[16384] @ 0xf071a5b0                                                                                   |       16,400 |        16,400
byte[16384] @ 0xf07165a0                                                                                   |       16,400 |        16,400
byte[16384] @ 0xf0712590                                                                                   |       16,400 |        16,400
Total: 29 of 2,453 entries; 2,424 more                                                                     |              |              
-----------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by jasontedor** [comment] 2018-11-09 00:51
Thanks @tvernum!

@original-brownbear @tbrooks8 Would you take a look?

**Comment by tbrooks8** [comment] 2018-11-09 00:56
Are there tests where we send 50 mb messages? The `MockTcpTransport` is pretty straightforward in the way that it allocates byte arrays that are the exact size of the incoming message.

**Comment by tvernum** [comment] 2018-11-09 01:09
I think this is caused by MockTcpTransport trying to read TLS streams.

The messages sizes are supposedly `50390785` which is [ `0x03` `0x00` `0xe7` `0x01` ]
The message size starts at the 3rd  bytes of the stream (there are 2 header bytes).

Which means if MockTcpTranports gets a TLS header of `16,3,3,0` it will read the first 2 bytes as the header, and then the 3,0 ... as the mesasge size.

We might just want to validate the header bytes we read and allocate the message size?

**Comment by tbrooks8** [comment] 2018-11-09 01:18
> I think this is caused by MockTcpTransport trying to read TLS streams.

Isn't this kind of a problem? The `MockTcpTransport` does not support TLS. Shouldn't the test be using a different transport is we are doing TLS?

Anyway, yeah I can throw an exception prior to the allocation in case the marker bytes are incorrect.

**Comment by tbrooks8** [comment] 2018-11-09 01:35
I opened a PR for checking the marker bytes early. Additionally, the PR uses recyclable BigArrays for `BytesStreamOutput`. This does not prevent the allocation fo 50 mb arrays for the low level reads. That would be more work (and more complicated).

Before we do that we might want to have a discussion if we want to continue to maintain a blocking (behaves differently than production) and non-blocking test:framework transport. Since we now have both.

**Comment by ywelsch** [comment] 2018-11-09 08:48
> Before we do that we might want to have a discussion if we want to continue to maintain a blocking (behaves differently than production) and non-blocking test:framework transport. Since we have both now.

I've added the team-discuss label here.

**Comment by danielmitterdorfer** [comment] 2018-12-03 08:07
Last week we had a discussion among the team whether to remove `MockTcpTransport` entirely and decided to do so. Tim has implemented the first step towards removal in https://github.com/elastic/elasticsearch/pull/36089.

This issue here is closed by https://github.com/elastic/elasticsearch/pull/35402.

**Closed by danielmitterdorfer** 2018-12-03 08:07 UTC
Labels: :Core/Infra/Build, >test-failure, team-discuss, v6.6.0, v7.0.0
