### ISSUE TITLE
Cross Cluster Search inconsistently reporting cluster alias in _index field

### ISSUE THREAD

**Issue by ajoliveira** [elastic/elasticsearch#51720] opened 2020-01-31 00:05 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 7.5.X

**Description of the problem including expected versus actual behavior**: Cross Cluster Search (CCS) configured with 2 clusters, is inconsistent when it reports the `_index` value.  Depending on where wildcard is placed in the cluster/index name, the returned `_index` value will fail to report the cluster alias.  This causes downstream issues with Kibana Discover, for example, trying to drill down into the specific document will fail if the document is on the remote cluster from the cluster Kibana is configured with.

We've found that setting `ccs_minimize_roundtrips=false` does produce the expected results each time.  However, there doesn't appear to be a way to set this so that Kibana Discover can make use of it.

**Steps to reproduce**:
This appears in a specific cluster configured with CCS, using a VPN tunnel that has fairly high latency.  Sample results with defaults, note placement of wildcard:

GET \*:cluster-\*-winlogbeats-\*-2020.01.\*/_search (missing cluster alias) vs
GET \*:cluster-\*-winlogbeats-\*-2020.01.2\*/_search (correct cluster alias)
```
GET *:cluster-*-winlogbeats-*-2020.01.*/_search
{
  "query": {
    "terms": {
      "_id": [
        "xyz",
        "abc"
      ]
    }
  },
  "_source": "_index",
  "aggs": {
    "index": {
      "terms": {
        "field": "_index",
        "size": 100
      }
    }
  }
}
 
{
  "_clusters" : {
    "total" : 2,
    "successful" : 2,
    "skipped" : 0
  },
  "hits" : {
    "total" : {
      "value" : 2,
      "relation" : "eq"
    },
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "cluster-aaa-winlogbeats-v3-daily-2020.01.20",
        "_type" : "_doc",
        "_id" : "xyz",
        "_score" : 1.0,
        "_source" : { }
      },
      {
        "_index" : "cluster-bbb-winlogbeats-v1-daily-2020.01.27",
        "_type" : "doc",
        "_id" : "abc",
        "_score" : 1.0,
        "_source" : { }
      }
    ]
  },
  "aggregations" : {
    "index" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 0,
      "buckets" : [
        {
          "key" : "cluster-aaa-winlogbeats-v3-daily-2020.01.20",
          "doc_count" : 1
        },
        {
          "key" : "cluster-bbb-winlogbeats-v1-daily-2020.01.27",
          "doc_count" : 1
        }
      ]
    }
  }
}
 
 
GET *:cluster-*-winlogbeats-*-2020.01.2*/_search
{
  "query": {
    "terms": {
      "_id": [
        "xyz",
        "abc"
      ]
    }
  },
  "_source": "_index",
  "aggs": {
    "index": {
      "terms": {
        "field": "_index",
        "size": 100
      }
    }
  }
}
{
  "_clusters" : {
    "total" : 2,
    "successful" : 2,
    "skipped" : 0
  },
  "hits" : {
    "total" : {
      "value" : 2,
      "relation" : "eq"
    },
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "cluster-aaa:cluster-aaa-winlogbeats-v3-daily-2020.01.20",
        "_type" : "_doc",
        "_id" : "xyx",
        "_score" : 1.0,
        "_source" : { }
      },
      {
        "_index" : "cluster-bbb:cluster-bbb-winlogbeats-v1-daily-2020.01.27",
        "_type" : "doc",
        "_id" : "abc",
        "_score" : 1.0,
        "_source" : { }
      }
    ]
  },
  "aggregations" : {
    "index" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 0,
      "buckets" : [
        {
          "key" : "cluster-aaa:cluster-aaa-winlogbeats-v3-daily-2020.01.20",
          "doc_count" : 1
        },
        {
          "key" : "cluster-bbb:cluster-bbb-winlogbeats-v1-daily-2020.01.27",
          "doc_count" : 1
        }
      ]
    }
  }
}
```

Specifying `ccs_minimize_roundtrips=false` allows for all combinations to work.  The cluster alias should be included for every document - or at the very least, for the documents that are on the remote cluster from the one where the search is being run from.  This would allow Kibana Discover (or other components?) to correctly request the document.

**Comment by pcsanwald** [comment] 2020-02-05 20:22
@jimczi would you mind triaging this one when you have time?

**Comment by jimczi** [comment] 2020-02-06 14:20
@javanna can you take a look at this when you come back ;)

**Comment by javanna** [comment] 2020-02-18 14:36
@ajoliveira are all nodes on both clusters on the same version? Were you able to reproduce exactly the same behaviour when executing the set of requests that you posted above multiple times?

**Comment by tomerilp** [comment] 2020-04-19 09:44
Hi,
I'm experiencing the same behavior with v7.4.2 & v7.6.2
I have a central cluster (v7.6.2) which serves all remote cluster requests to 6 different clusters (v7.4.2)
The results from the remote search do not contain the cluster name as part of the index name which breaks the "View single document" feature in Kibana.

I have one remote cluster that's connected using the Proxy mode which seems to be working as expected.

**Comment by javanna** [comment] 2020-04-20 07:11
hi @tomerilp I have been trying to reproduce this without any luck, I would love to try and work with you on finding what is causing this. What do you mean by "proxy mode"?

**Comment by tomerilp** [comment] 2020-04-20 07:15
> hi @tomerilp I have been trying to reproduce this without any luck, I would love to try and work with you on finding what is causing this. What do you mean by "proxy mode"?

Hi, forget about the proxy mode, what i see is the cluster alias is missing from the '_index' field only on clusters that were upgraded from 6.8.3.  I created a brand new v7.4.2 cluster which seems to be working fine - i can see its cluster alias in the _index filed.

**Comment by javanna** [comment] 2020-04-20 12:49
Interesting @tomerilp thanks for the follow-up comment. I tried going the same path as you, by first creating a cluster on 6.8 and upgrading it to 7.x but I can't reproduce this behaviour no matter what I try, I always get back the complete _index field which includes the cluster alias. Would you mind posting your request and response, please?

**Comment by hmnguyen1201** [comment] 2020-04-20 14:37
I confirm that this is still an issue on 7.6.2. We did upgraded from 6.8 to 7.5 and that is when we first saw the problem

**Comment by hmnguyen1201** [comment] 2020-04-20 22:02
So this turned out to be the weirdest issue I have ever seen. after we upgraded from 7.5.2 to 7.6.2. I had to restart one of our coord node due to a memory issue and after that it looks like the index alias is working as expected.

**Comment by tomerilp** [comment] 2020-04-21 07:59
Restarting the coord node's service didn't help in my case.

@javanna the request and response are pretty simple, I just login into Kibana and run a simple, non-filtered search against one of the remote clusters for the last 15m, the results are all ok just the _index field shows just the index name without the prefixed cluster name.

**Comment by tomerilp** [comment] 2020-04-21 13:10
For me it seems to happen only when pointing Kibana to an index alias rather than to a specific index name:

_index correct: Point Kibana to search against Cluster_name:SomeIndexAlias
_index incorrect: Point Kibana to search against Cluster_name:FullIndexName

Besides that, i as mentioned before, i have a brand new remote cluster, with newly created indices, which does return the current _index even if i point to an index alias in Kibana.

**Comment by javanna** [comment] 2020-04-21 13:19
@tomerilp thanks for the info. This is a weird bug, it manifests in weird ways and it's hard to reproduce on my end. Are those simple aliases or do they have a filter associated to them?

**Comment by tomerilp** [comment] 2020-04-22 12:34
@javanna I tired both with simple aliases and filter aliases, get the same results.

**Comment by javanna** [comment] 2020-04-22 13:15
@tomerilp could you try sending search requests manually and providing different values of the `batched_reduce_size` parameter, say, `2`, `10` and a very high number that is higher than the number of shards that the query hits? I am curious to see if the result is consistent or not.

**Comment by tomerilp** [comment] 2020-04-22 13:50
@javanna I tried different values and got the same results.
The only way I could make it works is when is use ccs_minimize_roundtrips=false

**Comment by immon** [comment] 2020-05-29 10:33
@javanna I think this can manifest when remote indices are forcemerged.

**Comment by jtibshirani** [comment] 2022-09-23 21:00
We haven't been able to make progress reproducing and debugging this. Are people still seeing the issue pop up? If so could you please comment with the Elasticsearch version and some details of the CCS set-up?

**Comment by jtibshirani** [comment] 2022-11-01 00:10
I'm closing this but feel free to reopen if you see the issue again in recent versions (like 7.17 or later).

**Closed by jtibshirani** 2022-11-01 00:10 UTC
Labels: >bug, :Search/Search, Team:Search
