### ISSUE TITLE
SQL: No results when using LIKE 

### ISSUE THREAD

**Issue by gemaliano** [elastic/elasticsearch#41786] opened 2019-05-03 09:56 UTC
**Elasticsearch version**:
Working in 6.5.4
Not working in 6.7.1, 7.0.0,7.0.1

**Steps to reproduce**:

 1.  Delete testing index in case it is there.
``` DELETE my_index```
 2.  
``` 
POST my_index/_doc/
{
    "message" : "fruit 1\n\nPears\n\nTomatoes\n\nBig Tomatoes 2\n\nOrangesln\n\nLemonsn\nTomatoes\n\nBig Tomatoes 2\n\nOrangesln\n\nMiddle\n\nGrapes\n\nStrawberries 1-11-2\n\n1111 22 333\n\nLvlb Sq 320\n\nBbbbb Gggg DL123\n\nPearsWatermelon Apples 1\n\nBananas 1\n\nChocolateCake124467 874489 123 123 123 123"
}
```

 3.
```
POST /_xpack/sql?format=txt
{
    "query": "SELECT message FROM my_index WHERE message LIKE '%Apples%'"
}
```

No result in 6.7.1,7.0.0,7.0.1
Expected result in 6.5.4. We get the message in response.

4.
We get expected result when testing with:
```
POST my_index/_doc/
{
    "message" : "fruit 1\n\nPears\n\nTomatoes\n\nBig Tomatoes 2\n\nOrangesln\n\nLemonsn\nTomatoes\n\nBig Tomatoes 2\n\nOrangesln\n\nMiddle\n\nGrapes\n\nStrawberries 1-11-2\n\n1111 22 333\n\nLvlb Sq 320\n\nBbbbb Gggg DL123\n\nPearsWatermelon Apples 1\n\nBananas 1\n\nChocolateCake124467 874489"
}
```

**Comment by astefan** [comment] 2019-05-03 10:13
Hi @gemaliano,
This is not a bug. By default, when not using an explicit mapping for a `text` field, Elasticsearch adds a `keyword` subfield to it. In the case of Elasticsearch SQL and `LIKE` statement, we use this subfield to create a `wildcard` query (you can double check this by using the `_translate` API to see the ES query generated).

The `keyword` subfield created by Elasticsearch has `"ignore_above": 256` property which means that field values larger than 256 characters will be trimmed at 256. And in your tests' case this is what is happening. If you create an index like the following (with more than 256 characters allowed):

```
{
  "mappings": {
    "properties": {
      "message": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword",
            "ignore_above": 1256
          }
        }
      }
    }
  }
}
```

The SQL query you are trying to use will work.
Closing this issue now.

**Closed by astefan** 2019-05-03 10:13 UTC
Labels: :Search/SQL

**Comment by astefan** [comment] 2019-05-03 10:22
One more clarifying note: in versions prior to 6.7.1 this might have worked because at that time there was a bug that made ES SQL to generate a `query_string` query (which used the field itself - `message` as opposed to using the `keyword` subfield), which was incorrect.

That bug was fixed with https://github.com/elastic/elasticsearch/pull/40628.

**Comment by astefan** [comment] 2019-05-03 10:37
[Translate API](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/sql-translate.html) helps understanding this better imo.
