### ISSUE TITLE
[CI] AliasRoutingIT fails with test suite timeout

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#26445] opened 2017-08-30 15:09 UTC
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-darwin-compatibility/1109/consoleFull

The test stalls for 20 mins then times out:
```
13:09:41 HEARTBEAT J0 PID(79243@slave-c07tg57hg1hw.local): 2017-08-30T06:09:41, stalled for 1189s at: AliasRoutingIT.testAliasCrudRouting
```
Did it deadlock?

I was not able to reproduce:
```
gradle :core:integTest \
  -Dtests.seed=ACD26EE8017A13B7 \
  -Dtests.class=org.elasticsearch.routing.AliasRoutingIT \
  -Dtests.security.manager=true \
  -Dtests.locale=en-US \
  -Dtests.timezone=America/Los_Angeles
```

**Comment by jasontedor** [comment] 2017-08-31 03:22
I looked into this one. It's not clear what is happening. I noticed from the stack dump in the logs that the test is blocked on an indexing request that apparently never finished. There are two conflicting forces here:
 - the test is using NIO transport
 - the test is on macOS

These are conflicting forces because NIO transport is still in active development, and we have had a lot of issues with *standalone* nodes stalling on macOS the last few weeks (I am not sure why). They are both potential sources to look at, I don't know which it could be. I lean towards thinking this should be looked at from an NIO transport perspective first.

@tbrooks8 Can you take a look at this one? If you do not find anything, please close.

**Comment by tbrooks8** [comment] 2018-01-12 21:15
I have looked at this a couple of times and have been unable to reproduce it. Additionally, the nio work has changed substantially since this PR was opened, so I'm not sure this failure would be up to date. I am closing.

**Closed by tbrooks8** 2018-01-12 21:15 UTC
Labels: jenkins, test, v7.0.0
