### ISSUE TITLE
elasticsearch-plugin list causes stack trace

### ISSUE THREAD

**Issue by aleph-zero** [elastic/elasticsearch#21155] opened 2016-10-27 16:58 UTC
**Elasticsearch version**:
5.0.0

**Plugins installed**: []
None

**JVM version**:
java version "1.8.0_71"
Java(TM) SE Runtime Environment (build 1.8.0_71-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.71-b15, mixed mode)

**OS version**:
Mac OS Sierra

**Description of the problem including expected versus actual behavior**:
On a plain, empty installation ```elasticsearch-plugin list``` causes a stack trace. It should just say that no plugins are installed.

**Steps to reproduce**:
 1. Install 5.0
 2. Run ```./bin/elasticsearch-plugin list```

**Describe the feature**:
```
./bin/elasticsearch-plugin list
Exception in thread "main" java.io.IOException: Plugins directory missing: /Users/andrew/bin/elastic/stack-5.0.0/elasticsearch-5.0.0/plugins
	at org.elasticsearch.plugins.ListPluginsCommand.execute(ListPluginsCommand.java:51)
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96)
	at org.elasticsearch.cli.Command.main(Command.java:62)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:42)
```

**Comment by dadoonet** [comment] 2016-10-27 19:43
Duplicate of #20342

**Closed by dadoonet** 2016-10-27 19:43 UTC
