### ISSUE TITLE
Simplify the setup of third party tests

### ISSUE THREAD

**Issue by alpar-t** [elastic/elasticsearch#47844] opened 2019-10-10 09:07 UTC
We have a set of jobs that talk to external blob stores to test repositories against the real services. 
We run these tests against test fixtures too as part of our  regular build. 

We should consolidate all these tests into a single job, as there's plenty of capacity on the CI worker to run them in parallel. 

Further more we should create separate tasks  for the different types of tests instead of reusing the existing ones, and have the third party tests talk to vault directly for secrets as we do in the init scripts. 

This will allow us to have a single generic job in CI that just calls something like `./gradlew thirdPartyTest`

This will also make it easier to run these locally as all one needs is to export `VAULT_TOKEN`. 

Somewhat relates to #46813

**Comment by mark-vieira** [comment] 2019-10-16 23:04
@atorok are you suggesting we take this multijob and make it a single job with one build execution?

https://elasticsearch-ci.elastic.co/view/Elasticsearch%20master/job/elastic+elasticsearch+master+third-party-tests/

**Comment by atorok** [comment] 2019-10-17 07:12
Yes, but I would move the accessing of secrets from Vagrant  into the build first, so we can use a generic builder for the new job in CI that would replace the multijob.

**Comment by mark-vieira** [comment] 2019-10-17 20:48
I'm not sure I see the motivation for consolidating a multi-job into a single job. Most of our recent CI efforts involve doing the opposite. One benefit of the granular jobs is that reporting better. For example, if the GCE job fails but others pass that gives us some good indications on the cause. We lose some of this by lumping into a single job. Of course the actual build will tell us what tests fail but I guess I don't completely see why the current state is not ideal.

Are you mainly trying to ditch these custom builders?

https://github.com/elastic/infra/blob/0198dc922ce03387703c6e200f1c39eab20b3947/ci/jjb/elasticsearch-ci/globals/macros/builder.yml#L172-L257

**Comment by atorok** [comment] 2019-10-18 06:53
The main concern is to consolidate the builders. 

I'm ok to leave these as a multi job, but would like to point out that I do think that fewer jobs are better, splitting up the jobs is an unfortunate side effect of the performance optimization we do, but in this case there's plenty of capacity to run this on the same machine in parallel in the same time.  Of course we could further complicate the setup and use smaller workers, but that's the reason I was proposing we consolidate in the first place: to simplify the CI setup. 

Another advantage I see is that we would create a generic third party job, that will allow for others to be added seamlessly.  I'm sure there's other integrations where we would want to test against the real service. If it then becomes too large, we could split it like we currently split `check`, I'm not a fan of dedicated "feature" jobs in CI as  we have right now as  it makes it harder to reason about CI in general.

**Comment by mark-vieira** [comment] 2021-02-08 21:13
I think this will be mostly resolved when we migrate to JJBB/Pipelines so I'm closing this as it's not compelling to be an explicit goal.

**Closed by mark-vieira** 2021-02-08 21:13 UTC
Labels: :Delivery/Build, :Distributed/Snapshot/Restore, >enhancement, Team:Delivery, Team:Distributed
