### ISSUE TITLE
bulk index in node throws "Content-Type header [application/x-ldjson] is not supported" error

### ISSUE THREAD

**Issue by venkkiram** [elastic/elasticsearch#28199] opened 2018-01-12 17:17 UTC
**bulk index in node throws "Content-Type header [application/x-ldjson] is not supported" error**:
--
**Elasticsearch version** : 6.1.1
**JVM version** : 1.8.0_121
**OS version** : Windows 7
**Node version** : v8.5.0

while executing node-elasticsearch-tutorial-master program, I am unable to perform bulk indexing due to unsupported json content type version.

> const bulkIndex = function bulkIndex(index, type, data) {
>     let bulkBody = [];
> 
>     data.forEach(item => {
>       bulkBody.push({
>         index: {
>           _index: index,  _type: type, _id: item.id
>         }
>       });      
>       bulkBody.push(item);
>     });
> 
>     esClient.bulk({body: bulkBody})
>     .then(response => {
>       let errorCount = 0;
>       response.items.forEach(item => {
>         if (item.index && item.index.error) {
>           console.log(++errorCount, item.index.error);
>         }
>       });
>       console.log(`Successfully indexed ${data.length - errorCount} out of ${data.length} items`);
>     })
>     .catch(console.err);
>   };

Execution of node index.js from command prompt gives following error.

<- 406
{
 "error": "Content-Type header [application/x-ldjson] is not supported",
 "status": 406
}

Please advise me the direction to resolve the issue.

**Comment by dadoonet** [comment] 2018-01-12 18:02
I think this should be reported in https://github.com/elastic/elasticsearch-js instead. But make sure first that you are upgrading to the latest version of the JS client.

It's better to keep the discussion at https://discuss.elastic.co/t/node-bulk-indexing-not-working-content-type-header-application-x-ldjson-is-not-supported/114944/2?u=dadoonet. So I'm closing this as it's not a bug in elasticsearch itself.

**Closed by dadoonet** 2018-01-12 18:02 UTC
