### ISSUE TITLE
Mapped Boolean field saving string values

### ISSUE THREAD

**Issue by saurajeet** [elastic/elasticsearch#13382] opened 2015-09-08 00:05 UTC
```
PUT /test_boolean
{   "mappings": {
        "shops": {
            "properties": {
                "shop_type": {
                    "type": "object",
                    "dynamic": "strict",
                    "properties": {
                        "dealer": {"type": "boolean"},
                        "seller": {"type": "boolean"}
                    }
                }
            }
        }
    }
}

# THIS DOC SHOULD GET INDEXED
PUT test_boolean/shops/1
{
    "shop_type": [  
        {   "dealer": true, 
            "seller": false
        }
    ]
}


#THIS DOC SHOULDNOT GET INDEXED. MAPPER EXCEPTION EXPECTED
PUT test_boolean/shops/2
{
    "shop_type": [  
        {   "dealer": true, 
            "seller": "No this not a seller"
        }
    ]
}
```

Tried on latest: 1.7.1

According to my usecase the second document should fail by Mapper Exception telling cannot match string "No this not a seller" to boolean type.

I read though this https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-core-types.html#boolean 
The doc says any string is finally treated as True. But i can see the final persisted doc contains the string as well. 

GET test_boolean/shops/2
```
{
   "_index": "test_boolean",
   "_type": "shops",
   "_id": "2",
   "_version": 1,
   "found": true,
   "_source": {
      "shop_type": [
         {
            "dealer": true,
            "seller": "No this not a seller"
         }
      ]
   }
}
```

Is this a bug or a feature. If a feature, how can i circumvent this problem to enforce my usecase.

**Comment by dadoonet** [comment] 2015-09-08 01:16
Your source document contains the original text but true is indexed.

For example if you search "seller" with a TermQuery on seller field, you won't get it.

Do the same with a String type and you'll get the result.

I think there is an opened issue...

**Comment by jpountz** [comment] 2015-09-08 09:57
See #11503. We use the same logic for parsing booleans in documents and in settings.

**Comment by jpountz** [comment] 2015-09-08 21:33
Closing this issue as a duplicate of #11503.

**Closed by jpountz** 2015-09-08 21:33 UTC
