### ISSUE TITLE
ElasticSearch 5.5 SearchScript - fields cannot be found within segments

### ISSUE THREAD

**Issue by dsafaric** [elastic/elasticsearch#26124] opened 2017-08-09 19:47 UTC
I am in the process of implementing a custom native `SearchScript` that produces a certain score at query execution. Given a term `x` the script should calculate a similarity metric against the set of documents within an index. The search script should be compiled and executed using a `ScriptEngineService` instance. The problem is however that given a field that has been defined explicitly using the mapping endpoint, the field cannot be found within the segment. The source code part of this questions has been posted [here](https://stackoverflow.com/questions/45599401/elasticsearch-5-5-searchscript). Any hint onto why no documents containing the given field cannot be found?

**Comment by costin** [comment] 2017-08-10 11:36
Hi.

Your report looks like a question rather than a bug report. For that it's best to use our [forums](https://www.elastic.co/help) which we actively monitor (more than SO). 
To confirm is there any data actual stored? Even if a mapping is defined, if no data is indexed, no data will be stored (see the isMissing query for example).

P.S. When cross-posting, it helps to reuse the relevant information - such as ES version used, code snippet, etc...

**Comment by jpountz** [comment] 2017-08-10 11:47
I just added a comment on the SO post. Closing since we strive to only use Github for confirmed bugs and feature requests.

**Closed by jpountz** 2017-08-10 11:47 UTC
Labels: :Scripting, feedback_needed
