### ISSUE TITLE
Native (search) script parameters are being overwritten (scripted_metric agg)

### ISSUE THREAD

**Issue by iwhitfield** [elastic/elasticsearch#13131] opened 2015-08-26 23:27 UTC
**Disclaimer**: apologies in advance if it turns out I just did something stupid, but I've been banging my head against it and it makes no sense to me.

Got a weird one here. I'm writing a simple native script for the `scripted_metric` aggregation to group `DocLookup` objects by the `_parent` field of the documents being used. The problem is that the `_agg` object (part of my `params`) is being overwritten somewhere (i.e. not by myself). The fact I know there's a bug here is because if I look at the result set, it tells me that I have **4** `install` events... but I *only* have **3** of them stored inside Elasticsearch. The keys seem to be arbitrarily re-assigned to random values.

As part of my investigation, I decided to log the state of a specific `_parent` key after each run of the script (the `debug_parent` field). Here's what came back:

```
/* 'install' is added to a list assigned to the parent */
[2015-08-27 00:05:22,185][INFO ][mapper                   ] adding [install] to d04caf67-8f6b-49fc-a449-91f3192748c7
/* so this is immediately after on the same run() call */
[2015-08-27 00:05:22,187][INFO ][mapper                   ] [install]
/* on subsequent calls, it's gone, other stuff is there */
[2015-08-27 00:05:22,188][INFO ][mapper                   ] [node-stats-cpu]
[2015-08-27 00:05:22,188][INFO ][mapper                   ] [node-stats-memory]
[2015-08-27 00:05:22,189][INFO ][mapper                   ] [foreground]
[2015-08-27 00:05:22,189][INFO ][mapper                   ] [background]
```

So you can see that something is clearly overwriting my previously stored event names, but the Java should be appending to the previously stored list. 

Here is my native script (it's for a mapping phase).

```java
public class ParentContextProvider implements NativeScriptFactory {

    @Override
    public ExecutableScript newScript(@Nullable Map<String, Object> params) {

        final HashMap<String, List<DocLookup>> _agg
                = (HashMap<String, List<DocLookup>>) params.get("_agg");

        final String debug_parent = "d04caf67-8f6b-49fc-a449-91f3192748c7";

        final Logger logger = Logger.getLogger("mapper");

        return new AbstractSearchScript() {

            @Override
            public Object run() {
                DocLookup doc = doc();

                // only interested in docs with parents
                if (doc.containsKey("_parent")) {

                    // pull out the parent value of the DocLookup object
                    String parent = getStringDocValue(doc, "_parent");

                    // Retrieve either the previous list, or a new and empty list
                    List<DocLookup> tuples = _agg.getOrDefault(parent, Lists.newArrayList());

                    // add the doc to the list
                    tuples.add(doc);

                    // if it's the debug parent, log out what we added
                    if(debug_parent.equals(parent)) {
                        logger.info("adding " + doc.get("event") + " to " + parent);
                    }

                    // overwrite the list in the _agg param
                    _agg.put(parent, tuples);
                }

                // if the _agg has our debug parent
                if(_agg.get(debug_parent) != null) {

                    // create a string joiner
                    StringJoiner s = new StringJoiner(",");

                    // add every 'event' to the string
                    _agg.get(debug_parent).forEach(e -> s.add(e.get("event").toString()));

                     // log the string, this should be all events for that _parent
                     logger.info(s.toString());
                }

                return _agg;
            }

            private String getStringDocValue(DocLookup doc, String key){
                return ((ScriptDocValues.Strings) doc.get(key)).getValue();
            }
        };

    }

}
```

**Comment by iwhitfield** [comment] 2015-08-26 23:33
Also, if you copy the logging of `_agg.get(checkedSid)` to the very start of `run()`, you can see that `event1` is already gone by the time `run()` is next called - so it must be something outside of the script above (unless there's something bizarre with references going on that I'm missing?).

**Comment by clintongormley** [comment] 2015-08-27 11:08
@colings86 could you take a look at this please?

**Comment by colings86** [comment] 2015-08-27 11:56
@iwhitfield Could you post (maybe in a gist) of a Sense or curl recreation of this issue, including the commands for creating the index, indexing the events, and and search request for the scripted metric aggregation that uses your native script above?

**Comment by iwhitfield** [comment] 2015-08-27 15:54
@colings86 I'll dump my index, although I'm not sure the index is the issue, let me get back to you ASAP.

**Comment by colings86** [comment] 2015-08-27 15:57
@iwhitfield no, I don't think the index is the issue either but having the curl recreation will make it alot easier to reproduce the issue and work out whats going on

**Comment by iwhitfield** [comment] 2015-08-27 15:59
@colings86 sure thing, I'll get that to you - I just have to remove some private info in there, but I'll get it to you shortly.

**Comment by colings86** [comment] 2015-08-27 16:00
@iwhitfield ok great, thanks :)

**Comment by iwhitfield** [comment] 2015-08-27 17:28
@colings86 ok here's a gist - I hope I got everything you need: https://gist.github.com/iwhitfield/86b3193280bdd1d4edf2

I decided to keep the names as-is, rather than rename them to "eventX" because it'd just make it harder for you to read :)

`raw_data_dump.json` can be loaded by https://github.com/taskrabbit/elasticsearch-dump if you have it accessible to you, otherwise `raw_data_sense.txt` should be a file you can just load up into Sense (let me know if I did that wrong, though).

`test_curl.txt` is just the curl query I have been testing with. Although I don't think it's relevant, I'll note that I also had a combiner and reducer in most of my testing, but I narrowed it down to the mapping phase being the issue and so I have removed those from the curl (i.e. the logs in the OP prove it's a mapping issue).

Your help is much appreciated, let me know if I can do anything else to point you in a helpful direction - I've kept the index around that displays this issue, so I can run anything you like on it. Also, it appears that the keys and values are not mixed up at random - subsequent runs will always show the same progression as shown in the logs above, so maybe it's to do with some sort-of-random-but-with-some-logic-to-it Lucene thing :D

**Comment by iwhitfield** [comment] 2015-08-27 23:36
Have verified that this is the case consistently after reloading an index on my installation of ES1.7.1, and on another installation of ES1.6.1. So @colings86, you should be able to replicate with my dataset and script.

**Comment by colings86** [comment] 2015-08-28 12:16
@iwhitfield Sorry, it took me a little while to realise what the code in your script is doing. 

You are trying to store the DocLookup object in your `_agg` object but this will not work. This object does not represent a particular document, it is an object that can be used to access particular fields for the current document. When the aggregation moves onto the next document the DocLookup object stayed the same (you can see this as it has the same object id) but now calls to DocLookup will return values for the next document. This is why you are seeing this strange behaviour. 

You will need to change your script to retrieve the values that you need for each document (it looks like this is the value of `event` in your script above) and store that value in your `_agg` object rather than trying to store the DocLookup object.

I am going to close this issue as Elasticsearch it working correctly here.

**Closed by colings86** 2015-08-28 12:16 UTC
Labels: :Aggregations, discuss, feedback_needed

**Comment by iwhitfield** [comment] 2015-08-28 14:25
@colings86 that makes perfect sense, thank you for summing it up so quickly :) I knew it must be something with the way things are referenced. Thank you!
