### ISSUE TITLE
[CI] SearchableSnapshotsIntegTests testMaxRestoreBytesPerSecIsUsed failing

### ISSUE THREAD

**Issue by slobodanadamovic** [elastic/elasticsearch#94277] opened 2023-03-02 11:12 UTC
**Build scan:**
https://gradle-enterprise.elastic.co/s/rrbr7cc3ka7wa/tests/:x-pack:plugin:searchable-snapshots:internalClusterTest/org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests/testMaxRestoreBytesPerSecIsUsed

**Reproduction line:**
```
./gradlew ':x-pack:plugin:searchable-snapshots:internalClusterTest' --tests "org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests.testMaxRestoreBytesPerSecIsUsed" -Dtests.seed=1DF63FBE262BEEE -Dtests.locale=pt-BR -Dtests.timezone=America/Yakutat -Druntime.java=17
```

**Applicable branches:**
8.6

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests&tests.test=testMaxRestoreBytesPerSecIsUsed

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: a value greater than <0L>
     but: <0L> was equal to <0L>

  at __randomizedtesting.SeedInfo.seed([1DF63FBE262BEEE:2C8B91E9D0FD49BC]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests.testMaxRestoreBytesPerSecIsUsed(SearchableSnapshotsIntegTests.java:510)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by volodk85** [comment] 2023-05-05 18:40
Hi there,
Was not able to reproduce locally neither on 8.6 branch (tip commit: [8b86071]) nor on current main. Ran test for 100 times both for *seed* and *seedless* mode. Closing.

```
date
Fri  5 May 2023 11:38:06 PDT

./gradlew ':x-pack:plugin:searchable-snapshots:internalClusterTest' --tests "org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests.testMaxRestoreBytesPerSecIsUsed" -Dtests.seed=1DF63FBE262BEEE -Dtests.locale=pt-BR -Dtests.timezone=America/Yakutat -Dtests.iters=100
=======================================
Elasticsearch Build Hamster says Hello!
  Gradle Version        : 7.6.1
  OS Info               : Mac OS X 13.3.1 (x86_64)
  JDK Version           : 17.0.6+10-LTS (Azul Zulu)
  JAVA_HOME             : /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
  Random Testing Seed   : 1DF63FBE262BEEE
  In FIPS 140 mode      : false
=======================================
...
BUILD SUCCESSFUL in 2m 37s

./gradlew ':x-pack:plugin:searchable-snapshots:internalClusterTest' --tests "org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests.testMaxRestoreBytesPerSecIsUsed" -Dtests.locale=pt-BR -Dtests.timezone=America/Yakutat -Dtests.iters=100 
=======================================
Elasticsearch Build Hamster says Hello!
  Gradle Version        : 7.6.1
  OS Info               : Mac OS X 13.3.1 (x86_64)
  JDK Version           : 17.0.6+10-LTS (Azul Zulu)
  JAVA_HOME             : /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
  Random Testing Seed   : FD989CE23F4C4315
  In FIPS 140 mode      : false
=======================================
...
BUILD SUCCESSFUL in 2m 49s
```

**Comment by henningandersen** [comment] 2023-05-11 08:40
This test [failed only 3 times](https://ci-stats.elastic.co/s/jenkins/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1y,to:now))&_a=(columns:!(),filters:!(),index:'8aa88c00-417a-11ec-bdd9-bfc2b0e3b79b',interval:auto,query:(language:kuery,query:testMaxRestoreBytesPerSecIsUsed),sort:!(!(time,desc)))) over the last year. I think running it 2x100 times is not enough to conclude that it is gone.

**Comment by pxsalehi** [comment] 2023-05-11 08:46
Does running
```
./gradlew ':x-pack:plugin:searchable-snapshots:internalClusterTest' --tests "org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests.testMaxRestoreBytesPerSecIsUsed" -Dtests.seed=1DF63FBE262BEEE -Dtests.locale=pt-BR -Dtests.timezone=America/Yakutat -Dtests.iters=100
```
w/o adding `-Dtests.rand=$RANDOM` would actually run the test 100 times?

**Comment by volodk85** [comment] 2023-06-10 04:31
Checked 5 latest failures. All of them are failing on `useRateLimits == false` condition, meaning that test was instructed to disable rate limiting but it happened anyway

https://github.com/elastic/elasticsearch/blob/cdabe88242d93030444f77943c4e0ea0066f0527/x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/SearchableSnapshotsIntegTests.java#L506-L509

```
13:41:57     Expected: <0L>
13:41:57          but: was <33075429L>
13:41:57         at __randomizedtesting.SeedInfo.seed([F5CDB138FAA960D3:D899432AC8369781]:0)
13:41:57         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
13:41:57         at org.junit.Assert.assertThat(Assert.java:956)
13:41:57         at org.junit.Assert.assertThat(Assert.java:923)
13:41:57         at org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests.testMaxRestoreBytesPerSecIsUsed(SearchableSnapshotsIntegTests.java:506)
```

Why it happens?

Recovery uses augmented `InputStream` which is guarded by **TWO** rate limiters and **ONE** callback listener. When any of rate limiter engage, the listener gets invoked.  

https://github.com/elastic/elasticsearch/blob/6d72e5c5d05b72073f25d0f461171adb7bfea6d0/server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java#L3138-L3144

Currently test disables only one (configured in BlobStoreRepository) rate limiter leaving the second (comes from RecoverySettings) intact. Fix would be disabling the second rate limiter whilst keep asserting zero throttling callback invokes.

**Comment by volodk85** [comment] 2023-06-10 04:35
> Checked 5 latest failures. All of them are failing on `useRateLimits == false` condition, meaning that test was instructed to disable rate limiting but it happened anyway
> 
> https://github.com/elastic/elasticsearch/blob/cdabe88242d93030444f77943c4e0ea0066f0527/x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/SearchableSnapshotsIntegTests.java#L506-L509
> 
> ```
> 13:41:57     Expected: <0L>
> 13:41:57          but: was <33075429L>
> 13:41:57         at __randomizedtesting.SeedInfo.seed([F5CDB138FAA960D3:D899432AC8369781]:0)
> 13:41:57         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
> 13:41:57         at org.junit.Assert.assertThat(Assert.java:956)
> 13:41:57         at org.junit.Assert.assertThat(Assert.java:923)
> 13:41:57         at org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests.testMaxRestoreBytesPerSecIsUsed(SearchableSnapshotsIntegTests.java:506)
> ```
> 
> Why it happens?
> 
> Recovery uses augmented `InputStream` which is guarded by **TWO** rate limiters and **ONE** callback listener. When any of rate limiter engage, the listener gets invoked.
> 
> https://github.com/elastic/elasticsearch/blob/6d72e5c5d05b72073f25d0f461171adb7bfea6d0/server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java#L3138-L3144
> 
> Currently test disables only one (configured in BlobStoreRepository) rate limiter leaving the second (comes from RecoverySettings) intact. Fix would be disabling the second rate limiter whilst keep asserting zero throttling callback invokes.

**Closed** 2023-06-12 17:05 UTC
Labels: :Distributed/Snapshot/Restore, >test-failure, Team:Distributed
