### ISSUE TITLE
Latitude and longitude are returned when requesting geohash sub field

### ISSUE THREAD

**Issue by dmfenton** [elastic/elasticsearch#11841] opened 2015-06-24 01:54 UTC
### The problem

I'm trying to access the raw geohash per the [documentation here](https://www.elastic.co/guide/en/elasticsearch/reference/1.6/mapping-geo-point-type.html), but it's not returning what I expect. Please forgive me if this is user error.
### Background

What I _really_ want to do is count of the unique geohashes at a given level of precision, but there's doesn't seem to be a way to do that easily so here I am.
### Basics

``` json
{
  "status" : 200,
  "name" : "Soulfire",
  "cluster_name" : "elasticsearch1",
  "version" : {
    "number" : "1.6.0",
    "build_hash" : "cdd3ac4dde4f69524ec0a14de3828cb95bbb86d0",
    "build_timestamp" : "2015-06-09T13:36:34Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
```
### Mapping

``` json

{
  "koop_geohash" : {
    "mappings" : {
      "features" : {
        "properties" : {
          "centroid" : {
            "type" : "geo_point",
            "geohash" : true,
            "geohash_prefix" : true,
            "geohash_precision" : 8
          }
        }
      }
    }
  }
}
```
### Query

``` json
{
    "query":{
        "match_all": {}
    },
    "size": 1,
    "fields": ["centroid.geohash"]
}
```
### Response

``` json
{
  "took": 39,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 89,
    "max_score": 1,
    "hits": [
      {
        "_index": "koop_geohash",
        "_type": "features",
        "_id": "AU4jL53QJUVxb01NyiaD",
        "_score": 1,
        "fields": {
          "centroid.geohash": [
            -80.23283572892831,
            38.81329972121544
          ]
        }
      }
    ]
  }
}
```

**Comment by clintongormley** [comment] 2015-06-24 14:05
Hi @dmfenton 

The geohash would need to be stored in order to be accessible, but there seems to be no way to set it to stored, eg with this mapping:

        "centroid": {
          "type": "geo_point",
          "geohash": true,
          "geohash_prefix": true,
          "geohash_precision": 8,
          "store": true
        }

this request:

    GET _mapping/field/centroid*?include_defaults

returns

           "centroid": {
               "full_name": "centroid",
               "mapping": {
                  "centroid": {
                     "type": "geo_point",
                     "boost": 1,
                     "index": "not_analyzed",
                     "store": true,
                     "doc_values": false,
                     "term_vector": "no",
                     "norms": {
                        "enabled": false
                     },
                     "index_options": "docs",
                     "analyzer": "_keyword",
                     "similarity": "default",
                     "fielddata": {},
                     "path": "full",
                     "lat_lon": false,
                     "geohash": true,
                     "geohash_prefix": true,
                     "geohash_precision": 8,
                     "validate": true,
                     "normalize": true
                  }
               }
            }

@nknize would exposing the ability to set the geohash as stored make sense?

**Comment by dmfenton** [comment] 2015-06-24 14:11
Thanks @clintongormley. Just want to draw attention to my real use case.

As a user, I want to know how many unique geohashes will be returned for a given filtered aggregation, without transporting all the data over the wire.

Even better,

As a user, I want to know at which precision level will a geohash aggregation for a given filter contain fewer than x unique geohashes.

**Comment by talevy** [comment] 2018-03-15 20:58
I believe the behavior has slightly changed over time. Today this is the expected behavior:

https://github.com/elastic/elasticsearch/issues/28875#issuecomment-370891928

Closing

**Closed by talevy** 2018-03-15 20:58 UTC
Labels: :Search/Geo, discuss

**Comment by dmfenton** [comment] 2018-03-15 21:19
@talevy That wasn't a very helpful closing message. I don't see anything in that comment that shows the ability to aggregate or return a calculated geohash.

**Comment by talevy** [comment] 2018-03-15 21:25
@dmfenton I apologize I misunderstood the original intent of this issue.

There is no auto-tuning of precision that is available, but by running a cardinality aggregation
on the keyword-valued geohash multifields (potentially scripted to check cardinality against each precision 1-12) to find out how many buckets you expect

**Comment by dmfenton** [comment] 2018-03-15 21:28
@talevy thank you very much for the follow up. Can I actually return the calculated geohash from the source document?

**Comment by talevy** [comment] 2018-03-15 21:37
@dmfenton 
this is what I meant

calculating expected number of buckets per-precision for geohashes:
```
GET geohash_agg_test/location/_search
{
  "size": 0,
  "aggs": {
    "my_hack": {
      "cardinality": {
        "script": {
        "source": "doc['gisPoint.geohash'].value.substring(0, params.precision)",
        "params": {
          "precision": 1
        }
        }
      }
    }
  }
}
```

If you would like to retrieve the geohash, you must update the example mapping to explicitly [store](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/mapping-store.html) the value of `gisPoint.geohash`

example:

```
PUT geohash_agg_test
{
  "mappings": {
    "location": {
      "properties": {
        "gisPoint": {
          "type": "geo_point",
          "fields": {
            "geohash": {
              "store": true,
              "type": "keyword"
            }
          }
        }
      }
    }
  }
}

// retrieving the value

GET geohash_agg_test/location/_search
{
  "size": 1,
  "stored_fields": ["gisPoint.geohash"], 
  "query": {
    "match": {
      "_id": 1
    }
  }
}
```

**Comment by talevy** [comment] 2018-03-15 21:38
Let me know if that answers your questions! once again, I apologize for the incorrect evaluation of this issue when closing
