### ISSUE TITLE
max_shards_in_cluster is not properly calculated from max_shards_per_node

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/elasticsearch#96219] opened 2023-05-18 12:17 UTC
### Elasticsearch Version

8.6.0, 8.7.0, 8.8.0, 8.9.0

### Installed Plugins

ESS default

### Java Version

ESS default

### OS Version

ESS default

### Problem Description

Our clusters hit continuously the following error on ESS

It is related to the number of shards per cluster `max_shards_in_cluster` that is calculated based on `max_shards_per_node` but is not correctly calculated, our value for `max_shards_per_node` is 10000. We have 10 data nodes, so we have configured more than 7000 shards per cluster for sure. No matter the value you put on `max_shards_per_node`, we cannot have more than 7000 shards in our clusters.

![image](https://github.com/elastic/elasticsearch/assets/5400788/b32b3025-6c49-4ea8-a793-3a3d8ff0d300)

```
      "shards_capacity" : {
        "status" : "Red",
        "symptom" : "Cluster is close to reaching the configured maximum number of shards for data nodes.",
        "details" : {
          "data" : {
            "max_shards_in_cluster" : 7000,
            "current_used_shards" : 9023
```

```
{
  "status": "green",
  "number_of_nodes": 10,
  "unassigned_shards": 0,
  "number_of_pending_tasks": 2,
  "number_of_in_flight_fetch": 0,
  "timed_out": false,
  "active_primary_shards": 5185,
  "task_max_waiting_in_queue_millis": 600,
  "cluster_name": "0000000000000000000000000",
  "relocating_shards": 0,
  "active_shards_percent_as_number": 100,
  "active_shards": 9753,
  "initializing_shards": 0,
  "number_of_data_nodes": 7,
  "delayed_unassigned_shards": 0
}
```

Probably related to https://github.com/elastic/elasticsearch/issues/91119

### Steps to Reproduce

* Deploy a cluster with Elastic Stack 8.7.0
* Create more than 7000 shards
* Change the value of `max_shards_per_node` to 5000
* Wait until the error appears again

**Comment by DaveCTurner** [comment] 2023-05-18 12:38
>  `"number_of_data_nodes": 7,`

Apparently you have 7 data nodes, so 7000 is the right limit.

**Comment by kuisathaverat** [comment] 2023-05-18 12:40
If I have `max_shards_per_node` to 5000 `max_shards_in_cluster` number should be `7*5000`, isn't it?

**Comment by HiDAl** [comment] 2023-05-29 08:00
Hi @kuisathaverat 

I've created a cluster to test this and it was impossible to replicate the issue. 
Looking at the shared settings and `_cluster/health` API response, I've some questions:

1. Do you have frozen nodes in this cluster? Frozen nodes are added up as part of the `_cluster/health API > number_of_data_nodes` total, but, for this indicator, they are not counted to calculate the number of total shards ([Documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/troubleshooting-shards-capacity-issues.html#_cluster_is_close_to_reaching_the_configured_maximum_number_of_shards_for_data_nodes)). 
Please share the response of `GET _nodes/stats/?filter_path=nodes.*.roles`. Anyway, looking at the value `max_shards_in_cluster = 7000` and `number_of_data_nodes = 7` makes me think that you don't have frozen nodes, and `max_shards_per_node` is configured to the default value of 1000.

2. Can you share the current `cluster.max_shard_per_node & cluster.max_shard_per_node.frozen`  values? `GET _cluster/settings?&include_defaults=true&filter_path=defaults.cluster.max_shards_per_node*`

3. > If I have `max_shards_per_node` to 5000 `max_shards_in_cluster` number should be 7*5000, isn't it?

Yes, it should be 7 * 5000, **only** if you have 7 nodes that **are not part** of the frozen tier

Looking forward to your comments

**Comment by kuisathaverat** [comment] 2023-05-30 07:31
>Do you have frozen nodes in this cluster? Frozen nodes are added up as part of the _cluster/health API > number_of_data_nodes total, but, for this indicator, they are not counted to calculate the number of total shards ([Documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/troubleshooting-shards-capacity-issues.html#_cluster_is_close_to_reaching_the_configured_maximum_number_of_shards_for_data_nodes)).

no, we have hot (2 days), warm(7 days), and cold(180 days) nodes, we keep 180 days of data 5TB. 

GET _nodes/stats/?filter_path=nodes.*.roles

````
{
  "nodes": {
    "5eyRgQm3SoK58pD-mTgPjw": {
      "roles": [
        "data_content",
        "data_hot",
        "ingest",
        "remote_cluster_client",
        "transform"
      ]
    },
    "Gy3LWuXcRNWdvsmjKk9prw": {
      "roles": [
        "master",
        "remote_cluster_client"
      ]
    },
    "jsl9ndBFSOOiFF-G0YPBng": {
      "roles": [
        "data_cold",
        "remote_cluster_client"
      ]
    },
    "SQCU0bQvSVOELKMvRr5GAA": {
      "roles": [
        "data_warm",
        "remote_cluster_client"
      ]
    },
    "dvozxgiYRUucFiolj8sjNg": {
      "roles": [
        "data_content",
        "data_hot",
        "ingest",
        "remote_cluster_client",
        "transform"
      ]
    },
    "L5Ddf4-YRCCc1SiMCSFL0w": {
      "roles": [
        "ml",
        "remote_cluster_client"
      ]
    },
    "L98OCh_XQQqcZUf5GeXgVA": {
      "roles": [
        "data_warm",
        "remote_cluster_client"
      ]
    },
    "6n7HR-vPQjKyFX8x5pJTzA": {
      "roles": [
        "master",
        "remote_cluster_client"
      ]
    },
    "kBBFMM7-TKufltVSl_Bz-Q": {
      "roles": [
        "data_cold",
        "remote_cluster_client"
      ]
    },
    "Lr6P2ZVbSQy65SBGgk5WnQ": {
      "roles": [
        "data_content",
        "data_hot",
        "ingest",
        "remote_cluster_client",
        "transform"
      ]
    },
    "4xl6oDQOQEGUe-XcIq33sQ": {
      "roles": [
        "master",
        "remote_cluster_client"
      ]
    }
  }
}
```


GET _cluster/settings?&include_defaults=true&filter_path=defaults.cluster.max_shards_per_node*

```
{
  "defaults": {
    "cluster": {
      "max_shards_per_node.frozen": "3000",
      "max_shards_per_node": "1000"
    }
  }
}
```

^^after this call I tried to change the value again, and the response changed, I used this call

```
PUT /_cluster/settings
{
  "persistent": {
    "cluster.max_shards_per_node": "1500"
  }
}
```

Then I rerun the previous call to get the setting, and `max_shards_per_node` has disappeared.

GET _cluster/settings?&include_defaults=true&filter_path=defaults.cluster.max_shards_per_node*
```
{
  "defaults": {
    "cluster": {
      "max_shards_per_node": {
        "frozen": "3000"
      }
    }
  }
}
```

I guess this is the reason why when I make that REST call the issue disappear for a while

**Comment by kuisathaverat** [comment] 2023-05-30 09:09
>are you saying that you previously changed the max_shards_per_node setting? wasn't it persisted in the cluster?

Yes, we increased it to `max_shards_per_node=2000` a few months ago, we did it several times until we realized that no matter the value of that parameter, we cannot have more `max_shards_in_cluster =date_nodes*1000`

>why do you say, "for a while"?

When we see the error in the cluster, we set a bigger `max_shards_per_node`. This makes the error disappear from the ESS UI for minutes/hours (I am not sure) but appears again after a while if we are over the `max_shards_in_cluster =date_nodes*1000`. Last time before opening this issue we set `max_shards_per_node=15000` to be sure something weird happens

**Comment by HiDAl** [comment] 2023-05-30 09:40
According to our private conversation, it's highly probable that the issue is within the setting value rather than the indicator itself. @kuisathaverat has fully restarted the cluster but the settings weren't restored to `1000`, so we have no idea what could be happening. Ivan will continue monitoring the cluster in case the setting is reverted.

**Comment by HiDAl** [comment] 2023-05-30 10:04
marking as `>non-issue` but will keep it open for a couple of days just in case

**Comment by kuisathaverat** [comment] 2023-06-06 10:36
So far no changes, if the next week we do not see the issue again, we will close it.

**Comment by HiDAl** [comment] 2023-06-12 08:12
Hey, @kuisathaverat! any change last week? if no, can you close the issue? thanks

**Comment by kuisathaverat** [comment] 2023-06-12 09:08
I just checked this morning. We have reached 7000 shards in one of the clusters, and the error is activated, and it should not because we have 7 data nodes and 1500 shards per node configured (10500 per cluster)

```
{
  "status": "green",
  "number_of_nodes": 11,
  "unassigned_shards": 0,
  "number_of_pending_tasks": 1,
  "number_of_in_flight_fetch": 0,
  "timed_out": false,
  "active_primary_shards": 3546,
  "task_max_waiting_in_queue_millis": 0,
  "cluster_name": "REDACTED",
  "relocating_shards": 0,
  "active_shards_percent_as_number": 100,
  "active_shards": 7054,
  "initializing_shards": 0,
  "number_of_data_nodes": 7,
  "delayed_unassigned_shards": 0
}
```

```
{
  "persistent": {
    "cluster": {
      "max_shards_per_node": "1500"
    }
  }
}
```

**Comment by HiDAl** [comment] 2023-06-12 13:05
Looking at other clusters, I found another cluster with the same issue:

The indicator has a value of `1000` as the metadata (7 * 1000): 

 ![Screenshot 2023-06-12 at 14 45 51](https://github.com/elastic/elasticsearch/assets/284537/449885a0-19cf-4735-865c-4d9d899a2765)


but the actual metadata is configured to `1500`: 
![Screenshot 2023-06-12 at 14 45 38](https://github.com/elastic/elasticsearch/assets/284537/922c6dd8-fe53-4ab3-8d18-5e8aba972d33)

something is happening with the service in charge of refresh the setting value within the cluster state.

**Closed** 2023-06-15 13:24 UTC
Labels: >bug, Team:Data Management, :Data Management/Health, v8.9.0, v8.8.2
