### ISSUE TITLE
http.cors ES 2.3

### ISSUE THREAD

**Issue by chanserv** [elastic/elasticsearch#17534] opened 2016-04-05 10:14 UTC
**Elasticsearch version**:
2.3
**JVM version**:
1.8.0
**OS version**:
Windows 7
**Description of the problem including expected versus actual behavior**:
I have set cors conf in elasticsearch.yml like this
`http.cors.enabled : true
http.cors.allow-origin : "*"
http.cors.allow-methods : OPTIONS, HEAD, GET, POST, PUT, DELETE
http.cors.allow-headers : X-Requested-With,X-Auth-Token,Content-Type, Content-Length`

When requesting elasticsearch from file:///C:/elastic/index.html i got the following error
`Request header field Content-Type is not allowed by Access-Control-Allow-Headers`

I switched to 2.2 version and i set the same parameters and it works like a charm

**Steps to reproduce**:
 1.Set cors parameters in elasticsearch.yml
 2.Request elasticsearch from an url like this: file:///c:/..

**Comment by pciccarese** [comment] 2016-04-05 13:05
I believe this is similar to this: 
https://github.com/elastic/elasticsearch/issues/17483

**Comment by clintongormley** [comment] 2016-04-06 11:12
Closing as duplicate of #17483.

**Closed by clintongormley** 2016-04-06 11:12 UTC
