### ISSUE TITLE
[CI] DocsClientYamlTestSuiteIT test {yaml=reference/cluster/nodes-info/line_283} failing

### ISSUE THREAD

**Issue by pxsalehi** [elastic/elasticsearch#91444] opened 2022-11-09 09:29 UTC
**Build scan:**
https://gradle-enterprise.elastic.co/s/si3ghqjivcbfc/tests/:docs:yamlRestTest/org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT/test%20%7Byaml=reference%2Fcluster%2Fnodes-info%2Fline_283%7D

**Reproduction line:**
`./gradlew ':docs:yamlRestTest' --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/cluster/nodes-info/line_283}" -Dtests.seed=E26D2664BF3F6922 -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dtests.locale=fr -Dtests.timezone=Asia/Jerusalem -Druntime.java=17`

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT&tests.test=test%20%7Byaml%3Dreference/cluster/nodes-info/line_283%7D

**Failure excerpt:**
```
java.lang.AssertionError: Failure at [reference/cluster/nodes-info:124]: Expected a map containing
acknowledged: expected <true> but was <missing>
      _nodes: <unexpected> but was <{total=1, successful=1, failed=0}>
cluster_name: <unexpected> but was "yamlRestTest"
       nodes: <unexpected> but was <{jPmkYMccSki_j1dnWbMK7Q={name=node-0, transport_address=127.0.0.1:38257, host=127.0.0.1, ip=127.0.0.1, version=8.6.0, build_flavor=default, build_type=tar, build_hash=8d5519da742d6344e9ab9c7477a9ff9256e1fbec, roles=[data, data_cold, data_content, data_frozen, data_hot, data_warm, ingest, master, ml, remote_cluster_client, transform], attributes={xpack.installed=true, ml.max_jvm_size=536870912, ml.allocated_processors=32, testattr=test, ml.allocated_processors_double=32.0, ml.machine_memory=101250138112}, ingest={processors=[{type=append}, {type=attachment}, {type=bytes}, {type=circle}, {type=community_id}, {type=convert}, {type=csv}, {type=date}, {type=date_index_name}, {type=dissect}, {type=dot_expander}, {type=drop}, {type=enrich}, {type=fail}, {type=fingerprint}, {type=foreach}, {type=geoip}, {type=grok}, {type=gsub}, {type=html_strip}, {type=inference}, {type=join}, {type=json}, {type=kv}, {type=lowercase}, {type=network_direction}, {type=pipeline}, {type=registered_domain}, {type=remove}, {type=rename}, {type=script}, {type=set}, {type=set_security_user}, {type=sort}, {type=split}, {type=trim}, {type=uppercase}, {type=uri_parts}, {type=urldecode}, {type=user_agent}]}}}>

  at __randomizedtesting.SeedInfo.seed([E26D2664BF3F6922:6A3919BE11C304DA]:0)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:510)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:479)
  at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(null:-1)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

  Caused by: java.lang.AssertionError: Expected a map containing
  acknowledged: expected <true> but was <missing>
        _nodes: <unexpected> but was <{total=1, successful=1, failed=0}>
  cluster_name: <unexpected> but was "yamlRestTest"
         nodes: <unexpected> but was <{jPmkYMccSki_j1dnWbMK7Q={name=node-0, transport_address=127.0.0.1:38257, host=127.0.0.1, ip=127.0.0.1, version=8.6.0, build_flavor=default, build_type=tar, build_hash=8d5519da742d6344e9ab9c7477a9ff9256e1fbec, roles=[data, data_cold, data_content, data_frozen, data_hot, data_warm, ingest, master, ml, remote_cluster_client, transform], attributes={xpack.installed=true, ml.max_jvm_size=536870912, ml.allocated_processors=32, testattr=test, ml.allocated_processors_double=32.0, ml.machine_memory=101250138112}, ingest={processors=[{type=append}, {type=attachment}, {type=bytes}, {type=circle}, {type=community_id}, {type=convert}, {type=csv}, {type=date}, {type=date_index_name}, {type=dissect}, {type=dot_expander}, {type=drop}, {type=enrich}, {type=fail}, {type=fingerprint}, {type=foreach}, {type=geoip}, {type=grok}, {type=gsub}, {type=html_strip}, {type=inference}, {type=join}, {type=json}, {type=kv}, {type=lowercase}, {type=network_direction}, {type=pipeline}, {type=registered_domain}, {type=remove}, {type=rename}, {type=script}, {type=set}, {type=set_security_user}, {type=sort}, {type=split}, {type=trim}, {type=uppercase}, {type=uri_parts}, {type=urldecode}, {type=user_agent}]}}}>

    at org.elasticsearch.test.MapMatcher.assertMap(MapMatcher.java:82)
    at org.elasticsearch.test.MapMatcher.assertMap(MapMatcher.java:65)
    at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:94)
    at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:65)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:499)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:479)
    at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(null:-1)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:568)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
    at java.lang.Thread.run(Thread.java:833)

```

**Comment by pxsalehi** [comment] 2022-11-09 09:31
I might be wrong with the area label. Feel free to re-label it.

**Comment by pxsalehi** [comment] 2022-11-09 11:06
The test is not muted!

**Comment by thecoop** [comment] 2022-11-10 14:28
Looks like an issue with the doc examples

**Comment by astefan** [comment] 2022-11-16 14:32
Another failure today: https://gradle-enterprise.elastic.co/s/62nn5bpmex6ia
Doesn't repro locally.

```
  2> java.lang.AssertionError: Failure at [reference/cluster/nodes-info:124]: Expected a map containing
    acknowledged: expected <true> but was <missing>
          _nodes: <unexpected> but was <{total=1, successful=1, failed=0}>
    cluster_name: <unexpected> but was "yamlRestTest"
           nodes: <unexpected> but was <{9_CcmxjKSwK499e1v9xfBw={name=node-0, transport_address=127.0.0.1:46699, host=127.0.0.1, ip=127.0.0.1, version=8.5.2, build_flavor=default, build_type=tar, build_hash=44421ff8d42ff41a483df5f95a0c86021335f4ce, roles=[data, data_cold, data_content, data_frozen, data_hot, data_warm, ingest, master, ml, remote_cluster_client, transform], attributes={ml.allocated_processors=32, ml.max_jvm_size=536870912, xpack.installed=true, ml.machine_memory=101250138112, ml.allocated_processors_double=32.0, testattr=test}, ingest={processors=[{type=append}, {type=attachment}, {type=bytes}, {type=circle}, {type=community_id}, {type=convert}, {type=csv}, {type=date}, {type=date_index_name}, {type=dissect}, {type=dot_expander}, {type=drop}, {type=enrich}, {type=fail}, {type=fingerprint}, {type=foreach}, {type=geoip}, {type=grok}, {type=gsub}, {type=html_strip}, {type=inference}, {type=join}, {type=json}, {type=kv}, {type=lowercase}, {type=network_direction}, {type=pipeline}, {type=registered_domain}, {type=remove}, {type=rename}, {type=script}, {type=set}, {type=set_security_user}, {type=sort}, {type=split}, {type=trim}, {type=uppercase}, {type=uri_parts}, {type=urldecode}, {type=user_agent}]}}}>
        at __randomizedtesting.SeedInfo.seed([E298925916CAE3F4:6ACCAD83B8368E0C]:0)
        at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:510)
        at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:479)
        at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
        at java.base/java.lang.Thread.run(Thread.java:833)

        Caused by:
        java.lang.AssertionError: Expected a map containing
        acknowledged: expected <true> but was <missing>
              _nodes: <unexpected> but was <{total=1, successful=1, failed=0}>
        cluster_name: <unexpected> but was "yamlRestTest"
               nodes: <unexpected> but was <{9_CcmxjKSwK499e1v9xfBw={name=node-0, transport_address=127.0.0.1:46699, host=127.0.0.1, ip=127.0.0.1, version=8.5.2, build_flavor=default, build_type=tar, build_hash=44421ff8d42ff41a483df5f95a0c86021335f4ce, roles=[data, data_cold, data_content, data_frozen, data_hot, data_warm, ingest, master, ml, remote_cluster_client, transform], attributes={ml.allocated_processors=32, ml.max_jvm_size=536870912, xpack.installed=true, ml.machine_memory=101250138112, ml.allocated_processors_double=32.0, testattr=test}, ingest={processors=[{type=append}, {type=attachment}, {type=bytes}, {type=circle}, {type=community_id}, {type=convert}, {type=csv}, {type=date}, {type=date_index_name}, {type=dissect}, {type=dot_expander}, {type=drop}, {type=enrich}, {type=fail}, {type=fingerprint}, {type=foreach}, {type=geoip}, {type=grok}, {type=gsub}, {type=html_strip}, {type=inference}, {type=join}, {type=json}, {type=kv}, {type=lowercase}, {type=network_direction}, {type=pipeline}, {type=registered_domain}, {type=remove}, {type=rename}, {type=script}, {type=set}, {type=set_security_user}, {type=sort}, {type=split}, {type=trim}, {type=uppercase}, {type=uri_parts}, {type=urldecode}, {type=user_agent}]}}}>
            at org.elasticsearch.test.MapMatcher.assertMap(MapMatcher.java:82)
            at org.elasticsearch.test.MapMatcher.assertMap(MapMatcher.java:65)
            at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:94)
            at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:65)
            at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:499)
            ... 38 more
```

**Comment by davidkyle** [comment] 2022-11-16 14:40
I believe this is a duplicate of #87591 and appears to main occur on Ubuntu (as the failures here do)

Closing in favour of #87591, please reopen if I am incorrect

**Closed by davidkyle** 2022-11-16 14:40 UTC
Labels: >docs, :Core/Infra/Core, >test-failure, Team:Core/Infra, Team:Docs
