### ISSUE TITLE
BigArray memory leaking

### ISSUE THREAD

**Issue by xjtushilei** [elastic/elasticsearch#91949] opened 2022-11-28 08:30 UTC
### Elasticsearch Version

6.x

### Java Version

8

### OS Version

linux

### Problem Description

According to https://github.com/elastic/elasticsearch/pull/64744 , there are similar memory leaks in other places.
 
For example, in AvgAggregator,   if  allocate `counts` successfully, but  allocate `sums` unsuccessfully, who will release the memory of `counts` ?

### Steps to Reproduce

see in `Description`

**Comment by wchaparro** [comment] 2022-12-08 13:50
Please upgrade to at least 7.17 version (8.x preferred) to get these fixes.

**Comment by DaveCTurner** [comment] 2022-12-08 16:53
@wchaparro I think this is a legit resource leak bug that still exists in `main` today:

https://github.com/elastic/elasticsearch/blob/d1ba276587dd033120240a74a6a83f1f372fbd4a/server/src/main/java/org/elasticsearch/search/aggregations/metrics/AvgAggregator.java#L51-L53

If e.g. we hit a circuit breaker exception when constructing `compensations` we will leak the other two arrays. We should fix it in 7.x and 8.x (although ofc not 6.x).

**Comment by martijnvg** [comment] 2022-12-08 16:59
Thanks @DaveCTurner for re-opening this. I missed that it is still an issue in main.

**Comment by iverase** [comment] 2022-12-08 19:56
@DaveCTurner Upon calling `super` in the constructor, the object gets register in the aggregation context here: 

https://github.com/elastic/elasticsearch/blob/d1ba276587dd033120240a74a6a83f1f372fbd4a/server/src/main/java/org/elasticsearch/search/aggregations/AggregatorBase.java#L75

Therefore if there is an error, the close method will be called accordingly and the BigArrays will; be released. This kind of structure is problematic when you are creating an object inside of the constructor and the object is allocating more that one BigArray.

More over, since this [change](https://github.com/elastic/elasticsearch/pull/79676) where we introduced a better testing strategy, this sort of bugs a re much less likely as they should be caught by the testing framework.

**Comment by DaveCTurner** [comment] 2022-12-08 21:02
Ah I see, although I thought we weren't supposed to expose partially-constructed objects like that. We can close this then.

**Comment by xjtushilei** [comment] 2022-12-09 02:02
> @wchaparro I think this is a legit resource leak bug that still exists in `main` today:
> 
> https://github.com/elastic/elasticsearch/blob/d1ba276587dd033120240a74a6a83f1f372fbd4a/server/src/main/java/org/elasticsearch/search/aggregations/metrics/AvgAggregator.java#L51-L53
> 
> If e.g. we hit a circuit breaker exception when constructing `compensations` we will leak the other two arrays. We should fix it in 7.x and 8.x (although ofc not 6.x).

Yes, I have seen the latest code. There are many similar problems in the latest code

**Comment by martijnvg** [comment] 2022-12-12 06:48
Thanks @iverase for pointing this out!

@xjtushilei so if any of these arrays fail to be created then previously created arrays are cleaned up.
This happens because of before constructing any arrays using `BigArrays` the partially constructed object
is added to the `AggregationContext` as a resource that needs to be cleaned up (See `AggregatorBase.java` line 75 in main branch).

**Closed by martijnvg** 2022-12-12 06:48 UTC
Labels: >bug, :Analytics/Aggregations, Team:Analytics

**Comment by gregolsen** [comment] 2023-03-03 16:56
Hey folks 👋🏻 
We've just upgraded from 7.17.0 to 8.6.1 and started getting a lot more circuit breakers. It happened on two different clusters where we run expensive aggregations.
Right after upgrading the very first data nodes we had an elevation of estimated circuit breaker size for request circuit breaker:
<img width="1519" alt="image" src="https://user-images.githubusercontent.com/287994/222779834-448f0c25-b93f-4e8d-9bbf-ae143e686654.png">
breaker started tripping:
<img width="1527" alt="image" src="https://user-images.githubusercontent.com/287994/222779928-93789f52-993b-4f7a-9ef1-364ef270599a.png">
The error log lines point towards `reused_arrays` which is used by `BigArrays`
```
{"root_cause":[{"type":"circuit_breaking_exception","reason":"[request] Data too large, data for [<reused_arrays>] would be [3221293136/3gb], which is larger than the limit of [3221225472/3gb]","bytes_wanted":3221293136,"bytes_limit":3221225472,"durability":"TRANSIENT"}
```

We were suffering from a similar rate of circuit breaker errors on 7.9.3 but after upgrading to 7.17.0 it dropped significantly.
I see this was introduced in 7.11 https://github.com/elastic/elasticsearch/pull/64744
Any chance there's some regression in 8.6 that "undid" improvements in that PR?

**Comment by gregolsen** [comment] 2023-03-03 20:42
Looks like @neil-peirce figured out that it was due to `save_time_heuristic` becoming default since 8.3. Flipping back to `save_memory_heuristic` seems like solved the problem for us.
