### ISSUE TITLE
Use synonym in Keyword field

### ISSUE THREAD

**Issue by arkkanoid** [elastic/elasticsearch#27059] opened 2017-10-20 09:54 UTC
Hi, 
I'm trying to create a new mapping to include synonyms in a keyword field.  To do that, I use a normalizer:

    {
        "mappings": {
          "my_index": {
            "properties": {
              "name": {
                "type": "keyword",
                "normalizer": "synonym"
              }
            }
          }
        },
        "settings": {
    
            "analysis": {
              "filter": {
                "synonym": {
                  "type": "synonym",
                  "synonyms_path": "analysis/synonym.txt"
                }
              },
              "normalizer": {
                "synonym": {
                  "filter": [
                    "synonym"
                  ]
                }
              }
            }
          }
    
    }    

As a result:
    "Custom normalizer [synonym] may not use filter [synonym]"

Is there a way to include synonyms in a keyword field?

Elasticsearch version: 5.6

**Comment by nik9000** [comment] 2017-10-20 14:14
@arkkanoid I don't believe there is a way to use `synonym` in a normalizer right now. I believe the problem is that synonyms are allowed to emit more than a single token which violates the `keyword` contract. It feels like it'd be ok if we could guarantee that the `synonym` filter doesn't emit more than one synonym. Which ought to be possible in theory.

Can you explain what you want to use it for? It would only match the entire keyword. If you want to match only a portion of the field you'd want a [pattern replace filter](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-pattern-replace-charfilter.html) I think. That might be a good work around in even if you do want to replace the entire keyword.

**Comment by arkkanoid** [comment] 2017-10-20 14:31
Im my case, I store the country in one field. For example it could be 'usa', 'united states' or 'united states of america'). I mapped this field as a keyword. Then I aggregate this data and it appears 'usa', 'united states' or 'united states of america' as different values. 
I would like to count those values as the same one.

For this reason I though that using synonyms would be a good approach.
There is a simpler way to do that?

**Comment by nik9000** [comment] 2017-10-20 14:50
You could use a pattern replace char filter like I suggested. It feels like `synonym` should be fine here but it doesn't work. I've marked this for discussion so someone more familiar with the goals of normalizers can answer whether or not Elasticsearch should allow synonyms in normalizers in the future.

**Comment by dadoonet** [comment] 2017-10-20 15:04
You can always use a `text` field with `fieldata: true` as a workaround IMO.

**Comment by dadoonet** [comment] 2017-10-20 15:06
BTW may that this use case would fit in an `ingest-synonym` plugin which would be able to use a standard synonym file as input?

**Comment by nik9000** [comment] 2017-10-20 15:35
Yeah, I think that `ingest-synonym` would work well here. It isn't an option now because it doesn't exist, right?

**Comment by dadoonet** [comment] 2017-10-20 15:43
No it does not exist. It's a proposal as you marked the issue as `discuss`. 😃

**Comment by nik9000** [comment] 2017-10-20 15:52
> No it does not exist. It's a proposal as you marked the issue as discuss.

++

**Comment by jpountz** [comment] 2017-10-27 08:39
+1 to fix that issue at ingest time

**Comment by talevy** [comment] 2017-11-17 14:54
+1

I will open a PR soon to add [logstash-filter-translate](https://www.elastic.co/guide/en/logstash/6.0/plugins-filters-translate.html)-like support to Ingest
where one would be able to map keyword values to other values (the synonyms). This should help in a general way on the ingest side

**Comment by jpountz** [comment] 2018-03-14 09:11
cc @elastic/es-core-infra since it was decided to handle this with ingest

**Comment by talevy** [comment] 2018-03-15 16:21
Closing in favor of a new issue to introduce the Ingest Translate Processor

**Closed by talevy** 2018-03-15 16:21 UTC
Labels: :Core/Ingest, >enhancement

**Comment by ialisyed** [comment] 2019-12-23 11:36
@arkkanoid How did you solve your problem? I am stuck with the similar issue

**Comment by arkkanoid** [comment] 2019-12-23 11:43
I created a new field "synonyms" in each document where I add the related names

**Comment by ialisyed** [comment] 2019-12-23 12:05
@arkkanoid can you please elaborate it more?

**Comment by arkkanoid** [comment] 2019-12-23 15:41
Following the same example of countries, my mapping is:

	"mappings": {
		"location": {
			"properties": {
				"alternatenames": {
					"type": "text",
					"fields": {
						"keyword": {
							"type": "keyword",
							"ignore_above": 256
						}
					},
					"name": {
						"type": "keyword",
						"normalizer": "set_lowercase"
					}
				}
			}
		},
		"settings": {
			"analysis": {
				"normalizer": {
					"set_lowercase": {
						"filter": [
							"lowercase",
							"asciifolding"
						],
						"type": "custom"
					}
				}
			}
		}
	}

So I search synonyms in "name"( 'united states of america') and "alternatenames" fields ('usa', 'united states'). As a result, I ever get the "name" field ( 'united states of america').
