### ISSUE TITLE
Node FS total Stats only check path. it make fs total data not correct.

### ISSUE THREAD

**Issue by hgword** [elastic/elasticsearch#32568] opened 2018-08-02 00:24 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 5.6.4

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_151

**OS version** (`uname -a` if on a Unix-like system):  Linux 3.10.0-693.2.2.el7.x86_64 #1 SMP x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
when I try to fixing #32528 issue, 
I test like this.
```bash
df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda3       87G  6.7G   80G   8% /home
/dev/xvdb        99G   93M   94G   1% /home/data
```

```yaml
# elasticsearch.yml

path.data: /home1/elasticsearch-5.6.4/data, /home1/elasticsearch-5.6.4/data2, /home1/data/elastic/data2

```
* /home1/elasticsearch-5.6.4/data, /home1/elasticsearch-5.6.4/data2 are same mount positon(/dev/xvda3)
* /home1/data/elastic/data2 are "/dev/xvdb"

but when I call "GET _nodes/stats" return like this
``` json
"fs": {
            "timestamp": 1533169330636,
            "total": {
               "total": "271.2gb",
               "total_in_bytes": 291297730560,
               "free": "257.9gb",
               "free_in_bytes": 276960391168,
               "available": "252.9gb",
               "available_in_bytes": 271574904832
            },
            "data": [
               {
                  "path": "/home1/elasticsearch-5.6.4/data/nodes/0",
                  "mount": "/home1 (/dev/xvda3)",
                  "type": "ext4",
                  "total": "86.4gb",
                  "total_in_bytes": 92871450624,
                  "free": "79.8gb",
                  "free_in_bytes": 85741481984,
                  "available": "79.8gb",
                  "available_in_bytes": 85741481984,
                  "spins": "false"
               },
               {
                  "path": "/home1/data/elastic/data2/nodes/0",
                  "mount": "/home1/data (/dev/xvdb)",
                  "type": "ext4",
                  "total": "98.3gb",
                  "total_in_bytes": 105554829312,
                  "free": "98.2gb",
                  "free_in_bytes": 105477427200,
                  "available": "93.2gb",
                  "available_in_bytes": 100091940864,
                  "spins": "false"
               },
               {
                  "path": "/home1/elasticsearch-5.6.4/data2/nodes/0",
                  "mount": "/home1 (/dev/xvda3)",
                  "type": "ext4",
                  "total": "86.4gb",
                  "total_in_bytes": 92871450624,
                  "free": "79.8gb",
                  "free_in_bytes": 85741481984,
                  "available": "79.8gb",
                  "available_in_bytes": 85741481984,
                  "spins": "false"
               }
            ],
```
* total check "/home1" this partition twice.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by dakrone** [comment] 2020-10-27 17:53
Closing this as a duplicate of #27174

**Closed by dakrone** 2020-10-27 17:53 UTC
Labels: :Core/Features/Stats, >enhancement, Team:Core/Features
