### ISSUE TITLE
[discuss]should we fail fast when failures happens to parse search

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#26270] opened 2017-08-18 03:46 UTC
1. my mapping:
        "mappings": {
          "1": {
            "properties": {
              "data": {
                "type": "nested",
                "properties": {
                  "keywordNew": {
                    "type": "text"
                  }
                }
              },
              "Id": {
                "store": true,
                "type": "keyword"
              }
            }
          }
        }
2. my query:
{
   "stored_fields" : ["Id","data"],
  "query": {
    "term" : { "Id" : "XXXXX" } 
  }
}
3. my response:
{
  "_shards": {
    "total": 4,
    "failures": [
      {
        "reason": {
          "reason": "field [data] isn't a leaf field",
          "type": "illegal_argument_exception"
        },
        "index": "index",
        "shard": 0
      }
    ],
    "failed": 4,
    "successful": 0
  },
  "hits": {
    "hits": [],
    "total": 6,
  },
}
4. my question: should we fail fast when failures happens to parse search in this situation?

**Comment by rjernst** [comment] 2017-08-18 05:16
Closing a duplicate of #23719.

**Closed by rjernst** 2017-08-18 05:16 UTC
