### ISSUE TITLE
[CI] AutoFollowIT testDataStreams_autoFollowAfterDataStreamCreated failing

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#72062] opened 2021-04-22 05:46 UTC
Subsequent tests failed as well, but I suspect they are due to this initial failure.
```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "the leader index settings [{\"index.lifecycle.indexing_complete\":\"true\",\"index.lifecycle.name\":\"logs\",\"index.number_of_shards\":\"1\"}] and follower index settings [{\"index.lifecycle.name\":\"logs\",\"index.number_of_shards\":\"1\"}] must be identical"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "the leader index settings [{\"index.lifecycle.indexing_complete\":\"true\",\"index.lifecycle.name\":\"logs\",\"index.number_of_shards\":\"1\"}] and follower index settings [{\"index.lifecycle.name\":\"logs\",\"index.number_of_shards\":\"1\"}] must be identical"
  },
  "status": 400
}
```

**Build scan:**
https://gradle-enterprise.elastic.co/s/q4m7uwwqj7mei/tests/:x-pack:plugin:ccr:qa:multi-cluster:follow-cluster/org.elasticsearch.xpack.ccr.AutoFollowIT/testDataStreams_autoFollowAfterDataStreamCreated

**Reproduction line:**
`./gradlew ':x-pack:plugin:ccr:qa:multi-cluster:follow-cluster' --tests "org.elasticsearch.xpack.ccr.AutoFollowIT.testDataStreams_autoFollowAfterDataStreamCreated" -Dtests.seed=197AA5A92FE81C06 -Dtests.locale=sr-Latn-BA -Dtests.timezone=America/Argentina/San_Juan -Druntime.java=8`

**Applicable branches:**
7.x

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ccr.AutoFollowIT&tests.test=testDataStreams_autoFollowAfterDataStreamCreated

**Failure excerpt:**
```
org.elasticsearch.client.ResponseException: method [PUT], host [http://[::1]:45566], URI [/.ds-logs-syslog-prod-2021.04.22-000001/_ccr/follow?wait_for_active_shards=1], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"the leader index settings [{\"index.lifecycle.indexing_complete\":\"true\",\"index.lifecycle.name\":\"logs\",\"index.number_of_shards\":\"1\"}] and follower index settings [{\"index.lifecycle.name\":\"logs\",\"index.number_of_shards\":\"1\"}] must be identical"}],"type":"illegal_argument_exception","reason":"the leader index settings [{\"index.lifecycle.indexing_complete\":\"true\",\"index.lifecycle.name\":\"logs\",\"index.number_of_shards\":\"1\"}] and follower index settings [{\"index.lifecycle.name\":\"logs\",\"index.number_of_shards\":\"1\"}] must be identical"},"status":400}

  at __randomizedtesting.SeedInfo.seed([197AA5A92FE81C06:AD357CF326BDC165]:0)
  at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:326)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)
  at org.elasticsearch.xpack.ccr.ESCCRRestTestCase.followIndex(ESCCRRestTestCase.java:109)
  at org.elasticsearch.xpack.ccr.ESCCRRestTestCase.followIndex(ESCCRRestTestCase.java:81)
  at org.elasticsearch.xpack.ccr.ESCCRRestTestCase.followIndex(ESCCRRestTestCase.java:77)
  at org.elasticsearch.xpack.ccr.ESCCRRestTestCase.followIndex(ESCCRRestTestCase.java:73)
  at org.elasticsearch.xpack.ccr.AutoFollowIT.testDataStreams_autoFollowAfterDataStreamCreated(AutoFollowIT.java:319)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at java.lang.Thread.run(Thread.java:748)

```

**Comment by tlrx** [comment] 2021-04-30 09:29
I wasn't able to reproduce but I noticed that multiple tests were using the same patterns for auto-follower, which could cause the issue described. I merged #72464 to improve this, but if this issue occurs again please feel free to reopen.

**Comment by mark-vieira** [comment] 2021-06-04 00:04
I've seen a couple more failures but with a slightly different error: https://gradle-enterprise.elastic.co/s/5ggruoy3gvj2a/tests/:x-pack:plugin:ccr:qa:multi-cluster:follow-cluster/org.elasticsearch.xpack.ccr.AutoFollowIT/testDataStreams_autoFollowAfterDataStreamCreated?top-execution=1

**Comment by tlrx** [comment] 2021-06-04 12:01
@mvg this test fails regularly with either the index `.ds-logs-syslog-prod-2021.06.04-000001` not found or mismatching index settings between the leader and the follower (which I suppose can happen since they are rolled over at different times). I'm not sure what is exactly expected: maybe just retry the follow index request?

I'm going to assign this issue to you if that's OK.

**Comment by martijnvg** [comment] 2021-06-04 12:37
> I'm going to assign this issue to you if that's OK.

Yes, I will take a look at this issue. Thanks for looking at this and getting this to my attention.

**Comment by martijnvg** [comment] 2021-06-07 15:44
I have looked at the server logs (to find more info about what happened in the follow index call), but I couldn't find out whether the `.ds-logs-syslog-prod-2021.06.04-000001` is missing in the leader or follower cluster or any other significant clue. I like to add few more assertions around the `followIndex(...)` method invocation.

I did see: 

```
[2021-06-04T00:00:16,687][WARN ][o.e.p.PersistentTasksClusterService] [follow-cluster-0] persistent task CMeVsrySQp6c3L9-HxSm5g-0 failed
org.elasticsearch.index.IndexNotFoundException: no such index [.ds-logs-syslog-prod-2021.06.04-000002]
        at org.elasticsearch.xpack.ccr.action.ShardFollowTaskCleaner.clusterChanged(ShardFollowTaskCleaner.java:69) ~[?:?]
        at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListener(ClusterApplierService.java:515) ~[elasticsearch-7
.14.0-SNAPSHOT.jar:7.14.0-SNAPSHOT]
```

Which suggests that at some point the index was created in the follow cluster. Perhaps this happened at the end of the test suite.

**Comment by jkakavas** [comment] 2021-06-10 15:32
Another one today in master https://gradle-enterprise.elastic.co/s/dvcgbgdezj3ww/tests/:x-pack:plugin:ccr:qa:multi-cluster:follow-cluster/org.elasticsearch.xpack.ccr.AutoFollowIT/testDataStreams_autoFollowAfterDataStreamCreated

**Comment by martijnvg** [comment] 2021-06-14 09:48
In the failure mentioned by @jkakavas, the follow index (`ds-logs-syslog-prod-*-000001`) is successfully created in the follower cluster via the put follow api, but the resume follow api (which the put follow api executes) fails because the index settings of the leader index have changed in the meantime by ilm running in the leader cluster (by built-in ilm policy for logs). 

The mentioned index is rolled over manually in the test, but at a later point in the time ilm runs and sees that the data stream has been rolled over and updates the `index.lifecycle.indexing_complete` index setting. In this particular test failure this seems to happen after the follower index has been created and before the index is actually being followed (which is what resume follow index api is trying to initiate).

We can change the test to:

- Change the data stream name, so that the built-in logs templates / ilm policy aren't active.
- Or wait for the `index.lifecycle.indexing_complete` index setting be set in the leader index before attempting the follow the `ds-logs-syslog-prod-*-000001` index in follow cluster.
- Or change the resume follow index api to not fail if the `index.lifecycle.indexing_complete` setting has been set in the leader index, but not in the follower index. When index following is initiated then eventually the `index.lifecycle.indexing_complete` should be set too in the follower index (index settings version will not be equal between leader and follower index). 

I'm currently in favour of the last option. This test failure is something that can happen in real live too. (work around would be too remove the follower index and invoke the follow index api again).

**Comment by markharwood** [comment] 2021-06-23 09:15
Another one today in 7.13 https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.13+periodic+java-matrix/ES_RUNTIME_JAVA=zulu11,nodes=general-purpose/95/

**Closed** 2021-06-24 07:00 UTC
Labels: :Core/Features/Data streams, :Distributed/CCR, >test-failure, Team:Core/Features, Team:Distributed
