### ISSUE TITLE
Disabling disk watermarks for single node clusters is deprecated and no longer the default message is very confusing

### ISSUE THREAD

**Issue by bhavyarm** [elastic/elasticsearch#80817] opened 2021-11-18 09:54 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 7.16.0 BC4

**OS version** (`uname -a` if on a Unix-like system): darwin

**Description of the problem including expected versus actual behavior**:  

"Disabling disk watermarks for single-node clusters is deprecated and no longer the default" critical warning on ES in upgrade assistant is confusing for the following reasons:

1. I haven't set this config explicitly in my elasticsearch.yml. 
2. _You can set “cluster.routing.allocation.disk.threshold_enabled” to false to disable disk based allocation._  text in the warning is not the actual remediation step
2. And the actual remediation step is to set cluster.routing.allocation.disk.watermark.enable_for_single_data_node: true in the config file which isn't mentioned in the warning at all. 

<img width="1792" alt="Screen Shot 2021-11-17 at 1 50 20 PM (1)" src="https://user-images.githubusercontent.com/7074629/142392686-9572861e-0346-4a1f-9e5a-53a88ec92b32.png">

**Comment by LeeDr** [comment] 2021-11-18 14:57
Just adding my note here because it took some Slack discussion for me to finally understand it.

The disk water mark threshold is disabled by default on 7.x (I never knew this before).
On 8.x the default changes so that it is enabled.

This deprecation message is trying to get the "single node cluster" user to explicitly enable the disk watermark check while still on 7.16.0 so that they will know if they are over the watermark _before_ they upgrade to 8.0.  The setting isn't needed in 8.0 unless they want to force it to be disabled.

It *could* just be a release note that tells users about the change in default.  But some "single node cluster" users wouldn't read the release notes, upgrade, and if they are over the watermark, could see unexpected behavior.

Most production clusters would have more than one node and the disk watermark behavior wouldn't change and they wouldn't see any deprecation message.

**Comment by DaveCTurner** [comment] 2021-11-18 15:03
Yes that looks right @LeeDr. Not sure why this didn't auto-close when #80824 was merged but I'm closing it by hand now.

**Closed by DaveCTurner** 2021-11-18 15:03 UTC
Labels: >bug, >upgrade, :Distributed/Allocation
