### ISSUE TITLE
Properties of type ip named ip are not correclty handled on 6.8.x

### ISSUE THREAD

**Issue by albertored** [elastic/elasticsearch#53120] opened 2020-03-04 16:19 UTC
**Elasticsearch version**
I'm using the managed AWS Elasticsearch Service, this is the version given by API call

```json
{
  "name" : "AeXkreh",
  "cluster_name" : "409039530560:stagingelastic",
  "cluster_uuid" : "9on15f6pStKI3dwOAowKcg",
  "version" : {
    "number" : "6.8.0",
    "build_flavor" : "oss",
    "build_type" : "tar",
    "build_hash" : "629c3fa",
    "build_date" : "2020-02-21T22:15:06.700584Z",
    "build_snapshot" : false,
    "lucene_version" : "7.7.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

**Description of the problem including expected versus actual behavior**:
After creating an index with a mapping with a property of name `ip` and type `ip` the returned mapping is missing for that property and `_search` results do not include `ip` values.

**Steps to reproduce**:

 1. Create an index with a property `ip` of type `ip`:
`PUT /test-index`
```json
{
    "mappings" : {
        "_doc" : {
            "properties" : {
                "ip" : { "type" : "ip" }
            }
        }
    }
}
```

 2. `GET test-index/_mapping` returns
```json
{
  "test-index" : {
    "mappings" : {
      "_doc" : {
        "properties" : { }
      }
    }
  }
}
```

 3. Create a doc
`POST /test-index/_doc`
```json
{
  "ip": "1.2.3.4"
}
```

 4. `_search` API call (`GET test-index/_search`) does not return the ip value
```json
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "test-index",
      "_type" : "_doc",
      "_id" : "uSJGpnABRaLsIZkkSAQO",
      "_score" : 1.0,
      "_source" : { }
    } ]
  }
}
```

The expected return json for points 2 and 4 respectively is:
```json
{
  "test-index" : {
    "mappings" : {
      "_doc" : {
        "properties" : {
          "ip" : {
            "type" : "ip"
          }
        }
      }
    }
  }
}
```
and
```json
{
  "took" : 0,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "test-index",
        "_type" : "_doc",
        "_id" : "SUtSpnABh7CVxdJNcs7O",
        "_score" : 1.0,
        "_source" : {
          "ip" : "1.2.3.4"
        }
      }
    ]
  }
}
```

**Note 1**
The expected behavior is obtained on another AWS elasticsearch service instance where all works as expected, the version for this second instance is the same but the build date and build hash are different so I suspect also the version is indeed different.

```json
{
  "name" : "yNxeoOY",
  "cluster_name" : "241714805255:athcloudes",
  "cluster_uuid" : "wp7fRz9GTqyZYG7kMyD4gQ",
  "version" : {
    "number" : "6.8.0",
    "build_flavor" : "oss",
    "build_type" : "tar",
    "build_hash" : "65b6179",
    "build_date" : "2019-09-05T00:47:46.026972Z",
    "build_snapshot" : false,
    "lucene_version" : "7.7.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

**Note 2**
Other types work as expected, I tried with:
```json
{
  "test-index" : {
    "mappings" : {
      "_doc" : {
        "properties" : {
          "keyword" : {
            "type" : "keyword"
          }
        }
      }
    }
  }
}
```

**Comment by cbuescher** [comment] 2020-03-09 10:49
Hi @albertored, unfortunately I cannot reproduce this issue with neither 6.8.0, 6.8.7 or the current 7.6.1 versions, even the OSS versions.
The "official" release hast the following build information:
```
 "number": "6.8.0",
    "build_flavor": "oss",
    "build_type": "tar",
    "build_hash": "65b6179",
    "build_date": "2019-05-15T20:06:13.172855Z",
```
Note this was build sometime in May last year and matches the version that you report works for you as well.
I don't know why AWS services report different versions here, but 
```
"build_hash" : "629c3fa",
"build_date" : "2020-02-21T22:15:06.700584Z",
```
is clearly different and looks like it was build just recently, which indicates is shouldn't be any of the officially supported Elasticsearch versions. I'm closing this for lack of reproducability and would suggest you contact AWS support to clarify which versions they are using.

**Closed by cbuescher** 2020-03-09 10:49 UTC
Labels: :Search/Mapping

**Comment by albertored** [comment] 2020-03-09 11:11
Thanks @cbuescher for your reply. I tried with official elasticsearch versions and I cannot reproduce the issue either. I will open a ticket to AWS support as you suggested, thanks again and sorry for the noise :-)
