### ISSUE TITLE
Term Vector With BiGrams in Nested Object

### ISSUE THREAD

**Issue by vishva2005** [elastic/elasticsearch#25070] opened 2017-06-06 10:27 UTC
**Describe the feature**:

**Elasticsearch version**: 5.2.1

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_101

**OS version** (`uname -a` if on a Unix-like system): Ubuntu 14.04.4 LTS

**Description of the problem including expected versus actual behavior**: When creating term vectors for a nested document with bigrams, the result is always a unigram if term vectors are dynamically evaluated, if they are evaluated and stored, result is an empty array. However same works for fields in non-nested document

**Steps to reproduce**:

I have a a document which contains a subdocument, as such I have made the subdocument a nested property of the document. Now i need to find term vectors for the sub document. My terms can be unigrams or bigrams, hence I created an analyzer with shingle filter. The setting for the index is as follows
```
{
  "settings": {
    "analysis": {
      "filter": {
        "light_english_stemmer": {
		  "type":       "stemmer",
          "language":   "light_english" 
        },
        "filter_shingle":{
		   "type":"shingle",
		   "max_shingle_size":3,
		   "min_shingle_size":2,
		   "output_unigrams":"true",
		   "filler_token" : ""
		}
      },
      "analyzer": {
        "keyword_discovery_analyzer": {
          "tokenizer":  "standard",
          "char_filter":  [ "html_strip" ],
          "filter": [
            "lowercase",
            "filter_shingle",
            "light_english_stemmer"
          ]
        }
      }
    }
  },
  "mappings": {
  	"doc" : {
  		"properties" : {
  			"name" : {
  				"type" : "text"
  			},
  			"description" : {
  				"type" : "text",
  				"analyzer" : "indexing_analyzer",
  				"search_analyzer": "search_analyzer",
  				"fields" : {
  					"termVec": { 
		              "type" : "text",
		              "term_vector": "yes",
			          "store" : true,
			          "analyzer" : "keyword_discovery_analyzer"
		            }
  				}
  			},
  			"subDoc" : {
  				"type" : "nested",
  				"properties" : {
  					"name" : {
		  				"type" : "text",
		  				"fields" : {
							"termVec": { 
				              "type" : "text",
				              "term_vector": "yes",
					          "store" : true,
					          "analyzer" : "keyword_discovery_analyzer"
				            }
  						}
		  			},
		  			"description" : {
		  				"type" : "text",
		  				"fields" : {
							"termVec": { 
				              "type" : "text",
				              "term_vector": "yes",
					          "store" : true,
					          "analyzer" : "keyword_discovery_analyzer"
				            }
  						}
		  			}
  				}
  			}
  		}
  	}
  }
}
```

When i execute request

```
GET /_termvectors
{
"fields" : ["subDoc.name.termVec"],
"offsets" : false,
"payloads" : false,
"positions" : false,
"term_statistics" : true,
"field_statistics" : true,
"filter" :{
"max_num_terms" : 4
}
}
```

I get empty result. However if instead of the above query i run the following, 
```
GET /12631946/_termvectors
{
"fields" : ["subDoc.name"],
"offsets" : false,
"payloads" : false,
"positions" : false,
"term_statistics" : true,
"field_statistics" : true,
"per_field_analyzer" : {
"name": "keyword_discovery_analyzer"
},
"filter" :{
"max_num_terms" : 15
}
}
```

**Comment by tlrx** [comment] 2017-06-06 13:35
I don't think that nested documents are supported by the Term Vectors API and I don't think it is planned to be supported.

I'm going to label this issue as "Discuss" so that users and contributors can argue on the need and feasibility to add such a feature to the Term Vectors API.

**Comment by tlrx** [comment] 2017-06-09 13:10
We discussed this in Fix-it Friday and it's indeed a duplicate of #21625.

**Closed by tlrx** 2017-06-09 13:10 UTC
Labels: :Term Vectors, discuss
