### ISSUE TITLE
Index stays in UNASSIGNED state, if cluster was shutdown while a process of changing the replicas was running.

### ISSUE THREAD

**Issue by jakommo** [elastic/elasticsearch#15061] opened 2015-11-27 11:21 UTC
If a cluster is shutdown (all nodes at once), while there is a process running to increase the number of replicas, the index stays in a `UNASSIGNED` state with no messages in the logs.
If the number of replica is changed again the index comes back.

Steps to reproduce:

1. spin up a cluster with at least 3 nodes
2. Index some data (should be enough data for the replicas assignment to take some time) 
3. Change replicas to 0 `curl -XPUT 'localhost:9200/_settings' -d '{ "index" : {"number_of_replicas" : 0 }}'`
4. Raise number of replicas `curl -XPUT 'localhost:9200/_settings' -d '{ "index" : {"number_of_replicas" : 1 }}'` and shut down all nodes before the replicas have been fully assigned.
5. Start all nodes again
6.  The Index will stay in an `UNASSIGNED` state, but there is nothing in the logs on why this is the case.
7. Changing the number of replicas to 0 again, will bring back the index into a `STARTED` state.

Reproduced on 2.0 and 2.1.

**Comment by clintongormley** [comment] 2015-11-28 11:11
@bleskes could you take a look at this please

**Comment by bleskes** [comment] 2015-11-30 15:41
yeah, sadly this is how things work today. When we recover a primary, we reach out to all the nodes in the cluster and select the best copy we find (in order to make sure we don't select stale copies). In order to make this effective we require to see at least a quorum of the possible copies (i.e., number of replicas +1 ) with a special case for 2.  Since the number of replicas is increased and the cluster is shut down before ES is able to make more copies, a new primary is not elected. 

This will be fixed once we complete the work on #14739 . I'm closing this for now, as a duplicate of #14739 where github nicely refers back to this. Feel free to reopen if there is anything else.

**Comment by bleskes** [comment] 2015-11-30 15:49
sorry, mis read the ticket and thought you had more then 1 replica. Re-opening for further investigation.

**Comment by bleskes** [comment] 2015-12-01 12:14
I tried to reproduce but I couldn't, @jakommo are you sure used just one replica in your example in # 4 ? if it was 2 what I said above would explain it.

**Comment by jakommo** [comment] 2015-12-01 13:46
@bleskes you are right, sorry. I initially tried it with 4 nodes and num of replicas set to 3.
Just tried it again with 3 nodes and it doesn't happen with replicas set to 1, but with replicas 2.

**Comment by bleskes** [comment] 2015-12-01 13:49
OK. Good.  See my explanation above.  Closing again :)

**Closed by bleskes** 2015-12-01 13:49 UTC
Labels: :Recovery, bug, v2.1.1
