### ISSUE TITLE
[CI] IndexPrimaryRelocationIT.testPrimaryRelocationWhileIndexing failure

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#42502] opened 2019-05-24 10:01 UTC
## Example build failure
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-darwin-compatibility/186/console

## Reproduction line 
does not reproduce locally
```
./gradlew :server:integTest --tests "org.elasticsearch.indices.recovery.IndexPrimaryRelocationIT.testPrimaryRelocationWhileIndexing" \
  -Dtests.seed=26108842CFB5797B \
  -Dtests.security.manager=true \
  -Dtests.locale=th \
  -Dtests.timezone=Pacific/Fiji \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

## Example relevant log:
```
org.elasticsearch.indices.recovery.IndexPrimaryRelocationIT > testPrimaryRelocationWhileIndexing FAILED
    java.lang.AssertionError: Count is 10000+ hits but 11137 was expected.  Total shards: 1 Successful shards: 1 & 0 shard failures:
        at __randomizedtesting.SeedInfo.seed([26108842CFB5797B:78BF11179A450500]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertHitCount(ElasticsearchAssertions.java:256)
        at org.elasticsearch.indices.recovery.IndexPrimaryRelocationIT.testPrimaryRelocationWhileIndexing(IndexPrimaryRelocationIT.java:103)
```

Occurrence seems rare, not muting yet.

You can find the full logs [here](https://github.com/elastic/elasticsearch/files/3216279/testPrimaryRelocationWhileIndexing_failure.txt.zip)

**Comment by ywelsch** [comment] 2019-05-24 10:47
This was fixed in https://github.com/elastic/elasticsearch/pull/39384, but unfortunately not backported 😞 I've backported it now to all branches.

**Comment by pgomulka** [comment] 2019-06-13 11:05
interestingly the change was backported to 7.1 but I the issue reapeared
```
REPRODUCE WITH: ./gradlew :server:integTest --tests "org.elasticsearch.indices.recovery.IndexPrimaryRelocationIT.testPrimaryRelocationWhileIndexing" \
  -Dtests.seed=741D0A45431135A0 \
  -Dtests.security.manager=true \
  -Dtests.locale=es-BO \
  -Dtests.timezone=Europe/Vaduz \
  -Dcompiler.java=12 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew :server:integTest --tests "org.elasticsearch.indices.recovery.IndexPrimaryRelocationIT.testPrimaryRelocationWhileIndexing" \
  -Dtests.seed=741D0A45431135A0 \
  -Dtests.security.manager=true \
  -Dtests.locale=es-BO \
  -Dtests.timezone=Europe/Vaduz \
  -Dcompiler.java=12 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew :server:integTest --tests "org.elasticsearch.indices.recovery.IndexPrimaryRelocationIT.testPrimaryRelocationWhileIndexing" \
  -Dtests.seed=741D0A45431135A0 \
  -Dtests.security.manager=true \
  -Dtests.locale=es-BO \
  -Dtests.timezone=Europe/Vaduz \
  -Dcompiler.java=12 \
  -Druntime.java=8
```
does not reproduce locally for me

https://scans.gradle.com/s/q2vcb5fa2ocyu

**Comment by ywelsch** [comment] 2019-06-13 12:11
> interestingly the change was backported to 7.1 but I the issue reapeared

what makes you think it's the same issue? Because it's the same test failing?

This is a different assertion error in a different place (see below), for which we should create a fresh issue instead of resurrecting an unrelated old one. I understand it's not always easy to figure out whether it's the same cause or a different one, but if the error message changes, please add that information to the GH issue.

The failure here is:

```
java.lang.AssertionError: 
    Expected: <false>
         but: was <true>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.indices.recovery.IndexPrimaryRelocationIT.testPrimaryRelocationWhileIndexing(IndexPrimaryRelocationIT.java:88)

    com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=1107, name=Thread-12, state=RUNNABLE, group=TGRP-IndexPrimaryRelocationIT]

        Caused by:
        NodeClosedException[node closed {node_t0}{WudnTnG0R6OF2NJV0sWbQQ}{dzlZPFaQTFWmAZ2dbj8v_Q}{127.0.0.1}{127.0.0.1:35137}]
```

The UncaughtExceptionError is just a side effect of the previous assertion tripping. The assertion that trips indicates that a request took longer than a minute to complete.

The actual problem here is that the nodes seem to be freezing during the test, with fault detection of the 2 nodes noticing that the respective other is not responding.

This does not look to be anything specific to this test, and might indicate an infrastructure problem.

```
  1> [2019-06-13T10:47:58,545][TRACE][o.e.i.s.IndexShard       ] [node_t0] [test][0] refresh with source [schedule]
  1> [2019-06-13T10:48:08,806][DEBUG][o.e.c.c.LeaderChecker    ] [node_t1] 1 consecutive failures (limit [cluster.fault_detection.leader_check.retry_count] is 3) with leader [{node_t0}{WudnTnG0R6OF2NJV0sWbQQ}{dzlZPFaQTFWmAZ2dbj8v_Q}{127.0.0.1}{127.0.0.1:35137}]
  1> org.elasticsearch.transport.ReceiveTimeoutTransportException: [node_t0][127.0.0.1:35137][internal:coordination/fault_detection/leader_check] request_id [225] timed out after [10006ms]
  1> 	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:1026) [main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681) [main/:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
  1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
  1> [2019-06-13T10:48:08,806][DEBUG][o.e.c.c.FollowersChecker ] [node_t0] FollowerChecker{discoveryNode={node_t1}{9ysSabFGS-msrN6aRmOxrQ}{YjxB2namSy2PzoMx1-Zi8Q}{127.0.0.1}{127.0.0.1:58527}, failureCountSinceLastSuccess=1, [cluster.fault_detection.follower_check.retry_count]=3} failed, retrying
  1> org.elasticsearch.transport.ReceiveTimeoutTransportException: [node_t1][127.0.0.1:58527][internal:coordination/fault_detection/follower_check] request_id [300] timed out after [10006ms]
  1> 	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:1026) [main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681) [main/:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
  1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
  1> [2019-06-13T10:48:20,807][DEBUG][o.e.c.c.FollowersChecker ] [node_t0] FollowerChecker{discoveryNode={node_t1}{9ysSabFGS-msrN6aRmOxrQ}{YjxB2namSy2PzoMx1-Zi8Q}{127.0.0.1}{127.0.0.1:58527}, failureCountSinceLastSuccess=1, [cluster.fault_detection.follower_check.retry_count]=3} failed, retrying
  1> org.elasticsearch.transport.ReceiveTimeoutTransportException: [node_t1][127.0.0.1:58527][internal:coordination/fault_detection/follower_check] request_id [302] timed out after [10005ms]
  1> 	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:1026) [main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681) [main/:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
  1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
  1> [2019-06-13T10:48:20,807][DEBUG][o.e.c.c.LeaderChecker    ] [node_t1] 1 consecutive failures (limit [cluster.fault_detection.leader_check.retry_count] is 3) with leader [{node_t0}{WudnTnG0R6OF2NJV0sWbQQ}{dzlZPFaQTFWmAZ2dbj8v_Q}{127.0.0.1}{127.0.0.1:35137}]
  1> org.elasticsearch.transport.ReceiveTimeoutTransportException: [node_t0][127.0.0.1:35137][internal:coordination/fault_detection/leader_check] request_id [227] timed out after [10006ms]
  1> 	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:1026) [main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681) [main/:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
  1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
...
  1> [2019-06-13T10:48:31,808][DEBUG][o.e.c.c.LeaderChecker    ] [node_t1] 2 consecutive failures (limit [cluster.fault_detection.leader_check.retry_count] is 3) with leader [{node_t0}{WudnTnG0R6OF2NJV0sWbQQ}{dzlZPFaQTFWmAZ2dbj8v_Q}{127.0.0.1}{127.0.0.1:35137}]
  1> org.elasticsearch.transport.ReceiveTimeoutTransportException: [node_t0][127.0.0.1:35137][internal:coordination/fault_detection/leader_check] request_id [228] timed out after [10006ms]
  1> 	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:1026) [main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681) [main/:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
  1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
...
  1> [2019-06-13T10:48:57,635][DEBUG][o.e.c.c.Coordinator      ] [node_t1] onLeaderFailure: coordinator becoming CANDIDATE in term 1 (was FOLLOWER, lastKnownLeader was [Optional[{node_t0}{WudnTnG0R6OF2NJV0sWbQQ}{dzlZPFaQTFWmAZ2dbj8v_Q}{127.0.0.1}{127.0.0.1:35137}]])
  1> [2019-06-13T10:48:57,635][WARN ][o.e.t.TransportService   ] [node_t1] Received response for a request that has timed out, sent [23815ms] ago, timed out [13809ms] ago, action [internal:coordination/fault_detection/leader_check], node [{node_t0}{WudnTnG0R6OF2NJV0sWbQQ}{dzlZPFaQTFWmAZ2dbj8v_Q}{127.0.0.1}{127.0.0.1:35137}], id [230]
  1> [2019-06-13T10:48:57,635][TRACE][o.e.a.b.TransportShardBulkAction] [node_t0] [[test][0]] op [indices:data/write/bulk[s]] completed on primary for request [BulkShardRequest [[test][0]] containing [index {[test][type][56wGUGsBkv9vA_k2l0cB], source[{"auto":true}]}]]
  1> [2019-06-13T10:48:57,635][TRACE][o.e.a.b.TransportShardBulkAction] [node_t0] operation succeeded. action [indices:data/write/bulk[s]],request [BulkShardRequest [[test][0]] containing [index {[test][type][56wGUGsBkv9vA_k2l0cB], source[{"auto":true}]}]]
  1> [2019-06-13T10:48:57,635][INFO ][o.e.i.r.IndexPrimaryRelocationIT] [testPrimaryRelocationWhileIndexing] [IndexPrimaryRelocationIT#testPrimaryRelocationWhileIndexing]: cleaning up after test
```

**Closed** 2019-06-14 07:23 UTC
Labels: :Distributed/Recovery, >test-failure

**Comment by pgomulka** [comment] 2019-06-14 08:15
@ywelsch apologies, I probably should have spend more time investigating this failure before reopening. I wrongly assumed that same testmethod and a recent change/fix would mean that this could be the same problem.
