### ISSUE TITLE
[CI] org.elasticsearch.index.reindex.RethrottleTests with two tests failing

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#26192] opened 2017-08-14 08:22 UTC
* Build failure link: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/3904/console
```
Tests with failures:
  - org.elasticsearch.index.reindex.RethrottleTests.testDeleteByQueryWithWorkers
  - org.elasticsearch.index.reindex.RethrottleTests.testDeleteByQuery
```

* Error message: 
```
ERROR   0.39s J1 | RethrottleTests.testDeleteByQueryWithWorkers <<< FAILURES!
   > Throwable #1: ElasticsearchException[Rethrottle of [kDDav6kbTqm-2S0E_VSGmA:163] failed]; nested: IllegalArgumentException[task [163] must be set as a child or parent];
   > 	at __randomizedtesting.SeedInfo.seed([B60C174C1CAD6D39:316B3A20264932DA]:0)
   > 	at org.elasticsearch.action.support.tasks.BaseTasksResponse.lambda$rethrowFailures$0(BaseTasksResponse.java:73)
   > 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
   > 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
   > 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
   > 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
   > 	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
   > 	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
   > 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
   > 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
   > 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
   > 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
   > 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
   > 	at org.elasticsearch.action.support.tasks.BaseTasksResponse.rethrowFailures(BaseTasksResponse.java:74)
   > 	at org.elasticsearch.index.reindex.RethrottleTests.testCase(RethrottleTests.java:118)
   > 	at org.elasticsearch.index.reindex.RethrottleTests.testDeleteByQueryWithWorkers(RethrottleTests.java:71)
   > 	at java.lang.Thread.run(Thread.java:748)
   > Caused by: java.lang.IllegalArgumentException: task [163] must be set as a child or parent
   > 	at org.elasticsearch.index.reindex.TransportRethrottleAction.rethrottle(TransportRethrottleAction.java:73)
   > 	at org.elasticsearch.index.reindex.TransportRethrottleAction.taskOperation(TransportRethrottleAction.java:57)
   > 	at org.elasticsearch.index.reindex.TransportRethrottleAction.taskOperation(TransportRethrottleAction.java:43)
   > 	at org.elasticsearch.action.support.tasks.TransportTasksAction.nodeOperation(TransportTasksAction.java:152)
   > 	at org.elasticsearch.action.support.tasks.TransportTasksAction.access$1000(TransportTasksAction.java:67)
   > 	at org.elasticsearch.action.support.tasks.TransportTasksAction$NodeTransportHandler.messageReceived(TransportTasksAction.java:347)
   > 	at org.elasticsearch.action.support.tasks.TransportTasksAction$NodeTransportHandler.messageReceived(TransportTasksAction.java:343)
   > 	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:30)
   > 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66)
   > 	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1526)
   > 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638)
   > 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
   > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   > 	... 1 more
```

```
FAILURE 0.73s J1 | RethrottleTests.testDeleteByQuery <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: a collection with size a value less than <2>
   >      but: collection size <2> was equal to <2>
   > 	at __randomizedtesting.SeedInfo.seed([B60C174C1CAD6D39:B8C31267456212AF]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.index.reindex.RethrottleTests.findTaskToRethrottle(RethrottleTests.java:180)
   > 	at org.elasticsearch.index.reindex.RethrottleTests.testCase(RethrottleTests.java:94)
   > 	at org.elasticsearch.index.reindex.RethrottleTests.testDeleteByQuery(RethrottleTests.java:59)
   > 	at java.lang.Thread.run(Thread.java:748)
```

* Reproduction lines:
  * gradle :modules:reindex:test -Dtests.seed=B60C174C1CAD6D39 -Dtests.class=org.elasticsearch.index.reindex.RethrottleTests -Dtests.method="testDeleteByQueryWithWorkers" -Dtests.security.manager=true -Dtests.jvm.argline="-XX:-UseConcMarkSweepGC -XX:+UseG1GC" -Dtests.locale=id-ID -Dtests.timezone=Asia/Phnom_Penh (does not reproduce locally)
  * gradle :modules:reindex:test -Dtests.seed=B60C174C1CAD6D39 -Dtests.class=org.elasticsearch.index.reindex.RethrottleTests -Dtests.method="testDeleteByQuery" -Dtests.security.manager=true -Dtests.jvm.argline="-XX:-UseConcMarkSweepGC -XX:+UseG1GC" -Dtests.locale=id-ID -Dtests.timezone=Asia/Phnom_Penh (does not reproduce locally)

**Comment by cbuescher** [comment] 2017-08-14 08:26
Here is another one over the weekend where also `RethrottleTests.testReindexWithWorkers` failed: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=opensuse/1422/console

**Comment by nik9000** [comment] 2017-08-14 13:12
I've reassigned to @andy-elastic because he's recently made some changes in this area. I'm happy to help though.

**Comment by andy-elastic** [comment] 2017-08-14 14:52
This is very likely caused by my changes, I'll take a look

**Comment by andy-elastic** [comment] 2017-08-14 18:05
I'm having trouble reproducing this but from the error messages it seems pretty clear that it's the rethrottle action is happening before the task's leader/worker state is set in the transport reindex handlers

**Comment by andy-elastic** [comment] 2017-08-15 01:26
I was able to reproduce this by causing the rethrottle to happen before the task state is set, and it does look similar to the logs from CI. Minor fixes here that I can think of are 

1. Make the test wait until the task state is set before sending the rethrottle command. It's easy to imagine client applications running into problems here, so I'd like it to be more resilient
2. Make the rethrottle action wait until the task's state is set before continuing, or timeout. I'm not a huge fan of this strategy, although I can't really articulate any good reasons why
3. Let it perform a rethrottle on the task, and if the state isn't set yet, "store" that rethrottle and apply it later at the time the task state is set. This is closest to the old behavior but maybe could be more confusing

All of these still have the issue where the task may have operations performed on it before its state is set, which didn't happen in the old behavior. The way to get around this, which would be a major change, would to be have it always set the task as leader when slices is `auto`. 

I'll try one of these minor ones first and see if that's satisfactory, and if not make the major change

**Comment by dimitris-athanasiou** [comment] 2017-08-16 10:21
Another where `testReindex` and `testReindexWithWorkers` both failed: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-darwin-compatibility/57/console

**Comment by dimitris-athanasiou** [comment] 2017-08-16 12:27
And another: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+oracle-periodic/239/console

**Comment by dimitris-athanasiou** [comment] 2017-08-16 14:33
In this one 4 tests failed: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+java9-periodic/250/console

**Comment by andy-elastic** [comment] 2017-08-25 16:01
Had another one today, doesn't seem to be consistently failing. I'll see if I can reproduce https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+aggressive-opts/157/consoleText

**Comment by andy-elastic** [comment] 2017-08-28 22:58
Couldn't reproduce this, added some test logging so we'll have more info the next time it fails in CI. 

The failure I posted above had a timeout while waiting for the reindex task to be finished initializing, but also had errors like this before, one for each shard

```
  1> [2017-08-25T10:19:18,933][WARN ][o.e.i.r.TransportReindexAction] [node_sc4] giving up on search because it failed with a non-retryable exception                                  
  1> org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed      
  1>    at org.elasticsearch.action.search.SearchScrollAsyncAction.onShardFailure(SearchScrollAsyncAction.java:269) ~[elasticsearch-6.1.0-SNAPSHOT.jar:6.1.0-SNAPSHOT]                 
  1>    at org.elasticsearch.action.search.SearchScrollAsyncAction$1.onFailure(SearchScrollAsyncAction.java:202) ~[elasticsearch-6.1.0-SNAPSHOT.jar:6.1.0-SNAPSHOT]                    
  1>    at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:51) ~[elasticsearch-6.1.0-SNAPSHOT.jar:6.1.0-SNAPSHOT]            
  1>    at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1060) ~[elasticsearch-6.1.0-SNAPSHOT.jar:6.1.0-SNAPSHOT]   
  1>    at org.elasticsearch.transport.TcpTransport.lambda$handleException$24(TcpTransport.java:1449) ~[elasticsearch-6.1.0-SNAPSHOT.jar:6.1.0-SNAPSHOT]                               
  1>    at org.elasticsearch.common.util.concurrent.EsExecutors$1.execute(EsExecutors.java:139) ~[elasticsearch-6.1.0-SNAPSHOT.jar:6.1.0-SNAPSHOT]                                     
  1>    at org.elasticsearch.transport.TcpTransport.handleException(TcpTransport.java:1447) ~[elasticsearch-6.1.0-SNAPSHOT.jar:6.1.0-SNAPSHOT]                                         
  1>    at org.elasticsearch.transport.TcpTransport.handlerResponseError(TcpTransport.java:1439) ~[elasticsearch-6.1.0-SNAPSHOT.jar:6.1.0-SNAPSHOT]                                    
  1>    at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1369) ~[elasticsearch-6.1.0-SNAPSHOT.jar:6.1.0-SNAPSHOT]                                         
  1>    at org.elasticsearch.transport.MockTcpTransport.readMessage(MockTcpTransport.java:170) ~[framework-6.1.0-SNAPSHOT.jar:6.1.0-SNAPSHOT]                                          
  1>    at org.elasticsearch.transport.MockTcpTransport.access$900(MockTcpTransport.java:71) ~[framework-6.1.0-SNAPSHOT.jar:6.1.0-SNAPSHOT]                                            
  1>    at org.elasticsearch.transport.MockTcpTransport$MockChannel$1.lambda$doRun$0(MockTcpTransport.java:348) ~[framework-6.1.0-SNAPSHOT.jar:6.1.0-SNAPSHOT]                         
  1>    at org.elasticsearch.common.util.CancellableThreads.executeIO(CancellableThreads.java:105) ~[elasticsearch-6.1.0-SNAPSHOT.jar:6.1.0-SNAPSHOT]                                  
  1>    at org.elasticsearch.transport.MockTcpTransport$MockChannel$1.doRun(MockTcpTransport.java:348) ~[framework-6.1.0-SNAPSHOT.jar:6.1.0-SNAPSHOT]                                  
  1>    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.1.0-SNAPSHOT.jar:6.1.0-SNAPSHOT]                                  
  1>    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_141]                                                                              
  1>    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_141]                                                                              
  1>    at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_141]                            
  1> Caused by: org.elasticsearch.transport.RemoteTransportException: [node_sd3][127.0.0.1:54368][indices:data/read/search[phase/query/scroll]]                                        
  1> Caused by: org.elasticsearch.search.SearchContextMissingException: No search context found for id [41]                                                                            
  1>    at org.elasticsearch.search.SearchService.findContext(SearchService.java:492) ~[elasticsearch-6.1.0-SNAPSHOT.jar:6.1.0-SNAPSHOT]                                               
  1>    at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:363) ~[elasticsearch-6.1.0-SNAPSHOT.jar:6.1.0-SNAPSHOT]                                         
  1>    at org.elasticsearch.action.search.SearchTransportService$8.messageReceived(SearchTransportService.java:390) ~[elasticsearch-6.1.0-SNAPSHOT.jar:6.1.0-SNAPSHOT]                
  1>    at org.elasticsearch.action.search.SearchTransportService$8.messageReceived(SearchTransportService.java:387) ~[elasticsearch-6.1.0-SNAPSHOT.jar:6.1.0-SNAPSHOT]                
  1>    at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) ~[elasticsearch-6.1.0-SNAPSHOT.jar:6.1.0-SNAPSHOT]                
  1>    at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1526) ~[elasticsearch-6.1.0-SNAPSHOT.jar:6.1.0-SNAPSHOT]                                    
  1>    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) ~[elasticsearch-6.1.0-SNAPSHOT.jar:6.1.0-SNAPSHOT]   
  1>    ... 4 more
```

**Comment by tlrx** [comment] 2017-10-05 08:29
Another instance today : https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/4530/

See [consoleText.txt](https://github.com/elastic/elasticsearch/files/1358547/consoleText.txt)

**Comment by andyb-elastic** [comment] 2018-01-02 19:55
Another in 6.x

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=amazon/479/console

[build-479-RethrottleTests.txt](https://github.com/elastic/elasticsearch/files/1598557/build-479-RethrottleTests.txt)

**Comment by andyb-elastic** [comment] 2018-01-02 20:03
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=debian/443/console

[build-443-RethrottleTests.txt](https://github.com/elastic/elasticsearch/files/1598572/build-443-RethrottleTests.txt)

**Comment by dakrone** [comment] 2018-03-20 14:52
Haven't seen these failures for quite a while, so closing this for now.

**Closed by dakrone** 2018-03-20 14:52 UTC
Labels: :Distributed/CRUD, jenkins
