### ISSUE TITLE
SQL: selecting a sub-field and all subfields generates error

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#43163] opened 2019-06-12 14:20 UTC
Issue reproduced on `demo.elastic.co`:
```
POST _sql?pretty&format=txt
{
  "query":"select Carrier.keyword, Carrier.* from flights"
}
```

Gives:

```
{
  "error": {
    "root_cause": [
      {
        "type": "index_out_of_bounds_exception",
        "reason": "Index: 1, Size: 1"
      }
    ],
    "type": "index_out_of_bounds_exception",
    "reason": "Index: 1, Size: 1"
  },
  "status": 500
}
```

**Comment by matriv** [comment] 2020-03-30 15:15
@elastic/es-ql

**Comment by luigidellaquila** [comment] 2022-02-09 12:58
I just tested it on `demo.elastic.co` and everything seems to work fine.
Probably the problem was solved as a consequence of another fix.

**Comment by bpintea** [comment] 2022-02-09 15:24
Indeed, I can't reproduce it either. I'll close it for now, we can reopen it if needed.

**Closed by bpintea** 2022-02-09 15:24 UTC
Labels: >bug, :Query Languages/SQL, Team:QL
