### ISSUE TITLE
A data node is both source and destination during cluster recovery.

### ISSUE THREAD

**Issue by linker-c** [elastic/elasticsearch#88876] opened 2022-07-27 22:14 UTC
### Elasticsearch Version

7.15

### Java Version

_bundled_

### OS Version

 5.4.0-1045-aws #47-Ubuntu 

### Problem Description

When adding several new data nodes to my existing cluster.  The cluster will start the recovery process.
If I have adjusted setting for "cluster_concurrent_rebalance" and "node_concurrent_recoveries" to some values greater than 5, I start to see shards being moved in and out of the same data node.  This caused the recovery to never end.
I even have the "cluster.routing.allocation.balance.threshold" set to 6.  I assume this means each data node can have up to 6 shard difference without needing to rebalance.
Please see below image where data node 102 is both the source and destination for different shards being moved.
This data comes from "GET /_cat/recovery?v&active_only"

<img width="818" alt="image" src="https://user-images.githubusercontent.com/13143624/181381361-2326f47e-ef0d-4c28-95dc-b39d83d6dafa.png">

### Steps to Reproduce

With an existing ES cluster (I have 30 data nodes), adding 3 new data nodes with the following cluster setting.

{
  "persistent" : {
    "action" : {
      "destructive_requires_name" : "true"
    },
    "cluster" : {
      "routing" : {
        "allocation" : {
          "balance" : {
            "threshold" : "6"
          },
          "cluster_concurrent_rebalance" : "10",
          "node_concurrent_recoveries" : "5"
        }
      }
    },
    "search" : {
      "default_search_timeout" : "30s"
    },
    "ingest" : {
      "geoip" : {
        "downloader" : {
          "enabled" : "false"
        }
      }
    }
  },
  "transient" : { }
}

**Comment by DaveCTurner** [comment] 2022-08-01 11:11
Closing as a duplicate of #87279.

**Closed by DaveCTurner** 2022-08-01 11:11 UTC
Labels: >bug, needs:triage
