### ISSUE TITLE
`_default_`-mapping needs to allow for negation of `_parent` 

### ISSUE THREAD

**Issue by konradkonrad** [elastic/elasticsearch#14256] opened 2015-10-23 00:28 UTC
I might be missing something here (hopefully), but I am at a loss, how to achieve the generic definition of an index, where **all other types except the type "parent" are children of the type "parent"**?

I thought, I could achieve this with index templates + the `_default_` mapping.

The docs for [default mapping](https://www.elastic.co/guide/en/elasticsearch/guide/current/default-mapping.html#default-mapping) state, that

> All types created _after_ the _default_ mapping will include all of these default settings, unless explicitly overridden in the type mapping itself.

The example goes on to display, how `"_all": {"enabled": true}}` can be explicitly overwritten, which seems straightforward. However, I fail to achieve the same thing, after defining a `_parent` mapping in `_default_`:

```
curl -XPOST localhost:9200/_template/familytrouble -d '{
  "template": "trouble*",
  "mappings": {
    "parent": {
  },
    "_default_": {
      "_parent": {"type": "parent"}
    }
  }
}'
curl -XPUT localhost:9200/troubled/parent/1
>> {"error":"RoutingMissingException[routing is required for [troubled]/[parent]/[1]]","status":400}
```

So I guess, if I could use a mapping-definition akin to

```
"_parent": {}
```

in my parent type, this should work. But I could not find the necessary override for the `_parent`-setting.

**Comment by rjernst** [comment] 2015-10-26 18:42
@konradkonrad Can you try using 2 templates, where the first has a higher priority, and creates the parent mapping? I have seen issues with precedence before due to serialization/deserialization. The mappings are added one by one, even when multiple are passed at creation time, and unfortunately it isn't always in the same order they are originally parsed in.

**Comment by clintongormley** [comment] 2015-10-29 19:01
@rjernst that won't work either... I believe the templates are merged before trying to create the mappings, so you end up with the same mappings as if you use just one template.  The problem is that you can't specify a `parent` setting that says "I have no parent settings"

**Comment by clintongormley** [comment] 2017-11-10 15:08
Default mappings are no longer supported, and indices can only have a single mapping type.  Closing

**Closed by clintongormley** 2017-11-10 15:08 UTC
Labels: :Index Templates, :Mapping, adoptme, bug, low hanging fruit
