### ISSUE TITLE
Docs test failed tophits-aggregation

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#45572] opened 2019-08-14 19:58 UTC
Failed on master; doesn't reproduce locally for me.

REPRODUCE WITH: ./gradlew :docs:integTestRunner --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/aggregations/metrics/tophits-aggregation/line_243}" \
  -Dtests.seed=8528B5779D499F51 \
  -Dtests.security.manager=true \
  -Dtests.locale=es-CR \
  -Dtests.timezone=Asia/Hovd \
  -Dcompiler.java=12 \
  -Druntime.java=11

Log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob+fast+part1/759/console
Build Scans: https://gradle-enterprise.elastic.co/s/c3acklgkuxn62

Caused by: java.lang.AssertionError: expected [2xx] status code but api [raw[method=PUT path=sales]] returned [400 Bad Request] [{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [sales/tZO5adjTTXq8kLb1Of1UaQ] already exists","index_uuid":"tZO5adjTTXq8kLb1Of1UaQ","index":"sales","stack_trace":"[sales/tZO5adjTTXq8kLb1Of1UaQ] 
...
[test] [yaml=reference/aggregations/metrics/tophits-aggregation/line_243]

In line 243 of the test we again create an index:
```
PUT /sales
```

Not sure what causes that. The index with the same name created from the previous test is supposed to be deleted. May be makes sense to use a different index name, or do some investigation on DocsClientYamlTestSuiteIT side.

**Comment by matriv** [comment] 2019-09-20 12:33
Another failure on 7.3: https://gradle-enterprise.elastic.co/s/rkhgvjrsjvaki/console-log?task=:docs:integTestRunner

Could not reproduce locally.

**Comment by jrodewig** [comment] 2019-10-04 15:26
[docs issue triage]

Leaving open as this is still relevant.

**Comment by imotov** [comment] 2019-11-12 18:49
I checked the backlog and it looks like this test didn't fail since #46091 was resolved. I am going to close it.

**Closed by imotov** 2019-11-12 18:49 UTC
Labels: :Analytics/Aggregations, >docs, >test-failure
