### ISSUE TITLE
update script error

### ISSUE THREAD

**Issue by orange-jacky** [elastic/elasticsearch#24153] opened 2017-04-18 10:02 UTC
**Elasticsearch version**:
elasticsearch-2.3.5.tar.gz

**Plugins installed**: []
modules [reindex, lang-expression, lang-groovy], plugins [license, delete-by-query], sites []

**JVM version**:
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

**OS version**:
[search@search-02 es1]$ lsb_release  -a
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	CentOS
Description:	CentOS release 6.5 (Final)
Release:	6.5
Codename:	Final

[search@search-02 es1]$ uname -a
Linux search-02.cloud.mos 2.6.32-431.1.2.0.1.el6.x86_64 #1 SMP Fri Dec 13 13:06:13 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
PUT test/type1/1
{
    "counter" : 1,
    "tags" : ["red"]
}
it ok

POST test/type1/1/_update
{
    "script" : {
        "inline": "ctx._source.counter += count",
        "params" : {
            "count" : 4
        }
    }
}

it fail.

error info:

   "error": {
      "root_cause": [
         {
            "type": "remote_transport_exception",
            "reason": "[node-3][172.16.8.145:9300][indices:data/write/update[s]]"
         }
      ],
      "type": "illegal_argument_exception",
      "reason": "failed to execute script",
      "caused_by": {
         "type": "script_exception",
         "reason": "failed to run inline script [ctx._source.counter += count] using lang [groovy]",
         "caused_by": {
            "type": "no_class_def_found_error",
            "reason": "Could not initialize class org.codehaus.groovy.vmplugin.v7.IndyGuardsFiltersAndSignatures"
         }
      }
   },
   "status": 400
}
￼
<img width="928" alt="ok" src="https://cloud.githubusercontent.com/assets/461594/25125844/da127d4e-2462-11e7-9def-5c13789f42d2.png">

<img width="936" alt="fail" src="https://cloud.githubusercontent.com/assets/461594/25125857/e507736c-2462-11e7-8a58-4de0f4372ae0.png">

**Steps to reproduce**:
 1. create a cluster, has 3 nodes
 2.start the cluster
 3.the flowwing is configure file
[elasticsearch.yml.zip](https://github.com/elastic/elasticsearch/files/928483/elasticsearch.yml.zip)

**Provide logs (if relevant)**:

[cheackflight_dev.log.zip](https://github.com/elastic/elasticsearch/files/928507/cheackflight_dev.log.zip)

**Describe the feature**:

**Comment by jasontedor** [comment] 2017-04-18 10:29
This does not reproduce:

```
06:21:31 [jason:~] $ curl -XGET localhost:9200/            
{
  "name" : "Rachel van Helsing",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "2.3.5",
    "build_hash" : "90f439ff60a3c0f497f91663701e64ccd01edbb4",
    "build_timestamp" : "2016-07-27T10:36:52Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.0"
  },
  "tagline" : "You Know, for Search"
}
06:24:41 [jason:~] $ curl -XPUT localhost:9200/test/type1/1?pretty=true -d '            
{
  "counter": 1,
  "tags": ["red"]
}'
{
  "_index" : "test",
  "_type" : "type1",
  "_id" : "1",
  "_version" : 1,
  "_shards" : {
    "total" : 2,
    "successful" : 2,
    "failed" : 0
  },
  "created" : true
}
06:24:47 [jason:~] $ curl -XPOST localhost:9200/test/type1/1/_update?pretty=true -d '
{
  "script": {
    "inline": "ctx._source.counter += count",
    "params": {
      "count": 4
    }
  }
}'
{
  "_index" : "test",
  "_type" : "type1",
  "_id" : "1",
  "_version" : 2,
  "_shards" : {
    "total" : 2,
    "successful" : 2,
    "failed" : 0
  }
}
06:25:00 [jason:~] $ 
```

Typically when we see these kinds of problems, it's due to security manager permissions. Have you modified your security permissions? It's clear that there is a reproduction step that you are leaving out. If you could open a post on the [forum](https://discuss.elastic.co), someone could try to work through the issue with you. Since Elastic reserves GitHub only for verified bug reports and feature requests, I'm closing this issue as unable to reproduce.

**Closed by jasontedor** 2017-04-18 10:29 UTC

**Comment by orange-jacky** [comment] 2017-04-18 14:53
In fact,I countered this issue today,i build two cluster,one is produce ,the other is develop,the same os ,the same es and the same configure. The produce is ok,and the dev has the issue. It makes me fuzzyed
