### ISSUE TITLE
A bug about index alias which could cause serious problems

### ISSUE THREAD

**Issue by dzhang22** [elastic/elasticsearch#21318] opened 2016-11-03 20:02 UTC
**Elasticsearch version**:
2.4.1
**Plugins installed**: []
None
**JVM version**:
1.7
**OS version**:
Ubuntu14.04
**Description of the problem including expected versus actual behavior**:
I create two alias A and B for the original index M. The index type is N. I put a document with _id X under alias A. The bug is I can access X under B. Specifically,
. GET /A/N/X gives me the document (expected)
. GET /M/N/X returns "Found False" (not sure if correct)
. GET /B/N/X gives me the document (unexpected)

In another test, I use the search api and the results are:
. GET /A/N/_search?q=id:X gives me the document (expected)
. GET /M/N/_search?q=id:X gives me the document (not sure if correct)
. GET /B/N/_search?q=id:X finds no document (expected)

**Steps to reproduce**:
 1. Build an index M and create two alias A and B
 2. Put Document with _id X under A
 3. Try GET and search X under A, B, M

**Provide logs (if relevant)**:

**Comment by jasontedor** [comment] 2016-11-03 20:52
This does not reproduce for me.

```
16:48:47 ⌁58% [jason:~] $ curl -XPOST localhost:9200/m?pretty=1 -d '
{
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 0
  }
}'
{
  "acknowledged" : true
}
16:49:03 ⌁58% [jason:~] $ curl -XPOST localhost:9200/_aliases?pretty=1 -d '
{
  "actions": [
    { "add": { "index": "m", "alias": "a" } }
  ]
}'
{
  "acknowledged" : true
}
16:49:09 ⌁58% [jason:~] $ !!:gs/"a"/"b"
curl -XPOST localhost:9200/_aliases?pretty=1 -d '
{
  "actions": [
    { "add": { "index": "m", "alias": "b" } }
  ]
}'
{
  "acknowledged" : true
}
16:49:13 ⌁58% [jason:~] $ curl -XPOST localhost:9200/a/n/1?pretty=1 -d '{"f": "v"}'
{
  "_index" : "m",
  "_type" : "n",
  "_id" : "1",
  "_version" : 1,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "created" : true
}
16:49:20 ⌁58% [jason:~] $ curl -XGET localhost:9200/a/n/1?pretty=1
{
  "_index" : "m",
  "_type" : "n",
  "_id" : "1",
  "_version" : 1,
  "found" : true,
  "_source" : {
    "f" : "v"
  }
}
16:49:30 ⌁58% [jason:~] $ curl -XGET localhost:9200/b/n/1?pretty=1
{
  "_index" : "m",
  "_type" : "n",
  "_id" : "1",
  "_version" : 1,
  "found" : true,
  "_source" : {
    "f" : "v"
  }
}
16:49:32 ⌁58% [jason:~] $ curl -XGET localhost:9200/m/n/1?pretty=1
{
  "_index" : "m",
  "_type" : "n",
  "_id" : "1",
  "_version" : 1,
  "found" : true,
  "_source" : {
    "f" : "v"
  }
}
16:51:16 ⌁57% [jason:~] $ curl -XGET localhost:9200/a/_search?pretty=1 -d '
{
  "query": {
    "match_all": {}
  }
}'
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "m",
      "_type" : "n",
      "_id" : "1",
      "_score" : 1.0,
      "_source" : {
        "f" : "v"
      }
    } ]
  }
}
16:51:26 ⌁57% [jason:~] $ curl -XGET localhost:9200/b/_search?pretty=1 -d '
{
  "query": {
    "match_all": {}
  }
}'
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "m",
      "_type" : "n",
      "_id" : "1",
      "_score" : 1.0,
      "_source" : {
        "f" : "v"
      }
    } ]
  }
}
16:51:30 ⌁57% [jason:~] $ curl -XGET localhost:9200/m/_search?pretty=1 -d '
{
  "query": {
    "match_all": {}
  }
}'
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "m",
      "_type" : "n",
      "_id" : "1",
      "_score" : 1.0,
      "_source" : {
        "f" : "v"
      }
    } ]
  }
}
```

If you have an actual reproduction that reproduces the issue, that would be really helpful otherwise I will have to close this as unable to reproduce.

**Comment by dzhang22** [comment] 2016-11-03 21:33
Thanks for creating the example.

Below is the reproduction of the problem. 
With 1 shard and 0 replica, x can be found under both a, b, m. With 5 shards and 1 replica, x cannot be found under b, m.

Why is this?

============= with 1 shard and 0 replica =================
ubuntu$ curl -XPOST localhost:9200/m?pretty=1 -d '
 {
   "settings": {
     "number_of_shards": 1,
     "number_of_replicas": 0
   }
 }'
{
  "acknowledged" : true
}

ubuntu$ curl -XPUT localhost:9200/m/_alias/a -d '
 {
   "routing": "a",
   "filter": {
     "term": {
       "account_id": "a"
     }
   }
 }'
{"acknowledged":true}

ubuntu$ curl -XPUT localhost:9200/m/_alias/b -d '
 {
   "routing": "b",
   "filter": {
     "term": {
       "account_id": "b"
     }
   }
 }'
{"acknowledged":true}

ubuntu$ curl -XGET http://localhost:9200/m/_alias?pretty
{
  "m" : {
    "aliases" : {
      "a" : {
        "filter" : {
          "term" : {
            "account_id" : "a"
          }
        },
        "index_routing" : "a",
        "search_routing" : "a"
      },
      "b" : {
        "filter" : {
          "term" : {
            "account_id" : "b"
          }
        },
        "index_routing" : "b",
        "search_routing" : "b"
      }
    }
  }
}

ubuntu$ curl -XPOST localhost:9200/a/n/x?pretty=1 -d '{"account_id": "a", "message_id": "x"}'
{
  "_index" : "m",
  "_type" : "n",
  "_id" : "x",
  "_version" : 1,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "created" : true
}

ubuntu$ curl -XGET localhost:9200/a/n/x?pretty=1
{
  "_index" : "m",
  "_type" : "n",
  "_id" : "x",
  "_version" : 1,
  "_routing" : "a",
  "found" : true,
  "_source" : {
    "account_id" : "a",
    "message_id" : "x"
  }
}

ubuntu$ curl -XGET localhost:9200/b/n/x?pretty=1
{
  "_index" : "m",
  "_type" : "n",
  "_id" : "x",
  "_version" : 1,
  "_routing" : "a",
  "found" : true,
  "_source" : {
    "account_id" : "a",
    "message_id" : "x"
  }
}

ubuntu$ curl -XGET localhost:9200/m/n/x?pretty=1
{
  "_index" : "m",
  "_type" : "n",
  "_id" : "x",
  "_version" : 1,
  "_routing" : "a",
  "found" : true,
  "_source" : {
    "account_id" : "a",
    "message_id" : "x"
  }
}

============= with more shards and replica =================
ubuntu$ curl -XPOST localhost:9200/m?pretty=1 -d '
 {
   "settings": {
     "number_of_shards": 5,
     "number_of_replicas": 1
   }
 }'
{
  "acknowledged" : true
}

ubuntu$ curl -XPUT localhost:9200/m/_alias/a -d '
 {
   "routing": "a",
   "filter": {
     "term": {
       "account_id": "a"
     }
   }
 }'
{"acknowledged":true}

ubuntu$ curl -XPUT localhost:9200/m/_alias/b -d '
 {
   "routing": "b",
   "filter": {
     "term": {
       "account_id": "b"
     }
   }
 }'
{"acknowledged":true}

ubuntu$ curl -XGET http://localhost:9200/m/_alias?pretty
{
  "m" : {
    "aliases" : {
      "a" : {
        "filter" : {
          "term" : {
            "account_id" : "a"
          }
        },
        "index_routing" : "a",
        "search_routing" : "a"
      },
      "b" : {
        "filter" : {
          "term" : {
            "account_id" : "b"
          }
        },
        "index_routing" : "b",
        "search_routing" : "b"
      }
    }
  }
}

ubuntu$ curl -XPOST localhost:9200/a/n/x?pretty=1 -d '{"account_id": "a", "message_id": "x"}'
{
  "_index" : "m",
  "_type" : "n",
  "_id" : "x",
  "_version" : 1,
  "_shards" : {
    "total" : 2,
    "successful" : 1,
    "failed" : 0
  },
  "created" : true
}

ubuntu$ curl -XGET localhost:9200/a/n/x?pretty=1
{
  "_index" : "m",
  "_type" : "n",
  "_id" : "x",
  "_version" : 1,
  "_routing" : "a",
  "found" : true,
  "_source" : {
    "account_id" : "a",
    "message_id" : "x"
  }
}

ubuntu$ curl -XGET localhost:9200/b/n/x?pretty=1
{
  "_index" : "m",
  "_type" : "n",
  "_id" : "x",
  "found" : false
}

ubuntu$ curl -XGET localhost:9200/m/n/x?pretty=1
{
  "_index" : "m",
  "_type" : "n",
  "_id" : "x",
  "found" : false
}

**Comment by jasontedor** [comment] 2016-11-03 21:50
It is because of the routing that you have, you're not hitting the shard that contains the document. With one shard, all routing will hit the sole shard.

**Closed by jasontedor** 2016-11-03 21:50 UTC
Labels: feedback_needed

**Comment by dzhang22** [comment] 2016-11-03 22:14
With one shard, since the alias has a filter, is it supposed that x should not appear under b? In another word, "curl -XGET localhost:9200/b/n/x?pretty=1" should return Found=False?

**Comment by dzhang22** [comment] 2016-11-03 22:33
How to reopen this issue so that it's visible to others who might have more insights?

**Comment by jasontedor** [comment] 2016-11-03 22:43
> With one shard, since the alias has a filter, is it supposed that x should not appear under b?

@dzhang22 Filters do not apply to gets, only to searches.

**Comment by jasontedor** [comment] 2016-11-03 22:44
Relates #3861
