### ISSUE TITLE
RestHighLevelClient - Error on sort string field

### ISSUE THREAD

**Issue by medcl** [elastic/elasticsearch#46362] opened 2019-09-05 04:36 UTC
**Elasticsearch version** (`bin/elasticsearch --version`):
v7.3.1

**Description of the problem including expected versus actual behavior**:

Using RestHighLevelClient to perform search request, sorting on number field is ok, sorting on string field will throw exception. it seems the client only try to decode the returned sort field as number.

**Steps to reproduce**:

Here is the sample document:
```
{
          "times" : 1,
          "ip" : "10.1.35.240",
          "updateTime" : "2019-03-19T23:34:39.000Z",
          "interface" : "Ethernet111/1/31"
        }
```
Here is the sample request:
```
	SearchRequest searchRequest = new SearchRequest();
        SearchSourceBuilder searchSourceBuilder = new SearchSourceBuilder();
        searchRequest.indices(Constant.NETALERT_LOG_TRANS_INDEX_NAME+"-*");
        searchSourceBuilder.query(QueryBuilders.matchAllQuery()).from(0).size(5);
        searchSourceBuilder.sort("updateTime",SortOrder.DESC);
```
This will be throw exception, as a good case, sort on `times` will be successful.

**Provide logs (if relevant)**:

```
		
Message: GatewayApp running failed
Error: xxxx.xxxx.common.error.UnknownException: BeanCreationException: Error creating bean with name 'netAlertBoardTransService': Invocation of init method failed; nested exception is ElasticsearchStatusException[Elasticsearch exception [type=search_phase_execution_exception, reason=]]; nested: ElasticsearchException[Elasticsearch exception [type=class_cast_exception, reason=class java.lang.Long cannot be cast to class org.apache.lucene.util.BytesRef (java.lang.Long is in module java.base of loader 'bootstrap'; org.apache.lucene.util.BytesRef is in unnamed module of loader 'app')]];
	at xxxx.xxxx.common.error.BaseException.translate(BaseException.java:46)
	at xxxx.xxxx.impl.GatewayApp.main(GatewayApp.java:27)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'netAlertBoardTransService': Invocation of init method failed; nested exception is ElasticsearchStatusException[Elasticsearch exception [type=search_phase_execution_exception, reason=]]; nested: ElasticsearchException[Elasticsearch exception [type=class_cast_exception, reason=class java.lang.Long cannot be cast to class org.apache.lucene.util.BytesRef (java.lang.Long is in module java.base of loader 'bootstrap'; org.apache.lucene.util.BytesRef is in unnamed module of loader 'app')]];
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:137)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at xxxx.xxxx.gateway.impl.GatewayApp.main(GatewayApp.java:23)
Caused by: ElasticsearchStatusException[Elasticsearch exception [type=search_phase_execution_exception, reason=]]; nested: ElasticsearchException[Elasticsearch exception [type=class_cast_exception, reason=class java.lang.Long cannot be cast to class org.apache.lucene.util.BytesRef (java.lang.Long is in module java.base of loader 'bootstrap'; org.apache.lucene.util.BytesRef is in unnamed module of loader 'app')]];
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177)
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1727)
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1704)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1467)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1424)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1394)
	at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:930)
	at xxxx.xxxx.log.impl.timer.NetAlertBoardTransService.getLastTranLogTime(NetAlertBoardTransService.java:145)
	at xxxx.xxxx.log.impl.timer.NetAlertBoardTransService.init(NetAlertBoardTransService.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:366)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:311)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:134)
	... 16 more
	Suppressed: org.elasticsearch.client.ResponseException: method [POST], host [https://10.1.240.240:9200], URI [/xxxx-xxxx-*/_search?typed_keys=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&ignore_throttled=true&search_type=query_then_fetch&batched_reduce_size=512&ccs_minimize_roundtrips=true], status line [HTTP/1.1 500 Internal Server Error]
{"error":{"root_cause":[],"type":"search_phase_execution_exception","reason":"","phase":"fetch","grouped":true,"failed_shards":[],"caused_by":{"type":"class_cast_exception","reason":"class java.lang.Long cannot be cast to class org.apache.lucene.util.BytesRef (java.lang.Long is in module java.base of loader 'bootstrap'; org.apache.lucene.util.BytesRef is in unnamed module of loader 'app')"}},"status":500}
		at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:253)
		at org.elasticsearch.client.RestClient.performRequest(RestClient.java:231)
		at org.elasticsearch.client.RestClient.performRequest(RestClient.java:205)
		at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1454)
		... 28 more
Caused by: ElasticsearchException[Elasticsearch exception [type=class_cast_exception, reason=class java.lang.Long cannot be cast to class org.apache.lucene.util.BytesRef (java.lang.Long is in module java.base of loader 'bootstrap'; org.apache.lucene.util.BytesRef is in unnamed module of loader 'app')]]
	at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:491)
	at org.elasticsearch.ElasticsearchException.fromXContent(ElasticsearchException.java:402)
	at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:432)
	at org.elasticsearch.ElasticsearchException.failureFromXContent(ElasticsearchException.java:598)
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:169)
	... 31 more

********************************************************************************

Process finished with exit code 1
```

**Comment by hub-cap** [comment] 2019-09-05 18:57
I cannot reproduce this. My steps to reproduce are as follows, running 7.3.1 docker containers for both elasticsearch and kibana.

I added two documents via kibana console
```
PUT foo/_doc/1
{
          "times" : 1,
          "ip" : "10.1.35.240",
          "updateTime" : "2019-03-19T23:34:39.0001",
          "interface" : "Ethernet111/1/31"
        }

PUT foo/_doc/2
{
          "times" : 1,
          "ip" : "10.1.35.240",
          "updateTime" : "2009-03-19T23:34:39.0001",
          "interface" : "Ethernet111/1/31"
        }
```
I went to my IDE and added the following code
```
 SearchRequest searchRequest = new SearchRequest();
        SearchSourceBuilder searchSourceBuilder = new SearchSourceBuilder();
        searchRequest.indices("foo");
        searchSourceBuilder.query(QueryBuilders.matchAllQuery()).from(0).size(5);
        searchSourceBuilder.sort("updateTime", SortOrder.DESC);

        RestHighLevelClient client = new RestHighLevelClient(
            RestClient.builder(
                new HttpHost("localhost", 9200, "http")));

        SearchResponse response = client.search(searchRequest, RequestOptions.DEFAULT);
        System.err.println(response);
        client.close();
```
and finally the result printed out

```
{
	"took": 2,
	"timed_out": false,
	"_shards": {
		"total": 1,
		"successful": 1,
		"skipped": 0,
		"failed": 0
	},
	"hits": {
		"total": {
			"value": 2,
			"relation": "eq"
		},
		"max_score": 1.0,
		"hits": [{
			"_index": "foo",
			"_type": "_doc",
			"_id": "1",
			"_score": 1.0,
			"_source": {
				"times": 1,
				"ip": "10.1.35.240",
				"updateTime": "2019-03-19T23:34:39.0001",
				"interface": "Ethernet111/1/31"
			}
		}, {
			"_index": "foo",
			"_type": "_doc",
			"_id": "2",
			"_score": 1.0,
			"_source": {
				"times": 1,
				"ip": "10.1.35.240",
				"updateTime": "2009-03-19T23:34:39.0001",
				"interface": "Ethernet111/1/31"
			}
		}]
	}
}
```

does it maybe have something to do with your mapping? have u tried issuing the same search in kibana console?

**Comment by hub-cap** [comment] 2019-10-07 13:26
@medcl i am closing this for now since i did not get feedback. If you can reproduce it, I will gladly take a look. Thanks!

**Closed by hub-cap** 2019-10-07 13:26 UTC
Labels: :Core/Features/Java High Level REST Client, >bug

**Comment by medcl** [comment] 2019-10-08 01:38
Thanks @hub-cap .
