### ISSUE TITLE
ClassCastException DoubleTerms$Bucket cannot be cast to LongTerms$Bucket

### ISSUE THREAD

**Issue by prog8** [elastic/elasticsearch#15609] opened 2015-12-22 15:34 UTC
I see very strange behavior of ES. I use ES 1.7.3. When I execute a query which you can see below I get 

`ClassCastException[org.elasticsearch.search.aggregations.bucket.terms.DoubleTerms$Bucket cannot be cast to org.elasticsearch.search.aggregations.bucket.terms.LongTerms$Bucket` 

```curl 'localhost:9200/index1_2015-12-19,index1_2015-12-20,index1_2015-12-21,index1_2015-12-22,index1_2015-12-23/_search?ignore_unavailable=true' -d '{"query":{"filtered":{"query":{"query_string":{"query":"*","default_operator":"AND"}},"filter":{"range":{"@timestamp":{"gte":"2015-12-20T14:45:36","lte":"2015-12-22T14:45:36"}}}}},"aggs":{"values":{"terms":{"field":"measure","size":10}}}}'```

This doesn't happen when I run the same query on each index separately. This made me think that I have a problem with _mapping. I checked the mapping for each of indices and for all fields I have 

```
          "measure" : {
            "type" : "long",
            "doc_values" : true
          },
```

Am I doing something wrong or it is a bug?

**Comment by jpountz** [comment] 2015-12-22 18:44
Can you check how `measure` is mapped on all types of the following indices:
 - index1_2015-12-19
 - index1_2015-12-20
 - index1_2015-12-21
 - index1_2015-12-22
 - index1_2015-12-23

If it is mapped as a double on any of these types, then it is the cause of the issue that you are seeing.

Otherwise it could mean that you are hit by this bug: #8688.

**Comment by prog8** [comment] 2015-12-22 19:12
On all types this field is mapped to long 

```
"measure" : {
            "type" : "long",
            "doc_values" : true
          }
```

I realized that now it fails also when I query single index (index1_2015-12-22 and index1_2015-12-21). Maybe you are right that I hit the bug #8688

**Comment by jpountz** [comment] 2015-12-22 22:01
Thanks for checking. Then I confirm it is very likely caused by #8688. Unfortunately it is required to reindex the data in order to fix the problem. The only way to prevent it from happening is to either map fields explicitly or use dynamic templates to that elasticsearch never has to decide whether to use a long or a double by itself.

The issue is fixed in 2.0, but you could still have the issue when querying multiple indices. For instance if the first document that is indexed looks like the following:
```
{
  "measure": 3.0
}
```
then the field will be mapped as a double, so if you run an aggregation against several indices including this one and another index that has the field mapped as a long, then you could still get this exception.

**Closed by jpountz** 2015-12-22 22:01 UTC

**Comment by prog8** [comment] 2015-12-22 22:24
I'm considering adding a raw "sub-field" to measure field which would be string. This will prevent from terms aggregation problems. I checked and a few other aggregations work (avg, min, max) so raw field should resolve all problems, including the case you mentioned

**Comment by jpountz** [comment] 2015-12-22 23:24
@prog8 if you control the mappings, then let's map the field explicitly when creating the index (possibly via index templates) as a long instead of using sub fields?
