### ISSUE TITLE
Failed Run or install as service From Program Files

### ISSUE THREAD

**Issue by cstack89** [elastic/elasticsearch#28748] opened 2018-02-20 14:58 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 6.2.1

**Plugins installed**: []

**JVM version** (`java -version`): JDK 1.8.0.151

**OS version** (`uname -a` if on a Unix-like system): Windows Server 2012

**Description of the problem including expected versus actual behavior**:
I unzipped the elasticsearch zip file to a sub-directory under C:\Program Files (x86) and I have JAVA_HOME pointing to C:\Program Files\Java\jdk1.8.0.151. When running elasticsearch-service.bat install I get an error saying 
subdir\elasticsearch-6.2.1\lib\*" "org.elasticsearch.tools.launchers.JvmOptionsParser" "C:\Program was unexpected at this time. The same error occurs if I try to run elasticsearch.bat.

**Steps to reproduce**:

 1. Install Java somewhere in Program Files.
 2. Unzip ES somewhere in Program Files or Program Files (x86).
 3. Try and install as a service. 

**Provide logs (if relevant)**:

**Comment by albertzaharovits** [comment] 2018-02-20 15:11
@elastic/es-core-infra

**Comment by albertzaharovits** [comment] 2018-02-20 15:12
This looks like: https://github.com/elastic/elasticsearch/issues/27289
but should have been fixed in 6.x https://github.com/elastic/elasticsearch/issues/27289#issuecomment-342501587 ?
Is it the same underlying cause @DaveCTurner , can you please take a look?

**Comment by cstack89** [comment] 2018-02-20 15:27
Still early but it looks like it's working for me if I change to delayed expansion for ES_CLASSPATH and ES_JVM_OPTIONS in elasticsearch.bat line 46 (or whichever line sets the JVM_OPTIONS).

And in elasticsearch-service.bat where it sets LOG_OPTS I turned on delayed expansion for LOG_OPTS and  SERVICE_LOG_DIR and also did the delayed expansion change for ES_CLASSPATH and ES_JVM_OPTIONS where it sets up JVM_OPTIONS (around line 104)

**Comment by jasontedor** [comment] 2018-02-20 22:38
This has nothing to do with #27289, the problem is not the spaces. The problem is the closing parenthesis in the path, it busts the `for` statement. I have a fix.

**Comment by jasontedor** [comment] 2018-02-20 22:43
> 2. Unzip ES somewhere in Program Files or Program Files (x86).

This reproduction is not accurate. All is well in `Program Files` but not `Program Files (x86)` (because of the closing `)`.

**Comment by jasontedor** [comment] 2018-02-20 23:06
Also, another reason that #27289 is not relevant: the code tripping here in the batch file is new in 6.2 and does not exist in 5.6 at all.

**Comment by jasontedor** [comment] 2018-02-20 23:12
I opened #28753.

**Closed** 2018-02-21 15:58 UTC
Labels: :Core/Packaging, >bug, v6.2.1

**Comment by jasontedor** [comment] 2018-02-21 16:01
Thanks so much for the report @cstack89.

**Comment by cstack89** [comment] 2018-02-22 18:28
Sorry I've been out of office, I also had to change 

`if "%LOG_OPTS%" == "" set LOG_OPTS=--LogPath "%SERVICE_LOG_DIR%" --LogPrefix "%SERVICE_ID%" --StdError auto --StdOutput auto`

to
 
`if "!LOG_OPTS!" == "" set LOG_OPTS=--LogPath "%SERVICE_LOG_DIR%" --LogPrefix "%SERVICE_ID%" --StdError auto --StdOutput auto`

in elasticsearch-service.bat. Otherwise it does not make it past that line. Are you not seeing that behavior?

**Comment by jasontedor** [comment] 2018-02-26 15:28
@cstack89 No, I did not see that behavior; what are you setting the relevant environment variables here to?
