### ISSUE TITLE
Add Alias information to Slow query logs

### ISSUE THREAD

**Issue by nirmalc** [elastic/elasticsearch#10328] opened 2015-03-30 18:54 UTC
Looks like currently we dont add alias name to slow query logs, Also I doubt if it adds the filter used in alias as well .

May be we need to update -> https://github.com/elastic/elasticsearch/blob/master/src/main/java/org/elasticsearch/index/search/slowlog/ShardSlowLogSearchService.java#L185 and  add alias name + Context.aliasFilter ?

**Comment by javanna** [comment] 2015-03-31 07:49
Marking this for discussion. Might make sense to print out the alias filter, a little less to print out the alias name as an alias might point to multiple indices and in the slowlog we want to know the concrete index that the search executes against.

**Comment by nirmalc** [comment] 2015-03-31 12:27
It's useful to know which app fires most of slow queries if we create separate aliases per app - however filters are more useful

**Comment by clintongormley** [comment] 2015-04-05 13:31
Closing as duplicate of #10044

**Closed by clintongormley** 2015-04-05 13:31 UTC
Labels: :Logging, discuss
