### ISSUE TITLE
Document dealing with defaults 

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch#21706] opened 2016-11-21 15:04 UTC
Elasticsearch 5 introduced [better handling of default settings](https://www.elastic.co/blog/elasticsearch-5-0-0-released#friendly), that has no reference doc.

I wonder if "dealing with defaults" could be linked from cluster settings, index settings, etc.

```
#Show defaults
GET /_cluster/settings?include_defaults

#Return me to default
PUT /_cluster/settings
{
   "persistent": {
      "xpack.monitoring.collection.interval" : null
   }
} 
```

**Comment by javanna** [comment] 2017-05-15 08:41
Resetting cluster settings is documented here: https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-update-settings.html .

**Comment by PhaedrusTheGreek** [comment] 2017-05-15 14:02
Cluster settings is only an example.   [Update Index settings](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-update-settings.html) appears to be missing docs on how to handle defaults, and what else?   Is this not a more generic topic?

**Comment by javanna** [comment] 2017-05-15 14:07
Sure then we are missing to mention the same in the update index settings docs. I don't know where else we should mention resetting settings, these are the two apis that we have that allow to update settings?

**Comment by rjernst** [comment] 2018-03-14 07:43
Duplicate of #22870

**Closed by rjernst** 2018-03-14 07:43 UTC
Labels: :Core/Settings, >docs, adoptme
