### ISSUE TITLE
There are still fetch slowlog on SetFetchSource (false)？

### ISSUE THREAD

**Issue by luoxn28** [elastic/elasticsearch#37641] opened 2019-01-21 03:53 UTC
When es query on java client, it only needs to obtain the document id (_id). SetFetchSource (false) is set in the code, and it is said that there is no fetch stage of query_and_fetch, but I see that query slowlog is still performed by the fetch stage？Thanks for your reply.
```java
SearchRequestBuilder requestBuilder = transportClient.prepareSearch(INDEX).setTypes(TYPE);
requestBuilder.setQuery(query)
		.setSize(size)
		.setFetchSource(false);
```

![image](https://user-images.githubusercontent.com/11440684/51451954-de072c00-1d72-11e9-9688-46a32e1bbd2e.png)

**Comment by jimczi** [comment] 2019-01-21 07:50
Hi @luoxn28 ,
what you see is expected, the fetch phase is always executed even if `_source` is disabled.
We use this phase to retrieve the `_id` of the document (the search phase retrieves the internal document id which is different), the `_source` (if not disabled) and many other things like stored fields, doc values field or highlighting. Furthermore the `query_and_fetch` execution is now reserved to queries that target a single shard. 
Since we reserve github for confirmed bugs and feature requests I am going to close this issue, however if you want more informations regarding the execution of the search phases you can post in the [discuss forum](https://discuss.elastic.co/c/elasticsearch) where me or someone from the community will be glad to help.

**Closed by jimczi** 2019-01-21 07:50 UTC
