### ISSUE TITLE
[CI] MlDistributedFailureIT#testFullClusterRestart

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#58533] opened 2020-06-25 09:57 UTC
**Build scan**: https://gradle-enterprise.elastic.co/s/jeoql6ppg2iku

**Repro line**: `./gradlew ':x-pack:plugin:ml:internalClusterTest' --tests "org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.testFullClusterRestart" -Dtests.seed=DD96E9D2F4821BAF -Dtests.security.manager=true -Dtests.locale=fr-BE -Dtests.timezone=US/Mountain -Druntime.java=11`

**Reproduces locally?**: No

**Applicable branches**: `master`

**Failure history**:
https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!f,value:7200000),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'class:%20%22org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT%22%20test:%20%22testFullClusterRestart%22'),sort:!(time,desc))

**Failure excerpt**:
```
java.lang.AssertionError: failed to reach a stable cluster of [3] nodes. Tried via [node_t0]. last cluster state:
12:19:37     cluster uuid: DIXb_u8PSQe4QvzUrb8E9g [committed: true]
12:19:37     version: 64
12:19:37     state uuid: PbzLzbRtTVuznkxxS6LdXA
12:19:37     from_diff: false
12:19:37     meta data version: 56
12:19:37        coordination_metadata:
12:19:37           term: 4
12:19:37           last_committed_config: VotingConfiguration{libhdxGrQDCted5Sub97WQ,grRXwwwHR8WYarJGUllUpA,GOWk8mE8RXyF1-L_okWoSw}
12:19:37           last_accepted_config: VotingConfiguration{libhdxGrQDCted5Sub97WQ,grRXwwwHR8WYarJGUllUpA,GOWk8mE8RXyF1-L_okWoSw}
12:19:37           voting tombstones: []
12:19:37        [.ml-config/MZW2ZlLOT56WBeI8jDxqQQ]: v[9], mv[1], sv[2], av[1]
12:19:37           0: p_term [2], isa_ids [JYNICHv3RA2sxmU54Mvkvg, B82JZA2iSNWq0CWK5oIlJw]
12:19:37        [.ml-anomalies-shared/rwyxayFaQeaEmX4Rd2huSQ]: v[12], mv[1], sv[2], av[2]
12:19:37           0: p_term [2], isa_ids [NAd8QNw5QNaZs82sR6s2lQ, 7SI08RWpSz6p0BomCjOCyQ]
12:19:37        [.ml-annotations-6/QFh701rrRFusRV3p5L89oQ]: v[12], mv[1], sv[2], av[2]
12:19:37           0: p_term [2], isa_ids [Y7AXS8N8RnGJ3cdI_PhqcA, RkqtUhAASkaLrEGWWiNZBA]
12:19:37        [data/Oo5baM63RoCSadULUGgDUw]: v[6], mv[1], sv[1], av[1]
12:19:37           0: p_term [2], isa_ids [mYVzh39-RKiSq8VPNqg8wg, GSSkfs9gQ-K-JYH0R24v_w]
12:19:37        [.ml-state-000001/UW6lrZRYSK2DXNHrGY9B6A]: v[13], mv[1], sv[2], av[1]
12:19:37           0: p_term [2], isa_ids [yT6j-nKiS--cSbuTF-uoiw, GCzg69rwTgmxnqmN33HZ8A]
12:19:37        [.ml-notifications-000001/JHJYeK8STb6HnWQBLr73MQ]: v[10], mv[1], sv[2], av[1]
12:19:37           0: p_term [2], isa_ids [O_mgdTFnTf2Iun6JdEOk8Q, hNuzXg5PQUqEdC_fIXMyLQ]
12:19:37     metadata customs:
12:19:37        index_lifecycle: {
12:19:37       "policies" : {
12:19:37         "ml-size-based-ilm-policy" : {
12:19:37           "policy" : {
12:19:37             "phases" : {
12:19:37               "hot" : {
12:19:37                 "min_age" : "0ms",
12:19:37                 "actions" : {
12:19:37                   "rollover" : {
12:19:37                     "max_size" : "50gb"
12:19:37                   }
12:19:37                 }
12:19:37               }
12:19:37             }
12:19:37           },
12:19:37           "headers" : { },
12:19:37           "version" : 1,
12:19:37           "modified_date" : 1593076621794,
12:19:37           "modified_date_string" : "2020-06-25T09:17:01.794Z"
12:19:37         },
12:19:37         "slm-history-ilm-policy" : {
12:19:37           "policy" : {
12:19:37             "phases" : {
12:19:37               "hot" : {
12:19:37                 "min_age" : "0ms",
12:19:37                 "actions" : {
12:19:37                   "rollover" : {
12:19:37                     "max_size" : "50gb",
12:19:37                     "max_age" : "30d"
12:19:37                   }
12:19:37                 }
12:19:37               },
12:19:37               "delete" : {
12:19:37                 "min_age" : "90d",
12:19:37                 "actions" : {
12:19:37                   "delete" : {
12:19:37                     "delete_searchable_snapshot" : true
12:19:37                   }
12:19:37                 }
12:19:37               }
12:19:37             }
12:19:37           },
12:19:37           "headers" : { },
12:19:37           "version" : 1,
12:19:37           "modified_date" : 1593076620773,
12:19:37           "modified_date_string" : "2020-06-25T09:17:00.773Z"
12:19:37         }
12:19:37       },
```

There are also entries like the following in stacktrace:
```
12:23:34   1> org.elasticsearch.ElasticsearchParseException: No processor type exists with name [script]
12:23:34   1> 	at org.elasticsearch.ingest.ConfigurationUtils.newConfigurationException(ConfigurationUtils.java:316) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
12:23:34   1> 	at org.elasticsearch.ingest.ConfigurationUtils.readProcessor(ConfigurationUtils.java:446) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
12:23:34   1> 	at org.elasticsearch.ingest.ConfigurationUtils.readProcessor(ConfigurationUtils.java:399) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
12:23:34   1> 	at org.elasticsearch.ingest.ConfigurationUtils.readProcessorConfigs(ConfigurationUtils.java:337) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
12:23:34   1> 	at org.elasticsearch.ingest.Pipeline.create(Pipeline.java:74) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
12:23:34   1> 	at org.elasticsearch.ingest.IngestService.validatePipeline(IngestService.java:321) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
12:23:34   1> 	at org.elasticsearch.ingest.IngestService.putPipeline(IngestService.java:226) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
12:23:34   1> 	at org.elasticsearch.action.ingest.PutPipelineTransportAction.lambda$masterOperation$0(PutPipelineTransportAction.java:84) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
12:23:34   1> 	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
12:23:34   1> 	at org.elasticsearch.client.node.NodeClient.lambda$executeLocally$0(NodeClient.java:91) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
12:23:34   1> 	at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:175) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
12:23:34   1> 	at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:169) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
12:23:34   1> 	at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.finishHim(TransportNodesAction.java:237) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
12:23:34   1> 	at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.onOperation(TransportNodesAction.java:214) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
12:23:34   1> 	at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$1.handleResponse(TransportNodesAction.java:192) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
12:23:34   1> 	at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$1.handleResponse(TransportNodesAction.java:184) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
12:23:34   1> 	at org.elasticsearch.transport.TransportService$6.handleResponse(TransportService.java:573) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
12:23:34   1> 	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1102) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
12:23:34   1> 	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1180) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
12:23:34   1> 	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1160) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
12:23:34   1> 	at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:52) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
12:23:34   1> 	at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:245) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
12:23:34   1> 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:72) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
12:23:34   1> 	at org.elasticsearch.transport.TransportService$8.doRun(TransportService.java:741) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
12:23:34   1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:706) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
12:23:34   1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
12:23:34   1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
12:23:34   1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
```

Similar issue from the past: #44744

**Comment by benwtrent** [comment] 2020-06-25 12:26
closing as duplicate of: https://github.com/elastic/elasticsearch/issues/58532

**Closed by benwtrent** 2020-06-25 12:26 UTC
Labels: :ml, >test-failure
