### ISSUE TITLE
Range Aggregation Returns No Results on 5.0.0-alpha1

### ISSUE THREAD

**Issue by tebriel** [elastic/elasticsearch#17795] opened 2016-04-15 18:54 UTC
**Elasticsearch version**:
5.0.0-alpha1

**JVM version**:
java 8

**OS version**:

Elasticsearch Docker Image (based on java:8-jre)

**Description of the problem including expected versus actual behavior**:

I've got a bunch of documents like this:

```
{
  "_index": "test-rtes",
  "_type": "rtesevent",
  "_id": "AVQbPk8vbhx2Mf7tEPJS",
  "_score": 1,
  "_source": {
    "call": {
      "risk_score": 44.8285,
      "site_name": "atlanta",
      "toll_free_number": ""
    },
    "current_time": "2016-04-15T18:45:49Z",
    "event_id": "c9a89d35-f166-47f1-b9f3-5d9a9d7f0582",
    "event_type": "risk_score",
    "version": 1
  },
  "fields": {
    "current_time": [
      1460745949000
    ]
  }
}
```

And I want to aggregate on call.risk_score:

```
{
  "size": 0,
  "aggs": {
    "2": {
      "range": {
        "field": "call.risk_score",
        "ranges": [
          {
            "from": 0,
            "to": 50
          },
          {
            "from": 51,
            "to": 100
          }
        ],
        "keyed": true
      }
    }
  }
}
```

And I always get 0 results back:

```
{
  "_shards": {
    "failed": 0,
    "successful": 5,
    "total": 5
  },
  "aggregations": {
    "2": {
      "buckets": {
        "0.0-50.0": {
          "doc_count": 0,
          "from": 0.0,
          "from_as_string": "0.0",
          "to": 50.0,
          "to_as_string": "50.0"
        },
        "51.0-100.0": {
          "doc_count": 0,
          "from": 51.0,
          "from_as_string": "51.0",
          "to": 100.0,
          "to_as_string": "100.0"
        }
      }
    }
  },
  "hits": {
    "hits": [],
    "max_score": 0.0,
    "total": 1805264
  },
  "timed_out": false,
  "took": 119
}
```

the relevant chunk of my mapping is:

```
    "mappings": {
      "rtesevent": {
        "properties": {
          "call": {
            "properties": {
              "risk_score": {
                "type": "float"
              }
            },
```

Am I holding it wrong? I tried generating the query in Kibana 5.0.0-alpha1 and it returns 0 results as well. A count query returns many results.

**Comment by dakrone** [comment] 2016-04-15 20:39
@tebriel I'm not able to reproduce this, do you have a small reproduction you can share?

## Create Index<a id="orgheadline1"></a>

```es
POST /i
{
  "mappings": {
    "d": {
      "properties": {
        "call": {
          "properties": {
            "risk_score": {
              "type": "float"
            }
          }
        }
      }
    }
  }
}
```

```es
{"acknowledged":true}
```

```es
GET /i/d/_mapping?pretty
{}
```

```es
{
  "i" : {
    "mappings" : {
      "d" : {
        "properties" : {
          "call" : {
            "properties" : {
              "risk_score" : {
                "type" : "float"
              }
            }
          }
        }
      }
    }
  }
}
```

## Index Doc<a id="orgheadline2"></a>

```es
POST /i/d/1
{
  "call": {
    "risk_score": 44.8285,
    "site_name": "atlanta",
    "toll_free_number": ""
  },
  "current_time": "2016-04-15T18:45:49Z",
  "event_id": "c9a89d35-f166-47f1-b9f3-5d9a9d7f0582",
  "event_type": "risk_score",
  "version": 1
}
```

```es
{"_index":"i","_type":"d","_id":"1","_version":1,"_shards":{"total":2,"successful":1,"failed":0},"created":true}
```

## Range Agg<a id="orgheadline3"></a>

```es
POST /i/_search?pretty
{
  "size": 0,
  "aggs": {
    "2": {
      "range": {
        "field": "call.risk_score",
        "ranges": [
          {
            "from": 0,
            "to": 50
          },
          {
            "from": 51,
            "to": 100
          }
        ],
        "keyed": true
      }
    }
  }
}
```

```es
{
  "took" : 37,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 0.0,
    "hits" : [ ]
  },
  "aggregations" : {
    "2" : {
      "buckets" : {
        "0.0-50.0" : {
          "from" : 0.0,
          "from_as_string" : "0.0",
          "to" : 50.0,
          "to_as_string" : "50.0",
          "doc_count" : 1
        },
        "51.0-100.0" : {
          "from" : 51.0,
          "from_as_string" : "51.0",
          "to" : 100.0,
          "to_as_string" : "100.0",
          "doc_count" : 0
        }
      }
    }
  }
}
```

**Comment by clintongormley** [comment] 2016-05-24 10:35
No further feedback.  Closing

**Closed by clintongormley** 2016-05-24 10:35 UTC
Labels: :Aggregations, feedback_needed, Pioneer Program
