### ISSUE TITLE
it can not start the shard without the translog file

### ISSUE THREAD

**Issue by Macln** [elastic/elasticsearch#16402] opened 2016-02-03 07:04 UTC
I'm tring to start a shard without the translog files or with the damaged translog files using elasticsearch 2.0,but it's failed and print some exception,such as:
```
NoSuchFileException[/data/.../.../{index}/0/translog/translog.ckp
```
or
```
NotSerializableExceptionWrapper[/data/.../.../{index}/0/translog/translog.ckp
```

I think the translog from the shard is invasive too strong with the index's shard,so a shard has data,but it can't start just because of the lacking translog files.

**Comment by bleskes** [comment] 2016-02-03 07:43
Indeed we fail starting a shard if it misses the necessary translog files. The reason for this that opening shard will amount to loss of data. Note that we rely on another shard copy to take over, just like we do in any case of corruption. Can you elaborate on what made you delete the translog file? 

I'm closing this issue as things work as intended. We can continue the discussion and if it turns out something is wrong, we can surely reopen it.

**Closed by bleskes** 2016-02-03 07:43 UTC

**Comment by Macln** [comment] 2016-02-03 07:59
@bleskes this problem can't deal with it? I think not only because of missing the translog files or damaged translog files which be known as notSerializableExceptionWrapper files that the index's shard cant 't start,just those shards possess data.
why can't fix the translog file,if the translog files is missing or damaged when starting the shards.

**Comment by bleskes** [comment] 2016-02-03 08:03
I’m not sure  I follow you completely. The high level thinking is that the translog stores data just like lucene and any corruption there is treated the same way as corruption elsewhere. If you have another copy (i.e., replica) ES will recover on it’s own. Otherwise you sadly need to reindex.

**Comment by bleskes** [comment] 2016-02-03 14:02
People have reminded me that we do have an escape route for these cases - you can set `index.engine.force_new_translog` to true on the index , wait for it to recover and reset back to false. Note though that leaving it on true is dangerous - if the cluster shutsdown and restarts it will ignore the translog when recovering (and loose data).

**Comment by Macln** [comment] 2016-02-04 03:53
@bleskes OK,thanks,I see,I'm going to try.
