### ISSUE TITLE
YAML REST tests fail when mixing `-Dtests.method` and `-Dtests.iters`

### ISSUE THREAD

**Issue by axw** [elastic/elasticsearch#102194] opened 2023-11-15 06:13 UTC
Taking the reproduction command from https://github.com/elastic/elasticsearch/issues/101929, I added `-Dtests.iters=100` to try and get it to fail reliably locally:

```
./gradlew ':x-pack:plugin:apm-data:yamlRestTest' --tests "org.elasticsearch.xpack.apmdata.APMYamlTestSuiteIT" -Dtests.method="test {yaml=/10_apm/Test metrics-apm.app-* dynamic mapping}" -Dtests.seed=AD0634F5391AC4AF -Dtests.locale=es-PE -Dtests.timezone=Etc/GMT-1 -Druntime.java=21 -Dtests.iters=2 -Dtests.failfast=true
```

This fails with the following error:

```
> Task :x-pack:plugin:apm-data:yamlRestTest FAILED
Nov 14, 2023 3:35:27 PM sun.util.locale.provider.LocaleProviderAdapter <clinit>
WARNING: COMPAT locale provider will be removed in a future release

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':x-pack:plugin:apm-data:yamlRestTest'.
> No tests found for given includes: [**/*$*.class](exclude rules) [org.elasticsearch.xpack.apmdata.APMYamlTestSuiteIT](--tests filter)
```

Without the `-Dtests.iters=2` it works. With `-Dtests.iters=2`, but without the `-Dtests.method=...` it also works.

**Comment by mark-vieira** [comment] 2023-11-15 23:13
This is actually a bug in the randomized runner when you use `tests.iters` in conjunction with `tests.method`. The issue is that `tests.iters` generates a bunch of dynamic method descriptors, which are then filtered by what we pass to `tests.method`. The workaround here is to include an additional glob `*` in your method filter. So something like `-Dtests.method="test {yaml=/10_apm/Test metrics-apm.app-* dynamic mapping *}"` would work in this case.

**Comment by mark-vieira** [comment] 2023-11-16 15:56
Since there's nothing we can really do on our end here I'm going to close this issue. You can feel free to open an issue against https://github.com/randomizedtesting/randomizedtesting.

**Closed by mark-vieira** 2023-11-16 15:56 UTC
Labels: >bug, :Delivery/Build, Team:Delivery
