### ISSUE TITLE
6.2.2 timestamps could be out of order

### ISSUE THREAD

**Issue by maverick220** [elastic/elasticsearch#29128] opened 2018-03-18 09:28 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 6.2.2

**Plugins installed**: None

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system): Windows

**Description of the problem including expected versus actual behavior**: 
In 6.2.2, we are seeing an issue if 2 (or more) log messages came out with the same *millisecond* in their timestamp, their order in Kibana output (if sorted by timestamps) could be unpredictably messed up/misordered.

Thanks!

**Comment by dadoonet** [comment] 2018-03-18 10:07
I think it's a duplicate of #10005 where nanoseconds could help. So I'm going to close it.

If you don't think it is, please open a question on discuss.elastic.co where we can discuss about it.

**Closed by dadoonet** 2018-03-18 10:07 UTC

**Comment by maverick220** [comment] 2018-03-18 10:20
Don't think this is the same. I'll revert to the elastic.co board.

**Comment by dadoonet** [comment] 2018-03-18 10:27
@maverick220 Sure?

From #10005

> The biggest impact of this is during sorting of search results. If you sort chronologically, newest-first, by a date field, documents with the same date will probably be sorted incorrectly (because they match). This is often reported by users seeing events "out of order" when they have the same timestamp. Specific example being sorting by date and seeing events in newest-first order, unless there is a tie, in which case oldest-first (or first-written?) appears. This causes a bit of confusion for the ELK use case.

Isn't what you reported?
