### ISSUE TITLE
Reindex fails if dest is alias using `is_write_index`

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#41667] opened 2019-04-30 08:58 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 6.7.1, 7.0, 7.x, master

**Description of the problem including expected versus actual behavior**:
Reindexing when the destination is an alias using `is_write_index` (i.e. an alias with multiple indices but only one set with `is_write_index: true`) fails with:
```
[elasticsearch] java.lang.IllegalStateException: alias [my_data] has more than one write index [index-1,index-2]
[elasticsearch]         at org.elasticsearch.cluster.metadata.AliasOrIndex$Alias.computeAndValidateWriteIndex(AliasOrIndex.java:154) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.cluster.metadata.MetaData$Builder.lambda$buildAliasAndIndexLookup$1(MetaData.java:1230) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[elasticsearch]         at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
[elasticsearch]         at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
[elasticsearch]         at java.util.TreeMap$ValueSpliterator.forEachRemaining(TreeMap.java:2890) ~[?:?]
[elasticsearch]         at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
[elasticsearch]         at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
[elasticsearch]         at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
[elasticsearch]         at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
[elasticsearch]         at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
[elasticsearch]         at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
[elasticsearch]         at org.elasticsearch.cluster.metadata.MetaData$Builder.buildAliasAndIndexLookup(MetaData.java:1230) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.cluster.metadata.MetaData$Builder.build(MetaData.java:1193) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$IndexCreationTask.execute(MetaDataCreateIndexService.java:557) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:687) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:310) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:210) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:142) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:687) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[elasticsearch]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
[elasticsearch]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
[elasticsearch]         at java.lang.Thread.run(Thread.java:835) [?:?]
```

This should work since indexing into an alias with multiple indexes is now permitted as long as the alias is using `is_write_index`.

**Steps to reproduce**:

```
GET _cat/indices?v

DELETE index-1

PUT index-1
{
  "aliases": {
    "my_data": {
      "is_write_index": true
    }
  }
}

POST my_data/_doc/1
{
  "foo":"bar"
}

POST my_data/_rollover
{
  "conditions": {
    "max_docs": 1
  }
}

GET my_data

POST my_data/_doc/2
{
  "foo":"baz"
}

POST other-index/_doc/3
{
  "foo": "bof"
}

# This fails with the above error
POST _reindex
{
  "source": {
    "index": "other-index"
  },
  "dest": {
    "index": "my_data"
  }
}
```

**Comment by henningandersen** [comment] 2019-05-01 07:34
@colings86 , trying to reproduce this using the steps above, I do get an error during `_reindex`, which seems to be the error addressed in #41677. But the error happens directly on the reindex request thread and not during a cluster state update task as indicated by above stack trace.

I would imagine the above exception comes from the rollover. I have not been able to figure out how that could be triggered from reindex and hope you can give a hint on that?

**Closed** 2019-05-08 07:27 UTC
Labels: :Distributed/Reindex, >bug
