### ISSUE TITLE
[CI] SearchStatsIT & IndexingIT failures

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#37179] opened 2019-01-07 09:44 UTC
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1090/console

This is a reproducible failure that errors with 

```
  2> java.lang.AssertionError
  2>    at __randomizedtesting.SeedInfo.seed([33185699574722A3]:0)
  2>    at org.elasticsearch.action.search.SearchPhaseController$TopDocsStats.getTotalHits(SearchPhaseController.java:763)
  2>    at org.elasticsearch.action.search.SearchPhaseController.reducedQueryPhase(SearchPhaseController.java:510)
  2>    at org.elasticsearch.action.search.SearchPhaseController.reducedQueryPhase(SearchPhaseController.java:421)
  2>    at org.elasticsearch.action.search.SearchPhaseController.reducedScrollQueryPhase(SearchPhaseController.java:412)
  2>    at org.elasticsearch.action.search.SearchScrollQueryThenFetchAsyncAction$1.run(SearchScrollQueryThenFetchAsyncAction.java:71)
  2>    at org.elasticsearch.action.search.SearchScrollAsyncAction$1.innerOnResponse(SearchScrollAsyncAction.java:189)
  2>    at org.elasticsearch.action.search.SearchActionListener.onResponse(SearchActionListener.java:45)
```

```
./gradlew :server:integTest \
  -Dtests.seed=33185699574722A3 \
  -Dtests.class=org.elasticsearch.search.stats.SearchStatsIT \
  -Dtests.method="testOpenContexts" \
  -Dtests.security.manager=true \
  -Dtests.locale=ga-IE \
  -Dtests.timezone=Africa/Windhoek \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

**Comment by davidkyle** [comment] 2019-01-07 09:48
Muted on master in 7cc749dcedd7241d717abd6d5855b15a82156cbf

**Comment by davidkyle** [comment] 2019-01-07 10:14
`FieldLevelSecurityTests` failed with the same assertion.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=java11,nodes=virtual&&linux/165/console

Does not reproduce
```
./gradlew :x-pack:plugin:security:unitTest \
  -Dtests.seed=6624CB3E3B1A0E76 \
  -Dtests.class=org.elasticsearch.integration.FieldLevelSecurityTests \
  -Dtests.method="testScroll" \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-Latn-ME \
  -Dtests.timezone=Africa/Malabo \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

```
Caused by: java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([6624CB3E3B1A0E76]:0)
	at org.elasticsearch.action.search.SearchPhaseController$TopDocsStats.getTotalHits(SearchPhaseController.java:763)
	at org.elasticsearch.action.search.SearchPhaseController.reducedQueryPhase(SearchPhaseController.java:510)
	at org.elasticsearch.action.search.SearchPhaseController.reducedQueryPhase(SearchPhaseController.java:421)
	at org.elasticsearch.action.search.SearchPhaseController.reducedScrollQueryPhase(SearchPhaseController.java:412)
```

**Comment by jimczi** [comment] 2019-01-07 11:33
> If it's a completely different problem and you'd prefer it raised in a new issue let me know.

Yes this is a different issue, the one described here should only happen on master.

**Comment by droberts195** [comment] 2019-01-07 11:59
> Yes this is a different issue, the one described here should only happen on master

OK cool.  I transferred it to #37185.

**Comment by davidkyle** [comment] 2019-01-07 14:51
I think this assertion is also causing failures in the mixed cluster test `IndexingIT` as the error takes down the node.

From the log file:
```
[2019-01-07T00:42:11,829][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [node-3] fatal error in thread [elasticsearch[node-3][search][T#24]], exiting
java.lang.AssertionError: null
	at org.elasticsearch.action.search.SearchPhaseController$TopDocsStats.getTotalHits(SearchPhaseController.java:763) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
	at org.elasticsearch.action.search.SearchPhaseController.reducedQueryPhase(SearchPhaseController.java:510) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
	at org.elasticsearch.action.search.SearchPhaseController.reducedQueryPhase(SearchPhaseController.java:421) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
	at org.elasticsearch.action.search.SearchPhaseController$1.reduce(SearchPhaseController.java:737) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
	at org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:101) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
	at org.elasticsearch.action.search.FetchSearchPhase.access$000(FetchSearchPhase.java:44) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
	at org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:86) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:759) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=centos/165/console

**Comment by jimczi** [comment] 2019-01-09 12:18
`IndexingIT` is still failing with the same failure:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+bwc-tests/307/console
I am not able to reproduce yet but the previous fix is not enough so reopening.

**Closed** 2019-01-09 22:11 UTC
Labels: :Search/Search, >test-failure
