### ISSUE TITLE
Reindex-from-remote should use preemptive authorization if username and password are configured

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#22328] opened 2016-12-22 16:10 UTC
Reported [here](https://discuss.elastic.co/t/reindex-from-remote-not-working/69625). Currently if reindex-from-remote attempts to talk to a server that doesn't send `403 forbidden` when it needs a password then it'll never try to send the password.

**Comment by nik9000** [comment] 2017-01-10 19:21
Blocking this on #21336.

**Comment by nik9000** [comment] 2017-01-10 19:24
I got a start on the test for this: https://github.com/elastic/elasticsearch/compare/master...nik9000:reindex_from_remote_preemptive?expand=1

**Comment by javanna** [comment] 2017-05-15 08:37
@nik9000 do you still plan on picking this back up? Or shall we mark adoptme?

**Comment by bleskes** [comment] 2018-05-22 10:47
@javanna do you think this can be labeled as a low hanging fruit?

**Comment by javanna** [comment] 2018-05-22 10:59
@bleskes I guess so, I added the low hanging fruit label.

**Comment by aaronoah** [comment] 2018-07-22 04:03
Does anyone into this already? Otherwise, I will try and pick it up.

**Comment by bleskes** [comment] 2018-07-22 07:13
@aaronoah go for it! let us know if you need some guidance. Also just to make sure - please check  our [contribution readme](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md).

**Comment by aaronoah** [comment] 2018-07-26 15:15
@bleskes I'm having an issue running `gradlew check`, here's the discuss post: https://discuss.elastic.co/t/es-gradle-check-error/141051

**Comment by bleskes** [comment] 2018-07-31 14:13
@aaronoah it seems you're getting help on the forums. That's the right place for it. Thanks again.

**Comment by CamW** [comment] 2019-03-04 19:35
I had a look through #21336, bc5d37bb21cd0bd02e14fafa9a77c9c9e3750fa2 and the test above from @nik9000 to see if this was something that I wanted to take on. It looks like this should already work as desired. bc5d37bb21cd0bd02e14fafa9a77c9c9e3750fa2 looks like it sets up preemptive auth by default and allows for disabling it as described [here](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/_basic_authentication.html). TransportReindexAction.java makes use of the RestClientBuilder but does not call disableAuthCaching on the HttpAsyncClientBuilder, leaving preemptive auth on for reindex-from-remote. Am I missing something?

**Comment by CamW** [comment] 2019-03-11 18:57
Confirmed this with a 6.6 container. Curling [this](https://www.elastic.co/guide/en/elasticsearch/reference/master/docs-reindex.html#reindex-from-remote) results in a request to the host with appropriate basic auth header set on the initial GET. `Authorization: Basic dXNlcjpwYXNz`

**Comment by henningandersen** [comment] 2019-03-25 14:39
Confirmed that authorization is included in first request on master. Closing this issue.

**Closed by henningandersen** 2019-03-25 14:39 UTC
Labels: :Distributed/CRUD, >bug, good first issue, help wanted
