### ISSUE TITLE
simple_query_string doesn't work with CCS between ES 6 and ES 5

### ISSUE THREAD

**Issue by consulthys** [elastic/elasticsearch#38889] opened 2019-02-14 09:42 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): CCS between ES 6.5.1 and ES 5.6.2

**Plugins installed**: [ N/A ]

**JVM version** (`java -version`): 1.8

**OS version** (`uname -a` if on a Unix-like system): Tested on Mac + Linux

**Description of the problem including expected versus actual behavior**:

When sending a `simple_query_string` query to an ES6 cluster to be run on a remote ES5 cluster via cross-cluster search, the query fails.

**Steps to reproduce**:

1. Spin up an ES 5.6.2 node (cluster-name: `es-562`)
2. Spin up an ES 6.5.1 node (cluster-name: `es-651`)
3. Create a test index on `es-562`
```
PUT test/doc/1
{
  "test": "John"
}
```
4. Set up CCS on `es-651`
```
PUT _cluster/settings
{
  "persistent": {
    "search": {
      "remote": {
        "es-562": {
          "seeds": [
            "localhost:9301"
          ]
        }
      }
    }
  }
}
```
5. Search john directly from `es-562` (no CCS)
``` 
POST test/_search
{
  "query": {
    "bool": {
      "filter": [
        {
          "simple_query_string": {
            "query": "john",
            "fields": [
              "test"
            ]
          }
        }
      ]
    }
  }
}
```
**=> Document 1 is returned**

5. Search john from `es-651` (via CCS)
``` 
POST es-562:test/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "simple_query_string": {
            "query": "john",
            "fields": [
              "test"
            ]
          }
        }
      ]
    }
  }
}
```
**=> ERROR**
```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "Unknown NamedWriteable [org.elasticsearch.index.query.QueryBuilder][]"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "es-562:test",
        "node": "8Gql5xv_T7C8oXtPsWb4pQ",
        "reason": {
          "type": "illegal_argument_exception",
          "reason": "Unknown NamedWriteable [org.elasticsearch.index.query.QueryBuilder][]"
        }
      }
    ],
    "caused_by": {
      "type": "illegal_argument_exception",
      "reason": "Unknown NamedWriteable [org.elasticsearch.index.query.QueryBuilder][]",
      "caused_by": {
        "type": "illegal_argument_exception",
        "reason": "Unknown NamedWriteable [org.elasticsearch.index.query.QueryBuilder][]"
      }
    }
  },
  "status": 400
}
```
Replacing `must` by `should` produces the same error.
Replacing `must` by `filter` yields another similar error:
```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_state_exception",
        "reason": "unexpected byte [0x02]"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "es-562:test",
        "node": "8Gql5xv_T7C8oXtPsWb4pQ",
        "reason": {
          "type": "illegal_state_exception",
          "reason": "unexpected byte [0x02]"
        }
      }
    ],
    "caused_by": {
      "type": "illegal_state_exception",
      "reason": "unexpected byte [0x02]",
      "caused_by": {
        "type": "illegal_state_exception",
        "reason": "unexpected byte [0x02]"
      }
    }
  },
  "status": 500
}
```

Finally, it is also worth noting that replacing `simple_query_string` with `query_string` (whether `must`, `filter` or `should`) works and yields document 1. 

So it clearly seems that CCS doesn't like `simple_query_string` and that feels like a bug. I'm all ears if anyone has any idea. Thanks much in advance.

**Comment by javanna** [comment] 2019-02-15 14:42
thanks a lot for reporting this @consulthys ! Weird that we have not found it before, this is caused by a serialization bug in simple query string that was introduced with `6.0.0-alpha1`. All 6.x releases are affected, meaning that whenever simple query string is serialized between 5.6 and 6.x, the read and write end don't match causing the errors that you've seen. It is not a CCS bug specifically, mixed clusters are affected too.

**Comment by consulthys** [comment] 2019-02-15 14:57
Thanks a lot for looking into and fixing this @javanna, I'm glad you found the issue!

For others stumbling onto the same issue, we've reverted back to use `query_string` instead (which is admittedly less safe and more sensible to user input), but at least doesn't suffer from the same serialization issue. For now, that will do.

Thanks again, much appreciated!

**Comment by jimczi** [comment] 2019-04-08 08:29
Closed by https://github.com/elastic/elasticsearch/pull/21504

**Closed by jimczi** 2019-04-08 08:29 UTC
Labels: :Search/Search
