### ISSUE TITLE
[CI] DownsampleActionIT testRollupIndex failing

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#105437] opened 2024-02-13 06:53 UTC
The test failed 9 times in the last month and there seems to be a history of failures in the past, at least these ones fail with the same error message:

* https://github.com/elastic/elasticsearch/issues/95447
* https://github.com/elastic/elasticsearch/issues/95156

**Build scan:**
https://gradle-enterprise.elastic.co/s/k4rkaj5pl7yvo/tests/:x-pack:plugin:ilm:qa:multi-node:javaRestTest/org.elasticsearch.xpack.ilm.actions.DownsampleActionIT/testRollupIndex

**Reproduction line:**
```
./gradlew ':x-pack:plugin:ilm:qa:multi-node:javaRestTest' --tests "org.elasticsearch.xpack.ilm.actions.DownsampleActionIT.testRollupIndex" -Dtests.seed=60DC99456040484D -Dtests.locale=it -Dtests.timezone=America/Montserrat -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
[Failure dashboard for `org.elasticsearch.xpack.ilm.actions.DownsampleActionIT#testRollupIndex`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testRollupIndex'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.ilm.actions.DownsampleActionIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.AssertionError: Cannot retrieve rollup index name

  at __randomizedtesting.SeedInfo.seed([60DC99456040484D:86F8E813090C4181]:0)
  at org.junit.Assert.fail(Assert.java:89)
  at org.junit.Assert.assertTrue(Assert.java:42)
  at org.junit.Assert.assertNotNull(Assert.java:713)
  at org.elasticsearch.xpack.ilm.actions.DownsampleActionIT.testRollupIndex(DownsampleActionIT.java:203)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by kkrik-es** [comment] 2024-04-05 13:14
Relevant log entries:

```
  1> [2024-02-13T02:38:06,052][INFO ][o.e.x.i.a.DownsampleActionIT] [testRollupIndex] before test
  1> [2024-02-13T02:38:06,055][INFO ][o.e.x.i.a.DownsampleActionIT] [testRollupIndex] initializing REST clients against [http://[::1]:46243, http://127.0.0.1:46367, http://[::1]:35351, http://127.0.0.1:33495, http://[::1]:40151, http://127.0.0.1:44007, http://[::1]:45997, http://127.0.0.1:37807]
  1> [2024-02-13T02:38:06,089][WARN ][o.e.x.i.a.DownsampleActionIT] [testRollupIndex] This test is running on the legacy test framework; historical features from production code will not be available. You need to port the test to the new test plugins in order to use historical features from production code. If this is a legacy feature used only in tests, you can add it to a test-only FeatureSpecification such as org.elasticsearch.test.rest.RestTestLegacyFeatures.
  1> [2024-02-13T02:38:06,090][INFO ][o.e.x.i.a.DownsampleActionIT] [testRollupIndex] --> running [testRollupIndex] with index [index-mfpwyetolc], data stream [ds-hnncnforts], alias [alias-QkJlp] and policy [policy-DfUEf]
  1> [2024-02-13T02:40:06,867][WARN ][o.e.x.i.a.DownsampleActionIT] [testRollupIndex] --> original index name is [index-mfpwyetolc], rollup index name is NULL, possible explanation: {index=index-mfpwyetolc, managed=true, policy=policy-DfUEf, index_creation_date_millis=1707806286168, time_since_index_creation=2.01m, step_info={type=illegal_argument_exception, reason=policy [policy-DfUEf] does not exist}}
  1> [2024-02-13T02:40:07,141][INFO ][o.e.x.i.a.DownsampleActionIT] [testRollupIndex] There are still tasks running after this test that might break subsequent tests [health-node[c]].
  1> [2024-02-13T02:40:07,142][INFO ][o.e.x.i.a.DownsampleActionIT] [testRollupIndex] after test
  2> REPRODUCE WITH: ./gradlew ':x-pack:plugin:ilm:qa:multi-node:javaRestTest' --tests "org.elasticsearch.xpack.ilm.actions.DownsampleActionIT.testRollupIndex" -Dtests.seed=60DC99456040484D -Dtests.locale=it -Dtests.timezone=America/Montserrat -Druntime.java=21
  2> java.lang.AssertionError: Cannot retrieve rollup index name
        at __randomizedtesting.SeedInfo.seed([60DC99456040484D:86F8E813090C4181]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertNotNull(Assert.java:713)
        at org.elasticsearch.xpack.ilm.actions.DownsampleActionIT.testRollupIndex(DownsampleActionIT.java:203)
```

**Comment by kkrik-es** [comment] 2024-04-08 10:06
The log entry above is not very helpful. I'm re-enabling the test with trace logging for ILM to further debug.

**Comment by kkrik-es** [comment] 2024-04-11 08:39
No test failures over the past 4 days. Removing trace logging and closing for now.

**Comment by gmarouli** [comment] 2024-06-14 11:55
Hey, @kkrik-es I found it, and let me tell you, it was not where we were looking :). 

So the naughty line is non other than:
https://github.com/elastic/elasticsearch/blob/c22855d13b694b9df8d14ec64652446405c39e14/x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/actions/DownsampleActionIT.java#L165

This line adds the policy to the newly created index, but this policy does not exist yet. If ILM doesn't run before the policy is added, all is good, that's common when you run it locally. But sometimes in CI, 5 seconds pass and ILM does execute as you can see in the logs:
```
----> The index gets created referring a policy that does not exist yet, ILM runs at least twice before the policy is there
[2024-06-12T20:14:28,857][....] [index-sanohmhwxl] creating index, ......
[2024-06-12T20:14:28,870][....] [index-sanohmhwxl] retrieved current step key: null
[2024-06-12T20:14:28,871][....] unable to retrieve policy [policy-tohpA] for index [index-sanohmhwxl], recording this in step_info for this index java.lang.IllegalArgumentException: policy [policy-tohpA] does not exist

-----> Only now the policy is added
[2024-06-12T20:14:29,024][....] adding index lifecycle policy [policy-tohpA]

-----> ILM is running periodically but because the current step is null it ignores it
[2024-06-12T20:15:23,791][....] job triggered: ilm, 1718223323790, 1718223323790
[2024-06-12T20:15:23,791][....] retrieved current step key: null
[2024-06-12T20:15:23,791][....] maybe running periodic step (InitializePolicyContextStep) with current step {"phase":"new","action":"init","name":"init"}
```
By the way you can reproduce it locally by adding a 5s thread sleep before adding the policy. The index gets unstuck only when there is a cluster update, but since this is a test which does nothing but waits for the name to be available, this does not happen. The index gets unstuck only during test tear down, ironically. 

If you remove the naughty line it works. 🎉

**Closed** 2024-06-17 07:55 UTC
Labels: >test-failure, :StorageEngine/Downsampling, low-risk, Team:StorageEngine
