### ISSUE TITLE
Fetching many fields takes much more time than retrieving _source

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#96349] opened 2023-05-25 13:57 UTC
In a search request, asking to retrieve many fields can take substantially more time than retrieving the whole source.

For example, tested in ES 8.6 asking to retrieve 200 fields takes  > 6s. On the same shard without fetching fields, but grabbing the whole source takes around 139 ms.

```js
"fields": [
    {
      "field": "*",
      "include_unmapped": "true"
    },
    {
      "field": "@timestamp",
      "format": "strict_date_optional_time"
    },
    {
      "field": "field1",
      "format": "strict_date_optional_time"
    },
    {
      "field": "field2",
      "format": "strict_date_optional_time"
    },
    {
      "field": "field3",
      "format": "strict_date_optional_time"
    },
```

**Comment by cpmoore** [comment] 2023-06-28 00:21
Hi @mayya-sharipova 
I was the one to initially report this on a support case. I was wondering if you had any updates since I haven’t received any from my support case. 
I’m happy to help in any way I can.

**Comment by andreidan** [comment] 2024-06-26 14:10
I've done some testing trying to reproduce this issue and I believe I've found a case where retrieving 100 timestamp fields, from 8k documents takes 2 - 2.5 seconds on one Elasticsearch nodes (whilst retrieving the whole source takes `0.2` seconds)

This is due to the [data parsing](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/index/mapper/DateFieldMapper.java#L530) we execute when retrieving the fields.
The time to parse dates is something the wider Elasticsearch team works on periodically (e.g. https://github.com/elastic/elasticsearch/pull/106486 ) but I don't think we can do much else here in the meantime. 

I'll keep this issue open for a few more days to potentially collect more comments but otherwise I believe we should rely on the improvements we make to date/time parsing to speed up the retrieval of many `date` fields.

**Comment by andreidan** [comment] 2024-07-17 13:06
Closing this for now but please reopen if more details/information is available.

**Closed by andreidan** 2024-07-17 13:06 UTC
Labels: >bug, priority:normal, Team:Search Foundations, :Search Foundations/Search
