### ISSUE TITLE
[CI] StableMasterDisruptionIT.testRepeatedNullMasterRecognizedAsGreenIfMasterDoesNotKnowItIsUnstable

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#89425] opened 2022-08-17 13:21 UTC
### CI Link

https://gradle-enterprise.elastic.co/s/sjbgu4zjbxhmo

### Repro line

gradlew ':server:internalClusterTest' --tests "org.elasticsearch.discovery.StableMasterDisruptionIT.testRepeatedNullMasterRecognizedAsGreenIfMasterDoesNotKnowItIsUnstable" -Dtests.seed=5F13EFF29906BB53 -Dtests.locale=en-IE -Dtests.timezone=Australia/South -Druntime.java=17

### Does it reproduce?

No

### Applicable branches

main

### Failure excerpt

```
org.elasticsearch.discovery.StableMasterDisruptionIT > testRepeatedNullMasterRecognizedAsGreenIfMasterDoesNotKnowItIsUnstable FAILED
    java.lang.AssertionError: {"status":"yellow","cluster_name":"TEST-TEST_WORKER_VM=[226]-CLUSTER_SEED=[7924964341647394941]-HASH=[F908511566]-cluster","indicators":{"master_is_stable":{"status":"yellow","symptom":"The cluster's master has alternated between [{node_t0}{cX_Eos3KTJi7ejP3Ciy7Gw}{ZPwl9rtsTlmdxJanBAD2ew}{node_t0}{127.0.0.1}{127.0.0.1:20111}{m}] and no master multiple times in the last 30m","details":{"current_master":{"node_id":"cX_Eos3KTJi7ejP3Ciy7Gw","name":"node_t0"},"recent_masters":[{"node_id":"cX_Eos3KTJi7ejP3Ciy7Gw","name":"node_t0"},{"node_id":"cX_Eos3KTJi7ejP3Ciy7Gw","name":"node_t0"},{"node_id":"cX_Eos3KTJi7ejP3Ciy7Gw","name":"node_t0"}],"exception_fetching_history":{"message":"[node_t0][127.0.0.1:20111][internal:cluster/master_history/get] request_id [25] timed out after [10044ms]","stack_trace":"org.elasticsearch.transport.ReceiveTimeoutTransportException: [node_t0][127.0.0.1:20111][internal:cluster/master_history/get] request_id [25] timed out after [10044ms]\n"}},"impacts":[{"severity":1,"description":"The cluster cannot create, delete, or rebalance indices, and cannot insert or update documents.","impact_areas":["ingest"]},{"severity":1,"description":"Scheduled tasks such as Watcher, ILM, and SLM will not work. The _cat APIs will not work.","impact_areas":["deployment_management"]},{"severity":3,"description":"Snapshot and restore will not work. Searchable snapshots cannot be mounted.","impact_areas":["backup"]}],"diagnosis":[{"cause":"The Elasticsearch cluster does not have a stable master node.","action":"Get help at https://ela.st/getting-help","help_url":"https://ela.st/getting-help"}]},"repository_integrity":{"status":"unknown","symptom":"Could not determine health status. Check details on critical issues preventing the health status from reporting.","details":{"reasons":{"master_is_stable":"yellow"}}},"shards_availability":{"status":"unknown","symptom":"Could not determine health status. Check details on critical issues preventing the health status from reporting.","details":{"reasons":{"master_is_stable":"yellow"}}}}}
    Expected: <GREEN>
         but: was <YELLOW>
        at __randomizedtesting.SeedInfo.seed([5F13EFF29906BB53:B4381153A289DA9A]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.elasticsearch.discovery.StableMasterDisruptionIT.lambda$assertMasterStability$0(StableMasterDisruptionIT.java:140)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1104)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1077)
        at org.elasticsearch.discovery.StableMasterDisruptionIT.assertMasterStability(StableMasterDisruptionIT.java:137)
        at org.elasticsearch.discovery.StableMasterDisruptionIT.assertGreenMasterStability(StableMasterDisruptionIT.java:133)
        at org.elasticsearch.discovery.StableMasterDisruptionIT.testRepeatedNullMasterRecognizedAsGreenIfMasterDoesNotKnowItIsUnstable(StableMasterDisruptionIT.java:474)
```

and it appears to be an inter-node communication failure, but cannot tell why:

```
  1> [2022-08-17T17:47:45,058][WARN ][o.e.c.NodeConnectionsService] [node_t2] failed to connect to {node_t0}{zgq2cRpNRhufvFA4vwUkbg}{pqnnBb8nTtK7pomrY0Xoxw}{node_t0}{127.0.0.1}{127.0.0.1:20111}{m} (tried [1] times)
  1> org.elasticsearch.transport.ConnectTransportException: [node_t0][127.0.0.1:20111] connect_exception
  1> 	at org.elasticsearch.transport.TcpTransport$ChannelsConnectedListener.onFailure(TcpTransport.java:1100) ~[main/:?]
  1> 	at org.elasticsearch.action.ActionListener.lambda$toBiConsumer$0(ActionListener.java:305) ~[main/:?]
  1> 	at org.elasticsearch.core.CompletableContext.lambda$addListener$0(CompletableContext.java:33) ~[elasticsearch-core-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
  1> 	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
  1> 	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
  1> 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
  1> 	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[?:?]
  1> 	at org.elasticsearch.core.CompletableContext.completeExceptionally(CompletableContext.java:48) ~[elasticsearch-core-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
  1> 	at org.elasticsearch.transport.netty4.Netty4TcpChannel.lambda$addListener$0(Netty4TcpChannel.java:63) ~[transport-netty4-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
  1> 	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
  1> 	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
  1> 	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
  1> 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
  1> 	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
  1> 	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
  1> 	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
  1> 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
  1> 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
  1> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
  1> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:623) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
  1> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:586) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
  1> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
  1> 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
  1> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
  1> 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
  1> Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 127.0.0.1/127.0.0.1:20111
  1> Caused by: java.net.ConnectException: Connection refused
  1> 	at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
  1> 	at sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[?:?]
  1> 	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946) ~[?:?]
  1> 	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
  1> 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
  1> 	... 7 more
```

**Comment by dimitris-athanasiou** [comment] 2022-08-22 09:21
Closing as duplicate of #89431 which now seems to have more info.

**Closed by dimitris-athanasiou** 2022-08-22 09:21 UTC
Labels: >test-failure, :Distributed/Cluster Coordination, Team:Distributed
