### ISSUE TITLE
Min or max aggregation of date returns floating point number

### ISSUE THREAD

**Issue by jimmyjones2** [elastic/elasticsearch#9934] opened 2015-03-01 14:16 UTC
A min or max aggregation of a date field returns a floating point number, epoch milliseconds, despite it being internally stored as a long. Should it really return an long? In some rare cases, will floating point not return an entirely accurate answer?

**Comment by haight6716** [comment] 2015-05-26 19:04
I'm seeing something similar, but worse.  Dates being returned in scientific notation with the wrong value.  I get stuff like: 

    "aggregations": {
        "time-test": {
            "avg": 7.078292805144e-312,
            "avg_as_string": "1970-01-01T00:00:00.000Z",
            "count": 1847,
            "max": 7.078307915815e-312,
            "max_as_string": "1970-01-01T00:00:00.000Z",
            "min": 7.07828016824e-312,
            "min_as_string": "1970-01-01T00:00:00.000Z",
            "sum": 1.307360681110475e-308,
            "sum_as_string": "1970-01-01T00:00:00.000Z"
        }
    }

The field in question contains dates from the modern day (2015), not 1970.

    "version" : {
      "number" : "1.5.0",
      "build_hash" : "544816042d40151d3ce4ba4f95399d7860dc2e92",
      "build_timestamp" : "2015-03-23T14:30:58Z",
      "build_snapshot" : false,
      "lucene_version" : "4.10.4"
    }

**Comment by clintongormley** [comment] 2015-05-27 09:57
Hi @jimmyjones2 - I'm going to close this as a duplicate of #9545

**Closed by clintongormley** 2015-05-27 09:57 UTC
Labels: :Aggregations, discuss
