### ISSUE TITLE
lots of unassigned shards after master unexpectedly crashed 

### ISSUE THREAD

**Issue by wangxiangyu** [elastic/elasticsearch#34790] opened 2018-10-24 06:35 UTC
**Elasticsearch version**  5.4.3

**Plugins installed**: x-pack

**JVM version** : 1.8.0_60

**OS version** : Debian GNU/Linux 8

**Description of the problem including expected versus actual behavior**:
There are three master node in my cluster.  One of them crashed unexpectedly.   About six hours later,  the crashed master node was  started again, lots of unassigned shard appeared. 

Try to call ``/_cluster/allocation/explain`` to get the unassigned reason,   response as follows:

```
"allocate_explanation": "cannot allocate because a previous copy of the primary shard existed but can no longer be found on the nodes in the cluster"
```
These unassigned shards(index) were deleted during the crash time of master node. So Why these shards were in unassigned status when the crashed master node was up again instead of just deleted?

**Comment by wangxiangyu** [comment] 2018-10-25 02:39
@DaveCTurner thanks for your replay

Approximately how many indices did you delete while the master node was unavailable?
About 400 indices

Are there any mentions of the affected indices in the logs of the master node once it was restarted? Can you share any matching log lines?
log as follows:
```
[2018-10-23T14:19:08,407][INFO ][o.e.g.DanglingIndicesState] [hzxs-billions-es-01-masternode] [[billions-bplus-access-lbs-dao-@2018.10.21-hzxs01-1/3ne4MdhQRLmZ2CdBqpUf-g]] dangling index exists on local file system, but not in cluster metadata, auto import to cluster state
[2018-10-23T14:19:08,407][INFO ][o.e.g.DanglingIndicesState] [hzxs-billions-es-01-masternode] [[billions-bplus-rpc-dynamic-rcmd-@2018.10.21-hzxs01-1/xyJkHZGLS_C6bJFAZIq2cw]] dangling index exists on local file system, but not in cluster metadata, auto import to cluster state
[2018-10-23T14:19:08,407][INFO ][o.e.g.DanglingIndicesState] [hzxs-billions-es-01-masternode] [[billions-main.manager.workflow-service-@2018.10.22-hzxs01-1/vPZQyRMGT0aIswn4a_3NHw]] dangling index exists on local file system, but not in cluster metadata, auto import to cluster state
[2018-10-23T14:19:08,407][INFO ][o.e.g.DanglingIndicesState] [hzxs-billions-es-01-masternode] [[billions-main.common-arch.config-service-@2018.10.22-hzxs01-2/tCtzhZu7Rb6jjGJ5YgTN4Q]] dangling index exists on local file system, but not in cluster metadata, auto import to cluster state
[2018-10-23T14:19:08,408][INFO ][o.e.g.DanglingIndicesState] [hzxs-billions-es-01-masternode] [[billions-main.search.search-job-ticket-@2018.10.22-hzxs01-2/t7oOc4D6SUuj1a4ZoDw-nA]] dangling index exists on local file system, but not in cluster metadata, auto import to cluster state
[2018-10-23T14:19:08,408][INFO ][o.e.g.DanglingIndicesState] [hzxs-billions-es-01-masternode] [[billions-main.archive.videoup-report-job-@2018.10.22-hzxs01-2/euPYopB3SI-l-eXpQrKkvQ]] dangling index exists on local file system, but not in cluster metadata, auto import to cluster state
[2018-10-23T14:19:08,408][INFO ][o.e.g.DanglingIndicesState] [hzxs-billions-es-01-masternode] [[billions-main.common-arch.dapper-service-@2018.10.22-hzxs01-2/ft-7n1VRTUqoirjs_yI54Q]] dangling index exists on local file system, but not in cluster metadata, auto import to cluster state
[2018-10-23T14:19:08,408][INFO ][o.e.g.DanglingIndicesState] [hzxs-billions-es-01-masternode] [[billions-live.live.live-riskcontrol-service-@2018.10.22-hzxs01-2/7CHqXjF_QGeah1iggbl7dw]] dangling index exists on local file system, but not in cluster metadata, auto import to cluster state
[2018-10-23T14:19:08,408][INFO ][o.e.g.DanglingIndicesState] [hzxs-billions-es-01-masternode] [[billions-bplus-rpc-lbs-svr-@2018.10.21-hzxs01-1/qZg-9TpsQJKiyWvlh2bIjQ]] dangling index exists on local file system, but not in cluster metadata, auto import to cluster state
[2018-10-23T14:19:08,408][INFO ][o.e.g.DanglingIndicesState] [hzxs-billions-es-01-masternode] [[billions-open.pay.openplatform-pay-sandbox-@2018.10.22-hzxs01-2/eMCJ-eViRh6wRNiglgSR0A]] dangling index exists on local file system, but not in cluster metadata, auto import to cluster state
[2018-10-23T14:19:08,408][INFO ][o.e.g.DanglingIndicesState] [hzxs-billions-es-01-masternode] [[billions-live.vc.link-news-@2018.10.22-hzxs01-2/A5S5UAv_TI24t8hFylZ6sQ]] dangling index exists on local file system, but not in cluster metadata, auto import to cluster state
[2018-10-23T14:19:08,408][INFO ][o.e.g.DanglingIndicesState] [hzxs-billions-es-01-masternode] [[billions-main.bangumi.comic-manager-@2018.10.22-hzxs01-2/pjy6UXuCRuOlpkLhbn2UlQ]] dangling index exists on local file system, but not in cluster metadata, auto import to cluster state
[2018-10-23T14:19:08,409][INFO ][o.e.g.DanglingIndicesState] [hzxs-billions-es-01-masternode] [[billions-ops.billions.fake_flow.000875-@2018.10.22-hzxs01-2/Nr4PUZivQxSLC7e8mVFVow]] dangling index exists on local file system, but not in cluster metadata, auto import to cluster state
[2018-10-23T14:19:08,409][INFO ][o.e.g.DanglingIndicesState] [hzxs-billions-es-01-masternode] [[billions-bplus-dynamic-account-@2018.10.21-hzxs01-1/1WCnN77pRkqNGcMuSRXbig]] dangling index exists on local file system, but not in cluster metadata, auto import to cluster state
[2018-10-23T14:19:08,409][INFO ][o.e.g.DanglingIndicesState] [hzxs-billions-es-01-masternode] [[billions-bplus-alarm-promo_task_dao-@2018.10.21-hzxs01-1/hOo2FihqRc-qPn7eUzdCGQ]] dangling index exists on local file system, but not in cluster metadata, auto import to cluster state
[2018-10-23T14:19:08,409][INFO ][o.e.g.DanglingIndicesState] [hzxs-billions-es-01-masternode] [[billions-bplus-alarm-dynamic_dao-@2018.10.21-hzxs01-1/tut97VHOQJi05MaybCNAlQ]] dangling index exists on local file system, but not in cluster metadata, auto import to cluster state
[2018-10-23T14:19:08,409][INFO ][o.e.g.DanglingIndicesState] [hzxs-billions-es-01-masternode] [[billions-live.live.app-interface-@2018.10.22-hzxs01-2/bqEpvYs1TyiRs5b1H9eOSQ]] dangling index exists on local file system, but not in cluster metadata, auto import to cluster state
[2018-10-23T14:19:08,409][INFO ][o.e.g.DanglingIndicesState] [hzxs-billions-es-01-masternode] [[billions-mall-index-@2018.10.22-hzxs01-2/6iueEeKiQ_KptSa5i0w0Rw]] dangling index exists on local file system, but not in cluster metadata, auto import to cluster state
[2018-10-23T14:19:08,409][INFO ][o.e.g.DanglingIndicesState] [hzxs-billions-es-01-masternode] [[billions-live.fe.blfe-live-levelserver-@2018.10.22-hzxs01-2/90-ylv1bTr2Ax2Gb6O3oQA]] dangling index exists on local file system, but not in cluster metadata, auto import to cluster state
```

**Comment by DaveCTurner** [comment] 2018-10-25 06:55
Thanks. When you delete an index, Elasticsearch remembers that it has done so so that it can delete the index from any nodes that are currently offline when they return. It only remembers the last 500 deletions (by default) so if you delete more than this number and then restore a node it will find some shard data for indices that it no longer remembers deleting and so it will import them again as dangling indices. Here's the relevant bit of the manual:

https://www.elastic.co/guide/en/elasticsearch/reference/5.4/misc-cluster.html#cluster-max-tombstones

I'm closing this as it's not a bug, but if you have further questions please open a thread on the discussion forum at https://discuss.elastic.co/c/elasticsearch

**Closed by DaveCTurner** 2018-10-25 06:55 UTC
Labels: :Distributed/Allocation, feedback_needed, v5.4.3
