### ISSUE TITLE
HighLevelRestClient throws SocketTimeoutException for idle connections

### ISSUE THREAD

**Issue by sahana412** [elastic/elasticsearch#98151] opened 2023-08-02 17:55 UTC
### Elasticsearch Version

7+

### Java Version

_bundled_

### OS Version

Centos 7 Linux

### Problem Description

Using latest SpringBoot 2.6 and Java HLRC,
We have built a rest high level client with socket timeout of 1500ms and there is some health checks doing ping to elastic search server every 15s but still we see socket timeout exception once in an hour. A connection pool might have default 20 connections and all the connections may not be used by health checks throughout so some connections may be idle and become stale. But how is it that it happens every one hour, why after every hour, the ping to elastic search fails with sockettimeout exception. We have seen the pattern of 1 hour and sometimes once in 2 hours, and sometimes no error for 5-6 hours. So there is no one pattern which can be deduced here but pretty sure its happening because of request getting idle connection and then timing out.

### Steps to Reproduce

Create a HLRC in SpringBoot. Set connection and socket timeout to 1500 ms (for example).
Ping to ES server every 15s
A SocketTimeoutException exception occur and returned after the configured timeout.

**Comment by DaveCTurner** [comment] 2023-08-02 20:15
Closing as a duplicate of https://github.com/elastic/elasticsearch/issues/65213.

**Closed by DaveCTurner** 2023-08-02 20:15 UTC
Labels: >bug, needs:triage
