### ISSUE TITLE
Set a default search timeout to clusters

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#27187] opened 2017-10-31 11:55 UTC
Many client applications overlook the `timeout` setting in the search API meaning searches run indefinitely.
This issue proposes that a default timeout setting is defined for `search.default_search_timeout`.

What will be a good choice of default setting is an interesting question - many applications that exist today will expect sub-second search responses but several may be happy with searches that can take up to a minute. 
Assuming we pick "1 minute" as the default timeout default then we run the risk of returning partial results to many existing applications that are content with >1 minute response times and have no code to check for `timed_out` responses. They will be lying to their users about stats at this point. Better then, that we throw an error if searches timeout by default using the new setting proposed in https://github.com/elastic/elasticsearch/issues/27186 
It would be better to loudly complain about excessive resource usage on our cluster than silently return incorrect/partial results.

**Comment by jasontedor** [comment] 2017-10-31 13:04
Note that we have `search.default_search_timeout` (since 2.0 via #12211) which is a dynamic cluster setting (it defaults to no timeout though).

**Comment by markharwood** [comment] 2017-10-31 13:38
Thanks, Jason - I have revised this issue to discuss what the existing setting should be defaulted to.

**Comment by jpountz** [comment] 2017-10-31 14:44
From what I remember from discussions that we have had recently, default timeouts were considered trappy because they require that you check a flag in the response to know that results are partial. Should we only allow default timeouts for hard timeouts?

**Comment by clintongormley** [comment] 2017-11-10 14:30
This brought up some interesting issues like should we also throw a hard exception when partial data is returned (eg a missing shard), or when some shards fail because of different mappings (which could be considered a feature).

Let's start with benchmarking it and see if it is even feasible.

**Comment by markharwood** [comment] 2017-11-13 13:12
*update* below a rally benchmark result from the "PMC" track when adding a default search timeout of 1 minute to searches.
Search operations (terms/phrase/aggs) show little deviation in response times but curiously the indexing time is 2 minutes longer. I saw this when benchmarking on my laptop. 


Comparing baseline
  Race timestamp: 2017-11-13 09:53:11
  Challenge: append-no-conflicts
  (current master - no default timeout)

with contender
  Race timestamp: 2017-11-13 10:53:14
  Challenge: append-no-conflicts
  master with search_timeout=1ms

|                         Metric |                     Operation |   Baseline |   Contender |     Diff |   Unit |
|-------------------------------:|------------------------------:|-----------:|------------:|---------:|-------:|
|                  Indexing time |                               |    74.9711 |     77.3724 |  2.40135 |    min |
|                     Merge time |                               |    68.0357 |     66.2806 | -1.75512 |    min |
|                   Refresh time |                               |    8.40285 |     8.43457 |  0.03172 |    min |
|                     Flush time |                               |    2.58573 |     2.52118 | -0.06455 |    min |
|            Merge throttle time |                               |    46.8416 |     44.8858 | -1.95573 |    min |
|             Total Young Gen GC |                               |     20.799 |      22.543 |    1.744 |      s |
|               Total Old Gen GC |                               |    123.442 |     112.841 |  -10.601 |      s |
|                     Index size |                               |     23.132 |     23.0885 | -0.04354 |     GB |
|                Totally written |                               |    115.141 |       115.5 |  0.35888 |     GB |
|         Heap used for segments |                               |    23.2306 |      22.698 | -0.53259 |     MB |
|       Heap used for doc values |                               |  0.0945206 |    0.050457 | -0.04406 |     MB |
|            Heap used for terms |                               |    21.1937 |     20.7079 | -0.48583 |     MB |
|            Heap used for norms |                               |  0.0439453 |   0.0411987 | -0.00275 |     MB |
|           Heap used for points |                               | 0.00939274 |  0.00925446 | -0.00014 |     MB |
|    Heap used for stored fields |                               |    1.88907 |     1.88926 |  0.00019 |     MB |
|                  Segment count |                               |        144 |         135 |       -9 |        |
|                 Min Throughput |                  index-append |    869.608 |     864.419 | -5.18811 | docs/s |
|              Median Throughput |                  index-append |    887.312 |     878.543 | -8.76979 | docs/s |
|                 Max Throughput |                  index-append |    913.906 |     917.789 |  3.88341 | docs/s |
|        99th percentile latency |                  index-append |    10106.6 |       10681 |  574.446 |     ms |
|       100th percentile latency |                  index-append |    12251.1 |     11030.2 | -1220.91 |     ms |
|        90th percentile latency |                  index-append |    7252.02 |     7968.42 |  716.392 |     ms |
|        50th percentile latency |                  index-append |    3746.25 |     3980.86 |  234.618 |     ms |
|   99th percentile service time |                  index-append |    10106.6 |       10681 |  574.446 |     ms |
|  100th percentile service time |                  index-append |    12251.1 |     11030.2 | -1220.91 |     ms |
|   90th percentile service time |                  index-append |    7252.02 |     7968.42 |  716.392 |     ms |
|   50th percentile service time |                  index-append |    3746.25 |     3980.86 |  234.618 |     ms |
|                     error rate |                  index-append |          0 |           0 |        0 |      % |
|                 Min Throughput |                   force-merge |   0.418106 |    0.144967 | -0.27314 |  ops/s |
|              Median Throughput |                   force-merge |   0.418106 |    0.144967 | -0.27314 |  ops/s |
|                 Max Throughput |                   force-merge |   0.418106 |    0.144967 | -0.27314 |  ops/s |
|       100th percentile latency |                   force-merge |    2391.73 |     6898.09 |  4506.35 |     ms |
|  100th percentile service time |                   force-merge |    2391.73 |     6898.09 |  4506.35 |     ms |
|                     error rate |                   force-merge |          0 |           0 |        0 |      % |
|                 Min Throughput |                   index-stats |    50.2374 |     50.2399 |  0.00251 |  ops/s |
|              Median Throughput |                   index-stats |    50.2936 |     50.2939 |  0.00026 |  ops/s |
|                 Max Throughput |                   index-stats |    50.3499 |     50.3479 | -0.00198 |  ops/s |
|        99th percentile latency |                   index-stats |    6.43547 |     7.14443 |  0.70897 |     ms |
|       100th percentile latency |                   index-stats |    6.66701 |     7.37419 |  0.70718 |     ms |
|        90th percentile latency |                   index-stats |    5.87808 |      5.7694 | -0.10869 |     ms |
|        50th percentile latency |                   index-stats |    5.64964 |     5.55484 |  -0.0948 |     ms |
|   99th percentile service time |                   index-stats |    6.21751 |     7.05867 |  0.84116 |     ms |
|  100th percentile service time |                   index-stats |     6.4338 |     7.28686 |  0.85306 |     ms |
|   90th percentile service time |                   index-stats |    5.70024 |     5.52927 | -0.17096 |     ms |
|   50th percentile service time |                   index-stats |      5.474 |     5.32982 | -0.14418 |     ms |
|                     error rate |                   index-stats |          0 |           0 |        0 |      % |
|                 Min Throughput |                    node-stats |    50.2333 |     50.2371 |  0.00373 |  ops/s |
|              Median Throughput |                    node-stats |     50.292 |     50.2935 |  0.00158 |  ops/s |
|                 Max Throughput |                    node-stats |    50.3506 |       50.35 | -0.00057 |  ops/s |
|        99th percentile latency |                    node-stats |    6.63116 |     8.56075 |  1.92959 |     ms |
|       100th percentile latency |                    node-stats |    8.73263 |     8.77871 |  0.04608 |     ms |
|        90th percentile latency |                    node-stats |     5.9655 |     5.85351 |   -0.112 |     ms |
|        50th percentile latency |                    node-stats |    5.75911 |     5.71182 | -0.04729 |     ms |
|   99th percentile service time |                    node-stats |    6.38706 |     8.31918 |  1.93212 |     ms |
|  100th percentile service time |                    node-stats |    8.49234 |     8.54064 |   0.0483 |     ms |
|   90th percentile service time |                    node-stats |    5.75763 |      5.6131 | -0.14453 |     ms |
|   50th percentile service time |                    node-stats |    5.52969 |     5.47457 | -0.05513 |     ms |
|                     error rate |                    node-stats |          0 |           0 |        0 |      % |
|                 Min Throughput |                       default |     20.008 |     20.0088 |  0.00088 |  ops/s |
|              Median Throughput |                       default |    20.0139 |     20.0133 | -0.00051 |  ops/s |
|                 Max Throughput |                       default |    20.0334 |     20.0295 | -0.00397 |  ops/s |
|        99th percentile latency |                       default |    22.5174 |     20.1212 |  -2.3962 |     ms |
|       100th percentile latency |                       default |    33.1086 |     22.5227 | -10.5858 |     ms |
|      99.9th percentile latency |                       default |    24.4827 |      21.133 | -3.34962 |     ms |
|        90th percentile latency |                       default |    20.3026 |     18.3062 | -1.99632 |     ms |
|        50th percentile latency |                       default |    19.3091 |     17.7082 | -1.60094 |     ms |
|   99th percentile service time |                       default |    22.3273 |      19.824 |  -2.5033 |     ms |
|  100th percentile service time |                       default |    32.9116 |     22.4026 | -10.5091 |     ms |
| 99.9th percentile service time |                       default |    24.2566 |     20.4342 | -3.82237 |     ms |
|   90th percentile service time |                       default |    20.0923 |     18.0769 | -2.01537 |     ms |
|   50th percentile service time |                       default |    19.0911 |     17.4962 | -1.59493 |     ms |
|                     error rate |                       default |          0 |           0 |        0 |      % |
|                 Min Throughput |                          term |    20.0097 |     20.0097 |   -5e-05 |  ops/s |
|              Median Throughput |                          term |    20.0147 |     20.0151 |  0.00042 |  ops/s |
|                 Max Throughput |                          term |    20.0292 |     20.0324 |  0.00319 |  ops/s |
|        99th percentile latency |                          term |    15.2716 |      16.217 |  0.94539 |     ms |
|       100th percentile latency |                          term |    20.8363 |     21.4561 |  0.61979 |     ms |
|      99.9th percentile latency |                          term |    20.4538 |     20.8909 |  0.43709 |     ms |
|        90th percentile latency |                          term |    14.0722 |     14.6841 |  0.61184 |     ms |
|        50th percentile latency |                          term |     13.594 |     14.3825 |  0.78843 |     ms |
|   99th percentile service time |                          term |    15.0115 |     16.0377 |  1.02625 |     ms |
|  100th percentile service time |                          term |    20.6045 |     21.2178 |   0.6133 |     ms |
| 99.9th percentile service time |                          term |     20.217 |     20.6507 |  0.43362 |     ms |
|   90th percentile service time |                          term |    13.8403 |     14.4563 |    0.616 |     ms |
|   50th percentile service time |                          term |    13.3628 |     14.1595 |  0.79667 |     ms |
|                     error rate |                          term |          0 |           0 |        0 |      % |
|                 Min Throughput |                        phrase |    20.0096 |     20.0096 |    2e-05 |  ops/s |
|              Median Throughput |                        phrase |    20.0151 |      20.015 |   -6e-05 |  ops/s |
|                 Max Throughput |                        phrase |    20.0286 |     20.0288 |  0.00022 |  ops/s |
|        99th percentile latency |                        phrase |    18.8202 |     17.9396 | -0.88064 |     ms |
|       100th percentile latency |                        phrase |    35.2297 |     35.2921 |  0.06239 |     ms |
|      99.9th percentile latency |                        phrase |    23.4982 |     20.9151 | -2.58317 |     ms |
|        90th percentile latency |                        phrase |    14.6354 |     14.6004 | -0.03498 |     ms |
|        50th percentile latency |                        phrase |    14.2541 |      14.102 | -0.15214 |     ms |
|   99th percentile service time |                        phrase |    18.7237 |     17.7061 | -1.01763 |     ms |
|  100th percentile service time |                        phrase |    34.9885 |      35.055 |  0.06654 |     ms |
| 99.9th percentile service time |                        phrase |    23.2529 |     20.6762 | -2.57668 |     ms |
|   90th percentile service time |                        phrase |    14.4061 |     14.3861 | -0.01999 |     ms |
|   50th percentile service time |                        phrase |    14.0276 |     13.8883 | -0.13934 |     ms |
|                     error rate |                        phrase |          0 |           0 |        0 |      % |
|                 Min Throughput | articles_monthly_agg_uncached |     20.003 |     19.9991 | -0.00398 |  ops/s |
|              Median Throughput | articles_monthly_agg_uncached |    20.0094 |     20.0146 |  0.00517 |  ops/s |
|                 Max Throughput | articles_monthly_agg_uncached |    20.0273 |     20.0432 |  0.01595 |  ops/s |
|        99th percentile latency | articles_monthly_agg_uncached |    38.2355 |     38.9997 |  0.76419 |     ms |
|       100th percentile latency | articles_monthly_agg_uncached |    44.3933 |     51.4955 |  7.10212 |     ms |
|      99.9th percentile latency | articles_monthly_agg_uncached |     43.703 |      48.698 |  4.99507 |     ms |
|        90th percentile latency | articles_monthly_agg_uncached |    36.5011 |     37.1451 |    0.644 |     ms |
|        50th percentile latency | articles_monthly_agg_uncached |    33.6744 |     34.1861 |  0.51169 |     ms |
|   99th percentile service time | articles_monthly_agg_uncached |         38 |     38.7643 |  0.76425 |     ms |
|  100th percentile service time | articles_monthly_agg_uncached |    44.1461 |     51.2615 |  7.11537 |     ms |
| 99.9th percentile service time | articles_monthly_agg_uncached |    43.6283 |     48.4491 |  4.82072 |     ms |
|   90th percentile service time | articles_monthly_agg_uncached |    36.2601 |     36.9207 |  0.66062 |     ms |
|   50th percentile service time | articles_monthly_agg_uncached |    33.4282 |     33.9335 |  0.50531 |     ms |
|                     error rate | articles_monthly_agg_uncached |          0 |           0 |        0 |      % |
|                 Min Throughput |   articles_monthly_agg_cached |    20.0158 |     20.0158 |   -6e-05 |  ops/s |
|              Median Throughput |   articles_monthly_agg_cached |    20.0265 |      20.027 |   0.0005 |  ops/s |
|                 Max Throughput |   articles_monthly_agg_cached |    20.0928 |     20.0909 | -0.00194 |  ops/s |
|        99th percentile latency |   articles_monthly_agg_cached |    5.03546 |     4.93111 | -0.10436 |     ms |
|       100th percentile latency |   articles_monthly_agg_cached |    8.95999 |     11.1342 |  2.17423 |     ms |
|      99.9th percentile latency |   articles_monthly_agg_cached |    8.93657 |     7.38508 | -1.55149 |     ms |
|        90th percentile latency |   articles_monthly_agg_cached |    4.33348 |     4.34181 |  0.00833 |     ms |
|        50th percentile latency |   articles_monthly_agg_cached |    4.21191 |     4.23683 |  0.02491 |     ms |
|   99th percentile service time |   articles_monthly_agg_cached |    4.79768 |     4.67188 |  -0.1258 |     ms |
|  100th percentile service time |   articles_monthly_agg_cached |    8.82886 |     10.8991 |  2.07021 |     ms |
| 99.9th percentile service time |   articles_monthly_agg_cached |    8.70213 |     7.30004 | -1.40209 |     ms |
|   90th percentile service time |   articles_monthly_agg_cached |    4.09859 |     4.11132 |  0.01273 |     ms |
|   50th percentile service time |   articles_monthly_agg_cached |    3.98283 |     4.00618 |  0.02336 |     ms |
|                     error rate |   articles_monthly_agg_cached |          0 |           0 |        0 |      % |
|                 Min Throughput |                        scroll |    4.85937 |      4.6288 | -0.23057 |  ops/s |
|              Median Throughput |                        scroll |    4.86417 |     4.63186 | -0.23231 |  ops/s |
|                 Max Throughput |                        scroll |    4.86728 |     4.63641 | -0.23087 |  ops/s |
|        99th percentile latency |                        scroll |     617407 |      655473 |  38065.7 |     ms |
|       100th percentile latency |                        scroll |     621528 |      659816 |  38287.7 |     ms |
|        90th percentile latency |                        scroll |     580519 |      616492 |    35973 |     ms |
|        50th percentile latency |                        scroll |     417061 |      443046 |  25985.2 |     ms |
|   99th percentile service time |                        scroll |    5201.08 |     5464.82 |  263.733 |     ms |
|  100th percentile service time |                        scroll |    5263.83 |     5511.59 |  247.752 |     ms |
|   90th percentile service time |                        scroll |    5174.86 |     5423.22 |  248.364 |     ms |
|   50th percentile service time |                        scroll |    5132.71 |     5385.35 |  252.647 |     ms |
|                     error rate |                        scroll |          0 |           0 |        0 |      % |

**Comment by markharwood** [comment] 2017-11-21 16:44
Changing to add on-by-default search timeouts will be a dangerous change for existing clients when we are set to return partial results. We will need to  implement https://github.com/elastic/elasticsearch/issues/27435 first which moves us to error-by-default when we have partial results like timeouts.

**Comment by javanna** [comment] 2018-03-16 11:09
@elastic/es-search-aggs

**Comment by javanna** [comment] 2019-04-09 10:15
@markharwood are you ok with closing this as a duplicate of #26308 or am I missing details on why they are two separate issues?

**Comment by jimczi** [comment] 2019-05-07 07:08
Closing as duplicate of https://github.com/elastic/elasticsearch/issues/26308, please reopen if we're missing something.

**Closed by jimczi** 2019-05-07 07:08 UTC
Labels: :Search/Search, >feature
