### ISSUE TITLE
Implement HEAD for index private properties

### ISSUE THREAD

**Issue by felixsanz** [elastic/elasticsearch#19152] opened 2016-06-29 14:06 UTC
When you `curl ip:9200/name/_mappings` (or `_settings`, for example), you get a response with the JSON object.

But when you do  `curl -I ip:9200/name/_mappings`, you get 404.

Why? Because `-I` is not a GET operation, but a HEAD one, and it's not implemented.

I think this is strange behaviour. According to [HTTP protocol spec](https://tools.ietf.org/html/rfc2616#section-9.4):

>  The HEAD method is identical to GET except that the server MUST NOT
   return a message-body in the response. The metainformation contained
   in the HTTP headers in response to a HEAD request SHOULD be identical
   to the information sent in response to a GET request.

So would be nice to have the HEAD acting the same as GET here (without body response), instead of returning 404. I wasted some time trying to figure out what was wrong until i removed `-I` :confused:

**Comment by clintongormley** [comment] 2016-06-29 14:39
Given that support for HEAD requests is not required (and doesn't make much sense with this request) I think the correct behaviour would be to return 405 method not allowed.  As such, i'm closing as a duplicate of #15335

**Closed by clintongormley** 2016-06-29 14:39 UTC
