### ISSUE TITLE
Test Failure in Build: org.elasticsearch.search.profile.QueryProfilerIT

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#17302] opened 2016-03-23 20:37 UTC
Unable to reproduce locally.

Build (https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-os-compatibility/os=centos/111/console)

Suite: org.elasticsearch.search.profile.QueryProfilerIT
  2> REPRODUCE WITH: gradle :core:integTest -Dtests.seed=E6B1C23627D79398 -Dtests.class=org.elasticsearch.search.profile.QueryProfilerIT -Dtests.method="testBoosting" -Des.logger.level=WARN -Dtests.security.manager=true -Dtests.locale=ga -Dtests.timezone=Africa/Addis_Ababa
FAILURE 50.9s J0 | QueryProfilerIT.testBoosting <<< FAILURES!
  2> NOTE: leaving temporary files on disk at: /var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob-os-compatibility/os/centos/core/build/testrun/integTest/J0/temp/org.elasticsearch.search.profile.QueryProfilerIT_E6B1C23627D79398-001
  2> NOTE: test params are: codec=Asserting(Lucene60): {field1=PostingsFormat(name=Asserting), _field_names=PostingsFormat(name=Asserting), _type=PostingsFormat(name=Asserting), _uid=PostingsFormat(name=Asserting), field2=PostingsFormat(name=Asserting), _all=PostingsFormat(name=Asserting)}, docValues:{_type=DocValuesFormat(name=Lucene54), field2=DocValuesFormat(name=Lucene54), _version=DocValuesFormat(name=Lucene54)}, maxPointsInLeafNode=1793, maxMBSortInHeap=6.374764498623509, sim=ClassicSimilarity, locale=ga, timezone=Africa/Addis_Ababa
  2> NOTE: Linux 2.6.32-573.12.1.el6.x86_64 amd64/Oracle Corporation 1.8.0_65 (64-bit)/cpus=4,threads=1,free=229665336,total=527433728
   > Throwable #1: java.lang.AssertionError: timed out waiting for green state
  2> NOTE: All tests run in this JVM: [InternalEngineMergeIT, RepositoriesIT, TruncatedRecoveryIT, TopHitsIT, BlobStoreFormatIT, MetaDataIT, AliasResolveRoutingIT, RecoveryBackwardsCompatibilityIT, NettyPipeliningDisabledIT, HighlighterSearchIT, BulkProcessorIT, CorruptedFileIT, SimpleValidateQueryIT, GeoBoundsIT, ClusterStatsIT, NettyTransportPublishAddressIT, SimpleThreadPoolIT, IndexWithShadowReplicasIT, ContextCompletionSuggestSearchIT, ClusterInfoServiceIT, IngestProcessorNotInstalledOnAllNodesIT, ScriptFieldIT, ClusterSearchShardsIT, TransportSearchFailuresIT, ListenerActionIT, DateMathIndexExpressionsIntegrationIT, NestedIT, BasicAnalysisBackwardCompatibilityIT, MultiFieldsIntegrationIT, RecoveryWhileUnderLoadIT, GetIndexBackwardsCompatibilityIT, CircuitBreakerNoopIT, StressSearchServiceReaperIT, UpdateByNativeScriptIT, OpenCloseIndexIT, MatchedQueriesIT, UpdateNumberOfReplicasIT, UpgradeIT, AliasedIndexDocumentActionsIT, SimpleGetFieldMappingsIT, QueryProfilerIT]
   > 	at __randomizedtesting.SeedInfo.seed([E6B1C23627D79398:AAAABA5277BD299C]:0)
   > 	at org.elasticsearch.test.ESIntegTestCase.ensureGreen(ESIntegTestCase.java:880)
   > 	at org.elasticsearch.test.ESIntegTestCase.ensureGreen(ESIntegTestCase.java:865)
   > 	at org.elasticsearch.search.profile.QueryProfilerIT.testBoosting(QueryProfilerIT.java:389)
   > 	at java.lang.Thread.run(Thread.java:745)
Completed [239/276] on J0 in 1098.11s, 11 tests, 1 failure <<< FAILURES!

**Comment by clintongormley** [comment] 2016-03-24 17:15
@polyfractal could you take a look at this please?

**Comment by polyfractal** [comment] 2016-03-24 19:44
Will take a look on my flight tonight.  Appears to be unrelated to the actual profile test though, since the cluster never made it to green for the test to start.

**Comment by polyfractal** [comment] 2016-04-04 17:47
I forgot to update this thread: I couldn't reproduce this failure either. :/

**Comment by clintongormley** [comment] 2016-05-03 14:13
No further failures. Closing

**Closed by clintongormley** 2016-05-03 14:13 UTC
Labels: :Search, bug, test
