### ISSUE TITLE
Data frame Job ID Ordering

### ISSUE THREAD

**Issue by varungupta2015135** [elastic/elasticsearch#44108] opened 2019-07-09 11:16 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 7.2.0

**Plugins installed**: []

**JVM version** (`java -version`): 
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.18.04.1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)

**OS version** (`uname -a` if on a Unix-like system): 18.04.1-Ubuntu SMP Tue Jun 25 15:14:42 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**: Data Frame jobs ordering according to ID is not right. If I flip the ID to ascending order, it should be  1 --> 2 --> ...  --> 10. Instead it goes like 1 --> 10--> ... --> 2.

**Steps to reproduce**: 

 1. Create 3 new data frame jobs with IDs of 1, 2, and 10.
 2. Go back to Data Frame jobs display page and click on the ID column to flip to ascending or descending order.

**Comment by markharwood** [comment] 2019-07-09 12:23
Thanks for report this.
To be more readable the Job ID allows alphanumeric characters e.g. typically we'd expect a meaningful ID like "SessionGrouper v1.1". To support this we must use an alphanumeric sort order.
A classic problem with sorting pure number strings alphanumerically is that 10 will come before 2.
If you need "correct" ordering on strings like this you can zero-prefix these strings e.g. 002 and 010.

Closing as "not a bug"

**Closed by markharwood** 2019-07-09 12:23 UTC
Labels: :ml/Data Frame, >bug
