### ISSUE TITLE
Support timeouts in _msearch API

### ISSUE THREAD

**Issue by msukmanowsky** [elastic/elasticsearch#11310] opened 2015-05-22 19:24 UTC
The `_msearch` API currently doesn't allow you to specify a timeout parameter in the header of each request.

This is problematic given that long running queries can easily swamp an ES node.

Recommend that we add timeout to the API which is specified per request in milliseconds for consistency with the timeout parameter for the `search` API:

```
{"timeout": 100}
{"query": ...}
{"timeout": 50}
{"query": ...}
...
```

Happy to contribute here but not sure where to start.

Thoughts?

**Comment by msukmanowsky** [comment] 2015-05-22 19:36
I suppose if https://www.elastic.co/guide/en/elasticsearch/guide/current/empty-search.html#_timeout is accurate

> Use the time-out because it is important to your SLA, not because you want to abort the execution of long-running queries.

Then this is irrelevant considering that the queries themselves will keep executing and swamping the server...

**Comment by clintongormley** [comment] 2015-05-25 17:37
@markharwood is this comment still (or was it ever) accurate?

**Comment by markharwood** [comment] 2015-05-26 08:43
The parameter referenced in https://www.elastic.co/guide/en/elasticsearch/guide/current/empty-search.html#_timeout overrides any setting in the query JSON body.

The timeout settings do curtail execution of queries on shards _but only when it gets the opportunity to do so._ 
Most of the heavy loops that are part of the query execution (e.g. collecting matching documents) have a timer check which should halt execution but there is always the potential for some other untimed loops (e.g.while loading FieldData) to overrun. We deliberately chose not to put a timeout into FieldData loading because that activity is a cost shared by many queries and so it doesn't make sense to shut it down early.

**Comment by msukmanowsky** [comment] 2015-05-26 13:36
In that case, sounds like adding support in msearch does make sense (and that the docs maybe need updating).

**Comment by discoverytrips** [comment] 2017-03-20 10:21
Use missing filter, which is essentially the inverse of exists: it returns a document that corresponds to a particular field without any value.

**Comment by discoverytrips** [comment] 2017-03-21 07:49
Because the timeout command will not stop the query, it just tells you the smooth return result nodes and then close the connection.
So you in each node to set timeout and no significance, and also affected your actual operation result.
However, you left out the parameters of the unit symbols.

**Comment by colings86** [comment] 2017-04-26 08:49
@clintongormley @markharwood is this a duplicate of https://github.com/elastic/elasticsearch/issues/4227 ? Seems like this issue asks for a specific parameter thats available onthe search API to be made available on the msearch API and the linked issue asks for the same but for all parameters supported by the search API?

**Comment by markharwood** [comment] 2017-04-26 09:35
> is this a duplicate of #4227 ?

Looks that way. If Clinton's 4227 suggestion of making _search an implicit _msearch with a count of 1 then this timeout issue and others would be dealt with. I'm not sure if there are any gotchas in taking that approach though..

**Comment by colings86** [comment] 2017-04-26 09:37
Closing in favour of #4227

**Closed by colings86** 2017-04-26 09:37 UTC
Labels: :Search, adoptme, low hanging fruit
