### ISSUE TITLE
Cross cluster search does not display results when one cluster is struggling

### ISSUE THREAD

**Issue by stejacks** [elastic/elasticsearch#84995] opened 2022-03-15 15:46 UTC
### Elasticsearch Version

7.17.0

### Java Version

_bundled_

### OS Version

Cloud

### Problem Description

Due to a cloud incident unrelated to elasticsearch, one of our regional logging clusters began experiencing intermittent high search thread pools.

This caused our single pane of glass cross cluster search cluster to become incapable of loading any dashboards.  Hitting anything that required CCS would spin for approximately a minute, and then display the following:

<img width="645" alt="Screen Shot 2022-03-15 at 11 45 02 AM" src="https://user-images.githubusercontent.com/8227774/158416416-a3db6886-757d-473a-81a1-d5a612052eeb.png">

### Steps to Reproduce

Create CCS to multiple clusters.

Cause one of them to become slow but not actually unresponsive.

**Comment by javanna** [comment] 2022-03-16 09:37
What is the desired behaviour compared to the observed behaviour? Did the cross-cluster search go through _search or _async_search ? Would you like to see search hits before all clusters have come back with their results, or aggregations results?

In general, in order to display search hits, results have to come in from all clusters and be reduced on the coordinating node. If the request went through async search, the aggs partial results are returned before all clusters come back, but not the search hits.

**Comment by neiljbrookes** [comment] 2022-03-16 10:03
> Did the cross-cluster search go through _search or _async_search

From memory, I think it went through `_async_search`. 

@stejacks will confirm, but I believe the desired behaviour is to display results from the available remote clusters and not allow timeouts to a single (misbehaving) remote cluster impact the viz of other data.

I understand this is probably a much more difficult problem than it sounds, but it would be good to hear what options are available ? Could CCS exclude the problem cluster from the map-phase and raise a warning that it was skipped  ?

**Comment by stejacks** [comment] 2022-03-16 15:04
I am confirming what @neiljbrookes said. :)

We are using this as a single pane of glass into the Elastic Cloud repository, and having it be completely dead when one of 160+ CCS nodes is having issues makes it essentially unusable.

We would need to have some method of degraded results when one host is down, whether that be what Neil suggested, some variety of timeout before showing what results they have, or some other option.  Simply not returning results means that we'd not be able to use this in any situation where we're having problems, which seriously limits one of the biggest use cases for this cluster.

**Comment by javanna** [comment] 2022-03-17 09:29
One host being down and one host being slow are two different scenarios.

When one host is down, and that is considered acceptable, you can set `skip_unavailable` to `true` in the configuration of its remote cluster connection so that it is declared optional, meaning errors received from it will be ignored. In that case there would be internal errors when communicating between the coordinating node and the downstream cluster, but the search would continue ignoring such cluster and returning the results it has available, while displaying that one cluster was skipped as part of the final search response.

On the other hand when the remote cluster is slowly responding like in your scenario, there may be timeouts at different levels, or it may just take a while. I believe, but please confirm this, that the timeout is on the client side based on your screenshot. 
If you go through the _search endpoint, there is no way to show partial results. Results have to be retrieved from all clusters and reduced back in the coordinating node, there is no other option. 
If you go through async search, client timeouts are suspicious, and in order to understand more we would need to look at the submit async search request as well as the get async search request that you are sending. Do you set the `wait_for_completion_timeout`? Async search does allow to retrieve partial results, but only for the aggregations side of the search and not for the search hits so far. There is an issue open on allowing to expose partial hits, see #62935, but I am not sure that this is necessarily what you are looking for here: search results may be misleading because without waiting for all results from all clusters, ES may return documents that are going to be later discarded.

**Comment by javanna** [comment] 2022-03-17 11:57
I realize that some of these questions are hard to answer as you are going through Kibana. You mentioned 7.17 which means that Kibana uses async search internally. Setting `wait_for_completion_timeout` is something that Kibana does and I am not sure users have control over. I will reach out to the Kibana team to get more context and see whether we can do something to improve this. I acknowledge that while we have a good answer for remote clusters being down, the behaviour for a remote cluster being very slow is something we need to look at and potentially improve.

**Comment by Dosant** [comment] 2022-03-17 16:28
>  You mentioned 7.17 which means that Kibana uses async search internally.

Yes, confirm

> Setting wait_for_completion_timeout is something that Kibana does and I am not sure users have control over

it is `100ms` and non configurable


I reproduced using a cluster that @javanna has sent me privately. There the timeout out kicked in exactly after 10 minutes of waiting. 

![Screen Shot 2022-03-17 at 17 22 51](https://user-images.githubusercontent.com/7784120/158846674-4d3a9fdb-a92d-43d5-a773-606d75735e2e.png)


This 10 minutes is configured in Kibana's advanced setting `search:timeout`. Since the issue description mentions "approximately a minute"  I wonder if there was a cluster with 1 minute configured as a `search:timeout`. @stejacks could you check advanced settings > `search:timeout` of that cluster?

**Comment by stejacks** [comment] 2022-03-17 16:47
I have to confess that I totally guessed at how long it took. :)  Ten minutes makes a lot of sense, and is very likely.

I also understand that down and slow are two very different cases, and that down is much easier to deal with.   My point in opening this ticket is that we'll need to also handle the slow use failure case better in order for this to work well in the cloud platform and also for our customers.

As all of these are also internal clusters, if you'd like to see or test any of it out in the staging environments, please feel free to reach out to me on slack (same username).

**Comment by benwtrent** [comment] 2024-07-10 11:48
Since this was last opened, we have made many strides in CCS and making its behavior nicer. 

Does this issue still exist? @quux00 @javanna ?

**Comment by naj-h** [comment] 2024-07-10 15:02
@benwtrent yes this should be fixed in 8.15.0 ([ES PR](https://github.com/elastic/elasticsearch/pull/103134), [Kibana PR](https://github.com/elastic/kibana/pull/179679)) - As a side note, the ES logic is fully implemented only for when [minimize_round_trips=true](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-cross-cluster-search.html#ccs-async-search-minimize-roundtrips-true), which is the default in Kibana dashboards and discover since 8.9.

**Closed** 2024-07-10 15:32 UTC
Labels: >bug, :Search/Search, Team:Search, priority:normal
