### ISSUE TITLE
[CI] :test:fixtures:azure-fixture:composeDown error while removing network XX has active endpoints

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#84897] opened 2022-03-10 22:59 UTC
### CI Link

https://gradle-enterprise.elastic.co/s/euelspokyjdvw

### Repro line

./gradlew :test:fixtures:azure:composeDown

### Does it reproduce?

Didn't try

### Applicable branches

master

### Failure history

https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=all_failures&failures.failureMessage=Execution%20failed%20for%20task%20*%0A%3E%20Exit-code%201%20when%20calling%20/usr/local/bin/docker-compose%2C%20stdout:%20N/A&search.relativeStartTime=P7D&search.timeZoneId=America/Chicago

### Failure excerpt

```
:test:fixtures:azure-fixture:composeDown FAILED
Removing 89cca2f066d0bf3df9b635216d80dacf_azure-fixture__azure-fixture-snapshot-based-recoveries_1 ... done	
Removing network 89cca2f066d0bf3df9b635216d80dacf_azure-fixture__default	
error while removing network: network 89cca2f066d0bf3df9b635216d80dacf_azure-fixture__default id e4f0d9b9d5079515e21f6c9076a3214a470314399d6d6780b9454802fc92c16b has active endpoints	
```

**Comment by mark-vieira** [comment] 2022-03-10 23:02
Closing as a duplicate of https://github.com/elastic/elasticsearch/issues/69045.

**Closed by mark-vieira** 2022-03-10 23:02 UTC
Labels: :Delivery/Build, >test-failure, needs:triage, Team:Delivery
