### ISSUE TITLE
analyze api hangs when the analyzer is not found

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#15190] opened 2015-12-02 16:20 UTC
The analyze api currently hangs when e.g. you refer to a custom analyzer and you forget to specify the index in the url. I remember from previous versions a nice "analyzer not found" error but that now (2.0) just hangs and the logs show:

```
[2015-12-02 15:27:46,621][ERROR][transport                ] [Smart Alec] failed to handle exception for action [indices:admin/analyze[s]], handler [org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$1@41c75d23]
java.lang.NullPointerException
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.perform(TransportSingleShardAction.java:195)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.access$700(TransportSingleShardAction.java:115)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$1.handleException(TransportSingleShardAction.java:174)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:821)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:799)
	at org.elasticsearch.transport.TransportService$4.onFailure(TransportService.java:361)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by clintongormley** [comment] 2015-12-03 13:13
Duplicate of #15148

**Closed by clintongormley** 2015-12-03 13:13 UTC
Labels: :Analysis, bug
