### ISSUE TITLE
Build is buggy for java 9.

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#18039] opened 2016-04-28 13:04 UTC
Try compiling with java 9:

First you will hit this. This can be fixed by using `assertEquals`, which also simplifies the test.

```
/home/rmuir/workspace/elasticsearch/core/src/test/java/org/elasticsearch/threadpool/ScalingThreadPoolTests.java:180: error: method invoked with incorrect number of arguments; expected 2, found 0
            assertThat(stats(threadPool, threadPoolName).getThreads(), equalTo(128));
                      ^
/home/rmuir/workspace/elasticsearch/core/src/test/java/org/elasticsearch/threadpool/ScalingThreadPoolTests.java:196: error: method invoked with incorrect number of arguments; expected 2, found 0
            assertThat(stats(threadPool, threadPoolName).getCompleted(), equalTo(128L));
                      ^
```

Next problem is that I am unsure `-source/-target` settings are being passed at all. Because I see class files referencing java 9 StringConcatFactory.

Next problem is that forbidden-apis screams, presumably because its being run in the wrong JVM (not the JAVA_HOME that is set, but the java 8 one running gradle itself). It sees StringConcatFactory and fails the build:

```
Caused by: org.gradle.internal.UncheckedException: de.thetaphi.forbiddenapis.ForbiddenApiException: Check for forbidden API calls failed: java.lang.ClassNotFoundException: java.lang.invoke.StringConcatFactory
    at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:45)
    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:78)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:227)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
    ... 68 more
Caused by: de.thetaphi.forbiddenapis.ForbiddenApiException: Check for forbidden API calls failed: java.lang.ClassNotFoundException: java.lang.invoke.StringConcatFactory
    at de.thetaphi.forbiddenapis.Checker.run(Checker.java:550)
    at de.thetaphi.forbiddenapis.gradle.CheckForbiddenApis.checkForbidden(CheckForbiddenApis.java:551)
    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
    ... 75 more
Caused by: java.lang.ClassNotFoundException: java.lang.invoke.StringConcatFactory
    at de.thetaphi.forbiddenapis.Checker.getClassFromClassLoader(Checker.java:264)
    at de.thetaphi.forbiddenapis.Checker.lookupRelatedClass(Checker.java:277)
    at de.thetaphi.forbiddenapis.ClassScanner$2.checkMethodAccess(ClassScanner.java:349)
    at de.thetaphi.forbiddenapis.ClassScanner$2.checkHandle(ClassScanner.java:411)
    at de.thetaphi.forbiddenapis.ClassScanner$2.visitInvokeDynamicInsn(ClassScanner.java:497)
    at de.thetaphi.forbiddenapis.asm.ClassReader.a(Unknown Source)
    at de.thetaphi.forbiddenapis.asm.ClassReader.b(Unknown Source)
    at de.thetaphi.forbiddenapis.asm.ClassReader.accept(Unknown Source)
    at de.thetaphi.forbiddenapis.asm.ClassReader.accept(Unknown Source)
    at de.thetaphi.forbiddenapis.Checker.checkClass(Checker.java:528)
    at de.thetaphi.forbiddenapis.Checker.run(Checker.java:545)
    ... 77 more


BUILD FAILED
```

**Comment by uschindler** [comment] 2016-04-28 13:10
I think the bug is plain simple:
- You do not pass -source/-target. This causes the source code compiled with Java 9 's javac emitting Java 9 bytecode that refers to Java 9's StringConcatFactory. In fact the code won't run with Java 8
- Forbidden fails because it runs in Gradle's JVM. In fact it is right: The code won't run on Java 8 at all.

So I think the compiler is wrong: It should also pass source/target 8 to make javac only use Java 8 source format and produce Java 8 class files.

**Comment by rmuir** [comment] 2016-04-28 13:13
Yeah, if i just `grep` for StringConcatFactory, it matches tons of class files. So either its not set correctly in the build, or its being ignored.

**Comment by uschindler** [comment] 2016-04-28 14:56
It is quite clear: I was not aware that the Groovy build runs under JDK 8 and just invokes the compiler of Java 9. If the java 9 compiler is not configured to compile class files for Java 8 (target is 1.8), it will use StringConcatFactory.

As the Groovy build runs under jdk 8 and loads forbiddenApis in its own JVM, it cannot find this class. In fact, it found the bug in the class output by javac, which produces wrong class files.
--
Uwe Schindler
H.-H.-Meier-Allee 63, 28213 Bremen
http://www.thetaphi.de

**Comment by rjernst** [comment] 2016-04-28 15:01
We do actually tell gradle what the target and source compatibility are. However, gradle has a check that breaks since when compiling with java 9, gradle is running under java 8, and javac is running with java 9.  This check needs to be simple, no condition on the trying to be "smart" and omit the compatibility arg:

```
if (targetCompatibility != null && !JavaVersion.current().equals(JavaVersion.toVersion(targetCompatibility))) {
            args.add("-target");
            args.add(targetCompatibility);
        }
```

**Comment by rmuir** [comment] 2016-04-28 16:38
I'm reopening because things still don't work. I see this now:
```
=======================================
Elasticsearch Build Hamster says Hello!
=======================================
  Gradle Version        : 2.12
  OS Info               : Linux 4.2.0-30-generic (amd64)
  JDK Version (gradle)  : Oracle Corporation 1.8.0_45 [Java HotSpot(TM) 64-Bit Server VM 25.45-b02]
  JAVA_HOME (gradle)    : /usr/local/jdk1.8.0_45
  JDK Version (compile) : Oracle Corporation 9-ea [Java HotSpot(TM) 64-Bit Server VM 9-ea+115]
  JAVA_HOME (compile)   : /home/rmuir/Downloads/jdk-9
:core:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.8
error: warnings found and -Werror specified
1 error
1 warning
:core:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:compileJava'.
> Compilation failed with exit code 1; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 16.944 secs
```

Additionally, we still need to deal with the compiler error in the test class at least too.

**Comment by uschindler** [comment] 2016-04-28 17:43
Can we please open a bug @ Gradle. This is total BULLSHIT! Why should it be smart at all? There is no reason! If one configures version "1.8" it should just pass it down to javac no matter which version it is. The good thing is that javac also complains if it is too old for the version you configured.

Total sonsense. The more I look into Gradle, the more it annoys me.

Just be safe and always pass -source and -target as configured! PERIOD.

**Comment by rjernst** [comment] 2016-04-28 17:53
Yes, I plan to open a bug (and fix) with gradle.

**Comment by rmuir** [comment] 2016-04-28 17:56
to be fair, i only tested with Gradle 2.12, but 2.13 is now released. the last time i had issues with java 9 stuff the newer releases seemed to have some fixes, so we may want to see if it happens on 2.13.

**Comment by rjernst** [comment] 2016-04-28 18:01
>  so we may want to see if it happens on 2.13

I have gradle checked out, the code i pasted is from tip of master. So the problem still exists. :/

**Comment by rjernst** [comment] 2016-04-28 18:15
I created a gradle discuss thread here (they don't want users creating jiras anymore I guess):
https://discuss.gradle.org/t/source-and-target-are-only-passed-to-javac-when-java-version-is-different-than-gradle-java-version/17235

**Comment by rjernst** [comment] 2016-04-28 18:29
And I opened a PR: gradle/gradle#627

**Comment by uschindler** [comment] 2016-04-28 20:00
Other thing: Does anybody know why the test code fails to compile with Java 9? Robert may say: "this is too complicated code" but actually this seems to be a javac bug? So report this to http://bugs.java.com/ !

**Comment by uschindler** [comment] 2016-04-28 20:48
@rmuir Isn't the new one just a duplicate of #13448?

**Comment by rjernst** [comment] 2016-04-28 23:21
I was not able to create a minimal reproduction for the test compile failure. I will switch it to assertEquals as @rmuir suggested.

**Comment by abhi8642** [comment] 2016-04-29 17:25
try clean and build option instead of build.

**Comment by rmuir** [comment] 2016-05-01 14:16
> Other thing: Does anybody know why the test code fails to compile with Java 9? Robert may say: "this is too complicated code" but actually this seems to be a javac bug? So report this to http://bugs.java.com/ !

I was hoping a couple javac bugs would put a dent in hamcrest matcher usage :)

In all seriousness, what causes things like `assertThat(x, equalTo(128))` and `assertTrue("x should be equal to 128 but isn't", x.equals(128))`. I know in the latter case, some features of the intellij IDE were responsible. almost as bad as the eclipse auto-generated "try/catch". 

Maybe we should ban this equalTo() method?

**Comment by uschindler** [comment] 2016-05-01 16:02
I agree, the hamcrest  stuff is only useful sometimes for more complicated matchers, but just comparing for equals should be done with assetEquals and not hamcrest or assetTrue.

I just said that we should report this bug to Oracle, because it could affect other code, too. It is clearly a bug if it fails to compile. Similar to the 8u20 problems with final vars in lambdas.

Unfortunately Ryan did not find a reproducer on isolation :(

**Comment by jasontedor** [comment] 2016-05-04 18:35
> Maybe we should ban this equalTo() method?

I think that `equalTo` is more readable than `assertEquals`. I also find it to be more flexible (e.g., `assertThat(s, anyOf(equalTo("x"), equalTo("y"))` instead of `assertTrue(s != null && (s.equals("x") || s.equals("y")))` because the latter gives a useless assertion message).

Since this is a subjective assessment, I think that banning `equalTo` is a bridge too far.

**Comment by rmuir** [comment] 2016-05-06 22:25
> I also find it to be more flexible

This very flexibility is what i hate. Why make complex assertions like that? Keep it simple.

**Comment by jasontedor** [comment] 2018-01-17 16:46
The build succeeds on JDK 9 now; in fact, we require compilation with JDK 9 since #28071.

**Closed by jasontedor** 2018-01-17 16:46 UTC
Labels: :Core, build
