### ISSUE TITLE
Update Quick Start Guide

### ISSUE THREAD

**Issue by fawazahmed0** [elastic/elasticsearch#85654] opened 2022-04-02 08:35 UTC
### Elasticsearch Version

NA

### Java Version

_bundled_

### OS Version

NA

### Problem Description

Hi,
I am new to elasticsearch, and I was following [quick start guide](https://www.elastic.co/guide/en/elasticsearch/reference/current/getting-started.html) and it is missing crucial information.

I was trying to execute the curl command given on [quick start guide](https://www.elastic.co/guide/en/elasticsearch/reference/current/getting-started.html) and it was failing:
```
curl -X GET http://localhost:9200/
```

![Screenshot (536)](https://user-images.githubusercontent.com/20347013/161374624-32df1a60-5bac-4f1a-bf7f-ab8fa1693fdd.png)

The crucial information is given on [this ](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html)page.
It states that you have to copy `http_ca.crt` file from docker and then run curl using:
```
curl --cacert http_ca.crt -u elastic https://localhost:9200
```

You should consider updating the quick start guide with this important step, because people who want to try elastic search for first time, will refer quick start guide and the curl command will fail, as the information given is outdated.

Thanks.
Fawaz Ahmed

### Steps to Reproduce

NA

**Comment by DJRickyB** [comment] 2022-04-05 17:49
closing as duplicate of #85130

**Closed by DJRickyB** 2022-04-05 17:49 UTC
Labels: >bug, needs:triage
