### ISSUE TITLE
[CI] SnapshotResiliencyTests.testConcurrentSnapshotCreateAndDeleteOther failure

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#55702] opened 2020-04-24 01:15 UTC
This is a new failure since today but it failed 5 times on `master` branch:
* https://gradle-enterprise.elastic.co/s/uallgp4u7igny
* https://gradle-enterprise.elastic.co/s/3yyhml2iknfju
* https://gradle-enterprise.elastic.co/s/u6uzbd7dye5ta
* https://gradle-enterprise.elastic.co/s/ft5l4vg3plocc
* This one has no build scan but jenkins job is https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_RUNTIME_JAVA=zulu11,nodes=general-purpose/649/console

The error message is
```
Expected: an instance of org.elasticsearch.snapshots.ConcurrentSnapshotExecutionException
     but: null
```

> ./gradlew ':server:test' --tests "org.elasticsearch.snapshots.SnapshotResiliencyTests.testConcurrentSnapshotCreateAndDeleteOther" -Dtests.seed=754A50E41B92E9E5 -Dtests.security.manager=true -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dtests.locale=sv-SE -Dtests.timezone=America/Argentina/Cordoba -Dcompiler.java=14 -Druntime.java=11

I cannot reproduce locally.

Sample stacktrace
```
at __randomizedtesting.SeedInfo.seed([754A50E41B92E9E5:C96E97BB010E765E]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at org.elasticsearch.snapshots.SnapshotResiliencyTests.lambda$testConcurrentSnapshotCreateAndDeleteOther$31(SnapshotResiliencyTests.java:541)
at org.elasticsearch.action.ActionListener$1.onFailure(ActionListener.java:71)
at org.elasticsearch.client.node.NodeClient.lambda$executeLocally$1(NodeClient.java:91)
at org.elasticsearch.tasks.TaskManager$1.onFailure(TaskManager.java:167)
at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$1.handleException(TransportMasterNodeAction.java:192)
at org.elasticsearch.transport.TransportService$6.handleException(TransportService.java:580)
at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1111)
at org.elasticsearch.test.transport.MockTransport.handleError(MockTransport.java:149)
at org.elasticsearch.test.transport.MockTransport.handleRemoteError(MockTransport.java:132)
at org.elasticsearch.test.disruption.DisruptableMockTransport$4$2.run(DisruptableMockTransport.java:227)
at org.elasticsearch.cluster.coordination.AbstractCoordinatorTestCase$1.run(AbstractCoordinatorTestCase.java:1234)
at org.elasticsearch.cluster.coordination.DeterministicTaskQueue.runTask(DeterministicTaskQueue.java:132)
at org.elasticsearch.cluster.coordination.DeterministicTaskQueue.runRandomTask(DeterministicTaskQueue.java:126)
at org.elasticsearch.cluster.coordination.DeterministicTaskQueue.runAllRunnableTasks(DeterministicTaskQueue.java:76)
at org.elasticsearch.snapshots.SnapshotResiliencyTests.testConcurrentSnapshotCreateAndDeleteOther(SnapshotResiliencyTests.java:559)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:566)
at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
at java.lang.Thread.run(Thread.java:834)
```

**Comment by ywangd** [comment] 2020-04-24 04:43
Another 3 more failures:
* https://gradle-enterprise.elastic.co/s/ugqczx3h7btkw
* https://gradle-enterprise.elastic.co/s/hcws26fkt2ooc
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_RUNTIME_JAVA=zulu11,nodes=general-purpose/650/console

I am muting it.

**Comment by ywangd** [comment] 2020-04-24 05:00
Muted #55703

**Comment by droberts195** [comment] 2020-05-04 08:22
The same error happened on 7.x in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=centos-7&&immutable/728/consoleText (sorry no Gradle scan for this one as there was an OOM in the build process after the failure occurred).

The error can be seen in the console log though, and it's the same as the one originally reported on master:

```
  2> java.lang.AssertionError: 
    Expected: an instance of org.elasticsearch.snapshots.ConcurrentSnapshotExecutionException
         but: null
        at __randomizedtesting.SeedInfo.seed([AEF01AA48AB9127E:12D4DDFB90258DC5]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.snapshots.SnapshotResiliencyTests.lambda$testConcurrentSnapshotCreateAndDeleteOther$31(SnapshotResiliencyTests.java:542)
        at org.elasticsearch.action.ActionListener$1.onFailure(ActionListener.java:71)
        at org.elasticsearch.action.support.TransportAction$1.onFailure(TransportAction.java:92)
        at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$1.handleException(TransportMasterNodeAction.java:192)
        at org.elasticsearch.transport.TransportService$6.handleException(TransportService.java:639)
        at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1173)
        at org.elasticsearch.test.transport.MockTransport.handleError(MockTransport.java:149)
        at org.elasticsearch.test.transport.MockTransport.handleRemoteError(MockTransport.java:132)
        at org.elasticsearch.test.disruption.DisruptableMockTransport$4$2.run(DisruptableMockTransport.java:227)
        at org.elasticsearch.cluster.coordination.AbstractCoordinatorTestCase$1.run(AbstractCoordinatorTestCase.java:1234)
        at org.elasticsearch.cluster.coordination.DeterministicTaskQueue.runTask(DeterministicTaskQueue.java:133)
        at org.elasticsearch.cluster.coordination.DeterministicTaskQueue.runRandomTask(DeterministicTaskQueue.java:127)
        at org.elasticsearch.cluster.coordination.DeterministicTaskQueue.runAllRunnableTasks(DeterministicTaskQueue.java:77)
        at org.elasticsearch.snapshots.SnapshotResiliencyTests.testConcurrentSnapshotCreateAndDeleteOther(SnapshotResiliencyTests.java:560)
```

The repro command for this one is:

```
./gradlew ':server:test' --tests "org.elasticsearch.snapshots.SnapshotResiliencyTests.testConcurrentSnapshotCreateAndDeleteOther" -Dtests.seed=AEF01AA48AB9127E -Dtests.security.manager=true -Dtests.locale=be -Dtests.timezone=Europe/Athens -Dcompiler.java=14 -Druntime.java=8
```

This did not reproduce locally for me on the 7.x branch.

**Comment by original-brownbear** [comment] 2020-05-04 09:49
I just merged https://github.com/elastic/elasticsearch/pull/56091 this morning which should bring `7.x` behavior in line with `master` and have fixed the test again on `7.x` -> closing here since that failing build didn't include that fix.

**Closed by original-brownbear** 2020-05-04 09:49 UTC
Labels: :Distributed/Snapshot/Restore, >test-failure, Team:Distributed
