### ISSUE TITLE
Wildcards and escape characters can not be queried at the same time

### ISSUE THREAD

**Issue by chickenlove** [elastic/elasticsearch#25328] opened 2017-06-21 03:27 UTC
elasticsearch version:5.4
`{
    "query": {
        "bool": {
            "must": [
                {
                    "query_string": {
                        "query": "domain:*.a\\-abc.com",
                        "analyze_wildcard": true
                    }
                },
                {
                    "range": {
                        "@timestamp": {
                            "gte": 1498013653031,
                            "lte": 1498014553031,
                            "format": "epoch_millis"
                        }
                    }
                }
            ],
            "must_not": []
        }
    }
}`
unavailable
`{
    "query": {
        "bool": {
            "must": [
                {
                    "query_string": {
                        "query": "domain:www.a\\-abc.com",
                        "analyze_wildcard": true
                    }
                },
                {
                    "range": {
                        "@timestamp": {
                            "gte": 1498013653031,
                            "lte": 1498014553031,
                            "format": "epoch_millis"
                        }
                    }
                }
            ],
            "must_not": []
        }
    }
}`
available
`{
  "query": {
    "wildcard": {
      "domain": {
        "value": "*a\\-abc.com", "boost" : 2.0
      }
    }
  }
}`
unavailable
`{
  "query": {
    "wildcard": {
      "domain": {
        "value": "*abc.com", "boost" : 2.0
      }
    }
  }
}`
available

**Comment by chickenlove** [comment] 2017-06-21 03:31
`"version" : {
    "number" : "5.4.0",
    "build_hash" : "780f8c4",
    "build_date" : "2017-04-28T17:43:27.229Z",
    "build_snapshot" : false,
    "lucene_version" : "6.5.0"
  }`

**Comment by tlrx** [comment] 2017-06-22 13:35
Can you please share your mappings and some sample documents to reproduce the issue?

**Comment by chickenlove** [comment] 2017-06-22 14:33
`
{
    "access-2017.06.21": {
        "mappings": {
            "fluentd": {
                "properties": {
                    "@timestamp": {
                        "type": "date"
                    },
                    "agent": {
                        "type": "text",
                        "fields": {
                            "keyword": {
                                "type": "keyword",
                                "ignore_above": 256
                            }
                        }
                    }
                    "domain": {
                        "type": "text",
                        "fields": {
                            "keyword": {
                                "type": "keyword",
                                "ignore_above": 256
                            }
                        }
                    }
                }
            }
        }
    }
}
`

**Comment by chickenlove** [comment] 2017-06-27 02:10
Do you need any other information?

**Comment by mayya-sharipova** [comment] 2018-03-22 20:46
@chickenlove  For your query `{ "query": { "wildcard": { "domain": { "value": "*a\\-abc.com", "boost" : 2.0 } } } }`, you should use `domain.keyword` field:

`{ "query": { "wildcard": { "domain.keyword": { "value": "*a\\-abc.com", "boost" : 2.0 } } } }`

Values in the `domain` field will be analyzed using Standard Analyzer that will remove `\\`. For example, if your domain is `"aaaa\\aaa-abc.com"`, you will get the following tokens: `["aaaa", "aaa", abc.com]`. Since none of these tokens contain `\\`, you will not get any results in return for your query.

Closing this issue, as this is not really an issue, but not correct use.

**Closed by mayya-sharipova** 2018-03-22 20:46 UTC
Labels: :Search/Search
