### ISSUE TITLE
[GEO] Ignore duplicate coordinates InvalidShapeException

### ISSUE THREAD

**Issue by danni** [elastic/elasticsearch#14014] opened 2015-10-08 06:16 UTC
Elasticsearch generates an InvalidShapeException from polygons generated by PostGIS:

```
MapperParsingException[failed to parse [catchment_mpoly]]; nested: InvalidShapeException[Provided shape has duplicate consecutive coordinates at: (145.105506775, -37.791859504, NaN)]
```

This particular check seems overzealous.

It's also surprising, given that the polygons are being fed through `ST_SimplifyPreserveTopology`. It is generating errors after its own precision is applied?

**Comment by clintongormley** [comment] 2015-10-08 13:30
@nknize could you take a look please?

**Comment by nknize** [comment] 2015-10-08 13:34
Thanks @danni can you provide the following so I can reproduce the issue: 
* ES version
* ```geo_shape``` field mapping
* geojson for the shape

**Comment by danni** [comment] 2015-10-13 05:30
Running on 1.7.2-1.

```
GEO_SHAPE = {
    'type': 'geo_shape',
    'tree': 'quadtree',
    'precision': '15m',
}
```

Having trouble outputting the full polygon due to buffer sizes.

The start of it is `mpoly: { "type": "MultiPolygon", "coordinates": [ [ [ [ 145.169139998999981, -37.862005047499991 ], [ 145.177806084499991, -37.863051944 ], [ 145.182334310999977, -37.863574976 ], [ 145.195710027999979, -37.865173764499993 ], [ 145.195406457499985, -37.865261251 ], [ 145.194888266999982, -37.865314197999986 ], [ 145.194754786499971, -37.86535698849999 ], [ 145.194700839499973, -37.865423255499991 ], [ 145.194712227499991, -37.865489966499993 ], [ 145.194749858999984, -37.865552071 ], [ 145.194801835, -37.865595139 ], [ 145.194896953999972, -37.865636745499984 ], [ 145.195023791499978, -37.865761047 ], [ 145.195104821499967, -37.865897262499992 ], [ 145.195151212999974, -37.865933226499997 ], [ 145.195197385499938, -37.865933578 ], [ 145.195271881999957, -37.865892711499988 ], [ 145.195398208499938, -37.865758993499995 ], [ 145.195451133499972, -37.865751279 ], [ 145.195508438499985, -37.865777197499995 ], [ 145.195516066999971, -37.865905439499997 ], [ 145.195455403999972, -37.866129678 ], [ 145.195399193999947, -37.866195574999985 ], [ 145.195355284499982, -37.866204547499997 ], [ 145.19527564149999, -37.866187860499991 ], [ 145.195120516499969, -37.866111233499986 ], [ 145.194927102999969, -37.866096951499998 ], [ 145.194564146999966, -37.866204806499994 ], [ 145.194258313499944, -37.866221160499997 ], [ 145.194204183999972, -37.866236275 ], [ 145.19416428949998, -37.866269685999988 ], [ 145.194178925999978, -37.866310626499995 ], [ 145.194227653499979, -37.866341947 ], [ 145.194458698499972, -37.866419998499993 ], [ 145.194729272999979, -37.866446509 ], [ 145.194793841499973, -37.866435390499994 ], [ 145.194865746499971, -37.866452447499988 ], [ 145.194930387999989, -37.866446564499988 ], [ 145.194974735499983, -37.866462641 ], [ 145.195002000999978, -37.866498401499996 ], [ 145.195005322499981, -37.866539138499995 ], [ 145.194946849499985, -37.866660739 ], [ 145.19484950399999, -37.866725229999986 ], [ 145.194675727499941, -37.866763228999986 ], [ 145.194639154499981, -37.866808646499997 ], [ 145.19461962699998, -37.866865071499994 ], [ 145.194706861999947, -37.866881555 ], [ 145.195039194499969, -37.866858023 ], [ 145.195102120499968, -37.866877577499992 ], [ 145.195122925499987, -37.866919776 ], [ 145.195104639, -37.866951189 ], [ 145.195051932999974, -37.866981954499991 ], [ 145.194570351999971, -37.867128548499984 ], [ 145.194461946999979, -37.867188451499992 ], [ 145.19441453349998, -37.867241602 ], [ 145.194291382499983, -37.867470650499989 ], [ 145.194285067999971, -37.867504413 ], [ 145.194306858499971, -37.867532440499993 ], [ 145.194357337999975, -37.867531719 ], [ 145.194617327499969, -37.867405252999987 ], [ 145.194822785999975, -37.867371583 ], [ 145.194954112999966, -37.867412394 ], [ 145.194986159999985, -37.867457737499997 ], [ 145.194984042999977, -37.867507188 ], [ 145.194755078499981, -37.867943381 ], [ 145.194681165999981, -37.868050015 ], [ 145.194619663499964, -37.868085257499992 ], [ 145.19435584149997, -37.868164178499995 ], [ 145.194079390499979, -37.868363442 ], [ 145.194014055499991, -37.868502506499993 ], [ 145.194044678999944, -37.868677609 ], [ 145.194019092499985, -37.868788054 ], [ 145.194043985499974, -37.868820225499995 ], [ 145.194076178499984, -37.868832490999985 ], [ 145.194127314999974, -37.868824073499994 ], [ 145.194172173499993, -37.868789737499995 ], [ 145.194229004, -37.868687432499996 ], [ 145.194270723499983, -37.868644013 ], [ 145.194465998499993, -37.868581779 ], [ 145.194766867999988, -37.868547517 ], [ 145.19482030399999, -37.868576488 ], [ 145.194817237999985, -37.868641996499989 ], [ 145.194741865499992, -37.868704008499989 ], [ 145.194537939999975, -37.868799413 ], [ 145.194293572499987, -37.869032513 ], [ 145.194155857999988, -37.869079854499994 ], [ 145.193937879999964, -37.869132357499993 ], [ 145.193683073499983, -37.869169079999985 ], [ 145.193633871499969, -37.869192723 ], [ 145.19364898249998, -37.869225560499991 ], [ 145.193719135499975, -37.869250683499992 ], [ 145.193806990999974, -37.869316025499991 ], [ 145.193814144999976, -37.869401958 ], [ 145.193729136499968, -37.869512236499986 ], [ 145.193560506499978, -37.869621053499991 ], [ 145.193544008499941, -37.869650579499996 ], [ 145.193601021499973, -37.869699382499995 ], [ 145.193724172499969, -37.869736475 ], [ 145.193789069499985, -37.869840426499991 ], [ 145.193809947499972, -37.869952388499989 ], [ 145.193778082999984, -37.870073933499988 ], [ 145.193673145499986, -37.870244374 ], [ 145.193367713499981, -37.870455902999986 ], [ 145.193209777999954, -37.870538468499987 ], [ 145.192953146499974, -37.870603440499991 ], [ 145.192884782, -37.870657035 ], [ 145.192859998499983, -37.87076378 ], [ 145.192867809499973, -37.870801686499995 ], [ 145.192906900999986, -37.870863532 ], [ 145.192968805, -37.870906766499992 ], [ 145.19299851599996, -37.870903177499997 ], [ 145.193167547499968, -37.870771938499985 ], [ 145.193296611499989, -37.870766888 ], [ 145.193343112499974, -37.870797006 ], [ 145.193340009999986, -37.870828603999989 ], [ 145.193297925499991, -37.870881624999988 ], [ 145.19323850349997, -37.870934035499985 ], [ 145.193121995499979, -37.871000246999984 ], [ 145.193103964499983, -37.871033343499995 ], [ 145.193113965499975, -37.871088251499991 ], [ 145.193281390999971, -37.871472996 ], [ 145.193268652499967, -37.87157593 ], [ 145.193205580499978, -37.871630005499995 ], [ 145.193082392999969, -37.871684025499995 ], [ 145.192925662, -37.871693719499994 ], [ 145.192618550999953, -37.871756564 ], [ 145.192583401499974, -37.871735881 ], [ 145.192596431999988, -37.871581146999986 ], [ 145.192577269499992, -37.871525332499992 ], [ 145.192547266499986, -37.871504649499997 ], [ 145.192403164499979, -37.87151049549999 ], [ 145.192291766499977, -37.871533565 ], [ 145.192218985499977, -37.871566809499988 ], [ 145.192171060999982, -37.871639644 ], [ 145.192150036999976, -37.871841404999984 ], [ 145.192112806999972, -37.871988073 ], [ 145.192061487999979, -37.872083569999987 ], [ 145.192070320999989, -37.872107638499998 ], [ 145.192104229499989, -37.872125528 ], [ 145.192385206499949, -37.87215054 ], [ 145.192601395999958, -37.872302351 ], [ 145.193039323, -37.872474086499984 ], [ 145.19312002449999, -37.872558909 ], [ 145.19312714199998, -37.872612041 ], [ 145.193094766499968, -37.872744094 ], [ 145.193103672499973, -37.872825124 ], [ 145.19313696049997, -37.872886248 ], [ 145.193259052999963, -37.873029104999986 ], [ 145.193275623999966, -37.873085696499984 ], [ 145.193264491499974, -37.873133075 ], [ 145.193128163999972, -37.873313265 ], [ 145.19310093499999, -37.873431442999987 ], [ 145.193127725999972, -37.873450683 ], [ 145.193182293499973, -37.873455289499987 ], [ 145.193411038999983, -37.873397995 ], [ 145.193459364999939, -37.873418326499994 ], [ 145.193476775499988, -37.873463633 ], [ 145.193430821999982, -37.873513953 ], [ 145.193274419499971, -37.873612928 ], [ 145.193055091, -37.873704558499995 ], [ 145.192820687999983, -37.873765700999989 ], [ 145.192751045999984, -37.873834595 ], [ 145.192739657999965, -37.873912036 ], [ 145.192759659999979, -37.873955843999987 ], [ 145.192803605999956, -37.873994268499992 ], [ 145.19287602199995, -37.874021056499991 ], [ 145.192973987999977, -37.874032674499993 ], [ 145.193125353499994, -37.873989791499994 ], [ 145.193259563999987, -37.873884952 ], [ 145.193334388999972, -37.873888652 ], [ 145.193388737499987, -37.873973844499993 ], [ 145.193395307499969, -37.874262019 ], [ 145.193343514, -37.874335464 ], [ 145.19329719549998, -37.874354833499993 ], [ 145.193245693999984, -37.874354426499991 ], [ 145.19310462149997, -37.874287178999985 ], [ 145.192889380999986, -37.874228293499996 ], [ 145.192613732999973, -37.874205538499993 ], [ 145.192351115499946, -37.874067121499998 ], [ 145.192193325999966, -37.874036633499991 ], [ 145.192151679499972, -37.874051341 ], [ 145.192119267499976, -37.874085473499989 ], [ 145.19208287699999, -37.874231586499995 ], [ 145.192112587999986, -37.874258929499995 ], [ 145.192266544999967, -37.874300018 ], [ 145.192368671999986, -37.874371243 ], [ 145.192414661999948, -37.874416142499996 ], [ 145.192416633, -37.87447064349999 ], [ 145.192399696999956, -37.874495655499985 ], [ 145.192283590499983, -37.874558888499998 ], [ 145.192158869999957, -37.874576556 ], [ 145.192036704499969, -37.874541961 ], [ 145.19189471949997, -37.874452883499991 ], [ 145.191852707999971, -37.874442135 ], [ 145.19181055049998, -37.874463076999987 ], [ 145.191841356499992, -37.874541258 ], [ 145.191889646, -37.874593668499998 ], [ 145.192062144999966, -37.874732381499996 ], [ 145.192245411499982, -37.874848875999987 ], [ 145.192321002999989, -37.874859717 ], [ 145.192362649499984, -37.87484948649999 ], [ 145.192465469999973, -37.87474005899999 ], [ 145.192527884999947, -37.874702855499997 ], [ 145.192583583999976, -37.874720356499992 ], [ 145.192629610499978, -37.87`

**Comment by nknize** [comment] 2015-11-03 19:37
@danni this check is per the [OGC SFA](http://www.opengeospatial.org/standards/sfa) and  [ISO 19107:2003](http://www.iso.org/iso/catalogue_detail.htm?csnumber=26012) standard.

Of course any software package can interpret the standard as they wish. Below is how we interpret:

Particularly:
> A Curve is simple if it does not pass through the same Point twice with the possible exception of the two end points (Reference [1], section 3.12.7.3):
> A Curve is closed if its start Point is equal to its end Point (Reference [1], section 3.12.7.3).
> A Curve that is simple and closed is a Ring.
> The boundary of a Polygon consists of a set of LinearRings that make up its exterior and interior boundaries; 

Once you have exported the offending polygon you can try "repairing" using the following packages https://github.com/tudelft3d/prepair

**Comment by nknize** [comment] 2015-11-12 17:47
@danni, I'm going to go ahead and close this and #14015 as a non issue. For the time being issue #12325 will remain open for further discussion and as a reference for cleaning invalid data.

**Closed by nknize** 2015-11-12 17:47 UTC
Labels: :Geo, discuss, feedback_needed

**Comment by smithsimonj** [comment] 2016-03-30 12:10
I get this issue with the attached shape for [Antarctica](https://github.com/elastic/elasticsearch/files/195290/Antarctica.txt) in Elasticsearch 2.2.1. The error is:

    Provided shape has duplicate consecutive coordinates at: (180.0, -90.0, NaN)

My mapping bit looks like:

    "location": {"type": "geo_shape", "precision": "1600m"}

The shape I am trying to load is in the attached JSON record (specifically the "geometry" field from within it): [Antarctica.txt](https://github.com/elastic/elasticsearch/files/195435/Antarctica.txt)

I agree with the analysis by @danni that this is a artifact of the shape being simplified before being indexed - the 'duplicate consecutive coordinates' being referred to in the error quite simply don't appear even once in the original data.

**Comment by smithsimonj** [comment] 2016-03-30 12:14
Do you want me to raise this as a new issue @nknize?

**Comment by clintongormley** [comment] 2016-03-30 20:41
@smithsimonj best to open a new issue, thanks
