### ISSUE TITLE
Support duration datatype

### ISSUE THREAD

**Issue by dagguh** [elastic/elasticsearch#42114] opened 2019-05-13 14:11 UTC
Support [ISO 8601 duration](https://en.wikipedia.org/wiki/ISO_8601#Durations) datatype.

#### Visualize
Visualize duration data (e.g. response times) as duration rather than ambiguous numbers.
Remove the need to specify the time unit on chart axes and other visualizations.
Remove the need for transporting the time unit in field names. 
Make it easier to interpret duration of various scale, e.g. reading [` "event.duration": 124000000`](https://github.com/elastic/beats/blob/d9668d356af2d25416453a4a78cb6f02cb11bd24/filebeat/module/elasticsearch/slowlog/test/test.log-expected.json#L68) from a chart is hard to interpret and internalize, even if you do know the time unit.

#### Ingest
Ingest ISO-standard-format data, [example](https://github.com/atlassian/report/blob/master/src/test/resources/com/atlassian/performance/tools/report/api/result/real-results/JIRA-JPT-9107/virtual-users/virtual-user-node-1/test-results/000adb0a-ffaf-47a9-b947-863fbbbe5290/action-metrics.jpt).
It's very difficult to parse it via Logstash or Beats. They don't support it out of the box. I cannot find a way to fix it via a Logstash codec or a Beats processor.

#### Query
Filter by duration. Avoid the need for time unit conventions in indexes by accepting standard duration notation in the criteria. Enable a more intuitive duration query GUI, e.g. a dedicated duration picker.

### Notes
It was [raised before](https://discuss.elastic.co/t/iso8601-durations/920).
Under the hood, ISO 8601 durations are perfectly representable as integers. E.g. `java.time.Duration` holds it as a pair of fields: `long seconds` and `int nanos`. It also offers rich behavior like parsing, stringifying, arithmetic, comparison, various tests and conversions.

**Comment by tvernum** [comment] 2019-05-15 04:34
@dagguh This seems to be a duplicate of https://github.com/elastic/elasticsearch/issues/31244.

Would you mind reading through that issue and adding a comment there if you think something is missing.

Thanks.

**Closed by tvernum** 2019-05-15 04:34 UTC
Labels: :Search/Mapping
