### ISSUE TITLE
Support snapshots on AWS Glacier?

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#12500] opened 2015-07-28 04:47 UTC
Apparently when data is moved from an S3 snapshot repository to Glacier we can no longer see it. This has come from https://discuss.elastic.co/t/snapshot-and-restore-s3-and-glacier/26337

Though this probably has an impact - _To keep costs low, Amazon Glacier is optimized for infrequently accessed data where a retrieval time of several hours is suitable._ https://aws.amazon.com/glacier/

Some more info from http://cloudacademy.com/blog/amazon-s3-vs-amazon-glacier-a-simple-backup-strategy-in-the-cloud/
_S3 objects that have been moved to Glacier storage using S3 Lifecycle policies can only be accessed (or shall I say restored) using the S3 API endpoints. As such they are still managed as objects within S3buckets, instead of Archives within Vaults, which is the Glacier terminology._

Based on that it looks like the biggest issue is going to be the retrieval time, as ES would expect a reasonably quick response from the "FS".

**Comment by geekpete** [comment] 2015-09-23 04:35
Almost needs a migration tool to move snapshots from s3 to glacier and back, where it tarballs and gzips (or some other method to create fewer or one file for glacier) then transfers to glacier. Then the reverse to "put it back" for restoration of the snapshot. 

Would be nicer to be a full plugin or be supported in the aws plugin,etc.

Would also be nice if this could be very parallel.

**Comment by CliveJL** [comment] 2015-10-16 10:51
I have been successfully archiving ES Snapshots to Glacier using an S3 Bucket Lifecycle policy for some time now. This Lifecycle policy archives the S3 objects in the **"indices/" path only**. This covers all the large snapshot data files. The much smaller snapshot metadata files, in the "root" of the Bucket, **always remains in S3's Standard storage class**, so they can be read immediately without causing errors for actions such as displaying snapshot data, for example the Curator "show snapshots" command.

On the odd occasion when I've needed to restore an index from a snapshot, I've used the AWS CLI tools (aws s3 & aws s3api) to restore the data file(s) from Glacier first, waited a few hours, and then use the ES API to restore the index(es) into the ES cluster. This process is a little long-winded but works.

One issue I have just come across is trying to delete snapshots that are no longer required. The Curator tool is using the DELETE snapshot call to the ES API, and this is throwing an error due to the storage class of the S3 object (presumably the Glaciered "indices/*" files).

It would be great to have the handling of Glaciered snapshots by Elasticsearch done transparently.

**Comment by dadoonet** [comment] 2015-11-30 14:16
See also discussion in #13656

**Comment by geekpete** [comment] 2016-05-06 00:51
Also to note is the new Infrequent Access storage class for S3 that Amazon now has.
This isn't as restrictive as Glacier, doesn't save you quite as much in cost but is still a very reduced cost compared to leaving it as is in S3. Which might make the glacier storage class slightly more special use case for only long term archival rather than pure cost saving now if much of your data may be ok to be set to Infrequent Access.

**Comment by ywelsch** [comment] 2018-03-21 16:48
@geekpete The S3 plugin supports the `storage_class` setting that can be set to `STANDARD_IA` for the infrequent access storage.
We explicitly forbid the `GLACIER` storage class, as writing a snapshot currently also potentially involves reading a lot of metadata files (low retrieval time, high costs). As such, I'm closing this issue. Please feel free to comment or +1 here if you want to add your point of view.

**Closed by ywelsch** 2018-03-21 16:48 UTC
Labels: :Distributed/Snapshot/Restore, discuss

**Comment by 2arunpmohan** [comment] 2021-11-28 03:00
> how do you manage to delete the old snapshots?

**Comment by dadoonet** [comment] 2021-11-28 03:13
> how do you manage to delete the old snapshots?

Please ask this question on https://ela.st/forum where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on https://ela.st/forum.

Thanks!

**Comment by ahenestrosa** [comment] 2022-09-01 19:23
> @geekpete The S3 plugin supports the `storage_class` setting that can be set to `STANDARD_IA` for the infrequent access storage. We explicitly forbid the `GLACIER` storage class, as writing a snapshot currently also potentially involves reading a lot of metadata files (low retrieval time, high costs). As such, I'm closing this issue. Please feel free to comment or +1 here if you want to add your point of view.

How about using de S3 Glacier Instant Retrieval now? It has milisecond retrieval time with much lower costs per GB than Standard and Standard IA.
