### ISSUE TITLE
Ability to change scripts directory

### ISSUE THREAD

**Issue by electrical** [elastic/elasticsearch#10369] opened 2015-04-01 14:39 UTC
At the moment the scripts directory is hard coded to `scriptsDirectory = new File(env.configFile(), "scripts");` but it would be handy to make this configurable.
Main reason is that with the Puppet module we allow multiple instances, and it would be handy that all instances on a single node can share the same directory where the scripts are located.

**Comment by javanna** [comment] 2015-04-01 14:41
This seems like a duplicate of #6766 ?

**Comment by electrical** [comment] 2015-04-01 14:43
@javanna oops you are right. must have overlooked it. Closing this one. thanks!

**Closed** 2015-04-01 14:44 UTC
