### ISSUE TITLE
Upgrade from 5.4.1 to 5.5 Fails

### ISSUE THREAD

**Issue by JimKeating2** [elastic/elasticsearch#25691] opened 2017-07-12 18:04 UTC
After upgrading a node from 5.4.1 to 5.5 the service will not start.  I've done lots of researching and tried tweaking permissions with no luck.  Tried running from the command line.  Here is the error:

Jul 12 10:40:36 es2 elasticsearch[7632]: 2017-07-12 10:40:36,370 main ERROR Could not register mbeans java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")
Jul 12 10:40:36 es2 elasticsearch[7632]: at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
Jul 12 10:40:36 es2 elasticsearch[7632]: at java.lang.SecurityManager.checkPermission(SecurityManager.java:585)
Jul 12 10:40:36 es2 elasticsearch[7632]: at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanTrustPermission(DefaultMBeanServerInterceptor.java:1848)
Jul 12 10:40:36 es2 elasticsearch[7632]: at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:322)
Jul 12 10:40:36 es2 elasticsearch[7632]: at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
Jul 12 10:40:36 es2 elasticsearch[7632]: at org.apache.logging.log4j.core.jmx.Server.register(Server.java:389)
Jul 12 10:40:36 es2 elasticsearch[7632]: at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:167)
Jul 12 10:40:36 es2 elasticsearch[7632]: at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:140)
Jul 12 10:40:36 es2 elasticsearch[7632]: at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:556)
Jul 12 10:40:36 es2 elasticsearch[7632]: at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:261)
Jul 12 10:40:36 es2 elasticsearch[7632]: at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:206)
Jul 12 10:40:36 es2 elasticsearch[7632]: at org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:221)
Jul 12 10:40:36 es2 elasticsearch[7632]: at org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:197)
Jul 12 10:40:36 es2 elasticsearch[7632]: at org.elasticsearch.common.logging.LogConfigurator.configureStatusLogger(LogConfigurator.java:175)
Jul 12 10:40:36 es2 elasticsearch[7632]: at org.elasticsearch.common.logging.LogConfigurator.configureWithoutConfig(LogConfigurator.java:99)
Jul 12 10:40:36 es2 elasticsearch[7632]: at org.elasticsearch.cli.Command.main(Command.java:85)
Jul 12 10:40:36 es2 elasticsearch[7632]: at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91)
Jul 12 10:40:36 es2 elasticsearch[7632]: at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84)
Jul 12 10:40:36 es2 elasticsearch[7632]: Exception in thread "main" java.lang.IllegalStateException: status logger logged an error before logging was configured
Jul 12 10:40:36 es2 elasticsearch[7632]: at org.elasticsearch.common.logging.LogConfigurator.checkErrorListener(LogConfigurator.java:128)
Jul 12 10:40:36 es2 elasticsearch[7632]: at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:117)
Jul 12 10:40:36 es2 elasticsearch[7632]: at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:316)
Jul 12 10:40:36 es2 elasticsearch[7632]: at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123)
Jul 12 10:40:36 es2 elasticsearch[7632]: at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114)
Jul 12 10:40:36 es2 elasticsearch[7632]: at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67)
Jul 12 10:40:36 es2 elasticsearch[7632]: at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
Jul 12 10:40:36 es2 elasticsearch[7632]: at org.elasticsearch.cli.Command.main(Command.java:88)
Jul 12 10:40:36 es2 elasticsearch[7632]: at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91)
Jul 12 10:40:36 es2 elasticsearch[7632]: at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84)
Jul 12 10:40:36 es2 elasticsearch[7632]: Refer to the log for complete error details.
Jul 12 10:40:36 es2 systemd[1]: elasticsearch.service: main process exited, code=exited, status=1/FAILURE
Jul 12 10:40:36 es2 systemd[1]: Unit elasticsearch.service entered failed state.

Thanks in advance...JK

**Comment by jasontedor** [comment] 2017-07-12 18:24
You've lost your jvm.options file which disables functionality in Log4j 2 that trips the security manager with this permission. Since this is not a bug I'm closing this issue. Please feel free to follow up on the [forum](https://discuss.elastic.co) for additional help if needed.

**Closed by jasontedor** 2017-07-12 18:24 UTC

**Comment by JimKeating2** [comment] 2017-07-12 18:27
The jvm.options file is still there and has not been changed...

**Comment by JimKeating2** [comment] 2017-07-12 18:30
# log4j 2
-Dlog4j.shutdownHookEnabled=false
-Dlog4j2.disable.jmx=true
-Dlog4j.skipJansi=true

**Comment by jasontedor** [comment] 2017-07-12 18:47
Do you see in the startup the JVM options that Elasticsearch was started with, we log them now? If you see those entries there, please let me know (and share the log line) and I will investigate further but right now I remain convinced that Elasticsearch is not being started with the correct jvm.options file.

**Comment by JimKeating2** [comment] 2017-07-12 18:59
Jason,  Thanks for the response.  I've done an upgrade from 5.4.1 to 5.5 twice now and had the same experience both times.  There is only the one jvm.options file and it has not been edited as it has the same file date that it had before the upgrade.  I had accidentally upgraded Elasticsearch the first time doing an apt-get upgrade command when patching one of our 4 Elasticsearch VMs.  (We had used the apt repository when installing the VMs and had forgot to remove it.)  The Elasticsearch service had the same error and I tried to fix it over a day's time...the next day it automatically removed itself from the cluster.  I rebuilt it with 5.5 and tried to join it to the cluster with no luck.  This morning I shut down the 3 working VMs and snapshotted them and restarted.   I then followed the instructions to do a rolling upgrade but received the same error that I had with the previous VM.  I reverted the snapshots on the 3 VMs a while ago so we could start logging again.  Any suggestions to get a successful upgrade would be appreciated..   BTW...I did submit this to the forum too.  Thanks again!  JK

**Comment by jasontedor** [comment] 2017-07-12 19:06
I want to help you but I think that my question still remains here, what JVM options do you see in the logs on startup on the 5.5.0 node? We have packaging tests that test upgrades from prior versions which pass so we will need something concrete here.

**Comment by JimKeating2** [comment] 2017-07-12 21:32
Jason,  I don't have time to try another upgrade to 5.5 soon so I'm giving up for now.  I've removed Elastic from my sources list so I can upgrade the server VMs without upgrading Elasticsearch.  I do still think there is a problem with the upgrade...maybe you will see it from others trying to do the same thing.  I reinstalled 5.4.1 from a .deb file on the 4th VM and the cluster is happy again.  Cheers!  JK

**Comment by jasontedor** [comment] 2017-07-12 21:45
Okay, I'm sorry that you ran into trouble and I will be on the look out for other reports.

**Comment by timwsuqld** [comment] 2017-07-13 22:21
@jasontedor We are running Ubuntu 16.04, using the ```https://artifacts.elastic.co/packages/5.x/apt stable/main amd64``` repository. Upgrading from 5.4.1 to 5.5 is giving us this error as well.

Where does the startup now log the JVM options? This is with the provided packages, no modifications done to jvm.options. Is it possible the 5.5 package has broken how it loads jvm.options?

```
Jul 14 08:19:57 suq-elasticsearch-1 elasticsearch[2450]: 2017-07-14 08:19:57,362 main ERROR Could not register mbeans java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")
Jul 14 08:19:57 suq-elasticsearch-1 elasticsearch[2450]:         at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
Jul 14 08:19:57 suq-elasticsearch-1 elasticsearch[2450]:         at java.lang.SecurityManager.checkPermission(SecurityManager.java:585)
Jul 14 08:19:57 suq-elasticsearch-1 elasticsearch[2450]:         at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanTrustPermission(DefaultMBeanServerInterceptor.java:1848)
Jul 14 08:19:57 suq-elasticsearch-1 elasticsearch[2450]:         at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:322)
Jul 14 08:19:57 suq-elasticsearch-1 elasticsearch[2450]:         at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
Jul 14 08:19:57 suq-elasticsearch-1 elasticsearch[2450]:         at org.apache.logging.log4j.core.jmx.Server.register(Server.java:389)
Jul 14 08:19:57 suq-elasticsearch-1 elasticsearch[2450]:         at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:167)
Jul 14 08:19:57 suq-elasticsearch-1 elasticsearch[2450]:         at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:140)
Jul 14 08:19:57 suq-elasticsearch-1 elasticsearch[2450]:         at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:556)
Jul 14 08:19:57 suq-elasticsearch-1 elasticsearch[2450]:         at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:261)
Jul 14 08:19:57 suq-elasticsearch-1 elasticsearch[2450]:         at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:206)
Jul 14 08:19:57 suq-elasticsearch-1 elasticsearch[2450]:         at org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:221)
Jul 14 08:19:57 suq-elasticsearch-1 elasticsearch[2450]:         at org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:197)
Jul 14 08:19:57 suq-elasticsearch-1 elasticsearch[2450]:         at org.elasticsearch.common.logging.LogConfigurator.configureStatusLogger(LogConfigurator.java:175)
Jul 14 08:19:57 suq-elasticsearch-1 elasticsearch[2450]:         at org.elasticsearch.common.logging.LogConfigurator.configureWithoutConfig(LogConfigurator.java:99)
Jul 14 08:19:57 suq-elasticsearch-1 elasticsearch[2450]:         at org.elasticsearch.cli.Command.main(Command.java:85)
Jul 14 08:19:57 suq-elasticsearch-1 elasticsearch[2450]:         at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91)
Jul 14 08:19:57 suq-elasticsearch-1 elasticsearch[2450]:         at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84)
Jul 14 08:19:57 suq-elasticsearch-1 elasticsearch[2450]: Exception in thread "main" java.lang.IllegalStateException: status logger logged an error before logging was configured
Jul 14 08:19:57 suq-elasticsearch-1 elasticsearch[2450]:         at org.elasticsearch.common.logging.LogConfigurator.checkErrorListener(LogConfigurator.java:128)
Jul 14 08:19:57 suq-elasticsearch-1 elasticsearch[2450]:         at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:117)
Jul 14 08:19:57 suq-elasticsearch-1 elasticsearch[2450]:         at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:316)
Jul 14 08:19:57 suq-elasticsearch-1 elasticsearch[2450]:         at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123)
Jul 14 08:19:57 suq-elasticsearch-1 elasticsearch[2450]:         at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114)
Jul 14 08:19:57 suq-elasticsearch-1 elasticsearch[2450]:         at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67)
Jul 14 08:19:57 suq-elasticsearch-1 elasticsearch[2450]:         at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
Jul 14 08:19:57 suq-elasticsearch-1 elasticsearch[2450]:         at org.elasticsearch.cli.Command.main(Command.java:88)
Jul 14 08:19:57 suq-elasticsearch-1 elasticsearch[2450]:         at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91)
Jul 14 08:19:57 suq-elasticsearch-1 elasticsearch[2450]:         at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84)
Jul 14 08:19:57 suq-elasticsearch-1 elasticsearch[2450]: Refer to the log for complete error details.
Jul 14 08:19:57 suq-elasticsearch-1 systemd[1]: elasticsearch.service: Main process exited, code=exited, status=1/FAILURE
Jul 14 08:19:57 suq-elasticsearch-1 systemd[1]: elasticsearch.service: Unit entered failed state.
Jul 14 08:19:57 suq-elasticsearch-1 systemd[1]: elasticsearch.service: Failed with result 'exit-code'.
```

**Comment by timwsuqld** [comment] 2017-07-13 22:34
After further investigation, there was a ```jvm.options.dpkg-dist``` file, indicating that apt thought there was a conflict, and so didn't overwrite the jvm.options with the packaged version. This file appears to have happened in a previous updated, but 5.5 was the first version to throw an error.
Overwriting the jvm.options with the jvm.options.dpkg-dist and everything is working.

**Comment by tinawenqiao** [comment] 2017-07-14 14:43
@jasontedor Hi,I have the same problem upgrade from 5.4.0 to 5.5. Run the es with supervisor with the following config. And I set the var ENV_MASTER_JVM_OPTIONS in my profile. What should I do?
[program:elkmaster]
environment=ES_JVM_OPTIONS=%(ENV_MASTER_JVM_OPTIONS)s
command =  /logger/elasticsearch/bin/elasticsearch -Epath.conf=/logger/elasticsearch/configmaster
username = logger
autostart=true
autorestart=false
startsecs=3
priority=1000
redirect_stderr=true
stdout_logfile=/logger/elasticsearch/bin/logs/supervisor_master.log

The error log:
2017-07-14 22:42:08,247 main ERROR Could not register mbeans java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:585)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanTrustPermission(DefaultMBeanServerInterceptor.java:1848)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:322)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
	at org.apache.logging.log4j.core.jmx.Server.register(Server.java:389)
	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:167)
	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:140)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:556)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:261)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:206)
	at org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:221)
	at org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:197)
	at org.elasticsearch.common.logging.LogConfigurator.configureStatusLogger(LogConfigurator.java:175)
	at org.elasticsearch.common.logging.LogConfigurator.configureWithoutConfig(LogConfigurator.java:99)
	at org.elasticsearch.cli.Command.main(Command.java:85)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84)

Exception in thread "main" java.lang.IllegalStateException: status logger logged an error before logging was configured
	at org.elasticsearch.common.logging.LogConfigurator.checkErrorListener(LogConfigurator.java:128)
	at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:117)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:316)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.Command.main(Command.java:88)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84)
Refer to the log for complete error details.
