### ISSUE TITLE
Range aggregation nested in a filter aggregation yields non-filtered records

### ISSUE THREAD

**Issue by dinamic** [elastic/elasticsearch#44162] opened 2019-07-10 11:56 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 5.6.13 via docker image (docker.elastic.co/elasticsearch/elasticsearch)

**Plugins installed**: default setup with x-pack enabled

**JVM version** (`java -version`):

```
sh-4.2$ java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system):

Docker Desktop Edge 2.0.5.0 running on macOS 10.14.5

```
sh-4.2$ uname -a
Linux 0f12147f0d69 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

I am trying to use a range aggregation nested in a filter one. The filter contains a term query to discriminate on the status field that we've got. The range aggregation operates in a nested document.

The issue that I am running into is that the range aggregation returns documents that should have been discriminated by the filter aggregation earlier.

I have been looking around whether this is expected behavior but was unable to find any relevant information.

Could you please tell me if this is a bug or am I doing something wrong?

Here's the query I'm trying to use: [github_example_query.txt](https://github.com/elastic/elasticsearch/files/3377281/github_example_query.txt). You could see that I filter by `status = completed`, yet the range aggregation gives me records that have their `status` field set to other values.

**Comment by dinamic** [comment] 2019-07-10 12:23
The problem that I've got seem similar as to the bug report in https://github.com/elastic/elasticsearch/issues/18412

**Comment by dinamic** [comment] 2019-07-10 16:01
@PhaedrusTheGreek could you spot something wrong with my query?

**Comment by polyfractal** [comment] 2019-07-10 19:50
I believe this is the same situation as #18412, and not a bug.  What's likely happening is that your first filter finds documents that have status `completed`, but since they are nested there are also other statuses.  Then the next aggregations work on the full nested document and collect all the docs regardless of their statuses.  You probably need to invert the query as suggested in https://github.com/elastic/elasticsearch/issues/18412 (quoting from that ticket):

> In the first query, the filter keeps root documents that have at leas one nested document that matches the query. Since the 2nd root document has one nested document that matches, it is selected. Then we run the nested aggregation, which can see all nested docs of this root document.
> 
> On the other hand the second query first goes to the nested documents, and then only keeps those that match the filter, so there is only one bucket: the one that matches the filter.



Although it's hard to say without seeing the mapping.  If you open a post at the [Discuss Forums](https://discuss.elastic.co/c/elasticsearch) with the query and the mapping we can help work through the query there.

We try to reserve Github tickets for known bugs or feature requests.  I'm going to close this ticket for now.

**Closed by polyfractal** 2019-07-10 19:50 UTC
Labels: :Analytics/Aggregations

**Comment by dinamic** [comment] 2019-07-11 13:54
Thanks @polyfractal

**Comment by dinamic** [comment] 2019-07-11 15:15
@polyfractal just posted a question at the Discuss Forums. I would appreciate any help!

Here's link to the question:
- https://discuss.elastic.co/t/nested-range-aggregation-misbehaving/190055

**Comment by dinamic** [comment] 2019-07-12 09:45
@polyfractal I still think this is a bug. I have a filter aggregation that has a boolean statement in it and the range aggregation is nested after. So, no actual nesting could be messed up IMO.

Maybe I spoke too soon and not understanding what the underlying issue in #18412 is. Maybe this misleads you on thinking it's the same problem here.

The query, the mapping, and the result are linked in the Elastic Discuss.

Could you have a look, please?

**Comment by polyfractal** [comment] 2019-07-12 13:42
Patience...  I'm probably in a different time zone from you and can't respond to tickets immediately either :)

I'll leave a reply on the forum thread.  Thanks for opening a discuss thread!
