### ISSUE TITLE
[CI] CoordinatorTests.testLogsWarningPeriodicallyIfClusterNotFormed failing on 7.x

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#46920] opened 2019-09-20 12:49 UTC
Logs: https://gradle-enterprise.elastic.co/s/n2zxbakfbzi36/console-log?task=:server:test

Couldn't reproduce locally with:
```
./gradlew ':server:test' --tests "org.elasticsearch.cluster.coordination.CoordinatorTests.testLogsWarningPeriodicallyIfClusterNotFormed" \
  -Dtests.seed=4223C526497B2D65 \
  -Dtests.security.manager=true \
  -Dtests.locale=no \
  -Dtests.timezone=Asia/Chungking \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

Stacktrace:
```

org.elasticsearch.cluster.coordination.CoordinatorTests > testLogsWarningPeriodicallyIfClusterNotFormed FAILED
--
java.lang.AssertionError: [{node0}{zL-LbQAAQACH3l2B_____w}{0.0.0.0}{0.0.0.0:20}{dim}, {node2}{77fEz___T_-jSIsAAAAAAA}{0.0.0.0}{0.0.0.0:22}{dim}] vs [{node0}{zL-LbQAAQACH3l2B_____w}{0.0.0.0}{0.0.0.0:20}{dim}, {node1}{J6nlEgAAQACtOVyt_____w}{0.0.0.0}{0.0.0.0:16}{dim}, {node2}{77fEz___T_-jSIsAAAAAAA}{0.0.0.0}{0.0.0.0:22}{dim}]
Expected: <[{node0}{zL-LbQAAQACH3l2B_____w}{0.0.0.0}{0.0.0.0:20}{dim}, {node1}{J6nlEgAAQACtOVyt_____w}{0.0.0.0}{0.0.0.0:16}{dim}, {node2}{77fEz___T_-jSIsAAAAAAA}{0.0.0.0}{0.0.0.0:22}{dim}]>
but: was <[{node0}{zL-LbQAAQACH3l2B_____w}{0.0.0.0}{0.0.0.0:20}{dim}, {node2}{77fEz___T_-jSIsAAAAAAA}{0.0.0.0}{0.0.0.0:22}{dim}]>
at __randomizedtesting.SeedInfo.seed([4223C526497B2D65:7FE5C0D97B91B710]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:956)
at org.elasticsearch.cluster.coordination.CoordinatorTests$3.assertMatched(CoordinatorTests.java:1250)
at org.elasticsearch.test.MockLogAppender.assertAllExpectationsMatched(MockLogAppender.java:66)
at org.elasticsearch.cluster.coordination.CoordinatorTests.testLogsWarningPeriodicallyIfClusterNotFormed(CoordinatorTests.java:1255)

```

**Comment by DaveCTurner** [comment] 2019-09-20 15:46
This reproduces, eventually, after sufficiently many iterations and without specifying a seed. It does not seem to be deterministically reproducible. I will continue investigating.

**Comment by DaveCTurner** [comment] 2019-09-22 15:05
This is a test bug due to a delay that's 200ms too short, and I opened #46958 to fix it.

The lack of reproducibility is due to the known nondeterminism in iteration order of HPPC sets which can be fixed by adding `-Dtests.jvm.argline="-Dhppc.bitmixer=DETERMINISTIC"`.

**Closed** 2019-09-23 09:46 UTC
Labels: :Distributed/Cluster Coordination, >test-failure
