### ISSUE TITLE
file permissions for ingest-geoip

### ISSUE THREAD

**Issue by misch42** [elastic/elasticsearch#29284] opened 2018-03-28 15:14 UTC
Hi,

I installed ingest-geoip plugin and upgraded elasticsearch to 6.2.2. After the upgrade elasticsearch refused to start with the error message in the logs:

org.elasticsearch.bootstrap.StartupException: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /etc/elasticsearch/ingest-geo
ip

**Elasticsearch version** (`bin/elasticsearch --version`):
6.2.2. (after upgrade)

**Plugins installed**: []
ingest-geoip

**JVM version** (`java -version`):
# java -version
openjdk version "1.8.0_161"
OpenJDK Runtime Environment (IcedTea 3.7.0) (Gentoo icedtea-3.7.0)
OpenJDK 64-Bit Server VM (build 25.161-b12, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux XXX 3.14.27-hardened-r1 #1 SMP Wed Dec 31 01:33:16 CET 2014 x86_64 QEMU Virtual CPU version 1.4.0 GenuineIntel GNU/Linux

**Description of the problem including expected versus actual behavior**:
see above

**Steps to reproduce**:

 1. bin/elasticsearch-plugin install ingest-geoip
 2. emerge elasticsearch (yes, I am on gentoo) 
 3. /etc/init.d/elasticsearch start

**Provide logs (if relevant)**:
see above.

Resolution:
chown -R elasticsearch /etc/elasticsearch/ingest-geo

**Comment by bleskes** [comment] 2018-03-28 15:26
I'm going to label this as packaging and plugins labels first as I feel people with that expertise should look at this first. If it turns out to be something with the specific plugin we can re-label.

**Comment by rjernst** [comment] 2018-03-28 15:39
Note: We have no tests for and do not officially support gentoo systems.

Can you run `ls -ld /etc/elasticsearch` and show the results here?

**Comment by jasontedor** [comment] 2018-03-28 17:07
I think that this is neither a bug with the packaging nor a bug with the plugin. Instead, I suspect there is a problem with the environment here. Specifically, I suspect that the `setgid` bit is missing on `/etc/elasticsearch`. I am removing the bug label and marking this one as pending feedback, namely the information that was requested by @rjernst.

**Comment by misch42** [comment] 2018-03-29 14:49
# ls -ld /etc/elasticsearch/
drwxr-xr-x 4 root root 4096 Mar 28 16:43 /etc/elasticsearch/

But if you want the rights on the dir below it is:
# ls -ld /etc/elasticsearch/*
-rw-r--r-- 1 root          root 3000 Mar  2 21:55 /etc/elasticsearch/elasticsearch.yml
drwxr-x--- 2 elasticsearch root 4096 Mar 28 16:43 /etc/elasticsearch/ingest-geoip
-rw-r--r-- 1 root          root 2767 Mar 28 15:53 /etc/elasticsearch/jvm.options
-rw-r--r-- 1 root          root 5091 Mar 28 15:53 /etc/elasticsearch/log4j2.properties
-rw-r--r-- 1 root          root 2571 Mar  8  2016 /etc/elasticsearch/logging.yml
drwxr-xr-x 2 root          root 4096 Mar 28 15:53 /etc/elasticsearch/scripts

Please note that I already changed the ownership of the ingest-geoip directory.

**Comment by jasontedor** [comment] 2018-03-29 16:28
I wanted to see the permissions on `/etc/elasticsearch` and it shows exactly what I thought would be the case. Namely, it does not have the `setgid` bit set:

```
drwxr-xr-x 4 root root 4096 Mar 28 16:43 /etc/elasticsearch/
```

Instead, this should be:

```
drwxr-s--- 2 root elasticsearch ...
```

I am not sure exactly how you installed Elasticsearch, but the package does establish these [directories in this way](https://github.com/elastic/elasticsearch/blob/v6.2.2/distribution/src/main/packaging/scripts/postinst#L102-L104).

Since it appears that you have deviated from the intended package configuration, I am closing this as not a bug. Please feel free to continue the discussion if needed, we can reopen this if you do present evidence of a bug here.

**Closed by jasontedor** 2018-03-29 16:28 UTC
Labels: :Core/Packaging, feedback_needed
