### ISSUE TITLE
Remove initializing/relocating replicas with higher priority

### ISSUE THREAD

**Issue by gf2121** [elastic/elasticsearch#69981] opened 2021-03-04 16:00 UTC
1. Create an index with shards like this:
```
prirep shard state
p      0     STARTED
p      1     STARTED
p      2     STARTED
p      3     STARTED
p      4     STARTED
p      5     STARTED
p      6     STARTED
p      7     STARTED
r      0     STARTED
r      1     STARTED
r      2     STARTED
r      3     STARTED
r      4     STARTED
r      5     STARTED
r      6     STARTED
r      7     STARTED
```
2. Updated its setting to have 2 replicas.
```
prirep shard state
p      0     STARTED
p      1     STARTED
p      2     STARTED
p      3     STARTED
p      4     STARTED
p      5     STARTED
p      6     STARTED
p      7     STARTED
r      0     STARTED
r      1     STARTED
r      2     STARTED
r      3     STARTED
r      4     STARTED
r      5     STARTED
r      6     STARTED
r      7     STARTED
r      0     INITIALIZING
r      1     INITIALIZING
r      2     INITIALIZING
r      3     INITIALIZING
r      4     INITIALIZING
r      5     INITIALIZING
r      6     INITIALIZING
r      7     INITIALIZING
```
3. Update it back to 1 replica
```
prirep shard state
p      0     STARTED
p      1     STARTED
p      2     STARTED
p      3     STARTED
p      4     STARTED
p      5     STARTED
p      6     STARTED
p      7     STARTED
r      0     INITIALIZING
r      1     INITIALIZING
r      2     STARTED
r      3     INITIALIZING
r      4     STARTED
r      5     STARTED
r      6     INITIALIZING
r      7     STARTED
```
As we can see, the replicas are just removed randomly. I think it could be nice if Elasticsearch can automatically choose the `INITIALIZING` replicas to remove, because `INITIALIZING` would cost cluster resources and `INITIALIZING` replicas can not help execute search requests.

**Comment by DaveCTurner** [comment] 2021-03-04 16:08
This seems like a reasonable request to me. I'm not sure why you opened two issues on the subject tho. I'm closing this as a duplicate of #69982.

**Closed by DaveCTurner** 2021-03-04 16:08 UTC
Labels: >enhancement, needs:triage

**Comment by gf2121** [comment] 2021-03-04 16:20
> This seems like a reasonable request to me. I'm not sure why you opened two issues on the subject tho. I'm closing this as a duplicate of #69982.

I thought I had to open an issue before opening a pull request... Sorry for the duplicate.

**Comment by DaveCTurner** [comment] 2021-03-04 16:31
No problem. It's usually a good idea to discuss your idea before working on a PR, but if you already did the work then there's no need for a separate issue for the discussion.
