### ISSUE TITLE
javadoc rendering in 6.7 is breaking links of same package different module

### ISSUE THREAD

**Issue by hub-cap** [elastic/elasticsearch#41212] opened 2019-04-15 17:51 UTC
the HLRC depends on some code in another module that is in the same package as the client, `o.e.client`. In the deployed javadoc for 6.6, the links between the HLRC javadoc and this other module work fine, but in 6.7 the are broken. This is broken in 6.7 and up to master.

In the following examples, navigate to the `RestClientBuilder` and click or hover over it. It does not resolve to a URL with `client/` in it at all.

[Example working](https://artifacts.elastic.co/javadoc/org/elasticsearch/client/elasticsearch-rest-high-level-client/6.6.1/org/elasticsearch/client/RestHighLevelClient.html)

[Example broken](https://artifacts.elastic.co/javadoc/org/elasticsearch/client/elasticsearch-rest-high-level-client/6.7.1/org/elasticsearch/client/RestHighLevelClient.html)

**Comment by jasontedor** [comment] 2019-04-15 18:19
I suspect this is due to the change to use the JDK 12 compiler. It could be that this is expected behavior now (or that we were relying on a buggy behavior before), something that we would need to investigate.

**Comment by rjernst** [comment] 2019-04-15 18:39
I think the issue is we have split packages. We need to clean this up, since java modules will not support this. Building the javadocs has to guess and (arbitrarily) chooses which jar contains a given package.

**Comment by mark-vieira** [comment] 2022-05-03 02:21
Given we've "removed" the HLRC in current branches in favor of https://github.com/elastic/elasticsearch-java I think we can close this issue.

**Closed by mark-vieira** 2022-05-03 02:21 UTC
Labels: >bug, :Delivery/Build, Team:Delivery
