### ISSUE TITLE
Docker images failing build

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#36414] opened 2018-12-10 08:23 UTC
CI is tripping all over the newly added Docker images build.

```
> Task :distribution:docker:buildDockerImage FAILED
invalid reference format
Task ':distribution:docker:buildDockerImage' is not up-to-date because:

FAILURE: Build failed with an exception.
  Task has not declared any outputs despite executing actions.
Starting process 'command 'docker''. Working directory: /var/lib/jenkins/workspace/elastic+elasticsearch+6.x+multijob-unix-compatibility/os/opensuse/distribution/docker Command: docker build build/docker --pull --tag elasticsearch:6.6.0-SNAPSHOT --tag docker.elastic.co/elasticsearch/elasticsearch:6.6.0-SNAPSHOT --tag docker.elastic.co/elasticsearch/elasticsearch-full:6.6.0-SNAPSHOT
Successfully started process 'command 'docker''
Sending build context to Docker daemon  147.1MB


* What went wrong:
Step 1/30 : FROM centos:7 AS builder
Execution failed for task ':distribution:docker:buildDockerImage'.
> Process 'command 'docker'' finished with non-zero exit value 1
:distribution:docker:buildDockerImage (Thread[Execution worker for ':' Thread 11,5,main]) completed. Took 0.652 secs.
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=opensuse/108/console

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+release-tests/195/console

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-darwin-compatibility/108/console

and many many more.

Relates to #36246

**Comment by jasontedor** [comment] 2018-12-10 21:01
Half of these are addressed by an internal infra PR that I opened. I am looking into the other failures.

The salient error message is:

```

:distribution:docker:buildDockerImage FAILED
--
Sending build context to Docker daemon  147.1MB
 
Step 1/30 : FROM centos:7 AS builder
invalid reference format
```

**Comment by jasontedor** [comment] 2018-12-10 21:03
This `invalid reference format` issue appears to only be occurring on the openSUSE CI workers, so something is off there.

**Comment by nknize** [comment] 2018-12-10 21:06
Out of the blue I randomly started getting the following on #35320:

```15:02:09 Caused by: java.lang.IllegalArgumentException: expected build.docker to be unset or one of "true" or "false" but was [$(]```

Link to Jenkins build:  https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-2/1814/console

**Comment by jasontedor** [comment] 2018-12-10 21:49
We are actively working on this internally, sorry for the issues.

**Comment by jasontedor** [comment] 2018-12-11 02:51
A multi-stage Docker build as we use requires Docker 17.05 or higher, and the openSUSE CI workers only have Docker 17.04.

**Comment by jasontedor** [comment] 2018-12-11 03:03
I opened an internal issue for this.

**Comment by jasontedor** [comment] 2018-12-11 17:09
I opened #36497 so that the issue is more apparent.

**Comment by jasontedor** [comment] 2018-12-17 13:07
I opened #36706.

**Closed** 2018-12-20 10:15 UTC
Labels: :Core/Infra/Packaging, >test-failure
