### ISSUE TITLE
elasticsearch 6.3 doesn't work on macOS catalina

### ISSUE THREAD

**Issue by eswenson1** [elastic/elasticsearch#49664] opened 2019-11-27 22:46 UTC
**Elasticsearch version** (`bin/elasticsearch --version`):

Version: 6.3.2, Build: default/tar/053779d/2018-07-20T05:20:23.451332Z, JVM: 1.8.0_181

**Plugins installed**: None

**JVM version** (`java -version`):

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):

macOS Catalina 10.15.1

**Description of the problem including expected versus actual behavior**:

Cannot start up elastisearch after upgrading to Catalina. First problem is that I get the popup dialog indicating that "controller" can't be run because it can't be virus checked because the developer cannot be identified. My company has configured my machine (with JAMF) so that I cannot choose the "Allow any" option to prevent Gatekeeper from prohibiting running apps that aren't properly signed.  (You can get around this issue by manually running "./modules/x-pack/x-pack-ml/platform/darwin-x86_64/bin/controller &", but that is not a good solution.

Then, after getting past the first problem, I get errors like:

[2019-11-27T14:37:24,736][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: ElasticsearchException[Failed to create native process factories for Machine Learning]; nested: FileNotFoundException[/var/folders/ch/ffy34wnx2hs87hg6l_nq2m4jk1svrc/T/elasticsearch.enCagApJ/controller_log_16294 (No such file or directory)];
...
Caused by: org.elasticsearch.ElasticsearchException: Failed to create native process factories for Machine Learning

and 

Caused by: java.io.FileNotFoundException: /var/folders/ch/ffy34wnx2hs87hg6l_nq2m4jk1svrc/T/elasticsearch.enCagApJ/controller_log_16294 (No such file or directory)

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. start macOS Catalina
 2. run bin/elasticsearch

**Provide logs (if relevant)**:

**Comment by matriv** [comment] 2019-11-28 13:55
Hello @eswenson1,

There is already an [open issue](https://github.com/elastic/elasticsearch/issues/46498) for the Catalina problems with notarization: 
but keep in mind that it won't be fixed for versions < `6.8`.

Closing this as a duplicate of #46498

**Closed by matriv** 2019-11-28 13:55 UTC

**Comment by Kxrr** [comment] 2020-12-18 02:52
```
curl -L -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.8.5.tar.gz
```

works for me on macOS Catalina.

**Comment by eswenson1** [comment] 2020-12-18 15:52
Yes, thanks, @Kxrr. I'm using 6.8.5 now, with no issues on Big Sur, and previously Catalina.
