### ISSUE TITLE
Search slow logs throws JSonGeneration exception when trying to log the actual query that was executed.

### ISSUE THREAD

**Issue by DivyaMalini** [elastic/elasticsearch#27749] opened 2017-12-11 09:45 UTC
Is this bug report or feature request for a supported OS?
>>[Divya] I guess this is a bug where we are not handling some corner case, 
I had raised the same issue in the ES forum - https://discuss.elastic.co/t/es-5x-jsongenerationexception-in-slow-logs/108510/2

**Elasticsearch version** (`bin/elasticsearch --version`):
ES version 5.4.1
Nest 2.3.3

**JVM version** (`java -version`):
Java 1.8 or above

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
Change setting to enable search slow logs
PUT _all/_settings
{
"index.search.slowlog.threshold.query.warn": "1ms",
"index.search.slowlog.threshold.query.info": "1ms",
"index.search.slowlog.threshold.fetch.warn": "1ms",
"index.search.slowlog.threshold.fetch.info": "1ms"
}

Fire the query in the given link from kibana->dev tools
https://gist.github.com/DivyaMalini/489f158a01a988ff7e725832fb03beb4

Logs -
[2017-11-20T11:35:32,917][WARN ][index.search.slowlog.query] [es-d11-rm] [sharedindex][10] took[12.5s], took_millis[12544], types[documentcontract], stats[], search_type[QUERY_THEN_FETCH], total_shards[6], source[{ "error" : "JsonGenerationException[Can not start an object, expecting field name (context: Object)]"}],
[2017-11-20T11:35:42,521][WARN ][index.search.slowlog.query] [es-d11-rm] [sharedindex][3] took[22.1s], took_millis[22158], types[documentcontract], stats[], search_type[QUERY_THEN_FETCH], total_shards[6], source[{ "error" : "JsonGenerationException[Can not start an object, expecting field name (context: Object)]"}],
[2017-11-20T11:47:26,846][INFO ][index.search.slowlog.query] [es-d11-rm] [sharedindex][3] took[6.3s], took_millis[6330], types[documentcontract], stats[], search_type[QUERY_THEN_FETCH], total_shards[6], source[{ "error" : "JsonGenerationException[Can not start an object, expecting field name (context: Object)]"}],
[2017-11-20T11:48:27,842][INFO ][index.search.slowlog.query] [es-d11-rm] [sharedindex][3] took[6.9s], took_millis[6932], types[documentcontract], stats[], search_type[QUERY_THEN_FETCH], total_shards[6], source[{ "error" : "JsonGenerationException[Can not start an object, expecting field name (context: Object)]"}],
[2017-11-20T11:48:45,656][INFO ][index.search.slowlog.query] [es-d11-rm] [sharedindex][6] took[9.1s], took_millis[9168], types[documentcontract], stats[], search_type[QUERY_THEN_FETCH], total_shards[6], source[{ "error" : "JsonGenerationException[Can not start an object, expecting field name (context: Object)]"}],
[2017-11-20T11:48:57,620][WARN ][index.search.slowlog.query] [es-d11-rm] [sharedindex][9] took[21.1s], took_millis[21121], types[documentcontract], stats[], search_type[QUERY_THEN_FETCH], total_shards[6], source[{ "error" : "JsonGenerationException[Can not start an object, expecting field name (context: Object)]"}],
[2017-11-20T11:49:08,569][WARN ][index.search.slowlog.query] [es-d11-rm] [sharedindex][2] took[32s], took_millis[32080], types[documentcontract], stats[], search_type[QUERY_THEN_FETCH], total_shards[6], source[{ "error" : "JsonGenerationException[Can not start an object, expecting field name (context: Object)]"}],
[2017-11-20T11:50:59,729][INFO ][index.search.slowlog.query] [es-d11-rm] [sharedindex][3] took[6.8s], took_millis[6898], types[documentcontract], stats[], search_type[QUERY_THEN_FETCH], total_shards[6], source[{ "error" : "JsonGenerationException[Can not start an object, expecting field name (context: Object)]"}],
[2017-11-20T11:56:02,530][WARN ][index.search.slowlog.query] [es-d11-rm] [sharedindex][9] took[10.1s], took_millis[10146], types[documentcontract], stats[], search_type[QUERY_THEN_FETCH], total_shards[6], source[{ "error" : "JsonGenerationException[Can not start an object, expecting field name (context: Object)]"}],
[2017-11-20T11:56:05,265][WARN ][index.search.slowlog.query] [es-d11-rm] [sharedindex][2] took[12.8s], took_millis[12872], types[documentcontract], stats[], search_type[QUERY_THEN_FETCH], total_shards[6], source[{ "error" : "JsonGenerationException[Can not start an object, expecting field name (context: Object)]"}],
[2017-11-20T11:56:17,629][WARN ][index.search.slowlog.query] [es-d11-rm] [sharedindex][3] took[25.2s], took_millis[25239], types[documentcontract], stats[], search_type[QUERY_THEN_FETCH], total_shards[6], source[{ "error" : "JsonGenerationException[Can not start an object, expecting field name (context: Object)]"}],
[2017-11-20T11:56:17,629][WARN ][index.search.slowlog.query] [es-d11-rm] [sharedindex][3] took[10.7s], took_millis[10724], types[documentcontract], stats[], search_type[QUERY_THEN_FETCH], total_shards[6], source[{ "error" : "JsonGenerationException[Can not start an object, expecting field name (context: Object)]"}],
[2017-11-20T11:56:25,755][INFO ][index.search.slowlog.query] [es-d11-rm] [sharedindex][10] took[5.3s], took_millis[5360], types[documentcontract], stats[], search_type[QUERY_THEN_FETCH], total_shards[6], source[{ "error" : "JsonGenerationException[Can not start an object, expecting field name (context: Object)]"}],
[2017-11-20T12:08:41,808][WARN ][index.search.slowlog.query] [es-d11-rm] [sharedindex][2] took[16.2s], took_millis[16216], types[documentcontract], stats[], search_type[QUERY_THEN_FETCH], total_shards[6], source[{ "error" : "JsonGenerationException[Can not start an object, expecting field name (context: Object)]"}],
[2017-11-20T12:08:47,168][WARN ][index.search.slowlog.query] [es-d11-rm] [sharedindex][9] took[21.5s], took_millis[21578], types[documentcontract], stats[], search_type[QUERY_THEN_FETCH], total_shards[6], source[{ "error" : "JsonGenerationException[Can not start an object, expecting field name (context: Object)]"}],
[2017-11-20T12:08:58,130][INFO ][index.search.slowlog.query] [es-d11-rm] [sharedindex][3] took[5.3s], took_millis[5330], types[documentcontract], stats[], search_type[QUERY_THEN_FETCH], total_shards[6], source[{ "error" : "JsonGenerationException[Can not start an object, expecting field name (context: Object)]"}]

**Comment by colings86** [comment] 2017-12-11 11:12
I've tested this on  master, 6.0.1, 5.6.5 and 5.4.1 and cannot reproduce this bug. In my tests the query is printed in full as expected. If you are still able to reproduce this bug could you remove parts of your search request until you can determine which part of the search request are causing the issue? Also please can you try to reproduce this on a clean installation of Elasticsearch and potentially also with fake documents to index that you can share to help in the reproduction?

**Comment by colings86** [comment] 2018-01-11 11:35
No further feedback so closing. If you have the requested information please add a comment and we can reopen the issue

**Closed by colings86** 2018-01-11 11:35 UTC
Labels: :Search, feedback_needed

**Comment by DivyaMalini** [comment] 2018-03-31 02:04
Could you please tell what is the JsonSerializerSetting.MaxDepth value is ? If its the default(NULL), then there shouldn't have been a max val at which this exception would have occurred.
