### ISSUE TITLE
ES 6.0 cancel running task command not stopping task

### ISSUE THREAD

**Issue by ulvinasirli99** [elastic/elasticsearch#74605] opened 2021-06-28 08:30 UTC
Elasticsearch version (bin/elasticsearch --version): 6.0

Plugins installed: []

JVM version (java -version):

OS version (uname -a if on a Unix-like system):

Description of the problem including expected versus actual behavior:

Steps to reproduce:

To get the running task in ES 6.0
run the command:
GET _tasks?actions=*search (this will fetch those tasks which are related with search

from the response get the node_id:task_id

Now run the ES 6.0 cancel command:
POST _tasks/node_id:task_id/_cancel

**Comment by fcofdez** [comment] 2021-06-28 09:31
I'm closing this as a duplicate of #74461

**Closed by fcofdez** 2021-06-28 09:31 UTC
Labels: >bug, needs:triage
