### ISSUE TITLE
Cancelling relocations with /_cluster/reroute API does not work

### ISSUE THREAD

**Issue by joedj** [elastic/elasticsearch#29517] opened 2018-04-14 04:12 UTC
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 6.2.3, Build: c59ff00/2018-03-13T10:06:29.741383Z, JVM: 1.8.0_161

**Plugins installed**:
discovery-ec2  ingest-geoip  ingest-user-agent  repository-s3  x-pack

**JVM version** (`java -version`):
openjdk version "1.8.0_161"
OpenJDK Runtime Environment (build 1.8.0_161-b14)
OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux 368248a25fe8 4.9.85-38.58.amzn1.x86_64 #1 SMP Wed Mar 14 01:17:26 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

Expected behaviour:
https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-reroute.html mentions "(or recovery)" in the `cancel` section, implying that it is possible to cancel an ongoing shard recovery (i.e. rebalance).

Invoking the `cancel` command with `"node" : "target_node"` should cancel the recovery.

Actual behaviour:
Invoking the `cancel` command with `"node" : "target_node"` does nothing.
Invoking the `cancel` command with `"node" : "source_node"` cancels the allocation on the source node, and the shard is reinitialized.

**Steps to reproduce**:

1. Allocate a shard to a different node.
2. Find relevant information:
```bash
curl localhost:9200/_cat/shards | grep RELOCATING
myindex                  2  r RELOCATING 57683083  63.2gb 10.9.37.161 ip-10-9-37-161-f69cced2c589 -> 10.9.37.163 yJhK1sq_R-eLQIlMV52MvA ip-10-9-37-163-3d269cd16c52
```
3. Attempt to cancel relocation
```bash
curl -s -XPOST -H'Content-Type: application/json' http://localhost:9200/_cluster/reroute --data-binary @- << "END"
{
    "commands" : [
        {
            "cancel" : {
                "index" : "myindex",
                "shard" : 2,
                "node": "yJhK1sq_R-eLQIlMV52MvA"
            }
        }
    ]
}
END
```
4. Observe that the relocation is not cancelled.

**Comment by DaveCTurner** [comment] 2018-04-15 21:17
Hi @joedj,

I can't reproduce what you describe. I created a three-node cluster containing a sizeable index, started a relocation of the replica and then attempted to cancel it (i.e. cancelled the allocation at the target node) and the relocation was indeed cancelled. A transcript is below. Could you identify the difference between what I've done here and the effect you describe?

```

# ========================================
# Request: 
GET /_cat/nodes
# at 2018-04-15T21:11:26.843Z

# ----------------------------------------
# Response: 
# 200 OK
# 127.0.0.1 44 99 9 2.48   mdi * XutRwHX
# 127.0.0.1 43 99 9 2.48   mdi - cVv2Fyq
# 127.0.0.1 29 99 9 2.48   mdi - z8FCp49
# 
# at 2018-04-15T21:11:26.858Z
# (0.014285s elapsed)

# ========================================
# Request: 
GET /_cat/shards
# at 2018-04-15T21:11:26.858Z

# ----------------------------------------
# Response: 
# 200 OK
# i 0 r STARTED 107780 717.7mb 127.0.0.1 z8FCp49
# i 0 p STARTED 107780 717.7mb 127.0.0.1 cVv2Fyq
# 
# at 2018-04-15T21:11:26.862Z
# (0.004141s elapsed)

# ========================================
# Request: 
POST /_cluster/reroute
{
  "commands": [
    {
      "move": {
        "shard": 0,
        "to_node": "XutRwHX",
        "from_node": "z8FCp49",
        "index": "i"
      }
    }
  ]
}
# at 2018-04-15T21:11:26.863Z

# ----------------------------------------
# Response: 
# 200 OK
# {
#   "state": {
#     "blocks": {},
#     "state_uuid": "LROkpu8YSmmiLwBhY6SRYA",
#     "routing_nodes": {
#       "unassigned": [],
#       "nodes": {
#         "z8FCp49KQUCiIjZeD3qY_Q": [
#           {
#             "shard": 0,
#             "state": "RELOCATING",
#             "node": "z8FCp49KQUCiIjZeD3qY_Q",
#             "expected_shard_size_in_bytes": 752641394,
#             "primary": false,
#             "allocation_id": {
#               "relocation_id": "1YzjJARWTcC94Db6e6oxCw",
#               "id": "ZlzCZBqYSiSxuYCIieu-hA"
#             },
#             "relocating_node": "XutRwHXVTvygFnkoS9t9bg",
#             "index": "i"
#           }
#         ],
#         "XutRwHXVTvygFnkoS9t9bg": [
#           {
#             "shard": 0,
#             "state": "INITIALIZING",
#             "node": "XutRwHXVTvygFnkoS9t9bg",
#             "expected_shard_size_in_bytes": 752641394,
#             "primary": false,
#             "allocation_id": {
#               "relocation_id": "ZlzCZBqYSiSxuYCIieu-hA",
#               "id": "1YzjJARWTcC94Db6e6oxCw"
#             },
#             "relocating_node": "z8FCp49KQUCiIjZeD3qY_Q",
#             "index": "i",
#             "recovery_source": {
#               "type": "PEER"
#             }
#           }
#         ],
#         "cVv2FyqAS7OLoxKIyW8CFA": [
#           {
#             "shard": 0,
#             "state": "STARTED",
#             "node": "cVv2FyqAS7OLoxKIyW8CFA",
#             "primary": true,
#             "allocation_id": {
#               "id": "JE7bI4M-T6WaDOJNEcIm6A"
#             },
#             "relocating_node": null,
#             "index": "i"
#           }
#         ]
#       }
#     },
#     "restore": {
#       "snapshots": []
#     },
#     "master_node": "XutRwHXVTvygFnkoS9t9bg",
#     "snapshot_deletions": {
#       "snapshot_deletions": []
#     },
#     "snapshots": {
#       "snapshots": []
#     },
#     "version": 14,
#     "routing_table": {
#       "indices": {
#         "i": {
#           "shards": {
#             "0": [
#               {
#                 "shard": 0,
#                 "state": "RELOCATING",
#                 "node": "z8FCp49KQUCiIjZeD3qY_Q",
#                 "expected_shard_size_in_bytes": 752641394,
#                 "primary": false,
#                 "allocation_id": {
#                   "relocation_id": "1YzjJARWTcC94Db6e6oxCw",
#                   "id": "ZlzCZBqYSiSxuYCIieu-hA"
#                 },
#                 "relocating_node": "XutRwHXVTvygFnkoS9t9bg",
#                 "index": "i"
#               },
#               {
#                 "shard": 0,
#                 "state": "STARTED",
#                 "node": "cVv2FyqAS7OLoxKIyW8CFA",
#                 "primary": true,
#                 "allocation_id": {
#                   "id": "JE7bI4M-T6WaDOJNEcIm6A"
#                 },
#                 "relocating_node": null,
#                 "index": "i"
#               }
#             ]
#           }
#         }
#       }
#     },
#     "nodes": {
#       "z8FCp49KQUCiIjZeD3qY_Q": {
#         "transport_address": "127.0.0.1:9302",
#         "name": "z8FCp49",
#         "attributes": {},
#         "ephemeral_id": "-TjZLoWkQEGFArqbD_9qZA"
#       },
#       "XutRwHXVTvygFnkoS9t9bg": {
#         "transport_address": "127.0.0.1:9300",
#         "name": "XutRwHX",
#         "attributes": {},
#         "ephemeral_id": "JITh5jCnTw6-UcfB2dy_zw"
#       },
#       "cVv2FyqAS7OLoxKIyW8CFA": {
#         "transport_address": "127.0.0.1:9301",
#         "name": "cVv2Fyq",
#         "attributes": {},
#         "ephemeral_id": "GCanxYKmQHeyt9K2W3efvA"
#       }
#     }
#   },
#   "acknowledged": true
# }
# at 2018-04-15T21:11:26.921Z
# (0.058129s elapsed)

# ========================================
# Request: 
GET /_cat/shards
# at 2018-04-15T21:11:26.924Z

# ----------------------------------------
# Response: 
# 200 OK
# i 0 r RELOCATING 107780 717.7mb 127.0.0.1 z8FCp49 -> 127.0.0.1 XutRwHXVTvygFnkoS9t9bg XutRwHX
# i 0 p STARTED    107780 717.7mb 127.0.0.1 cVv2Fyq
# 
# at 2018-04-15T21:11:26.931Z
# (0.007914s elapsed)

# ========================================
# Request: 
POST /_cluster/reroute
{
  "commands": [
    {
      "cancel": {
        "shard": 0,
        "node": "XutRwHX",
        "index": "i"
      }
    }
  ]
}
# at 2018-04-15T21:11:33.760Z

# ----------------------------------------
# Response: 
# 200 OK
# {
#   "state": {
#     "blocks": {},
#     "state_uuid": "vzSMv5bVR3SArwSLoOqufw",
#     "routing_nodes": {
#       "unassigned": [],
#       "nodes": {
#         "z8FCp49KQUCiIjZeD3qY_Q": [
#           {
#             "shard": 0,
#             "state": "STARTED",
#             "node": "z8FCp49KQUCiIjZeD3qY_Q",
#             "primary": false,
#             "allocation_id": {
#               "id": "ZlzCZBqYSiSxuYCIieu-hA"
#             },
#             "relocating_node": null,
#             "index": "i"
#           }
#         ],
#         "XutRwHXVTvygFnkoS9t9bg": [],
#         "cVv2FyqAS7OLoxKIyW8CFA": [
#           {
#             "shard": 0,
#             "state": "STARTED",
#             "node": "cVv2FyqAS7OLoxKIyW8CFA",
#             "primary": true,
#             "allocation_id": {
#               "id": "JE7bI4M-T6WaDOJNEcIm6A"
#             },
#             "relocating_node": null,
#             "index": "i"
#           }
#         ]
#       }
#     },
#     "restore": {
#       "snapshots": []
#     },
#     "master_node": "XutRwHXVTvygFnkoS9t9bg",
#     "snapshot_deletions": {
#       "snapshot_deletions": []
#     },
#     "snapshots": {
#       "snapshots": []
#     },
#     "version": 15,
#     "routing_table": {
#       "indices": {
#         "i": {
#           "shards": {
#             "0": [
#               {
#                 "shard": 0,
#                 "state": "STARTED",
#                 "node": "z8FCp49KQUCiIjZeD3qY_Q",
#                 "primary": false,
#                 "allocation_id": {
#                   "id": "ZlzCZBqYSiSxuYCIieu-hA"
#                 },
#                 "relocating_node": null,
#                 "index": "i"
#               },
#               {
#                 "shard": 0,
#                 "state": "STARTED",
#                 "node": "cVv2FyqAS7OLoxKIyW8CFA",
#                 "primary": true,
#                 "allocation_id": {
#                   "id": "JE7bI4M-T6WaDOJNEcIm6A"
#                 },
#                 "relocating_node": null,
#                 "index": "i"
#               }
#             ]
#           }
#         }
#       }
#     },
#     "nodes": {
#       "z8FCp49KQUCiIjZeD3qY_Q": {
#         "transport_address": "127.0.0.1:9302",
#         "name": "z8FCp49",
#         "attributes": {},
#         "ephemeral_id": "-TjZLoWkQEGFArqbD_9qZA"
#       },
#       "XutRwHXVTvygFnkoS9t9bg": {
#         "transport_address": "127.0.0.1:9300",
#         "name": "XutRwHX",
#         "attributes": {},
#         "ephemeral_id": "JITh5jCnTw6-UcfB2dy_zw"
#       },
#       "cVv2FyqAS7OLoxKIyW8CFA": {
#         "transport_address": "127.0.0.1:9301",
#         "name": "cVv2Fyq",
#         "attributes": {},
#         "ephemeral_id": "GCanxYKmQHeyt9K2W3efvA"
#       }
#     }
#   },
#   "acknowledged": true
# }
# at 2018-04-15T21:11:33.836Z
# (0.075239s elapsed)

# ========================================
# Request: 
GET /_cat/shards
# at 2018-04-15T21:11:33.839Z

# ----------------------------------------
# Response: 
# 200 OK
# i 0 r STARTED 107780 717.7mb 127.0.0.1 z8FCp49
# i 0 p STARTED 107780 717.7mb 127.0.0.1 cVv2Fyq
# 
# at 2018-04-15T21:11:33.848Z
# (0.009147s elapsed)

```

**Comment by ywelsch** [comment] 2018-04-16 08:48
@joedj is rebalancing/allocation disabled when you run that command? If not, the cluster will rebalance the shard in the same cluster update, i.e, cancel the relocation, notice that the cluster is unbalanced, and relocate the shard again to the same node (so it might appear as if nothing happened).

**Comment by DaveCTurner** [comment] 2018-04-30 08:24
Closing due to lack of a response. If you can help us reproduce this then please comment and we'll re-open it.

**Closed by DaveCTurner** 2018-04-30 08:24 UTC
Labels: :Distributed/Allocation, feedback_needed

**Comment by kvadaliyasalesforce** [comment] 2023-11-02 06:30
cancel rebalance is also not working for me

**Comment by simps7b2** [comment] 2024-08-17 00:23
I think I was having the issue of the cluster auto-rebalancing after I tried to cancel a relocation operation. What I did was include an alternative move operation into my reroute command and this achieved what I needed (moving a larger shard instead of a smaller one for better disk balance) without having to disable rebalancing.
