### ISSUE TITLE
Documentation doesn't explain overall structure or composition of document components (queries, filters, etc.)

### ISSUE THREAD

**Issue by bitemyapp** [elastic/elasticsearch#8374] opened 2014-11-06 23:43 UTC
https://twitter.com/mausch/status/530504035540160513

https://twitter.com/LeviNotik/status/530505312777023488

https://twitter.com/mwotton/status/442775637648891904

https://twitter.com/melvinmt/status/530474427306479616

https://twitter.com/kosmikko/status/502340971527671808

https://twitter.com/kenperkins/status/494173990152175617 (navigation, I've had this problem and I'm a relatively experienced user of the site and ES itself)

https://twitter.com/icyliquid/status/477500839020752896

https://twitter.com/werg/status/466733972324880384 (another suggestion to bypass official ES documentation)

I wrote https://github.com/bitemyapp/bloodhound partly because I was having a hell of a time generating valid Elasticsearch requests without lots of copy-paste and templating.

The docs have not been improved much in the last couple years other than when you did the big site change.

It's extremely hard for a new user of Elasticsearch to get a bird's eye view.

I brought up Bloodhound when I first released it as a way to possibly start a proper spec of what Elasticsearch accepts as a valid request and what it does not. I'd like to revive the idea of having a spec so that users and client implementors don't have to keep rediscovering how Elasticsearch works through haphazard experimentation.

Back when I was implementing Bloodhound I asked if there was a spec. I was told there wasn't one. I was briefly hopeful when I saw there was a Thrift spec...but it passes off the actual document structure as a JSON blob, lending no useful information.

Please at least consider having a spec for the API.

**Comment by clintongormley** [comment] 2015-06-04 19:41
Closing as a duplicate of https://github.com/elastic/elasticsearch/issues/8965

**Closed by clintongormley** 2015-06-04 19:41 UTC
Labels: doc
