### ISSUE TITLE
Date Range Query Illegal Argument Exception

### ISSUE THREAD

**Issue by cashel1** [elastic/elasticsearch#18479] opened 2016-05-19 23:53 UTC
Elasticsearch version 5.0 Alpha-2

JVM version 1.8.0_91

OS version Windows 7

**Description of the problem including expected versus actual behavior**:
Lucene throws the following error when running the Date Range query below. Files to reproduce are attached.

IllegalArgumentException[field="inceptionDate" is unrecognized];
Caused by: java.lang.IllegalArgumentException: field="inceptionDate" is unrecognized
at org.apache.lucene.codecs.lucene60.Lucene60PointsReader.getBKDReader(Lucene60PointsReader.java:120).  
1. Schema included in mapping.txt file
2. ES dump included in dump.txt
3. stack trace in log.txt
   {
   "query" : {
     "range" : {
   [log.txt](https://github.com/elastic/elasticsearch/files/273652/log.txt)
   [mapping.txt](https://github.com/elastic/elasticsearch/files/273651/mapping.txt)
   [dump.txt](https://github.com/elastic/elasticsearch/files/273653/dump.txt)
   
     "inceptionDate" : {
       "from" : "10/1/1980",
       "to" : "12/31/2015",
       "include_lower" : true,
       "include_upper" : true,
       "boost" : 1.0
     }
   }
   },
   "fields" : [ "orgType", "inceptionDate", "name", "id", "qualityRating", "version", "parentId", "descp" ]
   }
   **Provide logs (if relevant)**:

**Describe the feature**:

**Comment by clintongormley** [comment] 2016-05-20 08:54
I'm unable to replicate this with the following:

    PUT security1
    {
      "mappings": {
        "Org": {
          "dynamic": "false",
          "properties": {
            "certOrgId": {
              "type": "text"
            },
            "descp": {
              "type": "text"
            },
            "effectiveFrom": {
              "type": "date"
            },
            "effectiveThru": {
              "type": "date"
            },
            "externalId": {
              "type": "text"
            },
            "id": {
              "type": "text"
            },
            "inceptionDate": {
              "type": "date"
            },
            "indexDate": {
              "type": "date"
            },
            "latLon": {
              "type": "geo_point"
            },
            "name": {
              "type": "text"
            },
            "networkId": {
              "type": "text"
            },
            "orgType": {
              "type": "text"
            },
            "parentId": {
              "type": "text"
            },
            "qualityRating": {
              "type": "integer"
            },
            "routeId": {
              "type": "text"
            },
            "searchRoutes": {
              "type": "text"
            },
            "type": {
              "type": "text"
            },
            "version": {
              "type": "long"
            }
          }
        }
      }
    }
    
    PUT security1/Org/_bulk
    {"index":{"_id":"a"}}
    {"name":"Acme","parentId":null,"externalId":null,"networkId":"NC Public Cloud","inceptionDate":1422684000000,"certOrgId":null,"orgType":"Parent","geoHash":"9rv25grh5tgu","routeId":"R2","searchRoutes":"R2,R3,R4,R5","descp":"Acme Health System","qualityRating":4,"id":"a","type":null,"version":0,"indexDate":1463695280759,"effectiveFrom":1463695280759,"effectiveThru":1463695280759}
    {"index":{"_id":"ae"}}
    {"name":"Acme East","parentId":"a","externalId":null,"networkId":"NC Public Cloud","inceptionDate":1422684000000,"certOrgId":null,"orgType":"Region","geoHash":"dr782k465uvc","routeId":"R2","searchRoutes":"R4,R5","descp":"Acme Eastern Region","qualityRating":3,"id":"ae","type":null,"version":0,"indexDate":1463695280847,"effectiveFrom":1463695280847,"effectiveThru":1463695280847}
    {"index":{"_id":"aw"}}
    {"name":"Acme West","parentId":"a","externalId":null,"networkId":"NC Public Cloud","inceptionDate":1425103200000,"certOrgId":null,"orgType":"Region","geoHash":"9rv25grh5tgu","routeId":"R2","searchRoutes":"R2,R3","descp":"Acme Western Region","qualityRating":4,"id":"aw","type":null,"version":0,"indexDate":1463695280904,"effectiveFrom":1463695280904,"effectiveThru":1463695280904}
    {"index":{"_id":"aae"}}
    {"name":"Acme Acute East","parentId":"ae","externalId":null,"networkId":"NC Public Cloud","inceptionDate":1425103200000,"certOrgId":null,"orgType":"Division","geoHash":"dr782k465uvc","routeId":"R2","searchRoutes":"R4","descp":"Acme Acute - Eastern Region","qualityRating":3,"id":"aae","type":null,"version":0,"indexDate":1463695280962,"effectiveFrom":1463695280962,"effectiveThru":1463695280962}
    {"index":{"_id":"abe"}}
    {"name":"Acme Behav East","parentId":"ae","externalId":null,"networkId":"NC Public Cloud","inceptionDate":1427778000000,"certOrgId":null,"orgType":"Division","geoHash":"dr782k465uvc","routeId":"R2","searchRoutes":"R5","descp":"Acme Behavioral - Eastern Region","qualityRating":3,"id":"abe","type":null,"version":0,"indexDate":1463695281111,"effectiveFrom":1463695281111,"effectiveThru":1463695281111}
    {"index":{"_id":"aaw"}}
    {"name":"Acme Acute West","parentId":"aw","externalId":null,"networkId":"NC Public Cloud","inceptionDate":1427778000000,"certOrgId":null,"orgType":"Division","geoHash":"9rv25grh5tgu","routeId":"R2","searchRoutes":"R2","descp":"Acme Acute - Western Region","qualityRating":5,"id":"aaw","type":null,"version":0,"indexDate":1463695281242,"effectiveFrom":1463695281242,"effectiveThru":1463695281242}
    {"index":{"_id":"abw"}}
    {"name":"Acme Behav West","parentId":"aw","externalId":null,"networkId":"NC Public Cloud","inceptionDate":1427778000000,"certOrgId":null,"orgType":"Division","geoHash":"9rv25grh5tgu","routeId":"R2","searchRoutes":"R3","descp":"Acme Behavioral - Western Region","qualityRating":4,"id":"abw","type":null,"version":0,"indexDate":1463695281308,"effectiveFrom":1463695281308,"effectiveThru":1463695281308}
    {"index":{"_id":"boi"}}
    {"name":"Boise","parentId":"aaw","externalId":null,"networkId":"NC Public Cloud","inceptionDate":1427778000000,"certOrgId":null,"orgType":"Hospital","geoHash":"9rv25grh5tgu","routeId":"R3","searchRoutes":"","descp":"Boise Acute Care","qualityRating":4,"id":"boi","type":null,"version":0,"indexDate":1463695281366,"effectiveFrom":1463695281366,"effectiveThru":1463695281366}
    {"index":{"_id":"por"}}
    {"name":"Portland","parentId":"abw","externalId":null,"networkId":"NC Public Cloud","inceptionDate":1430370000000,"certOrgId":null,"orgType":"Hospital","geoHash":"c20dyhxgpq5w","routeId":"R4","searchRoutes":"","descp":"Portlandia Behavioral System","qualityRating":2,"id":"por","type":null,"version":0,"indexDate":1463695281424,"effectiveFrom":1463695281424,"effectiveThru":1463695281424}
    {"index":{"_id":"ny"}}
    {"name":"NewYork","parentId":"aae","externalId":null,"networkId":"NC Public Cloud","inceptionDate":1430370000000,"certOrgId":null,"orgType":"Hospital","geoHash":"dr782k465uvc","routeId":"R5","searchRoutes":"","descp":"New York Community Care","qualityRating":3,"id":"ny","type":null,"version":0,"indexDate":1463695281481,"effectiveFrom":1463695281481,"effectiveThru":1463695281481}
    
    GET security1/_search
    {
      "query": {
        "range": {
          "inceptionDate": {
            "from": "1980-10-01",
            "to": "2015-12-31",
            "include_lower": true,
            "include_upper": true,
            "boost": 1
          }
        }
      }
    }

That said, i think this is a duplicate of https://github.com/elastic/elasticsearch/issues/18010 which has been fixed in master

**Comment by clintongormley** [comment] 2016-05-20 08:55
Any chance you can build from master to check? Or send me a recreation that fails on alpha2?

**Comment by cashel1** [comment] 2016-05-20 17:44
Can't get it to fail.  I'll try the master approach.  Thanks

**Comment by jpountz** [comment] 2016-05-23 11:57
@clintongormley Probably a duplicate of #18010 indeed.

**Comment by cbuescher** [comment] 2017-03-31 13:12
@jpountz Given that this isn't reproducible any more and #18010 was likely the cause, should we close this?

**Closed** 2017-03-31 13:22 UTC
Labels: :Mapping, bug, feedback_needed, Pioneer Program
