### ISSUE TITLE
[CI] DeprecationHttpIT is broken

### ISSUE THREAD

**Issue by thecoop** [elastic/elasticsearch#101596] opened 2023-10-31 11:10 UTC
Despite the changes in #101273, DeprecationHttpIT is still very leaky between tests (#101500, #101263). This needs a proper investigation

**Comment by thecoop** [comment] 2024-01-16 16:54
I had another look at this - it does not fail locally, even when run hundreds of times. There's no source of leakage that I can see. At the moment, the only thing to try that I can think of is to put a big sleep before each test to guarantee they are run in isolation - but at that point are we actually surfacing a genuine ES bug around syncing index CRUD operations in a cluster & responding to clients?

**Comment by DaveCTurner** [comment] 2024-01-16 17:37
Could it be explained by the following sequence? At the end of a test we're deleting the deprecation log index:

https://github.com/elastic/elasticsearch/blob/f3b697f6a55c4cc70375a334183e516ddb5f219c/x-pack/plugin/deprecation/qa/rest/src/javaRestTest/java/org/elasticsearch/xpack/deprecation/DeprecationHttpIT.java#L99

Then we remove the deprecated setting, which queues up another deprecation warning but may not index it straight away:

https://github.com/elastic/elasticsearch/blob/51caf171bc2cf7bedeefdb7fcc8c2e400d4662e3/test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java#L1209

Then in the setup for the next test we check that the deprecation log index is still absent:

https://github.com/elastic/elasticsearch/blob/f3b697f6a55c4cc70375a334183e516ddb5f219c/x-pack/plugin/deprecation/qa/rest/src/javaRestTest/java/org/elasticsearch/xpack/deprecation/DeprecationHttpIT.java#L80-L86

And then the enqueued deprecation warning gets flushed to the index, just before we run the test that asserts the contents of the index.

If so, I think it should work to remove the deprecated setting within the test rather than leaving it in place for `wipeCluster()` to clean up.

**Comment by DaveCTurner** [comment] 2024-01-16 17:38
> If so, I think it should work to remove the deprecated setting within the test rather than leaving it in place for wipeCluster() to clean up.

Hmm actually not sure that's true, we'd need to be sure that it wasn't sitting in the `BulkProcessor` queue too.

**Comment by thecoop** [comment] 2024-01-17 13:51
The only test that we're actually setting deprecated settings - `testDeprecatedSettingsReturnWarnings` - calls `cleanupSettings` at the end of the test method. Its possible that reset is triggering another deprecation warning that is racing with clearing the index.

So then a fix might be to wait until the warnings from the reset are added to the log, and only then do we end the test and let the next one run.

**Comment by pgomulka** [comment] 2024-01-18 10:47
good find! I think this is what is happening. I checked previous build scans and they were failing on `test.setting.deprecated.true2` being present in deprecation datastream. That is the deprecated setting that is 'cleaned'/nulled in the cleanup of `testDeprecatedSettingsReturnWarnings`. I will raise a PR to try to fix it

**Comment by pgomulka** [comment] 2024-01-18 11:07
turns out the cleanup should not be able to generate more deprecations.
it uses the same settings which previously generated a deprecation. Meaning it will be throttled (in a ratelimitingfilter) and would not generate new deprecations

**Comment by DaveCTurner** [comment] 2024-01-18 11:16
Somehow we're seeing the document being indexed, then the index is deleted, then the index is created again and the same document is indexed. Can we confirm that the `RateLimitingFilter` is really doing what we think it's doing?

Another possibility I can think of is that we're observing the document in `DeprecationTestUtils#getIndexedDeprecations`, and then deleting the index, before the indexing operation actually finishes, which causes the `BulkProcessor` to see a failure on which it retries.

**Comment by pgomulka** [comment] 2024-01-18 11:45
> Can we confirm that the RateLimitingFilter is really doing what we think it's doing?

yes. this is what I confirmed in https://github.com/elastic/elasticsearch/pull/104514#discussion_r1457284962

> Another possibility I can think of is that we're observing the document in DeprecationTestUtils#getIndexedDeprecations, and then deleting the index, before the indexing operation actually finishes, which causes the BulkProcessor to see a failure on which it retries.

is there a way we could add a trace log for this? or prove it in some other way?

**Comment by mosche** [comment] 2024-04-17 12:59
Rather than trying extremely hard to pretend isolation on a shared resource (the deprecation index), this PR instead attempts to provide isolation by strictly using a unique xOpaqueId per test case.
Additionally it sets the flush interval of the deprecation bulk processor to achieve reasonably fast test runs.

https://github.com/elastic/elasticsearch/pull/107563

**Comment by mosche** [comment] 2024-05-10 08:28
I briefly peeked into a recent failure ([buildscan](https://gradle-enterprise.elastic.co/s/2vhy6yngkhrq4)), the test timed out waiting 30secs for the deprecation to appear in logs.
To me doesn't look like a test failure, but I'd have to look further into it.

The test logs:
```
[2024-05-07T10:01:00,440][INFO ][o.e.x.d.DeprecationHttpIT] [testDeprecatedSettingsReturnWarnings] before test
мај 07, 2024 10:01:00 AM org.elasticsearch.client.RestClient logResponse
WARNING: request [PUT http://127.0.0.1:40969/_cluster/settings] returned 2 warnings: [299 Elasticsearch-8.15.0-b0fb722cc5d8f8e60ac49112f229811ce2cdf7cf "[test.setting.deprecated.true2] setting was deprecated in Elasticsearch and will be removed in a future release."],[299 Elasticsearch-8.15.0-b0fb722cc5d8f8e60ac49112f229811ce2cdf7cf "[test.setting.deprecated.true1] setting was deprecated in Elasticsearch and will be removed in a future release."]
[2024-05-07T10:01:00,963][WARN ][o.e.x.d.DeprecationHttpIT] [testDeprecatedSettingsReturnWarnings] []
[2024-05-07T10:01:00,989][WARN ][o.e.x.d.DeprecationHttpIT] [testDeprecatedSettingsReturnWarnings] []
[2024-05-07T10:01:01,031][WARN ][o.e.x.d.DeprecationHttpIT] [testDeprecatedSettingsReturnWarnings] []
[2024-05-07T10:01:01,087][WARN ][o.e.x.d.DeprecationHttpIT] [testDeprecatedSettingsReturnWarnings] []
[2024-05-07T10:01:01,122][WARN ][o.e.x.d.DeprecationHttpIT] [testDeprecatedSettingsReturnWarnings] []
[2024-05-07T10:01:01,192][WARN ][o.e.x.d.DeprecationHttpIT] [testDeprecatedSettingsReturnWarnings] []
[2024-05-07T10:01:01,265][WARN ][o.e.x.d.DeprecationHttpIT] [testDeprecatedSettingsReturnWarnings] []
[2024-05-07T10:01:01,370][WARN ][o.e.x.d.DeprecationHttpIT] [testDeprecatedSettingsReturnWarnings] []
[2024-05-07T10:01:01,535][WARN ][o.e.x.d.DeprecationHttpIT] [testDeprecatedSettingsReturnWarnings] []
[2024-05-07T10:01:01,830][WARN ][o.e.x.d.DeprecationHttpIT] [testDeprecatedSettingsReturnWarnings] []
[2024-05-07T10:01:02,379][WARN ][o.e.x.d.DeprecationHttpIT] [testDeprecatedSettingsReturnWarnings] []
[2024-05-07T10:01:03,451][WARN ][o.e.x.d.DeprecationHttpIT] [testDeprecatedSettingsReturnWarnings] []
[2024-05-07T10:01:05,544][WARN ][o.e.x.d.DeprecationHttpIT] [testDeprecatedSettingsReturnWarnings] []
[2024-05-07T10:01:09,674][WARN ][o.e.x.d.DeprecationHttpIT] [testDeprecatedSettingsReturnWarnings] []
[2024-05-07T10:01:17,906][WARN ][o.e.x.d.DeprecationHttpIT] [testDeprecatedSettingsReturnWarnings] []
[2024-05-07T10:01:34,318][WARN ][o.e.x.d.DeprecationHttpIT] [testDeprecatedSettingsReturnWarnings] []
мај 07, 2024 10:01:34 AM org.elasticsearch.client.RestClient logResponse
WARNING: request [PUT http://[::1]:41399/_cluster/settings] returned 2 warnings: [299 Elasticsearch-8.15.0-b0fb722cc5d8f8e60ac49112f229811ce2cdf7cf "[test.setting.deprecated.true2] setting was deprecated in Elasticsearch and will be removed in a future release."],[299 Elasticsearch-8.15.0-b0fb722cc5d8f8e60ac49112f229811ce2cdf7cf "[test.setting.deprecated.true1] setting was deprecated in Elasticsearch and will be removed in a future release."]
[2024-05-07T10:01:34,466][INFO ][o.e.x.d.DeprecationHttpIT] [testDeprecatedSettingsReturnWarnings] after test
REPRODUCE WITH: ./gradlew ':x-pack:plugin:deprecation:qa:rest:javaRestTest' --tests "org.elasticsearch.xpack.deprecation.DeprecationHttpIT.testDeprecatedSettingsReturnWarnings" -Dtests.seed=446C182627B25D32 -Dtests.locale=sr-ME -Dtests.timezone=US/Mountain -Druntime.java=21
```

However, looking at the deprecation log you'll see the following:
```
{"@timestamp":"2024-05-07T16:01:34.325Z", "log.level": "WARN",  "data_stream.dataset":"deprecation.elasticsearch","data_stream.namespace":"default","data_stream.type":"logs","elasticsearch.elastic_product_origin":"","elasticsearch.event.category":"settings","elasticsearch.http.request.x_opaque_id":"testDeprecatedSettingsReturnWarnings","event.code":"test.setting.deprecated.true2","message":"[test.setting.deprecated.true2] setting was deprecated in Elasticsearch and will be removed in a future release." , "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"deprecation.elasticsearch","process.thread.name":"elasticsearch[javaRestTest-0][masterService#updateTask][T#1]","log.logger":"org.elasticsearch.deprecation.common.settings.Settings","elasticsearch.cluster.uuid":"dDcqp0Y3Tte6TEqtUezFsw","elasticsearch.node.id":"3E_sV7YrQJW0ySfuirx-0g","elasticsearch.node.name":"javaRestTest-0","elasticsearch.cluster.name":"javaRestTest"}
{"@timestamp":"2024-05-07T16:01:34.326Z", "log.level": "WARN",  "data_stream.dataset":"deprecation.elasticsearch","data_stream.namespace":"default","data_stream.type":"logs","elasticsearch.elastic_product_origin":"","elasticsearch.event.category":"settings","elasticsearch.http.request.x_opaque_id":"testDeprecatedSettingsReturnWarnings","event.code":"test.setting.deprecated.true1","message":"[test.setting.deprecated.true1] setting was deprecated in Elasticsearch and will be removed in a future release." , "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"deprecation.elasticsearch","process.thread.name":"elasticsearch[javaRestTest-0][masterService#updateTask][T#1]","log.logger":"org.elasticsearch.deprecation.common.settings.Settings","elasticsearch.cluster.uuid":"dDcqp0Y3Tte6TEqtUezFsw","elasticsearch.node.id":"3E_sV7YrQJW0ySfuirx-0g","elasticsearch.node.name":"javaRestTest-0","elasticsearch.cluster.name":"javaRestTest"}
```

These logs correspond to the request in the finally block, when resetting/removing the deprecated settings again.
It appears as if the first request was neither logged nor indexed 🤷

**Comment by DaveCTurner** [comment] 2024-05-13 16:02
Another at https://gradle-enterprise.elastic.co/s/nlw52dnqiof4a/tests/task/:x-pack:plugin:deprecation:qa:rest:javaRestTest/details/org.elasticsearch.xpack.deprecation.DeprecationHttpIT/testDeprecatedSettingsReturnWarnings?top-execution=1

**Comment by mosche** [comment] 2024-05-14 15:36
Closing this, the above is a new failure tracked in https://github.com/elastic/elasticsearch/issues/108628

**Closed by mosche** 2024-05-14 15:36 UTC
Labels: >test-failure, :Core/Infra/Logging, Team:Core/Infra, low-risk
