### ISSUE TITLE
Elasticsearch listening on mutiple specific ips

### ISSUE THREAD

**Issue by siddharthasahu** [elastic/elasticsearch#13677] opened 2015-09-21 15:37 UTC
Hi,

Can elasticsearch be configured to listen on multiple IPs, but not on all?
So I want it to listen on all private ips + localhost, but not on the public ips all present on the same node.

Thanks

**Comment by nik9000** [comment] 2015-09-21 15:39
Duplicate of #13592.

**Closed by nik9000** 2015-09-21 15:39 UTC
