### ISSUE TITLE
[CI] XPackRestIT "analytics/top_metrics/sort by string script fails" failure

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#52409] opened 2020-02-17 12:42 UTC
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=oraclelinux-7&&immutable/574/console

```
02:31:08 org.elasticsearch.xpack.test.rest.XPackRestIT > test {p0=analytics/top_metrics/sort by string script fails} FAILED
02:31:08     java.lang.AssertionError: Failure at [analytics/top_metrics:247]: expected [400] status code but api [search] returned [200 OK] [{"took":8,"timed_out":false,"_shards":{"total":2,"successful":1,"skipped":0,"failed":1,"failures":[{"shard":0,"index":"test","node":"gtl65pvDSVSvSoO1viU9Lg","reason":{"type":"illegal_argument_exception","reason":"error building sort for [_script]: script sorting only supported on [numeric] scripts but was [string]"}}]},"hits":{"total":{"value":0,"relation":"eq"},"max_score":null,"hits":[]},"aggregations":{"tm":{"top":[]}}}]
02:31:08         at __randomizedtesting.SeedInfo.seed([6ECA51725C63A9D5:E69E6EA8F29FC42D]:0)
02:31:08         at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:405)
02:31:08         at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:382)
02:31:08         at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
```

Couldn't repro, though :-(.

**Comment by henningandersen** [comment] 2020-02-18 08:08
Another failure in master here:
https://gradle-enterprise.elastic.co/s/muy4t6spxrake

Looks like the index somehow got created with 2 shards.

**Comment by henningandersen** [comment] 2020-02-18 09:13
This master failure looks similar, but is for another test case: `p0=analytics/top_metrics/sort by keyword field fails`
https://gradle-enterprise.elastic.co/s/6expjc2t4e6rs/tests/fcijb24gqtmnc-q63yzuzm4b2wi
Looks like the index also got two shards in this case:
```
        "successful" : 1,
        "skipped" : 0,
        "failed" : 1,
```

**Comment by henningandersen** [comment] 2020-02-18 10:07
Notice that an index template "global" is randomly added, causing the indices to have two shards.

@nik9000 I noticed this is a new test, maybe you can take a look? `skip features: default_shards` might do the trick here?

**Comment by nik9000** [comment] 2020-02-20 20:13
Fixed in #52516.

**Comment by nik9000** [comment] 2020-02-21 21:57
I had my wires crossed. This wasn't fixed.

**Closed** 2020-02-24 18:02 UTC
Labels: :Analytics/Aggregations, >test-failure

**Comment by markharwood** [comment] 2020-02-25 14:05
I might just have hit this in a [PR build](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-2/16964/testReport/junit/org.elasticsearch.xpack.test.rest/XPackRestIT/test__p0_analytics_top_metrics_sort_by_string_script_fails_/) based off master abeb837b0618b2f71837207899c1d6b46f913fc8 which has the [number of shards fix](https://github.com/elastic/elasticsearch/commit/5d18655a6d1dae2e7a7e71c54da84740c6ab98c0). Didn't reproduce locally.

**Comment by nik9000** [comment] 2020-02-25 14:29
> I might just have hit this in a [PR build](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-2/16964/testReport/junit/org.elasticsearch.xpack.test.rest/XPackRestIT/test__p0_analytics_top_metrics_sort_by_string_script_fails_/) based off master [abeb837](https://github.com/elastic/elasticsearch/commit/abeb837b0618b2f71837207899c1d6b46f913fc8) which has the [number of shards fix](https://github.com/elastic/elasticsearch/commit/5d18655a6d1dae2e7a7e71c54da84740c6ab98c0). Didn't reproduce locally.

I'll push some even more paranoid clamping on the test to see if that fixes it....

**Comment by nik9000** [comment] 2020-02-25 15:45
More paranoia: 0a4c5e0f2b8cf8852dbf394d91072074f481e6d0
