### ISSUE TITLE
if an index cannot be created, its bogusly retried in a loop

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#13319] opened 2015-09-03 17:51 UTC
This sucks horribly when upgrading lucene, because people scatter asserts in the code to remind us to upgrade things, but then tests just silently hang.

If there is an exception e.g. coming from IndexShard, then why in the hell does it do this?

**Comment by nik9000** [comment] 2015-09-21 21:27
I theorize that the trouble was [an assert in IndexShard](https://github.com/elastic/elasticsearch/commit/f216d92d19cf2f12fbc460c7aef66f38998ef9fd#diff-3d9da880b4a90ac1e9545d4039d5c4e6L257) and I added the assert back. Then I ran a random test, `CommonTermsQueryParserTests`, and it took 30 seconds for it to fail. It timed out waiting for the cluster to go green.

@rmuir , is that what you were seeing?

**Comment by rmuir** [comment] 2015-09-21 21:38
yeah thats it. and you see that timed out failure versus the assert. so when those asserts go in "remove this on upgrade to lucene X", they do not have the desired impact.

**Comment by nik9000** [comment] 2015-09-21 21:58
Part of the problem is that we've set `es.logger.level` to `ERROR` but the error is being logged at `WARN`:
```
  1> [2015-09-21 17:56:04,262][WARN ][indices.cluster          ] [node_s_0] [[test-index][0]] marking and sending shard failed due to [failed to create shard]
  1> [test-index][[test-index][0]] ElasticsearchException[failed to create shard]; nested: AssertionError;
  1>    at org.elasticsearch.index.IndexService.createShard(IndexService.java:376)
  1>    at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyInitializingShard(IndicesClusterStateService.java:643)
  1>    at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyNewOrUpdatedShards(IndicesClusterStateService.java:543)
  1>    at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:178)
  1>    at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:496)
  1>    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
  1>    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
  1>    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  1>    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  1>    at java.lang.Thread.run(Thread.java:745)
  1> Caused by: java.lang.AssertionError
  1>    at org.elasticsearch.index.shard.IndexShard.<init>(IndexShard.java:250)
  1>    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  1>    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  1>    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  1>    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
  1>    at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:50)
  1>    at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
  1>    at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:110)
  1>    at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47)
  1>    at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:887)
  1>    at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
  1>    at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59)
  1>    at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:46)
  1>    at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:201)
  1>    at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
  1>    at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:880)
  1>    at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
  1>    at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
  1>    at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
  1>    at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:162)
  1>    at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:55)
  1>    at org.elasticsearch.index.IndexService.createShard(IndexService.java:374)
  1>    ... 9 more
```

Is there a good reason not to set `es.logger.level` to `WARN`?

The other issue I see is that we wait 30 seconds before giving up on the cluster ever getting into the desired state.

**Comment by rjernst** [comment] 2015-09-21 22:37
I think the problem is one of delayed action. AFAIK, "creating an index" starts by just putting something in the cluster state that says "there is a new uninitialized index" and returning. Then the master goes off and does allocation and such, and fails. In lieu of fixing the real issue (synchronous index creation), it seems like there the cluster health with waitFor request should fail once it is impossible to reach that state. So eg the index creation fails, it should return with a failure right away, not continue waiting for the timeout.

**Comment by nik9000** [comment] 2015-09-21 22:48
> I think the problem is one of delayed action. AFAIK, "creating an index" starts by just putting something in the cluster state that says "there is a new uninitialized index" and returning. Then the master goes off and does allocation and such, and fails. In lieu of fixing the real issue (synchronous index creation), it seems like there the cluster health with waitFor request should fail once it is impossible to reach that state. So eg the index creation fails, it should return with a failure right away, not continue waiting for the timeout.

I believe your assessment is correct. I started debugging around this afternoon looking for something to put a watch on.

**Comment by bleskes** [comment] 2015-09-22 08:06
> Then the master goes off and does allocation and such, and fails.

Small correction - the master doesn't fail to allocate (typically), but rather the node that receives the cluster state and goes and allocates the shard fails in creating it and notifies the master about it. This is where the asynchronicity  comes from.

> it seems like there the cluster health with waitFor request should fail once it is impossible to reach that state

This is trickier than it seems - how do you define that it is impossible to reach a state in  30s? maybe there is a network hick up that caused a node to drop off the cluster and it will be back? Maybe , like in our tests, we are busy forming a cluster and the nodes will join in 10 seconds?

The problem with this issue is we currently don't keep track of all the places we tried to create a shard and it failed. The master sees the shard fails message from a node, and tries another. If that fails it may go back to the first one. If you only have one node, the master will first clean the shard by sending the node a state where the shard is not assigned to it and then will try again. We should find a place to keep track of this and be able to say "we tried all options so far, so no point in trying again".  Perhaps the new unassigned info can be extended to keep "tried and failed" node list, which will be cleared upon successful allocation (because unassigned info goes away) and will be used to stop this infinite loop.

**Comment by nik9000** [comment] 2015-09-22 13:43
> The problem with this issue is we currently don't keep track of all the places we tried to create a shard and it failed. The master sees the shard fails message from a node, and tries another. If that fails it may go back to the first one. If you only have one node, the master will first clean the shard by sending the node a state where the shard is not assigned to it and then will try again. We should find a place to keep track of this and be able to say "we tried all options so far, so no point in trying again". Perhaps the new unassigned info can be extended to keep "tried and failed" node list, which will be cleared upon successful allocation (because unassigned info goes away) and will be used to stop this infinite loop.

At that point you could indeed "give up" on things - so long as you knew that you weren't going to add new nodes to the cluster which would give it more chances. But something like this seems like a long and windy journey. A journey with greatness at the end, for sure.

Minimally I think we should make sure that the actual failure is logged, even if we can't timeout eagerly. Could we set `es.logger.level` to `WARN` or even `INFO` for the tests? I liked the old days better, when tests were noisy and we used randomized testing to keep them quiet if they passed but they spit out a kajillion lines of useful logs if they failed.

When we timeout waiting for the cluster to go green can we attach the last hand full of errors as "potential causes"?

**Comment by rjernst** [comment] 2015-09-28 05:58
IMO definitely not `INFO`. We moved away from that because it is way too verbose when running tests. When tests fail, you want to see the failure. I would be ok with `WARN`. I have the gradle branch set to this, because I found there are some errors sometimes emitted as a warning (not sure why...we should fix that too but I've already forgot what the error was...).

**Comment by s1monw** [comment] 2015-11-11 09:39
I added only the assertion back in master and ran `IndexShardTests.java` with this output:

```
[2015-11-11 10:36:26,734][INFO ][org.elasticsearch.index.shard] --> idxPath: [/private/var/folders/qj/rsr2js6n275f3r88r1z5bbgw0000gn/T/org.elasticsearch.index.shard.IndexShardTests_A92392023D5F82E0-001/OibDuggcVx]
[2015-11-11 10:36:26,940][INFO ][org.elasticsearch.cluster.metadata] [node_s_0] [test] creating index, cause [api], templates [], shards [1]/[0], mappings []
[2015-11-11 10:36:27,042][WARN ][org.elasticsearch.indices.cluster] [node_s_0] [[test][0]] marking and sending shard failed due to [failed to create shard]
java.lang.AssertionError
	at org.elasticsearch.index.shard.IndexShard.<init>(IndexShard.java:264)
	at org.elasticsearch.index.IndexService.createShard(IndexService.java:279)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyInitializingShard(IndicesClusterStateService.java:627)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyNewOrUpdatedShards(IndicesClusterStateService.java:527)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:184)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:517)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2015-11-11 10:36:27,121][WARN ][org.elasticsearch.cluster.action.shard] [node_s_0] [test][0] received shard failed for [test][0], node[tTPyckqMRDaf8clvc9SzOA], [P], v[1], s[INITIALIZING], a[id=OlU9n_QSS9OXBvk_TgNzeA], unassigned_info[[reason=INDEX_CREATED], at[2015-11-11T09:36:26.943Z]], indexUUID [6qDGq_IkToCsYtCvoKMWUg], message [failed to create shard], failure [AssertionError[null]]
java.lang.AssertionError
	at org.elasticsearch.index.shard.IndexShard.<init>(IndexShard.java:264)
	at org.elasticsearch.index.IndexService.createShard(IndexService.java:279)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyInitializingShard(IndicesClusterStateService.java:627)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyNewOrUpdatedShards(IndicesClusterStateService.java:527)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:184)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:517)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

you will now see this in master once per shard but after 30 sec the test times out and all is well. This is purely caused by guice which is gone in master. I am closing this

**Closed by s1monw** 2015-11-11 09:39 UTC
Labels: :Cluster, bug, PITA
