### ISSUE TITLE
Reverse nested aggregations for parent child relationships

### ISSUE THREAD

**Issue by vineet85** [elastic/elasticsearch#11578] opened 2015-06-10 14:07 UTC
Hi,
I'm noticing the reverse nested aggregation feature is available only for the nested data model but not for parent-child. We need to use parent-child since update latency is very important to us but noticing that aggregations which are several levels deep are not possible in a single query using parent child.

Here is how this can be done with the Nested model. Is this something which can be added for parent-child?

REQUEST:-
POST/document_test/document/_search?search_type=count{
    "aggs": {
        "created_date_agg": {
            "nested": {
                "path": "metadata"
            },
            "aggs": {
                "created_date_agg_filter": {
                    "filter": {
                        "term": {
                            "fieldid": "CREATEDDATE"
                        }
                    },
                    "aggs": {
                        "created_date_agg_values": {
                            "terms": {
                                "field": "fieldvalue"
                            },
                            "aggs": {
                                "metadata_to_parent": {
                                    "reverse_nested": {
                                        
                                    },
                                    "aggs": {
                                        "filetype_agg": {
                                            "nested": {
                                                "path": "metadata"
                                            },
                                            "aggs": {
                                                "filetype_agg_filter": {
                                                    "filter": {
                                                        "term": {
                                                            "fieldid": "DOCTYPE"
                                                        }
                                                    },
                                                    "aggs": {
                                                        "filetype_agg_values": {
                                                            "terms": {
                                                                "field": "fieldvalue"
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

RESPONSE:-
RESPONSE: -"aggregations": {
    "created_date_agg": {
        "doc_count": 12,
        "created_date_agg_filter": {
            "doc_count": 4,
            "created_date_agg_values": {
                "doc_count_error_upper_bound": 0,
                "sum_other_doc_count": 0,
                "buckets": [
                    {
                        "key": "6/9/2015",
                        "doc_count": 3,
                        "metadata_to_parent": {
                            "doc_count": 3,
                            "filetype_agg": {
                                "doc_count": 9,
                                "filetype_agg_filter": {
                                    "doc_count": 3,
                                    "filetype_agg_values": {
                                        "doc_count_error_upper_bound": 0,
                                        "sum_other_doc_count": 0,
                                        "buckets": [
                                            {
                                                "key": "Excel",
                                                "doc_count": 2
                                            },
                                            {
                                                "key": "Microsoft Word",
                                                "doc_count": 1
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    },
                    {
                        "key": "6/10/2015",
                        "doc_count": 1,
                        "metadata_to_parent": {
                            "doc_count": 1,
                            "filetype_agg": {
                                "doc_count": 3,
                                "filetype_agg_filter": {
                                    "doc_count": 1,
                                    "filetype_agg_values": {
                                        "doc_count_error_upper_bound": 0,
                                        "sum_other_doc_count": 0,
                                        "buckets": [
                                            {
                                                "key": "Powerpoint",
                                                "doc_count": 1
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                ]
            }
        }
    }
}
}

**Comment by clintongormley** [comment] 2015-06-12 15:05
Duplicate of #5306

**Closed by clintongormley** 2015-06-12 15:05 UTC
