### ISSUE TITLE
search using Rest API call from python is different from REST API call from browser

### ISSUE THREAD

**Issue by JeevaTM** [elastic/elasticsearch#41111] opened 2019-04-11 10:08 UTC
I have stored multiple documents. Each document has two sentences. When I made a search using REST API call from browser for the word 'Times of India', it only returned the particular sentences which has the word 'Times of India'. When I tried to make a search using REST API call from python code for the same word 'Times of India', it returned all the sentences with the words 'Times', 'Of', and 'India'. It is not the case when we search for 'The Hindu' or 'Cloud Service Provider', etc.

**Comment by DaveCTurner** [comment] 2019-04-11 10:14
Hi @JeevaTM, it is likely that the difference between these behaviours is because the API call that Elasticsearch receives are different. It'd be better to ask about this on the [discussion forum](https://discuss.elastic.co/c/elasticsearch) since we prefer to keep GitHub issues for confirmed bug reports and feature requests. I am closing this issue, but if you open a thread on the discussion forum then please link to it from here so other readers can find the rest of the discussion.

**Closed by DaveCTurner** 2019-04-11 10:14 UTC

**Comment by JeevaTM** [comment] 2019-04-11 10:19
Alright. Thanks for the heads up.
