### ISSUE TITLE
[CI] MlDistributedFailureIT testClusterWithTwoMlNodes_RunsDatafeed_GivenOriginalNodeGoesDown failing

### ISSUE THREAD

**Issue by pxsalehi** [elastic/elasticsearch#104361] opened 2024-01-15 10:46 UTC
**Build scan:**
https://gradle-enterprise.elastic.co/s/gvys7gqavcfvq/tests/:x-pack:plugin:ml:internalClusterTest/org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT/testClusterWithTwoMlNodes_RunsDatafeed_GivenOriginalNodeGoesDown

**Reproduction line:**
```
./gradlew ':x-pack:plugin:ml:internalClusterTest' --tests "org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.testClusterWithTwoMlNodes_RunsDatafeed_GivenOriginalNodeGoesDown" -Dtests.seed=D0733C3E0FD14A9D -Dtests.locale=ar-LB -Dtests.timezone=Asia/Choibalsan -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT#testClusterWithTwoMlNodes_RunsDatafeed_GivenOriginalNodeGoesDown`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testClusterWithTwoMlNodes_RunsDatafeed_GivenOriginalNodeGoesDown'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: an empty collection
     but: <[LEAK: resource was not cleaned up before it was garbage-collected.
Recent access records: 
Created at:
	org.elasticsearch.action.search.ArraySearchPhaseResults.<init>(ArraySearchPhaseResults.java:25)
	org.elasticsearch.action.search.QueryPhaseResultConsumer.<init>(QueryPhaseResultConsumer.java:85)
	org.elasticsearch.action.search.SearchPhaseController.newSearchPhaseResults(SearchPhaseController.java:807)
	org.elasticsearch.action.search.TransportSearchAction$AsyncSearchActionProvider.newSearchPhase(TransportSearchAction.java:1298)
	org.elasticsearch.action.search.TransportSearchAction.executeSearch(TransportSearchAction.java:1127)
	org.elasticsearch.action.search.TransportSearchAction.executeLocalSearch(TransportSearchAction.java:909)
	org.elasticsearch.action.search.TransportSearchAction.lambda$executeRequest$10(TransportSearchAction.java:336)
	org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:236)
	org.elasticsearch.index.query.Rewriteable.rewriteAndFetch(Rewriteable.java:109)
	org.elasticsearch.index.query.Rewriteable.rewriteAndFetch(Rewriteable.java:77)
	org.elasticsearch.action.search.TransportSearchAction.executeRequest(TransportSearchAction.java:448)
	org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:303)
	org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:112)
	org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:97)
	org.elasticsearch.action.support.ActionFilter$Simple.apply(ActionFilter.java:53)
	org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:94)
	org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:69)
	org.elasticsearch.tasks.TaskManager.registerAndExecute(TaskManager.java:196)
	org.elasticsearch.client.internal.node.NodeClient.executeLocally(NodeClient.java:104)
	org.elasticsearch.client.internal.node.NodeClient.doExecute(NodeClient.java:82)
	org.elasticsearch.client.internal.support.AbstractClient.execute(AbstractClient.java:361)
	org.elasticsearch.client.internal.FilterClient.doExecute(FilterClient.java:54)
	org.elasticsearch.client.internal.ParentTaskAssigningClient.doExecute(ParentTaskAssigningClient.java:61)
	org.elasticsearch.client.internal.support.AbstractClient.execute(AbstractClient.java:361)
	org.elasticsearch.client.internal.support.AbstractClient.execute(AbstractClient.java:347)
	org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:34)
	org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:41)
	org.elasticsearch.xpack.core.ClientHelper.executeWithHeaders(ClientHelper.java:274)
	org.elasticsearch.xpack.ml.datafeed.extractor.scroll.ScrollDataExtractor.executeSearchRequest(ScrollDataExtractor.java:137)
	org.elasticsearch.xpack.ml.datafeed.extractor.scroll.ScrollDataExtractor.initScroll(ScrollDataExtractor.java:124)
	org.elasticsearch.xpack.ml.datafeed.extractor.scroll.ScrollDataExtractor.tryNextStream(ScrollDataExtractor.java:118)
	org.elasticsearch.xpack.ml.datafeed.extractor.scroll.ScrollDataExtractor.next(ScrollDataExtractor.java:101)
	org.elasticsearch.xpack.ml.datafeed.extractor.chunked.ChunkedDataExtractor.getNextStream(ChunkedDataExtractor.java:172)
	org.elasticsearch.xpack.ml.datafeed.extractor.chunked.ChunkedDataExtractor.next(ChunkedDataExtractor.java:118)
	org.elasticsearch.xpack.ml.datafeed.DatafeedJob.run(DatafeedJob.java:376)
	org.elasticsearch.xpack.ml.datafeed.DatafeedJob.runLookBack(DatafeedJob.java:179)
	org.elasticsearch.xpack.ml.datafeed.DatafeedRunner$Holder.executeLookBack(DatafeedRunner.java:548)
	org.elasticsearch.xpack.ml.datafeed.DatafeedRunner$2.doRun(DatafeedRunner.java:247)
	org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:917)
	java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	java.base/java.lang.Thread.run(Thread.java:1583)]>

  at __randomizedtesting.SeedInfo.seed([D0733C3E0FD14A9D:773E082CD674FE76]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:964)
  at org.junit.Assert.assertThat(Assert.java:930)
  at org.elasticsearch.test.ESTestCase.checkStaticState(ESTestCase.java:727)
  at org.elasticsearch.test.ESTestCase.after(ESTestCase.java:518)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by pxsalehi** [comment] 2024-01-15 10:48
Just a guess: this might not be directly related to ML but rather a bug in the recent changes to managing search results, etc. But I might be wrong.

**Comment by maxhniebergall** [comment] 2024-01-15 15:19
another failure: https://gradle-enterprise.elastic.co/s/alngveogeycgk

**Comment by droberts195** [comment] 2024-01-18 15:54
This is the same thing as #103108, #104071 and #104081. They're all tests in the same suite failing for the same reason.

This suite contains internal cluster tests that run multiple nodes inside the same JVM and unexpectedly stop them to simulate failures. Presumably this plays havoc with the search response leak checking in some way.

**Comment by droberts195** [comment] 2024-01-18 16:52
I've had a closer look at this and can now see that it's _not_ the `SearchResponse` object referenced from the datafeed code that's leaking, but an `ArraySearchPhaseResults` object that's used deep inside the search action implementation.

I imagine that's getting leaked because part of shutting down a node is to shut down the search service: https://github.com/elastic/elasticsearch/blob/14acde97328bdccdf955fa4a476ab4f841a35946/server/src/main/java/org/elasticsearch/node/Node.java#L545

So when the distributed failure tests stop a node to simulate it failing they will shut down its search service and this may cause some low-level internal objects to not be cleaned up properly. However, this would not matter at all in a production node if it only happened immediately before termination.

@original-brownbear should we add an option to internal cluster tests to bypass the leak check and simply reset leak tracking if an internal cluster node has been shut down during the test?

**Comment by original-brownbear** [comment] 2024-01-18 17:12
>  should we add an option to internal cluster tests to bypass the leak check and simply reset leak tracking if an internal cluster node has been shut down during the test?

I don't think that's possible. The leak tracker is a per JVM thing that hooks into the GC process. If we missed closing something before it gets collected, we log the leak. We can't reliably isolate a node or even a single test here.
We had this kind of issue before in e.g. recovery, the fix here (assuming the problem is with the shutdown) should be done in whatever service gets shut down. Looking into that now :) Thanks for pointing out the shutdown, I completely missed that that was the likely relevant thing here :)

**Comment by kingherc** [comment] 2024-02-14 10:33
More leak at [elasticsearch / periodic / platform-support / 8.12 / rhel-8 / platform-support-unix](https://gradle-enterprise.elastic.co/s/nlqvckx56vb4i)

```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:internalClusterTest' --tests "org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.testFullClusterRestart" -Dtests.seed=A6C119ADD98B1F4E -Dtests.locale=es-AR -Dtests.timezone=Asia/Manila -Druntime.java=21

org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT > testFullClusterRestart FAILED
    java.lang.AssertionError: 
    Expected: an empty collection
         but: <[LEAK: resource was not cleaned up before it was garbage-collected.
    Recent access records: 
    Created at:
    	org.elasticsearch.action.search.ArraySearchPhaseResults.<init>(ArraySearchPhaseResults.java:25)
    	org.elasticsearch.action.search.QueryPhaseResultConsumer.<init>(QueryPhaseResultConsumer.java:85)
    	org.elasticsearch.action.search.SearchPhaseController.newSearchPhaseResults(SearchPhaseController.java:808)
    	org.elasticsearch.action.search.TransportSearchAction$AsyncSearchActionProvider.newSearchPhase(TransportSearchAction.java:1323)
    	org.elasticsearch.action.search.TransportSearchAction.executeSearch(TransportSearchAction.java:1152)
    	org.elasticsearch.action.search.TransportSearchAction.executeLocalSearch(TransportSearchAction.java:913)
```

**Comment by astefan** [comment] 2024-04-04 14:17
Same class, different test method, same error and stack trace. Today on 8.13: https://gradle-enterprise.elastic.co/s/pkp2hy2erwbz4

```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:internalClusterTest' --tests "org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.testFullClusterRestart" -Dtests.seed=714DED3E6D154A7B -Dtests.locale=he-IL -Dtests.timezone=Canada/Eastern -Druntime.java=22

org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT > testFullClusterRestart FAILED
    java.lang.AssertionError: 
    Expected: an empty collection
         but: <[LEAK: resource was not cleaned up before it was garbage-collected.
    Recent access records: 
    Created at:
    	org.elasticsearch.action.search.ArraySearchPhaseResults.<init>(ArraySearchPhaseResults.java:27)
    	org.elasticsearch.action.search.QueryPhaseResultConsumer.<init>(QueryPhaseResultConsumer.java:85)
    	org.elasticsearch.action.search.SearchPhaseController.newSearchPhaseResults(SearchPhaseController.java:813)
    	org.elasticsearch.action.search.TransportSearchAction$AsyncSearchActionProvider.newSearchPhase(TransportSearchAction.java:1324)
    	org.elasticsearch.action.search.TransportSearchAction.executeSearch(TransportSearchAction.java:1153)
    	org.elasticsearch.action.search.TransportSearchAction.executeLocalSearch(TransportSearchAction.java:914)
    	org.elasticsearch.action.search.TransportSearchAction.lambda$executeRequest$8(TransportSearchAction.java:342)
    	org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:245)
    	org.elasticsearch.index.query.Rewriteable.rewriteAndFetch(Rewriteable.java:109)
    	org.elasticsearch.index.query.Rewriteable.rewriteAndFetch(Rewriteable.java:77)
    	org.elasticsearch.action.search.TransportSearchAction.executeRequest(TransportSearchAction.java:455)
    	org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:309)
    	org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:113)
    	org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:96)
    	org.elasticsearch.action.support.ActionFilter$Simple.apply(ActionFilter.java:53)
    	org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:93)
    	org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:68)
    	org.elasticsearch.tasks.TaskManager.registerAndExecute(TaskManager.java:196)
    	org.elasticsearch.client.internal.node.NodeClient.executeLocally(NodeClient.java:105)
    	org.elasticsearch.client.internal.node.NodeClient.doExecute(NodeClient.java:83)
    	org.elasticsearch.client.internal.support.AbstractClient.execute(AbstractClient.java:356)
    	org.elasticsearch.client.internal.support.AbstractClient.search(AbstractClient.java:491)
    	org.elasticsearch.xpack.core.ClientHelper.executeAsyncWithOrigin(ClientHelper.java:221)
    	org.elasticsearch.xpack.ml.job.persistence.JobConfigProvider.expandJobs(JobConfigProvider.java:585)
    	org.elasticsearch.xpack.ml.job.JobManager.expandJobBuilders(JobManager.java:170)
    	org.elasticsearch.xpack.ml.action.TransportGetJobsAction.masterOperation(TransportGetJobsAction.java:75)
    	org.elasticsearch.xpack.ml.action.TransportGetJobsAction.masterOperation(TransportGetJobsAction.java:34)
    	org.elasticsearch.action.support.master.TransportMasterNodeAction.executeMasterOperation(TransportMasterNodeAction.java:125)
    	org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.lambda$doStart$3(TransportMasterNodeAction.java:236)
    	org.elasticsearch.action.ActionRunnable$4.doRun(ActionRunnable.java:95)
    	org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
    	org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:241)
    	org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.doStart(TransportMasterNodeAction.java:236)
    	org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:173)
    	org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:55)
    	org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:96)
    	org.elasticsearch.action.support.ActionFilter$Simple.apply(ActionFilter.java:53)
    	org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:93)
    	org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:68)
    	org.elasticsearch.tasks.TaskManager.registerAndExecute(TaskManager.java:196)
    	org.elasticsearch.client.internal.node.NodeClient.executeLocally(NodeClient.java:105)
    	org.elasticsearch.client.internal.node.NodeClient.doExecute(NodeClient.java:83)
    	org.elasticsearch.client.internal.support.AbstractClient.execute(AbstractClient.java:356)
    	org.elasticsearch.xpack.core.ClientHelper.lambda$executeAsyncWithOrigin$3(ClientHelper.java:236)
    	org.elasticsearch.xpack.core.ClientHelper.executeAsyncWithOrigin(ClientHelper.java:221)
    	org.elasticsearch.xpack.core.ClientHelper.executeAsyncWithOrigin(ClientHelper.java:236)
    	org.elasticsearch.xpack.ml.job.task.OpenJobPersistentTasksExecutor$RevertToCurrentSnapshotAction.tryAction(OpenJobPersistentTasksExecutor.java:543)
    	org.elasticsearch.action.support.RetryableAction$1.doRun(RetryableAction.java:111)
    	org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
    	org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
    	java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    	java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    	java.base/java.lang.Thread.run(Thread.java:1570)]>
        at __randomizedtesting.SeedInfo.seed([714DED3E6D154A7B:2062FC2F983902D4]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at org.elasticsearch.test.ESTestCase.assertThat(ESTestCase.java:2119)
        at org.elasticsearch.test.ESTestCase.checkStaticState(ESTestCase.java:729)
        at org.elasticsearch.test.ESTestCase.after(ESTestCase.java:520)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
        at java.base/java.lang.Thread.run(Thread.java:1570)
```

**Comment by ywangd** [comment] 2024-04-26 07:24
Failed again on 8.14 https://gradle-enterprise.elastic.co/s/py24whnokg3vw/tests/task/:x-pack:plugin:ml:internalClusterTest/details/org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT/testClusterWithTwoMlNodes_RunsDatafeed_GivenOriginalNodeGoesDown?top-execution=1

**Comment by original-brownbear** [comment] 2024-05-07 17:01
Hmm this might not be as benign as assumed after all. The leak trace here would explain #108369 ... lets see

**Closed** 2024-05-13 08:26 UTC
Labels: >test-failure, :ml, Team:ML, needs:risk
