### ISSUE TITLE
Heap slowly filling up with org.elasticsearch.index.SearchSlowLog$SlowLogSearchContextPrinter

### ISSUE THREAD

**Issue by ccoffey** [elastic/elasticsearch#32537] opened 2018-08-01 10:45 UTC
**Elasticsearch version** (`bin/elasticsearch --version`):

```json
{
   "version" : {
      "number" : "6.3.0",
       "build_flavor" : "default",
       "build_type" : "rpm",
       "build_hash" : "424e937",
       "build_date" : "2018-06-11T23:38:03.357887Z",
       "build_snapshot" : false,
       "lucene_version" : "7.3.1",
       "minimum_wire_compatibility_version" : "5.6.0",
       "minimum_index_compatibility_version" : "5.0.0"
  }
}
```

**Plugins installed**: ['discovery-ec2', 'repository-s3']

**JVM version** (`java -version`):

```
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system):
```
Linux es-data-1 4.14.51-60.38.amzn1.x86_64 #1 SMP Tue Jun 26 23:06:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Description of the problem including expected versus actual behavior**:

Garbage collection is able to recover less and less of the heap as time moves on. Eventually this puts a lot of memory pressure on `data-nodes` and we see long pause the world `Old GC collections`

![screen shot 2018-08-01 at 11 38 42](https://user-images.githubusercontent.com/456400/43517118-848f568c-957f-11e8-8709-32536bacd6f3.png)

**Day 1**

![screen shot 2018-08-01 at 11 12 25](https://user-images.githubusercontent.com/456400/43515939-cd3005a2-957b-11e8-81f4-94009bc73bdf.png)

**Day 2**

![screen shot 2018-08-01 at 11 17 45](https://user-images.githubusercontent.com/456400/43516140-8d54fc70-957c-11e8-8eda-54c1992bcbdc.png)

**Day 3**

![screen shot 2018-08-01 at 11 19 30](https://user-images.githubusercontent.com/456400/43516208-ca9ba480-957c-11e8-9e75-2d57faf3a710.png)

On Day 3, we took a heap dump and saw that `6,776 MB == ~30%` of the heap was filled with `org.elasticsearch.index.SearchSlowLog$SlowLogSearchContextPrinter` 

<img width="1729" alt="43466021-8679f9f6-94d6-11e8-8e79-7357e64a5b8b" src="https://user-images.githubusercontent.com/456400/43516565-d3b49648-957d-11e8-992c-f8132c4be0ae.png">

We then turned off slow logging by doing the following

```
curl -XPUT 'localhost:9200/_settings' -H 'Content-Type: application/json' -d '{
  "index.indexing.slowlog.level": null,
  "index.search.slowlog.threshold.query.warn": null,
  "index.search.slowlog.threshold.fetch.warn": null,
  "index.indexing.slowlog.threshold.index.warn": null
}'
```

We restarted each `data-node` in our cluster 12 hours ago and things seem stable since then (really we won't be sure for a few more days).

**Last 12 hours**

![screen shot 2018-08-01 at 11 32 14](https://user-images.githubusercontent.com/456400/43516808-90417af6-957e-11e8-9078-e3ddfd120126.png)

**Last hour**

![screen shot 2018-08-01 at 11 32 45](https://user-images.githubusercontent.com/456400/43516838-a624fe4c-957e-11e8-9d5f-73547ff1c439.png)

**Steps to reproduce**:

I haven't tried to reproduce this, but this has happened to all four of our `ES 6.3.0` clusters.

 1. Turn on slow logging
 2. Generate a lot of slow queries
 3. Look at the metric `jvm.mem.heap_in_use` over time. 
 
**Note:** This issue might have the same route cause as: https://github.com/elastic/elasticsearch/issues/27300

**Comment by gregolsen** [comment] 2018-08-03 21:44
@original-brownbear thanks for figuring out the root cause, I also did some investigation and came to the same conclusion, failed to find the already opened log4j issue though.

@ccoffey I just put a summary of my investigations to add a bit of context about our specific case here:
Our data node has 32 cores and hence search thread pool is 32 * 3 / 2 + 1 = 49 threads.
Sometimes our cluster processes insanely huge queries with raw size of tens of MB (e.g. 22 MB).
Overtime all the threads in the pool process a query like that which is logged as a slow query. Upon logging `MutableLogEvent`, stored in a thread local by log4j, still holds the reference to the search context which contains both raw query in a string builder as well as its parsed version. This is not GCed until next query above slow log threshold gets logged. On the screenshot in the issue description there are 47 `SearchSlowLogContextPrinter` objects reported, so 47 out of 49 threads had processed one of those massive queries by the time we started seeing old GC spikes.

I was able to reproduce this locally with a 22MB query:
All 7 search threads have lots of retained heap (I have 4 cores on my local machine)
<img width="1207" alt="screen shot 2018-08-03 at 17 22 34" src="https://user-images.githubusercontent.com/287994/43666581-bb6aef94-9774-11e8-82b1-3324d42242cd.png">

A given thread has a `MutableLogEvent` thread local that holds the reference to the search context through `SearchSlowLogContextPrinter`:
![eclipse memory analyzer 2018-08-03 23-38-53](https://user-images.githubusercontent.com/287994/43667111-e2380628-9776-11e8-8483-8f1c9d8aca36.jpg)

For our huge query (so called company ids query) all the memory is consumed by the `BigByteArray`. The problem happened at roughly the same time over the day, we probably have something triggered on schedule. Slow log files were rotated just when the issued occurred and were all filled with company ids queries. On the image above you can actually see company ids in that `BigByteArray`.
```
-rw-r--r-- 1 elasticsearch elasticsearch 4116645 Jul 23 23:44 usersearch13_index_search_slowlog-2018-07-23.log
-rw-r--r-- 1 elasticsearch elasticsearch 1136998 Jul 24 12:34 usersearch13_index_search_slowlog-2018-07-24.log
-rw-r--r-- 1 elasticsearch elasticsearch  144436 Jul 26 15:41 usersearch13_index_search_slowlog-2018-07-26.log
-rw-r--r-- 1 elasticsearch elasticsearch   90783 Jul 27 15:36 usersearch13_index_search_slowlog-2018-07-27.log
-rw-r--r-- 1 elasticsearch elasticsearch  100870 Jul 28 15:31 usersearch13_index_search_slowlog-2018-07-28.log
-rw-r--r-- 1 elasticsearch elasticsearch  191653 Jul 29 15:31 usersearch13_index_search_slowlog-2018-07-29.log
```

**Comment by jimczi** [comment] 2018-08-06 09:10
It seems that there is a fix for this in log4j 2.10.0:
https://issues.apache.org/jira/browse/LOG4J2-2269
https://logging.apache.org/log4j/2.0/changes-report.html#a2.10.0
We use version ` 2.9.1` so we'd need to upgrade to a more recent version to get the fix.
That said you should probably limit the size of you query by not using huge `terms` query. These queries are not handled efficiently in Lucene and since they can pollute the cache we've decided to disable caching when they reach 1MB.

**Comment by original-brownbear** [comment] 2018-08-06 09:12
@jimczi already incoming here https://github.com/elastic/elasticsearch/pull/32616 :)

**Comment by jimczi** [comment] 2018-08-06 09:18
Thanks @original-brownbear I missed the pr link on the issue ;).

**Comment by gregolsen** [comment] 2018-08-06 09:57
@jimczi thank you for the response. Unfortunately those huge queries are the result of an application side join (second query with lots of IDs). It is a many to many relationship with some of the documents linked with thousands of others and frequently updated. So we can't denormalize it. Limiting it in size would result in lots of batched queries and it might not be an option for us. 

 Is there any setting to tune this 1MB limit?

**Comment by jimczi** [comment] 2018-08-06 10:38
Sorry it's 1024 `bytes` and not mega bytes and you cannot change it. These large queries break the memory accounting of the query cache (we don't estimate the size of query objects) and used to lead to out of memory issue so we've decided to ban them from the query cache. 

>  Limiting it in size would result in lots of batched queries and it might not be an option for us.

You might be interested by https://github.com/elastic/elasticsearch/issues/25674 . Not limiting these queries in size will cause instability in your cluster.

**Closed** 2018-08-06 12:56 UTC
Labels: :Core/Logging, >bug

**Comment by ccoffey** [comment] 2018-08-07 08:09
> Not limiting these queries in size will cause instability in your cluster.

Thank you for this information @original-brownbear. Can you please elaborate on what you mean by `will cause instability`. How is this likely to manifest itself? Are we talking about a slow degradation in the clusters performance over time (like this memory leak)? Or are we talking about instability during one of these queries because the query itself consumes a lot of resources?

**Comment by original-brownbear** [comment] 2018-08-07 08:12
@jimczi  ^^

**Comment by jimczi** [comment] 2018-08-07 08:50
> Are we talking about a slow degradation in the clusters performance over time (like this memory leak)? Or are we talking about instability during one of these queries because the query itself consumes a lot of resources?

I'd say instability during these queries and maybe even OOME errors if you have too many ids or if you return a lot of documents. There is no leak when you run these big queries but since they take time and memories they can disturb the other queries and make the cluster unresponsive.
