### ISSUE TITLE
[CI] StableMasterDisruptionIT testStaleMasterNotHijackingMajority test failing on OpenJDK 20

### ISSUE THREAD

**Issue by n1v0lg** [elastic/elasticsearch#93707] opened 2023-02-10 16:04 UTC
### CI Link

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+8.7+periodic+java-matrix/ES_RUNTIME_JAVA=openjdk20,GRADLE_TASK=checkPart1,nodes=general-purpose/4/

### Repro line

`./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.discovery.StableMasterDisruptionIT.testStaleMasterNotHijackingMajority" -Dtests.seed=5D665FEF0E31DE1C -Dtests.locale=nb -Dtests.timezone=Pacific/Kosrae -Druntime.java=20`

### Does it reproduce?

Didn't try

### Applicable branches

main

### Failure excerpt

```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.discovery.StableMasterDisruptionIT.testStaleMasterNotHijackingMajority" -Dtests.seed=5D665FEF0E31DE1C -Dtests.locale=nb -Dtests.timezone=Pacific/Kosrae -Druntime.java=20

org.elasticsearch.discovery.StableMasterDisruptionIT > testStaleMasterNotHijackingMajority FAILED
    java.lang.UnsupportedOperationException
        at java.base/java.lang.Thread.resume(Thread.java:1882)
        at org.elasticsearch.test.disruption.LongGCDisruption.resumeThreads(LongGCDisruption.java:346)
        at org.elasticsearch.test.disruption.LongGCDisruption.startDisrupting(LongGCDisruption.java:178)
        at org.elasticsearch.discovery.StableMasterDisruptionIT.testStaleMasterNotHijackingMajority(StableMasterDisruptionIT.java:278)

    java.lang.UnsupportedOperationException
        at java.base/java.lang.Thread.resume(Thread.java:1882)
        at org.elasticsearch.test.disruption.LongGCDisruption.resumeThreads(LongGCDisruption.java:346)
        at org.elasticsearch.test.disruption.LongGCDisruption.stopDisrupting(LongGCDisruption.java:199)
        at org.elasticsearch.test.disruption.SingleNodeDisruption.removeFromNode(SingleNodeDisruption.java:59)
        at org.elasticsearch.test.disruption.SingleNodeDisruption.removeFromCluster(SingleNodeDisruption.java:42)
        at org.elasticsearch.test.disruption.LongGCDisruption.removeAndEnsureHealthy(LongGCDisruption.java:218)
        at org.elasticsearch.test.InternalTestCluster.clearDisruptionScheme(InternalTestCluster.java:2261)
        at org.elasticsearch.test.InternalTestCluster.clearDisruptionScheme(InternalTestCluster.java:2252)
        at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:562)
        at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2249)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
        at java.base/java.lang.Thread.run(Thread.java:1623)
```

**Comment by pxsalehi** [comment] 2023-02-13 14:56
I think this has to do with this change in OpenJDK https://jdk.java.net/20/release-notes#JDK-8249627. They're going to remove `Thread.suspend/resume`. 

I guess the test itself doesn't have an issue, but we'd have to do something about how `org.elasticsearch.test.disruption.**` works. 

Should we close this, and create an issue to track this?

**Comment by pxsalehi** [comment] 2023-02-13 15:01
They've been deprecated since 1998! 😃

**Comment by pxsalehi** [comment] 2023-02-13 15:07
This might be useful: https://docs.oracle.com/en/java/javase/19/docs/api/java.base/java/lang/doc-files/threadPrimitiveDeprecation.html

**Comment by DaveCTurner** [comment] 2023-02-13 15:27
++ I'm asking the core/infra folks for some ideas for what to do about this disruption mechanism

**Comment by thecoop** [comment] 2023-02-13 16:06
Using thread resume is a really bad way of simulating a long GC, GCs ensure threads are in safe points before pausing them, which (AFAIK) `suspend` does not do. The test does try and make sure the threads are in ES-relative safe points, but still, this test gives me the heebie-geebies.

The way I've seen this sort of thing tested previously is by having empty overridable methods in the classes you want to test, that are then overridden in test scenarios to add an `await` on some sort of sync object that is manipulated in the test. That way the test runs in cooperation with the testee class, at specific known points of contention, without manipulating threads that are possibly running native JVM code.

**Comment by davidkyle** [comment] 2023-02-20 10:28
A couple more failures, the first eventually OOM'd 

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+8.7+periodic+java-matrix/ES_RUNTIME_JAVA=openjdk20,GRADLE_TASK=checkPart1,nodes=general-purpose/23/consoleText

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+main+periodic+java-matrix/ES_RUNTIME_JAVA=openjdk20,GRADLE_TASK=checkPart1,nodes=general-purpose/671/consoleText

```
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-1-thread-1"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "main"
```

These tests are quite difficult to triage as Gradle is not reporting the test failure, I've added OpenJDK to the title so that others may arrive here sooner

**Comment by ChrisHegarty** [comment] 2023-02-24 09:44
While I agree with @thecoop (Using thread suspend is a really bad way of simulating a long GC), injecting or otherwise overloading some common usage like, say logging or security manager callbacks, is quite invasive. The use of Thread suspend/resume is quite fragile, has this test proven to be reliable over the years? 

Some similar-to-existing replacements that come to mind:
1. JVMTI can be used to directly suspend and resume Java threads (requires some minimal native C implementation)
2. JDI (the Debugger Interface) can also directly suspend and resume Java threads.

**Comment by craigtaverner** [comment] 2023-02-28 14:04
As @DaveCTurner mentions, this might be the cause of the LongGCDistruptionTests failures:

* Today 28th Feb: https://gradle-enterprise.elastic.co/s/2cez7jjoafjy6/tests/:test:framework:test/org.elasticsearch.test.disruption.LongGCDisruptionTests/testNotBlockingUnsafeStackTraces?top-execution=1
* Also a month ago on the 2nd February: https://gradle-enterprise.elastic.co/s/azrns37543ppo/tests/:test:framework:test/org.elasticsearch.test.disruption.LongGCDisruptionTests/testNotBlockingUnsafeStackTraces?top-execution=1

**Comment by DaveCTurner** [comment] 2023-02-28 18:00
That sounds fine to me. I'm not convinced these tests are worth much effort to reinstate, but we can discuss that at a later date.

**Closed** 2023-03-01 15:13 UTC
Labels: :Core/Infra/Core, >test-failure, Team:Core/Infra
