### ISSUE TITLE
Feature request: List stored scripts endpoint.

### ISSUE THREAD

**Issue by codebrain** [elastic/elasticsearch#42735] opened 2019-05-31 00:17 UTC
A list of stored scripts is available through the cluster state metadata endpoint, but not available as a first class endpoint in itself.

Given the versioning semantics of the cluster state response (i.e. not guaranteed there will not be breaking changes between minor versions) can we look to add a "list" endpoint.

https://www.elastic.co/guide/en/elasticsearch/reference/6.2/modules-scripting-using.html#modules-scripting-stored-scripts - does not mention a "list" endpoint.

This relates to a customer request here:
https://github.com/elastic/elasticsearch-net/issues/3746

(copying in @cscorley - customer seeking the feature)

**Comment by ozencem** [comment] 2019-06-03 07:29
Hi @codebrain and the team,

I am new to Elasticsearch development, although I have been wanting to contribute to it for a while now. Can I pick this issue up? It would help me get familiar with the codebase, the review process etc. for future contributions. 

I actually had some time last night and I have a basic working implementation already but it obviously needs more polishing and testing but I would be more than happy to work with the team to get a good PR out for this feature if that's alright with you as well.

**Comment by codebrain** [comment] 2019-06-03 07:55
Hi @ozencem - that'd be great!

It might be worth taking a read of the `CONTRIBUTING.MD` document: https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md

At some point when you submit a PR you'll need to ensure that you have signed the CLA contributor agreement: https://www.elastic.co/contributor-agreement

When you open a PR be sure to link to this ticket so we can keep track.

Thanks and best of luck!

**Comment by rjernst** [comment] 2019-06-20 23:41
Closing as a duplicate of https://github.com/elastic/elasticsearch/issues/25179

**Closed by rjernst** 2019-06-20 23:41 UTC
Labels: :Core/Infra/Scripting, >feature
