### ISSUE TITLE
Filter does not work if field value is "No" - Tried with Query Search & Kibana

### ISSUE THREAD

**Issue by jagansankara** [elastic/elasticsearch#50640] opened 2020-01-06 09:06 UTC
**Elasticsearch version** : 7.0.1

**Description of the problem including expected versus actual behavior**:
If any of field has value "No", it does not work with filter query.
**Example**:
_id: 123123, user_id: 123123, processed: Yes, account_type: AA, name: Test One
_id: 123124, user_id: 123124, processed: No, account_type: BA,  name: Test Two
_id: 123125, user_id: 123125, processed: Yes, account_type: CA,  name: Test Three

**Query**: 

{
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "user_id": "123124"
          }
        }
      ],
      "filter": {
        "term": {
          "processed": "no"
        }
      }
    }
  }
}

It return 0 hits. But, if `processed` value is `noo`, it works. 
Same query for field `account_type` with value `AA` works well. 

If number of characters is the problem means, it shouldn't work with `account_type` value `AA`. But it works well for them. Even checked with documentation for reserved keyword but i found nothing for `No`.

**Comment by romseygeek** [comment] 2020-01-06 09:36
I suspect that this may be caused by whatever client you're using to communicate with ES converting your `"no`" to a boolean json value - how are you sending your HTTP requests?

**Comment by romseygeek** [comment] 2020-01-06 09:44
I tried this in a Kibana instance and it returned the expected results:
```
PUT test/_doc/1 
{
  "user_id" : "123123",
  "processed" : "yes",
  "account_type" : "AA",
  "name" : "Test One"
}

PUT test/_doc/2
{
  "user_id" : "123124",
  "processed" : "no",
  "account_type" : "BB",
  "name" : "Test One"
}

PUT test/_doc/3
{
  "user_id" : "123125",
  "processed" : "yes",
  "account_type" : "CC",
  "name" : "Test One"
}

GET test/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "match": { "user_id": "123124" }
        }
      ],
      "filter": {
        "term": { "processed": "no" }
      }
    }
  }
}
```

```
{
  "took" : 4,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 1,
      "relation" : "eq"
    },
    "max_score" : 0.87546873,
    "hits" : [
      {
        "_index" : "test",
        "_type" : "_doc",
        "_id" : "2",
        "_score" : 0.87546873,
        "_source" : {
          "user_id" : "123124",
          "processed" : "no",
          "account_type" : "BB",
          "name" : "Test Two"
        }
      }
    ]
  }
}
```

**Comment by jagansankara** [comment] 2020-01-06 09:52
@romseygeek  I tried in both Kibana Dev console & Postman. Both are returning 0 hits. What's the version of ES you are using? Mine is 7.0.1.

**Comment by romseygeek** [comment] 2020-01-06 09:56
@jagansankara this was on 7.0.0 - can you post the exact steps you took in Kibana?

**Comment by jagansankara** [comment] 2020-01-06 10:23
@romseygeek 
Values in ES: 
_id: 123123, user_id: 123123, processed: Yes, account_type: AA, name: Test One
_id: 123124, user_id: 123124, processed: No, account_type: BA, name: Test Two
_id: 123125, user_id: 123125, processed: Yes, account_type: CA, name: Test Three

**Method 1**:
Searched value "123124" in Kibana dashboard 
Click `Filter` icon to filter `processed` is `"No"`
Return 0 results

**Method 2**:
(tried same query in Postman and Kibana Dev Console
{
    "query": {
        "bool": {
            "must": [
                {
                    "match": {
                        "user_id": "123124"
                    }
                }
            ],
            "filter": {
                "term": {
                    "processed": "no"
                }
            }
        }
    }
}

**Comment by romseygeek** [comment] 2020-01-06 10:47
This may be an issue with indexing then.  Can you detail how you added the docs to ES?  The mappings would also be helpful.

**Comment by jagansankara** [comment] 2020-01-06 11:55
Uploaded through bulk api - curl command
Mapping:
 "processed": {
        "type": "text"
      }

**Comment by romseygeek** [comment] 2020-01-06 11:59
Could you add the exact curl command you used to upload?

**Comment by jagansankara** [comment] 2020-01-06 13:09
Here is the command 
`curl -k -u username:password -XPOST "https://localhost:9400/test_index/_bulk?pretty" --data-binary @SampleData.txt  -H 'Content-Type: application/json; charset=UTF-8'`

**Comment by romseygeek** [comment] 2020-01-06 13:31
I'll need the contents of `SampleData.txt` as well if I'm going to reproduce this.

**Comment by jagansankara** [comment] 2020-01-06 14:03
File content

`{"index":{"_id":"123123"}}
{"user_id":"123123","processed":"Yes","account_type":"AA","name":"Test One"}
{"index":{"_id":"123124"}}
{"user_id":"123124","processed":"No","account_type":"BA","name":"Test Two"}
{"index":{"_id":"123125"}}
{"user_id":"123125","processed":"Yes","account_type":"CA","name":"Test Three"}

`

**Comment by romseygeek** [comment] 2020-01-06 14:43
I can't reproduce this at all, everything works fine when I try this.  Can you post the output of `GET /test-index` - there maybe something funky happening with analysis.

**Comment by jagansankara** [comment] 2020-01-07 07:06
``` json

{
  "test_index" : {
    "aliases" : { },
    "mappings" : {
      "dynamic_templates" : [
        {
          "integers" : {
            "match_mapping_type" : "long",
            "match_pattern" : "regex",
            "mapping" : {
              "type" : "integer"
            }
          }
        },
        {
          "strings" : {
            "match_mapping_type" : "string",
            "match_pattern" : "regex",
            "mapping" : {
              "analyzer" : "autocomplete",
              "fields" : {
                "raw" : {
                  "normalizer" : "sorting",
                  "ignore_above" : 256,
                  "type" : "keyword"
                }
              },
              "search_analyzer" : "nostop",
              "type" : "text"
            }
          }
        }
      ],
      "properties" : {
       "processed" : {
          "type" : "text"
        },
        "user_id" : {
          "type" : "text"
        },
        "name" : {
          "type" : "text"
        },
        "account_type" : {
          "type" : "text",
          "fields" : {
            "raw" : {
              "type" : "keyword",
              "ignore_above" : 256,
              "normalizer" : "sorting"
            }
          },
          "analyzer" : "autocomplete",
          "search_analyzer" : "nostop"
        }
      }
    },
    "settings" : {
      "index" : {
        "refresh_interval" : "1s",
        "number_of_shards" : "3",
        "provided_name" : "test_index",
        "creation_date" : "1577370017776",
        "analysis" : {
          "filter" : {
            "english_stemmer" : {
              "Language" : "english",
              "type" : "stemmer"
            },
            "frenchsnow" : {
              "type" : "snowball",
              "language" : "french"
            },
            "autocomplete" : {
              "token_chars" : [
                "letter",
                "digit"
              ],
              "min_gram" : "3",
              "type" : "ngram",
              "max_gram" : "3"
            },
            "english_stop" : {
              "type" : "stop",
              "stopwords" : "_english_"
            },
            "french_elision" : {
              "type" : "elision",
              "articles" : [
                "l",
                "m",
                "t",
                "qu",
                "n",
                "s",
                "j",
                "d",
                "c",
                "jusqu",
                "quoiqu",
                "lorsqu",
                "puisqu"
              ],
              "articles_case" : "true"
            },
            "nfkc_normalizer" : {
              "name" : "nfkc",
              "type" : "asciifolding"
            },
            "english_possessive_stemmer" : {
              "type" : "stemmer",
              "language" : "possessive_english"
            },
            "french_stemmer" : {
              "Language" : "light_french",
              "type" : "stemmer"
            },
            "my_word_delimiter" : {
              "split_on_numerics" : "false",
              "preserve_original" : "false",
              "catenate_words" : "true",
              "generate_number_parts" : "false",
              "catenate_all" : "true",
              "split_on_case_change" : "false",
              "type" : "word_delimiter_graph",
              "catenate_numbers" : "true",
              "stem_english_possessive" : "true"
            },
            "my_synonym" : {
              "type" : "synonym",
              "lenient" : "true",
              "synonyms" : [
                "pharmasave, drugs, pharma, drug"
              ]
            }
          },
          "char_filter" : {
            "remove_leading_non_alphanum" : {
              "pattern" : "^(\\W|_)+",
              "type" : "pattern_replace",
              "replacement" : ""
            }
          },
          "normalizer" : {
            "sorting" : {
              "filter" : [
                "lowercase",
                "asciifolding"
              ],
              "type" : "custom"
            }
          },
          "analyzer" : {
            "nostop" : {
              "filter" : [
                "lowercase",
                "asciifolding",
                "my_word_delimiter"
              ],
              "char_filter" : [
                "html_strip",
                "remove_leading_non_alphanum"
              ],
              "type" : "custom",
              "stopwords" : "_english_",
              "tokenizer" : "standard"
            },
            "autocomplete" : {
              "filter" : [
                "lowercase",
                "asciifolding",
                "my_word_delimiter"
              ],
              "char_filter" : [
                "html_strip",
                "remove_leading_non_alphanum"
              ],
              "type" : "custom",
              "stopwords" : "_english_",
              "tokenizer" : "standard"
            },
            "default" : {
              "filter" : [
                "lowercase",
                "asciifolding",
                "stop",
                "snowball"
              ],
              "char_filter" : [
                "html_strip"
              ],
              "tokenizer" : "standard"
            }
          }
        },
        "number_of_replicas" : "2",
        "uuid" : "NH89ppkFQ_u6mrv5yaMzOg",
        "version" : {
          "created" : "7000199"
        }
      }
    }
  }
}


```

**Comment by romseygeek** [comment] 2020-01-07 09:09
Got it - your dynamic template is applying the `autocomplete` filter, which uses the default english stopword set.  And `no` is a stopword, so it gets removed.

**Comment by jagansankara** [comment] 2020-01-07 14:48
@romseygeek  Okay, then what should i do now to configure it to accept `no` in `processed` field ? :)

**Comment by romseygeek** [comment] 2020-01-08 12:51
That depends really on how you need to apply dynamic templates elsewhere; in your case I'd suggest re-mapping `processed` as a `keyword` field, rather than `text`, given that you don't really want analysis applied to it.

Seeing as this is a problem with configuration, rather than a bug in ES, I'm going to close the issue - please feel free to ask further questions in our forums at https://discuss.elastic.co/c/elasticsearch/6

**Closed by romseygeek** 2020-01-08 12:51 UTC
