### ISSUE TITLE
Init scripts reports "OK" when Elasticsearch fails to start from bad YAML

### ISSUE THREAD

**Issue by martinb3** [elastic/elasticsearch#19297] opened 2016-07-07 09:30 UTC
Hello! The Chef cookbook for Elasticsearch has received a bug report regarding the packaging of ES, specifically the init scripts and status reporting. Here's the actual report: https://github.com/elastic/cookbook-elasticsearch/issues/483

In short, the user is seeing the init script for Ubuntu 14.04 report "OK" when starting Elasticsearch, even though parsing of the YAML configuration file has failed. Perhaps Elasticsearch needs a 'configtest' akin to the way Apache and Nginx have implemented it, or perhaps the init script just needs improvement to catch when Elasticsearch has exited or failed to start.

**Elasticsearch version**: 2.3.3
**JVM version**: 1.8.0_91
**OS version**: ubuntu 14.04

**Steps to reproduce**:
1. Add `http.cors.allow-origin: *` to elasticsearch.yml
2. Attempt to start the service

**Provide logs (if relevant)**:
The user reporting the issue found this in his logs:

```
Exception in thread "main" SettingsException[Failed to load settings from [elasticsearch.yml]]; nested: ScannerException[while scanning an alias
 in 'reader', line 41, column 25:
    http.cors.allow-origin: *
                            ^
expected alphabetic or numeric character, but found but found

 in 'reader', line 41, column 26:
    http.cors.allow-origin: *
                             ^
];
Likely root cause: while scanning an alias
 in 'reader', line 41, column 25:
    http.cors.allow-origin: *
                            ^
```

**Comment by clintongormley** [comment] 2016-07-07 13:09
I think this is a duplicate of https://github.com/elastic/elasticsearch/issues/12716 and Elasticsearch is failing to return the proper exit code because of the double daemonization

**Comment by clintongormley** [comment] 2016-07-07 13:10
@martinb3 any chance you could try what is suggested https://github.com/elastic/elasticsearch/issues/12716#issuecomment-224799775 and let us know if it fixes your issue?

**Comment by martinb3** [comment] 2016-07-07 13:17
Howdy @clintongormley -- I searched the tracker but didn't find that one -- sorry about that!

**Comment by clintongormley** [comment] 2016-07-07 16:22
@martinb3 no worries - i want to get this one fixed, so would be good to have corroboration

**Comment by jasontedor** [comment] 2016-07-07 18:32
@martinb3 Can you share some more details here? I think on System V init compatible systems we should be okay here but maybe not on systemd systems? I think that Ubuntu 14.04 is a System V init compatible system by default?

The Elasticsearch JVM does successfully start, it just dies during node start because of the malformed configuration file. We do have sleeps in our scripts attempting to detect when this happens and I just tested it on a clean Ubuntu 14.04 install and it did the right thing:

```bash
# cat /etc/elasticsearch/elasticsearch.yml
node.name: test
# purposefully malformed
 cluster.name: test
# service elasticsearch start
 * Starting Elasticsearch Server                                                                    [fail] 
#
```

**Comment by clintongormley** [comment] 2016-07-08 07:30
@jasontedor but does the double daemonization mentioned in #12716 actually make sense? If we remove that, surely we wouldn't need the sleep?

**Comment by jasontedor** [comment] 2016-07-08 09:27
@clintongormley To be clear, the double daemonization needs to be removed and we should just rely on daemonization from the underlying service implementation but we still need a sleep somewhere otherwise in cases like this Elasticsearch will successfully daemonize and later die. The successful daemonization will appear like successful startup, so a sleep is needed to give it time to die if it's going to.

**Comment by lassizci** [comment] 2016-09-06 13:32
Struggling with this as well on systemd system. the problem with `Type=simple` is that there's no mechanism to know whether the service started or not. It has to be found out afterwards with `status`. `ExecStartPost` could have some sleep in which case if ES (hopefully) dies during the sleep, the startup failure would be reported, but then again, arbitary sleeps aren't always reliable. There seems to be at least https://github.com/faljse/SDNotify which would allow to send actual notifications for service `Type=notify`

**Comment by colings86** [comment] 2017-03-31 13:50
@jasontedor Is this still an issue? Could it be closed?

**Comment by jasontedor** [comment] 2017-03-31 14:04
@colings86 Yes, this is still an issue and this should remain open.

**Comment by williamrandolph** [comment] 2019-09-04 19:22
We, and by "we" I mean @jasontedor, changed the systemd service type to `notify`, as @lassizci suggested, in PR #44673. I will try to verify that this change fixes the issue reported here.

**Comment by jasontedor** [comment] 2019-09-05 18:05
Note that that only relates to `systemd`, but not on Sys V init.

**Comment by pugnascotia** [comment] 2022-07-25 14:15
@rjernst is this still an issue? A lot has changed in this area.

**Comment by rjernst** [comment] 2022-07-25 14:49
I'm not sure if this issue was still a problem, but it would have been fixed by the move to Java based CLIs.

**Closed by rjernst** 2022-07-25 14:49 UTC
Labels: >bug, :Delivery/Packaging, Team:Delivery
