### ISSUE TITLE
geo_distance query, performance regression (from 1.7 to 2.2)

### ISSUE THREAD

**Issue by pierrre** [elastic/elasticsearch#16481] opened 2016-02-05 16:49 UTC
I'm currently migrating from Elasticsearch 1.7 to 2.2 and I have a performance issue with the geo_distance query.

My model is simple:
- 20k documents in a type
- each document contains a field with type "array of object" (nested mapping)
- these nested documents contains a "location" field (lat/lon)

I want to filter my root documents by distance.

My search queries:

Elasticsearch 1.7:
```json
{
 "filter": {
   "geo_distance": {
     "distance": "100000m",
     "stores.location": {
       "lat": 48.86,
       "lon": 2.35
     }
   }
 }
}
```

Elasticsearch 2.2:
```json
{
  "query": {
    "bool": {
      "filter": {
        "geo_distance": {
          "distance": "100000m",
          "stores.location": {
            "lat": 48.86,
            "lon": 2.35
          }
        }
      }
    }
  }
}
```

With Elasticsearch 1.7, the response time (took) is around 35ms.
With Elasticsearch 2.2, the response time is around 3700ms.

If I test with random locations, the response time of Elasticsearch 1.7 stay stable. (there is no cached result)

Is there a way to improve performance?

**Comment by nknize** [comment] 2016-02-05 17:45
Can you post your mapping? Showing nested type definitions and all.

**Comment by pierrre** [comment] 2016-02-05 18:17
Of course (I removed non relevant fields):
```json
{  
  "title":{  
    "type":"string",
    "analyzer":"french"
  },
  "stores":{  
    "type":"nested",
    "include_in_parent":true,
    "properties":{  
      "id":{  
        "type":"string",
        "index":"not_analyzed"
      },
      "location":{  
        "type":"geo_point"
      }
    }
  }
}
```
In my documents `stores` is an array of objects.
There are usually 50-200 nested documents per root document.

I didn't use the "nested" query in my previous message, because it doesn't change anything to the performance issue.
But I still need to use "nested" in my case (I have other fields).

**Comment by pierrre** [comment] 2016-02-08 10:11
Even weirder:

I reimplemented the "geo_distance query" with a "script query":
```json
{
  "query": {
    "bool": {
      "filter": {
        "script": {
          "script": "import org.elasticsearch.common.unit.DistanceUnit;\nimport org.elasticsearch.common.geo.GeoDistance;\nfor (storeLocation in doc[\"stores.location\"]) {\n    distance = GeoDistance.ARC.calculate(location.lat, location.lon, storeLocation.lat, storeLocation.lon, DistanceUnit.METERS);\n    if (distance <= storeDistanceMax) {\n        return true;\n    }\n}\nreturn false;",
          "params": {
            "location": {
              "lat": 49.85,
              "lon": 2.35
            },
            "storeDistanceMax": 100000
          }
        }
      }
    }
  },
  "fields": []
}
```

My search took 200ms! (instead of 3700ms for the "geo_distance query")

**Comment by pierrre** [comment] 2016-02-08 10:24
It's getting worse:

I added a "term query" before the "geo_distance query", to restrict the search to 1 hit:
```json
{
  "query": {
    "bool": {
      "filter": {
        "query": {
          "bool": {
            "must": [
              {
                "term": {
                  "_id": "51a89a7c4eb8dd9e41000025"
                }
              },
              {
                "geo_distance": {
                  "distance": "100000m",
                  "stores.location": {
                    "lat": 48.71,
                    "lon": 2.35
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}
```

There is only 1 document with this id.
It takes 500ms.
(there is only 53 sub documents in the "store" field)

**Comment by clintongormley** [comment] 2016-02-08 10:51
@pierrre Could you set the `profile` parameter to `true` and upload the response please?

**Comment by pierrre** [comment] 2016-02-08 11:25
Search:
```json
{
  "query": {
    "bool": {
      "filter": {
        "geo_distance": {
          "distance": "100000m",
          "stores.location": {
            "lat": 49.83,
            "lon": 2.34
          }
        }
      }
    }
  },
  "fields": [],
  "profile": true
}
```

Profile (I removed the hits):
```json
{  
  "took":1880,
  "timed_out":false,
  "_shards":{  
    "total":5,
    "successful":5,
    "failed":0
  },
  "hits":{  
    "total":4701,
    "max_score":0
  },
  "profile":{  
    "shards":[  
      {  
        "id":"[ST0bPIZTSbOP768od67YHA][test-v5][1]",
        "searches":[  
          {  
            "query":[  
              {  
                "query_type":"BooleanQuery",
                "lucene":"+ConstantScore(GeoPointDistanceQueryImpl: field=stores.location: Lower Left: [0.9473075707611631,48.93168471588048] Upper Right: [3.7326924292388366,50.72831528411952])^0.0 #ConstantScore(_type:offer)",
                "time":"4961.247043ms",
                "breakdown":{  
                  "score":74250,
                  "create_weight":285299,
                  "next_doc":461141,
                  "match":0,
                  "build_scorer":1653267115,
                  "advance":0
                },
                "children":[  
                  {  
                    "query_type":"BoostQuery",
                    "lucene":"ConstantScore(GeoPointDistanceQueryImpl: field=stores.location: Lower Left: [0.9473075707611631,48.93168471588048] Upper Right: [3.7326924292388366,50.72831528411952])^0.0",
                    "time":"3305.913181ms",
                    "breakdown":{  
                      "score":19386,
                      "create_weight":12349,
                      "next_doc":0,
                      "match":0,
                      "build_scorer":1652853718,
                      "advance":123164
                    },
                    "children":[  
                      {  
                        "query_type":"GeoPointTermQueryConstantScoreWrapper",
                        "lucene":"GeoPointDistanceQueryImpl: field=stores.location: Lower Left: [0.9473075707611631,48.93168471588048] Upper Right: [3.7326924292388366,50.72831528411952]",
                        "time":"1652.904564ms",
                        "breakdown":{  
                          "score":0,
                          "create_weight":3376,
                          "next_doc":0,
                          "match":0,
                          "build_scorer":1652844406,
                          "advance":56782
                        }
                      }
                    ]
                  },
                  {  
                    "query_type":"ConstantScoreQuery",
                    "lucene":"ConstantScore(_type:offer)",
                    "time":"1.246057000ms",
                    "breakdown":{  
                      "score":0,
                      "create_weight":253447,
                      "next_doc":106307,
                      "match":0,
                      "build_scorer":234222,
                      "advance":99908
                    },
                    "children":[  
                      {  
                        "query_type":"TermQuery",
                        "lucene":"_type:offer",
                        "time":"0.5521730000ms",
                        "breakdown":{  
                          "score":0,
                          "create_weight":244762,
                          "next_doc":62877,
                          "match":0,
                          "build_scorer":166216,
                          "advance":78318
                        }
                      }
                    ]
                  }
                ]
              }
            ],
            "rewrite_time":48665,
            "collector":[  
              {  
                "name":"SimpleTopScoreDocCollector",
                "reason":"search_top_hits",
                "time":"0.1369960000ms"
              }
            ]
          }
        ]
      },
      {  
        "id":"[ST0bPIZTSbOP768od67YHA][test-v5][2]",
        "searches":[  
          {  
            "query":[  
              {  
                "query_type":"BooleanQuery",
                "lucene":"+ConstantScore(GeoPointDistanceQueryImpl: field=stores.location: Lower Left: [0.9473075707611631,48.93168471588048] Upper Right: [3.7326924292388366,50.72831528411952])^0.0 #ConstantScore(_type:offer)",
                "time":"4704.517483ms",
                "breakdown":{  
                  "score":103082,
                  "create_weight":1672361,
                  "next_doc":599497,
                  "match":0,
                  "build_scorer":1566220273,
                  "advance":0
                },
                "children":[  
                  {  
                    "query_type":"BoostQuery",
                    "lucene":"ConstantScore(GeoPointDistanceQueryImpl: field=stores.location: Lower Left: [0.9473075707611631,48.93168471588048] Upper Right: [3.7326924292388366,50.72831528411952])^0.0",
                    "time":"3131.965622ms",
                    "breakdown":{  
                      "score":27974,
                      "create_weight":21414,
                      "next_doc":0,
                      "match":0,
                      "build_scorer":1565840240,
                      "advance":164784
                    },
                    "children":[  
                      {  
                        "query_type":"GeoPointTermQueryConstantScoreWrapper",
                        "lucene":"GeoPointDistanceQueryImpl: field=stores.location: Lower Left: [0.9473075707611631,48.93168471588048] Upper Right: [3.7326924292388366,50.72831528411952]",
                        "time":"1565.911210ms",
                        "breakdown":{  
                          "score":0,
                          "create_weight":8763,
                          "next_doc":0,
                          "match":0,
                          "build_scorer":1565832122,
                          "advance":70325
                        }
                      }
                    ]
                  },
                  {  
                    "query_type":"ConstantScoreQuery",
                    "lucene":"ConstantScore(_type:offer)",
                    "time":"3.956648000ms",
                    "breakdown":{  
                      "score":0,
                      "create_weight":1627981,
                      "next_doc":131485,
                      "match":0,
                      "build_scorer":183439,
                      "advance":124196
                    },
                    "children":[  
                      {  
                        "query_type":"TermQuery",
                        "lucene":"_type:offer",
                        "time":"1.889547000ms",
                        "breakdown":{  
                          "score":0,
                          "create_weight":1614342,
                          "next_doc":70688,
                          "match":0,
                          "build_scorer":110984,
                          "advance":93533
                        }
                      }
                    ]
                  }
                ]
              }
            ],
            "rewrite_time":64977,
            "collector":[  
              {  
                "name":"SimpleTopScoreDocCollector",
                "reason":"search_top_hits",
                "time":"0.1800850000ms"
              }
            ]
          }
        ]
      },
      {  
        "id":"[ST0bPIZTSbOP768od67YHA][test-v5][0]",
        "searches":[  
          {  
            "query":[  
              {  
                "query_type":"BooleanQuery",
                "lucene":"+ConstantScore(GeoPointDistanceQueryImpl: field=stores.location: Lower Left: [0.9473075707611631,48.93168471588048] Upper Right: [3.7326924292388366,50.72831528411952])^0.0 #ConstantScore(_type:offer)",
                "time":"5089.745722ms",
                "breakdown":{  
                  "score":90465,
                  "create_weight":358410,
                  "next_doc":621934,
                  "match":0,
                  "build_scorer":1695828128,
                  "advance":0
                },
                "children":[  
                  {  
                    "query_type":"BoostQuery",
                    "lucene":"ConstantScore(GeoPointDistanceQueryImpl: field=stores.location: Lower Left: [0.9473075707611631,48.93168471588048] Upper Right: [3.7326924292388366,50.72831528411952])^0.0",
                    "time":"3391.571303ms",
                    "breakdown":{  
                      "score":24217,
                      "create_weight":17164,
                      "next_doc":0,
                      "match":0,
                      "build_scorer":1695648631,
                      "advance":159863
                    },
                    "children":[  
                      {  
                        "query_type":"GeoPointTermQueryConstantScoreWrapper",
                        "lucene":"GeoPointDistanceQueryImpl: field=stores.location: Lower Left: [0.9473075707611631,48.93168471588048] Upper Right: [3.7326924292388366,50.72831528411952]",
                        "time":"1695.721428ms",
                        "breakdown":{  
                          "score":0,
                          "create_weight":4688,
                          "next_doc":0,
                          "match":0,
                          "build_scorer":1695642225,
                          "advance":74515
                        }
                      }
                    ]
                  },
                  {  
                    "query_type":"ConstantScoreQuery",
                    "lucene":"ConstantScore(_type:offer)",
                    "time":"1.275482000ms",
                    "breakdown":{  
                      "score":0,
                      "create_weight":313628,
                      "next_doc":105851,
                      "match":0,
                      "build_scorer":93796,
                      "advance":195599
                    },
                    "children":[  
                      {  
                        "query_type":"TermQuery",
                        "lucene":"_type:offer",
                        "time":"0.5666080000ms",
                        "breakdown":{  
                          "score":0,
                          "create_weight":304105,
                          "next_doc":52834,
                          "match":0,
                          "build_scorer":42238,
                          "advance":167431
                        }
                      }
                    ]
                  }
                ]
              }
            ],
            "rewrite_time":66164,
            "collector":[  
              {  
                "name":"SimpleTopScoreDocCollector",
                "reason":"search_top_hits",
                "time":"0.1565940000ms"
              }
            ]
          }
        ]
      },
      {  
        "id":"[ST0bPIZTSbOP768od67YHA][test-v5][3]",
        "searches":[  
          {  
            "query":[  
              {  
                "query_type":"BooleanQuery",
                "lucene":"+ConstantScore(GeoPointDistanceQueryImpl: field=stores.location: Lower Left: [0.9473075707611631,48.93168471588048] Upper Right: [3.7326924292388366,50.72831528411952])^0.0 #ConstantScore(_type:offer)",
                "time":"4168.444183ms",
                "breakdown":{  
                  "score":112480,
                  "create_weight":1390519,
                  "next_doc":651504,
                  "match":0,
                  "build_scorer":1387739181,
                  "advance":0
                },
                "children":[  
                  {  
                    "query_type":"BoostQuery",
                    "lucene":"ConstantScore(GeoPointDistanceQueryImpl: field=stores.location: Lower Left: [0.9473075707611631,48.93168471588048] Upper Right: [3.7326924292388366,50.72831528411952])^0.0",
                    "time":"2775.107749ms",
                    "breakdown":{  
                      "score":30077,
                      "create_weight":21344,
                      "next_doc":0,
                      "match":0,
                      "build_scorer":1387401154,
                      "advance":178740
                    },
                    "children":[  
                      {  
                        "query_type":"GeoPointTermQueryConstantScoreWrapper",
                        "lucene":"GeoPointDistanceQueryImpl: field=stores.location: Lower Left: [0.9473075707611631,48.93168471588048] Upper Right: [3.7326924292388366,50.72831528411952]",
                        "time":"1387.476434ms",
                        "breakdown":{  
                          "score":0,
                          "create_weight":8741,
                          "next_doc":0,
                          "match":0,
                          "build_scorer":1387392110,
                          "advance":75583
                        }
                      }
                    ]
                  },
                  {  
                    "query_type":"ConstantScoreQuery",
                    "lucene":"ConstantScore(_type:offer)",
                    "time":"3.442750000ms",
                    "breakdown":{  
                      "score":0,
                      "create_weight":1345801,
                      "next_doc":142323,
                      "match":0,
                      "build_scorer":180087,
                      "advance":139750
                    },
                    "children":[  
                      {  
                        "query_type":"TermQuery",
                        "lucene":"_type:offer",
                        "time":"1.634789000ms",
                        "breakdown":{  
                          "score":0,
                          "create_weight":1336059,
                          "next_doc":76175,
                          "match":0,
                          "build_scorer":114883,
                          "advance":107672
                        }
                      }
                    ]
                  }
                ]
              }
            ],
            "rewrite_time":43438,
            "collector":[  
              {  
                "name":"SimpleTopScoreDocCollector",
                "reason":"search_top_hits",
                "time":"0.1943090000ms"
              }
            ]
          }
        ]
      },
      {  
        "id":"[ST0bPIZTSbOP768od67YHA][test-v5][4]",
        "searches":[  
          {  
            "query":[  
              {  
                "query_type":"BooleanQuery",
                "lucene":"+ConstantScore(GeoPointDistanceQueryImpl: field=stores.location: Lower Left: [0.9473075707611631,48.93168471588048] Upper Right: [3.7326924292388366,50.72831528411952])^0.0 #ConstantScore(_type:offer)",
                "time":"5621.826671ms",
                "breakdown":{  
                  "score":105805,
                  "create_weight":230198,
                  "next_doc":612438,
                  "match":0,
                  "build_scorer":1873433238,
                  "advance":0
                },
                "children":[  
                  {  
                    "query_type":"BoostQuery",
                    "lucene":"ConstantScore(GeoPointDistanceQueryImpl: field=stores.location: Lower Left: [0.9473075707611631,48.93168471588048] Upper Right: [3.7326924292388366,50.72831528411952])^0.0",
                    "time":"3746.271286ms",
                    "breakdown":{  
                      "score":28564,
                      "create_weight":11564,
                      "next_doc":0,
                      "match":0,
                      "build_scorer":1873000894,
                      "advance":170871
                    },
                    "children":[  
                      {  
                        "query_type":"GeoPointTermQueryConstantScoreWrapper",
                        "lucene":"GeoPointDistanceQueryImpl: field=stores.location: Lower Left: [0.9473075707611631,48.93168471588048] Upper Right: [3.7326924292388366,50.72831528411952]",
                        "time":"1873.059393ms",
                        "breakdown":{  
                          "score":0,
                          "create_weight":3611,
                          "next_doc":0,
                          "match":0,
                          "build_scorer":1872983462,
                          "advance":72320
                        }
                      }
                    ]
                  },
                  {  
                    "query_type":"ConstantScoreQuery",
                    "lucene":"ConstantScore(_type:offer)",
                    "time":"1.173706000ms",
                    "breakdown":{  
                      "score":0,
                      "create_weight":199370,
                      "next_doc":137624,
                      "match":0,
                      "build_scorer":234299,
                      "advance":124913
                    },
                    "children":[  
                      {  
                        "query_type":"TermQuery",
                        "lucene":"_type:offer",
                        "time":"0.4775000000ms",
                        "breakdown":{  
                          "score":0,
                          "create_weight":188244,
                          "next_doc":75295,
                          "match":0,
                          "build_scorer":120317,
                          "advance":93644
                        }
                      }
                    ]
                  }
                ]
              }
            ],
            "rewrite_time":44649,
            "collector":[  
              {  
                "name":"SimpleTopScoreDocCollector",
                "reason":"search_top_hits",
                "time":"0.1850390000ms"
              }
            ]
          }
        ]
      }
    ]
  }
}
```

I can't use "profile" with Elasticsearch 1.7, but my query is:
```json
{
  "filter": {
    "geo_distance": {
      "distance": "100000m",
      "stores.location": {
        "lat": 49.83,
        "lon": 2.34
      }
    }
  },
  "fields": []
}
```

**Comment by clintongormley** [comment] 2016-02-08 11:30
@pierrre thanks. btw - did you reindex your geo-points in 2.2, or reuse geo-points from an earlier index?

**Comment by pierrre** [comment] 2016-02-08 12:40
@clintongormley yes, I created a new index (it's a new Elasticsearch instance), and reindexed all my data.

I also observe the same regression with the "geo_bounding_box" and "geo_distance_range" queries.

**Comment by jimferenczi** [comment] 2016-02-08 13:21
> My model is simple: 20k documents in a type

@pierre is it the total number of documents with a field named `stores.location` ? Do you have other types with the same field name in your index ? What is the total number of documents in this index (20k ?) ?

**Comment by pierrre** [comment] 2016-02-08 13:30
> is it the total number of documents with a field named stores.location ?

@jimferenczi yes, there are 20k root documents with the field `stores.location`.
There are between 50-200 documents in each `stores`fields. (sometimes more)

> Do you have other types with the same field name in your index ?

No, there is only 1 type that uses `stores` & `stores.location` (in the mapping).
I checked with GET `myindex/_mapping`.

> What is the total number of documents in this index (20k ?) ?

GET `myindex/_count` returns 207322.

**Comment by clintongormley** [comment] 2016-02-08 14:39
I've tried this out locally, build an index with 1 million random lat/lon points written in 2.1.1 and in a new index in 2.2.0.  Also added in 50 nested docs in each doc, and using the following settings/mappings:

    PUT x
    {
      "settings": {
        "index.number_of_shards": 1,
        "index.queries.cache.type": "none"
      },
      "mappings": {
        "t": {
          "properties": {
            "loc": {
              "type": "geo_point"
            },
            "nested": {
              "type": "nested",
              "properties": {
                "foo": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }

(note I've disabled caching so that that doesn't interfere with the measurements)

Then I query it like this:

    GET x/t/_search?size=1
    {
      "query": {
        "bool": {
          "must": {
            "geo_distance": {
              "distance": "10000km",
              "loc": {
                "lat": 0,
                "lon": 0
              }
            }
          }
        }
      }
    }

Performance for v1 geo-points is pretty much the same whatever the distance (> distance == more matching docs).  V2 varies greatly depending on how many docs match, eg for a distance of "10000km" it is about the same as v1, eg 1000ms, for eg "10km" this drops to eg 16ms.

So things seem to be working as expected, with v2 much faster than v1, even with the nested docs.

@pierrre are you running this on eg your laptop?  v1 distance calculations are memory based, so all geopoints get loaded onto your heap.  v2 calculations use the index so it is important to have enough file system cache (and use fast disks) to get best performance.  I wonder if you're running this in an unrealistic environment, eg laptop with little free memory for file system caching?

**Comment by pierrre** [comment] 2016-02-08 14:53
@clintongormley in my mapping, the location field is in a nested documents: https://github.com/elastic/elasticsearch/issues/16481#issuecomment-180479677

I'll try to write a script to create the index/add data.

> are you running this on eg your laptop? v1 distance calculations are memory based, so all geopoints get loaded onto your heap. v2 calculations use the index so it is important to have enough file system cache (and use fast disks) to get best performance. I wonder if you're running this in an unrealistic environment, eg laptop with little free memory for file system caching?

Yes I run my test on a laptop:
- Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz (max 3.3Ghz), 4 cores, 2 threads per core
- 8GB RAM
- SSD Samsung 840

I also use the default Elasticsearch config: -Xms256m -Xmx1g
Should I increase the memory usage?

**Comment by clintongormley** [comment] 2016-02-08 14:57
> in my mapping, the location field is in a nested documents

But you're querying it at the root level, because I don't see a nested query anywhere?

> Should I increase the memory usage?

No, that's the point.  V2 is in your file system cache, NOT the ES heap, so if you don't have much free space for caching, then it'll need to hit disk all the time.

**Comment by clintongormley** [comment] 2016-02-08 14:58
> But you're querying it at the root level, because I don't see a nested query anywhere?

OK so the difference here is multiple geopoints per field at the root level, I'll try that.

**Comment by pierrre** [comment] 2016-02-08 15:00
> >in my mapping, the location field is in a nested documents

> But you're querying it at the root level, because I don't see a nested query anywhere?

In my queries, I need a nested query (there are other fields in my nesteds documents).
But I've got a performance issue even if I don't use a nested query.

**Comment by clintongormley** [comment] 2016-02-08 15:39
OK, with 100,000 docs, each with 50 random geopoints, v1 takes about 2 seconds for me, regardless of how many docs match.  v2 varies dramatically with the number of docs that match, eg if i set the distance to 10km (5 docs) it takes 13ms, for 100km (751 docs) it takes 80ms, for 1000km (54,747 docs) it takes 2,200ms, and for 10000km (88,551 docs) it took 100 seconds!

The times for v2 with a geo-bounding-box covering most of the earth was better, but still 10-15x slower than v1.  @nknize over to you!

**Comment by pierrre** [comment] 2016-02-08 16:49
Here is a script (Go) to reproduce the issue: https://gist.github.com/pierrre/1b95f47d25d30e03316c

**Comment by nknize** [comment] 2016-02-08 18:26
Thanks for the reproduction @pierrre. There's an issue with multiple geo-fields in Lucene 5.4.1. I have a fix that will be available in the ES 2.2.1 release.

**Comment by pierrre** [comment] 2016-02-08 20:30
Lucene issue: https://issues.apache.org/jira/browse/LUCENE-7018

**Comment by nknize** [comment] 2016-02-09 04:35
update: feature branch cut. Bug fix back ported. 5.5 will be cut on Wed. There are a few other relational fixes I'm going to back port to 5.4.2. Will keep this issue updated when 5.4.2 is released.

**Comment by nknize** [comment] 2016-02-12 18:26
@pierrre with the release of 5.5 and 2.3 right around the corner we have decided to forgo fixing this in 2.2.x. This bugfix, along with other encoding optimizations, will be available in the 2.3 release coming real soon.

**Comment by pierrre** [comment] 2016-02-12 18:42
OK, thank you.

**Comment by pierrre** [comment] 2016-02-12 21:18
Any idea of ETA for Elasticsearch 2.3.0? 1 week? 1 month? When it's done? :D

**Comment by nknize** [comment] 2016-02-12 21:22
Should be more information coming out at Elasticon. I defer to @clintongormley

**Comment by clintongormley** [comment] 2016-02-13 12:02
it'll definitely be out before 2.3.1 :)

**Comment by clintongormley** [comment] 2016-02-13 13:33
Closed by https://github.com/elastic/elasticsearch/pull/16615

**Closed by clintongormley** 2016-02-13 13:33 UTC
Labels: :Geo, bug, v2.3.0

**Comment by jweber** [comment] 2016-03-12 21:29
My apologies if this isn't the right place to comment on this, but I wanted to mention that we are seeing similar poor performance with `geo_distance` queries in 2.2.0 but on documents without nested collections of geopoints. I [commented on a post](https://discuss.elastic.co/t/slower-geo-distance-queries-in-2-2/41655/4) in the Elasticsearch forums with this data but I also wanted to add it here to increase visibility.

I also tried [the script based approach](https://github.com/elastic/elasticsearch/issues/16481#issuecomment-181288953) that @pierrre performed and found it to return results faster than the equivalent `geo_distance` but under load started encountering shard errors using it.

Here's the comment I posted on the forums:

----

I've definitely encountered this issue as well and are able to recreate it with test data. The following comparisons were performed against v2.1.2, v2.2.0 and 5.0.0 (built from source).

The test data is 6 million documents with random locations on the following index (single shard, query cache disabled). I'm running Elasticsearch with the stock configs on my development machine.

	{
	  "test": {
	    "mappings": {
	      "document": {
	        "properties": {
	          "id": {
	            "type": "integer"
	          },
	          "location": {
	            "type": "geo_point",
	            "lat_lon": true
	          }
	        }
	      }
	    }
	  }
	}
	
The `geo_distance` queries look like:

	{
	  "query": {
	    "bool": {
	      "filter": {
	        "geo_distance": {
	          "distance": "100mi",
	          "location": "[lat], [lon]"
	        }
	      }
	    }
	  }
	}

	
Here are the average times when performing the same 100 `geo_distance` searches against the different Elasticsearch versions: 

	Radius      2.1.2       2.2.0       5.0.0
	1mi         256ms       1ms         2ms
	10mi        206ms       10ms        2ms
	30mi        236ms       36ms        3ms
	50mi        252ms       277ms       40ms
	100mi       258ms       461ms       74ms
	250mi       241ms       2,088ms     315ms
	500mi       227ms       3,534ms     643ms
	1000mi      223ms       943ms       339ms
	2000mi      280ms       754ms       683ms
	
I was also curious about bounding box performance, so I ran the same queries using a bounding box that circumbscribes the diameter of the `geo_distance` query:

	            2.1.2       2.2.0       5.0.0
	1mi         211ms       23ms        9ms
	10mi        217ms       72ms        13ms
	30mi        221ms       60ms        18ms
	50mi        221ms       91ms        23ms
	100mi       220ms       89ms        32ms
	250mi       223ms       130ms       54ms
	500mi       231ms       168ms       81ms
	1000mi      231ms       156ms       96ms
	2000mi      226ms       143ms       100ms
	
The slower queries for 2.2.0 and 5.0.0 always have the largest matching count of documents, so queries over areas with lower matching documents perform quickly.
	
I'm not too sure what to think about the v2.2.0 performance at 250mi and 500mi, but it's definitely not an option for us to run those searches. The next version looks to be an improvement over 2.2.0 but still lags behind 2.1.2 with regards to larger radius searches.

**Comment by cdonnellytx** [comment] 2016-03-22 00:32
We are also seeing poor performance with documents indexed on 2.2.1 (as opposed to a preexisting index created on 1.7.3 prior to upgrade).

It looks like this was closed because 2.3.0 was slated to be released sometime in February, but it's been over a month and 2.3.0 hasn't been released, nor can I find any documentation on when it will be released.

Is there a workaround on 2.2 where you can tell Elasticsearch to index using the old format? Or are the only workarounds the script / not upgrading at this time?

**Comment by jweber** [comment] 2016-03-24 16:54
We've not been able to find an adequate workaround for this issue on 2.2.0. The script option, while performing better than using geo_distance queries, still does not give acceptable performance. I ran the same performance tests against the current 2.3.0 branch and it looks like that will in fact resolve this issue. It would be nice to have an updated estimate on when 2.3.0 will be released as 2.2.x does not perform well enough in these scenarios for us to use.

**Comment by tmatei** [comment] 2016-03-29 23:34
I've encountered the same issue and I'm running 2.2.1

**Comment by jweber** [comment] 2016-03-30 00:28
@cdonnellytx: We ended up creating a new index in 2.2.0 using the following setting, which treats the index as being created using 2.1.2:

**index.version.created: 2010299**

This has allowed us to stay on 2.2.0 but not have the geospatial performance issues of using the 2.2.0 index.

**Comment by pierrre** [comment] 2016-03-30 18:13
https://www.elastic.co/blog/elasticsearch-2-3-0-and-2-2-2-released?blade=tw
