### ISSUE TITLE
Remove types?

### ISSUE THREAD

**Issue by synhershko** [elastic/elasticsearch#23899] opened 2017-04-04 16:12 UTC
This may be a bit controversial perhaps, but I'd like to propose types to be removed in a future major release.

Historically, types were useful for separating documents with different structure within indexes. However, in recent versions this practically no longer holds - different document types cannot share the same field name if their mappings don't match.

In addition the only manageable units in Elasticsearch are documents and indexes. You can add and delete them. You cannot manage types. As such, the usual recommendation I give is to maintain an index per type - since usually when there are several types involved their sizes and SLAs are different, and thus different configurations for replication, retention etc are required anyway. If not now then in the future.

With Elasticsearch slowly moving to index-level and even cluster-level sharding (with cross-cluster search), and with index sizes only growing in real-world systems - I think the chances of types actually being useful anywhere are now close to zero, and different types of documents are better separated on an index level.

At this point, IMO types are just an unnecessary noise for the majority of systems. We can certainly live without them, type less (pun intended) and manage different types of data using separate indexes. This will also avoid various not-uncommon pitfalls (e.g. large number of fields in mapping).

Only feature affected will be parent/child, and I'm sure there could be an easy solution there (I'd probably go with an "invisible" types for parents and children).

WDYT?

**Comment by dadoonet** [comment] 2017-04-04 16:14
It's a duplicate of #15613 IMO. I'm closing but feel free to comment there or reopen.

**Closed by dadoonet** 2017-04-04 16:14 UTC

**Comment by synhershko** [comment] 2017-04-04 16:15
Oh, well I guess great minds think alike ;) I'll paste my thoughts there then
