### ISSUE TITLE
[CI] XPackRestIT.test {p0=analytics/top_metrics/sort by double field}"

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#52418] opened 2020-02-17 14:32 UTC
This doesn't reproduce for me.

```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:integTestRunner' --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=analytics/top_metrics/sort by double field}" \
  -Dtests.seed=8F62667C97A80AFD \
  -Dtests.security.manager=true \
  -Dtests.locale=ca-ES \
  -Dtests.timezone=America/Indiana/Winamac \
  -Dcompiler.java=13 \
  -Dtests.rest.blacklist=getting_started/10_monitor_cluster_health/*

REPRODUCE WITH: ./gradlew ':x-pack:plugin:integTestRunner' --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=analytics/top_metrics/sort by double field}" \
  -Dtests.seed=8F62667C97A80AFD \
  -Dtests.security.manager=true \
  -Dtests.locale=ca-ES \
  -Dtests.timezone=America/Indiana/Winamac \
  -Dcompiler.java=13 \
  -Dtests.rest.blacklist=getting_started/10_monitor_cluster_health/*
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_RUNTIME_JAVA=openjdk14,nodes=general-purpose/516/console
[7.6.1] https://gradle-enterprise.elastic.co/s/55iyxj2344cy4
[7.7.0] https://gradle-enterprise.elastic.co/s/25tx76dtr3x5a 
[7.6.1] https://gradle-enterprise.elastic.co/s/66qupjuezmduk
[7.7.0] https://gradle-enterprise.elastic.co/s/qse4aijncstnk
https://gradle-enterprise.elastic.co/s/un6vbajxobhja

```
java.lang.AssertionError: Failure at [analytics/top_metrics:91]: aggregations.tm.top.0.metrics.v didn't match expected value:
aggregations.tm.top.0.metrics.v: expected Double [2.718280076980591] but was Double [2.0]

	at __randomizedtesting.SeedInfo.seed([8F62667C97A80AFD:73659A639546705]:0)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:405)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:382)
```

**Comment by astefan** [comment] 2020-02-17 16:55
And another one, not on the same test, but with the same assertion message.


https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=centos-7&&immutable/580/console
[7.6.1] https://gradle-enterprise.elastic.co/s/npuk2azzhrxr6 
[7.7.0] https://gradle-enterprise.elastic.co/s/qqdq6evn3npwg 
[7.6.1] https://gradle-enterprise.elastic.co/s/qm56ztvp3sgsu 
[7.7.0] https://gradle-enterprise.elastic.co/s/dymi5ydxvhwac
https://gradle-enterprise.elastic.co/s/3nrjvc4sj7y6e

```
09:31:05 org.elasticsearch.xpack.test.rest.XPackRestIT > test {p0=analytics/top_metrics/sort by keyword field fails} FAILED
09:31:05     java.lang.AssertionError: Failure at [analytics/top_metrics:167]: expected [400] status code but api [search] returned [200 OK] [---
09:31:05     took: 17
09:31:05     timed_out: false
09:31:05     _shards:
09:31:05       total: 2
09:31:05       successful: 1
09:31:05       skipped: 0
09:31:05       failed: 1
09:31:05       failures:
09:31:05       - shard: 0
09:31:05         index: "test"
09:31:05         node: "J1HzqT__RLOf0s1YnVh3Gw"
09:31:05         reason:
09:31:05           type: "illegal_argument_exception"
09:31:05           reason: "error building sort for field [s.keyword] of type [keyword] in index\
09:31:05             \ [test]: only supported on numeric fields"
09:31:05           caused_by:
09:31:05             type: "illegal_argument_exception"
09:31:05             reason: "only supported on numeric fields"
09:31:05     hits:
09:31:05       total:
09:31:05         value: 0
09:31:05         relation: "eq"
09:31:05       max_score: null
09:31:05       hits: []
09:31:05     aggregations:
09:31:05       tm:
09:31:05         top: []
09:31:05     ]
09:31:05         at __randomizedtesting.SeedInfo.seed([C0B2FAC67C4999DB:48E6C51CD2B5F423]:0)
09:31:05         at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:405)
09:31:05         at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:382)
09:31:05         at jdk.internal.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
09:31:05         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:31:05         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
09:31:05         at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1754)
09:31:05         at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:942)
09:31:05         at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:978)
09:31:05         at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:992)
09:31:05         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
09:31:05         at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
09:31:05         at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
09:31:05         at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
09:31:05         at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
09:31:05         at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
09:31:05         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
09:31:05         at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:370)
09:31:05         at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:819)
09:31:05         at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:470)
09:31:05         at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:951)
09:31:05         at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:836)
09:31:05         at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:887)
09:31:05         at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:898)
09:31:05         at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
09:31:05         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
09:31:05         at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
09:31:05         at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
09:31:05         at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
09:31:05         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
09:31:05         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
09:31:05         at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
09:31:05         at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
09:31:05         at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
09:31:05         at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
09:31:05         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
09:31:05         at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:370)
09:31:05         at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:826)
09:31:05         at java.base/java.lang.Thread.run(Thread.java:834)
09:31:05 
09:31:05         Caused by:
09:31:05         java.lang.AssertionError: expected [400] status code but api [search] returned [200 OK] [---
09:31:05         took: 17
09:31:05         timed_out: false
09:31:05         _shards:
09:31:05           total: 2
09:31:05           successful: 1
09:31:05           skipped: 0
09:31:05           failed: 1
09:31:05           failures:
09:31:05           - shard: 0
09:31:05             index: "test"
09:31:05             node: "J1HzqT__RLOf0s1YnVh3Gw"
09:31:05             reason:
09:31:05               type: "illegal_argument_exception"
09:31:05               reason: "error building sort for field [s.keyword] of type [keyword] in index\
09:31:05                 \ [test]: only supported on numeric fields"
09:31:05               caused_by:
09:31:05                 type: "illegal_argument_exception"
09:31:05                 reason: "only supported on numeric fields"
09:31:05         hits:
09:31:05           total:
09:31:05             value: 0
09:31:05             relation: "eq"
09:31:05           max_score: null
09:31:05           hits: []
09:31:05         aggregations:
09:31:05           tm:
09:31:05             top: []
09:31:05         ]
09:31:05             at org.junit.Assert.fail(Assert.java:88)
09:31:05             at org.elasticsearch.test.rest.yaml.section.DoSection.execute(DoSection.java:255)
09:31:05             at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:398)
09:31:05             ... 37 more
```

**Comment by henningandersen** [comment] 2020-02-18 09:40
This failure is similar enough that I think it belongs here though it is `sort by long field` that fails:

```
aggregations.tm.top.0.metrics.v didn't match expected value:
aggregations.tm.top.0.metrics.v: expected Double [2.718280076980591] but was Double [2.0]
```

https://gradle-enterprise.elastic.co/s/7vmnvu7w63qlq/tests/fcijb24gqtmnc-mgmu5sm5iwtvs

Notice that the search result indicates that the index had two shards:

```
      "_shards" : {
        "total" : 2,
        "successful" : 2,
```

which indicates an overlap to #52409.

**Comment by henningandersen** [comment] 2020-02-18 09:44
This reproduces using:

```
./gradlew ':x-pack:plugin:integTestRunner' --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=analytics/top_metrics/sort by long field}"   -Dtests.seed=339A8B46489F00E1   -Dtests.security.manager=true   -Dtests.jvm.argline="-XX:-UseConcMarkSweepGC -XX:-UseSerialGC -XX:+UseG1GC"   -Dtests.locale=fi   -Dtests.timezone=Europe/Stockholm   -Dcompiler.java=13   -Dtests.rest.blacklist=getting_started/10_monitor_cluster_health/*
```

**Comment by henningandersen** [comment] 2020-02-18 11:37
Sort by score also fails locally using:

```
  - skip:
      version: "all"
      reason: "AwaitsFix https://github.com/elastic/elasticsearch/issues/52409"
```

**Comment by rjernst** [comment] 2020-02-19 23:10
Another case of this, with scaled float field:
https://gradle-enterprise.elastic.co/s/vmzl2lg6vdp7o/console-log?task=:x-pack:plugin:integTestRunner

**Comment by nik9000** [comment] 2020-02-20 20:13
Fixed in #52516.

**Comment by rjernst** [comment] 2020-02-20 21:10
@nik9000 Your fix targets a top_metric unit test, but the test failure here, and those that were muted, were rest tests...I think this needs to be reopened?

**Comment by henningandersen** [comment] 2020-02-21 10:55
Reopening since the tests are still muted (and looks like the wrong issue was closed).

**Comment by nik9000** [comment] 2020-02-21 11:09
> Reopening since the tests are still muted (and looks like the wrong issue was closed).

Sorry about that! I had my wires crossed.

**Closed** 2020-02-24 18:02 UTC
Labels: :Analytics/Aggregations, >test-failure
