### ISSUE TITLE
[CI] RRFRankMultiShardIT testMultiBM25WithAggregation failing

### ISSUE THREAD

**Issue by ChrisHegarty** [elastic/elasticsearch#101125] opened 2023-10-19 11:32 UTC
**Build scan:**
https://gradle-enterprise.elastic.co/s/mmnm6izluny2a/tests/:x-pack:plugin:rank-rrf:internalClusterTest/org.elasticsearch.xpack.rank.rrf.RRFRankMultiShardIT/testMultiBM25WithAggregation
**Reproduction line:**
```
./gradlew ':x-pack:plugin:rank-rrf:internalClusterTest' --tests "org.elasticsearch.xpack.rank.rrf.RRFRankMultiShardIT.testMultiBM25WithAggregation" -Dtests.seed=47B259993D35973F -Dtests.locale=lt -Dtests.timezone=America/Campo_Grande -Druntime.java=21
```

**Applicable branches:**
8.11

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.rank.rrf.RRFRankMultiShardIT&tests.test=testMultiBM25WithAggregation
**Failure excerpt:**
```
org.junit.ComparisonFailure: expected:<term 49[2]> but was:<term 49[9]>

  at __randomizedtesting.SeedInfo.seed([47B259993D35973F:ABE0714FE376D557]:0)
  at org.junit.Assert.assertEquals(Assert.java:115)
  at org.junit.Assert.assertEquals(Assert.java:144)
  at org.elasticsearch.xpack.rank.rrf.RRFRankMultiShardIT.testMultiBM25WithAggregation(RRFRankMultiShardIT.java:659)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by pmpailis** [comment] 2024-09-06 15:47
Can't reproduce it locally no matter the number of iters or releases :( 

Also, looking into the test's history it seems that we have only 1 similar failure in the last 3 months on `8.14` on June 30th. 


Baed on the error message
```
org.junit.ComparisonFailure: expected:<term 49[2]> but was:<term 49[9]>
```
we can add some additional assertions in the test to help us better understand if it's the score that is off, if there are any issues with indexing/retrieving all docs, etc. 

However, given the rework that we're doing for the rrf retriever, and that, AFAICT, there won't be another 8.14 release, I would suggest to close this and revisit if it resurfaces.

**Comment by pmpailis** [comment] 2024-09-06 16:20
Looking at the test again, it seems that we index the values `term [n]` where `0<=n<=1000` on a `text` field. We then use a `term` query on just the arithmetic part (e.g. `500`) and a custom `boost` to force ranking. 

Maybe this is a weird edge case, where due to different doc routing, some shards may end up having significant more documents so the `idf` component for the same `text` field might differ significantly in the `query_then_fetch` search type.  Given that we have a single occurrence of the arithmetic part on the index, the idf alone could affect scoring significantly, outweighing the `boost` factor we provide. 

I'll look to update the tests to use a constant score query instead, so that we can enforce ranking independently of shard routing and idf scores.

**Closed** 2024-11-05 21:53 UTC
Labels: >test, >test-failure, :Search Relevance/Ranking, low-risk, Team:Search Relevance
