### ISSUE TITLE
Geodistance - between two points

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#19525] opened 2016-07-20 21:36 UTC
It'd be schway if we had a geodistance query that works between two points, ie show me the distance between `33.8688° S, 151.2093°` and `41.3851° N, 2.1734° E`.

Inspired by [this](https://discuss.elastic.co/t/json-array-of-geo-locations-get-distance-of-all-the-location-in-json-array-of-a-document/55974) forum post.

**Comment by colings86** [comment] 2016-07-21 08:58
I'm not sure I understand what this query is supposed to do? If its supposed to score documents based on the distance between a fixed point and a point in the document then we already have this in the `decay` function of the `function_score` query. If not, could you provide more details as to what you would expect the inputs to the query to be and what the query would score against in the document?

**Comment by markwalkom** [comment] 2016-07-21 09:16
I want to measure how far apart two geopoints are.
No scoring, just "it's X KM from A to B".

**Comment by colings86** [comment] 2016-07-21 09:22
I might be missing something here but that's not a query? A query needs to make some selection of documents based on some criteria in those documents. Calculating a distance between two points and outputting it is a function. The bit I'm confused about here is how this related to a geo-distance query as mentioned in your original post? Are you just after a convenience method that can be used in scripts/function_score/something else?

**Comment by markwalkom** [comment] 2016-07-21 09:30
True, it's not a query and it is a simplicity thing. But it'd be useful.

**Comment by clintongormley** [comment] 2016-07-21 12:17
Duplicate of https://github.com/elastic/elasticsearch/issues/17506

**Closed by clintongormley** 2016-07-21 12:17 UTC
Labels: :Geo, discuss, enhancement
