### ISSUE TITLE
[CI] SearchQueryIT#testQuotedQueryStringWithBoost failing

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#43144] opened 2019-06-12 09:31 UTC
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=oraclelinux-6/32/console

https://gradle.com/s/zw3nmldyl5kn2

Relevant log lines:

```
org.elasticsearch.search.query.SearchQueryIT > testQuotedQueryStringWithBoost FAILED
    java.lang.AssertionError: 
    Expected: a numeric value within <0.1> of <19.6165828704834>
         but: <9.400073051452637> differed by <10.116509819030762> more than delta <0.1>
        at __randomizedtesting.SeedInfo.seed([6B85DE554674A401:C205F912F67AFFC]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.search.query.SearchQueryIT.testQuotedQueryStringWithBoost(SearchQueryIT.java:927)
REPRODUCE WITH: ./gradlew :server:integTest --tests "org.elasticsearch.search.query.SearchQueryIT.testQuotedQueryStringWithBoost" -Dtests.seed=6B85DE554674A401 -Dtests.security.manager=true -Dtests.locale=de-CH -Dtests.timezone=Europe/San_Marino -Dcompiler.java=12 -Druntime.java=8
```

**Comment by mayya-sharipova** [comment] 2019-07-24 12:14
Reopening this issue, as the we have not found the reason for the test failure. We just added more logging for investigation

**Comment by markharwood** [comment] 2019-09-11 13:20
In [this PR](https://github.com/elastic/elasticsearch/pull/43385#issuecomment-511970279) the following comment was made:

>I am not sure how dummy documents can influence scoring, as they are empty documents and don't contain any fields

They change the IDF scores because deleted documents count towards the size of the corpus in these calculations.
Given that explanation can we assume this is fixed now? (Wasn't reproducing for me with master).

**Comment by mayya-sharipova** [comment] 2019-10-23 14:40
@markharwood  Thanks for looking into this.
> They change the IDF scores because deleted documents count towards the size of the corpus in these calculations.

These bogus deleted documents don't have any fields, so they should not be counted to the idf for a query on a particular field.

I still blame `indexRandom` for this change in scores given a lot of randomness how docs are indexed, when flush is performed, and handling of errors.  

I also think that we should close this issue for now, as no test failures occur after the initial filing of this issue. We left some debugging in case another test failure occurs.

**Closed by mayya-sharipova** 2019-10-23 14:40 UTC
Labels: :Search/Search, >test-failure
