### ISSUE TITLE
[CI] ScalingThreadPoolTests testScalingThreadPoolConfiguration failing

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#92419] opened 2022-12-16 15:34 UTC
(Not 100% sure who owns threadpools, whether it's core/infra or the distributed team)

**Build scan:**
https://gradle-enterprise.elastic.co/s/6bnqyucslkqwu/tests/:server:test/org.elasticsearch.threadpool.ScalingThreadPoolTests/testScalingThreadPoolConfiguration

**Reproduction line:**
```
./gradlew ':server:test' --tests "org.elasticsearch.threadpool.ScalingThreadPoolTests.testScalingThreadPoolConfiguration" -Dtests.seed=723A4CB306D59946 -Dtests.locale=zh-SG -Dtests.timezone=Asia/Aqtau -Druntime.java=17
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.threadpool.ScalingThreadPoolTests&tests.test=testScalingThreadPoolConfiguration

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: <10>
     but: was <5>

  at __randomizedtesting.SeedInfo.seed([723A4CB306D59946:5FBC453C30C07715]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.threadpool.ScalingThreadPoolTests.lambda$testScalingThreadPoolConfiguration$0(ScalingThreadPoolTests.java:105)
  at org.elasticsearch.threadpool.ScalingThreadPoolTests.runScalingThreadPoolTest(ScalingThreadPoolTests.java:433)
  at org.elasticsearch.threadpool.ScalingThreadPoolTests.testScalingThreadPoolConfiguration(ScalingThreadPoolTests.java:88)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by thecoop** [comment] 2022-12-16 16:45
Unable to reproduce locally here. I also can't match up the given random seed with the failure here. There's nothing committed recently that could explain why this has started failing now.

I'm going to blame infrastructure gremlins for now...

**Comment by rjernst** [comment] 2022-12-16 17:42
This looks like it is caused by https://github.com/elastic/elasticsearch/pull/92392, which removed the fixed max of 10 for the snapshot threadpool. This test will need to be adjusted for the new dynamic max, @pxsalehi can adjust the test accordingly?

There is also something about this test that uses some randomness outside of the fixed test seed, though I cannot identify it. My hunch is it has to do with available processors, but that also would not change from test run to test run. For me this reproduced when I used tests.iters, but sometimes it would pass dozens of times before getting a failure.

**Comment by pxsalehi** [comment] 2022-12-19 09:36
> There is also something about this test that uses some randomness outside of the fixed test seed, though I cannot identify it. My hunch is it has to do with available processors, but that also would not change from test run to test run. For me this reproduced when I used tests.iters, but sometimes it would pass dozens of times before getting a failure.

Maybe because the test picks a random Scaling threadpool each time to test:
```java
public void testScalingThreadPoolConfiguration() throws InterruptedException {
        final String threadPoolName = randomThreadPool(ThreadPool.ThreadPoolType.SCALING);
        // ...
}

static String randomThreadPool(final ThreadPool.ThreadPoolType type) {
        return randomFrom(
            ThreadPool.THREAD_POOL_TYPES.entrySet().stream().filter(t -> t.getValue().equals(type)).map(Map.Entry::getKey).toList()
        );
    }
```
and that adds some "extra randomness" when listing the map entries. Probably a `sorted()` before `toList()` would help in that case.

**Closed** 2022-12-19 10:16 UTC
Labels: :Distributed/Snapshot/Restore, >test-failure, Team:Distributed
