### ISSUE TITLE
windows elasticsearch.bat file has problems with certains paths

### ISSUE THREAD

**Issue by Dobatymo** [elastic/elasticsearch#30606] opened 2018-05-15 09:30 UTC
Bug report:

**Elasticsearch version**: 6.2.4
**Plugins installed**: None
**JVM version**: 1.8.0_171
**OS version**: Windows 10 (1511)

**Description of the problem including expected versus actual behavior**:

I cannot start elastic search using `elasticsearch.bat`.
The error message is: `\Common was unexpected at this time.`

**Fix**

%JAVA% is assigned `C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe` in `elasticsearch-env.bat`.
This breaks the last for loop in `elasticsearch.bat`. This can be fixed be changing it to

``for /F "usebackq" %%a in (`CALL %JAVA% -cp "!ES_CLASSPATH!" "org.elasticsearch.tools.launchers.JvmOptionsParser" "!ES_JVM_OPTIONS!" ^|^| echo jvm_options_parser_failed`) do set JVM_OPTIONS=%%a``

See also https://stackoverflow.com/a/30139757/

**Comment by cbuescher** [comment] 2018-05-15 12:29
I found https://github.com/elastic/elasticsearch/pull/28753 which might be related but that should have been fixed in 6.2.3. Not sure if this is a different issue.

**Comment by sathiql** [comment] 2018-06-01 20:56
I had the same issue in windows
Added JAVA_HOME in Environmetn Variable --> System Variables section.
It worked

**Comment by Dobatymo** [comment] 2018-06-02 08:31
@sathiql JAVA_HOME is assigned, the problem is with the parentheses in the path. Does your path contain parentheses?

**Comment by Henr1k80** [comment] 2018-06-06 07:29
My Windows 10 with java SE x64 version 1.8.0_171-b11 running Elasticsearch 6.2.4 also had this problem
I added the fix to the bat file and it worked.
In my Path variable there is this path:
C:\Program Files (x86)\Common Files\Oracle\Java\javapath
which I guess is some kind of symbolic link folder to my current x64 java (special icon, only java, javaw and javaws exe). I think it is the culprit.
I have no JAVA_HOME and adding one did not help.

**Comment by lashchev** [comment] 2018-06-11 15:02
Thanks, @Dobatymo for the fix!. It works in general, but the result will be that only first option from jvm.options file will be picked up. Here is the updated version (with added _delims=_ option) that picks all JVM options:

```
for /F "usebackq delims=" %%a in (`CALL %JAVA% -cp "!ES_CLASSPATH!" "org.elasticsearch.tools.launchers.JvmOptionsParser" "!ES_JVM_OPTIONS!" ^|^| echo jvm_options_parser_failed`) do set JVM_OPTIONS=%%a
```

**Comment by lashchev** [comment] 2018-06-25 10:23
Still the same issue in v6.3.0

Another issue that is in the elasticsearch.bat is just 2 lines above "for /F". It starts with set "ES_JVM_OPTIONS=
It has double quotes between "set" and variable name. These quotes are not really needed because in the command below that variable is enclosed in the quotes anyway.
So, the full working snippet that works for me looks like the following 
```
set ES_JVM_OPTIONS=%ES_PATH_CONF%\jvm.options
@setlocal
for /F "usebackq delims=" %%a in (`CALL %JAVA% -cp "!ES_CLASSPATH!" "org.elasticsearch.tools.launchers.JvmOptionsParser" "!ES_JVM_OPTIONS!" ^|^| echo jvm_options_parser_failed`) do set JVM_OPTIONS=%%a
@endlocal & set "MAYBE_JVM_OPTIONS_PARSER_FAILED=%JVM_OPTIONS%" & set ES_JAVA_OPTS=%JVM_OPTIONS:${ES_TMPDIR}=!ES_TMPDIR!% %ES_JAVA_OPTS%
```

**Comment by PhaedrusTheGreek** [comment] 2018-08-14 13:51
This is reproducible in Windows server 2016 when `JAVA_HOME` has parenthesis, like in `Program Files (x86).

**Comment by SreekanthPuj** [comment] 2018-10-09 17:22
I've resolved this with the below two steps on Windows 10 - 64 bit machine using Command Line Installer for ElasticSearch 6.4.2
1. Added an environment variable JAVA_HOME to the System Environment varaibles.
2. In the ElasticSearch.bat
replace for /F "usebackq delims=" %%a in (`"JAVA....
with for /F "usebackq delims=" %%a in (`"**!**JAVA**!**...
it worked like a charm for me...
PS: The startup then hit an issue:
[2018-10-09T18:20:49,158][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [Sree_Cluster1_node-1] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: ElasticsearchException[X-Pack is not supported and Machine Learning is not available for [windows-x86]; you can use the other X-Pack features (unsupported) by setting xpack.ml.enabled: false in elasticsearch.yml]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:140) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.4.2.jar:6.4.2]

This one got resolved by adding **xpack.ml.enabled: false** to the elasticsearch.yml

**Closed** 2019-04-02 10:54 UTC
Labels: :Core/Infra/Packaging, >bug

**Comment by jaiswarvipin** [comment] 2019-04-27 17:30
Hi All,
if your java is installed under C:\Program Files (x86) then set the JAVA_HOME like will below

`set JAVA_HOME=C:\Progra~2\Java\jre1.8.0_131`

if your java is installed under C:\Program Files then set the JAVA_HOME like will below
`set JAVA_HOME=C:\Progra~1\Java\jre1.8.0_131`

After that try to start the elastic search, it should start then.

Thanks & Regards
Jaiswar Vipin Kumar R

**Comment by hap2y1122** [comment] 2021-06-10 19:15
> I had the same issue in windows
> Added JAVA_HOME in Environmetn Variable --> System Variables section.
> It worked

I did the same but it won't work

**Comment by hap2y1122** [comment] 2021-06-10 20:21
after hours my conclusion of those whose elasticsearch.bat file not opening

-  First go to edit environment variables 
- Go to system variables section 
- Add a new path or edit the old java home path to >>   JAVA_HOME or ES_JAVA_HOME   :  the current java path till jdk-{version}
- Add it
- Then go to path and double click
- Edit the path till `bin` this time

Do these you elasticsearch.bat file not opening will be solved.

**Comment by vancleimatheus** [comment] 2021-09-08 22:43
Very late to the party but I would add some more comments for someone that might be here in the future:

- in addition to checking JAVA_HOME environment variable, be sure it points to a valid location, even though java is working on my machine I'm not sure why JAVA_HOME was set to an older version
- be sure JAVA_HOME doesn't include \bin, the script will include the \bin
- I believe the changes made by @pgomulka are not included on packages for older versions, it would be nice if it was possible to include these changes.
- Either way, I edited `elasticsearch.bat` to include @pgomulka changes and it worked just fine

just my 2cents
