### ISSUE TITLE
CI: SmokeTestIngestWithAllDepsClientYamlTestSuiteIT fails reproducibly

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#24567] opened 2017-05-09 16:24 UTC
This seed fails reproducibly for me on osx.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/147/console

```
gradle :qa:smoke-test-ingest-with-all-dependencies:integTestRunner -Dtests.seed=DED6103101C484C6 -Dtests.class=org.elasticsearch.smoketest.SmokeTestIngestWithAllDepsClientYamlTestSuiteIT -Dtests.method="test {yaml=ingest/60_pipeline_timestamp_date_mapping/Test timestamp templating does not match date-mapping defaults}" -Dtests.security.manager=true -Dtests.locale=da -Dtests.timezone=Greenwich
```

**Comment by spinscale** [comment] 2017-05-09 16:37
another occurence at https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/2744/console

**Comment by talevy** [comment] 2017-05-09 17:21
thanks for reporting... wonder why it passed once before

**Comment by talevy** [comment] 2017-05-09 17:34
I used your seed shared in the description, and cannot reproduce yet. I've re-run this seed on my laptop and a linux box, unable to reproduce after multiple runs off latest master.

will keep running it in a loop for a bit until it occurs? might have been a rogue timing error between requests?

**Comment by talevy** [comment] 2017-05-09 18:07
happened again on 5.x

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.x+multijob-intake/1157/console

```
gradle :qa:smoke-test-ingest-with-all-dependencies:integTestRunner -Dtests.seed=53E2CEBC9F4D499E -Dtests.class=org.elasticsearch.smoketest.SmokeTestIngestWithAllDepsClientYamlTestSuiteIT -Dtests.method="test {yaml=ingest/10_pipeline_with_mustache_templates/Test rolling up json object arrays}" -Dtests.security.manager=true -Dtests.locale=sq-AL -Dtests.timezone=Etc/GMT+0
```

**Comment by talevy** [comment] 2017-05-09 18:07
I believe this is related: https://github.com/elastic/elasticsearch/commit/3e376740dbecbd34fa937f1492323f9b8ecc5509

**Comment by talevy** [comment] 2017-05-09 19:21
happened on windows again after the "related" commit ^^

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/148/console

**Comment by talevy** [comment] 2017-05-09 20:39
OK, realized the issue after stumbling a bit... didn't expect timezones not to be supported in Joda

https://github.com/JodaOrg/joda-time/blob/master/src/main/java/org/joda/time/DateTimeUtils.java#L435-L450

*many* timezones are not supported.

**Comment by talevy** [comment] 2017-05-09 21:36
pushed fixes in
`5.x`: https://github.com/elastic/elasticsearch/commit/fd5d23c7e5d6125d2241be1e8a24cf17ea8788ee
`master`: https://github.com/elastic/elasticsearch/commit/d2416a3a408d3d3d02742890ad8b96ac9591270c

**Comment by talevy** [comment] 2017-05-09 21:37
@spinscale silly Joda is very US-specific when it comes to parsing timezone, and since your system timezone is part of the unsupported, you ran into this issue while I never did.

I updated the check to skip the timezone, it is not important for the overall format check

**Comment by talevy** [comment] 2017-05-10 20:30
latest test here: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/149/ alludes to this problem being solved. Although, it fails for other reasons. 
Closing this, will re-open if pops up again for whatever reason

**Closed by talevy** 2017-05-10 20:30 UTC
Labels: :Ingest, test
