### ISSUE TITLE
Deleting data directory while elasticsearch is running puts elasticsearch in a frozen state (RED)

### ISSUE THREAD

**Issue by Rajind** [elastic/elasticsearch#19549] opened 2016-07-22 14:52 UTC
**Elasticsearch version**: 2.3.3

**JVM version**:  1.7.0_80-b15

**OS version**: ubuntu 16.04 LTS

**Description of the problem including expected versus actual behavior**:
Deleting data directory while elasticsearch is running puts elasticsearch in a frozen state (RED) and even you restart elasticsearch it is still in a frozen state (RED). 
P.S: I know that it is not good to delete data directory. I am using an embedded server and has configured data directory to be deleted on maven clean command. It was by accident that I came across this issue.

**Steps to reproduce**:
 1. run elasticsearch 
 2. delete elasticsearch data directory while elasticsearch is running
 3. restart elasticsearch

**Comment by abeyad** [comment] 2016-07-22 15:18
Its not clear what you mean by frozen state?  RED means the cluster can't handle any write operations because primary shards are missing.  If you delete your data directory, this will naturally be the case.  

Closing as this is not a bug.

**Closed by abeyad** 2016-07-22 15:18 UTC

**Comment by imotov** [comment] 2016-07-22 18:32
@Rajind I wasn't able to reproduce this issue the way you described it. When I wipe out entire data directory and restart the node, I get a clean cluster in GREEN state. You are probably wiping out the index directory not entire data directory, which causes elasticsearch to think that index should exist when it actually doesn't, therefore shards are missing and as a result you get RED state. The solution here would be to delete the entire data directory when server is stopped and then start it again.

**Comment by Rajind** [comment] 2016-07-25 04:14
@imotov: Thanks for the reply. I assume you tried deleting the data directory while elasticsearch is running. I am deleting the directory which is given to the elasticsearch configuration as "path.data". Is is same as index directory ? If not where would be the index directory when running elasticsearch embedded ? 

The scenario I saw is that first when I delete data directory when elasticsearch is running the folder is empty. but when elasticsearch shuts down it writes some files to that dir and probably those files might be related to the index i suppose. And when I start elasticsearch again the index is there but no data. So recovery fails.

**Comment by imotov** [comment] 2016-07-28 01:23
> I am deleting the directory which is given to the elasticsearch configuration as "path.data". Is is same as index directory ?

Yes, it is the same directory. I just tried it with non-default data directory and couldn't reproduce it either.

> The scenario I saw is that first when I delete data directory when elasticsearch is running the folder is empty. but when elasticsearch shuts down it writes some files to that dir and probably those files might be related to the index i suppose. 

When you delete the data directory while elasticsearch is running it doesn't actually recreate this directory. So, when you start elasticsearch again it creates an empty directory and starts fine. You can download elasticsearch and try to reproduce it yourself. You will see what I mean.

**Comment by Rajind** [comment] 2016-08-01 08:31
@imotov I still experience the same scenario. Do you think what I observe has something to do with BulkProcessor trying to publish while the data directory is deleted ?

**Comment by imotov** [comment] 2016-08-08 00:14
@Rajind did you try reproducing it outside of your application with non-embedded mode? When you run elasticsearch in an embedded mode a lot of things can happen inside your application that are very hard to reproduce for us unless we know what exactly your application is doing. So, unless you can help us reproducing it without your application code involved, I am not really sure we can do something about it.

**Comment by Rajind** [comment] 2016-08-09 03:23
@imotov I will try to reproduce it with a sample code with an standalone node and get back to you. Thanks.
