### ISSUE TITLE
[CI] IndexDiskUsageAnalyzerIT classMethod failing

### ISSUE THREAD

**Issue by kkrik-es** [elastic/elasticsearch#100830] opened 2023-10-13 12:54 UTC
**Build scan:**
https://gradle-enterprise.elastic.co/s/rjfh3k3bkfpkg/tests/:server:internalClusterTest/org.elasticsearch.action.admin.indices.diskusage.IndexDiskUsageAnalyzerIT
**Reproduction line:**
```
null
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.action.admin.indices.diskusage.IndexDiskUsageAnalyzerIT&tests.test=classMethod
**Failure excerpt:**
```
java.lang.AssertionError: (No message provided)

  at __randomizedtesting.SeedInfo.seed([E460851DF1054B60]:0)
  at org.elasticsearch.discovery.PeerFinder.closePeers(PeerFinder.java:183)
  at org.elasticsearch.cluster.coordination.Coordinator.onClusterStateApplied(Coordinator.java:420)
  at org.elasticsearch.cluster.coordination.Coordinator.lambda$handleApplyCommit$8(Coordinator.java:408)
  at org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.lambda$map$0(ActionListenerImplementations.java:108)
  at org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:89)
  at org.elasticsearch.cluster.service.ClusterApplierService$ClusterApplyActionListener.onResponse(ClusterApplierService.java:598)
  at org.elasticsearch.cluster.service.ClusterApplierService$ClusterApplyActionListener.onResponse(ClusterApplierService.java:569)
  at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:439)
  at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:154)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:916)
  at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:217)
  at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:183)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by kingherc** [comment] 2023-10-16 13:20
I believe this is a duplicate of https://github.com/elastic/elasticsearch/issues/99023 . Right @fcofdez ? I'm closing it for this reason. But please undo if I'm mistaken.

**Closed by kingherc** 2023-10-16 13:20 UTC
Labels: blocker, >test-failure, :Distributed/Cluster Coordination, Team:Distributed
