### ISSUE TITLE
[CI] AsyncBulkByScrollActionTests testScrollResponseBatchingBehavior failing

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#110181] opened 2024-06-26 10:08 UTC
**Build scan:**
https://gradle-enterprise.elastic.co/s/h7gdqkimbf4tg/tests/:modules:reindex:test/org.elasticsearch.reindex.AsyncBulkByScrollActionTests/testScrollResponseBatchingBehavior

**Reproduction line:**
```
./gradlew ':modules:reindex:test' --tests "org.elasticsearch.reindex.AsyncBulkByScrollActionTests.testScrollResponseBatchingBehavior" -Dtests.seed=5638EFEF212A5042 -Dtests.locale=nl-BE -Dtests.timezone=America/Atka -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.reindex.AsyncBulkByScrollActionTests#testScrollResponseBatchingBehavior`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testScrollResponseBatchingBehavior'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.reindex.AsyncBulkByScrollActionTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.AssertionError: cannot complete future on thread Thread[#70,elasticsearch[testScrollResponseBatchingBehavior][generic][T#7],5,TGRP-AsyncBulkByScrollActionTests] with waiter on thread Thread[#69,elasticsearch[testScrollResponseBatchingBehavior][generic][T#6],5,TGRP-AsyncBulkByScrollActionTests], could deadlock if pool was full
	at java.base/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:410)
	at java.base/java.util.concurrent.LinkedTransferQueue$DualNode.await(LinkedTransferQueue.java:452)
	at java.base/java.util.concurrent.LinkedTransferQueue.xfer(LinkedTransferQueue.java:613)
	at java.base/java.util.concurrent.LinkedTransferQueue.poll(LinkedTransferQueue.java:1268)
	at java.base/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1069)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)

  at __randomizedtesting.SeedInfo.seed([5638EFEF212A5042]:0)
  at org.elasticsearch.action.support.PlainActionFuture.assertCompleteAllowed(PlainActionFuture.java:416)
  at org.elasticsearch.action.support.PlainActionFuture.onFailure(PlainActionFuture.java:42)
  at org.elasticsearch.reindex.AbstractAsyncBulkByScrollAction.lambda$finishHim$3(AbstractAsyncBulkByScrollAction.java:598)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:917)
  at org.elasticsearch.index.reindex.ClientScrollableHitSource.cleanup(ClientScrollableHitSource.java:127)
  at org.elasticsearch.index.reindex.ScrollableHitSource.lambda$close$2(ScrollableHitSource.java:115)
  at org.elasticsearch.index.reindex.ClientScrollableHitSource$2.onResponse(ClientScrollableHitSource.java:114)
  at org.elasticsearch.index.reindex.ClientScrollableHitSource$2.onResponse(ClientScrollableHitSource.java:110)
  at org.elasticsearch.reindex.AsyncBulkByScrollActionTests$MyMockClient.doExecute(AsyncBulkByScrollActionTests.java:1092)
  at org.elasticsearch.client.internal.support.AbstractClient.execute(AbstractClient.java:138)
  at org.elasticsearch.client.internal.support.AbstractClient.clearScroll(AbstractClient.java:363)
  at org.elasticsearch.index.reindex.ClientScrollableHitSource.clearScroll(ClientScrollableHitSource.java:110)
  at org.elasticsearch.index.reindex.ScrollableHitSource.close(ScrollableHitSource.java:115)
  at org.elasticsearch.reindex.AbstractAsyncBulkByScrollAction.finishHim(AbstractAsyncBulkByScrollAction.java:588)
  at org.elasticsearch.reindex.AbstractAsyncBulkByScrollAction.finishHim(AbstractAsyncBulkByScrollAction.java:576)
  at org.elasticsearch.reindex.AbstractAsyncBulkByScrollAction$1.onFailure(AbstractAsyncBulkByScrollAction.java:373)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:967)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:28)
  at org.elasticsearch.common.util.concurrent.RunOnce.run(RunOnce.java:40)
  at org.elasticsearch.index.reindex.WorkerBulkByScrollTaskState$DelayedPrepareBulkRequest.lambda$new$0(WorkerBulkByScrollTaskState.java:254)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:917)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  at java.lang.Thread.run(Thread.java:1570)

```

**Comment by nicktindall** [comment] 2024-06-28 09:06
This is the same cause as [this issue](https://github.com/elastic/elasticsearch/issues/109792). It's because `org.elasticsearch.action.support.PlainActionFuture#assertCompleteAllowed` only takes into account the executor name, and not the node & executor name when determining if we're risking a deadlock.

**Comment by nicktindall** [comment] 2024-07-01 06:59
[This build scan](https://gradle-enterprise.elastic.co/s/7tm7ijw3ijumg/tests/task/:modules:reindex:test/details/org.elasticsearch.reindex.AsyncBulkByScrollActionTests/testScrollResponseBatchingBehavior?expanded-stacktrace=WyIwIl0&top-execution=1) is more illustrative of the problem I believe, it looks like two threads are attempting to complete/fail the `PlainActionFuture` concurrently. I assume the first one in would usually do it's thing and the second one would be prevented from doing so, but because of the safety check (which is necessarily done without acquiring the mutex) it fails? I will keep digging.

**Comment by nicktindall** [comment] 2024-07-02 03:07
This appears to be an issue with threads concurrently resolving the `PlainActionFuture`.

It happens when multiple threads call `complete` simultaneously
- one thread successfully calls `compareAndSet(RUNNING, COMPLETING)` and proceeds to set the value/exception
- a second thread fails `compareAndSet(RUNNING, COMPLETING)` while the state is still `COMPLETING` so it calls `acquireShared` to wait for the first thread to finish its call to `complete`.
- a third thread from the same pool as the second thread calls `assertCompleteAllowed` which throws because there is a thread from the same pool waiting on the result.

This explains the strange stack traces that don't appear to show the waiter waiting on the `PlainActionFuture` (it has usually moved on by the time the stack trace is printed).

This is technically not a false-positive because there is genuinely a thread from the same pool waiting for the result of the future, but the reason its waiting means it is a false positive (because the waiter will not be blocked indefinitely).

I've been able to reproduce this with only two threads provided they are in a tight loop calling `onFailure`/`onResult` so we don't strictly need three threads for this to occur (in the two-thread case, the thread that succeeds in completing the future comes back and calls complete again while the waiting thread is still waiting).

Why this scenario arises in this test I'm not sure, both the threads seem to be calling onFailure, but the deadlock detection causes the original exception to be swallowed.

**Comment by nicktindall** [comment] 2024-07-02 05:22
Caused by #110360

**Closed** 2024-07-03 09:15 UTC
Labels: >test-failure, :Distributed/Reindex, Team:Distributed, low-risk
