### ISSUE TITLE
Mappings: Restrict unexpected characters from field names

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#12094] opened 2015-07-07 18:14 UTC
You can manage to slip unexpected characters into field names, like `\n`, `\0` (`\u0000`), `\t`, `\'`, `\"`, etc. I think that we should prevent this, but the change would create a backwards incompatible restriction.

Big caveat/counter argument: as long as they're escaped, these unexpected characters _are_ valid JSON.

**Comment by jpountz** [comment] 2015-07-08 15:41
Duplicate of https://github.com/elastic/elasticsearch/issues/9059

**Closed by jpountz** 2015-07-08 15:41 UTC
Labels: :Mapping, breaking, discuss, enhancement
