### ISSUE TITLE
Snapshot from replicas?

### ISSUE THREAD

**Issue by samcday** [elastic/elasticsearch#18866] opened 2016-06-14 18:41 UTC
It would be awesome if we could configure snapshots to run from replicas. Of course, this might not even be technically feasible due to the way Lucene segments are synced during a snapshot. But, I thought I'd ask anyway. I imagine it being an option for the repository (`allow_replicas` or something) which defaults to false. I understand that by enabling such an option, there's a risk that the snapshot process will be snapshotting out of date data. In our case, that risk is acceptable.

**Background:** we run a pretty massive Elasticsearch cluster that is indexing 50k+ events per second (45mbp/s+), all day, every day. The problem is, we run frequent snapshots, and the burden this places on the primary shards can cause our indexing performance to suffer as a result. If the replicas could also be selected as candidates for the snapshot process then it would reduce this pressure.

**Comment by clintongormley** [comment] 2016-06-14 19:00
@imotov seems reasonable? Can't we just do this by default?

**Comment by imotov** [comment] 2016-06-14 19:23
@samcday, @clintongormley sorry, I must be missing something, but I don't really see how it would help. Replication in elasticsearch is document-based, so amount of work performed on primaries is exactly the same as amount of work performed on replicas (unless we run some very heavy update operations with some crazy scripts). We removed async operation option in 2.0, so an indexing operation is now going to always wait for the replica to finish the operation before returning response to the user. By moving "the burden" to a replica we are just going to move the place were we wait. Even with async replication, it doesn't make sense to me, because a slow replica would cause a pileup of in-flight indexing requests, which in turn can lead to running out of memory and cluster instability. Could you give a bit more details on how how this change would improve the overall indexing performance?

**Comment by samcday** [comment] 2016-06-14 20:47
@imotov here's our problem in more detail:

We have a large cluster holding 9416 primary shards. Each of these shards has one replica in a different AZ (we're deploying in AWS). We've sunk a *lot* of engineering effort into a pretty elaborate higher-level allocation strategy that ensures the indices that are actively being written to have shards evenly distributed across 4 "indexing tiers" made up of 24 nodes in total. The problem is, short of actually disabling Elasticsearch shard allocation and doing it 100% ourselves, we have no way to control where the primary shards are allocated. We're already using [index.routing.allocation.total_shards_per_node](https://www.elastic.co/guide/en/elasticsearch/reference/current/allocation-total-shards.html) but this does not stop a large number of primary shards from clustering on a small set of index nodes. If the snapshot process randomly selected between the primary or one of the available replicas for the primary, then it would negate the clustering we're seeing.

Before you say it, yes, I know our use-case is crazy. I have virtually every PM and dev at Elastic telling me we're crazy (maybe we are. If we're cognizant of our possible craziness, wouldn't that mean we're definitely not crazy though? hmmm.). Anyway, you could simplify this way down:

Let's say you have 2 indices each with 3 primary shards + 3 replica shards. Allocation looks like this:

```





      NODE A            NODE B
+---------------+ +---------------+
| index_1[0][p] | | index_1[0][r] |
| index_1[1][p] | | index_1[1][r] |
| index_1[2][r] | | index_1[2][p] |
| index_2[0][p] | | index_2[0][r] |
| index_2[1][p] | | index_2[1][r] |
| index_2[2][r] | | index_2[2][p] |
+---------------+ +---------------+
```

In this case, Node A has 4 primary shards, Node B only has 2. So, during a snapshot, NodeA currently has to do 2x more work than Node B.

**Comment by imotov** [comment] 2016-06-14 21:02
Now, it makes more sense. So, the problem is unbalanced allocation of primary shards, which leads to overloading nodes with disproportionate number of primary shards on operations that are executed only on primaries, which in this particular case the snapshot operation. 

I can clearly see how this can be an issue on two nodes cluster in your example, but I am having a bit of a hard time imagining this situation across 24 nodes unless you just did a rolling restart or using very long living indices.

**Comment by samcday** [comment] 2016-06-14 21:06
You hit the nail on the head - we do a lot of rolling restarts to propagate config changes / ES minor version upgrades. For larger changes we do use shard allocation filtering to exclude nodes, wait for the node to be evacuated, and then kill it. In this case shards disperse more evenly, but we don't do this too often, seeing as each indexing node has 1tb+ of data to move around :(

**Comment by samcday** [comment] 2016-06-14 22:01
Whilst discussing this I've realised that maybe what I'm asking for is a band-aid. I've also raised #18874 as a feature request.

I'd still like to keep this one open to see if others have a similar need.

**Comment by clintongormley** [comment] 2016-06-15 08:49
> Whilst discussing this I've realised that maybe what I'm asking for is a band-aid. I've also raised #18874 as a feature request.

Actually I don't think this is a band-aid at all.  Primaries and replicas SHOULD be doing similar amounts of work.  It should not matter that all primaries are on one node and all replicas on another.

We should work at reducing reliance on the primary to avoid these hot spots.

**Comment by bleskes** [comment] 2016-06-17 09:28
the main reason why we always snapshot from a primary is that we want to make sure we snapshot the same shard so we can do proper file based deltas and make snapshoting efficient (files across shards are different). At the time snapshot and restore was written, we only had one way to accomplish this - do it on the primary. These days we have allocation ids and we can explore making each snapshot sticky to the same allocation id (but not necessarily a primary) and distribute the load across copies. @samcday will that work for you?

**Comment by samcday** [comment] 2016-06-18 04:34
@bleskes yeah that sounds great. How would you decide which shard to use? Randomised selection?

**Comment by bleskes** [comment] 2016-06-18 06:06
That would be my first attempt, yeah.

**Comment by s1monw** [comment] 2016-07-01 09:51
I think we can remove the discuss label @bleskes please put it back if you feel like it needs more discussion

**Comment by bleskes** [comment] 2016-07-01 10:48
@s1monw yeah, I should have removed the label. This for cleaning up.

**Comment by apatrida** [comment] 2017-02-09 18:20
A note for @bleskes  ... we use a model where we add and remove nodes all the time based on load (i.e. app servers come online and receive shards for indexes they use heavily so they can mostly query locally which still having live data, and then scale up or down).  Therefore allocations will change a lot as these extra expansions come and go.   Does this break the following?

> These days we have allocation ids and we can explore making each snapshot sticky to the same allocation id (but not necessarily a primary) and distribute the load across copies.

**Comment by bleskes** [comment] 2017-02-10 08:17
@apatrida if we end up doing this (there are more questions, like for example, are we willing to suffer the costs of a bigger snapshot when a shard relocates - at that point it is copied from the primary, not the original shard) it will be indeed problematic for you as it seems you would like to make sure that certain copies are never snapshotted. Note thought that even today you are not safe- if a primary fails, one of the copies on the app servers may be elected as primary. There is no way to control that and I don't see that happening soon.

**Comment by bleskes** [comment] 2017-02-10 10:16
> So the consequence isn't really a breakage of snapshot/restore but more about how much data will need to be copied since maybe it will be less incremental 

Correct.

> that happens to no longer have the same allocation IDs available between runs.

Almost. When shard is moved around it gets a new allocation ID. You can think as an identifier of a disk folder - when the shard moves to a new folder on another node  it gets a new id. When it is moved back, the old data is "deleted" (not really, but conceptually yes, at least now - there are plans to change it) and the shard gets a new allocation id. The problem is more that the different shards have different merge cycles and thus different files. To make snapshot efficient (i.e., small deltas) we need to make it stick to a certain set of files. We currently do so by looking at the primary. If we move to aID we could stick to other shards, but when those shards are moved their file structure will change (it will be a copy of the primary)

**Comment by apatrida** [comment] 2017-02-10 14:02
thanks.  that helps.  I think our shard manager will be ok in these models,
when compared to the inner workings and one not breaking the other (much).

**Comment by original-brownbear** [comment] 2019-12-11 15:00
We discussed this during out team sync today and decided to close this issue.
Given the low demand, limited usefulness and complexity of implementing this we don't see this as something to work on in the foreseeable future.

**Closed by original-brownbear** 2019-12-11 15:00 UTC
Labels: :Distributed/Snapshot/Restore, >feature, help wanted
