### ISSUE TITLE
IndexOutOfBoundsException in Sorting Script

### ISSUE THREAD

**Issue by tdoman** [elastic/elasticsearch#70190] opened 2021-03-10 00:36 UTC
**Elasticsearch version**:
6.8.13 (same behavior in 6.1.1)

**OS**:
Windows

**Programming Language\Library**:
C#\NEST 6.8.6

I'm getting index out of bounds when trying to use the following script when sorting in descending order only (ie. ascending order works fine):

```
POST _scripts/sortTargetsByFollowers
{
  "script": {
    "lang": "painless",
    "source": "if (doc.containsKey('followerKeys')) { return doc['followerKeys'].size(); } else { return 0; }"
  }
}
```
The sort portion of the request is as follows:
```
  "sort": [
    {
      "_script": {
        "order": "desc",
        "script": {
          "id": "sortTargetsByFollowers"
        },
        "type": "number"
      }
    }
```
Here's the operative part of the exception detail:
```
          "org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:39)",
          "return doc['followerKeys'].size(); } else { ",
          "           ^---- HERE"
        ],
        "script": "sortTargetsByFollowers",
        "lang": "painless",
        "stack_trace": "ScriptException[runtime error]; nested: IndexOutOfBoundsException;\r\n\tat org.elasticsearch.painless.PainlessScript.convertToScriptException
```
Here's the operative part of the mapping:
```
        "followerKeys": {
          "type": "long"
        },
```
As I noted, this has been an issue since 6.1.1 (our first version of 6.x) and I had been hoping it'd be fixed in 6.8.13.  Is there a way I can work around this?

**Comment by rjernst** [comment] 2021-05-05 21:37
@tdoman Can you please provide the entire exception? It looks like there is more above what you excerpted.

**Comment by tdoman** [comment] 2021-05-06 22:46
Sure, here you go:
```{
  "error": {
    "root_cause": [
      {
        "type": "script_exception",
        "reason": "runtime error",
        "script_stack": [
          "java.base/java.nio.Buffer.checkIndex(Buffer.java:687)",
          "java.base/java.nio.DirectByteBuffer.get(DirectByteBuffer.java:269)",
          "org.apache.lucene.store.ByteBufferGuard.getByte(ByteBufferGuard.java:118)",
          "org.apache.lucene.store.ByteBufferIndexInput$SingleBufferImpl.readByte(ByteBufferIndexInput.java:385)",
          "org.apache.lucene.codecs.lucene70.Lucene70DocValuesProducer$10.get(Lucene70DocValuesProducer.java:599)",
          "org.apache.lucene.codecs.lucene70.Lucene70DocValuesProducer$22.nextValue(Lucene70DocValuesProducer.java:1271)",
          "org.elasticsearch.index.fielddata.ScriptDocValues$Longs.setNextDocId(ScriptDocValues.java:166)",
          "org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:94)",
          "org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:39)",
          "return doc['followerKeys'].size(); } else { ",
          "           ^---- HERE"
        ],
        "script": "sortTargetsByFollowers",
        "lang": "painless",
        "stack_trace": "ScriptException[runtime error]; nested: IndexOutOfBoundsException;\r\n\tat org.elasticsearch.painless.PainlessScript.convertToScriptException(PainlessScript.java:94)\r\n\tat org.elasticsearch.painless.PainlessScript$Script.execute(sortTargetsByFollowers:91)\r\n\tat org.elasticsearch.painless.ScriptImpl.run(ScriptImpl.java:104)\r\n\tat org.elasticsearch.painless.ScriptImpl.runAsDouble(ScriptImpl.java:109)\r\n\tat org.elasticsearch.search.sort.ScriptSortBuilder$2$1.doubleValue(ScriptSortBuilder.java:381)\r\n\tat org.elasticsearch.index.fielddata.FieldData$14.advanceExact(FieldData.java:572)\r\n\tat org.elasticsearch.index.fielddata.NumericDoubleValues$1.advanceExact(NumericDoubleValues.java:44)\r\n\tat org.apache.lucene.search.FieldComparator$DoubleComparator.getValueForDoc(FieldComparator.java:181)\r\n\tat org.apache.lucene.search.FieldComparator$DoubleComparator.copy(FieldComparator.java:200)\r\n\tat org.apache.lucene.search.MultiLeafFieldComparator.copy(MultiLeafFieldComparator.java:81)\r\n\tat org.apache.lucene.search.TopFieldCollector$SimpleFieldCollector$1.collect(TopFieldCollector.java:191)\r\n\tat org.apache.lucene.search.MultiCollector$MultiLeafCollector.collect(MultiCollector.java:174)\r\n\tat org.apache.lucene.search.MultiCollector$MultiLeafCollector.collect(MultiCollector.java:174)\r\n\tat org.apache.lucene.search.Weight$DefaultBulkScorer.scoreRange(Weight.java:247)\r\n\tat org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:225)\r\n\tat org.elasticsearch.search.internal.CancellableBulkScorer.score(CancellableBulkScorer.java:56)\r\n\tat org.apache.lucene.search.BulkScorer.score(BulkScorer.java:39)\r\n\tat org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:670)\r\n\tat org.elasticsearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:191)\r\n\tat org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:471)\r\n\tat org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:276)\r\n\tat org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:114)\r\n\tat org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:350)\r\n\tat org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:394)\r\n\tat org.elasticsearch.search.SearchService.access$100(SearchService.java:126)\r\n\tat org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:359)\r\n\tat org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:355)\r\n\tat org.elasticsearch.search.SearchService$4.doRun(SearchService.java:1117)\r\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\r\n\tat org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41)\r\n\tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:778)\r\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\r\n\tat java.base/java.lang.Thread.run(Thread.java:834)\r\nCaused by: java.lang.IndexOutOfBoundsException\r\n\tat java.base/java.nio.Buffer.checkIndex(Buffer.java:687)\r\n\tat java.base/java.nio.DirectByteBuffer.get(DirectByteBuffer.java:269)\r\n\tat org.apache.lucene.store.ByteBufferGuard.getByte(ByteBufferGuard.java:118)\r\n\tat org.apache.lucene.store.ByteBufferIndexInput$SingleBufferImpl.readByte(ByteBufferIndexInput.java:385)\r\n\tat org.apache.lucene.codecs.lucene70.Lucene70DocValuesProducer$10.get(Lucene70DocValuesProducer.java:599)\r\n\tat org.apache.lucene.codecs.lucene70.Lucene70DocValuesProducer$22.nextValue(Lucene70DocValuesProducer.java:1271)\r\n\tat org.elasticsearch.index.fielddata.ScriptDocValues$Longs.setNextDocId(ScriptDocValues.java:166)\r\n\tat org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:94)\r\n\tat org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:39)\r\n\tat org.elasticsearch.painless.PainlessScript$Script.execute(sortTargetsByFollowers:51)\r\n\t... 33 more\r\n"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "qz_targets_v2021_01",
        "node": "0qhbnJy2SiGaNbZn77bEYw",
        "reason": {
          "type": "script_exception",
          "reason": "runtime error",
          "script_stack": [
            "java.base/java.nio.Buffer.checkIndex(Buffer.java:687)",
            "java.base/java.nio.DirectByteBuffer.get(DirectByteBuffer.java:269)",
            "org.apache.lucene.store.ByteBufferGuard.getByte(ByteBufferGuard.java:118)",
            "org.apache.lucene.store.ByteBufferIndexInput$SingleBufferImpl.readByte(ByteBufferIndexInput.java:385)",
            "org.apache.lucene.codecs.lucene70.Lucene70DocValuesProducer$10.get(Lucene70DocValuesProducer.java:599)",
            "org.apache.lucene.codecs.lucene70.Lucene70DocValuesProducer$22.nextValue(Lucene70DocValuesProducer.java:1271)",
            "org.elasticsearch.index.fielddata.ScriptDocValues$Longs.setNextDocId(ScriptDocValues.java:166)",
            "org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:94)",
            "org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:39)",
            "return doc['followerKeys'].size(); } else { ",
            "           ^---- HERE"
          ],
          "script": "sortTargetsByFollowers",
          "lang": "painless",
          "caused_by": {
            "type": "index_out_of_bounds_exception",
            "reason": null,
            "stack_trace": "java.lang.IndexOutOfBoundsException\r\n\tat java.base/java.nio.Buffer.checkIndex(Buffer.java:687)\r\n\tat java.base/java.nio.DirectByteBuffer.get(DirectByteBuffer.java:269)\r\n\tat org.apache.lucene.store.ByteBufferGuard.getByte(ByteBufferGuard.java:118)\r\n\tat org.apache.lucene.store.ByteBufferIndexInput$SingleBufferImpl.readByte(ByteBufferIndexInput.java:385)\r\n\tat org.apache.lucene.codecs.lucene70.Lucene70DocValuesProducer$10.get(Lucene70DocValuesProducer.java:599)\r\n\tat org.apache.lucene.codecs.lucene70.Lucene70DocValuesProducer$22.nextValue(Lucene70DocValuesProducer.java:1271)\r\n\tat org.elasticsearch.index.fielddata.ScriptDocValues$Longs.setNextDocId(ScriptDocValues.java:166)\r\n\tat org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:94)\r\n\tat org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:39)\r\n\tat org.elasticsearch.painless.PainlessScript$Script.execute(sortTargetsByFollowers:51)\r\n\tat org.elasticsearch.painless.ScriptImpl.run(ScriptImpl.java:104)\r\n\tat org.elasticsearch.painless.ScriptImpl.runAsDouble(ScriptImpl.java:109)\r\n\tat org.elasticsearch.search.sort.ScriptSortBuilder$2$1.doubleValue(ScriptSortBuilder.java:381)\r\n\tat org.elasticsearch.index.fielddata.FieldData$14.advanceExact(FieldData.java:572)\r\n\tat org.elasticsearch.index.fielddata.NumericDoubleValues$1.advanceExact(NumericDoubleValues.java:44)\r\n\tat org.apache.lucene.search.FieldComparator$DoubleComparator.getValueForDoc(FieldComparator.java:181)\r\n\tat org.apache.lucene.search.FieldComparator$DoubleComparator.copy(FieldComparator.java:200)\r\n\tat org.apache.lucene.search.MultiLeafFieldComparator.copy(MultiLeafFieldComparator.java:81)\r\n\tat org.apache.lucene.search.TopFieldCollector$SimpleFieldCollector$1.collect(TopFieldCollector.java:191)\r\n\tat org.apache.lucene.search.MultiCollector$MultiLeafCollector.collect(MultiCollector.java:174)\r\n\tat org.apache.lucene.search.MultiCollector$MultiLeafCollector.collect(MultiCollector.java:174)\r\n\tat org.apache.lucene.search.Weight$DefaultBulkScorer.scoreRange(Weight.java:247)\r\n\tat org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:225)\r\n\tat org.elasticsearch.search.internal.CancellableBulkScorer.score(CancellableBulkScorer.java:56)\r\n\tat org.apache.lucene.search.BulkScorer.score(BulkScorer.java:39)\r\n\tat org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:670)\r\n\tat org.elasticsearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:191)\r\n\tat org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:471)\r\n\tat org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:276)\r\n\tat org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:114)\r\n\tat org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:350)\r\n\tat org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:394)\r\n\tat org.elasticsearch.search.SearchService.access$100(SearchService.java:126)\r\n\tat org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:359)\r\n\tat org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:355)\r\n\tat org.elasticsearch.search.SearchService$4.doRun(SearchService.java:1117)\r\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\r\n\tat org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41)\r\n\tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:778)\r\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\r\n\tat java.base/java.lang.Thread.run(Thread.java:834)\r\n"
          },
          "stack_trace": "ScriptException[runtime error]; nested: IndexOutOfBoundsException;\r\n\tat org.elasticsearch.painless.PainlessScript.convertToScriptException(PainlessScript.java:94)\r\n\tat org.elasticsearch.painless.PainlessScript$Script.execute(sortTargetsByFollowers:91)\r\n\tat org.elasticsearch.painless.ScriptImpl.run(ScriptImpl.java:104)\r\n\tat org.elasticsearch.painless.ScriptImpl.runAsDouble(ScriptImpl.java:109)\r\n\tat org.elasticsearch.search.sort.ScriptSortBuilder$2$1.doubleValue(ScriptSortBuilder.java:381)\r\n\tat org.elasticsearch.index.fielddata.FieldData$14.advanceExact(FieldData.java:572)\r\n\tat org.elasticsearch.index.fielddata.NumericDoubleValues$1.advanceExact(NumericDoubleValues.java:44)\r\n\tat org.apache.lucene.search.FieldComparator$DoubleComparator.getValueForDoc(FieldComparator.java:181)\r\n\tat org.apache.lucene.search.FieldComparator$DoubleComparator.copy(FieldComparator.java:200)\r\n\tat org.apache.lucene.search.MultiLeafFieldComparator.copy(MultiLeafFieldComparator.java:81)\r\n\tat org.apache.lucene.search.TopFieldCollector$SimpleFieldCollector$1.collect(TopFieldCollector.java:191)\r\n\tat org.apache.lucene.search.MultiCollector$MultiLeafCollector.collect(MultiCollector.java:174)\r\n\tat org.apache.lucene.search.MultiCollector$MultiLeafCollector.collect(MultiCollector.java:174)\r\n\tat org.apache.lucene.search.Weight$DefaultBulkScorer.scoreRange(Weight.java:247)\r\n\tat org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:225)\r\n\tat org.elasticsearch.search.internal.CancellableBulkScorer.score(CancellableBulkScorer.java:56)\r\n\tat org.apache.lucene.search.BulkScorer.score(BulkScorer.java:39)\r\n\tat org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:670)\r\n\tat org.elasticsearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:191)\r\n\tat org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:471)\r\n\tat org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:276)\r\n\tat org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:114)\r\n\tat org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:350)\r\n\tat org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:394)\r\n\tat org.elasticsearch.search.SearchService.access$100(SearchService.java:126)\r\n\tat org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:359)\r\n\tat org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:355)\r\n\tat org.elasticsearch.search.SearchService$4.doRun(SearchService.java:1117)\r\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\r\n\tat org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41)\r\n\tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:778)\r\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\r\n\tat java.base/java.lang.Thread.run(Thread.java:834)\r\nCaused by: java.lang.IndexOutOfBoundsException\r\n\tat java.base/java.nio.Buffer.checkIndex(Buffer.java:687)\r\n\tat java.base/java.nio.DirectByteBuffer.get(DirectByteBuffer.java:269)\r\n\tat org.apache.lucene.store.ByteBufferGuard.getByte(ByteBufferGuard.java:118)\r\n\tat org.apache.lucene.store.ByteBufferIndexInput$SingleBufferImpl.readByte(ByteBufferIndexInput.java:385)\r\n\tat org.apache.lucene.codecs.lucene70.Lucene70DocValuesProducer$10.get(Lucene70DocValuesProducer.java:599)\r\n\tat org.apache.lucene.codecs.lucene70.Lucene70DocValuesProducer$22.nextValue(Lucene70DocValuesProducer.java:1271)\r\n\tat org.elasticsearch.index.fielddata.ScriptDocValues$Longs.setNextDocId(ScriptDocValues.java:166)\r\n\tat org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:94)\r\n\tat org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:39)\r\n\tat org.elasticsearch.painless.PainlessScript$Script.execute(sortTargetsByFollowers:51)\r\n\t... 33 more\r\n"
        }
      }
    ],
    "stack_trace": "Failed to execute phase [query], all shards failed; shardFailures {[0qhbnJy2SiGaNbZn77bEYw][qz_targets_v2021_01][0]: RemoteTransportException[[ES-DEV1][172.16.3.4:10300][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: ScriptException[runtime error]; nested: IndexOutOfBoundsException; }\r\n\tat org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:296)\r\n\tat org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:133)\r\n\tat org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:259)\r\n\tat org.elasticsearch.action.search.InitialSearchPhase.onShardFailure(InitialSearchPhase.java:100)\r\n\tat org.elasticsearch.action.search.InitialSearchPhase.access$100(InitialSearchPhase.java:48)\r\n\tat org.elasticsearch.action.search.InitialSearchPhase$2.lambda$onFailure$1(InitialSearchPhase.java:220)\r\n\tat org.elasticsearch.action.search.InitialSearchPhase.maybeFork(InitialSearchPhase.java:174)\r\n\tat org.elasticsearch.action.search.InitialSearchPhase.access$000(InitialSearchPhase.java:48)\r\n\tat org.elasticsearch.action.search.InitialSearchPhase$2.onFailure(InitialSearchPhase.java:220)\r\n\tat org.elasticsearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:73)\r\n\tat org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:59)\r\n\tat org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:463)\r\n\tat org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1126)\r\n\tat org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1238)\r\n\tat org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1212)\r\n\tat org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:60)\r\n\tat org.elasticsearch.action.support.ChannelActionListener.onFailure(ChannelActionListener.java:56)\r\n\tat org.elasticsearch.search.SearchService$2.onFailure(SearchService.java:367)\r\n\tat org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:361)\r\n\tat org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:355)\r\n\tat org.elasticsearch.search.SearchService$4.doRun(SearchService.java:1117)\r\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\r\n\tat org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41)\r\n\tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:778)\r\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\r\n\tat java.base/java.lang.Thread.run(Thread.java:834)\r\nCaused by: ScriptException[runtime error]; nested: IndexOutOfBoundsException;\r\n\tat org.elasticsearch.painless.PainlessScript.convertToScriptException(PainlessScript.java:94)\r\n\tat org.elasticsearch.painless.PainlessScript$Script.execute(sortTargetsByFollowers:91)\r\n\tat org.elasticsearch.painless.ScriptImpl.run(ScriptImpl.java:104)\r\n\tat org.elasticsearch.painless.ScriptImpl.runAsDouble(ScriptImpl.java:109)\r\n\tat org.elasticsearch.search.sort.ScriptSortBuilder$2$1.doubleValue(ScriptSortBuilder.java:381)\r\n\tat org.elasticsearch.index.fielddata.FieldData$14.advanceExact(FieldData.java:572)\r\n\tat org.elasticsearch.index.fielddata.NumericDoubleValues$1.advanceExact(NumericDoubleValues.java:44)\r\n\tat org.apache.lucene.search.FieldComparator$DoubleComparator.getValueForDoc(FieldComparator.java:181)\r\n\tat org.apache.lucene.search.FieldComparator$DoubleComparator.copy(FieldComparator.java:200)\r\n\tat org.apache.lucene.search.MultiLeafFieldComparator.copy(MultiLeafFieldComparator.java:81)\r\n\tat org.apache.lucene.search.TopFieldCollector$SimpleFieldCollector$1.collect(TopFieldCollector.java:191)\r\n\tat org.apache.lucene.search.MultiCollector$MultiLeafCollector.collect(MultiCollector.java:174)\r\n\tat org.apache.lucene.search.MultiCollector$MultiLeafCollector.collect(MultiCollector.java:174)\r\n\tat org.apache.lucene.search.Weight$DefaultBulkScorer.scoreRange(Weight.java:247)\r\n\tat org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:225)\r\n\tat org.elasticsearch.search.internal.CancellableBulkScorer.score(CancellableBulkScorer.java:56)\r\n\tat org.apache.lucene.search.BulkScorer.score(BulkScorer.java:39)\r\n\tat org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:670)\r\n\tat org.elasticsearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:191)\r\n\tat org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:471)\r\n\tat org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:276)\r\n\tat org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:114)\r\n\tat org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:350)\r\n\tat org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:394)\r\n\tat org.elasticsearch.search.SearchService.access$100(SearchService.java:126)\r\n\tat org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:359)\r\n\t... 9 more\r\nCaused by: java.lang.IndexOutOfBoundsException\r\n\tat java.base/java.nio.Buffer.checkIndex(Buffer.java:687)\r\n\tat java.base/java.nio.DirectByteBuffer.get(DirectByteBuffer.java:269)\r\n\tat org.apache.lucene.store.ByteBufferGuard.getByte(ByteBufferGuard.java:118)\r\n\tat org.apache.lucene.store.ByteBufferIndexInput$SingleBufferImpl.readByte(ByteBufferIndexInput.java:385)\r\n\tat org.apache.lucene.codecs.lucene70.Lucene70DocValuesProducer$10.get(Lucene70DocValuesProducer.java:599)\r\n\tat org.apache.lucene.codecs.lucene70.Lucene70DocValuesProducer$22.nextValue(Lucene70DocValuesProducer.java:1271)\r\n\tat org.elasticsearch.index.fielddata.ScriptDocValues$Longs.setNextDocId(ScriptDocValues.java:166)\r\n\tat org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:94)\r\n\tat org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:39)\r\n\tat org.elasticsearch.painless.PainlessScript$Script.execute(sortTargetsByFollowers:51)\r\n\t... 33 more\r\n"
  },
  "status": 500
}
```
Again, note that the ascending sort works fine, I assume, cuz the cardinality is low in that range.  Presumably, if I paged through long enough, I'd hit it once the cardinality of the `followerKeys` was high enough to trigger the same condition.  Thanks for looking into this.

**Comment by rjernst** [comment] 2021-05-07 16:38
Adding the Search team, as this looks like maybe a problem inside Lucene.

The stack trace shows the call to SortedNumericDocValues.nextValue() is triggering this IOOBE.

```
"java.base/java.nio.Buffer.checkIndex(Buffer.java:687)",
"java.base/java.nio.DirectByteBuffer.get(DirectByteBuffer.java:269)",
"org.apache.lucene.store.ByteBufferGuard.getByte(ByteBufferGuard.java:118)",
"org.apache.lucene.store.ByteBufferIndexInput$SingleBufferImpl.readByte(ByteBufferIndexInput.java:385)",
"org.apache.lucene.codecs.lucene70.Lucene70DocValuesProducer$10.get(Lucene70DocValuesProducer.java:599)",      "org.apache.lucene.codecs.lucene70.Lucene70DocValuesProducer$22.nextValue(Lucene70DocValuesProducer.java:1271)",
"org.elasticsearch.index.fielddata.ScriptDocValues$Longs.setNextDocId(ScriptDocValues.java:166)",
```

The closest Lucene issue I could find is https://issues.apache.org/jira/browse/LUCENE-6170.

@tdoman Which version of Java and which GC implementation?

**Comment by stu-elastic** [comment] 2021-06-10 16:35
Removing the scripting label as this is a level below scripting.

**Comment by javanna** [comment] 2024-06-17 19:56
This sadly feel through the cracks. It seems to be a Lucene issue. If it still reproduces, would you please comment to this issue so we can look into it? I am closing it for now, but we will reopen as needed.

**Closed by javanna** 2024-06-17 19:56 UTC
Labels: >bug, :Search/Search, Team:Search, v6.8.13
