### ISSUE TITLE
Shard awareness leaves replica shards unassigned when racks are unevenly sized

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#12431] opened 2015-07-23 22:55 UTC
There are a few parts to this ticket:

**Functionality**
There is this logic (https://github.com/elastic/elasticsearch/blob/c57951780e0132c50b723d78038ab73e10d176c5/core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/AwarenessAllocationDecider.java#L222) which prevents the allocation of shards when the number of shards per unique node attribute used in the awareness (eg. rack_id) is exceeded (`if (currentNodeCount > (requiredCountPerAttribute + leftoverPerAttribute)) {`).

In this particular use case, the user has 69 nodes with an index that has 1 primary shard defined with 68 replicas (so 69 copies of the shard).  The expectation is that it will put 1 shard on each node.  The issue here is that it doesn't and it ends up leaving 2 copies unassigned.

For example, one of the rack_id's used in allocation awareness is associated to 5 different nodes in the cluster.  It ended up allocating 1 shard on 4 of the 5 nodes.  At this point, (currentNodeCount > (requiredCountPerAttribute + leftoverPerAttribute)), so it prevents the 5th node from getting a copy of this shard.  In this case averagePerAttribute is 2 (with 28 unique attributes) so requiredCountPerAttribute is 2.  totalLeftover is not 0, so leftoverPerAttribute is 1.  So 4 > 3 and it prevents the 5th node from getting a shard copy.

There is quite an uneven distribution of nodes per rack_id, some rack_ids in this setup has 1 node, others have up to 5 nodes in them.  The allocation decider logic is preventing all shards for that index from being allocated and leaving a few unassigned.

For this use case, the user is not that concerned about distribution of shards for this particular index across racks.  But awareness is currently enabled for the node/cluster and there does not appear to be a way to configure a specific index to be excluded from the awareness logic.

**Documentation**
Not much available on the above logic.

**Logging/Debugging**
This may get a bit verbose so I am not sure about the feasibility of it.  For troubleshooting purposes, it will be helpful if we can write a trace line with a bit more details than just the current message in the reroute explain ("explanation": "too many shards on nodes for attribute: [rack_id]").  Like it will be useful if it will tell you the problem index, how many shards are allowed, and how many are on there currently, etc..  Doesn't have to be logging either, maybe add to the explanation string that is returned by reroute explain to give some more specific information.

**Comment by clintongormley** [comment] 2015-07-27 09:02
@imotov @dakrone any thoughts on this one?

**Comment by dakrone** [comment] 2015-07-27 17:54
> Doesn't have to be logging either, maybe add to the explanation string that is returned by reroute explain to give some more specific information.

I added additional messages for this in #12490

**Comment by GlenRSmith** [comment] 2015-07-30 00:14
I think it makes sense to allow a client to interrogate the cluster for the state of shard distribution under the context of any/all awareness attributes, possibly including index-level allocation filtering.

Possibly something like this:

```
{
  "attributes": {
    "rack_id": {
      "rack_one": {
        "nodes": {
          "_all": {
            "logstash-2015.07.24": {
              "0": ["0", "2", "3"],
              "1": ["1", "2"],
              "2": ["0", "3"],
              "3": ["1"],
              "4": ["1", "3"]
            }
          },
          "abcxyz0123456": {
            "logstash-2015.07.24": ["0-0", "1-1", "2-0", "3-1", "4-1"]
          }
        }
      }
    }
  }
}
```

I'm not sure what endpoint is most logical to include it. Possibly cluster stats?

**Comment by clintongormley** [comment] 2015-07-30 15:22
It'd be nice to think of a better algorithm, so that we can deal with unevenly sized groups.

**Comment by ywelsch** [comment] 2018-04-18 09:36
Closing this as a duplicate of #12273. The balancer is greedy and does not take all options into account.

**Closed by ywelsch** 2018-04-18 09:36 UTC
Labels: :Distributed/Allocation, >docs, >enhancement, discuss
