### ISSUE TITLE
Error in visualization in v7.8.1 

### ISSUE THREAD

**Issue by LaygoMaricar** [elastic/elasticsearch#60655] opened 2020-08-04 14:44 UTC
**Elasticsearch version** (`bin/elasticsearch --7.8.1`):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
I got an error in displaying data in the data table.

![Capture](https://user-images.githubusercontent.com/38770888/89307791-1136b500-d6a4-11ea-86b6-2bffa9e4567a.PNG)

**Provide logs (if relevant)**:

**Comment by gwbrown** [comment] 2020-08-05 17:04
Thanks very much for your interest in Elasticsearch.

This is not a bug, but a limit on aggregations that Elasticsearch imposes to ensure that those aggregations don't destabilize your cluster.  This limit is controlled by [the `search.max_buckets` setting](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-settings.html).

If you want more assistance, there's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. If you believe that there is a bug in Kibana that is causing it to make aggregations which trigger this limit when they shouldn't, please [file an issue in the Kibana repo](https://github.com/elastic/kibana/issues/new/choose). For now, I'm going to close this issue as this does not appear to be an Elasticsearch bug.

**Closed by gwbrown** 2020-08-05 17:04 UTC
Labels: >bug, needs:triage
