### ISSUE TITLE
Suggest returned even when setting "suggest_mode" to be "missing"

### ISSUE THREAD

**Issue by czheo** [elastic/elasticsearch#11739] opened 2015-06-18 03:34 UTC
I think when setting `suggest_mode` to be `missing`, no suggestion should be returned if the term exists in the index. But it turns out not to behave like my expectation. Is it a bug or anything?

Below is what i did. (with elasticsearch 1.5)
```
# remove all
$ curl -XDELETE elastic:9200/*
{"acknowledged":true}

# index two documents
$ curl -XPOST elastic:9200/my_index/my_type -d '{"name": "shinagawa hotel"}'
{"_index":"my_index","_type":"my_type","_id":"AU4FdpnwDWV1B-oz3tLK","_version":1,"created":true}
$ curl -XPOST elastic:9200/my_index/my_type -d '{"name": "shirakawa hotel"}'
{"_index":"my_index","_type":"my_type","_id":"AU4Fdta7DWV1B-oz3tLL","_version":1,"created":true}
```
```
$ cat search.json
```
``` json
{
    "explain": true,
    "query": {
        "match": {
            "name": {
                "query": "shinagawa"
            }
        }
    },
    "suggest": {
        "my-suggest": {
            "text": "shinagawa",
            "term": {
                "field": "name",
                "suggest_mode": "missing"
            }
        }
    }
}
```
```
$ curl elastic:9200/my_index/_search?pretty -d@search.json
```
``` json
{
  "took" : 7,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 0.19178301,
    "hits" : [ {
      "_shard" : 3,
      "_node" : "7UoDQJWRQYqF4Gjq94LiMg",
      "_index" : "my_index",
      "_type" : "my_type",
      "_id" : "AU4FdpnwDWV1B-oz3tLK",
      "_score" : 0.19178301,
      "_source":{"name": "shinagawa hotel"},
      "_explanation" : {
        "value" : 0.19178301,
        "description" : "weight(name:shinagawa in 0) [PerFieldSimilarity], result of:",
        "details" : [ {
          "value" : 0.19178301,
          "description" : "fieldWeight in 0, product of:",
          "details" : [ {
            "value" : 1.0,
            "description" : "tf(freq=1.0), with freq of:",
            "details" : [ {
              "value" : 1.0,
              "description" : "termFreq=1.0"
            } ]
          }, {
            "value" : 0.30685282,
            "description" : "idf(docFreq=1, maxDocs=1)"
          }, {
            "value" : 0.625,
            "description" : "fieldNorm(doc=0)"
          } ]
        } ]
      }
    } ]
  },
  "suggest" : {
    "my-suggest" : [ {
      "text" : "shinagawa",
      "offset" : 0,
      "length" : 9,
      "options" : [ {
        "text" : "shirakawa",
        "score" : 0.7777778,
        "freq" : 1
      } ]
    } ]
  }
}
```
Here `shinagawa` is in the index of `name` field, but suggestion to it is not excluded.

**Comment by inqueue** [comment] 2015-06-18 06:02
Have a look at https://github.com/elastic/elasticsearch/issues/7472. They are looking for a repro there as well.

**Comment by clintongormley** [comment] 2015-06-18 18:07
Hi @czheo 

The reason for this is that you have two documents in two different shards.  Suggestions are calculated per shard, then merged.  So the term specified exists on one shard and is missing on the other, which is why it is included as a suggestion.

A similar problem exists with relevance when searching across a tiny collection of documents. See https://www.elastic.co/guide/en/elasticsearch/guide/current/relevance-is-broken.html

Duplicate of #7472

**Closed by clintongormley** 2015-06-18 18:07 UTC

**Comment by vidyaramanathan** [comment] 2017-03-22 23:31
Hi - I have a similar issue. Is there any solution for this problem other than going with one primary shard ? (since we may have million documents and need to scale out instead of scale in to get better results)

I've posted my concern here as well -
https://discuss.elastic.co/t/phrase-suggester-returned-suggestions-even-if-searched-keyword-is-in-the-index/79656
