### ISSUE TITLE
Failed to Install Windows Service in Directory with a Space

### ISSUE THREAD

**Issue by cstack89** [elastic/elasticsearch#89510] opened 2022-08-22 16:11 UTC
### Elasticsearch Version

8.3.3

### Installed Plugins

None

### Java Version

_bundled_

### OS Version

Windows 10 and Windows Server 2016

### Problem Description

When trying to install Elasticsearch as a service on Windows I get a 'C:\Program ' is not recognized...

### Steps to Reproduce

1. Download the elasticsearch Windows 8.3.3 zip file and copy it somewhere like C:\Program Files\storage\elasticsearch
2. Set environment variables (set JAVA_HOME=C:\Program Files\storage\elasticsearch\jdk ; set ES_START_TYPE=auto ; set ES_TMPDIR=C:\ProgramData\server\esTemp; set SERVICE_DISPLAY_NAME=My Elastic; set SERVICE_DESCRIPTION="My Elastic Service"
3. cd to C:\Program Files\storage\elasticsearch
4. Run bin\elasticsearch-service.bat install MyElastic

### Logs (if relevant)

bin\elasticsearch-service.bat install MyElastic
warning: ignoring JAVA_HOME=C:\Program Files\storage\elasticsearch\jdk; using bundled JDK
Installing service : MyElastic
Using ES_JAVA_HOME : C:\Program Files\storage\elasticsearch\jdk
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

ERROR: Failed installing 'MyElastic' service

**Comment by luigidellaquila** [comment] 2022-08-23 07:18
Hi @cstack89 

This is a known problem in v 8.3 (this issue is in fact a duplicate of https://github.com/elastic/elasticsearch/issues/89043).
For now, the only available work-around is to install Elasticsearch on a folder without whitespaces.

Thanks

Luigi

**Closed by luigidellaquila** 2022-08-23 07:18 UTC
Labels: >bug, Team:Core/Infra, :Core/Infra/CLI
