### ISSUE TITLE
NPE when fetching source from an index with _source disabled

### ISSUE THREAD

**Issue by marfago** [elastic/elasticsearch#20408] opened 2016-09-11 11:41 UTC
**Elasticsearch version**: 2.4.0

**Plugins installed**: [Marvel,Head,License,Delete-by-query]

**JVM version**: 1.8.0_91

**OS version**: linux ubuntu 14.04 - 4.5.7

**Description of the problem including expected versus actual behavior**:

I have 8 indexes, called url-0,url-1,...,url-8 with around 1B documents.
The template for each index is 

    {
        "template" : "url-*",
        "settings" : {            
            "number_of_shards"   : "1",
            "number_of_replicas" : "0",
            "refresh_interval"   : "180s"
        },
        "mappings" : {
            "url" : {
                "_all" : {"enabled" : false},
                "_timestamp" : {"enabled" : false},
                "_source": {"enabled": false},
                "_ttl" : { "enabled" : false },
                "properties" : {
                    "url" : {"type" : "string", "index": "not_analyzed", "store" : true},
                    "domain" : {"type": "string", "index" : "not_analyzed", "store" : false},
                    "scheme" : {"type": "string", "index" : "not_analyzed", "store" : false},
                    "parsedUrl" : {"type": "string", "index": "analyzed", "store": false},
                    "workerIndex": {"type": "integer", "store" : false},
                    "error": {"type": "boolean", "store" : false},
                    "banned": {"type": "boolean", "store" : false},
                    "timestamp": {"type": "date", "store" : true},
                    "depth": {"type": "integer", "store" : true},
                    "processed": {"type": "boolean", "store" : false}

                }
            }
        }

When I execute the query

`curl -XPOST localhost:9200/url/url/_search?search_type=scan&scroll=5m&size=50&_source=url&preference=_shards:0;_prefer_node:XqfWWAGFRdCPo98qIeFfGg`

I get

    {

        "_scroll_id": "c2Nhbjs4OzMyNzUyNzpYcWZXV0FHRlJkQ1BvOThxSWVGZkdnOzQ3MTkzODplTDZZa3AxSlRVQ3lHd1FMTjR3T3NnOzgxMzY4ODpwSHVGaVJRM1JSYTIwaWRxNTlFbXNBOzgxMzY4NzpwSHVGaVJRM1JSYTIwaWRxNTlFbXNBOzgxMzY4NjpwSHVGaVJRM1JSYTIwaWRxNTlFbXNBOzQ3MTkzOTplTDZZa3AxSlRVQ3lHd1FMTjR3T3NnOzMxNDc1NDpqbUdTWGRmWVRTdWFIT1FFSmZ1WVN3OzgxMzY4OTpwSHVGaVJRM1JSYTIwaWRxNTlFbXNBOzE7dG90YWxfaGl0czoxMDEzOTAyNTk1Ow==",
        "took": 8221,
        "timed_out": false,
        "_shards": {
            "total": 8,
            "successful": 8,
            "failed": 0
        },
        "hits": {
            "total": 1013902595,
            "max_score": 0,
            "hits": [ ]
        }
    }

but

If I query for the scrollId I get an error and a NPE on the server.

    culr -XPOST localhost:9200/_search/scroll?scroll=1m -d '
    {
      "scroll_id": "c2Nhbjs4OzMyNzUyNzpYcWZXV0FHRlJkQ1BvOThxSWVGZkdnOzQ3MTkzODplTDZZa3AxSlRVQ3lHd1FMTjR3T3NnOzgxMzY4ODpwSHVGaVJRM1JSYTIwaWRxNTlFbXNBOzgxMzY4NzpwSHVGaVJRM1JSYTIwaWRxNTlFbXNBOzgxMzY4NjpwSHVGaVJRM1JSYTIwaWRxNTlFbXNBOzQ3MTkzOTplTDZZa3AxSlRVQ3lHd1FMTjR3T3NnOzMxNDc1NDpqbUdTWGRmWVRTdWFIT1FFSmZ1WVN3OzgxMzY4OTpwSHVGaVJRM1JSYTIwaWRxNTlFbXNBOzE7dG90YWxfaGl0czoxMDEzOTAyNTk1Ow"
    }'

result:

    {

        "_scroll_id": "c2NhbjswOzE7dG90YWxfaGl0czoxMDEzOTAyNTk1Ow==",
        "took": 105,
        "timed_out": false,
        "_shards": {
            "total": 8,
            "successful": 0,
            "failed": 8,
            "failures": [
                {
                    "shard": -1,
                    "index": null,
                    "reason": {
                        "type": "null_pointer_exception",
                        "reason": null
                    }
                }
            ]
        },
        "hits": {
            "total": 1013902595,
            "max_score": 0,
            "hits": [ ]
        }

    }

And in the logs:

    RemoteTransportException[[es-1][][indices:data/read/search[phase/scan/scroll]]]; nested: NullPointerException;
    Caused by: java.lang.NullPointerException
            at org.elasticsearch.search.fetch.source.FetchSourceSubPhase.hitExecute(FetchSourceSubPhase.java:79)
            at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:188)
            at org.elasticsearch.search.SearchService.executeScan(SearchService.java:342)

Maybe it is a problem related to the **_source** parameter in the query and the fact that the _source field is disabled in the mapping. If I remove the **_source** field from the query, it works fine.

PS: The above query was originated by Spark with the elasticsearch-spark_2.11 (v.2.4.0) library.

**Comment by tlrx** [comment] 2016-09-12 07:15
This looks very similar to #20093

**Comment by marfago** [comment] 2016-09-12 08:50
Yes I agree.  It affects v2.4 too.

**Comment by javanna** [comment] 2016-09-12 09:32
thanks for pointing this out. Fixed by #20093 . Fix will be part of the next 5.0 release. 5.0.0-alpha5 is still affected. 

The problem manifested only when _source was asked for explicitly. I am not too happy with not returning any error and simply skipping the _source part of the request, I would have rather thrown an error there. Thoughts?

**Comment by tlrx** [comment] 2016-09-12 09:45
> The problem manifested only when _source was asked for explicitly. I am not too happy with not returning any error and simply skipping the _source part of the request, I would have rather thrown an error there. Thoughts?

I hate to say that but I think it should be configurable on a per request basis? When querying multiple indices you might want to return `foo` for some docs and `bar` for other docs while searching on a third field. And sometimes you query well defined indices and a missing source field must just throw an error in that case.

**Comment by javanna** [comment] 2016-09-12 10:02
@tlrx what should be configurable? The behaviour? Either throw an error or skip without barfing? I am afraid I don't follow why skipping some part of the request that cannot be performed would help. You are going to run into problems when reading the response anyway as some part will be missing.

**Comment by marfago** [comment] 2016-09-12 10:17
In my case, _source is disabled but some fields are still stored. So it is definitely still possible to retrieve some fields event though _source is disabled.

**Comment by javanna** [comment] 2016-09-12 10:21
@marfago then you should use `fields` rather than `_source`. `_source` will always try to extract fields out of the source field and will return only those rather than the whole source. Fields will instead get the stored fields from lucene directly. Not sure whether the spark integration supports any of this.

**Comment by marfago** [comment] 2016-09-12 11:31
@javanna :thank you for the clarification. 
What if:
1)keep as default the current behaviour, just handling/wrapping the NPE with a more meaningful message/exception 
2)introduce a boolean query parameter (a sort of ignore_disabled_source) in order to change behaviour and silently ignore indexes with disabled _source
3)open a new issue in elasticsearch-spark for handling the "fields" parameter.

**Comment by javanna** [comment] 2016-09-12 12:07
> 1)keep as default the current behaviour, just handling/wrapping the NPE with a more meaningful message/exception 

the current behaviour after the fix is "ignore the _source parameter if _source is disabled", I don't like that

> 2)introduce a boolean query parameter (a sort of ignore_disabled_source) in order to change behaviour and silently ignore indexes with disabled _source

I tend to be against this, I don't think it is worth adding yet another request parameter for such an edge case, in the spirit of #11172.

> 3)open a new issue in elasticsearch-spark for handling the "fields" parameter.

thanks for doing that ;)

**Comment by tlrx** [comment] 2016-09-12 12:21
> I tend to be against this, I don't think it is worth adding yet another request parameter for such an edge case, in the spirit of #11172.

This is a very good point @javanna and the rationale behind #11172 is good too. I agree we should throw an error here but I'd like to be sure how we handle similar case with `fields` or `stored_fields`.

**Comment by javanna** [comment] 2016-09-12 12:23
thanks Tanguy, maybe @clintongormley has some opinion too on this

**Comment by s1monw** [comment] 2016-09-12 12:59
++ to what @javanna said. If you disable source and you use a feature that needs it you fail. Hard!

**Comment by marfago** [comment] 2016-09-12 14:51
@javanna and @s1monw In my use case (see the description), the first query succeeds returning an apparently valid scrollId, then the second query fails because the _source is disabled. 
I think it should fail earlier, preventing the scrollId to be created.

**Comment by javanna** [comment] 2016-09-12 15:03
I see what you mean @marfago , I am afraid what you request is not that easy to achieve on our end, but I will check whether we already have some validation mechanism in place that we can leverage. The problem is that we throw the error once we try and fetch fields from the source, which is part of the fetch phase. The first phase of search, query, works without any issue. Once the top hits need to be fetched, the problem arises. That is why the first scroll request succeeds in your case, cause there is no fetch phase as part of that first step.

**Closed** 2016-09-12 16:36 UTC
Labels: bug
