### ISSUE TITLE
Backslash escaping inconsistent between string functions and operators (e.g. LIKE) in ES|QL

### ISSUE THREAD

**Issue by abulhol** [elastic/elasticsearch#118932] opened 2024-12-18 10:04 UTC
### Elasticsearch Version

8.16.1

### Java Version

openjdk version "1.8.0_432"

### OS Version

5.15.0-126-generic #136-Ubuntu

### Problem Description

I am using Winlogbeat with Elasticsearch and running queries with ES|QL. 

I ran into issues because double quotes need to be escaped differently when using a wildcard operator opposed to string operators. 

This is fairly confusing and not made clear in the documentation. 
I saw that there has been activity around this last year, e.g.: https://github.com/elastic/elasticsearch/issues/101106
If this is going to remain like this, would it be possible to at least improve the documentation?

### Steps to Reproduce

I run the queries on the command line using `curl`. 

The following examples target the field `process.executable` which has the following mapping (`mappings.properties.process.properties.executable`):
```
{
  "type": "keyword",
  "ignore_above": 1024,
  "fields": {
    "text": {
      "type": "match_only_text"
    }
  }
}
```

If I query for a string with backslashes using e.g. `starts_with`, this query:
`{"query": "from * metadata _id, _index, _version | where starts_with(process.executable, \"C:\\\\Windows\\\\System32\\\\\")"}`
works and matches e.g. `"C:\\Windows\\System32\\RuntimeBroker.exe"`

If I use a wildcard query with `LIKE` instead, this one here fails:
`'{"query": "from * metadata _id, _index, _version | where process.executable like \"C:\\\\Windows\\\\System32\\\\*\""}'`
with `Invalid sequence - escape character is not followed by special wildcard char`. 

The query works if I double the number of escape characters:
`json_query='{"query": "from * metadata _id, _index, _version | where process.executable like \"C:\\\\\\\\Windows\\\\\\\\System32\\\\\\\\*\""}'`
or if I use triple quotes around the string:
`{"query": "from * metadata _id, _index, _version | where process.executable like \"\"\"C:\\\\Windows\\\\System32\\\\*\"\"\""}'`

**Comment by alex-spies** [comment] 2024-12-19 10:27
Hi @abulhol and thanks for your bug report! I highly appreciate your detailed reproducer.

I believe the behavior here is actually expected. The reason is that `LIKE` permits wildcards `*` and `?`, and thus a literal `*` or `?` needs to be escaped with a `\`. For this reason, also `\` itself needs to be escaped. `STARTS_WITH` does not permit wildcards, and therefore backslashes do not need additional escaping. As a result, you need double the number of backslashes in `LIKE` compared to `STARTS_WITH`.

Our [docs](https://www.elastic.co/guide/en/elasticsearch/reference/master/esql-functions-operators.html#esql-like-operator) for `LIKE` have an example that demonstrates this as well, and recommend usage of triple quotes like in your example above.

In the example of Windows paths, the required levels of escaping can be a bit unfortunate. Note that, to type a single literal backslash in a request sent via cURL, you need 4 backslashes:
- 2 backslashes to type a literal backslash in the first place
- double the number because of escaping in the JSON, so 4

That means that a single literal backslash in `LIKE` for a request sent via cURL requires 8 backslashes, because `LIKE` has an additional layer of escaping. Which is consistent with your examples.

Since this doesn't seem to be a bug, I will close this. Let me know if I can help in any other way!

**Closed by alex-spies** 2024-12-19 10:27 UTC
Labels: >bug, Team:Analytics, :Analytics/ES|QL

**Comment by abulhol** [comment] 2024-12-19 12:49
@alex-spies Thank you for the swift reply!
I agree that it is logical, but you could extend the docs a bit to make this difference a bit clearer (like you did here). Maybe even using an example with a Windows path, because this is a quite frequent use case in Elastic Security.

**Comment by alex-spies** [comment] 2024-12-19 13:29
You are right! I opened a docs issue to track this here: https://github.com/elastic/elasticsearch/issues/119081
