### ISSUE TITLE
thirdPartyAudit failure on analysis api plugin

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#90862] opened 2022-10-13 09:12 UTC
### CI Link

https://gradle-enterprise.elastic.co/s/ssqkx6qintb4a

### Repro line

n/a

### Does it reproduce?

Didn't try

### Applicable branches

main

### Failure excerpt

```
WARNING: Class 'java.lang.foreign.ValueLayout$OfFloat' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.ValueLayout$OfFloat'). Please fix the classpath! |  
-- | --
  | ==end of forbidden APIs== |  
  | Missing classes: |  
  | * java.lang.foreign.MemorySegment |  
  | * java.lang.foreign.MemorySession |  
  | * java.lang.foreign.ValueLayout |  
  | * java.lang.foreign.ValueLayout$OfByte |  
  | * java.lang.foreign.ValueLayout$OfFloat |  
  | * java.lang.foreign.ValueLayout$OfInt |  
  | * java.lang.foreign.ValueLayout$OfLong |  
  | * java.lang.foreign.ValueLayout$OfShort
```

It looks as though forbidden APIs can't load the preview classes in the lucene MR-JAR

**Comment by ywangd** [comment] 2022-10-27 04:47
Failed again on main https://gradle-enterprise.elastic.co/s/fcmlasitvunoy

**Comment by fcofdez** [comment] 2022-11-02 11:26
Another failure: https://gradle-enterprise.elastic.co/s/h5mvx53aymyrw

**Comment by breskeby** [comment] 2022-11-21 12:15
This seems like a duplicate of https://github.com/elastic/elasticsearch/issues/91264

**Closed by breskeby** 2022-11-21 12:15 UTC
Labels: :Delivery/Build, >test-failure, Team:Delivery
