### ISSUE TITLE
[CI] Docs failure for `resume-auto-follow-pattern.asciidoc`

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#48410] opened 2019-10-23 15:22 UTC
```
java.lang.AssertionError: Failure at [reference/ccr/apis/auto-follow/resume-auto-follow-pattern:20]: expected [2xx] status code but api [raw[method=PUT path=_ccr/auto_follow/my_auto_follow_pattern]] returned [400 Bad Request] [{"error":{"root_cause":[{"type":"no_such_remote_cluster_exception","reason":"no such remote cluster: [remote_cluster]", "stacktrace" : "..."}]}}]
```

```
REPRODUCE WITH: ./gradlew ':docs:integTestRunner' --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/ccr/apis/auto-follow/resume-auto-follow-pattern/line_70}" \
  -Dtests.seed=CD879B92519177E2 \
  -Dtests.security.manager=true \
  -Dtests.locale=th-TH-u-nu-thai-x-lvariant-TH \
  -Dtests.timezone=America/Argentina/San_Juan \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

Build scan is here: https://gradle-enterprise.elastic.co/s/ubisjve3sdofk/console-log?task=:docs:integTestRunner
Has failed a few times in the past few days in master, 7.5 and 7.x

**Comment by ywelsch** [comment] 2019-10-23 15:43
Duplicate of #47718

**Closed by ywelsch** 2019-10-23 15:43 UTC
Labels: :Distributed/CCR, >test-failure
