### ISSUE TITLE
Unable to recover from  shards initializing

### ISSUE THREAD

**Issue by digitalrinaldo** [elastic/elasticsearch#17877] opened 2016-04-20 02:39 UTC
**Elasticsearch version**: 2.3.1

**JVM version**:8u77

**OS version**:OL 7u1 and Solaris 11.2  

**Description of the problem including expected versus actual behavior**:
Cluster is operating normally and runs into an out of space condition on a node, that is the 85% value is reached. Shard stays in initializing state and following does not clear the condition.

1) Attempts to reassign ( Message below)
2) Reboots of nodes with shard having issue resident
3) Change of replicas from 4 to 2

**Steps to reproduce**:
 1. Run a cluster and fill up the disk on some node
 2. Have other indices with continuous writes
 3. wait until shards start showing unassigned

**Provide logs (if relevant)**:

2016-04-19 22:32:35] {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"[move_allocation] can't move [logstash-feeder-df-2016.04][1], shard is not started (state = INITIALIZING]"}],"type":"illegal_argument_exception","reason":"[move_allocation] can't move [logstash-feeder-df-2016.04][1], shard is not started (state = INITIALIZING]"},"status":400}

**Comment by clintongormley** [comment] 2016-04-20 12:18
Duplicate of https://github.com/elastic/elasticsearch/pull/17698

**Closed by clintongormley** 2016-04-20 12:18 UTC
