### ISSUE TITLE
DateUtilsTests#testTimezoneIds can fail assertion

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#72039] opened 2021-04-21 16:38 UTC
**Build scan**: https://gradle-enterprise.elastic.co/s/5c2nzd4cpqb34

**Repro line**:
```
./gradlew ':server:test' --tests "org.elasticsearch.common.time.DateUtilsTests.testTimezoneIds" \
    -Dtests.seed=148AFC75F556CC5E   -Dtests.locale=zh   -Dtests.timezone=Asia/Tbilisi   -Druntime.java=17
```

**Reproduces locally?**: no, but I only tried without `-Druntime.java=17`

**Applicable branches**: master

**Failure history**: failed 3 times over past couple days

**Failure excerpt**:
```
    java.lang.AssertionError: Australia/Currie
    Expected: <36000000>
         but: was <39600000>
        at __randomizedtesting.SeedInfo.seed([148AFC75F556CC5E:C86FA1EFB8FA8578]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.elasticsearch.common.time.DateUtilsTests.testTimezoneIds(DateUtilsTests.java:50)
```

**Comment by jtibshirani** [comment] 2021-04-21 17:24
I muted this on `master` in `541546a14a748e1596f3582d9eb204d77e4de0cd`.

**Comment by rjernst** [comment] 2021-04-21 18:41
Thanks for muting Julie. I think this is a duplicate of https://github.com/elastic/elasticsearch/issues/72028.

**Closed by rjernst** 2021-04-21 18:41 UTC
Labels: :Core/Infra/Core, >test-failure, Team:Core/Infra

**Comment by jtibshirani** [comment] 2021-04-21 19:17
Oops, thanks for deduplicating.
