### ISSUE TITLE
Configuration API endpoint

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#10713] opened 2015-04-22 01:06 UTC
It'd be really useful if there was a single endpoint that could be called that gathers all the config from nodes in the cluster as well as any cluster level config, this includes the local elasticsearch.yml from all nodes.

**Comment by markwalkom** [comment] 2015-07-28 23:57
This may be related to https://github.com/elastic/elasticsearch/issues/6732

**Comment by eskibars** [comment] 2016-01-13 21:36
Closing as a duplicate of #6732

**Closed by eskibars** 2016-01-13 21:36 UTC
Labels: :Settings, discuss, feature
