### ISSUE TITLE
Inconsistency with geo point type in the fields api

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#72249] opened 2021-04-26 15:17 UTC
I'm seeing an inconsistency in the response of the fields api when I have a geo point mapped as a standard field versus a geo point mapped as a runtime field.

```
        "fields" : {
          "rgeopoint" : [
            "45.0, 70.49999998882413"
          ],
          "fgeopoint" : [
            {
              "coordinates" : [
                70.5,
                45.0
              ],
              "type" : "Point"
            }
          ]
        }
```

I produced this response by executing the following curl commands against 8.0:

```
curl -X PUT "localhost:9200/test/?pretty" -H 'Content-Type: application/json' -d'
{
  "mappings": {
    "properties": {
      "fboolean":  {"type": "boolean"},
      "fdate":     {"type": "date"},
      "fdouble":   {"type": "double"},
      "fgeopoint": {"type": "geo_point"},
      "fip":       {"type": "ip"},
      "fkeyword":  {"type": "keyword"},
      "flong":     {"type": "long"}
    },
    "runtime": {
      "rboolean": {
        "type": "boolean",
        "script": {
          "source": "emit(doc[\"fboolean\"].value)"
        }
      },
      "rdate": {
        "type": "date",
        "script": {
          "source": "emit(doc[\"fdate\"].value.toInstant().toEpochMilli())"
        }
      },
      "rdouble": {
        "type": "double",
        "script": {
          "source": "emit(doc[\"fdouble\"].value)"
        }
      },
      "rgeopoint": {
        "type": "geo_point",
        "script": {
          "source": "emit(doc[\"fgeopoint\"].value.lat, doc[\"fgeopoint\"].value.lon)"
        }
      },
      "rip": {
        "type": "ip",
        "script": {
          "source": "emit(doc[\"fip\"].value)"
        }
      },
      "rkeyword": {
        "type": "keyword",
        "script": {
          "source": "emit(doc[\"fkeyword\"].value)"
        }
      },
      "rlong": {
        "type": "long",
        "script": {
          "source": "emit(doc[\"flong\"].value)"
        }
      }
    }
  }
}
'

curl -X POST "localhost:9200/test/_doc/?pretty" -H 'Content-Type: application/json' -d'
{
  "fdate": "2021-11-15T13:12:00Z",
  "fkeyword": "blah",
  "fboolean": true,
  "fdouble": 1.0,
  "fgeopoint": "45.0,70.5",
  "fip": "127.0.0.1",
  "flong": "-1"
}
'

curl -X GET "localhost:9200/test/_search?pretty" -H 'Content-Type: application/json' -d'
{
  "fields": [
    "fgeopoint",
    "rgeopoint"
  ],
  "_source": false
}
'
```

**Comment by drempapis** [comment] 2024-10-23 10:02
I reproduced the issue against the v8.0.0 version. However, the behavior looks correct for v8.15.0+ 

For the query
```
GET test/_search
{
  "fields": [
    "fgeopoint",
    "rgeopoint"
  ],
  "_source": false
}
```
The response under the fields is 
```
"fields":{
   "rgeopoint":[
      {
         "coordinates":[
            70.49999998882413,
            45
         ],
         "type":"Point"
      }
   ],
   "fgeopoint":[
      {
         "coordinates":[
            70.5,
            45
         ],
         "type":"Point"
      }
   ]
}
```
In this scenario, it is worth spending some time debugging/inspecting the code and creating tests (if not already provided)

**Comment by drempapis** [comment] 2024-10-25 13:09
The response format has been updated in this work #85449

**Comment by drempapis** [comment] 2024-10-25 13:13
@javanna, there are tests to validate such behavior, such as
```
runtime-fields-common/src/yamlRestTest/resources/rest-api-spec/test/runtime_fields/100_geo_point.yml
```
Should I close this issue?

**Comment by javanna** [comment] 2024-10-29 10:44
Great catch @drempapis and good news. After all, this issue looks like a duplicate of #85245 . I think we are good, we can close it.

**Closed** 2024-10-29 10:56 UTC
Labels: >bug, :Search Foundations/Mapping, priority:normal, Team:Search Foundations
