### ISSUE TITLE
More verbose geo parse errors

### ISSUE THREAD

**Issue by Destroy666x** [elastic/elasticsearch#38282] opened 2019-02-03 14:18 UTC
**Describe the feature**: right now the "failed to parse" error isn't too useful and you have to debug the reason of failed parsing manually. Please add the exact reason of why parsing point/shape fails.

**Comment by atorok** [comment] 2019-02-04 07:16
thank you   for you  interest in Elasticsearch @Destroy666x! It  would help if you could provide some more specific examples of the API calls and errors you are getting.

**Comment by Destroy666x** [comment] 2019-02-05 15:36
Sure. I.e. on 6.3.x -> 6.4.0 transition a change was added that started requiring coordinates as floats in GeoJSON - my code had them as strings and I didn't even realize. What ES returned as error was https://github.com/elastic/elasticsearch/blob/68149b6058a720ec891974e8a6982c5e480fb9f1/server/src/main/java/org/elasticsearch/index/mapper/GeoShapeFieldMapper.java#L122  which only let me know of the name of the single shape field in the document and I had to debug the request manually to find the cause. Something like `Coordinates are required to be floats.` or at least `string found, float expected` at the end would save developers time.

**Comment by imotov** [comment] 2019-02-12 15:08
@Destroy666x Could you give a more specific example. I am trying to reproduce this error with master using the following example and this is what I am getting:
```
DELETE test
PUT test
{
  "mappings": {
      "properties": {
        "shape": {
          "type": "geo_shape"
        }
      }
  }
}

PUT test/_doc/1
{
  "shape": {
        "type" : "point",
        "coordinates" : [-77.03653, "38.897676"]
  }
}
```
This returns me an error message:
```
{
  "error": {
    "root_cause": [
      {
        "type": "parse_exception",
        "reason": "geo coordinates must be numbers"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "failed to parse field [shape] of type [geo_shape]",
    "caused_by": {
      "type": "parse_exception",
      "reason": "geo coordinates must be numbers"
    }
  },
  "status": 400
}
```
I get the same on the 6.5.4. In both cases we have:
```
    "root_cause": [
      {
        "type": "parse_exception",
        "reason": "geo coordinates must be numbers"
      }
    ]
```

What is my repro missing?

**Comment by imotov** [comment] 2019-02-19 14:21
@Destroy666x any comments?

**Comment by imotov** [comment] 2019-03-13 19:59
Since we didn't receive any feedback for almost a month, I am going to close this issue for now. Please, feel free to reopen if you have any additional information or can show a better way to reproduce this issue.

**Closed by imotov** 2019-03-13 19:59 UTC
Labels: :Analytics/Geo, >enhancement, feedback_needed, v8.0.0
