### ISSUE TITLE
[CI] Multi-node test timeout on Fedora 32

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#74076] opened 2021-06-14 15:03 UTC
SmokeTestMultiNodeClientYamlTestSuiteIT test {yaml=field_caps/10_basic/Get object and nested field caps} failing

Timeout in 7.x on Fedora 32. May be related to: https://github.com/elastic/elasticsearch/issues/73073.

This particular failure isn't a multi-versioned cluster, so didn't update existing issue.

**Build scan:**
https://gradle-enterprise.elastic.co/s/uizpc2d4swptm/tests/:qa:smoke-test-multinode:integTest/org.elasticsearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT/test%20%7Byaml=field_caps%2F10_basic%2FGet%20object%20and%20nested%20field%20caps%7D

**Reproduction line:**
`./gradlew ':qa:smoke-test-multinode:integTest' --tests "org.elasticsearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT.test {yaml=field_caps/10_basic/Get object and nested field caps}" -Dtests.seed=3DA62AC7C90AAC53 -Dtests.locale=es-MX -Dtests.timezone=Etc/GMT+7 -Druntime.java=8`

**Applicable branches:**
7.x

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT&tests.test=test%20%7Byaml%3Dfield_caps/10_basic/Get%20object%20and%20nested%20field%20caps%7D

**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([3DA62AC7C90AAC53]:0)

```

**Comment by benwtrent** [comment] 2021-06-14 16:19
Another similar failure: https://gradle-enterprise.elastic.co/s/mgkxb34x3xrf2

**Comment by mark-vieira** [comment] 2021-06-16 17:21
Closing this as a duplicate of https://github.com/elastic/elasticsearch/issues/73073. In the end the root cause here is slow test execution on Fedora 32.

**Closed by mark-vieira** 2021-06-16 17:21 UTC
Labels: :Delivery/Build, >test-failure, Team:Delivery
