### ISSUE TITLE
[CI] AsyncEsqlQueryActionIT testFinishingBeforeTimeoutKeep failing

### ISSUE THREAD

**Issue by luigidellaquila** [elastic/elasticsearch#107343] opened 2024-04-11 07:45 UTC
**Build scan:**
https://gradle-enterprise.elastic.co/s/dderk4k4luvic/tests/:x-pack:plugin:esql:internalClusterTest/org.elasticsearch.xpack.esql.action.AsyncEsqlQueryActionIT/testFinishingBeforeTimeoutKeep

**Reproduction line:**
```
./gradlew ':x-pack:plugin:esql:internalClusterTest' --tests "org.elasticsearch.xpack.esql.action.AsyncEsqlQueryActionIT.testFinishingBeforeTimeoutKeep" -Dtests.seed=8FE38D79593AAECC -Dtests.locale=sl-SI -Dtests.timezone=GB -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
[Failure dashboard for `org.elasticsearch.xpack.esql.action.AsyncEsqlQueryActionIT#testFinishingBeforeTimeoutKeep`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testFinishingBeforeTimeoutKeep'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.esql.action.AsyncEsqlQueryActionIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
org.elasticsearch.ResourceNotFoundException: sink exchanger for id [dS0IlzSsSjq8ykLPZD42ng:53] doesn't exist

  at org.elasticsearch.compute.operator.exchange.ExchangeService.getSinkHandler(ExchangeService.java:109)
  at org.elasticsearch.xpack.esql.plugin.ComputeService.runComputeOnDataNode(ComputeService.java:722)
  at org.elasticsearch.xpack.esql.plugin.ComputeService$DataNodeRequestHandler.messageReceived(ComputeService.java:792)
  at org.elasticsearch.xpack.esql.plugin.ComputeService$DataNodeRequestHandler.messageReceived(ComputeService.java:759)
  at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
  at org.elasticsearch.transport.InboundHandler.doHandleRequest(InboundHandler.java:288)
  at org.elasticsearch.transport.InboundHandler$1.doRun(InboundHandler.java:301)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
  at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by alex-spies** [comment] 2024-04-18 13:48
@ChrisHegarty , you're probably best to assess this - could please you check if this is a blocker?

**Comment by ChrisHegarty** [comment] 2024-04-19 09:18
closing as a duplicate of #106426

**Closed by ChrisHegarty** 2024-04-19 09:18 UTC
Labels: blocker, >test-failure, Team:Analytics, :Analytics/ES|QL
