### ISSUE TITLE
[CI] GeoIpDownloaderIT testUseGeoIpProcessorWithDownloadedDBs failing

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#74358] opened 2021-06-21 12:00 UTC
**Build scan:**
https://gradle-enterprise.elastic.co/s/olo4rnrjasm4w/tests/:modules:ingest-geoip:internalClusterTest/org.elasticsearch.ingest.geoip.GeoIpDownloaderIT/testUseGeoIpProcessorWithDownloadedDBs

https://gradle-enterprise.elastic.co/s/ql6aurcrkfw6e

**Reproduction line:**
`./gradlew ':modules:ingest-geoip:internalClusterTest' --tests "org.elasticsearch.ingest.geoip.GeoIpDownloaderIT.testUseGeoIpProcessorWithDownloadedDBs" -Dtests.seed=A1C4413ACE07BB5E -Dtests.locale=en-CA -Dtests.timezone=W-SU -Druntime.java=11`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.ingest.geoip.GeoIpDownloaderIT&tests.test=testUseGeoIpProcessorWithDownloadedDBs

I found 2 failures in the last 7 days [build-stats](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testUseGeoIpProcessorWithDownloadedDBs),sort:!(time,desc)))

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: "Tumba"
     but: was "Linköping"

  at __randomizedtesting.SeedInfo.seed([A1C4413ACE07BB5E:E29CB27911159C49]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.ingest.geoip.GeoIpDownloaderIT.testUseGeoIpProcessorWithDownloadedDBs(GeoIpDownloaderIT.java:231)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:834)

```

**Comment by davidkyle** [comment] 2021-06-21 15:40
Muted in #74358

**Comment by pgomulka** [comment] 2021-06-23 13:51
failed in 7.x https://gradle-enterprise.elastic.co/s/tb5eobsko6fq6
the same starcktrace as in master
```
./gradlew ':modules:ingest-geoip:internalClusterTest' --tests "org.elasticsearch.ingest.geoip.GeoIpDownloaderIT.testUseGeoIpProcessorWithDownloadedDBs" -Dtests.seed=69EF3382EDC4F877 -Dtests.locale=zh-SG -Dtests.timezone=Etc/GMT-2 -Druntime.java=8
```
does not reproduce locally for me

it is related to https://github.com/elastic/elasticsearch/issues/69972
the logging was still trace in 7.x
@martijnvg I muted the test for the time being. You can see the logs in build scan

muted in https://github.com/elastic/elasticsearch/pull/74491

**Comment by martijnvg** [comment] 2021-06-23 14:25
Thanks. I will look into this test failure tomorrow.

**Comment by martijnvg** [comment] 2021-06-24 12:45
The test fails, because the geo location data of the new databases is used instead of the old geo location data. The old geo location data is expected, because the database downloader shouldn't be active/running.

Looking at the latest failure, I suspect this is a timing related test issue. At the end of each test, the databases managed by the geoip downloader is cleaned (by disabling the geoip downloader). But the teardown logic doesn't wait for the files to be removed in geoip tmp folder on each ingest node. So it could be that the test uses the new database files provided by the geoip downloader instead of the old builtin database files.

I think the teardown logic should wait for the files to be really removed from the geoip ip tmp dir.

**Comment by gwbrown** [comment] 2021-07-14 20:49
Reopening this because it failed [again on my PR today](https://gradle-enterprise.elastic.co/s/c2sdhoiwrf2fo/tests/:modules:ingest-geoip:internalClusterTest/org.elasticsearch.ingest.geoip.GeoIpDownloaderCliIT/testUseGeoIpProcessorWithDownloadedDBs?top-execution=1) which is up to date with `master`, and it's failed 3 times in the past 2 days (once on master, twice on PRs).

**Comment by probakowski** [comment] 2021-07-14 23:03
Failures above are different than original one (it's in `GeoIpDownloaderCliIT` not `GeoIpDownloaderIT`) and they are likely connected to failing `GeoIpDownloaderCliIT.testInvalidTimestamp` which will be fixed by https://github.com/elastic/elasticsearch/pull/75330

**Closed** 2021-07-14 23:27 UTC
Labels: :Core/Features/Features, >test-failure, Team:Core/Features
