### ISSUE TITLE
[CI] LockObtainFailedException during rolling-upgrade tests

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#103839] opened 2024-01-03 07:55 UTC
### CI Link

https://gradle-enterprise.elastic.co/s/g3w5fhrvbrvus

### Repro line

`./gradlew  :x-pack:qa:rolling-upgrade:v8.12.0#oneThirdUpgradedTest`

### Does it reproduce?

Didn't try

### Applicable branches

8.12

### Failure excerpt

```
=== Log output of node `node{:x-pack:qa:rolling-upgrade:v8.12.0-2}` ===
»    ↓ errors and warnings from /dev/shm/bk/bk-agent-prod-gcp-1704267709785516042/elastic/elasticsearch-pull-request/x-pack/qa/rolling-upgrade/build/testclusters/v8.12.0-2/logs/es.out ↓
» [2024-01-03T07:48:22,794][INFO ][o.e.x.s.a.s.FileRolesStore] [v8.12.0-2] updated roles (roles file [/dev/shm/bk/bk-agent-prod-gcp-1704267709785516042/elastic/elasticsearch-pull-request/x-pack/qa/rolling-upgrade/build/testclusters/v8.12.0-2/config/roles.yml] changed)
»  Jan 03, 2024 7:48:23 AM sun.util.locale.provider.LocaleProviderAdapter <clinit>
»  WARNING: COMPAT locale provider will be removed in a future release
»   ↑ repeated 2 times ↑
» [2024-01-03T07:46:32,274][WARN ][o.e.b.BootstrapChecks    ] [v8.12.0-2] HTTPS is required in order to use the token service; please enable HTTPS using the [xpack.security.http.ssl.enabled] setting or disable the token service using the [xpack.security.authc.token.enabled] setting; for more information see [https://www.elastic.co/guide/en/elasticsearch/reference/master/bootstrap-checks-xpack.html#_token_ssl_check]
» [2024-01-03T07:46:32,282][WARN ][o.e.d.FileBasedSeedHostsProvider] [v8.12.0-2] expected, but did not find, a dynamic hosts list at [/dev/shm/bk/bk-agent-prod-gcp-1704267709785516042/elastic/elasticsearch-pull-request/x-pack/qa/rolling-upgrade/build/testclusters/v8.12.0-2/config/unicast_hosts.txt]
» [2024-01-03T07:48:30,093][ERROR][o.e.b.Elasticsearch      ] [v8.12.0-2] fatal exception while booting Elasticsearch java.lang.IllegalStateException: failed to obtain node locks, tried [/dev/shm/bk/bk-agent-prod-gcp-1704267709785516042/elastic/elasticsearch-pull-request/x-pack/qa/rolling-upgrade/build/testclusters/v8.12.0-2/data]; maybe these locations are not writable or multiple nodes were started on the same data path?
»       at org.elasticsearch.server@8.12.0-SNAPSHOT/org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:296)
»       at org.elasticsearch.server@8.12.0-SNAPSHOT/org.elasticsearch.node.NodeConstruction.validateSettings(NodeConstruction.java:484)
»       at org.elasticsearch.server@8.12.0-SNAPSHOT/org.elasticsearch.node.NodeConstruction.prepareConstruction(NodeConstruction.java:246)
»       at org.elasticsearch.server@8.12.0-SNAPSHOT/org.elasticsearch.node.Node.<init>(Node.java:181)
»       at org.elasticsearch.server@8.12.0-SNAPSHOT/org.elasticsearch.bootstrap.Elasticsearch$2.<init>(Elasticsearch.java:236)
»       at org.elasticsearch.server@8.12.0-SNAPSHOT/org.elasticsearch.bootstrap.Elasticsearch.initPhase3(Elasticsearch.java:236)
»       at org.elasticsearch.server@8.12.0-SNAPSHOT/org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:73)
»  Caused by: org.apache.lucene.store.LockObtainFailedException: Lock held by another program: /dev/shm/bk/bk-agent-prod-gcp-1704267709785516042/elastic/elasticsearch-pull-request/x-pack/qa/rolling-upgrade/build/testclusters/v8.12.0-2/data/node.lock
»       at org.apache.lucene.core@9.9.1/org.apache.lucene.store.NativeFSLockFactory.obtainFSLock(NativeFSLockFactory.java:117)
»       at org.apache.lucene.core@9.9.1/org.apache.lucene.store.FSLockFactory.obtainLock(FSLockFactory.java:43)
»       at org.apache.lucene.core@9.9.1/org.apache.lucene.store.BaseDirectory.obtainLock(BaseDirectory.java:44)
»       at org.elasticsearch.server@8.12.0-SNAPSHOT/org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:234)
»       at org.elasticsearch.server@8.12.0-SNAPSHOT/org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:209)
»       at org.elasticsearch.server@8.12.0-SNAPSHOT/org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:288)
»       ... 6 more
»
»  ERROR: Elasticsearch did not exit normally - check the logs at /dev/shm/bk/bk-agent-prod-gcp-1704267709785516042/elastic/elasticsearch-pull-request/x-pack/qa/rolling-upgrade/build/testclusters/v8.12.0-2/logs/v8.12.0.log
»
```

**Comment by mark-vieira** [comment] 2024-01-03 19:34
This looks like a duplicate of https://github.com/elastic/elasticsearch/issues/101231.

**Closed by mark-vieira** 2024-01-03 19:34 UTC
Labels: blocker, :Delivery/Build, >test-failure, Team:Delivery
