### ISSUE TITLE
no_match_size ignored using the fast-vector-highlighter on a field containing an array of strings

### ISSUE THREAD

**Issue by edwardsmit** [elastic/elasticsearch#13734] opened 2015-09-23 09:53 UTC
As demonstrated in the gist, no_match_size setting is ignored and no highlight field is returned when the field on which highlighting is requested has no match _and_ the field contains an array of strings instead of a single string.
https://gist.github.com/edwardsmit/2ec8506db2e4402024dd

**Comment by nik9000** [comment] 2015-09-23 13:08
Confirmed. I don't know when it'll get a fix but it certainly is a bug.

I believe `no_match_size` was supposed to return the first n characters of the first entry in the array if. At least that is how I remember it but its been a long while since I wrote it.

Your gist is wonderful! If all issues had such a thing I'd be very happy.

For next time its: add the `?pretty` option to the requests so they are a little easier to read and/or end them in `;echo`. Without the trailing newline things get messy.

I usually prefer to put the `curl -XDELETE localhost:9200/indexname` as the first line rather than the last. It'll fail the first time unless I have an index with that name in which case it'll clean up the last index.

Thanks for filing this.

**Comment by nik9000** [comment] 2015-09-23 13:12
I added 3.0.0 because I confirmed it on my local checkout which happened to be the master branch. Did you confirm this on 1.7?

**Comment by edwardsmit** [comment] 2015-09-23 13:14
Yes I've verified this on 1.7.2

**Comment by nik9000** [comment] 2015-09-23 13:22
> Yes I've verified this on 1.7.2

So marked. And I also added 2.0.0 and 2.1.0 because I don't imagine its in 1.7 and 3.0 and not in 2.x.

**Comment by clintongormley** [comment] 2016-11-25 15:00
Closing in favour of #21621

**Closed** 2016-11-25 16:02 UTC
Labels: :Highlighting, bug
