### ISSUE TITLE
[CI] GeoIpDownloaderCliIT testInvalidTimestamp failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#94098] opened 2023-02-23 22:41 UTC
All the `ingest-geoip` module internal cluster tests are failing on Windows. This looks to be due to a recent refactoring where because we removed the reliance on docker, these tests can now run on Windows. My hunch is these never would have worked on Windows due to any number of reasons, and so they are just failing now because we're running them on the platform.

**Build scan:**
https://gradle-enterprise.elastic.co/s/c4vwmewipm256/tests/:modules:ingest-geoip:internalClusterTest/org.elasticsearch.ingest.geoip.GeoIpDownloaderCliIT/testInvalidTimestamp

**Reproduction line:**
```
gradlew ':modules:ingest-geoip:internalClusterTest' --tests "org.elasticsearch.ingest.geoip.GeoIpDownloaderCliIT.testInvalidTimestamp" -Dtests.seed=C865186684FA4C7E -Dtests.locale=ga -Dtests.timezone=Africa/Asmara -Druntime.java=19
```

**Applicable branches:**
main, 8.7, 8.6

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.ingest.geoip.GeoIpDownloaderCliIT&tests.test=testInvalidTimestamp

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: not a collection containing "GeoLite2-ASN.mmdb"
     but: was <[GeoLite2-ASN.mmdb_LICENSE.txt, GeoLite2-ASN.mmdb_README.txt, GeoLite2-ASN.mmdb_COPYRIGHT.txt, GeoLite2-Country.mmdb, GeoLite2-ASN.mmdb, GeoLite2-City.mmdb]>

  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.ingest.geoip.GeoIpDownloaderIT.lambda$testInvalidTimestamp$7(GeoIpDownloaderIT.java:181)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1112)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1085)
  at org.elasticsearch.ingest.geoip.GeoIpDownloaderIT.testInvalidTimestamp(GeoIpDownloaderIT.java:177)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1589)

```

**Comment by mark-vieira** [comment] 2023-02-23 22:57
I've decided to mute these for now until we decide whether we want to go through the effort to get these tests running on Windows.

It hadn't really occurred to me though that this highlights that any tests we currently have that rely on docker-based fixtures have zero coverage on Windows.

**Comment by masseyke** [comment] 2023-04-28 18:52
Adding some notes about my debugging failures on this one:
Since I don't have access to a Windows box, I hacked the code so that it always uses`org.apache.lucene.tests.mockfile.WindowsFS` as the filesystem (that one works like windows in that it will blow up if you try to delete a file that is open). I ran it hundreds of times, with no failures. I put some artificial Thread.sleep() calls in before closing the file handles in `DatabaseReaderLazyLoader:getDatabaseType` (the try/finally block that calls databaseInputStream()). No luck. The only way I could reproduce this problem is to change WindowsFS to ignore when a file handle was released. Then I get the exact same error. But I have no idea how that could actually happen.

**Comment by masseyke** [comment] 2023-04-28 19:14
Oh, I also logged out everywhere we accessed `GeoLite2-Country.mmdb`, just in case there was some place with a risk that we weren't closing a file handle. No luck. We only do it from these two places:

- https://github.com/elastic/elasticsearch/blob/v8.7.0/modules/ingest-geoip/src/internalClusterTest/java/org/elasticsearch/ingest/geoip/AbstractGeoIpIT.java#L56
- https://github.com/elastic/elasticsearch/blob/v8.7.0/modules/ingest-geoip/src/main/java/org/elasticsearch/ingest/geoip/DatabaseReaderLazyLoader.java#L94

**Comment by mark-vieira** [comment] 2023-05-01 14:22
It's somewhat worth noting that these tests running on Windows at all is relatively new. This only started a couple of months ago when the geo-ip fixture was refactored to remove the Docker requirement. So I'm not sure how much heartache we want to go through here to get these running, given we've only recently started running them on Windows, before we just mute. Your call.

**Closed** 2024-11-05 21:55 UTC
Labels: >test-failure, :Data Management/Ingest Node, Team:Data Management, medium-risk
