### ISSUE TITLE
[CI] AzureStorageRepositoryClientYamlTestSuiteIT {yaml=repository_azure/10_repository/Snapshot/Restore with repository-azure} failure

### ISSUE THREAD

**Issue by henningandersen** [elastic/elasticsearch#47201] opened 2019-09-27 09:08 UTC
Example failure:

https://gradle-enterprise.elastic.co/s/zb2xff2k72smu/console-log#L41

This started failing frequently yesterday (Sept. 26th):

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-90d,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:AzureStorageRepositoryClientYamlTestSuiteIT),sort:!(time,desc))

The failure seems to come from:

```
1>         "stack_trace" : "Failed to execute phase [query], all shards failed
--
1> 	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:314)
1> 	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:139)
1> 	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:273)
1> 	at org.elasticsearch.action.search.InitialSearchPhase.onShardFailure(InitialSearchPhase.java:105)
1> 	at org.elasticsearch.action.search.InitialSearchPhase.lambda$performPhaseOnShard$1(InitialSearchPhase.java:251)
1> 	at org.elasticsearch.action.search.InitialSearchPhase$1.doRun(InitialSearchPhase.java:172)
1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
1> 	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44)
1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:769)
1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
1> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
1> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
1> 	at java.base/java.lang.Thread.run(Thread.java:834)
```

Did not reproduce locally using:

```
./gradlew ':plugins:repository-azure:qa:microsoft-azure-storage:integTestRunner' --tests "org.elasticsearch.repositories.azure.AzureStorageRepositoryClientYamlTestSuiteIT.test {yaml=repository_azure/10_repository/Snapshot/Restore with repository-azure}" -Dtests.seed=382441B02443BE15 -Dtests.security.manager=true -Dtests.locale=nnh-CM -Dtests.timezone=America/Indiana/Tell_City -Dcompiler.java=12 -Druntime.java=11
```

**Comment by tlrx** [comment] 2019-10-03 13:55
This is a duplicate of #47202 which has been fixed by #47284.

Third party tests and repository integration tests were running against the same bucket/container when those tests were executed against the real Azure/S3/GCS service, leading to various issues.

**Closed by tlrx** 2019-10-03 13:55 UTC
Labels: :Distributed/Snapshot/Restore, >test-failure
