### ISSUE TITLE
Allow more than 1024 dimensions for indexed dense_vector fields

### ISSUE THREAD

**Issue by rishabh279** [elastic/elasticsearch#93130] opened 2023-01-23 08:11 UTC
### Description

 I am using OpenAi's embeddings ie.  text-embedding-ada-002 and they have 1536 dimensions, but dense_vectors of the elasticsearch only support 1024-dim. Ideally, can we please increase the dense vector size to a reasonable dimension like 1536 or any other increased standard dimension like 2048 that would help us to use the state-of-the-art models by OpenAI or any other model which has an embedding size greater than 1024-dim?

If not, can anyone please guide me through the steps to make necessary changes in the codebase since I have recently only started exploring the elastic search for my use-case? This will help me to explore the changes in my current dataset. 

Thanks in advance!

**Comment by benwtrent** [comment] 2023-01-24 17:26
closing as duplicate of: https://github.com/elastic/elasticsearch/issues/92458

**Closed by benwtrent** 2023-01-24 17:26 UTC
Labels: >enhancement, Team:Search, :Search/Vectors

**Comment by abulsalman** [comment] 2024-05-20 13:40
@rishabh279 did you figure it out in the end? I am facing the same problem.
