### ISSUE TITLE
Wrong forced shard allocation setting crashing the cluster 

### ISSUE THREAD

**Issue by dschneiter** [elastic/elasticsearch#72524] opened 2021-04-30 07:45 UTC
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 7.8.1, Build: default/tar/b5ca9c58fb664ca8bf9e4057fc229b3396bf3a89/2020-07-21T16:40:44.668009Z, JVM: 14.0.1 (and others)

**Plugins installed**: []
None

**JVM version** (`java -version`):
JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/14.0.1/14.0.1+7]

**OS version** (`uname -a` if on a Unix-like system):
Linux server1 4.4.0-1117-aws #131-Ubuntu SMP Tue Oct 6 20:45:33 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
A wrong forced shard allocation awareness setting crashes Elasticsearch, dropping nodes from the cluster and making it no longer possible for them to re-join.

A student by mistake used an underscore (following the attribute name) instead of a dot when configuring forced shard allocation awareness (see https://discuss.elastic.co/t/how-to-completely-reset-forced-shard-allocation-awareness/271710). The bogus setting did not get rejected and brought the cluster state in a non-working configuration. Any bogus setting results in the same behavior.

Expected behavior: A bogus / mal-formatted setting should get rejected.

**Steps to reproduce**:
 1. Start up a cluster
 2. Execute 
```
PUT /_cluster/settings
{
  "persistent": {
    "cluster.routing.allocation.awareness.force.nonsense": ""
  }
}
```

**Provide logs (if relevant)**:
Excerpt:
```
[2021-04-30T08:55:47,698][WARN ][o.e.c.s.ClusterSettings  ] [MacBook-Pro.lan] failed to apply settings
org.elasticsearch.common.settings.SettingsException: Failed to get setting group for [] setting prefix and setting [nonsense] because of a missing '.'
	at org.elasticsearch.common.settings.Settings.getGroupsInternal(Settings.java:440) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.settings.Settings.getAsGroups(Settings.java:452) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.cluster.routing.allocation.decider.AwarenessAllocationDecider.setForcedAwarenessAttributes(AwarenessAllocationDecider.java:93) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.settings.Setting$GroupSetting$1.apply(Setting.java:1102) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.settings.Setting$GroupSetting$1.apply(Setting.java:1076) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.settings.AbstractScopedSettings$SettingUpdater.lambda$updater$0(AbstractScopedSettings.java:618) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.settings.AbstractScopedSettings.applySettings(AbstractScopedSettings.java:182) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:455) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:407) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.access$000(ClusterApplierService.java:57) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:151) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:673) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:241) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:204) [elasticsearch-7.12.0.jar:7.12.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
[2021-04-30T08:55:47,704][WARN ][o.e.c.s.ClusterApplierService] [MacBook-Pro.lan] failed to apply updated cluster state in [0s]:
version [37], uuid [WgofdmjvSomtdLRgLT1TpQ], source [Publication{term=1, version=37}]
org.elasticsearch.common.settings.SettingsException: Failed to get setting group for [] setting prefix and setting [nonsense] because of a missing '.'
	at org.elasticsearch.common.settings.Settings.getGroupsInternal(Settings.java:440) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.settings.Settings.getAsGroups(Settings.java:452) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.cluster.routing.allocation.decider.AwarenessAllocationDecider.setForcedAwarenessAttributes(AwarenessAllocationDecider.java:93) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.settings.Setting$GroupSetting$1.apply(Setting.java:1102) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.settings.Setting$GroupSetting$1.apply(Setting.java:1076) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.settings.AbstractScopedSettings$SettingUpdater.lambda$updater$0(AbstractScopedSettings.java:618) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.settings.AbstractScopedSettings.applySettings(AbstractScopedSettings.java:182) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:455) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:407) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.access$000(ClusterApplierService.java:57) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:151) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:673) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:241) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:204) [elasticsearch-7.12.0.jar:7.12.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
[2021-04-30T08:55:47,707][INFO ][o.e.c.s.ClusterApplierService] [MacBook-Pro.lan] master node changed {previous [{MacBook-Pro.lan}{ZToSgRxDTGerkkiW9nguzw}{ncGSE2FXQX2FSSt2ekihoQ}{127.0.0.1}{127.0.0.1:9300}{cdfhilmrstw}{ml.machine_memory=68719476736, xpack.installed=true, transform.node=true, ml.max_open_jobs=20, ml.max_jvm_size=33285996544}], current []}, term: 1, version: 37, reason: becoming candidate: clusterApplier#onNewClusterState
[2021-04-30T08:55:47,711][INFO ][o.e.c.s.ClusterSettings  ] [MacBook-Pro.lan] updating [cluster.routing.allocation.awareness.force.] from [{}] to [{"nonsense":""}]
[2021-04-30T08:55:47,711][WARN ][o.e.c.s.ClusterSettings  ] [MacBook-Pro.lan] failed to apply settings
org.elasticsearch.common.settings.SettingsException: Failed to get setting group for [] setting prefix and setting [nonsense] because of a missing '.'
	at org.elasticsearch.common.settings.Settings.getGroupsInternal(Settings.java:440) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.settings.Settings.getAsGroups(Settings.java:452) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.cluster.routing.allocation.decider.AwarenessAllocationDecider.setForcedAwarenessAttributes(AwarenessAllocationDecider.java:93) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.settings.Setting$GroupSetting$1.apply(Setting.java:1102) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.settings.Setting$GroupSetting$1.apply(Setting.java:1076) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.settings.AbstractScopedSettings$SettingUpdater.lambda$updater$0(AbstractScopedSettings.java:618) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.settings.AbstractScopedSettings.applySettings(AbstractScopedSettings.java:182) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:455) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:407) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.access$000(ClusterApplierService.java:57) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:151) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:673) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:241) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:204) [elasticsearch-7.12.0.jar:7.12.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
[2021-04-30T08:55:47,710][WARN ][o.e.c.s.MasterService    ] [MacBook-Pro.lan] took [0s] and then failed to publish updated cluster state (version: 37, uuid: WgofdmjvSomtdLRgLT1TpQ) for [cluster_update_settings]:
```

**Comment by DaveCTurner** [comment] 2021-04-30 08:00
Thanks for the report @dschneiter; I adjusted it slightly to include the cluster applier logs since that's where the problem lies.

**Comment by rjernst** [comment] 2021-05-01 00:06
By design the force setting takes arbitrary key/values, similar to node attributes. @DaveCTurner Can you elaborate on why you think this is a settings infrastructure issue?

**Comment by DaveCTurner** [comment] 2021-05-01 12:26
Maybe I'm confused by the meaning of a `groupSetting` but my understanding was that calling `getAsGroups` here is legitimate assuming the setting is valid as a group setting. For instance the `monitor.jvm.gc.collector` group setting behaves similarly: setting `monitor.jvm.gc.collector.nonsense: foo` passes validation and then fails when initialising the `JvmGcMonitorService` for much the same reason:

```
[2021-05-01T13:13:16,763][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [MacBook-Pro.lan] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: SettingsException[Failed to get setting group for [] setting prefix and setting [nonsense] because of a missing '.']
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116) ~[elasticsearch-cli-7.12.0.jar:7.12.0]
	at org.elasticsearch.cli.Command.main(Command.java:79) ~[elasticsearch-cli-7.12.0.jar:7.12.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:81) ~[elasticsearch-7.12.0.jar:7.12.0]
Caused by: org.elasticsearch.common.settings.SettingsException: Failed to get setting group for [] setting prefix and setting [nonsense] because of a missing '.'
	at org.elasticsearch.common.settings.Settings.getGroupsInternal(Settings.java:440) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.settings.Settings.getAsGroups(Settings.java:452) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.monitor.jvm.JvmGcMonitorService.<init>(JvmGcMonitorService.java:105) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.monitor.MonitorService.<init>(MonitorService.java:32) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.node.Node.<init>(Node.java:423) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.node.Node.<init>(Node.java:278) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:217) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:217) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:397) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.12.0.jar:7.12.0]
	... 6 more
```

(The consequences aren't so severe here since the setting is static and can be fixed).

My reasoning was that the only two group settings I tested had the same issue, so this seemed to be something infrastructural rather than us using the setting wrongly in the decider. It could just be the same bug in both places.

**Comment by rjernst** [comment] 2021-05-01 21:06
> my understanding was that calling getAsGroups here is legitimate assuming the setting is valid as a group setting

Group settings assume there is a set of arbitrary keys, under which an entire group of settings exist. In this case, instead of the value of the key being a yaml object, it is a direct value. So the settings infrastructure throws an error (though perhaps the error message could be more clear), saying that it expected there to be some subkeys after the user defined key (in your example, the collector name).

So, IMO settings are doing the right thing, throwing an error because the setting is invalid. And we see that in the logs. How that error does not propagate to a failure of the update cluster settings I'm not sure.

In particular:
> The bogus setting did not get rejected and brought the cluster state in a non-working configuration.

Is the setting exception being ignored somewhere and the cluster state still applied?

**Comment by DaveCTurner** [comment] 2021-05-06 11:20
The `SettingsException` is being thrown _during_ cluster state application, which means we already committed this state so it's too late to do anything about it. We should be detecting that it's invalid before we even start to publish the state.

Now that I look at this again I think I was indeed misunderstanding what these group settings are for, and yes I now think the missing validation is in the allocation code rather than in settings-land itself. I'll relabel this, thanks for your help Ryan.

**Closed** 2021-05-10 16:17 UTC
Labels: :Distributed/Allocation, >bug, Team:Distributed
