### ISSUE TITLE
Error while aggregating histogram fields

### ISSUE THREAD

**Issue by romainneutron** [elastic/elasticsearch#80954] opened 2021-11-23 16:28 UTC
**Elasticsearch version:** 7.14.2

**Original install method (e.g. download page, yum, from source, etc.):** ElasticCloud

**Describe the bug:**

Hello,

I encounter an issue with some particular values using histogram aggregations:

Here's a reproducer:

```json
PUT test-index
{
  "mappings" : {
    "properties" : {
      "my_histogram" : {
        "type" : "histogram"
      }
    }
  }
}

PUT test-index/_doc/1
{
  "my_histogram": {
    "counts": [
      2100000000,
      300000000
    ],
    "values": [
      1000,
      2000
    ]
  }
}

GET test-index/_search
{
  "aggs": {
    "wt_96th_percentile": {
      "percentiles": {
        "field": "my_histogram",
        "percents": [
          "96.0"
        ]
      }
    }
  }
}
```
Here's the result I got:

```json
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_state_exception",
        "reason" : "Negative longs unsupported, use writeLong or writeZLong for negative numbers [-1894967296]"
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "test-index",
        "node" : "EJmqZRg-RWy1WYbItsbmHQ",
        "reason" : {
          "type" : "illegal_state_exception",
          "reason" : "Negative longs unsupported, use writeLong or writeZLong for negative numbers [-1894967296]"
        }
      }
    ],
    "caused_by" : {
      "type" : "illegal_state_exception",
      "reason" : "Negative longs unsupported, use writeLong or writeZLong for negative numbers [-1894967296]",
      "caused_by" : {
        "type" : "illegal_state_exception",
        "reason" : "Negative longs unsupported, use writeLong or writeZLong for negative numbers [-1894967296]"
      }
    }
  },
  "status" : 500
}
```

Thanks for your time,
Romain

**Comment by iverase** [comment] 2021-11-24 09:49
duplicate of https://github.com/elastic/elasticsearch/issues/80153, therefore closing it.

**Closed by iverase** 2021-11-24 09:49 UTC
Labels: >bug, :Analytics/Aggregations, Team:Analytics
