### ISSUE TITLE
Inconsistent behavior of index stats API for closed indices vs closed indices with an alias matching the index pattern:  `index_closed_exception`

### ISSUE THREAD

**Issue by bczifra** [elastic/elasticsearch#100661] opened 2023-10-11 08:29 UTC
### Elasticsearch Version

8.8.2

### Java Version

_bundled_

### OS Version

Elastic Cloud

### Problem Description

The index stats API returns an `index_closed_exception` if a closed index is behind an alias matching the wildcard index pattern, but returns without an exception if the closed index matches the wildcard index pattern but is _not_ behind an alias matching the pattern.

### Steps to Reproduce

When calling the [Indices Stats API](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html) against a single, closed index:
```
PUT aliased_index

GET aliased_index/_stats

POST aliased_index/_close

GET */_stats
```
the final call returns an `index_closed_exception`.

If we create a new index, then call `_stats` for those two indices, the API returns without an error:
```
PUT unaliased_index

GET unal*,ali*/_stats
```

However, if we now create an alias for that first index:
```
POST _aliases
{
  "actions": [
    {
      "add": {
        "index": "aliased_index",
        "alias": "my-alias"
      }
    }
  ]
}
```

Then this call:
```
GET my*,unalias*/_stats
```
will return an `index_closed_exception`.

**Comment by bczifra** [comment] 2023-10-11 08:29
Related: https://github.com/elastic/elasticsearch/issues/88752 and https://github.com/elastic/beats/issues/36677

**Comment by DaveCTurner** [comment] 2023-10-11 09:35
I think this is a genuine issue, but I'm closing this as a duplicate of https://github.com/elastic/elasticsearch/issues/32238.

**Closed by DaveCTurner** 2023-10-11 09:35 UTC
Labels: >bug, needs:triage
