### ISSUE TITLE
_mapping output returns boolean property "dynamic" as a string

### ISSUE THREAD

**Issue by stampycode** [elastic/elasticsearch#48802] opened 2019-11-01 11:55 UTC
**Elasticsearch version** 7.1

**Plugins installed**: []

**JVM version** (`java -version`): _unknown_ (using AWS ES service)

**OS version** (`uname -a` if on a Unix-like system): _unknown_ (using AWS ES service)

**Description of the problem including expected versus actual behavior**:

Call `GET` on `/myindex/_mapping` should return:
```
"myindex": {
  "mappings": {
    "properties": {
      "myfield": {
        "type": "object",
        "dynamic": false,
        "enabled": false
}}}}
```

But the "dynamic" field is actually returned as a string type `"false"`:
```
"myindex": {
  "mappings": {
    "properties": {
      "myfield": {
        "type": "object",
        "dynamic": "false",
        "enabled": false
}}}}
```

**Steps to reproduce**:

1. create the index with dynamic:false as a field property
2. GET the _mapping of the index

**Comment by DaveCTurner** [comment] 2019-11-01 16:56
That's the expected behaviour @stampycode: [`dynamic` is not a boolean](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic.html) since it also accepts the value `"strict"`. I suppose we could remove the leniency that lets Elasticsearch accept the `"dynamic": false` syntax and require you to say `"dynamic": "false"` but that'd be quite a major breaking change for quite a minor benefit in consistency. I think there's no action required here so I am closing this.

**Closed by DaveCTurner** 2019-11-01 16:56 UTC
Labels: :Search/Mapping

**Comment by stampycode** [comment] 2019-11-02 13:38
I guess I didn't expect that - if I set the field to boolean false I would expect it to output the value as boolean false, not a string representation. It's not included in the documentation that the returned type would be a string, and there are no examples of the returned values.

I only noticed this because I was doing a deep-compare on the index to detect changes in the mapping from the config it was defined with, and of course boolean false is not equal to string "false" so it flagged the change.

From a design perspective, where is this decided?
If I have an integer setting, which can also accept boolean false, does it convert all int and boolean values to strings?
