### ISSUE TITLE
Executed jar file not working for ElasticSearch

### ISSUE THREAD

**Issue by ahr12** [elastic/elasticsearch#24003] opened 2017-04-10 07:20 UTC
ElasticSearch - 5.3.0
Ubuntu- 14.04
Hello,
I created the maven project for insert the data in ElasticSearch.It's working fine when I executed the code in eclipse.then I create the jar file with dependencies for this project.but when I executed the jar file I am getting the following errors -

Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.elasticsearch.common.logging.DeprecationLogger.<clinit>(DeprecationLogger.java:138)
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.<init>(AbstractXContentParser.java:57)
	at org.elasticsearch.common.xcontent.json.JsonXContentParser.<init>(JsonXContentParser.java:44)
	at org.elasticsearch.common.xcontent.json.JsonXContent.createParser(JsonXContent.java:103)
	at org.elasticsearch.common.settings.Setting.parseableStringToList(Setting.java:832)
	at org.elasticsearch.common.settings.Setting.lambda$listSetting$27(Setting.java:786)
	at org.elasticsearch.common.settings.Setting.listSetting(Setting.java:791)
	at org.elasticsearch.common.settings.Setting.listSetting(Setting.java:786)
	at org.elasticsearch.common.network.NetworkService.<clinit>(NetworkService.java:50)
	at org.elasticsearch.client.transport.TransportClient.newPluginService(TransportClient.java:98)
	at org.elasticsearch.client.transport.TransportClient.buildTemplate(TransportClient.java:126)
	at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:268)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:125)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:111)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:101)
	at org.formcept.Es.Test.main(Test.java:79)
Caused by: java.lang.IllegalStateException: Error finding the build shortHash. Stopping Elasticsearch now so it doesn't run in subtly broken ways. This is likely a build bug.
	at org.elasticsearch.Build.<clinit>(Build.java:62)
	... 16 more

and my pom file look like this - 
 
  <properties>
		<jdk.version>1.8</jdk.version>
		<jodatime.version>2.5</jodatime.version>
		<junit.version>4.11</junit.version>
	</properties>
    <repositories>
      
      <repository>
    <id>ES-snapshots</id>
    <url>https://oss.sonatype.org/content/groups/staging</url>
  </repository> 
      <repository>
    <id>central</id>
    <url>http://repo1.maven.org/maven2/</url>
  </repository>
      <repository>
         <id>elasticsearch-releases</id>
         <url>https://artifacts.elastic.co/maven</url>
         <releases>
            <enabled>true</enabled>
         </releases>
         <snapshots>
            <enabled>false</enabled>
         </snapshots>
      </repository>
   </repositories> 
  <dependencies>
  
   
  
 <dependency>
    <groupId>org.apache.lucene</groupId>
    <artifactId>lucene-grouping</artifactId>
    <version>6.5.0</version>
</dependency>
 
  		<dependency>
    <groupId>com.google.code.gson</groupId>
    <artifactId>gson</artifactId>
    <version>2.8.0</version>
</dependency>
  	 
  		
		<dependency>
			<groupId>org.elasticsearch</groupId>
			<artifactId>elasticsearch</artifactId>
			<version>5.3.0</version>
		</dependency>
		<dependency>
    <groupId>org.elasticsearch.client</groupId>
    <artifactId>transport</artifactId>
    <version>5.3.0</version>
</dependency>
<dependency>
    <groupId>org.apache.logging.log4j</groupId>
    <artifactId>log4j-api</artifactId>
    <version>2.7</version>
</dependency>
<dependency>
    <groupId>org.apache.logging.log4j</groupId>
    <artifactId>log4j-core</artifactId>
    <version>2.7</version>
</dependency>
<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>${junit.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>joda-time</groupId>
			<artifactId>joda-time</artifactId>
			<version>${jodatime.version}</version>
		</dependency>
		</dependencies>
<build>
		<finalName>path</finalName>
		<plugins>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-eclipse-plugin</artifactId>
				<version>2.10</version>
				<configuration>
					<downloadSources>true</downloadSources>
					<downloadJavadocs>false</downloadJavadocs>
				</configuration>
			</plugin>

		
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.6.1</version>
				<configuration>
					<source>${jdk.version}</source>
					<target>${jdk.version}</target>
				</configuration>
			</plugin>

			
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<version>3.0.0</version>
				<configuration>
					
					<descriptorRefs>
						<descriptorRef>jar-with-dependencies</descriptorRef>
					</descriptorRefs>
					
					<archive>
					  <manifest>
						<mainClass>org.formcept.Es</mainClass>
					  </manifest>
					</archive>

				</configuration>
				<executions>
				  <execution>
					<id>make-assembly</id>
                                       
					<phase>package</phase>
					<goals>
						<goal>single</goal>
					</goals>
				  </execution>
				</executions>
			</plugin>

		</plugins>
	</build>

		
</project>

Maybe this is some type of the bug in elastic search because it's working fine for other projects.

**Comment by tvernum** [comment] 2017-04-10 07:29
Hi @ahr12,
Elastic uses GitHub issues for tracking confirmed bugs and feature requests. We aren't able to help diagnose your problem through this site.

Please ask this question on our [discuss forum](https://discuss.elastic.co/) where we can provide better support. 
When you post there, please provide more specific information about the way you are packaging/running your application. Those details will help get to the bottom of the problem.

I'm going to close this issue for now - if the discussion on the forum identifies a specific bug, then we can re-open it then.
Thanks.

**Closed by tvernum** 2017-04-10 07:29 UTC

**Comment by s1monw** [comment] 2017-04-10 07:32
you are trying to build an uber jar but you don't forward the values in our manifest file. If you repackage / build uber jars you have to forward those as well. This hasn't been the case until 5.3.0 but our deprecation logger requires the build hash from what we build the binary in order to run. I am writing this in here since other might run into that as well.

**Comment by Canappeco** [comment] 2017-10-11 12:34
@s1monw I have the same problem. I am sorry but I can understand what you mean. Can you give some more details to solve this problem?

**Comment by Canappeco** [comment] 2017-10-11 12:49
@ahr12 have you solve this problem? I have the same problem with you , can you give me some help?

**Comment by ahr12** [comment] 2017-10-11 16:11
@Canappeco now, I am using the elasticSearch 2.3.0 which haven't any problem with the urban jar.
