### ISSUE TITLE
[CCR] CCRIT.testAutoFollowing is failing

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#37231] opened 2019-01-08 15:41 UTC
The test  `CCRIT.testAutoFollowing` is failing on CI:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1125

With the error:
```
14:48:58   1> [2019-01-08T17:48:57,831][INFO ][o.e.u.CCRIT              ] [testAutoFollowing] There are still tasks running after this test that might break subsequent tests [cluster:monitor/state, indices:data/read/xpack/ccr/shard_changes, indices:data/read/xpack/ccr/shard_changes[s], xpack/ccr/shard_follow_task[c]].
14:48:58   1> [2019-01-08T17:48:57,832][INFO ][o.e.u.CCRIT              ] [testAutoFollowing] after test
14:48:58 FAILURE 10.2s | CCRIT.testAutoFollowing <<< FAILURES!
14:48:58    > Throwable #1: java.lang.AssertionError: 
14:48:58    > Expected: <1>
14:48:58    >      but: was <0>
14:48:58    > 	at __randomizedtesting.SeedInfo.seed([C7C9CBCAF12212B6:6827EDCAF58BB99B]:0)
14:48:58    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
14:48:58    > 	at org.elasticsearch.upgrades.CCRIT.assertFollowerGlobalCheckpoint(CCRIT.java:273)
14:48:58    > 	at org.elasticsearch.upgrades.CCRIT.lambda$testAutoFollowing$5(CCRIT.java:123)
14:48:58   2> NOTE: leaving temporary files on disk at: /var/lib/jenkins/workspace/elastic+elasticsearch+master+intake/x-pack/qa/rolling-upgrade/without-system-key/build/testrun/v6.7.0#oneThirdUpgradedTestRunner/J0/temp/org.elasticsearch.upgrades.CCRIT_C7C9CBCAF12212B6-001
14:48:58    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:847)
14:48:58    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:821)
14:48:58   2> NOTE: test params are: codec=Asserting(Lucene80): {}, docValues:{}, maxPointsInLeafNode=1566, maxMBSortInHeap=7.812807438368832, sim=Asserting(org.apache.lucene.search.similarities.AssertingSimilarity@33ae1d18), locale=es-DO, timezone=Europe/Volgograd
14:48:58    > 	at org.elasticsearch.upgrades.CCRIT.testAutoFollowing(CCRIT.java:121)
14:48:58    > 	at java.lang.Thread.run(Thread.java:748)
14:48:58    > 	Suppressed: java.lang.AssertionError: 
14:48:58   2> NOTE: Linux 4.9.0-8-amd64 amd64/Oracle Corporation 1.8.0_192 (64-bit)/cpus=16,threads=1,free=427840024,total=514850816
14:48:58    > Expected: <1>
14:48:58    >      but: was <0>
14:48:58    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
14:48:58    > 		at org.elasticsearch.upgrades.CCRIT.assertFollowerGlobalCheckpoint(CCRIT.java:273)
14:48:58   2> NOTE: All tests run in this JVM: [IndexAuditUpgradeIT, UpgradeClusterClientYamlTestSuiteIT, RollupIDUpgradeIT, IndexingIT, TokenBackwardsCompatibilityIT, CCRIT]
14:48:58    > 		at org.elasticsearch.upgrades.CCRIT.lambda$testAutoFollowing$5(CCRIT.java:123)
14:48:58    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
14:48:58    > 		... 39 more
```

It does not reproduce locally for me with:
```
./gradlew :x-pack:qa:rolling-upgrade:without-system-key:v6.7.0#oneThirdUpgradedTestRunner -Dtests.seed=C7C9CBCAF12212B6 -Dtests.class=org.elasticsearch.upgrades.CCRIT -Dtests.method="testAutoFollowing" -Dtests.security.manager=true -Dtests.locale=es-DO -Dtests.timezone=Europe/Volgograd -Dcompiler.java=11 -Druntime.java=8
```

The failure looks different from #35937 hence the new issue.

**Comment by tlrx** [comment] 2019-01-08 15:47
Another instance: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1127

Full execution log [consoleTest.tar.gz](https://github.com/elastic/elasticsearch/files/2737453/consoleTest.tar.gz)

**Comment by martijnvg** [comment] 2019-01-08 15:55
I've muted the two tests in `CCRIT` test class. The seem to fail for the same reason.

**Comment by martijnvg** [comment] 2019-01-10 15:49
I merged #37239, which fixes the underlying issue why this rolling upgrade test failed.
I will unmute this test soon, when I've verified that this test doesn't fail locally. (I was able to reproduce locally).

**Comment by dnhatn** [comment] 2019-01-31 21:57
This test is failing again. I am re-opening the issue.

Some instances:
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1716/console
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1714/console

**Comment by martijnvg** [comment] 2019-02-01 09:16
This failure is expected. In a 3 node cluster, all on version 6.7.0-SNAPSHOT, one node gets upgraded to 7.0.0-SNAPSHOT. In this state a leader index gets created on the upgraded node. The auto follow coordinator auto-follows this index, and the restore is performed on a not upgraded node. The restore fails because a 6.7.0-SNAPSHOT node can't read the index files from a 7.0.0-SNAPSHOT node:

```
[2019-02-01T09:59:32,426][WARN ][o.e.s.RestoreService     ] [node-1] [_ccr_local:_latest_] failed to restore snapshot
org.elasticsearch.snapshots.SnapshotRestoreException: [_ccr_local:_latest_/_latest_] the snapshot was created with Elasticsearch version [7.0.0] which is higher than the version of this node [6.7.0]
        at org.elasticsearch.snapshots.RestoreService.validateSnapshotRestorable(RestoreService.java:855) ~[elasticsearch-6.7.0-SNAPSHOT.jar:6.7.0-SNAPSHOT]
        at org.elasticsearch.snapshots.RestoreService.restoreSnapshot(RestoreService.java:197) [elasticsearch-6.7.0-SNAPSHOT.jar:6.7.0-SNAPSHOT]
        at org.elasticsearch.xpack.ccr.action.TransportPutFollowAction$1.doRun(TransportPutFollowAction.java:174) [x-pack-ccr-6.7.0-SNAPSHOT.jar:6.7.0-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:751) [elasticsearch-6.7.0-SNAPSHOT.jar:6.7.0-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.7.0-SNAPSHOT.jar:6.7.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

This test is testing a rolling upgrade in a local cluster (which is another form of bi-directional index following, see #38037) and currently we can't support that. The reason that it didn't fail before is because the new follower index would do an ops based recovery and recently we switched to a file based recovery as initial recovery.

I'm working an adding a qa module that does a rolling upgrading in two clusters that is setup to do unidirectional index following. In this case a rolling upgrade while new leader indices are auto followed should work without a problem. When that is ready we can then move this test, to this new qa module.

**Closed** 2019-02-15 09:24 UTC
Labels: :Distributed/CCR, >test-failure, v8.0.0
