### ISSUE TITLE
Please REOPEN 85047

### ISSUE THREAD

**Issue by tedivm** [elastic/elasticsearch#102312] opened 2023-11-16 16:52 UTC
### Elasticsearch Version

8

### Installed Plugins

None

### Java Version

_bundled_

### OS Version

Whatever is in the docker container

### Problem Description

The error from issue #85047 is not resolved. After the issue was closed people still kept responding pointing out the error still occurs. The most recent response was three days ago.

The docker elasticsearch container is broken and does not set passwords.

### Steps to Reproduce

```yaml
version: "3.7"

services:
  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: elastic
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      discovery.type: "single-node"
      network.host: "_site_, _local_"
      ELASTIC_PASSWORD: "TestingPassword123@"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300

```

Run this and you'll get 

> elastic                       | {"@timestamp":"2023-11-16T16:46:55.210Z", "log.level": "INFO", "message":"Auto-configuration will not generate a password for the elastic built-in superuser, as we cannot  determine if there is a terminal attached to the elasticsearch process. You can use the `bin/elasticsearch-reset-password` tool to set the password for the elastic user.", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.xpack.security.InitialNodeSecurityAutoConfiguration","elasticsearch.node.name":"f642103df533","elasticsearch.cluster.name":"docker-cluster"}

**Comment by andreidan** [comment] 2023-11-20 14:50
Thanks for using elasticsearch @tedivm 

I'll go ahead and close this issue as duplicate of https://github.com/elastic/elasticsearch/issues/85047 but please leave the feedback on https://github.com/elastic/elasticsearch/issues/85047.

**Closed by andreidan** 2023-11-20 14:50 UTC
Labels: >bug, needs:triage
