### ISSUE TITLE
:qa:mixed-cluster:v8.8.3#mixedClusterTest failure

### ISSUE THREAD

**Issue by edsavage** [elastic/elasticsearch#97502] opened 2023-07-10 11:07 UTC
### CI Link

https://gradle-enterprise.elastic.co/s/q3wnn56o7bysc/console-log?task=:qa:mixed-cluster:v8.8.3%23mixedClusterTest

### Repro line

/gradlew ':qa:mixed-cluster:v8.8.3#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=search/140_pre_filter_search_shards/pre_filter_shard_size with shards that have no hit}" -Dtests.seed=E160367AC2A68185 -Dtests.bwc=true -Dtests.locale=mk-MK -Dtests.timezone=America/Grenada -Druntime.java=17 -Dtests.fips.enabled=true	

### Does it reproduce?

No

### Applicable branches

main

### Failure excerpt

org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT > test {p0=search/140_pre_filter_search_shards/pre_filter_shard_size with shards that have no hit} FAILED |  
-- | --
  | java.lang.AssertionError: Failure at [search/140_pre_filter_search_shards:164]: |  
  | Expected: <1> |  
  | but: was <0>

**Comment by davidkyle** [comment] 2023-07-17 13:53
Another failure on 8.8 where mute wasn't backported to

https://gradle-enterprise.elastic.co/s/ursmx63nuzh3m

**Comment by benwtrent** [comment] 2023-08-03 12:09
duplicate of: https://github.com/elastic/elasticsearch/issues/92058

**Comment by benwtrent** [comment] 2023-10-12 13:37
closing as duplicate: https://github.com/elastic/elasticsearch/issues/92058

**Closed by benwtrent** 2023-10-12 13:37 UTC
Labels: :Search/Search, >test-failure, Team:Search
