### ISSUE TITLE
XPackRestIT p0=vectors/35_sparse_vector_l1l2 failures

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#51603] opened 2020-01-29 11:33 UTC
This failed intake on 7.6 today : https://gradle-enterprise.elastic.co/s/p6h4e2nuvyjk2
```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:integTestRunner' --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=vectors/35_sparse_vector_l1l2/L1 norm}" -Dtests.seed=76B805D13EA61B16 -Dtests.security.manager=true -Dtests.locale=lv -Dtests.timezone=Asia/Baghdad -Dcompiler.java=13 -Druntime.java=8 -Dtests.rest.blacklist=getting_started/10_monitor_cluster_health/*
```

Has been failing on and off since early December: https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(project,message,branch),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'35_sparse_vector_l1l2'),sort:!(time,desc))

**Comment by cbuescher** [comment] 2020-01-29 15:52
Maybe related to https://github.com/elastic/elasticsearch/issues/50716, maybe @mayya-sharipova knows if it makes sense to track individually or if the two are related and this can be closed.

**Comment by jtibshirani** [comment] 2020-01-29 18:26
I think we can close this as a duplicate of #50716. I added these tests originally and am currently looking into a fix.

**Closed by jtibshirani** 2020-01-29 18:26 UTC
Labels: :Search/Search, >test-failure
