### ISSUE TITLE
[CI] ClusterDisruptionIT.testAckedIndexing fails

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#25286] opened 2017-06-19 09:02 UTC
At first this looked similar to #24932 but the error looks different:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=debian/1135/console

```
FAILURE 48.1s J1 | ClusterDisruptionIT.testAckedIndexing <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: timed out waiting for green state
   > 	at __randomizedtesting.SeedInfo.seed([B177E37DC19D7063:3BB6578E9DE09628]:0)
   > 	at org.elasticsearch.test.ESIntegTestCase.ensureColor(ESIntegTestCase.java:944)
   > 	at org.elasticsearch.test.ESIntegTestCase.ensureGreen(ESIntegTestCase.java:910)
   > 	at org.elasticsearch.test.ESIntegTestCase.ensureGreen(ESIntegTestCase.java:899)
   > 	at org.elasticsearch.discovery.ClusterDisruptionIT.testAckedIndexing(ClusterDisruptionIT.java:201)
   > 	at java.lang.Thread.run(Thread.java:748)
```
I wasn't able to reproduce this locally so far. Reproduce line:
```
REPRODUCE WITH: gradle :core:integTest -Dtests.seed=B177E37DC19D7063 -Dtests.class=org.elasticsearch.discovery.ClusterDisruptionIT -Dtests.method="testAckedIndexing" -Dtests.security.manager=true -Dtests.locale=es-SV -Dtests.timezone=America/Puerto_Rico
```

**Comment by cbuescher** [comment] 2017-06-19 10:10
@ywelsch could you take a look at this and reassign to the appropriate person if this is not your area?

**Comment by tlrx** [comment] 2017-06-21 15:22
It failed again today:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=sles/1142/console

See the log 
[consoleText.txt](https://github.com/elastic/elasticsearch/files/1091983/consoleText.txt)

Note that this issue is a duplicate of #24932 already assigned to Jason. @ywelsch I let you manage with him who it going to look at this :)

**Comment by ywelsch** [comment] 2017-06-21 15:28
This test fails for many reasons (the failure that Christophe showed, I cannot explain yet). @tlrx the build failure you posted is a duplicate of https://github.com/elastic/elasticsearch/issues/21658.
The failure that is assigned to Jason is still different. Let's leave all these issues open for now so that they can be addressed separately.

**Comment by tlrx** [comment] 2017-06-21 15:31
Rah sorry - so many failures today. Thanks for the rectification.

**Comment by bleskes** [comment] 2017-06-21 16:06
the last failure didn't include https://github.com/elastic/elasticsearch/pull/25320 . I think it's useless to chase these without that fix.

**Comment by martijnvg** [comment] 2017-07-18 07:23
Encountered another ack indexing failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/3580/consoleFull

Actual failure:

```
ClusterDisruptionIT.testAckedIndexing <<< FAILURES!
   > Throwable #1: com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=7061, name=elasticsearch[node_t2][bulk][T#1], state=RUNNABLE, group=TGRP-ClusterDisruptionIT]
   > 	at __randomizedtesting.SeedInfo.seed([BD856C14EBA7C8B2:3744D8E7B7DA2EF9]:0)
   > Caused by: java.lang.AssertionError
   > 	at __randomizedtesting.SeedInfo.seed([BD856C14EBA7C8B2]:0)
   > 	at org.elasticsearch.index.seqno.GlobalCheckpointTracker.getReplicationGroup(GlobalCheckpointTracker.java:271)
   > 	at org.elasticsearch.index.seqno.SequenceNumbersService.getReplicationGroup(SequenceNumbersService.java:180)
   > 	at org.elasticsearch.index.shard.IndexShard.getReplicationGroup(IndexShard.java:1736)
   > 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.getReplicationGroup(TransportReplicationAction.java:1012)
   > 	at org.elasticsearch.action.support.replication.ReplicationOperation.checkActiveShardCount(ReplicationOperation.java:235)
   > 	at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:96)
   > 	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:338)
   > 	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:282)
   > 	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:927)
   > 	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:924)
   > 	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:235)
   > 	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:2091)
   > 	at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryShardReference(TransportReplicationAction.java:936)
   > 	at org.elasticsearch.action.support.replication.TransportReplicationAction.access$400(TransportReplicationAction.java:94)
   > 	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:299)
   > 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
   > 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:278)
   > 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:265)
   > 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66)
   > 	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:650)
   > 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638)
   > 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
   > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
   > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
   > 	at java.lang.Thread.run(Thread.java:748)
```

I don't think this failure is related to the failures already mentioned here and in the other issue open for this test. I'm unsure if another issue needs to be opened, otherwise we have 3 open issues for this test.

**Comment by jasontedor** [comment] 2017-07-18 07:52
@martijnvg Different failures should be different issues, especially for a test like the ACKed indxing test.

**Comment by martijnvg** [comment] 2017-07-18 08:11
@jasontedor Ok, I opened: #25765

**Comment by martijnvg** [comment] 2017-07-18 15:36
This time, this failure looks similar as here: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.5+multijob-unix-compatibility/os=oraclelinux/103/consoleFull

```
DiscoveryWithServiceDisruptionsIT.testAckedIndexing <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: timed out waiting for green state
   > 	at __randomizedtesting.SeedInfo.seed([E89016AE4071CABA:6251A25D1C0C2CF1]:0)
   > 	at org.elasticsearch.test.ESIntegTestCase.ensureColor(ESIntegTestCase.java:932)
   > 	at org.elasticsearch.test.ESIntegTestCase.ensureGreen(ESIntegTestCase.java:898)
   > 	at org.elasticsearch.test.ESIntegTestCase.ensureGreen(ESIntegTestCase.java:887)
   > 	at org.elasticsearch.discovery.DiscoveryWithServiceDisruptionsIT.testAckedIndexing(DiscoveryWithServiceDisruptionsIT.java:591)
   > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by bleskes** [comment] 2018-03-27 15:41
This is 9 months old now - I'm not sure it makes sense to keep this open/chase it around - many things are different. I'm closing - if someone feels differently by all means please reopen.

**Closed by bleskes** 2018-03-27 15:41 UTC
Labels: :Distributed/ZenDiscovery, >test, jenkins, v6.0.3
