### ISSUE TITLE
Gradle task :distribution:docker:buildCloudDockerImage fails regularly on apt-get/curl

### ISSUE THREAD

**Issue by craigtaverner** [elastic/elasticsearch#96371] opened 2023-05-26 09:57 UTC
Repeated build failures in CI, for example:

* https://gradle-enterprise.elastic.co/s/5s2q4et5qvsam

The final error is:

```
A failure occurred while executing org.elasticsearch.gradle.internal.docker.DockerBuildTask$DockerBuildAction
> Process 'command 'docker'' finished with non-zero exit value 1
```

But this is likely due to an earlier error within the scripts in the docker build:

```
  | \| ------ |  
  | \| Dockerfile:16 |  
  | \| -------------------- |  
  | \|   15 \| |  
  | \|   16 \| >>> RUN for iter in 1 2 3 4 5 6 7 8 9 10; do \ |  
  | \|   17 \| >>>       apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y curl  && \ |  
  | \|   18 \| >>>       exit_code=0 && break \|\| \ |  
  | \|   19 \| >>>         exit_code=$? && echo "apt-get error: retry $iter in 10s" && sleep 10; \ |  
  | \|   20 \| >>>     done; \ |  
  | \|   21 \| >>>     exit $exit_code |  
  | \|   22 \| |  
  | \| -------------------- |  
  | \| ERROR: failed to solve: process "/bin/sh -c for iter in 1 2 3 4 5 6 7 8 9 10; do       apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y curl  &&       exit_code=0 && break \|\|         exit_code=$? && echo \"apt-get error: retry $iter in 10s\" && sleep 10;     done;     exit $exit_code"
      did not complete successfully: exit code: 4294967295 | 
```

This seems similar to, or a replacement for an older issue at https://github.com/elastic/elasticsearch/issues/81150, and hence I've used the same labels as in that issue.

**Comment by craigtaverner** [comment] 2023-05-26 09:59
Similar failure in https://gradle-enterprise.elastic.co/s/52zjcnzdb7jzg

```
\| Dockerfile:79 |  
  | \| -------------------- |  
  | \|   78 \|     # Change default shell to bash, then install required packages with retries. |  
  | \|   79 \| >>> RUN yes no \| dpkg-reconfigure dash && \ |  
  | \|   80 \| >>>     export DEBIAN_FRONTEND=noninteractive && \ |  
  | \|   81 \| >>>       apt-get update && \ |  
  | \|   82 \| >>>       apt-get upgrade -y && \ |  
  | \|   83 \| >>>       apt-get install -y --no-install-recommends \ |  
  | \|   84 \| >>>         ca-certificates curl netcat p11-kit unzip zip  && \ |  
  | \|   85 \| >>>       apt-get clean && \ |  
  | \|   86 \| >>>       rm -rf /var/lib/apt/lists/* |  
  | \|   87 \| |  
  | \| -------------------- |  
  | \| ERROR: failed to solve: process "/bin/sh -c yes no \| dpkg-reconfigure dash &&     export DEBIAN_FRONTEND=noninteractive &&       apt-get update &&       apt-get upgrade -y &&       apt-get install -y --no-install-recommends         ca-certificates curl netcat p11-kit unzip zip  &&       apt-get clean &&       rm -rf /var/lib/apt/lists/*"
    did not complete successfully: exit code: 4294967295 |  
```

**Comment by mark-vieira** [comment] 2023-05-26 17:05
Closing as a duplicate of https://github.com/elastic/elasticsearch/issues/96207

**Closed by mark-vieira** 2023-05-26 17:05 UTC
Labels: >bug, Team:Delivery, :Delivery/Cloud
