### ISSUE TITLE
Gradle requires JAVA_HOME to be set

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#14614] opened 2015-11-09 08:48 UTC
I get the following error when running the build:

```
* What went wrong:
A problem occurred configuring project ':distribution:tar'.
> Ambiguous method overloading for method java.io.File#<init>.
  Cannot resolve which method to invoke for [null, class java.lang.String] due to overlapping prototypes between:
  	[class java.lang.String, class java.lang.String]
  	[class java.io.File, class java.lang.String]
```

which is due to the following problem:

```
Caused by: groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method java.io.File#<init>.
Cannot resolve which method to invoke for [null, class java.lang.String] due to overlapping prototypes between:
	[class java.lang.String, class java.lang.String]
	[class java.io.File, class java.lang.String]
	at org.elasticsearch.gradle.test.ClusterFormationTasks$_configureCheckPreviousTask_closure16.doCall(ClusterFormationTasks.groovy:282)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:110)
	at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:488)
	at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:93)
	at org.gradle.api.tasks.TaskContainer$create$3.call(Unknown Source)
	at org.elasticsearch.gradle.test.ClusterFormationTasks.configureCheckPreviousTask(ClusterFormationTasks.groovy:278)
	at org.elasticsearch.gradle.test.ClusterFormationTasks.configureTasks(ClusterFormationTasks.groovy:94)
	at org.elasticsearch.gradle.test.ClusterFormationTasks$configureTasks$1.callStatic(Unknown Source)
	at org.elasticsearch.gradle.test.ClusterFormationTasks.setup(ClusterFormationTasks.groovy:49)
	at org.elasticsearch.gradle.test.ClusterFormationTasks$setup.call(Unknown Source)
	at org.elasticsearch.gradle.test.RestIntegTestTask$_closure1.doCall(RestIntegTestTask.groovy:74)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy12.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
	... 41 more
```

And indeed at ClusterFormationTasks.groovy:282 we have the following

```groovy
            commandLine new File(System.getenv('JAVA_HOME'), 'bin/jps'), '-l'
```

So if JAVA_HOME is not set then Groovy won't know whether to use the File(File, String) or the File(String, String) constructor. Could we just expect jps to be on the PATH or at least detect JAVA_HOME automatically when it is not set?

**Comment by nik9000** [comment] 2015-11-09 13:03
I fixed this once before. I can do this again!

**Comment by jpountz** [comment] 2015-11-09 13:07
That would be great. Thanks @nik9000 !

**Comment by rjernst** [comment] 2015-11-09 15:43
I have a fix for this in a branch, the problem is intellij. I had this check a long time ago, but removed because it caused problems for intellij users (but not for me because I have java home set for intellij). My current fix simply ignores the check when intellij runs gradle, but I'm apprehensive about that. Maybe others have an opinion?

**Comment by nik9000** [comment] 2015-11-09 15:48
> Maybe others have an opinion?

Can you make IntelliJ blow up loudly and _tell_ the user how to set JAVA_HOME?

**Comment by rjernst** [comment] 2015-11-09 15:53
Yes and no. Certainly the error can be customized for intellij. But setting is complicated and I'm not even sure myself the exact steps to go through (I did it many months ago for another reason).

**Closed** 2015-11-09 18:25 UTC
Labels: build
