### ISSUE TITLE
Highlighting does not work seemingly, why?

### ISSUE THREAD

**Issue by gamelife1314** [elastic/elasticsearch#40351] opened 2019-03-22 09:21 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 6.4.1

**Plugins installed**: [elasticsearch-analysis-ik]

**JVM version** (`java -version`): 

**OS version** (`uname -a` if on a Unix-like system):

Here is the DSL I used to search:

```json
{
	"_source": {
		"excludes": ["content"]
	},
    "query": {
        "bool": {
            "should": [
                {
                    "multi_match": {
                        "fields": ["title^10", "content"],
                        "query": "能量无忧包退订",
                        "type": "phrase",
                        "boost": 10,
                        "analyzer": "ik_smart"
                    }
                },
                {
                    "multi_match": {
                        "fields": ["title", "content"],
                        "query": "能量无忧包退订",
                        "type": "cross_fields",
                        "analyzer": "ik_smart"
                    }
                }
            ],
            "minimum_should_match": 1
        }
    },
    "highlight": {
        "pre_tags": ["<strong class='box_search_highlight'>"],
        "post_tags": ["</strong>"],
        "fields": {
            "content": {
                "no_match_size": 60,
                "fragment_size": 60,
                "number_of_fragments": 3,
                "fragmenter": "span"
            },
            "title": {
                "no_match_size": 60,
                "fragment_size": 60,
                "number_of_fragments": 3,
                "force_source": true,
                "fragmenter": "span"
            }
        }
    }
}
```

And here are the results：

```json
{
    "took": 4,
    "timed_out": false,
    "_shards": {
        "total": 3,
        "successful": 3,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": 360,
        "max_score": 30.710907,
        "hits": [
            {
                "_index": "box_storage_10011",
                "_type": "10011",
                "_id": "296978",
                "_score": 30.710907,
                "_source": {
                    "start_time": "1970-01-01",
                    "is_dir": "false",
                    "end_time": "2070-01-01",
                    "title": "能量无忧包服务购买及退订",
                    "tags": [
                        "id:8301f7a4-cae7-4442-959c-b61544d85205",
                        "nodeid:3664a23f-7c3e-4086-961b-62c8a99df11d",
                        "type:1",
                        "status:2",
                        "role:all"
                    ]
                },
                "highlight": {
                    "title": [
                        "能量无忧包服务购买及退订"
                    ],
                    "content": [
                        "（如遇到能量无忧包无法购买，确认一下用户昵称是否有特殊字符或者英文字母，建议修改之后即可重新购买。）"
                    ]
                }
            }
            ......
        ]
    }
}
```

Why does the highlight not work?

**Comment by cbuescher** [comment] 2021-06-16 14:27
@gamelife1314 sorry for not getting back on this issue yet. After reading through your description it seems to me we are missing some crucial information here, like for example how the fields in question (here "content", "title") are mapped and what your expectation are for the highlighting. Having said that, I have a feeling this is more of a usage question and not a bug per se, so I'd like to close this issue and redirect you to our support forums over at https://discuss.elastic.co if you still need an answer to this question.

**Closed by cbuescher** 2021-06-16 14:27 UTC
Labels: :Search/Highlighting, Team:Search
