### ISSUE TITLE
RefreshListenerTests.testLotsOfThreads sporadically failes

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#24418] opened 2017-05-01 13:33 UTC
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+nfs/220

```
2> java.lang.AssertionError: listener never called
  2> 	at __randomizedtesting.SeedInfo.seed([2F3BA4832C2AEE7]:0)
  2> 	at org.junit.Assert.fail(Assert.java:88)
  2> 	at org.junit.Assert.assertTrue(Assert.java:41)
  2> 	at org.junit.Assert.assertNotNull(Assert.java:621)
  2> 	at org.elasticsearch.index.shard.RefreshListenersTests.lambda$null$6(RefreshListenersTests.java:295)
  2> 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:716)
  2> 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:690)
  2> 	at org.elasticsearch.index.shard.RefreshListenersTests.lambda$testLotsOfThreads$7(RefreshListenersTests.java:295)
  2> 	at java.lang.Thread.run(Thread.java:745)
  2> 	Suppressed: java.lang.AssertionError: listener never called
  2> 		at org.junit.Assert.fail(Assert.java:88)
  2> 		at org.junit.Assert.assertTrue(Assert.java:41)
  2> 		at org.junit.Assert.assertNotNull(Assert.java:621)
  2> 		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$null$6(RefreshListenersTests.java:295)
  2> 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:704)
  2> 		... 3 more
  2> 	Suppressed: java.lang.AssertionError: listener never called
  2> 		at org.junit.Assert.fail(Assert.java:88)
  2> 		at org.junit.Assert.assertTrue(Assert.java:41)
  2> 		at org.junit.Assert.assertNotNull(Assert.java:621)
  2> 		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$null$6(RefreshListenersTests.java:295)
  2> 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:704)
  2> 		... 3 more
  2> 	Suppressed: java.lang.AssertionError: listener never called
  2> 		at org.junit.Assert.fail(Assert.java:88)
  2> 		at org.junit.Assert.assertTrue(Assert.java:41)
  2> 		at org.junit.Assert.assertNotNull(Assert.java:621)
  2> 		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$null$6(RefreshListenersTests.java:295)
  2> 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:704)
  2> 		... 3 more
  2> 	Suppressed: java.lang.AssertionError: listener never called
  2> 		at org.junit.Assert.fail(Assert.java:88)
  2> 		at org.junit.Assert.assertTrue(Assert.java:41)
  2> 		at org.junit.Assert.assertNotNull(Assert.java:621)
  2> 		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$null$6(RefreshListenersTests.java:295)
  2> 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:704)
  2> 		... 3 more
  2> 	Suppressed: java.lang.AssertionError: listener never called
  2> 		at org.junit.Assert.fail(Assert.java:88)
  2> 		at org.junit.Assert.assertTrue(Assert.java:41)
  2> 		at org.junit.Assert.assertNotNull(Assert.java:621)
  2> 		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$null$6(RefreshListenersTests.java:295)
  2> 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:704)
  2> 		... 3 more
  2> 	Suppressed: java.lang.AssertionError: listener never called
  2> 		at org.junit.Assert.fail(Assert.java:88)
  2> 		at org.junit.Assert.assertTrue(Assert.java:41)
  2> 		at org.junit.Assert.assertNotNull(Assert.java:621)
  2> 		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$null$6(RefreshListenersTests.java:295)
  2> 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:704)
  2> 		... 3 more
  2> 	Suppressed: java.lang.AssertionError: listener never called
  2> 		at org.junit.Assert.fail(Assert.java:88)
  2> 		at org.junit.Assert.assertTrue(Assert.java:41)
  2> 		at org.junit.Assert.assertNotNull(Assert.java:621)
  2> 		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$null$6(RefreshListenersTests.java:295)
  2> 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:704)
  2> 		... 3 more
  2> 	Suppressed: java.lang.AssertionError: listener never called
  2> 		at org.junit.Assert.fail(Assert.java:88)
  2> 		at org.junit.Assert.assertTrue(Assert.java:41)
  2> 		at org.junit.Assert.assertNotNull(Assert.java:621)
  2> 		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$null$6(RefreshListenersTests.java:295)
  2> 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:704)
  2> 		... 3 more
  2> 	Suppressed: java.lang.AssertionError: listener never called
  2> 		at org.junit.Assert.fail(Assert.java:88)
  2> 		at org.junit.Assert.assertTrue(Assert.java:41)
  2> 		at org.junit.Assert.assertNotNull(Assert.java:621)
  2> 		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$null$6(RefreshListenersTests.java:295)
  2> 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:704)
  2> 		... 3 more
  2> 	Suppressed: java.lang.AssertionError: listener never called
  2> 		at org.junit.Assert.fail(Assert.java:88)
  2> 		at org.junit.Assert.assertTrue(Assert.java:41)
  2> 		at org.junit.Assert.assertNotNull(Assert.java:621)
  2> 		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$null$6(RefreshListenersTests.java:295)
  2> 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:704)
  2> 		... 3 more
  2> 	Suppressed: java.lang.AssertionError: listener never called
  2> 		at org.junit.Assert.fail(Assert.java:88)
  2> 		at org.junit.Assert.assertTrue(Assert.java:41)
  2> 		at org.junit.Assert.assertNotNull(Assert.java:621)
  2> 		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$null$6(RefreshListenersTests.java:295)
  2> 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:704)
  2> 		... 3 more
  2> 	Suppressed: java.lang.AssertionError: listener never called
  2> 		at org.junit.Assert.fail(Assert.java:88)
  2> 		at org.junit.Assert.assertTrue(Assert.java:41)
  2> 		at org.junit.Assert.assertNotNull(Assert.java:621)
  2> 		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$null$6(RefreshListenersTests.java:295)
  2> 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:704)
  2> 		... 3 more
  2> 	Suppressed: java.lang.AssertionError: listener never called
  2> 		at org.junit.Assert.fail(Assert.java:88)
  2> 		at org.junit.Assert.assertTrue(Assert.java:41)
  2> 		at org.junit.Assert.assertNotNull(Assert.java:621)
  2> 		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$null$6(RefreshListenersTests.java:295)
  2> 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:704)
  2> 		... 3 more
```

**Comment by javanna** [comment] 2017-05-01 13:34
@nik9000 sorry to be assigning this one too to you, feel free to reassign.

**Comment by nik9000** [comment] 2017-05-01 19:14
I pushed more logging for the test because the failure didn't really help me to debug it.

**Comment by ideadapt** [comment] 2017-12-26 17:43
@nik9000 I could not find any failed build since your commit, that features this test failure. Hence I don't have any trace logs of that test. Do you maybe have some more information / logs, maybe from a local test run?

**Comment by nik9000** [comment] 2018-01-26 15:49
> @nik9000 I could not find any failed build since your commit, that features this test failure. Hence I don't have any trace logs of that test. Do you maybe have some more information / logs, maybe from a local test run?

Sorry for getting back to you so late, no, I never managed to get more information on the failures. I'll dig around my email later today looking for any test failures like this.

**Comment by nik9000** [comment] 2018-01-26 16:36
I can confirm that this hasn't failed since I added the logging. I'm going to drop the logging and close. If it fails again we'll reopen it with a new data point.

**Comment by nik9000** [comment] 2018-01-26 16:38
Someone else seems to have already removed the test logging. Since we haven't had any failures recently I'm going to call this "fixed by someone who wasn't me while they were doing other work." Good for them!

**Comment by astefan** [comment] 2018-12-12 14:13
Found this one again [here](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/708/console). Couldn't reproduce it locally though :-(.

```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=468, name=Thread-42, state=RUNNABLE, group=TGRP-RefreshListenersTests]
Caused by: java.lang.AssertionError: listener never called
	at __randomizedtesting.SeedInfo.seed([951EE2B6CFEE324A]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at org.elasticsearch.index.shard.RefreshListenersTests.lambda$testLotsOfThreads$10(RefreshListenersTests.java:317)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:847)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:821)
	at org.elasticsearch.index.shard.RefreshListenersTests.lambda$testLotsOfThreads$11(RefreshListenersTests.java:317)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.AssertionError: listener never called
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.assertTrue(Assert.java:41)
		at org.junit.Assert.assertNotNull(Assert.java:712)
		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$testLotsOfThreads$10(RefreshListenersTests.java:317)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
		... 3 more
	Suppressed: java.lang.AssertionError: listener never called
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.assertTrue(Assert.java:41)
		at org.junit.Assert.assertNotNull(Assert.java:712)
		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$testLotsOfThreads$10(RefreshListenersTests.java:317)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
		... 3 more
	Suppressed: java.lang.AssertionError: listener never called
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.assertTrue(Assert.java:41)
		at org.junit.Assert.assertNotNull(Assert.java:712)
		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$testLotsOfThreads$10(RefreshListenersTests.java:317)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
		... 3 more
	Suppressed: java.lang.AssertionError: listener never called
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.assertTrue(Assert.java:41)
		at org.junit.Assert.assertNotNull(Assert.java:712)
		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$testLotsOfThreads$10(RefreshListenersTests.java:317)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
		... 3 more
	Suppressed: java.lang.AssertionError: listener never called
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.assertTrue(Assert.java:41)
		at org.junit.Assert.assertNotNull(Assert.java:712)
		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$testLotsOfThreads$10(RefreshListenersTests.java:317)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
		... 3 more
	Suppressed: java.lang.AssertionError: listener never called
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.assertTrue(Assert.java:41)
		at org.junit.Assert.assertNotNull(Assert.java:712)
		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$testLotsOfThreads$10(RefreshListenersTests.java:317)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
		... 3 more
	Suppressed: java.lang.AssertionError: listener never called
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.assertTrue(Assert.java:41)
		at org.junit.Assert.assertNotNull(Assert.java:712)
		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$testLotsOfThreads$10(RefreshListenersTests.java:317)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
		... 3 more
	Suppressed: java.lang.AssertionError: listener never called
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.assertTrue(Assert.java:41)
		at org.junit.Assert.assertNotNull(Assert.java:712)
		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$testLotsOfThreads$10(RefreshListenersTests.java:317)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
		... 3 more
	Suppressed: java.lang.AssertionError: listener never called
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.assertTrue(Assert.java:41)
		at org.junit.Assert.assertNotNull(Assert.java:712)
		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$testLotsOfThreads$10(RefreshListenersTests.java:317)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
		... 3 more
	Suppressed: java.lang.AssertionError: listener never called
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.assertTrue(Assert.java:41)
		at org.junit.Assert.assertNotNull(Assert.java:712)
		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$testLotsOfThreads$10(RefreshListenersTests.java:317)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
		... 3 more
	Suppressed: java.lang.AssertionError: listener never called
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.assertTrue(Assert.java:41)
		at org.junit.Assert.assertNotNull(Assert.java:712)
		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$testLotsOfThreads$10(RefreshListenersTests.java:317)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
		... 3 more
	Suppressed: java.lang.AssertionError: listener never called
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.assertTrue(Assert.java:41)
		at org.junit.Assert.assertNotNull(Assert.java:712)
		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$testLotsOfThreads$10(RefreshListenersTests.java:317)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
		... 3 more
	Suppressed: java.lang.AssertionError: listener never called
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.assertTrue(Assert.java:41)
		at org.junit.Assert.assertNotNull(Assert.java:712)
		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$testLotsOfThreads$10(RefreshListenersTests.java:317)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
		... 3 more
```

**Comment by ywelsch** [comment] 2019-01-11 09:17
I've pushed 3a929c7aeac to see if that fixes the issue.

**Comment by gwbrown** [comment] 2019-01-11 15:17
This [failed today in 6.6](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.6+intake/103/) so if @ywelsch's fix succeeds it should be backported to at least 6.x as well.

**Comment by ywelsch** [comment] 2019-01-14 14:18
No more failures on master since I pushed the fix. I'm backporting it now to 6.x/6.6, and closing this. If it reoccurs again, please reopen.

**Closed by ywelsch** 2019-01-14 14:18 UTC
Labels: :Distributed/Engine, >test, >test-failure
