### ISSUE TITLE
Add Wildcard character ability for _reindex API

### ISSUE THREAD

**Issue by chromechris1** [elastic/elasticsearch#20739] opened 2016-10-04 18:34 UTC
**Elasticsearch version**: 2.3.2

**Plugins installed**: modules [lang-groovy, reindex, lang-expression], plugins [marvel-agent, watcher, shield, license, head], sites [head]

**JVM version**: OpenJDK 64-Bit Server VM (build 24.111-b01, mixed mode)

**OS version**: Red Hat Enterprise Linux Server release 6.8 (Santiago)

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. Attempt to reindex two indeces, with either index containing a wildcard character in it's name

**Provide logs (if relevant)**:
"Invalid index name [index-name-*], must not contain the following characters [\\, /, *, ?, \", <, >, |,  , ,]"

**Describe the feature**:
Please enable the _reindex API to work with indeces with wildcard characters.

**Comment by nik9000** [comment] 2016-10-04 19:04
I think this is a duplicate of https://github.com/elastic/elasticsearch/issues/19662 so I'm going to close it. Please reopen if it isn't and explain how it differs.

**Closed by nik9000** 2016-10-04 19:04 UTC
