### ISSUE TITLE
[CI] ExecuteWatchQueuedStatsTests testQueuedStats timing out

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#72035] opened 2021-04-21 15:35 UTC
This test has failed with a timeout 9 times in the past month. This isn't specific to FIPS or any particular worker configuration.

**Build scan:**
https://gradle-enterprise.elastic.co/s/latqxwe2g7lxk/tests/:x-pack:plugin:watcher:internalClusterTest/org.elasticsearch.xpack.watcher.execution.ExecuteWatchQueuedStatsTests/testQueuedStats

**Reproduction line:**
`./gradlew ':x-pack:plugin:watcher:internalClusterTest' --tests "org.elasticsearch.xpack.watcher.execution.ExecuteWatchQueuedStatsTests.testQueuedStats" -Dtests.seed=312D92B686A5AA42 -Dtests.locale=zh-SG -Dtests.timezone=America/Metlakatla -Druntime.java=16 -Dtests.fips.enabled=true`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.watcher.execution.ExecuteWatchQueuedStatsTests&tests.test=testQueuedStats

**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([312D92B686A5AA42]:0)

```

**Comment by davidkyle** [comment] 2021-04-26 08:19
Another timeout also in on master but in the release tests this time:
https://gradle-enterprise.elastic.co/s/fzcaflqhojb5s

**Comment by danhermann** [comment] 2021-05-13 12:58
Duplicate of https://github.com/elastic/elasticsearch/issues/66392

**Closed by danhermann** 2021-05-13 12:58 UTC
Labels: :Core/Features/Watcher, >test-failure, Team:Core/Features
