### ISSUE TITLE
Add "token_filters" array option to keyword type mapping

### ISSUE THREAD

**Issue by synhershko** [elastic/elasticsearch#21241] opened 2016-11-01 15:03 UTC
The separation of string to text and keyword is awesome. The only remaining item in my opinion is the not-tokenized-but-lowercased case - it is common enough but will still require some rigorous configuration. It probably makes sense now to allow specifying "token-filters" to execute on "keyword" fields directly in that field's mapping (because different approaches to normalization can be taken - ascii folding, etc). I'm aware of tokenizing tokenfilters (e.g. word-delimiter) but think we can ignore that edge-case for this purpose. WDYT?

**Comment by dakrone** [comment] 2016-11-01 15:13
Closing this as a duplicate of #18064 - @synhershko @jpountz is working on this!

**Closed by dakrone** 2016-11-01 15:13 UTC

**Comment by synhershko** [comment] 2016-11-02 03:39
Yay!
