### ISSUE TITLE
[CI] Packaging tests: dpkg: error: dpkg frontend is locked by another process

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#36047] opened 2018-11-29 12:27 UTC
I found two failures with something like this in the logs:

```
07:01:05 #   `install' failed
07:01:05 #   `install' failed
07:01:05 # dpkg failed:
07:01:05 # dpkg: error: dpkg frontend is locked by another process
07:01:05 # lsof /var/lib/dpkg/lock:
07:01:05 # COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
07:01:05 # apt-get 24459 root    5uW  REG    8,3        0  938 /var/lib/dpkg/lock
07:01:05 # dpkg failed:
07:01:05 # dpkg: error: dpkg frontend is locked by another process
07:01:05 # lsof /var/lib/dpkg/lock:
07:01:05 # COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
07:01:05 # apt-get 24459 root    5uW  REG    8,3        0  938 /var/lib/dpkg/lock
```
This is from https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+packaging-tests/154/consoleFull

Another one was a few days ago at:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+packaging-tests/136/console

Not sure if there is any relation but might be worth taking a look if it happens more often.

**Comment by nik9000** [comment] 2018-11-29 14:56
Maybe a dupe of #33762?

**Comment by danielmitterdorfer** [comment] 2018-11-29 15:54
Closing as duplicate of #33762.

**Closed by danielmitterdorfer** 2018-11-29 15:54 UTC
Labels: :Core/Infra/Build, :Core/Infra/Packaging, >test-failure
