### ISSUE TITLE
Custom Analyzer does not work as a chain as expected.

### ISSUE THREAD

**Issue by jzbahrai** [elastic/elasticsearch#20803] opened 2016-10-07 14:49 UTC
The settings are as follows:

```
   "products_v2": {
      "settings": {
         "index": {
            "creation_date": "1475684313640",
            "analysis": {
               "filter": {
                  "english_keywords": {
                     "ignore_case": "true",
                     "type": "keyword_marker",
                     "keywords_path": "analysis/exclude_stem.txt"
                  },
                  "synonym_expand": {
                     "type": "synonym",
                     "synonyms_path": "analysis/synonyms.txt"
                  },
                  "english_stemmer": {
                     "type": "stemmer",
                     "language": "english"
                  },
                  "english_stop": {
                     "type": "stop",
                     "stopwords": "_english_"
                  },
                  "english_possessive_stemmer": {
                     "type": "stemmer",
                     "language": "possessive_english"
                  },
               "char_filter": {
                  "stem_mapping": {
                     "type": "mapping",
                     "mappings_path": "analysis/char_mappings.txt"
                  }
               },
               "analyzer": {
                  "synonyms_expand": {
                     "filter": [
                        "synonym_expand",
                        "english_possessive_stemmer",
                        "lowercase",
                        "english_stop",
                        "english_keywords",
                        "english_stemmer"
                     ],
                 "type": "custom",
                  "tokenizer": "standard"
                  }
                }
         }
}
```
The expected result after expansion for synonym is the following:
```
GET /products_v2/_analyze?analyzer=english&text="jell-o"
{
   "tokens": [
      {
         "token": "jell",
         "start_offset": 1,
         "end_offset": 5,
         "type": "<ALPHANUM>",
         "position": 0
      },
      {
         "token": "o",
         "start_offset": 6,
         "end_offset": 7,
         "type": "<ALPHANUM>",
         "position": 1
      }
   ]
}
```
The synonym I put in is jello=>jell-o

The result that I get after using the synonym analyzer
```
GET /products_v2/_analyze?analyzer=synonyms_expand&text="jello"
{
   "tokens": [
      {
         "token": "jell-o",
         "start_offset": 1,
         "end_offset": 6,
         "type": "SYNONYM",
         "position": 0
      }
   ]
}
```
This doesn't seem right. I use the english chain after synonyms expanded.
The result should be the same as the one that I get when running:
GET /products_v2/_analyze?analyzer=english&text="jell-o"

The reason for this is because the standard analyzer gets applied first and only then do we apply the synonym analyzer

What happens: 
jello, the standard analyzer gets applied. There is no taken chain
Then the word gets expanded to the synonym analzyer: jell-o
At this point there is no tokenization that happens to jell-o. The word doesn't change.

When jell-o gets indexed -  it gets indexed using the english analyzer so "jell o". Therefore it doesn't change.  Is there anyway we can add a standard tokenizer to the chain of analysis after the synonym expansion happens?

**Comment by clintongormley** [comment] 2016-10-07 15:28
Duplicate of https://github.com/elastic/elasticsearch/issues/7199

**Closed by clintongormley** 2016-10-07 15:28 UTC
