### ISSUE TITLE
Too many cached tokens (> 100)

### ISSUE THREAD

**Issue by simonefrancia** [elastic/elasticsearch#74832] opened 2021-07-01 13:00 UTC
**Elasticsearch version** : 7.13

**Plugins installed**: We are using Managed Service by AWS

I've created a filter as autocomplete_filter based on ngram with `min_gram=1` and `max_gram=10`.
Here my index settings. 

```
"settings": {
                "index": {
                    "number_of_shards": "8",
                    "number_of_replicas": "1"
                },
                "analysis": {
                    "filter": {
                        "autocomplete_filter": {
                            "type": "ngram",
                            "min_gram": 1,
                            "max_gram": 10
                        }
                    },
                    "analyzer": {
                           "autocomplete": {
                                                  "filter": [
                                                               "lowercase",
                                                               "autocomplete_filter"],
              "type": "custom",
              "tokenizer": "standard"
            }
```

Inside out mapping we inserted an author attribute that we want to use as `search_as_you_type` and it's linked with the analyzer.

```
"author": {
                        "type": "search_as_you_type",
                        "analyzer": "autocomplete",
                        "search_analyzer": "standard"
                    },
```

The problem with this configuration is shown there. 

```
{
      "index": {
        "_index": "episode",
        "_type": "_doc",
        "_id": "1",
        "status": 500,
        "error": {
          "type": "illegal_state_exception",
          "reason": "Too many cached tokens (> 100)"
        }
      }
    }
```

This problem appears when we index data for `author` attribute.

Thanks

**Comment by endlessbounce** [comment] 2021-07-01 16:29
I get the same error when I ingest an attachment (a document with Data field Base64 encoded), I figured out it somehow depends on the file name. Example:
When ingesting 123456789ABCD.xlsx - it goes through.
When ingesting 123456789ABCDE.xlsx - it throws this error for the same file (with the same content) just renamed with one more letter added. I.e. any file of any type will throw this error if the file name is larger than 13 chars (in this case without the extension).
The config for the pipeline is below.

```
{
  "id": "attachment",
  "config": {
    "description": "Extract attachment information",
    "processors": [
      {
        "attachment": {
          "field": "Data",
          "properties": [
            "content"
          ]
        }
      },
      {
        "remove": {
          "field": "Data",
          "description": "Removes the fields which had Base-64 data",
          "ignore_missing": true
        }
      }
    ]
  }
}
```

**Comment by jimczi** [comment] 2021-07-02 06:46
The `search_as_you_type` field uses shingles and ngrams under the hood so using an `ngram` analyzer for this field is redundant and can lead to too many token. You can set a simple tokenizer and let the `search_as_you_type` add the required filters for autocomplete automatically.
Since this is not a bug but rather a misconfiguration I am closing this issue. Don't hesitate to reopen if I missed anything.

**Closed by jimczi** 2021-07-02 06:46 UTC
Labels: :Search/Analysis, Team:Search

**Comment by loretoparisi** [comment] 2021-07-02 08:14
@jimczi so that's why when the index has been built, one se

```json
{
    "type": "search_as_you_type",
    "doc_values": false,
    "max_shingle_size": 3
}
```

How to control then the `min_gram` and `max_gram` when  using `search_as_you_type`?
From the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/search-as-you-type.html) I can only see `max_shingle_size`.
