### ISSUE TITLE
Adding simulation capability for ILM/SLM policies

### ISSUE THREAD

**Issue by hartfordfive** [elastic/elasticsearch#75856] opened 2021-07-29 19:40 UTC
# Description

Currently, when testing ILM or SLM policies, it make take days to determine if your intended changes have worked as expected. 
For example, in the case of ILM policies, if you're attempting to confirm that an index would in fact transition to the cold phase after 5 days to be updated as a searchable snapshot, you have to wait at least 5 days.  Having a simulation feature could allow users to simulate execution of ILM and SLM policies which could "fake" the date for the `min_age`/`max_age` options.   Simulation results could then allow a faster update cycle without necessarily having to test in a DEV environment first.

**Comment by andreidan** [comment] 2021-12-01 13:43
Closing as duplicate of #62959.

**Closed by andreidan** 2021-12-01 13:43 UTC
Labels: >enhancement, :Data Management/ILM+SLM, Team:Data Management
