### ISSUE TITLE
[CI] SearchAsyncActionTests.testFanOutAndCollect

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#29242] opened 2018-03-26 08:43 UTC
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=fedora/846/console

Apparently commit 29e103cc064181b42feab66a21f03ce087a529c6 failed with:

```
java.lang.AssertionError: []
	at __randomizedtesting.SeedInfo.seed([807C41D74FFA71C0:FB8DC4A7B651B043]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.elasticsearch.action.search.SearchAsyncActionTests.testFanOutAndCollect(SearchAsyncActionTests.java:357)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
...
```

The assertion in question is:

    assertTrue(nodeToContextMap.get(primaryNode).toString(), nodeToContextMap.get(primaryNode).isEmpty());

(Strange that `.toString()` returned `[]` but `.isEmpty()` returned `false`)

```
REPRODUCE WITH: ./gradlew :server:test \
  -Dtests.seed=807C41D74FFA71C0 \
  -Dtests.class=org.elasticsearch.action.search.SearchAsyncActionTests \
  -Dtests.method="testFanOutAndCollect" \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-Latn-ME \
  -Dtests.timezone=Africa/Lome
```

Does not reproduce locally for me, even with `-Dtests.iters=1000`.

**Comment by DaveCTurner** [comment] 2018-03-26 11:46
See also https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-java-periodic/ESJAVA=java10,ESRUNTIME=java8,nodes=linux/22/console

**Comment by colings86** [comment] 2018-05-11 09:10
This looks like its been fixed as it failed for three days in a row (25-27 March 2018) and hasn't failed since. I'll close this for now and hasn't failed since. If this fails again please reopen the issue

**Comment by vladimirdolzhenko** [comment] 2018-07-05 07:23
Issue appears again: 

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=debian/2536/console

```
./gradlew :server:test -Dtests.seed=12B50C4C51FB075B -Dtests.class=org.elasticsearch.action.search.SearchAsyncActionTests -Dtests.method="testFanOutAndCollect" -Dtests.security.manager=true -Dtests.locale=ja -Dtests.timezone=America/Argentina/La_Rioja
```

but it is not reproducible locally

**Comment by colings86** [comment] 2018-08-03 10:43
> (Strange that .toString() returned [] but .isEmpty() returned false)

This is very weird because the object in question is a simple `Set<Long>`. Also we remove the contextId from the set in `sendFreeContext()` which is called (not directly) from the `run()` method of the search phase in the test. This is also where we count down the latch so it should no be possible for the test to get past the `latch.await()` with a search phase (and context) still in flight.

The only idea I have to progress this is to add a check before we countdown the latch to make sure its not already 0 (i.e. we are running something twice) and unmute the test to catch this again.

Would welcome any ideas others have on this too

**Closed** 2018-09-25 12:58 UTC
Labels: :Search/Search, >test-failure
