### ISSUE TITLE
Create configuration reference

### ISSUE THREAD

**Issue by j0hnsmith** [elastic/elasticsearch#11701] opened 2015-06-16 14:00 UTC
There's no single source of reference for configuration options which makes configuring Elasticsearch awkward. https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration.html is a good start but I believe more is omitted than included (`path.repo` for example).

Elasticsearch needs a single page that lists every possible configuration option with an explanation of what the setting does, Django has a good example https://docs.djangoproject.com/en/1.8/ref/settings/

**Comment by colings86** [comment] 2015-06-17 08:35
Duplicate of https://github.com/elastic/elasticsearch/issues/11504, closing in favour of that issue.

**Closed by colings86** 2015-06-17 08:35 UTC
