### ISSUE TITLE
[CI] Autoscaling reference docs Incorrect HTTP method for uri

### ISSUE THREAD

**Issue by albertzaharovits** [elastic/elasticsearch#52050] opened 2020-02-07 14:33 UTC
```
java.lang.AssertionError: Failure at [reference/autoscaling/apis/get-autoscaling-decision:11]: expected [2xx] status code but api [raw[method=GET path=_autoscaling/decision/]] returned [405 Method Not Allowed] [{"error":"Incorrect HTTP method for uri [/_autoscaling/decision/?error_trace=true] and method [GET], allowed: [POST]","status":405}] |  
```

Build stats:
https://gradle-enterprise.elastic.co/s/etiuz357uq37a
https://gradle-enterprise.elastic.co/s/ulirtbaby33yw
https://gradle-enterprise.elastic.co/s/scsxzp5ygfots

cc @jasontedor  (because you've recently created these)

**Comment by jasontedor** [comment] 2020-02-07 15:31
This appears to be an infrastructure problem. The autoscaling docs are not suppose to be included in release docs at this time, yet they are clearly being included here. I think this might relate to #51743, but I’m not sure. Can @nik9000 and @jrodewig help?

**Comment by jrodewig** [comment] 2020-02-07 16:02
I can revert #51743, but I don't think it's related.

#51743 should only impact what's included in the HTML output. I believe `DocsClientYamlTestSuite` picks up any test snippets in the repo's asciidoc files, regardless of whether it's included in the HTML output.

Here's how I tested this locally:

1. Add a new asciidoc file containing a purposefully broken snippet.
2. Do not include the asciidoc file in the docbook index or other files.
3. Run `./gradlew -pdocs check` to ensure `DocsClientYamlTestSuite`  failed on the broken snippet test. 

If the intent is to skip tests on these snippets for now, we should add a `// TEST[skip: ...]` comment below the snippet.

**Comment by henningandersen** [comment] 2020-02-07 16:45
@jrodewig I think the problem is that change, which now only checks if we are on a release branch or not. But the code checks if we are in a release build and if we are, it does not register the HTTP endpoints.

I think we should only include the docs if we are not on a release branch AND not in a release build.

**Comment by jrodewig** [comment] 2020-02-07 16:55
@henningandersen I opened #52066 to revert.

**Comment by jrodewig** [comment] 2020-02-07 17:16
The revert of #52066 has now been merged into `master` and `7.x`. Hopefully, we'll see these clear up now.  

I'll work on another way to include the autoscaling and EQL docs as @henningandersen outlined. 

Sorry for the noise!

**Comment by jasontedor** [comment] 2020-02-07 23:35
I opened #52088.

**Closed** 2020-02-08 02:35 UTC
Labels: :Distributed/Autoscaling, :Docs, >test-failure
