### ISSUE TITLE
Shards stuck in INITIALIZING

### ISSUE THREAD

**Issue by krisb78** [elastic/elasticsearch#12926] opened 2015-08-17 09:11 UTC
I have a fairly large index (~3.5 million documents, with nested fields, some of the docs are quite large) where the documents are being updated a lot.

A while ago the cluster went into the yellow state and I'm seeing a number of shards stuck in the "INITIALIZING" state:

```
joint_user_summary_v1                   0 r INITIALIZING                   127.0.1.1 cubitsearch-1
joint_user_summary_v1                   7 r INITIALIZING                   127.0.1.1 cubitsearch-5
joint_user_summary_v1                   7 r INITIALIZING                   127.0.1.1 cubitsearch-2
joint_user_summary_v1                   3 r INITIALIZING                   127.0.1.1 cubitsearch-1
joint_user_summary_v1                   1 r INITIALIZING                   127.0.1.1 cubitsearch-4
joint_user_summary_v1                   1 r INITIALIZING                   127.0.1.1 cubitsearch-3
joint_user_summary_v1                   5 r INITIALIZING                   127.0.1.1 cubitsearch-2
joint_user_summary_v1                   6 r INITIALIZING                   127.0.1.1 cubitsearch-3
joint_user_summary_v1                   6 r INITIALIZING                   127.0.1.1 cubitsearch-5
```

Naturally, I can't optimize this index anymore:

```
{"_shards":{"total":30,"successful":5,"failed":6,"failures":[{"index":"joint_user_summary_v1","shard":0,"status":500,"reason":"BroadcastShardOperationFailedException[[joint_user_summary_v1][0] ]; nested: RemoteTransportException[[cubitsearch-2][inet[/10.0.1.236:9300]][indices:admin/optimize[s]]]; nested: OptimizeFailedEngineException[[joint_user_summary_v1][0] force merge failed]; nested: FlushNotAllowedEngineException[[joint_user_summary_v1][0] recovery is in progress, flush is not allowed]; "},{"index":"joint_user_summary_v1","shard":1,"status":500,"reason":"BroadcastShardOperationFailedException[[joint_user_summary_v1][1] ]; nested: RemoteTransportException[[cubitsearch-2][inet[/10.0.1.236:9300]][indices:admin/optimize[s]]]; nested: OptimizeFailedEngineException[[joint_user_summary_v1][1] force merge failed]; nested: FlushNotAllowedEngineException[[joint_user_summary_v1][1] recovery is in progress, flush is not allowed]; "},{"index":"joint_user_summary_v1","shard":3,"status":500,"reason":"BroadcastShardOperationFailedException[[joint_user_summary_v1][3] ]; nested: RemoteTransportException[[cubitsearch-3][inet[/10.0.1.237:9300]][indices:admin/optimize[s]]]; nested: OptimizeFailedEngineException[[joint_user_summary_v1][3] force merge failed]; nested: FlushNotAllowedEngineException[[joint_user_summary_v1][3] recovery is in progress, flush is not allowed]; "},{"index":"joint_user_summary_v1","shard":5,"status":500,"reason":"BroadcastShardOperationFailedException[[joint_user_summary_v1][5] ]; nested: RemoteTransportException[[cubitsearch-1][inet[/10.0.1.235:9300]][indices:admin/optimize[s]]]; nested: OptimizeFailedEngineException[[joint_user_summary_v1][5] force merge failed]; nested: FlushNotAllowedEngineException[[joint_user_summary_v1][5] recovery is in progress, flush is not allowed]; "},{"index":"joint_user_summary_v1","shard":6,"status":500,"reason":"BroadcastShardOperationFailedException[[joint_user_summary_v1][6] ]; nested: RemoteTransportException[[cubitsearch-1][inet[/10.0.1.235:9300]][indices:admin/optimize[s]]]; nested: OptimizeFailedEngineException[[joint_user_summary_v1][6] force merge failed]; nested: FlushNotAllowedEngineException[[joint_user_summary_v1][6] recovery is in progress, flush is not allowed]; "},{"index":"joint_user_summary_v1","shard":7,"status":500,"reason":"BroadcastShardOperationFailedException[[joint_user_summary_v1][7] ]; nested: RemoteTransportException[[cubitsearch-3][inet[/10.0.1.237:9300]][indices:admin/optimize[s]]]; nested: OptimizeFailedEngineException[[joint_user_summary_v1][7] force merge failed]; nested: FlushNotAllowedEngineException[[joint_user_summary_v1][7] recovery is in progress, flush is not allowed]; "}]}}
```

Here's an excerpt from the log file that may shed some light on the issue:

```
Aug 17 09:06:31 cubitsearch-3 elasticsearch: [2015-08-17 09:06:31,525][DEBUG][action.bulk              ] [cubitsearch-3] observer: timeout notification from cluster service. timeout setting [60ms], time since start [60ms]
Aug 17 09:06:31 cubitsearch-3 elasticsearch: [2015-08-17 09:06:31,525][DEBUG][action.bulk              ] [cubitsearch-3] observer: timeout notification from cluster service. timeout setting [60ms], time since start [60ms]
Aug 17 09:06:31 cubitsearch-3 elasticsearch: [2015-08-17 09:06:31,939][WARN ][indices.cluster          ] [cubitsearch-3] [[joint_user_summary_v1][1]] marking and sending shard failed due to [failed recovery]
Aug 17 09:06:31 cubitsearch-3 elasticsearch: org.elasticsearch.indices.recovery.RecoveryFailedException: [joint_user_summary_v1][1]: Recovery failed from [cubitsearch-2][U2eMGyQ7Rhic1lHqzIoLXA][cubitsearch-2][inet[/10.0.1.236:9300]]{max_local_storage_nodes=1, master=false} into [cubitsearch-3][IEP7xQczReKinA78HfLC3Q][cubitsearch-3][inet[/10.0.1.237:9300]]{max_local_storage_nodes=1, master=false}
Aug 17 09:06:31 cubitsearch-3 elasticsearch: #011at org.elasticsearch.indices.recovery.RecoveryTarget.doRecovery(RecoveryTarget.java:280)
Aug 17 09:06:31 cubitsearch-3 elasticsearch: #011at org.elasticsearch.indices.recovery.RecoveryTarget.access$700(RecoveryTarget.java:70)
Aug 17 09:06:31 cubitsearch-3 elasticsearch: #011at org.elasticsearch.indices.recovery.RecoveryTarget$RecoveryRunner.doRun(RecoveryTarget.java:561)
Aug 17 09:06:31 cubitsearch-3 elasticsearch: #011at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
Aug 17 09:06:31 cubitsearch-3 elasticsearch: #011at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
Aug 17 09:06:31 cubitsearch-3 elasticsearch: #011at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
Aug 17 09:06:31 cubitsearch-3 elasticsearch: #011at java.lang.Thread.run(Thread.java:745)
Aug 17 09:06:31 cubitsearch-3 elasticsearch: Caused by: org.elasticsearch.transport.RemoteTransportException: [cubitsearch-2][inet[/10.0.1.236:9300]][internal:index/shard/recovery/start_recovery]
Aug 17 09:06:31 cubitsearch-3 elasticsearch: Caused by: org.elasticsearch.index.engine.RecoveryEngineException: [joint_user_summary_v1][1] Phase[2] Execution failed
Aug 17 09:06:31 cubitsearch-3 elasticsearch: #011at org.elasticsearch.index.engine.InternalEngine.recover(InternalEngine.java:902)
Aug 17 09:06:31 cubitsearch-3 elasticsearch: #011at org.elasticsearch.index.shard.IndexShard.recover(IndexShard.java:780)
Aug 17 09:06:31 cubitsearch-3 elasticsearch: #011at org.elasticsearch.indices.recovery.RecoverySource.recover(RecoverySource.java:125)
Aug 17 09:06:31 cubitsearch-3 elasticsearch: #011at org.elasticsearch.indices.recovery.RecoverySource.access$200(RecoverySource.java:49)
Aug 17 09:06:31 cubitsearch-3 elasticsearch: #011at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:146)
Aug 17 09:06:31 cubitsearch-3 elasticsearch: #011at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:132)
Aug 17 09:06:31 cubitsearch-3 elasticsearch: #011at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:279)
Aug 17 09:06:31 cubitsearch-3 elasticsearch: #011at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
Aug 17 09:06:31 cubitsearch-3 elasticsearch: #011at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
Aug 17 09:06:31 cubitsearch-3 elasticsearch: #011at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
Aug 17 09:06:31 cubitsearch-3 elasticsearch: #011at java.lang.Thread.run(Thread.java:745)
Aug 17 09:06:31 cubitsearch-3 elasticsearch: Caused by: org.elasticsearch.transport.ReceiveTimeoutTransportException: [cubitsearch-3][inet[/10.0.1.237:9300]][internal:index/shard/recovery/prepare_translog] request_id [14280416] timed out after [900000ms]
Aug 17 09:06:31 cubitsearch-3 elasticsearch: #011at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:529)
Aug 17 09:06:31 cubitsearch-3 elasticsearch: #011... 3 more
```

I was hoping that upgrading to the latest version (1.7.1) would fix the problem, but unfortunately it persists.

**Comment by clintongormley** [comment] 2015-08-17 10:59
Are you setting the cluster timeout somewhere? I'm seeing `timeout setting [60ms]` while the timeout in the code is 60 seconds.  Also, what logs are you seeing in the other nodes (eg `cubitsearch-2`) about why recovery is failing?

**Comment by krisb78** [comment] 2015-08-17 11:49
I'm setting the `timeout` param on bulk requests to "60", I'm assuming it's coming from there.

Here's what I see in the logs on cubitsearch-2:

```
Aug 17 11:36:12 cubitsearch-2 elasticsearch: [2015-08-17 11:36:12,191][WARN ][indices.cluster          ] [cubitsearch-2] [[joint_user_summary_v1][5]] marking and sending shard failed due to [failed recovery]
Aug 17 11:36:12 cubitsearch-2 elasticsearch: org.elasticsearch.indices.recovery.RecoveryFailedException: [joint_user_summary_v1][5]: Recovery failed from [cubitsearch-1][-nlEhC5-SliQ_REVJm1FWA][cubitsearch-1][inet[/10.0.1.235:9300]]{max_local_storage_nodes=1, master=false} into [cubitsearch-2][U2eMGyQ7Rhic1lHqzIoLXA][cubitsearch-2][inet[/10.0.1.236:9300]]{max_local_storage_nodes=1, master=false}
Aug 17 11:36:12 cubitsearch-2 elasticsearch: #011at org.elasticsearch.indices.recovery.RecoveryTarget.doRecovery(RecoveryTarget.java:280)
Aug 17 11:36:12 cubitsearch-2 elasticsearch: #011at org.elasticsearch.indices.recovery.RecoveryTarget.access$700(RecoveryTarget.java:70)
Aug 17 11:36:12 cubitsearch-2 elasticsearch: #011at org.elasticsearch.indices.recovery.RecoveryTarget$RecoveryRunner.doRun(RecoveryTarget.java:561)
Aug 17 11:36:12 cubitsearch-2 elasticsearch: #011at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
Aug 17 11:36:12 cubitsearch-2 elasticsearch: #011at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
Aug 17 11:36:12 cubitsearch-2 elasticsearch: #011at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
Aug 17 11:36:12 cubitsearch-2 elasticsearch: #011at java.lang.Thread.run(Thread.java:745)
Aug 17 11:36:12 cubitsearch-2 elasticsearch: Caused by: org.elasticsearch.transport.RemoteTransportException: [cubitsearch-1][inet[/10.0.1.235:9300]][internal:index/shard/recovery/start_recovery]
Aug 17 11:36:12 cubitsearch-2 elasticsearch: Caused by: org.elasticsearch.index.engine.RecoveryEngineException: [joint_user_summary_v1][5] Phase[2] Execution failed
Aug 17 11:36:12 cubitsearch-2 elasticsearch: #011at org.elasticsearch.index.engine.InternalEngine.recover(InternalEngine.java:902)
Aug 17 11:36:12 cubitsearch-2 elasticsearch: #011at org.elasticsearch.index.shard.IndexShard.recover(IndexShard.java:780)
Aug 17 11:36:12 cubitsearch-2 elasticsearch: #011at org.elasticsearch.indices.recovery.RecoverySource.recover(RecoverySource.java:125)
Aug 17 11:36:12 cubitsearch-2 elasticsearch: #011at org.elasticsearch.indices.recovery.RecoverySource.access$200(RecoverySource.java:49)
Aug 17 11:36:12 cubitsearch-2 elasticsearch: #011at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:146)
Aug 17 11:36:12 cubitsearch-2 elasticsearch: #011at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:132)
Aug 17 11:36:12 cubitsearch-2 elasticsearch: #011at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:279)
Aug 17 11:36:12 cubitsearch-2 elasticsearch: #011at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
Aug 17 11:36:12 cubitsearch-2 elasticsearch: #011at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
Aug 17 11:36:12 cubitsearch-2 elasticsearch: #011at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
Aug 17 11:36:12 cubitsearch-2 elasticsearch: #011at java.lang.Thread.run(Thread.java:745)
Aug 17 11:36:12 cubitsearch-2 elasticsearch: Caused by: org.elasticsearch.transport.ReceiveTimeoutTransportException: [cubitsearch-2][inet[/10.0.1.236:9300]][internal:index/shard/recovery/prepare_translog] request_id [13236725] timed out after [900000ms]
Aug 17 11:36:12 cubitsearch-2 elasticsearch: #011at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:529)
Aug 17 11:36:12 cubitsearch-2 elasticsearch: #011... 3 more
Aug 17 11:36:19 cubitsearch-2 elasticsearch: [2015-08-17 11:36:19,768][WARN ][indices.cluster          ] [cubitsearch-2] [[joint_user_summary_v1][5]] marking and sending shard failed due to [failed to create shard]
Aug 17 11:36:19 cubitsearch-2 elasticsearch: org.elasticsearch.index.shard.IndexShardCreationException: [joint_user_summary_v1][5] failed to create shard
Aug 17 11:36:19 cubitsearch-2 elasticsearch: #011at org.elasticsearch.index.IndexService.createShard(IndexService.java:357)
Aug 17 11:36:19 cubitsearch-2 elasticsearch: #011at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyInitializingShard(IndicesClusterStateService.java:704)
Aug 17 11:36:19 cubitsearch-2 elasticsearch: #011at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyNewOrUpdatedShards(IndicesClusterStateService.java:605)
Aug 17 11:36:19 cubitsearch-2 elasticsearch: #011at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:185)
Aug 17 11:36:19 cubitsearch-2 elasticsearch: #011at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:480)
Aug 17 11:36:19 cubitsearch-2 elasticsearch: #011at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:196)
Aug 17 11:36:19 cubitsearch-2 elasticsearch: #011at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:162)
Aug 17 11:36:19 cubitsearch-2 elasticsearch: #011at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
Aug 17 11:36:19 cubitsearch-2 elasticsearch: #011at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
Aug 17 11:36:19 cubitsearch-2 elasticsearch: #011at java.lang.Thread.run(Thread.java:745)
Aug 17 11:36:19 cubitsearch-2 elasticsearch: Caused by: org.apache.lucene.store.LockObtainFailedException: Can't lock shard [joint_user_summary_v1][5], timed out after 5000ms
Aug 17 11:36:19 cubitsearch-2 elasticsearch: #011at org.elasticsearch.env.NodeEnvironment$InternalShardLock.acquire(NodeEnvironment.java:582)
Aug 17 11:36:19 cubitsearch-2 elasticsearch: #011at org.elasticsearch.env.NodeEnvironment.shardLock(NodeEnvironment.java:510)
Aug 17 11:36:19 cubitsearch-2 elasticsearch: #011at org.elasticsearch.index.IndexService.createShard(IndexService.java:310)
Aug 17 11:36:19 cubitsearch-2 elasticsearch: #011... 9 more
```

**Comment by krisb78** [comment] 2015-08-17 12:00
Also, I changed the timeout on these bulk requests to `60 * 1000` and am now seeing:

```
Aug 17 11:59:15 cubitsearch-2 elasticsearch: [2015-08-17 11:59:15,210][DEBUG][action.bulk              ] [cubitsearch-2] observer: timeout notification from cluster service. timeout setting [1m], time since start [1m]
Aug 17 11:59:19 cubitsearch-2 elasticsearch: [2015-08-17 11:59:19,214][DEBUG][action.bulk              ] [cubitsearch-2] observer: timeout notification from cluster service. timeout setting [1m], time since start [1m]
Aug 17 11:59:19 cubitsearch-2 elasticsearch: [2015-08-17 11:59:19,214][DEBUG][action.bulk              ] [cubitsearch-2] observer: timeout notification from cluster service. timeout setting [1m], time since start [1m]
```

**Comment by krisb78** [comment] 2015-08-17 12:03
Every now and then I'm also seeing things like:

```
Aug 17 12:02:10 cubitsearch-2 elasticsearch: [2015-08-17 12:02:10,262][WARN ][transport                ] [cubitsearch-2] Received response for a request that has timed out, sent [1799364ms] ago, timed out [899363ms] ago, action [internal:index/shard/recovery/prepare_translog], node [[cubitsearch-3][IEP7xQczReKinA78HfLC3Q][cubitsearch-3][inet[/10.0.1.237:9300]]{max_local_storage_nodes=1, master=false}], id [15135853]
```

```
Aug 17 12:01:45 cubitsearch-2 elasticsearch: [2015-08-17 12:01:45,397][WARN ][transport                ] [cubitsearch-2] Received response for a request that has timed out, sent [1374518ms] ago, timed out [474517ms] ago, action [internal:index/shard/recovery/prepare_translog], node [[cubitsearch-1][-nlEhC5-SliQ_REVJm1FWA][cubitsearch-1][inet[/10.0.1.235:9300]]{max_local_storage_nodes=1, master=false}], id [15166776]
```

**Comment by clintongormley** [comment] 2015-08-17 12:33
You're setting it to 60 milliseconds, not 60 seconds. Try `60s`.

**Comment by krisb78** [comment] 2015-08-17 12:50
Yep, done that, please see above.

**Comment by clintongormley** [comment] 2015-08-17 12:54
ok, looks like the root of the problem is here:

    Caused by: org.apache.lucene.store.LockObtainFailedException: Can't lock shard [joint_user_summary_v1][5], timed out after 5000ms

This looks like a duplicate of #12011.  I think the only thing you can do here is to restart your nodes (one by one).  We're still trying to figure out what is causing this issue.

**Closed by clintongormley** 2015-08-17 12:54 UTC
Labels: :Recovery, feedback_needed

**Comment by krisb78** [comment] 2015-08-17 13:02
I did restart all of them a couple of times, but it didn't help...

Thanks for your prompt responses though, I'll be keeping an eye on https://github.com/elastic/elasticsearch/issues/12011
