### ISSUE TITLE
POST /_cat/indices causes a NullPointerException

### ISSUE THREAD

**Issue by oxymor0n** [elastic/elasticsearch#24032] opened 2017-04-10 20:57 UTC
When I made the mistake of using POST instead of get when querying `/_cat/indices`, ES returns a 500 message saying it has encountered an NPE.

To replicate, run the following cURL command against the official ES Docker image:

```
curl -XPOST -u elastic:changeme localhost:9200/_cat/indices?pretty
{
  "error" : {
    "root_cause" : [
      {
        "type" : "null_pointer_exception",
        "reason" : null
      }
    ],
    "type" : "null_pointer_exception",
    "reason" : null
  },
  "status" : 500
}
```

**Comment by jasontedor** [comment] 2017-04-10 21:01
This should result in method not allowed (cf. #15335) but instead the request gets routed to the index handler which NPEs because there is no content in the request. There is an open pull request for this, #17916. I'm closing this as a duplicate of #15335.

**Closed by jasontedor** 2017-04-10 21:01 UTC
