### ISSUE TITLE
subclass of   ActionFilter.Simple  was invoked twice

### ISSUE THREAD

**Issue by whdwsl** [elastic/elasticsearch#14577] opened 2015-11-06 09:02 UTC
hi, guys,   i wrote a Filter whice extends ActionFilter.Simple ,  and override the method : apply(String action, ActionResponse response, ActionListener listener).  when i invoke method: client.prepareSearch,  the apply method  was invoked twice whice is not i wanted, once is enough. is there sth i missed ?  here is my code :

public static class LoggingFilter extends ActionFilter.Simple {

        @Inject
        public LoggingFilter(Settings settings) {
            super(settings);
        }

        @Override
        public int order() {
            return 999;
        }

        @Override
        protected boolean apply(String action, ActionRequest request, ActionListener listener) {
            return true;
        }

        @Override
        protected boolean apply(String action, ActionResponse response, ActionListener listener) {
            if ("indices:data/read/search".equals(action)) {
                System.out.println("=========" + action + "======" + listener);
                System.out.println("=========" + response.hashCode() + "======" );
            }

            return true;
        }
    }

public class ActionInvokeModule extends AbstractModule implements PreProcessModule {

        @Override
        protected void configure() {
            bind(LoggingFilter.class).asEagerSingleton();
        }

        @Override
        public void processModule(Module module) {
            if (module instanceof ActionModule) {
                ((ActionModule)module).registerFilter(LoggingFilter.class);
            }
        }
    }

public class ActionInvokePlugin extends AbstractPlugin {

    @Override
    public Collection<Class<? extends Module>> modules() {
        Collection<Class<? extends Module>> modules = new ArrayList<Class<? extends Module>>();
        modules.add(ActionLoggingModule.class);
        System.out.println("==========loaded log plugin");
        return modules;
    }
}

this is my client :
@Test
    public void testSimpleSearch() {
        SearchResponse response = client.prepareSearch("twitter2")
                .setTypes("tweet2")
                .setSearchType(SearchType.DFS_QUERY_THEN_FETCH)
                .setQuery(QueryBuilders.termQuery("user", "wangwu"))             // Query
                .setFrom(0).setSize(60).setExplain(true)
                .execute()
                .actionGet();
        for (SearchHit hit : response.getHits().getHits()) {
            System.out.println("======" + hit.getSource());
        }

    }

**Comment by javanna** [comment] 2015-11-23 16:41
I think this is the same as #11710. If it happens only with search, it's because TransportSearchAction delegates to a subaction (depending on the search type) which causes the duplication you are seeing.

**Comment by javanna** [comment] 2015-11-24 19:07
Closing as duplicate of #11710 as it is caused by the same problem. Feel free to reopen if that's not the case.

**Closed by javanna** 2015-11-24 19:07 UTC
