### ISSUE TITLE
Remove retry logic from IndicesClusterStateService

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#15896] opened 2016-01-11 17:36 UTC
IndicesClusterStateService currently manages its own retries when managing shard state. Channel related failures will now be managed in ShardStateAction (#15748, #15895) so the retry logic should be refactored there to only handle non-channel failures.

**Comment by bleskes** [comment] 2018-03-20 12:11
This issue is w.r.t to resending of shard failed message on each incoming cluster state. This can cause an barrage of shard failed messages. It is unneeded as ShardStateAction is now more resilient and should take care of all the retries (network failures, master loss , etc)

**Comment by jgq2008303393** [comment] 2018-04-08 05:55
@bleskes we still encounter this problem in 5.6.4.

https://discuss.elastic.co/t/half-dead-node-lead-to-cluster-hang/113658

**Comment by bleskes** [comment] 2018-04-09 09:32
@jgq2008303393 the issue is still open, so sadly, that's expected.

**Comment by DaveCTurner** [comment] 2022-07-29 11:36
This class has been drastically simplified since 2016 and I think there's no retry logic in `IndicesClusterStateService` any more so I'm closing this.

**Closed by DaveCTurner** 2022-07-29 11:36 UTC
Labels: >enhancement, :Distributed/Distributed, Team:Distributed, >tech-debt
