### ISSUE TITLE
[CI] :qa:repository-old-versions:oldES6_8_20Fixture fails

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#84223] opened 2022-02-22 11:50 UTC
### CI Link

https://gradle-enterprise.elastic.co/s/2ydktlakcvcme

### Repro line

-

### Does it reproduce?

Didn't try

### Applicable branches

master

### Failure excerpt

```
uncaught exception in thread [main]
org.elasticsearch.ElasticsearchException: Failure running machine learning native code. This could be due to running on an unsupported OS or distribution, missing OS libraries, or a problem with the temp directory. To bypass this problem by running Elasticsearch without machine learning functionality set [xpack.ml.enabled: false].
	at org.elasticsearch.xpack.ml.MachineLearning.createComponents(MachineLearning.java:868)
	at org.elasticsearch.node.Node.lambda$new$16(Node.java:679)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.elasticsearch.node.Node.<init>(Node.java:693)
	at org.elasticsearch.node.Node.<init>(Node.java:289)
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:234)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:234)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:358)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:166)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:157)
	at org.elasticsearch.common.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:81)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112)
	at org.elasticsearch.cli.Command.main(Command.java:77)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:122)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80)
For complete error details, refer to the log at /usr/share/elasticsearch/logs/elasticsearch-node.log
WARNING: A terminally deprecated method in java.lang.System has been called
```

**Comment by cbuescher** [comment] 2022-02-22 11:51
This looks very similar to https://github.com/elastic/elasticsearch/issues/80177.

**Comment by mark-vieira** [comment] 2022-02-22 22:12
Hmm, haven't seen any other instances of this. Strange that the idp-fixture also blew up with what looks like some kind of timeout issue. I don't believe we capture the docker-fixture logs anywhere to later inspect. Let's see if we get another one of these and if so we might need to add some additional diagnostics here.

**Comment by mark-vieira** [comment] 2022-02-28 17:21
Closing this as a duplicate of https://github.com/elastic/elasticsearch/issues/81980

**Closed by mark-vieira** 2022-02-28 17:21 UTC
Labels: :Delivery/Build, >test-failure, Team:Delivery
