### ISSUE TITLE
X-Pack support for Java high level REST client (feature request)

### ISSUE THREAD

**Issue by thomasbratt** [elastic/elasticsearch#33060] opened 2018-08-22 12:55 UTC
X-Pack only supports the Java transport client, which will be removed in future release.

This feature request is to ask for X-Pack support in the Java high level REST client.

References:

"We plan on deprecating the TransportClient in Elasticsearch 7.0 and removing it completely in 8.0."
https://www.elastic.co/guide/en/x-pack/current/java-clients.html#transport-client

"If you want to use a Java transport client with a cluster where X-Pack is installed, then you must download and configure the X-Pack transport client."
https://www.elastic.co/guide/en/elasticsearch/reference/6.x/setup-xpack-client.html

**Comment by jasontedor** [comment] 2018-08-22 12:58
Heya, thanks for your interest! We agree this is very important, and is actively being worked on across the team. In fact, we have an existing issue for this where we are tracking completeness of the APIs. See #29827. I hope you do not mind then that I close this issue as a duplicate of that one.

**Closed by jasontedor** 2018-08-22 12:58 UTC

**Comment by thomasbratt** [comment] 2018-08-22 13:38
@jasontedor no that's perfect thanks. Don't know why I could find it earlier :)
