### ISSUE TITLE
Scripting: GeoPoint.distanceInMiles is broken when GeoPoints come from an array

### ISSUE THREAD

**Issue by alexlitvak13** [elastic/elasticsearch#20486] opened 2016-09-14 19:28 UTC
**Elasticsearch version**: 2.4.0
**JVM version**: 1.8
**OS version**: Elastic Cloud

**Description of the problem including expected versus actual behavior**:

distanceInMiles() is not recognized when GeoPoints come from an array.  Expected behavior is that the geo distance methods would operate on individual GeoPoints regardless of where they originate.

Error Message: No signature of method: org.elasticsearch.common.geo.GeoPoint.distanceInMiles() is applicable for argument types: (java.lang.Double, java.lang.Double)

Seems like elasticsearch is hoping for one of these: org.elasticsearch.index.fielddata.ScriptDocValues$GeoPoints

Works fine: "script": "distance = doc['home.coordinates'].distanceInMiles(lat,lon)"
Works fine: "script": "doc[favorite_parks.coordinates].each { coordinate -> sumOfDistances = 1 }; return 1 "
Doesn't work: "script": "doc[favorite_parks.coordinates].each { coordinate -> sumOfDistances = coordinate.distanceInMiles(lat,lon) }; return 1 "

**Steps to reproduce**:
https://gist.github.com/alexlitvak13/8146cc5a8ac0defd5ffcf77116d375d4

Related commentary at the bottom of this ticket: https://github.com/elastic/elasticsearch/issues/16695

**Comment by clintongormley** [comment] 2016-09-15 11:29
Yes, this is a problem today.  https://github.com/elastic/elasticsearch/pull/19846 is aimed at improving this, but I think there will be more to follow. /cc @nknize

**Comment by nknize** [comment] 2017-02-01 21:44
I'm coming back to address these loose ends. I have some in-flight tasks/PRs open that aim to clean up this whole distance mess. Once those are merged this will be fixed.

**Comment by jdconrad** [comment] 2018-03-13 19:07
@nknize Is this something still worth addressing or has it already been fixed?

**Comment by imotov** [comment] 2018-12-11 14:30
@jdconrad it looks to me as a duplicate of #25796 which means it should be solved by #24946. Basically, the issues is again with inability to call distance functions on multiple GeoPoint values. So, I am going to close it in favor of #24946.

**Closed by imotov** 2018-12-11 14:30 UTC
Labels: :Analytics/Geo, :Core/Infra/Scripting, >enhancement

**Comment by jdconrad** [comment] 2018-12-11 17:13
@imotov Looks like it, thanks for closing.
