### ISSUE TITLE
ES failing with "marking and sending shard failed due to [failed recovery]"

### ISSUE THREAD

**Issue by ashwgupt** [elastic/elasticsearch#13569] opened 2015-09-15 08:27 UTC
We have a ES Cluster of 1.5.2 with 2 nodes in it. The cluster has been working smoothly for more than 4months until it went into some kind of Failed Shards errors and has stopped working.

Below is the huge number of errors reported by the cluster on both nodes, and stopping any sending (Logstash) or receiving application (Kibana here) from connecting to it.

Recently it also started causing Memory exhaustion as well on one of the nodes, when I had to shut down our ES completely.

Can anyone advise on the possible reason of the failure and any fix for it?

*************** Exception in logs **********************
[2015-09-15 00:02:52,692][WARN ][transport                ] [fil_middleware_clus01_node02] Received response for a request that has timed out, sent [30761ms] ago, timed out [760ms] ago, action [in
ternal:discovery/zen/fd/master_ping], node [[fil_middleware_clus01_node01][cYhvLzXwT92_0EsM6IEvDg][ukx06621.uk.fid-intl.com][inet[/10.60.172.71:9301]]{master=true}], id [893623]
[2015-09-15 00:02:52,726][WARN ][indices.cluster          ] [fil_middleware_clus01_node02] [[.mw_kibana02][0]] marking and sending shard failed due to [failed recovery]
org.elasticsearch.indices.recovery.RecoveryFailedException: [.mw_kibana02][0]: Recovery failed from [fil_middleware_clus01_node01][cYhvLzXwT92_0EsM6IEvDg][ukx06621.uk.fid-intl.com][inet[/10.60.172
.71:9301]]{master=true} into [fil_middleware_clus01_node02][DVKSAI0dTyWk3u_nkcaVoA][ukx06622.uk.fid-intl.com][inet[/10.60.172.72:9302]]{master=true}
        at org.elasticsearch.indices.recovery.RecoveryTarget.doRecovery(RecoveryTarget.java:274)
        at org.elasticsearch.indices.recovery.RecoveryTarget.access$700(RecoveryTarget.java:69)
        at org.elasticsearch.indices.recovery.RecoveryTarget$RecoveryRunner.doRun(RecoveryTarget.java:550)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.transport.RemoteTransportException: [fil_middleware_clus01_node01][inet[/10.60.172.71:9301]][internal:index/shard/recovery/start_recovery]
Caused by: org.elasticsearch.index.engine.RecoveryEngineException: [.mw_kibana02][0] Phase[1] Execution failed
        at org.elasticsearch.index.engine.InternalEngine.recover(InternalEngine.java:842)
        at org.elasticsearch.index.shard.IndexShard.recover(IndexShard.java:699)
        at org.elasticsearch.indices.recovery.RecoverySource.recover(RecoverySource.java:125)
        at org.elasticsearch.indices.recovery.RecoverySource.access$200(RecoverySource.java:49)
        at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:146)
        at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:132)
        at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:277)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.indices.recovery.RecoverFilesRecoveryException: [.mw_kibana02][0] Failed to transfer [0] files with total size of [0b]
        at org.elasticsearch.indices.recovery.RecoverySourceHandler.phase1(RecoverySourceHandler.java:413)
        at org.elasticsearch.index.engine.InternalEngine.recover(InternalEngine.java:837)
        ... 10 more
Caused by: java.io.IOException: directory '/elkmwpoc/ES/data/fil_middleware_cluster01/nodes/0/indices/.mw_kibana02/0/index' exists and is a directory, but cannot be listed: list() returned null
        at org.apache.lucene.store.FSDirectory.listAll(FSDirectory.java:226)
        at org.apache.lucene.store.FSDirectory.listAll(FSDirectory.java:237)
        at org.elasticsearch.index.store.fs.DefaultFsDirectoryService$1.listAll(DefaultFsDirectoryService.java:57)
        at org.apache.lucene.store.FilterDirectory.listAll(FilterDirectory.java:48)
        at org.apache.lucene.store.FilterDirectory.listAll(FilterDirectory.java:48)
        at org.apache.lucene.store.FilterDirectory.listAll(FilterDirectory.java:48)
        at org.elasticsearch.index.store.Store.failIfCorrupted(Store.java:532)
        at org.elasticsearch.index.store.Store.failIfCorrupted(Store.java:528)
        at org.elasticsearch.index.store.Store.getMetadata(Store.java:219)
        at org.elasticsearch.indices.recovery.RecoverySourceHandler.phase1(RecoverySourceHandler.java:159)
        ... 11 more
[2015-09-15 00:02:52,743][WARN ][indices.cluster          ] [fil_middleware_clus01_node02] [[logstash-ctm-stats-2015.04.29][4]] marking and sending shard failed due to [failed recovery]
org.elasticsearch.indices.recovery.RecoveryFailedException: [logstash-ctm-stats-2015.04.29][4]: Recovery failed from [fil_middleware_clus01_node01][cYhvLzXwT92_0EsM6IEvDg][ukx06621.uk.fid-intl.com
][inet[/10.60.172.71:9301]]{master=true} into [fil_middleware_clus01_node02][DVKSAI0dTyWk3u_nkcaVoA][ukx06622.uk.fid-intl.com][inet[/10.60.172.72:9302]]{master=true}
        at org.elasticsearch.indices.recovery.RecoveryTarget.doRecovery(RecoveryTarget.java:274)
        at org.elasticsearch.indices.recovery.RecoveryTarget.access$700(RecoveryTarget.java:69)
        at org.elasticsearch.indices.recovery.RecoveryTarget$RecoveryRunner.doRun(RecoveryTarget.java:550)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.index.engine.RecoveryEngineException: [logstash-ctm-stats-2015.04.29][4] Phase[1] Execution failed
        at org.elasticsearch.index.engine.InternalEngine.recover(InternalEngine.java:842)
        at org.elasticsearch.index.shard.IndexShard.recover(IndexShard.java:699)
        at org.elasticsearch.indices.recovery.RecoverySource.recover(RecoverySource.java:125)
        at org.elasticsearch.indices.recovery.RecoverySource.access$200(RecoverySource.java:49)
        at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:146)
        at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:132)
        at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:277)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.indices.recovery.RecoverFilesRecoveryException: [logstash-ctm-stats-2015.04.29][4] Failed to transfer [0] files with total size of [0b]
        at org.elasticsearch.indices.recovery.RecoverySourceHandler.phase1(RecoverySourceHandler.java:413)
        at org.elasticsearch.index.engine.InternalEngine.recover(InternalEngine.java:837)
        ... 10 more
Caused by: java.io.IOException: directory '/elkmwpoc/ES/data/fil_middleware_cluster01/nodes/0/indices/logstash-ctm-stats-2015.04.29/4/index' exists and is a directory, but cannot be listed: list()
 returned null
        at org.apache.lucene.store.FSDirectory.listAll(FSDirectory.java:226)
        at org.apache.lucene.store.FSDirectory.listAll(FSDirectory.java:237)
        at org.elasticsearch.index.store.fs.DefaultFsDirectoryService$1.listAll(DefaultFsDirectoryService.java:57)
        at org.apache.lucene.store.FilterDirectory.listAll(FilterDirectory.java:48)
        at org.apache.lucene.store.FilterDirectory.listAll(FilterDirectory.java:48)
        at org.apache.lucene.store.FilterDirectory.listAll(FilterDirectory.java:48)
        at org.elasticsearch.index.store.Store.failIfCorrupted(Store.java:532)
        at org.elasticsearch.index.store.Store.failIfCorrupted(Store.java:528)
        at org.elasticsearch.index.store.Store.getMetadata(Store.java:219)
        at org.elasticsearch.indices.recovery.RecoverySourceHandler.phase1(RecoverySourceHandler.java:159)
        ... 11 more

**Comment by clintongormley** [comment] 2015-09-19 12:17
What's happening with your data store?  eg:

    Caused by: java.io.IOException: directory '/elkmwpoc/ES/data/fil_middleware_cluster01/nodes/0/indices/.mw_kibana02/0/index' exists and is a directory, but cannot be listed: list() returned null
    Caused by: java.io.IOException: directory '/elkmwpoc/ES/data/fil_middleware_cluster01/nodes/0/indices/logstash-ctm-stats-2015.04.29/4/index' exists and is a directory, but cannot be listed: list()
returned null

**Comment by ashwgupt** [comment] 2015-09-21 10:35
I don't see any issue with it though.

The listing works perfectly fine when done on the server.

/elkmwpoc/ES/data/fil_middleware_cluster01/nodes/0/indices/logstash-ctm-stats-2015.04.29/4/index$ ls -ltr
total 24
-rw-rw-r--. 1 elkmwpoc elkmwpoc    0 Aug  3 13:51 write.lock
-rw-rw-r--. 1 elkmwpoc elkmwpoc 5539 Aug  3 13:51 _0.cfs
-rw-rw-r--. 1 elkmwpoc elkmwpoc  308 Aug  3 13:51 _0.cfe
-rw-rw-r--. 1 elkmwpoc elkmwpoc  257 Aug  3 13:51 _0.si
-rw-rw-r--. 1 elkmwpoc elkmwpoc  128 Aug  3 14:21 segments_2
-rw-rw-r--. 1 elkmwpoc elkmwpoc   36 Aug  3 14:21 segments.gen

/elkmwpoc/ES/data/fil_middleware_cluster01/nodes/0/indices/.mw_kibana02/0/index$ ls -ltr
total 172
-rw-rw-r--. 1 elkmwpoc elkmwpoc    0 Jun  1 09:58 write.lock
-rw-rw-r--. 1 elkmwpoc elkmwpoc   64 Jul  7 13:21 _n.fdx
-rw-rw-r--. 1 elkmwpoc elkmwpoc 3848 Jul  7 13:21 _n.fdt
-rw-rw-r--. 1 elkmwpoc elkmwpoc  705 Jul  7 13:21 _n_Lucene41_0.tip
-rw-rw-r--. 1 elkmwpoc elkmwpoc 8442 Jul  7 13:21 _n_Lucene41_0.tim
-rw-rw-r--. 1 elkmwpoc elkmwpoc 3623 Jul  7 13:21 _n_Lucene41_0.pos
-rw-rw-r--. 1 elkmwpoc elkmwpoc  961 Jul  7 13:21 _n_Lucene41_0.doc
-rw-rw-r--. 1 elkmwpoc elkmwpoc   90 Jul  7 13:21 _n_Lucene410_0.dvm
-rw-rw-r--. 1 elkmwpoc elkmwpoc   52 Jul  7 13:21 _n_Lucene410_0.dvd
-rw-rw-r--. 1 elkmwpoc elkmwpoc  426 Jul  7 13:21 _n.si
-rw-rw-r--. 1 elkmwpoc elkmwpoc  181 Jul  7 13:21 _n.nvm
-rw-rw-r--. 1 elkmwpoc elkmwpoc  582 Jul  7 ...........

**Comment by ashwgupt** [comment] 2015-09-21 10:36
To me it looks like ES is failing for some of it's internal fault and unable to deal with it, as the whole of cluster has failed at once.

**Comment by jasontedor** [comment] 2015-09-21 10:48
A possible cause of the `IOException` that @clintongormley drew attention to is running into system limits on the number of open file descriptors. Could you try checking your [file descriptor configuration](https://www.elastic.co/guide/en/elasticsearch/reference/1.4/setup-configuration.html#file-descriptors) and increase it appropriately based on your specific system.

**Comment by clintongormley** [comment] 2016-01-28 17:30
No further feedback. Closing

**Closed by clintongormley** 2016-01-28 17:30 UTC
Labels: feedback_needed
