### ISSUE TITLE
Gradle 3.5 doesn't seem to work

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#24072] opened 2017-04-12 17:11 UTC
I tried out gradle 3.5 today while debugging some windows issues. It blows up on progress logger stuff. Here is an example of it running in CI:
http://build-us-00.elastic.co/job/ES%20Server%205.x%20on%20Windows%202012%20R2/15/consoleFull

**Comment by rjernst** [comment] 2017-04-19 07:33
The final release of gradle 3.5 works for me on master. I'm closing this, but please reopen if you can reproduce.

**Closed by rjernst** 2017-04-19 07:33 UTC
Labels: build
