### ISSUE TITLE
Wrong search hit counts in SearchQueryIT#testCommonTermsQuery

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#39659] opened 2019-03-04 15:23 UTC
This seems to have started failing recently.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+internalClusterTest/1710/console

Cannot reproduce on 7.x so far:
```
./gradlew :server:integTest \
  -Dtests.seed=5B4E5FE50A607D7B \
  -Dtests.class=org.elasticsearch.search.query.SearchQueryIT \
  -Dtests.method="testCommonTermsQuery" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-EC \
  -Dtests.timezone=Europe/Prague \
  -Dcompiler.java=11 \
  -Druntime.java=8
```
```
java.lang.AssertionError: Count is 2 hits but 3 was expected.  Total shards: 1 Successful shards: 1 & 0 shard failures:
	at __randomizedtesting.SeedInfo.seed([5B4E5FE50A607D7B:6081909C50FF6C37]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertHitCount(ElasticsearchAssertions.java:256)
	at org.elasticsearch.search.query.SearchQueryIT.testCommonTermsQuery(SearchQueryIT.java:300)
```

Other similar looking issues all in the last few weeks:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+internalClusterTest/1183/console (7.x branch, 2019-02-24)
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+internalClusterTest/1169/console (7.0 branch, 2019-02-23)
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+internalClusterTest/660/console (7.0 branch, 2019-02-16)

I couldn't find any earlier failures looking like this particular one before Feb-16.

**Comment by cbuescher** [comment] 2019-04-04 15:29
Just checked the last occurance of this particular test failing was March 4th, it seems to have failes earlier in February but not dince then.
I think we should keep it open another few weeks but can close then if we don't see this exact failure again.

**Comment by hendrikmuhs** [comment] 2019-04-26 13:03
oops, it did it again:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+intake/1213/console

**Comment by benwtrent** [comment] 2019-04-26 13:06
Failed again: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+intake/1213/console

Reproduce line
```
./gradlew :server:integTest --tests "org.elasticsearch.search.query.SearchQueryIT.testCommonTermsQuery" -Dtests.seed=AA785C1B72970241 -Dtests.security.manager=true -Dtests.locale=fr-BE -Dtests.timezone=Asia/Dhaka -Dcompiler.java=12 -Druntime.java=8
```
Does not reproduce locally

StackTrace:
```
java.lang.AssertionError: Count is 2 hits but 3 was expected.  Total shards: 1 Successful shards: 1 & 0 shard failures:
	at __randomizedtesting.SeedInfo.seed([AA785C1B72970241:91B793622808130D]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertHitCount(ElasticsearchAssertions.java:256)
	at org.elasticsearch.search.query.SearchQueryIT.testCommonTermsQuery(SearchQueryIT.java:287)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jimczi** [comment] 2020-03-24 22:10
The common terms query has been removed in 8.0 and the tests did not fail in 7.x. since almost one year, hence closing.

**Closed by jimczi** 2020-03-24 22:10 UTC
Labels: :Search/Search, >test-failure, v7.7.0
