### ISSUE TITLE
restoring system data stream causes cluster to throw 403s

### ISSUE THREAD

**Issue by LucaWintergerst** [elastic/elasticsearch#75802] opened 2021-07-28 17:21 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 7.14 BC4 
    "build_hash" : "6ef8c9df9a5605291c84fd3b5b0e1c7e16883a87",
    "build_date" : "2021-07-21T23:34:08.637646613Z",

**Plugins installed**: [] the source cluster had the mapper_size plugin installed, the destination cluster did not. I don't believe that this is relevant since a restore would usually fail with an exception if that's the case, but maybe there's an edge case for data streams.

**JVM version** (`java -version`): Elastic Cloud

**OS version** (`uname -a` if on a Unix-like system): Elastic Cloud

**Description of the problem including expected versus actual behavior**:

After restoring a snapshot, the cluster gets locked down and most APIs are not accessible anymore

As an example a `GET _cat/indices`
```{
  "error" : {
    "root_cause" : [
      {
        "type" : "security_exception",
        "reason" : "action [indices:monitor/settings/get] is unauthorized for user [3612216885] with roles [superuser], this action is granted by the index privileges [monitor,view_index_metadata,manage,all]"
      }
    ],
    "type" : "security_exception",
    "reason" : "action [indices:monitor/settings/get] is unauthorized for user [3612216885] with roles [superuser], this action is granted by the index privileges [monitor,view_index_metadata,manage,all]",
    "caused_by" : {
      "type" : "illegal_state_exception",
      "reason" : "system index is part of a data stream that is not a system data stream"
    }
  },
  "status" : 403
}
```

**Steps to reproduce**:
I will share the steps to reproduce internally in slack as this snapshot bucket can not be shared publicly 

**Provide logs (if relevant)**:

**Comment by gwbrown** [comment] 2021-07-28 22:36
There are a few things we've found about this issue:
1. This is caused by the `system` flag on system data streams not surviving a round-trip through snapshot/restore. The problem is on the restore side, not the snapshot side, so once a version of Elasticsearch without this bug is in use, the snapshot can be restored as expected.
2. The errors from most APIs only occurs when Security is enabled, although the underlying issue of point 1 remains and is likely to cause errors in a narrower scope.
3. If this occurs, the offending data stream can be removed using this command:
```
curl --user elastic:your_password_here -XDELETE -H 'X-elastic-product-origin: kibana' localhost:9200/_data_stream/.fleet-actions-results
```
This will, of course, result in the loss of historical results of Fleet actions however.

**Comment by gwbrown** [comment] 2021-07-29 20:15
https://github.com/elastic/elasticsearch/issues/75802 has been merged & backported, fixing this issue. Therefore, I'm going to close this.

**Closed by gwbrown** 2021-07-29 20:15 UTC
Labels: :Core/Infra/Core, >bug, Team:Core/Infra, blocker
