### ISSUE TITLE
Make 0 as invalid value for `min_children` in `has_child` query

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#32949] opened 2018-08-17 14:22 UTC
0 for `min_children` option in `has_child` query doesn't make sense, because:
1. It is ambiguous. Does it mean to match only parents that either have children matching the specified constraints or no have no children at all.
2. It currently behaves as a value of `1`, that is if there is no at least 1 child matching a specified constrained, a parent document is not returned.

For these reasons, we should make 0 value as invalid value.

Related #21224

**Comment by kevinaud** [comment] 2018-08-18 19:38
I'm interested in working on this

**Comment by rajeshggwp** [comment] 2018-10-06 05:56
Is anyone still working on this? If not can I pick this?

**Comment by mayya-sharipova** [comment] 2018-10-17 13:55
@rajeshggwp  Sorry, we do have an open PR for this: https://github.com/elastic/elasticsearch/pull/33073

**Comment by shoaib4330** [comment] 2019-02-06 07:57
Is someone working on it? The issue is still open, I plan on working on int.

**Comment by mayya-sharipova** [comment] 2019-02-07 16:47
@shoaib4330 Sorry, we have a stalled PR opened for it. I think we will just finish that PR.

**Comment by mayya-sharipova** [comment] 2019-02-12 19:46
@shoaib4330 We have closed a stalled PR #33073, because of inactivity!  If you still would like to work on this issue, please go ahead.

**Comment by shoaib4330** [comment] 2019-02-13 05:45
Sure. I'm on it then.

**Comment by kutty-kumar** [comment] 2019-03-15 09:30
@shoaib4330 have u started working on this, if not then i will pick it up.

**Comment by codebird** [comment] 2019-04-18 13:55
@mayya-sharipova I am new here, can I take on this issue?

**Comment by cbuescher** [comment] 2019-04-25 16:14
Closed by https://github.com/elastic/elasticsearch/pull/41347

**Closed** 2019-04-25 19:26 UTC
Labels: :Search/Search, >enhancement, good first issue
