### ISSUE TITLE
[feature request]make in-memory segment mutable, therefor make ES real time

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#22290] opened 2016-12-21 02:44 UTC
sorry to bother, it is more or less a lucene feature.
**Describe the feature**:
make in-memory segment mutable and can be insert/update/delete/search real time. when it is fsync to disk tranform it into immutable segment just like cassandra acts.

**Comment by jpountz** [comment] 2016-12-21 08:15
Duplicate of https://issues.apache.org/jira/browse/LUCENE-2312.

Note that it is not as easy as it sounds since Lucene heavily relies on the fact that things are sorted, while the terms dictionary and points are typically not sorted yet when they are in the IW ram buffer.

**Closed by jpountz** 2016-12-21 08:15 UTC

**Comment by makeyang** [comment] 2016-12-21 10:15
@jpountz  thanks very much. this is exactly what I need.

**Comment by jpountz** [comment] 2016-12-21 16:17
In both cases of Lucene and Elasticsearch, the vast majority of things we are working on are already in Github, see for instance https://github.com/elastic/elasticsearch/issues/10708 if you are interested about one big thing we are working on.
