### ISSUE TITLE
Make index.routing.allocation.total_shards_per_node resilient to node drops

### ISSUE THREAD

**Issue by Bukhtawar** [elastic/elasticsearch#43058] opened 2019-06-10 17:22 UTC
**Problem Description**
With the setting enabled on the index if there are node failures this setting can cause primary shards to go unassigned and cluster to go RED. 

**Proposal**
Provide a knob to honor this setting as a best case when all primary shards are assigned so that there is no total data loss.

**Comment by Bukhtawar** [comment] 2019-06-10 18:00
Essentially a knob to control
1. unassigned_primaries
2. all_unassigned

**Comment by ywelsch** [comment] 2019-06-11 12:11
primary shards with an existing store are already force-allocated, independently of the `total_shards_per_node` setting.

> With the setting enabled on the index if there are node failures this setting can cause primary shards to go unassigned and cluster to go RED

This is simply not true. Please provide an actual example before making such claims.

**Comment by Bukhtawar** [comment] 2019-06-11 15:53
@ywelsch you are right a single node failure can't cause RED but a second node failure will, if all the nodes had a shard-copy of an index and I take back the unassigned primary shard part(apologies for a false alarm). First failure will cause the cluster to go YELLOW as the limit would be breached on other nodes(which otherwise would have allocated a replica on the remaining node). The second failure can cause the cluster to go RED. Do you think it makes sense to expose a knob to honor this setting only if all shards are assigned and the cluster is GREEN essentially choosing availability over performance(maybe).

**Comment by DaveCTurner** [comment] 2019-06-19 11:50
The resilience of an index to arbitrary node failures is a function of its `number_of_replicas` setting. If you need your cluster to be resilient to any two nodes failing then you must set `number_of_replicas` to at least 2. You can also use allocation awareness to make the cluster more resilient to correlated failures of multiple nodes.

It's important to respect the `total_shards_per_node` setting as a hard limit, because exceeding this setting may cause the node to run out of resources and fail, resulting in other nodes exceeding this setting and failing in turn.

That said, Elasticsearch's handling of hard allocation limits is known to be imperfect, and there are already open issues to do with it (e.g. #12273, #17213) so I think this can be closed as a duplicate of those.

**Closed by DaveCTurner** 2019-06-19 11:50 UTC
Labels: :Distributed/Allocation, feedback_needed
