### ISSUE TITLE
ES 2.0.0 - Filter Query returns empty

### ISSUE THREAD

**Issue by iyerdude** [elastic/elasticsearch#16119] opened 2016-01-20 10:59 UTC
Hello,
I am facing issues while using filter to query using ES 2.0.0

I have an index named user_details with 2 values as below,
{
"_index": "user_details",
"_type": "user",
"_id": "2",
"_score": 1,
"_source": {
"name": "Daniel",
"age": 50
}
}
,
{
"_index": "user_details",
"_type": "user",
"_id": "1",
"_score": 1,
"_source": {
"name": "James",
"age": 30
}
}

Now when I run my filter query as below, it returns empty.
 curl -XGET http://localhost:9200/user_details/_search -d '{"query":{"bool":{"filter":{"term":{"name":"James"}}}}}'

I have also tried adding a "must" clause. that doesn't run at all.
curl -XGET http://localhost:9200/user_details/_search -d '{"query":{"bool":{"must":{"age":30},"filter":{"term":{"name":"James"}}}}}'

Any help to fix this issue is appreciated.

**Comment by danielmitterdorfer** [comment] 2016-01-20 13:15
Please note that we have a separate [discussion forum](http://discuss.elastic.co/) for these questions. In the future, please ask your questions there. The community over there is very helpful.

As a hint though, your problem is that the `name` field is analyzed but the filter looks for the exact term. You probably want to use a match query instead. This works perfectly fine:

```
GET _search
{
   "query": {
      "bool": {
         "must": {
            "match": {
               "name": "James"
            }
         },
         "filter": {
            "term": {
               "age": 30
            }
         }
      }
   }
}
```

You can read more about [match queries](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/query-dsl-match-query.html) and [term queries](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/query-dsl-term-query.html) in the docs.

Closing as this is not a bug.

**Closed by danielmitterdorfer** 2016-01-20 13:15 UTC

**Comment by iyerdude** [comment] 2016-01-20 13:35
@danielmitterdorfer Thanks for helping with this. 

Sorry, wasn't aware about the discussion forum. Will use the forum instead for further questions.

**Comment by danielmitterdorfer** [comment] 2016-01-20 13:37
You're welcome; glad I could help.
