### ISSUE TITLE
Add G1GC to JVMCheck and bail on G1GC usage

### ISSUE THREAD

**Issue by kimchy** [elastic/elasticsearch#10740] opened 2015-04-22 23:22 UTC
We know based on tests that G1GC can cause corruptions on the index, though it seems like the JVM group is taking actions into fixing this issue, and some promising changes have been made to Java 8u40, its still an issue.

I suggest we bail ES from starting if G1GC is used, people can always override the JVM check flag if they are feeling adventurous. If we do this change, we need to make sure we disable this check when we test on G1GC in our testing infra, since we want to know when this is fixed eventually.

See https://issues.apache.org/jira/browse/LUCENE-5168 for example.

**Comment by jpountz** [comment] 2015-04-24 09:44
Maybe another flag we should consider banning is `-XX:+AggressiveOpts`?

**Comment by clintongormley** [comment] 2015-04-26 16:37
@rmuir would you be keen to do this?

**Comment by rmuir** [comment] 2015-04-27 09:21
I think we need to do something, just not sure what the exact behavior should be. Yes we can look for the flag explicitly passed on the command line, but still its different than the current version-based checks because it will impact jvms to be released in the future...

**Comment by kimchy** [comment] 2015-04-27 09:24
yea, thats the tricky part, where if G1GC suddenly becomes good in 8u60, there is no way to undo this change. I don't have a good idea around how to solve this, we can decide to pin G1GC to last know Java versions, i.e. all the ones up to 8u40, but then the bad part is that if 8u60 fails and we don't fail, it might confuse users to think it fails.

Another option: fail if on 8u40 and before, and info log that check the docs for later versions? This does mean we need to keep on maintaining this check as new JVM versions gets released.

**Comment by rmuir** [comment] 2015-04-27 09:34
Even things as simple as range based version checks are hairy, if its based on anything other than java major version. Thats because, insanely its always 1.7.0 or 1.8.0 officially. Doing any kind of parsing here on these strings is a place i would rather not go. If some internal format changes we could easily land in a unhappy place...

**Comment by kimchy** [comment] 2015-04-27 10:36
@rmuir yea, I hear you, minor versions are a mess to parse. Best idea I can come up with is to list the known version in 7 and 8, and mark G1GC as problematic on them, and thats it? It won't help for future versions that might be a problem, but at least its progress in helping our users?

@jpountz yea, I think regardless of a version, certain JVM flags, like AggressiveOpts should probably cause us to bail as well

**Comment by danielmitterdorfer** [comment] 2015-05-02 11:31
Just as an FYI and in case you are not aware yet: G1 seems to become the default GC in JDK 9: http://openjdk.java.net/jeps/248

**Comment by rtkmhart** [comment] 2015-05-05 19:34
As a customer happily running G1GC (yes I'm aware of the risks) I'd be quite unhappy with this.

Reason for switching: we'd regularly see a JVM with CMS GC go from running happily at 75% heap with the normal sawtooth pattern for days, and then suddenly hit 100% and full GC within minutes for inexplicable reasons which we cannot replicate on demand, and the only recovery is to restart it. Switching to G1GC made this go away. We recently switched back after strong recommendations from support and immediately saw the same GC issue again. So we're going back to G1GC shortly. 

I understand the risks, and know what the implications are. I'd be happy with a strongly worded warning. And open to further discussion of course.

**Comment by jprante** [comment] 2015-05-18 15:38
Switching to G1GC and Java 8 made a lot of my ES JVM scaling issues caused by GC pausing go away. I do not have broken index data for years. I am aware there are bugs visible in ES testing, while it is hard for me to reproduce them in my environment.

So I would suggest a less rigorous and more risk mitigation focused strategy instead of simply bailing out.

For example

- discouraging Java 7
- enabling Java 9 support for ES
- embedding direct links in warning messages to failed ES tests where involved JVM versions and diagnostics can be revealed so risk mitigation is possible
- referencing OpenJDK issues at https://bugs.openjdk.java.net/browse/JDK/component/10304#selectedTab=com.atlassian.jira.plugin.system.project%3Acomponent-issues-panel so ES users can get advise from OpenJDK community how to fix / work around issues

**Comment by rmuir** [comment] 2015-05-19 03:03
> Switching to G1GC and Java 8 made a lot of my ES JVM scaling issues caused by GC pausing go away. I do not have broken index data for years. I am aware there are bugs visible in ES testing, while it is hard for me to reproduce them in my environment.

It is dangerous to look at things this way, for example a lot of people could not reproduce the superword corruption bug (JDK-8024830), and that is because it required sandy bridge to easily reproduce.

> discouraging Java 7

If I were to add any check here (as discussed above), I would only add it with a list of released hotspot versions < java 8u40.

> enabling Java 9 support for ES

I don't know what this means: tests in master pass with the latest EA snapshot of java 9, at least if you run them once. java 9 likely has some bugs, since its not released. There is nothing more we can do about this situation, its as good as it gets.

> embedding direct links in warning messages to failed ES tests where involved JVM versions and diagnostics can be revealed so risk mitigation is possible
> referencing OpenJDK issues at https://bugs.openjdk.java.net/browse/JDK/component/10304#selectedTab=com.atlassian.jira.plugin.system.project%3Acomponent-issues-panel so ES users can get advise from OpenJDK community how to fix / work around issues

This seems to imply we would waste time digging into/fixing bugs around G1GC: nobody has the time for that.

**Comment by clintongormley** [comment] 2016-01-17 17:48
@rmuir what's your take on this, 8 months later?  Should we do anything here?

**Comment by jasontedor** [comment] 2016-02-23 00:53
Closed by #16737

**Closed by jasontedor** 2016-02-23 00:53 UTC
Labels: :Packaging, discuss, resiliency, v2.3.0
