### ISSUE TITLE
[CI] ProcessWorkerExecutorServiceTests testAutodetectWorkerExecutorServiceDoesNotSwallowErrors failing

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#101144] opened 2023-10-19 14:20 UTC
**Build scan:**
https://gradle-enterprise.elastic.co/s/ud4ggnomaa7p6/tests/:x-pack:plugin:ml:test/org.elasticsearch.xpack.ml.job.process.ProcessWorkerExecutorServiceTests/testAutodetectWorkerExecutorServiceDoesNotSwallowErrors
**Reproduction line:**
```
./gradlew ':x-pack:plugin:ml:test' --tests "org.elasticsearch.xpack.ml.job.process.ProcessWorkerExecutorServiceTests.testAutodetectWorkerExecutorServiceDoesNotSwallowErrors" -Dtests.seed=FCF6267296BD3EED -Dtests.locale=pl -Dtests.timezone=CST6CDT -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ml.job.process.ProcessWorkerExecutorServiceTests&tests.test=testAutodetectWorkerExecutorServiceDoesNotSwallowErrors
**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([FCF6267296BD3EED]:0)

```

**Comment by droberts195** [comment] 2023-10-19 16:19
@jonathan-buttner I think this is caused by your change in #100925. This test locks up if the random boolean chooses the `submit` path rather than `execute`, so 50% chance of failure, which is why it managed to pass CI to get merged: https://github.com/elastic/elasticsearch/blob/1ca66bde9109bcc716a692be4a3531c0418299e8/x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/job/process/ProcessWorkerExecutorServiceTests.java#L132

I was going to suggest changing `ProcessWorkerExecutorService` to throw `UnsupportedOperationException` in its `submit` method if this is no longer supported, but I just seen we're using that in production code, for example here: https://github.com/elastic/elasticsearch/blob/b7eafce32cb1e7dfdcb259aab89b886ff93a1c66/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/AutodetectProcessManager.java#L795

I think the problem with #100925 is that it _will_ now eat `Error` exceptions, like `VirtualMachineError`.

**Closed** 2023-10-19 17:46 UTC
Labels: >test-failure, :ml, Team:ML, low-risk
