### ISSUE TITLE
[CI] elasticsearch # 8.9 - windows compatibility tests failing

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#97944] opened 2023-07-25 23:25 UTC
### CI Link

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+8.9+multijob+platform-support-windows/GRADLE_TASK=checkPart1,os=windows-2012-r2/67/

### Repro line

N/A

### Does it reproduce?

Didn't try

### Applicable branches

8.9

### Failure excerpt

It seems to be some infrastructure failure after [bumping version post 8.9.0](3ed4a315881f56047b98067788be7384514f02b0).

The error message is
```
09:01:08 Exception in thread "main" clojure.lang.ExceptionInfo: throw+: {:res Parse error at line 6, column 8:
09:01:08 gpgsig -----BEGIN SSH SIGNATURE-----
09:01:08        ^
09:01:08 Expected:
09:01:08 "-----BEGIN PGP SIGNATURE-----"
09:01:08 , :commit "commit 3ed4a315881f56047b98067788be7384514f02b0\ntree e3c773e5641ac6505801ae7ffae0cd730a7af776\nparent 02410f9e1c7367509a328828ce1d1698db671e82\nauthor Ryan Ernst <ryan@xxxx> 1690309856 -0700\ncommitter Ryan Ernst 
```

**Comment by ywangd** [comment] 2023-08-22 04:40
Failed on 8.10 as well https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+8.10+multijob+packaging-tests-windows/os=windows-2012-r2/18/

**Comment by mark-vieira** [comment] 2023-08-22 21:34
Closing as a duplicate of https://github.com/elastic/elasticsearch/issues/97998

**Closed by mark-vieira** 2023-08-22 21:34 UTC
Labels: :Delivery/Build, >test-failure, Team:Delivery
