### ISSUE TITLE
[CI] Build logs archive is corrupted

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#94984] opened 2023-04-03 11:27 UTC
### CI Link

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+main+multijob+platform-support-unix/os=amazon-2022&&immutable/766/console

### Repro line

REPRODUCE WITH: ./gradlew ':x-pack:plugin:security:qa:multi-cluster:javaRestTest' --tests "org.elasticsearch.xpack.remotecluster.RemoteClusterSecurityWithSameModelRemotesRestIT" \   -Dtests.seed=197B7DFCAA5AD480 \   -Dtests.locale=en-US \   -Dtests.timezone=UTC \   -Druntime.java=20

### Does it reproduce?

No

### Applicable branches

main

### Failure excerpt

```
11:40:02 Failed to archive additional logs
11:40:02 : Problem creating TAR: request to write '6126' bytes exceeds size in header of '407199' bytes for entry 'x-pack/plugin/eql/qa/multi-cluster-with-security/build/testclusters/remote-cluster-1/logs/es.out'
11:40:02 	at org.apache.tools.ant.taskdefs.Tar.execute(Tar.java:348)
11:40:02 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
11:40:02 	at jdk.internal.reflect.GeneratedMethodAccessor1255.invoke(Unknown Source)
11:40:02 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:40:02 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
11:40:02 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
11:40:02 	at groovy.ant.AntBuilder.performTask(AntBuilder.java:343)
11:40:02 	at groovy.ant.AntBuilder.nodeCompleted(AntBuilder.java:282)
11:40:02 	at org.gradle.api.internal.project.ant.BasicAntBuilder.nodeCompleted(BasicAntBuilder.java:90)
11:40:02 	at groovy.util.BuilderSupport.doInvokeMethod(BuilderSupport.java:160)
11:40:02 	at groovy.ant.AntBuilder.doInvokeMethod(AntBuilder.java:216)
11:40:02 	at org.gradle.api.internal.project.ant.BasicAntBuilder.doInvokeMethod(BasicAntBuilder.java:117)
11:40:02 	at groovy.util.BuilderSupport.invokeMethod(BuilderSupport.java:74)
11:40:02 	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:44)
11:40:02 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
11:40:02 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
11:40:02 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148)
11:40:02 	at precompiled_ElasticsearchBuildComplete$_run_closure1.doCall(precompiled_ElasticsearchBuildComplete:24)
11:40:02 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:40:02 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
11:40:02 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:40:02 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
11:40:02 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
11:40:02 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
11:40:02 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
11:40:02 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
11:40:02 	at groovy.lang.Closure.call(Closure.java:412)
11:40:02 	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:41)
11:40:02 	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
11:40:02 	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:43)
11:40:02 	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:257)
11:40:02 	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:164)
11:40:02 	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:83)
11:40:02 	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:69)
11:40:02 	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:363)
11:40:02 	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:261)
11:40:02 	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:148)
11:40:02 	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
11:40:02 	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
11:40:02 	at jdk.proxy1/jdk.proxy1.$Proxy29.buildFinished(Unknown Source)
11:40:02 	at org.gradle.internal.build.DefaultBuildLifecycleController.lambda$finishBuild$8(DefaultBuildLifecycleController.java:202)
11:40:02 	at org.gradle.internal.model.StateTransitionController.lambda$finish$12(StateTransitionController.java:238)
11:40:02 	at org.gradle.internal.work.DefaultSynchronizer.withLock(DefaultSynchronizer.java:44)
11:40:02 	at org.gradle.internal.model.StateTransitionController.finish(StateTransitionController.java:229)
11:40:02 	at org.gradle.internal.build.DefaultBuildLifecycleController.finishBuild(DefaultBuildLifecycleController.java:190)
11:40:02 	at org.gradle.internal.buildtree.DefaultBuildTreeFinishExecutor.finishBuildTree(DefaultBuildTreeFinishExecutor.java:55)
11:40:02 	at org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.lambda$runBuild$4(DefaultBuildTreeLifecycleController.java:103)
11:40:02 	at org.gradle.internal.model.StateTransitionController.lambda$transition$6(StateTransitionController.java:177)
11:40:02 	at org.gradle.internal.model.StateTransitionController.doTransition(StateTransitionController.java:258)
11:40:02 	at org.gradle.internal.model.StateTransitionController.lambda$transition$7(StateTransitionController.java:177)
11:40:02 	at org.gradle.internal.work.DefaultSynchronizer.withLock(DefaultSynchronizer.java:44)
11:40:02 	at org.gradle.internal.model.StateTransitionController.transition(StateTransitionController.java:177)
11:40:02 	at org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.runBuild(DefaultBuildTreeLifecycleController.java:95)
11:40:02 	at org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.scheduleAndRunTasks(DefaultBuildTreeLifecycleController.java:68)
11:40:02 	at org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.scheduleAndRunTasks(DefaultBuildTreeLifecycleController.java:63)
11:40:02 	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:31)
11:40:02 	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
11:40:02 	at org.gradle.internal.buildtree.ProblemReportingBuildActionRunner.run(ProblemReportingBuildActionRunner.java:49)
11:40:02 	at org.gradle.launcher.exec.BuildOutcomeReportingBuildActionRunner.run(BuildOutcomeReportingBuildActionRunner.java:65)
11:40:02 	at org.gradle.tooling.internal.provider.FileSystemWatchingBuildActionRunner.run(FileSystemWatchingBuildActionRunner.java:140)
11:40:02 	at org.gradle.launcher.exec.BuildCompletionNotifyingBuildActionRunner.run(BuildCompletionNotifyingBuildActionRunner.java:41)
11:40:02 	at org.gradle.launcher.exec.RootBuildLifecycleBuildActionExecutor.lambda$execute$0(RootBuildLifecycleBuildActionExecutor.java:40)
11:40:02 	at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:122)
11:40:02 	at org.gradle.launcher.exec.RootBuildLifecycleBuildActionExecutor.execute(RootBuildLifecycleBuildActionExecutor.java:40)
11:40:02 	at org.gradle.internal.buildtree.DefaultBuildTreeContext.execute(DefaultBuildTreeContext.java:40)
11:40:02 	at org.gradle.launcher.exec.BuildTreeLifecycleBuildActionExecutor.lambda$execute$0(BuildTreeLifecycleBuildActionExecutor.java:65)
11:40:02 	at org.gradle.internal.buildtree.BuildTreeState.run(BuildTreeState.java:53)
11:40:02 	at org.gradle.launcher.exec.BuildTreeLifecycleBuildActionExecutor.execute(BuildTreeLifecycleBuildActionExecutor.java:65)
11:40:02 	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor$3.call(RunAsBuildOperationBuildActionExecutor.java:61)
11:40:02 	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor$3.call(RunAsBuildOperationBuildActionExecutor.java:57)
11:40:02 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
11:40:02 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
11:40:02 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
11:40:02 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
11:40:02 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
11:40:02 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
11:40:02 	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
11:40:02 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
11:40:02 	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor.execute(RunAsBuildOperationBuildActionExecutor.java:57)
11:40:02 	at org.gradle.launcher.exec.RunAsWorkerThreadBuildActionExecutor.lambda$execute$0(RunAsWorkerThreadBuildActionExecutor.java:36)
11:40:02 	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:249)
11:40:02 	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:109)
11:40:02 	at org.gradle.launcher.exec.RunAsWorkerThreadBuildActionExecutor.execute(RunAsWorkerThreadBuildActionExecutor.java:36)
11:40:02 	at org.gradle.tooling.internal.provider.continuous.ContinuousBuildActionExecutor.execute(ContinuousBuildActionExecutor.java:110)
11:40:02 	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecutor.execute(SubscribableBuildActionExecutor.java:64)
11:40:02 	at org.gradle.internal.session.DefaultBuildSessionContext.execute(DefaultBuildSessionContext.java:46)
11:40:02 	at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter$ActionImpl.apply(BuildSessionLifecycleBuildActionExecuter.java:100)
11:40:02 	at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter$ActionImpl.apply(BuildSessionLifecycleBuildActionExecuter.java:88)
11:40:02 	at org.gradle.internal.session.BuildSessionState.run(BuildSessionState.java:69)
11:40:02 	at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter.execute(BuildSessionLifecycleBuildActionExecuter.java:62)
11:40:02 	at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter.execute(BuildSessionLifecycleBuildActionExecuter.java:41)
11:40:02 	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:63)
11:40:02 	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
11:40:02 	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:50)
11:40:02 	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:38)
11:40:02 	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:47)
11:40:02 	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:31)
11:40:02 	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:65)
11:40:02 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
11:40:02 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
11:40:02 	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:39)
11:40:02 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
11:40:02 	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:29)
11:40:02 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
11:40:02 	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:35)
11:40:02 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
11:40:02 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:78)
11:40:02 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:75)
11:40:02 	at org.gradle.util.internal.Swapper.swap(Swapper.java:38)
11:40:02 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:75)
11:40:02 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
11:40:02 	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:64)
11:40:02 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
11:40:02 	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
11:40:02 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
11:40:02 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
11:40:02 	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:84)
11:40:02 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
11:40:02 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
11:40:02 	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
11:40:02 	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
11:40:02 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
11:40:02 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
11:40:02 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
11:40:02 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
11:40:02 	at java.base/java.lang.Thread.run(Thread.java:833)
11:40:02 Caused by: java.io.IOException: request to write '6126' bytes exceeds size in header of '407199' bytes for entry 'x-pack/plugin/eql/qa/multi-cluster-with-security/build/testclusters/remote-cluster-1/logs/es.out'
11:40:02 	at org.apache.tools.tar.TarOutputStream.write(TarOutputStream.java:414)
11:40:02 	at org.apache.tools.ant.taskdefs.Tar.tarResource(Tar.java:512)
11:40:02 	at org.apache.tools.ant.taskdefs.Tar.tarFile(Tar.java:378)
11:40:02 	at org.apache.tools.ant.taskdefs.Tar.tar(Tar.java:695)
11:40:02 	at org.apache.tools.ant.taskdefs.Tar.execute(Tar.java:344)
11:40:02 	... 125 more
11:40:02 	Suppressed: java.io.IOException: This archives contains unclosed entries.
11:40:02 		at org.apache.tools.tar.TarOutputStream.finish(TarOutputStream.java:234)
11:40:02 		at org.apache.tools.tar.TarOutputStream.close(TarOutputStream.java:251)
11:40:02 		at org.apache.tools.ant.taskdefs.Tar.execute(Tar.java:322)
11:40:02 		... 125 more
11:40:02 
11:40:02 FAILURE: Build failed with an exception.
```

**Comment by n1v0lg** [comment] 2023-04-03 12:12
The relevant failure stacktrace is:

```
org.elasticsearch.xpack.remotecluster.RemoteClusterSecurityWithSameModelRemotesRestIT > classMethod FAILED
    java.lang.RuntimeException: An error occurred orchestrating test cluster.
        at __randomizedtesting.SeedInfo.seed([197B7DFCAA5AD480]:0)
        at org.elasticsearch.test.cluster.local.LocalClusterHandle.execute(LocalClusterHandle.java:236)
        at org.elasticsearch.test.cluster.local.LocalClusterHandle.execute(LocalClusterHandle.java:241)
        at org.elasticsearch.test.cluster.local.LocalClusterHandle.start(LocalClusterHandle.java:68)
        at org.elasticsearch.test.cluster.local.LocalElasticsearchCluster$1.evaluate(LocalElasticsearchCluster.java:38)
        at org.elasticsearch.test.cluster.local.LocalElasticsearchCluster$1.evaluate(LocalElasticsearchCluster.java:39)
        at org.elasticsearch.test.cluster.local.LocalElasticsearchCluster$1.evaluate(LocalElasticsearchCluster.java:39)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
        at java.base/java.lang.Thread.run(Thread.java:1623)

        Caused by:
        java.util.concurrent.CancellationException: Request execution cancelled
            at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.execute(CloseableHttpAsyncClientBase.java:114)
            at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:138)
            at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)
            at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
            at org.elasticsearch.xpack.remotecluster.AbstractRemoteClusterSecurityTestCase.performRequestWithAdminUser(AbstractRemoteClusterSecurityTestCase.java:205)
            at org.elasticsearch.xpack.remotecluster.AbstractRemoteClusterSecurityTestCase.createCrossClusterAccessApiKey(AbstractRemoteClusterSecurityTestCase.java:136)
            at org.elasticsearch.xpack.remotecluster.AbstractRemoteClusterSecurityTestCase.createCrossClusterAccessApiKey(AbstractRemoteClusterSecurityTestCase.java:119)
            at org.elasticsearch.xpack.remotecluster.RemoteClusterSecurityWithSameModelRemotesRestIT.lambda$static$0(RemoteClusterSecurityWithSameModelRemotesRestIT.java:55)
```

We're tracking this under https://github.com/elastic/elasticsearch/issues/94939. I'll close this and add the failure info there instead. Thanks for reporting!

**Comment by DaveCTurner** [comment] 2023-04-03 15:53
I think there's a separate issue for the delivery team to investigate here. I tried to download the `.tar.bz2` file associated with some of these failing builds and found them to be truncated/corrupt, because of the issue above. It suggests that we start to tar up the logs while there are processes still running. Therefore I'm reopening this (and labelling it accordingly).

**Comment by mark-vieira** [comment] 2023-10-09 17:16
I've renamed this issue and removed the `>test-failure` label to better represent the issue.

**Comment by mark-vieira** [comment] 2023-10-09 17:20
Actually going to close this as a duplicate of https://github.com/elastic/elasticsearch/issues/77830

**Closed by mark-vieira** 2023-10-09 17:20 UTC
Labels: :Delivery/Build, Team:Delivery
