### ISSUE TITLE
Bad breaker log doesn't allow understanding the problematic query/field

### ISSUE THREAD

**Issue by AdallomRoy** [elastic/elasticsearch#15065] opened 2015-11-27 13:11 UTC
There is no way to understand from this log, what is actually problematic, or to debug it:

    [REQUEST] New used memory 12804659728 [11.9gb] from field [<reused_arrays>] would be larger than configured breaker: 12804659609 [11.9gb], breaking

I think the minimum is either to print the query/aggregation or at least the problematic field.

**Comment by clintongormley** [comment] 2015-11-28 11:25
The problem is that the aggregation at fault may just be the straw that broke the camel's back. It could well be that another much bigger aggregation is the one that used up most of the memory, but it didn't hit the limits.

**Comment by clintongormley** [comment] 2015-11-28 11:26
Duplicate of #11145

**Closed by clintongormley** 2015-11-28 11:26 UTC
Labels: :Circuit Breakers, discuss

**Comment by rayward** [comment] 2015-12-17 22:22
Is that actually a duplicate? I don't necessarily need the whole query logged if I still don't know which agg or field was the problem.

`<reused_arrays>` is just very vague. I'm curious as to why sometimes you can get an actual description, eg `Data too large, data for field [request.count] ` but on this occasion there isn't.

**Comment by rayward** [comment] 2015-12-18 02:00
Btw we had two nodes that were constantly hitting this exception. We ended up restarting both of those nodes and the issue has seemed to resolve itself. Perhaps whatever this `reuse_arrays` structure is was not freeing up memory correctly?

We're on ES 1.7.3.
