### ISSUE TITLE
Bug - Search isn't using filters - 7.0

### ISSUE THREAD

**Issue by fyodorr** [elastic/elasticsearch#42335] opened 2019-05-22 05:28 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 7.0

**Plugins installed**: [] None

**JVM version** (`java -version`): 11

**OS version** (`uname -a` if on a Unix-like system): Ubuntu 18.04

**Description of the problem including expected versus actual behavior**:

Noticed a change since version 7.0 in how the search is working and producing false results of a search. Works in both Kibana and Elasticsearch.

Search for a field that doesn't exist yet in the index (name):

src:1.1.1.1 AND name:"Computer1"

If the field name doesn't exist in index we will get a result of only src:1.1.1.1

If we change the query to:
src:1.1.1.1 AND name:"Computer1" AND name:*

Now we will get the right results and the query using the name field that doesn't exist yet in the index.

**Steps to reproduce**:

Search for a value that doesn't exist in the index for now. For example:

hhjhghjg:"jhjhgkhlkj" AND value:"Exists"  - Will give a match on only field: value:"Exists"

hhjhghjg:"jhjhgkhlkj" AND hhjhghjg:* AND value:"Exists"    - Will not give any results.

**Provide logs (if relevant)**:

**Comment by jimczi** [comment] 2019-05-22 06:13
Thanks for reporting @fyodorr . I am closing the issue since it is a duplicate of https://github.com/elastic/elasticsearch/issues/41022 that was fixed in 7.0.1 with https://github.com/elastic/elasticsearch/pull/41062

**Closed by jimczi** 2019-05-22 06:13 UTC
