### ISSUE TITLE
multiple 'children' aggregations interfere with each other

### ISSUE THREAD

**Issue by perryn** [elastic/elasticsearch#9958] opened 2015-03-03 05:53 UTC
If you have two sibling aggregations that make use of the 'children' aggregation, then the second aggregation seems to count each document twice.

Here is a cut-down example

I have a mapping that has parent documents of type 'datastreams' with child documents of type 'readings'

I ran this, which has two identical sibling aggregations:

    curl -XGET 'https://blahblahblah/index/datastreams/_search?search_type=count&pretty' -d '{
    "aggs" : {
         "one" : {
            "children": {
              "type": "readings"
            },
           "aggs" :{
             "grand-total" : { "sum" : { "field" : "readings.dv" } }
           }
         },
         "two" : {
            "children": {
              "type": "readings"
             },
            "aggs" :{
              "grand-total" : { "sum" : { "field" : "readings.dv" } }
            }
         }  
     }  
    }' 

and got the response

    {
       "took" : 23620,
       "timed_out" : false,
       "_shards" : {
          "total" : 5,
          "successful" : 5,
          "failed" : 0
       },
      "hits" : {
         "total" : 1389,
         "max_score" : 0.0,
         "hits" : [ ]
      },
     "aggregations" : {
        "two" : {
           "doc_count" : 729353222,
           "grand-total" : {
              "value" : 2.389726905175203E10
           }
        },
       "one" : {
          "doc_count" : 364676611,
          "grand-total" : {
              "value" : 1.1948634525852589E10
          }
       }
     }
    }

Although aggregation 'one' and 'two' are identical Elasticsearch seems to have double counted the documents for aggregation 'two'

**Comment by martijnvg** [comment] 2015-03-03 08:57
Hi @perryn on what version of ES are experiencing this interference issue? Also are you able to reproduce on a smaller scale?

**Comment by perryn** [comment] 2015-03-03 23:23
Hi @martijnvg 

The above was seen on 1.4.4 but I was also able to reproduce the issue on a smaller scale on 1.4.2.

I ran the same query as above and got the following result

    {
      "took" : 4,
      "timed_out" : false,
      "_shards" : {
        "total" : 5,
        "successful" : 5,
        "failed" : 0
      },
      "hits" : {
        "total" : 600,
        "max_score" : 0.0,
        "hits" : [ ]
      },
      "aggregations" : {
        "one" : {
          "doc_count" : 12,
          "grand-total" : {
            "value" : 259.251
          }
        },
        "two" : {
          "doc_count" : 24,
          "grand-total" : {
            "value" : 518.502
          }
        }
      }
    }


cheers
Perryn

**Comment by martijnvg** [comment] 2015-03-25 14:02
@perryn I think that the issue you're reporting is fixed by #10263. Would be great if you can verify this!

**Comment by AlexKovalevich** [comment] 2015-03-29 23:57
Can reproduce in 1.5. That's actually how I came here, by trying to find a solution.

If I specify children aggregation first and then would do different sub aggregations under it - they seem to work as expected. So the example below returns two identical histograms as requested for this example.

  "aggregations" : {
    "rating_histogram_total_1" : {
      "children" : {
        "type" : "myIndex"
      },
      "aggregations" : {
        "rating_histogram_total_1" : {
          "histogram" : {
            "field" : "myIndex.reviewsRatingAverage",
            "interval" : 1,
            "min_doc_count" : 0,
            "extended_bounds" : {
              "min" : 0,
              "max" : 5
            }
          }
        },
                "rating_histogram_total_2" : {
          "histogram" : {
            "field" : "myIndex.reviewsRatingAverage",
            "interval" : 1,
            "min_doc_count" : 0,
            "extended_bounds" : {
              "min" : 0,
              "max" : 5
            }
          }
        }
       }
    }

The following request, however, doesn't work. If I put children aggregation under different filters and then try to use the same histogram, the second histogram returns values n^2, the third one - n^3 and so on. I didn't debug what would happen if filters above "children would have different criteria s".

Example: query:
"aggregations" : {
    "rating_histogram_total_1" : {
      "children" : {
        "type" : "myIndex"
      },
      "aggregations" : {
        "rating_histogram_total_1" : {
          "histogram" : {
            "field" : "myIndex.reviewsRatingAverage",
            "interval" : 1,
            "min_doc_count" : 0,
            "extended_bounds" : {
              "min" : 0,
              "max" : 5
            }
          }
        }
      }
    },
    "rating_histogram_total_2" : {
      "children" : {
        "type" : "myIndex"
      },
      "aggregations" : {
        "rating_histogram_total_2" : {
          "histogram" : {
            "field" : "myIndex.reviewsRatingAverage",
            "interval" : 1,
            "min_doc_count" : 0,
            "extended_bounds" : {
              "min" : 0,
              "max" : 5
            }
          }
        }
      }
    },
    
    "rating_histogram_total_3" : {
      "children" : {
        "type" : "myIndex"
      },
      "aggregations" : {
        "rating_histogram_total_3" : {
          "histogram" : {
            "field" : "myIndex.reviewsRatingAverage",
            "interval" : 1,
            "min_doc_count" : 0,
            "extended_bounds" : {
              "min" : 0,
              "max" : 5
            }
          }
        }
      }
    },
 
     "rating_histogram_total_4" : {
      "children" : {
        "type" : "myIndex"
      },
      "aggregations" : {
        "rating_histogram_total_4" : {
          "histogram" : {
            "field" : "myIndex.reviewsRatingAverage",
            "interval" : 1,
            "min_doc_count" : 0,
            "extended_bounds" : {
              "min" : 0,
              "max" : 5
            }
          }
        }
      }
    }


And the results are:

"aggregations": {
      "rating_histogram_total_4": {
         "doc_count": 32,
         "rating_histogram_total_4": {
            "buckets": [
               {
                  "key": 0,
                  "doc_count": 24
               },
               {
                  "key": 1,
                  "doc_count": 0
               },
               {
                  "key": 2,
                  "doc_count": 0
               },
               {
                  "key": 3,
                  "doc_count": 8
               },
               {
                  "key": 4,
                  "doc_count": 0
               },
               {
                  "key": 5,
                  "doc_count": 0
               }
            ]
         }
      },
      "rating_histogram_total_1": {
         "doc_count": 4,
         "rating_histogram_total_1": {
            "buckets": [
               {
                  "key": 0,
                  "doc_count": 3
               },
               {
                  "key": 1,
                  "doc_count": 0
               },
               {
                  "key": 2,
                  "doc_count": 0
               },
               {
                  "key": 3,
                  "doc_count": 1
               },
               {
                  "key": 4,
                  "doc_count": 0
               },
               {
                  "key": 5,
                  "doc_count": 0
               }
            ]
         }
      },
      "rating_histogram_total_3": {
         "doc_count": 16,
         "rating_histogram_total_3": {
            "buckets": [
               {
                  "key": 0,
                  "doc_count": 12
               },
               {
                  "key": 1,
                  "doc_count": 0
               },
               {
                  "key": 2,
                  "doc_count": 0
               },
               {
                  "key": 3,
                  "doc_count": 4
               },
               {
                  "key": 4,
                  "doc_count": 0
               },
               {
                  "key": 5,
                  "doc_count": 0
               }
            ]
         }
      },
      "rating_histogram_total_2": {
         "doc_count": 8,
         "rating_histogram_total_2": {
            "buckets": [
               {
                  "key": 0,
                  "doc_count": 6
               },
               {
                  "key": 1,
                  "doc_count": 0
               },
               {
                  "key": 2,
                  "doc_count": 0
               },
               {
                  "key": 3,
                  "doc_count": 2
               },
               {
                  "key": 4,
                  "doc_count": 0
               },
               {
                  "key": 5,
                  "doc_count": 0
               }
            ]
         }
      }

I hope it will help.
Thank you.

**Comment by martijnvg** [comment] 2015-04-08 14:12
@AlexKovalevich Thanks for sharing. It think this was fixed via #10263 (since it looks similar to the issue you describe). This will be included in 1.5.1. I can't be sure if this really fixed your issue, because there is no reproduction. If you like you can build from the 1.5 branch and see if the issue still occurs. This would help a lot.

**Comment by martijnvg** [comment] 2015-04-09 18:59
@AlexKovalevich Now that 1.5.1 has been released can you check if the issue still occurs in your environment?

**Comment by fozzylyon** [comment] 2015-04-10 21:34
@martijnvg I was running into the same issue and I can verify that 1.5.1 fixed it for me.

**Comment by clintongormley** [comment] 2015-04-13 10:38
awesome. @fozzylyon thanks for letting us know. closing

**Closed by clintongormley** 2015-04-13 10:38 UTC
Labels: :Aggregations, bug, feedback_needed

**Comment by AlexKovalevich** [comment] 2015-04-23 18:23
Fixed for me too in 1.5.1 !
(Sorry for delay, couldn't test earlier)
