### ISSUE TITLE
Can we have easier access to _ttl & _timestamp values?

### ISSUE THREAD

**Issue by nickminutello** [elastic/elasticsearch#11350] opened 2015-05-26 12:06 UTC
If I am not mistaken, after enabling _ttl & _timestamp, one must also then add a request for the _ttl & _timestamp fields (and _source, otherwise, it disappears) to (every) search request thereafter in order to get the values - if we want to display them.

Is there a downside to having them included with the other hit fields (_id, _index, _type, _score) automatically? 

It seems to me to be the most intuitive behaviour.
At least thats what I (and my pair) were expecting - and we had to go on a bit of a tour of stackexchange to find out why it wasnt behaving like that what hoops we had to jump through

**Comment by clintongormley** [comment] 2015-05-26 12:21
hi @nickminutello 

Agreed - in fact we have another issue open for it: https://github.com/elastic/elasticsearch/issues/8068

> Is there a downside to having them included with the other hit fields (_id, _index, _type, _score) automatically?

There used to be, a long time ago.  Now there is almost no overhead

Closing as a duplicate of #8068

**Closed by clintongormley** 2015-05-26 12:21 UTC

**Comment by nickminutello** [comment] 2015-05-26 13:21
Awesome. And quick response! Thanks.
