### ISSUE TITLE
buildDockerImageTask runs in every invocation of :distribution:docker:integTest

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#49359] opened 2019-11-20 09:43 UTC
This happens even though nothing has changed in between, which I would assume make gradle reuse existing images. 

Reproduces for instance, by running: 

```
./gradlew ':distribution:docker:integTest' --tests "org.elasticsearch.docker.test.DockerYmlTestSuiteIT.test {p0=/11_nodes/Additional disk information}"
```

consecutively

**Comment by pugnascotia** [comment] 2019-11-20 10:11
Also very irritating when iterating on Docker packaging tests and running them locally.

**Comment by mark-vieira** [comment] 2019-11-20 16:12
Indeed, we should make these tasks support incremental build.

**Comment by pugnascotia** [comment] 2019-12-02 13:22
@jkakavas this should be fixed in master. Would you mind verifying?

**Comment by pugnascotia** [comment] 2019-12-04 09:50
Actually, [Mark found that we still need some improvements here](https://github.com/elastic/elasticsearch/pull/49613#issuecomment-561340397).

**Comment by mark-vieira** [comment] 2019-12-11 21:17
This was fixed with #49613.

Here's an example build with all the build tasks UP-TO-DATE: https://gradle-enterprise.elastic.co/s/fb36ht6rfwtty

**Comment by pugnascotia** [comment] 2020-01-22 11:08
@mark-vieira there seems to be a regression here - https://gradle-enterprise.elastic.co/s/y447z33bdzgrg

What happened was:

   1. I make a change to the Docker-related files
   2. Ran the `DockerTests`, which rebuilt the image and ran the test
   3. I then immediately re-ran one of the tests, which rebuilt the image

**Comment by rjernst** [comment] 2020-01-22 19:32
Looks like the ML jar changed:
https://gradle-enterprise.elastic.co/s/y447z33bdzgrg/timeline?end=1579690100773&start=1579690100029#cpltkof7et2ea

**Comment by rjernst** [comment] 2020-01-22 19:45
@pugnascotia Do you have the build scan from the build just before the one you linked?

**Comment by pugnascotia** [comment] 2020-01-23 11:13
@mark-vieira I did two test runs back-to-back in my IDE:

First: https://gradle-enterprise.elastic.co/s/4ddr4hi2dlpa2
Second: https://gradle-enterprise.elastic.co/s/ovtybfoiywgjo

You can see in the second that it rebuilt the linux tar and docker image, when I had changed nothing.

**Comment by pugnascotia** [comment] 2020-01-23 11:47
Another run from the command line, instead of IntelliJ, and just building the Docker image. Again, back-to-back runs, on `master` this time.

   1. https://gradle-enterprise.elastic.co/s/j2elqcpc7rm6s
   2. https://gradle-enterprise.elastic.co/s/2woutebnogeay

**Comment by rjernst** [comment] 2020-01-23 18:07
@pugnascotia Can you please add `-Dscan.capture-task-input-files` to your command line and run the two again?

**Comment by pugnascotia** [comment] 2020-01-24 10:20
1. https://gradle-enterprise.elastic.co/s/ntzgihd5t2cyk
   2. https://gradle-enterprise.elastic.co/s/tfsmubr5ossv6

**Comment by mark-vieira** [comment] 2020-02-27 17:16
@pugnascotia I am unable to reproduce this locally for the life of me. Is this continuing to happen for you? @rjernst were _you_ able to reproduce this locally?

If this is still happening do you mind sharing the contents of `x-pack/plugin/ml/build/tmp/jar/MANIFEST.MF` before each build run?

**Comment by pugnascotia** [comment] 2020-03-03 10:49
Something's changed on master, because I just did two back-to-back builds and the second run was fine. I even ran the tests and saw that the first time it exported the Docker image as expected, and the second time it didn't.

So we're all good here as far as I can tell.

**Closed by pugnascotia** 2020-03-03 10:49 UTC
Labels: :Core/Infra/Build, >bug, stalled

**Comment by mark-vieira** [comment] 2020-03-03 17:10
Thanks, Rory.
