### ISSUE TITLE
Elasticsearch backup fails 

### ISSUE THREAD

**Issue by sukantasaha** [elastic/elasticsearch#38849] opened 2019-02-13 14:26 UTC
Hi we are using Elasticsearch 5.4.0 version with same version of repository-s3 plugin (repository-s3-5.4.0.jar)
we are getting below errors while taking snapshot

"state" : "PARTIAL",
      "start_time" : "2019-02-13T12:44:59.673Z",
      "start_time_in_millis" : 1550061899673,
      "end_time" : "2019-02-13T12:59:05.596Z",
      "end_time_in_millis" : 1550062745596,
      "duration_in_millis" : 845923,
      "failures" : [
        {
          "index" : "lst_p170_v_12_20170109_1730",
          "index_uuid" : "lst_p170_v_12_20170109_1730",
          "shard_id" : 0,
          "reason" : "IndexShardSnapshotFailedException[Failed to perform snapshot (index files)]; nested: IOException[Unable to upload object C-listening4-es5/indices/t_ub2WBnRAec0_dUMCSoXw/0/__m5.part11]; nested: AmazonS3Exception[MD5 local [sc2iBKE2Gs299k2vccuDsQ==], remote [UgwERt74gMmaxo5x/8qtJA==] are not equal... (Service: null; Status Code: 0; Error Code: null; Request ID: null)]; ",
          "node_id" : "uIii3lCTR2WogV0qiAyp7Q",
          "status" : "INTERNAL_SERVER_ERROR"
        }
      ],
      "shards" : {
        "total" : 1102,
        "failed" : 1,
        "successful" : 1101
      }

Here is the repository settings

"spr-prod-es-backup-group5" : {
    "type" : "s3",
    "settings" : {
      "bucket" : "spr-prod-es-backup-group5",
      "chunk_size" : "40mb",
      "server_side_encryption" : "true",
      "max_restore_bytes_per_sec" : "10gb",
      "use_throttle_retries" : "true",
      "max_retries" : "5",
      "compress" : "true",
      "buffer_size" : "40mb",
      "base_path" : "C-listening4-es5",
      "max_snapshot_bytes_per_sec" : "20mb"
    }
  }

Can some one please suggest what should be the fix

**Comment by original-brownbear** [comment] 2019-02-13 19:46
@sukantasaha do you have object locking enabled on that bucket by any chance?

**Comment by sukantasaha** [comment] 2019-02-13 23:52
No we are not locking any file or object

**Comment by sukantasaha** [comment] 2019-02-14 06:25
Also many times seeing this error

{
          "index" : "universal_message_workflow_store_1206",
          "index_uuid" : "universal_message_workflow_store_1206",
          "shard_id" : 1,
          "reason" : "IndexShardSnapshotFailedException[com.amazonaws.AmazonClientException: Unable to execute HTTP request: connect timed out]; nested: AmazonClientException[Unable to execute HTTP request: connect timed out]; nested: SocketTimeoutException[connect timed out]; ",
          "node_id" : "ntrw2NW1TtW3Z79sVHqzLQ",
          "status" : "INTERNAL_SERVER_ERROR"
        }

is there any way to increase SocketTimeout ?

**Comment by DaveCTurner** [comment] 2019-02-15 08:36
Closing this as a duplicate of https://github.com/elastic/elasticsearch/issues/25269. Please upgrade to ≥5.4.3. If the problem persists after the upgrade then please let us know and we'll reopen the issue.

**Closed by DaveCTurner** 2019-02-15 08:36 UTC
Labels: :Distributed/Snapshot/Restore
