### ISSUE TITLE
[CI] "string profiler via global ordinals native implementation" fails

### ISSUE THREAD

**Issue by dnhatn** [elastic/elasticsearch#71086] opened 2021-03-31 00:52 UTC
Build scan: https://gradle-enterprise.elastic.co/s/r2uhjr2wsn6cy

```
 ./gradlew ':qa:smoke-test-multinode:integTest' --tests "org.elasticsearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT" \
-Dtests.method="test {yaml=search.aggregation/20_terms/string profiler via global ordinals native implementation}" \
-Dtests.seed=247343C29CF5B2F2 \
-Dtests.security.manager=true \
-Dtests.locale=fi-FI \
-Dtests.timezone=Asia/Damascus 
```

```
2> java.lang.AssertionError: Failure at [search.aggregation/20_terms:860]: profile.shards.0.aggregations.0.children.0.debug.segments_with_multi_valued_ords didn't match expected value:
    profile.shards.0.aggregations.0.children.0.debug.segments_with_multi_valued_ords: expected Integer [0] but was Integer [1]
```

**Comment by nik9000** [comment] 2021-03-31 12:23
I'm away from my laptop today but I'll try and look tomorrow or the next day. If it's frequent while I'm out please zap the lines that assert on "single_value".

**Comment by nik9000** [comment] 2021-04-02 13:44
Good news! I believe I've tracked down the cause of this one!

**Comment by nik9000** [comment] 2021-04-02 14:56
Translated into English the failure says "we thought we could take the fastest path for some segments but couldn't". Interestingly, this was the only test that we could consistently take this path. I believe we were only able to take this fast path if the index contained only a single segment. There are two ways to do that:
1. You've just indexed a hand full of docs.
2. You've force merged to a single segment.

Our test was *usually* hitting case 1. But sometimes the refresh interval would kick in during the indexing and we'd end up with two segments. *That* is when it'd fail.

In production folks will fall into case 2 if they are aggregating against data that has been "rolled over" by ILM or data streams or some other process that makes a new index and force merges it down to a single segment. So for "old" data I expect folks to hit the fast path. But for "new" data I expect folks won't. Without my fix.

**Comment by nik9000** [comment] 2021-04-02 15:25
```
|        50th percentile latency | date-histo-string-terms-via-global-ords | 3414.02 | 2632.01 | -782.015 | ms |
|        90th percentile latency | date-histo-string-terms-via-global-ords | 3470.91 | 2756.88 | -714.031 | ms |
|       100th percentile latency | date-histo-string-terms-via-global-ords | 3620.89 | 2875.79 | -745.102 | ms |
|   50th percentile service time | date-histo-string-terms-via-global-ords | 3410.15 | 2628.87 | -781.275 | ms |
|   90th percentile service time | date-histo-string-terms-via-global-ords | 3467.36 | 2752.43 | -714.933 | ms |   20%!!!!
|  100th percentile service time | date-histo-string-terms-via-global-ords | 3617.71 | 2871.63 | -746.083 | ms |
```

**Closed** 2021-04-15 12:27 UTC
Labels: :Analytics/Aggregations, >test-failure, Team:Analytics
