### ISSUE TITLE
Allow composite agg keys to be selected inside bucket selector

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#36853] opened 2018-12-19 17:33 UTC
`bucket_path` syntax allows for retrieving the current count, number of buckets and lastly the value of the current bucket through `_bucket`.
However it doesn't seem to work (as far as I can tell) for composite agg as it cannot unwrap the map of keys used internally by the agg:

Take for example the following query:
```javascript
"aggregations": {
 "groupby": {
  "composite": {
   "sources": [{
     "31": {
      "date_histogram": {
       "field": "birth_date"
       ...
      }
     }
    }
   ]
  },
  "aggregations": {
   "having.8": {
    "bucket_selector": {
     "buckets_path": {
      "g0": "_key"
     }
    }
   }
  }
 }
}
```

this returns:
"buckets_path must reference either a number value or a single value numeric metric aggregation, got: org.elasticsearch.search.aggregations.bucket.composite.InternalComposite.ArrayMap"

and any other variation such as "31", "31>_key", "31#_key", "_key[31]", "_key#31" returns "agg not found"

**Comment by acarstoiu** [comment] 2019-02-22 13:36
[not helpful]
I'm curious, where did you find the tip about `_bucket`?

**Comment by polyfractal** [comment] 2019-07-12 16:46
Closing as duplicate of https://github.com/elastic/elasticsearch/issues/32692 (e.g. composite doesn't work with pipeline aggs right now).

Although a related note, I have a PR open to allow selecting specific keys/buckets from a multi-bucket agg when using pipeline aggs: https://github.com/elastic/elasticsearch/pull/44179

**Closed by polyfractal** 2019-07-12 16:46 UTC
Labels: :Analytics/Aggregations
