### ISSUE TITLE
Can't compile external plugin with 7.5.0 (relying on org.elasticsearch.gradle:build-tools)

### ISSUE THREAD

**Issue by dweiss** [elastic/elasticsearch#50230] opened 2019-12-16 12:49 UTC
I can't upgrade the clustering plugin to work with 7.5.0. 
https://github.com/carrot2/elasticsearch-carrot2

Out of the box it says:
```
> Failed to apply plugin [class 'org.elasticsearch.gradle.DistributionDownloadPlugin']
   > Cannot get property 'isInternal' on extra properties extension as it does not exist
```
and when I add isInternal=false to ext it bails later on with:
```
Could not determine the dependencies of task ':extractElasticsearch7.5.0'.
> Expected configuration ':elasticsearch_7.5.0_integ_test_zip_null' to contain exactly one file, however, it contains no files.
```

I think this is related to a recent change by (Ryan @rjernst)? branch 7.4.x also doesn't compile but for a different reason (bwcVersions property referenced).

These types of problems occur very frequently. It'd be really nice if you had a simple plugin that is *not* part of the ES build but rather invoked as a forked GradleBuild task (with a local pseudo-maven repository for example). Or even kept in a separate repository (maybe there is one but I missed it?) This would help in making sure that things work for external plugin writers and as an example of any special magic that needs to be added to the external plugin.

**Comment by rjernst** [comment] 2019-12-16 19:22
@dweiss The latter error about configuration being empty was fixed by #49813 and #49956. I checked out the master branch of carrot2 did not see the error about isInternal, only the empty error above. Are there some other reproduction steps you can recommend?

**Comment by rjernst** [comment] 2019-12-16 19:23
Oh I see it now, I found that you checked in the isInternal = false hack. I'm looking into it.

**Comment by dweiss** [comment] 2019-12-16 19:24
Yeah. Sorry for leaving it messy!

**Comment by rjernst** [comment] 2019-12-16 19:52
Ok, the isInternal issue is because you are applying testclusters before esplugin. If you reverse the order (or just remove applying testclusters as it is applied by esplugin), you only get the latter error, for which there are workarounds described #49813 and #49956. I'm addressing that in #50249.

> These types of problems occur very frequently. It'd be really nice if you had a simple plugin that is not part of the ES build but rather invoked as a forked GradleBuild task (with a local pseudo-maven repository for example).

We sort of had this, but the way it was setup was causing spurious failures for unrelated reasons that were very difficult to debug. We want to add them back in some fashion. The general idea is to use the `plugins/examples` build files and tweak them to use a locally build maven repo, thus they should trigger all the "external" code. I'm going to close this issue as the problem of compiling in 7.5 is addressed by the linked PRs. Thanks for reporting the problem!

**Closed by rjernst** 2019-12-16 19:52 UTC
Labels: :Core/Infra/Build

**Comment by dweiss** [comment] 2019-12-16 20:17
Thanks Ryan! I'll follow-up on this tomorrow.

**Comment by dweiss** [comment] 2019-12-17 09:28
Hmm... Where's the workaround in those referenced issues :) Because I've read the discussion there and looked at the patch but I don't see how I can apply it so that my code compiles against 7.5.0. 

Is your suggestion to wait for the update that fixes the problem (7.5.1)?

**Comment by rjernst** [comment] 2019-12-17 16:20
Sorry @dweiss the workarounds are in the issue those PRs address. Here they are:
https://github.com/elastic/elasticsearch/issues/49787#issuecomment-562704640
https://github.com/elastic/elasticsearch/issues/49787#issuecomment-562720655

**Comment by dweiss** [comment] 2019-12-17 19:23
Configurations.whenObjectAdded? Love the magic. ;) Thanks Ryan.
