### ISSUE TITLE
[CI] ESSingleNodeTestCase fails during tear down

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#110409] opened 2024-07-03 09:13 UTC
There a few tests failing with the following tripping assertion:

```
java.lang.AssertionError: 
Expected: <0>
     but: was <1>

  at __randomizedtesting.SeedInfo.seed([59D096BBD580D6F7:30569F584F933B31]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
  at org.elasticsearch.test.ESTestCase.assertThat(ESTestCase.java:2313)
  at org.elasticsearch.test.ESSingleNodeTestCase.tearDown(ESSingleNodeTestCase.java:134)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
```
Tests are totally unrelated and the only commonalty is that the extend `ESSingleNodeTestCase`. There is some suspicion that this is caused by https://github.com/elastic/elasticsearch/pull/109481. Anyway I open this issue so we can add those failing test under the same umbrella.

related https://github.com/elastic/elasticsearch/issues/110406
related https://github.com/elastic/elasticsearch/issues/110398
related https://github.com/elastic/elasticsearch/issues/110388
related https://github.com/elastic/elasticsearch/issues/109905

**Comment by pmpailis** [comment] 2024-07-03 09:17
Also relates to https://github.com/elastic/elasticsearch/issues/109830. We're adding trace logging in https://github.com/elastic/elasticsearch/pull/110378 to help identify the cause/why the context is not being cleaned up.

**Comment by pmpailis** [comment] 2024-07-09 05:21
Added a waiting check for all `free_context` actions to be consumed before validating active contexts in https://github.com/elastic/elasticsearch/pull/110595. Closing this one.

**Closed by pmpailis** 2024-07-09 05:21 UTC
Labels: :Search/Search, >test-failure, Team:Search, needs:risk
