### ISSUE TITLE
[CI] BanFailureLoggingTests testLogsAtDebugOnDisconnectionDuringBan failing

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#76558] opened 2021-08-16 12:11 UTC
Suspicious that this failed after this same test failed for a different reason a couple of weeks ago: https://github.com/elastic/elasticsearch/pull/75171

**Build scan:**
https://gradle-enterprise.elastic.co/s/prdb3lqjdshak/tests/:server:test/org.elasticsearch.tasks.BanFailureLoggingTests/testLogsAtDebugOnDisconnectionDuringBan

**Reproduction line:**
`./gradlew ':server:test' --tests "org.elasticsearch.tasks.BanFailureLoggingTests.testLogsAtDebugOnDisconnectionDuringBan" -Dtests.seed=3A306031869227FC -Dtests.locale=sr-BA -Dtests.timezone=America/Argentina/Rio_Gallegos -Druntime.java=16`

**Applicable branches:**
7.14

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.tasks.BanFailureLoggingTests&tests.test=testLogsAtDebugOnDisconnectionDuringBan

**Failure excerpt:**
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=231, name=elasticsearch[TransportTasksActionTests][management][T#1], state=RUNNABLE, group=TGRP-BanFailureLoggingTests]

  at __randomizedtesting.SeedInfo.seed([3A306031869227FC:8D572F744CBF6026]:0)

  Caused by: java.lang.AssertionError: (No message provided)

    at __randomizedtesting.SeedInfo.seed([3A306031869227FC]:0)
    at org.junit.Assert.fail(Assert.java:86)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertTrue(Assert.java:52)
    at org.elasticsearch.tasks.BanFailureLoggingTests.lambda$runTest$5(BanFailureLoggingTests.java:127)
    at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1035)
    at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1008)
    at org.elasticsearch.tasks.BanFailureLoggingTests.lambda$runTest$6(BanFailureLoggingTests.java:127)
    at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:61)
    at org.elasticsearch.transport.InboundHandler$1.doRun(InboundHandler.java:212)
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:732)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
    at java.lang.Thread.run(Thread.java:831)

```

**Comment by DaveCTurner** [comment] 2021-08-18 15:55
I managed to reproduce this failure by running `./gradlew ':server:test' --tests "org.elasticsearch.tasks.BanFailureLoggingTests.testLogsAtDebugOnDisconnectionDuringBan" -Dtests.iters=1000 -Dtests.failfast=true` concurrently with `stress-ng --cpu 16 --yield 8` to try and mess with the thread scheduling a bit. It also fails in `master` like this.

I suspect this might be a genuine bug. The failure indicates we're not cancelling a task received over a transport connection when the connection closes. If I ensure that the task already started before closing the connection then I see no failures (for many thousands of iterations) but if I let the connection close concurrently with the task starting then it fails pretty reliably within the first 1000 iterations.

**Comment by DaveCTurner** [comment] 2021-08-18 17:04
Oh no it's ok, just a silly test bug. I opened https://github.com/elastic/elasticsearch/pull/76668.

**Comment by original-brownbear** [comment] 2021-09-02 12:38
This just failed again on 7.15 (and seemingly in the exact same way it failed here so I'm reopening this one).

See https://gradle-enterprise.elastic.co/s/fl7iq3ig4up6i/console-log/raw

**Comment by DaveCTurner** [comment] 2022-02-08 21:48
#76668 was labelled to be backported to 7.14 and 7.15 but it turns out I only backported it as far as 7.16. The unfixed branches are dead now and this hasn't subsequently failed on any branches with the fix so I'm closing this.

**Closed by DaveCTurner** 2022-02-08 21:48 UTC
Labels: >test-failure, :Distributed/Task Management, Team:Distributed
