### ISSUE TITLE
Elastic 2.0 beta returning wrong results from cache?

### ISSUE THREAD

**Issue by devlo** [elastic/elasticsearch#13662] opened 2015-09-18 19:54 UTC
I have an array with categories in which i have genres like for example Comedy. I search for documents that contain that and other genres using filtered query in which i have empty query and terms filter. 
Next i use match query on for example title field + terms filter for genres and choose Comedy. On third query i do exact search like first one so only look for Comedy in genres (only using terms filter and empty query) and i get results of last match search (so second query results) which are obviously wrong.

**Comment by s1monw** [comment] 2015-09-18 20:06
@devlo thanks so much for opening this, can you reproduce this in a simple self contained example?

**Comment by devlo** [comment] 2015-09-18 21:25
As i thought it's a cache problem, i've added _cache: false to terms query (i am using node.js driver) and it's returning good results. I will try to make an example.
Probably has something to do with #5363

**Comment by clintongormley** [comment] 2015-09-19 13:12
Hi @devlo 

The `_cache` parameter is no longer supported in 2.0 (it is silently ignored) so I doubt it has anything to do with this.  A recreation would be very helpful indeed.

**Comment by clintongormley** [comment] 2015-09-19 13:17
This is what I've tried doing to recreate this, but it works as expected:

    POST t/t
    {
      "title": "One foo bar",
      "cats": ["one","two","three"]
    }
    
    POST t/t
    {
      "title": "Two foo bar",
      "cats": ["one","two"]
    }
    
    POST t/t
    {
      "title": "Three foo bar",
      "cats": ["two"]
    }
    
    GET _search
    {
      "query": {
        "filtered": {
          "query": {
            "query_string": {
              "query": "*"
            }
          }, 
          "filter": {
            "terms": {
              "cats": [
                "one",
                "three"
              ]
            }
          }
        }
      }
    }
    
    GET _search
    {
      "query": {
        "filtered": {
          "query": {"match": {
            "title": "One"
          }}, 
          "filter": {
            "terms": {
              "cats": [
                "one",
                "three"
              ]
            }
          }
        }
      }
    }

**Comment by devlo** [comment] 2015-09-19 21:06
Hmmm i can't reproduce it now, i've restarted elasticsearch after that, used _cache: false and i thought it was the issue. But i've removed _cache: false and tried now and everything works as intented. Indeed very wierd behaviour. It's wierd because i had the same issue on local test environment and on remote test server. I've restarted elastic on both. I will observe this as i am working on 2.0 beta anyway.

**Comment by clintongormley** [comment] 2015-10-06 14:19
Looks like a false alarm. Closing.  Feel free to reopen if you can reproduce.

**Closed by clintongormley** 2015-10-06 14:19 UTC
Labels: blocker, bug

**Comment by JulianRooze** [comment] 2016-08-26 13:31
Hi,

I believe I currently have this same issue (or at least related) and have a reproducible case (at least on my machine and our production cluster :D). I can't post the data publicly, but poke me on Twitter @queryable and I can provide it for you (it's small enough at 9 MB). 

I've opened a Stackoverflow question on it here:

http://stackoverflow.com/questions/39155676/erratic-search-results-from-elastic-when-sorting-on-a-field

**Comment by clintongormley** [comment] 2016-08-26 13:47
@JulianRooze could you email it to me at clinton at elastic dot co?

**Comment by JulianRooze** [comment] 2016-08-26 13:58
@clintongormley I've mailed it to you, thanks!

**Comment by JulianRooze** [comment] 2016-10-20 18:06
@clintongormley Hi Clinton, I was curious about this issue and if you guys have made any progress on it. Last I heard you managed to reproduce the faulty behavior. This is both speaking out of curiosity what the cause behind this weird behavior is and whether I can strip the workaround from our code yet :)

Cheers!

**Comment by clintongormley** [comment] 2016-11-02 17:46
Sorry @JulianRooze - this was fixed in #20196

**Comment by JulianRooze** [comment] 2016-11-02 19:58
@clintongormley Great, thanks for letting me know!
