### ISSUE TITLE
[CI] IndexShardTests testScheduledRefresh failing

### ISSUE THREAD

**Issue by salvatore-campagna** [elastic/elasticsearch#96920] opened 2023-06-19 11:24 UTC
**Build scan:**
https://gradle-enterprise.elastic.co/s/vsnco5lyqpo3c/tests/:server:test/org.elasticsearch.index.shard.IndexShardTests/testScheduledRefresh

**Reproduction line:**
```
./gradlew ':server:test' --tests "org.elasticsearch.index.shard.IndexShardTests.testScheduledRefresh" -Dtests.seed=72D17F6136232683 -Dtests.locale=es-HN -Dtests.timezone=America/Buenos_Aires -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.index.shard.IndexShardTests&tests.test=testScheduledRefresh

**Failure excerpt:**
```
java.lang.AssertionError: (No message provided)

  at __randomizedtesting.SeedInfo.seed([72D17F6136232683:84443C8B62B9FD0A]:0)
  at org.junit.Assert.fail(Assert.java:86)
  at org.junit.Assert.assertTrue(Assert.java:41)
  at org.junit.Assert.assertTrue(Assert.java:52)
  at org.elasticsearch.index.shard.IndexShardTests.testScheduledRefresh(IndexShardTests.java:3854)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

**Comment by kingherc** [comment] 2023-06-19 13:47
@original-brownbear we've done some PRs on refresh related changes. Since you're checking this out, I'd like to point out https://github.com/elastic/elasticsearch/pull/96640/files as a first PR to take a look at.

**Comment by tlrx** [comment] 2023-06-22 15:04
@kingherc I opened https://github.com/elastic/elasticsearch/pull/97012 following the change you mentioned

**Comment by valeriy42** [comment] 2023-06-26 12:35
Another failure: https://gradle-enterprise.elastic.co/s/upt5xd3lkcw52

**Comment by kingherc** [comment] 2023-06-27 09:43
This looks like it started appearing when https://github.com/elastic/elasticsearch/pull/96321/ was merged. I cannot certainly say it's the cause. But looks like maybe some scheduled operation or something refreshes the shard before we assert the scheduledRefresh() call? cc @martijnvg in case he can think of why that PR may have influenced the failing assertion. I'll continue investigating.

**Comment by martijnvg** [comment] 2023-06-27 11:50
I don't think the async refresh is causing this test failure. I don't fully understand the failure yet, I will take another look at this test failure.

**Comment by kingherc** [comment] 2023-06-27 12:55
@martijnvg I think finally that this part of the code:

```
    public final void ensureShardSearchActive(Consumer<Boolean> listener) {
...
            addRefreshListener(location, (result) -> {
                pendingRefreshLocation.compareAndSet(location, null);
                listener.accept(true);
            });
```

does not mean that when the listener is invoked that a refresh has actually happened. So I would recommend to remove the way we use the latches in the test, and instead replace them by waiting for the total number of refreshes to go up by 1. This should ensure that the lucene refresh was completed.

If you're not working on this issue actively yet, I can propose a PR.

**Closed** 2023-06-28 07:26 UTC
Labels: >test-failure, :Distributed/Engine, Team:Distributed
