### ISSUE TITLE
[CI] RecoveryIT testRecoveryWithConcurrentIndexing failing

### ISSUE THREAD

**Issue by arteam** [elastic/elasticsearch#99778] opened 2023-09-21 17:29 UTC
**Build scan:**
https://gradle-enterprise.elastic.co/s/7qe3jde27dcuu/tests/:qa:rolling-upgrade-legacy:v7.17.13%23upgradedClusterTest/org.elasticsearch.upgrades.RecoveryIT/testRecoveryWithConcurrentIndexing

**Reproduction line:**
```
./gradlew ':qa:rolling-upgrade-legacy:v7.17.13#upgradedClusterTest' -Dtests.class="org.elasticsearch.upgrades.RecoveryIT" -Dtests.method="testRecoveryWithConcurrentIndexing" -Dtests.seed=DD0C8780632E495C -Dtests.bwc=true -Dtests.locale=sq -Dtests.timezone=Europe/Kiev -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.upgrades.RecoveryIT&tests.test=testRecoveryWithConcurrentIndexing

**Failure excerpt:**
```
java.lang.AssertionError: failed to get doc count for index [recovery_with_concurrent_indexing] with preference [_only_nodes:GIsX4jecSECR8Sukz4EWZg] response [org.elasticsearch.client.ResponseException: method [GET], host [http://127.0.0.1:38683], URI [recovery_with_concurrent_indexing/_count?preference=_only_nodes%3AGIsX4jecSECR8Sukz4EWZg], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"no data nodes with criteria [GIsX4jecSECR8Sukz4EWZg] found for shard: [recovery_with_concurrent_indexing][0]"}],"type":"illegal_argument_exception","reason":"no data nodes with criteria [GIsX4jecSECR8Sukz4EWZg] found for shard: [recovery_with_concurrent_indexing][0]"},"status":400}] recovery [{"recovery_with_concurrent_indexing":{"shards":[{"id":0,"type":"PEER","stage":"DONE","primary":false,"start_time_in_millis":1695316186643,"stop_time_in_millis":1695316186855,"total_time_in_millis":212,"source":{"id":"SymbfPsORgWRLdlBANBhkQ","host":"127.0.0.1","transport_address":"127.0.0.1:35819","ip":"127.0.0.1","name":"v7.17.13-0"},"target":{"id":"QcuazfWtSq2Chj-mCEaa9w","host":"127.0.0.1","transport_address":"127.0.0.1:38307","ip":"127.0.0.1","name":"v7.17.13-1"},"index":{"size":{"total_in_bytes":0,"reused_in_bytes":0,"recovered_in_bytes":0,"recovered_from_snapshot_in_bytes":0,"percent":"0.0%"},"files":{"total":0,"reused":0,"recovered":0,"percent":"0.0%"},"total_time_in_millis":0,"source_throttle_time_in_millis":0,"target_throttle_time_in_millis":0},"translog":{"recovered":65,"total":67,"percent":"97.0%","total_on_start":-1,"total_time_in_millis":168},"verify_index":{"check_index_time_in_millis":0,"total_time_in_millis":0}},{"id":0,"type":"PEER","stage":"DONE","primary":false,"start_time_in_millis":1695316051628,"stop_time_in_millis":1695316051692,"total_time_in_millis":64,"source":{"id":"QcuazfWtSq2Chj-mCEaa9w","host":"127.0.0.1","transport_address":"127.0.0.1:35397","ip":"127.0.0.1","name":"v7.17.13-1"},"target":{"id":"SymbfPsORgWRLdlBANBhkQ","host":"127.0.0.1","transport_address":"127.0.0.1:35819","ip":"127.0.0.1","name":"v7.17.13-0"},"index":{"size":{"total_in_bytes":0,"reused_in_bytes":0,"recovered_in_bytes":0,"recovered_from_snapshot_in_bytes":0,"percent":"0.0%"},"files":{"total":0,"reused":0,"recovered":0,"percent":"0.0%"},"total_time_in_millis":0,"source_throttle_time_in_millis":0,"target_throttle_time_in_millis":0},"translog":{"recovered":11,"total":11,"percent":"100.0%","total_on_start":-1,"total_time_in_millis":59},"verify_index":{"check_index_time_in_millis":0,"total_time_in_millis":0}}]}}]

  at __randomizedtesting.SeedInfo.seed([DD0C8780632E495C:5D5D43D3E18A9796]:0)
  at org.junit.Assert.fail(Assert.java:88)
  at org.elasticsearch.upgrades.RecoveryIT.assertCount(RecoveryIT.java:181)
  at org.elasticsearch.upgrades.RecoveryIT.testRecoveryWithConcurrentIndexing(RecoveryIT.java:161)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

**Comment by pgomulka** [comment] 2023-09-22 11:19
more failures on branches
https://gradle-enterprise.elastic.co/s/6ip6oawgrr52i/tests/task/:qa:rolling-upgrade:v7.17.14%23upgradedClusterTest/details/org.elasticsearch.upgrades.RecoveryIT/testOperationBasedRecovery?top-execution=1

**Comment by cbuescher** [comment] 2023-09-26 15:04
I just had this on a PR CI test run, also "RecoveryIT#TestTurnOffTranslogRetentionAfterUpgraded" was failing:
https://gradle-enterprise.elastic.co/s/kqa24bgamikqy/tests/overview?outcome=failed

**Comment by mark-vieira** [comment] 2023-10-03 21:08
This is failing a handful of times a day or more so I've muted this test.

**Comment by williamrandolph** [comment] 2023-10-03 21:21
I think this is failing because of the change I made here: https://github.com/elastic/elasticsearch/pull/99668/

Looking back at the logs from the failure on that merge commit, I found this line:

```
» [2023-09-20T20:37:26,299][WARN ][o.e.i.c.IndicesClusterStateService] [v7.17.14-2] [.tasks][0] marking and sending
shard failed due to [failed to update index (mapping update failed)]
»  java.lang.IllegalStateException: expected current mapping [{"task":{"dynamic":"strict","_meta":{"version":"7.17.1
4"},"properties":{"completed":{"type":"boolean"},"error":{"type":"object","enabled":false},"response":{"type":"objec
t","enabled":false},"task":{"properties":{"action":{"type":"keyword"},"cancellable":{"type":"boolean"},"description"
:{"type":"text"},"headers":{"type":"object","enabled":false},"id":{"type":"long"},"node":{"type":"keyword"},"parent_
task_id":{"type":"keyword"},"running_time_in_nanos":{"type":"long"},"start_time_in_millis":{"type":"long"},"status":
{"type":"object","enabled":false},"type":{"type":"keyword"}}}}}}] to be the same as new mapping [{"task":{"dynamic":
"strict","_meta":{"version":"8.11.0","managed_index_mappings_version":0},"properties":{"completed":{"type":"boolean"
},"error":{"type":"object","enabled":false},"response":{"type":"object","enabled":false},"task":{"properties":{"acti
on":{"type":"keyword"},"cancellable":{"type":"boolean"},"description":{"type":"text"},"headers":{"type":"object","en
abled":false},"id":{"type":"long"},"node":{"type":"keyword"},"parent_task_id":{"type":"keyword"},"running_time_in_na
nos":{"type":"long"},"start_time_in_millis":{"type":"long"},"status":{"type":"object","enabled":false},"type":{"type
":"keyword"}}}}}}]
```

The difference between those two json blobs is just in the metadata block:

```
      "_meta": {
        "version": "7.17.14"
      },
```

vs.

```
      "_meta": {
        "managed_index_mappings_version": 0,
        "version": "8.11.0"
      },
```

This is a mapping for a managed system index. In #99668, I loosened the conditions under which system index mapping updates occur, and I'm guessing I introduced (or increased the likelihood of) a race condition with the index recovery code.

I'm taking this issue and moving it to core/infra for further investigation.

**Comment by benwtrent** [comment] 2023-10-03 23:54
@williamrandolph fantastic find!

**Comment by williamrandolph** [comment] 2023-10-17 12:40
I spent a while trying to chase this down, and I think I figured out why it doesn't reproduce locally: system indices (in this case `.tasks`) don't get created by the `RecoveryIT` itself, but by the YAML tests that run alongside it. I _think_ the race condition here is that the `SystemIndexMappingUpdateService` modifies the mappings concurrently with some shard reallocation operation, but I haven't yet found where the window for error is on the shard allocation side.

**Comment by williamrandolph** [comment] 2023-10-23 15:47
I haven't been able to reproduce this, and I'm not even sure whether there's a problem apart from test expectations. I'm going to reenable the test with additional logging and dig in once there's another failure. In the meantime, I'm going to downgrade this issue back to medium-risk.

**Closed** 2023-11-03 19:09 UTC
Labels: >test, :Core/Infra/Core, >test-failure, Team:Core/Infra, medium-risk
