### ISSUE TITLE
Support for nested query syntax within query string query DSL

### ISSUE THREAD

**Issue by tuespetre** [elastic/elasticsearch#11322] opened 2015-05-24 19:14 UTC
I understand that issue #9611 was closed regarding this:

> Nested fields need to be queries with nested queries/filters, because multiple documents can match and you need to be able to specify how these multiple scores should be reduced to a single score.
> &mdash; -- @clintongormley 
# Proposal

I propose that, when a field name within a query string query is parsed, and it does not match a field mapping, an attempt should be made to match the field name to a nested object mapper. If the attempt is successful, the query text for that field name should then be parsed as a query string query using the same settings as the root level query string query. The resulting query from that parsing will in turn be used to create a ToParentBlockJoinQuery (a nested query) that uses the same default scoring mode that would be applied when manually submitting a nested query ("avg".) 
# The syntax

The acceptable syntax for a nested query within a query string query is similar to this:

`nestedPath:"<query string query>"`

This means that any constructs you would use in a query string query are valid:

`children:"children.first:peggy"`
`children:"children.first:\"peggy\""`
`children:"children.first:(peggy ruby)"`
`children:"children.first:peggy AND children.last:sue"`
`children:"children.first:pegyg~ +children.last:su?"`

Note that the nested query MUST be surrounded with quotes. I wanted it to be parentheses instead but unfortunately the Lucene QueryParser class does not recognize the field names the way I wanted it to (`children:(children.first:peggy)` would come out as a TermQuery on `children.first`, the `children` field name would be discarded.)
# Other considerations
- Support for specifying scoring modes within the query string query settings based on nested object paths is a possibility.
- Support for inner hits may also be a possibility, in a similar fashion to scoring modes.

Support for nested queries in query strings at all would be an enhancement, but these options could provide additional enhancements. Example of how they may look:

```
{
    "query_string" : {
        "query" : "children:\"children.first:peggy\"",
        "nested": [
            {
                "path": "children",
                "score_mode": "max",
                "inner_hits": {
                    <inner_hits_options>
                }
            }
        ]
    }
}
```
# Pull request

For the basic functionality, I have already made the necessary modifications (three changed files, one changed test file to add a test with several assertions) on the 'master' branch of my local clone of the repository. I would like to submit a pull request; please advise as to how you would like that to be done (if I need to rebase onto another branch, etc.)

**Comment by tuespetre** [comment] 2015-07-24 12:58
I've since worked around this in other ways (simple regex to parse out nested field expressions on my end and submit them properly to ES); It was fun to mess around with this but I fully support axing it now.

**Comment by clintongormley** [comment] 2015-07-27 11:12
thanks @tuespetre

**Comment by radenui** [comment] 2016-01-22 15:44
Hi @tuespetre ,

I'm very interested in the workaround you used. Did you manage to make it work with kibana ?
Thanks !

**Comment by tuespetre** [comment] 2016-01-22 16:16
@radenui 

I wrote the following drop-in helper class (written in C#, but should be easily portable to other languages): https://gist.github.com/tuespetre/f6951bb665c79abbb7c8

You basically use the class to create new URIs by performing some function against the existing query string (remove this filter, replace that filter, add this filter, etc.) When you specifically need to allow users to perform a 'proper' nested query, you can just use the helper to extract the filters on the nested properties out and build up a separate query string, which you would then submit as a nested query string query in your request to Elasticsearch.

I'm using it to offer both 'customer service representative friendly' interfaces (where the query string built up by the 'friendly' controls is stored in a hidden input) and 'technical user friendly' interfaces (where the query string is spit out into a visible text box that you can also type in, a-la GitHub Issues.)

**Comment by rmm5t** [comment] 2016-05-10 18:30
I actually quite like this proposal. Is it something that would be considered by the elasticsearch team or is this something that's not likely to ever be a feature? I'd love if the query string syntax allowed for nested query combinations. 

> I wanted it to be parentheses instead 

Agreed. I think this syntax would be much better served by parentheses instead of quotations.

**Comment by jsangari-ssat** [comment] 2016-05-24 12:58
Hi,

Is the syntax recommended here for the query_string supported in ES, I am using Version 2.2 and am having hard time getting it to work

**Comment by alexgarel** [comment] 2016-09-19 13:45
Hello I also think this should be supported. Query DSL remains a nice helper, and being able to use nested objects whit it would be great.

**Comment by tuespetre** [comment] 2016-09-19 14:05
@alexgarel and all everyone:

I think it would be more beneficial to keep something this niche and complex out of the core elasticsearch, and offer your own query DSL 'layer' that can be translated into a 'proper' ES query on the backend. By brushing up on regular expressions (or even parsing!) a little bit you can put together some pretty cool UX affordances specific to your application.

**Comment by rmm5t** [comment] 2016-09-19 14:12
> ...keep something this niche and complex out of the core elasticsearch...

> ...By brushing up on regular expressions (or even parsing!) a little bit...

So, is it niche and _complex_ or is it as simple as adding a few items to the elasticsearch grammar? 

Personally, I agree that you can add a custom syntax on top (with regexes or otherwise), but I also would like this discussion to remain open, because I think having a conversation about making the query string syntax more robust isn't necessarily a bad thing. Having every elasticsearch application implement yet another hack on top of the query string syntax to accomplish this isn't necessarily a great use of global man-hours. 

I'm mostly interested to better understand if the elasticsearch team is interested in a Pull Request for this feature. So far,  we don't have an answer to that question.

**Comment by alexgarel** [comment] 2016-09-19 14:21
Ok I understand, it's the way we have chosen but not fully implemented yet. If someone needs it, we have a (GPL)  [lucene query parser in python](https://github.com/jurismarches/luqum/)

**Comment by tuespetre** [comment] 2016-09-19 14:37
@rmm5t I had submitted a PR (https://github.com/elastic/elasticsearch/issues/11339) but as @clintongormley points out it's just a fragile thing to have in the core application, and as I found out when working the PR initially, it can't really be done with a pleasant syntax -- it comes out feeling very verbose and awkward, especially being unable to hijack the parenthesis for it. With a small handful of regular expressions I was able to implement a much nicer syntax specific to the particular needs of our application without feeling like I had to 'settle' for something subpar.

**Comment by rmm5t** [comment] 2016-09-19 19:16
> I had submitted a PR (#11339) but as @clintongormley points out it's just a fragile thing to have in the core application, and as I found out when working the PR initially, it can't really be done with a pleasant syntax

@tuespetre  Interesting point. That PR was tagged for discussion (which respectfully never really happened amongst the elasticsearch team, aside from @clintongormley willingness to comment and chime in). Then, it was closed, solely because you closed this particular issue after building a workaround -- not because a discussion really happened. 

I agree with your first assessment that the double-quoted syntax isn't ideal. I understand there are problems with the clearer parentheses syntax, but I suspect those can probably be overcome.

If the core query string syntax and implementation are _"fragile,"_ maybe that's something that should be addressed and potentially refactored as well. To be clear, I'm not trying to make light of this; I'm sure a refactor would be a tricky endeavor.

Overall, I'd really just like to see an ability to narrow a query string search to one particular embedded object.  I'd like to see a syntax that looked like this:

`children:(gender:male AND age:>18 AND age:<26)`

Otherwise, there's no way to use the query string syntax and (in this particular US-centric example) find parents who have children who should be signed up for the US Selective Service System.

**Comment by traut** [comment] 2017-07-20 10:41
can we resurrect this issue please?

**Comment by clintongormley** [comment] 2017-07-20 10:47
Yeah, I think we need to think more about whether to expose this.  Opening for more discussion

**Comment by czjxy881** [comment] 2017-10-09 07:40
+1

**Comment by tuespetre** [comment] 2017-10-09 14:29
@rmm5t good points, your 'wish syntax' looks nice!

**Comment by buchanae** [comment] 2017-12-14 21:29
If I could comment on my experience as a user:

It took me an hour or so to figure out that this didn't exist. I'd like to build a dashboard with a search bar, where the syntax is defined by Elasticsearch/Lucene's query string syntax. Having this would make that project substantially easier.

As an engineer: this seems like a great candidate for something that could grow, mature, and harden outside of the core. If a service/library can be built using Lucene's parser and submit JSON-style nested Elasticsearch queries on the backend, we could figure out the details with a non-core prototype.

> children:(gender:male AND age:>=18 AND age:<=25)

I like that.

My initial idea, inspired by `jq`: `children[].gender:male`. About 2 seconds of thought went into that, so potentially full of holes :)

**Comment by alexgarel** [comment] 2017-12-14 22:08
@buchanae sorry for I repeat myself but you can see our (GPL)  [lucene query parser in python](https://github.com/jurismarches/luqum/) it's yet far from perfect but may help.

**Comment by albogdano** [comment] 2018-01-12 09:46
I'd also like to +1 this and share my experience. I'm a long-time Elasticsearch user and I've recently hit the "**field mapping explosion**" limitation. Our system allows users to define their own objects with any number of custom fields, which leads to a mapping explosion. Currently, from what [I read in the forum](https://discuss.elastic.co/t/can-nested-fields-prevent-mapping-explosion/95464/2), the only way to solve this is to use nested key/value objects inside an array field: 
```
nested: [{k: KEY1, v: VALUE1}, ...]
``` 

This lead me to this issue. I'm trying to seamlessly combine normal queries and queries to nested objects in a single query string query. I think this feature would make it easier for people to solve the problem of "too many custom fields".

**Comment by cont-korzh** [comment] 2018-04-10 03:48
+1

**Comment by jonasbergqvist** [comment] 2018-06-28 12:55
+ 1

**Comment by waswrongassembled** [comment] 2019-02-15 08:45
+1

**Comment by ChristopherSnay** [comment] 2019-04-25 14:48
+1

**Comment by theoJA** [comment] 2019-05-13 21:45
+1

**Comment by prashantalhat** [comment] 2020-03-13 04:41
+1

**Comment by waswrongassembled** [comment] 2020-03-13 05:55
+1

**Comment by kietdinh** [comment] 2020-03-16 13:46
+1

**Comment by ffery** [comment] 2020-04-15 13:32
+1

**Comment by chethan-uc** [comment] 2020-10-07 09:58
+1

**Comment by 4ndygu** [comment] 2021-07-21 22:29
+1

**Comment by tumbledwyer** [comment] 2021-11-09 14:45
+1
I have the issue, where I'm trying to do a nested query from logstash using the elasticsearch filter, which only supports query string, not the regular DSL.
I can accomplish this in KQL like this:
`myNestedObject:{ nestedProperty: "The value I'm looking for" }`

**Comment by vaimer** [comment] 2022-09-22 10:21
+1 it will be very useful

**Comment by javanna** [comment] 2022-10-13 10:00
Closing as duplicate of #16551.

**Closed by javanna** 2022-10-13 10:00 UTC
Labels: >feature, :Search/Search, Team:Search

**Comment by mldyh** [comment] 2023-09-06 02:50
+1

**Comment by heidi-holappa** [comment] 2023-11-23 11:02
+1
