### ISSUE TITLE
Suggest not working with custom analyzer

### ISSUE THREAD

**Issue by aslamy** [elastic/elasticsearch#24786] opened 2017-05-19 09:02 UTC
I have created a custom analyzer like: 

{
  "settings": {
    "analysis": {
      "analyzer": {
        "myCustomFilter": {
          "type": "custom",
          "filter": [
            "lowercase",
            "standard",
            "asciifolding",
            "unique"
          ],
          "tokenizer": "standard"
        }
      }
    }
  }

I have to example unique token filter. The unique token filter keeps only unique tokens. but this not working !

**Comment by aslamy** [comment] 2017-05-19 09:03
`{
"settings": {
"analysis": {
"analyzer": {
"myCustomFilter": {
"type": "custom",
"filter": [
"lowercase",
"standard",
"asciifolding",
"unique"
],
"tokenizer": "standard"
}
}
}
}`

**Comment by martijnvg** [comment] 2017-05-19 10:21
Hi @aslamy, we reserve Github for bug reports and feature requests only. Please ask questions like these in the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch) instead. Thank you!

**Comment by aslamy** [comment] 2017-05-19 10:28
But that's a fucking bug.

**Comment by martijnvg** [comment] 2017-05-19 11:14
> But that's a fucking bug.

Please mind your language here. There is no reason you should reply like you did.

Can you provide more details (like we ask in the issue template)? At least minimal productions steps (not just providing index settings), Elasticsearch version and did you see an error or did the unique token filter not behave correctly?

**Comment by clintongormley** [comment] 2017-05-19 11:27
This works as expected:

```
PUT t
{
  "settings": {
    "analysis": {
      "analyzer": {
        "myCustomFilter": {
          "type": "custom",
          "filter": [
            "lowercase",
            "standard",
            "asciifolding",
            "unique"
          ],
          "tokenizer": "standard"
        }
      }
    }
  }
}

POST t/_analyze
{
  "text": "Foo Foo Bar Foo",
  "analyzer": "myCustomFilter"
}
```

outputs:

```
{
  "tokens": [
    {
      "token": "foo",
      "start_offset": 0,
      "end_offset": 3,
      "type": "<ALPHANUM>",
      "position": 0
    },
    {
      "token": "bar",
      "start_offset": 8,
      "end_offset": 11,
      "type": "<ALPHANUM>",
      "position": 1
    }
  ]
}
```

This is not a bug.  Closing. If you're unsure how to use it, then please ask in the forums

**Closed by clintongormley** 2017-05-19 11:27 UTC

**Comment by aslamy** [comment] 2017-05-19 12:28
Of course that working ! I meant this not working with completion API .
