### ISSUE TITLE
Test in :x-pack:plugin:ent-search:qa:full-cluster-restart:javaRestTest failing after fixing its location

### ISSUE THREAD

**Issue by breskeby** [elastic/elasticsearch#104470] opened 2024-01-17 15:35 UTC
### CI Link

https://gradle-enterprise.elastic.co/s/4cthxzdxcvite/tests/task/:x-pack:plugin:ent-search:qa:full-cluster-restart:v8.11.5%23bwcTest/details/org.elasticsearch.xpack.application.FullClusterRestartIT/testBehavioralAnalyticsDataRetention%20%7Bcluster=OLD%7D?top-execution=1

### Repro line

./gradlew :x-pack:plugin:ent-search:qa:full-cluster-restart:bwcTest

### Does it reproduce?

Yes

### Applicable branches

main

### Failure excerpt

org.elasticsearch.client.ResponseException: method [PUT], host [http://[::1]:36129], URI [_application/analytics/oldstuff], status line [HTTP/1.1 400 Bad Request]	
{"error":{"root_cause":[{"type":"status_exception","reason":"error while creating analytics collection [oldstuff]"}],"type":"status_exception","reason":"error while creating analytics collection [oldstuff]","caused_by":{"type":"illegal_argument_exception","reason":"no matching index template found for data stream [behavioral_analytics-events-oldstuff]"}},"status":400}

**Comment by demjened** [comment] 2024-01-18 18:37
@breskeby We're trying to reproduce the error locally but running into some issues. The error message says v8.11.5 which is a nonexistent version. This is confirmed when trying to run the gradle command locally - `v8.11.5#bwcTest` not found the in project, nor in the [repo](https://github.com/search?q=repo%3Aelastic%2Felasticsearch%208.11.5&type=code):
![Screenshot 2024-01-18 at 1 19 51 PM](https://github.com/elastic/elasticsearch/assets/14224983/e9807a06-4a86-43b4-b985-63a810e7daa9)

Could someone from the Delivery/Build team verify if the integration test build configuration is correct? (I reassigned the ticket to the team.)

**Comment by mark-vieira** [comment] 2024-01-18 18:50
> Could someone from the Delivery/Build team verify if the integration test build configuration is correct? (I reassigned the ticket to the team.)

This is because this version disappeared with the release of 8.12.0. I don't think the version is _particularly_ important. You can use 8.12.1 if you want the most recent snapshot version compatible with `main`.

**Comment by demjened** [comment] 2024-01-23 21:33
Not a blocker - main functionality is working, only the integration test is broken. [This PR](https://github.com/elastic/elasticsearch/pull/104463) should disable the broken test, and we'll investigate under [this ticket](https://elasticco.atlassian.net/browse/SEARCH-231).

**Comment by demjened** [comment] 2024-01-26 19:14
[PR](https://github.com/elastic/elasticsearch/pull/104635) to disable the test has been merged. We'll continue investigating why it's broken and restore it, in a separate effort from this issue.

**Closed** 2024-01-26 19:14 UTC
Labels: blocker, :Delivery/Build, >test-failure, Team:Delivery, :EnterpriseSearch/Application, Team:Enterprise Search
