### ISSUE TITLE
Document which analysis components are allowed in normalizers.

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#25427] opened 2017-06-27 12:15 UTC
We should document which analysis components are allowed in normalizers. Maybe a good start would be to give a subset of the ones that can be used and are usually the most useful ones such as the `lowercase` and the `ascii_folding` filters.

**Comment by mayya-sharipova** [comment] 2018-03-16 17:46
cc @elastic/es-search-aggs

**Comment by mayya-sharipova** [comment] 2018-03-16 17:50
Duplicate of https://github.com/elastic/elasticsearch/issues/28605, which is already implemented an merged.

**Closed by mayya-sharipova** 2018-03-16 17:50 UTC
Labels: :Search/Analysis, >docs
