### ISSUE TITLE
Cluster state parsing is too lenient

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#15611] opened 2015-12-22 16:28 UTC
See https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/cluster/metadata/MetaData.java#L1150. If an element is not recognized in a cluster state, it is simply ignored.

**Comment by ywelsch** [comment] 2015-12-22 16:45
This is on purpose, to allow plugins to add custom metadata. If the plugin that added custom metadata is removed, the metadata of that plugin cannot be read anymore. If we were to fail the parsing here, cluster state could not be recovered on startup after uninstalling plugin.

I agree that improvements can be made in this area, just wanted to give an explanation for the current implementation.

**Comment by s1monw** [comment] 2015-12-22 16:47
> I agree that improvements can be made in this area, just wanted to give an explanation for the current implementation.

++

**Comment by bleskes** [comment] 2018-03-20 12:01
Closing as duplicate of https://github.com/elastic/elasticsearch/issues/21471 . The link in the description doesn't work but glimpsing at the current code it seems that the custom metadata is only leniency we have.

**Closed by bleskes** 2018-03-20 12:01 UTC
Labels: :Distributed/Distributed, >bug
