### ISSUE TITLE
Query Template: "Field name [myChild.name] cannot contain '.'

### ISSUE THREAD

**Issue by asaf** [elastic/elasticsearch#14837] opened 2015-11-18 15:26 UTC
Hey,

I have a query template that looks like:

```json
{
  "query": {
    "filtered": {
      "filter": {
        "nested": {
          "path": "myChild",
          "filter": {
            "bool": {
              "must": [
                {
                  "term": {
                    "myChild.name": "{{name}}"
                  }
                },
                .......... more
              ]
            }
          }
        }
      }
    }
  }
}
```

Saving it causes:

```
{"msg":"[mapper_parsing_exception] Field name [myChild.name] cannot contain '.'
```

But running the exact same query not as template works as expected,

What is wrong?

btw this happens with `Elastic Search v2` (works fine with 1.7)

Thanks,

Asaf.

**Comment by clintongormley** [comment] 2015-11-18 18:38
See https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_mapping_changes.html#_field_names_may_not_contain_dots

**Comment by asaf** [comment] 2015-11-18 18:43
@clintongormley 

This is not the case,
The doc contains no dots, it contains nested properties,

I am talking about query templates,

Elastic probably performs "." field validation on the query template too and it restricts the query to be persisted, but from my understanding, the "nested" filter acts like the nested matcher, which as stated requires "." notation,

```
A nested filter behaves much like a nested query, except that it doesn’t accept the score_mode 
parameter. It can be used only in filter context—such as inside a filtered query—and it behaves like any 
other filter: it includes or excludes, but it doesn’t score.
```


Please re-open :)

Thanks.

**Comment by clintongormley** [comment] 2015-11-18 18:58
Ah read way too fast, apologies!

**Comment by clintongormley** [comment] 2015-11-18 19:08
A simpler recreation:

    PUT _search/template/foo
    {
      "query": {
        "match": {
          "foo.bar": "TEXT"
        }
      }
    }

**Comment by asaf** [comment] 2015-11-18 19:17
@clintongormley :+1:

**Comment by MaineC** [comment] 2015-11-25 13:01
From a first look at the code the problem seems to be that on indexing the template query we try to parse it as a regular document which includes trying to create a mapping for it. This fails for the reason @clintongormley mentioned earlier (code that complains: https://github.com/elastic/elasticsearch/blob/debfb84d38e8d24755996032fa2bdd2b81f7068f/core/src/main/java/org/elasticsearch/index/mapper/object/ObjectMapper.java#L262 ).

Not yet sure how to fix this issue though.

**Comment by rjernst** [comment] 2015-11-25 19:20
Why do we index the query template? Is it just for storage (although then I'm confused why it isn't just part of the cluster state)? Can we store it as a blob in a single field instead of using the structure from the query as the document?

**Comment by MaineC** [comment] 2015-11-26 09:33
@rjernst AFAIK it is just for storage (did a bit of digging, the original issue #5921 also suggests that).

> (although then I'm confused why it isn't just part of the cluster state)

No idea. Maybe @clintongormley or @s1monw can comment on that.


> Can we store it as a blob in a single field instead of using the structure from the query as the 
> document?

IMHO that would make more sense than the current implementation.

**Comment by clintongormley** [comment] 2015-11-28 10:17
OK the root cause of this appears to be because indexed search templates can be passed without the outer `template` element (which is undocumented).

If you use the documented syntax:

    PUT _search/template/foo
    {
      "template": {
        "query": {
          "match_all": {}
        }
      }
    }

Then the `.scripts` index contains the following mapping:

    {
      ".scripts": {
        "mappings": {
          "mustache": {
            "properties": {
              "script": {
                "type": "object",
                "enabled": false
              },
              "template": {
                "type": "object",
                "enabled": false
              }
            }
          }
        }
      }
    }

The `query` field is correctly set to `enabled: false`, so nothing in the query is indexed or even parsed.

However, without the outer `template` property:

    PUT _search/template/foo
    {
      "query": {
        "match_all": {}
      }
    }

Then every element in the query generates a field:

    {
      ".scripts": {
        "mappings": {
          "mustache": {
            "properties": {
              "query": {
                "properties": {
                  "match_all": {
                    "type": "object"
                  }
                }
              },
              "script": {
                "type": "object",
                "enabled": false
              },
              "template": {
                "type": "object",
                "enabled": false
              }
            }
          }
        }
      }
    }

So the solution here is to only accept a `template` property for indexed templates, and a `script` property for indexed scripts.

**Comment by clintongormley** [comment] 2015-11-29 11:56
Related to https://github.com/elastic/elasticsearch/issues/13729

**Comment by brwe** [comment] 2015-12-09 17:31
There are two ways to index scripts:

1. `PUT _search/template/foo`
2. `PUT .scripts/mustache/foo`

For the first we could add extra parsing logic somewhere that ensures that we start with "template" only and nothing else is allowed. For the second we would need a dedicated rest endpoint because currently this is just the regular index API that performs no checks whatsoever except for adding the "_default_" mapping here: https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/index/mapper/MapperService.java#L136.

The trouble is that people can still use 2. with the java API and I have no idea how to hack the index API without being yelled at on github when I make the pull request :-)

**Comment by brwe** [comment] 2015-12-10 13:09
Discussed with @clintongormley and we decided to fix this only for the _search/template endpoint and open a separate issue for the index api and discuss there

**Comment by clintongormley** [comment] 2016-02-14 17:30
Related to #16651

**Comment by avalonabecker** [comment] 2016-04-12 14:10
I got the Field name [myChild.name] cannot contain '.' when I forgot to put the "_search" at the end of my URL  - just posting so others might save time on a newbie mistake there.

**Comment by clintongormley** [comment] 2016-05-07 15:37
Closed by https://github.com/elastic/elasticsearch/issues/16651

**Closed by clintongormley** 2016-05-07 15:37 UTC
Labels: :Search Templates, adoptme, bug, low hanging fruit
