### ISSUE TITLE
[CI] ClusterStatsNodesTests.testIngestStats failure on master

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#59174] opened 2020-07-07 16:35 UTC
**Build scan**:
https://gradle-enterprise.elastic.co/s/3rljbxcxeddxq

**Repro line**:
```
./gradlew ':server:test' --tests "org.elasticsearch.action.admin.cluster.stats.ClusterStatsNodesTests.testIngestStats" \
  -Dtests.seed=2B18C0EB83EF536A \
  -Dtests.security.manager=true \
  -Dtests.locale=sq \
  -Dtests.timezone=Asia/Ulan_Bator \
  -Dcompiler.java=14 \
  -Druntime.java=11
```

**Reproduces locally?**:

Yes

**Failure excerpt**:
```
java.lang.IllegalArgumentException: duration cannot be negative, was given [-5167652678572409797]
	at __randomizedtesting.SeedInfo.seed([2B18C0EB83EF536A:B3CC4A8E32729A56]:0)
	at org.elasticsearch.common.unit.TimeValue.<init>(TimeValue.java:51)
	at org.elasticsearch.action.admin.cluster.stats.ClusterStatsNodes$IngestStats.toXContent(ClusterStatsNodes.java:755)
	at org.elasticsearch.common.xcontent.XContentHelper.toXContent(XContentHelper.java:366)
	at org.elasticsearch.common.xcontent.XContentHelper.toXContent(XContentHelper.java:351)
	at org.elasticsearch.action.admin.cluster.stats.ClusterStatsNodesTests.testIngestStats(ClusterStatsNodesTests.java:111)
```

**Comment by dakrone** [comment] 2020-10-06 20:35
I looked into this, and I was not able to reproduce this either on master or 7.x. I also tried hardcoding times to `Long.MAX_VALUE - 1` to see if perhaps there was an adding issue where we were overflowing due to `randomNonNegativeLong()`, but alas, no luck.

With that in mind, I'm going to close this for now and if it reoccurs we can investigate some more.

**Comment by ywangd** [comment] 2021-01-29 05:29
Another one on master https://gradle-enterprise.elastic.co/s/nyaraeqhhvaqe

It is reproducible locally with:
> ./gradlew ':server:test' --tests "org.elasticsearch.action.admin.cluster.stats.ClusterStatsNodesTests.testIngestStats" -Dtests.seed=647182AD53A48B64 -Dtests.security.manager=true -Dtests.locale=es-CO -Dtests.timezone=Pacific/Port_Moresby -Druntime.java=15

Note the build scan is a FIPS job, but the failure has nothing to do with fips. In fact, the I removed `-Dtests.fips.enabled=true` from the above repro line and it still fails locally.

It is seed specific in that if I remove `-Dtests.seed=647182AD53A48B64`, it passes. So I am not going to mute it just yet.

**Closed** 2021-03-18 06:21 UTC
Labels: :Core/Features/Stats, >test-failure, Team:Core/Features
