### ISSUE TITLE
copy_to doesnt work within nested document

### ISSUE THREAD

**Issue by gbhati** [elastic/elasticsearch#24045] opened 2017-04-11 12:04 UTC
**Elasticsearch version**: elasticsearch-5.2.1

**Plugins installed**: [No]

**JVM version**: jdk1.8.0_25

**OS version**: Windows/Red Hat Enterprise Linux Server release 7.3

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 Sample Mapping for replicating the issue

```
PUT my_index
{
   "mappings": {
      "my_type": {
         "properties": {
            "first_name": {
               "type": "text",
               "copy_to": "test.full_name"
            },
            "last_name": {
               "type": "text",
               "copy_to": "test.full_name"
            },
            "test": {                
               "type": "nested",
               "properties": {
                  "test_name":{
                      "type": "text",
                      "copy_to": "test.full_name"       
                  },
                  "full_name": {
                     "type": "text",
                     "store": true
                  }
               }
            }
         }
      }
   }
}
```

Sample data

```
put my_index/my_type/1
{
    "first_name":"first",
    "last_name":"last",
    "test":{
        "test_name":"new"
    }
}
```

Now Output of stored_fields is unexpected

```
            "fields": {
               "test.full_name": [
                  "first",
                  "last"
               ]
            }
```

I expect additional "new" to be also copied to test.full_name. In addition to this problem,  we are also not able to copy data from nested objects to an inner nested object. The only copy_to that is working is copy to root.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by spinscale** [comment] 2017-04-11 13:47
if you use the `include_in_root` flag, this works, see this example

```
PUT my_index
{
   "mappings": {
      "my_type": {
         "properties": {
            "first_name": {
               "type": "text",
               "copy_to": "test.full_name"
            },
            "last_name": {
               "type": "text",
               "copy_to": "test.full_name"
            },
            "test": {                
               "type": "nested",
               "include_in_root": true, 
               "properties": {
                  "test_name":{
                      "type": "text",
                      "copy_to": "test.full_name"       
                  },
                  "full_name": {
                     "type": "text",
                     "store": true
                  }
               }
            }
         }
      }
   }
}

PUT my_index/my_type/1
{
    "first_name":"first",
    "last_name":"last",
    "test":{
        "test_name":"new"
    }
}

GET my_index/my_type/1?stored_fields=test.full_name
```

I am actually unsure, if this is a bug or a feature, I think @martijnvg might be able to help out

**Comment by abeyad** [comment] 2017-04-12 16:33
Assigning to @martijnvg to confirm the behavior of `include_in_root`.  As an aside, it looks like `include_in_root` and `include_in_parent` may be deprecated in favor of `copy_to`: https://github.com/elastic/elasticsearch/issues/12461

**Comment by clintongormley** [comment] 2017-05-26 17:49
Duplicate of https://github.com/elastic/elasticsearch/issues/23077

**Closed by clintongormley** 2017-05-26 17:49 UTC
Labels: :Nested Docs

**Comment by jpv** [comment] 2020-02-01 11:31
I had the same issue "include_in_root": true solved it.
