### ISSUE TITLE
Gradle assemble task builds BWC versions too

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#33581] opened 2018-09-10 19:09 UTC
Today, in both `6.x` and `master`, executing `./gradlew assemble` will run BWC-related tasks such as `:distribution:bwc:next-{bugfix,minor}-snapshot:buildBwcVersion`, which appears to be unnecessary for the ultimate goal of the `assemble` task.

**Comment by rjernst** [comment] 2018-09-10 20:02
This was recently addressed by https://github.com/elastic/elasticsearch/pull/33372. @DaveCTurner are you sure this is still an issue?

**Comment by DaveCTurner** [comment] 2018-09-11 06:09
Apologies, by "Today" I clearly meant "a week ago", and the handful of PR builds I looked at had not picked up #33372. Sorry for the noise.

**Comment by original-brownbear** [comment] 2019-01-07 10:43
This problem seems to be back. With current `master`  (e778abaac58b598c2c9f3d844ed70761b773461b)  I again see the Bwc versions being built for `./gradlew assemble`.

**Comment by original-brownbear** [comment] 2019-01-07 10:43
@atorok can you take another look?

**Comment by atorok** [comment] 2019-01-07 14:40
@original-brownbear I can't reproduce. was `./gradlew assemble` your entire command line  ?

**Comment by original-brownbear** [comment] 2019-01-07 14:59
@atorok I tracked this down (sorta).

If I run the build from my normal zsh shell `./gradlew assemble` no BwC archives are built.
If I run the following script (I have ES checked out in `./build/elasticsearch` relative to the script):

```sh
#!/usr/bin/env bash
cd ./build/elasticsearch && ./gradlew clean assemble
```

it builds the Bwc archives ...
It could be some difference in my bash and zsh environments or so?
Regardless, it's kinda weird this happens :D If you can't reproduce it though, I can take a look. No need to waste your time, this is pretty fringe obviously :)

**Comment by atorok** [comment] 2019-01-07 15:47
`./gradlew clean assemble` will build the  bwc versions. We only short circuit it if `assemble` is the only task on the command line. The reason is that it's too complex to reason about what other tasks might do and if they require bwc versions or not.

**Comment by original-brownbear** [comment] 2019-01-07 18:19
@atorok 

:man_facepalming: my bad => sorry for the noise :)

**Comment by rjernst** [comment] 2019-01-09 01:05
I think we can make this better. I've opened another solution in #37245.

**Closed** 2019-01-09 18:57 UTC
Labels: :Core/Infra/Build, >non-issue, v6.5.0, v7.0.0
