### ISSUE TITLE
[CI] EqlSearchIT testMultiValueFields failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#76632] opened 2021-08-18 00:26 UTC
This reproduced locally for me. The failure seem to be specific to mixed node clusters with 7.10.x or 7.11.x nodes.

**Build scan:**
https://gradle-enterprise.elastic.co/s/7i3e2pqrc5uds/tests/:x-pack:plugin:eql:qa:mixed-node:v7.11.2%23mixedClusterTest/org.elasticsearch.xpack.eql.qa.mixed_node.EqlSearchIT/testMultiValueFields

**Reproduction line:**
`./gradlew ':x-pack:plugin:eql:qa:mixed-node:v7.11.2#mixedClusterTest' -Dtests.class="org.elasticsearch.xpack.eql.qa.mixed_node.EqlSearchIT" -Dtests.method="testMultiValueFields" -Dtests.seed=8C02DAC5D1268002 -Dtests.bwc=true -Dtests.locale=ar-QA -Dtests.timezone=Europe/Busingen -Druntime.java=8`

**Applicable branches:**
7.x

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.eql.qa.mixed_node.EqlSearchIT&tests.test=testMultiValueFields

**Failure excerpt:**
```
java.lang.AssertionError: For query [PROCESS where multiply(pid, 10) == 120]
Response does not match:
                             0: same [116]
                             1: same [117]
                             2: same [118]
                             3: same [119]
expected [2] more entries

  at __randomizedtesting.SeedInfo.seed([8C02DAC5D1268002:85A2465BB331FCF8]:0)
  at org.junit.Assert.fail(Assert.java:88)
  at org.elasticsearch.xpack.eql.qa.mixed_node.EqlSearchIT.assertResponse(EqlSearchIT.java:357)
  at org.elasticsearch.xpack.eql.qa.mixed_node.EqlSearchIT.assertMultiValueFunctionQuery(EqlSearchIT.java:326)
  at org.elasticsearch.xpack.eql.qa.mixed_node.EqlSearchIT.testMultiValueFields(EqlSearchIT.java:169)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at java.lang.Thread.run(Thread.java:748)

```

**Comment by mark-vieira** [comment] 2021-08-18 00:27
I've muted this test in `7.x` for now.

**Comment by astefan** [comment] 2021-08-18 12:59
This might be a duplicate of https://github.com/elastic/elasticsearch/issues/76618, but until I'm sure of it I'll take ownership and keep it open.

**Closed** 2021-08-24 08:12 UTC
Labels: >test-failure, :Query Languages/EQL, Team:QL
