### ISSUE TITLE
[CI] IndexShardIT » testMaybeFlush

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#52223] opened 2020-02-11 17:25 UTC
failed on master:

https://gradle-enterprise.elastic.co/s/izpnat3y374v4

```
expected:<0> but was:<3>
java.lang.AssertionError
: 
expected:<0> but was:<3>
Close stacktrace
at __randomizedtesting.SeedInfo.seed([ACB0D4A252C38F40:2DB52A569EBDD90C]:0)
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:645)
at org.junit.Assert.assertEquals(Assert.java:631)
at org.elasticsearch.index.shard.IndexShardIT.testMaybeFlush(IndexShardIT.java:352)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:566)
at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1754)
at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:942)
at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:978)
at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:992)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:370)
at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:819)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:470)
at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:951)
at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:836)
at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:887)
at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:898)
at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:370)
at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:826)
at java.lang.Thread.run(Thread.java:834)
[2020-02-12T03:56:52,902][INFO ][o.e.i.s.IndexShardIT     ] [testMaybeFlush] before test
[2020-02-12T03:56:52,908][INFO ][o.e.c.m.MetaDataCreateIndexService] [node_s_0] [test] creating index, cause [api], templates [one_shard_index_template, random-soft-deletes-template], shards [1]/[0], mappings []
[2020-02-12T03:56:53,059][INFO ][o.e.c.r.a.AllocationService] [node_s_0] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[test][0]]]).
[2020-02-12T03:56:53,133][INFO ][o.e.c.s.IndexScopedSettings] [node_s_0] [test] updating [index.translog.flush_threshold_size] from [512mb] to [135b]
[2020-02-12T03:56:53,181][INFO ][o.e.c.s.IndexScopedSettings] [node_s_0] [test] updating [index.translog.flush_threshold_size] from [512mb] to [135b]
[2020-02-12T03:56:53,188][INFO ][o.e.c.m.MetaDataMappingService] [node_s_0] [test/1CLpUW3xTsuEeLFtC4nV7g] create_mapping
[2020-02-12T03:56:53,329][INFO ][o.e.i.s.IndexShardIT     ] [testMaybeFlush] after test
[2020-02-12T03:56:53,329][INFO ][o.e.c.m.MetaDataDeleteIndexService] [node_s_0] [test/1CLpUW3xTsuEeLFtC4nV7g] deleting index
```

**Comment by dnhatn** [comment] 2020-02-11 23:23
Relates to https://github.com/elastic/elasticsearch/pull/51905.

**Comment by astefan** [comment] 2020-02-17 14:06
This one failed again today:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_RUNTIME_JAVA=openjdk13,nodes=general-purpose/516/console
https://gradle-enterprise.elastic.co/s/do3zhzqosbde4

and the fix referenced in this issue seems to be in.

Doesn't reproduce for me though.

**Comment by ywelsch** [comment] 2020-03-03 08:16
@dnhatn has added more assertions here, but there haven't been any recent failures. I'll close this for now, but please report and reopen issue on any future failures.

**Comment by tlrx** [comment] 2020-03-25 11:56
This test failed today on `7.x` with a similar assertion error:

```
java.lang.AssertionError: last commit [{translog_uuid=-eXKsvspTWe4_IpuWE2ZJA, history_uuid=Q7T02qpRT3-59zTo-2JICw, local_checkpoint=2, max_seq_no=2, max_unsafe_auto_id_timestamp=-1}]
Expected: <0>
     but: was <3>
	at __randomizedtesting.SeedInfo.seed([1D69D57C6EE18EC5:9C6C2B88A29FD889]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.elasticsearch.index.shard.IndexShardIT.testMaybeFlush(IndexShardIT.java:371)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Build scan: [https://gradle-enterprise.elastic.co/s/i7xtizngehx4u](https://gradle-enterprise.elastic.co/s/i7xtizngehx4u/console-log?task=:server:integTest)

**Comment by ywelsch** [comment] 2020-03-27 13:59
I've not been able to reproduce the failure, but looked a bit at the cause. I think that it might be explained as follows:

- Flush is issued (afterWriteOperation) before global checkpoint is persisted
- This means that if the flush completes before the global checkpoint is persisted, that for the CombinedDeletionPolicy.onCommit(), the new commit is not considered safe
- That also means that when calling updateRetentionPolicy() and subsequently translogDeletionPolicy.setLocalCheckpointOfSafeCommit() this sets a local checkpoint of an older index commit (not the one that was just flushed)
- If we subsequently call translog.sync(), which calls trimUnreferencedReaders(), then getMinReferencedGen() returns an older translog generation for the wrong safe commit.

I think that the problem is that the notion of uncommitted operation is tied to the safe commit now, which in itself can be a bit stale as we're not revisiting what the latest safe commit is after persisting a new global checkpoint. Previously, revisiting this did not make sense as the commit was tied to a fixed translog generation, but with https://github.com/elastic/elasticsearch/pull/51905 this is no longer the case, and the notion of safe commit could be updated when a new global checkpoint is persisted.

**Comment by dnhatn** [comment] 2020-04-01 03:43
We still do not have enough info for this test failure. I've enabled the debug logs of the engine in this test. I am closing this issue again. Please reopen when it fails.

**Comment by gwbrown** [comment] 2020-04-01 20:30
This failed again in 7.x. [Build scan](https://gradle-enterprise.elastic.co/s/iemte3g4p4rxo/tests/kyv2y2z3r4v7k-q3s77yitlygly?open-stacktraces=WzBd), [Jenkins](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob+fast+part1/4268/)

**Comment by williamrandolph** [comment] 2020-04-02 18:38
And again, in 7.x: [Build scan](https://gradle-enterprise.elastic.co/s/uog6w447rdpmu), [Jenkins](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_RUNTIME_JAVA=zulu8,nodes=general-purpose/607/)

**Comment by mayya-sharipova** [comment] 2020-04-03 20:06
And again, in 7.x: [Build scan](https://gradle-enterprise.elastic.co/s/kjzklafae6dii), [Jenkins](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob+fast+part1/4334/console)

**Comment by dimitris-athanasiou** [comment] 2020-04-06 07:49
Ang again, in 7.x: [Build scan](https://gradle-enterprise.elastic.co/s/hlikqhqbmp4t4), [Jenkins](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+release-tests/1101/console)

**Comment by dnhatn** [comment] 2020-04-06 16:57
I am looking at this issue now.

**Comment by dnhatn** [comment] 2020-04-06 19:24
I've opened https://github.com/elastic/elasticsearch/pull/54839.

**Closed** 2020-04-07 15:14 UTC
Labels: :Distributed/Engine, >test-failure
