### ISSUE TITLE
Phrase suggester test in docs fails with wrong score

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#20259] opened 2016-08-31 16:41 UTC
It [failed](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=opensuse/109/console) with the error below and it's not reproducible. Opening an issue hare in case it's a real race condition that affects suggester scoring.

```
Suite: org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT
  1> [2016-08-31 13:58:20,087][INFO ][org.elasticsearch.smoketest] Stash dump on failure [{
  1>   "stash" : {
  2> REPRODUCE WITH: gradle :docs:integTest -Dtests.seed=F5407B0B4DA21C4A -Dtests.class=org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT -Dtests.method="test {yaml=reference/search/suggesters/phrase-suggest/line_86}" -Dtests.security.manager=true -Dtests.locale=id -Dtests.timezone=America/Kentucky/Monticello
  1>     "body" : {
  1>       "_shards" : {
  1>         "total" : 1,
  1>         "successful" : 1,
  1>         "failed" : 0
  1>       },
  1>       "simple_phrase" : [
  1>         {
  1>           "text" : "noble prize",
  1>           "offset" : 0,
  1>           "length" : 11,
  1>           "options" : [
  1>             {
  1>               "text" : "nobel prize",
  1>               "highlighted" : "<em>nobel</em> prize",
  1>               "score" : 0.5962314
  1>             }
  1>           ]
  1>         }
  1>       ]
  1>     }
  1>   }
  1> }]
  1> [2016-08-31 13:58:20,088][ERROR][org.elasticsearch.smoketest] This failing test was generated by documentation starting at reference/search/suggesters/phrase-suggest.asciidoc:line_86. It may include many snippets. See docs/README.asciidoc for an explanation of test generation.
FAILURE 1.93s | DocsClientYamlTestSuiteIT.test {yaml=reference/search/suggesters/phrase-suggest/line_86} <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Failure at [reference/search/suggesters/phrase-suggest:98]: $body didn't match the expected value:
   >                          $body: 
   >                          _shards: 
   >                             failed: same [0]
   >                         successful: same [1]
   >                              total: same [1]
   >                    simple_phrase: 
   >                                  0: 
   >                               length: same [11]
   >                               offset: same [0]
   >                              options: 
   >                                      0: 
   >                              highlighted: same [<em>nobel</em> prize]
   >                                    score: expected [0.40765354] but was [0.5962314]
   >                                     text: same [nobel prize]
   >                                 text: same [noble prize]
   >    at __randomizedtesting.SeedInfo.seed([F5407B0B4DA21C4A:7D1444D1E35E71B2]:0)
   >    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:329)
   >    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:309)
   >    at java.lang.Thread.run(Thread.java:745)
   > Caused by: java.lang.AssertionError: $body didn't match the expected value:
   >                          $body: 
   >                          _shards: 
   >                             failed: same [0]
   >                         successful: same [1]
   >                              total: same [1]
   >                    simple_phrase: 
   >                                  0: 
   >                               length: same [11]
   >                               offset: same [0]
   >                              options: 
   >                                      0: 
   >                              highlighted: same [<em>nobel</em> prize]
   >                                    score: expected [0.40765354] but was [0.5962314]
   >                                     text: same [nobel prize]
   >                                 text: same [noble prize]
   >    at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:84)
   >    at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:76)
   >    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:325)
   >    ... 38 more
```

**Comment by cbuescher** [comment] 2016-09-01 15:51
fyi, I was curious an ran the snippets from https://www.elastic.co/guide/en/elasticsearch/reference/master/search-suggesters-phrase.html manually on a local node running es-alpha5. About half of the time I get a result with  `"score": 0.40765354`, the other times I get `"score": 0.5962314`. I don't have enough knowledge of the inner workings of phrase suggestion scoring but maybe @areek can shed some light on this.

**Comment by jimczi** [comment] 2018-03-19 18:43
cc @elastic/es-search-aggs

**Comment by cbuescher** [comment] 2018-05-18 14:37
I just re-checked this, lost of changes since this was opened. First 74184cb1b08012ee01696723cc29ac33551bd424 seems to have fixed the varying scoring, since then the score has changed multiple times on master and 6.x. I cannot reproduce the original buggy behaviour anymore, so closing.

**Closed by cbuescher** 2018-05-18 14:37 UTC
Labels: :Search/Suggesters, >bug, >docs, >test-failure
