### ISSUE TITLE
Overlap calculations in geo

### ISSUE THREAD

**Issue by eskibars** [elastic/elasticsearch#13190] opened 2015-08-28 20:19 UTC
It would be useful to be able to return the net overlap/disjoint areas on a geo_shape query, so as to determine similarity of the queried shape to the indexed document.

**Comment by Ghost93** [comment] 2016-01-15 20:14
+1

**Comment by clintongormley** [comment] 2016-01-28 13:41
Duplicate of #6616

**Closed by clintongormley** 2016-01-28 13:41 UTC
Labels: :Geo, adoptme, enhancement, high hanging fruit
