### ISSUE TITLE
Explanation of More Like This Query Cannot be Parsed

### ISSUE THREAD

**Issue by algebrei** [elastic/elasticsearch#80256] opened 2021-11-03 09:09 UTC
**Elasticsearch version**: 7.15

**Plugins installed**: []

**JVM version**: 1.8.0_181

**OS version**: Darwin Kernel Version 19.6.0

**Description of the problem including expected versus actual behavior**: The explanation written by the [Validate API](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-validate.html#search-validate) for [More Like This](https://www.elastic.co/guide/en/elasticsearch/reference/7.15/query-dsl-mlt-query.html) queries appears to be ill-formed and cannot be parsed, neither the Lucene query parser or as a [Query String](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#query-dsl-query-string-query) query, contrary to what expected. The parsing exception suggests the issue lies in the phrase slop associated with the disjunctive query.

**Steps to reproduce**:

The issue can be reproduced by following the steps in https://www.elastic.co/guide/en/elasticsearch/reference/current/search-validate.html#_the_rewrite_parameter:
 1. The Validation query:`GET my-index-000001/_validate/query?rewrite=true
{
  "query": {
    "more_like_this": {
      "like": {
        "_id": "2"
      },
      "boost_terms": 1
    }
  }
}`
 2. The response to this Validation query: `{
   "valid": true,
   "_shards": {
      "total": 1,
      "successful": 1,
      "failed": 0
   },
   "explanations": [
      {
         "index": "my-index-000001",
         "valid": true,
         "explanation": "((user:terminator^3.71334 plot:future^2.763601 plot:human^2.8415773 plot:sarah^3.4193945 plot:kyle^3.8244398 plot:cyborg^3.9177752 plot:connor^4.040236 plot:reese^4.7133346 ... )~6) -ConstantScore(_id:2)) #(ConstantScore(_type:_doc))^0.0"
      }
   ]
}`
 3. If one extracts the disjunctive query `((user:terminator^3.71334 plot:future^2.763601 plot:human^2.8415773 plot:sarah^3.4193945 plot:kyle^3.8244398 plot:cyborg^3.9177752 plot:connor^4.040236 plot:reese^4.7133346)~6)` and defines a Query String query accordingly, a parsing exception is thrown:
`{
        "type" : "parse_exception",
        "reason" : "parse_exception: Encountered \" <FUZZY_SLOP> \"~6 \"\" at line 1, column 173.\nWas expecting one of:\n    <AND> ...\n    <OR> ...\n    <NOT> ...\n    \"+\" ...\n    \"-\" ...\n    <BAREOPER> ...\n    \"(\" ...\n    \")\" ...\n    \"*\" ...\n    \"^\" ...\n    <QUOTED> ...\n    <TERM> ...\n    <PREFIXTERM> ...\n    <WILDTERM> ...\n    <REGEXPTERM> ...\n    \"[\" ...\n    \"{\" ...\n    <NUMBER> ...\n    "
      }`

**Comment by cbuescher** [comment] 2021-11-03 18:03
As documented, the "explaination" part of the _validate output shows the detailed explanation of the Lucene query that will be executed. Lucene queries "toString" methods typically print user-readable versions of the query that can be used for human debugging, but they are not per-se intended to be fed back into the system 1 to 1. In your case, I believe the `~6` that throws of the query_string parser represents [the "minimum_should_match" value](https://github.com/apache/lucene/blob/branch_9_0/lucene/core/src/java/org/apache/lucene/search/BooleanQuery.java#L570) of the rewritten query. This can be set as a top-level parameter of `query_string`  in the [Elasticsearch query DSL](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#query-string-top-level-params).
I hope this explanation helps and will close this issue since its not a bug.

**Closed by cbuescher** 2021-11-03 18:03 UTC
Labels: >bug, :Search/Search, Team:Search
