### ISSUE TITLE
[Query] query_string or range wrongly match a string

### ISSUE THREAD

**Issue by PMickael** [elastic/elasticsearch#46859] opened 2019-09-19 10:33 UTC
**Elasticsearch version** `6.4.2`
**Plugins installed**: [`analysis-icu`, `analysis-kuromoji`]
**JVM version**
```bash
openjdk 11 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
```

**OS version** (`4.9.58-xxxx-std-ipv6-64 x86_64 x86_64 x86_64 GNU/Linux`):
**Description of the problem including expected versus actual behavior**:
Range matching error/odd
Wrongly match the term `1fich` with the range `[1970 TO 2018]` with query_string but also with range

**Steps to reproduce**:
```json
PUT test/_doc/1
{
  "url": "1fich"
}

POST test/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "range": {
            "url": {
              "gte": 1970,
              "lte": 2017
            }
          }
        }
      ]
    }
  }
}

POST test/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "query_string": {
            "default_field": "url",
            "query": "[1970 TO 2017]"
          }
        }
      ]
    }
  }
}
```

**Comment by jimczi** [comment] 2019-09-19 10:41
While I understand that it might be unexpected, the range that you provided should match the document. `1fich` is between `1970` and `2017` if we consider them as strings so the fact that it matches is not a bug. We could be less lenient in the range query and throw an error if the provided values are not strings and the target field is a keyword/text but can you explain why you consider that it's an error ?

**Comment by PMickael** [comment] 2019-09-19 11:35
Yes, in query_string I'm partially agree, but not with range function which is not supposed to be string based so trigger an error.
About query string, what sound like more accurate is when its string based matching, it should match string term of each term in the specified range so 1970..2017 as a string

**Comment by gwbrown** [comment] 2019-09-19 15:25
The `range` query does and is intended to work on string (`text`/`keyword`) fields, and when it does so, it uses the same logic as sorting by a string field, which is dictionary-like order (i.e. all strings starting with `a` come before all strings starting with `b`, etc., this pattern holds for numbers in string fields as well). This is working as intended if the field is mapped as text, so I'm going to close this issue.   If we can demonstrate that there is in fact a bug, we can reopen this issue.

**Closed by gwbrown** 2019-09-19 15:25 UTC
Labels: :Search/Search
