### ISSUE TITLE
[CI] RepositoryS3ClientYamlTestSuiteIT failure due to index already existing

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#45336] opened 2019-08-08 14:36 UTC
Build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob+fast+part2/640/console

Build scan: https://gradle-enterprise.elastic.co/s/zi337tn5jozq4/tests/lnddip5cdajhs-s5kswmsl4dtig

Reproduce:

```
./gradlew :plugins:repository-s3:integTestMinioRunner --tests "org.elasticsearch.repositories.s3.RepositoryS3ClientYamlTestSuiteIT.test {yaml=repository_s3/20_repository_permanent_credentials/Snapshot and Restore with repository-s3 using permanent credentials}" -Dtests.seed=7B7F7EB548DDC3C5 -Dtests.security.manager=true -Dtests.locale=haw-US -Dtests.timezone=America/Moncton -Dcompiler.java=12 -Druntime.java=11 -Dtests.rest.blacklist=repository_s3/30_repository_temporary_credentials/*,repository_s3/40_repository_ec2_credentials/*,repository_s3/50_repository_ecs_credentials/*
```

Failure:

```
java.lang.AssertionError: Failure at [repository_s3/20_repository_permanent_credentials:231]: expected [2xx] status code but api [snapshot.restore] returned [500 Internal Server Error] [{"error":{"root_cause":[{"type":"snapshot_restore_exception","reason":"[repository_permanent:snapshot-two/yakZmp42RJynf5AU_EB8MA] cannot restore index [docs] because an open index with same name already exists in the cluster. Either close or delete the existing index or restore the index under a different name by providing a rename pattern and replacement name","stack_trace":"SnapshotRestoreException[[repository_permanent:snapshot-two/yakZmp42RJynf5AU_EB8MA] cannot restore index [docs] because an open index with same name already exists in the cluster. Either close or delete the existing index or restore the index under a different name by providing a rename pattern and replacement name]\n\tat org.elasticsearch.snapshots.RestoreService$1.validateExistingIndex(RestoreService.java:444)\n\tat org.elasticsearch.snapshots.RestoreService$1.execute(RestoreService.java:294)\n\tat org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47)\n\tat org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:697)\n\tat org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:319)\n\tat org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:214)\n\tat org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:151)\n\tat org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)\n\tat org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)\n\tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:699)\n\tat org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252)\n\tat org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\n"}],"type":"snapshot_restore_exception","reason":"[repository_permanent:snapshot-two/yakZmp42RJynf5AU_EB8MA] cannot restore index [docs] because an open index with same name already exists in the cluster. Either close or delete the existing index or restore the index under a different name by providing a rename pattern and replacement name","stack_trace":"SnapshotRestoreException[[repository_permanent:snapshot-two/yakZmp42RJynf5AU_EB8MA] cannot restore index [docs] because an open index with same name already exists in the cluster. Either close or delete the existing index or restore the index under a different name by providing a rename pattern and replacement name]\n\tat org.elasticsearch.snapshots.RestoreService$1.validateExistingIndex(RestoreService.java:444)\n\tat org.elasticsearch.snapshots.RestoreService$1.execute(RestoreService.java:294)\n\tat org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47)\n\tat org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:697)\n\tat org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:319)\n\tat org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:214)\n\tat org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:151)\n\tat org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)\n\tat org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)\n\tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:699)\n\tat org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252)\n\tat org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\n"},"status":500}]Open stacktrace
Caused by: java.lang.AssertionError: expected [2xx] status code but api [snapshot.restore] returned [500 Internal Server Error] [{"error":{"root_cause":[{"type":"snapshot_restore_exception","reason":"[repository_permanent:snapshot-two/yakZmp42RJynf5AU_EB8MA] cannot restore index [docs] because an open index with same name already exists in the cluster. Either close or delete the existing index or restore the index under a different name by providing a rename pattern and replacement name","stack_trace":"SnapshotRestoreException[[repository_permanent:snapshot-two/yakZmp42RJynf5AU_EB8MA] cannot restore index [docs] because an open index with same name already exists in the cluster. Either close or delete the existing index or restore the index under a different name by providing a rename pattern and replacement name]\n\tat org.elasticsearch.snapshots.RestoreService$1.validateExistingIndex(RestoreService.java:444)\n\tat org.elasticsearch.snapshots.RestoreService$1.execute(RestoreService.java:294)\n\tat org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47)\n\tat org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:697)\n\tat org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:319)\n\tat org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:214)\n\tat org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:151)\n\tat org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)\n\tat org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)\n\tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:699)\n\tat org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252)\n\tat org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\n"}],"type":"snapshot_restore_exception","reason":"[repository_permanent:snapshot-two/yakZmp42RJynf5AU_EB8MA] cannot restore index [docs] because an open index with same name already exists in the cluster. Either close or delete the existing index or restore the index under a different name by providing a rename pattern and replacement name","stack_trace":"SnapshotRestoreException[[repository_permanent:snapshot-two/yakZmp42RJynf5AU_EB8MA] cannot restore index [docs] because an open index with same name already exists in the cluster. Either close or delete the existing index or restore the index under a different name by providing a rename pattern and replacement name]\n\tat org.elasticsearch.snapshots.RestoreService$1.validateExistingIndex(RestoreService.java:444)\n\tat org.elasticsearch.snapshots.RestoreService$1.execute(RestoreService.java:294)\n\tat org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47)\n\tat org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:697)\n\tat org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:319)\n\tat org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:214)\n\tat org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:151)\n\tat org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)\n\tat org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)\n\tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:699)\n\tat org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252)\n\tat org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\n"},"status":500}]Open stacktrace
[2019-08-08T09:04:23,113][INFO ][o.e.r.s.RepositoryS3ClientYamlTestSuiteIT] [test] [yaml=repository_s3/20_repository_permanent_credentials/Snapshot and Restore with repository-s3 using permanent credentials] before test
[2019-08-08T09:04:25,473][WARN ][o.e.c.RestClient         ] [test] request [PUT http://[::1]:38473/_bulk?refresh=true&error_trace=true] returned 1 warnings: [299 Elasticsearch-8.0.0-SNAPSHOT-78e35c2c3df3450ec33348cf8614e26665009d03 "[types removal] Specifying types in bulk requests is deprecated."]
[2019-08-08T09:05:01,606][INFO ][o.e.r.s.RepositoryS3ClientYamlTestSuiteIT] [test] Stash dump on test failure [{
  "stash" : {
    "body" : {
      "error" : {
        "root_cause" : [
          {
            "type" : "snapshot_restore_exception",
            "reason" : "[repository_permanent:snapshot-two/yakZmp42RJynf5AU_EB8MA] cannot restore index [docs] because an open index with same name already exists in the cluster. Either close or delete the existing index or restore the index under a different name by providing a rename pattern and replacement name",
            "stack_trace" : "SnapshotRestoreException[[repository_permanent:snapshot-two/yakZmp42RJynf5AU_EB8MA] cannot restore index [docs] because an open index with same name already exists in the cluster. Either close or delete the existing index or restore the index under a different name by providing a rename pattern and replacement name]
	at org.elasticsearch.snapshots.RestoreService$1.validateExistingIndex(RestoreService.java:444)
	at org.elasticsearch.snapshots.RestoreService$1.execute(RestoreService.java:294)
	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47)
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:697)
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:319)
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:214)
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:151)
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:699)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
"
          }
        ],
        "type" : "snapshot_restore_exception",
        "reason" : "[repository_permanent:snapshot-two/yakZmp42RJynf5AU_EB8MA] cannot restore index [docs] because an open index with same name already exists in the cluster. Either close or delete the existing index or restore the index under a different name by providing a rename pattern and replacement name",
        "stack_trace" : "SnapshotRestoreException[[repository_permanent:snapshot-two/yakZmp42RJynf5AU_EB8MA] cannot restore index [docs] because an open index with same name already exists in the cluster. Either close or delete the existing index or restore the index under a different name by providing a rename pattern and replacement name]
	at org.elasticsearch.snapshots.RestoreService$1.validateExistingIndex(RestoreService.java:444)
	at org.elasticsearch.snapshots.RestoreService$1.execute(RestoreService.java:294)
	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47)
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:697)
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:319)
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:214)
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:151)
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:699)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
"
      },
      "status" : 500
    }
  }
}]
```

This does seem a bit similar to https://github.com/elastic/elasticsearch/issues/32458

**Comment by original-brownbear** [comment] 2019-08-14 12:16
So this is a really strange state to be in:

```
[2019-08-08T12:04:23,625][INFO ][o.e.c.m.MetaDataCreateIndexService] [integTestMinio-0] [docs] creating index, cause [auto(bulk api)], templates [], shards [1]/[1], mappings []
[2019-08-08T12:04:24,650][INFO ][o.e.c.m.MetaDataMappingService] [integTestMinio-0] [docs/O1dpyDjUTn2l9OIFm49v-A] create_mapping [doc]
[2019-08-08T12:04:25,812][INFO ][o.e.s.SnapshotsService   ] [integTestMinio-0] snapshot [repository_permanent:snapshot-one/gkSS10brSEycokZvWD4Uug] started
[2019-08-08T12:04:26,263][INFO ][o.e.s.SnapshotsService   ] [integTestMinio-0] snapshot [repository_permanent:snapshot-one/gkSS10brSEycokZvWD4Uug] completed with state [SUCCESS]
[2019-08-08T12:04:26,689][INFO ][o.e.s.SnapshotsService   ] [integTestMinio-0] snapshot [repository_permanent:snapshot-two/yakZmp42RJynf5AU_EB8MA] started
[2019-08-08T12:04:29,655][INFO ][o.e.s.SnapshotsService   ] [integTestMinio-0] snapshot [repository_permanent:snapshot-two/yakZmp42RJynf5AU_EB8MA] completed with state [SUCCESS]
[2019-08-08T12:04:30,246][INFO ][o.e.c.m.MetaDataDeleteIndexService] [integTestMinio-0] [docs/O1dpyDjUTn2l9OIFm49v-A] deleting index
[2019-08-08T12:05:01,566][WARN ][o.e.s.RestoreService     ] [integTestMinio-0] [snapshot-two/yakZmp42RJynf5AU_EB8MA] failed to restore snapshot
org.elasticsearch.snapshots.SnapshotRestoreException: [repository_permanent:snapshot-two/yakZmp42RJynf5AU_EB8MA] cannot restore index [docs] because an open index with same name already exists in the cluster. Either close or delete the existing index or restore the index under a different name by providing a rename pattern and replacement name
	at org.elasticsearch.snapshots.RestoreService$1.validateExistingIndex(RestoreService.java:444) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.snapshots.RestoreService$1.execute(RestoreService.java:294) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:697) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:319) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:214) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:151) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:699) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[2019-08-08T12:05:06,747][DEBUG][o.e.a.a.c.s.r.RestoreClusterStateListener] [integTestMinio-0] restore of [snapshot-two/yakZmp42RJynf5AU_EB8MA] completed
[2019-08-08T12:05:06,751][INFO ][o.e.r.RepositoriesService] [integTestMinio-0] delete repository [repository_permanent]
[2019-08-08T12:05:06,788][INFO ][o.e.c.m.MetaDataDeleteIndexService] [integTestMinio-0] [docs/T9_1gwFJQo--MAIrttMetQ] deleting index

```

We delete the index which looks like it worked out, no error there.
The we log a failed restore operation but also log this:

```
[2019-08-08T12:05:06,747][DEBUG][o.e.a.a.c.s.r.RestoreClusterStateListener] [integTestMinio-0] restore of [snapshot-two/yakZmp42RJynf5AU_EB8MA] completed
```

This is logged from a cluster state update listener for the restore that should not be created for a failed restore. Also in the next step the index uuid for `docs` has in fact changed when it is deleted again. Almost seems like the restore was executed twice for some reason with one restore succeeding and one failing and the failing one being used for the REST response. Looking into it ...

**Comment by original-brownbear** [comment] 2019-09-10 21:28
Closing this as duplicate of https://github.com/elastic/elasticsearch/issues/46091 ... same issue, except that the restore operation was rerun as a result of slowness. For now we should be good here with the higher timeout and CI adjustments anyway.

**Closed by original-brownbear** 2019-09-10 21:28 UTC
Labels: :Distributed/Snapshot/Restore, >test-failure
