### ISSUE TITLE
Cannot pass custom HTTPClient to elasticsearch.Config ...anymore?

### ISSUE THREAD

**Issue by ORESoftware** [elastic/elasticsearch#102780] opened 2023-11-29 19:53 UTC
### Elasticsearch Version

8.11.1

### Java Version

_bundled_

### OS Version

macos

### Problem Description

ummm so:

<img width="568" alt="Screen Shot 2023-11-29 at 2 50 39 PM" src="https://github.com/elastic/elasticsearch/assets/11139560/7663af10-db67-40f6-9522-8a054938b034">

```golang
esClient, err := elasticsearch.NewClient(elasticsearch.Config{
		HTTPClient: httpClient,  // here
		Addresses: []string{
			conf.GetConf().ES_FULL_URL,
		},
	})
```

we cannot pass a custom HTTP Client anymore?

### Steps to Reproduce

see code

**Comment by williamrandolph** [comment] 2023-11-29 22:16
This looks like an issue with the Elasticsearch go client rather than the Elasticsearch server, and it seems like a usage question. Questions about client usage belong on our [discussion forums](https://discuss.elastic.co) or our [community slack channel](https://elasticstack.slack.com/). (I suggest including the version of the client where this code worked as intended.)

If you're curious about the source code for the Go client, it's here: https://github.com/elastic/go-elasticsearch/

Since this issue is related to Elasticsearch client code rather than Elasticsearch application code, and appears to be a usage question, I hope you understand if I close it here.

**Closed by williamrandolph** 2023-11-29 22:16 UTC
Labels: >bug, needs:triage
