### ISSUE TITLE
NoSuchFileException installing plugin in batch mode

### ISSUE THREAD

**Issue by darrenmoen** [elastic/elasticsearch#49373] opened 2019-11-20 12:36 UTC
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 7.3.2, Build: oss/tar/1c1faf1/2019-09-06T14:40:30.409026Z, JVM: 11

**Plugins installed**: []
None

**JVM version** (`java -version`):
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux centos7 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. Download latest readonlyrest plugin for Elasticsearch
 2. Install the plugin, specifying **--batch**
 3. Installation fails, see log below

Note:
 - the plugin installs fine without '--batch', but I need that option to install the plugin in a non-interactive mode.
 - this used to work fine with Elasticsearch 6.8.x with the relevant readonlyrest plugin

**Provide logs (if relevant)**:
```
./bin/elasticsearch-plugin install --verbose --batch file:////home/vagrant/readonlyrest-1.18.8_es7.3.2.zip 

-> Downloading file:////home/vagrant/readonlyrest-1.18.8_es7.3.2.zip
Retrieving zip from file:////home/vagrant/readonlyrest-1.18.8_es7.3.2.zip
- Plugin information:
Name: readonlyrest
Description: Safely expose Elasticsearch REST API
Version: 1.18.8
Elasticsearch Version: 7.3.2
Java Version: 1.8
Native Controller: false
Extended Plugins: []
 * Classname: tech.beshu.ror.es.ReadonlyRestPlugin
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.io.FilePermission /proc/sys/net/core/somaxconn#plus read
* java.io.FilePermission <<ALL FILES>> read
* java.lang.RuntimePermission accessClassInPackage.sun.misc
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission getClassLoader
* java.lang.RuntimePermission setContextClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.net.SocketPermission * connect,accept,resolve
* java.security.SecurityPermission getProperty.ssl.KeyManagerFactory.algorithm
* java.util.PropertyPermission * read,write
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
Exception in thread "main" java.nio.file.NoSuchFileException: /home/vagrant/elasticsearch/plugins/readonlyrest/plugin-security.policy
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.setMode(UnixFileAttributeViews.java:254)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.setPermissions(UnixFileAttributeViews.java:276)
	at java.base/java.nio.file.Files.setPosixFilePermissions(Files.java:2079)
	at org.elasticsearch.plugins.InstallPluginCommand.setFileAttributes(InstallPluginCommand.java:938)
	at org.elasticsearch.plugins.InstallPluginCommand.access$000(InstallPluginCommand.java:122)
	at org.elasticsearch.plugins.InstallPluginCommand$1.visitFile(InstallPluginCommand.java:848)
	at org.elasticsearch.plugins.InstallPluginCommand$1.visitFile(InstallPluginCommand.java:842)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2724)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2796)
	at org.elasticsearch.plugins.InstallPluginCommand.movePlugin(InstallPluginCommand.java:842)
	at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:818)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:785)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:231)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:216)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
```

**Comment by darrenmoen** [comment] 2019-11-20 17:35
This is/was some sort of a permissions issue. Elasticsearch is installed in a location (/home/vagrant) that is shared via Vagrant and even though it has the necessary OS permissions it doesn't seem to work in batch mode.
When I moved Elasticsearch to a non-shared location the plugin installed fine.

**Comment by rjernst** [comment] 2019-12-17 23:06
I was not able to reproduce this. Indeed it seems like some permission issue on your end. If you are able to reproduce with exact steps I'm happy to investigate further, but until then I hope you don't mind that I close this issue.

```
[~/Downloads/elasticsearch-7.3.2] ➜  ./bin/elasticsearch-plugin install --batch file:///Users/rjernst/Downloads/readonlyrest-1.18.9_es7.3.2.zip
-> Downloading file:///Users/rjernst/Downloads/readonlyrest-1.18.9_es7.3.2.zip
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.io.FilePermission /proc/sys/net/core/somaxconn#plus read
* java.io.FilePermission <<ALL FILES>> read
* java.lang.RuntimePermission accessClassInPackage.sun.misc
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission getClassLoader
* java.lang.RuntimePermission setContextClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.net.SocketPermission * connect,accept,resolve
* java.security.SecurityPermission getProperty.ssl.KeyManagerFactory.algorithm
* java.util.PropertyPermission * read,write
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
-> Installed readonlyrest
```

**Closed by rjernst** 2019-12-17 23:06 UTC
Labels: :Core/Infra/Plugins
