### ISSUE TITLE
IllegalStateExceptions caused by JsonParseExceptions should return 4xx status codes

### ISSUE THREAD

**Issue by kderusso** [elastic/elasticsearch#112296] opened 2024-08-28 17:19 UTC
### Elasticsearch Version

Latest main

### Java Version

_bundled_

### OS Version

Serverless and cloud

### Problem Description

Invalid Json that results in an `IllegalStateException` when parsing return 500 status codes and should return 4xx status codes as this indicates invalid output. 

This issue is similar to https://github.com/elastic/elasticsearch/issues/111542 but slightly different as that issue is due to an EOF exception. 

### Steps to Reproduce

Use the following command to reproduce: 

```
curl localhost:9200/_search -H "Content-Type: application/json" -d '{ "query": { "match": { "foo": [ { "bar": { "baz": 1 }} ] }}'
```

The curl response is: 
```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_state_exception",
        "reason": "Can't get text on a START_ARRAY at 1:32"
      }
    ],
    "type": "illegal_state_exception",
    "reason": "Can't get text on a START_ARRAY at 1:32"
  },
  "status": 500
}
```

**Comment by rjernst** [comment] 2024-08-28 19:35
This looks like a duplicate of https://github.com/elastic/elasticsearch/issues/111542

**Comment by kderusso** [comment] 2024-08-28 19:49
@rjernst I added a new bug because the proposed fix PR specifically catches an EOF Exception, whereas an IllegalStateException is thrown here.

**Comment by rjernst** [comment] 2024-08-28 23:54
Thanks @kderusso, I see the distinction now. However, looking at this more, I do not think it is a bug in the json parser. The parser is at an open array token, but the match query asked to parse the current object. It looks like a bug in match query, it should not call `parser.objectText()`, but instead throw its own parse exception explaining what state it expected (ie, a json object). I think this is labeled correctly for the search team, so I'll leave it to them to decide how to handle it.

**Comment by javanna** [comment] 2024-08-29 14:39
I relabelled based on the latest explanation that the query parser should be updated.

**Closed** 2024-09-11 14:15 UTC
Labels: >bug, Team:Search Relevance, :Search Relevance/Search
