### ISSUE TITLE
why keyword typed field`s Aggregation consume fielddata memory

### ISSUE THREAD

**Issue by bigstar119** [elastic/elasticsearch#41840] opened 2019-05-06 09:12 UTC
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 5.6.5, Build: 6a37571/2017-12-04T07:50:10.466Z, JVM: 1.8.0_141
**Plugins installed**: [no]

**JVM version** (`java -version`):
java version "1.8.0_141"
Java(TM) SE Runtime Environment (build 1.8.0_141-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.141-b15, mixed mode)
**OS version** (`uname -a` if on a Unix-like system):
CentOS Linux release 7.3.1611 (Core) X64
**Description of the problem including expected versus actual behavior**:
I do some Aggregation operation on a keyword typed field.because keyword typed field`s sort/Aggregation use doc_values, so
the fielddata will not increase. but fielddata memory is increased  a lot! why?
and when i use _forcemerge cmd like below:
curl -X POST 'http://10.10.105.50:9200/mstest20190506/_forcemerge?max_num_segments=1'
after forcemerge finished,i redo Aggregation operation on the keyword  typed field, this time fielddata never increased! why?

in my test max_num_segments only set to 1 ,after forcemerge,redo Aggregation operation on the keyword  typed field fielddata never increased
is _forcemerge?max_num_segments=1 do any special things caused this ?

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.create index and mapping
 curl -XPUT 'http://10.10.105.50:9200/mstest20190506 -d
 {
   "settings": {
     "index.translog.durability": "async",
     "index.translog.sync_interval": "120s",
     "refresh_interval": "30s",
     "number_of_shards": 8,
     "number_of_replicas": 1
   },
   "mappings": {
     "ph_http_list_tab": {
       "properties": {
         "title": {
           "type": "text",
           "fielddata": true
         },
         "keyword": {
           "type": "keyword"
         }
       }
     }
   }
 }
 2.insert some data
    mstest20190506
    size: 2.73Gi (5.45Gi)
    docs: 2,931,888 (5,769,392)
 3.do Aggregation operation on a keyword typed field(keyword),and lookup fielddata memory(fm)
curl -X POST 'http://10.10.105.50:9200/mstest20190506/ph_http_list_tab/_search
{
  "size": 0,
  "aggs": {
    "keyword_aggs": {
      "terms": {
        "field": "keyword"
      }
    }
  }
}
[es@hadoop-3 indices]$ curl -X GET "http://10.10.105.50:9200/_cat/nodes?v&h=name,port,sc,sm,fm,qcm,rcm,siwm,svmm,sfbm,hc,hm,hp,rp,scc,so,scti,sfc,sqc,sqti,scrcc,mc,iic,idc,gc,load_15m,cs"
name   port sc      sm      fm qcm   rcm siwm svmm sfbm    hc    hm hp rp scc so  scti sfc sqc sqti scrcc mc iic idc gc load_15m cs
node-3 9300 68 456.7mb   1.2mb  0b   3kb   0b   0b   0b 1.4gb 1.9gb 72 88   0  0 19.9m   0   0   1m     1  0   0   0  0     2.07 0b
node-1 9300 57 458.8mb 935.1kb  0b 2.2kb   0b   0b   0b 1.4gb 1.9gb 73 90   0  0 17.9m   0   0   1m     1  0   0   0  0     0.63 0b
node-2 9300 57 548.8mb 301.2kb  0b  785b   0b   0b   0b 1.1gb 1.9gb 58 89   0  0   22m   0   0 1.3m     1  0   0   0  0     1.33 0b
[es@hadoop-3 indices]$ curl -X GET "http://10.10.105.50:9200/_cat/fielddata?v"
id                     host         ip           node   field      size
3l1CfRtPR_SCBnyIChasaw 10.10.105.50 10.10.105.50 node-1 keyword 935.1kb
-f1o6kzcS9uelICQMzpxaQ 10.10.125.54 10.10.125.54 node-3 keyword   1.2mb
APuxDzzaQjSZtIsW4qUCaQ 10.10.125.50 10.10.125.50 node-2 keyword 301.2kb
4.forcemerge and do agg operate again
4-1.forcemerge
curl -X POST 'http://10.10.105.50:9200/mstest20190506/_forcemerge?max_num_segments=1'
4-2.do agg operate
curl -X POST 'http://10.10.105.50:9200/mstest20190506/ph_http_list_tab/_search -d
{
  "size": 0,
  "aggs": {
    "keyword_aggs": {
      "terms": {
        "field": "keyword"
      }
    }
  }
}
4-3.ookup fielddata memory(fm)
[es@hadoop-3 indices]$ curl -X GET "http://10.10.105.50:9200/_cat/nodes?v&h=name,port,sc,sm,fm,qcm,rcm,siwm,svmm,sfbm,hc,hm,hp,rp,scc,so,scti,sfc,sqc,sqti,scrcc,mc,iic,idc,gc,load_15m,cs"
name   port sc      sm fm qcm   rcm siwm svmm sfbm    hc    hm hp rp scc so  scti sfc sqc sqti scrcc mc iic idc gc load_15m cs
node-3 9300 11 456.6mb 0b  0b 1.5kb   0b   0b   0b 1.2gb 1.9gb 63 88   0  0 19.9m   0   0   1m     1  0   0   0  0     2.02 0b
node-1 9300 10 458.7mb 0b  0b 1.5kb   0b   0b   0b 1.2gb 1.9gb 66 91   0  0 17.9m   0   0   1m     1  0   0   0  0     0.55 0b
node-2 9300 11 548.8mb 0b  0b   3kb   0b   0b   0b 1.4gb 1.9gb 76 89   0  0   22m   0   0 1.3m     1  0   0   0  0     1.28 0b
[es@hadoop-3 indices]$ curl -X GET "http://10.10.105.50:9200/_cat/fielddata?v"
id                     host         ip           node   field   size
APuxDzzaQjSZtIsW4qUCaQ 10.10.125.50 10.10.125.50 node-2 keyword   0b
3l1CfRtPR_SCBnyIChasaw 10.10.105.50 10.10.105.50 node-1 keyword   0b
-f1o6kzcS9uelICQMzpxaQ 10.10.125.54 10.10.125.54 node-3 keyword   0b
**Provide logs (if relevant)**:

**Comment by albertzaharovits** [comment] 2019-05-06 15:13
@bigstar119 Thank you for taking the time to open an issue. 
However, I'm having trouble replicating your issue at step 3. My `_cat/fielddata` returns 0b for the keyword field. After adding a few docs and running aggs on both fields I still get `0b` in the fielddata stats.

```
curl -XPUT 'http://localhost:9200/mstest20190506' -d'
{
"settings": {
"index.translog.durability": "async",
"index.translog.sync_interval": "120s",
"refresh_interval": "30s",
"number_of_shards": 8,
"number_of_replicas": 1
},
"mappings": {
"ph_http_list_tab": {
"properties": {
"title": {
"type": "text",
"fielddata": true
},
"keyword": {
"type": "keyword"
}
}
}
}
}
'
```

```
curl -X PUT "http://localhost:9200/mstest20190506/ph_http_list_tab/1" -d'
{
  "title": "title one 1",
  "keyword": "one"
}
'
```
```
curl -X PUT "http://localhost:9200/mstest20190506/ph_http_list_tab/2" -d'
{
  "title": "title two 2",
  "keyword": "two"
}
'
```
```
curl -X PUT "http://localhost:9200/mstest20190506/ph_http_list_tab/3" -d'
{
  "title": "title three 3",
  "keyword": "three"
}
'
```
```
 curl -X POST 'http://localhost:9200/mstest20190506/ph_http_list_tab/_search?pretty' -d'
{
"size": 0,
"aggs": {
"keyword_aggs": {
"terms": {
"field": "keyword"
}
}
}
}'
```
```
curl -X POST 'http://localhost:9200/mstest20190506/ph_http_list_tab/_search?pretty' -d'
{
"size": 0,
"aggs": {
"keyword_aggs": {
"terms": {
"field": "title"
}
}
}
}'
```
```
curl -X GET "http://localhost:9200/_cat/fielddata?v"
id                     host      ip        node    field    size
nVddB4SqScaLIKyN5zXR5Q 127.0.0.1 127.0.0.1 nVddB4S title   1.5kb
nVddB4SqScaLIKyN5zXR5Q 127.0.0.1 127.0.0.1 nVddB4S keyword    0b
```

Can you please provide us with a minimal set of reproducible cmds that would output non-zero fielddata size for the `keyword` type?

**Comment by jimczi** [comment] 2019-05-06 16:43
@bigstar119, this memory usage is due to global ordinals that elasticsearch builds on top of doc values for keyword fields. See https://github.com/elastic/elasticsearch/issues/17472. We already have an open [issue](https://github.com/elastic/elasticsearch/issues/37092) to document this behavior so I hope you don't mind if I close this one.

**Closed by jimczi** 2019-05-06 16:43 UTC
Labels: :Analytics/Aggregations
