### ISSUE TITLE
Since Elasticsearch 6.1.0 environment variable substitutions in lists do not work

### ISSUE THREAD

**Issue by vbohata** [elastic/elasticsearch#27926] opened 2017-12-20 14:13 UTC
In elasticsearch 6.1.0 and 6.1.1 I can not use variable substitutions for x-pack related configuration in elasticsearch. Also mentioned here: https://discuss.elastic.co/t/x-pack-6-1-0-does-not-handle-variable-substitutions/111953
`
xpack:
  security:
    authc:
      realms:
          ssl:
            certificate_authorities: [ "${ELASTICSEARCH_CONFIG_PATH}/certs/myca.crt" ]
`
I am receiving:
`java.nio.file.NoSuchFileException: /app/volumes/config/${ELASTICSEARCH_CONFIG_PATH}/certs/myca.crt`
Last known working version is 6.0.1. I am quite surprised this bug passed release testing cycle so I tried to find if this is a feature but it seems it is not.

**Comment by jasontedor** [comment] 2017-12-20 14:24
On its face this looks like an X-Pack issue which we do not handle here as this is for open source Elasticsearch only. However, this is a core feature implemented in open source Elasticsearch.

Have you set `ELASTICSEARCH_CONFIG_PATH`? What does 

```
$ echo $ELASTICSEARCH_CONFIG_PATH
```

show? Are you sure that you exported the environment variable? If you start the process (suspend it before it fails) and get its pid, does `/proc/<PID>/environ` show that environment variable as being exposed to Elasticsearch?

Are you sure that you did not mean `ES_CONF_PATH`?

> I am quite surprised this bug passed release testing cycle so I tried to find if this is a feature but it seems it is not.

I am not sure what this mean. Bugs happen. So does user error. Let's figure it out together.

**Comment by vbohata** [comment] 2017-12-20 14:45
I run ES in docker. I use my entrypoint script which exports ELASTICSEARCH_CONFIG_PATH variable before starting elasticsearch. I know the variable is exported (even see it in environ). To fix the issue I just need to build the docker image with older ES - 6.0.1 (not 6.1.0 or 6.1.1). The issue can be easily replicated by very simple installation of elasticsearch + x-pack without the docker. I do not know if this is elasticsearch or x-pack problem or their integration issue, but in pure elasticsearch var substition works (for example for path.data).

> I am not sure what this mean. Bugs happen. So does user error. Let's figure it out together.

I wanted to say it looked like a feature for the first time - no one reported it, I expected a lot of people will be affected by this.

**Comment by jasontedor** [comment] 2017-12-20 14:50
Would you share a Dockerfile including entrypoint and reproduction of this issue please?

**Comment by jasontedor** [comment] 2017-12-21 03:34
I want to help you but this is too far from a useable reproduction. For example, you are trying to switch to the `elastic` user yet you never created this user. Yes, I could do this, but this is the Nth hurdle in trying to get a working reproduction from what you've provided where now `N` is too large (I do not know your base image but `gosu` is not installed, `wget` is not installed, you have referenced several scripts in the entrypoint that are not provided here, etc. (really, there's more)). I need to put this back on you: please provide a simple reproduction that I can use to debug this. It should not take me more than a few minutes from what you provide to have a working reproduction of the issue that I can iterate on.

**Comment by tvernum** [comment] 2017-12-21 04:31
I can reproduce, it seems to be exclusively a problem with array settings, so my guess is that it's a by-product of #26878

In 6.0.1 running with this config file:
```
discovery.zen.ping.unicast.hosts: [ "${THIS_DOES_NOT_EXIST}" ]
```
would fail to start with:
```
Exception in thread "main" java.lang.IllegalArgumentException: Could not resolve placeholder 'THIS_DOES_NOT_EXIST'
```

In 6.1, it starts, but logs:
```
][WARN ][o.e.d.z.UnicastZenPing   ] failed to resolve host [${THIS_DOES_NOT_EXIST}]
```

**Comment by tvernum** [comment] 2017-12-21 04:47
It seems to have been a somewhat consious decision in #26878
https://github.com/elastic/elasticsearch/pull/26878/files#diff-ec9e18970c4ce90d89639c46bb07218eR1206

Assigning to @s1monw to comment.

**Comment by jasontedor** [comment] 2017-12-22 02:24
Thanks for triaging this one @tvernum.

Thanks for the report @vbohata, no further action is needed from you, we will take it from here.

**Comment by hatdropper1977** [comment] 2018-01-04 21:13
@jasontedor thank you.  I will wait until this is fixed to upgrade.

**Closed** 2018-01-10 17:08 UTC
Labels: :Settings, bug
