### ISSUE TITLE
Two consecutive failures due to Gradle Test Executor failing

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#44553] opened 2019-07-18 11:11 UTC
FAILURE elastic/elasticsearch#7.3 de86c2a EAR - 20190718075150-3C0B23D6

Builds #30 and #31 failed from the same reason, i.e: 
```
Execution failed for task ':server:integTest'.
> Process 'Gradle Test Executor 53' finished with non-zero exit value 137
  This problem might be caused by incorrect test process configuration.
  Please refer to the test execution section in the User Manual at https://docs.gradle.org/5.5/userguide/java_testing.html#sec:test_execution
```

Does not reproduce locally.

Log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.3+EAR/31/console
Build Scans: https://gradle.com/s/lznkutpe7ncag, https://gradle.com/s/hw3mlyegxnuho, https://gradle.com/s/3kqit46vr3ogc

**Comment by atorok** [comment] 2019-07-18 12:21
most likely a duplicate of #13000

**Closed by atorok** 2019-07-18 12:21 UTC
Labels: :Core/Infra/Build, >test-failure
