### ISSUE TITLE
Issue with EC2 Discovery Plugin - Does not honor discovery.ec2.tag

### ISSUE THREAD

**Issue by krishmah** [elastic/elasticsearch#18663] opened 2016-05-31 17:35 UTC
**Elasticsearch version**: Elasticsearch 5.0.0-alpha2

**JVM version**: Java 8.0

**OS version**: Linux

**Description of the problem including expected versus actual behavior**:

Based on documentation, I see that we can make use of discovery.ec2.tag in the EC2 discovery plugin as a Prefix to filter down the EC2 instances to be included in the discovery process. I created a tag by name Stage with value as DEV-ELK in EC2 instances in AWS and  I included the following setting in latest Elasticsearch 5.0.0-alpha2 release

discovery.ec2.tag.Stage=DEV-ELK

But while starting up Elastic Search instance after including the above tag in elasticsearch.yml file, it complains Exception in thread "main" java.lang.IllegalArgumentException: unknown setting [discovery.ec2.tag.Stage]

**Steps to reproduce**:
 1.Create EC2 instances with Tag as Stage and Value as DEV-ELK
 2.Configure elasticsearch.yml file to use Discovery Plugin and include the following setting to filter down the instance discovery.ec2.tag.Stage=DEV-ELK
 3.Restart the Elastic Search instance. As soon as you start, you will see the following error pasted in logs section

**Provide logs (if relevant)**:

Exception in thread "main" java.lang.IllegalArgumentException: unknown setting [discovery.ec2.tag.Stage]
at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:267)
at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:238)
at org.elasticsearch.common.settings.SettingsModule.configure(SettingsModule.java:120)
at <<<guice>>>
at org.elasticsearch.node.Node.<init>(Node.java:235)
at org.elasticsearch.node.Node.<init>(Node.java:161)
at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:188)
at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:188)
at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:267)
at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:111)
at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:106)
at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:91)
at org.elasticsearch.cli.Command.main(Command.java:53)
at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:74)
at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:67)

**Comment by krishmah** [comment] 2016-06-16 11:13
Any update on this?

**Comment by clintongormley** [comment] 2016-06-16 12:49
@dadoonet could you look at this please?

**Comment by s1monw** [comment] 2016-06-16 13:09
@krishmah did you install the discovery plugin? It seems like it's registered but if you haven't installed the plugin it will fail with this error.

**Comment by krishmah** [comment] 2016-06-16 14:55
I have installed this plugin. It is working with Security group based
discovery. Just that Tag based discovery is not working

**Comment by s1monw** [comment] 2016-06-16 16:05
duplicate of https://github.com/elastic/elasticsearch/pull/18257 - this is fixed in alpha3, please upgrade :)

**Closed by s1monw** 2016-06-16 16:05 UTC
