### ISSUE TITLE
Unable to suppress DEBUG on o.e.a.ActionModule using -E flag

### ISSUE THREAD

**Issue by phlax** [elastic/elasticsearch#57022] opened 2020-05-21 06:45 UTC
**Elasticsearch version** (`bin/elasticsearch --version`):

`Version: 7.8.0-SNAPSHOT, Build: default/docker/10fb54e90ab82b271e78da60587c2275ad3e3d88/2020-05-20T20:22:08.133568Z, JVM: 14`

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

docker build `7.8.0-SNAPSHOT`

**Description of the problem including expected versus actual behavior**:

Im getting `DEBUG` logging even when setting the `-E logger.action.level=info` flag

I tried editing the `log4js2.properties` file directly and set the log level to `info` and this suppressed the logs successfully

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. run elasticsearch with -E logger.action.level=info
 2. hope for no `DEBUG` messages from `o.e.a.ActionModule`
 3. be disappointed

**Provide logs (if relevant)**:

There are quite a few with traces relating to shard startup etc. Some are very lengthy, not sure how helpful to post.

**Comment by nik9000** [comment] 2020-05-29 17:14
I believe we've removed this from the rpm/deb/tar/zip version of log4j2.properties but it looks like we haven't from docker. That sounds like a bug to me.

Also, I did think you were supposed to be able to override properties with `-E` so that sounds like another bug.

**Comment by nik9000** [comment] 2020-05-29 17:14
But someone who knows that packaging better than I do will have to take a look.

**Comment by rjernst** [comment] 2020-05-29 23:41
Thanks for raising this issue. As Nik pointed out, this was missed in our recent removal of this from our log4j config in the docker case. I've opened https://github.com/elastic/elasticsearch/pull/57389 to fix that.

> -E logger.action.level=info

This is the not the correct setting. It should be `-E logger.org.elasticsearch.action=info`.

As the description of this issue is not a bug, I hope you don't mind that I close this issue.

**Closed by rjernst** 2020-05-29 23:41 UTC
Labels: :Core/Infra/Packaging, >bug, Team:Core/Infra
