### ISSUE TITLE
Date fails to parse exact match with milliseconds

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#12523] opened 2015-07-29 04:56 UTC
Since at least 1.6.0, exactly matching against a field mapped as a `date` using the Unix epoch format will fail. This worked in Elasticsearch 1.4.4. Of interest, we upgraded from Joda 2.3 to Joda 2.7 starting with ES 1.5.0.

```json
{
  "query": {
    "query_string": { 
      "query": "@timestamp:1438142633505"
    }
  }
}
```

or

```json
{
  "query": {
    "match": { 
      "@timestamp": "1438142633505"
    }
  }
}
```

Both of these produce

```
java.lang.IllegalArgumentException: Invalid format: "1438142633505" is malformed at "3505"
	at org.elasticsearch.common.joda.time.format.DateTimeParserBucket.doParseMillis(DateTimeParserBucket.java:187)
	at org.elasticsearch.common.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:780)
	at org.elasticsearch.index.mapper.core.DateFieldMapper.parseValue(DateFieldMapper.java:276)
	at org.elasticsearch.index.mapper.core.DateFieldMapper.indexedValueForSearch(DateFieldMapper.java:265)
	at org.elasticsearch.index.mapper.core.NumberFieldMapper.termQuery(NumberFieldMapper.java:277)
```

### Workaround

Fortunately, for the unusual use case of exactly matching with millisecond precision, you can use range queries (or filters) to workaround the issue.

```json
{
  "query": {
    "query_string": { 
      "query": "@timestamp:[1438142633505 TO 1438142633505]"
    }
  }
}
```

or

```json
{
  "query": {
    "range": { 
      "@timestamp": {
        "gte" : 1438142633505,
        "lte" : 1438142633505
      }
    }
  }
}
```

**Comment by HarishAtGitHub** [comment] 2015-07-30 06:31
I am trying to reproduce this issue in the latest elastic search code that I pulled from master (elasticsearch_2.0.0~SNAPSHOT) in an attempt to fix the bug if it is ..
1) create index  http://localhost:9200/elasticsearch - POST
         elasticsearch is the indexname

2) to create an index and its mappings
http://localhost:9200/elasticsearch/indexone/_mapping - POST 
{
       "properties" : { 
           "@timestamp" : {
            "type" :   "date"
           },
           "name" : {
            "type" :   "string"
           }
        }
}

here @timestamp is the field mapped to date (as your issue says)

3) create an entry in the type indexone as 
http://localhost:9200/elasticsearch/indexone/1 - POST 
1 is the id of the entry

{
  "name" : "harish",
  "@timestamp":1438142633505
}


4) query it as 
http://localhost:9200/elasticsearch/_search - POST 

i/p - 
{
  "query": {
    "match": { 
      "@timestamp": "1438142633505"
    }
  }
}


o/p

{
    "took": 2,
    "timed_out": false,
    "_shards": {
        "total": 5,
        "successful": 5,
        "failed": 0
    },
    "hits": {
        "total": 1,
        "max_score": 1,
        "hits": [
            {
                "_index": "elasticsearch",
                "_type": "indexone",
                "_id": "1",
                "_score": 1,
                "_source": {
                    "name": "harish",
                    "@timestamp": 1438142633505
                }
            }
        ]
    }
}


so I got the desired output. 

Am I going wrong in this test case ... Please point out ...

**Comment by HarishAtGitHub** [comment] 2015-07-30 06:32
I even tried enabling the timestamp internal field that es provides and tried to do exact matching and it worked.

**Comment by clintongormley** [comment] 2015-08-05 09:26
This bug was caused by https://github.com/elastic/elasticsearch/pull/10648

@markharwood please could you take a look

**Comment by markharwood** [comment] 2015-08-05 10:31
This works for me on 1.7.1:

	{
	  "query": {
		"match": { 
		  "@timestamp": 1438142633505
		}
	  }
	}

(note the use of a numeric value rather than the string in your example)
`query_string` and your `match` example that passes a String fail from what looks to be an issue with this version of Joda time parsing Strings as opposed to Longs. 

Master branch works OK for `match` with Strings and `query_string`.

**Comment by clintongormley** [comment] 2015-08-05 17:01
OK so fixed in master. I'll close this then.  thanks @markharwood

**Closed by clintongormley** 2015-08-05 17:01 UTC
Labels: :Query DSL, bug, v2.0.0-beta1

**Comment by ejain** [comment] 2015-09-07 17:30
Just ran into this issue when upgrading from 1.5.2 to 1.7.1. Had to replace `QueryBuilders.termQuery(field, value)` with `QueryBuilders.matchQuery(field, Long.parseLong(value))`.
