### ISSUE TITLE
Build Failure: org.elasticsearch.search.suggest.completion.CompletionSuggestionTests

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#19896] opened 2016-08-09 19:43 UTC
I was able to reproduce this test failure locally.

Reproduce with:
```gradle :core:test -Dtests.seed=78FD9CE1DD644100 -Dtests.class=org.elasticsearch.search.suggest.completion.CompletionSuggestionTests -Dtests.method="testToReduce" -Dtests.security.manager=true -Dtests.locale=uk-UA -Dtests.timezone=MST```

Build Failure:
(https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+dockeralpine-periodic/243/console)

**Comment by ywelsch** [comment] 2016-08-11 12:43
@areek can you look at this one? I've muted the test.

**Comment by chengpohi** [comment] 2016-08-11 15:37
@ywelsch can I pick this issue? I have done investigation about this issue:

this issue is caused by when `tests.seed` is `78FD9CE1DD644100`.

- `int nShards = randomIntBetween(1, 10);` the `nShards` is `1`
- `int size = randomIntBetween(3, 5);` the `size` is `5`

result:
- `shardSuggestions` size is 1
- `shardSuggestions` options are `5`

When `CompletionSuggestion.reduceTo` met the reduced `suggestions` size is 1, it will directly return first `suggestion` without filter. so this cause this test failed.

**Comment by ywelsch** [comment] 2016-08-11 15:51
@chengpohi sure, open a PR for it and ping @areek for a review.

**Comment by javanna** [comment] 2016-09-14 15:58
This was fixed by #19969

**Closed by javanna** 2016-09-14 15:58 UTC
Labels: :Suggesters, jenkins, test, v5.0.0
