### ISSUE TITLE
CI job third-party-tests-azure fails consistently

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#41405] opened 2019-04-22 09:38 UTC
From Apr. 17th, this junking jobs seems to be always failing, for example: 

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+third-party-tests-azure/8/console

The errors in the logs look like:

```
11:13:24     java.lang.RuntimeException: Failure at [repository_azure/10_repository:6]: 60 000 milliseconds timeout on connection http-outgoing-1 [ACTIVE]
11:13:24 
11:13:24         Caused by:
11:13:24         java.net.SocketTimeoutException: 60 000 milliseconds timeout on connection http-outgoing-1 [ACTIVE]
11:13:24 
11:13:24             Caused by:
11:13:24             java.net.SocketTimeoutException: 60 000 milliseconds timeout on connection http-outgoing-1 [ACTIVE]
```

**Comment by original-brownbear** [comment] 2019-04-22 09:44
This is being investigated by infra here https://github.com/elastic/infra/issues/1063#issuecomment-484236560

I don't think it's an issue with ES itself since I can reproduce the test passing from my local workstation just fine against real Azure. I'll assign myself here and see what if anything we can do from the ES end to help out there.

**Comment by droberts195** [comment] 2019-04-23 08:55
This is still failing, for example https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+third-party-tests-azure/14/console

Since the sole purpose of the Jenkins job is to test with a real Azure repository it seems silly to mute the tests that use Azure but leave the Jenkins job running.  I have asked infra if it would be worth making the persistently failing Jenkins job run only on demand until the problem is resolved.

**Comment by original-brownbear** [comment] 2019-04-23 18:17
This now only remains an issue on `7.x` because the way we match the repository settings in the REST tests seems to have trouble dealing with `7.0` being part of the `base_path`. I'll fix that.

For `master` this test now passes fine.

**Comment by jkakavas** [comment] 2019-04-24 06:17
> This now only remains an issue on 7.x

It also fails for 6.7, example: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.7+third-party-tests-azure/16/console

**Comment by original-brownbear** [comment] 2019-04-24 06:20
Thanks I added the 6.7.x label to the fix PR https://github.com/elastic/elasticsearch/pull/41457 as well. This should be fixed shortly :)

**Closed** 2019-04-24 08:12 UTC
Labels: :Core/Infra/Build, >test-failure
