### ISSUE TITLE
EqlStatsIT.testEqlRestUsage fails on master with endgame resource already exists exception

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#59665] opened 2020-07-15 20:25 UTC
**Build scan**:
https://gradle-enterprise.elastic.co/s/5qp7b7b7ejixm

**Repro line**:
```
./gradlew ':x-pack:plugin:eql:qa:rest:integTestRunner' --tests "org.elasticsearch.xpack.eql.EqlStatsIT.testEqlRestUsage" -Dtests.seed=909070014E59699 -Dtests.security.manager=true -Dtests.locale=sr-Latn -Dtests.timezone=Africa/Mogadishu -Druntime.java=11
```

**Reproduces locally?**:
No

**Applicable branches**:
master

**Failure history**:
7 times in the last two days
https://gradle-enterprise.elastic.co/scans/tests?search.buildToolType=gradle&search.buildToolType=maven&search.relativeStartTime=P7D&search.timeZoneId=America/Denver&tests.container=org.elasticsearch.xpack.eql.EqlStatsIT&tests.sortField=FAILED&tests.test=testEqlRestUsage&tests.unstableOnly=true

**Failure excerpt**:
```
org.elasticsearch.xpack.eql.EqlStatsIT > testEqlRestUsage FAILED
    [endgame-1.4.0/gdv7pdcTRnmxTbureltqzA] org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=resource_already_exists_exception, reason=index [endgame-1.4.0/gdv7pdcTRnmxTbureltqzA] already exists]
        at __randomizedtesting.SeedInfo.seed([909070014E59699:8243F16565E1D787]:0)
        at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:187)
        at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1892)
        at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1869)
        at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1626)
        at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1598)
        at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1565)
        at org.elasticsearch.client.IndicesClient.create(IndicesClient.java:144)
        at org.elasticsearch.test.eql.DataLoader.createTestIndex(DataLoader.java:65)
        at org.elasticsearch.test.eql.DataLoader.loadDatasetIntoEs(DataLoader.java:57)
        at org.elasticsearch.test.eql.stats.RestEqlUsageTestCase.testEqlRestUsage(RestEqlUsageTestCase.java:118)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
```

**Comment by astefan** [comment] 2020-07-17 06:13
Duplicate of https://github.com/elastic/elasticsearch/issues/59619.

**Comment by astefan** [comment] 2020-07-17 08:42
Fixed with the following PRs:
master (8.0.0): https://github.com/elastic/elasticsearch/pull/59745
7.x (7.10.0): https://github.com/elastic/elasticsearch/pull/59747
7.9 (7.9.0): https://github.com/elastic/elasticsearch/pull/59748

**Closed by astefan** 2020-07-17 08:42 UTC
Labels: :Query Languages/EQL, >test-failure, Team:QL
