### ISSUE TITLE
Pagination & Sorting & Aggregation

### ISSUE THREAD

**Issue by mohannadsalem** [elastic/elasticsearch#25054] opened 2017-06-05 13:37 UTC
**Describe the feature**:

**Elasticsearch version**:

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by colings86** [comment] 2017-06-05 13:58
This issue doesn't have much detail but it looks like a duplicate of https://github.com/elastic/elasticsearch/issues/14928. If thats not correct please provide details of what this feature request is

**Closed by colings86** 2017-06-05 13:58 UTC
