### ISSUE TITLE
Default lifecycle policy affects system indices

### ISSUE THREAD

**Issue by mutt13y** [elastic/elasticsearch#62891] opened 2020-09-24 16:19 UTC
**Elasticsearch version** (`bin/elasticsearch --version`):
7.9.1
**Plugins installed**: []

**JVM version** (`java -version`):
openjdk version “14.0.1” 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.1+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.1+7, mixed mode, sharing)

**OS version** (`uname -a` if on a Unix-like system):
Centos7
3.10.0-957.27.2.el7.x86_6

**Description of the problem including expected versus actual behavior**:
Default index template with lifecycle policy applies to system indices

**Steps to reproduce**:
1. Create lifecycle policy with delete after N days
2. Create index template to apply lifecycle and match '\*'
3. In reality perform some upgrade which creates a new system index, to test delete .kibana

now the new lifecycle policy is applied to .kibana and settings will be lost every N days

This is a latent issue since most system indices will be created before the template in normal operation but after an upgrade the index can be replaced and so the policy is applied.

I think that '\*' should not match indices that start with a '.' we should have to explicitly use '.\*' or have a flag to indicate if it applies to system indices.

Certianly from an end user perspective there seems to be nothing obviously wrong with defining a catchall template with an aggressive lifecycle policy
![Screenshot 2020-09-24 at 16 14 20](https://user-images.githubusercontent.com/39803837/94171776-957a0d00-fe89-11ea-8f6e-2aa05252bb12.png)
![Screenshot 2020-09-24 at 17 13 20](https://user-images.githubusercontent.com/39803837/94171804-9ca11b00-fe89-11ea-854a-ec599b2e0a06.png)

P.S.
Work around is to create a policy matching ".\*" with a lower priority

**Comment by gwbrown** [comment] 2020-09-28 15:43
We are currently in the process of formalizing internal or "System" indices to prevent this kind of scenario, see https://github.com/elastic/elasticsearch/issues/50251. As part of that effort, we will be preventing global templates from impacting System Indices. As such, I consider this a duplicate of the above issue, and I hope you don't mind that I close this.

**Closed by gwbrown** 2020-09-28 15:43 UTC
Labels: >bug, needs:triage
