### ISSUE TITLE
No handler for type [dense_vector] declared on field [my_vector]

### ISSUE THREAD

**Issue by psyapathy** [elastic/elasticsearch#39783] opened 2019-03-07 09:02 UTC
Hello!
I need help. I just installed new Elastic,create index and try mapping by [example](https://www.elastic.co/guide/en/elasticsearch/reference/master/dense-vector.html)

```
{
 "properties": {
   "my_vector": {
     "type": "dense_vector"
    },
    "my_text" : {
      "type" : "keyword"
    }
  }
}
```
and i get error:

```
{
    "error": {
        "root_cause": [
            {
                "type": "mapper_parsing_exception",
                "reason": "No handler for type [dense_vector] declared on field [my_vector]"
            }
        ],
        "type": "mapper_parsing_exception",
        "reason": "No handler for type [dense_vector] declared on field [my_vector]"
    },
    "status": 400
}
```
Thank you advance for reply!

**Comment by jimczi** [comment] 2019-03-07 09:47
This is probably because you installed a version of Elasticsearch that doesn't support this field type. The `dense_vector` field type is only released for testing in the beta1 version of 7.0.0:
https://www.elastic.co/blog/elasticsearch-7-0-0-beta1-released
I tested the snippets with this version and it works as documented so I am closing this issue. Please reopen with a recreation if you can reproduce in this version.

**Closed by jimczi** 2019-03-07 09:47 UTC
