### ISSUE TITLE
delete api date time resolution for snapshots

### ISSUE THREAD

**Issue by sudo-su-tony** [elastic/elasticsearch#50833] opened 2020-01-10 01:29 UTC
First off I'm very new to Elastic, currently running open distro, but I tested this on normal Elastic too.
I was trying to delete snapshots using the delete api with an expression something like this 

`DELETE _snapshot/my_repository/%3Cname-%7Bnow%2FM-1M%7Byyyy.MM%7D%7D%3E`

and it would return:
`[my_repository:<name-{now/M-1M{yyyy.MM}}>] is missing`

which means the api didn't resolve the datetime expression I think. 
I no longer need to do this (turns out it was a mistake anyways), but I thought I'd report this in case it's unintended because I couldn't find anything relating to it on google.

sudo su

**Comment by original-brownbear** [comment] 2020-01-10 11:18
Hi @sudo-su-tony 

thanks for raising this, it's a good point and fortunately known.

Currently, deleting multi snapshots in one go is not supported so there's no support for  any kind of expression here either. I'm currently implementing deleting multiple snapshots at once as a new feature in https://github.com/elastic/elasticsearch/pull/49800 so some form of this is eventually incoming.

For now everything is working as intended, so I'm closing here as we already have #49800.

**Closed by original-brownbear** 2020-01-10 11:18 UTC
Labels: :Distributed/Snapshot/Restore
