### ISSUE TITLE
Elasticsearch fails to shutdown, blocked by 

### ISSUE THREAD

**Issue by gehel** [elastic/elasticsearch#19829] opened 2016-08-05 14:19 UTC
**Elasticsearch version**: 2.3.3

**JVM version**:

    $ java -version
    java version "1.7.0_111"
    OpenJDK Runtime Environment (IcedTea 2.6.7) (7u111-2.6.7-1~deb8u1)
    OpenJDK 64-Bit Server VM (build 24.111-b01, mixed mode)

**OS version**: Debian Jessie (8.2)

**Description of the problem including expected versus actual behavior**:

When doing a routine cluster restart, one of our elasticsearch node refused to shutdown (`sudo service elasticsearch restart`) for a long time. We ended up doing a `kill -9`. Taking [thread dumps](https://gist.github.com/gehel/3e5bab4228d40670afe99d428d18faae), we see:

* The shutdown handler is blocked, waiting on `Thread.join()`, letting me think there is a non background thread still doing work.
* It seems that the only activity left was a [lucene merge that was in progress](https://gist.github.com/gehel/3e5bab4228d40670afe99d428d18faae#file-threaddump-elasticsearch-L213).
* This looks very similar to #12941.

**Steps to reproduce**:
We don't know how to reproduce this in a reliable way. This seems to be related to shutting down elasticsearch while a merge is in progress

**Provide logs (if relevant)**:

* Thread dumps: https://gist.github.com/gehel/3e5bab4228d40670afe99d428d18faae

**Comment by s1monw** [comment] 2016-08-05 14:30
can you elaborate what `long time` means for you :) I like 1 min, 10min? Waiting for pending merges to abort can potentially take quite a while, I am double checking though.

**Comment by gehel** [comment] 2016-08-05 14:34
Long time meaning 1 hour before we killed it. I did take a few threaddumps and can validate that the merge was still doing work. So it would probably have completed eventually. But I would much prefer the merge to abort and the shutdown to complete.

**Comment by s1monw** [comment] 2016-08-05 14:55
@gehel can you tell why the node get's restarted? do you have GC going on or are you under memory pressure? I also wonder how big your index is there and if you potentially have a lot of sparse fields in your index?

**Comment by gehel** [comment] 2016-08-05 15:09
@s1monw the node got restarted for scheduled maintenance (JVM security upgrade). We have 30Go of heap allocated to the JVM, 128Go of RAM in the machine. I don't think that we have much GC activity, but I need to check on that.

This elasticsearch cluster is our logstash backend, we have one index per day with ~10-20M document, and pri.store.size between 5 and 40Go, mostly around 10Go.

**Comment by mikemccand** [comment] 2016-08-05 15:09
I have a possible explanation: a merge only checks whether it's aborted when its `RateLimiter.pause` is invoked, but since forced merges run un-throttled, this is never called, and the forced merge will block shutdown.

I'll try to confirm with a standalone Lucene test and open an issue...

**Comment by mikemccand** [comment] 2016-08-05 17:09
> I have a possible explanation: 

OK, I was wrong about this: even at un-throttled IO, Lucene 5.5.0 still checks for aborts every 1 MB of bytes written.  And I tested a standalone Lucene case and confirmed that a forced merge is quickly aborted during rollback.

So I can't explain what's happening here yet.

If a merge thread runs for a long time but never writes more than 1 MB, that could lead to this behavior, but it's hard to imagine a merge thread running for an *hour* and not writing 1 MB ;)

Do you have very sparse fields?  How many documents were in the index being force merged?  Were there maybe many deletions?

**Comment by gehel** [comment] 2016-08-06 15:30
I don't know how to check how sparse our fields are. As this elasticsearch cluster is backing logstash, I can very well imagine that some fields are only used for some applications. So we probably do have fairly sparse fields, but I don't have an exact measure of that. We don't do deletions on that cluster.

**Comment by mikemccand** [comment] 2016-08-08 12:53
I tried to reproduce this, using the ES 2.3.3 install, and indexing the first 50 M documents from the NYC taxi data set: http://www.nyc.gov/html/tlc/html/about/trip_record_data.shtml

Then I kick off the `forceMerge`, see that it's running, then I send SIGINT to the ES process and it very quickly terminates.  I repeated this and tried closing the index instead of shutting ES process down, and it also quickly terminates.

So I'm unable to reproduce this so far ... there must be some difference.  Could you pull a diagnostics (https://github.com/elasticsearch/elasticsearch-support-diagnostics) and post somewhere?

**Comment by gehel** [comment] 2016-08-08 14:15
@mikemccand Thanks for the efforts! Diagnostic dump is available at https://phabricator.wikimedia.org/F4345184 Let me know if there is anything else I can provide!

Note that we had the same issue restarting the next node in the same cluster (still for planned maintenance). The [thread dump](https://gist.github.com/gehel/bae0154a740024e54a8e7d04e7c94561) of this other restart looks very similar.

**Comment by mikemccand** [comment] 2016-08-08 20:51
Thanks @gehel.

Hmm, in the hot threads, I see a `forceMerge` running, this time doing `isSingleValued` on a biggish merge (39.8 GB, 16.7 M docs), which is indeed a step of the merge that does all reading and no writing.  But it ought to be fast.

Other parts of merging are read-only (e.g. `checkIntegrity`) but should also be fast.

Your first merge hot thread should have been writing stuff, which should eventually lead to checking for the merge being aborted.

You have a miniscule number of deletes, so the merge ought to be writing bytes to the new segment as it runs.

When this happens again, can you pull many hot threads over time and post all of them?  And also run iostat continuously while the force merge is refusing to stop, and post that? I'd like to see what the merge thread is doing over this hour...

What IO system is backing your path.data?

**Comment by nomoa** [comment] 2016-08-08 22:00
@mikemccand here is a set of [5 stackdumps](https://phabricator.wikimedia.org/F4345956) took when elastic was stuck after calling service restart.
The first stack was taken at 11:55 and the last one at 12:48. The merge seems to be always stuck while processing DocValues.
I downloaded one of the shards (10gb) but failed to reproduce the issue with a simple lucene test case, I'll try with a bigger one.

**Comment by mikemccand** [comment] 2016-08-08 22:20
Thanks, indeed all 5 of those show doc values merging, specifically sorted set, and sometimes from an older segment (Lucene 4.10.x format).

I'm wondering if your data is such that the compression of the newer doc values formats (Lucene 5.4+) is much better than 4.10.x was and this merge is doing tons of reading and hardly any writing.  The `iostat` output would help confirm this.  Would it be possible to upload one of your shards somewhere?   I can try to confirm this.

**Comment by gehel** [comment] 2016-08-09 08:03
@mikemccand Thanks for the help! I'm afraid we can't upload the shards as they potential contain critical information. I'll check though.

For your previous question, our IO system is: 4x1To spinning disk in software RAID0. I can find the specific models, controllers, ... if you think that's useful.

**Comment by gehel** [comment] 2016-08-09 09:40
@mikemccand here is a [dashboard of iostat metrics that we collect](https://grafana.wikimedia.org/dashboard/db/logstash-elasticsearch-investigation). Let me know if you want more metrics, I'll see what I can add. The timings are as follow:

* 09:42 UTC: starting shutdown of elasticsearch
* 10:56 UTC: kill -9 elasticsearch and restart

So it seems that during the whole shutdown, there was almost no IO happening.

Not sure this is directly related, but I did find some errors about optimize just after shutdown: https://gist.github.com/gehel/ba16e9fd7debbcaa70ab6549525c2b1c

**Comment by mikemccand** [comment] 2016-08-09 09:57
> So it seems that during the whole shutdown, there was almost no IO happening.

Wow, how strange, that the CPU can be working so hard for an hour merging away and not cause any IO... the reads could all have been cached by the OS, but the writes should periodically (every 5s by default in Linux) be written through to the IO device.  Apparently Lucene is merging away and producing no bytes for your new segment.

Does this only happen when force-merging older indices (Lucene 4.10.x, ES 1.x)?

> For your previous question, our IO system is: 4x1To spinning disk in software RAID0. I can find the specific models, controllers, ... if you think that's useful.

OK, thanks, no need for specifics.  The IO devices aren't even being written to ...

> I'm afraid we can't upload the shards as they potential contain critical information. I'll check though.

OK, too bad: I'm very curious what sort of indices compress down to 0 bytes on merge ;)  Something odd is happening.

**Comment by gehel** [comment] 2016-08-09 10:25
We might be able to send you one of our shard, provided you (@mikemccand) or elastic signs an NDA. I'm checking to see if this is actually possible and if it is easy enough to make sense.

**Comment by gehel** [comment] 2016-08-11 21:20
Anything else I can do to help on this? It should not be too hard on our side to get give you an NDA to sign and send one of our problematic shard. Interested?

**Comment by mikemccand** [comment] 2016-08-11 23:14
@gehel sure, can you send it to my private email address (see my github profile)?

**Comment by ebernhardson** [comment] 2016-08-16 22:30
I can add that we did have a few very sparse fields in a couple indices. I'm not sure which index was doing the merge when this occured, but there was a bug for a few days where one of the applications logging to these instances created 50k-100k fields per day by mistakenly using hashes as nested array keys. That bug has since been fixed, but perhaps having 100k fields that are each used in a single document (one doc might have 10 unique fields) could have contributed?

**Comment by mikemccand** [comment] 2016-08-17 08:58
> That bug has since been fixed, but perhaps having 25k (up to 100k on the worst days) fields that are each used in a single document could have caused an issue like this?

Did these fields have doc values enabled?  If so, that could explain it: older versions of Lucene (4.10.x) did not compress extremely sparse cases very well, but with https://issues.apache.org/jira/browse/LUCENE-6863 (included in ES 2.3.x) we now compress these extremely sparse cases.

**Comment by ebernhardson** [comment] 2016-08-17 19:05
Checked our mapping, yes they all had doc values enabled (per defaults). The mapping per field generally looks like:

          "err_body_req_body_attributes_value_ids_mw9g_dsr_0": {
            "type": "string",
            "norms": {
              "enabled": false
            },
            "fields": {
              "raw": {
                "type": "string",
                "index": "not_analyzed",
                "ignore_above": 256
              }
            }
          },

**Comment by mikemccand** [comment] 2016-08-18 21:45
OK thanks @ebernhardson; I think given that this is an unusual corner case situation (old Lucene 4.10.x segments being merged, while containing documents caused by an application level bug that created tons of exceptionally sparse fields), there's nothing for us to fix here.

**Closed by mikemccand** 2016-08-18 21:45 UTC
Labels: :Core, feedback_needed
