### ISSUE TITLE
Painless throws null pointer in parsing analyzed field

### ISSUE THREAD

**Issue by sumitsaxena21** [elastic/elasticsearch#24125] opened 2017-04-16 18:08 UTC
**Elasticsearch version**: 5.1

**Plugins installed**: [painless]

**JVM version**: 1.8

**OS version**: AWS Elasticsearch

**Description of the problem including expected versus actual behavior**:

There is a bug in painless script. If sort field is not present in all the documents then it is throwing null pointer exception while executing below script
```
"aggregations" : {
	        "id_script_keyword" : {
	          "max" : {
	            "script" : {
	              "inline" : "Double.parseDouble(doc['id.keyword'].value)",
	              "lang" : "painless"
	            }
	          }
```
I have 100 documents and few documents don't have id field.
expected : normal sort behavior.
actual :  null pointer exception.

**Steps to reproduce**:
 1. put a document in elaticsearch without id field.
 2. run 
```
"aggregations" : {
	        "id_script_keyword" : {
	          "max" : {
	            "script" : {
	              "inline" : "Double.parseDouble(doc['id.keyword'].value)",
	              "lang" : "painless"
	            }
	          }
```
 3.

**Provide logs (if relevant)**:
```
{
  "took": 6,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 4,
    "failed": 1,
    "failures": [
      {
        "shard": 0,
        "index": "merch-ecs_products-v2-en_us_g1",
        "node": "SxJrPFRHSOGEy5Rh9QiOTg",
        "reason": {
          "type": "script_exception",
          "reason": "runtime error",
          "caused_by": {
            "type": "null_pointer_exception",
            "reason": null
          },
          "script_stack": [],
          "script": "Double.parseDouble(doc['id.keyword'].value)",
          "lang": "painless"
        }
      }
    ]
  },
  "hits": {
    "total": 0,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "rollupIdentifier": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 0,
      "buckets": []
    }
  }
}
```

**Describe the feature**:

**Comment by nik9000** [comment] 2017-04-16 18:55
Lack of a script_stack element is certainly a bug. NPE might be yours. I
have a few more script_stack issues to look at next week, so I'm happy to
look I to this one. Any chance you could figure out if the document that
causes this exception has a bill id.keyword field?

**Comment by nik9000** [comment] 2017-04-17 16:05
Your script is throwing the NPE. I think you can work around it by checking
the null first. Even when I fix the bug your script still won't work
because it expects all documents to have an id.

**Comment by nik9000** [comment] 2017-04-18 21:03
@sumitsaxena21 your words talk about a sort but your example is an aggregation.

**Comment by nik9000** [comment] 2017-04-18 21:05
Ah, bucket sort script.

**Comment by nik9000** [comment] 2017-04-18 21:12
OK. I still can't reproduce this. Here is the script I'm using:
```
DELETE /ledger

PUT /ledger
{
  "settings": {
    "number_of_shards": 2,
    "number_of_replicas": 1
  },
  "mappings": {
    "doc": {
      "properties": {
        "id": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword"
            }
          }
        },
        "type": {
          "type": "keyword"
        },
        "amount": {
          "type": "double"
        }
      }
    }
  }
}

POST /ledger/doc/_bulk?refresh
{"index":{}}
{"id": "213", "date": "2015/01/01 00:00:00", "amount": 200, "type": "sale", "description": "something"}
{"index":{}}
{"date": "2015/01/01 00:00:00", "amount": 10, "type": "expense", "decription": "another thing"}

POST /ledger/_search
{
  "aggs": {
    "date": {
      "terms": {
        "field": "date",
        "order": {
          "id_script_keyword": "desc"
        }
      },
      "aggs": {
        "id_script_keyword": {
          "max": {
            "script": {
              "inline": "Double.parseDouble(doc['id.keyword'].value)",
              "lang": "painless"
            }
          }
        }
      }
    }
  }
}
```

I get a null pointer exception all right, but it has an obvious script_stack:

```
"failures": [
      {
        "shard": 1,
        "index": "ledger",
        "node": "u-u9FSzOSbaGHGfCqYmY6A",
        "reason": {
          "type": "script_exception",
          "reason": "runtime error",
          "caused_by": {
            "type": "null_pointer_exception",
            "reason": null
          },
          "script_stack": [
            "sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1838)",
            "sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)",
            "java.lang.Double.parseDouble(Double.java:538)",
            "Double.parseDouble(doc['id.keyword'].value)",
            "                                    ^---- HERE"
          ],
          "script": "Double.parseDouble(doc['id.keyword'].value)",
          "lang": "painless"
        }
      }
```

As far as I can tell this is working perfectly. If you want to handle null in the script that is up to you. Like this:
```
POST /ledger/_search
{
  "aggs": {
    "date": {
      "terms": {
        "field": "date",
        "order": {
          "id_script_keyword": "desc"
        }
      },
      "aggs": {
        "id_script_keyword": {
          "max": {
            "script": {
              "inline": "doc['id.keyword'].empty ? 0 : Double.parseDouble(doc['id.keyword'].value)",
              "lang": "painless"
            }
          }
        }
      }
    }
  }
}
```

Can you put together a complete reproduction, like the one I pasted in the top of this comment? Without something like that I'm just guessing.

**Comment by nik9000** [comment] 2017-04-19 00:45
I wonder if this is http://jawspeak.com/2010/05/26/hotspot-caused-exceptions-to-lose-their-stack-traces-in-production-and-the-fix/

**Comment by colings86** [comment] 2017-05-25 08:58
No further feedback, closing. If you manage to create a reproduction script please post it here and we can reopen

**Closed by colings86** 2017-05-25 08:58 UTC
Labels: :Plugin Lang Painless, feedback_needed

**Comment by bilalvdemir** [comment] 2018-03-24 11:17
With Elasticsearch 5.x and gt verison we can read all fields with script. For example:

`GET _search
{
  "size": 0,
  "query": {
    "match": {
      "description": "test"
    }
  },
  "_source": {
    "excludes": [],
    "includes": [
      "detail.name",
      "data.timestamp",
      "data.o3"
    ]
  },
  "aggs": {
    "custom": {
      "sum": {
        "script": "((params._source.detail.name==null) ? 0 : (params._source.detail.name.toString().length())) + ((params._source.data.timestamp==null) ? 0 : (params._source.data.timestamp.toString().length()))"
      }
    }
  }
}`

For nested feilds you must use nested conditions.
"(params._source.x==null) ? 0 : ( (params._source.x.y==null) ? 0 : (params._source.x.y.z.length()) ))"

@sumitsaxena21 @nik9000
