### ISSUE TITLE
[CI] SnapshotBasedRecoveryIT testSnapshotBasedRecovery failing

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#94149] opened 2023-02-27 13:08 UTC
**Build scan:**
https://gradle-enterprise.elastic.co/s/h233lk33zmlue/tests/:qa:rolling-upgrade:v8.6.1%23oneThirdUpgradedTest/org.elasticsearch.upgrades.SnapshotBasedRecoveryIT/testSnapshotBasedRecovery

**Reproduction line:**
```
./gradlew ':qa:rolling-upgrade:v8.6.1#oneThirdUpgradedTest' -Dtests.class="org.elasticsearch.upgrades.SnapshotBasedRecoveryIT" -Dtests.method="testSnapshotBasedRecovery" -Dtests.seed=F47E24CAEB3AB7B9 -Dtests.bwc=true -Dtests.locale=mt-MT -Dtests.timezone=America/Anguilla -Druntime.java=17
```

**Applicable branches:**
8.7

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.upgrades.SnapshotBasedRecoveryIT&tests.test=testSnapshotBasedRecovery

**Failure excerpt:**
```
java.lang.AssertionError: timed out waiting for green state for index [snapshot_based_recovery] cluster state [{
  "cluster_name" : "v8.6.1",
  "cluster_uuid" : "ugxLuWX_QlCtYqzBBM3BGg",
  "version" : 389,
  "state_uuid" : "8XTThkQlT9-kVnNSeX5a5g",
  "master_node" : "rj4Z-6_aSvujKUNPDG63rw",
  "blocks" : {
    "indices" : {
      "index_mixed_8060199" : {
        "4" : {
          "description" : "index closed",
          "retryable" : false,
          "levels" : [
            "read",
            "write"
          ]
        }
      },
      "closed_index_replica_allocation" : {
        "4" : {
          "description" : "index closed",
          "retryable" : false,
          "levels" : [
            "read",
            "write"
          ]
        }
      },
      "closed_index_created_on_old" : {
        "4" : {
          "description" : "index closed",
          "retryable" : false,
          "levels" : [
            "read",
            "write"
          ]
        }
      },
      "index_old_8060199" : {
        "4" : {
          "description" : "index closed",
          "retryable" : false,
          "levels" : [
            "read",
            "write"
          ]
        }
      }
    }
  },
  "nodes" : {
    "rj4Z-6_aSvujKUNPDG63rw" : {
      "name" : "v8.6.1-1",
      "ephemeral_id" : "QXiNUys5SZKDsntTdINOBw",
      "transport_address" : "127.0.0.1:35745",
      "external_id" : "v8.6.1-1",
      "attributes" : {
        "ml.allocated_processors_double" : "32.0",
        "ml.machine_memory" : "101372157952",
        "xpack.installed" : "true",
        "ml.max_jvm_size" : "536870912",
        "ml.allocated_processors" : "32",
        "testattr" : "test"
      },
      "roles" : [
        "data",
        "data_cold",
        "data_content",
        "data_frozen",
        "data_hot",
        "data_warm",
        "ingest",
        "master",
        "ml",
        "remote_cluster_client",
        "transform"
      ]
    },
    "BMTGfwK3TMeWsco_JGUhRA" : {
      "name" : "v8.6.1-0",
      "ephemeral_id" : "SHTb8G0ARPuwfA1T4MRiRg",
      "transport_address" : "127.0.0.1:45731",
      "external_id" : "v8.6.1-0",
      "attributes" : {
        "testattr" : "test",
        "ml.machine_memory" : "101372157952",
        "upgraded" : "true",
        "ml.allocated_processors" : "32",
        "ml.allocated_processors_double" : "32.0",
        "ml.max_jvm_size" : "536870912",
        "xpack.installed" : "true"
      },
      "roles" : [
        "data",
        "data_cold",
        "data_content",
        "data_frozen",
        "data_hot",
        "data_warm",
        "ingest",
        "master",
        "ml",
        "remote_cluster_client",
        "transform"
      ]
    },
    "aJ2aZXGzQTatm5lqTzehMg" : {
      "name" : "v8.6.1-2",
      "ephemeral_id" : "mc2QN4RBTMGXvVzX_VGqJw",
      "transport_address" : "127.0.0.1:40883",
      "external_id" : "v8.6.1-2",
      "attributes" : {
        "ml.allocated_processors_double" : "32.0",
        "ml.machine_memory" : "101372157952",
        "xpack.installed" : "true",
        "ml.max_jvm_size" : "536870912",
        "ml.allocated_processors" : "32",
        "testattr" : "test"
      },
      "roles" : [
        "data",
        "data_cold",
        "data_content",
        "data_frozen",
        "data_hot",
        "data_warm",
        "ingest",
        "master",
        "ml",
        "remote_cluster_client",
        "transform"
      ]
    }
  },
  "metadata" : {
    "cluster_uuid" : "ugxLuWX_QlCtYqzBBM3BGg",
    "cluster_uuid_committed" : true,
    "cluster_coordination" : {
      "term" : 2,
      "last_committed_config" : [
        "aJ2aZXGzQTatm5lqTzehMg",
        "BMTGfwK3TMeWsco_JGUhRA",
        "rj4Z-6_aSvujKUNPDG63rw"
      ],
      "last_accepted_config" : [
        "aJ2aZXGzQTatm5lqTzehMg",
        "BMTGfwK3TMeWsco_JGUhRA",
        "rj4Z-6_aSvujKUNPDG63rw"
      ],
      "voting_config_exclusions" : [ ]
    },
    "templates" : {
      ".monitoring-beats" : {
        "order" : 0,
        "version" : 8010099,
        "index_patterns" : [
          ".monitoring-beats-7-*"
        ],
        "settings" : {
          "index" : {
            "format" : "7",
            "codec" : "best_compression",
            "number_of_shards" : "1",
            "auto_expand_replicas" : "0-1",
            "number_of_replicas" : "0"
          }
        },
        "mappings" : {
          "_doc" : {
            "dynamic" : false,
            "properties" : {
              "beats_state" : {
                "properties" : {
                  "beat" : {
                    "properties" : {
                      "host" : {
                        "type" : "keyword"
                      },
                      "name" : {
                        "type" : "keyword"
                      },
                      "type" : {
                        "type" : "keyword"
                      },
                      "uuid" : {
                        "type" : "keyword"
                      },
                      "version" : {
                        "type" : "keyword"
                      }
                    }
                  },
                  "state" : {
                    "properties" : {
                      "beat" : {
                        "properties" : {
                          "name" : {
                            "type" : "keyword"
                          }
                        }
                      },
                      "host" : {
                        "properties" : {
                          "architecture" : {
                            "type" : "keyword"
                          },
                          "name" : {
                            "type" : "keyword"
                          },
                          "hostname" : {
                            "type" : "keyword"
                          },
                          "os" : {
                            "properties" : {
                              "build" : {
                                "type" : "keyword"
                              },
                              "family" : {
                                "type" : "keyword"
                              },
                              "platform" : {
                                "type" : "keyword"
                              },
                              "version" : {
                                "type" : "keyword"
                              }
                            }
                          }
                        }
                      },
                      "input" : {
                        "properties" : {
                          "count" : {
                            "type" : "long"
                          },
                          "names" : {
                            "type" : "keyword"
                          }
                        }
                      },
                      "module" : {
                        "properties" : {
                          "count" : {
                            "type" : "long"
                          },
                          "names" : {
                            "type" : "keyword"
                          }
                        }
                      },
                      "output" : {
                        "properties" : {
                          "name" : {
                            "type" : "keyword"
                          }
                        }
                      },
                      "service" : {
                        "properties" : {
                          "id" : {
                            "type" : "keyword"
                          },
                          "name" : {
                            "type" : "keyword"
                          },
                          "version" : {
                            "type" : "keyword"
                          }
                        }
                      }
                    }
                  },
                  "timestamp" : {
                    "format" : "date_time",
                    "type" : "date"
                  }
                }
              },
              "beats_stats" : {
                "properties" : {
                  "beat" : {
                    "properties" : {
                      "host" : {
                        "type" : "keyword"
                      },
                      "name" : {
                        "type" : "keyword"
                      },
                      "type" : {
                        "type" : "keyword"
                      },
                      "uuid" : {
                        "type" : "keyword"
                      },
                      "version" : {
                        "type" : "keyword"
                      }
                    }
                  },
                  "metrics" : {
                    "properties" : {
                      "beat" : {
                        "properties" : {
                          "cgroup" : {
                            "properties" : {
                              "cpu" : {
                                "properties" : {
                                  "id" : {
                                    "type" : "keyword"
                                  },
                                  "cfs" : {
                                    "properties" : {
                                      "period" : {
                                        "properties" : {
                                          "us" : {
                                            "type" : "long"
                                          }
                                        }
                                      },
                                      "quota" : {
                                        "properties" : {
                                          "us" : {
                                            "type" : "long"
                                          }
                                        }
                                      }
                                    }
                                  },
                                  "stats" : {
                                    "properties" : {
                                      "periods" : {
                                        "type" : "long"
                                      },
                                      "throttled" : {
                                        "properties" : {
                                          "periods" : {
                                            "type" : "long"
                                          },
                                          "ns" : {
                                            "type" : "long"
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              },
                              "cpuacct" : {
                                "properties" : {
                                  "id" : {
                                    "type" : "keyword"
                                  },
                                  "total" : {
                                    "properties" : {
                                      "ns" : {
                                        "type" : "long"
                                      }
                                    }
                                  }
                                }
                              },
                              "memory" : {
                                "properties" : {
                                  "id" : {
                                    "type" : "keyword"
                                  },
                                  "mem" : {
                                    "properties" : {
                                      "limit" : {
                                        "properties" : {
                                          "bytes" : {
                                            "type" : "long"
                                          }
                                        }
                                      },
                                      "usage" : {
                                        "properties" : {
                                          "bytes" : {
                                            "type" : "long"
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          },
                          "cpu" : {
                            "properties" : {
                              "system" : {
                                "properties" : {
                                  "ticks" : {
                                    "type" : "long"
                                  },
                                  "time" : {
                                    "properties" : {
                                      "ms" : {
                                        "type" : "long"
                                      }
                                    }
                                  }
                                }
                              },
                              "total" : {
                                "properties" : {
                                  "value" : {
                                    "type" : "long"
                                  },
                                  "ticks" : {
                                    "type" : "long"
                                  },
                                  "time" : {
                                    "properties" : {
                                      "ms" : {
                                        "type" : "long"
                                      }
                                    }
                                  }
                                }
                              },
                              "user" : {
                                "properties" : {
                                  "ticks" : {
                                    "type" : "long"
                                  },
                                  "time" : {
                                    "properties" : {
                                      "ms" : {
                                        "type" : "long"
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          },
                          "info" : {
                            "properties" : {
                              "ephemeral_id" : {
                                "type" : "keyword"
                              },
                              "uptime" : {
                                "properties" : {
                                  "ms" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "version" : {
                                "type" : "keyword"
                              }
                            }
                          },
                          "memstats" : {
                            "properties" : {
                              "gc_next" : {
                                "type" : "long"
                              },
                              "memory_alloc" : {
                                "type" : "long"
                              },
                              "memory_total" : {
                                "type" : "long"
                              },
                              "rss" : {
                                "type" : "long"
                              }
                            }
                          },
                          "handles" : {
                            "properties" : {
                              "open" : {
                                "type" : "long"
                              },
                              "limit" : {
                                "properties" : {
                                  "hard" : {
                                    "type" : "long"
                                  },
                                  "soft" : {
                                    "type" : "long"
                                  }
                                }
                              }
                            }
                          }
                        }
                      },
                      "apm-server" : {
                        "properties" : {
                          "acm" : {
                            "properties" : {
                              "request" : {
                                "properties" : {
                                  "count" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "response" : {
                                "properties" : {
                                  "count" : {
                                    "type" : "long"
                                  },
                                  "errors" : {
                                    "properties" : {
                                      "validate" : {
                                        "type" : "long"
                                      },
                                      "internal" : {
                                        "type" : "long"
                                      },
                                      "queue" : {
                                        "type" : "long"
                                      },
                                      "count" : {
                                        "type" : "long"
                                      },
                                      "decode" : {
                                        "type" : "long"
                                      },
                                      "toolarge" : {
                                        "type" : "long"
                                      },
                                      "unavailable" : {
                                        "type" : "long"
                                      },
                                      "forbidden" : {
                                        "type" : "long"
                                      },
                                      "method" : {
                                        "type" : "long"
                                      },
                                      "notfound" : {
                                        "type" : "long"
                                      },
                                      "invalidquery" : {
                                        "type" : "long"
                                      },
                                      "ratelimit" : {
                                        "type" : "long"
                                      },
                                      "closed" : {
                                        "type" : "long"
                                      },
                                      "unauthorized" : {
                                        "type" : "long"
                                      }
                                    }
                                  },
                                  "valid" : {
                                    "properties" : {
                                      "notmodified" : {
                                        "type" : "long"
                                      },
                                      "count" : {
                                        "type" : "long"
                                      },
                                      "ok" : {
                                        "type" : "long"
                                      },
                                      "accepted" : {
                                        "type" : "long"
                                      }
                                    }
                                  },
                                  "unset" : {
                                    "type" : "long"
                                  },
                                  "request" : {
                                    "properties" : {
                                      "count" : {
                                        "type" : "long"
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          },
                          "server" : {
                            "properties" : {
                              "request" : {
                                "properties" : {
                                  "count" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "concurrent" : {
                                "properties" : {
                                  "wait" : {
                                    "properties" : {
                                      "ms" : {
                                        "type" : "long"
                                      }
                                    }
                                  }
                                }
                              },
                              "response" : {
                                "properties" : {
                                  "count" : {
                                    "type" : "long"
                                  },
                                  "errors" : {
                                    "properties" : {
                                      "count" : {
                                        "type" : "long"
                                      },
                                      "toolarge" : {
                                        "type" : "long"
                                      },
                                      "validate" : {
                                        "type" : "long"
                                      },
                                      "ratelimit" : {
                                        "type" : "long"
                                      },
                                      "queue" : {
                                        "type" : "long"
                                      },
                                      "closed" : {
                                        "type" : "long"
                                      },
                                      "forbidden" : {
                                        "type" : "long"
                                      },
                                      "concurrency" : {
                                        "type" : "long"
                                      },
                                      "unauthorized" : {
                                        "type" : "long"
                                      },
                                      "internal" : {
                                        "type" : "long"
                                      },
                                      "decode" : {
                                        "type" : "long"
                                      },
                                      "method" : {
                                        "type" : "long"
                                      }
                                    }
                                  },
                                  "valid" : {
                                    "properties" : {
                                      "ok" : {
                                        "type" : "long"
                                      },
                                      "accepted" : {
                                        "type" : "long"
                                      },
                                      "count" : {
                                        "type" : "long"
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          },
                          "decoder" : {
                            "properties" : {
                              "deflate" : {
                                "properties" : {
                                  "content-length" : {
                                    "type" : "long"
                                  },
                                  "count" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "gzip" : {
                                "properties" : {
                                  "content-length" : {
                                    "type" : "long"
                                  },
                                  "count" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "uncompressed" : {
                                "properties" : {
                                  "content-length" : {
                                    "type" : "long"
                                  },
                                  "count" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "reader" : {
                                "properties" : {
                                  "size" : {
                                    "type" : "long"
                                  },
                                  "count" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "missing-content-length" : {
                                "properties" : {
                                  "count" : {
                                    "type" : "long"
                                  }
                                }
                              }
                            }
                          },
                          "processor" : {
                            "properties" : {
                              "metric" : {
                                "properties" : {
                                  "decoding" : {
                                    "properties" : {
                                      "errors" : {
                                        "type" : "long"
                                      },
                                      "count" : {
                                        "type" : "long"
                                      }
                                    }
                                  },
                                  "validation" : {
                                    "properties" : {
                                      "errors" : {
                                        "type" : "long"
                                      },
                                      "count" : {
                                        "type" : "long"
                                      }
                                    }
                                  },
                                  "transformations" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "sourcemap" : {
                                "properties" : {
                                  "counter" : {
                                    "type" : "long"
                                  },
                                  "decoding" : {
                                    "properties" : {
                                      "errors" : {
                                        "type" : "long"
                                      },
                                      "count" : {
                                        "type" : "long"
                                      }
                                    }
                                  },
                                  "validation" : {
                                    "properties" : {
                                      "errors" : {
                                        "type" : "long"
                                      },
                                      "count" : {
                                        "type" : "long"
                                      }
                                    }
                                  }
                                }
                              },
                              "transaction" : {
                                "properties" : {
                                  "decoding" : {
                                    "properties" : {
                                      "errors" : {
                                        "type" : "long"
                                      },
                                      "count" : {
                                        "type" : "long"
                                      }
                                    }
                                  },
                                  "validation" : {
                                    "properties" : {
                                      "errors" : {
                                        "type" : "long"
                                      },
                                      "count" : {
                                        "type" : "long"
                                      }
                                    }
                                  },
                                  "transformations" : {
                                    "type" : "long"
                                  },
                                  "transactions" : {
                                    "type" : "long"
                                  },
                                  "spans" : {
                                    "type" : "long"
                                  },
                                  "stacktraces" : {
                                    "type" : "long"
                                  },
                                  "frames" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "error" : {
                                "properties" : {
                                  "decoding" : {
                                    "properties" : {
                                      "errors" : {
                                        "type" : "long"
                                      },
                                      "count" : {
                                        "type" : "long"
                                      }
                                    }
                                  },
                                  "validation" : {
                                    "properties" : {
                                      "errors" : {
                                        "type" : "long"
                                      },
                                      "count" : {
                                        "type" : "long"
                                      }
                                    }
                                  },
                                  "transformations" : {
                                    "type" : "long"
                                  },
                                  "errors" : {
                                    "type" : "long"
                                  },
                                  "stacktraces" : {
                                    "type" : "long"
                                  },
                                  "frames" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "span" : {
                                "properties" : {
                                  "transformations" : {
                                    "type" : "long"
                                  }
                                }
                              }
                            }
                          },
                          "sampling" : {
                            "properties" : {
                              "transactions_dropped" : {
                                "type" : "long"
                              },
                              "tail" : {
                                "properties" : {
                                  "dynamic_service_groups" : {
                                    "type" : "long"
                                  },
                                  "storage" : {
                                    "properties" : {
                                      "lsm_size" : {
                                        "type" : "long"
                                      },
                                      "value_log_size" : {
                                        "type" : "long"
                                      }
                                    }
                                  },
                                  "events" : {
                                    "properties" : {
                                      "processed" : {
                                        "type" : "long"
                                      },
                                      "dropped" : {
                                        "type" : "long"
                                      },
                                      "stored" : {
                                        "type" : "long"
                                      },
                                      "sampled" : {
                                        "type" : "long"
                                      },
                                      "head_unsampled" : {
                                        "type" : "long"
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      },
                      "libbeat" : {
                        "properties" : {
                          "config" : {
                            "properties" : {
                              "module" : {
                                "properties" : {
                                  "running" : {
                                    "type" : "long"
                                  },
                                  "starts" : {
                                    "type" : "long"
                                  },
                                  "stops" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "reloads" : {
                                "type" : "long"
                              }
                            }
                          },
                          "output" : {
                            "properties" : {
                              "events" : {
                                "properties" : {
                                  "acked" : {
                                    "type" : "long"
                                  },
                                  "active" : {
                                    "type" : "long"
                                  },
                                  "batches" : {
                                    "type" : "long"
                                  },
                                  "dropped" : {
                                    "type" : "long"
                                  },
                                  "duplicates" : {
                                    "type" : "long"
                                  },
                                  "failed" : {
                                    "type" : "long"
                                  },
                                  "total" : {
                                    "type" : "long"
                                  },
                                  "toomany" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "read" : {
                                "properties" : {
                                  "bytes" : {
                                    "type" : "long"
                                  },
                                  "errors" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "type" : {
                                "type" : "keyword"
                              },
                              "write" : {
                                "properties" : {
                                  "bytes" : {
                                    "type" : "long"
                                  },
                                  "errors" : {
                                    "type" : "long"
                                  }
                                }
                              }
                            }
                          },
                          "pipeline" : {
                            "properties" : {
                              "clients" : {
                                "type" : "long"
                              },
                              "events" : {
                                "properties" : {
                                  "active" : {
                                    "type" : "long"
                                  },
                                  "dropped" : {
                                    "type" : "long"
                                  },
                                  "failed" : {
                                    "type" : "long"
                                  },
                                  "filtered" : {
                                    "type" : "long"
                                  },
                                  "published" : {
                                    "type" : "long"
                                  },
                                  "retry" : {
                                    "type" : "long"
                                  },
                                  "total" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "queue" : {
                                "properties" : {
                                  "acked" : {
                                    "type" : "long"
                                  }
                                }
                              }
                            }
                          }
                        }
                      },
                      "system" : {
                        "properties" : {
                          "load" : {
                            "properties" : {
                              "1" : {
                                "type" : "double"
                              },
                              "15" : {
                                "type" : "double"
                              },
                              "5" : {
                                "type" : "double"
                              },
                              "norm" : {
                                "properties" : {
                                  "1" : {
                                    "type" : "double"
                                  },
                                  "15" : {
                                    "type" : "double"
                                  },
                                  "5" : {
                                    "type" : "double"
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  },
                  "tags" : {
                    "type" : "keyword"
                  },
                  "timestamp" : {
                    "format" : "date_time",
                    "type" : "date"
                  }
                }
              },
              "cluster_uuid" : {
                "type" : "keyword"
              },
              "interval_ms" : {
                "type" : "long"
              },
              "source_node" : {
                "properties" : {
                  "host" : {
                    "type" : "keyword"
                  },
                  "ip" : {
                    "type" : "keyword"
                  },
                  "name" : {
                    "type" : "keyword"
                  },
                  "transport_address" : {
                    "type" : "keyword"
                  },
                  "uuid" : {
                    "type" : "keyword"
                  }
                }
              },
              "timestamp" : {
                "format" : "date_time",
                "type" : "date"
              },
              "type" : {
                "type" : "keyword"
              }
            }
          }
        },
        "aliases" : { }
      },
      ".monitoring-es" : {
        "order" : 0,
        "version" : 8010099,
        "index_patterns" : [
          ".monitoring-es-7-*"
        ],
        "settings" : {
          "index" : {
            "format" : "7",
            "codec" : "best_compression",
            "number_of_shards" : "1",
            "auto_expand_replicas" : "0-1",
            "number_of_replicas" : "0"
          }
        },
        "mappings" : {
          "_doc" : {
            "date_detection" : false,
            "dynamic" : false,
            "properties" : {
              "cluster_uuid" : {
                "type" : "keyword"
              },
              "state_uuid" : {
                "type" : "keyword"
              },
              "timestamp" : {
                "type" : "date",
                "format" : "date_time"
              },
              "interval_ms" : {
                "type" : "long"
              },
              "type" : {
                "type" : "keyword"
              },
              "source_node" : {
                "properties" : {
                  "uuid" : {
                    "type" : "keyword"
                  },
                  "host" : {
                    "type" : "keyword"
                  },
                  "transport_address" : {
                    "type" : "keyword"
                  },
                  "ip" : {
                    "type" : "keyword"
                  },
                  "name" : {
                    "type" : "keyword"
                  },
                  "timestamp" : {
                    "type" : "date",
                    "format" : "date_time"
                  }
                }
              },
              "indices_stats" : {
                "properties" : {
                  "_all" : {
                    "properties" : {
                      "primaries" : {
                        "properties" : {
                          "docs" : {
                            "properties" : {
                              "count" : {
                                "type" : "long"
                              }
                            }
                          },
                          "indexing" : {
                            "properties" : {
                              "index_total" : {
                                "type" : "long"
                              },
                              "index_time_in_millis" : {
                                "type" : "long"
                              }
                            }
                          },
                          "search" : {
                            "properties" : {
                              "query_total" : {
                                "type" : "long"
                              },
                              "query_time_in_millis" : {
                                "type" : "long"
                              }
                            }
                          },
                          "bulk" : {
                            "properties" : {
                              "total_operations" : {
                                "type" : "long"
                              },
                              "total_time_in_millis" : {
                                "type" : "long"
                              },
                              "total_size_in_bytes" : {
                                "type" : "long"
                              },
                              "avg_time_in_millis" : {
                                "type" : "long"
                              },
                              "avg_size_in_bytes" : {
                                "type" : "long"
                              }
                            }
                          }
                        }
                      },
                      "total" : {
                        "properties" : {
                          "docs" : {
                            "properties" : {
                              "count" : {
                                "type" : "long"
                              }
                            }
                          },
                          "indexing" : {
                            "properties" : {
                              "index_total" : {
                                "type" : "long"
                              },
                              "index_time_in_millis" : {
                                "type" : "long"
                              }
                            }
                          },
                          "search" : {
                            "properties" : {
                              "query_total" : {
                                "type" : "long"
                              },
                              "query_time_in_millis" : {
                                "type" : "long"
                              }
                            }
                          },
                          "bulk" : {
                            "properties" : {
                              "total_operations" : {
                                "type" : "long"
                              },
                              "total_time_in_millis" : {
                                "type" : "long"
                              },
                              "total_size_in_bytes" : {
                                "type" : "long"
                              },
                              "avg_time_in_millis" : {
                                "type" : "long"
                              },
                              "avg_size_in_bytes" : {
                                "type" : "long"
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              },
              "index_stats" : {
                "properties" : {
                  "index" : {
                    "type" : "keyword"
                  },
                  "primaries" : {
                    "properties" : {
                      "docs" : {
                        "properties" : {
                          "count" : {
                            "type" : "long"
                          }
                        }
                      },
                      "fielddata" : {
                        "properties" : {
                          "memory_size_in_bytes" : {
                            "type" : "long"
                          },
                          "evictions" : {
                           ...
```

**Comment by idegtiarenko** [comment] 2023-02-27 13:36
Looks like a duplicate of https://github.com/elastic/elasticsearch/issues/93271

**Closed by idegtiarenko** 2023-02-27 13:36 UTC
Labels: :Distributed/Snapshot/Restore, >test-failure, Team:Distributed
