### ISSUE TITLE
Failure to catch misconfigured Java clients

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#7854] opened 2014-09-24 11:43 UTC
The issue elasticsearch/elasticsearch#7840 was not caught by our test framework.
The suspected reason is that our tests with a Java TransportClient are always run in the the same JVM as data nodes servicing requests and as such all of the module registrations for handling things like transport streams are successfully registered by the data node.
In a more realistic client environment (where TransportClient is housed in a client apps' dedicated JVM) the registration processes are different and bugs like the one above emerge. We should consider changing our test framework to support this configuration.

**Comment by javanna** [comment] 2016-09-14 14:18
This was opened long ago but I am not sure I follow what the problem was and what should be done. Serialization issue caused by transport client and nodes running on the same jvm? A transport client needs to have its modules registered, if that doesn't happen it will throw error. Maybe we didn't have enough tests or those weren't using the transport client simply but only client nodes?

**Comment by clintongormley** [comment] 2016-11-25 18:49
This doesn't seem to have recurred in the last two years.  Closing

**Closed by clintongormley** 2016-11-25 18:49 UTC
Labels: :Java API, adoptme, bug, test
