### ISSUE TITLE
scripted_metric aggregation is very slow in v2.3.3

### ISSUE THREAD

**Issue by Hexer338** [elastic/elasticsearch#20097] opened 2016-08-22 09:23 UTC
**Elasticsearch version**: v2.3.3

**Plugins installed**: [murmur3]

**JVM version**:
      * "version" : "1.8.0_91",
      * "vm_name" : "OpenJDK 64-Bit Server VM",
      * "vm_version" : "25.91-b14",
      * "vm_vendor" : "Oracle Corporation",

**OS version**: Linux

**Description of the problem including expected versus actual behavior**:
Scripted_metric aggregations are performing very slow when compared to v2.0.0.

**Steps to reproduce**:
Iam running Elasticsearch v2.3.3 and Elasticsearch v2.0.0 in docker.
 I have 1 million documents in index with following mapping:
```js
               "units": {
                  "type": "double"
               },
               "unit_price": {
                  "type": "double"
```
Used the following esQuery to test.

```js
{
   "size": 0,
   "aggregations": {
      "__filtered__": {
         "filter": {
            "bool": {
               "should": [
                  {
                     "exists": {
                        "field": "units"
                     }
                  },
                  {
                     "exists": {
                        "field": "unit_price"
                     }
                  }
               ]
            }
         },
         "aggs": {
            "test_aggregation": {
               "scripted_metric": {
                  "params": {
                     "_agg": {},
                     "global": {}
                  },
                  "reduce_params": {
                     "r_v": [],
                     "r_v_args": []
                  },
                  "init_script": "_agg['r_v_map'] = [];_agg['r_v_combine'] = null;",
                  "map_script": "result = 0;a = [doc['units'].value, doc['unit_price'].value, doc['units'].value]; for (i in a) {result += i;};b = a;a = null;for (i in b) {result +=i;};c = b; b = null;for (i in c) {result +=i;};_agg['r_v_map'].add(result);",
                  "combine_script": "args = _agg['r_v_map'];result = 0; for (a in args) {result += a};_agg['r_v_combine'] = result;_agg['r_v_map'] = null; _agg;",
                  "reduce_script": "for (arg in _aggs){if (arg != null) {if (arg['r_v_combine'] != null){r_v_args.add(arg['r_v_combine']);};};};args = r_v_args;result = 0; for (a in args) {result += a};return result"
               }
            }
         }
      }
   }
}
```
The **performance** of the query is **significantly slow** in v2.3.3 when compared to v2.0.0.
It is taking 98 seconds in v2.3.3 when compared to 2 seconds in v2.0.0.
I attached es responses below.
 
**Provide logs (if relevant)**:
**Es Response for above query in v2.3.3**
```js
{
   "took": 98031,
   "timed_out": false,
   "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
   },
   "hits": {
      "total": 1092823,
      "max_score": 0,
      "hits": []
   },
   "aggregations": {
      "__filtered__": {
         "doc_count": 1092823,
         "test_aggregation": {
            "value": 1030923404.8491706
         }
      }
   }
}
```

**Es Response for above query in v2.0.0**
```js
{
   "took": 1428,
   "timed_out": false,
   "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
   },
   "hits": {
      "total": 1092823,
      "max_score": 0,
      "hits": []
   },
   "aggregations": {
      "__filtered__": {
         "doc_count": 1092823,
         "test_aggregation": {
            "value": 1030923404.849173
         }
      }
   }
}
```
#### Elasticsearch version and jvm version for v2.0.0:
**Elasticsearch version**: v2.0.0

**Plugins installed**: [murmur3]

**JVM version**:
        * "version" : "1.8.0_66-internal",
        * "vm_name" : "OpenJDK 64-Bit Server VM",
        * "vm_version" : "25.66-b17",
        * "vm_vendor" : "Oracle Corporation"

**Comment by jpountz** [comment] 2016-08-22 13:26
I am wondering that the difference might be related to how Groovy compiles the script, using a primitive type in 2.0.0 and slow big decimals in 2.3.3. Can you capture some [hot threads](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-hot-threads.html) while the query is running? Also can you try to modify your `map` script to force `result` to be a `double` rather than a BigDecimal?

**Comment by Hexer338** [comment] 2016-08-22 15:39
Forcing `result` to be `double` seems to be fixing the issue. Queries are much faster now.

[Here is the gist containing `hot threads` for both cases (not forcing `result` to double, forcing `result` to double)] (https://gist.github.com/Hexer338/5f117879cb211d90cf65ce9c0e61844b)

**Comment by rmuir** [comment] 2016-08-22 16:11
The reason you see `MutableCallSite.setTarget` is because groovy's invokedynamic code has very simplistic (read: trappy as hell) inline caching that can really only handle one type per callsite. it will just flip back and forth when it sees new types.

So the change is more likely related to that (changing the default to be invokedynamic).

**Comment by jpountz** [comment] 2016-08-23 13:09
Closing this one since a workaround has been provided and the root cause will be adressed by #20017.

**Closed by jpountz** 2016-08-23 13:09 UTC
Labels: :Aggregations, :Scripting, feedback_needed
