### ISSUE TITLE
Lots of ReplicationTasks sitting around

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#19794] opened 2016-08-03 22:58 UTC
User on the [forum](https://discuss.elastic.co/t/elasticsearch-garbage-collection-issue/56143/8) was seeing memory creeping up and up and up slowly, having to restart nodes. It turns out that he's accumulating `ReplicationTask`s in the task manager's map. We currently have no idea *why* they are sticking around, but they are.

I'm marking this as a task manager issue even though it may very well be a "something else" issue. The task manager, but dint of being the lens through which we can look at Elasticsearch's guts is where we are starting.

**Comment by wadey** [comment] 2016-08-04 01:44
This seems suspicious: https://github.com/elastic/elasticsearch/blob/v2.3.3/core/src/main/java/org/elasticsearch/transport/RequestHandlerRegistry.java#L78-L80

This section is only unregistering the task if it fails. The only other way unregister gets called for a task is when `handler` calls `channel.sendResponse` (because TransportChannelWrapper unregisters it then). Are there any cases where `sendResponse` might not be getting called by the handler?

**Comment by imotov** [comment] 2016-08-04 15:38
@wadey  If `sendResponse` is not getting called it's a problem in itself. We can figure out where it happens by getting a list of currently running/leaking tasks or a heapdump.

**Comment by s1monw** [comment] 2016-08-04 15:48
> This section is only unregistering the task if it fails. The only other way unregister gets called for a task is when handler calls channel.sendResponse (because TransportChannelWrapper unregisters it then). Are there any cases where sendResponse might not be getting called by the handler?

We always send a response even in the case of an exception. I wonder if they pile up due to a node connection drop and we wait for a cluster state update to retry? Do they go away at some point? We wait I think 60 sec by default so they might pile up in the case of a hick-up ?

**Comment by wadey** [comment] 2016-08-04 16:37
> We can figure out where it happens by getting a list of currently running/leaking tasks or a heapdump.

@imotov I don't feel comfortable sharing the heapdump as it contains a lot of internal information, but I'm trying to look through it and help debug this (I work with Max the original reporter in the forums). I am going to try to enable debug/trace logging for the related Replication class files to see if I can see any errors or retries happening.

> Do they go away at some point? We wait I think 60 sec by default so they might pile up in the case of a hick-up ?

@s1monw There are ReplicationTasks that are multiple days old inside of the `tasks` map. Example:

![visualvm_1_3_8](https://cloud.githubusercontent.com/assets/18437/17410060/0fbb3b72-5a40-11e6-823d-5f3aa38a81a3.png)

**Comment by imotov** [comment] 2016-08-04 17:20
@wadey Thanks! This is useful. Are most of these tasks say "indices:data/writes/bulk[s]" in the action field? Could you give any more information about the state of the cluster for the last few day? Are all shards available for this index? Have you seen any failures? Did you have a lot of node restarts? Are you using any plugins?

**Comment by dopey** [comment] 2016-08-04 17:45
Hey @imotov. The cluster state has been green (all shards are available) since the last rolling restart which was ~ 1week ago. We did restart 1 node yesterday after we made a request to he `_task` api which caused an OOM on the server, but in general we don't see restarts until we need to do a rolling restart of the whole cluster due to memory pressure. Nothing in the logs to indicate any failures. No connection dropping, no master elections, just `create mapping` and `update mapping` lines from when the log index rolls over. We use 3 plugins: elasticsearch-statsd, elasticsearch-head, and search-guard-ssl. We have 2 clusters: a staging cluster with 3 servers, and a production cluster with 5 servers. The staging cluster has ~400million documents and the production one has ~1billion. We normally have ~2.5weeks in staging before we need to rolling restart the cluster, and ~1.5 weeks in production.

Looking into the action field question.

**Comment by wadey** [comment] 2016-08-04 18:14
> Are most of these tasks say "indices:data/writes/bulk[s]" in the action field?

@imotov I used [MAT](http://www.eclipse.org/mat/) to do a group by, here are the ReplicationTasks grouped by `action`:

<img width="546" alt="eclipse_memory_analyzer" src="https://cloud.githubusercontent.com/assets/18437/17413048/b3bce4ca-5a4d-11e6-9837-8f9d993b32e2.png">

**Comment by imotov** [comment] 2016-08-04 19:42
@wadey and @dopey thanks a lot for providing an awesome bug report. The information that you provided and timely responses were really helpful and I was able to reproduce the issue locally. It looks like an issue is in the `searchguard-ssl` plugin that you are using. I opened floragunncom/search-guard-ssl/pull/31 It fixes the issue for me. Since it doesn't seem to be an elasticsearch bug, I am going to close this issue for now. Please, feel free to reopen if needed.

**Closed by imotov** 2016-08-04 19:42 UTC
Labels: :Task Manager, bug, v2.3.3

**Comment by floragunncom** [comment] 2016-08-09 21:45
Bug is fixed with version 15 of Search Guard SSL (released today). Thx @imotov for providing a fix.

**Comment by wadey** [comment] 2016-08-10 18:01
Thanks @imotov @nik9000 @floragunncom (and anyone else I missed) for the quick work in investigating and getting this resolved!

**Comment by trentcioran** [comment] 2016-08-17 18:01
Hi, any idea when this fix will made available on a new version of elasticsearch? Thanks

**Comment by jasontedor** [comment] 2016-08-17 18:05
@trentcioran The issue is with the plugin, not Elasticsearch, and a fix for the plugin has been made [available](https://github.com/floragunncom).
