### ISSUE TITLE
Test failure for :qa:mixed-cluster:v7.0.0#mixedClusterTest

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#59284] opened 2020-07-09 09:29 UTC
**Build scan**: https://gradle-enterprise.elastic.co/s/nvus6pdwrc5wy

**Repro line**: none provided by the build but the CI build has executed the following command:

```
./gradlew --parallel --scan --build-cache -Dorg.elasticsearch.build.cache.url=https://gradle-enterprise.elastic.co/cache/ -S --parallel --max-workers=16 -Dbwc.checkout.align=true -Dignore.tests.seed v7.0.0#bwcTest
```

**Reproduces locally?**: no

**Applicable branches**: `7.x`

**Failure history**: Only noticed this once so far.

**Failure excerpt**:

The test starts four nodes: `v7.0.0-0`, `v7.0.0-1`, `v7.0.0-2` and `v7.0.0-3` and fails with:

```
TestClustersException: process was found dead while waiting for ports files, node{:qa:mixed-cluster:v7.0.0-2}
```

Further above in the logs we can see the cause for this failure. Starting `v7.0.0-2` has failed with:

```
01:49:55 » ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [v7.0.0-2] fatal error in thread [main], exiting
01:49:55 »  java.lang.AssertionError: null
01:49:55 »  	at org.elasticsearch.monitor.os.OsProbe.readSingleLine(OsProbe.java:189) ~[elasticsearch-7.0.0.jar:7.0.0]
01:49:55 »  	at org.elasticsearch.monitor.os.OsProbe.readSysFsCgroupCpuAcctCpuAcctUsage(OsProbe.java:277) ~[elasticsearch-7.0.0.jar:7.0.0]
01:49:55 »  	at org.elasticsearch.monitor.os.OsProbe.getCgroupCpuAcctUsageNanos(OsProbe.java:264) ~[elasticsearch-7.0.0.jar:7.0.0]
01:49:55 »  	at org.elasticsearch.monitor.os.OsProbe.getCgroup(OsProbe.java:483) ~[elasticsearch-7.0.0.jar:7.0.0]
01:49:55 »  	at org.elasticsearch.monitor.os.OsProbe.osStats(OsProbe.java:603) ~[elasticsearch-7.0.0.jar:7.0.0]
01:49:55 »  	at org.elasticsearch.monitor.os.OsService.<init>(OsService.java:49) ~[elasticsearch-7.0.0.jar:7.0.0]
01:49:55 »  	at org.elasticsearch.monitor.MonitorService.<init>(MonitorService.java:46) ~[elasticsearch-7.0.0.jar:7.0.0]
01:49:55 »  	at org.elasticsearch.node.Node.<init>(Node.java:365) ~[elasticsearch-7.0.0.jar:7.0.0]
01:49:55 »  	at org.elasticsearch.node.Node.<init>(Node.java:251) ~[elasticsearch-7.0.0.jar:7.0.0]
01:49:55 »  	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:211) ~[elasticsearch-7.0.0.jar:7.0.0]
01:49:55 »  	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:211) ~[elasticsearch-7.0.0.jar:7.0.0]
01:49:55 »  	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:325) ~[elasticsearch-7.0.0.jar:7.0.0]
01:49:55 »  	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.0.0.jar:7.0.0]
01:49:55 »  	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-7.0.0.jar:7.0.0]
01:49:55 »  	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.0.0.jar:7.0.0]
01:49:55 »  	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-7.0.0.jar:7.0.0]
01:49:55 »  	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.0.0.jar:7.0.0]
01:49:55 »  	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) ~[elasticsearch-7.0.0.jar:7.0.0]
01:49:55 »  	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.0.0.jar:7.0.0]
```

The assertion checks whether the file `/sys/fs/cgroup/cpuacct/user.slice/cpuacct.usage` contains exactly one line. For all nodes but `v7.0.0-2` this has succeeded (`user.slice` is dynamically determined by parsing `/proc/self/cgroup` - see `OsProbe#getControlGroups()`).

**Comment by rjernst** [comment] 2020-08-05 22:25
This appears to be rare, as I have not been able to find additional cases. The assertion output does not help diagnose the issue, since we are not sure what exactly the contents of the cpuacct.usage file were. I've opened #60796 to improve that if we ever hit this again, but in the meantime I'm closing this since it has not reproduced as far as I can tell.

**Closed by rjernst** 2020-08-05 22:26 UTC
Labels: :Core/Infra/Core, >test-failure, Team:Core/Infra
