### ISSUE TITLE
Bulk freezes

### ISSUE THREAD

**Issue by kiryam** [elastic/elasticsearch#10723] opened 2015-04-22 13:15 UTC
If I send this json to elasticsearch, cluster was freezes.
https://dl.dropboxusercontent.com/u/1003531/bulk_freeze.txt

**Comment by imotov** [comment] 2015-04-22 19:06
@kiryam which version of elasticsearch is this? This bug looks very similar to #7266, which was fixed in 1.4.0 and 1.3.3.

**Comment by kiryam** [comment] 2015-04-22 19:49
{
"status": 200,
"name": "process",
"cluster_name": "elasticsearch",
"version": {
"number": "1.4.4",
"build_hash": "c88f77ffc81301dfa9dfd81ca2232f09588bd512",
"build_timestamp": "2015-02-19T13:05:36Z",
"build_snapshot": false,
"lucene_version": "4.10.3"
},
"tagline": "You Know, for Search"
}

**Comment by imotov** [comment] 2015-04-22 20:17
@kiryam could you share the mapping for this index and type? I cannot reproduce the issue with v1.4.4 and default mapping?

**Comment by kiryam** [comment] 2015-04-23 04:49
@imotov https://gist.github.com/kiryam/93df99e99ffaf397072e

**Comment by imotov** [comment] 2015-04-23 14:06
@kiryam How are `ru` and `exact` analyzers defined? Could you post settings for this index? Are you using any analysis plugins? If you do which versions of the plugins are you using?

**Comment by kiryam** [comment] 2015-04-23 14:10
@imotov https://gist.github.com/kiryam/94a8c418e09025d7ef77
```
/usr/share/elasticsearch/plugins/analysis-morphology# ls
elasticsearch-analysis-morphology-1.2.0.jar  english-4.6.0.jar	morph-4.6.0.jar  russian-4.6.0.jar
```

**Comment by imotov** [comment] 2015-04-23 22:20
@kiryam the problem is in this regular expression:

```
exact_rstrip: 
        type: "pattern_replace"
        pattern: "[^#@a-zA-Zа-яА-Я0-9$%°~_]+($| )"
        replacement: "$1"
```
It's just takes too long to execute this regex on the string that consists of a million of "\" characters. I just did an [experiment with 50k string](https://gist.github.com/imotov/f56d090981e72dc87828) and it takes 17 seconds to process on my machine. 

What are you trying to achieve here?

**Comment by kiryam** [comment] 2015-04-24 07:44
@imotov I want to remove special characters exclude "[^#@a-zA-Zа-яА-Я0-9$%°~_] in end of word

**Comment by clintongormley** [comment] 2015-04-24 13:45
Could you replace all three character filters with the following?

    PUT /test?pretty
    {
      "settings": {
        "index": {
          "analysis": {
            "analyzer": {
              "exact": {
                "tokenizer": "whitespace",
                "char_filter": [
                  "strip_chars"
                ]
              }
            },
            "char_filter": {
              "strip_chars": {
                "type": "pattern_replace",
                "pattern": "[^#@a-zA-Zа-яА-Я0-9$%°~_]+",
                "replacement": " "
              }
            }
          }
        }
      }
    }

With @imotov's test string, this is pretty much instantaneous.

**Closed** 2015-04-24 13:47 UTC
Labels: non-issue
