### ISSUE TITLE
Total shards per host limit

### ISSUE THREAD

**Issue by ViggoC** [elastic/elasticsearch#81029] opened 2021-11-25 03:45 UTC
The recommended heap size of es is around 30 g, and the memory of the server is usually large, so it is common to deploy multiple nodes on a host. 

Now ES has `index.routing.allocation.total_shards_per_node` for an index is set to avoid hot spot node. But it cannot limit the total number of shards of an index on a host. Therefore, a host may become a hot spot. 

Can we consider adding a setting like `total_shard_per_host` to avoid hot spot host?

**Comment by DaveCTurner** [comment] 2021-11-25 08:42
This is effectively a duplicate of https://github.com/elastic/elasticsearch/issues/17213, which is something we're working on addressing. Therefore I'm closing this.

**Closed by DaveCTurner** 2021-11-25 08:42 UTC
Labels: >enhancement, needs:triage
