### ISSUE TITLE
[CI] Tripping assertion in PeerFinder#closePeers

### ISSUE THREAD

**Issue by fcofdez** [elastic/elasticsearch#99023] opened 2023-08-29 18:28 UTC
**Build scan:**
https://gradle-enterprise.elastic.co/s/bcxstpjolnb2q/tests/:x-pack:plugin:ccr:internalClusterTest/org.elasticsearch.xpack.ccr.FollowerFailOverIT/testReadRequestsReturnLatestMappingVersion

**Reproduction line:**
```
./gradlew ':x-pack:plugin:ccr:internalClusterTest' --tests "org.elasticsearch.xpack.ccr.FollowerFailOverIT.testReadRequestsReturnLatestMappingVersion" -Dtests.seed=A75C1F0C6F541957 -Dtests.locale=fr-CA -Dtests.timezone=America/Tijuana -Druntime.java=20
```

**Applicable branches:**
8.10

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ccr.FollowerFailOverIT&tests.test=testReadRequestsReturnLatestMappingVersion

**Failure excerpt:**
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=498, name=elasticsearch[follower2][clusterApplierService#updateTask][T#1], state=RUNNABLE, group=TGRP-FollowerFailOverIT]

  at __randomizedtesting.SeedInfo.seed([A75C1F0C6F541957:A564CB31A58082CC]:0)

  Caused by: java.lang.AssertionError: (No message provided)

    at __randomizedtesting.SeedInfo.seed([A75C1F0C6F541957]:0)
    at org.elasticsearch.discovery.PeerFinder.closePeers(PeerFinder.java:182)
    at org.elasticsearch.cluster.coordination.Coordinator.onClusterStateApplied(Coordinator.java:415)
    at org.elasticsearch.cluster.coordination.Coordinator.lambda$handleApplyCommit$8(Coordinator.java:403)
    at org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.lambda$map$0(ActionListenerImplementations.java:108)
    at org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:89)
    at org.elasticsearch.cluster.service.ClusterApplierService$ClusterApplyActionListener.onResponse(ClusterApplierService.java:598)
    at org.elasticsearch.cluster.service.ClusterApplierService$ClusterApplyActionListener.onResponse(ClusterApplierService.java:569)
    at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:439)
    at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:154)
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:916)
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:217)
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:183)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    at java.lang.Thread.run(Thread.java:1623)

```

**Comment by DaveCTurner** [comment] 2023-10-12 09:14
This is fairly pervasive, we can't mute our way out of it. Does that mean it's a `blocker`? Certainly needs fairly urgent attention IMO.

**Comment by kingherc** [comment] 2023-10-12 10:59
If this is urgent @DaveCTurner , I can take a look at it to see if I can somehow handle it in a manageable timeframe.

**Comment by DaveCTurner** [comment] 2023-10-12 11:03
Thanks Iraklis; I suspect we don't _need_ to assert this here, but still it indicates we're in a surprising state and I'd like to understand why before just suppressing it. Presumably we're completing the cluster state update (which leads to calling `PeerFinder#closePeers`) before calling `PeerFinder#deactivate`? Or maybe we became LEADER and then CANDIDATE again straight away and then the cluster state update completes? Somewhat surprising that this doesn't seem to reproduce in `CoordinatorTests` too.

**Comment by DaveCTurner** [comment] 2023-10-12 11:07
Ah I think I see it, this looks suspicious:

https://github.com/elastic/elasticsearch/blob/d411acecbcbd029ebadbfa533a07c70330d454c8/server/src/main/java/org/elasticsearch/cluster/coordination/Coordinator.java#L417-L421

We need to check `mode` and call `PeerFinder#closePeers` in the same `synchronized` block I reckon. If not, we could indeed fall back to `CANDIDATE` and reactivate the `PeerFinder` before we get around to closing it. That's not something the `CoordinatorTests` would catch because they're single-threaded.

**Comment by kingherc** [comment] 2023-10-12 11:19
Thanks for the hints @DaveCTurner ! I can follow up with seeing if I can create a test to reproduce this and fix the synchronized block.

**Comment by kingherc** [comment] 2023-10-16 13:21
New appearance in duplicate issue https://github.com/elastic/elasticsearch/issues/100830 and specifically https://gradle-enterprise.elastic.co/s/rjfh3k3bkfpkg/tests/:server:internalClusterTest/org.elasticsearch.action.admin.indices.diskusage.IndexDiskUsageAnalyzerIT .

**Closed** 2023-10-17 17:23 UTC
Labels: blocker, >test-failure, :Distributed/Cluster Coordination, Team:Distributed
