### ISSUE TITLE
mapper-extras v7.4.0 dependency missing from maven central

### ISSUE THREAD

**Issue by phillipross** [elastic/elasticsearch#47413] opened 2019-10-01 22:09 UTC
org.elasticsearch.plugin:mapper-extras:7.4.0 appears not to be available in maven central
but is referenced from org.elasticsearch.client:elasticsearch-rest-high-level-client:7.4.0

**Comment by Guillaume-Mayer** [comment] 2019-10-02 06:02
Same for me

**Comment by jimczi** [comment] 2019-10-02 10:15
Thanks for reporting. The dependency was added without the publication of the client jar. I opened https://github.com/elastic/elasticsearch/pull/47430 to fix this and make it available for the next official release (7.4.1 or 7.5.0). Sorry for the trouble.

**Comment by MT-Jacobs** [comment] 2019-10-02 13:41
Does this mean that 7.4.0 is unusable?

**Comment by jimczi** [comment] 2019-10-02 13:53
> Does this mean that 7.4.0 is unusable?

No, that means that you cannot reference any of the QueryBuilder that the mapper-extras module exposes when using the high level rest client. The mapper-extras was not exposed in previous version so this is also not a regression, we could fix the doc to remove any mention of the mapper-extras queries in 7.4.0 to avoid confusion.

**Comment by MT-Jacobs** [comment] 2019-10-02 14:37
So anyone can more or less safely exclude the dependency from their build as long as they don't use the new QueryBuilder features and are careful to remove the exclusion later.

---

For anyone else who comes to this PR, the feature in question is listed in https://www.elastic.co/guide/en/elasticsearch/reference/7.4/release-notes-7.4.0.html:

> Add mapper-extras and the RankFeatureQuery in the hlrc #43713 (issue: #43634)

Details on the RankFeatureQuery - https://www.elastic.co/guide/en/elasticsearch/reference/7.4/query-dsl-rank-feature-query.html

**Comment by jimczi** [comment] 2019-10-02 14:56
Yes that's unfortunate but https://github.com/elastic/elasticsearch/pull/47430 will solve this for the next official release.

**Comment by dadoonet** [comment] 2019-10-02 15:40
Wasn't that possible to publish the missing artefact without changing anything else?

**Comment by jimczi** [comment] 2019-10-02 15:51
> Wasn't that possible to publish the missing artefact without changing anything else?

I am not sure since mapper-extras was not in the previous versions so there's no regression here. Users that want to use classes from this jar will need to wait one more release so that's unfortunate but not a blocker ?

**Comment by dadoonet** [comment] 2019-10-02 16:00
> that's unfortunate but not a blocker

Yeah sure. We can use the 7.3.2 client with 7.4.0 server. Or as mentioned exclude manually the missing jar:

```xml
<dependency>
    <groupId>org.elasticsearch.client</groupId>
    <artifactId>elasticsearch-rest-high-level-client</artifactId>
    <version>7.4.0</version>
    <!-- TODO Remove this with 7.4.1 -->
    <exclusions>
        <exclusion>
            <groupId>org.elasticsearch.plugin</groupId>
            <artifactId>mapper-extras</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

I was just curious why we can't "just" upload, even manually the missing jar as this jar has been generated I guess for 7.4.0 but was just not uploaded to maven central.

**Comment by jimczi** [comment] 2019-10-02 16:28
I thought that the dependency was optional but it's not, the exclusion is required, sorry for the confusion and thanks for chiming in @dadoonet . We're now looking at manually publishing this jar for 7.4.0 and we'll update this issue soon.

**Comment by jimczi** [comment] 2019-10-04 08:11
Thanks to @mgreau the artifact for 7.4.0 should be available now ! Please reopen if any problem arises.

**Comment by dadoonet** [comment] 2019-10-04 09:55
I can confirm that it works very well now. I'm closing the issue then.

**Closed by dadoonet** 2019-10-04 09:55 UTC
Labels: :Core/Features/Java High Level REST Client, >bug
