### ISSUE TITLE
Elasticsearch: ER slow query logs should include information about alias and alias filter

### ISSUE THREAD

**Issue by JalehD** [elastic/elasticsearch#19888] opened 2016-08-09 15:00 UTC
**Elasticsearch version**:
elasticsearch 2.3.4

**Describe the feature**:
Slow Query log to include information when the query is over an index alias. 
Specially if the alis includes a filter this should be visible from slow query log. At the moment these logs don't show any information and look identical when alias is used or not.

**Steps to reproduce**:
 1. install elasticsearch 2.3.4
 2. index some data. example data, use shakespeare data from docs.
 3. create an alias with a filter, as an example: 

POST _aliases/
{
   "actions" : [
       {
           "add" : {
                "index" : "shakespeare",
                "alias" : "shakespeare_lines",
                "filter" : { "type" : {"value":"line"} }
           }
       }
   ]
}

4- configure slow log with a very low threshold 
 index.search.slowlog.threshold.query.trace: 1ms
 index.search.slowlog.threshold.fetch.trace: 1ms

5- query the data 

{
 "query": { "match_all": {} }
}
6- see below log lacking any reference to the alis or the filter.

[2016-08-09 16:10:58,120][INFO ][index.search.slowlog.query] [shakespeare]took[1.1ms], took_millis[1], types[], stats[], search_type[QUERY_THEN_FETCH], total_shards[5], source[{"query":{"match_all":{}}}], extra_source[],

**Comment by javanna** [comment] 2016-08-10 09:43
This sounds like a duplicate of #10044.

**Comment by clintongormley** [comment] 2016-08-10 15:55
Closing in favour of https://github.com/elastic/elasticsearch/issues/10044

**Closed by clintongormley** 2016-08-10 15:55 UTC
Labels: enhancement
