### ISSUE TITLE
[Transform] problems with timeout parameter in Create Transform API

### ISSUE THREAD

**Issue by riemvis** [elastic/elasticsearch#92254] opened 2022-12-09 07:41 UTC
### Elasticsearch Version

8.5

### Java Version

_bundled_

### OS Version

Windows 10

### Problem Description

The documentation of "Create Transform API" (https://www.elastic.co/guide/en/elasticsearch/reference/current/put-transform.html) mentions the availability of the ´timeout´ query parameter an error is reported that it is not supported when trying to use it.
This prevents larger datasets to use transforms as they will timeout (default limit 30s).
The same parameter is implemented correctly in the "Preview Transform API" (https://www.elastic.co/guide/en/elasticsearch/reference/current/preview-transform.html).

### Steps to Reproduce

Open DEV-tools and create any example to PUT a transform and add the '?timeout=60s' to the url.

**Comment by hendrikmuhs** [comment] 2022-12-12 21:29
@riemvis Thanks for the report

I could not reproduce it, can you add:

- the concrete API calls you tried
- the error message you see

I tried it with the kibana sample dataset, e.g. 

```
PUT _transform/t1?timeout=60s
```

Regarding:

> This prevents larger datasets to use transforms as they will timeout (default limit 30s).

The only possible reason I see is a timeout during validation. Validation might be expensive if a lot of indices are involved and in case you use expensive aggregations. To understand the problem, can you share some details about your setup?

It is possible to skip some validations with `?defer_validation=true`, for example the query part. This will allow you to create the transform, however if validations are timing out during creation, your transform will still run into the same problem later. Therefore it would be good to understand your case.

**Comment by hendrikmuhs** [comment] 2022-12-21 16:16
I am closing this issue as I haven't received an answer and this does not reproduce.

@riemvis please re-open the issue if you still have problems with it and include further information as asked above.

**Closed by hendrikmuhs** 2022-12-21 16:16 UTC
Labels: >bug, :ml/Transform, Team:ML
