### ISSUE TITLE
[ES 7.16.1] Wildcard query doesn't work with strings

### ISSUE THREAD

**Issue by mzagrajek** [elastic/elasticsearch#82171] opened 2021-12-31 16:38 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 7.16.1

**Plugins installed**: None

**JVM version** (`java -version`): Needs to be checked.

**OS version** (`uname -a` if on a Unix-like system): Cloud on-premise

**Description of the problem including expected versus actual behavior**:

We upgraded ES from 7.7.1 to 7.16.1 due to Log4j problems. We are using wildcard queries to fetch the data with filters. Those filters can be different type of strings. Rarely they are only numbers like '1690', mostly like 'cls-1023' or '16T0'.

**This wildcardf query doesnt work:**

GET index/_count
{"query":{"bool":{"filter":[{"wildcard":{"testField":{"wildcard":"*15C0*","boost":1.0}}},{"match":{"lang":{"query":"en_gb","operator":"OR","prefix_length":0,"max_expansions":50,"fuzzy_transpositions":true,"lenient":false,"zero_terms_query":"NONE","auto_generate_synonyms_phrase_query":true,"boost":1.0}}},{"match_all":{"boost":1.0}}],"adjust_pure_negative":true,"boost":1.0}}}

**This wildcard query works:**

GET index/_count
{"query":{"bool":{"filter":[{"wildcard":{"testField":{"wildcard":"*8750*","boost":1.0}}},{"match":{"lang":{"query":"en_gb","operator":"OR","prefix_length":0,"max_expansions":50,"fuzzy_transpositions":true,"lenient":false,"zero_terms_query":"NONE","auto_generate_synonyms_phrase_query":true,"boost":1.0}}},{"match_all":{"boost":1.0}}],"adjust_pure_negative":true,"boost":1.0}}}
 
Example of this testField can be:
- 16C0,74C0,74B0,15C0,PE60,EC60
- 16C0
- PE60,EC60
- 74B0
- 74B0,74C0
- 8750

So it is strings separated with commas, that is why we are using wildcard here. 

**Steps to reproduce**: 

1. Query needs to be wildcard
2. Query needs to have string with letters and numbers
3. Query results is 0 despite the data is there
4. Querying with field.keyword helps with wildcard query
5. Querying with field but only integers also work with wildcard query

**Comment by markharwood** [comment] 2022-01-04 09:40
Thanks for raising this.
On first sight it looks like the JSON of your wildcard queries does not contain any wildcard characters so I'm not sure why you are using that syntax instead of the `term` or `match` query types.

The report includes JSON for your queries which is useful but we will need JSON for the mappings and the example documents before we can investigate further.

If you use the `_explain` and `_analyze` apis you should be able to get more insight into what is stored in the index as a result of your mapping configuration and why it doesn't match. 

In the vast majority of no-match cases it is a mapping/query inconsistency rather than a bug in elasticsearch. 

>We upgraded ES from 7.7.1 to 7.16.1 due to Log4j problems.

Did these queries/mappings/docs work OK in 7.7.1?

**Comment by mzagrajek** [comment] 2022-01-04 10:51
Hi @markharwood 
I will try to get all details, meanwhile:


> Did these queries/mappings/docs work OK in 7.7.1?

Yes, it worked, that's why we are confused, there were nothing in release notes about that.

We tried with match, but for this string fields separated by comma it is not working. 
**Example:**
testField is:

-     one doc: 74B0,74C0,8570
-     second doc: 8750

and query:

```
GET testIndex/_count
{"query":{"bool":{"filter":[{"match":{"testField":{"query":"8570","operator":"OR","prefix_length":0,"max_expansions":50,"fuzzy_transpositions":true,"lenient":false,"zero_terms_query":"NONE","auto_generate_synonyms_phrase_query":true,"boost":1}}},{"match":{"lang":{"query":"en_gb","operator":"OR","prefix_length":0,"max_expansions":50,"fuzzy_transpositions":true,"lenient":false,"zero_terms_query":"NONE","auto_generate_synonyms_phrase_query":true,"boost":1}}},{"match_all":{"boost":1}}],"adjust_pure_negative":true,"boost":1}}}
```

Match was only taking the document with the 8570.
I have the same thing in kibana. When I search:
testField: 8570
and testField: *8570* 
I got different results and that would be logical.

**Comment by markharwood** [comment] 2022-01-04 10:57
>Yes, it worked, that's why we are confused,

OK. Can you supply exact JSON for mappings, queries and example documents so we can reproduce?

**Comment by mzagrajek** [comment] 2022-01-04 13:53
[elastic.zip](https://github.com/elastic/elasticsearch/files/7808042/elastic.zip)

**Comment by mzagrajek** [comment] 2022-01-04 13:53
@markharwood i uploaded them in ZIP file :)

**Comment by markharwood** [comment] 2022-01-04 15:11
Using the `_analyze` API I mentioned I can see that the words beginning with numbers are ignored: 
With this simplified setup:
```
DELETE test
PUT test
{
  "mappings": {
    "properties": {
      "marketReleases": {
        "type": "text"
      }
    }
  }
}
POST test/_analyze
{
  "field": "marketReleases",
  "text": ["8570,16C0,74C0,74B0,15C0,PE60,EC60"]
}
```
We can see the provided doc string is indexed as tokens `8570,16c0,74c0,74b0,15c0`, `pe60` and `ec60`.
Perhaps not the best way to index, but let's stick with it for the purposes of this analysis.
Note the `15C0` value has been lower-cased to `15c0`.

The fact that your query used to match `*15CO*` was a bug in wildcard query that was fixed. Wildcard queries are supposed to be case sensitive with what is in the index.
The good news is you can get the old behaviour back by setting `case_insensitive:true` on the wildcard query.
I'll close this as a non-bug if you don't mind.

**Closed by markharwood** 2022-01-04 15:11 UTC
Labels: >bug, :Search/Search, Team:Search

**Comment by mzagrajek** [comment] 2022-01-05 08:19
@markharwood  thank you for the detailed explanation!
