### ISSUE TITLE
[CI] Reproducible Failure in org.elasticsearch.xpack.transform.integration.TransformPivotRestSpecialCasesIT.testIndexTemplateMappingClash

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#71792] opened 2021-04-18 12:24 UTC
The following fails for me locally every time on current master:

```
 ./gradlew ':x-pack:plugin:transform:qa:single-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.transform.integration.TransformPivotRestSpecialCasesIT.testIndexTemplateMappingClash" -Dtests.seed=642C08CC77828612 -Dtests.security.manager=true -Dtests.locale=sv-SE -Dtests.timezone=ECT -Druntime.java=11
```

fails as:

```
org.elasticsearch.xpack.transform.integration.TransformPivotRestSpecialCasesIT > testIndexTemplateMappingClash FAILED
    org.elasticsearch.client.WarningFailureException: method [PUT], host [http://[::1]:32843], URI [_template/special_pivot_template], status line [HTTP/1.1 200 OK]
    Warnings: [Legacy index templates are deprecated and will be removed completely in a future version. Please use composable templates instead.]
    {"acknowledged":true}
        at __randomizedtesting.SeedInfo.seed([642C08CC77828612:4A70332C96BD2688]:0)
        at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:326)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)
        at org.elasticsearch.xpack.transform.integration.TransformPivotRestSpecialCasesIT.testIndexTemplateMappingClash(TransformPivotRestSpecialCasesIT.java:66)
REPRODUCE WITH: ./gradlew ':x-pack:plugin:transform:qa:single-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.transform.integration.TransformPivotRestSpecialCasesIT.testIndexTemplateMappingClash" -Dtests.seed=642C08CC77828612 -Dtests.security.manager=true -Dtests.locale=sv-SE -Dtests.timezone=ECT -Druntime.java=11

Suite: Test class org.elasticsearch.xpack.transform.integration.TransformPivotRestSpecialCasesIT
  1> [2021-04-18T14:22:38,405][INFO ][o.e.x.t.i.TransformPivotRestSpecialCasesIT] [testIndexTemplateMappingClash] before test
  1> [2021-04-18T14:22:38,505][INFO ][o.e.x.t.i.TransformPivotRestSpecialCasesIT] [testIndexTemplateMappingClash] initializing REST clients against [http://[::1]:32843, http://127.0.0.1:33657]
  1> [2021-04-18T14:22:39,809][WARN ][o.e.c.RestClient         ] [testIndexTemplateMappingClash] request [PUT http://[::1]:32843/_template/special_pivot_template] returned 1 warnings: [299 Elasticsearch-8.0.0-SNAPSHOT-b390cbda345d4b6b88831f84e516ce6557297cf6 "Legacy index templates are deprecated and will be removed completely in a future version. Please use composable templates instead."]
  1> [2021-04-18T14:22:39,817][INFO ][o.e.x.t.i.TransformPivotRestSpecialCasesIT] [testIndexTemplateMappingClash] writing audit messages to the log
  1> [2021-04-18T14:22:40,123][INFO ][o.e.x.t.i.TransformPivotRestSpecialCasesIT] [testIndexTemplateMappingClash] after test
  2> REPRODUCE WITH: ./gradlew ':x-pack:plugin:transform:qa:single-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.transform.integration.TransformPivotRestSpecialCasesIT.testIndexTemplateMappingClash" -Dtests.seed=642C08CC77828612 -Dtests.security.manager=true -Dtests.locale=sv-SE -Dtests.timezone=ECT -Druntime.java=11
  2> org.elasticsearch.client.WarningFailureException: method [PUT], host [http://[::1]:32843], URI [_template/special_pivot_template], status line [HTTP/1.1 200 OK]
    Warnings: [Legacy index templates are deprecated and will be removed completely in a future version. Please use composable templates instead.]
    {"acknowledged":true}
        at __randomizedtesting.SeedInfo.seed([642C08CC77828612:4A70332C96BD2688]:0)
        at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:326)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)
        at org.elasticsearch.xpack.transform.integration.TransformPivotRestSpecialCasesIT.testIndexTemplateMappingClash(TransformPivotRestSpecialCasesIT.java:66)
  2> NOTE: leaving temporary files on disk at: /home/brownbear/src/elasticsearch/x-pack/plugin/transform/qa/single-node-tests/build/testrun/javaRestTest/temp/org.elasticsearch.xpack.transform.integration.TransformPivotRestSpecialCasesIT_642C08CC77828612-002
  2> NOTE: test params are: codec=Lucene87, sim=Asserting(RandomSimilarity(queryNorm=false): {}), locale=sv-SE, timezone=ECT
  2> NOTE: Linux 5.8.0-50-generic amd64/Oracle Corporation 11.0.2 (64-bit)/cpus=48,threads=1,free=423123936,total=536870912
  2> NOTE: All tests run in this JVM: [TransformPivotRestSpecialCasesIT]

Tests with failures:
 - org.elasticsearch.xpack.transform.integration.TransformPivotRestSpecialCasesIT.testIndexTemplateMappingClash

1 test completed, 1 failed

=== Log output of node `node{:x-pack:plugin:transform:qa:single-node-tests:javaRestTest-0}` ===

»    ↓ errors and warnings from /home/brownbear/src/elasticsearch/x-pack/plugin/transform/qa/single-node-tests/build/testclusters/javaRestTest-0/logs/javaRestTest.log ↓
» [2021-04-18T14:22:36,838][WARN ][o.e.d.FileBasedSeedHostsProvider] [javaRestTest-0] expected, but did not find, a dynamic hosts list at [/home/brownbear/src/elasticsearch/x-pack/plugin/transform/qa/single-node-tests/build/testclusters/javaRestTest-0/config/unicast_hosts.txt]
»   ↓ last 40 non error or warning messages from /home/brownbear/src/elasticsearch/x-pack/plugin/transform/qa/single-node-tests/build/testclusters/javaRestTest-0/logs/javaRestTest.log ↓
» [2021-04-18T14:22:37,417][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding template [.ml-state] for index patterns [.ml-state*]
» [2021-04-18T14:22:37,464][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding template [.ml-stats] for index patterns [.ml-stats-*]
» [2021-04-18T14:22:37,517][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding component template [metrics-settings]
» [2021-04-18T14:22:37,565][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding component template [logs-mappings]
» [2021-04-18T14:22:37,611][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding component template [metrics-mappings]
» [2021-04-18T14:22:37,653][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding component template [synthetics-settings]
» [2021-04-18T14:22:37,692][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding component template [synthetics-mappings]
» [2021-04-18T14:22:37,729][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding component template [logs-settings]
» [2021-04-18T14:22:37,803][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding index template [.watch-history-14] for index patterns [.watcher-history-14*]
» [2021-04-18T14:22:37,846][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding index template [ilm-history] for index patterns [ilm-history-5*]
» [2021-04-18T14:22:37,885][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding index template [.slm-history] for index patterns [.slm-history-5*]
» [2021-04-18T14:22:37,923][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding component template [.deprecation-indexing-settings]
» [2021-04-18T14:22:37,962][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding component template [.deprecation-indexing-mappings]
» [2021-04-18T14:22:38,002][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding template [.monitoring-alerts-7] for index patterns [.monitoring-alerts-7]
» [2021-04-18T14:22:38,051][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding template [.monitoring-es] for index patterns [.monitoring-es-7-*]
» [2021-04-18T14:22:38,094][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding template [.monitoring-kibana] for index patterns [.monitoring-kibana-7-*]
» [2021-04-18T14:22:38,139][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding template [.monitoring-logstash] for index patterns [.monitoring-logstash-7-*]
» [2021-04-18T14:22:38,206][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding template [.monitoring-beats] for index patterns [.monitoring-beats-7-*]
» [2021-04-18T14:22:38,251][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding index template [metrics] for index patterns [metrics-*-*]
» [2021-04-18T14:22:38,292][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding index template [synthetics] for index patterns [synthetics-*-*]
» [2021-04-18T14:22:38,333][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding index template [logs] for index patterns [logs-*-*]
» [2021-04-18T14:22:38,374][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding index template [.deprecation-indexing-template] for index patterns [.logs-deprecation.*]
» [2021-04-18T14:22:38,413][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [javaRestTest-0] adding index lifecycle policy [ml-size-based-ilm-policy]
» [2021-04-18T14:22:38,457][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [javaRestTest-0] adding index lifecycle policy [synthetics]
» [2021-04-18T14:22:38,501][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [javaRestTest-0] adding index lifecycle policy [logs]
» [2021-04-18T14:22:38,540][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [javaRestTest-0] adding index lifecycle policy [metrics]
» [2021-04-18T14:22:38,573][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [javaRestTest-0] adding index lifecycle policy [watch-history-ilm-policy]
» [2021-04-18T14:22:38,608][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [javaRestTest-0] adding index lifecycle policy [ilm-history-ilm-policy]
» [2021-04-18T14:22:38,643][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [javaRestTest-0] adding index lifecycle policy [slm-history-ilm-policy]
» [2021-04-18T14:22:38,681][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [javaRestTest-0] adding index lifecycle policy [.deprecation-indexing-ilm-policy]
» [2021-04-18T14:22:38,729][INFO ][o.e.c.m.MetadataCreateIndexService] [javaRestTest-0] [reviews] creating index, cause [api], templates [], shards [1]/[1]
» [2021-04-18T14:22:38,913][INFO ][o.e.l.LicenseService     ] [javaRestTest-0] license [ae96f6bf-bbcb-4a4d-8ca2-ab856f989cfb] mode [trial] - valid
» [2021-04-18T14:22:38,913][INFO ][o.e.x.s.s.SecurityStatusChangeListener] [javaRestTest-0] Active license is now [TRIAL]; Security is enabled
» [2021-04-18T14:22:39,771][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding template [special_pivot_template] for index patterns [special_pivot_template*]
» [2021-04-18T14:22:39,899][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] removing template [special_pivot_template]
» [2021-04-18T14:22:39,986][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [javaRestTest-0] adding index lifecycle policy [synthetics]
» [2021-04-18T14:22:40,060][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [javaRestTest-0] adding index lifecycle policy [.deprecation-indexing-ilm-policy]
» [2021-04-18T14:22:40,157][INFO ][o.e.c.m.MetadataDeleteIndexService] [javaRestTest-0] [reviews/L1gCjJSXQPGWJdlZ6Qmf7w] deleting index
» [2021-04-18T12:22:40.251227705Z] [BUILD] Stopping node

> Task :x-pack:plugin:transform:qa:single-node-tests:javaRestTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':x-pack:plugin:transform:qa:single-node-tests:javaRestTest'.

```

Also happened on CI now here: https://gradle-enterprise.elastic.co/s/y2c2zcdsg3zhc

**Comment by mayya-sharipova** [comment] 2021-04-18 18:18
Another failure in this PR failure: https://gradle-enterprise.elastic.co/s/2zmadgq2pl4so


REPRODUCE WITH: ./gradlew ':x-pack:plugin:transform:qa:single-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.transform.integration.TransformPivotRestSpecialCasesIT.testIndexTemplateMappingClash" -Dtests.seed=28B21B0ED61E3E38 -Dtests.security.manager=true -Dtests.locale=el -Dtests.timezone=America/Costa_Rica -Druntime.java=11

**Comment by henningandersen** [comment] 2021-04-18 18:18
This will be fixed by #71778

**Comment by henningandersen** [comment] 2021-04-19 06:16
Muted in 7.x and master (#71810).

**Comment by hendrikmuhs** [comment] 2021-04-19 06:25
Notes:

- regression got introduced with #71309 
- this test simulates user input, which remains valid although deprecated, therefore I don't see a reason to remove this test until legacy templates have been removed (#71778 adds the deprecation warning :+1: )

**Comment by hendrikmuhs** [comment] 2021-04-19 06:50
I don't get why the PR #71309 build did not fail. The test is super old and hasn't been touched for ages. It's also not a potentially disabled BWC on, but an ordinary test. Inspecting the logs and checking gradle enterprise I could not find a reason.

This is odd, because it makes me think that PR builds are not reliable.

**Comment by valeriy42** [comment] 2021-04-19 07:03
Another failure on the CI https://gradle-enterprise.elastic.co/s/f64oymuarf3xo too. It started happening last Friday:
https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=Europe/Berlin&tests.container=org.elasticsearch.xpack.transform.integration.TransformPivotRestSpecialCasesIT&tests.sortField=FAILED&tests.test=testIndexTemplateMappingClash&tests.unstableOnly=true

![image](https://user-images.githubusercontent.com/1292899/115194684-10d53180-a0ee-11eb-85db-4ad688c02a92.png)

**Comment by droberts195** [comment] 2021-04-19 09:33
> This is odd, because it makes me think that PR builds are not reliable.

I don't think this unreliability is limited to PR builds.  After being committed the problematic change successfully got past an intake build too.

I compared the server-side logs from [the PR build that failed that led to this issue being opened](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-2/5419/gcsObjects/) and [the PR build of the PR that introduced the problem](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-2/5402/gcsObjects/).

The failure case looks like this:

```
[2021-04-18T10:19:33,451][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding template [special_pivot_template] for index patterns [special_pivot_template*]
[2021-04-18T10:19:33,517][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] removing template [special_pivot_template]
```

The success case looks like this:

```
[2021-04-16T12:44:40,535][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding template [special_pivot_template] for index patterns [special_pivot_template*]
[2021-04-16T12:44:40,584][INFO ][o.e.c.m.MetadataCreateIndexService] [javaRestTest-0] [special_pivot_template_mappings_clash] creating index, cause [api], templates [special_pivot_template], shards [1]/[1]
[2021-04-16T12:44:40,585][INFO ][o.e.c.r.a.AllocationService] [javaRestTest-0] updating number_of_replicas to [0] for indices [special_pivot_template_mappings_clash]
[2021-04-16T12:44:40,666][INFO ][o.e.x.t.t.TransformTask  ] [javaRestTest-0] [special_pivot_template_mappings_clash] updating state for transform to [{"task_state":"started","indexer_state":"stopped","checkpoint":0,"should_stop_at_checkpoint":false}].
[2021-04-16T12:44:40,688][INFO ][o.e.x.t.t.TransformPersistentTasksExecutor] [javaRestTest-0] [special_pivot_template_mappings_clash] successfully completed and scheduled task in node operation
[2021-04-16T12:44:40,727][INFO ][o.e.x.t.t.ClientTransformIndexer] [javaRestTest-0] [special_pivot_template_mappings_clash] transform finished indexing all data, initiating stop.
[2021-04-16T12:44:40,864][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] removing template [special_pivot_template]
```

`removing template [special_pivot_template]` comes from the cleanup after the test passes or fails.

The only possible ways I can explain the difference are:

1. Deprecation warnings are not always returned in response headers when they should be
2. The test client sometimes misses deprecation warnings in response headers

So it seems that this failure might have exposed a much deeper problem than the direct cause of the failing assertion.

**Comment by hendrikmuhs** [comment] 2021-04-19 10:20
Thank you @droberts195!

This triggered and idea:

>     1. Deprecation warnings are not always returned in response headers when they should be

Looking at the logs you linked again, the (false) successful test used the old endpoints:

```
special_pivot_template_mappings_clash/_stats] returned 1 warnings: [299 Elasticsearch-8.0.0-SNAPSHOT-f03ca332cb4936be976768fcd31b4aad7d04dcf6 "[_data_frame/transforms/] is deprecated, use [_transform/] in the future."]
```

It seems there is a limitation for deprecation logs: Only 1 deprecation, the 1st, is returned.

The test randomly uses the deprecated `_data_frame` endpoint:

https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/transform/qa/single-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/transform/integration/TransformRestTestCase.java#L64

If I set this to `true` and execute the repro steps, the test passes.

I will create a PR to remove testing of the deprecated endpoint on `master`, that's the plan for `master` anyway.

**Closed** 2021-04-19 12:34 UTC
Labels: :Core/Features/Indices APIs, >test-failure, Team:Core/Features
