### ISSUE TITLE
Download page for past releases lists "undefined"

### ISSUE THREAD

**Issue by sandeepkanabar** [elastic/elasticsearch#31550] opened 2018-06-25 08:32 UTC
**Steps to reproduce**:

- Go to the Elastic [downloads](https://www.elastic.co/downloads/past-releases) page for past releases
- In the `Products` drop down, select a product e.g `Kibana`.
- In the `Versions` drop down, enter any version for e.g. `6.3.0` 
- Along with the selected version, there will also be a listing titled `undefined`.

**Comment by colings86** [comment] 2018-06-25 11:00
@sandeepkanabar could you add a screen shot showing what you mean? I have followed your steps above but I don't seem to get the problem that you see.

**Comment by sandeepkanabar** [comment] 2018-06-25 11:04
Sure. @colings86 . Here you go. 
<img width="1218" alt="screen shot 2018-06-25 at 1 54 25 pm" src="https://user-images.githubusercontent.com/5564497/41846821-9a455bae-7895-11e8-9c52-b6a73e21cab5.png">

**Comment by tvernum** [comment] 2018-06-25 11:08
It seems to be browser specific. I can reproduce in Chrome, but not Firefox.

**Comment by sandeepkanabar** [comment] 2018-06-25 11:13
@tvernum - I am able to reproduce it in Chrome, FF and Safari. Screenshots for FF and Chrome attached.
<img width="992" alt="screen shot 2018-06-25 at 4 41 48 pm" src="https://user-images.githubusercontent.com/5564497/41847223-dd3426d8-7896-11e8-880e-0914d69d2d90.png">
<img width="1043" alt="screen shot 2018-06-25 at 4 42 09 pm" src="https://user-images.githubusercontent.com/5564497/41847224-dd67ca4c-7896-11e8-9740-3548dee86466.png">

**Comment by colings86** [comment] 2018-06-25 11:16
I am not able to reproduce it on `Chrome 67.0.3396.87 (Official Build) (64-bit)`. However I will raise this to our website team to look into. Since this is a problem with the elastic.co website and not the Elasticsearch product though I hope you don't mind me closing this issue here.

**Closed by colings86** 2018-06-25 11:16 UTC

**Comment by colings86** [comment] 2018-06-25 11:22
@sandeepkanabar I've opened an issue with our website team. Some other information that might help them investigate if you are able to provide it:
* What exact versions of FF, Chrome and Safari are you using?
* What country are you accessing the website from (in case this is a regional CDN problem)

**Comment by colings86** [comment] 2018-06-25 11:28
@sandeepkanabar thanks, I'll pass this onto the website team as well.
