### ISSUE TITLE
CI: packaging fails due to missing files

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#62635] opened 2020-09-18 14:19 UTC
A number of Cli tests are failing due to incorrect permissions or missing files.

**Build scan**:
PluginCliTests in 7.x: 
https://gradle-enterprise.elastic.co/s/foei5rgng7qw2
SqlClitests/ArchiveTests  in 7.x:
https://gradle-enterprise.elastic.co/s/a7nujb7rluyju

**Repro line**:

**Reproduces locally?**:
Not applicable

**Applicable branches**:
7.x so far.

**Failure history**:

**Failure excerpt**:

PluginCliTests
```
15:34:49 org.elasticsearch.packaging.test.PluginCliTests > test10Install FAILED
15:34:49     java.lang.AssertionError: 
15:34:49     Expected: "file/directory: "<File> with owner "root" with group "elasticsearch" with posix permissions [<OWNER_READ>,<OWNER_WRITE>,<GROUP_READ>,<GROUP_WRITE>]
15:34:49          but: path </etc/elasticsearch/elasticsearch.keystore>Does not exist
```
SqlCliTests
```
15:36:05 
15:36:05 org.elasticsearch.packaging.test.SqlCliTests > test010Install FAILED
15:36:05     java.lang.AssertionError: 
15:36:05     Expected: "file/directory: "<File> with owner "root" with group "elasticsearch" with posix permissions [<OWNER_READ>,<OWNER_WRITE>,<GROUP_READ>,<GROUP_WRITE>]
15:36:05          but: path </etc/elasticsearch/elasticsearch.keystore>Does not exist
```

this might be related to a GLIBC issue seen in some of the error logs:

```
java.lang.RuntimeException: Command was not successful: [bash -c sudo -E -u elasticsearch "/tmp/elasticsearch/bin/elasticsearch-plugin" list]
15:34:37        result: exitCode = [1] stdout = [] stderr = [/tmp/elasticsearch/jdk/bin/java: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/elasticsearch/jdk/bin/../lib/libjli.so)]
15:34:37         at __randomizedtesting.SeedInfo.seed([C45E3BC5D833FE24:D00AD72D3E2EBD96]:0)
15:34:37         at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:158)
15:34:37         at org.elasticsearch.packaging.util.Shell.run(Shell.java:84)
15:34:37         at org.elasticsearch.packaging.util.Installation$Executable.run(Installation.java:185)
15:34:37         at org.elasticsearch.packaging.util.Installation$Executable.run(Installation.java:168)
15:34:37         at org.elasticsearch.packaging.test.ArchiveTests.test20PluginsListWithNoPlugins(ArchiveTests.java:69)
```

**Comment by rjernst** [comment] 2020-09-18 20:34
It seems this failure is now happening on centos 6 and oel 6, which we no longer have support for in master. Here is another failure, again related to glibc:

https://gradle-enterprise.elastic.co/s/pigavidhsr324/console-log?task=:qa:verify-version-constants:v7.9.2%23integTest 

This looks related to our upgrade of the bundled jdk to java 15, which appears to now rely on glibc 2.14. That version does not appear to be available in these legacy environments.

**Comment by droberts195** [comment] 2020-09-21 09:03
CentOS/RHEL/Oracle Linux 6 ship with glibc 2.12.

So it looks like either 7.x will have to stick with Java 14 or else we'll have to drop support for CentOS/RHEL/Oracle Linux 6.

**Comment by droberts195** [comment] 2020-09-21 10:58
It looks like the problem also affects 7.9.2.

These two 7.9 builds failed on CentOS/RHEL/Oracle Linux 6 due to it not having glibc 2.14:

1. https://gradle-enterprise.elastic.co/s/klw27zjadxz3k
2. https://gradle-enterprise.elastic.co/s/qhbjyrsd7tcr2

Both had:

```
Runtime JDK Version   : 1.8 (Oracle JDK)
Runtime java.home     : /var/lib/jenkins/.java/oracle-8u241-linux
Gradle JDK Version    : 14 (OpenJDK)
Gradle java.home      : /var/lib/jenkins/.java/openjdk-14.0.2+12-linux
```

The error is:

```
sudo service elasticsearch start] stderr = [/usr/share/elasticsearch/jdk/bin/java: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/share/elasticsearch/jdk/bin/../lib/libjli.so)
```

So that shows that even when a CI run is supposed to be testing a specific JDK some of the tools that are shipped with Elasticsearch that are invoked by the tests are still using the bundled JDK.

But also it shows that the upgrade to Java 15 was not just done on the master and 7.x branches, but also on the 7.9 branch.  7.9.2 BC1 does not work on CentOS/RHEL/Oracle Linux 6 as a result.  I have confirmed this by downloading 7.9.2 BC1:

```
$ bin/java -version
bin/java: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/dave/792/elasticsearch-7.9.2/jdk/bin/../lib/libjli.so)
```

The JDK in the GA 7.9.1 build works fine:

```
[dave@linux jdk]$ bin/java -version
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.1+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.1+7, mixed mode, sharing)
```

So, this requires urgent consideration about what to do for 7.9.2 - whether it's OK to document that if you want to run on certain supported platforms you cannot use the bundled JDK, or whether the bundled JDK needs to work on every supported platform.

**Comment by jasontedor** [comment] 2020-09-21 14:16
Relates elastic/elasticsearch#62709

**Comment by rjernst** [comment] 2020-10-13 23:07
This has been fixed by switching to Oracle JDK 15.

**Closed by rjernst** 2020-10-13 23:07 UTC
Labels: :Core/Infra/Packaging, >test-failure, Team:Core/Infra
