### ISSUE TITLE
GrokTests unit tests fail with "Unable to find pattern [] in Grok's pattern dictionary"

### ISSUE THREAD

**Issue by alpar-t** [elastic/elasticsearch#43673] opened 2019-06-27 06:10 UTC
## Example build failure
https://scans.gradle.com/s/iepue6nvnpjco/tests/vmr3zh2fll5n6-jtrpes23gv6dm

## Reproduction line 
does not reproduce locally
```
./gradlew :libs:elasticsearch-grok:test --tests "org.elasticsearch.grok.GrokTests.testDatePattern" -Dtests.seed=7783EF4A23023948 -Dtests.security.manager=true -Dtests.locale=fur -Dtests.timezone=Europe/Kiev -Dcompiler.java=12 -Druntime.java=12
HomeTestsGrokTests » testDatePatternClose test output (esc)
```

## Example relevant log:
```
java.lang.IllegalArgumentException: Unable to find pattern [] in Grok's pattern dictionary
```

## Frequency

reproduces  ~ 6 times in the past 30 days

/cc @talevy

**Comment by jimczi** [comment] 2019-07-01 16:28
It is related to the ingest grok processor, @talevy  can you take a look and reassign if needed ?

**Comment by talevy** [comment] 2019-07-01 19:49
I investigated this issue in the past and wasn't sure how to resolve it. I'll take a look.

**Comment by andrershov** [comment] 2019-08-08 15:45
"testExponentialExpressions" failed for the same reason on CI:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=ubuntu-16.04&&immutable/188/console

**Comment by jaymode** [comment] 2019-09-20 16:12
I hit this locally on master but wasn't able to reproduce.

```
java.lang.IllegalArgumentException: Unable to find pattern [] in Grok's pattern dictionary
at __randomizedtesting.SeedInfo.seed([1186E7D07D363562:26D61FAD77849B19]:0)
at org.elasticsearch.grok.Grok.toRegex(Grok.java:193)
at org.elasticsearch.grok.Grok.<init>(Grok.java:104)
at org.elasticsearch.grok.Grok.<init>(Grok.java:82)
at org.elasticsearch.grok.GrokTests.testApacheLog(GrokTests.java:315)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:567)
at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
at java.lang.Thread.run(Thread.java:835)

REPRODUCE WITH: ./gradlew ':libs:elasticsearch-grok:test' --tests "org.elasticsearch.grok.GrokTests.testApacheLog" -Dtests.seed=1186E7D07D363562 -Dtests.security.manager=true -Dtests.locale=ml -Dtests.timezone=Europe/Berlin -Dcompiler.java=12 -Druntime.java=12
```

**Comment by talevy** [comment] 2019-09-20 16:27
ugh sorry folks. I'll get back to this. I still have no clue how this is happening

**Comment by martijnvg** [comment] 2019-10-01 16:01
A while ago jcodings was upgraded (#43334), but joni wasn't. I've opened a pr to upgrade joni (#47374). This may not be causing the grok failures, but it isn't ideal either. The version jcodings (`1.0.44`) was upgraded to wasn't the version joni (`2.1.6`) was build against. The `2.1.29` joni version is build against jcodings `1.0.44.

**Comment by jdconrad** [comment] 2019-10-07 17:23
Another (https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=java12,nodes=general-purpose/251/console)

**Comment by talevy** [comment] 2019-10-07 19:57
thanks Jack, I was hoping some code I changed would expose the error here, but it doesn't look like it

**Comment by dnhatn** [comment] 2019-10-12 01:06
Another instance: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/8632/

**Comment by droberts195** [comment] 2019-12-06 10:24
This problem occurred in the 7.5 branch in https://gradle-enterprise.elastic.co/s/rck3jol2wuye6

Is it worth backporting the fix to 7.5?

**Comment by tlrx** [comment] 2020-02-06 09:58
Tests are failing regularly on 7.5 branch so I muted the whole GrokTests class that branch in a508b10638323c730fa9d625f471b571577d5d2e.

Here is the build scan of today's failure (https://gradle-enterprise.elastic.co/s/y4nfudrjljl3s) but you can find ~10 for the last 30 days in the build stats.

Also, these tests are timing out regularly too in both 7.5 and 7.5 branches (builds scans:https://gradle-enterprise.elastic.co/s/mhly7mq3el6vy, https://gradle-enterprise.elastic.co/s/2xdryigg2jsn6)

**Comment by probakowski** [comment] 2020-11-06 11:22
I'm going to close it as there are no failures since February and we are done with 7.5 branch

**Closed by probakowski** 2020-11-06 11:22 UTC
Labels: :Core/Features/Ingest, >test-failure, Team:Core/Features, v8.0.0
