### ISSUE TITLE
script_lang not supported [groovy] when putting indexed script

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#15867] opened 2016-01-08 20:14 UTC
In pom:

```
        <dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch</artifactId>
            <version>1.7.1</version>
        </dependency>
```

ES 1.7.1 has `script.inline: on` set:

Using a NodeClient connection:

```
        node = NodeBuilder.nodeBuilder().settings(settings).node();
        client = node.client();
```

Tried 2 ways to put an indexed script.

Example 1:

```
 PutIndexedScriptResponse putIndexedScriptResponse =
        client.preparePutIndexedScript()
                .setId("dummy_script_name")
                .setScriptLang("groovy")
                .setSource("\"script\" : \"_score * doc['some_field'].value\"")
                .get();
```

Example 2:

```
PutIndexedScriptResponse putIndexedScriptResponse = client.preparePutIndexedScript(GroovyScriptEngineService.NAME, "dummy_script_name", "\"script\" : \"_score * doc['some_field'].value\"").get();
```

They both return the same exception:

```
Exception in thread "main" org.elasticsearch.ElasticsearchIllegalArgumentException: script_lang not supported [groovy]
	at org.elasticsearch.script.ScriptService.validateScriptLanguage(ScriptService.java:343)
	at org.elasticsearch.script.ScriptService.putScriptToIndex(ScriptService.java:395)
	at org.elasticsearch.action.indexedscripts.put.TransportPutIndexedScriptAction.doExecute(TransportPutIndexedScriptAction.java:54)
	at org.elasticsearch.action.indexedscripts.put.TransportPutIndexedScriptAction.doExecute(TransportPutIndexedScriptAction.java:36)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:75)
	at org.elasticsearch.client.node.NodeClient.execute(NodeClient.java:98)
	at org.elasticsearch.client.support.AbstractClient.putIndexedScript(AbstractClient.java:260)
	at org.elasticsearch.action.indexedscripts.put.PutIndexedScriptRequestBuilder.doExecute(PutIndexedScriptRequestBuilder.java:189)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:91)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:65)
	at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:73)
	at com.elasticsearch.pius.PutIndexedScript.main(PutIndexedScript.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

Rest request works:

```
POST /_scripts/groovy/dummy_script_name
{
     "script": "_score * doc['some_field'].value"
}
```

Is this a bug?  Or are there steps missing that should be documented in our guide?

**Comment by dadoonet** [comment] 2016-01-08 20:18
I think you need to add:

```xml
        <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <version>2.4.4</version>
        </dependency>
```

As it's marked as optional.

**Comment by dadoonet** [comment] 2016-01-08 20:19
For example, see doc: https://www.elastic.co/guide/en/elasticsearch/client/java-api/1.7/_metrics_aggregations.html#java-aggs-metrics-scripted-metric

**Comment by ppf2** [comment] 2016-01-08 20:34
Thanks @dadoonet for the tip !  I am thinking it will be helpful to also add this caveat of adding the `groovy-all-<version>.jar` to the Java client project to the main scripting module page [here](https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-scripting.html).  Thoughts? :)

**Comment by rjernst** [comment] 2016-01-08 20:50
The problem is this line in the stack trace:
```
at org.elasticsearch.script.ScriptService.validateScriptLanguage(ScriptService.java:343)
```

Why is the client trying to validate the script language? The client should pass the script along to the system and let it do any validation necessary.

**Comment by rjernst** [comment] 2016-01-08 20:52
Seems like the root of the problem there is there are no apis for indexed scripts, it is essentially something that is translated client side into an index request (to the indexed scripts index). Instead, there should really be CRUD operations for scripts, and those translate into indexing operations on the server side.

**Comment by rjernst** [comment] 2016-01-08 20:54
Oh we do have CRUD ops! So I think we just need to change the client to call those, instead of indexing directly into the indexed scripts?

**Comment by rjernst** [comment] 2016-01-08 20:58
Ah, I think I see the real root of the problem. The node client performs all actions *locally* (on itself). Really I think it should be sending these requests to the cluster, assuming *nothing* about the "node client" itself? But i think this comes back to a core problem with the node client: it is a node in the cluster, so the cluster thinks it should work like any other node.

**Comment by dadoonet** [comment] 2016-01-09 10:40
I think we have a similar issue with `mustache`. See https://discuss.elastic.co/t/template-query-on-embedded-server-results-in-script-lang-not-supported-mustache/38765
So if we document it, we need to add documentation for https://www.elastic.co/guide/en/elasticsearch/client/java-api/2.1/java-specialized-queries.html#java-query-dsl-template-query as well.

**Comment by clintongormley** [comment] 2016-05-24 10:06
Indexed scripts have been replaced with stored scripts.  Closing

**Closed by clintongormley** 2016-05-24 10:06 UTC
Labels: :Indexed Scripts/Templates, :Java API, discuss, docs
