### ISSUE TITLE
JdbcCsvSpecIT.testAverageWithOneValueAndLimit failing

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#47080] opened 2019-09-25 07:42 UTC
```
java.lang.AssertionError: 
Elasticsearch [JdbcResultSet:row 4:cursor size 2:[languages<type=[BYTE]>, 'F'<type=[DOUBLE]>]] still has data after [3] entries:
3                    | 53660.0     



REPRODUCE WITH: ./gradlew ':x-pack:plugin:sql:qa:single-node:integTestRunner' --tests "org.elasticsearch.xpack.sql.qa.single_node.JdbcCsvSpecIT" -Dtests.method="test {pivot.testAverageWithOneValueAndLimit}" -Dtests.seed=81AF0740AC9F7D95 -Dtests.security.manager=true -Dtests.locale=yo -Dtests.timezone=Etc/GMT-10 -Dcompiler.java=12 -Druntime.java=11
```

Build scan: https://gradle-enterprise.elastic.co/s/ryxn3kl4orgom

**Comment by ywelsch** [comment] 2019-09-25 07:42
Failure on 7.x : https://gradle-enterprise.elastic.co/s/bimadqxmhc6rk

**Comment by ywelsch** [comment] 2019-09-25 08:37
Don't know how to mute this single test, so I just removed it for now (see f903d924b1d (master) and 056ac32738f (7.x))

**Comment by costin** [comment] 2019-10-10 11:15
I've tried reproducing this without success - I think that's because there was a race condition, the fix being about to be merged: https://github.com/elastic/elasticsearch/pull/47121

**Comment by costin** [comment] 2019-10-10 11:28
Indeed, on both 7.x and master I cannot reproduce the failure. I'm asking around for some folks to try it out, otherwise, I'll enable the tests back.

**Closed** 2019-10-10 12:46 UTC
Labels: :Search/SQL, >test-failure
