### ISSUE TITLE
InternalMedianAbsoluteDeviationTests.testConcurrentEquals fails

### ISSUE THREAD

**Issue by edsavage** [elastic/elasticsearch#97486] opened 2023-07-10 08:58 UTC
### CI Link

https://gradle-enterprise.elastic.co/s/ehmstrj24ie6k

### Repro line

gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.metrics.InternalMedianAbsoluteDeviationTests.testConcurrentEquals" -Dtests.seed=F35BA938AE8CF838 -Dtests.locale=sk -Dtests.timezone=Canada/Atlantic -Druntime.java=20	

### Does it reproduce?

Yes

### Applicable branches

main

### Failure excerpt

        Caused by:
        java.lang.AssertionError
            at org.elasticsearch.tdigest.MergingDigest.merge(MergingDigest.java:338)
            at org.elasticsearch.tdigest.MergingDigest.mergeNewValues(MergingDigest.java:247)
            at org.elasticsearch.tdigest.MergingDigest.mergeNewValues(MergingDigest.java:237)
            at org.elasticsearch.tdigest.MergingDigest.centroidCount(MergingDigest.java:495)
            at org.elasticsearch.tdigest.HybridDigest.centroidCount(HybridDigest.java:165)
            at org.elasticsearch.search.aggregations.metrics.TDigestState.centroidCount(TDigestState.java:237)
            at org.elasticsearch.search.aggregations.metrics.TDigestState.equals(TDigestState.java:167)
            at java.base/java.util.Objects.equals(Objects.java:64)
            at org.elasticsearch.search.aggregations.metrics.InternalMedianAbsoluteDeviation.equals(InternalMedianAbsoluteDeviation.java:114)
            at org.junit.Assert.isEquals(Assert.java:131)
            at org.junit.Assert.equalsRegardingNull(Assert.java:127)
            at org.junit.Assert.assertEquals(Assert.java:111)
            at org.junit.Assert.assertEquals(Assert.java:144)
            at org.elasticsearch.test.AbstractWireTestCase.lambda$testConcurrentEquals$0(AbstractWireTestCase.java:80)
            at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
            at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
            ... 1 more
  2> NOTE: leaving temporary files on disk at: /Users/eds/src/elasticsearch/es-new/server/build/testrun/test/temp/org.elasticsearch.search.aggregations.metrics.InternalMedianAbsoluteDeviationTests_F35BA938AE8CF838-001
  2> NOTE: test params are: codec=Asserting(Lucene95), sim=Asserting(RandomSimilarity(queryNorm=true): {}), locale=sk, timezone=Canada/Atlantic
  2> NOTE: Mac OS X 13.4.1 aarch64/Oracle Corporation 20.0.1 (64-bit)/cpus=10,threads=1,free=444280424,total=536870912
  2> NOTE: All tests run in this JVM: [InternalMedianAbsoluteDeviationTests]

**Comment by edsavage** [comment] 2023-07-10 09:11
Muting this test case is difficult as the test method in question is declared `final` in the base class `AbstractWireTestCase`

**Comment by kkrik-es** [comment] 2023-07-31 09:44
Hi @edsavage, thanks for reporting this. I wasn't able to reproduce the issue at head. I also tried running the test with `-Dtests.iters=1000`, no failures reported.

Can you please give it another try after syncing? I wonder if you happened to pick up an older version of the code.

**Comment by kkrik-es** [comment] 2023-08-02 06:03
Closing for now as I can't reproduce the issue.

**Closed by kkrik-es** 2023-08-02 06:03 UTC
Labels: :Analytics/Aggregations, >test-failure, Team:Analytics
