### ISSUE TITLE
Elasticsearch 7.8.0  . When setting "fuzziness":0 highlight does not return any results .

### ISSUE THREAD

**Issue by sargisaleksanyan** [elastic/elasticsearch#59351] opened 2020-07-10 07:21 UTC
As already mentioned bug exists in https://github.com/elastic/elasticsearch/issues/45373  7.3.0 , still encounter the same problem .But when set fuzziness any other value or do not set fuzziness highlight works perfectly*
```
{  
   "query":{  
      "bool":{  
         "must":[  
            {  
               "span_near":{  
                  "clauses":[  
                     {  
                        "span_multi":{  
                           "match":{  
                              "fuzzy":{  
                                 "content":{  
                                    "value":"anna",
                                    "fuzziness":0
                                 }
                              }
                           }
                        }
                     },
                     {  
                        "span_multi":{  
                           "match":{  
                              "fuzzy":{  
                                 "content":{  
                                    "value":"pavlova",
                                    "fuzziness":0
                                 }
                              }
                           }
                        }
                     }
                  ],
                  "slop":0,
                  "in_order":false
               }
            }
         ]
      }
   }
,"size":100,
    "highlight" : {
        "fields" : {
            "content" : {}
        }
    }
}
```

**Comment by jtibshirani** [comment] 2020-07-14 17:09
I'm closing this as a duplicate of #45373. I assigned that issue to myself and am taking a look.

**Closed by jtibshirani** 2020-07-14 17:09 UTC
Labels: :Search/Search, >bug, Team:Search, needs:triage
