### ISSUE TITLE
Connection reset by peer error when omitting / (slash) at the end of query

### ISSUE THREAD

**Issue by gsouveton** [elastic/elasticsearch#70964] opened 2021-03-29 08:09 UTC
**Elasticsearch version** : ES6

**JVM version** (`java -version`): java version "1.8.0_162"

**OS version** : Ubuntu 18.0.4

**Description of the problem including expected versus actual behavior**:

A strange behavior happens when proceeding to a _**_search**_ query without a trailing slash (whether there are additionnal parameters or not).

For instance :

```
curl -X GET http://127.0.0.1:9200/my_index/_count
{"count":544001,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0}}

```
Works fine. But with _search :

```
curl -X GET http://127.0.0.1:9200/my_index/_search
curl: (56) Recv failure: Connection reset by peer
```

A 'connection reset by peer' error occurs.
If we simply add a trailing slash at the end, it works fine :

```
curl -X GET http://127.0.0.1:9200/my_index/_search/
{"took":26,"timed_out":false,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0},"hits":{...}}

```

I found this old post that describes the same behavior : http://elasticsearch-users.115913.n3.nabble.com/Odd-Connection-Reset-by-peer-issue-when-URL-contains-a-query-string-td4069593.html
This user indicates that this bug started happening after an update. I guess it was an old version of ES in his case, but the bug seems to be still there.

It seems to be network related, but only happens for specific queries.
What is problematic is that it also happens when using API (like elasticsearch-php or elasticsearch-py) which probably make requests without adding the trailing slash.

**Comment by rjernst** [comment] 2021-04-06 00:25
Thanks very much for your interest in Elasticsearch. I was not able to reproduce this, using Elasticsearch 6.8.15:

```
curl -XGET http://localhost:9200/index/_search
{"took":49,"timed_out":false,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0},"hits":{"total":2,"max_score":1.0,"hits":[{"_index":"index","_type":"_doc","_id":"doc1","_score":1.0,"_source":{"foo":"bar"}},{"_index":"index","_type":"_doc","_id":"doc2","_score":1.0,"_source":{"foo":"bar"}}]}}
```

The thread you referenced is quite old, long before ES 6 came out. We also have plenty of tests that hit the search endpoint without a trailing slash. Given that, it seems this is environmental for you.

I recommend you reach out in our [forums](https://discuss.elastic.co). There's an active community in there that should be able to help isolate how your setup may be triggering this issue. If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. As such, I hope you don't mind that I close this.

**Closed by rjernst** 2021-04-06 00:25 UTC
Labels: :Core/Infra/REST API, >bug, Team:Core/Infra
