### ISSUE TITLE
ESQL: a second `ENRICH` enriching with a `RENAME`d field fails

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#110041] opened 2024-06-21 13:02 UTC
### Description

A query like:
```
FROM airports_web 
| ENRICH my-policy ON abbrev WITH city
| RENAME city as c
| ENRICH my-policy ON abbrev WITH city
```
fails with `"Found 1 problem\nline 21:3: Plan [EsqlProject[[abbrev{f}#2287, location{f}#2286, name{f}#2284, scalerank{f}#2285, type{f}#2288, city{r}#2293 AS c, city{r}#2\n298]]] optimized incorrectly due to missing references [city{r}#2293]"`

**Comment by alex-spies** [comment] 2024-07-23 07:57
Reproducer that can just be plopped into `enrich.csv-spec`:

```
required_capability: enrich_load
ROW city = "Zürich"
| ENRICH city_names ON city WITH airport
| RENAME airport AS a
| ENRICH city_names ON city WITH airport
;
```

This results in an illegal state, like above:

```
line 3:3: Plan [EsqlProject[[city{r}#2, airport{r}#15 AS a, airport{r}#20]]] optimized incorrectly due to missing references [airport{r}#15]
```

**Comment by alex-spies** [comment] 2024-07-23 08:00
The culprit is, again, `PushDownEnrich`; this is the same root cause as for https://github.com/elastic/elasticsearch/issues/108008.

```
[2024-07-23T03:55:13,768][INFO ][o.e.x.e.o.LogicalPlanOptimizer] [test-cluster-0] Rule rules.PushDownEnrich applied
Enrich[ANY,[63 69 74 79 5f 6e 61 6d 65 73][KEYWORD],city{r}#2,{"match":{"indices":[],"match_field":"city","enrich_fields     ! EsqlProject[[city{r}#2, airport{r}#15 AS a, airport{r}#20]]
":["airport","region","city_boundary"]}},{=.enrich-city_names-1721721312651},[airport{r}#20]]                                ! \_Enrich[ANY,[63 69 74 79 5f 6e 61 6d 65 73][KEYWORD],city{r}#2,{"match":{"indices":[],"match_field":"city","enrich_fields
\_EsqlProject[[city{r}#2, airport{r}#15 AS a]]                                                                               ! ":["airport","region","city_boundary"]}},{=.enrich-city_names-1721721312651},[airport{r}#20]]
  \_Enrich[ANY,[63 69 74 79 5f 6e 61 6d 65 73][KEYWORD],city{r}#2,{"match":{"indices":[],"match_field":"city","enrich_fields =   \_Enrich[ANY,[63 69 74 79 5f 6e 61 6d 65 73][KEYWORD],city{r}#2,{"match":{"indices":[],"match_field":"city","enrich_fields
":["airport","region","city_boundary"]}},{=.enrich-city_names-1721721312651},[airport{r}#15]]                                = ":["airport","region","city_boundary"]}},{=.enrich-city_names-1721721312651},[airport{r}#15]]
    \_Limit[1000[INTEGER]]                                                                                                   =     \_Limit[1000[INTEGER]]
      \_Row[[[5a c3 bc 72 69 63 68][KEYWORD] AS city]]                                                                       =       \_Row[[[5a c3 bc 72 69 63 68][KEYWORD] AS city]]
```

A more minimal reproducer is

```
ROW city = "Zürich", airport = "ZRH"
| RENAME airport AS a
| ENRICH city_names ON city WITH airport
```

**Comment by alex-spies** [comment] 2024-07-23 08:02
This will be fixed by https://github.com/elastic/elasticsearch/pull/108360.

Since this has the same cause as https://github.com/elastic/elasticsearch/issues/108008, I'll close this as duplicate - and will add tests to https://github.com/elastic/elasticsearch/pull/108360 to make sure this edge case is covered.

**Closed by alex-spies** 2024-07-23 08:02 UTC
Labels: >bug, Team:Analytics, :Analytics/ES|QL
