### ISSUE TITLE
This is the correct place of documentation issues, right?

### ISSUE THREAD

**Issue by spottedmahn** [elastic/elasticsearch#55979] opened 2020-04-29 21:06 UTC
>** Please read the guidelines below. **
Issues that do not follow these guidelines are likely to be closed.
>1.  GitHub is reserved for bug reports and feature requests. The best place to
    ask a general question is at the Elastic [forums](https://discuss.elastic.co).
    GitHub is not the place for general questions.
>2.  Is this bug report or feature request for a supported OS? If not, it
    is likely to be closed.  See https://www.elastic.co/support/matrix#show_os
>3.  Please fill out EITHER the feature request block or the bug report block
    below, and delete the other block.

**Describe the feature**:
This is the correct place of documentation issues, right?  For example, the [Count API](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/7.x/java-rest-high-count.html) documentation is using a `deprecated` method and I wanted to open an issue about it.

If so, can the **issue templated be updated** saying such as to remove any confusion?  Thoughts? 💭

**Comment by DaveCTurner** [comment] 2020-04-30 10:21
Yes, a deprecated method in an example in the docs is worth reporting here as a bug. However, as per the instructions you quoted:

> The best place to ask a general question is at the Elastic forums. GitHub is not the place for general questions.

Since this is a general question and not a bug report or a feature request, I am closing this issue and recommend that in future you ask these questions on the [forums](https://discuss.elastic.co). I don't expect we'll respond further on this thread.

**Closed by DaveCTurner** 2020-04-30 10:21 UTC

**Comment by spottedmahn** [comment] 2020-04-30 13:21
>May be you should open an issue in elasticsearch repository (the documentation is living there)?

A [previous request directed](https://discuss.elastic.co/t/add-deprecated-warning-more-broadly-in-doc-pages/217429/2?u=spottedmahn) me here 🙋‍♂️🤷‍♂️
