### ISSUE TITLE
Elasticsearch Crash

### ISSUE THREAD

**Issue by dstarh** [elastic/elasticsearch#16584] opened 2016-02-10 15:16 UTC
Since upgrading from 1.6 to 2.1 we've had elastic crash on us twice, once in production and once in staging.  The crash log can be found at https://gist.github.com/dstarh/007ee8d544581f6c0234. The first crash in production, nothing was happening other than normal user searches and the second crash, in staging I was re-building an index.  There's nothing out of the ordinary in the elastic logs themselves, just the crash log in /tmp

Versions: 
elasticsarch:  2.1.1
java: version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-0ubuntu1.14.04.1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
ubuntu 14.04.2

**Comment by clintongormley** [comment] 2016-02-10 15:40
Hi @dstarh 

It sounds like a bug between Groovy and the JVM... Could you try upgrading your JVM to the latests Java 8 and see if that fixes it?

**Comment by jasontedor** [comment] 2016-02-10 15:41
This is a hard crash of the JVM, which is in general a hard thing to do and almost always indicative of a JVM bug. I searched for the specific issue you're seeing and there isn't anything obvious out there. It looks like you're using the default startup flags, so there is nothing egregious there. I did observe some Groovy scripting engine events in your log, which might be surfacing a JVM bug? Maybe try upgrading the JVM to at least 7u95 if you have to stay in the 2.x line of IcedTea, otherwise try going to the latest 8u release if that's an option for you. If this reliably reproduces, I think you'll want to file a bug with OpenJDK.

I'm

**Comment by dstarh** [comment] 2016-02-10 15:44
@clintongormley @jasontedor 8.x open jdk or oracle or does it matter?

**Comment by jasontedor** [comment] 2016-02-10 15:46
> @clintongormley @jasontedor 8.x open jdk or oracle or does it matter?

@dstarh: Oracle if you have a choice.

**Comment by jasontedor** [comment] 2016-02-14 18:48
@dstarh: Since we think that the issue you were experiencing was due to a JVM issue, I'm closing this issue. Please feel free to open if you gather evidence otherwise.

**Closed by jasontedor** 2016-02-14 18:48 UTC
Labels: feedback_needed, jvm bug
