### ISSUE TITLE
[packaging] Add a way to start master only nodes along side other nodes on the same server

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#11702] opened 2015-06-16 14:26 UTC
We just use the deb package to install Elasticsearch but we don't have any spare systems to use as master node. I'm told that its generally good practice in this case to pick three of your nodes and run a master only node in a separate JVM from the data node. We'd do just that, but to do it we'd have to add some hacky configuration on top of the deb install. It'd be awesome if there was a dedicated master package (deb, rpm) we could install that'd install an init script and configuration for a dedicated master node.

**Comment by clintongormley** [comment] 2015-06-18 12:37
Note that the Puppet module for Elasticsearch supports multiple instances: https://github.com/elastic/puppet-elasticsearch

**Comment by nik9000** [comment] 2015-06-24 14:42
> Note that the Puppet module for Elasticsearch supports multiple instances: https://github.com/elastic/puppet-elasticsearch

Yup. This is for the folks (like WMF) who aren't willing to do much hacking after the deb does its install. Its one of those convenience/supported use case things.

**Comment by jordansissel** [comment] 2016-06-09 04:58
@nik9000 I like this proposal, though I am not sure how best to provide it successfully without confusing users.

Rough proposal: 

We could ship with two services (elasticsearch and elasticsearch-master). The former (elasticsearch) would not be master-eligible. The later would be master-eligible. They would have two different homes (configuration directories, etc). Users needing a master and data node on a single server would need to enable *both* services.

I do worry about users accidentally forgetting to run the master node or that users would accidentally run the data node when they really didn't want to. Thoughts?

**Comment by jasontedor** [comment] 2016-06-10 19:45
> We could ship with two services (elasticsearch and elasticsearch-master). The former (elasticsearch) would not be master-eligible.

This would mean that the people can not download the `elasticsearch` package and immediately start a single node and start experimenting. I think that that would be a usability regression.

**Comment by rjernst** [comment] 2018-03-13 08:34
This issue has been open for almost 3 years with no other interest. Additionally, I think this could more simply be handled by systemd templates (#24867). I'm going to close this in favor of that issue, as new packages would be a heavyweight option that I do not think anyone would favor due to the overhead of maintaining.

**Closed by rjernst** 2018-03-13 08:34 UTC
Labels: :Core/Packaging, discuss
