### ISSUE TITLE
Java HighLevelRestClient search bug

### ISSUE THREAD

**Issue by danfisk** [elastic/elasticsearch#29374] opened 2018-04-04 17:18 UTC
**Elasticsearch version** (`bin/elasticsearch --version`):
Initial bug was found in:
client:
'org.elasticsearch.client:elasticsearch-rest-high-level-client:6.2.2'
'org.elasticsearch.client:elasticsearch-rest-client:6.2.2'
with server at 6.0.0 
**OS version** (`uname -a` if on a Unix-like system): MacOS 10.13.3
**JVM version** (`java -version`): JVM 1.8.0_161-b12
I have also verified that the bug still exists in:
client:
'org.elasticsearch.client:elasticsearch-rest-high-level-client:6.2.3'
'org.elasticsearch.client:elasticsearch-rest-client:6.2.3'
with server at 6.2.3
Version: 6.2.3, Build: c59ff00/2018-03-13T10:06:29.741383Z, JVM: 1.8.0_05
**Plugins installed**: []
 
**Description of the problem including expected versus actual behavior**:
The Java "searchSourceBuilder.query(QueryBuilders.queryStringQuery(searchString)
                                            .lenient(Boolean.TRUE));"
is adding the "autoGenerateSynonymsPhraseQuery" parameter when not specified, then the following execution results in an error..
 [type=parsing_exception, reason=[query_string] query does not support [auto_generate_synonyms_phrase_query]]]

Please refer to the following discussion thread for further explanation:
https://discuss.elastic.co/t/java-highlevelrestclient-search-problem/126264

**Comment by cbismuth** [comment] 2018-09-14 09:53
I'll have a look at this one and let you know.

**Comment by cbismuth** [comment] 2018-09-14 13:20
I've created search integration test in the RHLC module, but I can't reproduce this bug.

**Comment by cbismuth** [comment] 2018-09-14 13:44
I can't reproduce this issue from `master`.

I've opened a pull request to add HLRC search integration tests to cover this use case, see https://github.com/elastic/elasticsearch/pull/33719.

**Comment by cbuescher** [comment] 2018-09-19 16:10
@danfisk I tried to reproduce this with 6.3.2 as described in the discuss issue, but also couldn't. The `parsing_exception` you see is completely explainable from the code when you run a 6.3 client against a cluster with some nodes running with versions before 6.1 since https://github.com/elastic/elasticsearch/pull/26097 was only introduced in 6.1. Thats not a bug however, since the client it supposed to be [forward compatibly](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/master/java-rest-high-compatibility.html) only.
I would like you to check again the versions of all your cluster nodes (e.g. using [the nodes info API](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html) together with making sure they are all the same and higher or the same as the client version you are using in your reproduction. If the issue still persists we probably need more info about how you set up the client project, initialize the connection etc... but first please double check the versions again since I cannot reproduce this issue.

**Comment by cbuescher** [comment] 2018-10-02 14:20
Closing with no further feedback. Please reopen if you are still able to reproduce.

**Closed by cbuescher** 2018-10-02 14:20 UTC
Labels: :Core/Java High Level REST Client, feedback_needed
