### ISSUE TITLE
Add Circuit breaker on Transport ResponseHandlers

### ISSUE THREAD

**Issue by easyice** [elastic/elasticsearch#66196] opened 2020-12-11 02:32 UTC
for every in flight Transport request， we add  a handler at  `org.elasticsearch.transport.Transport.ResponseHandlers`

````
public long add(ResponseContext<? extends TransportResponse> holder) {
            long requestId = newRequestId();
            ResponseContext existing = handlers.put(requestId, holder);
            assert existing == null : "request ID already in use: " + requestId;
            return requestId;
      }
````

some times, the users sent a lot of request, such as query, that they exceed the system's capacity，then, CPU utilization reached 100%, but ,The client still sends a large number of requests，the requests  will be add in `ResponseHandlers#handlers`

then the Elasticsearch nodes will be oom

This happened to me a few times,I dump the jvm  memory，open with Eclipse Memory Analyzer, it show the `ResponseHandlers#handlers` used 7.7GB memory

![image](https://user-images.githubusercontent.com/23521001/101854153-e998b180-3b9b-11eb-8e33-40359d09147b.png)

**Comment by Hailei** [comment] 2021-01-14 07:00
Add some information that maybe helpful to find out root cause.
### Basic configuration
ES version:6.8.0
write_queuesize:1000
the size of data nodes: 52
total shards: 62650:
special index setting:  total_shards_per_node:xx

> epoch      timestamp cluster status node.total node.data shards   pri relo init unassign pending_tasks max_task_wait_time active_shards_percent
1610606033 06:33:53  ad_bi_3 green          65        52  62650 31310    2    0        0             8              18.5s                100.0%

This problem occurred again last night, Our index is time series, divided by day. So will create a lot of indexes  at 0 o'clock, unfortunately we enabled dynamic mapping, if find not existing field, will send update mapping request to master, this operation is blocked. in the meantime, we have another process to creating offline index, since the size of total shards is very large, creating index is very slow, usually  more than 30s.  because the priority of put-mapping is lower then create-index, So Put-mapping will be blocked, Bulk requests will be piled up in the queue
if this size of single bulk is pretty large，this will lead to OOM

I think Rejecting has effort to this problem, But not sure if it can totally solve this problem

more interesting thing that  need to clarify，the size of write queue is 1000, it can be far beyond 1000 in the accident


![image](https://user-images.githubusercontent.com/1724869/104555456-e1d79b80-5678-11eb-9be9-81168a38a1c7.png)

![image](https://user-images.githubusercontent.com/1724869/104555534-0469b480-5679-11eb-8258-8239f233e180.png)

**Comment by DaveCTurner** [comment] 2021-01-14 08:30
@Hailei your comment is off-topic for this thread so I've hidden it. The issue you describe is not related to response handling and is addressed in newer versions, see https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-indexing-pressure.html. It's also a natural consequence of using dynamic mappings so heavily. If you need further assistance, please start a conversation on the [discussion forums](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6).

**Comment by Hailei** [comment] 2021-01-14 08:42
> @Hailei your comment is off-topic for this thread so I've hidden it. The issue you describe is not related to response handling and is addressed in newer versions, see https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-indexing-pressure.html. It's also a natural consequence of using dynamic mappings so heavily. If you need further assistance, please start a conversation on the [discussion forums](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6).

@DaveCTurner , I think my comment is related to this thread, Since they are the same cluster,I just explain why lead to GC,if rejecting works, the request will fast fail,don't piled up

**Comment by DaveCTurner** [comment] 2021-01-14 08:48
I don't think there's a general transport-level solution for limiting the size retained by a response handler since the memory retained by a handler is pretty much independent of the transport layer. The OP doesn't tell us anything about what requests correspond with the problematic response handlers, nor what version they're using. Likely culprits include searches (in which case this duplicates #67478), stats (in which case this duplicates #55550) or bulks (in which case this is resolved by the new indexing pressure mechanisms). @easyice to what requests do the problematic handlers relate?

**Comment by Hailei** [comment] 2021-01-14 09:03
>

> I don't think there's a general transport-level solution for limiting the size retained by a response handler since the memory retained by a handler is pretty much independent of the transport layer.
 I can't agree any more, @easyice  is my coworker, The cluster that this issue mentioned is the same to me

ES version: 6.8.0

**Comment by DaveCTurner** [comment] 2021-01-14 09:16
Ok, there is a solution for limiting the size retained by _bulk_ response handlers, and it's already implemented (as of 7.9) so I think there's no further action needed here.

**Closed by DaveCTurner** 2021-01-14 09:16 UTC
Labels: :Distributed/Network, >enhancement, Team:Distributed, feedback_needed, team-discuss

**Comment by easyice** [comment] 2021-01-15 10:03
@DaveCTurner  Thanks for reply, Let me add the relate requests, It doesn't just appear in bulk，also in search request,like this:

![image](https://user-images.githubusercontent.com/23521001/104710926-a6fa6400-575b-11eb-8202-8fd260567a79.png)

**Comment by DaveCTurner** [comment] 2021-01-15 10:07
Indeed, we're tracking the issue for search responses at https://github.com/elastic/elasticsearch/issues/67478.
