### ISSUE TITLE
Allow Other methods of s3 server-side encryption

### ISSUE THREAD

**Issue by tylerfontaine** [elastic/elasticsearch#18561] opened 2016-05-25 02:59 UTC
**Describe the feature**: 

Currently, by setting server_side_encryption to true, the only method that is allowed is aes256. It would be great if we could specify other s3 encryption methods, e.g. aws:kms.

For aws:kms, if the bucket has a default key, it's just a matter of including the correct header, so one possibility may be an additional parameter to specify the value of the `x-amz-server-side-encryption` header to get sent with requests. But the ability to specify an ams key to use would also be great.

**Comment by dadoonet** [comment] 2016-05-25 08:34
Related doc: http://docs.aws.amazon.com/AmazonS3/latest/dev/client-side-using-kms-java.html

**Comment by smarks** [comment] 2017-05-08 15:20
I would like to work on this.

**Comment by original-brownbear** [comment] 2019-07-22 19:29
Closing here as a duplicate of https://github.com/elastic/elasticsearch/issues/41196

**Closed by original-brownbear** 2019-07-22 19:29 UTC
Labels: :Distributed/Snapshot/Restore, >enhancement, help wanted
