### ISSUE TITLE
[CI] DataTierMixedIT testMixedTierCompatibility failing

### ISSUE THREAD

**Issue by volodk85** [elastic/elasticsearch#103362] opened 2023-12-12 22:28 UTC
Seems this did not happen in the past. Opening new issue for investigation

**Build scan:**
https://gradle-enterprise.elastic.co/s/veevi27x3el3u/tests/:x-pack:qa:mixed-tier-cluster:v8.10.2%23mixedClusterTest/org.elasticsearch.mixed.DataTierMixedIT/testMixedTierCompatibility

**Reproduction line:**
```
./gradlew ':x-pack:qa:mixed-tier-cluster:v8.10.2#mixedClusterTest' -Dtests.class="org.elasticsearch.mixed.DataTierMixedIT" -Dtests.method="testMixedTierCompatibility" -Dtests.seed=D583F4DF623A54E -Dtests.bwc=true -Dtests.locale=es-BO -Dtests.timezone=Asia/Oral -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
[Failure dashboard for `org.elasticsearch.mixed.DataTierMixedIT#testMixedTierCompatibility`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testMixedTierCompatibility'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.mixed.DataTierMixedIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.net.ConnectException: Connection refused

  at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:934)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:304)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:323)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:323)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:323)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:323)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:307)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:292)
  at org.elasticsearch.test.rest.ESRestTestCase.getClusterStateFeatures(ESRestTestCase.java:2071)
  at org.elasticsearch.test.rest.ESRestTestCase.initClient(ESRestTestCase.java:305)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:980)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

  Caused by: java.net.ConnectException: Connection refused

    at sun.nio.ch.Net.pollConnect(Net.java:-2)
    at sun.nio.ch.Net.pollConnectNow(Net.java:682)
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:973)
    at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:174)
    at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:148)
    at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:351)
    at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:221)
    at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
    at java.lang.Thread.run(Thread.java:1583)

```

**Comment by rjernst** [comment] 2023-12-13 05:13
This test cluster seemed to really struggle. It had issues in coordination early on, and one node failed with `exiting java.lang.AssertionError: org.elasticsearch.gateway.CorruptStateException`. Seems more likely distributed can help out here.

**Comment by pxsalehi** [comment] 2023-12-14 12:31
Master seems to fail while writing/parsing some index_template:
```
» [2023-12-12T21:31:45,715][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [v8.10.2-2] fatal error in thread [elasticsearch[v8.10.2-2][cluster_coordination][T#1]], exiting java.lang.AssertionError: org.elasticsearch.gateway.CorruptStateException: org.elasticsearch.xcontent.XContentParseException: [-1:34566] [index_template] failed to parse field [index_template]
»  	at org.elasticsearch.server@8.10.2/org.elasticsearch.gateway.PersistedClusterStateService$Writer.assertOnCommit(PersistedClusterStateService.java:1244)
»  	at org.elasticsearch.server@8.10.2/org.elasticsearch.gateway.PersistedClusterStateService$Writer.commit(PersistedClusterStateService.java:1234)
»  	at org.elasticsearch.server@8.10.2/org.elasticsearch.gateway.PersistedClusterStateService$Writer.writeIncrementalStateAndCommit(PersistedClusterStateService.java:976)
»  	at org.elasticsearch.server@8.10.2/org.elasticsearch.gateway.GatewayMetaState$LucenePersistedState.writeClusterStateToDisk(GatewayMetaState.java:579)
»  	at org.elasticsearch.server@8.10.2/org.elasticsearch.gateway.GatewayMetaState$LucenePersistedState.setLastAcceptedState(GatewayMetaState.java:562)
»  	at org.elasticsearch.server@8.10.2/org.elasticsearch.cluster.coordination.CoordinationState.handlePublishRequest(CoordinationState.java:392)
»  	at org.elasticsearch.server@8.10.2/org.elasticsearch.cluster.coordination.Coordinator.handlePublishRequest(Coordinator.java:469)
»  	at org.elasticsearch.server@8.10.2/org.elasticsearch.cluster.coordination.PublicationTransportHandler.acceptState(PublicationTransportHandler.java:213)
»  	at org.elasticsearch.server@8.10.2/org.elasticsearch.cluster.coordination.PublicationTransportHandler.handleIncomingPublishRequest(PublicationTransportHandler.java:200)
»  	at org.elasticsearch.server@8.10.2/org.elasticsearch.cluster.coordination.PublicationTransportHandler.lambda$new$0(PublicationTransportHandler.java:112)
»  	at org.elasticsearch.server@8.10.2/org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:74)
»  	at org.elasticsearch.server@8.10.2/org.elasticsearch.transport.InboundHandler$1.doRun(InboundHandler.java:294)
»  	at org.elasticsearch.server@8.10.2/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)
»  	at org.elasticsearch.server@8.10.2/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
»  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
»  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
»  	at java.base/java.lang.Thread.run(Thread.java:1623)
»  Caused by: org.elasticsearch.gateway.CorruptStateException: org.elasticsearch.xcontent.XContentParseException: [-1:34566] [index_template] failed to parse field [index_template]
»  	at org.elasticsearch.server@8.10.2/org.elasticsearch.gateway.PersistedClusterStateService.readXContent(PersistedClusterStateService.java:674)
»  	at org.elasticsearch.server@8.10.2/org.elasticsearch.gateway.PersistedClusterStateService.lambda$loadOnDiskState$6(PersistedClusterStateService.java:572)
»  	at org.elasticsearch.server@8.10.2/org.elasticsearch.gateway.PersistedClusterStateService.consumeFromType(PersistedClusterStateService.java:716)
»  	at org.elasticsearch.server@8.10.2/org.elasticsearch.gateway.PersistedClusterStateService.loadOnDiskState(PersistedClusterStateService.java:571)
»  	at org.elasticsearch.server@8.10.2/org.elasticsearch.gateway.PersistedClusterStateService$Writer.assertOnCommit(PersistedClusterStateService.java:1242)
»  	... 16 more
»  Caused by: org.elasticsearch.xcontent.XContentParseException: [-1:34566] [index_template] failed to parse field [index_template]
»  	at org.elasticsearch.xcontent@8.10.2/org.elasticsearch.xcontent.ObjectParser.throwFailedToParse(ObjectParser.java:616)
»  	at org.elasticsearch.xcontent@8.10.2/org.elasticsearch.xcontent.ObjectParser.parseValue(ObjectParser.java:611)
»  	at org.elasticsearch.xcontent@8.10.2/org.elasticsearch.xcontent.ObjectParser.parseSub(ObjectParser.java:629)
»  	at org.elasticsearch.xcontent@8.10.2/org.elasticsearch.xcontent.ObjectParser.parse(ObjectParser.java:315)
»  	at org.elasticsearch.xcontent@8.10.2/org.elasticsearch.xcontent.ConstructingObjectParser.parse(ConstructingObjectParser.java:166)
»  	at org.elasticsearch.server@8.10.2/org.elasticsearch.cluster.metadata.ComposableIndexTemplateMetadata.fromXContent(ComposableIndexTemplateMetadata.java:67)
»  	at org.elasticsearch.xcontent@8.10.2/org.elasticsearch.xcontent.NamedXContentRegistry$Entry.lambda$new$0(NamedXContentRegistry.java:54)
»  	at org.elasticsearch.xcontent@8.10.2/org.elasticsearch.xcontent.NamedXContentRegistry.parseNamedObject(NamedXContentRegistry.java:147)
»  	at org.elasticsearch.xcontent@8.10.2/org.elasticsearch.xcontent.support.AbstractXContentParser.namedObject(AbstractXContentParser.java:414)
»  	at org.elasticsearch.server@8.10.2/org.elasticsearch.cluster.metadata.Metadata$Builder.fromXContent(Metadata.java:2660)
»  	at org.elasticsearch.server@8.10.2/org.elasticsearch.gateway.PersistedClusterStateService.readXContent(PersistedClusterStateService.java:672)
»  	... 20 more
»  Caused by: org.elasticsearch.xcontent.XContentParseException: [-1:34566] [index_template] failed to parse field [template]
»  	at org.elasticsearch.xcontent@8.10.2/org.elasticsearch.xcontent.ObjectParser.throwFailedToParse(ObjectParser.java:616)
»  	at org.elasticsearch.xcontent@8.10.2/org.elasticsearch.xcontent.ObjectParser.parseValue(ObjectParser.java:611)
»  	at org.elasticsearch.xcontent@8.10.2/org.elasticsearch.xcontent.ObjectParser.parseSub(ObjectParser.java:629)
»  	at org.elasticsearch.xcontent@8.10.2/org.elasticsearch.xcontent.ObjectParser.parse(ObjectParser.java:315)
»  	at org.elasticsearch.xcontent@8.10.2/org.elasticsearch.xcontent.ConstructingObjectParser.parse(ConstructingObjectParser.java:166)
»  	at org.elasticsearch.server@8.10.2/org.elasticsearch.cluster.metadata.ComposableIndexTemplate.parse(ComposableIndexTemplate.java:102)
»  	at org.elasticsearch.server@8.10.2/org.elasticsearch.cluster.metadata.ComposableIndexTemplateMetadata.lambda$static$1(ComposableIndexTemplateMetadata.java:50)
»  	at org.elasticsearch.xcontent@8.10.2/org.elasticsearch.xcontent.ObjectParser.lambda$declareField$10(ObjectParser.java:431)
»  	at org.elasticsearch.xcontent@8.10.2/org.elasticsearch.xcontent.ObjectParser.parseValue(ObjectParser.java:609)
»  	... 29 more
»  Caused by: org.elasticsearch.xcontent.XContentParseException: [-1:34564] [template] unknown field [lifecycle]
»  	at org.elasticsearch.xcontent@8.10.2/org.elasticsearch.xcontent.ObjectParser.lambda$errorOnUnknown$2(ObjectParser.java:105)
»  	at org.elasticsearch.xcontent@8.10.2/org.elasticsearch.xcontent.ObjectParser.parse(ObjectParser.java:299)
»  	at org.elasticsearch.xcontent@8.10.2/org.elasticsearch.xcontent.ConstructingObjectParser.parse(ConstructingObjectParser.java:166)
»  	at org.elasticsearch.xcontent@8.10.2/org.elasticsearch.xcontent.ObjectParser.lambda$declareField$10(ObjectParser.java:431)
»  	at org.elasticsearch.xcontent@8.10.2/org.elasticsearch.xcontent.ObjectParser.parseValue(ObjectParser.java:609)
```

Seems to be complaining about [this field](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/cluster/metadata/Template.java#L48) which is related to DLM.

**Comment by idegtiarenko** [comment] 2023-12-14 12:34
I believe exactly the same failure is tracked (and triaged to correct team) here: https://github.com/elastic/elasticsearch/issues/103358#issuecomment-1853314589

**Comment by pxsalehi** [comment] 2023-12-14 12:35
Well, then! Closing as duplicate of that one! Thanks, Ievgen!

**Closed by pxsalehi** 2023-12-14 12:35 UTC
Labels: blocker, >test-failure, :Distributed/Distributed, Team:Distributed
