### ISSUE TITLE
SumLongAggregator led to java.lang.ArithmeticException: long overflow exception

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#110987] opened 2024-07-17 17:48 UTC
### Elasticsearch Version

8.14.1

### Java Version

serverless environment

### OS Version

serverless environment

### Problem Description

SumLongAggregator led to java.lang.ArithmeticException: long overflow exception

### Steps to Reproduce

A request to `_query` API caused that, but can't say what request exactly. 

### Logs (if relevant)

"error.stack_trace": [
      "java.lang.ArithmeticException: long overflow\n\tat java.base/java.lang.Math.addExact(Math.java:932)\n\tat org.elasticsearch.compute.aggregation.SumLongAggregator.combine(SumLongAggregator.java:23)\n\tat org.elasticsearch.compute.aggregation.SumLongAggregatorFunction.addRawBlock(SumLongAggregatorFunction.java:84)\n\tat org.elasticsearch.compute.aggregation.SumLongAggregatorFunction.addRawInput(SumLongAggregatorFunction.java:64)\n\tat org.elasticsearch.compute.aggregation.Aggregator.processPage(Aggregator.java:42)\n\tat org.elasticsearch.compute.operator.AggregationOperator.addInput(AggregationOperator.java:98)\n\tat org.elasticsearch.compute.operator.Driver.runSingleLoopIteration(Driver.java:255)\n\tat org.elasticsearch.compute.operator.Driver.run(Driver.java:178)\n\tat org.elasticsearch.compute.operator.Driver$1.doRun(Driver.java:364)\n\tat org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)\n\tat org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)\n\tat org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)\n\tat org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1570)\n"
    ],

**Comment by alex-spies** [comment] 2024-07-18 08:11
Thanks Mayya! I think this is a duplicate of https://github.com/elastic/elasticsearch/issues/110437.

**Closed** 2024-07-18 08:11 UTC
Labels: >bug, Team:Analytics, :Analytics/ES|QL
