### ISSUE TITLE
Can not use the GetTransform API with the RestHighLevelClient

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#64602] opened 2020-11-04 17:22 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 7.9.3

**Steps to reproduce**:

I tried this code:

EDITED on Dec 17th, 2020:

```java
    @Test
    void transformApi() {
        try (RestHighLevelClient client = new RestHighLevelClient(
                RestClient.builder(HttpHost.create("http://localhost:9200")))) {
            try {
                client.indices().delete(new DeleteIndexRequest("transform-source"), RequestOptions.DEFAULT);
            } catch (ElasticsearchStatusException ignored) { }
            client.index(new IndexRequest("transform-source").id("1").source("{\"foo\":\"bar\"}", XContentType.JSON), RequestOptions.DEFAULT);
            client.indices().refresh(new RefreshRequest("transform-source"), RequestOptions.DEFAULT);

            String id = "test-get";

            GroupConfig groupConfig = GroupConfig.builder().groupBy("reviewer",
                    TermsGroupSource.builder().setField("user_id").build()).build();
            AggregatorFactories.Builder aggBuilder = new AggregatorFactories.Builder();
            aggBuilder.addAggregator(AggregationBuilders.avg("avg_rating").field("stars"));
            PivotConfig pivotConfig = PivotConfig.builder().setGroups(groupConfig).setAggregations(aggBuilder).build();

            DestConfig destConfig = DestConfig.builder().setIndex("pivot-dest").build();

            TransformConfig transform = TransformConfig.builder()
                    .setId(id)
                    .setSource(SourceConfig.builder().setIndex("transform-source").setQuery(new MatchAllQueryBuilder()).build())
                    .setDest(destConfig)
                    .setPivotConfig(pivotConfig)
                    .setDescription("this is a test transform")
                    .build();

            client.transform().putTransform(new PutTransformRequest(transform), RequestOptions.DEFAULT);

            GetTransformResponse response = client.transform().getTransform(new GetTransformRequest(id), RequestOptions.DEFAULT);
            System.out.println("response.getCount() = " + response.getCount());
        } catch (Exception e) {
            e.printStackTrace(System.err);
        }
    }
```

**Provide logs (if relevant)**:

EDITED on Dec 17th, 2020:

```
java.io.IOException: Unable to parse response body for Response{requestLine=GET /_transform/test-get HTTP/1.1, host=http://localhost:55014, response=HTTP/1.1 200 OK}

	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1651)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1617)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1584)
	at org.elasticsearch.client.TransformClient.getTransform(TransformClient.java:361)
	at fr.pilato.test.elasticsearch.hlclient.EsClientTest.transformApi(EsClientTest.java:287)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:212)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:208)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: org.elasticsearch.common.xcontent.XContentParseException: [1:103] [get_transform] failed to parse field [transforms]
	at org.elasticsearch.common.xcontent.ObjectParser.parseValue(ObjectParser.java:531)
	at org.elasticsearch.common.xcontent.ObjectParser.parseArray(ObjectParser.java:523)
	at org.elasticsearch.common.xcontent.ObjectParser.parseSub(ObjectParser.java:555)
	at org.elasticsearch.common.xcontent.ObjectParser.parse(ObjectParser.java:324)
	at org.elasticsearch.common.xcontent.ConstructingObjectParser.parse(ConstructingObjectParser.java:171)
	at org.elasticsearch.common.xcontent.ConstructingObjectParser.apply(ConstructingObjectParser.java:163)
	at org.elasticsearch.client.transform.GetTransformResponse.fromXContent(GetTransformResponse.java:64)
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1911)
	at org.elasticsearch.client.RestHighLevelClient.lambda$performRequestAndParseEntity$9(RestHighLevelClient.java:1585)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1649)
	... 67 more
Caused by: org.elasticsearch.common.xcontent.XContentParseException: [1:103] [transform] failed to parse field [source]
	at org.elasticsearch.common.xcontent.ObjectParser.parseValue(ObjectParser.java:531)
	at org.elasticsearch.common.xcontent.ObjectParser.parseSub(ObjectParser.java:541)
	at org.elasticsearch.common.xcontent.ObjectParser.parse(ObjectParser.java:324)
	at org.elasticsearch.common.xcontent.ConstructingObjectParser.parse(ConstructingObjectParser.java:171)
	at org.elasticsearch.common.xcontent.ConstructingObjectParser.apply(ConstructingObjectParser.java:163)
	at org.elasticsearch.common.xcontent.AbstractObjectParser.lambda$declareObjectArray$13(AbstractObjectParser.java:254)
	at org.elasticsearch.common.xcontent.AbstractObjectParser.lambda$declareFieldArray$22(AbstractObjectParser.java:300)
	at org.elasticsearch.common.xcontent.AbstractObjectParser.parseArray(AbstractObjectParser.java:382)
	at org.elasticsearch.common.xcontent.AbstractObjectParser.lambda$declareFieldArray$23(AbstractObjectParser.java:300)
	at org.elasticsearch.common.xcontent.ObjectParser.lambda$declareField$9(ObjectParser.java:386)
	at org.elasticsearch.common.xcontent.ObjectParser.parseValue(ObjectParser.java:529)
	... 76 more
Caused by: org.elasticsearch.common.xcontent.XContentParseException: [1:103] [transform_config_source] failed to parse field [query]
	at org.elasticsearch.common.xcontent.ObjectParser.parseValue(ObjectParser.java:531)
	at org.elasticsearch.common.xcontent.ObjectParser.parseSub(ObjectParser.java:541)
	at org.elasticsearch.common.xcontent.ObjectParser.parse(ObjectParser.java:324)
	at org.elasticsearch.common.xcontent.ConstructingObjectParser.parse(ConstructingObjectParser.java:171)
	at org.elasticsearch.common.xcontent.ConstructingObjectParser.apply(ConstructingObjectParser.java:163)
	at org.elasticsearch.client.transform.transforms.TransformConfig.lambda$static$1(TransformConfig.java:99)
	at org.elasticsearch.common.xcontent.AbstractObjectParser.lambda$declareObject$1(AbstractObjectParser.java:170)
	at org.elasticsearch.common.xcontent.ObjectParser.lambda$declareField$9(ObjectParser.java:386)
	at org.elasticsearch.common.xcontent.ObjectParser.parseValue(ObjectParser.java:529)
	... 86 more
Caused by: org.elasticsearch.common.xcontent.XContentParseException: unknown named object category [org.elasticsearch.index.query.QueryBuilder]
	at org.elasticsearch.common.xcontent.NamedXContentRegistry.parseNamedObject(NamedXContentRegistry.java:128)
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.namedObject(AbstractXContentParser.java:409)
	at org.elasticsearch.index.query.AbstractQueryBuilder.parseInnerQueryBuilder(AbstractQueryBuilder.java:320)
	at org.elasticsearch.client.transform.transforms.QueryConfig.fromXContent(QueryConfig.java:39)
	at org.elasticsearch.client.transform.transforms.SourceConfig.lambda$static$1(SourceConfig.java:56)
	at org.elasticsearch.common.xcontent.AbstractObjectParser.lambda$declareObject$1(AbstractObjectParser.java:170)
	at org.elasticsearch.common.xcontent.ObjectParser.lambda$declareField$9(ObjectParser.java:386)
	at org.elasticsearch.common.xcontent.ObjectParser.parseValue(ObjectParser.java:529)
	... 94 more
```

This has been reported at https://discuss.elastic.co/t/gettransformresponse-unable-to-parse-source-field/254305

The full code to test this is available at: https://github.com/dadoonet/elasticsearch-java-client-demo

**Comment by benwtrent** [comment] 2020-11-05 19:54
@dadoonet this error is because a transform with that ID exists already in your cluster. The user in the discuss ticket is having problems with named x content serialization I think.
```
Caused by: org.elasticsearch.common.xcontent.XContentParseException: [1:137] [transform_config_source] failed to parse field [query]
	at org.elasticsearch.common.xcontent.ObjectParser.parseValue(ObjectParser.java:531) ~[elasticsearch-x-content-7.8.1.jar:7.8.1]
	at org.elasticsearch.common.xcontent.ObjectParser.parseSub(ObjectParser.java:541) ~[elasticsearch-x-content-7.8.1.jar:7.8.1]
	at org.elasticsearch.common.xcontent.ObjectParser.parse(ObjectParser.java:324) ~[elasticsearch-x-content-7.8.1.jar:7.8.1]
	at org.elasticsearch.common.xcontent.ConstructingObjectParser.parse(ConstructingObjectParser.java:171) ~[elasticsearch-x-content-7.8.1.jar:7.8.1]
	at org.elasticsearch.common.xcontent.ConstructingObjectParser.apply(ConstructingObjectParser.java:163) ~[elasticsearch-x-content-7.8.1.jar:7.8.1]
	at org.elasticsearch.client.transform.transforms.TransformConfig.lambda$static$1(TransformConfig.java:99) ~[elasticsearch-rest-high-level-client-7.8.1.jar:7.8.1]
	at org.elasticsearch.common.xcontent.AbstractObjectParser.lambda$declareObject$1(AbstractObjectParser.java:169) ~[elasticsearch-x-content-7.8.1.jar:7.8.1]
	at org.elasticsearch.common.xcontent.ObjectParser.lambda$declareField$9(ObjectParser.java:386) ~[elasticsearch-x-content-7.8.1.jar:7.8.1]
	at org.elasticsearch.common.xcontent.ObjectParser.parseValue(ObjectParser.java:529) ~[elasticsearch-x-content-7.8.1.jar:7.8.1]
	... 47 common frames omitted
Caused by: org.elasticsearch.common.xcontent.XContentParseException: unknown named object category [org.elasticsearch.index.query.QueryBuilder]
	at org.elasticsearch.common.xcontent.NamedXContentRegistry.parseNamedObject(NamedXContentRegistry.java:128) ~[elasticsearch-x-content-7.8.1.jar:7.8.1]
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.namedObject(AbstractXContentParser.java:385) ~[elasticsearch-x-content-7.8.1.jar:7.8.1]
	at org.elasticsearch.index.query.AbstractQueryBuilder.parseInnerQueryBuilder(AbstractQueryBuilder.java:320) ~[elasticsearch-7.8.1.jar:7.8.1]
	at org.elasticsearch.client.transform.transforms.QueryConfig.fromXContent(QueryConfig.java:39) ~[elasticsearch-rest-high-level-client-7.8.1.jar:7.8.1]
	at org.elasticsearch.client.transform.transforms.SourceConfig.lambda$static$1(SourceConfig.java:56) ~[elasticsearch-rest-high-level-client-7.8.1.jar:7.8.1]
	at org.elasticsearch.common.xcontent.AbstractObjectParser.lambda$declareObject$1(AbstractObjectParser.java:169) ~[elasticsearch-x-content-7.8.1.jar:7.8.1]
	at org.elasticsearch.common.xcontent.ObjectParser.lambda$declareField$9(ObjectParser.java:386) ~[elasticsearch-x-content-7.8.1.jar:7.8.1]
	at org.elasticsearch.common.xcontent.ObjectParser.parseValue(ObjectParser.java:529) ~[elasticsearch-x-content-7.8.1.jar:7.8.1]
	... 55 common frames omitted
```
`unknown named object category [org.elasticsearch.index.query.QueryBuilder]` indicates that the RestHighLevelClient was somehow constructed without the appropriate named x content entries.

**Comment by benwtrent** [comment] 2020-11-05 19:57
I don't think this is a transform bug at all @dadoonet 

Here are our own transform rest high level client integration tests to catch regressions: https://github.com/elastic/elasticsearch/blob/master/client/rest-high-level/src/test/java/org/elasticsearch/client/TransformIT.java

If desired, we can add a more complicated query scenario there.

**Comment by dadoonet** [comment] 2020-11-05 20:00
> @dadoonet this error is because a transform with that ID exists already in your cluster. The user in the discuss ticket is having problems with named x content serialization I think.
> 
> ```
> Caused by: org.elasticsearch.common.xcontent.XContentParseException: [1:137] [transform_config_source] failed to parse field [query]
> 	at org.elasticsearch.common.xcontent.ObjectParser.parseValue(ObjectParser.java:531) ~[elasticsearch-x-content-7.8.1.jar:7.8.1]
> 	at org.elasticsearch.common.xcontent.ObjectParser.parseSub(ObjectParser.java:541) ~[elasticsearch-x-content-7.8.1.jar:7.8.1]
> 	at org.elasticsearch.common.xcontent.ObjectParser.parse(ObjectParser.java:324) ~[elasticsearch-x-content-7.8.1.jar:7.8.1]
> 	at org.elasticsearch.common.xcontent.ConstructingObjectParser.parse(ConstructingObjectParser.java:171) ~[elasticsearch-x-content-7.8.1.jar:7.8.1]
> 	at org.elasticsearch.common.xcontent.ConstructingObjectParser.apply(ConstructingObjectParser.java:163) ~[elasticsearch-x-content-7.8.1.jar:7.8.1]
> 	at org.elasticsearch.client.transform.transforms.TransformConfig.lambda$static$1(TransformConfig.java:99) ~[elasticsearch-rest-high-level-client-7.8.1.jar:7.8.1]
> 	at org.elasticsearch.common.xcontent.AbstractObjectParser.lambda$declareObject$1(AbstractObjectParser.java:169) ~[elasticsearch-x-content-7.8.1.jar:7.8.1]
> 	at org.elasticsearch.common.xcontent.ObjectParser.lambda$declareField$9(ObjectParser.java:386) ~[elasticsearch-x-content-7.8.1.jar:7.8.1]
> 	at org.elasticsearch.common.xcontent.ObjectParser.parseValue(ObjectParser.java:529) ~[elasticsearch-x-content-7.8.1.jar:7.8.1]
> 	... 47 common frames omitted
> Caused by: org.elasticsearch.common.xcontent.XContentParseException: unknown named object category [org.elasticsearch.index.query.QueryBuilder]
> 	at org.elasticsearch.common.xcontent.NamedXContentRegistry.parseNamedObject(NamedXContentRegistry.java:128) ~[elasticsearch-x-content-7.8.1.jar:7.8.1]
> 	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.namedObject(AbstractXContentParser.java:385) ~[elasticsearch-x-content-7.8.1.jar:7.8.1]
> 	at org.elasticsearch.index.query.AbstractQueryBuilder.parseInnerQueryBuilder(AbstractQueryBuilder.java:320) ~[elasticsearch-7.8.1.jar:7.8.1]
> 	at org.elasticsearch.client.transform.transforms.QueryConfig.fromXContent(QueryConfig.java:39) ~[elasticsearch-rest-high-level-client-7.8.1.jar:7.8.1]
> 	at org.elasticsearch.client.transform.transforms.SourceConfig.lambda$static$1(SourceConfig.java:56) ~[elasticsearch-rest-high-level-client-7.8.1.jar:7.8.1]
> 	at org.elasticsearch.common.xcontent.AbstractObjectParser.lambda$declareObject$1(AbstractObjectParser.java:169) ~[elasticsearch-x-content-7.8.1.jar:7.8.1]
> 	at org.elasticsearch.common.xcontent.ObjectParser.lambda$declareField$9(ObjectParser.java:386) ~[elasticsearch-x-content-7.8.1.jar:7.8.1]
> 	at org.elasticsearch.common.xcontent.ObjectParser.parseValue(ObjectParser.java:529) ~[elasticsearch-x-content-7.8.1.jar:7.8.1]
> 	... 55 common frames omitted
> ```
> 
> `unknown named object category [org.elasticsearch.index.query.QueryBuilder]` indicates that the RestHighLevelClient was somehow constructed without the appropriate named x content entries.

Damn. I think I pasted the wrong error and not the initial one. I'll reproduce it.

**Comment by benwtrent** [comment] 2020-11-05 20:05
@dadoonet I bet that your reproduction is due to not including the `SearchPlugin` named x content serializers, if you are able to reproduce the issue.

**Comment by benwtrent** [comment] 2020-11-05 20:12
Here is what we do in the integration test framework:

```
private static class HighLevelClient extends RestHighLevelClient {
        private HighLevelClient(RestClient restClient) {
            super(restClient, (client) -> {}, new SearchModule(Settings.EMPTY, Collections.emptyList()).getNamedXContents());
        }
    }
```

Note the inclusion of the `SearchModule` `getNamedXContents()`

**Comment by dadoonet** [comment] 2020-11-05 20:40
But I'm doing that in an external project like any java end user would do. 
Is that something people have to do if they want to use the transform API? 
In that case it needs to be documented.

**Comment by benwtrent** [comment] 2020-11-05 21:17
@dadoonet, no it is not something they need to interact with the transform API. It is something need to do when parsing search queries.

I agree, documentation here is lacking (especially around these types of errors, etc.). But, this is not a transforms issue. It seems like an overall high level rest client documentation issue.

**Comment by swallez** [comment] 2020-11-09 13:18
@benwtrent I'm a bit puzzled by _"it is not something they need to interact with the transform API"_ and _"it seems like an overall high level rest client documentation issue"_.

As I understand the issue, the high level client has its XContent registry missing some entries to correctly parse the result of `client.transform().getTransform` (namely the `query` field).

So it does seem like a bug of the client caused by an incomplete `NamedXContentRegistry` more than a documentation issue, as this should work out the box.

WDYT?

If we agree this is a code bug, what would be the best place to add this? As code inside `RestHighLevelClient` or in the client's `META-INF/services/org.elasticsearch.plugins.spi.NamedXContentProvider` file?

**Comment by benwtrent** [comment] 2020-11-09 13:25
Yeah, I do think it's weird that we don't do a blanket inclusion of all named xcontent parsers 

As for a place to put it... I leave that to you :).

Is there any reason for a user to NOT want to have these named xcontent parsers?

**Comment by swallez** [comment] 2020-11-09 13:30
> Is there any reason for a user to NOT want to have these named xcontent parsers?

Well, I think users of the high level client should not even have to care about what an xcontent parser is 😉 

I'll prepare a PR to add the missing bits!

**Comment by dadoonet** [comment] 2020-11-09 18:02
Agreed. As I said [on discuss](https://discuss.elastic.co/t/gettransformresponse-unable-to-parse-source-field/254305/11?u=dadoonet):

> But I do think that end users should not have to care about that.
> It should be available OOTB.

+1 to consider this as a bug and not a documentation issue.

**Comment by dadoonet** [comment] 2020-12-17 12:09
For the record, I edited the original description by adding the real stacktrace 😄

**Comment by hendrikmuhs** [comment] 2022-07-29 10:34
Because the java high level rest client is deprecated, I am closing this as "won't fix"

**Closed by hendrikmuhs** 2022-07-29 10:34 UTC
Labels: >bug, :Clients/Java High Level REST Client, :ml/Transform, Team:Data Management, Team:Clients
