### ISSUE TITLE
Documents ids with slashes cause issues in high-level client

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#37405] opened 2019-01-14 09:35 UTC
This issue was originated from #36988 . When using the high-level REST client to get/index/update documents, slashes in ids can cause problems. This has to do with the logic that encodes each url part separately and then puts the result together in `RequestConverters`. The following test fails while I think it should succeed. What I think happens at the moment is that the document gets indexed with a different id than the one provided.

```
public void testIdWithSlashes() throws IOException {
       IndexRequest indexRequest = new IndexRequest("dev_product");
       indexRequest.id("/sku/test.com/48923AQ3");
       indexRequest.source("field", "value");
       IndexResponse indexResponse = highLevelClient().index(indexRequest, RequestOptions.DEFAULT);

       assertEquals("/sku/test.com/48923AQ3", indexResponse.getId());

       GetResponse getResponse = highLevelClient()
           .get(new GetRequest("dev_product", "/sku/test.com/48923AQ3"), RequestOptions.DEFAULT);
       assertTrue(getResponse.isExists());
   }
```

**Comment by martijnvg** [comment] 2019-01-16 08:06
This is how the id is received when the index request is sent via the HLRC: `test.com/48923AQ3`
The `/sku/` is missing.

I think the problem is in the `EndpointBuilder#encodePart(...)` method in `RequestCoverters.java` line 1106. I think in the case that the pathPart starts with a `/` then it should not add extra leading slash.

This is a more targeted test:

```
EndpointBuilder endpointBuilder = new EndpointBuilder().addPathPart("/sku/test.com/48923AQ3");
assertEquals("/%2Fsku%2Ftest.com%2F48923AQ3", endpointBuilder.build());
```

**Comment by iverase** [comment] 2021-09-02 12:42
It seems this issue has been fixed in https://github.com/elastic/elasticsearch/pull/34436 so it can be closed? the examples given here pass successfully.

**Closed** 2022-01-05 15:29 UTC
Labels: >bug, :Data Management/Java High Level REST Client, Team:Data Management
