### ISSUE TITLE
[ML] Missing audit messages when stopping datafeed that is awaiting assignment

### ISSUE THREAD

**Issue by sophiec20** [elastic/elasticsearch#55521] opened 2020-04-21 11:02 UTC
Noticed in 7.7.0-BC8
Usability minor issue.

When a job is set to lazy open, and it is closed whilst still pending node assignment, then we should still see the audit messages to explain job was stopped.

To replicate, in UI:
1. create job with a 10gb model memory limit and `allow_lazy_open: true` (assuming you have less than 10gb available for ML)
2. start job, look at Job Messages tab and you will see that the job and datafeed are awaiting node assignment. The job status is `opening` and the datafeed status is `starting`
3. stop the job

Refresh the Job messages tab by moving to a different tab and returning.
There are no messages. The following would be expected from an open/started job.

![image](https://user-images.githubusercontent.com/4185750/79858566-887f5c00-83c7-11ea-9800-f9d5df9cd364.png)

**Comment by droberts195** [comment] 2020-04-21 11:27
I don't think this is unique to lazy open jobs, although they make it easier to reproduce on demand.  Currently if you close _any_ job while it's not assigned to a node, for example immediately after the node is was running on is killed, then the close doesn't get audited.

The same problem also applies to data frame analytics jobs.

It's basically a one line fix in each of these actions to add the auditor call for the unassigned case.

**Comment by droberts195** [comment] 2020-04-21 17:39
After investigating a bit more I think this might be a UI side problem.

I added the extra audit message indexing for unassigned jobs and now _two_ audit messages are being indexed when unassigned jobs are stopped.  But _neither_ of these is showing up in the UI.  The UI must have some extra cleverness about which messages are shown in the list.

**Comment by droberts195** [comment] 2020-04-22 09:29
Please can someone from @elastic/ml-ui look into this?  I cannot work out why the audit message is not being displayed in the UI.  It is searchable from dev console (if running as superuser) but doesn't show up in the job messages list.  Is there some extra condition that's being applied that's filtering it out, maybe because there are warnings present before the info?

**Comment by droberts195** [comment] 2020-04-22 10:59
> Please can someone from @elastic/ml-ui look into this? I cannot work out why the audit message is not being displayed in the UI.

Oh, it's just that the "Job messages" tab isn't auto-refreshed by clicking the "Refresh" link.  If I switch to the "JSON" tab, then back to "Job messages" then the extra message is there.

So I think the bug is that clicking "Refresh" while the "Job messages" tab is visible doesn't redraw the job messages table.  Shall I open a bug in the Kibana repo for that or is it already a known issue?

**Comment by sophiec20** [comment] 2020-04-22 11:05
Already a known issue, discussed with @peteharverson yesterday. Pending GH ticket.

**Comment by sophiec20** [comment] 2020-04-22 11:11
Updated title to reflect that datafeed stop audit message was missing, and not the job closing.

**Closed** 2020-04-23 12:51 UTC
Labels: :ml
