### ISSUE TITLE
Node killed after starting for sometime, JVM throws SIGSEGV

### ISSUE THREAD

**Issue by hiimdoublej** [elastic/elasticsearch#39632] opened 2019-03-04 09:08 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 
`6.6.1`

**Plugins installed**: 
`ik-analysis`, `ingest-geoip`, `ingest-user-agents`

**JVM version** (`java -version`): 
`1.8.0_191`

**OS version** (`uname -a` if on a Unix-like system): 

`Linux elk 4.15.0-1027-gcp #28-Ubuntu SMP Tue Jan 15 12:29:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`  

**Description of the problem including expected versus actual behavior**:
Yesterday out of the blue my Elasticsearch single node instance stopped responding, I didn't thought of it much, I just restarted it, it would start fine, and I can use it just like the way it's supposed to. But the instance just keeps going down after 5-15 minutes of normal usage. Spitting out logs containing `SIGSEGV` errors. Attempting to fix the issue, I did a rolling upgrade from 6.3.0 to 6.6.1 since I've got no clue might as well try to let it fix itself, but it did not. The problem persists. Then I also tried to start Elasticsearch with several different version of JDKs, namely `8u131`, `8u201`, `8u202`. But they didn't help address the situation. 

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. `sudo systemctl start elasticsearch`
 2. wait 5-15 minutes
 3. WHACK ! There's your `SIGSEGV` log and Elasticsearch was shut down.

**Provide logs (if relevant)**:
[hs_err_pid4401.log](https://github.com/elastic/elasticsearch/files/2925009/hs_err_pid4401.log)

**Comment by matriv** [comment] 2019-03-04 10:27
Hello @hiimdoublej,

It would be helpful if you could provide some more info:

- What do you mean rolling upgrade 6.3.0 -> 6.6.1. You say it's a single node cluster.
- Did you change something in the OS: configuration, packages/kernel upgrade?
- Could you provide the output of `dmesg`?
- Can you set the `ulimit -c unlimited`, restart the instance and provide the core dump once it fails again?

Some suggestions to try out:
- Is it possible to move your node to another machine (suspecting h/w failure) and try it there?
- Could you also try to run it with java 11 ?

**Comment by hiimdoublej** [comment] 2019-03-04 11:27
1. I followed [this official guide](https://www.elastic.co/guide/en/elasticsearch/reference/current/rolling-upgrades.html) to upgrade from 6.3.0 -> 6.6.1, hence I used the term 'rolling upgrade', maybe in my case just a simple 'upgrade' would do it, not trying to steer people off the wrong way here, sorry about that.
2. I did not change anything system-wise, but I did change the cpu cores (since it's a gcp machine and we're reducing the cost) and reboot.
3. I did not check `dmesg`, but now that you mentioned it, I took a look and made a [gist](https://gist.github.com/hiimdoublej/2ee657759ade9eda05b3d0f064b7fa63) with it, on line 429, it did say a volume was not mounted properly, I'll try to fix it and report back here.

**Comment by hiimdoublej** [comment] 2019-03-04 11:50
1. I fixed the volume with `fsck` , problem persists
2. I did `sudo ulimit -c unlimited` then `sudo ulimit -a` to see it's set to unlimited , finally`sudo systemctl start elasticsearch` to run ES, in 15 minutes it crashed, but the `hs_err` file says that it failed to write core dumps and core dumps have been disabled....strange
I'll try java 11 next and report back, thanks for your help.

**Comment by matriv** [comment] 2019-03-04 13:38
1. Can you attach the new failure? (cannot write core dumps)
2. Do you see any errors in the ES log file?

**Comment by hiimdoublej** [comment] 2019-03-04 14:30
1. The most recent failure is [here](https://gist.github.com/hiimdoublej/0b80441ad094483f59d5263794fdc049). I did a bit of research on `ulimit` ,I found out that in case the ES is started using systemd, I cannot simply do `ulimit -c unlimited`, I have to add `LimitCore=infinity` in my ES service file under the `[service]` directive. I'll check if core dumps are successful.
2. No, just normal startup messages in `elasticsearch.log`

**Comment by matriv** [comment] 2019-03-04 15:39
Once the node is started and before it fails:
Is the cluster in green state or Is it still recovering shards?
Is it idle or do you run operations (index/update/delete/search, etc.) ?

**Comment by matriv** [comment] 2019-03-04 18:02
Another suggestion would be to try `niofs`: https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-store.html

**Comment by hiimdoublej** [comment] 2019-03-05 01:50
I got good news, so I set ES to use  `openjdk 11.0.2` then went to bed, the problem seems to go away....for now. Let me monitor it closely for like a day to see if the problem resurfaces. I'll report back. Thank you @matriv your suggested debug methods have been very helpful and I'm grateful for that.

**Comment by jpountz** [comment] 2019-03-05 10:51
To anyone else reading this ticket, the reason why we suggested giving `niofs` a try is because it reads data from disk differently, and we speculated that what translates into a SEGV with `mmapfs` might translate into an `IOException` with `niofs` which could have given us more information about the root cause of the issue. The fact that the bug doesn't reproduce with Java 11 now suggests that Java 8 was doing something wrong that Java 11 fixed. We are unlikely to check what exactly given that the system exhibits some issues (see dmesg output) and that Java 11 appears to have addressed the issue.

I'm closing the issue now. @hiimdoublej please reopen if the problem appears again with Java 11.

**Closed by jpountz** 2019-03-05 10:51 UTC
Labels: :Core/Infra/Core

**Comment by hiimdoublej** [comment] 2019-03-05 14:45
Alright, I think it's safe to say that the problem's gone. It's been almost 24 hours since the `jdk` switch. For folks who wound up here please try `openjdk 11.0.2`
