### ISSUE TITLE
Ability to shadow value of a field with runtime fields accessing the original `doc` value

### ISSUE THREAD

**Issue by lucabelluccini** [elastic/elasticsearch#112875] opened 2024-09-13 14:42 UTC
### Description

A very useful feature of `runtime` fields is to shadow the type or patch the value of a real field.
This can save a lot of time (reindexing).

If we need to just patch the type of a field `a`, we can just define the runtime field `a` and the type we need. If it can be automatically converted, we do not even need a `script`.

If we need to patch the value of the field, we cannot do it as we prevent `Cyclic dependency`.

**Would it be possible to have a way to bypass the check or have another accessor?**

Example: Return both `system.cores` and `system.core` if the original field had `system.core` (for backward compatibility of a dashboard/application in Kibana)

```
GET metrics-system.*/_search
{
  "aggs": {
    "NAME": {
      "terms": {
        "field": "event.dataset"
      }
    }
  },
  "runtime_mappings": {
    "event.dataset": {
      "type": "keyword",
      "script": {
        "source": """
def tmp = doc['event.dataset'];
if(tmp != null) {
  if(tmp == 'system.core') {
    emit('system.cores');
  }
  emit(tmp);
}
"""
      }
    }
  }
}
```

```
          "caused_by": {
            "type": "illegal_argument_exception",
            "reason": "Cyclic dependency detected while resolving runtime fields: event.dataset -> event.dataset"
          }
```

The workaround would be to use the `params._source`, but the perfs difference would be of different orders of magnitude.

**Comment by rjernst** [comment] 2024-09-18 22:38
This is an interesting idea. How to implement it is more a question for search as the resolution happens within SearchLookup, not in the script itself.

**Comment by javanna** [comment] 2024-09-19 10:06
I believe this is a duplicate of #89093 .

**Closed by javanna** 2024-09-19 10:06 UTC
Labels: >enhancement, :Core/Infra/Scripting, Team:Core/Infra, Team:Search Foundations, :Search Foundations/Search

**Comment by lucabelluccini** [comment] 2024-09-19 12:09
100% Thanks - I didn't spot the existing issue.
