### ISSUE TITLE
integTestCluster times out in :modules:percolator

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#24185] opened 2017-04-19 13:08 UTC
failure trace ([source](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/2509/consoleFull)):

```
Executing task ':modules:percolator:integTestCluster#wait' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
Node 0 output:
|-----------------------------------------
|  failure marker exists: false
|  pid file exists: true
|  http ports file exists: false
|  transport ports file exists: false
|
|  [ant output]
|
|  [log]
|    Warning: Ignoring JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
|    Please pass JVM parameters via ES_JAVA_OPTS instead
|    [2017-04-19T08:53:06,127][INFO ][o.e.n.Node               ] [node-0] initializing ...
|    [2017-04-19T08:53:06,367][INFO ][o.e.e.NodeEnvironment    ] [node-0] using [1] data paths, mounts [[/ (rootfs)]], net usable_space [424.6gb], net total_space [499.9gb], spins? [unknown], types [rootfs]
|    [2017-04-19T08:53:06,367][INFO ][o.e.e.NodeEnvironment    ] [node-0] heap size [494.9mb], compressed ordinary object pointers [true]
|    [2017-04-19T08:53:06,369][INFO ][o.e.n.Node               ] [node-0] node name [node-0], node ID [MBAcuQ0NRCOQehEG2aLrjQ]
|    [2017-04-19T08:53:06,369][INFO ][o.e.n.Node               ] [node-0] version[6.0.0-alpha1-SNAPSHOT], pid[21400], build[8758c54/2017-04-19T08:25:39.165Z], OS[Linux/3.10.0-514.10.2.el7.x86_64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_121/25.121-b13]
|    [2017-04-19T08:53:06,370][WARN ][o.e.n.Node               ] [node-0] version [6.0.0-alpha1-SNAPSHOT] is a pre-release version of Elasticsearch and is not suitable for production
|    [2017-04-19T08:53:06,893][INFO ][o.e.p.PluginsService     ] [node-0] loaded module [percolator]
|    [2017-04-19T08:53:06,893][INFO ][o.e.p.PluginsService     ] [node-0] loaded module [transport-netty4]
|    [2017-04-19T08:53:06,894][INFO ][o.e.p.PluginsService     ] [node-0] no plugins loaded
|-----------------------------------------
:modules:percolator:integTestCluster#wait FAILED
:modules:percolator:integTestCluster#wait (Thread[Daemon worker,5,main]) completed. Took 1 mins 0.035 secs.
:modules:percolator:integTestCluster#stop (Thread[Daemon worker,5,main]) started.
:modules:percolator:integTestCluster#stop
Putting task artifact state for task ':modules:percolator:integTestCluster#stop' into context took 0.0 secs.
Executing task ':modules:percolator:integTestCluster#stop' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
Shutting down external node with pid 21400
```

This looks like the node failed to start (the next log line I'd expect is `[INFO ][o.e.d.DiscoveryModule    ] [node-0] using discovery type [zen]`) and then timed out after 60 seconds (which is the currently configured timeout in `ClusterFormationTasks`).

[Full contents of the directory `/var/lib/jenkins/workspace/elastic+elasticsearch+master+periodic/modules/percolator/build`](https://github.com/elastic/elasticsearch/files/934610/modules-percolator-build.tar.gz) are attached.

**Comment by jasontedor** [comment] 2017-04-19 17:29
So it's strange that the node appears to hang on startup, yet it's still alive or sending it `SIGKILL` would have failed. I think that we should take a stack dump before killing a node in this situation so we have more insight into why it's hanging.

**Comment by rjernst** [comment] 2017-04-19 17:39
I opened #24193 so we can get jstack output when cluster startup times out.

**Comment by jasontedor** [comment] 2017-04-19 18:42
I think we should treat this as addressed by #24193, there's nothing special about startup here (no special settings or plugins or anything) just a general startup hang that we need to watch for but there's nothing to do to address without more information.

**Closed by jasontedor** 2017-04-19 18:42 UTC
Labels: build

**Comment by liuguangmin** [comment] 2017-04-20 03:21
@jasontedor 


dear jasontedor I just ask you question a moment : when I solve the problem I get another question like this 
I copy the elasticsearch executable file's modules to the elasticseach source(the gradle project) code's modules  when I run again: the below print:


[2017-04-20T11:12:51,779][INFO ][o.e.e.NodeEnvironment    ] [mdkCxIS] using [1] data paths, mounts [[Windows7_OS (C:)]], net usable_space [130.6gb], net total_space [224.2gb], spins? [unknown], types [NTFS]
[2017-04-20T11:12:51,779][INFO ][o.e.e.NodeEnvironment    ] [mdkCxIS] heap size [1.7gb], compressed ordinary object pointers [true]
[2017-04-20T11:12:51,782][INFO ][o.e.n.Node               ] node name [mdkCxIS] derived from node ID [mdkCxISESYOK28TdFhYI1A]; set [node.name] to override
[2017-04-20T11:12:51,782][INFO ][o.e.n.Node               ] version[6.0.0-alpha1-SNAPSHOT], pid[185692], build[Unknown/Unknown], OS[Windows 7/6.1/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_121/25.121-b13]
[2017-04-20T11:12:51,783][WARN ][o.e.n.Node               ] version [6.0.0-alpha1-SNAPSHOT] is a pre-release version of Elasticsearch and is not suitable for production
[2017-04-20T11:12:51,818][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: plugin [aggs-matrix-stats] is incompatible with version [6.0.0-alpha1]; was designed for version [5.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[1/:?]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[1/:?]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) ~[1/:?]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[1/:?]
	at org.elasticsearch.cli.Command.main(Command.java:88) ~[1/:?]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[1/:?]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[1/:?]
Caused by: java.lang.IllegalArgumentException: plugin [aggs-matrix-stats] is incompatible with version [6.0.0-alpha1]; was designed for version [5.3.0]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:146) ~[1/:?]
	at org.elasticsearch.plugins.PluginsService.getModuleBundles(PluginsService.java:273) ~[1/:?]
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:117) ~[1/:?]
	at org.elasticsearch.node.Node.<init>(Node.java:294) ~[1/:?]
	at org.elasticsearch.node.Node.<init>(Node.java:236) ~[1/:?]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:221) ~[1/:?]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[1/:?]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:339) ~[1/:?]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[1/:?]
	... 6 more
2017-04-20 11:12:51,826 Thread-4 ERROR Could not unregister MBeans for org.apache.logging.log4j2:type=73d16e93 java.security.AccessControlException: access denied ("javax.management.MBeanPermission" "-#-[-]" "queryNames")
	at java.security.AccessControlContext.checkPermission(Unknown Source)
	at java.security.AccessController.checkPermission(Unknown Source)
	at java.lang.SecurityManager.checkPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.queryNames(Unknown Source)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.queryNames(Unknown Source)
	at org.apache.logging.log4j.core.jmx.Server.unregisterAllMatching(Server.java:335)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:259)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:247)
	at org.apache.logging.log4j.core.LoggerContext.stop(LoggerContext.java:338)
	at org.apache.logging.log4j.core.AbstractLifeCycle.stop(AbstractLifeCycle.java:136)
	at org.apache.logging.log4j.core.config.Configurator.shutdown(Configurator.java:344)
	at org.elasticsearch.bootstrap.Bootstrap$5.run(Bootstrap.java:196)

2017-04-20 11:12:51,830 Thread-4 ERROR Could not unregister MBeans for org.apache.logging.log4j2:type=73d16e93,component=StatusLogger java.security.AccessControlException: access denied ("javax.management.MBeanPermission" "-#-[-]" "queryNames")
	at java.security.AccessControlContext.checkPermission(Unknown Source)
	at java.security.AccessController.checkPermission(Unknown Source)
	at java.lang.SecurityManager.checkPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.queryNames(Unknown Source)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.queryNames(Unknown Source)
	at org.apache.logging.log4j.core.jmx.Server.unregisterAllMatching(Server.java:335)
	at org.apache.logging.log4j.core.jmx.Server.unregisterStatusLogger(Server.java:288)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:262)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:247)
	at org.apache.logging.log4j.core.LoggerContext.stop(LoggerContext.java:338)
	at org.apache.logging.log4j.core.AbstractLifeCycle.stop(AbstractLifeCycle.java:136)
	at org.apache.logging.log4j.core.config.Configurator.shutdown(Configurator.java:344)
	at org.elasticsearch.bootstrap.Bootstrap$5.run(Bootstrap.java:196)

2017-04-20 11:12:51,831 Thread-4 ERROR Could not unregister MBeans for org.apache.logging.log4j2:type=73d16e93,component=ContextSelector java.security.AccessControlException: access denied ("javax.management.MBeanPermission" "-#-[-]" "queryNames")
	at java.security.AccessControlContext.checkPermission(Unknown Source)
	at java.security.AccessController.checkPermission(Unknown Source)
	at java.lang.SecurityManager.checkPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.queryNames(Unknown Source)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.queryNames(Unknown Source)
	at org.apache.logging.log4j.core.jmx.Server.unregisterAllMatching(Server.java:335)
	at org.apache.logging.log4j.core.jmx.Server.unregisterContextSelector(Server.java:293)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:263)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:247)
	at org.apache.logging.log4j.core.LoggerContext.stop(LoggerContext.java:338)
	at org.apache.logging.log4j.core.AbstractLifeCycle.stop(AbstractLifeCycle.java:136)
	at org.apache.logging.log4j.core.config.Configurator.shutdown(Configurator.java:344)
	at org.elasticsearch.bootstrap.Bootstrap$5.run(Bootstrap.java:196)

2017-04-20 11:12:51,833 Thread-4 ERROR Could not unregister MBeans for org.apache.logging.log4j2:type=73d16e93,component=Loggers,name=* java.security.AccessControlException: access denied ("javax.management.MBeanPermission" "-#-[-]" "queryNames")
	at java.security.AccessControlContext.checkPermission(Unknown Source)
	at java.security.AccessController.checkPermission(Unknown Source)
	at java.lang.SecurityManager.checkPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.queryNames(Unknown Source)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.queryNames(Unknown Source)
	at org.apache.logging.log4j.core.jmx.Server.unregisterAllMatching(Server.java:335)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerConfigs(Server.java:299)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:264)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:247)
	at org.apache.logging.log4j.core.LoggerContext.stop(LoggerContext.java:338)
	at org.apache.logging.log4j.core.AbstractLifeCycle.stop(AbstractLifeCycle.java:136)
	at org.apache.logging.log4j.core.config.Configurator.shutdown(Configurator.java:344)
	at org.elasticsearch.bootstrap.Bootstrap$5.run(Bootstrap.java:196)

2017-04-20 11:12:51,834 Thread-4 ERROR Could not unregister MBeans for org.apache.logging.log4j2:type=73d16e93,component=Appenders,name=* java.security.AccessControlException: access denied ("javax.management.MBeanPermission" "-#-[-]" "queryNames")
	at java.security.AccessControlContext.checkPermission(Unknown Source)
	at java.security.AccessController.checkPermission(Unknown Source)
	at java.lang.SecurityManager.checkPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.queryNames(Unknown Source)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.queryNames(Unknown Source)
	at org.apache.logging.log4j.core.jmx.Server.unregisterAllMatching(Server.java:335)
	at org.apache.logging.log4j.core.jmx.Server.unregisterAppenders(Server.java:311)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:265)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:247)
	at org.apache.logging.log4j.core.LoggerContext.stop(LoggerContext.java:338)
	at org.apache.logging.log4j.core.AbstractLifeCycle.stop(AbstractLifeCycle.java:136)
	at org.apache.logging.log4j.core.config.Configurator.shutdown(Configurator.java:344)
	at org.elasticsearch.bootstrap.Bootstrap$5.run(Bootstrap.java:196)

2017-04-20 11:12:51,836 Thread-4 ERROR Could not unregister MBeans for org.apache.logging.log4j2:type=73d16e93,component=AsyncAppenders,name=* java.security.AccessControlException: access denied ("javax.management.MBeanPermission" "-#-[-]" "queryNames")
	at java.security.AccessControlContext.checkPermission(Unknown Source)
	at java.security.AccessController.checkPermission(Unknown Source)
	at java.lang.SecurityManager.checkPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.queryNames(Unknown Source)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.queryNames(Unknown Source)
	at org.apache.logging.log4j.core.jmx.Server.unregisterAllMatching(Server.java:335)
	at org.apache.logging.log4j.core.jmx.Server.unregisterAsyncAppenders(Server.java:317)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:266)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:247)
	at org.apache.logging.log4j.core.LoggerContext.stop(LoggerContext.java:338)
	at org.apache.logging.log4j.core.AbstractLifeCycle.stop(AbstractLifeCycle.java:136)
	at org.apache.logging.log4j.core.config.Configurator.shutdown(Configurator.java:344)
	at org.elasticsearch.bootstrap.Bootstrap$5.run(Bootstrap.java:196)

2017-04-20 11:12:51,838 Thread-4 ERROR Could not unregister MBeans for org.apache.logging.log4j2:type=73d16e93,component=AsyncLoggerRingBuffer java.security.AccessControlException: access denied ("javax.management.MBeanPermission" "-#-[-]" "queryNames")
	at java.security.AccessControlContext.checkPermission(Unknown Source)
	at java.security.AccessController.checkPermission(Unknown Source)
	at java.lang.SecurityManager.checkPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.queryNames(Unknown Source)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.queryNames(Unknown Source)
	at org.apache.logging.log4j.core.jmx.Server.unregisterAllMatching(Server.java:335)
	at org.apache.logging.log4j.core.jmx.Server.unregisterAsyncLoggerRingBufferAdmins(Server.java:323)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:267)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:247)
	at org.apache.logging.log4j.core.LoggerContext.stop(LoggerContext.java:338)
	at org.apache.logging.log4j.core.AbstractLifeCycle.stop(AbstractLifeCycle.java:136)
	at org.apache.logging.log4j.core.config.Configurator.shutdown(Configurator.java:344)
	at org.elasticsearch.bootstrap.Bootstrap$5.run(Bootstrap.java:196)

2017-04-20 11:12:51,839 Thread-4 ERROR Could not unregister MBeans for org.apache.logging.log4j2:type=73d16e93,component=Loggers,name=*,subtype=RingBuffer java.security.AccessControlException: access denied ("javax.management.MBeanPermission" "-#-[-]" "queryNames")
	at java.security.AccessControlContext.checkPermission(Unknown Source)
	at java.security.AccessController.checkPermission(Unknown Source)
	at java.lang.SecurityManager.checkPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.queryNames(Unknown Source)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.queryNames(Unknown Source)
	at org.apache.logging.log4j.core.jmx.Server.unregisterAllMatching(Server.java:335)
	at org.apache.logging.log4j.core.jmx.Server.unregisterAsyncLoggerConfigRingBufferAdmins(Server.java:329)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:268)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:247)
	at org.apache.logging.log4j.core.LoggerContext.stop(LoggerContext.java:338)
	at org.apache.logging.log4j.core.AbstractLifeCycle.stop(AbstractLifeCycle.java:136)
	at org.apache.logging.log4j.core.config.Configurator.shutdown(Configurator.java:344)
	at org.elasticsearch.bootstrap.Bootstrap$5.run(Bootstrap.java:196)

=======================================
the same problem
 version[6.0.0-alpha1-SNAPSHOT], pid[185692], build[Unknown/Unknown], OS[Windows 7/6.1/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_121/25.121-b13]

**Comment by jasontedor** [comment] 2017-04-20 19:51
@liuguangmin I don't see what your question has to do with this issue, can I ask you to open a topic on the [forum](https://discuss.elastic.co)?

**Comment by liuguangmin** [comment] 2017-04-21 02:54
@jasontedor 
ok I have @jasontedor  another theme you could see ,great THX
