### ISSUE TITLE
Inconsistent result from _cat/aliases vs actual state of the indices.

### ISSUE THREAD

**Issue by AIsaac08** [elastic/elasticsearch#14982] opened 2015-11-24 19:50 UTC
This was briefly describe in this issue #14818 
When I call `GET _cat/aliases` or `GET _aliases` I got all the alias associated with an open index, if later I associated the same alias with an closed index, if I try to call the alias I get a `index_closed_exception`, even when is closed, I understand this, but, is that the desire behavior to the `GET _cat/aliases`  or `GET _aliases` endpoints (to just show the alias associated with an open index)?

P.S: I said is inconsistent because is not showing all the indices with an alias.

**Comment by clintongormley** [comment] 2015-11-28 16:55
This has been made consistent in 2.0.  Closing

**Comment by AIsaac08** [comment] 2015-11-28 17:21
You may be wrong, because I'm using ES 2.0 and I still see this issue, consider reopening or letting me know if this was solved on 2.1 exactly, thanks.

**Comment by clintongormley** [comment] 2015-11-28 17:54
@AIsaac08 I ran the reproduction shown in #14818 and as @ppf2 said, saw that it had been fixed in 2.0.  If you are seeing something different, please provide a recreation that I can run.

**Comment by clintongormley** [comment] 2015-12-19 12:32
I've just reread this issue and realised i misunderstood the initial description.  Today, the cat-aliases and GET alias/es requests only return open indices, but a search request against an alias will throw a closed-index exception.

I think it was a mistake to only show open indices in the aliases requests.  We should show all indices associated with an alias.

There has been a suggestion to remove any aliases automatically when closing an index, but I think this is not the correct behaviour.  If a user wants this, then they can simply `DELETE {index}/_alias/*` before closing the index.

**Comment by AIsaac08** [comment] 2015-12-21 15:34
I have the same thought, if a user wants to remove an alias, the user should explicitly remove the alias. I would prefer that the aliases requests should show all indices with an alias/es associated to them.

**Comment by javanna** [comment] 2016-01-13 10:41
Note that `GET alias/_alias` will return all indices, including the closed ones, while `GET _aliases` and `GET _cat/aliases` will only return the open ones. This behaviour doesn't seem to be configurable, I think we should make this consistent and return all indices in all cases.

**Comment by clintongormley** [comment] 2016-01-13 11:31
I agree with making `_cat/aliases` consistent. There is this issue (https://github.com/elastic/elasticsearch/issues/15817) for removing the `GET _aliases` API.

**Comment by javanna** [comment] 2016-01-13 11:37
I think my comment was a bit premature :) I did some more digging and it turns out that the `expand_wildcards` option can be used in all cases to control what gets returned. This is because this api allows to specify index names as well, if none are specified that is considered a wildcard expression.

I also stand corrected on what I said above, let me summarize the current behaviour:

`GET _alias/alias` returns open only indices
`GET _alias/alias?expand_wildcards?open,closed` return all indices

Unfortunately the cat api doesn't support `expand_wildcards`, not sure whether we should expose it or change it to always return all indices.

Also we may want to change the default behaviour of `_alias` and `_aliases` endpoint.

**Comment by clintongormley** [comment] 2016-01-13 11:43
Hmm OK - thanks for the update @javanna.  I think that `GET _alias` and `_cat/aliases` should both return closed indices by default (ie `expand_wildcards=open,closed`).  Perhaps `_cat/aliases` could be expanded to include an indication of whether the index is open or closed, but it probably doesn't need to support the `expand_wildcards` option.

**Closed** 2016-01-14 13:24 UTC
Labels: :Aliases, enhancement, low hanging fruit
