### ISSUE TITLE
Unable to access doc values by using expression script within nested aggregated top_hits.

### ISSUE THREAD

**Issue by bhagat95** [elastic/elasticsearch#31719] opened 2018-07-02 08:24 UTC
**Elasticsearch version**: 5.4.1

**JVM version** (`java -version`): 1.8.0_131

**OS version** (`uname -a` if on a Unix-like system): 6.1 (Windows Server)

**Description of the problem including expected versus actual behavior**:
Unable to access doc values by using expression script within nested aggregated top_hits. It works fine if I remove parent aggregation(dealers)/ change script `lang `to painless.

**Steps to reproduce**:

Index structure:
```
     {
        "_index": "stockv21",
        "_type": "stock",
        "_id": "D1422435",
        "_score": 1,
        "_source": {
          ...
           "dealerId": "D2345"
           "lattitude": 68255.9964,
           "longitude": 262151.9964
         }
        ...
     }
```

Query:
```
GET stock/_search
{
  "from": 0,
  "size": 0,
  "aggs": {
    "dealers": {
      "terms": {
          "field":"dealerId"
      },
      "aggs": {
        "stocks": {
          "top_hits": {
                 "sort": [
                      {
                         "_script": {
                            "type": "number",
                            "script": {
                               "lang": "expression",
                               "inline": "doc['longitude'].value"
                            }
                         }
                      }
                 ]
              }
          }
      }
    }
  }
```

Output:
```
{
   "error": {
      "root_cause": [
         {
            "type": "null_pointer_exception",
            "reason": null
         }
      ],
      "type": "search_phase_execution_exception",
      "reason": "all shards failed",
      "phase": "query",
      "grouped": true,
      "failed_shards": [
         {
            "shard": 0,
            "index": "stockv21",
            "node": "93Y1YbqaRVG8J3kuLnc5ow",
            "reason": {
               "type": "null_pointer_exception",
               "reason": null
            }
         }
      ]
   },
   "status": 500
}
```

**Provide logs (if relevant)**:

org.elasticsearch.transport.RemoteTransportException: [93Y1Ybq][172.16.0.11:9300][indices:data/read/search[phase/query]]
Caused by: java.lang.NullPointerException
[2018-07-02T14:50:17,461][DEBUG][o.e.a.s.TransportSearchAction] [93Y1Ybq] [stagingstockv21][2], node[93Y1YbqaRVG8J3kuLnc5ow], [P], s[STARTED], a[id=ISv9ED1-TpecavcZ_PA84g]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[stagingstock], indicesOptions=IndicesOptions[id=38, ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_alisases_to_multiple_indices=true, forbid_closed_indices=true], types=[], routing='null', preference='null', requestCache=null, scroll=null, source={
  "aggregations" : {
    "dealers" : {
      "terms" : {
        "field" : "dealerId",
        "size" : 4,
        "min_doc_count" : 1,
        "shard_min_doc_count" : 0,
        "show_term_doc_count_error" : false,
        "order" : [
          {
            "_count" : "desc"
          },
          {
            "_term" : "asc"
          }
        ]
      },
      "aggregations" : {
        "stocks" : {
          "top_hits" : {
            "from" : 0,
            "size" : 4,
            "version" : false,
            "explain" : false,
            "sort" : [
              {
                "_script" : {
                  "script" : {
                    "inline" : "doc['longitude'].value",
                    "lang" : "expression"
                  },
                  "type" : "number",
                  "order" : "asc"
                }
              }
            ]
          }
        }
      }
    }
  }
}}]
org.elasticsearch.transport.RemoteTransportException: [93Y1Ybq][172.16.0.11:9300][indices:data/read/search[phase/query]]
Caused by: java.lang.NullPointerException
[2018-07-02T14:50:17,461][DEBUG][o.e.a.s.TransportSearchAction] [93Y1Ybq] All shards failed for phase: [query]
org.elasticsearch.ElasticsearchException$1: null
	at org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:618) ~[elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:126) [elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:241) [elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.action.search.InitialSearchPhase.onShardFailure(InitialSearchPhase.java:87) [elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.action.search.InitialSearchPhase.access$100(InitialSearchPhase.java:47) [elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.action.search.InitialSearchPhase$1.onFailure(InitialSearchPhase.java:155) [elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:51) [elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1050) [elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1154) [elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1132) [elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.transport.TransportService$7.onFailure(TransportService.java:638) [elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:623) [elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39) [elasticsearch-5.4.1.jar:5.4.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
[2018-07-02T14:50:17,465][WARN ][r.suppressed             ] path: /stagingstock/_search, params: {index=stagingstock}
org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:272) [elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:130) [elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:241) [elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.action.search.InitialSearchPhase.onShardFailure(InitialSearchPhase.java:87) [elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.action.search.InitialSearchPhase.access$100(InitialSearchPhase.java:47) [elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.action.search.InitialSearchPhase$1.onFailure(InitialSearchPhase.java:155) [elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:51) [elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1050) [elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1154) [elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1132) [elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.transport.TransportService$7.onFailure(TransportService.java:638) [elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:623) [elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39) [elasticsearch-5.4.1.jar:5.4.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: org.elasticsearch.ElasticsearchException$1
	at org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:618) ~[elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.action.search.SearchPhaseExecutionException.guessRootCauses(SearchPhaseExecutionException.java:170) ~[elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.action.search.SearchPhaseExecutionException.getCause(SearchPhaseExecutionException.java:111) ~[elasticsearch-5.4.1.jar:5.4.1]
	at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:139) [log4j-core-2.8.2.jar:2.8.2]
	at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:122) [log4j-core-2.8.2.jar:2.8.2]
	at org.apache.logging.log4j.core.impl.MutableLogEvent.getThrownProxy(MutableLogEvent.java:338) [log4j-core-2.8.2.jar:2.8.2]
	at org.apache.logging.log4j.core.pattern.ExtendedThrowablePatternConverter.format(ExtendedThrowablePatternConverter.java:63) [log4j-core-2.8.2.jar:2.8.2]
	at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:38) [log4j-core-2.8.2.jar:2.8.2]
	at org.apache.logging.log4j.core.layout.PatternLayout$PatternSerializer.toSerializable(PatternLayout.java:333) [log4j-core-2.8.2.jar:2.8.2]
	at org.apache.logging.log4j.core.layout.PatternLayout.toText(PatternLayout.java:232) [log4j-core-2.8.2.jar:2.8.2]
	at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:217) [log4j-core-2.8.2.jar:2.8.2]
	at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:57) [log4j-core-2.8.2.jar:2.8.2]
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:177) [log4j-core-2.8.2.jar:2.8.2]
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:170) [log4j-core-2.8.2.jar:2.8.2]
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:161) [log4j-core-2.8.2.jar:2.8.2]
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156) [log4j-core-2.8.2.jar:2.8.2]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129) [log4j-core-2.8.2.jar:2.8.2]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120) [log4j-core-2.8.2.jar:2.8.2]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84) [log4j-core-2.8.2.jar:2.8.2]
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448) [log4j-core-2.8.2.jar:2.8.2]
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:433) [log4j-core-2.8.2.jar:2.8.2]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417) [log4j-core-2.8.2.jar:2.8.2]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:403) [log4j-core-2.8.2.jar:2.8.2]
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63) [log4j-core-2.8.2.jar:2.8.2]
	at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146) [log4j-core-2.8.2.jar:2.8.2]
	at org.apache.logging.log4j.spi.ExtendedLoggerWrapper.logMessage(ExtendedLoggerWrapper.java:217) [log4j-api-2.8.2.jar:2.8.2]
	at org.elasticsearch.common.logging.PrefixLogger.logMessage(PrefixLogger.java:67) [elasticsearch-5.4.1.jar:5.4.1]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2091) [log4j-api-2.8.2.jar:2.8.2]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:1983) [log4j-api-2.8.2.jar:2.8.2]
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1845) [log4j-api-2.8.2.jar:2.8.2]
	at org.apache.logging.log4j.spi.AbstractLogger.warn(AbstractLogger.java:2546) [log4j-api-2.8.2.jar:2.8.2]
	at org.elasticsearch.rest.BytesRestResponse.build(BytesRestResponse.java:139) [elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:101) [elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:92) [elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.rest.action.RestActionListener.onFailure(RestActionListener.java:58) [elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.action.support.TransportAction$1.onFailure(TransportAction.java:94) [elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.raisePhaseFailure(AbstractSearchAsyncAction.java:220) [elasticsearch-5.4.1.jar:5.4.1]
	... 16 more
Caused by: java.lang.NullPointerException

**Comment by rjernst** [comment] 2018-07-02 21:17
There should be a stack trace for the exception in your log file. Can you please attach that?

**Comment by bhagat95** [comment] 2018-07-03 11:56
Updated stack trace

**Comment by rjernst** [comment] 2018-07-03 17:01
@bhagat95 That does not look like a complete stacktrace (there should be stuff after `Caused by: java.lang.NullPointerException`). Additionally, it is very hard to read inline. Could you please put this in a gist and link to it here instead of pasting into the issue description?

**Comment by original-brownbear** [comment] 2018-08-07 08:34
@bhagat95 @rjernst I tried reproducing this and couldn't (at least in `master`).

**Comment by rjernst** [comment] 2018-08-13 16:13
I'm going to close this issue as there has been no update in over a month. In order to investigate further, please comment with the requested full stack trace and we can re-open.

**Closed by rjernst** 2018-08-13 16:13 UTC
Labels: :Core/Scripting
