### ISSUE TITLE
[CI] MedianAbsoluteDeviationLongAggregatorFunctionTests testSimpleFinishClose failing

### ISSUE THREAD

**Issue by kkrik-es** [elastic/elasticsearch#100797] opened 2023-10-13 06:50 UTC
https://gradle-enterprise.elastic.co/s/nx3pemdql3tgs/console-log?page=19

```
./gradlew ':x-pack:plugin:esql:compute:test' --tests "org.elasticsearch.compute.aggregation.MedianAbsoluteDeviationLongAggregatorFunctionTests.testSimpleFinishClose" -Dtests.seed=BE3FB916F9F4F807 -Dtests.locale=en-CA -Dtests.timezone=Europe/Bucharest -Druntime.java=21	
org.elasticsearch.compute.aggregation.MedianAbsoluteDeviationLongAggregatorFunctionTests > testSimpleFinishClose FAILED	
    java.lang.AssertionError: 2	
        at org.elasticsearch.compute.operator.OperatorTestCase.testSimpleFinishClose(OperatorTestCase.java:224)

...

java.lang.RuntimeException: 2 blocks have not been released	
        at org.elasticsearch.compute.data.MockBlockFactory.ensureAllBlocksAreReleased(MockBlockFactory.java:53)	
        at org.elasticsearch.compute.operator.AnyOperatorTestCase.allBreakersEmpty(AnyOperatorTestCase.java:130)

...

Caused by:	
        java.lang.RuntimeException: Block allocated from test: org.elasticsearch.compute.aggregation.MedianAbsoluteDeviationLongAggregatorFunctionTests	
            at org.elasticsearch.compute.data.MockBlockFactory.trackDetail(MockBlockFactory.java:34)	
            at org.elasticsearch.compute.data.MockBlockFactory.newLongArrayVector(MockBlockFactory.java:256)	
            at org.elasticsearch.compute.data.BlockFactory.newLongArrayVector(BlockFactory.java:244)	
            at org.elasticsearch.compute.operator.SequenceLongBlockSourceOperator.createPage(SequenceLongBlockSourceOperator.java:51)	
            at org.elasticsearch.compute.operator.AbstractBlockSourceOperator.getOutput(AbstractBlockSourceOperator.java:50)	
            at org.elasticsearch.compute.operator.CannedSourceOperator.collectPages(CannedSourceOperator.java:25)	
            at org.elasticsearch.compute.operator.OperatorTestCase.testSimpleFinishClose(OperatorTestCase.java:223)
```

**Build scan:**
https://gradle-enterprise.elastic.co/s/nx3pemdql3tgs/tests/:x-pack:plugin:esql:compute:test/org.elasticsearch.compute.aggregation.MedianAbsoluteDeviationLongAggregatorFunctionTests/testSimpleFinishClose
**Reproduction line:**
```
./gradlew ':x-pack:plugin:esql:compute:test' --tests "org.elasticsearch.compute.aggregation.MedianAbsoluteDeviationLongAggregatorFunctionTests.testSimpleFinishClose" -Dtests.seed=BE3FB916F9F4F807 -Dtests.locale=en-CA -Dtests.timezone=Europe/Bucharest -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.compute.aggregation.MedianAbsoluteDeviationLongAggregatorFunctionTests&tests.test=testSimpleFinishClose
**Failure excerpt:**
```
java.lang.AssertionError: 2

  at org.elasticsearch.compute.operator.OperatorTestCase.testSimpleFinishClose(OperatorTestCase.java:224)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by ChrisHegarty** [comment] 2023-10-19 14:48
closing as a duplicate of #100902

**Closed by ChrisHegarty** 2023-10-19 14:48 UTC
Labels: blocker, >test-failure, Team:QL, :Query Languages/ES|QL
