### ISSUE TITLE
[CI] GlobalCheckpointSyncIT.testPersistGlobalCheckpoint fails

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#84898] opened 2022-03-10 23:02 UTC
### CI Link

https://gradle-enterprise.elastic.co/s/dtflrsmg3j2xo

### Repro line

./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.index.seqno.GlobalCheckpointSyncIT.testPersistGlobalCheckpoint" -Dtests.seed=C9AFA21D6F4061B7 -Dtests.locale=zh-SG -Dtests.timezone=Africa/Accra -Druntime.java=17	

### Does it reproduce?

Didn't try

### Applicable branches

master

### Failure history

https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=all_failures&failures.failureMessage=Execution%20failed%20for%20task%20*%0A%3E%20There%20were%20failing%20tests.%20See%20the%20report%20at:%20file:///*/*/*/*/build/reports/tests/*/index.html&search.relativeStartTime=P7D&search.timeZoneId=America/Chicago

### Failure excerpt

```
  1> [2022-03-10T22:36:51,207][INFO ][o.e.i.s.GlobalCheckpointSyncIT] [testPersistGlobalCheckpoint] [GlobalCheckpointSyncIT#testPersistGlobalCheckpoint]: cleaned up after test	
  1> [2022-03-10T22:36:51,208][INFO ][o.e.i.s.GlobalCheckpointSyncIT] [testPersistGlobalCheckpoint] after test	
  2> REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.index.seqno.GlobalCheckpointSyncIT.testPersistGlobalCheckpoint" -Dtests.seed=C9AFA21D6F4061B7 -Dtests.locale=zh-SG -Dtests.timezone=Africa/Accra -Druntime.java=17	
  2> java.lang.AssertionError: 	
    Expected: <0L>	
         but: was <-1L>	
        at __randomizedtesting.SeedInfo.seed([C9AFA21D6F4061B7:A7A11E86B6B5DA71]:0)	
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)	
        at org.junit.Assert.assertThat(Assert.java:956)	
        at org.junit.Assert.assertThat(Assert.java:923)	
        at org.elasticsearch.index.seqno.GlobalCheckpointSyncIT.lambda$testPersistGlobalCheckpoint$8(GlobalCheckpointSyncIT.java:240)	
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1066)	
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1039)	
        at org.elasticsearch.index.seqno.GlobalCheckpointSyncIT.testPersistGlobalCheckpoint(GlobalCheckpointSyncIT.java:233)```

**Comment by DaveCTurner** [comment] 2022-04-26 08:12
There's been 4 failures that look like this over the past 12 months, all since February. Strangely the reported `AssertionError` is being thrown from the end of `assertBusy()` but contains no suppressed exceptions and I don't see how that can happen yet.

**Comment by kingherc** [comment] 2023-01-12 15:55
I have yet to reproduce this. I have done over 5000 iterations with `main` without an error. Considering the almost non-existent failure history, I think maybe this issue does not exist anymore and could be closed.

**Comment by pxsalehi** [comment] 2023-05-26 12:54
@DaveCTurner this is the oldest failure we have open. There hasn't been any real CI failures in the past 3 months (the 1 in the list doesn't seem related). Should we close this? Or you'd rather keep it open?
<img width="1107" alt="image" src="https://github.com/elastic/elasticsearch/assets/3340727/d6af4dfa-09b7-432a-ab9e-37badb88183c">

**Comment by DaveCTurner** [comment] 2023-05-26 12:58
Yeah let's close this, if we can't reproduce it and CI can't reproduce it then there's not really any action to take here.

**Closed by DaveCTurner** 2023-05-26 12:58 UTC
Labels: >test-failure, :Distributed/Engine, Team:Distributed
