### ISSUE TITLE
Cannot upload licenses through license ui in Kibana or through api

### ISSUE THREAD

**Issue by bhavyarm** [elastic/elasticsearch#32503] opened 2018-07-31 15:02 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 6.4.0 BC1

**Plugins installed**: default distro

**OS version** (`uname -a` if on a Unix-like system): darwin

**Description of the problem including expected versus actual behavior**: User cannot upload valid license either through license UI or using API.

Please note I tried with trial license. 

**Steps to reproduce**:
 1. Downgrade your license through license UI to basic
 2. Download the trial license through internal wiki under release builds
3. Try to upload the license through the ui or through the api - user gets invalid license message.

<img width="1440" alt="screen shot 2018-07-31 at 11 04 00 am" src="https://user-images.githubusercontent.com/7074629/43468135-3778ac3c-94b1-11e8-861b-343706542a81.png">

**Comment by jkakavas** [comment] 2018-07-31 17:53
Our debugging around this is rather limited, but this fails on https://github.com/elastic/elasticsearch/blob/648899e29453840f825095e9d26bf63ce1af34ed/x-pack/plugin/core/src/main/java/org/elasticsearch/license/LicenseVerifier.java#L65

that is, verify returns false. 

That means that the public.key we are using to verify the signature ( the one we ship in x-pack-core-{version}.jar ) is not the correct one - doesn't correspond to the private one we use for generating licenses. The files were last changed as part of https://github.com/elastic/elasticsearch/pull/30251/files.
The private key shouldn't have changed - although the binary representation of it seems different - verification pending. 
The public key should have changed - as this is now stored and shipped in plain text ( as opposed to being encrypted previously ) 
An obvious way forward is to revert to using the old keypair ( the public key still needs to be decrypted)

**Comment by tvernum** [comment] 2018-08-01 04:56
I can confirm that the `public.key` in 6.4.0 BC1 is not the same as was in 6.3.2
```
$ unzip -p x-pack-core-6.3.2.jar public.key  | md5
a87a64e0f4c73be062cf67aaa512f75c
``` 
```
$ unzip -p x-pack-core-6.4.0.jar public.key  | md5
134c185f2fbbed6583d3a5b18c4c2808
```

It appears that the 6.4.0 BC has the test public.key in it:
```
$ md5 -q x-pack/license-tools/src/test/resources/public.key
134c185f2fbbed6583d3a5b18c4c2808
```

**Comment by jkakavas** [comment] 2018-08-01 05:26
Thanks Tim. It was intended to change but not to the test one. I've synced with Jason and provided the correct key last night ,core/infra will be owning this while I'm off.

**Comment by jasontedor** [comment] 2018-08-01 19:53
This has been addressed internally.

**Closed by jasontedor** 2018-08-01 19:53 UTC
Labels: :Core/License, >bug, >regression, blocker, v6.4.0
