### ISSUE TITLE
ArrayIndexOutOfBoundsException during nested aggregation

### ISSUE THREAD

**Issue by ruke47** [elastic/elasticsearch#31040] opened 2018-06-01 21:14 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): Seen on both 6.2.2 and 6.2.4

**Plugins installed**: 
 - discovery-ec2 6.2.4
 - repository-s3 6.2.4

**JVM version** (`java -version`): 1.8.0_161

**OS version** (`uname -a` if on a Unix-like system): `Linux ip-10-4-0-82 4.4.0-1052-aws #61-Ubuntu SMP Mon Feb 12 23:05:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**: Running a query with a nested aggregation ( date histogram -> terms -> sum ) causes an ArrayIndexOutOfBoundException. Removing either the terms aggregation or the sum aggregation causes the query to succeed.

**Steps to reproduce**:
I cannot reliably reproduce. :( We run an identical aggregation for many of our customers; it fails for two. The query is always roughly: 
```
{
  "size": 0,
  "timeout": "5m",
  "query": {
    "bool": {
      "must": [
        {
          "range": {
            "timestamp": {
              "from": 1527102045865,
              "to": 1527103800000,
              "include_lower": true,
              "include_upper": false,
              "boost": 1
            }
          }
        },
        {
          "query_string": {
            "query": "_exists_:bytes AND ip_type_src:private AND NOT category:alert",
            "fields": [],
            "type": "best_fields",
            "default_operator": "and",
            "max_determinized_states": 10000,
            "enable_position_increments": true,
            "fuzziness": "AUTO",
            "fuzzy_prefix_length": 0,
            "fuzzy_max_expansions": 50,
            "phrase_slop": 0,
            "analyze_wildcard": true,
            "escape": false,
            "auto_generate_synonyms_phrase_query": true,
            "fuzzy_transpositions": true,
            "boost": 1
          }
        },
        {
          "exists": {
            "field": "bytes",
            "boost": 1
          }
        }
      ],
      "must_not": [
        {
          "term": {
            "trigger_id": {
              "value": "d30bf4d677e24f0eb44845c5bf74d4af",
              "boost": 1
            }
          }
        }
      ],
      "adjust_pure_negative": true,
      "boost": 1
    }
  },
  "aggregations": {
    "count_by_date": {
      "date_histogram": {
        "field": "timestamp",
        "interval": "1800s",
        "offset": 0,
        "order": {
          "_key": "asc"
        },
        "keyed": false,
        "min_doc_count": 1
      },
      "aggregations": {
        "group_by": {
          "terms": {
            "field": "endpoint_ip",
            "size": 10000,
            "min_doc_count": 1,
            "shard_min_doc_count": 0,
            "show_term_doc_count_error": false,
            "order": [
              {
                "_count": "desc"
              },
              {
                "_key": "asc"
              }
            ]
          },
          "aggregations": {
            "SUM": {
              "sum": {
                "field": "bytes"
              }
            }
          }
        }
      }
    }
  }
}
```
The cardinality of the `endpoint_ip` field is roughly 3000. This query has approximately 211000 total hits. The sum of the `bytes` field for all hits is `6.463672855E9`.

**Provide logs (if relevant)**:
```
[2018-06-01T19:50:21,567][DEBUG][o.e.a.s.TransportSearchAction] [prod-es6-client-0d36b4089f266564e] [my-idx-2018-05-23][0], node[rLUOTbtQQfaHYjP0rHFlBQ], [P], s[STARTED], a[id=_vWPln2UT36mIO55Aj1Hfg]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[my-idx-2018-05-21, my-idx-2018-05-22, my-idx-2018-05-23, my-idx-2018-05-24], indicesOptions=IndicesOptions[id=38, ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_aliases_to_multiple_indices=true, forbid_closed_indices=true, ignore_aliases=false], types=[], routing='null', preference='null', requestCache=null, scroll=null, maxConcurrentShardRequests=120, batchedReduceSize=512, preFilterShardSize=128, source={"size":0,"timeout":"5m","query":{"bool":{"must":[{"range":{"timestamp":{"from":1527102045865,"to":1527103800000,"include_lower":true,"include_upper":false,"boost":1.0}}},{"query_string":{"query":"_exists_:bytes AND ip_type_src:private AND NOT category:alert","fields":[],"type":"best_fields","default_operator":"and","max_determinized_states":10000,"enable_position_increments":true,"fuzziness":"AUTO","fuzzy_prefix_length":0,"fuzzy_max_expansions":50,"phrase_slop":0,"analyze_wildcard":true,"escape":false,"auto_generate_synonyms_phrase_query":true,"fuzzy_transpositions":true,"boost":1.0}},{"exists":{"field":"bytes","boost":1.0}}],"must_not":[{"term":{"trigger_id":{"value":"d30bf4d677e24f0eb44845c5bf74d4af","boost":1.0}}}],"adjust_pure_negative":true,"boost":1.0}},"aggregations":{"count_by_date":{"date_histogram":{"field":"timestamp","interval":"1800s","offset":0,"order":{"_key":"asc"},"keyed":false,"min_doc_count":1},"aggregations":{"group_by":{"terms":{"field":"endpoint_ip","size":10000,"min_doc_count":1,"shard_min_doc_count":0,"show_term_doc_count_error":false,"order":[{"_count":"desc"},{"_key":"asc"}]},"aggregations":{"SUM":{"sum":{"field":"bytes"}}}}}}}}}]
org.elasticsearch.transport.RemoteTransportException: [prod-es-data-warm-0b6f4329d85500264][10.4.1.17:9300][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper: index_out_of_bounds_exception: null
        at java.nio.Buffer.checkIndex(Buffer.java:540) ~[?:1.8.0_161]
        at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:253) ~[?:1.8.0_161]
        at org.apache.lucene.store.ByteBufferGuard.getByte(ByteBufferGuard.java:118) ~[lucene-core-7.2.1.jar:7.2.1 b2b6438b37073bee1fca40374e85bf91aa457c0b - ubuntu - 2018-01-10 00:48:43]
        at org.apache.lucene.store.ByteBufferIndexInput$SingleBufferImpl.readByte(ByteBufferIndexInput.java:385) ~[lucene-core-7.2.1.jar:7.2.1 b2b6438b37073bee1fca40374e85bf91aa457c0b - ubuntu - 2018-01-10 00:48:43]
        at org.apache.lucene.codecs.lucene70.Lucene70DocValuesProducer$10.get(Lucene70DocValuesProducer.java:599) ~[lucene-core-7.2.1.jar:7.2.1 b2b6438b37073bee1fca40374e85bf91aa457c0b - ubuntu - 2018-01-10 00:48:43]
        at org.apache.lucene.codecs.lucene70.Lucene70DocValuesProducer$22.nextValue(Lucene70DocValuesProducer.java:1271) ~[lucene-core-7.2.1.jar:7.2.1 b2b6438b37073bee1fca40374e85bf91aa457c0b - ubuntu - 2018-01-10 00:48:43]
        at org.elasticsearch.index.fielddata.FieldData$SortedDoubleCastedValues.nextValue(FieldData.java:544) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.search.aggregations.metrics.sum.SumAggregator$1.collect(SumAggregator.java:78) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.search.aggregations.bucket.BestBucketsDeferringCollector.prepareSelectedBuckets(BestBucketsDeferringCollector.java:186) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.search.aggregations.bucket.DeferringBucketCollector.replay(DeferringBucketCollector.java:44) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.search.aggregations.bucket.DeferableBucketAggregator.runDeferredCollections(DeferableBucketAggregator.java:102) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.search.aggregations.bucket.terms.GlobalOrdinalsStringTermsAggregator.buildAggregation(GlobalOrdinalsStringTermsAggregator.java:226) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.search.aggregations.AggregatorFactory$MultiBucketAggregatorWrapper.buildAggregation(AggregatorFactory.java:151) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.bucketAggregations(BucketsAggregator.java:128) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.search.aggregations.bucket.histogram.DateHistogramAggregator.buildAggregation(DateHistogramAggregator.java:134) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.search.aggregations.AggregationPhase.execute(AggregationPhase.java:130) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:113) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.indices.IndicesService.lambda$loadIntoContext$14(IndicesService.java:1133) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.indices.IndicesService.lambda$cacheShardLevelResult$15(IndicesService.java:1186) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.indices.IndicesRequestCache$Loader.load(IndicesRequestCache.java:160) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.indices.IndicesRequestCache$Loader.load(IndicesRequestCache.java:143) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.common.cache.Cache.computeIfAbsent(Cache.java:412) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.indices.IndicesRequestCache.getOrCompute(IndicesRequestCache.java:116) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.indices.IndicesService.cacheShardLevelResult(IndicesService.java:1192) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.indices.IndicesService.loadIntoContext(IndicesService.java:1132) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:305) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:340) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:316) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:312) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.search.SearchService$3.doRun(SearchService.java:1002) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:672) [elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) [elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.2.4.jar:6.2.4]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

**Comment by jimczi** [comment] 2018-06-06 08:43
This looks like a bad bug but it could also be caused by a corrupted index. Can you try to run the following command on the index named `my-idx-2018-05-23` :
````
$ java -cp <path to elasticsearch lib/lucene-core-7.2.1.jar> org.apache.lucene.index.CheckIndex -fast <path to folder containing indices/<index UUID>/<shard ID>/index>
````
The exception occurs on shard 0 of the node `rLUOTbtQQfaHYjP0rHFlBQ` so you can check this one first. Note that you need to run this on a closed index if the node is running, otherwise you can stop the node and run the command. The command will check if the files in the shard are corrupted (due to a disk issue or anything that could alter the data written in these files).

**Comment by ruke47** [comment] 2018-06-09 00:46
Sorry for the delay; I wasn't able to close a production index, so I had to restore the index from backups into an empty cluster. (I ran the aggregation on my test cluster and confirmed that I got the same exception.)

I've pasted the results of CheckIndex in [this gist](https://gist.github.com/ruke47/eeb109ac2f8b79c0661b4b0a5289efad), but it ends with `No problems were detected with this index.`

**Comment by ruke47** [comment] 2021-03-18 20:05
I am now using Elasticsearch 7.5.2, and I have not seen this error in the past several months. I am not sure at what point, specifically, it stopped.

**Comment by zwguo** [comment] 2021-03-19 09:57
@ruke47 ok, thank you.

**Comment by csoulios** [comment] 2021-04-07 14:57
@zwguo have you hit the same issue?

**Comment by not-napoleon** [comment] 2021-06-10 16:02
Closing - there are no repro steps, and it seems to be fixed on more recent versions.

**Closed by not-napoleon** 2021-06-10 16:02 UTC
Labels: :Analytics/Aggregations, >bug, Team:Analytics
