### ISSUE TITLE
ES 2.1 occasional failed engine [refresh failed] due to NullPointerException while evicting query cache.

### ISSUE THREAD

**Issue by vs-adm** [elastic/elasticsearch#15043] opened 2015-11-26 11:39 UTC
Hello all.

I am running 4-node ES cluster with logstash as data producer. Recently I've upgraded ES from 1.6 to 2.1. After upgrade recent indexs' shards are continuously being marked as failed and re-initialized. If failed shard is primary shard then indexing stucks.

One node:
```
2015-11-26_07:01:21.22958 [2015-11-26 07:01:21,229][WARN ][index.engine             ] [John Falsworth] [logstash-2015.11.26][2] failed engine [refresh failed]
2015-11-26_07:01:21.22961 java.lang.NullPointerException
2015-11-26_07:01:21.23006 [2015-11-26 07:01:21,229][WARN ][index.shard              ] [John Falsworth] [logstash-2015.11.26][2] Failed to perform scheduled engine refresh
2015-11-26_07:01:21.23008 [logstash-2015.11.26][[logstash-2015.11.26][2]] RefreshFailedEngineException[Refresh failed]; nested: NullPointerException;
2015-11-26_07:01:21.23008       at org.elasticsearch.index.engine.InternalEngine.refresh(InternalEngine.java:686)
2015-11-26_07:01:21.23008       at org.elasticsearch.index.shard.IndexShard.refresh(IndexShard.java:615)
2015-11-26_07:01:21.23009       at org.elasticsearch.index.shard.IndexShard$EngineRefresher$1.run(IndexShard.java:1255)
2015-11-26_07:01:21.23009       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2015-11-26_07:01:21.23009       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2015-11-26_07:01:21.23010       at java.lang.Thread.run(Thread.java:745)
2015-11-26_07:01:21.23010 Caused by: java.lang.NullPointerException
2015-11-26_07:01:21.23044 [2015-11-26 07:01:21,230][WARN ][indices.cluster          ] [John Falsworth] [[logstash-2015.11.26][2]] marking and sending shard failed due to [eng
ine failure, reason [refresh failed]]
2015-11-26_07:01:21.23046 java.lang.NullPointerException
2015-11-26_07:04:18.05160 [2015-11-26 07:04:18,050][WARN ][index.translog           ] [John Falsworth] [logstash-2015.11.26][2] failed to delete temp file /var/lib/elasticsea
rch/dss2es/nodes/0/indices/logstash-2015.11.26/2/translog/translog-8708119625210250383.tlog
2015-11-26_07:04:18.05162 java.nio.file.NoSuchFileException: /var/lib/elasticsearch/dss2es/nodes/0/indices/logstash-2015.11.26/2/translog/translog-8708119625210250383.tlog
2015-11-26_07:04:18.05163       at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
2015-11-26_07:04:18.05163       at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
2015-11-26_07:04:18.05163       at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
2015-11-26_07:04:18.05164       at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
2015-11-26_07:04:18.05164       at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
2015-11-26_07:04:18.05164       at java.nio.file.Files.delete(Files.java:1126)
2015-11-26_07:04:18.05165       at org.elasticsearch.index.translog.Translog.recoverFromFiles(Translog.java:324)
2015-11-26_07:04:18.05165       at org.elasticsearch.index.translog.Translog.<init>(Translog.java:166)
2015-11-26_07:04:18.05165       at org.elasticsearch.index.engine.InternalEngine.openTranslog(InternalEngine.java:209)
2015-11-26_07:04:18.05166       at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:152)
2015-11-26_07:04:18.05166       at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:25)
2015-11-26_07:04:18.05167       at org.elasticsearch.index.shard.IndexShard.newEngine(IndexShard.java:1408)
2015-11-26_07:04:18.05167       at org.elasticsearch.index.shard.IndexShard.createNewEngine(IndexShard.java:1403)
2015-11-26_07:04:18.05167       at org.elasticsearch.index.shard.IndexShard.internalPerformTranslogRecovery(IndexShard.java:906)
2015-11-26_07:04:18.05168       at org.elasticsearch.index.shard.IndexShard.performTranslogRecovery(IndexShard.java:883)
2015-11-26_07:04:18.05168       at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:245)
2015-11-26_07:04:18.05168       at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56)
2015-11-26_07:04:18.05169       at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129)
2015-11-26_07:04:18.05169       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2015-11-26_07:04:18.05169       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2015-11-26_07:04:18.05171       at java.lang.Thread.run(Thread.java:745)
```

Another node:
```
2015-11-26_07:04:16.53521 [2015-11-26 07:04:16,534][WARN ][index.engine             ] [Turner D. Century] [logstash-2015.11.26][2] failed engine [refresh failed]
2015-11-26_07:04:16.53524 java.lang.NullPointerException
2015-11-26_07:04:16.53525       at org.elasticsearch.indices.cache.query.IndicesQueryCache$1.onDocIdSetEviction(IndicesQueryCache.java:158)
2015-11-26_07:04:16.53525       at org.apache.lucene.search.LRUQueryCache.clearCoreCacheKey(LRUQueryCache.java:313)
2015-11-26_07:04:16.53525       at org.apache.lucene.search.LRUQueryCache$1.onClose(LRUQueryCache.java:276)
2015-11-26_07:04:16.53526       at org.apache.lucene.index.SegmentCoreReaders.notifyCoreClosedListeners(SegmentCoreReaders.java:168)
2015-11-26_07:04:16.53526       at org.apache.lucene.index.SegmentCoreReaders.decRef(SegmentCoreReaders.java:157)
2015-11-26_07:04:16.53526       at org.apache.lucene.index.SegmentReader.doClose(SegmentReader.java:175)
2015-11-26_07:04:16.53527       at org.apache.lucene.index.IndexReader.decRef(IndexReader.java:253)
2015-11-26_07:04:16.53527       at org.apache.lucene.index.StandardDirectoryReader.doClose(StandardDirectoryReader.java:359)
2015-11-26_07:04:16.53527       at org.apache.lucene.index.IndexReader.decRef(IndexReader.java:253)
2015-11-26_07:04:16.53528       at org.apache.lucene.index.IndexReader.close(IndexReader.java:403)
2015-11-26_07:04:16.53528       at org.apache.lucene.index.FilterDirectoryReader.doClose(FilterDirectoryReader.java:134)
2015-11-26_07:04:16.53529       at org.apache.lucene.index.IndexReader.decRef(IndexReader.java:253)
2015-11-26_07:04:16.53529       at org.apache.lucene.search.SearcherManager.decRef(SearcherManager.java:130)
2015-11-26_07:04:16.53530       at org.apache.lucene.search.SearcherManager.decRef(SearcherManager.java:58)
2015-11-26_07:04:16.53531       at org.apache.lucene.search.ReferenceManager.release(ReferenceManager.java:274)
2015-11-26_07:04:16.53531       at org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:189)
2015-11-26_07:04:16.53531       at org.apache.lucene.search.ReferenceManager.maybeRefreshBlocking(ReferenceManager.java:253)
2015-11-26_07:04:16.53532       at org.elasticsearch.index.engine.InternalEngine.refresh(InternalEngine.java:678)
2015-11-26_07:04:16.53532       at org.elasticsearch.index.shard.IndexShard.refresh(IndexShard.java:615)
2015-11-26_07:04:16.53532       at org.elasticsearch.index.shard.IndexShard$EngineRefresher$1.run(IndexShard.java:1255)
2015-11-26_07:04:16.53532       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2015-11-26_07:04:16.53533       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2015-11-26_07:04:16.53533       at java.lang.Thread.run(Thread.java:745)
```

**Comment by vs-adm** [comment] 2015-11-27 14:29
Anyone? I can handle this by moving failed shard to another node by the way.

**Comment by vs-adm** [comment] 2015-11-27 23:18
It seems like NPE is in cache eviction method which can't aquire stats counters using `stats2`

```(java)
protected void onDocIdSetEviction(Object readerCoreKey, int numEntries, long sumRamBytesUsed) {
                assert Thread.holdsLock(this);
                super.onDocIdSetEviction(readerCoreKey, numEntries, sumRamBytesUsed);
                // We can't use ShardCoreKeyMap here because its core closed
                // listener is called before the listener of the cache which
                // triggers this eviction. So instead we use use stats2 that
                // we only evict when nothing is cached anymore on the segment
                // instead of relying on close listeners
                final StatsAndCount statsAndCount = stats2.get(readerCoreKey);
                final Stats shardStats = statsAndCount.stats;
                shardStats.cacheSize -= numEntries;
                shardStats.ramBytesUsed -= sumRamBytesUsed;
                statsAndCount.count -= numEntries;
                if (statsAndCount.count == 0) {
                    stats2.remove(readerCoreKey);
                }
            }
```

What is the preferable way to fix this? Ignoring stats update if `statsAndCount` is `null` leads to incorrect statistics.

**Comment by vs-adm** [comment] 2015-11-27 23:26
Also, API call `POST /_cache/clear` episodically gives the same error

```json
{
  "_shards": {
    "total": 6830,
    "successful": 6827,
    "failed": 3,
    "failures": [
      {
        "shard": 2,
        "index": "logstash-2015.11.26",
        "status": "INTERNAL_SERVER_ERROR",
        "reason": {
          "type": "null_pointer_exception",
          "reason": null
        }
      }
    ]
  }
}
```

**Comment by clintongormley** [comment] 2015-11-28 13:41
@s1monw Is this issue fixed by https://github.com/elastic/elasticsearch/pull/15012 ?

**Comment by bleskes** [comment] 2015-11-30 15:34
@clintongormley I think this is something else, relating to evictions in the new query cache. Maybe @jpountz can take a look?

**Comment by IngaFeick** [comment] 2015-12-02 10:00
Same story here. Updated to 2.1 a couple of days ago also, and ever since we have the same error message that some temporary files could not be deleted:

```
[2015-12-02 09:31:41,802][WARN ][index.translog           ] [Bacon] [.kibana][0] failed to delete temp file /appdata/elasticsearch/data/elasticsearch/nodes/0/indices/.kibana/0/translog/translog-4247269950871871367.tlog
```
The mentioned files never exist. 
Also some of our shards are stuck in a translog state. When this first occured a couple of days ago, they would recover from it after some time, but now that's not working anymore and the number of affected shards is growing. Restarting elasticsearch does not help (anymore). The indices also cannot be closed or deleted via the http api anymore. Indexing is stuck, too.

**Comment by jpountz** [comment] 2015-12-02 10:39
@IngaFeick This warning can be safely ignored. It will be fixed in 2.1.1, see https://github.com/elastic/elasticsearch/pull/14872.

**Comment by jpountz** [comment] 2015-12-02 10:53
To be clear, only this warning that elasticsearch "failed to delete" a temp file will be fixed. The NullPointerException mentioned above is an actual bug however.

**Comment by IngaFeick** [comment] 2015-12-02 10:57
Thanks @jpountz , unfortunately we get that NPE also:
```
java.lang.NullPointerException
        at org.elasticsearch.indices.cache.query.IndicesQueryCache$1.onDocIdSetEviction(IndicesQueryCache.java:158)
        at org.apache.lucene.search.LRUQueryCache.clearCoreCacheKey(LRUQueryCache.java:313)
        at org.apache.lucene.search.LRUQueryCache$1.onClose(LRUQueryCache.java:276)
        at org.apache.lucene.index.SegmentCoreReaders.notifyCoreClosedListeners(SegmentCoreReaders.java:168)
        at org.apache.lucene.index.SegmentCoreReaders.decRef(SegmentCoreReaders.java:157)
        at org.apache.lucene.index.SegmentReader.doClose(SegmentReader.java:175)
        at org.apache.lucene.index.IndexReader.decRef(IndexReader.java:253)
        at org.apache.lucene.index.ReadersAndUpdates.dropReaders(ReadersAndUpdates.java:182)
        at org.apache.lucene.index.IndexWriter$ReaderPool.dropAll(IndexWriter.java:603)
        at org.apache.lucene.index.IndexWriter.rollbackInternal(IndexWriter.java:2075)
```

**Comment by vs-adm** [comment] 2015-12-02 10:58
As a temporary and dirty workaround I'm running `POST /cache/clear` every ten minutes in cronjob. This slows down search requests but prevents shards format failing.

**Comment by IngaFeick** [comment] 2015-12-02 11:00
@vs-adm we tried that also, to no noticable effect, but I'll give that cronjob a try to prevent additional failures. Thanks!

**Comment by jpountz** [comment] 2015-12-02 21:10
I managed to find a case in which I'm able to reproduce the above NullPointerException, see #15202. Hopefully this is the same case as this one.

**Closed** 2015-12-03 08:38 UTC
Labels: :Cache, bug, v2.1.1
