### ISSUE TITLE
[CI] Execution failed for task ':test:fixtures:gcs-fixture:composeUp'

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#51602] opened 2020-01-29 11:19 UTC
https://gradle-enterprise.elastic.co/s/mzg6lpsfambwq

Not sure what to make out of this:
```
:test:fixtures:gcs-fixture:composeUp FAILED
/bin/sh: /tmp/_MEI295aNA/libreadline.so.7: no version information available (required by /bin/sh)
Building gcs-fixture
Building gcs-fixture-third-party
/bin/sh: /tmp/_MEIJs5qzv/libreadline.so.7: no version information available (required by /bin/sh)
Creating network "f1b062e4dea8730db89ab48e7966686d_gcs-fixture__default" with the default driver
Creating f1b062e4dea8730db89ab48e7966686d_gcs-fixture__gcs-fixture-third-party_1 ... 
Creating f1b062e4dea8730db89ab48e7966686d_gcs-fixture__gcs-fixture_1             ... 
Creating f1b062e4dea8730db89ab48e7966686d_gcs-fixture__gcs-fixture_1             ... error

ERROR: for f1b062e4dea8730db89ab48e7966686d_gcs-fixture__gcs-fixture_1  Cannot start service gcs-fixture: unable to remount dir as readonly: mount tmpfs:/var/lib/docker/containers/61791de7b38100b7169eb7d15a82e085a6aeb113c4eb1bbd9893e88a15335348/mounts/secrets, flags: 0x21, data: uid=0,gid=0: device or resource busy
Creating f1b062e4dea8730db89ab48e7966686d_gcs-fixture__gcs-fixture-third-party_1 ... done

ERROR: for gcs-fixture  Cannot start service gcs-fixture: unable to remount dir as readonly: mount tmpfs:/var/lib/docker/containers/61791de7b38100b7169eb7d15a82e085a6aeb113c4eb1bbd9893e88a15335348/mounts/secrets, flags: 0x21, data: uid=0,gid=0: device or resource busy
Encountered errors while bringing up the project.
/bin/sh: /tmp/_MEIqxXDAq/libreadline.so.7: no version information available (required by /bin/sh)
Stopping f1b062e4dea8730db89ab48e7966686d_gcs-fixture__gcs-fixture-third-party_1 ... 
Stopping f1b062e4dea8730db89ab48e7966686d_gcs-fixture__gcs-fixture-third-party_1 ... done
/bin/sh: /tmp/_MEIXoZdV8/libreadline.so.7: no version information available (required by /bin/sh)
Removing f1b062e4dea8730db89ab48e7966686d_gcs-fixture__gcs-fixture-third-party_1 ... 
Removing f1b062e4dea8730db89ab48e7966686d_gcs-fixture__gcs-fixture_1             ... 
Removing f1b062e4dea8730db89ab48e7966686d_gcs-fixture__gcs-fixture_1             ... done
Removing f1b062e4dea8730db89ab48e7966686d_gcs-fixture__gcs-fixture-third-party_1 ... done
Removing network f1b062e4dea8730db89ab48e7966686d_gcs-fixture__default
```

**Comment by mark-vieira** [comment] 2020-01-31 21:49
Closing as a duplicate of https://github.com/elastic/elasticsearch/issues/48027.

**Closed by mark-vieira** 2020-01-31 21:49 UTC
Labels: :Core/Infra/Build, >test-failure
