### ISSUE TITLE
Support add dynamic field to hit doc in java expert score plugin

### ISSUE THREAD

**Issue by demonatic** [elastic/elasticsearch#62806] opened 2020-09-23 07:24 UTC
Currently painless script supports "script_field" to dynamically add field to hit doc, but it seems no way to achieve the same thing in java expert score plugin. 
Already tried:
docLookup.fields().put("k","v");
docLookup.source().put("k","v");
docLookup.source().source.put("k","v");
docLookup.doc().put("k","v");
none of these works.

**Comment by cbuescher** [comment] 2020-09-23 09:44
Hi @demonatic,

> it seems no way to achieve the same thing in java expert score plugin

Can you specify which plugin exactly you are refering to? Also it would be helpful to understand what goals you are trying to achieve and what exactly does not work as expected to see if this is a bug or enhancement request for this github repo.

**Comment by demonatic** [comment] 2020-09-23 12:26
> Hi @demonatic,
> 
> > it seems no way to achieve the same thing in java expert score plugin
> 
> Can you specify which plugin exactly you are refering to? Also it would be helpful to understand what goals you are trying to achieve and what exactly does not work as expected to see if this is a bug or enhancement request for this github repo.

I am referring to this score plugin https://github.com/elastic/elasticsearch/tree/master/plugins/examples/script-expert-scoring/src

Currently we use a different search engine in production which could dynamically insert plugin-generated-field(score plugin in our case) to doc being scored, and we have a custom score plugin that calculate our own text relevance for each field of the doc, and we insert a dynamic string field to the doc being scored to indicate which field has the best text relevance match, e.g we insert a dynamic field: "best_match_field":"fieldA" in score plugin. Our Java service rely on this field in hit docs the engine returns to do other thing, like deciding which fields should be rendered on client, since there could be many fields that match the query and we can't show all of them on devices like cell phone with limited space on screen. We are now trying to migrating to elasticsearch but find that there's no way to acheive the same thing in elasticsearch expert score Java plugin (script_field add dynamic field only on fetch sub phase and does not meet our requirement).

**Comment by rjernst** [comment] 2021-03-22 18:55
@demonatic Sorry for the slow reply here. Score scripts cannot, by design, modify a document. The accessor you use to get source intentionally cannot add or remove anything from source. It is is a read-only version (decoded on the fly) of the original source document that is stored in Lucene.

I recommend you look at [runtime fields](https://www.elastic.co/guide/en/elasticsearch/reference/master/runtime.html). This is a new feature that may satisfy your needs by allowing to compute a field at runtime, instead of trying to insert it into the document.

Since the score scripts are working as designed, I hope you don't mind that I close this issue.

**Closed by rjernst** 2021-03-22 18:55 UTC
Labels: :Core/Infra/Scripting, >enhancement, Team:Core/Infra
