### ISSUE TITLE
Make `ctx._version` immutable in update scripts

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#22829] opened 2017-01-27 10:17 UTC
Update script can access the current version of the document in question via `ctx._version`. I guess it's handy to expose it for debugging purposes and for completeness' sake.

That said the current logic allows to update it which leads to weird scenarios. For example:

```
PUT index/type/1
{
  "f": 1
}

POST index/type/1/_update
{
  "script": {
    "inline": "ctx._source.f=2; ctx._version = 5"
  }
}

GET index/type/1
```

Will totally ignore the version change and the doc version will be set to 2 (assuming first command created it).

With reindexing you can do funkier stuff:

```
POST _reindex
{
  "source": {
    "index": "index"
  },
  "dest": {
    "index": "myindex_new",
    "version_type": "external"
  },
  "script": {
    "inline": "if (ctx._source.f == 1) {ctx._version++;}",
    "lang": "painless"
  }
}
```

This script will actually cause the version field in the target index to be set to the result of the script. I think this is dangerous and we shouldn't allow it (even though it might be handy in some extreme cases).

IMO we should make `ctx._version` immutable and throw an exception if someone changes it.

**Comment by nik9000** [comment] 2017-01-27 13:21
I think we should make version immutable for `_update` because I think messing with the version doesn't make much sense relative to itself. Because there is only one index you are dealing with.

For reindex this is by design. At the time I could think of several use cases. All of them only made sense when `dest`'s `version_type` is `external`. Say you are building an index that drops a bunch of fields from the source index. You'd do that by running reindex from the source index into the destination. You'd use `"version_type" : "external"` so you can rerun this process and only change documents that have changed in the source index. This doesn't pick up deletes, but it is still useful. Anyway, if you now want to change the script and rebuild the target index then rerunning the reindex won't work because none of the versions bumped. You can make it work by bumping the version in the script. Maybe we shouldn't support that use case but that is the design.

**Comment by bleskes** [comment] 2017-01-27 13:54
> Anyway, if you now want to change the script and rebuild the target index then rerunning the reindex won't work because none of the versions bumped.

On the other side, if I understand you correctly. You can only do it once. So if you want to do again you can't. IMO reindexing from the source index to remove a field when the target index was already built before should be done by dropping the target index and building it from scratch. Mucking with versioning leads to complex setups where people need to remember what the current version delta is between source and target. Sounds like a too big of a headache.

**Comment by nik9000** [comment] 2017-02-08 16:37
> Mucking with versioning leads to complex setups where people need to remember what the current version delta is between source and target.

I agree with this part, at least. Bumping the version becomes quite complex quite quickly.

**Comment by jdconrad** [comment] 2018-03-13 19:25
This is tricky because it requires specialization of a value within a Map.

**Comment by bleskes** [comment] 2018-03-13 20:58
We can potentially enforce it by checking that the vesion is the same after
the update script was executed

**Comment by jdconrad** [comment] 2018-08-30 20:26
This is something that we will do.  We are still coming up with the best way to implement this.

**Comment by rjernst** [comment] 2019-04-26 23:06
Closing in favor of https://github.com/elastic/elasticsearch/issues/41618

**Closed by rjernst** 2019-04-26 23:06 UTC
Labels: :Core/Features/Indices APIs, :Core/Infra/Scripting, >breaking, >enhancement
