### ISSUE TITLE
IDF is negative value  in some case when cross field search

### ISSUE THREAD

**Issue by CougarsJ** [elastic/elasticsearch#66485] opened 2020-12-17 06:52 UTC
I search (cross field multi match) documents that has name and address fields. In most of documents ,the name field is null. when i check IDF(name) value ,I found n greater than N,so the IDF is an  negative value .  I think N must be the documents count that contain address or name field ,not just name field.

the es version is 7.7.1

**Comment by jimczi** [comment] 2020-12-17 11:54
Thanks for reporting @CougarsJ , the issue is already tracked in https://github.com/elastic/elasticsearch/issues/44700 so I hope you don't mind if I close this one. You can follow the progress on the linked issue.

**Closed by jimczi** 2020-12-17 11:54 UTC
