### ISSUE TITLE
Index unrecoverable after setting invalid BM25 parameter

### ISSUE THREAD

**Issue by adrianocrestani** [elastic/elasticsearch#24498] opened 2017-05-04 20:27 UTC
**Elasticsearch version**: 5.3.0

**Plugins installed**: []

**JVM version** (`java -version`): Java(TM) SE Runtime Environment (build 1.8.0_101-b13)

**OS version** (`uname -a` if on a Unix-like system): CentOS 6 - Linux esr01.nw.dev.tripadvisor.com 2.6.32-642.15.1.el6.x86_64 #1 SMP Fri Feb 24 14:31:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
After setting a BM25 similarity with invalid parameters, the index won't re-open and it also fails to re-set the parameters to something valid.

**Steps to reproduce**:
```
# create index
PUT test

# close index before changing similarity
POST test/_close

# set similarity with invalid parameters. It succeeds!
PUT test/_settings
{
    "similarity": {
      "my_bm25": {
        "type": "BM25",
        "b":    2,
        "k1": 1.2
      }
    }
}

# attempt to re-open the index. It fails complaining about invalid BM25 parameter
POST test/_open

# attempt to re-set it to valid parameters! It fails
PUT test/_settings
{
    "similarity": {
      "my_bm25": {
        "type": "BM25",
        "b":    0.7,
        "k1": 1.2
      }
    }
}
```

**Provide logs (if relevant)**:

**Comment by danielmitterdorfer** [comment] 2017-05-05 07:10
Verified on 5.3.0 and also current master. When opening the index, it fails with

```
[elasticsearch] [2017-05-05T09:07:40,073][WARN ][r.suppressed             ] path: /test/_open, params: {index=test}
[elasticsearch] org.elasticsearch.ElasticsearchException: Failed to verify index [test/9NLrpfRJSZSHK4-fwfQwPA]
[elasticsearch]         at org.elasticsearch.cluster.metadata.MetaDataIndexStateService$2.execute(MetaDataIndexStateService.java:175) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:639) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:269) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:194) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:129) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:247) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:210) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
[elasticsearch]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
[elasticsearch]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
[elasticsearch]         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[elasticsearch] Caused by: java.lang.IllegalArgumentException: illegal b value: 2.0, must be between 0 and 1
[elasticsearch]         at org.apache.lucene.search.similarities.BM25Similarity.<init>(BM25Similarity.java:55) ~[lucene-core-7.0.0-snapshot-89f6d17.jar:7.0.0-snapshot-89f6d17 89f6d170f5db176c81980d58ffe21484885eb464 - jpountz - 2017-04-13 09:46:42]
[elasticsearch]         at org.elasticsearch.index.similarity.BM25SimilarityProvider.<init>(BM25SimilarityProvider.java:52) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.index.similarity.SimilarityService.<init>(SimilarityService.java:87) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.index.IndexModule.newIndexService(IndexModule.java:366) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.indices.IndicesService.createIndexService(IndicesService.java:441) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.indices.IndicesService.verifyIndexMetadata(IndicesService.java:485) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.cluster.metadata.MetaDataIndexStateService$2.execute(MetaDataIndexStateService.java:173) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
[elasticsearch]         ... 13 more
```

**Comment by jimczi** [comment] 2017-05-05 07:13
Thanks for the report @adrianocrestani 
This is a duplicate of https://github.com/elastic/elasticsearch/issues/23787 that should be fixed with 
https://github.com/elastic/elasticsearch/pull/24487

**Closed by jimczi** 2017-05-05 07:13 UTC
Labels: :Settings, adoptme, bug
