### ISSUE TITLE
Support KQL with Query String Queries

### ISSUE THREAD

**Issue by ljak** [elastic/elasticsearch#56391] opened 2020-05-07 20:11 UTC
[Query String Query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#query-string-nested) make it really easy to write queries, without the DSL. It seems really close to the [Lucene Query Syntax](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html).

On the side, Kibana started, from the Lucene Query Syntax, its own query syntax called Kibana Query Language (KQL) : https://www.elastic.co/guide/en/kibana/current/kuery-query.html . Very similar to the Lucene Query Syntay, they recently added support for Nested Fields : https://www.elastic.co/guide/en/kibana/current/kuery-query.html#kuery-query-nested-field and https://github.com/elastic/kibana/pull/47070

My request : could it be possible to have an ES query type (similar to the Query String query - maybe improves that one) to parse the KQL ? That new query string type will support natively nested fields ! Thanks.

**Comment by Truth1984** [comment] 2021-02-07 09:50
+1

Currently using `elasticsearch` npm

**Comment by qpointsystems** [comment] 2022-01-18 19:42
+1 This is exactly what I'm looking for also.  I've even attempted to get kbn-es-query out of @elastic/kibana so I could use it as is to 'parse' my query which works peachy in Discover.  

Nesting source is magical for the data I'm working with. It'd be equally magical if I had an obvious way (like Discover does) to work with a search like this: **branchOrganizers.leafOrganizers.fieldList:{ CWPersonName.familyName: Erdman }**

**Comment by javanna** [comment] 2022-10-13 10:01
Closing as duplicate of #16551.

**Closed by javanna** 2022-10-13 10:01 UTC
Labels: >enhancement, :Search/Search, Team:Search
