### ISSUE TITLE
Null pointer exception in Aggregation Code Path

### ISSUE THREAD

**Issue by rkalhans** [elastic/elasticsearch#16624] opened 2016-02-12 06:43 UTC
In ValuesSourceAggregatorFactory.java note the following code 

```
  @Override
    public void doValidate() {
        if (config == null || !config.valid()) {
            resolveValuesSourceConfigFromAncestors(name, parent, config.valueSourceType());
        }
    }
```

When this method is called with config = null this throws null pointer exception. I am hitting this issue while writing a plugin where I am extending the Aggregator.

**Comment by colings86** [comment] 2016-03-22 15:42
@rkalhans The functionality for resolving the config of an aggregation from its ancestors has been removed in 5.0 so this should not be an issue from 5.0 onwards. The reason it has been removed is that it is error prone and trappy since it can be hard to tell which ancestor will provide the config for an aggregation.

As far as fixing this in 2.x I'm not sure there is a lot we could do short of throwing a better exception if `config` is `null`. The problem is that we need to know what type of value source to look for in an ancestor and we can only know that if the config is not `null`. All of the built in aggregations will not have a `null` config, in the case that a field is not mapped on a shard, the config object is still built but `config.valid()` returns `false`. Without knowing what you are trying to do it is hard to provide a workaround for you but `ValuesSourceAggregatorFactory.resolveConfig()` should ensure that the `config` object is created, this is usually called in the `init()` method.

**Comment by clintongormley** [comment] 2016-03-25 14:52
thanks @colings86 - closing

**Closed by clintongormley** 2016-03-25 14:52 UTC
Labels: :Aggregations, bug, discuss
