### ISSUE TITLE
Distributed Search issue 

### ISSUE THREAD

**Issue by diegossilveira** [elastic/elasticsearch#13250] opened 2015-09-01 16:32 UTC
When using a Scripted Metric Aggregation, we're facing some weird result inconsistencies:

The `init_script`:
```groovy
_agg['success'] = [];
_agg['error'] = [];
_agg['tolerated'] = [];
_agg['ignored'] = [];
``` 

The `map_script`:
```groovy
tags = doc['tags'].values

if(tags.contains('_gw-successful') || tags.contains('_gw-informational')) {
	return _agg.success.add(1)
}
if(tags.contains('_gw-client-error') || tags.contains('_gw-server-error')) {
	return _agg.error.add(1)
}
if(tags.contains('_gw-unauthorized-origin')) {
	return _agg.ignored.add(1)
}

return _agg.tolerated.add(1)
```

The `combine_script`:
```groovy
 _combine = {}

 _combine['error'] = 0
for (t in _agg.error) {
	_combine['error'] += t
}

_combine['success'] = 0
for (t in _agg.success) {
	_combine['success'] += t
}

_combine['tolerated'] = 0
for (t in _agg.tolerated) {
	_combine['tolerated'] += t
}

return _combine
```

The `reduce_script`:
```groovy
error = 0
for (a in _aggs['error']) {
 error += a
}
success = 0
for (a in _aggs['success']) {
	success += a
}
tolerated = 0
for (a in _aggs['tolerated']) {
	tolerated += a
}
total = success + error + tolerated
return total > 0 ? (success + tolerated/2)/total : 1
```

The `query`:
```json
{
    "query": {
        "bool": {
            "must": [
                {
                    "range": {
                        "@timestamp": {
                            "gte": "now-5h"
                        }
                    }
                },
                {
                    "match": {
                        "_entrypoint.id": 6
                    }
                }
            ]
        }
    },
    "aggs": {
        "resourcesScore": {
            "filters": {
                "filters": {
                    "81": {
                        "term": {
                            "_resource.id": 81
                        }
                    },
                    "83": {
                        "term": {
                            "_resource.id": 83
                        }
                    }
                }
            },
            "aggs": {
                "apdexScore": {
                    "scripted_metric": {
                        "init_script_file": "init_script",
                        "map_script_file": "map_script",
                        "combine_script_file": "combine_script",
                        "reduce_script_file": "reduce_script"
                    }
                },
                "responseTime": {
                    "percentiles": {
                        "field": "entries.entrypoint.time",
                        "percents": [
                            10,
                            80
                        ]
                    }
                }
            }
        }
    }
}
```

This `query` sometimes give us aleatory failures like this:

```json
{
    "took": 9,
    "timed_out": false,
    "_shards": {
        "total": 5,
        "successful": 3,
        "failed": 2,
        "failures": [
            {
                "index": "events-gateway-29-20150901",
                "shard": 0,
                "status": 500,
                "reason": "RemoteTransportException[[Shellshock][inet[/192.168.12.37:9300]][indices:data/read/search[phase/query]]]; nested: IOException[Can't write type [class b033d26c7c699de2870d36961a0ba8fc886a1963$_run_closure1]]; "
            },
            {
                "index": "events-gateway-29-20150901",
                "shard": 2,
                "status": 500,
                "reason": "RemoteTransportException[[Asp][inet[/192.168.12.245:9300]][indices:data/read/search[phase/query]]]; nested: IOException[Can't write type [class b033d26c7c699de2870d36961a0ba8fc886a1963$_run_closure1]]; "
            }
        ]
    },
    "hits": {
        "total": 14,
        "max_score": 0,
        "hits": []
    },
    "aggregations": {
        "resourcesScore": {
            "buckets": {
                "81": {
                    "doc_count": 14,
                    "responseTime": {
                        "values": {
                            "10.0": 17.2,
                            "80.0": 43.6
                        }
                    },
                    "apdexScore": {
                        "value": "0.0357142857"
                    }
                },
                "83": {
                    "doc_count": 0,
                    "responseTime": {
                        "values": {
                            "10.0": "NaN",
                            "80.0": "NaN"
                        }
                    },
                    "apdexScore": {
                        "value": 1
                    }
                }
            }
        }
    }
}
``` 

Is there something we're missing or is that a issue with Elasticsearch?

**Comment by felipegs** [comment] 2015-09-01 17:07
we are using elasticsearch 1.7.1

**Comment by clintongormley** [comment] 2015-09-01 17:13
@colings86 could you take a look at this please?

**Comment by colings86** [comment] 2015-09-02 10:13
@felipegs I'm going to try and reproduce this to see what might be going on buy in the mean time would you be able to do the following:

* Confirm that the same errors happen when the `responseTime` agg is removed? (I expect it to be the case but asking for completeness
* Confirm whether the errors occur when the `filters` aggregation is removed and the `scripted_metric` aggregation is run on its own?
* Confirm which of the scripts the error is occurring in by removing the reduce script and seeing if the errors occur and then removing the combine script as well and seeing if the errors occur?
* Confirm if the failing shards are always shards 0 and 2 of `events-gateway-29-20150901` or if the shards change each time?
* Confirm if the errors only occur on that index (`events-gateway-29-20150901`) or if they occur on other indices too?

Thanks

**Comment by colings86** [comment] 2015-09-02 10:48
I have managed to reproduce the issue using the steps in this gist: https://gist.github.com/colings86/0ee1159ee113e4992457

This is done on a 2-node cluster running version 1.7.1.

It seems that for me the error consistently occurs and it always on the same 2 shards.

I have a look into what is causing this now

**Comment by colings86** [comment] 2015-09-02 11:03
So the problem seems to be with the way you are initialising `_combine` in the `combine_script`. To initialise an empty map you should use `_combine = [:]` and then populate that map as you are currently (see http://www.groovy-lang.org/groovy-dev-kit.html#Collections-Maps for more details). By using `{}` i think (I'm not an expert in groovy) you are creating a new object type in groovy which Elasticsearch will not know how to serialise. The reason you only get the error for 2 of the shards is probably because they are the non-local shards being used in the request. The local shards (the ones on the same node which received the request from the client) will not need to serialise those objects to send them back for the reduce phase.

I'm going to close this issue as the aggregation is working as expected in that the object emitted from the scripts need to be either primitive types, strings, maps of these types or an array of the types here.

**Closed by colings86** 2015-09-02 11:03 UTC
Labels: :Aggregations, discuss

**Comment by colings86** [comment] 2015-09-02 11:14
I've updated the documentation for the `scripted_metric` aggregation to be clearer on what types are valid to return from the scripts: https://github.com/elastic/elasticsearch/commit/1d9905a798e350f4a732790cb8731df8ab016059

**Comment by diegossilveira** [comment] 2015-09-02 12:56
Thank you for the reply @colings86! We will make some tests and I will let you know if we find some other problems.
