### ISSUE TITLE
Multi_match query for boolean fields is not work

### ISSUE THREAD

**Issue by vara855** [elastic/elasticsearch#32676] opened 2018-08-07 11:51 UTC
**Describe the feature**: Multi_match query for boolean fields is not work

**Elasticsearch version** : 6.2.3

**Plugins installed**: [elasticsearch-carrot2(6.2.3)]

**JVM version** (`java -version`): 1.8.0_151

**OS version** (`uname -a` if on a Unix-like system): win 10

**Description of the problem including expected versus actual behavior**: 
multi_match query for boolean index fields is not work.
If index have sample structure: 
`"_index": "index",
        "_type": "_doc",
        "_id": "1",
        "_score": 1,
        "_source": {
          "my": {
            "boolean": true,
            "text": "foo bar"
          }
        }
      }
`
AND query is
`GET index/_search
{
  "query": {
    "multi_match": {
      "query": true,
      "fields": [ "my.*boolean"]
    }
  }
}`

AR: request does not find docs
ER: request should find docs with field "boolean": true

**Steps to reproduce**:
 1.`DELETE index`
 2. `PUT index/_doc/1
{
  "my": {
    "boolean": true,
    "text": "foo bar"
  }
}`
 3. `GET index/_search
{
  "query": {
    "multi_match": {
      "query": true,
      "fields": [ "my.*boolean"]
    }
  }
}`

**Comment by jimczi** [comment] 2018-08-07 12:39
Closing as duplicate of https://github.com/elastic/elasticsearch/issues/31798 . Thanks for reporting @vara855

**Closed by jimczi** 2018-08-07 12:39 UTC
