### ISSUE TITLE
[feature request] limit the size of scroll search 

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#19386] opened 2016-07-12 09:12 UTC
ES 2.1
**Describe the feature**:
below query still get response:
                MatchAllQueryBuilder maq = QueryBuilders.matchAllQuery();
		SearchResponse sResponse = client.prepareSearch(indexName)
		        .setSearchType(SearchType.SCAN)
		        .setQuery(maq)
		        .setSize(20000)
		        .execute()
		        .actionGet();

better limit size for scroll search type the same way for search with max result window

**Comment by clintongormley** [comment] 2016-07-12 10:25
Duplicate of #19249 and fixed by https://github.com/elastic/elasticsearch/pull/19367

**Closed by clintongormley** 2016-07-12 10:25 UTC

**Comment by makeyang** [comment] 2016-07-12 10:29
won't backport to 2.1?

**Comment by jasontedor** [comment] 2016-07-12 15:04
> won't backport to 2.1?

Nothing will be backported to 2.1, there will be no additional releases of the 2.1.x line.
