### ISSUE TITLE
marvel: changing marvel.agent.interval to '60s' leads to 0/s rates for "Last hour"

### ISSUE THREAD

**Issue by awelzel** [elastic/elasticsearch#18947] opened 2016-06-17 16:56 UTC
Hey there,

I'm observing an issue with marvel after increasing marvel.agent.interval to '60s'.

**Elasticsearch version**: 2.3.3

**JVM version**: Java(TM) SE Runtime Environment (build 1.8.0_72-b15)

**OS version**: Ubuntu 14.04

**Description of the problem including expected versus actual behavior**: After increasing the marvel.agent.interval to '60s', the marvel overview in Kibana shows search and index rates of all zeroes when the "Last 1 hour" interval is selected. When selecting the "Last 4 hours" interval, the index and search rate show sensible values. Expected would be that "Last 1 hour" shows proper values as well.

The API returns all zeroes for the 1 hour case in the `metrics.cluster_index_latency` for the `/indices` endpoint, so it's not a display issue. `curl'ing` by hand with a 2 hour interval shows that `metrics.cluster_index_latency` is populated with sensible values.

**Steps to reproduce**:
1. Change marvel.agent.interval to '60s' in elasticsearch.yml
2. Delete all marvel indices
3. Restart elasticsearch
4. Visit marvel page after a few minutes with "Last hour" selected
5. Search and Index rate show only 0/s
6. Switch to "Last 4 hours" -> Search and Index rate look sensible

Let me know if you need more info!

Thanks,
   Arne

**Comment by tlrx** [comment] 2016-07-04 10:08
Thanks for reporting @awelzel 

I can reproduce this issue and I just pinged some people in charge of Marvel user interface /cc @tsullivan @pickypg because they might have an opinion on what's going on here.

**Comment by awelzel** [comment] 2016-10-24 23:11
Hi @tlrx,

just a quick update: I upgraded ES to 2.4.1, Kibana to 4.6.2 and I still see the "all zeroes" behavior for the 1hour interval.

Thanks,
   Arne

**Comment by pickypg** [comment] 2016-10-24 23:21
@awelzel 

The Marvel UI that came is associated with Kibana 4.6.2 did not get any fixes associated with the "unusual" shift in data collection. The reason is that there's no extra variable that goes into our calculation _yet_ to adjust based on collection size. That won't change in 5.0, but I do expect it to change in a 5.x release.

In the mean time, I think the best course is to just do exactly what you're doing. You can change the default time picker in the Advanced -> Settings screen to be `now-4h` to get the expected view without having to click anything.

**Comment by colings86** [comment] 2017-03-21 17:51
Since this is an issue relating to x-pack I have raised an issue in our internal bug tracker for X-Pack. I will close this issue here as the issue does not directly relate to Elasticsearch

**Closed by colings86** 2017-03-21 17:51 UTC
