### ISSUE TITLE
NotSerializableException java.util.Collections$UnmodifiableList when starting new node in cluster

### ISSUE THREAD

**Issue by nickminutello** [elastic/elasticsearch#14117] opened 2015-10-14 16:36 UTC
We get this stacktrace on the starting node.

```
2015-10-14 16:31:28,448 [elasticsearch[Orb][generic][T#2]] WARN  org.elasticsearch.indices.cluster - [Orb] [[ion][3]] marking and sending shard failed due to [failed recovery]
org.elasticsearch.indices.recovery.RecoveryFailedException: [ion][3]: Recovery failed from [Stature][ZK-Drkc5TNqMGL1d-xqxGA][LONW00071288][inet[/10.102.43.214:9300]]{local=false} into [Orb][_CvekKpITyip5sQuop7oNQ][LONW00071288][inet[/10.102.43.214:9301]]{local=false}
	at org.elasticsearch.indices.recovery.RecoveryTarget.doRecovery(RecoveryTarget.java:280) [elasticsearch-1.7.1.jar:na]
	at org.elasticsearch.indices.recovery.RecoveryTarget.access$700(RecoveryTarget.java:70) [elasticsearch-1.7.1.jar:na]
	at org.elasticsearch.indices.recovery.RecoveryTarget$RecoveryRunner.doRun(RecoveryTarget.java:561) [elasticsearch-1.7.1.jar:na]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36) [elasticsearch-1.7.1.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_65]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_65]
Caused by: org.elasticsearch.transport.RemoteTransportException: Failed to deserialize exception response from stream
Caused by: org.elasticsearch.transport.TransportSerializationException: Failed to deserialize exception response from stream
	at org.elasticsearch.transport.netty.MessageChannelHandler.handlerResponseError(MessageChannelHandler.java:178) ~[elasticsearch-1.7.1.jar:na]
	at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:130) ~[elasticsearch-1.7.1.jar:na]
	at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[elasticsearch-1.7.1.jar:na]
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[elasticsearch-1.7.1.jar:na]
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[elasticsearch-1.7.1.jar:na]
	at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296) ~[elasticsearch-1.7.1.jar:na]
	at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462) ~[elasticsearch-1.7.1.jar:na]
	at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443) ~[elasticsearch-1.7.1.jar:na]
	at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303) ~[elasticsearch-1.7.1.jar:na]
	at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[elasticsearch-1.7.1.jar:na]
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[elasticsearch-1.7.1.jar:na]
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) ~[elasticsearch-1.7.1.jar:na]
	at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268) ~[elasticsearch-1.7.1.jar:na]
	at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255) ~[elasticsearch-1.7.1.jar:na]
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) ~[elasticsearch-1.7.1.jar:na]
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) ~[elasticsearch-1.7.1.jar:na]
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) ~[elasticsearch-1.7.1.jar:na]
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) ~[elasticsearch-1.7.1.jar:na]
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) ~[elasticsearch-1.7.1.jar:na]
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[elasticsearch-1.7.1.jar:na]
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) ~[elasticsearch-1.7.1.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_65]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_65]
Caused by: java.io.NotSerializableException: java.util.Collections$UnmodifiableList
	at org.elasticsearch.common.io.ThrowableObjectInputStream.verify(ThrowableObjectInputStream.java:139) ~[elasticsearch-1.7.1.jar:na]
	at org.elasticsearch.common.io.ThrowableObjectInputStream.readClassDescriptor(ThrowableObjectInputStream.java:74) ~[elasticsearch-1.7.1.jar:na]
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1601) ~[na:1.7.0_65]
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517) ~[na:1.7.0_65]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771) ~[na:1.7.0_65]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350) ~[na:1.7.0_65]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990) ~[na:1.7.0_65]
	at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:500) ~[na:1.7.0_65]
	at java.lang.Throwable.readObject(Throwable.java:914) ~[na:1.7.0_65]
	at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_65]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_65]
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017) ~[na:1.7.0_65]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1893) ~[na:1.7.0_65]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798) ~[na:1.7.0_65]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350) ~[na:1.7.0_65]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990) ~[na:1.7.0_65]
	at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:500) ~[na:1.7.0_65]
	at java.lang.Throwable.readObject(Throwable.java:914) ~[na:1.7.0_65]
	at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_65]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_65]
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017) ~[na:1.7.0_65]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1893) ~[na:1.7.0_65]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798) ~[na:1.7.0_65]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350) ~[na:1.7.0_65]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370) ~[na:1.7.0_65]
	at org.elasticsearch.transport.netty.MessageChannelHandler.handlerResponseError(MessageChannelHandler.java:176) ~[elasticsearch-1.7.1.jar:na]
	... 23 common frames omitted

```

It appears that we get two instances of the same Package object (java.util) so the logic here fails:

```java
        if (aClass.isPrimitive() // primitives are fine
                || aClass.isArray() // arrays are ok too
                || Throwable.class.isAssignableFrom(aClass)// exceptions are fine
                || CLASS_WHITELIST.contains(aClass) // whitelist JDK stuff we need
                || PKG_WHITELIST.contains(aClass.getPackage())
                || pkg.getName().startsWith("org.elasticsearch")) { // es classes are ok
            return streamClass;
        }
        throw new NotSerializableException(aClass.getName());

```

The PKG_WHITELIST.contains() relies on the equals implementation for Package - which is based on identity. The same is true for the CLASS_WHITELIST .... Perhaps we should be using the class or package names (ie list of String) ?

**Comment by nik9000** [comment] 2015-10-14 16:44
@nickminutello can you tell us which version this is?

**Comment by jasontedor** [comment] 2015-10-14 16:45
@nik9000 It's visible in `elasticsearch-1.7.1.jar:na` in the stack trace.

**Comment by nickminutello** [comment] 2015-10-14 22:47
Sorry. Yes 1.7.1

**Comment by clintongormley** [comment] 2015-10-15 13:18
@nickminutello Is this with a custom plugin that uses its own exceptions?

**Comment by nik9000** [comment] 2015-10-15 13:37
> Sorry. Yes 1.7.1

Thanks! Sorry. I should have seen it in the stack trace. I'll try and remember to look there next time. Thanks for filing the whole stack trace, btw.

> @nickminutello Is this with a custom plugin that uses its own exceptions?

I don't think so - if I had to guess I'd say its just an exception we didn't test well. IIRC in 2.0 exception passing is done differently so the unserializable exception is probably exclusive to 1.7.

Im' not 100% sure on the root cause. I guess it could be a jar hell thing - I've not looked into the full story of equals and hashcode for package and class objects but if it was easy to do we'd have seen it in testing or production somewhere else. 

So I'm not sure. What does the environment look like where you run this? Do you modify the white and black lists? If so, what do you have them set to?

**Comment by nickminutello** [comment] 2015-10-20 07:40
No. No custom plugins.
Not sure of the root cause of the issue either.
A possibility is perhaps two different cluster members running on different version jvms?

But a static analysis of the code would suggest its not going to work as expected? (or am I missing something).

**Comment by jasontedor** [comment] 2015-10-21 15:53
Unfortunately, it is possible for different versions of the JVM to cause serialization issues in the transport layer (addressed in #11910). The most common cause that we've seen is due to changes in 6u45 and 7u21 for the serialization of [`java.net.InetAddress`](https://bugzilla.redhat.com/show_bug.cgi?id=952657). I see that the machine this exception occurred on was running 7u65; are you running any machines in your cluster on a version of the JVM prior to 7u21? That said, the exception message that you present here is slightly different than what we normally see when the differences in serialization lead to issues.

**Comment by nickminutello** [comment] 2015-10-30 17:52
The issue occurs when one node JVM is 1.8 and the other is 1.7 (see above).

However, is it the case that this is just exposing the _actual_ bug (relying on Object.equals()) above?

**Comment by jasontedor** [comment] 2015-10-30 18:50
Is it possible for you to either take the 1.7 system to 1.8 or the 1.8 system to 1.7 and see if the issue reproduces? This still feels like a cross JVM version serialization issue to me. Mixing minor version is generally okay (not 100%, e.g., 6u45 and 7u21) but crossing major versions seems ripe for trouble.

**Comment by nickminutello** [comment] 2015-11-04 13:36
Running both on 1.8 reproduces this bug, so the JVM mismatch is a bit of a red herring.

**Comment by nickminutello** [comment] 2015-11-04 13:44
The root cause exception is:
```
org.elasticsearch.indices.recovery.DelayRecoveryException: source node does not have the shard listed in its state as allocated on the node
	at org.elasticsearch.indices.recovery.RecoverySource.recover(RecoverySource.java:108)
	at org.elasticsearch.indices.recovery.RecoverySource.access$200(RecoverySource.java:49)
	at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:146)
	at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:132)
	at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:279)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
But I can see now that the bug that is the subject of this issue is not actually in elastic - but in commons-io?

Fundamentally, the **private ObjectStreamClass verify(ObjectStreamClass streamClass)** is broken.
The CLASS_WHITELIST.contains(aClass) and PKG_WHITELIST.contains(aClass.getPackage()) is unlikely to work.

**Comment by clintongormley** [comment] 2016-01-29 14:15
@jasontedor @nickminutello anything more on this bug?  Haven't heard reports of this elsewhere, and 2.0 doesn't use java serialization, so I'm tempted to close this?

**Closed** 2016-01-30 16:18 UTC
Labels: :Exceptions, discuss, v1.7.1
