### ISSUE TITLE
Support intervals query with Fast Vector Highlighter

### ISSUE THREAD

**Issue by ZeusFSX** [elastic/elasticsearch#65729] opened 2020-12-02 11:35 UTC
I have a document, for example: 
```
{
    "text": "Index Down Jones",
    "title": "Index Down Jones"
}
```

And my mapping for text and title the same:
```
  "mappings": {
    "properties": {
      "text": {
        "type": "text",
        "analyzer": "my_analyzer",
        "term_vector": "with_positions_offsets",
        "fields": {
          "exact": {
            "type": "text",
            "term_vector": "with_positions_offsets",
            "analyzer": "default"
          },
          "keyword": {
            "type": "keyword",
            "ignore_above": 256
          }
        }
      }
```
My query:
```
{
    "query": {
        "bool": {
            "should": [
                {
                    "intervals": {
                        "text": {
                            "all_of": {
                                "intervals": [
                                    {
                                        "match": {
                                            "query": "Down"
                                           }
                                    },
                                    {
                                        "match": {
                                            "analyzer": "default",
                                            "max_gaps": 0,
                                            "query": "Jones",
                                            "use_field": "text.exact"
                                        }
                                    }
                                ],
                                "max_gaps": 0,
                                "ordered": False}
                        }
                    }
                },
                {
                    "intervals": {
                        "title": {
                            "all_of": {
                                "intervals": [
                                    {
                                        "match": {
                                            "query": "Down"
                                         }
                                     },
                                    {
                                        "match": {
                                            "analyzer": "default",
                                            "max_gaps": 0,
                                            "query": "Jones",
                                            "use_field": "title.exact"
                                        }
                                    }
                                ],
                                "max_gaps": 0,
                                "ordered": False
                            }
                        }
                    }
                }
            ]
        }
    },
    "highlight": {
        "number_of_fragments": 0,
        "post_tags": ["</em>"],
        "pre_tags": ["<em>"]},
        "fields": {
            "text": {
                "matched_fields": ["text", "text.exact"],
                "type": "fvh"
            },
            "title": {
                "matched_fields": ["title", "title.exact"],
                "type": "fvh"
            }
        }
}
```
Can you add support to fast vector highlighter when use intervals query?
By the way, when I use __unified__ highlighter elasticsearch highlights fields separately:
```
"highlight": {
    "text.exact": ["Index Down <em>Jones</em>"],
    "title.exact": ["Index Down <em>Jones</em>"],
    "text": ["Index <em>Down</em> Jones"],
    "title": ["Index <em>Down</em> Jones"]
}
```

**Comment by jimczi** [comment] 2020-12-18 11:26
The Fast vector highlighter is in maintenance mode so all developments are now made on the `unified` highlighter.
There are no more activities in Lucene for this highlighter as well so the chance that intervals are handled by this old highlighter are very small. For this reason  I hope you don't mind if I close this issue, if something is missing or not working with the  `unified` highlighter please open a new one.

**Closed by jimczi** 2020-12-18 11:26 UTC
Labels: :Search/Search, >enhancement

**Comment by ZeusFSX** [comment] 2020-12-18 12:32
@jimczi Do you have any advice for highlight,  how to merge two fields into one: ```text``` and ```text.exact``` using ```unified``` highlighter?

**Comment by jimczi** [comment] 2020-12-18 12:53
That's tracked in https://github.com/elastic/elasticsearch/issues/5172 @ZeusFSX . The fact that the issue is still opened is a good indicator that we want to implement it, however this is a high hanging fruit and we never had the time, due to other prioritization, to address it properly. I am afraid that this will not change in the near future but we'll get to it eventually. The linked issue also provides some workaround in the meantime.

**Comment by ZeusFSX** [comment] 2020-12-18 13:01
@jimczi Thanks)))
