### ISSUE TITLE
testNotifyOnDisconnectInSniffer fails (very occasionally)

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#52213] opened 2020-02-11 15:27 UTC
This build failed:

https://gradle-enterprise.elastic.co/s/vf7pp6fchoh5w/console-log?task=:server:integTest

```

org.elasticsearch.client.transport.NodeDisconnectIT > testNotifyOnDisconnectInSniffer FAILED |  
-- | --
  | java.lang.AssertionError: expected:<1> but was:<0> |  
  | at __randomizedtesting.SeedInfo.seed([A37722C9900F7688:2A4BE9BB222164B6]:0) |  
  | at org.junit.Assert.fail(Assert.java:88) |  
  | at org.junit.Assert.failNotEquals(Assert.java:834) |  
  | at org.junit.Assert.assertEquals(Assert.java:645) |  
  | at org.junit.Assert.assertEquals(Assert.java:631) |  
  | at org.elasticsearch.client.transport.NodeDisconnectIT.testNotifyOnDisconnectInSniffer(NodeDisconnectIT.java:78) |  
  | REPRODUCE WITH: ./gradlew ':server:integTest' --tests "org.elasticsearch.client.transport.NodeDisconnectIT.testNotifyOnDisconnectInSniffer" -Dtests.seed=A37722C9900F7688 -Dtests.security.manager=true -Dtests.locale=bg -Dtests.timezone=Etc/GMT+0 -Dcompiler.java=13
```

It does not reproduce for me.

I see a few other failures of this test in the past, but it's very infrequent.

Notable mention for this strange exception in the log:

```

1> [2020-02-11T14:56:54,260][INFO ][o.e.c.s.ClusterApplierService] [node_t1] removed {{node_t0}{TUWuLZ62QQO-StG8hmnAEw}{202HRPTnT-O6K6DYk_I97w}{127.0.0.1}{127.0.0.1:43096}{dim}}, term: 1, version: 10, reason: Publication{term=1, version=10}
--
1> [2020-02-11T14:56:54,281][INFO ][o.e.c.t.TransportClientNodesService] [testNotifyOnDisconnectInSniffer] failed to get node info for {#transport#-1}{mCenUNDbQSe0Xtd6HXghVQ}{127.0.0.1}{127.0.0.1:43096}, disconnecting... |  
-- | --
  | 1> org.elasticsearch.transport.RemoteTransportException: [_client_][127.0.0.1:43096][cluster:monitor/nodes/liveness] |  
  | 1> Caused by: org.elasticsearch.transport.ActionNotFoundTransportException: No handler for action [cluster:monitor/nodes/liveness] |  
  | 1> 	at org.elasticsearch.transport.InboundHandler.handleRequest(InboundHandler.java:167) ~[main/:?] |  
  | 1> 	at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:119) ~[main/:?] |  
  | 1> 	at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:103) ~[main/:?] |  
  | 1> 	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:676) ~[main/:?] |  
  | 1> 	at org.elasticsearch.transport.TcpTransport.consumeNetworkReads(TcpTransport.java:700) ~[main/:?] |  
  | 1> 	at org.elasticsearch.transport.nio.MockNioTransport$MockTcpReadWriteHandler.consumeReads(MockNioTransport.java:276) ~[framework-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:228) ~[elasticsearch-nio-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.nio.BytesChannelContext.read(BytesChannelContext.java:40) ~[elasticsearch-nio-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.nio.EventHandler.handleRead(EventHandler.java:139) ~[elasticsearch-nio-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.transport.nio.TestEventHandler.handleRead(TestEventHandler.java:151) ~[framework-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.nio.NioSelector.handleRead(NioSelector.java:420) ~[elasticsearch-nio-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:246) ~[elasticsearch-nio-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:174) ~[elasticsearch-nio-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:131) ~[elasticsearch-nio-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT] |  
  | 1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
```

Maybe it was a port collision (`43096` was the publish port for one of the nodes, but now seems to belong to the `_client_`??) or maybe it's unrelated. It doesn't appear in the previous time this test failed.

**Comment by davidkyle** [comment] 2020-02-11 15:38
Closing as duplicate of #52215

**Closed by davidkyle** 2020-02-11 15:38 UTC
Labels: :Distributed/Network, >test-failure
