### ISSUE TITLE
Query String Query no way to escape spaces in version 2.3.5 and 2.4.0, but not on 5.0

### ISSUE THREAD

**Issue by jasw** [elastic/elasticsearch#24082] opened 2017-04-13 07:13 UTC
**Elasticsearch 2.3.5 and 2.4.0**:

**Plugins installed**: []

**1.8.0_74-b02**:

**32~14.04.1-Ubuntu**:

**Query String Query escaping spaces do not work**:

**Steps to reproduce**:

1. start elastic search 2.3.5 or 2.4.0
2. create index 'my_index' and a type 'city' with normal string mapping and a raw 'not_analyzed' mapping
```
curl -XPUT 'localhost:9200/my_index?pretty' -H 'Content-Type: application/json' -d'
{
  "mappings": {
    "my_type": {
      "properties": {
        "city": {
          "type": "string",
          "fields": {
            "raw": { 
              "type":  "string",
              "index": "not_analyzed"
            }
          }
        }
      }
    }
  }
}

```
3. add two documents with city='A B C Cleaning' and city='Cleaning' 

```
curl -XPUT 'localhost:9200/my_index/my_type/1?pretty' -H 'Content-Type: application/json' -d'
{
  "city": "A B C Cleaning"
}
'
curl -XPUT 'localhost:9200/my_index/my_type/2?pretty' -H 'Content-Type: application/json' -d'
{
  "city": "Cleaning"
}
'


```

4. Run query string query try to match 'A B C'

```
curl -XGET 'localhost:9200/my_index/_search?pretty' -H 'Content-Type: application/json' -d'
{
  "query": {
    "query_string": {
       "query" : "*A\\ B\\ C*",
      "fields": ["city","city.raw"]
    }
  }
}
'

```

Expected match: document 1. Result: no match.

Why is this a bug?  The behaviour above clearly does not match what the spec says:
 
> Watch this space
 A space may also be a reserved character. For instance, if you have a synonym list which converts "wi fi" to "wifi", a > query_string search for "wi fi" would fail. The query string parser would interpret your query as a search for "wi OR fi", while the token stored in your index is actually "wifi". Escaping the space will protect it from being touched by the query string parser: "wi\ fi".

Please note:

1. **The same test case ran against version 5.0 works as expected. -- matching document 1.** 
2. ***This issue has been raised and closed (wrongly, I think) a couple of days ago**. You can see it here #24035

If you have a workaround, please suggest. I have been stuck at this for quite some days now. 

Thanks,
Jason

**Comment by danielmitterdorfer** [comment] 2017-04-13 07:44
Hi @jasw! I just ran the reproduction scenario on a fresh install of Elasticsearch 2.4.4 and Elasticsearch 5.0.0. Both versions behave identical, so I cannot confirm your claim that Elasticsearch 5.0.0 behaves differently. Also, the query does not do what you think it does. Hence, I'll close it as it is not a bug.

However, I think I have a solution for your problem and will soon follow up on the related Discuss thread that you have created recently: https://discuss.elastic.co/t/query-string-query-escaping-spaces-in-v2-3/81254

**Closed by danielmitterdorfer** 2017-04-13 07:44 UTC

**Comment by jasw** [comment] 2017-04-13 09:11
@danielmitterdorfer  Thank you very much. Thats really insightful.   I think my question has been addressed by your suggest perfectly. However, I tried to use the 2.4 fresh installed elastic search docker (the 2.4 version points to 2.4.4) and 5.0 version (points to 5.3.0). The behaviours for the same search on the same date did give different answers. 

Note, I am very happy for this ticket to be closed as I have a better solution thanks to your suggestion. Can you please update the document on the escaping part?  I do think your explanation would help a lot of people like me. 

Here is what I have tried:


```
docker run -d -p 9200:9200 -e "http.host=0.0.0.0" -e "transport.host=127.0.0.1" -e "xpack.security.enabled=false" docker.elastic.co/elasticsearch/elasticsearch:5.3.0
```

 You can see it is running 5.3.0
```
curl -XGET 'localhost:9200/'
{
  "name" : "UYb3yL1",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "Dvhqa5W-SZ2L10MYDTmE4A",
  "version" : {
    "number" : "5.3.0",
    "build_hash" : "3adb13b",
    "build_date" : "2017-03-23T03:31:50.652Z",
    "build_snapshot" : false,
    "lucene_version" : "6.4.1"
  },
  "tagline" : "You Know, for Search"
}
```

The search returns one match:
```
curl -XGET 'localhost:9200/my_index/_search?pretty' -H 'Content-Type: application/json' -d'
{
  "query": {
    "query_string": {
       "query" : "*A\\ B\\ C\\ *",
      "fields": ["city","city.raw"]
    }
  }
}
'

{
  "took" : 31,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "my_index",
        "_type" : "my_type",
        "_id" : "1",
        "_score" : 1.0,
        "_source" : {
          "city" : "A B C Cleaning"
        }
      }
    ]
  }
}
```

Now run it on Elastic Search 2.4.4

```
 curl -XGET 'localhost:32772/my_index/_search?pretty' -H 'Content-Type: application/json' -d'
{
  "query": {
    "query_string": {
       "query" : "*A\\ B\\ C*",
      "fields": ["city","city.raw"]
    }
  }
}
'

{
  "took" : 34,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : null,
    "hits" : [ ]
  }
}
```


Data in 2.4.4 and 5.3.0 are identical (9200 ports is for 5.3.0 and 32772 is for 2.4.4):

```
curl -XGET  http://localhost:9200/my_index/_search\?pretty -d '
{
    "aggs" : {
        "genres" : {
            "terms" : { "field" : "city.raw" }
        }
    }
}'
{
  "took" : 4,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "my_index",
        "_type" : "my_type",
        "_id" : "2",
        "_score" : 1.0,
        "_source" : {
          "city" : "Cleaning"
        }
      },
      {
        "_index" : "my_index",
        "_type" : "my_type",
        "_id" : "1",
        "_score" : 1.0,
        "_source" : {
          "city" : "A B C Cleaning"
        }
      }
    ]
  },
  "aggregations" : {
    "genres" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 0,
      "buckets" : [
        {
          "key" : "A B C Cleaning",
          "doc_count" : 1
        },
        {
          "key" : "Cleaning",
          "doc_count" : 1
        }
      ]
    }
  }
}
```

```
curl -XGET  http://localhost:32772/my_index/_search\?pretty -d '
{
    "aggs" : {
        "genres" : {
            "terms" : { "field" : "city.raw" }
        }
    }
}'
{
  "took" : 480,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "my_index",
      "_type" : "my_type",
      "_id" : "2",
      "_score" : 1.0,
      "_source" : {
        "city" : "Cleaning"
      }
    }, {
      "_index" : "my_index",
      "_type" : "my_type",
      "_id" : "1",
      "_score" : 1.0,
      "_source" : {
        "city" : "A B C Cleaning"
      }
    } ]
  },
  "aggregations" : {
    "genres" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 0,
      "buckets" : [ {
        "key" : "A B C Cleaning",
        "doc_count" : 1
      }, {
        "key" : "Cleaning",
        "doc_count" : 1
      } ]
    }
  }
}
```

So they DO look like behaving differently. 

Appreciate your help Daniel!

**Comment by danielmitterdorfer** [comment] 2017-04-13 10:54
I can confirm that the behavior you describe has changed with Elasticsearch 5.1.1 but as we've both found out there your requirements are best met by a different query.

> Can you please update the document on the escaping part?

I am not sure what you mean by "escaping part"? Do you mean that we should document that double quotes need t be escaped when used within a JSON string?, i.e. this:

```
GET /my_index/_search
{
    "query": {
        "query_string": {
           "fields": ["city"],
           "query": "\"A B C\""
        }
    }
}
```
