### ISSUE TITLE
[CI] DocsClientYamlTestSuiteIT test {yaml=reference/ccr/apis/get-ccr-stats}

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#47880] opened 2019-10-10 19:03 UTC
Could not reproduce locally.

Scan:
https://gradle-enterprise.elastic.co/s/sitw4mw7yks7w/tests/jbm2x6tnwtxku-5fg27oqaedztk

Failure:
```
java.lang.AssertionError: Failure at [reference/ccr/apis/auto-follow/get-auto-follow-pattern:20]: expected [2xx] status code but api [raw[method=PUT path=_ccr/auto_follow/my_auto_follow_pattern]] returned [400 Bad Request] [{"error":{"root_cause":[{"type":"no_such_remote_cluster_exception","reason":"no such remote cluster: [remote_cluster]"....
```

**Comment by dnhatn** [comment] 2019-10-11 14:18
Duplicate of https://github.com/elastic/elasticsearch/issues/47718.

**Closed by dnhatn** 2019-10-11 14:18 UTC
Labels: :Distributed/CCR, >docs, >test-failure
