### ISSUE TITLE
Regression - JSON parsing on CentOS 7

### ISSUE THREAD

**Issue by floggle** [elastic/elasticsearch#44659] opened 2019-07-21 15:38 UTC
The following code works with ES 6.3.2 (and earlier versions) on CentoOS 7.6 and Windows.
It also works on ES 7.2.0 on Windows
```
curl -X PUT http://localhost:9200/_snapshot/my_snaps -H 'Content-Type: application/json' -d '{
	"type": "fs",
	"settings": {
		"location": "/home/elasticsearch/snapshots",
		"compress": true
	}
}'
```

However, put this code into ES 7.2.0 on Centos 7.6 and you get back:

```
{"error":{"root_cause":[{"type":"json_parse_exception","reason":"Unexpected character ('g' (code 103)): was expecting double-quote to start field name\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@26017a55; line: 2, column: 2]"}],"type":"json_parse_exception","reason":"Unexpected character ('g' (code 103)): was expecting double-quote to start field name\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@26017a55; line: 2, column: 2]"},"status":500}
```

It seems that for some reason it's now taking exception to the tab character (despite what the error message above is saying which is totally a red-herring). If I replace the tabs with spaces it works fine:

curl -X PUT http://localhost:9200/_snapshot/my_snaps -H 'Content-Type: application/json' -d '{
  "type": "fs",
  "settings": {
    "location": "/home/elasticsearch/snapshots",
    "compress": true
  }
}'

Again, the tabs version works fine on windows (via kibana).

**Comment by jasontedor** [comment] 2019-07-22 08:39
I am not able to reproduce this, using Elasticsearch 7.2.0 on CentOS 7.6.1810. I suspect an environmental issue. Can you provide a packet capture between curl and Elasticsearch (a `pcap` from `tcpdump` is sufficient), so we can see exactly what is being seen by the server?

**Comment by jasontedor** [comment] 2019-07-29 08:00
No additional feedback, closing.

**Closed by jasontedor** 2019-07-29 08:00 UTC
Labels: :Core/Infra/Core, feedback_needed
