### ISSUE TITLE
[CI] GC logging JVM flags cause failures on Java 9

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#27646] opened 2017-12-04 16:15 UTC
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+java9-periodic/1565/console

When our integration tests try to start up ES, they fail due to the `PrintGCDateStamps` flag

```
Node 0 output:
|-----------------------------------------
|  failure marker exists: true
|  pid file exists: false
|  http ports file exists: false
|  transport ports file exists: false
|
|  [ant output]
|
|  [log]
|    warning: ignoring JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
|    Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
|    Unrecognized VM option 'PrintGCDateStamps'
|    Error: Could not create the Java Virtual Machine.
|    Error: A fatal exception has occurred. Program will exit.
|-----------------------------------------
```

Relates to #27610

**Comment by droberts195** [comment] 2017-12-08 09:30
I think the change that has been made probably works for production but not for the integration tests.

The integration tests now fail with this error:

```
08:52:44 |  [log]
08:52:44 |    warning: ignoring JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
08:52:44 |    Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
08:52:44 |    [0.001s][error][logging] Error opening log file '/var/log/elasticsearch/gc.log': No such file or directory
08:52:44 |    Initialization of output 'file=/var/log/elasticsearch/gc.log' using options 'filecount=32,filesize=64m' failed.
08:52:44 |    Invalid -Xlog option '-Xlog:gc*,gc+age=trace,safepoint:file=/var/log/elasticsearch/gc.log:utctime,pid,tags:filecount=32,filesize=64m'
08:52:44 |    Error: Could not create the Java Virtual Machine.
08:52:44 |    Error: A fatal exception has occurred. Program will exit.
```

An example of this is https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+java9-periodic/4989/console

I think the problem is that the JVM is being told to log to `/var/log/elasticsearch`, but for the integration tests the rpm is installed into a sub-directory of the build directory, so the directory that actually exists is `distribution/rpm/build/cluster/integTestCluster node0/rpm-extracted/var/log/elasticsearch`.

**Comment by droberts195** [comment] 2017-12-08 09:34
This one is basically the same problem but when testing the deb rather than the rpm: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+java9-periodic/1609/console

**Comment by jasontedor** [comment] 2017-12-08 11:15
@droberts195 This is tracked in #26062 (see [comment](https://github.com/elastic/elasticsearch/issues/26062#issuecomment-350057073)). In short, the proposal in that issue is stop exploding these archives and starting Elasticsearch from them as that is not how they are intended to be used (instead, installed via a package manager and started as a service). So we need to disable these integration tests for the RPM and the Debian (we already have tests that they work in the packaging tests). I'm going to re-close this in favor of that one.

**Closed by jasontedor** 2017-12-08 11:15 UTC
Labels: :Packaging, jenkins

**Comment by jasontedor** [comment] 2017-12-08 15:37
I opened #27725.

**Comment by steelywing** [comment] 2018-02-22 08:55
I get the following error, when using OpenJDK 9, Ubuntu 16
```
[0.000s][error][logging] Invalid decorator 'utctime'.
Invalid -Xlog option '-Xlog:gc*,gc+age=trace,safepoint:file=/var/log/elasticsearch/gc.log:utctime,pid,tags:filecount=32,filesize=64m'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
