### ISSUE TITLE
Rollup search misses the pipeline aggregation result

### ISSUE THREAD

**Issue by kiju98** [elastic/elasticsearch#34390] opened 2018-10-11 08:40 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): Version: 6.4.0, Build: default/tar/595516e/2018-08-17T23:18:47.308994Z, JVM: 1.8.0_162

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_162, Java HotSpot(TM) 64-Bit Server VM, 25.162-b12, Oracle Corporation

**OS version** (`uname -a` if on a Unix-like system): Linux oss-elastic02 3.10.0-327.el7.x86_64 #1 SMP Thu Oct 29 17:29:29 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

I tried a rollup search but the pipeline aggregation result is missing.

**Steps to reproduce**:

 1. Prepare an index.
```
PUT stat
{
  "mappings": {
    "doc": {
      "properties": {
        "agent": {
          "properties": {
            "@timestamp": {
              "type": "date"
            }
          }
        },
        "cpu": {
          "properties": {
            "idle": {
              "properties": {
                "pct": {
                  "type": "float"
                }
              }
            },
            "iowait": {
              "properties": {
                "pct": {
                  "type": "float"
                }
              }
            },
            "sys": {
              "properties": {
                "pct": {
                  "type": "float"
                }
              }
            },
            "total": {
              "properties": {
                "pct": {
                  "type": "scaled_float",
                  "store": true,
                  "scaling_factor": 100
                }
              }
            },
            "user": {
              "properties": {
                "pct": {
                  "type": "float"
                }
              }
            }
          }
        }
      }
    }
  }
}

PUT stat/doc/1
{
  "agent": {
    "@timestamp": "2018-09-01T09:19:00.000Z"
  },
  "cpu": {
    "total": {
      "pct": 11
    },
    "iowait": {
      "pct": 0
    },
    "sys": {
      "pct": 1
    },
    "idle": {
      "pct": 88.6
    },
    "user": {
      "pct": 10.5
    }
  }
}
```
 2. Create and start a rollup job.
```
PUT _xpack/rollup/job/rollup-stat
{
  "index_pattern": "stat",
  "rollup_index": "rollup-stat",
  "cron": "* * * * * ?",
  "page_size": 2000,
  "groups": {
    "date_histogram": {
      "interval": "1h",
      "field": "agent.@timestamp"
    }
  },
  "metrics": [
    {
      "field": "cpu.total.pct",
      "metrics": [
        "min",
        "max",
        "avg"
      ]
    }
  ]
}

POST _xpack/rollup/job/rollup-stat/_start
```
 3. Run a rollup query
```
GET rollup-stat/_rollup_search
{
  "size": 0,
  "aggs": {
    "1day_val": {
      "date_histogram": {
        "field": "agent.@timestamp",
        "interval": "1d",
        "format": "yyyy-MM-dd",
        "time_zone": "UTC"
      },
      "aggs": {
        "cpu_day_max": {
          "max": {
            "field": "cpu.total.pct"
          }
        }
      }
    },
    "cpu_peak_avg": {
      "avg_bucket": {
        "buckets_path": "1day_val>buckets>cpu_day_max"
      }
    }
  }
}
```
and see the pipeline aggregation (cpu_peak_avg) result is missing as below:
```
{
  "took": 1,
  "timed_out": false,
  "terminated_early": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 0,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "1day_val": {
      "meta": {},
      "buckets": [
        {
          "key_as_string": "2018-09-01T00:00:00.000Z",
          "key": 1535760000000,
          "doc_count": 1,
          "cpu_day_max": {
            "value": 11
          }
        }
      ]
    }
  }
}
```
The result should include 
```
    "cpu_peak_avg": {
      "value": 11
    }
```

**Provide logs (if relevant)**:

**Comment by rokcarl** [comment] 2020-10-21 06:04
I have a similar problem that, I think, has the same root cause.

The problem is that I can do a Max Bucket aggregation on my raw data, but I can't on my rollup data.

Here's the graph from the raw data:

<img width="1536" alt="Screenshot 2020-10-20 at 15 50 45" src="https://user-images.githubusercontent.com/42874/96678892-e7239380-1372-11eb-9856-1beb06a5dd01.png">

But I can't do the same graph from the rolled-up data. I can also do a [search query](https://gist.github.com/rokcarl/fa297006ca3c0cea3c2322ac47404436) on `GET /stats-*/_search` to get lots of [aggregation results](https://gist.github.com/rokcarl/ba61bbed727e9c7f2c5b0bb02a5d20a4), but if I run the same query on the rollup index `GET /stat_rollups_minute2/_rollup_search`, I get an error `There is not a rollup job that has a [date_histogram] agg on field [timestamp] which also satisfies all requirements of query.`.
I used [this straightforward rollup configuration](https://gist.github.com/rokcarl/2273874a8fc4b362332135c1d07bebcb).

**Comment by not-napoleon** [comment] 2021-06-14 17:18
@giladgal @csoulios - Can you comment on this?  I don't think downsampling for metrics will solve these use cases.

**Comment by csoulios** [comment] 2021-06-15 14:20
It looks like pipeline aggregations are not supported by the `_rollup_search` endpoint. 
As per @polyfractal it is a known issue:  https://github.com/elastic/sdh-elasticsearch/issues/1011#issuecomment-428480674

>    >  I suspect the pipeline aggregations not running is also a bug too.
> 
> This is definitely a known bug, although there's no ticket right now. I was hoping to get it fixed last month but was distracted by some larger bugs (the ID collision bug).
> 
> It unfortunately turned out to be tricky to support pipelines. I have a WIP branch (https://github.com/polyfractal/elasticsearch/tree/rollup_pipeline_aggs) which works, but the solution is not pretty. After review we may decide it's not worth the hacks and just declare pipelines unsupported until we find a better solution, not sure.

And it looks like this ticket was created to document this problem.

**Comment by wchaparro** [comment] 2023-06-23 19:17
With the 8.7 release of Elasticsearch, we have made a [new downsampling capability](https://www.elastic.co/guide/en/elasticsearch/reference/current/downsampling.html) associated with the new [time series datastreams](https://www.elastic.co/guide/en/elasticsearch/reference/current/tsds.html) functionality generally available (GA). This capability was in tech preview in ILM since 8.5.  Downsampling provides a method to reduce the footprint of your time series data by storing it at reduced granularity. The downsampling process rolls up documents within a fixed time interval into a single summary document. Each summary document includes statistical representations of the original data: the min, max, sum, value_count, and average for each metric. Data stream time series dimensions are stored unchanged. 

Downsampling is superior to rollup because:

- Downsampled indices are searched through the _search API
- It is possible to query multiple downsampled indices together with raw data indices
- The pre-aggregation is based on the metrics and time series definitions in the index mapping so very little configuration is required (i.e. much easier to add new time serieses)
- Downsampling is managed as an action in ILM
- It is possible to downsample a downsampled index, and reduce granularity as the index ages
- The performance of the pre-aggregation process is superior in downsampling, as it builds on the time_series index mode infrastructure

Because of the introduction of this new capability, we are deprecating the rollups functionality, which never left the Tech Preview/Experimental status, in favor of downsampling and thus we are closing this issue. We encourage you to migrate your solution to downsampling and take advantage of the new TSDB functionality.

**Closed by wchaparro** 2023-06-23 19:17 UTC
Labels: >bug, :Analytics/Rollup, Team:Analytics
