### ISSUE TITLE
bg_count is always zero when doing a significant terms aggregation with a custom background set that does not overlap with the foreground set

### ISSUE THREAD

**Issue by ryanrozich** [elastic/elasticsearch#18738] opened 2016-06-04 04:03 UTC
ES 2.3.2 server and java api

Whenever I perform a significant terms aggregation with a custom background set (where the background set and foreground sets do not overlap) and iterate through the `SignificantTerms.Bucket` entry objects in the java object result, I always get a `subsetDF`, `subsetSize` and `supersetDF` but `supersetSize` is always zero. It doesn't matter which significance heuristic I use. Is this expected? Is there another way I should be getting the per-bucket counts from the background set?

Example json request and response below, notice that the bg_count is zero for all of the results

**Request**
```json
{
  "size" : 0,
  "query" : {
    "bool" : {
      "filter" : {
        "range" : {
          "createdAt" : {
            "from" : "2016-05-19",
            "to" : "2016-05-25",
            "include_lower" : true,
            "include_upper" : true
          }
        }
      }
    }
  },
  "aggregations" : {
    "significant_categories" : {
      "significant_terms" : {
        "field" : "category",
        "size" : 5,
        "background_filter" : {
          "range" : {
            "createdAt" : {
              "from" : "2016-05-12",
              "to" : "2016-05-18",
              "include_lower" : true,
              "include_upper" : true
            }
          }
        },
        "mutual_information" : {
          "include_negatives" : true,
          "background_is_superset" : false
        }
      }
    }
  }
}
```

**Response**
```json
{
  "took" : 35,
  "timed_out" : false,
  "_shards" : {
    "total" : 18,
    "successful" : 18,
    "failed" : 0
  },
  "hits" : {
    "total" : 543817,
    "max_score" : 0.0,
    "hits" : [ ]
  },
  "aggregations" : {
    "significant_categories" : {
      "doc_count" : 543817,
      "buckets" : [ {
        "key" : "Condiments_And_Sweeteners.Hot_sauces",
        "doc_count" : 29754,
        "score" : 0.028138457657103193,
        "bg_count" : 0
      }, {
        "key" : "Chemistry.Fatty_acids",
        "doc_count" : 11676,
        "score" : 0.01090831954637533,
        "bg_count" : 0
      }, {
        "key" : "Beverages.Milk_substitutes",
        "doc_count" : 10549,
        "score" : 0.009848021517760529,
        "bg_count" : 0
      }, {
        "key" : "Chemistry.Essential_oils",
        "doc_count" : 8521,
        "score" : 0.007944061722549585,
        "bg_count" : 0
      }, {
        "key" : "Condiments_And_Sweeteners.Salad_dressings",
        "doc_count" : 6036,
        "score" : 0.005618049544322981,
        "bg_count" : 0
      } ]
    }
  }
}
```

**Comment by clintongormley** [comment] 2016-06-06 17:14
@markharwood could you take a look please?

**Comment by markharwood** [comment] 2016-06-06 17:45
I see the foreground and background sets do not overlap at all in terms of documents.
Is it conceivable that the category fields used in the foreground set were not used at all in the background set? That would certainly be a significant change (nothing to 29754 sales). In my tests I see bg_count as >0 except for when the foreground set terms do not exist in the background set.

**Comment by ryanrozich** [comment] 2016-06-08 05:25
Thanks @markharwood for taking a look here.

What I am doing in this example is comparing log events from a previous time period to a current time period, so you are right the foreground and background do not overlap in terms of documents. However, I have verified that these terms do exist in the background set through a second query.

Here is an example using region as the field for aggregating significant terms

**Request**
```json
{
  "size" : 0,
  "query" : {
    "bool" : {
      "filter" : {
        "range" : {
          "createdAt" : {
            "from" : "2016-05-19",
            "to" : "2016-05-25",
            "include_lower" : true,
            "include_upper" : true
          }
        }
      }
    }
  },
  "aggregations" : {
    "significant_categories" : {
      "significant_terms" : {
        "field" : "geoip.real_region_name.raw",
        "size" : 20,
        "background_filter" : {
          "range" : {
            "createdAt" : {
              "from" : "2016-05-12",
              "to" : "2016-05-18",
              "include_lower" : true,
              "include_upper" : true
            }
          }
        },
        "mutual_information" : {
          "include_negatives" : true,
          "background_is_superset" : false
        }
      }
    }
  }
}
```

**Response**
```json
{
  "took" : 40,
  "timed_out" : false,
  "_shards" : {
    "total" : 18,
    "successful" : 18,
    "failed" : 0
  },
  "hits" : {
    "total" : 543817,
    "max_score" : 0.0,
    "hits" : [ ]
  },
  "aggregations" : {
    "significant_categories" : {
      "doc_count" : 543817,
      "buckets" : [ {
        "key" : "California",
        "doc_count" : 40928,
        "score" : 0.03900360479716631,
        "bg_count" : 0
      }, {
        "key" : "New York",
        "doc_count" : 24273,
        "score" : 0.0228697776932465,
        "bg_count" : 0
      }, {
        "key" : "Florida",
        "doc_count" : 19577,
        "score" : 0.018386887777233945,
        "bg_count" : 0
      }, {
        "key" : "New Jersey",
        "doc_count" : 12524,
        "score" : 0.011707184425668314,
        "bg_count" : 0
      }, {
        "key" : "Massachusetts",
        "doc_count" : 11555,
        "score" : 0.01079440443731854,
        "bg_count" : 0
      }, {
        "key" : "Illinois",
        "doc_count" : 10948,
        "score" : 0.010223223979040349,
        "bg_count" : 0
      }, {
        "key" : "Indiana",
        "doc_count" : 9297,
        "score" : 0.00867199072530764,
        "bg_count" : 0
      }, {
        "key" : "Michigan",
        "doc_count" : 7680,
        "score" : 0.007156007888300512,
        "bg_count" : 0
      }, {
        "key" : "Connecticut",
        "doc_count" : 7320,
        "score" : 0.006818941429226905,
        "bg_count" : 0
      }, {
        "key" : "Georgia",
        "doc_count" : 7103,
        "score" : 0.006615843146036082,
        "bg_count" : 0
      }, {
        "key" : "Colorado",
        "doc_count" : 6712,
        "score" : 0.006250039611369389,
        "bg_count" : 0
      }, {
        "key" : "Arizona",
        "doc_count" : 6609,
        "score" : 0.006153708646216918,
        "bg_count" : 0
      }, {
        "key" : "Minnesota",
        "doc_count" : 6590,
        "score" : 0.00613594029555656,
        "bg_count" : 0
      }, {
        "key" : "Maryland",
        "doc_count" : 6420,
        "score" : 0.005976980257079576,
        "bg_count" : 0
      }, {
        "key" : "Missouri",
        "doc_count" : 5485,
        "score" : 0.0051033406093923235,
        "bg_count" : 0
      }, {
        "key" : "British Columbia",
        "doc_count" : 5466,
        "score" : 0.005085598730652028,
        "bg_count" : 0
      }, {
        "key" : "North Carolina",
        "doc_count" : 4702,
        "score" : 0.004372558367334927,
        "bg_count" : 0
      }, {
        "key" : "Louisiana",
        "doc_count" : 4329,
        "score" : 0.0040246998498886764,
        "bg_count" : 0
      }, {
        "key" : "Nevada",
        "doc_count" : 2683,
        "score" : 0.0024916935042830425,
        "bg_count" : 0
      }, {
        "key" : "Alabama",
        "doc_count" : 2592,
        "score" : 0.002407037622030747,
        "bg_count" : 0
      } ]
    }
  }
}
```

Notice that the `bg_count` is always zero in each bucket. So I've created a follow up query with a `filters` aggregtion over the background set to get the actual counts for each bucket. See request and response below:

**Request**
```json
{
  "size" : 0,
  "query" : {
    "bool" : {
      "filter" : [ {
        "terms" : {
          "geoip.real_region_name.raw" : [ "North Carolina", "New York", "Indiana", "Minnesota", "British Columbia", "California", "Florida", "Alabama", "New Jersey", "Michigan", "Massachusetts", "Illinois", "Colorado", "Connecticut", "Missouri", "Louisiana", "Georgia", "Maryland", "Arizona", "Nevada" ]
        }
      }, {
        "range" : {
          "createdAt" : {
            "from" : "2016-05-12",
            "to" : "2016-05-18",
            "include_lower" : true,
            "include_upper" : true
          }
        }
      } ]
    }
  },
  "aggregations" : {
    "sigterms" : {
      "filters" : {
        "filters" : {
          "California" : {
            "term" : {
              "geoip.real_region_name.raw" : "California"
            }
          },
          "New York" : {
            "term" : {
              "geoip.real_region_name.raw" : "New York"
            }
          },
          "Florida" : {
            "term" : {
              "geoip.real_region_name.raw" : "Florida"
            }
          },
          "New Jersey" : {
            "term" : {
              "geoip.real_region_name.raw" : "New Jersey"
            }
          },
          "Massachusetts" : {
            "term" : {
              "geoip.real_region_name.raw" : "Massachusetts"
            }
          },
          "Illinois" : {
            "term" : {
              "geoip.real_region_name.raw" : "Illinois"
            }
          },
          "Indiana" : {
            "term" : {
              "geoip.real_region_name.raw" : "Indiana"
            }
          },
          "Michigan" : {
            "term" : {
              "geoip.real_region_name.raw" : "Michigan"
            }
          },
          "Connecticut" : {
            "term" : {
              "geoip.real_region_name.raw" : "Connecticut"
            }
          },
          "Georgia" : {
            "term" : {
              "geoip.real_region_name.raw" : "Georgia"
            }
          },
          "Colorado" : {
            "term" : {
              "geoip.real_region_name.raw" : "Colorado"
            }
          },
          "Arizona" : {
            "term" : {
              "geoip.real_region_name.raw" : "Arizona"
            }
          },
          "Minnesota" : {
            "term" : {
              "geoip.real_region_name.raw" : "Minnesota"
            }
          },
          "Maryland" : {
            "term" : {
              "geoip.real_region_name.raw" : "Maryland"
            }
          },
          "Missouri" : {
            "term" : {
              "geoip.real_region_name.raw" : "Missouri"
            }
          },
          "British Columbia" : {
            "term" : {
              "geoip.real_region_name.raw" : "British Columbia"
            }
          },
          "North Carolina" : {
            "term" : {
              "geoip.real_region_name.raw" : "North Carolina"
            }
          },
          "Louisiana" : {
            "term" : {
              "geoip.real_region_name.raw" : "Louisiana"
            }
          },
          "Nevada" : {
            "term" : {
              "geoip.real_region_name.raw" : "Nevada"
            }
          },
          "Alabama" : {
            "term" : {
              "geoip.real_region_name.raw" : "Alabama"
            }
          }
        }
      }
    }
  }
}
```

**Response**
```json
{
  "took" : 18,
  "timed_out" : false,
  "_shards" : {
    "total" : 18,
    "successful" : 18,
    "failed" : 0
  },
  "hits" : {
    "total" : 214123,
    "max_score" : 0.0,
    "hits" : [ ]
  },
  "aggregations" : {
    "sigterms" : {
      "buckets" : {
        "California" : {
          "doc_count" : 39262
        },
        "New York" : {
          "doc_count" : 25489
        },
        "Florida" : {
          "doc_count" : 20512
        },
        "New Jersey" : {
          "doc_count" : 14308
        },
        "Massachusetts" : {
          "doc_count" : 13731
        },
        "Illinois" : {
          "doc_count" : 12788
        },
        "Indiana" : {
          "doc_count" : 4603
        },
        "Michigan" : {
          "doc_count" : 9815
        },
        "Connecticut" : {
          "doc_count" : 4457
        },
        "Georgia" : {
          "doc_count" : 7617
        },
        "Colorado" : {
          "doc_count" : 8229
        },
        "Arizona" : {
          "doc_count" : 7056
        },
        "Minnesota" : {
          "doc_count" : 7485
        },
        "Maryland" : {
          "doc_count" : 7218
        },
        "Missouri" : {
          "doc_count" : 6259
        },
        "British Columbia" : {
          "doc_count" : 5440
        },
        "North Carolina" : {
          "doc_count" : 10301
        },
        "Louisiana" : {
          "doc_count" : 3819
        },
        "Nevada" : {
          "doc_count" : 3140
        },
        "Alabama" : {
          "doc_count" : 2594
        }
      }
    }
  }
}
```

Notice that when I query the background set directly for doc counts using this secondary query and a `filters` aggregation I can get the actual counts in the background set. I would have expected these to be the counts that were returned in the `bg_count` field of the significant terms result. 

My use case here is looking for anomalies in a current time period versus a previous time period (i.e. what is trending up or down). My intention is to produce reports from the query above like:

```
California change:   +8.36% significance score: 0.039004
             *  cur_wk:  7.53% (   40,928 views out of   543,817)
             * prev_wk:  6.95% (   39,262 views out of   565,291)

  New York change:   -1.01% significance score: 0.022870
             *  cur_wk:  4.46% (   24,273 views out of   543,817)
             * prev_wk:  4.51% (   25,489 views out of   565,291)

   Florida change:   -0.79% significance score: 0.018387
             *  cur_wk:  3.60% (   19,577 views out of   543,817)
             * prev_wk:  3.63% (   20,512 views out of   565,291)

New Jersey change:   -9.01% significance score: 0.011707
             *  cur_wk:  2.30% (   12,524 views out of   543,817)
             * prev_wk:  2.53% (   14,308 views out of   565,291)

Massachusetts change:  -12.52% significance score: 0.010794
             *  cur_wk:  2.12% (   11,555 views out of   543,817)
             * prev_wk:  2.43% (   13,731 views out of   565,291)

  Illinois change:  -11.01% significance score: 0.010223
             *  cur_wk:  2.01% (   10,948 views out of   543,817)
             * prev_wk:  2.26% (   12,788 views out of   565,291)

   Indiana change: +109.95% significance score: 0.008672
             *  cur_wk:  1.71% (    9,297 views out of   543,817)
             * prev_wk:  0.81% (    4,603 views out of   565,291)

  Michigan change:  -18.66% significance score: 0.007156
             *  cur_wk:  1.41% (    7,680 views out of   543,817)
             * prev_wk:  1.74% (    9,815 views out of   565,291)

Connecticut change:  +70.72% significance score: 0.006819
             *  cur_wk:  1.35% (    7,320 views out of   543,817)
             * prev_wk:  0.79% (    4,457 views out of   565,291)

   Georgia change:   -3.07% significance score: 0.006616
             *  cur_wk:  1.31% (    7,103 views out of   543,817)
             * prev_wk:  1.35% (    7,617 views out of   565,291)

  Colorado change:  -15.21% significance score: 0.006250
             *  cur_wk:  1.23% (    6,712 views out of   543,817)
             * prev_wk:  1.46% (    8,229 views out of   565,291)

   Arizona change:   -2.64% significance score: 0.006154
             *  cur_wk:  1.22% (    6,609 views out of   543,817)
             * prev_wk:  1.25% (    7,056 views out of   565,291)

 Minnesota change:   -8.48% significance score: 0.006136
             *  cur_wk:  1.21% (    6,590 views out of   543,817)
             * prev_wk:  1.32% (    7,485 views out of   565,291)

  Maryland change:   -7.54% significance score: 0.005977
             *  cur_wk:  1.18% (    6,420 views out of   543,817)
             * prev_wk:  1.28% (    7,218 views out of   565,291)

  Missouri change:   -8.91% significance score: 0.005103
             *  cur_wk:  1.01% (    5,485 views out of   543,817)
             * prev_wk:  1.11% (    6,259 views out of   565,291)

British Columbia change:   +4.45% significance score: 0.005086
             *  cur_wk:  1.01% (    5,466 views out of   543,817)
             * prev_wk:  0.96% (    5,440 views out of   565,291)

North Carolina change:  -52.55% significance score: 0.004373
             *  cur_wk:  0.86% (    4,702 views out of   543,817)
             * prev_wk:  1.82% (   10,301 views out of   565,291)

 Louisiana change:  +17.83% significance score: 0.004025
             *  cur_wk:  0.80% (    4,329 views out of   543,817)
             * prev_wk:  0.68% (    3,819 views out of   565,291)

    Nevada change:  -11.18% significance score: 0.002492
             *  cur_wk:  0.49% (    2,683 views out of   543,817)
             * prev_wk:  0.56% (    3,140 views out of   565,291)

   Alabama change:   +3.87% significance score: 0.002407
             *  cur_wk:  0.48% (    2,592 views out of   543,817)
             * prev_wk:  0.46% (    2,594 views out of   565,291)

```

Without the `bg_count` I cannot calculate the proportion of events in the previous week and therefore cannot calculate the relative change week over week. The secondary query/aggregation is what I need to do for the time being to get this count.

This secondary query is a fine stopgap for a simple example like this, but as I want to do more advanced things like start nesting significant terms aggregations, having to do 2-stage queries for each bucket and each of the sub-buckets starts to get messy and expensive.

**Comment by markharwood** [comment] 2016-06-08 09:08
I can't reproduce on 2.3.2 and using REST api.

We can either work back from your broken system's config, removing config/data until it works or build up from a simpler working example adding data/config that is the same as your system until it breaks.

Here's my simple example which works with a single shard/node and also multiple shards and nodes

	DELETE test
	PUT test
	{
	   "settings": {
		  "number_of_replicas": "0",
		  "number_of_shards": "1"
	   },
	   "mappings": {
		  "doc": {
			 "properties": {
				"state": {
				   "type": "string",
				   "index": "not_analyzed"
				},
				"date": {
				   "type": "date",
				   "format": "yyyy-MM-dd"
				}
			 }
		  }
	   }
	}
	POST test/doc
	{ "state":"MA", "date":"2016-05-12" }
	POST test/doc
	{ "state":"CA", "date":"2016-05-12" }
	POST test/doc
	{ "state":"CA", "date":"2016-05-13" }
	POST test/doc
	{ "state":"CA", "date":"2016-05-14" }

	POST test/doc
	{ "state":"MA", "date":"2016-05-19" }
	POST test/doc
	{ "state":"CA", "date":"2016-05-19" }
	POST test/doc
	{ "state":"CA", "date":"2016-05-20" }
	POST test/doc
	{ "state":"CA", "date":"2016-05-21" }
	POST test/doc
	{ "state":"CA", "date":"2016-05-22" }

	POST test/_search
	{
	   "query": {
		  "bool": {
			 "filter": {
				"range": {
				   "date": {
					  "from": "2016-05-19",
					  "to": "2016-05-25",
					  "include_lower": true,
					  "include_upper": true
				   }
				}
			 }
		  }
	   },
	   "size": 0,
	   "aggs": {
		  "keywords": {
			 "significant_terms": {
				"field": "state",
				"background_filter": {
				   "range": {
					  "date": {
						 "from": "2016-05-12",
						 "to": "2016-05-18",
						 "include_lower": true,
						 "include_upper": true
					  }
				   }
				},
				"mutual_information": {
				   "include_negatives": true,
				   "background_is_superset": false
				}
			 }
		  }
	   }
	}

Can you help play spot-the-difference with your setup?

**Comment by ryanrozich** [comment] 2016-06-08 13:17
One difference might be that I am using a logstash-style index with one shard per day. So in my case of the foreground and background set data would exist on separate shards, could that make a difference?

**Comment by markharwood** [comment] 2016-06-08 13:41
>t I am using a logstash-style index with one shard per day.

To be clear, presumably one _index_ per day, not shard.

>could that make a difference?
Yes. In the simple case if you were looking at this Thursday Vs last Thursday and had daily indices each shard would either have a zero-sized foreground or zero-sized background. If the former it would return no results (nothing matched the query) and if the latter it would return bg_count ==0 which is what you are seeing.

There's an assumption in significant_terms that each shard has a reasonable mix of both foreground and background data from which we can spot promising changes locally. If your data/queries are not organised this way it won't work well.

Given your data layout you're probably better advised to issue a single query and return two filtered aggregations one for the states in the current time range and one for the states in the historic time range and diff the values using your own code.

**Comment by ryanrozich** [comment] 2016-06-08 20:48
Thanks Mark.

If the significant terms are calculated per-shard, its surprising that I am getting any results back at all, since none of the shards will contain examples from both foreground and background sets. What terms am I getting returned in these examples?

For examples like states with low cardinality its feasible to do two filter aggregations and do the diff in memory, but some fields have very high cardinality (tens of thousands of terms). Are there any other suggestions on looking for date-range-based anomalies for indexes that are partitioned by date?

**Comment by ryanrozich** [comment] 2016-06-08 21:43
From your comment on significant terms assuming that each shard needing to have a reasonable mix of foreground and background data to spot changes locally, I assumed that the buckets I was getting back were meaningless since this is never the case in my examples. 

However, it actually looks like these buckets do represent significant differences between the two date ranges. For instance here is example output based on referrer site

```
 Views coming from referrer site buzzfeed.com changed by +1002.89% over the previous period (significance score: 0.004579)
     *  cur_wk:  0.91% (    4,923 views out of   543,817)
     * prev_wk:  0.08% (      464 views out of   565,291)
```
Taking a quick look in kibana at the foreground and background date range, there does seem to be a very significant difference between the foreground and background sets

![kibana screenshot](https://gmkr.io/s/57588e718e519a8474c1e0a3/0)

I did have to look up the background count in the separate query with the secondary filter query, but isn't it odd that the significant terms aggregation called this out, given how my indexes are partitioned?

Just to check if I got lucky with this other example, I looked at another:

```
 Views coming from referrer site facebook.com changed by  -30.27% over the previous period (significance score: 0.009720)
     *  cur_wk:  1.91% (   10,413 views out of   543,817)
     * prev_wk:  2.75% (   15,523 views out of   565,291)
```

visualizing the data in kibana again shows that there is indeed a negative trend between the background and foreground sets

![Screenshot of Kibana](https://gmkr.io/s/57589030cf468e6678b1e0c2/0)

I did this for several of the other top significant terms buckets, they all seem to represent real significant differences in the foreground and background sets. I'm wondering how this could be, given that on each shard, the foreground count=0 or background count=0?

**Comment by markharwood** [comment] 2016-06-09 08:30
>What terms am I getting returned in these examples?

From shards with no foreground you'll get no results.
From shards with no background, some significance heuristics I expect will throw an error. You have opted for mutual information and set the `background_is_superset` to false meaning that it should expect foreground and background numbers to be independent. In the absence of _any_ background stats it looks like this heuristic would simply rank based on straight foreground popularity.

> Are there any other suggestions on looking for date-range-based anomalies for indexes that are partitioned by date?

If you could introduce just one dummy document into each shard that listed all states and had a dummy=true flag on it you could change your foreground query to be dateRange=X OR dummy=true. This would have the effect of always bringing each state into the foreground set at least once regardless if the shard was in the desired date range. That then means each shard would always return foreground and background stats and the final answer computed on the reduce node would have all the background stats - they would just be off by one because of the dummy doc.

**Comment by markharwood** [comment] 2016-06-13 13:33
Currently working as-designed and although it would be nice to have a fix we don't see an easy work-around from the elastic side. My last comment offers a possible solution although this is less than ideal.

Closing for now but I can re-open if we have any further bright ideas.

**Closed by markharwood** 2016-06-13 13:33 UTC
Labels: :Aggregations, won't fix

**Comment by ryanrozich** [comment] 2016-06-15 13:01
Thanks Mark for the help and explanations. It would be great in the future to be able to have significant terms work for looking for differences in date ranges on dat-partitioned indexes, but for now I'll do the diffs in code. At least I can use the elasticsearch SignificanceHeurisitic implementations so I don't have to re-implement all the math.
