### ISSUE TITLE
Synthetic _source: support ignore_malformed

### ISSUE THREAD

**Issue by felixbarny** [elastic/elasticsearch#90007] opened 2022-09-12 14:32 UTC
As part of LX, we want to make log indices more lenient. Therefore, we're planning on using ignore_malformed. See also https://github.com/elastic/elasticsearch/issues/88777. While using synthetic source is not a requirement for LX, we should think about how we could eventually leverage synthetic source to save space.

One of the blockers is that synthetic source doesn't have support for ignore_malformed. That's because malformed values will only be available in the _source. But if the source is synthetic, malformed values would just be lost.

We could to something similar to https://github.com/elastic/elasticsearch/pull/89466 and store malformed values in a hidden stored field. One of the challenges is that stored fields are strictly typed (IINM) but the malformed value could be of any type. But we could just always store the malformed value in a string field, in the exact form that was provided in the JSON document. For example `"42"` (note the quotes), `true`, `42`. When re-constructing the _source, we can just use that value and append it to the JSON document. Just an idea :)

cc @nik9000

**Comment by nik9000** [comment] 2022-09-13 17:54
Began in #90038

**Comment by javanna** [comment] 2023-04-21 12:14
heya @nik9000 do you remember what is left to do here?

**Comment by felixbarny** [comment] 2023-05-04 07:42
AFAICS, Nik added support for the ip field type but others are missing. I guess the first step would be to create a list of all field types and tick the one(s) off that are supported already and then work on implementing support for the rest.

We have recently made the change to use `ignore_malformed` by default for logs: https://github.com/elastic/elasticsearch/pull/95329.

**Comment by felixbarny** [comment] 2023-05-04 08:05
> create a list of all field types and tick the one(s) off that are supported already and then work on implementing support for the rest.

Nvm. this already exists here: https://github.com/elastic/elasticsearch/issues/86603

**Comment by nik9000** [comment] 2023-05-04 10:30
> heya @nik9000 do you remember what is left to do here?

Wow I missed this comment. Sorry.

I left off trying to build `ignore_malformed` for `geo_point` which is especially complex because it's a json object and not a single field. So we have to "go back" if we hit a malformed object. I think I had it working, but the implementation made me sad: #90777 .  I picked `geo_point` at the time because it was the simplest example of the "complex" fields. But I think the way forward is clear for most of the other field types. Just not the json object ones.

**Comment by lkts** [comment] 2024-04-30 18:47
Currently `ignore_malformed` is not supported while using synthetic source for following fields.
* `scaled_float`
* `date`, `date_nanos`
* `geo_point`


`geo_shape` does not support synthetic source to begin with.

**Comment by lkts** [comment] 2024-05-13 18:35
I missed that, thank you for notifying.

**Comment by lkts** [comment] 2024-05-23 15:23
See #106483.

**Comment by lkts** [comment] 2024-07-02 15:11
Closing as a duplicate of #106483.

**Closed by lkts** 2024-07-02 15:11 UTC
Labels: >feature, Team:StorageEngine, :StorageEngine/Mapping
