### ISSUE TITLE
SQL: SUM FUNCTION CAN NOT WORK WITH "*"

### ISSUE THREAD

**Issue by GuilleCoduri** [elastic/elasticsearch#37972] opened 2019-01-29 14:35 UTC
Hi, 
Currently, multiplication within a sum is not supported.
I tried it in version 7.0-alpha. Could it be supported in later versions?

Simples use case:  `SELECT SUM(PRICE * QTY) FROM test GROUP BY XXX`

**Comment by matriv** [comment] 2019-05-09 15:28
Closing this as a duplicate of #29980.
Currently no expression other than plain fields (columns) is allowed inside aggregate functions.

**Closed** 2019-05-09 20:24 UTC
Labels: :Search/SQL
