### ISSUE TITLE
[CI] MetadataIndexStateServiceBatchingTests testBatchCloseIndices failing

### ISSUE THREAD

**Issue by arteam** [elastic/elasticsearch#109187] opened 2024-05-29 21:39 UTC
**Build scan:**
https://gradle-enterprise.elastic.co/s/vn2vj6dmamixc/tests/:server:test/org.elasticsearch.cluster.metadata.MetadataIndexStateServiceBatchingTests/testBatchCloseIndices

**Reproduction line:**
```
./gradlew ':server:test' --tests "org.elasticsearch.cluster.metadata.MetadataIndexStateServiceBatchingTests.testBatchCloseIndices" -Dtests.seed=A054AE00F85B4FB8 -Dtests.locale=hi -Dtests.timezone=Pacific/Majuro -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
[Failure dashboard for `org.elasticsearch.cluster.metadata.MetadataIndexStateServiceBatchingTests#testBatchCloseIndices`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testBatchCloseIndices'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.cluster.metadata.MetadataIndexStateServiceBatchingTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([A054AE00F85B4FB8]:0)

```

**Comment by arteam** [comment] 2024-05-31 09:53
Actual exception:
```
May 30, 2024 8:26:54 AM com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException	
WARNING: Uncaught exception in thread: Thread[#362,elasticsearch[node_s_0][clusterApplierService#updateTask][T#1],5,TGRP-MetadataIndexStateServiceBatchingTests]	
java.lang.AssertionError: 	
Expected: one of {<0>, <3>}	
     but: was <1>	
	at __randomizedtesting.SeedInfo.seed([A054AE00F85B4FB8]:0)	
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)	
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)	
	at org.elasticsearch.test.ESTestCase.assertThat(ESTestCase.java:2119)	
	at org.elasticsearch.cluster.metadata.MetadataIndexStateServiceBatchingTests.lambda$closedIndexCountListener$7(MetadataIndexStateServiceBatchingTests.java:213)	
	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListener(ClusterApplierService.java:560)	
	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListeners(ClusterApplierService.java:546)	
	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:505)	
	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:429)	
	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:154)	
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:917)	
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:217)	
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:183)	
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)	
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)	
	at java.base/java.lang.Thread.run(Thread.java:1583)	
```

**Comment by ywangd** [comment] 2024-06-03 06:49
The relevant logs are
```
[2024-05-30T08:26:54,184][INFO ][o.e.c.m.MetadataIndexStateService] [node_s_0] closing indices [test-1/KC4ZJtYhQsqHLrwsmvO4UQ]
[2024-05-30T08:26:54,185][INFO ][o.e.c.m.MetadataIndexStateService] [node_s_0] closing indices [test-3/Yg8Zg7_PTUmpSx-N0Os_0Q],[test-2/dnFWjYBQTjWu6itOkczzcQ]
[2024-05-30T08:26:54,219][INFO ][o.e.c.m.MetadataIndexStateService] [node_s_0] completed closing of indices [test-1]
```

Note there is no "completed closing of indices" message for the second "closing" request, i.e. the second request failed somehow. Unfortunately this error message is sallowed due to how this test is structured. I raised #109278 for better error message in case this fails again.

**Comment by ywangd** [comment] 2024-06-21 10:35
Failed again 
https://gradle-enterprise.elastic.co/s/zrcvzjabo4e4y/tests/task/:server:test/details/org.elasticsearch.cluster.metadata.MetadataIndexStateServiceBatchingTests/testBatchCloseIndices?expanded-stacktrace=WyIwIl0&top-execution=1

**Comment by ywangd** [comment] 2024-07-03 03:17
@DaveCTurner Could you please advise how this test failure should be fixed?

It is reproducible with the following diff
```diff
--- a/server/src/main/java/org/elasticsearch/cluster/service/MasterService.java
+++ b/server/src/main/java/org/elasticsearch/cluster/service/MasterService.java
@@ -1602,6 +1602,14 @@ public class MasterService extends AbstractLifecycleComponent {
                 )
             );

+            if (name.equals("close-index")) {
+                try {
+                    Thread.sleep(Math.abs(task.hashCode() % 10) * 200);
+                } catch (InterruptedException e) {
+                    throw new RuntimeException(e);
+                }
+            }
+
             if (queueSize.getAndIncrement() == 0) {
                 perPriorityQueue.execute(processor);
             }
```

The test expects the two `close-indices` tasks to be batched. It [waits](https://github.com/elastic/elasticsearch/blob/bc1b77ff111e1d1c1c19b0be0d0f1ef0c0454b3f/server/src/test/java/org/elasticsearch/cluster/metadata/MetadataIndexStateServiceBatchingTests.java#L127) for both of them to appear in the masterService's pending tasks before proceeding. However, the exact number of tasks to be batched is determined by [queueSize](https://github.com/elastic/elasticsearch/blob/bc1b77ff111e1d1c1c19b0be0d0f1ef0c0454b3f/server/src/main/java/org/elasticsearch/cluster/service/MasterService.java#L1663) which is [incremented](https://github.com/elastic/elasticsearch/blob/bc1b77ff111e1d1c1c19b0be0d0f1ef0c0454b3f/server/src/main/java/org/elasticsearch/cluster/service/MasterService.java#L1605) after [adding the task to the queue](https://github.com/elastic/elasticsearch/blob/bc1b77ff111e1d1c1c19b0be0d0f1ef0c0454b3f/server/src/main/java/org/elasticsearch/cluster/service/MasterService.java#L1594). If there is some delay between `queue.add` and `queueSize.getAndIncrement()` (as shown in the above diff), the two tasks will not be batched. Hence the indices will be closed in two cluster state publications instead of one, failing the test assertion.

I have spent quite some time on this but could not find a good way for fixing it. Intuitively, the test should wait for `queueSize` instead of `queue.size()`. But exposing `queueSize` is challenging since it's not part of the `Batch` interface. In addition,`MasterService` does not expose `Batch` either. It would be quite invasive to do so. Alternatively, I looked at `ClusterService`, `MasterService` and `MetadataIndexStateService` to see whether we can intercept the `createTaskQueue` to return a `queue` that counts its `submitTask` calls. But that does not seem possible (or at least not feasible without a lot of changes in node construction). Other options would be accepting that the test can sometimes not batching. But that is defeating the purpose of the test. Or rewrite the tests completely so it is no longer a `ESSingleNodeTestCase` and we construcut `MetadataIndexStateService` manually. Now sure how feasible it is and certainly a large change. I noticed [ClusterStateChanges](https://github.com/elastic/elasticsearch/blob/bc1b77ff111e1d1c1c19b0be0d0f1ef0c0454b3f/server/src/test/java/org/elasticsearch/indices/cluster/ClusterStateChanges.java#L132) which might be what we want if rewrite is the way to go.

Any comments and suggestions are appreciated. Thanks!

**Comment by DaveCTurner** [comment] 2024-07-03 04:03
Something like #110405 perhaps?

**Closed** 2024-07-03 05:26 UTC
Labels: >test-failure, :Distributed/Cluster Coordination, Team:Distributed, low-risk
