### ISSUE TITLE
Nested Query and Filter results in Filter being ignored

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#15648] opened 2015-12-24 01:14 UTC
I ran into this while answering [a question over on StackOverflow](http://stackoverflow.com/questions/34431092/how-to-access-doc-values-of-a-nested-array-in-elasticsearch-script). If you create a `nested` `query` and also supply the `filter`, then the `filter` is silently ignored. If you do not supply the `query`, then the `filter` is used as you would expect.

This issue is present in both ES 1.x and 2.x.

```http
PUT /test
{
  "mappings": {
    "user": {
      "properties": {
        "name": {
          "type": "string"
        },
        "skills": {
          "type": "nested",
          "properties": {
            "skill_id": {
              "type": "integer"
            },
            "recommendations_count": {
              "type": "integer"
            }
          }
        }
      }
    }
  }
}

PUT /test/user/1
{
   "name": "John",
   "skills": [
      {
         "skill_id": 100,
         "recommendations_count": 5
      },
      {
         "skill_id": 200,
         "recommendations_count": 3
      }
   ]
}

PUT /test/user/2
{
   "name": "Mary",
   "skills": [
      {
         "skill_id": 100,
         "recommendations_count": 9
      },
      {
         "skill_id": 200,
         "recommendations_count": 0
      }
   ]
}
```

Followed by:

```http
GET /test/_search
{
  "query": {
    "nested": {
      "path": "skills",
      "query": {
        "function_score": {
          "functions": [
            {
              "field_value_factor": {
                "field": "skills.recommendations_count",
                "factor": 1.2,
                "modifier": "sqrt",
                "missing": 1
              }
            }
          ]
        }
      },
      "filter": {
        "term": {
          "skills.skill_id": 100
        }
      }
    }
  }
}
```

Noting the `filter`, the `skill_id` filter works even if the value does not exist (e.g., 500). This is true of both Elasticsearch 1.x and 2.x.

This can be rewritten for each version to work though:

ES 1.x:

```http
GET /test/_search
{
  "query": {
    "nested": {
      "path": "skills",
      "query": {
        "filtered": {
          "filter": {
            "term": {
              "skills.skill_id": 100
            }
          },
          "query": {
            "function_score": {
              "functions": [
                {
                  "field_value_factor": {
                    "field": "skills.recommendations_count",
                    "factor": 1.2,
                    "modifier": "sqrt",
                    "missing": 0
                  }
                }
              ]
            }
          }
        }
      }
    }
  }
}
```

For ES 2.x:

```http
GET /test/_search
{
  "query": {
    "nested": {
      "path": "skills",
      "query": {
        "bool": {
          "filter": {
            "term": {
              "skills.skill_id": 100
            }
          },
          "must": {
            "function_score": {
              "functions": [
                {
                  "field_value_factor": {
                    "field": "skills.recommendations_count",
                    "factor": 1.2,
                    "modifier": "sqrt",
                    "missing": 0
                  }
                }
              ]
            }
          }
        }
      }
    }
  }
}
```

**Comment by clintongormley** [comment] 2016-01-10 19:05
@cbuescher has this been fixed with the search refactoring?

**Comment by cbuescher** [comment] 2016-01-11 11:25
@clintongormley Looking at the history of NestedQueryParser, it looks like support for the "field" parameter has been removed on master after deprecating it with 6076cc. I can take a look at what's causing this problem on 2.x.

**Comment by cbuescher** [comment] 2016-01-11 13:27
For 2.x, in `NestedQueryParser#build()` the `query` takes precedence over `filter` as observed by @pickypg when constructing the Lucene query. Looking at the docs in 1.7 or 2.x, this seems also like the expected behaviour (`the query (or filter) includes the query that will run on the nested`). Not sure if there is anything to fix here @clintongormley? We could throw an exception if both are specified, but not sure if that's worth going into 2.x since the whole parameter is gone on master anyway.

**Comment by clintongormley** [comment] 2016-01-11 18:52
Makes sense, thanks @cbuescher 

Closing

**Closed by clintongormley** 2016-01-11 18:52 UTC
Labels: :Query DSL, bug

**Comment by brupm** [comment] 2016-01-19 16:36
If I understand correctly you're saying that supporting both has been removed from master and that the documentation specified that `the query (or filter)` should be used. As in, either query OR filter is supported, but not both. If that's the case the documentation is not expressive enough to something that can potentially cause hours of headaches.

**Comment by pickypg** [comment] 2016-01-19 17:02
I tend to agree with @brupm on this one: it's a documentation bug if the code isn't going to be changed because "or" is overly suggestive.

In `master` (from 6076ccb), [the code literally removed `filter`](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/index/query/NestedQueryParser.java#L33-L36) as an option. Given the simplification of using filters in 2.0+, I think that that was the right move. It also needs to be listed as a breaking change though for 3.0.

I think that we should:

- Change the docs, starting with 2.0+ to not mention the `filter` parameter -- instead showing the `filter` being used using a `bool` query.
- Add the lack of a filter parameter for the nested query as a breaking change.

What do you think @clintongormley?

**Comment by clintongormley** [comment] 2016-01-20 14:12
I agree - @cbuescher would you mind adding the removal of the "filter" param from nested to the breaking changes in 3.0, plus anything similar that you can think of that has changed?

**Comment by cbuescher** [comment] 2016-01-20 14:35
@clintongormley there is already a note in https://github.com/elastic/elasticsearch/blob/master/docs/reference/migration/migrate_3_0.asciidoc#nested-query, should this go to any other place or is this the right location for "breaking changes"?

**Comment by clintongormley** [comment] 2016-01-20 15:29
@cbuescher ah i see it now https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking_30_rest_api_changes.html#_nested_query

i'll reorganise these breaking changes docs before we release to make them a bit more organised. thanks

**Comment by pickypg** [comment] 2016-01-20 15:32
Ah, I didn't look under the REST API changes. Honestly, most of those are more of "search changes" than REST API changes from my perspective.
