### ISSUE TITLE
Epoch Nano in date time format

### ISSUE THREAD

**Issue by mbullock1986** [elastic/elasticsearch#23323] opened 2017-02-23 12:58 UTC
**Describe the feature**: I currently have to convert EPOCH nano to EPOCH milli to be supported in Elastic Search. Can EPOCH Nano be added to date formats?

**Comment by jpountz** [comment] 2017-02-23 13:46
Indeed we have been thinking about increasing the accuracy of date fields for some time now, but it is not easy. Closing as a duplicate of #10005.

**Closed by jpountz** 2017-02-23 13:46 UTC
