### ISSUE TITLE
snapshot_in_progress_exception returns 400 status code causing most applications to fail instead of retrying their request

### ISSUE THREAD

**Issue by rudolf** [elastic/elasticsearch#65883] opened 2020-12-04 12:45 UTC
**Elasticsearch version** (`bin/elasticsearch --version`):
6.7+
7.x
8.x

**Description of the problem including expected versus actual behavior**:
When closing or deleting an index while a snapshot is in progress Elasticsearch returns a 400 Bad Request status code.
https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/snapshots/SnapshotInProgressException.java#L44

From https://tools.ietf.org/html/rfc7231#section-6.5.1
> 6.5.1.  400 Bad Request
>   The 400 (Bad Request) status code indicates that the server cannot or
   will not process the request due to something that is perceived to be
   **a client error** (e.g., malformed request syntax, invalid request
   message framing, or deceptive request routing).

Using the 503 status code would be more appropriate:
https://tools.ietf.org/html/rfc7231#section-6.6.4
> 6.6.4.  503 Service Unavailable
>   The 503 (Service Unavailable) status code indicates that the **server
   is currently unable to handle the request due to a temporary overload
   or scheduled maintenance, which will likely be alleviated after some
   delay**.  The server MAY send a Retry-After header field
   (Section 7.1.3) to suggest an appropriate amount of time for the
   client to wait before retrying the request.

Since most Elasticsearch clients will automatically retry a 503 error most users applications won't be affected by a snapshot_in_progress exception if it had a 503 status code e.g. elasticsearch-js:

https://github.com/elastic/elasticsearch-js/blob/502509cabc7ad58b714ea8e025d41fb249b6e12e/lib/Transport.js#L311-L314

Instead, after having received a 400 status code most applications might throw an exception or crash and users have to add custom retry logic to handle this special exception.

**Comment by original-brownbear** [comment] 2020-12-07 09:09
I think we could change this indeed. We already use `503` for `org.elasticsearch.snapshots.ConcurrentSnapshotExecutionException` (which is thrown when trying to run a snapshot operation that is prevented by another running snapshot operation) as well and it seems consistent to me to go with `503` in this case as well.

**Comment by pmuellr** [comment] 2021-03-16 18:16
I'm rarely happy to see applications return 50x errors directly, since it then becomes unclear if that response came from a proxy/gateway or from the application.  Since we do usually see 50x errors from proxy/gateways, I like it when applications **never** use these status codes, so you immediately know the problem is the proxy/gateway.

So I'll offer up the [429 status code - Too Many Requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429), as an alternative.  That doesn't quite fit either, unless you view it has "ES isn't allowing any requests right now, so even 1 is Too Many Requests".  :-)

That status code also specifically calls out the `Retry-After` response header, where you can give the client an indication of when they can try again.  For cases where we might know, or be able to provide an estimate of when the request can be retried.  Of course, we could use that header with any sort of "error" response, including 50x's.

Of course, we already use 429's in elasticsearch responses, so perhaps there would be some semantic conflict with the existing uses ...

**Comment by pmuellr** [comment] 2021-03-16 18:20
I'm curious what the retry logic looks like in the elasticsearch clients if we return a 50x - what sort of delay is involved before any retries they provide "for free"?  If it's short, and presumably there is a limit on the number of retries, the 50x may end up bubbling up to the callers pretty quickly with the snapshot still in-process, so likely the callers will end up with a now rarely-seen 50x response from the new clients, and still have to handle it as some kind of error.

**Comment by original-brownbear** [comment] 2022-07-28 11:52
Closing this, we have concurrent snapshots now so this is irrelevant for the most part.

**Closed by original-brownbear** 2022-07-28 11:52 UTC
Labels: >bug, :Distributed/Snapshot/Restore, :Core/Infra/REST API, Team:Distributed
