### ISSUE TITLE
[suggestion] Restore the removed option `index.compound_on_flush` to reduce write amplification ?

### ISSUE THREAD

**Issue by micoq** [elastic/elasticsearch#30560] opened 2018-05-14 08:17 UTC
Compound segment format helps to reduce the number of used file descriptors but to write this kind of segment (*.cfs *.cfe), Lucene first write a complete segment (*.fdx *.fdt ...), reread it and finally write the compound segment.

While it helps to reduce the number of file descriptors (2 files instead of ~14), this option increase the disk load and latency in heavy indexing environments.

In Elasticsearch, there was two options to control the compound format creation:
- `index.compound_on_flush` for flushes (defaults to true)
- `index.compound_format` for merges (defaults to 10% of the shard size)

The former was removed since ES 5.0 (#10778).

In our case, disable the second option reduces the CPU %wait from 5% to 1% on our cluster with the same load (doc/s).

For the first option, I made some tests in a raw Lucene index (not directly in Elasticsearch) and I observed a slightly better indexing speed (approximately 10%) with compound format disabled (tested on SSDs and rotating disks with NIOFSDirectory and Lucene 7.0.0).

However, for small segments (<1 MB) and small refresh interval (Lucene flush, <1s) the compound format performs better (since the latency came from the file creation, not from the data copy).

ES version: 5.5.0
Cluster size: 5 nodes (4 data nodes)
Shards: ~1700
Current indexing speed: 6000 docs/s (up to 20000)
Storage: 10k rpm disks

**Comment by jpountz** [comment] 2018-05-14 08:51
I never did any serious performance testing with these options but my assumption was that they wouldn't impact indexing performance much since compound files are only applied to small segments and the compound file is written right after the segment has been written, so intermediate files don't have time to make it to the disk, they only live in the filesystem cache.

Do all your 1700 shards receive write operations or are some of them read-only?

I'm also wondering how much memory you give to the filesystem cache and what your `vm.dirty_background_ratio` is.

**Comment by jpountz** [comment] 2018-05-14 08:52
cc @danielmitterdorfer since this is performance/benchmark-related

**Comment by micoq** [comment] 2018-05-14 09:42
@jpountz We have only 96 active shards at a time: 3 daily indices with 16 shards and 1 replica for a total of ~700 GB per day (including replicas).

Each machine have a total of 64 GB (26 GB for the Heap, the rest is for the system and the filesystem cache).
`vm.dirty_background_ratio` is 10%

For the Lucene tests and the `index.compound_on_flush` option, I didn't used this cluster but a single machine with Lucene indices and different sizes for the index buffer : 10kb to 256Mb (however, in this case, I didn't measure the %wait CPU).

**Comment by jpountz** [comment] 2018-05-14 09:49
96 active shards on 4 nodes only actually sounds like too many to me, but this wouldn't explain why you can also reproduce this with your standalone Lucene index.

**Comment by micoq** [comment] 2018-05-18 07:55
We have configured 16 shards per index to distribute the searches more efficiently across all the CPUs (each machine has 40 CPUs). It seems to be the right value in our case since less shards increase the response time (and more shards no longer improve the response time).

I think `index.compound_on_flush` will not influence the storage activity and thus the %wait CPU. Like you explained: the new segments are small and can fit into the filesystem cache (the merged segments are bigger and older, this could explain the influence of `index.compound_format` on the storage activity).

However, the latency could come from the (CPU) time consumed by the bulk threads to create the compound files (`*.cfs`) for re-read and re-write operations.
Correct me if i'm wrong, the compound files are created synchronously in the indexing process by the bulk threads (and merges are asynchronous).

**Comment by micoq** [comment] 2018-05-28 08:05
Well, I launched again my tests on Lucene (7.0.0) with a more precise setup and here are the results for indexing 1 million small documents (~1ko) with various indexing buffer sizes (128kB to 1GB) in a single Lucene index:

Commit: total time after indexing and a full commit (fsync) without using compound format
Commit+Compound: same using compound format
Flush: total time after indexing and after a flush of the remaining documents but before the full commit without compound format
Flush+Compound: same using compound format

<a href="https://ibb.co/ezuCoJ"><img src="https://preview.ibb.co/cRKdTJ/compound.png" alt="compound" border="0"></a>

So, I wonder if I didn't make a mistake in my first setup:
- We can see the compound format doesn't seem to have a big impact on indexing speed for a sufficient indexing buffer size (yellow and green lines). 
- The time consumed by `IndexWriter.commit()` depends on the number of files to write to the filesystem after all operations with `fsync()`. Since the time spent in this syscall seems constant regardless of the file size, the compound format performs better (blue and red lines).

For these tests, I totally disabled the segment merges that's why I have a lot of segments for small indexing buffer sizes.

In all cases, all the index files fit into the filesystem cache (~200MB) so the storage is used only when `fsync()` is called.
The 10% drop I measured the first time could be caused by a lack of filesystem cache (these Lucene-only tests are performed on another hardware).

Finally, enable `index.compound_on_flush` by default seems to be the right choice (at least on a single Lucene index at a time, I didn't perform a concurrent test against multiple threads).

For the `index.compound_format` option, the results are still valid thought (less %wait CPU on big segments).

Here are the raw results (time in seconds):
```
Buffer: 0,128000 MB,    Compound: false, Time: 64295
Buffer: 0,256000 MB,    Compound: false, Time: 32660
Buffer: 0,512000 MB,    Compound: false, Time: 14497
Buffer: 1,000000 MB,    Compound: false, Time: 8451
Buffer: 2,000000 MB,    Compound: false, Time: 5581
Buffer: 4,000000 MB,    Compound: false, Time: 4119
Buffer: 8,000000 MB,    Compound: false, Time: 3437
Buffer: 16,000000 MB,   Compound: false, Time: 3167
Buffer: 32,000000 MB,   Compound: false, Time: 2906
Buffer: 64,000000 MB,   Compound: false, Time: 2970
Buffer: 128,000000 MB,  Compound: false, Time: 3064
Buffer: 256,000000 MB,  Compound: false, Time: 2927
Buffer: 512,000000 MB,  Compound: false, Time: 2952
Buffer: 1024,000000 MB, Compound: false, Time: 2861
Buffer: 0,128000 MB,    Compound: true,  Time: 56452
Buffer: 0,256000 MB,    Compound: true,  Time: 13213
Buffer: 0,512000 MB,    Compound: true,  Time: 6696
Buffer: 1,000000 MB,    Compound: true,  Time: 4728
Buffer: 2,000000 MB,    Compound: true,  Time: 3885
Buffer: 4,000000 MB,    Compound: true,  Time: 3147
Buffer: 8,000000 MB,    Compound: true,  Time: 2984
Buffer: 16,000000 MB,   Compound: true,  Time: 2842
Buffer: 32,000000 MB,   Compound: true,  Time: 2756
Buffer: 64,000000 MB,   Compound: true,  Time: 2749
Buffer: 128,000000 MB,  Compound: true,  Time: 2870
Buffer: 256,000000 MB,  Compound: true,  Time: 2704
Buffer: 512,000000 MB,  Compound: true,  Time: 2789
Buffer: 1024,000000 MB, Compound: true,  Time: 2721

Buffer: 0,128000 MB,    Compound: false, Time: 35086
Buffer: 0,256000 MB,    Compound: false, Time: 2832
Buffer: 0,512000 MB,    Compound: false, Time: 2390
Buffer: 1,000000 MB,    Compound: false, Time: 2458
Buffer: 2,000000 MB,    Compound: false, Time: 2408
Buffer: 4,000000 MB,    Compound: false, Time: 2413
Buffer: 8,000000 MB,    Compound: false, Time: 2513
Buffer: 16,000000 MB,   Compound: false, Time: 2591
Buffer: 32,000000 MB,   Compound: false, Time: 2559
Buffer: 64,000000 MB,   Compound: false, Time: 2461
Buffer: 128,000000 MB,  Compound: false, Time: 2554
Buffer: 256,000000 MB,  Compound: false, Time: 2527
Buffer: 512,000000 MB,  Compound: false, Time: 2480
Buffer: 1024,000000 MB, Compound: false, Time: 2532
Buffer: 0,128000 MB,    Compound: true,  Time: 16476
Buffer: 0,256000 MB,    Compound: true,  Time: 2885
Buffer: 0,512000 MB,    Compound: true,  Time: 2467
Buffer: 1,000000 MB,    Compound: true,  Time: 2420
Buffer: 2,000000 MB,    Compound: true,  Time: 2458
Buffer: 4,000000 MB,    Compound: true,  Time: 2481
Buffer: 8,000000 MB,    Compound: true,  Time: 2527
Buffer: 16,000000 MB,   Compound: true,  Time: 2638
Buffer: 32,000000 MB,   Compound: true,  Time: 2662
Buffer: 64,000000 MB,   Compound: true,  Time: 2663
Buffer: 128,000000 MB,  Compound: true,  Time: 2665
Buffer: 256,000000 MB,  Compound: true,  Time: 2693
Buffer: 512,000000 MB,  Compound: true,  Time: 2636
Buffer: 1024,000000 MB, Compound: true,  Time: 2658
```

**Comment by jpountz** [comment] 2018-05-28 13:10
2600 seconds for 1M small documents sounds very long to me, it is less than 400 documents per second. Is the code that you used to conduct this benchmark available somewhere?

**Comment by micoq** [comment] 2018-05-28 16:10
@jpountz Sorry, the unit was wrong, it's indeed in milliseconds not in seconds !

**Comment by jpountz** [comment] 2018-05-29 15:28
Thank you, so it's actually 400K docs per second. How many threads do you use for indexing and how do you generate your documents?

**Comment by micoq** [comment] 2018-05-30 18:43
I use a single thread. The documents are generated with constant and variable fields just to fill the inverted index.

Here is the piece of code I used:
```
public static void main(String[] args) throws IOException {  

  double[] segSizes = new double[] {
    0.128,
    0.256,
    0.512,
    1.0,
    2.0,
    4.0,
    8.0,
    16.0,
    32.0,
    64.0,
    128.0,
    256.0,
    512.0,
    1024.0
  };
  
  boolean[] useCompoundList = new boolean[] {
      false,
      true
  };
  
  Directory dir = new MMapDirectory(Paths.get("/home/test/test_lucene"));
  
  StringBuilder blob = new StringBuilder();
  for(int i=0; i<1024; ++i) {
    blob.append('a');
  }
  Field blobField = new StringField("blob",blob.toString(),Field.Store.YES);
  
  for(boolean useCompound : useCompoundList) {
    for(double segSize : segSizes) {
      try {
        for(String fileName : dir.listAll()) {
          dir.deleteFile(fileName);
        }
      
      IndexWriterConfig config = new IndexWriterConfig();
      MergePolicy mergePolicy = NoMergePolicy.INSTANCE; // merges are disabled
      config.setMergePolicy(mergePolicy);
      config.setUseCompoundFile(useCompound);
      config.setRAMBufferSizeMB(segSize);

      long startTime = System.nanoTime();
      long endTime = startTime;
      IndexWriter writer = null;
      try {
        writer = new IndexWriter(dir, config);
        for(int i=0;i<1000000;++i) {
          Document doc = new Document();
          doc.add(blobField);
          doc.add(new StringField("field",Integer.toString(i),Field.Store.YES));
          doc.add(new LongPoint("number",i));
          writer.addDocument(doc);
        }
        writer.flush();
        endTime = System.nanoTime();
        writer.commit(); // can be slow with a lot of files
        writer.close();
      }
      catch (IOException e) {
        e.printStackTrace();
      }
      System.out.println(String.format("Buffer: %f MB, Compound: %s, Time: %d",
          config.getRAMBufferSizeMB(),
          config.getUseCompoundFile() ? "true" : "false",
          (endTime-startTime)/1000000
          ));
    }
  }
}
```

**Comment by s1monw** [comment] 2018-06-14 15:41
I mean we can think about making this a size based setting in lucene ie. everything below 10MB we use CFS and otherwise use plain files. I just need some data to reproduce this in order to work on a fix. @micoq

**Comment by s1monw** [comment] 2018-09-04 12:43
we haven't got much feedback I am closing this.

**Closed by s1monw** 2018-09-04 12:43 UTC
Labels: :Core/Core, >enhancement
