### ISSUE TITLE
Add node name to _cat/recovery output

### ISSUE THREAD

**Issue by nemonster** [elastic/elasticsearch#9353] opened 2015-01-19 22:23 UTC
If multiple hosts are running on a single server hostname doesn't provide an accurate picture of the recovery process.  Addition of node name, or at least the ports would differentiate between the different  running processes.

**Comment by cmims** [comment] 2015-03-18 11:41
+1

**Comment by drewr** [comment] 2015-03-18 15:06
:+1: This is true for `_cat/thread_pool` as well. Will fix.

**Comment by drewr** [comment] 2015-03-25 02:38
Duplicate of #8041

**Closed by drewr** 2015-03-25 02:38 UTC
Labels: :CAT API, adoptme, enhancement, low hanging fruit, v1.6.0, v2.0.0
