### ISSUE TITLE
failed to parse date field after upgrade to 7.11.x from 7.10.2

### ISSUE THREAD

**Issue by Robert-Saiter** [elastic/elasticsearch#69382] opened 2021-02-22 19:51 UTC
We are getting the following error after upgrading from 7.10.2 to 7.11.0 (subsequent update to 7.11.1 did not resolve the issue).

`failed to parse date field [1.613970929E12] with format [strict_date_optional_time||epoch_millis]`

Mapping is basic and remains unchanged from 7.10.2 configuration. 

Fields throwing the error.... 
```       
        "ProcTime": {
          "type": "date",
          "store": true
        },
        "RcvTime": {
          "type": "date",
          "store": true
        }
```

We have multiple deployments and only the ones upgraded to 7.11.x are having this issue. 

Since nothing on our end changed and I didn't see anything in the 7.11.x breaking changes or release notes I am posting here.  Please let me know what I can provide to assist with reproducing or identifying the issue. 

Thank you

**Comment by mayya-sharipova** [comment] 2021-02-22 22:19
@Robert-Saiter Thank you for submitting the issue.
If you have a stack trace, can you please post it here.
If not, it would be helpful to know when does this error happen (are you trying to run some query?).

**Comment by Robert-Saiter** [comment] 2021-02-22 22:27
My apologies, hopefully I did not post in the wrong location.  This issue occurs only in Kibana when attempting to pull any data from our existing indexes while on the 7.11.x versions.  I posted the error displayed in Kibana above, I can retrieve further logs or info as requested.

**Comment by rjernst** [comment] 2021-02-23 01:35
Using epoch times in scientific notation was deprecated in 6.6. This was a feature of Joda time that was not carried over into Java time. So it would seem you are using Java dates, though that would have been expected in 7.10 as well (we started using java dates in 7.0 by default).

As Mayya mentioned, the Elasticsearch log messages for the failure would be necessary for us to investigate at all.

/cc @pgomulka

**Comment by Robert-Saiter** [comment] 2021-02-25 05:50
Thank you, I will close this out as it is working as intended.  I've notified my internal team about this change and they will need to correct it on their end.  I appreciate you taking a look and providing me with these details so quickly.

**Comment by pgomulka** [comment] 2021-03-02 08:51
@Robert-Saiter can you please report back to use what was causing this on your end? I would like to investigate this more closely but I am not sure how to reproduce this.
Thank you

**Comment by nik9000** [comment] 2021-03-08 17:43
We've tracked down a bug from where if you send a `date` or `date_nanos` in like `12345.123456` we will bump into this issue if try to fetch the date with `fields`. #70040 silences the exception but leaves a loss of precision. You can read up on what the loss looks like over there. I *think* that is what is going on here - kibana uses the `fields` API with `date` and `date_nanos` fields in 7.11.

**Comment by nik9000** [comment] 2021-03-08 17:44
I've marked #70040 as closing this one because I'm *fairly* sure this is about the `fields` API for that format.

**Closed** 2021-03-08 20:54 UTC
Labels: :Core/Infra/Core, >bug, Team:Core/Infra
