### ISSUE TITLE
BUG: Bucket Script Aggregation

### ISSUE THREAD

**Issue by DoychinDoychev** [elastic/elasticsearch#21579] opened 2016-11-15 19:40 UTC
Hi there,

I think there is a bug in _Bucket Script Aggregation_. I have two examples - one working and the other one is not.

**WORKING EXAMPLE**
```
{
  "size": 0,
  "aggs": {
    "time": {
      "date_histogram": {
        "field": "startTime",
        "interval": "day"
      }, 
      "aggs": {
        "dislike": {
          "filter" : { "term": { "type": "Dislike" } },
          "aggs": {
            "dislike-values": {
              "value_count" : { 
                "script" : {
                  "inline" : "doc",
                  "lang" : "groovy"
                }
              } 
            }
          }
        },
        "follow": {
          "filter" : { "term": { "type": "Follow" } },
          "aggs": {
            "follow-values": {
              "value_count" : { 
                "script" : {
                  "inline" : "doc",
                  "lang" : "groovy"
                }
              } 
            }
          }
        },
        "connected_users": {
          "bucket_script": {
            "buckets_path": {
              "follow": "follow>follow-values",
              "dislike": "dislike>dislike-values"
            },
            "script": "follow - dislike",
            "gap_policy": "insert_zeros"
          }
        }
        
      }
    }
  }
}
``` 
NOTICE 
```      
"date_histogram": {
        "field": "startTime",
        "interval": "day"
      }, 
```

**NOT WORKING**
```
{
  "size": 0,
  "aggs": {
    "time": {
      "date_range": {
        "field": "startTime",
          "ranges": [
              { 
                "to": "now-1d"
              }, 
              { 
                "to": "now-2d"
              }
            ]
      },
      "aggs": {
        "dislike": {
          "filter" : { "term": { "type": "Dislike" } },
          "aggs": {
            "dislike-values": {
              "value_count" : { 
                "script" : {
                  "inline" : "doc",
                  "lang" : "groovy"
                }
              } 
            }
          }
        },
        "follow": {
          "filter" : { "term": { "type": "Follow" } },
          "aggs": {
            "follow-values": {
              "value_count" : { 
                "script" : {
                  "inline" : "doc",
                  "lang" : "groovy"
                }
              } 
            }
          }
        },
        "connected_users": {
          "bucket_script": {
            "buckets_path": {
              "follow": "follow>follow-values",
              "dislike": "dislike>dislike-values"
            },
            "script": "follow - dislike",
            "gap_policy": "insert_zeros"
          }
        }
      }
    }
  }
}
```
NOTICE
```
      "date_range": {
        "field": "startTime",
          "ranges": [
              { 
                "to": "now-1d"
              }, 
              { 
                "to": "now-2d"
              }
            ]
      },
```
this gives 
```
{
   "error": {
      "root_cause": [],
      "type": "reduce_search_phase_exception",
      "reason": "[reduce] ",
      "phase": "fetch",
      "grouped": true,
      "failed_shards": [],
      "caused_by": {
         "type": "null_pointer_exception",
         "reason": null
      }
   },
   "status": 503
}
```
in Sense.

**Comment by s1monw** [comment] 2016-11-16 08:20
can you tell what version of ES are you using and can you paste the stacktrace from the logs please

**Comment by DoychinDoychev** [comment] 2016-11-16 18:34
Thanks for the reply,

I actually missed the block causing the issue in the `NOT WORKING` example

```
"connected_users": {
          "bucket_script": {
            "buckets_path": {
              "follow": "follow>follow-values",
              "dislike": "dislike>dislike-values"
            },
            "script": "follow - dislike",
            "gap_policy": "insert_zeros"
          }
        }
```
this is the update that i made.

ES traceback:
```
[2016-11-16 18:28:54,950][WARN ][rest.suppressed          ] path: /activity/stream/_search, params: {index=activity, type=stream}
Failed to execute phase [fetch], [reduce]
        at org.elasticsearch.action.search.SearchQueryThenFetchAsyncAction$2.onFailure(SearchQueryThenFetchAsyncAction.java:146)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at org.elasticsearch.search.aggregations.bucket.range.date.InternalDateRange$Factory.createBucket(InternalDateRange.java:141)
        at org.elasticsearch.search.aggregations.bucket.range.date.InternalDateRange$Factory.createBucket(InternalDateRange.java:115)
        at org.elasticsearch.search.aggregations.bucket.range.InternalRange.createBucket(InternalRange.java:286)
        at org.elasticsearch.search.aggregations.bucket.range.InternalRange.createBucket(InternalRange.java:43)
        at org.elasticsearch.search.aggregations.pipeline.bucketscript.BucketScriptPipelineAggregator.reduce(BucketScriptPipelineAggregator.java:141)
        at org.elasticsearch.search.aggregations.InternalAggregation.reduce(InternalAggregation.java:155)
        at org.elasticsearch.search.aggregations.InternalAggregations.reduce(InternalAggregations.java:170)
        at org.elasticsearch.search.controller.SearchPhaseController.merge(SearchPhaseController.java:411)
        at org.elasticsearch.action.search.SearchQueryThenFetchAsyncAction$2.doRun(SearchQueryThenFetchAsyncAction.java:132)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        ... 3 more
```

ES version: `2.4.0`

**Comment by s1monw** [comment] 2016-11-16 20:49
@colings86 can you take a look at this please

**Comment by colings86** [comment] 2016-11-17 09:45
@s1monw sure

**Comment by DoychinDoychev** [comment] 2016-11-17 13:30
thanks guys! :)

**Comment by colings86** [comment] 2016-11-18 12:27
I have reproduced this on 2.4.0 with the following script:
```js
DELETE test

PUT test
{
    "settings": {
        "number_of_shards": 1,
        "number_of_replicas": 0
    },
    "mappings": {
      "doc": {
        "properties": {
          "d": {
            "type": "date"
          }
        }
      }
    }
}

POST test/doc/1
{
    "a": 1,
    "b": 1,
    "c": 2,
    "d": "2016-11-18"
}

POST test/doc/2
{
    "a": 2,
    "b": 1,
    "c": 2,
    "d": "2016-11-17"
}

POST test/doc/3
{
    "a": 3,
    "b": 1,
    "c": 2,
    "d": "2016-11-16"
}

POST test/doc/4
{
    "a": 4,
    "b": 1,
    "c": 2,
    "d": "2016-11-15"
}

GET test/_search
{
    "size": 0,
    "aggs": {
      "range": {
        "date_range": {
          "field": "d",
          "ranges": [
            {
              "to": "now-1d/d"
            },
            {
              "from": "now-1d/d"
            }
          ]
        },
        "aggs": {
          "b": {
            "avg": {
              "field": "b"
            }
          },
          "c": {
            "avg": {
              "field": "c"
            }
          },
          "diff": {
            "bucket_script": {
              "buckets_path": {
                "b": "b",
                "c": "c"
              },
              "script": {
                "inline": "c - b"
              }
            }
          }
        }
      }
    }
}
```

The bug is in this snippet of `InternalDateRange`:
```java
@Override
        public Bucket createBucket(InternalAggregations aggregations, Bucket prototype) {
            return new Bucket(prototype.getKey(), ((Number) prototype.getFrom()).doubleValue(), ((Number) prototype.getTo()).doubleValue(),
                    prototype.getDocCount(), aggregations, prototype.getKeyed(), prototype.getFormatter());
        }
```

The problem is that the `createBucket` method does not account for the case where either `from` or `to` are `null` in the prototype and so will throw a `NullPointerException` in this case.

In 5.0.0 onwards this is not an issue (and so not reproducible) as the range aggregation stores an explicit `Double` rather than an `Object` that need to be cast to a `Number` to get its `double` value

**Comment by clintongormley** [comment] 2016-11-19 13:09
Closed by https://github.com/elastic/elasticsearch/pull/21659

**Closed by clintongormley** 2016-11-19 13:09 UTC
Labels: feedback_needed
