### ISSUE TITLE
whitespace allowed in template field name

### ISSUE THREAD

**Issue by podollb** [elastic/elasticsearch#14033] opened 2015-10-08 17:21 UTC
If I `PUT` this template definition to `http://localhost:9200/_template/my_new_template` it works, but notice the field name `"some_field "` actually has a trailing whitespace in the String (I think that should be trimmed).

```json
{
  "template": "some_index_*",
  "mappings": {
    "some_mapping": {
      "properties": {
        "some_field ": {
          "type": "double"
        }
      }
    }
  }
}
```

**Comment by clintongormley** [comment] 2015-10-13 07:03
Agreed - closing as duplicate of #9059

**Closed by clintongormley** 2015-10-13 07:03 UTC
