### ISSUE TITLE
Computing average shows wrong value

### ISSUE THREAD

**Issue by CristianWeiland** [elastic/elasticsearch#23108] opened 2017-02-10 13:09 UTC
**Elasticsearch version**: 5.2.0

**JVM version**: openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2~bpo8+1-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)

**OS version**: Debian 8.7

I am using the official Docker container 5.2.

**Description of the problem**:

Using Data table visualization in Kibana, I want to get the average value of a number field. When an extra filter is applied, which results in only one row, the average looks correct, but without extra filters, it seems like ElasticSearch does not search all documents in the date range.

**Screenshot without filters**:
![data_without_filters](https://cloud.githubusercontent.com/assets/12500687/22827130/63340f22-ef7d-11e6-8c48-f0aa84004032.png)

**Screenshot using Name as filter** (note that documents retrieved went from 2 to 94 on the **Count** column):
![data_with_filter](https://cloud.githubusercontent.com/assets/12500687/22827200/af4f6a6e-ef7d-11e6-9be6-a771adc94a09.png)

**Request** without filters (first screenshot):
```
{
  "query": {
    "bool": {
      "must": [
        {
          "query_string": {
            "query": "*",
            "analyze_wildcard": true
          }
        },
        {
          "range": {
            "@timestamp": {
              "gte": 1328876530691,
              "lte": 1486729330691,
              "format": "epoch_millis"
            }
          }
        }
      ],
      "must_not": []
    }
  },
  "size": 0,
  "_source": {
    "excludes": []
  },
  "aggs": {
    "2": {
      "terms": {
        "field": "NOME.keyword",
        "size": 10,
        "order": {
          "1": "desc"
        }
      },
      "aggs": {
        "1": {
          "avg": {
            "field": "REMUNERAÇÃO APÓS DEDUÇÕES OBRIGATÓRIAS (R$)"
          }
        }
      }
    }
  }
}
```
**Response** without filters (first screenshot):
```
{
  "took": 29,
  "timed_out": false,
  "_shards": {
    "total": 235,
    "successful": 235,
    "failed": 0
  },
  "hits": {
    "total": 366968,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "2": {
      "doc_count_error_upper_bound": -1,
      "sum_other_doc_count": 366956,
      "buckets": [
        {
          "1": {
            "value": 52272
          },
          "key": "CARLOS JOSE DE MESQUITA SIQUEIRA",
          "doc_count": 2
        },
        {
          "1": {
            "value": 44516
          },
          "key": "CLAUDIR JOSE DALTOE",
          "doc_count": 1
        },
        {
          "1": {
            "value": 37745
          },
          "key": "DIONE MARIA MENZ",
          "doc_count": 1
        },
        {
          "1": {
            "value": 36270
          },
          "key": "PAULO DA CUNHA LANA",
          "doc_count": 1
        },
        {
          "1": {
            "value": 36081
          },
          "key": "LUIZ PEREIRA RAMOS",
          "doc_count": 1
        },
        {
          "1": {
            "value": 35154
          },
          "key": "CARLOS EDUARDO PILLEGGI DE SOUZA",
          "doc_count": 1
        },
        {
          "1": {
            "value": 35017
          },
          "key": "ALBERTO PIO FIORI",
          "doc_count": 1
        },
        {
          "1": {
            "value": 34044
          },
          "key": "PAULO HENRIQUE TROMBETA ZANIN",
          "doc_count": 1
        },
        {
          "1": {
            "value": 33876
          },
          "key": "THELMA ALVIM VEIGA LUDWIG",
          "doc_count": 2
        },
        {
          "1": {
            "value": 33775
          },
          "key": "ANDREA KNABEM",
          "doc_count": 1
        }
      ]
    }
  },
  "status": 200
}
```

**Request** with name filters (second screenshot):
```
{
  "query": {
    "bool": {
      "must": [
        {
          "query_string": {
            "query": "*",
            "analyze_wildcard": true
          }
        },
        {
          "match": {
            "NOME.keyword": {
              "query": "CARLOS JOSE DE MESQUITA SIQUEIRA",
              "type": "phrase"
            }
          }
        },
        {
          "range": {
            "@timestamp": {
              "gte": 1328876577929,
              "lte": 1486729377929,
              "format": "epoch_millis"
            }
          }
        }
      ],
      "must_not": []
    }
  },
  "size": 0,
  "_source": {
    "excludes": []
  },
  "aggs": {
    "2": {
      "terms": {
        "field": "NOME.keyword",
        "size": 10,
        "order": {
          "1": "desc"
        }
      },
      "aggs": {
        "1": {
          "avg": {
            "field": "REMUNERAÇÃO APÓS DEDUÇÕES OBRIGATÓRIAS (R$)"
          }
        }
      }
    }
  }
}
```

**Response** with name filter (second screenshot):
```
{
  "took": 45,
  "timed_out": false,
  "_shards": {
    "total": 235,
    "successful": 235,
    "failed": 0
  },
  "hits": {
    "total": 94,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "2": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 0,
      "buckets": [
        {
          "1": {
            "value": 12990.489361702128
          },
          "key": "CARLOS JOSE DE MESQUITA SIQUEIRA",
          "doc_count": 94
        }
      ]
    }
  },
  "status": 200
}
```

This issue has been created in Kibana [here](https://github.com/elastic/kibana/issues/5265), but already closed by @rashidkpc , who said it was a bug in ElasticSearch.

**Comment by dpasqualin** [comment] 2017-02-10 13:36
Same here.

**Comment by jpountz** [comment] 2017-02-10 14:57
Terms aggregations might indeed be very inaccurate when sorting by anything else than `_term:asc`, `_term:desc` or `_count:desc`. This issue will likely never be fixed and an option that has been discussed in the past was rather to drop the ability to sort by sub aggregations, or at least restrict it. Sorting by sub `avg` aggregations is probably one of the worst-case scenarii.

Closing as a duplicate of #17588.

**Closed by jpountz** 2017-02-10 14:57 UTC
