### ISSUE TITLE
Strange behaviour when trying to index geo_shape polygon over dateline

### ISSUE THREAD

**Issue by rsmith013** [elastic/elasticsearch#26286] opened 2017-08-18 15:04 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 5.5.1

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_141

**OS version** (`uname -a` if on a Unix-like system): GNU/Linux

**Description of the problem including expected versus actual behavior**:

When trying to index a geo_shape which crosses the dateline am getting intersection errors. 80% of the issues were solved by subtracting a small amount (1e10^-14) from any value which lies directly on +/-180°. There were no intersections here either but ES seemed to not like the value 180.0.  There are still a few shapes which won't go in. I have investigated to see if there are any intersections and can't find any. Translating the shape to meridian using +180 on -ve values and -180 on +ve values allows it to go in so it is solely a dateline issue. 

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. PUT /test-index
```json
{
   "mappings": {
      "geo_metadata": {
         "_all": {
            "enabled": true
         },
         "properties": {
            "spatial": {
               "properties": {
                  "geometries": {
                     "properties": {
                        "search": {
                           "type": "geo_shape",
                           "tree": "quadtree",
                           "precision": "8km"
                        }
                     }
                  }
               }
            }
         }
      }
   }
}

```
 2. PUT /test-index/geo_metadata/1
```json
{
        "spatial": {
            "geometries": {
                "search":{
                    "coordinates": [[[179.99999999999, -72.661870459646082], [-179.92242898523259, -72.614739463963019], [-179.70509673080812, -72.48077664056396], [-179.49092755066465, -72.346619319446333], [-179.27982991402556, -72.212217663440484], [-179.0801618967584, -72.082942320949627], [-179.91362724448533, -72.077340115037259], [179.99999999999, -72.595885626443078], [179.98777151047784, -72.669300308135334], [179.99999999999, -72.661870459646082]]],
                    "orientation": "counterclockwise",
                    "type": "polygon"
                }
            }
        }
}

```

**Comment by jimczi** [comment] 2017-08-21 07:09
@nknize can you take a look ?

**Comment by imotov** [comment] 2018-12-12 14:47
The error message is generated inside JTS validation that fails on `LINEARRING (-179.92242898523259 -72.61473946396302, -179.70509673080812 -72.48077664056396, -179.49092755066465 -72.34661931944633, -179.27982991402556 -72.21221766344048, -179.0801618967584 -72.08294232094963, -179.91362724448533 -72.07734011503726, 179.99999999999 -72.59588562644308, 179.98777151047784 -72.66930030813533, 179.99999999999 -72.66187045964608, -179.92242898523259 -72.61473946396302)` that we pass to it, which is indeed self-intersecting if you treat it clockwise. Since this code path is going away as a result of #32039, it makes sense to wait for it. 

Saying that I tried this shape in #35320 and got the error:

```
[elasticsearch] Caused by: java.lang.IllegalArgumentException: Unable to Tessellate shape [[-72.61473946396302, -179.92242898523259] [-72.48077664056396, -179.70509673080812] [-72.34661931944633, -179.49092755066465] [-72.21221766344048, -179.27982991402556] [-72.08294232094963, -179.0801618967584] [-72.07734011503726, -179.91362724448533] [-72.59588562644308, 179.99999999999] [-72.66930030813533, 179.98777151047784] [-72.66187045964608, 179.99999999999] [-72.61473946396302, -179.92242898523259] ]. Possible malformed shape detected.
[elasticsearch]         at org.apache.lucene.geo.Tessellator.tessellate(Tessellator.java:115) ~[lucene-sandbox-8.0.0-snapshot-61e448666d.jar:8.0.0-snapshot-61e448666d 61e448666d56c20c37dfb825ec14ffe697d000ff - nhat - 2018-12-11 18:10:56]
[elasticsearch]         at org.apache.lucene.document.LatLonShape.createIndexableFields(LatLonShape.java:72) ~[lucene-sandbox-8.0.0-snapshot-61e448666d.jar:8.0.0-snapshot-61e448666d 61e448666d56c20c37dfb825ec14ffe697d000ff - nhat - 2018-12-11 18:10:56]
[elasticsearch]         at org.elasticsearch.index.mapper.GeoShapeFieldMapper.indexShape(GeoShapeFieldMapper.java:134) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.index.mapper.GeoShapeFieldMapper.parse(GeoShapeFieldMapper.java:117) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
```
So, it looks like the issue migrated to the new system as well somehow.

**Comment by imotov** [comment] 2018-12-13 15:07
I've done some more digging here. Basically, it fails if a non self-intersecting counterclockwise polygon that is crossing the dateline self-intersects if you treat is as clockwise. The simples reproduction I could come up with is:

```
DELETE test-index

PUT /test-index
{
  "mappings": {
    "_doc": {
      "properties": {
        "shape": {
          "type": "geo_shape"
        }
      }
    }
  }
}

PUT /test-index/_doc/1
{
  "shape": {
    "coordinates": [[[180, -10], [-170, -5], [-170, 15], [170, -15], [180, -10]]],
    "type": "polygon"
  }
}
```
Interestingly enough, if I specify ` "orientation": "clockwise",` it actually indices fine.
```
PUT /test-index/_doc/1
{
  "shape": {
    "coordinates": [[[180, -10], [-170, -5], [-170, 15], [170, -15], [180, -10]]],
    "orientation": "clockwise",
    "type": "polygon"
  }
}
```

**Comment by imotov** [comment] 2018-12-20 20:52
This is still an issue with #35320, only the error message changed:

```
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "failed to parse field [shape] of type [geo_shape]"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "failed to parse field [shape] of type [geo_shape]",
    "caused_by": {
      "type": "illegal_argument_exception",
      "reason": "Unable to Tessellate shape [[-10.0, 180.0] [-5.0, -170.0] [15.0, -170.0] [-15.0, 170.0] [-10.0, 180.0] ]. Possible malformed shape detected."
    }
  },
  "status": 400
}
```

@iverase what do you think?

**Comment by dwilson1988** [comment] 2020-10-22 15:16
Running into this currently on version 7.9.2, is the best workaround to fix the geometry by changing the orientation before indexing?

**Comment by iverase** [comment] 2020-10-23 11:24
Hi @dwilson1988,

thanks to bringing back this issue to our attention. I had a deeper look into the issue and I found out the problem. Currently for some polygons we seem to compute wrongly the orientation. I have just open a PR to fix the issue. 

Changing the orientation can solve your issue now but it will fail once the fix is in place so you need to be careful.

**Comment by dwilson1988** [comment] 2020-10-23 17:09
Just to confirm, if my geometries are RFC7946 compliant, I should be okay, right?

**Closed** 2020-10-28 08:00 UTC
Labels: :Analytics/Geo, >bug, Team:Analytics
