### ISSUE TITLE
The Update API examples result in invalid_type_name_exception

### ISSUE THREAD

**Issue by cwright-onshape** [elastic/elasticsearch#43643] opened 2019-06-26 14:47 UTC
**Elasticsearch version** (`bin/elasticsearch --version`):docker.elastic.co/elasticsearch/elasticsearch:6.7.2

**Plugins installed**: None

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):MacOS 10.14.4

**Description of the problem including expected versus actual behavior**:
Provided examples for the update api in the documentation fail with:
"root_cause" : [
      {
        "type" : "invalid_type_name_exception",
        "reason" : "Document mapping type name can't start with '_', found: [_update]"
      }
    ]
**Steps to reproduce**:

Using the provided examples on either this page:
https://www.elastic.co/guide/en/elasticsearch/reference/current/getting-started-update-documents.html
or this page:
https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html

The "Copy as CURL" fails:

curl -X POST "localhost:9200/customer/_update/1?pretty" -H 'Content-Type: application/json' -d'
> {
>   "doc": { "name": "Jane Doe" }
> }
> '
{
  "error" : {
    "root_cause" : [
      {
        "type" : "invalid_type_name_exception",
        "reason" : "Document mapping type name can't start with '_', found: [_update]"
      }
    ],
    "type" : "invalid_type_name_exception",
    "reason" : "Document mapping type name can't start with '_', found: [_update]"
  },
  "status" : 400
}

**Comment by chenkv** [comment] 2019-06-26 22:18
You need to create a document with _id=1 first like below:
` curl -X PUT "localhost:9200/customer/_doc/1" -H 'Content-Type: application/json' -d'
{
"doc": { "name": "Jane Doe 0" }
}'
`
then you can update with id = 1; otherwise the id is auto generated

**Comment by henningandersen** [comment] 2019-06-27 07:01
@cwright-onshape thanks for your interest in elasticsearch. I notice that you are using elasticsearch version 6.7.2, but using the "current" documentation, which is currently for version 7.2. Version 6.7 does not support the new typeless endpoint for the `_update` API. See [6.7 documentation](https://www.elastic.co/guide/en/elasticsearch/reference/6.7/docs-update.html) for the correct examples for your version. I would recommend to always ensure that the documentation consulted is for the specific version in use.

Given that this works as intended and the docs look correct, I am closing this issue.

**Closed by henningandersen** 2019-06-27 07:01 UTC
