### ISSUE TITLE
_xpack/rollup/job doesn't work correctly

### ISSUE THREAD

**Issue by jdu-mydevices** [elastic/elasticsearch#32446] opened 2018-07-27 21:30 UTC
**Elasticsearch version** (`6.3.0`):

**Plugins installed**: [_xpack]

**JVM version** (`1.8.0_161-b14`):

**OS version** (`Linux 3.10.0-327.10.1.el7.x86_64`):

**Description of the problem including expected versus actual behavior**:
1). Firstly, I have a job to rollup data with `"interval": "1m"`
```
PUT _xpack/rollup/job/rollup_data_minutes_job
{
    "index_pattern": "data*",
    "rollup_index": "rollup_data_minutes",
    "cron": "* */5 * * * ?",
    "page_size" :1000,
    "groups" : {
      "date_histogram": {
        "field": "created_at",
        "interval": "1m",
        "time_zone": "UTC"
      },
      "terms": {
        "fields": ["account_id", "data_id"]
      }
    },
    "metrics": [
        {
            "field": "value",
            "metrics": ["sum"]
        }
    ]
}
```
2). After that, I have another job to rollup the created indices in step `1)`
```
PUT _xpack/rollup/job/rollup_data_hours_job
{
    "index_pattern": "rollup_data_minutes*",
    "rollup_index": "rollup_data_hours",
    "cron": "* */30 * * * ?",
    "page_size" :1000,
    "groups" : {
      "date_histogram": {
        "field": "created_at.date_histogram.timestamp",
        "interval": "1h",
        "time_zone": "UTC"
      },
      "terms": {
        "fields": ["account_id.terms.value", "data_id.terms.value"]
      }
    },
    "metrics": [
        {
            "field": "value.sum.value",
            "metrics": ["sum"]
        }
    ]
}
```

**Problem**
The job can be created correctly but no result returned when searching it.
I've confirmed that the `rollup_data_minutes` index returned several millions of data.
```
POST /rollup_data_hours/_search
{
      "query": {
        "match_all": {}
      }
}
```
```
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 0,
    "max_score": null,
    "hits": []
  }
}
```

Also, I hope the result of metrics `"avg"` can also return the `"sum"` value in the result. now I can get `_count` only, so need to use the sum directly and then use `sum`/`count` to get the average.
```
    "metrics": [
        {
            "field": "value",
            "metrics": ["avg"]
        }
    ]
```

**Comment by jdu-mydevices** [comment] 2018-07-31 00:31
I searched the index again today, got some rollup result. I don't know when these result created.
If I recreate the index using another name `rollup_data_hours1`, after executed `GET _xpack/rollup/job/_all`,
I got 
```
      "stats": {
        "pages_processed": 490,
        "documents_processed": 405231,
        "rollups_indexed": 15543,
        "trigger_count": 473
      }
```

But I tried several times of search, no data returned.
```
GET /rollup_data_hours1/_search
{
      "query": {
        "match_all": {}
      }
}
```

Maybe it's an timing issue?
How often will the job executed when `"cron": "* */5 * * * ?"`?

**Comment by polyfractal** [comment] 2018-07-31 12:41
Hi @jdu-mydevices, I think the issue is just with the cron schedules.  Rollup uses the same [cron scheduling system as Watcher](https://www.elastic.co/guide/en/watcher/current/trigger.html#schedule-cron).  So you're two cron schedules are:

- `* */5 * * * ?` : every five minutes
- `* */30 * * * ?` : every 30 minutes

When you create a job, it is created in a "paused" state (`stopped` is the status if you were to check the GetJobs API).  The job is created, can be interacted with, but isn't doing anything right now.

After you start the job with the StartJob API, it moves to `started` state, but it isn't actively indexing yet.  It won't begin indexing until the cron is triggered (and the state will become `indexing`). So in this case, they won't start executing until five and 30 minutes after you started the job.

Does that help?

> Also, I hope the result of metrics "avg" can also return the "sum" value in the result. now I can get _count only, so need to use the sum directly and then use sum/count to get the average.

Unfortunately, right now Rollup can't do this.  It would be an obvious optimization to make in the future, but we skipped it in the first release for simplicity.  If you want the other metrics (`sum`, etc) you'll have to explicitly include it in the config too.

**Comment by jdu-mydevices** [comment] 2018-07-31 17:46
Thanks @polyfractal!
Yeah, I know the schedules are 5 minutes and 30 minutes. But the problem was there were no indices created even after I waited several hours. I think there maybe some issues in the schedule. I'll try a newer version. Or maybe multiple jobs caused the issue. I'll clear all the jobs and indices and test again. 
I'm sure the jobs were started because when running the start command, I got the error `reason": "Cannot start task for Rollup Job [rollup_data_hours_job] because state was [STARTED]"
  }`.

**Comment by polyfractal** [comment] 2018-07-31 21:45
Hm ok, I agree it'd be best to start with a fresh cluster (delete all the jobs, remove all the rollup indices) and see if you can recreate it.  If you can find something that reproduces please paste the sequence of commands here and I'll investigate.  Definitely want to check it out if you've found a bug! A reproducible example would help a bunch.

Thanks!

Note: it's possible for rollup jobs to point to the same rollup index, so perhaps the jobs were accidentally pointing to the same location and that's why it looked like the rollup index was never created?

**Comment by jdu-mydevices** [comment] 2018-08-01 01:39
Seems it's a bug. I reproduced it again after deleted all the jobs and indices.
And I am sure two jobs were started normally.
I'll confirm again to see if the rollup result created.
There is no other special scripts, just what I posted above.
```
POST _xpack/rollup/job/rollup_data_minutes_job/_start
{
  "started": true
}
POST _xpack/rollup/job/rollup_data_hours_job/_start
{
  "started": true
}
```

**Comment by polyfractal** [comment] 2018-08-01 15:52
I just noticed that you are rolling up a rollup index:  `"index_pattern": "rollup_data_minutes*",`

This is _technically_ possible today, but I would consider it an anti-pattern.  The fields/naming conventions inside of rollup docs are internal conventions, and liable to change if we ever need to reconfigure how data is stored.  That's why we provide the `_rollup_search` endpoint, to translate our internal conventions into something useful.

If you want both minute and hourly rollups, just configure two rollup jobs on the source data with the appropriate intervals.  I would not recommend rolling up a rollup index.  We may officially support that in the future, or may make it explicitly disallowed.  In either case it isn't tested right now.

**Comment by jdu-mydevices** [comment] 2018-08-01 16:30
Yes, I've tried configure two rollup jobs on the source data and it was working. But because the source data have about 8billion indicies, I think it will save some time to rollup hourly data based on minute rollups. Since what I am trying to do is not officially support, I will configure multiple jobs on the source data.
thanks @polyfractal!

**Comment by polyfractal** [comment] 2018-08-01 16:46
Noted!  We're waiting to decide if we should officially support "chaining" jobs together like you did, depending on how many people request the feature.  Or perhaps jobs that accept multiple intervals and internally do the same thing.  

So this is a useful data point, although I am sorry it isn't working for you right now.

If the jobs are going too slow, you might consider raising the `page_size`.  This controls how many buckets we ask the composite aggregation to return.  As long as you have sufficient memory on the node, a larger page size should help speed up the jobs.

I'm going to go ahead and close this issue, but feel free to re-open if you run into problems with the regular jobs!

**Closed by polyfractal** 2018-08-01 16:46 UTC
Labels: :Search/Rollup
