### ISSUE TITLE
Term aggregation on rollup index require large size parameter to provide accurate results

### ISSUE THREAD

**Issue by nikhil-bhat** [elastic/elasticsearch#44998] opened 2019-07-30 10:05 UTC
**Elasticsearch version** 6.6.1

**Plugins installed**: 

| plugin name | version | description 
| --- | --- | ---
| opendistro_sql | v0.8.0.0 | Open Distro for Elasticsearch SQL
| search-guard-6 | v6.6.2-24.3 | Provide access control related features for Elasticsearch 6

**JVM version** Java HotSpot(TM) 64-Bit Server VM (1.8.0_172):

**OS version** Linux

**Term aggregation on rollup index require large size parameter to provide accurate results**:

**Steps to reproduce**:
1.) Create rollup index from index pattern
2.) Perform term aggregation on actual index
3.) Perfom term aggregation on rolled up index
4.) Observe huge discrepancy in top 5 terms
5.) Increase term aggregation size to 1000 for example.
6.) Accurate results are seen afterwards 

here are some discuss links describing the same bug [rollup bug](https://discuss.elastic.co/t/problem-in-terms-aggregation-result-buckets-in-rollup-search/191651)

**Comment by jimczi** [comment] 2019-07-30 12:31
By default the bucket of the `terms` aggregation are sorted by doc count. Documents in the rollup index are an aggregate of multiple documents but when running a `terms` aggregation one occurence of a term counts as a single document. So even if the rollup documents is the result of a merge of thousands of documents, the terms present in the document will be counted as if they appear only once. We record the number of aggregated document in rollup doc so it is possible to perform a `sum` over this field (`$fieldName.terms._count`) and use this metric to sort the buckets:
`````
POST /rolled_index/_rollup_search
{
    "aggregations": {
        "the_terms": {
            "terms": {
                "field": "$field_name.terms.value",
                "order": {
                    "rollup_doc_count": "desc"
                }
            },
            "aggregations": {
                "rollup_doc_count": {
                    "sum": {
                        "field": "foo.terms._count"
                    }
                }
            }
        }
    }
}
````
However I think that this rewriting should be applied automatically in the `rollup_search` endpoint since it is the expected behavior and users should not need to know about the internals.
Another option that we discussed with @polyfractal would be to allow aggregations to use metadata field to retrieve the doc count of each document. If we apply this change to all our metrics/buckets aggregation we'd not need the `rollup_search` endpoint and the support for rollup would be directly integrated in the aggregation framework.

**Comment by polyfractal** [comment] 2019-07-30 15:32
> However I think that this rewriting should be applied automatically in the rollup_search endpoint since it is the expected behavior and users should not need to know about the internals.

++ we should absolutely do this, I think it's a bug that we don't (and too much to ask the user to add a sort on their own).  I can work on a fix.  

Even if we do go with the second plan mentioned by Jim I think we should fix this in the mean time.

**Comment by rokcarl** [comment] 2020-10-22 11:59
I hit this bug today as well.

I've done a date histogram with a split series by the customer name.

<details><summary>Doing a `Terms` aggregation with a large `size` works fine:</summary>

Raw index:
<img width="1524" alt="Screenshot 2020-10-22 at 10 24 23" src="https://user-images.githubusercontent.com/42874/96868078-d6a41380-146d-11eb-82df-aa6490e57157.png">

Rolled-up index:
<img width="1534" alt="Screenshot 2020-10-22 at 10 41 32" src="https://user-images.githubusercontent.com/42874/96868119-e4599900-146d-11eb-8b45-aff22f1c68fe.png">

</details>
<details><summary>Doing a `Terms` aggregation with a small `size` fails for the rolled-up index:</summary>

Raw index:
<img width="1529" alt="Screenshot 2020-10-22 at 10 26 21" src="https://user-images.githubusercontent.com/42874/96868317-271b7100-146e-11eb-8e10-ceb66e3643e2.png">

Rolled-up index:
<img width="1526" alt="Screenshot 2020-10-22 at 10 32 58" src="https://user-images.githubusercontent.com/42874/96868328-2da9e880-146e-11eb-8a22-d9874729667a.png">


</details>

As you can see above, the values for the top results on the rolled-up index are way off. There is an option on the raw index in Kibana to do `Group other values in separate bucket`. If this was possible on the rollup index as well, this would "solve" the issue for me as I would always then select it and I'm sure the data would be fine. Not sure if this is specific to Kibana or a problem in Elasticsearch's rollup index/search not supporting this.

**Comment by rokcarl** [comment] 2020-10-22 13:34
And the [above workaround query](https://github.com/elastic/elasticsearch/issues/44998#issuecomment-516398322) does not work for me. I don't know, maybe I wrote it incorrectly, but I tried to incorporate it into my existing query that was having problems, but it doesn't work.

<details><summary>Old query:</summary>

```
{
  "aggs": {
    "2": {
      "date_histogram": {
        "field": "timestamp",
        "fixed_interval": "60m",
        "time_zone": "UTC",
        "min_doc_count": 1
      },
      "aggs": {
        "3": {
          "terms": {
            "field": "customer",
            "order": {
              "_count": "desc"
            },
            "size": 1
          }
        }
      }
    }
  },
  "size": 0,
  "stored_fields": [
    "*"
  ],
  "script_fields": {},
  "docvalue_fields": [
    {
      "field": "timestamp",
      "format": "date_time"
    }
  ],
  "_source": {
    "excludes": []
  },
  "query": {
    "bool": {
      "must": [],
      "filter": [
        {
          "match_all": {}
        },
        {
          "range": {
            "timestamp": {
              "gte": "2020-10-21T18:00:00.000Z",
              "lte": "2020-10-21T21:59:59.999Z",
              "format": "strict_date_optional_time"
            }
          }
        }
      ],
      "should": [],
      "must_not": []
    }
  }
}
```
</details>

<details><summary>New query:</summary>

```
{
  "aggs": {
    "2": {
      "date_histogram": {
        "field": "timestamp",
        "fixed_interval": "60m",
        "time_zone": "UTC",
        "min_doc_count": 1
      },
      "aggregations": {
        "3": {
          "terms": {
            "field": "customer.terms.value",
            "order": {
              "rollup_doc_count": "desc"
            },
            "size": 1
          },
          "aggregations": {
            "rollup_doc_count": {
              "sum": {
                "field": "customer.terms._count"
              }
            }
          }
        }
      }
    }
  },
  "size": 0,
  "stored_fields": [
    "*"
  ],
  "script_fields": {},
  "docvalue_fields": [
    {
      "field": "timestamp",
      "format": "date_time"
    }
  ],
  "_source": {
    "excludes": []
  },
  "query": {
    "bool": {
      "must": [],
      "filter": [
        {
          "match_all": {}
        },
        {
          "range": {
            "timestamp": {
              "gte": "2020-10-21T18:00:00.000Z",
              "lte": "2020-10-21T21:59:59.999Z",
              "format": "strict_date_optional_time"
            }
          }
        }
      ],
      "should": [],
      "must_not": []
    }
  }
}
```
</details>

The query doesn't even work on the rollup index (`There is not a rollup job that has a [terms] agg on field [customer.terms.value] which also satisfies all requirements of query.`). It does work on the raw index, but the data returned is bad, it's not split by the term at all.

<details><summary>Here's an example result bucket from the raw index:</summary>

```
        {
          "key_as_string": "2020-10-21T18:00:00.000Z",
          "key": 1603303200000,
          "doc_count": 264803,
          "3": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": []
          }
        }
```
</details>

<details><summary>Here's an example result bucket from the raw index:</summary>

```
        {
          "key_as_string": "2020-10-21T18:00:00.000Z",
          "key": 1603303200000,
          "doc_count": 264803,
          "3": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": []
          }
        }
```
</details>

<details><summary>For reference, this is how a bucket result looked on the old query:</summary>

```
        {
          "key_as_string": "2020-10-21T21:00:00.000Z",
          "key": 1603314000000,
          "doc_count": 201504,
          "3": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 139803,
            "buckets": [
              {
                "key": "patrick@foxtrot.io",
                "doc_count": 61701
              }
            ]
          }
        }
```
</details>

**Comment by wchaparro** [comment] 2023-06-23 19:06
With the 8.7 release of Elasticsearch, we have made a [new downsampling capability](https://www.elastic.co/guide/en/elasticsearch/reference/current/downsampling.html) associated with the new [time series datastreams](https://www.elastic.co/guide/en/elasticsearch/reference/current/tsds.html) functionality generally available (GA). This capability was in tech preview in ILM since 8.5.  Downsampling provides a method to reduce the footprint of your time series data by storing it at reduced granularity. The downsampling process rolls up documents within a fixed time interval into a single summary document. Each summary document includes statistical representations of the original data: the min, max, sum, value_count, and average for each metric. Data stream time series dimensions are stored unchanged. 

Downsampling is superior to rollup because:

- Downsampled indices are searched through the _search API
- It is possible to query multiple downsampled indices together with raw data indices
- The pre-aggregation is based on the metrics and time series definitions in the index mapping so very little configuration is required (i.e. much easier to add new time serieses)
- Downsampling is managed as an action in ILM
- It is possible to downsample a downsampled index, and reduce granularity as the index ages
- The performance of the pre-aggregation process is superior in downsampling, as it builds on the time_series index mode infrastructure

Because of the introduction of this new capability, we are deprecating the rollups functionality, which never left the Tech Preview/Experimental status, in favor of downsampling and thus we are closing this issue. We encourage you to migrate your solution to downsampling and take advantage of the new TSDB functionality.

**Closed by wchaparro** 2023-06-23 19:06 UTC
Labels: :Analytics/Rollup, Team:Analytics
