### ISSUE TITLE
[CI] RestClientSingleHostIntegTests.testGetWithBody failed on master

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#29558] opened 2018-04-17 12:15 UTC
Build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=debian/2325/console

No reproduce line was printed.

Failures:

```
11:07:12 Suite: org.elasticsearch.client.RestClientSingleHostIntegTests
11:07:12 ERROR   0.01s J0 | RestClientSingleHostIntegTests.testGetWithBody <<< FAILURES!
11:07:12    > Throwable #1: org.apache.http.ConnectionClosedException: Connection closed
11:07:12    > 	at __randomizedtesting.SeedInfo.seed([BA869D479D2D8EDD:60456C0CDC8F44A]:0)
11:07:12    > 	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:718)
11:07:12    > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235)
11:07:12    > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:198)
11:07:12    > 	at org.elasticsearch.client.RestClientSingleHostIntegTests.bodyTest(RestClientSingleHostIntegTests.java:321)
11:07:12    > 	at org.elasticsearch.client.RestClientSingleHostIntegTests.bodyTest(RestClientSingleHostIntegTests.java:312)
11:07:12    > 	at org.elasticsearch.client.RestClientSingleHostIntegTests.testGetWithBody(RestClientSingleHostIntegTests.java:216)
11:07:12    > 	at java.lang.Thread.run(Thread.java:748)
11:07:12    > Caused by: org.apache.http.ConnectionClosedException: Connection closed
11:07:12    > 	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.endOfInput(HttpAsyncRequestExecutor.java:344)
11:07:12    > 	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:261)
11:07:12    > 	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
11:07:12    > 	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
11:07:12    > 	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
11:07:12    > 	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
11:07:12    > 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
11:07:12    > 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
11:07:12    > 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
11:07:12    > 	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
11:07:12    > 	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
11:07:12    > 	... 1 more
```

**Comment by markharwood** [comment] 2018-04-27 11:01
Another example in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.3+matrix-java-periodic/ES_BUILD_JAVA=java10,ES_RUNTIME_JAVA=java10,nodes=linux/5/console

	 Suite: org.elasticsearch.client.RestClientSingleHostIntegTests
	 ERROR   0.02s J0 | RestClientSingleHostIntegTests.testEncodeParams &lt;&lt;&lt; FAILURES!
	    > Throwable #1: java.io.IOException: Connection reset by peer
	    > 	at __randomizedtesting.SeedInfo.seed([8B1467B354CAACAB:353358761BB80C2A]:0)
	    > 	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:728)
	    > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235)
	    > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:198)
	    > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:177)
	    > 	at org.elasticsearch.client.RestClientSingleHostIntegTests.testEncodeParams(RestClientSingleHostIntegTests.java:221)
	    > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	    > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	    > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	    > 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	    > 	at java.base/java.lang.Thread.run(Thread.java:844)
	    > Caused by: java.io.IOException: Connection reset by peer
	    > 	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	    > 	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	    > 	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:283)
	    > 	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:250)

Mock HTTP server closing the connection?

**Comment by bleskes** [comment] 2018-04-30 20:34
another one: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java10,ES_RUNTIME_JAVA=java10,nodes=linux/24/console

```
16:55:54 Suite: org.elasticsearch.client.RestClientSingleHostIntegTests
16:55:54 ERROR   0.01s J0 | RestClientSingleHostIntegTests.testHeaders <<< FAILURES!
16:55:54    > Throwable #1: java.io.IOException: Connection reset by peer
16:55:54    > 	at __randomizedtesting.SeedInfo.seed([B67B0BD19953E74F:7CAB3B8E1061062F]:0)
16:55:54    > 	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:728)
16:55:54    > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235)
16:55:54    > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:198)
16:55:54    > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:177)
16:55:54    > 	at org.elasticsearch.client.RestClientSingleHostIntegTests.testHeaders(RestClientSingleHostIntegTests.java:177)
16:55:54    > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:55:54    > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:55:54    > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:55:54    > 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
16:55:54    > 	at java.base/java.lang.Thread.run(Thread.java:844)
16:55:54    > Caused by: java.io.IOException: Connection reset by peer
16:55:54    > 	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
16:55:54    > 	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
16:55:54    > 	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:283)
16:55:54    > 	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:250)
```
it looks like the http server the test sets up crashed, no info as to why (I logged onto the server and couldn't find anything telling in the build folder)

**Comment by jdconrad** [comment] 2018-05-07 21:10
Another one: (https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=debian/1039/consoleFull)

**Comment by talevy** [comment] 2018-05-10 01:42
this has failed again:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=oraclelinux/2422/console

It has failed 12 times in the last 30 days. I am AwaitsFix'ing it for `master` and `6.x`.
It has also failed on `6.3`, but I am not sure whether it warrants muting it there, if others disagree
I'll add that too

**Comment by jasontedor** [comment] 2018-05-11 23:14
This was failing many times per day, and now since #30504 it has not failed at all. This increases my level of hope that we have solved this one.

**Comment by talevy** [comment] 2018-05-15 17:07
thanks @jasontedor, I've taken another look and it has continued passing since. I will go ahead and close this.

<img width="566" alt="screen shot 2018-05-15 at 10 07 13 am" src="https://user-images.githubusercontent.com/388837/40072166-c61109b0-5827-11e8-8599-8c5e9c967cd3.png">

**Closed by talevy** 2018-05-15 17:07 UTC
Labels: :Core/Java Low Level REST Client, >test-failure, v6.4.0, v7.0.0
