### ISSUE TITLE
Have mappings available on all nodes

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#17965] opened 2016-04-25 22:10 UTC
Mappings for a given index are only available on nodes that hold a shard for this index. While this may reduce memory usage on clusters that have many indices with few shards on many nodes, it tends to make things more complicated. For instance, search requests cannot be validated on the coordinating node. Wouldn't it be a better trade-off to have mappings available on all nodes?

**Comment by dadoonet** [comment] 2016-05-01 10:34
+1. I always thought that mapping were part of the cluster state.
Is that the idea here? Move mappings in cluster state?

**Comment by jpountz** [comment] 2016-05-01 19:46
The mappings are in the cluster state indeed, but only in their serialized form. You have no way to query the mappings to know whether type contains a field, or whether a field is indexed.

**Comment by nik9000** [comment] 2016-05-01 23:46
It's make function score parsing nicer too! I don't know enough to know the
drawbacks. Certainly heap usage, but is it that much?

**Comment by ywelsch** [comment] 2016-05-02 09:50
> it tends to make things more complicated

@jpountz do you mean code-wise? Or is it just that you want the request to fail as early as possible? (If it is only the latter, we could make this the default only on dedicated client nodes?). 

Related to this, would it be possible to have the same mapping objects for indices that share the same mapping (for example time-based indices)?

**Comment by nik9000** [comment] 2016-05-02 13:41
> Related to this, would it be possible to have the same mapping objects for indices that share the same mapping (for example time-based indices)?

Probably but I don't know if it is worth the complexity? Maybe.

> @jpountz do you mean code-wise? Or is it just that you want the request to fail as early as possible? (If it is only the latter, we could make this the default only on dedicated client nodes?).

Personally I think both are true.

**Comment by nik9000** [comment] 2016-05-02 13:43
> Personally I think both are true.

To be clear - I mean it makes the code more complex which is bad. The fact that we have to delay some stuff until later adds some complexity too. The error reporting consequences of the delay aren't great, but I don't see them as as bad as the code complexity problems.

**Comment by s1monw** [comment] 2016-06-03 09:37
@bleskes I know you had opinions on this can you please comment here

**Comment by bleskes** [comment] 2016-06-03 13:10
yeah. Currently the nodes only open up the mappings that are relevant to them. All the rest are kept in a  compressed version. This means that the number of open mapping per node is limited by the number indices it hosts. If we change it, we are creating an upper bound to the amount of indices (via their mapping) that a cluster can hold and I wasn't comfortable with the fact that this algorithm is not scalable by design (adding nodes doesn't help).  We discussed this last week and I promised to look at https://github.com/elastic/elasticsearch/pull/17959 , which represents the current down sides - as we know it. IMO what we're doing now is the right trade off, at least for this case - streaming a human readable form of the sorting key , next to a binary form that's needed for the actual sorting, doesn't sound too bad to me. Especially if we only do it on the fetch phase - I do want to discuss it with @jpountz and here the finer details behind the issue.

**Comment by s1monw** [comment] 2016-06-10 09:47
While there are a number of reasons why having mappings locally for all indices there are also risks involved. For instance the aspect of relying on local state when search requests are merged not how I think we should design this API. SearchResponses form a shard should contain all information to merge the search results (sort, aggs etc). This is an important aspect when we want to allow searches across different clusters of even different versions where the knowledge / mapping of the index is not necessarily available. There are also situations where data can just not reside in the same cluster for legal reasons but can be searched together etc. In order to add support for these use-cases we must not rely on the mappings but should rather design our protocol in a way that all necessary information is available in the response.

**Closed** 2016-06-17 09:49 UTC
Labels: :Internal, discuss, PITA
