### ISSUE TITLE
Historical segments were not deleted. 

### ISSUE THREAD

**Issue by q578953158** [elastic/elasticsearch#110359] opened 2024-07-02 03:16 UTC
### Elasticsearch Version

8.11

### Installed Plugins

ik

### Java Version

_bundled_

### OS Version

centos7.7

### Problem Description

There are two nodes in my production environment. One index contains 50 million data and is divided into one copy and one shard. The ip address of the server is 45,46. Result The disk usage of 45 active nodes is increasing. When you query the data directory, it is found that many historical segments are not deleted, which leads to increasing segments, and the data on the two nodes is inconsistent

![image](https://github.com/elastic/elasticsearch/assets/18608726/1fd8f219-4c63-4530-93c5-5918dcb754f0)

![9d197afb26d12400ef52fdafb4bd313a](https://github.com/elastic/elasticsearch/assets/18608726/63f3e9ba-cffb-413f-a90d-64c486e93b66)

![image](https://github.com/elastic/elasticsearch/assets/18608726/fcb3f41f-c303-4030-9166-5d3a4f0aa72b)

### Steps to Reproduce

Originally set is 4 shards 1 copy, the result is still the same primary node increasing, help how to solve this abnormal problem, is it es8.11 bug

```[tasklist]
### Tasks
```

**Comment by q578953158** [comment] 2024-07-02 03:23
The two servers in my production environment have the same configuration and are also ssd 500G hard disks

**Comment by DaveCTurner** [comment] 2024-07-02 06:24
Closing as a likely duplicate of https://github.com/elastic/elasticsearch/pull/106544

**Closed by DaveCTurner** 2024-07-02 06:24 UTC
Labels: >bug, needs:triage
