### ISSUE TITLE
Some deprecation messages get logged at level `CRITICAL`

### ISSUE THREAD

**Issue by garethhumphriesgkc** [elastic/elasticsearch#95396] opened 2023-04-19 21:20 UTC
### Elasticsearch Version

8.5.2

### Java Version

_bundled_

### OS Version

Ubuntu 20.04

### Problem Description

At least one kibana deprecation message (_"The role [reporting_user] is deprecated and will be removed in a future version of Elasticsearch. Please use Kibana feature privileges instead"_) gets logged with `log.level` as `CRITICAL`.  This is an inappropriate level, as `CRITICAL` typically indicates that an application is in an unrecoverable state and cannot continue without user intervention.

The `event.type` field is set to `INFO` - this feels like a more appropriate level.

Many dashboards and watchers will be configured to fire on "Error or above", which includes critical, so this will be causing a lot of false alarms.

```
{
  "_source": {
    "input": {
      "type": "log"
    }
  },
  "elasticsearch": {
    "component": "o.e.d.x.s.a.s.RoleDescriptorStore",
    "deprecation": {}
  },
  "log": {
    "file": {
      "path": "/var/log/elasticsearch/logging_deprecation.log"
    },
    "offset": 68441554,
    "level": "CRITICAL"
  },
  "service": {
    "type": "elasticsearch"
  },
  "event": {
    "kind": "event",
    "module": "elasticsearch",
    "category": "database",
    "type": "info",
    "dataset": "elasticsearch.deprecation"
  },
  "message": "data_stream.dataset=\"deprecation.elasticsearch\" data_stream.namespace=\"default\" data_stream.type=\"logs\" elasticsearch.elastic_product_origin=\"kibana\" elasticsearch.event.category=\"security\" elasticsearch.http.request.x_opaque_id=\"a7fae8f3-0134-400d-a879-b2d63db8b013;kibana:application:securitySolutionUI:%7B%22detailName%22%3A%22655b5af0-c396-11ed-b111-3d44eb868502%22%7D\" event.code=\"deprecated_role-reporting_user\" message=\"The role [reporting_user] is deprecated and will be removed in a future version of Elasticsearch. Please use Kibana feature privileges instead\"",
  "fileset": {
    "name": "deprecation"
  }
}
```

### Steps to Reproduce

Run cluster with the `reporting_user` role.  Grep the logs for `CRITICAL`.

### Logs (if relevant)

```
{
  "_source": {
    "input": {
      "type": "log"
    }
  },
  "elasticsearch": {
    "component": "o.e.d.x.s.a.s.RoleDescriptorStore",
    "deprecation": {}
  },
  "log": {
    "file": {
      "path": "/var/log/elasticsearch/logging_deprecation.log"
    },
    "offset": 68441554,
    "level": "CRITICAL"
  },
  "service": {
    "type": "elasticsearch"
  },
  "event": {
    "kind": "event",
    "module": "elasticsearch",
    "category": "database",
    "type": "info",
    "dataset": "elasticsearch.deprecation"
  },
  "message": "data_stream.dataset=\"deprecation.elasticsearch\" data_stream.namespace=\"default\" data_stream.type=\"logs\" elasticsearch.elastic_product_origin=\"kibana\" elasticsearch.event.category=\"security\" elasticsearch.http.request.x_opaque_id=\"a7fae8f3-0134-400d-a879-b2d63db8b013;kibana:application:securitySolutionUI:%7B%22detailName%22%3A%22655b5af0-c396-11ed-b111-3d44eb868502%22%7D\" event.code=\"deprecated_role-reporting_user\" message=\"The role [reporting_user] is deprecated and will be removed in a future version of Elasticsearch. Please use Kibana feature privileges instead\"",
  "fileset": {
    "name": "deprecation"
  }
}
```

**Comment by DaveCTurner** [comment] 2023-04-20 06:56
This is [by design](https://www.elastic.co/guide/en/elasticsearch/reference/current/logging.html#deprecation-logging): the deprecation log only reports information that pertains to upgrades to the next major version, and in that context this is indeed something that has no automatic remedy and needs user intervention.

This is more of a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help if you need further information about this. As such, I hope you don't mind that I close this.

**Closed by DaveCTurner** 2023-04-20 06:56 UTC
Labels: >bug, needs:triage
