### ISSUE TITLE
Tripped assertion in CI regarding event.ingested range

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#110252] opened 2024-06-28 07:52 UTC
One of the runs tripped with the following message:

```
» [2024-06-28T07:03:58,420][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [v8.14.2-0] fatal error in thread [elasticsearch-error-rethrower], exiting java.lang.AssertionError: event.ingested range should be UNKNOWN but is NO_SHARDS for index: [simulate_template_index_cf-ocb1irz2fssqrin8uvw/YQe8OreEQFOKBWIy_AF0CQ] minTransportVersion: 8636001
```

It happens during the bump of lucene from 9.11.0 t 9.11.1, not sure if it is related. @quux00 it seems you recently added this assertion so I assign it to the search team.

https://gradle-enterprise.elastic.co/s/eqfqrahihziug

**Comment by quux00** [comment] 2024-06-28 15:11
I'll own the ticket, but the issue is firmly in the distributed team space, so I reassigned the team labels.

**Closed** 2024-06-28 19:35 UTC
Labels: >test-failure, :Distributed/Distributed, Team:Distributed, medium-risk
