### ISSUE TITLE
elasticsearch7.9.1 highlight uncorrect

### ISSUE THREAD

**Issue by hkh1012** [elastic/elasticsearch#66484] opened 2020-12-17 03:09 UTC
Env:
my es instance is based official's image(elasticsearch:7.9.1) 
es 7.9.1
ik 7.9.1
java 8
none synonym settings

the index field mapping :
`"title" : {
          "type" : "text",
          "analyzer" : "ik_max_word",
          "search_analyzer" : "ik_smart"
        }`
Description:
when i search with some keywords es sometimes return the results with uncerrect highlight .
eg. i search "中国医学影像技术" ，return a doc which the title field is "中国医学教育技术" ,and highlighting the whole words "中国医学教育技术"。

pom:
`<dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>elasticsearch-rest-high-level-client</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.elasticsearch</groupId>
                    <artifactId>elasticsearch</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.elasticsearch.client</groupId>
                    <artifactId>elasticsearch-rest-client</artifactId>
                </exclusion>
            </exclusions>
            <version>7.9.1</version>
        </dependency>
        
        <dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch</artifactId>
            <version>7.9.1</version>
        </dependency>
      <dependency>
          <groupId>org.elasticsearch.client</groupId>
          <artifactId>elasticsearch-rest-client</artifactId>
          <version>7.9.1</version>
      </dependency>`
java search setting code:
` SearchSourceBuilder sourceBuilder = new SearchSourceBuilder();
        BoolQueryBuilder shouldQueryBuilder = QueryBuilders.boolQuery()
                .should(QueryBuilders.matchQuery("periodicalname",searchVo.getKeyword()).boost(560).analyzer("ik_max_word"));

... some other codes ...
 BoolQueryBuilder allBoolQueryBuilder = QueryBuilders.boolQuery().must(shouldQueryBuilder);
        sourceBuilder.query(allBoolQueryBuilder);
                ;`

java highlighting setting code:
`if (StringUtils.isNotBlank(searchVo.getKeyword())){
            HighlightBuilder highlightBuilder = new HighlightBuilder();
            highlightBuilder.preTags("<span style='color: #ED4014;'>");
            highlightBuilder.postTags("</span>");
            highlightBuilder.field("title",0,0);
            highlightBuilder.highlighterType("plain").requireFieldMatch(true);
            sourceBuilder.highlighter(highlightBuilder);
        }`

java result code:
` Map<String, HighlightField> highlightFieldMap =  hit.getHighlightFields();
                Map<String,String> highLights = new HashMap<>();
                if (highlightFieldMap.containsKey("title")){
                    Text[] highField = highlightFieldMap.get("title").getFragments();
                    String t = "";
                    for (Text text : highField){
                        t = t + text.toString();
                    }
                    highLights.put("title",t);
                }`

the rest response snipet:
title=<span style='color: #ED4014;'>中国医学教育技术</span>

I don't know why .
it happens on some search keywords ,not on all search keywords ,majority search is right。
i read the Elasticsearch Reference note in the [docs,,](https://www.elastic.co/guide/en/elasticsearch/reference/current/highlighting.html#highlighting-settings)
`
Highlighters don’t reflect the boolean logic of a query when extracting terms to highlight. Thus, for some complex boolean queries (e.g nested boolean queries, queries using minimum_should_match etc.), parts of documents may be highlighted that don’t correspond to query matches.`

so it is a bug ? or other?
thanks .

**Comment by jimczi** [comment] 2020-12-17 17:41
The offfsets that are used for highlighting depends on the analyzer that you use on the field. Considering that you use a non-official plugin that exposes a custom analyzer I hope you don't mind if I close the issue. Please open an issue in the plugin repository since the problem could be there. If the problems is not caused by the plugin then we can reopen this issue but we need the confirmation first that the problem is not caused by the external plugin.

**Closed by jimczi** 2020-12-17 17:41 UTC
Labels: >bug, needs:triage
