### ISSUE TITLE
Unexpected behaviour in multi match/cross_field/OR query when a two way synonym with multiple words applies

### ISSUE THREAD

**Issue by gmarouli** [elastic/elasticsearch#45841] opened 2019-08-22 13:48 UTC
**Specs**

**Version:** 7.3.0, 
**Build:** default/tar/de777fa/2019-07-24T18:30:11.767338Z, 
**JVM:** 11.0.2
**OS:** Darwin 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

**Expected Behaviour**
When an analyser is being used with a two way synonym of the type: `a b, ab`, we expect a multi-match query `a b` with the cross_fields option and the OR operator will match documents that only contain `a` or `b`.

**Unexpected behaviour**
We notice that the two way synonym interferes and ES doesn't match documents with only `a` or `b`, whereas if we look for `a c` it will match.

**Reproduction path**

Create index:
```
PUT test-synonym-or
{
    "settings": {
        "index" : {
            "analysis" : {
                "analyzer" : {
                    "synonym" : {
                        "tokenizer" : "whitespace",
                        "filter" : ["synonym"]
                    }
                },
                "filter" : {
                    "synonym" : {
                        "type" : "synonym",
                        "synonyms":["kantjes maaier, kantjesmaaier"]
                    }
                }
            }
        }
    }
}
```

Upload mapping:
```
PUT test-synonym-or/_mapping
{
  "properties": {
    "myField": {
      "type": "text",
      "analyzer":"synonym"
    },
    "myField2": {
      "type": "text",
      "analyzer":"synonym"
    }
  }
}
```

Upload documents:
```
POST test-synonym-or/_doc
{
  "myField":"maaier"
}

POST test-synonym-or/_doc
{
  "myField":"bla"
}
```

Search for **kantjes maaier**, expected 1 document, got nothing:
```
GET test-synonym-or/_search
{
  "query": {
    "multi_match": {
      "query": "kantjes maaier",
      "fields": [
        "myField",
        "myField2"
      ],
      "minimum_should_match": "-1",
      "operator": "OR"
    }
  }
}
```

Search for **kantjes bla**, expected 1 document, got 1 document:
```
GET test-synonym-or/_search
{
  "query": {
    "multi_match": {
      "query": "kantjes bla",
      "fields": [
        "myField",
        "myField2"
      ],
      "minimum_should_match": "-1",
      "operator": "OR"
    }
  }
}
```

**Comment by markharwood** [comment] 2021-01-14 14:24
I'm not sure this should be considered a bug.
I'm not sure what` kantjes maier` means so I did a search and replace of `kantjes ->go` and `maier->pro` so that the example is looking for [gopro](https://gopro.com/) cameras. This is a common e-commerce rule because people often type `gopro` or `go pro` to mean the same thing. With that in mind the system behaves as I would expect:

```
DELETE test
PUT test
{
    "settings": {
        "index" : {
            "analysis" : {
                "analyzer" : {
                    "synonym" : {
                        "tokenizer" : "whitespace",
                        "filter" : ["synonym"]
                    }
                },
                "filter" : {
                    "synonym" : {
                        "type" : "synonym",
                        "synonyms":["go pro, gopro"]
                    }
                }
            }
        }
    }
}

PUT test/_mapping
{
  "properties": {
    "myField": {
      "type": "text",
      "analyzer":"synonym"
    },
    "myField2": {
      "type": "text",
      "analyzer":"synonym"
    }
  }
}

POST test/_doc
{
  "myField":"pro"
}

POST test/_doc
{
  "myField":"fishing"
}

# Should not match either doc
GET test/_search
{
  "query": {
    "multi_match": {
      "query": "go pro",
      "fields": [
        "myField",
        "myField2"
      ],
      "minimum_should_match": "-1",
      "operator": "OR"
    }
  }
}
# Should match fishing doc
GET test/_search
{
  "query": {
    "multi_match": {
      "query": "go fishing",
      "fields": [
        "myField",
        "myField2"
      ],
      "minimum_should_match": "-1",
      "operator": "OR"
    }
  }
}
```
The rule is intended to make the two words `go pro` mean the product `gopro`. When you ask for an OR on the search `go pro` that is partly nonsensical because it is a single term/concept so there is only one route to a match.

**Comment by markharwood** [comment] 2021-01-15 10:09
After some further investigation, the example query can be further simplified - a single-field `match` query also fails to match:
```
GET test/_search
{
  "query": {
    "match": {
      "myField": {
        "query": "go pro",
        "minimum_should_match": "-1",
        "operator": "OR"
      }
    }
  }
}
```

The complaint raised in this bug is based on the assumption that this should be interpreted as `go OR pro`.
However, the synonym rule means that this search is interpreted as `"go pro" OR gopro` which makes more sense.
This can be verified by adding this doc:
```
POST test/_doc/3
{
  "myField":"go pro"
}
```
and running this diagnosis:
```
GET test/_doc/3/_explain
{
  "query": {
    "match": {
      "myField": {
        "query": "go pro",
        "minimum_should_match": "-1",
        "operator": "OR"
      }
    }
  }
}
```

This is working as designed from what I can see so will close this issue. Feel free to reopen if you disagree.
Thanks for raising and sorry for the delay in investigating.

**Closed by markharwood** 2021-01-15 10:09 UTC
Labels: :Search/Analysis, Team:Search, v7.3.0
