### ISSUE TITLE
warm index is not moved on the warm node (since 7.12)

### ISSUE THREAD

**Issue by Luigius** [elastic/elasticsearch#71886] opened 2021-04-19 23:05 UTC
Hi,
I got a problem since updating to 7.12

I have a cluster 2 nodes one designed as hot and one designed as worm.
I have an ILM policy that change indexes to warm after 7 days.
Since upgrading to 7.12 the indexes get marked warm but they still phisically stored on the hot node and do not get transfered on the warm node.

Here some commands results:
The log is in warm state.

get winlogbeat-7.11.2-2021.04.06-000006/_ilm/explain

{
  "indices" : {
    "winlogbeat-7.11.2-2021.04.06-000006" : {
      "index" : "winlogbeat-7.11.2-2021.04.06-000006",
      "managed" : true,
      "policy" : "winlogbeat",
      "lifecycle_date_millis" : 1618040937471,
      "age" : "8.77d",
      "phase" : "warm",
      "phase_time_millis" : 1618040940226,
      "action" : "complete",
      "action_time_millis" : 1618043336017,
      "step" : "complete",
      "step_time_millis" : 1618043336017,
      "phase_execution" : {
        "policy" : "winlogbeat",
        "phase_definition" : {
          "min_age" : "0ms",
          "actions" : {
            "allocate" : {
              "number_of_replicas" : 0,
              "include" : { },
              "exclude" : { },
              "require" : { }
            },
            "shrink" : {
              "number_of_shards" : 1
            },
            "forcemerge" : {
              "max_num_segments" : 1
            },
            "set_priority" : {
              "priority" : 50
            }
          }
        },
        "version" : 5,
        "modified_date_in_millis" : 1614928927575
      }
    }
  }
}

get winlogbeat-7.11.2-2021.04.06-000006/

I get the uuid value

{
  "winlogbeat-7.11.2-2021.04.06-000006" : {
    "aliases" : {    },
    "mappings" : { },
    "settings" : {
      "index" : {
        "mapping" : { },
        "refresh_interval" : "5s",
        "blocks" : { },
        "provided_name" : "<winlogbeat-7.11.2-{now/d}-000006>",
        "query" : { },
        "creation_date" : "1617751736437",
        "priority" : "50",
        "number_of_replicas" : "0",
        "uuid" : "3wW9TSYnTja0ri3CxBhb9g",
        "version" : {
          "created" : "7120099"
        },
        "lifecycle" : {
          "name" : "winlogbeat",
          "rollover_alias" : "winlogbeat-7.11.2",
          "indexing_complete" : "true"
        },
        "routing" : {
          "allocation" : {
            "include" : {
              "_tier_preference" : "data_warm,data_hot"
            }
          }
        },
        "number_of_shards" : "1",
        "max_docvalue_fields_search" : "200"
      }
    }
  }
}

GET _cat/nodeattrs?v&h=node,attr,value&s=attr:desc

node      attr              value
monitor   xpack.installed   true
monitor-1 xpack.installed   true
monitor   transform.node    true
monitor-1 transform.node    true
monitor   ml.max_open_jobs  20
monitor-1 ml.max_open_jobs  20
monitor   ml.max_jvm_size   8589934592
monitor-1 ml.max_jvm_size   4294967296
monitor   ml.machine_memory 46192480256
monitor-1 ml.machine_memory 33512464384
monitor   box_type          hot
monitor-1 box_type          warm

I verify that the index is stored on the hot node (monitor) 
[root@Monitor ~]# ls /var/lib/elasticsearch/nodes/0/

results
...
drwxr-sr-x    4 elasticsearch elasticsearch    29 Apr 16 04:48 3wW9TSYnTja0ri3CxBhb9g

and that the index uses all the space on the hot node instead of the warm node.

[root@Monitor ~]# du -sh /var/lib/elasticsearch/nodes/0/indices/3w*
21G     /var/lib/elasticsearch/nodes/0/indices/3wW9TSYnTja0ri3CxBhb9g

**Comment by Luigius** [comment] 2021-04-23 00:11
Hi,
I found a workaround.
If I change the ILM policy for the warm phase and change Data Tier Options from "Use warm nodes (recommended)" to "Custom" and then select the box_type:warm then I run the command to change the status of the index from warm:complete:complete to hot:rollover:set-index-complete, then the all rollover process starts and the index is moved on the warm node.

Here the command:
POST _ilm/move/.ds-logs-endpoint.events.process-default-2021.02.19-000001
{
 "current_step": { 
    "phase": "warm",
    "action": "complete",
    "name": "complete"
  },
  "next_step": { 
    "phase": "hot",
    "action": "rollover",
    "name": "set-indexing-complete"
  }
}


Thanks

**Comment by andrassy** [comment] 2021-04-28 18:06
Think I'm facing a similar issue (bug?). We have Filebeat (both an older 7.4.1 version and a newer 7.12.0 version) pushing data to two different sets of indices. All new indices seem to be created with a strong affinity for "data:hot", but I don't see this in any index templates anywhere 🤔.

```
        "routing" : {
          "allocation" : {
            "require" : {
              "data" : "hot"
            }
          }
        }
```

When the indices get to "warm" state, the "hot" allocation remains on the index, holding it on the hot nodes. 😢 

These are my two corresponding ILM policies. Nothing too crazy here...

```
{
  "filebeat-7.4.1" : {
    "version" : 17,
    "modified_date" : "2021-04-23T17:00:16.811Z",
    "policy" : {
      "phases" : {
        "hot" : {
          "min_age" : "0ms",
          "actions" : {
            "rollover" : {
              "max_size" : "5gb",
              "max_age" : "1d"
            },
            "set_priority" : {
              "priority" : 100
            }
          }
        },
        "delete" : {
          "min_age" : "28d",
          "actions" : {
            "delete" : {
              "delete_searchable_snapshot" : true
            }
          }
        },
        "warm" : {
          "min_age" : "24h",
          "actions" : {
            "forcemerge" : {
              "max_num_segments" : 1
            },
            "readonly" : { },
            "set_priority" : {
              "priority" : 90
            }
          }
        }
      }
    }
  },
  "filebeat-7.12.0" : {
    "version" : 5,
    "modified_date" : "2021-04-23T17:00:02.858Z",
    "policy" : {
      "phases" : {
        "hot" : {
          "min_age" : "0ms",
          "actions" : {
            "rollover" : {
              "max_size" : "5gb",
              "max_age" : "1d"
            },
            "set_priority" : {
              "priority" : 100
            }
          }
        },
        "delete" : {
          "min_age" : "28d",
          "actions" : {
            "delete" : {
              "delete_searchable_snapshot" : true
            }
          }
        },
        "warm" : {
          "min_age" : "24h",
          "actions" : {
            "forcemerge" : {
              "max_num_segments" : 1
            },
            "readonly" : { },
            "set_priority" : {
              "priority" : 90
            }
          }
        }
      }
    }
  }
}
```

Pretty sure we've only seen this behaviour since the upgrade to 7.12.0. We're using Elastic Cloud and have upgraded at pretty much each release.

**Comment by jakelandis** [comment] 2021-05-03 20:06
@Luigius - I think this might have been something unique to your environment. For example, *beat uses version specific ILM policies and if you modify one version then upgrade *beat you can loose your modifications. What you are looking for is moving shards via node attributes what was never supported out of the box, so it must been a user defined configuration that the shards to the warm nodes. 

@andrassy - Newer version of ES, for data streams will always allocate on the hot nodes if the `data_hot` node role exists. As well on our cloud offering there is also a strong preference for all data to land on hot nodes (if you chose the hot/warm deployment). Hot allocation is mostly (except for newer data streams and `data_hot` node roles) is described via the index template, then moving to warm, cold, etc. is done via ILM. In the policies you have listed you will need to ensure that you are using node roles and define a warm phase (which you already have)...or you will need to use the old way of node attributes with an ILM allocate action. 

For a bit more context: https://www.elastic.co/blog/elasticsearch-data-lifecycle-management-with-data-tiers  

I'm going to close these as I don't see any bugs here.  If you disagree, please reopen and provide a reproduction scenario.

**Closed by jakelandis** 2021-05-03 20:06 UTC
Labels: :Core/Features/ILM+SLM, Team:Core/Features
