### ISSUE TITLE
docvalue_fields support wildcard?

### ISSUE THREAD

**Issue by jgq2008303393** [elastic/elasticsearch#26299] opened 2017-08-20 03:43 UTC
Hi, all.

When using docvalue_fields, we would like to use wildcard like stored_fields:

```
# already supported
GET /index/_search
{
  "stored_fields": ["*"]
}

# not support now
GET /index/_search
{
  "docvalue_fields": ["*"]
}
```

Looking forward to this feature.

**Comment by jpountz** [comment] 2017-08-22 15:44
Agreed we should support it for consistency.

**Comment by jpountz** [comment] 2017-08-25 13:42
We discussed it in FixitFriday. We agreed to do this, but at the same time we should probably add a soft limit over the number of doc_values and script fields that are requested (computed based on the number of matches in the mappings) since doc-values fields come up with a per-field per-document seek (while stored fields only incur a per-document seek regardless of the number of fields).

**Comment by jpountz** [comment] 2017-08-25 13:44
I opened #26390.

**Comment by serdyuk-alex** [comment] 2018-08-14 05:26
any updates here? I have object with 60 fields and all of them are needed to be extracted

**Comment by mayya-sharipova** [comment] 2018-08-15 14:47
@serdyuk-alex  the issue is still marked as "adoptme", it is not implemented yet.

**Comment by iverase** [comment] 2018-08-17 14:32
I don't think this is feasible without changing how [docvalue_fields](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-docvalue-fields.html) work. For example the following query:

```
GET /index/_search
{
  "docvalue_fields": ["_version"]
}
``` 

throws an exception:

```
"failed_shards" : [
      {
        "shard" : 0,
        "index" : "twitter",
        "node" : "65h3mLZ0TtKkR5GBDdq6dg",
        "reason" : {
          "type" : "illegal_argument_exception",
          "reason" : "Fielddata is not supported on field [_version] of type [_version]"
        }
      }
    ]
``` 

Therefore if "*" is expand to all fields (which I believe it should include metadata fields), it will always result on an error. 

Note that for [stored_fields](https://www.elastic.co/guide/en/elasticsearch/reference/6.3/search-request-stored-fields.html), fields are  ignored if they are not stored.

**Comment by jpountz** [comment] 2018-08-17 14:40
Requesting doc-value fields on all fields is likely going to fail all the time anyway because of the soft limit that we plan to introduce, it will only be possible to use wildcards that match a very narrow set of fields. I think we should implement support for wildcards regardless of the fact that some fields don't support it?

**Closed** 2018-08-23 08:04 UTC
Labels: :Search/Search, >feature, adoptme, low hanging fruit
