### ISSUE TITLE
TribeNode / TribeMaster ignores CONF_DIR after Upgrade to ES 5.3.1 or higher

### ISSUE THREAD

**Issue by h8h** [elastic/elasticsearch#25113] opened 2017-06-07 17:34 UTC
**Elasticsearch version**: 5.3.1

**Plugins installed**: [x-pack]

**JVM version** (`java -version`): will be given later, debian jessie backports 8u131-b11-1~bpo8+1

**OS version** (`uname -a` if on a Unix-like system): Debian Jessie 8, 64bit.

**Description of the problem including expected versus actual behavior**:
After upgrade the Tribe Master from ES 5.3.0 to ES 5.3.1 and x-pack the CONF_DIR variable gets ignored and ES searches for files in wrong directories, `/usr/share/elasticsearch` instead of `/etc/elasticsearch`.

Only the Tribe Master is affected.

A Tribe Master is in my opinion a system with at least the following configuration:
```
tribe:
    t1: 
        cluster.name:   cluster_one
    t2: 
        cluster.name:   cluster_two
```
If I delete the tribe block, everything works again, even with ES 5.3.1

*The problem is not fixed in the later versions*

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

1. Upgrade Debian ES 5.3.0 to ES 5.3.1 
2. Restart ES (`systemctl restart elasticsearch`)
3. Restart failed, see logs above
4. Downgrade to ES 5.3.0 (`apt-get install elasticsearch=5.3.0`)
5. ES works again

**Provide logs (if relevant)**:
```
java.security.AccessControlException: access denied
("java.io.FilePermission" "/usr/share/elasticsearch/config/scripts" "read")
	at
java.security.AccessControlContext.checkPermission(AccessControlContext.java
:472) ~[?:1.8.0_131]
	at
java.security.AccessController.checkPermission(AccessController.java:884)
~[?:1.8.0_131]
	at
java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
~[?:1.8.0_131]
org.elasticsearch.bootstrap.StartupException:
java.security.AccessControlException: access denied
("java.io.FilePermission" "/usr/share/elasticsearch/config/scripts" "read")
Caused by: java.security.AccessControlException: access denied
("java.io.FilePermission" "/usr/share/elasticsearch/config/scripts" "read")
	at
java.security.AccessControlContext.checkPermission(AccessControlContext.java
:472) ~[?:1.8.0_131]
	at
java.security.AccessController.checkPermission(AccessController.java:884)
~[?:1.8.0_131]
	at
java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
~[?:1.8.0_131]
java.security.AccessControlException: access denied
("java.io.FilePermission" "/usr/share/elasticsearch/config/scripts" "read")
	at
java.security.AccessControlContext.checkPermission(AccessControlContext.java
:472) ~[?:1.8.0_131]
	at
java.security.AccessController.checkPermission(AccessController.java:884)
~[?:1.8.0_131]
	at
java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
~[?:1.8.0_131]
org.elasticsearch.bootstrap.StartupException:
java.security.AccessControlException: access denied
("java.io.FilePermission" "/usr/share/elasticsearch/config/scripts" "read")
Caused by: java.security.AccessControlException: access denied
("java.io.FilePermission" "/usr/share/elasticsearch/config/scripts" "read")
	at
java.security.AccessControlContext.checkPermission(AccessControlContext.java
:472) ~[?:1.8.0_131]
	at
java.security.AccessController.checkPermission(AccessController.java:884)
~[?:1.8.0_131]
	at
java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
~[?:1.8.0_131]
org.elasticsearch.bootstrap.StartupException: ElasticsearchException[Failed
to load plugin class [org.elasticsearch.xpack.XPackPlugin]]; nested:
InvocationTargetException; nested: AccessControlException[access denied
("java.io.FilePermission"
"/usr/share/elasticsearch/config/x-pack/system_key" "read")];
```

/etc/default/elasticsearch
```
################################
# Elasticsearch
################################

# Elasticsearch home directory
#ES_HOME=/usr/share/elasticsearch

# Elasticsearch Java path
#JAVA_HOME=

# Elasticsearch configuration directory
#CONF_DIR=/etc/elasticsearch

# Elasticsearch data directory
#DATA_DIR=/var/lib/elasticsearch

# Elasticsearch logs directory
#LOG_DIR=/var/log/elasticsearch

# Elasticsearch PID directory
#PID_DIR=/var/run/elasticsearch

# Additional Java OPTS
ES_JAVA_OPTS=""

# Configure restart on package upgrade (true, every other setting will lead
to not restarting)
#RESTART_ON_UPGRADE=true

################################
# Elasticsearch service
################################

# SysV init.d
#
# When executing the init script, this user will be used to run the
elasticsearch service.
# The default value is 'elasticsearch' and is declared in the init.d file.
# Note that this setting is only used by the init script. If changed, make
sure that
# the configured user can read and write into the data, work, plugins and
log directories.
# For systemd service, the user is usually configured in file
/usr/lib/systemd/system/elasticsearch.service
#ES_USER=elasticsearch
#ES_GROUP=elasticsearch

# The number of seconds to wait before checking if Elasticsearch started
successfully as a daemon process
ES_STARTUP_SLEEP_TIME=5

################################
# System properties
################################

# Specifies the maximum file descriptor number that can be opened by this
process
# When using Systemd, this setting is ignored and the LimitNOFILE defined in
# /usr/lib/systemd/system/elasticsearch.service takes precedence
#MAX_OPEN_FILES=65536

# The maximum number of bytes of memory that may be locked into RAM
# Set to "unlimited" if you use the 'bootstrap.memory_lock: true' option
# in elasticsearch.yml.
# When using Systemd, the LimitMEMLOCK property must be set
# in /usr/lib/systemd/system/elasticsearch.service
#MAX_LOCKED_MEMORY=unlimited

# Maximum number of VMA (Virtual Memory Areas) a process can own
# When using Systemd, this setting is ignored and the 'vm.max_map_count'
# property is set at boot time in /usr/lib/sysctl.d/elasticsearch.conf
#MAX_MAP_COUNT=262144
```

**Comment by spinscale** [comment] 2017-06-08 08:41
I could quickly reproduce the issue, but my systemd skills fail me to get more debug logs for now...

**Comment by ppf2** [comment] 2017-06-15 02:05
This is still occurring on 5.4.1 (upgrading from 5.3.0) and only affects ES when the node is configured as the tribe node.  In this case, the repro is on CentOS, haven't tried other setup yet.

You will see that when it initializes the node, it does originally determine the right location for the config directory `using config [/etc/elasticsearch]`.

```
[2017-06-14T21:55:08,882][INFO ][o.e.n.Node               ] [] initializing ...
[2017-06-14T21:55:08,981][TRACE][o.e.e.NodeEnvironment    ] obtaining node lock on /var/lib/elasticsearch/nodes/0 ...
[2017-06-14T21:55:08,988][TRACE][o.e.e.NodeEnvironment    ] found state file: [id:52, legacy:false, file:/var/lib/elasticsearch/nodes/0/_state/node-52.st]
[2017-06-14T21:55:09,026][TRACE][o.e.e.NodeEnvironment    ] state id [52] read from [node-52.st]
[2017-06-14T21:55:09,044][DEBUG][o.e.e.NodeEnvironment    ] [hCQ8y9c] using node location [[NodePath{path=/var/lib/elasticsearch/nodes/0, spins=null}]], local_lock_id [0]
[2017-06-14T21:55:09,046][DEBUG][o.e.e.NodeEnvironment    ] [hCQ8y9c] node data locations details:
 -> /var/lib/elasticsearch/nodes/0, free_space [28gb], usable_space [28gb], total_space [37.4gb], spins? [unknown], mount [/ (rootfs)], type [rootfs]
[2017-06-14T21:55:09,046][INFO ][o.e.e.NodeEnvironment    ] [hCQ8y9c] heap size [1.9gb], compressed ordinary object pointers [true]
[2017-06-14T21:55:09,090][INFO ][o.e.n.Node               ] node name [hCQ8y9c] derived from node ID [hCQ8y9c4RGOtOkR16H2W2A]; set [node.name] to override
[2017-06-14T21:55:09,090][INFO ][o.e.n.Node               ] version[5.4.1], pid[7095], build[2cfe0df/2017-05-29T16:05:51.443Z], OS[Linux/3.10.0-123.9.2.el7.x86_64/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_121/25.121-b13]
[2017-06-14T21:55:09,090][INFO ][o.e.n.Node               ] JVM arguments [-Xms2g, -Xmx2g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+DisableExplicitGC, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Djdk.io.permissionsUseCanonicalPath=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -XX:+HeapDumpOnOutOfMemoryError, -Des.path.home=/usr/share/elasticsearch]
[2017-06-14T21:55:09,090][DEBUG][o.e.n.Node               ] using config [/etc/elasticsearch], data [[/var/lib/elasticsearch]], logs [/var/log/elasticsearch], plugins [/usr/share/elasticsearch/plugins]
[2017-06-14T21:55:09,098][TRACE][o.e.p.PluginsService     ] --- adding plugin [/usr/share/elasticsearch/plugins/x-pack]
```

But when it tries to initialize the tribe client (eg. t1), it is somehow deciding to use `using config [/usr/share/elasticsearch/config]` instead.  Because this is occurring when we initialize the tribe client (t1), it doesn't seem like a packaging type of issue?

```
[2017-06-14T21:55:15,795][DEBUG][o.e.a.ActionModule       ] Using REST wrapper from plugin org.elasticsearch.xpack.XPackPlugin
[2017-06-14T21:55:15,888][INFO ][o.e.n.Node               ] [hCQ8y9c/t1] initializing ...
[2017-06-14T21:55:15,901][INFO ][o.e.n.Node               ] [hCQ8y9c/t1] node name [hCQ8y9c/t1], node ID [W_ZzMJq2Q-yNPgEj1BAUjg]
[2017-06-14T21:55:15,901][INFO ][o.e.n.Node               ] [hCQ8y9c/t1] version[5.4.1], pid[7095], build[2cfe0df/2017-05-29T16:05:51.443Z], OS[Linux/3.10.0-123.9.2.el7.x86_64/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_121/25.121-b13]
[2017-06-14T21:55:15,901][INFO ][o.e.n.Node               ] [hCQ8y9c/t1] JVM arguments [-Xms2g, -Xmx2g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+DisableExplicitGC, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Djdk.io.permissionsUseCanonicalPath=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -XX:+HeapDumpOnOutOfMemoryError, -Des.path.home=/usr/share/elasticsearch]
[2017-06-14T21:55:15,901][DEBUG][o.e.n.Node               ] [hCQ8y9c/t1] using config [/usr/share/elasticsearch/config], data [[/usr/share/elasticsearch/data]], logs [/var/log/elasticsearch], plugins [/usr/share/elasticsearch/plugins]
[2017-06-14T21:55:15,904][TRACE][o.e.p.PluginsService     ] --- adding plugin [/usr/share/elasticsearch/plugins/x-pack]
```

This explains why the problem is only reproducible for the tribe node, since regular nodes do not have tribe clients (t1) to initialize.

One workaround is to set `path.conf: /etc/elasticsearch` in the yml of the tribe node.

@clintongormley Thoughts on tagging this to the upcoming 5.4.2 release?

**Comment by jasontedor** [comment] 2017-06-15 02:08
Since a workaround exists I do not think we should block the 5.4.2 release for this.

**Comment by rjernst** [comment] 2018-03-12 05:27
Tribe node has been removed for 7.0, so I'm going to close this issue.

**Closed by rjernst** 2018-03-12 05:27 UTC
Labels: :Core/Packaging, >bug, adoptme
