### ISSUE TITLE
repository-s3 plugin URL incorrect in 6.2.3

### ISSUE THREAD

**Issue by jonassteinberg1** [elastic/elasticsearch#31668] opened 2018-06-28 17:51 UTC
6.2.3
xpack
1.8.0_171
CentOS Linux release 7.4.1708 (Core) 

**Description of the problem**:
attempted install of repository-s3 plugin fails to resolve URL.  wget is possible.

**Steps to reproduce**:
`sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install repository-s3 --verbose`
stdout's 
`Checking if url exists: https://artifacts.elastic.co/downloads/elasticsearch-plugins/repository-s3/repository-s3-linux-x86_64-6.2.3.zip`
then
`wget https://artifacts.elastic.co/downloads/elasticsearch-plugins/repository-s3/repository-s3-linux-x86_64-6.2.3.zip` should throw 404
whilst `wget https://artifacts.elastic.co/downloads/elasticsearch-plugins/repository-s3/repository-s3-6.2.3.zip` succeeds.  Second url I modified from what is listed in the current 6.2 docs for an offline install.  It is missing the '-linux' substring.

![image](https://user-images.githubusercontent.com/7853938/42051556-431be1e4-7ac1-11e8-94fa-cb56a4871ffd.png)

**Comment by spinscale** [comment] 2018-06-29 08:33
is this reproducible all the time you invoke the plugin installation? I just tried with a 6.2.3 installation and it worked, under osx:

```
 bin/elasticsearch-plugin install repository-s3 --verbose
Checking if url exists: https://artifacts.elastic.co/downloads/elasticsearch-plugins/repository-s3/repository-s3-darwin-x86_64-6.2.3.zip
-> Downloading repository-s3 from elastic
Retrieving zip from https://artifacts.elastic.co/downloads/elasticsearch-plugins/repository-s3/repository-s3-6.2.3.zip
[=================================================] 100%
- Plugin information:
Name: repository-s3
Description: The S3 repository plugin adds S3 repositories
Version: 6.2.3
Native Controller: false
Requires Keystore: false
Extended Plugins: []
 * Classname: org.elasticsearch.repositories.s3.S3RepositoryPlugin
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission getClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.net.SocketPermission * connect,resolve
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

Continue with installation? [y/N]y
-> Installed repository-s3
```

I also tried this with a centos vagrant box

```
[root@localhost elasticsearch-6.2.3]# cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)

[root@localhost elasticsearch-6.2.3]# bin/elasticsearch-plugin install repository-s3 --verbose
Checking if url exists: https://artifacts.elastic.co/downloads/elasticsearch-plugins/repository-s3/repository-s3-linux-x86_64-6.2.3.zip
-> Downloading repository-s3 from elastic
Retrieving zip from https://artifacts.elastic.co/downloads/elasticsearch-plugins/repository-s3/repository-s3-6.2.3.zip
[=================================================] 100%
```

Are you using a proxy or do you have a direct connection?

Also, it looks as if you aborted the plugin installation command hitting ctrl+C, did something get stuck?

**Comment by jonassteinberg1** [comment] 2018-06-29 17:50
This is taken from your _centos vagrant box_ code block

```Checking if url exists: https://artifacts.elastic.co/downloads/elasticsearch-plugins/repository-s3/repository-s3-linux-x86_64-6.2.3.zip
-> Downloading repository-s3 from elastic
Retrieving zip from https://artifacts.elastic.co/downloads/elasticsearch-plugins/repository-s3/repository-s3-6.2.3.zip```

If you look the URLs are actually different.  The check shows _repository-s3-linux-x86_64-6.2.3.zip_ but the retrieve shows _repository-s3-6.2.3.zip_

**Comment by jonassteinberg1** [comment] 2018-07-03 03:09
Any update on this?

**Comment by tvernum** [comment] 2018-07-03 03:45
I don't see any bug here, so I'm going to close this issue (with an explanation of what's going on below).

If you would like to continue the discusison, or need any other assistance, please ask on our  [discuss forum](https://discuss.elastic.co/c/elasticsearch) where we can provide better support. Those forums are designed to support the kinds of conversations that are necessary for this sort of troubleshooting and problem diagnosis.

You need to tell the plugin command to make use of your proxy.
Please read https://docs.oracle.com/javase/8/docs/api/java/net/doc-files/net-properties.html#Proxies for the options, but it may be as simple as running
```
ES_JAVA_OPTS="-Djava.net.useSystemProxies=true" /usr/share/elasticsearch/bin/elasticsearch-plugin install repository-s3
```
Or, depending on your system configuration, you may need to explicitly set `https.proxyHost` and `https.proxyPort` in `ES_JAVA_OPTS`

Your screenshot clearly shows that you had to kill (`^C`) the plugin install because it was hanging while trying to check whether a URL exists. That's because it doesn't know about the proxy, so it's trying to make a direct connection, but isn't able to. It should eventually time out if you leave it.

> `wget https://artifacts.elastic.co/downloads/elasticsearch-plugins/repository-s3/repository-s3-linux-x86_64-6.2.3.zip` should throw 404

This correct. Your `wget` is obviously configured to use the proxy, so it can resolve that URL and determine that it is has a 404 response. The plugin install process will also get a 404 once it can get through the proxy.

Then when the plugin install determines that there isn't a platform specific plugin for repository-s3 it will then look for the platform independent one:

> `wget https://artifacts.elastic.co/downloads/elasticsearch-plugins/repository-s3/repository-s3-6.2.3.zip`

This is what the plugin install command will download and install once it can get out to the network.

**Closed by tvernum** 2018-07-03 03:45 UTC
Labels: :Core/Plugins, feedback_needed

**Comment by jonassteinberg1** [comment] 2018-07-03 03:53
I'm sure you're right.  I was _assuming_ that with my proxies set in the current shell, as opposed to the java service, that ES would work and obviously this is an incorrect assumption.  Sorry for wasting your time and I appreciate the prompt response :-)
