### ISSUE TITLE
Feature Request - include snapshot as part of ILM before delete phase 

### ISSUE THREAD

**Issue by elizabethwann** [elastic/elasticsearch#47576] opened 2019-10-04 14:23 UTC
Filed on behalf of Colruyt Group:

Colruyt are using ES for a logging use case where some logs would have a long retention period for audit requirements, but would not need to be queried unless there is an audit. They would like to use snapshots to archive old data before deletion from the cluster. It would be useful to have a snapshot feature before the delete phase in ILM to take a snapshot of old index data to store as an archive before it is deleted from the cluster. 

Related: https://github.com/elastic/elasticsearch/issues/45067

**Comment by dakrone** [comment] 2019-10-04 15:36
This is a duplicate of https://github.com/elastic/elasticsearch/issues/45067. We're unlikely to actually force a snapshot of an index from ILM, because snapshots span multiple indices and ILM policies are per-index. If we allowed ILM policies to spawn their own snapshots, a cluster with 1000 indices would end up creating 1000 snapshots. Rather, an ILM step should wait until the delete phase has started, then wait for a snapshot to be taken naturally (via SLM) prior to the delete.

Closing this for now since it's a duplicate, we can re-open if more discussion is needed (or discuss on #45067)

**Closed by dakrone** 2019-10-04 15:36 UTC
