### ISSUE TITLE
Aggregation Serialization Issue for getKeyAsNumber() method in aggregation bucket

### ISSUE THREAD

**Issue by parkhekishor1988** [elastic/elasticsearch#39170] opened 2019-02-20 08:44 UTC
**Elasticsearch version** :6.3.2

**JVM version** : 1.8

**OS version**: windows 10

**Description of the problem including expected versus actual behavior**: I am using a term aggregation for the field. I got an expected result. I was trying to convert as JSON(Jackson Mapper). 
I am getting a number format exception. After the debugging,  I found the method, getKeyAsNumber() which being call for String data type too. if The key data type is not number it should not try or handled with a valid exception.

**Steps to reproduce**:

 1. execute a Term aggregation on a string or text field.
 2. Convert to a JSON by using Jackson lib or any JSON conversion lib.
 3.After executing an aggregation on any string data type field. Try to convert as JSON using a Jackson JSON library or any JSON conversion lib. It will through an exception.

**Comment by astefan** [comment] 2019-02-20 09:00
@parkhekishor1988 not 100% sure I understand, not necessarily the issue, but how you tested this? The steps you mentioned are executed inside Java code or? If so, can you share that code or, if not, provide more details about the reproduction method? Sorry, but it's not clear to me.

**Comment by parkhekishor1988** [comment] 2019-02-21 04:32
> @parkhekishor1988 not 100% sure I understand, not necessarily the issue, but how you tested this? The steps you mentioned are executed inside Java code or? If so, can you share that code or, if not, provide more details about the reproduction method? Sorry, but it's not clear to me.

Hi, 
**Yes, I using JAVA code for aggregation.**
**Below is test code to reproduce an issue, But code is working for fine with Search query only**, 

import java.io.IOException;
import org.elasticsearch.action.search.SearchRequest;
import org.elasticsearch.action.search.SearchResponse;
import org.elasticsearch.search.aggregations.AggregationBuilders;
import org.elasticsearch.search.aggregations.BucketOrder;
import org.elasticsearch.search.aggregations.bucket.terms.TermsAggregationBuilder;
import org.elasticsearch.search.builder.SearchSourceBuilder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;


import com.fasterxml.jackson.databind.ObjectMapper;

public class Test {
	@Lazy
	@Autowired
	private ElasticsearchIndexerConfig esConfig;
	private static final String TERM_AGGREGATION = "TERM_AGG";

	public static void main(String[] args) {
		Test test = new Test();

		try {
			System.out.println(test.getAggregationResponseAsJSON());
		} catch (IOException e) {
			e.printStackTrace();

		}
	}

	/**
	 * 
	 * @return Aggregation result in String format.
	 * @throws IOException
	 */
	public String getAggregationResponseAsJSON() throws IOException {

		ObjectMapper objectMapper = new ObjectMapper();
		TermsAggregationBuilder termsAggregationBuilder = AggregationBuilders.terms(TERM_AGGREGATION).field("name")
				.order(BucketOrder.key(true));

		SearchRequest searchRequest = new SearchRequest("testindex");
		searchRequest.source(new 
               SearchSourceBuilder().size(0).aggregation(termsAggregationBuilder));

		SearchResponse searchResponse = esConfig.getRestHighLevelClient().search(searchRequest);
		String json = objectMapper.writeValueAsString(searchResponse);
		return json;
	}

}

**After running above code, I am getting an error for number format exception. Below is code snippet for refernce.**

package org.elasticsearch.search.aggregations.bucket.terms;

import org.elasticsearch.search.aggregations.bucket.MultiBucketsAggregation;

import java.util.List;

/**
 * A {@code terms} aggregation. Defines multiple bucket, each associated with a unique term for a specific field.
 * All documents in a bucket has the bucket's term in that field.
 */
public interface Terms extends MultiBucketsAggregation {

    /**
     * A bucket that is associated with a single term
     */
    interface Bucket extends MultiBucketsAggregation.Bucket {

        **#Number getKeyAsNumber();**

        long getDocCountError();
    }

    /**
     * Return the sorted list of the buckets in this terms aggregation.
     */
    @Override
    List<? extends Bucket> getBuckets();

    /**
     * Get the bucket for the given term, or null if there is no such bucket.
     */
    Bucket getBucketByKey(String term);

    /**
     * Get an upper bound of the error on document counts in this aggregation.
     */
    long getDocCountError();

    /**
     * Return the sum of the document counts of all buckets that did not make
     * it to the top buckets.
     */
    long getSumOfOtherDocCounts();
}

**Comment by hudsonb** [comment] 2019-02-21 17:28
This doesn't sound like an elasticsearch bug to me. Can't you add a filter to your `ObjectMapper` to ignore this?

**Comment by polyfractal** [comment] 2019-02-21 21:16
I agree, I think this is just an issue with how Jackson is trying to automagically convert an object to JSON.  E.g. `StringTerms` objects, the result of a terms agg on a string field, [knows how to convert strings to numbers](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/StringTerms.java#L69-L79).

If you want a JSON value out of a `SearchResponse`, you can just call `SearchResponse.toString()` which [internally calls `Strings.toString()`](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/common/Strings.java#L772) on the `SearchResponse` because it's a `ToXContent` object.  You could alternatively call `toXContent()` yourself and pass in the builder etc, but toString is easier :)

I'm going to close this issue.  In the future questions like this are probably better handled in our [discuss forums](https://discuss.elastic.co/c/elasticsearch).

**Closed by polyfractal** 2019-02-21 21:16 UTC
Labels: :Analytics/Aggregations, feedback_needed
