### ISSUE TITLE
String values are compared using '==' in MessageChannelHandler

### ISSUE THREAD

**Issue by slachiewicz** [elastic/elasticsearch#10202] opened 2015-03-21 19:53 UTC
In org.elasticsearch.transport.netty.MessageChannelHandler i found

if (handler.executor() == ThreadPool.Names.SAME) {

**Comment by javanna** [comment] 2015-03-22 09:53
Closing as duplicate of #10204 , PR that addresses this issue.

**Closed by javanna** 2015-03-22 09:53 UTC
