### ISSUE TITLE
[CI] UberModuleClassLoaderTests testServiceLoadingWithModuleInfo failing

### ISSUE THREAD

**Issue by arteam** [elastic/elasticsearch#109191] opened 2024-05-29 21:58 UTC
**Build scan:**
https://gradle-enterprise.elastic.co/s/f7pik7z3irgys/tests/:server:test/org.elasticsearch.plugins.UberModuleClassLoaderTests/testServiceLoadingWithModuleInfo

**Reproduction line:**
```
./gradlew ':server:test' --tests "org.elasticsearch.plugins.UberModuleClassLoaderTests.testServiceLoadingWithModuleInfo" -Dtests.seed=F654025ACE6BDDE2 -Dtests.locale=en -Dtests.timezone=Indian/Christmas -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
[Failure dashboard for `org.elasticsearch.plugins.UberModuleClassLoaderTests#testServiceLoadingWithModuleInfo`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testServiceLoadingWithModuleInfo'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.plugins.UberModuleClassLoaderTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.reflect.InvocationTargetException: (No message provided)

  at __randomizedtesting.SeedInfo.seed([F654025ACE6BDDE2:8D7BA559EEBAA4D4]:0)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at org.elasticsearch.plugins.UberModuleClassLoaderTests.testServiceLoadingWithModuleInfo(UberModuleClassLoaderTests.java:378)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1575)

  Caused by: java.util.ServiceConfigurationError: java.util.random.RandomGenerator: module p.synthetic.test does not declare `uses`

    at java.util.ServiceLoader.fail(ServiceLoader.java:589)
    at java.util.ServiceLoader.checkCaller(ServiceLoader.java:575)
    at java.util.ServiceLoader.<init>(ServiceLoader.java:503)
    at java.util.ServiceLoader.load(ServiceLoader.java:1688)
    at p.ServiceCaller.demo(ServiceCaller.java:9)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at org.elasticsearch.plugins.UberModuleClassLoaderTests.testServiceLoadingWithModuleInfo(UberModuleClassLoaderTests.java:378)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
    at java.lang.Thread.run(Thread.java:1575)

```

**Comment by rjernst** [comment] 2024-05-29 22:34
This doesn't reproduce for me. @arteam it reproduced for you? What system?

**Comment by arteam** [comment] 2024-05-30 09:06
@rjernst It reproduces for me on Ubuntu Linux, openjdk23

**Comment by mark-vieira** [comment] 2024-06-06 20:35
I also could not reproduce on my Mac, but it fails 100% of the time in CI on Linux.

**Comment by valeriy42** [comment] 2024-06-10 13:44
Another failure [here](https://gradle-enterprise.elastic.co/s/j6blfeemdjctw)

**Comment by prdoyle** [comment] 2024-06-21 20:31
Ran it in Docker and it still does not fail.

```
=======================================
Elasticsearch Build Hamster says Hello!
  Gradle Version        : 8.8
  OS Info               : Linux 6.6.31-linuxkit (aarch64)
  Runtime JDK Version   : 23-ea+23-1895 (Oracle, 23-ea+23-1895)
  Runtime java.home     : /home/testuser/.gradle/jdks/oracle_corporation-23-aarch64-linux/jdk-23
  Gradle JDK Version    : 22.0.1+8 (Eclipse Temurin)
  Gradle java.home      : /opt/java/openjdk
  Random Testing Seed   : F654025ACE6BDDE2
  In FIPS 140 mode      : false
=======================================

```

**Comment by prdoyle** [comment] 2024-06-24 20:05
To do this, I wrote this `Dockerfile` (just to run as a non-root user):

```
FROM eclipse-temurin:22

WORKDIR /home/testuser

RUN \
	groupadd -r testuser && \
	useradd -rg testuser testuser && \
	chown -R testuser:testuser /home/testuser

USER testuser
```

And I wrote this wrapper script:

```
#! /bin/bash

docker run --rm \
  -v /Users:/host/Users \
  -v /Applications:/host/Applications \
  -v "$(pwd)":/app \
  -w /app \
  my-ubuntu \
  $*
```

I can run it this way:

```
./run-in-ubuntu.sh ./gradlew ':server:test' --tests "org.elasticsearch.plugins.UberModuleClassLoaderTests.testServiceLoadingWithModuleInfo" -Dtests.seed=F654025ACE6BDDE2 -Dtests.locale=en -Dtests.timezone=Indian/Christmas -Druntime.java=23
```

This is not ideal because it installs Gradle and rebuilds ES every time it's run... but at least it runs the desired command under Ubuntu.

**Comment by mark-vieira** [comment] 2024-07-01 20:57
@prdoyle you can use the following to reproduce this error in a real CI environment.

https://github.com/elastic/elasticsearch-infra/tree/master/buildkite-tools

**Comment by prdoyle** [comment] 2024-07-02 13:17
Thanks @mark-vieira. I've installed the tools and created a Buildkite token. How would I go about reproducing this error?

**Comment by prdoyle** [comment] 2024-07-03 18:04
For future reference:

```
https://buildkite.com/elastic/elasticsearch-periodic/builds/2942#018fc43a-5109-42ee-8c96-e654786402c4
```

**Comment by prdoyle** [comment] 2024-07-03 20:49
With @brianseeders help I managed to run it in GCP... and the test passed. 🤷 

Build scan: https://gradle.com/s/h3c7p2a6mgpek

(Interesting that the build scan URL is public. 🤔 )

**Comment by mark-vieira** [comment] 2024-07-03 20:52
Our [build scan config](https://github.com/elastic/elasticsearch/blob/52fb2dbb6805847dda02baedbdb9806c437d3359/build-tools-internal/src/main/groovy/elasticsearch.build-scan.gradle#L22) looks for an environment variable `BUILDKITE=true` to configure Gradle Enterprise. We might want to add that to the tool scripts so that gets set.

**Comment by prdoyle** [comment] 2024-07-03 20:56
Also... this ran no tests?  https://scans.gradle.com/s/h3c7p2a6mgpek/tests/overview

> This build did not execute any tests.

I should have looked at what `./buildkite-command.sh` contained before I killed the instance.

**Comment by mark-vieira** [comment] 2024-07-03 20:57
> Also... this ran no tests? https://scans.gradle.com/s/h3c7p2a6mgpek/tests/overview

Looks like it just ran the help command?

**Comment by prdoyle** [comment] 2024-07-03 20:58
😂 

Ok let me be a little more careful with it this time.

**Comment by prdoyle** [comment] 2024-07-03 21:05
Ok looks like it passed for reals. Build scan [here](https://gradle-enterprise.elastic.co/s/ymr5h6kq3bry4/tests/overview).

Command:

```
BUILDKITE=true ./gradlew ':server:test' --tests "org.elasticsearch.plugins.UberModuleClassLoaderTests.testServiceLoadingWithModuleInfo" -Dtests.seed=F654025ACE6BDDE2 -Dtests.locale=en -Dtests.timezone=Indian/Christmas -Druntime.java=23
```

**Comment by prdoyle** [comment] 2024-07-03 21:15
That ran with a recent git commit for ES.

Let me try f94c5416e30179a4b6cc0d2f564e96ea0961f800, where the failure was originally reported.

**Comment by prdoyle** [comment] 2024-07-03 22:10
That seemed to pass too. I just can't make this thing fail.

Build scan [here](https://gradle-enterprise.elastic.co/s/aqnbljkezizmu).

**Comment by rjernst** [comment] 2024-07-05 20:20
@prdoyle It looks like your build (using `-Druntime.java=23`) used jdk 23 build 23:

```
Runtime JDK Version : 23-ea+23-1895 (Oracle, 23-ea+23-1895)
```

The failure occurs with the openjdk23 jobs, which set the jdk directly, and are on the newer build 24:
```
Runtime JDK Version : 23-ea+24-1995 (Oracle, 23-ea+24-1995)
```

Unfortunately our openjdk toolchain provider has an explicit jdk build, and we don't currently have a way to auto-update it. I've opened https://github.com/elastic/elasticsearch/pull/110549 to update to the latest build.

**Comment by prdoyle** [comment] 2024-07-08 13:04
Ok thanks @rjernst. Just so I understand... how did the CI fail in the first place?

**Comment by rjernst** [comment] 2024-07-08 13:47
I'm not sure, that's what we need to determine. It appears as if the newer JDK 23 build somehow breaks the test.

**Comment by prdoyle** [comment] 2024-07-08 15:56
I made the same change from #110549 on top of commit f94c5416e301 and it still ran build 23.

**Comment by prdoyle** [comment] 2024-07-08 16:43
> The failure occurs with the openjdk23 jobs, which set the jdk directly

@rjernst - how do they do that?

**Comment by prdoyle** [comment] 2024-07-08 17:50
Ok I think I did it.

Command line:

```
RUNTIME_JAVA_HOME=/opt/buildkite-agent/.java/openjdk23 BUILDKITE=true ./gradlew ':server:test' --scan --tests "org.elasticsearch.plugins.UberModuleClassLoaderTests.testServiceLoadingWithModuleInfo" -Dtests.seed=F654025ACE6BDDE2 -Dtests.locale=en -Dtests.timezone=Indian/Christmas
```

This is actually running build 29:

```
=======================================
Elasticsearch Build Hamster says Hello!
  Gradle Version        : 8.8
  OS Info               : Linux 5.15.0-1062-gcp (amd64)
  Runtime JDK Version   : 23-ea+29-2309 (Oracle, 23-ea+29-2309)
  Runtime java.home     : /opt/buildkite-agent/.java/openjdk23
  Gradle JDK Version    : 17.0.2+8-86 (Oracle)
  Gradle java.home      : /usr/java/openjdk17
  Random Testing Seed   : F654025ACE6BDDE2
  In FIPS 140 mode      : false
=======================================
```

I got this output:

```
UberModuleClassLoaderTests > testServiceLoadingWithModuleInfo FAILED
    java.lang.reflect.InvocationTargetException
        at __randomizedtesting.SeedInfo.seed([F654025ACE6BDDE2:8D7BA559EEBAA4D4]:0)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.elasticsearch.plugins.UberModuleClassLoaderTests.testServiceLoadingWithModuleInfo(UberModuleClassLoaderTests.java:378)

        Caused by:
        java.util.ServiceConfigurationError: java.util.random.RandomGenerator: module p.synthetic.test does not declare `uses`
            at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:589)
            at java.base/java.util.ServiceLoader.checkCaller(ServiceLoader.java:575)
            at java.base/java.util.ServiceLoader.<init>(ServiceLoader.java:503)
            at java.base/java.util.ServiceLoader.load(ServiceLoader.java:1688)
            at p.synthetic.test/p.ServiceCaller.demo(ServiceCaller.java:9)
            at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
            ... 2 more
```

**Comment by prdoyle** [comment] 2024-07-08 18:21
Ok, I reproduced this on my Mac.

```
RUNTIME_JAVA_HOME=/Users/prdoyle/Downloads/JDKs/openjdk-23-ea+30/jdk-23.jdk/Contents/Home ./gradlew ':server:test' --tests "org.elasticsearch.plugins.UberModuleClassLoaderTests.testServiceLoadingWithModuleInfo" -Dtests.seed=F654025ACE6BDDE2 -Dtests.locale=en -Dtests.timezone=Indian/Christmas
```

**Comment by prdoyle** [comment] 2024-07-08 18:47
Reproduced it in IntelliJ.

**Comment by prdoyle** [comment] 2024-07-08 19:11
Between build 23 and build 24, `java.util.random.RandomGenerator` disappeared from the `uses` list in the module descriptor. The `demo` method needs it.

```
ServiceLoader<RandomGenerator> randomLoader = ServiceLoader.load(RandomGenerator.class);
```

**Comment by prdoyle** [comment] 2024-07-08 19:16
I wonder if it was [this change here](https://github.com/openjdk/jdk/commit/42e3c842ae2684265c794868fc76eb0ff2dea3d9#diff-03546451d9e4189f639e3af3dcd6a9e44318fff5ceaadce8478cbf0203ac3f45L422-L435).

**Comment by rjernst** [comment] 2024-07-08 20:30
Seems like the test was just trying to load any SPI from the jdk. I'm not sure why the test checked that, we only really care that our own SPI loads fine. I think we could just remove that line from the demo function.

**Comment by prdoyle** [comment] 2024-07-08 21:37
Oh good point. I already merged it by changing what we loaded. I can do another PR that deletes it if you prefer.

**Closed** 2024-07-08 21:36 UTC
Labels: :Core/Infra/Core, >test-failure, Team:Core/Infra, medium-risk
