### ISSUE TITLE
_cat/fielddata reports node IP address instead of fielddata size of a field called "ip".

### ISSUE THREAD

**Issue by GlenRSmith** [elastic/elasticsearch#18163] opened 2016-05-05 19:28 UTC
**Elasticsearch version**: 2.3.1

**JVM version**: 

>[gsmith@crowley ~ ] > java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

**OS version**: OS X 10.10.5

**Description of the problem including expected versus actual behavior**:

Response to `_cat/fielddata` when there is an actual "ip" field in the indexed data reports the IP address of the node in the column where the size of fielddata used by the "ip" field should appear.

**Steps to reproduce**:

```
# 0. Delete the index
DELETE test_field_data
# 1. Create the index with a document:
POST test_field_data/test_field_data
{"reason": "something is off", "ip": "192.168.1.0"}
# 2. Flush
POST _flush
# 3. Perform a search that loads fielddata
GET test_field_data/_search
{
  "query": {
    "match_all": {}
  },
  "aggs": {
    "ip": {
      "terms": {
        "field": "ip",
        "size": 10
      }
    },
    "reason": {
      "terms": {
        "field": "reason",
        "size": 10
      }
    }
  }
}
# 4. Inspect the fielddata
GET _cat/fielddata/ip,reason?v
```

The return looks like:

```
id                     host      ip        node total reason ip        
FNsjPCVATN-xsg7O0vxIuQ 127.0.0.1 127.0.0.1 only 2.8kb   488b 127.0.0.1 
```

I have also seen a response from a 3 node cluster, also v 2.3.1, where two of the nodes are reported as shown above, and the third node actually has the fielddata usage reported, both in the correct place and in the column where the node ip address is supposed to appear.

**Comment by clintongormley** [comment] 2016-05-06 08:38
Duplicate of #10249

**Closed by clintongormley** 2016-05-06 08:38 UTC
Labels: :CAT API, bug
