### ISSUE TITLE
[TSDB] TSDB enablement fails when there is a field of type text

### ISSUE THREAD

**Issue by constanca-m** [elastic/elasticsearch#96254] opened 2023-05-22 14:42 UTC
**Note**: similar issue [was opened ](https://github.com/elastic/elasticsearch/issues/94113) and close for type `flattened`.

When using Kubernetes integration, there is a `message` field of type `text`:

```
    - name: message
      type: text
      description: |
        Message recorded for the given event
```

This field is **not** a dimension. However, when trying to enable TSDB, it fails, showing this error:

```
illegal_argument_exception Caused by: illegal_argument_exception: invalid composite mappings for [metrics-kubernetes.event] Root causes: illegal_argument_exception: composable template [metrics-kubernetes.event] template after composition with component templates [metrics-kubernetes.event@package, metrics-kubernetes.event@custom, .fleet_globals-1, .fleet_agent_id_verification-1] is invalid
```

I tried to delete the field to understand if this was the cause of this error, and the integration was then added with no problems. If I try to add the field again, and update the integration, it fails:
![image](https://github.com/elastic/elasticsearch/assets/113898685/b900ec79-ea50-4421-b6dd-93991778d9d1)

**Comment by martijnvg** [comment] 2023-05-23 06:09
@constanca-m Can you share the actual Elasticsearch mapping for this `message` field? Currently synthetic source isn't supported on plain text fields. TSDB always uses synthetic source and there this error is returned when adopting tsdb with fields of type text.

However text fields are supported with tsdb if `stored` attribute of a text mapping field is set to `true`. Or text fields have a multi field of type `keyword`. Can you try whether one of these work arounds are acceptable in this case?

**Comment by martijnvg** [comment] 2023-05-23 08:57
I will close this issue in favour of #95799. Because this is an issue with synthetic source and not tsdb.
The mentioned issue is about being able to easily use synthetic source without any barrier. In the context of text field this means that maybe either `stored=true` or a keyword multi field should be configured automatically for text fields when synthetic source is enabled.

**Comment by lalit-satapathy** [comment] 2023-06-01 10:18
@martijnvg,

Re-opening this. There is a data stream with a single field as text, but we want to enable TSDB on that data stream (with other metric fields). Can we allow it?

**Comment by martijnvg** [comment] 2023-06-01 11:17
@lalit-satapathy Can you configure that field be stored? By setting the `stored` attribute to `true` in the mapping for that field? Then synthetic source should work as expected.

**Comment by wchaparro** [comment] 2023-06-07 20:13
@martijnvg @lalit-satapathy were we able to resolve this one?

**Comment by lincolncoe-vca** [comment] 2023-06-12 19:53
Is there a temporary workaround? I am unable to install the kubernetes integration in my 8.8.1 cluster as a result of this which I came about from https://github.com/elastic/integrations/issues/6208

**Comment by lalit-satapathy** [comment] 2023-06-13 03:32
@lincolncoe-vca,

Thanks for raising the issue. You should not face any issue installing the k8 package on 8.8.1; Can you provide more details?
- How did you install the k8 package. Did you upgrade the stack? Did you upgrade the package version?
- Which version of the package you are getting the error?
- Please provide the specific error you are getting.

**Comment by lincolncoe-vca** [comment] 2023-06-13 13:49
@constanca-m @lalit-satapathy 

Good to know I shouldn't be encountering this error. I am using an Elastic cluster via Elastic Cloud. 

> * How did you install the k8 package. Did you upgrade the stack? Did you upgrade the package version?
Originally I had it installed under ES 8.6.2 and the k8s package was 1.32.2. On 06/05 I upgraded the cluster first to 8.7.1 and then to 8.8.0 and tried to update the k8s package to 1.41.0 and the error I observed from the call via browser dev tools was this - 
{"statusCode":500,"error":"Internal Server Error","message":"illegal_argument_exception\n\tCaused by:\n\t\tillegal_argument_exception: invalid composite mappings for [metrics-kubernetes.pod]\n\tRoot causes:\n\t\tillegal_argument_exception: composable template [metrics-kubernetes.pod] template after composition with component templates [metrics-kubernetes.pod@package, metrics-kubernetes.pod@custom, .fleet_globals-1, .fleet_agent_id_verification-1] is invalid"}

I opened a support ticket and was advised to remove mappings and templates, I uninstalled the k8s package and tried to install it as a fresh 1.41.0 and it continues to run into this error. The mappings it fails on changes sometimes, but it always has the same general error. 

I've gone through and verified there are no components, datastreams, indicies or index templates with kubernetes in it. In the logs when I try to install it, I can see it add some of the templates and then remove them once it fails. 
I've also updated to 8.8.1 but same error. 

> * Which version of the package you are getting the error?
1.41.0 on ES 8.8.1
> * Please provide the specific error you are getting.
I get this error if I click either to add Kubernetes and then choose an agent policy, or if I click to install the assets for the integration. 
{
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "illegal_argument_exception\n\tCaused by:\n\t\tillegal_argument_exception: invalid composite mappings for [metrics-kubernetes.state_daemonset]\n\tRoot causes:\n\t\tillegal_argument_exception: composable template [metrics-kubernetes.state_daemonset] template after composition with component templates [metrics-kubernetes.state_daemonset@package, metrics-kubernetes.state_daemonset@custom, .fleet_globals-1, .fleet_agent_id_verification-1] is invalid"
}

You'll see this one fails on metrics-kubernetes.state_daemonset but if I click the same button to install the assets it fails on metrics-kubernetes.state_deployment so it's seemingly random which one it fails on.
{
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "illegal_argument_exception\n\tCaused by:\n\t\tillegal_argument_exception: invalid composite mappings for [metrics-kubernetes.state_deployment]\n\tRoot causes:\n\t\tillegal_argument_exception: composable template [metrics-kubernetes.state_deployment] template after composition with component templates [metrics-kubernetes.state_deployment@package, metrics-kubernetes.state_deployment@custom, .fleet_globals-1, .fleet_agent_id_verification-1] is invalid"
}


I also attached the ES log from when I tried to add it but not much interesting to me.
[k8saddassets.txt](https://github.com/elastic/elasticsearch/files/11735567/k8saddassets.txt)

> @lincolncoe-vca That should not happen, since TSDB is not enabled on the events data stream. Are you enabling it yourself?

I did not know what TSDB was until I came across this thread so I believe the answer is no but I am happy to check if you let me know how I can do so.

**Comment by constanca-m** [comment] 2023-06-13 14:05
Hey @lincolncoe-vca, thanks for all the details.

I created a new deployment for elastic cloud 8.8.1 and installed Kubernetes integration, but I did not run into any of those problems. Did you uninstall everything from the Kubernetes integration through this button "Uninstall button" (in the screenshot without color)?

![image](https://github.com/elastic/elasticsearch/assets/113898685/4b2d96a4-a417-4005-bb84-bec8fa344458)

I am afraid that is not enough. Here is two options, but both imply you will lose data:

- Option 1: Forget about this deployment and create a new one. Kubernetes integration should be installed with no problems.

- Option 2: This one is more complicated. Remove kubernetes from your policy. And now you need to remove everything related to it (unfortunately, that uninstall button does not do this, but I don't know why):
   1. Go to **Management > Stack management > Data > Index Management > Data streams**. Delete everything related to kubernetes:
   
![image](https://github.com/elastic/elasticsearch/assets/113898685/372c89c6-7d4d-4b5c-aa7c-1b72e9d75542)

   2. Do the same for **indices** (toggle the option Include hidden indices, top right on the screenshot):
   
  
![image](https://github.com/elastic/elasticsearch/assets/113898685/5b78a2b1-4759-4f59-9e85-c585fba2c2e5)

   3. And then the exact same thing for **Index templates** and **component templates**.

If you now reinstall the Kubernetes integration, it should work fine.

Let me know if it works!

**Comment by lalit-satapathy** [comment] 2023-06-13 14:27
@constanca-m  Can we file separate issue to track this? Don't want to mix with the original [issue](https://github.com/elastic/elasticsearch/issues/96254#issue-1719842467) which looks different. Let's keep the old comments if possible?

**Comment by constanca-m** [comment] 2023-06-13 14:39
@lincolncoe-vca I created a separe issue https://github.com/elastic/integrations/issues/6554 to track this problem

**Comment by constanca-m** [comment] 2023-06-19 08:37
Providing more context, the reason for failure when trying to migrate to TSDB is:

```console
field [elasticsearch.cluster.stats.nodes.versions] of type [text] doesn't support synthetic source unless it is stored or has a sub-field of type [keyword] with doc values or stored and without a normalizer
```

**Comment by felixbarny** [comment] 2023-06-22 14:54
I've created an issue to support the `store` option in the package spec:
* https://github.com/elastic/package-spec/issues/548

**Comment by wchaparro** [comment] 2023-06-30 13:26
Closing in favor of other issues already opened.

**Closed by wchaparro** 2023-06-30 13:26 UTC
Labels: >bug, Team:Analytics, :Analytics/TSDB
