### ISSUE TITLE
Global ordinals crash warmers

### ISSUE THREAD

**Issue by zygfryd** [elastic/elasticsearch#15590] opened 2015-12-22 07:23 UTC
This has been happening in ES 2.0.x and 2.1.x, the last release where warmers worked for me was 2.0rc1. Affects newly created indexes.

Stacktrace for a simple terms aggregation warmer for a string field (ES 2.1.1):

    [2015-12-21 19:28:06,323][WARN ][index.warmer             ] [lxc] [works9][0] warmer [warm_contrib_aggs] failed
    java.lang.ClassCastException: org.apache.lucene.index.MultiReader cannot be cast to org.apache.lucene.index.DirectoryReader
	    at org.elasticsearch.search.aggregations.support.ValuesSource$Bytes$WithOrdinals$FieldData.globalOrdinalsValues(ValuesSource.java:144)
	    at org.elasticsearch.search.aggregations.support.ValuesSource$Bytes$WithOrdinals.globalMaxOrd(ValuesSource.java:117)
	    at org.elasticsearch.search.aggregations.bucket.terms.TermsAggregatorFactory.doCreateInternal(TermsAggregatorFactory.java:214)
	    at org.elasticsearch.search.aggregations.support.ValuesSourceAggregatorFactory.createInternal(ValuesSourceAggregatorFactory.java:64)
	    at org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:102)
	    at org.elasticsearch.search.aggregations.AggregatorFactories.createTopLevelAggregators(AggregatorFactories.java:87)
	    at org.elasticsearch.search.aggregations.AggregationPhase.preProcess(AggregationPhase.java:78)
	    at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:104)
	    at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:363)
	    at org.elasticsearch.search.SearchService.access$600(SearchService.java:119)
	    at org.elasticsearch.search.SearchService$SearchWarmer$1.run(SearchService.java:1160)
	    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	    at java.lang.Thread.run(Thread.java:745)

**Comment by jpountz** [comment] 2015-12-22 15:02
Thanks for the report, this problem is due to #14084.

**Comment by jpountz** [comment] 2016-01-07 09:50
Closing: warmers will go away in 3.0 #15614

**Closed by jpountz** 2016-01-07 09:50 UTC
Labels: bug

**Comment by ppf2** [comment] 2016-03-16 02:25
I can still reproduce the issue on 2.2.0 so it doesn't look like it is addressed by https://github.com/elastic/elasticsearch/pull/14084.  

```
[2016-03-15 19:04:28,764][WARN ][index.warmer             ] [cluster1_node1] [testwarmer][3] warmer [testwarmer] failed
java.lang.ClassCastException: org.apache.lucene.index.MultiReader cannot be cast to org.apache.lucene.index.DirectoryReader
	at org.elasticsearch.search.aggregations.support.ValuesSource$Bytes$WithOrdinals$FieldData.globalOrdinalsValues(ValuesSource.java:144)
	at org.elasticsearch.search.aggregations.support.ValuesSource$Bytes$WithOrdinals.globalMaxOrd(ValuesSource.java:117)
	at org.elasticsearch.search.aggregations.bucket.terms.TermsAggregatorFactory.doCreateInternal(TermsAggregatorFactory.java:217)
	at org.elasticsearch.search.aggregations.support.ValuesSourceAggregatorFactory.createInternal(ValuesSourceAggregatorFactory.java:64)
	at org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:102)
	at org.elasticsearch.search.aggregations.AggregatorFactories.createTopLevelAggregators(AggregatorFactories.java:87)
	at org.elasticsearch.search.aggregations.AggregationPhase.preProcess(AggregationPhase.java:85)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:111)
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:364)
	at org.elasticsearch.search.SearchService.access$600(SearchService.java:120)
	at org.elasticsearch.search.SearchService$SearchWarmer$1.run(SearchService.java:1165)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Simple warmer with a terms agg:

```
PUT testwarmer/type/1
{
  "test":"test"
}

PUT /testwarmer/_warmer/testwarmer
{
  "query": {
    "match_all": {}
  },
  "aggs": {
    "test":{
      "terms": {
        "field": "test",
        "size": 10
      }
    }
  }
}

PUT testwarmer/type/1
{
  "test":"test"
}
```

However, as noted above, warmers will be removed from the product in 5.0 (previously known as 3.0) so this is just a note in case  users run into it on 2.2.x.
