### ISSUE TITLE
[CI] IndexShardTests.testIndexCheckOnStartup

### ISSUE THREAD

**Issue by pugnascotia** [elastic/elasticsearch#72013] opened 2021-04-21 13:24 UTC
**Build scan**:

https://gradle-enterprise.elastic.co/s/bu6bymrkj3d6m

**Repro line**:

```
./gradlew ':server:test' --tests "org.elasticsearch.index.shard.IndexShardTests.testIndexCheckOnStartup" -Dtests.seed=BF1204DB64EF09DE -Dtests.locale=sk -Dtests.timezone=America/Indiana/Indianapolis -Druntime.java=11
```

**Reproduces locally?**:

Yes

**Applicable branches**:

`master`

**Failure history**:

9 failures this month.

https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=Europe/London&tests.container=org.elasticsearch.index.shard.IndexShardTests&tests.sortField=FAILED&tests.test=testIndexCheckOnStartup&tests.unstableOnly=true

**Failure excerpt**:

```
org.elasticsearch.index.shard.IndexShardTests > testIndexCheckOnStartup FAILED
    org.apache.lucene.index.IndexFormatTooNewException: Format version is not supported (resource MockIndexInputWrapper(MMapIndexInput(path="/Users/rory/src/elastic/elasticsearch/server/build/testrun/test/temp/org.elasticsearch.index.shard.IndexShardTests_BF1204DB64EF09DE-001/tempDir-002/indices/_na_/0/index/_0.cfs") [slice=_0_Lucene80_0.dvd])): 65538 (needs to be between 0 and 2)
        at __randomizedtesting.SeedInfo.seed([BF1204DB64EF09DE:BEB4D1726E69CB06]:0)
        at org.apache.lucene.codecs.CodecUtil.checkHeaderNoMagic(CodecUtil.java:216)
        at org.apache.lucene.codecs.CodecUtil.checkHeader(CodecUtil.java:198)
        at org.apache.lucene.codecs.CodecUtil.checkIndexHeader(CodecUtil.java:255)
        at org.apache.lucene.codecs.lucene80.Lucene80DocValuesProducer.<init>(Lucene80DocValuesProducer.java:97)
        at org.apache.lucene.codecs.lucene80.Lucene80DocValuesFormat.fieldsProducer(Lucene80DocValuesFormat.java:166)
        at org.apache.lucene.codecs.perfield.PerFieldDocValuesFormat$FieldsReader.<init>(PerFieldDocValuesFormat.java:303)
        at org.apache.lucene.codecs.perfield.PerFieldDocValuesFormat.fieldsProducer(PerFieldDocValuesFormat.java:386)
        at org.apache.lucene.index.SegmentDocValues.newDocValuesProducer(SegmentDocValues.java:51)
        at org.apache.lucene.index.SegmentDocValues.getDocValuesProducer(SegmentDocValues.java:67)
        at org.apache.lucene.index.SegmentReader.initDocValuesProducer(SegmentReader.java:175)
        at org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:99)
        at org.apache.lucene.index.CheckIndex.checkIndex(CheckIndex.java:676)
        at org.apache.lucene.util.TestUtil.checkIndex(TestUtil.java:301)
        at org.apache.lucene.store.MockDirectoryWrapper.close(MockDirectoryWrapper.java:867)
        at org.apache.lucene.store.FilterDirectory.close(FilterDirectory.java:110)
        at org.elasticsearch.index.shard.IndexShardTests.testIndexCheckOnStartup(IndexShardTests.java:3100)
```

**Comment by tlrx** [comment] 2021-04-26 12:11
Duplicate of #71827

**Closed by tlrx** 2021-04-26 12:11 UTC
Labels: :Distributed/Recovery, >test-failure, Team:Distributed
