### ISSUE TITLE
ES error logs on type mismatch (at ingestion) could be clearer

### ISSUE THREAD

**Issue by smgduncan** [elastic/elasticsearch#26507] opened 2017-09-05 10:57 UTC
**Elasticsearch version** (`bin/elasticsearch --version`):
5.5.2 Docker Image:
[elasticsearch@1fac82d84533 bin]$ elasticsearch -V 
Version: 5.5.2, Build: b2f0c09/2017-08-14T12:33:14.154Z, JVM: **1.8.0_141**

**Plugins installed**: X-Pack (30 day trial) (as included in the Docker version.

**JVM version** (`java -version`):
1.8.0_141

**OS version** (`uname -a` if on a Unix-like system):
[elasticsearch@1fac82d84533 bin]$ uname -a
Linux 1fac82d84533 4.9.41-moby #1 SMP Fri Aug 18 01:58:38 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
This issue was originally flagged by a customer.  They were submitting an out of range integer value (via Logstash), which was being correctly rejected by Elasticsearch, resulting in various 
"Could not index event to Elasticsearch" caused by "number_format_exception" errors in the Logstash logs.  They were unable to determine the root cause by reviewing the Elasticsearch logs.

Expected behaviour: Able to determine the root cause (value exceeded range of the integer type, and hence should be mapped to a Long) easily from the elasticsearch.log.

Actual behaviour: Was not obvious.

Request: Can the log entries for this error be made a little clearer?

**Steps to reproduce**:

1. Create an index with an integer data type, e.g:

PUT integertest
{
  "mappings": {
    "numeric_type": {
      "properties": {
        "integer": {
          "type": "integer"
        },
        "long": {
          "type": "long"
        },
        "float": {
          "type": "float"
        }
      }
    }
  }
}

 2. Attempt to put an entry in with an out of range integer:

put integertest/numeric_type/2
{
  "integer" : 2287862150
}

3.  This will result in the following error output in the Console:

{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "failed to parse [integer]"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "failed to parse [integer]",
    "caused_by": {
      "type": "json_parse_exception",
      "reason": "Numeric value (2287862150) out of range of int\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@4270b78a; line: 2, column: 25]"
    }
  },
  "status": 400
}

4. The output in the elasticsearch.log was not as easy to interpret:
[2017-09-05T10:52:35,882][DEBUG][o.e.a.b.TransportShardBulkAction] [8trXFm_] [integertest][2] failed to execute bulk item (index) BulkShardRequest [[integertest][2]] containing [index {[integertest][numeric_type][2], source[{
  "integer" : 2287862150
}
]}]
org.elasticsearch.index.mapper.MapperParsingException: failed to parse [integer]
	at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:298) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:468) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:591) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.index.mapper.DocumentParser.innerParseObject(DocumentParser.java:396) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrNested(DocumentParser.java:373) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.index.mapper.DocumentParser.internalParseDocument(DocumentParser.java:93) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:66) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:277) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:529) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.index.shard.IndexShard.prepareIndexOnPrimary(IndexShard.java:506) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.prepareIndexOperationOnPrimary(TransportShardBulkAction.java:450) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequestOnPrimary(TransportShardBulkAction.java:458) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:143) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:113) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:69) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:939) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:908) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:113) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:322) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:264) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:888) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:885) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.index.shard.IndexShardOperationsLock.acquire(IndexShardOperationsLock.java:151) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationLock(IndexShard.java:1657) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryShardReference(TransportReplicationAction.java:897) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.action.support.replication.TransportReplicationAction.access$400(TransportReplicationAction.java:93) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:281) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:260) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:252) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(SecurityServerTransportInterceptor.java:258) ~[?:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.common.util.concurrent.EsExecutors$1.execute(EsExecutors.java:110) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.lambda$messageReceived$0(SecurityServerTransportInterceptor.java:307) ~[?:?]
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:59) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.lambda$authorizeAsync$5(ServerTransportFilter.java:191) ~[?:?]
	at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.maybeRun(AuthorizationUtils.java:127) ~[?:?]
	at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.setRunAsRoles(AuthorizationUtils.java:121) ~[?:?]
	at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.authorize(AuthorizationUtils.java:109) ~[?:?]
	at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.authorizeAsync(ServerTransportFilter.java:193) ~[?:?]
	at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.lambda$inbound$2(ServerTransportFilter.java:162) ~[?:?]
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:59) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$authenticateAsync$2(AuthenticationService.java:212) ~[x-pack-5.5.2.jar:5.5.2]
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$lookForExistingAuthentication$4(AuthenticationService.java:246) ~[x-pack-5.5.2.jar:5.5.2]
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lookForExistingAuthentication(AuthenticationService.java:257) [x-pack-5.5.2.jar:5.5.2]
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.authenticateAsync(AuthenticationService.java:210) [x-pack-5.5.2.jar:5.5.2]
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.access$000(AuthenticationService.java:159) [x-pack-5.5.2.jar:5.5.2]
	at org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:122) [x-pack-5.5.2.jar:5.5.2]
	at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.inbound(ServerTransportFilter.java:145) [x-pack-5.5.2.jar:5.5.2]
	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:314) [x-pack-5.5.2.jar:5.5.2]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) [elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:644) [elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) [elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.5.2.jar:5.5.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: com.fasterxml.jackson.core.JsonParseException: Numeric value (2287862150) out of range of int
 at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@58aafc98; line: 2, column: 25]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702) ~[jackson-core-2.8.6.jar:2.8.6]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558) ~[jackson-core-2.8.6.jar:2.8.6]
	at com.fasterxml.jackson.core.base.ParserBase.convertNumberToInt(ParserBase.java:928) ~[jackson-core-2.8.6.jar:2.8.6]
	at com.fasterxml.jackson.core.base.ParserBase._parseIntValue(ParserBase.java:866) ~[jackson-core-2.8.6.jar:2.8.6]
	at com.fasterxml.jackson.core.base.ParserBase.getIntValue(ParserBase.java:694) ~[jackson-core-2.8.6.jar:2.8.6]
	at org.elasticsearch.common.xcontent.json.JsonXContentParser.doIntValue(JsonXContentParser.java:165) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.intValue(AbstractXContentParser.java:155) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.index.mapper.NumberFieldMapper$NumberType$6.parse(NumberFieldMapper.java:610) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.index.mapper.NumberFieldMapper$NumberType$6.parse(NumberFieldMapper.java:589) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.index.mapper.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:1058) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:287) ~[elasticsearch-5.5.2.jar:5.5.2]
	... 56 more

**Comment by markharwood** [comment] 2017-09-05 13:59
This might just be an education exercise. The "caused by" part of the above exception has the details:

    Caused by: com.fasterxml.jackson.core.JsonParseException: Numeric value (2287862150) out of range of int

While we take efforts to make the REST response readable (unwrapping the "caused by" layers), the log files tend to want to keep extra info to provide added context.

Having said that, I can see that for common user-supplied data errors we might want to cut down on the verbose logging seen here and replace with a shorter message.

**Comment by jasontedor** [comment] 2017-09-05 20:31
The reason is right there in the JSON response, no need to even go through the logs:

```
"caused_by": {
"type": "json_parse_exception",
"reason": "Numeric value (2287862150) out of range of int\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@4270b78a; line: 2, column: 25]"
```

As far as chomping stack traces, note that this monster only appears in the server logs. We are not going to chomp stack traces there, I'm sorry, but we need these for debugging when things do not go as expected. Everything needed to triage this one is in the API response, so I am going to close this issue.

**Closed by jasontedor** 2017-09-05 20:31 UTC
Labels: discuss
