### ISSUE TITLE
[CI] ml.integration.ModelPlotsIT

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#30388] opened 2018-05-04 12:33 UTC
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.3+release-tests/29/console

Reproducible with
```
./gradlew :x-pack:qa:ml-native-tests:integTestRunner 
-Dtests.seed=9D3C27042B1EA097 
-Dtests.class=org.elasticsearch.xpack.ml.integration.ModelPlotsIT 
-Dtests.method="testByFieldWithTerms"
-Dtests.security.manager=true 
-Dbuild.snapshot=false 
-Dtests.jvm.argline="
-Dbuild.snapshot=false" 
-Dtests.locale=mt-MT -Dtests.timezone=Pacific/Nauru
```

**Comment by droberts195** [comment] 2018-05-04 13:01
The failure if you try to reproduce locally is:

```
> Property license.key must be set for release build
```

This is due to the way the license key is injected into the build by CI but not recorded anywhere.

**Comment by droberts195** [comment] 2018-05-04 13:03
I'm pretty sure the reason this failed in CI was that it relies on a C++ change and there was only a snapshot build available for the required change.  I did a non-snapshot build of the 6.3.0 C++ about 3 hours ago, but this failed CI run started about 5 hours ago so wouldn't have used it.

Let's just see if https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.3+release-tests/30/console succeeds.  If it does then we can close this.  If not we'll need to get an appropriate license key to debug locally.

**Comment by droberts195** [comment] 2018-05-05 05:49
Build 30 worked - closing.

**Closed by droberts195** 2018-05-05 05:49 UTC
Labels: :ml, >test
