### ISSUE TITLE
Unable to use Elasticsearch-shards recovery tool (nullPointerException)

### ISSUE THREAD

**Issue by craigsheppard** [elastic/elasticsearch#43997] opened 2019-07-05 05:01 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 7.2.0

**Plugins installed**: []

**JVM version** (`java -version`): `openjdk version "1.8.0_212"`

**OS version** (`uname -a` if on a Unix-like system): **docker sebp/elk image**
`Linux 3133ef838a7a 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**:
I have an index with corrupted translogs (primaries are ALLOCATION_FAILED due to translog EOF), and I'm trying to use the `elasticsearch-shards` tool to get my index up and running again, but it crashes when run with a `java.lang.NullPointerException`.

**Steps to reproduce**:
Running the latest sebp/elk locally on an old machine (MacOS):

I get a shell in my docker image: `bash -c "clear && docker exec -it elk sh"` then I kill elasticsearch, and then run:
```
# opt/elasticsearch/bin/elasticsearch-shard remove-corrupted-data --index environment --shard-id 0
```
and the output is:
```
future versions of Elasticsearch will require Java 11; your Java version from [/usr/lib/jvm/java-8-openjdk-amd64/jre] does not meet this requirement
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
-----------------------------------------------------------------------

    WARNING: Elasticsearch MUST be stopped before running this tool.

  Please make a complete backup of your index before using this tool.

-----------------------------------------------------------------------
Exception in thread "main" java.lang.NullPointerException
	at org.elasticsearch.index.shard.RemoveCorruptedShardDataCommand.findAndProcessShardPath(RemoveCorruptedShardDataCommand.java:175)
	at org.elasticsearch.index.shard.RemoveCorruptedShardDataCommand.execute(RemoveCorruptedShardDataCommand.java:282)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.index.shard.ShardToolCli.main(ShardToolCli.java:35)
# 
```

Not sure where to go next - I'm ok with some data loss, but would like to recover this ASAP.

Thanks!

**Comment by dliappis** [comment] 2019-07-05 09:07
Thanks very much for your interest in Elasticsearch.

Note that the Docker image in use (https://hub.docker.com/r/sebp/elk)
is not a [docker image maintained by Elastic](https://www.docker.elastic.co).

One thing you could attempt is, assuming that you use a Docker volume or bind
mount for your data and it's named `esdata` for example, to bind mount it to the 
official elasticsearch docker image and try something like:

```
docker run --rm -u 1000:0 -v esdata:/usr/share/elasticsearch/data -ti docker.elastic.co/elasticsearch/elasticsearch:7.2.0 /bin/bash

$ bin/elasticsearch-shard remove-corrupted-data --index <your index> --shard-id 0
...
Opening Lucene index at /usr/share/elasticsearch/data/nodes/0/indices/yOhM_rjQQui-9TEmWLN2GQ/0/index


 >> Lucene index is clean at /usr/share/elasticsearch/data/nodes/0/indices/yOhM_rjQQui-9TEmWLN2GQ/0/index


Opening translog at /usr/share/elasticsearch/data/nodes/0/indices/yOhM_rjQQui-9TEmWLN2GQ/0/translog


 >> Translog is clean at /usr/share/elasticsearch/data/nodes/0/indices/yOhM_rjQQui-9TEmWLN2GQ/0/translog

Exception in thread "main" ElasticsearchException[Shard does not seem to be corrupted at /usr/share/elasticsearch/data/nodes/0/indices/yOhM_rjQQui-9TEmWLN2GQ/0]
...
```

The above command overrides launching Elasticsearch and worked for me on a "twitter" index I created earlier.

Since this appears to be a user question and the NPE couldn't be reproduced,
we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/).
If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified 
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I 
hope you don't mind that I close this.

**Closed by dliappis** 2019-07-05 09:07 UTC

**Comment by craigsheppard** [comment] 2019-07-05 18:32
Thanks! I understand :)

FYI I attempted with the official docker container and it now gives a more descriptive `java.io.EOFException` error:

```...Opening translog at /usr/share/elasticsearch/data/nodes/0/indices/8WitgzPDQvCiYJcnnli1sQ/1/translog

read past EOF. pos [51026] length: [4] end: [51026]```

I will follow up on the forms. Thank you for your help!
