### ISSUE TITLE
Simple query string with NEAR|PHRASE flags and nGrams

### ISSUE THREAD

**Issue by alexlopespereira** [elastic/elasticsearch#62789] opened 2020-09-22 20:07 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 7.9

**Description of the problem including expected versus actual behavior**: The NEAR flag does not work when the PHRASE flag is set.

**Steps to reproduce**:

 1.Create the index
```
PUT test/
{
    "settings": {
        "number_of_shards": 1,
        "number_of_replicas": 0,
        "max_ngram_diff": "50",
        "analysis": {
            "analyzer": {
                "custom_ngram": {
                    "type": "custom",
                    "tokenizer": "ngram_tokenizer"
                }
            },
            "tokenizer": {
                "ngram_tokenizer": {
                    "type": "ngram",
                    "min_gram": 2,
                    "max_gram": 10,
                    "token_chars": [
                        "letter",
                        "digit",
                        "punctuation",
                        "symbol"
                    ]
                }
            }
        }
    },
    "mappings": {
        "properties": {
            "txtfield": {"type": "text", "analyzer": "custom_ngram"}
        }
    }
}
```

 2. Insert the document
```
PUT /test/_doc/1
{"txtfield": "this than those"}
```

 3. The simple_query_string with the NEAR flag and without the PHRASE returns the record
```
GET test/_search
{
  "query": {
    "simple_query_string": {
      "query": "\"this those\"~2",
      "flags": "NEAR",
      "fields": [
        "txtfield"
      ]
    }
}}
```

 4. The simple_query_string with the NEAR flag and with the PHRASE does not return the record
```
GET test/_search
{
  "query": {
    "simple_query_string": {
      "query": "\"this those\"~2",
      "flags": "NEAR|PHRASE",
      "fields": [
        "txtfield"
      ]
    }
}}
```

If this is a feature, the documentation should be updated. https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html

**Comment by imotov** [comment] 2020-09-22 21:30
@alexlopespereira Thank you for a good reproduction. This always helps.

Unfortunately, nGrams don't work with phrase searches the way you expect them to work. If you run your text over analyzer you will see that you have not 3 but 21 words in your query (the each word's position can be found in the position field below):

```
POST test/_analyze
{
  "text": ["this than those"],
  "field": "txtfield"
}

{
  "tokens" : [
    {
      "token" : "th",
      "start_offset" : 0,
      "end_offset" : 2,
      "type" : "word",
      "position" : 0
    },
    {
      "token" : "thi",
      "start_offset" : 0,
      "end_offset" : 3,
      "type" : "word",
      "position" : 1
    },
    {
      "token" : "this",
      "start_offset" : 0,
      "end_offset" : 4,
      "type" : "word",
      "position" : 2
    },
    {
      "token" : "hi",
      "start_offset" : 1,
      "end_offset" : 3,
      "type" : "word",
      "position" : 3
    },
    {
      "token" : "his",
      "start_offset" : 1,
      "end_offset" : 4,
      "type" : "word",
      "position" : 4
    },
    {
      "token" : "is",
      "start_offset" : 2,
      "end_offset" : 4,
      "type" : "word",
      "position" : 5
    },
    {
      "token" : "th",
      "start_offset" : 5,
      "end_offset" : 7,
      "type" : "word",
      "position" : 6
    },
    {
      "token" : "tha",
      "start_offset" : 5,
      "end_offset" : 8,
      "type" : "word",
      "position" : 7
    },
    {
      "token" : "than",
      "start_offset" : 5,
      "end_offset" : 9,
      "type" : "word",
      "position" : 8
    },
    {
      "token" : "ha",
      "start_offset" : 6,
      "end_offset" : 8,
      "type" : "word",
      "position" : 9
    },
    {
      "token" : "han",
      "start_offset" : 6,
      "end_offset" : 9,
      "type" : "word",
      "position" : 10
    },
    {
      "token" : "an",
      "start_offset" : 7,
      "end_offset" : 9,
      "type" : "word",
      "position" : 11
    },
    {
      "token" : "th",
      "start_offset" : 10,
      "end_offset" : 12,
      "type" : "word",
      "position" : 12
    },
    {
      "token" : "tho",
      "start_offset" : 10,
      "end_offset" : 13,
      "type" : "word",
      "position" : 13
    },
    {
      "token" : "thos",
      "start_offset" : 10,
      "end_offset" : 14,
      "type" : "word",
      "position" : 14
    },
    {
      "token" : "those",
      "start_offset" : 10,
      "end_offset" : 15,
      "type" : "word",
      "position" : 15
    },
    {
      "token" : "ho",
      "start_offset" : 11,
      "end_offset" : 13,
      "type" : "word",
      "position" : 16
    },
    {
      "token" : "hos",
      "start_offset" : 11,
      "end_offset" : 14,
      "type" : "word",
      "position" : 17
    },
    {
      "token" : "hose",
      "start_offset" : 11,
      "end_offset" : 15,
      "type" : "word",
      "position" : 18
    },
    {
      "token" : "os",
      "start_offset" : 12,
      "end_offset" : 14,
      "type" : "word",
      "position" : 19
    },
    {
      "token" : "ose",
      "start_offset" : 12,
      "end_offset" : 15,
      "type" : "word",
      "position" : 20
    },
    {
      "token" : "se",
      "start_offset" : 13,
      "end_offset" : 15,
      "type" : "word",
      "position" : 21
    }
  ]
}
```

**Comment by imotov** [comment] 2020-09-29 14:27
@alexlopespereira since this behavior doesn't look like a bug, I am going to close this issue. If you have any questions regarding this or other issues in elasticsearch, let's continue the discussion on our forum https://discuss.elastic.co/

**Closed** 2020-09-29 14:28 UTC
Labels: :Search/Search, >non-issue, Team:Search, needs:triage
