### ISSUE TITLE
inconsistent Elastic score between kibana and Fetch API

### ISSUE THREAD

**Issue by chakpongchung** [elastic/elasticsearch#28776] opened 2018-02-22 00:44 UTC
inconsistent _score between Kibana and restful call in Node.js
**Elasticsearch version** (`bin/elasticsearch --version`):

Version: 6.1.2, Build: 5b1fea5/2018-01-10T02:35:59.208Z, JVM: 1.8.0_152

**Plugins installed**: []
Xpack
**JVM version** (`java -version`):

java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):

Darwin FNG172165 16.7.0 Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**:

1. 

I expect the following code using the fetch api show the same _score as the corresponding one from Kibana, but right now it is not.

2.

I tried to delete the index first before creating it. It would fail always. Instead, I delete separately, then 
create a mapping without creating the corresponding index first, it works .

**Steps to reproduce**:

#

To recreate the problem, save the following node.js code in index.js, then `node index.js`

Compare the score with these requests in Kibana
```
DELETE fuzzy_products

# Create the index
PUT /fuzzy_products
# Create the product mapping
PUT /fuzzy_products/product/_mapping
{
  "product": {
    "properties": {
      "name": {
        "type": "text",
        "analyzer": "simple"
      }
    }
  }
}
# Upload some documents
PUT /fuzzy_products/product/1
{"name": "The Water Horse"}

# Perform a fuzzy search!
POST /fuzzy_products/product/_search
{
  "query": {
    "match": {
      "name": {
        "query": "The Water Horse",
        "fuzziness": 2,
        "prefix_length": 1
      }
    }
  }
}

```

```
const fetch = require('node-fetch')
let url
// create the index
let analyzer = 'simple'
let type = 'text'

async function myfunction () {
  // // curl -XHEAD 'localhost:9200/twitter?pretty'

  //   // curl - XDELETE 'localhost:9200/fuzzy_products?pretty'
  // url = 'http://localhost:9200/fuzzy_products'
  // await fetch(url, {
  //   method: 'DELETE', // or 'PUT'
  //   headers: {
  //     'Content-Type': 'application/json'
  //   }
  // }).then(res => res.json())
  //   .catch(error => console.error('Error:', error))
  //   .then(response => console.log('Success delete?:', JSON.stringify(response, null, 2)))

  // var sleep = require('sleep')
  // await sleep.sleep(10) // sleep for ten seconds

  // // create index
  url = 'http://localhost:9200/fuzzy_products'
  await fetch(url, {
    method: 'PUT', // or 'PUT'
    headers: {
      'Content-Type': 'application/json'
    }

  })
    .then(res => res.json())
    .catch(error => console.error('Error:', error))
    .then(response => console.log('index created?:', JSON.stringify(response, null, 2)))

  // // create a mapping for the index
  url = 'http://localhost:9200/fuzzy_products/product/_mapping'
  await fetch(url, {
    method: 'PUT', // or 'PUT'
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      'product': {
        'properties': {
          'name': {
            'type': type,
            'analyzer': analyzer
          }
        }
      }
    })
  })
    .then(res => res.json())
    .catch(error => console.error('Error:', error))
    .then(response => console.log('mapping created:', response))

  // index a document
  // url = 'http://localhost:9200/fuzzy_products/product/9-1-1?pretty'
  let documentName = 'The Water Horse'
  url = 'http://localhost:9200/fuzzy_products/product/' + documentName

  await fetch(url, {
    method: 'PUT', // or 'PUT'
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({ 'name': documentName })

  })
    .then(res => res.json())
    .catch(error => console.error('Error:', error))
    .then(response => console.log('Indexed document?:', response))

  // https://www.elastic.co/guide/en/elasticsearch/reference/current/search-explain.html#search-explain
  url = 'http://localhost:9200/fuzzy_products/product/' + documentName + '/_explain'
  await fetch(url, {
    method: 'POST', // or 'PUT'
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      'query': {
        'match': { 'name': documentName }
      }
    })
  })
    .then(res => res.json())
    .catch(error => console.error('Error:', error))
    .then(response => console.log('Expalin found?:', response))

  // # Perform a fuzzy search!
  url = 'http://localhost:9200/fuzzy_products/product/_search?pretty=true&search_type=dfs_query_then_fetch'
  await fetch(url, {
    method: 'POST', // or 'PUT'
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      'query': {
        'match': {
          'name': {
            'query': documentName,
            'fuzziness': 0,
            'prefix_length': 1
          }
        }
      }
    })
  })
    .then(res => res.json())
    .catch(error => console.error('Error:', error))
    .then(response => console.log('Success found?:', response, response.hits))
}
myfunction()

```
**Provide logs (if relevant)**:

**Comment by chakpongchung** [comment] 2018-02-22 00:46
![screen shot 2018-02-21 at 4 45 13 pm](https://user-images.githubusercontent.com/8110904/36513891-afa1407e-1726-11e8-8282-26f6ebf3a345.png)
<img width="667" alt="screen shot 2018-02-21 at 4 46 02 pm" src="https://user-images.githubusercontent.com/8110904/36513910-bac9b7ce-1726-11e8-92ff-b79ff2df5916.png">

**Comment by DaveCTurner** [comment] 2018-02-22 07:39
I have followed these instructions in a clean 6.2.1 cluster and do not see this effect. The given code, yields no hits because it lacks a refresh:

```
$ node index.js 
index created?: {
  "acknowledged": true,
  "shards_acknowledged": true,
  "index": "fuzzy_products"
}
mapping created: { acknowledged: true }
Indexed document?: { _index: 'fuzzy_products',
  _type: 'product',
  _id: 'The Water Horse',
  _version: 1,
  result: 'created',
  _shards: { total: 2, successful: 1, failed: 0 },
  _seq_no: 0,
  _primary_term: 1 }
Expalin found?: { _index: 'fuzzy_products',
  _type: 'product',
  _id: 'The Water Horse',
  matched: false }
Success found?: { took: 1,
  timed_out: false,
  _shards: { total: 5, successful: 5, skipped: 0, failed: 0 },
  hits: { total: 0, max_score: null, hits: [] } } { total: 0, max_score: null, hits: [] }
```

If I change the line that indexes the document to read

      url = 'http://localhost:9200/fuzzy_products/product/' + documentName + '?refresh'

... then the document is returned, with score `0.8630436` just as reported in Kibana:

```
$ node index.js 
index created?: {
  "error": {
    "root_cause": [
      {
        "type": "resource_already_exists_exception",
        "reason": "index [fuzzy_products/s7lfzmNITwGKlXkK7fFqZw] already exists",
        "index_uuid": "s7lfzmNITwGKlXkK7fFqZw",
        "index": "fuzzy_products"
      }
    ],
    "type": "resource_already_exists_exception",
    "reason": "index [fuzzy_products/s7lfzmNITwGKlXkK7fFqZw] already exists",
    "index_uuid": "s7lfzmNITwGKlXkK7fFqZw",
    "index": "fuzzy_products"
  },
  "status": 400
}
mapping created: { acknowledged: true }
Indexed document?: { _index: 'fuzzy_products',
  _type: 'product',
  _id: 'The Water Horse',
  _version: 2,
  result: 'updated',
  forced_refresh: true,
  _shards: { total: 2, successful: 1, failed: 0 },
  _seq_no: 1,
  _primary_term: 1 }
Expalin found?: { _index: 'fuzzy_products',
  _type: 'product',
  _id: 'The Water Horse',
  matched: true,
  explanation: 
   { value: 0.8630463,
     description: 'sum of:',
     details: [ [Object], [Object], [Object] ] } }
Success found?: { took: 2,
  timed_out: false,
  _shards: { total: 5, successful: 5, skipped: 0, failed: 0 },
  hits: { total: 1, max_score: 0.8630463, hits: [ [Object] ] } } { total: 1,
  max_score: 0.8630463,
  hits: 
   [ { _index: 'fuzzy_products',
       _type: 'product',
       _id: 'The Water Horse',
       _score: 0.8630463,
       _source: [Object] } ] }
```

Note that the commands run in Kibana don't exactly match those in the script: at least, the search URL in this script differs:

      url = 'http://localhost:9200/fuzzy_products/product/_search?pretty=true&search_type=dfs_query_then_fetch'

It's not clear that this matters, but it's worth noting that all Kibana does is make HTTP calls to Elasticsearch, so if you make the same HTTP calls you should get the same results. I expect the reported effect is some other kind of difference between what you're doing in Kibana and in your script.

I'm closing this for now but if you can provide commands that do reproduce this effect then please reopen.

**Closed by DaveCTurner** 2018-02-22 07:39 UTC
