### ISSUE TITLE
DiscoveryWithServiceDisruptionsIT#testAckedIndexing fails on 5.6

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#35287] opened 2018-11-06 09:30 UTC
Link to the build failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+multijob-unix-compatibility/os=sles/41/

Error:

```
DiscoveryWithServiceDisruptionsIT.testAckedIndexing <<< FAILURES!
07:56:23    > Throwable #1: java.lang.AssertionError: expected index shard counter on shard [test][0] on node node_t0 to be 0 but was 1.
```

Reproduce line (does not seem to repro):

```
REPRODUCE WITH: ./gradlew :core:integTest -Dtests.seed=183C381D4B33B132 -Dtests.class=org.elasticsearch.discovery.DiscoveryWithServiceDisruptionsIT -Dtests.method="testAckedIndexing" -Dtests.security.manager=true -Dtests.locale=lt-LT -Dtests.timezone=Europe/Uzhgorod
```

**Comment by ywelsch** [comment] 2018-11-06 11:13
This is hiding another assertion error (which is the true cause for the failure here):

```
2> Lap 06, 2018 8:52:27 AM com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
  2> WARNING: Uncaught exception in thread: Thread[elasticsearch[node_t0][bulk][T#1],5,TGRP-DiscoveryWithServiceDisruptionsIT]
  2> java.lang.AssertionError: version must be set. got -1
  2> 	at __randomizedtesting.SeedInfo.seed([183C381D4B33B132]:0)
  2> 	at org.elasticsearch.index.engine.InternalEngine.indexIntoLucene(InternalEngine.java:597)
  2> 	at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:504)
  2> 	at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:557)
  2> 	at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:546)
  2> 	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequestOnPrimary(TransportShardBulkAction.java:493)
  2> 	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:145)
  2> 	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:114)
  2> 	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:69)
  2> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:975)
  2> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:944)
  2> 	at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:113)
  2> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:345)
  2> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:270)
  2> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:924)
  2> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:921)
  2> 	at org.elasticsearch.index.shard.IndexShardOperationsLock.acquire(IndexShardOperationsLock.java:151)
  2> 	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationLock(IndexShard.java:1659)
  2> 	at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryShardReference(TransportReplicationAction.java:933)
  2> 	at org.elasticsearch.action.support.replication.TransportReplicationAction.access$500(TransportReplicationAction.java:92)
  2> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:291)
  2> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
  2> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:266)
  2> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:248)
  2> 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69)
  2> 	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:662)
  2> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:675)
  2> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
  2> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  2> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  2> 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ywelsch** [comment] 2018-11-07 10:07
@bleskes I need a second pair of eyes here. I've traced through the code and cannot see how, given the stack trace above, this assertion can trip. The test goes as follows:
- node0 (master), on which the assertion trips, has a replica initially
- node1 has the primary and will be partitioned away from node0 and node2
- replica on node0 is promoted to primary
- Indexing requests might be retried due to disconnect and the original replication requests from node1 might be replicated to node0 while the replica on node0 is transitioning to primary (and in contrast to 6.x, this transition is not happening under the operation block, so less clean).

Now looking at the above stack trace:
- `testAckedIndexing` does not use auto-generated IDs
- We see `TransportShardBulkAction.executeIndexRequestOnPrimary` in the stack trace, which means that the document to be indexed has `Engine.Operation.Origin.PRIMARY`
- This in turn means that `planIndexingAsPrimary` will be called. As we are later trying to index into Lucene with version `-1` this only leaves `processNormally` as the possible indexing strategy (all other ones either use fixed value (1) or don't index into Lucene.
- `processNormally` determines the version based on version type. `testAckedIndexing` uses the standard (internal versioning). The updated version is calculated based on `currentVersion == Versions.NOT_FOUND ? 1 : currentVersion + 1` where `Versions.NOT_FOUND` is `-1`. The `currentVersion` is either `-1` or `versionValue.getVersion()`, which comes from `resolveDocVersion`. The `resolveDocVersion` either resolves the version through the version map or from the index. The test is only issuing index operations, not deletes, so `resolveDocVersion` should either yield -1 or a positive number, which means that the updated version will always be positive.
- it is therefore a mystery to me how we can end up with an `IndexingStrategy` that has `-1` as version.

**Comment by bleskes** [comment] 2018-11-09 16:03
@ywelsch and I went through this and sadly, no dice - we couldn't find an explanation.

**Comment by dnhatn** [comment] 2018-12-08 02:29
Another instance on 5.6: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+periodic/311/consoleText

**Comment by ywelsch** [comment] 2019-02-01 09:05
Closing this as this looks to be a 5.6 problem only and we can't figure out the cause. Given that 5.6 is EOL very soon, I don't think we should continue chasing this one.

**Closed by ywelsch** 2019-02-01 09:05 UTC
Labels: :Distributed/ZenDiscovery, >test-failure
