### ISSUE TITLE
[CI] SearchWithMinCompatibleSearchNodeIT testMinVersionAsNewVersion failing

### ISSUE THREAD

**Issue by n1v0lg** [elastic/elasticsearch#95384] opened 2023-04-19 14:52 UTC
Tagging as TSDB issue since the error is:

```
[2023-04-19T13:16:16,446][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [v8.1.1-0] fatal error in thread [elasticsearch[v8.1.1-0][write][T#13]], exiting java.lang.AssertionError: expected mapper parsing failures. got org.elasticsearch.index.mapper.DocumentParsingException: [1:134] failed to parse: _id must be unset or set to [7XQzc-TMfQ1jepZDAAABeRnDq7M] but was [Zl2omYcBecgk29tWmlOQ] because [test] is in time_series mode
```

**Build scan:**
https://gradle-enterprise.elastic.co/s/wqpond4z7i75a/tests/:qa:mixed-cluster:v8.1.1%23mixedClusterTest/org.elasticsearch.backwards.SearchWithMinCompatibleSearchNodeIT/testMinVersionAsNewVersion

**Reproduction line:**
```
./gradlew ':qa:mixed-cluster:v8.1.1#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.SearchWithMinCompatibleSearchNodeIT" -Dtests.method="testMinVersionAsNewVersion" -Dtests.seed=3C2140849CB1BE41 -Dtests.bwc=true -Dtests.locale=en-AU -Dtests.timezone=America/Cuiaba -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.backwards.SearchWithMinCompatibleSearchNodeIT&tests.test=testMinVersionAsNewVersion

**Failure excerpt:**
```
java.lang.AssertionError: timed out waiting for green state for index [test_min_version] cluster state [{
  "cluster_name" : "v8.1.1",
  "cluster_uuid" : "9RCkmDTUSH-UiHXjPvEsqA",
  "version" : 18895,
  "state_uuid" : "s3KjsbLuRWSMmfAR7SjIIg",
  "master_node" : "jKGXG40FSAycCNoRpzvMoA",
  "blocks" : { },
  "nodes" : {
    "jKGXG40FSAycCNoRpzvMoA" : {
      "name" : "v8.1.1-3",
      "ephemeral_id" : "AEA0fFnATqaNQWcyBSt0og",
      "transport_address" : "127.0.0.1:35366",
      "attributes" : {
        "testattr" : "test",
        "ml.max_jvm_size" : "536870912",
        "ml.machine_memory" : "101200584704",
        "xpack.installed" : "true"
      },
      "roles" : [
        "data",
        "data_cold",
        "data_content",
        "data_frozen",
        "data_hot",
        "data_warm",
        "ingest",
        "master",
        "ml",
        "remote_cluster_client",
        "transform"
      ]
    },
    "UJbqP_V2Q3ORXfhzxRzGBA" : {
      "name" : "v8.1.1-1",
      "ephemeral_id" : "Pb3wcrCOSkmLCYEp5tDvRQ",
      "transport_address" : "127.0.0.1:39230",
      "attributes" : {
        "ml.allocated_processors_double" : "32.0",
        "upgraded" : "true",
        "ml.machine_memory" : "101200584704",
        "xpack.installed" : "true",
        "testattr" : "test",
        "ml.max_jvm_size" : "536870912",
        "ml.allocated_processors" : "32"
      },
      "roles" : [
        "data",
        "data_cold",
        "data_content",
        "data_frozen",
        "data_hot",
        "data_warm",
        "ingest",
        "master",
        "ml",
        "remote_cluster_client",
        "transform"
      ]
    },
    "DQokkvqZRfaN_j1IuLRFtA" : {
      "name" : "v8.1.1-2",
      "ephemeral_id" : "t-Ptga26RXCFQFAVF3InAw",
      "transport_address" : "127.0.0.1:37222",
      "attributes" : {
        "testattr" : "test",
        "ml.machine_memory" : "101200584704",
        "xpack.installed" : "true",
        "ml.max_jvm_size" : "536870912"
      },
      "roles" : [
        "data",
        "data_cold",
        "data_content",
        "data_frozen",
        "data_hot",
        "data_warm",
        "ingest",
        "master",
        "ml",
        "remote_cluster_client",
        "transform"
      ]
    }
  },
  "metadata" : {
    "cluster_uuid" : "9RCkmDTUSH-UiHXjPvEsqA",
    "cluster_uuid_committed" : true,
    "cluster_coordination" : {
      "term" : 7,
      "last_committed_config" : [
        "jKGXG40FSAycCNoRpzvMoA",
        "UJbqP_V2Q3ORXfhzxRzGBA",
        "DQokkvqZRfaN_j1IuLRFtA"
      ],
      "last_accepted_config" : [
        "jKGXG40FSAycCNoRpzvMoA",
        "UJbqP_V2Q3ORXfhzxRzGBA",
        "DQokkvqZRfaN_j1IuLRFtA"
      ],
      "voting_config_exclusions" : [ ]
    },
    "templates" : {
      ".monitoring-alerts-7" : {
        "order" : 0,
        "version" : 8010099,
        "index_patterns" : [
          ".monitoring-alerts-7"
        ],
        "settings" : {
          "index" : {
            "format" : "7",
            "codec" : "best_compression",
            "number_of_shards" : "1",
            "auto_expand_replicas" : "0-1",
            "number_of_replicas" : "0"
          }
        },
        "mappings" : {
          "_doc" : {
            "dynamic" : false,
            "properties" : {
              "timestamp" : {
                "type" : "date"
              },
              "update_timestamp" : {
                "type" : "date"
              },
              "resolved_timestamp" : {
                "type" : "date"
              },
              "prefix" : {
                "type" : "text"
              },
              "message" : {
                "type" : "text"
              },
              "suffix" : {
                "type" : "text"
              },
              "metadata" : {
                "properties" : {
                  "cluster_uuid" : {
                    "type" : "keyword"
                  },
                  "link" : {
                    "type" : "keyword"
                  },
                  "severity" : {
                    "type" : "short"
                  },
                  "type" : {
                    "type" : "keyword"
                  },
                  "version" : {
                    "type" : "keyword"
                  },
                  "watch" : {
                    "type" : "keyword"
                  }
                }
              }
            }
          }
        },
        "aliases" : { }
      },
      ".monitoring-kibana" : {
        "order" : 0,
        "version" : 8010099,
        "index_patterns" : [
          ".monitoring-kibana-7-*"
        ],
        "settings" : {
          "index" : {
            "format" : "7",
            "codec" : "best_compression",
            "number_of_shards" : "1",
            "auto_expand_replicas" : "0-1",
            "number_of_replicas" : "0"
          }
        },
        "mappings" : {
          "_doc" : {
            "dynamic" : false,
            "properties" : {
              "cluster_uuid" : {
                "type" : "keyword"
              },
              "timestamp" : {
                "type" : "date",
                "format" : "date_time"
              },
              "interval_ms" : {
                "type" : "long"
              },
              "type" : {
                "type" : "keyword"
              },
              "source_node" : {
                "properties" : {
                  "uuid" : {
                    "type" : "keyword"
                  },
                  "host" : {
                    "type" : "keyword"
                  },
                  "transport_address" : {
                    "type" : "keyword"
                  },
                  "ip" : {
                    "type" : "keyword"
                  },
                  "name" : {
                    "type" : "keyword"
                  },
                  "timestamp" : {
                    "type" : "date",
                    "format" : "date_time"
                  }
                }
              },
              "kibana_stats" : {
                "properties" : {
                  "usage" : {
                    "properties" : {
                      "index" : {
                        "type" : "keyword"
                      }
                    }
                  },
                  "kibana" : {
                    "properties" : {
                      "uuid" : {
                        "type" : "keyword"
                      },
                      "name" : {
                        "type" : "keyword"
                      },
                      "host" : {
                        "type" : "keyword"
                      },
                      "transport_address" : {
                        "type" : "keyword"
                      },
                      "version" : {
                        "type" : "keyword"
                      },
                      "snapshot" : {
                        "type" : "boolean"
                      },
                      "status" : {
                        "type" : "keyword"
                      },
                      "statuses" : {
                        "properties" : {
                          "name" : {
                            "type" : "keyword"
                          },
                          "state" : {
                            "type" : "keyword"
                          }
                        }
                      }
                    }
                  },
                  "cloud" : {
                    "properties" : {
                      "name" : {
                        "type" : "keyword"
                      },
                      "id" : {
                        "type" : "keyword"
                      },
                      "vm_type" : {
                        "type" : "keyword"
                      },
                      "region" : {
                        "type" : "keyword"
                      },
                      "zone" : {
                        "type" : "keyword"
                      },
                      "metadata" : {
                        "type" : "object"
                      }
                    }
                  },
                  "os" : {
                    "properties" : {
                      "load" : {
                        "properties" : {
                          "1m" : {
                            "type" : "half_float"
                          },
                          "5m" : {
                            "type" : "half_float"
                          },
                          "15m" : {
                            "type" : "half_float"
                          }
                        }
                      },
                      "memory" : {
                        "properties" : {
                          "total_in_bytes" : {
                            "type" : "float"
                          },
                          "free_in_bytes" : {
                            "type" : "float"
                          },
                          "used_in_bytes" : {
                            "type" : "float"
                          }
                        }
                      },
                      "uptime_in_millis" : {
                        "type" : "long"
                      }
                    }
                  },
                  "process" : {
                    "properties" : {
                      "memory" : {
                        "properties" : {
                          "heap" : {
                            "properties" : {
                              "total_in_bytes" : {
                                "type" : "float"
                              },
                              "used_in_bytes" : {
                                "type" : "float"
                              },
                              "size_limit" : {
                                "type" : "float"
                              }
                            }
                          },
                          "resident_set_size_in_bytes" : {
                            "type" : "float"
                          }
                        }
                      },
                      "event_loop_delay" : {
                        "type" : "float"
                      },
                      "uptime_in_millis" : {
                        "type" : "long"
                      }
                    }
                  },
                  "sockets" : {
                    "properties" : {
                      "http" : {
                        "properties" : {
                          "total" : {
                            "type" : "long"
                          }
                        }
                      },
                      "https" : {
                        "properties" : {
                          "total" : {
                            "type" : "long"
                          }
                        }
                      }
                    }
                  },
                  "timestamp" : {
                    "type" : "date"
                  },
                  "requests" : {
                    "properties" : {
                      "disconnects" : {
                        "type" : "long"
                      },
                      "total" : {
                        "type" : "long"
                      },
                      "status_codes" : {
                        "type" : "object"
                      }
                    }
                  },
                  "response_times" : {
                    "properties" : {
                      "average" : {
                        "type" : "float"
                      },
                      "max" : {
                        "type" : "float"
                      }
                    }
                  },
                  "concurrent_connections" : {
                    "type" : "long"
                  }
                }
              }
            }
          }
        },
        "aliases" : { }
      },
      ".monitoring-beats" : {
        "order" : 0,
        "version" : 8010099,
        "index_patterns" : [
          ".monitoring-beats-7-*"
        ],
        "settings" : {
          "index" : {
            "format" : "7",
            "codec" : "best_compression",
            "number_of_shards" : "1",
            "auto_expand_replicas" : "0-1",
            "number_of_replicas" : "0"
          }
        },
        "mappings" : {
          "_doc" : {
            "dynamic" : false,
            "properties" : {
              "beats_state" : {
                "properties" : {
                  "beat" : {
                    "properties" : {
                      "host" : {
                        "type" : "keyword"
                      },
                      "name" : {
                        "type" : "keyword"
                      },
                      "type" : {
                        "type" : "keyword"
                      },
                      "uuid" : {
                        "type" : "keyword"
                      },
                      "version" : {
                        "type" : "keyword"
                      }
                    }
                  },
                  "state" : {
                    "properties" : {
                      "beat" : {
                        "properties" : {
                          "name" : {
                            "type" : "keyword"
                          }
                        }
                      },
                      "host" : {
                        "properties" : {
                          "architecture" : {
                            "type" : "keyword"
                          },
                          "name" : {
                            "type" : "keyword"
                          },
                          "hostname" : {
                            "type" : "keyword"
                          },
                          "os" : {
                            "properties" : {
                              "build" : {
                                "type" : "keyword"
                              },
                              "family" : {
                                "type" : "keyword"
                              },
                              "platform" : {
                                "type" : "keyword"
                              },
                              "version" : {
                                "type" : "keyword"
                              }
                            }
                          }
                        }
                      },
                      "input" : {
                        "properties" : {
                          "count" : {
                            "type" : "long"
                          },
                          "names" : {
                            "type" : "keyword"
                          }
                        }
                      },
                      "module" : {
                        "properties" : {
                          "count" : {
                            "type" : "long"
                          },
                          "names" : {
                            "type" : "keyword"
                          }
                        }
                      },
                      "output" : {
                        "properties" : {
                          "name" : {
                            "type" : "keyword"
                          }
                        }
                      },
                      "service" : {
                        "properties" : {
                          "id" : {
                            "type" : "keyword"
                          },
                          "name" : {
                            "type" : "keyword"
                          },
                          "version" : {
                            "type" : "keyword"
                          }
                        }
                      }
                    }
                  },
                  "timestamp" : {
                    "format" : "date_time",
                    "type" : "date"
                  }
                }
              },
              "beats_stats" : {
                "properties" : {
                  "beat" : {
                    "properties" : {
                      "host" : {
                        "type" : "keyword"
                      },
                      "name" : {
                        "type" : "keyword"
                      },
                      "type" : {
                        "type" : "keyword"
                      },
                      "uuid" : {
                        "type" : "keyword"
                      },
                      "version" : {
                        "type" : "keyword"
                      }
                    }
                  },
                  "metrics" : {
                    "properties" : {
                      "beat" : {
                        "properties" : {
                          "cgroup" : {
                            "properties" : {
                              "cpu" : {
                                "properties" : {
                                  "id" : {
                                    "type" : "keyword"
                                  },
                                  "cfs" : {
                                    "properties" : {
                                      "period" : {
                                        "properties" : {
                                          "us" : {
                                            "type" : "long"
                                          }
                                        }
                                      },
                                      "quota" : {
                                        "properties" : {
                                          "us" : {
                                            "type" : "long"
                                          }
                                        }
                                      }
                                    }
                                  },
                                  "stats" : {
                                    "properties" : {
                                      "periods" : {
                                        "type" : "long"
                                      },
                                      "throttled" : {
                                        "properties" : {
                                          "periods" : {
                                            "type" : "long"
                                          },
                                          "ns" : {
                                            "type" : "long"
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              },
                              "cpuacct" : {
                                "properties" : {
                                  "id" : {
                                    "type" : "keyword"
                                  },
                                  "total" : {
                                    "properties" : {
                                      "ns" : {
                                        "type" : "long"
                                      }
                                    }
                                  }
                                }
                              },
                              "memory" : {
                                "properties" : {
                                  "id" : {
                                    "type" : "keyword"
                                  },
                                  "mem" : {
                                    "properties" : {
                                      "limit" : {
                                        "properties" : {
                                          "bytes" : {
                                            "type" : "long"
                                          }
                                        }
                                      },
                                      "usage" : {
                                        "properties" : {
                                          "bytes" : {
                                            "type" : "long"
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          },
                          "cpu" : {
                            "properties" : {
                              "system" : {
                                "properties" : {
                                  "ticks" : {
                                    "type" : "long"
                                  },
                                  "time" : {
                                    "properties" : {
                                      "ms" : {
                                        "type" : "long"
                                      }
                                    }
                                  }
                                }
                              },
                              "total" : {
                                "properties" : {
                                  "value" : {
                                    "type" : "long"
                                  },
                                  "ticks" : {
                                    "type" : "long"
                                  },
                                  "time" : {
                                    "properties" : {
                                      "ms" : {
                                        "type" : "long"
                                      }
                                    }
                                  }
                                }
                              },
                              "user" : {
                                "properties" : {
                                  "ticks" : {
                                    "type" : "long"
                                  },
                                  "time" : {
                                    "properties" : {
                                      "ms" : {
                                        "type" : "long"
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          },
                          "info" : {
                            "properties" : {
                              "ephemeral_id" : {
                                "type" : "keyword"
                              },
                              "uptime" : {
                                "properties" : {
                                  "ms" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "version" : {
                                "type" : "keyword"
                              }
                            }
                          },
                          "memstats" : {
                            "properties" : {
                              "gc_next" : {
                                "type" : "long"
                              },
                              "memory_alloc" : {
                                "type" : "long"
                              },
                              "memory_total" : {
                                "type" : "long"
                              },
                              "rss" : {
                                "type" : "long"
                              }
                            }
                          },
                          "handles" : {
                            "properties" : {
                              "open" : {
                                "type" : "long"
                              },
                              "limit" : {
                                "properties" : {
                                  "hard" : {
                                    "type" : "long"
                                  },
                                  "soft" : {
                                    "type" : "long"
                                  }
                                }
                              }
                            }
                          }
                        }
                      },
                      "apm-server" : {
                        "properties" : {
                          "acm" : {
                            "properties" : {
                              "request" : {
                                "properties" : {
                                  "count" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "response" : {
                                "properties" : {
                                  "count" : {
                                    "type" : "long"
                                  },
                                  "errors" : {
                                    "properties" : {
                                      "validate" : {
                                        "type" : "long"
                                      },
                                      "internal" : {
                                        "type" : "long"
                                      },
                                      "queue" : {
                                        "type" : "long"
                                      },
                                      "count" : {
                                        "type" : "long"
                                      },
                                      "decode" : {
                                        "type" : "long"
                                      },
                                      "toolarge" : {
                                        "type" : "long"
                                      },
                                      "unavailable" : {
                                        "type" : "long"
                                      },
                                      "forbidden" : {
                                        "type" : "long"
                                      },
                                      "method" : {
                                        "type" : "long"
                                      },
                                      "notfound" : {
                                        "type" : "long"
                                      },
                                      "invalidquery" : {
                                        "type" : "long"
                                      },
                                      "ratelimit" : {
                                        "type" : "long"
                                      },
                                      "closed" : {
                                        "type" : "long"
                                      },
                                      "unauthorized" : {
                                        "type" : "long"
                                      }
                                    }
                                  },
                                  "valid" : {
                                    "properties" : {
                                      "notmodified" : {
                                        "type" : "long"
                                      },
                                      "count" : {
                                        "type" : "long"
                                      },
                                      "ok" : {
                                        "type" : "long"
                                      },
                                      "accepted" : {
                                        "type" : "long"
                                      }
                                    }
                                  },
                                  "unset" : {
                                    "type" : "long"
                                  },
                                  "request" : {
                                    "properties" : {
                                      "count" : {
                                        "type" : "long"
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          },
                          "server" : {
                            "properties" : {
                              "request" : {
                                "properties" : {
                                  "count" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "concurrent" : {
                                "properties" : {
                                  "wait" : {
                                    "properties" : {
                                      "ms" : {
                                        "type" : "long"
                                      }
                                    }
                                  }
                                }
                              },
                              "response" : {
                                "properties" : {
                                  "count" : {
                                    "type" : "long"
                                  },
                                  "errors" : {
                                    "properties" : {
                                      "count" : {
                                        "type" : "long"
                                      },
                                      "toolarge" : {
                                        "type" : "long"
                                      },
                                      "validate" : {
                                        "type" : "long"
                                      },
                                      "ratelimit" : {
                                        "type" : "long"
                                      },
                                      "queue" : {
                                        "type" : "long"
                                      },
                                      "closed" : {
                                        "type" : "long"
                                      },
                                      "forbidden" : {
                                        "type" : "long"
                                      },
                                      "concurrency" : {
                                        "type" : "long"
                                      },
                                      "unauthorized" : {
                                        "type" : "long"
                                      },
                                      "internal" : {
                                        "type" : "long"
                                      },
                                      "decode" : {
                                        "type" : "long"
                                      },
                                      "method" : {
                                        "type" : "long"
                                      }
                                    }
                                  },
                                  "valid" : {
                                    "properties" : {
                                      "ok" : {
                                        "type" : "long"
                                      },
                                      "accepted" : {
                                        "type" : "long"
                                      },
                                      "count" : {
                                        "type" : "long"
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          },
                          "decoder" : {
                            "properties" : {
                              "deflate" : {
                                "properties" : {
                                  "content-length" : {
                                    "type" : "long"
                                  },
                                  "count" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "gzip" : {
                                "properties" : {
                                  "content-length" : {
                                    "type" : "long"
                                  },
                                  "count" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "uncompressed" : {
                                "properties" : {
                                  "content-length" : {
                                    "type" : "long"
                                  },
                                  "count" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "reader" : {
                                "properties" : {
                                  "size" : {
                                    "type" : "long"
                                  },
                                  "count" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "missing-content-length" : {
                                "properties" : {
                                  "count" : {
                                    "type" : "long"
                                  }
                                }
                              }
                            }
                          },
                          "processor" : {
                            "properties" : {
                              "metric" : {
                                "properties" : {
                                  "decoding" : {
                                    "properties" : {
                                      "errors" : {
                                        "type" : "long"
                                      },
                                      "count" : {
                                        "type" : "long"
                                      }
                                    }
                                  },
                                  "validation" : {
                                    "properties" : {
                                      "errors" : {
                                        "type" : "long"
                                      },
                                      "count" : {
                                        "type" : "long"
                                      }
                                    }
                                  },
                                  "transformations" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "sourcemap" : {
                                "properties" : {
                                  "counter" : {
                                    "type" : "long"
                                  },
                                  "decoding" : {
                                    "properties" : {
                                      "errors" : {
                                        "type" : "long"
                                      },
                                      "count" : {
                                        "type" : "long"
                                      }
                                    }
                                  },
                                  "validation" : {
                                    "properties" : {
                                      "errors" : {
                                        "type" : "long"
                                      },
                                      "count" : {
                                        "type" : "long"
                                      }
                                    }
                                  }
                                }
                              },
                              "transaction" : {
                                "properties" : {
                                  "decoding" : {
                                    "properties" : {
                                      "errors" : {
                                        "type" : "long"
                                      },
                                      "count" : {
                                        "type" : "long"
                                      }
                                    }
                                  },
                                  "validation" : {
                                    "properties" : {
                                      "errors" : {
                                        "type" : "long"
                                      },
                                      "count" : {
                                        "type" : "long"
                                      }
                                    }
                                  },
                                  "transformations" : {
                                    "type" : "long"
                                  },
                                  "transactions" : {
                                    "type" : "long"
                                  },
                                  "spans" : {
                                    "type" : "long"
                                  },
                                  "stacktraces" : {
                                    "type" : "long"
                                  },
                                  "frames" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "error" : {
                                "properties" : {
                                  "decoding" : {
                                    "properties" : {
                                      "errors" : {
                                        "type" : "long"
                                      },
                                      "count" : {
                                        "type" : "long"
                                      }
                                    }
                                  },
                                  "validation" : {
                                    "properties" : {
                                      "errors" : {
                                        "type" : "long"
                                      },
                                      "count" : {
                                        "type" : "long"
                                      }
                                    }
                                  },
                                  "transformations" : {
                                    "type" : "long"
                                  },
                                  "errors" : {
                                    "type" : "long"
                                  },
                                  "stacktraces" : {
                                    "type" : "long"
                                  },
                                  "frames" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "span" : {
                                "properties" : {
                                  "transformations" : {
                                    "type" : "long"
                                  }
                                }
                              }
                            }
                          },
                          "sampling" : {
                            "properties" : {
                              "transactions_dropped" : {
                                "type" : "long"
                              },
                              "tail" : {
                                "properties" : {
                                  "dynamic_service_groups" : {
                                    "type" : "long"
                                  },
                                  "storage" : {
                                    "properties" : {
                                      "lsm_size" : {
                                        "type" : "long"
                                      },
                                      "value_log_size" : {
                                        "type" : "long"
                                      }
                                    }
                                  },
                                  "events" : {
                                    "properties" : {
                                      "processed" : {
                                        "type" : "long"
                                      },
                                      "dropped" : {
                                        "type" : "long"
                                      },
                                      "stored" : {
                                        "type" : "long"
                                      },
                                      "sampled" : {
                                        "type" : "long"
                                      },
                                      "head_unsampled" : {
                                        "type" : "long"
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      },
                      "libbeat" : {
                        "properties" : {
                          "config" : {
                            "properties" : {
                              "module" : {
                                "properties" : {
                                  "running" : {
                                    "type" : "long"
                                  },
                                  "starts" : {
                                    "type" : "long"
                                  },
                                  "stops" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "reloads" : {
                                "type" : "long"
                              }
                            }
                          },
                          "output" : {
                            "properties" : {
                              "events" : {
                                "properties" : {
                                  "acked" : {
                                    "type" : "long"
                                  },
                                  "active" : {
                                    "type" : "long"
                                  },
                                  "batches" : {
                                    "type" : "long"
                                  },
                                  "dropped" : {
                                    "type" : "long"
                                  },
                                  "duplicates" : {
                                    "type" : "long"
                                  },
                                  "failed" : {
                                    "type" : "long"
                                  },
                                  "total" : {
                                    "type" : "long"
                                  },
                                  "toomany" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "read" : {
                                "properties" : {
                                  "bytes" : {
                                    "type" : "long"
                                  },
                                  "errors" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "type" : {
                                "type" : "keyword"
                              },
                              "write" : {
                                "properties" : {
                                  "bytes" : {
                                    "type" : "long"
                                  },
                                  "errors" : {
                                    "type" : "long"
                                  }
                                }
                              }
                            }
                          },
                          "pipeline" : {
                            "properties" : {
                              "clients" : {
                                "type" : "long"
                              },
                              "events" : {
                                "properties" : {
                                  "active" : {
                                    "type" : "long"
                                  },
                                  "dropped" : {
                                    "type" : "long"
                                  },
                                  "failed" : {
                                    "type" : "long"
                                  },
                                  "filtered" : {
                                    "type" : "long"
                                  },
                                  "published" : {
                                    "type" : "long"
                                  },
                                  "retry" : {
                                    "type" : "long"
                                  },
                                  "total" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "queue" : {
                                "properties" : {
                                  "acked" : {
                                    "type" : "long"
                                  }
                                }
                              }
                            }
                          }
                        }
                      },
                      "system" : {
                        "properties" : {
                          "load" : {
                            "properties" : {
                              "1" : {
                                "type" : "double"
                              },
                              "15" : {
                                "type" : "double"
                              },
                              "5" : {
                                "type" : "double"
                              },
                              "norm" : {
                                "properties" : {
                                  "1" : {
                                    "type" : "double"
                                  },
                                  "15" : {
                                    "type" : "double"
                                  },
                                  "5" : {
                                    "type...
```

**Comment by kkrik-es** [comment] 2023-10-12 10:57
Can't reproduce, there were a few tests that took almost 30'. Seems like a random slowness issue, closing for now.

**Comment by kkrik-es** [comment] 2024-10-23 06:36
Unmuting to see if this will show up again.

**Closed** 2024-10-23 16:34 UTC
Labels: >test-failure, :StorageEngine/TSDB, low-risk, Team:StorageEngine

**Comment by smalyshev** [comment] 2025-01-13 18:41
@kkrik-es Looks like it did: https://github.com/elastic/elasticsearch/issues/95384
