### ISSUE TITLE
5.1.1 to 5.1.2 possible regression

### ISSUE THREAD

**Issue by AndrewBryukhov** [elastic/elasticsearch#22767] opened 2017-01-24 14:45 UTC
I'm using logstash to move data into es from psql.

After updating from logstash 5.1.1 to 5.1.2 (also elastic) i see those messages (for same configuration):

> {"log":"14:56:02.635 [[main]\u003eworker0] **WARN logstash.outputs.elasticsearch - Failed action.** {:status=\u003e409, :action=\u003e[\"update\", {:id=\u003e\"%{id}\", :index=\u003e\"ta\", :type=\u003e\"events\", :routing=\u003enil, :retryon_conflict=\u003e1}, 2017-01-18T14:56:01.081Z %{host} %{message}], :response=\u003e{\"update\"=\u003e{\"index\"=\u003e\"ta\", \"type\"=\u003e\"events\", \"id\"=\u003e\"%{id}\", \"status\"=\u003e409, \"error\"=\u003e{\"type\"=\u003e\"**versionconflict_engine_exception**\", \"reason\"=\u003e\"**[events][%{id}]: version conflict, current version [453] is different than the one provided [452]**\", \"index_uuid\"=\u003e\"iomvsETXQVezDOCweq2gLQ\", \"shard\"=\u003e\"0\", \"index\"=\u003e\"ta\"}}}}\n","stream":"stdout","time":"2017-01-18T14:56:02.645718181Z"}
> ...

Also i was change number of cpu for docker from 1 to 2.

5.1.2 is  is a clean installation (elastic + logstash) to new clean docker instance.
Configuration is old. For example:

> jdbc {
> jdbc_connection_string => "jdbc:postgresql://..."
> jdbc_user => "postgres"
> jdbc_password => "pass"
> jdbc_driver_library => "/connectors/postgresql-9.4.1212.jar"
> jdbc_driver_class => "org.postgresql.Driver"
> schedule => "*/7 * * * *"
> statement => "SELECT id, name, updated_at::varchar, created_at::varchar FROM sale_types"
> type => "sale_types"
> }
> 
> ..
> output {
> elasticsearch {
> index => "ta"
> document_type => "%{type}"
> hosts => ["http://elastic:9200"]
> doc_as_upsert => true
> action => "update"
> document_id => "%{id}"
> }
> }

**Comment by bleskes** [comment] 2017-01-24 15:22
you are using the update action that can lead to version conflict rejects if there are concurrent modification to the same document. That I'm not sure you want to use the `action => "update"`  option when getting data from an SQL database. I'm going to close this as it is not a bug. If you need more information please ask on our forum on discuss.elastic.co . We try to keep github for issues and feature requests.

**Closed by bleskes** 2017-01-24 15:22 UTC
