### ISSUE TITLE
[CI] RecoveryIT testClosedIndexNoopRecovery failing

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#97896] opened 2023-07-24 12:20 UTC
**Build scan:**
https://gradle-enterprise.elastic.co/s/nnann4bjdvxxe/tests/:qa:rolling-upgrade:v8.9.0%23oneThirdUpgradedTest/org.elasticsearch.upgrades.RecoveryIT/testClosedIndexNoopRecovery

**Reproduction line:**
```
./gradlew ':qa:rolling-upgrade:v8.9.0#oneThirdUpgradedTest' -Dtests.class="org.elasticsearch.upgrades.RecoveryIT" -Dtests.method="testClosedIndexNoopRecovery" -Dtests.seed=B2CC9E996730905C -Dtests.bwc=true -Dtests.locale=ga-IE -Dtests.timezone=Asia/Yakutsk -Druntime.java=20
```

**Applicable branches:**
8.9

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.upgrades.RecoveryIT&tests.test=testClosedIndexNoopRecovery

**Failure excerpt:**
```
java.lang.AssertionError: must find replica

  at __randomizedtesting.SeedInfo.seed([B2CC9E996730905C:1EFE851D8E457298]:0)
  at org.junit.Assert.fail(Assert.java:88)
  at org.junit.Assert.assertTrue(Assert.java:41)
  at org.elasticsearch.upgrades.RecoveryIT.assertNoopRecoveries(RecoveryIT.java:644)
  at org.elasticsearch.upgrades.RecoveryIT.testClosedIndexNoopRecovery(RecoveryIT.java:511)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

**Comment by DaveCTurner** [comment] 2023-08-01 11:45
The problem is that the first node to restart took so long that the 2-minute delayed allocation timer expired and its shards were reassigned elsewhere:

```
$ cat v8.9.0-1/logs/es.out | grep NodeJoin
[2023-07-24T11:57:05,876][INFO ][o.e.c.c.NodeJoinExecutor ] [v8.9.0-1] node-join: [{v8.9.0-0}{GCUXxLMwRIa34nVaCu4UAQ}{rVGulul2R7SDiqVF2xJr2g}{v8.9.0-0}{127.0.0.1}{127.0.0.1:45279}{cdfhilmrstw}{8.9.0}] with reason [completing election]
[2023-07-24T11:57:05,879][INFO ][o.e.c.c.NodeJoinExecutor ] [v8.9.0-1] node-join: [{v8.9.0-1}{PEkZRY7sSJiHx6ICE0zXEw}{1Q0xvRvkRqyOapafTslVvA}{v8.9.0-1}{127.0.0.1}{127.0.0.1:41763}{cdfhilmrstw}{8.9.0}] with reason [completing election]
[2023-07-24T11:57:06,088][INFO ][o.e.c.c.NodeJoinExecutor ] [v8.9.0-1] node-join: [{v8.9.0-2}{08UzPVjoRLKaKK9dfCpKLg}{NtQFYuUhT26Z_8Vc6UF7xA}{v8.9.0-2}{127.0.0.1}{127.0.0.1:39461}{cdfhilmrstw}{8.9.0}] with reason [joining]
[2023-07-24T11:57:06,089][INFO ][o.e.c.c.NodeJoinExecutor ] [v8.9.0-1] node-join: [{v8.9.0-2}{08UzPVjoRLKaKK9dfCpKLg}{NtQFYuUhT26Z_8Vc6UF7xA}{v8.9.0-2}{127.0.0.1}{127.0.0.1:39461}{cdfhilmrstw}{8.9.0}] with reason [joining]
[2023-07-24T12:03:08,853][INFO ][o.e.c.c.NodeJoinExecutor ] [v8.9.0-1] node-join: [{v8.9.0-0}{GCUXxLMwRIa34nVaCu4UAQ}{d9vcL_ppS1GYlc-ZClhY-Q}{v8.9.0-0}{127.0.0.1}{127.0.0.1:40915}{cdfhilmrstw}{8.9.0}] with reason [joining after restart, removed [3.4m/207586ms] ago with reason [disconnected]]
```

Fixing this by making the timer much longer.

**Closed** 2023-08-01 12:51 UTC
Labels: >test-failure, :Distributed/Recovery, Team:Distributed
