### ISSUE TITLE
Unable to compile string as Pattern object in Painless

### ISSUE THREAD

**Issue by damntourists** [elastic/elasticsearch#28755] opened 2018-02-21 00:42 UTC
**Elasticsearch version** (`bin/elasticsearch --version`):
Elasticsearch 5.5.3

**Plugins installed**: []
None

**JVM version** (`java -version`):
% java -version
java version "1.7.0_151"
Java(TM) SE Runtime Environment (build 1.7.0_151-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.151-b15, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
% uname -a
Linux [HOSTNAME HERE] 2.6.32-696.10.2.el6.x86_64 #1 SMP Sun Sep 10 11:10:44 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
I am attempting to rewrite one of our legacy Groovy scripts in Painless and have been having some issues with regex splitting. 

In Groovy, a user could do `stringObjectHere.split(params.someRegexHere)`, however, in Painless, in order to do similar, I must do `Pattern p = /someRegexHere/; p.split(stringObjectHere);`. The problem for us is that our regex `someRegexHere` isn't constant and is supplied via params. Performing a `Pattern p = Pattern.compile(params.someRegexHere);` doesn't seem to work since Patterns.compile() isn't exposed. 

Any attempt to create a pattern results in errors like
```
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.regex.Pattern
```
or
```
Caused by: java.lang.IllegalArgumentException: Unknown call [compile] with [1] arguments on type [Pattern].
```

Doing `Pattern delimiter = /params.someRegexHere/;` doesn't throw an error and the Painless code doesn't work as expected. 

Is there another way to do this? 

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.  in python, 
```
es_connection.put_script(
                lang="painless", id="my_script",
                body={"script": "any painless code that attempts to convert String to Pattern"}
)
```
 2. query similar to the following
```
{'query': {'bool': {'filter': [{'term': {'seq': 'seq10'}}]}},
 'sort': [{'_script': {'order': 'asc',
                       'script': {'id': 'my_script',
                                  'lang': 'painless',
                                  'params': {'someRegexHere': '\._'}},
                       'type': 'string'}}]}
```
 3. 

**Provide logs (if relevant)**:

**Comment by jdconrad** [comment] 2018-02-21 22:48
Unfortunately, Painless doesn't allow this as all Patterns are considered constant at runtime due to complications with performance and casting.  A workaround for this would be to create a new stored script whenever a regex changes or if they change nearly every time use inline scripts instead.

**Comment by rjernst** [comment] 2018-02-22 00:01
Closing as this is working as designed.

**Closed by rjernst** 2018-02-22 00:01 UTC
Labels: :Core/Scripting

**Comment by damntourists** [comment] 2018-02-22 00:36
Thanks for the explanation @jdconrad!

**Comment by andrew-greiner** [comment] 2019-01-22 22:13
That is terrible news :(

Perhaps this is slightly off topic, but how would one do the following in an ingestion pipe-line:
1. For each naughty **word** in this array
2. Search for the word in the ingested document description field and if found set valid field to true

Any help would be appreciated because this was on preferred way, but it seems as though it won't work.
