### ISSUE TITLE
[CI] AggregationsIntegrationIT.testScroll() fails

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#26378] opened 2017-08-25 08:16 UTC
The test `org.elasticsearch.search.aggregations.AggregationsIntegrationIT.testScroll()` failed on CI today:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.0+oracle-periodic/343/

With:

> AggregationsIntegrationIT.testScroll <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: expected:<11> but was:<9>
   > 	at __randomizedtesting.SeedInfo.seed([938CB6F7E71EBAF6:A1DA451BDF1F32EB]:0)
   > 	at org.elasticsearch.search.aggregations.AggregationsIntegrationIT.testScroll(AggregationsIntegrationIT.java:72)
   > 	at java.lang.Thread.run(Thread.java:748)

It didn't reproduce with:
```
gradle :core:integTest -Dtests.seed=938CB6F7E71EBAF6 -Dtests.class=org.elasticsearch.search.aggregations.AggregationsIntegrationIT -Dtests.method="testScroll" -Dtests.security.manager=true -Dtests.locale=en-US -Dtests.timezone=Asia/Kuwait
```

The full console output is: 
[consoleText.txt](https://github.com/elastic/elasticsearch/files/1251248/consoleText.txt)

**Comment by jimczi** [comment] 2017-08-25 09:02
There is a connection failure to one node during the tests. The two documents missing may come from that node, that would explain why the scroll only sees 9 out of 11 documents:

`````
[2017-08-25T06:54:52,071][WARN ][o.e.c.NodeConnectionsService] [node_s1] failed to connect to node {node_s0}{nf4GnuydSP66xJDkBMJJaA}{KyOvUcWnRdGzRF_t6IAlng}{127.0.0.1}{127.0.0.1:9440} (tried [1] times)
  1> org.elasticsearch.transport.ConnectTransportException: [node_s0][127.0.0.1:9440] general node connection failure
  1> 	at org.elasticsearch.transport.TcpTransport.openConnection(TcpTransport.java:609) ~[main/:?]
  1> 	at org.elasticsearch.transport.TcpTransport.connectToNode(TcpTransport.java:495) ~[main/:?]
  1> 	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:325) ~[main/:?]
  1> 	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:312) ~[main/:?]
  1> 	at org.elasticsearch.cluster.NodeConnectionsService.validateAndConnectIfNeeded(NodeConnectionsService.java:154) ~[main/:?]
  1> 	at org.elasticsearch.cluster.NodeConnectionsService$1.doRun(NodeConnectionsService.java:107) ~[main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) ~[main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[main/:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_144]
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_144]
````

I'll monitor the tests for some days and close it if it does not reproduce.

**Comment by jimczi** [comment] 2017-10-31 13:42
Did not reproduced since August so closing this as non-issue

**Closed by jimczi** 2017-10-31 13:42 UTC
Labels: jenkins, test, v6.0.0

**Comment by imotov** [comment] 2017-11-28 14:56
Just failed in 5.6 https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+multijob-windows-compatibility/381/console

**Comment by jimczi** [comment] 2017-11-28 15:24
Thanks @imotov , I think that the scroll timeouts during the execution of the test. I raised the scroll timeout to 1 minute (500ms was too low and could fail on some shard if the machine is slow):
https://github.com/elastic/elasticsearch/commit/37653c9dca1bf59574c9bdddaadc378c7d1f6337
I'll reopen if this reproduces with this new commit
