### ISSUE TITLE
[CI] testAllTestTasksIncluded fails from time to time

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#45909] opened 2019-08-23 15:11 UTC
org.elasticsearch.gradle.precommit.TestingConventionsTasksIT testAllTestTasksIncluded failed on master:

Recent failure:
Log:https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob+fast+part1/922/console
Build Scans: https://gradle-enterprise.elastic.co/s/vo5ju3bula6zm

```
java.lang.AssertionError: 
Expected the following line in output:

Test classes are not included in any enabled task (:all_classes_in_tasks:test):

Output is:
The client will now receive all logging from the daemon (pid: 46221). The daemon log file: /tmp/junit17329564500544085697/junit15086427948623241831/test-kit-daemon/5.5/daemon-46221.out.log
```

The test failure doesn't seem related to the test, but issues with a build.

**Comment by mayya-sharipova** [comment] 2019-08-23 15:39
There is another test fails from time to time with related failure: org.elasticsearch.gradle.precommit.TestingConventionsTasksIT testTaskNotImplementBaseClass

Recent failure:
Log:https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob+fast+part1/890/console
Build Scans: https://gradle-enterprise.elastic.co/s/v4logf2obbnim
```
java.lang.AssertionError: 
Expected the following line in output:

Tests classes with suffix `IT` should extend org.elasticsearch.gradle.testkit.Integration but the following classes do not:

Output is:
The client will now receive all logging from the daemon (pid: 15035). The daemon log file: /tmp/junit9443843576232958656/junit3816899034882796784/test-kit-daemon/5.5/daemon-15035.out.log
```

**Comment by atorok** [comment] 2019-09-02 08:32
root cause: https://gradle-enterprise.elastic.co/s/vo5ju3bula6zm/tests/orjfcz7hu5lqq-ndxrm7wivi23e 
```
* What went wrong:
Execution failed for task ':all_classes_in_tasks:compileTestJava'.
> Could not resolve all files for configuration ':all_classes_in_tasks:testCompileClasspath'.
   > Could not download junit.jar (junit:junit:4.12)
      > Could not get resource 'https://jcenter.bintray.com/junit/junit/4.12/junit-4.12.jar'.
         > Could not GET 'https://d29vzk4ow07wi7.cloudfront.net/2973d150c0dc1fefe998f834810d68f278ea58ec?response-content-disposition=attachment%3Bfilename%3D%22junit-4.12.jar%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvMjk3M2QxNTBjMGRjMWZlZmU5OThmODM0ODEwZDY4ZjI3OGVhNThlYz9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMmp1bml0LTQuMTIuamFyJTIyIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNTY2NTcxOTk4fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjAuMC4wLjAvMCJ9fX1dfQ__&Signature=eb9kYWMmlFFcP76PhpGbINiv2n8Pi~VSDekzY5SrEtG4OEZ-uAS-7N~HbJGUWmy1p-WsxO2xIcgeAb4cj3z8NrjzAWDpSwLaryJP0mXWdj1wKv0M3OYRn2TZ2BRVyZtr6ACADAM6ju9x6KvxqUZicLNYo5XmzSKPP7a1jLyydvfStEwu4iXVPORsQFuyZ5pd1ymCNe7eOlmtgapCctPFlyOQnNTaCdA0lMqiqpdXvI80CLk95Mlw7CD1p~NcULvtMLEHE6DfcJV7fhuDgnHu-QO4zAJJOMsHi~J0uQEJP8ZqbNVayEZlIFWMU3kCoHwwecdIo31BzwgqeN7LaeoxCQ__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA'.
            > d29vzk4ow07wi7.cloudfront.net: Name or service not known
```

**Comment by atorok** [comment] 2019-09-02 08:33
Duplicate of #45568

**Closed by atorok** 2019-09-02 08:33 UTC
Labels: :Core/Infra/Build, >test-failure
