### ISSUE TITLE
 elasticsearch returns inconsistent result on v7.8.1 and returns correct result on v5.6.7 for the same match_phrase_prefix query

### ISSUE THREAD

**Issue by animeshmdhokare** [elastic/elasticsearch#81718] opened 2021-12-14 11:40 UTC
Hi @markharwood,
Thanks for quick reply.

We have created a dataset where 8910 documents contain field "name" which starts with value "Trust"
and 991 documents contain the same field which does not start with "Trust". Hence the total doc count is 9901(8910+991).

In above result section , we are trying to search 
1. String that starts with "Trust" _(should query)_ and expect that it will return correct doc count i.e. 8910 
2. String that does not start with "Trust" _(must_not query)_ and expect that it will return correct doc count i.e. 991

If we try to execute query mentioned in the ticket, on v5.6.7, we get correct results for point 1 and 2. But for the same query we observe different set of results on 7.8.1 **_(i.e for "must_not" query we are getting strings which starts with "Trust" which is wrong result leading to wrong doc count)_**

On v7.8.1, when we increased _max_expansion from 50 to 10000_, the same query started giving correct results(mentioned in point 1 & 2). We are getting the _wrong results in sorted order_ provided in query.

Although, increasing max_expansion to certain number gives correct result, it comes with performance issues. Also, we can not identify correct value for larger datasets available in production environments. 
Below is the result on 1M documents.
<img width="423" alt="els_bug" src="https://user-images.githubusercontent.com/19922659/145986823-869215c5-f902-4be4-b823-2f8f7d40a604.png">

I'm running the same query back to back on an index and results come back different for each hit. How can I get consistent result on v7.8.1? Is there any specific change related to "match_phrase_query" implemented on v7.8.1 as compared to v5.6.7?
Can you please try to reproduce this at your end and see if you can get some pointers over this? Do we need to perform any server side config operations to get consistent result set for "match_phrase_query" on v7.8.1? Please suggest.

_Originally posted by @animeshmdhokare in https://github.com/elastic/elasticsearch/issues/81702#issuecomment-993448837_

**Comment by markharwood** [comment] 2021-12-14 11:41
Closing as duplicate of #81702

**Closed by markharwood** 2021-12-14 11:41 UTC
