### ISSUE TITLE
[Documentation] Coverage of boolean operator precedence in query_string is inaccurate

### ISSUE THREAD

**Issue by mrec** [elastic/elasticsearch#24847] opened 2017-05-23 16:26 UTC
**Elasticsearch version**: 2.3.2

**Plugins installed**: [analysis-icu 2.3.2, analysis-korean 2.3.2, analysis-kuromoji 2.3.2, analysis-smartcn 2.3.2, analysis-stconvert 1.8.3, delete-by-query 2.3.2, enhanced-highlighter 2.3.2-1.6, enhanced-plain-highlighter 2.3.2-1.7, entsearch 2.3.2-1.6, head master, license 2.3.2, marvel-agent 2.3.2, reindex 2.3.2,
repository-hdfs 2.3.1]

**JVM version**: 1.8.0

**OS version**: Oracle Linux Server 6.5

**Description of the problem including expected versus actual behavior**:

Even in 5.4, the docs on [Query String Query > Boolean operators](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/query-dsl-query-string-query.html#_boolean_operators) still state that

> `NOT` takes precedence over `AND`, which takes precedence over `OR`.

which in the absence of explicit parens is demonstrably not the case. Comments on #9414 and #13100 (both linking to [this article](https://lucidworks.com/2011/12/28/why-not-and-or-and-not/)) make it clear that Lucene does not work that way and that this is highly unlikely to change.

Suggest replacing the text 

> However, the effects of these operators can be more complicated than is obvious at first glance. NOT takes precedence over AND, which takes precedence over OR. While the + and - only affect the term to the right of the operator, AND and OR can affect the terms to the left and right.

with something along the lines of

> However, due to Lucene quirks, these operators behave unpredictably when mixed unless precedence is explicitly forced using matched parentheses. This includes e.g. mixtures of implicit (`"default_operator":"AND"`) and explicit (`"query":"foo OR bar"`) operators.

**Steps to reproduce**:

```
PUT mrec
{
  "mappings": {
    "doc": {
      "properties": {
        "s": {
          "type": "string",
          "analyzer": "standard"
        }
      }
    }
  }
}

PUT mrec/doc/1
{
  "s":"apple"
}

PUT mrec/doc/2
{
  "s":"banana split"
}

GET mrec/_search
{
  "query": {
    "query_string": {
      "query": "s:(apple OR banana AND split)"
    }
  }
}
```

Based on the documentation I expected both docs to match, i.e. that the query would be treated like `s:(apple OR (banana AND split))`. It's actually interpreted as `+(s:apple s:banana) +s:split`, i.e. only the `banana split` doc matches.

**Comment by colings86** [comment] 2017-05-25 08:50
@mrec I think the documentation is correct here and working as expected because the OR and AND operators are expected to act on the arguments left and right of them much like `+`, `-`, `*`, `/` do in arithmetic. This is, at least from my experience, normal behaviour for boolean operators too (except NOT which is a unary operator os only acts on the argument to the right of it)

When you specify `A AND B` you are saying that the query should match only if both A and B evaluate to true. When precedence is defined it dictates the order in which the operators are evaluated and each operator assumes only the __immediate argument either side of it at that point in the evaluation__. So if you specify `A OR B AND C` it will first evaluate the `AND` operator with only the arguments immediately either side of the operator so in this case it will evaluate `B AND C`. Lets assume that evaluates to `true`, the expression then becomes `A OR true`, then the OR operator can be evaluated to complete the expression and obtain a result.

I don't believe this is a quirk of Lucene or Elasticsearch, as far as I know its the way boolean precedence is usually defined (in some cases no precedence is defined and the order of evaluation is strictly left to right but when it is defined I believe its always defined this way).

**Comment by colings86** [comment] 2017-05-25 09:00
Sorry, ignore the above, you are right that there is an issue, exactly because of what I wrote above 😄

**Comment by colings86** [comment] 2017-05-25 09:10
We should fix the documentation to explain the unexpected behaviour of using `AND` and `OR` in the `query_string` query and IMO we should also encourage people to not use `NOT/AND/OR` and instead use the `+/-` unary operators to define what should, must, and must not match for a document to be considered a hit much like the conclusion of [the article linked above suggests](https://lucidworks.com/2011/12/28/why-not-and-or-and-not/).

**Comment by ekalgolas** [comment] 2018-08-27 11:11
@mrec @colings86 This is already fixed in master. The doc now states:

The familiar boolean operators `AND`, `OR` and `NOT` (also written `&&`, `||`
and `!`) are also supported but beware that they do not honor the usual
precedence rules, so parentheses should be used whenever multiple operators are
used together. For instance the previous query could be rewritten as:

`((quick AND fox) OR (brown AND fox) OR fox) AND NOT news`::

This form now replicates the logic from the original query correctly, but
the relevance scoring bears little resemblance to the original.

In contrast, the same query rewritten using the <<query-dsl-match-query,`match` query>>
would look like this:

    {
        "bool": {
            "must":     { "match": "fox"         },
            "should":   { "match": "quick brown" },
            "must_not": { "match": "news"        }
        }
    }

**Comment by kat257** [comment] 2019-04-05 18:17
Locations to be corrected: 
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_boolean_operators
https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/java-full-text-queries.html

**Comment by mrec** [comment] 2019-04-05 20:00
Agreed, the new text looks fine to me. Happy for this to be closed as fixed.

(I must have missed the update from @ekalgolas - apologies)

**Comment by jimczi** [comment] 2019-05-07 07:17
Docs are already updated so I am closing this issue.

**Closed by jimczi** 2019-05-07 07:17 UTC
Labels: :Search/Search, >docs, help wanted
