### ISSUE TITLE
uneven shard allocation when adding new nodes

### ISSUE THREAD

**Issue by jgq2008303393** [elastic/elasticsearch#37638] opened 2019-01-20 13:08 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): ES 6.4.3

**JVM version** (`java -version`): 1.8.0_181

**OS version** (`uname -a` if on a Unix-like system): Ubuntu 16.04.5 LTS

**Description of the problem including expected versus actual behavior**:
For clusters with insufficient disk space, when doing scale-out operation, we often encounter the following problem: After we added 5 new nodes to the 20-node cluster,  almost all the new shards created the next day were allocated to the 5 new nodes. As the 5 new nodes were not able to cover the bulk pressure, the scale-out operation cause a lot of bulk rejections.

We have encountered this problem several times, and we used to set index.routing.allocation.total_shards_per_node to control this situation. Although it works, but is very troublesome to operate when there are many clusters. 

We have traced the process of create-index, and found that the shard allocation is mainly decided by 
the combination of node-level and index-level balance：
```
        private float weight(Balancer balancer, ModelNode node, String index, int numAdditionalShards) {
            final float weightShard = node.numShards() + numAdditionalShards - balancer.avgShardsPerNode();
            final float weightIndex = node.numShards(index) + numAdditionalShards - balancer.avgShardsPerNode(index);
            return theta0 * weightShard + theta1 * weightIndex;
        }
```
This policy is good for rebalance operation, but bad for new shard allocation. For example, when old nodes has 100 shards and new nodes has 10 shards, the new shards are tend to place on the new nodes 
 which have smaller weight.

**Solution**:
For new shard allocation, we think it's better to just consider index-level balance, so that the new shards are evenly distributed across all nodes. And the rebalance operation will do node-level balance asynchronously.

**Comment by DaveCTurner** [comment] 2019-01-21 08:44
This duplicates #17213, and the solution we would like to implement is described in 
https://github.com/elastic/elasticsearch/issues/17213#issuecomment-383974707.

I do not think that treating new shards differently from existing ones is a good idea. Elasticsearch's behaviour today is desirable in some cases, and the proposed change could cause many unnecessary and expensive relocations. Additionally, rebalancing the already-assigned shards may simply immediately undo the effects of the change proposed here.

We would like to add more control as described in the linked issue, but for now I think the solution is to set `total_shards_per_node`. Can you explain why this is "troublesome to operate"? It seems straightforward enough to set this value in the index templates as nodes are added to the cluster. An alternative is to use [allocation filtering](https://www.elastic.co/guide/en/elasticsearch/reference/current/shard-allocation-filtering.html) to give finer control over the nodes to which shards are assigned, again using index templates.

**Comment by jgq2008303393** [comment] 2019-01-22 14:35
@DaveCTurner Thanks for your reply.

> Can you explain why this is "troublesome to operate"?

total_shards_per_node is a mandatory rule. As we have many clusters and many users, it's easy to lead cluster yellow or even red.

> the proposed change could cause many unnecessary and expensive relocations. Additionally, rebalancing the already-assigned shards may simply immediately undo the effects of the change proposed here.

As relocation will consider both node-level and index-level balance, we think that ES will tend to move some old shards to the new nodes, and not to move new shards back to old nodes instead of moving the new shards to the old nodes. The proposed change should not cause too much useless relocations.

Is there any problem with my understanding, or what is missing?

**Comment by jgq2008303393** [comment] 2019-01-23 01:52
The solution described in #17213 (comment) is good too, is there any plan about it recently?

**Comment by jgq2008303393** [comment] 2019-01-23 13:38
ping @DaveCTurner

**Comment by DaveCTurner** [comment] 2019-01-23 17:40
Responding here is on my list of tasks, and I will get to it. There is no need to ping me for a response a few hours after your last message.

**Comment by jgq2008303393** [comment] 2019-01-24 05:43
Ok, I'm very much looking forward to your reply.

**Comment by DaveCTurner** [comment] 2019-01-30 09:04
Ok, yes, I think the long-term solution for these issues is what we're discussing in #17213. As an interim measure you can prevent new indices from being allocated to the mostly-empty new nodes by adding a [shard allocation filter](https://www.elastic.co/guide/en/elasticsearch/reference/current/shard-allocation-filtering.html) to the relevant index template while the cluster is rebalancing. I'm closing this as a duplicate of the other issue, but would like to say thanks for raising this idea and the subsequent discussion.

**Closed by DaveCTurner** 2019-01-30 09:04 UTC
Labels: :Distributed/Allocation, feedback_needed
