### ISSUE TITLE
Delete index : inconsistent behavior when using a concrete index and a wildcard

### ISSUE THREAD

**Issue by olcbean** [elastic/elasticsearch#24104] opened 2017-04-14 09:39 UTC
In the corner case when the index does not exist, delete index with a concrete index will throw and if a wildcard is used, the request will succeed.
```
PUT test
DELETE test
DELETE test
```
```
"root_cause": [
      {
        "type": "index_not_found_exception",
        "reason": "no such index",
        "resource.type": "index_or_alias",
        "resource.id": "test",
        "index_uuid": "_na_",
        "index": "test"
      }
```  

```
PUT test
DELETE test*
DELETE test*
```
```
"acknowledged": true
``` 
Note : in the above example `test*` can  be replaced with `*` or `_all` (result will be `"acknowledged": true`

Is this the intended behavior?

---
At the same time I think it contradicts the behavior for `_open` and `_close` (#24031) where if all  indices are open and a concrete index is passed to `_open` the request will succeed and if a wildcard is used an error is returned (just the opposite to DELETE).

**Comment by javanna** [comment] 2017-04-14 15:34
thanks for raising this @olcbean ! Indeed the Delete api is a no-op in case the index expression doesn't match any index. I think this is the intended behaviour, but it is odd that the default is lenient, as we throw an exception against a non existing concrete index, but we don't if an index expression doesn't match anything. That is because ignore_unavailable is set to `false` by default, while `allow_no_indices` is set to `true` by default. I think we should change that in 6.0.

**Comment by javanna** [comment] 2017-04-14 15:37
Feel free to send a PR @olcbean and ping me for review.

**Comment by olcbean** [comment] 2017-04-14 16:52
@javanna thanks :) 
I will change the delete to a no-op in both cases.

**Comment by olcbean** [comment] 2017-04-15 14:07
> I will change the delete to a no-op in both cases.

Errr I meant to write exactly the opposite :)

I will proceed to change the default for `allow_no_indices` to a `false` in 6.0, and also adjust `delete` not matching an index to
 - throw when `allow_no_indices` is false
 - become a no-op when `allow_no_indices` is true

**Comment by javanna** [comment] 2017-04-15 15:42
hey @olcbean the second part was about open/close rather than delete right?

**Comment by olcbean** [comment] 2017-04-15 18:48
Well, I thought for both:) Maybe I misunderstood you, @javanna. Let me elaborate a little bit.
 
If I just change the default for `allow_no_indices=false` then both `DELETE test` and `DELETE test*` will throw (ok) but
`DELETE test?allow_no_indices=true` throws as
`DELETE test*?allow_no_indices=true` will succeed.

So the change will simply push the inconsistency to appear only when the `allow_no_indices=true` is explicitly set.

Am I missing something?

**Comment by javanna** [comment] 2017-04-18 09:36
sounds good @olcbean you got it :)

**Comment by javanna** [comment] 2017-04-28 15:28
heya @olcbean as I said in the PR, while I was reviewing it I realized that it was going to break existing code and maybe we should rather adapt open/close to this behaviour. This also resulted from a discussion with @clintongormley . For this reason I closed the PR and I am going to close this as a won't fix. Once again, sorry about changing my mind and thanks for your help on this and other issues!

**Closed by javanna** 2017-04-28 15:28 UTC
Labels: :Index APIs, adoptme, enhancement, low hanging fruit
