### ISSUE TITLE
Installer for 5.0.0-rc1 does not create service, nor config on Deb

### ISSUE THREAD

**Issue by oazabir** [elastic/elasticsearch#21083] opened 2016-10-22 21:31 UTC
Just tried installing 5.0.0-rc1 on Ubuntu. The apt-get install did not create any service, nor any configuration. /etc/elasticsearch is empty. Folder is there, no file inside. 

Not able to start ES at all.

**Comment by tlrx** [comment] 2016-10-24 06:56
@oazabir Thanks for reporting! Can you please indicate the version of Ubuntu as well as the output of the command?

**Comment by oazabir** [comment] 2016-10-24 10:57
Ubuntu 14.04 LTS (GNU/Linux 2.6.32-042stab117.16 x86_64)

**Comment by oazabir** [comment] 2016-10-24 10:58
I installed the latest .deb package manually using dpkg and then it installed the stuff properly and got it to run.

**Comment by oazabir** [comment] 2016-10-24 10:59
Another issue, I had the 2.x version installed before. Which I removed and then tried to install the new version. I did get questions asked about what to do with launch script, config file etc when I tried to install manually using dpkg. But when I tried to install using apt-get, it did not ask me anything.

**Comment by jasontedor** [comment] 2016-10-24 11:16
This does not reproduce for me, the service is there (`/etc/init.d/elasticsearch`) and so are the config files.

Are you sure that you had the right permissions when you tried to view `/etc/elasticsearch`? Since `/etc` is visible (`rwxr-xr-x root root`) but `/etc/elasticsearch` is not (`rwxr-x--- root elasticsearch`), you'll be able to see the directory but not its contents unless you're running as a user with the right permissions.

**Comment by oazabir** [comment] 2016-10-24 11:40
I am the root. 
In order to repro, you will probably have to do the following:

Install ES 2.x
Uninstall ES 2.x
Install ES 5 using apt-get.

**Comment by jasontedor** [comment] 2016-10-24 12:41
This still does not reproduce for me, even with your proposed steps. Can you please provide either a reliable reproduction or the output that @tlrx asked for?

**Comment by nik9000** [comment] 2016-10-25 19:02
We test this as part of the build so I expect something is up with your
system. Can you reproduce this on a clean install?

**Comment by jasontedor** [comment] 2016-10-26 20:43
No feedback, closing.

**Closed by jasontedor** 2016-10-26 20:43 UTC
Labels: :Packaging, feedback_needed, v5.0.0-rc1
