### ISSUE TITLE
Test Failure: org.elasticsearch.test.rest.IntegTestZipClientYamlTestSuiteIT

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#23725] opened 2017-03-23 18:50 UTC
Unable to reproduce locally on Arch, but this appears to only occur on Windows.

Reproduce With:

gradle :distribution:integ-test-zip:integTestRunner -Dtests.seed=3864EF39B7D9E888 -Dtests.class=org.elasticsearch.test.rest.IntegTestZipClientYamlTestSuiteIT -Dtests.method="test {p0=indices.put_mapping/all_path_options/put mapping with missing type}" -Dtests.security.manager=true -Dtests.nightly=false -Dtests.heap.size=555m -Dtests.jvm.argline="-server -XX:+UseConcMarkSweepGC -XX:+UseCompressedOops -XX:+AggressiveOpts" -Dtests.locale=en-PH -Dtests.timezone=CTT

Build Failure:

http://build-us-00.elastic.co/job/es_core_master_windows-2012-r2/5115/console

**Comment by jasontedor** [comment] 2017-03-23 18:58
The REST tests fail non-stop on Windows CI due to suite timeouts like we see here, it's been this way for months. There appear to be odd performance issues. The issue is under investigation, so I think we can close this specific test failure out.

**Closed by jasontedor** 2017-03-23 18:58 UTC
Labels: test, v6.0.0

**Comment by jdconrad** [comment] 2017-03-23 19:15
@jasontedor Sorry for the noise here then.

**Comment by jasontedor** [comment] 2017-03-23 19:26
> Sorry for the noise here then.

No worries at all!
