### ISSUE TITLE
index_failed_engine_exception Index failed for translog is already closed status 500

### ISSUE THREAD

**Issue by waheed1947** [elastic/elasticsearch#23871] opened 2017-04-03 06:15 UTC
ES Version : 2.3.3
Laravel version : 5.0

When we update indexes most of them updated successfully but some indexes not updated.
Share My Error Log

ServerErrorResponseException in Connection.php line 659:
index_failed_engine_exception: Index failed for [sources#10475977]
in Connection.php line 659
at Connection->tryDeserializeError(array('transfer_stats' => array('url' => '', 'content_type' => 'application/json; charset=UTF-8', 'http_code' => 500, 'header_size' => 106, 'request_size' => 804, 'filetime' => -1, 'ssl_verify_result' => 0, 'redirect_count' => 0, 'total_time' => 0.51500000000000001, 'namelookup_time' => 0, 'connect_time' => 0.249, 'pretransfer_time' => 0.249, 'size_upload' => 712, 'size_download' => 361, 'speed_download' => 700, 'speed_upload' => 1382, 'download_content_length' => 361, 'upload_content_length' => 712, 'starttransfer_time' => 0.51500000000000001, 'redirect_time' => 0, 'redirect_url' => '', 'primary_ip' => '70.32.82.156', 'certinfo' => array(), 'primary_port' => 9200, 'local_ip' => '192.168.1.106', 'local_port' => 51589, 'error' => '', 'errno' => 0), 'curl' => array('error' => '', 'errno' => 0), 'effective_url' => '', 'headers' => array('Content-Type' => array('application/json; charset=UTF-8'), 'Content-Length' => array('361')), 'version' => '1.1', 'status' => 500, 'reason' => 'Internal Server Error', 'body' => '{"error":{"root_cause":[{"type":"index_failed_engine_exception","reason":"Index failed for [sources#10475977]","shard":"2","index":"verbingo"}],"type":"index_failed_engine_exception","reason":"Index failed for [sources#10475977]","shard":"2","index":"verbingo","caused_by":{"type":"already_closed_exception","reason":"translog is already closed"}},"status":500}'), 'Elasticsearch\\Common\\Exceptions\\ServerErrorResponseException') in Connection.php line 638
at Connection->tryDeserialize500Error(array('transfer_stats' => array('url' => '', 'content_type' => 'application/json; charset=UTF-8', 'http_code' => 500, 'header_size' => 106, 'request_size' => 804, 'filetime' => -1, 'ssl_verify_result' => 0, 'redirect_count' => 0, 'total_time' => 0.51500000000000001, 'namelookup_time' => 0, 'connect_time' => 0.249, 'pretransfer_time' => 0.249, 'size_upload' => 712, 'size_download' => 361, 'speed_download' => 700, 'speed_upload' => 1382, 'download_content_length' => 361, 'upload_content_length' => 712, 'starttransfer_time' => 0.51500000000000001, 'redirect_time' => 0, 'redirect_url' => '', 'primary_ip' => '70.32.82.156', 'certinfo' => array(), 'primary_port' => 9200, 'local_ip' => '192.168.1.106', 'local_port' => 51589, 'error' => '', 'errno' => 0), 'curl' => array('error' => '', 'errno' => 0), 'effective_url' => '', 'headers' => array('Content-Type' => array('application/json; charset=UTF-8'), 'Content-Length' => array('361')), 'version' => '1.1', 'status' => 500, 'reason' => 'Internal Server Error', 'body' => '{"error":{"root_cause":[{"type":"index_failed_engine_exception","reason":"Index failed for [sources#10475977]","shard":"2","index":"verbingo"}],"type":"index_failed_engine_exception","reason":"Index failed for [sources#10475977]","shard":"2","index":"verbingo","caused_by":{"type":"already_closed_exception","reason":"translog is already closed"}},"status":500}')) in Connection.php line 601
at Connection->process5xxError(array('http_method' => 'PUT', 'scheme' => 'http', 'uri' => '/verbingo/sources/10475977', 'body' => '{"id":10475977,"project_id":1470031884,"position":1,"content":"LiveClicks","comment":"","selected_translation":"LiveClicks","word_count":1,"idml_pdffile":null,"backup":1,"modified":"0","comments":null,"keyValue":null,"project":{"id":1470031884,"user_id":11098,"title":"My way file 1","type":3,"src_language":"en","tar_language":"hi","src_count":15,"tar_count":15,"time_created":"2017-03-25 03:35:01","time_dedline":"0000-00-00 00:00:00","time_last_active":"2017-03-25 03:30:58","old_id":null,"visible_status":0,"backup":1,"modified":"0","comments":null,"project_number":"","assigned_user_id":0,"dashboard_id":0,"billing_option":0,"website_project":0,"total_matched":2,"total_words":124,"project_percentage":"2"}}', 'headers' => array('host' => array('verbingotms.com:9200'))), array('transfer_stats' => array('url' => '', 'content_type' => 'application/json; charset=UTF-8', 'http_code' => 500, 'header_size' => 106, 'request_size' => 804, 'filetime' => -1, 'ssl_verify_result' => 0, 'redirect_count' => 0, 'total_time' => 0.51500000000000001, 'namelookup_time' => 0, 'connect_time' => 0.249, 'pretransfer_time' => 0.249, 'size_upload' => 712, 'size_download' => 361, 'speed_download' => 700, 'speed_upload' => 1382, 'download_content_length' => 361, 'upload_content_length' => 712, 'starttransfer_time' => 0.51500000000000001, 'redirect_time' => 0, 'redirect_url' => '', 'primary_ip' => '70.32.82.156', 'certinfo' => array(), 'primary_port' => 9200, 'local_ip' => '192.168.1.106', 'local_port' => 51589, 'error' => '', 'errno' => 0), 'curl' => array('error' => '', 'errno' => 0), 'effective_url' => '', 'headers' => array('Content-Type' => array('application/json; charset=UTF-8'), 'Content-Length' => array('361')), 'version' => '1.1', 'status' => 500, 'reason' => 'Internal Server Error', 'body' => '{"error":{"root_cause":[{"type":"index_failed_engine_exception","reason":"Index failed for [sources#10475977]","shard":"2","index":"verbingo"}],"type":"index_failed_engine_exception","reason":"Index failed for [sources#10475977]","shard":"2","index":"verbingo","caused_by":{"type":"already_closed_exception","reason":"translog is already closed"}},"status":500}'), array()) in Connection.php line 267
at Connection->Elasticsearch\Connections\{closure}(array('transfer_stats' => array('url' => '', 'content_type' => 'application/json; charset=UTF-8', 'http_code' => 500, 'header_size' => 106, 'request_size' => 804, 'filetime' => -1, 'ssl_verify_result' => 0, 'redirect_count' => 0, 'total_time' => 0.51500000000000001, 'namelookup_time' => 0, 'connect_time' => 0.249, 'pretransfer_time' => 0.249, 'size_upload' => 712, 'size_download' => 361, 'speed_download' => 700, 'speed_upload' => 1382, 'download_content_length' => 361, 'upload_content_length' => 712, 'starttransfer_time' => 0.51500000000000001, 'redirect_time' => 0, 'redirect_url' => '', 'primary_ip' => '70.32.82.156', 'certinfo' => array(), 'primary_port' => 9200, 'local_ip' => '192.168.1.106', 'local_port' => 51589, 'error' => '', 'errno' => 0), 'curl' => array('error' => '', 'errno' => 0), 'effective_url' => '', 'headers' => array('Content-Type' => array('application/json; charset=UTF-8'), 'Content-Length' => array('361')), 'version' => '1.1', 'status' => 500, 'reason' => 'Internal Server Error', 'body' => resource)) in FulfilledPromise.php line 25
at FulfilledPromise->then(object(Closure), null, null) in CompletedFutureValue.php line 55
at CompletedFutureValue->then(object(Closure), null, null) in Core.php line 341
at Core::proxy(object(CompletedFutureArray), object(Closure)) in Connection.php line 285
at Connection->Elasticsearch\Connections\{closure}(array('http_method' => 'PUT', 'scheme' => 'http', 'uri' => '/verbingo/sources/10475977', 'body' => '{"id":10475977,"project_id":1470031884,"position":1,"content":"LiveClicks","comment":"","selected_translation":"LiveClicks","word_count":1,"idml_pdffile":null,"backup":1,"modified":"0","comments":null,"keyValue":null,"project":{"id":1470031884,"user_id":11098,"title":"My way file 1","type":3,"src_language":"en","tar_language":"hi","src_count":15,"tar_count":15,"time_created":"2017-03-25 03:35:01","time_dedline":"0000-00-00 00:00:00","time_last_active":"2017-03-25 03:30:58","old_id":null,"visible_status":0,"backup":1,"modified":"0","comments":null,"project_number":"","assigned_user_id":0,"dashboard_id":0,"billing_option":0,"website_project":0,"total_matched":2,"total_words":124,"project_percentage":"2"}}', 'headers' => array('host' => array('verbingotms.com:9200'))), object(Connection), object(Transport), array()) in Connection.php line 161
at Connection->performRequest('PUT', '/verbingo/sources/10475977', array(), array('id' => 10475977, 'project_id' => 1470031884, 'position' => 1, 'content' => 'LiveClicks', 'comment' => '', 'selected_translation' => 'LiveClicks', 'word_count' => 1, 'idml_pdffile' => null, 'backup' => 1, 'modified' => '0', 'comments' => null, 'keyValue' => null, 'project' => array('id' => 1470031884, 'user_id' => 11098, 'title' => 'My way file 1', 'type' => 3, 'src_language' => 'en', 'tar_language' => 'hi', 'src_count' => 15, 'tar_count' => 15, 'time_created' => '2017-03-25 03:35:01', 'time_dedline' => '0000-00-00 00:00:00', 'time_last_active' => '2017-03-25 03:30:58', 'old_id' => null, 'visible_status' => 0, 'backup' => 1, 'modified' => '0', 'comments' => null, 'project_number' => '', 'assigned_user_id' => 0, 'dashboard_id' => 0, 'billing_option' => 0, 'website_project' => 0, 'total_matched' => 2, 'total_words' => 124, 'project_percentage' => '2')), array(), object(Transport)) in Transport.php line 106
at Transport->performRequest('PUT', '/verbingo/sources/10475977', array(), array('id' => 10475977, 'project_id' => 1470031884, 'position' => 1, 'content' => 'LiveClicks', 'comment' => '', 'selected_translation' => 'LiveClicks', 'word_count' => 1, 'idml_pdffile' => null, 'backup' => 1, 'modified' => '0', 'comments' => null, 'keyValue' => null, 'project' => array('id' => 1470031884, 'user_id' => 11098, 'title' => 'My way file 1', 'type' => 3, 'src_language' => 'en', 'tar_language' => 'hi', 'src_count' => 15, 'tar_count' => 15, 'time_created' => '2017-03-25 03:35:01', 'time_dedline' => '0000-00-00 00:00:00', 'time_last_active' => '2017-03-25 03:30:58', 'old_id' => null, 'visible_status' => 0, 'backup' => 1, 'modified' => '0', 'comments' => null, 'project_number' => '', 'assigned_user_id' => 0, 'dashboard_id' => 0, 'billing_option' => 0, 'website_project' => 0, 'total_matched' => 2, 'total_words' => 124, 'project_percentage' => '2')), array()) in AbstractEndpoint.php line 80
at AbstractEndpoint->performRequest() in Client.php line 791
at Client->index(array('index' => 'verbingo', 'type' => 'sources', 'id' => 10475977, 'body' => array('id' => 10475977, 'project_id' => 1470031884, 'position' => 1, 'content' => 'LiveClicks', 'comment' => '', 'selected_translation' => 'LiveClicks', 'word_count' => 1, 'idml_pdffile' => null, 'backup' => 1, 'modified' => '0', 'comments' => null, 'keyValue' => null, 'project' => array('id' => 1470031884, 'user_id' => 11098, 'title' => 'My way file 1', 'type' => 3, 'src_language' => 'en', 'tar_language' => 'hi', 'src_count' => 15, 'tar_count' => 15, 'time_created' => '2017-03-25 03:35:01', 'time_dedline' => '0000-00-00 00:00:00', 'time_last_active' => '2017-03-25 03:30:58', 'old_id' => null, 'visible_status' => 0, 'backup' => 1, 'modified' => '0', 'comments' => null, 'project_number' => '', 'assigned_user_id' => 0, 'dashboard_id' => 0, 'billing_option' => 0, 'website_project' => 0, 'total_matched' => 2, 'total_words' => 124, 'project_percentage' => '2')))) in ElasticquentTrait.php line 313
at Source->addToIndex() in FuzzyController.php line 13
at FuzzyController->index('1470031884', '1')
at call_user_func_array(array(object(FuzzyController), 'index'), array('project' => '1470031884', 'position' => '1')) in Controller.php line 55
at Controller->callAction('index', array('project' => '1470031884', 'position' => '1')) in ControllerDispatcher.php line 44
at ControllerDispatcher->dispatch(object(Route), object(FuzzyController), 'index') in Route.php line 204
at Route->runController() in Route.php line 160
at Route->run() in Router.php line 559
at Router->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in SubstituteBindings.php line 41
at SubstituteBindings->handle(object(Request), object(Closure)) in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in VerifyCsrfToken.php line 65
at VerifyCsrfToken->handle(object(Request), object(Closure)) in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure)) in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in StartSession.php line 64
at StartSession->handle(object(Request), object(Closure)) in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure)) in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in EncryptCookies.php line 59
at EncryptCookies->handle(object(Request), object(Closure)) in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 102
at Pipeline->then(object(Closure)) in Router.php line 561
at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 520
at Router->dispatchToRoute(object(Request)) in Router.php line 498
at Router->dispatch(object(Request)) in Kernel.php line 174
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request)) in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in TransformsRequest.php line 30
at TransformsRequest->handle(object(Request), object(Closure)) in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in TransformsRequest.php line 30
at TransformsRequest->handle(object(Request), object(Closure)) in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in ValidatePostSize.php line 27
at ValidatePostSize->handle(object(Request), object(Closure)) in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure)) in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 102
at Pipeline->then(object(Closure)) in Kernel.php line 149
at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 116
at Kernel->handle(object(Request)) in index.php line 54
at require_once('C:\\xampp\\htdocs\\laravel5\\public\\index.php') in index.php line 21

ServerErrorResponseException in Connection.php line 657:
{"error":{"root_cause":[{"type":"index_failed_engine_exception","reason":"Index failed for [sources#10475977]","shard":"2","index":"verbingo"}],"type":"index_failed_engine_exception","reason":"Index failed for [sources#10475977]","shard":"2","index":"verbingo","caused_by":{"type":"already_closed_exception","reason":"translog is already closed"}},"status":500}
Please some one help me to through this

**Comment by tvernum** [comment] 2017-04-03 06:19
> Please some one help me to through this

If you are simply asking for assistance in solving a problem, please ask on our [discuss forum](https://discuss.elastic.co/) where we can provide better support.
Elastic uses GitHub issues for confirmed bugs and feature requests which have been discussed on the forums. 

I'm going to close this issue now, but if it turns out that you have uncovered a bug, we can reopen it later. Note thought, that Elasticsearch 2.3 is quite old, and even if there is a bug it is quite possible that it has been fixed in a more recent version.

Thank you.

**Closed by tvernum** 2017-04-03 06:19 UTC
