### ISSUE TITLE
Wildcard query converts strings "63" and "42" to wildcards

### ISSUE THREAD

**Issue by niko-dotlabs** [elastic/elasticsearch#20099] opened 2016-08-22 10:14 UTC
**Elasticsearch version**: v2.3.1

**Plugins installed**: [head]

**JVM version**: Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

**OS version**: Debian GNU/Linux 7 (wheezy)

**Description of the problem including expected versus actual behavior**:
In a wildcard query the strings "63" and "42" get converted to wildcards. As those strings are not actually wildcarded one could use other query types, but there are certainly use cases where the wildcard query is used for both cases. 

**Steps to reproduce**:
 1. do the following query for a field in the schema:
`{
    "wildcard" : { "field" : "63" }
}`
 2. as result you get all documents in the index

**Comment by colings86** [comment] 2016-08-22 12:58
I have just tried to reproduce this with the below example but was not able to get what you are seeing, maybe there is something I am missing. Could you give a similar full reproduction example so we can reproduce what you are seeing and tey to see whats going on?

```
DELETE test

POST test/test/1
{
  "foo": "bar"
}

GET test/_search
{
  "query": { "wildcard" : { "foo" : "63" } }
}
```

Response form search:
```
{
  "took" : 48,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : null,
    "hits" : [ ]
  }
}
```

**Comment by niko-dotlabs** [comment] 2016-08-22 16:12
Just recognized that the field mapping has been set to number. maybe 
that's the difference...

I'll provide the full reproduction sample as soon as possible.


Thanks

Am 22.08.2016 um 15:00 schrieb Colin Goodheart-Smithe:

**Comment by colings86** [comment] 2016-08-23 07:58
I've reproduced this on 2.3.1 with the following script:
```
DELETE test

POST test/test/1
{
  "foo": 102
}

GET test/_search
{
  "query": { "wildcard" : { "foo" : "63" } }
}
```

This gives the following output for the search request:
```
{
  "took" : 50,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "test",
      "_type" : "test",
      "_id" : "1",
      "_score" : 1.0,
      "_source" : {
        "foo" : 102
      }
    } ]
  }
}
```

I was also able to reproduce the same on 2.3.5. In 5.0 this issue is not reproducible and the search request instead fails with:

```
{
  "error": {
    "root_cause": [
      {
        "type": "query_shard_exception",
        "reason": "failed to create query: {\n  \"wildcard\" : {\n    \"foo\" : {\n      \"wildcard\" : \"63\",\n      \"boost\" : 1.0\n    }\n  }\n}",
        "index_uuid": "g0YKR0jgS6aaiJ9rn4Ku1A",
        "index": "test"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "test",
        "node": "ImBbtNUrTFGhL6uO-m5XKg",
        "reason": {
          "type": "query_shard_exception",
          "reason": "failed to create query: {\n  \"wildcard\" : {\n    \"foo\" : {\n      \"wildcard\" : \"63\",\n      \"boost\" : 1.0\n    }\n  }\n}",
          "index_uuid": "g0YKR0jgS6aaiJ9rn4Ku1A",
          "index": "test",
          "caused_by": {
            "type": "illegal_argument_exception",
            "reason": "Cannot extract a term from a query of type class org.apache.lucene.document.FloatPoint$1: foo:[63.0 TO 63.0]"
          }
        }
      }
    ],
    "caused_by": {
      "type": "query_shard_exception",
      "reason": "failed to create query: {\n  \"wildcard\" : {\n    \"foo\" : {\n      \"wildcard\" : \"63\",\n      \"boost\" : 1.0\n    }\n  }\n}",
      "index_uuid": "g0YKR0jgS6aaiJ9rn4Ku1A",
      "index": "test",
      "caused_by": {
        "type": "illegal_argument_exception",
        "reason": "Cannot extract a term from a query of type class org.apache.lucene.document.FloatPoint$1: foo:[63.0 TO 63.0]"
      }
    }
  },
  "status": 400
}
```

It seems correct that a wildcard query will fail on a numeric field in 5.0 since wildcard queries are intended for string fields

**Comment by clintongormley** [comment] 2016-08-23 13:24
> It seems correct that a wildcard query will fail on a numeric field in 5.0 since wildcard queries are intended for string fields

Agreed.  Closing

**Closed by clintongormley** 2016-08-23 13:24 UTC
Labels: :Search, feedback_needed
