### ISSUE TITLE
geoHashLevelsForPrecision returns 24 maximum level on 0 meters passed

### ISSUE THREAD

**Issue by chamini2** [elastic/elasticsearch#35523] opened 2018-11-13 23:42 UTC
I was using `geoHashLevelsForPrecision` and in 

https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/common/geo/GeoUtils.java#L202-L204

it seems to return the maximum possible level if you pass 0 meters. This is delegated to `GeohashPrefixTree`, which is returning `24`; instead of using `GeoHashUtils.PRECISION` (12).

Am I not understanding the method or this is a bug?

**Comment by iverase** [comment] 2018-11-14 10:08
@markharwood note that there are two different things:

1) Spatial prefix tree based on geohash that support up to 24 levels. This is used when indexing geo_shapes and the `tree` is set to geohash.  For  [geohash prefix tree](https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-shape.html#prefix-trees),  the maximum level is 24.
2) Geohash grid aggregation which supports up to 12 levels.

**Comment by markharwood** [comment] 2018-11-14 10:18
OK. I'm not a geo expert so I'll leave it to the geo team to comment but perhaps one reason for the 12 vs 24 discrepancy is the different contexts:
GeohashGrid agg - being end-user facing we don't want to render gigabytes of fine-grained JSON information at the lower levels of detail, especially when used with sub aggregations.
Spatial indexes used for measuring shape intersections may want to use higher levels of detail for accurate matching.

**Comment by chamini2** [comment] 2018-11-14 14:19
@iverase, but the weird part is that sending a 0 to that method returns a 24, and then sending a 1 returns a 11; there is no in between. (I did not try to send floating number between 0 and 1, though :thinking:)

**Comment by iverase** [comment] 2018-11-14 14:41
@chamini2:  That is actually right as 1 meter precision is around 11 levels. If you try one centimetre (0.001 meters) then you see that the levels are 15.

**Comment by chamini2** [comment] 2018-11-14 14:46
In case that returning 24 makes sense for this case... Where can I find an equivalent method for geohash grid?

**Comment by markharwood** [comment] 2018-11-14 16:00
>Where can I find an equivalent method for geohash grid?

Do you mean you want 24 levels in geohashgrid agg or you want to express precision using meters not level numbers?

**Comment by chamini2** [comment] 2018-11-14 16:07
I want a method that works just like `geoHashLevelsForPrecision` but returns 12 or less (like https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-geohashgrid-aggregation.html says), not 24 (which seems to be appropriate for geohash prefix tree)

**Comment by markharwood** [comment] 2018-11-14 16:25
>I want a method 

Are we talking Java methods? So the equivalent of:

     Math.min(12, GeoUtils.geoHashLevelsForPrecision(meters))

When we talk about changes to the elasticsearch API we generally talk about changing the REST interface for the benefit of all languages (python, perl etc). 
We're not a Java SDK so we don't generally discuss making changes to internal classes to make only one language client (Java) happier.

**Comment by chamini2** [comment] 2018-11-14 16:58
I understand that, but this seems like a bug on the Java client from my point of view. Allowing precision to be 24 in geohash grid would be good anyways.

Where should I open Java client specific bugs?

**Comment by markharwood** [comment] 2018-11-14 17:38
>Allowing precision to be 24 in geohash grid would be good anyways.

Can you say more about the use cases where this would be useful? We tend to avoid features that can easily create a bazillion buckets when not used with care.

>Where should I open Java client specific bugs?

I suspect GeoUtils is not considered to be part of the Java client. We are moving to a lightweight Java client free of server-side dependencies which will expose as much or little functionality as all other clients have access to via the REST api. Java apps should stop building dependencies on server code.

**Comment by chamini2** [comment] 2018-11-14 19:15
Then there is a bug on the java server?

Doing `GeoUtils.checkPrecisionRange(GeoUtils.geoHashLevelsForPrecision(0))` throws an error:

```
    public static int checkPrecisionRange(int precision) {
        if ((precision < 1) || (precision > 12)) {
            throw new IllegalArgumentException("Invalid geohash aggregation precision of " + precision
                + ". Must be between 1 and 12.");
        }
        return precision;
    }
```

**Comment by markharwood** [comment] 2018-11-14 19:50
GeoUtils.checkPrecisionRange is only used by `org.elasticsearch.search.aggregations.bucket.geogrid.GeoGridAggregationBuilder` and `org.elasticsearch.search.suggest.completion.context.GeoQueryContext` both of which have documented precision limits of 12.
I don't think theres an issue to be flagged here unless @nknize has a concern over the 24-level shape encoding support in the index but only a 12-level aggregation support.

**Comment by imotov** [comment] 2018-12-12 18:52
I think returning 12 for `GeoUtils.geoHashLevelsForPrecision(0)` might be misleading. This function is used in parsing geo hash aggs. So, right now if a user runs something like this:
```
POST /museums/_search?size=0
{
    "aggregations" : {
        "large-grid" : {
            "geohash_grid" : {
                "field" : "location",
                "precision" : "1mm"
            }
        }
    }
}
```
we return an error message:
```
{
  "error": {
    "root_cause": [
      {
        "type": "x_content_parse_exception",
        "reason": "[6:31] [geohash_grid] failed to parse field [precision]"
      }
    ],
    "type": "x_content_parse_exception",
    "reason": "[6:31] [geohash_grid] failed to parse field [precision]",
    "caused_by": {
      "type": "illegal_argument_exception",
      "reason": "precision too high [0.1mm]",
      "caused_by": {
        "type": "illegal_argument_exception",
        "reason": "Invalid geohash aggregation precision of 16. Must be between 1 and 12."
      }
    }
  },
  "status": 400
}
```
Basically, it is more or less clear that we cannot support such high precision. Returning 12 could set wrong expectations about supported precision I think. From this perspective, using the workaround `Math.min(12, GeoUtils.geoHashLevelsForPrecision(meters))` proposed by @markharwood is a good solution since it forces the user to acknowledge that the fact the precision is too high is ignored. 

Saying that I wonder if the correct behaviour for precisions that we cannot support is to throw `IllegalArgumentException`. Because right now
`GeoUtils.geoHashLevelsForPrecision("0m")` returns `24`
but 
`GeoUtils.geoHashLevelsForPrecision("0.00000001mm")` returns `25`

Such behaviour seems to be technically incorrect. Although, I understand that it's might be not very practical example since we are talking subatomic scale here.

**Comment by markharwood** [comment] 2018-12-18 14:37
Closing as not a bug - GeoUtils is not considered part of the Java client API and a workaround was offered in https://github.com/elastic/elasticsearch/issues/35523#issuecomment-438724490

**Closed by markharwood** 2018-12-18 14:37 UTC
Labels: :Analytics/Geo, team-discuss
