### ISSUE TITLE
slowlog transient

### ISSUE THREAD

**Issue by YinChunGuang** [elastic/elasticsearch#27002] opened 2017-10-13 10:18 UTC
It got wrong when I update the slowlog by transient,
Can I update the common config like slowlog  by transient.
Thanks！
 
PUT _cluster/settings
{
  "transient" : 
        {
          "index.indexing.slowlog.threshold.index.warn": "10s" 
        }
}

{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "transient setting [index.indexing.slowlog.threshold.index.warn], not dynamically updateable"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "transient setting [index.indexing.slowlog.threshold.index.warn], not dynamically updateable"
  },
  "status": 400
}

**Comment by jasontedor** [comment] 2017-10-13 10:25
Please follow our contributing guidelines and our issue template when opening an issue or a feature request. For example, you're missing specifying the Elasticsearch version here, and our issue template explains that we do not answer general questions here. Instead, we request that you ask general questions on the [forum](https://discuss.elastic.co). As such, I am going to close this issue as it is not a bug.

**Closed by jasontedor** 2017-10-13 10:25 UTC
