### ISSUE TITLE
Enhance histogram aggregation - specify number of buckets instead of interval

### ISSUE THREAD

**Issue by nreese** [elastic/elasticsearch#20590] opened 2016-09-20 20:58 UTC
The current implementation of the histogram aggregation requires an interval field to specify the histogram bucket size. Providing an appropriate interval requires additional knowledge about the data set, usually the min and max. This additional knowledge can be obtained from Elasticsearch but requires additional HTTP traffic and adds unnecessary complexity to client implementations.

I recommend adding a new parameter, **buckets**, to the histogram aggregation. Elasticsearch would use this value to automatically calculate an appropriate interval that generates the specified number of buckets taking into consideration all provided queries, filters, and aggregation filters.
```
{
    "aggs" : {
        "prices" : {
            "histogram" : {
                "field" : "price",
                "buckets" : 25
            }
        }
    }
}
```

**Comment by Bargs** [comment] 2016-09-21 00:29
This would be a boon for Kibana because it would allow us to easily [auto scale the histogram visualization](https://github.com/elastic/kibana/pull/8139) and protect users from [accidentally creating too many buckets](https://github.com/elastic/kibana/issues/2908), crashing their browser in the process.

As @nreese mentioned we could accomplish this by issuing two requests from the client, the first grabbing the min/max values for the given field. But since the aggregation may have a search query and/or filters associated with it we don't know how performant this would be. I imagine it would be more efficient to implement this option inside elasticsearch so the calculations can be done in a single request.

I think there's some precedence for such an option in the terms agg. Essentially we want the `size` option from the terms agg, but for histograms.

Thanks for considering!

**Comment by clintongormley** [comment] 2016-09-21 13:42
Duplicate of https://github.com/elastic/elasticsearch/issues/9572

**Closed by clintongormley** 2016-09-21 13:42 UTC
