### ISSUE TITLE
Skip dangling indices checks for dedicated masters

### ISSUE THREAD

**Issue by Bukhtawar** [elastic/elasticsearch#48106] opened 2019-10-16 07:49 UTC
## Problem Description
Although optimized in 6.5 but still the check seems wasteful for dedicated master nodes. There is no point checking for indices directory. This can to a very insignificant slow down cluster state updates as this check is done at every update. This happened in ES 6.2 below is the hot threads o/p

```
23.4% (116.7ms out of 500ms) cpu usage by thread 'elasticsearch[tkCBQZW][clusterApplierService#updateTask][T#1]'
     2/10 snapshots sharing following 37 elements
       java.io.UnixFileSystem.canonicalize0(Native Method)
       java.io.UnixFileSystem.canonicalize(UnixFileSystem.java:172)
       java.io.File.getCanonicalPath(File.java:618)
       java.io.FilePermission$1.run(FilePermission.java:215)
       java.io.FilePermission$1.run(FilePermission.java:203)
       java.security.AccessController.doPrivileged(Native Method)
       java.io.FilePermission.init(FilePermission.java:203)
       java.io.FilePermission.<init>(FilePermission.java:277)
       java.lang.SecurityManager.checkRead(SecurityManager.java:888)
       sun.nio.fs.UnixPath.checkRead(UnixPath.java:795)
       sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:49)
       sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
       sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
       java.nio.file.Files.readAttributes(Files.java:1737)
       java.nio.file.Files.isDirectory(Files.java:2192)
       org.elasticsearch.env.NodeEnvironment.availableIndexFoldersForPath(NodeEnvironment.java:790)
       org.elasticsearch.env.NodeEnvironment.availableIndexFolders(NodeEnvironment.java:767)
       org.elasticsearch.gateway.MetaStateService.loadIndicesStates(MetaStateService.java:89)
       org.elasticsearch.gateway.DanglingIndicesState.findNewDanglingIndices(DanglingIndicesState.java:131)
       org.elasticsearch.gateway.DanglingIndicesState.findNewAndAddDanglingIndices(DanglingIndicesState.java:116)
       org.elasticsearch.gateway.DanglingIndicesState.processDanglingIndices(DanglingIndicesState.java:81)
       org.elasticsearch.gateway.DanglingIndicesState.clusterChanged(DanglingIndicesState.java:185)
       org.elasticsearch.cluster.service.ClusterApplierService.lambda$callClusterStateListeners$7(ClusterApplierService.java:509)
       org.elasticsearch.cluster.service.ClusterApplierService$$Lambda$1712/1950969471.accept(Unknown Source)
       java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
       java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
       java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
       org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListeners(ClusterApplierService.java:506)
       org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:489)
       org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:432)
       org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:161)
       org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:582)
       org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244)
       org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207)
       java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
       java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
       java.lang.Thread.run(Thread.java:748)
```

**Comment by DaveCTurner** [comment] 2019-10-16 08:16
Dangling indices are checking for unreferenced index metadata, so they can arise on dedicated master nodes just as on data nodes. The optimization in 6.5 (#34349) reduces this check to little more than listing the `indices` directory on nodes with no dangling indices, so I think we can close this as a duplicate.

If you can reproduce a significant performance issue on a version after 6.5 then please provide more details and we'll re-open this.

**Closed by DaveCTurner** 2019-10-16 08:16 UTC
Labels: :Distributed/Allocation

**Comment by Bukhtawar** [comment] 2019-10-16 08:45
@DaveCTurner sure we'll run benchmarks but can you help me understand why this check is needed on active master on every cluster state update. Isn't that wasteful

**Comment by DaveCTurner** [comment] 2019-10-16 08:51
I'm not sure how to put it in a different way from my previous statement:

> Dangling indices are checking for unreferenced index metadata, so they can arise on dedicated master nodes just as on data nodes.

**Comment by Bukhtawar** [comment] 2019-10-16 08:55
Putting my question differently, when a master is elected it can sync any dangling indices one time. For data nodes they go down and come back hence checking it regularly makes sense. Between the master between elected till it step down what are the cases that the `unreferenced index metadata` would change.

**Comment by Bukhtawar** [comment] 2019-10-16 09:01
Putting it differently just for my understanding. Under what cases do we expect `unreferenced index metadata` to change post a node joining the cluster or active master getting changed. To be specific when do we actually see index metadata change if the cluster is all stable with no node drops/restarts.

**Comment by Bukhtawar** [comment] 2019-10-16 09:32
@DaveCTurner This is what I am referring to
https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-gateway-dangling-indices.html#modules-gateway-dangling-indices

**Comment by DaveCTurner** [comment] 2019-10-16 09:34
The reasons for this feature are quite historical. In early versions of Elasticsearch you could add index metadata to the data path of a running node and it would be imported as a dangling index. This is deeply unsafe and thoroughly unsupported today, but we must maintain it anyway since it would be a breaking change to remove it.

If there were a more compelling case to make the change you are suggesting (e.g. a quantifiable performance issue) then we might take a different view, but I don't think there's any such case in recent versions. Cluster state updates are not that frequent, and we don't have any evidence that this check is adding any significant burden in recent versions.
