### ISSUE TITLE
[CI] ClassReadersTests and NamedComponentScannerTests classMethod failing

### ISSUE THREAD

**Issue by salvatore-campagna** [elastic/elasticsearch#93026] opened 2023-01-18 10:22 UTC
**Build scan:**
https://gradle-enterprise.elastic.co/s/5npwoa3kbaasm/tests/:libs:elasticsearch-plugin-scanner:test/org.elasticsearch.plugin.scanner.ClassReadersTests

**Reproduction line:**
```
null
```

**Applicable branches:**
8.6

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.plugin.scanner.ClassReadersTests&tests.test=classMethod

**Failure excerpt:**
```
java.io.IOException: Could not remove the following files (in the order of attempts):
   C:\Users\jenkins\workspace\platform-support\126\libs\plugin-scanner\build\testrun\test\temp\org.elasticsearch.plugin.scanner.ClassReadersTests_E47F780AD60785A7-001\tempDir-004: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\platform-support\126\libs\plugin-scanner\build\testrun\test\temp\org.elasticsearch.plugin.scanner.ClassReadersTests_E47F780AD60785A7-001\tempDir-004
   C:\Users\jenkins\workspace\platform-support\126\libs\plugin-scanner\build\testrun\test\temp\org.elasticsearch.plugin.scanner.ClassReadersTests_E47F780AD60785A7-001\tempDir-004\jars-dir: java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\platform-support\126\libs\plugin-scanner\build\testrun\test\temp\org.elasticsearch.plugin.scanner.ClassReadersTests_E47F780AD60785A7-001\tempDir-004\jars-dir
   C:\Users\jenkins\workspace\platform-support\126\libs\plugin-scanner\build\testrun\test\temp\org.elasticsearch.plugin.scanner.ClassReadersTests_E47F780AD60785A7-001: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\platform-support\126\libs\plugin-scanner\build\testrun\test\temp\org.elasticsearch.plugin.scanner.ClassReadersTests_E47F780AD60785A7-001

  at __randomizedtesting.SeedInfo.seed([E47F780AD60785A7]:0)
  at org.apache.lucene.util.IOUtils.rm(IOUtils.java:341)
  at org.apache.lucene.tests.util.TestRuleTemporaryFilesCleanup.afterAlways(TestRuleTemporaryFilesCleanup.java:209)
  at com.carrotsearch.randomizedtesting.rules.TestRuleAdapter$1.afterAlways(TestRuleAdapter.java:31)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1589)

```

**Comment by thecoop** [comment] 2023-01-18 10:24
Duplicate of #93005

**Closed by thecoop** 2023-01-18 10:24 UTC
Labels: :Core/Infra/Core, >test-failure, Team:Core/Infra
