### ISSUE TITLE
Possible missing dependency: Apache HttpCore 4.3.x

### ISSUE THREAD

**Issue by spencerwi** [elastic/elasticsearch#10488] opened 2015-04-08 14:47 UTC
When upgrading our dependencies, we encountered this error in our stack trace:

```
Exception Thrown
org.elasticsearch.common.inject.CreationException: Guice creation errors:

1) Error injecting constructor, java.lang.NoClassDefFoundError: org/apache/http/util/Args
  at org.elasticsearch.discovery.ec2.Ec2Discovery.<init>(Unknown Source)
  while locating org.elasticsearch.discovery.ec2.Ec2Discovery
  while locating org.elasticsearch.discovery.Discovery
    for parameter 3 at org.elasticsearch.node.service.NodeService.<init>(Unknown Source)
  while locating org.elasticsearch.node.service.NodeService
Caused by: java.lang.NoClassDefFoundError: org/apache/http/util/Args
```

After checking through the pomfile for elasticsearch-cloud-aws, we didn't find any references to a specific version of Apache HTTPCore (so we weren't able to directly identify which version elasticsearch depends on).

We are using elasticsearch 1.5.0 and cloud-aws 2.5.0 (per the helpful README in cloud-aws!); we were using these in a previous release as well, but had another dependency that happened to provide HTTPCore 4.3.x as a transitive dependency. When that lib was upgraded, it specified HTTPCore 4.2.5, which appears not to contain the `org.apache.http.util.Args` class.

So when we were no longer lucky enough to have another dependency transitively satisfying cloud-aws's dependency on HTTPCore 4.3.x, since cloud-aws doesn't specify HTTPCore 4.3.x in its pomfile, we got a NoClassDefFound error.

It was something like this before:

```
                     OUR_APP
          /                         \
         /                           \
        /                             \
    DepA                     ElasticSearch
       |                               /  (dep not in pomfile)
 HTTPCore <---------------------------/        
 (no version specified, so grabs 4.3.x)
```

And now we have this:
```
                     OUR_APP
          /                         \
         /                           \
        /                             \
    DepA                     ElasticSearch
       |                               /  (dep not in pomfile)
 HTTPCore <---------------------------/        
   (4.2.5, breaks ElasticSearch)
```

Should this dependency be added to the pomfile?

**Comment by clintongormley** [comment] 2015-04-10 11:28
@dadoonet could you take a look at this please? (should probably move to https://github.com/elastic/elasticsearch-cloud-aws ?)

**Comment by tlrx** [comment] 2015-04-10 11:56
As far as I know, elasticsearch has a transitive dependency on `httpcore` with the scope `test`:

```
$ mvn dependency:tree | grep http
[INFO] ------------------------------------------------------------------------
[INFO] Building elasticsearch 1.5.0
[INFO] ------------------------------------------------------------------------
...
[INFO] +- org.apache.httpcomponents:httpclient:jar:4.3.5:test
[INFO] |  +- org.apache.httpcomponents:httpcore:jar:4.3.2:test
```

This dependency is not required at runtime, so I don't see why this dependency should be declared in the pom file.

This issue is a duplicate of https://github.com/elastic/elasticsearch-cloud-aws/issues/200, maybe we can close this one and continue on the cloud-aws issue?

**Comment by clintongormley** [comment] 2015-04-13 09:43
@tlrx agreed. closing

**Closed by clintongormley** 2015-04-13 09:43 UTC
