### ISSUE TITLE
Index warmer does not execute function score script

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#12254] opened 2015-07-15 04:09 UTC
Repro here (https://gist.github.com/ppf2/63e19e4ede49a6ff89ba).

In short, when a function score query with a script is added to the index warmer, the warmer itself fires (I can confirm via index.warmer at trace level) but it does not execute the script.  If I run the same query directly, it does fire the script.  Script filters' script does fire when added to the index warmer.  

From a scoring point of view, it may not make sense to run it via the warmer, though I have the impression that we also try to cache the script for faster subsequent executions which makes me wonder if it will still help to run the script as part of the warmer.  Either way, would be nice to know more about how it works :)

Not sure if the behavior is expected (if so, can we document it?)

**Comment by clintongormley** [comment] 2015-07-15 11:03
@martijnvg any ideas here?

@ppf2 as a side note, this is a particularly poor way to use warmers.  Just sorting on `listprice` would have the same effect, or updating the mapping for the field to (eg) load global ordinals eagerly.

**Comment by ppf2** [comment] 2015-07-15 16:22
@clintongormley btw, the repro is really just for quick demonstration purposes using groovy equivalent, the end user actually has a more elaborate native script being used which is not getting executed by the warmer.

**Comment by martijnvg** [comment] 2015-07-17 10:22
warmers queries are executed with search_type=count if no sort is specified and therefor scores are never computed. The function_score scripts are only invoked if scores are computed, so that is why the script doesn't get invoked during warming.

**Comment by clintongormley** [comment] 2015-07-17 10:23
thanks @martijnvg - sounds like this should be documented

**Comment by ppf2** [comment] 2015-07-17 18:28
```
  "sort": [
    {
      "_score": {
        "order": "desc"
      }
    }
  ]
```

Thanks for the feedback.  Per comments above, I attempted a fix by adding an explicit sort to the _score.

The results are:
1.  At the time the put warmer is called with the sort in place, it fires the script successfully
2.  But when the node is restarted, the warmer still does not execute the script.

I discussed with @martijnvg , it sounds like there is actually a bug here.

**Comment by masaruh** [comment] 2015-12-24 04:09
I think I found the cause. While it's parsing `sort` part, it omits sorting if query has one sort criteria and if it's sorting on `_score` in descending order (https://github.com/elastic/elasticsearch/blob/v2.1.1/core/src/main/java/org/elasticsearch/search/sort/SortParseElement.java#L101-L117). Then, SearchService thinks it doesn't have sort and changes query to size=0 (https://github.com/elastic/elasticsearch/blob/v2.1.1/core/src/main/java/org/elasticsearch/search/SearchService.java#L1148-L1153).

So, if you change the sort part from `desc` to `asc`, the script will be executed.

**Comment by clintongormley** [comment] 2016-01-10 19:05
Warmers have been removed. Closing

**Closed by clintongormley** 2016-01-10 19:05 UTC
Labels: :Warmers, discuss
