### ISSUE TITLE
[7.4.0, BUG] Highlighting(fvh) - Elastic Search

### ISSUE THREAD

**Issue by ilamparithi10** [elastic/elasticsearch#48054] opened 2019-10-15 11:31 UTC
**Describe the feature**: I am using highlighting(fvh) in the elasticsearch to highlight the keyword.
When I do a search with keyword 5-2011, it produces the result with the keyword 005-2011 but it doesn't highlight the keyword.
My query to highlight is 
```
{
                        "type": "fvh",
                        "pre_tags": ["<em>"],
                        "post_tags": ["</em>"],
                        "number_of_fragments": 100,
                        "fragment_size": 50,
                        "fields": { "*": {} }
}
```

**Elasticsearch version** (`bin/elasticsearch --version`): **7.4.0**

**Plugins installed**: []

**JVM version** (`java -version`): **openjdk version "11.0.4"**

**OS version** (`uname -a` if on a Unix-like system): **Ubuntu 16.04**

**Description of the problem including expected versus actual behavior**:
Actual behavior:
it doesn't return highlight for the keyword(5-2011)

expected behavior:

00"< em >5-2011</ em >

**Provide logs (if relevant)**:

**Comment by jimczi** [comment] 2019-10-15 20:17
@ilamparithi10 there are multiple factors that can affect highlighting so it difficult to understand your issue without a clear reproduction. Can you provide us with the mappings and settings for your index, the document that you think should be highlighted and the original query that you send ? Without these informations we won't be able to help you.

**Comment by ilamparithi10** [comment] 2019-10-16 06:01
@jimczi , 

Settings for my index: https://pastebin.com/nxAbReBT

Mappings: https://pastebin.com/cYTDnkrq

sample document: https://pastebin.com/NGa6PHTh

query: https://pastebin.com/gBp5wfE4

expected result : https://pastebin.com/4hBBhgN4

Let me know if it helps

**Comment by ilamparithi10** [comment] 2019-10-18 04:59
@jimczi , any update on this?

**Comment by ilamparithi10** [comment] 2019-10-29 09:11
@polyfractal whether this issue can be solved by anyway?

**Comment by jimczi** [comment] 2019-10-29 09:20
Can you try with the `unified` highlighter ? This highlighter is the default in Elasticsearch, it extracts offsets from terms_vector if they are available exactly like the `fvh` so it should be comparable in terms of performance.

**Comment by ilamparithi10** [comment] 2019-10-29 09:40
@jimczi  when I use the `unified` highlighter it throws the following error,
`TransportError(500, 'search_phase_execution_exception', 'bytes can be at most 32766 in length; got 48204')`

**Comment by jimczi** [comment] 2019-10-29 09:58
That's because you try to highlight all your fields including the `keyword` one. There is a small bug in the `unified` highlighter, it doesn't respect `ignore_above` but the limit for a single term is  `32766`  utf8 bytes. Unlike the `fvh`, the `unified` highlighter will re-analyze the field if it wasn't indexed with the offsets option. The workaround is to set the list of fields to highlight instead of using `*`, this way you can restrict highlighting to the provided fields rather than trying to highlight all fields even those that don't make sense ?

**Comment by ilamparithi10** [comment] 2019-10-29 10:26
how to provide list of fields to highlight?

**Comment by jimczi** [comment] 2019-10-29 10:40
You can use:
````
"highlight" : {
       "type": "unified",
       "pre_tags": ["<em>"],
       "post_tags": ["</em>"],
        "number_of_fragments": 100,
        "fragment_size": 50,
        "fields" : {
            "content" : {},
            "title": {}
        }
}
````

**Comment by ilamparithi10** [comment] 2019-10-29 11:12
I tried this, but no luck. It doesn't highlight.
Query:
```
{
	'highlight': {
		'type': 'unified',
		'pre_tags': ['<em>'],
		'post_tags': ['</em>'],
		'number_of_fragments': 100,
		'fragment_size': 50,
		'fields': {
			'clause_number': {}
		}
	}
}
```

**Comment by jimczi** [comment] 2019-10-29 11:31
@ilamparithi10 I think your issue comes from a misconfigured mapping or wrong expectation (`clause_number` does not appear in your raw document). We try to reserve github for feature requests and verified bugs so it would be easier to discuss on the [forum](https://discuss.elastic.co/c/elasticsearch) which is more suited for these questions/answers communication. I hope your don't mind if I close this issue, please open a new topic in the forum and provide the link here if needed.

**Closed by jimczi** 2019-10-29 11:31 UTC
Labels: :Search/Highlighting, feedback_needed

**Comment by ilamparithi10** [comment] 2019-10-29 11:37
@jimczi ,
"field" in the document is "clause_number".
**updated query:**
```
{
	'highlight': {
		'type': 'unified',
		'pre_tags': ['<em>'],
		'post_tags': ['</em>'],
		'number_of_fragments': 100,
		'fragment_size': 50,
		'fields': {
			'field': {}
		}
	}
}
```

**Comment by jimczi** [comment] 2019-10-29 11:53
In such case it is expected that `005-2011` isn't highlighted when searching for `5-2011`. The standard tokenizer creates two tokens for the input `005-2011`, `005` and `2011`. Same for `5-2011` except that the tokens are `5` and `2011` and since we don't highlight partial word (and we don't match on them either) the response you get is expected. Please use the forum if you have follow up questions. As said above the issues you're having is due to wrong expectations regarding tokenization and queries so I'd be happy to follow up on the discuss forum.
