### ISSUE TITLE
"newbie mode" in API reference

### ISSUE THREAD

**Issue by ccurvey** [elastic/elasticsearch#18427] opened 2016-05-17 22:12 UTC
**Describe the feature**:

it would be great if the API documentation (the stuff on the web) had a "newbie" mode that would show query components within the context of a complete query.  for example, on https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-common-terms-query.html, there are examples of the "common" block, but it's not clear (to me at least) where the "common" block fits in the query.  

I realize that adding that information to every page would be noisy for experienced users, so I'd suggest a way for newbies to say "show me this in the context of the ENTIRE query".  That would also be helpful as a learning tool, because by seeing lots of different examples, the newbie learns the structure of queries by osmosis.

**Comment by nik9000** [comment] 2016-05-18 01:31
We're actively working to switch all the snippets in the docs to runnable snippets for a bunch of reasons, one of which is this. The other is that we've start to actually run those snippets as tests to make sure that the docs don't bit rot on us. So this is kind of a duplicate of #18160 so I'm going to close it. Thanks for the suggestion!

**Closed by nik9000** 2016-05-18 01:31 UTC
