### ISSUE TITLE
Datanodes crash in ES cluster with java.lang.StackOverflowError

### ISSUE THREAD

**Issue by sbagwe** [elastic/elasticsearch#58077] opened 2020-06-13 16:59 UTC
**Elasticsearch version** (`5.3.0`):

**Plugins installed**: []

**JVM version** (`1.8.0_202`):

**OS version** (`CentOS 6.9`):

**Description of the problem including expected versus actual behavior**:

Datanodes crash with below stacktrace. We are in process of upgrading the Elasticsearch but is there any known workaround in the meantime since this is our production enviornment? 

[2020-06-13T16:26:32,261][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [Search_data_9208] fatal error in thread [elasticsearch[Search_data_9208][search][T#26]], exiting
java.lang.StackOverflowError: null
        at org.apache.lucene.util.automaton.RegExp.next(RegExp.java:1017) ~[lucene-core-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e - jpountz - 2017-02-01 14:43:32]
        at org.apache.lucene.util.automaton.RegExp.parseCharExp(RegExp.java:1163) ~[lucene-core-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e - jpountz - 2017-02-01 14:43:32]
        at org.apache.lucene.util.automaton.RegExp.parseSimpleExp(RegExp.java:1158) ~[lucene-core-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e - jpountz - 2017-02-01 14:43:32]
        at org.apache.lucene.util.automaton.RegExp.parseCharClassExp(RegExp.java:1090) ~[lucene-core-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e - jpountz - 2017-02-01 14:43:32]
        at org.apache.lucene.util.automaton.RegExp.parseComplExp(RegExp.java:1078) ~[lucene-core-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e - jpountz - 2017-02-01 14:43:32]
        at org.apache.lucene.util.automaton.RegExp.parseRepeatExp(RegExp.java:1047) ~[lucene-core-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e - jpountz - 2017-02-01 14:43:32]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1040) ~[lucene-core-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e - jpountz - 2017-02-01 14:43:32]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1042) ~[lucene-core-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e - jpountz - 2017-02-01 14:43:32]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1042) ~[lucene-core-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e - jpountz - 2017-02-01 14:43:32]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1042) ~[lucene-core-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e - jpountz - 2017-02-01 14:43:32]
   
**Steps to reproduce**:

**Provide logs (if relevant)**:

**Comment by dnhatn** [comment] 2020-06-13 21:36
Closing as a duplicate of https://github.com/elastic/elasticsearch/issues/37637.

**Closed by dnhatn** 2020-06-13 21:36 UTC
Labels: >bug, needs:triage
