### ISSUE TITLE
Make a much smaller Java API that includes transport client.

### ISSUE THREAD

**Issue by willwarren** [elastic/elasticsearch#8633] opened 2014-11-24 14:22 UTC
This may exist so apologies if I couldn't find it and am duplicating here: 

Would it be possible to break out the code for a client only API that doesn't include the entire elastic search code base?

Currently we have a lot of modular web services modules that make calls to elastic search and because we want to include the advantages of the transport client we have to use the full elastic search codebase.  This means that each web service war file is +30 megabytes.  

Ideally we'd like a client jar file that only includes the API and the transport code.

**Comment by javanna** [comment] 2015-03-19 19:12
relates to #6170

**Comment by dakrone** [comment] 2015-04-10 17:34
Closing as duplicate of #8633

**Closed by dakrone** 2015-04-10 17:34 UTC
Labels: discuss

**Comment by dakrone** [comment] 2015-04-10 17:37
Whoops, meant to say closing as duplicate of #6170
