### ISSUE TITLE
Add ability to reference parent to do aggregations with copy_to

### ISSUE THREAD

**Issue by billnbell** [elastic/elasticsearch#22980] opened 2017-02-05 05:20 UTC
I would like to define: copy_to: {parentname}_all. Today I can only use {name} which does not allow the object of the parent to be referenced. I want to take fields and aggregate all children into a terms search. Kinda like _all but at the object level.

Here is an example: Note this is kinda useless, since I want to use {parentname}.

```
PUT /index2
{
  "mappings": {
    "_default_": {
      "dynamic_templates": [
        {
          "nested_template": {
            "path_match": "*.*",
            "match_mapping_type": "string",
            "mapping": {
              "copy_to": "{name}_all",
              "type": "string",
              "index": "not_analyzed"
            }
          }
        },
        {
          "nested2_template": {
            "match": "*_all",
            "match_mapping_type": "string",
            "mapping": {
              "type": "string",
              "index": "not_analyzed"
            }
          }
        },
        {
          "nested2_template": {
            "path_unmatch": "*.*",
            "match_mapping_type": "string",
            "mapping": {
              "type": "string",
              "index": "not_analyzed"
            }
          }
        },
        {
          "notanalyzed": {
            "match": "*",
            "match_mapping_type": "string",
            "mapping": {
              "type": "string",
              "index": "not_analyzed"
            }
          }
        }
      ]
    }
  }
}
```

**Comment by clintongormley** [comment] 2017-02-17 13:53
Duplicate of https://github.com/elastic/elasticsearch/issues/12169

**Closed by clintongormley** 2017-02-17 13:53 UTC
Labels: :Mapping, discuss
