### ISSUE TITLE
ESQL: incorrect optimization rule behavior for different type, same name field STATS usage

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#110477] opened 2024-07-04 13:27 UTC
### Description

For query `FROM sample_data_str, sample_data | eval ip = to_string(client_ip) | STATS count=count(*) BY ip` the output is 

```
     count     |      ip       
---------------+---------------
8              |172.21.3.15    
2              |172.21.0.5     
2              |172.21.2.113   
2              |172.21.2.162   
```

while adding one more `stats` the behavior is unexpected

`FROM sample_data_str, sample_data | eval ip = to_string(client_ip) | STATS count=count(*) BY ip | STATS mc=count(count) BY count`

```
      mc       |     count     
---------------+---------------
6              |1              
2              |4              
```

Enabling TRACE logging there is this transformation that doesn't look like it's doing the right thing:

```
[TRACE][o.e.x.e.o.LogicalPlanOptimizer] [runTask-0] Rule rules.CombineProjections applied
Limit[1000[INTEGER]]                                                                = Limit[1000[INTEGER]]
\_Aggregate[STANDARD,[count{r}#735],[COUNT(count{r}#735) AS mc, count{r}#735]]      = \_Aggregate[STANDARD,[count{r}#735],[COUNT(count{r}#735) AS mc, count{r}#735]]
  \_Aggregate[STANDARD,[ip{r}#732],[COUNT(*[KEYWORD]) AS count, ip{r}#732]]         !   \_Aggregate[STANDARD,[client_ip{f}#741],[COUNT(*[KEYWORD]) AS count, client_ip{f}#741 AS ip]]
    \_Project[[client_ip{f}#740, client_ip{f}#741 AS ip]]                           !     \_EsRelation[sample_data_str,sample_data][client_ip{f}#740, client_ip{f}#741]
      \_EsRelation[sample_data_str,sample_data][client_ip{f}#740, client_ip{f}#741] !
```

The evaluated `ip` disappears and `client_ip` is being used instead. In these two indices, though, `client_ip` has different types (one is `keyword` the other is `ip`) and based on this differentiation the counts in the final result seem legit.

**Comment by luigidellaquila** [comment] 2024-07-04 15:10
Very similar query, completely different error:

```
PUT test1
{
    "mappings": {
        "properties": {
            "@timestamp": {
                "type": "long"
            },
            "name": {
                "type": "keyword"
            }
        }
    }
}

PUT test2
{
    "mappings": {
        "properties": {
            "@timestamp": {
                "type": "date"
            },
            "name": {
                "type": "keyword"
            }
        }
    }
}

POST _bulk
{"index": {"_index":"test1"}}
{"@timestamp":10000000, "name":"foo"}
{"index": {"_index":"test2"}}
{"@timestamp":"2022-05-06T12:01:00.000Z"}
```


```
FROM test* | eval ts = to_string(@timestamp) | STATS count=count(*) BY ts | STATS mc=count(count) BY count
```


```
[2024-07-04T16:22:40,604][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [runTask-0] fatal error in thread [elasticsearch[runTask-0][esql_worker][T#2]], exiting java.lang.AssertionError: LONG NOT IN (NULL, BYTES_REF)
        at org.elasticsearch.compute.lucene.ValuesSourceReaderOperator.process(ValuesSourceReaderOperator.java:164)
        at org.elasticsearch.compute.operator.AbstractPageMappingOperator.getOutput(AbstractPageMappingOperator.java:76)
        at org.elasticsearch.compute.operator.OrdinalsGroupingOperator$ValuesAggregator.addInput(OrdinalsGroupingOperator.java:514)
        at org.elasticsearch.compute.operator.OrdinalsGroupingOperator.addInput(OrdinalsGroupingOperator.java:176)
        at org.elasticsearch.compute.operator.Driver.runSingleLoopIteration(Driver.java:255)
        at org.elasticsearch.compute.operator.Driver.run(Driver.java:178)
        at org.elasticsearch.compute.operator.Driver$1.doRun(Driver.java:364)
        at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
        at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
        at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1570)
```

**Comment by craigtaverner** [comment] 2024-07-05 14:59
The issue should be fixed by https://github.com/elastic/elasticsearch/pull/110476

**Comment by craigtaverner** [comment] 2024-07-05 15:45
@luigidellaquila The error you see above would likely be fixed by the ordinals aggregation fix I removed from the other PR. I was not able to reproduce this because it always took a different code path. Your query looks extremely similar to the ones I'm testing, so should have triggered the same error.

**Comment by craigtaverner** [comment] 2024-07-05 15:58
Actually, @luigidellaquila , I wrote a test with your query and while I don't get the same error you do, I do not get the correct results from the query. So perhaps my current PR does not cover this case completely. Could you copy your query to another issue, and I can decide on Monday whether to include the fix in the current PR, or make a new one?

**Comment by luigidellaquila** [comment] 2024-07-05 16:09
Opened this https://github.com/elastic/elasticsearch/issues/110539 so that we don't forget, but I'll have to add some details on the failure

**Closed** 2024-07-08 12:13 UTC
Labels: >bug, Team:Analytics, :Analytics/ES|QL
