### ISSUE TITLE
accidental index with type that starts with underscore causes unexpected behavior

### ISSUE THREAD

**Issue by djschny** [elastic/elasticsearch#20044] opened 2016-08-18 04:30 UTC
**Elasticsearch version**: 2.3.2

**Plugins installed**: []

**JVM version**: 1.8.0_92-b14

**OS version**: Mac 10.11.5

**Description of the problem including expected versus actual behavior**:
When accidentally submitting a PUT request with a _type that starts with an underscore, an index turns red after closeing and re-opening.

**Steps to reproduce**:
Follow the following Sense commands and observe the status of the index afterwards:

```
DELETE my_index
PUT my_index
 
POST /my_index/my_type
{
  "name" : "foo"
}
 
PUT my_index/_settings
{
  "number_of_replicas": 3
}
 
POST my_index/_close
 
 
POST my_index/_open
 
GET _cat/indices?v
 
PUT my_index/_settings
{
  "number_of_replicas": 1
}
 
GET _cat/indices?v
```

Two items of concern here:

1. The index goes red after the open/close. Appears to be in regards to validation allowing a mapping to be created when it shouldn't.
2. Changing number of replicas somehow makes the index go from `red` to `yellow`. Not sure on this one and don't have a good explanation.

FYI - tested with alpha5 and this is not an issue.

CC @gsumpster who found this during a training class

**Comment by clintongormley** [comment] 2016-08-18 10:13
@djschny this has nothing to do with a type starting with an underscore (and your recreation doesn't HAVE a type starting with an underscore).

It's the fact that there should be 4 copies of the shard (because you set replicas to 3) but you only have one node, so 3 copies aren't assigned. When you try to reopen the index it looks for a quorum of shards before deciding which one to make the primary.

This is resolved in 5.0 with allocation IDs

**Closed by clintongormley** 2016-08-18 10:13 UTC

**Comment by djschny** [comment] 2016-08-18 13:39
However these were the errors we were seeing in the logs:

```
[2016-08-16 13:39:45,806][DEBUG][action.index             ] [node-1] failed to execute [index {[my_first_index][_settings][AVaVFJJ8Y-0C7PhxvOc9], source[{
  "number_of_replicas": 0
}
]}] on [[my_first_index][3]]
InvalidTypeNameException[Document mapping type name can't start with '_']
        at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:288)
        at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230)
        at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:468)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:772)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by clintongormley** [comment] 2016-08-19 11:26
this is a log message from a different request, one to `my_first_index/_settings`

**Comment by djschny** [comment] 2016-08-19 12:54
Yes I know. That was the error experienced by @gsumpster when he was trying to open an index. We then tried to get to steps to reproduce it. I slimmed down the commands to a smaller subset that was better for consumption on a github issue. Hence why the difference. We thought we got the steps right to reproduce but obviously looks like we did not.

Will continue to try.

**Comment by gsumpster** [comment] 2016-08-19 17:32
[Here's the full original log, ](http://hastebin.com/upowaqetaw.tex), lots going on in there, that log wasn't a reproduction, just me messing around.

The document mapping type error looks like it's being thrown correctly, right, because it's as a result of the action being taken, and the cluster going red is because it can't find places to assign shards.

I need to reproduce this again, but when I initially did this, all of the shards were unassigned, primary and replica.
