### ISSUE TITLE
Invalid receiver type interface org.apache.http.Header -from RestClient.convertResponse 7.9.0

### ISSUE THREAD

**Issue by marco-miller** [elastic/elasticsearch#61664] opened 2020-08-27 21:49 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 7.9.0

**Plugins installed**: []

**JVM version** (`java -version`): `1.8.0_231`

**OS version** (`uname -a` if on a Unix-like system): macOS 10.15.6

**Description of the problem including expected versus actual behavior**:

```
java.lang.BootstrapMethodError: call site initialization exception
	at java.lang.invoke.CallSite.makeSite(CallSite.java:341)
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
	at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:288)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:272)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:246)
(...)
Caused by: java.lang.invoke.LambdaConversionException: Invalid receiver type interface org.apache.http.Header; not a subtype of implementation type interface org.apache.http.NameValuePair
	at java.lang.invoke.AbstractValidatingLambdaMetafactory.validateMetafactoryArgs(AbstractValidatingLambdaMetafactory.java:233)
	at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:303)
	at java.lang.invoke.CallSite.makeSite(CallSite.java:302)
	... 63 more
```

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. `private volatile RestClient client;`
 2. `private final List<HttpHost> hosts;`
 3. `RestClientBuilder builder = RestClient.builder(hosts.toArray(new HttpHost[hosts.size()]));`
 4. `client = builder.build();`
 5. `Response response = client.performRequest(new Request("GET", "/"));`

**Provide logs (if relevant)**: stack trace further above.

**Comment by marco-miller** [comment] 2020-08-27 21:51
May relate to #60174.

**Comment by swallez** [comment] 2020-09-04 12:34
@marco-miller can you check if there are several versions of `httpcore.jar` in your classpath and tell us the versions (even if there's only one)? Thanks.

**Comment by marco-miller** [comment] 2020-09-04 20:50
Project has been using version 4.4.1 of org.apache.httpcomponents including httpcore. I just realized that while looking into your question above; thanks for the pointer.

I started working on aligning those with the ones prescribed in this client's pom file. Meaning, trying with httpcore 4.4.12 and 4.5.10 for the other http components. More to come once I get my latest results with this applied, then.

**Comment by marco-miller** [comment] 2020-09-05 00:54
Doing that (above) fixed the issue; thanks again. I think we can close this. My next step will be to try to get those dependency upgrades approved.

**Comment by swallez** [comment] 2020-09-05 14:09
Thanks for the feedback @marco-miller!

An additional question though: would it help if the version of httpcomponents used by the Elasticsearch client was shaded, i.e. renamed to e.g. `org.elasticsearch.org.apache.http`? This would avoid conflicts with the same dependency with another version in the application at the price of duplication of that library in the running process.

I also understand you need approval to upgrade dependencies, so a shaded version would only require approval for the Elasticsearch client, and not for httpcomponents used in other places of the application.

**Comment by marco-miller** [comment] 2020-09-05 20:32
That would be great, yes. This approach would make the client even more autonomous than it is today. Shading would guarantee proper dependency versions loaded, no matter the surrounding ones, making the client more robust -against issues such as this one.

Applications like "mine" (Gerrit), which partly depend on stricter dependency versions (Google's), would benefit from this I think. The client and its changing versions -dependencies- would become easier to 1) integrate and 2) upgrade.

The requirements left would be for the integrator to accept the shaded versions coming with the client version to upgrade to, and for the client to only bundle what it really needs, to foster that acceptance. Adopting the upgraded client may be easier and faster that (whole) way.

Two flavours of the client could be needed depending on who's using it. One with the shaded dependencies and another without, as it is today.

**Comment by marco-miller** [comment] 2020-09-05 20:52
In terms of Gerrit, it has a mix of dependencies that require Google's library compliance and others that don't, based on if Google is using them or not. The http components are split between both baskets. The elastic client is in the latter, but its http dependencies are split, that way. I can point you to which one is in which basket if need be.

**Comment by swallez** [comment] 2020-09-07 11:34
Thanks @marco-miller for your detailed feedback. I'm closing this issue and we'll see if we want to provide out of the box shaded versions in the future. In the meantime are you aware of the [instructions to shade the dependencies in your build](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-low-usage-shading.html)?

**Closed by swallez** 2020-09-07 11:34 UTC
Labels: :Core/Features/Java High Level REST Client, >bug, Team:Core/Features, v7.9.0

**Comment by dserdyuk** [comment] 2021-03-12 02:52
It seems like the issue is reproducable even with single httpcore jar in classpath.. in my case it was 4.4.6.
I managed to workaround without shaded jar by adding deependencyManagement in pom.xml


    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.apache.httpcomponents</groupId>
                <artifactId>httpclient</artifactId>
                <version>4.5.10</version>
            </dependency>
            <dependency>
                <groupId>org.apache.httpcomponents</groupId>
                <artifactId>httpcore</artifactId>
                <version>4.4.12</version>
            </dependency>
    </dependencyManagement>

**Comment by reality** [comment] 2021-04-21 09:25
My experience in Gradle was slightly more painful; I ended up having to force versions of the other httpcomponents modules too. Posting here just in case it saves anyone else some time:

```gradle
dependencies {
      // [ ... your other dependencies here ]

      implementation('org.apache.httpcomponents:httpclient') {
        version {
          strictly '4.5.10'
        }
      }
      implementation('org.apache.httpcomponents:httpmime') {
        version {
          strictly '4.5.10'
        }
      }
      implementation('org.apache.httpcomponents:httpcore') {
        version {
          strictly '4.4.12'
        }
      }
     implementation('org.apache.httpcomponents:httpcore-osgi') {
        version {
          strictly '4.4.12'
        }
      }
}
```

**Comment by FangPengbo** [comment] 2023-10-10 09:42
```
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpcore</artifactId>
            <version>4.4.12</version>
        </dependency>

```

ok!
