### ISSUE TITLE
Date range query does it support microseconds?

### ISSUE THREAD

**Issue by jacobsy** [elastic/elasticsearch#29422] opened 2018-04-08 09:49 UTC
**Describe the feature**:    Query by date range precision

**Elasticsearch version** (`bin/elasticsearch --version`):"elasticseach-5.5.3"

**JVM version** (`java -version`): 1.8

**OS version** (`uname -a` if on a Unix-like system): 
2.6.32-431.23.3.el6.x86_64 #1 SMP Thu Jul 31 17:20:51 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Expect to get greater than equal "2018-03-29T07:10:18.463242817Z" records, but recodes Less than it  have also appeared. details see picture.

**Provide logs (if relevant)**:
![image](https://user-images.githubusercontent.com/2225457/38465826-fbd817f6-3b52-11e8-951c-b3e66085e775.png)

**Comment by dadoonet** [comment] 2018-04-08 10:49
Duplicate of https://github.com/elastic/elasticsearch/issues/10005

Better to ask questions on discuss.elastic.co. Thanks!

**Closed by dadoonet** 2018-04-08 10:49 UTC
