### ISSUE TITLE
[CI] LegacyFeatureImportanceTests.testClassificationConversion

### ISSUE THREAD

**Issue by pugnascotia** [elastic/elasticsearch#62991] opened 2020-09-29 09:16 UTC
**Build scan**:

https://gradle-enterprise.elastic.co/s/4dhwmblof4xrk/tests/:x-pack:plugin:core:test/org.elasticsearch.xpack.core.ml.inference.results.LegacyFeatureImportanceTests/testClassificationConversion#1

**Repro line**:

```
./gradlew ':x-pack:plugin:core:test' --tests "org.elasticsearch.xpack.core.ml.inference.results.LegacyFeatureImportanceTests.testClassificationConversion" -Dtests.seed=30FAB24BFEFCD7BD -Dtests.security.manager=true -Dtests.locale=fr-CA -Dtests.timezone=Pacific/Easter -Druntime.java=11
```

**Reproduces locally?**:

Yes

**Applicable branches**:

~`master`~ (test was removed in that branch), `7.x` 

**Failure history**:

**Failure excerpt**:

```
org.elasticsearch.xpack.core.ml.inference.results.LegacyFeatureImportanceTests > testClassificationConversion FAILED
    java.lang.AssertionError:
    Expected: <org.elasticsearch.xpack.core.ml.inference.results.LegacyFeatureImportance@8b0f5b59>
         but: was <org.elasticsearch.xpack.core.ml.inference.results.LegacyFeatureImportance@588baefb>
        at __randomizedtesting.SeedInfo.seed([30FAB24BFEFCD7BD:F9906A32C9379BB9]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.core.ml.inference.results.LegacyFeatureImportanceTests.testClassificationConversion(LegacyFeatureImportanceTests.java:59)
```

**Comment by droberts195** [comment] 2020-09-29 10:41
The failing test will shortly be removed by #62989

**Comment by dimitris-athanasiou** [comment] 2020-09-29 11:23
Even though #62989 removes this from the master branch, the test remains in 7.x. I know what the problem is, I'll fix it shortly.

**Comment by dimitris-athanasiou** [comment] 2020-09-29 12:55
Fixed in 7.x by https://github.com/elastic/elasticsearch/pull/63000

**Closed by dimitris-athanasiou** 2020-09-29 12:55 UTC
Labels: :ml, >test-failure
