### ISSUE TITLE
docker.elastic.co is down

### ISSUE THREAD

**Issue by aviau** [elastic/elasticsearch#61047] opened 2020-08-12 16:41 UTC
Looks like your docker registry is down.

```
$ docker pull docker.elastic.co/elasticsearch/elasticsearch:7.2.0
Error response from daemon: Get https://docker.elastic.co/v2/elasticsearch/elasticsearch/manifests/7.2.0: unauthorized: authentication required
```

This breaks our CI :cry:

**Comment by kjdelisle** [comment] 2020-08-12 17:11
cc @dakrone @ywelsch 

Sorry if I'm pinging the wrong folks, didn't see anything obvious that named contacts for this sort of thing.

**Comment by ywelsch** [comment] 2020-08-12 17:24
The team is working with highest priority on a fix. Sorry for the disruption.

**Comment by xeraa** [comment] 2020-08-12 17:25
In the meantime you could pull directly from dockerhub (where we mirror our images): `docker pull elasticsearch:7.2.0`

**Comment by xeraa** [comment] 2020-08-12 17:27
Also it should be working again 😅

**Comment by rjernst** [comment] 2020-08-13 03:13
As noted by @xeraa, this has been fixed. Closing.

**Closed by rjernst** 2020-08-13 03:13 UTC
Labels: >bug, needs:triage

**Comment by fzyzcjy** [comment] 2020-11-21 14:05
Hi I still see this issue :(

```
docker pull docker.elastic.co/eck/eck-operator:1.3.0
1.3.0: Pulling from eck/eck-operator
4753a4528f5f: Pulling fs layer 
c0194df27eff: Pulling fs layer 
883e829391d8: Pulling fs layer 
8a5da2b735d7: Waiting 
40ef5e53df00: Waiting 
682d96ac8f41: Waiting 
error pulling image configuration: Get https://docker.elastic.co/v2/eck/eck-operator/blobs/sha256:fd4f062e1c64d8f19a7099db9abb7f4a7b7741a20f8e39bbd6f02d6915ff96ba: EOF
```

but when curl

```
curl  https://docker.elastic.co/v2/eck/eck-operator/blobs/sha256:fd4f062e1c64d8f19a7099db9abb7f4a7b7741a20f8e39bbd6f02d6915ff96ba
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"eck/eck-operator","Action":"pull"}]}]}
```

**Comment by xeraa** [comment] 2020-11-23 04:37
This looks like a different issue. If it persists for you, please open an issue in https://github.com/elastic/cloud-on-k8s/issues

PS: This does not reproduce for me:

```
≻ docker logout docker.elastic.co
Removing login credentials for docker.elastic.co
≻ docker pull docker.elastic.co/eck/eck-operator:1.3.0
1.3.0: Pulling from eck/eck-operator
4753a4528f5f: Pull complete 
c0194df27eff: Pull complete 
883e829391d8: Pull complete 
8a5da2b735d7: Pull complete 
40ef5e53df00: Pull complete 
682d96ac8f41: Pull complete 
Digest: sha256:6b6c9ababfb0c14a87846612c42a84eff7a6159f4447f0b46b60a5f6c993b727
Status: Downloaded newer image for docker.elastic.co/eck/eck-operator:1.3.0
docker.elastic.co/eck/eck-operator:1.3.0
```

**Comment by fzyzcjy** [comment] 2020-11-23 06:35
@xeraa The issue disappeared finally. Thanks for the reply!
