### ISSUE TITLE
Memory lock lost on Windows Server 2012R2

### ISSUE THREAD

**Issue by xorandor** [elastic/elasticsearch#16750] opened 2016-02-21 19:56 UTC
I'm running my nodes with 
`bootstrap.mlockall: true`
and I have verified that the memory is allocated using task manager and if I run 
`curl http://localhost:9200/_nodes/process?pretty`
it's confirmed the lock's in place.

I've experienced that a node might "loose" some of the previously allocated memory, where instead I see that memory has been allocated to lucene index files as mapped files.

As soon as there's load on the node (assuming it's trying to use the expected available heap memory) the cluster turns red, shows all shards assigned to the node as unassigned. Nothing is logged when it happens.

**Comment by clintongormley** [comment] 2016-02-28 19:20
Hi @xorandor 

Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only. If you find a bug then feel free to open an issue with the details.

thanks

**Comment by clintongormley** [comment] 2016-02-28 19:21
Ah windows, didn't see that.  I think this is a duplicate of https://github.com/elastic/elasticsearch/issues/13648

**Closed by clintongormley** 2016-02-28 19:21 UTC
