### ISSUE TITLE
java.lang.RuntimeException: java.lang.ClassNotFoundException: com.unboundid.util.Debug

### ISSUE THREAD

**Issue by sanyam1212** [elastic/elasticsearch#31245] opened 2018-06-11 13:52 UTC
**Elasticsearch version** : 5.3.3

**Plugins installed**: [x-pack]

**JVM version**: java version "1.8.0_171"

**OS version** : Ubuntu 14.04

**Description of the problem including expected versus actual behaviour**:
I'm trying to implement a simple watch service using elastic-search watcher but am facing following errors/exceptions.....although syntactically the code seems ok...but I think there's an issue with the dependencies. I have followed the official documentation :
https://www.elastic.co/guide/en/x-pack/5.3/xpack-introduction.html

A similar issue was raised here on stackoverflow:
https://stackoverflow.com/questions/50797498/unable-to-create-prebuiltxpacktransportclient-x-pack-elastic-search
but hasn't been answered!
 
**Code**:
package watcher;

import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.List;

import org.elasticsearch.action.search.SearchRequest;
import org.elasticsearch.action.search.SearchType;
import org.elasticsearch.client.Requests;
import org.elasticsearch.client.transport.TransportClient;
import org.elasticsearch.cluster.metadata.IndexMetaData;
import org.elasticsearch.common.bytes.BytesArray;
import org.elasticsearch.common.collect.ImmutableOpenMap;
import org.elasticsearch.common.settings.Settings;
import org.elasticsearch.common.transport.InetSocketTransportAddress;
import org.elasticsearch.index.query.BoolQueryBuilder;
import org.elasticsearch.index.query.QueryBuilders;
import org.elasticsearch.script.Script;
import org.elasticsearch.search.builder.SearchSourceBuilder;
import org.elasticsearch.transport.client.PreBuiltTransportClient;
import org.elasticsearch.xpack.XPackClient;
import org.elasticsearch.xpack.client.PreBuiltXPackTransportClient;
//import org.elasticsearch.xpack.client.PreBuiltXPackTransportClient;
import org.elasticsearch.xpack.notification.email.EmailTemplate;
import org.elasticsearch.xpack.watcher.actions.email.EmailAction;
import org.elasticsearch.xpack.watcher.client.WatchSourceBuilder;
import org.elasticsearch.xpack.watcher.client.WatchSourceBuilders;
import org.elasticsearch.xpack.watcher.client.WatcherClient;
import org.elasticsearch.xpack.watcher.condition.ScriptCondition;
import org.elasticsearch.xpack.watcher.input.search.SearchInput;
import org.elasticsearch.xpack.watcher.support.search.WatcherSearchTemplateRequest;
import org.elasticsearch.xpack.watcher.transport.actions.put.PutWatchResponse;
import org.elasticsearch.xpack.watcher.trigger.TriggerBuilders;
import org.elasticsearch.xpack.watcher.trigger.schedule.Schedules;
import com.carrotsearch.hppc.cursors.ObjectObjectCursor;

public class Watch {

	@SuppressWarnings("unchecked")
	public static void main(String[] args) throws UnknownHostException {

		@SuppressWarnings("resource")
		TransportClient client = new PreBuiltXPackTransportClient(
				Settings.builder().put("cluster.name", "elasticsearch").build())
						.addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName("localhost"), 9300));

		ImmutableOpenMap<String, IndexMetaData> indices = client.admin().cluster()
			    .prepareState().get().getState()
			    .getMetaData().getIndices();
		
		for (ObjectObjectCursor<String, IndexMetaData> objectObjectCursor : indices) {
			System.out.println(objectObjectCursor.key);
		}
		
		XPackClient xpackClient = new XPackClient(client);
		WatcherClient watcherClient = xpackClient.watcher();

		WatchSourceBuilder watchSourceBuilder = WatchSourceBuilders.watchBuilder();

		// Set the trigger
		watchSourceBuilder.trigger(TriggerBuilders.schedule(Schedules.cron("0 0/1 * * * ?")));

		BoolQueryBuilder query_er = QueryBuilders.boolQuery().filter(QueryBuilders.termQuery("message", "error"));
		
		// Create the search request to use for the input
		SearchRequest request = Requests.searchRequest("idx")
				.source(SearchSourceBuilder.searchSource().query(query_er));

		// Create the search input
		SearchInput input = new SearchInput(new WatcherSearchTemplateRequest(new String[] { "idx" }, null,
				SearchType.DEFAULT, WatcherSearchTemplateRequest.DEFAULT_INDICES_OPTIONS,
				new BytesArray(request.source().toString())), null, null, null);

		// Set the input
		watchSourceBuilder.input(input);

		// Set the condition
		watchSourceBuilder.condition(new ScriptCondition(new Script("ctx.payload.hits.total > 1")));

		// Create the email template to use for the action
		EmailTemplate.Builder emailBuilder = EmailTemplate.builder();
		emailBuilder.to("abc.def@xyz.com");
		emailBuilder.subject("404");
		EmailAction.Builder emailActionBuilder = EmailAction.builder(emailBuilder.build());

		// Add the action
		watchSourceBuilder.addAction("email_someone", emailActionBuilder);

		PutWatchResponse putWatchResponse = watcherClient.preparePutWatch("my-watch").setSource(watchSourceBuilder)
				.get();
		System.out.println(putWatchResponse);
	}
}

**Error logs ()**: 
![error](https://user-images.githubusercontent.com/15365045/41235122-a7c302ee-6dab-11e8-8839-fa9e4abf0578.png)

**Comment by DaveCTurner** [comment] 2018-06-11 14:05
The root cause

    Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)

suggests to me that you have a corrupt jar file in your environment. We prefer to keep Github issues for bug reports and feature requests, so I'm going to close this issue. In future, please note that https://discuss.elastic.co is the best place to ask questions like this.

**Closed by DaveCTurner** 2018-06-11 14:05 UTC
