### ISSUE TITLE
Elasticsearch shuts down automatically

### ISSUE THREAD

**Issue by maverickpravin** [elastic/elasticsearch#34153] opened 2018-09-28 17:04 UTC
I am using a VM instance running Ubuntu (1GB RAM + 25GB Harddisk) with Elasticsearch on it. Although I have managed to install the elasticsearch on it when i start the service via 
`sudo service elasticsearch start` the ES service starts and then stops after few seconds. Throwing following error
![capture](https://user-images.githubusercontent.com/11708491/46222543-4b2f2580-c36e-11e8-82ec-ce10789c4cd2.PNG)

**Comment by nik9000** [comment] 2018-09-28 18:33
I'm going to close this because we try to reserve github for feature requests and confirmed bug reports. This *might* a bug with Elasticsearch but usually things like this are environmental and you can track them down by looking at the logs in `/var/log/elasticsearch`. If that isn't helpful then please post about this on https://discuss.elastic.co/c/elasticsearch with the contents of the logs or reproduction steps from a clean install or something like that. Sorry I couldn't be of more help!

**Closed by nik9000** 2018-09-28 18:33 UTC
