### ISSUE TITLE
simulate api and ingest pipeline behaves different when Json processor is used for a document containing a nested field with same field name

### ISSUE THREAD

**Issue by TomonoriSoejima** [elastic/elasticsearch#96053] opened 2023-05-12 01:22 UTC
### Elasticsearch Version

8.7.0

### Java Version

_bundled_

### OS Version

linux

### Problem Description

I noticed this behavior while using JSON processor in ingest pipeline after testing the processor in ingest UI.

You can see from the screenshot that I have `message` field nested in the parent `message` field and it is successfully parsed inside the target_field `parsed_json`

![image](https://github.com/elastic/elasticsearch/assets/25199092/ff7a8b81-bc93-42ce-bbef-77650b0fbe5a)

So I tried to run via `_ingest` and I encountered this error in  `POST my_index/_doc/2?pipeline=test`

```
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "failed to parse field [parsed_json.message] of type [text] in document with id '2'. Preview of field's value: '{nest1=nest1, nest2=nest2}'"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "failed to parse field [parsed_json.message] of type [text] in document with id '2'. Preview of field's value: '{nest1=nest1, nest2=nest2}'",
    "caused_by": {
      "type": "illegal_state_exception",
      "reason": "Can't get text on a START_OBJECT at 1:180"
    }
  },
  "status": 400
}

```

### Steps to Reproduce

As a workaround, I had to rename `message` inside the parent field `message` to `message1`.

```
PUT _ingest/pipeline/test
{
  "processors": [
    {
      "json": {
        "field": "message",
        "target_field": "parsed_json",
          "ignore_failure": true
      }
    }
  ]
}


POST /_ingest/pipeline/_simulate
{
  "pipeline": {
    "processors": [
      {
        "json": {
          "field": "message",
          "target_field": "parsed_json",
          "ignore_failure": true
        }
      }
    ]
  },
  "docs": [
    {
      "_source": {
          "message": """{"newHire":"Person1","id":"36", "message":{"nest1": "nest1","nest2":"nest2"}}"""
      }
    }
  ]
}



POST my_index/_doc/2?pipeline=test
{
  "level": "INFO",
  "message": """{"newHire":"Person1","id":"36", "message":{"nest1": "nest1","nest2":"nest2"}}"""
}



POST my_index/_doc/3?pipeline=test
{
  "level": "INFO",
  "message": """{"newHire":"Person1","id":"36", "message1":{"nest1": "nest1","nest2":"nest2"}}"""
}
```

But  I believe that we should be able to use the same field name as the preferred behavior.

**Comment by TomonoriSoejima** [comment] 2023-05-31 05:55
Doing the same in 8.6 worked.

**Comment by mattc58** [comment] 2023-12-28 16:12
I am unable to reproduce this on either `main` or on `8.7.0`. The nested `message` field appears in the ingested document, and seems to behave just as `_simulate` does. Closing this for now--please do reopen if there's more information here that I missed.

**Closed by mattc58** 2023-12-28 16:12 UTC
Labels: >bug, :Data Management/Ingest Node, Team:Data Management
