### ISSUE TITLE
[CI] amazon-2&&immutable failing multiple times

### ISSUE THREAD

**Issue by kingherc** [elastic/elasticsearch#93651] opened 2023-02-09 14:00 UTC
### CI Link

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+8.6+multijob+platform-support-unix/os=amazon-2&&immutable/170/

### Repro line

./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.action.admin.ReloadSecureSettingsIT.testInvalidKeystoreFile" -Dtests.seed=E93B0D7895404FAB -Dtests.locale=ms -Dtests.timezone=Asia/Dubai -Druntime.java=17

### Does it reproduce?

Didn't try

### Applicable branches

main, 8.6, 8.7, 7.17

### Failure history

See below

### Failure excerpt

Failure histories:

* 8.6 https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+8.6+multijob+platform-support-unix/os=amazon-2&&immutable/
* 8.7 https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+8.7+multijob+platform-support-unix/os=amazon-2&&immutable/
* 7.17 https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.17+multijob+platform-support-unix/os=amazon-2&&immutable/
* main https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+main+multijob+platform-support-unix/os=amazon-2&&immutable/

Full console is almost 800 MiB! Beginning shows:

```
<span class="timestamp"><b>09:54:33</b> </span>
<span class="timestamp"><b>09:54:33</b> </span>REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.action.admin.ReloadSecureSettingsIT.testInvalidKeystoreFile" -Dtests.seed=E93B0D7895404FAB -Dtests.locale=ms -Dtests.timezone=Asia/Dubai -Druntime.java=17
<span class="timestamp"><b>09:54:33</b> </span>
<span class="timestamp"><b>09:54:33</b> </span>org.elasticsearch.action.admin.ReloadSecureSettingsIT &gt; testInvalidKeystoreFile FAILED
<span class="timestamp"><b>09:54:33</b> </span>    java.lang.AssertionError
<span class="timestamp"><b>09:54:33</b> </span>        at org.junit.Assert.fail(Assert.java:86)
<span class="timestamp"><b>09:54:33</b> </span>        at org.junit.Assert.assertTrue(Assert.java:41)
<span class="timestamp"><b>09:54:33</b> </span>        at org.junit.Assert.assertFalse(Assert.java:64)
<span class="timestamp"><b>09:54:33</b> </span>        at org.junit.Assert.assertFalse(Assert.java:74)
<span class="timestamp"><b>09:54:33</b> </span>        at org.elasticsearch.test.InternalTestCluster.validateClusterFormed(InternalTestCluster.java:1215)
<span class="timestamp"><b>09:54:33</b> </span>        at org.elasticsearch.test.InternalTestCluster.startAndPublishNodesAndClients(InternalTestCluster.java:1746)
<span class="timestamp"><b>09:54:33</b> </span>        at org.elasticsearch.test.InternalTestCluster.reset(InternalTestCluster.java:1192)
<span class="timestamp"><b>09:54:33</b> </span>        at org.elasticsearch.test.InternalTestCluster.beforeTest(InternalTestCluster.java:1085)
<span class="timestamp"><b>09:54:33</b> </span>        at org.elasticsearch.test.ESIntegTestCase.lambda$beforeInternal$0(ESIntegTestCase.java:362)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.RandomizedContext.runWithPrivateRandomness(RandomizedContext.java:187)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.RandomizedContext.runWithPrivateRandomness(RandomizedContext.java:211)
<span class="timestamp"><b>09:54:33</b> </span>        at org.elasticsearch.test.ESIntegTestCase.beforeInternal(ESIntegTestCase.java:371)
<span class="timestamp"><b>09:54:33</b> </span>        at org.elasticsearch.test.ESIntegTestCase.setupTestCluster(ESIntegTestCase.java:2228)
<span class="timestamp"><b>09:54:33</b> </span>        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
<span class="timestamp"><b>09:54:33</b> </span>        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
<span class="timestamp"><b>09:54:33</b> </span>        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
<span class="timestamp"><b>09:54:33</b> </span>        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:980)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
<span class="timestamp"><b>09:54:33</b> </span>        at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
<span class="timestamp"><b>09:54:33</b> </span>        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
<span class="timestamp"><b>09:54:33</b> </span>        at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
<span class="timestamp"><b>09:54:33</b> </span>        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
<span class="timestamp"><b>09:54:33</b> </span>        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
<span class="timestamp"><b>09:54:33</b> </span>        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
<span class="timestamp"><b>09:54:33</b> </span>        at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
<span class="timestamp"><b>09:54:33</b> </span>        at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
<span class="timestamp"><b>09:54:33</b> </span>        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
<span class="timestamp"><b>09:54:33</b> </span>        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
<span class="timestamp"><b>09:54:33</b> </span>        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
<span class="timestamp"><b>09:54:33</b> </span>        at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
<span class="timestamp"><b>09:54:33</b> </span>        at java.base/java.lang.Thread.run(Thread.java:833)

<span class="timestamp"><b>09:54:33</b> </span>    java.lang.AssertionError: ClusterHealthResponse has timed out - returned: [{"cluster_name":"SUITE-TEST_WORKER_VM=[148]-CLUSTER_SEED=[-6642037413227423824]-HASH=[1047FDDA10D]-cluster","status":"green","timed_out":true,"number_of_nodes":5,"number_of_data_nodes":2,"active_primary_shards":0,"active_shards":0,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":0,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":100.0}]
<span class="timestamp"><b>09:54:33</b> </span>    Expected: is &lt;false&gt;
<span class="timestamp"><b>09:54:33</b> </span>         but: was &lt;true&gt;
<span class="timestamp"><b>09:54:33</b> </span>        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
<span class="timestamp"><b>09:54:33</b> </span>        at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertNoTimeout(ElasticsearchAssertions.java:99)
<span class="timestamp"><b>09:54:33</b> </span>        at org.elasticsearch.test.ESIntegTestCase.ensureClusterSizeConsistency(ESIntegTestCase.java:1088)
<span class="timestamp"><b>09:54:33</b> </span>        at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:574)
<span class="timestamp"><b>09:54:33</b> </span>        at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2244)
<span class="timestamp"><b>09:54:33</b> </span>        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
<span class="timestamp"><b>09:54:33</b> </span>        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
<span class="timestamp"><b>09:54:33</b> </span>        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
<span class="timestamp"><b>09:54:33</b> </span>        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
<span class="timestamp"><b>09:54:33</b> </span>        at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
<span class="timestamp"><b>09:54:33</b> </span>        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
<span class="timestamp"><b>09:54:33</b> </span>        at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
<span class="timestamp"><b>09:54:33</b> </span>        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
<span class="timestamp"><b>09:54:33</b> </span>        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
<span class="timestamp"><b>09:54:33</b> </span>        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
<span class="timestamp"><b>09:54:33</b> </span>        at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
<span class="timestamp"><b>09:54:33</b> </span>        at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
<span class="timestamp"><b>09:54:33</b> </span>        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
<span class="timestamp"><b>09:54:33</b> </span>        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
<span class="timestamp"><b>09:54:33</b> </span>        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
<span class="timestamp"><b>09:54:33</b> </span>        at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
<span class="timestamp"><b>09:54:33</b> </span>        at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
<span class="timestamp"><b>09:54:33</b> </span>        at java.base/java.lang.Thread.run(Thread.java:833)
<span class="timestamp"><b>09:54:39</b> </span>
<span class="timestamp"><b>09:54:39</b> </span>REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.action.admin.cluster.repositories.RepositoryBlocksIT.testDeleteRepositoryWithBlocks" -Dtests.seed=E93B0D7895404FAB -Dtests.locale=es-US -Dtests.timezone=SystemV/MST7 -Druntime.java=17
<span class="timestamp"><b>09:54:39</b> </span>
```

Then comes a very long list of similar errors like:

```
<span class="timestamp"><b>09:54:43</b> </span>  1&gt; [2023-02-09T00:53:08,818][ERROR][o.e.t.TcpTransport       ] [node_t0] exception from server channel caught on transport layer [Netty4TcpChannel{localAddress=/127.0.0.1:17711}]
<span class="timestamp"><b>09:54:43</b> </span>  1&gt; java.io.IOException: Invalid argument
<span class="timestamp"><b>09:54:43</b> </span>  1&gt;  at sun.nio.ch.Net.accept(Native Method) ~[?:?]
<span class="timestamp"><b>09:54:43</b> </span>  1&gt;  at sun.nio.ch.ServerSocketChannelImpl.implAccept(ServerSocketChannelImpl.java:425) ~[?:?]
<span class="timestamp"><b>09:54:43</b> </span>  1&gt;  at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:391) ~[?:?]
<span class="timestamp"><b>09:54:43</b> </span>  1&gt;  at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:119) ~[netty-common-4.1.84.Final.jar:4.1.84.Final]
<span class="timestamp"><b>09:54:43</b> </span>  1&gt;  at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:116) ~[netty-common-4.1.84.Final.jar:4.1.84.Final]
<span class="timestamp"><b>09:54:43</b> </span>  1&gt;  at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]
<span class="timestamp"><b>09:54:43</b> </span>  1&gt;  at io.netty.util.internal.SocketUtils.accept(SocketUtils.java:116) ~[netty-common-4.1.84.Final.jar:4.1.84.Final]
<span class="timestamp"><b>09:54:43</b> </span>  1&gt;  at org.elasticsearch.transport.netty4.CopyBytesServerSocketChannel.doReadMessages(CopyBytesServerSocketChannel.java:45) ~[transport-netty4-8.6.2-SNAPSHOT.jar:8.6.2-SNAPSHOT]
<span class="timestamp"><b>09:54:43</b> </span>  1&gt;  at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:79) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
<span class="timestamp"><b>09:54:43</b> </span>  1&gt;  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
<span class="timestamp"><b>09:54:43</b> </span>  1&gt;  at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
<span class="timestamp"><b>09:54:43</b> </span>  1&gt;  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
<span class="timestamp"><b>09:54:43</b> </span>  1&gt;  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
<span class="timestamp"><b>09:54:43</b> </span>  1&gt;  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.84.Final.jar:4.1.84.Final]
<span class="timestamp"><b>09:54:43</b> </span>  1&gt;  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.84.Final.jar:4.1.84.Final]
<span class="timestamp"><b>09:54:43</b> </span>  1&gt;  at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by mark-vieira** [comment] 2023-02-09 16:25
Something here is causing internal cluster tests to go haywire and spam this exception over and over. As mentioned, the log is 100s of MB and eventually all this noise causes the build to run out of heap and crash.

```  1> [2023-02-08T20:53:22,691][ERROR][o.e.t.TcpTransport       ] [node_t0] exception from server channel caught on transport layer [Netty4TcpChannel{localAddress=/127.0.0.1:17742}]
  1> java.io.IOException: Invalid argument
  1> 	at sun.nio.ch.Net.accept(Native Method) ~[?:?]
  1> 	at sun.nio.ch.ServerSocketChannelImpl.implAccept(ServerSocketChannelImpl.java:425) ~[?:?]
  1> 	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:391) ~[?:?]
  1> 	at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:119) ~[netty-common-4.1.84.Final.jar:4.1.84.Final]
  1> 	at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:116) ~[netty-common-4.1.84.Final.jar:4.1.84.Final]
  1> 	at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]
  1> 	at io.netty.util.internal.SocketUtils.accept(SocketUtils.java:116) ~[netty-common-4.1.84.Final.jar:4.1.84.Final]
  1> 	at org.elasticsearch.transport.netty4.CopyBytesServerSocketChannel.doReadMessages(CopyBytesServerSocketChannel.java:45) ~[transport-netty4-8.6.2-SNAPSHOT.jar:8.6.2-SNAPSHOT]
  1> 	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:79) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
  1> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
  1> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
  1> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
  1> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
  1> 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.84.Final.jar:4.1.84.Final]
  1> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.84.Final.jar:4.1.84.Final]
  1> 	at java.lang.Thread.run(Thread.java:833) ~[?:?]```

**Comment by DaveCTurner** [comment] 2023-02-14 09:06
I've tried reproducing this on an Amazon Linux machine but so far no luck. My reading of the JDK source is that it means `accept()` is returning `EINVAL`; the [docs](https://linux.die.net/man/2/accept) say:

> **EINVAL**
> Socket is not listening for connections, or addrlen is invalid (e.g., is negative).

I don't see how either of these things could be the problem, but these docs are often not exhaustive so it could be something else. I wonder if perhaps we are running into some system-wide limit, but without being able to reproduce this I don't know how to find it.

**Comment by pxsalehi** [comment] 2023-02-14 09:57
There seems to be more of this, e.g.: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+8.6+multijob+platform-support-unix/os=amazon-2&&immutable/179/consoleFull

Where some highlighter test fails, but actually it is because the cluster fails to form and times out.

There is an OOM error at the end of that log. not sure if it is related
```
20:52:05 Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-1-thread-1"
20:52:11 
20:52:11 Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "main"
```

**Comment by DaveCTurner** [comment] 2023-02-14 10:37
I think this OOME is the one Mark mentioned above, where Gradle itself just falls over under the volume of logs caused by these repeated exceptions. The fundamental problem is the `java.io.IOException: Invalid argument` tho.

**Comment by mark-vieira** [comment] 2023-02-28 16:58
> The fundamental problem is the `java.io.IOException: Invalid argument` tho.

@DaveCTurner Any suggestions on how to proceed here? Is there anything that I or infra could provide to help reproduce or diagnose this failure?

**Comment by DaveCTurner** [comment] 2023-02-28 17:59
I don't have any great ideas here. I tried reproducing this with no luck, but then I might not have been reproducing the CI machine configuration very closely. Maybe try that? It'd be awfully useful to be logged into the machine while this is happening.

**Comment by mark-vieira** [comment] 2023-03-01 19:43
> It'd be awfully useful to be logged into the machine while this is happening.

I'm going to attempt to do this today. I'll follow up with what I find out.

**Comment by mark-vieira** [comment] 2023-03-01 22:21
I can consistently reproduce this, not with any _single_ test, but running any significantly large internal cluster test suite will eventually trigger this. Here's a step-by-step:

1. Trigger [this CI job](https://elasticsearch-ci.elastic.co/view/Elasticsearch%20main/job/elastic+elasticsearch+main+periodic+platform-support/), if one isn't already running
2. [Go to the Amazon 2 job](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+main+multijob+platform-support-unix/os=amazon-2&&immutable/) that's currently running, and find the agent running the build
3. Hit "update offline reason" and make it something that doesn't contain the word "gobld" (you need to log in to do this)
4. Follow [these docs](https://github.com/elastic/infra/blob/master/docs/accessing-instances.md) to SSH into the worker (you can find the IP on the Jenkins agent page)
5. Switch to the `jenkins` user via `sudo -i` followed by `su jenkins`
6. `cd ~/workspace/elastic+elasticsearch+main+multijob+platform-support-unix`
7. `rm ~/.gradle/init.d/*`
8. `export JAVA_HOME=~/.java/openjdk17`
9. `./gradlew :server:internalClusterTest`

For the last step I find that even using `--max-workers 1` it'll still trigger the issue so I don't think it's related to concurrent test execution. It's just _eventually_ it loses its mind. I've tried with Java 17 and 19 as the runtime Java with the same result. Something is _definitely_ wrong on this system. It's not clear whether its some funky way we are customizing these images or a legit incompatibility with Amazon Linux 2. @DaveCTurner do you think you or someone else from the team might have time to look into this. I've spoken with @rdnm and we're not _super_ comfortable with shipping 8.7 with this red in CI although I'm not sure we necessarily want to call this a blocker at this time, given this is failing on all branches, it's highly unlikely to be a regression we've actually introduced.

**Comment by mark-vieira** [comment] 2023-03-09 16:43
Thanks @kingherc. This is indeed an odd one. There's gotta be something particular about the setup on that agent image. It's unlikely that this is a regression we introduced in ES as this started happening on all dev branches at the same time.

**Comment by kingherc** [comment] 2023-03-10 11:30
Hi @mark-vieira , @DaveCTurner , I spent an unreasonable amount of time bisecting commits to figure out if there was a commit that somehow introduced this (or in any case a commit that induces the new behavior if it is new), and I think I found PR https://github.com/elastic/elasticsearch/pull/87885/files being the culprit. I managed to successfully run the previous commit in history (exactly before this PR) 3 times, while this PR fails. Furthermore, I then tried on current `main` by setting to 0 the two ports mentioned in that PR, and it successfully runs 3 iterations now! I am not certain why though. But it does seem probable to me that something wrong with the ports, e.g., clashing ports, might have caused all these errors we saw. But happy I could find something helpful so far. Maybe you two might have more ideas why this is happening. If not, I believe there is something we can do with `getPortRange()` to fix this (instead of setting them to 0 which I see had other unwanted side-effects), and will continue checking that. Maybe I will try increasing PORTS_PER_WORKER.

**Comment by kingherc** [comment] 2023-03-10 16:02
Unfortunately even if I increase PORTS_PER_WORKER from 30 to 300, it fails. Still not sure of the implications of why ephemeral ports (0) work.

**Comment by mark-vieira** [comment] 2023-03-10 18:18
Why is this limited to Amazon 2 though? Is the range of available ports restricted on that system?

**Comment by kingherc** [comment] 2023-03-11 08:58
It might have to do also with how the env var `org.gradle.test.worker` is set on the gradle workers there. Will investigate a bit more when I have time.

**Comment by mark-vieira** [comment] 2023-03-11 16:38
Well, like I said above, I could reproduce this even with a single Gradle
worker (no concurrently executing tests) so I don't think parallelism is at
play here.

**Comment by fcofdez** [comment] 2023-03-24 16:51
I've been looking into the JDK code where the exception is triggered:
https://github.com/openjdk/jdk/blob/97649489d078a3aa34a73e7f686e507f34155788/src/java.base/unix/native/libnio/ch/Net.c#L340-L370
```c
JNIEXPORT jint JNICALL
Java_sun_nio_ch_Net_accept(JNIEnv *env, jclass clazz, jobject fdo, jobject newfdo,
                           jobjectArray isaa)
{
    jint fd = fdval(env, fdo);
    jint newfd;
    SOCKETADDRESS sa;
    socklen_t sa_len = sizeof(SOCKETADDRESS);
    jobject remote_ia;
    jint remote_port = 0;
    jobject isa;

    /* accept connection but ignore ECONNABORTED */
    for (;;) {
        newfd = accept(fd, &sa.sa, &sa_len);
        if (newfd >= 0) {
            break;
        }
        if (errno != ECONNABORTED) {
            break;
        }
        /* ECONNABORTED => restart accept */
    }

    if (newfd < 0) {
        if (errno == EAGAIN || errno == EWOULDBLOCK)
            return IOS_UNAVAILABLE;
        if (errno == EINTR)
            return IOS_INTERRUPTED;
        JNU_ThrowIOExceptionWithLastError(env, "Accept failed");
        return IOS_THROWN;
    }
```
The IOException message comes from the errno:
```
1529:    X(EINVAL, "Invalid argument") \
```

Which according to the accept man page:

```
       EINVAL Socket is not listening for connections, or addrlen is
              invalid (e.g., is negative).
```

Looks strange... I'll keep digging once I've access to the jenkins workers.

**Comment by fcofdez** [comment] 2023-03-27 12:43
```
[ 1144.376417] TCP: request_sock_TCP: Possible SYN flooding on port 37339. Sending cookies.  Check SNMP counters.
```
It looks like the OS might think that there's a SYN flooding attack and it's closing the connections. I'll keep digging into this.

**Comment by fcofdez** [comment] 2023-03-27 14:39
@mark-vieira do you know if something has changed in those jenkins workers? I'm not able to reproduce the issue.

**Comment by mark-vieira** [comment] 2023-03-27 17:20
> @mark-vieira do you know if something has changed in those jenkins workers? I'm not able to reproduce the issue.

Not that I'm aware. Are you not able to reproduce with the instructions I created above? It looks like things are magically passing again on amazon-2 but still failing on Oracle Linux 7.

**Comment by fcofdez** [comment] 2023-03-27 17:22
I've noticed that the kernel version is newer in the latest amazon VMs `kernel-4.14.309-231.529.amzn2.x86_64`. It was `kernel-4.14.305...` before. The change-logs don't point to anything obvious 🤔

**Comment by fcofdez** [comment] 2023-03-27 17:37
This https://github.com/netty/netty/issues/7790#issuecomment-375086126 is exactly what's happening here.

**Comment by cbuescher** [comment] 2023-05-04 12:19
This failure looks related, no build scan upload but long log with tons of netty noise there:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+8.8+multijob+platform-support-unix/os=oraclelinux-7&&immutable/16/console

**Comment by mark-vieira** [comment] 2023-10-04 21:19
Did this just magically sort itself?

**Comment by mark-vieira** [comment] 2023-10-09 17:17
I haven't seen these errors recently so I'm going to close this.

**Closed by mark-vieira** 2023-10-09 17:17 UTC
Labels: :Delivery/Build, :Distributed/Network, >test-failure, Team:Distributed, Team:Delivery
