### ISSUE TITLE
ReplicationTask$Status.toXContent throws "Can not start an object, expecting field name (context: Object)" exception

### ISSUE THREAD

**Issue by floragunncom** [elastic/elasticsearch#26530] opened 2017-09-07 08:31 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 
6.0.0-beta2

**Plugins installed**: 
none

**JVM version** (`java -version`):
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

**OS version** (`uname -a` if on a Unix-like system): 
Mac OS X x86_64 10.10.5
14.5.0 Darwin Kernel Version 14.5.0: Sun Jun  4 21:40:08 PDT 2017; root:xnu-2782.70.3~1/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**: `ReplicationTask$Status.toXContent` should produce valid Xcontent and not throw an `com.fasterxml.jackson.core.JsonGenerationException`. 

**Steps to reproduce**:
Execute Task.getStatus() on a `indices:data/write/bulk[s]` task, for example create a an ActionFilter and write something like this:

<pre>
@Override
    public <Request extends ActionRequest, Response extends ActionResponse> void apply(Task task, String action, Request request,
            ActionListener<Response> listener, ActionFilterChain<Request, Response> chain) {
        
        System.out.println("Task "+task.getAction()+"#"+task.getType()+"#"+task.getStatus()+"#"+task.getParentTaskId());
        ...
</pre>

**Provide logs (if relevant)**:

<pre>
Error building toString out of XContent: com.fasterxml.jackson.core.JsonGenerationException: Can not start an object, expecting field name (context: Object)
	at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:1897)
	at com.fasterxml.jackson.core.json.JsonGeneratorImpl._reportCantWriteValueExpectName(JsonGeneratorImpl.java:244)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator._verifyValueWrite(UTF8JsonGenerator.java:1027)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeStartObject(UTF8JsonGenerator.java:313)
	at org.elasticsearch.common.xcontent.json.JsonXContentGenerator.writeStartObject(JsonXContentGenerator.java:156)
	at org.elasticsearch.common.xcontent.XContentBuilder.startObject(XContentBuilder.java:217)
	at org.elasticsearch.action.support.replication.ReplicationTask$Status.toXContent(ReplicationTask.java:82)
	at org.elasticsearch.common.Strings.toString(Strings.java:803)
	at org.elasticsearch.action.support.replication.ReplicationTask$Status.toString(ReplicationTask.java:95)
...
</pre>

**Comment by bleskes** [comment] 2017-09-07 08:56
Thank you for trying out 6.0.0-beta2. I tried to reproduce this (calling toString on the status of a ShardBulkRequest ) but couldn't. Can you share a code snippet that (a unit test?) that reproduce this?

**Comment by floragunncom** [comment] 2017-09-07 09:22
`       System.out.println(new org.elasticsearch.action.support.replication.ReplicationTask.Status("a").toString()); 
`

**Comment by floragunncom** [comment] 2017-09-07 09:34
Same here and maybe other `org.elasticsearch.tasks.Task.Status` impls are affected as well
<pre>
System.out.println(new org.elasticsearch.index.shard.PrimaryReplicaSyncer.ResyncTask(1,"type","action","desc",new TaskId("task:0")).getStatus().toString());
</pre>

**Comment by bleskes** [comment] 2017-09-07 09:47
I see, and I also see why I couldn't reproduced. This is fixed by https://github.com/elastic/elasticsearch/pull/26321 , where the decision was made to not back port it to 6.0 (I'm still chasing it to see what we can do there). Thanks for trying out the beta. I will make the issue as eligible for the pioneer program.

**Closed by bleskes** 2017-09-07 09:47 UTC
Labels: Pioneer Program
