### ISSUE TITLE
Wildcard and constant_keyword fields are incorrectly identified as `keyword` by field caps api

### ISSUE THREAD

**Issue by mattkime** [elastic/elasticsearch#81022] opened 2021-11-24 21:46 UTC
Kibana data views management exposes the underlying ES field types so users can make decisions about how their data is mapped. Kibana demo data also demonstrates to users what is available.

---

UPDATE - Taking a look at the docs, this is a purposeful decision. Is the reason for the decision documented? Seems I need to do a careful reading of the docs to understand the different between type families and types. `keyword` has the unfortunate distinction  of being both a `type` and a `type family`.

**Comment by markharwood** [comment] 2021-11-25 11:08
This was a deliberate decision (although not one I personally agreed with). 
The `wildcard` field was intended to be a transparent drop-in replacement for `keyword` fields so that Kibana could adopt it more easily. The thinking was that rather than having a proliferation of new data types, we'd group potentially many physical data types under a common logical family e.g. `keyword` family. 

### Why was `wildcard` field considered a member of the `keyword`family?
The rationale was that it was like the `keyword` field because it did not tokenise strings. This makes for a clean split between the families `text` = tokenised, `keyword` = untokenised and then we have the various number/geo fields. Wildcard would just be another alternative implementation of the keyword field. This meant the wildcard field had to support all the functions of `keyword` fields beyond queries, like aggregations and sorting, even though wildcard field is very far from optimised for these extra tasks.

### What sort of content goes into wildcard fields?
In the [wildcard field blog](https://www.elastic.co/blog/find-strings-within-strings-faster-with-the-new-elasticsearch-wildcard-field) I outlined what sort of content people should store in the new `wildcard` fields and why the existing `text` or `keyword` fields were bad choices. The TL/DR is that it is good for storing long, machine-generated content with no common structure e.g. typical log messages.

### Why wildcards might be a bad fit in the keyword family
I'd argue that users [have historically abused keyword fields ](https://socprime.com/blog/elastic-for-security-analysts-part-1-searching-strings/) to store log messages because it was the least-worst option between text and keyword fields. I call it abuse of keyword fields because they didn't want to aggregate or sort on these fields - only search. 
This is why I think of log messages as more like a text field in terms of how you interact with them. The only problem with storing log messages as text fields is they are machine-generated strings (urls, stack traces, file paths), not white-space separated text like this paragraph. When searchers and document analyzers have no shared agreement as to what "words" to store in the index there's no understanding of what to search for.

For my money `wildcard` field is more like a `text` field (search only, no aggs/sorting), but the way you search is different. Unlike text field, searches for words (`quick OR brown fox` etc) are not supported - instead you search for _character_ sequences (`*\.(dll|exe)`). That shift in unstructured search behaviour requires changes to Kibana like[ supporting regex in KQL](https://github.com/elastic/kibana/issues/46855) .

**Comment by jtibshirani** [comment] 2021-11-29 18:24
@mattkime the original discussion can be found in https://github.com/elastic/elasticsearch/issues/53175. Note that our thinking evolved past the proposal in the PR description. In my understanding, this grouping has been a big help to clients like SQL, since they don't need a separate data type (and set of behaviors) for each new ES field type. It also helps on the "search" side of Kibana, as each field type family just needs to be handled once.

This documentation describes "field type families", and groups types according to their family: https://www.elastic.co/guide/en/elasticsearch/reference/7.15/mapping-types.html. Please let us know if you have suggestions for improvements in the docs or behavior.

**Comment by mattkime** [comment] 2021-12-01 03:59
There are a couple of problems with type families as they're implemented:

1) They're ambiguous with types. `keyword` is both a type and a type family. The same is true of `text`. As best I can tell, those are the only two type families. 

2) Not all types belong to a type family. This just muddles the concept. This seems to have happened to scratch a technical itch at the cost of conceptual complexity.

3) Most importantly - We display them to our users via Data view management. Generally speaking, in Kibana we assume that users are working with sets of indices. The field caps api is the only way we can get field information about sets of indices. If field caps doesn't do something or does it in a compromised way we really don't have a way of correcting. This is largely a feature as I've never seen Kibana fail to accurately portray the fields in ES. Our users rely on this info to be an accurate reflection of whats occurring in ES.

---

>this grouping has been a big help to clients

I can accept this, but I find it odd. Treating a number of types as the same type just shouldn't be a technical challenge. Then again, code can always be unpleasantly weird.

**Comment by jtibshirani** [comment] 2021-12-01 23:07
Thanks for the feedback. At this point the discussion is getting further from the intent of the original issue. I also think it'd be better to have a high-bandwidth offline discussion about field types and data view management, then loop back to GitHub when we have more concrete actions. I'll close this out for now and reach out offline.

**Closed by jtibshirani** 2021-12-01 23:07 UTC
Labels: :Search/Mapping, Team:Search
