### ISSUE TITLE
[CI] TransformNoRemoteClusterClientNodeIT testPutTransformWithRemoteIndex_DeferValidation failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#72034] opened 2021-04-21 15:31 UTC
Looks like this test suite has been refactored recently. There have been a couple other failures here as well:

https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=America/Los_Angeles&tests.container=org.elasticsearch.xpack.transform.integration.TransformNoTransformNodeIT&tests.sortField=FAILED&tests.unstableOnly=true

**Build scan:**
https://gradle-enterprise.elastic.co/s/afjzaqedkjhce/tests/:x-pack:plugin:transform:internalClusterTest/org.elasticsearch.xpack.transform.integration.TransformNoRemoteClusterClientNodeIT/testPutTransformWithRemoteIndex_DeferValidation

**Reproduction line:**
`./gradlew ':x-pack:plugin:transform:internalClusterTest' --tests "org.elasticsearch.xpack.transform.integration.TransformNoRemoteClusterClientNodeIT.testPutTransformWithRemoteIndex_DeferValidation" -Dtests.seed=C37544326143C2D1 -Dtests.locale=et -Dtests.timezone=America/Pangnirtung -Druntime.java=11`

**Applicable branches:**
master, 7.x

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.transform.integration.TransformNoRemoteClusterClientNodeIT&tests.test=testPutTransformWithRemoteIndex_DeferValidation

**Failure excerpt:**
```
org.elasticsearch.action.ActionRequestValidationException: Validation Failed: 1: duplicate field [i] detected;

  at __randomizedtesting.SeedInfo.seed([C37544326143C2D1:BAB9FDDF44A5CD30]:0)
  at org.elasticsearch.action.ValidateActions.addValidationError(ValidateActions.java:15)
  at org.elasticsearch.xpack.core.transform.transforms.pivot.PivotConfig.validate(PivotConfig.java:188)
  at org.elasticsearch.xpack.core.transform.transforms.TransformConfig.validate(TransformConfig.java:341)
  at org.elasticsearch.xpack.core.transform.action.PutTransformAction$Request.validate(PutTransformAction.java:74)
  at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:42)
  at org.elasticsearch.tasks.TaskManager.registerAndExecute(TaskManager.java:164)
  at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:97)
  at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:77)
  at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:375)
  at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:364)
  at org.elasticsearch.xpack.transform.integration.TransformNoRemoteClusterClientNodeIT.testPutTransformWithRemoteIndex_DeferValidation(TransformNoRemoteClusterClientNodeIT.java:62)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:834)

```

**Comment by mark-vieira** [comment] 2021-04-21 15:31
@przemekwitek since you work on this test recently do you mind taking a look?

**Comment by przemekwitek** [comment] 2021-04-22 06:46
Closing this issue as a duplicate of https://github.com/elastic/elasticsearch/issues/71950
The root cause has already been fixed.

**Closed by przemekwitek** 2021-04-22 06:46 UTC
Labels: :ml/Transform, >test-failure, Team:ML
