### ISSUE TITLE
Store pre-computed HyperLogLog compatible with Cardinality Aggregation

### ISSUE THREAD

**Issue by ncolomer** [elastic/elasticsearch#24468] opened 2017-05-03 15:18 UTC
Hi community,

At tinyclues (and probably in many other places), we need to count unique IDs over gigantic amounts of events. We already rely on HyperLogLog for many use cases but we are looking for new ways of doing that, especially to make our computed aggregates available in fancy dashboards.

We already know the [Cardinality Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-cardinality-aggregation.html) feature, but actually:
- we don't want to store billions of events into elasticsearch:
  - our data is aggregated offline using Spark
  - original data is already stored elsewhere
- we don't want to send to elasticsearch aggregate documents with an array field containing millions of - even hashed - ID:
  - it generates massive data transfer over-the-wire
  - it induces high write load (HLL computation in addition to indexing fields)
  - we just don't want to store this data in elasticseach (well ok, we can disable storage of this field)

Our analysis shows we're stuck until we have the following features:
1. being able to store pre-computed, serialized / encoded HyperLogLog structures in elasticsearch
2. make the above structure compatible with the Cardinality Aggregator (ie. deserialize / decode + merge HLLs on-the-fly)

For instance, we could have a custom `hyperloglog` type and declare such field in index mapping. It would enable cardinality reduction, and they would just be plain (not analyzed) text field otherwise.

One problem we can see is that the HLL serialization / encoding process must be the same between clients and elasticsearch at write time. Here we can consider reusing elasticsearch's HLL implementation. We could also think of a way to have a normalized representation of an HLL binary structure (a good old byte array) making the feature HLL implementation agnostic.

Does it makes sense?

Cheers,
Nicolas

---

Note 1 - A solution that we consider in the meantime is to:
- compute and serialize HLLs our way (using algebird's implementation for instance), client side
- store them in elasticsearch using any binary-to-text encoding (eg. base64)
- when we query, the client fetches HLL and decodes / deserializes / merges them itself

Note 2 - In the documentation, we can read a paragraph named [Pre-computed hashes](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-cardinality-aggregation.html#_pre_computed_hashes). At the beginning, we though that it was the perfect solution, but then we understood that it was an optimisation: instead of pushing plain strings for instance, you hash them and send the hashes to elasticsearch.

> On string fields that have a high cardinality, it might be faster to store the hash of your field values in your index and then run the cardinality aggregation on this field. This can either be done by providing hash values from client-side or by letting elasticsearch compute hash values for you by using the mapper-murmur3 plugin.

**Comment by colings86** [comment] 2017-05-16 08:57
@ncolomer we had a discussion about this idea internally and although in concept it is something that we would like to provide there are some issues that make it very challenging from a project perspective. These mainly centre around the fact that having this feature would expose the internal algorithm used to compute the cardinality which would make it difficult to be able to change and improve the cardinality aggregation over time.

As an example suppose that we find a better algorithm for calculating the cardinality which requires different state. We could not provide a clean upgrade path for users who have stored documents with the old algorithms state since there would likely not be a way to transform the old algorithms state into the state needed for the new algorithm. This would mean that not only would we not be able to upgrade the state stored in the documents to the new algorithm (with a reindex) but we also could not perform aggregations which span the boundary between between documents containing the old and new algorithm's state. This would mean that we would cause a very hard break in the cardinality aggregation for users when we did improve the algorithm and we would be very restricted in when we could modify the underlying algorithm (since it would such a hard break) meaning that we could not iterate and improve the cardinality aggregation.

Since these algorithms by design lose information about the original values and since different algorithms lose this information in different ways and retain different aspects of the original values it's hard to see a way of making the state agnostic of the algorithm.

It would be great if we could find a way around these challenges so we are open to suggestions. In the mean time you could choose to implement a custom aggregation which loads the cardinality state from a field in a document and merges them together to obtain a final cardinality.

**Comment by nirmalc** [comment] 2017-07-18 20:34
@ncolomer we wrote a simple es plugin for aggregating hll serialized objects - in case you are interested: https://github.com/bazaarvoice/elasticsearch-hyperloglog ( may need to modify precision etc )  it uses stream-lib

**Comment by apocarteres** [comment] 2017-11-16 06:43
@ncolomer thanks a lot. I faced the same issue in my project and found your plugin useful!

**Comment by polyfractal** [comment] 2018-03-22 16:11
@elastic/es-search-aggs

**Comment by polyfractal** [comment] 2018-10-19 13:58
Related to #33214

**Comment by gibrown** [comment] 2020-04-29 20:49
I'm not sure if this helps or not, but another possible improvement here could be to move to a different cardinality algorithm such as [Theta Sketch](https://datasketches.apache.org/docs/Theta/ThetaSketchFramework.html).

If I understand correctly this could allow storing samples of the data which can then be combined do rollup into various answers. We are starting to speed up unique user counts on data we have in HDFS this way.

**Comment by wchaparro** [comment] 2024-02-15 21:03
closing as not planned.

**Closed by wchaparro** 2024-02-15 21:03 UTC
Labels: >feature, high hanging fruit, :Analytics/Aggregations, Team:Analytics
