### ISSUE TITLE
Composite aggs `terms` value source should allow `include` and `exclude`

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#76952] opened 2021-08-25 20:00 UTC
The `terms` value source in composite aggs does not support `include` or `exclude`. 

Since `composite` aggregation has many optimizations when there is no query present, it would be nice to keep optimizations while reducing the term set bucketed. 

Additionally, it affords a nice API for crafting scrolling buckets when only a subset of terms is desired.

**Comment by not-napoleon** [comment] 2021-12-13 16:50
I'm closing this as a duplicate of https://github.com/elastic/elasticsearch/issues/50368.

**Closed by not-napoleon** 2021-12-13 16:50 UTC
Labels: >enhancement, Team:Analytics, :Analytics/CompositeAggs
