### ISSUE TITLE
How to install license shield

### ISSUE THREAD

**Issue by tommoholmes10** [elastic/elasticsearch#12928] opened 2015-08-17 10:17 UTC
I want to update my shield because time it's expiry
when I run 
``
curl -XPUT -u admin 'http://localhost:9200/_licenses' -d @license.json
``
I have message like this
``{"error":"ElasticsearchParseException[Failed to derive xcontent from (offset=0, length=0): []]","status":400}``

**Comment by markwalkom** [comment] 2015-08-17 10:19
You should really chat to the Elastic support team about this, because assistance for installing licensed plugins is covered with your subscription :)

**Comment by tommoholmes10** [comment] 2015-08-17 10:25
Okee thanks

**Comment by markwalkom** [comment] 2015-08-17 10:31
I've asked someone from the Shield team to drop in, however I would encourage you to contact the Support team ASAP to get this resolved, especially if your license is expired.

**Comment by jaymode** [comment] 2015-08-17 10:51
@tommoholmes10 is your license file empty? I was able to reproduce the exception you got with an empty license file, which is to be expected.

**Comment by markwalkom** [comment] 2015-08-17 11:47
It looks like you have also raised this on our forums - https://discuss.elastic.co/t/license-shield/27493/3

I'll close this as Github is for bugs or feature requests, not support.

**Closed by markwalkom** 2015-08-17 11:47 UTC
