### ISSUE TITLE
elasticsearch-rest-high-level-client 6.7.2 packages seem to be missing

### ISSUE THREAD

**Issue by jleskovar-tyro** [elastic/elasticsearch#44393] opened 2019-07-16 01:53 UTC
**Version: 6.7.2 (elasticsearch-rest-high-level-client dependency):** 

**Description of the problem including expected versus actual behavior**:
When using version 6.7.2 of the elasticsearch-rest-high-level-client dependency, there are a lot of missing types and references, specifically classes in the org.elasticsearch.action package. Downgrading to 6.7.1 resolves the issue.

**Steps to reproduce**:

 1. Setup a maven project with the following dependency
```        
<dependency>
        <groupId>org.elasticsearch.client</groupId>
        <artifactId>elasticsearch-rest-high-level-client</artifactId>
        <version>6.7.2</version>
</dependency>
```
 2. Try and compile the following:
```
import org.apache.http.HttpHost;
import org.elasticsearch.action.index.IndexRequest;
import org.elasticsearch.client.RestClient;
import org.elasticsearch.client.RestHighLevelClient;

import java.io.IOException;

public class Main {
    public static void main(String[] args) throws IOException {
        RestHighLevelClient client = new RestHighLevelClient(RestClient.builder(HttpHost.create("localhost:9200")));
        client.index(new IndexRequest("some-index", "_doc", "some-id"));
    }
}
```
 3. On version 6.7.2, the above does not compile (will complain "IndexRequest" is missing). On 6.7.1, the code does compile.

**Comment by jbaiera** [comment] 2019-08-06 15:51
I was able to create a new Maven (as well as Gradle) project using the above dependency and test code. The classes resolved just fine for me. I also checked for any differences in the pom files and only found that the only changes were version numbers.

Do note: The action objects are a part of the `elasticsearch` jar, which is a dependency of the HLRC (from the pom.xml):

```xml
<dependency>
  <groupId>org.elasticsearch</groupId>
  <artifactId>elasticsearch</artifactId>
  <version>6.7.2</version>
  <scope>compile</scope>
</dependency>
```

Maven downloads this just fine for me as a transitive dependency. I would double check that you are able to reach the jar (https://repo1.maven.org/maven2/org/elasticsearch/elasticsearch/6.7.2/) from Maven, as well as any dependency management configurations. It's possible that you might have some sort of configuration that is keeping it from pulling the artifact.

Since this didn't reproduce for me, I'm going to go ahead and close this out - but if you find some additional information that might help us successfully reproduce it, please share it here and we can re-open this to get things fixed!

**Closed by jbaiera** 2019-08-06 15:51 UTC
Labels: :Core/Features/Java High Level REST Client, team-discuss
