### ISSUE TITLE
CI Failures: jarHell failed to run on Windows

### ISSUE THREAD

**Issue by nknize** [elastic/elasticsearch#47953] opened 2019-10-11 20:04 UTC
This jarHell failure has cropped up a few times in the last couple days on master and 7.4 branches. 

https://groups.google.com/a/elastic.co/forum/#!searchin/build-elasticsearch/jarHell%7Csort:date

All with the same failure: 

```
14:41:02 > Task :x-pack:plugin:ml:jarHell FAILED
14:41:02 Exec output and error:
14:41:02 | Output for C:\Users\jenkins\.java\openjdk12\bin\java.exe:
14:41:02 
14:41:02 > Task :x-pack:plugin:security:testingConventions
14:41:02 
14:41:02 FAILURE: Build failed with an exception.
14:41:02 
14:41:02 * What went wrong:
14:41:02 Execution failed for task ':x-pack:plugin:ml:jarHell'.
14:41:02 > A problem occurred starting process 'command 'C:\Users\jenkins\.java\openjdk12\bin\java.exe
```

**Comment by droberts195** [comment] 2019-10-11 20:25
`A problem occurred starting process 'command 'C:\Users\jenkins\.java\openjdk12\bin\java.exe` is the cause here. The fact it was trying to do a check on some ML source at the time is a fluke.

The worker had 32 CPUs. Does that mean it was doing 32 checks in parallel, each in a separate JVM? Certainly there are lots of very similar timestamps on the check task that are listed in the console log.

Maybe on Windows the parallelism needs scaling back a little or the workers need more memory on Windows?

**Comment by atorok** [comment] 2019-10-15 13:03
Here's a scan: https://gradle-enterprise.elastic.co/s/4dnt4bscjqldo 
The root  cause: 
```
Caused by: java.io.IOException: CreateProcess error=206, The filename or extension is too long
```

**Comment by droberts195** [comment] 2019-10-15 13:36
The associated stack trace might also be useful because it shows which component doesn't like long path names - it's `net.rubygrapefruit.platform.internal.DefaultProcessLauncher`:

```
at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
at net.rubygrapefruit.platform.internal.WindowsProcessLauncher.start(WindowsProcessLauncher.java:22)
at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
at org.gradle.process.internal.ExecHandleRunner.startProcess(ExecHandleRunner.java:98)
at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:71)
at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
```

**Comment by droberts195** [comment] 2019-10-15 13:46
A similar problem was worked around in the Elasticsearch code by getting the short (8.3) path before passing it to the `ProcessBuilder` - see #25344.

**Comment by atorok** [comment] 2019-10-15 13:57
I think the error is a bit misleading, as the path is rather short here `C:\Users\jenkins\.java\openjdk12\bin\java.exe`. 
I think it's the command line length that gets exceeded because the classpath is too long.
We could pass it as as the `CLASSPATH` env var instead, but looking at some issues Gradle should already be doing it ...

**Comment by mark-vieira** [comment] 2019-10-15 23:08
> I think it's the command line length that gets exceeded because the classpath is too long.

I believe you are correct:

```
Cannot run program "C:\Users\jenkins\.java\openjdk12\bin\java.exe" (in directory "C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2012-r2\x-pack\plugin\ml"): CreateProcess error=206, The filename or extension is too long
```

> We could pass it as as the CLASSPATH env var instead, but looking at some issues Gradle should already be doing it ...

I don't think using `CLASSPATH` is a long-term solution:

> All environment variables must live together in a single environment block, which itself has a limit of 32767 characters.

That said, this might be good enough for now, as I believe the current command line limit is 8k characters so perhaps that will solve the problem temporarily until Gradle 6.0 which has a [permanent fix for this](https://docs.gradle.org/release-nightly/release-notes.html#usability-improvements).

**Comment by mark-vieira** [comment] 2019-10-15 23:11
> Gradle should already be doing it ...

For clarification, Gradle does not already do this. The only scenario in which Gradle circumvents OS command line length limits is for worker processes (like test workers, or the worker API using process isolation) where the classpath is passed via `stdin`.

**Closed** 2019-10-22 08:16 UTC
Labels: :Core/Infra/Build, >test-failure, v7.4.1, v8.0.0
