### ISSUE TITLE
testRandomDateFormatterPattern fails with java.lang.IllegalArgumentException: temporal accessor

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#61496] opened 2020-08-24 17:47 UTC
**Build scan**:
https://gradle-enterprise.elastic.co/s/2fzd2ou3ctvjs
**Repro line**:
```
./gradlew ':test:framework:test' --tests "org.elasticsearch.test.test.ESTestCaseTests.testRandomDateFormatterPattern" -Dtests.seed=CBBABE1AD795407C -Dtests.security.manager=true -Dtests.locale=pt-BR -Dtests.timezone=Pacific/Guadalcanal -Druntime.java=8
```
**Reproduces locally?**:
Yes
**Applicable branches**:
7.x
**Failure excerpt**:
```
org.elasticsearch.test.test.ESTestCaseTests > testRandomDateFormatterPattern FAILED
    java.lang.IllegalArgumentException: temporal accessor [{WeekOfWeekBasedYear[WeekFields[MONDAY,4]]=41, WeekBasedYear[WeekFields[MONDAY,4]]=2003},ISO] cannot be converted to zoned date time
        at __randomizedtesting.SeedInfo.seed([CBBABE1AD795407C:C6D3E02039259987]:0)
        at org.elasticsearch.common.time.DateFormatters.from(DateFormatters.java:1905)
        at org.elasticsearch.common.time.DateFormatters.from(DateFormatters.java:1858)
        at org.elasticsearch.common.time.DateFormatter.parseMillis(DateFormatter.java:51)
        at org.elasticsearch.test.test.ESTestCaseTests.testRandomDateFormatterPattern(ESTestCaseTests.java:217)
```

**Comment by benwtrent** [comment] 2020-08-24 17:52
Tagging search as I am unsure what other team should get pinged :)

**Comment by cbuescher** [comment] 2020-09-15 17:08
Narrowing this down a bit. This reproduces for me on 7.x but not on master. Also if I leave out the runtime Java version `-Druntime.java=8` or change it to anything highter the test passes.
The randomization picks a "strict_weekyear_week" formatter and formats a random long date trough which for this seed gives "2003-W41". This doesn't get parsed well back with `parseMillis` by the same formatter, so roundtripping doesn't work. Reduced to one line:
```
DateFormatter.forPattern("strict_weekyear_week").parseMillis("2003-W41");
```
fails for `-Druntime.java=8` (which for me locally is Oracle jdk1.8.0_201.jdk) but passes for higher versions (e.g. 9, Oracle jdk-9.0.4.jdk)

**Comment by cbuescher** [comment] 2020-09-15 17:47
Using 8, DateFormatter#from(TemporalAccessor accessor, Locale locale, ZoneId defaultZone) falls through for the above, while higher jdk versions return from the `else if (accessor.isSupported(WeekFields.of(locale).weekBasedYear()))` condition.
Other formatters that exhibit similar quirks with 8 are "strict_weekyear_week", "strict_weekyear", "weekyear_week" and "week_year".

**Comment by cbuescher** [comment] 2020-10-05 15:45
> ' DateFormatter.forPattern("strict_weekyear_week").parseMillis("2003-W41");'

This is not only a test issue, I started current 7.x branch locally with java 8 (Oracle 1.8.0_201), and the following
snippet does not work, whereas with a Java 9 version everthing works fine.

```
PUT /datetest
{
  "mappings": {
    "properties": {
      "datefield" : {
        "type": "date",
        "format": "strict_weekyear_week"
      }
    }
  }
}

PUT /datetest/_doc/1
{
  "datefield" : "2003-W41"
}
```
Getting the following error on 8:
```
 "type" : "illegal_argument_exception",
      "reason" : "temporal accessor [{WeekBasedYear[WeekFields[MONDAY,4]]=2003, WeekOfWeekBasedYear[WeekFields[MONDAY,4]]=41},ISO] cannot be converted to zoned date time"
```

I will go ahead and file a regular issue for this, then we can maybe simplify the test by excluding the problematic formats for the time being (at least on 7.x branch, this is no issue on master etc... since we don't allow using Java 8 there anymore).

**Comment by pgomulka** [comment] 2020-10-06 14:42
the problem is indeed with JDK 8. 
JDK defaults start of the week to Sunday and expects 1 day in the first week of the year. That means that 
We use SPI to load custom `IsoCalendarDataProvider` which allows use to override start of the week and minimum of years in first week of year.
It is easy with jdk9+ as we only need to put it on a classpath. To make it work with jdk8 we would have to place it in jre/ext/lib - we don't expect users to do this.

So when running DateFormatters.from method in this line https://github.com/elastic/elasticsearch/blob/7.x/server/src/main/java/org/elasticsearch/common/time/DateFormatters.java#L1898
we have an accessor ` [{WeekBasedYear[WeekFields[MONDAY,4]]=2003, WeekOfWeekBasedYear[WeekFields[MONDAY,4]]=41},ISO] `
but it checks if `isSupported(WeekBasedYear[WeekFields[Sunday,1]]` and it returns false.

in jdk9+ this would test against `isSupported(WeekBasedYear[WeekFields[MONDAY,4]]` and would return true.

It is documented in 6.8 as a known issue, we made a comment about this in code here 
https://github.com/elastic/elasticsearch/blob/7.x/server/src/main/java/org/elasticsearch/common/time/DateFormatters.java#L58
but the problem for jdk8 will persist in 7.x
For other tests we make an assumption it has to be run with at least JDK8 
maybe we do the same here?
https://github.com/elastic/elasticsearch/blob/7.x/server/src/test/java/org/elasticsearch/common/joda/JavaJodaTimeDuellingTests.java#L58

**Comment by cbuescher** [comment] 2020-10-06 14:49
> For other tests we make an assumption it has to be run with at least JDK8
> maybe we do the same here?
> https://github.com/elastic/elasticsearch/blob/7.x/server/src/test/java/org/elasticsearch/common/joda/JavaJodaTimeDuellingTests.java#L58

I'm happy to do that for the test in question. I was concerned that this is a real issue for anybody running 7.x versions with JDK 8, but since this seems to be a rare format and combination and its going away with 8.0 anyway it might not be worth fixing. Would you think this is rather a documentation / known issue case then? I can open a follow up to document this better.

**Comment by pgomulka** [comment] 2020-10-06 14:49
I will try to investigate if any fix is possible and will add a known issue if nothing helps

**Comment by pgomulka** [comment] 2020-10-14 05:29
closed by  https://github.com/elastic/elasticsearch/pull/63626

**Closed by pgomulka** 2020-10-14 05:29 UTC
Labels: :Search/Search, >test-failure, Team:Search
