### ISSUE TITLE
[CI] UpgradeClusterClientYamlTestSuiteIT test {p0=mixed_cluster/90_ml_data_frame_analytics_crud/Get old regression job} failing

### ISSUE THREAD

**Issue by gmarouli** [elastic/elasticsearch#96520] opened 2023-06-02 09:54 UTC
Multiple failures in this test suite all failed while waiting for watcher to initialise 3 watcher nodes.

**Build scan:**
https://gradle-enterprise.elastic.co/s/iaoaohhd264rg/tests/:x-pack:qa:rolling-upgrade:v8.8.1%23oneThirdUpgradedTest/org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT/test%20%7Bp0=mixed_cluster%2F90_ml_data_frame_analytics_crud%2FGet%20old%20regression%20job%7D

**Reproduction line:**
```
./gradlew ':x-pack:qa:rolling-upgrade:v8.8.1#oneThirdUpgradedTest' -Dtests.class="org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=mixed_cluster/90_ml_data_frame_analytics_crud/Get old regression job}" -Dtests.seed=84DE804D33DB72A9 -Dtests.bwc=true -Dtests.locale=de-DE -Dtests.timezone=Etc/Universal -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT&tests.test=test%20%7Bp0%3Dmixed_cluster/90_ml_data_frame_analytics_crud/Get%20old%20regression%20job%7D

**Failure excerpt:**
```
java.lang.AssertionError: Failure in test setup: Failed to initialize at least 3 watcher nodes

  at __randomizedtesting.SeedInfo.seed([84DE804D33DB72A9:C8ABF979D271F51]:0)
  at org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT.waitForWatcher(UpgradeClusterClientYamlTestSuiteIT.java:74)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:980)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

  Caused by: java.lang.AssertionError: 
  Expected: a value equal to or greater than <3>
       but: <2> was less than <3>

    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
    at org.junit.Assert.assertThat(Assert.java:956)
    at org.junit.Assert.assertThat(Assert.java:923)
    at org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT.lambda$waitForWatcher$0(UpgradeClusterClientYamlTestSuiteIT.java:67)
    at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1171)
    at org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT.waitForWatcher(UpgradeClusterClientYamlTestSuiteIT.java:63)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke(Method.java:578)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:980)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
    at java.lang.Thread.run(Thread.java:1623)

```

**Comment by masseyke** [comment] 2023-06-09 19:16
I can't reproduce this (because I keep hitting another problem before I get to this one). But I see that one of the 3 nodes in the log here did not actually come up. It crashed on a call to `_xpack/usage`:
```
» [2023-06-02T09:23:04,241][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [v8.8.1-0] fatal error in thread [elasticsearch[v8.8.1-0][management][T#2]], exiting java.lang.AssertionError: java.lang.IllegalStateException: Message not fully read (response) for requestId [883], handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/UnregisterChildTransportResponseHandler[unregisterChildNode=releaseOnce[org.elasticsearch.tasks.TaskManager$$Lambda$7484/0x00000008021d88a0@21ba9662], handler=org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$1@22bf26ab/org.elasticsearch.action.ActionListenerImplementations$DelegatingFailureActionListener/org.elasticsearch.action.support.ContextPreservingActionListener/org.elasticsearch.tasks.TaskManager$1{SafelyWrappedActionListener[listener=org.elasticsearch.rest.action.RestCancellableNodeClient$1@3a3cecc4]}{Task{id=1514, type='transport', action='cluster:monitor/xpack/usage', description='', parentTask=unset, startTime=1685697783956, startTimeNanos=1264315751396}}/org.elasticsearch.xpack.security.action.filter.SecurityActionFilter$$Lambda$6958/0x0000000802129b00@48e2e108, action=cluster:monitor/xpack/usage, childRequest=org.elasticsearch.protocol.xpack.XPackUsageRequest/fLad6cT0Tn63VV19nai5mg:1514, childConnection=NodeChannels[{v8.8.1-2}{By71ji1lRyeSmd3211kXzA}{TPVB7f1mSNSBoDH8mfLGHQ}{v8.8.1-2}{127.0.0.1}{127.0.0.1:34759}{cdfhilmrstw}{8.8.1}], taskManager=org.elasticsearch.tasks.TaskManager@56a3bd7a]], error [false]; resetting
»  	at org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.transport.InboundHandler.verifyResponseReadFully(InboundHandler.java:190)
»  	at org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.transport.InboundHandler.doHandleResponse(InboundHandler.java:418)
»  	at org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.transport.InboundHandler$2.doRun(InboundHandler.java:376)
»  	at org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)
»  	at org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
»  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
»  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
»  	at java.base/java.lang.Thread.run(Thread.java:1623)
»  Caused by: java.lang.IllegalStateException: Message not fully read (response) for requestId [883], handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/UnregisterChildTransportResponseHandler[unregisterChildNode=releaseOnce[org.elasticsearch.tasks.TaskManager$$Lambda$7484/0x00000008021d88a0@21ba9662], handler=org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$1@22bf26ab/org.elasticsearch.action.ActionListenerImplementations$DelegatingFailureActionListener/org.elasticsearch.action.support.ContextPreservingActionListener/org.elasticsearch.tasks.TaskManager$1{SafelyWrappedActionListener[listener=org.elasticsearch.rest.action.RestCancellableNodeClient$1@3a3cecc4]}{Task{id=1514, type='transport', action='cluster:monitor/xpack/usage', description='', parentTask=unset, startTime=1685697783956, startTimeNanos=1264315751396}}/org.elasticsearch.xpack.security.action.filter.SecurityActionFilter$$Lambda$6958/0x0000000802129b00@48e2e108, action=cluster:monitor/xpack/usage, childRequest=org.elasticsearch.protocol.xpack.XPackUsageRequest/fLad6cT0Tn63VV19nai5mg:1514, childConnection=NodeChannels[{v8.8.1-2}{By71ji1lRyeSmd3211kXzA}{TPVB7f1mSNSBoDH8mfLGHQ}{v8.8.1-2}{127.0.0.1}{127.0.0.1:34759}{cdfhilmrstw}{8.8.1}], taskManager=org.elasticsearch.tasks.TaskManager@56a3bd7a]], error [false]; resetting
»  	at org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.transport.InboundHandler.verifyResponseReadFully(InboundHandler.java:187)
»  	... 7 more
»  
»  
»  ERROR: Elasticsearch exited unexpectedly
```
I can't find the exact failure, but I'm guessing that this is due to #96177, and very similar to #96687 and #96574 in that we didn't handle DLM correctly if the feature is off or not in the version.

**Comment by masseyke** [comment] 2023-06-09 20:46
It looks like when we run this test the DLM feature flag is enabled. It started failing when we merged #96177 because at that point the output of `_xpack/usage` from newer nodes became unreadable by older nodes. I think this will be fixed by the work @andreidan is doing in #96687.

**Comment by andreidan** [comment] 2023-06-12 11:17
@masseyke I don't think https://github.com/elastic/elasticsearch/issues/96687 is related (that's enabling unit tests in `8.8`) 

This was probably fixed by https://github.com/elastic/elasticsearch/pull/96518

**Closed by andreidan** 2023-06-12 11:17 UTC
Labels: >test-failure, :Data Management/Watcher, Team:Data Management

**Comment by masseyke** [comment] 2023-06-12 19:08
Makes sense -- I didn't realize that there'd coincidentally been other activity in _xpack/usage at the same time!
