### ISSUE TITLE
Check mapping compatibility ignored when upgrading

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#13345] opened 2015-09-04 13:09 UTC
A 2.0 node starts even though there is a conflicting mapping.

Steps to reproduce:
1. Start a 1.7.1 node
2. Add an index with field type conflict and add a few documents:

```
PUT /test
{
  "mappings": {
    "parent": {},
    "child": {
      "_parent": {
        "type": "parent",
        "fielddata": {
          "loading": "eager_global_ordinals"
        }
      }
    }
  }
}

PUT /test/parent/1
{}

PUT /test/child/1?parent=1
{}
``` 

3. Stop the 1.7.1 node
4. Start a 2.0.0-beta2-SNAPSHOT node
5. Two things can happen. 

a) It fails with an error that I can't update like this:

```
Exception in thread "main" java.lang.IllegalStateException: unable to upgrade the mappings for the index [test], reason: [Mapper for [_parent] conflicts with existing mapping in other types:
[mapper [_parent] is used by multiple types. Set update_all_types to true to update [fielddata] across all types.]]
Likely root cause: java.lang.IllegalArgumentException: Mapper for [_parent] conflicts with existing mapping in other types:
[mapper [_parent] is used by multiple types. Set update_all_types to true to update [fielddata] across all types.]
	at org.elasticsearch.index.mapper.FieldTypeLookup.checkCompatibility(FieldTypeLookup.java:117)
	at org.elasticsearch.index.mapper.MapperService.checkNewMappersCompatibility(MapperService.java:345)
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:296)
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:242)
	at org.elasticsearch.cluster.metadata.MetaDataIndexUpgradeService.checkMappingsCompatibility(MetaDataIndexUpgradeService.java:331)
	at org.elasticsearch.cluster.metadata.MetaDataIndexUpgradeService.upgradeIndexMetaData(MetaDataIndexUpgradeService.java:113)
	at org.elasticsearch.gateway.GatewayMetaState.pre20Upgrade(GatewayMetaState.java:226)
	at org.elasticsearch.gateway.GatewayMetaState.<init>(GatewayMetaState.java:85)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at <<<guice>>>
	at org.elasticsearch.node.Node.<init>(Node.java:198)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:157)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:168)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:267)
```

b) The node starts with a conflicting mapping

6. If it fails to start then try to start start it a few more times and eventually the node will start even though a conflicting mapping is active.

The 2.0.0-beta2 node should never start with a conflicting mapping. I don't know yet what is causing this.

**Comment by imotov** [comment] 2015-09-04 14:49
This is tricky one. In order to check the correctness of the mapping MetaDataIndexUpgradeService [loads and applies one type](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java#L329) at a time and checks it for conflicts with already loaded mappings. If it loads the parent first and then the child, it gets Mapper conflict exception as expected and fails to start the node. However, if it loads the child first and then parent, no exception is thrown and index gets successfully loaded and marked as upgraded to 2.0.0. The problem is that types are stored in map and their order is unpredictable and can change on over load. So, if somebody starts the node enough times, it will eventually get the child type before the parent type and upgrade the index. 

It's possible to simulate the issue by running the following script on 2.0.0-beta1, which recreates the conflicting mapping within 2.0.0-beta1.

```
curl -XDELETE "localhost:9200/test?pretty"
curl -XPUT "localhost:9200/test?pretty"
curl -XPUT "localhost:9200/test/child/_mapping?pretty" -d '{
	"child": {
		"_parent": {
			"type": "parent",
			"fielddata": {
				"loading": "eager_global_ordinals"
			}
		}
	}
}'
curl -XPUT "localhost:9200/test/parent/_mapping?pretty" -d '{
	"parent": {}
}'
curl -XGET "localhost:9200/test/_mapping?pretty"
```

If you try to put this mapping as a whole into 2.0.0 it fails:

```
curl -XDELETE "localhost:9200/test2?pretty"
curl -XPUT "localhost:9200/test2?pretty" -d '{
	"mappings": {
		"parent": {},
		"child": {
			"_parent": {
				"type": "parent",
				"fielddata": {
					"loading": "eager_global_ordinals"
				}
			}
		}
	}
}'
```

We discussed it with @martijnvg and he suggested that it's a version of #13169. We might also want to look into making the mapping upgrade procedure more consistent. Maybe apply mappings in alphabetical order?

**Comment by imotov** [comment] 2015-09-04 19:02
After some research, it looks like applying types in alphabetical order will not really help us that much. If we could figure out initial type creation order we could have followed it every time we validate the mapping. But since this order is not preserved, there is little value in enforcing a completely different order later on. It looks like the only way to prevent the issue above is to make sure that mapper works the same way independently of the order of merged types. So, unless somebody has some better ideas I am going to close this issue.

**Comment by clintongormley** [comment] 2015-09-06 13:33
@imotov agreed.  I think this is only an issue for the `_parent` field, which should be dealt with in #13169

**Closed by clintongormley** 2015-09-06 13:33 UTC
Labels: :Upgrade API, blocker, bug
