### ISSUE TITLE
The addition assignment operator seems to be broken in Painless scripts

### ISSUE THREAD

**Issue by munkrig** [elastic/elasticsearch#22790] opened 2017-01-25 15:40 UTC
**Elasticsearch version**: 5.1.2

**Plugins installed**: []

**JVM version**: 1.8.0_111

**OS version**: I am using the latest official Docker image (`elasticsearch:5.1.2`) on CoreOS 1235.6.0

**Description of the problem including expected versus actual behavior**:
When I perform a script update via the `_update` endpoint it seems that the addition assignment operator (`+=`) will downcast double values to integers, thus dropping the decimal places.

For example, applying the simple script `ctx._source.value += 1.5` to an initial document `{ value : 0 }` will yield a result of `{ value : 1 }` instead of `{ value : 1.5 }`. This only happens when the object has been initialized with an integer value. If the object has been initialized with a double value, the operator works as expected.

Using the assignment operator in conjunction with the addition operator (`ctx._source.value = ctx._source.value + 1.5`), always produces correct results, irrespective of whether the initial value was an integer or a double. In Groovy scripts the `+=` operator works as expected, as far as I can tell.

**Steps to reproduce**:
You can reproduce the described behavior by issuing the following commands in Kibana Sense/Console:

Prepare the scenario:
```
PUT foo
PUT foo/bar/_mapping
{
  "properties": {
    "value": {
      "type": "double"
    }
  }
}
PUT foo/bar/1
{
  "value": 0
}
```

This script produces incorrect results:
```
POST foo/bar/1/_update
{
  "script": {
    "lang": "painless", 
    "inline": "ctx._source.value += 1.5"
  },
  "_source":true
}
```

This script works as expected:

```
POST foo/bar/1/_update
{
  "script": {
    "lang": "painless", 
    "inline": "ctx._source.value = ctx._source.value + 1.5"
  },
  "_source":true
}
```

**Comment by jdconrad** [comment] 2017-01-25 16:52
I will take a look into this.  At the very least I would assume that the behavior for x += y should result in the same answer as x = x + y.

**Comment by jdconrad** [comment] 2017-01-25 17:34
So my previous assumption was actually incorrect and what is happening is indeed the expected behavior in Painless.

Take the case where you have the following:

``` int x = 5; x += 5.0; ```

This results in an int value of 10.  We decided to make the behavior of the def type be consistent with the behavior of the other compound assignment types meaning that for numeric values, the result will be cast to the original numeric type.  However, given the original type is actually def it's possible the expected behavior should be as described in the original comment.  I'll need to give this some more though.

In the meantime, this definitely needs to be better documented and that's something we're currently working on right now.

**Comment by jdconrad** [comment] 2017-01-25 18:21
I'm strongly leaning towards leaving the existing behavior.  Take a look at the following examples:

``` short x = 1; x = (short)(x + 1); ```
versus
``` short x = 1; x += 1; ```

With compound assignment the user has no ability to create a cast that would make that second statement valid without the cast being implicit.  This same logic applies to def.  The user would have no ability to cast to the type he/she wants the def type to end up as during a compound assignment so it's logical to not change the type implicitly on the fly with upcasting.

@nik9000 Any thoughts on this?

**Comment by munkrig** [comment] 2017-01-26 09:45
After considering your argument and checking how Java handles these cases, I tend to agree with you. Retaining the current behavior might indeed be the better alternative.

The only thing I would like to add is that I had explicitly declared my variable as a double in the type mapping. It seems that painless does not take the mapping into account during type inference. Instead it sees the initial value of `0` and deduces that the variable must be an integer. As an end user that seems a little strange to me.

**Comment by nik9000** [comment] 2017-01-26 14:30
> It seems that painless does not take the mapping into account during type inference. Instead it sees the initial value of 0 and deduces that the variable must be an integer. As an end user that seems a little strange to me.

Yeah! We've talked about a few times. The reason it works the way it does is that Elasticsearch's scripting APIs were designed around MVEL and Groovy, neither of which could do anything with the type information. We're (slowly, carefully) in the process of reworking the scripting APIs so we can send more interesting information to Painless.

**Comment by jdconrad** [comment] 2017-01-26 17:12
I definitely understand the frustration around not being able to take into account mappings.  To add a bit more explanation to what Nik has already said -- we compile scripts in a way that allow them to run across all indexes, unfortunately this means we can't assume a mapping for a specific index at compile time since fields with the same name could actually be different types in different indexes, so we do the best we can with the information we do have, in this case 0 for int.  As Nik mentioned, this is something we are working on longer term to hopefully make things a bit more user friendly.

**Comment by munkrig** [comment] 2017-01-26 17:58
Thanks for the explanation!

As far as I’m concerned, the issue can be closed then. Assignments of the kind `x = x + 1.5` work even if the initial value was an integer and can easily be used in place of `x += 1.5`.

It might make sense to document the behavior though, as it may save other developers some head-scratching.

**Comment by jdconrad** [comment] 2017-01-26 18:00
@munkrig You're very welcome for the explanation, and I agree 100% with this needing to be documented.  Documentation is something we're in process of making large improvements too.
Closing now.

**Closed by jdconrad** 2017-01-26 18:00 UTC
Labels: :Plugin Lang Painless, v6.0.0
