### ISSUE TITLE
getting "authentication required" after >docker pull docker.elastic.co/elasticsearch/elasticsearch:7.5.2

### ISSUE THREAD

**Issue by achang77** [elastic/elasticsearch#53060] opened 2020-03-03 15:43 UTC
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):elasticsearch:7.5.2

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):macos 10.15.3

**Description of the problem including expected versus actual behavior**:
docker pull returning authentication required
**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. run docker pull docker.elastic.co/elasticsearch/elasticsearch:7.5.2
 2.
 3.

**Provide logs (if relevant)**:
Error response from daemon: Get https://docker.elastic.co/v2/: EOF

**Comment by matriv** [comment] 2020-03-11 10:42
Thank you very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/) and it seems that you have
already opened an [issue](https://discuss.elastic.co/t/docker-pull-docker-elastic-co-elasticsearch-elasticsearch-7-5-2-getting-authentication-required/221918) there. 

I couldn't reproduce and it seems more likely that the issue is in your end (maybe a firewall/proxy), but I'd like to ask to followup in the discuss forums and I hope you don't mind that I close this.

**Closed by matriv** 2020-03-11 10:42 UTC
