### ISSUE TITLE
Accessing _id field in plugin leads to gibberish

### ISSUE THREAD

**Issue by cjmcgraw** [elastic/elasticsearch#63504] opened 2020-10-08 16:57 UTC
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 7.9.0, Build: default/docker/a479a2a7fce0389512d6a9361301708b92dff667/2020-08-11T21:36:48.204330Z, JVM: 14.0.1

**Plugins installed**: [custom]

**JVM version** (`java -version`): 
openjdk 14.0.1 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.1+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.1+7, mixed mode, sharing)

**OS version** (`uname -a` if on a Unix-like system): 
Linux 1ed57b24faa6 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
Unexpected outcome when attempting to deserialize _id field

**Steps to reproduce**:
Internal to ES in a rescore plugin do the following:

```java
 public TopDocs rescore(TopDocs topDocs, IndexSearcher searcher, RescoreContext rescoreContext) throws IOException {
    ScoreDoc scoreDoc = topDocs.scoreDocs[0];
    Document doc = searcher.doc(scoreDoc.doc);
    log.info("_id = " + doc.getField("_id").binaryValue().utf8ToString());
    return topDocs
}
```

Watching the log we get unexpected id values, that do not match up with _id values from ES:

```
_id = ??i
```

Either this isn't working as intended, or there is an issue with mapping es _id's to lucene documents.

**Comment by cbuescher** [comment] 2020-10-12 11:02
@cjmcgraw thanks for opening the issue, this is working as intended but you might need an additional decoding step for the "_id" field.
We internally seem to encode the raw id value again using the `Uid` helper class in https://github.com/elastic/elasticsearch/blob/7.9/server/src/main/java/org/elasticsearch/index/mapper/IdFieldMapper.java#L289. That means when getting back the binary value from the IndexableField you need to decode it back using something similar to https://github.com/elastic/elasticsearch/blob/7.9/server/src/main/java/org/elasticsearch/index/mapper/IdFieldMapper.java#L255. I think the exact code might differ since you get a BytesRef with `binaryValue()` but that should contain the original bytes array, offset and length. I didn't try this out yet but hope this helps. 
I'm going to close this issue as it is more a usage question than an enhancement request or bug report. Please consider using our support forums over at https://discuss.elastic.co in the future since we prefer to use Github issues only for bug reports and feature requests. Let me know if you have more questions and we should continue the discussion there.

**Closed by cbuescher** 2020-10-12 11:02 UTC
Labels: >bug, needs:triage

**Comment by cjmcgraw** [comment] 2020-10-17 00:30
@cbuescher I will investigate this and get back to you. I was imagining it was more operator error than anything. Thanks for the information!
