### ISSUE TITLE
Long type does not work for TermsAggregation

### ISSUE THREAD

**Issue by jdcohen220** [elastic/elasticsearch#52262] opened 2020-02-12 13:55 UTC
**Elasticsearch version** (`bin/elasticsearch --version`):
`7.5.1`
**Plugins installed**: []
`analysis_phonetic`
**JVM version** (`java -version`):
```
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
```
**OS version** (`uname -a` if on a Unix-like system):
```
Linux ip-172-31-31-196 4.15.0-1032-aws #34-Ubuntu SMP Thu Jan 17 15:18:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Description of the problem including expected versus actual behavior**:
Bucket aggregations, such as the `TermsAggregation` do not work with `long` datatypes. The buckets do not return in the aggregations section. The same exact query/aggregation works correctly if using the keyword datatype. The docs for this aggregation make no mention of this restriction.
**Steps to reproduce**:

**Using the long datatype:**

```
PUT long_bucketing_index
{
  "mappings": {
    "dynamic": "strict",
    "properties": {
      "id": {
        "type": "keyword"
      },
      "category_id": {
        "type": "long"
      }
    }
  }
}

POST long_bucketing_index/_doc
{
  "id": 1,
  "category_id": 1353143788557567278
}

POST long_bucketing_index/_doc
{
  "id": 2,
  "category_id": 1353143788557567278
}

POST long_bucketing_index/_doc
{
  "id": 3,
  "category_id": 135314378855756999
}

//the query

POST long_bucketing_index/_search?
{
  "query": {
    "match_all": {}
  },
  "aggs": {
    "category": {
      "terms": {
        "field": "category_id",
        "include": [
          135314378855756999,
          1353143788557567278
        ]
      }
    }
  }
}

//results
{
  "took" : 0,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 3,
      "relation" : "eq"
    },
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "long_bucketing_index",
        "_type" : "_doc",
        "_id" : "lDWQOXAB9vBCg04Ye6R5",
        "_score" : 1.0,
        "_source" : {
          "id" : 1,
          "category_id" : 1353143788557567278
        }
      },
      {
        "_index" : "long_bucketing_index",
        "_type" : "_doc",
        "_id" : "TJWQOXABIyKBZB8Fgj3E",
        "_score" : 1.0,
        "_source" : {
          "id" : 2,
          "category_id" : 1353143788557567278
        }
      },
      {
        "_index" : "long_bucketing_index",
        "_type" : "_doc",
        "_id" : "HXKQOXABPlSARae1jLoC",
        "_score" : 1.0,
        "_source" : {
          "id" : 3,
          "category_id" : 135314378855756999
        }
      }
    ]
  },
  "aggregations" : {
    "category" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 0,
      "buckets" : [ ]
    }
  }
}
```

Notice the buckets array is empty for the aggregations.

The same exact procedure works as expected if using the `keyword` datatype

**Using the keyword datatype**
```
PUT keyword_bucketing_index
{
  "mappings": {
    "dynamic": "strict",
    "properties": {
      "id": {
        "type": "keyword"
      },
      "category_id": {
        "type": "keyword"
      }
    }
  }
}

POST keyword_bucketing_index/_doc
{
  "id": 1,
  "category_id": "1353143788557567278"
}

POST keyword_bucketing_index/_doc
{
  "id": 2,
  "category_id": "1353143788557567278"
}

POST keyword_bucketing_index/_doc
{
  "id": 3,
  "category_id": "135314378855756999"
}

//the query
POST keyword_bucketing_index/_search?
{
  "query": {
    "match_all": {}
  },
  "aggs": {
    "category": {
      "terms": {
        "field": "category_id",
        "include": [
          "135314378855756999",
          "1353143788557567278"
        ]
      }
    }
  }
}

//results
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 3,
      "relation" : "eq"
    },
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "keyword_bucketing_index",
        "_type" : "_doc",
        "_id" : "9DWUOXAB9vBCg04YTqRC",
        "_score" : 1.0,
        "_source" : {
          "id" : 1,
          "category_id" : "1353143788557567278"
        }
      },
      {
        "_index" : "keyword_bucketing_index",
        "_type" : "_doc",
        "_id" : "fguUOXABJIXuaXqhVZPY",
        "_score" : 1.0,
        "_source" : {
          "id" : 2,
          "category_id" : "1353143788557567278"
        }
      },
      {
        "_index" : "keyword_bucketing_index",
        "_type" : "_doc",
        "_id" : "gwuUOXABJIXuaXqhepNh",
        "_score" : 1.0,
        "_source" : {
          "id" : 3,
          "category_id" : "135314378855756999"
        }
      }
    ]
  },
  "aggregations" : {
    "category" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 0,
      "buckets" : [
        {
          "key" : "1353143788557567278",
          "doc_count" : 2
        },
        {
          "key" : "135314378855756999",
          "doc_count" : 1
        }
      ]
    }
  }
}
```

Additionally, attempting to do things such as `regex` in the `includes` filter for this aggregation does not work (as expected), however, the error message implies that any numeric type should work for the aggregation in general:

i.e trying something such as:
```
  "category": {
      "terms": {
        "field": "category_id",
        "include": [
          "1353*"
        ]
      }
    }
```
Returns the following error message:
```
"root_cause": [
  {
    "type": "aggregation_execution_exception",
    "reason": "Aggregation [category] cannot support 
regular expression style include/exclude 
settings as they can only be applied to string fields. 
Use an array of numeric values for include/exclude clauses used to filter numeric fields"
  }
],
```

I am happy to help contribute to docs with some guidance on what is best. To me this seems related to (but not the exact same) as:  #49538

**Comment by polyfractal** [comment] 2020-02-13 12:58
Terms agg definitely supports numerics and longs.  This appears to be an issue with `include`/`exclude`, probably some kind of parsing issue so that the parsed include value (parsed as bytes and converted to `long` later) is not matching the indexed `long` value.

I tested briefly and a terms agg + query works as expected:

```
POST long_bucketing_index/_search?
{
  "query": {
    "terms": {
      "category_id": ["135314378855756999", "1353143788557567278"]
    }
  },
  "aggs": {
    "category": {
      "terms": {
        "field": "category_id"
      }
    }
  }
}
```

As does a plain terms agg (no query or `include`).  Haven't had a chance to dig into the code to see what's going on, but I think this is indeed a bug.  Thanks for the report!

**Comment by imotov** [comment] 2020-05-05 14:27
@jdcohen220 sorry for the delay and thank you for the detailed reproduction script. I was able to reproduce the issue on 7.5.1, but it is no longer reproducible on 7.6.2 and above. Could you try upgrading and let us know if you are still experiencing the issue.

The issue with 
```
  "category": {
      "terms": {
        "field": "category_id",
        "include": [
          "1353*"
        ]
      }
    }
```
is a bit different. In the `keyword_bucketing_index` it doesn't return anything because it is supposed to match only terms like `135`, `1353`, `13533`, `135333`, `13533333` and so on. Based on your example, I think you meant  `"1353.*"` here. 

In case of `long_bucketing_index` in master we parse this value earlier now and therefore the error message changed. So, now it returns:
```
    "root_cause" : [
      {
        "type" : "number_format_exception",
        "reason" : "For input string: \"1353.*\""
      }
    ],
```
@polyfractal, @not-napoleon not sure if this is a bug or a feature :smile:

**Comment by imotov** [comment] 2020-05-11 16:48
Since it is no longer reproducible I am going to close the issue.

**Closed by imotov** 2020-05-11 16:48 UTC
Labels: :Analytics/Aggregations, >bug, Team:Analytics, feedback_needed
