### ISSUE TITLE
Add a node level limitation on the number of merging threads

### ISSUE THREAD

**Issue by ahadadi** [elastic/elasticsearch#28555] opened 2018-02-07 19:51 UTC
Currently there is no option to limit the number of merging threads per node.
The existing setting (index.merge.scheduler.max_thread_count) is a shard level setting, so even when set to 1 it's possible for #shards threads to merge together, hogging the CPU and hurting search latency.

**Comment by polyfractal** [comment] 2018-02-07 21:03
Not my area of expertise (would be good to wait for someone else to weigh in), but I'm not sure this is possible from a technical perspective.  Each Lucene index (e.g. a shard) manages it's own merge scheduler and thus it's own thread pool.  I don't think we can share those threads across multiple IndexWriters.

But, I could be wrong.  :)

If you're having problems with merge load affecting search latency, perhaps consider setting the merge throttling to a lower rate?  That would ease up the pressure, and probably do so in a more consistent manner than if we tried to limit total number of threads.

**Comment by jasontedor** [comment] 2018-02-07 22:02
To answer the immediate question, technically it would be possible.

**Comment by ahadadi** [comment] 2018-02-08 07:40
@polyfractal I'm only familiar with indices.store.throttle.max_bytes_per_sec which has been [removed in 6.x](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_60_settings_changes.html#_store_throttling_settings).
Are you referring to some other setting?

**Comment by bleskes** [comment] 2018-02-08 11:01
@jpountz any opinion? seems to me that a node level setting is more inline with what we do in other places, but I don't have a good grasp of the implications to Lucene.

**Comment by polyfractal** [comment] 2018-02-08 14:56
@ahadadi Yep, ignore me... forgot that was removed.  I'm 0/2 on this ticket :)

**Comment by jpountz** [comment] 2018-02-12 09:33
For the record, one thing we need to be careful with is that we should not let merges fall behind or updates/search are going to slow down due to the high number of segments.

The merge scheduler already has logic to throttle merges based on whether the merging backlog is stable, decreases or increases. This helps control how much is written per second, but not the concurrency of merges: if a node has 100 shards, there could still be 100 (throttled) merges.

Since you mentioned CPU usage and not disk I/O, I'm wondering whether the issue is something else? For instance on 5.x, sparse doc-value fields or sparse norm fields can cause merging to be CPU-intensive while writing little to disk, which makes rate limiting inefficient to limit the impact of merges on CPU usage. We might be able to check this by looking at the hot threads while merges are hogging your CPU.

**Comment by ahadadi** [comment] 2018-02-12 11:19
I will elaborate on our setup to give you some background:
We have an 8GB index split to 100 shards. The index is fully replicated to all nodes.
The index resides on tmpfs, so I/O is irrelevant.
We use custom routing and hit on average 1.2 shards.
Our floor_segment is 20MB, segments_per_tier & max_merge_at_once = 2. 
The result is that we have almost all our shards with 4 segments and a few with 2, due to custom routing that creates uneven shards (but not too uneven).
The consequence of this setup is that every refresh involves a merge on each shard to keep the segment count low. We are basically merging a big (10% - 20%) part of our 8GB index on each refresh. As small merges (< 50MB) are not throttled, we get 100 merging threads starting up almost simultaneously causing a few seconds of high latency, especially when there's high search load.
We are currently refreshing every 10 minutes to limit the effect of these spikes.

We arrived at this peculiar setup due to our stringent latency & throughput needs.
1) We tested floor_segment of 5MB and our capacity was almost halved simply by having to search 8 segments instead of 4.
2) We tried to use a smaller number of shards but that results in frequent bigger merges which cause higher latency spikes then we currently observe.
3) We tried to not replicate the index fully to all nodes, but that involves more round trips and again - more latency.

This setup allows us to serve 20K QPS using 14 physical machines with 24 hyperthreaded cores each and 128GB RAM. query latency 99 percentile is ~13ms, median is ~6ms.

You can see our merging pattern here
![Merging](https://user-images.githubusercontent.com/25010233/36093562-b1a0fade-0ff3-11e8-81dc-c67c7f1789bb.png)

**Comment by ahadadi** [comment] 2018-02-23 13:05
@jpountz regarding

> The merge scheduler already has logic to throttle merges based on whether the merging backlog is stable, decreases or increases

Looking at the code for `ConcurrentMergeScheduler` in Lucene 7.2.1 it seems the `MergeThread` `MergeRateLimiter` is not injected from outside, so it's also acting only on a shard level.
Is the logic you're referring to per shard?

**Comment by jpountz** [comment] 2018-02-23 15:27
This is per-shard indeed.

**Comment by ahadadi** [comment] 2018-02-23 16:28
As a workaround, I modified our client to index documents shard by shard.
When an indexing request arrives we identify the relevant shard ID and put the request in a per shard buffer (applying semaphore based back pressure on the total number of buffered documents). A background scheduler empties a single shard's buffer every 2.4 seconds and sends its documents over to elastic.
Combining this with a refresh every 7 seconds we get a much smoother merge process and I get long term job security :)

<img width="1417" alt="screen shot 2018-02-23 at 18 16 02" src="https://user-images.githubusercontent.com/25010233/36604204-ba237f30-18c5-11e8-86c0-de71cc9720f8.png">

**Comment by jpountz** [comment] 2021-04-06 20:30
> As a workaround, I modified our client to index documents shard by shard.

Oh, this is a nice trick, and actually a better fix than bounding the number of merge threads in my opinion. Maybe this is something that Elasticsearch could do it by itself by trying to space out refreshes as much as possible on a per-node basis. I don't like bounding the number of merge threads so I'm closing this issue and just opened #71371 for that other idea.

**Closed by jpountz** 2021-04-06 20:30 UTC
Labels: :Core/Infra/Core, >enhancement, Team:Core/Infra, team-discuss
