### ISSUE TITLE
[ML] Machine Learning datafeeds fail on remote clusters due to _has_privileges check

### ISSUE THREAD

**Issue by aarju** [elastic/elasticsearch#87832] opened 2022-06-20 08:58 UTC
### Elasticsearch Version

8.2.3

### Java Version

_bundled_

### OS Version

Elastic Cloud

### Problem Description

On our Cross Cluster Search primary cluster we have several Machine Learning jobs and Datafeeds using the data on the remote clusters. This worked fine in 7.X, but it appears that they are all in a closed state in 8.2.3 due to the `_has_privileges` api check failing on the remote clusters. We are unable to create new datafeeds using the CCS configuration. It is a known issue that `_has_privileges` does not work on remote CCS cluster indices so at this time Machine Learning does not support CCS due to this API check.
https://github.com/elastic/elasticsearch/issues/67798

### Steps to Reproduce

Create multiple clusters and configure them to use Cross Cluster Search. On the primary cluster create a Machine Learning job and datafeed referencing the remote cluster. The Machine Learning job will fail the permissions check when creating a new datafeed.

**Comment by aarju** [comment] 2022-06-20 10:01
A workaround to this issue is to have a user with `superuser` privileges on the primary CCS cluster open the datafeeds. It appears that if you are running as `superuser` the `_has_privileges` check is bypassed.

**Comment by droberts195** [comment] 2022-06-20 11:58
The fact that it worked in 7.17 but not 8.2 is interesting.  We didn't change anything in the ML code between these two versions.

https://github.com/elastic/elasticsearch/issues/72715#issuecomment-832769999 contains this interesting snippet:

>  - [ ] CCS checks are done against the local cluster:
>   - no checks on the remote
>   - the check on the local cluster can fail although the check is wrong
>   - to workaround the issue its necessary to create privileges on the local cluster that mimic the remote privileges or use `?defer_validation=true`
>     - example: you want to query `myremote:remote_test_index`, you need a privilege on the _local_ cluster for `remote_test_index` (:facepalm:) to pass the check in PUT, or use `defer_validation=true`, on `myremote` you need the privileges, too. Otherwise the transform will fail

It makes me think this is how it was working for datafeeds in 7.x too.  And now datafeeds is broken in 8.2 transforms probably is too.

@elastic/es-security were there changes in how `_has_privileges` worked between 7.17 and 8.2 that would explain this?

I am thinking that for the fix in 8.x we should just stop using `_has_privileges` to try to check in advance whether datafeeds/transforms will work if they reference any remote indices.

**Comment by slobodanadamovic** [comment] 2022-06-24 15:25
@droberts195 @dolaru 

There were no changes to how `_has_privileges` works between 7.17 and 8.2. Due to https://github.com/elastic/elasticsearch/issues/67798 issue, this was never expected to work.

I followed steps to reproduce from https://github.com/elastic/elasticsearch/issues/87832#issuecomment-1160314247 and I was able to reproduce the same error on 7.17.4 cluster. Could it be that you were logged with different user when testing in 7.17 cluster?

```
{
  "statusCode": 403,
  "error": "Forbidden",
  "message": "[security_exception: [security_exception] Reason: Cannot create datafeed [datafeed-test-ml-anomaly] because user testml lacks permissions on the indices: {\"*:kibana_sample_data*\":{\"indices:data/read/search\":false}}]: Cannot create datafeed [datafeed-test-ml-anomaly] because user testml lacks permissions on the indices: {\"*:kibana_sample_data*\":{\"indices:data/read/search\":false}}",
  "attributes": {
    "body": {
      "error": {
        "root_cause": [
          {
            "type": "security_exception",
            "reason": "Cannot create datafeed [datafeed-test-ml-anomaly] because user testml lacks permissions on the indices: {\"*:kibana_sample_data*\":{\"indices:data/read/search\":false}}"
          }
        ],
        "type": "security_exception",
        "reason": "Cannot create datafeed [datafeed-test-ml-anomaly] because user testml lacks permissions on the indices: {\"*:kibana_sample_data*\":{\"indices:data/read/search\":false}}"
      },
      "status": 403
    }
  }
}
```

**Comment by sommerda** [comment] 2022-10-05 15:19
I found a workaround by granting (dummy) read access to the local index `remote-cluster:kibana_sample_data*` on the cluster that runs the ML models. This allows for creation of the datafeed. 

To do so, I have created the corresponding role "ml_log_reader_dummy" and assigend it to my (less-privileged) user.
```
POST /_security/role/ml_log_reader_dummy
{
    "cluster": [],
    "indices": [
      {
        "names": [
					"remote-cluster:kibana_sample_data*"
        ],
        "privileges": [
          "read",
          "read_cross_cluster",
					"view_index_metadata"
        ],
        "field_security": {
          "grant": [
            "*"
          ],
          "except": []
        },
        "allow_restricted_indices": false
      }
    ],
    "applications" : [ ],
    "run_as": [],
    "metadata": {
			"ATTENTION": "The index name in this sample is hacky and will break as soon as these strings are properly parsed."
		},
    "transient_metadata": {
      "enabled": true
    }
}
```

Looks like `_has_privileges` is not resolving the `:`-remote-cluster notation. For now, it works. 

Of course, this workaround will break as soon as the index/data-view string is parsed differently.

**Comment by droberts195** [comment] 2022-11-18 14:58
Looking into this again it seems that the same problem affects transforms.  It turns out some of our transform tests have had to use the workaround mentioned above too, for example: https://github.com/elastic/elasticsearch/blob/312a0e2b2bf0648131ef2d0bf24f6adeb5c2d2c6/x-pack/plugin/transform/qa/multi-cluster-tests-with-security/src/test/resources/rest-api-spec/test/multi_cluster/80_transform.yml#L43

We'll change the up-front privilege validation for both datafeeds and transforms so that it ignores configured source indices if they contain colons (indicating cross-cluster patterns).

**Closed** 2022-11-24 16:02 UTC
Labels: >bug, :ml, Team:ML
