### ISSUE TITLE
TransportTasksActionTests#testFailedTasksCount failure

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#69731] opened 2021-03-01 17:43 UTC
**Build scan**: https://gradle-enterprise.elastic.co/s/wi7xnxp4xl6xm/console-log?task=:server:test

**Repro line**: `REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.action.admin.cluster.node.tasks.TransportTasksActionTests.testFailedTasksCount" -Dtests.seed=46694367B4C29CB8 -Dtests.security.manager=true -Dtests.locale=sq -Dtests.timezone=Antarctica/McMurdo -Druntime.java=8`

**Reproduces locally?**: No

**Applicable branches**: Only 7.x so far

**Failure history**: Three times in 90 days: https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-90d,mode:quick,to:now))&_a=(columns:!(build.branch),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:TransportTasksActionTests),sort:!(process.time-start,desc))

**Failure excerpt**:

```
  1> [2021-03-02T05:29:51,188][INFO ][o.e.a.a.c.n.t.TransportTasksActionTests] [testFailedTasksCount] before test
  1> [2021-03-02T05:29:51,233][INFO ][o.e.t.TransportService   ] [testFailedTasksCount] publish_address {127.0.0.1:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}
  1> [2021-03-02T05:29:51,256][INFO ][o.e.t.TransportService   ] [testFailedTasksCount] publish_address {127.0.0.1:9301}, bound_addresses {[::1]:9301}, {127.0.0.1:9301}
  1> [2021-03-02T05:29:51,287][INFO ][o.e.t.TransportService   ] [testFailedTasksCount] publish_address {127.0.0.1:9302}, bound_addresses {[::1]:9302}, {127.0.0.1:9302}
  1> [2021-03-02T05:29:51,323][INFO ][o.e.t.TransportService   ] [testFailedTasksCount] publish_address {127.0.0.1:9304}, bound_addresses {[::1]:9304}, {127.0.0.1:9304}
  1> [2021-03-02T05:29:51,378][INFO ][o.e.t.TransportService   ] [testFailedTasksCount] publish_address {127.0.0.1:9305}, bound_addresses {[::1]:9305}, {127.0.0.1:9305}
  1> [2021-03-02T05:29:51,416][INFO ][o.e.t.TransportService   ] [testFailedTasksCount] publish_address {127.0.0.1:9306}, bound_addresses {[::1]:9306}, {127.0.0.1:9306}
  1> [2021-03-02T05:29:51,454][INFO ][o.e.t.TransportService   ] [testFailedTasksCount] publish_address {127.0.0.1:9307}, bound_addresses {[::1]:9307}, {127.0.0.1:9307}
  1> [2021-03-02T05:29:51,519][INFO ][o.e.t.TransportService   ] [testFailedTasksCount] publish_address {127.0.0.1:9308}, bound_addresses {[::1]:9308}, {127.0.0.1:9308}
  1> [2021-03-02T05:29:51,551][INFO ][o.e.t.TransportService   ] [testFailedTasksCount] publish_address {127.0.0.1:9309}, bound_addresses {[::1]:9309}, {127.0.0.1:9309}
  1> [2021-03-02T05:29:51,556][INFO ][o.e.c.s.ClusterApplierService] [test] added {{node3}{rTzXvYPtQUSV0kY_g7upDA}{127.0.0.1}{127.0.0.1:9304},{node5}{bQPoT46qSHS4qFdZrT-mVw}{127.0.0.1}{127.0.0.1:9306},{node8}{REhZYKG2RHeH0AX6YN8yTw}{127.0.0.1}{127.0.0.1:9309},{node7}{rwpZotiASWqyC6IwQHyuhg}{127.0.0.1}{127.0.0.1:9308},{node4}{mLOMMC6zSqCfJf1XrgLh-w}{127.0.0.1}{127.0.0.1:9305},{node2}{UGjOOj35Q565ZyIX8xeinw}{127.0.0.1}{127.0.0.1:9302},{node6}{BAJBCYptTCuPco8rNECiSw}{127.0.0.1}{127.0.0.1:9307},{node1}{xq0KTs6lRcKdX8-cd4PW8Q}{127.0.0.1}{127.0.0.1:9301}}, term: 0, version: 1, reason: test setting state
  1> [2021-03-02T05:29:51,558][INFO ][o.e.c.s.ClusterApplierService] [test] master node changed {previous [{node1}{xq0KTs6lRcKdX8-cd4PW8Q}{127.0.0.1}{127.0.0.1:9301}], current [{node0}{r3SHT5-3R6qqk1y0pj9S_Q}{127.0.0.1}{127.0.0.1:9300}]}, added {{node5}{bQPoT46qSHS4qFdZrT-mVw}{127.0.0.1}{127.0.0.1:9306},{node7}{rwpZotiASWqyC6IwQHyuhg}{127.0.0.1}{127.0.0.1:9308},{node4}{mLOMMC6zSqCfJf1XrgLh-w}{127.0.0.1}{127.0.0.1:9305},{node8}{REhZYKG2RHeH0AX6YN8yTw}{127.0.0.1}{127.0.0.1:9309},{node0}{r3SHT5-3R6qqk1y0pj9S_Q}{127.0.0.1}{127.0.0.1:9300},{node2}{UGjOOj35Q565ZyIX8xeinw}{127.0.0.1}{127.0.0.1:9302},{node3}{rTzXvYPtQUSV0kY_g7upDA}{127.0.0.1}{127.0.0.1:9304},{node6}{BAJBCYptTCuPco8rNECiSw}{127.0.0.1}{127.0.0.1:9307}}, term: 0, version: 1, reason: test setting state
  1> [2021-03-02T05:29:51,563][INFO ][o.e.c.s.ClusterApplierService] [test] master node changed {previous [{node2}{UGjOOj35Q565ZyIX8xeinw}{127.0.0.1}{127.0.0.1:9302}], current [{node0}{r3SHT5-3R6qqk1y0pj9S_Q}{127.0.0.1}{127.0.0.1:9300}]}, added {{node5}{bQPoT46qSHS4qFdZrT-mVw}{127.0.0.1}{127.0.0.1:9306},{node1}{xq0KTs6lRcKdX8-cd4PW8Q}{127.0.0.1}{127.0.0.1:9301},{node0}{r3SHT5-3R6qqk1y0pj9S_Q}{127.0.0.1}{127.0.0.1:9300},{node4}{mLOMMC6zSqCfJf1XrgLh-w}{127.0.0.1}{127.0.0.1:9305},{node7}{rwpZotiASWqyC6IwQHyuhg}{127.0.0.1}{127.0.0.1:9308},{node8}{REhZYKG2RHeH0AX6YN8yTw}{127.0.0.1}{127.0.0.1:9309},{node3}{rTzXvYPtQUSV0kY_g7upDA}{127.0.0.1}{127.0.0.1:9304},{node6}{BAJBCYptTCuPco8rNECiSw}{127.0.0.1}{127.0.0.1:9307}}, term: 0, version: 1, reason: test setting state
  1> [2021-03-02T05:29:51,588][INFO ][o.e.c.s.ClusterApplierService] [test] master node changed {previous [{node3}{rTzXvYPtQUSV0kY_g7upDA}{127.0.0.1}{127.0.0.1:9304}], current [{node0}{r3SHT5-3R6qqk1y0pj9S_Q}{127.0.0.1}{127.0.0.1:9300}]}, added {{node0}{r3SHT5-3R6qqk1y0pj9S_Q}{127.0.0.1}{127.0.0.1:9300},{node4}{mLOMMC6zSqCfJf1XrgLh-w}{127.0.0.1}{127.0.0.1:9305},{node1}{xq0KTs6lRcKdX8-cd4PW8Q}{127.0.0.1}{127.0.0.1:9301},{node2}{UGjOOj35Q565ZyIX8xeinw}{127.0.0.1}{127.0.0.1:9302},{node7}{rwpZotiASWqyC6IwQHyuhg}{127.0.0.1}{127.0.0.1:9308},{node6}{BAJBCYptTCuPco8rNECiSw}{127.0.0.1}{127.0.0.1:9307},{node5}{bQPoT46qSHS4qFdZrT-mVw}{127.0.0.1}{127.0.0.1:9306},{node8}{REhZYKG2RHeH0AX6YN8yTw}{127.0.0.1}{127.0.0.1:9309}}, term: 0, version: 1, reason: test setting state
  1> [2021-03-02T05:29:51,591][INFO ][o.e.c.s.ClusterApplierService] [test] master node changed {previous [{node4}{mLOMMC6zSqCfJf1XrgLh-w}{127.0.0.1}{127.0.0.1:9305}], current [{node0}{r3SHT5-3R6qqk1y0pj9S_Q}{127.0.0.1}{127.0.0.1:9300}]}, added {{node1}{xq0KTs6lRcKdX8-cd4PW8Q}{127.0.0.1}{127.0.0.1:9301},{node5}{bQPoT46qSHS4qFdZrT-mVw}{127.0.0.1}{127.0.0.1:9306},{node2}{UGjOOj35Q565ZyIX8xeinw}{127.0.0.1}{127.0.0.1:9302},{node6}{BAJBCYptTCuPco8rNECiSw}{127.0.0.1}{127.0.0.1:9307},{node7}{rwpZotiASWqyC6IwQHyuhg}{127.0.0.1}{127.0.0.1:9308},{node8}{REhZYKG2RHeH0AX6YN8yTw}{127.0.0.1}{127.0.0.1:9309},{node3}{rTzXvYPtQUSV0kY_g7upDA}{127.0.0.1}{127.0.0.1:9304},{node0}{r3SHT5-3R6qqk1y0pj9S_Q}{127.0.0.1}{127.0.0.1:9300}}, term: 0, version: 1, reason: test setting state
  1> [2021-03-02T05:29:51,600][INFO ][o.e.c.s.ClusterApplierService] [test] master node changed {previous [{node5}{bQPoT46qSHS4qFdZrT-mVw}{127.0.0.1}{127.0.0.1:9306}], current [{node0}{r3SHT5-3R6qqk1y0pj9S_Q}{127.0.0.1}{127.0.0.1:9300}]}, added {{node0}{r3SHT5-3R6qqk1y0pj9S_Q}{127.0.0.1}{127.0.0.1:9300},{node2}{UGjOOj35Q565ZyIX8xeinw}{127.0.0.1}{127.0.0.1:9302},{node7}{rwpZotiASWqyC6IwQHyuhg}{127.0.0.1}{127.0.0.1:9308},{node8}{REhZYKG2RHeH0AX6YN8yTw}{127.0.0.1}{127.0.0.1:9309},{node1}{xq0KTs6lRcKdX8-cd4PW8Q}{127.0.0.1}{127.0.0.1:9301},{node4}{mLOMMC6zSqCfJf1XrgLh-w}{127.0.0.1}{127.0.0.1:9305},{node3}{rTzXvYPtQUSV0kY_g7upDA}{127.0.0.1}{127.0.0.1:9304},{node6}{BAJBCYptTCuPco8rNECiSw}{127.0.0.1}{127.0.0.1:9307}}, term: 0, version: 1, reason: test setting state
  1> [2021-03-02T05:29:51,620][INFO ][o.e.c.s.ClusterApplierService] [test] master node changed {previous [{node6}{BAJBCYptTCuPco8rNECiSw}{127.0.0.1}{127.0.0.1:9307}], current [{node0}{r3SHT5-3R6qqk1y0pj9S_Q}{127.0.0.1}{127.0.0.1:9300}]}, added {{node3}{rTzXvYPtQUSV0kY_g7upDA}{127.0.0.1}{127.0.0.1:9304},{node0}{r3SHT5-3R6qqk1y0pj9S_Q}{127.0.0.1}{127.0.0.1:9300},{node5}{bQPoT46qSHS4qFdZrT-mVw}{127.0.0.1}{127.0.0.1:9306},{node7}{rwpZotiASWqyC6IwQHyuhg}{127.0.0.1}{127.0.0.1:9308},{node8}{REhZYKG2RHeH0AX6YN8yTw}{127.0.0.1}{127.0.0.1:9309},{node4}{mLOMMC6zSqCfJf1XrgLh-w}{127.0.0.1}{127.0.0.1:9305},{node2}{UGjOOj35Q565ZyIX8xeinw}{127.0.0.1}{127.0.0.1:9302},{node1}{xq0KTs6lRcKdX8-cd4PW8Q}{127.0.0.1}{127.0.0.1:9301}}, term: 0, version: 1, reason: test setting state
  1> [2021-03-02T05:29:51,621][INFO ][o.e.c.s.ClusterApplierService] [test] master node changed {previous [{node7}{rwpZotiASWqyC6IwQHyuhg}{127.0.0.1}{127.0.0.1:9308}], current [{node0}{r3SHT5-3R6qqk1y0pj9S_Q}{127.0.0.1}{127.0.0.1:9300}]}, added {{node0}{r3SHT5-3R6qqk1y0pj9S_Q}{127.0.0.1}{127.0.0.1:9300},{node1}{xq0KTs6lRcKdX8-cd4PW8Q}{127.0.0.1}{127.0.0.1:9301},{node2}{UGjOOj35Q565ZyIX8xeinw}{127.0.0.1}{127.0.0.1:9302},{node8}{REhZYKG2RHeH0AX6YN8yTw}{127.0.0.1}{127.0.0.1:9309},{node6}{BAJBCYptTCuPco8rNECiSw}{127.0.0.1}{127.0.0.1:9307},{node4}{mLOMMC6zSqCfJf1XrgLh-w}{127.0.0.1}{127.0.0.1:9305},{node5}{bQPoT46qSHS4qFdZrT-mVw}{127.0.0.1}{127.0.0.1:9306},{node3}{rTzXvYPtQUSV0kY_g7upDA}{127.0.0.1}{127.0.0.1:9304}}, term: 0, version: 1, reason: test setting state
  1> [2021-03-02T05:29:51,649][INFO ][o.e.c.s.ClusterApplierService] [test] master node changed {previous [{node8}{REhZYKG2RHeH0AX6YN8yTw}{127.0.0.1}{127.0.0.1:9309}], current [{node0}{r3SHT5-3R6qqk1y0pj9S_Q}{127.0.0.1}{127.0.0.1:9300}]}, added {{node7}{rwpZotiASWqyC6IwQHyuhg}{127.0.0.1}{127.0.0.1:9308},{node3}{rTzXvYPtQUSV0kY_g7upDA}{127.0.0.1}{127.0.0.1:9304},{node4}{mLOMMC6zSqCfJf1XrgLh-w}{127.0.0.1}{127.0.0.1:9305},{node2}{UGjOOj35Q565ZyIX8xeinw}{127.0.0.1}{127.0.0.1:9302},{node5}{bQPoT46qSHS4qFdZrT-mVw}{127.0.0.1}{127.0.0.1:9306},{node1}{xq0KTs6lRcKdX8-cd4PW8Q}{127.0.0.1}{127.0.0.1:9301},{node0}{r3SHT5-3R6qqk1y0pj9S_Q}{127.0.0.1}{127.0.0.1:9300},{node6}{BAJBCYptTCuPco8rNECiSw}{127.0.0.1}{127.0.0.1:9307}}, term: 0, version: 1, reason: test setting state
  1> [2021-03-02T05:29:52,076][INFO ][o.e.a.a.c.n.t.TransportTasksActionTests] [testFailedTasksCount] after test
  2> REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.action.admin.cluster.node.tasks.TransportTasksActionTests.testFailedTasksCount" -Dtests.seed=46694367B4C29CB8 -Dtests.security.manager=true -Dtests.locale=sq -Dtests.timezone=Antarctica/McMurdo -Druntime.java=8
  2> java.lang.AssertionError: expected:<0> but was:<1>
        at __randomizedtesting.SeedInfo.seed([46694367B4C29CB8:2B231CCEE907C653]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at org.elasticsearch.action.admin.cluster.node.tasks.TransportTasksActionTests.testFailedTasksCount(TransportTasksActionTests.java:520)
```

**Comment by DaveCTurner** [comment] 2021-07-08 15:36
There's only been one failure of this since the additional logging was added:

```
java.lang.AssertionError: still running tasks on node [node1]  
4: [4][internal:transport/handshake] started at 1623854057836
```

It seems that the task is not unregistered even though the handshakes have all completed. We unregister the task before sending the handshake response, and we receive the response before checking all the tasks are unregistered. However, the JLS's threading model talks a bit about "external actions" but I don't see anything that guarantees that the transmission of some bytes on a socket _happens before_ the bytes are received by the other end, because the causal relationship between these two events is outside the JVM's purview. Maybe this means that unregistering the task and listing all the tasks are poorly synchronized and might be observed to run out of order?

Seems pretty tenuous I know, but I'm out of ideas otherwise...

**Comment by DaveCTurner** [comment] 2021-12-15 17:55
I'm still stumped here. I've run literally millions of iterations of this test on an otherwise-stressed machine without a failure, and yet it fails in CI every few months. The last one was in https://gradle-enterprise.elastic.co/s/m6jvvn7fygnem and reports:

```
org.elasticsearch.action.admin.cluster.node.tasks.TransportTasksActionTests > testFailedTasksCount FAILED
    java.lang.AssertionError: eventually completed, but still unexpected:
    still running tasks on node [node3]
    7: [7][internal:transport/handshake] started at 1633306893727

    Expected: <0>
         but: was <98>
        at __randomizedtesting.SeedInfo.seed([4C58CBB4DD7E14FA:2112941D80BB4E11]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.elasticsearch.action.admin.cluster.node.tasks.TransportTasksActionTests.testFailedTasksCount(TransportTasksActionTests.java:538)
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.action.admin.cluster.node.tasks.TransportTasksActionTests.testFailedTasksCount" -Dtests.seed=4C58CBB4DD7E14FA -Dtests.locale=ar-MA -Dtests.timezone=Pacific/Samoa -Druntime.java=8
```

This indicates that a transport handshake task was still running despite all the calls to `TransportService#connectToNode` having completed successfully. The handshake isn't stuck because it completes in the `assertBusy()`, but we shouldn't be able to see it at all. I can't see how that would happen.

**Comment by henningandersen** [comment] 2021-12-17 16:52
I examined this today and it looks like an external transport client/peer finder that does the handshake. Looking at the logs from https://gradle-enterprise.elastic.co/s/m6jvvn7fygnem, I find following:

```
grep 'internal:transport/handshake' m6jvvn7fygnem-console-log.txt  | grep 'sent to' | wc -l
42
grep 'internal:transport/handshake' m6jvvn7fygnem-console-log.txt  | grep 'received response' | wc -l
42
grep 'internal:transport/handshake' m6jvvn7fygnem-console-log.txt  | grep 'received request' | wc -l
53
```

so we received more requests than the test asked for. Also, running it locally with same seed, I get:

```
grep 'internal:transport/handshake' mylog.txt | grep 'sent to' | wc -l
42
grep 'internal:transport/handshake' mylog.txt | grep 'received response' | wc -l
42
grep 'internal:transport/handshake' mylog.txt | grep 'received request' | wc -l
42
```

and finally, this test uses the default port numbers, increasing the probability. I will work on a fix for this, possibly just using the gradle worker specific port range instead.

**Comment by henningandersen** [comment] 2021-12-21 10:24
Opened #81979 that hopefully fixes this but left the logging and assert-busy in place in case above turns out not to be the root cause, i.e., this fails again. Will leave this issue open to ensure we remember to remove the logging etc. once we declare this fixed.

**Comment by henningandersen** [comment] 2022-01-17 08:54
Issue has not reoccurred, closing for now, please reopen if this test fails again, even if only very rarely.

**Closed** 2022-01-17 08:54 UTC
Labels: feedback_needed, >test-failure, :Distributed/Task Management, Team:Distributed
