### ISSUE TITLE
[CI] RestartIndexFollowingIT testFollowIndex failing

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#81302] opened 2021-12-03 11:22 UTC
It seems to fail rarely. I can see a similar failure on Oct25 in master and another on Nov 22 in 7.16

**Build scan:**
https://gradle-enterprise.elastic.co/s/bf3jiz2ojwa5q/tests/:x-pack:plugin:ccr:internalClusterTest/org.elasticsearch.xpack.ccr.RestartIndexFollowingIT/testFollowIndex

**Reproduction line:**
`./gradlew ':x-pack:plugin:ccr:internalClusterTest' --tests "org.elasticsearch.xpack.ccr.RestartIndexFollowingIT.testFollowIndex" -Dtests.seed=515B350E07CA8464 -Dtests.locale=es-EC -Dtests.timezone=America/Belize -Druntime.java=17`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ccr.RestartIndexFollowingIT&tests.test=testFollowIndex

**Failure excerpt:**
```
java.lang.AssertionError: (No message provided)

  at __randomizedtesting.SeedInfo.seed([515B350E07CA8464:B237FA3C3E72BDEE]:0)
  at org.junit.Assert.fail(Assert.java:86)
  at org.junit.Assert.assertTrue(Assert.java:41)
  at org.junit.Assert.assertTrue(Assert.java:52)
  at org.elasticsearch.xpack.ccr.RestartIndexFollowingIT.setupRemoteCluster(RestartIndexFollowingIT.java:125)
  at org.elasticsearch.xpack.ccr.RestartIndexFollowingIT.testFollowIndex(RestartIndexFollowingIT.java:91)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by idegtiarenko** [comment] 2021-12-09 12:23
This test is failing the second assertion:
https://github.com/elastic/elasticsearch/blob/12ad399c488f0cc60e19b5e1b29c6d569cb4351a/x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/RestartIndexFollowingIT.java#L123-L125

I managed to break this assertion locally in 2 ways:
* try to connect to the cluster that is not running:
```
[2021-12-09T15:09:02,993][INFO ][o.e.c.s.ClusterSettings  ] [follower2] updating [cluster.remote.leader_cluster.seeds] from [[]] to [["127.0.0.1:3418"]]
[2021-12-09T15:09:02,999][WARN ][o.e.t.SniffConnectionStrategy] [follower2] fetching nodes from external cluster [leader_cluster] failed
org.elasticsearch.transport.ConnectTransportException: [][127.0.0.1:3418] connect_exception
```
* connection is taking more then 10 seconds
```
[2021-12-09T10:07:32,189][INFO ][o.e.c.s.ClusterSettings  ] [follower0] updating [cluster.remote.leader_cluster.seeds] from [[]] to [["127.0.0.1:46563"]]
[2021-12-09T10:07:42,196][WARN ][o.e.t.RemoteClusterService] [follower0] failed to connect to new remote cluster leader_cluster within 10s
```

I managed to find 3 build scans with the test failure during last 45 days:
https://gradle-enterprise.elastic.co/s/ka55k26zoffv4/tests/:x-pack:plugin:ccr:internalClusterTest/org.elasticsearch.xpack.ccr.RestartIndexFollowingIT/testFollowIndex?expanded-stacktrace=WyIwIl0&top-execution=1
https://gradle-enterprise.elastic.co/s/uef2oayl5nze4/tests/:x-pack:plugin:ccr:internalClusterTest/org.elasticsearch.xpack.ccr.RestartIndexFollowingIT/testFollowIndex?anchor=eyJvdXRwdXRMaW5lIjoiMC0yNDkifQ&focused-execution=1#Lundefined
https://gradle-enterprise.elastic.co/s/bf3jiz2ojwa5q/tests/:x-pack:plugin:ccr:internalClusterTest/org.elasticsearch.xpack.ccr.RestartIndexFollowingIT/testFollowIndex?anchor=eyJvdXRwdXRMaW5lIjoiMC0yOTgifQ&expanded-stacktrace=WyIwIl0

However none of them contained logs that would indicate timeout or failure to connect.
I have no other ideas at the moment.

**Comment by idegtiarenko** [comment] 2022-01-13 07:47
I am closing as this have not reproduced since additional logs were added about a month ago.
Please reopen if/when this fails again.

**Comment by tlrx** [comment] 2022-04-25 09:24
It occurs again (#86129) in https://gradle-enterprise.elastic.co/s/xmqr6idbdvhii/

**Comment by iverase** [comment] 2022-05-03 09:40
Another instance in 8.2: https://gradle-enterprise.elastic.co/s/gescnhvdiwez2

**Comment by idegtiarenko** [comment] 2022-05-09 12:12
Additional logging enabled in https://github.com/elastic/elasticsearch/pull/81799/files:

```
[2022-05-06T09:36:31,098][TRACE][o.e.t.SniffConnectionStrategy] [follower0] [leader_cluster] opening transient connection to seed node: [{leader_cluster#127.0.0.1:42317}{sXThZrxaQFeeNP8uJZdxIQ}{127.0.0.1}{127.0.0.1:42317}{cdfhilmrstvw}]
[2022-05-06T09:36:31,099][DEBUG][o.e.t.RemoteClusterService] [follower0] connection to new remote cluster leader_cluster failed
[2022-05-06T09:36:31,106][TRACE][o.e.t.SniffConnectionStrategy] [follower0] [leader_cluster] opening managed connection to seed node: [{leader0}{kvh8qZWvSDqHXZkH-sFOIQ}{hbFYM6KeTLq95EFUHeoGjA}{127.0.0.1}{127.0.0.1:42317}{ilmrt}{xpack.installed=true}] proxy address: []
[2022-05-06T09:36:31,112][TRACE][o.e.t.SniffConnectionStrategy] [follower0] [leader_cluster] opening managed connection to node: [{leader1}{ZqVuZm-wRI-qWnzFLlbp_w}{0xpsctXjRtmB2nsuf2wq0w}{127.0.0.1}{127.0.0.1:37277}{cdfhilrstw}{xpack.installed=true}] proxy address: []
[2022-05-06T09:36:31,118][TRACE][o.e.t.SniffConnectionStrategy] [follower0] [leader_cluster] opening managed connection to node: [{leader0}{kvh8qZWvSDqHXZkH-sFOIQ}{hbFYM6KeTLq95EFUHeoGjA}{127.0.0.1}{127.0.0.1:42317}{ilmrt}{xpack.installed=true}] proxy address: []
```

**Comment by idegtiarenko** [comment] 2022-05-09 12:33
Unfortunately additional information is not containing exception message nor stack trace. I am opening a pr to include those.

**Comment by idegtiarenko** [comment] 2022-06-16 09:35
There was one more failure: https://gradle-enterprise.elastic.co/s/krnbc7iy5mfyu/tests/:x-pack:plugin:ccr:internalClusterTest/org.elasticsearch.xpack.ccr.RestartIndexFollowingIT/testFollowIndex?top-execution=1

It was caused by: 
```
[2022-06-15T03:32:12,633][DEBUG][o.e.t.RemoteClusterService] [follower0] connection to new remote cluster [leader_cluster] 
  org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: connect listener queue is full
```

**Comment by luigidellaquila** [comment] 2022-06-28 12:23
New failure here https://gradle-enterprise.elastic.co/s/wa4gdqkqxacbe
Though, I don't see `connect listener queue is full` this time; the problem seems to be on cluster setup

**Comment by valeriy42** [comment] 2022-07-04 09:13
Another failure here https://gradle-enterprise.elastic.co/s/ydb32aun3jbu2/tests/:x-pack:plugin:ccr:internalClusterTest/org.elasticsearch.xpack.ccr.RestartIndexFollowingIT/testFollowIndex

Caused again by
```
[2022-07-04T17:39:22,002][DEBUG][o.e.t.RemoteClusterService] [follower0] connection to new remote cluster [leader_cluster] failed
org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: connect listener queue is full
```

**Comment by ywangd** [comment] 2022-07-07 07:48
Another on 7.17 https://gradle-enterprise.elastic.co/s/6yjj5ebjwjwgq/tests/:x-pack:plugin:ccr:internalClusterTest/org.elasticsearch.xpack.ccr.RestartIndexFollowingIT/testFollowIndex?top-execution=1

**Closed** 2022-08-08 06:24 UTC
Labels: feedback_needed, >test-failure, :Distributed/CCR, Team:Distributed
