### ISSUE TITLE
Improve the YML testing infrastructure 

### ISSUE THREAD

**Issue by alpar-t** [elastic/elasticsearch#47793] opened 2019-10-09 13:25 UTC
We had several different issues and thoughts around the YML test infrastructure. 
This issue collects them all since it probably makes most sense to consider this as part of a larger project of improving them:

- [ ] `precommit` should check that the yml tests parse (from #46636) 
- [ ] YML tests should be able to load from the classpath so we can leverage Gradles dependency handling and  don't need various tasks to copy these around. 
- [ ] Add support for generating a runner so we don't have to check a class in specifically 
- [ ] yml tets can have dots in their name that confuses Gradle ( from #41380 )

**Comment by rjernst** [comment] 2019-10-10 17:13
> YML tests should be able to load from the classpath

These tests are already loaded from the classpath. The issue is whether the tests exist inside a jar or in a classpath directory. The jar based support was removed because there are issues with the zip based filesystem overlay java uses there. The extraction of the jar exists so that these tests always run the same way, regardless of where the tests came from; sometimes they are from the core rest-api-spec project, and sometimes they are in the local project's classpath under src/test/resources, and these must all be merged together.

I think we need to re-think how these test files are specified. We really don't; loading from the classpath just complicates things, as we are limited by java's classloader capabilities.  IMO we should place the tests/specs in zip files, extract them to a local directory that is not on the classpath, and pass directory paths to the test runner to look at for specs and tests.

**Comment by atorok** [comment] 2019-10-15 12:30
Sorry, I was thinking about loading from the Jars when I wrote that. 
I was hoping we can work around those issues as there are a number of popular framework that can list and use resources from the classpath regardless of how those get there, and it shouldn't make any difference for the test itself. 

The end goal I am looking for is to make these behave like the Gradle test runner that just scans for classes. I think there's a net win in getting the YML tests to behave as close as possible if not identical to how the Gradle runner otherwise runs tests,
so we could use Gradles dependency management  to pass these around, possibly avoiding any needless packing and unpacking along the way. 

Another way to achieve this would be  to "compile" the YML into class files. 
That would assure they behave the same way, but I don't have experience and haven't looked into what that would entail and what tools are available.

**Comment by atorok** [comment] 2019-10-15 12:35
We could also generate source code and compile it with [getSystemJavaCompiler](https://docs.oracle.com/javase/6/docs/api/javax/tools/ToolProvider.html) to avoid dealing with generated sources and multiple source sets that would complicate the Gradle config.

**Comment by rjernst** [comment] 2019-10-15 23:09
I'd be in favor of transforming the yml into test class files. It would alleviate a lot of pain we have had with eg reproduce lines being special for rest tests. It would also eliminate the need to pass the files in on the classpath. However, I don't think it is a small task, but nothing to improve the rest tests really would be.

**Comment by probakowski** [comment] 2019-10-16 14:42
I have some ideas how to implement this compiling yml to classes in a way that should be fairly easy and straightforward. I'd like to give it a try if you don't mind.

**Comment by atorok** [comment] 2019-10-16 14:51
Quite the contrary.  We can also use this issue to discuss ideas, in case you want some feedback before investing a lot of  time.

**Comment by probakowski** [comment] 2019-10-28 09:50
@atorok I've created initial version in #48568, tell me what do you think when you have some time

**Comment by mark-vieira** [comment] 2019-10-29 20:14
> I'd be in favor of transforming the yml into test class files. It would alleviate a lot of pain we have had with eg reproduce lines being special for rest tests.

@rjernst could you elaborate here? The only special handling we had to do was with the fact that some YML test names include a `.` character which messes things up. Otherwise AFAIK you can run individual YML tests using the `--tests` option just like any other test.

**Comment by atorok** [comment] 2019-10-30 05:59
@probakowski thanks allot for the time invested in this! I'm replying here to so it's all in a single place.  
I think the most important conclusion is that it's not overly difficult to re-use the existing infrastructure to some extent, it will take a bit more work to achieve all the goals outlined in this ticket, but it's doable. For example we would need to be able to load the yml files from a configuration and possibly a jar, not just the yml files in the sources dir.
I would strongly prefer we generate one class per file instead of inner classes  and randomly sized chunks, this would help us parallelize these tests in the future too and it's a more natural division. 

I'm not sold on using asm due to it's complexity and high brier to entry, for someone like me who never used it it would be challenging to even edit the existing code ... using `getSystemJavaCompiler` as described above would help with this but I'm not sure of any downsides it may have. 

I think the general direction on the PR is good, having a task to compile these is the way to go. We can iterate on the implementation as mentioned above. 
Eventually I think we would want yml to be interpreted as part of the compilation to catch any illegal syntax there, we can then also better support jars, worst case Gradle can extract them. 
A Gradle plugin or a better way to integrate this into projects would also be nice. 
The base classes are just for configuration we could extract it to a Gradle extension and generate the code according to that configuration, but these are all improvements we could work on incrementally.

**Comment by atorok** [comment] 2019-10-30 06:48
On second taught the configuration we now have in the base class should really be part of the yml itself as it influences the test outcome itself. That way clients could benefit as well. 

@javanna  might have some input or interest w.r.t. clients running these tests.

**Comment by mark-vieira** [comment] 2020-12-18 08:02
There already exists a separate issue for the first item, there's not good consensus on the second item, and the fourth item has been resolved. For now I'm going to close this as generating yml test runners isn't terribly high priority.

**Closed by mark-vieira** 2020-12-18 08:02 UTC
Labels: :Delivery/Build, >enhancement, Team:Delivery
