### ISSUE TITLE
flood_stage setting marks indices read-only even if host has other free data disks

### ISSUE THREAD

**Issue by phoerious** [elastic/elasticsearch#36965] opened 2018-12-23 10:56 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 6.4.1

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_162

**OS version** (`uname -a` if on a Unix-like system): Elastic Docker Image on Ubuntu 14.04 host

**Description of the problem including expected versus actual behavior**:

The `cluster.routing.allocation.disk.watermark.flood_stage` setting seems to be based on individual disks instead of total storage capacity on a host, resulting in read-only indices in case a single disk runs out of space even if all nodes still have enough capacity to hold the shards.

Background: we have an Elasticsearch cluster of 130 nodes with 7 data disks per host. Although all nodes reported a remaining storage capacity between 1 and 10 TB, my indices were continuously being reset to read-only, even with `flood_stage` set to something as low as 10 GB. I tried lowering the `high` threshold so as to move shards away from "fuller" hosts, but it didn't solve the problem.

In the end, the reason turned out to be a single hosts with 1 full disk (only a few hundred MB left) and I had to manually remove the disk from the node's config file. The other 6 disks were more than capable of holding shards and ES had already moved all its shards from the full disk to somewhere else (meaning the data filling the disk belonged to other processes), but it kept marking my indices read-only anyway.

It would be great if the `flood_stage` setting were only applied if *all* disks on a host containing shards exceed the threshold.

**Steps to reproduce**:
 1. Deploy a cluster with multiple data disks per host
 2. fill up one disk with stuff beyond the 'flood_stage' threshold
 3. indices are marked read-only even though all hosts have enough space to hold shards

**Comment by DaveCTurner** [comment] 2018-12-24 14:13
This is roughly a duplicate of #28323 and, as indicated there, we don't expect to work on making allocation decisions on a disk-by-disk basis in the foreseeable future. If the data paths are all equivalent then you can obtain disk-based balancing by spreading a single filesystem across all the disks on each node (e.g. using RAID0), which has the advantage that each shard may span multiple disks.

**Closed by DaveCTurner** 2018-12-24 14:13 UTC
Labels: :Distributed/Allocation

**Comment by phoerious** [comment] 2018-12-24 15:00
Having a single file system requires at least RAID1 to be reliable. Otherwise we lose all data (that's many Terabytes) if we lose one disk (and we lose disks regularly at that scale). However, having RAID1 is not desirable, since it halves our storage and is entirely redundant for both Elasticsearch and HDFS.

**Comment by DaveCTurner** [comment] 2018-12-24 15:32
The other option available today is to run more nodes, each with fewer data paths.

There is an ongoing internal discussion on this subject, to which I have added a link to your comment above. It's useful feedback, thanks.

**Comment by phoerious** [comment] 2018-12-24 15:38
You mean one per disk? That's only an option if they could share memory. I cannot allocate 20GB RAM for for each of the 7+ nodes on a host.

**Comment by DaveCTurner** [comment] 2018-12-24 16:36
As a general guideline nodes with fewer shards need less heap, although there is some overhead so it's not completely linear.
