### ISSUE TITLE
Block Colon (:) in Index Names

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#25924] opened 2017-07-27 05:30 UTC
Now that Cross-Cluster Search can respond by modifying / augmenting the `_index` name to indicate the index's true origin, we should no longer accept index names that include `:` in them to avoid confusion.

For instance, if I create an index named `test:index`, then Elasticsearch will happily accept it today. This could easily lead to problems for some clients that then parse that index name and assume that it is using cross-cluster search as a result.

**Comment by olcbean** [comment] 2017-07-27 11:02
I think this is similar to #23892. AFAICS it was also discussed on FixItFriday ( https://github.com/elastic/elasticsearch/pull/23911#issuecomment-308239886 ), but I couldn't find a note what was decided.

**Comment by javanna** [comment] 2017-07-27 11:07
thanks for pointing this out @olcbean . This is a duplicate of #23892 . I am not sure that we discussed it yet in FixItFriday, in which case somebody would have commented on the outcome of the discussion.

**Closed by javanna** 2017-07-27 11:07 UTC
Labels: :Index APIs, discuss
