### ISSUE TITLE
[CI] SystemDataStreamIT timing out

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#72031] opened 2021-04-21 15:16 UTC
This is a newly added test that is regularly timing out (5% of the time). Reproduced locally for me.

**Build scan:**
https://gradle-enterprise.elastic.co/s/i3jrnnjc5xxwi/tests/:x-pack:plugin:data-streams:internalClusterTest/org.elasticsearch.datastreams.SystemDataStreamIT/classMethod

**Reproduction line:**
`./gradlew ':x-pack:plugin:data-streams:internalClusterTest' --tests "org.elasticsearch.datastreams.SystemDataStreamIT" -Dtests.seed=D294A26992B8ED12 -Dtests.locale=mt-MT -Dtests.timezone=US/East-Indiana -Druntime.java=11`

**Applicable branches:**
master, 7.x, 7.13

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.datastreams.SystemDataStreamIT&tests.test=classMethod

**Failure excerpt:**
```
java.lang.Exception: Suite timeout exceeded (>= 1800000 msec).

  at __randomizedtesting.SeedInfo.seed([B729FA5941DE57CD]:0)

```

**Comment by jaymode** [comment] 2021-04-21 15:26
@mark-vieira thanks for opening this issue. However if you look at the cause this appears to be happening in various tests and might be more of a systemic issue:

```
  | java.lang.AssertionError: All incoming requests on node [node_s2] should have finished. Expected 0 but got 557; pending tasks [[{ |  
-- | -- | --
  | "node" : "node_s2", |  
  | "id" : 32, |  
  | "type" : "transport", |  
  | "action" : "internal:index/shard/recovery/start_recovery", |  
  | "description" : "", |  
  | "start_time" : "2021-04-21T05:45:00.470Z", |  
  | "start_time_in_millis" : 1618983900470, |  
  | "running_time" : "1.1m", |  
  | "running_time_in_nanos" : 66064932191, |  
  | "cancellable" : false, |  
  | "headers" : { } |  
  | }]]
```

I've seen this in ClusterHealthIT, UpdateSettingsIT, SimpleClusterStateIT and DataStreamIT.

**Comment by mark-vieira** [comment] 2021-04-21 15:40
Thanks, Jay. Yeah, I noticed this in https://github.com/elastic/elasticsearch/issues/72033

It's likely that root issue is causing all sorts of trouble.

**Comment by mark-vieira** [comment] 2021-04-21 15:41
I'll keep this issue open since we'll need to unmute this test once that underly issue is sorted out.

**Comment by jtibshirani** [comment] 2021-04-21 22:38
I'm closing since I removed the `@AwaitsFix` in #72055. We can use #72033 to track the investigation.

**Closed by jtibshirani** 2021-04-21 22:38 UTC
Labels: :Core/Features/Data streams, >test-failure, Team:Core/Features
