### ISSUE TITLE
Crash on StubRoutines::jint_disjoint_arraycopy

### ISSUE THREAD

**Issue by lytvynenko-dmitriy** [elastic/elasticsearch#56468] opened 2020-05-08 21:12 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 6.5.3

**Plugins installed**: []

**JVM version**: Java HotSpot(TM) 64-Bit Server VM (11.0.6+8-LTS, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)

**OS version**: Windows Server 2016 , 64 bit Build 14393 (10.0.14393.3630)

**Description of the problem including expected versus actual behavior**:
We encounter crash of Elasticsearch when it is configured to store the data to network drive.

[hs_err_pid360.log](https://github.com/elastic/elasticsearch/files/4601638/hs_err_pid360.log)
[hs_err_pid4092.txt](https://github.com/elastic/elasticsearch/files/4601639/hs_err_pid4092.txt)

**Comment by original-brownbear** [comment] 2020-05-09 08:44
Hi @lytvynenko-dmitriy 

this does not look like an Elasticsearch bug to me. What you're seeing:

```
siginfo: EXCEPTION_IN_PAGE_ERROR (0xc0000006), reading address 0x00000197d0c8a000
```

is likely the result of your network file system failing to execute a write by Elasticsearch, leading to the JVM failing on this exception on the next access to whatever file failed to write. Note that it is generally not advisable to run Elasticsearch on a NFS. You can find more information on this in this [thread](https://discuss.elastic.co/t/why-nfs-is-to-be-avoided-for-data-directories/215240) on our discuss forums.
Since we try to limit Github to feature requests and confirmed bugs I hope you don't mind that I'm going to close this issue. If you want to further discuss this or other topics that aren't necessarily confirmed bugs I would refer you to the above linked discuss forums.

**Closed by original-brownbear** 2020-05-09 08:44 UTC
Labels: >bug, needs:triage
