### ISSUE TITLE
[CI] ResetJobIT testReset failing

### ISSUE THREAD

**Issue by slobodanadamovic** [elastic/elasticsearch#89644] opened 2022-08-26 09:50 UTC
```

[2022-07-13T09:28:01,484][ERROR][o.e.x.m.d.DataFrameAnalyticsTask] [javaRestTest-2] [test_model_memory_limit_lower_than_estimated_memory_usage] Setting task to failed org.elasticsearch.ElasticsearchException: [test_model_memory_limit_lower_than_estimated_memory_usage] analytics/12724 process stopped unexpectedly: Input error: memory limit [1 mb] has been exceeded. Please force stop the job, increase to new estimated limit [3 mb] and restart. |  
-- | --
  | »  	at org.elasticsearch.xcore@8.4.0-SNAPSHOT/org.elasticsearch.xpack.core.ml.utils.ExceptionsHelper.serverError(ExceptionsHelper.java:61) |  
  | »  	at org.elasticsearch.xpack.ml.dataframe.process.AnalyticsProcessManager.processData(AnalyticsProcessManager.java:232) |  
  | »  	at org.elasticsearch.xpack.ml.dataframe.process.AnalyticsProcessManager.lambda$runJob$1(AnalyticsProcessManager.java:153) |  
  | »  	at org.elasticsearch.server@8.4.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:710) |  
  | »  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) |  
  | »  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) |  
  | »  	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Build scan:**
https://gradle-enterprise.elastic.co/s/jpakm3keu7zsq/tests/:x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest/org.elasticsearch.xpack.ml.integration.ResetJobIT/testReset

**Reproduction line:**
`gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.ml.integration.ResetJobIT.testReset" -Dtests.seed=219F87BCE4E842F2 -Dtests.locale=sr-Latn-BA -Dtests.timezone=Africa/Mogadishu -Druntime.java=18`

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ml.integration.ResetJobIT&tests.test=testReset

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: "Job has been reset"
     but: was "Job is closing"

  at __randomizedtesting.SeedInfo.seed([219F87BCE4E842F2:4ABAA518012329D2]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.xpack.ml.integration.ResetJobIT.testReset(ResetJobIT.java:72)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:577)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by dimitris-athanasiou** [comment] 2022-08-26 12:28
The error message at the top, coming from `DataFrameAnalyticsTask` is irrelevant. Looking into this.

**Comment by dimitris-athanasiou** [comment] 2022-08-26 13:20
I looked at this. Nothing seems out of the ordinary. Here are the relevant logs:

```
[2022-08-26T09:32:10,947][INFO ][o.e.x.m.j.p.a.AutodetectProcessManager] [javaRestTest-2] Opening job [test-reset]
[2022-08-26T09:32:10,948][INFO ][o.e.x.c.m.u.MlIndexAndAlias] [javaRestTest-2] About to create first concrete index [.ml-state-000001] with alias [.ml-state-write]
[2022-08-26T09:32:10,994][INFO ][o.e.c.m.MetadataCreateIndexService] [javaRestTest-2] [.ml-state-000001] creating index, cause [api], templates [.ml-state], shards [1]/[1]
[2022-08-26T09:32:11,235][INFO ][o.e.x.m.j.p.a.AutodetectProcessManager] [javaRestTest-2] [test-reset] Loading model snapshot [N/A], job latest_record_timestamp [N/A]
[2022-08-26T09:32:11,291][INFO ][o.e.x.i.IndexLifecycleTransition] [javaRestTest-2] moving index [.ml-state-000001] from [null] to [{"phase":"new","action":"complete","name":"complete"}] in policy [ml-size-based-ilm-policy]
[2022-08-26T09:32:11,380][INFO ][o.e.x.i.IndexLifecycleTransition] [javaRestTest-2] moving index [.ml-state-000001] from [{"phase":"new","action":"complete","name":"complete"}] to [{"phase":"hot","action":"unfollow","name":"branch-check-unfollow-prerequisites"}] in policy [ml-size-based-ilm-policy]
[2022-08-26T09:32:11,434][INFO ][o.e.c.r.a.AllocationService] [javaRestTest-2] current.health="GREEN" message="Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[.ml-state-000001][0], [.ml-notifications-000002][0]]])." previous.health="YELLOW" reason="shards started [[.ml-state-000001][0], [.ml-notifications-000002][0]]"
[2022-08-26T09:32:11,483][INFO ][o.e.x.i.IndexLifecycleTransition] [javaRestTest-2] moving index [.ml-state-000001] from [{"phase":"hot","action":"unfollow","name":"branch-check-unfollow-prerequisites"}] to [{"phase":"hot","action":"rollover","name":"check-rollover-ready"}] in policy [ml-size-based-ilm-policy]
[2022-08-26T09:32:11,716][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [javaRestTest-2] [test-reset] [autodetect/10208] [CResourceMonitor.cc@84] Setting model memory limit to 1024 MB
[2022-08-26T09:32:11,770][INFO ][o.e.c.m.MetadataMappingService] [javaRestTest-2] [.ml-anomalies-shared/o2dEfb9WQ5GzNgIvBWURKQ] update_mapping [_doc]
[2022-08-26T09:32:11,990][INFO ][o.e.x.m.j.p.DataCountsReporter] [javaRestTest-2] [test-reset] 10000 records written to autodetect; missingFieldCount=0, invalidDateCount=0, outOfOrderCount=0
[2022-08-26T09:32:12,068][INFO ][o.e.x.m.j.p.a.AutodetectProcessManager] [javaRestTest-2] Closing job [test-reset], because [close job (api)]
[2022-08-26T09:32:12,069][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [javaRestTest-2] [test-reset] [autodetect/10208] [CCmdSkeleton.cc@66] Handled 11254 records
[2022-08-26T09:32:12,069][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [javaRestTest-2] [test-reset] [autodetect/10208] [CAnomalyJob.cc@1598] Pruning obsolete models
[2022-08-26T09:32:12,150][INFO ][o.e.x.m.p.AbstractNativeProcess] [javaRestTest-2] [test-reset] State output finished
[2022-08-26T09:32:12,311][INFO ][o.e.c.m.MetadataMappingService] [javaRestTest-2] [.ml-anomalies-shared/o2dEfb9WQ5GzNgIvBWURKQ] update_mapping [_doc]
[2022-08-26T09:32:12,427][INFO ][o.e.x.m.j.p.a.o.AutodetectResultProcessor] [javaRestTest-2] [test-reset] 100 buckets parsed from autodetect output
[2022-08-26T09:32:12,628][INFO ][o.e.x.m.j.p.a.AutodetectCommunicator] [javaRestTest-2] [test-reset] autodetect connection for job closed
[2022-08-26T09:32:12,810][INFO ][o.e.x.m.a.TransportResetJobAction] [javaRestTest-2] [test-reset] Resetting job
[2022-08-26T09:32:12,994][INFO ][o.e.x.m.j.p.JobDataDeleter] [javaRestTest-2] [test-reset] running delete by query on [.ml-anomalies-shared]
[2022-08-26T09:32:13,275][INFO ][o.e.x.m.a.TransportResetJobAction] [javaRestTest-2] [test-reset] Reset has successfully completed
```

The job seems to be first closing, then resetting. I have raised #89653 to show the fetched audit messages when that assertion fails. This might help reveal the issue.

**Comment by joegallo** [comment] 2022-11-29 14:49
https://gradle-enterprise.elastic.co/s/iahpminiqzhi4/tests/:x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest/org.elasticsearch.xpack.ml.integration.ResetJobIT/testReset?top-execution=1

Just hit this one today.

**Comment by dimitris-athanasiou** [comment] 2022-11-29 14:54
The failure above with the added assertion message was:

```
java.lang.AssertionError: Audit messages: [Job created, Opening job on node [javaRestTest-2], Loading model snapshot [N/A], job latest_record_timestamp [N/A], Job is closing]	
Expected: "Job has been reset"
     but: was "Job is closing"

  at __randomizedtesting.SeedInfo.seed([219F87BCE4E842F2:4ABAA518012329D2]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.xpack.ml.integration.ResetJobIT.testReset(ResetJobIT.java:72)
```

**Comment by cbuescher** [comment] 2023-03-10 09:55
Another one today on 8.6., the Audit message above reads the same:
```
java.lang.AssertionError: Audit messages: [Job created, Opening job on node [javaRestTest-1], Loading model snapshot [N/A], job latest_record_timestamp [N/A], Job is closing] |  
```
https://gradle-enterprise.elastic.co/s/r4bsajgsemupy/tests/:x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest/org.elasticsearch.xpack.ml.integration.ResetJobIT/testReset?top-execution=1

**Comment by droberts195** [comment] 2023-10-10 11:12
Assigning `low-risk` as the test isn't muted and fails incredibly rarely.

**Comment by edsavage** [comment] 2024-10-18 03:47
I suspect that the changes in #106020 have made the test more robust.

Whatever the reason I'm unable to reproduce this failure after many hundreds of iterations, hence closing the issue.

**Closed by edsavage** 2024-10-18 03:47 UTC
Labels: >test-failure, :ml, Team:ML, low-risk
