### ISSUE TITLE
Remove node.local and node.mode

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#12793] opened 2015-08-11 04:04 UTC
These settings parallel each other and are also confusing with `transport.type`. This causes problems in tests sometimes since we randomize the first two settings. So if a test wants to rely on, eg always using netty, it has to remember to set *two* settings, to make sure randomization doesn't mess this up. And if the test forgets one, it can have weird consequences, like the wrong transport address instance being created, causing class cast exceptions like in #12788.

I think we should minimize these to as single setting (preferably `transport.type` since that is the pluggable setting).

**Comment by clintongormley** [comment] 2016-01-26 18:37
Duplicate of https://github.com/elastic/elasticsearch/issues/16234

**Closed by clintongormley** 2016-01-26 18:37 UTC
Labels: discuss
