### ISSUE TITLE
DiscoveryModule is very slow (3min +)

### ISSUE THREAD

**Issue by Colossus1983** [elastic/elasticsearch#24549] opened 2017-05-08 14:08 UTC
**Elasticsearch version**: 
5.4.0

**Plugins installed**: 
None

**JVM version** :
 1.8.0_131

**OS version**:
 Windows Server 2012 R2

**Description of the problem including expected versus actual behavior**: 
I just did a rolling upgrade from version 5.1.1 to 5.4.0, everything went okay. Cluster is green again.
Only on all the nodes the following command takes more then 3 minutes:
[2017-05-08T16:01:07,568][INFO ][o.e.d.DiscoveryModule    ] [NODE] using discovery type [zen]
[2017-05-08T16:04:31,676][INFO ][o.e.n.Node               ] [NODE] initialized

The timeout settings i have: 
discovery.zen.fd.ping_timeout: 5s
transport.tcp.connect_timeout: 5s

Other relevant information:
I'm using **network.bind_host** and **network_publish_host** to make sure i only loopback 1 IP

**Comment by bleskes** [comment] 2017-05-08 14:14
Thx @Colossus1983 . Quite a lot happens between the log line in the discovery module (which doesn't do much at that stage) and the initialized message, so this can be many things. I would recommend turning on debug logging to get more information. Also, as we will be happy to help you debug further on our forums at discuss.elastic.co . Once, and if, we resolve it to a concrete issue with some component we can open a github ticket for that. I will be closing this ticket for now.

**Comment by jasontedor** [comment] 2017-05-08 14:14
Discovery does not happen between those two log lines, it happens later. To debug this, you need to take a stack dump (use `jstack`) when the node is hung between those two long lines. Grab a few to make sure the node is stuck doing the same thing. I doubt there's a bug here though, probably an environment problem, so your best bet is to go the [forum](https://discuss.elastic.co).

**Closed by bleskes** 2017-05-08 14:14 UTC

**Comment by Colossus1983** [comment] 2017-05-08 14:31
Aah sorry for the wrong location of this issue.
I see now that the indexes keep upgrading. 
So i will look into that. Thank you for the tip

**Comment by jasontedor** [comment] 2017-05-08 15:35
No apology necessary. It's reasonable for someone not versed in the code to think there is a bug here, and this is the right place to open bug reports. We can tell right away it's probably not a bug and only an environment problem and we prefer to handle those on the forum.
