### ISSUE TITLE
Ability to delete deleted documents

### ISSUE THREAD

**Issue by antonpious** [elastic/elasticsearch#30237] opened 2018-04-29 16:57 UTC
There should be a way to delete all deleted documents by having the other details constant.

Due to the immutability of a segment in Lucene, the current way for a document that is updated is to keep the existing document in the segment in which it was created and to put the updated document in a new segment. Over the period of time if this continues the number of deleted documents grows significantly. The similar is the case of documents which are deleted which unfortunately is very less.

The cluster tries to control the optimum segment count by its own algorithm which currently is not explicitly based on deleted document size. The segment count is also optimized for what the cluster feels should be the segment count of the index for efficient read and write.

What is needed is to delete only the deleted documents which is unfortunately tied to reducing the segment count which would eventually remove the deleted document which are there in the segment. This would also expose large segments when segments are merged as well as no control on how many deleted documents should be cleaned and its random. The only way to recover space for all deleted documents is to force merge to 1 segment which if the cluster felt is the right way it should have done it. The cluster never has this logic of force merging to only 1 segment so why should the customer be told to do force merge to 1 segment to remove deleted documents.

The way it should work is to give a specific API to clean deleted documents. It should do just that.

The migrate API is doing the deleted documents correctly and should be the basis for this feature. The migrate API copies all the data from one index to the other by doesn't copy the deleted documents. So the delete api should be based on this, keep existing segment counts as it is but copy over only the current documents

**Comment by bleskes** [comment] 2018-05-01 09:04
@antonpious removing deletes can be expensive which is why Lucene is not aggressively doing it but rather tries to inline it with the normal merging process (it waits until segments are 10% deleted before trying to merge them away due to that). You do not have the option to only remove deletes from segments because it's inefficient - if you're already copying segment data, you might as well take to opportunity to merge that. You do have the option to only merge segments with deletes in them see `only_expunge_deletes` [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-forcemerge.html) .

All of that said - if all indexing stops, a single segment is the best storage option. 

I'm going to close this as this works as intended and I don't see (yet) the need to change it. I'm curious to know what problem you are trying to solve. I suggest you open a discussion on https://discuss.elastic.co/ and link to here. If we end up concluding that something in ES needs to change we can reopen the issue.

**Closed by bleskes** 2018-05-01 09:04 UTC
Labels: :Distributed/Engine
