### ISSUE TITLE
ESQL: More memory accounting improvements

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#102267] opened 2023-11-16 00:12 UTC
Extends https://github.com/elastic/elasticsearch/issues/99173
- [ ] block referencing
- [ ] Filter blocks
- [ ] Expand blocks
- [ ] enrich memory accounting
- [ ] Remove Block.Ref
- [ ] Remove nonBreakingBlockFactory
- [ ] Remove deprecated Block methods

**Comment by alex-spies** [comment] 2023-11-16 08:25
@dnhatn , I'll happily take the filter+expand blocks as follow-ups to the general refcounting.
As previously discussed, I'd love your help esp. on Block.Ref as that one profits from good knowledge on the implicit ownership of blocks during evaluation.

**Comment by dnhatn** [comment] 2023-11-17 00:05
>  I'll happily take the filter+expand blocks as follow-ups to the general refcounting.

++, please go ahead. Thank you, Alex!

**Comment by alex-spies** [comment] 2023-11-17 08:38
Duplicate of https://github.com/elastic/elasticsearch/issues/100528

**Closed by alex-spies** 2023-11-17 08:38 UTC
Labels: Team:QL, :Query Languages/ES|QL
