### ISSUE TITLE
bug report: select not return all document after index

### ISSUE THREAD

**Issue by LYKZZzz** [elastic/elasticsearch#32186] opened 2018-07-19 06:06 UTC
**Elasticsearch version** : 6.3.1

**Plugins installed**: null

**JVM version** (`java -version`): 10.0.1

**OS version** : windows7 64bit

**Description of the problem including expected versus actual behavior**:
I am using RestHighLevelClient to index documents and search them, when I create an index and put some JSON document in it and then search them, some of document will not be returned, seems like client.index() execute asynchronously. If this is not a bug, would you like to tell me how to know whether all documents have been indexed, thank you!

**Steps to reproduce**:

the java program will throw AssertError:
```Java
import com.alibaba.fastjson.JSON;
import org.apache.http.HttpHost;
import org.elasticsearch.action.admin.indices.create.CreateIndexRequest;
import org.elasticsearch.action.admin.indices.delete.DeleteIndexRequest;
import org.elasticsearch.action.admin.indices.get.GetIndexRequest;
import org.elasticsearch.action.index.IndexRequest;
import org.elasticsearch.action.search.SearchRequest;
import org.elasticsearch.action.search.SearchResponse;
import org.elasticsearch.client.RestClient;
import org.elasticsearch.client.RestHighLevelClient;
import org.elasticsearch.common.xcontent.XContentType;
import org.elasticsearch.index.query.QueryBuilders;
import org.elasticsearch.search.builder.SearchSourceBuilder;
import java.io.IOException;
import java.util.Vector;

public class Test {
    public static void main(String[] args) throws IOException, InterruptedException {
        // init client and create index "test" (delete it if already exist)
        RestHighLevelClient client = new RestHighLevelClient(RestClient.builder(new HttpHost("localhost", 9200, "http")));
        GetIndexRequest getIndexRequest = new GetIndexRequest();
        getIndexRequest.indices("test");
        if (client.indices().exists(getIndexRequest)){
            DeleteIndexRequest clearAllData = new DeleteIndexRequest("test");
            client.indices().delete(clearAllData);
        }
        CreateIndexRequest createIndexRequest = new CreateIndexRequest("test");
        client.indices().create(createIndexRequest);

        // generate test data
        Vector<WebPageData> testData = new Vector<>();
        for (int i = 0; i < 10; i++){
            WebPageData data = new WebPageData();
            Vector<String> tags = new Vector<>();
            tags.add("test" + i);
            data.setUrl(i + ".html");
            data.setTitle(i + "ttest");
            data.setPrice(i + 100);
            data.setChildPrice(i + 50);
            data.setTags(tags);
            testData.add(data);
        }

        // index 10 json document
        for (WebPageData i : testData) {
            IndexRequest indexRequest = new IndexRequest("test", "doc");
            indexRequest.source(JSON.toJSONString(i), XContentType.JSON);
            client.index(indexRequest);
        }

        // if sleep 1s, everything looks good
        //Thread.sleep(1000);

        // search all doc in index "test"
        SearchRequest searchRequest = new SearchRequest("test");
        SearchSourceBuilder searchSourceBuilder = new SearchSourceBuilder();
        searchSourceBuilder.query(QueryBuilders.matchAllQuery());
        searchRequest.source(searchSourceBuilder);
        SearchResponse searchResponse = client.search(searchRequest);
        System.out.println(searchResponse.getHits().totalHits);

        // totalHits == 10 should be true
        if (searchResponse.getHits().totalHits != 10){
            throw new AssertionError();
        }
    }
}
```
**WebPageData** is a JavaBean class:
```Java
import java.util.Vector;

public class WebPageData {
    private String title;
    private String url;
    private int price;
    private int childPrice;
    private Vector<String> tags;

    // omit set and get

}
```

**Comment by tvernum** [comment] 2018-07-19 06:52
Please read
- https://www.elastic.co/guide/en/elasticsearch/reference/6.3/_basic_concepts.html#_near_realtime_nrt
- https://www.elastic.co/guide/en/elasticsearch/reference/6.3/indices-refresh.html

If you have any further questions, please ask on our [discuss forum](https://discuss.elastic.co/c/elasticsearch) where we can provide better support. Those forums are designed to support the kinds of conversations that are necessary for this sort of troubleshooting and problem diagnosis.

Elastic uses GitHub issues for tracking clearly identified bugs and feature requests. Since the issue you raise is not a bug, I hope you don't mind if I close this ticket.

Thank you.

**Closed by tvernum** 2018-07-19 06:52 UTC
