### ISSUE TITLE
GoogleCloudStorageRepositoryClientYamlTestSuiteIT failing

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#57115] opened 2020-05-25 11:46 UTC
**Build scan**:

[6.8.10] https://gradle-enterprise.elastic.co/s/4rvjvn5vxbs2c
https://gradle-enterprise.elastic.co/s/bp66r3rbnidcm

**Repro line**:

```
REPRODUCE WITH: ./gradlew ':plugins:repository-gcs:qa:google-cloud-storage:largeBlobIntegTestRunner' --tests "org.elasticsearch.repositories.gcs.GoogleCloudStorageRepositoryClientYamlTestSuiteIT.test {yaml=repository_gcs/10_repository/Snapshot/Restore with repository-gcs}" \
  -Dtests.seed=E87E0CDC9EE08B9D \
  -Dtests.security.manager=true \
  -Dtests.locale=es-GT \
  -Dtests.timezone=PRC \
  -Dcompiler.java=14 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew ':plugins:repository-gcs:qa:google-cloud-storage:largeBlobIntegTestRunner' --tests "org.elasticsearch.repositories.gcs.GoogleCloudStorageRepositoryClientYamlTestSuiteIT.test {yaml=repository_gcs/10_repository/Snapshot/Restore with repository-gcs}" \
  -Dtests.seed=E87E0CDC9EE08B9D \
  -Dtests.security.manager=true \
  -Dtests.locale=es-GT \
  -Dtests.timezone=PRC \
  -Dcompiler.java=14 \
  -Druntime.java=8
```

**Reproduces locally?**:

No

**Applicable branches**:

7.7

**Failure history**:

Not sure if this is the exact same failure, but there were occasional failures of `GoogleCloudStorageRepositoryClientYamlTestSuiteIT` for at least a few months.

**Failure excerpt**:

```
11:18:51 org.elasticsearch.repositories.gcs.GoogleCloudStorageRepositoryClientYamlTestSuiteIT > test {yaml=repository_gcs/10_repository/Snapshot/Restore with repository-gcs} FAILED
11:18:51     java.lang.AssertionError: Failure at [repository_gcs/10_repository:129]: snapshot.state didn't match expected value:
11:18:51                     snapshot.state: expected String [SUCCESS] but was String [PARTIAL]
11:18:51         at __randomizedtesting.SeedInfo.seed([E87E0CDC9EE08B9D:602A3306301CE665]:0)
11:18:51         at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:405)
11:18:51         at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:382)
11:18:51         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:18:51         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11:18:51         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:18:51         at java.lang.reflect.Method.invoke(Method.java:498)
11:18:51         at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
11:18:51         at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
11:18:51         at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
11:18:51         at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
11:18:51         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
11:18:51         at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
11:18:51         at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
11:18:51         at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
11:18:51         at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
11:18:51         at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
11:18:51         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
11:18:51         at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
11:18:51         at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
11:18:51         at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
11:18:51         at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
11:18:51         at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
11:18:51         at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
11:18:51         at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
11:18:51         at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
11:18:51         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
11:18:51         at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
11:18:51         at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
11:18:51         at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
11:18:51         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
11:18:51         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
11:18:51         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
11:18:51         at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
11:18:51         at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
11:18:51         at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
11:18:51         at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
11:18:51         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
11:18:51         at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
11:18:51         at java.lang.Thread.run(Thread.java:748)
11:18:51 
11:18:51         Caused by:
11:18:51         java.lang.AssertionError: snapshot.state didn't match expected value:
11:18:51                         snapshot.state: expected String [SUCCESS] but was String [PARTIAL]
11:18:51             at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:93)
11:18:51             at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:76)
11:18:51             at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:398)
11:18:51             ... 38 more
```

**Comment by original-brownbear** [comment] 2020-05-25 12:20
This should be fixed by #57073 ... will backport the fix further to fix this

**Comment by original-brownbear** [comment] 2020-05-27 08:58
I opened backport PRs to 7.7 #57191  and 7.8 #57192 for the above fix, closing here

**Comment by original-brownbear** [comment] 2020-05-27 20:04
Still failing https://gradle-enterprise.elastic.co/s/ufloccejuphoe ... I'll take another look tomorrow

**Comment by original-brownbear** [comment] 2020-05-28 09:05
I'm beginning to think that this is a bug in the JDK's `HttpServer` in some way. I added logging to the docker container and was able to reproduce this:

For the server/docker-container this is logged:

```
May 28 10:53:31 pc-168 914f5cf1f596[26399]: java.io.IOException: connection closed before all data received
May 28 10:53:31 pc-168 914f5cf1f596[26399]:         at sun.net.httpserver.FixedLengthInputStream.readImpl(FixedLengthInputStream.java:64) ~[jdk.httpserver:?]
May 28 10:53:31 pc-168 914f5cf1f596[26399]:         at sun.net.httpserver.LeftOverInputStream.read(LeftOverInputStream.java:87) ~[jdk.httpserver:?]
May 28 10:53:31 pc-168 914f5cf1f596[26399]:         at fixture.gcs.GoogleCloudStorageHttpHandler.handle(GoogleCloudStorageHttpHandler.java:249) ~[gcs-fixture-7.9.0-SNAPSHOT.jar:7.9.0-SNAPSHOT]
May 28 10:53:31 pc-168 914f5cf1f596[26399]:         at fixture.gcs.GoogleCloudStorageHttpFixture.lambda$new$1(GoogleCloudStorageHttpFixture.java:58) [gcs-fixture-7.9.0-SNAPSHOT.jar:7.9.0-SNAPSHOT]
May 28 10:53:31 pc-168 914f5cf1f596[26399]:         at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77) [jdk.httpserver:?]
May 28 10:53:31 pc-168 914f5cf1f596[26399]:         at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82) [jdk.httpserver:?]
May 28 10:53:31 pc-168 914f5cf1f596[26399]:         at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80) [jdk.httpserver:?]
May 28 10:53:31 pc-168 914f5cf1f596[26399]:         at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:692) [jdk.httpserver:?]
May 28 10:53:31 pc-168 914f5cf1f596[26399]:         at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77) [jdk.httpserver:?]
May 28 10:53:31 pc-168 914f5cf1f596[26399]:         at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:664) [jdk.httpserver:?]
May 28 10:53:31 pc-168 914f5cf1f596[26399]:         at fixture.gcs.GoogleCloudStorageHttpFixture.lambda$new$0(GoogleCloudStorageHttpFixture.java:47) [gcs-fixture-7.9.0-SNAPSHOT.jar:7.9.0-SNAPSHOT]
May 28 10:53:31 pc-168 914f5cf1f596[26399]:         at sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:442) [jdk.httpserver:?]
May 28 10:53:31 pc-168 914f5cf1f596[26399]:         at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:408) [jdk.httpserver:?]
May 28 10:53:31 pc-168 914f5cf1f596[26399]:         at java.lang.Thread.run(Thread.java:834) [?:?]
May 28 10:53:31 pc-168 914f5cf1f596[26399]: [2020-05-28T08:53:31,334][INFO ][fixture.gcs.GoogleCloudSto
```

while on the client-side/es this is logged:

```
» WARN ][o.e.s.SnapshotShardsService] [largeBlobIntegTest-0] [[docs][0]][repository:snapshot-two/tho835F8SN2PRkbLnhLyHQ] failed to snapshot shard
»  com.google.cloud.storage.StorageException: Socket Closed
»       at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:229) ~[?:?]
»       at com.google.cloud.storage.spi.v1.HttpStorageRpc.write(HttpStorageRpc.java:776) ~[?:?]
»       at com.google.cloud.storage.BlobWriteChannel$1.run(BlobWriteChannel.java:60) ~[?:?]
»       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_201]
»       at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105) ~[?:?]
»       at com.google.cloud.RetryHelper.run(RetryHelper.java:76) ~[?:?]
»       at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50) ~[?:?]
»       at com.google.cloud.storage.BlobWriteChannel.flushBuffer(BlobWriteChannel.java:53) ~[?:?]
»       at com.google.cloud.BaseWriteChannel.close(BaseWriteChannel.java:151) ~[?:?]
»       at org.elasticsearch.repositories.gcs.SocketAccess.lambda$doPrivilegedVoidIOException$0(SocketAccess.java:54) ~[?:?]
»       at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
»       at org.elasticsearch.repositories.gcs.SocketAccess.doPrivilegedVoidIOException(SocketAccess.java:53) ~[?:?]
»       at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore$1.close(GoogleCloudStorageBlobStore.java:292) ~[?:?]
»       at java.nio.channels.Channels$1.close(Channels.java:178) ~[?:1.8.0_201]
»       at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:104) ~[elasticsearch-core-7.9.0-SNAPSHOT.jar:7.9.0-SNAPSHOT]
»       at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:74) ~[elasticsearch-core-7.9.0-SNAPSHOT.jar:7.9.0-SNAPSHOT]
»       at org.elasticsearch.core.internal.io.Streams.copy(Streams.java:64) ~[elasticsearch-core-7.9.0-SNAPSHOT.jar:7.9.0-SNAPSHOT]
»       at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore.writeBlobResumable(GoogleCloudStorageBlobStore.java:277) ~[?:?]
»       at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore.writeBlob(GoogleCloudStorageBlobStore.java:243) ~[?:?]
»       at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobContainer.writeBlob(GoogleCloudStorageBlobContainer.java:72) ~[?:?]
»       at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobContainer.writeBlobAtomic(GoogleCloudStorageBlobContainer.java:77) ~[?:?]
»       at org.elasticsearch.repositories.blobstore.ChecksumBlobStoreFormat.lambda$writeAtomic$0(ChecksumBlobStoreFormat.java:166) ~[elasticsearch-7.9.0-SNAPSHOT.jar:7.9.0-SNAPSHOT]
»       at org.elasticsearch.repositories.blobstore.ChecksumBlobStoreFormat.writeTo(ChecksumBlobStoreFormat.java:213) ~[elasticsearch-7.9.0-SNAPSHOT.jar:7.9.0-SNAPSHOT]
»       at org.elasticsearch.repositories.blobstore.ChecksumBlobStoreFormat.writeAtomic(ChecksumBlobStoreFormat.java:164) ~[elasticsearch-7.9.0-SNAPSHOT.jar:7.9.0-SNAPSHOT]
»       at org.elasticsearch.repositories.blobstore.BlobStoreRepository.writeShardIndexBlob(BlobStoreRepository.java:2075) ~[elasticsearch-7.9.0-SNAPSHOT.jar:7.9.0-SNAPSHOT]
»       at org.elasticsearch.repositories.blobstore.BlobStoreRepository.lambda$snapshotShard$61(BlobStoreRepository.java:1812) ~[elasticsearch-7.9.0-SNAPSHOT.jar:7.9.0-SNAPSHOT]
»       at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) ~[elasticsearch-7.9.0-SNAPSHOT.jar:7.9.0-SNAPSHOT]
»       at org.elasticsearch.common.util.concurrent.ListenableFuture$1.doRun(ListenableFuture.java:112) ~[elasticsearch-7.9.0-SNAPSHOT.jar:7.9.0-SNAPSHOT]
»       at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.9.0-SNAPSHOT.jar:7.9.0-SNAPSHOT]
»       at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:226) ~[elasticsearch-7.9.0-SNAPSHOT.jar:7.9.0-SNAPSHOT]
»       at org.elasticsearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:106) ~[elasticsearch-7.9.0-SNAPSHOT.jar:7.9.0-SNAPSHOT]
»       at org.elasticsearch.common.util.concurrent.ListenableFuture.lambda$done$0(ListenableFuture.java:98) ~[elasticsearch-7.9.0-SNAPSHOT.jar:7.9.0-SNAPSHOT]
»       at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_201]
»       at org.elasticsearch.common.util.concurrent.ListenableFuture.done(ListenableFuture.java:98) [elasticsearch-7.9.0-SNAPSHOT.jar:7.9.0-SNAPSHOT]
»       at org.elasticsearch.common.util.concurrent.BaseFuture.set(BaseFuture.java:144) [elasticsearch-7.9.0-SNAPSHOT.jar:7.9.0-SNAPSHOT]
»       at org.elasticsearch.common.util.concurrent.ListenableFuture.onResponse(ListenableFuture.java:127) [elasticsearch-7.9.0-SNAPSHOT.jar:7.9.0-SNAPSHOT]
»       at org.elasticsearch.action.StepListener.innerOnResponse(StepListener.java:62) [elasticsearch-7.9.0-SNAPSHOT.jar:7.9.0-SNAPSHOT]
»       at org.elasticsearch.action.NotifyOnceListener.onResponse(NotifyOnceListener.java:40) [elasticsearch-7.9.0-SNAPSHOT.jar:7.9.0-SNAPSHOT]
»       at org.elasticsearch.action.support.GroupedActionListener.onResponse(GroupedActionListener.java:66) [elasticsearch-7.9.0-SNAPSHOT.jar:7.9.0-SNAPSHOT]
»       at org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:89) [elasticsearch-7.9.0-SNAPSHOT.jar:7.9.0-SNAPSHOT]
»       at org.elasticsearch.action.ActionRunnable$1.doRun(ActionRunnable.java:46) [elasticsearch-7.9.0-SNAPSHOT.jar:7.9.0-SNAPSHOT]
»       at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:695) [elasticsearch-7.9.0-SNAPSHOT.jar:7.9.0-SNAPSHOT]
»       at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.9.0-SNAPSHOT.jar:7.9.0-SNAPSHOT]
»       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
»       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
»       at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
»  Caused by: java.io.IOException: Socket Closed
»       at java.net.AbstractPlainSocketImpl.getInputStream(AbstractPlainSocketImpl.java:421) ~[?:1.8.0_201]
»       at java.net.Socket$2.run(Socket.java:914) ~[?:1.8.0_201]
»       at java.net.Socket$2.run(Socket.java:912) ~[?:1.8.0_201]
»       at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
»       at java.net.Socket.getInputStream(Socket.java:911) ~[?:1.8.0_201]
»       at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:673) ~[?:?]
»       at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587) ~[?:?]
»       at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[?:?]
»       at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[?:1.8.0_201]
»       at com.google.api.client.http.javanet.NetHttpResponse.<init>(NetHttpResponse.java:36) ~[?:?]
»       at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:149) ~[?:?]
»       at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:84) ~[?:?]
»       at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1012) ~[?:?]
»       at com.google.cloud.storage.spi.v1.HttpStorageRpc.write(HttpStorageRpc.java:753) ~[?:?]

```

Since this does not happen in tests running the http server in the test JVM, it seems more likely that the issue is with the networking on the server side. I'll try to investigate this some more.

**Comment by original-brownbear** [comment] 2020-05-29 15:20
This only ever fails on 7.x and Java 8. Since the code is the same between master and 7.x I'm starting to think this might be an issue with the Java HTTP client ... like e.g. https://bugs.openjdk.java.net/browse/JDK-8240275

**Comment by davidkyle** [comment] 2020-06-01 13:27
Some more failures on both 7.7 and 7.8. Java 8 again.

https://gradle-enterprise.elastic.co/s/hdrmhpnp7ltlu
https://gradle-enterprise.elastic.co/s/vh5qvobca7n3k
https://gradle-enterprise.elastic.co/s/yp2tpuuaj6wdm
https://gradle-enterprise.elastic.co/s/qru4z2n5zqhem

Muted on 7.8 edeac408e55408d70e0837e5fd766a53a4c3536b
Muted on 7.7 599e2dd1ca878472daef056081f8945354e1b4fb

**Comment by markharwood** [comment] 2020-06-03 12:27
Happened on 7.x Java8 today.
https://gradle-enterprise.elastic.co/s/wlvfly5dd225w

Muted 7.x with e2c0c4197f550e7b5fe7c243bcd8d40e27310b5f

**Comment by fcofdez** [comment] 2020-06-03 17:14
Maybe we can try to use the apache http transport to confirm this is a Java HTTP client issue?

**Comment by original-brownbear** [comment] 2020-06-04 16:01
@fcofdez 

> Maybe we can try to use the apache http transport to confirm this is a Java HTTP client issue?

Yea we could I think but it's quite a bit of effort potentially (I haven't checked the details, might be it works out of the box but I know we do some trickery around the SSL handling in the client and I'm not sure how that has to be transferred to the Apache client). I wonder if we haven't already confirmed this to some (enough?) degree though by isolating it to Java-8.  That said, I'm not opposed to experimenting with the Apache client implementation in general. If it's an easy thing to swap out it's definitely interesting to look into the effects of it.

**Comment by original-brownbear** [comment] 2020-06-09 13:08
I looked into the above again and was able to reproduce this issue in a unit test now. Somehow the JDK8 http client is closing the connection where newer JDK's clients don't close it. It's fairly easy to reproduce this by removing the JDK8 exclusion from `GoogleCloudStorageBlobStoreRepositoryTests` and running it in a loop on JDK8 for a minute or two.

**Comment by original-brownbear** [comment] 2020-06-12 06:43
As discussed on Wednesday, I'm closing this one. It's unfortunate that bugs in JDK-8 show up like this and lower our test coverage but I don't see what we can do about this problem. We could move to the Apache HTTP client implementation to have more consistent behavior across JDK versions but that seems like a risky proposition since there's no guarantee that doesn't come with other instabilities.
Since we never observed this issue on Cloud in the real world => closing.

**Closed by original-brownbear** 2020-06-12 06:43 UTC
Labels: :Distributed/Snapshot/Restore, >test-failure, Team:Distributed
