### ISSUE TITLE
Highlighting - does not work with boosting.

### ISSUE THREAD

**Issue by chriszhangz** [elastic/elasticsearch#22086] opened 2016-12-09 19:20 UTC
**Elasticsearch version**:2.3.5

**Plugins installed**: [head,ik]

**JVM version**:1.8.0_92

**OS version**:Red Hat 4.8.3

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.Highlighting does not work with a boosting query.
 2.When I get rid of boosting it will works as expected.

**Provide logs (if relevant)**:

**Describe the feature**:
I found that Issue #1314 from september 2011 raises the same issue, has it perhaps reappeared?

**Comment by chriszhangz** [comment] 2016-12-09 21:25
@s1monw could you please help to check this out? I thought you already fixed it in past version but it happened again.

**Comment by clintongormley** [comment] 2016-12-12 13:25
@chriszhangz we ask for a replication because it is usually not obvious just from a description what you are doing.  You say that highlighting doesn't work with the boost query, but try this example and you can see that it does:

```
PUT t 
{
  "settings": {
    "number_of_shards": 1
  }
}

PUT t/t/1
{
  "text": "apple pie"
}

PUT t/t/2
{
  "text": "apple mac"
}


GET /_search
{
  "highlight": {
    "fields": {
      "text": {}
    }
  }, 
  "query": {
    "boosting": {
      "positive": {
        "match": {
          "text": "apple pie"
        }
      },
      "negative": {
        "match": {
          "text": "mac"
        }
      },
      "negative_boost": 0.2
    }
  }
}
```

If you mean, instead, that highlighting doesn't work when you boost particular fields in a query, then it may be a duplicate of this issue: https://github.com/elastic/elasticsearch/issues/21236

If neither of the above is correct, then please open a new issue with a recreation

**Closed by clintongormley** 2016-12-12 13:25 UTC
