### ISSUE TITLE
TransportSerializationException occurs when requesting stats

### ISSUE THREAD

**Issue by slixurd** [elastic/elasticsearch#24043] opened 2017-04-11 11:17 UTC
ES Version : 2.3.4
JDK: 1.7.0_76
ThreadPool is not modified
8 Nodes( 8 Core 16G mem)

When requesting /_stats, it will encounter failure
the request missing a lot of information (such as the infomation in indices.poi.primaries) with failure message
```   
"_shards": {
    "total": 28,
    "successful": 4,
    "failed": 24,
    "failures": [
      {
        "shard": 0,
        "index": "poi",
        "status": "INTERNAL_SERVER_ERROR",
        "reason": {
          "type": "failed_node_exception",
          "reason": "Failed node [01oKwFSRTk2E-zvq69k5jA]",
          "caused_by": {
            "type": "transport_serialization_exception",
            "reason": "Failed to deserialize response of type [org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$NodeResponse]",
            "caused_by": {
              "type": "index_out_of_bounds_exception",
              "reason": "Readable byte limit exceeded: 2364"
            }
          }
        }
      },
      {
        "shard": 0,
        "index": "poi",
        "status": "INTERNAL_SERVER_ERROR",
        "reason": {
          "type": "failed_node_exception",
          "reason": "Failed node [tI1TaFl2TGuTsYKQ_gl9eQ]",
          "caused_by": {
            "type": "transport_serialization_exception",
            "reason": "Failed to deserialize response of type [org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$NodeResponse]",
            "caused_by": {
              "type": "index_out_of_bounds_exception",
              "reason": "Readable byte limit exceeded: 2354"
            }
          }
        }
      },
.....
"indices": {
 "poi": {
      "primaries": {
      },
      "total": {
        "docs": {
          "count": 625,
          "deleted": 0
        }
       ....
}
```
And there is error stack in log
```
[DEBUG][action.admin.indices.stats] [search-node01] failed to execute [indices:monitor/stats] on node [01oKwFSRTk2E-zvq69k5jA]
RemoteTransportException[[Failed to deserialize response of type [org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$NodeResponse]]]; nested: TransportSerializationException[Failed to deserialize response of type [org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$NodeResponse]]; nested: IndexOutOfBoundsException[Readable byte limit exceeded: 2364];
Caused by: TransportSerializationException[Failed to deserialize response of type [org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$NodeResponse]]; nested: IndexOutOfBoundsException[Readable byte limit exceeded: 2364];
        at org.elasticsearch.transport.netty.MessageChannelHandler.handleResponse(MessageChannelHandler.java:180)
        at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:138)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Readable byte limit exceeded: 2364
        at org.jboss.netty.buffer.AbstractChannelBuffer.readByte(AbstractChannelBuffer.java:236)
        at org.elasticsearch.transport.netty.ChannelBufferStreamInput.readByte(ChannelBufferStreamInput.java:132)
        at org.elasticsearch.common.io.stream.FilterStreamInput.readByte(FilterStreamInput.java:39)
        at org.elasticsearch.common.io.stream.StreamInput.readString(StreamInput.java:254)
        at org.elasticsearch.index.search.stats.SearchStats.readFrom(SearchStats.java:311)
        at org.elasticsearch.index.search.stats.SearchStats.readSearchStats(SearchStats.java:299)
        at org.elasticsearch.action.admin.indices.stats.CommonStats.readFrom(CommonStats.java:527)
        at org.elasticsearch.action.admin.indices.stats.CommonStats.readCommonStats(CommonStats.java:484)
        at org.elasticsearch.action.admin.indices.stats.ShardStats.readFrom(ShardStats.java:97)
        at org.elasticsearch.action.admin.indices.stats.ShardStats.readShardStats(ShardStats.java:90)
        at org.elasticsearch.action.admin.indices.stats.TransportIndicesStatsAction.readShardResult(TransportIndicesStatsAction.java:80)
        at org.elasticsearch.action.admin.indices.stats.TransportIndicesStatsAction.readShardResult(TransportIndicesStatsAction.java:47)
        at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$NodeResponse.readFrom(TransportBroadcastByNodeAction.java:544)
        at org.elasticsearch.transport.netty.MessageChannelHandler.handleResponse(MessageChannelHandler.java:178)
        ... 23 more
```

**Comment by spinscale** [comment] 2017-04-11 13:39
thanks for your report. A couple of more information would be great, can you paste the output of

```
GET _cat/nodes?v&h=id,jdk,version,build,node.role,ram.*,heap.*
GET _cat/plugins
```

Just out of curiosity: there was no other exception before this happened the first time (like an OOM for example)?

**Comment by slixurd** [comment] 2017-04-12 03:11
1. _cat/node
```
id   jdk      version build   node.role ram.current ram.percent ram.max heap.current heap.percent heap.max 
8bgQ 1.7.0_76 2.3.4   e455fd0 d                                                                      7.3gb 
01oK 1.7.0_76 2.3.4   e455fd0 d                                                                      7.3gb 
AO3T 1.7.0_76 2.3.4   e455fd0 d                                                                      7.3gb 
AKHa 1.7.0_76 2.3.4   e455fd0 d                                                                      7.3gb 
RCC3 1.7.0_76 2.3.4   e455fd0 d              15.3gb          99  15.5gb        4.9gb           66    7.3gb 
td06 1.7.0_76 2.3.4   e455fd0 d                                                                      7.3gb 
tI1T 1.7.0_76 2.3.4   e455fd0 d                                                                      7.3gb 
t-xj 1.7.0_76 2.3.4   e455fd0 d                                                                      7.3gb 
```
The same error also result in the data loss
Only the local node return information
Error stack:
```
[2017-04-12 11:06:24,778][DEBUG][action.admin.cluster.node.stats] [search-node01] failed to execute on node [t-xjAafhQ3qFSsdEIHNwfA]
RemoteTransportException[[Failed to deserialize response of type [org.elasticsearch.action.admin.cluster.node.stats.NodeStats]]]; nested: TransportSerializationException[Failed to deserialize response of type [org.elasticsearch.action.admin.cluster.node.stats.NodeStats]]; nested: IndexOutOfBoundsException[Readable byte limit exceeded: 2690];
Caused by: TransportSerializationException[Failed to deserialize response of type [org.elasticsearch.action.admin.cluster.node.stats.NodeStats]]; nested: IndexOutOfBoundsException[Readable byte limit exceeded: 2690];
	at org.elasticsearch.transport.netty.MessageChannelHandler.handleResponse(MessageChannelHandler.java:180)
	at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:138)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Readable byte limit exceeded: 2690
	at org.jboss.netty.buffer.AbstractChannelBuffer.readByte(AbstractChannelBuffer.java:236)
	at org.elasticsearch.transport.netty.ChannelBufferStreamInput.readByte(ChannelBufferStreamInput.java:132)
	at org.elasticsearch.common.io.stream.FilterStreamInput.readByte(FilterStreamInput.java:39)
	at org.elasticsearch.common.io.stream.StreamInput.readString(StreamInput.java:254)
	at org.elasticsearch.index.search.stats.SearchStats.readFrom(SearchStats.java:311)
	at org.elasticsearch.index.search.stats.SearchStats.readSearchStats(SearchStats.java:299)
	at org.elasticsearch.action.admin.indices.stats.CommonStats.readFrom(CommonStats.java:527)
	at org.elasticsearch.action.admin.indices.stats.CommonStats.readCommonStats(CommonStats.java:484)
	at org.elasticsearch.indices.NodeIndicesStats.readFrom(NodeIndicesStats.java:170)
	at org.elasticsearch.indices.NodeIndicesStats.readIndicesStats(NodeIndicesStats.java:164)
	at org.elasticsearch.action.admin.cluster.node.stats.NodeStats.readFrom(NodeStats.java:190)
	at org.elasticsearch.transport.netty.MessageChannelHandler.handleResponse(MessageChannelHandler.java:178)
	... 23 more
```

2. plugin
```
head                          master s /_plugin/head/ 
elasticsearch-analysis-ik     1.8.0  j 
elasticsearch-analysis-pinyin 1.6.0  j
```

**Comment by slixurd** [comment] 2017-04-28 10:35
This exception is gone after I added another elasticsearch server to this cluster.
Cannot figure out why.

**Comment by clintongormley** [comment] 2017-05-26 17:21
thanks @slixurd - without any further info, we won't be able to debug this.  closing

**Comment by nerophon** [comment] 2017-12-05 17:03
@spinscale @clintongormley 

Another user has experienced what appears to be this issue. Here is what they have reported:

Our Elasticsearch 2.4.5 cluster that has been running since 2017-11-16, is failing on /_stats requests since the morning of 2017-11-29. The _stats response shows a failure like this for every node: 

```
"shard" : 5, 
"index" : "<obfuscated>", 
"status" : "INTERNAL_SERVER_ERROR", 
"reason" : { 
  "type" : "failed_node_exception", 
  "reason" : "Failed node [taiONwmQQbKCC9GDEUCrFw]", 
  "caused_by" : { 
    "type" : "transport_serialization_exception", 
    "reason" : "Failed to deserialize response of type [org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$NodeResponse]", 
    "caused_by" : { 
      "type" : "index_out_of_bounds_exception", 
      "reason" : "Readable byte limit exceeded: 1232" 
    } 
  } 
} 
```

Correspondingly the ES log contains this: 

```
2017-11-29 14:40:44,370 DEBUG [orker #23}] [indices.stats ] [luu1240p] failed to execute [indices:monitor/stats] on node [loKmHfQPRkeeVphG9qRKRQ] 
RemoteTransportException[[Failed to deserialize response of type [org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$NodeResponse]]]; nested: TransportSerializationExc 
eption[Failed to deserialize response of type [org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$NodeResponse]]; nested: IndexOutOfBoundsException[Readable byte limit exceeded: 1232]; 
Caused by: TransportSerializationException[Failed to deserialize response of type [org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$NodeResponse]]; nested: IndexOutOfBoundsException[Readable byte limit exceeded: 1232]; 
at org.elasticsearch.transport.netty.MessageChannelHandler.handleResponse(MessageChannelHandler.java:152) 
at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:124) 
at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) 
at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) 
at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) 
at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) 
at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462) 
at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443) 
at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303) 
at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) 
at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) 
at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) 
at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) 
at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) 
at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) 
at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) 
at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) 
at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) 
at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) 
at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) 
at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
at java.lang.Thread.run(Thread.java:745) 
Caused by: java.lang.IndexOutOfBoundsException: Readable byte limit exceeded: 1232 
at org.jboss.netty.buffer.AbstractChannelBuffer.readByte(AbstractChannelBuffer.java:236) 
at org.elasticsearch.transport.netty.ChannelBufferStreamInput.readByte(ChannelBufferStreamInput.java:132) 
at org.elasticsearch.common.io.stream.FilterStreamInput.readByte(FilterStreamInput.java:39) 
at org.elasticsearch.common.io.stream.StreamInput.readString(StreamInput.java:268) 
at org.elasticsearch.search.suggest.completion.CompletionStats.readFrom(CompletionStats.java:70) 
at org.elasticsearch.search.suggest.completion.CompletionStats.readCompletionStats(CompletionStats.java:121) 
at org.elasticsearch.action.admin.indices.stats.CommonStats.readFrom(CommonStats.java:551) 
at org.elasticsearch.action.admin.indices.stats.CommonStats.readCommonStats(CommonStats.java:484) 
at org.elasticsearch.action.admin.indices.stats.ShardStats.readFrom(ShardStats.java:97) 
at org.elasticsearch.action.admin.indices.stats.ShardStats.readShardStats(ShardStats.java:90) 
at org.elasticsearch.action.admin.indices.stats.TransportIndicesStatsAction.readShardResult(TransportIndicesStatsAction.java:80) 
at org.elasticsearch.action.admin.indices.stats.TransportIndicesStatsAction.readShardResult(TransportIndicesStatsAction.java:47) 
at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$NodeResponse.readFrom(TransportBroadcastByNodeAction.java:560) 
at org.elasticsearch.transport.netty.MessageChannelHandler.handleResponse(MessageChannelHandler.java:150) 
```

We captured the TCP traffic between the nodes on port 9300. From this we excerpted a serialized ShardStats, and wrote a few lines of Groovy to try to parse it. The resulting stacktrace is the same, though the exception is now EOFException due to the different StreamInput used. 

```
$ groovy ShardStatsIndexOutOfBounds.groovy ShardStatsIndexOutOfBounds.data 
Caught: java.io.EOFException 
java.io.EOFException 
at org.elasticsearch.common.io.stream.InputStreamStreamInput.readByte(InputStreamStreamInput.java:43) 
at org.elasticsearch.common.io.stream.StreamInput.readString(StreamInput.java:268) 
at org.elasticsearch.search.suggest.completion.CompletionStats.readFrom(CompletionStats.java:70) 
at org.elasticsearch.search.suggest.completion.CompletionStats.readCompletionStats(CompletionStats.java:121) 
at org.elasticsearch.action.admin.indices.stats.CommonStats.readFrom(CommonStats.java:551) 
at org.elasticsearch.action.admin.indices.stats.CommonStats.readCommonStats(CommonStats.java:484) 
at org.elasticsearch.action.admin.indices.stats.ShardStats.readFrom(ShardStats.java:97) 
at org.elasticsearch.action.admin.indices.stats.ShardStats.readShardStats(ShardStats.java:90) 
at org.elasticsearch.action.admin.indices.stats.ShardStats$readShardStats.call(Unknown Source) 
at ShardStatsIndexOutOfBounds.run(ShardStatsIndexOutOfBounds.groovy:6) 
```

Files are attached. 

We’ve not identified the root cause. The parsing goes astray somewhere before the CompletionStats that finally fails, as some readBoolean() calls start to return other byte values than 0 and 1. 

We are currently requesting a restart of this ES cluster which will hopefully clear out this problem, as we have to progress with our work. We hope that this diagnostic information allows you to pinpoint the cause of this apparent serialization bug.

[Archive.zip](https://github.com/elastic/elasticsearch/files/1532114/Archive.zip)

**Comment by clintongormley** [comment] 2017-12-05 17:30
The 2.x series is no longer maintained, and in 5.0, the completion suggester (which was was causing this issue) has been removed.  I suggest upgrading your cluster to 5.x or 6.x.

**Closed by clintongormley** 2017-12-05 17:30 UTC
Labels: :Stats, feedback_needed
