### ISSUE TITLE
Elasticsearch fuzzy search not working properly with simpleQueryStringQuery

### ISSUE THREAD

**Issue by rocky1234** [elastic/elasticsearch#61780] opened 2020-09-01 11:59 UTC
Elasticsearch fuzzy search not working properly with simpleQueryStringQuery

It is not able to search weird which is stored as weirds in the elasticsearch

Query used:
QueryBuilder matchQueryBuilder = QueryBuilders.simpleQueryStringQuery(text)

Term available in title passed as text.

If I use ~, it starts searching some other index stored in my local machine again which does not even have that term

**Comment by jloleysens** [comment] 2020-09-01 13:17
Hi @rocky1234 ! Would you mind providing more detailed instructions for how to reproduce the issue you are seeing. Would you also please provide the version of ES you are using.

It could also be the case that `QueryBuilders.matchQuery` could be the builder you are looking for?

**Comment by rocky1234** [comment] 2020-09-01 13:35
Hi

I am using ES 77.8 with JDK 1.8. I am trying to perform the search on the whole document rather than on specific fields. SO I am not using QueryBuilders.matchQuery or QueryBuilders.multiMatchQuery. This issue occurs when I try to search singular field in my searchbox whereas plural is present in ES. For instance:

I search: weird
Stored in document: weirds

No output is shown for it. This is for both the cases:  QueryBuilders.simpleQueryStringQuery(text) and QueryBuilder matchQueryBuilder = QueryBuilders.queryStringQuery(text).fuzziness(Fuzziness.AUTO);

Code:


				//QueryBuilder matchQueryBuilder = QueryBuilders.simpleQueryStringQuery(text).flags();
		       QueryBuilder matchQueryBuilder = QueryBuilders.queryStringQuery(text).fuzziness(Fuzziness.AUTO);
			     
		        SearchSourceBuilder sourceBuilder = new SearchSourceBuilder();
		        sourceBuilder.query(matchQueryBuilder);
		        sourceBuilder.from(0);
		        sourceBuilder.size(5); 				
		        
		        sourceBuilder.timeout(new TimeValue(60, TimeUnit.SECONDS));
		 
		        
		        SearchRequest searchRequest = new SearchRequest();
		        searchRequest.source(sourceBuilder);
		
		        
		        SearchResponse searchResponse = client.search(searchRequest,RequestOptions.DEFAULT);
		        for(SearchHit searchHit : searchResponse.getHits().getHits()){

//Rest of the code
}

Screenshot of ES:

![image](https://user-images.githubusercontent.com/15325069/91857868-23494a80-ec86-11ea-81cb-141cdf1645cd.png)


Please let me know if anything else is required

**Comment by jimczi** [comment] 2020-09-01 18:46
Hi @rocky1234 , setting `fuzziness(Fuzziness.AUTO)` in the query string is not enough. This option is to set the implicit distance that should be used when the fuzziness operator (`~`) is used in the query. So if you want to search fuzzy terms with the query_string you'll need to search for `QueryBuilders.queryStringQuery("weird~")`.
Since there is no bug here I hope you don't mind if I close the issue. We reserve github for verified bugs and feature request so if you have any further questions regarding the behavior please open a topic in the [discuss forum](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6).

**Closed by jimczi** 2020-09-01 18:46 UTC
Labels: :Core/Features/Java High Level REST Client, >bug, Team:Core/Features, needs:triage

**Comment by rocky1234** [comment] 2020-09-02 05:56
Hi @jimczi ,

As I have already mentioned:

If I use ~ with my term or ~1, it starts searching some other index stored in my local machine again which does not even have that term. And it then throws the error since the other index do not have the fields which current index have. That is the reason I opened the bug.

For further testing, best I can do is delete that other index and perform the search on the current index. Please suggest how should I proceed
