### ISSUE TITLE
service stops after a couple of hours

### ISSUE THREAD

**Issue by Yashin-s** [elastic/elasticsearch#10101] opened 2015-03-16 02:52 UTC
Hello,
I am running elasticsearch on my linux vps server. While starting the service, it is ok but I am getting the following stuffs : 

root@vps15042 [~]# sudo service elasticsearch start 
error: permission denied on key 'vm.max_map_count' 
Starting elasticsearch: [ OK ] 
root@vps15042 [~]# log4j:WARN No appenders could be found for logger (common) 
log4j:WARN Please initialize the log4j system properly. 
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for morefo. 

I do have my elasticsearch.yml and logging.yml under etc/elasticsearch/

And after a couple of hours, it stops by itself, whether it has been kept idle or the service has been used via the webinterface. I have tried to modify the ES_HEAP_SIZE = 2g on etc/sysconfig, but it is still not working. Note that the VPS has 4gb of RAM.

Can anyone please help me please? I am stuck with this issue for more than a week and my whole website is based on elasticsearch which runs fine on my windows for development.

**Comment by tlrx** [comment] 2015-03-16 03:13
@Yashin-s thanks for reporting.

I think there are few problems here. The first one is that the logging system hasn't been initialized so we can't really know why the elasticsearch node has been stopped.

The second one is that you start elasticsearch with the root user while executing a `sudo` command. If possible, I recommand to remove completely elasticsearch and reinstall it, then starting it with the `elasticsearch` user. Also, you can check that the `elasticsearch` user has the correct privileges on  the log directory (see /var/log/elasticsearch)

**Comment by Yashin-s** [comment] 2015-03-16 12:59
I've uninstalled elasticsearch completly. I previously installed it through yum. I've now followed the instructions on http://tecadmin.net/install-elasticsearch-on-linux/ to install the 1.4.4 package. But I am still getting the same error on start. Below is the output. Also, how do I log as elasticsearch user ? I am accessing the VPS via putty.

root@vps15042 [/usr/share/elasticsearch/elasticsearch-1.4.4]# log4j:WARN No appenders could be found for logger (common).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[2015-03-16 07:14:05,484][INFO ][node                     ] [Ape] version[1.4.4], pid[7785], build[c88f77f/2015-02-19T13:05:36Z]
[2015-03-16 07:14:05,485][INFO ][node                     ] [Ape] initializing ...
[2015-03-16 07:14:05,490][INFO ][plugins                  ] [Ape] loaded [], sites [head]
[2015-03-16 07:14:07,900][INFO ][node                     ] [Ape] initialized
[2015-03-16 07:14:07,900][INFO ][node                     ] [Ape] starting ...
[2015-03-16 07:14:08,030][INFO ][transport                ] [Ape] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/23.235.207.40:9300]}
[2015-03-16 07:14:08,048][INFO ][discovery                ] [Ape] elasticsearch/IeHVdHdZSVqvR2U84cvK-g
[2015-03-16 07:14:08,056][WARN ][discovery.zen.ping.multicast] [Ape] failed to send multicast ping request: IOException[Operation not permitted]
[2015-03-16 07:14:09,557][WARN ][discovery.zen.ping.multicast] [Ape] failed to send multicast ping request: IOException[Operation not permitted]
[2015-03-16 07:14:11,060][WARN ][discovery.zen.ping.multicast] [Ape] failed to send multicast ping request: IOException[Operation not permitted]
[2015-03-16 07:14:11,818][INFO ][cluster.service          ] [Ape] new_master [Ape][IeHVdHdZSVqvR2U84cvK-g][vps15042.inmotionhosting.com][inet[/23.235.207.40:9300]], reason: zen-disco-join 

(elected_as_master)
[2015-03-16 07:14:11,845][INFO ][gateway                  ] [Ape] recovered [0] indices into cluster_state
[2015-03-16 07:14:11,845][INFO ][http                     ] [Ape] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/23.235.207.40:9200]}
[2015-03-16 07:14:11,846][INFO ][node                     ] [Ape] started

**Comment by Yashin-s** [comment] 2015-03-16 16:35
On this installation, it is quiting after I close my SSH connection. How can I keep it ongoing?

**Comment by tlrx** [comment] 2015-03-16 17:13
Here is how I usually proceed:
- uninstall everything is needed
- check if java is correctly installed
- install elasticsearch with YUM
- check if the `elasticsearch` user has been created
- check if /var/log/elasticsearch, /var/lib/elasticsearch, /etc/elasticsearch directories are created
- check if elasticsearch user has read/write privileges on these directories
- start elasticsearch as a service

I also recommend you to follow the documentation, these pages http://www.elastic.co/guide/en/elasticsearch/reference/current/setup-repositories.html#yum and http://www.elastic.co/guide/en/elasticsearch/reference/current/setup-service.html should help you.

**Comment by Yashin-s** [comment] 2015-03-17 03:59
Thanks for your reply.
I've followed your instructions and set new privileges to elasticsearch user which was no present on the /etc/elasticsearch directory
As a non-linux user, I have one more question.
When I did "su elasticsearch", it tells me user has not been setup. After some research on the net I did

$ sudo chsh -s /bin/bash elasticsearch

Now when I do "su elasticsearch", and then "sudo service elasticsearch start", it prompts me for the password of elasticsearch user. I have not configured it anywhere, what should this be or how to configure it?

Thank you for your time.

**Comment by Yashin-s** [comment] 2015-03-18 13:43
Thanks for the instructions, I've already uninstall and re-install the plugin several times but I keep getting the same issue. I think that it has something to do with virtual memory setting. My vm.max_map_count is only 65,530 compared to the 262,144 that es is trying to assign. It may be that it is resulting in OOM exceptions. I cannot change vm.max_map_count either to test it, since I do not have the permission on the VPS server. What can I do to detect if there are indeed out of memory exceptions and what can I do to solve the issue?

**Comment by tlrx** [comment] 2015-03-20 08:55
Hi @Yashin-s,

I close this issue because it seems to be more a configuration problem than a bug. Could you please post your question on the mailing list https://groups.google.com/group/elasticsearch/? It will be easier and there are more people there to help you.

**Closed by tlrx** 2015-03-20 08:55 UTC
Labels: :Packaging

**Comment by Ziink** [comment] 2015-04-26 01:02
It seems like the problem is due to the kernel version of OpenVZ. At least that is the case with me.

Yashin-s I'm guessing your VPS is on OpenVZ. Run the command 
uname -a

On the VPS where elasticsearch keeps crashing at random times, I get an output like
> Linux nyserver1 2.6.32-042stab104.1 #1 SMP Thu Jan 29 12:58:41 MSK 2015 x86_64 x86_64 x86_64 GNU/Linux

On another VPS, where elasticsearch is working fine, the output I get is
> Linux zine 2.6.32-042stab103.6 #1 SMP Wed Jan 21 13:07:39 MSK 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by clintongormley** [comment] 2015-04-26 17:55
Possibly related to https://github.com/elastic/elasticsearch/issues/9582 ?

**Comment by fundup** [comment] 2015-06-17 11:27
I had same problem. I did my first install using root. Then I remove and install once again using a user and sudo apt-get (https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-repositories.html) . It seems to work now. Hope it will help
