### ISSUE TITLE
ElasticSearch does not respect the mapping types

### ISSUE THREAD

**Issue by anujgandharv** [elastic/elasticsearch#15056] opened 2015-11-27 09:16 UTC
HI,
 I am working with Elasticsearch 2.1.0.
I have a requirement to specify the schema for my documents.
So i used the ElasticSearch Mapping functionality like this:

curl -XPUT 'http://localhost:9200/customer/external/_mapping' -d ' { "external" : { "properties" : { "example" : { "properties" : { "custom_property" : { "type" : "byte" } } } } } } '

It gets reflected in the schema mapping as well:

```json
{
  "customer" : {
    "mappings" : {
      "external" : {
        "properties" : {
          "first" : {
            "type" : "long"
          },
          "example" : {
            "properties" : {
              "custom_property" : {
                "type" : "byte"
              },
              "last" : {
                "type" : "long"
              }
            }
          }
        }
      }
    }
  }
}
```
I then added the value for this field like this:

curl -XPUT 'localhost:9200/customer/external/1?pretty' -d '{"example": {"custom_property": 12345}}'

And to my surprise it was saved successfully. Here is the output : 
```json
{
  "_index" : "customer",
  "_type" : "external",
  "_id" : "1",
  "_version" : 3,
  "found" : true,
  "_source":{"example": {"custom_property": 12345}}
}
```
I did some more investigation and found that the value is treated as short and not as byte. 

There is a similar issue with float dataType as well. Can someone explain what may be causing this and how can this be rectified?

Thanks,
Anuj Kumar

**Comment by clintongormley** [comment] 2015-11-28 11:01
Duplicate of https://github.com/elastic/elasticsearch/issues/11513

**Closed by clintongormley** 2015-11-28 11:01 UTC
