### ISSUE TITLE
Painless still cannot understand some overloaded methods

### ISSUE THREAD

**Issue by umnick84** [elastic/elasticsearch#22177] opened 2016-12-14 20:22 UTC
**Elasticsearch version**: 5.0.1 and 5.1.1

**Plugins installed**: []

**JVM version**: 1.8.102

**OS version**: MacOS

**Description of the problem including expected versus actual behavior**:
When I write a script with code "BitSet.valueOf(some_byte_array)" I get ClassCastException with message byte[] cannot be cast to long[]. I think this happens because method valueOf is overloaded and first method in the overloaded method list uses long[] as method parameter.
I added java.util.BitSet class to whitelist for painless.
Expected: script execute the method so that instance of BitSet is created.

I found the issue #18385 and it should be fixed. I suspect that this fix was added to ES 5.x

**Steps to reproduce**:
 1. Create a painless script that does "BitSet.valueOf(some_byte_array)"
 2. Run script
 3. Get exception that byte[] cannot be cast to long[]

**Comment by clintongormley** [comment] 2016-12-16 13:53
@jdconrad any thoughts?

**Comment by jdconrad** [comment] 2016-12-16 17:26
A couple of quick notes:

Do you mind showing me exactly what you added to the whitelist as we didn't really intend for things to be added externally?  Perhaps, this is something I could add on permanently if it's useful for you.  Was it the entire BitSet class?

Overloading is part of version 5.0 and later.  We decided early on in development to go with arity overloading (meaning methods with the same name must have a different number of arguments) because it turns out it's really difficult to determine method overloading at runtime without at least taking a significant performance hit.

One suggestion would be to remove the valueOf(long[]) method from the whitelist for now as I believe this will fix the problem if you only need the valueOf(byte[]) method.

**Comment by umnick84** [comment] 2016-12-22 10:33
Thanks for that!
Meanwhile I prepared workaround with custom java plugin implementation. It works fine. However I cannot compare its performance with native painless code. In documentation you said that painless is really fast. Not sure if I can use groovy script for that (as far as I remember it could not access BitSet class at all so I gave up after a while).

**Comment by jdconrad** [comment] 2016-12-22 16:18
Groovy has been deprecated in 5.0 and is removed in 6.0, so it's not really an option anymore just in case you were still looking into that.

On a different note, after a bit of investigation, we went with long[] for performance reasons, but this is place where having byte[] also would be good, so I'll evaluate what our options are here to see if we can give you what you need.

**Comment by nezda** [comment] 2017-02-04 16:33
I got tripped up by `Integer.valueOf(String)` not working (seems only the `int` form works so I used `Integer.parsInt(String)`) - was trying to support input from either ints or string sorta like JavaScript.  Guess I can `Integer.valueOf(arg.toString())`...

**Comment by jdconrad** [comment] 2017-02-07 00:09
@nezda -- Here is the published Painless API. (https://www.elastic.co/guide/en/elasticsearch/reference/master/painless-api-reference.html)
Please see the reasoning below for why some expected methods may not be defined.

@s1monw I'm not sure I consider this a bug since we claim to support arity overloading, it was a design decision made so method look up (especially for runtime performance) would be fast.  Otherwise, we'd have to write our own algorithm for figuring out which method is closest to the passed in arguments which is both very difficult and bad for performance.  This means we did have to make decisions around what methods were available that had the same arity within a separate class.  I think an appropriate solution to this might be to alias some of the methods that share a name and arity to simply have a different name.

**Comment by jdconrad** [comment] 2017-11-29 16:11
This is not a bug.  Painless uses arity overloading, but it's very unlikely we ever support full signature overloading.  Closing.

**Closed by jdconrad** 2017-11-29 16:11 UTC
Labels: :Plugin Lang Painless, bug
