### ISSUE TITLE
Weird behaviour when adding a snapshot repository

### ISSUE THREAD

**Issue by arikmaor** [elastic/elasticsearch#66755] opened 2020-12-22 16:07 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 7.6.1

**Plugins installed**: [repository-gcs]

**JVM version** (`java -version`): N/A

**OS version** (`uname -a` if on a Unix-like system): N/A

**Docker file**:
```
FROM docker.elastic.co/elasticsearch/elasticsearch:7.6.1
RUN bin/elasticsearch-plugin install --batch repository-gcs
```

**Description of the problem including expected versus actual behavior**:
Weird behaviour in snapshots repository with bad input (writing `base_path:` instead of `base_path`)
Instead of failing to add a snapshot repository or adding it and ignoring the bad argument, the process succeeds and a confusing state is shown in `kibana`

**Steps to reproduce**:

1. Create a snapshot repository and a snapshot:
```
curl 127.0.0.1:9200/_snapshot/test-snapshot-repo \
  -XPUT -H 'Content-Type:application/json' \
  -d '{"type":"gcs","settings":{"bucket":"YOUR_BUCKET","base_path":"test-snapshots","compress":true}}'
curl '127.0.0.1:9200/_snapshot/test-snapshot-repo/snapshot-1?wait_for_completion=true' \
  -XPUT -H 'Content-Type:application/json'
```
2. Delete the repository
```
curl 127.0.0.1:9200/_snapshot/test-snapshot-repo -XDELETE
```
3. Add the repository again and this time note the bad `base_path:` in the request:
```
curl 127.0.0.1:9200/_snapshot/test-snapshot-repo \
  -XPUT -H 'Content-Type:application/json' \
  -d '{"type":"gcs","settings":{"bucket":"YOUR_BUCKET","base_path:":"test-snapshots","compress":true}}'
```
4. Go to `kibana` management => click _Snapshots and Restore_ => click the `test-snapshot-repo`
**You will see the base path as like it's configured correctly but there are no snapshots**

5. Click `Edit` and `Save` and the snapshots will appear

**Comment by original-brownbear** [comment] 2020-12-25 19:14
This is a duplicate of https://github.com/elastic/elasticsearch/issues/27765 => closing here

**Closed by original-brownbear** 2020-12-25 19:14 UTC
Labels: :Distributed/Snapshot/Restore, >bug, Team:Distributed
