### ISSUE TITLE
Add size or number of fields limit on dynamic mapping

### ISSUE THREAD

**Issue by yanjunh** [elastic/elasticsearch#11443] opened 2015-06-01 15:49 UTC
Object mapping are dynamic by default. The mapping size get exploded when incoming document stream contains dynamic keys such as uuid string, time string etc. For example, {"fields":{"de305d54-75b4-431b-adb2-eb6b9e546014":{...}}}. It can kill the cluster very fast at high indexing rate. We need a way to limit mapping by size or by number of fields. When the limit is reached, the object mapping behavior changes from dynamic:true to dynamic:false.

**Comment by clintongormley** [comment] 2015-06-02 18:20
Hi @yanjunh 

This feels like the wrong approach.  Why would we index field `foo-bar-123` and reject `foo-bar-124`?  Why index the first field at all, if you're just going to throw away the next field arbitrarily?

I'm afraid the proposed solution is not a solution at all. Instead, you need to change how you're indexing the data, or how you're adding fields.

**Comment by nik9000** [comment] 2015-06-02 18:38
I think the idea is to catch mistakes and prevent the cluster from becoming unstable.

**Comment by clintongormley** [comment] 2015-06-02 18:42
@nik9000 sure, but this is still the wrong solution. we're not going to add a setting which arbitrarily rejects fields if X many fields still exist.

**Comment by yanjunh** [comment] 2015-06-02 18:49
@clintongormley We have been telling developers about the limitation but we can't prevent them from producing unfriendly data. Thought about detecting it on when data flow through Logstash but that's not a good place. What's the recommended way to guard against unbounded mapping growth?

**Comment by nik9000** [comment] 2015-06-02 18:53
> What's the recommended way to guard against unbounded mapping growth?

Strong language.

Seriously though, for my use case I turn mapping to non-dynamic and only add fields "intentionally" but that's not always possible.

Also - I imagine this is something you could catch in code review and by giving all developers their own instance to test against. But I'm still for adding some extra defence against it to Elasticsearch.

**Comment by yanjunh** [comment] 2015-06-02 18:58
@nik9000 Forgive my wording
We have no control on what people log. So far I can only set alerts when problem happens. Even so it's often too late because the data are coming in so fast.

**Comment by clintongormley** [comment] 2015-06-02 19:05
@yanjunh I'll reopen the issue for further discussion.

**Comment by jpountz** [comment] 2015-06-03 09:42
Going from `dynamic:true` to `dynamic:false` is not an option in my opinion. If you index the same set of documents twice, you would get different mappings depending on the order in which documents have been indexed.

I would be open to discuss switching from `dynamic:true` to `dynamic:strict` however, so that the cause of the issue would be propagated to the client which is indexing the document. I can see value in admins being able to protect against client-side bugs and/or enforce consumers of elasticsearch to follow some good practices.

**Comment by nik9000** [comment] 2015-06-03 11:38
> I would be open to discuss switching from dynamic:true to dynamic:strict however, so that the cause of the issue would be propagated to the client which is indexing the document.

If dynamic:strict rejects the document then I'm +1 on that. So long as the setting is dynamically update-able then it shouldn't prevent people from doing this if they want - just get in their way and remind them its a bad idea.

**Comment by yanjunh** [comment] 2015-06-03 14:18
I agree with dynamic:strict. My original thought is to keep the good part of the document and just drop the bad field. Dropping whole document might be a better idea. That will force the data producers to structure their data in the right way. The data consumers can then effectively  search and aggregate on the right structured data. In either approach, being able to protect the search cluster from bad data can be very useful.

**Comment by segalziv** [comment] 2015-07-23 10:13
+1 for setting a limit on the number of (dynamic) fields, and moving to dynamic:false when that limit reached. 

I'm also trying to protect elasticsearch from becoming unstable due to too many fields.

**Comment by breml** [comment] 2015-11-15 09:42
We use a custom analyzer to mark dynamically added fields, which allows us to monitor the count of added fields. More explanation in the following blog post:  https://breml.github.io/blog/2015/10/28/tagging-of-dynamically-added-fields-in-elasticsearch/

**Comment by ppf2** [comment] 2016-01-06 21:28
+1 on providing an option for the safeguard.  Another use case is key value logging and using the LS KV filter with dynamic mappings so that these fields are automatically extracted and generated.  Having a limit the user can set can help prevent unintentional explosion in mappings when someone decides to use UUIDs as keys, etc..

**Closed** 2016-03-29 17:40 UTC
Labels: :Mapping, adoptme, enhancement
