### ISSUE TITLE
[CI] MlDistributedFailureIT testJobRelocationIsMemoryAware 

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#68685] opened 2021-02-08 16:50 UTC
**Build scan**:
https://gradle-enterprise.elastic.co/s/3f46ieb2kaar6

**Repro line**:
```
./gradlew ':x-pack:plugin:ml:internalClusterTest' --tests "org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.testJobRelocationIsMemoryAware" \
  -Dtests.seed=414C5FE387D03C47 \
  -Dtests.security.manager=true \
  -Dtests.locale=und \
  -Dtests.timezone=America/Cordoba \
  -Druntime.java=11
```

**Reproduces locally?**:
No

**Applicable branches**:
8.0, 7.x, 7.12, 7.11, 6.8

**Failure history**:
Fairly rare but the test was muted on Debian due to the memory bug.

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-60d,mode:quick,to:now))&_a=(columns:!(branch,test),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testJobRelocationIsMemoryAware),sort:!(time,desc))

**Failure excerpt**:
The exact failing assertion changes. In this [case](https://gradle-enterprise.elastic.co/s/3f46ieb2kaar6) on master the failure was:

```
java.lang.AssertionError: expected:<4> but was:<0>
	at __randomizedtesting.SeedInfo.seed([414C5FE387D03C47:D209B66A43FB2FE9]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.lambda$testJobRelocationIsMemoryAware$14(MlDistributedFailureIT.java:451)
``` 

On 7.11 the stack trace is:
```
java.lang.AssertionError: expected:<1> but was:<2> 	
        at __randomizedtesting.SeedInfo.seed([62D0B869E3ED68D9:F19551E027C67B77]:0)
        at org.junit.Assert.fail(Assert.java:88) 	
        at org.junit.Assert.failNotEquals(Assert.java:834) 	
        at org.junit.Assert.assertEquals(Assert.java:645)
 	at org.junit.Assert.assertEquals(Assert.java:631)
 	at org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.lambda$testJobRelocationIsMemoryAware$14(MlDistributedFailureIT.java:460)
```

**Comment by droberts195** [comment] 2021-02-08 16:54
It's the problem noted in https://github.com/elastic/elasticsearch/issues/64171#issuecomment-716613448.  Now the Debian 8 memory issue is out of the way that has come back.  It will be interesting to see if it is less intermittent now than when originally seen.

**Comment by benwtrent** [comment] 2021-03-22 18:01
https://gradle-enterprise.elastic.co/s/h5slxk7ylljvu

another failure. This was `centos-7` with `Zulu11`

Logs for assignment: 
```
  | 1> [2021-03-22T18:31:27,869][INFO ][o.e.x.m.j.p.a.AutodetectProcessManager] [node_t2] Opening job [small3] |  
  | 1> [2021-03-22T18:31:27,878][INFO ][o.e.x.m.j.p.a.AutodetectProcessManager] [node_t2] [small3] Loading model snapshot [N/A], job latest_record_timestamp [N/A] |  
  | 1> [2021-03-22T18:31:27,899][INFO ][o.e.x.m.j.p.a.AutodetectProcessManager] [node_t1] Opening job [small4] |  
  | 1> [2021-03-22T18:31:27,917][INFO ][o.e.x.m.j.p.a.AutodetectProcessManager] [node_t1] Opening job [small2] |  
  | 1> [2021-03-22T18:31:27,918][INFO ][o.e.x.m.j.p.a.AutodetectProcessManager] [node_t1] [small4] Loading model snapshot [N/A], job latest_record_timestamp [N/A] |  
  | 1> [2021-03-22T18:31:27,919][INFO ][o.e.x.m.j.p.a.AutodetectProcessManager] [node_t1] Opening job [small1] |  
  | 1> [2021-03-22T18:31:27,995][INFO ][o.e.x.m.j.p.a.AutodetectProcessManager] [node_t1] [small2] Loading model snapshot [N/A], job latest_record_timestamp [N/A] |  
  | 1> [2021-03-22T18:31:27,995][INFO ][o.e.x.m.j.p.a.AutodetectProcessManager] [node_t1] [small1] Loading model snapshot [N/A], job latest_record_timestamp [N/A] |  
  | 1> [2021-03-22T18:31:28,071][INFO ][o.e.x.m.j.p.a.AutodetectProcessManager] [node_t2] Successfully set job state to [opened] for job [small3] |  
  | 1> [2021-03-22T18:31:28,140][INFO ][o.e.x.m.j.p.a.AutodetectProcessManager] [node_t1] Successfully set job state to [opened] for job [small4] |  
  | 1> [2021-03-22T18:31:28,195][INFO ][o.e.x.m.j.p.a.AutodetectProcessManager] [node_t1] Successfully set job state to [opened] for job [small2] |  
  | 1> [2021-03-22T18:31:28,294][INFO ][o.e.x.m.j.p.a.AutodetectProcessManager] [node_t1] Successfully set job state to [opened] for job [small1] |  
  | 1> [2021-03-22T18:31:37,803][INFO ][o.e.x.m.j.p.a.o.AutodetectResultProcessor] [node_t0] [small4] 0 buckets parsed from autodetect output |  
  | 1> [2021-03-22T18:31:37,806][INFO ][o.e.x.m.j.p.a.o.AutodetectResultProcessor] [node_t0] [small3] 0 buckets parsed from autodetect output |  
  | 1> [2021-03-22T18:31:37,808][INFO ][o.e.x.m.j.p.a.o.AutodetectResultProcessor] [node_t0] [small2] 0 buckets parsed from autodetect output |  
  | 1> [2021-03-22T18:31:37,809][INFO ][o.e.x.m.j.p.a.o.AutodetectResultProcessor] [node_t0] [small1] 0 buckets parsed from autodetect output |  
  | 1> [2021-03-22T18:31:37,810][INFO ][o.e.t.InternalTestCluster] [testJobRelocationIsMemoryAware] removing voting config exclusions for [node_t0] after restart/shutdown |  
  | 1> [2021-03-22T18:31:37,992][INFO ][o.e.x.m.i.MlDistributedFailureIT] [testJobRelocationIsMemoryAware] small job nodes: [node_t1, node_t1, node_t2, node_t1], big job nodes: [node_t2] |  
  | 1> [2021-03-22T18:31:38,059][INFO ][o.e.x.m.i.MlDistributedFailureIT] [testJobRelocationIsMemoryAware] small job nodes: [node_t1, node_t1, node_t2, node_t1], big job nodes: [node_t2] |  
  | 1> [2021-03-22T18:31:38,088][INFO ][o.e.x.m.i.MlDistributedFailureIT] [testJobRelocationIsMemoryAware] small job nodes: [node_t1, node_t1, node_t2, node_t1], big job nodes: [node_t2] |  
  | 1> [2021-03-22T18:31:38,154][INFO ][o.e.x.m.i.MlDistributedFailureIT] [testJobRelocationIsMemoryAware] small job nodes: [node_t1, node_t1, node_t2, node_t1], big job nodes: [node_t2] |  
  | 1> [2021-03-22T18:31:38,223][INFO ][o.e.x.m.i.MlDistributedFailureIT] [testJobRelocationIsMemoryAware] small job nodes: [node_t1, node_t1, node_t2, node_t1], big job nodes: [node_t2] |  
  | 1> [2021-03-22T18:31:38,265][INFO ][o.e.x.m.i.MlDistributedFailureIT] [testJobRelocationIsMemoryAware] small job nodes: [node_t1, node_t1, node_t2, node_t1], big job nodes: [node_t2] |  
  | 1> [2021-03-22T18:31:38,333][INFO ][o.e.x.m.i.MlDistributedFailureIT] [testJobRelocationIsMemoryAware] small job nodes: [node_t1, node_t1, node_t2, node_t1], big job nodes: [node_t2] |  
  | 1> [2021-03-22T18:31:38,442][INFO ][o.e.x.m.i.MlDistributedFailureIT] [testJobRelocationIsMemoryAware] small job nodes: [node_t1, node_t1, node_t2, node_t1], big job nodes: [node_t2] |  
  | 1> [2021-03-22T18:31:38,603][INFO ][o.e.x.m.i.MlDistributedFailureIT] [testJobRelocationIsMemoryAware] small job nodes: [node_t1, node_t1, node_t2, node_t1], big job nodes: [node_t2] |  
  | 1> [2021-03-22T18:31:38,892][INFO ][o.e.x.m.i.MlDistributedFailureIT] [testJobRelocationIsMemoryAware] small job nodes: [node_t1, node_t1, node_t2, node_t1], big job nodes: [node_t2] |  
  | 1> [2021-03-22T18:31:39,430][INFO ][o.e.x.m.i.MlDistributedFailureIT] [testJobRelocationIsMemoryAware] small job nodes: [node_t1, node_t1, node_t2, node_t1], big job nodes: [node_t2] |  
  | 1> [2021-03-22T18:31:40,476][INFO ][o.e.x.m.i.MlDistributedFailureIT] [testJobRelocationIsMemoryAware] small job nodes: [node_t1, node_t1, node_t2, node_t1], big job nodes: [node_t2] |  
  | 1> [2021-03-22T18:31:42,555][INFO ][o.e.x.m.i.MlDistributedFailureIT] [testJobRelocationIsMemoryAware] small job nodes: [node_t1, node_t1, node_t2, node_t1], big job nodes: [node_t2] |  
  | 1> [2021-03-22T18:31:48,492][INFO ][o.e.x.m.i.MlDistributedFailureIT] [testJobRelocationIsMemoryAware] small job nodes: [node_t1, node_t1, node_t2, node_t1], big job nodes: [node_t2]
```

**Comment by droberts195** [comment] 2021-03-23 11:14
This issue is the same as #64171, but even though that one is older I'll keep this one open as it doesn't have the confusion caused by comments about different problems.

The relevant knowledge from #64171 is in https://github.com/elastic/elasticsearch/issues/64171#issuecomment-716613448.

The distribution of jobs in the most recent failure reported on this issue is `small job nodes: [node_t1, node_t1, node_t2, node_t1], big job nodes: [node_t2]`.  That is different to the `small job nodes: [node_t2, node_t1, node_t2, node_t1], big job nodes: [node_t2]` that was observed in https://github.com/elastic/elasticsearch/issues/64171#issuecomment-716613448, but the root cause is the same: job assignment was done by count rather than by memory.  The reasons for the difference are:

1. The jobs got iterated in a different order when collecting the list
2. Since there are 5 jobs and 2 nodes, when allocating by count it's arbitrary which node the 5th job goes on

> This "expected:<1> but was:<2>" error was first seen in 7.7 on 1st May 2020 in build https://gradle-enterprise.elastic.co/s/5dmfgujbmccvq. (There have been many other failures of this test but due to suite timeouts or failure to form a cluster or other test infrastructure problems that are not interesting as far as this particular failure is concerned.) So it is probably worth looking at changes to the node assignment code in the 6 weeks prior to 1st May to see if anything was changed that might have introduced a loophole into the logic.

I had a look and there weren't any such changes.  The autoscaling changes were all done after this.  So it would appear that the problem existed for a long time before it first manifested itself.  Another piece of evidence to corroborate this is an `expected:<1> but was:<2>` failure in https://gradle-enterprise.elastic.co/s/ckhqfcj656sog, which was a 6.8 build from January 2021.

**Comment by droberts195** [comment] 2021-03-23 12:12
I have enabled test logging in #70727 to try to finally get to the bottom of this problem.

**Comment by benwtrent** [comment] 2021-03-26 12:42
Got some trace logs with a failure. Some interesting patterns (insufficient history, MlMemoryTracker stopping due to master change, etc.)

[qof2b6w4yayos-console-log.txt.zip](https://github.com/elastic/elasticsearch/files/6211828/qof2b6w4yayos-console-log.txt.zip)

Gonna mute the test.

**Comment by droberts195** [comment] 2021-03-28 12:26
It is important to understand that "expected:<4> but was:<0>" and "expected:<1> but was:<2>" are completely different failure scenarios.

The most recent failure that caused this test to be muted was "expected:<4> but was:<0>".  I think I have fixed this in #70950.  "expected:<4> but was:<0>" is purely a test problem that will not affect end users - the default interval for rechecking persistent task assignment is 30 seconds, but the test was only waiting 10 seconds to achieve the expected state.

The other failure, "expected:<1> but was:<2>", is more worrying, and _might_ affect end users.  I have unmuted the test in #70950 so that hopefully we can get some extra logging for that failure scenario.

**Comment by romseygeek** [comment] 2021-03-29 11:52
"expected:<1> but was:<2>" just popped up again here:
https://gradle-enterprise.elastic.co/s/wgplh22honqwg/tests/:x-pack:plugin:ml:internalClusterTest/org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT/testJobRelocationIsMemoryAware#1

**Comment by benwtrent** [comment] 2021-03-29 11:55
Was just about to comment this ^.

The logging indeed has all the necessary trace logging. 

[wgplh22honqwg-console-log.txt.zip](https://github.com/elastic/elasticsearch/files/6221486/wgplh22honqwg-console-log.txt.zip)

**Comment by droberts195** [comment] 2021-03-29 17:01
The "expected:<1> but was:<2>" problem occurs because as the cluster elects a new master immediately after one node is killed the new master flips between non-master and master twice:

```
[2021-03-29T14:33:39,213][INFO ][o.e.c.s.ClusterApplierService] [node_t1] master node changed {previous [], current [{node_t1}{A00_h_wsQZ-LXXiy019Mjw}{JGgFAZBkRs6KAuhZW61VkA}{127.0.0.1}{127.0.0.1:36145}{cdfhilmrsw}]}, term: 3, version: 60, reason: Publication{term=3, version=60}
...
[2021-03-29T14:33:39,332][INFO ][o.e.c.s.ClusterApplierService] [node_t1] master node changed {previous [{node_t1}{A00_h_wsQZ-LXXiy019Mjw}{JGgFAZBkRs6KAuhZW61VkA}{127.0.0.1}{127.0.0.1:36145}{cdfhilmrsw}], current []}, term: 3, version: 60, reason: becoming candidate: joinLeaderInTerm	
...
[2021-03-29T14:33:39,335][INFO ][o.e.c.c.JoinHelper       ] [node_t2] failed to join {node_t1}{A00_h_wsQZ-LXXiy019Mjw}{JGgFAZBkRs6KAuhZW61VkA}{127.0.0.1}{127.0.0.1:36145}{cdfhilmrsw}{ml.machine_memory=101361889280, ml.max_open_jobs=20, xpack.installed=true, ml.max_jvm_size=512229376} with JoinRequest{sourceNode={node_t2}{W7E_VR4oSxCBfVfBZmEM8w}{MmzuFyswTASRHljyqOekSA}{127.0.0.1}{127.0.0.1:41429}{cdfhilmrsw}{ml.machine_memory=101361889280, xpack.installed=true, ml.max_open_jobs=20, ml.max_jvm_size=506986496}, minimumTerm=3, optionalJoin=Optional.empty}
...
[2021-03-29T14:33:39,487][INFO ][o.e.c.s.ClusterApplierService] [node_t1] master node changed {previous [], current [{node_t1}{A00_h_wsQZ-LXXiy019Mjw}{JGgFAZBkRs6KAuhZW61VkA}{127.0.0.1}{127.0.0.1:36145}{cdfhilmrsw}]}, term: 5, version: 61, reason: Publication{term=5, version=61}	
```

Each time the node becomes master it triggers a memory requirement refresh.  Each time it ceases to be master it clears its cache of memory requirements.

The way we use the ML memory tracker is not atomic.  We call a method to ask if memory requirements are up to date, then call another method to get the memory requirements.  If the node ceased to be master in between these events then we can find that the memory requirements are up to date, but then find they don't exist when needed.

**Comment by droberts195** [comment] 2021-03-30 15:45
I opened #71067 as a short-term improvement.  It will be interesting to see how many "expected:<1> but was:<2>" we get in CI after this is merged.

The better fix would be to combine the "is recently refreshed?" and "what are the memory requirements?" questions into a single accessor method.  This would have to return an immutable map and then the caller would pass this around to all the places where either question needed answering for a particular assignment decision.

**Comment by droberts195** [comment] 2021-05-06 08:05
This test hasn't failed since 29th March, so it looks like the not-quite-perfect fix was good enough.

**Closed by droberts195** 2021-05-06 08:05 UTC
Labels: :ml, >test-failure, Team:ML
