### ISSUE TITLE
Elastic search service starting is failing - java.lang.IllegalArgumentException: Plugin [delete-by-query] is incompatible with Elasticsearch [2.4.5]. Was designed for version [2.4.4]

### ISSUE THREAD

**Issue by bibinvenugopal** [elastic/elasticsearch#25160] opened 2017-06-09 17:39 UTC
java.lang.IllegalArgumentException: Plugin [delete-by-query] is incompatible with Elasticsearch [2.4.5]. Was designed for version [2.4.4]
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:118)
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:378)
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:128)
        at org.elasticsearch.node.Node.<init>(Node.java:158)
        at org.elasticsearch.node.Node.<init>(Node.java:140)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:194)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:286)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:45)

**Comment by jasontedor** [comment] 2017-06-09 17:42
What's unclear about the error message? If it needs improvement, we will improvement but it seems pretty clear: you have installed version 2.4.4 of the delete-by-query plugin on a node running 2.4.5. I'm closing this as not a bug. If you need additional help, ask on the [forum](https://discuss.elastic.co).

**Closed by jasontedor** 2017-06-09 17:42 UTC
