### ISSUE TITLE
service failed to start

### ISSUE THREAD

**Issue by DangerView** [elastic/elasticsearch#21298] opened 2016-11-03 09:15 UTC
**Elasticsearch version**:
5.0
**Plugins installed**: []
x-pack
**JVM version**:
1.8
**OS version**:
ubuntu 14.05
**Description of the problem including expected versus actual behavior**:

enter command
service elasticsearch start
after 10s failed.
/var/log/elasticsearch there is no logs.
so I was test /etc/init.d/elasticsearch, it seems to timeout and immediately finished.
I have no idea... what can i do anything?
thanks your support.

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by clintongormley** [comment] 2016-11-03 11:25
This sounds like a duplicate of https://github.com/elastic/elasticsearch/issues/21300

**Closed by clintongormley** 2016-11-03 11:25 UTC
