### ISSUE TITLE
[CI] VotingOnlyNodePluginTests testBasicSnapshotRestoreWorkFlow failing

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#105426] opened 2024-02-12 22:42 UTC
**Build scan:**
https://gradle-enterprise.elastic.co/s/vfv66urr77xvi/tests/:x-pack:plugin:voting-only-node:internalClusterTest/org.elasticsearch.cluster.coordination.votingonly.VotingOnlyNodePluginTests/testBasicSnapshotRestoreWorkFlow

**Reproduction line:**
```
./gradlew ':x-pack:plugin:voting-only-node:internalClusterTest' --tests "org.elasticsearch.cluster.coordination.votingonly.VotingOnlyNodePluginTests.testBasicSnapshotRestoreWorkFlow" -Dtests.seed=6BAC3E9C903A3C85 -Dtests.configure_test_clusters_with_one_processor=true -Dtests.locale=pl -Dtests.timezone=America/Asuncion -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
[Failure dashboard for `org.elasticsearch.cluster.coordination.votingonly.VotingOnlyNodePluginTests#testBasicSnapshotRestoreWorkFlow`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testBasicSnapshotRestoreWorkFlow'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.cluster.coordination.votingonly.VotingOnlyNodePluginTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.AssertionError: Unexpected AlreadyClosedException

  at __randomizedtesting.SeedInfo.seed([6BAC3E9C903A3C85]:0)
  at org.elasticsearch.index.engine.InternalEngine.failOnTragicEvent(InternalEngine.java:2529)
  at org.elasticsearch.index.engine.InternalEngine.refresh(InternalEngine.java:2068)
  at org.elasticsearch.index.engine.InternalEngine.lambda$maybeRefresh$8(InternalEngine.java:2020)
  at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:270)
  at org.elasticsearch.index.engine.InternalEngine.maybeRefresh(InternalEngine.java:2020)
  at org.elasticsearch.index.shard.IndexShard.lambda$scheduledRefresh$47(IndexShard.java:3935)
  at org.elasticsearch.action.ActionListener.run(ActionListener.java:356)
  at org.elasticsearch.index.shard.IndexShard.scheduledRefresh(IndexShard.java:3915)
  at org.elasticsearch.index.IndexService.maybeRefreshEngine(IndexService.java:998)
  at org.elasticsearch.index.IndexService$AsyncRefreshTask.runInternal(IndexService.java:1134)
  at org.elasticsearch.common.util.concurrent.AbstractAsyncTask.run(AbstractAsyncTask.java:137)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:917)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  at java.lang.Thread.run(Thread.java:1583)

  Caused by: org.apache.lucene.store.AlreadyClosedException: engine is closed

    at org.elasticsearch.index.shard.IndexShard.getEngine(IndexShard.java:3185)
    at org.elasticsearch.index.shard.IndexShard$RefreshFieldHasValueListener.afterRefresh(IndexShard.java:4015)
    at org.apache.lucene.search.ReferenceManager.notifyRefreshListenersRefreshed(ReferenceManager.java:275)
    at org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:182)
    at org.apache.lucene.search.ReferenceManager.maybeRefresh(ReferenceManager.java:213)
    at org.elasticsearch.index.engine.InternalEngine.refresh(InternalEngine.java:2047)
    at org.elasticsearch.index.engine.InternalEngine.lambda$maybeRefresh$8(InternalEngine.java:2020)
    at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:270)
    at org.elasticsearch.index.engine.InternalEngine.maybeRefresh(InternalEngine.java:2020)
    at org.elasticsearch.index.shard.IndexShard.lambda$scheduledRefresh$47(IndexShard.java:3935)
    at org.elasticsearch.action.ActionListener.run(ActionListener.java:356)
    at org.elasticsearch.index.shard.IndexShard.scheduledRefresh(IndexShard.java:3915)
    at org.elasticsearch.index.IndexService.maybeRefreshEngine(IndexService.java:998)
    at org.elasticsearch.index.IndexService$AsyncRefreshTask.runInternal(IndexService.java:1134)
    at org.elasticsearch.common.util.concurrent.AbstractAsyncTask.run(AbstractAsyncTask.java:137)
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:917)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    at java.lang.Thread.run(Thread.java:1583)

```

**Comment by DaveCTurner** [comment] 2024-02-13 09:03
Closing as a duplicate of https://github.com/elastic/elasticsearch/issues/105330 (fix incoming in https://github.com/elastic/elasticsearch/pull/105374)

**Closed by DaveCTurner** 2024-02-13 09:03 UTC
Labels: blocker, :Distributed/Snapshot/Restore, >test-failure, Team:Distributed
