### ISSUE TITLE
Querying nested objects with query_string

### ISSUE THREAD

**Issue by imranazad** [elastic/elasticsearch#15627] opened 2015-12-23 10:53 UTC
It would be useful to be able to query nested objects with the query_string.

For example consider the following document structure:

@graph
------------- @drug
 ------------------- @value

The query could look like this:
         "query": { 
                    "query_string" : {
                        "fields" : ["@graph\*"]
                        "query" :"\*@value:paracetamol"
                    }
         }
It can be laborious to explicitly specify nested fields when the document is heavily nested.
What do you think?

**Comment by clintongormley** [comment] 2016-01-10 19:17
Do you mean fields of type `nested` or fields of type `object`?  Either way, `@` is a legal character in a field name, so you couldn't use it to mean something else.

**Comment by clintongormley** [comment] 2016-02-29 20:22
Duplicate of #16551

**Closed by clintongormley** 2016-02-29 20:22 UTC
Labels: :Query DSL, feedback_needed
