### ISSUE TITLE
[CI] AzureRepositoriesMeteringIT multiple tests failing failing

### ISSUE THREAD

**Issue by mosche** [elastic/elasticsearch#105864] opened 2024-03-01 15:00 UTC
**Build scan:**
https://gradle-enterprise.elastic.co/s/bjvkojojf4ekc/tests/:x-pack:plugin:repositories-metering-api:qa:azure:javaRestTest/org.elasticsearch.xpack.repositories.metering.azure.AzureRepositoriesMeteringIT/testStatsAreArchivedAfterRepositoryDeletion

**Test failures**
[elasticsearch / periodic / 8.13 / third-party / azure](https://gradle-enterprise.elastic.co/s/bjvkojojf4ekc)
Test failures:
[AzureRepositoriesMeteringIT » testClearRepositoriesStats](https://gradle-enterprise.elastic.co/s/bjvkojojf4ekc/tests/:x-pack:plugin:repositories-metering-api:qa:azure:javaRestTest/org.elasticsearch.xpack.repositories.metering.azure.AzureRepositoriesMeteringIT/testClearRepositoriesStats)
[AzureRepositoriesMeteringIT » testStatsAreTracked](https://gradle-enterprise.elastic.co/s/bjvkojojf4ekc/tests/:x-pack:plugin:repositories-metering-api:qa:azure:javaRestTest/org.elasticsearch.xpack.repositories.metering.azure.AzureRepositoriesMeteringIT/testStatsAreTracked)
[AzureRepositoriesMeteringIT » testRegisterMultipleRepositoriesAndGetStats](https://gradle-enterprise.elastic.co/s/bjvkojojf4ekc/tests/:x-pack:plugin:repositories-metering-api:qa:azure:javaRestTest/org.elasticsearch.xpack.repositories.metering.azure.AzureRepositoriesMeteringIT/testRegisterMultipleRepositoriesAndGetStats)
[AzureRepositoriesMeteringIT » testDeleteThenAddRepositoryWithTheSameName](https://gradle-enterprise.elastic.co/s/bjvkojojf4ekc/tests/:x-pack:plugin:repositories-metering-api:qa:azure:javaRestTest/org.elasticsearch.xpack.repositories.metering.azure.AzureRepositoriesMeteringIT/testDeleteThenAddRepositoryWithTheSameName)
[AzureRepositoriesMeteringIT » testStatsAreArchivedAfterRepositoryDeletion](https://gradle-enterprise.elastic.co/s/bjvkojojf4ekc/tests/:x-pack:plugin:repositories-metering-api:qa:azure:javaRestTest/org.elasticsearch.xpack.repositories.metering.azure.AzureRepositoriesMeteringIT/testStatsAreArchivedAfterRepositoryDeletion)

**Reproduction line:**
```
./gradlew ':x-pack:plugin:repositories-metering-api:qa:azure:javaRestTest' --tests "org.elasticsearch.xpack.repositories.metering.azure.AzureRepositoriesMeteringIT.testStatsAreArchivedAfterRepositoryDeletion" -Dtests.seed=35579160B1CCDAFB -Dtests.locale=lt -Dtests.timezone=Etc/GMT+9 -Druntime.java=21
```

**Applicable branches:**
8.13

**Reproduces locally?:**
No

**Failure history:**
[Failure dashboard for `org.elasticsearch.xpack.repositories.metering.azure.AzureRepositoriesMeteringIT#testStatsAreArchivedAfterRepositoryDeletion`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testStatsAreArchivedAfterRepositoryDeletion'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.repositories.metering.azure.AzureRepositoriesMeteringIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
org.elasticsearch.client.ResponseException: method [POST], host [http://[::1]:35993], URI [_snapshot/yvwzjtrfot/botvekesxg/_restore?wait_for_completion=true], status line [HTTP/1.1 500 Internal Server Error]
{"error":{"root_cause":[{"type":"snapshot_restore_exception","reason":"[yvwzjtrfot:botvekesxg/9xSEHhi-RyehlqqA0XEQ9A] cannot restore index [bqkleqgcdm] because an open index with same name already exists in the cluster. Either close or delete the existing index or restore the index under a different name by providing a rename pattern and replacement name"}],"type":"snapshot_restore_exception","reason":"[yvwzjtrfot:botvekesxg/9xSEHhi-RyehlqqA0XEQ9A] cannot restore index [bqkleqgcdm] because an open index with same name already exists in the cluster. Either close or delete the existing index or restore the index under a different name by providing a rename pattern and replacement name"},"status":500}

  at __randomizedtesting.SeedInfo.seed([35579160B1CCDAFB:417ABC912FB90BDB]:0)
  at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:351)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:317)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:292)
  at org.elasticsearch.test.rest.ESRestTestCase.restoreSnapshot(ESRestTestCase.java:1990)
  at org.elasticsearch.xpack.repositories.metering.AbstractRepositoriesMeteringAPIRestTestCase.snapshotAndRestoreIndex(AbstractRepositoriesMeteringAPIRestTestCase.java:252)
  at org.elasticsearch.xpack.repositories.metering.AbstractRepositoriesMeteringAPIRestTestCase.snapshotAndRestoreIndex(AbstractRepositoriesMeteringAPIRestTestCase.java:214)
  at org.elasticsearch.xpack.repositories.metering.AbstractRepositoriesMeteringAPIRestTestCase.testStatsAreArchivedAfterRepositoryDeletion(AbstractRepositoriesMeteringAPIRestTestCase.java:144)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.elasticsearch.test.cluster.local.DefaultLocalElasticsearchCluster$1.evaluate(DefaultLocalElasticsearchCluster.java:47)
  at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by mosche** [comment] 2024-03-01 15:03
similar
[AzureRepositoriesMeteringIT » testRegisterMultipleRepositoriesAndGetStats](https://gradle-enterprise.elastic.co/s/bjvkojojf4ekc/tests/:x-pack:plugin:repositories-metering-api:qa:azure:javaRestTest/org.elasticsearch.xpack.repositories.metering.azure.AzureRepositoriesMeteringIT/testRegisterMultipleRepositoriesAndGetStats)

**Comment by pxsalehi** [comment] 2024-05-23 09:41
There were a lot of failures in this suite due to invalid credentials which have been change. The only relevant failures in the past two months are two: https://es-delivery-stats.elastic.dev/app/r/s/5CAv8

One seem to be an http connection timeout which I would consider an infra issue. The other one seems to be a generic problem in the suite that occasionally happens. When we take a snapshot, we remove the index. However, it seems sometimes this removal doesn't work, and restore fails because there is already an open index with the same name. I haven't been able to reproduce this, but I will open a specific issue for that one failure example so we can track this. I will close this one.

**Closed** 2024-05-23 09:42 UTC
Labels: :Distributed/Snapshot/Restore, >test-failure, Team:Distributed, medium-risk
