### ISSUE TITLE
SQL : 'like' can not work

### ISSUE THREAD

**Issue by liujin1993** [elastic/elasticsearch#37031] opened 2018-12-29 08:59 UTC
I use es6.5.1
![image](https://user-images.githubusercontent.com/31949674/50536005-de087780-0b8a-11e9-8031-7985a02f5b52.png)

my sql is:
select max(return_sku_size) from \"recommend-retrieval-2018.12.29\" where platform like 'ra%'
it returns "Cannot evaluate script for expression LikePattern[ra%,\u0000]"

but when sql is:
select return_sku_size from \"recommend-retrieval-2018.12.29\" where platform like 'ra%'
it is normal.
![image](https://user-images.githubusercontent.com/31949674/50536031-20ca4f80-0b8b-11e9-974c-226e6d9be4ec.png)

**Comment by astefan** [comment] 2019-01-07 09:18
@liujin1993 the issue you reported is a duplicate of https://github.com/elastic/elasticsearch/issues/36161, which has been fixed in the meantime and will be available in 6.6.0.

**Closed by astefan** 2019-01-07 09:18 UTC
Labels: :Search/SQL
