### ISSUE TITLE
:distribution:docker:composeUp failure

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#48565] opened 2019-10-28 09:07 UTC
https://gradle-enterprise.elastic.co/s/4w3ijtjcanqmy

```
ERROR: for elasticsearch-default-1  Cannot start service elasticsearch-default-1: unable to remount dir as readonly: mount tmpfs:/var/lib/docker/containers/b243469fb78f29f925ffcfa0232e349e0c1851db84972794ef1a9ee1628bb2e1/mounts/secrets, flags: 0x21, data: uid=0,gid=0: device or resource busy

08:53:40 Execution failed for task ':distribution:docker:composeUp'.
08:53:40 > Exit-code 1 when calling /usr/local/bin/docker-compose, stdout: N/A
``

**Comment by atorok** [comment] 2019-10-28 10:38
duplicate of #48027

**Closed by atorok** 2019-10-28 10:38 UTC
Labels: :Core/Infra/Packaging, >test-failure
