### ISSUE TITLE
GET after DELETE Rollup Job results in a 200

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch#34292] opened 2018-10-04 09:02 UTC
```json
PUT https://127.0.0.1:9200/_xpack/rollup/job/rollup-fluent-945a5ac0-rollupjob?pretty=true&error_trace=true HTTP/1.1
Accept: application/json
Authorization: Basic **************
Content-Type: application/json
Content-Length: 475
Host: 127.0.0.1:9200

{
  "index_pattern": "logs-*",
  "rollup_index": "rollup-fluent-945a5ac0-rollupjob",
  "cron": "*/30 * * * * ?",
  "page_size": 1000,
  "groups": {
    "date_histogram": {
      "field": "timestamp",
      "interval": "1h"
    },
    "terms": {
      "fields": [
        "section",
        "tag"
      ]
    }
  },
  "metrics": [
    {
      "field": "temperature",
      "metrics": [
        "avg",
        "min",
        "max"
      ]
    }
  ]
}
```

Then issue a DELETE:

```
DELETE https://127.0.0.1:9200/_xpack/rollup/job/rollup-fluent-945a5ac0-rollupjob?pretty=true&error_trace=true HTTP/1.1
Accept: application/json
Authorization: Basic **************
Content-Length: 0
Host: 127.0.0.1:9200

```

Both of these operations return a 200:

```json
{
  "acknowledged" : true
}
```

If we do a GET after the delete

```
GET https://127.0.0.1:9200/_xpack/rollup/job/rollup-fluent-945a5ac0-rollupjob?pretty=true&error_trace=true HTTP/1.1
Accept: application/json
Authorization: Basic **************
Host: 127.0.0.1:9200

```

We get a 200 again:

```
HTTP/1.1 200 OK
content-type: application/json; charset=UTF-8
content-length: 19

{
  "jobs" : [ ]
}
````

Whereas if we try to DELETE this resource again we get a 404 as expected:

```json
HTTP/1.1 404 Not Found
content-type: application/json; charset=UTF-8
content-length: 3460

{
  "error" : {
    "root_cause" : [
      {
        "type" : "resource_not_found_exception",
        "reason" : "the task with id rollup-fluent-945a5ac0-rollupjob doesn't exist",
        "stack_trace" : "...."
      }
    ],
    "type" : "resource_not_found_exception",
    "reason" : "the task with id rollup-fluent-945a5ac0-rollupjob doesn't exist",
    "stack_trace" : "....."
  },
  "status" : 404
}
```

**Comment by jimczi** [comment] 2018-10-04 09:34
This is a duplicate of https://github.com/elastic/elasticsearch/issues/33919. Hence closing, thanks @Mpdreamz

**Closed by jimczi** 2018-10-04 09:34 UTC
