### ISSUE TITLE
./bin/elasticsearch M3 JDK ERROR

### ISSUE THREAD

**Issue by Changgf** [elastic/elasticsearch#115044] opened 2024-10-17 19:22 UTC
### Elasticsearch Version

8.15.2

### Java Version

_bundled_

### OS Version

M3

### Problem Description

![Image](https://github.com/user-attachments/assets/cc8539ad-2860-44cc-8aa8-9a9a5ea01da8)

### Steps to Reproduce

 ./bin/elasticsearch

**Comment by pxsalehi** [comment] 2024-10-18 10:37
Please provide more details, and what the issue is.

**Comment by pxsalehi** [comment] 2024-10-18 10:40
I'll close this. Feel free to re-open with more details about where you've download ES from, and what the exact issue is.

**Closed by pxsalehi** 2024-10-18 10:40 UTC
Labels: >bug, needs:triage
