### ISSUE TITLE
Expose Lucene 5's heap explain API

### ISSUE THREAD

**Issue by synhershko** [elastic/elasticsearch#10857] opened 2015-04-28 16:57 UTC
The new explain API for detailing heap usage can be a huge help in debugging large Elasticsearch systems - for performance or crashes

Obviously if you can add the ES's structures to this functionality , all the better

https://issues.apache.org/jira/browse/LUCENE-5949

**Comment by rmuir** [comment] 2015-04-28 16:58
Duplicate of #9111

**Closed by rmuir** 2015-04-28 16:58 UTC

**Comment by synhershko** [comment] 2015-04-28 17:00
Cool, thanks
