### ISSUE TITLE
We should not allocate too many newly created shards to newly joined nodes

### ISSUE THREAD

**Issue by kkewwei** [elastic/elasticsearch#76219] opened 2021-08-08 12:06 UTC
As it's known to all, Considering the overall balance, ES will allocate too much newly created shards to the newly joined nodes. The load of newly joined nodes will be very high because most of incoming document will be writing into the newly created shards, especially when the proportion of new joined nodes is very small, the situation will be very scary.

The overall balance is determined by two aspects: `cluster.routing.allocation.balance.index` and `cluster.routing.allocation.balance.shard`. If we could not taking the new joined nodes into consideration for overall balance, Or the allocation of the newly created shards will be only determined by : `cluster.routing.allocation.balance.index`.

**Comment by DaveCTurner** [comment] 2021-08-08 18:21
Closing this as a duplicate of #17213.

**Closed by DaveCTurner** 2021-08-08 18:21 UTC
Labels: >enhancement, needs:triage
