### ISSUE TITLE
RestClientMultipleHostsIntegTests frequently failing in CI

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#45577] opened 2019-08-14 20:35 UTC
We have had a large number of failures of tests in `org.elasticsearch.client.RestClientMultipleHostsIntegTests` failing in `master` over the last couple of days.

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(test,class,branch),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:kuery,query:'class:%20"org.elasticsearch.client.RestClientMultipleHostsIntegTests"'),sort:!(time,desc))

Since these tests don't use `ESTestCase` there's no reproduction line so it's hard to determine if this is reproducible with a particular test seed.

**Comment by mark-vieira** [comment] 2019-08-14 20:37
This test has been muted in `master` in 4a6c9f7df25e8de2fc56eb0eb47d7043735ebf99.

**Comment by javanna** [comment] 2019-08-15 06:00
I am digging into these failures. They have to do with #45379 where we added support for cancelling requests in the low-level REST client. Note that I think only `testCancelAsyncRequests` should have been muted. When that one fails, it does in quite a bad way as the client crashes, which makes all the subsequent tests fail also. @mark-vieira would you mind if I remove the ignore from the whole test and mute only the `testCancelAsyncRequests` method?

**Comment by mark-vieira** [comment] 2019-08-15 07:23
> @mark-vieira would you mind if I remove the ignore from the whole test and mute only the testCancelAsyncRequests method?

Feel free to do what you need to in order to get things stable again. Keep in mind that although _most_ of recent failures are the `testCancelAsyncRequests` test, others such as `testAsyncRequests` and `testSyncRequests` have failed recently too, although not as often.

**Comment by javanna** [comment] 2019-08-15 07:41
@mark-vieira I saw but I think that those other tests have failed as a consequence of the other one failing. The underlying client is static, reused throughout different tests, and it crashed while executing testCancelAsyncRequests.

**Comment by javanna** [comment] 2019-08-15 14:09
see https://issues.apache.org/jira/browse/HTTPCORE-591 which causes these failures.

**Comment by tlrx** [comment] 2019-10-25 15:16
The test failed multiple times today:
https://gradle-enterprise.elastic.co/s/diof5e3ijkd2g
https://gradle-enterprise.elastic.co/s/inkideseqek4e

Looking at the [build stats](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-90d,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'class:%22org.elasticsearch.client.restclientmultiplehostsintegtests%22%20AND%20test:%22testCancelAsyncRequests%22'),sort:!(time,desc))), the test failed multiple times in the last 90 days.

**Comment by mark-vieira** [comment] 2021-03-12 00:46
This failed again today: https://gradle-enterprise.elastic.co/s/poaiyju55xbpc/tests/:client:rest:test/org.elasticsearch.client.RestClientMultipleHostsIntegTests/testCancelAsyncRequests#1

Looks like something inside apache HTTP client blew up with an NPE which is likely the root cause of the test hanging.

**Comment by martijnvg** [comment] 2021-04-06 09:32
Another instance of this failure: https://gradle-enterprise.elastic.co/s/paviu7zr5cjbi/console-log#L1559
This test [failed twice](https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=Europe/Amsterdam&tests.container=org.elasticsearch.client.RestClientMultipleHostsIntegTests&tests.sortField=FAILED&tests.test=testCancelAsyncRequests&tests.unstableOnly=true) in the last 7 days.

**Comment by tlrx** [comment] 2021-06-01 12:43
Despite of #45808 and #70003 this test is still failing multiple times per week on master, 7.x and 7.13.

All failures I looked at were on Windows platforms with an Open JDK 15.0.2+7-27 and the following error:
```

  2> Jun 01, 2021 10:32:17 AM org.apache.http.impl.nio.client.InternalHttpAsyncClient run
  2> SEVERE: I/O reactor terminated abnormally
  2> java.lang.NullPointerException
  2> 	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:170)
  2> 	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:148)
  2> 	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:351)
  2> 	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:221)
  2> 	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
  2> 	at java.base/java.lang.Thread.run(Thread.java:834)
```
which seems to be fixed in HTTP Core NIO in version 4.4.13 (see https://issues.apache.org/jira/browse/HTTPCORE-609)

@elastic/es-core-features I'm going to mute this test again but I think this deserve some investigation.

**Comment by dimitris-athanasiou** [comment] 2021-07-12 09:14
We got a possibly related failure in the 6.8 branch for `testNodeSelector` test: https://gradle-enterprise.elastic.co/s/vqdvfkk2ucrxu/console-log?task=:client:rest:unitTest

Can someone confirm this is caused by the same issue? Should I mute the test in 6.8 or is this a different kind of failure?

**Comment by swallez** [comment] 2023-02-14 13:25
No update for more than 1 year, closing. Reopen if needed.

**Closed by swallez** 2023-02-14 13:25 UTC
Labels: >test-failure, :Clients/Java Low Level REST Client, Team:Clients

**Comment by cbuescher** [comment] 2023-10-31 10:23
While on test triage I just discovered this test is still muted. I suspect that's why we didn't see anything here for so long and will re-enable the test for now.
