### ISSUE TITLE
Node stats api does not correctly provide  mem.used_percent information

### ISSUE THREAD

**Issue by yangjiajun2014** [elastic/elasticsearch#27157] opened 2017-10-28 02:51 UTC
I call _node stats api to see the running state of my elasticsearch node running in a linux server.The api shows that mem.used_percent of my machine is 99%.But the top command shows that the server exactly uses about 11% memory and  most of memory is allocated to buffer/cache.According to linux mechanism,the memory in buffer/cache is available,or I am in trouble with this situation.

**Comment by jasontedor** [comment] 2017-10-29 23:42
No, it's intended that used memory includes the pages allocated to the filesystem cache. The used memory is calculated as the total physical memory on the system minus the free physical memory on the system. The free physical memory on the system is ultimately obtained from `sysconf(_SC_AVPHYS_PAGES)` on Linux which includes only the pages the OS can allocate without flushing the cache or paging to disk. I am closing this as operating as intended.

**Closed by jasontedor** 2017-10-29 23:42 UTC
Labels: :Stats, docs
