### ISSUE TITLE
Using dynamic_date_format across multiple types causes errors

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#15138] opened 2015-12-01 09:01 UTC
First reported on discuss forum: https://discuss.elastic.co/t/mapping-problem-with-dynamic-date-formats-es-2-0/35955

If you set `dynamic_date_formats` in the mappings and then try to index two documents in separate types and error is raised on the second index request even though the date format on the second document is the same so no mapping update should be necessary.

```
$ curl -XPUT http://localhost:9200/myIndex -d '{"mappings": {"_default_": 
    { "dynamic_date_formats": ["yyyy-MM-dd"]}
}}'

$ curl -XPOST http://localhost:9200/myIndex/type1 -d '{"myDate":"2015-01-01"}'

$ curl -XPOST http://localhost:9200/myIndex/type2 -d '{"myDate":"2015-01-02"}'
```

Stack Trace:
```
[2015-12-01 08:54:41,115][INFO ][rest.suppressed          ] /my-index/type2 Params: {update_all_types=, index=my-index, type=type2}
java.lang.IllegalArgumentException: Mapper for [myDate] conflicts with existing mapping in other types:
[mapper [myDate] is used by multiple types. Set update_all_types to true to update [format] across all types.]
	at org.elasticsearch.index.mapper.FieldTypeLookup.checkCompatibility(FieldTypeLookup.java:109)
	at org.elasticsearch.index.mapper.MapperService.checkNewMappersCompatibility(MapperService.java:317)
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:268)
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:214)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:334)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:252)
	at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:401)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:596)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by jpountz** [comment] 2015-12-21 12:32
I could reproduce the bug. This is due to how we handle dynamic mapping updates when a field already exists in another type. Closing in favour of #15568

**Closed by jpountz** 2015-12-21 12:32 UTC
Labels: :Mapping, adoptme, bug, v2.1.2, v2.2.0, v3.0.0
