### ISSUE TITLE
changing search_analyzer on existing field returns error

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#15185] opened 2015-12-02 14:50 UTC
Trying to change the search analyzer for an existing field through put mapping api:

```
PUT test/my_type/1
{
  "field":"value"
}

PUT test/_mapping/my_type
{
  "properties": {
    "field" : {
      "type": "string",
      "search_analyzer": "keyword"
    }
  }
}
```

I get back "analyzer on field [field] must be set when search_analyzer is set". The error seems to imply that I have to add the "analyzer" too, although it is the default one already. Adding `"analyzer": "standard"` as follows:

```
PUT test/_mapping/my_type
{
  "properties": {
    "field" : {
      "type": "string",
      "search_analyzer": "keyword",
      "analyzer": "standard"
    }
  }
}
```

causes a "Merge failed with failures {[mapper [field] has different [analyzer]]}". I am not sure what I am doing wrong or whether there is a bug somewhere, but at least the errors here really need to be improved and clarified.

**Comment by nik9000** [comment] 2015-12-02 15:18
That sounds like trouble. I'm pretty sure I remember changing the search analyzer on the fly a few times.

**Comment by jimferenczi** [comment] 2015-12-02 15:40
By default the analyzer is set with the name "default" (and not "standard" though default points to "standard" ...). If you change the analyzer name to "default" you'll be able to change the search_analyzer ;)

**Comment by javanna** [comment] 2015-12-02 16:10
cool thanks @jimferenczi !  still I don't get why one has to specify the analyzer (and has to know to use default instead of standard). It might make sense for new mappings to be explicit, not for fields that are already defined. Seems like bad user experience to me.

**Comment by rjernst** [comment] 2015-12-02 19:27
I agree it makes sense only for new mappings. I think the problem is simply that standard and default are not considered "the same".

**Comment by rjernst** [comment] 2015-12-02 19:37
Scratch my last statement. We have no way to distinguish when this is a "new mapping" vs an "update".

**Comment by rjernst** [comment] 2015-12-02 19:42
I also think this is actually a good thing. It makes it very clear to the user that they now have 2 analyzers acting on the field.

**Comment by djschny** [comment] 2015-12-02 20:47
Agree with @javanna that this is a bad user experience. I fail to see how this makes it very clear to the user.

Perhaps instead make it so when you `GET` a mapping instead of having implied values that are not present, we always explicitly include in the json the analyzer so that way users will be able to see the `default` vs `standard` situation.

**Comment by rjernst** [comment] 2015-12-02 21:27
@djschny I was not referring to the problem with `default` vs `standard`. The request in first post here that included `analyzer` should have worked. We should fix that. I was only referring to the fact that `analyzer` must be included when updating `search_analyzer`.

**Comment by javanna** [comment] 2015-12-02 23:21
I understand in general that being explicit is better, but if we just want to change the search_analyzer, and an analyzer is already defined for the field, and we don't want to change that analyzer, why should one be forced to specify again that same analyzer, which is also the only one that will be accepted (as the index analyzer cannot be changed)? That seems misleading from a user perspective, the fact that technically it's challenging to distinguish between new mappings and updates is a different story, that we may or may not have to deal with internally.

**Comment by jpountz** [comment] 2015-12-21 10:48
Mappings have a way to apply a default source. For instance this is how the `_default_` mapping is applied. On the contrary when a mapping already exists for a given type, we don't apply any defaults. I'm wondering that maybe this issue could be solved by applying the current mapping as a default source when mappings for a type already exist?

**Comment by clintongormley** [comment] 2016-02-14 18:34
@jpountz that sounds like a plan

**Comment by clintongormley** [comment] 2016-02-14 18:35
And honestly the requirement to have to be explicit about setting an analyzer when adding a search_analyzer is just annoying - I see no real benefit in this requirement.

**Comment by jpountz** [comment] 2018-03-13 18:19
cc @elastic/es-search-aggs

**Comment by cbuescher** [comment] 2021-02-25 16:56
Just revisiting this on 7.11, the original scenario in this issue works now, that is:
```
DELETE test

PUT test/_doc/1
{
  "field":"value"
}

PUT test/_mapping
{
  "properties": {
    "field" : {
      "type": "text",
      "search_analyzer": "keyword"
    }
  }
}
```
won't error anymore, but instead "field" will then be set to  `"analyzer" : "default",  "search_analyzer" : "keyword"`.
Users still need to repeat the "analyzer" setting when the initial one wasn't the default one, but working on #40008 we agreed this should be a documentation change. That why I think its okay for me to close this issue.

**Closed by cbuescher** 2021-02-25 16:56 UTC
Labels: :Search/Mapping, >bug, Team:Search
