### ISSUE TITLE
[CI] Packaging Test 071 BindMountCustomPathWithDifferentUID failure for UBI

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#61614] opened 2020-08-27 05:05 UTC
**Build scan**: https://gradle-enterprise.elastic.co/s/rmxnfg5jcgyno/tests/:qa:os:destructiveDistroTest.default-docker_ubi/org.elasticsearch.packaging.test.DockerTests/test071BindMountCustomPathWithDifferentUID#1

**Repro line**: 
```
./gradlew :qa:os:destructiveDistroTest.default-docker_ubi
```

**Reproduces locally?**: N/A 

**Applicable branches**: master

**Failure excerpt**:
```
org.elasticsearch.packaging.util.Shell$ShellException: Command was not successful: [bash -c docker run --rm --volume "/tmp/DockerTests2807067604740472611:/mount" alpine /bin/sh -c "cd /mount && rm -r esDataDir"] 
  result: exitCode = [1] stdout = [] stderr = [rm: can't remove 'esDataDir/_state': Directory not empty]
```

Possibly related to #61194

**Comment by pugnascotia** [comment] 2020-08-27 08:05
Probably a duplicate of #61553, but I'll live this issue open until I can confirm.

**Closed** 2020-09-01 11:03 UTC
Labels: :Core/Infra/Packaging, >test-failure, Team:Core/Infra
