### ISSUE TITLE
JarHell does not check whether a given path entry exists

### ISSUE THREAD

**Issue by tberne** [elastic/elasticsearch#15052] opened 2015-11-26 18:03 UTC
When embedding ES in Websphere Application Server (don't know the app server version right now), it is breaking boot because of:

> Caused by: java.lang.IllegalStateException: failed to load bundle [] due to jar hell
> 	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:342)
> 	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:113)
> 	at org.elasticsearch.node.Node.<init>(Node.java:144)
> 	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
> 	at org.elasticsearch.node.NodeBuilder.node(NodeBuilder.java:152)
> 	... 97 more
> Caused by: java.io.FileNotFoundException: C:\Program Files (x86)\IBM\WebSphere\AppServer\lib\jsf-nls.jar 
> (The system cannot find the file specified)
> 	at java.util.zip.ZipFile.open(Native Method)
> 	at java.util.zip.ZipFile.<init>(ZipFile.java:231)
> 	at java.util.zip.ZipFile.<init>(ZipFile.java:161)
> 	at java.util.jar.JarFile.<init>(JarFile.java:169)
> 	at java.util.jar.JarFile.<init>(JarFile.java:106)
> 	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:173)
> 	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:340)
> 	... 104 more

The correction is as simple as an if in [JarHell](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/bootstrap/JarHell.java#L174).

**Comment by rmuir** [comment] 2015-11-26 19:12
The classpath should not contain non-existent elements though, that is just indicative of a bug.

**Comment by tberne** [comment] 2015-11-26 19:42
I couldn't disagree, but still it is a commonly used application server and because of the assumption that the jar file exists I am unable to deploy ES on Websphere.

I already implemented a workaround (for instance, I transformed JarHell.checkJarHell(URL[]) in a dummy method via Javassist).

I just think that a simple if could solve my problem (and possibly others). And there's no simple workaround for that, since Websphere's classpath is not under my control.

**Comment by rmuir** [comment] 2015-11-26 19:46
It destroys the entire purpose of this class. The purpose is to fail when the codebases are incorrect, not to be lenient like javas classloading and deliver strange errors later.

**Comment by tberne** [comment] 2015-11-26 19:52
Agreed. But I need to deploy ES on Websphere. I have no control on its classpath. What should I do?
I also think CheckJarHell is a good think, but I have no other option since I have no control on generated classpath.
I think that many others may reach this very same problem.

**Comment by s1monw** [comment] 2015-11-26 21:45
why don't you add the missing jar file instead?

**Comment by tberne** [comment] 2015-11-27 01:10
@s1monw, I'm going to check whether this install is ok. But, once more, if the install is ok and it is an issue of Websphere, how could I deploy ES?

**Comment by s1monw** [comment] 2015-11-27 19:54
> @s1monw, I'm going to check whether this install is ok. But, once more, if the install is ok and it is an issue of Websphere, how could I deploy ES?

well I guess if you can't fix it you need to wait until it's fixed in on the websphere end?

**Comment by tberne** [comment] 2015-11-27 20:27
Well, this is not an option at all. Given that CheckJarHell is susceptible to this kind of classpath failure and I can't fix the classpath, there's only one way: completely disable CheckJarHell through Javassist.

BTW, in [Java SE Documentation](https://docs.oracle.com/javase/7/docs/technotes/tools/windows/classpath.html), it is said that "Classpath entries that are neither directories nor archives (.zip or .jar files) nor * are ignored.".

This makes me think the CheckJarHell should have the same behavior.

**Comment by nik9000** [comment] 2015-11-28 14:56
> This makes me think the CheckJarHell should have the same behavior.

I think JarHell is intentionally being more strict that the spec.

Are you trying to embed the Elasticsearch server in websphere or just the client?

**Comment by rmuir** [comment] 2015-11-28 15:02
> I think JarHell is intentionally being more strict that the spec.

Exactly, as already explained above. Adding any leniency like classpath elements that don't exist will only hide bugs, e.g. hiding errors of wrong file permissions and so on, and instead delivering confusing NoClassDefFoundError later. 

The problem is, anytime someone has jar hell, they want leniency for their specific case: if we were to do this, it would already be a no-op check and be useless.

**Comment by tberne** [comment] 2015-11-28 20:08
@nik9000, we embed Elasticsearch. Depending on the client configuration, it will act as a client or as a server. In our product we do not recommend to use the embedded ES as a server for production, but it is configurable.

@rmuir, I don't think a no-op check (like I did with Javassist) is the only option here. There could be a blacklist of classpath entries (and/or classes maybe?) or something so this strange scenario could be solved without making CheckJarHell useless. This way the specific (ugly) problem could be fixed and CJH would still play along.

**Comment by rjernst** [comment] 2015-11-28 21:00
> There could be a blacklist of classpath entries (and/or classes maybe?) or something so this strange scenario could be solved without making CheckJarHell useless.

That is exactly the leniency that would make it useless, because you could then configure JarHell to essentially do nothing (by blacklisting every jar). JarHell is an upfront check for potentially buggy behavior. As @rmuir explained above, a file "not existing" could be an error in our security policy which does not grant access to the jar.

**Comment by s1monw** [comment] 2015-11-30 09:15
I agree we can't really loosen the strictness here. This is something that IMO should be build-in to Java but it isn't. We can't add workarounds for broken 3rd party installations, those installations need to be fixed instead. We try to prevent hunting any ghosts because of class file clashes or broken installations. If we make this check lenient or add a flag it's entire purpose vanishes.

**Comment by tberne** [comment] 2015-11-30 12:23
Guys, you forgot we live in a real world, where not always we will have complete control over everything. If you decide to let CJH as it is, I will understand. But in a real world those things happen. And whenever they happen, someone will have to do dirty things (like Javassisting and make CJH no-op).

**Comment by rmuir** [comment] 2015-11-30 12:42
Its not really that. Its just that jarhell gets *SO MUCH HATE* because its the first thing that will fail for you.

But really, if you run inside any container, you are in for a world of pain, because such a configuration is completely untested.

The point of jarhell is to fail early and hard on stupid problems, hence users whine about it. But it is not the issue, the problem is your broken configuration.

**Closed by rmuir** 2015-11-30 12:42 UTC
