### ISSUE TITLE
Explain API ignores search_type

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#2612] opened 2013-02-04 03:14 UTC
It appears that the Explain API ignores search_type.  I'm unsure if this is by design, or because of an underlying limitation, but thought it deserved an issue report.

Here is an example query showing scoring disparity due to low doc count (5 docs) spread across 5 shards.  Perfectly normal for a `query_then_fetch` search_type:

```
curl -XGET localhost:9200/startswith/test/_search?pretty -d '{                                                          "query": {
        "match_phrase_prefix": {
           "title": {
             "query": "d",
             "max_expansions": 5
           }
         }
       }
     }' | grep title

      "_score" : 1.0, "_source" : {"title":"drunk"}
      "_score" : 0.30685282, "_source" : {"title":"dzone"}
      "_score" : 0.30685282, "_source" : {"title":"data"}
      "_score" : 0.30685282, "_source" : {"title":"drive"}
```

Same query with search_type set to `dfs_query_then_fetch`, showing appropriate scoring:

```
 curl -XGET 'localhost:9200/startswith/test/_search?pretty=true&search_type=dfs_query_then_fetch' -d '{
        "query": {
        "match_phrase_prefix": {
           "title": {
             "query": "d",
             "max_expansions": 5
           }
         }
       }
     }' | grep title

      "_score" : 1.9162908, "_source" : {"title":"dzone"}
      "_score" : 1.9162908, "_source" : {"title":"data"}
      "_score" : 1.9162908, "_source" : {"title":"drunk"}
      "_score" : 1.9162908, "_source" : {"title":"drive"}
```

Ok, with the verification out of the way, here are the corresponding Explain API examples for the "dzone" document, which in the above example has differential scoring depending on the search_type.  It appears that the Explain API completely ignores the search_type, since the score remains unaffected and maxDocs does not change.

```
curl -XGET 'localhost:9200/startswith/test/gvgXfR5YRSaXu7PfFc4FkA/_explain?pretty=true&search_type=query_then_fetch' -d '{
        "query": {
        "match_phrase_prefix": {
           "title": {
             "query": "d",
             "max_expansions": 5
           }
         }
       }
     }'
{
  "ok" : true,
  "_index" : "startswith",
  "_type" : "test",
  "_id" : "gvgXfR5YRSaXu7PfFc4FkA",
  "matched" : true,
  "explanation" : {
    "value" : 0.30685282,
    "description" : "fieldWeight(title:dzone in 0), product of:",
    "details" : [ {
      "value" : 1.0,
      "description" : "tf(termFreq(title:dzone)=1)"
    }, {
      "value" : 0.30685282,
      "description" : "idf(docFreq=1, maxDocs=1)"
    }, {
      "value" : 1.0,
      "description" : "fieldNorm(field=title, doc=0)"
    } ]
  }
```

And now dfs_query_then_fetch:

```
#curl -XGET 'localhost:9200/startswith/test/gvgXfR5YRSaXu7PfFc4FkA/_explain?pretty=true&search_type=dfs_query_then_fetch' -d '{
        "query": {
        "match_phrase_prefix": {
           "title": {
             "query": "d",
             "max_expansions": 5
           }
         }
       }
     }'
{
  "ok" : true,
  "_index" : "startswith",
  "_type" : "test",
  "_id" : "gvgXfR5YRSaXu7PfFc4FkA",
  "matched" : true,
  "explanation" : {
    "value" : 0.30685282,
    "description" : "fieldWeight(title:dzone in 0), product of:",
    "details" : [ {
      "value" : 1.0,
      "description" : "tf(termFreq(title:dzone)=1)"
    }, {
      "value" : 0.30685282,
      "description" : "idf(docFreq=1, maxDocs=1)"
    }, {
      "value" : 1.0,
      "description" : "fieldNorm(field=title, doc=0)"
    } ]
  }
```

**Comment by vaniaravinda** [comment] 2015-08-03 10:47
Hi,
Can someone let me know how to use "search_type": "DFS_query_then_fetch" in Sense plugin query.

Thanks,
Vani Aravinda

**Comment by clintongormley** [comment] 2016-05-06 13:19
Duplicate of #15369

**Closed by clintongormley** 2016-05-06 13:19 UTC
Labels: :Search, adoptme, bug, low hanging fruit, v2.4.0
