### ISSUE TITLE
Feature to set a ttl at the index level rather than only at the document level

### ISSUE THREAD

**Issue by casieowen** [elastic/elasticsearch#15699] opened 2015-12-29 18:17 UTC
Hi -- 
According to what I'm hearing in the community, there is a feature request in to allow for setting a ttl at the index level rather than only at the doc level.  See here: https://discuss.elastic.co/t/set-a--ttl-value-at-the-index-level/31668/3 where theuntergeek -- Aaron Mildenstein says "there is no index-level TTL presently. There's a feature request issue out for it (I forget the number), but it has not yet been added."  and https://discuss.elastic.co/t/index-level-ttl-how-do-we-track-this-feature-request/37775 where warkolm (Mark Walkom) responded to my request about how to track such a feature with "It'd be in here - https://github.com/elastic/elasticsearch/issues/1.  If you find it, please link it here so others can benefit :smile: (I couldn't find it!)"

I've checked in issues and features and am not finding anything.  Can someone please point me to where to track this feature request?  I'm surprised there isn't more noise about this one, since it would make index maintenance much simpler.

Thanks,
Casie

**Comment by eskibars** [comment] 2015-12-29 18:41
The existing feature request is at https://github.com/elastic/elasticsearch/issues/2114.  It was closed because [curator](https://github.com/elastic/curator) can already do this and it's fairly easy to do so ([delete](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/delete.html) + [index selection](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/index-selection.html)).  I'm going to close this issue as it seems like it's an exact duplicate of https://github.com/elastic/elasticsearch/issues/2114.  If the existing curator functionality doesn't fill your needs, feel free to +1 and/or comment in there and we can always consider reopening it.

**Closed by eskibars** 2015-12-29 18:41 UTC

**Comment by casieowen** [comment] 2015-12-29 19:00
Thanks. Yes, I know curator can do it, but setting a ttl at the index level at time of creation is way more efficient.  Will +1 and/or comment in 2114,
