### ISSUE TITLE
distance calculation incorrect

### ISSUE THREAD

**Issue by q2434006** [elastic/elasticsearch#55092] opened 2020-04-11 03:05 UTC
The current version is 7.2
When performing distance screening, I feel that the calculated distance is not very accurate.
from [104.182362,35.940037 ] to  [104.1699800758683,35.942937057779]
in es the result is 922.04770917729m
but in googlemap is 1163m
Is it something I use

![image](https://user-images.githubusercontent.com/12470760/79033894-8a396a80-7be4-11ea-8d88-b6ba01e0374b.png)

![image](https://user-images.githubusercontent.com/12470760/79033866-4f373700-7be4-11ea-9b3b-c31c1ef431e2.png)

**Comment by iverase** [comment] 2020-04-14 07:02
There is something that doesn't make sense in your example. The sorting seems to be done on a field called `geometry` and the result is compared to a field called `shape`. I think you are not comparing the right fields, could you provide a full example with mappings? I tried myself and I get the following distance which is under the field's precision:

```
"sort" : [
          1160.3966211614975
        ]
```

**Comment by iverase** [comment] 2020-06-12 09:31
I am going to close this issue as we did not get the information requested and our reproduction was showing correct results. Please tree to reopen if necessary.

**Closed by iverase** 2020-06-12 09:31 UTC
Labels: :Analytics/Geo, Team:Analytics
