### ISSUE TITLE
ILM time schedule

### ISSUE THREAD

**Issue by vbohata** [elastic/elasticsearch#39596] opened 2019-03-02 02:24 UTC
Some operations like forcemerge creates a significant load to the cluster and should not be performed in business hours. Is there any way to force some actions wait until defined maintenance time or assign them some maintenance hours window? If not I think it should be implemented as it is a must have feature to be able to migrate from curator,

**Comment by dakrone** [comment] 2019-03-04 17:08
Closing this as a duplicate of #37325

**Closed by dakrone** 2019-03-04 17:08 UTC
Labels: :Core/Features/ILM
