### ISSUE TITLE
[CI] AsyncSearchActionTests fails unpredictably

### ISSUE THREAD

**Issue by williamrandolph** [elastic/elasticsearch#53360] opened 2020-03-10 19:33 UTC
We've had a couple of test failures from `AsyncSearchActionTests` today. The failures haven't reproduced locally for me.

Failure on `master`: https://gradle-enterprise.elastic.co/s/asvh7ted2nfvy/

```
org.elasticsearch.xpack.search.AsyncSearchActionTests > testInvalidId FAILED |  
-- | --
  | java.lang.AssertionError: Values should be different. Actual: 2 |  
  | at org.junit.Assert.fail(Assert.java:88) |  
  | at org.junit.Assert.failEquals(Assert.java:185) |  
  | at org.junit.Assert.assertNotEquals(Assert.java:199) |  
  | at org.junit.Assert.assertNotEquals(Assert.java:211) |  
  | at org.elasticsearch.xpack.search.AsyncSearchIntegTestCase$2.lambda$doNext$0(AsyncSearchIntegTestCase.java:214) |  
  | at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:881) |  
  | at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:854) |  
  | at org.elasticsearch.xpack.search.AsyncSearchIntegTestCase$2.doNext(AsyncSearchIntegTestCase.java:209) |  
  | at org.elasticsearch.xpack.search.AsyncSearchIntegTestCase$2.next(AsyncSearchIntegTestCase.java:187) |  
  | at org.elasticsearch.xpack.search.AsyncSearchIntegTestCase$2.next(AsyncSearchIntegTestCase.java:172) |  
  | at org.elasticsearch.xpack.search.AsyncSearchActionTests.testInvalidId(AsyncSearchActionTests.java:234) |  
  |   |  
  | java.lang.AssertionError: Accounting breaker not reset to 0 on node: node_sd3, are there still Lucene indices around? |  
  | Expected: <0L> |  
  | but: was <11134L> |  
  | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18) |  
  | at org.junit.Assert.assertThat(Assert.java:956) |  
  | at org.elasticsearch.test.InternalTestCluster.lambda$ensureEstimatedStats$37(InternalTestCluster.java:2195) |  
  | at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:881) |  
  | at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:854) |  
  | at org.elasticsearch.test.InternalTestCluster.ensureEstimatedStats(InternalTestCluster.java:2193) |  
  | at org.elasticsearch.test.TestCluster.assertAfterTest(TestCluster.java:90) |  
  | at org.elasticsearch.test.InternalTestCluster.assertAfterTest(InternalTestCluster.java:2235) |  
  | at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:550) |  
  | at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:1936) |  
  […]
```

Earlier failure on ~7.x~ master: https://gradle-enterprise.elastic.co/s/3pjzmjjxc66wi
```
org.elasticsearch.xpack.search.AsyncSearchActionTests > testCleanupOnFailure FAILED |  
-- | --
  | java.lang.AssertionError: |  
  | Expected: <6> |  
  | but: was <5> |  
  | at __randomizedtesting.SeedInfo.seed([43B69EECA92F38A8:C8A2BFFE0F2A2760]:0) |  
  | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18) |  
  | at org.junit.Assert.assertThat(Assert.java:956) |  
  | at org.junit.Assert.assertThat(Assert.java:923) |  
  | at org.elasticsearch.xpack.search.AsyncSearchActionTests.testCleanupOnFailure(AsyncSearchActionTests.java:221)
```

I believe @jimczi is working on this actively, but I'm going to go ahead and mute while he's in progress.

Relates #49931

**Comment by williamrandolph** [comment] 2020-03-11 16:28
@jimczi Thanks for handling this!

**Comment by jimczi** [comment] 2020-03-11 16:30
thanks for muting @williamrandolph , I'll watch the build since I was not able to reproduce the exact same exceptions locally.

**Comment by jimczi** [comment] 2020-03-11 16:40
Reopened since it failed on the first build :(

**Comment by mayya-sharipova** [comment] 2020-03-11 18:24
Another failure just occurred on master, and this failure occurred even with the @jimczi latest commit: 
```
Changes
...
Fix sporadic failures in AsyncSearchActionTests (take 2) (commit: eba2b03) (details / githubweb)
```

REPRODUCE WITH: ./gradlew ':x-pack:plugin:async-search:test' --tests "org.elasticsearch.xpack.search.AsyncSearchActionTests.testInvalidId" \
  -Dtests.seed=A1BCB56A6A844751 \
  -Dtests.security.manager=true \
  -Dtests.jvm.argline="-XX:-UseConcMarkSweepGC -XX:-UseSerialGC -XX:+UseG1GC" \
  -Dtests.locale=ms-MY \
  -Dtests.timezone=America/Indiana/Knox \
  -Dcompiler.java=13

this tests and several other tests.   Do NOT reproduce for me on master.

Log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/845/console
Build Scans: https://gradle-enterprise.elastic.co/s/4f4s44z7rp5fa

```
java.lang.AssertionError: Values should be different. Actual: 6
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failEquals(Assert.java:185)
at org.junit.Assert.assertNotEquals(Assert.java:199)
at org.junit.Assert.assertNotEquals(Assert.java:211)
at org.elasticsearch.xpack.search.AsyncSearchIntegTestCase$2.lambda$doNext$0(AsyncSearchIntegTestCase.java:211)
```

**Comment by gwbrown** [comment] 2020-03-12 19:04
There was another failure just now on master, [Jenkins build](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob+fast+part2/4218/) and [Build scan](https://gradle-enterprise.elastic.co/s/qfgdfhile6zb6)

**Comment by jimczi** [comment] 2020-03-16 15:55
Thanks @mayya-sharipova , a backport was missing, I pushed https://github.com/elastic/elasticsearch/commit/dc2edc97f09e8d914a0fd98a2a9cc75311d9073e and will watch the build in 7.x before closing.

**Comment by jimczi** [comment] 2020-03-20 12:34
The tests seem stable in master and 7.x, hence closing.

**Comment by ywangd** [comment] 2020-03-31 23:48
This started to fail for "darwin-compatibility" since March 27 for `master`, `7.x` and `7.7`. On CI, all tests of this class fail all the time for "darwin-compatibility", see following trend:

https://gradle-enterprise.elastic.co/scans/tests?list.size=50&list.sortColumn=startTime&list.sortOrder=desc&search.buildToolType=gradle&search.buildToolType=maven&search.startTimeMax=1585698495283&search.startTimeMin=1585093695283&search.tags=CI&search.tags=MAC&search.tzOffset=660&tests.container=org.elasticsearch.xpack.search.AsyncSearchActionTests&tests.sortField=FAILED&tests.test=testNoIndex&tests.unstableOnly=true

But I _cannot_ reproduce locally:
```
./gradlew ':x-pack:plugin:async-search:test' --tests "org.elasticsearch.xpack.search.AsyncSearchActionTests.testNoIndex" \
  -Dtests.seed=49A4746586643385 \
  -Dtests.security.manager=true \
  -Dtests.locale=es-MX \
  -Dtests.timezone=SystemV/MST7MDT \
  -Dcompiler.java=13
```

Sample error message
```
:x-pack:plugin:async-search:test » org.elasticsearch.xpack.search.AsyncSearchActionTests » testNoIndex (11.246s)
6 channels still being tracked in RestCancellableNodeClient while there should be none expected:<0> but was:<6>
java.lang.AssertionError: 6 channels still being tracked in RestCancellableNodeClient while there should be none expected:<0> but was:<6>
```

Build scan:
https://gradle-enterprise.elastic.co/s/q4uaac6hl4jvu

Build log:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-darwin-compatibility/613/console

Failure email notification:
https://groups.google.com/a/elastic.co/forum/?utm_medium=email&utm_source=footer#!topic/build-elasticsearch/vxu0iDmfzcg

**Comment by ywangd** [comment] 2020-04-01 02:15
I am closing this issue as recent discussion is in #54180

**Closed by ywangd** 2020-04-01 02:15 UTC
Labels: :Search/Search, >test-failure
