### ISSUE TITLE
Analyzer is not parsing Emoji's on text fields

### ISSUE THREAD

**Issue by wmelton** [elastic/elasticsearch#62912] opened 2020-09-25 16:47 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 7.7.1

**Plugins installed**: []

**JVM version** (`java -version`): cloud.elastic.com

**OS version** (`uname -a` if on a Unix-like system): cloud.elastic.com

**Description of the problem including expected versus actual behavior**:
ElasticSearch indexer is not correctly parsing and storing Emojis. The text field is being saved with all emojis converted to question marks (?). 

For example: Here is the JSON field prior to insertion: 

``` 
  post_meta__comment: 'Making toniiiiiiiiiight 🧁   #cupcakes',
```

However in ES, the document field looks like this: 

```
"post_meta__comment": "Making toniiiiiiiiiight ?   #cupcakes"
```

This doesn't make sense because if we run `_analyze` on the same string/sentence, the analyzer returns the correct token definitions: 

```
{
    "tokens": [
        {
            "token": "making",
            "start_offset": 0,
            "end_offset": 6,
            "type": "<ALPHANUM>",
            "position": 0
        },
        {
            "token": "toniiiiiiiiiight",
            "start_offset": 7,
            "end_offset": 23,
            "type": "<ALPHANUM>",
            "position": 1
        },
        {
            "token": "🧁",
            "start_offset": 24,
            "end_offset": 26,
            "type": "<EMOJI>",
            "position": 2
        },
        {
            "token": "cupcakes",
            "start_offset": 29,
            "end_offset": 37,
            "type": "<ALPHANUM>",
            "position": 3
        }
    ]
}
```

This is the field definition in the mapping: 

```
"post_comment": {
                    "type": "text"
                }
```

**Steps to reproduce**:

 1. Create an index with a text field defined as above in the mapping example
 2. Insert the string 'Making toniiiiiiiiiight 🧁   #cupcakes' in a document in that field
 3. Query for the document by id. Emoji will be a `?` instead of the emoji or unicode value

**Comment by cbuescher** [comment] 2020-09-28 10:33
I cannot reproduce this. The following works for me in 7.7.1. Might be a client display issues, but the emoji value is indexed correctly, is searchable and shown in "_source" in the result in the kibana console and when querying locally with curl.

```
PUT /my-index/_doc/1
{
  "foo" : "Making toniiiiiiiiiight 🧁   #cupcakes"
}

GET /my-index/_doc/1

POST /my-index/_search

POST /my-index/_search
{
  "query": {
    "match": {
      "foo": "🧁"
    }
  }
}
```

**Comment by cbuescher** [comment] 2020-09-28 10:35
@wmelton I suspect a usage problem here, not a bug. Would you mind to follow up on this in the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and as long as this isn't reproducable I think it's more likely this is a usage question. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Please reopen if this can be narrowed down to an ES bug after all.

**Closed by cbuescher** 2020-09-28 10:35 UTC
Labels: :Search/Analysis, Team:Search, feedback_needed
