### ISSUE TITLE
[CI] Failure in IndexLevelReplicationTests.testSeqNoCollision

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#52148] opened 2020-02-10 14:42 UTC
See build scan [here](https://gradle-enterprise.elastic.co/s/a667hehu23iu4/tests/nfxodyych4uas-djctkaix5dfoq).

```

2> REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.index.replication.IndexLevelReplicationTests.testSeqNoCollision" -Dtests.seed=31094FBDA96BD170 -Dtests.security.manager=true -Dtests.locale=es-VE -Dtests.timezone=America/Guayaquil -Dcompiler.java=13 |  
-- | --
  | 2> java.lang.AssertionError: |  
  | Expected: <2> |  
  | but: was <1> |  
  | at __randomizedtesting.SeedInfo.seed([31094FBDA96BD170:833EF97CD3F49AF6]:0) |  
  | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18) |  
  | at org.junit.Assert.assertThat(Assert.java:956) |  
  | at org.junit.Assert.assertThat(Assert.java:923) |  
  | at org.elasticsearch.index.replication.IndexLevelReplicationTests.testSeqNoCollision(IndexLevelReplicationTests.java:574)

```

**Comment by dnhatn** [comment] 2020-02-10 14:57
Thanks Armin. This failure should relate to #51905. I am working on the fix now.

**Comment by dakrone** [comment] 2020-02-20 15:36
This failed again on the master intake build: https://gradle-enterprise.elastic.co/s/dxox6wl2v24su/tests/nfxodyych4uas-djctkaix5dfoq

**Comment by mark-vieira** [comment] 2020-02-20 17:39
We've had 15 failures today due to this so I've muted this test in `master` with dc070a541e5ef343bca11fb08715b8b2ba0c2e16.

@dnhatn given #51905 has been merged already it doesn't look like it addressed this issue. Do you mind taking another look. Given this failure reproduces locally we should aim to sort it out quickly.

**Comment by dnhatn** [comment] 2020-02-20 18:11
@mark-vieira Thanks for the ping. The recent failures are caused by #52556. I've opened #52588 to adjust the test.

**Comment by mark-vieira** [comment] 2020-02-20 19:30
Thanks @dnhatn!

**Closed** 2020-02-20 19:29 UTC
Labels: :Distributed/CRUD, >test-failure
