### ISSUE TITLE
[CI] bwc tests fail pre-6.3 old cluster tests

### ISSUE THREAD

**Issue by henningandersen** [elastic/elasticsearch#61710] opened 2020-08-31 11:33 UTC
**Build scan**:
https://gradle-enterprise.elastic.co/s/flk5apwuhcvxq
https://gradle-enterprise.elastic.co/s/gnmletkuohufk
(one per release before 6.3)

**Repro line**:

N/A

**Reproduces locally?**:
Did not try.

**Applicable branches**:

7.x

**Failure history**:
https://build-stats.elastic.co/goto/bfec24275e9f6e1be5bdfc39b95d2aa2

Started failing August 27th and have failed 280 builds since (total running against 11 pre-6.3 releases).

**Failure excerpt**:

I *think* this is the problem:
```
| ERROR: plugin directory [/dev/shm/elastic+elasticsearch+7.x+bwc/BWC_VERSION/6.0.1/nodes/centos-7&&immutable/build/elasticsearch-distros/extracted_elasticsearch_6.0.1_archive_linux_default/elasticsearch-6.0.1/plugins/x-pack] already exists; if you need to update the plugin, uninstall it first using command 'remove x-pack'

...

> Process 'command './bin/elasticsearch-plugin'' finished with non-zero exit value 1
```

**Comment by rjernst** [comment] 2020-08-31 15:43
duplicate of https://github.com/elastic/elasticsearch/issues/61643

**Closed by rjernst** 2020-08-31 15:43 UTC
Labels: :Core/Infra/Build, >test-failure, Team:Core/Infra, v7.10.0
