### ISSUE TITLE
Mix of transport and REST API breaks index template merging

### ISSUE THREAD

**Issue by chengangxiong** [elastic/elasticsearch#25899] opened 2017-07-26 09:12 UTC
es version: 5.2.2
we have to index template like this
```json
{
  "elog-default": {
    "order": 0,
    "template": "elog_*",
    "settings": {
      "index": {
        "mapper": {
          "dynamic": "true"
        },
        "mapping": {
          "ignore_malformed": "true"
        },
        "refresh_interval": "30s",
        "analysis": {
          "analyzer": {
            "default_search": {
              "lowercase": "true",
              "pattern": "\W|_",
              "type": "pattern"
            },
            "default": {
              "lowercase": "true",
              "pattern": "\W|_",
              "type": "pattern"
            }
          }
        },
        "number_of_shards": "9",
        "number_of_replicas": "1"
      }
    },
    "mappings": {
      "elog": {
        "_all": {
          "enabled": false
        },
        "properties": {
          "_ip": {
            "ignore_above": "32766",
            "type": "keyword"
          },
          "_log": {
            "type": "text"
          },
          "_collectTime": {
            "format": "yyyy-MM-dd HH:mm:ss",
            "type": "date"
          },
          "_hostName": {
            "type": "text"
          },
          "_fileName": {
            "type": "text"
          },
          "_sortedId": {
            "ignore_above": "32766",
            "type": "keyword"
          }
        }
      }
    },
    "aliases": {}
  }
}
```

the another 

```json
{
  "elog-esearch-canal": {
    "order": 1,
    "template": "elog_esearch-canal-20*",
    "settings": {},
    "mappings": {
      "elog": {
        "properties": {
          "logLevel": {
            "ignore_above": "32766",
            "type": "keyword"
          },
          "_log": {
            "type": "text"
          },
          "_time": {
            "format": "yyyy-MM-dd HH:mm:ss",
            "type": "date"
          }
        }
      }
    },
    "aliases": {}
  }
}
```

then create index 
elog_esearch-canal-20991
result is like this 

```json
{
  "settings": {
    "index": {
      "mapping": {
        "ignore_malformed": "true"
      },
      "refresh_interval": "30s",
      "number_of_shards": "9",
      "provided_name": "elog_esearch-canal-20991",
      "mapper": {
        "dynamic": "true"
      },
      "creation_date": "1501059220807",
      "analysis": {
        "analyzer": {
          "default_search": {
            "lowercase": "true",
            "pattern": "\W|_",
            "type": "pattern"
          },
          "default": {
            "lowercase": "true",
            "pattern": "\W|_",
            "type": "pattern"
          }
        }
      },
      "number_of_replicas": "1",
      "uuid": "eeEUja1NSSKpfgv6GwrWoA",
      "version": {
        "created": "5020299"
      }
    }
  },
  "mappings": {
    "elog": {
      "_all": {
        "search_analyzer": "default_search",
        "analyzer": "default",
        "enabled": false
      },
      "properties": {
        "logLevel": {
          "ignore_above": 32766,
          "type": "keyword"
        },
        "_ip": {
          "ignore_above": 32766,
          "type": "keyword"
        },
        "_log": {
          "search_analyzer": "default_search",
          "analyzer": "default",
          "type": "text"
        },
        "_collectTime": {
          "format": "yyyy-MM-dd HH:mm:ss",
          "type": "date"
        },
        "_hostName": {
          "search_analyzer": "default_search",
          "analyzer": "default",
          "type": "text"
        },
        "_fileName": {
          "search_analyzer": "default_search",
          "analyzer": "default",
          "type": "text"
        },
        "_sortedId": {
          "ignore_above": 32766,
          "type": "keyword"
        },
        "_time": {
          "format": "yyyy-MM-dd HH:mm:ss",
          "type": "date"
        }
      }
    }
  }
}
```

this is what we want.
then I modify the first template elog-default refresh_interval to "31s" in kibana devtool get&put 
and then create index elog_esearch-canal-20992
```json
{
  "state": "open",
  "settings": {
    "index": {
      "mapping": {
        "ignore_malformed": "true"
      },
      "refresh_interval": "31s",
      "number_of_shards": "9",
      "provided_name": "elog_esearch-canal-20992",
      "mapper": {
        "dynamic": "true"
      },
      "creation_date": "1501059247497",
      "analysis": {
        "analyzer": {
          "default_search": {
            "lowercase": "true",
            "pattern": "\W|_",
            "type": "pattern"
          },
          "default": {
            "lowercase": "true",
            "pattern": "\W|_",
            "type": "pattern"
          }
        }
      },
      "number_of_replicas": "1",
      "uuid": "7X6jKVxbTvGKNCG1V3FKhQ",
      "version": {
        "created": "5020299"
      }
    }
  },
  "mappings": {
    "elog": {
      "_all": {
        "search_analyzer": "default_search",
        "analyzer": "default",
        "enabled": false
      },
      "properties": {
        "_ip": {
          "ignore_above": 32766,
          "type": "keyword"
        },
        "_log": {
          "search_analyzer": "default_search",
          "analyzer": "default",
          "type": "text"
        },
        "_collectTime": {
          "format": "yyyy-MM-dd HH:mm:ss",
          "type": "date"
        },
        "_hostName": {
          "search_analyzer": "default_search",
          "analyzer": "default",
          "type": "text"
        },
        "_fileName": {
          "search_analyzer": "default_search",
          "analyzer": "default",
          "type": "text"
        },
        "_sortedId": {
          "ignore_above": 32766,
          "type": "keyword"
        }
      }
    }
  }
}
```

some properties like logLevel missing，I tried several times，the result same

**Comment by danielmitterdorfer** [comment] 2017-07-27 13:21
_Note_: I've reformatted the code blocks in your original message as they were hard to read.

Unfortunately, I cannot reproduce your problem. As your mappings are quite complex, I have created are reduced example. I've tested the following on 5.2.2.

```
PUT /_template/elog-default
{
   "order": 0,
   "template": "elog_*",
   "settings": {
      "refresh_interval": "30s"
   },
   "mappings": {
      "elog": {
         "properties": {
            "_log": {
               "type": "text"
            }
         }
      }
   }
}

PUT /_template/elog-esearch-canal
{
   "order": 1,
   "template": "elog_esearch-canal-20*",
   "settings": {},
   "mappings": {
      "elog": {
         "properties": {
            "logLevel": {
               "ignore_above": "32766",
               "type": "keyword"
            },
            "_log": {
               "type": "text"
            },
            "_time": {
               "format": "yyyy-MM-dd HH:mm:ss",
               "type": "date"
            }
         }
      }
   }
}

PUT /elog_esearch-canal-20991
```

The index is as expected. `GET /elog_esearch-canal-20991` gives:

```json
{
   "elog_esearch-canal-20991": {
      "aliases": {},
      "mappings": {
         "elog": {
            "properties": {
               "_log": {
                  "type": "text"
               },
               "_time": {
                  "type": "date",
                  "format": "yyyy-MM-dd HH:mm:ss"
               },
               "logLevel": {
                  "type": "keyword",
                  "ignore_above": 32766
               }
            }
         }
      },
      "settings": {
         "index": {
            "refresh_interval": "30s",
            "number_of_shards": "5",
            "provided_name": "elog_esearch-canal-20991",
            "creation_date": "1501161317965",
            "number_of_replicas": "1",
            "uuid": "IqjKlaN7TS6viGVpj8eK6Q",
            "version": {
               "created": "5020299"
            }
         }
      }
   }
}
```

Then we change the settings and create a new index:

```
PUT /_template/elog-default
{
   "order": 0,
   "template": "elog_*",
   "settings": {
      "refresh_interval": "31s"
   },
   "mappings": {
      "elog": {
         "properties": {
            "_log": {
               "type": "text"
            }
         }
      }
   }
}


PUT /elog_esearch-canal-20992
```

As expected, `GET /elog_esearch-canal-20992`gives all properties:

```json
{
   "elog_esearch-canal-20992": {
      "aliases": {},
      "mappings": {
         "elog": {
            "properties": {
               "_log": {
                  "type": "text"
               },
               "_time": {
                  "type": "date",
                  "format": "yyyy-MM-dd HH:mm:ss"
               },
               "logLevel": {
                  "type": "keyword",
                  "ignore_above": 32766
               }
            }
         }
      },
      "settings": {
         "index": {
            "refresh_interval": "31s",
            "number_of_shards": "5",
            "provided_name": "elog_esearch-canal-20992",
            "creation_date": "1501161394226",
            "number_of_replicas": "1",
            "uuid": "EKdpEic-Q5il412dYSKGHg",
            "version": {
               "created": "5020299"
            }
         }
      }
   }
}
```

Please also note that we reserve Github for bug reports and feature requests only. Please ask questions like these in the future [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch) instead.

**Comment by chengangxiong** [comment] 2017-07-28 03:23
@danielmitterdorfer 
Thank you for your reply very much
but maybe I made some error description
_**The important thing is the two index template created by java transport client, not in kibana**_
here I add some pictures to my operation
![es-01](https://user-images.githubusercontent.com/17596277/28701063-34e4041e-7386-11e7-885d-b84e8dfc805f.png)
![es-02](https://user-images.githubusercontent.com/17596277/28701065-3c4f7f08-7386-11e7-989f-1502f7dc0804.png)
**_these two index template created by java transport client_**
then create index from template, this index contain property "logLevel" and this is what I want
![es-04](https://user-images.githubusercontent.com/17596277/28701091-5a68ec86-7386-11e7-9675-75995bed9844.png)
then only modify the template "elog-default" setting refresh_interval from 30s to 31s in kibana
![es-05](https://user-images.githubusercontent.com/17596277/28701141-adcbb43a-7386-11e7-9421-cd4c8d76acac.png)
then create index from template again
![es-07](https://user-images.githubusercontent.com/17596277/28701166-d7e43e72-7386-11e7-9a7a-a8566d00b15a.png)
and some happend not as expected, the index donnot contain property "logLevel", the property  "time" is the same.

**Comment by danielmitterdorfer** [comment] 2017-07-28 05:44
Hi @chengangxiong. I now tried exactly this example again on a fresh install of Elasticsearch 5.2.2. I see that you are getting odd behavior but I just cannot reproduce it on a fresh install. So I suspect there is something in your environment intervening (a setting, maybe an application that proactively writes to the cluster, ...). So let's take a step back.

First of all, it does not make a difference how the index templates were created (transport client, REST client, curl, Kibana does not matter).

Can I please ask you to:

1. Shutdown all running Elasticsearch instances on your development machine (verify with `jps -v` on the command line. It should not show any Elasticsearch processes)
2. Install and start a  fresh installation of Elasticsearch 5.2.2.
3. Retry the following reproduction scenario (it should reflect exactly what you are doing above)

```
# Delete *all* index templates. Do not do this on a production cluster or you will potentially break your application.
DELETE /_template/*

# Delete *all* ""elog_" indices. Please do not do this on a production cluster or you will lose data.
DELETE /elog_*

PUT /_template/elog-default
{
   "order": 0,
   "template": "elog_*",
   "settings": {
      "index": {
         "mapper": {
            "dynamic": "true"
         },
         "mapping": {
            "ignore_malformed": "true"
         },
         "refresh_interval": "30s",
         "analysis": {
            "analyzer": {
               "default_search": {
                  "lowercase": "true",
                  "pattern": "\\W|_",
                  "type": "pattern"
               },
               "default": {
                  "lowercase": "true",
                  "pattern": "\\W|_",
                  "type": "pattern"
               }
            }
         },
         "number_of_shards": "9",
         "number_of_replicas": "1"
      }
   },
   "mappings": {
      "elog": {
         "_all": {
            "enabled": false
         },
         "properties": {
            "_ip": {
               "ignore_above": "32766",
               "type": "keyword"
            },
            "_log": {
               "type": "text"
            },
            "_collectTime": {
               "format": "yyyy-MM-dd HH:mm:ss",
               "type": "date"
            },
            "_hostName": {
               "type": "text"
            },
            "_fileName": {
               "type": "text"
            },
            "_sortedId": {
               "ignore_above": "32766",
               "type": "keyword"
            }
         }
      }
   },
   "aliases": {}
}

PUT /_template/elog-esearch-canal
{
   "order": 1,
   "template": "elog_esearch-canal-20*",
   "settings": {},
   "mappings": {
      "elog": {
         "properties": {
            "logLevel": {
               "ignore_above": "32766",
               "type": "keyword"
            },
            "_log": {
               "type": "text"
            },
            "_time": {
               "format": "yyyy-MM-dd HH:mm:ss",
               "type": "date"
            }
         }
      }
   },
   "aliases": {}
}

# ensure the index does not exist, then create the first index

DELETE /elog_esearch-canal-20991
PUT /elog_esearch-canal-20991

# verify mapping and settings
GET /elog_esearch-canal-20991

# Now we modify the refresh interval in the index template
PUT /_template/elog-default
{
   "order": 0,
   "template": "elog_*",
   "settings": {
      "index": {
         "mapper": {
            "dynamic": "true"
         },
         "mapping": {
            "ignore_malformed": "true"
         },
         "refresh_interval": "31s",
         "analysis": {
            "analyzer": {
               "default_search": {
                  "lowercase": "true",
                  "pattern": "\\W|_",
                  "type": "pattern"
               },
               "default": {
                  "lowercase": "true",
                  "pattern": "\\W|_",
                  "type": "pattern"
               }
            }
         },
         "number_of_shards": "9",
         "number_of_replicas": "1"
      }
   },
   "mappings": {
      "elog": {
         "_all": {
            "enabled": false
         },
         "properties": {
            "_ip": {
               "ignore_above": "32766",
               "type": "keyword"
            },
            "_log": {
               "type": "text"
            },
            "_collectTime": {
               "format": "yyyy-MM-dd HH:mm:ss",
               "type": "date"
            },
            "_hostName": {
               "type": "text"
            },
            "_fileName": {
               "type": "text"
            },
            "_sortedId": {
               "ignore_above": "32766",
               "type": "keyword"
            }
         }
      }
   },
   "aliases": {}
}

# ensure the index does not exist, then create an index after we've modified the index template.

DELETE /elog_esearch-canal-20992
PUT /elog_esearch-canal-20992

# verify mapping and settings
GET /elog_esearch-canal-20992
```

The last `GET` should produce the following output:

```json
{
   "elog_esearch-canal-20992": {
      "aliases": {},
      "mappings": {
         "elog": {
            "_all": {
               "enabled": false,
               "analyzer": "default",
               "search_analyzer": "default_search"
            },
            "properties": {
               "_collectTime": {
                  "type": "date",
                  "format": "yyyy-MM-dd HH:mm:ss"
               },
               "_fileName": {
                  "type": "text",
                  "analyzer": "default",
                  "search_analyzer": "default_search"
               },
               "_hostName": {
                  "type": "text",
                  "analyzer": "default",
                  "search_analyzer": "default_search"
               },
               "_ip": {
                  "type": "keyword",
                  "ignore_above": 32766
               },
               "_log": {
                  "type": "text",
                  "analyzer": "default",
                  "search_analyzer": "default_search"
               },
               "_sortedId": {
                  "type": "keyword",
                  "ignore_above": 32766
               },
               "_time": {
                  "type": "date",
                  "format": "yyyy-MM-dd HH:mm:ss"
               },
               "logLevel": {
                  "type": "keyword",
                  "ignore_above": 32766
               }
            }
         }
      },
      "settings": {
         "index": {
            "mapping": {
               "ignore_malformed": "true"
            },
            "refresh_interval": "31s",
            "number_of_shards": "9",
            "provided_name": "elog_esearch-canal-20992",
            "mapper": {
               "dynamic": "true"
            },
            "creation_date": "1501218848859",
            "analysis": {
               "analyzer": {
                  "default_search": {
                     "lowercase": "true",
                     "pattern": "\\W|_",
                     "type": "pattern"
                  },
                  "default": {
                     "lowercase": "true",
                     "pattern": "\\W|_",
                     "type": "pattern"
                  }
               }
            },
            "number_of_replicas": "1",
            "uuid": "Bh6ri5jqRyW2E4v-oI9-Hw",
            "version": {
               "created": "5020299"
            }
         }
      }
   }
}
```

After you have verified that this is working on a fresh installation of Elasticsearch 5.2.2 (this step is crucial because I still cannot reproduce this on a fresh installation), you should review the following on the cluster where this is happening:

* All templates that are defined for this cluster by issuing `GET /_template`.
* Cluster settings in the config file `config/elasticsearch.yml`
* Cluster settings setting set via the API by issuing `GET /_cluster/settings`

I hope this will reveal the cause.

**Comment by chengangxiong** [comment] 2017-07-28 09:26
Hi @danielmitterdorfer 
I tried it on a fresh installation, and the result same.
I got an conclusion : when I update template A(elog-default or elog-esearch-canal), then the index only contain properties from template A. 
And when the index template created from curl. everything is ok as you has reproduced.

Although the index properties are different , but the logs from es are same as below

[2017-07-28T16:52:21,042][INFO ][o.e.c.m.MetaDataCreateIndexService] [node-154] [elog_esearch-canal-209913] creating index, cause [api], templates [elog-esearch-canal, elog-default], shards [9]/[0], mappings [elog]
[2017-07-28T16:52:29,211][INFO ][o.e.c.m.MetaDataCreateIndexService] [node-154] [elog_esearch-canal-209914] creating index, cause [api], templates [elog-esearch-canal, elog-default], shards [9]/[1], mappings [elog]

Although you said there was no difference how the index templates were created, yes , I agree with you before I got the different result. so I hope you can write some java code to create index template. I'm feel sorry about that this cost you much time. And I will look deep into the es source code for this issue.

thank you again.

**Comment by danielmitterdorfer** [comment] 2017-07-28 09:37
Well, then the cause seems to be in how you create the index templates. Can you please come up with a minimal reproduction example involving your use of the transport client?

**Comment by chengangxiong** [comment] 2017-07-28 10:49
@danielmitterdorfer 
I write a minimal reproduction example: https://github.com/chengangxiong/forest/tree/master/forest-es
[forest-es-1.0-assembly.tar.gz](https://github.com/elastic/elasticsearch/files/1182756/forest-es-1.0-assembly.tar.gz)

you can run it : java -cp forest-es.jar:lib/* com.forest.es.main.CreateIndexTemplate localhost
localhost : es ip, only one ip 

it will create two index named "elog-default" "elog-esearch-canal", 

then create index "elog_esearch-canal-209901" contain properties "_collectTime", "_log", "_log2"
then update template "elog-default" modify nothing in kibana
then createindex "elog_esearch-canal-209902" contain properties "_collectTime", "_log"

**Comment by danielmitterdorfer** [comment] 2017-07-31 10:40
@chengangxiong Thanks for your persistence. I could indeed reproduce the issue now. I took your example and made it self-contained. Here is a summary.

### Problem

When index templates are created with the transport client and are updated via the REST API, template merging breaks and only the template with the lowest `order` is applied.

### Reproduction

1. Create multiple index templates via the transport client
2. Create an index that matches both templates. Verify that it contains all properties defined in the templates from (1).
3. Update the template with the highest order (i.e. order = 0 below) e.g. by defining a new index setting.
4. Create another index that matches both templates.

Expectation in step 4: The index contains all properties defined in the templates.
Actual outcome in step 4: The index contains only properties defined in the template with the highest order (i.e. order = 0 below).

Here is a minimal reproduction (working against 6.0.0-beta1):

```java
package org.elasticsearch.cli;

import org.apache.http.HttpHost;
import org.apache.http.message.BasicHeader;
import org.apache.http.nio.entity.NStringEntity;
import org.elasticsearch.action.admin.indices.create.CreateIndexRequest;
import org.elasticsearch.action.admin.indices.mapping.get.GetMappingsRequest;
import org.elasticsearch.action.admin.indices.mapping.get.GetMappingsResponse;
import org.elasticsearch.client.Client;
import org.elasticsearch.client.Response;
import org.elasticsearch.client.RestClient;
import org.elasticsearch.common.settings.Settings;
import org.elasticsearch.common.transport.TransportAddress;
import org.elasticsearch.common.xcontent.XContentBuilder;
import org.elasticsearch.common.xcontent.XContentFactory;
import org.elasticsearch.transport.client.PreBuiltTransportClient;

import java.io.IOException;
import java.net.InetAddress;
import java.nio.charset.StandardCharsets;
import java.util.Collections;
import java.util.Map;

public class TemplateInheritanceReproduction {
    private static Client transportClient;
    private static RestClient restClient;

    public static void main(String[] args) throws Exception {
        transportClient = new PreBuiltTransportClient(Settings.builder().put("client.transport.ignore_cluster_name", true).build())
                .addTransportAddress(new TransportAddress(InetAddress.getByName("localhost"), 9300));
        restClient = RestClient.builder(new HttpHost("localhost", 9200, "http")).build();

        try {
            createTemplatesAndIndices();
        } finally {
            restClient.close();
            transportClient.close();
        }
    }

    private static void createTemplatesAndIndices() throws Exception {
        transportClient.admin().indices()
            .preparePutTemplate("default-template")
            .setOrder(0)
                .setPatterns(Collections.singletonList("logs-*"))
            .addMapping("elog", createMapping("_log", "text"))
                .execute().actionGet();

        transportClient.admin().indices()
            .preparePutTemplate("specific-template")
            .setOrder(1)
                .setPatterns(Collections.singletonList("logs-my-app-*"))
            .addMapping("elog", createMapping("_log2", "text"))
                .execute().actionGet();

        // Will show both fields "_log" and "_log2" -> both templates got merged correctly
        createAndVerifyIndex("logs-my-app-20991");

        // update the default template via REST; mapping stays identical, settings change
        Response restResponse = restClient.performRequest("PUT", "/_template/default-template",
                Collections.emptyMap(),
                new NStringEntity("{" +
                        "\"order\": 0, \"template\": \"logs-*\"," +
                        // this is the actual change
                        "\"settings\": { \"index\": { \"refresh_interval\": \"31s\" } }," +
                        "\"mappings\": { \"elog\": { \"properties\": { \"_log\": { \"type\": \"text\" } } } }," +
                        "\"aliases\": {}" +
                        "}", StandardCharsets.UTF_8),
                new BasicHeader("Content-Type", "application/json"));

        System.out.println("Update index template via REST: " + restResponse.getStatusLine().getReasonPhrase());

        // Will only show "_log" from default template but not "_log2" from specific template.
        createAndVerifyIndex("logs-my-app-20992");
    }

    private static XContentBuilder createMapping(String propertyName, String type) throws IOException {
        return XContentFactory.jsonBuilder()
                .startObject()
                    .startObject("properties")
                        .startObject(propertyName)
                            .field("type", type)
                        .endObject()
                    .endObject()
                .endObject();
    }

    private static void createAndVerifyIndex(String index) throws IOException {
        transportClient.admin().indices().create(new CreateIndexRequest(index)).actionGet();
        GetMappingsResponse response = transportClient.admin().indices().getMappings(new GetMappingsRequest().indices(index)).actionGet();
        Map<String, String> props = (Map<String, String>) response.getMappings().get(index).get("elog").getSourceAsMap().get("properties");
        System.out.println("[" + index + "] has field _log: " + props.containsKey("_log"));
        System.out.println("[" + index + "] has field _log2: " + props.containsKey("_log2"));

    }
}
```

#### Additional findings

If we do the following: 

1. run the reproduction scenario
2. restart Elasticsearch
3. `PUT /logs-my-app-20993`

Then we get:

```
[2017-07-31T12:38:34,387][DEBUG][o.e.c.m.MetaDataCreateIndexService] [AeWwSiu] [logs-my-app-20993] failed to create
org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping [properties]: Root mapping definition has unsupported parameters:  [_log2 : {type=text}]
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:339) ~[elasticsearch-6.0.0-beta1-SNAPSHOT.jar:6.0.0-beta1-SNAPSHOT]
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:267) ~[elasticsearch-6.0.0-beta1-SNAPSHOT.jar:6.0.0-beta1-SNAPSHOT]
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$1.execute(MetaDataCreateIndexService.java:402) ~[elasticsearch-6.0.0-beta1-SNAPSHOT.jar:6.0.0-beta1-SNAPSHOT]
	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45) ~[elasticsearch-6.0.0-beta1-SNAPSHOT.jar:6.0.0-beta1-SNAPSHOT]
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:640) ~[elasticsearch-6.0.0-beta1-SNAPSHOT.jar:6.0.0-beta1-SNAPSHOT]
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:270) ~[elasticsearch-6.0.0-beta1-SNAPSHOT.jar:6.0.0-beta1-SNAPSHOT]
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:195) [elasticsearch-6.0.0-beta1-SNAPSHOT.jar:6.0.0-beta1-SNAPSHOT]
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:130) [elasticsearch-6.0.0-beta1-SNAPSHOT.jar:6.0.0-beta1-SNAPSHOT]
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [elasticsearch-6.0.0-beta1-SNAPSHOT.jar:6.0.0-beta1-SNAPSHOT]
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [elasticsearch-6.0.0-beta1-SNAPSHOT.jar:6.0.0-beta1-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) [elasticsearch-6.0.0-beta1-SNAPSHOT.jar:6.0.0-beta1-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:247) [elasticsearch-6.0.0-beta1-SNAPSHOT.jar:6.0.0-beta1-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:210) [elasticsearch-6.0.0-beta1-SNAPSHOT.jar:6.0.0-beta1-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: org.elasticsearch.index.mapper.MapperParsingException: Root mapping definition has unsupported parameters:  [_log2 : {type=text}]
	at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:151) ~[elasticsearch-6.0.0-beta1-SNAPSHOT.jar:6.0.0-beta1-SNAPSHOT]
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:139) ~[elasticsearch-6.0.0-beta1-SNAPSHOT.jar:6.0.0-beta1-SNAPSHOT]
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:91) ~[elasticsearch-6.0.0-beta1-SNAPSHOT.jar:6.0.0-beta1-SNAPSHOT]
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:336) ~[elasticsearch-6.0.0-beta1-SNAPSHOT.jar:6.0.0-beta1-SNAPSHOT]
	... 15 more
```

### Affected versions

I check the following versions and could reproduce this issue on all of them:

* 5.2.2
* 5.5.0
* 6.0.0-beta1

### Workaround

One workaround is to redefine *all* index templates in the inheritance chain via the REST API, even if nothing has actually changed. In the example above, we'd need to issue a `PUT /_templates/specific-template` with the original content.

**Comment by danielmitterdorfer** [comment] 2017-08-04 08:02
@chengangxiong I've found out why it is failing: you need to add the mapping type too in the XContent when you create the mapping. So instead of:

```java
XContentBuilder mapping = XContentFactory.jsonBuilder()
    .startObject()
        .startObject("properties")
            .startObject("_log")
                .field("type", "text")
            .endObject()
        .endObject()
    .endObject();
```

you need to create the mapping *including* the document type:

```java
XContentBuilder mapping = XContentFactory.jsonBuilder()
    .startObject()
        // define the document type
        .startObject("elog")
            .startObject("properties")
                .startObject("_log")
                    .field("type", "text")
                .endObject()
            .endObject()
        .endObject()
    .endObject();
```

As we can explain this misbehavior by wrong API usage, I'll close this ticket. So you need to change your client code to include the mapping type, then it will work fine.

However, I think that this behavior is trappy and I've created #26054 to discuss what we can do to improve the situation.

**Closed by danielmitterdorfer** 2017-08-04 08:02 UTC
Labels: :Index Templates, adoptme, bug, v6.0.0
