### ISSUE TITLE
Unicast ping request doesn't check the cluster name. 

### ISSUE THREAD

**Issue by ESamir** [elastic/elasticsearch#9617] opened 2015-02-09 15:57 UTC
[2015-02-06 15:09:56,722][INFO ][cluster.service ] [LONTTL-ELS03v] detected_master [LONTTL-ELS01v][He9uLnSxRD2w-w6_4e8d8A][LONTTL-ELS01V][inet[/10.128.3.216:9300]], added {[LONTTL-ELS01v][He9uLnSxRD2w-w6_4e8d8A][LONTTL-ELS01V][inet[/10.128.3.216:9300]],[LONTTL-ELS02v][UPV5NBl2TECGYiExIG_I8A][LONTTL-ELS02v][inet[/10.128.3.218:9300]],}, reason: zen-disco-receive(from master [[LONTTL-ELS01v][He9uLnSxRD2w-w6_4e8d8A][LONTTL-ELS01V][inet[/10.128.3.216:9300]]])

LONTTL-ELS03v is on cluster name TTL.LOCAL_MarvelServer

LONTTL-ELS02v and LONTTL-ELS01v are on cluster name TTL.LOCAL_ElasticSearch

The customer misconfigured the unicast configuration and added the following configuration in all the nodes in both cluster :
discovery.zen.ping.unicast.hosts: ["LONTTL-ELS01v","LONTTL-ELS02v","LONTTL-ELS03v"]

The  node LONTTL-ELS01v with one cluster name can discover a master with another cluster name when people misconfigured  unicast discovery,  because we do not check the cluster name in  unicast ping.

**Comment by clintongormley** [comment] 2015-12-05 15:17
Duplicate of #9615

**Closed by clintongormley** 2015-12-05 15:17 UTC
Labels: bug
