### ISSUE TITLE
Test Failure: org.elasticsearch.index.reindex.ReindexClientYamlTestSuiteIT 

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#23724] opened 2017-03-23 18:44 UTC
Unable to reproduce locally on Arch.

Reproduce with:

gradle :modules:reindex:integTest -Dtests.seed=F246EA1E2B3C0AAB -Dtests.class=org.elasticsearch.index.reindex.ReindexClientYamlTestSuiteIT -Dtests.method="test {yaml=reindex/90_remote/Reindex from remote with query}" -Dtests.security.manager=true -Dtests.locale=pt-PT -Dtests.timezone=GMT

Build Failure:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.2+dockeralpine-periodic/466/console

**Comment by nik9000** [comment] 2017-03-28 12:31
I can't reproduce this on 5.x and master and I merged https://github.com/elastic/elasticsearch/pull/23677 to it so I *think* this should be fixed, at least in 5.x.

**Closed by nik9000** 2017-03-28 12:31 UTC
Labels: :Reindex API, bug, test, v5.2.3
