### ISSUE TITLE
Allow disabling bootstrap checks explicitly

### ISSUE THREAD

**Issue by giftig** [elastic/elasticsearch#23580] opened 2017-03-14 13:38 UTC
When running elasticsearch in docker, in a development environment or when running builds, I need to have elasticsearch bind to 0.0.0.0 and/or publish a container hostname. This has the undesirable side-effect of enforcing bootstrap checks.

I understand the benefit of these bootstrap checks in production, but I question the assumption that you must be in production if you're binding to a non-local address, especially given the prevalence of docker. Having to modify the host to set `vm.max_map_count`, for example, severely limits the portability of my test environment for no real reason. It would be useful to be able to set a configuration setting explicitly indicating I am *not* in production and that the bootstrap checks are therefore unnecessary, rather than binding the assumption of development vs production to the hostname to which we choose to bind.

**Comment by dadoonet** [comment] 2017-03-14 13:58
Duplicate of #21655

**Closed by dadoonet** 2017-03-14 13:58 UTC

**Comment by jasontedor** [comment] 2017-04-04 13:53
We have added a new discovery type suitable for binding transport to an external interface for the purpose of testing the transport client against Elasticsearch in situations where might not have permissions to modify the configuration of the host to pass the bootstrap checks (for example, CI providers). To summarize the situation:
 - we have added a new discovery type called `single-node`
 - when a node uses the discovery type `single-node` it can not form a cluster with another node
 - when a node uses the discovery type `single-node` the bootstrap checks are disabled
 - for users that are running a node using discovery type `single-node` in production, they should enable the system property `es.enable.bootstrap.checks` to force the bootstrap checks to run; they are at their own risk if they do not do this

This is documented in the bootstrap checks docs.

This will be available starting with Elasticsearch 5.4.0.

**Comment by ebuildy** [comment] 2017-11-13 16:49
That mean we cannot test clustering in our laptop? not really clever, why not an explicit way to disable it?

**Comment by jasontedor** [comment] 2017-11-13 16:54
> That mean we cannot test clustering in our laptop?

Why not? You can still form a cluster with nodes that bind to localhost on your laptop.

**Comment by chitraj8** [comment] 2018-02-05 20:04
I am trying to setup ES 5.6 with single node, but the startup process fails due to boostrap checks.
how to disable them?

**Comment by ebuildy** [comment] 2018-02-06 08:34
@chitraj8 please read what @jaalcorn  just said with the single-node (or use the forum for questions).

**Comment by DjangoFR** [comment] 2019-03-29 16:35
@jasontedor i think what @ebuildy means is "We cannot test clustering in our _docker_ (one container per es-node)? To be able to simulate a cluster locally in development. And there it would be nice to have a way to explicit disable boostrap checks. Or what is the best way to get it working in docker?

**Comment by C-Duv** [comment] 2019-04-26 10:51
To make Elasticsearch API available to Docker containers while still only-binding Elasticsearch to *localhost* network interface (to avoid Elasticsearch *enforcing bootstrap checks*), I use [`redir`](https://linux.die.net/man/1/redir):
```
redir \
    --laddr $(ip -4 addr show docker0 | grep "inet\b" | awk '{print $2}' | cut -d '/' -f 1) \
    --lport 9201 \
    --caddr 127.0.0.1 \
    --cport 9200
```
Then I can use:
```
docker_host_ip=$( \
    ip route get 255.255.255.254 \
    | head -n 1 \
    | sed -E 's/^[\.0-9]{7,15} via ([\.0-9]{7,15}) dev .*$/\1/' \
)
curl http://${docker_host_ip}:9201
```
to access Elasticsearch API from within my Docker containers.
