### ISSUE TITLE
_meta field on mappings are not accepted on the scope of a field

### ISSUE THREAD

**Issue by fredgalvao** [elastic/elasticsearch#20218] opened 2016-08-29 19:22 UTC
**Elasticsearch version**:
`version[2.3.5]`

**Plugins installed**:
`[kopf, HQ]`

**JVM version**:
```
$ java -version
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
```

**OS version**:
```
$ uname -a
Linux <xxx> 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Description of the problem including expected versus actual behavior**:

According to the [reference mapping-type index page](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/mapping.html#mapping-type) and to the associated [reference meta-fields index page](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/mapping-fields.html) as well as the [reference _meta field page](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/mapping-meta-field.html), this was supposed to run successfully on a 2.3.x cluster:

**Steps to reproduce**:

DELETE /tweet
PUT /tweet

PUT /tweet/tweet/_mapping
```json
{
  "properties": {
    "tweet": {
      "type": "string",
      "analyzer": "english",
      "_meta": {
        "label": "This is a tweet body."
      }
    },
    "date": {
      "type": "date"
    },
    "name": {
      "type": "string"
    },
    "user_id": {
      "type": "long"
    },
    "_meta": {
      "label": "This is a tweet object."
    }
  },
  "_meta": {
    "label": "This is a tweet database."
  }
}
```

**Answer**:

```json
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "Mapping definition for [tweet] has unsupported parameters:  [_meta : {label=This is a tweet body.}]"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "Mapping definition for [tweet] has unsupported parameters:  [_meta : {label=This is a tweet body.}]"
  },
  "status": 400
}
```

Issue https://github.com/elastic/elasticsearch/issues/9649 mentioned it, and at the end it was commented that this was implemented and available. So I'm assuming it was either removed without a doc sync or it was broken recently. However, a quick lookup at the code searching for "_meta" got me to no place where MapperRegistry was ever used to register a Mapper for "_meta" attribute. I'm looking forward to being proven wrong though.

**Comment by nik9000** [comment] 2016-08-29 19:36
@clintongormley said that you could use `_meta` to document the fields, not that it was available on every field. Given that I think this is a duplicate of #9649 so I'll close it.

**Closed by nik9000** 2016-08-29 19:36 UTC

**Comment by fredgalvao** [comment] 2016-08-29 20:21
@nik9000 You're definitely right, I misread the docs.
