### ISSUE TITLE
test.iters may cause bad reproduce strings

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#38455] opened 2019-02-05 18:21 UTC
While investigating (https://github.com/elastic/elasticsearch/issues/38359), I ran the reproduce line with ```-Dtests.iters=1000``` and received 1 failure.  The reproduce line for that failure was the following:

```./gradlew :x-pack:plugin:monitoring:unitTest -Dtests.seed=1B6F728E6033F9E8 -Dtests.class=org.elasticsearch.xpack.monitoring.collector.node.NodeStatsMonitoringDocTests -Dtests.method="testToUTC {seed=[1B6F728E6033F9E8:E252917F49CF0B8F]}" -Dtests.security.manager=true -Dtests.locale=lv-LV -Dtests.timezone=GMT0 -Dcompiler.java=11 -Druntime.java=8```

When attempting to execute the reproduce line above with the embedded seed for testToUTC the test is ignored and skipped entirely.

**Comment by mark-vieira** [comment] 2020-12-18 23:29
This looks to be a duplicate of #31900.

**Closed by mark-vieira** 2020-12-18 23:29 UTC
Labels: :Delivery/Build, >bug, Team:Delivery
