### ISSUE TITLE
Cannot start Elasticsearch with non loopback address

### ISSUE THREAD

**Issue by calbatron** [elastic/elasticsearch#19987] opened 2016-08-14 01:59 UTC
Elastic 5a5
0 plugs
java 8u60
Amazon Linux AMI 2016.03

issue
When setting Elastic to a non local loop back ip, elasticserch fails to start

reproduce
elastic config -> network.host: network.host: 0.0.0.0
Starting elasticsearch:                                    [FAILED]

logs:
```
[2016-08-14 01:48:54,120][INFO ][plugins                  ] [egvE2n6] no plugins loaded
[2016-08-14 01:48:56,096][INFO ][node                     ] [egvE2n6] initialized
[2016-08-14 01:48:56,097][INFO ][node                     ] [egvE2n6] starting ...
[2016-08-14 01:48:56,194][INFO ][transport                ] [egvE2n6] publish_address {10.38.164.205:9300}, bound_addresses {[::]:9300}
[2016-08-14 01:48:56,198][INFO ][bootstrap                ] [egvE2n6] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
[2016-08-14 01:48:56,200][ERROR][bootstrap                ] [egvE2n6] Exception
java.lang.RuntimeException: bootstrap checks failed
initial heap size [268435456] not equal to maximum heap size [2147483648]; this can cause resize pauses and prevents mlockall from locking the entire heap
please set [discovery.zen.minimum_master_nodes] to a majority of the number of master eligible nodes in your cluster
	at org.elasticsearch.bootstrap.BootstrapCheck.check(BootstrapCheck.java:132)
	at org.elasticsearch.bootstrap.BootstrapCheck.check(BootstrapCheck.java:85)
	at org.elasticsearch.bootstrap.BootstrapCheck.check(BootstrapCheck.java:65)
	at org.elasticsearch.bootstrap.Bootstrap$5.validateNodeBeforeAcceptingRequests(Bootstrap.java:178)
	at org.elasticsearch.node.Node.start(Node.java:471)
	at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:193)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:257)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:101)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:96)
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:88)
	at org.elasticsearch.cli.Command.main(Command.java:54)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:75)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:68)
	Suppressed: java.lang.IllegalStateException: initial heap size [268435456] not equal to maximum heap size [2147483648]; this can cause resize pauses and prevents mlockall from locking the entire heap
		at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
		at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
		at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
		at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
		at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
		at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
		at java.util.stream.ReferencePipeline.forEach(Unknown Source)
		at org.elasticsearch.bootstrap.BootstrapCheck.check(BootstrapCheck.java:133)
		... 13 more
	Suppressed: java.lang.IllegalStateException: please set [discovery.zen.minimum_master_nodes] to a majority of the number of master eligible nodes in your cluster
		at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
		at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
		at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
		at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
		at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
		at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
		at java.util.stream.ReferencePipeline.forEach(Unknown Source)
		at org.elasticsearch.bootstrap.BootstrapCheck.check(BootstrapCheck.java:133)
		... 13 more
[2016-08-14 01:48:56,202][WARN ][bootstrap                ] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupError: java.lang.RuntimeException: bootstrap checks failed
initial heap size [268435456] not equal to maximum heap size [2147483648]; this can cause resize pauses and prevents mlockall from locking the entire heap
please set [discovery.zen.minimum_master_nodes] to a majority of the number of master eligible nodes in your cluster
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:105)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:96)
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:88)
	at org.elasticsearch.cli.Command.main(Command.java:54)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:75)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:68)
Caused by: java.lang.RuntimeException: bootstrap checks failed
initial heap size [268435456] not equal to maximum heap size [2147483648]; this can cause resize pauses and prevents mlockall from locking the entire heap
please set [discovery.zen.minimum_master_nodes] to a majority of the number of master eligible nodes in your cluster
	at org.elasticsearch.bootstrap.BootstrapCheck.check(BootstrapCheck.java:132)
	at org.elasticsearch.bootstrap.BootstrapCheck.check(BootstrapCheck.java:85)
	at org.elasticsearch.bootstrap.BootstrapCheck.check(BootstrapCheck.java:65)
	at org.elasticsearch.bootstrap.Bootstrap$5.validateNodeBeforeAcceptingRequests(Bootstrap.java:178)
	at org.elasticsearch.node.Node.start(Node.java:471)
	at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:193)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:257)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:101)
	... 6 more
	Suppressed: java.lang.IllegalStateException: initial heap size [268435456] not equal to maximum heap size [2147483648]; this can cause resize pauses and prevents mlockall from locking the entire heap
		at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
		at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
		at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
		at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
		at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
		at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
		at java.util.stream.ReferencePipeline.forEach(Unknown Source)
		at org.elasticsearch.bootstrap.BootstrapCheck.check(BootstrapCheck.java:133)
		... 13 more
	Suppressed: java.lang.IllegalStateException: please set [discovery.zen.minimum_master_nodes] to a majority of the number of master eligible nodes in your cluster
		at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
		at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
		at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
		at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
		at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
		at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
		at java.util.stream.ReferencePipeline.forEach(Unknown Source)
		at org.elasticsearch.bootstrap.BootstrapCheck.check(BootstrapCheck.java:133)
		... 13 more
[2016-08-14 01:48:56,203][INFO ][node                     ] [egvE2n6] stopping ...
[2016-08-14 01:48:56,217][INFO ][node                     ] [egvE2n6] stopped
[2016-08-14 01:48:56,217][INFO ][node                     ] [egvE2n6] closing ...
[2016-08-14 01:48:56,229][INFO ][node                     ] [egvE2n6] closed
```

**Comment by nik9000** [comment] 2016-08-14 02:03
Do the things it says and it'll start.

On Aug 13, 2016 9:59 PM, "Daniel Morrison" <notifications@github.com> wrote:

Elastic 5a5
0 plugs
java 8u60
Amazon Linux AMI 2016.03

issue
When setting Elastic to a non local loop back ip, elasticserch fails to
start

reproduce
elastic config -> network.host: network.host: 0.0.0.0
Starting elasticsearch: [FAILED]

logs:

[2016-08-14 01:48:54,120][INFO ][plugins                  ] [egvE2n6]
no plugins loaded
[2016-08-14 01:48:56,096][INFO ][node                     ] [egvE2n6]
initialized
[2016-08-14 01:48:56,097][INFO ][node                     ] [egvE2n6]
starting ...
[2016-08-14 01:48:56,194][INFO ][transport                ] [egvE2n6]
publish_address {10.38.164.205:9300}, bound_addresses {[::]:9300}
[2016-08-14 01:48:56,198][INFO ][bootstrap                ] [egvE2n6]
bound or publishing to a non-loopback or non-link-local address,
enforcing bootstrap checks
[2016-08-14 01:48:56,200][ERROR][bootstrap                ] [egvE2n6] Exception
java.lang.RuntimeException: bootstrap checks failed
initial heap size [268435456] not equal to maximum heap size
[2147483648]; this can cause resize pauses and prevents mlockall from
locking the entire heap
please set [discovery.zen.minimum_master_nodes] to a majority of the
number of master eligible nodes in your cluster
    at org.elasticsearch.bootstrap.BootstrapCheck.check(BootstrapCheck.java:132)
    at org.elasticsearch.bootstrap.BootstrapCheck.check(BootstrapCheck.java:85)
    at org.elasticsearch.bootstrap.BootstrapCheck.check(BootstrapCheck.java:65)
    at org.elasticsearch.bootstrap.Bootstrap$5.validateNodeBeforeAcceptingRequests(Bootstrap.java:178)
    at org.elasticsearch.node.Node.start(Node.java:471)
    at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:193)
    at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:257)
    at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:101)
    at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:96)
    at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
    at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:88)
    at org.elasticsearch.cli.Command.main(Command.java:54)
    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:75)
    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:68)
    Suppressed: java.lang.IllegalStateException: initial heap size
[268435456] not equal to maximum heap size [2147483648]; this can
cause resize pauses and prevents mlockall from locking the entire heap
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown
Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown
Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown
Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at org.elasticsearch.bootstrap.BootstrapCheck.check(BootstrapCheck.java:133)
        ... 13 more
    Suppressed: java.lang.IllegalStateException: please set
[discovery.zen.minimum_master_nodes] to a majority of the number of
master eligible nodes in your cluster
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown
Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown
Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown
Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at org.elasticsearch.bootstrap.BootstrapCheck.check(BootstrapCheck.java:133)
        ... 13 more
[2016-08-14 01:48:56,202][WARN ][bootstrap                ] []
uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupError: java.lang.RuntimeException:
bootstrap checks failed
initial heap size [268435456] not equal to maximum heap size
[2147483648]; this can cause resize pauses and prevents mlockall from
locking the entire heap
please set [discovery.zen.minimum_master_nodes] to a majority of the
number of master eligible nodes in your cluster
    at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:105)
    at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:96)
    at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
    at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:88)
    at org.elasticsearch.cli.Command.main(Command.java:54)
    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:75)
    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:68)
Caused by: java.lang.RuntimeException: bootstrap checks failed
initial heap size [268435456] not equal to maximum heap size
[2147483648]; this can cause resize pauses and prevents mlockall from
locking the entire heap
please set [discovery.zen.minimum_master_nodes] to a majority of the
number of master eligible nodes in your cluster
    at org.elasticsearch.bootstrap.BootstrapCheck.check(BootstrapCheck.java:132)
    at org.elasticsearch.bootstrap.BootstrapCheck.check(BootstrapCheck.java:85)
    at org.elasticsearch.bootstrap.BootstrapCheck.check(BootstrapCheck.java:65)
    at org.elasticsearch.bootstrap.Bootstrap$5.validateNodeBeforeAcceptingRequests(Bootstrap.java:178)
    at org.elasticsearch.node.Node.start(Node.java:471)
    at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:193)
    at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:257)
    at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:101)
    ... 6 more
    Suppressed: java.lang.IllegalStateException: initial heap size
[268435456] not equal to maximum heap size [2147483648]; this can
cause resize pauses and prevents mlockall from locking the entire heap
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown
Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown
Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown
Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at org.elasticsearch.bootstrap.BootstrapCheck.check(BootstrapCheck.java:133)
        ... 13 more
    Suppressed: java.lang.IllegalStateException: please set
[discovery.zen.minimum_master_nodes] to a majority of the number of
master eligible nodes in your cluster
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown
Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown
Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown
Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at org.elasticsearch.bootstrap.BootstrapCheck.check(BootstrapCheck.java:133)
        ... 13 more
[2016-08-14 01:48:56,203][INFO ][node                     ] [egvE2n6]
stopping ...
[2016-08-14 01:48:56,217][INFO ][node                     ] [egvE2n6] stopped
[2016-08-14 01:48:56,217][INFO ][node                     ] [egvE2n6]
closing ...
[2016-08-14 01:48:56,229][INFO ][node                     ] [egvE2n6] closed

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/elastic/elasticsearch/issues/19987>, or mute the thread

**Closed** 2016-08-14 02:05 UTC

**Comment by mingfang** [comment] 2016-11-10 17:39
why do you people keep making these pointless changes and then make others sound stupid for reporting it!

**Comment by jasontedor** [comment] 2016-11-10 17:42
@mingfang The checks have a point; we've explained their purpose on our [blog](https://www.elastic.co/blog/bootstrap_checks_annoying_instead_of_devastating) and in our [docs](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/bootstrap-checks.html).

**Comment by mingfang** [comment] 2016-11-10 17:44
@jasontedor Thanks for the links.

**Comment by jasontedor** [comment] 2016-11-10 17:45
@mingfang You are very welcome. :smile:

**Comment by junjiemars** [comment] 2016-12-30 03:39
I don't care about what the doc or explain, just one question: 
will listening on 0.0.0.0, and how to do that?

**Comment by cyrilcyril70** [comment] 2017-02-01 12:06
Worked on my AWS Linux Machine

cluster.name: myES_Cluster
node.name: ESNODE_CYR
node.master: true
node.data: true
transport.host: localhost
transport.tcp.port: 9300
http.port: 9200
network.host: 0.0.0.0
discovery.zen.minimum_master_nodes: 2

I have tried with this on the elasticsearch.yml (key:value) and worked fine for me. But it takes 2 days to fix it :wink: :slight_smile: , going on with ES Doc is so tough.

**Comment by treue** [comment] 2017-02-09 08:09
thanks a lot cyrilcyril70, this saved days of frustration for me :)

Question to the developers: Couldn't a minimal, working (but unsafe and inefficient) configuration (like the one presented) be included in the standard installations? Possibly a warning before using it could be implemented...

**Comment by mallan-patil** [comment] 2017-02-17 11:10
Thank you cyrilcyril70. You really saved me from going into frustration mode :)

**Comment by dmitrygrig** [comment] 2017-03-03 22:02
Thanks cyrilcyril70! works like a charm! 

BTW I have tried it out locally and found out that the problem occurs due to settings of transport host/tcp.port. 
configuration can be reduced to 
`transport.host: localhost
transport.tcp.port: 9300
http.port: 9200
network.host: 0.0.0.0`

**Comment by CuriousVini** [comment] 2017-03-11 03:04
Thanks @cyrilcyril70

**Comment by eperry** [comment] 2017-03-19 21:08
yah I totally don't get this non-local-address who thought is was a good idea. anywah. 

I can add localhost but when I add in the ip I want it bound to it says it is a non-loopback whicih is correct non-link-local address  which is false.   

The config works in 5.1 and now with this Bootcheck change it is causing me problems. Waz sup?
> 
> [2017-03-19T17:03:51,399][INFO ][o.e.t.TransportService   ] [hd1melk24lx-es-client-1] publish_address {10.32.42.204:9305}, bound_addresses {10.32.42.204:9305}
> [2017-03-19T17:03:51,403][INFO ][o.e.b.BootstrapChecks    ] [hd1melk24lx-es-client-1] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
> [2017-03-19T17:03:51,405][ERROR][o.e.b.Bootstrap          ] [hd1melk24lx-es-client-1] node validation exception
> bootstrap checks failed
> system call filters failed to install; check the logs and fix your configuration or disable system call filters at your own risk
> 

> bond0     Link encap:Ethernet  HWaddr 00:17:A4:77:08:04  
>           inet addr:10.32.42.204  Bcast:10.32.42.255  Mask:255.255.255.0
>           inet6 addr: fe80::217:a4ff:fe77:804/64 Scope:Link
>           UP BROADCAST RUNNING MASTER MULTICAST  MTU:1500  Metric:1

**Comment by jasontedor** [comment] 2017-03-19 21:18
@eperry It's here:

> system call filters failed to install; check the logs and fix your configuration or disable system call filters at your own risk

If you look higher in your logs, you'll see a message explaining why the system call filters failed to install. You can read more about this bootstrap check in the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/system-call-filter-check.html).

If you have additional questions, please start a topic on the [forum](https://discuss.elastic.co). Elastic reserves GitHub for verified bug reports and feature requests and prefers to keep general discussion off of issues, especially closed issues.

**Comment by eperry** [comment] 2017-03-19 21:30
opps did not see that this was closed but still very POOR messages there are no errors and if you can log that it failed to load you can repeat the actual problem validation. 

But anyway it is a closed issue I will go create a new thread.

**Comment by ChipmunkV** [comment] 2017-05-02 10:28
Reduced to this:

    transport.host: localhost
    network.host: 0.0.0.0

**Comment by chomenko** [comment] 2017-08-01 12:05
Díky moc cyrilcyril70

**Comment by pedrosk** [comment] 2017-11-28 22:03
This worked for me:
in elasticsearch.yml
^^^^^^^^^^^^^^^^^
http.port: 9201
#http.bind_host: 192.168.1.172 #works
http.publish_host: 192.168.1.172 #by itself does not work
http.host: 192.168.1.172 #works alone
====================
on /etc/hosts
192.168.1.172 mytestnode

**Comment by StrikerASD** [comment] 2018-04-06 12:41
Basically, you need to comment network.host to be able to use elasticsearch on non-loopback address.

**Comment by liuzexin** [comment] 2018-06-25 12:31
What a stupid configuration,How do you think about developer's user experience?

**Comment by AddoSolutions** [comment] 2019-05-06 15:14
There really needs to be an option for:

```
bootstrapCheck.enforcing: 0
```

**Comment by desprit** [comment] 2019-07-29 07:58
In my setup problem was here:

*wrong config*
```
environment:
  discovery.type: single-node
  transport.host: localhost
  transport.tcp.port: 9300
  http.port: 9200
  http.host: 0.0.0.0
```

*correct config*
```
environment:
  - discovery.type=single-node
  - transport.host=localhost
  - transport.tcp.port=9300
  - http.port=9200
  - http.host=0.0.0.0
```

**Comment by JackTrapper** [comment] 2020-01-31 13:16
Elastisearch comes *"broken by default"*. In order to have it listen on a network socket, you have to add **two** entries to your `elastisearch.yml` file:

**C:\ProgramData\Elastic\Elasticsearch\config\elasticsearch.yml**:

    network.host: 0.0.0.0
    discovery.seed_hosts: []

The first option will have Elastisearch open an actual network listening socket.  
The second option is needed to satisfy *something*. Nobody cares what the option is; it's just needed to make it shut up and do its job.

**Comment by DaveCTurner** [comment] 2020-01-31 13:54
> The second option is needed to satisfy _something_. Nobody cares what the option is; it's just needed to make it shut up and do its job.

That's not really true. It is needed as an explicit indication whether you intend this node to join a larger cluster or not. Elasticsearch cannot know this for certain either way, and it cannot guess without risking data loss. In the default "development mode" configuration it does guess and risks data loss as a result, but [this is not appropriate behaviour for production clusters](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery-bootstrap-cluster.html#_auto_bootstrapping_in_development_mode).

**Comment by JackTrapper** [comment] 2020-02-01 14:34
> It is needed as an explicit indication whether you intend this node to join a larger cluster or not. Elasticsearch cannot know this for certain either way, and it cannot guess without risking data loss.

Elastisearch can know this for certain: 

- there is only one node
- therefore there is only one node

If there was more than one node then: there would be more than one node.

**Comment by zhou-xia-ping** [comment] 2021-01-15 08:56
> Worked on my AWS Linux Machine
> 
> cluster.name: myES_Cluster
> node.name: ESNODE_CYR
> node.master: true
> node.data: true
> transport.host: localhost
> transport.tcp.port: 9300
> http.port: 9200
> network.host: 0.0.0.0
> discovery.zen.minimum_master_nodes: 2
> 
> I have tried with this on the elasticsearch.yml (key:value) and worked fine for me. But it takes 2 days to fix it 😉 :slight_smile: , going on with ES Doc is so tough.

you saved my life！

**Comment by Chris-Wazuh** [comment] 2021-04-22 14:52
> 
> 
> why do you people keep making these pointless changes and then make others sound stupid for reporting it!

Because when we need serious topologies we need
