### ISSUE TITLE
fuzziness AUTO option does not work as intended with edgeNgram analyzer

### ISSUE THREAD

**Issue by JshiGit** [elastic/elasticsearch#38048] opened 2019-01-30 19:21 UTC
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): 6.2.1 and 6.2.4

**Plugins installed**: []

**JVM version** (`java -version`): 8

**OS version** (`uname -a` if on a Unix-like system): CentOS7

**Description of the problem including expected versus actual behavior**: 
I built an edgeNgram analyzer on a text field. The query with "fuzziness": "AUTO" act weirdly as if it is 0, no matter what the length of the search string is.  

For example, assuming I have two documents with the content "interpretation" and "elasticsearch". Per the document, a search key "inyer" will return the first document because it is only wrong by 1 LV distance. But it didn't. However for some search key like "ekast", it can return the second document. Basically the points are:

1. For some documents, "fuzziness": "AUTO" act like 0
2. For some other documents in the same index, it actually works 

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.Create a index with at least the following things:
{
        "analysis": {
            "char_filter": {
                "my_char_filter":{
                    "type": "mapping",
                    "mappings":["( =>", ") =>", "- =>"]
                }
            },
            "tokenizer": {
                "my_tokenizer": {
                    "type": "edge_ngram",
                    "min_gram": 1,
                    "max_gram": 20,
                    "token_chars": [
                        "letter",
                        "punctuation",
                        "digit"
                    ]
                }
            },
            "analyzer": {
                "my_analyzer": {
                    "type": "custom",
                    "char_filter": "my_char_filter",
                    "tokenizer": "my_tokenizer",
                    "filter": [
                        "lowercase",
                        "asciifolding"
                    ]
                }
            },
    "mappings": {
        "mydoc": {
            "properties": {
                "my_field": {
                    "type": "text",
                    "analyzer": "my_analyzer",
                    "search_analyzer": "my_analyzer"
                }
            }
        }
    }
}
 
 2. Give it a few random data and run a query like this:
GET my_index/_search
{
            "query": {
                "bool": {
                    "should": [
                        {"match": {
                            "my_field": {
                                "query": "blabla",
                                "fuzziness": "AUTO",
                                "operator": "and"
                                }
                            }
                        }
              }
}

 3. If you think there should be a match and there is not, set the "fuzziness" to 1 or 2 and it will work. 

**Provide logs (if relevant)**:

According to this chapter in the official documentation: https://www.elastic.co/guide/en/elasticsearch/reference/6.2/analysis-edgengram-tokenizer.html

One "does not have to" use the EdgeNgram analyzer for both indexing and searching, however it should not be wrong to use it. Also if there is in fact a reason for fuzziness settings not working with this type of analyzer, it should be listed with bold font. 

I can bypass this problem by 2 different means:
1.  use a normal analyzer such as whitespace as the search_analyzer
2.  manually create a heuristic like "fuzziness":"AUTO" but assign actual values (0,1,2)

Anyway, I think this behavior is suspicious and worth looking into. Thanks.

**Comment by jimczi** [comment] 2019-01-30 19:49
@JshiGit it is difficult to understand the issue without a description and a complete recreation of the problem. We have a guideline when you open open a new issue so can you fill the description with the requested informations ? The version you're using and a simple recreation at minimum, otherwise we have no way to diagnose your issue and/or provide a fix for it.

**Comment by JshiGit** [comment] 2019-01-30 20:13
Sorry I clicked submit button by accident, now the information is added.

**Comment by jimczi** [comment] 2019-05-10 07:30
Sorry for the late reply. I tried you recreation with Elasticsearch 6.7 and it works as expected. A query with fuzziness AUTO for `inyer` returns the document that contains `interpretation`. Also note that the expansion is limited to the 50 closest terms so if you have a lot of documents and since you use edge_ngrams on this field it is likely possible that the selected terms do not include `inter` in the final query. I am going to close this issue but feel free to reopen if you can find a simple reproduction that exhibits the issue on Elasticsearch 6.7.

**Closed by jimczi** 2019-05-10 07:30 UTC
Labels: :Search/Search
