### ISSUE TITLE
Node cannot recover from restart: Failed to deserialize response of type [org.elasticsearch.xpack.action.XPackUsageResponse]

### ISSUE THREAD

**Issue by tomas-mazak** [elastic/elasticsearch#20631] opened 2016-09-22 11:39 UTC
**Elasticsearch version**: 5.0.0-alpha5

**Plugins installed**: [x-pack 5.0.0-alpha5]

**JVM version**: openjdk-8-jre:amd64                 8u102-b14.1-1~bpo8+1

**OS version**: Debian Jessie amd64

**Description of the problem including expected versus actual behavior**:
After restarting, the node ends up continually leaving and joining the cluster, not able to start working properly (see the log below). After deleting all data on the affected node and restarting elasticsearch again, the node joins the cluster and starts working properly.

**Steps to reproduce**:
In order to reproduce this problem, I need to reinstall the broken version of elasticsearch data dir and restart elasticsearch. As it happened twice, I have two instances of "broken data". The data is large and contains confidential information, so I cannot provide it here. However, if somebody is interested in looking at this issue, I can help analyzing the data.

**Provide logs (if relevant)**:
[2016-09-22 13:18:16,621][INFO ][cluster.service          ] [epyk-node1] detected_master {epyk-arbiter}{06_SMr8iSpuyzPG0n1dXCg}{vZiHtdyZS_OicIxqI7lXjw}{10.32.56.22}{10.32.56.22:9300}, added {{epyk-arbiter}{06_SMr8iSpuyzPG0n1dXCg}{vZiHtdyZS_OicIxqI7lXjw}{10.32.56.22}{10.32.56.22:9300},}, reason: zen-disco-receive(from master [master {epyk-arbiter}{06_SMr8iSpuyzPG0n1dXCg}{vZiHtdyZS_OicIxqI7lXjw}{10.32.56.22}{10.32.56.22:9300} committed version [1498]])
[2016-09-22 13:18:18,653][WARN ][rest.suppressed          ] path: _xpack/usage, params: {}
RemoteTransportException[[Failed to deserialize response of type [org.elasticsearch.xpack.action.XPackUsageResponse]]]; nested: TransportSerializationException[Failed to deserialize response of type [org.elasticsearch.xpack.action.XPackUsageResponse]]; nested: IOException[Can't read unknown type [97]];
Caused by: TransportSerializationException[Failed to deserialize response of type [org.elasticsearch.xpack.action.XPackUsageResponse]]; nested: IOException[Can't read unknown type [97]];
	at org.elasticsearch.transport.TcpTransport.handleResponse(TcpTransport.java:1234)
	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1206)
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:474)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:428)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Can't read unknown type [97]
	at org.elasticsearch.common.io.stream.StreamInput.readGenericValue(StreamInput.java:509)
	at org.elasticsearch.common.io.stream.StreamInput.readArrayList(StreamInput.java:518)
	at org.elasticsearch.common.io.stream.StreamInput.readGenericValue(StreamInput.java:477)
	at org.elasticsearch.common.io.stream.StreamInput.readMap(StreamInput.java:437)
	at org.elasticsearch.xpack.security.SecurityFeatureSet$Usage.<init>(SecurityFeatureSet.java:178)
	at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:40)
	at org.elasticsearch.xpack.action.XPackUsageResponse.readFrom(XPackUsageResponse.java:60)
	at org.elasticsearch.transport.TcpTransport.handleResponse(TcpTransport.java:1231)
	... 23 more
[2016-09-22 13:18:18,662][WARN ][transport.netty4         ] [epyk-node1] exception caught on transport layer [[id: 0xe26113ed, L:/10.32.56.24:43659 - R:/10.32.56.22:9300]], closing connection
java.lang.IllegalStateException: Message not fully read (response) for requestId [1570], handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler@50936fba], error [false]; resetting
	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1213)
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:474)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:428)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at java.lang.Thread.run(Thread.java:745)
[2016-09-22 13:18:18,665][INFO ][discovery.zen            ] [epyk-node1] master_left [{epyk-arbiter}{06_SMr8iSpuyzPG0n1dXCg}{vZiHtdyZS_OicIxqI7lXjw}{10.32.56.22}{10.32.56.22:9300}], reason [transport disconnected]
[2016-09-22 13:18:18,666][WARN ][discovery.zen            ] [epyk-node1] master left (reason = transport disconnected), current nodes: {{epyk-node1}{bEQdMB_2RuiVQrQbUdcYsg}{RGqPjcwTS-6F-H8K9X6wxg}{10.32.56.24}{10.32.56.24:9300},{epyk-node2}{rx6eFW2zQ8WQkUrLKRe_ZQ}{4XQPgbKFTwCSJqceIR3N8Q}{10.32.56.23}{10.32.56.23:9300},}
[2016-09-22 13:18:18,666][INFO ][cluster.service          ] [epyk-node1] removed {{epyk-arbiter}{06_SMr8iSpuyzPG0n1dXCg}{vZiHtdyZS_OicIxqI7lXjw}{10.32.56.22}{10.32.56.22:9300},}, reason: master_failed ({epyk-arbiter}{06_SMr8iSpuyzPG0n1dXCg}{vZiHtdyZS_OicIxqI7lXjw}{10.32.56.22}{10.32.56.22:9300})
[2016-09-22 13:18:20,215][ERROR][xpack.monitoring.agent   ] [epyk-node1] exception when exporting documents
ExportException[failed to flush export bulks]
	at org.elasticsearch.xpack.monitoring.agent.exporter.ExportBulk$Compound.doFlush(ExportBulk.java:143)
	at org.elasticsearch.xpack.monitoring.agent.exporter.ExportBulk.close(ExportBulk.java:72)
	at org.elasticsearch.xpack.monitoring.agent.exporter.Exporters.export(Exporters.java:198)
	at org.elasticsearch.xpack.monitoring.agent.AgentService$ExportingWorker.run(AgentService.java:209)
	at java.lang.Thread.run(Thread.java:745)

**Comment by javanna** [comment] 2016-09-22 13:49
Hi @tomas-mazak what version are the other nodes in the cluster?

**Comment by tomas-mazak** [comment] 2016-09-22 14:08
3 nodes, 2 of which are data and master-eligible, 1 is only master-eligible (tie-breaker): 
 ~# curl localhost:9200/_cat/nodes
10.32.56.23 22 100 7 1.91 2.03 2.10 mdi * epyk-node2
10.32.56.24 33 100 4 1.60 1.63 1.69 mdi - epyk-node1
10.32.56.22 17  93 0 0.00 0.01 0.05 mi  - epyk-arbiter

All three are running the same version of ES on the same version of java with the same version of x-pack:
epyk-node1 ~# dpkg -l | egrep 'elasticsearch|openjdk'
ii  elasticsearch                       5.0.0-alpha5               all          Elasticsearch is a distributed RESTful search engine built for the cloud. Reference documentation can be found at https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html and the 'Elasticsearch: The Definitive Guide' book can be found at https://www.elastic.co/guide/en/elasticsearch/guide/current/index.html
ii  openjdk-8-jre:amd64                 8u102-b14.1-1~bpo8+1       amd64        OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-8-jre-headless:amd64        8u102-b14.1-1~bpo8+1       amd64        OpenJDK Java runtime, using Hotspot JIT (headless)

epyk-node2 ~# dpkg -l | egrep 'elasticsearch|openjdk'
ii  elasticsearch                       5.0.0-alpha5               all          Elasticsearch is a distributed RESTful search engine built for the cloud. Reference documentation can be found at https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html and the 'Elasticsearch: The Definitive Guide' book can be found at https://www.elastic.co/guide/en/elasticsearch/guide/current/index.html
rc  openjdk-7-jre-headless:amd64        7u111-2.6.7-1~deb8u1       amd64        OpenJDK Java runtime, using Hotspot JIT (headless)
ii  openjdk-8-jre:amd64                 8u102-b14.1-1~bpo8+1       amd64        OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-8-jre-headless:amd64        8u102-b14.1-1~bpo8+1       amd64        OpenJDK Java runtime, using Hotspot JIT (headless)

epyk-arbiter ~# dpkg -l | egrep 'elasticsearch|openjdk'
ii  elasticsearch                       5.0.0-alpha5               all          Elasticsearch is a distributed RESTful search engine built for the cloud. Reference documentation can be found at https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html and the 'Elasticsearch: The Definitive Guide' book can be found at https://www.elastic.co/guide/en/elasticsearch/guide/current/index.html
ii  openjdk-8-jre:amd64                 8u102-b14.1-1~bpo8+1       amd64        OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-8-jre-headless:amd64        8u102-b14.1-1~bpo8+1       amd64        OpenJDK Java runtime, using Hotspot JIT (headless)

~# curl localhost:9200/_cat/plugins
epyk-node1   x-pack 5.0.0-alpha5
epyk-node2   x-pack 5.0.0-alpha5
epyk-arbiter x-pack 5.0.0-alpha5

**Comment by javanna** [comment] 2016-09-22 14:19
Thanks for the info @tomas-mazak . this seems to be a serialization bug that will be fixed with xpack 5.0.0-beta1, which is going to be released soon. The bug is in the xpack usage api. I am not sure though if that is the cause of recovery going wrong. Are you firing `_xpack/usage` requests by any chance?

**Comment by tomas-mazak** [comment] 2016-09-22 14:41
Thanks for quick reply @javanna . I am not hitting the _xpack/usage intentionally, however, I am running kibana with x-pack installed and use the monitoring quite a lot. Anyway, during the erroneous state described, I tried to shutoff kibana service completely and it did not help.

**Comment by javanna** [comment] 2016-09-22 14:47
I verified that it's the monitoring plugin calling _xpack/usage as part of the info that it collects. That explains who causes the serialization error, but not what is causing the recovery problems. That seems to be another problem.

**Comment by tlrx** [comment] 2016-09-22 14:49
To get rid of the serialization error and as a workaround the fix is available, you can set `xpack.monitoring.enabled: false` in your configuration to disable monitoring.

**Comment by tomas-mazak** [comment] 2016-09-22 15:00
@tlrx , thanks for a hint! I will try that as soon as my cluster is green again. I would also like to point out that deleting the whole local data did help to workaround this problem. But returning the old data-dir brought it back so it looks like the bug is connected with the data in the data dir.

**Comment by clintongormley** [comment] 2016-09-23 13:38
@tomas-mazak could you try your old data dir with beta1 to see what happens?  Maybe there is another exception unrelated to the bad serialization.

**Comment by tomas-mazak** [comment] 2016-09-23 14:04
@clintongormley thanks for the pioneer label :) I will install beta1 in the beginning of the next week and try with the "corrupted" data dir

**Comment by tomas-mazak** [comment] 2016-10-13 13:06
Hey, I was not able to replicate this problem with 5.0.0-rc1, so I suppose it's fixed.

**Comment by clintongormley** [comment] 2016-10-17 08:50
thanks for letting us know @tomas-mazak

**Closed by clintongormley** 2016-10-17 08:50 UTC
Labels: :Recovery, feedback_needed, Pioneer Program, v5.0.0-beta1
