### ISSUE TITLE
null_pointer_exception for term vector request

### ISSUE THREAD

**Issue by bijanfahimi** [elastic/elasticsearch#48744] opened 2019-10-31 10:40 UTC
This issue is related to #47723, with some additional information and hopefully narrowing down the issue.

**We observed that when we wait 10 minutes the termvector query will pass correctly.**

**Elasticsearch version** : 7.4.1

**Plugins installed**: 
- mapper-annotated-text
- hunspell

**JVM version**:
openjdk 13 2019-09-17
OpenJDK Runtime Environment AdoptOpenJDK (build 13+33)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13+33, mixed mode, sharing)

**OS version** :
4.19.0-5-amd64 #1 SMP Debian 4.19.37-5+deb10u2 (2019-08-08) x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. Create Index.
```
PUT myindex

{
  "settings" : {
    "number_of_shards" : 1
  },
  "mappings" : {
    "properties" : {
      "owner" : { "type" : "keyword" }
    },
    "dynamic_templates": [
      {
        "namedEntities": {
          "path_match": "entities.*",
          "mapping": {
            "type": "text",
            "term_vector": "with_offsets"
          }
        }
      }
    ]
  }
}
```

2. Add a document
```
PUT myindex/_doc/1

{
  "owner": "max"
}
```

**3. Update document with painless script (This causes the error, even its on an other field)**
```
POST myindex/_update/1

{
  "script": {
    "source": "ctx._source.owner='hans'",
    "lang": "painless"
  }
}
```

4. Update document without script (This is not a problem)
```
{
    "doc" : {
        "entities.en" : "dog"
    }
}
```

5. Get termvector for an artifical document (This leads to the nullpointer, **if the term is not in the index**)

```
{
  "term_statistics": true,
  "doc": {
    "entities.en": [
      "cat"
    ]
  },
  "filter": {
    "max_num_terms": 1000,
    "min_term_freq": 1,
    "max_term_freq": 1000,
    "min_doc_freq": 1,
    "max_doc_freq": 1000,
    "min_word_length": 1,
    "max_word_length": 1000
  }
}
```

**Error message**:
```
{
  "error": {
    "root_cause": [
      {
        "type": "exception",
        "reason": "failed to execute term vector request"
      }
    ],
    "type": "exception",
    "reason": "failed to execute term vector request",
    "caused_by": {
      "type": "null_pointer_exception",
      "reason": null
    }
  },
  "status": 500
}
```

**Error Log**:
```
{"type": "server", "timestamp": "2019-10-31T10:28:41,230Z", "level": "WARN", "component": "r.suppressed", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-0", "message": "path: /myindex/_termvectors, params: {index=myindex}", "cluster.uuid": "r1awoSQ9QuKUVZPMgHQXAw", "node.id": "rCrCEQ2yTzSArMbz2u7Bxg" , 
"stacktrace": ["org.elasticsearch.transport.RemoteTransportException: [elasticsearch-master-0][10.42.6.86:9300][indices:data/read/tv[s]]", 
"Caused by: org.elasticsearch.ElasticsearchException: failed to execute term vector request", 
"at org.elasticsearch.index.termvectors.TermVectorsService.getTermVectors(TermVectorsService.java:149) ~[elasticsearch-7.4.1.jar:7.4.1]", 
"at org.elasticsearch.index.termvectors.TermVectorsService.getTermVectors(TermVectorsService.java:78) ~[elasticsearch-7.4.1.jar:7.4.1]", 
"at org.elasticsearch.action.termvectors.TransportTermVectorsAction.shardOperation(TransportTermVectorsAction.java:110) ~[elasticsearch-7.4.1.jar:7.4.1]", 
"at org.elasticsearch.action.termvectors.TransportTermVectorsAction.shardOperation(TransportTermVectorsAction.java:46) ~[elasticsearch-7.4.1.jar:7.4.1]", 
"at org.elasticsearch.action.support.single.shard.TransportSingleShardAction.lambda$asyncShardOperation$0(TransportSingleShardAction.java:110) ~[elasticsearch-7.4.1.jar:7.4.1]", 
"at org.elasticsearch.action.ActionRunnable$1.doRun(ActionRunnable.java:45) ~[elasticsearch-7.4.1.jar:7.4.1]", 
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:773) [elasticsearch-7.4.1.jar:7.4.1]", 
"at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.4.1.jar:7.4.1]", 
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]", 
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]", 
"at java.lang.Thread.run(Thread.java:830) [?:?]", 
"Caused by: java.lang.NullPointerException", 
"at java.util.Objects.requireNonNull(Objects.java:222) ~[?:?]", 
"at org.apache.lucene.search.TermStatistics.<init>(TermStatistics.java:65) ~[lucene-core-8.2.0.jar:8.2.0 31d7ec7bbfdcd2c4cc61d9d35e962165410b65fe - ivera - 2019-07-19 15:05:56]", 
"at org.elasticsearch.action.termvectors.TermVectorsFilter.getTermStatistics(TermVectorsFilter.java:289) ~[elasticsearch-7.4.1.jar:7.4.1]", 
"at org.elasticsearch.action.termvectors.TermVectorsFilter.selectBestTerms(TermVectorsFilter.java:221) ~[elasticsearch-7.4.1.jar:7.4.1]", 
"at org.elasticsearch.index.termvectors.TermVectorsService.getTermVectors(TermVectorsService.java:138) ~[elasticsearch-7.4.1.jar:7.4.1]", 
"at org.elasticsearch.index.termvectors.TermVectorsService.getTermVectors(TermVectorsService.java:78) ~[elasticsearch-7.4.1.jar:7.4.1]", 
"at org.elasticsearch.action.termvectors.TransportTermVectorsAction.shardOperation(TransportTermVectorsAction.java:110) ~[elasticsearch-7.4.1.jar:7.4.1]", 
"at org.elasticsearch.action.termvectors.TransportTermVectorsAction.shardOperation(TransportTermVectorsAction.java:46) ~[elasticsearch-7.4.1.jar:7.4.1]", 
"at org.elasticsearch.action.support.single.shard.TransportSingleShardAction.lambda$asyncShardOperation$0(TransportSingleShardAction.java:110) ~[elasticsearch-7.4.1.jar:7.4.1]", 
"at org.elasticsearch.action.ActionRunnable$1.doRun(ActionRunnable.java:45) ~[elasticsearch-7.4.1.jar:7.4.1]", 
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:773) ~[elasticsearch-7.4.1.jar:7.4.1]", 
"at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.4.1.jar:7.4.1]", 
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]", 
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]", 
"at java.lang.Thread.run(Thread.java:830) ~[?:?]"] }
```

**Comment by jimczi** [comment] 2019-10-31 12:17
If the issue is the same it would be easier to add your comment on the original one rather than opening a new one. However I opened https://github.com/elastic/elasticsearch/pull/48745 to fix this bug and linked the two issues so we'll close both when the pr is merged.

**Comment by cbuescher** [comment] 2021-04-27 13:02
This issue is solved by https://github.com/elastic/elasticsearch/pull/48745 but wasn't closed correctly, so closing now.

**Closed by cbuescher** 2021-04-27 13:02 UTC
Labels: :Search/Search, >bug, Team:Search
