### ISSUE TITLE
vectors/30_sparse_vector_basic/Cosine Similarity failed on 7.x intake

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#49383] opened 2019-11-20 14:52 UTC
Build scan: https://gradle-enterprise.elastic.co/s/yg5x4sd6qjs56

REPRODUCE WITH: ./gradlew ':x-pack:plugin:integTestRunner' --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=vectors/30_sparse_vector_basic/Cosine Similarity}" -Dtests.seed=F4BEAC1DB1D53060 -Dtests.security.manager=true -Dtests.locale=it-CH -Dtests.timezone=Etc/GMT-2 -Dcompiler.java=12 -Druntime.java=8 -Dtests.rest.blacklist=getting_started/10_monitor_cluster_health/*

```
Caused by: java.lang.AssertionError: 
did not get expected warning header [
	The [sparse_vector] field type is deprecated and will be removed in 8.0.
]
```

I am puzzled as this test failure doesn't reproduce for me.
And all other tests in this file that expect the same warning ran without failures.
I can suggest that is probably something related to how tests are run (testing infrastructure) than to the test itself

We can monitor for more failures on these tests, and if no more failures occur, we will close the issue.
cc @jtibshirani

**Comment by droberts195** [comment] 2019-12-06 17:35
The same failure just occurred in `XPackRestIT test {p0=vectors/35_sparse_vector_l1l2/L1 norm}` in https://gradle-enterprise.elastic.co/s/oopg7rdugmzne:

```
Caused by: java.lang.AssertionError: 
did not get expected warning header [
	The [sparse_vector] field type is deprecated and will be removed in 8.0.
]
```

This didn't reproduce locally using:

```
./gradlew ':x-pack:plugin:integTestRunner' --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=vectors/35_sparse_vector_l1l2/L1 norm}" \
  -Dtests.seed=82A7DCDC265AC010 \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-Latn-RS \
  -Dtests.timezone=Etc/GMT+4 \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

This failure is _extremely_ intermittent.

**Comment by jtibshirani** [comment] 2019-12-11 01:27
The stash dump shows that the search hit two shards, but the test index only has one shard:

```
-- | --
  | 1>   "stash" : { |  
  | 1>     "body" : { |  
  | 1>       "took" : 2, |  
  | 1>       "timed_out" : false, |  
  | 1>       "_shards" : { |  
  | 1>         "total" : 2, |  
  | 1>         "successful" : 2, |  
  | 1>         "skipped" : 0, |  
  | 1>         "failed" : 0 |  
  | 1>       }, |  
  | 1>       "hits" : { 
...
```

A theory as to what is happening:
1. There is an extra empty index present in addition to the test index. Since the search doesn't specify an index name, it hits both the test index and this extra empty index.
2. The shard responses from the extra index don't produce deprecation warnings because it's empty and we never try to execute the script. If not all shard responses contain the warning headers, then certain deprecation warnings can be lost (due to the bug described in #33936).

I'm not clear on how there could be an extra empty index present. But it is good practice to specify the index name directly in searches -- I'll plan to change the search calls to specify `test-index` directly and then monitor whether we see more failures.

**Comment by jtibshirani** [comment] 2019-12-11 18:36
I'm going to close this now that #50061 has merged, we can re-open it if we see the failure again.

**Closed by jtibshirani** 2019-12-11 18:36 UTC
Labels: :Search/Search, >test-failure
