### ISSUE TITLE
XPackRestIT "ml/set_upgrade_mode/Setting upgrade mode to disabled from enabled" fails

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#41052] opened 2019-04-10 07:29 UTC
On 7.0: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+intake/686/console

Reproduce line (does not reproduce locally):
```
./gradlew :x-pack:plugin:integTestRunner --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=ml/set_upgrade_mode/Setting upgrade mode to disabled from enabled}" \
  -Dtests.seed=375B8E9C58C08155 \
  -Dtests.security.manager=true \
  -Dtests.locale=sk \
  -Dtests.timezone=Europe/Budapest \
  -Dcompiler.java=12 \
  -Druntime.java=8 \
  -Dtests.rest.blacklist=getting_started/10_monitor_cluster_health/*
```

Stack trace:
```
java.lang.RuntimeException: Had to resort to force-closing jobs, something went wrong?
	at __randomizedtesting.SeedInfo.seed([375B8E9C58C08155:BF0FB146F63CECAD]:0)
	at org.elasticsearch.xpack.core.ml.integration.MlRestTestStateCleaner.deleteAllJobs(MlRestTestStateCleaner.java:85)
	at org.elasticsearch.xpack.core.ml.integration.MlRestTestStateCleaner.clearMlMetadata(MlRestTestStateCleaner.java:31)
	at org.elasticsearch.xpack.test.rest.XPackRestIT.clearMlState(XPackRestIT.java:270)
	at org.elasticsearch.xpack.test.rest.XPackRestIT.cleanup(XPackRestIT.java:254)
	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.elasticsearch.client.ResponseException: method [POST], host [http://[::1]:33569], URI [/_ml/anomaly_detectors/_all/_close], status line [HTTP/1.1 500 Internal Server Error]
{"error":{"root_cause":[{"type":"exception","reason":"Unable to read field length from input stream\nFailed to parse length encoded header from stream\nFailed to handle all input data\nMl anomaly detector job failed\n"}],"type":"exception","reason":"Exception closing autodetect process","caused_by":{"type":"exception","reason":"Unable to read field length from input stream\nFailed to parse length encoded header from stream\nFailed to handle all input data\nMl anomaly detector job failed\n"}},"status":500}
	at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:260)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:238)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:212)
	at org.elasticsearch.xpack.core.ml.integration.MlRestTestStateCleaner.deleteAllJobs(MlRestTestStateCleaner.java:77)
	... 37 more
```

Likely be related to https://github.com/elastic/elasticsearch/issues/40385 but its in another test method ("Setting upgrade mode to disabled from enabled") but I'll leave it to the team to decide if this is a duplicate.

**Comment by cbuescher** [comment] 2019-04-10 07:30
A similar looking one on master from April 1st: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+artifactory/142/console

**Comment by cbuescher** [comment] 2019-04-10 07:33
Another one from March 12th: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+intake/383/console

I'll leave it up to @davidkyle to decide if the frequency of this makes it necessary to mute this test.

**Comment by davidkyle** [comment] 2019-04-10 16:22
Thanks for triaging this @cbuescher, I've found the cause and it is indeed the same as #40385. Closing this preferring #40385 to track the issue.

**Closed by davidkyle** 2019-04-10 16:22 UTC
Labels: :ml, >test-failure, v7.0.1, v7.1.0, v8.0.0
