### ISSUE TITLE
Normalizer,Keyword and Ignore_Above doesnt work

### ISSUE THREAD

**Issue by hoeghen** [elastic/elasticsearch#23588] opened 2017-03-15 13:48 UTC
It seems that the combination of keyword type, and a custom normalizer, and ignore_above is not working
The ignore_above setting is not effective anymore in this combination.
```
.startObject("raw")
            .field("type", "keyword") 					
            .field("ignore_above",250) 
            .field("normalizer","lower_keyword")
.endObject()
```

**Comment by cbuescher** [comment] 2017-03-16 15:51
What version are you using? I cannot reproduce this on 5.2.2 using the following:

```
PUT test
{
  "settings": {
    "analysis": {
      "normalizer": {
        "lower_keyword": {
          "type": "custom",
          "char_filter": [],
          "filter": ["lowercase", "asciifolding"]
        }
      }
    }
  },
  "mappings": {
    "type": {
      "properties": {
        "city": {
          "type": "keyword",
          "ignore_above" : 10,
          "normalizer" : "lower_keyword"
        }
      }
    }
  }
}

GET /test/type/_mapping

PUT /test/type/1
{
  "city" : "HAMBURG"
}

PUT /test/type/2
{
  "city" : "LONGCITYNAME1234567890123456789"
}

GET /test/type/_search
{
  "docvalue_fields" : ["city"]
}

GET /test/type/_search
{
  "docvalue_fields" : ["city"]
}
```

With this I see the `city` field in doc1 being indexed while the field for the second document gets skipped (not indexed). Closing, but please feel free to reopen if this is reproducable in another version or ask questions about this in the [forum](https://discuss.elastic.co) if you need assistance.

**Closed by cbuescher** 2017-03-16 15:51 UTC
