### ISSUE TITLE
array_index_out_of_bounds_exception in top hits aggregation in nested fields

### ISSUE THREAD

**Issue by shreyanshssoni** [elastic/elasticsearch#82640] opened 2022-01-15 18:10 UTC
Composite aggregation on nested Fields is giving me an error  of "array out of bound exception.
If i remove top hits:then its working fine but as i apply the top hits aggregation its starts giving me this error and also tried top_metrics got the same error.

caused_by" : {
        "type" : "array_index_out_of_bounds_exception",
        "reason" : "Index 129 out of bounds for length 129"
      }
Query of elasticSearch :
GET /mdoqa.masterdataonline.com_workflow_do_0_en/_search
{
  "size": 0,
  "query": {
    "bool": {
      "must": [
        {
          "bool": {
            "filter": [
              {
                "nested": {
                  "query": {
                    "bool": {
                      "must": [
                        {
                          "term": {
                            "hyvs.1.rows.PLANT.vc.c.keyword": {
                              "value": "0001",
                              "boost": 1
                            }
                          }
                        }
                      ],
                      "adjust_pure_negative": true,
                      "boost": 1
                    }
                  },
                  "path": "hyvs.1.rows",
                  "ignore_unmapped": false,
                  "score_mode": "none",
                  "boost": 1,
                  "inner_hits": {
                    "name": "1_440031199239724271",
                    "ignore_unmapped": false,
                    "from": 0,
                    "size": 3,
                    "version": false,
                    "seq_no_primary_term": false,
                    "explain": false,
                    "track_scores": false
                  }
                }
              }
            ],
            "adjust_pure_negative": true,
            "boost": 1
          }
        },
        {
          "terms": {
            "staticFields.OBJECTTYPE.vc.c.keyword": [
              "1005"
            ],
            "boost": 1
          }
        }
      ],
      "adjust_pure_negative": true,
      "boost": 1
    }
  },
  "aggregations": {
    "nested_tags": {
      "nested": {
        "path": "hyvs.1.rows"
      },
      "aggregations": {
        "bucket": {
          "composite": {
            "size": 10,
            "sources": [
              {
                "FILTER": {
                  "terms": {
                    "script": {
                      "source": "try{if(doc.containsKey('hyvs.1.rows.PLANT.vc.t.keyword') && doc['hyvs.1.rows.PLANT.vc.t.keyword'].size()!=0) { return doc['hyvs.1.rows.PLANT.vc.t.keyword'].value} else { if(doc.containsKey('hyvs.1.rows.PLANT.vc.c.keyword') && doc['hyvs.1.rows.PLANT.vc.c.keyword'].size()!=0) { return doc['hyvs.1.rows.PLANT.vc.c.keyword'].value}  else { return '';}}}catch(Exception e){return null;}",
                      "lang": "painless"
                    },
                    "missing_bucket": false,
                    "order": "asc"
                  }
                }
              }
            ]
          },
          "aggregations": {
            "items": {
              "top_hits": {
                "from": 0,
                "size": 1,
                "version": false,
                "seq_no_primary_term": false,
                "explain": false,
                "_source": {
                  "includes": [
                    "hyvs.1.rows.PLANT.vc"
                  ],
                  "excludes": []
                },
                "sort": [
                  {
                    "_score": {
                      "order": "desc"
                    }
                  }
                ]
              }
            }
          }
        }
      }
    }
  }
}

here, hyvs is a nested [path:hyvs.1.rows](url)
![structure](https://user-images.githubusercontent.com/61939305/149632909-41e3a58a-871d-4c02-bdfd-f4be90219cce.png)
![lucene](https://user-images.githubusercontent.com/61939305/149632911-e61c1fc8-c3dd-4a84-9099-18ef87affc7a.png)
![es issue](https://user-images.githubusercontent.com/61939305/149632913-d6dd9051-81ee-4b97-b18d-47a2cc9ff2b2.png)

**Comment by shreyanshssoni** [comment] 2022-01-15 18:14
@cbuescher please have a look into this have a best hope from you. @elasticsearchmachine @@elastic/es-search @amitmbm .

**Comment by cbuescher** [comment] 2022-01-17 09:45
Since this seems to be a very specific error, depending on certain user data, index mappings and potentially related to a script execution, for possible reproduction would you please provide:
* the mapping for the index in question
* a minimal set of documents (ideally only a few) from the index that are needed to recreate the error
* the Elasticsearch Version you are using

**Comment by shreyanshssoni** [comment] 2022-01-19 05:35
Hi @cbuescher sorry for the late response,Here i am attching mapping and setting of index and also sharing file with some documnets .Moreover,sharing one filte with all steps i got with this error.Please have look into this.

**Comment by shreyanshssoni** [comment] 2022-01-19 05:44
[ElasticIssue.zip](https://github.com/elastic/elasticsearch/files/7894378/ElasticIssue.zip)
@cbuescher

**Comment by shreyanshssoni** [comment] 2022-01-21 08:08
@cbuescher  any update on this..

**Comment by cbuescher** [comment] 2022-01-24 10:16
@shreyanshssoni please provide the additional information I requested and we can start looking into this from there.

**Comment by cbuescher** [comment] 2022-01-24 10:17
Sorry, I didn't see the zip file, please disregard my previous message. We will look into this soon.

**Comment by cbuescher** [comment] 2022-01-28 17:08
Just a quick update, I looked at the index mappings/settings, doc and query you supplied and think I can see the same IndexOutOfBounds error but have not been able to dig deeper into its causes. Thanks for your patience.

**Comment by shreyanshssoni** [comment] 2022-02-01 05:07
yes , @cbuescher thanks for update and i also read that ..Composite(with nested fields) + Top Hits[] = array out of bounds exception ,also done too much R&d on it but found nothing.

**Comment by noah79** [comment] 2022-07-11 16:44
We have the same issue with nested + top_hits on ES Cloud v8.3.2.  There have been no updates to this issue in 6+ months.  Is there any traction or suggested workarounds or do we need to change our application logic significantly?

**Comment by shreyanshssoni** [comment] 2022-07-12 05:52
@noah79 you can do one thing use multi-search Query for this issue.
i.e .use aggregation but do not use top_hits instead of make a multi-search query and getting only one document of that particular match. It worked for me.

**Comment by martijnvg** [comment] 2022-10-20 07:41
This bug here is the same kind of bug that has been reported in #90955. Only here a `top_hits` agg is used as leaf aggregations instead of `scripted_metric`. This bug is likely to occur with any leaf aggregation that requires score and has  a nested and composite aggregation as parents.

**Comment by wchaparro** [comment] 2022-12-08 13:29
closing this one in favor of https://github.com/elastic/elasticsearch/issues/90955

**Closed** 2022-12-08 13:30 UTC
Labels: >bug, :Analytics/Aggregations, Team:Analytics, :Analytics/CompositeAggs
