### ISSUE TITLE
[CI] Index creation fails in yml rest tests with ResourceAlreadyExistsException

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#50598] opened 2020-01-03 12:16 UTC
Log | https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=oraclelinux-7&&immutable/485/console
-- | --
Build Scans | [7.5.2] https://gradle-enterprise.elastic.co/s/2qhifqa65z7bg [6.8.7] https://gradle-enterprise.elastic.co/s/72mgirevam4pg https://gradle-enterprise.elastic.co/s/7ufmfia2dnlcw

This doesn't reproduce, but I expect it to be a general testing issue, not one with this particular test:
```
./gradlew ':qa:mixed-cluster:v7.5.2#mixedClusterTest' --tests "org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search/180_locale_dependent_mapping/Test Index and Search locale dependent mappings / dates}" \
  -Dtests.seed=FAF83F80DFE9DFD8 \
  -Dtests.security.manager=true \
  -Dtests.locale=no-NO \
  -Dtests.timezone=Pacific/Tahiti \
  -Dcompiler.java=13 \
  -Druntime.java=8
```
```
13:35:36 org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT > test {p0=search/180_locale_dependent_mapping/Test Index and Search locale dependent mappings / dates} FAILED
13:35:36     java.lang.AssertionError: Failure at [search/180_locale_dependent_mapping:8]: expected [2xx] status code but api [indices.create] returned [400 Bad Request] [{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [test_index/Gcp-JAi-QyiuVM34GWHGMw] already exists","index_uuid":"Gcp-JAi-QyiuVM34GWHGMw","index":"test_index","stack_trace":"[test_index/Gcp-JAi-QyiuVM34GWHGMw] ResourceAlreadyExistsException[index [test_index/Gcp-JAi-QyiuVM34GWHGMw] already exists]\n\tat org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validateIndexName(MetaDataCreateIndexService.java:153)\n\tat org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validate(MetaDataCreateIndexService.java:686)\n\tat org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.applyCreateIndexRequest(MetaDataCreateIndexService.java:267)\n\tat org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$1.execute(MetaDataCreateIndexService.java:242)\n\tat org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47)\n\tat org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:702)\n\tat 
[...]
```

**Comment by cbuescher** [comment] 2020-01-03 12:17
Labeled this as `:Core/Infra/Build` mainly because I expect this to be an issue somehow related to how we set up and run these tests, there might have been recent changes in this area that I'm not aware of. Please relabel if anything else seems more appropriate.

**Comment by mark-vieira** [comment] 2020-01-06 19:25
Yeah, this kind of thing generally indicates an issue with the test implementation. It might be possible this is https://github.com/elastic/elasticsearch/issues/46091 creeping up again.

**Comment by mark-vieira** [comment] 2020-02-06 22:37
Seeing a lot of these in `MixedClusterClientYamlTestSuiteIT`. Here are some examples:

https://gradle-enterprise.elastic.co/s/zm4q56zvdbjgu/tests/vzldwfo6t3k3y-2pri752okzdby
https://gradle-enterprise.elastic.co/s/utvv37tw2rr6y/tests/vzldwfo6t3k3y-2pri752okzdby
https://gradle-enterprise.elastic.co/s/sz6n5bemmaopc/tests/vzldwfo6t3k3y-2pri752okzdby

**Comment by gwbrown** [comment] 2020-08-06 19:58
I've looked at recent failures on build-stats which show similar symptoms in an effort to determine if this is still an issue, and have a few conclusions:
1) Failures with messages similar to this do not appear to be common in periodic branch builds[1]. There was only one build in July (on `7.8`), and 6 in June (on `master` and `7.x`), which failed with a message similar to this. In each case, there were several other failures which indicate other problems with the build, such as `SocketTimeoutException`s.
2) Failures similar to this are more common on pull-request builds, but from checking a number of impacted builds, it appears that there were issues in a few PRs (primarily related data streams and/or the REST compatibility layer) that caused widespread failures. The few I found where the failure fit this particular pattern appeared to be due to the contents of the pull request and were fixed before merging.

As all recent test failures I've found that appear similar to this one also appear to be caused by some relatively obvious cause other than failure of the test framework to properly clean up the cluster between tests, I believe this is no longer an issue on current dev branches. As such, I'm going to close this issue. Please re-open it (or a new issue and link this one) if failures like this start to occur with no obvious cause.

---

[1]: After excluding outliers. There were a few "real" problems which caused many failures with similar error messages which have since been fixed.

**Closed by gwbrown** 2020-08-06 19:58 UTC
Labels: :Core/Infra/Build, >test-failure, Team:Core/Infra
