### ISSUE TITLE
ES not listening to port 9200 or any port

### ISSUE THREAD

**Issue by qubusp** [elastic/elasticsearch#19298] opened 2016-07-07 10:04 UTC
Ver 4.xx
GitHub is reserved for bug reports and feature requests. The best place
to ask a general question is at the Elastic Discourse forums at
https://discuss.elastic.co. If you are in fact posting a bug report or
a feature request, please include one and only one of the below blocks
in your new issue.
-->

**Elasticsearch version**:

**JVM version**:

**OS version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by jasontedor** [comment] 2016-07-07 10:12
There is no useful content here, closing. The title suggests to me that you have a question and not a bug report. Please use the Elastic [Discourse forum](https://discuss.elastic.co/).

**Closed by jasontedor** 2016-07-07 10:12 UTC
