### ISSUE TITLE
Ilegal_access_error : failed to access class org.objectweb.asm.Edge from class org.objectweb.asm.MethodWriter

### ISSUE THREAD

**Issue by XinhaoLiam** [elastic/elasticsearch#89399] opened 2022-08-17 00:39 UTC
### CI Link

https://github.com/XinhaoLiam/elasticsearch_issue/tree/main

### Repro line

The commands for reproduction are written in the README.md

### Does it reproduce?

Yes

### Applicable branches

7.16.3

### Failure excerpt

I am using docker 20.10.7 to run an Elasticsearch mirror 7.16.3. However, when I tried to run a painless script, it returned such an error to me. I had already updated the log4j hot patch in the server to the latest version like written in [the post](https://github.com/elastic/elasticsearch/issues/81915). However, the error still exists. The full context of error is written below:

{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"failed to execute script"}],"type":"illegal_argument_exception","reason":"failed to execute script","caused_by":{"type":"script_exception","reason":"compile error","script_stack":[],"script":"if (ctx._source.array==null) {ctx._source.array=[params.new_array]}else{ctx._source.annotation.add(params.new_array)}","lang":"painless","caused_by":{"type":"illegal_access_error","reason":"failed to access class org.objectweb.asm.Edge from class org.objectweb.asm.MethodWriter (org.objectweb.asm.Edge is in unnamed module of loader 'app'; org.objectweb.asm.MethodWriter is in unnamed module of loader java.net.FactoryURLClassLoader @72ab05ed)"}}},"status":400}

**Comment by stu-elastic** [comment] 2022-08-17 18:21
Hi @XinhaoLiam, I'd recommend checking the server log from the instance corresponding to the `IllegalAccessError`, such as in [this post](https://github.com/elastic/elasticsearch/issues/81915#issuecomment-1001741461). 

It looks like the removal of the log4j hotpatch on that server was not effective, if you see something other than the `Log4jHotPatch` jar in the server then please reopen this issue with the appropriate log information.

However, with the information given, there is no indication this is an issue on the elasticsearch side.  So I'm closing this as a duplicate of #81915.

**Closed by stu-elastic** 2022-08-17 18:21 UTC
Labels: :Core/Infra/Scripting, >test-failure, team-discuss, Team:Core/Infra
