### ISSUE TITLE
Increase default file descriptors

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#17468] opened 2016-04-01 05:06 UTC
In `/etc/default/elasticsearch` we have `MAX_OPEN_FILES=65535`. If you uncomment that, but don't edit it, and start ES you get this in the logs;
```
[2016-04-01 05:02:50,128][WARN ][env                      ] [Achebe] max file descriptors [65535] for elasticsearch process likely too low, consider increasing to at least [65536]
```

Can we just increase the default by one to ensure our checks align with our default settings?

**Comment by clintongormley** [comment] 2016-04-01 08:30
Duplicate of #17430

**Closed by clintongormley** 2016-04-01 08:30 UTC

**Comment by innerpeacenan** [comment] 2017-12-03 10:25
my os is ubuntu 16.04, my elastic version is 6.0.0, I  solved the problem by the following steps:

*  open file /etc/security/limits.conf, add lines above for user who elastic search belongs, such as user named ffz.
```
ffz  soft nofile 65539
ffz hard nofile 65539
```

* reboot system

* run  `ulimit -n` to check for current user limit , if the result it not large enough , run `ulimit -n 65550`  to change ulimit, where 65550 is the new value.
