### ISSUE TITLE
Removed setting `index.mapper.dynamic` can be set on v7+ indices

### ISSUE THREAD

**Issue by matt-monacelli** [elastic/elasticsearch#96075] opened 2023-05-12 15:39 UTC
### Elasticsearch Version

7.10.2

### Java Version

_bundled_

### OS Version

AWS 7.10.2

### Problem Description

After setting a deprecated setting `index.mapper.dynamic` to false, I am unable to remove the setting and it is preventing me from opening the index:

`{ "error" : { "root_cause" : [ { "type" : "exception", "reason" : "Failed to verify index [events-000012/e57doKb8Qe2p-D-fOLUcNw]" } ], "type" : "exception", "reason" : "Failed to verify index [events-000012/e57doKb8Qe2p-D-fOLUcNw]", "caused_by" : { "type" : "illegal_argument_exception", "reason" : "Setting index.mapper.dynamic was removed after version 6.0.0" } }, "status" : 500 } `

### Steps to Reproduce

1.  Set index setting `index.mapper.dynamic` to false
2.  close the index
3.  try to open the index

### Workaround

Restore the problematic index from snapshot, passing `"ignore_index_settings": "index.mapper.dynamic"` to the restore request to filter out the bad setting.

**Comment by thecoop** [comment] 2023-05-15 08:31
@matt-monacelli This setting was removed in v6 by #25734, which versions are you upgrading from?

**Comment by matt-monacelli** [comment] 2023-05-15 14:15
@thecoop I am not upgrading, I have been on v7.10.2 and did not realize this setting was deprecated when I executed the API command to set it - now I am unable to set it back to true (or to remove it altogether by setting to null).

**Comment by DaveCTurner** [comment] 2023-05-15 14:48
Relates the discussion at https://discuss.elastic.co/t/unable-to-open-index-after-config-change-while-closed/333325. I'm not convinced this is a bug, or at least not a bug which exists in any non-EOL versions today. For example in 7.17.10 you cannot set this setting even when the index is closed:

```
PUT /testindex
{
  "settings": {
    "number_of_replicas": 0
  }
}

# 200 OK
# {
#   "shards_acknowledged": true,
#   "acknowledged": true,
#   "index": "testindex"
# }

POST /testindex/_close

# 200 OK
# {
#   "shards_acknowledged": true,
#   "acknowledged": true,
#   "indices": {
#     "testindex": {
#       "closed": true
#     }
#   }
# }

PUT /testindex/_settings
{
  "index.mapper.dynamic": false
}

# 400 Bad Request
# {
#   "status": 400,
#   "error": {
#     "reason": "Setting index.mapper.dynamic was removed after version 6.0.0",
#     "root_cause": [
#       {
#         "reason": "Setting index.mapper.dynamic was removed after version 6.0.0",
#         "type": "illegal_argument_exception"
#       }
#     ],
#     "type": "illegal_argument_exception"
#   }
# }
```

Since I don't see that there's any action for the ES dev team to take here, I'm closing this.

**Comment by rjernst** [comment] 2023-05-15 19:24
I re-labled this for the Search team. This particular check is not a generic settings feature, but instead a specific check during the construction of the MapperService. I suspect the check only being done on mapper service construction is why it is not tripped up on index setting changes.

**Comment by hatefpalizgar** [comment] 2023-06-14 08:30
I'm on version 7.9.1 and experiencing the same issue. There is no way to re-open a closed index and remove the deprecated settings even by calling the Settings Update API:
![image](https://github.com/elastic/elasticsearch/assets/44304240/8156c625-666f-4a16-ab6a-90194e167fed)

As you can see, above config is persisted in the settings and there is no way to remove or disable it.

**Comment by matt-monacelli** [comment] 2023-06-14 22:05
Exactly - there is a bug report submitted - hopefully it gets fixed!

**Comment by kunisen** [comment] 2023-12-21 08:08
Can we make sure to get some attention on this issue please?

After having this setting - `index.mapper.dynamic` in place, if restarting the node having the relevant shard data, the node will run into a bootlooping state, with the following error:

```logs
[2023-11-18T21:08:21,591][ERROR][org.elasticsearch.bootstrap.ElasticsearchUncaughtExceptionHandler] [instance-0000000026] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to parse mappings for index [[the_bad_index/msi-gPGJSo6_CRQiCUKBxQ]]
    at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:173) ~[elasticsearch-7.17.11.jar:7.17.11]
    at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:160) ~[elasticsearch-7.17.11.jar:7.17.11]
    at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:77) ~[elasticsearch-7.17.11.jar:7.17.11]
    at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112) ~[elasticsearch-cli-7.17.11.jar:7.17.11]
    at org.elasticsearch.cli.Command.main(Command.java:77) ~[elasticsearch-cli-7.17.11.jar:7.17.11]
    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:125) ~[elasticsearch-7.17.11.jar:7.17.11]
    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80) ~[elasticsearch-7.17.11.jar:7.17.11]
Caused by: java.lang.IllegalStateException: Failed to parse mappings for index [[the_bad_index/msi-gPGJSo6_CRQiCUKBxQ]]
    at org.elasticsearch.cluster.metadata.IndexMetadataVerifier.checkMappingsCompatibility(IndexMetadataVerifier.java:191) ~[elasticsearch-7.17.11.jar:7.17.11]
    at org.elasticsearch.cluster.metadata.IndexMetadataVerifier.verifyIndexMetadata(IndexMetadataVerifier.java:87) ~[elasticsearch-7.17.11.jar:7.17.11]
    at org.elasticsearch.gateway.GatewayMetaState.upgradeMetadata(GatewayMetaState.java:279) ~[elasticsearch-7.17.11.jar:7.17.11]
    at org.elasticsearch.gateway.GatewayMetaState.upgradeMetadataForNode(GatewayMetaState.java:265) ~[elasticsearch-7.17.11.jar:7.17.11]
    at org.elasticsearch.gateway.GatewayMetaState.start(GatewayMetaState.java:178) ~[elasticsearch-7.17.11.jar:7.17.11]
    at org.elasticsearch.node.Node.start(Node.java:1183) ~[elasticsearch-7.17.11.jar:7.17.11]
    at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:335) ~[elasticsearch-7.17.11.jar:7.17.11]
    at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:443) ~[elasticsearch-7.17.11.jar:7.17.11]
    at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:169) ~[elasticsearch-7.17.11.jar:7.17.11]
    ... 6 more
Caused by: java.lang.IllegalArgumentException: Setting index.mapper.dynamic was removed after version 6.0.0
    at org.elasticsearch.index.mapper.MapperService.<init>(MapperService.java:208) ~[elasticsearch-7.17.11.jar:7.17.11]
    at org.elasticsearch.cluster.metadata.IndexMetadataVerifier.checkMappingsCompatibility(IndexMetadataVerifier.java:177) ~[elasticsearch-7.17.11.jar:7.17.11]
    at org.elasticsearch.cluster.metadata.IndexMetadataVerifier.verifyIndexMetadata(IndexMetadataVerifier.java:87) ~[elasticsearch-7.17.11.jar:7.17.11]
    at org.elasticsearch.gateway.GatewayMetaState.upgradeMetadata(GatewayMetaState.java:279) ~[elasticsearch-7.17.11.jar:7.17.11]
    at org.elasticsearch.gateway.GatewayMetaState.upgradeMetadataForNode(GatewayMetaState.java:265) ~[elasticsearch-7.17.11.jar:7.17.11]
    at org.elasticsearch.gateway.GatewayMetaState.start(GatewayMetaState.java:178) ~[elasticsearch-7.17.11.jar:7.17.11]
    at org.elasticsearch.node.Node.start(Node.java:1183) ~[elasticsearch-7.17.11.jar:7.17.11]
    at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:335) ~[elasticsearch-7.17.11.jar:7.17.11]
    at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:443) ~[elasticsearch-7.17.11.jar:7.17.11]
    at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:169) ~[elasticsearch-7.17.11.jar:7.17.11]
    ... 6 more
```

Which means, this issue has a much bigger potential impact - 
**It can cause potential full-cluster loss due to one or more ES nodes not able to boot / start - nodes will go bootlooping if nodes hold indices having the setting in place and get restarted.**

---

cc @hubbleview

**Comment by DaveCTurner** [comment] 2024-01-16 10:11
Another user bitten by this pretty serious bug: https://discuss.elastic.co/t/elasticsearch-node-wont-start-after-updating-index-setting-with-index-mapper-dynamic/351101/1

**Comment by martijnvg** [comment] 2024-05-31 11:51
Closing this issue. The next 7.17 release will allow the `index.mapper.dynamic` index setting again (#109160), but it will not have any effect. Upon upgrading to a 8.x version the setting will be archived and it can no longer be set, because the setting is no longer defined (in 7.17.x the setting is defined, but custom validation disallowed the usage of the setting).

**Closed by martijnvg** 2024-05-31 11:51 UTC
Labels: >bug, Team:StorageEngine, :StorageEngine/Mapping
