### ISSUE TITLE
failed to sync translog(1.5.2)

### ISSUE THREAD

**Issue by 287400117** [elastic/elasticsearch#12120] opened 2015-07-08 08:05 UTC
[2015-07-08 16:00:53,447][WARN ][index.engine             ] [ES48225] [apksigs2015][32] failed to sync translog
[2015-07-08 16:00:53,451][WARN ][indices.cluster          ] [ES48225] [[apksigs2015][32]] marking and sending shard failed due to [failed recovery]
org.elasticsearch.index.gateway.IndexShardGatewayRecoveryException: [apksigs2015][32] failed to recover shard
        at org.elasticsearch.index.gateway.local.LocalIndexShardGateway.recover(LocalIndexShardGateway.java:290)
        at org.elasticsearch.index.gateway.IndexShardGatewayService$1.run(IndexShardGatewayService.java:112)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.index.translog.TranslogCorruptedException: translog corruption while reading from stream
        at org.elasticsearch.index.translog.ChecksummedTranslogStream.read(ChecksummedTranslogStream.java:72)
        at org.elasticsearch.index.gateway.local.LocalIndexShardGateway.recover(LocalIndexShardGateway.java:260)
        ... 4 more
Caused by: org.elasticsearch.ElasticsearchIllegalArgumentException: No type mapped for [0]
        at org.elasticsearch.index.translog.Translog$Operation$Type.fromId(Translog.java:237)
        at org.elasticsearch.index.translog.ChecksummedTranslogStream.read(ChecksummedTranslogStream.java:66)
        ... 5 more

**Comment by s1monw** [comment] 2015-07-08 08:08
this is fixed in the upcoming 2.0 this is unfortunately expected to see these kind of corruptions on 1.5

**Closed by s1monw** 2015-07-08 08:08 UTC

**Comment by 287400117** [comment] 2015-07-08 08:10
Now, how do I fix it

**Comment by kuduk** [comment] 2015-08-07 06:33
I resolved a similar problem caused by out of disk space. But in my log there are also something like that:

[2015-08-07 08:16:36,817][WARN ][cluster.action.shard     ] [Lady Octopus] [logstash-2015.08.04][3] received shard failed for [logstash-2015.08.04][3], node[mM2oHJ1ERzSknGsLlSbanQ], [P], s[INITIALIZING], indexUUID [_KQOGo3tQj6iRxYBkZk7TQ], reason [shard failure [failed recovery][IndexShardGatewayRecoveryException[[logstash-2015.08.04][3] failed to recover shard]; nested: TranslogCorruptedException[translog corruption while reading from stream]; nested: ElasticsearchIllegalArgumentException[No version type match [95]]; ]]


so I could delete corrupted indicies in /var/lib/elasticsearch/elasticsearch/nodes/0/indices

**Comment by 287400117** [comment] 2015-08-07 06:41
I also solved the problem, By removing translog, But some data may be lost

**Comment by kuduk** [comment] 2015-08-07 09:10
In my case i was lucky i deleted only indicies, my data stay on logstash :)
