### ISSUE TITLE
Aggregation on integer field returns float

### ISSUE THREAD

**Issue by ajupazhamayil** [elastic/elasticsearch#43258] opened 2019-06-15 11:37 UTC
**Elasticsearch version**: 7.1.1

**JVM version** : openjdk version 11.0.3

**OS version**: Ubuntu-18-04

**Description of the problem including expected versus actual behaviour**:
I have made an index with a property type integer and inserted a value. But when I try to do aggregation like min/max It results in a float value.

**Steps to reproduce**:
Create index:
```
curl -X PUT "localhost:9200/test" -H 'Content-Type: application/json' -d'
{
  "settings": {
    "number_of_shards": 1
  },
  "mappings": {
    "new_type": {
      "properties": {
        "nums": {
          "type": "integer"
        }
      }
    }
  }
}
'
```

Insert value:
```
curl -X PUT "localhost:9200/test/new_type/2" -H "Content-Type: application/json" -d'
{
    "nums" : 2
}
'
```

Find min:
```
curl -X POST "localhost:9200/test/_search?size=0" -H 'Content-Type: application/json' -d'
{
  "aggs": {
    "value": {
      "min": {
        "field": "nums"
      }
    }
  }
}
'
```

**Output (Actual)**:
```
{"took":40,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":1,"relation":"eq"},"max_score":null,"hits":[]},"aggregations":{"value":**{"value":2.0}**}}
```
**Output (Expected)**:
```
{"took":40,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":1,"relation":"eq"},"max_score":null,"hits":[]},"aggregations":{"value":**{"value":2}**}}
```

**Comment by jpountz** [comment] 2019-06-17 06:19
There has been a related discussion at #9545. This is due to the fact that numeric aggregations always use doubles as internal representations of the values they are working on, yet this can be problematic with long fields, since doubles can't represent their entire range.

One thing that made this issue hard to solve was the transport client, now that we are removing it in favor of the rest client, we could give it another try.

**Comment by not-napoleon** [comment] 2020-07-23 18:22
Relates to #60149 - High precision aggregations

**Comment by wchaparro** [comment] 2021-06-10 15:50
@giladgal FYI, we modified this one to enhancement as this is working as designed, and falls under the umbrella for high precision aggs

**Comment by wchaparro** [comment] 2024-07-02 19:23
This is not something we plan to implement in the near future in aggregations, and has been superceded by our focus on ESQL. Closing as not planned. If your feel strongly about this one, please let us know.

**Closed by wchaparro** 2024-07-02 19:23 UTC
Labels: >enhancement, :Analytics/Aggregations, Team:Analytics
