### ISSUE TITLE
es5 alpha fails to make progress

### ISSUE THREAD

**Issue by SweetNSourPavement** [elastic/elasticsearch#18799] opened 2016-06-09 12:36 UTC
**Elasticsearch version**:

5.0.0 alpha1/2/3 and v5.0.0-alpha3-216-g6202b63

**JVM version**:

java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

**OS version**:

Linux 107r01pc 4.2.0-36-generic # 42~14.04.1-Ubuntu SMP Fri May 13 17:27:22 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

A cluster with 3 data nodes and an index with 2 replicas can become
unavailable with the right order of node restarts. Other orderings of
restarts result in eventual availability.

I expected that 2 data nodes are always enough to service an index with
replication factor 3.

Other issues can be reproduced by very similar steps:
* with unsafe minimum master nodes restarts can cause data loss
* when only a quorum of the replicas are present incomplete replicas
  won't get fixed. it would be nice to see earlier replica healing.
  It seems to be safer and easier to move replicas if every working
  quorum of shards would heal themselves, as the missing nodes may
  crashed hard, and couldn't be restarted in any way.

**Steps to reproduce**:

There are some scripts to reproduce these issues, but attaching them is
not allowed, so, please, see
https://github.com/SweetNSourPavement/es5issue.

The gist of the modus operandi is:
 1. create an index with replication 3
 2. shut down one data node
 3. insert a doc, which should be successful, as a quorum is present
 4. stop and start nodes
 5. observe the result

**Comment by clintongormley** [comment] 2016-06-13 17:49
@ywelsch could you take a look at this please

**Comment by ywelsch** [comment] 2016-06-14 09:30
@SweetNSourPavement thanks for your interest in testing the ES 5.0 alpha releases and reporting back to us. Let me give some explanations for the observations you've made with ES. Setting `minimum_master_nodes` to a wrong value will indeed lead to data loss (I will later in this post explain why). We've taken a number of steps to make users aware of this:
- The default configuration has a section that talks about "split brain" and the setting `minimum_master_nodes`, pointing to our documentation.
- Since v5.0.0, we enforce that `minimum_master_nodes` is explicitly set in production mode (#17288)
- Since v5.0.0, we log warnings when we detect that `minimum_master_nodes` is set to less than a quorum of master-eligible nodes in the cluster (#15625)
- We are also discussing stricter rules to enforce that `minimum_master_nodes` is set to a quorum of master-eligible nodes (#18573).

The reason data loss occurs in case of split brains has to do with how we replicate data in ES. Data replication in ES is based on the primary/backup model. This means that there is a single shard copy that is the source of truth (called `the primary`), replicating it's contents to other shard copies. In case of the primary failing, one of the secondary copies is chosen as the new primary. Recovery on cluster restart is simple. The master choses a non-stale copy of the data as primary. The other shard copies simply resync their data from the new primary. As you might have noticed in this description, ES does not do quorum-based recoveries (it does not look at multiple shard copies to determine what data should be part of the new primary). The advantage of primary/backup replication is that this step is not required, making it a simple yet powerful model that also works in scenarios where users want to have only 2 copies of the data.

Let me explain now what happened in the specific scenario which you outlined above: node 1 (when it was shut down) thinks that all three (empty at that point) shard copies of the data are non-stale. After node 1 left, both node 2 and node 3 know that only their shard copies are good (and the copy of node 1 is stale). When restarting the cluster, node 1 gets up first, however, and elects itself as master (before node 2 and 3 are up). This can happen because `minimum_master_nodes` is wrongly set to 1. Node 1 thinks that it’s own copy of the data is good and makes it the primary shard. Node 2 and node 3 then join the cluster and resync their copies of the data from the primary, effectively removing the indexed document.

The other scenarios you describe can be explained in the same way and follow directly from the data replication model we use. If you want me to clarify on some points, I'm happy to explain further.

**Comment by SweetNSourPavement** [comment] 2016-06-14 13:21
Thank you for the explanation. My theories, which you now confirmed, led me to poke around replica quorums, and after realizing that this data loss scenario kinda works like intended I probed on.

The main issue I try to raise here is the inability of es5 to recover an index, even in a seemingly healthy enough state. The script `progress`, when run with parameter `red` configures the cluster correctly, I think:
* has 3 master nodes
* all masters stay up all the time, so they have the ability to witness all
* `minimum_master_nodes` is 2
* has 3 data nodes
* 2 data nodes are running when queries are made

and yet, the index state remains red.

**Comment by ywelsch** [comment] 2016-06-14 13:46
The index state remaining red is expected behavior in this case. When the data nodes shut down one after the other, only the last one will be seen as having a non-stale copy of the data. The reason is that the master nodes can only witness nodes leaving the cluster but not data being written to the shards. Assume for example that after the first two data nodes have left the cluster a document is indexed (and acknowledged) into the shard on the third node just before that one is shut down. To prevent data loss, the master nodes can only resurrect the shard on the third node as primary.

**Comment by SweetNSourPavement** [comment] 2016-06-14 14:58
I'm confused now. The expected behaviour is this:
* There's no guarantee that an index remains available (in the long run) if nodes stop and start?
* If an index remains unavailable, the best solution is to stop and start nodes until the correct start order is hit upon?

What am I missing? Availability seems not that high when an _expected_ single hard failure can cause unbounded unavailability, and human intervention is required.

**Comment by ywelsch** [comment] 2016-06-14 15:13
A single hard failure does not cause unbounded unavailability. In your scenario, there was a moment where 2 out of the 3 data nodes were unavailable (when restarted). This means that only the data on the third node was non-stale. Now by shutting down the third node and starting only the first two nodes this single remaining "good" copy became unavailable to the cluster...

The scenario with 3 data nodes and 3 shard copies supports two nodes to fail and the data to still be available.

**Comment by SweetNSourPavement** [comment] 2016-06-14 15:19
Only 1 of the data nodes is stopped, the other 2 are up and running, so the write should be a quorum write.

**Comment by clintongormley** [comment] 2016-06-14 15:23
@SweetNSourPavement That would be the case if all 3 nodes were running then one left.  However, you are recovering from scratch and the node holding the freshest shard copy has not yet appeared, which means that you might lose data unless you wait for it.

If that node is never coming back, there is an API which allows you to choose one of the stale shard copies as the new primary and to recover anyway, but you run the risk of losing data.

**Comment by ywelsch** [comment] 2016-06-14 15:27
> Only 1 of the data nodes is stopped, the other 2 are up and running, so the write should be a quorum write.

The two remaining data nodes are not stopped in perfect synchrony. There is a short moment in time where a write request can sneak in. Write requests do not have to be quorum, that is configurable on a per-request basis.

**Comment by SweetNSourPavement** [comment] 2016-06-14 15:34
So, I try to sum it up, maybe I will be clearer.

Here's what the script does:
* starts 3 master nodes
* starts 3 data node (in the script they are referenced as 4, 5 and 6)
* creates the index
* stops one data node (say 4)
* makes one insert
* stops the remaining data nodes (5 and 6)
* starts 2 data nodes (4 and 5)

and I expect the insert to be a quorum write, after that some unavailability while the nodes cycle through their business, and after that an index which can be read.

The way the nodes are chosen influence the final outcome, red or yellow index state.

**Comment by ywelsch** [comment] 2016-06-14 16:06
I'll reiterate what I said above. There is a moment in time in your scenario where only one data node is up (namely when you stop both node 5 and 6, which does not happen in perfect synchrony). The master node observes this and marks the shard on this last node as the only one to have non-stale data, thereby preventing data loss. Although no additional writes have happened in your scenario while stopping the data nodes 5 and 6, that's something the master node is unaware of (it does not participate in data replication).

**Comment by SweetNSourPavement** [comment] 2016-06-14 16:23
That's maybe true, I've not read anything substantial on es replication yet, but doesn't help anybody with a stuck index. Power cycles and crashes are normal. Is my test misconfigured? What can I do to have some real higher availability?

**Comment by clintongormley** [comment] 2016-06-14 17:15
> Power cycles and crashes are normal. Is my test misconfigured? What can I do to have some real higher availability?

With a power cycle, you expect all nodes to rejoin, in which case your index will go green.  With a running cluster where one or two nodes crash, the freshest primary is still online, in which case you can still index with `write_consistency=1` (which is one more node you can afford to lose than with a quorum).  If you do a full cluster restart and don't bring up all the nodes, then you may have lost data.  In this case a human needs to say "i'd rather lose data than keep on waiting".

**Comment by SweetNSourPavement** [comment] 2016-06-16 12:14
Do you plan improving on this?

**Comment by clintongormley** [comment] 2016-06-16 12:42
> Do you plan improving on this?

How would you suggest doing so?

**Comment by ywelsch** [comment] 2016-06-16 12:51
Yes, we're currently discussing a solution that involves not marking a shard copy as stale on node shutdown as long as none of the other active shards have received acknowledged writes. I've opened an issue for this here (#18919) so you can track progress on that.

**Comment by jasontedor** [comment] 2016-06-17 19:53
Closing in favor of #18919

**Closed by jasontedor** 2016-06-17 19:53 UTC
Labels: :Cluster, Pioneer Program
