### ISSUE TITLE
[CI] LangMustacheClientYamlTestSuiteIT "30_search_template/Test that parameters can be used" fails

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#28150] opened 2018-01-09 11:39 UTC
This one fails on 6.1 using the zing jvm:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.1+zing/22/console

The error looks like it should reproduce but I couldn't get it to fail locally, maybe because of the different jvm. Also tried with 8u152-zulu but couldn't reproduce either. I'll open this issue in case something similar turns up on another build. Maybe its also clear from the test itself what needs fixing here.

```
  2> REPRODUCE WITH: ./gradlew :modules:lang-mustache:integTestRunner -Dtests.seed=E3848DFA5F597EE -Dtests.class=org.elasticsearch.script.mustache.LangMustacheClientYamlTestSuiteIT -Dtests.method="test {yaml=lang_mustache/30_search_template/Test that parameters can be used}" -Dtests.security.manager=true -Dtests.locale=es -Dtests.timezone=America/Panama
  1> [2018-01-08T21:17:35,116][INFO ][o.e.s.m.LangMustacheClientYamlTestSuiteIT] Stash dump on failure [{
  1>   "stash" : {
  1>     "body" : {
  1>       "took" : 1,
  1>       "timed_out" : false,
  1>       "_shards" : {
  1>         "total" : 5,
  1>         "successful" : 5,
  1>         "skipped" : 0,
  1>         "failed" : 0
  1>       },
  1>       "hits" : {
  1>         "total" : 1,
  1>         "max_score" : 0.28768208622932434,
  1>         "hits" : [
  1>           {
  1>             "_shard" : "[test][0]",
  1>             "_node" : "pGAo_0v-Rxyb05j3udZc_A",
  1>             "_index" : "test",
  1>             "_type" : "type",
  1>             "_id" : "5",
  1>             "_score" : 0.28768208622932434,
  1>             "_source" : {
  1>               "otherField" : "foo"
  1>             },
  1>             "_explanation" : {
  1>               "value" : 0.28768208622932434,
  1>               "description" : "weight(otherField:foo in 0) [PerFieldSimilarity], result of:",
  1>               "details" : [
  1>                 {
  1>                   "value" : 0.28768208622932434,
  1>                   "description" : "score(doc=0,freq=1.0 = termFreq=1.0
  1> ), product of:",
  1>                   "details" : [
  1>                     {
  1>                       "value" : 0.28768208622932434,
  1>                       "description" : "idf, computed as log(1 + (docCount - docFreq + 0.5) / (docFreq + 0.5)) from:",
  1>                       "details" : [
  1>                         {
  1>                           "value" : 1.0,
  1>                           "description" : "docFreq",
  1>                           "details" : [ ]
  1>                         },
  1>                         {
  1>                           "value" : 1.0,
  1>                           "description" : "docCount",
  1>                           "details" : [ ]
  1>                         }
  1>                       ]
  1>                     },
  1>                     {
  1>                       "value" : 1.0,
  1>                       "description" : "tfNorm, computed as (freq * (k1 + 1)) / (freq + k1 * (1 - b + b * fieldLength / avgFieldLength)) from:",
  1>                       "details" : [
  1>                         {
  1>                           "value" : 1.0,
  1>                           "description" : "termFreq=1.0",
  1>                           "details" : [ ]
  1>                         },
  1>                         {
  1>                           "value" : 1.2000000476837158,
  1>                           "description" : "parameter k1",
  1>                           "details" : [ ]
  1>                         },
  1>                         {
  1>                           "value" : 0.75,
  1>                           "description" : "parameter b",
  1>                           "details" : [ ]
  1>                         },
  1>                         {
  1>                           "value" : 1.0,
  1>                           "description" : "avgFieldLength",
  1>                           "details" : [ ]
  1>                         },
  1>                         {
  1>                           "value" : 1.0,
  1>                           "description" : "fieldLength",
  1>                           "details" : [ ]
  1>                         }
  1>                       ]
  1>                     }
  1>                   ]
  1>                 }
  1>               ]
  1>             }
  1>           }
  1>         ]
  1>       }
  1>     }
  1>   }
  1> }]
FAILURE 1.32s | LangMustacheClientYamlTestSuiteIT.test {yaml=lang_mustache/30_search_template/Test that parameters can be used} <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Failure at [lang_mustache/30_search_template:116]: hits.hits.0._explanation.description didn't match expected value:
   > hits.hits.0._explanation.description: expected [weight(otherField:foo in 1) [PerFieldSimilarity], result of:] but was [weight(otherField:foo in 0) [PerFieldSimilarity], result of:]
   > 	at __randomizedtesting.SeedInfo.seed([E3848DFA5F597EE:866C77050B09FA16]:0)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:350)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:330)
   > 	at java.lang.Thread.run(Thread.java:748)
   > Caused by: java.lang.AssertionError: hits.hits.0._explanation.description didn't match expected value:
   > hits.hits.0._explanation.description: expected [weight(otherField:foo in 1) [PerFieldSimilarity], result of:] but was [weight(otherField:foo in 0) [PerFieldSimilarity], result of:]
   > 	at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:87)
   > 	at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:76)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:346)
   > 	... 38 more
```

**Comment by cbuescher** [comment] 2018-01-11 10:08
Another one today: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+zing

**Comment by cbuescher** [comment] 2018-01-26 13:24
Another one: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+zing/83/console

**Comment by s1monw** [comment] 2018-01-26 13:38
I was able to reproduce it and I think I know what the issue is. I will look into it and assign it to me.

**Comment by s1monw** [comment] 2018-01-26 13:53
close by 7957c9751cb98dc3c72797f26f952eb07f9329eb

**Closed by s1monw** 2018-01-26 13:53 UTC
Labels: :Templates, jenkins
