### ISSUE TITLE
SingleNodeDiscoveryIT.testCannotJoinNodeWithSingleNodeDiscovery

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#84351] opened 2022-02-24 15:59 UTC
### CI Link

https://gradle-enterprise.elastic.co/s/udrxwwlnmmbzo

### Repro line

`gradlew ':server:internalClusterTest' --tests "org.elasticsearch.discovery.single.SingleNodeDiscoveryIT.testCannotJoinNodeWithSingleNodeDiscovery" -Dtests.seed=C1877C38D3336473 -Dtests.locale=is-IS -Dtests.timezone=America/Argentina/Buenos_Aires -Druntime.java=17`

### Does it reproduce?

No

### Applicable branches

master

### Failure excerpt

```
        Caused by:
        java.lang.AssertionError: java.lang.IllegalArgumentException: remote node [{node-0}{KhfdIDeLRjKkvNVyZQ_L_w}{nIW0rezVTeq_GS7dY4f5kw}{127.0.0.1}{127.0.0.1:36755}{cdfhilmrstw}{testattr=test, ml.machine_memory=101200797696, xpack.installed=true, ml.max_jvm_size=536870912}] is build [6c6721e0ac07ef751383195ff66d7957eb3712f4] of version [8.2.0] but this node is build [unknown] of version [8.2.0] which has an incompatible wire format
            at __randomizedtesting.SeedInfo.seed([C1877C38D3336473]:0)
            at org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:346)
            at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:142)
            at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:94)
            at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:796)
            at org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:149)
            at org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:121)
            at org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:86)
            at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
            at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
            at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
            at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
            at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
            at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
            at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
            at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
            at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
            at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
            at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:623)
            at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:586)
            at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
            at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
            at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
            at java.base/java.lang.Thread.run(Thread.java:833)

            Caused by:
            java.lang.IllegalArgumentException: remote node [{node-0}{KhfdIDeLRjKkvNVyZQ_L_w}{nIW0rezVTeq_GS7dY4f5kw}{127.0.0.1}{127.0.0.1:36755}{cdfhilmrstw}{testattr=test, ml.machine_memory=101200797696, xpack.installed=true, ml.max_jvm_size=536870912}] is build [6c6721e0ac07ef751383195ff66d7957eb3712f4] of version [8.2.0] but this node is build [unknown] of version [8.2.0] which has an incompatible wire format
                at org.elasticsearch.transport.TransportService$HandshakeResponse.<init>(TransportService.java:582)
                at org.elasticsearch.action.ActionListenerResponseHandler.read(ActionListenerResponseHandler.java:58)
                at org.elasticsearch.action.ActionListenerResponseHandler.read(ActionListenerResponseHandler.java:25)
                at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1330)
                at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1317)
                at org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:338)
```

**Comment by DaveCTurner** [comment] 2022-02-28 09:37
I don't get it.

`remote node [...] is build [6c6721e0ac07ef751383195ff66d7957eb3712f4] of version [8.2.0] but this node is build [unknown]`.

Both `6c6721e0ac07ef751383195ff66d7957eb3712f4` and `unknown` are from `Build.CURRENT.hash()`. `Build#CURRENT` is a `static final` field, and `hash()` is a record accessor so effectively reading a final field too. Are there multiple classloaders in play? Even if so, how are they not picking up the same hash?

I think this needs core/infra help.

**Comment by DaveCTurner** [comment] 2022-03-01 08:19
Hmm maybe the rogue node is genuinely a separate process, running on the CI worker for reasons that are completely unrelated to this test. Its node ID and port don't appear anywhere else in the CI log, and they're both called `node-0`. We don't run test tasks in containers to isolate them from each other AFAIK.

Not sure why we'd have a node with build `unknown` running here tho, nor why it would be trying to handshake with this nonstandard port, nor do I have great ideas for tracking it down.

**Comment by ChrisHegarty** [comment] 2022-03-01 14:04
Probably unrelated, but when trying to reproduce on my local machine (macOs M1), I see the test intermittently fail for a different reason. 

I just run the repro command from the description with `-Dtests.iters=5`

About 2-3 runs fails with:
```
2> java.lang.AssertionError: expected to see test but did not
  Expected: <true>
     but: was <false>
    at __randomizedtesting.SeedInfo.seed([C1877C38D3336473:35221F5B8EA210F6]:0)
    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
    at org.elasticsearch.test.MockLogAppender$SeenEventExpectation.assertMatched(MockLogAppender.java:121)
    at org.elasticsearch.test.MockLogAppender.assertAllExpectationsMatched(MockLogAppender.java:55)
    at org.elasticsearch.discovery.single.SingleNodeDiscoveryIT.lambda$testCannotJoinNodeWithSingleNodeDiscovery$0(SingleNodeDiscoveryIT.java:178)
    at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1068)
    at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1041)
```

**Comment by DaveCTurner** [comment] 2022-03-01 16:10
What commit are you using there @ChrisHegarty? `SingleNodeDiscoveryIT.java:178` doesn't make sense to me:

```
$ git rev-parse master
400fb28845c4a9a607d6368a0778efe60ce90317
$ git show 400fb28845c4a9a607d6368a0778efe60ce90317:./server/src/internalClusterTest/java/org/elasticsearch/discovery/single/SingleNodeDiscoveryIT.java  | nl -ba | sed -ne '176,181p'
   176	    }
   177
   178	    public void testStatePersistence() throws Exception {
   179	        createIndex("test");
   180	        internalCluster().fullRestart();
   181	        assertTrue(indexExists("test"));
```

**Comment by DaveCTurner** [comment] 2022-03-01 16:40
Ok gotcha. This is strange tho, I've run thousands of iterations (on my Linux machine) with no issues. Is it a timing thing? `assertBusy()` times out after 10s, could you extend it to 30s?

**Comment by grcevski** [comment] 2022-03-09 16:20
This is likely a duplicate of https://github.com/elastic/elasticsearch/issues/83034

**Comment by grcevski** [comment] 2022-03-09 16:30
Closing as duplicate of https://github.com/elastic/elasticsearch/issues/83034

**Closed by grcevski** 2022-03-09 16:30 UTC
Labels: :Distributed/Network, >test-failure, Team:Distributed
