### ISSUE TITLE
Master node crashes with OutOfMemoryError exception

### ISSUE THREAD

**Issue by dwo** [elastic/elasticsearch#21439] opened 2016-11-09 18:54 UTC
**Elasticsearch version**: 2.2.0

**Plugins installed**: [kopf, aws]

**JVM version**: 1.8.0_101

**OS version**: Linux (3.14.35-28.38.amzn1.x86_64)

**Description of the problem including expected versus actual behavior**:

We run a large Elasticsearch cluster in AWS: ~60 nodes, ~2000 indices, 34K shards, ~13 Billion docs (sans replicas) and ~25TB of data. The cluster is write-heavy, a majority of documents go in through the bulk API via Logstash 2.3.

We've noticed our master nodes crashing under certain circumstances and have captured a heap dump. In the latest case, we had several data nodes run out of disk space, which we suspect stopped shards being routed to data nodes.

The heap dump reveals `Thread causing OutOfMemoryError exception: elasticsearch[Psi-Lord][transport_client_worker][T#1]{New I/O worker #1}`.

In previous cases, before we were capturing heap dumps, we suspected a very similar thing happened to our cluster a few times at midnight UTC when many daily and hourly indices would be created automatically at once by bulk API requests.

**Expected behaviour**: Graceful failure of bulk API requests and shard routing on master node.

**Actual behaviour**: Heap is exhausted, master node crashes with OOM exception.

Here's an image of the top classes in the heap dump.
![screen shot 2016-11-09 at 6 09 02 pm](https://cloud.githubusercontent.com/assets/131652/20149918/39843186-a6ab-11e6-825a-c5edf2950861.png)

Here's the same thing but filtered to `org.elasticsearch.*`
![screen shot 2016-11-09 at 6 09 20 pm](https://cloud.githubusercontent.com/assets/131652/20149936/49704328-a6ab-11e6-8788-65c4dc4e3f1a.png)

Here's a graph of JVM heap used as percent on the master when it died.
![screen shot 2016-11-09 at 6 06 11 pm](https://cloud.githubusercontent.com/assets/131652/20149939/5193cc00-a6ab-11e6-945d-dadf5cdac0e3.png)

**Provide logs (if relevant)**:

The disk space issues that we think predicated this issue:

```
low disk watermark [85%] exceeded on [CxBLzItaRmOIXRBBObW1iQ][Master Man][/data/cluster/nodes/0] free: 111.3gb[14.1%], replicas will not be assigned to this node
```

followed by

```
failed to put mappings on indices [[indexname-2016.11.09.18]], type [logs]
failed to execute bulk item (index) index {[indexname-2016.11.09.18][logs][AVhKVPX-QITpIF62dCmj], source[{...
```

Full thread stack trace:
```
"elasticsearch[Psi-Lord][transport_client_worker][T#1]{New I/O worker #1}" daemon prio=5 tid=19 RUNNABLE
	at java.lang.OutOfMemoryError.<init>(OutOfMemoryError.java:48)
	at org.elasticsearch.cluster.routing.ShardRouting.readShardRoutingEntry(ShardRouting.java:293)
	at org.elasticsearch.action.admin.indices.stats.ShardStats.readFrom(ShardStats.java:96)
	at org.elasticsearch.action.admin.indices.stats.ShardStats.readShardStats(ShardStats.java:90)
	at org.elasticsearch.action.admin.indices.stats.TransportIndicesStatsAction.readShardResult(TransportIndicesStatsAction.java:80)
	at org.elasticsearch.action.admin.indices.stats.TransportIndicesStatsAction.readShardResult(TransportIndicesStatsAction.java:47)
	at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$NodeResponse.readFrom(TransportBroadcastByNodeAction.java:533)
	at org.elasticsearch.transport.netty.MessageChannelHandler.handleResponse(MessageChannelHandler.java:177)
	at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:138)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Anything else I could share: let me know.

**Comment by dwo** [comment] 2016-11-10 11:22
I looked through subsequent (to 2.2.0) release notes this morning and wondered if these resolved issues might be related: 

* #15678 "Speed improvements for BalancedShardsAllocator" (in 2.3.0)
* #16926 "Speed up shard balancer by reusing shard model while moving shards that can no longer be allocated to a node" (in 2.3.0)
* #17106 "IndicesStore checks for `allocated elsewhere` for every shard not alocated on the local node" (in 2.2.2)

**Comment by clintongormley** [comment] 2016-11-10 11:29
@ywelsch any ideas?

**Comment by ywelsch** [comment] 2016-11-10 15:07
> Anything else I could share: let me know.

- Could you make the heap dump available? Could you also provide a heap dump under normal operations to use as a baseline? The top classes show 10 million ShardRouting instances and I would like to know what's keeping those references (I suspect InternalClusterInfoService).
- Interesting would also be to know the pending tasks on the master as well as to have a graph for the number of pending tasks on the master over time (similar to the "JVM heap used" graph).
- The `hot_threads` output might also be useful to figure out what's happening here.

The PRs you linked above help to speed up calculation of cluster state updates, which in turn helps the master in processing its queue of pending tasks. This will definitely help the master in processing a large queue of pending tasks but I'm not sure whether that's the root cause here.

**Comment by dwo** [comment] 2016-11-12 14:23
Hey, just getting around to digging into these for you. I'm not sure whether I can make the heap dump available, but I can do my best to answer your questions.

> Could you also provide a heap dump under normal operations to use as a baseline?

Here is a sampled heap of a healthy master (sorted by instances):

<img width="919" alt="screen shot 2016-11-12 at 2 12 03 pm" src="https://cloud.githubusercontent.com/assets/131652/20238387/3aade1f4-a8e2-11e6-9158-e8546d010afd.png">

Same again, filtered to `org.elasticsearch.*`:

<img width="919" alt="screen shot 2016-11-12 at 2 12 35 pm" src="https://cloud.githubusercontent.com/assets/131652/20238392/5b9bfebe-a8e2-11e6-855f-0082278d3b03.png">

> The top classes show 10 million ShardRouting instances and I would like to know what's keeping those references (I suspect InternalClusterInfoService).

Let me post about this when my computer has stopped sounding like a jet engine. VisualVM is crunching through those instances in the dump as I type up the rest of this...

> Interesting would also be to know the pending tasks on the master as well as to have a graph for the number of pending tasks on the master over time (similar to the "JVM heap used" graph).

Here you go. Orange = master that OOM'd, Yellow = master that took over (same one I just got the sampled heap dumps above from):

<img width="617" alt="screen shot 2016-11-12 at 2 02 28 pm" src="https://cloud.githubusercontent.com/assets/131652/20238399/99448650-a8e2-11e6-8d8e-67dd2b4b652c.png">

> The `hot_threads` output might also be useful to figure out what's happening here.

I hit a dead end here, I don't think we have been harvesting these stats. Maybe I'm wrong, I'll ask around on Monday.

**Comment by dwo** [comment] 2016-11-12 15:09
Any tips on how to go about exploring the references to `ShardRouting` instances? Clicking around in VisualVM, I can't see any reference to `InternalClusterInfoService` like you suspected.

<img width="991" alt="screen shot 2016-11-12 at 2 59 59 pm" src="https://cloud.githubusercontent.com/assets/131652/20238709/8ebf73c8-a8e9-11e6-83c7-5d79fa9c303c.png">

On `hot_threads`: is there any way to inspect that retroactively if you aren't for eg. logging the output of the response from `<elastic_host:port>/_nodes/<master_id>/hot_threads` periodically? I can see some `HotThreads` instances in the heap dump, but they don't seem to hold much information (or I just don't know where to look).

**Comment by dwo** [comment] 2016-11-12 20:26
I got a better picture of where the `ShardRouting` instances are coming from with [MAP](https://www.eclipse.org/mat/).

<img width="1392" alt="screen shot 2016-11-12 at 8 13 11 pm" src="https://cloud.githubusercontent.com/assets/131652/20240615/cf547c32-a914-11e6-9d43-04590af1d730.png">

There are a lot more of those `java.util.HashMap$Node`s making up the 4.8GB total for `InternalClusterService`, but there's also `org.elasticsearch.cluster.ClusterState` in there too.

<img width="1392" alt="screen shot 2016-11-12 at 8 25 04 pm" src="https://cloud.githubusercontent.com/assets/131652/20240667/1ff1e70a-a916-11e6-91e2-8c6f745133a3.png">

**Comment by ywelsch** [comment] 2016-11-13 17:09
Thanks for providing the heap analysis pictures. With the last batch I have figured out what's going on: Some response listeners that are used for cluster state update tasks (e.g. index creation) keep a reference to state that is completely unnecessary to later run the listeners (one of these thing they hold on to is the last cluster state that was applied when the update task was submitted). If the master has a large pending queue of such tasks, it possibly keeps references to many old cluster states. I'll look at options to fix this.

Example showing the issue:

<img width="1233" alt="screen shot 2016-11-13 at 12 00 23" src="https://cloud.githubusercontent.com/assets/3718355/20245114/a282e498-a999-11e6-996c-35e1084ffb24.png">

**Comment by dwo** [comment] 2016-11-13 21:17
Nice one, let me know if you need anything else from the heap dump.

**Comment by clintongormley** [comment] 2016-11-19 15:45
Closing in favour of https://github.com/elastic/elasticsearch/issues/21568

**Closed by clintongormley** 2016-11-19 15:45 UTC
Labels: :Core, bug
