### ISSUE TITLE
Request breaker leaking on connection dropped/reset

### ISSUE THREAD

**Issue by jklap** [elastic/elasticsearch#24113] opened 2017-04-14 15:49 UTC
**Elasticsearch version**: 5.2.2

**Plugins installed**: [search-guard-5]

**JVM version**: OpenJDK 1.8.0_121

**OS version**: Red Hat Enterprise Linux Server release 7.3 (Maipo)

**Description of the problem including expected versus actual behavior**:

We are currently running Elastic with fluentd pushing in log data via a bulk index. Yesterday we ran some large tests (~1 million rows of log data) pushing in a large number of rows in a short period of time.

Some of those pushes from fluentd timed out (it had a 5 second response timeout check), likely because Elastic was dealing with the volume and starting heavy GC.

During this the request breaker filled and stayed full (example below not the real deal since I didn't copy & paste it-- can't remember if the estimated was slightly above or below the limit):

```
2017-04-13 14:23:49 -0400 [warn]: temporarily failed to flush the buffer. next_retry=2017-04-13 14:23:48 -0400 error_class="Elasticsearch::Transport::Transport::Errors::ServiceUnavailable" error="[503] {\"error\":{\"root_cause\":[{\"type\":\"circuit_breaking_exception\",\"reason\":\"[parent] Data too large, data for [<http_request>] would be larger than limit of [2242655027/2gb]\",\"bytes_wanted\":2267000752,\"bytes_limit\":2242655027}],\"type\":\"circuit_breaking_exception\",\"reason\":\"[parent] Data too large, data for [<http_request>] would be larger than limit of [2242655027/2gb]\",\"bytes_wanted\":2267000752,\"bytes_limit\":2242655027},\"status\":503}" plugin_id="catchall-elastic-access"
```

```
"limit_size_in_bytes": 1922275737,
"limit_size": "1.7gb",
"estimated_size_in_bytes": 2242655027,
"estimated_size": "2gb",
```

Fluentd would continue to retry pushing over the rest of the queued date every 30 minutes but Elastic never recovered until it was restarted.

Once I restarted Elastic, the last two bulk index requests were pushed from fluentd and the request breaker was left at 0.

This morning I when through the process end-to-end again and encountered the same behavior (including the fluentd request timeout).

I can reproduce this manually (and consistently) using Paw (http://paw.cloud) with the below bulk request by executing the request and then executing the request again before the first request completed (which I'm assuming is abruptly closing the first request's connection):

```
{ "index" : { "_index" : "logstash-test", "_type" : "test" } }
{"method":"GET","remoteHost":"192.168.0.11","responseTime":"3","requestURI":"/test","message":"GET /authds/status?details","responseCode":"200","file":"access_log.2017-04-13.txt","bytes":"454","host":"localhost","http":"HTTP/1.0","user":"tester","@timestamp":"2017-08-28T19:46:40-04:00","tag":"access"}
```

With the above request, each time I abort the request the request breaker grows by 16,440.

Also note: A large number of those requests had invalid timestamps and hence Elastic threw errors on the @timetamp parsing (noted here because it happened, but not sure it contributed to the issue)
* [stacktrace.txt](https://github.com/elastic/elasticsearch/files/922303/stacktrace.txt)

**Comment by jasontedor** [comment] 2017-04-14 16:12
I do not doubt you have the version correct but I must double check, are you sure that you're on version 5.2.2 everywhere? I must double check because I think we fixed this exact issue in 5.2.2 (cf. #23310). Does this reproduce *without* search-guard-5 installed?

**Comment by jklap** [comment] 2017-04-14 16:29
Always good to double check.

Problem with having a dev instance.

Production, where this problem is occurring, is running **5.2.1**

I should be able to bump production up to 5.3 this coming week and can verify it's addressed there!

**Comment by jasontedor** [comment] 2017-04-14 16:35
> Production, where this problem is occurring, is running *5.2.1*

Okay, this is a *huge* sigh of relief for me, and I appreciate you double checking and reporting back. The bug definitely exists in 5.2.1, I think what you're experiencing is definitely fixed in 5.2.2 so if you upgrade there or even to 5.3.0 you'll get the fix. I would really appreciate you verifying after upgrading when you have a chance. This was an incredibly nasty bug to track down!

**Comment by jasontedor** [comment] 2017-04-26 02:44
I'm going to close this, if you have an update either way it would be appreciated (and we can reopen this if there is still an issue here).

**Closed by jasontedor** 2017-04-26 02:44 UTC
Labels: :Circuit Breakers, feedback_needed

**Comment by jklap** [comment] 2017-04-26 13:05
Sorry-- was OOTO. Yes, we updated to 5.3.x last week and I've been watching the breaker(s)-- as of late last week everything looked good-- thanks for the work on the previous ticket!

**Comment by jasontedor** [comment] 2017-04-26 13:51
Thanks for verifying @jklap, happy to hear that all is well!
