### ISSUE TITLE
Indices _stats ignores completely red indices

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#27178] opened 2017-10-30 18:38 UTC
```http
DELETE /test

PUT /test
{
  "settings": {
    "index.routing.allocation.require.dne": "dne"
  }
}

GET /test/_stats
```

This results in the response:

```json
{
  "_shards": {
    "total": 10,
    "successful": 0,
    "failed": 0
  },
  "_all": {
    "primaries": {},
    "total": {}
  },
  "indices": {}
}
```

It makes sense why, and the giveaway is in `_shards`, but it is extremely misleading to get such a response back without the index. It is most misleading because any index with at least one shard that is _not_ red will appear in the stats response, which makes it inconsistent in my opinion.

I think that it would be fine if it listed the index with either all zeroes for `total` and `primaries` counts, or simply didn't define those inner objects at all.

**Comment by jyoti0208** [comment] 2017-11-16 09:44
I would like to work on this.

**Comment by cbismuth** [comment] 2018-10-11 15:37
Thank you for this report @pickypg, I can reproduce it on `master` (see [cURL recreation script](https://gist.github.com/cbismuth/fe2894839f219be337a2d20a02f1a8df)). I'll have a look at this one and let you know.

**Comment by cbismuth** [comment] 2018-10-15 14:47
I've opened PR #34463 to fix this issue.

**Comment by dakrone** [comment] 2024-05-08 21:50
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.

**Closed by dakrone** 2024-05-08 21:50 UTC
Labels: >bug, help wanted, :Data Management/Stats, Team:Data Management
