### ISSUE TITLE
Match Phrase Prefix Issue

### ISSUE THREAD

**Issue by manikandanselva** [elastic/elasticsearch#39995] opened 2019-03-13 14:19 UTC
Hi 

{
  "query": {
    "dis_max": {
      "queries": [
        {
          "match_phrase_prefix": {
            "message": "[12/Mar/2019"
          }
        },
        {
          "match_phrase_prefix": {
            "message": "[2019-03-12"
          }
        },
        {
          "match_phrase_prefix": {
            "message": " Mar 12 "
          }
        }
      ]
    }
  }
}

this is my filter query in kibana bt i also get following field 2019:03:12 (time data)

**Comment by jimczi** [comment] 2019-03-13 16:57
Can you explain what the issue is ? It is hard to understand the problem with the current description. 
The templates for new issue describes the information that you need to provide when reporting a possible bug:
````
<!-- Bug report -->

**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:
````

**Comment by manikandanselva** [comment] 2019-03-14 09:04
> Can you explain what the issue is ? It is hard to understand the problem with the current description.
> The templates for new issue describes the information that you need to provide when reporting a possible bug:
> 
> ```
> 
> 
> **Elasticsearch version** (`bin/elasticsearch --version`):
> 
> **Plugins installed**: []
> 
> **JVM version** (`java -version`):
> 
> **OS version** (`uname -a` if on a Unix-like system):
> 
> **Description of the problem including expected versus actual behavior**:
> 
> **Steps to reproduce**:
> 
> Please include a *minimal* but *complete* recreation of the problem, including
> (e.g.) index creation, mappings, settings, query etc.  The easier you make for
> us to reproduce it, the more likely that somebody will take the time to look at it.
> 
>  1.
>  2.
>  3.
> 
> **Provide logs (if relevant)**:
> ```

This also In search Query Ex : Search is .....AND message:("2019-03-13") But I got also given field of data in search result [14/Mar/2019:03:13:57 +0000]

**Comment by jimczi** [comment] 2019-03-15 08:40
Thanks @manikandanselva, this is probably because you've set the `message` field as a `text` field. If you want to match `date` accurately you'll need to use the type `date` in your mapping, otherwise the query is analyzed and the default analyzer removes the punctuation (`-`, `/`, ...). We reserve github for bugs and feature requests so I hope you don't mind that I close this issue. We can continue to discuss your mapping and how mappings and queries work in general but the forum is better suited for this kind of discussion. Please open a topic on the [discuss forum](https://discuss.elastic.co/c/elasticsearch) if you have more questions and me or someone from the community should be able to help you.

**Closed by jimczi** 2019-03-15 08:40 UTC
Labels: feedback_needed
