### ISSUE TITLE
Preserve log4j2.properties in RPM/deb installation

### ISSUE THREAD

**Issue by seang-es** [elastic/elasticsearch#24120] opened 2017-04-14 20:44 UTC
It looks like the packaging scripts currently preserve elasticsearch.yml, jvm.options, and logging.yml.  log4j2.properties is not in the list of preserved files, so if it is customized it will be overwritten during an upgrade.

**Comment by jasontedor** [comment] 2017-04-14 23:29
This does not sound right, we [mark](https://github.com/elastic/elasticsearch/blob/v5.3.0/distribution/build.gradle#L407) it as a configuration file and I'm pretty sure that we have a test for it. I will check on Monday.

**Comment by jasontedor** [comment] 2017-04-14 23:31
What version was the upgrade from and to?

**Comment by jasontedor** [comment] 2017-04-15 12:48
I tested this and everything behaved as expected. Specifically, I installed Elasticsearch 5.2.1, edited the log4j2.properties, upgraded to Elasticsearch 5.2.2, and the modifications that I made were still present. I then upgraded to Elasticsearch 5.3.0, and the modifications that I made were still present. The reason that I tested a second upgrade is because we shipped a new log4j2.properties file starting in Elasticsearch 5.3.0 and the expected behavior here is not that the new configuration file would overwrite the existing configuration file (if there were modifications) but would instead be saved alongside the existing configuration file so that an end-user has the option to merge the new package-provided configuration file with their existing configuration file if they so desire. This is exactly what happened.

CentOS 6:

```
centos-6:/home/vagrant$ rpm -i elasticsearch-5.2.1.rpm 
warning: elasticsearch-5.2.1.rpm: Header V4 RSA/SHA512 Signature, key ID d88e42b4: NOKEY
Creating elasticsearch group... OK
Creating elasticsearch user... OK
### NOT starting on installation, please execute the following statements to configure elasticsearch service to start automatically using chkconfig
 sudo chkconfig --add elasticsearch
### You can start elasticsearch service by executing
 sudo service elasticsearch start
centos-6:/home/vagrant$ grep "\(debug\|info\)" /etc/elasticsearch/log4j2.properties
# log action execution errors for easier debugging
logger.action.level = debug
rootLogger.level = info
centos-6:/home/vagrant$ perl -p -i -e 's/info/debug/g' /etc/elasticsearch/log4j2.properties
centos-6:/home/vagrant$ grep "\(debug\|info\)" /etc/elasticsearch/log4j2.properties
# log action execution errors for easier debugging
logger.action.level = debug
rootLogger.level = debug
centos-6:/home/vagrant$ rpm -U elasticsearch-5.2.2.rpm 
warning: elasticsearch-5.2.2.rpm: Header V4 RSA/SHA512 Signature, key ID d88e42b4: NOKEY
centos-6:/home/vagrant$ grep "\(debug\|info\)" /etc/elasticsearch/log4j2.properties
# log action execution errors for easier debugging
logger.action.level = debug
rootLogger.level = debug
centos-6:/home/vagrant$ rpm -U elasticsearch-5.3.0.rpm 
warning: elasticsearch-5.3.0.rpm: Header V4 RSA/SHA512 Signature, key ID d88e42b4: NOKEY
warning: /etc/elasticsearch/log4j2.properties created as /etc/elasticsearch/log4j2.properties.rpmnew
centos-6:/home/vagrant$ grep "\(debug\|info\)" /etc/elasticsearch/log4j2.properties
# log action execution errors for easier debugging
logger.action.level = debug
rootLogger.level = debug
centos-6:/home/vagrant$ grep "\(debug\|info\)" /etc/elasticsearch/log4j2.properties.rpmnew 
# log action execution errors for easier debugging
logger.action.level = debug
rootLogger.level = info
centos-6:/home/vagrant$ 
```

CentOS 7:

```
centos-7:/home/vagrant$ rpm -i elasticsearch-5.2.1.rpm 
warning: elasticsearch-5.2.1.rpm: Header V4 RSA/SHA512 Signature, key ID d88e42b4: NOKEY
Creating elasticsearch group... OK
Creating elasticsearch user... OK
### NOT starting on installation, please execute the following statements to configure elasticsearch service to start automatically using systemd
 sudo systemctl daemon-reload
 sudo systemctl enable elasticsearch.service
### You can start elasticsearch service by executing
 sudo systemctl start elasticsearch.service
centos-7:/home/vagrant$ grep "\(debug\|info\)" /etc/elasticsearch/log4j2.properties
# log action execution errors for easier debugging
logger.action.level = debug
rootLogger.level = info
centos-7:/home/vagrant$ perl -p -i -e 's/info/debug/g' /etc/elasticsearch/log4j2.properties
centos-7:/home/vagrant$ grep "\(debug\|info\)" /etc/elasticsearch/log4j2.properties
# log action execution errors for easier debugging
logger.action.level = debug
rootLogger.level = debug
centos-7:/home/vagrant$ rpm -U elasticsearch-5.2.2.rpm 
warning: elasticsearch-5.2.2.rpm: Header V4 RSA/SHA512 Signature, key ID d88e42b4: NOKEY
centos-7:/home/vagrant$ grep "\(debug\|info\)" /etc/elasticsearch/log4j2.properties
# log action execution errors for easier debugging
logger.action.level = debug
rootLogger.level = debug
centos-7:/home/vagrant$ rpm -U elasticsearch-5.3.0.rpm 
warning: elasticsearch-5.3.0.rpm: Header V4 RSA/SHA512 Signature, key ID d88e42b4: NOKEY
warning: /etc/elasticsearch/log4j2.properties created as /etc/elasticsearch/log4j2.properties.rpmnew
centos-7:/home/vagrant$ grep "\(debug\|info\)" /etc/elasticsearch/log4j2.properties
# log action execution errors for easier debugging
logger.action.level = debug
rootLogger.level = debug
centos-7:/home/vagrant$ grep "\(debug\|info\)" /etc/elasticsearch/log4j2.properties.rpmnew 
# log action execution errors for easier debugging
logger.action.level = debug
rootLogger.level = info
```

Ubuntu 14.04:

```
ubuntu-1404:/home/vagrant$ dpkg -i elasticsearch-5.2.1.deb 
Selecting previously unselected package elasticsearch.
(Reading database ... 145976 files and directories currently installed.)
Preparing to unpack elasticsearch-5.2.1.deb ...
Creating elasticsearch group... OK
Creating elasticsearch user... OK
Unpacking elasticsearch (5.2.1) ...
Setting up elasticsearch (5.2.1) ...
Processing triggers for ureadahead (0.100.0-16) ...
ureadahead will be reprofiled on next reboot
ubuntu-1404:/home/vagrant$ grep "\(debug\|info\)" /etc/elasticsearch/log4j2.properties
# log action execution errors for easier debugging
logger.action.level = debug
rootLogger.level = info
ubuntu-1404:/home/vagrant$ perl -p -i -e 's/info/debug/g' /etc/elasticsearch/log4j2.properties
ubuntu-1404:/home/vagrant$ grep "\(debug\|info\)" /etc/elasticsearch/log4j2.properties
# log action execution errors for easier debugging
logger.action.level = debug
rootLogger.level = debug
ubuntu-1404:/home/vagrant$ dpkg -i elasticsearch-5.2.2.deb 
(Reading database ... 146101 files and directories currently installed.)
Preparing to unpack elasticsearch-5.2.2.deb ...
Unpacking elasticsearch (5.2.2) over (5.2.1) ...
Setting up elasticsearch (5.2.2) ...
Installing new version of config file /usr/lib/systemd/system/elasticsearch.service ...
Processing triggers for ureadahead (0.100.0-16) ...
ubuntu-1404:/home/vagrant$ grep "\(debug\|info\)" /etc/elasticsearch/log4j2.properties
# log action execution errors for easier debugging
logger.action.level = debug
rootLogger.level = debug
ubuntu-1404:/home/vagrant$ dpkg -i elasticsearch-5.3.0.deb 
(Reading database ... 146101 files and directories currently installed.)
Preparing to unpack elasticsearch-5.3.0.deb ...
Unpacking elasticsearch (5.3.0) over (5.2.2) ...
Setting up elasticsearch (5.3.0) ...
Installing new version of config file /etc/elasticsearch/jvm.options ...

Configuration file '/etc/elasticsearch/log4j2.properties'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** log4j2.properties (Y/I/N/O/D/Z) [default=N] ? N
Installing new version of config file /usr/lib/systemd/system/elasticsearch.service ...
Processing triggers for ureadahead (0.100.0-16) ...
ubuntu-1404:/home/vagrant$ grep "\(debug\|info\)" /etc/elasticsearch/log4j2.properties
# log action execution errors for easier debugging
logger.action.level = debug
rootLogger.level = debug
ubuntu-1404:/home/vagrant$ grep "\(debug\|info\)" /etc/elasticsearch/log4j2.properties.dpkg-dist 
# log action execution errors for easier debugging
logger.action.level = debug
rootLogger.level = info
```

Ubuntu 16.04:

```
ubuntu-1604:/home/vagrant$ dpkg -i elasticsearch-5.2.1.deb 
Selecting previously unselected package elasticsearch.
(Reading database ... 117778 files and directories currently installed.)
Preparing to unpack elasticsearch-5.2.1.deb ...
Creating elasticsearch group... OK
Creating elasticsearch user... OK
Unpacking elasticsearch (5.2.1) ...
Setting up elasticsearch (5.2.1) ...
Processing triggers for systemd (229-4ubuntu16) ...
Processing triggers for ureadahead (0.100.0-19) ...
ubuntu-1604:/home/vagrant$ grep "\(debug\|info\)" /etc/elasticsearch/log4j2.properties
# log action execution errors for easier debugging
logger.action.level = debug
rootLogger.level = info
ubuntu-1604:/home/vagrant$ perl -p -i -e 's/info/debug/g' /etc/elasticsearch/log4j2.properties
ubuntu-1604:/home/vagrant$ grep "\(debug\|info\)" /etc/elasticsearch/log4j2.properties
# log action execution errors for easier debugging
logger.action.level = debug
rootLogger.level = debug
ubuntu-1604:/home/vagrant$ dpkg -i elasticsearch-5.2.2.deb 
(Reading database ... 117903 files and directories currently installed.)
Preparing to unpack elasticsearch-5.2.2.deb ...
Unpacking elasticsearch (5.2.2) over (5.2.1) ...
Setting up elasticsearch (5.2.2) ...
Installing new version of config file /usr/lib/systemd/system/elasticsearch.service ...
Processing triggers for systemd (229-4ubuntu16) ...
Processing triggers for ureadahead (0.100.0-19) ...
ubuntu-1604:/home/vagrant$ grep "\(debug\|info\)" /etc/elasticsearch/log4j2.properties
# log action execution errors for easier debugging
logger.action.level = debug
rootLogger.level = debug
ubuntu-1604:/home/vagrant$ dpkg -i elasticsearch-5.3.0.deb 
(Reading database ... 117903 files and directories currently installed.)
Preparing to unpack elasticsearch-5.3.0.deb ...
Unpacking elasticsearch (5.3.0) over (5.2.2) ...
Setting up elasticsearch (5.3.0) ...
Installing new version of config file /etc/elasticsearch/jvm.options ...

Configuration file '/etc/elasticsearch/log4j2.properties'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** log4j2.properties (Y/I/N/O/D/Z) [default=N] ? N
Installing new version of config file /usr/lib/systemd/system/elasticsearch.service ...
Processing triggers for systemd (229-4ubuntu16) ...
Processing triggers for ureadahead (0.100.0-19) ...
ubuntu-1604:/home/vagrant$ grep "\(debug\|info\)" /etc/elasticsearch/log4j2.properties
# log action execution errors for easier debugging
logger.action.level = debug
rootLogger.level = debug
ubuntu-1604:/home/vagrant$ grep "\(debug\|info\)" /etc/elasticsearch/log4j2.properties.dpkg-dist 
# log action execution errors for easier debugging
logger.action.level = debug
rootLogger.level = info
```

**Comment by jasontedor** [comment] 2017-04-15 12:49
@seang-es We will need more details including a reproduction to further triage this one.

**Comment by jasontedor** [comment] 2017-04-26 02:44
No additional feedback, closing.

**Closed by jasontedor** 2017-04-26 02:44 UTC
Labels: :Packaging, feedback_needed
