### ISSUE TITLE
Alternate Store Implementation for _source field

### ISSUE THREAD

**Issue by amitpl** [elastic/elasticsearch#49687] opened 2019-11-28 15:43 UTC
Currently, the `_source` field is stored as a compressed JSON. However, there are better storage formats available (such as avro, parquet, orc etc).
Is there any way for us to plug any alternate storage handler?

**Comment by matriv** [comment] 2019-11-28 16:44
@amitpl Closing this as a duplicate of #9034. Please upvote and/or add comments there.

**Closed by matriv** 2019-11-28 16:44 UTC
