### ISSUE TITLE
_analyze with min_hash filter returns invalid JSON

### ISSUE THREAD

**Issue by Kukunin** [elastic/elasticsearch#41556] opened 2019-04-25 21:35 UTC
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 6.6.1, Build: oss/tar/1fd8f69/2019-02-13T17:10:04.160291Z, JVM: 1.8.0_202

**Plugins installed**: []

**JVM version** (`java -version`):
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
macOS Mojave 10.14.2

**Description of the problem including expected versus actual behavior**:
Background: I need to find near-duplicate documents from my index. I saw that Elasticsearch contains `min_hash` filter that is suitable for this. Because I didn't find a way to find all duplicated documents I decided to do the clustering on the Postgres side while keeping ES to generate `min_hash` set (don't want to re-implement it).

In order to get a configured `min_hash` set for a text, I use `GET /articles/_analyze` query:

```json
{
  "text": "my cool phrases somebody here",
  "analyzer": "minhash_analyzer"
}
```

and it returns to me something like:

```json
{
  "tokens": [
    {
      "token": "瞅䅿磯뎛怉瘡䯿꣪",
      "start_offset": 0,
      "end_offset": 29,
      "type": "MIN_HASH",
      "position": 0
    },
    {
      "token": "瞅䅿磯뎛怉瘡䯿꣪",
      "start_offset": 0,
      "end_offset": 29,
      "type": "MIN_HASH",
      "position": 0
    },
    {
      "token": "瞅䅿磯뎛怉瘡䯿꣪",
      "start_offset": 0,
      "end_offset": 29,
      "type": "MIN_HASH",
      "position": 0
    }
  ]
}
```

As you can see, tokens are raw binary, which may break JSON. 
Out of 100 random texts, 12 generated broken JSON for me.

It raises the following exception in Ruby:

    MultiJson::ParseError:
      468: incomplete surrogate pair at '陘㖒ꗖ抦ㅵᶚ\uD8BD","start_offset":0,"end_offset":54,"type":"MIN_HASH","position":0},{"token":"陘㖒ꗖ抦ㅵᶚ\uD8BD","start_offset":0,"end_offset":54,"type":"MIN_HASH","position":0},{"token":"샥鯛䲥짭᜛佪逮","start_offset":0,"end_offset":54,"type":"MIN_HASH","position":0},{"token":"샥鯛䲥짭᜛佪逮","start_offset":0,"end_offset":54,"type":"MIN_HASH","position":0},{"token":"샥鯛䲥짭᜛佪逮","start_offset":0,"end_offset":54,"type":"MIN_HASH","position":0},{"token":"샥鯛䲥짭᜛佪逮","start_offset":0,"end_offset":54,"type":"MIN_HASH","position":0},{"token":"샥鯛䲥짭᜛佪逮","start_offset":0,"end_offset":54,"type":"MIN_HASH","position":0},{"token":"샥鯛䲥짭᜛佪逮","start_offset":0,"end_offset":54,"type":"MIN_HASH","position":0},{"token":"⺩귏쇀ⰹ㱭돎ﾝ❦","start_offset":0,"end_offset":54,"type":"MIN_HASH","position":0},{"token":"⺩귏쇀ⰹ㱭돎ﾝ❦","start_offset":0,"end_offset":54,"type":"MIN_HASH","position":0},{"token":"⺩귏쇀ⰹ㱭돎ﾝ❦","start_offset":0,"end_offset":54,"type":"MIN_HASH","position":0},{"token":"⺩귏쇀ⰹ㱭돎ﾝ❦","start_offset":0,"end_offset":54,"type":"MIN_HASH","position":0},{"token":"⺩귏쇀ⰹ㱭돎ﾝ❦","start_offset":0,"end_offset":54,"type":"MIN_HASH","position":0},{"token":"⺩귏쇀ⰹ㱭돎ﾝ❦","start_offset":0,"end_offset":54,"type":"MIN_HASH","position":0},{"token":"⺩귏쇀ⰹ㱭돎ﾝ❦","start_offset":0,"end_offset":54,"type":"MIN_HASH","position":0}]}'

Didn't find a way to escape it (render as hex or base64).

**Steps to reproduce**:

My mapping:

```json
{  
   "filter":{  
      "shingle_filter":{  
         "type":"shingle",
         "min_shingle_size":5,
         "max_shingle_size":5,
         "output_unigrams":false
      },
      "minhash_filter":{  
         "type":"min_hash",
         "hash_count":1,
         "bucket_count":32,
         "hash_set_size":1,
         "with_rotation":true
      }
   },
   "analyzer":{  
      "minhash_analyzer":{  
         "tokenizer":"whitespace",
         "char_filter":[  
            "html_strip"
         ],
         "filter":[  
            "shingle_filter",
            "minhash_filter"
         ]
      }
   }
}
```

My request:

`GET http://localhost:9200/articles_test/_analyze`

```json
{
  "text": "Ugh goth offal small batch kickstarter ramps leggings.",
  "analyzer": "minhash_analyzer"
}
```

**Comment by jpountz** [comment] 2019-04-26 07:34
Thanks for reporting. This issue is caused by the fact that the analyze API expects terms to be text, but the `minhash` filter is abusing the API by recording the hash bits into characters of a term without trying to make it valid unicode.

**Comment by jpountz** [comment] 2019-04-26 07:40
I'm closing in favor of https://issues.apache.org/jira/browse/LUCENE-8779 since this is a Lucene issue.

**Closed by jpountz** 2019-04-26 07:40 UTC
Labels: :Search/Analysis, >bug
