### ISSUE TITLE
scaled_float does not work in dynamic templates across multiple types

### ISSUE THREAD

**Issue by travisp** [elastic/elasticsearch#26674] opened 2017-09-15 21:03 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 5.4 through 5.6

**Description of the problem including expected versus actual behavior**:

When creating a default dynamic template that uses `scaled_float` and setting a `scaling_factor`, the mapping will be successfully applied to the first type that Elasticsearch encounters. When encountering a second type, with field names of the same type, Elasticsearch gives the following error `Field [X] misses required parameter [scaling_factor]`

The same issue was reported by another user in April in the Elasticsearch mailing list: https://discuss.elastic.co/t/mapper-parsing-exception-when-creating-the-same-document-with-different-type/82987

**Steps to reproduce**:

1. Create two dynamic templates for different types, with the same name and both with type scaled_float and a scaling_factor.
2. Index into the first type, then index into the second type (it will fail)

Alternatively:
1. Create one _default_ dynamic template with scaled_float type and scaling_factor set
2. Index into one type with a field that'll match the dynamic template
3. Index into a second type with the same field name that'll match the dynamic template (this will fail)

Reproduction inside Elasticsearch unit tests:

test-mapping_any.json :
```json
{
    "dynamic_templates":[
        {
            "scaled_float_template":{
                "match":"incoming_integer",
                "mapping":{
                    "type":"scaled_float",
                    "scaling_factor":1000
                }
            }
        }
    ]
}
```

test-data.json :
```json
{
    "name":"some name",
    "incoming_integer": 54
}
```

```java
   // DynamicTemplatesTests (probably not the best place, but it works)
    public void testScaledFloatDynamic() throws Exception {
        String mapping = copyToStringFromClasspath("/org/elasticsearch/index/mapper/dynamictemplate/scaled_float/test-mapping_any.json");
        client().admin().indices().prepareCreate("test").addMapping("transaction_one", mapping)
            .addMapping("transaction_two", mapping).get();

        String data = copyToStringFromClasspath("/org/elasticsearch/index/mapper/dynamictemplate/scaled_float/test-data.json");

        BulkResponse response = client().prepareBulk().add(new IndexRequest("test", "transaction_one", "1").source(data, XContentType.JSON)).get();
        assertThat(response.hasFailures(), is(false));
        assertThat(response.getItems()[0].isFailed(), equalTo(false));

        GetMappingsResponse mappingResponse = client().admin().indices().prepareGetMappings("test").get();

        response = client().prepareBulk().add(new IndexRequest("test", "transaction_two", "1").source(data, XContentType.JSON)).get();
        assertThat(response.hasFailures(), is(false)); 
        assertThat(response.getItems()[0].isFailed(), equalTo(false));
    }
```

The second request fails with "Field [incoming_integer] misses required parameter [scaling_factor]"

The mapping for `transaction_one`, in the mappingResponse variable is:
```
{"transaction_one":{"dynamic_templates":[{"scaled_float_template":{"match":"incoming_integer","mapping":{"scaling_factor":1000,"type":"scaled_float"}}}],"properties":{"incoming_integer":{"type":"scaled_float","scaling_factor":1000.0},"name":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}}}}}
```

The mapping for `transaction_two`, in the mappingResponse variable is:
```
{"transaction_two":{"dynamic_templates":[{"scaled_float_template":{"match":"incoming_integer","mapping":{"scaling_factor":1000,"type":"scaled_float"}}}]}}
```

You can see that the dynamic templates are identical, and both have a scaling_factor, but the insert into the second type always fails with a complaint about "scaling_factor"

Update:

I don't know the internals of Elasticsearch well, but it looks like the problem is that because mappings actually have to be the same between types, the code fails to apply the scaling_factor to the second type after the first was created. In the method `org.elasticsearch.index.mapper.DocumentParser.createBuilderFromFieldType`, it passes in no information into the new builder about scaling factor.

The example failing test passes if the `createBuilderFromFieldType` method is updated to include the following elseif statement:

```
        } else if (fieldType instanceof ScaledFloatFieldMapper.ScaledFloatFieldType) {
            builder = new ScaledFloatFieldMapper.Builder(currentFieldName).scalingFactor(
                ((ScaledFloatFieldMapper.ScaledFloatFieldType) fieldType).getScalingFactor()
            );
```

**Comment by travisp** [comment] 2017-09-17 02:34
I don't know the internals of Elasticsearch well, but it looks like the problem is that because mappings actually have to be the same between types, the code fails to apply the scaling_factor to the second type after the first was created in `org.elasticsearch.index.mapper.DocumentParser.createBuilderFromFieldType`

The example failing test passes if the method is updated to include the following elseif statement:

```
        } else if (fieldType instanceof ScaledFloatFieldMapper.ScaledFloatFieldType) {
            builder = new ScaledFloatFieldMapper.Builder(currentFieldName).scalingFactor(
                ((ScaledFloatFieldMapper.ScaledFloatFieldType) fieldType).getScalingFactor()
            );
```

**Comment by danielmitterdorfer** [comment] 2017-09-18 08:18
@travisp thanks for the detailed report and reproduction scenario! @jpountz could you please have a look at this one?

**Comment by jpountz** [comment] 2017-09-25 14:32
This is "interesting" since we recently moved some mappers including `scaled_float` to a module in order to avoid introducing dependencies between the mapping API and specific implementations while this bug would require such a dependency to be fixed.

For the record, this bug only exists in multi-type setups so it can't affect 6.0+ indices, which disallow the use of multiple types.

Maybe we could fix it without a compile-time dependency on `ScaledFloatFieldMapper` by adding a case to the switch statement that would do something like that:

```java
            case "scaled_float": // this is the only added line, below is handling for double, which scaled_float can share
            case "double":
                builder = context.root().findTemplateBuilder(context, currentFieldName, "double", XContentFieldType.DOUBLE);
                break;
```

This way it should at least work in the case that the field is defined in templates.

**Comment by jpountz** [comment] 2018-01-24 13:50
I am leaning towards making it a "won't fix" since it is easy to work around and no longer an issue in 6.0 due to the fact indices can have at most one type.

**Comment by travisp** [comment] 2018-02-16 16:30
I understand if it's chosen to not fix -- but I know that we, and probably others, aren't able to update to 6 right away because of the breaking changes. And dealing with this bug with scaled_float is also a big pain point as there's no work around other than not using dynamic templates.

**Comment by javanna** [comment] 2018-03-16 10:48
@elastic/es-search-aggs

**Comment by jpountz** [comment] 2019-02-18 14:27
I'm going to close it now that multiple types per index is not supported anymore.

**Closed by jpountz** 2019-02-18 14:27 UTC
Labels: :Search/Mapping, >bug
