### ISSUE TITLE
SnapshotShardsServiceIT#testRetryPostingSnapshotStatusMessages fails on 6.4

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#33199] opened 2018-08-28 11:33 UTC
`SnapshotShardsServiceIT#testRetryPostingSnapshotStatusMessages` failed twice in the last week or so on 6.4:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.4+matrix-java-periodic/ES_BUILD_JAVA=java10,ES_RUNTIME_JAVA=java10,nodes=virtual&&linux/49/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.4+periodic/189/console

I was not able to reproduce this.

```
REPRODUCE WITH: ./gradlew :server:integTest -Dtests.seed=C6E187BCF23E9A64 -Dtests.class=org.elasticsearch.snapshots.SnapshotShardsServiceIT -Dtests.method="testRetryPostingSnapshotStatusMessages" -Dtests.security.manager=true -Dtests.locale=en-NZ -Dtests.timezone=Europe/Athens
```

```
22:01:34 ERROR   1.99s J2 | SnapshotShardsServiceIT.testRetryPostingSnapshotStatusMessages <<< FAILURES!
22:01:34    > Throwable #1: NotSerializableExceptionWrapper[not_x_content_exception: Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes]
22:01:34    > 	at __randomizedtesting.SeedInfo.seed([8D7F690C8A92F95A:D5E6E7CCFFF0DBA8]:0)
22:01:34    > 	at org.elasticsearch.common.compress.CompressorFactory.compressor(CompressorFactory.java:56)
22:01:34    > 	at org.elasticsearch.common.xcontent.XContentHelper.createParser(XContentHelper.java:69)
22:01:34    > 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getRepositoryData(BlobStoreRepository.java:671)
22:01:34    > 	at org.elasticsearch.snapshots.SnapshotsService.getRepositoryData(SnapshotsService.java:139)
22:01:34    > 	at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:97)
22:01:34    > 	at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:55)
22:01:34    > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:88)
22:01:34    > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.doRun(TransportMasterNodeAction.java:174)
22:01:34    > 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723)
22:01:34    > 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
22:01:34    > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
22:01:34    > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
22:01:34    > 	at java.lang.Thread.run(Thread.java:844)
```

**Comment by s1monw** [comment] 2018-08-30 15:04
@imotov I feel like you are the only one who can shed some light on this? It seems we fail with and exception [here ](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java#L670) but the issue is that the file is there but is empty ie. has length of `0`. Now further [down](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java#L701) we have some special logic that if the file is not there we exit normally. Is it possible that we have a race condition where the file is there but not written fully?  Like with FSRepository this seems to be an issue [here](https://github.com/elastic/elasticsearch/blob/2bb4f3837113952488a9c71773107b024b756d14/server/src/main/java/org/elasticsearch/common/blobstore/fs/FsBlobContainer.java#L132-L134)?

**Comment by s1monw** [comment] 2018-08-30 15:05
I assigned it to you to make sure it's been taken care of. Feel free to pass it on if needed.

**Comment by DaveCTurner** [comment] 2018-08-30 15:37
I see three calls to `writeBlob` that I think should be `writeBlobAtomic`:

https://github.com/elastic/elasticsearch/blob/2bb4f3837113952488a9c71773107b024b756d14/server/src/main/java/org/elasticsearch/repositories/blobstore/ChecksumBlobStoreFormat.java#L153

https://github.com/elastic/elasticsearch/blob/f4e9729d647add3d42b5bdd091278dcb3af727af/server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java#L889

https://github.com/elastic/elasticsearch/blob/f4e9729d647add3d42b5bdd091278dcb3af727af/server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java#L1328

More generally, I'm wondering if we need to distinguish `writeBlob` from `writeBlobAtomic` at the `BlobContainer` level, or whether we can just have one method that always writes atomically everywhere? The temp-file-and-rename dance feels more like an implementation detail of `FsBlobContainer` than something that needs to be available to all the repos, and I can't actually see any cases where we want the write to happen non-atomically.

**Comment by DaveCTurner** [comment] 2018-09-10 07:12
Pinging @tlrx about this too.

**Comment by ywelsch** [comment] 2019-01-22 18:39
Duplicates #37005

**Closed by ywelsch** 2019-01-22 18:39 UTC
Labels: :Distributed/Snapshot/Restore, >test-failure
