### ISSUE TITLE
JSON logging with discovery-ec2 plugin

### ISSUE THREAD

**Issue by alex-voigt** [elastic/elasticsearch#23382] opened 2017-02-27 12:57 UTC
**Elasticsearch version**: 5.1.2

**Plugins installed**: [discovery-ec2]

**JVM version**: 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13

**OS version**: Ubuntu 16.04

**Description of the problem including expected versus actual behavior**:

I am using a log4j2 log file configuration for logging to JSON format on a devbox.

To make this work I had to put a copy of the `jackson-databind-2.8.1.jar` and `jackson-annotations-2.8.1.jar` into the `/usr/share/elasticsearch/lib` folder. Works perfectly fine.

But our production system runs on AWS and requires additionally the `discovery-ec2` plugin. In combination it doesn't work because I am ending in up in the 'jar hell'.

`java.lang.IllegalStateException: failed to load bundle [file:/usr/share/elasticsearch/plugins/discovery-ec2/httpcore-4.4.5.jar, file:/usr/share/elasticsearch/plugins/discovery-ec2/discovery-ec2-5.1.2.jar, file:/usr/share/elasticsearch/plugins/discovery-ec2/aws-java-sdk-core-1.10.69.jar, file:/usr/share/elasticsearch/plugins/discovery-ec2/commons-logging-1.1.3.jar, file:/usr/share/elasticsearch/plugins/discovery-ec2/commons-codec-1.10.jar, file:/usr/share/elasticsearch/plugins/discovery-ec2/aws-java-sdk-ec2-1.10.69.jar, file:/usr/share/elasticsearch/plugins/discovery-ec2/httpclient-4.5.2.jar, file:/usr/share/elasticsearch/plugins/discovery-ec2/jackson-databind-2.5.3.jar, file:/usr/share/elasticsearch/plugins/discovery-ec2/jackson-annotations-2.5.0.jar] due to jar hell
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:327) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:132) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.node.Node.<init>(Node.java:294) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.node.Node.<init>(Node.java:229) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:214) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:214) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:306) [elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) [elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) [elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) [elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) [elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.cli.Command.main(Command.java:88) [elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89) [elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82) [elasticsearch-5.1.2.jar:5.1.2]
Caused by: java.lang.IllegalStateException: jar hell!
class: com.fasterxml.jackson.databind.AbstractTypeResolver
jar1: /usr/share/elasticsearch/lib/jackson-databind-2.8.1.jar
jar2: /usr/share/elasticsearch/plugins/discovery-ec2/jackson-databind-2.5.3.jar
	at org.elasticsearch.bootstrap.JarHell.checkClass(JarHell.java:277) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:187) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:325) ~[elasticsearch-5.1.2.jar:5.1.2]
	... 13 more
[2017-02-27T12:09:14,988][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to load bundle [file:/usr/share/elasticsearch/plugins/discovery-ec2/httpcore-4.4.5.jar, file:/usr/share/elasticsearch/plugins/discovery-ec2/discovery-ec2-5.1.2.jar, file:/usr/share/elasticsearch/plugins/discovery-ec2/aws-java-sdk-core-1.10.69.jar, file:/usr/share/elasticsearch/plugins/discovery-ec2/commons-logging-1.1.3.jar, file:/usr/share/elasticsearch/plugins/discovery-ec2/commons-codec-1.10.jar, file:/usr/share/elasticsearch/plugins/discovery-ec2/aws-java-sdk-ec2-1.10.69.jar, file:/usr/share/elasticsearch/plugins/discovery-ec2/httpclient-4.5.2.jar, file:/usr/share/elasticsearch/plugins/discovery-ec2/jackson-databind-2.5.3.jar, file:/usr/share/elasticsearch/plugins/discovery-ec2/jackson-annotations-2.5.0.jar] due to jar hell
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82) ~[elasticsearch-5.1.2.jar:5.1.2]
Caused by: java.lang.IllegalStateException: failed to load bundle [file:/usr/share/elasticsearch/plugins/discovery-ec2/httpcore-4.4.5.jar, file:/usr/share/elasticsearch/plugins/discovery-ec2/discovery-ec2-5.1.2.jar, file:/usr/share/elasticsearch/plugins/discovery-ec2/aws-java-sdk-core-1.10.69.jar, file:/usr/share/elasticsearch/plugins/discovery-ec2/commons-logging-1.1.3.jar, file:/usr/share/elasticsearch/plugins/discovery-ec2/commons-codec-1.10.jar, file:/usr/share/elasticsearch/plugins/discovery-ec2/aws-java-sdk-ec2-1.10.69.jar, file:/usr/share/elasticsearch/plugins/discovery-ec2/httpclient-4.5.2.jar, file:/usr/share/elasticsearch/plugins/discovery-ec2/jackson-databind-2.5.3.jar, file:/usr/share/elasticsearch/plugins/discovery-ec2/jackson-annotations-2.5.0.jar] due to jar hell
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:327) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:132) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.node.Node.<init>(Node.java:294) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.node.Node.<init>(Node.java:229) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:214) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:214) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:306) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-5.1.2.jar:5.1.2]
	... 6 more
Caused by: java.lang.IllegalStateException: jar hell!
class: com.fasterxml.jackson.databind.AbstractTypeResolver
jar1: /usr/share/elasticsearch/lib/jackson-databind-2.8.1.jar
jar2: /usr/share/elasticsearch/plugins/discovery-ec2/jackson-databind-2.5.3.jar
	at org.elasticsearch.bootstrap.JarHell.checkClass(JarHell.java:277) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:187) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:325) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:132) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.node.Node.<init>(Node.java:294) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.node.Node.<init>(Node.java:229) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:214) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:214) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:306) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-5.1.2.jar:5.1.2]
	... 6 more`

When I remove those files out of the `/usr/share/elasticsearch/lib` again the syslog contains the following lines and logging in JSON format does not work anymore:

`Feb 27 12:45:26 project-search systemd[1]: Started Elasticsearch.
Feb 27 12:45:27 project-search elasticsearch[9703]: 2017-02-27 12:45:27,055 main ERROR Unable to invoke factory method in class class org.apache.logging.log4j.core.layout.JsonLayout for element JSONLayout. java.lang.reflect.InvocationTargetException
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at java.lang.reflect.Method.invoke(Method.java:498)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:132)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:942)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:882)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:874)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:874)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:498)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:227)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:239)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:530)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:258)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:116)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:83)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:272)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.cli.Command.main(Command.java:88)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82)
Feb 27 12:45:27 project-search elasticsearch[9703]: Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ser/FilterProvider
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.layout.JsonLayout.<init>(JsonLayout.java:814)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.layout.JsonLayout.createLayout(JsonLayout.java:922)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011... 24 more
Feb 27 12:45:27 project-search elasticsearch[9703]: Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ser.FilterProvider
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011... 26 more
Feb 27 12:45:27 project-search elasticsearch[9703]: 2017-02-27 12:45:27,133 main ERROR Unable to invoke factory method in class class org.apache.logging.log4j.core.layout.JsonLayout for element JSONLayout. java.lang.reflect.InvocationTargetException
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at java.lang.reflect.Method.invoke(Method.java:498)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:132)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:942)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:882)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:874)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:874)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:498)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:227)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:239)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:530)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:258)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:116)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:83)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:272)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.cli.Command.main(Command.java:88)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82)
Feb 27 12:45:27 project-search elasticsearch[9703]: Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ser/FilterProvider
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.layout.JsonLayout.<init>(JsonLayout.java:814)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.layout.JsonLayout.createLayout(JsonLayout.java:922)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011... 24 more
Feb 27 12:45:27 project-search elasticsearch[9703]: Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ser.FilterProvider
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011... 26 more
Feb 27 12:45:27 project-search elasticsearch[9703]: 2017-02-27 12:45:27,140 main ERROR Unable to invoke factory method in class class org.apache.logging.log4j.core.layout.JsonLayout for element JSONLayout. java.lang.reflect.InvocationTargetException
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at java.lang.reflect.Method.invoke(Method.java:498)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:132)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:942)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:882)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:874)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:874)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:498)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:227)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:239)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:530)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:258)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:116)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:83)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:272)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.cli.Command.main(Command.java:88)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82)
Feb 27 12:45:27 project-search elasticsearch[9703]: Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ser/FilterProvider
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.layout.JsonLayout.<init>(JsonLayout.java:814)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.layout.JsonLayout.createLayout(JsonLayout.java:922)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011... 24 more
Feb 27 12:45:27 project-search elasticsearch[9703]: Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ser.FilterProvider
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011... 26 more
Feb 27 12:45:27 project-search elasticsearch[9703]: 2017-02-27 12:45:27,158 main ERROR Unable to invoke factory method in class class org.apache.logging.log4j.core.layout.JsonLayout for element JSONLayout. java.lang.reflect.InvocationTargetException
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at java.lang.reflect.Method.invoke(Method.java:498)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:132)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:942)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:882)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:874)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:874)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:498)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:227)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:239)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:530)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:258)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:116)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:83)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:272)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.cli.Command.main(Command.java:88)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82)
Feb 27 12:45:27 project-search elasticsearch[9703]: Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ser/FilterProvider
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.layout.JsonLayout.<init>(JsonLayout.java:814)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at org.apache.logging.log4j.core.layout.JsonLayout.createLayout(JsonLayout.java:922)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011... 24 more
Feb 27 12:45:27 project-search elasticsearch[9703]: Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ser.FilterProvider
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Feb 27 12:45:27 project-search elasticsearch[9703]: #011... 26 more`

Is there any way to get out of the jar hell with JSON logging and discovery plugin enabled? For me it looks like a bug in the Plugin because dependencies seem to influence the ES behaviour.

**Comment by jasontedor** [comment] 2018-03-14 01:16
Supporting structured logging (out of which meaningfully logging to JSON trivially falls out) is something that is on our roadmap but is not actively being worked on. Closing this as a duplicate of #8786.

**Closed by jasontedor** 2018-03-14 01:16 UTC
Labels: :Core/Core, discuss
