### ISSUE TITLE
Bulk API does not accept charset with application/x-ndjson in Content-Type header

### ISSUE THREAD

**Issue by mieciu** [elastic/elasticsearch#61637] opened 2020-08-27 14:29 UTC
**Elasticsearch version** (`bin/elasticsearch --version`):
```
Version: 6.8.13-SNAPSHOT, Build: default/tar/37825c3/2020-08-26T14:42:26.771178Z, JVM: 1.8.0_262
```

**JVM version** (`java -version`):
```
openjdk version "1.8.0_262"
OpenJDK Runtime Environment (build 1.8.0_262-b10)
OpenJDK 64-Bit Server VM (build 25.262-b10, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system):
```
Linux ce0caf533cff 4.15.0-1066-aws #70-Ubuntu SMP Wed Apr 8 16:10:41 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Description of the problem including expected versus actual behavior**:

Trying to index data via `/_bulk` API with the `Content-Type: application/x-ndjson; charset=ISO-8859-1` header results in the `406` error:
```
{"error":"Content-Type header [application/x-ndjson; charset=ISO-8859-1] is not supported","status":406}
```

To have this working I can either strip the `charset` part **OR** use `Content-Type: application/json; charset=ISO-8859-1` which is technically incorrect, because my payload **is truly ndjson**:
```
PUT /_bulk HTTP/1.1
Authorization: Basic <TOKEN>
Accept: */*
Content-Type: application/x-ndjson; charset=ISO-8859-1
Content-Length: 1595845
Host: 127.0.0.1:5000
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.10 (Java/1.8.0_252)
Accept-Encoding: gzip,deflate

{"index":{"_index":"test-ml","_type":"_doc"}}
{"@timestamp":1595938329181,"accept":285308,"deny":2173,"host":"server_1","response":3.526092,"service":"app_3"}
{"index":{"_index":"test-ml","_type":"_doc"}}
{"@timestamp":1595938389181,"accept":178321,"deny":2717,"host":"server_1","response":3.2162445,"service":"app_3"}
[...]
```

Documentation for `6.8` clearly states the need for `application/x-ndjson` header though (ref: https://www.elastic.co/guide/en/elasticsearch/reference/6.8/docs-bulk.html). 

**When testing on `7.9` everything works fine**, `Content-Type: application/x-ndjson; charset=ISO-8859-1` header is accepted and data is being loaded without any issues. This PR could be related https://github.com/elastic/elasticsearch/pull/45130/files.

**Steps to reproduce**:

Full instruction below:
<details>

1) Create index
```
HOST_URL=https://my-host.my-domain.com:9243
BASIC_AUTH=elastic:<PASS>

curl -k  -H 'Content-Type: application/json' -u ${BASIC_AUTH} -XPUT ${HOST_URL}/test-ml2 -d '
{
    "mappings": {
    "_doc" : {
        "properties": {
          "@timestamp": {
            "type": "date"
          },
          "accept": {
            "type": "long"
          },
          "deny": {
            "type": "long"
          },
          "host": {
            "type": "keyword"
          },
          "response": {
            "type": "float"
          },
          "service": {
            "type": "keyword"
          },
          "total": {
            "type": "long"
          }
        }
      }
    }
}
'
```

2) Index data with `application/x-ndjson` - **IT WILL FAIL WITH 406**
```
curl -k  -H 'Content-Type: application/x-ndjson; charset=ISO-8859-1' -u ${BASIC_AUTH} -XPUT ${HOST_URL}/_bulk --data-binary '
{"index":{"_index":"test-ml2","_type":"_doc"}}
{"@timestamp":1595855011420,"accept":244647,"deny":79,"host":"server_1","response":0.40575957,"service":"app_3"}
{"index":{"_index":"test-ml2","_type":"_doc"}}
{"@timestamp":1595855071420,"accept":483733,"deny":391,"host":"server_1","response":2.5463665,"service":"app_3"}
{"index":{"_index":"test-ml2","_type":"_doc"}}
{"@timestamp":1595855131420,"accept":231359,"deny":4609,"host":"server_1","response":2.2355824,"service":"app_3"}
{"index":{"_index":"test-ml2","_type":"_doc"}}
{"@timestamp":1595855191420,"accept":272323,"deny":4106,"host":"server_1","response":3.9306116,"service":"app_3"}
'
```
3) Index data with `application/json` - it will succeed, but that's not what docs recommend doing:
```
curl -k  -H 'Content-Type: application/json; charset=ISO-8859-1' -u ${BASIC_AUTH} -XPUT ${HOST_URL}/_bulk --data-binary '
{"index":{"_index":"test-ml2","_type":"_doc"}}
{"@timestamp":1595855011420,"accept":244647,"deny":79,"host":"server_1","response":0.40575957,"service":"app_3"}
{"index":{"_index":"test-ml2","_type":"_doc"}}
{"@timestamp":1595855071420,"accept":483733,"deny":391,"host":"server_1","response":2.5463665,"service":"app_3"}
{"index":{"_index":"test-ml2","_type":"_doc"}}
{"@timestamp":1595855131420,"accept":231359,"deny":4609,"host":"server_1","response":2.2355824,"service":"app_3"}
{"index":{"_index":"test-ml2","_type":"_doc"}}
{"@timestamp":1595855191420,"accept":272323,"deny":4106,"host":"server_1","response":3.9306116,"service":"app_3"}
'
```
</details>

Note that charset could be `charset=UTF-8`, the value doesn't really matter here (but yes, as @DaveCTurner pointed out JSON should technically be UTF-8 https://tools.ietf.org/html/rfc7159#section-8.1)

**Comment by jaymode** [comment] 2020-08-27 18:16
I am going to close this issue as a duplicate of https://github.com/elastic/elasticsearch/issues/28123. The plan is to ensure we always accept content-types with a proper charset, which will be `UTF-8` only. 

The fact that `application/json` works for bulk and other APIs is an artifact of elasticsearch doing content type auto-detection in the past. There is some long running discussion on deprecation in https://github.com/elastic/elasticsearch/issues/25718

**Closed by jaymode** 2020-08-27 18:16 UTC
Labels: >bug, needs:triage
