### ISSUE TITLE
_nodes/stats returns failed_node_exception if closed indices exist

### ISSUE THREAD

**Issue by marevol** [elastic/elasticsearch#91259] opened 2022-11-02 21:29 UTC
### Elasticsearch Version

8.5.0

### Java Version

_bundled_

### OS Version

Linux 9b4c50a443c1 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

In 8.5, _nodes/stats returns a failure message if the node has closed indices. In previous versions, it works.
Please see steps to reproduce.

### Steps to Reproduce

```
$ curl -XPUT http://localhost:9200/test_index
$ curl http://localhost:9200/_nodes/stats  # <- it works
$ curl -XPOST http://localhost:9200/test_index/_close
$ curl http://localhost:9200/_nodes/stats
{
  "_nodes": {
    "total": 1,
    "successful": 0,
    "failed": 1,
    "failures": [
      {
        "type": "failed_node_exception",
        "reason": "Failed node [...]",
        "node_id": "...",
        "caused_by": {
          "type": "null_pointer_exception",
          "reason": "Cannot invoke \"org.elasticsearch.index.mapper.MapperService.mappingLookup()\" because the return value of \"org.elasticsearch.index.IndexService.mapperService()\" is null"
        }
      }
    ]
  },
  "cluster_name": "...",
  "nodes": {}
}
```

**Comment by gwbrown** [comment] 2022-11-04 21:09
I reproduced this one on an 8.5.0 Cloud cluster using the steps in the issue, looks legit.

**Comment by redbaron4** [comment] 2022-11-17 04:47
+1 I ran into this after upgrading the infrastructure to 8.5 from 8.4.1

I have observed that the API works correctly for few requests after a node restarts but then starts failing with the above message.

Master node API is not affected (probably because it has no closed indices)

**Closed** 2022-11-21 12:31 UTC
Labels: >bug, :Data Management/Stats, Team:Data Management
