### ISSUE TITLE
Elasticsearch fails to startup with valid fsize and virtual memory limits

### ISSUE THREAD

**Issue by nathan-maves** [elastic/elasticsearch#113705] opened 2024-09-27 16:08 UTC
### Elasticsearch Version

8.15

### Java Version

_bundled_

### OS Version

Linux

### Problem Description

We have found a few issues with the Bootstrap checks on Linux/Unix machines.  The first is that a value of `-1` should be accepted along with `unlimited` and `infinity` based on [this](https://man.archlinux.org/man/limits.conf.5) documentation.

```
All items support the values -1, unlimited or infinity indicating no limit, except for priority, nice, and nonewprivs. If nofile is to be set to one of these values, it will be set to the contents of /proc/sys/fs/nr_open instead (see setrlimit(3)).
```

The second issue is that [this code](https://github.com/elastic/elasticsearch/blob/ee24f84df0265f5b8bc0baa3dadde6516cf3c073/server/src/main/java/org/elasticsearch/bootstrap/BootstrapChecks.java#L429-L431) appears to be incorrect.

It should be checking for the max file size and **NOT** the max memory size

```java
long getMaxFileSize() {
    return NativeAccess.instance().getProcessLimits().maxFileSize();
}
```

### Steps to Reproduce

Set the `fsize` value to `-1` in the `/etc/security/limits.conf ` file then start up Elastic 8.15.x.

### Logs (if relevant)

```
[2024-09-25T17:00:39,398][ERROR][o.e.b.Elasticsearch ] [node-f41036c7-370b-4665-a0d0-679e2bedef84] node validation exception
[2] bootstrap checks failed. You must address the points described in the following [2] lines before starting Elasticsearch. For more information see [https://www.elastic.co/guide/en/elasticsearch/reference/8.15/bootstrap-checks.html]
bootstrap check failure [1] of [2]: max size virtual memory [-1] for user [###] is too low, increase to [unlimited]; for more information see [https://www.elastic.co/guide/en/elasticsearch/reference/8.15/max-size-virtual-memory-check.html]
bootstrap check failure [2] of [2]: max file size [-1] for user [###] is too low, increase to [unlimited]; for more information see [https://www.elastic.co/guide/en/elasticsearch/reference/8.15/_max_file_size_check.html]
```

**Comment by prdoyle** [comment] 2024-09-27 17:37
For the second part... `maxVirtualMemorySize` certainly _looks like_ a bug. @rjernst - do you agree it should be calling `maxFileSize`? The code came from [here](https://github.com/elastic/elasticsearch/pull/108805/files#diff-74e8858c06245b31e61aa905326bdc6d4b03c31410c4609a3fa5a35199a02baaR429).

**Comment by prdoyle** [comment] 2024-09-27 17:51
For the first part, I think we want to change [this](https://github.com/elastic/elasticsearch/blob/ee24f84df0265f5b8bc0baa3dadde6516cf3c073/server/src/main/java/org/elasticsearch/bootstrap/BootstrapChecks.java#L416) `Long.MIN_VALUE` to just `-1` like it is [elsewhere](https://github.com/elastic/elasticsearch/blob/ee24f84df0265f5b8bc0baa3dadde6516cf3c073/server/src/main/java/org/elasticsearch/bootstrap/BootstrapChecks.java#L447).

**Comment by prdoyle** [comment] 2024-09-27 18:04
I've changed it to accept both `Long.MIN_VALUE` and `-1`. A [comment in the unit test](https://github.com/elastic/elasticsearch/blob/ee24f84df0265f5b8bc0baa3dadde6516cf3c073/server/src/test/java/org/elasticsearch/bootstrap/BootstrapChecksTests.java#L408) seems to suggest that this value can be `MIN_VALUE` if the size is "not available".

**Comment by nathan-maves** [comment] 2024-09-27 18:39
I think you might want to add the -1 to this check as well.

https://github.com/elastic/elasticsearch/blob/ee24f84df0265f5b8bc0baa3dadde6516cf3c073/server/src/main/java/org/elasticsearch/bootstrap/BootstrapChecks.java#L384

There could be others too.

**Comment by prdoyle** [comment] 2024-09-27 19:30
I believe @rjernst is also looking at this now.

**Comment by prdoyle** [comment] 2024-09-27 19:58
My original -1 fix was incorrect. The code is already supposed to be turning that -1 into `ProcessLimits.UNLIMITED` [here](https://github.com/elastic/elasticsearch/blob/53d8cc35694d2d14596d322878e780ed869610f1/libs/native/src/main/java/org/elasticsearch/nativeaccess/PosixNativeAccess.java#L60) (where `constants.RLIMIT_INFINITY` is defined to be `-1L` by the first parameter [here](https://github.com/elastic/elasticsearch/blob/53d8cc35694d2d14596d322878e780ed869610f1/libs/native/src/main/java/org/elasticsearch/nativeaccess/LinuxNativeAccess.java#L94).

**Comment by prdoyle** [comment] 2024-09-27 20:16
@nathan-maves - what happens if you try to use -1?

**Comment by nathan-maves** [comment] 2024-09-27 20:43
You can see in the logs I added to the issue we already have the system set to `-1`.  So the code is reading in the value of `-1` and telling us that it is too low.

`max file size [-1] for user [collibra] is too low`

**Comment by rjernst** [comment] 2024-09-27 21:19
Are there any other log messages like `unable to retrieve max size virtual memory`? We translate the RLIMIT_INFINITY value for each system into our own (which is represented by MAX_INT). I suspect what is happening here is the rlimit call failed, which then stores our own `UNKNOWN` (-1), but the bootstrap checks aren't currently specializing the error message for that case, so it looks as if -1 was not handled.

**Comment by rjernst** [comment] 2024-09-27 21:22
The issue description mentioneds "Unix" as the OS. Do you mean linux, and if so, what distribution? We do not support any Unix distributions, and I can see how that might be an issue (our rlimit calls are probably not setup right for unix).

**Comment by nathan-maves** [comment] 2024-09-27 21:30
That was my bad.  I am pretty sure we support RHEL and rocky linux.

**Comment by prdoyle** [comment] 2024-09-30 15:24
The merged PR only fixes one of the reported problems. The "-1 problem" still exists.

**Comment by nathan-maves** [comment] 2024-10-01 20:16
Is there anything your team needs from me?  

A member of my team tried both "unlimited" and "-1" and ES 8.15 would not start up on debian linux.  This might stem from the issue you fixed as the code is not reading the correct setting value.  Is there any chance we can get a build with the fix to test things out?

**Comment by prdoyle** [comment] 2024-10-07 20:08
Hey @nathan-maves - I think we have everything we need. I'll try to reproduce today and reach out if I'm unable to do so.

**Comment by prdoyle** [comment] 2024-10-07 20:35
Actually @nathan-maves - can you please confirm that you have no files in `/etc/security/limits.d`?

**Comment by prdoyle** [comment] 2024-10-08 13:02
@nathan-maves - if you want to try with the fix... are you in a position to clone this repo and run `./gradlew run`?

**Comment by nathan-maves** [comment] 2024-10-08 14:39
@prdoyle I asked some people on our team and they confirmed that there is not much or sometimes nothing in their `/etc/security/limits.d`.

**Comment by prdoyle** [comment] 2024-10-08 18:03
Note to self: these limits are annoyingly sticky.

First, they only take effect on a new ssh session. The existing ssh session will retain the old limits even after `limits.conf` is edited.

Second, they apparently also stick to a Gradle daemon started during an ssh session. So even if you log out and ssh back into the machine, if a Gradle daemon is still running, it will remember the old limits too.

The command line I'm experimenting with right now is:

```
./gradlew --no-daemon run -Dtests.jvm.argline="-Des.enforce.bootstrap.checks=true" -Dtests.es.xpack.security.enabled=false
```

This appears to be doing what I want,

**Comment by prdoyle** [comment] 2024-10-08 18:27
Using the above technique,  `-1` appears to work as expected. I'm unable to provoke ES into showing `-1` as the file size setting in the error message.

Here's what I tried:

1. Boot an Ubuntu 20 VM.
2. Set `fsize` to 10001000000 in `/etc/security/limits.conf`. Open an SSH into the same machine. Boot elasticsearch using the above `./gradlew run` command line. **ES fails to boot**. At the end of `build/testclusters/runTask-0/logs/es.out` I see the error originally reported (quoted below).
3. Set `fsize` to `-1`. Open an SSH into the same machine. Boot ES. **ES boots successfully**.

The error I saw in the log was this:

```
bootstrap check failure [1] of [1]: max file size [10241024000000] for user [buildkite-agent] is too low, increase to [unlimited].
```

(Note that the reported value is 1024 times the setting I put in `limits.conf` as expected.)

**Comment by prdoyle** [comment] 2024-10-08 18:37
@nathan-maves - could you please check your ES logs for a line like this? If you're seeing this in your log, it's pretty hard for me to understand how you could have seen the `-1` error message. 🤔 

```
[INFO ][o.e.n.NativeAccess       ] [runTask-0] Using [jdk] native provider and native methods for [Linux]
```

**Comment by prdoyle** [comment] 2024-10-09 17:54
...in particular, it should say either `[Linux]`, `[MacOS]`, or `[Windows]`. If it says `[Linux]` that should be an indicator it was called from [this location](https://github.com/elastic/elasticsearch/blob/0736bf505e2ef504c2e523bf4dc64bdeaf94a845/libs/native/src/main/java/org/elasticsearch/nativeaccess/LinuxNativeAccess.java#L94), which also sets `-1` to mean "unlimited", in which case I'm not seeing how the code could generate the error message you saw.

**Comment by prdoyle** [comment] 2024-10-11 18:03
@nathan-maves - given that I've fixed one bug and cannot reproduce the other, I'm going to close this issue for now. If you do add a comment with some additional guidance for reproducing the "-1" error, we can reopen this issue and resume the investigation.

**Closed by prdoyle** 2024-10-11 18:03 UTC
Labels: >bug, :Core/Infra/Core, Team:Core/Infra

**Comment by nathan-maves** [comment] 2024-10-23 19:13
Was there a back port to 8.15 planned for this?

**Comment by prdoyle** [comment] 2024-11-03 17:48
8.15 backport is in #116152.

**Comment by zausel23** [comment] 2025-01-20 13:26
I build a 8.15.5 version for s390x architecture. We run the elasticsearch in a ubi9 image on openshift. When we start the statefulset we get the following error:

[2025-01-20T09:36:37,255][INFO ][o.e.b.BootstrapChecks    ] [elasticsearch-0] bound or publishing to a non-loopback address, enforcing bootstrap checks
[2025-01-20T09:36:37,256][WARN ][o.e.n.NativeAccess       ] [elasticsearch-0] Cannot get process limits because native access is not available
[2025-01-20T09:36:37,257][WARN ][o.e.n.NativeAccess       ] [elasticsearch-0] Cannot get process limits because native access is not available
[2025-01-20T09:36:37,257][WARN ][o.e.n.NativeAccess       ] [elasticsearch-0] Cannot get process limits because native access is not available
[2025-01-20T09:36:37,257][WARN ][o.e.n.NativeAccess       ] [elasticsearch-0] Cannot get process limits because native access is not available
[2025-01-20T09:36:37,257][WARN ][o.e.n.NativeAccess       ] [elasticsearch-0] Cannot get process limits because native access is not available
[2025-01-20T09:36:37,257][WARN ][o.e.n.NativeAccess       ] [elasticsearch-0] Cannot get process limits because native access is not available
[2025-01-20T09:36:37,261][ERROR][o.e.b.Elasticsearch      ] [elasticsearch-0] node validation exception
[2] bootstrap checks failed. You must address the points described in the following [2] lines before starting Elasticsearch. For more information see [https://www.elastic.co/guide/en/elasticsearch/reference/8.15/bootstrap-checks.html]
bootstrap check failure [1] of [2]: max size virtual memory [-1] for user [1001030000] is too low, increase to [unlimited]; for more information see [https://www.elastic.co/guide/en/elasticsearch/reference/8.15/max-size-virtual-memory-check.html]
bootstrap check failure [2] of [2]: max file size [-1] for user [1001030000] is too low, increase to [unlimited]; for more information see [https://www.elastic.co/guide/en/elasticsearch/reference/8.15/_max_file_size_check.html]
ERROR: Elasticsearch did not exit normally - check the logs at /usr/share/elasticsearch/logs/elasticsearch-cluster.log
[2025-01-20T09:36:37,268][INFO ][o.e.n.Node               ] [elasticsearch-0] stopping ...
