### ISSUE TITLE
java api scroll and curl scroll doesn't match

### ISSUE THREAD

**Issue by guomm** [elastic/elasticsearch#27185] opened 2017-10-31 10:00 UTC
I use scroll command to pull data, such as 
`curl localhost:9200/customer/_search?scroll=3m -d '{"size":50,"sort":[{"_doc":{"order":"asc"}}],"query":{"match_all":{}}}'.`
No matter how many times I executed the command, the scroll _id didn't change.
But, when I used the command by java api, the scroll _id  changed. Because I used multi thread to get data by same scrollId,  an error occred.
```
Caused by: SearchContextMissingException[No search context found for id [180930541]]
	at org.elasticsearch.search.SearchService.findContext(SearchService.java:510)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:286)
	at org.elasticsearch.action.search.SearchTransportService$8.messageReceived(SearchTransportService.java:314)
	at org.elasticsearch.action.search.SearchTransportService$8.messageReceived(SearchTransportService.java:311)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69)
	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1488)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:596)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```
java:
```
QueryBuilder qb = matchAllQuery();
 SearchResponse scrollResp = source_client.prepareSearch(index)
                .setScroll(new TimeValue(60000))
                .addSort(FieldSortBuilder.DOC_FIELD_NAME, SortOrder.ASC)
                .setQuery(qb)
                .setSize(5000).get();
```
**:

**Elasticsearch version** (`5.2.0`):

**JVM version** (`1.8`):

**OS version** (Red Hat 4.4.6-3):

someone has any idea?
thks!

**Comment by jasontedor** [comment] 2017-10-31 13:15
> No matter how many times I executed the command, the scroll _id didn't change.

I'm not sure how you're verifying these, but they definitely change. To wit:

```
$ diff <(curl -sS -H "Content-Type: application/json" "localhost:9200/_search?scroll=3m&pretty=true" -d '{"size":50,"sort":[{"_doc":{"order":"asc"}}],"query":{"match_all":{}}}' | jq '._scroll_id' <(curl -sS -H "Content-Type: application/json" "localhost:9200/_search?scroll=3m&pretty=true" -d '{"size":50,"sort":[{"_doc":{"order":"asc"}}],"query":{"match_all":{}}}' | jq '._scroll_id')
1c1
< "DnF1ZXJ5VGhlbkZldGNoBQAAAAAAAAA4FkdHUkJ1WkQxUU4yR3pXcDZMMjdVM0EAAAAAAAAAORZHR1JCdVpEMVFOMkd6V3A2TDI3VTNBAAAAAAAAADoWR0dSQnVaRDFRTjJHeldwNkwyN1UzQQAAAAAAAAA7FkdHUkJ1WkQxUU4yR3pXcDZMMjdVM0EAAAAAAAAAPBZHR1JCdVpEMVFOMkd6V3A2TDI3VTNB"
---
> "DnF1ZXJ5VGhlbkZldGNoBQAAAAAAAAA9FkdHUkJ1WkQxUU4yR3pXcDZMMjdVM0EAAAAAAAAAPhZHR1JCdVpEMVFOMkd6V3A2TDI3VTNBAAAAAAAAAD8WR0dSQnVaRDFRTjJHeldwNkwyN1UzQQAAAAAAAABAFkdHUkJ1WkQxUU4yR3pXcDZMMjdVM0EAAAAAAAAAQRZHR1JCdVpEMVFOMkd6V3A2TDI3VTNB"
```

note: `AAAAAAAAAOR` and `AAAAAAAAAPh`. Taking it further:

```
$ diff <(curl -sS -H "Content-Type: application/json" "localhost:9200/_search?scroll=3m&pretty=true" -d '{"size":50,"sort":[{"_doc":{"order":"asc"}}],"query":{"match_all":{}}}' | jq '._scroll_id' | shasum -a 1) <(curl -sS -H "Content-Type: application/json" "localhost:9200/_search?scroll=3m&pretty=true" -d '{"size":50,"sort":[{"_doc":{"order":"asc"}}],"query":{"match_all":{}}}' | jq '._scroll_id' | shasum -a 1)
1c1
< b43668e2261dfc0a8e7af1ae37be08b0372d72c5  -
---
> 8b3f6402fb71add0fba060772da555309ce4b168  -
```

I'm going to close this as unable to reproduce.

**Closed by jasontedor** 2017-10-31 13:15 UTC

**Comment by guomm** [comment] 2017-11-01 07:16
I am sorry, it's an expressed error.
I mean that after i get a scroll_id by command(curl localhost:9200/customer/_search?scroll=3m -d '{"size":50,"sort":[{"_doc":{"order":"asc"}}],"query":{"match_all":{}}}'), next i get the rest result by command(curl 100.110.6.105:9200/_search/scroll -d '{"scroll":"1m","scroll_id":"xxxx"}'). I can get result by same scroll_id. But this isn't suitable for java API.
