### ISSUE TITLE
java.text.Normalizer not found error in painless script after upgrading to v7.10.x

### ISSUE THREAD

**Issue by OzqurYalcin** [elastic/elasticsearch#66823] opened 2020-12-27 06:19 UTC
Elasticsearch version : 7.10.1

Plugins installed: analysis-icu

JVM version : openjdk version "11.0.9.1" 2020-11-04

OS version : Debian GNU/Linux 10 (buster)

Example part in query:
```json
 "script": {
        "inline": "def list=new ArrayList(); int count = doc[\"my_string_field\"].length; for(int i=0; i<count; i++){ list.add(Normalizer.normalize(doc[\"my_string_field\"][i], Normalizer.Form.NFD)); } return list.toArray();",
        "lang": "painless"
 }
```

Returned error part in response:
```json
 "caused_by" : {
        "type" : "illegal_argument_exception",
        "reason" : "field [java.text.Normalizer, Form] not found"
 }
```

Example part in query works fine in elasticsearch v7.8.x.
After upgrading to 7.10.x, query failed.
What is the the problem ?

**Comment by jdconrad** [comment] 2021-01-05 17:48
I have replicated this bug, and I believe this is caused by the PR (https://github.com/elastic/elasticsearch/pull/56293) where static inner class resolution wasn't appropriately taken into account.

**Comment by jdconrad** [comment] 2021-01-05 19:13
Fixed by https://github.com/elastic/elasticsearch/pull/67027

**Closed by jdconrad** 2021-01-05 19:13 UTC
Labels: :Core/Infra/Scripting, >bug, Team:Core/Infra
