### ISSUE TITLE
[docs] Side menu (TOC) not rendering on Firefox 60

### ISSUE THREAD

**Issue by ergo** [elastic/elasticsearch#30901] opened 2018-05-28 10:45 UTC
Hello,
Documentation does not render side menu anymore.
Is this something that can be added back? Currently this makes browsing documentation very tedious task.

**Comment by dadoonet** [comment] 2018-05-28 11:53
It does for me... May be clean your browser cache?

![image](https://user-images.githubusercontent.com/274222/40613350-7f7f77be-627e-11e8-87a8-c0c48cbdeed3.png)

**Comment by ergo** [comment] 2018-05-28 11:57
Hm, seems like it is a JS bug.

`ReferenceError: MktoForms2 is not defined` - happens on Firefox 60, and menu is gone.
On Chrome it indeed renders fine.

**Comment by dadoonet** [comment] 2018-05-28 12:00
Thank you! I'm going to ping people internally.

**Comment by debadair** [comment] 2018-05-29 20:01
I can't reproduce, either. Works fine on FF 60.0.1 on the Mac & also tested on Windows via Browserstack.com. The JS error they were seeing seems odd...but the most common reason the TOC doesn't load correctly is that some ad/privacy blocker is engaged.

**Comment by ergo** [comment] 2018-05-30 15:30
Really, is that even legal with GDPR right now?

**Comment by lcawl** [comment] 2018-05-31 16:38
Related issue?: https://github.com/elastic/docs/issues/367

**Comment by mariusz-kowalski** [comment] 2018-06-01 10:03
This is issue with "Tracking protection" when it is enabled in Firefox (by default in my case) side menu disappears. When I disable tracking protection for elastic.co menu is back.

**Comment by sylvie777** [comment] 2018-06-01 10:07
@mariusz-kowalski Do you mind checking something for me? Would you do the same on our [staging site](https://staging-website.elastic.co/guide/index.html) and let me know if the problem still persists?

**Comment by sylvie777** [comment] 2018-06-01 10:11
@mariusz-kowalski Sorry, didn't mean to delete your comment:

This is issue with "Tracking protection" when it is enabled in Firefox (by default in my case) side menu disappears. When I disable tracking protection for elastic.co menu is back.

**Comment by sylvie777** [comment] 2018-06-04 22:03
@ergo @Hashiko @dadoonet Thanks for your patience with this! A fix has been applied. Please let me know if the issue still persists for you.

**Comment by dadoonet** [comment] 2018-06-05 07:42
Awesome! Closing then. Thanks all for fixing and confirming the fix!

**Closed by dadoonet** 2018-06-05 07:42 UTC
Labels: :Docs, >docs
