### ISSUE TITLE
GeoShapeQueryTests.testRandomGeoCollectionQuery failures on CI

### ISSUE THREAD

**Issue by gwbrown** [elastic/elasticsearch#44915] opened 2019-07-26 17:04 UTC
[Build scan](https://scans.gradle.com/s/qsdg7dujtvmle/tests/nfxodyych4uas-5wqvk3m5mgnzm?openStackTraces=WzBd)

Per build-stats this has failed a few times in the last 60 days, and 3 times within the past couple days.

Reproduce line (does not reproduce locally):
```
/gradlew :server:test --tests "org.elasticsearch.search.geo.GeoShapeQueryTests.testRandomGeoCollectionQuery" -Dtests.seed=C66D73C415DBFB0C -Dtests.security.manager=true -Dtests.locale=nn-NO -Dtests.timezone=America/St_Lucia -Dcompiler.java=12 -Druntime.java=8
```

Failure details:
```
java.lang.AssertionError: 
query: {
  "geo_shape" : {
    "location" : {
      "shape" : {
        "type" : "geometrycollection",
        "geometries" : [
          {
            "type" : "multipoint",
            "coordinates" : [
              [
                109.33427363785381,
                -31.055602170604672
              ],
              [
                106.1064321128294,
                -29.010310521912526
              ],
              [
                104.8001918267574,
                -31.24373213861376
              ],
              [
                109.09068417090897,
                -30.227476666966684
              ],
              [
                108.52113521171589,
                -30.18572773332367
              ],
              [
                108.97009378627727,
                -28.957151596631558
              ],
              [
                104.27021889977178,
                -30.746722049972746
              ],
              [
                106.04757005639395,
                -30.049325249811364
              ],
              [
                106.16192110494983,
                -29.583153339133382
              ],
              [
                108.41290548703893,
                -30.839102308836758
              ]
            ]
          },
          {
            "type" : "linestring",
            "coordinates" : [
              [
                105.77812860342026,
                -32.29217300567255
              ],
              [
                107.56444493009464,
                -30.47188731140721
              ],
              [
                108.88682918169046,
                -30.168794386125768
              ],
              [
                106.7397210052791,
                -29.535880148994714
              ],
              [
                105.87410624467522,
                -30.117446177340703
              ],
              [
                109.25780121368561,
                -29.071284577228745
              ]
            ]
          },
          {
            "type" : "multipoint",
            "coordinates" : [
              [
                109.20444928453941,
                -28.887330859986612
              ],
              [
                108.4948177047382,
                -31.814012086285782
              ],
              [
                104.5081629751859,
                -28.9716495030422
              ],
              [
                107.58576915751799,
                -28.999188592956223
              ],
              [
                104.7019422125022,
                -29.47963692603792
              ],
              [
                107.40550479923213,
                -29.080785475639004
              ]
            ]
          },
          {
            "type" : "multilinestring",
            "coordinates" : [
              [
                [
                  108.3542147280241,
                  -32.24251657011377
                ],
                [
                  107.85786510015313,
                  -29.956104515999883
                ],
                [
                  107.19974175423394,
                  -31.495655564108375
                ],
                [
                  108.86874713499965,
                  -30.693954694786402
                ],
                [
                  107.81492735144948,
                  -28.944613025188517
                ]
              ]
            ]
          },
          {
            "type" : "polygon",
            "coordinates" : [
              [
                [
                  -85.0,
                  -55.41268710136279
                ],
                [
                  -85.0,
                  -45.08800706112868
                ],
                [
                  110.46383303911944,
                  -45.08800706112868
                ],
                [
                  -85.0,
                  -55.41268710136279
                ]
              ]
            ]
          }
        ]
      },
      "relation" : "intersects"
    },
    "ignore_unmapped" : false,
    "boost" : 1.0
  }
} doc: {"location":{"type":"geometrycollection","geometries":[{"type":"polygon","orientation":"right","coordinates":[[[-105.04363460103107,21.529664784728634],[-106.93194353064283,21.769539947070843],[-108.65365799162868,22.73851432389303],[-108.63208348397023,25.12957017719524],[-108.25178382933814,26.02590291685958],[-104.39505130530688,25.613469467782718],[-104.39084040870026,22.743818215313],[-105.04363460103107,21.529664784728634]]]},{"type":"polygon","orientation":"right","coordinates":[[[-124.70359656336262,-36.87240260493818],[-126.60201263596461,-36.27149106730364],[-126.69424961260506,-35.07697072642597],[-126.58734752823541,-31.669998917167486],[-126.34023107753984,-31.607583503068806],[-124.45141782146695,-31.663005389609214],[-123.569435941306,-33.16420727207776],[-123.77784733511275,-36.43328202252092],[-124.70359656336262,-36.87240260493818]]]},{"type":"point","coordinates":[52.0999666369553,26.195929943617784]},{"type":"multilinestring","coordinates":[[[-114.9951002610597,81.26592744169788],[-118.45262282718537,82.89053346818918],[-115.74859271548624,80.25762823325577],[-117.18567198089143,80.3219078479273],[-115.14116348366986,82.75795186589495],[-115.23723057458224,79.91167513377567],[-114.90436429938512,81.31197056690364]],[[-114.10674635416268,82.61447077600309],[-114.4792869715932,81.20792950830932],[-117.2678921568098,81.16296955317189]],[[-115.9774572600585,81.81808068292607],[-114.50820245924662,82.97956086593652],[-115.07480716282188,81.69473520863662],[-114.35808164908535,80.55087045383196],[-116.36564898365921,80.6764557540112],[-118.51937931830362,81.94977234210653]]]},{"type":"polygon","orientation":"right","coordinates":[[[-85.0,-55.41268710136279],[-85.0,-45.08800706112868],[110.46383303911944,-45.08800706112868],[-85.0,-55.41268710136279]]]}]}}

at __randomizedtesting.SeedInfo.seed([C66D73C415DBFB0C:AE107D6743F82484]:0)
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.elasticsearch.search.geo.GeoShapeQueryTests.testRandomGeoCollectionQuery(GeoShapeQueryTests.java:455)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
at java.lang.Thread.run(Thread.java:748)
```

May relate to https://github.com/elastic/elasticsearch/issues/37356

**Comment by imotov** [comment] 2019-07-26 20:56
Duplicate of #44891

**Closed by imotov** 2019-07-26 20:56 UTC
Labels: :Analytics/Geo, >test-failure
