### ISSUE TITLE
multi dynamic_templates incorrect

### ISSUE THREAD

**Issue by cyinll** [elastic/elasticsearch#29200] opened 2018-03-22 03:21 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 5.3.0

**Plugins installed**: []

**JVM version** (`java -version`): 1.8

**OS version** (`uname -a` if on a Unix-like system): 

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. create template with dynamic_templates in mappings
```
PUT /_template/dynamic
{
  "template" : "*",
  "mappings": {
    "default": {
      "dynamic_templates": [
        {
          "string_as_text": {
            "match": "*_text",
            "match_mapping_type": "string",
            "mapping": {
              "type": "text",
              "analyzer": "ik_max_word"
            }
          }
        }
      ]
    }
  }
}
```
 2. create index with dynamic_templates in mappings
```
PUT /test_dynamic
{
  "mappings": {
    "default": {
      "dynamic_templates": [
        {
          "string_as_text": {
            "match_mapping_type": "string",
            "mapping": {
              "type": "text",
              "analyzer": "ik_max_word"
            }
          }
        }
      ]
    }
  }
}
```
 3. get index mappings, i hope it use the second dynamic_templates without 'match' parameter, but it will use the first
```
GET /test_dynamic/_mappings

{
  "test_dynamic" : {
    "mappings" : {
      "default" : {
        "dynamic_templates" : [
          {
            "string_as_text" : {
              "match" : "*_text",
              "match_mapping_type" : "string",
              "mapping" : {
                "analyzer" : "ik_max_word",
                "type" : "text"
              }
            }
          }
        ]
      }
    }
  }
}
```

**Comment by colings86** [comment] 2018-03-22 09:31
So whats happening here is that dynamic templates with the same name are being merged together to produce the final template. You can see this more clearly if you add an extra setting to the index creeation command as below:
```
PUT /test_dynamic
{
  "mappings": {
    "default": {
      "dynamic_templates": [
        {
          "string_as_text": {
            "match_mapping_type": "string",
            "mapping": {
              "type": "text",
              "analyzer": "ik_max_word",
              "norms": false
            }
          }
        }
      ]
    }
  }
}
```

The resulting mapping is now:
```
{
  "test_dynamic": {
    "mappings": {
      "default": {
        "dynamic_templates": [
          {
            "string_as_text": {
              "match": "*_text",
              "match_mapping_type": "string",
              "mapping": {
                "analyzer": "ik_max_word",
                "norms": false,
                "type": "text"
              }
            }
          }
        ]
      }
    }
  }
}
```

Note that the mapping now includes both the `match` line and thee `norms` line.

It's tricky to know what to do here as its certainly useful to be able to augment rules made in a base template by adding or overriding settings in the rules in the index creation command. Maybe we should only merge the `mapping` part of the dynamic template and have the `match` and `match_mapping_type` only take from the last template in the precedence order, however I'm not sure how complex this would be in the code and they could well be other users that rely on being able to merge the `match` and `match_mapping_type` in their templates. (@clintongormley @jpountz what do you think?)

A workaround for this would be to add `"match": "*",` to the dynamic template in the create index request which will mean the template will match any name of field as you require.

/cc @elastic/es-search-aggs

**Comment by colings86** [comment] 2018-03-23 13:55
We discussed this in FixItFriday and it was agreed that it is unfortunate that dynamic templates with the same name in different index templates/create index request are merged rather than replaced and we would like to change this.

Another concern was raised that when merging the index template and create index request which even have different dynamic templates its not clear what the order of the dynamic templates would be in the final mappings and we should fix this too.

**Comment by jtibshirani** [comment] 2018-04-30 22:34
I've started to look into fixing this. @colings86 there are a few points that would be helpful to clarify:
1. When combining mappings across index templates and create index requests, we do a ‘deep merge’, which attempts to recursively combine all map keys. This clearly differs from the normal way mappings are merged during a ‘put mappings’ request. From the documentation on index templates:

    > Note, for mappings, the merging is "deep", meaning that specific object/property based mappings can easily be added/overridden on higher order templates, with lower order templates providing the basis.

    It sounds like we want to keep this deep merge strategy for all other parts of the mapping, but change it only for dynamic templates? This seems a bit inconsistent to me, as other top-level parts of the mapping (like `_meta`) will still still undergo a deep merge. I don’t have context from the discussion though, and am likely missing some important reasoning here.

2. After merging the index templates and create index request, it seems like the dynamic templates should be listed in the following order: the entries from the ‘create index’ request, then the entries from each matching index template, starting from the index template with the highest ‘order’ parameter and progressing to the lowest. It looks like this is in fact what’s happening, but I can make sure to add docs + a test for this behavior.

Lastly @cyinll — just a quick note that I modified the first step of your reproduction above to include the `_template` endpoint.

**Comment by simitt** [comment] 2019-09-23 09:40
APM creates multiple keys with the same name for default `dynamic_templates`, with the purpose of having different mappings on different `match_mapping_type` definitions. E.g
```
{
    "dynamic_templates": [
        {
            "labels": {
                "path_match": "labels.*",
                "match_mapping_type": "string",
                "mapping": {
                    "type": "keyword"
                }
            }
        },
        {
            "labels": {
                "path_match": "labels.*",
                "match_mapping_type": "boolean",
                "mapping": {
                    "type": "boolean"
                }
            }
        },
        {
            "labels": {
                "path_match": "labels.*",
                "mapping": {
                    "scaling_factor": 1000000,
                    "type": "scaled_float"
                }
            }
        }
    ]
}
```

This works fine as long as users don't add custom templates defining `dynamic_templates`, as this leads to merging the dynamic templates, removing all but one entry with the same name in the final mapping. 

The issue was identified by a user, for more details see https://github.com/elastic/apm-server/issues/2693#issuecomment-530366857

As pointed out to me by @jtibshirani the behavior seems related to the discussions on this issue.

**Comment by cbuescher** [comment] 2020-03-10 09:51
I opened #52062 with the current plan to deprecate and remove the ability to use the same name for dynamic templates and will close this issue because of this.

**Comment by javanna** [comment] 2023-05-03 22:26
Closing in favour of #53326 which covers the exact same problem.

**Closed by javanna** 2023-05-03 22:26 UTC
Labels: >bug, >breaking, :Search/Mapping, Team:Search
