### ISSUE TITLE
unbalanced allocation when adding new nodes

### ISSUE THREAD

**Issue by jgq2008303393** [elastic/elasticsearch#27977] opened 2017-12-24 04:47 UTC
**Elasticsearch version:**
```
  "version": {
    "number": "5.6.4",
    "build_hash": "8bbedf5",
    "build_date": "2017-10-31T18:55:38.105Z",
    "build_snapshot": false,
    "lucene_version": "6.6.1"
  }
```

**Cluster:**
Cluster: 10 machines, each with 2 nodes
Indices: 1 index rollover daily (40 primary shards, each with 1 replica)

**Description of the problem:**
We add 5 machines(10 nodes) to the cluster on friday. Howover, we found all 40 * 2 shards are allocated to the 5 new machines on saturday, which cause a lot of bulk rejections.

We have encounted this problem before on another cluster, and now we use index.routing.allocation.total_shards_per_node to control shard allocation when add new nodes.
Although it works, but is trouble to operate when manage many clusters. 

We wonder that is this a known issues? Is there any working or plan on it?

Thanks very much : )

**Comment by DaveCTurner** [comment] 2017-12-26 09:14
This is quite possibly a duplicate of #17213 and possibly also related to recent discussion on #27622 but I'm raising it for discussion with the team when we return from the Christmas break in case it's something else.

**Comment by DaveCTurner** [comment] 2017-12-26 12:27
@jgq2008303393 when you added the machines on Friday, did the cluster rebalance itself to use the new nodes straight away, or did they remain idle until then new indices were created at the start of Saturday?

If they were idle then it makes sense that all the new shards ended up on the new nodes, but it raises the question of why the new nodes remained idle for so long. Was rebalancing disabled or otherwise prevented from working? Can you use the [allocation explain API](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-allocation-explain.html) to investigate why this happened?

**Comment by jgq2008303393** [comment] 2017-12-27 01:50
Yes, this is quite similar to [#17213](https://github.com/elastic/elasticsearch/issues/17213). We didn't change rebalancing setting and rebalancing is just slow for big shards.

**Comment by jgq2008303393** [comment] 2017-12-27 02:02
Since the cluster is balanced now, I think it's not helpful to use the allocation explain api now. Any way, the current response is as following:
```
{
  "index": "index_name_2017.12.23",
  "shard": 0,
  "primary": true,
  "current_state": "started",
  "current_node": {
    "id": "m3UVXCzeQL6UeTt8-WNUeQ",
    "name": "1513934553052069111",
    "transport_address": "xxxx",
    "attributes": {
      "rack": "112180",
      "set": "18",
      "region": "99",
      "ip": "xxxx"
    },
    "weight_ranking": 1
  },
  "can_remain_on_current_node": "yes",
  "can_rebalance_cluster": "yes",
  "can_rebalance_to_other_node": "no",
  "rebalance_explanation": "cannot rebalance as no target node exists that can both allocate this shard and improve the cluster balance",
  "node_allocation_decisions": [
    {
      "node_id": "36DFt1IGTteUU4BSdyGuoA",
      "node_name": "1513934553052069411",
      "transport_address": "xxxx",
      "node_attributes": {
        "rack": "112129",
        "set": "18",
        "region": "99",
        "ip": "xxxx"
      },
      "node_decision": "no",
      "weight_ranking": 1,
      "deciders": [
        {
          "decider": "awareness",
          "decision": "NO",
          "explanation": "there are too many copies of the shard allocated to nodes with attribute [ip], there are [2] total configured shard copies for this shard id and [15] total attribute values, expected the allocated shard count per attribute [2] to be less than or equal to the upper bound of the required number of shards per attribute [1]"
        }
      ]
    },
    ......
  ]
}
```

**Comment by DaveCTurner** [comment] 2018-01-05 15:53
We discussed this in Fix-it-Friday. We are aware that the allocator can make suboptimal decisions in this sort of situation, and this is effectively a duplicate of #17213.

The `index.routing.allocation.total_shards_per_node` setting is the preferred way to control this situation at the moment. An alternative could be to adjust the [shard balancing heuristics](https://www.elastic.co/guide/en/elasticsearch/reference/6.1/shards-allocation.html#_shard_balancing_heuristics) by increasing `cluster.routing.allocation.balance.index` and/or decreasing `cluster.routing.allocation.balance.shard` to encourage the allocator to pay less attention to the shards from other indices.

It's a little confusing that your 10 new nodes were unable to handle Saturday's traffic on their own, when it seems that your 10 old nodes were handling Friday's traffic just fine. Were they similar traffic levels or was Saturday notably heavier than Friday?

Another comment was that 40 primary shards for a daily index seems like a lot. We don't know the details of your use case, of course, nor what benchmarking you have already performed, but the general advice was that you might find it worthwhile to try and reduce the number of shards you're using.

Since this is very closely related to #17213 we'll leave that issue open and close this one.

**Closed by DaveCTurner** 2018-01-05 15:53 UTC
Labels: :Allocation, discuss

**Comment by jgq2008303393** [comment] 2018-01-20 06:48
Thanks for your reply and hope  ES can play better in this situation.

I don't express some information clearly. The cluster originally has 10 machines(20 nodes), then we add 5 new machines, so it is 15 machines totally.
