### ISSUE TITLE
Better Handling of ILM Policy Changes where Steps change/get removed

### ISSUE THREAD

**Issue by BenB196** [elastic/elasticsearch#94153] opened 2023-02-27 14:40 UTC
### Description

(I'm opening this as a feature request rather than a bug report, but I think it could technically be either depending on what is actually expected)

I think Elasticsearch should better handle switch ILM policies on an index where a step is removed from one policy to another.

## Example

1. Create an ILM policy that does something like: Hot -> Warm -> Cold -> Delete
2. Create an index and assign it the above policy
3. Wait for the index to reach the `Cold` phase
4. Create a new ILM policy that does something like: Hot -> Warm -> Delete
5. Apply this new ILM policy to the index.
6. Get a warning/stack trace like:

```
java.lang.IllegalArgumentException: step [{"phase":"cold","action":"complete","name":"complete"}] for index [restored-.ds-metrics-linux.iostat-private.linux.development-2023.01.20-000012] with policy [metrics-linux.iostat] does not exist
	at org.elasticsearch.ilm@8.6.2/org.elasticsearch.xpack.ilm.IndexLifecycleTransition.validateTransition(IndexLifecycleTransition.java:95)
	at org.elasticsearch.ilm@8.6.2/org.elasticsearch.xpack.ilm.IndexLifecycleTransition.moveClusterStateToStep(IndexLifecycleTransition.java:123)
	at org.elasticsearch.ilm@8.6.2/org.elasticsearch.xpack.ilm.ExecuteStepsUpdateTask.doExecute(ExecuteStepsUpdateTask.java:173)
	at org.elasticsearch.ilm@8.6.2/org.elasticsearch.xpack.ilm.IndexLifecycleClusterStateUpdateTask.execute(IndexLifecycleClusterStateUpdateTask.java:47)
	at org.elasticsearch.ilm@8.6.2/org.elasticsearch.xpack.ilm.IndexLifecycleRunner$1.execute(IndexLifecycleRunner.java:69)
	at org.elasticsearch.server@8.6.2/org.elasticsearch.cluster.service.MasterService.innerExecuteTasks(MasterService.java:1052)
	at org.elasticsearch.server@8.6.2/org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:1017)
	at org.elasticsearch.server@8.6.2/org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:278)
	at org.elasticsearch.server@8.6.2/org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:170)
	at org.elasticsearch.server@8.6.2/org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:110)
	at org.elasticsearch.server@8.6.2/org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:148)
	at org.elasticsearch.server@8.6.2/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:850)
	at org.elasticsearch.server@8.6.2/org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:257)
	at org.elasticsearch.server@8.6.2/org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:223)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

7. The index will never hit the Delete step because of the above.

It would be nice if ILM could better recognize this type of issue, and just proceed with the Delete phase.

**Comment by andreidan** [comment] 2023-03-08 11:05
Closing this as duplicate of https://github.com/elastic/elasticsearch/issues/91749

**Closed by andreidan** 2023-03-08 11:05 UTC
Labels: >bug, :Data Management/ILM+SLM, Team:Data Management
