### ISSUE TITLE
Add registered_domain processor similar to Filebeat processor

### ISSUE THREAD

**Issue by leehinman** [elastic/elasticsearch#57476] opened 2020-06-01 19:56 UTC
It would be nice to have a registered_domain processor like the [filebeat one](https://www.elastic.co/guide/en/beats/filebeat/current/processor-registered-domain.html).  This would be useful so we can have ingest pipelines that are completely in ES that can fill out the ECS fields like dns.question.top_level_domain.

**Comment by jamiehynds** [comment] 2020-08-31 14:38
Discussed with @jakelandis. @jamiehynds to provide ECS fields to map to.

**Comment by webmat** [comment] 2020-11-18 19:20
In ECS, fields that contain a DNS domain name can appear in many places:

* `url.domain` generally contains an FQDN, but can also contain an IP address
* `dns.question.name` contains a domain in CNAME lookups, but can can contain other things, depending on the DNS query type
* `[source|destination|client|server].domain` can contain either FQDNs or Active Directory domain names.

Each of these field can potentially contain stuff that doesn't look like a FQDN, so leniency is important. Or at least the code path for invalid values should be as fast :-)

The convention we've followed has always been to have the domain breakdown fields as siblings to each of the above. The breakdown fields are `.registered_domain`, `.top_level_domain` and `subdomain`. You can check out each of their descriptions on the [ECS dns fields page](https://www.elastic.co/guide/en/ecs/current/ecs-dns.html).

But by example, when breaking down "www.google.co.uk":

* registered_domain: google.co.uk
* top_level_domain: co.uk (so it's the "effective" TLD)
* subdomain: www

**Comment by mbudge** [comment] 2020-12-08 08:35
Hi, 

We are implementing indicator match in the SIEM. One issue we have is doing TLD extract in non-beats fieds i.e. not packetbeat. 

Proxy data is indexed in elastic directly through logstash, and although there is a Logstash TLD extract filter it is not maintained/documented. 

The problem is if an indicator has a sub-domain in the logs but not the threat intel feed, there's a high risk it will be missed. 

It would help if we could do TLD extract in an ingest processor.

The rules for doing TLD extract with the public suffix list can be found here
https://publicsuffix.org/list/

**Comment by danhermann** [comment] 2021-04-14 12:18
Closed by https://github.com/elastic/elasticsearch/pull/67611

**Closed by danhermann** 2021-04-14 12:18 UTC
Labels: :Core/Features/Ingest, >enhancement, Team:Core/Features
