### ISSUE TITLE
cluster.name if empty prevents installation of plugins

### ISSUE THREAD

**Issue by Jaff** [elastic/elasticsearch#24762] opened 2017-05-18 02:33 UTC
**Elasticsearch version**: 5.4.0

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by jasontedor** [comment] 2017-05-18 02:46
You can not even start Elasticsearch with an empty cluster name (we reject empty settings), so I'm closing this as expected behavior and not a bug.

**Closed by jasontedor** 2017-05-18 02:46 UTC
