### ISSUE TITLE
Confusing error when using has_child with inner hits

### ISSUE THREAD

**Issue by HonzaKral** [elastic/elasticsearch#16685] opened 2016-02-15 23:48 UTC
When inner_hits has mis-configured `highlight` key the error returned is wrong:

```
curl localhost:9200/stack/question/_search -d '{
    "query": {
        "has_child": {
            "inner_hits": {
                "highlight": {"body": {}}
            },
            "type": "answer",
            "query": {
                "match": {"body": "drip"}
            }
        }
    }
}'
```

complaints with:

```
            {
                "col": 66,
                "index": "stack",
                "line": 1,
                "reason": "[has_child] requires 'query' field",
                "type": "query_parsing_exception"
            }
```

**Comment by clintongormley** [comment] 2016-02-17 15:44
In current master, the bad highlight block just gets ignored completely.  I think this will probably change when the search refactoring for inner_hits gets merged in?  @cbuescher @colings86 ?

**Comment by cbuescher** [comment] 2016-02-29 13:59
@clintongormley the parser that parses the bad highlight block will throw an exception when it runs into an object name it doesn't know (here "body"). Since we haven't refactored `inner_hits` yet, this part still gets parsed on the shard, so it will raise the error there, but once we have refactored `inner_hits` this should also be raised already on the coordinating node. We can keep this open until then for verification, the tests for throwing an error on the bad highlight element are already there.

**Comment by colings86** [comment] 2017-04-26 11:24
@cbuescher is this issue now solved since all of the search request has now been refactored?

**Comment by cbuescher** [comment] 2017-04-26 11:55
@colings86 yes, this can be close now. I just checked this on 5.3, the error we get now is:
```
"type": "parsing_exception",
    "reason": "[inner_hits] failed to parse field [highlight]",
    "line": 4,
    "col": 31,
    "caused_by": {
      "type": "illegal_argument_exception",
      "reason": "[highlight] unknown field [body], parser not found"
    }
```
Which correctly points to the cause of the error (the unknown "body" field).

**Closed by cbuescher** 2017-04-26 11:55 UTC
Labels: :Query DSL, bug
