### ISSUE TITLE
[TEST] Builds can hit the max compilations limit

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#24308] opened 2017-04-25 10:46 UTC
Build URL: 
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.3+multijob-unix-compatibility/os=centos/143/console

This build failed because it exceeded 1000 inline script compilations per minute. Given that our tests use a mock script engine, should we increase this limit for tests that extend `ESIntegTestCase`?

**Comment by nik9000** [comment] 2017-04-25 13:31
I wonder if this is a duplicate of #24272?

**Comment by colings86** [comment] 2017-04-25 13:33
I does seem related

**Comment by jdconrad** [comment] 2017-05-09 00:09
Another: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=ubuntu/948/console
And Another: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+aggressive-opts/83/console
And Another: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=centos/948/console

**Comment by jasontedor** [comment] 2017-05-09 13:43
@jdconrad I pushed f222748506dee3f50f99551b33b049e87c6cd425 for those specific failures.

**Comment by jdconrad** [comment] 2017-05-09 14:57
@jasontedor Thank you!

**Comment by jasontedor** [comment] 2017-05-24 00:09
I increased this to 2048 in 2e570fc6fa45c6a4007835ebd2244025859ffde2 and backported to 5.x in 3ad726d3369128994167726ccca0a306d991ddfc.

**Comment by markharwood** [comment] 2017-07-31 08:19
Looks a similar limit was hit but this time in YAML tests.
https://internal-ci.elastic.co/job/elastic+x-pack-elasticsearch+master+periodic/3602/console

	  2> REPRODUCE WITH: gradle :x-pack-elasticsearch:qa:reindex-tests-with-security:integTestRunner -Dtests.seed=C478BB8E0AA47746 -Dtests.class=org.elasticsearch.xpack.security.ReindexWithSecurityClientYamlTestSuiteIT -Dtests.method="test {yaml=/10_reindex/Using a script to write to an index to which you don't have access is forbidden}" -Dtests.security.manager=true -Dtests.locale=ar-JO -Dtests.timezone=America/Indiana/Marengo
	  1>         "reason" : "Failed to compile inline script [if (ctx._source.user == \"kimchy\") {ctx._index = 'other_dest'}] using lang [painless]",
	  1>         "caused_by" : {
	  1>           "type" : "circuit_breaking_exception",
	  1>           "reason" : "[script] Too many dynamic script compilations within one minute, max: [15/min]; please use on-disk, indexed, or scripts with parameters instead; this limit can be changed by the [script.max_compilations_per_minute] setting",
	  1>           "bytes_wanted" : 0,
	  1>           "bytes_limit" : 0,
	  1>           "stack_trace" : "CircuitBreakingException[[script] Too many dynamic script compilations within one minute, max: [15/min]; please use on-disk, indexed, or scripts with parameters instead; this limit can be changed by the [script.max_compilations_per_minute] setting]
	  1> 	at org.elasticsearch.script.ScriptService.checkCompilationLimit(ScriptService.java:342)
	  1> 	at org.elasticsearch.script.ScriptService.compile(ScriptService.java:295)


The error message says the exceeded limit here says only 15 compilations per minute.

**Comment by jasontedor** [comment] 2017-07-31 08:29
That's an X-Pack issue @markharwood.

**Closed by jasontedor** 2017-07-31 08:29 UTC
Labels: :Scripting, jenkins, test

**Comment by markharwood** [comment] 2017-07-31 08:47
Thx - will open a separate issue.

**Comment by jasontedor** [comment] 2017-08-01 05:53
I pushed 6d68e8a10c2d66467af88c4a130d3020a23d5673 and backported it too.
