### ISSUE TITLE
NoClassDefFoundError: io/netty/util/concurrent/PromiseTask

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#42532] opened 2019-05-24 16:10 UTC
[This PR build](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/14658) failed with a deeply mysterious fatal error during node startup:

```
  [2019-05-24T15:53:17,531][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [integTest-0] fatal error in thread [main], exiting
  java.lang.NoClassDefFoundError: io/netty/util/concurrent/PromiseTask
  	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
  	at java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[?:?]
  	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
  	at java.net.URLClassLoader.defineClass(URLClassLoader.java:550) ~[?:?]
  	at java.net.URLClassLoader$1.run(URLClassLoader.java:458) ~[?:?]
  	at java.net.URLClassLoader$1.run(URLClassLoader.java:452) ~[?:?]
  	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
  	at java.net.URLClassLoader.findClass(URLClassLoader.java:451) ~[?:?]
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
  	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:899) ~[?:?]
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
  	at io.netty.util.concurrent.GlobalEventExecutor.<init>(GlobalEventExecutor.java:47) ~[?:?]
  	at io.netty.util.concurrent.GlobalEventExecutor.<clinit>(GlobalEventExecutor.java:44) ~[?:?]
  	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:36) ~[?:?]
  	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58) ~[?:?]
  	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47) ~[?:?]
  	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59) ~[?:?]
  	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77) ~[?:?]
  	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72) ~[?:?]
  	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59) ~[?:?]
  	at org.elasticsearch.transport.netty4.Netty4Transport.doStart(Netty4Transport.java:131) ~[?:?]
  	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:59) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  	at org.elasticsearch.transport.TransportService.doStart(TransportService.java:228) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:59) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  	at org.elasticsearch.node.Node.start(Node.java:682) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  	at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:271) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:348) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  Caused by: java.lang.ClassNotFoundException: io.netty.util.concurrent.PromiseTask
  	at java.net.URLClassLoader$1.run(URLClassLoader.java:460) ~[?:?]
  	at java.net.URLClassLoader$1.run(URLClassLoader.java:452) ~[?:?]
  	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
  	at java.net.URLClassLoader.findClass(URLClassLoader.java:451) ~[?:?]
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
  	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:899) ~[?:?]
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
  	... 34 more
  Caused by: java.io.EOFException
  	at java.io.RandomAccessFile.readFully(RandomAccessFile.java:472) ~[?:?]
  	at java.util.zip.ZipFile$Source.readFullyAt(ZipFile.java:1304) ~[?:?]
  	at java.util.zip.ZipFile$ZipFileInputStream.initDataOffset(ZipFile.java:998) ~[?:?]
  	at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:1013) ~[?:?]
  	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:468) ~[?:?]
  	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159) ~[?:?]
  	at jdk.internal.loader.Resource.getBytes(Resource.java:124) ~[?:?]
  	at java.net.URLClassLoader.defineClass(URLClassLoader.java:545) ~[?:?]
  	at java.net.URLClassLoader$1.run(URLClassLoader.java:458) ~[?:?]
  	at java.net.URLClassLoader$1.run(URLClassLoader.java:452) ~[?:?]
  	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
  	at java.net.URLClassLoader.findClass(URLClassLoader.java:451) ~[?:?]
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
  	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:899) ~[?:?]
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
  	... 34 more
  [2019-05-24T15:53:17,532][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [integTest-0] uncaught exception in thread [elasticsearch[integTest-0][generic][T#1]]
  java.lang.NullPointerException: null
  	at org.elasticsearch.transport.netty4.Netty4Transport.lambda$stopInternal$2(Netty4Transport.java:255) ~[?:?]
  	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:103) ~[elasticsearch-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:85) ~[elasticsearch-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  	at org.elasticsearch.common.lease.Releasables.close(Releasables.java:36) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  	at org.elasticsearch.common.lease.Releasables.close(Releasables.java:46) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  	at org.elasticsearch.common.lease.Releasables.close(Releasables.java:51) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  	at org.elasticsearch.transport.netty4.Netty4Transport.stopInternal(Netty4Transport.java:254) ~[?:?]
  	at org.elasticsearch.transport.TcpTransport.lambda$doStop$15(TcpTransport.java:564) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:687) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
  	at java.lang.Thread.run(Thread.java:834) [?:?]
```

Build scan: https://scans.gradle.com/s/ferny2m2wcgho

**Comment by rjernst** [comment] 2019-05-24 17:10
I saw this in a recent PR as well (although I can't find the link). I attributed it to disk/memory corruption and it passed on retry.

**Comment by original-brownbear** [comment] 2019-05-24 17:13
@rjernst yea same here (unfortunately no link as well). I mean:

```
17:53:18   Caused by: java.io.EOFException
17:53:18   	at java.io.RandomAccessFile.readFully(RandomAccessFile.java:472) ~[?:?]
17:53:18   	at java.util.zip.ZipFile$Source.readFullyAt(ZipFile.java:1304) ~[?:?]
17:53:18   	at java.util.zip.ZipFile$ZipFileInputStream.initDataOffset(ZipFile.java:998) ~[?:?]
17:53:18   	at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:1013) ~[?:?]
17:53:18   	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:468) ~[?:?]
17:53:18   	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159) ~[?:?]
17:53:18   	at jdk.internal.loader.Resource.getBytes(Resource.java:124) ~[?:?]
17:53:18   	at java.net.URLClassLoader.defineClass(URLClassLoader.java:545) ~[?:?]
17:53:18   	at java.net.URLClassLoader$1.run(URLClassLoader.java:458) ~[?:?]
17:53:18   	at java.net.URLClassLoader$1.run(URLClassLoader.java:452) ~[?:?]
17:53:18   	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
17:53:18   	at java.net.URLClassLoader.findClass(URLClassLoader.java:451) ~[?:?]
17:53:18   	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
17:53:18   	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:899) ~[?:?]
17:53:18   	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
17:53:18   	... 34 more
```

certainly looks like disk/mem corruption but it is kind of unlikely for this to hit Netty classes multiple times I guess?
I initially thought it might have something to do with a version conflict (since in HDFS we have Netty 4.0.32 as a dep. as well, but that doesn't apply here either).

**Comment by original-brownbear** [comment] 2019-05-24 18:48
On the off chance that it's the dependency in some strange way ... upgrade to 4.1.36 in https://github.com/elastic/elasticsearch/pull/42543

**Comment by original-brownbear** [comment] 2019-05-25 03:57
Same exception though with a different classname trying to upgrade to Netty 4.1.36. https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/14703/console

```

23:20:54   [2019-05-24T21:20:53,790][WARN ][i.n.c.AbstractChannelHandlerContext] [integTest-0] An exception 'java.lang.NoClassDefFoundError: io/netty/util/internal/logging/AbstractInternalLogger$1' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
23:20:54   java.lang.NoClassDefFoundError: io/netty/util/internal/logging/AbstractInternalLogger$1
23:20:54   	at io.netty.util.internal.logging.AbstractInternalLogger.isEnabled(AbstractInternalLogger.java:53) ~[netty-common-4.1.36.Final.jar:4.1.36.Final]
23:20:54   	at io.netty.handler.logging.LoggingHandler.channelRegistered(LoggingHandler.java:140) ~[netty-handler-4.1.36.Final.jar:4.1.36.Final]
23:20:54   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:161) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
23:20:54   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:147) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
23:20:54   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:140) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
23:20:54   	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRegistered(DefaultChannelPipeline.java:1381) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
23:20:54   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:161) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
23:20:54   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:147) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
23:20:54   	at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:824) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
23:20:54   	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:518) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
23:20:54   	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:428) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
23:20:54   	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:487) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
23:20:54   	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.36.Final.jar:4.1.36.Final]
23:20:54   	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405) [netty-common-4.1.36.Final.jar:4.1.36.Final]
23:20:54   	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
23:20:54   	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) [netty-common-4.1.36.Final.jar:4.1.36.Final]
23:20:54   	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.36.Final.jar:4.1.36.Final]
23:20:54   	at java.lang.Thread.run(Thread.java:834) [?:?]
23:20:54   Caused by: java.lang.ClassNotFoundException: io.netty.util.internal.logging.AbstractInternalLogger$1
23:20:54   	at java.net.URLClassLoader$1.run(URLClassLoader.java:460) ~[?:?]
23:20:54   	at java.net.URLClassLoader$1.run(URLClassLoader.java:452) ~[?:?]
23:20:54   	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
23:20:54   	at java.net.URLClassLoader.findClass(URLClassLoader.java:451) ~[?:?]
23:20:54   	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
23:20:54   	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:899) ~[?:?]
23:20:54   	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
23:20:54   	... 18 more
23:20:54   Caused by: java.io.EOFException
23:20:54   	at java.io.RandomAccessFile.readFully(RandomAccessFile.java:472) ~[?:?]
23:20:54   	at java.util.zip.ZipFile$Source.readFullyAt(ZipFile.java:1304) ~[?:?]
23:20:54   	at java.util.zip.ZipFile$ZipFileInputStream.initDataOffset(ZipFile.java:998) ~[?:?]
23:20:54   	at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:1013) ~[?:?]
23:20:54   	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:468) ~[?:?]
23:20:54   	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159) ~[?:?]
23:20:54   	at jdk.internal.loader.Resource.getBytes(Resource.java:124) ~[?:?]
23:20:54   	at java.net.URLClassLoader.defineClass(URLClassLoader.java:545) ~[?:?]
23:20:54   	at java.net.URLClassLoader$1.run(URLClassLoader.java:458) ~[?:?]
23:20:54   	at java.net.URLClassLoader$1.run(URLClassLoader.java:452) ~[?:?]
23:20:54   	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
23:20:54   	at java.net.URLClassLoader.findClass(URLClassLoader.java:451) ~[?:?]
23:20:54   	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
23:20:54   	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:899) ~[?:?]
23:20:54   	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
23:20:54   	... 18 more
```

**Comment by henningandersen** [comment] 2019-05-27 13:35
One more somewhat similar:

```
14:14:21   [2019-05-27T12:14:21,560][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [integTest-0] fatal error in thread [main], exiting
14:14:21   java.lang.NoClassDefFoundError: org/elasticsearch/transport/netty4/ByteBufBytesReference
14:14:21   	at org.elasticsearch.transport.Netty4Plugin.<clinit>(Netty4Plugin.java:49) ~[?:?]
14:14:21   	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
14:14:21   	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
14:14:21   	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
14:14:21   	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
14:14:21   	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:609) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
14:14:21   	at org.elasticsearch.plugins.PluginsService.loadBundle(PluginsService.java:556) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
14:14:21   	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:471) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
14:14:21   	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:163) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
14:14:21   	at org.elasticsearch.node.Node.<init>(Node.java:312) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
14:14:21   	at org.elasticsearch.node.Node.<init>(Node.java:256) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
14:14:21   	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:219) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
14:14:21   	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:219) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
14:14:21   	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:339) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
14:14:21   	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
14:14:21   	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
14:14:21   	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
14:14:21   	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
14:14:21   	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
14:14:21   	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
14:14:21   	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
14:14:21   Caused by: java.lang.ClassNotFoundException: org.elasticsearch.transport.netty4.ByteBufBytesReference
14:14:21   	at java.net.URLClassLoader$1.run(URLClassLoader.java:460) ~[?:?]
14:14:21   	at java.net.URLClassLoader$1.run(URLClassLoader.java:452) ~[?:?]
14:14:21   	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
14:14:21   	at java.net.URLClassLoader.findClass(URLClassLoader.java:451) ~[?:?]
14:14:21   	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
14:14:21   	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:899) ~[?:?]
14:14:21   	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
14:14:21   	... 21 more
14:14:21   Caused by: java.io.EOFException
14:14:21   	at java.io.RandomAccessFile.readFully(RandomAccessFile.java:472) ~[?:?]
14:14:21   	at java.util.zip.ZipFile$Source.readFullyAt(ZipFile.java:1304) ~[?:?]
14:14:21   	at java.util.zip.ZipFile$ZipFileInputStream.initDataOffset(ZipFile.java:998) ~[?:?]
14:14:21   	at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:1013) ~[?:?]
14:14:21   	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:468) ~[?:?]
14:14:21   	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159) ~[?:?]
14:14:21   	at jdk.internal.loader.Resource.getBytes(Resource.java:124) ~[?:?]
14:14:21   	at java.net.URLClassLoader.defineClass(URLClassLoader.java:545) ~[?:?]
14:14:21   	at java.net.URLClassLoader$1.run(URLClassLoader.java:458) ~[?:?]
14:14:21   	at java.net.URLClassLoader$1.run(URLClassLoader.java:452) ~[?:?]
14:14:21   	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
14:14:21   	at java.net.URLClassLoader.findClass(URLClassLoader.java:451) ~[?:?]
14:14:21   	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
14:14:21   	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:899) ~[?:?]
14:14:21   	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
14:14:21   	... 21 more
14:14:21 Standard error of node `node{:modules:percolator:integTest-0}`
```

in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/14762/console

**Comment by original-brownbear** [comment] 2019-05-27 14:43
I think I found a bug in our classloading/way we set up Netty loggers in https://github.com/elastic/elasticsearch/pull/42591, not sure how this could actualize as an `EOFException` though.

**Comment by original-brownbear** [comment] 2019-06-01 06:54
Still running into this in (https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/15140/console) after #42591 and follow ups removing the static initializers we used in the Netty transport code => continuing to look into this.

**Comment by original-brownbear** [comment] 2019-06-01 14:18
@atorok maybe you have an idea here? The fact that we error out on an `EOFException` when loading Netty is hard to explain by anything but a broken jar getting bundled/loaded here somehow. I tried reproducing this in various environments but failed unfortunately, but maybe there's some issue with the custom task we use to copy the transport-netty4 module in integTests? 
Maybe if you have no idea either we could change the way we store build outputs to GCS and keep a copy of the dependency jars temporarily? With the frequency this is happening we shouldn't need long to get a reproducer to inspect the actual jars imo.

**Comment by original-brownbear** [comment] 2019-06-03 17:33
Or may e @mark-vieira you have an idea? :)

**Comment by mark-vieira** [comment] 2019-06-03 17:50
It's possible that we may be doing some kind of processing or token replacement on files which might be corrupting this JAR. Can we do a comparison on the extracted JAR in the testing distribution vs the original JAR and see if maybe we've mucked with it somehow?

**Comment by original-brownbear** [comment] 2019-06-03 17:53
> Can we do a comparison on the extracted JAR in the testing distribution vs the original JAR and see if maybe we've mucked with it somehow?

That was my idea in the above as well, but I think this will require a bit of infra work?
 Currently we're not storing the output jar's from builds long term right (that's all I can find in GCS at least)?

**Comment by mark-vieira** [comment] 2019-06-03 17:59
Is this only happening in _some_ PR builds or has anyone been able to reproduce this locally?

**Comment by original-brownbear** [comment] 2019-06-03 18:03
@mark-vieira I haven't hear from anyone experiencing this locally and yes it's inly happing in some PR builds.

**Comment by mark-vieira** [comment] 2019-06-03 23:46
This is happening with some regularity over the past month. I suspect there is something going on with parallel execution and perhaps some other task is touching those JARs. I suspect it's _something_ to do with how we deal with the integ-test distribution since that's what's common to all these projects where this seems to fail.

https://scans.gradle.com/s/ferny2m2wcgho
https://scans.gradle.com/s/n4aj3kbygxqns
https://scans.gradle.com/s/w6m35afvbhy56
https://scans.gradle.com/s/arty7cxvkiua4

Going to continue to dig into this.

**Comment by mark-vieira** [comment] 2019-06-05 00:57
I've pushed #42879 which hopefully should address this. Going to keep an eye on more build failures like this before closing this issue.

**Comment by mark-vieira** [comment] 2019-06-05 15:12
Had [another instance](https://scans.gradle.com/s/54s4z6jxbnndc/console-log?task=:modules:percolator:integTestRunner) of this even with the "fix". I'm quite certain it's still an issue with testclusters overriding the bundled integ-test netty JARs, just certain why it's still happening. Continuing to investigate.

**Comment by mark-vieira** [comment] 2019-06-05 17:00
Ok, my initial fix was insufficient. I'm _fairly_ confident_ #42900 will sort out the issue once merged.

**Comment by mark-vieira** [comment] 2019-06-05 20:36
Alright, changes from #42900 are in. Let's let that percolate out to everyone's branches and see if that clears up the issue.

**Comment by mark-vieira** [comment] 2019-06-10 17:31
We've not had an incidence of this in 4 days now so I think we can call this solved.

**Closed by mark-vieira** 2019-06-10 17:31 UTC
Labels: :Core/Infra/Build
