### ISSUE TITLE
Debian APT 2.x repo gives 404

### ISSUE THREAD

**Issue by ge-fa** [elastic/elasticsearch#26217] opened 2017-08-15 11:26 UTC
Hi,

`http://packages.elastic.co/elasticsearch/2.x/debian/dists/stable/main/binary-amd64/Packages` gives 404 currently. Is this intended?

Thanks,
Georg

**Comment by jasontedor** [comment] 2017-08-15 11:32
If you mean a simple HTTP request, it does not:

```bash
07:30:36 [jason@totoro:~] $ curl -I http://packages.elastic.co/elasticsearch/2.x/debian/dists/stable/main/binary-amd64/Packages
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 20231
Content-Type: text/plain; charset=UTF-8
Date: Tue, 15 Aug 2017 11:30:39 GMT
ETag: "e501c1d995926df684ed8102f9cf7055"
Last-Modified: Tue, 25 Jul 2017 12:42:10 GMT
Server: nginx/1.4.6 (Ubuntu)
x-amz-id-2: XLOupfJSe4RfBjtUrEN/8S0oTB1TzF9Xx+HbtaV83csbAfkvv9kqLLbIX5RHbiFWnENMtihhZ48=
x-amz-meta-md5: e501c1d995926df684ed8102f9cf7055
x-amz-request-id: 3019EC2B74D364BE
x-ngx-hostname: www04
Connection: keep-alive
```

Is this what you mean? If not, please provide steps to reproduce.

**Comment by jasontedor** [comment] 2017-08-15 13:34
Since the immediate link provided does not 404, and I was successfully able to test an apt-get install from the 2.x repository, I'm going to close this issue as can not reproduce. If you need additional help, please ask on the [forum](https://discuss.elastic.co). If there is indeed an issue here, we can reopen.

**Closed by jasontedor** 2017-08-15 13:34 UTC
Labels: feedback_needed

**Comment by ge-fa** [comment] 2017-08-15 14:30
@jasontedor Sorry for the noise, you're right. It was a problem with APT caching being done in my infrastructure.
