### ISSUE TITLE
Fields defined in _source return other fields too 

### ISSUE THREAD

**Issue by aliostad** [elastic/elasticsearch#26292] opened 2017-08-18 18:01 UTC
**Elasticsearch version**: 5.1.2
**Plugins installed**: x-pack
**JVM version**: 1.8.0_111
**OS version**: Linux myvmname 3.16.0-43-generic #58~14.04.1-Ubuntu SMP Mon Jun 22 10:21:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
If I define field `foobar` in the `_source` and my document has field `foo`, it will be returned. I find this happens if the content of the field is an array - but this is just an observation. Not sure how it could be related. 

**Steps to reproduce**:

``` JSON
POST sisyphus/life
{
  "stone" : ["large"],
  "stoneWeight" : [500]
}

POST sisyphus/life
{
  "stone" : ["small"],
  "stoneWeight" : [200]
}

GET sisyphus/_search
{
  "_source": "stoneWeight", 
  "query": {
    "match_all": {}
  }
}
```

Returns `stone` as well as `stoneWeight`:

``` JSON
{
  "took": 4,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 2,
    "max_score": 1,
    "hits": [
      {
        "_index": "sisyphus",
        "_type": "life",
        "_id": "AV32c1_JK9fID-KFUKqO",
        "_score": 1,
        "_source": {
          "stoneWeight": [
            500
          ],
          "stone": [
            "large"
          ]
        }
      },
      {
        "_index": "sisyphus",
        "_type": "life",
        "_id": "AV32c2hbK9fID-KFUKqP",
        "_score": 1,
        "_source": {
          "stoneWeight": [
            500
          ],
          "stone": [
            "large"
          ]
        }
      }
    ]
  }
}

```

**Comment by rjernst** [comment] 2017-08-18 23:16
I cannot reproduce this on master. Can you try on a more recent version of elasticsearch (say 5.5)?

**Comment by aliostad** [comment] 2017-08-19 11:39
I cannot reproduce on 5.4.

**Comment by jimczi** [comment] 2017-08-21 06:27
This is a duplicate of https://github.com/elastic/elasticsearch/issues/22557 which was fixed by  https://github.com/elastic/elasticsearch/pull/22593 in es 5.2.1

**Closed by jimczi** 2017-08-21 06:27 UTC

**Comment by aliostad** [comment] 2017-08-21 08:11
Thank you!
