### ISSUE TITLE
Aggregate results by query input params

### ISSUE THREAD

**Issue by reshadman** [elastic/elasticsearch#12592] opened 2015-08-03 05:52 UTC
I have two indexes, the first one called **areas** is an index containing of multiple polygons, and second one is an index containing of multiple **points** indicating  the document's lat/lon on earth, the index is called **stores**.

The problem is that I want to attach areas(polygons) that contain the **store's point** (lat/lon) inside of them, to the store's document as an embedded object. So I can easily find that a document on **stores** index has which areas.

In an **RDBMS** I was able to join this two table and find the needed records, In elasticsearch I can iterate over **areas** index documents one by one and perform a query to find the **stores** that fit in the **area's** polygon, and then perform an update on the **store** document, as the number of **areas** are huge, I have to perform over 50,000 queries on elasticsearch.

A good solution would be sending a bulk list of areas with the query and tell elasticsearch to aggregate returning results by them the answer would be something like this:

 - Polygon A : [store1, store2, store3],
 - Polygon B : [store1, store4, store5]

I didn't find anyway to implement this and I switched back to RDBMS solution which is not very optimized and fast too, but it is faster in design.

Is there anyway to implement this with elasticsearch?

I also planned for writing a plugin which does this functionality if it is not possible currently.

**Comment by colings86** [comment] 2015-08-03 07:52
This question is a duplicate of a post on the Discuss forums: https://discuss.elastic.co/t/aggregate-results-by-query-input/26692

Please stick to asking questions on the forums rather than this issues list which is for products issues rather than questions.

Joining across indices is not possible in Elasticsearch. Due to the distributed nature of Elasticsearch indices it joins do not scale well. This is why for parent/child documents we required the parent and child document to be located on the same shard, because joining across shards (or indices) in a distributed environment would not perform well

**Closed by colings86** 2015-08-03 07:52 UTC

**Comment by reshadman** [comment] 2015-08-05 10:59
Thanks @colings86 . I know I should post this kind of issues on forums, but I described my app specific  scenario to get better understanding of the elasticsearch related feature.

Anyway, I found a great feature which allows to reference polygons with their names on another index ([Pre index shapes](https://www.elastic.co/guide/en/elasticsearch/reference/1.6/query-dsl-geo-shape-filter.html#_pre_indexed_shape)) but there is not any option to aggregate results using this filter. Found a great plugin which has this functionality ( [elasticsearch-plugin-geoshap](https://github.com/opendatasoft/elasticsearch-plugin-geoshape) ).

Wouldn't it be nice to have aggregation on pre index shapes ?

**Comment by colings86** [comment] 2015-08-05 12:15
> Thanks @colings86 . I know I should post this kind of issues on forums, but I described my app specific scenario to get better understanding of the elasticsearch related feature.

This is exactly what the forums are for.

> Wouldn't it be nice to have aggregation on pre index shapes ?

You can already do this using the `geo_shape` filter with the `filters` aggregation.
