### ISSUE TITLE
[CI] DocsClientYamlTestSuiteIT test {yaml=reference/ccr/apis/follow/post-unfollow/line_33} failing

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#84889] opened 2022-03-10 21:30 UTC
### CI Link

https://gradle-enterprise.elastic.co/s/qcv575yh6wlqg

### Repro line

./gradlew ':docs:integTest' --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/ccr/apis/follow/post-unfollow/line_33}" -Dtests.seed=15CE56AD55BA2D5F -Dtests.locale=en -Dtests.timezone=Asia/Barnaul -Druntime.java=8	

### Does it reproduce?

No

### Applicable branches

7.17

### Failure excerpt

```
expected [2xx] status code but api [raw[method=PUT path=follower_index/_ccr/follow]] returned [400 Bad Request] [{"error":{"root_cause":[{"type":"connect_transport_exception"

[2022-03-11T03:51:01,382][INFO ][o.e.s.DocsClientYamlTestSuiteIT] [test] [yaml=reference/ccr/apis/follow/post-unfollow/line_33] before test	
[2022-03-11T03:51:31,497][INFO ][o.e.s.DocsClientYamlTestSuiteIT] [test] Stash dump on test failure [{	
  "stash" : {	
    "host" : "127.0.0.1:50050",	
    "body" : {	
      "error" : {	
        "root_cause" : [	
          {	
            "type" : "connect_transport_exception",	
            "reason" : "[][127.0.0.1:56544] connect_timeout[30s]",	
            "stack_trace" : "ConnectTransportException[[][127.0.0.1:56544] connect_timeout[30s]]	
	at org.elasticsearch.transport.TcpTransport$ChannelsConnectedListener.onTimeout(TcpTransport.java:1053)	
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:718)	
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)	
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)	
	at java.lang.Thread.run(Thread.java:748)	
"	
          }	
        ],	
        "type" : "status_exception",	
        "reason" : "can not fetch remote index [remote_cluster:leader_index] metadata as the license state of the remote cluster [remote_cluster] could not be determined",	
        "caused_by" : {	
          "type" : "exception",	
          "reason" : "could not determine the license type for cluster [remote_cluster]",	
          "caused_by" : {	
            "type" : "connect_transport_exception",	
            "reason" : "[][127.0.0.1:56544] connect_timeout[30s]",	
            "stack_trace" : "ConnectTransportException[[][127.0.0.1:56544] connect_timeout[30s]]	
	at org.elasticsearch.transport.TcpTransport$ChannelsConnectedListener.onTimeout(TcpTransport.java:1053)	
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:718)	
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)	
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)	
	at java.lang.Thread.run(Thread.java:748)
```

```
[2022-03-10T20:55:09,371][INFO ][o.e.c.m.MetadataDeleteIndexService] [node-0] [leader_index/oMRrzqCHS-G_IIzXn5N-Nw] deleting index
[2022-03-10T20:55:09,372][INFO ][o.e.c.m.MetadataDeleteIndexService] [node-0] [follower_index/Elov-hVOSaKNi2q8AV332g] deleting index
[2022-03-10T20:55:09,414][WARN ][o.e.p.PersistentTasksClusterService] [node-0] persistent task Elov-hVOSaKNi2q8AV332g-0 failed
org.elasticsearch.index.IndexNotFoundException: no such index [follower_index]
        at org.elasticsearch.xpack.ccr.action.ShardFollowTaskCleaner.clusterChanged(ShardFollowTaskCleaner.java:69) ~[?:?]
        at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListener(ClusterApplierService.java:573) ~[elasticsearch-7.17.2-SNAPSHOT.jar:7.17.2-SNAPSHOT]
        at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListeners(ClusterApplierService.java:559) ~[elasticsearch-7.17.2-SNAPSHOT.jar:7.17.2-SNAPSHOT]
        at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:519) ~[elasticsearch-7.17.2-SNAPSHOT.jar:7.17.2-SNAPSHOT]
        at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:428) ~[elasticsearch-7.17.2-SNAPSHOT.jar:7.17.2-SNAPSHOT]
        at org.elasticsearch.cluster.service.ClusterApplierService.access$000(ClusterApplierService.java:56) ~[elasticsearch-7.17.2-SNAPSHOT.jar:7.17.2-SNAPSHOT]
        at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:154) ~[elasticsearch-7.17.2-SNAPSHOT.jar:7.17.2-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:718) ~[elasticsearch-7.17.2-SNAPSHOT.jar:7.17.2-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:262) ~[elasticse
arch-7.17.2-SNAPSHOT.jar:7.17.2-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:225) ~[elasticsearch-7.1
7.2-SNAPSHOT.jar:7.17.2-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_301]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_301]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_301]
[2022-03-10T20:55:09,456][INFO ][o.e.c.s.ClusterSettings  ] [node-0] updating [cluster.remote.remote_cluster.seeds] from [["127.0.0.1:56544"]] to [[]]
[2022-03-10T20:55:09,456][INFO ][o.e.c.s.ClusterSettings  ] [node-0] updating [cluster.remote.remote_cluster.seeds] from [["127.0.0.1:56544"]] to [[]]
[2022-03-10T20:55:09,457][INFO ][o.e.c.s.ClusterSettings  ] [node-0] updating [cluster.remote.remote_cluster.seeds] from [["127.0.0.1:56544"]] to [[]]
[2022-03-10T20:55:09,458][INFO ][o.e.c.s.ClusterSettings  ] [node-0] updating [cluster.remote.remote_cluster.seeds] from [["127.0.0.1:56544"]] to [[]]
[2022-03-10T20:55:09,458][INFO ][o.e.c.s.ClusterSettings  ] [node-0] updating [cluster.remote.remote_cluster.seeds] from [["127.0.0.1:56544"]] to [[]]
[2022-03-10T20:55:09,459][WARN ][o.e.x.c.a.ShardFollowNodeTask] [node-0] shard follow task encounter non-retryable error
org.elasticsearch.transport.RemoteTransportException: [node-0][127.0.0.1:56544][indices:data/read/xpack/ccr/shard_changes]
Caused by: org.elasticsearch.index.IndexNotFoundException: no such index [leader_index]
        at org.elasticsearch.cluster.routing.RoutingTable.shardRoutingTable(RoutingTable.java:130) ~[elasticsearch-7.17.2-SNAPSHOT.jar:7.17.2-SNAPSHOT]
        at org.elasticsearch.xpack.ccr.action.ShardChangesAction$TransportAction.shards(ShardChangesAction.java:515) ~[?:?]
```
```

I tried to reproduce with runtime.java=17 and it did not fail locally

**Comment by arteam** [comment] 2022-03-22 13:38
https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=Europe/Berlin&tests.container=org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT&tests.sortField=FAILED&tests.test=test%20%7Byaml%3Dreference/ccr/apis/follow/post-unfollow/line_33%7D&tests.unstableOnly=true

**Comment by DaveCTurner** [comment] 2022-03-22 13:48
Although this one specific test seems not to have failed before, I count 6 recent failures matching `DocsClientYamlTestSuiteIT and ConnectTransportException`, all of which look like the same sort of problem.

- https://gradle-enterprise.elastic.co/s/dzmv24k5czfyg
- https://gradle-enterprise.elastic.co/s/mh5o4v54ev7c4
- https://gradle-enterprise.elastic.co/s/glwlimokiubys
- https://gradle-enterprise.elastic.co/s/f76b2cl2wctzm
- https://gradle-enterprise.elastic.co/s/sxnq2bcige3ns
- https://gradle-enterprise.elastic.co/s/qcv575yh6wlqg

**Comment by arteam** [comment] 2022-03-29 13:33
> Caused by: java.lang.NullPointerException: Cannot invoke \"org.elasticsearch.index.mapper.DocumentMapper.mapping()\" because the return value of \"org.elasticsearch.index.mapper.MapperService.documentMapper()\" is null

**Comment by arteam** [comment] 2022-04-19 11:47
I haven't been able to reproduce this issue reliably. The stats show that there might be some infra issue causing the `:docs:integTest` job to fail once at around thousand times. I'm going to close the issue because it's not caused the CCR tests.

**Closed by arteam** 2022-04-19 11:47 UTC
Labels: >test-failure, :Distributed/CCR, Team:Distributed
