### ISSUE TITLE
[CI] ConcurrentSeqNoVersioningIT testSeqNoCASLinearizability failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#91574] opened 2022-11-15 01:57 UTC
This has failed a few times this week with this same error.

**Build scan:**
https://gradle-enterprise.elastic.co/s/rwp6hp3ladauw/tests/:server:internalClusterTest/org.elasticsearch.versioning.ConcurrentSeqNoVersioningIT/testSeqNoCASLinearizability

**Reproduction line:**
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.versioning.ConcurrentSeqNoVersioningIT.testSeqNoCASLinearizability" -Dtests.seed=7865154887225253 -Dtests.locale=it-IT -Dtests.timezone=SystemV/AST4ADT -Druntime.java=17
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.versioning.ConcurrentSeqNoVersioningIT&tests.test=testSeqNoCASLinearizability

**Failure excerpt:**
```
org.elasticsearch.discovery.MasterNotDiscoveredException: (No message provided)

  at __randomizedtesting.SeedInfo.seed([7865154887225253:A3AB3B229D3070E7]:0)
  at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.onTimeout(TransportMasterNodeAction.java:316)
  at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:326)
  at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:264)
  at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:642)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:850)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by fcofdez** [comment] 2022-11-15 08:22
This is slightly different than https://github.com/elastic/elasticsearch/issues/90594. I'll take a look too.

**Comment by fcofdez** [comment] 2022-11-15 13:44
I'm closing this as a duplicate of https://github.com/elastic/elasticsearch/issues/90594

**Closed by fcofdez** 2022-11-15 13:44 UTC
Labels: >test-failure, :Distributed/Distributed, Team:Distributed
