### ISSUE TITLE
Disable query unless user specifies index and a field‏

### ISSUE THREAD

**Issue by abordia** [elastic/elasticsearch#10241] opened 2015-03-24 17:03 UTC
In my org, each team is creating ES index daily so the number of index grows very quickly.  Usually users are interested only in their 'team' data.  Currently, some users execute query using Kibana w/o specifying index and field name(it takes _all').   Such queries at times, bring our cluster to halt/ crash etc.  I would like queries to be restricted such that only well defined queries can be executed on ES.  A well defined query is a query which specifies index and field name.  I could not find a server level config param to enforce such constraint on user queries.  I posted question on ES forum but did not get a clear answer.

This bug/ ER filed to have ES server level parameter such as to enforce user defined queries to have index name and/ or field name specified.

**Comment by javanna** [comment] 2015-03-25 10:22
I think this is a duplicate of #6470. You can disable wildcard expansion at the moment, but only per request, which is not what you need. We would need to make this a global setting as described in #6470. Closing as a duplicate, feel free to reopen if I missed something.

**Closed by javanna** 2015-03-25 10:22 UTC
