### ISSUE TITLE
No reproduction info for LLREST tests

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#36368] opened 2018-12-07 14:51 UTC
When a low level rest client test fails it doesn't spit out reproduction information. This is probably because it needs to run in java 7 so it can't use our standard reproduction info printer. It should print out *something* though.

**Comment by javanna** [comment] 2018-12-07 15:56
This may just be because `RestClientTestCase` is missing the configuration for the reproduce info printer.  I probably forgot to add it at the time that I added the base test class. See the missing listeners section that `ESTestCase` has but `RestClientTestCase` does not have.

**Comment by dakrone** [comment] 2024-05-17 20:22
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.

**Closed by dakrone** 2024-05-17 20:22 UTC
Labels: >test, :Clients/Java Low Level REST Client, Team:Data Management
