### ISSUE TITLE
indexed script not properly updated when used for sort

### ISSUE THREAD

**Issue by schnittchen** [elastic/elasticsearch#10517] opened 2015-04-09 17:47 UTC
I index a groovy script and use it w/ script_score. Everything is fine.
I update the script (I used PUT below, but POST does the same) with a new script that should produce different values (constant, for the sake of demonstration). I get old values instead (values below are from an older atan2(1,1) version).

Same if I -XDELETE on the endpoint before POST/PUTing the new script.

Restarting elasticsearch makes the problem go away, until I change the script again.

```
 ~ ✓ curl -XPUT localhost:9200/_scripts/groovy/indexedCalculateScore -d '{"script": "atan2(1, 2)"}'
{"_id":"indexedCalculateScore","_version":24,"created":false} ~ ✓ 
 ~ ✓ curl http://localhost:9200/twitter/tweet/_search?pretty=true -d '
{ "query": {
  "function_score": {
    "query": {
      "match": {"message": "tweet"}
    },
    "boost_mode": "replace",
    "script_score":{
      "scriptId": "indexedCalculateScore",
      "lang":"groovy"}
    }
  }
}
'
{
  "took" : 11,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 0.7853982,
    "hits" : [ {
      "_index" : "twitter",
      "_type" : "tweet",
      "_id" : "2",
      "_score" : 0.7853982,
      "_source":
{
    "user": "kimchy",
    "postDate": "2009-11-15T14:12:12",
    "message": "Another tweet, will it be indexed?"
}
    } ]
  }
}


 ~ ✓ curl -XPUT localhost:9200/_scripts/groovy/indexedCalculateScore -d '{"script": "atan2(2, 1)"}'
{"_id":"indexedCalculateScore","_version":25,"created":false} ~ ~ ✓ curl http://localhost:9200/twitter/tweet/_search?pretty=true -d '
{ "query": {
  "function_score": {
    "query": {
      "match": {"message": "tweet"}
    },
    "boost_mode": "replace",
    "script_score":{
      "scriptId": "indexedCalculateScore",
      "lang":"groovy"}
    }
  }
}
'
{
  "took" : 6,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 0.7853982,
    "hits" : [ {
      "_index" : "twitter",
      "_type" : "tweet",
      "_id" : "2",
      "_score" : 0.7853982,
      "_source":
{
    "user": "kimchy",
    "postDate": "2009-11-15T14:12:12",
    "message": "Another tweet, will it be indexed?"
}
    } ]
  }
}
```

**Comment by javanna** [comment] 2015-04-10 09:00
this is caused by the same reason as #10397 . We are addressing it in #10526 .

**Comment by MaineC** [comment] 2015-04-23 09:16
As #10526 was merged I think this can be closed?

**Comment by javanna** [comment] 2015-04-23 19:23
agreed @MaineC go for it ;)

**Closed** 2015-04-24 07:14 UTC
Labels: :Indexed Scripts/Templates, bug
