### ISSUE TITLE
Build failed - a problem occurred evaluating project ':benchmarks'.

### ISSUE THREAD

**Issue by LululuAlu** [elastic/elasticsearch#66213] opened 2020-12-12 03:39 UTC
### ENV 
* OS = ubuntu18.04
* gradle=Gradle 5.2.1
* JAVA_HOME=jdk12
```
openjdk version "12" 2019-03-19
OpenJDK Runtime Environment (build 12+32)
OpenJDK 64-Bit Server VM (build 12+32, mixed mode, sharing)
```
* build command  = ` ./gradlew :assemble --parallel`
* version=Tag v6.8.0

### ERROR
``` * Where:
Build file '/mnt/d/develop/repertory1/elasticsearch/benchmarks/build.gradle' line: 20

* What went wrong:
A problem occurred evaluating project ':benchmarks'.
> Failed to apply plugin [id 'elasticsearch.build']
   >  {awt.toolkit=sun.awt.X11.XToolkit, java.specification.version=12, http.keepAlive=false, sun.jnu.encoding=UTF-8, sun.arch.data.model=64, java.vendor.url=https://java.oracle.com/, sun.boot.library.path=/mnt/d/develop/linux-jdk/jdk-12/lib, sun.java.command=org.gradle.launcher.daemon.bootstrap.GradleDaemon 5.2.1, jdk.debug=release, java.specification.vendor=Oracle Corporation, java.version.date=2019-03-19, java.home=/mnt/d/develop/linux-jdk/jdk-12, file.separator=/, java.vm.compressedOopsMode=32-bit, line.separator=
     , java.vm.specification.vendor=Oracle Corporation, java.specification.name=Java Platform API Specification, sun.management.compiler=HotSpot 64-Bit Tiered Compilers, java.runtime.version=12+32, user.name=root, file.encoding=UTF-8, java.io.tmpdir=/tmp, java.version=12, java.vm.specification.name=Java Virtual Machine Specification, java.library.path=/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib, java.vendor=Oracle Corporation, sun.io.unicode.encoding=UnicodeLittle, library.jansi.path=/root/.gradle/native/jansi/1.17.1/linux64, java.class.path=/root/.gradle/wrapper/dists/gradle-5.2.1-all/bviwmvmbexq6idcscbicws5me/gradle-5.2.1/lib/gradle-launcher-5.2.1.jar, java.vm.vendor=Oracle Corporation, user.variant=, user.timezone=Asia/Shanghai, java.vm.specification.version=12, os.name=Linux, user.country=, sun.java.launcher=SUN_STANDARD, sun.cpu.endian=little, user.home=/root, user.language=en, org.gradle.appname=gradlew, java.awt.graphicsenv=sun.awt.X11GraphicsEnvironment, path.separator=:, os.version=4.4.0-19041-Microsoft, java.runtime.name=OpenJDK Runtime Environment, java.vm.name=OpenJDK 64-Bit Server VM, java.vendor.url.bug=https://bugreport.java.com/bugreport/, user.dir=/mnt/d/develop/repertory1/elasticsearch, os.arch=amd64, java.vm.info=mixed mode, sharing, java.vm.version=12+32, java.class.version=56.0} JAVA_HOME must be set to build Elasticsearch. Note that if the variable was just set you might have to run `./gradlew --stop` for it to be picked up. See https://github.com/elastic/elasticsearch/issues/31399 details.
```
I have seen `https://github.com/elastic/elasticsearch/issues/31399`, and try to run `gradlew --stop` but useless.

**Comment by mark-vieira** [comment] 2020-12-18 20:34
I'm not able to reproduce this locally. Did you confirm that the `JAVA_HOME` environment variable is pointing to a valid JDK location?

**Comment by LululuAlu** [comment] 2020-12-28 02:34
> I'm not able to reproduce this locally. Did you confirm that the `JAVA_HOME` environment variable is pointing to a valid JDK location?

yes，command `java -version`  info as above.
OS `ubuntu18.04` was windows wsl1.  And I can assemble success at branch 7.9

**Comment by mark-vieira** [comment] 2021-01-29 03:09
Can you try running the build with `--scan` and sharing the resultant link?

**Comment by LululuAlu** [comment] 2021-01-29 05:30
ok，https://gradle.com/s/mj7wlctplinug

**Comment by mark-vieira** [comment] 2021-01-29 06:45
I noticed this:

```Linux 4.4.0-19041-Microsoft```

Are you using WSL or WSL2 perhaps?

**Comment by LululuAlu** [comment] 2021-02-01 02:33
WSL

**Comment by mark-vieira** [comment] 2021-02-01 22:05
I think you are going to run into all sort of potential issues here. We specifically don't support Elasticsearch via WSL so even if the build did run, you'd probably have other problems. I'm going to close this issue as we don't plan on adding support, although you might reach out on our [discussion forums](https://discuss.elastic.co/) to see if anyone else in the community is experimenting here.

**Closed by mark-vieira** 2021-02-01 22:05 UTC
Labels: :Delivery/Build, >bug, Team:Delivery
