### ISSUE TITLE
Provide access to filter cache use via stats

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#11987] opened 2015-07-02 04:12 UTC
Given [we track filter cache use](https://github.com/elastic/elasticsearch/issues/8449), is there anyway we can provide stats around what filter caches are in use and what that use looks like?

**Comment by markwalkom** [comment] 2015-07-02 04:14
Was asked by @sl1pm4t in training :)

**Comment by clintongormley** [comment] 2015-07-02 11:53
Closing as duplicate of #9558

**Closed by clintongormley** 2015-07-02 11:53 UTC
