### ISSUE TITLE
geo_shape matches shapes outside polygon

### ISSUE THREAD

**Issue by ptpt** [elastic/elasticsearch#31048] opened 2018-06-03 11:07 UTC
**Elasticsearch Version** (`bin/elasticsearch --version`): 6.2.4

**Plugins installed**: []

**JVM version** (`java -version`): run in docker

**OS version** (`uname -a` if on a Unix-like system): run in docker

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

 1. `docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:6.2.4`
 2. create the mapping
```
curl localhost:9200/tweets -d '
{
    "mappings": {
        "_doc": {
            "properties": {
                "location": {
                    "type": "geo_shape"
                }
            }
        }
    }
}' -XPUT -H 'Content-Type:application/json'
```
 3. create the doc located in Sweden
```
curl "localhost:9200/tweets/_doc?refresh" -d '
{
    "name": "Wind & Wetter, Berlin, Germany",
    "location": {
        "type": "point",
        "coordinates": [15.120892, 63.431233]
    }
}' -H 'Content-Type:application/json'
```

4. query docs within Norway, the doc located in Sweden appears in the hits
```
curl "localhost:9200/tweets/_search" -d@query.json -H 'content-type: application/json'
```

**Provide logs (if relevant)**:

[query.json.zip](https://github.com/elastic/elasticsearch/files/2065890/query.json.zip)

Shape of Norway: https://gist.github.com/ptpt/73d0ffe353226283ccd1c7768b932445

**Comment by DaveCTurner** [comment] 2018-06-04 08:59
Elasticsearch yields some [false positives](https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-shape.html#_accuracy) for queries like this, and the accuracy is a function of the size of the whole shape. In this case the shape of "Norway" includes Svalbard and Bouvetøya and is therefore about 15000km across, but the error in this query is ~85km, which is around 0.5% of the total size:

<img width="656" alt="screen shot 2018-06-04 at 09 39 08" src="https://user-images.githubusercontent.com/5058284/40907906-1bcc1c2c-67dd-11e8-86ee-43b3aadf3c46.png">

#27954 looks to be a similar issue.

**Comment by imotov** [comment] 2018-12-13 15:58
This seems to be a duplicate of #27954, so I am going to close it.

**Closed by imotov** 2018-12-13 15:58 UTC
Labels: :Analytics/Geo, >bug
