### ISSUE TITLE
[CI] buildDockerImage fails when installing unzip

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#40205] opened 2019-03-19 13:40 UTC
This has happened a couple of times recently

```
Step 6/28 : RUN yum install -y unzip which
 ---> Running in 30a274ee68c6
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
[91m

 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=<repoid> ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>
        or
            subscription-manager repos --disable=<repoid>

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot find a valid baseurl for repo: base/7/x86_64
[0mCould not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container error was
12: Timeout on http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds')
The command '/bin/sh -c yum install -y unzip which' returned a non-zero code: 1


FAILURE: Build failed with an exception.

> Task :distribution:docker:buildDockerImage FAILED
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=java8,nodes=immutable&&linux&&docker/47/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.7+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=zulu11,nodes=immutable&&linux&&docker/82/console

**Comment by dliappis** [comment] 2019-03-20 15:12
Related to https://github.com/elastic/elasticsearch/issues/38832

**Comment by dliappis** [comment] 2019-03-20 15:28
Closing as duplicate of #38832

**Closed by dliappis** 2019-03-20 15:28 UTC
Labels: :Core/Infra/Build, >test-failure, PITA
