### ISSUE TITLE
More graceful handling of failure in DescribeInstances (ec2-discovery)

### ISSUE THREAD

**Issue by azsolinsky** [elastic/elasticsearch#28452] opened 2018-01-31 03:05 UTC
If the DescribeInstances call fails from the EC2 Discovery plugin for any reason, the code just returns an empty list of nodes.  ~~This is bad because the code currently caches it until the refresh interval expires.~~ This is bad because the code uses the empty list of nodes immediately, and will try to make the call again on the next get, which potentially doesn't include any retry back-off.

https://github.com/elastic/elasticsearch/blob/139deb535a58de87c602888a121b2791bcd22df2/plugins/discovery-ec2/src/main/java/org/elasticsearch/discovery/ec2/AwsEc2UnicastHostsProvider.java#L106:L119

~~With the default refresh of 10s this is sometimes not catastrophic; however, if throttling is happening a lot it can potentially cause the masters to not be able to communicate with one another and lead to cluster instability. ~~

~~Also, with this bug, increasing the refresh interval is dangerous because the empty results list is cached until the refresh interval expires.~~ The code should probably not return empty list if it is being throttled and continue to use the list from the last successful call, or possibly retry more with exponential back-off for throttling exceptions.

**Comment by ywelsch** [comment] 2018-02-06 14:09
@azsolinsky How did you determine for this to be the cause? Looking at `DiscoNodesCache`, which is the class that does the caching, it seems to account for the empty list. If the returned list is empty, no caching should be happening. The only possible fault I can find with the `DiscoNodesCache` class is that the `empty` variable might not be concurrency-safe.

**Comment by azsolinsky** [comment] 2018-02-07 17:24
Ok, how did you determine no caching is happening if it returns an empty list?

https://github.com/elastic/elasticsearch/blob/139deb535a58de87c602888a121b2791bcd22df2/plugins/discovery-ec2/src/main/java/org/elasticsearch/discovery/ec2/AwsEc2UnicastHostsProvider.java#L239

https://github.com/elastic/elasticsearch/blob/139deb535a58de87c602888a121b2791bcd22df2/server/src/main/java/org/elasticsearch/common/util/SingleObjectCache.java#L49

If empty list is returned the SIngleObjectCache will certainly cache it; why do you think it will not cache the empty list?

**Comment by rjernst** [comment] 2018-02-07 22:57
@azsolinsky The `empty` variable is set if the returned list is empty, which means `needsRefresh()` will always return `true`.

**Comment by azsolinsky** [comment] 2018-02-08 00:31
Ok. Won't it still use the empty list for that call though as opposed to using the last good response? Suppose it stays throttled for 30 seconds?

On Feb 7, 2018, at 2:59 PM, Ryan Ernst <notifications@github.com<mailto:notifications@github.com>> wrote:


@azsolinsky<https://github.com/azsolinsky> The empty variable is set if the returned list is empty, which means needsRefresh() will always return true.

-

**Comment by azsolinsky** [comment] 2018-02-08 00:32
Also that means there is a potential issue with retrying the call too much without exponential back off.

Jeff S

On Feb 7, 2018, at 2:59 PM, Ryan Ernst <notifications@github.com<mailto:notifications@github.com>> wrote:


@azsolinsky<https://github.com/azsolinsky> The empty variable is set if the returned list is empty, which means needsRefresh() will always return true.

-

**Comment by rjernst** [comment] 2018-02-08 02:21
I'm not saying the current behavior is good or correct, just that it will not "cache the empty list" as was originally stated in this issue.

**Comment by azsolinsky** [comment] 2018-02-08 02:27
Ok, your point is taken. I took for granted that needsRefresh was being overridden, and thought it would not refresh on a second call. I updated the title. However, I think the behavior during throttling still needs to be addressed to protect the service from spikes calling the describe instance call API in the case of throttling.

**Comment by rjernst** [comment] 2018-02-09 23:27
@azsolinsky I've marked this as an `adoptme`. Do you have any interesting in working on a PR?

**Comment by azsolinsky** [comment] 2018-02-12 16:16
I have interest, but I'm not sure about my availability; I'll have to get back on it in the near future.

**Comment by henningandersen** [comment] 2019-03-19 17:14
@azsolinsky thanks for your interest in improving elasticsearch. We discussed this internally and do not currently intend to work on this in the foreseeable future. I will therefore close this issue. If you still have an interest in improving this, feel free to open a pull request for it.

**Closed by henningandersen** 2019-03-19 17:14 UTC
Labels: :Distributed/Discovery-Plugins, >enhancement, help wanted
