### ISSUE TITLE
Bulk queue size appears much bigger than the configured queue size

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#15101] opened 2015-11-30 10:12 UTC
1. es version: 1.7.0
2. cluster: 3 dedicated master nodes, 10 data nodes
3. bulk.threadpool type: fix, thread size: 32, queue size: 30

under heavy write, marvel tell that bulk queue size is over 1.5k. why is it over my setting?

**Comment by clintongormley** [comment] 2015-11-30 10:17
@makeyang could you paste the output of these requests (when under heavy write load):

    GET _nodes/thread_pool
    GET _nodes/stats/thread_pool

This will help us to see whether it is Elasticsearch or Marvel at fault.

**Comment by makeyang** [comment] 2015-11-30 10:36
@clintongormley 
GET _nodes/thread_pool:
https://github.com/makeyang/grocery/blob/master/_nodes-thread_pool.txt
GET _nodes/stats/thread_pool:
https://github.com/makeyang/grocery/blob/master/_nodes-stats-thread_pool.txt

**Comment by clintongormley** [comment] 2015-11-30 11:09
@makeyang currently your nodes stats are showing nothing in the bulk queues, just a number of previous rejections.  Please repost these stats when you are seeing active rejections.

**Comment by makeyang** [comment] 2015-12-02 10:36
@clintongormley  I updated files
GET _nodes/thread_pool:
https://github.com/makeyang/grocery/blob/master/_nodes-thread_pool.txt
GET _nodes/stats/thread_pool:
https://github.com/makeyang/grocery/blob/master/_nodes-stats-thread_pool.txt

u can see that set  thread pool size is 30 and I posted stats file, there are some nodes pool size is over 30.

**Comment by clintongormley** [comment] 2015-12-02 12:22
I still don't understand.  According to the data you've posted, your bulk threadpools are configured as follows:

            "bulk": {
               "type": "fixed",
               "min": 48,
               "max": 48,
               "queue_size": "30"
            },

And the bulk queue is currently empty, although you have had many rejections:

            "bulk": {
               "threads": 48,
               "queue": 0,
               "active": 30,
               "rejected": 7352,
               "largest": 48,
               "completed": 145157
            },


Are you not confusing rejections with the queue size?

Could you paste a screenshot of Marvel showing what you think is an error?

**Comment by makeyang** [comment] 2015-12-03 01:20
@clintongormley 
look at the node nRDJU5LjRRi3U2TK1ndJ3g 
 "bulk": {
               "threads": 48,
               "queue": 57,
               "active": 48,
               "rejected": 24547,
               "largest": 48,
               "completed": 140952
            },
the queue is 57

**Comment by makeyang** [comment] 2015-12-04 01:19
anybody can take a look at this issue?

**Comment by bleskes** [comment] 2015-12-04 09:19
@makeyang the bulk queues sizes are intended to back pressure incoming operations on the primary (and thus to the client). Once an operation gets in the primary, we have to make sure it is also indexed on the replicas. As such, we insert these operations to the bulk queues on nodes with replicas, even if the queue is "over capacity". 

I also noted that the thread size is not what you asked.  I think you use `thread_size` and not just `size` in your config, but that's just guess work.

Closing for now as it is "by design". Let me know if you have any questions.

**Closed by bleskes** 2015-12-04 09:19 UTC
Labels: :Stats, feedback_needed

**Comment by makeyang** [comment] 2015-12-07 01:30
if it is by desing, then it is design by simple, not design be reasonable.
with the queue over capacity, it is easy to cause memory issue, GC issue, cluster state unstaybility.
Hope u guys can make progress on this spot ASAP.

**Comment by sunyonggang** [comment] 2016-01-26 06:10
i'm sorry, but i met the same problem.
1: es version 1.4.4, with 5 nodes. use the default bulk queue_size(50)
when i upload about 2k message, ES can only get 1.8k, after detection, i get the bulk response with every message, like this:
```
{"index":{"_index":"name@2015-12-12","_type":"vn","_id":"b01c65c7dab6094b4cb099451c47c474b86228ef9b0d53f8b90f625c42e485da","status":429,"error":"RemoteTransportException[[ali-tsi-0b-svg-p-01-svm-a-009][inet[/10.144.210.10:9300]][indices:data/write/bulk[s]]]; nested: EsRejectedExecutionException[rejected execution (queue capacity 50) on org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1@23deb51c]; "}}
```
so i want to find a solution to it. so how to configure the specified number of the bulk queue_size? can i just choose 500 or 1000?
these will be helpful
```
"bulk" : {
          "type" : "fixed",
          "min" : 4,
          "max" : 4,
          "queue_size" : "50"
        },

"bulk" : {
          "threads" : 4,
          "queue" : 0,
          "active" : 0,
          "rejected" : 1137,
          "largest" : 4,
          "completed" : 14785507
        },
```
👻

**Comment by clintongormley** [comment] 2016-01-26 12:28
@sunyonggang the right place to ask questions like these is the forum: http://discuss.elastic.co/

Short answer: you either need to slow down on how fast you're sending data, or increase the indexing capacity of the structure by adding more nodes or better disks.

**Comment by eherot** [comment] 2018-04-19 17:59
@bleskes I apologize for resurrecting such an old thread, but I seem to have run into an issue related to the queue "over capacity" behavior you described above. Do you know if there is any further documentation on this logic? I had a cluster go down because my coordinator nodes ran out of heap space and I suspect an excessively high number of messages in the work queue may have been to blame (data in prometheus shows that there were, at one point, over 3,000 messages in the queue even though the "limit" was still set to 200).

Thanks for any help you can provide! I will also post this question to the forums.

**Comment by bleskes** [comment] 2018-04-19 19:42
@eherot np. Please post to the forums so we can research further. OOM can be multiple things. Please make sure you post your exact ES version number and a short description of what kind if indexing requests you uses. If you had a heap dump, a summary / screenshot of the biggest memory consumers always help.

**Comment by Bukhtawar** [comment] 2019-12-29 06:10
@bleskes  Once the bulk sub-request is enqueued onto replica will it have it's entry removed from the primary node's queue and hence allowing it to take in further requests. Could there be cases where a slow replica can bump up memory pressure on primary if primary continues to take in requests while still holding onto unprocessed replication requests.
