### ISSUE TITLE
Ability to define sniffing for Client Nodes only

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/elasticsearch#28155] opened 2018-01-09 19:46 UTC
@javanna please let me know your thoughts here.

Right now if you want to allow an application to use Client Nodes only, you need to define the nodes in the connection settings for the Client. If you add sniffing, you  will be able to sniff any node and you could use the `sniffHosts` option to sniff just client nodes from an external source.

If you want to have a dynamic pool of nodes (client only nodes) that when you add a new client node to a cluster, that node is added to the connection pool, but when you add master or data nodes, those aren't used, one of the ways that people would do that is by using an external Load Balancer.

I think that it will be great for the Java REST client to be able to have a way to **sniff client-only** nodes.

The current Transport Client doesn't do that, and actually just retrieves a list of data nodes. The reason the transport client excludes non-data nodes is to avoid sending search traffic to master only nodes (from the docs).

What do you think?

**Comment by dadoonet** [comment] 2018-01-09 20:00
Or ingest nodes? I mean it could be nice to be able to filter nodes by just giving some filtering properties. Could be a rack name, a region, a tag...

**Comment by gmoskovicz** [comment] 2018-01-09 20:01
++ @dadoonet

**Comment by javanna** [comment] 2018-01-16 13:50
makes sense, closing as duplicate of #21888.

**Closed by javanna** 2018-01-16 13:50 UTC
Labels: :Java REST Client, enhancement
