### ISSUE TITLE
Test on JDK 16 EA

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#63900] opened 2020-10-19 18:20 UTC
We need to add testing in CI for JDK 16 EA releases. We should also document the process, so that in the future when a JDK is released, we have a process for not only bumping the bundled jdk, but also adding the next EA release.

**Comment by mark-vieira** [comment] 2020-12-18 07:52
Duplicate of #66274 which is in-progress.

**Closed by mark-vieira** 2020-12-18 07:52 UTC
Labels: :Delivery/Build, Team:Delivery
