### ISSUE TITLE
Reassigning aliases to the newly created indexes using Aliases API (Java Client)

### ISSUE THREAD

**Issue by andremrezende** [elastic/elasticsearch#17572] opened 2016-04-06 19:34 UTC
Hi folks, I´m using ES 1.7.3 and client Java the same version.

The alias API accept a list of add/remove actions which are executed atomically in one call. Java-wise you can do the following:

```java
client.admin().indices().prepareAliases().removeAlias("old_index", "my_alias").addAlias("new_index", "my_alias").execute().actionGet();
```

But, in a short time, the other client request a new search on ES and the Exception `[my_alias] missing` happens. What can I do to fix it?

Thanks,
André Rezende

**Comment by dadoonet** [comment] 2016-04-07 10:01
@andremrezende Thank you for reporting this.
Is this something you can reproduce with a Java test?

Could you share the full code?

Asking that because IMO this is not supposed to happen.
The `client` is not aware that the configuration on the server has changed. Or may be you are using a NodeClient which could potentially explain this?

So any information you could add would help a lot.

And BTW, are you seeing that with elasticsearch 2.3?

**Comment by andremrezende** [comment] 2016-04-07 11:03
The method to add alias is:
    `private void addAlias(final IndicesAdminClient indices, final String indexName, long cdCatalog) throws DBRElasticsearchException {
    	IndicesAliasesResponse aliasReponse = null;
    	try {
    		//Removes the alias from the old index at the same time as we add it to the new index. The change needs to be atomic.
    		if(lastIndexName!=null && !"".equals(lastIndexName)) {
    			aliasReponse = indices.prepareAliases().removeAlias(lastIndexName, ALIAS.PRODUCTS.toString(cdCatalog)).addAlias(indexName, ALIAS.PRODUCTS.toString(cdCatalog)).execute().actionGet();
    			//indices.prepareAliases().removeAlias(lastIndexName, ALIAS.PRODUCTS.toString(cdCatalog)).execute();
    		} else {
    			aliasReponse = indices.prepareAliases().addAlias(indexName, ALIAS.PRODUCTS.toString(cdCatalog)).execute().actionGet();
    		}
    		if (aliasReponse!=null && !aliasReponse.isAcknowledged()) {
    			throw new DBRElasticsearchException("Alias: %s error to create: " + ALIAS.PRODUCTS.toString(cdCatalog));
    		}
		} catch (InvalidAliasNameException e) {
	             ...
		}
    }`
The indices parameter is loading on constructor method and shared with other methods.

Thanks in advanced,
André Rezende

**Comment by dadoonet** [comment] 2016-04-07 11:05
What kind of client are you using?

**Comment by andremrezende** [comment] 2016-04-07 11:06
The property type is: IndicesAdminClient

**Comment by dadoonet** [comment] 2016-04-07 11:41
I might be unclear.

How do you build this client please?

**Comment by andremrezende** [comment] 2016-04-07 11:48
`Settings settings = ImmutableSettings.settingsBuilder()
						.put("cluster.name", prop.getProperty("clusetername"))
						.put("client.transport.ping_timeout", "100s")
						.put("client.transport.sniff", true)
						.put("discovery.zen.ping.multicast.enabled", false)
						.put("discovery.zen.ping.unicast.enabled", true)
						.put("discovery.zen.multicast.enabled", false)
						.put("discovery.zen.unicast.enabled", true).build();
 client = new TransportClient(settings);
 client.addTransportAddress(new InetSocketTransportAddress(
							'IP_ADDRESS', 9300));`

**Comment by dadoonet** [comment] 2016-04-07 11:57
Ok. So it's a `TransportClient`. So I don't understand how this can happen.

Are you able to reproduce this in a test case?
Also, can you reproduce with 2.x version?

Asking that because lot of changes have been done in the meantime in 2.x series. For example #11930 might fix what you described.

**Comment by andremrezende** [comment] 2016-04-07 12:06
So, I tried to reproduce it using a test case, but I was not able to get exceptions, just on prodction enviroment. :(
I did NOT upgrade my ES to 2 because the java api lib is different, and I must change the source code.
I would like to see any document or reference about this upgrade, change the ES server is easier, but the ES client I don´t think so.

thanks

**Comment by dadoonet** [comment] 2016-04-07 14:24
> change the ES server is easier

Well. It depends. You will have to check what the migration plugin says and also go through all the braking changes.

> but the ES client I don´t think so.

Yes and no. It depends on the result of what I just said ^^^ 

> So, I tried to reproduce it using a test case, but I was not able to get exceptions, just on prodction enviroment. :(

May be you are doing things a bit differently than in your use case?

**Comment by andremrezende** [comment] 2016-04-07 15:25
There are 2 systems, an ERP to update data in ES and another system to "consume" data. The exception occurs on consumer when the ERP is removing and adding alias on the same time.

**Comment by dadoonet** [comment] 2016-06-30 06:56
I'm going to close this one. I believe it has been fixed in 2.x with #11930 TBH. 
If you can come with a test, like a load test which change aliases all the time in a process and query the alias in another process and fails, that could be awesome.
Even more, if you can do it in 1.7 then upgrade to 2.3 and check that it does not occur anymore... That'd be fantastic.

Feel free to reopen or comment if you have any more information.

**Closed by dadoonet** 2016-06-30 06:56 UTC
