### ISSUE TITLE
Memory calculation error

### ISSUE THREAD

**Issue by yjiu1990** [elastic/elasticsearch#50492] opened 2019-12-25 08:17 UTC
Free memory is not total-free, it should be total- (free + buff/cache) = used mem，this is real memory
<img width="687" alt="E1CB64E8-26E1-4B4C-9E8F-5A712A8536B1" src="https://user-images.githubusercontent.com/41354304/71438786-0b521c00-2732-11ea-83a3-f29377709c62.png">

**Comment by rjernst** [comment] 2020-01-07 02:38
@yjiu1990 Could you please explain a little more about what you would expect to offset from free memory? I believe you mean buffers like those used in search requests or static objects living for the life of the Elasticsearch process, but these would be very difficult to ascertain accurate sizes.

**Comment by yjiu1990** [comment] 2020-01-07 05:53
I want to get the actual memory used in the machine, otherwise the memory calculated in this way will be of little use, because according to the current monitoring data, the memory utilization is 99%, but half of the actual memory will be put in the buff/cache first

**Comment by rjernst** [comment] 2020-01-07 18:42
Can you describe more what you mean by "buff/cache"? Is it the java persistent java objects I described, or do you mean the operating system's caches/buffers? We use java's OS mxbean to get the total/free memory, and it does not provide any way to find the sizes of the latter:
https://docs.oracle.com/javase/7/docs/jre/api/management/extension/com/sun/management/OperatingSystemMXBean.html

**Comment by yjiu1990** [comment] 2020-01-08 06:26
I understand, because there are some differences in the memory calculation of Linux, the memory rate is generally (total-memavailable)/total or (total – free - buffers - cached) / total. If you use mxbean, the monitoring data displayed will be shown as shown in the figure. In fact, you don't use so much
![image](https://user-images.githubusercontent.com/41354304/71955287-d5796100-3222-11ea-844c-7528191464b6.png)

**Comment by yjiu1990** [comment] 2020-01-08 06:27
![image](https://user-images.githubusercontent.com/41354304/71955344-fb066a80-3222-11ea-9086-9925a1845a30.png)

**Comment by rjernst** [comment] 2020-01-08 18:17
We do use the mxbean I mentioned, so that is all the information we can get. We discussed this as a team and don't see a way to get at what you want without adding native code, which we try to stay away from as often as possible. We recommend working with tools in your system to limite/manage the buffers and cache size outside of ES if you are concerned about the reporting being high. Since we see this as not a bug, I hope you don't mind that I close this issue.

**Closed by rjernst** 2020-01-08 18:17 UTC
Labels: :Core/Infra/Core
