### ISSUE TITLE
pipeline agg could return value of a not-exists buckets_path

### ISSUE THREAD

**Issue by chenryn** [elastic/elasticsearch#15707] opened 2015-12-30 09:40 UTC
Percentiles metric aggregtaion returns a multi-value result. And I know I can write `buckets_path` for multi-value like `bucketsname.metricname`.

But, the key of percentiles metric agg result is named like 50.0, 90.0, those also use DOT!

I try to delete the `.0`, and find something other more interesting: pipeline agg can return values of a not-exists `buckets_path`.

Here is my request:

```
{
  "aggs" : {
    "my_date_histo" : {
      "date_histogram" : {
        "field" : "@timestamp",
        "interval" : "1h"
      },
      "aggs" : {
        "pcttime" : {
        "percentiles" : { "field" : "num_field" }
        },
        "the_movavg45" : {
          "moving_avg" : {
            "buckets_path" : "pcttime.45",
            "window" : 10,
            "model" : "simple"
          }
        },
        "the_movavg50" : {
          "moving_avg" : {
            "buckets_path" : "pcttime.50",
            "window" : 10,
            "model" : "simple"
          }
        }
      }
    }
  }
}
```

And the result:

```
"aggregations" : {
    "my_date_histo" : {
      "buckets" : [ {
        "key_as_string" : "2015-12-24T02:00:00.000Z",
        "key" : 1450922400000,
        "doc_count" : 1462,
        "pcttime" : {
          "values" : {
            "1.0" : 8.61,
            "5.0" : 50.0,
            "25.0" : 259.7801169590643,
            "50.0" : 506.6208791208792,
            "75.0" : 752.2619047619047,
            "95.0" : 946.6333333333332,
            "99.0" : 994.0
          }
        }
      }, {
        "key_as_string" : "2015-12-24T03:00:00.000Z",
        "key" : 1450926000000,
        "doc_count" : 13077,
        "pcttime" : {
          "values" : {
            "1.0" : 10.25333333333333,
            "5.0" : 52.61263736263737,
            "25.0" : 253.4788589832068,
            "50.0" : 501.97747099662007,
            "75.0" : 752.0346378551421,
            "95.0" : 949.8349473684209,
            "99.0" : 988.0
          }
        },
        "the_movavg45" : {
          "value" : 466.2075
        },
        "the_movavg50" : {
          "value" : 506.6208791208792
        }
      }, {
```

There are no 45( nor 45.0) in `pcttime.values` of percentiles metric aggregation. How can the pipeline got the value of `pcttime.45`?

**Comment by clintongormley** [comment] 2016-01-10 18:14
@colings86 could you take a look please?

**Comment by colings86** [comment] 2016-01-11 10:26
This is a quirk of the percentiles and percentile_ranks aggregations. The underlying algorithms that calculates the percentile values (TDigest and HDRHistogram) do this by storing a histogram which can be queried for any value, not just the values asked for in the request. The `metricname` in the buckets_path is passed directly to the algorithm to return a result so the buckets_path will get a result for any percentile value (between 0 and 100). I guess this is technically a bug but IMO its not a bug that really causes any harm (hence why I called it a quirk at the start of this comment) so I am wary of adding in extra code to protect against something that doesn't really cause a problem (maybe others have a different view on this?). 

Incidently, to access percentile values with a dot in them (e.g. 99.9th percentile) you can use square bracket notation like this:

```
"buckets_path" : "pcttime[99.9]",
```

**Comment by chenryn** [comment] 2016-01-13 02:45
Thank you, and I think it's a good hidden feature for percentiles and percentile_ranks aggregations.
Maybe more good if describe the percentiles feature and square bracket style of `bucket_path` in doc.

**Comment by clintongormley** [comment] 2016-03-01 08:55
Documentation about the alternate buckets_path syntax has been added.  Closing

**Closed by clintongormley** 2016-03-01 08:55 UTC
Labels: :Aggregations, discuss
