### ISSUE TITLE
'no such index' exception when index.mapper.dynamic: false

### ISSUE THREAD

**Issue by robth** [elastic/elasticsearch#17561] opened 2016-04-06 14:30 UTC
**Elasticsearch version**: 2.3.0

**JVM version**: Oracle 1.8.0_60 x86_64

**OS version**: CentOS 6.7 (Final)

**Description of the problem including expected versus actual behavior**:
I have an index template that matches template `persons*`:

```
{
    "order" : 0,
    "template" : "persons*",
    "settings" : {
        "index" : {
            "number_of_shards" : "1",
            "number_of_replicas" : "0"
        }
    },
    "mappings" : {
        "person" : {
            "dynamic" : "strict",
            "_all" : {
                "enabled" : false
            },
            "properties" : {
                "name" : {
                    "index" : "not_analyzed",
                    "type" : "string"
                }
            }
        }
    }
}
```

I index a document into an index `persons-1970-01-01`:

```
{
    "name" : "Henk"
}
```

Before 2.3.0, the new index would be created with the supplied document. With 2.3.0 it doesn't work any longer. The response is:

```
{
    "error": {
        "root_cause": [
            {
                "type": "index_not_found_exception",
                "reason": "no such index",
                "resource.type": "index_expression",
                "resource.id": "persons-1970-01-01",
                "index": "persons-1970-01-01"
            }
        ],
        "type": "index_not_found_exception",
        "reason": "no such index",
        "resource.type": "index_expression",
        "resource.id": "persons-1970-01-01",
        "index": "persons-1970-01-01"
    },
    "status": 404
}
```

See below for ES stacktrace.

**Steps to reproduce**:
1. Make sure you have `index.mapper.dynamic: false` configured in your `config/elasticsearch.yml` file.
2. Create the template: `curl -s -XPUT localhost:13011/_template/my-template -d@persons-template.json`. This should work.
3. Index the doc: `curl -s -XPUT localhost:13011/persons-1970-01-01/person/henk -d@person-doc.json`. You'll get the above mentioned error.
4. Now, comment the `index.mapper.dynamic: false` setting.
5. Repeat steps 2 and 3, but this time, the doc will be indexed as expected.

**Provide logs (if relevant)**:
Elasticsearch stacktrace when indexing the doc with `index.mapper.dynamic: false`:
```
[2016-04-06 16:11:06,386][WARN ][action.index             ] [rob] unexpected error during the primary phase for action [indices:data/write/index], request [index {[persons-1970-01-01][person][henk], source[{    "name" : "Henk"}]}]
[persons-1970-01-01] IndexNotFoundException[no such index]
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:151)
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:95)
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteSingleIndex(IndexNameExpressionResolver.java:208)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.doRun(TransportReplicationAction.java:451)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.action.support.replication.TransportReplicationAction.doExecute(TransportReplicationAction.java:131)
	at org.elasticsearch.action.index.TransportIndexAction.innerExecute(TransportIndexAction.java:135)
	at org.elasticsearch.action.index.TransportIndexAction.doExecute(TransportIndexAction.java:119)
	at org.elasticsearch.action.index.TransportIndexAction.doExecute(TransportIndexAction.java:66)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:137)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:85)
	at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:58)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
	at org.elasticsearch.client.FilterClient.doExecute(FilterClient.java:52)
	at org.elasticsearch.rest.BaseRestHandler$HeadersAndContextCopyClient.doExecute(BaseRestHandler.java:83)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
	at org.elasticsearch.client.support.AbstractClient.index(AbstractClient.java:371)
	at org.elasticsearch.rest.action.index.RestIndexAction.handleRequest(RestIndexAction.java:102)
	at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:54)
	at org.elasticsearch.rest.RestController.executeHandler(RestController.java:205)
	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:166)
	at org.elasticsearch.http.HttpServer.internalDispatchRequest(HttpServer.java:128)
	at org.elasticsearch.http.HttpServer$Dispatcher.dispatchRequest(HttpServer.java:86)
	at org.elasticsearch.http.netty.NettyHttpServerTransport.dispatchRequest(NettyHttpServerTransport.java:449)
	at org.elasticsearch.http.netty.HttpRequestHandler.messageReceived(HttpRequestHandler.java:61)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.http.netty.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:60)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by clintongormley** [comment] 2016-04-07 16:07
See related bug in https://github.com/elastic/elasticsearch/issues/17592

In this issue, `index.mapper.dynamic` is set in the config file instead of in the template.  The ability to set this in the config file will go away in 5.x.

**Comment by clintongormley** [comment] 2016-04-07 16:34
Probably caused by https://github.com/elastic/elasticsearch/pull/15424

**Comment by clintongormley** [comment] 2016-05-05 08:06
Actually investigating this further, this setting in the config file never worked correctly.  For instance, the following:

    PUT _template/test
    {
      "order": 0,
      "template": "persons*",
      "settings": {
        "index": {
          "number_of_shards": "1",
          "number_of_replicas": "0"
        }
      },
      "mappings": {
        "person": {
          "dynamic": "strict",
          "_all": {
            "enabled": false
          },
          "properties": {
            "name": {
              "index": "not_analyzed",
              "type": "string"
            }
          }
        }
      }
    }
    
Now put a document with type `personx`, which should have been prevented:

    PUT persons_1970/personx/1
    {
        "name" : "Henk"
    }

The `personx` type is added.  If the index already existed at the time we tried to add `personx`, then this would fail.  Setting `index.*` settings in the config file is no longer supported in 5.0 so I'm going to close this issue.

**Closed by clintongormley** 2016-05-05 08:06 UTC
Labels: :Mapping, adoptme, regression, v2.3.3
