### ISSUE TITLE
non existent setting not removeable but still in cluster

### ISSUE THREAD

**Issue by scratchy** [elastic/elasticsearch#28524] opened 2018-02-05 20:17 UTC
After rolling upgrade from 6.0.0 to 6.1.3 im having issues to update cluster settings

for example running this

```
curl -XPUT 'localhost:9200/_cluster/settings?pretty' -H 'Content-Type: application/json' -d'
{
  "transient": {
    "cluster.routing.allocation.enable": "all"
  }
}
'
```

results in:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "remote_transport_exception",
        "reason" : "[search-8][xxx:9300][cluster:admin/settings/update]"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "unknown setting [indices.store.throttle.max_bytes_per_sec] did you mean [indices.recovery.max_bytes_per_sec]?"
  },
  "status" : 400
}
```

tried to remove (set `indices.store.throttle.max_bytes_per_sec` to null) which complains with 'its not valid since its not there anymore as well as removing the upper level with):

```
curl -XPUT 'localhost:9200/_cluster/settings?pretty' -H 'Content-Type: application/json' -d'
{
  "persistent": {
    "indices.store.*" : null
  }
}
'
```

which gets acked:
```
{
  "acknowledged" : true,
  "persistent" : { },
  "transient" : { }
}
```

but still the error from above persists. I'm unable to update any cluster settings right now (because all of them complaining with the error above)

Any idears?

**Comment by scratchy** [comment] 2018-02-05 21:14
curl -XPUT 'localhost:9200/_cluster/settings?pretty' -H 'Content-Type: application/json' -d'
{ "persistent": { "*": null},"transcient:": {"*": null}}'

{
  "error" : {
    "root_cause" : [
      {
        "type" : "remote_transport_exception",
        "reason" : "[search-8][xxx:9300][cluster:admin/settings/update]"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "unknown setting [indices.store.throttle.max_bytes_per_sec] did you mean [indices.recovery.max_bytes_per_sec]?"
  },
  "status" : 400
}

**Comment by polyfractal** [comment] 2018-02-07 19:48
I believe this is a duplicate of #28026?  E.g. known bug, and some deprecated settings weren't added to the "archived" set (https://github.com/elastic/elasticsearch/issues/28026#issuecomment-363831607) which needs fixing.

Closing in favor of #28026

**Closed by polyfractal** 2018-02-07 19:48 UTC
