### ISSUE TITLE
[analysis] Kuromoji: updating user dictionary

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#13154] opened 2015-08-27 16:08 UTC
_From @gabriel-tessier on July 17, 2015 2:56_

Hi,
I need to update the user dictionary and I usually open close the index to make the change apply.
One question: Is it the only way to update the dict cause in case of typo (missing a , or one bad space) in the file the index don't open at all and on production server it's not an option.
first question (for confirmation): is it the good way to do? open close the index to reload the dict.
second one: is there a way to have an option like check config for apache [apachectl configtest]? so we can open close the index without fear!!

Thanks.

_Copied from original issue: elastic/elasticsearch-analysis-kuromoji#65_

**Comment by dadoonet** [comment] 2015-08-27 16:08
_From @johtani on July 29, 2015 9:25_

Hi,
Now, I think we don't have a way to reload the dict without open/close.
Because, the settings of mappings is load only in a timing to create index. 
Question about "an option like check config for apache". Does this mean checking only user dictionary?

**Comment by dadoonet** [comment] 2015-08-27 16:08
_From @gabriel-tessier on July 29, 2015 10:56_

Hi, thanks for the reply,

Question about "an option like check config for apache". Does this mean checking only user dictionary?
I don't know what it's better and how it's works from inside but concerning the plugin yes it can be a useful option.
When you said only user dictionary does it also include synonyms files, stop words, mapping etc... or it's a different system?


Also read about this blog : https://www.elastic.co/blog/support-in-the-wild-my-biggest-elasticsearch-problem-at-scale
It's written that closing the index remove the fielddata so if I need to update the dictionary several time a day and open close the index, it can make the search on this index more slow.

Thanks again for your time.

**Comment by dadoonet** [comment] 2015-08-27 16:08
_From @johtani on July 30, 2015 9:27_

Yes, if index close and open, then it can make the search on this index more slow.

However, if you update the dictionary several time a day, you have to re-index the existed data before updating the dictionary.
Changing the dictionary means changing the output of tokens. 
Some words can not match documents using old dictionary.

BTW, I think it is useful that we have the validation of mapping before creating index.

**Comment by dadoonet** [comment] 2015-08-27 16:08
_From @gabriel-tessier on July 30, 2015 9:45_

Hi,

> BTW, I think it is useful that we have the validation of mapping before creating index.

Cool!! Thanks a lot!

> you have to re-index the existed data before updating the dictionary.

it's re-index __after__ updating the dictionary??

Thanks again it'll be very helpful!

**Comment by dadoonet** [comment] 2015-08-27 16:08
_From @johtani on July 30, 2015 9:46_

Yes, "after updating the dictionary".

**Comment by clintongormley** [comment] 2015-08-28 09:18
I'm not sure there are any action points to take away from this issue.  It looks like a duplicate of others, to do with synonyms etc.  Closing

**Closed by clintongormley** 2015-08-28 09:18 UTC
Labels: :Plugin Analysis Kuromoji, discuss
