### ISSUE TITLE
[CI] MixedClusterClientYamlTestSuiteIT test {p0=indices.split/20_source_mapping/Split index ignores target template mapping} failing

### ISSUE THREAD

**Issue by danhermann** [elastic/elasticsearch#74197] opened 2021-06-16 16:22 UTC
~30 failures in the past two months

**Build scan:**
https://gradle-enterprise.elastic.co/s/lgmcz6ol5jdvk/tests/:qa:mixed-cluster:v6.8.17%23mixedClusterTest/org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT/test%20%7Bp0=indices.split%2F20_source_mapping%2FSplit%20index%20ignores%20target%20template%20mapping%7D

**Reproduction line:**
`./gradlew ':qa:mixed-cluster:v6.8.17#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=indices.split/20_source_mapping/Split index ignores target template mapping}" -Dtests.seed=240DCD1B0C321576 -Dtests.bwc=true -Dtests.locale=ar-SY -Dtests.timezone=Asia/Dhaka -Druntime.java=8`

**Applicable branches:**
master, 7.x, 6.8

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT&tests.test=test%20%7Bp0%3Dindices.split/20_source_mapping/Split%20index%20ignores%20target%20template%20mapping%7D

**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([240DCD1B0C321576]:0)

```

**Comment by mark-vieira** [comment] 2021-06-16 17:21
Closing this as a duplicate of https://github.com/elastic/elasticsearch/issues/73073. For some reason test execution is slower on this platform. We don't yet know why.

**Closed by mark-vieira** 2021-06-16 17:21 UTC
Labels: :Core/Features/Indices APIs, >test-failure, Team:Core/Features
