### ISSUE TITLE
use_real_memory setting causes GC collection issues

### ISSUE THREAD

**Issue by lanerjo** [elastic/elasticsearch#62278] opened 2020-09-12 00:21 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 7.8.1

**Plugins installed**: []

**JVM version** (`java -version`): bundled

**OS version** (`uname -a` if on a Unix-like system): rhel 6 & 7

**Description of the problem including expected versus actual behavior**:
Garbage collection not happening as expected when use_real_memory setting is enabled.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

```
    #Circuit Breaker Settings
    'indices.breaker.fielddata.limit' => '1%',
    'indices.breaker.fielddata.overhead' => '1.03',
    'indices.breaker.request.limit' => '60%',
    'indices.breaker.request.overhead' =>'1',
    'indices.breaker.total.limit' => '95%',
    'network.breaker.inflight_requests.limit' => '85%',
    'network.breaker.inflight_requests.overhead' => "2",
```

jvm.options
```
      10-:-XX:+UseG1GC
      10-:-XX:G1ReservePercent=20
      10-:-XX:InitiatingHeapOccupancyPercent=30
      10-:-XX:G1HeapRegionSize=16m
      10-:-XX:MaxGCPauseMillis=400
      10-:-XX:ParallelGCThreads=8
      10-:-XX:ConcGCThreads=6
      10-:-XX:+UseStringDeduplication
      -server
      -Djava.awt.headless=true
      -Dfile.encoding=UTF-8
      -Dio.netty.noUnsafe=true
      -Dio.netty.noKeySetOptimization=true
      -Dio.netty.recycler.maxCapacityPerThread=0
      -Dio.netty.allocator.type=unpooled
      -Dlog4j.shutdownHookEnabled=false
      -Dlog4j2.disable.jmx=true
      -Dlog4j.skipJansi=true
      -XX:+HeapDumpOnOutOfMemoryError
```
query... which was ran against 6Tb data
```
{"aggs":{"2":{"terms":{"field":"visit.applicationDetails.applicationType","order":{"_count":"desc"},"size":5},"aggs":{"3":{"terms":{"field":"state.view.previousPage.pageName","order":{"_count":"desc"},"size":50},"aggs":{"4":{"terms":{"field":"message.name","order":{"_count":"desc"},"size":5},"aggs":{"5":{"terms":{"field":"operation.operationType","order":{"_count":"desc"},"size":20},"aggs":{"6":{"terms":{"field":"state.view.currentPage.elements.standardizedName","order":{"_count":"desc"},"size":20},"aggs":{"7":{"cardinality":{"field":"visit.account.encAccountNumber"}}}}}}}}}}}}},"size":0,"_source":{"excludes":[]},"stored_fields":["*"],"query":{"bool":{"must":[],"filter":[{"match_all":{}},{"match_phrase":{"visit.applicationDetails.applicationName":{"query":"Spectrum Guide"}}},{"bool":{"should":[{"match_phrase":{"message.name":"selectAction"}},{"match_phrase":{"message.name":"playbackSelect"}}],"minimum_should_match":1}},{"range":{"message.timestamp":{"format":"strict_date_optional_time","gte":"2020-08-16T06:00:00.000Z","lte":"2020-09-24T06:00:00.000Z"}}}],"should":[],"must_not":[]}}}
```

**Provide logs (if relevant)**:
First set of query runs with use_real_memory: false 
![image](https://user-images.githubusercontent.com/20589998/92981664-20094800-f458-11ea-8ff5-5b91b24d0cec.png)
Second set of queries run with use_real_memory: true, also stopped running the queries due to circuit breaker exceptions after ~5 minutes

![image](https://user-images.githubusercontent.com/20589998/92982559-e9cdc780-f45b-11ea-80de-cd4d628b75dd.png)
You can see no GC happening for second set of queries

![image](https://user-images.githubusercontent.com/20589998/92982578-01a54b80-f45c-11ea-8bd8-c330ea1c560e.png)

GC Duration also not happening on second set of queries

**Comment by lanerjo** [comment] 2020-09-12 15:42
Upon further investigation of this matter. I noticed, that because GC has not cleaned up the memory in use, the node will continue to report circuit breaker exceptions for all subsequent calls, effectively making the node useless.

**Comment by original-brownbear** [comment] 2020-09-14 01:47
@lanerjo 

What was your heap usage before running those queries? It looks like it's close to 100% for most of the above graph.
What kind of client were you using to run those queries? Could it be that the client started backing off from sending more requests due to the `503` errors (that happened pretty much all the time due to being almost out of heap to begin with) and that's why there's no GC happening?

**Comment by lanerjo** [comment] 2020-09-14 14:31
I am using rally with a custom query load to generate those queries.
Here is the graph for the entire day...
![image](https://user-images.githubusercontent.com/20589998/93097707-23bcea80-f663-11ea-90e9-7adeea834f93.png)
The difference... 
Use real memory turned off, the same set of queries succeed and GC happens queries return successfully.
Use real memory enabled, the same set of queries first one succeeds, then subsequent queries fail with circuit breaker exception.

Short simple explanation, use real memory does not release heap in a reasonable amount of time. causing coordinating only node to become useless, stop serving even light queries, run into OOM on a query that was returning previously. It seems like most issues with circuit breakers the default answer from most Elastic responses seems to be to use_real_memory: true. 

The rally client was not backing off queries, which I would expect to not happen during a load test. 

I did find another issue related to this, so this should be a known bug... This was known before the 7.8.1 release, fixed before the 7.8.1 release, but it was not ported to 7.8.1. However this is not listed in the documentation. 

This is a potentially breaking bug, that could cause a lot of admins headaches beyond belief... I cannot even imagine having to restart coordinating only nodes due to an issue like this. I am glad I discovered this issue through testing, and before deploying to a production environment, where my users would have been affected.

**Comment by zdeseb** [comment] 2020-09-14 15:18
I can confirm similar problem on data nodes.

If **use_real_memory** setting is enabled and I put cluster under memory pressure for example by increasing number of replicas at once (at 9:05 on the graph bellow), I get into situation that some data nodes start to refuse requests, they even say that shards cannot be correctly opened etc.

If I try to wait, it doesn't help. Eventually I had to restart affected data nodes (the yellow mark on the graph).

I had to disable **use_real_memory** setting at all to ensure that my cluster doesn't crash every time it starts to create more than few replicas at once. **With this option disabled, memory consumption goes up for a while, but GC handles it well.**

![GC_problem](https://user-images.githubusercontent.com/9085123/93104195-d31eaf00-f6ad-11ea-86e3-293ee29d1f1b.JPG)

**Comment by jaymode** [comment] 2020-09-18 18:59
I would expect this issue to be better on Elasticsearch 7.9.0+ with the fix @henningandersen made for these situations in #58674.

@zdeseb @lanerjo are you able to upgrade to 7.9?

**Comment by zdeseb** [comment] 2020-09-18 20:55
@jaymode  At the moment I am quite happy with the workaround (disabled use_real_memory setting) but I believe that in a few weeks we will upgrade our test cluster and then we will see...

**Comment by rjernst** [comment] 2020-12-15 08:43
@zdeseb @lanerjo Were you able to try 7.9.0+? As Jay mentioned, we expect the situation to be better there. There doesn't seem to be much we can do here as we have not experienced this issue in our own tests, nor have we heard other reports.

**Comment by henningandersen** [comment] 2020-12-29 07:58
Since this is likely fixed in 7.9+, I will close this issue. @zdeseb and @lanerjo please reopen this if you still encounter this issue after upgrade to 7.9+.

**Closed** 2020-12-29 07:58 UTC
Labels: :Core/Infra/Circuit Breakers, >bug, Team:Core/Infra, feedback_needed

**Comment by zdeseb** [comment] 2020-12-29 08:23
> @zdeseb @lanerjo Were you able to try 7.9.0+? As Jay mentioned, we expect the situation to be better there. There doesn't seem to be much we can do here as we have not experienced this issue in our own tests, nor have we heard other reports.

@rjernst I am sorry but we were not :-(
Still running the same version as in September (other business priorities etc...)

**Comment by jplaisted** [comment] 2021-02-22 21:17
I believe this is still an issue. 

**Elasticsearch version (bin/elasticsearch --version):** 7.10.0

**Plugins installed:** []

**JVM version (java -version):** openjdk version "11.0.5" 2019-10-15 LTS

**OS version (uname -a if on a Unix-like system)**: rhel 7


We're trying to upgrade from 5 to 7 (quite late, yes yes). Our old cluster was 1 node, and our new one is 3. So there really is no reason why this new setup can't handle the old's data. I set up our ingestion pipeline to write to the new cluster, without copying any old data, and after a week or two it hit this issue. I cleared the cluster, and I tried copying over the smaller indices via python's bulk helper, and I could consistently hit this issue. It looks like only one node is hitting the limit, but I don't see the old heap GC run basically ever.

My manual copy test was roughly 5 GB of data before I ran into the issue consistently (I did not manage to copy everything). There are 30 indices, usually set up with 5 primary 1 replica (should probably make that 3 primary or less for this test cluster, but I don't think it'd break things this bad). Each node has 80 to 90 segments. In theory, there should be tons of runway here, there's no reason for a node to be using this much heap.

Our circuit breaker was 50% when I first saw the issue (hold over from our 5 config). I raised it to 75%, then did that manual copy test, and I still see it consistently.

I was not writing to any node in particular, afaik, we've set up an alias that should do round robin over the nodes.

Notice we are using CMS (default `jvm.options` + java 11 = CMS). [This thread](https://discuss.elastic.co/t/parent-circuit-breaker-calculation-seems-to-be-wrong-with-version-7-x/183530/23) has a similar issue, but everyone fixed it by moving to CMS.

I then set `use_real_memory` to false and turned the circuit breaker back to 50%. It was able to handle this, and old GC does run, but the heap usage is still very high for this 9.2 gb of data I ended up testing with (we have a index that is a few hundred gb I did not test with since copying that would take forever).

---

While testing with `use_real_memory` true:

Scrubbed `_nodes/jvm` https://gist.github.com/jplaisted/21f6e3b5310764108e73358f43b76ba1
Scrubbed node stats https://gist.github.com/jplaisted/2b3ae628b9731e3c8db284a942ca293d

Heap usage was at this level for days after the test. Old GC did not run.

---

After setting to false:

Scrubbed `_nodes/jvm`: https://gist.github.com/jplaisted/c236ada07fc85ad7915c83a3fcfc868b
Scrubbed node stats:  https://gist.github.com/jplaisted/85c8fb15a9cc4848d0d2a091570f4562

Heap usage is still very high for this amount of data, afaik, but I can actually see it GC in some graphs. Circuit breaker was never triggered, despite the heap going over the limit of 50%. I assume that the stats here are using a different calculation than the circuit breaker is.

Note that after my experiment, memory usage is constant, and GC no longer runs, just like in the test before. The heap remains this high, which is interesting, as it did drop / GC ran _during_ the experiment, unlike last time.

---

**Comment by jaymode** [comment] 2021-02-23 15:32
@jplaisted Thank you for providing all of those details in your comment. I actually think you might be running into something different especially since you are using CMS and the issue here is about G1GC. It could be similar and we may decide this is an issue for which we could make a code change but I think the best course of action is to dive deeper into your issue first. For that, can you please start a thread on https://discuss.elastic.co/c/elastic-stack/elasticsearch and link it here?

**Comment by jplaisted** [comment] 2021-02-23 20:52
Done. Thanks.

https://discuss.elastic.co/t/high-heap-usage-old-gc-does-not-run-consistently/265253
