### ISSUE TITLE
Elasticsearch V8.10.4 dies with a “noClassDefFoundError”

### ISSUE THREAD

**Issue by Franco901** [elastic/elasticsearch#101307] opened 2023-10-25 11:16 UTC
### Elasticsearch Version

V8.10.4

### Installed Plugins

none

### Java Version

_bundled_

### OS Version

CentOS 7

### Problem Description

While indexing our Nextcloud user data, the Nextcloud indexer sends an (encrypted) PDF to ES which bring ES to death. :cold_face:

I could isolate the user's documents, which I let index against our ES V7.17.13 node, which continues to work - as I would expect from V8 too.

Seems there are some bouncy castle dependencies broken?

Please fix that dependencies since we cannot migrate to ES V8.10 as long as this issue 

### Steps to Reproduce

start the OCC indexer with the encyrpted PDF

php occ fulltextsearch:index:document -u UserId files docId

index is "nextcloud":

---- settings.json ----
{
  "settings": {
    "index": {
      "routing": {
        "allocation": {
          "include": {
            "_tier_preference": "data_content"
          }
        }
      },
      "mapping": {
        "total_fields": {
          "limit": "10000"
        }
      },
      "number_of_shards": "1",
      "provided_name": "nextcloud",
      "creation_date": "1697437432798",
      "number_of_replicas": "1",
      "uuid": "9e3_sqY_QEyycgg21BNQHA",
      "version": {
        "created": "8100399"
      }
    }
  },
  "defaults": {
    "index": {
      "flush_after_merge": "512mb",
      "time_series": {
        "end_time": "9999-12-31T23:59:59.999Z",
        "start_time": "-9999-01-01T00:00:00Z",
        "es87tsdb_codec": {
          "enabled": "true"
        }
      },
      "final_pipeline": "_none",
      "max_inner_result_window": "100",
      "unassigned": {
        "node_left": {
          "delayed_timeout": "1m"
        }
      },
      "max_terms_count": "65536",
      "rollup": {
        "source": {
          "name": "",
          "uuid": ""
        }
      },
      "lifecycle": {
        "prefer_ilm": "true",
        "rollover_alias": "",
        "origination_date": "-1",
        "name": "",
        "parse_origination_date": "false",
        "step": {
          "wait_time_threshold": "12h"
        },
        "indexing_complete": "false"
      },
      "mode": "standard",
      "routing_partition_size": "1",
      "force_memory_term_dictionary": "false",
      "max_docvalue_fields_search": "100",
      "merge": {
        "scheduler": {
          "max_thread_count": "4",
          "auto_throttle": "true",
          "max_merge_count": "9"
        },
        "policy": {
          "merge_factor": "32",
          "floor_segment": "2mb",
          "max_merge_at_once_explicit": "30",
          "max_merge_at_once": "10",
          "max_merged_segment": "0b",
          "expunge_deletes_allowed": "10.0",
          "segments_per_tier": "10.0",
          "type": "UNSET",
          "deletes_pct_allowed": "20.0"
        }
      },
      "max_refresh_listeners": "1000",
      "max_regex_length": "1000",
      "load_fixed_bitset_filters_eagerly": "true",
      "number_of_routing_shards": "1",
      "write": {
        "wait_for_active_shards": "1"
      },
      "verified_before_close": "false",
      "mapping": {
        "coerce": "false",
        "nested_fields": {
          "limit": "50"
        },
        "depth": {
          "limit": "20"
        },
        "field_name_length": {
          "limit": "9223372036854775807"
        },
        "nested_objects": {
          "limit": "10000"
        },
        "ignore_malformed": "false",
        "dimension_fields": {
          "limit": "21"
        }
      },
      "source_only": "false",
      "soft_deletes": {
        "enabled": "true",
        "retention": {
          "operations": "0"
        },
        "retention_lease": {
          "period": "12h"
        }
      },
      "max_script_fields": "32",
      "query": {
        "default_field": [
          "*"
        ],
        "parse": {
          "allow_unmapped_fields": "true"
        }
      },
      "format": "0",
      "frozen": "false",
      "sort": {
        "missing": [],
        "mode": [],
        "field": [],
        "order": []
      },
      "priority": "1",
      "routing_path": [],
      "version": {
        "compatibility": "8100399"
      },
      "codec": "default",
      "max_rescore_window": "10000",
      "bloom_filter_for_id_field": {
        "enabled": "true"
      },
      "max_adjacency_matrix_filters": "100",
      "analyze": {
        "max_token_count": "10000"
      },
      "gc_deletes": "60s",
      "top_metrics_max_size": "10",
      "optimize_auto_generated_id": "true",
      "max_ngram_diff": "1",
      "hidden": "false",
      "translog": {
        "flush_threshold_age": "1m",
        "generation_threshold_size": "64mb",
        "flush_threshold_size": "10gb",
        "sync_interval": "5s",
        "retention": {
          "size": "-1",
          "age": "-1"
        },
        "durability": "REQUEST"
      },
      "auto_expand_replicas": "false",
      "fast_refresh": "false",
      "recovery": {
        "type": ""
      },
      "requests": {
        "cache": {
          "enable": "true"
        }
      },
      "data_path": "",
      "highlight": {
        "max_analyzed_offset": "1000000",
        "weight_matches_mode": {
          "enabled": "true"
        }
      },
      "routing": {
        "rebalance": {
          "enable": "all"
        },
        "allocation": {
          "disk": {
            "watermark": {
              "ignore": "false"
            }
          },
          "enable": "all",
          "total_shards_per_node": "-1"
        }
      },
      "search": {
        "slowlog": {
          "level": "TRACE",
          "threshold": {
            "fetch": {
              "warn": "-1",
              "trace": "-1",
              "debug": "-1",
              "info": "-1"
            },
            "query": {
              "warn": "-1",
              "trace": "-1",
              "debug": "-1",
              "info": "-1"
            }
          }
        },
        "idle": {
          "after": "30s"
        },
        "throttled": "false"
      },
      "fielddata": {
        "cache": "node"
      },
      "look_ahead_time": "2h",
      "default_pipeline": "_none",
      "max_slices_per_scroll": "1024",
      "shard": {
        "check_on_startup": "false"
      },
      "xpack": {
        "watcher": {
          "template": {
            "version": ""
          }
        },
        "version": "",
        "ccr": {
          "following_index": "false"
        }
      },
      "percolator": {
        "map_unmapped_fields_as_text": "false"
      },
      "allocation": {
        "max_retries": "5",
        "existing_shards_allocator": "gateway_allocator"
      },
      "refresh_interval": "1s",
      "indexing": {
        "slowlog": {
          "reformat": "true",
          "threshold": {
            "index": {
              "warn": "-1",
              "trace": "-1",
              "debug": "-1",
              "info": "-1"
            }
          },
          "source": "1000",
          "level": "TRACE"
        }
      },
      "compound_format": "1gb",
      "blocks": {
        "metadata": "false",
        "read": "false",
        "read_only_allow_delete": "false",
        "read_only": "false",
        "write": "false"
      },
      "max_result_window": "10000",
      "store": {
        "stats_refresh_interval": "10s",
        "type": "",
        "fs": {
          "fs_lock": "native"
        },
        "preload": [],
        "snapshot": {
          "snapshot_name": "",
          "index_uuid": "",
          "cache": {
            "prewarm": {
              "enabled": "true"
            },
            "enabled": "true",
            "excluded_file_types": []
          },
          "repository_uuid": "",
          "uncached_chunk_size": "-1b",
          "delete_searchable_snapshot": "false",
          "index_name": "",
          "partial": "false",
          "blob_cache": {
            "metadata_files": {
              "max_length": "64kb"
            }
          },
          "repository_name": "",
          "snapshot_uuid": ""
        }
      },
      "queries": {
        "cache": {
          "enabled": "true"
        }
      },
      "shard_limit": {
        "group": "normal"
      },
      "warmer": {
        "enabled": "true"
      },
      "downsample": {
        "origin": {
          "name": "",
          "uuid": ""
        },
        "source": {
          "name": "",
          "uuid": ""
        },
        "status": "unknown"
      },
      "override_write_load_forecast": "0.0",
      "max_shingle_diff": "3",
      "query_string": {
        "lenient": "false"
      }
    }
  }
}

----  stats.json. ----

{
  "_shards": {
    "total": 2,
    "successful": 1,
    "failed": 0
  },
  "stats": {
    "uuid": "9e3_sqY_QEyycgg21BNQHA",
    "health": "yellow",
    "status": "open",
    "primaries": {
      "docs": {
        "count": 3019416,
        "deleted": 2246
      },
      "shard_stats": {
        "total_count": 1
      },
      "store": {
        "size_in_bytes": 59698292351,
        "total_data_set_size_in_bytes": 59698292351,
        "reserved_in_bytes": 0
      },
      "indexing": {
        "index_total": 0,
        "index_time_in_millis": 0,
        "index_current": 0,
        "index_failed": 0,
        "delete_total": 0,
        "delete_time_in_millis": 0,
        "delete_current": 0,
        "noop_update_total": 0,
        "is_throttled": false,
        "throttle_time_in_millis": 0,
        "write_load": 0
      },
      "get": {
        "total": 0,
        "time_in_millis": 0,
        "exists_total": 0,
        "exists_time_in_millis": 0,
        "missing_total": 0,
        "missing_time_in_millis": 0,
        "current": 0
      },
      "search": {
        "open_contexts": 0,
        "query_total": 1,
        "query_time_in_millis": 1,
        "query_current": 0,
        "fetch_total": 1,
        "fetch_time_in_millis": 0,
        "fetch_current": 0,
        "scroll_total": 0,
        "scroll_time_in_millis": 0,
        "scroll_current": 0,
        "suggest_total": 0,
        "suggest_time_in_millis": 0,
        "suggest_current": 0
      },
      "merges": {
        "current": 0,
        "current_docs": 0,
        "current_size_in_bytes": 0,
        "total": 0,
        "total_time_in_millis": 0,
        "total_docs": 0,
        "total_size_in_bytes": 0,
        "total_stopped_time_in_millis": 0,
        "total_throttled_time_in_millis": 0,
        "total_auto_throttle_in_bytes": 20971520
      },
      "refresh": {
        "total": 2,
        "total_time_in_millis": 0,
        "external_total": 2,
        "external_total_time_in_millis": 1,
        "listeners": 0
      },
      "flush": {
        "total": 0,
        "periodic": 0,
        "total_time_in_millis": 0
      },
      "warmer": {
        "current": 0,
        "total": 1,
        "total_time_in_millis": 1
      },
      "query_cache": {
        "memory_size_in_bytes": 0,
        "total_count": 0,
        "hit_count": 0,
        "miss_count": 0,
        "cache_size": 0,
        "cache_count": 0,
        "evictions": 0
      },
      "fielddata": {
        "memory_size_in_bytes": 0,
        "evictions": 0,
        "global_ordinals": {
          "build_time_in_millis": 0
        }
      },
      "completion": {
        "size_in_bytes": 0
      },
      "segments": {
        "count": 40,
        "memory_in_bytes": 0,
        "terms_memory_in_bytes": 0,
        "stored_fields_memory_in_bytes": 0,
        "term_vectors_memory_in_bytes": 0,
        "norms_memory_in_bytes": 0,
        "points_memory_in_bytes": 0,
        "doc_values_memory_in_bytes": 0,
        "index_writer_memory_in_bytes": 0,
        "version_map_memory_in_bytes": 0,
        "fixed_bit_set_memory_in_bytes": 0,
        "max_unsafe_auto_id_timestamp": -1,
        "file_sizes": {}
      },
      "translog": {
        "operations": 0,
        "size_in_bytes": 55,
        "uncommitted_operations": 0,
        "uncommitted_size_in_bytes": 55,
        "earliest_last_modified_age": 192143
      },
      "request_cache": {
        "memory_size_in_bytes": 616,
        "evictions": 0,
        "hit_count": 0,
        "miss_count": 1
      },
      "recovery": {
        "current_as_source": 0,
        "current_as_target": 0,
        "throttle_time_in_millis": 0
      },
      "bulk": {
        "total_operations": 0,
        "total_time_in_millis": 0,
        "total_size_in_bytes": 0,
        "avg_time_in_millis": 0,
        "avg_size_in_bytes": 0
      },
      "dense_vector": {
        "value_count": 0
      }
    },
    "total": {
      "docs": {
        "count": 3019416,
        "deleted": 2246
      },
      "shard_stats": {
        "total_count": 1
      },
      "store": {
        "size_in_bytes": 59698292351,
        "total_data_set_size_in_bytes": 59698292351,
        "reserved_in_bytes": 0
      },
      "indexing": {
        "index_total": 0,
        "index_time_in_millis": 0,
        "index_current": 0,
        "index_failed": 0,
        "delete_total": 0,
        "delete_time_in_millis": 0,
        "delete_current": 0,
        "noop_update_total": 0,
        "is_throttled": false,
        "throttle_time_in_millis": 0,
        "write_load": 0
      },
      "get": {
        "total": 0,
        "time_in_millis": 0,
        "exists_total": 0,
        "exists_time_in_millis": 0,
        "missing_total": 0,
        "missing_time_in_millis": 0,
        "current": 0
      },
      "search": {
        "open_contexts": 0,
        "query_total": 1,
        "query_time_in_millis": 1,
        "query_current": 0,
        "fetch_total": 1,
        "fetch_time_in_millis": 0,
        "fetch_current": 0,
        "scroll_total": 0,
        "scroll_time_in_millis": 0,
        "scroll_current": 0,
        "suggest_total": 0,
        "suggest_time_in_millis": 0,
        "suggest_current": 0
      },
      "merges": {
        "current": 0,
        "current_docs": 0,
        "current_size_in_bytes": 0,
        "total": 0,
        "total_time_in_millis": 0,
        "total_docs": 0,
        "total_size_in_bytes": 0,
        "total_stopped_time_in_millis": 0,
        "total_throttled_time_in_millis": 0,
        "total_auto_throttle_in_bytes": 20971520
      },
      "refresh": {
        "total": 2,
        "total_time_in_millis": 0,
        "external_total": 2,
        "external_total_time_in_millis": 1,
        "listeners": 0
      },
      "flush": {
        "total": 0,
        "periodic": 0,
        "total_time_in_millis": 0
      },
      "warmer": {
        "current": 0,
        "total": 1,
        "total_time_in_millis": 1
      },
      "query_cache": {
        "memory_size_in_bytes": 0,
        "total_count": 0,
        "hit_count": 0,
        "miss_count": 0,
        "cache_size": 0,
        "cache_count": 0,
        "evictions": 0
      },
      "fielddata": {
        "memory_size_in_bytes": 0,
        "evictions": 0,
        "global_ordinals": {
          "build_time_in_millis": 0
        }
      },
      "completion": {
        "size_in_bytes": 0
      },
      "segments": {
        "count": 40,
        "memory_in_bytes": 0,
        "terms_memory_in_bytes": 0,
        "stored_fields_memory_in_bytes": 0,
        "term_vectors_memory_in_bytes": 0,
        "norms_memory_in_bytes": 0,
        "points_memory_in_bytes": 0,
        "doc_values_memory_in_bytes": 0,
        "index_writer_memory_in_bytes": 0,
        "version_map_memory_in_bytes": 0,
        "fixed_bit_set_memory_in_bytes": 0,
        "max_unsafe_auto_id_timestamp": -1,
        "file_sizes": {}
      },
      "translog": {
        "operations": 0,
        "size_in_bytes": 55,
        "uncommitted_operations": 0,
        "uncommitted_size_in_bytes": 55,
        "earliest_last_modified_age": 192143
      },
      "request_cache": {
        "memory_size_in_bytes": 616,
        "evictions": 0,
        "hit_count": 0,
        "miss_count": 1
      },
      "recovery": {
        "current_as_source": 0,
        "current_as_target": 0,
        "throttle_time_in_millis": 0
      },
      "bulk": {
        "total_operations": 0,
        "total_time_in_millis": 0,
        "total_size_in_bytes": 0,
        "avg_time_in_millis": 0,
        "avg_size_in_bytes": 0
      },
      "dense_vector": {
        "value_count": 0
      }
    }
  }
}

### Logs (if relevant)

java.lang.NoClassDefFoundError: org/bouncycastle/cms/CMSException
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:3549) ~[?:?]
	at java.lang.Class.getConstructor0(Class.java:3754) ~[?:?]
	at java.lang.Class.getDeclaredConstructor(Class.java:2930) ~[?:?]
	at org.apache.pdfbox.pdmodel.encryption.SecurityHandlerFactory.newSecurityHandler(SecurityHandlerFactory.java:132) ~[?:?]
	at org.apache.pdfbox.pdmodel.encryption.SecurityHandlerFactory.newSecurityHandlerForFilter(SecurityHandlerFactory.java:116) ~[?:?]
	at org.apache.pdfbox.pdmodel.encryption.PDEncryption.<init>(PDEncryption.java:97) ~[?:?]
	at org.apache.pdfbox.pdfparser.COSParser.prepareDecryption(COSParser.java:2974) ~[?:?]
	at org.apache.pdfbox.pdfparser.COSParser.retrieveTrailer(COSParser.java:285) ~[?:?]
	at org.apache.pdfbox.pdfparser.PDFParser.initialParse(PDFParser.java:173) ~[?:?]
	at org.apache.pdfbox.pdfparser.PDFParser.parse(PDFParser.java:226) ~[?:?]
	at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1232) ~[?:?]
	at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1206) ~[?:?]
	at org.apache.tika.parser.pdf.PDFParser.getPDDocument(PDFParser.java:317) ~[?:?]
	at org.apache.tika.parser.pdf.PDFParser.parse(PDFParser.java:172) ~[?:?]
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298) ~[?:?]
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:195) ~[?:?]
	at org.apache.tika.Tika.parseToString(Tika.java:525) ~[?:?]
	at org.elasticsearch.ingest.attachment.TikaImpl.lambda$parse$0(TikaImpl.java:97) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:714) ~[?:?]
	at org.elasticsearch.ingest.attachment.TikaImpl.parse(TikaImpl.java:96) ~[?:?]
	at org.elasticsearch.ingest.attachment.AttachmentProcessor.execute(AttachmentProcessor.java:121) ~[?:?]
	at org.elasticsearch.ingest.CompoundProcessor.innerExecute(CompoundProcessor.java:163) ~[elasticsearch-8.10.4.jar:?]
	at org.elasticsearch.ingest.CompoundProcessor.execute(CompoundProcessor.java:139) ~[elasticsearch-8.10.4.jar:?]
	at org.elasticsearch.ingest.Pipeline.execute(Pipeline.java:112) ~[elasticsearch-8.10.4.jar:?]
	at org.elasticsearch.ingest.IngestDocument.executePipeline(IngestDocument.java:853) ~[elasticsearch-8.10.4.jar:?]
	at org.elasticsearch.ingest.IngestService.executePipeline(IngestService.java:951) ~[elasticsearch-8.10.4.jar:?]
	at org.elasticsearch.ingest.IngestService.executePipelines(IngestService.java:827) ~[elasticsearch-8.10.4.jar:?]
	at org.elasticsearch.ingest.IngestService$1.doRun(IngestService.java:721) ~[elasticsearch-8.10.4.jar:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.10.4.jar:?]
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33) ~[elasticsearch-8.10.4.jar:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983) ~[elasticsearch-8.10.4.jar:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.10.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Franco901** [comment] 2023-10-26 06:07
I found a related post https://github.com/bcgit/bc-java/issues/1502.

Maybe this is the problem?

Trying to locate the bc*-jar files, I found these in lib/tools/security-cli 

bcpkix-jdk15on-1.64.jar
bcprov-jdk15on-1.64.jar

beside elasticsearch-security-cli-8.10.3.jar

But I **can't find a suitable bcutil-jdk15on-1.64.jar** on maven repo https://repo1.maven.org/maven2/org/bouncycastle/bcutil-jdk15on/ 

Only version 1.69 and 1.70

**Comment by masseyke** [comment] 2023-10-27 13:38
It looks like this was caused by https://github.com/elastic/elasticsearch/pull/88031. We need to add a better error message and better error handling if someone does pass in an encrypted file.

**Comment by masseyke** [comment] 2023-10-27 14:08
@Franco901 can you attach a file that reproduces this? When I try an encrypted PDF, the error is correctly handled and I get the expected:
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "parse_exception",
        "reason" : "Error parsing document in field [data]"
      }
    ],
    "type" : "parse_exception",
    "reason" : "Error parsing document in field [data]",
    "caused_by" : {
      "type" : "encrypted_document_exception",
      "reason" : "Unable to process: document is encrypted",
      "caused_by" : {
        "type" : "invalid_password_exception",
        "reason" : "Cannot decrypt PDF, the password is incorrect"
      }
    }
  },
  "status" : 400
}
```
There must be something different in the way your PDF is encrypted that I'm not testing. Thanks.

**Comment by masseyke** [comment] 2023-10-27 14:19
Oh it looks like this happens if the encryption type is `Adobe.PubSec`. I had used `Standard`.

**Comment by masseyke** [comment] 2023-11-01 15:25
This is fixed now in the 8.12 and 8.11 lines.

**Closed** 2023-11-01 16:11 UTC
Labels: >bug, :Data Management/Ingest Node, Team:Data Management

**Comment by Franco901** [comment] 2023-11-02 09:36
Tnx Keith for fixing/improving handling of encrypted files.

Now, I only have to wait for V8.11 available on https://artifacts.elastic.co/packages/8.x/yum

Best regards
Franco

**Comment by Franco901** [comment] 2023-11-16 07:26
Good news!

This morning I got new Version 8.11 from your RPM repo and installed it on a test node.
Throwing one of the evil encrypted PDFs into it, doesn't seem to bring to death - as previous ES 7.17 did.

Good work done! Tnx a lot. 

Best regards
Franco
