### ISSUE TITLE
[CI] CacheServiceTests.testCacheSynchronization failing on Windows

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#66424] opened 2020-12-16 01:38 UTC
This test seems to fail more often then not on Windows specifically

**Build scan**:
https://gradle-enterprise.elastic.co/s/vuzo7psf6b3wi/tests/:x-pack:plugin:searchable-snapshots:test/org.elasticsearch.xpack.searchablesnapshots.cache.CacheServiceTests/testCacheSynchronization#1

**Repro line**:
`gradlew ':x-pack:plugin:searchable-snapshots:test' --tests "org.elasticsearch.xpack.searchablesnapshots.cache.CacheServiceTests.testCacheSynchronization" -Dtests.seed=18CB9A8E31330D26 -Dtests.security.manager=true -Dtests.locale=fr-LU -Dtests.timezone=US/Michigan -Druntime.java=8`

**Reproduces locally?**:
I didn't go so far as to spin up a Windows VM to test on

**Applicable branches**:
Looks like only `7.x` so far

**Failure history**:
https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.tags=windows&search.timeZoneId=America/Los_Angeles&tests.container=org.elasticsearch.xpack.searchablesnapshots.cache.CacheServiceTests&tests.sortField=FAILED&tests.test=testCacheSynchronization&tests.unstableOnly=true

**Failure excerpt**:
```
org.elasticsearch.xpack.searchablesnapshots.cache.CacheServiceTests > testCacheSynchronization FAILED
    java.lang.AssertionError: 
    Expected: <1>
         but: was null
        at __randomizedtesting.SeedInfo.seed([18CB9A8E31330D26:C112B8C2AC2CE043]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.searchablesnapshots.cache.CacheServiceTests.lambda$testCacheSynchronization$5(CacheServiceTests.java:161)
        at java.util.HashMap.forEach(HashMap.java:1289)
        at org.elasticsearch.xpack.searchablesnapshots.cache.CacheServiceTests.testCacheSynchronization(CacheServiceTests.java:160)
```

**Comment by mark-vieira** [comment] 2020-12-16 01:39
@tlrx looks like this test was added by you recently. Mind taking a look?

**Comment by mark-vieira** [comment] 2020-12-16 01:42
Interestingly, looks like this failed every now and then in `master` up until this month, then it started failing again in `7.x` (I presume because it was just backported). Perhaps there's a fix that exists in `master` that wasn't backported?

**Comment by tlrx** [comment] 2020-12-17 09:00
> Interestingly, looks like this failed every now and then in `master` up until this month, then it started failing again in `7.x` (I presume because it was just backported). Perhaps there's a fix that exists in `master` that wasn't backported?

Yes, my fault. The test has been muted for Windows on master (#65581) and I forgot to backport this.

I'm closing this issue as a duplicate of #65581.

**Closed by tlrx** 2020-12-17 09:00 UTC
Labels: :Distributed/Snapshot/Restore, >test-failure, Team:Distributed

**Comment by tlrx** [comment] 2020-12-17 10:54
The mute has been backported to 7.x (#66502) and 7.11 (#66503) until the test is fixed on Windows.
