### ISSUE TITLE
Using high-level-rest-client (7.1.0) is causing exception for termsQuery

### ISSUE THREAD

**Issue by viswanathk** [elastic/elasticsearch#45394] opened 2019-08-09 15:51 UTC
**Elasticsearch version** (`bin/elasticsearch --version`):
7.1
**Plugins installed**: []

**JVM version** (`java -version`):

java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
4.9.0-4-amd64 #1 SMP Debian 4.9.65-3 (2017-12-03) x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

Problem: Using termsQuery in high level rest client is causing a:
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.index.query.TermsQueryBuilder exception.

**Steps to reproduce**:

1. Use high level rest client in java
2. Create a BoolQueryBuilder:
```
new BoolQueryBuilder().filter(QueryBuilders.termsQuery(ENTITY_ID, entry.getValue()))
```
3. See the stack trace

**Provide logs (if relevant)**:
```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.index.query.TermsQueryBuilder
	at org.elasticsearch.index.query.QueryBuilders.termsQuery(QueryBuilders.java:565) ~[elasticsearch-7.1.0.jar:7.1.0]
```

**Comment by hub-cap** [comment] 2019-08-12 18:03
A quick test did not reproduce this. I have the following pom dependencies, 

```
    <dependencies>
        <dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>elasticsearch-rest-client</artifactId>
            <version>7.3.0</version>
        </dependency>
        <dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch</artifactId>
            <version>7.3.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.11.1</version>
        </dependency>
    </dependencies>

```

and I built a main with the `new BoolQueryBuilder....`, and did not get a stack trace. 

Are there more steps to reproduce this that were omitted?

**Comment by viswanathk** [comment] 2019-08-17 10:13
Here are the pom dependencies being used by me:

```
<dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>elasticsearch-rest-high-level-client</artifactId>
            <version>7.1.0</version>
        </dependency>

        <dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>elasticsearch-rest-client</artifactId>
            <version>7.1.0</version>
        </dependency>
        <dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch</artifactId>
            <version>7.1.0</version>
        </dependency>
```

Looks like you are using 7.3.0, issue was coming up in 7.1.0.

**Comment by hub-cap** [comment] 2019-08-23 18:16
I cannot reproduce this, so Im closing it. I tried again with your exact dependencies (see below), and the following main method, and ran it in my IDE fine.

```
    static final Log log = LogFactory.getLog(Foo.class);

    public static void main(String[] args) {
        BoolQueryBuilder b = new BoolQueryBuilder().filter(QueryBuilders.termsQuery("foo", "1"));
        log.info(b);
    }
```

```
    <dependencies>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.11.1</version>
        </dependency>
        <dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>elasticsearch-rest-high-level-client</artifactId>
            <version>7.1.0</version>
        </dependency>

        <dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>elasticsearch-rest-client</artifactId>
            <version>7.1.0</version>
        </dependency>
        <dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch</artifactId>
            <version>7.1.0</version>
        </dependency>
    </dependencies>

```

Id be happy to test it more if you could give me a full example that showed this being reproducible.

**Closed by hub-cap** 2019-08-23 18:16 UTC
Labels: :Core/Features/Java High Level REST Client, feedback_needed
