### ISSUE TITLE
Different behavior between TransportClient and RestHighLevelClient on msearch Requests when providing scroll parameter

### ISSUE THREAD

**Issue by xtermi2** [elastic/elasticsearch#54377] opened 2020-03-28 12:59 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 7.6.1

**Plugins installed**: []

**JVM version** (`java -version`): the one provided in `docker.elastic.co/elasticsearch/elasticsearch:7.6.1`

**OS version** (`uname -a` if on a Unix-like system): `docker.elastic.co/elasticsearch/elasticsearch:7.6.1`
Host: `Linux XXX 5.3.0-40-generic #32-Ubuntu SMP Fri Jan 31 20:24:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
**Docker version**: 19.03.6, build 369ce74a3c

**Description of the problem including expected versus actual behavior**:
This issue is related to https://github.com/elastic/elasticsearch/issues/4227

There is a unexpected difference in transport client and rest client (or in general in REST API) when doing a msearch Request and setting the `scroll` parameter. Just have a look at https://github.com/xtermi2/elasticsearch-resthighlevelclient-msearch-scrollId/blob/master/src/test/java/com/github/xtermi2/elasticsearch/RHLCMsearchScrollIdTest.java for a complete running example to reproduce.

Test `restHighLevelClient_msearch_should_return_scrollId` failes, because the request does not provide the scroll parameter, so the response does not contain a scroll_id

Test `transportClient_msearch_should_return_scrollId` passes, because transport client somehow provides the scroll parameter in its request and the response, of course, contains a scroll_id.

It's the same request (MultiSearchRequest) for both clients. Here a example:
```java
        SearchRequest searchRequest = new SearchRequest("my-index")
                .scroll(TimeValue.timeValueSeconds(30));
        searchRequest.source()
                .query(QueryBuilders.matchAllQuery())
                .size(2);
        MultiSearchRequest multiSearchRequest = new MultiSearchRequest();
        multiSearchRequest.add(searchRequest);
```
When firing this request via RestHighLevelClient, you never get a `scroll_id` in the response.
```java
        MultiSearchResponse msearchRes = restHighLevelClient.msearch(multiSearchRequest, DEFAULT);
        msearchRes.getResponses()[1].getResponse().getScrollId(); // this is always null; unexpected behavior!
```
But when firing this request via TransportClient, you will get a `scroll_id` in the response.
```java
        MultiSearchResponse msearchRes = transportClient.multiSearch(multiSearchRequest).actionGet();
        msearchRes.getResponses()[1].getResponse().getScrollId(); // non-null, as expected and how it should work
```

So from the perspective of the transport-client/RestHighLevelClient I have the exact same API but get different behavior which is totally unexpected.

The minimum should be to provide a Exception when you want to do a `_msearch` request which provides unsupported parameters via RestHighLevelClient - until https://github.com/elastic/elasticsearch/issues/4227 is fixed and _msearch supports all parameters from _search

**Steps to reproduce**:
Repo to reproduce, just execute `./mvnw clean test` and you get a failing unittest because  `scroll_id` is unexpected null:
https://github.com/xtermi2/elasticsearch-resthighlevelclient-msearch-scrollId

**Comment by javanna** [comment] 2020-03-30 21:56
heya @xtermi2 thanks for opening this issue. 

I took some time to look into this and I was able to reproduce the problem. As far as I can see scrolling in msearch is not supported. At REST, the scroll parameter is not among the ones that we parse, and actually if you try this with curl you'll get back an error saying that "key [scroll] is not supported in the metadata section". You don't get back an error with the high-level client because the client does not even send out the scroll when a search request is sent as part of a multi search request, which translates on the server side with an ordinary search without a scroll, hence no scroll id will be returned in the search response.

But then, why does it work with the transport client? Because the transport client uses binary serialization and the transport layer, where the scroll id does not get lost in the search request.

Now that I understand better where the problem is and what needs to be done to solve it, I think we can close this one in favour of #4227 where you originally left a comment, as that issue addresses exactly this type of inconsistency between search and msearch. I am not sure if this specific inconsistency is there for a reason, but that can be discussed in the linked issue.

**Closed by javanna** 2020-03-30 21:56 UTC
Labels: :Core/Features/Java High Level REST Client, >bug
