### ISSUE TITLE
Teach /_cat/indices to Return the 'creation_date' Value

### ISSUE THREAD

**Issue by RyanFrantz** [elastic/elasticsearch#11998] opened 2015-07-02 16:39 UTC
``/_cat/indices`` currently allows returning an explicit set of headers in its output, such as health, status, index name, shard counts, etc. I'd love to see this endpoint support an additional header parameter: ``?h=creation_date``.

This would be useful for enumerating indices by age.

**Comment by clintongormley** [comment] 2015-07-05 16:15
Closing as duplicate of #11524

**Closed by clintongormley** 2015-07-05 16:15 UTC
