### ISSUE TITLE
NPE in GlobalOrdinalsSignificantTermsAggregator.WithHash

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#23652] opened 2017-03-20 15:35 UTC
One of our rest test runs run into this. Here's a complete stack trace:

```
Caused by: java.lang.NullPointerException
        at org.elasticsearch.search.aggregations.bucket.significant.GlobalOrdinalsSignificantTermsAggregator$WithHash.<init>(GlobalOrdinalsSignificantTermsAggregator.java:170) ~[elasticsearch-6.0.0-alpha1
-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
        at org.elasticsearch.search.aggregations.bucket.significant.SignificantTermsAggregatorFactory$ExecutionMode$3.create(SignificantTermsAggregatorFactory.java:284) ~[elasticsearch-6.0.0-alpha1-SNAPSH
OT.jar:6.0.0-alpha1-SNAPSHOT]
        at org.elasticsearch.search.aggregations.bucket.significant.SignificantTermsAggregatorFactory.doCreateInternal(SignificantTermsAggregatorFactory.java:217) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar
:6.0.0-alpha1-SNAPSHOT]
        at org.elasticsearch.search.aggregations.support.ValuesSourceAggregatorFactory.createInternal(ValuesSourceAggregatorFactory.java:55) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
        at org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:221) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
        at org.elasticsearch.search.aggregations.AggregatorFactory.asMultiBucketAggregator(AggregatorFactory.java:235) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
        at org.elasticsearch.search.aggregations.bucket.significant.SignificantTermsAggregatorFactory.doCreateInternal(SignificantTermsAggregatorFactory.java:172) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
        at org.elasticsearch.search.aggregations.support.ValuesSourceAggregatorFactory.createInternal(ValuesSourceAggregatorFactory.java:55) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
        at org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:221) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
        at org.elasticsearch.search.aggregations.AggregatorFactories.createSubAggregators(AggregatorFactories.java:205) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
        at org.elasticsearch.search.aggregations.AggregatorBase.<init>(AggregatorBase.java:78) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
        at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.<init>(BucketsAggregator.java:45) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
        at org.elasticsearch.search.aggregations.bucket.SingleBucketAggregator.<init>(SingleBucketAggregator.java:38) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
        at org.elasticsearch.search.aggregations.bucket.sampler.SamplerAggregator.<init>(SamplerAggregator.java:144) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
        at org.elasticsearch.search.aggregations.bucket.sampler.SamplerAggregatorFactory.createInternal(SamplerAggregatorFactory.java:45) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
        at org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:221) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
        at org.elasticsearch.search.aggregations.AggregatorFactories.createTopLevelAggregators(AggregatorFactories.java:221) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
        at org.elasticsearch.search.aggregations.AggregationPhase.preProcess(AggregationPhase.java:55) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
        at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:106) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
        at org.elasticsearch.indices.IndicesService.lambda$loadIntoContext$15(IndicesService.java:1133) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
```

**Comment by markharwood** [comment] 2017-03-21 15:28
Build URL: https://internal-ci.elastic.co/job/elastic+x-pack-elasticsearch+master+periodic/449/
Reproduction line with seed (but did not reproduce for me either):
 
    gradle :x-pack-elasticsearch:qa:core-rest-tests-with-security:integTestRunner -Dtests.seed=C016D74BF486C161 -Dtests.class=org.elasticsearch.xpack.security.CoreWithSecurityClientYamlTestSuiteIT -Dtests.method="test {yaml=msearch/20_typed_keys/Multisearch test with typed_keys parameter for sampler and significant terms}" -Dtests.security.manager=true -Dtests.locale=sr-RS -Dtests.timezone=America/North_Dakota/Center "-Dtests.rest.blacklist=cat.aliases/10_basic/Empty cluster,index/10_with_id/Index with ID,indices.get_alias/10_basic/Get alias against closed indices,cat.templates/10_basic/No templates,cat.templates/10_basic/Sort templates,cat.templates/10_basic/Multiple template"

**Comment by markharwood** [comment] 2017-03-21 17:27
Odd one - doesn't reproduce for me and looking at code the only method invocation is on SearchContext object which suggests this was null somehow:

      bucketOrds = new LongHash(1, context.bigArrays());

**Comment by markharwood** [comment] 2017-03-22 09:38
Actually the line that failed was the closing bracket after the above statement. I assumed this was an inaccuracy in error reporting but then saw this from @nik9000 on a different build failure this morning:
>The last stack trace element (BlockTermState.java:55) in on a closing bracket. I've seen a few NPEs on the closing brackets locally as well but I thought it was bad hardware because I *knew* I had bad hardware at the time.

**Comment by jasontedor** [comment] 2017-03-22 10:53
Indeed, it can not be the case that `context` is null, it was accessed higher up the stack in org.elasticsearch.search.aggregations.bucket.significant.SignificantTermsAggregatorFactory.doCreateInternal, and prior to that in a super constructor for `WithHash` (`BucketsAggregator`). Since it's final, it simply can not be `null` here or we would blow up earlier.

**Comment by jasontedor** [comment] 2017-04-07 11:01
Given this is an NPE in an unusual place, I do not think there is much if anything to do here and we should close this issue as we are tracking these unusual failures elsewhere.

**Closed by jasontedor** 2017-04-07 11:01 UTC
Labels: :Aggregations, test
