### ISSUE TITLE
bulk operation,docs has a redundant "}",the search api has some problem vesion 1.4.1

### ISSUE THREAD

**Issue by zhengfengshaw** [elastic/elasticsearch#10808] opened 2015-04-26 07:09 UTC
![image](https://cloud.githubusercontent.com/assets/3814081/7336251/b5981cc0-ec25-11e4-8b04-34cf5d6e7bd2.png)
，then when I search it, somethings happen,
![image](https://cloud.githubusercontent.com/assets/3814081/7336256/10434438-ec26-11e4-929a-3b2cc3aaa7a0.png)
The result is not a JSON structure!

**Comment by markwalkom** [comment] 2015-04-26 08:11
It'd be easier if you pasted the text, rather than screenshots :)

**Comment by clintongormley** [comment] 2015-04-26 18:00
@zhengfengshaw not quite following what you're saying, but if you're saying that currently Elasticsearch accepts invalid JSON, and is then quite happy to return it, then yes.  This is a known issue.  

Closing as a duplicate of https://github.com/elastic/elasticsearch/pull/2315

Please reopen if I have misunderstood

**Closed by clintongormley** 2015-04-26 18:00 UTC
Labels: feedback_needed
