### ISSUE TITLE
ES2.1.0 keep throw NotSerializableExceptionWrapper

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#15537] opened 2015-12-18 10:06 UTC
same ES2.1.0 server and client. 

[DEBUG][action.admin.cluster.node.info] [node1] failed to execute on node [yQYHZ3hxTWOwrQPq8w4rrQ]
RemoteTransportException[[node2][node2:9305][cluster:monitor/nodes/info[n]]]; nested: NotSerializableExceptionWrapper;
Caused by: NotSerializableExceptionWrapper[null]
at java.util.ArrayList.sort(ArrayList.java:1456)
at java.util.Collections.sort(Collections.java:175)
at org.elasticsearch.action.admin.cluster.node.info.PluginsInfo.getInfos(PluginsInfo.java:55)
at org.elasticsearch.action.admin.cluster.node.info.PluginsInfo.writeTo(PluginsInfo.java:86)
at org.elasticsearch.action.admin.cluster.node.info.NodeInfo.writeTo(NodeInfo.java:284)
at org.elasticsearch.transport.netty.NettyTransportChannel.sendResponse(NettyTransportChannel.java:97)
at org.elasticsearch.transport.netty.NettyTransportChannel.sendResponse(NettyTransportChannel.java:75)
at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:211)
at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:207)
at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:299)
at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

**Comment by jasontedor** [comment] 2015-12-18 10:19
This exception can not be coming from a 2.1.0 node as `o.e.a.a.c.n.i.PluginsInfo` is not a class there. Maybe this is from a 1.x node joining your cluster?

**Comment by makeyang** [comment] 2015-12-18 10:31
no, the cluster noeds are all 2.1.0

**Comment by jasontedor** [comment] 2015-12-18 11:25
Please accept my apologies. The `PluginsInfo` class was indeed removed in the current 2.x branch, but is still present in 2.1.0. What plugins do you have installed or have you developed any plugins locally? Is there a possibility that you have a plugin that has a null name?

**Comment by jasontedor** [comment] 2015-12-18 12:31
I can reproduce this locally. This can be caused by concurrent requests to any of the nodes info, cluster stats and the cat plugins API. I will open a pull request to address shortly.

**Comment by robertsmarty** [comment] 2015-12-29 00:48
I'm also receiving these errors intermittently. I left my 5 node 2.1.0 cluster running over the Christmas break collecting about 120k events per minute from firewalls. Have the following plugins installed...

    - license
    - marvel-agent
    - cloud-aws
    - shield
    - watcher

Receiving the following error on all cluster nodes...

[2015-12-29 07:26:26,735][DEBUG][action.admin.cluster.node.info] [elkrp11] failed to execute on node [m_uC_oh1TAmasv2k1n3zJg]
RemoteTransportException[[elkrp7][10.10.60.121:9300][cluster:monitor/nodes/info[n]]]; nested: NotSerializableExceptionWrapper;
Caused by: NotSerializableExceptionWrapper[null]
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
        at java.util.ArrayList$Itr.next(ArrayList.java:851)
        at org.elasticsearch.action.admin.cluster.node.info.PluginsInfo.writeTo(PluginsInfo.java:86)
        at org.elasticsearch.action.admin.cluster.node.info.NodeInfo.writeTo(NodeInfo.java:284)
        at org.elasticsearch.transport.netty.NettyTransportChannel.sendResponse(NettyTransportChannel.java:97)
        at org.elasticsearch.transport.netty.NettyTransportChannel.sendResponse(NettyTransportChannel.java:75)
        at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:211)
        at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:207)
        at org.elasticsearch.shield.transport.ShieldServerTransportService$ProfileSecuredRequestHandler.messageReceived(ShieldServerTransportService.java:165)
        at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:299)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by jasontedor** [comment] 2015-12-29 01:13
Closed in 2.1 by 0cd08afd53b90523ed9cb052869653bc2184cf25 and in 2.0 by 916218d1f87ea95785e659f514fae5f9a524005d.

**Closed by jasontedor** 2015-12-29 01:13 UTC

**Comment by robertsmarty** [comment] 2015-12-29 05:10
I'm running a 2.1.1 cluster and this issue still persists

**Comment by jasontedor** [comment] 2015-12-29 12:20
> I'm running a 2.1.1 cluster and this issue still persists

The fix for this was put into the 2.1 branch for inclusion in an eventual 2.1.2 patch release by commit 0cd08afd53b90523ed9cb052869653bc2184cf25, and the into the 2.0 branch for inclusion in a potential (but not guaranteed) 2.0.3 release by commit 916218d1f87ea95785e659f514fae5f9a524005d. The version labels on #15541 are v2.0.3 and v2.1.2 showing the potential releases that will contain the fix.

**Comment by oleg-andreyev** [comment] 2016-09-09 13:40
Issue seems still persists on v2.4.0:

```
Caused by: NotSerializableExceptionWrapper[too_complex_to_determinize_exception: Determinizing automaton with 77 states and 317 transitions would result in more than 10000 states.]
        at org.apache.lucene.util.automaton.Operations.determinize(Operations.java:743)
        at org.apache.lucene.util.automaton.MinimizationOperations.minimize(MinimizationOperations.java:58)
        at org.apache.lucene.util.automaton.RegExp.toAutomatonInternal(RegExp.java:515)
        at org.apache.lucene.util.automaton.RegExp.toAutomaton(RegExp.java:495)
        at org.apache.lucene.util.automaton.RegExp.toAutomaton(RegExp.java:426)
        at org.elasticsearch.search.aggregations.bucket.terms.support.IncludeExclude.toAutomaton(IncludeExclude.java:384)
        at org.elasticsearch.search.aggregations.bucket.terms.support.IncludeExclude.convertToOrdinalsFilter(IncludeExclude.java:408)
        at org.elasticsearch.search.aggregations.bucket.terms.TermsAggregatorFactory$ExecutionMode$2.create(TermsAggregatorFactory.java:71)
        at org.elasticsearch.search.aggregations.bucket.terms.TermsAggregatorFactory.doCreateInternal(TermsAggregatorFactory.java:246)
        at org.elasticsearch.search.aggregations.support.ValuesSourceAggregatorFactory.createInternal(ValuesSourceAggregatorFactory.java:64)
        at org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:102)
        at org.elasticsearch.search.aggregations.AggregatorFactories.createTopLevelAggregators(AggregatorFactories.java:87)
        at org.elasticsearch.search.aggregations.AggregationPhase.preProcess(AggregationPhase.java:85)
        at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:111)
        at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:372)
        at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:480)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryFetchTransportHandler.messageReceived(SearchServiceTransportAction.java:392)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryFetchTransportHandler.messageReceived(SearchServiceTransportAction.java:389)
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
        at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:293)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)

```

```
{
"name": "opcart-es-data-1",
"cluster_name": "opcart-prod-v2",
"version": {
"number": "2.4.0",
"build_hash": "ce9f0c7394dee074091dd1bc4e9469251181fc55",
"build_timestamp": "2016-08-29T09:14:17Z",
"build_snapshot": false,
"lucene_version": "5.5.2"
},
"tagline": "You Know, for Search"
}
```

**Comment by jasontedor** [comment] 2016-09-09 14:23
@oleg-andreyev This is a completely different issue. You're hitting a `TooComplexToDeterminizeException` inside Lucene, which we do not serialize, hence the wrapper. Hence the message:

> `too_complex_to_determinize_exception: Determinizing automaton with 77 states and 317 transitions would result in more than 10000 states.`

It looks like you have a regular expression that is too complex? I suggest opening a discuss thread on the [Elastic Discourse forums](https://discuss.elastic.co) if you have additional questions.
