### ISSUE TITLE
Elasticsearch hangs if a NFS mount point is stale

### ISSUE THREAD

**Issue by dineshpathak** [elastic/elasticsearch#24361] opened 2017-04-27 09:59 UTC
We are running ES 2.0 on a system which has some stale NFS mount points also, but the data directory given to ES is on HDD only. Seems ES on start tries to figure out whether the device containing data directory spins or not and the underlying java API iterates over all the available mount points and issues a stat call. Since this NFS mount point is stale, ES hangs for sometime and then crashes and this keeps on happening. 
On linux systems, it can query /proc/self/mounts or do a mount | grep <mountpoint> or a parameter can be taken from user in data.path config to say if this device spins or not.

Below is the stack of main thread in hung state.

"main" #1 prio=5 os_prio=0 tid=0x00007fc5d000a800 nid=0xce9f runnable [0x00007fc5d82d8000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.fs.UnixNativeDispatcher.stat0(Native Method)
        at sun.nio.fs.UnixNativeDispatcher.stat(UnixNativeDispatcher.java:286)
        at sun.nio.fs.UnixFileAttributes.get(UnixFileAttributes.java:70)
        at sun.nio.fs.UnixFileStore.devFor(UnixFileStore.java:55)
        at sun.nio.fs.UnixFileStore.<init>(UnixFileStore.java:70)
        at sun.nio.fs.LinuxFileStore.<init>(LinuxFileStore.java:48)
        at sun.nio.fs.LinuxFileSystem.getFileStore(LinuxFileSystem.java:112)
        at sun.nio.fs.UnixFileSystem$FileStoreIterator.readNext(UnixFileSystem.java:213)
        at sun.nio.fs.UnixFileSystem$FileStoreIterator.hasNext(UnixFileSystem.java:224)
        - locked <0x000000070058a288> (a sun.nio.fs.UnixFileSystem$FileStoreIterator)
        at org.apache.lucene.util.IOUtils.getFileStore(IOUtils.java:534)
        at org.apache.lucene.util.IOUtils.spinsLinux(IOUtils.java:483)
        at org.apache.lucene.util.IOUtils.spins(IOUtils.java:472)
        at org.elasticsearch.env.ESFileStore.<init>(ESFileStore.java:57)
        at org.elasticsearch.env.Environment.<clinit>(Environment.java:88)
        at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:82)
        at org.elasticsearch.common.cli.CliTool.<init>(CliTool.java:107)
        at org.elasticsearch.common.cli.CliTool.<init>(CliTool.java:100)
        at org.elasticsearch.bootstrap.BootstrapCLIParser.<init>(BootstrapCLIParser.java:48)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:226)

**Comment by danielmitterdorfer** [comment] 2017-04-27 10:57
This is a duplicate of #19134 (although this one is about ES 2.x and the other one about 5.x, the underlying code is the same).

> Since this NFS mount point is stale, ES hangs for sometime and then crashes and this keeps on happening.

How does Elasticsearch crash? Does it exit with an error code? Is there a stack trace in the logs?

**Comment by danielmitterdorfer** [comment] 2017-04-27 11:07
Also, is there any chance you use the [NFS mount option `hard`](https://linux.die.net/man/5/nfs)? As you can see from the stack trace, the JVM issues a `stat` file system call and which will hang indefinitely in that case AFAIK. If that's the case, then I fear we're out of luck here (I think inspecting `/proc/self/mounts` is not an option for us).

**Comment by dineshpathak** [comment] 2017-04-28 08:41
Sorry, the crashes are because of our own monitoring of ES, so please ignore that. Can you give an option to users to specify where device spins or not. Default mechanism can be auto detection, but users can provide this if they want. These machines are getting used for some other purpose also so soft mount is not an option.

**Comment by danielmitterdorfer** [comment] 2017-04-28 12:19
If you look closely at the stack trace, you'll see that pretty soon the JDK is involved:

```
[...]
at sun.nio.fs.UnixFileSystem$FileStoreIterator.hasNext(UnixFileSystem.java:224)
- locked <0x000000070058a288> (a sun.nio.fs.UnixFileSystem$FileStoreIterator)
at org.apache.lucene.util.IOUtils.getFileStore(IOUtils.java:534)
[...]
```

So it is a implementation detail of the JDK's NIO implementation that it issues a `stat` call. Elasticsearch and Lucene use NIO in various places so even changing or circumventing the detection of spinning disks would just defer the problem, hence I'm closing.

**Closed by danielmitterdorfer** 2017-04-28 12:19 UTC
Labels: :Internal, discuss

**Comment by danielmitterdorfer** [comment] 2017-04-28 13:44
We analyzed the surrounding code once more and there are a few simplifications that we can make which would also solve your problem: See #24390 for the technical details.
