### ISSUE TITLE
Lucene CustomScoreQuery not enumerating long primitives

### ISSUE THREAD

**Issue by dsafaric** [elastic/elasticsearch#26830] opened 2017-09-29 09:23 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): Version: 5.6.1, Build: 667b497/2017-09-14T19:22:05.189Z, JVM: 1.8.0_144

**Plugins installed**: [custom plugin]

**JVM version** (`java -version`): 1.8

**OS version** (`uname -a` if on a Unix-like system): #39~16.04.1-Ubuntu SMP Wed Sep 13 09:02:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
I've written a custom Lucene `CustomScoreQuery` subclass that is expected to: (1) classify documents using a `long` field type as matched or not, (2) score the hit documents using another `long` field type. The problem I am facing is that the `CustomScoreQuery`'s subquery is not iterating through the terms of the given field. If I change the field type from `long` to `keyword` for example, the `getTermsEnum()` function of the subquery is executed and a FilteredTermsEnum instance is returned, which is the expected behaviour. In addition, I've used the plugin successfully in Apache Solr, however the same does not imply to Elastic. The most important implementation details may be found [here](https://discuss.elastic.co/t/querys-gettermsenum-not-executed/101501).

The index mapping I've defined is as follows:

```
{
  "images" : {
    "mappings" : {
      "descriptors" : {
        "properties" : {
          "image_descriptor_long" : {
            "type" : "long"
          },
          "image_descriptor_short" : {
            "type" : "long"
          }
        }
      }
    }
  }
}

```

**Comment by jimczi** [comment] 2017-09-29 09:42
@dsafaric I answered on the forum directly, thanks for opening the discussion. I am going to close this issue because we reserve github for confirmed bugs and feature requests, we can continue the discussion on the forum.

**Closed by jimczi** 2017-09-29 09:42 UTC
