### ISSUE TITLE
Running junit tests in IntelliJ 15 results in "JAVA_HOME must be set" error

### ISSUE THREAD

**Issue by martiansnoop** [elastic/elasticsearch#15255] opened 2015-12-04 22:59 UTC
I discovered this while attempting to build master as of last night.

I found that I can run unit tests in IntelliJ 14, but not IntelliJ 15. This is the error in 15:

```
FAILURE: Build failed with an exception.
* Where:
Build file '[removed]/elasticsearch/core/build.gradle' line: 24
* What went wrong:
A problem occurred evaluating project ':core'.
> Failed to apply plugin [id 'elasticsearch.build']
   > JAVA_HOME must be set to build Elasticsearch
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

The error appears to be happening on [this line] (https://github.com/elastic/elasticsearch/blob/master/buildSrc/src/main/groovy/org/elasticsearch/gradle/BuildPlugin.groovy#L124). It looks like the "idea.active" property is not being set in my copy of Intellij15. 

Locally, I found a property the intellij 15 did set, and altered the code to also check that property:

```java
if (System.getProperty("idea.active") != null || System.getProperty("idea.home.path") != null) 
```

It seems like this kind of solution might get out of hand, so I'm not sure if it's a good/workable solution or not. I assume there are disadvantages to using `Jvm.current().javaHome` for all cases, or else the original author of the code might have done that. Can anyone explain further why the findJavaHome method is structured the way it is?

**Comment by rjernst** [comment] 2015-12-04 23:16
@martiansnoop Did you import into intellij as a gradle project, or simply open the generated file based project `gradle idea` produces?

**Comment by rjernst** [comment] 2015-12-04 23:29
> Can anyone explain further why the findJavaHome method is structured the way it is?

This is due to gradle being broken with java 9. In order to allow running tests with jdk9 / jigsaw we use JAVA_HOME to indicate which java to use for compiling/testing. This means we can set org.gradle.java.home to tell gradle which jvm to use, and separately set JAVA_HOME. 

In intellij,they don't set JAVA_HOME when they spin up jvms for tests or gradle tasks. Unfortunately they don't see this as a problem...
https://youtrack.jetbrains.com/issue/IDEA-147331

Also, the fact your hitting this suggest to me you tried running the test from intellij through "gradle" instead of JUnit? This is something I hope we can support, but at least right now I do not believe it works (I think it tries running all unit tests when you try running a single one).

**Comment by martiansnoop** [comment] 2015-12-05 23:51
>Also, the fact your hitting this suggest to me you tried running the test from intellij through "gradle" instead of JUnit?

Yes, this is correct, I was trying to run tests through gradle (IntelliJ 15 defaulted to it). I set up a JUnit configuration instead and tests run for me in intellij now without modifying the line in `BuildPlugin.groovy`. Thanks for the suggestion!

> Did you import into intellij as a gradle project, or simply open the generated file based project gradle idea produces?

I ran `gradle idea`, then went to `File > New > Project from existing sources...`, selected the directory where I cloned the repo, and followed the menus after that. (I am unfamiliar with the workings of gradle, so this may have been a suboptimal sequence.)

**Comment by rjernst** [comment] 2015-12-08 07:59
@martiansnoop Thanks for the info. Since you confirmed running junit tests do work, I'm closing this. Hopefully sometime in the future we can make running tests through gradle from the IntelliJ work.

**Closed by rjernst** 2015-12-08 07:59 UTC
Labels: build, feedback_needed

**Comment by poson** [comment] 2018-05-29 12:38
In my case , i had installed gradle 2.10             3.5-rc-2         4.4              4.6              jars-1           jars-3           
3.4.1            4.0              4.4.1            4.7。
I always found error like “> Failed to apply plugin [id 'elasticsearch.build']
   > JAVA_HOME must be set to build Elasticsearch”，
after a lot of try， I delete /Users/xxx/.gradle/caches/2.10 , /Users/xxx/.gradle/caches/3.4.1 ,.....,just leave 4.7 ，then gradle build is successful！
