### ISSUE TITLE
Track total fields overhead

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#98107] opened 2023-08-01 14:49 UTC
### Elasticsearch Version

8.8

### Java Version

_bundled_

### OS Version

All OSs

### Problem Description

When a node contains a huge number of fields `_nodes/stats` mappings section reports incorrect `total_estimated_overhead`, where reported value could be 100X time smaller than the real value occupied by `FieldInfo`.

### Steps to Reproduce

Create an index with many fields.

**Comment by henningandersen** [comment] 2024-03-19 10:01
We discussed this a bit in the distrib team. What we have today is the mapping information and we are missing the overhead from segments and field-infos. We think this could go into a separate stat field, at least they would likely have different volatility (the former depending only on allocation and mappings, the latter also on merging and indexing activity).

It could be good to have this information available also for other purposes than sizing the cluster. For instance determining which readers to keep open in frozen tier or stateless could benefit from accurate tracking of memory use, since then we could setup a memory limit for how much memory to use for open readers.

**Comment by javanna** [comment] 2024-06-07 10:29
I reworded the description based on the input we got above. The current value is just an estimation of the memory overhead around mappings, and does not include info from segments or field infos. If we wanted to add that, we were recommended to introduce a new field for it. I relabelled this as enhancement as well, given that the team that added total_estimated_overhead confirmed that its behavior is expected.

**Comment by martijnvg** [comment] 2024-07-09 05:46
I was chatting with @dnhatn and  with #110561, it will be likely that we would always overestimate the memory usage for `FieldInfo`. So not sure whether this issue still makes sense.

**Comment by dnhatn** [comment] 2024-08-28 15:23
We have added Lucene segment-level field stats in https://github.com/elastic/elasticsearch/pull/111123. These new stats should provide a more accurate explanation of the memory usage for mappings and fields. I think we can close the issue now.

```json
"mappings": {
  "total_count": 1637,
  "total_estimated_overhead_in_bytes": 1676288,
  "total_segments": 147,
  "total_segment_fields": 20269,
  "average_fields_per_segment": 137
}
```

**Closed by dnhatn** 2024-08-28 15:23 UTC
Labels: >enhancement, Team:StorageEngine, :StorageEngine/Mapping
