### ISSUE TITLE
Bulk index tasks stuck forever

### ISSUE THREAD

**Issue by jeancornic** [elastic/elasticsearch#31099] opened 2018-06-05 10:53 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 6.1.3

**Plugins installed**: []

**JVM version** (`java -version`):

```
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system):

```
Linux *** 4.4.0-1049-aws #58-Ubuntu SMP Fri Jan 12 23:17:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Description of the problem including expected versus actual behavior**:

Seeing a weird behaviour, with bulk index actions that never finish.
They are triggered by the Elasticsearch Java client (version 6.1.3), through a `BulkRequestBuilder`, with the default timeout (1m). Seems we never enter the `ActionListener` callbacks.

I found out recently that it's linked with tasks running indefinitely. When checking the /_tasks api, I'm seeing tasks that have been running for several days (!)..

```
$ curl 'localhost:9200/_tasks?pretty&human&actions=indices:data/write/bulk&detailed'
...
    "pd5MT4eUSEqsOy_oq_q-vw" : {
      "name" : "***",
      "transport_address" : "***",
      "host" : "***",
      "ip" : "***",
      "roles" : [
        "data"
      ],
      "attributes" : {
        "availability_zone" : "us-east-1c",
        "tag" : "fresh"
      },
      "tasks" : {
        "pd5MT4eUSEqsOy_oq_q-vw:208477658" : {
          "node" : "pd5MT4eUSEqsOy_oq_q-vw",
          "id" : 208477658,
          "type" : "netty",
          "action" : "indices:data/write/bulk",
          "start_time" : "2018-04-12T21:17:45.175Z",
          "start_time_in_millis" : 1523567865175,
          "running_time" : "53.4d",
          "running_time_in_nanos" : 4622108629250516,
          "cancellable" : false
        }
      }
    },
...
```

I would expect the bulk action to run for 1min, and then timeout.

I came across several issues / PRs on github:
- https://github.com/elastic/elasticsearch/pull/28667: could it be related to the issue?
- https://github.com/elastic/elasticsearch/issues/25863: seems like a similar issue, but we're running a newer version, and we have no rejection logs in ES, so I don't believe that's it.

**Steps to reproduce**: I have no idea, it happens randomly, since we migrated from 5.6 to 6.1.3.

**Provide logs (if relevant)**: found nothing relevant nor in ES, nor in the client logs.

**Comment by jeancornic** [comment] 2018-06-14 11:44
Do you need more details? Or that I run some commands on the cluster?

I also found out recently that this bug is responsible for stuck relocations. Somehow the ongoing bulk operation prevents the relocation from finishing completely, and the workaround I found is is to close / re-open the index.

**Comment by s1monw** [comment] 2018-06-14 18:42
@bleskes this seems more of a distributed systems issue? Can you follow up

**Comment by bleskes** [comment] 2018-06-18 15:34
@jeancornic thanks. It seems these are stuck waiting for a replica that never responded. The two tickets that you mention are similar in nature, but I don't see anything here that point in that direction.

I understand that you see this regularly. Is that true? if so, can you maybe upgrade to 6.3.0 and see how it goes? it will help reduce the scope of the search. 

Some more generic questions about your setup:
1) Do you use dynamic mapping?
2) Is there anything else of note in the logs?  The replica nodes (FDW9DMoWTiOX7AeQ8xmdCA & pd5MT4eUSEqsOy_oq_q-vw) are interesting.

**Comment by jeancornic** [comment] 2018-06-19 17:10
@bleskes We see this regularly indeed, several times a week.

1. We don't use dynamic mapping
2. Investigated another task than the one in example, more recent: 

```
"WpsOgw9JTxivBHkMatVPrQ:2158610039" : {
      "node" : "WpsOgw9JTxivBHkMatVPrQ",
      "id" : 2158610039,
      "type" : "netty",
      "action" : "indices:data/write/bulk",
      "description" : "requests[671], indices[]",
      "start_time" : "2018-06-17T22:06:29.484Z",
      "start_time_in_millis" : 1529273189484,
      "running_time" : "1.7d",
      "running_time_in_nanos" : 153023445214125,
      "cancellable" : false,
      "children" : [
        {
          "node" : "WpsOgw9JTxivBHkMatVPrQ",
          "id" : 2158610093,
          "type" : "transport",
          "action" : "indices:data/write/bulk[s]",
          "status" : {
            "phase" : "rerouted"
          },
          "description" : "requests[29], index[13.1529271600000.1]",
          "start_time" : "2018-06-17T22:06:29.487Z",
          "start_time_in_millis" : 1529273189487,
          "running_time" : "1.7d",
          "running_time_in_nanos" : 153023441823453,
          "cancellable" : false,
          "parent_task_id" : "WpsOgw9JTxivBHkMatVPrQ:2158610039",
          "children" : [
            {
              "node" : "63tYulq1Q7qhsMAcQXR6Bg",
              "id" : 1928749409,
              "type" : "netty",
              "action" : "indices:data/write/bulk[s]",
              "status" : {
                "phase" : "waiting_on_primary"
              },
              "description" : "requests[29], index[13.1529271600000.1]",
              "start_time" : "2018-06-17T22:06:29.488Z",
              "start_time_in_millis" : 1529273189488,
              "running_time" : "1.7d",
              "running_time_in_nanos" : 153023440722690,
              "cancellable" : false,
              "parent_task_id" : "WpsOgw9JTxivBHkMatVPrQ:2158610093",
              "children" : [
                {
                  "node" : "FDW9DMoWTiOX7AeQ8xmdCA",
                  "id" : 2871784213,
                  "type" : "netty",
                  "action" : "indices:data/write/bulk[s][r]",
                  "status" : {
                    "phase" : "replica"
                  },
                  "description" : "requests[29], index[13.1529271600000.1]",
                  "start_time" : "2018-06-17T22:06:29.544Z",
                  "start_time_in_millis" : 1529273189544,
                  "running_time" : "1.7d",
                  "running_time_in_nanos" : 153023387248385,
                  "cancellable" : false,
                  "parent_task_id" : "63tYulq1Q7qhsMAcQXR6Bg:1928749409"
                },
                {
                  "node" : "63tYulq1Q7qhsMAcQXR6Bg",
                  "id" : 1928749487,
                  "type" : "direct",
                  "action" : "indices:data/write/bulk[s][p]",
                  "status" : {
                    "phase" : "primary"
                  },
                  "description" : "requests[29], index[13.1529271600000.1]",
                  "start_time" : "2018-06-17T22:06:29.499Z",
                  "start_time_in_millis" : 1529273189499,
                  "running_time" : "1.7d",
                  "running_time_in_nanos" : 153023430180000,
                  "cancellable" : false,
                  "parent_task_id" : "63tYulq1Q7qhsMAcQXR6Bg:1928749409"
                }
              ]
            }
          ]
        }
      ]
    }
```

In the logs (on the 3 nodes `WpsOgw9JTxivBHkMatVPrQ`, `63tYulq1Q7qhsMAcQXR6Bg` & `FDW9DMoWTiOX7AeQ8xmdCA`), I don't find anything relevant:

* indexing slowlogs, < 500ms

* some debug logs, async flush request, async roll translog generation & merge

```
...
[2018-06-17T22:11:22,131][DEBUG][o.e.i.s.IndexShard       ] [***] [13.1529271600000.1][4] submitting async flush request
...
[2018-06-17T22:06:37,917][DEBUG][o.e.i.s.IndexShard       ] [***] [13.1529271600000.1][0] submitting async roll translog generation request
...
[2018-06-17T22:06:41,358][DEBUG][o.e.i.e.InternalEngine$EngineMergeScheduler] [***] [13.1529271600000.1][4] merge segment [_7e] done: took [25.4s], [375.2 MB], [526,460 docs], [0s stopped], [17.8s throttled], [364.3 MB written], [16.5 MB/sec throttle]
...
```

Seeing also one

```
[2018-06-19T02:18:09,096][WARN ][o.e.t.n.Netty4Transport  ] [***] send message failed [channel: org.elasticsearch.transport.netty4.NettyTcpChannel@542b0ecb]
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[?:?]
```

but 4 hours after the bulk, probably unrelated.

**Comment by bleskes** [comment] 2018-06-22 12:29
@jeancornic thanks. Nothing pops up directly here, which means it's going to be a long search. It's good it happens frequently as it greatly increases to chance of finding out what its.

The the last log message you sent is important: 
```
[2018-06-19T02:18:09,096][WARN ][o.e.t.n.Netty4Transport  ] [***] send message failed [channel: org.elasticsearch.transport.netty4.NettyTcpChannel@542b0ecb]
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[?:?]
```

Can you post the full stack trace for this? can you also check other nodes for transport level logs that look suspicious?

**Comment by linyy2233** [comment] 2018-10-09 01:28
We also encountered the same problem, this task caused several nodes to load very high, and then the cluster could not write. Restart the node with high load to recover. Is there a solution? Thank you.
node hot_threads
![image](https://user-images.githubusercontent.com/39547259/46641700-9d115000-cba5-11e8-8b0f-e07e7bd78a60.png)

**Comment by linyy2233** [comment] 2018-10-09 01:50
node hot_threads
![image](https://user-images.githubusercontent.com/39547259/46642241-b36cdb00-cba8-11e8-9b8c-2648cbc54fe9.png)

**Comment by ywelsch** [comment] 2018-10-09 22:28
@linyy2233 it looks like you're having a different (unrelated) problem, possibly caused by having a very large JSON number in your document? Can you open a topic on discuss.elastic.co please for further investigation? Thanks.

Also, as no reply on original ticket, closing this.

**Closed by ywelsch** 2018-10-09 22:28 UTC
Labels: :Distributed/CRUD, >bug

**Comment by seborys** [comment] 2018-12-20 04:36
@jeancornic Did you ever get more info on this? Experiencing the same.

**Comment by ywelsch** [comment] 2018-12-20 07:43
For the case where tasks are stuck on replicas (Tasks are organized in a tree hierarchy, and the leaves are tasks with an action name `indices:data/write/bulk[s][r]`, i.e., ending in `[r]`), we found the root cause yesterday and created a fix (see https://github.com/elastic/elasticsearch/pull/36770). Note that there can be other reasons for stuck tasks, so if your leaf tasks are not replica tasks, they might be stuck for a different reason.

**Comment by linyy2233** [comment] 2019-01-06 06:05
Thanks, I changed this parameter to false and it does not appear.
numeric_detection

**Comment by IvanBoyko** [comment] 2020-03-30 20:02
We experience the same problem on 6.8.7

Is there any generic workaround how to delete stuck tasks?
