### ISSUE TITLE
Histogram aggregation of decimal values

### ISSUE THREAD

**Issue by docwarren** [elastic/elasticsearch#20150] opened 2016-08-24 22:46 UTC
For many applications, common metrics are between 0 and 1. e.g. frequency, percentage, proportion, probability. The ability to perform histogram aggregation on decimal values would be great.

**Comment by jpountz** [comment] 2016-08-25 07:23
Hi @docwarren , this is a known issue that will be addressed in the upcoming major release (5.0).

Duplicate of #4847
Fixed via #19551

**Closed by jpountz** 2016-08-25 07:23 UTC
