### ISSUE TITLE
Simple Query String: NOT operator causes all documents in index to be returned

### ISSUE THREAD

**Issue by dsem** [elastic/elasticsearch#18603] opened 2016-05-26 18:08 UTC
**Elasticsearch version**:
2.3.3

**JVM version**:
8u91

**OS version**:
Debian Jessie and CentOS 7

**Description of the problem including expected versus actual behavior**:

Including a simple query string query with the NOT operator (hyphen) causes all documents to be returned.

**Steps to reproduce**:
 1. Start from a fresh ElasticSearch instance
 ```
docker run -d -p 9200:9200 elasticsearch -Des.network.host=0.0.0.0
 ```

 2. Load some data
 ```
curl -XPUT localhost:9200/test_index -d '{"settings": {"index" {"number_of_shards": 3, "number_of_replicas": 0}}}'
curl -XPOST localhost:9200/test_index/test_doc -d '{"content": "Buffalo"}'
curl -XPOST localhost:9200/test_index/test_doc -d '{"content": "Buffalo, New York"}'
curl -XPOST localhost:9200/test_index/test_doc -d '{"content": "Canada"}'
 ```

 3. Verify normal querying works:
 ```
curl -XGET localhost:9200/test_index/test_doc/_search -d'
{
    "query": {
        "simple_query_string": {
            "query": "Buffalo"
        }
    }
}'
# The two, correct results are returned
 ```

 4. Demonstrate queries with the NOT operator don't work:
 ```
{
    "query": {
        "simple_query_string": {
            "query": "Buffalo -New"
        }
    }
}'
# Here, all three documents are returned, including one without terms specified in the query.
 ```

**Comment by dsem** [comment] 2016-05-26 18:12
Possibly related to #9633

**Comment by clintongormley** [comment] 2016-06-01 13:08
Duplicate of #4707

**Closed by clintongormley** 2016-06-01 13:08 UTC
