### ISSUE TITLE
Potential memory/cache problem in 5.5.2

### ISSUE THREAD

**Issue by natelapp** [elastic/elasticsearch#26587] opened 2017-09-11 20:54 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 5.5.2

**Plugins installed**: [x-pack (basic license)]

**JVM version** (`java -version`): 

**OS version** (`uname -a` if on a Unix-like system): CentOS 7

**Description of the problem including expected versus actual behavior**:

During periods of ingest using the bulk API (500 docs per request with a max of 5 concurrent requests) we're seeing the memory usage on the 10 ES nodes in our cluster increase slowly, but continually, until the nodes eventually OOM.

**Steps to reproduce**:

Unfortunately, I don't have the ability to provide configuration/mappings/etc. due to our elasticsearch instance being on a closed network.  I will do my best to provide as much detail as possible that might be relevant to tracking down this issue.

During these periods of ingest, regular GCs are occurring, but the trough after GC is completed is always higher than before.   Basically, the typical pattern you'd see from a memory leak.   These OOMs occurred consistently and I was able to reproduce several times through multiple cluster restarts.  In trying to track this down today, I let our process run until the nodes hit around 90% memory used and then I stopped the ingest process, basically short circuiting it right before the OOMs.   The memory on all of the nodes flatlined at 90% and didn't decrease, despite no ingest/query activity taking place.

The heap on the 10 ES nodes are set to 12gb and we're heavily favoring 'keyword' types for all but a couple of string fields.  There are no aggs or anything going against analyzed fields and our overall fielddata is very low on all the nodes.   In looking at 'fielddata', 'query_cache' and 'request_cache' stats, there is a total of a couple of gb per node -- nowhere near the 12gb configured for the jvm.  I also did a force 'flush' to make sure the translog wasn't somehow going beyond the default 512mb.  That had no effect.

I suspected there was still some cache somewhere that was causing this, so I used the 'clear cache' API to see if I could free up the ~90% memory that was still being consumed by all of the nodes.  First, I tried _only_ clearing the cache against the indices we created.  That had no effect on the memory usage.  Next I tried clearing using ```/.*/_cache/clear``` (matching against the ES .monitoring*, .tasks, etc.).  That too had no effect.  Finally, I issued a clear cache against all indices using ```/*/_cache/clear```. All of the nodes immediately dropped their memory usage to ~10%.

Are there any internal elasticsearch indices that are not exposed externally (via ```_cat/indices```, for example) that could be caching without regard to the configured cache limits (all using the defaults)?  We're using x-pack, but not any of the ML or anything else like that (though xpack.ml.enabled was true initially).   Alternatively, are there any other internal cache mechanisms that get cleared when a 'clear all' is submitted?

Any help on this is appreciated.   Thanks.

**Comment by jpountz** [comment] 2017-09-12 08:07
Would you be able to share a heap dump of the node upon OOME? Or if that is too sensitive, screenshots of a heap analysis tool showing the top consumers?

**Comment by natelapp** [comment] 2017-09-12 10:26
Unfortunately, being an ES federal user, I don't have any way of getting the heap dump or screenshots to you.  I will continue working it on my end to see if I can narrow it down further.

**Comment by jpountz** [comment] 2017-09-12 12:05
Your description of the issue suggests that memory is actually used by one of the cache, but in a way that the cache is not aware of, otherwise it would have evicted entries in order to keep a bounded size. It would be nice to find out which cache has the bug, and why.

Your bug description reminds me of https://issues.apache.org/jira/browse/LUCENE-7657 but this bug is expected to be fixed in 5.5.2.

Is there any search activity in parallel to bulk indexing? If not, then it means that this can't be the request cache or query cache.

Are you using parent/child or nested mappings? Those fields make Elasticsearch load some data-structures in memory in order to be able to resolve joins efficiently.

**Comment by natelapp** [comment] 2017-09-12 12:29
Sure.  We're happy to work to track it down.

So, we're absolutely doing some things that are less than ideal in our design that likely fall outside of the norm.   We're currently using parent/child/grandchild.  This particular OOM issue occurs when attempting to create the grandchild records for existing documents that don't have any grandchildren.   The basic flow is:

- Query for children records that don't have children of their own.  We're using "search_after" to page through the results.
- For _each_ child doc that is found from the initial query, submit a different query to find the data that is needed to create the grandchildren docs.
- Create the grandchild docs and insert them using the bulk API.

So yes, there are lots of parallel queries and inserts going on.   And yes, parent/child uses abound.  We're using nested objects in our mapping, but in my process of triaging this, I created a new index simply setting "dynamic":true and let ES define all of the data types automatically to rule out the possibility of our mapping causing the problem.  The OOMs still occurred.

I've also been in contact with the ES Federal team this morning, in case they're in a better position to be able to work this.

I've got a heap dump from an OOM this morning and will be running it through an analysis tool to figure out what the top classes are.   I'll update this ticket when I have more information.   Thanks!

**Comment by natelapp** [comment] 2017-09-12 15:22
The problem appears to be in `org.elasticsearch.indices.IndicesQueryCache$ElasticsearchLRUQueryCache`.  That's consuming almost all of the memory.

We're using the Eclipse Memory Analyzer, but aren't sure what type of information would be helpful to you in figuring out the cause.   Are there any other pieces of data from the analysis that we should pass along?

**Comment by jpountz** [comment] 2017-09-12 16:24
Good. Most likely the cache itself is not the issue, but rather some of the queries in the cache are larger than they should be. Can you check that most memory does indeed go into `org.elasticsearch.indices.IndicesQueryCache$ElasticsearchLRUQueryCache.uniqueQueries`, and see what are the largest queries this `uniqueQueries` map stores?

**Comment by natelapp** [comment] 2017-09-13 13:59
I've done a bit more digging.  I'm not very familiar with the MAT application, so forgive me if this is a bit painful in trying to interpret what I'm seeing.

- It does indeed look like it's `uniqueQueries`.  The `cache` usage is below the default 10% of heap.
- Most of the rest of the top consumers within `ElasticsearchLRUQueryCache` are `BooleanQuery` objects, with the largest consumer within those objects being `globalOrds`.  For example, the largest `BooleanQuery` objects (if i'm interpreting everything correctly) is ~3.6mb.  The `GlobalOrdinalsQuery` inside of that object is 98% of that.
- Inside some of the map entries, there appears to be memory taken up by the `<class>.<classloader>.<class>.scl.classes.elementData`.   Again, not sure if this is just noise, but figured I'd include it.
- I noticed a small thing that confused me at the `IndicesQueryCache` level.  I see the following values:
  `cacheSize`: 54550
  `cacheCount`: 55424
  `maxSize`: 10000
I know that the configuration of the cache.count is 10000, but I wasn't sure what role `cacheSize` and `cacheCount` play and if those numbers made sense.   If those are normal/expected, that's fine.   Again, just throwing things out here that aren't obvious in case there's some issue.

If there's anything else I should be looking for, please let me know.   It's also not outside the realm of possibility that we're doing something terrible in our querying.   I'll spend some time logging the queries themselves and make sure there's not something obvious on our end.

**Comment by natelapp** [comment] 2017-09-13 17:32
There aren't any obvious problems with the queries from what I can see.  The process is as I indicated above:

- From within a filter, do a `must` on a _type and a single term and a `must_not` of `has_child` (match_all).   Basically, find all docs of a given _type that don't have any children.   In my process there are a few million results that come back.
- With those 100 results in memory in our app, we're collecting the distinct values from a field in the _source of the results and submitting those values as a query (term filter) to the same index.  There are at most 200 terms.   Using the results from that query, we're constructing the children documents for each of the 100 initial results.
- Finally, we're using the bulk API to submit the new children, queuing up 500 index requests at a time with a max of 5 concurrent submits.
- Page for the next set of 100 docs that don't have children using `search_after`.

One of the oddities I've noticed is we're re-issuing the `search_after` query on the data we're modifying.  Since `search_after` is against a "live" index, the results of that paging query are continually changing, due to the children being added via the bulk requests.  A scroll would likely be a better solution here, but I'd rather figure out the cause of this issue rather than finding a work-around.

If it would help to see the actual queries we're submitting, let me know and I'll transcribe them.

**Comment by jpountz** [comment] 2017-09-14 08:43
OK I think your issue is caused by those GlobalOrdinalsQuery objects. They have to reference global ordinals instances in order to be able to work, however those global ords are not taken into account while they can take significant memory (3.6MB in your case). Multiplied by the number of cached queries, this can be an issue.

I can't think of a straightforward way to fix it, however you should be able to work around it on your end by setting `indices.queries.cache.count` to eg. 100 instead of its default value of 10000. Since your queries are ~4MB this should make sure that cached queries can't take more than 400MB (the cache might be larger than that however since it also needs to store the values that are associated with these queries). Unfortunately this is a node setting and requires nodes to be restarted in order to be taken into account.

> cacheSize: 54550
cacheCount: 55424
maxSize: 10000

`cacheSize` is the number of (query, segment) pairs that currently exist in the cache and `cacheCount` is the cumulative number of (query, segment) pairs that have been put in the cache. These numbers are only maintained in order to give usage statistics of the cache, they are not used to maintain invariants or anything. `maxSize` is the number of _unique_ queries that are allowed to live in the cache at any instant. `cacheSize` can be larger than `maxSize` if the same query is cached on multiple segments, which is common. In order to know the number of currently cached queries, you need to look up the size of the `uniqueQueries` map.

I'll think about ways to fix this issue...

**Comment by natelapp** [comment] 2017-09-14 10:13
That all makes sense.  Is `globalOrds` so large because of our use of parent/child?  And will the size of `globalOrds` increase with an increase in data?  This issue is present in our development system which contains much less data than our production environment.  I want to set `indices.queries.cache.count` to something that can support our prod data set.

I want to make sure I understand everything you've explained.   It seems like there are two pieces that are cached... the query itself and the query results.   Is that correct?  And according to your comment [here ](https://github.com/elastic/elasticsearch/issues/22742#issuecomment-274524333) and in this issue, while byte size _is_ accounted for with regards to the query results, the byte size of the query is not considered within the eviction strategy.  So, in our case, because the bytes of the results are small and the bytes of the query itself (due to the `globalOrds` ref) is large, the only way anything is going to be evicted is based on count (which defaults to 10000).  Unfortunately, we end up running out of memory on the nodes well before we hit the 10000 count limit of the cache.  Is that an accurate summary?

I know it's probably easier said than done, but is it reasonable to consider all of the data (query and results) when determining the overall byte size of the cache?   Admittedly, we're doing things with parent/child/grandchild that [fall outside of what you guys recommend](https://www.elastic.co/guide/en/elasticsearch/guide/current/parent-child-performance.html#_multigenerations_and_concluding_thoughts), however, it does seem like an issue that will likely pop up again in the future with someone else.

Also, one other thing I'm curious about is, why didn't the `/my_index/_cache/clear` call free up the memory, yet calling `/*/_cache/clear` did?

**Comment by jpountz** [comment] 2017-09-14 11:14
> That all makes sense. Is globalOrds so large because of our use of parent/child? And will the size of globalOrds increase with an increase in data?

You wouldn't need this GlobalOrdinalsQuery if you were not using parent/child. The size will indeed increase if you add more data, so you can try a more conservative size of the cache.

>  It seems like there are two pieces that are cached... the query itself and the query results. Is that correct?

Correct, the cache has 2 levels: on the first level we have queries, and on the second level we have segments. Conceptually the cache acts like a `Map<Query, Map<Segment, DocIdSet>>` where `DocIdSet` is a set of matching docs.

> And according to your comment here and in this issue, while byte size is accounted for with regards to the query results, the byte size of the query is not considered within the eviction strategy.

There are some efforts to take the query size into account, but it doesn't work all the time (which would be hard to fix) and we tend to rely on the assumption that queries are much smaller than DocIdSets, which is true for most queries, but there are exceptions like TermInSetQuery (Lucene's impl for Elasticsearch's `terms`query) or this `GlobalOrdinalsQuery`.

> Unfortunately, we end up running out of memory on the nodes well before we hit the 10000 count limit of the cache. Is that an accurate summary?

This is the most likely explanation I have for the symptoms you are observing indeed.

> is it reasonable to consider all of the data (query and results) when determining the overall byte size of the cache

This is what we would do ideally. The issue is that it feels a bit wrong to add an API for queries purely for `TermInSetQuery`and `GlobalOrdinalsQuery` which tend to be quite esoteric from a Lucene perspective. We could try to do `instanceof`checks for these two queries but it would not work all the time due to wrapper queries like `BooleanQuery`.

> Also, one other thing I'm curious about is, why didn't the /my_index/_cache/clear call free up the memory, yet calling /*/_cache/clear did?

The reason is that the cache is shared by all indices. If we had one cache per index then applying a maximum size would be complicated. For instance if we were to exceed the maximum capacity, from which cache should we evict.

So to take back the Map analogy, when you call `clear` on the entire cache then we clear the top-level `Map<Query, Map<Segment, DocIdSet>>` but if you `clear` a single index then we only clear on the second level for segments that belong to the cleared index. So we keep queries which are stored at the top level.

**Comment by natelapp** [comment] 2017-09-14 13:24
Thank you for the explanation.  I think the safest thing short-term is to try disabling query cache completely and hope that performance isn't _too_ bad.  We were already planning on moving away from parent/child, which seems to be our best bet long-term.

Thanks again for helping us figure out what was causing this.

**Comment by jpountz** [comment] 2017-09-14 13:36
We used to rely a lot on the cache for performance to be good (especially pre-2.0) but this is something that we worked on fixing in recent versions, so things shouldn't be too bad with a disabled query cache.

Thanks for reporting this bug, it can definitely be problematic in some cases and we need to find a way to fix/avoid it.

**Comment by jpountz** [comment] 2018-04-06 15:31
This was fixed in Elasticsearch 6.2 which introduced the ability for queries to opt out of caching (https://issues.apache.org/jira/browse/LUCENE-8017).

**Closed by jpountz** 2018-04-06 15:31 UTC
Labels: >bug, PITA, v5.5.2
