### ISSUE TITLE
Cluster sharhs rebalance should take into account that primary shards are evenly distributed among the dataNodes

### ISSUE THREAD

**Issue by kkewwei** [elastic/elasticsearch#57070] opened 2020-05-22 08:00 UTC
**Describe the feature**

When we wan to add some nodes to cluster, We use `index.routing.allocation.total_shards_per_node` to controll shards allocation. After reaching equilibrium, the primary shards are almost distributed on the new nodes, this is not a good phenomenon. there will be more pressure on the new nodes when indexing and recovery.

If we should add a new AllocationDecider to make distribution of the primary shards more evenly.

**Comment by DaveCTurner** [comment] 2020-05-25 17:35
Closing this as a duplicate of #41543.

**Closed by DaveCTurner** 2020-05-25 17:35 UTC
Labels: >enhancement, needs:triage
