### ISSUE TITLE
Elasticsearch identifying non polygon area as a part of polygon

### ISSUE THREAD

**Issue by aashirhaq** [elastic/elasticsearch#105591] opened 2024-02-16 12:54 UTC
### Elasticsearch Version

7.7.0

### Java Version

1.8

### OS Version

Amazon Linux 2

### Problem Description

I have created a field of type `geo_shape` in Elasticsearch. It stores an array of latitude and longitude values to create a polygon. My use case is to search for users based on their location (latitude and longitude) and determine if they are inside the polygon or not. However, sometimes Elasticsearch considers all areas as part of the polygon, which is causing issues.

### Steps to Reproduce

Below is the index mapping for the polygons:

`{
  "closed-regions": {
    "mappings": {
      "properties": {
        "location": {
          "type": "geo_shape"
        },
        "propertyIds": {
          "type": "nested",
          "properties": {
            "id": {
              "type": "integer"
            },
            "time_from": {
              "type": "date",
              "format": "HH:mm:ss"
            },
            "time_to": {
              "type": "date",
              "format": "HH:mm:ss"
            }
          }
        },
        "title": {
          "type": "text"
        }
      }
    },
    "settings": {
      "index": {
        "creation_date": "1654766211880",
        "number_of_shards": "5",
        "number_of_replicas": "1",
        "uuid": "KHMf2ceuRme6U5H1FXlYSw",
        "version": {
          "created": "7070099"
        },
        "provided_name": "closed-regions"
      }
    }
  }
}`

and the polygon data which causes the above issue are:

`{
  "location": {
    "type": "polygon",
    "coordinates": [
      [
        [
          73.154866320844,
          33.655045737865
        ],
        [
          73.064573854208,
          33.570837907056
        ],
        [
          73.063834905624,
          33.570596545721
        ],
        [
          73.06327432394,
          33.570450164212
        ],
        [
          73.062076717615,
          33.570142873979
        ],
        [
          73.06076914072,
          33.569833347802
        ],
        [
          73.058848679066,
          33.569262341725
        ],
        [
          73.057763725519,
          33.568953929827
        ],
        [
          73.056644392624,
          33.568645342228
        ],
        [
          73.055862039328,
          33.568342689948
        ],
        [
          73.054574579,
          33.567778378723
        ],
        [
          73.054262223369,
          33.567661989074
        ],
        [
          73.054004609585,
          33.567634227344
        ],
        [
          73.053747117519,
          33.567621935354
        ],
        [
          73.053178489208,
          33.567621935354
        ],
        [
          73.052352195768,
          33.567697747567
        ],
        [
          73.052742630243,
          33.567290050983
        ],
        [
          73.053382323013,
          33.566723323344
        ],
        [
          73.053886656144,
          33.566392552989
        ],
        [
          73.054605599117,
          33.565731008476
        ],
        [
          73.054960817099,
          33.565508804651
        ],
        [
          73.055367171764,
          33.565288660614
        ],
        [
          73.056599646807,
          33.565821698762
        ],
        [
          73.05680885911,
          33.565878690068
        ],
        [
          73.057062881817,
          33.565865105746
        ],
        [
          73.057245300184,
          33.565784647409
        ],
        [
          73.057352605105,
          33.565605850836
        ],
        [
          73.057352605105,
          33.565409174178
        ],
        [
          73.057009229357,
          33.564238044803
        ],
        [
          73.056975156069,
          33.563944317086
        ],
        [
          73.0569845438,
          33.56377445673
        ],
        [
          73.057024776936,
          33.563668293839
        ],
        [
          73.057085126638,
          33.563534193157
        ],
        [
          73.057266761168,
          33.563308281928
        ],
        [
          73.058436384811,
          33.562414269724
        ],
        [
          73.059337770992,
          33.561645411825
        ],
        [
          73.059998005629,
          33.560782848208
        ],
        [
          73.060834854841,
          33.559783759747
        ],
        [
          73.061986863613,
          33.558357747695
        ],
        [
          73.061840683222,
          33.558117469051
        ],
        [
          73.061685115099,
          33.557867131521
        ],
        [
          73.061530888081,
          33.557619028432
        ],
        [
          73.061351180077,
          33.557380982907
        ],
        [
          73.061025291681,
          33.557025589774
        ],
        [
          73.060698062181,
          33.556678018346
        ],
        [
          73.061029314995,
          33.556813247267
        ],
        [
          73.061646223068,
          33.557071410983
        ],
        [
          73.062096834183,
          33.557179817162
        ],
        [
          73.062728494406,
          33.557326221167
        ],
        [
          73.063460737467,
          33.556190745437
        ],
        [
          73.063590824604,
          33.556047692318
        ],
        [
          73.063662215632,
          33.55595028614
        ],
        [
          73.06371152401,
          33.555838700226
        ],
        [
          73.063755780458,
          33.555747056475
        ],
        [
          73.063766509295,
          33.555659883061
        ],
        [
          73.063732981682,
          33.555447537197
        ],
        [
          73.063662215632,
          33.555235016184
        ],
        [
          73.063624352217,
          33.555143546421
        ],
        [
          73.063640754648,
          33.555029374976
        ],
        [
          73.063785284758,
          33.554608207121
        ],
        [
          73.063924759626,
          33.554269566978
        ],
        [
          73.06406510021,
          33.553930279378
        ],
        [
          73.064103126526,
          33.553766633624
        ],
        [
          73.064215779305,
          33.553224579952
        ],
        [
          73.064344525337,
          33.552499228584
        ],
        [
          73.064387014974,
          33.552276169939
        ],
        [
          73.064685165882,
          33.550573497332
        ],
        [
          73.064879626036,
          33.549645822733
        ],
        [
          73.064846098423,
          33.549103743206
        ],
        [
          73.064856827259,
          33.548937206751
        ],
        [
          73.064917176962,
          33.548722608967
        ],
        [
          73.065226972103,
          33.547926804196
        ],
        [
          73.065358128653,
          33.547546136301
        ],
        [
          73.065309841438,
          33.547295768136
        ],
        [
          73.065229362747,
          33.547072224519
        ],
        [
          73.065052321057,
          33.546466741503
        ],
        [
          73.065036225319,
          33.546381794182
        ],
        [
          73.065025494827,
          33.546229782978
        ],
        [
          73.06502817745,
          33.546118009863
        ],
        [
          73.06502817745,
          33.546024120334
        ],
        [
          73.065068416795,
          33.54588999226
        ],
        [
          73.065384966313,
          33.545143342173
        ],
        [
          73.065350092214,
          33.54505839355
        ],
        [
          73.065283026638,
          33.545002506253
        ],
        [
          73.064534574811,
          33.544971209351
        ],
        [
          73.063987319712,
          33.545036038636
        ],
        [
          73.06363874267,
          33.544953325402
        ],
        [
          73.063330241021,
          33.544901909028
        ],
        [
          73.062278842412,
          33.542778162487
        ],
        [
          73.062099236671,
          33.542429415962
        ],
        [
          73.062008321285,
          33.542302312104
        ],
        [
          73.06190340519,
          33.542185739669
        ],
        [
          73.061798782891,
          33.542024778806
        ],
        [
          73.061586855671,
          33.541772159068
        ],
        [
          73.061535885834,
          33.541693913867
        ],
        [
          73.061503694357,
          33.541615668595
        ],
        [
          73.06144467665,
          33.541354105314
        ],
        [
          73.061409802551,
          33.541155137844
        ],
        [
          73.06146517396,
          33.540827946092
        ],
        [
          73.061538565559,
          33.540524698566
        ],
        [
          73.061568074412,
          33.540433038572
        ],
        [
          73.061637822611,
          33.540319022346
        ],
        [
          73.061516135931,
          33.540236627714
        ],
        [
          73.06140884757,
          33.540430008271
        ],
        [
          73.06119158864,
          33.540380824818
        ],
        [
          73.059708327055,
          33.541687530243
        ],
        [
          73.059800863266,
          33.541751244203
        ],
        [
          73.059461563826,
          33.542004981786
        ],
        [
          73.059405237436,
          33.541961388158
        ],
        [
          73.059263080359,
          33.542082108922
        ],
        [
          73.058805763721,
          33.541627169607
        ],
        [
          73.058292727899,
          33.541486004846
        ],
        [
          73.057873696089,
          33.54135219284
        ],
        [
          73.057523667812,
          33.541067155024
        ],
        [
          73.057590723038,
          33.540371882369
        ],
        [
          73.05792465806,
          33.539819684346
        ],
        [
          73.058679699898,
          33.539854336552
        ],
        [
          73.059202730656,
          33.53915234721
        ],
        [
          73.059352934361,
          33.538710806406
        ],
        [
          73.059497773647,
          33.538278206014
        ],
        [
          73.059977889061,
          33.537998747245
        ],
        [
          73.060368150473,
          33.538552074731
        ],
        [
          73.060640394688,
          33.538501772378
        ],
        [
          73.060942143202,
          33.538448116504
        ],
        [
          73.061347156763,
          33.538101588177
        ],
        [
          73.061757534742,
          33.537749469261
        ],
        [
          73.061998933554,
          33.537563907604
        ],
        [
          73.061908153288,
          33.537428002301
        ],
        [
          73.061108440161,
          33.537815421802
        ],
        [
          73.060958504734,
          33.537159719262
        ],
        [
          73.060631006956,
          33.536485182856
        ],
        [
          73.060782551765,
          33.536435997158
        ],
        [
          73.060533106327,
          33.535905013408
        ],
        [
          73.060282319784,
          33.535374026398
        ],
        [
          73.059857189655,
          33.534828503715
        ],
        [
          73.059418742871,
          33.534405298568
        ],
        [
          73.059035092592,
          33.534180132114
        ],
        [
          73.058964014053,
          33.533996798573
        ],
        [
          73.058568388224,
          33.533768748991
        ],
        [
          73.058127164841,
          33.533538463018
        ],
        [
          73.057283610106,
          33.533102483041
        ],
        [
          73.057133406401,
          33.53305553122
        ],
        [
          73.056973814964,
          33.533025347893
        ],
        [
          73.056712299585,
          33.533013050979
        ],
        [
          73.056405186653,
          33.533051059617
        ],
        [
          73.055828511715,
          33.533130430541
        ],
        [
          73.055343031883,
          33.533200858202
        ],
        [
          73.055076661824,
          33.533291233296
        ],
        [
          73.054540137217,
          33.533514812558
        ],
        [
          73.052840530872,
          33.534436127689
        ],
        [
          73.05261656642,
          33.53418125
        ],
        [
          73.05239662528,
          33.533891716977
        ],
        [
          73.051997010579,
          33.533237574187
        ],
        [
          73.051420301199,
          33.53219138958
        ],
        [
          73.051417564004,
          33.53177087898
        ],
        [
          73.051418960094,
          33.531721865275
        ],
        [
          73.051473945379,
          33.531614545076
        ],
        [
          73.051516860724,
          33.531523993554
        ],
        [
          73.051687180996,
          33.531294819526
        ],
        [
          73.055013120174,
          33.531434559859
        ],
        [
          73.056163787842,
          33.531288111984
        ],
        [
          73.056183904409,
          33.53082976207
        ],
        [
          73.056213408709,
          33.530370291791
        ],
        [
          73.056261688471,
          33.529453579803
        ],
        [
          73.056068569422,
          33.52910030771
        ],
        [
          73.055892884731,
          33.52875485987
        ],
        [
          73.055548220873,
          33.528059488187
        ],
        [
          73.055336326361,
          33.527623480582
        ],
        [
          73.055129796267,
          33.527181880895
        ],
        [
          73.055136501789,
          33.526740278953
        ],
        [
          73.055144548416,
          33.526309854637
        ],
        [
          73.056278382304,
          33.526311767444
        ],
        [
          73.056289112796,
          33.525826559294
        ],
        [
          73.057417797557,
          33.525828472112
        ],
        [
          73.057439258541,
          33.525121896864
        ],
        [
          73.05841036808,
          33.524969848271
        ],
        [
          73.059363663197,
          33.524917948351
        ],
        [
          73.059517890215,
          33.524911240315
        ],
        [
          73.059666752815,
          33.524921302369
        ],
        [
          73.05996628944,
          33.524943016139
        ],
        [
          73.060577927492,
          33.524969848271
        ],
        [
          73.06062027812,
          33.525001798762
        ],
        [
          73.060624301434,
          33.525047636952
        ],
        [
          73.060813397169,
          33.525001798762
        ],
        [
          73.06099105144,
          33.524987736355
        ],
        [
          73.061270044235,
          33.524960904228
        ],
        [
          73.061403483152,
          33.524961550575
        ],
        [
          73.061591959,
          33.525139784916
        ],
        [
          73.061913873764,
          33.525296305215
        ],
        [
          73.061994352455,
          33.525305249224
        ],
        [
          73.062144579345,
          33.525072704702
        ],
        [
          73.062646687031,
          33.524931364423
        ],
        [
          73.06349426508,
          33.524870992086
        ],
        [
          73.064136654139,
          33.525112481179
        ],
        [
          73.064306459684,
          33.524916183998
        ],
        [
          73.064498752356,
          33.524469626778
        ],
        [
          73.064682026909,
          33.523963637609
        ],
        [
          73.064846098423,
          33.523490242888
        ],
        [
          73.064911812544,
          33.523378440368
        ],
        [
          73.064992278814,
          33.523266637705
        ],
        [
          73.06511297822,
          33.523149244752
        ],
        [
          73.06526683873,
          33.523028969218
        ],
        [
          73.065927028656,
          33.522494077348
        ],
        [
          73.06621670723,
          33.522231338173
        ],
        [
          73.066393540405,
          33.522058513358
        ],
        [
          73.066577464342,
          33.52181430797
        ],
        [
          73.067150040101,
          33.522134540247
        ],
        [
          73.067569881678,
          33.52238339158
        ],
        [
          73.067804600122,
          33.522577283744
        ],
        [
          73.067874348321,
          33.522657782318
        ],
        [
          73.067922592163,
          33.523096697379
        ],
        [
          73.067907840014,
          33.523327011161
        ],
        [
          73.067772408645,
          33.523878668173
        ],
        [
          73.068496616672,
          33.524138048296
        ],
        [
          73.068712502718,
          33.524186769328
        ],
        [
          73.068782240152,
          33.524208011619
        ],
        [
          73.068846613169,
          33.524247142142
        ],
        [
          73.068856088159,
          33.524334818905
        ],
        [
          73.068748783237,
          33.524661278246
        ],
        [
          73.06853953864,
          33.52502798453
        ],
        [
          73.06814789772,
          33.525311485573
        ],
        [
          73.068019109772,
          33.52534549725
        ],
        [
          73.067569881678,
          33.52571396497
        ],
        [
          73.06699052453,
          33.526152218182
        ],
        [
          73.066712915897,
          33.526392585711
        ],
        [
          73.066591954317,
          33.52657976098
        ],
        [
          73.067187496631,
          33.527089560422
        ],
        [
          73.06728407106,
          33.527241605289
        ],
        [
          73.067364549751,
          33.527465200194
        ],
        [
          73.0674277246,
          33.527786704199
        ],
        [
          73.067461252213,
          33.528116504404
        ],
        [
          73.068418800831,
          33.528823055184
        ],
        [
          73.068142533302,
          33.529778901877
        ],
        [
          73.069208711386,
          33.530246200859
        ],
        [
          73.068881481886,
          33.530810757265
        ],
        [
          73.068603873253,
          33.531317177994
        ],
        [
          73.068416220785,
          33.531449564464
        ],
        [
          73.067982941866,
          33.532061711694
        ],
        [
          73.067567199469,
          33.532408264232
        ],
        [
          73.067194372416,
          33.532711217087
        ],
        [
          73.067009299994,
          33.533217626684
        ],
        [
          73.066844203686,
          33.53364960612
        ],
        [
          73.066731533519,
          33.53378375319
        ],
        [
          73.066516923676,
          33.533850826648
        ],
        [
          73.066682070494,
          33.535911720592
        ],
        [
          73.066888600588,
          33.536925617177
        ],
        [
          73.067340552807,
          33.537079880444
        ],
        [
          73.068343698978,
          33.537250911136
        ],
        [
          73.068986088037,
          33.537686870192
        ],
        [
          73.070304393768,
          33.53636668999
        ],
        [
          73.071597218514,
          33.535047607501
        ],
        [
          73.072038441896,
          33.535308071994
        ],
        [
          73.072012960911,
          33.536339861394
        ],
        [
          73.072012960911,
          33.537341456659
        ],
        [
          73.072045147419,
          33.539345730193
        ],
        [
          73.071154654026,
          33.539715727643
        ],
        [
          73.070296347141,
          33.540060013878
        ],
        [
          73.070178329945,
          33.540132671513
        ],
        [
          73.069809526205,
          33.540181855107
        ],
        [
          73.06971564889,
          33.540207564702
        ],
        [
          73.069648593664,
          33.540545142155
        ],
        [
          73.069548010826,
          33.540869304693
        ],
        [
          73.06932002306,
          33.541062683835
        ],
        [
          73.069267719984,
          33.541237060031
        ],
        [
          73.069301420971,
          33.541300128098
        ],
        [
          73.069228827953,
          33.541315305646
        ],
        [
          73.069183385558,
          33.541349311028
        ],
        [
          73.069164454937,
          33.541756833144
        ],
        [
          73.069051802158,
          33.541801544664
        ],
        [
          73.068944513798,
          33.542141351458
        ],
        [
          73.069066554308,
          33.542397323456
        ],
        [
          73.069149702787,
          33.542404030136
        ],
        [
          73.069203346968,
          33.542704712408
        ],
        [
          73.069246262312,
          33.542863436458
        ],
        [
          73.069282472134,
          33.543091462046
        ],
        [
          73.069332093,
          33.543224476695
        ],
        [
          73.069393783808,
          33.543300484974
        ],
        [
          73.069416582584,
          33.543364197745
        ],
        [
          73.06942731142,
          33.543471503357
        ],
        [
          73.069440722466,
          33.543631343762
        ],
        [
          73.06946888566,
          33.543955494725
        ],
        [
          73.069743812084,
          33.543948788165
        ],
        [
          73.069782704115,
          33.544413775046
        ],
        [
          73.069824278355,
          33.544877641676
        ],
        [
          73.070349991322,
          33.544842991484
        ],
        [
          73.070395588875,
          33.545728243654
        ],
        [
          73.069886232793,
          33.545941084951
        ],
        [
          73.069912380858,
          33.546240637187
        ],
        [
          73.070277217591,
          33.547081166275
        ],
        [
          73.070140779018,
          33.547215938681
        ],
        [
          73.070163577795,
          33.547334416673
        ],
        [
          73.070186376572,
          33.547461836219
        ],
        [
          73.070423752069,
          33.547698791366
        ],
        [
          73.070253431797,
          33.547932392739
        ],
        [
          73.070138096809,
          33.548079930122
        ],
        [
          73.070050925016,
          33.548153698719
        ],
        [
          73.069692485261,
          33.548333002952
        ],
        [
          73.069572150707,
          33.548472244211
        ],
        [
          73.069498389959,
          33.548473361913
        ],
        [
          73.069569084601,
          33.549343400757
        ],
        [
          73.069574449848,
          33.54955352625
        ],
        [
          73.069399148226,
          33.550381257149
        ],
        [
          73.069220054935,
          33.551122099005
        ],
        [
          73.069089353085,
          33.5516978703
        ],
        [
          73.068908303976,
          33.552266757211
        ],
        [
          73.068670928478,
          33.552913875489
        ],
        [
          73.068332970142,
          33.553737575163
        ],
        [
          73.068048655987,
          33.554338859789
        ],
        [
          73.06846305728,
          33.554546737887
        ],
        [
          73.068641424179,
          33.554466269005
        ],
        [
          73.068819791079,
          33.554386917673
        ],
        [
          73.069077283144,
          33.554317624901
        ],
        [
          73.069385737181,
          33.554648441505
        ],
        [
          73.069777339697,
          33.554466269005
        ],
        [
          73.069873899221,
          33.554422681663
        ],
        [
          73.069957047701,
          33.554409270168
        ],
        [
          73.070113956928,
          33.554377976674
        ],
        [
          73.070359379053,
          33.554338859789
        ],
        [
          73.070451915264,
          33.554322095404
        ],
        [
          73.070583254706,
          33.554331979407
        ],
        [
          73.070969581604,
          33.556277918315
        ],
        [
          73.07136118412,
          33.557547503085
        ],
        [
          73.071696460247,
          33.558834950274
        ],
        [
          73.071898967028,
          33.560352593409
        ],
        [
          73.07283103466,
          33.561206395645
        ],
        [
          73.076473342644,
          33.561252040021
        ],
        [
          73.079283088446,
          33.561378496121
        ],
        [
          73.080341219902,
          33.561423197487
        ],
        [
          73.080358654261,
          33.561547243657
        ],
        [
          73.080345243216,
          33.561675759771
        ],
        [
          73.080274164677,
          33.561994255404
        ],
        [
          73.080530315638,
          33.562278106662
        ],
        [
          73.080765539501,
          33.562593072905
        ],
        [
          73.080983608961,
          33.562932972541
        ],
        [
          73.081131130457,
          33.563208998139
        ],
        [
          73.081281334162,
          33.563486140362
        ],
        [
          73.081568330526,
          33.564015837136
        ],
        [
          73.07970687747,
          33.564773499026
        ],
        [
          73.079018890858,
          33.565071868476
        ],
        [
          73.078238368034,
          33.565542329074
        ],
        [
          73.077652305365,
          33.565936798811
        ],
        [
          73.077237904072,
          33.566211697335
        ],
        [
          73.077052746162,
          33.566383613232
        ],
        [
          73.076932132244,
          33.566500004604
        ],
        [
          73.07687446475,
          33.566558112929
        ],
        [
          73.076828867197,
          33.566617338682
        ],
        [
          73.076649159193,
          33.566940285939
        ],
        [
          73.076548576355,
          33.567229708233
        ],
        [
          73.07635679841,
          33.567714683957
        ],
        [
          73.075415343046,
          33.567210711433
        ],
        [
          73.074512779713,
          33.566729085274
        ],
        [
          73.07279214263,
          33.565195909405
        ],
        [
          73.072692900896,
          33.565647372183
        ],
        [
          73.07265534997,
          33.566048546284
        ],
        [
          73.072489053011,
          33.566048546284
        ],
        [
          73.072309868636,
          33.566079660946
        ],
        [
          73.072266429663,
          33.566082070498
        ],
        [
          73.072257041931,
          33.566031784172
        ],
        [
          73.072187304497,
          33.565979262868
        ],
        [
          73.072041606332,
          33.565882985367
        ],
        [
          73.071544915438,
          33.565961383267
        ],
        [
          73.071114420891,
          33.56602843175
        ],
        [
          73.071088939905,
          33.565389234102
        ],
        [
          73.071066141129,
          33.564738856813
        ],
        [
          73.070716112852,
          33.564100767118
        ],
        [
          73.070049583912,
          33.563649296255
        ],
        [
          73.06938841939,
          33.563201175563
        ],
        [
          73.06806743145,
          33.562309397295
        ],
        [
          73.067874312401,
          33.562701646766
        ],
        [
          73.067699968815,
          33.563069309182
        ],
        [
          73.067053556442,
          33.563610183569
        ],
        [
          73.066456764936,
          33.564058302137
        ],
        [
          73.066120147705,
          33.564219221954
        ],
        [
          73.06576743722,
          33.564376788983
        ],
        [
          73.066016882658,
          33.564780203968
        ],
        [
          73.066271692514,
          33.565166854789
        ],
        [
          73.066822886467,
          33.565928976482
        ],
        [
          73.066934198141,
          33.566132356794
        ],
        [
          73.067024052143,
          33.566342441449
        ],
        [
          73.067066967487,
          33.566496652199
        ],
        [
          73.067083060741,
          33.566653097607
        ],
        [
          73.06707338019,
          33.566973635203
        ],
        [
          73.066604286432,
          33.568162781226
        ],
        [
          73.066425919533,
          33.568753908479
        ],
        [
          73.06626859328,
          33.569351561673
        ],
        [
          73.065969944,
          33.569732779491
        ],
        [
          73.065524697304,
          33.570076946114
        ],
        [
          73.064573854208,
          33.570837907056
        ],
        [
          73.154867738485,
          33.655045179705
        ],
        [
          73.167210753664,
          33.484962369701
        ],
        [
          72.952257535101,
          33.481812553725
        ],
        [
          72.956721419831,
          33.640306249188
        ],
        [
          73.154866320844,
          33.655045737865
        ]
      ]
    ]
  }
}`

User location is: 
longitude: `73.0623258`
latitude: `33.5573597`

Elasticsearch returns a point within a polygon area, but the user's location is outside of that polygon area. 

I am using the following elasticsearch query for this:

`{
  "size": 500,
  "query": {
    "bool": {
      "filter": {
        "geo_shape": {
          "location": {
            "shape": {
              "type": "Point",
              "coordinates": [
                73.0623258,
                33.5573597
              ]
            },
            "relation": "contains"
          }
        }
      }
    }
  },
  "script_fields": {
    "propertyIds": {
      "script": {
        "id": "find-polygon-by-coordinates",
        "params": {
          "current_time": "16:58:06"
        }
      }
    }
  }
}`

Please help me find the solution to my problem.

**Comment by iverase** [comment] 2024-02-19 12:16
Hello, 

I had a look into this issue as I could not reproduce it with the latest version of Elasticsearch. It seems that is a bug in older version, in particular is a bug when "normalising" the polygon which produces a buggy polygon. This was fixed as a side effect of this change: https://github.com/elastic/elasticsearch/pull/84229

Therefore in order to fix your problem, you need to upgrade to a more recent version, 8.2+. Therefore there is nothing for us to do here so I hope you don't mind I am closing the issue.

**Closed by iverase** 2024-02-19 12:16 UTC
Labels: >bug, :Analytics/Geo
