### ISSUE TITLE
[CI] IndexRecoveryIT testRecoverLocallyUpToGlobalCheckpoint failing

### ISSUE THREAD

**Issue by n1v0lg** [elastic/elasticsearch#89235] opened 2022-08-10 08:57 UTC
Looks very similar to https://github.com/elastic/elasticsearch/issues/79923

There was a fix for the above issue  https://github.com/elastic/elasticsearch/pull/81312

**Build scan:**
https://gradle-enterprise.elastic.co/s/nwclvtpj6iwi4/tests/:server:internalClusterTest/org.elasticsearch.indices.recovery.IndexRecoveryIT/testRecoverLocallyUpToGlobalCheckpoint

**Reproduction line:**
`./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.indices.recovery.IndexRecoveryIT.testRecoverLocallyUpToGlobalCheckpoint" -Dtests.seed=75D02C5C4B4D3BB2 -Dtests.locale=id-ID -Dtests.timezone=Asia/Tokyo -Druntime.java=17`

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.indices.recovery.IndexRecoveryIT&tests.test=testRecoverLocallyUpToGlobalCheckpoint

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: <72L>
     but: was <71L>

  at __randomizedtesting.SeedInfo.seed([75D02C5C4B4D3BB2:8F8BA1185C489FFA]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.indices.recovery.IndexRecoveryIT.testRecoverLocallyUpToGlobalCheckpoint(IndexRecoveryIT.java:1095)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by pxsalehi** [comment] 2022-11-14 14:55
I am not able to reproduce this. It fails rarely (last failure was three months ago!) but it clearly still fails after the last fix (https://github.com/elastic/elasticsearch/pull/81312). Before that fix the expected/actual local recovered ops:
```java
assertThat((long) localRecoveredOps.get(), equalTo(lastSyncedGlobalCheckpoint - localCheckpointOfSafeCommit));
```
 were quite different, but after that fix they are always off by one, when it fails. I'm hoping this helps finding out some corner case in `getLocalCheckpointOfSafeCommit(IndexCommit safeIndexCommit)` which was added in the last fix, or at least being confident that this is just a test issue and not an actual bug. WDYT @fcofdez?

**Comment by pxsalehi** [comment] 2023-04-11 16:40
The off-by-one failure hasn't happened in roughly four months! However, the one failure since then is [this one](https://gradle-enterprise.elastic.co/s/bwgq2wlaxttcy/tests/:server:internalClusterTest/org.elasticsearch.indices.recovery.IndexRecoveryIT/testRecoverLocallyUpToGlobalCheckpoint?top-execution=1) which fails at [this assertion](https://github.com/elastic/elasticsearch/blob/e6b925eb41cde22dd4e6dfd6a6c4ba3b6f1e81c4/server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java#L1063).

I think the issue is that the test might require some more synchronization around when to read the recovery state of the attempt to recover locally, before the recovery stats are reseted due to a restarted recovery.

**Comment by pxsalehi** [comment] 2023-05-26 12:26
Three months and no failures. Closing this.
<img width="1092" alt="image" src="https://github.com/elastic/elasticsearch/assets/3340727/59656f8e-7eb7-4ff4-9cad-5b3e2f242cee">

**Closed by pxsalehi** 2023-05-26 12:26 UTC
Labels: >test-failure, :Distributed/Recovery, Team:Distributed
