### ISSUE TITLE
Build es source code failed with an exception

### ISSUE THREAD

**Issue by msjbear** [elastic/elasticsearch#23279] opened 2017-02-21 02:55 UTC
When run `gradle idea`, Build failed with an exception

**Description of the problem including expected versus actual behavior**:
```
=======================================
Elasticsearch Build Hamster says Hello!
=======================================
  Gradle Version        : 2.14.1
  OS Info               : Windows 7 6.1 (amd64)
  JDK Version           : Oracle Corporation 1.8.0_112 [Java HotSpot(TM) 64-Bit
Server VM 25.112-b15]
  JAVA_HOME             : C:\Software\Java\jdk1.8.0_112
Incremental java compilation is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Build file 'H:\Github\elasticsearch\plugins\repository-hdfs\build.gradle' line:
84

* What went wrong:
A problem occurred evaluating project ':plugins:repository-hdfs'.
> Could not get unknown property 'HADOOP_HOME' for task ':plugins:repository-hdf
s:integTest' of type org.elasticsearch.gradle.test.RestIntegTestTask.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 11.568 secs
```

**Comment by jasontedor** [comment] 2017-02-21 02:59
Please ask questions on the [forum](https://discuss.elastic.co). We build on our CI continuously and have never seen this problem. Closing as not a bug.

**Closed by jasontedor** 2017-02-21 02:59 UTC
