### ISSUE TITLE
rejected task exception with ES Java BulkProcessor

### ISSUE THREAD

**Issue by rrphotosoft** [elastic/elasticsearch#14911] opened 2015-11-21 15:02 UTC
Hi,
I am using Elasticsearch 1.4.4.and processing several documents using a BlockingThreadPoolExecutor.
The last step in the process(on each thread) is to index the document into elasticsearch. For this I'm using the BulkProcessor API.
I instantiate a bulkprocessor in the main thread, and pass it into the thread pool, and it is used by all the threads. I did this because I noticed that it internally uses a 'synchronized' add method, and the class description mentions "thread safe".

My problem is that I'm seeing a RejectedTaskExecution exception. Sometimes it shows up after just a couple of hundred requests at other times after several thousand. Irrespective, it shows up each and every time. 

My blockingthreadpoolexecutor uses a semaphore internally to throttle requests. And it is backed by an ArrayBlockingQueue. 

To ensure that the issue was related  with the call to BulkProcessor, I replaced the call to BulkProcessor.add(....) with a simple Thread.sleep(10,TimeUnit.seconds). My threadpoolexecutor works as expected.

I am including the relevant code below.
I hope I'm not doing something wrong, but I'm new to ES on the java api, any help is appreciated.

    BlockingThreadPoolExecutor.java

    public class BlockingThreadPoolExecutor extends ThreadPoolExecutor {
	private final Semaphore semaphore;

	public BlockingThreadPoolExecutor(int corePoolSize, int maximumPoolSize,
			long keepAliveTime, TimeUnit unit, BlockingQueue<Runnable> workQueue) {
		super(corePoolSize, maximumPoolSize, keepAliveTime, unit, workQueue);
		semaphore = new Semaphore(corePoolSize + 50);
	}

	@Override
	protected void beforeExecute(Thread t, Runnable r) {
		super.beforeExecute(t, r);
	}

	@Override
	public void execute(final Runnable task) {
		boolean acquired = false;
		
		do {
			try {
				semaphore.acquire();
				
				acquired = true;
				
			} catch (final InterruptedException e) {
				
			}
		} while (!acquired);
		try {
			
			super.execute(task);
		} catch (final RejectedExecutionException e) {
			semaphore.release();
			throw e;
		}
		
	}

	@Override
	protected void afterExecute(Runnable r, Throwable t) {
		super.afterExecute(r, t);
		if (t != null) {
			t.printStackTrace();
		}
		semaphore.release();
	}
    }
 

This is the main class from where everything is executed.

    Main.java

    public class Main{
    public static void main(String[] args){
             
              BulkProcessor processor = BulkProcessor
				.builder(ElasticClientHolder.getInstance(), new Listener() {

					@Override
					public void beforeBulk(long executionId, BulkRequest request) {
						// TODO Auto-generated method stub

					}

					@Override
					public void afterBulk(long executionId,
							BulkRequest request, Throwable failure) {
						// TODO Auto-generated method stub
				
					}

					@Override
					public void afterBulk(long executionId,
							BulkRequest request, BulkResponse response) {
						// TODO Auto-generated method stub
					}
				}).setBulkActions(500).build();
	     
              	
             
             BlockingQueue<Runnable> blockingQueue = new ArrayBlockingQueue<Runnable>(
				50);
	     BlockingThreadPoolExecutor executor = new BlockingThreadPoolExecutor(
				1, 2, 5000, TimeUnit.MILLISECONDS, blockingQueue);

            for(int i=0; i < 10000; i++){
                     
                      MyBulkRunnable runnable = new MyBulkRunnable(processor);
                     executor.execute(runnable);
                      
            }
            
           executor.shutDown();
           while(!executor.isTerminated){
           }
           try{
           processor.awaitClose(30l,TimeUnit.Seconds);
           }
           catch(Exception e){
           }
    }

    public static class MyBulkRunnable implements Runnable {

		private final BulkProcessor processor;

		public MyBulkRunnable(BulkProcessor processor){
			this.processor = processor;
		}

		@Override
		public void run() {
			// TODO Auto-generated method stub
			
			this.processor.add(new IndexRequest("test_index",
					"test_type").source(new HashMap<String, Object>() {
				{
					put("test_thread", Thread.currentThread().getId());
				}
			}));
			
		}

	}

    }

**Comment by danielmitterdorfer** [comment] 2015-11-21 21:02
Hi @rrphotosoft 

I see what you are trying to achieve. You want to issue 10.000 index requests via the bulk API. However, the problem is that you are doing something slightly different, namely issuing 10.000 index requests from 10.000 threads. :) That's also the reason why you are getting `RejectedExecutionException`: you are completely overwhelming the poor pool.

Fortunately, it should be much simpler to solve your problem. You can see an example in the [Client API documentation](https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/java-docs-bulk-processor.html):

```
//Assuming you want to wait until all requests have finished
int numRequests = 10000;
CountDownLatch latch = new CountDownLatch(numRequests);

BulkProcessor bulkProcessor = BulkProcessor.builder(
        client,  
        new BulkProcessor.Listener() {
            @Override
            public void beforeBulk(long executionId,
                                   BulkRequest request) {  
            } 

            @Override
            public void afterBulk(long executionId,
                                  BulkRequest request,
                                  BulkResponse response) {
              latch.countDown();  
            } 

            @Override
            public void afterBulk(long executionId,
                                  BulkRequest request,
                                  Throwable failure) {
              latch.countDown(); // also count down on failure  
            } 
        })
        .setBulkActions(500) 
        .setBulkSize(new ByteSizeValue(1, ByteSizeUnit.GB)) 
        .setFlushInterval(TimeValue.timeValueSeconds(5)) 
        .setConcurrentRequests(1) 
        .build();

for (int requestId = 0; requestId < numRequests; requestId++) {
     processor.add(new IndexRequest("test_index", "test_type").source(Collections.singletonMap("request", requestId)));
}

System.out.println("All indexing requests issued. Waiting for responses...");
latch.await();
System.out.println("Indexing finished");
```

That's just adapted from the docs. I hope this gets you started.

Btw, we're about to add automatic backoff in bulk processor soon if  (see #14620) so it's even less likely that you encounter `RejectedExecutionException`. However, this feature is likely to be included just in Elasticsearch 2.2.0+.

Does this solve your problem? If not, I suggest you create a new discussion in the [Elasticsearch user forum](https://discuss.elastic.co/c/elasticsearch) and we close this ticket as I don't think this is an issue with Elasticsearch.

**Comment by rrphotosoft** [comment] 2015-11-22 03:24
Hi,
Thanks for your reply and the code snippet. 
In my initial post, I've set the core threadpool size to 1 and the max to 2. 
I have also tested this code with the Runnable  doing a simple (Thread.sleep) or some other task (like couting down a million integers). In each of these cases I never see a task rejected exception.
By "overwhelming the pool" do you mean, I'm overwhelming the <b>ES threadpool</b> ? 
Thanks.
RrPhotosoft.

**Comment by danielmitterdorfer** [comment] 2015-11-22 10:47
Hi @rrphotosoft,

I should have run your code earlier. My first assumption was not entirely correct. First things first, you don't overwhelm any thread pool in Elasticsearch but your own thread pool.

The problem is that you have a race condition in your code. Your queue can take 50 runnables but the semaphore, which you seem to use for flow control, allows 50 + corePoolSize method entries. Consider this situation: The queue is full (50 entries), the semaphore allow count is zero and the pool is full. A runnable has finished, you release the semaphore in `#afterExecute()` (which is invoked from the pool thread),  `semaphore.acquire()` (in the main thread) passes and passes another runnable to #execute. The thing is that the pool has still some work to do after `#afterExecute()` and your race condition hits exactly this small window of time.

To avoid the race, replace the line:

```semaphore = new Semaphore(corePoolSize + 50);```

with

```semaphore = new Semaphore(50);```

You won't hit `RejectedExecutionException`any more.

I also don't know if this is just a minimalistic example to reproduce the problem but IMHO it won't buy you much to add entries from multiple threads to the bulk processor. I'd just go with a single thread that adds all index requests. With the single threaded approach your code gets *much* simpler and you also avoid running into lock contention issues within the bulk processor.

The `Retry` class you've mentioned is brand new and meant to be used internally in `BulkProcessor` and not exposed in the client API but as the PR is not closed yet it is not sure whether this implementation is really coming as I've implemented it.

I am closing this issue now as there is no problem in Elasticsearch to me. I hope I could help. :)

**Closed by danielmitterdorfer** 2015-11-22 10:47 UTC

**Comment by rrphotosoft** [comment] 2015-11-22 10:50
Hi,
I came across the solution just as you posted the response. Thanks for your help. 
Rrphotosoft.

**Comment by danielmitterdorfer** [comment] 2015-11-22 11:22
Another race condition :) You're welcome. Glad I could help.
