### ISSUE TITLE
[feature request]reject clients' read/write requests when cluster avalanche effects happens(may call this the safe mode of cluster)

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#22736] opened 2017-01-23 03:02 UTC
**Describe the feature**:
**1. cluster deployment:**
    1. usually I deploy cluster this way: with some dedicated master nodes(usually 3) with some dedicated data noeds and with some dedicated gateway nodes.
    2. close sniff or I customerized client logic that will filter out no dedicated gateway nodes.
**2. problem met:**
    1. when there are some traffic spike, some data nodes will long GC and without response.
    2. then one node will lead the others get requests hold in memory and then long GC too.
    3. then the whole cluster will unavaiable and hard to recovery
    4 let's call this cluster avalanche effects
**3. one possible way to make the pain less(may call this safe mode):**
    1. if avalanche effects happens or will happen based on some monitor data, then let the gateway node reject clients' read/write requests
    2. we may call this the safe mode of cluster, which will protect cluster and make it recovery more quickly

**Comment by bleskes** [comment] 2017-01-23 10:00
Thx @makeyang - I fully agreed that it will be great if we can detect the issues that may cause avalanches as you call them. These are issues that are not inherit to the node but rather to the data and query on the node and thus retrying on other nodes will only cause them to have trouble too. 

The problem is that these are *extremely* hard to identify. We are chasing them one by one and adding protections. Our strategy is not to detect them once they happened (i.e., one node is having trouble) but rather prevent them in advance. You can see examples on https://github.com/elastic/elasticsearch/issues/11511 . 

I'm closing this as I think it's too generic and is better replaced by the concrete list in #11511. Of course, if you run into something we can added to the list, please let us know.

**Closed by bleskes** 2017-01-23 10:00 UTC

**Comment by makeyang** [comment] 2017-01-23 10:12
@bleskes  sorry for misunderstanding.
actually what I expect here is to add the ability to reject clients' read/write requests with dynamic APIs or dynamic settings

**Comment by bleskes** [comment] 2017-01-23 10:18
I see. This is currently possible using an index settings (on an index by index basis). See https://www.elastic.co/guide/en/elasticsearch/reference/5.1/index-modules.html#index-modules-settings . Does this cover you needs?

**Comment by makeyang** [comment] 2017-01-23 10:41
this is good. I'll adopt it into my practices. thanks.
