### ISSUE TITLE
Correct analyzer is not always applied when using /_analyze api

### ISSUE THREAD

**Issue by mariane-sm** [elastic/elasticsearch#36934] opened 2018-12-21 13:03 UTC
Running multiple times this query brings me different results (sometimes applying standard, sometimes legacy_analyzer_indexing).

I am using ElasticSearch5.3
```
GET my_index/_analyze 
{
  "field": "x.name.en", 
  "text":  "<a>"
}
```
Mapping (relevant part):
```
        "x": {
          "type": "object",
          "properties": {
            "name": {
              "type": "object",
              "properties": {
                "default": {"type": "string", "analyzer": "standard"},
                "en": {"type": "string", "analyzer": "legacy_analyzer_indexing"},
              }
            }
          }
        },
```

**Comment by cbuescher** [comment] 2019-03-21 23:11
@mariane-sm sorry for the long wait, I was just trying to reproduce this behaviour on 5.3 and 5.7 and couldn't see different results for multiple queries.
Since I don't know what "legacy_analyzer_indexing" does I used the "standard" analyzer for "default" and the "english" analyzer for "en". The responses from the "_analyze" endpoints where always as expected, even in multi-node scenarios and with several hundred runs in test.

Here are a couple of questions that might enable us to see if this is (still) an issue:

Can you still reproduce the issue? 
Which exact version of 5.3 are you running? 
What is the expected analyze output for the case you mentioned ("text":  "<a>")?
Can you either provide some insight into what "legacy_analyzer_indexing" does or try it with another standard analyzer?
Whats your cluster setup (e.g. how many nodes)? 
Does this behaviour reproduce for you still in 5.7/6.x?

**Comment by cbuescher** [comment] 2019-04-09 07:42
@mariane-sm I'm closing this issue for now because without further feedback it is hard to progress on this. Please re-open and add more information if you are still encountering the problem.

**Closed by cbuescher** 2019-04-09 07:42 UTC
Labels: :Search/Analysis, >bug, feedback_needed, v5.3.3
