### ISSUE TITLE
geo_point with lat_lon true does not actually store lat and lon sub-fields

### ISSUE THREAD

**Issue by robin13** [elastic/elasticsearch#19740] opened 2016-08-02 10:56 UTC
**Elasticsearch version**: 2.3.3

**JVM version**:1.8.0_101

**OS version**: Ubuntu 14.0.4

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Adding documents with two different location formats:

```
PUT /foo
{
  "mappings": {
    "bar": {
      "properties": {
        "location": {
          "type": "geo_point",
          "lat_lon":true
        }
      }
    }
  }
}

PUT /foo/bar/1
{
  "location": "42,72"
}

PUT /foo/bar/2
{
  "location": {
    "lat": 41,
    "lon": 71
    }
}
```

And searching wanting to output the sub-fields `lat` and `lon` which should be created as a result of setting `"lat_lon": true` in the mapping:

```
GET /foo/bar/_search
{
  "fields": [ "location.lat", "location.lon" ]
}
```

returns

```
    "hits": [
      {
        "_index": "foo",
        "_type": "bar",
        "_id": "2",
        "_score": 1,
        "fields": {
          "location.lat": [
            41
          ],
          "location.lon": [
            71
          ]
        }
      },
      {
        "_index": "foo",
        "_type": "bar",
        "_id": "1",
        "_score": 1,
        "fields": {
          "location.lat": [
            "42,72"
          ],
          "location.lon": [
            "42,72"
          ]
        }
      }
```

Where we see that in document *2* the fields are correct, but in document *1* both lat and lon fields are the full original string.

Have I misunderstood [the documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/lat-lon.html) or is this a bug?

> Setting lat_lon to true causes the latitude and longitude values to be indexed as numeric fields (called .lat and .lon).

**Comment by clintongormley** [comment] 2016-08-11 11:40
Duplicate of https://github.com/elastic/elasticsearch/issues/13571 - use `fielddata_fields` instead of `fields`.  Also, `lat_lon` is deprecated https://github.com/elastic/elasticsearch/pull/17018

**Closed by clintongormley** 2016-08-11 11:40 UTC
