### ISSUE TITLE
the high order template can not overwrite the lower order template

### ISSUE THREAD

**Issue by nshfany** [elastic/elasticsearch#73754] opened 2021-06-04 09:24 UTC
hello! 
**Elasticsearch version** :  elasticsearch 6.8.15

**Steps to reproduce**:

 1. defined two template 
 `PUT _template/test_1
{
  "order":1,
  "index_patterns" : [
      "test_*"
  ],
  "mappings":{
    "_doc":{
      "properties":{
        "name":{
          "ignore_above" : 10922,
            "type" : "keyword"
        }
      }
    }
  }
}`
`PUT _template/test
{
  "order":0,
  "index_patterns" : [
      "test*"
  ],
  "mappings":{
    "_doc":{
      "properties":{
        "name":{
          "ignore_above" : 10922,
            "type" : "keyword",
            "index":false
        }
      }
    }
  }
}`
 2. write two index `test` and `test_1` 
 `PUT test/_doc/1
{
  "name":"Tom"
}`
`PUT test_1/_doc/1
{
  "name":"Tom"
}`
 3. get the two index `test` and `test_1` 
`GET test/_mapping`
`GET test_1/_mapping`
4. the mapping of  index `test_1` is match the template `test`

the elasticsearch server has not any the error message!

**Comment by dakrone** [comment] 2021-06-04 17:45
@nshfany legacy index templates (the ones used here) are merged, which is why `test_1` matches both templates. This is one of the downsides of legacy templates and has been addressed by composable index templates (#53101) released in 7.9+

Since this behavior is not a bug, I'm going to close this issue.

**Closed by dakrone** 2021-06-04 17:45 UTC
Labels: >bug, needs:triage

**Comment by nshfany** [comment] 2021-06-05 00:33
> @nshfany legacy index templates (the ones used here) are merged, which is why `test_1` matches both templates. This is one of the downsides of legacy templates and has been addressed by composable index templates (#53101) released in 7.9+
> 
> Since this behavior is not a bug, I'm going to close this issue.

Oh~ thanks! This is a fantastic idea! The problem has been solved satisfactorily by the function of V2 template
