### ISSUE TITLE
Aggregations: combining children, nested and range filter - filter not working properly

### ISSUE THREAD

**Issue by crutch** [elastic/elasticsearch#11376] opened 2015-05-27 14:28 UTC
Hello,

I am experiencing strange behavior when using aggregations combining `children`, `nested`, and `filter` aggs (with a `range` filter).

It looks like `children` aggregation is somehow affecting the `range` filter - it either returns count of all nested docs of a child document or none.

<pre>
curl -XPUT 'localhost:9200/nestingtest' -d '{
  "mappings": {
    "teams": {
      properties: {
        name: {
          type: "string",
          index: "not_analyzed",
          doc_values: true
        }
      }
    },
    "tasks": {
        _parent: { type: "teams" },
      properties: {
        task_id: {
          type: "long",
          doc_values: true
        },
        started_at: {
          type: "object",
          properties: {
            raw: {
              type: "date",
              doc_values: true
            },
            year: {
              type: "short",
              doc_values: true
            },
            month: {
              type: "short",
              doc_values: true
            },
            day: {
              type: "short",
              doc_values: true
            },
            hour: {
              type: "short",
              doc_values: true
            },
            minute: {
              type: "short",
              doc_values: true
            },
            wday: {
              type: "short",
              doc_values: true
            }
          }
        },
        events: {
          type: "nested",
          properties: {
            id: {
              type: "long",
              doc_values: true
            },
            happened_at: {
              type: "object",
              properties: {
                raw: {
                  type: "date",
                  doc_values: true
                },
                year: {
                  type: "short",
                  doc_values: true
                },
                month: {
                  type: "short",
                  doc_values: true
                },
                day: {
                  type: "short",
                  doc_values: true
                },
                hour: {
                  type: "short",
                  doc_values: true
                },
                minute: {
                  type: "short",
                  doc_values: true
                },
                wday: {
                  type: "short",
                  doc_values: true
                }
              }
            }
          }
        }
      }
    }
  }
}'
</pre>

Data:

<pre>
curl -XPOST 'localhost:9200/nestingtest/teams/1' -d '{ name: "team-A"}'

curl -XPOST 'localhost:9200/nestingtest/tasks/1?parent=1' -d '
    {
      _parent: 1,
      task_id: 1,
      started_at: {
        raw: "2015-05-27T13:05",
        year: 2015,
        month: 5,
        day: 27,
        hour: 13,
        minute: 5,
        dow: 3
      },
      events: [
        {
          id: 1,
          happened_at: {
            raw: "2015-05-27T13:10",
            year: 2015,
            month: 5,
            day: 27,
            hour: 13,
            minute: 10,
            dow: 3
          }
        }
      ]
    }
'

curl -XPOST 'localhost:9200/nestingtest/tasks/2?parent=1' -d '
    {
      _parent: 1,
      task_id: 2,
      started_at: {
        raw: "2015-05-27T16:05",
        year: 2015,
        month: 5,
        day: 27,
        hour: 16,
        minute: 5,
        dow: 3
      },
      events: [
        {
          id: 21,
          happened_at: {
            raw: "2015-05-27T16:10",
            year: 2015,
            month: 5,
            day: 27,
            hour: 16,
            minute: 10,
            dow: 3
          }
        },
        {
          id: 22,
          happened_at: {
            raw: "2015-05-27T17:10",
            year: 2015,
            month: 5,
            day: 27,
            hour: 17,
            minute: 10,
            dow: 3
          }
        }
      ]
    }
'   
</pre>

Queries:
This one, querying for parent documents is the one which behaves strangely
<pre>
curl -XPOST 'localhost:9200/nestingtest/teams/_search?pretty' -d '
    {
      aggs: {
        "to-tasks": {
          children: {
            type: "tasks"
          },
          aggs: {
            "to-events": {
              nested: {
                path: "tasks.events"
              },
              aggs: {
                filtered: {
                  filter: {
                    range: {
                      "events.happened_at.hour": {
                        gt: 15
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }

'
</pre>
   
It returns: 
<pre>
 "aggregations" : {
    "to-tasks" : {
      "doc_count" : 2,
      "to-events" : {
        "doc_count" : 3,
        "filtered" : {
          "doc_count" : 3
        }
      }
    }
</pre>

Where I would expect `filtered > doc_count` set to `2`.

If I change `events.happened_at.hour` to `tasks.events.happened_at.hour` it returns an empty bucket.

Just for comparison, this one queries the same data, but directly into children type (i.e., not using `children` aggregation) and is working as expected (returning 2 docs in the bucket). However, I would prefer to query for parent type, as I want to combine other criteria into query.

<pre>
curl -XPOST 'localhost:9200/nestingtest/tasks/_search?pretty' -d '
     {
      aggs: {
        "to-events": {
          nested: {
            path: "events"
          },
          aggs: {
            filtered: {
              filter: {
                range: {
                  "events.happened_at.hour": {
                    gt: 15
                  }
                }
              }
            }
          }
        }
      }
    }
'
</pre>

======================
<pre>
"version" : {
    "number" : "1.5.0",
    "build_hash" : "544816042d40151d3ce4ba4f95399d7860dc2e92",
    "build_timestamp" : "2015-03-23T14:30:58Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  }
</pre>

**Comment by martijnvg** [comment] 2015-05-27 15:58
@crutch I suspect that you're experiencing a bug that has been fixed via PR #10263.

Several bugs in the `children` agg have been fixed since 1.5.0, can you try to run with the latest 1.5 release?

**Comment by crutch** [comment] 2015-05-27 16:37
@martijnvg I am sorry to say, but I was able to reproduce the same weird behavior under 1.5.2.

**Comment by vhyza** [comment] 2015-05-28 11:18
I am experiencing similar behaviour on elasticsearch 1.5.2 with `children -> nested -> filter` aggregation with combination of `term filter` on `numeric` field.


Aggregation looks like this:
```json
{
  "aggs" : {
    "variants" : {
      "children" : {
        "type" : "variant"
      },
      "aggs" : {
        "parameters" : {
          "nested" : {
            "path" : "variant.parameters"
          },
          "aggs" : {
            "specifications" : {
              "filters" : {
                "filters" : {
                  "flavour" : {
                    "term" : {
                      "parameters.parameter_id": 1000
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "size" : 0
}
```

response

```json
{
   "took": 6,
   "timed_out": false,
   "_shards": {
      "total": 1,
      "successful": 1,
      "failed": 0
   },
   "hits": {
      "total": 2682,
      "max_score": 0,
      "hits": []
   },
   "aggregations": {
      "variants": {
         "doc_count": 2682,
         "parameters": {
            "doc_count": 62924,
            "specifications": {
               "buckets": {
                  "flavour": {
                     "doc_count": 0
                  }
               }
            }
         }
      }
   }
}
````

When I reindexed `parameter_id` as string, everything works as expected (with the same query as above).

```json
{
   "took": 5,
   "timed_out": false,
   "_shards": {
      "total": 1,
      "successful": 1,
      "failed": 0
   },
   "hits": {
      "total": 2682,
      "max_score": 0,
      "hits": []
   },
   "aggregations": {
      "variants": {
         "doc_count": 2682,
         "parameters": {
            "doc_count": 62924,
            "specifications": {
               "buckets": {
                  "flavour": {
                     "doc_count": 2438
                  }
               }
            }
         }
      }
   }
}
````

When I changed term filter to match query filter
```json
{
  "aggs" : {
    "variants" : {
      "children" : {
        "type" : "variant"
      },
      "aggs" : {
        "parameters" : {
          "nested" : {
            "path" : "variant.parameters"
          },
          "aggs" : {
            "specifications" : {
              "filters" : {
                "filters" : {
                  "flavour" : {
                    "query" : {
                      "match" : {
                      "parameters.parameter_id": 1000
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "size" : 0
}
````

It works

```json
{
   "took": 11,
   "timed_out": false,
   "_shards": {
      "total": 1,
      "successful": 1,
      "failed": 0
   },
   "hits": {
      "total": 2682,
      "max_score": 0,
      "hits": []
   },
   "aggregations": {
      "variants": {
         "doc_count": 2682,
         "parameters": {
            "doc_count": 62924,
            "specifications": {
               "buckets": {
                  "flavour": {
                     "doc_count": 2438
                  }
               }
            }
         }
      }
   }
}
````


With master (95faa35853bff06d14c9071120988c0cba9aae84) build It seems nested aggregation is not working.

Query
```json
{
  "aggs" : {
    "variants" : {
      "children" : {
        "type" : "variant"
      },
      "aggs" : {
        "parameters" : {
          "nested" : {
            "path" : "variant.parameters"
          },
          "aggs" : {
            "specifications" : {
              "filters" : {
                "filters" : {
                  "flavour" : {
                    "query" : {
                      "match" : {
                      "parameters.parameter_id": 1000
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "size" : 0
}
````

returns

```json
{
   "took": 2,
   "timed_out": false,
   "_shards": {
      "total": 1,
      "successful": 1,
      "failed": 0
   },
   "hits": {
      "total": 2682,
      "max_score": 0,
      "hits": []
   },
   "aggregations": {
      "variants": {
         "doc_count": 2682,
         "parameters": {
            "doc_count": 0 // here should be 62924
         }
      }
   }
}
````

Note that doc_count of parameters aggregations returns 0 instead of 62924 as elasticsearch 1.5.2 did.

When I remove `children` aggregation everything works as expected on both 1.5.2 and master (95faa35853bff06d14c9071120988c0cba9aae84) (with both `long` and `string` type)

```json
{
  "aggs": {
    "parameters": {
      "nested": {
        "path": "parameters"
      },
      "aggs": {
        "specifications": {
          "filters": {
            "filters": {
              "flavour": {
                "query": {
                  "match": {
                    "parameters.parameter_id": 1000
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "size": 0
}
````

returns

```json
{
   "took": 7,
   "timed_out": false,
   "_shards": {
      "total": 1,
      "successful": 1,
      "failed": 0
   },
   "hits": {
      "total": 2682,
      "max_score": 0,
      "hits": []
   },
   "aggregations": {
      "parameters": {
         "doc_count": 62924,
         "specifications": {
            "buckets": {
               "flavour": {
                  "doc_count": 2438
               }
            }
         }
      }
   }
}
````

**Comment by martijnvg** [comment] 2015-06-22 13:17
@crutch The issue in the first search request that you have shared is that the type defined in the url is letting the wrapped `nested` aggregator work incorrectly. If you omit the type from the url then the response is as expected:

```bash
curl -XPOST "http://localhost:9200/nestingtest/_search?pretty" -d'
{
  "size" : 0,
  "aggs": {
    "to-tasks": {
      "children": {
        "type": "tasks"
      },
      "aggs": {
        "to-events": {
          "nested": {
            "path": "events"
          },
          "aggs": {
            "filtered": {
              "filter": {
                "range": {
                  "events.happened_at.hour": {
                    "gt": 15
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}'
```

@vhyza Does removing the type from the url help in your case too?

**Comment by vhyza** [comment] 2015-06-22 14:08
@martijnvg Thanks! Yes, when I removed type from url, I got same result as with `match` query filter.

**Comment by martijnvg** [comment] 2015-06-22 18:46
The `nested` aggregator doesn't work, because the mapping can't be resolved. This is because the search is scoped to the `teams` type and the `tasks.events` object field doesn't exist in that type. This behaviour kind of is understandable, but hard to figure out, because the `nested` aggregator is ignored and just results an empty result.

I've been thinking about this and the best way is just make this kinds of requests fail, so it is clear that the type needs to be removed from the request url. I think we can get this behaviour in when #11806 gets in. The plan is there to by default let `nested` aggregation fail if no nested field can be resolved.

**Comment by vhyza** [comment] 2015-06-23 11:06
@martijnvg so, it is not a bug? I don't fully understand why (in my case) `match` query filter works and `term` filter does not (or why `parameter_id` indexed as `string` works even with `term` filter)

**Comment by martijnvg** [comment] 2015-06-23 12:43
@vhyza No, it is a bug. The bug here is that ES should fail the search request and tell that it couldn't resolve a nested field (or another field), instead of ignoring that and returning no results.

I'm not sure too, because I don't have the mapping and data you used, but this can be explained too by the fact that the mapping can't be resolved because the parent type is used in the url. In the case for term filter it assumes that the field is a string. This causes zero matches because the field is indexed as a number. Strings and numbers are stored differently and filters/queries need to be analysed different in ES to actual be able to match properly.

**Comment by crutch** [comment] 2015-06-23 16:13
@martijvng thank you for the quick solution for this.

However, I do not really understand why ES should fail on a completely
valid and correct query. From my point of view, I prefer to scope my query
to a particular type, just to be sure that I only get results of that type.
And I always thought that this type scope is related only to top-level
document. If I decide to jump to another document type via `has_child ` and
then use a `nested` filter inside, I do not expect that type scope declared
in the url to be that sticky and to force ES to declare that it was unable
to resolve a field here.  I would expect ES to know that the scope has
changed for this part of a query.

I understand that this might be difficult to achieve with current
implementation and I am OK with your workaround (thank you again for it).
But when I as a human can read a query and its interpretation is
unambiguous, then it should be clear for ES as well.

**Comment by martijnvg** [comment] 2015-06-23 16:24
@crutch I see your point and maybe ES shouldn't scope the internal field lookup in the mapping to the type defined in the url. I think the reason this exist, is that today one can define fields in different types in the same index that have the same name, but have different settings and field types. By scoping by type one has control of what actual field is used instead of let ES guess.

Actually this mapping characteristic is going to change and #11812 is going to prohibit having fields with same name but with different settings / field types. If that gets in then the type scoping that happens in the _search api during parsing can be removed and the search request that you initially shared should then work.

**Comment by martijnvg** [comment] 2015-06-26 14:44
@crutch @vhyza The underlying issue (field lookup taking the type in the url into account) has been fixed in master. This got fixed when #11812 got merged in. So your search request will also work with the type specified. 

This issue will not be fixed in 1.x, so for all current released ES versions this workaround needs to be used. When the first 2.0 release gets out the work around will not longer be needed.

**Comment by clintongormley** [comment] 2015-06-26 15:08
thanks @martijnvg - closing

**Closed by clintongormley** 2015-06-26 15:08 UTC
Labels: :Aggregations, :Parent/Child, bug

**Comment by vhyza** [comment] 2015-06-27 08:52
thanks @martijnvg!

**Comment by crutch** [comment] 2015-06-29 07:50
thanks @martijnvg, looking forward to 2.0
