### ISSUE TITLE
Simple combined_fields query fails with java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by nemphys** [elastic/elasticsearch#74037] opened 2021-06-11 13:21 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 7.13.1

**Plugins installed**: [analysis-icu]

**JVM version** (`java -version`): built-in

**OS version** (`uname -a` if on a Unix-like system): macOS Big Sur

Having replaced the use of multi_match cross_fields queries with the new combined_fields query, I am now running into a dead-end.

The query is very simple: 

```
GET /index-name/_search
{
  "query": {
    "combined_fields": {
      "query": "μαύρο",
      "operator": "AND",
      "fields": [
        "title",
        "description"
      ]
    }
  }
}
```

and fails with the following stacktrace:

`org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:661) [elasticsearch-7.13.1.jar:7.13.1]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:384) [elasticsearch-7.13.1.jar:7.13.1]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:694) [elasticsearch-7.13.1.jar:7.13.1]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:467) [elasticsearch-7.13.1.jar:7.13.1]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.access$000(AbstractSearchAsyncAction.java:62) [elasticsearch-7.13.1.jar:7.13.1]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:316) [elasticsearch-7.13.1.jar:7.13.1]
	at org.elasticsearch.action.ActionListener$Delegating.onFailure(ActionListener.java:66) [elasticsearch-7.13.1.jar:7.13.1]
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:48) [elasticsearch-7.13.1.jar:7.13.1]
	at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:400) [elasticsearch-7.13.1.jar:7.13.1]
	at org.elasticsearch.transport.TransportService$5.handleException(TransportService.java:738) [elasticsearch-7.13.1.jar:7.13.1]
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1283) [elasticsearch-7.13.1.jar:7.13.1]
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1392) [elasticsearch-7.13.1.jar:7.13.1]
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1366) [elasticsearch-7.13.1.jar:7.13.1]
	at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:50) [elasticsearch-7.13.1.jar:7.13.1]
	at org.elasticsearch.transport.TransportChannel.sendErrorResponse(TransportChannel.java:45) [elasticsearch-7.13.1.jar:7.13.1]
	at org.elasticsearch.action.support.ChannelActionListener.onFailure(ChannelActionListener.java:40) [elasticsearch-7.13.1.jar:7.13.1]
	at org.elasticsearch.action.ActionRunnable.onFailure(ActionRunnable.java:77) [elasticsearch-7.13.1.jar:7.13.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:28) [elasticsearch-7.13.1.jar:7.13.1]
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33) [elasticsearch-7.13.1.jar:7.13.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:732) [elasticsearch-7.13.1.jar:7.13.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.13.1.jar:7.13.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: org.elasticsearch.ElasticsearchException$1
	at org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:633) ~[elasticsearch-7.13.1.jar:7.13.1]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:382) [elasticsearch-7.13.1.jar:7.13.1]
	... 22 more
Caused by: java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:742) ~[?:?]
	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:297) ~[?:?]
	at org.apache.lucene.store.ByteBufferGuard.getByte(ByteBufferGuard.java:119) ~[lucene-core-8.8.2.jar:8.8.2 a92a05e195b775b30ca410bc0a26e8e79e7b3bfb - mdrob - 2021-04-06 16:33:27]
	at org.apache.lucene.store.ByteBufferIndexInput$SingleBufferImpl.readByte(ByteBufferIndexInput.java:434) ~[lucene-core-8.8.2.jar:8.8.2 a92a05e195b775b30ca410bc0a26e8e79e7b3bfb - mdrob - 2021-04-06 16:33:27]
	at org.apache.lucene.codecs.lucene80.Lucene80NormsProducer$8.longValue(Lucene80NormsProducer.java:397) ~[lucene-core-8.8.2.jar:8.8.2 a92a05e195b775b30ca410bc0a26e8e79e7b3bfb - mdrob - 2021-04-06 16:33:27]
	at org.apache.lucene.search.XMultiNormsLeafSimScorer$MultiFieldNormValues.advanceExact(XMultiNormsLeafSimScorer.java:135) ~[elasticsearch-7.13.1.jar:8.8.2 a92a05e195b775b30ca410bc0a26e8e79e7b3bfb - mdrob - 2021-04-06 16:33:27]
	at org.apache.lucene.search.XMultiNormsLeafSimScorer.getNormValue(XMultiNormsLeafSimScorer.java:91) ~[elasticsearch-7.13.1.jar:8.8.2 a92a05e195b775b30ca410bc0a26e8e79e7b3bfb - mdrob - 2021-04-06 16:33:27]
	at org.apache.lucene.search.XMultiNormsLeafSimScorer.score(XMultiNormsLeafSimScorer.java:103) ~[elasticsearch-7.13.1.jar:8.8.2 a92a05e195b775b30ca410bc0a26e8e79e7b3bfb - mdrob - 2021-04-06 16:33:27]
	at org.apache.lucene.search.XCombinedFieldQuery$CombinedFieldScorer.score(XCombinedFieldQuery.java:453) ~[elasticsearch-7.13.1.jar:8.8.2 a92a05e195b775b30ca410bc0a26e8e79e7b3bfb - mdrob - 2021-04-06 16:33:27]
	at org.apache.lucene.search.TopScoreDocCollector$SimpleTopScoreDocCollector$1.collect(TopScoreDocCollector.java:76) ~[lucene-core-8.8.2.jar:8.8.2 a92a05e195b775b30ca410bc0a26e8e79e7b3bfb - mdrob - 2021-04-06 16:33:27]
	at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreRange(Weight.java:252) ~[lucene-core-8.8.2.jar:8.8.2 a92a05e195b775b30ca410bc0a26e8e79e7b3bfb - mdrob - 2021-04-06 16:33:27]
	at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:239) ~[lucene-core-8.8.2.jar:8.8.2 a92a05e195b775b30ca410bc0a26e8e79e7b3bfb - mdrob - 2021-04-06 16:33:27]
	at org.elasticsearch.search.internal.CancellableBulkScorer.score(CancellableBulkScorer.java:45) ~[elasticsearch-7.13.1.jar:7.13.1]
	at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:39) ~[lucene-core-8.8.2.jar:8.8.2 a92a05e195b775b30ca410bc0a26e8e79e7b3bfb - mdrob - 2021-04-06 16:33:27]
	at org.elasticsearch.search.internal.ContextIndexSearcher.searchLeaf(ContextIndexSearcher.java:187) ~[elasticsearch-7.13.1.jar:7.13.1]
	at org.elasticsearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:160) ~[elasticsearch-7.13.1.jar:7.13.1]
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:445) ~[lucene-core-8.8.2.jar:8.8.2 a92a05e195b775b30ca410bc0a26e8e79e7b3bfb - mdrob - 2021-04-06 16:33:27]
	at org.elasticsearch.search.query.QueryPhase.searchWithCollector(QueryPhase.java:332) ~[elasticsearch-7.13.1.jar:7.13.1]
	at org.elasticsearch.search.query.QueryPhase.executeInternal(QueryPhase.java:287) ~[elasticsearch-7.13.1.jar:7.13.1]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:139) ~[elasticsearch-7.13.1.jar:7.13.1]
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:368) ~[elasticsearch-7.13.1.jar:7.13.1]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:422) ~[elasticsearch-7.13.1.jar:7.13.1]
	at org.elasticsearch.search.SearchService.lambda$executeQueryPhase$2(SearchService.java:394) ~[elasticsearch-7.13.1.jar:7.13.1]
	at org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:47) ~[elasticsearch-7.13.1.jar:7.13.1]
	at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62) ~[elasticsearch-7.13.1.jar:7.13.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-7.13.1.jar:7.13.1]
	... 6 more`

It is really weird and I cannot seem to spot the cause, since:
1) If I use other (random) queries, the query either succeeds or fails with the same exception
2) If I omit the "title" field, the query succeeds,
3) If I omit the "description" field, the query succeeds

Please note that this is definitely a combined_fields issue, since changing the query type to multi_match cross_fields makes it work properly.

This seems to be a Lucene issue, but I have no further idea.

@jtibshirani I suppose you might be interested in this one

**Comment by nemphys** [comment] 2021-06-11 13:48
Just found issue  #27131, which seems to be related.

**Comment by jtibshirani** [comment] 2021-06-11 23:19
@nemphys sorry you are running into issues with the new query, I hope we can get to the bottom of it quickly. To help debug, would you be able to supply your index mapping, as well as an example document? (I assume you aren't able to provide a full reproduction?)

**Comment by jtibshirani** [comment] 2021-06-12 03:06
I have a theory as to the issue: if some documents are missing values for one of the fields, then the query can fail when trying to compute norms. It's indeed a problem in Lucene, I filed an issue here: https://issues.apache.org/jira/browse/LUCENE-9999. Does this apply to your set-up -- are there documents missing either `title` or `description`? 

This is a really unfortunate bug, because part of why we encouraged users to try out `combined_fields` is to avoid a bug in `cross_fields` around this same set-up (where some documents are missing fields). I'll make sure this is resolved in an upcoming 7.13 patch release.

**Comment by nemphys** [comment] 2021-06-12 08:13
I think that missing values are indeed the issue: I checked, and out of ~47000 total documents there are ~19000 documents missing a description. I tried reindexing while forcing the value of the description field of the documents that lack it to an empty string and, behold, the problem went away (and came back when I reverted the change, so we definitely found the culprit).

This is why the presence of the description field in the query fields array causes exceptions (the complete query includes other fields, too, but I omitted them trying to find the cause of the issue; if I run the query with all other fields except for the description field, there are no exceptions). Also, it explains why some query strings fail, while others succeed (I suppose the ones that succeed happen to *not* match any of the documents missing a description).

Is this something you can deal with on the Elasticsearch side, or does it have to be fixed by Lucene?

**Comment by jtibshirani** [comment] 2021-06-12 16:01
> Is this something you can deal with on the Elasticsearch side, or does it have to be fixed by Lucene?

Ultimately it should be fixed in Lucene. But we have ways of applying small Lucene fixes in Elasticsearch without waiting for a new Lucene release, so we won't be tied to that schedule.

**Comment by nemphys** [comment] 2021-06-28 12:54
Ping

**Comment by jimczi** [comment] 2021-06-30 13:45
The issue is fixed by https://github.com/elastic/elasticsearch/pull/74678. The fix is not merged in Lucene yet but we've decided to release with an early fix in the next patch version of Elasticsearch. We'll merge the long term fix in [Lucene](https://github.com/apache/lucene/pull/185) and remove our fork in a later release. 
Closing this issue now as the bug is fixed. Thanks for reporting @nemphys !

**Closed by jimczi** 2021-06-30 13:45 UTC
Labels: :Search/Search, >bug, Team:Search

**Comment by nemphys** [comment] 2021-07-10 18:04
Nice to have this fixed (exceptions are indeed not thrown anymore if there are documents missing field values), but I am now facing a new issue, which is quite weird and hard to explain; since it might be related to this issue, I am not opening a new issue until we make sure that it is something new:

The documents in my index have a few fields (around 10), each indexed with 1 or more analyers based on some field template logic. The top level query is a bool (should) query, which contains many combined_fields subqueries (one for each analyzer, with the respective fields grouped by analyzer). 

Since all seemed to work fine (queries returned results as they should), I was under the impression that the new setup was good to go. 

Today I tried to perform a simple query for a specific field value prefix, which should match a few documents in the index. After receiving 0 results, I started manually adding/removing parts of the request in order to determine what the problem could be (needless to say that running the exact same query in multi_match/cross_fields mode yielded the expected results). My findings are as follows:

The initial query (that produces 0 results) is a boolean should query with 6 combined_fields children, out of which only 1 should match the documents (it searches against 2 fields using a n-gram analyzer, one of which contains the requested prefix), hereafter referred to as the "matching" query.

- If I remove all other combined_fields queries and leave just the "matching" one, the expected matches are returned.
- If I remove the 2nd field from the "matching" query (not the field containing the requested prefix) and leave everything else as is, the expected matches are returned; please note that the removed field contains some empty values (but I already tried setting an empty string value to them while debugging, with the same result).
- If I remove 2 other (yet specific) combined fields queries from the main query, the expected matches are returned; out of the 2 queries in question, 1 contains the same fields as the "matching" query (but uses a different anazyler) and the other contains some other fields (seemingly irrelevant to the query). Both should not return any matches. The weird thing is that only removing them *both* fixes the problem (removing just one of them still yields no results).

Since I am quite lost, I would appreciate some guidance regarding what to test next...

@jtibshirani to the rescue!

**Comment by jtibshirani** [comment] 2021-07-12 01:48
@nemphys great you could confirm the original issue is solved!

I am having trouble understanding what could be wrong based just on your description. Nothing jumps out to me in terms of a possible bug. I also suspect it isn't related to this issue, which wouldn't cause missing hits. Would you be able to file a new issue with a reproduction, or instead (understanding that may be a lot of work), include examples of the before + after queries?

**Comment by nemphys** [comment] 2021-07-12 07:10
@jtibshirani OK, i will open a new issue. Concerning the reproduction, I suppose that would be close to impossible :-) I will definitely include actual queries, though.

I will also try to do some actual debugging today (add some breakpoints to the ES code in IntelliJ and monitor behavior in requests that product/do not product results), just in case I spot something easily. Any insights regarding the relevant classes / methods would save me a lot of time.
