### ISSUE TITLE
Elasticsearch not starting if I add path.repo in elasticsearch.yml 

### ISSUE THREAD

**Issue by soaguru** [elastic/elasticsearch#25655] opened 2017-07-11 17:35 UTC
**Elasticsearch version**: 5.5.0
**Plugins installed**: X-pack for elasticsearch and kibana
**JVM version** (`java -version`):  1.8.0_131
**OS version** (`uname -a` if on a Unix-like system):  Linux localhost 3.8.13-118.18.4.el6uek.x86_64 #2 SMP Tue May 30 15:01:52 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux

When I add path.repo: ["/home/oracle/setup/test_repository"] line to elasticsearch.yml and restart elasticsearch, it is not starting up. If I comment this line out, it starts perfectly fine. 

/home/oracle/setup/test_repository  directory exists. 

Have tried  both   
sudo service elasticsearch restart  and 
/usr/share/elasticsearch/bin  sudo  ./elasticsearch

Error: 
Exception in thread "main" org.elasticsearch.bootstrap.BootstrapException: java.nio.file.NoSuchFileException: /usr/share/elasticsearch/config
Likely root cause: java.nio.file.NoSuchFileException: /usr/share/elasticsearch/config
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:225)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
	at java.nio.file.Files.walkFileTree(Files.java:2662)
	at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:150)
	at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:122)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:316)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.Command.main(Command.java:88)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84)
Refer to the log for complete error details.

**Steps to reproduce**:  Add path.repo: ["/home/oracle/setup/test_repository"] line to elasticsearch.yml and restart elasticsearch

**Comment by jasontedor** [comment] 2017-07-11 17:44
I'm not sure why you think this has something to do with `path.repo`, the error message is pretty clear as to the problem. You're trying to start Elasticsearch, it thinks it's config file should be in `/usr/share/elasticsearch/config` and there is nothing there. This often happens when users install Elasticsearch via a package distribution and try to start Elasticsearch from the command line (`/usr/share/elasticsearch/bin/elasticsearch`) instead of via the service. Rather, the package distributions are not meant to be started like this, rather their configuration is in `/etc/elasticsearch` and you should start them via the service.

We reserve GitHub for verified bug reports and feature requests, this looks like you just need help and not a bug. For that we would like to ask you to use the [forum](https://discuss.elastic.co). I hope you don't mind that I close this then. You can feel free to provide a link here to any topics that you open on the forum.

**Closed by jasontedor** 2017-07-11 17:44 UTC
