### ISSUE TITLE
`CommonAnalysisPluginTests.testSystemSynonymsIndexName` fails in `main`

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#95906] opened 2023-05-08 06:56 UTC
### CI Link

https://gradle-enterprise.elastic.co/s/dp6fcuc5av3ms

### Repro line

./gradlew ':modules:analysis-common:test' --tests "org.elasticsearch.analysis.common.CommonAnalysisPluginTests.testSystemSynonymsIndexName" \   -Dtests.seed=5368D738E696C3C5 \   -Dbuild.snapshot=false \   -Dtests.jvm.argline="-Dbuild.snapshot=false" \   -Dtests.locale=ar-QA \   -Dtests.timezone=America/Argentina/Catamarca \   -Druntime.java=20

### Does it reproduce?

Yes

### Applicable branches

main

### Failure excerpt

```
08:14:10 REPRODUCE WITH: ./gradlew ':modules:analysis-common:test' --tests "org.elasticsearch.analysis.common.CommonAnalysisPluginTests.testSystemSynonymsIndexName" -Dtests.seed=5368D738E696C3C5 -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dtests.locale=ar-QA -Dtests.timezone=America/Argentina/Catamarca -Druntime.java=20
08:14:10 
08:14:10 org.elasticsearch.analysis.common.CommonAnalysisPluginTests > testSystemSynonymsIndexName FAILED
08:14:10     java.lang.AssertionError: expected:<[.synonyms]> but was:<[]>
08:14:10         at __randomizedtesting.SeedInfo.seed([5368D738E696C3C5:51256678CA99F6DF]:0)
08:14:10         at org.junit.Assert.fail(Assert.java:88)
08:14:10         at org.junit.Assert.failNotEquals(Assert.java:834)
08:14:10         at org.junit.Assert.assertEquals(Assert.java:118)
08:14:10         at org.junit.Assert.assertEquals(Assert.java:144)
08:14:10         at org.elasticsearch.analysis.common.CommonAnalysisPluginTests.testSystemSynonymsIndexName(CommonAnalysisPluginTests.java:228)
08:14:10 
08:14:10 
```

**Comment by cbuescher** [comment] 2023-05-08 07:43
Closing as duplicate of https://github.com/elastic/elasticsearch/issues/95840

**Closed by cbuescher** 2023-05-08 07:43 UTC
Labels: :Search/Analysis, >test-failure, Team:Search
