### ISSUE TITLE
_migration/deprecations HTTP endpoint logs deprecation warning

### ISSUE THREAD

**Issue by kobelb** [elastic/elasticsearch#78098] opened 2021-09-21 13:20 UTC
**Elasticsearch version** (`bin/elasticsearch --version`):

`Version: 8.0.0-SNAPSHOT, Build: default/tar/4c23260290e19b306a809a8066a777f0a21bbd24/2021-09-15T14:07:01.982847214Z, JVM: 16.0.2`

**Plugins installed**: []

None

**JVM version** (`java -version`):

openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-24)
OpenJDK 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

**OS version** (`uname -a` if on a Unix-like system):

macOS 10.15.7

**Description of the problem including expected versus actual behavior**:

Kibana's upgrade assistant executes a `GET _migration/deprecations` HTTP request to Elasticsearch, which is causing a deprecation to be logged. Users should be able to use the Upgrade Assistant without a deprecation being logged.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. Start up a new instance of Elasticsearch
 2. `curl --verbose -u elastic:changeme -XGET http://localhost:9200/_migration/deprecations`
 3. Check the file deprecation log and see the following messages

**Provide logs (if relevant)**:

```
{"@timestamp":"2021-09-21T13:03:03.436Z", "log.level":"CRITICAL",  "data_stream.dataset":"deprecation.elasticsearch", "data_stream.namespace":"default", "data_stream.type":"logs", "ecs.version":"1.7", "elasticsearch.event.category":"api", "elasticsearch.http.request.x_opaque_id":"6b6fc2a3-c3ac-40b1-a87d-b59b287cdf80", "event.code":"open_system_index_access", "message":"this request accesses system indices: [.security-7], but in a future major version, direct access to system indices will be prevented by default" , "service.name":"ES_ECS","process.thread.name":"elasticsearch[kobelb.local][generic][T#11]","log.logger":"org.elasticsearch.deprecation.cluster.metadata.IndexNameExpressionResolver","event.dataset":"deprecation.elasticsearch","elasticsearch.cluster.uuid":"aWDCdlmeSaKIUhvF729pjA","elasticsearch.node.id":"cvvgD11PRNiOMtjNaayzoA","elasticsearch.node.name":"kobelb.local","elasticsearch.cluster.name":"elasticsearch"}
{"@timestamp":"2021-09-21T13:03:35.881Z", "log.level":"CRITICAL",  "data_stream.dataset":"deprecation.elasticsearch", "data_stream.namespace":"default", "data_stream.type":"logs", "ecs.version":"1.7", "elasticsearch.event.category":"api", "elasticsearch.http.request.x_opaque_id":"d37de351-4fa9-4d1a-a25a-bf67ba16e75d", "event.code":"open_system_index_access", "message":"this request accesses system indices: [.async-search, .security-7], but in a future major version, direct access to system indices will be prevented by default" , "service.name":"ES_ECS","process.thread.name":"elasticsearch[kobelb.local][generic][T#4]","log.logger":"org.elasticsearch.deprecation.cluster.metadata.IndexNameExpressionResolver","event.dataset":"deprecation.elasticsearch","elasticsearch.cluster.uuid":"aWDCdlmeSaKIUhvF729pjA","elasticsearch.node.id":"cvvgD11PRNiOMtjNaayzoA","elasticsearch.node.name":"kobelb.local","elasticsearch.cluster.name":"elasticsearch"}
```

**Comment by cjcenizal** [comment] 2021-09-21 16:58
@gwbrown Mentioned that https://github.com/elastic/elasticsearch/pull/67312 is related to this

**Comment by gwbrown** [comment] 2021-09-23 21:36
This should be fixed in 7.x with https://github.com/elastic/elasticsearch/pull/78151, though the behavior will be present in `master` until we finalize things. As such, I'm going to close this issue; please reopen it if the issue on `master` becomes problematic or the fix doesn't work as intended.

**Comment by rudolf** [comment] 2021-11-09 13:46
I can confirm that there's no deprecation warnings when only querying this API on the latest 7.16 snapshot `https://storage.googleapis.com/kibana-ci-es-snapshots-daily/7.16.0/archives/20211108-151357_c5ca20e2/elasticsearch-7.16.0-SNAPSHOT-darwin-x86_64.tar.gz`

When Kibana is started deprecation notices show up but these seem unrelated to this API.

**Closed by rudolf** 2021-11-09 13:46 UTC
Labels: :Core/Infra/Core, Team:Core/Infra

**Comment by cjcenizal** [comment] 2021-11-10 23:49
Thank you for investigating @rudolf!
