### ISSUE TITLE
5.0.0-rc Unable to remove plugins due to permissions

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch#21072] opened 2016-10-21 15:50 UTC
I'm not sure if this is related to (https://github.com/elastic/elasticsearch/issues/13444) but I'm running the rc on windows 10 (default user permissions) on java8. I installed the plugin and was asked for permissions which I granted, the same doesn't happen when I try to uninstall.

```

C:\elasticsearch.5.0\bin>elasticsearch-plugin install mapper-attachments
-> Downloading mapper-attachments from elastic
[=================================================] 100%  
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission getClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.security.SecurityPermission createAccessControlContext
* java.security.SecurityPermission insertProvider
* java.security.SecurityPermission putProviderProperty.BC
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

Continue with installation? [y/N]y
-> Installed mapper-attachments

C:\elasticsearch.5.0\bin>elasticsearch-plugin remove mapper-attachments
-> Removing mapper-attachments...
Exception in thread "main" java.nio.file.AccessDeniedException: C:\elasticsearch.5.0\plugins\mapper-attachments -> C:\elasticsearch.5.0\plugins\.removing-mapper-attachments
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
        at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
        at java.nio.file.Files.move(Files.java:1395)
        at org.elasticsearch.plugins.RemovePluginCommand.execute(RemovePluginCommand.java:87)
        at org.elasticsearch.plugins.RemovePluginCommand.execute(RemovePluginCommand.java:58)
        at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96)
        at org.elasticsearch.cli.Command.main(Command.java:62)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:42)

C:\elasticsearch.5.0\bin>
```

Yes, I get that this plugin was deprecated and that is why I tried to remove it.

**Comment by nik9000** [comment] 2016-10-21 16:14
These are two different types of permissions though. The permissions the plugin installer talks about are jvm security manager permissions. The AccessDeniedException is a filesystem level permissions thing.

**Comment by niemyjski** [comment] 2016-10-21 16:17
Same console instance should have the same file permissions applied no?

**Comment by jasontedor** [comment] 2016-10-21 17:04
This does not reproduce for me on macOS nor on a Windows 10 VM.

```
C:\Users\IEUser\elasticsearch\elasticsearch-5.0.0-rc1\bin>elasticsearch-plugin install mapper-attachments
Plugins directory [C:\Users\IEUser\elasticsearch\elasticsearch-5.0.0-rc1\plugins] does not exist. Creating...
-> Downloading mapper-attachments from elastic
[=================================================] 100%  
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission getClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.security.SecurityPermission createAccessControlContext
* java.security.SecurityPermission insertProvider
* java.security.SecurityPermission putProviderProperty.BC
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

Continue with installation? [y/N]y
-> Installed mapper-attachments

C:\Users\IEUser\elasticsearch\elasticsearch-5.0.0-rc1\bin>elasticsearch-plugin remove mapper-attachments
-> Removing mapper-attachments...

C:\Users\IEUser\elasticsearch\elasticsearch-5.0.0-rc1\bin>
```

The `.removing-mapper-attachments` directory is a temporary directory that we atomically move the existing `mapper-attachments` directory to before deleting. I do not see why the permissions would be modified unless there's something about your setup we are assuming to not be the case.

**Comment by niemyjski** [comment] 2016-10-24 15:15
I wasn't able to reproduce if it was something permission related.

```
C:\elasticsearch.5.0\bin>elasticsearch-plugin install mapper-attachments
-> Downloading mapper-attachments from elastic
[=================================================] 100%  
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission getClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.security.SecurityPermission createAccessControlContext
* java.security.SecurityPermission insertProvider
* java.security.SecurityPermission putProviderProperty.BC
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

Continue with installation? [y/N]y
-> Installed mapper-attachments

C:\elasticsearch.5.0\bin>elasticsearch-plugin remove mapper-attachments
-> Removing mapper-attachments...
```

The directory was also removed, I guess if you run into this again, we know there is some kind of bug. Please close this or leave it open, I just know that I hit some kind of crazy issue here.

**Comment by jasontedor** [comment] 2016-10-24 15:17
Unable to reproduce, closing.

**Closed by jasontedor** 2016-10-24 15:17 UTC
Labels: :Plugins
