### ISSUE TITLE
Feature request: add more information returned when using update api

### ISSUE THREAD

**Issue by bhaisaab** [elastic/elasticsearch#4680] opened 2014-01-10 08:35 UTC
The present update API has option to upsert document when it does not exist. The result is something like:
{"ok":true,"_index":"metadata","_type":"load","_id":"ind1","_version":1}

It does not tell us whether the document existed, or was upserted or fields were updated. If in the result we can have the following tunable via the update api:

- Difference between old and new values
- Whether document was upserted or updated
- List of fields that were updated, or that existed before

I'm not sure if this feature could be implemented as a plugin or by some other way.

**Comment by bleskes** [comment] 2015-03-27 11:32
I think this last suggestion on https://github.com/elastic/elasticsearch/issues/4420#issuecomment-86890958 , makes #4420 a complete duplicate of this one. I'm going to close this. If I missed something please re-open or comment on #4420 ?

PS. there is also the http response code (200 vs 201 ) to tell if an upsert happened.

**Closed by bleskes** 2015-03-27 11:32 UTC
Labels: discuss
