### ISSUE TITLE
SQL: Enhance IN behaviour with automatic casting

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#34748] opened 2018-10-23 13:49 UTC
Currently queries like 
`SELECT 1 in ('1', '2'), '1' in (1, 2), 1 in (1, '2');`
or
`SELECT a in ('1', '2'), a in (1, 2), a in (1, '2') FROM t`
throw an Exception for incompatible types where in PostgreSQL work.

If automatic casting for such cases is implemented it can save the user from manual casts or accidental typos (e.g.: missing or adding single quotes)

**Comment by costin** [comment] 2018-10-24 16:33
This would be quite handy when dealing with IP fields:
`WHERE ip IN ('192.168.1.1', ...)` fails because the value is `ip` while the list contains only strings.

**Comment by bpintea** [comment] 2021-05-26 11:20
This no longer seems to reproduce in master, 7.x. I'd close it, unless you have an objection, @matriv.

**Comment by bpintea** [comment] 2021-05-26 11:28
Yes, I did, that works too.

**Comment by matriv** [comment] 2021-05-26 11:48
Great, then yes, we can close this.

**Closed** 2021-05-26 12:03 UTC
Labels: :Query Languages/SQL, >enhancement, Team:QL
