### ISSUE TITLE
Elastic search more like this Query score issue in 5.x 

### ISSUE THREAD

**Issue by sanjaykanani** [elastic/elasticsearch#25670] opened 2017-07-12 12:19 UTC
Recently we have changed Elasticsearch version from 2.4 to 5.4 .

we found one issue in more like this query in version 5.x .

following query is used to find out similar documents by text

**INPUT Query**

> POST  /test/_search
> {
> "size": 10000,
> "stored_fields": [
> "docid"
> ],
> "_source": false,
> "query": {
> "more_like_this": {
> "fields": [
> "textcontent"
> ],
> "like": [
> {
> "_index": "test",
> "_type": "object",
> "_id": "AV0c9jvZXF-b5U5aNAWB"
> }
> ],
> "max_query_terms": 5000,
> "min_term_freq": 1,
> "min_doc_freq": 1
> }
> }
> }

**Output of Elasticsearch 2.4**

> {
> 
> "took": 16,
> "timed_out": false,
> "_shards": {
> "total": 1,
> "successful": 1,
> "failed": 0
> },
> "hits": {
> "total": 3,
> "max_score": 1.5381224,
> "hits": [
> {
> "_index": "test",
> "_type": "object",
> "_id": "AVzjOOdilllQ-Gyal6Z9",
> "_score": 1.5381224,
> "fields": {
> "docid": [
> "2"
> ]
> }
> }, {
> "_index": "test",
> "_type": "object",
> "_id": "AVzjOOdilllQ-Gyal63Z",
> "_score": .5381224,
> "fields": {
> "docid": [
> "3"
> ]
> }
> }, {
> "_index": "test",
> "_type": "object",
> "_id": "AVzjOOdilllQ-Gyal6Z",
> "_score": .381224,
> "fields": {
> "docid": [
> "4"
> ]
> }
> }

**Output of Elasticsearch 5.4**

> {
> "took": 16,
> "timed_out": false,
> "_shards": {
> "total": 1,
> "successful": 1,
> "failed": 0
> },
> "hits": {
> "total": 3,
> "max_score": 1.5381224,
> "hits": [
> {
> "_index": "test",
> "_type": "object",
> "_id": "AVzjOOdilllQ-Gyal6Z9",
> "_score": 168.5381224,
> "fields": {
> "docid": [
> "2"
> ]
> }
> }, {
> "_index": "test",
> "_type": "object",
> "_id": "AVzjOOdilllQ-Gyal63Z",
> "_score": 164.5381224,
> "fields": {
> "docid": [
> "3"
> ]
> }
> }, {
> "_index": "test",
> "_type": "object",
> "_id": "AVzjOOdilllQ-Gyal6Z",
> "_score": 132.381224,
> "fields": {
> "docid": [
> "4"
> ]
> }
> }}

The output is same in both versions except the score of the documents. version 5.4 is giving more score than 2.4. We are dependent on score for our work so if the score changes then its a problem for us. Please provide solution for this?

**Comment by jpountz** [comment] 2017-07-12 12:26
It might be due to the change of the default similarity in 5.0 from TF-IDF to BM25.

**Comment by dadoonet** [comment] 2017-07-12 12:29
Question is also opened in https://discuss.elastic.co/t/elastic-search-more-like-this-query-score-issue-in-5-x/92801/1

**Comment by javanna** [comment] 2017-07-12 12:29
I would add that the important bit is that the order of the documents stays about the same. Relying on a specific result (1 rather than 10 or 100) for the score can lead to problems given that the score changes as you index new documents (due to idf).

**Comment by javanna** [comment] 2017-07-12 12:30
Closing, better suited for our discuss forum. We reserve github issues for confirmed bugs or feature requests and this does not seem to be a bug.

**Closed by javanna** 2017-07-12 12:30 UTC

**Comment by sanjaykanani** [comment] 2017-07-13 03:44
@jpountz  thanks for your comment we have changed default similarity type to "classic" and got same result as previous.
