### ISSUE TITLE
Elasticsearch update script is not working

### ISSUE THREAD

**Issue by vk18vk** [elastic/elasticsearch#32491] opened 2018-07-31 10:05 UTC
As mentioned in https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html
above link tried updating a document in elasticsearch
Version: 5.1.2
request tried:
URL: http://localhost:9200/idx001/sdoc/f07d3ad282fb5303156851317bc36c29/_update
request body: {
"script" : "ctx._source.offices = vijay"
}

Result: { "error": { "root_cause": [ { "type": "remote_transport_exception", "reason": "[ssssss-node-1][127.0.0.1:9300][indices:data/write/update[s]]" } ], "type": "illegal_argument_exception", "reason": "failed to execute script", "caused_by": { "type": "illegal_argument_exception", "reason": "script_lang not supported [painless]" } }, "status": 400 }

please check

**Comment by nik9000** [comment] 2018-07-31 14:09
It looks like you've got Elasticsearch deployed in a "funny" way that doesn't have the `lang-painless` module. This used to happen a fair bit when folks when try to embed Elasticsearch inside another Java application. That isn't supported and will caused stuff like this. Beyond that it is hard to tell what is up.

Since this is *probably* not a bug in Elasticsearch I'm going to close this. If you want help deploying Elasticsearch please head to https://discuss.elastic.co . If you think this is genuinely a bug please provide steps for exactly how you deployed Elasticsearch and reopen the issue.

**Closed by nik9000** 2018-07-31 14:09 UTC
