### ISSUE TITLE
Concurrency issue with java slice api

### ISSUE THREAD

**Issue by aping** [elastic/elasticsearch#24766] opened 2017-05-18 08:29 UTC
**Elasticsearch version**: 5.4.0

**Plugins installed**: []

**JVM version** : 1.8.0_131(both client and server)

**OS version** : Linux 4.4.0-77-generic

**Description of the problem including expected versus actual behavior**:

***serial***:
```
            List<SearchResponse> responses = IntStream.range(0, numSlice).mapToObj(i -> {
                SliceBuilder sliceBuilder = new SliceBuilder(i, numSlice);
                SearchResponse response = transportClient.prepareSearch(index).setTypes(type).
                        setSource(searchSourceBuilder).
                        setScroll(scrollTimeout).
                        slice(sliceBuilder).
                        setSize(scrollSize).get();
                log.warn("hits for slice {}: {}", i, response.getHits().getTotalHits());
                return response;
            }).collect(Collectors.toList());
```
output:
hits for slice 0: 1600
hits for slice 1: 1571
hits for slice 2: 1618
hits for slice 3: 1551
hits for slice 4: 1542

***concurrent (note `.parallel()`)***:
```
            List<SearchResponse> responses =IntStream.range(0, numSlice).parallel().mapToObj(i -> {
                SliceBuilder sliceBuilder = new SliceBuilder(i, numSlice);
                SearchResponse response = transportClient.prepareSearch(index).setTypes(type).
                        setSource(searchSourceBuilder).
                        setScroll(scrollTimeout).
                        slice(sliceBuilder).
                        setSize(scrollSize).get();
                log.warn("hits for slice {}: {}", i, response.getHits().getTotalHits());
                return response;
            }).collect(Collectors.toList());
```

output:
hits for slice 1: 1571
hits for slice 0: 1571
hits for slice 4: 1571
hits for slice 2: 1571
hits for slice 3: 1551

So does it mean we have to get the first response of each slice serially(If so, I think that beats the purpose of slice itself)? After that, I can get the rest of each response in parallel.

Plus, personally I feel the slice api pretty awkward.
For example, say let's first send the server a request with the usual query and sort options, together with the number of slices we want, the server returns several scroll ids matching each slice(but no need of actual data of matching documents at all).
That's request No.1
Then we can use those scroll ids to retrieve the matching documents with subsequent requests.
Wouldn't that be more intuitive?

**Comment by jimczi** [comment] 2017-05-18 11:04
First of all are you sure that you're using 5.4.0 ? There was a bug in 5.3 where the hashing used to do the slicing was not consistent between the nodes:
https://github.com/elastic/elasticsearch/pull/23795

The bug is fixed in 5.3.1 and beyond so I tried to reproduce this issue on 5.4.0 but it worked as expected even when I have multiple nodes and active replicas in my index. If you still see this discrepancy in 5.4.0, can you try to create a small recreation that triggers the issue ?
Or at least provide the number of shards that your index have as well as the query you're using in your test.

Regarding the parallelism, each scroll is independent so by design the requests should work independently. 
We also discussed if we should have a single request that return the scroll id for each slice and decided not to do it especially because slices are independent from each other. You could decide to do slice number 10 only when the slices 0-9 are finished. In such case you don't want to have an open scroll for the slice 10 while the other slices are processed.

**Comment by aping** [comment] 2017-05-19 06:37
The version is 5.4.0 indeed, and I think I know how to reproduce it. The catch is to use the same `SearchSourceBuilder` in each thread.

Here's the code:
```
String index = "test_slice";
String type = "test_slice";

Settings settings = Settings.builder()
		.put("cluster.name", "docker-cluster")
		.build();

TransportClient client = new PreBuiltTransportClient(settings).addTransportAddress(
		new InetSocketTransportAddress(new InetSocketAddress("host", 9300)));

//delete
try {
	DeleteIndexResponse deleteIndexResponse = client.admin().indices().
			prepareDelete(index).
			execute().actionGet();
	log.info("Delete index resp: {}", deleteIndexResponse.isAcknowledged());
} catch (IndexNotFoundException e) {
	log.info("no index");
}

//create test data
//public static class TestSlice {
//	private int id;
//	private String name;
//}
List<TestSlice> list = new ArrayList<>();
for (int i = 0; i < 100; i++) {
	list.add(new TestSlice(i, "name " + i));
}

BulkRequestBuilder bulkRequest = client.prepareBulk();
list.forEach(ts -> {
	try {
		bulkRequest.add(
				client.prepareIndex(index, type, String.valueOf(ts.getId())).
					setSource(JsonUtil.toJsonBytes(ts), XContentType.JSON)
		);
	} catch (JsonProcessingException e) {
		throw new RuntimeException("Fail to serialize {}: " + ts, e);
	}
});
BulkResponse bulkResponse = bulkRequest.get();
if (bulkResponse.hasFailures()) {
	throw new RuntimeException("Fail to index documents: " + bulkResponse.buildFailureMessage());
}

//wait for a while, otherwise we can't get search result
try {
	Thread.sleep(2000);
} catch (InterruptedException e) {
	e.printStackTrace();
}

//search slice
int slices = 5;
int scrollSize = 10;
TimeValue scrollTimeout = new TimeValue(60 * 1000);

//NOTE THIS: THE searchSourceBuilder is reused
SearchSourceBuilder searchSourceBuilder = SearchSourceBuilder.searchSource();
searchSourceBuilder.query(QueryBuilders.termQuery("name", "name"));
IntStream.range(0, slices).parallel().forEach(i -> {
	//prepare search
	SliceBuilder sliceBuilder = new SliceBuilder(i, slices);
	SearchResponse response = client.prepareSearch(index).setTypes(type).
			setSource(searchSourceBuilder).
			setScroll(scrollTimeout).
			slice(sliceBuilder).
			setSize(scrollSize).
			setFetchSource("id", null).
			get();
	List<String> r = Arrays.stream(response.getHits().getHits()).
			map(SearchHit::getSourceAsString).collect(Collectors.toList());
	log.info("slice {}, response: {}", i, r);
});
```

And note that when I create the searchSourceBuilder in each thread itself, then it looks correct.

**Comment by jimczi** [comment] 2017-05-19 07:23
> And note that when I create the searchSourceBuilder in each thread itself, then it looks correct.

Sorry I missed this part. The `SliceBuilder` is part of the `SearchSourceBuilder` so when you change the slice in your parallel calls it affects all the threads. Instead you should create a new SearchSourceBuilder for each thread and reuse the `QueryBuilder` part if you want.

**Closed by jimczi** 2017-05-19 07:23 UTC
Labels: :Scroll
