### ISSUE TITLE
Multi get API does not honor the alias routing if alias without custom routing are also present

### ISSUE THREAD

**Issue by goodfella1408** [elastic/elasticsearch#26116] opened 2017-08-09 11:50 UTC
Bug report

Elasticsearch version : 2.4.4

Plugins installed: [marvel,licence]

JVM version: 1.8.0_111

OS version:14.04.1-Ubuntu

multi get API does not honor the routing in alias 

 1. Create a ES index (lets say index_name) with a alias (at this point only create alias without custom routing) - alias_without_custom_routing
 2. Index some documents using alias_without_custom_routing
 3. Now create a alias with custom routing - -
curl -XPUT http://localhost:9200/index_name/_alias/alias_with_custom_routing -d '{
  "routing": "routing-XYZ",
  "filter": {
    "term": {
      "filter-1": "filter-1-value"
    }
  }
}'
 3. Create and Update operations using the above alias , honor the routing derived from the alias
 4. Multi get operations do not honor the routing in the alias -
 curl localhost:9200/_mget -d '{
    "docs" : [
        {
            "_index" : "alias_with_custom_routing",
            "_type" : "type-123",
            "_id" : "doc_id"
        }
    ]
}'

does not return anything ,if the doc is not found based on default routing - the custom routing from alias is not used !
Documents are returned only when the routing is passed explicitly -
 curl localhost:9200/_mget -d '{
    "docs" : [
        {
            "_index" : "alias_with_custom_routing",
            "_type" : "type-123",
            "_id" : "doc_id",
            "_routing": "routing-XYZ"
        }
    ]
}'
Above command returns the document with id doc_id

**Comment by imotov** [comment] 2017-08-11 13:47
@goodfella1408 this should be fixed in 2.4.6 by #25697. I tried to reproduce it on 2.4.6 and everything seems to work correctly. Could you check 2.4.6 to see if it fixes your problem? 

This seems to be a duplicate of #25696

**Comment by imotov** [comment] 2017-09-27 13:28
No feedback for more than a month, so I am assuming that this is indeed a duplicate of #25696.

**Closed by imotov** 2017-09-27 13:28 UTC
Labels: :Aliases
