### ISSUE TITLE
Percolate Query on range with Constant Score doesn't return correct results

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#52658] opened 2020-02-21 17:59 UTC
The error happens on 7.x and master:

Steps to reproduce:
```js
DELETE myindex
PUT /myindex
{
  "mappings": {
    "properties": {
      "d": {
        "type": "date"
      },
      "q": {
        "type": "percolator"
      }
    }
  }
} 
PUT /myindex/_doc/1?refresh
{
  "q": {
    "bool": {
      "must": [
        {
          "range": {
            "d": {
              "gt": "now"
            }
          }
        }
      ]
    }
  }
} 
PUT myindex/_doc/2?refresh
{
  "q": {
    "bool": {
      "should": [
        {
          "range": {
            "d": {
              "lt": "now"
            }
          }
        }
      ]
    }
  }
}
# Having the expected result
GET /myindex/_search
{
  "query": {
    "percolate": {
      "field": "q",
      "document": {
        "d": "2010-01-18T15:00:00.000+11:00"
      }
    }
  }
}
# Getting two hits, should be just one
GET /myindex/_search
{
  "query": {
    "constant_score": {
      "filter": {
        "percolate": {
          "field": "q",
          "document": {
            "d": "2010-01-18T15:00:00.000+11:00"
          }
        }
      }
    }
  }
}
```

**Comment by matriv** [comment] 2020-02-21 19:35
Closing this as a duplicate of #52617.

**Closed by matriv** 2020-02-21 19:35 UTC
Labels: :Search/Percolator, >bug
