### ISSUE TITLE
[CI] ActivateWatchTests.testDeactivateAndActivate needs to not be sleep based

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#30699] opened 2018-05-17 19:53 UTC
Because this test is sleep based, it can lead to failures on slow or overloaded machines. Eg:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=fedora/1064/console

This needs to be rewritten to not be sleep based.

**Comment by jasontedor** [comment] 2018-05-17 20:00
@hub-cap Can you take a look? I am happy to discuss.

**Comment by hub-cap** [comment] 2018-05-30 18:02
Something interesting to note is that when I attempt to run this and slow it down with a debugger, i can repro the conflict (and I believe that there is code to retry on conflict), but i always see the following line after.

```
2018-05-30T23:42:13,433][DEBUG][o.e.x.w.e.ExecutionService] [node_sd4] executing watch [_id]
[2018-05-30T23:42:13,441][DEBUG][o.e.x.w.h.HistoryStore   ] [node_sd4] indexed watch history record [_id_6e92b1ac-7781-49c3-8c51-7fee439b1c21-2018-05-30T17:56:53.753Z]
...
```

Whereas with the logs above, the `"executing watch..."` is not present.

**Comment by spinscale** [comment] 2018-06-05 16:03
so, I stared at this test and its output a bit today, and I think the most important lines are the following:

```
39,448][DEBUG][o.e.x.w.e.ExecutionService] [node_s1] executing watch [_id]
39,483][DEBUG][o.e.x.w.WatcherIndexingListener] [node_s1] removing watch [_id] to trigger service
39,484][DEBUG][o.e.x.w.WatcherIndexingListener] [node_s1] adding watch [_id] to trigger service
39,494][DEBUG][o.e.x.w.e.ExecutionService] [node_s1] failed to execute watch [_id]
 org.elasticsearch.index.engine.VersionConflictEngineException: [doc][_id]: version conflict, current version [3] is different than the one provided [2]
```

What happens here, is that the deactivate watch action first removes the watch from the trigger service. However, then the `ExecutionService.updateWatchStatus()` method is called and adds the watch back to the trigger service. However the index operation fails due to a version conflict exception.

The `WatcherIndexingListener.postIndex(ShardId, Engine.Index, Exception)` logging message is never logged, which means to me that in the mean time this node lost the authority (because the shard might have been moved to another node) over the local watcher shard and thus `triggerService.remove()` is never called.

This brings the question, if the `postIndex` method is the right place for this or if this should be executed in the caller code depending on success or failure, because that `triggerservice.remove()` might only make sense if put watch action, a ack watch or a activate watch action is executed, but not if the execution service is called. This requires some more thinking (and also a lot of this is speculation because it is super hard to reproduce this bug so far).

**Comment by tvernum** [comment] 2019-02-21 04:21
@hub-cap Are you still working on this?
I have a plan for how to rework it to avoid the sleep and skip the inactive watch records, if you don't have something in progress.

**Comment by hub-cap** [comment] 2019-02-21 17:50
I do not have anything in progress here @tvernum. this fell off my radar a while ago :) Feel free to reassign it if you have something that will fix/close it.

**Comment by jakelandis** [comment] 2019-05-29 13:34
Removed explicit sleep's and un-muted this test on PR #42396.  

If (when?) this test fails again please obtain the following information before muting the test:

* Copy of the relevant failure
* Copy of the reproduce line
* The Jenkins build link 
* The Gradle scan link
* The relevant cluster logs from "Google Cloud Storage Upload Report" (link found in Jenkins build)

**Comment by henningandersen** [comment] 2019-06-10 14:53
This failed again here:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=fedora-29&&immutable/23/testReport/org.elasticsearch.xpack.watcher.transport.action.activate/ActivateWatchTests/testDeactivateAndActivate/

with:
```
java.lang.AssertionError: All incoming requests on node [node_sd1] should have finished. Expected 0 but got 254
Expected: <0L>
     but: was <254L>
	at __randomizedtesting.SeedInfo.seed([F5D256C04064759:AF055D91CB5F9125]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.elasticsearch.test.InternalTestCluster.lambda$assertRequestsFinished$35(InternalTestCluster.java:2297)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:862)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:836)
	at org.elasticsearch.test.InternalTestCluster.assertRequestsFinished(InternalTestCluster.java:2294)
	at org.elasticsearch.test.InternalTestCluster.assertAfterTest(InternalTestCluster.java:2272)
	at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:567)
	at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2066)
```

Gradle scan link:

https://scans.gradle.com/s/jkajvplgqp2w6

Reproduce line:

```
REPRODUCE WITH: ./gradlew :x-pack:plugin:watcher:test --tests "org.elasticsearch.xpack.watcher.transport.action.activate.ActivateWatchTests.testDeactivateAndActivate" \
  -Dtests.seed=F5D256C04064759 \
  -Dtests.security.manager=true \
  -Dtests.locale=ms \
  -Dtests.timezone=Etc/GMT-11 \
  -Dcompiler.java=12 \
  -Druntime.java=11
```
(did not reproduce locally for me).

Logs from google storage:
[log-files.tar.gz](https://github.com/elastic/elasticsearch/files/3272514/log-files.tar.gz)

This is the only failure since this was un-muted, so will leave this un-muted to allow getting data from further failures if necessary.

**Comment by gwbrown** [comment] 2019-06-24 16:36
This failed again: https://scans.gradle.com/s/wc2lqwkyuk2co

**Comment by jakelandis** [comment] 2019-10-07 14:06
This has been addressed by https://github.com/elastic/elasticsearch/pull/47667 ... basically there is not a tight coupling between de-activating a watch and when the history will be written. Waiting some arbitrary time for something to NOT happen is error prone . The fix to remove the history assertion, and rely on the other aspects of the test to prove correctness.

**Closed by jakelandis** 2019-10-07 14:06 UTC
Labels: :Core/Features/Watcher, >test-failure
