### ISSUE TITLE
Values mapped as a long are occasionally returned as unrelated values in scientific notation

### ISSUE THREAD

**Issue by ciorg** [elastic/elasticsearch#76053] opened 2021-08-03 23:24 UTC
**Elasticsearch version** (`bin/elasticsearch --version`):
7.9.2

**Plugins installed**: []
  none

**JVM version** (`java -version`):
openjdk version "15" 2020-09-15
OpenJDK Runtime Environment AdoptOpenJDK (build 15+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15+36, mixed mode, sharing)

**OS version** (`uname -a` if on a Unix-like system):
CentOS Linux 7 (Core)

Official 7.9.2 images

**Description of the problem including expected versus actual behavior**:
  Field values in results from large queries will occasionally have number values in scientific notation, ie `2.9327049176748e-310`,  instead of the expected value.  

  This was only observed if the query size is greater than approximately 50,000 records and for fields that are mapped to a `long` field data type.  Querying the record by its _id returns the expected values for the fields.  This is not deterministic or readily repeatable, the same query can run and return results with no issues, then return results with the altered value(s).  This also only seems to affect one record in the query results and so far it has never been the same record.

  This was observed in several data sets with different types of records.  The only similarities is that all the elasticsearch versions were 7.9.2 and the effected fields were `long` data types.

Examples:
example record from a large size query with changed values: 
{
         “integer_field1" : 443,
         “integer_field2" : 62457,
	“long_field1" : 443,
        “long_field2" : 62457
        “long_field3": 2.3204447699e-313,
        “long_field4: 215.0000000003942,
}

same record as example1 but queried by record ID
{
 “integer_field1" : 443,
   “integer_field2" : 62457,
  “long_field1" : 443,
  “long_field2" : 62457,
   “long_field3" : 1,
   “long_field4" : 215,
}

example record2 from a query with a large size setting:
{
      integer_field1: 53628,
      integer_field2 : 53,
      long_field1: 2.9327049176748e-310,
      long_field2: 1.25197751667e-312,
      long_field3: 2.9328005747723e-310,
      long_field4: 2.93280057477586e-310,
}

same record in example2 but queried by record ID
{
        integer_field1: 53628,
        integer_field2: 53,
	long_field1 : 2,
	long_field2 : 163,
	long_field3 : 428125390,
 	long_field4: 428132000
}

**Steps to reproduce**:
As mentioned above this only affected fields mapped as a `long`, even though the value was not large or close the maximum number size.  

 I used a simple node.js (node version 14.17.0) script that directly queried the elasticsearch cluster using node's native `http` module to send the queries. The query was basically `CLUSTER_URL/INDEX/_search?size=RANDOM_NUMBER`.   The script repeatedly queried the elasticsearch cluster with random `size` values between 50,000 and 100,000.  Eventually a record would be returned with the some values replaced by the exceptionally small scientific notation value.  It usually happened in less than 50 queries.    I also ran a similar python script (version 3.9.6) with the same results.

**Comment by nik9000** [comment] 2021-08-13 14:54
> I used a simple node.js (node version 14.17.0) script that directly queried the elasticsearch cluster using node's native `http` module to send the queries. The query was basically `CLUSTER_URL/INDEX/_search?size=RANDOM_NUMBER`. The script repeatedly queried the elasticsearch cluster with random `size` values between 50,000 and 100,000. Eventually a record would be returned with the some values replaced by the exceptionally small scientific notation value. It usually happened in less than 50 queries. I also ran a similar python script (version 3.9.6) with the same results.

Could you post a link to the reproduction code? We'd prefer the code in a bash script, but anything will probably do so long as its not difficult to set up. Without the reproduction code we'll be making a lot of guesses.

**Comment by ciorg** [comment] 2021-08-19 00:18
@nik9000 thanks for the response.  

Sure, here's a repo with the script - [link](https://github.com/ciorg/elasticsearch_corupt_values_query)

Just need to replace the es cluster url and index name in the index.js file.

**Comment by nik9000** [comment] 2021-08-19 18:00
I ran this for half an hour and didn't see any scientific notation. Here is how I made the data:
```
curl -XDELETE -uelastic:password localhost:9200/test
curl -XPUT -HContent-Type:application/json -uelastic:password localhost:9200/test -d'{
  "settings": {
    "index.max_result_window": 1000000
  }
}'

for i in $(seq 1 10); do
  rm /tmp/bulk
  for n in $(seq 1 10000); do
    echo '{"index": {}}' >> /tmp/bulk
    echo '{"n": '$n', "i": '$i'}' >> /tmp/bulk
  done
  curl -s -XPOST -HContent-Type:application/json -uelastic:password localhost:9200/test/_bulk?pretty --data-binary @/tmp/bulk | grep error
done
```

I *think* what is happening is that you are putting data with scientific notation into ES and we're accepting it  - either rounding it to `0` if the field is a `long` or storing it if the field is a `double`. My suggestion is to have your script log the index and id of the documents with the scientific notation and have a look at them and see if you can figure out how they got that way. That's not a particularly useful suggestion, I know, but it's all I have.

If ES made the scientific notation somehow, could you reopen this with a sequence on commands you can run on an empty cluster that creates the bad document?

**Comment by nik9000** [comment] 2021-08-19 18:01
I'll close this for now just to keep it from showing up when we're not sure its us. If you track it back to us then please reopen it.

**Comment by kstaken** [comment] 2021-08-19 19:15
@nik9000 we spent weeks isolating and tracking this back to ES. If it was in the data it would be stupidly obvious to see, this isn't. It happens in extremely rare circumstances and it does not impact the same record every time.

**Comment by nik9000** [comment] 2021-08-19 19:17
> @nik9000 we spent weeks isolating and tracking this back to ES. If it was in the data it would be stupidly obvious to see, this isn't. It happens in extremely rare circumstances and it does not impact the same record every time.

Oh neat!

**Comment by nik9000** [comment] 2021-08-19 19:25
So let's figure out a way for me to reproduce it. I can't really do anything about it if I can't.

Could you send me the source of a document where this happens? Like, maybe send me what your application sees for that document and what comes back from fetching it. Either post it to a gist or email it to me (my email is public on github). Anonymize it however you need, but the numbers have to line up.

I really need to be able to write something like that bash script to build and index so I can run your test. The best way to get us to fix this is for you to build such a bash script. I'll try and use your records in my script just for good measure but I'm not sure I'll get anywhere.

**Comment by nik9000** [comment] 2021-08-19 19:41
Could you log the raw output that makes one of the corrupt documents and find the json for the bad doc in it? I'd like to make sure that it isn't the json parsing. The example you gave me doesn't do any sort of source filtering so I'd expect us to have copied the exact bytes in the `_source` and sent them out the wire. I'm wondering what they look like.

**Comment by kstaken** [comment] 2021-08-19 20:06
@ciorg will help you with this. He provided the script he was using to reproduce it above. 

As far as we can tell it doesn't seem to be related to the specific data. Once we had isolated it to ES 7.9.2 we were able to reproduce it on other datasets stored in the same version of ES on different clusters but were not able to reproduce it on older versions. We do not yet run any newer versions of ES in production so can't provide insight there.

I would agree that it does seem like the fields should just be copied from _source but it's very odd that the issue has only ever shown up on fields mapped as longs and we've seen no evidence of any kind of data corruption on other fields or anything else related to the record, only in the value of long fields. And it's only the occasional record out of potentially billions of results, and not the same record repeatedly.

FYI, the data here is customer data so we can't share anything related to it but there's really nothing special about the data just simple numbers well within the limits for a long field.

**Comment by nik9000** [comment] 2021-08-20 13:51
> @ciorg will help you with this. He provided the script he was using to reproduce it above.

Sorry, I wasn't paying close attention to the replies. 

I jumped on our 7.9 branch and tried to reproduce and couldn't so either it's fixed in a patch release or its something sneaky. At this point I'm going to wait until y'all can send me more to reproduce it. Like I said, something that I can run against an empty cluster would be best, especially because you can't share the actual documents with me.

**Comment by ciorg** [comment] 2021-08-20 16:25
So far I've only seen it when querying customer data, I'm trying to reproduce it with my own fabricated data sets. I'll let you know when I get the formula.

**Comment by nik9000** [comment] 2021-08-20 16:58
> So far I've only seen it when querying customer data, I'm trying to reproduce it with my own fabricated data sets. I'll let you know when I get the formula.

Good luck! I wish there was anything I could do for you.


Oooh - you could mess with [`preference`](https://www.elastic.co/guide/en/elasticsearch/reference/7.9/search-search.html#search-preference). It might be that this is hard to reproduce because your shards have different data *somehow*. If you find that you can consistently get it to reproduce with a particular preference value but never reproduce with another that says something!

**Comment by javanna** [comment] 2024-06-13 12:50
We were sadly never able to reproduce this. Please comment on this issue if you can recreate the issue and we will reopen it.

**Closed by javanna** 2024-06-13 12:50 UTC
Labels: >bug, :Search/Mapping, Team:Search
