### ISSUE TITLE
[CI] InternalEngineTests testSegmentsStatsIncludingFileSizes fails

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#29157] opened 2018-03-20 10:29 UTC
Single failure on 6.x so far:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+aggressive-opts/821/consoleFull

Unfortunately I couldn't reproduce locally:
```
REPRODUCE WITH: ./gradlew :server:test \
  -Dtests.seed=5EEEF3F32C309B9E \
  -Dtests.class=org.elasticsearch.index.engine.InternalEngineTests \
  -Dtests.method="testSegmentsStatsIncludingFileSizes" \
  -Dtests.security.manager=true \
  -Dtests.jvm.argline="-XX:+AggressiveOpts" \
  -Dtests.locale=es-PY \
  -Dtests.timezone=W-SU
```

The error assertion message looks like this:
```
04:54:53 FAILURE 0.12s J2 | InternalEngineTests.testSegmentsStatsIncludingFileSizes <<< FAILURES!
04:54:53    > Throwable #1: java.lang.AssertionError: 
04:54:53    > Expected: a value greater than <78L>
04:54:53    >      but: <78L> was equal to <78L>
04:54:53    > 	at __randomizedtesting.SeedInfo.seed([5EEEF3F32C309B9E:C314E50796FAC0D9]:0)
04:54:53    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
04:54:53    > 	at org.elasticsearch.index.engine.InternalEngineTests.testSegmentsStatsIncludingFileSizes(InternalEngineTests.java:559)
```

Looking at the test in question it seems like the previous engine refresh should increase the segment stats, which seems to be true in most cases. Not sure if the assertion is wrong or something changed internally.

**Comment by bleskes** [comment] 2018-05-06 11:32
@dnhatn what is the status of this one? do you know the root cause?

**Comment by dnhatn** [comment] 2018-06-06 13:17
This test has not failed for the last three months. I am closing this and will keep an eye on it.

**Closed by dnhatn** 2018-06-06 13:17 UTC
Labels: :Distributed/Engine, >test-failure
