### ISSUE TITLE
[CI] CcrRollingUpgradeIT testCannotFollowLeaderInUpgradedCluster failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#100291] opened 2023-10-04 16:29 UTC
This looks like more fallout from the 8.12 version bump.

**Build scan:**
https://gradle-enterprise.elastic.co/s/iznsqgeozhlcw/tests/:x-pack:qa:rolling-upgrade-multi-cluster:v8.11.0%23follower%23upgradedClusterTest/org.elasticsearch.upgrades.CcrRollingUpgradeIT/testCannotFollowLeaderInUpgradedCluster
**Reproduction line:**
```
./gradlew ':x-pack:qa:rolling-upgrade-multi-cluster:v8.11.0#follower#upgradedClusterTest' -Dtests.class="org.elasticsearch.upgrades.CcrRollingUpgradeIT" -Dtests.method="testCannotFollowLeaderInUpgradedCluster" -Dtests.seed=27E3EAD1DEC83E86 -Dtests.bwc=true -Dtests.locale=sl-SI -Dtests.timezone=America/Caracas -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.upgrades.CcrRollingUpgradeIT&tests.test=testCannotFollowLeaderInUpgradedCluster
**Failure excerpt:**
```
junit.framework.AssertionFailedError: Expected exception ResponseException but no exception was thrown

  at __randomizedtesting.SeedInfo.seed([27E3EAD1DEC83E86:A9BC1A5D74E1259D]:0)
  at org.apache.lucene.tests.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2864)
  at org.apache.lucene.tests.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2850)
  at org.elasticsearch.upgrades.CcrRollingUpgradeIT.testCannotFollowLeaderInUpgradedCluster(CcrRollingUpgradeIT.java:223)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by thecoop** [comment] 2023-10-17 15:51
This is indeed broken by the 8.12 version commit 132220bf83b1b8177a7c83906abf9bbbb830c8bd, but the cause is not clear

**Comment by idegtiarenko** [comment] 2023-11-07 15:15
This test verifies that and older cluster can not follow and index created in a newer cluster.
Previously this check was linked to elasticsearch version, now it is updated to use `IndexVersion` instead: https://github.com/elastic/elasticsearch/blob/8e6e0e59ea34be29a6495f0680944d6a7f559756/server/src/main/java/org/elasticsearch/snapshots/RestoreService.java#L973-L982

Above check is failing as the latest `IndexVersion` is the same (`8_500_003`) for both versions:
* 8.11: https://github.com/elastic/elasticsearch/blob/57a067c08a37739ccf360ad4ec19063aca920ee0/server/src/main/java/org/elasticsearch/index/IndexVersion.java#L128
* current main: https://github.com/elastic/elasticsearch/blob/8a1db8c6c3ffa8028b98c9c1393aee9d9ea4d6f5/server/src/main/java/org/elasticsearch/index/IndexVersions.java#L89
and this currently allows an older 8.11 version to follow an index with the same version from the never main version.

If this is expected then _some_ elasticsearch versions become forward compatible re CCR.
If this is not expected then we need to introduce a new IndexVersion for every minor elasticsearch release.

**Comment by idegtiarenko** [comment] 2023-11-07 15:25
The test could be fixed with the following patch:
```
Index: x-pack/qa/rolling-upgrade-multi-cluster/src/test/java/org/elasticsearch/upgrades/CcrRollingUpgradeIT.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/x-pack/qa/rolling-upgrade-multi-cluster/src/test/java/org/elasticsearch/upgrades/CcrRollingUpgradeIT.java b/x-pack/qa/rolling-upgrade-multi-cluster/src/test/java/org/elasticsearch/upgrades/CcrRollingUpgradeIT.java
--- a/x-pack/qa/rolling-upgrade-multi-cluster/src/test/java/org/elasticsearch/upgrades/CcrRollingUpgradeIT.java	(revision d3aec39c72e0a7c5f4ad0ed684a1b57efc822a28)
+++ b/x-pack/qa/rolling-upgrade-multi-cluster/src/test/java/org/elasticsearch/upgrades/CcrRollingUpgradeIT.java	(date 1699370559030)
@@ -204,7 +204,6 @@
         }
     }
 
-    @AwaitsFix(bugUrl = "https://github.com/elastic/elasticsearch/issues/100291")
     public void testCannotFollowLeaderInUpgradedCluster() throws Exception {
         if (upgradeState != UpgradeState.ALL) {
             return;
@@ -225,8 +224,8 @@
                 ResponseException.class,
                 () -> followIndex(leaderClient(), "follower", "not_supported", "not_supported")
             );
-            assertThat(e.getMessage(), containsString("the snapshot was created with Elasticsearch version ["));
-            assertThat(e.getMessage(), containsString("] which is higher than the version of this node ["));
+            assertThat(e.getMessage(), containsString("the snapshot was created with index version ["));
+            assertThat(e.getMessage(), containsString("] which is higher than the version used by this node ["));
         } else if (clusterName == ClusterName.LEADER) {
             // At this point all nodes in both clusters have been updated and
             // the leader cluster can now follow not_supported index in the follower cluster:
Index: server/src/main/java/org/elasticsearch/index/IndexVersions.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/server/src/main/java/org/elasticsearch/index/IndexVersions.java b/server/src/main/java/org/elasticsearch/index/IndexVersions.java
--- a/server/src/main/java/org/elasticsearch/index/IndexVersions.java	(revision d3aec39c72e0a7c5f4ad0ed684a1b57efc822a28)
+++ b/server/src/main/java/org/elasticsearch/index/IndexVersions.java	(date 1699370209307)
@@ -87,6 +87,7 @@
     public static final IndexVersion NEW_SPARSE_VECTOR = def(8_500_001, Version.LUCENE_9_7_0);
     public static final IndexVersion SPARSE_VECTOR_IN_FIELD_NAMES_SUPPORT = def(8_500_002, Version.LUCENE_9_7_0);
     public static final IndexVersion UPGRADE_LUCENE_9_8 = def(8_500_003, Version.LUCENE_9_8_0);
+    public static final IndexVersion ES_VERSION_BUMP = def(8_500_004, Version.LUCENE_9_8_0);
 
     /*
      * STOP! READ THIS FIRST! No, really,

```

**Comment by williamrandolph** [comment] 2023-11-07 15:45
If there hasn't actually been any change to the index format, would we expect anything to go wrong if the "new" cluster followed the "old" cluster? In other words, would we be bumping the version in order to avoid bugs, or would we be bumping it so that it's easy to describe CCR compatibility between clusters?

**Comment by ldematte** [comment] 2023-11-09 14:53
This kept failing (twice today) so I backported the mute to 8.11

**Closed** 2023-11-22 09:10 UTC
Labels: :Core/Infra/Core, >test-failure, :Distributed/CCR, team-discuss, Team:Core/Infra, Team:Distributed, medium-risk
