### ISSUE TITLE
restart a node, then tomorrow, lots of shards lost

### ISSUE THREAD

**Issue by xushjie1987** [elastic/elasticsearch#20578] opened 2016-09-20 09:19 UTC
# 

**Elasticsearch version**:

**Plugins installed**: [2.1.1-2.4.0]

**JVM version**:1.8

**OS version**:centos7

**Description of the problem including expected versus actual behavior**:

{
    "error": {
        "root_cause": [
            {
                "type": "remote_transport_exception",
                "reason": "[node3][10.174.9.215:9300][cluster:admin/reroute]"
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "[allocate] allocation of [ai-2016.09.17][0] on node {node4}{X7AdQqLZQTSKOhhOIFGoJg}{10.45.149.165}{10.45.149.165:9300}{max_local_storage_nodes=1, master=true} is not allowed, reason: [YES(below shard recovery limit of [2])][YES(node passes include/exclude/require filters)][YES(allocation disabling is ignored)][YES(total shard limit disabled: [index: -1, cluster: -1] <= 0)][YES(primary is already active)][YES(shard not primary or relocation disabled)][YES(shard is not allocated to same node or host)][YES(no allocation awareness enabled)][YES(enough disk for shard on node, free: [334.2gb])][NO(target node version [2.1.1] is older than source node version [2.4.0])][YES(allocation disabling is ignored)]"
    },
    "status": 400
}

**Steps to reproduce**:
1. disable allocation
   {
   "transient": {
       "cluster.routing.allocation.enable": "none"
   }
   }
2. execute synced flush
3. kill one node (e.g. node1)
4. ...tomorrow...
5. restart node1, change the elasticsearch version to 2.4.0, but configuration not changed.
6. enable allocation
   {
   "transient": {
       "cluster.routing.allocation.enable": "none"
   }
   }
   1. then the cluster become "red", some indices's primary shard become UNASSIGNED
   2. my index is created based day-time, for example: 
      ct-2016.09.20       9     p      STARTED       599284 230.3mb 10.174.9.234  node2 
      ct-2016.09.19       0     p      STARTED       599909 231.7mb 10.174.9.224  node5 
      ct-2016.09.19       0     r      STARTED       599909 228.2mb 10.174.9.177  node1 
      ct-2016.09.17       8     p      STARTED       600222 229.7mb 10.174.9.177  node1 
      ct-2016.09.17       8     r      UNASSIGNED  
7. then i wait for a long time, lots of shards still UNASSIGNED
   1. so i have to do cluster reroute:
      curl -XPOST "xxx:9200/_cluster/reroute" -d "{
          "commands" : [ 
              {
                  "allocate" : {
                      "index" : "ct-2016.09.17",
                      "shard" : 12,
                      "node" : "",
                      "allow_primary" : true
                  }
              }
          ]
      }"
   2. then the UNASSIGNED primary shard become STARTED, but its size become 0!!!
      ct-2016.09.17       12    p      STARTED            0    159b 10.174.9.177  node1 
      ct-2016.09.17       12    r      UNASSIGNED  
      ct-2016.09.17       9     p      STARTED            0    159b 10.174.9.177  node1 
      ct-2016.09.17       9     r      UNASSIGNED  
      ct-2016.09.17       11    p      STARTED            0    159b 10.174.9.177  node1 
      ct-2016.09.17       11    r      UNASSIGNED  
   3. when i try to reroute the UNASSIGNED replica shard, i get exception: 
      {
      "error": {
      "root_cause": [
          {
              "type": "remote_transport_exception",
              "reason": "[node3][10.174.9.215:9300][cluster:admin/reroute]"
          }
      ],
      "type": "illegal_argument_exception",
      "reason": "[allocate] allocation of [ai-2016.09.17][0] on node {node4}{X7AdQqLZQTSKOhhOIFGoJg}{10.45.149.165}{10.45.149.165:9300}{max_local_storage_nodes=1, master=true} is not allowed, reason: [YES(below shard recovery limit of [2])][YES(node passes include/exclude/require filters)][YES(allocation disabling is ignored)][YES(total shard limit disabled: [index: -1, cluster: -1] <= 0)][YES(primary is already active)][YES(shard not primary or relocation disabled)][YES(shard is not allocated to same node or host)][YES(no allocation awareness enabled)][YES(enough disk for shard on node, free: [334.2gb])][NO(target node version [2.1.1] is older than source node version [2.4.0])][YES(allocation disabling is ignored)]"
      },
      "status": 400
      }
   4. i tried restart today, not wait for tomorrow, there isn't any question.

PS: I'm sorry, i found there's a bash script register to the crontab, it delete the old index in the night, but why couldn't i reroute the UNASSIGNED shard to or from new version elasticsearch from or old version elasticsearch?

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by jasontedor** [comment] 2017-04-29 13:00
Since it looks like this was caused by a cron job on your end, I'm closing this issue.

**Closed by jasontedor** 2017-04-29 13:00 UTC
Labels: :Allocation
