### ISSUE TITLE
simulate overwrites 'reserved' properties in source doc

### ISSUE THREAD

**Issue by BigFunger** [elastic/elasticsearch#21050] opened 2016-10-20 19:58 UTC
**Elasticsearch version**: elasticsearch-6.0.0-alpha1-SNAPSHOT

**Plugins installed**: ingest-geoip

The Ingest Simulate process overwrites existing properties in the source document if they are named the same as a property that ingest uses internally.

**Steps to reproduce**:
Making the following simulate request:

```
POST _ingest/pipeline/_simulate?verbose=true
{
  "pipeline": {
    "description": "",
    "processors": [
      {
        "set": {
          "tag": "set_1",
          "field": "foo",
          "value": "bar"
        }
      }
    ]
  },
  "docs": [
    {
      "_source": {
        "_id": "id value that I want to keep",
        "foo": "bar"
      }
    }
  ]
}
```

causes the following result

```
{
  "docs": [
    {
      "processor_results": [
        {
          "tag": "set_1",
          "doc": {
            "_index": "_index",
            "_type": "_type",
            "_id": "_id",
            "_source": {
              "foo": "bar"
            },
            "_ingest": {
              "timestamp": "2016-10-20T19:47:11.908+0000"
            }
          }
        }
      ]
    }
  ]
}
```

Note that even though the one processor in the pipeline does nothing with the `_id` field, it is removed from the `_source` object.

**Comment by talevy** [comment] 2016-10-20 20:01
Both `_type` and `_id` fields are reserved and are being defaulted to "_type" and "_id" respectively.

here:

https://github.com/talevy/elasticsearch/blob/d406b88857a299f7995ac829abf17020d2353069/core/src/main/java/org/elasticsearch/action/ingest/SimulatePipelineRequest.java#L155-L156

For users to test any pipelines wishing to operate on these fields, they must be migrated outside of the `_source`, and in the top-level document json.

**Comment by talevy** [comment] 2016-10-20 20:11
A solution for this would be to have a fallback strategy where we

1. default to the outer `_id`
2. fall-back to the `_source._id` field
3. set to _id="_id" if first two are missing.

**Comment by BigFunger** [comment] 2016-10-20 20:14
It seems strange that it modifies the `_source._id` property at all. From a consumer standpoint, the reserved `_id` field used by ingest simulate appears to be a separate 'meta' field which is a sibling of `_source`.

**Comment by javanna** [comment] 2016-10-20 20:54
Not sure what is going on in the simulate api and for sure this behaviour is weird, but the `_source._id` field doesn't make much sense. If you try to index a document with such a field, here is what you get:

```
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Field [_id] is a metadata field and cannot be added inside a document. Use the index API request parameters."}],"type":"mapper_parsing_exception","reason":"Field [_id] is a metadata field and cannot be added inside a document. Use the index API request parameters."},"status":400}
```

**Comment by clintongormley** [comment] 2017-01-12 10:34
@talevy just a ping because this looks like it has been forgotten

**Comment by talevy** [comment] 2017-01-12 20:50
thanks @clintongormley, I'll take another look at this next week

**Comment by talevy** [comment] 2017-01-23 23:24
Since ES doesn't allow any one of these metadata fields in the source:

```
* _timestamp
* _routing
* _parent
* _index
* _type
* _id
```

I am inclined to add validators on the IngestDocument constructor / setters to complain up-front and say you cannot do this. Does anyone see a problem with this? One big reason why I dislike this approach is that I am re-implementing the same checks that the mapping validator does when one *actually* indexes these documents. Without short-circuiting up-front, the expected behavior handling these special fields is ambiguous.

**Comment by talevy** [comment] 2018-03-15 15:15
Closing due to staleness. Anyone that stumbles upon this again, feel free to re-open this issue

**Closed by talevy** 2018-03-15 15:15 UTC
Labels: :Core/Ingest, >bug, discuss, v6.0.3
