### ISSUE TITLE
 ES selectively accepts/rejects documents via Elasticsearch .Net BulkAll() method

### ISSUE THREAD

**Issue by HenryQW** [elastic/elasticsearch#37765] opened 2019-01-23 13:38 UTC
**Elasticsearch version** (`bin/elasticsearch --version`):
6.5.1 (via docker: docker.elastic.co/elasticsearch/elasticsearch:6.5.1)

**Plugins installed**:
```yaml
elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    container_name: medgate-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=true
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m       
      - bootstrap.memory_lock=true       
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "esdata:/usr/share/elasticsearch/data"
    networks:
      - backend
    expose:
      - "9200"
    restart: on-failure
```
**JVM version** (`java -version`):
Default version comes with the image

**OS version** (`uname -a` if on a Unix-like system):
The host machine (Linux Server 4.4.0-141-generic 167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux)

**Description of the problem including expected versus actual behavior**:
Documents are randomly being accepted by ES, for instance docA worked the Nth time but not the (N+M)th time.

**Steps to reproduce**:

1. Using ElasticClient.Net to post the documents
	```c#
	 var bulkAllObservable = _client.BulkAll(results, b => b
	                    .Index(index)
	                    .Type(type.ToLower())
	                    .BackOffRetries(2)
	                    .BackOffTime("30s")
	                    .RefreshOnCompleted()
	                    .MaxDegreeOfParallelism(4)
	                    .BackOffRetries(2)
	                    .Size(bulkSize));
	
	
	            try
	            {
	                bulkAllObservable.Wait(TimeSpan.FromSeconds(30), b => { });
	            }
	            catch (Exception ex)
	            {
	                _logger.LogWarning(ex, "Result file format was rejected by ElasticSearch");
	            }
	```
 1. The document, note that in the last `prescription` object, `"dose-value": "-1"` which is inconsistent with the rest, but ES was happy to take it and assign it with `float` type.
	```json
	{
	  "text": "redacted",
	  "entities": {
	    "Prescription": [
	      {
	        "indices": [238, 265],
	        "status": "continuing",
	        "drug": "Sodium Valproate",
	        "drug-type": "BNF_generic",
	        "route": "unknown",
	        "tense": "past",
	        "dose": "1000mgs",
	        "dose-value": 1000.0,
	        "dose-unit": "mgs",
	        "dose-multiple": "1",
	        "frequency": 2.0,
	        "time-unit": "day",
	        "interval": 1.0
	      },
	      {
	        "indices": [269, 289],
	        "frequency": 2.0,
	        "drug": "Zonisamide",
	        "drug-type": "BNF_generic",
	        "status": "continuing",
	        "tense": "present",
	        "dose": "250mgs",
	        "route": "unknown",
	        "dose-value": 250.0,
	        "dose-unit": "mgs",
	        "dose-multiple": "1",
	        "time-unit": "day",
	        "interval": 1.0
	      },
	      {
	        "indices": [1345, 1368],
	        "drug": "Sodium Valproate",
	        "drug-type": "BNF_generic",
	        "status": "continuing",
	        "tense": "present",
	        "dose": "unknown",
	        "dose-value": "-1",
	        "dose-unit": "unknown",
	        "dose-multiple": "1",
	        "route": "unknown"
	      }
	    ]
	  }
	}
	```
 1. The mapping produced, note the aforementioned `dose-value` has the type of float:
	```json
	{
	  "mapping": {
	    "test123456": {
	      "properties": {
	        "fileName": {
	          "type": "text",
	          "fields": {
	            "keyword": {
	              "type": "keyword",
	              "ignore_above": 256
	            }
	          }
	        },
	        "id": {
	          "type": "text",
	          "fields": {
	            "keyword": {
	              "type": "keyword",
	              "ignore_above": 256
	            }
	          }
	        },
	        "result": {
	          "properties": {
	            "Prescription": {
	              "properties": {
	                "Directionality": {
	                  "type": "text",
	                  "fields": {
	                    "keyword": {
	                      "type": "keyword",
	                      "ignore_above": 256
	                    }
	                  }
	                },
	                "Length of Time": {
	                  "type": "text",
	                  "fields": {
	                    "keyword": {
	                      "type": "keyword",
	                      "ignore_above": 256
	                    }
	                  }
	                },
	                "Temporality": {
	                  "type": "text",
	                  "fields": {
	                    "keyword": {
	                      "type": "keyword",
	                      "ignore_above": 256
	                    }
	                  }
	                },
	                "Unit of Time": {
	                  "type": "text",
	                  "fields": {
	                    "keyword": {
	                      "type": "keyword",
	                      "ignore_above": 256
	                    }
	                  }
	                },
	                "dose": {
	                  "type": "text",
	                  "fields": {
	                    "keyword": {
	                      "type": "keyword",
	                      "ignore_above": 256
	                    }
	                  }
	                },
	                "dose-multiple": {
	                  "type": "text",
	                  "fields": {
	                    "keyword": {
	                      "type": "keyword",
	                      "ignore_above": 256
	                    }
	                  }
	                },
	                "dose-unit": {
	                  "type": "text",
	                  "fields": {
	                    "keyword": {
	                      "type": "keyword",
	                      "ignore_above": 256
	                    }
	                  }
	                },
	                "dose-value": {
	                  "type": "float"
	                },
	                "drug": {
	                  "type": "text",
	                  "fields": {
	                    "keyword": {
	                      "type": "keyword",
	                      "ignore_above": 256
	                    }
	                  }
	                },
	                "drug-type": {
	                  "type": "text",
	                  "fields": {
	                    "keyword": {
	                      "type": "keyword",
	                      "ignore_above": 256
	                    }
	                  }
	                },
	                "frequency": {
	                  "type": "float"
	                },
	                "indices": {
	                  "type": "long"
	                },
	                "interval": {
	                  "type": "float"
	                },
	                "route": {
	                  "type": "text",
	                  "fields": {
	                    "keyword": {
	                      "type": "keyword",
	                      "ignore_above": 256
	                    }
	                  }
	                },
	                "status": {
	                  "type": "text",
	                  "fields": {
	                    "keyword": {
	                      "type": "keyword",
	                      "ignore_above": 256
	                    }
	                  }
	                },
	                "tense": {
	                  "type": "text",
	                  "fields": {
	                    "keyword": {
	                      "type": "keyword",
	                      "ignore_above": 256
	                    }
	                  }
	                },
	                "time-unit": {
	                  "type": "text",
	                  "fields": {
	                    "keyword": {
	                      "type": "keyword",
	                      "ignore_above": 256
	                    }
	                  }
	                },
	                "when": {
	                  "type": "text",
	                  "fields": {
	                    "keyword": {
	                      "type": "keyword",
	                      "ignore_above": 256
	                    }
	                  }
	                }
	              }
	            }
	          }
	        },
	        "resultCreatedDate": {
	          "type": "date"
	        }
	      }
	    }
	  }
	}
	```
1. A screentshot of the document viewed in Kibana, with the above mapping:	
	![image](https://user-images.githubusercontent.com/5896343/51610025-8bb14100-1f13-11e9-8988-b66d11bbbb4b.png)

1. If the aforementioned `"dose-value": "-1"` is rectified to `"dose-value": -1`, ES is happy to accept it everytime, but unfortunately it's not feasible in my use case.

1. This document (and others) works randomly, I've tried it with:
	1. A fresh ES instance
	1. A new index in the existing ES instance
	The outcome is still the same where ES selectively takes it in or rejects it.

**Provide logs (if relevant)**:
```c#
{Elasticsearch.Net.ElasticsearchClientException: BulkAll halted after receiving failures that can not be retried from _bulk
   at Nest.BlockingSubscribeExtensions.WaitOnObservable[TObservable,TObserve,TObserver](TObservable observable, TimeSpan maximumRunTime, Func`3 factory)
   at Nest.BlockingSubscribeExtensions.Wait[T](BulkAllObservable`1 observable, TimeSpan maximumRunTime, Action`1 onNext)}
```

**Comment by HenryQW** [comment] 2019-01-23 14:44
@romseygeek if I set `bulkSize` to 1, and ingest only one document, it will fail/succeed randomly. That's the part puzzles me

**Comment by henningandersen** [comment] 2019-07-03 16:11
I think this is the same problems as: #40409. In case two shards try to update the mapping (when a new field is discovered), one of them could fail when the auto-discovered type differs (in your case float vs long).

I would like to ask for a couple of clarifications:

1. when you wrote:
> if I set bulkSize to 1, and ingest only one document, it will fail/succeed randomly
you were supposedly still ingesting all documents using the .NET program above, only you had bulkSize=1? Or is it really the case that indexing just one document using bulk with no parallel activity randomly rejects the document?

2. Does this also reproduce if you have bulkSize=1 and use MaxDegreeOfParallelism(1)?

**Comment by HenryQW** [comment] 2019-07-05 14:30
@henningandersen Thanks for looking into this. I've set `bulkSize=200` and `MaxDegreeOfParallelism(4)` it's been stable in production. The edge case of ingesting only 1 document only occurs during dev stage, therefore the product owner was happy about putting this into production.

I've tested with `MaxDegreeOfParallelism(1)` and it seems to avoid this issue.

**Comment by henningandersen** [comment] 2019-07-05 14:53
Thanks for trying this out @HenryQW. I think we can safely conclude that this is a duplicate of #40409 and since that contains tech discussion on the solution I will close this issue.

**Closed by henningandersen** 2019-07-05 14:53 UTC
Labels: :Distributed/CRUD
