### ISSUE TITLE
value_as_string does not match value when aggregation involves "epoch_second" format

### ISSUE THREAD

**Issue by pushshift** [elastic/elasticsearch#41175] opened 2019-04-13 01:56 UTC
**Version:** Elasticsearch version 7.0.0 GA

**Description of problem:**

When an aggregation using an "epoch_second" field is used, the value_as_string amount is 1,000 times less than the actual value field. 

**Expected Result:**

"value_as_string" would more or less match the value field.

Relevant mapping field:

```
    "author_created_delta": {
        "type": "date",
        "format": "epoch_second"
    },
```

**Query:**

```
{
  "size": 0,
  "query": {
    "bool": {
      "must": []
    }
  },
  "aggs": {
    "author_delta": {
      "terms": {
        "field": "author.keyword",
        "order": {
          "score": "asc"
        },
        "min_doc_count": 1000,
        "size": 1,
        "shard_size": 50010
      },
      "aggs": {
        "score": {
          "avg": {
            "field": "author_created_delta"
          }
        }
      }
    }
  }
}
```

**Response:**

```
{
  "took": 13115,
  "timed_out": false,
  "_shards": {
    "total": 8,
    "successful": 8,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 10000,
      "relation": "gte"
    },
    "max_score": null,
    "hits": []
  },
  "aggregations": {
    "author_delta": {
      "doc_count_error_upper_bound": -1,
      "sum_other_doc_count": 38857716,
      "buckets": [
        {
          "key": "Image-to-Braille-Bot",
          "doc_count": 7156,
          "score": {
            "value": 10475043.739519285,
            "value_as_string": "10475.043"
          }
        }
      ]
    }
  }
}
```

**Comment by polyfractal** [comment] 2019-04-15 13:58
Thanks for the report @pushshift.  This feels like a bug introduced during the java-time transition and supporting nanoseconds (being off by exactly 1000).  I'll try to reproduce locally and see what's up.

**Comment by polyfractal** [comment] 2019-04-15 16:30
Actually, I believe this is intended behavior.  I overlooked that the format is `epoch_seconds`.  The value internally is stored as milliseconds since epoch, so when it's formated to `epoch_seconds` it will be 1000 times less than the milliseconds representation.

So the "as_string" value is correct, because that represents the formatted version.  It just so happens that the formatter you chose is also a number (in seconds), which is why it looks different.

**Comment by pushshift** [comment] 2019-04-15 17:37
If that's the intended behavior, that's fine. However, I thought "value_as_string" served as an alternate to value in the event that a number was large or a floating point approximation was very large (similar to how Twitter's id_str is used as supplement to id because Javascript has issues with 64 bit integers.

My feeling on this is that value_as_string should be a string representation of the value field but if this is intended behavior then I understand.

Thanks for looking at this!

**Comment by polyfractal** [comment] 2019-04-15 18:01
Ah I see, gotcha.  Yeah, the `value_as_string` field is the formatted version of the field, which depends on the field formatter of the particular data type. 

The aggregation framework works will all numeric-based values (numbers, dates, scaled_floats, ip addresses, etc) as numbers internally, so the `value` field will be the result of that computation in numeric format.  The `value_as_string` field will then be the value, formatted with the data types string formatting utility.  E.g. IPs get turned back into dot-notation IP addresses, dates turned into whatever specified date format, scaled floats re-scaled back to their resolution, etc.

The naming is perhaps a bit confusing, especially in cases like `epoch_seconds` where there isn't an obvious difference like a string date would have (`1555351107833` vs `Mon Apr 15 2019 17:58:27`).  But at this point changing it would be a big ordeal for backwards compat reasons.

Gonna close this issue, apologies for the confusion!

**Closed by polyfractal** 2019-04-15 18:01 UTC
Labels: :Analytics/Aggregations
