### ISSUE TITLE
QueryProfilerIT.testNoProfile failure

### ISSUE THREAD

**Issue by abeyad** [elastic/elasticsearch#16318] opened 2016-01-29 16:07 UTC
Failed once:
http://build-us-00.elastic.co/job/es_core_master_strong/6362/testReport/junit/org.elasticsearch.search.profile/QueryProfilerIT/testNoProfile/
http://build-us-00.elastic.co/job/es_core_master_strong/6362/testReport/junit/org.elasticsearch.search.profile/QueryProfilerIT/testNoProfile/

I was unable to reproduce it with:
```
gradle :core:integTest -Dtests.seed=FB14D25BF47858F1 -Dtests.class=org.elasticsearch.search.profile.QueryProfilerIT -Dtests.method="testNoProfile" -Des.logger.level=DEBUG -Dtests.security.manager=true -Dtests.nightly=false -Dtests.heap.size=512m -Dtests.jvm.argline="-server -XX:+UseParallelGC -XX:-UseCompressedOops" -Dtests.locale=ar-LB -Dtests.timezone=America/Argentina/ComodRivadavia
```

Error message:
```
Error Message

 Expected: an empty iterable      but: [<RemoteTransportException[[transport_client_node_s1][local[417]][indices:data/write/index]]; nested: RemoteTransportException[[node_s1][local[413]][indices:data/write/index[p]]]; nested: NotSerializableExceptionWrapper[Failed to acknowledge mapping update within [17s]];>,<RemoteTransportException[[transport_client_node_s0][local[419]][indices:data/write/index]]; nested: RemoteTransportException[[node_s0][local[412]][indices:data/write/index[p]]]; nested: NotSerializableExceptionWrapper[Failed to acknowledge mapping update within [30s]];>,<RemoteTransportException[[transport_client_node_s2][local[418]][indices:data/write/index]]; nested: RemoteTransportException[[node_s2][local[414]][indices:data/write/index]]; nested: RemoteTransportException[[node_s0][local[412]][indices:data/write/index[p]]]; nested: NotSerializableExceptionWrapper[Failed to acknowledge mapping update within [30s]];>,<RemoteTransportException[[transport_client_node_s2][local[418]][indices:data/write/index]]; nested: RemoteTransportException[[node_s2][local[414]][indices:data/write/index[p]]]; nested: NotSerializableExceptionWrapper[Failed to acknowledge mapping update within [29s]];>,<RemoteTransportException[[transport_client_node_s1][local[417]][indices:data/write/index]]; nested: RemoteTransportException[[node_s1][local[413]][indices:data/write/index]]; nested: RemoteTransportException[[node_s2][local[414]][indices:data/write/index[p]]]; nested: NotSerializableExceptionWrapper[Failed to acknowledge mapping update within [29s]];>,<RemoteTransportException[[transport_client_node_s1][local[417]][indices:data/write/index]]; nested: RemoteTransportException[[node_s1][local[413]][indices:data/write/index[p]]]; nested: NotSerializableExceptionWrapper[Failed to acknowledge mapping update within [17s]];>]
Stacktrace

java.lang.AssertionError: 
Expected: an empty iterable
     but: [<RemoteTransportException[[transport_client_node_s1][local[417]][indices:data/write/index]]; nested: RemoteTransportException[[node_s1][local[413]][indices:data/write/index[p]]]; nested: NotSerializableExceptionWrapper[Failed to acknowledge mapping update within [17s]];>,<RemoteTransportException[[transport_client_node_s0][local[419]][indices:data/write/index]]; nested: RemoteTransportException[[node_s0][local[412]][indices:data/write/index[p]]]; nested: NotSerializableExceptionWrapper[Failed to acknowledge mapping update within [30s]];>,<RemoteTransportException[[transport_client_node_s2][local[418]][indices:data/write/index]]; nested: RemoteTransportException[[node_s2][local[414]][indices:data/write/index]]; nested: RemoteTransportException[[node_s0][local[412]][indices:data/write/index[p]]]; nested: NotSerializableExceptionWrapper[Failed to acknowledge mapping update within [30s]];>,<RemoteTransportException[[transport_client_node_s2][local[418]][indices:data/write/index]]; nested: RemoteTransportException[[node_s2][local[414]][indices:data/write/index[p]]]; nested: NotSerializableExceptionWrapper[Failed to acknowledge mapping update within [29s]];>,<RemoteTransportException[[transport_client_node_s1][local[417]][indices:data/write/index]]; nested: RemoteTransportException[[node_s1][local[413]][indices:data/write/index]]; nested: RemoteTransportException[[node_s2][local[414]][indices:data/write/index[p]]]; nested: NotSerializableExceptionWrapper[Failed to acknowledge mapping update within [29s]];>,<RemoteTransportException[[transport_client_node_s1][local[417]][indices:data/write/index]]; nested: RemoteTransportException[[node_s1][local[413]][indices:data/write/index[p]]]; nested: NotSerializableExceptionWrapper[Failed to acknowledge mapping update within [17s]];>]
	at __randomizedtesting.SeedInfo.seed([FB14D25BF47858F1:F64D2836A28F927]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at org.elasticsearch.test.ESIntegTestCase.indexRandom(ESIntegTestCase.java:1433)
	at org.elasticsearch.test.ESIntegTestCase.indexRandom(ESIntegTestCase.java:1353)
	at org.elasticsearch.test.ESIntegTestCase.indexRandom(ESIntegTestCase.java:1337)
	at org.elasticsearch.test.ESIntegTestCase.indexRandom(ESIntegTestCase.java:1313)
	at org.elasticsearch.search.profile.QueryProfilerIT.testNoProfile(QueryProfilerIT.java:602)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1764)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:871)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:907)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:921)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:50)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:46)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:49)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:65)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:48)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:367)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:809)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:460)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:880)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:781)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:816)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:827)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:46)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:42)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:54)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:65)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:55)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:367)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by bleskes** [comment] 2016-01-31 19:10
I looked at this and the failure is caused by two nodes taking ~40s to process mapping updates from the master. They do not hang but rather just take to long to complete. The only thing that sticks out is that the cluster state update contains mapping for two types at once. I tried to simulated this using a count down latch in the MetaDataMappingService, causing batching of types but to no avail, it doesn't reproduce. I suggest we wait and see if this failures comes back and try to get more information.

**Comment by polyfractal** [comment] 2016-02-02 15:22
Sorry for the delay, been traveling + internet issues.  Thanks for looking into this @bleskes, I'll defer to your judgement and just sit on this for a while :)

**Comment by javanna** [comment] 2016-09-14 15:54
this failed once last January and never again. Shall we close while we see if it happens again? Also from the explanation above it seemed not directly related to profiling so maybe similar things have happened in other tests too... not sure. WDYT @bleskes ?

**Comment by bleskes** [comment] 2016-09-14 16:52
I’m good with closing.

**Closed** 2016-09-14 16:55 UTC
Labels: jenkins, test
