### ISSUE TITLE
HandledTransportAction executor value don't make effect in the http transport worker thread

### ISSUE THREAD

**Issue by weizijun** [elastic/elasticsearch#105047] opened 2024-02-02 07:59 UTC
### Description

The constructor of HandledTransportAction has an executor parameter, which takes effect in the tcp transport layer, but when called from the rest http layer, but the action called from the rest layer still uses the SAME thread.

When the TransportAction called from the rest layer, it will called NodeClient.executeLocally to execute action, which dont' switch thread. 

This will cause ambiguity for users, thinking that if the executor value is passed on the HandledTransportAction, the doExecute method can be executed on the custom executor.

But in fact, when a Rest request call this transport action, doExecute method will be executed on the same http transport worker thread.

**Comment by ldematte** [comment] 2024-02-02 13:28
Related to (and possibly duplicate of): https://github.com/elastic/elasticsearch/issues/97916

**Comment by ldematte** [comment] 2024-02-02 13:30
Hi @weizijun, thanks for opening this issue. 
It is a known problem that requires some non-trivial effort to be solved at its roots. We already have an issue to track work on it, so I'm going to close this one and refer back to the already opened one: https://github.com/elastic/elasticsearch/issues/97916

**Closed by ldematte** 2024-02-02 13:30 UTC
Labels: >enhancement, :Core/Infra/Core, Team:Core/Infra
