### ISSUE TITLE
Java High Level REST Client is slow than kibana very much

### ISSUE THREAD

**Issue by zzujustme** [elastic/elasticsearch#59301] opened 2020-07-09 12:57 UTC
es version:6.6.0

i search by kibana cost 600ms,but search by rest high level rest client cost 10s!

**Comment by dadoonet** [comment] 2020-07-09 12:59
Could you open a discussion on discuss.elastic.co and share the exact query you are running on Kibana and the exact code you are running using Java?

**Comment by nik9000** [comment] 2020-07-15 18:17
I'm going to close this issue because I can't reproduce it. It'd be great if you could attach reproduction steps, like `curl` for the REST request and a little java project for the HLRC request.

**Closed by nik9000** 2020-07-15 18:17 UTC
Labels: >bug, needs:triage
