### ISSUE TITLE
Disk space full, addition of  a new disk  and data folder path in elasticsearch.yml does not start ES

### ISSUE THREAD

**Issue by rahul-contentsphere** [elastic/elasticsearch#27101] opened 2017-10-24 18:55 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): 2.1.1

**Plugins installed**: [No] 

**JVM version** (`java -version`):  1.8.0_91

**OS version** (`uname -a` if on a Unix-like system): SLES 11 SP4 : Linux elastic-test 3.0.101-63-default #1 SMP Tue Jun 23 16:02:31 UTC 2015 (4b89d0c) x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
I have ElasticSearch up and running with data folder path in elasticsearch.yml (data.path) and suddenly the disk space goes out of memory, adding another disk and its path in elasticsearch.yml (data.path) does not help to start elasticsearch and it gives the error .
Second data folder path is detected by ES but it does not write data in second path which it should as disk one is out of space
**Steps to reproduce**:

 1. Specify data folder path in config/elasticsearch.yml (path.data: [/opt/drive1/data])
 2. Start ES
 3. Disk space goes out of memory
4. Stop ES
5. Add another disk and its path in config/elasticsearch.yml (path.data: [/opt/drive1/data, /opt/drive2/data]
6. Start ES

**Provide logs (if relevant)**:
.
.
.
[2017-10-24 20:19:57,626][TRACE][action.index             ] [Primus] primary shard [[cs][3]] is not yet active, scheduling a retry.
[2017-10-24 20:19:57,626][WARN ][cluster.action.shard     ] [Primus] [cs][1] received shard failed for [cs][1], node[a_Q5KKvDQT2oUCqyDBMbxw], [P], v[11022], s[INITIALIZING], a[id=LIct0GgNQo6lDit7L155tA], unassigned_info[[reason=ALLOCATION_FAILED], at[2017-10-24T14:49:57.607Z], details[failed recovery, failure IndexShardRecoveryException[failed to recovery from gateway]; nested: EngineCreationFailureException[failed to create engine]; nested: FileSystemException[/opt/drive1/data/elasticsearch/nodes/0/indices/cs/1/translog/translog.ckp -> /opt/drive1/data/elasticsearch/nodes/0/indices/cs/1/translog/translog-6588876475027150237.tlog: No space left on device]; ]], indexUUID [gS6I9WYIR6KgYT4BVxLcHQ], message [failed recovery], failure [IndexShardRecoveryException[failed to recovery from gateway]; nested: EngineCreationFailureException[failed to create engine]; nested: FileSystemException[/opt/drive1/data/elasticsearch/nodes/0/indices/cs/1/translog/translog.ckp -> /opt/drive1/data/elasticsearch/nodes/0/indices/cs/1/translog/translog-6047595504573155792.tlog: No space left on device]; ]
[cs][[cs][1]] IndexShardRecoveryException[failed to recovery from gateway]; nested: EngineCreationFailureException[failed to create engine]; nested: FileSystemException[/opt/drive1/data/elasticsearch/nodes/0/indices/cs/1/translog/translog.ckp -> /opt/drive1/data/elasticsearch/nodes/0/indices/cs/1/translog/translog-6047595504573155792.tlog: No space left on device];
        at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:254)
        at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56)
        at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: [cs][[cs][1]] EngineCreationFailureException[failed to create engine]; nested: FileSystemException[/opt/drive1/data/elasticsearch/nodes/0/indices/cs/1/translog/translog.ckp -> /opt/drive1/data/elasticsearch/nodes/0/indices/cs/1/translog/translog-6047595504573155792.tlog: No space left on device];
        at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:156)
        at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:25)
        at org.elasticsearch.index.shard.IndexShard.newEngine(IndexShard.java:1408)
        at org.elasticsearch.index.shard.IndexShard.createNewEngine(IndexShard.java:1403)
        at org.elasticsearch.index.shard.IndexShard.internalPerformTranslogRecovery(IndexShard.java:906)
        at org.elasticsearch.index.shard.IndexShard.performTranslogRecovery(IndexShard.java:883)
        at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:245)
        ... 5 more
Caused by: java.nio.file.FileSystemException: /opt/drive1/data/elasticsearch/nodes/0/indices/cs/1/translog/translog.ckp -> /opt/drive1/data/elasticsearch/nodes/0/indices/cs/1/translog/translog-6047595504573155792.tlog: No space left on device
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixCopyFile.copyFile(UnixCopyFile.java:253)
        at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:581)
        at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
        at java.nio.file.Files.copy(Files.java:1274)
        at org.elasticsearch.index.translog.Translog.recoverFromFiles(Translog.java:316)
        at org.elasticsearch.index.translog.Translog.<init>(Translog.java:169)
        at org.elasticsearch.index.engine.InternalEngine.openTranslog(InternalEngine.java:209)
        at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:152)
        ... 11 more

.
.
.

**Comment by dakrone** [comment] 2017-10-26 19:14
In ES' view we need space to do things like create new translogs, and in Lucene's view, it needs space so that it can perform things like commits and merging. Since a shard does not span multiple data paths, ES doesn't start up happy. You'll need to manually move shards to a different data path and start ES up.

**Comment by rahul-contentsphere** [comment] 2017-10-26 19:24
Dakrone, 
Thank you so much for your response.

**Comment by dakrone** [comment] 2017-10-26 19:31
You're welcome, I'm going to close this for now as it's not a bug. Thanks!

**Closed by dakrone** 2017-10-26 19:31 UTC
Labels: :Core
