### ISSUE TITLE
Rollup job creation fails if the index pattern contains a comma

### ISSUE THREAD

**Issue by cjcenizal** [elastic/elasticsearch#61396] opened 2020-08-20 22:15 UTC
To reproduce, execute these requests:

```
# Create one index with a document
PUT test_1
{
  "mappings": {
    "properties": {
      "date": {
        "type":   "date",
        "format": "yyyy-MM-dd"
      }
    }
  }
}
PUT test_1/_doc/1
{
  "date": "1983-05-27"
}

# Create a second index with a document
PUT test_2
{
  "mappings": {
    "properties": {
      "date": {
        "type":   "date",
        "format": "yyyy-MM-dd"
      }
    }
  }
}
PUT test_2/_doc/1
{
  "date": "1983-05-27"
}

# Create the job with an index pattern that refers to these two indices
PUT _rollup/job/test
{
  "id": "test",
  "index_pattern": "test_1,test_2",
  "rollup_index": "result",
  "cron": "0 0 0 ? * 7",
  "page_size": 1000,
  "groups": {
    "date_histogram": {
      "interval": "10s",
      "delay": "1d",
      "time_zone": "UTC",
      "field": "date"
    }
  }
}
```

The request to create the rollup job will fail with this error:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "index_not_found_exception",
        "reason" : "no such index [test_1,test_2]",
        "resource.type" : "index_or_alias",
        "resource.id" : "test_1,test_2",
        "index_uuid" : "_na_",
        "index" : "test_1,test_2"
      }
    ],
    "type" : "index_not_found_exception",
    "reason" : "no such index [test_1,test_2]",
    "resource.type" : "index_or_alias",
    "resource.id" : "test_1,test_2",
    "index_uuid" : "_na_",
    "index" : "test_1,test_2"
  },
  "status" : 404
}
```

**Comment by wchaparro** [comment] 2021-06-09 20:40
@csoulios Thoughts on this one?

**Comment by not-napoleon** [comment] 2021-06-09 21:02
Looks to be a duplicate of #45591, closing in favor of that one.

**Closed by not-napoleon** 2021-06-09 21:02 UTC
Labels: :Analytics/Rollup, >bug, Team:Analytics

**Comment by csoulios** [comment] 2021-06-10 12:50
It is a duplicate indeed. Thanks for spotting this.
