### ISSUE TITLE
Could not determine the dependencies of task ':x-pack:plugin:ml:bundlePlugin'.

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#48350] opened 2019-10-22 13:05 UTC
Build | 20191022130130-9031DBB2
Log | https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.5+default-distro+bwc/BWC_VERSION=7.3.2,nodes=centos-7&&immutable/18/console
Build Scans | https://gradle-enterprise.elastic.co/s/qqfzxiydtlxqy

Excerpt from logs:
```
13:02:30 * What went wrong:
13:02:30 Could not determine the dependencies of task ':x-pack:plugin:ml:bundlePlugin'.
13:02:30 > Could not resolve all files for configuration ':x-pack:plugin:ml:nativeBundle'.
13:02:30    > Could not resolve org.elasticsearch.ml:ml-cpp:7.5.0-SNAPSHOT.
13:02:30      Required by:
13:02:30          project :x-pack:plugin:ml
13:02:30       > Could not resolve org.elasticsearch.ml:ml-cpp:7.5.0-SNAPSHOT.
13:02:30          > Could not get resource 'https://prelert-artifacts.s3.amazonaws.com/maven/org/elasticsearch/ml/ml-cpp/7.5.0-SNAPSHOT/ml-cpp-7.5.0-SNAPSHOT.zip'.
13:02:30             > Could not HEAD 'https://prelert-artifacts.s3.amazonaws.com/maven/org/elasticsearch/ml/ml-cpp/7.5.0-SNAPSHOT/ml-cpp-7.5.0-SNAPSHOT.zip'.
13:02:30                > prelert-artifacts.s3.amazonaws.com: Name or service not known
```

**Comment by przemekwitek** [comment] 2019-10-22 13:07
Another instance:

Build | 20191022105558-98B254C7
Log | https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=centos-7&&immutable/339/console
Build Scans | https://gradle-enterprise.elastic.co/s/aaoeuwdguj3zk

Logs:
```
11:48:07  [7.4.1] FAILURE: Build failed with an exception.
11:48:07  [7.4.1] 
11:48:07  [7.4.1] * Where:
11:48:07  [7.4.1] Build file '/var/lib/jenkins/workspace/elastic+elasticsearch+7.x+multijob-unix-compatibility/os/centos-7&&immutable/distribution/bwc/bugfix/build/bwc/checkout-7.4/x-pack/plugin/ml/build.gradle' line: 41
11:48:07  [7.4.1] 
11:48:07  [7.4.1] * What went wrong:
11:48:07  [7.4.1] Could not determine the dependencies of task ':x-pack:plugin:ml:bundlePlugin'.
11:48:07  [7.4.1] > Could not resolve all files for configuration ':x-pack:plugin:ml:nativeBundle'.
11:48:07  [7.4.1]    > Could not resolve org.elasticsearch.ml:ml-cpp:7.4.1-SNAPSHOT.
11:48:07  [7.4.1]      Required by:
11:48:07  [7.4.1]          project :x-pack:plugin:ml
11:48:07  [7.4.1]       > Could not resolve org.elasticsearch.ml:ml-cpp:7.4.1-SNAPSHOT.
11:48:07  [7.4.1]          > Could not get resource 'https://prelert-artifacts.s3.amazonaws.com/maven/org/elasticsearch/ml/ml-cpp/7.4.1-SNAPSHOT/ml-cpp-7.4.1-SNAPSHOT.zip'.
11:48:07  [7.4.1]             > Could not HEAD 'https://prelert-artifacts.s3.amazonaws.com/maven/org/elasticsearch/ml/ml-cpp/7.4.1-SNAPSHOT/ml-cpp-7.4.1-SNAPSHOT.zip'.
11:48:07  [7.4.1]                > prelert-artifacts.s3.amazonaws.com: Name or service not known
11:48:07  [7.4.1] 
```

**Comment by przemekwitek** [comment] 2019-10-22 13:08
Another instance:


Build | 20191022115850-686BB302
Log | https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.5+multijob+fast+bwc/52/console
Build Scans | https://gradle-enterprise.elastic.co/s/qc7gihl7ue5tw

**Comment by droberts195** [comment] 2019-11-12 10:06
This was caused by a DNS problem in Google Cloud on the day these problems were seen.  There was a DDoS attack against Google Cloud and they stopped resolving certain domain names to mitigate it, including `s3.amazonaws.com`.

**Closed by droberts195** 2019-11-12 10:06 UTC
Labels: :ml, >test-failure
