### ISSUE TITLE
Snapshot error with minio trailing / in the base_path of the repository gives FileAlreadyExistsException for recursive snapshots of the same index

### ISSUE THREAD

**Issue by thasija** [elastic/elasticsearch#41814] opened 2019-05-04 00:48 UTC
**Elasticsearch version** (`5.6.11`):

**Plugins installed**: [repository-s3]

**JVM version** (`jdk1.8.0_77`):

**OS version** (`uname -a` 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux):

**Description of the problem including expected versus actual behavior**:
Am taking snapshots of indices on Minio server which are taken in a bucket , The successive snapshots of the same indices complete successfully when taken at the bucket root level , but if  I register a new repository with a base_path to take snapshots under sub directory the first snapshot gets created successfully but the successive snapshots fail with the FileAlreadyExistsException.

**Provide logs (if relevant)**:
# Parent root level bucket snapshot repository
curl -XGET "esi1rvmm03-inc.tw-test.net:9200/_snapshot/intc_minio_repository/_all?pretty"
{
  "snapshots" : [
    {
      "snapshot" : "usg_report_month_2018_09_snapshot",
      "uuid" : "b1cXPStzSA245j6rNABL8g",
      "version_id" : 5061199,
      "version" : "5.6.11",
      "indices" : [
        "usg_report_month_2018_09"
      ],
      "state" : "SUCCESS",
      "start_time" : "2019-04-15T01:57:54.293Z",
      "start_time_in_millis" : 1555293474293,
      "end_time" : "2019-04-15T01:57:57.365Z",
      "end_time_in_millis" : 1555293477365,
      "duration_in_millis" : 3072,
      "failures" : [ ],
      "shards" : {
        "total" : 1,
        "failed" : 0,
        "successful" : 1
      }
    },
    {
      "snapshot" : "snapshot_1",
      "uuid" : "EsSYscL_REK7KVORsYrWuQ",
      "version_id" : 5061199,
      "version" : "5.6.11",
      "indices" : [
        "doclocker"
      ],
      "state" : "SUCCESS",
      "start_time" : "2019-05-02T22:35:02.206Z",
      "start_time_in_millis" : 1556836502206,
      "end_time" : "2019-05-02T22:35:13.609Z",
      "end_time_in_millis" : 1556836513609,
      "duration_in_millis" : 11403,
      "failures" : [ ],
      "shards" : {
        "total" : 5,
        "failed" : 0,
        "successful" : 5
      }
    },
    {
      "snapshot" : "snapshot_2",
      "uuid" : "vWpuP64ET5KBGuWJ4PmP2w",
      "version_id" : 5061199,
      "version" : "5.6.11",
      "indices" : [
        "doclocker"
      ],
      "state" : "SUCCESS",
      "start_time" : "2019-05-02T22:39:10.484Z",
      "start_time_in_millis" : 1556836750484,
      "end_time" : "2019-05-02T22:39:11.230Z",
      "end_time_in_millis" : 1556836751230,
      "duration_in_millis" : 746,
      "failures" : [ ],
      "shards" : {
        "total" : 5,
        "failed" : 0,
        "successful" : 5
      }

# Nested directory snapshot repository
curl -XGET "esi1rvmm03-inc.tw-test.net:9200/_snapshot/intc_minio_repository_doclocker/_all?pretty"
{
  "snapshots" : [
    {
      "snapshot" : "snapshot_1",
      "uuid" : "c_VRGCCdSSKLr-i0PTXLZg",
      "version_id" : 5061199,
      "version" : "5.6.11",
      "indices" : [
        "doclocker"
      ],
      "state" : "SUCCESS",
      "start_time" : "2019-05-03T19:33:20.166Z",
      "start_time_in_millis" : 1556912000166,
      "end_time" : "2019-05-03T19:33:28.478Z",
      "end_time_in_millis" : 1556912008478,
      "duration_in_millis" : 8312,
      "failures" : [ ],
      "shards" : {
        "total" : 5,
        "failed" : 0,
        "successful" : 5
      }
    },
    {
      "snapshot" : "snapshot_2",
      "uuid" : "wQD5j389QK2nHMoNKDCIwA",
      "version_id" : 5061199,
      "version" : "5.6.11",
      "indices" : [
        "doclocker"
      ],
      "state" : "PARTIAL",
      "start_time" : "2019-05-03T19:35:59.364Z",
      "start_time_in_millis" : 1556912159364,
      "end_time" : "2019-05-03T19:35:59.627Z",
      "end_time_in_millis" : 1556912159627,
      "duration_in_millis" : 263,
      "failures" : [
        {
          "index" : "doclocker",
          "index_uuid" : "doclocker",
          "shard_id" : 0,
          "reason" : "IndexShardSnapshotFailedException[Failed to perform snapshot (index files)]; nested: FileAlreadyExistsException[blob [__0] already exists, cannot overwrite]; ",
          "node_id" : "9XnkBOa5Q3mUiHp1WvY5hQ",
          "status" : "INTERNAL_SERVER_ERROR"
        },
        {
          "index" : "doclocker",
          "index_uuid" : "doclocker",
          "shard_id" : 2,
          "reason" : "IndexShardSnapshotFailedException[Failed to perform snapshot (index files)]; nested: FileAlreadyExistsException[blob [__0] already exists, cannot overwrite]; ",
          "node_id" : "cw3A2lK5SAOw1qQ2CY3sTw",
          "status" : "INTERNAL_SERVER_ERROR"
        },
        {
          "index" : "doclocker",
          "index_uuid" : "doclocker",
          "shard_id" : 4,
          "reason" : "IndexShardSnapshotFailedException[Failed to perform snapshot (index files)]; nested: FileAlreadyExistsException[blob [__0] already exists, cannot overwrite]; ",
          "node_id" : "cw3A2lK5SAOw1qQ2CY3sTw",
          "status" : "INTERNAL_SERVER_ERROR"
        },
        {
          "index" : "doclocker",
          "index_uuid" : "doclocker",
          "shard_id" : 1,
          "reason" : "IndexShardSnapshotFailedException[Failed to perform snapshot (index files)]; nested: FileAlreadyExistsException[blob [__0] already exists, cannot overwrite]; ",
          "node_id" : "9XnkBOa5Q3mUiHp1WvY5hQ",
          "status" : "INTERNAL_SERVER_ERROR"
        },
        {
          "index" : "doclocker",
          "index_uuid" : "doclocker",
          "shard_id" : 3,
          "reason" : "IndexShardSnapshotFailedException[Failed to perform snapshot (index files)]; nested: FileAlreadyExistsException[blob [__0] already exists, cannot overwrite]; ",
          "node_id" : "9XnkBOa5Q3mUiHp1WvY5hQ",
          "status" : "INTERNAL_SERVER_ERROR"
        }
      ],
      "shards" : {
        "total" : 5,
        "failed" : 5,
        "successful" : 0
      }
    }

**Comment by DaveCTurner** [comment] 2019-05-04 16:45
Hi @thasija,

Please note that the 5.6 series has reached the [end of its supported life](https://www.elastic.co/support/eol). Nonetheless, I tried and failed to reproduce the problem you describe against a brand-new one-node 5.6.16 cluster:

```
PUT /_snapshot/my_s3_repository
{
  "settings": {
    "base_path": "test_base_path",
    "bucket": "bucketname",
    "endpoint": "127.0.0.1:9000"
  },
  "type": "s3"
}

PUT /i
{
  "settings": {
    "number_of_shards": 1
  }
}

POST /i/doc
{}

POST /i/_flush

PUT /_snapshot/my_s3_repository/snapshot_1?wait_for_completion=true

POST /i/doc
{}

POST /i/_flush

PUT /_snapshot/my_s3_repository/snapshot_2?wait_for_completion=true

```

This last command reported:

```
# 200 OK
# {
#   "snapshot": {
#     "snapshot": "snapshot_2",
#     "duration_in_millis": 75,
#     "state": "SUCCESS",
#     "uuid": "4U7W9roOQHeCuxXOZwWeog",
#     "failures": [],
#     "end_time_in_millis": 1556988029412,
#     "indices": [
#       "i"
#     ],
#     "shards": {
#       "successful": 1,
#       "total": 1,
#       "failed": 0
#     },
#     "version": "5.6.16",
#     "start_time": "2019-05-04T16:40:29.337Z",
#     "end_time": "2019-05-04T16:40:29.412Z",
#     "version_id": 5061699,
#     "start_time_in_millis": 1556988029337
#   }
# }
```

Could you try again with a supported version (ideally 6.7.2 or 7.0.1) and give a more detailed sequence of steps to help us reproduce what you're seeing?

**Comment by thasija** [comment] 2019-05-04 17:54
Hi @DaveCTurner 
The steps to reproduce the issue are the same you have done, In my Minio bucket base path directory  I see an indices directory getting created that has blobs for the individual shards , These blobs are what are causing FileAlreadyException. Can you check if your test_base_path has the indices directory.

[minio@devchi-inf-012 ~]$ /opt/minio/bin/mc ls myminio/elasticsearch-esp3-intc/doclocker/indices/ju4twZSTSCaMGA9-O04qtw/
[2019-05-03 23:07:05 CDT] 3.1KiB meta-4g8_EJ8ESfekUOI9xAkCsQ.dat
[2019-05-03 23:05:47 CDT] 3.1KiB meta-Dmyo1S6nQ1-20-7wlFDl8g.dat
[2019-05-04 12:53:39 CDT]     0B 0/
[2019-05-04 12:53:39 CDT]     0B 1/
[2019-05-04 12:53:39 CDT]     0B 2/
[2019-05-04 12:53:39 CDT]     0B 3/
[2019-05-04 12:53:39 CDT]     0B 4/

**Comment by DaveCTurner** [comment] 2019-05-04 18:06
Yep, that's what I'd expect it to look like:


```
$ find minio/bucketname | sort
minio/bucketname
minio/bucketname/test_base_path
minio/bucketname/test_base_path/incompatible-snapshots
minio/bucketname/test_base_path/index-0
minio/bucketname/test_base_path/index-1
minio/bucketname/test_base_path/index.latest
minio/bucketname/test_base_path/indices
minio/bucketname/test_base_path/indices/_P-iWqjYSoOaUcOw6YWH-A
minio/bucketname/test_base_path/indices/_P-iWqjYSoOaUcOw6YWH-A/0
minio/bucketname/test_base_path/indices/_P-iWqjYSoOaUcOw6YWH-A/0/__0
minio/bucketname/test_base_path/indices/_P-iWqjYSoOaUcOw6YWH-A/0/__1
minio/bucketname/test_base_path/indices/_P-iWqjYSoOaUcOw6YWH-A/0/__2
minio/bucketname/test_base_path/indices/_P-iWqjYSoOaUcOw6YWH-A/0/__3
minio/bucketname/test_base_path/indices/_P-iWqjYSoOaUcOw6YWH-A/0/__4
minio/bucketname/test_base_path/indices/_P-iWqjYSoOaUcOw6YWH-A/0/__5
minio/bucketname/test_base_path/indices/_P-iWqjYSoOaUcOw6YWH-A/0/__6
minio/bucketname/test_base_path/indices/_P-iWqjYSoOaUcOw6YWH-A/0/__7
minio/bucketname/test_base_path/indices/_P-iWqjYSoOaUcOw6YWH-A/0/index-1
minio/bucketname/test_base_path/indices/_P-iWqjYSoOaUcOw6YWH-A/0/snap-HXt1s7GDQpqH3FAqF9IFWQ.dat
minio/bucketname/test_base_path/indices/_P-iWqjYSoOaUcOw6YWH-A/0/snap-egP5oQSwTuG8V2xhbLnJtw.dat
minio/bucketname/test_base_path/indices/_P-iWqjYSoOaUcOw6YWH-A/meta-HXt1s7GDQpqH3FAqF9IFWQ.dat
minio/bucketname/test_base_path/indices/_P-iWqjYSoOaUcOw6YWH-A/meta-egP5oQSwTuG8V2xhbLnJtw.dat
minio/bucketname/test_base_path/meta-HXt1s7GDQpqH3FAqF9IFWQ.dat
minio/bucketname/test_base_path/meta-egP5oQSwTuG8V2xhbLnJtw.dat
minio/bucketname/test_base_path/snap-HXt1s7GDQpqH3FAqF9IFWQ.dat
minio/bucketname/test_base_path/snap-egP5oQSwTuG8V2xhbLnJtw.dat
```

I'm using a recent version:

```
$ minio version
Version: 2019-05-02T19:07:09Z
Release-Tag: RELEASE.2019-05-02T19-07-09Z
Commit-ID: 4b858b562a0887e10bfd0414dc87e68f1af31c3a
```

**Comment by original-brownbear** [comment] 2019-05-04 18:11
@thasija do you actually have two repositories configured at the same time (one at the root and one nested?) or did you remove the root repo before creating the nested one?

**Comment by thasija** [comment] 2019-05-04 18:21
Hi @original-brownbear  yes I had the root level repository as well but later I deleted the root level repository and deleted all the files from the bucket , should I try fresh with a new bucket that doesn't has the root level repository ?

curl -X GET "esi1rvmm03-inc.tw-test.net:9200/_snapshot/?pretty"
{
  "intc_minio_repository_doclocker" : {
    "type" : "s3",
    "settings" : {
      "bucket" : "elasticsearch-esp3-intc",
      "base_path" : "doclocker/",
      "endpoint" : "http://10.70.255.229:9000",
      "protocol" : "http"
    }
  }

**Comment by original-brownbear** [comment] 2019-05-04 18:25
@thasija if possible try restarting your cluster fully to get a settings reload for the S3 client first and see if the nested path repo works. If it doesn't yea try a clean repo like @DaveCTurner suggested.

**Comment by thasija** [comment] 2019-05-04 19:06
I restarted the cluster and tried with a fresh new bucket in the same minio server but the issue happens again.

  "intc_minio_repository_doclocker_new" : {
    "type" : "s3",
    "settings" : {
      "bucket" : "elasticsearch-esp3-intc-new",
      "base_path" : "doclocker/",
      "endpoint" : "http://10.70.255.229:9000",
      "protocol" : "http"
    }
  }
}



{
  "snapshots" : [
    {
      "snapshot" : "snapshot_1",
      "uuid" : "Yt--Z2xYQ12xFYezre71lQ",
      "version_id" : 5061199,
      "version" : "5.6.11",
      "indices" : [
        "usg_report_month_2018_09"
      ],
      "state" : "SUCCESS",
      "start_time" : "2019-05-04T18:59:59.437Z",
      "start_time_in_millis" : 1556996399437,
      "end_time" : "2019-05-04T19:00:01.196Z",
      "end_time_in_millis" : 1556996401196,
      "duration_in_millis" : 1759,
      "failures" : [ ],
      "shards" : {
        "total" : 1,
        "failed" : 0,
        "successful" : 1
      }
    },
    {
      "snapshot" : "snapshot_2",
      "uuid" : "vM_AGQrRQkCZn3F8VtDqAQ",
      "version_id" : 5061199,
      "version" : "5.6.11",
      "indices" : [
        "usg_report_month_2018_09"
      ],
      "state" : "PARTIAL",
      "start_time" : "2019-05-04T19:01:25.437Z",
      "start_time_in_millis" : 1556996485437,
      "end_time" : "2019-05-04T19:01:26.004Z",
      "end_time_in_millis" : 1556996486004,
      "duration_in_millis" : 567,
      "failures" : [
        {
          "index" : "usg_report_month_2018_09",
          "index_uuid" : "usg_report_month_2018_09",
          "shard_id" : 0,
          "reason" : "IndexShardSnapshotFailedException[Failed to perform snapshot (index files)]; nested: FileAlreadyExistsException[blob [__0] already exists, cannot overwrite]; ",
          "node_id" : "9XnkBOa5Q3mUiHp1WvY5hQ",
          "status" : "INTERNAL_SERVER_ERROR"
        }
      ],
      "shards" : {
        "total" : 1,
        "failed" : 1,
        "successful" : 0
      }
    }
  ]
}

**Comment by original-brownbear** [comment] 2019-05-04 19:27
@thasija Could you try a newer version of ES with your repository like David suggested?

Also, it might be worth testing with `base_path` set to `doclocker` without the trailing `/` as that is the only difference I can really see in the steps you took and those taken by David.

**Comment by thasija** [comment] 2019-05-04 20:20
Thanks @original-brownbear  that helped to solve the issue , I created a new bucket and registered a new repository with the base path not having the trailing / , the successive snapshots worked this time and didn't gave any errors , Thanks @DaveCTurner

**Comment by original-brownbear** [comment] 2019-05-04 20:27
Interesting, seems we're sometimes stripping the trailing `/` and sometimes not in `BlobPath` so every path that ends in a `/` breaks for a few situations. I think we should fix this!

Could you add the conclusion that a trailing `/` in the base_path breaks the S3 repository to the issue description and adjust the title of the issue accordingly please? :)

**Comment by thasija** [comment] 2019-05-04 20:34
Updated the title

**Comment by thasija** [comment] 2019-05-04 23:06
@original-brownbear @DaveCTurner 
just noticed a different behavior on AWS S3 , On registering a AWS S3 repository with the trailing slash at the base path the issue doesn't happen. It happens with a minio bucket repository with a trailing slash at the base path.

`curl -X GET "esi1rvmm03-inc.tw-test.net:9200/_snapshot/s3_repository/?pretty"
{
  "s3_repository" : {
    "type" : "s3",
    "settings" : {
      "bucket" : "elasticsearch-esp3-intc",
      "base_path" : "doclocker/",
      "endpoint" : "s3.amazonaws.com",
      "protocol" : "http",
      "region" : "us-east"
    }
  }
}`

`curl -X GET "esi1rvmm03-inc.tw-test.net:9200/_snapshot/s3_repository/_all?verbose=false&pretty"
{
  "snapshots" : [
    {
      "snapshot" : "snapshot_1",
      "uuid" : "2V5fbdn4ShKsFe4nz563kA",
      "indices" : [
        "doclocker"
      ],
      "state" : "SUCCESS"
    },
    {
      "snapshot" : "snapshot_2",
      "uuid" : "8ZqwHDliQWyC6Eohx4-AIw",
      "indices" : [
        "doclocker"
      ],
      "state" : "SUCCESS"
    }
  ]
}`

**Comment by original-brownbear** [comment] 2019-05-05 06:07
@thasija ah thanks for pointing that out! I guess that's something to report to Minio itself technically. Regardless though, we're simply sending/using messy paths containing `//` and should just fix that as it may affect other blob stores as well and as we could see do so in a relatively unexpected way:)

**Comment by DaveCTurner** [comment] 2019-05-05 06:44
Well spotted @original-brownbear. The behaviour is different in 7.0, failing to even verify such a repository:

```
PUT /_snapshot/my_s3_repository
{
  "settings": {
    "base_path": "test_base_path/",
    "bucket": "bucketname",
    "endpoint": "127.0.0.1:9000"
  },
  "type": "s3"
}

# 500 Internal Server Error
# {
#   "status": 500,
#   "error": {
#     "caused_by": {
#       "caused_by": {
#         "reason": "The request signature we calculated does not match the signature you provided. Check your key and signing method. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: 159BB60A2E04BD08; S3 Extended Request ID: e1dec50c-ccbb-4d8b-8bcb-3ac127628605)",
#         "type": "amazon_s3_exception"
#       },
#       "reason": "Unable to upload object [test_base_path//tests-l-gAaacJQdit9_S-lvdmNQ/master.dat] using a single upload",
#       "type": "i_o_exception"
#     },
#     "reason": "[my_s3_repository] path [test_base_path/] is not accessible on master node",
#     "root_cause": [
#       {
#         "reason": "[my_s3_repository] path [test_base_path/] is not accessible on master node",
#         "type": "repository_verification_exception"
#       }
#     ],
#     "type": "repository_verification_exception"
#   }
# }

[2019-05-05T08:37:34,029][WARN ][r.suppressed             ] [node-0] path: /_snapshot/my_s3_repository, params: {repository=my_s3_repository}
org.elasticsearch.repositories.RepositoryVerificationException: [my_s3_repository] path [test_base_path/] is not accessible on master node
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:638) ~[elasticsearch-7.0.0.jar:7.0.0]
        at org.elasticsearch.repositories.RepositoriesService.lambda$verifyRepository$2(RepositoriesService.java:229) ~[elasticsearch-7.0.0.jar:7.0.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681) [elasticsearch-7.0.0.jar:7.0.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.io.IOException: Unable to upload object [test_base_path//tests-l-gAaacJQdit9_S-lvdmNQ/master.dat] using a single upload
        at org.elasticsearch.repositories.s3.S3BlobContainer.executeSingleUpload(S3BlobContainer.java:204) ~[?:?]
        at org.elasticsearch.repositories.s3.S3BlobContainer.lambda$writeBlob$2(S3BlobContainer.java:100) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_144]
        at org.elasticsearch.repositories.s3.SocketAccess.doPrivilegedIOException(SocketAccess.java:48) ~[?:?]
        at org.elasticsearch.repositories.s3.S3BlobContainer.writeBlob(S3BlobContainer.java:98) ~[?:?]
        at org.elasticsearch.repositories.s3.S3BlobContainer.writeBlobAtomic(S3BlobContainer.java:110) ~[?:?]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:633) ~[elasticsearch-7.0.0.jar:7.0.0]
        ... 5 more
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The request signature we calculated does not match the signature you provided. Check your key and signing method. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: 159BB60A2E04BD08; S3 Extended Request ID: e1dec50c-ccbb-4d8b-8bcb-3ac127628605)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1658) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1322) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1072) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:745) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:719) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:701) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:669) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:651) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:515) ~[?:?]
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4443) ~[?:?]
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4390) ~[?:?]
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1774) ~[?:?]
        at org.elasticsearch.repositories.s3.S3BlobContainer.lambda$executeSingleUpload$7(S3BlobContainer.java:201) ~[?:?]
        at org.elasticsearch.repositories.s3.SocketAccess.lambda$doPrivilegedVoid$0(SocketAccess.java:57) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_144]
        at org.elasticsearch.repositories.s3.SocketAccess.doPrivilegedVoid(SocketAccess.java:56) ~[?:?]
        at org.elasticsearch.repositories.s3.S3BlobContainer.executeSingleUpload(S3BlobContainer.java:200) ~[?:?]
        at org.elasticsearch.repositories.s3.S3BlobContainer.lambda$writeBlob$2(S3BlobContainer.java:100) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_144]
        at org.elasticsearch.repositories.s3.SocketAccess.doPrivilegedIOException(SocketAccess.java:48) ~[?:?]
        at org.elasticsearch.repositories.s3.S3BlobContainer.writeBlob(S3BlobContainer.java:98) ~[?:?]
        at org.elasticsearch.repositories.s3.S3BlobContainer.writeBlobAtomic(S3BlobContainer.java:110) ~[?:?]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:633) ~[elasticsearch-7.0.0.jar:7.0.0]
        ... 5 more
```

I suspect that there's been some change to the way that paths with trailing slashes are normalised in a newer SDK which isn't being respected by Minio. Regardless, I think we can reasonably strip extraneous directory separators from `base_path`; we should look at what happens with `/leading_ones` and `repeated//ones` too.

**Comment by DaveCTurner** [comment] 2019-05-05 06:48
If it turns out that the behaviour is different between Minio and S3 then it'd be good report an issue against Minio. I don't have a S3 bucket handy to try it out right now.

**Comment by original-brownbear** [comment] 2019-05-05 12:19
@DaveCTurner turns out the behavior difference is known to Minio: https://github.com/minio/minio/issues/5874#issuecomment-385764617

We should really just fix our code to remove all leading and trailing `/` and clean up double `//` in `BlobPath` (just like nio's `Path` would) to get predictable behavior across blob stores.

**Comment by original-brownbear** [comment] 2019-09-20 14:40
Closing this as there's not easy way to restrict path names in a BwC manner and generally limited usefulness of a fix here. See discussion in https://github.com/elastic/elasticsearch/pull/46869 for details.

**Closed by original-brownbear** 2019-09-20 14:40 UTC
Labels: :Distributed/Snapshot/Restore, >bug
