### ISSUE TITLE
Re-creation of transform creates multiple documents

### ISSUE THREAD

**Issue by adityaarun** [elastic/elasticsearch#45954] opened 2019-08-26 05:34 UTC
**Describe the feature**:

In the current dataframes implementation, the only way to update the dataframe job is to re-create the job. 
When we do that and run the job pointing it to the already existing index (for the job which was deleted) the job creates new documents for the already processed data with the exact same entries in the index.

If there was a way to handle this (e.g. by defining the document id generation), this would enable us to edit and modify dataframe job definitions.

Also this would prevent multiple entries for already processed documents.

**Elasticsearch version** (`bin/elasticsearch --version`): 7.3.0

**Plugins installed**: []

**JVM version** (`java -version`): OpenJDK 1.8.0_222

**OS version** (`uname -a` if on a Unix-like system): Ubuntu 18.04

**Comment by benwtrent** [comment] 2019-08-26 13:23
@adityaarun 

The ability to update transforms is being added in v7.4.0, but that will not be able to update the aggregations, or the groupings. If the `pivot` definition is updated, then completely different data is being generated which probably requires a different index mapping. Since dataframe transforms only creates the destination index mapping if it does not already exist, the new data may not be mapped correctly, and even cause field mapping conflicts (e.g. a field that was number is now a string). 

---------------------------------------------------------------
> If there was a way to handle this (e.g. by defining the document id generation), this would enable us to edit and modify dataframe job definitions.

Transforms generate each document ID by the results of the `group_by` fields. See: https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/IDGenerator.java

If the fields in the `group_by` are the same, the document IDs should be the same. 

--------------------------------------------------------------
If you have created the mappings for the destination index yourself, and are sure of all the data types, etc. and still want to generate your own document IDs, you can do so with a [ingest pipeline](https://www.elastic.co/guide/en/elasticsearch/reference/master/pipeline.html). You can then specify the `pipeline` field in the `dest` object in the transform. I would caution against generating the document IDs yourself. The IDs will have to be generated given by the output data, and if you are changing that data (via the transforms definition), the IDs generated will change.

**Comment by hendrikmuhs** [comment] 2020-01-24 10:20
I have concerns regarding adding something like this. Document ID generation is important for updating transforms, e.g. in continuous mode. More important is the resiliency aspect, the document ID generation is a hard requirement for fail-over cases.

As @benwtrent pointed out already: pipelines give you flexibility and you can do all kinds of (unsupported) stuff. You should be able to tweak transforms the way you like it matching your usecase.

However, adding an _official_ feature to tweak document ID's is for me not in scope. I therefore suggest to close this 'by design'.

**Comment by hendrikmuhs** [comment] 2020-01-30 10:29
@adityaarun 

We discussed this again. As already pointed out you can change the document id using an ingest pipeline. However, we will not add direct support for it as it breaks resiliency and continuous execution.

**Closed by hendrikmuhs** 2020-01-30 10:29 UTC
Labels: :ml, :ml/Transform, team-discuss, v7.3.0
