### ISSUE TITLE
GET a specific document in Sense with a request body overwrites it

### ISSUE THREAD

**Issue by sebnmuller** [elastic/elasticsearch#27140] opened 2017-10-27 08:51 UTC
**Elasticsearch version**:
Version: 5.6.2, Build: 57e20f3/2017-09-23T13:16:45.703Z, JVM: 1.8.0_144

**Plugins installed**: []

**JVM version**:
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

**OS version**:
MacOS Sierra 10.12.6

**Description of the problem including expected versus actual behavior**:
I came upon this accidentally. When getting a document in **Sense** i.e. GET index/type/id with a script_fields object in the request payload, the original document is overwritten **entirely** with the raw value of the script_fields content.

I didn't expect that getting a document could update and overwrite the document itself.

This only seems to happen when performing operations in Sense. Running the same Get with a payload using **curl** does **not** overwrite the document.

**Steps to reproduce**:

In sense:

 1. Create a test document

```
PUT /test/test/1
{"field1":"value1", "field2": "value2"}
```

 2. Confirm doc exists and contains expected content

```
GET /test/test/1
```

 3. GET doc with script_field in request

```
GET /test/test/1
{
  "script_fields": {
    "test": {
      "script": "doc[\"message\"]"
    }
  }
}
```

4. Confirm doc's entire content's overwritten with `"doc['message']"`

```
GET /test/test/1
```

![image](https://user-images.githubusercontent.com/3919957/32104333-3d839234-bb24-11e7-876d-b440ba4aaa72.png)

**Comment by danielmitterdorfer** [comment] 2017-10-27 11:31
Thanks for your report and the great reproduction scenario.

I could reproduce it also on 5.6.3 (most recent 5.x release). 6.0.0-rc1 and also the master version of Elasticsearch work fine.

The problem is that you send a GET request with a body (note that [script fields needs to be specified against the `_search` endpoint](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/search-request-script-fields.html)). 

I've debugged it and the problem is that the request method gets changed to POST by the time it reaches the `RestController` in Elasticsearch. It then (correctly) chooses `RestIndexAction` and the document gets updated. So the root cause is that the GET request method is changed to POST.

**Comment by danielmitterdorfer** [comment] 2017-10-27 12:26
> I could reproduce it also on 5.6.3

Scratch that. I have been fooled by [Sense](https://github.com/elastic/sense) which seems to be smart and changes the HTTP method to POST when a body is present. If I try this scenario with curl against a fresh install Elasticsearch (I've now tried 5.6.2 or 5.6.3), I get the expected behavior (i.e. the document is *not* changed).

Did you - by chance - also use a GUI tool instead of curl before? Can you please retry with curl?

**Comment by sebnmuller** [comment] 2017-10-27 12:28
I actually only used Sense and just copied the curl equivalents here. I'll try again with Sense and directly with curl too to verify.

**Comment by sebnmuller** [comment] 2017-10-27 12:34
You're right, with curl all is well. It's when using sense that the GET with a payload updates the document. I'll update the issue with correct details.

**Comment by danielmitterdorfer** [comment] 2017-10-27 12:40
> I actually only used Sense and just copied the curl equivalents here

No worries. I made the same mistake. :)

I think then it's an issue with Sense instead of Elasticsearch. Also, Sense not maintained anymore (although personally I also find it handy to have a standalone tool to work with) so I think it makes sense to close this issue.

**Closed by danielmitterdorfer** 2017-10-27 12:40 UTC
Labels: feedback_needed

**Comment by sebnmuller** [comment] 2017-10-27 16:18
Well, it was in the current incarnation of sense, so developer's tools in the current Kibana. Sorry for the confusion.

**Comment by danielmitterdorfer** [comment] 2017-10-27 17:44
No worries. :) In that case, would you please [open an issue there](https://github.com/elastic/kibana/issues)?

**Comment by jasimsulaiman** [comment] 2020-03-10 09:14
For reference, this issue is fixed in https://github.com/elastic/kibana/pull/46200
