### ISSUE TITLE
[CI] TransportMonitoringMigrateAlertsActionTests.testLocalAlertsRemoval

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#66586] opened 2020-12-18 11:14 UTC
Encountered on a PR build https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-2/15205/ (multiple tests failing `testLocalExporterWithAlertingDisabled`, `testLocalAlertsRemoval` and `testDisabledLocalExporterAlertsRemoval`

**Build scan**:
https://gradle-enterprise.elastic.co/s/or4i6aw2kxx6u

**Repro line**:
```
./gradlew ':x-pack:plugin:monitoring:test' --tests "org.elasticsearch.xpack.monitoring.action.TransportMonitoringMigrateAlertsActionTests.testLocalExporterWithAlertingDisabled" -Dtests.seed=74901503919A9EEE -Dtests.security.manager=true -Dtests.locale=el-GR -Dtests.timezone=Pacific/Pitcairn -Druntime.java=8
```

**Reproduces locally?**: No

**Applicable branches**: 7.11

**Failure history**:
https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.tags=CI&search.timeZoneId=America/Los_Angeles&tests.container=org.elasticsearch.xpack.monitoring.action.TransportMonitoringMigrateAlertsActionTests&tests.sortField=FAILED&tests.test=testLocalAlertsRemoval&tests.unstableOnly=true

**Failure excerpt**:
```
Expected: is <true>
     but: was <false>
	at __randomizedtesting.SeedInfo.seed([74901503919A9EEE:45FE8D342B81AB19]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.monitoring.test.MonitoringIntegTestCase.assertIndicesExists(MonitoringIntegTestCase.java:209)
	at org.elasticsearch.xpack.monitoring.test.MonitoringIntegTestCase.lambda$awaitIndexExists$3(MonitoringIntegTestCase.java:204)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1016)
	at org.elasticsearch.xpack.monitoring.test.MonitoringIntegTestCase.awaitIndexExists(MonitoringIntegTestCase.java:204)
	at org.elasticsearch.xpack.monitoring.action.TransportMonitoringMigrateAlertsActionTests.waitForWatcherIndices(TransportMonitoringMigrateAlertsActionTests.java:592)
	at org.elasticsearch.xpack.monitoring.action.TransportMonitoringMigrateAlertsActionTests.ensureInitialLocalResources(TransportMonitoringMigrateAlertsActionTests.java:473)
	at org.elasticsearch.xpack.monitoring.action.TransportMonitoringMigrateAlertsActionTests.testLocalAlertsRemoval(TransportMonitoringMigrateAlertsActionTests.java:139)
```

**Comment by gwbrown** [comment] 2020-12-18 18:39
These have been failing more recently on `master`, `7.x`, and `7.11` so I'm going to mute these pending a fix.

Some possibly-relevant logs from the failures:
```
[2020-12-18T08:15:12,687][ERROR][o.e.x.c.t.IndexTemplateRegistry] [node_s1] error adding index template [.watch-history-14] from [/watch-history.json] for [watcher]	
java.lang.IllegalArgumentException: composable template [.watch-history-14] template after composition is invalid	
	at org.elasticsearch.cluster.metadata.MetadataIndexTemplateService.addIndexTemplateV2(MetadataIndexTemplateService.java:504) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]	
	at org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$4.execute(MetadataIndexTemplateService.java:399) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]	
	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:59) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]	
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:697) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]	
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:319) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]	
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:214) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]	
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:151) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]	
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]	
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]	
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:680) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]	
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]	
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]	
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]	
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]	
	at java.lang.Thread.run(Thread.java:834) [?:?]	
Caused by: org.elasticsearch.common.xcontent.XContentParseException: [index_template] unknown field [data_stream]	
	at org.elasticsearch.cluster.metadata.MetadataIndexTemplateService.lambda$validateCompositeTemplate$21(MetadataIndexTemplateService.java:1133) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]	
	at org.elasticsearch.indices.IndicesService.withTempIndexService(IndicesService.java:638) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]	
	at org.elasticsearch.cluster.metadata.MetadataIndexTemplateService.validateCompositeTemplate(MetadataIndexTemplateService.java:1113) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]	
	at org.elasticsearch.cluster.metadata.MetadataIndexTemplateService.addIndexTemplateV2(MetadataIndexTemplateService.java:500) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]	
	... 14 more	
[2020-12-18T08:15:12,690][ERROR][o.e.x.c.t.IndexTemplateRegistry] [node_s1] error adding index template [.slm-history] from [/slm-history.json] for [index_lifecycle]	
java.lang.IllegalArgumentException: composable template [.slm-history] template after composition is invalid	
	at org.elasticsearch.cluster.metadata.MetadataIndexTemplateService.addIndexTemplateV2(MetadataIndexTemplateService.java:504) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]	
	at org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$4.execute(MetadataIndexTemplateService.java:399) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]	
	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:59) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]	
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:697) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]	
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:319) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]	
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:214) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]	
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:151) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]	
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]	
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]	
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:680) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]	
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]	
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]	
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]	
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]	
	at java.lang.Thread.run(Thread.java:834) [?:?]	
Caused by: org.elasticsearch.common.xcontent.XContentParseException: [index_template] unknown field [data_stream]	
	at org.elasticsearch.cluster.metadata.MetadataIndexTemplateService.lambda$validateCompositeTemplate$21(MetadataIndexTemplateService.java:1133) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]	
	at org.elasticsearch.indices.IndicesService.withTempIndexService(IndicesService.java:638) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]	
	at org.elasticsearch.cluster.metadata.MetadataIndexTemplateService.validateCompositeTemplate(MetadataIndexTemplateService.java:1113) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]	
	at org.elasticsearch.cluster.metadata.MetadataIndexTemplateService.addIndexTemplateV2(MetadataIndexTemplateService.java:500) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]	
	... 14 more
```

**Comment by martijnvg** [comment] 2021-01-05 11:12
The mentioned stacktrace is caused by the fact that the monitoring test doesn't load the data stream plugin and then the watcher history index template can't be added because it uses data stream (the data stream field type is missing). I also noticed that other plugins are not loaded which monitoring requires to run (enrich for `EnrichStatsCollector` and cc for `StatsCollector`). I will fix this and that should reduce the noice.

**Comment by martijnvg** [comment] 2021-01-06 16:47
I'm muting `testDisabledLocalExporterAlertsRemoval()` and `testLocalExporterWithAlertingDisabled()`, since these started to fail after merging in #66997.

**Comment by jbaiera** [comment] 2021-01-12 21:56
There are a couple of fresh failures for this test among others that were unmuted. 

https://gradle-enterprise.elastic.co/s/cj6fo6lynknmm/tests/:x-pack:plugin:monitoring:test/org.elasticsearch.xpack.monitoring.action.TransportMonitoringMigrateAlertsActionTests/testLocalAlertsRemoval#1

I was looking into this before the end of last year (turns out there was a duplicate issue #66391). From everything I was able to gather, something is delaying the setup of the `.watches` index that is required for the local tests. Here's the excerpt from the test logs:

```
  | 1> [2021-01-11T10:55:23,681][INFO ][o.e.x.m.a.TransportMonitoringMigrateAlertsActionTests] [testLocalAlertsRemoval] before test |  
  | 1> [2021-01-11T10:55:23,682][INFO ][o.e.x.m.a.TransportMonitoringMigrateAlertsActionTests] [testLocalAlertsRemoval] [TransportMonitoringMigrateAlertsActionTests#testLocalAlertsRemoval]: setting up test |  
  | 1> [2021-01-11T10:55:23,709][WARN ][o.e.c.m.MetadataIndexTemplateService] [node_s0] legacy template [random_index_template] has index patterns [*] matching patterns from existing composable templates [.slm-history,.triggered_watches,.watch-history-14,.watches] with patterns (.slm-history => [.slm-history-5*],.triggered_watches => [.triggered_watches*],.watch-history-14 => [.watcher-history-14*],.watches => [.watches*]); this template [random_index_template] may be ignored in favor of a composable template at index creation time |  
  | 1> [2021-01-11T10:55:23,711][INFO ][o.e.c.m.MetadataIndexTemplateService] [node_s0] adding template [random_index_template] for index patterns [*] |  
  | 1> [2021-01-11T10:55:23,766][INFO ][o.e.x.m.a.TransportMonitoringMigrateAlertsActionTests] [testLocalAlertsRemoval] [TransportMonitoringMigrateAlertsActionTests#testLocalAlertsRemoval]: all set up test |  
  | 1> [2021-01-11T10:55:23,778][INFO ][o.e.t.h.MockWebServer    ] [testLocalAlertsRemoval] bound HTTP mock server to [127.0.0.1:38303] |  
  | 1> [2021-01-11T10:55:23,802][INFO ][o.e.c.s.ClusterSettings  ] [node_s4] updating [xpack.monitoring.exporters._local.type] from [] to [local] |  
  | 1> [2021-01-11T10:55:23,802][INFO ][o.e.c.s.ClusterSettings  ] [node_s3] updating [xpack.monitoring.exporters._local.type] from [] to [local] |  
  | 1> [2021-01-11T10:55:23,802][INFO ][o.e.c.s.ClusterSettings  ] [node_s4] updating [xpack.monitoring.collection.enabled] from [false] to [true] |  
  | 1> [2021-01-11T10:55:23,802][INFO ][o.e.c.s.ClusterSettings  ] [node_s3] updating [xpack.monitoring.collection.enabled] from [false] to [true] |  
  | 1> [2021-01-11T10:55:23,802][INFO ][o.e.c.s.ClusterSettings  ] [node_s1] updating [xpack.monitoring.exporters._local.type] from [] to [local] |  
  | 1> [2021-01-11T10:55:23,802][INFO ][o.e.c.s.ClusterSettings  ] [node_s1] updating [xpack.monitoring.collection.enabled] from [false] to [true] |  
  | 1> [2021-01-11T10:55:23,807][INFO ][o.e.c.s.ClusterSettings  ] [node_s2] updating [xpack.monitoring.exporters._local.type] from [] to [local] |  
  | 1> [2021-01-11T10:55:23,807][INFO ][o.e.c.s.ClusterSettings  ] [node_s2] updating [xpack.monitoring.collection.enabled] from [false] to [true] |  
  | 1> [2021-01-11T10:55:23,814][INFO ][o.e.c.s.ClusterSettings  ] [node_s0] updating [xpack.monitoring.exporters._local.type] from [] to [local] |  
  | 1> [2021-01-11T10:55:23,815][INFO ][o.e.c.s.ClusterSettings  ] [node_s0] updating [xpack.monitoring.collection.enabled] from [false] to [true] |  
  | 1> [2021-01-11T10:55:24,810][DEPRECATION][o.e.d.c.m.MetadataCreateIndexService] [node_s0] data_stream.dataset="deprecation.elasticsearch" data_stream.namespace="default" data_stream.type="logs" ecs.version="1.6" key="index_template_multiple_match" message="index [.monitoring-es-7-2021.01.11] matches multiple legacy templates [.monitoring-es, random_index_template], composable templates will only match a single template" |  
  | 1> [2021-01-11T10:55:24,812][DEPRECATION][o.e.d.c.m.MetadataCreateIndexService] [node_s0] data_stream.dataset="deprecation.elasticsearch" data_stream.namespace="default" data_stream.type="logs" ecs.version="1.6" key="index_name_starts_with_dot" message="index name [.monitoring-es-7-2021.01.11] starts with a dot '.', in the next major version, index names starting with a dot are reserved for hidden indices and system indices" |  
  | 1> [2021-01-11T10:55:24,854][INFO ][o.e.c.m.MetadataCreateIndexService] [node_s0] [.monitoring-es-7-2021.01.11] creating index, cause [auto(bulk api)], templates [random_index_template, .monitoring-es], shards [10]/[1] |  
  | 1> [2021-01-11T10:55:28,188][INFO ][o.e.c.r.a.AllocationService] [node_s0] current.health="GREEN" message="Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[.monitoring-es-7-2021.01.11][8]]])." previous.health="YELLOW" reason="shards started [[.monitoring-es-7-2021.01.11][8]]" |  
  | 1> [2021-01-11T10:55:56,694][INFO ][o.e.c.s.ClusterSettings  ] [node_s4] updating [xpack.monitoring.exporters._local.type] from [local] to [] |  
  | 1> [2021-01-11T10:55:56,694][INFO ][o.e.c.s.ClusterSettings  ] [node_s2] updating [xpack.monitoring.exporters._local.type] from [local] to [] |  
  | 1> [2021-01-11T10:55:56,695][INFO ][o.e.c.s.ClusterSettings  ] [node_s4] updating [xpack.monitoring.collection.enabled] from [true] to [false] |  
  | 1> [2021-01-11T10:55:56,696][INFO ][o.e.c.s.ClusterSettings  ] [node_s2] updating [xpack.monitoring.collection.enabled] from [true] to [false] |  
  | 1> [2021-01-11T10:55:56,694][INFO ][o.e.c.s.ClusterSettings  ] [node_s3] updating [xpack.monitoring.exporters._local.type] from [local] to [] |  
  | 1> [2021-01-11T10:55:56,699][INFO ][o.e.c.s.ClusterSettings  ] [node_s3] updating [xpack.monitoring.collection.enabled] from [true] to [false] |  
  | 1> [2021-01-11T10:55:56,709][INFO ][o.e.c.s.ClusterSettings  ] [node_s1] updating [xpack.monitoring.exporters._local.type] from [local] to [] |  
  | 1> [2021-01-11T10:55:56,709][INFO ][o.e.c.s.ClusterSettings  ] [node_s1] updating [xpack.monitoring.collection.enabled] from [true] to [false] |  
  | 1> [2021-01-11T10:55:56,717][INFO ][o.e.c.s.ClusterSettings  ] [node_s0] updating [xpack.monitoring.exporters._local.type] from [local] to [] |  
  | 1> [2021-01-11T10:55:56,718][INFO ][o.e.c.s.ClusterSettings  ] [node_s0] updating [xpack.monitoring.collection.enabled] from [true] to [false] |  
  | 1> [2021-01-11T10:55:56,742][INFO ][o.e.x.m.a.TransportMonitoringMigrateAlertsActionTests] [testLocalAlertsRemoval] [TransportMonitoringMigrateAlertsActionTests#testLocalAlertsRemoval]: cleaning up after test |  
  | 1> [2021-01-11T10:55:56,921][INFO ][o.e.c.m.MetadataDeleteIndexService] [node_s0] [.monitoring-es-7-2021.01.11/g5ePvZ4-RKGXECT1vQqlQw] deleting index |  
  | 1> [2021-01-11T10:55:57,263][INFO ][o.e.c.m.MetadataIndexTemplateService] [node_s0] removing template [random_index_template] |  
  | 1> [2021-01-11T10:55:57,324][INFO ][o.e.x.m.a.TransportMonitoringMigrateAlertsActionTests] [testLocalAlertsRemoval] [TransportMonitoringMigrateAlertsActionTests#testLocalAlertsRemoval]: cleaned up after test |  
  | 1> [2021-01-11T10:55:57,324][INFO ][o.e.x.m.a.TransportMonitoringMigrateAlertsActionTests] [testLocalAlertsRemoval] after test |  
  | 2> REPRODUCE WITH: ./gradlew ':x-pack:plugin:monitoring:test' --tests "org.elasticsearch.xpack.monitoring.action.TransportMonitoringMigrateAlertsActionTests.testLocalAlertsRemoval" -Dtests.seed=38904F1E769EB12E -Dtests.security.manager=true -Dtests.locale=no-NO -Dtests.timezone=Africa/Algiers -Druntime.java=11 |  
  | 2> java.lang.AssertionError: |  
  | Expected: is <true> |  
  | but: was <false> |  
  | at __randomizedtesting.SeedInfo.seed([38904F1E769EB12E:9FED729CC8584D9]:0) |  
  | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18) |  
  | at org.junit.Assert.assertThat(Assert.java:956) |  
  | at org.junit.Assert.assertThat(Assert.java:923) |  
  | at org.elasticsearch.xpack.monitoring.test.MonitoringIntegTestCase.assertIndicesExists(MonitoringIntegTestCase.java:186) |  
  | at org.elasticsearch.xpack.monitoring.test.MonitoringIntegTestCase.lambda$awaitIndexExists$3(MonitoringIntegTestCase.java:180) |  
  | at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:955) |  
  | at org.elasticsearch.xpack.monitoring.test.MonitoringIntegTestCase.awaitIndexExists(MonitoringIntegTestCase.java:180) |  
  | at org.elasticsearch.xpack.monitoring.action.TransportMonitoringMigrateAlertsActionTests.waitForWatcherIndices(TransportMonitoringMigrateAlertsActionTests.java:578) |  
  | at org.elasticsearch.xpack.monitoring.action.TransportMonitoringMigrateAlertsActionTests.ensureInitialLocalResources(TransportMonitoringMigrateAlertsActionTests.java:459) |  
  | at org.elasticsearch.xpack.monitoring.action.TransportMonitoringMigrateAlertsActionTests.testLocalAlertsRemoval(TransportMonitoringMigrateAlertsActionTests.java:123)
```

**Comment by dnhatn** [comment] 2021-01-19 18:21
Another instance: https://gradle-enterprise.elastic.co/s/jcpiyio2mmcv6

**Comment by mark-vieira** [comment] 2021-01-21 22:19
I've muted both `testLocalAlertsRemoval` and `testRepeatedLocalAlertsRemoval` in `master` as they have been failing again this week.

**Comment by martijnvg** [comment] 2021-01-26 08:59
Apologies, I missed the updates to this issue. I've looked into the latest failure and I can confirm what @jbaiera has observed. In the case of the `testRepeatedLocalAlertsRemoval()` test, the test fails after waiting for 20s for the `.watches` index. This index should be created by the `LocalExporter` class in the monitoring plugin, however for some reason the logic in `LocalExporter#setupIfElectedMaster()` method doesn't get executed. Also the fact that all indices get deleted between tests, also probably doesn't help here. I'm going to unmute the `testLocalAlertsRemoval` and `testRepeatedLocalAlertsRemoval ` tests again and enable test logging for these tests. I will keep an eye on CI for these test failures. If I'm slow to respond, then please mute again.

**Comment by martijnvg** [comment] 2021-02-17 13:35
After adding more logging via #68752 and [this test failure](https://gradle-enterprise.elastic.co/s/yxpr54azkcehy/console-log?task=:x-pack:plugin:monitoring:test), that the setup of watcher is never attempted, however the local exporter setup is marked as completed and because of this during the `testRepeatedLocalAlertsRemoval()` test watches are never ever installed. This test expects the watch index to exists, and therefore fails.

The problem is `LocalExporter#setupClusterAlertsTasks(...)` skips installing the watches because:

```
watches shouldn't be setup, because state=[INITIALIZED] and clusterStateChange=[true]
```

However the .watch index is missing. I think the `setupClusterAlertsTasks()` method should also consider installing the watches if .watches index is missing, regardless of state.

The `setupIfElectedMaster()` method that is invoking the `setupClusterAlertsTasks()` method should not advertise the setup as complete, if watcher isn't ready and another setup attempt needs to be done.

I will work on a PR.

**Comment by martijnvg** [comment] 2021-02-22 11:57
The tests haven't failed in almost 5 days. Also re-enabled these tests in 7.x branch.

**Closed by martijnvg** 2021-02-22 11:57 UTC
Labels: :Core/Features/Monitoring, >test-failure, Team:Core/Features
