### ISSUE TITLE
The elasticsearch plugin cli ignore the path.plugins configuration

### ISSUE THREAD

**Issue by johnsudaar** [elastic/elasticsearch#26039] opened 2017-08-03 10:08 UTC
**Elasticsearch version** (`bin/elasticsearch --version`): `Version: 5.5.0, Build: 260387d/2017-06-30T23:16:05.735Z, JVM: 1.8.0_131`

**Plugins installed**: []

**JVM version** (`java -version`):
```
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system): `Linux 4225cddbbee9 4.10.0-28-generic #32~16.04.2-Ubuntu SMP Thu Jul 20 10:19:48 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

1. Use the following configuration (`/etc/elasticsearch/elasticsearch.yml`):
```
indices.fielddata.cache.size: 60%
indices.breaker.fielddata.limit: 70%

discovery.zen.ping.unicast.hosts: ["localhost"]

path.plugins: /var/lib/elasticsearch/plugins
```

2. Install a pugin
```
me@host:/usr/share/elasticsearch# CONF_DIR=/etc/elasticsearch/ bin/elasticsearch-plugin install mapper-attachments
-> Downloading mapper-attachments from elastic
[=================================================] 100%?? 
[...]
Continue with installation? [y/N]y
-> Installed mapper-attachments
```

3. Check where the plugin has been installed
```
me@host:/usr/share/elasticsearch# ls /var/lib/elasticsearch/plugins/
me@host:/usr/share/elasticsearch# ls /usr/share/elasticsearch/plugins/
mapper-attachments
```

The plugin should be installed to `/var/lib/elasticsearch/plugins` instead of the default `/usr/share/elasticsearch/plugins`

**Comment by jasontedor** [comment] 2017-08-03 10:19
That's not a valid setting since 5.0.0; see #18594 and the [breaking changes for 5.0.0](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_50_plugins.html#_custom_plugins_path). The plugins script doesn't read nor validate such settings but if you start Elasticsearch with that setting it will fail. I'm closing this as not a bug. However, do you see documentation for 5.x that indicates this is a valid setting? If so, we will need to correct the docs.

**Closed by jasontedor** 2017-08-03 10:19 UTC
