### ISSUE TITLE
[CI] QueryProfilerIT testProfileMatchesRegular is failing

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#32492] opened 2018-07-31 11:28 UTC
Test failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/2432/console

fails with:

```
QueryProfilerIT.testProfileMatchesRegular <<< FAILURES!
> Throwable #1: java.lang.AssertionError: Profile totalHits of [127] is not close to Vanilla totalHits [129]
> Expected: <127L>
>      but: was <129L>
> 	at __randomizedtesting.SeedInfo.seed([32784220547E92F2:61AD95220536708E]:0)
> 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
> 	at org.elasticsearch.search.profile.query.QueryProfilerIT.testProfileMatchesRegular(QueryProfilerIT.java:162)
> 	at java.lang.Thread.run(Thread.java:748)
```

Reproduction line:

```
./gradlew :server:integTest \
  -Dtests.seed=32784220547E92F2 \
  -Dtests.class=org.elasticsearch.search.profile.query.QueryProfilerIT \
  -Dtests.method="testProfileMatchesRegular" \
  -Dtests.security.manager=true \
  -Dtests.locale=id \
  -Dtests.timezone=America/Curacao
```

(does not reproduce locally)

**Comment by andyb-elastic** [comment] 2018-11-01 23:53
Another one in master

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=centos/33/console

[build-master-centos-33.txt.zip](https://github.com/elastic/elasticsearch/files/2540520/build-master-centos-33.txt.zip)

```
  2> REPRODUCE WITH: ./gradlew :server:integTest -Dtests.seed=91857F7F3931F7A9 -Dtests.class=org.elasticsearch.search.profile.query.QueryProfilerIT -Dtests.method="testProfileMatchesRegular" -Dtests.security.manager=true -Dtests.locale=en-AU -Dtests.timezone=Etc/GMT-0 -Dcompiler.java=11 -Druntime.java=8
```

```
FAILURE 0.34s J0 | QueryProfilerIT.testProfileMatchesRegular <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Vanilla hits were larger than profile hits.  Non-overlapping elements were: [{
   >   "_index" : "test",
   >   "_type" : "type1",
   >   "_id" : "106",
   >   "_score" : null,
   >   "_source" : {
   >     "field1" : "one hundred six ",
   >     "field2" : 106
   >   },
   >   "sort" : [
   >     "106"
   >   ]
   > }, {
   >   "_index" : "test",
   >   "_type" : "type1",
   >   "_id" : "104",
   >   "_score" : null,
   >   "_source" : {
   >     "field1" : "one hundred four ",
   >     "field2" : 104
   >   },
   >   "sort" : [
   >     "104"
   >   ]
   > }, {
   >   "_index" : "test",
   >   "_type" : "type1",
   >   "_id" : "16",
   >   "_score" : null,
   >   "_source" : {
   >     "field1" : "sixteen ",
   >     "field2" : 16
   >   },
   >   "sort" : [
   >     "16"
   >   ]
   > }, {
   >   "_index" : "test",
   >   "_type" : "type1",
   >   "_id" : "102",
   >   "_score" : null,
   >   "_source" : {
   >     "field1" : "one hundred two ",
   >     "field2" : 102
   >   },
   >   "sort" : [
   >     "102"
   >   ]
   > }, {
   >   "_index" : "test",
   >   "_type" : "type1",
   >   "_id" : "13",
   >   "_score" : null,
   >   "_source" : {
   >     "field1" : "thirteen ",
   >     "field2" : 13
   >   },
   >   "sort" : [
   >     "13"
   >   ]
   > }, {
   >   "_index" : "test",
   >   "_type" : "type1",
   >   "_id" : "17",
   >   "_score" : null,
   >   "_source" : {
   >     "field1" : "seventeen ",
   >     "field2" : 17
   >   },
   >   "sort" : [
   >     "17"
   >   ]
   > }, {
   >   "_index" : "test",
   >   "_type" : "type1",
   >   "_id" : "11",
   >   "_score" : null,
   >   "_source" : {
   >     "field1" : "eleven ",
   >     "field2" : 11
   >   },
   >   "sort" : [
   >     "11"
   >   ]
   > }, {
   >   "_index" : "test",
   >   "_type" : "type1",
   >   "_id" : "103",
   >   "_score" : null,
   >   "_source" : {
   >     "field1" : "one hundred three ",
   >     "field2" : 103
   >   },
   >   "sort" : [
   >     "103"
   >   ]
   > }, {
   >   "_index" : "test",
   >   "_type" : "type1",
   >   "_id" : "14",
   >   "_score" : null,
   >   "_source" : {
   >     "field1" : "fourteen ",
   >     "field2" : 14
   >   },
   >   "sort" : [
   >     "14"
   >   ]
   > }, {
   >   "_index" : "test",
   >   "_type" : "type1",
   >   "_id" : "10",
   >   "_score" : null,
   >   "_source" : {
   >     "field1" : "ten ",
   >     "field2" : 10
   >   },
   >   "sort" : [
   >     "10"
   >   ]
   > }]
   >    at __randomizedtesting.SeedInfo.seed([91857F7F3931F7A9:C250A87D687915D5]:0)
   >    at org.elasticsearch.search.profile.query.QueryProfilerIT.testProfileMatchesRegular(QueryProfilerIT.java:173)
   >    at java.lang.Thread.run(Thread.java:748)
```

**Comment by andyb-elastic** [comment] 2018-11-01 23:54
The full log is attached for that last one, so in hopes that it caught the debugging info that was added I'm going to mute this again

**Comment by polyfractal** [comment] 2018-11-02 14:37
Thanks for grabbing those logs @andyb-elastic!  I checked quickly and it doesn't reproduce locally for me... will let it run for a few hours in the background and see if it breaks.  

If anyone else from S&A wants to learn how the profiler works I'd be happy to share the debugging :)  Definitely not an encouraging failure, having the hits not match...

**Comment by polyfractal** [comment] 2018-11-02 14:56
Colin had a good idea; we should verify that all the `equals()` and `hashCode()`s are properly setup for profiler weights/queries/scores and make sure there isn't some kind of effect due to returning bad results from cache.

There are also other known caching issues too (https://github.com/elastic/elasticsearch/issues/29024) but that deals with the request cache and I don't think it's the issue here due to the randomization.  But we should double check the request cache as well just in case.

**Comment by polyfractal** [comment] 2019-02-11 21:42
I re-enabled the test and disabled caching, plus limiting the test to a single query per test run (to make reproduction clearer/easier... hopefully).

Going to close, again, please re-open if this fails again and I'll dive back into debugging.  FWIW, I haven't been able to reproduce at all despite hundreds of thousands of iterations :(

/me resets the days-since-failure counter

![image](https://user-images.githubusercontent.com/1224228/52595456-ee637180-2e1b-11e9-8ef3-6d047c52033a.png)

**Comment by jimczi** [comment] 2019-02-19 15:01
@polyfractal should we close this issue ?

**Comment by polyfractal** [comment] 2019-02-20 15:39
Yeah, I'll go ahead and close.  We can reopen if it pops up again (fingers crossed)

**Comment by cbuescher** [comment] 2019-04-10 08:00
Looks like this might have popped up again in https://github.com/elastic/elasticsearch/issues/40885. @polyfractal are you still familiar enough with the issue to see if these new occurances are related?

**Comment by polyfractal** [comment] 2019-04-11 16:39
@cbuescher Took a look... I think those are the same failures as this issue.  The new failure (`Profile totalHits of [93] is not close to Vanilla totalHits [98]`) is probably related as well... that found a case where the max score was different not just number of results.

I'm out of ideas about the problem though.  Perhaps something related to the changes in tracking total hits which is acting differently in the profiler?  Or something related to CCS changes?

**Comment by markharwood** [comment] 2019-05-20 15:22
Discussing https://github.com/elastic/elasticsearch/issues/39659 which is related to common terms query and there was a suggestion this issue may too have had a common terms query in previous failures so maybe that could be a common thread.

**Comment by markharwood** [comment] 2019-05-22 08:57
Using many iterations I saw 5 failures, all of them had a `common terms` query e.g.

    {
      "common" : {
        "field1" : {
          "query" : "fifty  twenty-nine  thirty-five  thirteen  zero nineteen  twenty-four  seven  thirteen  forty  seven  eight  twenty-seven  thirty-two  forty-four  thirty-four  thirty-six  fifty  thirty-two  forty-three  thirty-three  forty-nine  thirty-one  ten  six  thirty-four  six  eighteen  thirteen  fifteen  forty-five  thirty-three  five  twenty-five  twenty-one  forty-three  forty-four  thirty-three  forty-six  fifteen  five  four  twenty-one  thirty-three  forty-two  twenty-nine  forty-nine  twenty-seven  eight  nineteen",
          "high_freq_operator" : "AND",
          "low_freq_operator" : "OR",
          "cutoff_frequency" : 0.11731702,
          "minimum_should_match" : {
            "high_freq" : "2"
          },
          "boost" : 0.90921104
        }
      }
    }  

Will dig in some more

**Comment by jimczi** [comment] 2019-05-22 13:21
The `common` terms query relies on the statistics of the shard to build the query so the result can differ if two reader have the same live documents but a different number of deletes for instance (depending on how the segments are merged). Since the test adds some random deletes in the mix I wonder if we should simply remove this query from the random generation or force merge all replicas to 1 segment ?

**Comment by markharwood** [comment] 2019-05-22 13:22
The only thing vaguely reproducible I've found is:
1) The above query hard-coded into the test
2) The seed -Dtests.seed=36C99889D2D4AB97
3) Setting  `@Repeat(iterations = 10)` on the test

The above doesn't fail every time but when it does it is always on the 9th iteration

**Comment by markharwood** [comment] 2019-05-22 14:16
@jimczi spotted it - it's the subtle scoring differences between 2 replicas because of their divergent merging operations.
I'll put up a PR

**Closed** 2019-05-23 09:34 UTC
Labels: :Search/Search, >test-failure
