### ISSUE TITLE
Nest 5: Scroll issue

### ISSUE THREAD

**Issue by slorena** [elastic/elasticsearch#24538] opened 2017-05-07 23:06 UTC
Hello,

I'm using Elasticsearch 5.1.1 and Nest 5.0 and I'm trying to search items by query.
This is the code:
var searchDescriptor = new SearchDescriptor<object>()
                .Index(indexName)
                .Size(itemsPerShard)
                .StoredFields((Field)"Id")
                .Scroll("1m")
                .Sort(ss => ss.Ascending(SortSpecialField.DocumentIndexOrder))
                .Query(qd => qd
                    .QueryString(snd => snd
                        .Query(deleteByQuery)
                        .DefaultOperator(Operator.And))
                );
var scanResults = client.Search<object>(s => searchDescriptor);

When itemsPerShard > 10.000, I receive this error:
{Invalid NEST response built from a unsuccessful low level call on POST: /index/_search?scroll=1m}.
And in elasticsearch log file:
Batch size is too large, size must be less than or equal to: [10000] but was [10001]. Scroll batch sizes cost as much memory as result windows so they are controlled by the [index.max_result_window] index level setting.

How can I resolve this issue?

Thank you!

**Comment by tvernum** [comment] 2017-05-07 23:55
Please ask this question on our [discuss forum](https://discuss.elastic.co/c/elasticsearch) where we can provide better support for your question. 

I would recommend that you re-read the [documentation for the scrolling search requests](https://www.elastic.co/guide/en/elasticsearch/reference/5.1/search-request-scroll.html) in Elasticsearch, before asking your question so that you get the best possible help. (_Hint_: you probably don't want to have  size that is greater than `10,000`)

Elastic uses GitHub issues for confirmed bugs and feature requests only. Since this does not appear to be a bug in Elasticsearch, so I'm going to close this ticket.

Thank you.

**Closed** 2017-05-08 00:58 UTC
