### ISSUE TITLE
Relative data path on Windows can report incorrect disk size

### ISSUE THREAD

**Issue by seang-es** [elastic/elasticsearch#13251] opened 2015-09-01 16:42 UTC
To repro:

On Windows, set path.data to a relative path.  'data' for example.
Use Powershell to run a remote execution to remotely start Elasticsearch.

With a relative path set, the system reports a disk available size of '-1'.  If the absolute path is set in the configuration, disk available size is correct.  When started locally, the disk available size is also correct.

This may only need a document fix to specify absolute paths for path.data.

**Comment by clintongormley** [comment] 2015-09-01 17:09
@tlrx could you look at this please? See if it is the same after your changes in master?

**Comment by tlrx** [comment] 2015-10-15 14:16
> Use Powershell to run a remote execution to remotely start Elasticsearch.

@seang-es Are you starting elasticsearch as a service with PowerShell using the  ̀Start-Service` cmdlet?

**Comment by clintongormley** [comment] 2016-05-24 10:30
@seang-es ping

**Comment by tlrx** [comment] 2016-07-01 08:22
No feedback and I'm unable to reproduce the issue. I'm closing it, please feel free to reopen if needed.

**Closed by tlrx** 2016-07-01 08:22 UTC
Labels: :Stats, feedback_needed, v1.7.1
