### ISSUE TITLE
Unable to run Elasticsearch with single-node discovery setting.

### ISSUE THREAD

**Issue by franciszabala** [elastic/elasticsearch#25525] opened 2017-07-04 02:20 UTC
**Describe the feature**:

**Elasticsearch version**: 5.1.1

**Plugins installed**: vanilla install

**JVM version** (`java -version`): 1.8.0_131

**OS version** (`uname -a` if on a Unix-like system): Ubuntu 16.04

**Description of the problem including expected versus actual behavior**: Unable to run Elasticsearch using "single-node"

**Steps to reproduce**: 

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Download and extract Elasticsearch 5.1.1
 2. add discovery.type: single-node to config/elasticsearch.yml
 3. set network.host: _site_

**Provide logs (if relevant)**:

Caused by: java.lang.IllegalArgumentException: Unknown discovery type [single-node]
	at org.elasticsearch.discovery.DiscoveryModule.<init>(DiscoveryModule.java:93) ~[elasticsearch-5.1.1.jar:5.1.1]

**Comment by tvernum** [comment] 2017-07-04 02:25
Single node discovery was [introduced](https://github.com/elastic/elasticsearch/pull/23595) in Elasticsearch 5.4, it will not work in 5.1.1

If there is documentation somewhere that suggests this will work, please let us know so we can fix it.

I'm going to close this issue, as it is not a bug.

**Closed by tvernum** 2017-07-04 02:25 UTC

**Comment by krisavi** [comment] 2019-02-07 16:46
Maybe should be reopened. Same issue in 7.0.0-alpha2. Documentation states that it should be possible in 7.0.0
```
[2019-02-07T17:41:29,590][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [TESTMACHINE] [controller/33060] [Main.cc@109] controller (64 bit): Version 7.0.0-alpha2 (Build 9f15ef8a90260b) Copyright (c) 2018 Elasticsearch BV
[2019-02-07T17:41:30,698][ERROR][o.e.b.Bootstrap          ] [TESTMACHINE] Exception
java.lang.IllegalArgumentException: Unknown discovery type [singe-node]
```
