### ISSUE TITLE
 inconsistent num of document between _cat/indices and <index>/_search

### ISSUE THREAD

**Issue by veeruborra** [elastic/elasticsearch#15873] opened 2016-01-09 12:33 UTC
i inserted one document in elasticsearch.
when i search in indices it showing

http://localhost:9200/_cat/indices?v
health status   index          pri    rep     docs.count     docs.deleted     store.size             pri.store.size 
green  open   mylogs        5      1         2                  0                        72.4kb                     72.4kb  

when searching in that index

http://localhost:9200/mylogs/_search

took: 1,
timed_out: false,
_shards: {
total: 5,
successful: 5,
failed: 0
},
hits: {
total: 1,
max_score: 1,
hits: [
{}]

**Comment by jasontedor** [comment] 2016-01-09 13:23
What version of Elasticsearch are you running, and can you provide a minimal reliable reproduction as this does not reproduce for me?

```bash
$ curl -XGET localhost:9200/_cat/nodes?v
host      ip        heap.percent ram.percent cpu load node.role master name
127.0.0.1 127.0.0.1            6          99   6 1.69 d         m      Nick Fury
127.0.0.1 127.0.0.1            2          99   6 1.69 d         *      Thog
$ curl -XDELETE localhost:9200/_all?pretty=1
{
  "acknowledged" : true
}
$ curl -XPOST localhost:9200/foo/bar/1?pretty=1 -d '{ "foo" : "bar" }'
{
  "_index" : "foo",
  "_type" : "bar",
  "_id" : "1",
  "_version" : 1,
  "_shards" : {
    "total" : 2,
    "successful" : 1,
    "failed" : 0
  },
  "created" : true
}
$ curl -XGET localhost:9200/_cat/indices?v
health status index pri rep docs.count docs.deleted store.size pri.store.size
green  open   foo     5   1          1            0      3.3kb           260b
$ curl -XGET localhost:9200/foo/_search?pretty=1
{
  "took" : 3,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "foo",
      "_type" : "bar",
      "_id" : "1",
      "_score" : 1.0,
      "_source" : {
        "foo" : "bar"
      }
    } ]
  }
}
```

**Comment by veeruborra** [comment] 2016-01-10 09:45
{
name: "Leo",
cluster_name: "elasticsearch",
version: {
number: "2.1.1",
build_hash: "40e2c53a6b6c2972b3d13846e450e66f4375bd71",
build_timestamp: "2015-12-15T13:05:55Z",
build_snapshot: false,
lucene_version: "5.3.1"
},
tagline: "You Know, for Search"
}

**Comment by clintongormley** [comment] 2016-01-10 10:07
@veeruborra could you also provide a curl recreation demonstrating this problem?  I'm unable to recreate this either

**Comment by veeruborra** [comment] 2016-01-10 12:13
I am using elasticsearch-php for inserting document in my index.

 $params =
            [
                'index' => index_logs,
                'type' => index_type,
                'client' => [
                    'ignore' => [400, 404],
                    'verbose' => true,
                    'timeout' => 10,
                    'connect_timeout' => 10
                ],
                'body' => $data
            ];
        $client = ClientBuilder::create()->build();
        $apiexception = $client->create($params);

when exception occurs the error data is stored in $data variable..

**Comment by jasontedor** [comment] 2016-01-10 13:13
@veeruborra We are looking for a [reliable script and instructions that reliably reproduces the issue](https://en.wikipedia.org/wiki/Minimal_Working_Example) so that we can investigate. Without this information, we are in the dark about what you're seeing and what the cause is.

**Comment by jasontedor** [comment] 2016-01-15 12:47
Closing due to no feedback.

**Closed by jasontedor** 2016-01-15 12:47 UTC
Labels: :CAT API, feedback_needed
