### ISSUE TITLE
Darwin compatibility build fails due to git clone timeout

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#77032] opened 2021-08-30 14:57 UTC
Darwin compatibility tests have failed more than once due to a git clone timeout. 

This is a weird one to me, seems like its becoming systemic.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob+platform-support-darwin/232/

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob+platform-support-darwin/232/

In 7.x, it was able to fetch objects and THEN timedout. In the master build, it simply timedout.

**Comment by mark-vieira** [comment] 2021-08-31 22:24
Hmm, I need to reach out to infra again to rebuild these workings. I think they are beyond repair.

**Comment by mark-vieira** [comment] 2021-09-16 21:48
Closing as a duplicate of #73070.

**Closed** 2021-09-16 21:48 UTC
Labels: :Delivery/Build, >test-failure, Team:Delivery
