### ISSUE TITLE
ES Returns Empty Aggregations Between Time Ranges

### ISSUE THREAD

**Issue by shreyu86** [elastic/elasticsearch#27877] opened 2017-12-18 20:30 UTC
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): `6.1.0`

**Plugins installed**: [`"discovery-ec2"`]

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system): `Amazon Linux (3-node cluster)`

**Description of the problem including expected versus actual behavior**:
I have about 400K documents in ES (3 node cluster), the documents have following format:
```
{
    "@timestamp": "2017-11-21T06:49:39.800Z",
    "message": "xxxx",
    "username": "xxxx",
    "geoip": {
        "country_name": "United States",
        "region_name": "Washington",
        "city_name": "Seattle"
    }
}
```

I am performing nested aggregations using the following query:
```
{
    "size": 0,
    "query": {
        "bool": {
            "must": [
                {
                    "range": {
                        "@timestamp": {
                            "gte": "now-90d/d",
                            "lt": "now/d",
                            "time_zone": "US/Pacific"
                        }
                    }
                }
            ]
        }
    },
    "sort": [
        {
            "@timestamp": {
                "order": "desc"
            }
        }
    ],
    "aggs": {
        "countries": {
            "terms": {
                "size": 1000000,
                "field": "geoip.country_name.keyword"
            },
            "aggs": {
                "regions": {
                    "terms": {
                        "size": 1000000,
                        "field": "geoip.region_name.keyword"
                    },
                    "aggs": {
                        "cities": {
                            "terms": {
                                "size": 1000000,
                                "field": "geoip.city_name.keyword.keyword"
                            },
                            "aggs": {
                                "users": {
                                    "terms": {
                                        "size": 1000000,
                                        "field": "username.keyword"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```

I do get results back for this query and the aggregations are computed. However if I change the time range to target some of the most recent documents for example:
```
{
    "range": {
        "@timestamp": {
            "gte": "now-2d/d",
            "lt": "now/d",
            "time_zone": "US/Pacific"
        }
    }
}
```

I get hits back but no aggregations, I can confirm that there is documents matching the time range I provided and the data format has not changed either.

Only thing I can think of is that I recently upgraded to `ES 6.1.0` from `ES 6.0.0`
I found this odd that ES computes aggregations for slice of documents containing older documents but does not compute aggregations for newer documents.

I have opened an thread at https://discuss.elastic.co/t/es-6-1-0-aggregations-empty/112100 and opening an issue here for more visibility.

**Comment by colings86** [comment] 2017-12-19 11:04
@shreyu86  could you provide some recreation steps for this? By this I mean a short script which details calls made to Elasticsearch for a small test index from index creation, through indexing docs and showing the error in a search request. This will allow us to recreate your issue and help either understanding it or diagnosing the bug. I think the data in the documents will be the key to finding the source of the issue here.

**Comment by colings86** [comment] 2017-12-19 19:18
From the comment  on https://discuss.elastic.co/t/es-6-1-0-aggregations-empty/112100/5 it looks like this is confirmed as not a bug so I'm closing this issue

**Closed by colings86** 2017-12-19 19:18 UTC
Labels: :Aggregations, feedback_needed

**Comment by shreyu86** [comment] 2017-12-19 19:19
@colings86 Thanks for the response I was about to close this issue since I figured out why this was happening. I really appreciate your help and the comments on the forum.
