### ISSUE TITLE
[CI] org.elasticsearch.recovery.RelocationIT.testIndexAndRelocateConcurrently fails with checkpoint mismatch and missing document

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#24352] opened 2017-04-26 20:50 UTC
I was unable to reproduce the failure locally, but it fails not finding the document:

```
   > Throwable #1: java.lang.AssertionError: Some expected ids were not found in search results: [ⷻⷴⷽⷳⷾⷾⷾⷱⷶa254]. Total shards: 4 Successful shards: 4 & 0 shard failures:
   > Expected: <0>
   >      but: was <1>
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertSearchHits(ElasticsearchAssertions.java:229)
   > 	at org.elasticsearch.recovery.RelocationIT.testIndexAndRelocateConcurrently(RelocationIT.java:512)
   > 	at java.lang.Thread.run(Thread.java:745)Throwable #2: java.lang.AssertionError: [test][3], node[yOrQW5OfQMOMIFi1S4YKSA], [R], s[STARTED], a[id=WM-cDwAKSJOsTxUuqTFO5g] local checkpoint mismatch
```

As well as the local checkpoint not matching

```
   > Expected: <140L>
   >      but: was <34L>
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.recovery.RelocationIT.lambda$beforeIndexDeletion$1(RelocationIT.java:132)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:712)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:686)
   > 	at org.elasticsearch.recovery.RelocationIT.beforeIndexDeletion(RelocationIT.java:116)
   > 	at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:580)
   > 	at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2058)
   > 	at java.lang.Thread.run(Thread.java:745)
   > 	Suppressed: java.lang.AssertionError: [test][3], node[yOrQW5OfQMOMIFi1S4YKSA], [R], s[STARTED], a[id=WM-cDwAKSJOsTxUuqTFO5g] local checkpoint mismatch
```

Failure here: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=opensuse/891/consoleText

**Comment by ywelsch** [comment] 2017-04-26 21:02
duplicate of https://github.com/elastic/elasticsearch/issues/24167

**Comment by jasontedor** [comment] 2017-04-26 21:02
Duplicates #24167

**Closed by ywelsch** 2017-04-26 21:02 UTC
Labels: jenkins

**Comment by dakrone** [comment] 2017-04-26 21:10
Thanks Yannick & Jason
