### ISSUE TITLE
RHEL 9 installation fails

### ISSUE THREAD

**Issue by JensVD** [elastic/elasticsearch#97614] opened 2023-07-12 12:36 UTC
### Elasticsearch Version

Version: 7.17.11, Build: default/rpm/eeedb98c60326ea3d46caef960fb4c77958fb885/2023-06-23T05:33:12.261262042Z, JVM: 20.0.1

### Java Version

openjdk version "1.8.0_362"

### OS Version

Linux server 5.14.0-333.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jun 28 09:47:27 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

When trying to install any ElasticSearch related application on a RHEL9 based system it blocks due to the GPG checks. The reason for this is the deprecation of the SHA1 algorithm starting in RHEL9 based system.
The ElasticSearch GPG key seems to be signed using the SHA1 algorithm which is no longer secure and has been blocked since RHEL9.

This doesn't just affect ElasticSearch but all elastic.co products.

### Steps to Reproduce

1. Create a VM with CentOS9 (or another RHEL9 based system)
2. Import the RPM key and watch it fail
`sudo rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch`

`warning: Signature not supported. Hash algorithm SHA1 not available.
error: https://artifacts.elastic.co/GPG-KEY-elasticsearch: key 1 import failed.`

**Comment by mark-vieira** [comment] 2023-07-13 22:28
Duplicate of https://github.com/elastic/elasticsearch/issues/85876.

**Closed by mark-vieira** 2023-07-13 22:28 UTC
Labels: >bug, :Delivery/Packaging, Team:Delivery

**Comment by armghan** [comment] 2023-09-21 16:10
When will this issue be fixed? @elasticsearchmachine

**Comment by mark-vieira** [comment] 2023-09-26 19:44
> When will this issue be fixed? @elasticsearchmachine

This has been resolved: https://github.com/elastic/elasticsearch/issues/85876#issuecomment-1733018142
