### ISSUE TITLE
logstash ingest attachment plugin not working while using update action

### ISSUE THREAD

**Issue by cnus11** [elastic/elasticsearch#23408] opened 2017-02-28 13:03 UTC
**Elasticsearch version**: 5.2

**Plugins installed**: [ingest_attachment]

**Description of the problem including expected versus actual behavior**:

This happens in logstash configuration 

**Steps to reproduce**:
Elastic search and logstash should be installed.
ingest_atatchment plugin needs to be added
 1. Create a document with some random fields
 2. Update document with some attachment data which is base64 encoded
 3. attachment data will only get decoded while inserting but not while updating.

Here is my configuration file.

elasticsearch {
            hosts => ["localhost:9200"]
            index => "some_index"
            action => "update"
            document_id => "%{some_id}"
            pipeline => "attach_pipeline"
          }

**Comment by clintongormley** [comment] 2017-02-28 13:25
Ingest pipelines are not supported by the update API.  Closing as duplicate of https://github.com/elastic/elasticsearch/issues/17895

**Closed by clintongormley** 2017-02-28 13:25 UTC

**Comment by jgarcial** [comment] 2017-07-05 11:34
This is exactly my situation.

What is the workaround to update a record with an base64 encoded field that needs to be indexed?
