### ISSUE TITLE
[CI] Cannot connect to gradle daemon within 120s

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#36768] opened 2018-12-18 13:07 UTC
See https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-darwin-compatibility/126/console

There is a connection issue with the gradle daemon. The message already states that this can happen when the system is extremely slow, but 120 seconds is also quite the timeout. I have searched across former logs and builds and could not find anything like that - so if it is a fluke, please close immediately.

Here is the stack trace, the build daemon is started at the top, and the whole build only takes 4 seconds longer than the 120s timeout.

<details><summary>Stack Trace</summary>

```
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
Initialized native services in: /private/var/lib/jenkins/.gradle/native
Removing 0 daemon stop events from registry
Starting a Gradle Daemon (subsequent builds will be faster)
Starting process 'Gradle build daemon'. Working directory: /private/var/lib/jenkins/.gradle/daemon/5.0 Command: /private/var/lib/jenkins/.java/oracle-11+28-darwin/bin/java --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED -Xmx2g -Dfile.encoding=UTF8 -Duser.country=US -Duser.language=en -Duser.variant -cp /var/lib/jenkins/.gradle/wrapper/dists/gradle-5.0-all/4mxuau4c77thx8zlvtz4xiez7/gradle-5.0/lib/gradle-launcher-5.0.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 5.0
Successfully started process 'Gradle build daemon'
An attempt to start the daemon took 1.033 secs.
The client will now receive all logging from the daemon (pid: 87062). The daemon log file: /private/var/lib/jenkins/.gradle/daemon/5.0/daemon-87062.out.log
Starting build in new daemon [memory: 2.1 GB]
Using 12 worker leases.
Starting Build

> Configure project :buildSrc
Evaluating project ':buildSrc' using build file '/private/var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob-darwin-compatibility/buildSrc/build.gradle'.
Selected primary task 'build' from project :
:buildSrc:compileMinimumRuntimeJava (Thread[Execution worker for ':buildSrc' Thread 10,5,main]) started.

> Task :buildSrc:compileMinimumRuntimeJava NO-SOURCE
file or directory '/private/var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob-darwin-compatibility/buildSrc/src/minimumRuntime/java', not found
Skipping task ':buildSrc:compileMinimumRuntimeJava' as it has no source files and no previous output files.
:buildSrc:compileMinimumRuntimeJava (Thread[Execution worker for ':buildSrc' Thread 10,5,main]) completed. Took 0.076 secs.
:buildSrc:compileMinimumRuntimeGroovy (Thread[Execution worker for ':buildSrc' Thread 7,5,main]) started.

Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
> Task :buildSrc:compileMinimumRuntimeGroovy
Task ':buildSrc:compileMinimumRuntimeGroovy' is not up-to-date because:
  No history is available.
Starting process 'Gradle Worker Daemon 1'. Working directory: /private/var/lib/jenkins/.gradle/workers Command: /private/var/lib/jenkins/.java/oracle-11+28-darwin/bin/java --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED @/private/var/folders/l4/_7k_f5s96kl8dgc3pgw01dqr0000l_/T/gradle-worker-classpath3710403816219098951txt -Xmx512m -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Worker Daemon 1'
Successfully started process 'Gradle Worker Daemon 1'


> Task :buildSrc:compileMinimumRuntimeGroovy FAILED
FAILURE: Build failed with an exception.
:buildSrc:compileMinimumRuntimeGroovy (Thread[Execution worker for ':buildSrc' Thread 7,5,main]) completed. Took 2 mins 0.313 secs.

* What went wrong:
Execution failed for task ':buildSrc:compileMinimumRuntimeGroovy'.
> Failed to run Gradle Worker Daemon
   > Unable to connect to the child process 'Gradle Worker Daemon 1'.
     It is likely that the child process have crashed - please find the stack trace in the build log.
     This exception might occur when the build machine is extremely loaded.
     The connection attempt hit a timeout after 120.0 seconds (last known process state: STARTED, running: true).

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':buildSrc:compileMinimumRuntimeGroovy'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:96)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:65)
	at org.gradle.api.internal.tasks.execution.ActionEventFiringTaskExecuter.execute(ActionEventFiringTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.TimeoutTaskExecuter.execute(TimeoutTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.SnapshotAfterExecutionTaskExecuter.execute(SnapshotAfterExecutionTaskExecuter.java:38)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:49)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:61)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:49)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:44)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:337)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:325)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:318)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:304)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.process.internal.worker.WorkerProcessException: Failed to run Gradle Worker Daemon
	at org.gradle.process.internal.worker.WorkerProcessException.runFailed(WorkerProcessException.java:29)
	at org.gradle.process.internal.worker.DefaultMultiRequestWorkerProcessBuilder$1.invoke(DefaultMultiRequestWorkerProcessBuilder.java:139)
	at com.sun.proxy.$Proxy56.start(Unknown Source)
	at org.gradle.workers.internal.WorkerDaemonStarter.startDaemon(WorkerDaemonStarter.java:52)
	at org.gradle.workers.internal.WorkerDaemonClientsManager.reserveNewClient(WorkerDaemonClientsManager.java:106)
	at org.gradle.workers.internal.WorkerDaemonFactory$1.execute(WorkerDaemonFactory.java:46)
	at org.gradle.workers.internal.WorkerDaemonFactory$1.execute(WorkerDaemonFactory.java:58)
	at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler.execute(AbstractDaemonCompiler.java:54)
	at org.gradle.api.internal.tasks.compile.NormalizingGroovyCompiler.delegateAndHandleErrors(NormalizingGroovyCompiler.java:122)
	at org.gradle.api.internal.tasks.compile.NormalizingGroovyCompiler.execute(NormalizingGroovyCompiler.java:54)
	at org.gradle.api.internal.tasks.compile.NormalizingGroovyCompiler.execute(NormalizingGroovyCompiler.java:39)
	at org.gradle.api.internal.tasks.compile.AnnotationProcessorDiscoveringCompiler.execute(AnnotationProcessorDiscoveringCompiler.java:51)
	at org.gradle.api.internal.tasks.compile.AnnotationProcessorDiscoveringCompiler.execute(AnnotationProcessorDiscoveringCompiler.java:37)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:39)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:27)
	at org.gradle.api.tasks.compile.GroovyCompile.compile(GroovyCompile.java:77)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:48)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:704)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:671)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:117)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:106)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:85)
	... 35 more
Caused by: org.gradle.process.internal.ExecException: Unable to connect to the child process 'Gradle Worker Daemon 1'.
It is likely that the child process have crashed - please find the stack trace in the build log.
This exception might occur when the build machine is extremely loaded.
The connection attempt hit a timeout after 120.0 seconds (last known process state: STARTED, running: true).
	at org.gradle.process.internal.worker.DefaultWorkerProcess.doStart(DefaultWorkerProcess.java:188)
	at org.gradle.process.internal.worker.DefaultWorkerProcess.start(DefaultWorkerProcess.java:164)
	at org.gradle.process.internal.worker.DefaultWorkerProcessBuilder$MemoryRequestingWorkerProcess.start(DefaultWorkerProcessBuilder.java:221)
	at org.gradle.process.internal.worker.DefaultMultiRequestWorkerProcessBuilder$1.invoke(DefaultMultiRequestWorkerProcessBuilder.java:137)
	... 66 more


* Get more help at https://help.gradle.org

BUILD FAILED in 2m 4s
```

</details>

**Comment by atorok** [comment] 2018-12-19 05:54
I think I saw this  with Gradle once or twice before (in my lifetime, not in CI), but there's nothing in the gradle issues either, supposedly because it doesn't reproduce.  
It's good to have a trace for it, so thanks for reporting, but I propose we close this and reopen if it happens again, and then we can spend the time  to dig into it and try to reproduce it.

**Closed** 2018-12-20 17:07 UTC
Labels: :Core/Infra/Build, >test-failure
