### ISSUE TITLE
Remove deprecated script parsing

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#15849] opened 2016-01-08 03:09 UTC
The notes in the code say that the script parsing will go in 2.0 but its still there. I mean `SCRIPT_LANG`, `SCRIPT_FILE`, `SCRIPT_ID`, and `SCRIPT_INLINE`.

**Comment by nik9000** [comment] 2016-01-08 03:10
@colings86 I see your name coming up in git-blame on this code. Is this something you can do easily? Like, if its not that much work.

**Comment by clintongormley** [comment] 2016-03-01 11:54
Related to https://github.com/elastic/elasticsearch/issues/13729

**Comment by clintongormley** [comment] 2016-05-07 15:38
Duplicate of https://github.com/elastic/elasticsearch/issues/13729

**Closed by clintongormley** 2016-05-07 15:38 UTC
Labels: :Scripting, adoptme, non-issue, v5.0.0
