### ISSUE TITLE
EQL: Sequences should early terminate if any subqueries are empty 

### ISSUE THREAD

**Issue by rw-access** [elastic/elasticsearch#60768] opened 2020-08-05 17:18 UTC
I noticed with some EQL testing that it can spend forever searching on sequences that it clearly can't complete.

This sequence will early terminate because the first subquery is never satisfied. 
```json
{
    "query": """
      sequence
        [any where event.category == 'categorythatdoesnotexist']
        [any where event.category != null]
    """,
    "size": 1
}
```

This sequence will run until it has processed all documents with `event.category`. We should be able to detect that no sequences are possible because `any where event.category == 'categorythatdoesnotexist'` will return `hits.total.value = 0` on its first page and there are no more sequences to find.
 
```json
{
    "query": """
      sequence
        [any where event.category != null]
        [any where event.category == 'categorythatdoesnotexist']
    """,
    "size": 1
}
```

**Comment by costin** [comment] 2020-08-12 10:21
Thanks - this is a good constraint to add. Similar to #58937

**Comment by costin** [comment] 2020-08-14 11:54
Looking closer at the issue I don't see much that we can. The queries are valid and we don't have any cheap way of knowing that the second query will match or not.
Some kind of heuristic/stats would be helpful here - we could do a `count` however that is not cheap.

We could try and based on the expression _guess_ how expensive the queries will be however realistically that works only if the data is evenly distributed which is rarely the case.
For example in example above the category might be in general null and have only a few actual values - that is it is quite possible that the first query is cheap/has few results while the latter a lot more.

Without proper information from the execution engine/storage, from a query point of view there's not much we can do in planning the query.
/cc @jpountz

**Comment by rw-access** [comment] 2020-08-14 13:45
I think there are a lot of options, and I'm not totally familiar with the current algorithm we use for sequencing, to be honest.

I'm not attached to the specifics of how it's done, but I do think that something should be done. The alternative is that we waste a lot of cycles and memory ingesting events that are guaranteed to never match.

**Comment by rw-access** [comment] 2021-07-01 04:29
Just checking in again to see if this has been indirectly addressed. Any update here or way to bail out early?

**Comment by astefan** [comment] 2021-07-26 10:56
No updates on this issue.
From what I can see, we can bail out earlier only if we add an additional query (a _count query like @costin said) and only for the first query in the sequence. We cannot early check the other ones because those depend on the previous queries' results.

**Comment by costin** [comment] 2021-08-02 13:42
I'm not aware of any quick mechanism we can do that is cheap enough to be applied all the time.
There is [`terminate_after`](https://www.elastic.co/guide/en/elasticsearch/reference/7.13/search-your-data.html#quickly-check-for-matching-docs) however the issue is whether it makes sense to apply it all the time.
Ideally it should be added only for cases where there are a lot of hits on one query while the latter has few/no results - it's not just about skipping the query but rather moving the matching window in the future.

**Comment by astefan** [comment] 2022-09-06 11:14
Closing this one. There are no recent updates and no immediate future plans for short terminating a running sequence query.

**Closed by astefan** 2022-09-06 11:14 UTC
Labels: :Query Languages/EQL, Team:QL
