### ISSUE TITLE
Script fields on missing values do not work even with the suggsted size() workaround

### ISSUE THREAD

**Issue by spansh** [elastic/elasticsearch#41323] opened 2019-04-18 02:23 UTC
**Elasticsearch version** (`bin/elasticsearch --version`):

7.0.0

**Plugins installed**: []
None

**JVM version** (`java -version`):
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.16.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux Ubuntu-1604-xenial-64-minimal-no-hwe 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
The recent changes to painless scripting say that fields without values now produce an error for me, which would be fine if the suggested solution worked.  

Now I'm fairly certain that the index for this query does not have any documents without values for this specific field.

```
curl -X GET "localhost:9200/systems/_search" -H 'Content-Type: application/json' -d'
{
    "query": {
        "bool": {
            "must_not": {
                "exists": {
                    "field": "x"
                }
            }
        }
    }
}
'
```

produces no values (changing the fieldname to something random does).  Lets assume for now that there are some empty fields somewhere (possibly in nested documents?).

However I get the following error using my painless script:

```
# {
#    "error" : {
#       "failed_shards" : [
#          {
#             "node" : "aLP3EUguSqiaEs1O1Nu9_Q",
#             "reason" : {
#                "lang" : "painless",
#                "script_stack" : [
#                   "org.elasticsearch.index.fielddata.ScriptDocValues$Doubles.get(ScriptDocValues.java:249)",
#                   "org.elasticsearch.index.fielddata.ScriptDocValues$Doubles.getValue(ScriptDocValues.java:243)",
#                   "x = 0 - doc['x'].value;\n                    double ",
#                   "                ^---- HERE"
#                ],
#                "caused_by" : {
#                   "type" : "illegal_state_exception",
#                   "reason" : "A document doesn't have a value for a field! Use doc[<field>].size()==0 to check if a document is missing a field!"
#                },
#                "type" : "script_exception",
#                "script" : "\n                    double x = 0 - doc['x'].value;\n                    double y = 0 - doc['y'].value;\n                    double z = 0 - doc['z']
.value;\n                    double distance = x*x + y*y + z*z;\n                    return (distance <= 250000d);\n                ",
#                "reason" : "runtime error"
#             },
#             "shard" : 0,
#             "index" : "systems_1555494707"
#          }
#       ],
#       "reason" : "all shards failed",
#       "root_cause" : [
#          {
#             "reason" : "runtime error",
#             "script" : "\n                    double x = 0 - doc['x'].value;\n                    double y = 0 - doc['y'].value;\n                    double z = 0 - do[23/1817]
lue;\n                    double distance = x*x + y*y + z*z;\n                    return (distance <= 250000d);\n                ",
#             "lang" : "painless",
#             "type" : "script_exception",
#             "script_stack" : [
#                "org.elasticsearch.index.fielddata.ScriptDocValues$Doubles.get(ScriptDocValues.java:249)",
#                "org.elasticsearch.index.fielddata.ScriptDocValues$Doubles.getValue(ScriptDocValues.java:243)",
#                "x = 0 - doc['x'].value;\n                    double ",
#                "                ^---- HERE"
#             ]
#          }
#       ],
#       "phase" : "query",
#       "grouped" : true,
#       "type" : "search_phase_execution_exception"
#    },
#    "status" : 400
# }
```

If I put the suggested fix in place, I get the following error:
```
# {
#    "status" : 400,
#    "error" : {
#       "type" : "search_phase_execution_exception",
#       "phase" : "query",
#       "root_cause" : [
#          {
#             "script" : "\n                    if (doc['x'].value.size() == 0 || doc['y'].value.size() == 0 || doc['z'].value.size() == 0) {\n                        return fals
e;\n                    }\n                    double x = 0 - doc['x'].value;\n                    double y = 0 - doc['y'].value;\n                    double z = 0 - doc['z'].val
ue;\n                    double distance = x*x + y*y + z*z;\n                    return (distance <= 250000d);\n                ",
#             "reason" : "runtime error",
#             "type" : "script_exception",
#             "script_stack" : [
#                "if (doc['x'].value.size() == 0 || doc['y'].value.size() == 0 || doc['z'].value.size() == 0) {\n                        ",
#                "                  ^---- HERE"
#             ],
#             "lang" : "painless"
#          }
#       ],
#       "grouped" : true,
#       "reason" : "all shards failed",
#       "failed_shards" : [
#          {
#             "index" : "systems_1555494707",
#             "shard" : 0,
#             "reason" : {
#                "type" : "script_exception",
#                "lang" : "painless",
#                "script_stack" : [
#                   "if (doc['x'].value.size() == 0 || doc['y'].value.size() == 0 || doc['z'].value.size() == 0) {\n                        ",
#                   "                  ^---- HERE"
#                ],
#                "caused_by" : {
#                   "type" : "illegal_argument_exception",
#                   "reason" : "dynamic method [java.lang.Double, size/0] not found"
#                },
#                "script" : "\n                    if (doc['x'].value.size() == 0 || doc['y'].value.size() == 0 || doc['z'].value.size() == 0) {\n                        return f
alse;\n                    }\n                    double x = 0 - doc['x'].value;\n                    double y = 0 - doc['y'].value;\n                    double z = 0 - doc['z'].
value;\n                    double distance = x*x + y*y + z*z;\n                    return (distance <= 250000d);\n                ",
#                "reason" : "runtime error"
#             },
#             "node" : "aLP3EUguSqiaEs1O1Nu9_Q"
#          }
#       ]
#    }
# }
```

The field is just declared as a double field and none of the records have multiple values, and every record should have that field).

**Steps to reproduce**:

I don't really have time to produce this now but I suspect it should be relatively easy (I;m hurriedly degrading elasticsearch as I don't think I can script around this).

**Provide logs (if relevant)**:

**Comment by spansh** [comment] 2019-04-18 02:41
OK, after reading through more documents this looks to be somewhat of a different issue.  The documents suggest a different route to the error message by using doc.containsKey('field').  I implemented this and it appears that as far as painless is concerned, none of my documents have that field.

I can search on it fine and when I use it in other fields (I have a calculated distance field which returns perfectly fine) so the document values have definitely been stored (I never set that explicitly so it's defaulted).

The mapping is here
```
curl -X GET "localhost:9200/systems/_mapping"
{"systems_1555494707":{"mappings":{"properties":{"allegiance":{"type":"text","fields":{"keyword":{"type":"keyword","eager_global_ordinals":true}}},"bodies":{"type":"nested","properties":{"distance_to_arrival":{"type":"double"},"edsm_id":{"type":"keyword"},"estimated_mapping_value":{"type":"long"},"estimated_scan_value":{"type":"long"},"id":{"type":"keyword"},"id64":{"type":"keyword"},"is_main_star":{"type":"boolean"},"name":{"type":"text","fields":{"keyword":{"type":"keyword"},"suggest":{"type":"text","analyzer":"autocomplete","search_analyzer":"standard"}}},"subtype":{"type":"text","fields":{"keyword":{"type":"keyword"}}},"terraforming_state":{"type":"text","fields":{"keyword":{"type":"keyword"}}},"type":{"type":"text","fields":{"keyword":{"type":"keyword"}}}}},"controlling_minor_faction":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"edsm_id":{"type":"long"},"estimated_scan_value":{"type":"long"},"government":{"type":"text","fields":{"keyword":{"type":"keyword","eager_global_ordinals":true}}},"id":{"type":"keyword"},"id64":{"type":"keyword"},"minor_faction_presence":{"properties":{"influence":{"type":"float"},"name":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"state":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}}}},"minor_faction_presences":{"type":"nested","properties":{"influence":{"type":"double"},"name":{"type":"text","fields":{"keyword":{"type":"keyword"}}},"state":{"type":"text","fields":{"keyword":{"type":"keyword"}}}}},"name":{"type":"text","fields":{"keyword":{"type":"keyword"},"lkeyword":{"type":"keyword","normalizer":"lowercase"},"suggest":{"type":"text","analyzer":"autocomplete","search_analyzer":"standard"}}},"needs_permit":{"type":"boolean"},"population":{"type":"long"},"power":{"type":"text","fields":{"keyword":{"type":"keyword","eager_global_ordinals":true}}},"power_state":{"type":"text","fields":{"keyword":{"type":"keyword","eager_global_ordinals":true}}},"primary_economy":{"type":"text","fields":{"keyword":{"type":"keyword","eager_global_ordinals":true}}},"secondary_economy":{"type":"text","fields":{"keyword":{"type":"keyword","eager_global_ordinals":true}}},"security":{"type":"text","fields":{"keyword":{"type":"keyword","eager_global_ordinals":true}}},"state":{"type":"text","fields":{"keyword":{"type":"keyword","eager_global_ordinals":true}}},"x":{"type":"double"},"y":{"type":"double"},"z":{"type":"double"}}}}}
```

**Comment by spansh** [comment] 2019-04-18 03:30
I've managed to put a workaround in which avoids the problem but I'm still not sure what causes it.

The workaround is (using the same example above)

```
curl -H "Content-type: application/json" -XGET 'http://localhost:9200/systems/_search?pretty=true&size=100' -d '
{
   "query" : {
      "bool" : {
         "must" : [
            {
               "script" : {
                  "script" : {
                     "source" : "if (doc.x.size() == 0 || doc.y.size() == 0 || doc.z.size() == 0) {return false}\n                    double dx = -9530.5 - 0;\n                    double dy = -910.28125 - 0;\n                    double dz = 19808.125 - 0;\n\n                    double lengthsq = dx*dx + dy*dy + dz*dz;\n\n                    double pdx = doc[\u0027x\u0027].value - 0;\n                    double pdy = doc[\u0027y\u0027].value - 0;\n                    double pdz = doc[\u0027z\u0027].value - 0;\n\n                    double dot = pdx * dx + pdy * dy + pdz * dz;\n\nif ( dot < 0 || dot > lengthsq) {\n                        return false;\n                    }\n\n                    double dsq = (pdx*pdx + pdy*pdy + pdz*pdz) - dot*dot/lengthsq;\n                    if (dsq > 250000d) {\n                        return false;\n                    }\n\n                    return true;\n                 ",
                     "lang" : "painless"
                  }
               }
            },
            {
               "nested" : {
                  "query" : {
                     "function_score" : {
                        "script_score" : {
                           "script" : "doc[\u0027bodies.estimated_scan_value\u0027].value"
                        },
                        "score_mode" : "sum"
                     }
                  },
                  "inner_hits" : {
                     "size" : 20
                  },
                  "path" : "bodies",
                  "score_mode" : "sum"
               }
            }
         ]
      }
   }
}
'
```

**Comment by jimczi** [comment] 2019-04-18 08:24
The syntax to check if the field has values is:
````
doc['x'].size()
````
`doc['x'].value` is not a list, it is a pointer to the first value. I also tried your example with nested values and it worked fine, same for `doc.containsKey('x')`. 
The forum is better suited for this kind of discussion so I hope you don't mind if I close this issue since we reserve github for verified bugs and feature request. Please open a topic in the [forum](https://discuss.elastic.co/c/elasticsearch) (you can post the link here) if you have further questions and we'll be happy to help there.

**Closed by jimczi** 2019-04-18 08:24 UTC

**Comment by spansh** [comment] 2019-04-18 09:13
> The syntax to check if the field has values is:
> 
> ```
> doc['x'].size()
> ```
> `doc['x'].value` is not a list, it is a pointer to the first value. I also tried your example with nested values and it worked fine, same for `doc.containsKey('x')`.
> The forum is better suited for this kind of discussion so I hope you don't mind if I close this issue since we reserve github for verified bugs and feature request. Please open a topic in the [forum](https://discuss.elastic.co/c/elasticsearch) (you can post the link here) if you have further questions and we'll be happy to help there.

That syntax does not work as I have discussed above.  The only syntax which worked was doc.x.size().  Also it does not cover the fact that this does not occur if I remove the nested field query (none of my documents are missing the x field.

**Comment by jimczi** [comment] 2019-04-18 09:44
> If I have some more time I can generate a dataset which replicates the issue directly. If nothing else then the error message is wrong (it cost me several hours very early this morning).

According to the message you posted, you tried with `doc['x'].value.size()` instead of `doc['x'].size()` and that explains why you got the issue. The error message says that the syntax is ` doc[<field>].size()==0 `.
Regarding your `nested` query I tried the following reproduction:

````
PUT test
{
    "mappings": {
        "properties": {
            "bodies": {
                "type": "nested",
                "properties": {
                    "estimated_scan_value": {
                        "type": "long"
                    }
                }
            },
            "x": {
                "type": "double"
            }
        }
    }
}

# Add one document with a "x" field and a nested array
POST test/_doc
{
    "x": 1,
    "bodies": [
        {
            "estimated_scan_value": 100
        },
        {
            "estimated_scan_value": 200
        }
    ]
}

# And another one with the "x" field missing
POST test/_doc
{
    "bodies": [
        {
            "estimated_scan_value": 10
        },
        {
            "estimated_scan_value": 20
        }
    ]
}

POST test/_search
{
   "query" : {
      "bool" : {
         "must" : [
            {
               "script" : {
                  "script" : {
                     "source" : "if (doc['x'].size() > 0) { return true }",
                     "lang" : "painless"
                  }
               }
            },
            {
               "nested" : {
                  "query" : {
                     "function_score" : {
                        "script_score" : {
                           "script" : "doc['bodies.estimated_scan_value'].value"
                        },
                        "score_mode" : "sum"
                     }
                  },
                  "inner_hits" : {
                     "size" : 20
                  },
                  "path" : "bodies",
                  "score_mode" : "sum"
               }
            }
         ]
      }
   }
}

# returns:
{
    "took": 11,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": {
            "value": 1,
            "relation": "eq"
        },
        "max_score": 301,
        "hits": [
            {
                "_index": "test",
                "_type": "_doc",
                "_id": "kerSL2oBZDJG1nHfJjH4",
                "_score": 301,
                "_source": {
                    "x": 10,
                    "bodies": [
                        {
                            "estimated_scan_value": 100
                        },
                        {
                            "estimated_scan_value": 200
                        }
                    ]
                },
                "inner_hits": {
                    "bodies": {
                        "hits": {
                            "total": {
                                "value": 2,
                                "relation": "eq"
                            },
                            "max_score": 200,
                            "hits": [
                                {
                                    "_index": "test",
                                    "_type": "_doc",
                                    "_id": "kerSL2oBZDJG1nHfJjH4",
                                    "_nested": {
                                        "field": "bodies",
                                        "offset": 1
                                    },
                                    "_score": 200,
                                    "_source": {
                                        "estimated_scan_value": 200
                                    }
                                },
                                {
                                    "_index": "test",
                                    "_type": "_doc",
                                    "_id": "kerSL2oBZDJG1nHfJjH4",
                                    "_nested": {
                                        "field": "bodies",
                                        "offset": 0
                                    },
                                    "_score": 100,
                                    "_source": {
                                        "estimated_scan_value": 100
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        ]
    }
}
````
So everything seems to work fine. If I am missing anything please provide a simple reproduction that exhibits the issue.

**Comment by spansh** [comment] 2019-04-18 10:00
You are correct, I must have mistyped doc['x'].values.size() numerous times (even though I knew it was .size() without the value.  I was somewhat paniced as my site was basically down at this point and it would have been a 10 hour reindex to bring it back up) however I have posted exact replication steps in the forum thread I created https://discuss.elastic.co/t/issues-with-7-0-0-nested-script-query/177422 including sample data.
