### ISSUE TITLE
MixedClusterClientYamlTestSuiteIT fails periodically with timeout

### ISSUE THREAD

**Issue by BigPandaToo** [elastic/elasticsearch#70204] opened 2021-03-10 09:44 UTC
**Build scan**:
https://gradle-enterprise.elastic.co/s/uqlcjcsarbryg

**Repro line**:
REPRODUCE WITH: gradlew ':qa:mixed-cluster:v6.8.15#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=indices.get_alias/10_basic/Get alias against closed indices}" -Dtests.seed=BCA8156C77FE6D19 -Dtests.security.manager=true -Dtests.bwc=true -Dtests.locale=de-CH -Dtests.timezone=America/Regina -Druntime.java=8

**Reproduces locally?**:
No

**Applicable branches**:
7.x

**Failure history**:
Fails periodically with either: Test abandoned because suite timeout was reached
or: Suite timeout exceeded (>= 1800000 msec).

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-60d,mode:quick,to:now))&_a=(columns:!(branch,message),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:MixedClusterClientYamlTestSuiteIT),sort:!(time,desc))

**Failure excerpt**:
org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT > classMethod FAILED
    java.lang.Exception: Suite timeout exceeded (>= 1800000 msec).
        at __randomizedtesting.SeedInfo.seed([BCA8156C77FE6D19]:0)
REPRODUCE WITH: gradlew ':qa:mixed-cluster:v6.8.15#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=indices.get_alias/10_basic/Get alias against closed indices}" -Dtests.seed=BCA8156C77FE6D19 -Dtests.security.manager=true -Dtests.bwc=true -Dtests.locale=de-CH -Dtests.timezone=America/Regina -Druntime.java=8

**Comment by BigPandaToo** [comment] 2021-03-10 09:45
@rjernst assigning to you as you seems to worked on this issue before. Not muting the test as it only fails periodically

**Comment by BigPandaToo** [comment] 2021-03-10 16:05
More failures today: https://gradle-enterprise.elastic.co/s/2bbek5f3ejznm

**Comment by mark-vieira** [comment] 2021-03-11 21:38
Closing this as a duplicate of https://github.com/elastic/elasticsearch/issues/69973. Let's continue the discussion there.

**Closed by mark-vieira** 2021-03-11 21:38 UTC
Labels: >test-failure, Team:Core/Infra, v7.11.0, v7.12.0
