### ISSUE TITLE
Allow to partially query an adjacency matrix

### ISSUE THREAD

**Issue by flash1293** [elastic/elasticsearch#46213] opened 2019-09-01 09:31 UTC
## Idea

Currently it is possible to fetch the adjacency matrix for a given set of filters. However it is necessary to always fetch the complete matrix, e.g. for filters `filter0` up to `filter99` all possible pairings will be returned. In some cases it would be helpful to be able to only fetch a portion of the adjacency matrix.

This would allow a user to
* Incrementally query a very big adjacency matrix (thousands of filters), similar to how scroll searches and composite aggregations work today
* Save computation when filters are added to a matrix already fetched in previous requests (e.g. user fetches a matrix for `filter0` up to `filter99` and after looking at the results decides to also add `filter100` and `filter101`)

Computational and memory costs are mostly saved because not all possible pairings between filters have to be considered while calculating the matrix. This should be especially relevant in cases where costly child aggregations are done as part of the matrix aggregation.

### Nested filters

It is possible to do the same thing by nesting filter aggregations, e.g. in the use case from above "user fetches a matrix for `filter0` up to `filter99` and after looking at the results decides to also add `filter100` and `filter101`" it would be possible to do a filter aggregation for `filter100` and `filter101`, then having a nested filter aggregation for `filter0` up to `filter99` below that. The downside of this approach (besides possible performance problems I didn't test for yet) is that some pairings are calculated multiple times (`filter100 & filter101` vs `filter101 & filter100`). This problem gets worse if there is more overlap between the two sets of filters.

### Scope down to new filters

Again using the example from above, it would also be possible to use an adjacency matrix aggregation for `filter0` up to `filter101`, but scoping down the entire search to `filter100 OR filter101`. As long as all filters only operate on non-array fields, this should result in the same result as querying a partial adjacency matrix. However this approach would easily run into the limit of allowed filters per adjacency matrix aggregation even though the intended query would include way less data. Additionally lots of impossible pairings (e.g. `filter4 & filter55`) are considered during the calculation.

## API proposal

I propose to backwards-compatible extend the existing `adjacency_matrix` aggregation by adding an array property of filters for both selected rows and columns of the matrix.

```json
{
  "interactions": {
    "adjacency_matrix": {
      "filters": {
        "grpA": { "terms": { "accounts": ["hillary", "sidney"] } },
        "grpB": { "terms": { "accounts": ["donald", "mitt"] } },
        "grpC": { "terms": { "accounts": ["vladimir", "nigel"] } }
      },
      "columns": ["grpC"],
      "rows": ["grpA", "grpB", "grpC"]
    }
  }
}
```

Only pairings in the intersection of the row and column selector are returned to the user. If a selector is omitted, it falls back to all given filters, ensured backwards compatibility.

The downside of this API is that it's not trivial to efficiently query a very big adjacency matrix in an incremental fashion (keeping all requests around the same size and don't fetch the same data twice), however this could be implemented in a client library if the need arises.

## Settings

The `index.max_adjacency_matrix_filters` setting limits the number of filters in an adjacency matrix. It could continue to work in the exact same way is it currently does (limiting the number of specified filters), however that would be unnecessarily constraining because depending on rows and columns selectors only a small portion of the matrix is actually queried.

Ideally the limit should be applied to the product of selected rows and columns minus duplicates because of the symmetry of the matrix (maybe `index.max_adjacency_matrix_size`, defaulting to `5050` which is the current limit after considering duplicates), however that would make a breaking change necessary. This could be made part of the 8.0 release.

Considering duplicates in the calculation of the limit might be technically correct, but it's maybe too confusing to calculate, another option would be to simply not consider them in the limit and making sure to pick a default that also works for the worst case (no duplicates in rows and columns selector).

There is also the option to have a separate aggregation `partial_adjacency_matrix`, then limiting the product of rows and columns could be introduced in a minor version.

cc @markharwood 

Also see https://github.com/elastic/elasticsearch/issues/46212

**Comment by markharwood** [comment] 2019-09-03 13:01
Thanks for this write-up, @flash1293 

If https://github.com/elastic/elasticsearch/pull/46257 is adopted then we eliminate the exponential growth of RAM with number of filters. I suspect that means the role of `index.max_adjacency_matrix_filters` becomes similar to that of `indices.query.bool.max_clause_count ` in limiting disk seeks. 
The limit on RAM usage caused by many intersections I would expect to be controlled by the existing `search.max_buckets` (PR 46257 eliminates the additional RAM usage that is untracked by this setting).

When it comes to asking for a partial adjacency_matrix do you need both the `columns` and `rows` params? Do you not just need a single array of filter IDs representing the new additions to a client-side graph?

**Comment by flash1293** [comment] 2019-09-04 08:50
Hi @markharwood The limit settings make sense, thanks for looking into that and thanks for the super fast PR.

> When it comes to asking for a partial adjacency_matrix do you need both the columns and rows params? Do you not just need a single array of filter IDs representing the new additions to a client-side graph?

For new additions it works fine but not for incrementally (step by step)  fetching a large matrix - in this case we would fetch almost twice as much as necessary.

Consider the following matrix - the blue cells are the ones potentially containing data
<img width="487" alt="Screenshot 2019-09-04 at 10 34 16" src="https://user-images.githubusercontent.com/1508364/64239464-92b81d00-cf00-11e9-9bc6-897d463e6398.png">

Let's say we want to scan through the matrix three columns at a time. We would start like this (`"columns": ["A", "B", "C"]`), only getting the cells we wanted:
<img width="488" alt="Screenshot 2019-09-04 at 10 34 38" src="https://user-images.githubusercontent.com/1508364/64239547-bc714400-cf00-11e9-8bc3-b2eb28da9f53.png">

Next request would be `"columns": ["D", "E", "F"]` - however the server doesn't now the order of the columns (because `filters` is an object with no guaranteed order), so it has to assume we want all possible pairings with `D`, `E` and `F`:
<img width="484" alt="Screenshot 2019-09-04 at 10 45 30" src="https://user-images.githubusercontent.com/1508364/64239776-22f66200-cf01-11e9-92fe-99ddb86302b6.png">

This would also return the block highlighted in red, because the second request doesn't know we already got these cells in the first request (highlighted in darker shade).

If the user can specify columns and rows, they can tell the server to omit the "red" part of the matrix:
```
"columns": ["D", "E", "F"],
"rows": ["D", "E", "F", ..., "Q"]
```

**Comment by markharwood** [comment] 2020-06-24 14:57
This one has gone cold so closing - we can always reopen if required @flash1293

**Closed by markharwood** 2020-06-24 14:57 UTC
Labels: :Analytics/Aggregations, Team:Analytics
