### ISSUE TITLE
CIDR support for range/term query when searching an ip_range typed field

### ISSUE THREAD

**Issue by ZLightning** [elastic/elasticsearch#85037] opened 2022-03-16 15:27 UTC
### Description

When searching an ip data type field, the following query works as expected:
```JSON
{
  "query": {
    "term": {
      "ip": "1.2.3.0/24"
    }
  }
}
```
But the same query on a cidr field returns: ` "reason" : "failed to create query: '1.2.3.0/24' is not an IP string literal."`

Personally, I disagree with the idea that a term query is the appropriate query type for either ip or ip_range fields when searching with a CIDR.  I have come to expect term queries to be low level queries that do not expand terms in any way, and the CIDR notation on ip fields seems at odds with that.  However, ip_range fields accept CIDR notation, and I think range queries should accept CIDR notation too (for both ip and ip_range types).  What I think would make the most sense on an ip_range field would be if a term query accepted a CIDR and found exact matches for the range only, while a range query would find documents that intersect with the range.  The object notation for a range query would need the `value` field added for the range as CIDR.  That would allow for controlling the relation and boost parameters without having to compute the IP range values manually.

**Comment by javanna** [comment] 2024-07-17 18:42
Closing as duplicate of #89698

**Closed by javanna** 2024-07-17 18:42 UTC
Labels: >enhancement, :Search Foundations/Mapping, Team:Search
