### ISSUE TITLE
Unable to index IPv6 network address - '2001:db8::/48' is not an IP string literal.

### ISSUE THREAD

**Issue by scibi** [elastic/elasticsearch#27064] opened 2017-10-20 16:40 UTC
**Elasticsearch version** (`bin/elasticsearch --version`):

```
Version: 5.6.3, Build: 1a2f265/2017-10-06T20:33:39.012Z, JVM: 1.8.0_141
```

**Plugins installed**:

```
x-pack
```

**JVM version** (`java -version`):

```
openjdk version "1.8.0_141"
OpenJDK Runtime Environment (build 1.8.0_141-8u141-b15-1~deb9u1-b15)
OpenJDK 64-Bit Server VM (build 25.141-b15, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system):

Debian 9.2

```
Linux some.host.name 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux
```

I'm trying to index IPv6 network addresses. Unfortunately ES returns an error: `'2001:db8::/48' is not an IP string literal`.

**Steps to reproduce**:

1. Create template:

```
PUT _template/test_ip
{
  "template": "test_ip",
  "mappings": {
    "test_ip": {
      "_all": { "enabled": false  },
      "properties": {
        "ip_address": {
          "type": "ip"
        }
      }
    }
  }
}
````
2. Try to index document:

```
POST test_ip/test_ip/
{"ip_address": "2001:db8::/48"}
```

3. ES returns an error:

```
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "failed to parse [ip_address]"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "failed to parse [ip_address]",
    "caused_by": {
      "type": "illegal_argument_exception",
      "reason": "'2001:db8::/48' is not an IP string literal."
    }
  },
  "status": 400
}
```

**Comment by scibi** [comment] 2017-10-20 20:28
Ok - I've checked documentation once again and looked at the code. IP networks are supported only in queries. So I'm I guess this issue should be changed to feature request...

**Comment by spinscale** [comment] 2017-10-23 12:11
we support the [ip_range datatype](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/range.html), which allows you to store ranges in a slightly different way. Would that work for you?

We still could consider this a feature request to automatically create a range out of the above notation I assume.

**Comment by jpountz** [comment] 2017-10-25 13:01
Closing as duplicate of #26260 then.

**Closed by jpountz** 2017-10-25 13:01 UTC
Labels: :Mapping, enhancement
