### ISSUE TITLE
[Docs] Github Edit button opens incorrect file since 6.3

### ISSUE THREAD

**Issue by jen-huang** [elastic/elasticsearch#30883] opened 2018-05-25 17:13 UTC
https://www.elastic.co/guide/en/elasticsearch/reference/master/search-aggregations-metrics-min-aggregation.html

`The min aggregation can also calculate the maximum of a script.`
should be
`The min aggregation can also calculate the minimum of a script.`

In addition, the `Edit` button doesn't open the right file on `master`. The same page on `6.2` does however.

**Comment by cbuescher** [comment] 2018-05-28 07:35
@jen-huang thanks for catching this, also I can conform the edit button isn't working the way it should for me either. I will open a quick PR to fix the typo you mentioned and check if the edit button issue is already worked on.

**Comment by cbuescher** [comment] 2018-05-28 07:44
Opened #30899 for the typo, will change the labeling and title slightly to track the non-working edit buttons

**Comment by cbuescher** [comment] 2018-05-28 07:51
Most of the reference documentations Edit buttons all link to the elasticsearch/x-pack/docs/en/security/securing-communications/tls-ldap.asciidoc page, starting with versions 6.3 it seems.

**Comment by cbuescher** [comment] 2018-05-28 08:02
Git show that most of the broken links got changed by the Docs User bot in 87e587a5f20b8a3752383f893166184a8336f8ef, so I suspect some slightly earlier changes to be the cause.

**Comment by cbuescher** [comment] 2018-05-28 08:04
@lcawl can you take a look what changed in the build and either correct or reassign?

**Closed** 2018-05-29 15:16 UTC
Labels: :Docs, >bug, >docs, v6.3.1, v6.4.0, v7.0.0
