### ISSUE TITLE
[CI] CcrRepositoryIT.testIndividualActionsTimeout failing

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#42499] opened 2019-05-24 09:28 UTC
## Example build failure
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.1+multijob-darwin-compatibility/44/console

## Reproduction line 
does not reproduce locally
```
./gradlew :x-pack:plugin:ccr:internalClusterTest --tests "org.elasticsearch.xpack.ccr.CcrRepositoryIT.testIndividualActionsTimeout" \
  -Dtests.seed=6123E9B46050D9D7 \
  -Dtests.security.manager=true \
  -Dtests.locale=es-CO \
  -Dtests.timezone=Australia/Victoria \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

## Example relevant log:
```
08:53:00 org.elasticsearch.xpack.ccr.CcrRepositoryIT > testRateLimitingIsEmployed FAILED
08:53:00     java.lang.RuntimeException: failed to start nodes
08:53:00 
08:53:00         Caused by:
08:53:00         java.util.concurrent.ExecutionException: java.lang.IllegalStateException: failed to connect to remote clusters
08:53:00 
08:53:00             Caused by:
08:53:00             java.lang.IllegalStateException: failed to connect to remote clusters
08:53:00 
08:53:00                 Caused by:
08:53:00                 java.util.concurrent.ExecutionException: ConnectTransportException[[leader1][127.0.0.1:63618] general node connection failure]; nested: IllegalStateException[handshake failed with {leader1}{2s-cUw54RKCqtgOy8Vxnzg}{EKfqclgcSeqevJsSBBwwTg}{127.0.0.1}{127.0.0.1:63618}{xpack.installed=true}]; nested: ReceiveTimeoutTransportException[[leader1][127.0.0.1:63618][internal:transport/handshake] request_id [4] timed out after [30054ms]];
08:53:00 
08:53:00                     Caused by:
08:53:00                     ConnectTransportException[[leader1][127.0.0.1:63618] general node connection failure]; nested: IllegalStateException[handshake failed with {leader1}{2s-cUw54RKCqtgOy8Vxnzg}{EKfqclgcSeqevJsSBBwwTg}{127.0.0.1}{127.0.0.1:63618}{xpack.installed=true}]; nested: ReceiveTimeoutTransportException[[leader1][127.0.0.1:63618][internal:transport/handshake] request_id [4] timed out after [30054ms]];
08:53:00 
08:53:00                         Caused by:
08:53:00                         java.lang.IllegalStateException: handshake failed with {leader1}{2s-cUw54RKCqtgOy8Vxnzg}{EKfqclgcSeqevJsSBBwwTg}{127.0.0.1}{127.0.0.1:63618}{xpack.installed=true}
08:53:00 
08:53:00                             Caused by:
08:53:00                             ReceiveTimeoutTransportException[[leader1][127.0.0.1:63618][internal:transport/handshake] request_id [4] timed out after [30054ms]]
08:53:04 REPRODUCE WITH: ./gradlew :x-pack:plugin:ccr:internalClusterTest --tests "org.elasticsearch.xpack.ccr.CcrRepositoryIT.testRateLimitingIsEmployed" -Dtests.seed=6123E9B46050D9D7 -Dtests.security.manager=true -Dtests.locale=es-CO -Dtests.timezone=Australia/Victoria -Dcompiler.java=12 -Druntime.java=8
08:53:04 
08:53:04 org.elasticsearch.xpack.ccr.CcrRepositoryIT > testIndividualActionsTimeout FAILED
08:53:04     java.lang.AssertionError: 
08:53:04     Expected: a value greater than <0>
08:53:04          but: <0> was equal to <0>
08:53:04         at __randomizedtesting.SeedInfo.seed([6123E9B46050D9D7:53E0568D322EBE4]:0)
08:53:04         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
08:53:04         at org.junit.Assert.assertThat(Assert.java:956)
08:53:04         at org.junit.Assert.assertThat(Assert.java:923)
08:53:04         at org.elasticsearch.xpack.ccr.CcrRepositoryIT.testIndividualActionsTimeout(CcrRepositoryIT.java:345)
```

Occurrence seems rare, not muting yet.

You can find the full logs [here](https://github.com/elastic/elasticsearch/files/3216150/CcrRepositoryIT_failure.txt.zip)

**Comment by dnhatn** [comment] 2019-05-26 14:58
> 08:53:00 org.elasticsearch.xpack.ccr.CcrRepositoryIT > testRateLimitingIsEmployed FAILED
08:53:00     java.lang.RuntimeException: failed to start nodes
08:53:00 
08:53:00         Caused by:
08:53:00         java.util.concurrent.ExecutionException: java.lang.IllegalStateException: failed to connect to remote clusters
08:53:00 

This test failed because a new node on the follower cluster could not connect to the leader cluster. @tbrooks8 Can you please take a look? Thank you!

**Comment by tbrooks8** [comment] 2019-06-14 16:37
I think this might be similar to #41071

**Comment by dnhatn** [comment] 2019-06-14 17:07
Yes, let's close this in favour of #41071.

**Closed by dnhatn** 2019-06-14 17:07 UTC
Labels: :Distributed/CCR, >test-failure
