### ISSUE TITLE
Multiple path.data can not balance data automatically among the disks

### ISSUE THREAD

**Issue by wenma** [elastic/elasticsearch#21396] opened 2016-11-08 04:31 UTC
My online environment is as follows
- **Elasticsearch version**:  v2.3.1
- **Plugins installed**: kopf, head
- **JVM version**: jdk1.8.0_91
- **OS version**: centos 7.2

On one ES node,  The `df -h` shows :
```
# df -h
...
/dev/sdb        881G  719G  117G  87% /data1
/dev/sdc        881G  728G  108G  88% /data2
/dev/sdd        881G  721G  115G  87% /data3
/dev/sde        881G  723G  113G  87% /data4
/dev/sdf        881G  700G  136G  84% /data5
/dev/sdh        881G   37G  799G   5% /data6
...
```
the device `/dev/sdh` (mount on path `/data6`) is a new device added to the ES node， After I restart the ES node,  I found ES can not balance data automatically among the disks,  Is this a bug ?  

can someone help me to solve this?

**Comment by joshuar** [comment] 2016-11-08 05:36
Hi @wenma this is expected, the behaviour of `path.data` has changed in 2.x such that it no longer stripes shards across multiple paths (like RAID0), shards are now allocated into a single data path.  Because your shards might contain different distributions of documents with different sizes, you should expect to see some variation in disk usage from this method of shard distribution at the data path level.  So this is normal.

See also the explanation in the [2.0 Breaking Changes](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/breaking_20_multiple_literal_data_path_literal_striping.html)

Closing this issue as it is expected behaviour :)

**Closed by joshuar** 2016-11-08 05:36 UTC

**Comment by wenma** [comment] 2016-11-08 07:06
@joshuar I see. now, I want to rebalance data manually,  is there a possible way to solve the situation ?
moreover，I think ES should rebalance data automatically in shards level on one ES node.
