### ISSUE TITLE
[CI] AzureBlobStoreRepositoryTests.testIndicesDeletedFromRepository

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#48978] opened 2019-11-12 09:24 UTC
Looks like a service unavailable but since the issue was raised before (#47120) I'm raising it for consistency.

CI https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/483/
Scan: https://gradle-enterprise.elastic.co/s/2nryv35jtn7lo/tests/lgycqkw2bfw46-kysdm6ag7igo6

```
Caused by: com.microsoft.azure.storage.StorageException: Service Unavailable
	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:87) ~[azure-storage-8.4.0.jar:?]
	at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:305) ~[azure-storage-8.4.0.jar:?]
	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:196) ~[azure-storage-8.4.0.jar:?]
	at com.microsoft.azure.storage.blob.CloudBlockBlob.uploadFullBlob(CloudBlockBlob.java:1035) ~[azure-storage-8.4.0.jar:?]
	at com.microsoft.azure.storage.blob.CloudBlockBlob.upload(CloudBlockBlob.java:864) ~[azure-storage-8.4.0.jar:?]
	at com.microsoft.azure.storage.blob.CloudBlockBlob.upload(CloudBlockBlob.java:743) ~[azure-storage-8.4.0.jar:?]
	at org.elasticsearch.repositories.azure.AzureStorageService.lambda$writeBlob$15(AzureStorageService.java:333) ~[main/:?]
	at org.elasticsearch.repositories.azure.SocketAccess.lambda$doPrivilegedVoidException$0(SocketAccess.java:69) ~[main/:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at org.elasticsearch.repositories.azure.SocketAccess.doPrivilegedVoidException(SocketAccess.java:68) ~[main/:?]
	at org.elasticsearch.repositories.azure.AzureStorageService.writeBlob(AzureStorageService.java:332) ~[main/:?]
	at org.elasticsearch.repositories.azure.AzureBlobStore.writeBlob(AzureBlobStore.java:119) ~[main/:?]
	at org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlob(AzureBlobContainer.java:101) ~[main/:?]
	at org.elasticsearch.repositories.blobstore.ChecksumBlobStoreFormat.lambda$write$1(ChecksumBlobStoreFormat.java:1
```

**Comment by tlrx** [comment] 2019-11-12 10:04
Mark [mentioned](https://github.com/elastic/elasticsearch/issues/47120#issuecomment-552580483) a similar build failure:

https://gradle-enterprise.elastic.co/s/42cmniylhr7g4/tests/lgycqkw2bfw46-clvf2uhrzpiw4

**Comment by tlrx** [comment] 2019-11-13 09:08
I suspect an issue on the server side logic, so I added some logging in #48991 in case it reproduces.

**Comment by romseygeek** [comment] 2019-11-14 11:26
This just happened again on an intake build: 
https://gradle-enterprise.elastic.co/s/evu3cnypcts2o/tests/lgycqkw2bfw46-clvf2uhrzpiw4

**Comment by original-brownbear** [comment] 2019-11-15 09:55
@tlrx just had this fail on me here https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/10613/testReport/junit/org.elasticsearch.repositories.azure/AzureBlobStoreRepositoryTests/testIndicesDeletedFromRepository/ and it had the new logging active :)

**Comment by tlrx** [comment] 2019-11-20 10:04
It happened again today: https://gradle-enterprise.elastic.co/s/yfz6omddppwtu/console-log#L4299

**Comment by dnhatn** [comment] 2019-11-25 16:00
Another instance https://gradle-enterprise.elastic.co/s/nvwjkfg6fmlmm.

**Comment by original-brownbear** [comment] 2019-11-25 16:04
The above doesn't contain https://github.com/elastic/elasticsearch/pull/49525 (assumed fix) it seems :)

**Comment by tlrx** [comment] 2019-11-26 08:16
> The above doesn't contain #49525 (assumed fix) it seems :)

Yep

**Comment by original-brownbear** [comment] 2019-11-26 08:35
@tlrx think it's safe to close this one (and all the related ones) now? :) We didn't have any new failures ever since merging #49525 it appears :)

**Comment by tlrx** [comment] 2019-11-26 08:50
@original-brownbear It can take more than a day for the failure to happen, but yeah let's close this and reopen if needed (I'm sure we won't :)) Thanks again for your expertise on this!

**Closed by tlrx** 2019-11-26 08:50 UTC
Labels: :Distributed/Snapshot/Restore, >test-failure
