### ISSUE TITLE
[CI] DateTimeUnitTests.testConversion fails non-reproducibly

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#39617] opened 2019-03-04 03:40 UTC
I cannot reproduce this one.

Failed on 7.0 (bea2628)
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+multijob-unix-compatibility/os=oraclelinux-6/51/console

```
./gradlew :server:unitTest -Dtests.seed=55D6AFA4F0B92ECC \
  -Dtests.class=org.elasticsearch.common.rounding.DateTimeUnitTests \
  -Dtests.method="testConversion" -Dtests.security.manager=true \
  -Dtests.locale=th-TH -Dtests.timezone=SystemV/PST8 \
  -Dcompiler.java=11 -Druntime.java=8
```

```
03:03:05 
03:03:05 Suite: org.elasticsearch.common.rounding.DateTimeUnitTests
03:03:05   1> [2562-03-03T19:03:04,899][INFO ][o.e.c.r.DateTimeUnitTests] [testConversion] before test
03:03:05   1> [2562-03-03T19:03:04,909][INFO ][o.e.c.r.DateTimeUnitTests] [testConversion] after test
03:03:05 FAILURE 0.02s J7 | DateTimeUnitTests.testConversion <<< FAILURES!
03:03:05    > Throwable #1: java.lang.AssertionError: 
03:03:05    > Expected: is <289299900343L>
03:03:05    >      but: was <289303500343L>
03:03:05    > 	at __randomizedtesting.SeedInfo.seed([55D6AFA4F0B92ECC:53DE2A9EDD767158]:0)
03:03:05    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
03:03:05    > 	at org.elasticsearch.common.rounding.DateTimeUnitTests.testConversion(DateTimeUnitTests.java:79)
03:03:05    > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by davidkyle** [comment] 2019-03-15 10:21
The reproduce line from the build failure does not work but if I append `-Dtests.iters=100` then I repeatedly get failures

```
./gradlew :server:unitTest \
  -Dtests.seed=70955D0C70684381 \
  -Dtests.class=org.elasticsearch.common.rounding.DateTimeUnitTests \
  -Dtests.method="testConversion" \
  -Dtests.security.manager=true \
  -Dtests.jvm.argline="-XX:-UseConcMarkSweepGC -XX:+UseG1GC" \
  -Dtests.locale=es-UY \
  -Dtests.timezone=IET \
  -Dcompiler.java=11 \
  -Druntime.java=8 \
  -Dtests.iters=100
```

```
Expected: is <1380360797088L>
     but: was <1380357197088L>
	at __randomizedtesting.SeedInfo.seed([70955D0C70684381:769DD8365DA71C15]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.common.rounding.DateTimeUnitTests.testConversion(DateTimeUnitTests.java:79)
```

Note the difference between expected and actual is exactly 1 hour.

**Comment by dliappis** [comment] 2019-04-02 13:50
Observed again in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+intake/855/console

I had to increase iters to 10000 to get this reproduce:

```
Tests with failures:
  - org.elasticsearch.common.rounding.DateTimeUnitTests.testConversion {seed=[9A3AD580E64E70D9:7AC01F44B5E7C498]}
  - org.elasticsearch.common.rounding.DateTimeUnitTests.testConversion {seed=[9A3AD580E64E70D9:6F42C4DDF2CC87D2]}
  - org.elasticsearch.common.rounding.DateTimeUnitTests.testConversion {seed=[9A3AD580E64E70D9:1B76DB3A1BE294FD]}
  - org.elasticsearch.common.rounding.DateTimeUnitTests.testConversion {seed=[9A3AD580E64E70D9:16A6ADE38CA15E8F]}
  - org.elasticsearch.common.rounding.DateTimeUnitTests.testConversion {seed=[9A3AD580E64E70D9:DB1203E1230DC27F]}
```

I will backport the mute to 7.x.

**Comment by dliappis** [comment] 2019-04-10 13:38
Backport #40738 has now been merged into 7.x

**Comment by pgomulka** [comment] 2019-04-24 14:29
I think the test might be incorrect, I think the rules of calculating the time in a different zone could be more tricky around daylight saving time changes.
As per [javadoc](https://docs.oracle.com/javase/8/docs/api/java/time/zone/ZoneRules.html#getOffset-java.time.LocalDateTime-) :)
`The mapping from a local date-time to an offset is not straightforward. `
 I think we don't need this test - we can trust java got it right 

more explanation:
The test was tricky because it was using a current date (`Instant.now()`) and it was making this harder to reproduce. This is the data it actually failed on. 
```
public void testConversion() {
        long millis =1380403997088L;//
//        millis = randomLongBetween(0, Instant.now().toEpochMilli());
        DateTimeZone zone = DateTimeZone.forID("Pacific/Auckland");//randomDateTimeZone();
        ZoneId zoneId = zone.toTimeZone().toZoneId();

        int offsetSeconds = zoneId.getRules().getOffset(Instant.ofEpochMilli(millis)).getTotalSeconds();
        long parsedMillisJavaTime = ZonedDateTime.ofInstant(Instant.ofEpochMilli(millis), zoneId)

            .minusSeconds(offsetSeconds).toInstant().toEpochMilli();

        long parsedMillisJodaTime = zone.convertLocalToUTC(millis, false);
        assertThat(parsedMillisJavaTime, is(parsedMillisJodaTime));
    }
```

so the millis equal to 
2013-09-29T10:33:17.088+13:00[Pacific/Auckland] which happens to be last Sunday of september in 2013. This is the day when the daylight saving time change occurs:
```
The main islands use New Zealand Standard Time (NZST), 12 hours in advance of Coordinated Universal Time (UTC)

During summer months—from the last Sunday in September until the first Sunday in April—daylight saving time is observed and clocks are advanced one hour. New Zealand Daylight Time (NZDT) is 13 hours ahead of UTC
```

2013-09-29T23:33:17.088+13:00 at Pacific/Auckland should be 2013-09-28T21:33:17.088Z[UTC]. And this is what we would get from
```
ZonedDateTime.ofInstant(Instant.ofEpochMilli(millis), zoneId).withZoneSameInstant(ZoneOffset.UTC)`
```


But just subtracting 13h(the offset returned in offsetSeconds)  won’t work at this scenario

**Closed** 2019-04-25 07:11 UTC
Labels: :Core/Infra/Core, >test-failure
