### ISSUE TITLE
already flushing issue after upgrade to 1.5.2

### ISSUE THREAD

**Issue by leesword** [elastic/elasticsearch#11531] opened 2015-06-08 08:46 UTC
When I update the elastic to 1.5.2, it usually occur the issue as below:

[2015-06-07 00:00:07,870][DEBUG][action.admin.indices.flush] [pay_es_node0] [_river][1], node[nopuwJy_Q76PK1AwibE7Dw], [P], s[STARTED]: failed to execute [org.elasticsearch.action.admin.indices.flush.FlushRequest@22debddf]
org.elasticsearch.transport.RemoteTransportException: [pay_es_node1][inet[/*.*.*.*:9300]][indices:admin/flush[s]]
Caused by: org.elasticsearch.index.engine.FlushNotAllowedEngineException: [_river][1] already flushing...
        at org.elasticsearch.index.engine.InternalEngine.flush(InternalEngine.java:620)
        at org.elasticsearch.index.engine.InternalEngine.flush(InternalEngine.java:593)
        at org.elasticsearch.index.shard.IndexShard.flush(IndexShard.java:675)
        at org.elasticsearch.action.admin.indices.flush.TransportFlushAction.shardOperation(TransportFlushAction.java:109)
        at org.elasticsearch.action.admin.indices.flush.TransportFlushAction.shardOperation(TransportFlushAction.java:49)
        at org.elasticsearch.action.support.broadcast.TransportBroadcastOperationAction$ShardTransportHandler.messageReceived(TransportBroadcastOperationAction.java:339)
        at org.elasticsearch.action.support.broadcast.TransportBroadcastOperationAction$ShardTransportHandler.messageReceived(TransportBroadcastOperationAction.java:325)
        at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:277)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

Before that, I never encounter this, so I think it should be the upgraded version's issue, which cause the bulk insert operation failed. Anybody can tell me the reason ? 

Thanks

**Comment by bleskes** [comment] 2015-06-08 09:47
The flush process is in charge of commiting (fsyncing) any pending changes to disk so that the transaction log can be cleared. There can only be one ongoing flush at a time.  We trigger flushes internally but you can also trigger it externally with the flush API. If there is already an ongoing flush when the external API is called, the API will fail and tell you that with this exception. You can ask it wait for on going flushes before returning by using the `wait_if_ongoing ` parameter.  See https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-flush.html#flush-parameters

I'm closing this now because it seems that everything works as designed. If something is acting up, please feel fee to reopen.

**Closed by bleskes** 2015-06-08 09:47 UTC
