### ISSUE TITLE
obtaining the value of 'index.merge.scheduler.max_merge_count' from index-name/_settings?include_defaults=true error

### ISSUE THREAD

**Issue by kkewwei** [elastic/elasticsearch#51194] opened 2020-01-19 09:37 UTC
**ES_VERSION: 7.3.1**
**OS version: Linux**
**Description of the problem including expected versus actual behavior**:
The paramater value of index.merge.scheduler.max_merge_count obtaining from two different api are different:
1. The first way:
`curl -XGET 'http://localhost:9200/test1/_settings?pretty&include_defaults=true'`
the result:
```
{
  "test1": {
    "settings": {
      "index": {
        "provided_name": "test1",
        "merge": {
          "scheduler": {
            "max_thread_count": "1"
          }
        }
      }
    },
    "defaults": {
      "index": {
        "merge": {
          "scheduler": {
            "auto_throttle": "true",
            "max_merge_count": "9"
          }
        }
      }
    }
  }
}
```
2. The second way:
```
PUT test1/_settings
{
"index":{"merge.scheduler.max_merge_count":"7"}
}
```
The log is like this:
`[2020-01-19T17:30:28,079][INFO ][o.e.c.s.IndexScopedSettings] [node-1] updating [index.merge.scheduler.max_merge_count] from [6] to [7]`

The value of `index.merge.scheduler.max_merge_count` from the first way is 9(default value), the value from the second value is 6.

**Steps to reproduce**:

1. put the template:
```
PUT _template/test1
{
  "order": 0,
  "version": 2,
  "index_patterns": [
    "test1"
  ],
  "settings": {
    "index": {
      "merge": {
        "scheduler": {
          "max_thread_count": "1"
        }
      }
    }
  }
}
```
2. creating index `test1`
3. obtaining by the first way and second way.

**Comment by gaobinlong** [comment] 2020-02-10 10:25
The defaut value of `index.merge.scheduler.max_merge_count` is the value of `index.merge.scheduler.max_thread_count` plus 5. 
https://github.com/elastic/elasticsearch/blob/ee43115531234c2d955193ce0c9c268e1f02ab43/server/src/main/java/org/elasticsearch/index/MergeSchedulerConfig.java#L60

When `max_thread_count` is changed,  the value of `max_merge_count` is also changed, we can find the change from the log when we update `max_thread_count` to 1 by update settings API:
`
[index] updating [index.merge.scheduler.max_thread_count] from [4] to [1]
[index] updating [index.merge.scheduler.max_merge_count] from [9] to [6]
`
I think the updated value of `max_merge_count` is not set in the settings of  IndexMetaData, so we cannot see the real value by GET index settings API. Should we add `index.merge.scheduler.max_merge_count` in the settings of IndexMetaData if it has been changed associated with `index.merge.scheduler.max_thread_count` ?

**Comment by kkewwei** [comment] 2020-03-02 17:22
yes, It may be better to put  `index.merge.scheduler.max_merge_count` to IndexMetaData after updating `index.merge.scheduler.max_thread_count`.

**Comment by gwbrown** [comment] 2020-12-07 21:22
I believe this is a duplicate of https://github.com/elastic/elasticsearch/issues/47890, as this setting depends on the value of another setting. I'm going to close this issue as a duplicate and add this setting to that issue with a link to this issue.

**Closed by gwbrown** 2020-12-07 21:22 UTC
Labels: :Core/Infra/Settings, Team:Core/Infra, needs:triage
