### ISSUE TITLE
PluginCliTest Fails with Missing systemd-sysv-install on Fedora 32

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#64569] opened 2020-11-04 09:28 UTC
Not much to add here, this seems to be an infra issue.

`PluginCliTests.test20SymlinkPluginsDir` failed in https://gradle-enterprise.elastic.co/s/eusjndjmxqwes/tests/:qa:os:destructiveDistroTest.default-rpm/org.elasticsearch.packaging.test.PluginCliTests/test20SymlinkPluginsDir#1

with:

```

java.lang.RuntimeException: Command was not successful: [bash -c systemctl enable elasticsearch.service] |  
-- | --
  | result: exitCode = [1] stdout = [] stderr = [Synchronizing state of elasticsearch.service with SysV service script with /usr/lib/systemd/systemd-sysv-install. |  
  | Executing: /usr/lib/systemd/systemd-sysv-install enable elasticsearch |  
  | Failed to execute /usr/lib/systemd/systemd-sysv-install: No such file or directory] |  


```

**Comment by rjernst** [comment] 2020-11-04 20:03
This does look infrastructure related, as fedora 32 was just added in CI. I've opened an issue with that team, and will close this one as there is nothing we can do from the ES side.

**Closed by rjernst** 2020-11-04 20:03 UTC
Labels: :Core/Infra/Build, >test-failure, Team:Core/Infra

**Comment by imotov** [comment] 2020-11-05 21:38
It keeps failing on fedora-32 builds. It failed 72 times in the last 3 days. Should we mute it somehow while the issue is being investigated?

**Comment by rjernst** [comment] 2020-11-05 23:22
It's not just this test, any rpm test will file until fedora-32 is fixed. I don't think there is anything we can mute here.

**Comment by tvernum** [comment] 2020-11-06 05:02
I noticed the the infra issue is resolved with an ansible change, yet our tests are still failing
- https://gradle-enterprise.elastic.co/s/5qqigaerlvjee
- [Build Stats](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(sys.kernel-name,build.branch),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:b646ed00-7efc-11e8-bf69-63c8ef516157,key:build.project,negate:!f,params:(query:elasticsearch,type:phrase),type:phrase,value:elasticsearch),query:(match:(build.project:(query:elasticsearch,type:phrase))))),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:kuery,query:%22systemd-sysv-install%22),sort:!(process.time-start,desc)))

Is there something we need to do get new images pushed out to CI, or is it just a matter of waiting?
