### ISSUE TITLE
GlobalCheckpointSyncIT.testPersistGlobalCheckpoint test fails on main

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#86130] opened 2022-04-25 09:27 UTC
### CI Link

https://gradle-enterprise.elastic.co/s/zw5jghw3by7r2

### Repro line

gradlew ':server:internalClusterTest' --tests "org.elasticsearch.index.seqno.GlobalCheckpointSyncIT.testPersistGlobalCheckpoint" \   -Dtests.seed=7557CE3BCB407DEA \   -Dtests.locale=cs \   -Dtests.timezone=Europe/Mariehamn \   -Druntime.java=18

### Does it reproduce?

No

### Applicable branches

main

### Failure excerpt

10:29:14 org.elasticsearch.index.seqno.GlobalCheckpointSyncIT > testPersistGlobalCheckpoint FAILED
10:29:14     java.lang.AssertionError: 
10:29:14     Expected: <2L>
10:29:14          but: was <-1L>
10:29:14         at __randomizedtesting.SeedInfo.seed([7557CE3BCB407DEA:1B5972A012B5C62C]:0)
10:29:14         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
10:29:14         at org.junit.Assert.assertThat(Assert.java:956)
10:29:14         at org.junit.Assert.assertThat(Assert.java:923)
10:29:14         at org.elasticsearch.index.seqno.GlobalCheckpointSyncIT.lambda$testPersistGlobalCheckpoint$8(GlobalCheckpointSyncIT.java:239)
10:29:14         at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1061)
10:29:14         at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1034)
10:29:14         at org.elasticsearch.index.seqno.GlobalCheckpointSyncIT.testPersistGlobalCheckpoint(GlobalCheckpointSyncIT.java:232)

**Comment by DaveCTurner** [comment] 2022-04-26 07:48
Looks to be a duplicate of https://github.com/elastic/elasticsearch/issues/84898 which seems to be missing its team label so hasn't been showing up in our list. Closing this one and fixing the labels on the other.

**Closed by DaveCTurner** 2022-04-26 07:48 UTC
Labels: >test-failure, needs:triage
