### ISSUE TITLE
request aliases index respon index_closed_exception

### ISSUE THREAD

**Issue by test987654123** [elastic/elasticsearch#36998] opened 2018-12-27 09:58 UTC
Hi,  elasticsearch version: 6.5.4.  I am requesting index by wildcard to have data returned, But by index alias display index_closed_exception。 Is the new version modified, the corresponding api has changed。
 Index is to set the storage cycle，Application access to data through an alias mechanism。 
![image](https://user-images.githubusercontent.com/14846522/50475790-d026eb00-0a00-11e9-8d55-028e8b3f5b03.png)
![image](https://user-images.githubusercontent.com/14846522/50475824-e634ab80-0a00-11e9-869b-c1db07b45fc9.png)
![image](https://user-images.githubusercontent.com/14846522/50475839-edf45000-0a00-11e9-851f-107ea74b8bd0.png)
![image](https://user-images.githubusercontent.com/14846522/50475859-fba9d580-0a00-11e9-8ee3-d3b48743ac33.png)

**Comment by javanna** [comment] 2018-12-27 11:04
hi @test987654123 do you have any plugin installed? Are you using the security plugin by any chance?

**Comment by test987654123** [comment] 2018-12-28 03:02
Hi, there is any plugin .
I canceled the alias for closing the index, and now I request the alias data to respond normally.

**Comment by javanna** [comment] 2018-12-28 09:33
From the other similar issue that you opened (#36986) I understood that you are using xpack security, hence my initial question. This is the same problem as #36986, see #32238 for an explanation on the issue. It's a known problem when xpack security is used, and an alias that points to both closed and open indices is accessed. Closing as a duplicate of #32238.

**Closed by javanna** 2018-12-28 09:33 UTC
Labels: feedback_needed
