### ISSUE TITLE
Some doubt for new feature——SQL query

### ISSUE THREAD

**Issue by luoyuctl** [elastic/elasticsearch#72371] opened 2021-04-28 11:22 UTC
I try the new feature in elasticsearch v7.12.0 for search by SQL type.

But i found some question for this , why the array result view by using SQL type query isn't be allowed?

My doubts:

- Does SQL type query  affect query performance? 

- Why does this happen, the function is not realized or is there other considerations? 

- Is this will be support like DSL query？

![image](https://user-images.githubusercontent.com/51604064/116394245-40560d80-a855-11eb-860f-debda333e90f.png)

**Comment by markharwood** [comment] 2021-04-28 12:37
Thanks for opening this issue.
It looks to be a duplicate of the development ongoing in https://github.com/elastic/elasticsearch/issues/68066 so I will close this if you don't mind

**Closed by markharwood** 2021-04-28 12:37 UTC
Labels: >enhancement, needs:triage

**Comment by bpintea** [comment] 2021-04-29 17:00
@luoyuctl , this is indeed something we're actively looking into and hopefully make available in one of the coming releases.

**Comment by luoyuctl** [comment] 2021-04-30 03:52
> @luoyuctl , this is indeed something we're actively looking into and hopefully make available in one of the coming releases.

@bpintea Looking forward to your realization of the new features.
