### ISSUE TITLE
ESQL: cannot use null in math expressions

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#100637] opened 2023-10-10 20:14 UTC
### Description

The type check in Math operations does not accept the null type:
`eval x = 1 + null` --> 
```
org.elasticsearch.xpack.esql.EsqlIllegalArgumentException: Unsupported type NULL

	at __randomizedtesting.SeedInfo.seed([455B93726B4292FA:4B6918F6DF2C07E8]:0)
	at org.elasticsearch.xpack.esql.expression.predicate.operator.arithmetic.EsqlArithmeticOperation.toEvaluator(EsqlArithmeticOperation.java:141)
	at org.elasticsearch.xpack.esql.expression.predicate.operator.arithmetic.DateTimeArithmeticOperation.toEvaluator(DateTimeArithmeticOperation.java:155)
	at org.elasticsearch.xpack.esql.expression.predicate.operator.arithmetic.Add.toEvaluator(Add.java:27)
```

However this operation is not always triggered and seems to occur after enabling aggregation normalization in #100642

**Comment by luigidellaquila** [comment] 2023-11-03 09:22
@costin do you have a reproducer?

I tested it and it seems to work fine:

```
row a = 1 | eval b = 1 + null, c = a + null, d = null + null

       a       |       b       |       c       |       d       
---------------+---------------+---------------+---------------
1              |null           |null           |null      
```

Maybe it was fixed by [recent changes](https://github.com/elastic/elasticsearch/pull/101414) on null management?

**Comment by fang-xing-esql** [comment] 2024-07-31 00:22
I'm not able to reproduce this on the current main, the evaluation of x = 1 + null is done un `FoldNull` today, FoldNull happens before `ConstantFolding`, which calls `toEvaluator` as indicated in the backtrace of the original issue. It is likely that the code path changed, so the issue is gone. 

```
[TRACE][o.e.x.e.o.LogicalPlanOptimizer] [test] Rule rules.FoldNull applied
Limit[1000[INTEGER]]                   = Limit[1000[INTEGER]]
\_Eval[[1[INTEGER] + null[NULL] AS b]] ! \_Eval[[null[INTEGER] AS b]]
  \_Row[[1[INTEGER] AS a]]             =   \_Row[[1[INTEGER] AS a]]
```

**Closed by fang-xing-esql** 2024-07-31 00:22 UTC
Labels: >bug, Team:Analytics, :Analytics/ES|QL
