### ISSUE TITLE
[CI] CcsCommonYamlTestSuiteIT test {p0=search/500_date_range/test match query gte and lte with year uuuu} failing

### ISSUE THREAD

**Issue by kingherc** [elastic/elasticsearch#97787] opened 2023-07-19 08:54 UTC
**Build scan:**
https://gradle-enterprise.elastic.co/s/zdzeeuuyyra5e/tests/:qa:ccs-common-rest:yamlRestTest/org.elasticsearch.test.rest.yaml.CcsCommonYamlTestSuiteIT/test%20%7Bp0=search%2F500_date_range%2Ftest%20match%20query%20gte%20and%20lte%20with%20year%20uuuu%7D

**Reproduction line:**
```
./gradlew ':qa:ccs-common-rest:yamlRestTest' --tests "org.elasticsearch.test.rest.yaml.CcsCommonYamlTestSuiteIT.test {p0=search/500_date_range/test match query gte and lte with year uuuu}" -Dtests.seed=4F64B91746814CF9 -Dtests.locale=zh-Hant-TW -Dtests.timezone=America/Pangnirtung -Druntime.java=20
```

**Applicable branches:**
8.8

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.test.rest.yaml.CcsCommonYamlTestSuiteIT&tests.test=test%20%7Bp0%3Dsearch/500_date_range/test%20match%20query%20gte%20and%20lte%20with%20year%20uuuu%7D

**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([4F64B91746814CF9]:0)

```

**Comment by stu-elastic** [comment] 2023-09-05 15:17
Doesn't reproduce and no failures in the last week.  Looking for earlier instances of failures.

**Comment by stu-elastic** [comment] 2023-10-03 15:51
This is unrelated to the date range test, this is failing due to timeouts.  I'm going to close this because it's a general issue.

**Closed by stu-elastic** 2023-10-03 15:51 UTC
Labels: :Core/Infra/Core, >test-failure, Team:Core/Infra
