### ISSUE TITLE
: java.lang.ClassNotFoundException: com.microsoft.schemas.office.visio.x2012.main.ConnectsType

### ISSUE THREAD

**Issue by hello4usharath** [elastic/elasticsearch#25177] opened 2017-06-12 14:40 UTC
java.lang.NoClassDefFoundError: com/microsoft/schemas/office/visio/x2012/main/ConnectsType
        at com.microsoft.schemas.office.visio.x2012.main.impl.PageContentsTypeImpl.getConnects(Unknown Source) ~[?:?]
        at org.apache.poi.xdgf.usermodel.XDGFBaseContents.onDocumentRead(XDGFBaseContents.java:89) ~[?:?]
        at org.apache.poi.xdgf.usermodel.XDGFPageContents.onDocumentRead(XDGFPageContents.java:73) ~[?:?]
        at org.apache.poi.xdgf.usermodel.XDGFPages.onDocumentRead(XDGFPages.java:94) ~[?:?]
        at org.apache.poi.xdgf.usermodel.XmlVisioDocument.onDocumentRead(XmlVisioDocument.java:108) ~[?:?]
        at org.apache.poi.POIXMLDocument.load(POIXMLDocument.java:190) ~[?:?]
        at org.apache.poi.xdgf.usermodel.XmlVisioDocument.<init>(XmlVisioDocument.java:79) ~[?:?]
        at org.apache.poi.xdgf.extractor.XDGFVisioExtractor.<init>(XDGFVisioExtractor.java:41) ~[?:?]
        at org.apache.poi.extractor.ExtractorFactory.createExtractor(ExtractorFactory.java:207) ~[?:?]
        at org.apache.tika.parser.microsoft.ooxml.OOXMLExtractorFactory.parse(OOXMLExtractorFactory.java:86) ~[?:?]
        at org.apache.tika.parser.microsoft.ooxml.OOXMLParser.parse(OOXMLParser.java:87) ~[?:?]
        at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) ~[?:?]
        at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:120) ~[?:?]
        at org.apache.tika.parser.DelegatingParser.parse(DelegatingParser.java:72) ~[?:?]
        at org.apache.tika.extractor.ParsingEmbeddedDocumentExtractor.parseEmbedded(ParsingEmbeddedDocumentExtractor.java:102) ~[?:?]
        at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.handleEmbeddedFile(AbstractOOXMLExtractor.java:311) ~[?:?]
        at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.handleEmbeddedParts(AbstractOOXMLExtractor.java:202) ~[?:?]
        at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.getXHTML(AbstractOOXMLExtractor.java:115) ~[?:?]
        at org.apache.tika.parser.microsoft.ooxml.OOXMLExtractorFactory.parse(OOXMLExtractorFactory.java:112) ~[?:?]
        at org.apache.tika.parser.microsoft.ooxml.OOXMLParser.parse(OOXMLParser.java:87) ~[?:?]
        at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) ~[?:?]
        at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:120) ~[?:?]
        at org.apache.tika.Tika.parseToString(Tika.java:568) ~[?:?]
        at org.elasticsearch.ingest.attachment.TikaImpl$1.run(TikaImpl.java:94) ~[?:?]
        at org.elasticsearch.ingest.attachment.TikaImpl$1.run(TikaImpl.java:91) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
        at org.elasticsearch.ingest.attachment.TikaImpl.parse(TikaImpl.java:91) ~[?:?]
        at org.elasticsearch.ingest.attachment.AttachmentProcessor.execute(AttachmentProcessor.java:86) ~[?:?]
        at org.elasticsearch.ingest.common.ForEachProcessor.execute(ForEachProcessor.java:64) ~[?:?]
        at org.elasticsearch.ingest.CompoundProcessor.execute(CompoundProcessor.java:100) ~[elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.ingest.Pipeline.execute(Pipeline.java:58) ~[elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.ingest.PipelineExecutionService.innerExecute(PipelineExecutionService.java:166) ~[elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.ingest.PipelineExecutionService.access$000(PipelineExecutionService.java:41) ~[elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.ingest.PipelineExecutionService$2.doRun(PipelineExecutionService.java:88) ~[elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:596) ~[elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.2.0.jar:5.2.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.ClassNotFoundException: com.microsoft.schemas.office.visio.x2012.main.ConnectsType
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_121]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
        at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814) ~[?:1.8.0_121]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
        ... 39 more

**Comment by hello4usharath** [comment] 2017-06-12 14:41
we are getting above issue production

**Comment by dadoonet** [comment] 2017-06-12 14:42
@hello4usharath What is your elasticsearch version please?

**Comment by dadoonet** [comment] 2017-06-12 14:42
I see. 5.2.0. Then upgrade. It has been fixed since then.

**Comment by clintongormley** [comment] 2017-06-12 14:42
Looks like a duplicate of https://github.com/elastic/elasticsearch/pull/23214

**Comment by hello4usharath** [comment] 2017-06-12 14:43
5.2.0

**Closed** 2017-06-12 14:42 UTC

**Comment by hello4usharath** [comment] 2017-06-12 14:51
production we cannot upgraded. is there any other way?

**Comment by hello4usharath** [comment] 2017-06-12 14:51
production we cannot upgrade. is there any other way to fix the issue?

**Comment by dadoonet** [comment] 2017-06-12 14:58
No. Or don't send that kind of documents to the ingest pipeline.

I know someone who was starting dedicated ingest nodes then was monitoring the process and anytime the process was dying it was automatically restarted.

Or apply the patch made in #23214 in your own fork of the ingest attachment plugin then build it, then install it. But you will have to stop and restart the nodes anyway. 

But IMHO it's definitely better/safer to upgrade. Rolling upgrade is doable so it should not be an issue.
If you are a lucky user of elastic cloud, then just click on the upgrade button in cloud and you're done...

**Comment by hello4usharath** [comment] 2017-06-12 15:03
how to apply the patch?

**Comment by dadoonet** [comment] 2017-06-12 15:13
I believe you need to apply the changes that are in this commit https://github.com/elastic/elasticsearch/commit/76a977ab93127131b0646130c910235d96342e97

Then build the project with something like:

```sh
gradle plugins:ingest-attachment:assembleDist
```

But again, I would not do that but I'd upgrade.

**Comment by praveenkatru** [comment] 2022-12-14 20:16
I have facing the same issue in version 7.4.2 
java.lang.NoClassDefFoundError: com/microsoft/schemas/office/visio/x2012/main/ConnectsType
	at com.microsoft.schemas.office.visio.x2012.main.impl.PageContentsTypeImpl.getConnects(Unknown Source)

Could you please help on this
