### ISSUE TITLE
[Fields API] _type is not returned in the response

### ISSUE THREAD

**Issue by majagrubic** [elastic/elasticsearch#68311] opened 2021-02-01 16:42 UTC
When switching Discover to use the Fields API, `_type` field is no longer returned in the `fields` response. Moreover, when explicitly requesting a list of fields (which includes `_type`), an exception is thrown:
```type: "unsupported_operation_exception", reason: "Cannot fetch values for internal field [_type]."```

Our understanding was that this would be supported until 8.0.0. Removing it in a minor could be considered a breaking change for Discover.

**Comment by jtibshirani** [comment] 2021-02-01 21:23
Thanks for raising this. For now maybe `fields` could ignore the `_type` field it does for all other metadata fields. I think this is caused by a bug in how we detect metadata fields -- we miss the `_type` field since it was removed in 8.x.

We have a dedicated issue to consider how best to return metadata fields: https://github.com/elastic/elasticsearch/issues/63569. It'd be great to get your feedback there.

**Comment by jtibshirani** [comment] 2021-02-02 19:54
Here's a summary from digging in further:
* On the 7.x branch, and for 7.x indices on 'master' we correctly ignore the `_type` field.
* On 'master' with 8.x indices, we throw an error on `_type`. Instead we should behave as if the field didn't exist, where we don't error but return no values.

I opened #68413 to fix this oversight on 'master' and will close this out once it's merged. If you need a change to how metadata fields like `_type` are handled in general, let's discuss on #63569.

**Closed** 2021-02-05 20:13 UTC
Labels: :Search/Mapping, >bug, Team:Search
