### ISSUE TITLE
[CI] OutOfMemoryError in ESLoggingHandlerIT with FIPS enabled

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#70847] opened 2021-03-24 22:44 UTC
I've seen this happen twice now. Since the build blows up with an OOME I don't have a build scan to share. Here's the Jenkins jobs.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic-fips/ES_RUNTIME_JAVA=zulu11,nodes=general-purpose/94/console

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.12+matrix-java-periodic-fips/ES_RUNTIME_JAVA=java11,nodes=general-purpose/69/console

**Comment by mark-vieira** [comment] 2021-03-26 15:18
Happened again: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.12+matrix-java-periodic-fips/ES_RUNTIME_JAVA=openjdk15,nodes=general-purpose/72/console

**Comment by mark-vieira** [comment] 2021-03-26 15:21
Unfortunately we aren't capturing the heap dump anywhere. I'm looking at a way to do this but my intuition is that test is producing some obscene amount of log output.

**Comment by jkakavas** [comment] 2021-03-27 08:29
Not sure if these all have the same cause.. 

The zulu11 one fails with a StackOverflow Exception
```
REPRODUCE WITH: ./gradlew ':modules:transport-netty4:internalClusterTest' --tests "org.elasticsearch.transport.netty4.ESLoggingHandlerIT.testLoggingHandler" -Dtests.seed=68432A0D9B4958C5 -Dtests.security.manager=true -Dtests.locale=id-ID -Dtests.timezone=PRT -Druntime.java=11 -Dtests.fips.enabled=true

org.elasticsearch.transport.netty4.ESLoggingHandlerIT > classMethod FAILED
    com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=390, name=Thread-11, state=RUNNABLE, group=TGRP-ESLoggingHandlerIT]

        Caused by:
        java.lang.StackOverflowError
            at __randomizedtesting.SeedInfo.seed([68432A0D9B4958C5]:0)
            at java.base/java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3964)
            at java.base/java.util.regex.Pattern$GroupHead.match(Pattern.java:4804)
            at java.base/java.util.regex.Pattern$Loop.match(Pattern.java:4941)
            at java.base/java.util.regex.Pattern$GroupTail.match(Pattern.java:4863)
            at java.base/java.util.regex.Pattern$CharPropertyGreedy.match(Pattern.java:4306)
            at java.base/java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3964)
            at java.base/java.util.regex.Pattern$GroupHead.match(Pattern.java:4804)
            at java.base/java.util.regex.Pattern$Loop.match(Pattern.java:4941)
            at java.base/java.util.regex.Pattern$GroupTail.match(Pattern.java:4863)
            at java.base/java.util.regex.Pattern$CharPropertyGreedy.match(Pattern.java:4306)
```

Additionally ESLoggingHandlerIT seems to be logging ESLoggingHandler on TRACE level which does produce an obscene amount of log output


The java11, java15 ones ( both 7.12 as opposed to 7.x above ) still OOME'd but don't fail in the same way 

```
> Task :distribution:archives:integ-test-zip:checkMlCppNotice
java.nio.file.NoSuchFileException: /dev/shm/elastic+elasticsearch+7.12+matrix-java-periodic-fips/ES_RUNTIME_JAVA/java11/nodes/general-purpose/distribution/archives/integ-test-zip/build/zip-extracted/elasticsearch-7.12.1-SNAPSHOT/modules/x-pack-ml/NOTICE.txt
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:375)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:426)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newInputStream(Files.java:160)
	at java.base/java.nio.file.Files.newBufferedReader(Files.java:2916)
	at java.base/java.nio.file.Files.readAllLines(Files.java:3396)
```

is the only thing I could see in the jenkins logs. 

More investigation to follow, not really sure what goes on atm

**Comment by tvernum** [comment] 2021-03-29 02:49
I'd put a reasonable wager on this being related to Default-Distribution vs Integration-Distribution.
That would cause it to generate different logging when FIPS mode is enabled.

**Comment by reta** [comment] 2022-02-04 13:58
For the ones who are curious what is going on: the `ESLoggingHandlerIT` turns on the `trace` log level which leads to `Netty` dumping raw messages (in hex) into logs. For some specific rare patterns (I have an example), the `MockLogAppender` filter blows with `StrackOverflowError`. The change to `MockLogAppender` filter to watch only for single line log statements (as expressed in expectations for `testLoggingHandler`) fixed the issue [1].

[1] https://github.com/opensearch-project/OpenSearch/pull/2051/files

**Comment by jakelandis** [comment] 2022-10-24 18:34
Re-assigning test failure to distributed area. Fairly confident this is not directly related to FIPS (beyond it may change the runtime and logging slightly). [0 test failures in past 28 days](https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P28D&search.timeZoneId=America/Chicago&tests.container=org.elasticsearch.transport.netty4.ESLoggingHandlerIT#) and can not reproduce locally, so maybe this one should just be closed ?

**Comment by Tim-Brooks** [comment] 2023-02-01 16:30
Closing. I opened https://github.com/elastic/elasticsearch/pull/93399, but it seems like it may not be necessary due to other changes (https://github.com/elastic/elasticsearch/pull/90607). 

Thanks for the background and suggests @reta.

**Closed by Tim-Brooks** 2023-02-01 16:30 UTC
Labels: :Distributed/Network, >test-failure, Team:Distributed
