### ISSUE TITLE
NPE in DefaultSearchContext#isCancelled

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#35860] opened 2018-11-23 15:05 UTC
This reported before in #25820 as well as https://discuss.elastic.co/t/nullpointerexception-in-scroll/98717:

In a pretty overloaded cluster I see this logged:

```
[2018-11-21T01:29:01,790][DEBUG][o.e.a.s.TransportSearchScrollAction] [xxx] [341144276] Failed to execute query phase
org.elasticsearch.transport.RemoteTransportException: [xxx][xx.xx.xx.xx:9300][indices:data/read/search[phase/query+fetch/scroll]]
Caused by: java.lang.NullPointerException
	at org.elasticsearch.search.DefaultSearchContext.isCancelled(DefaultSearchContext.java:832) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:136) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:393) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:490) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.action.search.SearchTransportService$9.messageReceived(SearchTransportService.java:419) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.action.search.SearchTransportService$9.messageReceived(SearchTransportService.java:416) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(SecurityServerTransportInterceptor.java:251) ~[?:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.common.util.concurrent.EsExecutors$1.execute(EsExecutors.java:135) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.lambda$messageReceived$0(SecurityServerTransportInterceptor.java:300) ~[?:?]
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.lambda$inbound$2(ServerTransportFilter.java:154) ~[?:?]
	at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.maybeRun(AuthorizationUtils.java:173) ~[?:?]
	at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.setRunAsRoles(AuthorizationUtils.java:167) ~[?:?]
	at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.authorize(AuthorizationUtils.java:155) ~[?:?]
	at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.lambda$inbound$3(ServerTransportFilter.java:156) ~[?:?]
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$authenticateAsync$2(AuthenticationService.java:172) ~[?:?]
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$lookForExistingAuthentication$4(AuthenticationService.java:205) ~[?:?]
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lookForExistingAuthentication(AuthenticationService.java:216) ~[?:?]
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.authenticateAsync(AuthenticationService.java:170) ~[?:?]
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.access$000(AuthenticationService.java:131) ~[?:?]
	at org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:101) ~[?:?]
	at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.inbound(ServerTransportFilter.java:130) ~[?:?]
	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:307) ~[?:?]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1605) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.4.1.jar:6.4.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

This error being logged coincided with a data node becoming so overloaded that it timed out on various tasks and was unable to stay in sync with the cluster state.
Interestingly enough the other issue linked above also notes:

> Around the time of the error I noticed an NPE, IAE, and GC warnings in the ES logs. The index has 10 shards and 1 replica with 10 data nodes. Also around this time we experience a 60% increase in search latency (looking at kibana monitoring).

**Comment by original-brownbear** [comment] 2019-03-21 17:16
Small update here: This is reproducible by sending the same scroll request (same scroll id) concurrently. It seems both requests will use the same context in that scenario which leads to a race where the context is cleared on one thread while the other thread is still looping and checking for cancelled.

**Comment by jimczi** [comment] 2019-05-07 07:32
Since this is caused by using the same scroll id concurrently I wonder if we close this as won't fix, we already document that scroll ids should not be used concurrently. What do you think @original-brownbear ?

**Comment by original-brownbear** [comment] 2019-05-07 08:28
@jimczi I guess that would be ok :)

Though I wonder if we can do better. I faintly remember the situation this came out of:

* Someone was running into pretty high load in their cluster and as a result they seem to have ran into timeout + retry situations in their client that then obviously triggered this for a scroll request
 
=> obviously not the best user experience to get this behavior, but from a quick look over the code also not so trivial to fix. Maybe if we can't (or don't want to) fix the behavior to be nicer here we could at least add this information (that you can't use scroll IDs concurrently) to the logs though? (it's "a little" dirty to do that for an NPE, but maybe helpful?).

**Comment by jimczi** [comment] 2019-05-07 10:42
>  obviously not the best user experience to get this behavior, but from a quick look over the code also not so trivial to fix. Maybe if we can't (or don't want to) fix the behavior to be nicer here we could at least add this information (that you can't use scroll IDs concurrently) to the logs though? (it's "a little" dirty to do that for an NPE, but maybe helpful?).

The NPE is a result of a race condition and there is no guarantee that concurrent scroll request with the same id  always result in this NPE. They can fail at different places, we don't lock anything at the context level. However I wonder if we could check the reference counter of the context after it is incremented and if it's greater than 2 (the current thread + the context lock) throw a nicer IllegalStateException ? The current behavior is to free the context if a failure occurs so we'd still have a race condition but we could also consider this failure non-tragic and leave the context as is so that the other query can finish safely.

**Comment by original-brownbear** [comment] 2019-05-07 11:25
> However I wonder if we could check the reference counter of the context after it is incremented and if it's greater than 2 (the current thread + the context lock) throw a nicer IllegalStateException ?

:+1: sounds good to me :)

**Comment by javanna** [comment] 2024-06-17 19:48
There has been no further activity on this for a long while, closing.

**Closed by javanna** 2024-06-17 19:48 UTC
Labels: >bug, :Search/Search, Team:Search
