### ISSUE TITLE
Frequent failures for data frame tests in CI

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#45562] opened 2019-08-14 17:40 UTC
I've noticed an increase in the number of failures around the data frame integration tests. These don't reliable reproduce as it seems they are mostly timeout related. Here you can see this increase in failures began around last week.

https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=verification&failures.failureMessage=Execution%20failed%20for%20task%20%27:x-pack:plugin:data-frame:qa:*:integTestRunner%27.%0A%3E%20There%20were%20failing%20tests.%20See%20the%20report%20at:%20*&list.offset=0&list.size=50&list.sortColumn=startTime&list.sortOrder=desc&search.buildToolType=gradle&search.buildToolType=maven&search.startTimeMin=0&trends.section=overview&trends.timeResolution=day&viewer.tzOffset=-420

@atorok can you think of anything CI or build related that could impact this?

**Comment by benwtrent** [comment] 2019-08-14 18:28
I will be looking into this from the ML side of things. 

Here are some interesting logs from that latest failure. The test that is failing is one that tests how we handle failed states in transforms (ironic...). 

```
[2019-08-14T17:11:13,081][INFO ][o.e.x.d.t.DataFrameTransformTask] [integTest-0] Updating state for data frame transform [test-force-stop-failed-transform] to [{"task_state":"started","indexer_state":"stopped","checkpoint":0}]
...
[2019-08-14T17:11:14,183][WARN ][o.e.x.d.t.DataFrameTransformTask] [integTest-0] Data frame transform [test-force-stop-failed-transform] encountered an exception: 
org.elasticsearch.xpack.dataframe.transforms.DataFrameTransformTask$BulkIndexingException: Bulk index experienced failures. See the logs of the node running the transform for details.
...
[2019-08-14T17:11:14,249][ERROR][o.e.x.d.t.DataFrameTransformTask] [integTest-0] Data frame transform [test-force-stop-failed-transform]:task encountered more than 0 failures; latest failure: Bulk index experienced failures. See the logs of the node running the transform for details.
...
[2019-08-14T17:11:14,642][INFO ][o.e.x.d.t.DataFrameTransformTask] [integTest-0] Data frame transform [test-force-stop-failed-transform] has stopped
[2019-08-14T17:11:14,818][INFO ][o.e.x.d.t.DataFrameTransformTask] [integTest-0] Data frame transform [test-force-stop-failed-transform] has stopped
[2019-08-14T17:11:14,822][WARN ][o.e.x.d.t.DataFrameTransformTask] [integTest-0] Data frame transform [test-force-stop-failed-transform] encountered an exception: 
org.elasticsearch.xpack.dataframe.transforms.DataFrameTransformTask$BulkIndexingException: Bulk index experienced failures. See the logs of the node running the transform for details.
...
[2019-08-14T17:11:14,855][ERROR][o.e.x.d.t.DataFrameTransformTask] [integTest-0] Data frame transform [test-force-stop-failed-transform]:task encountered more than 0 failures; latest failure: Bulk index experienced failures. See the logs of the node running the transform for details.
[2019-08-14T17:11:14,913][WARN ][o.e.p.PersistentTasksClusterService] [integTest-0] trying to update state on non-existing task test-force-stop-failed-transform
[2019-08-14T17:11:14,959][ERROR][o.e.x.d.t.DataFrameTransformTask] [integTest-0] Failed to update state for data frame transform [test-force-stop-failed-transform]
...
[2019-08-14T17:11:14,961][ERROR][o.e.x.d.t.DataFrameTransformTask] [integTest-0] Failed to set task state as failed to cluster state
org.elasticsearch.ResourceNotFoundException: the task with id test-force-stop-failed-transform and allocation id 2 doesn't exist
```

We definitely have some sort of race condition, you can see by how many times we get the same log message. Many of those "failure" log messages referencing the task should realistically only be logged once.

**Comment by benwtrent** [comment] 2019-08-14 20:50
One PR merged to help with data frame instability: https://github.com/elastic/elasticsearch/pull/45511

**Comment by benwtrent** [comment] 2019-08-16 15:48
Another PR to address the failure state tests #45627

**Comment by mark-vieira** [comment] 2019-08-16 15:53
I was just about to report this one: https://gradle-enterprise.elastic.co/s/cnsrqikafhkm4/tests/failed

I'll update my branch and try again.

**Comment by benwtrent** [comment] 2019-08-16 17:03
@mark-vieira that build had my commit. I am re-muting that test. I see the cause, it is different than the ones I fixed.

**Comment by hendrikmuhs** [comment] 2019-10-21 06:34
several robustness have been made, no muted tests in this area, so this seems outdated.

**Closed by hendrikmuhs** 2019-10-21 06:34 UTC
Labels: :ml/Transform, >test-failure
