### ISSUE TITLE
Feature Request: Adjust score based on number of matching documents

### ISSUE THREAD

**Issue by pySilver** [elastic/elasticsearch#39405] opened 2019-02-26 16:46 UTC
Hi!

It might sound like SO question, but I haven't found anything remotely similar to my case in docs (and I checked it really well). So its kinda last resort to post it here :) 

I'm looking for the way to adjust score based on number of matching documents (through the function score or term score boosting or anything else)

Here is an example. You have 1000 sport shoes of different brands with the following distribution:

Adidas: 500
Nike: 300
Reebok: 150
Puma: 50

You'd like to show just 100 products per page and you definitely want to show products of a different brands, to avoid the situation that brand with biggest amount of products takes all space of a page, at least 1st page.

*Random/Function score* score will not work here simply because it does not take population size out of picture.

I was thinking about term query boost where each brand have different boost value based on its frequency, but that makes big brands products shifted to next pages all together if their boost val is too low, or it wont have any effect is too close to average value.

Maybe its possible to randomize boost from negative to some positive values per brand based on population (what value/why?) so some of products of biggest brand will be boosted and some not, while keeping positive boost range for smaller brands. It produces unpredictable output, but at least its better than "pure random". But still to make pagination and filtering work that boost should be constant for same product, so it wont appear on page 2,3 etc.

What I miss here actually is ability to stop boosting after X products of _that_ brand being boosted. Non-optimal solution would be (probably) to memorize product ids per brand that needs to be boosted and use it in term query/function score with context, but that raises questions of pagination and further filtering support. Sounds complex but fully automated solution would require:

1. aggregation query to determine competitive brands & number of matching products  in that product category
2. normalization by picking X products for each brand exceeding median value
3. boost all products except picked ones with negative value for biggest brands (or vice versa – boost all products of all brands equally, but for biggest brand limit boost to picked products only)

I will also be fine if I can somehow influence a position of a brand. Let's say by mod: Adidas takes every % 2 position, Nike ever 3rd and so on.

P.S. Does function_score is executed on every document that matches query (filter query in my case) or just a paginated subset returned by a query?

**Comment by mayya-sharipova** [comment] 2019-02-26 20:02
@pySilver  Thank you for submitting an issue. 

> Feature Request: Adjust score based on number of matching documents

Elasticsearch allows you to plug your own similarity which can define how a score can be computed.  In particular, in [scripted similarity](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-similarity.html#scripted_similarity) you have access to  `term.docFreq` - a number of matching documents for this term.  You can use this value and other values to come up with your own score calculations.

> is ability to stop boosting after X products of _that_ brand being boosted. ....P.S. Does function_score is executed on every document that matches query (filter query in my case) or just a paginated subset returned by a query?

The same score calculation is done for every matched document. But you can use [rescore](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-rescore.html) for your top documents.  

I am closing this issue, as what the issue is requesting `Feature Request: Adjust score based on number of matching documents` can already be done through a custom similarity. If you have a specific feature for rescoring, please submit a separate issue.

**Closed by mayya-sharipova** 2019-02-26 20:02 UTC
Labels: :Search/Ranking
