### ISSUE TITLE
[CI] Transforms mixed cluster tests can fail in 7.x due to index.hidden attribute

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#53931] opened 2020-03-22 09:57 UTC
Since #53902 was merged there have been numerous failures of the `mixed_cluster/80_transform_jobs_crud/Test GET, start, and stop old cluster batch transforms` test in the X-Pack rolling upgrade tests.

One example is:

* Build scan: https://gradle-enterprise.elastic.co/s/5z6xq7c75jkui
* Jenkins: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+default-distro+bwc/BWC_VERSION=7.4.0,nodes=centos-7&&immutable/684/

The error is:

```
expected [2xx] status code but api [data_frame_transform_deprecated.stop_transform] returned [409 Conflict] [{"error":{"root_cause":[{"type":"status_exception","reason":"Unable to stop data frame transform [old-simple-transform] as it is in a failed state with reason [Failed to create internal index mappings[java.lang.IllegalArgumentException: unknown setting [index.hidden] please check that any required plugins are installed, or check the breaking changes documentation for removed settings]]. Use force stop to stop the data frame transform.","stack_trace":"ElasticsearchStatusException[Unable to stop data frame transform [old-simple-transform] as it is in a failed state with reason [Failed to create internal index mappings[java.lang.IllegalArgumentException: unknown setting [index.hidden] please check that any required plugins are installed, or check the breaking changes documentation for removed settings]]. Use force stop to stop the data frame transform.]\n\tat org.elasticsearch.xpack.dataframe.action.TransportStopDataFrameTransformAction.validateTaskState(TransportStopDataFrameTransformAction.java:96)\n\tat org.elasticsearch.xpack.dataframe.action.TransportStopDataFrameTransformAction.lambda$doExecute$0(TransportStopDataFrameTransformAction.java:125)\n\tat org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62)\n\tat org.elasticsearch.xpack.dataframe.persistence.DataFrameTransformsConfigManager.lambda$expandTransformIds$9(DataFrameTransformsConfigManager.java:400)\n\tat org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62)\n\tat org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)\n\tat org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:70)\n\tat org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:64)\n\tat org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)\n\tat org.elasticsearch.action.search.AbstractSearchAsyncAction.sendSearchResponse(AbstractSearchAsyncAction.java:309)\n\tat org.elasticsearch.action.search.FetchSearchPhase$3.run(FetchSearchPhase.java:217)\n\tat org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:180)\n\tat org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:174)\n\tat org.elasticsearch.action.search.ExpandSearchPhase.run(ExpandSearchPhase.java:119)\n\tat org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:180)\n\tat org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:174)\n\tat org.elasticsearch.action.search.FetchSearchPhase.moveToNextPhase(FetchSearchPhase.java:210)\n\tat org.elasticsearch.action.search.FetchSearchPhase.lambda$innerRun$2(FetchSearchPhase.java:104)\n\tat org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:110)\n\tat org.elasticsearch.action.search.FetchSearchPhase.access$000(FetchSearchPhase.java:44)\n\tat org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:86)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\n\tat org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44)\n\tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:773)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:830)\n"}],"type":"status_exception","reason":"Unable to stop data frame transform [old-simple-transform] as it is in a failed state with reason [Failed to create internal index mappings[java.lang.IllegalArgumentException: unknown setting [index.hidden] please check that any required plugins are installed, or check the breaking changes documentation for removed settings]]. Use force stop to stop the data frame transform.","stack_trace":"ElasticsearchStatusException[Unable to stop data frame transform [old-simple-transform] as it is in a failed state with reason [Failed to create internal index mappings[java.lang.IllegalArgumentException: unknown setting [index.hidden] please check that any required plugins are installed, or check the breaking changes documentation for removed settings]]. Use force stop to stop the data frame transform.]\n\tat org.elasticsearch.xpack.dataframe.action.TransportStopDataFrameTransformAction.validateTaskState(TransportStopDataFrameTransformAction.java:96)\n\tat org.elasticsearch.xpack.dataframe.action.TransportStopDataFrameTransformAction.lambda$doExecute$0(TransportStopDataFrameTransformAction.java:125)\n\tat org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62)\n\tat org.elasticsearch.xpack.dataframe.persistence.DataFrameTransformsConfigManager.lambda$expandTransformIds$9(DataFrameTransformsConfigManager.java:400)\n\tat org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62)\n\tat org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)\n\tat org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:70)\n\tat org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:64)\n\tat org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)\n\tat org.elasticsearch.action.search.AbstractSearchAsyncAction.sendSearchResponse(AbstractSearchAsyncAction.java:309)\n\tat org.elasticsearch.action.search.FetchSearchPhase$3.run(FetchSearchPhase.java:217)\n\tat org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:180)\n\tat org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:174)\n\tat org.elasticsearch.action.search.ExpandSearchPhase.run(ExpandSearchPhase.java:119)\n\tat org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:180)\n\tat org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:174)\n\tat org.elasticsearch.action.search.FetchSearchPhase.moveToNextPhase(FetchSearchPhase.java:210)\n\tat org.elasticsearch.action.search.FetchSearchPhase.lambda$innerRun$2(FetchSearchPhase.java:104)\n\tat org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:110)\n\tat org.elasticsearch.action.search.FetchSearchPhase.access$000(FetchSearchPhase.java:44)\n\tat org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:86)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\n\tat org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44)\n\tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:773)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:830)\n"},"status":409}]
```

The important bit of that is obviously `Failed to create internal index mappings[java.lang.IllegalArgumentException: unknown setting [index.hidden] please check that any required plugins are installed, or check the breaking changes documentation for removed settings]`.

It's interesting that the other tests in that file haven't failed for the same reason.  This suggests that:

1. This test only fails when it is randomly selected as the first one to run out of the tests in the same file
2. If you create transform in a mixed version cluster before starting it then there is no problem, but if you start one that previously existed then you get this error

/cc @gwbrown @jaymode in case this is a sign of a wider problem with the introduction of hidden indices and rolling upgrades

**Comment by droberts195** [comment] 2020-03-22 10:04
> It's interesting that the other tests in that file haven't failed for the same reason

Gah, actually that's wrong, other tests _have_ failed for exactly the same reason, it just so happens that the first 3 I looked at were all the one in the original description:

* `mixed_cluster/80_transform_jobs_crud/Test GET, stop, start, old continuous transforms` failed in https://gradle-enterprise.elastic.co/s/ulg75vmequhq4
* `mixed_cluster/80_transform_jobs_crud/Test put batch transform on mixed cluster` failed in https://gradle-enterprise.elastic.co/s/7dt3jvptc2ubs

**Comment by droberts195** [comment] 2020-03-22 10:28
Since the tests are interdependent I opened #53932 to mute _all_ the transforms tests in the mixed and upgraded clusters in the 7.x branch.

**Comment by gwbrown** [comment] 2020-03-22 13:38
Thanks for raising and sorry for the noise - I wonder why these failures didn't occur on the CI run for the backport PR. 

I'll take a look at this first thing my Monday morning if not sooner, hopefully it's a simple fix.

**Comment by droberts195** [comment] 2020-03-22 15:59
> I wonder why these failures didn't occur on the CI run for the backport PR

These tests don't fail in every test run.  It's probably one third or even maybe one sixth.  It must take a combination of factors to make it happen, for example:

* Request sent to an old version coordinating node when the master node upgraded to 7.7
* Request sent to a 7.7 coordinating node when the master is still on the old version
* Some other test in the suite fixes the problem if run before one of the ones that's failed (remember cleanup cannot happen in between the rolling upgrade tests so side effects of one test can affect others), so the failure only occurs when that test is randomly selected to run after one of the "at risk" tests

I am not sure exactly which set of conditions causes the problem but it will be something along the lines of one of those things.

**Comment by droberts195** [comment] 2020-03-23 12:34
As well as the YAML tests, `TransformSurvivesUpgradeIT.testTransformRollingUpgrade` is failing for the same underlying reason.  An example is https://gradle-enterprise.elastic.co/s/ctg75mohgspuw

The test failure message is:

```
Expected: one of {<STARTED>, <INDEXING>}
     but: was <FAILED>
```

But the reason the transform is in the `failed` state is that it cannot create a notifications index.  From the server-side logs `x-pack/qa/rolling-upgrade/build/testclusters/v7.4.1-0/logs/v7.4.1.log` says:

```
[2020-03-23T11:09:41,387][ERROR][o.e.x.t.t.TransformTask  ] [v7.4.1-0] [continuous-transform-upgrade-job] transform has failed; experienced: [Failed to create internal index mappings[java.lang.IllegalArgumentException: unknown setting [index.hidden] please check that any required plugins are installed, or check the breaking changes documentation for removed settings]].
```

At the time that error happened the node it happened on `v7.4.1-0` _had_ been upgraded to version 7.7.0.  The master node at this time was `v7.4.1-2`, which had been elected a bit earlier:

```
[2020-03-23T11:08:00,751][INFO ][o.e.c.s.MasterService    ] [v7.4.1-2] elected-as-master ([2] nodes joined)[{v7.4.1-2}{CczcekDATT6GVtXDY3yBoA}{Of0quIhcRfmFkiGHqCgjrw}{127.0.0.1}{127.0.0.1:41750}{dilm}{ml.machine_memory=101204275200, xpack.installed=true, testattr=test, ml.max_open_jobs=20} elect leader, {v7.4.1-1}{-W9TLLMBSeGPVb-r1pmpdA}{Bce67W_MSUavZqa6LTbbIA}{127.0.0.1}{127.0.0.1:38268}{dilm}{testattr=test, ml.machine_memory=101204275200, ml.max_open_jobs=20, xpack.installed=true} elect leader, _BECOME_MASTER_TASK_, _FINISH_ELECTION_], term: 2, version: 1, reason: master node changed {previous [], current [{v7.4.1-2}{CczcekDATT6GVtXDY3yBoA}{Of0quIhcRfmFkiGHqCgjrw}{127.0.0.1}{127.0.0.1:41750}{dilm}{ml.machine_memory=101204275200, xpack.installed=true, testattr=test, ml.max_open_jobs=20}]}, added {{v7.4.1-1}{-W9TLLMBSeGPVb-r1pmpdA}{Bce67W_MSUavZqa6LTbbIA}{127.0.0.1}{127.0.0.1:38268}{dilm}{testattr=test, ml.machine_memory=101204275200, ml.max_open_jobs=20, xpack.installed=true},}
```

At the time of the problem `v7.4.1-2` was still on version 7.4.1, so the problematic scenario appears to be:

* Transform persistent task running on a 7.7 node when the master is still on the old version

The sequence in https://gradle-enterprise.elastic.co/s/ctg75mohgspuw is:

1. All 3 nodes start off running 7.4.1; `v7.4.2-2` is master
2. Transform gets started and its persistent task gets assigned to `v7.4.1-1`
3. The node `v7.4.1-0` gets stopped
4. The node `v7.4.1-0` gets restarted on version 7.7.0
5. The node `v7.4.1-1` gets stopped
6. The transform gets reassigned to `v7.4.1-0` so that it can continue operation
7. The node `v7.4.1-1` gets restarted on version 7.7.0
8. Problem occurs as 7.7.0 node `v7.4.1-0` sends a request to 7.4.1 node `v7.4.1-2` that it does not understand

The problem would not have occurred if the transform had been reassigned to `v7.4.1-2` instead of `v7.4.1-0` when `v7.4.1-1` was stopped.  This is one reason why the problem is intermittent.

The problem also would not have occurred if `v7.4.1-1` had originally been elected master and then `v7.4.1-0` had taken over as master when `v7.4.1-1` was stopped.  This is another reason why the problem is intermittent.

**Comment by jaymode** [comment] 2020-03-23 15:17
I addressed a similar issue for Watcher was to continue use of the template without the setting until all nodes have been upgraded, see #52974.

**Comment by gwbrown** [comment] 2020-03-23 15:18
Thanks for digging in @droberts195, that's really helpful. 

While I was writing this comment, @jaymode suggested the same thing I was just about to say I was going to try: Just adding some version guards around the logic that adds the `hidden` settings until all nodes have been upgraded.

**Comment by gwbrown** [comment] 2020-03-23 16:08
This reproduces reliably on 7.x (once you unmute) with:
```
./gradlew :x-pack:qa:rolling-upgrade:v7.4.0#bwcTest -Dtests.class="org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=mixed_cluster/80_transform_jobs_crud/*"
```

Just keeping this around because I always have to go and look up how to run these things since the reproduce line doesn't work.

**Comment by gwbrown** [comment] 2020-03-23 22:32
I muted `TransformSurvivesUpgradeIT.testTransformRollingUpgrade` in 7.x in https://github.com/elastic/elasticsearch/pull/54037.

I'll unmute in https://github.com/elastic/elasticsearch/pull/54036.

**Comment by gwbrown** [comment] 2020-03-24 21:54
This should be fixed by https://github.com/elastic/elasticsearch/pull/54036, so I'm closing this issue. Please reopen if we see these failures again - I'll try to keep an eye on the build over the next couple days to be sure.

**Closed by gwbrown** 2020-03-24 21:54 UTC
Labels: :ml/Transform, >test-failure, v7.7.0
