### ISSUE TITLE
[TSDB] Fields with metric type counter not supported when TSDB is enabled

### ISSUE THREAD

**Issue by ritalwar** [elastic/elasticsearch#95031] opened 2023-04-05 08:10 UTC
### Elasticsearch Version

 v 8.7.0

### Java Version

_bundled_

### OS Version

Darwin Kernel Version 21.3.0

### Problem Description

There is an observation for 2 different scenarios:

**Scenario 1:** Adding integration with enabling TSDB flag

**Behaviour**

Error in Dashboards for the fields of metric type counter.

![image](https://user-images.githubusercontent.com/102972658/230019490-3dfc01a9-6161-4309-b7bf-4a4a2082509a.png)
<img width="1708" alt="Screenshot 2023-04-05 at 1 08 39 PM" src="https://user-images.githubusercontent.com/102972658/230019545-b88b1135-c055-4ce2-a08e-69c2edcdb2b8.png">

Index Mapping is like:

```
{
        "mssql": {
          "properties": {
            "metrics": {
              "properties": {
                "active_log_size": {
                  "type": "long",
                  "meta": {
                    "unit": "byte"
                  },
                  "time_series_metric": "counter"
                },
                "database_id": {
                  "type": "long"
                },
                "database_name": {
                  "type": "keyword",
                  "time_series_dimension": true
                },
                "instance_name": {
                  "type": "keyword",
                  "time_series_dimension": true
                },
                "log_backup_time": {
                  "type": "date"
                },
                "log_recovery_size": {
                  "type": "long",
                  "meta": {
                    "unit": "byte"
                  },
                  "time_series_metric": "gauge"
                },
          }
        },
}
```

**Scenario 2:** Adding Integration without enabling TSDB flag

**Behaviour**

Dashboards woking fine:

![image](https://user-images.githubusercontent.com/102972658/230018269-2652bed9-98e3-4ed8-a4a8-1b16f67eada4.png)

Index Mapping is like:

```
{
        "mssql": {
          "properties": {
            "metrics": {
              "properties": {
                "active_log_size": {
                  "type": "long",
                  "meta": {
                    "unit": "byte"
                  }
                },
                "database_id": {
                  "type": "long"
                },
                "database_name": {
                  "type": "keyword"
                },
                "instance_name": {
                  "type": "keyword"
                },
                "log_backup_time": {
                  "type": "date"
                },
                "log_recovery_size": {
                  "type": "long",
                  "meta": {
                    "unit": "byte"
                  }
                },
            }
          }
        },
}
```

**Enable TSDB Flag:**
Dashboard still works fine and index mapping look like:

```

{
        "mssql": {
          "properties": {
            "metrics": {
              "properties": {
                "active_log_size": {
                  "type": "long",
                  "meta": {
                    "unit": "byte"
                  },
                  "time_series_metric": "counter"
                },
                "database_id": {
                  "type": "long"
                },
                "database_name": {
                  "type": "keyword",
                  "time_series_dimension": true
                },
                "instance_name": {
                  "type": "keyword",
                  "time_series_dimension": true
                },
                "log_backup_time": {
                  "type": "date"
                },
                "log_recovery_size": {
                  "type": "long",
                  "meta": {
                    "unit": "byte"
                  },
                  "time_series_metric": "gauge"
                },
            }
          }
        },
}
```

### Steps to Reproduce

Issue appears when we add any TSDB migrated integration with TSDB flag enabled.
Tested it with 2 integrations i.e MSSQL(Microsoft SQL Server) and RabbitMQ.
Dashboards are distorted with field not found error, for the fields of metric type counter.

Related Issue: https://github.com/elastic/elasticsearch/issues/93539

**Comment by ritalwar** [comment] 2023-04-05 09:22
Also, Please refer:
<img width="662" alt="Screenshot 2023-04-05 at 2 51 20 PM" src="https://user-images.githubusercontent.com/102972658/230039127-348b9e18-beb2-4eeb-a593-c968a57773b6.png">
<img width="860" alt="Screenshot 2023-04-05 at 2 51 55 PM" src="https://user-images.githubusercontent.com/102972658/230039148-1c646342-7d5e-4a0b-a7bd-c11a794f4193.png">

**Comment by martijnvg** [comment] 2023-04-05 11:46
Is it possible to retrieve the error that occurred in the last screenshot? 
I'm trying to figure out what is going on here, and I don't follow why the error in the first screenshot is returned. 
With the tsdb is enabled, max aggregation is supported on counter fields. When tsdb is disabled then all aggregations are allowed on counter fields.

**Comment by ritalwar** [comment] 2023-04-05 14:40
There is nothing more to the last screenshot.
Just Inspected the Request for the errored lens visualisation shared along and got this.

**Comment by lalit-satapathy** [comment] 2023-04-06 05:57
Duplicate of https://github.com/elastic/kibana/issues/152467

**Comment by martijnvg** [comment] 2023-04-06 07:25
I don't think that this is an Elasticsearch issue. Note that due to integration issue (#93539), the decision was made to not autocomplete counter fields in Kibana. But iirc if counter were to be used directly, then visualizations should be able to work. Work on its way so that in 8.8, counter fields can be autocompleted (elastic/kibana#152912).

**Comment by lalit-satapathy** [comment] 2023-05-12 13:41
Closing as https://github.com/elastic/kibana/issues/152467 is closed

**Closed by lalit-satapathy** 2023-05-12 13:41 UTC
Labels: >bug, Team:Analytics, :Analytics/TSDB
