### ISSUE TITLE
Exception serialization checking causes tests to hang in 1.7

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#12322] opened 2015-07-17 17:45 UTC
It looks like 1.7's LocalTransportChannel has:
```java
    @Override
    public void sendResponse(Throwable error) throws IOException {
        BytesStreamOutput stream = new BytesStreamOutput();
        if (ThrowableObjectOutputStream.canSerialize(error) == false) {
            assert false : "Can not serialize exception: " + error; // make sure tests fail
            error = new NotSerializableTransportException(error);
        }
...
```

This doesn't cause the tests to fail, at least not with the (probably outdated) way I run them in my plugin. It causes them to hang indefinitely.

For reference this is the way I run the integration tests that hang:
```java
@ElasticsearchIntegrationTest.ClusterScope(scope = ElasticsearchIntegrationTest.Scope.SUITE, transportClientRatio = 0.0)
public class AbstractPluginIntegrationTest extends ElasticsearchIntegrationTest {
    /**
     * Enable plugin loading.
     */
    @Override
    protected Settings nodeSettings(int nodeOrdinal) {
        return ImmutableSettings.builder().put(super.nodeSettings(nodeOrdinal))
                .put("plugins." + PluginsService.LOAD_PLUGIN_FROM_CLASSPATH, true).build();
    }
}
```

Its old, 1.1 era stuff but it still worked fine util now.

**Comment by nik9000** [comment] 2015-07-17 17:48
Looks to me like the assertion in LocalTransportChannel causes the response never to be sent at all.

**Comment by nik9000** [comment] 2015-07-17 19:43
I can fix the tests by throwing out the offending exceptions and throwing whole new, fully Serializable ones. Its what I'm doing with my extensions.

The hanging seems to be caused by that assertion. If I run the tests without assertions (```-ea:org.apache.lucene...``` so the base classes don't barf) then they pass even without the changes.

**Comment by nik9000** [comment] 2015-07-17 19:44
I'm told I should ping @s1monw about this.

**Comment by nik9000** [comment] 2015-07-29 00:53
It doesn't look like @s1monw's picked this up and I filed this so I'm taking it.

**Comment by nik9000** [comment] 2015-07-29 13:11
Clearing myself as assignee - this doesn't look like it'll be an issue in 2.0 so its probably ok to just let it become obsolete when 2.0 is eventually released.

**Comment by s1monw** [comment] 2015-08-03 09:13
@nik9000 sorry for the late answer here. I think this assertion is ok and we should stick with it on 1.7 - it's there to tell you you are sending stuff across the network that will be wrapped in a weird `NotSerializableException` can you share what exception can't be serialized so we might be able to add this to the whitelist?

**Comment by nik9000** [comment] 2015-08-03 13:22
> can you share what exception can't be serialized so we might be able to add this to the whitelist?

Its part of a plugin. It was simple enough to just make the exception serializable once I tracked down the breakage but it wasn't obvious where the breakage was because it looked like the test just hung - the assertion stopped elasticsearch from sending a response at all.

**Comment by s1monw** [comment] 2015-08-03 13:26
ok should we just close this and move on? I think it did was it was intended to do :)

**Comment by nik9000** [comment] 2015-08-03 13:27
Yeah - causing the test to hang wasn't great but its not worth fixing if its not a problem in 2.0.

**Closed** 2015-08-03 13:27 UTC
Labels: :Exceptions, bug, v1.7.2
