### ISSUE TITLE
Update nested fields with Spark

### ISSUE THREAD

**Issue by cristinaluengoagullo** [elastic/elasticsearch#29630] opened 2018-04-20 07:38 UTC
I'm trying to update a nested field using Spark and a scripted update. The code I'm using is:

update_params = "new_samples: samples"
update_script = "ctx._source.samples += new_samples"

es_conf = {
"es.mapping.id": "id",
"es.mapping.exclude": "id",
"es.write.operation": "upsert",
"es.update.script.params": update_params,
"es.update.script.inline": update_script
}

result.write.format("org.elasticsearch.spark.sql").options(**es_conf).option("es.nodes",configuration["elasticsearch"]["host"]).option("es.port",configuration["elasticsearch"]["port"] ).save(configuration["elasticsearch"]["index_name"]+"/"+configuration["version"],mode='append')

And the schema of the field is:

|-- samples: array (nullable = true)
| |-- element: struct (containsNull = true)
| | |-- gq: integer (nullable = true)
| | |-- dp: integer (nullable = true)
| | |-- gt: string (nullable = true)
| | |-- adBug: array (nullable = true)
| | | |-- element: integer (containsNull = true)
| | |-- ad: double (nullable = true)
| | |-- sample: string (nullable = true)

And I get the following error:

py4j.protocol.Py4JJavaError: An error occurred while calling o83.save.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1.0 failed 1 times, most recent failure: Lost task 0.0 in stage 1.0 (TID 1, localhost, executor driver): java.lang.ClassCastException: scala.collection.mutable.WrappedArray$ofRef cannot be cast to scala.Tuple2

Am I doing something wrong or is this a bug? Thanks.

**Comment by tlrx** [comment] 2018-04-20 07:49
Hi @cristinaluengoagullo, 

I saw that you already did the right thing: asking in the [Elastic forums](https://discuss.elastic.co/t/upsert-nested-fields-with-spark/128813?u=tanguy) first. Thank you!

I'm going to close this issue for now until it is confirmed as an Elasticsearch bug (because it looks like a misconfiguration for me but I don't know if it's on the Spark, Client or Scripted Update side). Let's sort this out on Discuss first.

**Closed by tlrx** 2018-04-20 07:49 UTC

**Comment by cristinaluengoagullo** [comment] 2018-04-20 07:53
Ok thanks!!

**Comment by cristinaluengoagullo** [comment] 2018-08-29 13:11
Hi! I know this issue is closed, but before creating a new one I wanted to ask. After asking in the Elastic forum, they told me the problem would be solved in a future version. I tried with the newest (6.4.0) and I still get the same error :( is it supposed to be fixed already?
Thanks!
