### ISSUE TITLE
Java API TransportClient sniffing with exlusion

### ISSUE THREAD

**Issue by baltendo** [elastic/elasticsearch#20681] opened 2016-09-28 12:10 UTC
We recently started to use the cluster sniffing feature in the Java API for node discovery which works great. But in our cluster setup we have 3 nodes (out of 9) which have different hardware (disk, less iops) and those are causing performance problems when they have to handle requests. To solve the issue I disabled sniffing again and didn't connect to those 3 nodes. 

In order to still have node discovery in case a node is added or removed to/from the cluster it would be great to have an exclusion feature.

```
Settings.Builder settingsBuilder = Settings.settingsBuilder()
                .put("cluster.name", "cluster")
                .put("client.transport.sniff", true).
                .putArray("client.transport.sniff.exclude", "node1", "node2", ...);
```

So sniffing would detect every x seconds all the nodes in the cluster, but it will not connect to the ones which are excluded.

**Comment by ywelsch** [comment] 2016-10-14 10:00
Duplicate of #16244

**Closed** 2016-10-14 10:01 UTC
Labels: :Java API, discuss
