### ISSUE TITLE
support lt/lte and gt/gte in range aggregation

### ISSUE THREAD

**Issue by djschny** [elastic/elasticsearch#15198] opened 2015-12-02 19:28 UTC
The [range aggregation] (https://www.elastic.co/guide/en/elasticsearch/reference/2.1/search-aggregations-bucket-range-aggregation.html) currently based upon documentation and my testing only supports `to` and `from` terminology.

In the theme to avoid ambiguity and prefer `lt`, `lte`, `gt`, and `gte` it would be nice if the aggregation query DSL support this.

Current
```
{
    "aggs" : {
        "price_ranges" : {
            "range" : {
                "field" : "price",
                "ranges" : [
                    { "to" : 50 },
                    { "from" : 50, "to" : 100 },
                    { "from" : 100 }
                ]
            }
        }
    }
}
```

Proposed
```
{
    "aggs" : {
        "price_ranges" : {
            "range" : {
                "field" : "price",
                "ranges" : [
                    { "lte" : 50 },
                    { "gte" : 50, "lt" : 100 },
                    { "gte" : 100 }
                ]
            }
        }
    }
}
```

@dakrone

**Comment by jpountz** [comment] 2015-12-02 21:44
This sounds similar to #5249 which has been closed as won't fix.

**Comment by clintongormley** [comment] 2015-12-03 13:56
Agreed. Closing as duplicate of #5249

**Closed by clintongormley** 2015-12-03 13:56 UTC
Labels: :Aggregations
