### ISSUE TITLE
[CI] UpgradeClusterClientYamlTestSuiteIT "test {p0=mixed_cluster/40_ml_datafeed_crud/Test old cluster datafeed without aggs}" timing out occasionally

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#52739] opened 2020-02-25 01:30 UTC
This test has timed out three times in one day after no failures in the past week on `master`. Seems a bit suspicious. In every case it seems we're blowing up when doing a rolling upgrade from `7.7.0` so perhaps this relates to some recent changes in `7.x`? Unfortunately, like most timeout failures, this didn't reproduce for me.

```
java.lang.AssertionError: Failure at [mixed_cluster/40_ml_datafeed_crud:2]: expected [2xx] status code but api [cluster.health] returned [408 Request Timeout] [{"cluster_name":"v7.7.0","status":"yellow","timed_out":true,"number_of_nodes":3,"number_of_data_nodes":3,"active_primary_shards":29,"active_shards":56,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":1,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":98.24561403508771}]Open stacktrace
Caused by: java.lang.AssertionError: expected [2xx] status code but api [cluster.health] returned [408 Request Timeout] [{"cluster_name":"v7.7.0","status":"yellow","timed_out":true,"number_of_nodes":3,"number_of_data_nodes":3,"active_primary_shards":29,"active_shards":56,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":1,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":98.24561403508771}]Open stacktrace
[2020-02-24T21:23:28,664][INFO ][o.e.u.UpgradeClusterClientYamlTestSuiteIT] [test] [p0=mixed_cluster/40_ml_datafeed_crud/Test old cluster datafeed without aggs] before test
[2020-02-24T21:24:38,735][INFO ][o.e.u.UpgradeClusterClientYamlTestSuiteIT] [test] Stash dump on test failure [{
  "stash" : {
    "body" : {
      "cluster_name" : "v7.7.0",
      "status" : "yellow",
      "timed_out" : true,
      "number_of_nodes" : 3,
      "number_of_data_nodes" : 3,
      "active_primary_shards" : 29,
      "active_shards" : 56,
      "relocating_shards" : 0,
      "initializing_shards" : 0,
      "unassigned_shards" : 1,
      "delayed_unassigned_shards" : 0,
      "number_of_pending_tasks" : 0,
      "number_of_in_flight_fetch" : 0,
      "task_max_waiting_in_queue_millis" : 0,
      "active_shards_percent_as_number" : 98.24561403508771
    }
  }
}]
[2020-02-24T21:24:38,779][INFO ][o.e.u.UpgradeClusterClientYamlTestSuiteIT] [test] There are still tasks running after this test that might break subsequent tests [data_frame/transforms[c], xpack/ml/job[c]].
[2020-02-24T21:24:38,779][INFO ][o.e.u.UpgradeClusterClientYamlTestSuiteIT] [test] [p0=mixed_cluster/40_ml_datafeed_crud/Test old cluster datafeed without aggs] after test
```

https://gradle-enterprise.elastic.co/s/6utx7vz3wa75s/tests/qvsbxgij46xlg-qz5znhu3cm5p2
https://gradle-enterprise.elastic.co/s/knmzxc5htf7fq/tests/qvsbxgij46xlg-qz5znhu3cm5p2
https://gradle-enterprise.elastic.co/s/7ba2auu65mcce/tests/qvsbxgij46xlg-qz5znhu3cm5p2

**Comment by mark-vieira** [comment] 2020-02-25 01:34
And yet another: https://gradle-enterprise.elastic.co/s/6666kjlw22ios/tests/qvsbxgij46xlg-qz5znhu3cm5p2

4 failures in a day seems too much to be a coincidence.

**Comment by mark-vieira** [comment] 2020-02-25 05:45
This test continues to time out so I've muted it in ab2f0c3de942f24bdb9e8a4b26325dfaa5f4270d.

**Comment by dnhatn** [comment] 2020-02-25 15:47
Another instance https://gradle-enterprise.elastic.co/s/zmzph46xfvt24.

**Comment by droberts195** [comment] 2020-02-25 18:06
> I could make the mixed cluster not wait for green (instead just wait for yellow)

That will mean that eventually we get a test failure because we completely lose an index.  When the mixed cluster is upgraded to the upgraded cluster then a node will be removed from it.  If this node has the only shard of a yellow index on it then that index will be completely lost and all the tests in the upgraded cluster that rely on it will fail.

So I think we need to find out what is stopping the green state being achieved.

One interesting thing from the Jenkins console output is this:

```
  1> [2020-02-25T06:30:34,378][INFO ][o.e.u.UpgradeClusterClientYamlTestSuiteIT] [test] There are still tasks running after this test that might break subsequent tests [data_frame/transforms[c], xpack/ml/job[c]].
  1> [2020-02-25T06:30:34,379][INFO ][o.e.u.UpgradeClusterClientYamlTestSuiteIT] [test] [p0=mixed_cluster/80_transform_jobs_crud/Test GET, stop, start, old continuous transforms] after test
  1> [2020-02-25T06:30:34,411][INFO ][o.e.u.UpgradeClusterClientYamlTestSuiteIT] [test] [p0=mixed_cluster/90_ml_data_frame_analytics_crud/Start and stop old regression job] before test
  1> [2020-02-25T06:30:35,317][INFO ][o.e.u.UpgradeClusterClientYamlTestSuiteIT] [test] There are still tasks running after this test that might break subsequent tests [data_frame/transforms[c], indices:admin/refresh, indices:admin/refresh[s], indices:admin/refresh[s][p], indices:data/read/search, indices:data/write/reindex, xpack/ml/job[c]].
  1> [2020-02-25T06:30:35,318][INFO ][o.e.u.UpgradeClusterClientYamlTestSuiteIT] [test] [p0=mixed_cluster/90_ml_data_frame_analytics_crud/Start and stop old regression job] after test
  1> [2020-02-25T06:30:35,342][INFO ][o.e.u.UpgradeClusterClientYamlTestSuiteIT] [test] [p0=mixed_cluster/40_ml_datafeed_crud/Test old cluster datafeed without aggs] before test
  1> [2020-02-25T06:31:45,430][INFO ][o.e.u.UpgradeClusterClientYamlTestSuiteIT] [test] Stash dump on test failure [{
  1>   "stash" : {
  1>     "body" : {
  1>       "cluster_name" : "v7.7.0",
  1>       "status" : "yellow",
  1>       "timed_out" : true,
  1>       "number_of_nodes" : 3,
  1>       "number_of_data_nodes" : 3,
  1>       "active_primary_shards" : 30,
  1>       "active_shards" : 58,
  1>       "relocating_shards" : 0,
  1>       "initializing_shards" : 0,
  1>       "unassigned_shards" : 1,
  1>       "delayed_unassigned_shards" : 0,
  1>       "number_of_pending_tasks" : 0,
  1>       "number_of_in_flight_fetch" : 0,
  1>       "task_max_waiting_in_queue_millis" : 0,
  1>       "active_shards_percent_as_number" : 98.30508474576271
  1>     }
  1>   }
  1> }]
```

`p0=mixed_cluster/90_ml_data_frame_analytics_crud/Start and stop old regression job` has left a reindex in progress when the 70 second wait for green started.  That may be related to the slowness, and if it's the test that runs _before_ the timeout that's the cause then it would explain why the failures are intermittent since the test order is random.

The server-side logs from the first reported failure, https://gradle-enterprise.elastic.co/s/6utx7vz3wa75s, are at https://storage.cloud.google.com/elasticsearch-ci-artifacts/jobs/elastic+elasticsearch+master+multijob+fast+bwc/build/3785.tar.bz2 . I downloaded this bundle and in the hope that the answer to this problem would be in one of these files:

```
bash-3.2$ ls -l x-pack/qa/rolling-upgrade/build/testclusters/v7.7.0-?/logs/v7.7.0.log
-rw-r--r--@ 1 dave  dev  85825 Feb 25 01:02 x-pack/qa/rolling-upgrade/build/testclusters/v7.7.0-0/logs/v7.7.0.log
-rw-r--r--@ 1 dave  dev  59389 Feb 25 01:01 x-pack/qa/rolling-upgrade/build/testclusters/v7.7.0-1/logs/v7.7.0.log
-rw-r--r--@ 1 dave  dev  98390 Feb 25 01:02 x-pack/qa/rolling-upgrade/build/testclusters/v7.7.0-2/logs/v7.7.0.log
```

The corresponding portions are:

7.7.0-0:

```
[2020-02-25T01:00:34,009][INFO ][o.e.x.t.t.TransformTask  ] [v7.7.0-0] [old-simple-continuous-transform] updating state for transform to [{"task_state":"started","indexer_state":"stopped","checkpoint":0,"progress":{"docs_remaining":0,"total_docs":0,"percent_complete":100.0,"docs_indexed":0,"docs_processed":0},"should_stop_at_checkpoint":false}].
[2020-02-25T01:00:34,079][INFO ][o.e.x.t.t.TransformPersistentTasksExecutor] [v7.7.0-0] [old-simple-continuous-transform] successfully completed and scheduled task in node operation
[2020-02-25T01:00:34,168][INFO ][o.e.x.c.i.AsyncTwoPhaseIndexer] [v7.7.0-0] Indexer job encountered [STOPPING] state, halting indexer.
[2020-02-25T01:00:34,170][INFO ][o.e.x.t.t.TransformIndexer] [v7.7.0-0] [old-simple-continuous-transform] transform has stopped.
[2020-02-25T01:00:34,932][INFO ][o.e.x.m.a.TransportStartDataFrameAnalyticsAction] [v7.7.0-0] [old_cluster_regression_job] Starting data frame analytics
[2020-02-25T01:00:35,041][INFO ][o.e.x.m.d.DataFrameAnalyticsManager] [v7.7.0-0] [old_cluster_regression_job] Creating destination index [old_cluster_regression_job_results]
[2020-02-25T01:00:35,078][INFO ][o.e.x.m.a.TransportStopDataFrameAnalyticsAction] [v7.7.0-0] [old_cluster_regression_job] Stopping task with force [false]
[2020-02-25T01:01:45,893][INFO ][o.e.x.m.j.p.a.AutodetectProcessManager] [v7.7.0-0] Opening job [old-cluster-categorization-job]
[2020-02-25T01:01:45,898][INFO ][o.e.x.c.m.j.p.ElasticsearchMappings] [v7.7.0-0] Mappings for [.ml-anomalies-shared] are outdated [7.7.0], updating it[8.0.0].
```

7.7.0-1:

```
[2020-02-25T01:00:32,539][DEBUG][o.e.x.w.WatcherIndexingListener] [v7.7.0-1] adding watch [my_watch] to trigger service
[2020-02-25T01:01:52,336][DEBUG][o.e.x.t.t.TransformTask  ] [v7.7.0-1] [data_frame/transforms/schedule_continuous-transform-upgrade-job] transform indexer schedule has triggered, state: [STARTED].
```

7.7.0-2:

```
[2020-02-25T01:00:35,088][INFO ][o.e.c.m.MetaDataCreateIndexService] [v7.7.0-2] [old_cluster_regression_job_results] creating index, cause [api], templates [], shards [1]/[1], mappings [_doc]
[2020-02-25T01:01:45,937][INFO ][o.e.c.m.MetaDataMappingService] [v7.7.0-2] [.ml-anomalies-shared/AUZ9C6bzT0e-jwhyq1gguQ] update_mapping [_doc]
```

So it's not completely clear from this which index had the unassigned shard, but the one created by the regression test that ran immediately before the timeout is a prime suspect.

It's a shame we can't get it to run a `_cat/indices` after the timeout waiting for green.

> I could make the mixed cluster not wait for green (instead just wait for yellow)

Maybe the solution is to wait for green, but only on the subset of indices needed by the datafeed tests instead of all indices.

**Comment by mayya-sharipova** [comment] 2020-11-03 17:24
Not completely sure if the issue is relevant, but today we had some failures on `master` for `90_ml_data_frame_analytics_crud`:

```
./gradlew ':x-pack:qa:rolling-upgrade:v7.11.0#twoThirdsUpgradedTest' --tests "org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT.test {p0=mixed_cluster/90_ml_data_frame_analytics_crud/Start and stop old outlier_detection job}" \
  -Dtests.seed=31E31FBBABF9FF90 \
  -Dtests.security.manager=true \
  -Dtests.locale=hu \
  -Dtests.timezone=Africa/Libreville \
  -Druntime.java=11 \
  -Dtests.rest.suite=mixed_cluster
```
BuildScan: https://gradle-enterprise.elastic.co/s/v3ddqghfoj2qy

```
Failure at [mixed_cluster/90_ml_data_frame_analytics_crud:33]: expected [2xx] status code but api [ml.start_data_frame_analytics] returned [400 Bad Request] [{"error":{"root_cause":[{"type":"status_exception","reason":"Unable to start old_cluster_outlier_detection_job as no documents in the source indices [bwc_ml_outlier_detection_job_source] contained all the fields selected for analysis....
```

Failure at [mixed_cluster/90_ml_data_frame_analytics_crud:33]: expected [2xx] status code but api [ml.start_data_frame_analytics] returned [400 Bad Request] [{"error":{"root_cause":[{"type":"status_exception","reason":"Unable to start old_cluster_outlier_detection_job as no documents in the source indices [bwc_ml_outlier_detection_job_source] contained all the fields selected for analysis. If you are relying on automatic field selection then there are currently mapped fields that do not exist in any indexed documents, and you will have to switch to explicit field selection and include only fields that exist in indexed documents.","stack_trace":"org.elasticsearch.ElasticsearchStatusException: Unable to start old_cluster_outlier_detection_job as no documents in the source indices [bwc_ml_outlier_detection_job_source] contained all the fields selected for analysis. If you are relying on automatic field selection then there are currently mapped fields that do not exist in any indexed documents, and you will have to switch to explicit field selection and include only fields that exist in indexed documents.\n\tat org.elasticsearch.xpack.core.ml.utils.ExceptionsHelper.badRequestException(ExceptionsHelper.java:75)\n\tat org.elasticsearch.xpack.ml.action.TransportStartDataFrameAnalyticsAction.lambda$validateSourceIndexRowsCount$16(TransportStartDataFrameAnalyticsAction.java:355)\n\tat org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)\n\tat org.elasticsearch.xpack.ml.dataframe.extractor.DataFrameDataExtractor.lambda$collectDataSummaryAsync$6(DataFrameDataExtractor.java:327)\n\tat org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)\n\tat org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)\n\tat org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:89)\n\tat org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:83)\n\tat org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)\n\tat org.elasticsearch.action.ActionListener$5.onResponse(ActionListener.java:249)\n\tat org.elasticsearch.action.search.AbstractSearchAsyncAction.sendSearchResponse(AbstractSearchAsyncAction.java:562)\n\tat org.elasticsearch.action.search.ExpandSearchPhase.run(ExpandSearchPhase.java:119)\n\tat org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:365)\n\tat org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:359)\n\tat org.elasticsearch.action.search.FetchSearchPhase.moveToNextPhase(FetchSearchPhase.java:230)\n\tat org.elasticsearch.action.search.FetchSearchPhase.lambda$innerRun$1(FetchSearchPhase.java:112)\n\tat org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:118)\n\tat org.elasticsearch.action.search.FetchSearchPhase.access$000(FetchSearchPhase.java:47)\n\tat org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:95)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\n\tat org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44)\n\tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:737)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)\n\tat java.lang.Thread.run(Thread.java:832)\n"}],"type":"status_exception","reason":"Unable to start old_cluster_outlier_detection_job as no documents in the source indices [bwc_ml_outlier_detection_job_source] contained all the fields selected for analysis. If you are relying on automatic field selection then there are currently mapped fields that do not exist in any indexed documents, and you will have to switch to explicit field selection and include only fields that exist in indexed documents.","stack_trace":"org.elasticsearch.ElasticsearchStatusException: Unable to start old_cluster_outlier_detection_job as no documents in the source indices [bwc_ml_outlier_detection_job_source] contained all the fields selected for analysis. If you are relying on automatic field selection then there are currently mapped fields that do not exist in any indexed documents, and you will have to switch to explicit field selection and include only fields that exist in indexed documents.\n\tat org.elasticsearch.xpack.core.ml.utils.ExceptionsHelper.badRequestException(ExceptionsHelper.java:75)\n\tat org.elasticsearch.xpack.ml.action.TransportStartDataFrameAnalyticsAction.lambda$validateSourceIndexRowsCount$16(TransportStartDataFrameAnalyticsAction.java:355)\n\tat org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)\n\tat org.elasticsearch.xpack.ml.dataframe.extractor.DataFrameDataExtractor.lambda$collectDataSummaryAsync$6(DataFrameDataExtractor.java:327)\n\tat org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)\n\tat org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)\n\tat org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:89)\n\tat org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:83)\n\tat org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)\n\tat org.elasticsearch.action.ActionListener$5.onResponse(ActionListener.java:249)\n\tat org.elasticsearch.action.search.AbstractSearchAsyncAction.sendSearchResponse(AbstractSearchAsyncAction.java:562)\n\tat org.elasticsearch.action.search.ExpandSearchPhase.run(ExpandSearchPhase.java:119)\n\tat org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:365)\n\tat org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:359)\n\tat org.elasticsearch.action.search.FetchSearchPhase.moveToNextPhase(FetchSearchPhase.java:230)\n\tat org.elasticsearch.action.search.FetchSearchPhase.lambda$innerRun$1(FetchSearchPhase.java:112)\n\tat org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:118)\n\tat org.elasticsearch.action.search.FetchSearchPhase.access$000(FetchSearchPhase.java:47)\n\tat org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:95)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\n\tat org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44)\n\tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:737)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)\n\tat java.lang.Thread.run(Thread.java:832)\n"},"status":400}] |  
-- | --
  | at __randomizedtesting.SeedInfo.seed([31E31FBBABF9FF90:B9B7206105059268]:0)


Failure at [mixed_cluster/90_ml_data_frame_analytics_crud:33]: expected [2xx] status code but api [ml.start_data_frame_analytics] returned [400 Bad Request] [{"error":{"root_cause":[{"type":"status_exception","reason":"Unable to start old_cluster_outlier_detection_job as no documents in the source indices [bwc_ml_outlier_detection_job_source] contained all the fields selected for analysis. If you are relying on automatic field selection then there are currently mapped fields that do not exist in any indexed documents, and you will have to switch to explicit field selection and include only fields that exist in indexed documents.","stack_trace":"org.elasticsearch.ElasticsearchStatusException: Unable to start old_cluster_outlier_detection_job as no documents in the source indices [bwc_ml_outlier_detection_job_source] contained all the fields selected for analysis. If you are relying on automatic field selection then there are currently mapped fields that do not exist in any indexed documents, and you will have to switch to explicit field selection and include only fields that exist in indexed documents.\n\tat org.elasticsearch.xpack.core.ml.utils.ExceptionsHelper.badRequestException(ExceptionsHelper.java:75)\n\tat org.elasticsearch.xpack.ml.action.TransportStartDataFrameAnalyticsAction.lambda$validateSourceIndexRowsCount$16(TransportStartDataFrameAnalyticsAction.java:355)\n\tat org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)\n\tat org.elasticsearch.xpack.ml.dataframe.extractor.DataFrameDataExtractor.lambda$collectDataSummaryAsync$6(DataFrameDataExtractor.java:327)\n\tat org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)\n\tat org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)\n\tat org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:89)\n\tat org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:83)\n\tat org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)\n\tat org.elasticsearch.action.ActionListener$5.onResponse(ActionListener.java:249)\n\tat org.elasticsearch.action.search.AbstractSearchAsyncAction.sendSearchResponse(AbstractSearchAsyncAction.java:562)\n\tat org.elasticsearch.action.search.ExpandSearchPhase.run(ExpandSearchPhase.java:119)\n\tat org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:365)\n\tat org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:359)\n\tat org.elasticsearch.action.search.FetchSearchPhase.moveToNextPhase(FetchSearchPhase.java:230)\n\tat org.elasticsearch.action.search.FetchSearchPhase.lambda$innerRun$1(FetchSearchPhase.java:112)\n\tat org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:118)\n\tat org.elasticsearch.action.search.FetchSearchPhase.access$000(FetchSearchPhase.java:47)\n\tat org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:95)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\n\tat org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44)\n\tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:737)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)\n\tat java.lang.Thread.run(Thread.java:832)\n"}],"type":"status_exception","reason":"Unable to start old_cluster_outlier_detection_job as no documents in the source indices [bwc_ml_outlier_detection_job_source] contained all the fields selected for analysis. If you are relying on automatic field selection then there are currently mapped fields that do not exist in any indexed documents, and you will have to switch to explicit field selection and include only fields that exist in indexed documents.","stack_trace":"org.elasticsearch.ElasticsearchStatusException: Unable to start old_cluster_outlier_detection_job as no documents in the source indices [bwc_ml_outlier_detection_job_source] contained all the fields selected for analysis. If you are relying on automatic field selection then there are currently mapped fields that do not exist in any indexed documents, and you will have to switch to explicit field selection and include only fields that exist in indexed documents.\n\tat org.elasticsearch.xpack.core.ml.utils.ExceptionsHelper.badRequestException(ExceptionsHelper.java:75)\n\tat org.elasticsearch.xpack.ml.action.TransportStartDataFrameAnalyticsAction.lambda$validateSourceIndexRowsCount$16(TransportStartDataFrameAnalyticsAction.java:355)\n\tat org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)\n\tat org.elasticsearch.xpack.ml.dataframe.extractor.DataFrameDataExtractor.lambda$collectDataSummaryAsync$6(DataFrameDataExtractor.java:327)\n\tat org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)\n\tat org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)\n\tat org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:89)\n\tat org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:83)\n\tat org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)\n\tat org.elasticsearch.action.ActionListener$5.onResponse(ActionListener.java:249)\n\tat org.elasticsearch.action.search.AbstractSearchAsyncAction.sendSearchResponse(AbstractSearchAsyncAction.java:562)\n\tat org.elasticsearch.action.search.ExpandSearchPhase.run(ExpandSearchPhase.java:119)\n\tat org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:365)\n\tat org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:359)\n\tat org.elasticsearch.action.search.FetchSearchPhase.moveToNextPhase(FetchSearchPhase.java:230)\n\tat org.elasticsearch.action.search.FetchSearchPhase.lambda$innerRun$1(FetchSearchPhase.java:112)\n\tat org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:118)\n\tat org.elasticsearch.action.search.FetchSearchPhase.access$000(FetchSearchPhase.java:47)\n\tat org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:95)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\n\tat org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44)\n\tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:737)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)\n\tat java.lang.Thread.run(Thread.java:832)\n"},"status":400}] |  
-- | --
  | at __randomizedtesting.SeedInfo.seed([31E31FBBABF9FF90:B9B7206105059268]:0)

**Comment by droberts195** [comment] 2023-10-09 19:43
This hasn't failed for years. Closing.

**Closed by droberts195** 2023-10-09 19:43 UTC
Labels: >test-failure, :ml
