### ISSUE TITLE
Reproducible Failure in org.elasticsearch.cluster.metadata.DateMathExpressionResolverTests.testExpression_MixedArray

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#66907] opened 2021-01-02 15:29 UTC
This fails and reproduces for me locally 100% of the time on master:

```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.cluster.metadata.DateMathExpressionResolverTests.testExpression_MixedArray" -Dtests.seed=DD523116F9B24D8C -Dtests.security.manager=true -Dtests.locale=is-IS -Dtests.timezone=Europe/Warsaw -Druntime.java=15

org.elasticsearch.cluster.metadata.DateMathExpressionResolverTests > testExpression_MixedArray FAILED
    java.lang.AssertionError: 
    Expected: ".logstash-2021.01"
         but: was ".logstash-2020.01"
        at __randomizedtesting.SeedInfo.seed([DD523116F9B24D8C:794B3FD6F49CA76C]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.cluster.metadata.DateMathExpressionResolverTests.testExpression_MixedArray(DateMathExpressionResolverTests.java:125)


Suite: Test class org.elasticsearch.cluster.metadata.DateMathExpressionResolverTests
  1> [2021-01-02T16:24:50,530][INFO ][o.e.c.m.DateMathExpressionResolverTests] [testExpression_MixedArray] before test
  1> [2021-01-02T16:24:50,617][INFO ][o.e.c.m.DateMathExpressionResolverTests] [testExpression_MixedArray] after test
  2> REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.cluster.metadata.DateMathExpressionResolverTests.testExpression_MixedArray" -Dtests.seed=DD523116F9B24D8C -Dtests.security.manager=true -Dtests.locale=is-IS -Dtests.timezone=Europe/Warsaw -Druntime.java=15
  2> java.lang.AssertionError: 
    Expected: ".logstash-2021.01"
         but: was ".logstash-2020.01"
        at __randomizedtesting.SeedInfo.seed([DD523116F9B24D8C:794B3FD6F49CA76C]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.cluster.metadata.DateMathExpressionResolverTests.testExpression_MixedArray(DateMathExpressionResolverTests.java:125)
  2> NOTE: leaving temporary files on disk at: /home/brownbear/src/elasticsearch/server/build/testrun/test/temp/org.elasticsearch.cluster.metadata.DateMathExpressionResolverTests_DD523116F9B24D8C-002
  2> NOTE: test params are: codec=Asserting(Lucene87): {}, docValues:{}, maxPointsInLeafNode=878, maxMBSortInHeap=6.27231052818936, sim=Asserting(RandomSimilarity(queryNorm=true): {}), locale=is-IS, timezone=Europe/Warsaw
  2> NOTE: Linux 5.8.0-33-generic amd64/AdoptOpenJDK 15.0.1 (64-bit)/cpus=48,threads=1,free=524039296,total=536870912
  2> NOTE: All tests run in this JVM: [DateMathExpressionResolverTests]

Tests with failures:
 - org.elasticsearch.cluster.metadata.DateMathExpressionResolverTests.testExpression_MixedArray

```

**Comment by ywangd** [comment] 2021-01-04 05:01
I encountered this failure as well ([build scan](https://gradle-enterprise.elastic.co/s/iviu23lcdwmsc/tests/:server:test/org.elasticsearch.cluster.metadata.DateMathExpressionResolverTests/testExpression_MixedArray#1))

The reason for the failure is that the date math expression parser sets the day to the first day of the month when the unit is `M`:
https://github.com/elastic/elasticsearch/blob/4e0f7bbfde3a0a9df3d513f59c6b5816965cd08c/server/src/main/java/org/elasticsearch/common/time/JavaDateMathParser.java#L143

This brings the date value to `2021-01-01`. The issue is that, based on the year of the week format (`YYYY`), the year is actually `2020`, so the final result of `<.logstash-{now/M{YYYY.MM}}>` is `.logstash-2020-01` instead of `.logstash-2021-01`.

This can be easily fixed by matching the testing code to the logic in the main code, i.e. basically also add `with(LocalTime.MIN)` to the following statement:
https://github.com/elastic/elasticsearch/blob/4e0f7bbfde3a0a9df3d513f59c6b5816965cd08c/server/src/test/java/org/elasticsearch/cluster/metadata/DateMathExpressionResolverTests.java#L125-L126

However, I wonder whether the logic in the main code, i.e. `with(LocalTime.MIN)`, is actually intended?

**Comment by ywangd** [comment] 2021-01-04 06:53
I raised #66914

**Closed** 2021-01-04 11:51 UTC
Labels: :Core/Infra/Core, >test-failure, Team:Core/Infra
