### ISSUE TITLE
ILM updating record with existing Id on older index creates a new entry on new write index

### ISSUE THREAD

**Issue by DR9885** [elastic/elasticsearch#61242] opened 2020-08-17 21:50 UTC
Lets say we have a lifecycle-policy set to 30gb or 1d, and a group of indexes for "Offers-*", with an alias set as "Offers" to make managing them easier... Next we create a record with ID 1 using alias "Offers". Then lets assume we trigger the roll because of day or size requirements are met. Then later we update ID 1 using alias "Offers", because there are corrections.

Next if I go to query "Offers" for ID 1, I will see two entries... I was hoping this would update the old record, or it would move it to the write index...

**Comment by dakrone** [comment] 2020-08-17 22:22
Closing this as it is a duplicate of https://github.com/elastic/elasticsearch/issues/44794

**Closed by dakrone** 2020-08-17 22:22 UTC
Labels: >enhancement, needs:triage
