### ISSUE TITLE
Some exceptions during index creation are only logged in DEBUG hindering investigation/troubleshooting

### ISSUE THREAD

**Issue by romain-chanu** [elastic/elasticsearch#109610] opened 2024-06-12 07:36 UTC
### Elasticsearch Version

7.17.6 / 8.14.0

### Java Version

_bundled_

### OS Version

N.A

### 1. Environment / Background

Such behaviour has been observed in the field while assisting troubleshooting an overwhelmed master node / unstable cluster.

### 2. Version affected

We have observed such behaviour in version 7.17.6 and version 8.14.0

### 3. Problem

1) Master node was overwhelmed with thousands of `create-index` pending tasks.

```
insertOrder timeInQueue priority source
     232759       29.9s URGENT   create-index [my-index-abc-2024.24-000001], cause [api]
     232760       29.9s URGENT   create-index [my-index-abc-2024.24-000001], cause [api]
     232761       29.9s URGENT   create-index [my-index-cde-2024.24-000001], cause [api]
     232763       29.9s URGENT   create-index [my-index-efg-2024.24-000001], cause [api]
     232764       29.9s URGENT   create-index [my-index-cde-2024.24-000001], cause [api]
     232762       29.9s URGENT   create-index [my-index-abc-2024.24-000001], cause [api]
     232765       29.9s URGENT   create-index [my-index-cde-2024.24-000001], cause [api]
     232766       29.9s URGENT   create-index [my-index-cde-2024.24-000001], cause [api]
     232773       29.8s URGENT   create-index [my-index-cde-2024.24-000001], cause [api]
     232767       29.9s URGENT   create-index [my-index-abc-2024.24-000001], cause [api]
     232771       29.9s URGENT   create-index [my-index-cde-2024.24-000001], cause [api]
     232782       29.7s URGENT   create-index [my-index-ghi-2024.24-000001], cause [api]
     232830       29.3s URGENT   create-index [my-index-cde-2024.24-000001], cause [api]
     232769       29.9s URGENT   create-index [my-index-efg-2024.24-000001], cause [api]
     232768       29.9s URGENT   create-index [my-index-abc-2024.24-000001], cause [api]
     232770       29.9s URGENT   create-index [my-index-cde-2024.24-000001], cause [api]
     232781       29.7s URGENT   create-index [my-index-efg-2024.24-000001], cause [api]
     232796       29.5s URGENT   create-index [my-index-abc-2024.24-000001], cause [api]
```

2) Indices listed in the pending tasks were not created and **no errors were reported for the above indices**

3) Node hot threads for the master node revealed one thread running at 100% usage:

```
   100.1% [cpu=100.1%, other=0.0%] (500.5ms out of 500ms) cpu usage by thread 'elasticsearch[instance-0000000186][masterService#updateTask][T#1]'
     4/10 snapshots sharing following 25 elements
       app//org.elasticsearch.cluster.metadata.Metadata$Builder.build(Metadata.java:1833)
       app//org.elasticsearch.cluster.metadata.Metadata$Builder.build(Metadata.java:1709)
       app//org.elasticsearch.cluster.metadata.MetadataCreateIndexService.clusterStateCreateIndex(MetadataCreateIndexService.java:1202)
       app//org.elasticsearch.cluster.metadata.MetadataCreateIndexService.lambda$applyCreateIndexWithTemporaryService$3(MetadataCreateIndexService.java:489)
       app//org.elasticsearch.cluster.metadata.MetadataCreateIndexService$$Lambda$8103/0x0000000801fb88c8.apply(Unknown Source)
       app//org.elasticsearch.indices.IndicesService.withTempIndexService(IndicesService.java:673)
       app//org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexWithTemporaryService(MetadataCreateIndexService.java:451)
       app//org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequestWithV1Templates(MetadataCreateIndexService.java:567)
       app//org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:413)
       app//org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:420)
       app//org.elasticsearch.cluster.metadata.MetadataCreateIndexService$1.execute(MetadataCreateIndexService.java:319)
```

4) Based on the above, we enabled debug logging for `logger.org.elasticsearch.cluster.metadata.MetadataCreateIndexService` , which resulted in the below logs appearing in the Elasticsearch logs:

```
[2024-06-11T10:05:59,963][DEBUG][org.elasticsearch.cluster.metadata.MetadataCreateIndexService] [instance-0000000186] [my-index-abc-2024.24-000001] failed to create
java.lang.IllegalStateException: alias [my-index-abc] has more than one write index [my-index-abc-2024.24-000025,my-index-abc-2024.24-000001]
	at org.elasticsearch.cluster.metadata.IndexAbstraction$Alias.<init>(IndexAbstraction.java:243) ~[elasticsearch-7.17.6.jar:7.17.6]
	at org.elasticsearch.cluster.metadata.Metadata$Builder.buildIndicesLookup(Metadata.java:1954) ~[elasticsearch-7.17.6.jar:7.17.6]
	at org.elasticsearch.cluster.metadata.Metadata$Builder.build(Metadata.java:1833) ~[elasticsearch-7.17.6.jar:7.17.6]
	at org.elasticsearch.cluster.metadata.Metadata$Builder.build(Metadata.java:1709) ~[elasticsearch-7.17.6.jar:7.17.6]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.clusterStateCreateIndex(MetadataCreateIndexService.java:1202) ~[elasticsearch-7.17.6.jar:7.17.6]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.lambda$applyCreateIndexWithTemporaryService$3(MetadataCreateIndexService.java:489) ~[elasticsearch-7.17.6.jar:7.17.6]
	at org.elasticsearch.indices.IndicesService.withTempIndexService(IndicesService.java:673) ~[elasticsearch-7.17.6.jar:7.17.6]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexWithTemporaryService(MetadataCreateIndexService.java:451) ~[elasticsearch-7.17.6.jar:7.17.6]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequestWithV1Templates(MetadataCreateIndexService.java:567) ~[elasticsearch-7.17.6.jar:7.17.6]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:413) ~[elasticsearch-7.17.6.jar:7.17.6]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:420) ~[elasticsearch-7.17.6.jar:7.17.6]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService$1.execute(MetadataCreateIndexService.java:319) ~[elasticsearch-7.17.6.jar:7.17.6]
	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:51) ~[elasticsearch-7.17.6.jar:7.17.6]
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:840) ~[elasticsearch-7.17.6.jar:7.17.6]
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:407) ~[elasticsearch-7.17.6.jar:7.17.6]
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:243) [elasticsearch-7.17.6.jar:7.17.6]
	at org.elasticsearch.cluster.service.MasterService.access$100(MasterService.java:63) [elasticsearch-7.17.6.jar:7.17.6]
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:170) [elasticsearch-7.17.6.jar:7.17.6]
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:146) [elasticsearch-7.17.6.jar:7.17.6]
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:202) [elasticsearch-7.17.6.jar:7.17.6]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:718) [elasticsearch-7.17.6.jar:7.17.6]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:262) [elasticsearch-7.17.6.jar:7.17.6]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:225) [elasticsearch-7.17.6.jar:7.17.6]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

as well as

```
[2024-06-11T10:05:59,992][DEBUG][org.elasticsearch.cluster.metadata.MetadataCreateIndexService] [instance-0000000186] [my-index-abc-2024.24-000001] failed to create
org.elasticsearch.cluster.metadata.ProcessClusterEventTimeoutException: failed to process cluster event (create-index [my-index-abc-2024.24-000001], cause [api]) within 30s
	at org.elasticsearch.cluster.service.MasterService$Batcher.lambda$onTimeout$0(MasterService.java:158) [elasticsearch-7.17.6.jar:7.17.6]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.elasticsearch.cluster.service.MasterService$Batcher.lambda$onTimeout$1(MasterService.java:157) [elasticsearch-7.17.6.jar:7.17.6]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:718) [elasticsearch-7.17.6.jar:7.17.6]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

### 4. Expected behaviour

1. We believe that the above exceptions `ProcessClusterEventTimeoutException` and `java.lang.IllegalStateException` should be logged as `ERROR` or `WARN` to facilitate investigation of such issues.

2. It is also unclear to us whether it is a normal behaviour where the master node gets overwhelmed processing thousands of such `create-index` requests. Perhaps this should be discussed in a different issue, but let us know your thoughts about this (the main thing in this issue is about the logging).

### 5. Steps to Reproduce

1. Create a cluster in ESS, version 8.14.0

3. Enable logs&metrics

4. Run the below APIs:

a) First index creation (success)

```
PUT %3Cmy-index-%7Bnow%2Fd%7D-000001%3E
{
  "aliases": {
    "my-write-alias": { 
      "is_write_index": true
    }
  }
}
```

b) Second index creation (failure)
```
PUT %3Cmy-index-%7Bnow%2Fd%7D-000002%3E
{
  "aliases": {
    "my-write-alias": { 
      "is_write_index": true
    }
  }
}
```

Observe the corresponding error/response:

```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_state_exception",
        "reason": "alias [my-write-alias] has more than one write index [my-index-2024.06.12-000002,my-index-2024.06.12-000001]"
      }
    ],
    "type": "illegal_state_exception",
    "reason": "alias [my-write-alias] has more than one write index [my-index-2024.06.12-000002,my-index-2024.06.12-000001]"
  },
  "status": 500
}
```

5. Check the Elasticsearch logs and observe that there are no errors related to the second index creation

6. Enable debug logging:

```
PUT _cluster/settings
{
  "transient": {
    "logger.org.elasticsearch.cluster.metadata.MetadataCreateIndexService": "DEBUG"
  }
}
```

7. Run again the below API:

```
PUT %3Cmy-index-%7Bnow%2Fd%7D-000002%3E
{
  "aliases": {
    "my-write-alias": { 
      "is_write_index": true
    }
  }
}
```

8. Check the ES logs and observe the below log line with `java.lang.IllegalStateException` in `DEBUG` log level:

```
[2024-06-12T07:05:57,970][DEBUG][org.elasticsearch.cluster.metadata.MetadataCreateIndexService] [instance-0000000000] [my-index-2024.06.12-000002] failed to create
java.lang.IllegalStateException: alias [my-write-alias] has more than one write index [my-index-2024.06.12-000002,my-index-2024.06.12-000001]
	at org.elasticsearch.cluster.metadata.Metadata$Builder.validateAlias(Metadata.java:2661) ~[elasticsearch-8.14.0.jar:?]
	at org.elasticsearch.cluster.metadata.Metadata.withAddedIndex(Metadata.java:628) ~[elasticsearch-8.14.0.jar:?]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.clusterStateCreateIndex(MetadataCreateIndexService.java:1239) ~[elasticsearch-8.14.0.jar:?]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.lambda$applyCreateIndexWithTemporaryService$2(MetadataCreateIndexService.java:509) ~[elasticsearch-8.14.0.jar:?]
	at org.elasticsearch.indices.IndicesService.withTempIndexService(IndicesService.java:708) ~[elasticsearch-8.14.0.jar:?]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexWithTemporaryService(MetadataCreateIndexService.java:471) ~[elasticsearch-8.14.0.jar:?]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequestWithV1Templates(MetadataCreateIndexService.java:594) ~[elasticsearch-8.14.0.jar:?]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:421) ~[elasticsearch-8.14.0.jar:?]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService$1.execute(MetadataCreateIndexService.java:300) ~[elasticsearch-8.14.0.jar:?]
	at org.elasticsearch.cluster.service.MasterService$UnbatchedExecutor.execute(MasterService.java:550) ~[elasticsearch-8.14.0.jar:?]
	at org.elasticsearch.cluster.service.MasterService.innerExecuteTasks(MasterService.java:1039) ~[elasticsearch-8.14.0.jar:?]
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:1004) ~[elasticsearch-8.14.0.jar:?]
	at org.elasticsearch.cluster.service.MasterService.executeAndPublishBatch(MasterService.java:232) ~[elasticsearch-8.14.0.jar:?]
	at org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.lambda$run$2(MasterService.java:1645) ~[elasticsearch-8.14.0.jar:?]
	at org.elasticsearch.action.ActionListener.run(ActionListener.java:356) ~[elasticsearch-8.14.0.jar:?]
	at org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.run(MasterService.java:1642) ~[elasticsearch-8.14.0.jar:?]
	at org.elasticsearch.cluster.service.MasterService$5.lambda$doRun$0(MasterService.java:1237) ~[elasticsearch-8.14.0.jar:?]
	at org.elasticsearch.action.ActionListener.run(ActionListener.java:356) ~[elasticsearch-8.14.0.jar:?]
	at org.elasticsearch.cluster.service.MasterService$5.doRun(MasterService.java:1216) ~[elasticsearch-8.14.0.jar:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984) ~[elasticsearch-8.14.0.jar:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.14.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

**Comment by DaveCTurner** [comment] 2024-06-12 09:08
This logging behaviour is by design: exceptions that relate directly to invalid client requests are normally not logged, because otherwise a badly-behaved or malicious client could fill the logs with overwhelming noise. It's up to the client to react to (or expose in its logs) these exceptions.

The fact that a badly-behaved or malicious client can also overwhelm the master with such requests is indeed a known problem, tracked at https://github.com/elastic/elasticsearch/issues/99285. I'm closing this as a duplicate of that issue.

**Closed by DaveCTurner** 2024-06-12 09:08 UTC
Labels: >bug, needs:triage
