### ISSUE TITLE
The MIPS architecture failed to start ES

### ISSUE THREAD

**Issue by xidiandb** [elastic/elasticsearch#68428] opened 2021-02-03 08:13 UTC
**Elasticsearch version** (`bin/elasticsearch --version`):
 7.9.2
**Plugins installed**: []

**JVM version** (`java -version`):
openjdk-13
**OS version** (`uname -a` if on a Unix-like system):
Linux infra01 4.19.90-1.nk7_5.27.2.mips64el #1 SMP PREEMPT Thu Jan 7 18:00:18 CST 2021 mips64el mips64el mips64el GNU/Linux
**Description of the problem including expected versus actual behavior**:
When I tried to start ES:
```
[2021-02-03T02:12:23,427][WARN ][o.e.b.JNANatives         ] [a967884c1698] unable to install syscall filter: 
java.lang.UnsupportedOperationException: seccomp unavailable: 'mips64el' architecture unsupported
	at org.elasticsearch.bootstrap.SystemCallFilter.linuxImpl(SystemCallFilter.java:266) ~[elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.bootstrap.SystemCallFilter.init(SystemCallFilter.java:617) ~[elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.bootstrap.JNANatives.tryInstallSystemCallFilter(JNANatives.java:260) [elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.bootstrap.Natives.tryInstallSystemCallFilter(Natives.java:113) [elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:116) [elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178) [elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393) [elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) [elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161) [elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127) [elasticsearch-cli-7.9.2.jar:7.9.2]
	at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-7.9.2.jar:7.9.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126) [elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) [elasticsearch-7.9.2.jar:7.9.2]
```
**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1.Find a MIPS machine
 2.Install the es
 3.Start the es

**Provide logs (if relevant)**:

![image](https://user-images.githubusercontent.com/12483608/106717005-11574380-663a-11eb-89ae-485eaaf66267.png)

**Comment by DaveCTurner** [comment] 2021-02-04 13:41
Effectively a duplicate of https://github.com/elastic/elasticsearch/issues/61406: as the message says, MIPS is not a [supported architecture](https://www.elastic.co/support/matrix). That's a deliberate choice, not a bug, so I am closing this.

**Closed by DaveCTurner** 2021-02-04 13:41 UTC
Labels: >bug, needs:triage

**Comment by xidiandb** [comment] 2021-02-05 08:08
@DaveCTurner  Why，Big brother

**Comment by DaveCTurner** [comment] 2021-02-05 17:11
Adding support for additional processor architectures is not something we [undertake lightly](https://github.com/elastic/elasticsearch/issues/54930#issuecomment-610690848) since it entails a good deal of ongoing effort in testing and maintenance. Today we cannot justify that effort, we only know of a small minority of users wanting to run Elasticsearch on MIPS-based machines. The costs still enormously outweigh the benefits so we will not be adding MIPS support.

We monitor the situation on an ongoing basis; if we start to see compelling reasons to add support for additional processor architectures then we will reconsider.
