### ISSUE TITLE
TimeThrottleIntegrationTests testTimeThrottleDefaults failure

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#95875] opened 2023-05-05 11:30 UTC
### CI Link

https://gradle-enterprise.elastic.co/s/5myw2twx435xi

### Repro line

`./gradlew ':x-pack:plugin:watcher:internalClusterTest' --tests "org.elasticsearch.xpack.watcher.actions.TimeThrottleIntegrationTests.testTimeThrottleDefaults" -Dtests.seed=EC68403920230004 -Dtests.locale=es -Dtests.timezone=Asia/Oral -Druntime.java=20`

### Does it reproduce?

No

### Applicable branches

main

### Failure history

In the past 7 days this is the first time it's failing `https://gradle-enterprise.elastic.co/scans/tests?search.timeZoneId=Europe/Bucharest&tests.container=org.elasticsearch.xpack.watcher.actions.TimeThrottleIntegrationTests&tests.test=testTimeThrottleDefaults`

### Failure excerpt

```
org.elasticsearch.xpack.watcher.actions.TimeThrottleIntegrationTests > testTimeThrottleDefaults FAILED
    java.lang.AssertionError: 
    Expected: is one of {<3L>, <4L>}
         but: was <2L>
        at __randomizedtesting.SeedInfo.seed([EC68403920230004:504646CBD1BA7D6E]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.watcher.actions.TimeThrottleIntegrationTests.assertTotalHistoryEntries(TimeThrottleIntegrationTests.java:120)
        at org.elasticsearch.xpack.watcher.actions.TimeThrottleIntegrationTests.testTimeThrottleDefaults(TimeThrottleIntegrationTests.java:84)
```

**Comment by masseyke** [comment] 2023-05-08 22:37
This looks like another one caused by making watcher history writes async (#94133). This is similar to #94836 and #94728, and I think can be fixed with just an assertBusy.

**Closed** 2023-05-09 18:02 UTC
Labels: >test-failure, :Data Management/Watcher, Team:Data Management
