### ISSUE TITLE
[CI] Failure in org.elasticsearch.indices.state.RareClusterStateIT.testDelayedMappingPropagationOnReplica

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#36813] opened 2018-12-19 03:38 UTC
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/379/

Does not reproduce
```
./gradlew :server:integTest -Dtests.seed=F9699D9733C3983F \
  -Dtests.class=org.elasticsearch.indices.state.RareClusterStateIT \
  -Dtests.method="testDelayedMappingPropagationOnReplica" \
  -Dtests.security.manager=true -Dtests.locale=ar-TN -Dtests.timezone=Asia/Yakutsk \
  -Dcompiler.java=11 -Druntime.java=8
```
```
02:01:35   1> [2018-12-19T11:01:22,864][INFO ][o.e.i.s.RareClusterStateIT] [testDelayedMappingPropagationOnReplica] [RareClusterStateIT#testDelayedMappingPropagationOnReplica]: cleaned up after test
02:01:35   1> [2018-12-19T11:01:22,864][INFO ][o.e.i.s.RareClusterStateIT] [testDelayedMappingPropagationOnReplica] after test
02:01:35 FAILURE 29.9s J4 | RareClusterStateIT.testDelayedMappingPropagationOnReplica <<< FAILURES!
02:01:35    > Throwable #1: java.lang.AssertionError: 
02:01:35    > Expected: an instance of org.elasticsearch.action.index.IndexResponse
02:01:35    >      but: null
02:01:35    > 	at __randomizedtesting.SeedInfo.seed([F9699D9733C3983F:85175C586324A3DC]:0)
02:01:35    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
02:01:35    > 	at org.elasticsearch.indices.state.RareClusterStateIT.lambda$testDelayedMappingPropagationOnReplica$5(RareClusterStateIT.java:413)
02:01:35    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:847)
02:01:35    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:821)
02:01:35    > 	at org.elasticsearch.indices.state.RareClusterStateIT.testDelayedMappingPropagationOnReplica(RareClusterStateIT.java:409)
02:01:35    > 	at java.lang.Thread.run(Thread.java:748)
02:01:35    > 	Suppressed: java.lang.AssertionError: 
02:01:35    > Expected: an instance of org.elasticsearch.action.support.master.AcknowledgedResponse
02:01:35    >      but: null
```

Previous email threads suggest there's a connection to https://github.com/elastic/elasticsearch/issues/33673

**Comment by original-brownbear** [comment] 2018-12-19 18:48
This looks like the test may have just been very slow for some reason. Looking at the fact that it polled 10 times (so more than half a second) for the `AcknowledgedResponse` when locally this this busy assert takes me less than 10ms.
Also, there's this in the logs:

```
ERROR: JVM J0 ended with an exception: Forked process returned with error code: 137. Very likely a JVM crash.  See process stderr at: /var/lib/jenkins/workspace/elastic+elasticsearch+master+periodic/server/build/testrun/integTest/temp/junit4-J0-20181219_015515_2601288045382664915697.syserr
	at com.carrotsearch.ant.tasks.junit4.JUnit4.executeSlave(JUnit4.java:1542)
	at com.carrotsearch.ant.tasks.junit4.JUnit4.access$000(JUnit4.java:123)
	at com.carrotsearch.ant.tasks.junit4.JUnit4$2.call(JUnit4.java:997)
	at com.carrotsearch.ant.tasks.junit4.JUnit4$2.call(JUnit4.java:994)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

=> seems like the kernel OOM killer killed a test JVM? ... hard to tell but maybe the system was so overloaded that the JVM process almost froze (from swapping or so) and simply timed out.
I also can't find anything obviously wrong in the cluster logs (and the logging is set to globally debug here). 

This is not the same failure as in other failing runs of this test that email threads reference. In those a non-polling ack assert failed, this one:

```java
        assertAcked(client().admin().indices().prepareUpdateSettings("index").setSettings(Settings.builder()
                .put("index.routing.allocation.include._name", "")).get());
```

=> I'd close this and reopen if it comes up again, since a timeout in a test run that eventually ran into the OOM killer is really suspicious? :)

**Comment by original-brownbear** [comment] 2019-01-05 19:18
Never mind the above comment, this test has failed a bunch of times again, e.g.
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=java8fips,nodes=virtual&&linux/162/consoleText

=> looking into it again.

**Comment by atorok** [comment] 2019-01-28 15:31
I observed this failure on a Centos 7 VM after ~ 1 hour of running internal cluster tests in a loop. Stack trace is different not sure if it's related. I haven't experienced slowness on CentOS in CI so far.
```
2> REPRODUCE WITH: ./gradlew :server:integTest -Dtests.seed=BD345D2CF064C409 -Dtests.class=org.elasticsearch.indices.state.RareClusterStateIT -Dtests.method="testDelayedMappingPropagationOnReplica" -Dtests.security.manager=true -Dtests.locale=br-FR -Dtests.timezone=Asia/Jerusalem -Dcompiler.java=11 -Druntime.java=11
FAILURE 3.55s J2 | RareClusterStateIT.testDelayedMappingPropagationOnReplica <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: AcknowledgedResponse failed - not acked
   > Expected: <true>
   >      but: was <false>
   >    at __randomizedtesting.SeedInfo.seed([BD345D2CF064C409:C14A9CE3A083FFEA]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked(ElasticsearchAssertions.java:112)
   >    at org.elasticsearch.indices.state.RareClusterStateIT.testDelayedMappingPropagationOnReplica(RareClusterStateIT.java:340)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   >    at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by atorok** [comment] 2019-01-28 15:32
Here's another recent repro for the one in the description: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1209/

**Comment by pgomulka** [comment] 2019-01-30 10:10
another failure. does not reproduce for me locally as well
`
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+internalClusterTest/131/console
`

```
./gradlew :server:integTest \
  -Dtests.seed=37FF28E573A0046A \
  -Dtests.class=org.elasticsearch.indices.state.RareClusterStateIT \
  -Dtests.method="testDelayedMappingPropagationOnReplica" \
  -Dtests.security.manager=true \
  -Dtests.locale=ga \
  -Dtests.timezone=Atlantic/Faeroe \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

**Comment by cbuescher** [comment] 2019-02-04 14:49
Still seems to fail on master:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+internalClusterTest/499/console

```
 ./gradlew :server:integTest \
  -Dtests.seed=7F2D32832D1B9B3B \
  -Dtests.class=org.elasticsearch.cluster.coordination.RareClusterStateIT \
  -Dtests.method="testDelayedMappingPropagationOnReplica" \
  -Dtests.security.manager=true \
  -Dtests.locale=en-SG \
  -Dtests.timezone=Australia/NSW \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

```
15:28:12 FAILURE 10.5s J0 | RareClusterStateIT.testDelayedMappingPropagationOnReplica <<< FAILURES!
15:28:12    > Throwable #1: java.lang.AssertionError
15:28:12    > 	at __randomizedtesting.SeedInfo.seed([7F2D32832D1B9B3B:353F34C7DFCA0D8]:0)
15:28:12    > 	at org.elasticsearch.cluster.coordination.RareClusterStateIT.lambda$testDelayedMappingPropagationOnReplica$4(RareClusterStateIT.java:346)
15:28:12    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:858)
15:28:12    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:832)
15:28:12    > 	at org.elasticsearch.cluster.coordination.RareClusterStateIT.testDelayedMappingPropagationOnReplica(RareClusterStateIT.java:340)
15:28:12    > 	at java.lang.Thread.run(Thread.java:748)
15:28:12    > 	Suppressed: java.lang.AssertionError
15:28:12    > 		at org.elasticsearch.cluster.coordination.RareClusterStateIT.lambda$testDelayedMappingPropagationOnReplica$4(RareClusterStateIT.java:346)
15:28:12    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:846)
15:28:12    > 		... 39 more
```

**Comment by cbuescher** [comment] 2019-02-04 14:51
Some more failures over the weekend that look related to me:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+internalClusterTest/392/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+internalClusterTest/306/console

**Comment by cbuescher** [comment] 2019-02-04 19:30
Another one: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+internalClusterTest/513/console

**Comment by cbuescher** [comment] 2019-02-04 21:30
Muted with  0ced775.

**Comment by original-brownbear** [comment] 2019-02-08 19:31
I could reproduce this one with the seed from https://github.com/elastic/elasticsearch/issues/36813#issuecomment-460275993 (hundreds of runs though). Attached the logs of the failure here +  working on it now.
[full-logs.txt](https://github.com/elastic/elasticsearch/files/2846581/full-logs.txt)

**Comment by original-brownbear** [comment] 2019-02-08 21:42
Figured out what's causing this.
The `assertBusy` in `org.elasticsearch.cluster.coordination.RareClusterStateIT#executeAndCancelCommittedPublication` randomly (every few 100 runs) takes 15s (pretty much exactly 15s every time) to pass.

Every time this happens the following is logged:

```sh
[2019-02-09T08:36:21,673][DEBUG][o.e.c.c.ElectionSchedulerFactory] [node_t0] scheduleNextElection{gracePeriod=500ms, thisAttempt=1, maxDelayMillis=200, delayMillis=697, ElectionScheduler{attempt=2, ElectionSchedulerFactory{initialTimeout=100ms, backoffTime=100ms, maxTimeout=10s}}} not starting election
[2019-02-09T08:36:37,588][DEBUG][o.e.c.s.ClusterApplierService] [node_t0] processing [Publication{term=1, version=9}]: execute
```

will figure where we're hanging tomorrow, but upping the timeout to say 1 minute would fix this test for sure as far as I can see already.

**Comment by iverase** [comment] 2019-02-15 09:13
It seems the test is still failing in master:


https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+internalClusterTest/1213/console

```
REPRODUCE WITH: ./gradlew :server:integTest \
  -Dtests.seed=A69C259BE17CC12C \
  -Dtests.class=org.elasticsearch.cluster.coordination.RareClusterStateIT \
  -Dtests.method="testDelayedMappingPropagationOnReplica" \
  -Dtests.security.manager=true \
  -Dtests.locale=ms \
  -Dtests.timezone=America/Creston \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=java11,nodes=immutable&&linux&&docker/243/console

```
REPRODUCE WITH: ./gradlew :server:integTest \
  -Dtests.seed=9F5F7DA15796856F \
  -Dtests.class=org.elasticsearch.cluster.coordination.RareClusterStateIT \
  -Dtests.method="testDelayedMappingPropagationOnReplica" \
  -Dtests.security.manager=true \
  -Dtests.locale=fr-NE \
  -Dtests.timezone=Africa/Brazzaville \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

They don't reproduce locally.

**Comment by original-brownbear** [comment] 2019-02-15 09:19
Hmpf ... it's a different failure now though it seems. We're now failing on a different step => I'm on it again.

**Comment by hendrikmuhs** [comment] 2019-02-19 08:03
another one: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+internalClusterTest/1485/consoleFull

**Comment by hendrikmuhs** [comment] 2019-02-19 10:49
again: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+internalClusterTest/1498/console

I will mute this test for now

**Comment by gwbrown** [comment] 2019-03-01 17:09
This popped up again today: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+internalClusterTest/1491/console

**Comment by droberts195** [comment] 2019-03-08 13:29
Another one in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+intake/483/consoleText:

```
FAILURE 10.5s J0 | RareClusterStateIT.testDelayedMappingPropagationOnReplica <<< FAILURES!
   > Throwable #1: java.lang.AssertionError
   > 	at __randomizedtesting.SeedInfo.seed([EAED3B7AC230EC8E:9693FAB592D7D76D]:0)
   > 	at org.elasticsearch.cluster.coordination.RareClusterStateIT.lambda$testDelayedMappingPropagationOnReplica$4(RareClusterStateIT.java:340)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:862)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:836)
   > 	at org.elasticsearch.cluster.coordination.RareClusterStateIT.testDelayedMappingPropagationOnReplica(RareClusterStateIT.java:334)
   > 	at java.lang.Thread.run(Thread.java:748)
   > 	Suppressed: java.lang.AssertionError
   > 		at org.elasticsearch.cluster.coordination.RareClusterStateIT.lambda$testDelayedMappingPropagationOnReplica$4(RareClusterStateIT.java:340)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:850)
   > 		... 39 more
```

A little bit higher up is:

```
  1> java.lang.IllegalStateException: transport has been stopped
  1> 	at org.elasticsearch.transport.TcpTransport.ensureOpen(TcpTransport.java:1123) ~[main/:?]
  1> 	at org.elasticsearch.transport.TcpTransport.openConnection(TcpTransport.java:291) ~[main/:?]
  1> 	at org.elasticsearch.transport.ConnectionManager.internalOpenConnection(ConnectionManager.java:206) ~[main/:?]
  1> 	at org.elasticsearch.transport.ConnectionManager.openConnection(ConnectionManager.java:80) ~[main/:?]
  1> 	at org.elasticsearch.transport.TransportService.openConnection(TransportService.java:367) ~[main/:?]
  1> 	at org.elasticsearch.discovery.HandshakingTransportAddressConnector$1.doRun(HandshakingTransportAddressConnector.java:82) [main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:747) [main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [main/:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
  1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
```

I have no idea if that's the same as the other failures that have been seen in the last month as nobody has said in this issue what the failures in the last month were (beyond the name of the test).

It doesn't reproduce locally using:

```
./gradlew :server:integTest \
  -Dtests.seed=EAED3B7AC230EC8E \
  -Dtests.class=org.elasticsearch.cluster.coordination.RareClusterStateIT \
  -Dtests.method="testDelayedMappingPropagationOnReplica" \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-Latn \
  -Dtests.timezone=UCT \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

I muted the test for 7.x in aec2db78eafa3447e86528b65f3fb296fd29e137 (and it was already muted in master)

**Comment by ywelsch** [comment] 2019-05-07 11:35
@original-brownbear as this test has been muted for a while and there is no recent failures with logs, and I can't reproduce  this locally, should we enable the test again on master to get a recent failure?

**Comment by original-brownbear** [comment] 2019-05-07 11:47
Sure I opened https://github.com/elastic/elasticsearch/pull/41884

**Comment by original-brownbear** [comment] 2019-05-22 06:42
This just failed again on `master` https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/3639/testReport/junit/org.elasticsearch.cluster.coordination/RareClusterStateIT/testDelayedMappingPropagationOnReplica/ looking into it now

**Closed** 2019-05-27 09:31 UTC
Labels: :Distributed/Distributed, >test-failure
