### ISSUE TITLE
[docs] full list of all configuration settings

### ISSUE THREAD

**Issue by shaharmor** [elastic/elasticsearch#20561] opened 2016-09-19 16:33 UTC
**Describe the feature**: At the moment there is no single point of truth of all possible Elasticsearch settings.
By that i mean both settings that are configured in the `elasticsearch.yml` & ones that are configured on a specific index (For example in a template).

It would be extremely helpful to have a single page where you can just search for settings and read about them.

Thanks

**Comment by s1monw** [comment] 2016-09-19 16:43
in 5.x you can query cluster and index settings and include defaults this will give you all settings available and their current settings. does this help  with this? On the yaml file you can't set any index settings anymore so the clsuter endpoint returns all settings that are settable in the yaml and are updateable via clusterstate

**Comment by shaharmor** [comment] 2016-09-19 17:11
It's better than nothing, but what I was talking about is a web page on elastic.co, because it's way more accessible than querying ES. (You might even not have access to query it).

I can say from my recent experience upgrading to ES 2.4, that I had to search heavily in Google to find docs about some settings (some i think that i didn't even find), and a page containing all of them could have been really helpful.

I also think that listing old settings and marking them as removed would be good to have.

**Comment by nik9000** [comment] 2016-09-19 18:28
If we can make the page in such a way that it can't go out of date I'd be happy to have it. Given that we can query elasticsearch for a list of settings now I think it'd be possible to rig up a build-time check that the page has all the settings.

If the page goes out of date constantly it'd make for a fairly sneaky trap, which is why we've never wanted to do it in the past.

**Comment by clintongormley** [comment] 2016-09-20 06:28
Duplicate of #11504

**Closed by clintongormley** 2016-09-20 06:28 UTC
