### ISSUE TITLE
[CI] task ':plugins:repository-hdfs:haHdfs2Fixture' failing

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#107105] opened 2024-04-04 14:06 UTC
### CI Link

https://gradle-enterprise.elastic.co/s/qj4m5zeidpqji

### Repro line

none

### Does it reproduce?

Yes

### Applicable branches

7.17

### Failure excerpt

```
java.io.IOException: java.lang.RuntimeException: Could not resolve Kerberos principal name: java.net.UnknownHostException: i-0827c96753d4ac016.us-west-2.compute.internal: i-0827c96753d4ac016.us-west-2.compute.internal: Name or service not known |  
-- | --
  | at org.apache.hadoop.http.HttpServer2.<init>(HttpServer2.java:396) |  
  | at org.apache.hadoop.http.HttpServer2.<init>(HttpServer2.java:111) |  
  | at org.apache.hadoop.http.HttpServer2$Builder.build(HttpServer2.java:325) |  
  | at org.apache.hadoop.hdfs.server.namenode.NameNodeHttpServer.start(NameNodeHttpServer.java:155) |  
  | at org.apache.hadoop.hdfs.server.namenode.NameNode.startHttpServer(NameNode.java:842) |  
  | at org.apache.hadoop.hdfs.server.namenode.NameNode.initialize(NameNode.java:693) |  
  | at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:906) |  
  | at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:885) |  
  | at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1626) |  
  | at org.apache.hadoop.hdfs.MiniDFSCluster.createNameNode(MiniDFSCluster.java:1162) |  
  | at org.apache.hadoop.hdfs.MiniDFSCluster.createNameNodesAndSetConf(MiniDFSCluster.java:1037) |  
  | at org.apache.hadoop.hdfs.MiniDFSCluster.initMiniDFSCluster(MiniDFSCluster.java:830) |  
  | at org.apache.hadoop.hdfs.MiniDFSCluster.<init>(MiniDFSCluster.java:485) |  
  | at org.apache.hadoop.hdfs.MiniDFSCluster$Builder.build(MiniDFSCluster.java:444) |  
  | at hdfs.MiniHDFS.main(MiniHDFS.java:114) |  
  | Caused by: java.lang.RuntimeException: Could not resolve Kerberos principal name: java.net.UnknownHostException: i-0827c96753d4ac016.us-west-2.compute.internal: i-0827c96753d4ac016.us-west-2.compute.internal: Name or service not known |  
  | at org.apache.hadoop.security.AuthenticationFilterInitializer.getFilterConfigMap(AuthenticationFilterInitializer.java:90) |  
  | at org.apache.hadoop.http.HttpServer2.getFilterProperties(HttpServer2.java:508) |  
  | at org.apache.hadoop.http.HttpServer2.constructSecretProvider(HttpServer2.java:499) |  
  | at org.apache.hadoop.http.HttpServer2.<init>(HttpServer2.java:388) |  
  | ... 14 more |  
  | Caused by: java.net.UnknownHostException: i-0827c96753d4ac016.us-west-2.compute.internal: i-0827c96753d4ac016.us-west-2.compute.internal: Name or service not known |  
  | at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1647) |  
  | at org.apache.hadoop.security.SecurityUtil.getLocalHostName(SecurityUtil.java:230) |  
  | at org.apache.hadoop.security.SecurityUtil.replacePattern(SecurityUtil.java:198) |  
  | at org.apache.hadoop.security.SecurityUtil.getServerPrincipal(SecurityUtil.java:153) |  
  | at org.apache.hadoop.security.AuthenticationFilterInitializer.getFilterConfigMap(AuthenticationFilterInitializer.java:87) |  
  | ... 17 more |  
  | Caused by: java.net.UnknownHostException: i-0827c96753d4ac016.us-west-2.compute.internal: Name or service not known |  
  | at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) |  
  | at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:933) |  
  | at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1519) |  
  | at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852) |  
  | at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509) |  
  | at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1642) |  
  | ... 21 more |  
  | 2024-04-04 12:47:20,663 INFO  [main] hdfs.MiniDFSCluster (MiniDFSCluster.java:shutdown(1789)) - Shutting down the Mini HDFS Cluster
```

**Comment by masseyke** [comment] 2024-04-05 14:08
It looks like this happens very frequently on 7.17, but I don't see any failures for months in 8.x. @breskeby tells me that they've done a lot of work on stabilizing this in 8. I'm tempted to mark this as won't fix because it's not worth the effort to backport the test fixture improvements. What do you think @breskeby @dakrone @jbaiera ?

**Comment by dakrone** [comment] 2024-04-23 15:11
@masseyke it's marked as reproducing, is it something that would affect production systems at all?

**Comment by masseyke** [comment] 2024-04-23 21:48
The fixes were in the test fixture, not in production code.

**Closed** 2024-11-05 21:47 UTC
Labels: >test-failure, Team:Data Management, low-risk, :Data Management/HDFS
